Etterna: NoteDisplay.h File Reference
NoteDisplay.h File Reference
#include "Actor.h"
#include "CubicSpline.h"
#include "GameInput.h"
#include "NoteData.h"
#include "PlayerNumber.h"
Classes
struct NoteColorActor
struct NoteColorSprite
struct NoteFieldRenderArgs
struct NCSplineHandler
struct NoteColumnRenderArgs
class NoteDisplay
Draws TapNotes and HoldNotes.
struct NoteDisplay::draw_hold_part_args
struct NoteColumnRenderer
struct NoteColumnRenderer::NCR_TweenState
Macros
#define FOREACH_HoldType(i) FOREACH_ENUM(HoldType, i)
Loop through each HoldType.
#define FOREACH_ActiveType(i) FOREACH_ENUM(ActiveType, i)
Loop through each ActiveType.
Enumerations
enum NotePart {
NotePart_Tap, NotePart_Mine, NotePart_Lift, NotePart_Fake,
NotePart_HoldHead, NotePart_HoldTail, NotePart_HoldTopCap, NotePart_HoldBody,
NotePart_HoldBottomCap, NUM_NotePart, NotePart_Invalid
}
the various parts of a Note.
enum NoteColorType { NoteColorType_Denominator, NoteColorType_Progress, NUM_NoteColorType, NoteColorType_Invalid }
the color type of a Note.
enum HoldType { hold, roll, NUM_HoldType, HoldType_Invalid }
What types of holds are there?
enum ActiveType { active, inactive, NUM_ActiveType, ActiveType_Invalid }
enum NoteColumnSplineMode {
NCSM_Disabled, NCSM_Offset, NCSM_Position, NUM_NoteColumnSplineMode,
NoteColumnSplineMode_Invalid
}
Functions
const RString & NoteColorTypeToString (NoteColorType nct)
NoteColorType StringToNoteColorType (const RString &s)
const RString & HoldTypeToString (HoldType ht)
const RString & ActiveTypeToString (ActiveType at)
const RString & NoteColumnSplineModeToString (NoteColumnSplineMode ncsm)
LuaDeclareType (NoteColumnSplineMode)
Detailed Description
NoteColumnRenderer and associated spline stuff (c) Eric Reese 2014-2015
Author
Brian Bugh, Ben Nordstrom, Chris Danford, Steve Checkoway (c) 2001-2006
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
FOREACH_ActiveType
#define FOREACH_ActiveType (i) FOREACH_ENUM(ActiveType, i)
Loop through each ActiveType.
Referenced by NoteDisplay::Load().
FOREACH_HoldType
#define FOREACH_HoldType (i) FOREACH_ENUM(HoldType, i)
Loop through each HoldType.
Referenced by NoteDisplay::Load().
Enumeration Type Documentation
ActiveType
enum ActiveType
Enumerator
active
inactive
NUM_ActiveType
ActiveType_Invalid
HoldType
enum HoldType
What types of holds are there?
Enumerator
hold
Merely keep your foot held on the body for it to count.
roll
Keep hitting the hold body for it to stay alive.
NUM_HoldType
HoldType_Invalid
NoteColorType
enum NoteColorType
the color type of a Note.
Enumerator
NoteColorType_Denominator
Color by note type.
NoteColorType_Progress
Color by progress.
NUM_NoteColorType
NoteColorType_Invalid
NoteColumnSplineMode
enum NoteColumnSplineMode
Enumerator
NCSM_Disabled
NCSM_Offset
NCSM_Position
NUM_NoteColumnSplineMode
NoteColumnSplineMode_Invalid
NotePart
enum NotePart
the various parts of a Note.
Enumerator
NotePart_Tap
The part representing a traditional TapNote.
NotePart_Mine
The part representing a mine.
NotePart_Lift
The part representing a lift note.
NotePart_Fake
The part representing a fake note.
NotePart_HoldHead
The part representing a hold head.
NotePart_HoldTail
The part representing a hold tail.
NotePart_HoldTopCap
The part representing a hold's top cap.
NotePart_HoldBody
The part representing a hold's body.
NotePart_HoldBottomCap
The part representing a hold's bottom cap.
NUM_NotePart
NotePart_Invalid
Function Documentation
ActiveTypeToString()
const RString& ActiveTypeToString (ActiveType at)
Referenced by NoteDisplay::Load().
HoldTypeToString()
const RString& HoldTypeToString (HoldType ht)
Referenced by NoteDisplay::Load().
LuaDeclareType()
LuaDeclareType (NoteColumnSplineMode)
NoteColorTypeToString()
const RString& NoteColorTypeToString (NoteColorType nct)
NoteColumnSplineModeToString()
const RString& NoteColumnSplineModeToString (NoteColumnSplineMode ncsm)
StringToNoteColorType()
NoteColorType StringToNoteColorType (const RString & s)
Referenced by NoteMetricCache_t::Load().