Etterna: RageSoundDriver_PulseAudio Class Reference
RageSoundDriver_PulseAudio Class Reference
#include <RageSoundDriver_PulseAudio.h>
Public Member Functions
RageSoundDriver_PulseAudio ()
virtual ~RageSoundDriver_PulseAudio ()
RString Init ()
int64_t GetPosition () const
int GetSampleRate () const
void CtxStateCb (pa_context *c)
void StreamStateCb (pa_stream *s)
void StreamWriteCb (pa_stream *s, size_t length)
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
virtual float GetPlayLatency () const
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Public Member Functions
static void StaticCtxStateCb (pa_context *c, void *user)
static void StaticStreamStateCb (pa_stream *s, void *user)
static void StaticStreamWriteCb (pa_stream *s, size_t length, void *user)
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Protected Member Functions
void m_InitStream ()
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
virtual void SetupDecodingThread ()
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Protected Attributes
int64_t m_LastPosition
int m_SampleRate
char * m_Error
RageSemaphore m_Sem
pa_threaded_mainloop * m_PulseMainLoop
pa_context * m_PulseCtx
pa_stream * m_PulseStream
Additional Inherited Members
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Constructor & Destructor Documentation
RageSoundDriver_PulseAudio()
RageSoundDriver_PulseAudio::RageSoundDriver_PulseAudio ()
References PrefsManager::m_iSoundPreferredSampleRate, m_SampleRate, and PREFSMAN.
~RageSoundDriver_PulseAudio()
RageSoundDriver_PulseAudio::~RageSoundDriver_PulseAudio () virtual
References m_Error, m_PulseCtx, and m_PulseMainLoop.
Member Function Documentation
CtxStateCb()
void RageSoundDriver_PulseAudio::CtxStateCb (pa_context * c)
References LOG, m_Error, m_InitStream(), m_PulseCtx, m_Sem, RageSemaphore::Post(), and RageLog::Trace().
Referenced by StaticCtxStateCb().
GetPosition()
int64_t RageSoundDriver_PulseAudio::GetPosition () const inline virtual
Implements RageSoundDriver.
References m_LastPosition.
GetSampleRate()
int RageSoundDriver_PulseAudio::GetSampleRate () const inline virtual
Reimplemented from RageSoundDriver.
Init()
RString RageSoundDriver_PulseAudio::Init () virtual
Reimplemented from RageSoundDriver.
References LOG, m_Error, m_PulseCtx, m_PulseMainLoop, m_Sem, ssprintf(), RageSoundDriver::StartDecodeThread(), StaticCtxStateCb(), RageLog::Trace(), and RageSemaphore::Wait().
m_InitStream()
void RageSoundDriver_PulseAudio::m_InitStream (void) protected
References LOG, m_Error, PrefsManager::m_iSoundPreferredSampleRate, m_PulseCtx, m_PulseStream, m_SampleRate, m_Sem, RageSemaphore::Post(), PREFSMAN, StaticStreamStateCb(), StaticStreamWriteCb(), and RageLog::Trace().
Referenced by CtxStateCb().
StaticCtxStateCb()
void RageSoundDriver_PulseAudio::StaticCtxStateCb (pa_context * c, void * user) static
References CtxStateCb().
Referenced by Init().
StaticStreamStateCb()
void RageSoundDriver_PulseAudio::StaticStreamStateCb (pa_stream * s, void * user) static
References StreamStateCb().
Referenced by m_InitStream().
StaticStreamWriteCb()
void RageSoundDriver_PulseAudio::StaticStreamWriteCb (pa_stream * s, size_t length, void * user) static
References StreamWriteCb().
Referenced by m_InitStream().
StreamStateCb()
void RageSoundDriver_PulseAudio::StreamStateCb (pa_stream * s)
References LOG, m_Error, m_PulseCtx, m_PulseStream, m_Sem, RageSemaphore::Post(), and RageLog::Trace().
Referenced by StaticStreamStateCb().
StreamWriteCb()
void RageSoundDriver_PulseAudio::StreamWriteCb (pa_stream * s, size_t length)
References m_LastPosition, m_PulseStream, RageSoundDriver::Mix(), and RageException::Throw().
Referenced by StaticStreamWriteCb().
Member Data Documentation
m_Error
char* RageSoundDriver_PulseAudio::m_Error protected
Referenced by CtxStateCb(), Init(), m_InitStream(), StreamStateCb(), and ~RageSoundDriver_PulseAudio().
m_LastPosition
int64_t RageSoundDriver_PulseAudio::m_LastPosition protected
Referenced by GetPosition(), and StreamWriteCb().
m_PulseCtx
pa_context* RageSoundDriver_PulseAudio::m_PulseCtx protected
Referenced by CtxStateCb(), Init(), m_InitStream(), StreamStateCb(), and ~RageSoundDriver_PulseAudio().
m_PulseMainLoop
pa_threaded_mainloop* RageSoundDriver_PulseAudio::m_PulseMainLoop protected
Referenced by Init(), and ~RageSoundDriver_PulseAudio().
m_PulseStream
pa_stream* RageSoundDriver_PulseAudio::m_PulseStream protected
Referenced by m_InitStream(), StreamStateCb(), and StreamWriteCb().
m_SampleRate
int RageSoundDriver_PulseAudio::m_SampleRate protected
Referenced by m_InitStream(), and RageSoundDriver_PulseAudio().
m_Sem
RageSemaphore RageSoundDriver_PulseAudio::m_Sem protected
Referenced by CtxStateCb(), Init(), m_InitStream(), and StreamStateCb().
The documentation for this class was generated from the following files:
RageSoundDriver_PulseAudio.h
RageSoundDriver_PulseAudio.cpp