Etterna: FilenameDB Class Reference
FilenameDB Class Reference
A container for a file listing.
#include <RageUtil_FileDB.h>
Public Member Functions
FilenameDB ()
virtual ~FilenameDB ()
void AddFile (const RString &sPath, int iSize, int iHash, void *pPriv=NULL)
void DelFile (const RString &sPath)
void * GetFilePriv (const RString &sPath)
void GetFilesSimpleMatch (const RString &sDir, const RString &sFile, vector< RString > &asOut, bool bOnlyDirs)
bool ResolvePath (RString &sPath)
RageFileManager::FileType GetFileType (const RString &sPath)
int GetFileSize (const RString &sPath)
int GetFileHash (const RString &sFilePath)
void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
void FlushDirCache (const RString &sDir=RString())
void GetFileSetCopy (const RString &dir, FileSet &out)
virtual void CacheFile (const RString &sPath)
Protected Member Functions
const File * GetFile (const RString &sPath)
FileSet * GetFileSet (const RString &sDir, bool create=true)
void GetFilesEqualTo (const RString &sDir, const RString &sName, vector< RString > &asOut, bool bOnlyDirs)
void GetFilesMatching (const RString &sDir, const RString &sBeginning, const RString &sContaining, const RString &sEnding, vector< RString > &asOut, bool bOnlyDirs)
void DelFileSet (map< RString, FileSet *>::iterator dir)
virtual void PopulateFileSet (FileSet &, const RString &)
Protected Attributes
RageEvent m_Mutex
map< RString, FileSet * > dirs
int ExpireSeconds { -1 }
Detailed Description
A container for a file listing.
Constructor & Destructor Documentation
FilenameDB()
FilenameDB::FilenameDB () inline
~FilenameDB()
virtual FilenameDB::~FilenameDB () inline virtual
References FlushDirCache().
Member Function Documentation
AddFile()
void FilenameDB::AddFile (const RString & sPath, int iSize, int iHash, void * pPriv = NULL)
References ASSERT, File::dir, f, FileSet::files, GetFileSet(), RageMutex::IsLockedByThisThread(), Rage::join(), m_Mutex, split(), and RageMutex::Unlock().
Referenced by RageFileDriverMountpoints::LoadFromDrivers(), RageFileDriverDirect::Move(), RageFileDriverMem::Open(), and RageFileDriverZip::ParseZipfile().
CacheFile()
void FilenameDB::CacheFile (const RString & sPath) virtual
Reimplemented in NullFilenameDB, and DirectFilenameDB.
References Dirname(), FlushDirCache(), LOG, and RageLog::Warn().
DelFile()
void FilenameDB::DelFile (const RString & sPath)
References DelFileSet(), dirs, FileSet::files, GetFileSet(), LockMut, m_Mutex, StdString::CStdStr< CT >::MakeLower(), SplitPath(), and RageMutex::Unlock().
Referenced by RageFileDriverDirect::Move(), RageFileDriverDirect::Remove(), and RageFileDriverMem::Remove().
DelFileSet()
void FilenameDB::DelFileSet (map< RString, FileSet *>::iterator dir) protected
References ASSERT, File::dirp, dirs, f, FileSet::files, RageMutex::IsLockedByThisThread(), and m_Mutex.
Referenced by DelFile(), and GetFileSet().
FlushDirCache()
void FilenameDB::FlushDirCache (const RString & sDir = RString())
References Basename(), Dirname(), dirs, FileSet::files, RageMutex::Lock(), LOG, FileSet::m_bFilled, m_Mutex, StdString::CStdStr< CT >::MakeLower(), RageMutex::Unlock(), RageEvent::Wait(), and RageLog::Warn().
Referenced by CacheFile(), RageFileDriver::FlushDirCache(), RageFileDriverMountpoints::LoadFromDrivers(), and ~FilenameDB().
GetDirListing()
void FilenameDB::GetDirListing (const RString & sPath, vector< RString > & asAddTo, bool bOnlyDirs, bool bReturnPathToo)
References ASSERT, and GetFilesSimpleMatch().
Referenced by RageFileDriver::GetDirListing().
GetFile()
const File * FilenameDB::GetFile (const RString & sPath) protected
References FileSet::files, GetFileSet(), RageMutex::IsLockedByThisThread(), LOG, m_Mutex, SplitPath(), and RageLog::Warn().
Referenced by GetFilePriv().
GetFileHash()
int FilenameDB::GetFileHash (const RString & sFilePath)
References ASSERT, FileSet::GetFileHash(), GetFileSet(), RageMutex::IsLockedByThisThread(), m_Mutex, SplitPath(), and RageMutex::Unlock().
Referenced by RageFileDriver::GetFileHash(), and RageFileDriverDirect::Move().
GetFilePriv()
void * FilenameDB::GetFilePriv (const RString & sPath)
References ASSERT, GetFile(), RageMutex::IsLockedByThisThread(), m_Mutex, and RageMutex::Unlock().
Referenced by RageFileDriverZip::GetFileInfo(), RageFileDriverZip::Open(), RageFileDriverMem::Open(), and RageFileDriverMem::Remove().
GetFilesEqualTo()
void FilenameDB::GetFilesEqualTo (const RString & sDir, const RString & sName, vector< RString > & asOut, bool bOnlyDirs) protected
References ASSERT, GetFileSet(), RageMutex::IsLockedByThisThread(), m_Mutex, and RageMutex::Unlock().
Referenced by GetFilesSimpleMatch().
GetFileSet()
FileSet * FilenameDB::GetFileSet (const RString & sDir, bool create = true) protected
References FileSet::age, ASSERT, Basename(), RageEvent::Broadcast(), DelFileSet(), Dirname(), dirs, ExpireSeconds, FileSet::files, RageMutex::IsLockedByThisThread(), RageMutex::Lock(), LOG, FileSet::m_bFilled, m_Mutex, StdString::CStdStr< CT >::MakeLower(), RageTimer::PeekDeltaTime(), PopulateFileSet(), StdString::CStdStr< CT >::Replace(), RageTimer::Touch(), RageMutex::Unlock(), RageEvent::Wait(), and RageLog::Warn().
Referenced by AddFile(), DirectFilenameDB::CacheFile(), DelFile(), GetFile(), GetFileHash(), GetFilesEqualTo(), GetFileSetCopy(), GetFileSize(), GetFilesMatching(), GetFileType(), and ResolvePath().
GetFileSetCopy()
void FilenameDB::GetFileSetCopy (const RString & dir, FileSet & out)
References GetFileSet(), m_Mutex, and RageMutex::Unlock().
Referenced by ThreadedFileWorker::HandleRequest().
GetFileSize()
int FilenameDB::GetFileSize (const RString & sPath)
References ASSERT, GetFileSet(), FileSet::GetFileSize(), RageMutex::IsLockedByThisThread(), m_Mutex, SplitPath(), and RageMutex::Unlock().
Referenced by RageFileDriver::GetFileSizeInBytes(), and RageFileDriverDirect::Move().
GetFilesMatching()
void FilenameDB::GetFilesMatching (const RString & sDir, const RString & sBeginning, const RString & sContaining, const RString & sEnding, vector< RString > & asOut, bool bOnlyDirs) protected
References ASSERT, GetFileSet(), RageMutex::IsLockedByThisThread(), m_Mutex, and RageMutex::Unlock().
Referenced by GetFilesSimpleMatch().
GetFilesSimpleMatch()
void FilenameDB::GetFilesSimpleMatch (const RString & sDir, const RString & sFile, vector< RString > & asOut, bool bOnlyDirs)
References GetFilesEqualTo(), and GetFilesMatching().
Referenced by GetDirListing().
GetFileType()
RageFileManager::FileType FilenameDB::GetFileType (const RString & sPath)
References ASSERT, GetFileSet(), FileSet::GetFileType(), RageMutex::IsLockedByThisThread(), m_Mutex, SplitPath(), RageFileManager::TYPE_DIR, and RageMutex::Unlock().
Referenced by RageFileDriver::GetFileType().
PopulateFileSet()
virtual void FilenameDB::PopulateFileSet (FileSet & , const RString &) inline protected virtual
Reimplemented in TimedFilenameDB, and DirectFilenameDB.
Referenced by GetFileSet().
ResolvePath()
bool FilenameDB::ResolvePath (RString & sPath)
References ASSERT_M, FileSet::files, GetFileSet(), RageMutex::Lock(), m_Mutex, split(), and RageMutex::Unlock().
Referenced by RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), DirectFilenameDB::PopulateFileSet(), and RageFileDriverDirect::Remove().
Member Data Documentation
dirs
map<RString, FileSet*> FilenameDB::dirs protected
Referenced by DelFile(), DelFileSet(), FlushDirCache(), and GetFileSet().
ExpireSeconds
int FilenameDB::ExpireSeconds { -1 } protected
Referenced by DirectFilenameDB::DirectFilenameDB(), GetFileSet(), NullFilenameDB::NullFilenameDB(), and TimedFilenameDB::TimedFilenameDB().
m_Mutex
RageEvent FilenameDB::m_Mutex protected
Referenced by AddFile(), DirectFilenameDB::CacheFile(), DelFile(), DelFileSet(), FlushDirCache(), GetFile(), GetFileHash(), GetFilePriv(), GetFilesEqualTo(), GetFileSet(), GetFileSetCopy(), GetFileSize(), GetFilesMatching(), GetFileType(), and ResolvePath().
The documentation for this class was generated from the following files:
RageUtil_FileDB.h
RageUtil_FileDB.cpp