Etterna: InputHandler_DirectInput.cpp File Reference
InputHandler_DirectInput.cpp File Reference
#include "global.h"
#include "InputHandler_DirectInput.h"
#include "Foreach.h"
#include "GamePreferences.h"
#include "InputFilter.h"
#include "InputHandler_DirectInputHelper.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "archutils/Win32/AppInstance.h"
#include "archutils/Win32/DirectXHelpers.h"
#include "archutils/Win32/ErrorStrings.h"
#include "archutils/Win32/GraphicsWindow.h"
#include "archutils/Win32/RegistryAccess.h"
Macros
#define HAT_UP_MASK 1
#define HAT_DOWN_MASK 2
#define HAT_LEFT_MASK 4
#define HAT_RIGHT_MASK 8
Functions
REGISTER_INPUT_HANDLER_CLASS2 (DirectInput, DInput)
static BOOL CALLBACK EnumDevicesCallback (const DIDEVICEINSTANCE *pdidInstance, void *pContext)
static void CheckForDirectInputDebugMode ()
static BOOL CALLBACK CountDevicesCallback (const DIDEVICEINSTANCE *pdidInstance, void *pContext)
static int GetNumHidDevices ()
static int GetNumJoysticksSlow ()
static int TranslatePOV (DWORD value)
static HRESULT GetDeviceState (LPDIRECTINPUTDEVICE8 dev, int size, void *ptr)
static wchar_t ScancodeAndKeysToChar (DWORD scancode, unsigned char keys[256])
Variables
static vector< DIDevice > Devices
static int g_iNumJoysticks
const float POLL_FOR_JOYSTICK_CHANGES_LENGTH_SECONDS = 15.0f
const float POLL_FOR_JOYSTICK_CHANGES_EVERY_SECONDS = 0.25f
Macro Definition Documentation
HAT_DOWN_MASK
#define HAT_DOWN_MASK 2
Referenced by TranslatePOV(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
HAT_LEFT_MASK
#define HAT_LEFT_MASK 4
Referenced by TranslatePOV(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
HAT_RIGHT_MASK
#define HAT_RIGHT_MASK 8
Referenced by TranslatePOV(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
HAT_UP_MASK
#define HAT_UP_MASK 1
Referenced by TranslatePOV(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
Function Documentation
CheckForDirectInputDebugMode()
static void CheckForDirectInputDebugMode () static
References LOG, and RageLog::Warn().
Referenced by InputHandler_DInput::InputHandler_DInput().
CountDevicesCallback()
static BOOL CALLBACK CountDevicesCallback (const DIDEVICEINSTANCE * pdidInstance, void * pContext) static
Referenced by GetNumJoysticksSlow().
EnumDevicesCallback()
static BOOL CALLBACK EnumDevicesCallback (const DIDEVICEINSTANCE * pdidInstance, void * pContext) static
References DIDevice::dev, DEVICE_JOY1, DEVICE_KEYBOARD, DEVICE_MOUSE, Devices, enum_add2(), g_iNumJoysticks, RageLog::Info(), DIDevice::JOYSTICK, DIDevice::JoystickInst, DIDevice::KEYBOARD, LOG, DIDevice::MOUSE, NUM_JOYSTICKS, and DIDevice::type.
Referenced by InputHandler_DInput::InputHandler_DInput().
GetDeviceState()
static HRESULT GetDeviceState (LPDIRECTINPUTDEVICE8 dev, int size, void * ptr) static
References LOG, and RageLog::Trace().
Referenced by InputHandler_DInput::UpdatePolled().
GetNumHidDevices()
static int GetNumHidDevices () static
Referenced by InputHandler_DInput::DevicesChanged(), and InputHandler_DInput::InputHandler_DInput().
GetNumJoysticksSlow()
static int GetNumJoysticksSlow () static
References CountDevicesCallback(), g_dinput, LOG, and RageLog::Warn().
Referenced by InputHandler_DInput::DevicesChanged(), and InputHandler_DInput::InputHandler_DInput().
REGISTER_INPUT_HANDLER_CLASS2()
REGISTER_INPUT_HANDLER_CLASS2 (DirectInput , DInput)
ScancodeAndKeysToChar()
static wchar_t ScancodeAndKeysToChar (DWORD scancode, unsigned char keys[256]) static
References ZERO.
Referenced by InputHandler_DInput::DeviceButtonToChar().
TranslatePOV()
static int TranslatePOV (DWORD value) static
References HAT_DOWN_MASK, HAT_LEFT_MASK, HAT_RIGHT_MASK, and HAT_UP_MASK.
Referenced by InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
Variable Documentation
Devices
vector<DIDevice> Devices static
Referenced by InputHandler_DInput::DeviceButtonToChar(), EnumDevicesCallback(), InputHandler_DInput::GetDevicesAndDescriptions(), InputHandler_DInput::InputHandler_DInput(), InputHandler_DInput::InputThreadMain(), InputHandler_DInput::PollAndAcquireDevices(), InputHandler_DInput::Update(), InputHandler_DInput::WindowReset(), and InputHandler_DInput::~InputHandler_DInput().
g_iNumJoysticks
int g_iNumJoysticks static
Referenced by EnumDevicesCallback(), and InputHandler_DInput::InputHandler_DInput().
POLL_FOR_JOYSTICK_CHANGES_EVERY_SECONDS
const float POLL_FOR_JOYSTICK_CHANGES_EVERY_SECONDS = 0.25f
Referenced by InputHandler_DInput::DevicesChanged().
POLL_FOR_JOYSTICK_CHANGES_LENGTH_SECONDS
const float POLL_FOR_JOYSTICK_CHANGES_LENGTH_SECONDS = 15.0f
Referenced by InputHandler_DInput::DevicesChanged().