Etterna: LowLevelWindow_Win32 Class Reference
LowLevelWindow_Win32 Class Reference
#include <LowLevelWindow_Win32.h>
Public Member Functions
LowLevelWindow_Win32 ()
~LowLevelWindow_Win32 ()
void * GetProcAddress (const RString &s)
RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut)
void GetDisplayResolutions (DisplayResolutions &out) const
bool IsSoftwareRenderer (RString &sError)
void SwapBuffers ()
void Update ()
bool SupportsThreadedRendering ()
void BeginConcurrentRendering ()
void EndConcurrentRendering ()
virtual bool SupportsRenderToTexture () const
virtual RenderTarget * CreateRenderTarget ()
const VideoModeParams * GetActualVideoModeParams () const
Public Member Functions inherited from LowLevelWindow
virtual ~LowLevelWindow ()=default
virtual void LogDebugInformation () const
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
Additional Inherited Members
Static Public Member Functions inherited from LowLevelWindow
static LowLevelWindow * Create ()
Constructor & Destructor Documentation
LowLevelWindow_Win32()
LowLevelWindow_Win32::LowLevelWindow_Win32 ()
References ASSERT, g_HGLRC, and g_HGLRC_Background.
~LowLevelWindow_Win32()
LowLevelWindow_Win32::~LowLevelWindow_Win32 ()
References DestroyGraphicsWindowAndOpenGLContext(), and Shutdown().
Member Function Documentation
BeginConcurrentRendering()
void LowLevelWindow_Win32::BeginConcurrentRendering () virtual
Reimplemented from LowLevelWindow.
References FAIL_M, g_HGLRC_Background, LOG, and RageLog::Warn().
CreateRenderTarget()
RenderTarget * LowLevelWindow_Win32::CreateRenderTarget () virtual
Reimplemented from LowLevelWindow.
EndConcurrentRendering()
void LowLevelWindow_Win32::EndConcurrentRendering () virtual
Reimplemented from LowLevelWindow.
GetActualVideoModeParams()
const VideoModeParams * LowLevelWindow_Win32::GetActualVideoModeParams () const virtual
Implements LowLevelWindow.
GetDisplayResolutions()
void LowLevelWindow_Win32::GetDisplayResolutions (DisplayResolutions & out) const virtual
Implements LowLevelWindow.
GetProcAddress()
void * LowLevelWindow_Win32::GetProcAddress (const RString & s) virtual
Implements LowLevelWindow.
IsSoftwareRenderer()
bool LowLevelWindow_Win32::IsSoftwareRenderer (RString & sError) virtual
Reimplemented from LowLevelWindow.
References LOG, OPENGL_NOT_AVAILABLE, and RageLog::Trace().
SupportsRenderToTexture()
virtual bool LowLevelWindow_Win32::SupportsRenderToTexture () const inline virtual
Reimplemented from LowLevelWindow.
SupportsThreadedRendering()
bool LowLevelWindow_Win32::SupportsThreadedRendering () virtual
Reimplemented from LowLevelWindow.
References g_HGLRC_Background.
SwapBuffers()
void LowLevelWindow_Win32::SwapBuffers () virtual
Implements LowLevelWindow.
TryVideoMode()
RString LowLevelWindow_Win32::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) virtual
Implements LowLevelWindow.
References ASSERT, ASSERT_M, VideoModeParams::bpp, ChooseWindowPixelFormat(), DestroyGraphicsWindowAndOpenGLContext(), DumpPixelFormat(), g_CurrentPixelFormat, g_HGLRC, g_HGLRC_Background, LOG, ssprintf(), RageLog::Trace(), RageLog::Warn(), and ZERO.
Update()
void LowLevelWindow_Win32::Update () virtual
Reimplemented from LowLevelWindow.
The documentation for this class was generated from the following files:
LowLevelWindow_Win32.h
LowLevelWindow_Win32.cpp