Etterna: LuaClass Class Reference
LuaClass Class Reference
#include <LuaBinding.h>
Public Member Functions
LuaClass ()=default
LuaClass (const LuaClass &cpy)
~LuaClass () override
LuaClass & operator= (const LuaClass &cpy)
Public Member Functions inherited from LuaTable
LuaTable ()
void Get (Lua *L, const std::string &sKey)
void Set (Lua *L, const std::string &sKey)
Public Member Functions inherited from LuaReference
LuaReference ()
virtual ~LuaReference ()
LuaReference (const LuaReference &cpy)
LuaReference & operator= (const LuaReference &cpy)
LuaReference (Lua *L)
void swap (LuaReference &other)
void SetFromStack (Lua *L)
void SetFromNil ()
bool SetFromExpression (const std::string &sExpression)
void DeepCopy ()
Deep-copy tables, detaching this reference from any others.
virtual void PushSelf (Lua *L) const
bool IsSet () const
Determine if the reference is set.
bool IsNil () const
Determine if the reference is nil.
void Unset ()
int GetLuaType () const
std::string Serialize () const
Additional Inherited Members
Static Public Member Functions inherited from LuaReference
template<typename T >
static LuaReference Create (const T &val)
template<class T >
static LuaReference CreateFromPush (T &obj)
Constructor & Destructor Documentation
LuaClass() [1/2]
LuaClass::LuaClass () default
LuaClass() [2/2]
LuaClass::LuaClass (const LuaClass & cpy)
References LuaReference::DeepCopy(), and LuaReference::IsSet().
~LuaClass()
LuaClass::~LuaClass () override
References LuaManager::Get(), GetGlobalTable(), L, LUA, LuaReference::PushSelf(), and LuaManager::Release().
Member Function Documentation
operator=()
LuaClass & LuaClass::operator= (const LuaClass & cpy)
References LuaReference::DeepCopy(), LuaReference::IsSet(), and LuaReference::operator=().
The documentation for this class was generated from the following files:
LuaBinding.h
LuaBinding.cpp