Etterna: StageStats.cpp File Reference
StageStats.cpp File Reference
#include "StageStats.h"
#include "AdjustSync.h"
#include "CryptManager.h"
#include "DownloadManager.h"
#include "Foreach.h"
#include "GamePreferences.h"
#include "GameState.h"
#include "MinaCalc.h"
#include "NetworkSyncManager.h"
#include "PlayerAI.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "Profile.h"
#include "ProfileManager.h"
#include "ScoreManager.h"
#include "Song.h"
#include "Style.h"
#include "global.h"
#include <fstream>
#include <sstream>
#include <errno.h>
#include <limits.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/in_systm.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/if.h>
#include <linux/sockios.h>
#include <sys/resource.h>
#include <sys/utsname.h>
#include "LuaBinding.h"
Classes
class LunaStageStats
Allow Lua to have access to the StageStats.
Functions
uint16_t hashMacAddress (uint8_t *mac)
DARWIN.
void getMacHash (uint16_t &mac1, uint16_t &mac2)
static void getCpuid (uint32_t *p, uint32_t ax)
uint16_t getCpuHash ()
string getMachineName ()
static uint16_t * computeSystemUniqueId ()
string getSystemUniqueId ()
bool DetermineScoreEligibility (const PlayerStageStats &pss, const PlayerState &ps)
static HighScore FillInHighScore (const PlayerStageStats &pss, const PlayerState &ps, RString sRankingToFillInMarker, RString sPlayerGuid)
Function Documentation
computeSystemUniqueId()
static uint16_t* computeSystemUniqueId () static
References getCpuHash(), and getMacHash().
Referenced by getSystemUniqueId().
DetermineScoreEligibility()
bool DetermineScoreEligibility (const PlayerStageStats & pss, const PlayerState & ps)
References GameState::CountNotesSeparately(), PlayerStageStats::everusedautoplay, PlayerStageStats::filegotholds, PlayerStageStats::filegotmines, PlayerStageStats::filehadnegbpms, FOREACHM_CONST, GAMESTATE, PlayerStageStats::GetGrade(), ModsGroup< T >::GetStage(), PlayerOptions::GetString(), PlayerStageStats::GetTotalTaps(), Grade_Failed, PlayerStageStats::luascriptwasloaded, PlayerStageStats::m_fLifeRecord, PlayerStageStats::m_fWifeScore, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, and StepsType_dance_single.
Referenced by FillInHighScore().
FillInHighScore()
static HighScore FillInHighScore (const PlayerStageStats & pss, const PlayerState & ps, RString sRankingToFillInMarker, RString sPlayerGuid) static
References BinaryToHex(), PlayerStageStats::CalcSSR(), GameState::CountNotesSeparately(), DetermineScoreEligibility(), PlayerStageStats::everusedautoplay, f, FOREACH_ENUM, GAMESTATE, PlayerStageStats::gaveuplikeadumbass, HighScore::GenerateValidationKeys(), GetCalcVersion(), ModsGroup< T >::GetCurrent(), PlayerStageStats::GetCurWifeScore(), HighScore::GetDateTime(), HighScore::GetEtternaValid(), PlayerStageStats::GetGrade(), PlayerStageStats::GetHoldReplayDataVector(), PlayerStageStats::GetMaxCombo(), PlayerStageStats::GetNoteRowVector(), DateTime::GetNowDateTime(), PlayerStageStats::GetOffsetVector(), PlayerStageStats::GetPercentDancePoints(), CryptManager::GetSHA1ForString(), HighScore::GetSSRNormPercent(), ModsGroup< T >::GetStage(), SongOptions::GetString(), PlayerOptions::GetString(), DateTime::GetString(), getSystemUniqueId(), PlayerStageStats::GetTapNoteTypeVector(), PlayerStageStats::GetTimingScale(), PlayerStageStats::GetTrackVector(), PlayerStageStats::GetWifeScore(), Grade_Failed, PlayerStageStats::InputData, PlayerStageStats::IsDisqualified(), Rage::join(), PlayerStageStats::luascriptwasloaded, PlayerStageStats::Combo_t::m_cnt, PlayerStageStats::m_fAliveSeconds, PlayerStageStats::m_fLifeRemainingSeconds, SongOptions::m_fMusicRate, PlayerStageStats::m_fWifeScore, PlayerStageStats::m_iHoldNoteScores, PlayerStageStats::m_iScore, PlayerStageStats::m_iTapNoteScores, GameState::m_pCurSteps, PlayerStageStats::m_PeakComboAward, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, PlayerStageStats::m_radarActual, GameState::m_SongOptions, PlayerStageStats::m_StageAward, HighScore::RescoreToWifeJudge(), HighScore::SetAliveSeconds(), HighScore::SetChartKey(), HighScore::SetChordCohesion(), HighScore::SetDateTime(), HighScore::SetDisqualified(), HighScore::SetEtternaValid(), HighScore::SetGrade(), HighScore::SetHoldNoteScore(), HighScore::SetHoldReplayDataVector(), HighScore::SetJudgeScale(), HighScore::SetLifeRemainingSeconds(), HighScore::SetMachineGuid(), HighScore::SetMaxCombo(), HighScore::SetModifiers(), HighScore::SetMusicRate(), HighScore::SetName(), HighScore::SetNoteRowVector(), HighScore::SetOffsetVector(), HighScore::SetPeakComboAward(), HighScore::SetPercentDP(), HighScore::SetPlayerGuid(), HighScore::SetRadarValues(), HighScore::SetReplayType(), HighScore::SetScore(), HighScore::SetScoreKey(), HighScore::SetSkillsetSSR(), HighScore::SetSSRCalcVersion(), HighScore::SetSSRNormPercent(), HighScore::SetStageAward(), HighScore::SetTapNoteScore(), HighScore::SetTapNoteTypeVector(), HighScore::SetTrackVector(), HighScore::SetWifePoints(), HighScore::SetWifeScore(), and HighScore::WriteInputData().
Referenced by StageStats::FinalizeScores().
getCpuHash()
uint16_t getCpuHash ()
References getCpuid().
Referenced by computeSystemUniqueId().
getCpuid()
static void getCpuid (uint32_t * p, uint32_t ax) static
Referenced by getCpuHash().
getMacHash()
void getMacHash (uint16_t & mac1, uint16_t & mac2)
References hashMacAddress().
Referenced by computeSystemUniqueId().
getMachineName()
string getMachineName ()
Referenced by getSystemUniqueId().
getSystemUniqueId()
string getSystemUniqueId ()
References computeSystemUniqueId(), and getMachineName().
Referenced by FillInHighScore().
hashMacAddress()
uint16_t hashMacAddress (uint8_t * mac)
DARWIN.
DARWIN
Referenced by getMacHash().