Etterna: XmlToLua.cpp File Reference
XmlToLua.cpp File Reference
#include "ActorUtil.h"
#include "Foreach.h"
#include "IniFile.h"
#include "LuaBinding.h"
#include "LuaManager.h"
#include "RageFile.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageTypes.h"
#include "XmlFile.h"
#include "XmlFileUtil.h"
#include "global.h"
#include <map>
#include <set>
#include <vector>
Classes
struct frame_t
struct actor_template_t
Macros
#define TWEEN_QUEUE_MAX 50
#define COMMON_ARG_VERIFY(count)
#define set_type(auto_type)
Typedefs
typedef void(* arg_converter_t) (vector< RString > &args)
typedef map< RString, RString > condition_set_t
typedef map< RString, RString > field_cont_t
Functions
RString unique_name ()
void convert_xmls_in_dir (RString const &dirname)
void convert_xml_file (RString const &fname, RString const &dirname)
RString maybe_conv_pos (RString pos, RString(*conv_func)(float p))
RString add_extension_to_relative_path_from_found_file (RString const &relative_path, RString const &found_file)
RString unique_name (RString const &type)
RString convert_xpos (float x)
RString convert_ypos (float y)
size_t after_slash_or_zero (RString const &s)
bool verify_arg_count (RString cmd, vector< RString > &args, size_t req)
void x_conv (vector< RString > &args)
void y_conv (vector< RString > &args)
void string_arg_conv (vector< RString > &args)
void lower_string_conv (vector< RString > &args)
void hidden_conv (vector< RString > &args)
void diffuse_conv (vector< RString > &args)
const RString & BlendModeToString (BlendMode)
const RString & CullModeToString (CullMode)
void blend_conv (vector< RString > &args)
void cull_conv (vector< RString > &args)
void init_parser_helpers ()
void convert_lua_chunk (RString &chunk_text)
int LuaFunc_convert_xml_bgs (lua_State *L)
LUAFUNC_REGISTER_COMMON (convert_xml_bgs)
Variables
map< RString, arg_converter_t > arg_converters
map< RString, size_t > tween_counters
set< RString > fields_that_are_strings
map< RString, RString > chunks_to_replace
Macro Definition Documentation
COMMON_ARG_VERIFY
#define COMMON_ARG_VERIFY (count)
Value:
if (!verify_arg_count(args[0], args, count))                               \
        return;
Referenced by blend_conv(), cull_conv(), diffuse_conv(), hidden_conv(), string_arg_conv(), x_conv(), and y_conv().
set_type
#define set_type (auto_type)
Value:
type_set_by_automagic = true;                                              \
    type = auto_type;
Referenced by actor_template_t::load_node().
TWEEN_QUEUE_MAX
#define TWEEN_QUEUE_MAX 50
Referenced by actor_template_t::store_cmd().
Typedef Documentation
arg_converter_t
typedef void(* arg_converter_t) (vector< RString > &args)
condition_set_t
typedef map<RString, RString> condition_set_t
field_cont_t
typedef map<RString, RString> field_cont_t
Function Documentation
add_extension_to_relative_path_from_found_file()
RString add_extension_to_relative_path_from_found_file (RString const & relative_path, RString const & found_file)
References after_slash_or_zero(), and StdString::CStdStr< CT >::Left().
Referenced by actor_template_t::load_node().
after_slash_or_zero()
size_t after_slash_or_zero (RString const & s)
Referenced by add_extension_to_relative_path_from_found_file().
blend_conv()
void blend_conv (vector< RString > & args)
References BlendModeToString(), COMMON_ARG_VERIFY, StdString::CStdStr< CT >::MakeLower(), and NUM_BlendMode.
Referenced by init_parser_helpers().
BlendModeToString()
const RString& BlendModeToString (BlendMode)
Referenced by blend_conv().
convert_lua_chunk()
void convert_lua_chunk (RString & chunk_text)
References StdString::CStdStr< CT >::Replace().
Referenced by convert_xml_file(), and actor_template_t::store_cmd().
convert_xml_file()
void convert_xml_file (RString const & fname, RString const & dirname)
References RageFile::Close(), convert_lua_chunk(), RageFile::GetError(), init_parser_helpers(), StdString::CStdStr< CT >::Left(), actor_template_t::load_node(), XmlFileUtil::LoadFromFileShowErrors(), LOG, RageFile::Open(), actor_template_t::output_to_file(), RageLog::Trace(), RageFile::WRITE, and RageFile::Write().
Referenced by convert_xmls_in_dir().
convert_xmls_in_dir()
void convert_xmls_in_dir (RString const & dirname)
References convert_xml_file(), convert_xmls_in_dir(), FILEMAN, FT_Directory, FT_Xml, RageFileManager::GetDirListing(), and ActorUtil::GetFileType().
Referenced by convert_xmls_in_dir(), DebugLineConvertXML::DoAndLog(), and LuaFunc_convert_xml_bgs().
convert_xpos()
RString convert_xpos (float x)
References f, and FloatToString().
Referenced by x_conv().
convert_ypos()
RString convert_ypos (float y)
References f, and FloatToString().
Referenced by y_conv().
cull_conv()
void cull_conv (vector< RString > & args)
References COMMON_ARG_VERIFY, CullModeToString(), StdString::CStdStr< CT >::MakeLower(), and NUM_CullMode.
Referenced by init_parser_helpers().
CullModeToString()
const RString& CullModeToString (CullMode)
Referenced by cull_conv().
diffuse_conv()
void diffuse_conv (vector< RString > & args)
References COMMON_ARG_VERIFY.
Referenced by init_parser_helpers().
hidden_conv()
void hidden_conv (vector< RString > & args)
References COMMON_ARG_VERIFY.
Referenced by init_parser_helpers().
init_parser_helpers()
void init_parser_helpers ()
References blend_conv(), cull_conv(), diffuse_conv(), hidden_conv(), lower_string_conv(), string_arg_conv(), x_conv(), and y_conv().
Referenced by convert_xml_file().
lower_string_conv()
void lower_string_conv (vector< RString > & args)
Referenced by init_parser_helpers().
LuaFunc_convert_xml_bgs()
int LuaFunc_convert_xml_bgs (lua_State * L)
References convert_xmls_in_dir(), and SArg.
LUAFUNC_REGISTER_COMMON()
LUAFUNC_REGISTER_COMMON (convert_xml_bgs)
maybe_conv_pos()
RString maybe_conv_pos (RString pos, RString(*)(float p) conv_func)
References f.
string_arg_conv()
void string_arg_conv (vector< RString > & args)
References COMMON_ARG_VERIFY.
Referenced by init_parser_helpers().
unique_name() [1/2]
RString unique_name ()
Referenced by actor_template_t::load_node(), actor_template_t::output_to_file(), and actor_template_t::store_cmd().
unique_name() [2/2]
RString unique_name (RString const & type)
verify_arg_count()
bool verify_arg_count (RString cmd, vector< RString > & args, size_t req)
References LuaHelpers::ReportScriptError().
x_conv()
void x_conv (vector< RString > & args)
References COMMON_ARG_VERIFY, and convert_xpos().
Referenced by init_parser_helpers().
y_conv()
void y_conv (vector< RString > & args)
References COMMON_ARG_VERIFY, and convert_ypos().
Referenced by init_parser_helpers().
Variable Documentation
arg_converters
map<RString, arg_converter_t> arg_converters
chunks_to_replace
map<RString, RString> chunks_to_replace
fields_that_are_strings
set<RString> fields_that_are_strings
tween_counters
map<RString, size_t> tween_counters