Etterna: MovieDecoder_FFMpeg Class Reference
MovieDecoder_FFMpeg Class Reference
#include <MovieTexture_FFMpeg.h>
Public Member Functions
MovieDecoder_FFMpeg ()
~MovieDecoder_FFMpeg ()
RString Open (const RString &sFile)
void Close ()
void Rewind ()
void GetFrame (RageSurface *pOut)
int DecodeFrame (float fTargetTime)
int GetWidth () const
int GetHeight () const
RageSurface * CreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, MovieDecoderPixelFormatYCbCr &fmtout)
float GetTimestamp () const
float GetFrameDuration () const
Public Member Functions inherited from MovieDecoder
virtual ~MovieDecoder ()
virtual float GetSourceAspectRatio () const
Private Member Functions
void Init ()
RString OpenCodec ()
int ReadPacket ()
int DecodePacket (float fTargetTime)
Private Attributes
avcodec::AVStream * m_pStream
avcodec::AVFrame * m_Frame
avcodec::PixelFormat m_AVTexfmt
avcodec::SwsContext * m_swsctx
avcodec::AVFormatContext * m_fctx
float m_fTimestamp
float m_fTimestampOffset
float m_fLastFrameDelay
int m_iFrameNumber
unsigned char * m_buffer
avcodec::AVIOContext * m_avioContext
avcodec::AVPacket m_Packet
int m_iCurrentPacketOffset
float m_fLastFrame
int m_iEOF
Constructor & Destructor Documentation
MovieDecoder_FFMpeg()
MovieDecoder_FFMpeg::MovieDecoder_FFMpeg ()
References FixLilEndian(), Init(), m_fctx, m_Frame, m_iCurrentPacketOffset, and m_pStream.
~MovieDecoder_FFMpeg()
MovieDecoder_FFMpeg::~MovieDecoder_FFMpeg ()
References RageFile::Close(), m_avioContext, m_buffer, m_iCurrentPacketOffset, m_Packet, and m_swsctx.
Member Function Documentation
Close()
void MovieDecoder_FFMpeg::Close () virtual
Implements MovieDecoder.
References Init(), m_fctx, and m_pStream.
CreateCompatibleSurface()
RageSurface * MovieDecoder_FFMpeg::CreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, MovieDecoderPixelFormatYCbCr & fmtout) virtual
Implements MovieDecoder.
References RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface(), and m_AVTexfmt.
DecodeFrame()
int MovieDecoder_FFMpeg::DecodeFrame (float fTargetTime) virtual
Implements MovieDecoder.
References ASSERT, DecodePacket(), m_fLastFrame, m_iEOF, and ReadPacket().
DecodePacket()
int MovieDecoder_FFMpeg::DecodePacket (float fTargetTime) private
References GetFrameDuration(), GetTimestamp(), LOG, m_fLastFrameDelay, m_Frame, m_fTimestamp, m_fTimestampOffset, m_iCurrentPacketOffset, m_iEOF, m_iFrameNumber, m_Packet, m_pStream, RageLog::Trace(), and RageLog::Warn().
Referenced by DecodeFrame().
GetFrame()
void MovieDecoder_FFMpeg::GetFrame (RageSurface * pOut) virtual
Implements MovieDecoder.
References GetHeight(), GetWidth(), LOG, m_AVTexfmt, m_Frame, m_pStream, m_swsctx, RageSurface::pitch, RageSurface::pixels, sws_flags, and RageLog::Warn().
GetFrameDuration()
float MovieDecoder_FFMpeg::GetFrameDuration () const virtual
Implements MovieDecoder.
References m_fLastFrameDelay.
Referenced by DecodePacket().
GetHeight()
int MovieDecoder_FFMpeg::GetHeight () const inline virtual
Implements MovieDecoder.
References m_pStream.
Referenced by GetFrame().
GetTimestamp()
float MovieDecoder_FFMpeg::GetTimestamp () const virtual
Implements MovieDecoder.
References m_fTimestamp, and m_fTimestampOffset.
Referenced by DecodePacket().
GetWidth()
int MovieDecoder_FFMpeg::GetWidth () const inline virtual
Implements MovieDecoder.
References m_pStream.
Referenced by GetFrame().
Init()
void MovieDecoder_FFMpeg::Init () private
References m_avioContext, m_buffer, m_fLastFrame, m_fLastFrameDelay, m_fTimestamp, m_fTimestampOffset, m_iCurrentPacketOffset, m_iEOF, m_iFrameNumber, m_Packet, and m_swsctx.
Referenced by Close(), MovieDecoder_FFMpeg(), and OpenCodec().
Open()
RString MovieDecoder_FFMpeg::Open (const RString & sFile) virtual
Implements MovieDecoder.
References averr_ssprintf(), AVIORageFile_ReadPacket(), AVIORageFile_Seek(), f, RageFile::GetError(), LOG, m_avioContext, m_buffer, m_fctx, m_pStream, RageFile::Open(), OpenCodec(), RageFile::READ, MovieTexture_FFMpeg::RegisterProtocols(), ssprintf(), STEPMANIA_FFMPEG_BUFFER_SIZE, and RageLog::Trace().
OpenCodec()
RString MovieDecoder_FFMpeg::OpenCodec () private
References ASSERT, averr_ssprintf(), Init(), LOG, m_pStream, ssprintf(), and RageLog::Trace().
Referenced by Open(), and Rewind().
ReadPacket()
int MovieDecoder_FFMpeg::ReadPacket () private
References m_fctx, m_iCurrentPacketOffset, m_iEOF, m_Packet, and m_pStream.
Referenced by DecodeFrame().
Rewind()
void MovieDecoder_FFMpeg::Rewind () virtual
Implements MovieDecoder.
References m_fctx, and OpenCodec().
Member Data Documentation
m_avioContext
avcodec::AVIOContext* MovieDecoder_FFMpeg::m_avioContext private
Referenced by Init(), Open(), and ~MovieDecoder_FFMpeg().
m_AVTexfmt
avcodec::PixelFormat MovieDecoder_FFMpeg::m_AVTexfmt private
Referenced by CreateCompatibleSurface(), and GetFrame().
m_buffer
unsigned char* MovieDecoder_FFMpeg::m_buffer private
Referenced by Init(), Open(), and ~MovieDecoder_FFMpeg().
m_fctx
avcodec::AVFormatContext* MovieDecoder_FFMpeg::m_fctx private
Referenced by Close(), MovieDecoder_FFMpeg(), Open(), ReadPacket(), and Rewind().
m_fLastFrame
float MovieDecoder_FFMpeg::m_fLastFrame private
Referenced by DecodeFrame(), and Init().
m_fLastFrameDelay
float MovieDecoder_FFMpeg::m_fLastFrameDelay private
Referenced by DecodePacket(), GetFrameDuration(), and Init().
m_Frame
avcodec::AVFrame* MovieDecoder_FFMpeg::m_Frame private
Referenced by DecodePacket(), GetFrame(), and MovieDecoder_FFMpeg().
m_fTimestamp
float MovieDecoder_FFMpeg::m_fTimestamp private
Referenced by DecodePacket(), GetTimestamp(), and Init().
m_fTimestampOffset
float MovieDecoder_FFMpeg::m_fTimestampOffset private
Referenced by DecodePacket(), GetTimestamp(), and Init().
m_iCurrentPacketOffset
int MovieDecoder_FFMpeg::m_iCurrentPacketOffset private
Referenced by DecodePacket(), Init(), MovieDecoder_FFMpeg(), ReadPacket(), and ~MovieDecoder_FFMpeg().
m_iEOF
int MovieDecoder_FFMpeg::m_iEOF private
Referenced by DecodeFrame(), DecodePacket(), Init(), and ReadPacket().
m_iFrameNumber
int MovieDecoder_FFMpeg::m_iFrameNumber private
Referenced by DecodePacket(), and Init().
m_Packet
avcodec::AVPacket MovieDecoder_FFMpeg::m_Packet private
Referenced by DecodePacket(), Init(), ReadPacket(), and ~MovieDecoder_FFMpeg().
m_pStream
avcodec::AVStream* MovieDecoder_FFMpeg::m_pStream private
Referenced by Close(), DecodePacket(), GetFrame(), GetHeight(), GetWidth(), MovieDecoder_FFMpeg(), Open(), OpenCodec(), and ReadPacket().
m_swsctx
avcodec::SwsContext* MovieDecoder_FFMpeg::m_swsctx private
Referenced by GetFrame(), Init(), and ~MovieDecoder_FFMpeg().
The documentation for this class was generated from the following files:
MovieTexture_FFMpeg.h
MovieTexture_FFMpeg.cpp