Etterna: LunaProfileManager Class Reference
LunaProfileManager Class Reference
Allow Lua to have access to the ProfileManager.
Public Member Functions
LunaProfileManager ()
Public Member Functions inherited from Luna< ProfileManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetStatsPrefix (T *p, lua_State *L)
static int SetStatsPrefix (T *p, lua_State *L)
static int IsPersistentProfile (T *p, lua_State *L)
static int GetProfile (T *p, lua_State *L)
static int GetMachineProfile (T *p, lua_State *L)
static int GetLocalProfile (T *p, lua_State *L)
static int GetLocalProfileFromIndex (T *p, lua_State *L)
static int GetLocalProfileIDFromIndex (T *p, lua_State *L)
static int GetLocalProfileIndexFromID (T *p, lua_State *L)
static int GetNumLocalProfiles (T *p, lua_State *L)
static int GetProfileDir (T *p, lua_State *L)
static int IsSongNew (T *p, lua_State *L)
static int LastLoadWasTamperedOrCorrupt (T *p, lua_State *L)
static int GetPlayerName (T *p, lua_State *L)
static int LocalProfileIDToDir (T *, lua_State *L)
static int SaveProfile (T *p, lua_State *L)
static int ConvertProfile (T *p, lua_State *L)
static int SaveLocalProfile (T *p, lua_State *L)
static int GetSongNumTimesPlayed (T *p, lua_State *L)
static int GetLocalProfileIDs (T *p, lua_State *L)
static int GetLocalProfileDisplayNames (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ProfileManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ProfileManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ProfileManager >
using T = ProfileManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ProfileManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ProfileManager.
Constructor & Destructor Documentation
LunaProfileManager()
LunaProfileManager::LunaProfileManager () inline
References ADD_METHOD, ConvertProfile(), GetLocalProfile(), GetLocalProfileDisplayNames(), GetLocalProfileFromIndex(), GetLocalProfileIDFromIndex(), GetLocalProfileIDs(), GetLocalProfileIndexFromID(), GetMachineProfile(), GetNumLocalProfiles(), GetPlayerName(), GetProfile(), GetProfileDir(), GetSongNumTimesPlayed(), GetStatsPrefix(), IsPersistentProfile(), IsSongNew(), LastLoadWasTamperedOrCorrupt(), LocalProfileIDToDir(), SaveLocalProfile(), SaveProfile(), and SetStatsPrefix().
Member Function Documentation
ConvertProfile()
static int LunaProfileManager::ConvertProfile (T * p, lua_State * L) inline static
References ProfileManager::ConvertProfile().
Referenced by LunaProfileManager().
GetLocalProfile()
static int LunaProfileManager::GetLocalProfile (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfile(), Profile::PushSelf(), and SArg.
Referenced by LunaProfileManager().
GetLocalProfileDisplayNames()
static int LunaProfileManager::GetLocalProfileDisplayNames (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfileDisplayNames(), and L.
Referenced by LunaProfileManager().
GetLocalProfileFromIndex()
static int LunaProfileManager::GetLocalProfileFromIndex (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfileFromIndex(), ProfileManager::GetNumLocalProfiles(), IArg, and Profile::PushSelf().
Referenced by LunaProfileManager().
GetLocalProfileIDFromIndex()
static int LunaProfileManager::GetLocalProfileIDFromIndex (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfileIDFromIndex(), ProfileManager::GetNumLocalProfiles(), and IArg.
Referenced by LunaProfileManager().
GetLocalProfileIDs()
static int LunaProfileManager::GetLocalProfileIDs (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfileIDs(), and L.
Referenced by LunaProfileManager().
GetLocalProfileIndexFromID()
static int LunaProfileManager::GetLocalProfileIndexFromID (T * p, lua_State * L) inline static
References ProfileManager::GetLocalProfileIndexFromID(), and SArg.
Referenced by LunaProfileManager().
GetMachineProfile()
static int LunaProfileManager::GetMachineProfile (T * p, lua_State * L) inline static
References ProfileManager::GetProfile(), PLAYER_1, and Profile::PushSelf().
Referenced by LunaProfileManager().
GetNumLocalProfiles()
static int LunaProfileManager::GetNumLocalProfiles (T * p, lua_State * L) inline static
References ProfileManager::GetNumLocalProfiles().
Referenced by LunaProfileManager().
GetPlayerName()
static int LunaProfileManager::GetPlayerName (T * p, lua_State * L) inline static
References ProfileManager::GetPlayerName(), and L.
Referenced by LunaProfileManager().
GetProfile()
static int LunaProfileManager::GetProfile (T * p, lua_State * L) inline static
References ProfileManager::GetProfile(), L, and Profile::PushSelf().
Referenced by LunaProfileManager().
GetProfileDir()
static int LunaProfileManager::GetProfileDir (T * p, lua_State * L) inline static
References ProfileManager::GetProfileDir().
Referenced by LunaProfileManager().
GetSongNumTimesPlayed()
static int LunaProfileManager::GetSongNumTimesPlayed (T * p, lua_State * L) inline static
References ProfileManager::GetSongNumTimesPlayed().
Referenced by LunaProfileManager().
GetStatsPrefix()
static int LunaProfileManager::GetStatsPrefix (T * p, lua_State * L) inline static
References ProfileManager::GetStatsPrefix().
Referenced by LunaProfileManager().
IsPersistentProfile()
static int LunaProfileManager::IsPersistentProfile (T * p, lua_State * L) inline static
References ProfileManager::IsPersistentProfile().
Referenced by LunaProfileManager().
IsSongNew()
static int LunaProfileManager::IsSongNew (T * p, lua_State * L) inline static
References ProfileManager::IsSongNew().
Referenced by LunaProfileManager().
LastLoadWasTamperedOrCorrupt()
static int LunaProfileManager::LastLoadWasTamperedOrCorrupt (T * p, lua_State * L) inline static
References ProfileManager::LastLoadWasTamperedOrCorrupt().
Referenced by LunaProfileManager().
LocalProfileIDToDir()
static int LunaProfileManager::LocalProfileIDToDir (T * , lua_State * L) inline static
References SArg.
Referenced by LunaProfileManager().
SaveLocalProfile()
static int LunaProfileManager::SaveLocalProfile (T * p, lua_State * L) inline static
References SArg, and ProfileManager::SaveLocalProfile().
Referenced by LunaProfileManager().
SaveProfile()
static int LunaProfileManager::SaveProfile (T * p, lua_State * L) inline static
References ProfileManager::SaveProfile().
Referenced by LunaProfileManager().
SetStatsPrefix()
static int LunaProfileManager::SetStatsPrefix (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and ProfileManager::SetStatsPrefix().
Referenced by LunaProfileManager().
The documentation for this class was generated from the following file:
ProfileManager.cpp