Etterna: ReceptorArrowRow Class Reference
ReceptorArrowRow Class Reference
A row of ReceptorArrow objects.
#include <ReceptorArrowRow.h>
Public Member Functions
ReceptorArrowRow ()
~ReceptorArrowRow () override
void Update (float fDeltaTime) override
void DrawPrimitives () override
Draw the primitives of the Actor.
void DrawOverlay ()
void Load (const PlayerState *pPlayerState, float fYReverseOffset)
void SetColumnRenderers (vector< NoteColumnRenderer > &renderers)
void Step (int iCol, TapNoteScore score)
void SetPressed (int iCol)
void SetNoteUpcoming (int iCol, bool b, int iRow)
void SetFadeToFailPercent (float fFadeToFailPercent)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushSelf (lua_State *L) override
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Attributes
const PlayerState * m_pPlayerState
float m_fYReverseOffsetPixels
float m_fFadeToFailPercent
vector< NoteColumnRenderer > const * m_renderers
vector< ReceptorArrow * > m_ReceptorArrow
vector< ReceptorArrow * > m_OverlayReceptorArrow
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A row of ReceptorArrow objects.
Constructor & Destructor Documentation
ReceptorArrowRow()
ReceptorArrowRow::ReceptorArrowRow ()
References m_fFadeToFailPercent, m_fYReverseOffsetPixels, m_pPlayerState, m_renderers, and NoteUpcoming.
~ReceptorArrowRow()
ReceptorArrowRow::~ReceptorArrowRow () override
References m_ReceptorArrow.
Member Function Documentation
DrawOverlay()
void ReceptorArrowRow::DrawOverlay ()
References GAMESTATE, GameState::GetCurrentStyle(), Style::m_iColumnDrawOrder, m_OverlayReceptorArrow, PlayerState::m_PlayerNumber, m_pPlayerState, and m_ReceptorArrow.
Referenced by NoteField::DrawPrimitives().
DrawPrimitives()
void ReceptorArrowRow::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from ActorFrame.
References GAMESTATE, GameState::GetCurrentStyle(), Style::m_iColumnDrawOrder, PlayerState::m_PlayerNumber, m_pPlayerState, and m_ReceptorArrow.
Load()
void ReceptorArrowRow::Load (const PlayerState * pPlayerState, float fYReverseOffset)
References ActorFrame::AddChild(), GAMESTATE, GameState::GetCurrentStyle(), m_fYReverseOffsetPixels, Style::m_iColsPerPlayer, m_OverlayReceptorArrow, PlayerState::m_PlayerNumber, m_pPlayerState, and m_ReceptorArrow.
SetColumnRenderers()
void ReceptorArrowRow::SetColumnRenderers (vector< NoteColumnRenderer > & renderers)
References ASSERT_M, m_ReceptorArrow, and m_renderers.
Referenced by NoteField::InitColumnRenderers().
SetFadeToFailPercent()
void ReceptorArrowRow::SetFadeToFailPercent (float fFadeToFailPercent) inline
References m_fFadeToFailPercent.
Referenced by NoteField::Update().
SetNoteUpcoming()
void ReceptorArrowRow::SetNoteUpcoming (int iCol, bool b, int iRow)
References ASSERT, m_ReceptorArrow, and NoteUpcoming.
Referenced by NoteColumnRenderer::DrawPrimitives().
SetPressed()
void ReceptorArrowRow::SetPressed (int iCol)
References ASSERT, and m_ReceptorArrow.
Referenced by NoteField::SetPressed().
Step()
void ReceptorArrowRow::Step (int iCol, TapNoteScore score)
References ASSERT, and m_ReceptorArrow.
Referenced by NoteField::Step().
Update()
void ReceptorArrowRow::Update (float fDeltaTime) override virtual
Reimplemented from Actor.
References CLAMP(), f, Style::ColumnInfo::fXOffset, GAMESTATE, ModsGroup< T >::GetCurrent(), GameState::GetCurrentStyle(), Style::m_ColumnInfo, PlayerOptions::m_fDark, m_fFadeToFailPercent, m_OverlayReceptorArrow, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pPlayerState, m_ReceptorArrow, m_renderers, ArrowEffects::Update(), and Actor::Update().
Referenced by NoteField::Update().
Member Data Documentation
m_fFadeToFailPercent
float ReceptorArrowRow::m_fFadeToFailPercent protected
Referenced by ReceptorArrowRow(), SetFadeToFailPercent(), and Update().
m_fYReverseOffsetPixels
float ReceptorArrowRow::m_fYReverseOffsetPixels protected
Referenced by Load(), and ReceptorArrowRow().
m_OverlayReceptorArrow
vector<ReceptorArrow*> ReceptorArrowRow::m_OverlayReceptorArrow protected
Referenced by DrawOverlay(), Load(), and Update().
m_pPlayerState
const PlayerState* ReceptorArrowRow::m_pPlayerState protected
Referenced by DrawOverlay(), DrawPrimitives(), Load(), ReceptorArrowRow(), and Update().
m_ReceptorArrow
vector<ReceptorArrow*> ReceptorArrowRow::m_ReceptorArrow protected
Referenced by DrawOverlay(), DrawPrimitives(), Load(), SetColumnRenderers(), SetNoteUpcoming(), SetPressed(), Step(), Update(), and ~ReceptorArrowRow().
m_renderers
vector<NoteColumnRenderer> const* ReceptorArrowRow::m_renderers protected
Referenced by ReceptorArrowRow(), SetColumnRenderers(), and Update().
The documentation for this class was generated from the following files:
ReceptorArrowRow.h
ReceptorArrowRow.cpp