Etterna: LocalizedStringImplThemeMetric Class Reference
LocalizedStringImplThemeMetric Class Reference
Public Member Functions
void Load (const RString &sGroup, const RString &sName) override
void Read () override
const RString & GetLocalized () const override
Public Member Functions inherited from ILocalizedStringImpl
virtual ~ILocalizedStringImpl ()=default
Public Member Functions inherited from ThemeMetric< RString >
ThemeMetric (const RString &sGroup="", const RString &sName="")
ThemeMetric (const ThemeMetric< RString > &cpy)
~ThemeMetric () override
void Load (const RString &sGroup, const RString &sName)
Load the chosen metric from the .ini file.
void ChangeGroup (const RString &sGroup)
void Read () override
Actually read the metric and get its data.
void PushSelf (Lua *L)
void Clear () override
const RString & GetName () const
Retrieve the metric's name.
const RString & GetGroup () const
Retrieve the metric's group.
const RString & GetValue () const
Retrieve the metric's value.
operator const RString & () const
bool IsLoaded () const
bool operator== (const RString &input) const
Public Member Functions inherited from IThemeMetric
virtual ~IThemeMetric ()=default
Static Public Member Functions
static ILocalizedStringImpl * Create ()
Additional Inherited Members
Protected Attributes inherited from ThemeMetric< RString >
RString m_sGroup
the metric's group.
RString m_sName
the metric's name.
LuaReference m_Value
the metric's value.
RString m_currentValue
bool m_bCallEachTime
Member Function Documentation
Create()
static ILocalizedStringImpl* LocalizedStringImplThemeMetric::Create () inline static
Referenced by ThemeManager::SwitchThemeAndLanguage().
GetLocalized()
const RString& LocalizedStringImplThemeMetric::GetLocalized () const inline override virtual
Implements ILocalizedStringImpl.
References ThemeManager::GetCurLanguage(), ThemeMetric< RString >::GetValue(), ThemeMetric< RString >::IsLoaded(), ThemeManager::IsThemeLoaded(), LOG, ThemeMetric< RString >::m_sName, and RageLog::Warn().
Load()
void LocalizedStringImplThemeMetric::Load (const RString & sGroup, const RString & sName) inline override virtual
Implements ILocalizedStringImpl.
References ThemeMetric< T >::Load().
Read()
void LocalizedStringImplThemeMetric::Read () inline override virtual
Implements IThemeMetric.
References ThemeManager::GetString(), ThemeManager::IsThemeLoaded(), ThemeMetric< RString >::m_currentValue, ThemeMetric< RString >::m_sGroup, ThemeMetric< RString >::m_sName, ThemeMetric< RString >::m_Value, and LuaReference::SetFromNil().
The documentation for this class was generated from the following file:
ThemeManager.cpp