Etterna: ScreenDebugOverlay.cpp File Reference
ScreenDebugOverlay.cpp File Reference
#include "ScreenDebugOverlay.h"
#include "CodeDetector.h"
#include "GameCommand.h"
#include "GameLoop.h"
#include "GamePreferences.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "InputEventPlus.h"
#include "InputMapper.h"
#include "LocalizedString.h"
#include "NoteSkinManager.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "ProfileManager.h"
#include "RageDisplay.h"
#include "RageInput.h"
#include "RageLog.h"
#include "RageSoundManager.h"
#include "RageTextureManager.h"
#include "ScreenDimensions.h"
#include "ScreenGameplay.h"
#include "ScreenManager.h"
#include "ScreenSyncOverlay.h"
#include "Song.h"
#include "SongManager.h"
#include "StepMania.h"
#include "ThemeMetric.h"
#include "XmlToLua.h"
#include "global.h"
Classes
class IDebugLine
struct MapDebugToDI
class DebugLineAutoplay
class DebugLineAssist
class DebugLineAutosync
class DebugLineSlow
class DebugLineHalt
class DebugLineStats
class DebugLineVsync
class DebugLineAllowMultitexture
class DebugLineShowMasks
class DebugLineProfileSlot
class DebugLineClearProfileStats
class DebugLineFillProfileStats
class DebugLineSendNotesEnded
class DebugLineResetKeyMapping
class DebugLineMuteActions
class DebugLineReloadCurrentScreen
class DebugLineRestartCurrentScreen
class DebugLineCurrentScreenOn
class DebugLineCurrentScreenOff
class DebugLineReloadTheme
class DebugLineReloadOverlayScreens
class DebugLineToggleErrors
class DebugLineShowRecentErrors
class DebugLineClearErrors
class DebugLineConvertXML
class DebugLineWriteProfiles
class DebugLineWritePreferences
class DebugLineMenuTimer
class DebugLineFlushLog
class DebugLinePullBackCamera
class DebugLineVolumeUp
class DebugLineVolumeDown
class DebugLineVisualDelayUp
class DebugLineVisualDelayDown
class DebugLineForceCrash
class DebugLineUptime
Macros
#define DECLARE_ONE(x) static x g_##x
Functions
static bool IsGameplay ()
REGISTER_SCREEN_CLASS (ScreenDebugOverlay)
static RString GetDebugButtonName (const IDebugLine *pLine)
template<typename U , typename V >
static bool GetKeyFromMap (const map< U, V > &m, const V &val, U &key)
template<typename U , typename V >
static bool GetValueFromMap (const map< U, V > &m, const U &key, V &val)
static void SetSpeed ()
void ChangeVolume (float fDelta)
void ChangeVisualDelay (float fDelta)
static bool IsSelectProfilePersistent ()
static HighScore MakeRandomHighScore (float fPercentDP)
static void FillProfileStats (Profile *pProfile)
DECLARE_ONE (DebugLineAutoplay)
DECLARE_ONE (DebugLineAssist)
DECLARE_ONE (DebugLineAutosync)
DECLARE_ONE (DebugLineSlow)
DECLARE_ONE (DebugLineHalt)
DECLARE_ONE (DebugLineStats)
DECLARE_ONE (DebugLineVsync)
DECLARE_ONE (DebugLineAllowMultitexture)
DECLARE_ONE (DebugLineShowMasks)
DECLARE_ONE (DebugLineProfileSlot)
DECLARE_ONE (DebugLineClearProfileStats)
DECLARE_ONE (DebugLineFillProfileStats)
DECLARE_ONE (DebugLineSendNotesEnded)
DECLARE_ONE (DebugLineReloadCurrentScreen)
DECLARE_ONE (DebugLineRestartCurrentScreen)
DECLARE_ONE (DebugLineCurrentScreenOn)
DECLARE_ONE (DebugLineCurrentScreenOff)
DECLARE_ONE (DebugLineReloadTheme)
DECLARE_ONE (DebugLineReloadOverlayScreens)
DECLARE_ONE (DebugLineToggleErrors)
DECLARE_ONE (DebugLineShowRecentErrors)
DECLARE_ONE (DebugLineClearErrors)
DECLARE_ONE (DebugLineConvertXML)
DECLARE_ONE (DebugLineWriteProfiles)
DECLARE_ONE (DebugLineWritePreferences)
DECLARE_ONE (DebugLineMenuTimer)
DECLARE_ONE (DebugLineFlushLog)
DECLARE_ONE (DebugLinePullBackCamera)
DECLARE_ONE (DebugLineVolumeDown)
DECLARE_ONE (DebugLineVolumeUp)
DECLARE_ONE (DebugLineVisualDelayDown)
DECLARE_ONE (DebugLineVisualDelayUp)
DECLARE_ONE (DebugLineForceCrash)
DECLARE_ONE (DebugLineUptime)
DECLARE_ONE (DebugLineResetKeyMapping)
DECLARE_ONE (DebugLineMuteActions)
Variables
static bool g_bIsDisplayed = false
static bool g_bIsSlow = false
static bool g_bIsHalt = false
static RageTimer g_HaltTimer (RageZeroTimer)
static float g_fImageScaleCurrent = 1
static float g_fImageScaleDestination = 1
static const ThemeMetric< RageColor > BACKGROUND_COLOR ("ScreenDebugOverlay", "BackgroundColor")
static const ThemeMetric< RageColor > LINE_ON_COLOR ("ScreenDebugOverlay", "LineOnColor")
static const ThemeMetric< RageColor > LINE_OFF_COLOR ("ScreenDebugOverlay", "LineOffColor")
static const ThemeMetric< float > LINE_START_Y ("ScreenDebugOverlay", "LineStartY")
static const ThemeMetric< float > LINE_SPACING ("ScreenDebugOverlay", "LineSpacing")
static const ThemeMetric< float > LINE_BUTTON_X ("ScreenDebugOverlay", "LineButtonX")
static const ThemeMetric< float > LINE_FUNCTION_X ("ScreenDebugOverlay", "LineFunctionX")
static const ThemeMetric< float > PAGE_START_X ("ScreenDebugOverlay", "PageStartX")
static const ThemeMetric< float > PAGE_SPACING_X ("ScreenDebugOverlay", "PageSpacingX")
static LocalizedString ON ("ScreenDebugOverlay", "on")
static LocalizedString OFF ("ScreenDebugOverlay", "off")
static LocalizedString MUTE_ACTIONS_ON ("ScreenDebugOverlay", "Mute actions on")
static LocalizedString MUTE_ACTIONS_OFF ("ScreenDebugOverlay", "Mute actions off")
static vector< IDebugLine * > * g_pvpSubscribers = NULL
const int MAX_DEBUG_LINES = 30
static MapDebugToDI g_Mappings
static LocalizedString IN_GAMEPLAY ("ScreenDebugOverlay", "%s in gameplay")
static LocalizedString OR ("ScreenDebugOverlay", "or")
static LocalizedString DEBUG_MENU ("ScreenDebugOverlay", "Debug Menu")
static LocalizedString AUTO_PLAY ("ScreenDebugOverlay", "AutoPlay")
static LocalizedString ASSIST ("ScreenDebugOverlay", "Assist")
static LocalizedString AUTOSYNC ("ScreenDebugOverlay", "Autosync")
static LocalizedString COIN_MODE ("ScreenDebugOverlay", "CoinMode")
static LocalizedString HALT ("ScreenDebugOverlay", "Halt")
static LocalizedString RENDERING_STATS ("ScreenDebugOverlay", "Rendering Stats")
static LocalizedString VSYNC ("ScreenDebugOverlay", "Vsync")
static LocalizedString MULTITEXTURE ("ScreenDebugOverlay", "Multitexture")
static LocalizedString SCREEN_TEST_MODE ("ScreenDebugOverlay", "Screen Test Mode")
static LocalizedString SCREEN_SHOW_MASKS ("ScreenDebugOverlay", "Show Masks")
static LocalizedString PROFILE ("ScreenDebugOverlay", "Profile")
static LocalizedString CLEAR_PROFILE_STATS ("ScreenDebugOverlay", "Clear Profile Stats")
static LocalizedString FILL_PROFILE_STATS ("ScreenDebugOverlay", "Fill Profile Stats")
static LocalizedString SEND_NOTES_ENDED ("ScreenDebugOverlay", "Send Notes Ended")
static LocalizedString RESET_KEY_MAP ("ScreenDebugOverlay", "Reset key mapping to default")
static LocalizedString MUTE_ACTIONS ("ScreenDebugOverlay", "Mute actions")
static LocalizedString RELOAD ("ScreenDebugOverlay", "Reload")
static LocalizedString RESTART ("ScreenDebugOverlay", "Restart")
static LocalizedString SCREEN_ON ("ScreenDebugOverlay", "Send On To Screen")
static LocalizedString SCREEN_OFF ("ScreenDebugOverlay", "Send Off To Screen")
static LocalizedString RELOAD_OVERLAY_SCREENS ("ScreenDebugOverlay", "Reload Overlay Screens")
static LocalizedString TOGGLE_ERRORS ("ScreenDebugOverlay", "Toggle Errors")
static LocalizedString SHOW_RECENT_ERRORS ("ScreenDebugOverlay", "Show Recent Errors")
static LocalizedString CLEAR_ERRORS ("ScreenDebugOverlay", "Clear Errors")
static LocalizedString CONVERT_XML ("ScreenDebugOverlay", "Convert XML")
static LocalizedString RELOAD_THEME_AND_TEXTURES ("ScreenDebugOverlay", "Reload Theme and Textures")
static LocalizedString WRITE_PROFILES ("ScreenDebugOverlay", "Write Profiles")
static LocalizedString WRITE_PREFERENCES ("ScreenDebugOverlay", "Write Preferences")
static LocalizedString MENU_TIMER ("ScreenDebugOverlay", "Menu Timer")
static LocalizedString FLUSH_LOG ("ScreenDebugOverlay", "Flush Log")
static LocalizedString PULL_BACK_CAMERA ("ScreenDebugOverlay", "Pull Back Camera")
static LocalizedString VISUAL_DELAY_UP ("ScreenDebugOverlay", "Visual Delay Up")
static LocalizedString VISUAL_DELAY_DOWN ("ScreenDebugOverlay", "Visual Delay Down")
static LocalizedString VOLUME_UP ("ScreenDebugOverlay", "Volume Up")
static LocalizedString VOLUME_DOWN ("ScreenDebugOverlay", "Volume Down")
static LocalizedString UPTIME ("ScreenDebugOverlay", "Uptime")
static LocalizedString FORCE_CRASH ("ScreenDebugOverlay", "Force Crash")
static LocalizedString SLOW ("ScreenDebugOverlay", "Slow")
static LocalizedString CPU ("ScreenDebugOverlay", "CPU")
static LocalizedString REPLAY ("ScreenDebugOverlay", "REPLAY")
static LocalizedString SONG ("ScreenDebugOverlay", "Song")
static LocalizedString MACHINE ("ScreenDebugOverlay", "Machine")
static LocalizedString SYNC_TEMPO ("ScreenDebugOverlay", "Tempo")
static ProfileSlot g_ProfileSlot = ProfileSlot_Player1
Macro Definition Documentation
DECLARE_ONE
#define DECLARE_ONE (x) static x g_##x
Function Documentation
ChangeVisualDelay()
void ChangeVisualDelay (float fDelta)
References CLAMP(), f, Preference< T >::Get(), Preference< T >::GetPreferenceByName(), and Preference< T >::Set().
Referenced by DebugLineVisualDelayUp::DoAndLog(), and DebugLineVisualDelayDown::DoAndLog().
ChangeVolume()
void ChangeVolume (float fDelta)
References CLAMP(), f, Preference< T >::Get(), Preference< T >::GetPreferenceByName(), Preference< T >::Set(), RageSoundManager::SetMixVolume(), and SOUNDMAN.
Referenced by DebugLineVolumeUp::DoAndLog(), and DebugLineVolumeDown::DoAndLog().
DECLARE_ONE() [1/36]
DECLARE_ONE (DebugLineAutoplay)
DECLARE_ONE() [2/36]
DECLARE_ONE (DebugLineAssist)
DECLARE_ONE() [3/36]
DECLARE_ONE (DebugLineAutosync)
DECLARE_ONE() [4/36]
DECLARE_ONE (DebugLineSlow)
DECLARE_ONE() [5/36]
DECLARE_ONE (DebugLineHalt)
DECLARE_ONE() [6/36]
DECLARE_ONE (DebugLineStats)
DECLARE_ONE() [7/36]
DECLARE_ONE (DebugLineVsync)
DECLARE_ONE() [8/36]
DECLARE_ONE (DebugLineAllowMultitexture)
DECLARE_ONE() [9/36]
DECLARE_ONE (DebugLineShowMasks)
DECLARE_ONE() [10/36]
DECLARE_ONE (DebugLineProfileSlot)
DECLARE_ONE() [11/36]
DECLARE_ONE (DebugLineClearProfileStats)
DECLARE_ONE() [12/36]
DECLARE_ONE (DebugLineFillProfileStats)
DECLARE_ONE() [13/36]
DECLARE_ONE (DebugLineSendNotesEnded)
DECLARE_ONE() [14/36]
DECLARE_ONE (DebugLineReloadCurrentScreen)
DECLARE_ONE() [15/36]
DECLARE_ONE (DebugLineRestartCurrentScreen)
DECLARE_ONE() [16/36]
DECLARE_ONE (DebugLineCurrentScreenOn)
DECLARE_ONE() [17/36]
DECLARE_ONE (DebugLineCurrentScreenOff)
DECLARE_ONE() [18/36]
DECLARE_ONE (DebugLineReloadTheme)
DECLARE_ONE() [19/36]
DECLARE_ONE (DebugLineReloadOverlayScreens)
DECLARE_ONE() [20/36]
DECLARE_ONE (DebugLineToggleErrors)
DECLARE_ONE() [21/36]
DECLARE_ONE (DebugLineShowRecentErrors)
DECLARE_ONE() [22/36]
DECLARE_ONE (DebugLineClearErrors)
DECLARE_ONE() [23/36]
DECLARE_ONE (DebugLineConvertXML)
DECLARE_ONE() [24/36]
DECLARE_ONE (DebugLineWriteProfiles)
DECLARE_ONE() [25/36]
DECLARE_ONE (DebugLineWritePreferences)
DECLARE_ONE() [26/36]
DECLARE_ONE (DebugLineMenuTimer)
DECLARE_ONE() [27/36]
DECLARE_ONE (DebugLineFlushLog)
DECLARE_ONE() [28/36]
DECLARE_ONE (DebugLinePullBackCamera)
DECLARE_ONE() [29/36]
DECLARE_ONE (DebugLineVolumeDown)
DECLARE_ONE() [30/36]
DECLARE_ONE (DebugLineVolumeUp)
DECLARE_ONE() [31/36]
DECLARE_ONE (DebugLineVisualDelayDown)
DECLARE_ONE() [32/36]
DECLARE_ONE (DebugLineVisualDelayUp)
DECLARE_ONE() [33/36]
DECLARE_ONE (DebugLineForceCrash)
DECLARE_ONE() [34/36]
DECLARE_ONE (DebugLineUptime)
DECLARE_ONE() [35/36]
DECLARE_ONE (DebugLineResetKeyMapping)
DECLARE_ONE() [36/36]
DECLARE_ONE (DebugLineMuteActions)
FillProfileStats()
static void FillProfileStats (Profile * pProfile) static
References Profile::AddStepsHighScore(), f, FOREACH, SongManager::GetAllSongs(), Profile::IncrementStepsPlayCount(), Profile::InitSongScores(), MakeRandomHighScore(), random_up_to(), randomf(), SCREENMAN, SONGMAN, and ScreenManager::ZeroNextUpdate().
Referenced by DebugLineFillProfileStats::DoAndLog().
GetDebugButtonName()
static RString GetDebugButtonName (const IDebugLine * pLine) static
References IDebugLine::all_screens, FAIL_M, IDebugLine::gameplay_only, RageInput::GetDeviceSpecificInputString(), IDebugLine::GetType(), LocalizedString::GetValue(), IN_GAMEPLAY, INPUTMAN, IDebugLine::m_Button, and ssprintf().
Referenced by ScreenDebugOverlay::UpdateText().
GetKeyFromMap()
template<typename U , typename V > static bool GetKeyFromMap (const map< U, V > & m, const V & val, U & key) static
Referenced by ScreenDebugOverlay::Init().
GetValueFromMap()
template<typename U , typename V > static bool GetValueFromMap (const map< U, V > & m, const U & key, V & val) static
Referenced by ScreenDebugOverlay::Input().
IsGameplay()
static bool IsGameplay () static
References gameplay, Screen::GetScreenType(), ScreenManager::GetTopScreen(), and SCREENMAN.
Referenced by ScreenDebugOverlay::Input().
IsSelectProfilePersistent()
static bool IsSelectProfilePersistent () static
References g_ProfileSlot, ProfileManager::IsPersistentProfile(), and PROFILEMAN.
Referenced by DebugLineProfileSlot::IsEnabled(), DebugLineClearProfileStats::IsEnabled(), DebugLineFillProfileStats::IsEnabled(), and DebugLineWriteProfiles::IsEnabled().
MakeRandomHighScore()
static HighScore MakeRandomHighScore (float fPercentDP) static
References PlayerOptions::ChooseRandomModifiers(), f, FOREACH_ENUM, DateTime::GetNowDateTime(), PlayerOptions::GetString(), Grade_Failed, Grade_Tier01, Grade_Tier06, Profile::MakeGuid(), randomf(), RandomInt(), SCALE, HighScore::SetAliveSeconds(), HighScore::SetDateTime(), HighScore::SetGrade(), HighScore::SetHoldNoteScore(), HighScore::SetMachineGuid(), HighScore::SetModifiers(), HighScore::SetName(), HighScore::SetPercentDP(), HighScore::SetPlayerGuid(), HighScore::SetProductID(), HighScore::SetRadarValues(), HighScore::SetScore(), and HighScore::SetTapNoteScore().
Referenced by FillProfileStats().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenDebugOverlay)
SetSpeed()
static void SetSpeed () static
Referenced by DebugLineSlow::DoAndLog(), and DebugLineHalt::DoAndLog().
Variable Documentation
ASSIST
LocalizedString ASSIST("ScreenDebugOverlay", "Assist") static
Referenced by DebugLineAssist::GetDisplayTitle().
AUTO_PLAY
LocalizedString AUTO_PLAY("ScreenDebugOverlay", "AutoPlay") static
Referenced by DebugLineAutoplay::GetDisplayTitle().
AUTOSYNC
LocalizedString AUTOSYNC("ScreenDebugOverlay", "Autosync") static
Referenced by DebugLineAutosync::GetDisplayTitle().
BACKGROUND_COLOR
const ThemeMetric<RageColor> BACKGROUND_COLOR("ScreenDebugOverlay", "BackgroundColor") static
Referenced by ScreenDebugOverlay::Init().
CLEAR_ERRORS
LocalizedString CLEAR_ERRORS("ScreenDebugOverlay", "Clear Errors") static
Referenced by DebugLineClearErrors::GetDisplayTitle().
CLEAR_PROFILE_STATS
LocalizedString CLEAR_PROFILE_STATS("ScreenDebugOverlay", "Clear Profile Stats") static
Referenced by DebugLineClearProfileStats::GetDisplayTitle().
COIN_MODE
LocalizedString COIN_MODE("ScreenDebugOverlay", "CoinMode") static
CONVERT_XML
LocalizedString CONVERT_XML("ScreenDebugOverlay", "Convert XML") static
Referenced by DebugLineConvertXML::GetDisplayTitle().
CPU
LocalizedString CPU("ScreenDebugOverlay", "CPU") static
Referenced by DebugLineAutoplay::GetDisplayValue().
DEBUG_MENU
LocalizedString DEBUG_MENU("ScreenDebugOverlay", "Debug Menu") static
Referenced by ScreenDebugOverlay::Init().
FILL_PROFILE_STATS
LocalizedString FILL_PROFILE_STATS("ScreenDebugOverlay", "Fill Profile Stats") static
Referenced by DebugLineFillProfileStats::GetDisplayTitle().
FLUSH_LOG
LocalizedString FLUSH_LOG("ScreenDebugOverlay", "Flush Log") static
Referenced by DebugLineFlushLog::GetDisplayTitle().
FORCE_CRASH
LocalizedString FORCE_CRASH("ScreenDebugOverlay", "Force Crash") static
Referenced by DebugLineForceCrash::GetDisplayTitle().
g_bIsDisplayed
bool g_bIsDisplayed = false static
Referenced by ScreenDebugOverlay::Input(), and ScreenDebugOverlay::Update().
g_bIsHalt
bool g_bIsHalt = false static
Referenced by DebugLineHalt::DoAndLog(), DebugLineHalt::IsEnabled(), ScreenDebugOverlay::Update(), and ScreenDebugOverlay::UpdateText().
g_bIsSlow
bool g_bIsSlow = false static
Referenced by DebugLineSlow::DoAndLog(), DebugLineSlow::IsEnabled(), and ScreenDebugOverlay::Update().
g_fImageScaleCurrent
float g_fImageScaleCurrent = 1 static
Referenced by ScreenDebugOverlay::Update().
g_fImageScaleDestination
float g_fImageScaleDestination = 1 static
Referenced by DebugLinePullBackCamera::DoAndLog(), DebugLinePullBackCamera::IsEnabled(), and ScreenDebugOverlay::Update().
g_HaltTimer
RageTimer g_HaltTimer(RageZeroTimer) static
Referenced by DebugLineHalt::DoAndLog(), and ScreenDebugOverlay::UpdateText().
g_Mappings
MapDebugToDI g_Mappings static
g_ProfileSlot
ProfileSlot g_ProfileSlot = ProfileSlot_Player1 static
Referenced by DebugLineProfileSlot::DoAndLog(), DebugLineClearProfileStats::DoAndLog(), DebugLineFillProfileStats::DoAndLog(), DebugLineWriteProfiles::DoAndLog(), DebugLineProfileSlot::GetDisplayValue(), and IsSelectProfilePersistent().
g_pvpSubscribers
vector<IDebugLine*>* g_pvpSubscribers = NULL static
Referenced by IDebugLine::IDebugLine(), ScreenDebugOverlay::Init(), ScreenDebugOverlay::Input(), and ScreenDebugOverlay::UpdateText().
HALT
LocalizedString HALT("ScreenDebugOverlay", "Halt") static
Referenced by DebugLineHalt::GetDisplayTitle().
IN_GAMEPLAY
LocalizedString IN_GAMEPLAY("ScreenDebugOverlay", "%s in gameplay") static
Referenced by GetDebugButtonName().
LINE_BUTTON_X
const ThemeMetric<float> LINE_BUTTON_X("ScreenDebugOverlay", "LineButtonX") static
Referenced by ScreenDebugOverlay::UpdateText().
LINE_FUNCTION_X
const ThemeMetric<float> LINE_FUNCTION_X("ScreenDebugOverlay", "LineFunctionX") static
Referenced by ScreenDebugOverlay::UpdateText().
LINE_OFF_COLOR
const ThemeMetric<RageColor> LINE_OFF_COLOR("ScreenDebugOverlay", "LineOffColor") static
Referenced by ScreenDebugOverlay::UpdateText().
LINE_ON_COLOR
const ThemeMetric<RageColor> LINE_ON_COLOR("ScreenDebugOverlay", "LineOnColor") static
Referenced by ScreenDebugOverlay::UpdateText().
LINE_SPACING
const ThemeMetric<float> LINE_SPACING("ScreenDebugOverlay", "LineSpacing") static
Referenced by ScreenDebugOverlay::UpdateText().
LINE_START_Y
const ThemeMetric<float> LINE_START_Y("ScreenDebugOverlay", "LineStartY") static
Referenced by ScreenDebugOverlay::UpdateText().
MACHINE
LocalizedString MACHINE("ScreenDebugOverlay", "Machine") static
Referenced by DebugLineAutosync::GetDisplayValue().
MAX_DEBUG_LINES
const int MAX_DEBUG_LINES = 30
Referenced by MapDebugToDI::Clear().
MENU_TIMER
LocalizedString MENU_TIMER("ScreenDebugOverlay", "Menu Timer") static
Referenced by DebugLineMenuTimer::GetDisplayTitle().
MULTITEXTURE
LocalizedString MULTITEXTURE("ScreenDebugOverlay", "Multitexture") static
Referenced by DebugLineAllowMultitexture::GetDisplayTitle().
MUTE_ACTIONS
LocalizedString MUTE_ACTIONS("ScreenDebugOverlay", "Mute actions") static
Referenced by DebugLineMuteActions::GetDisplayTitle().
MUTE_ACTIONS_OFF
LocalizedString MUTE_ACTIONS_OFF("ScreenDebugOverlay", "Mute actions off") static
Referenced by DebugLineMuteActions::DoAndLog(), and ScreenDebugOverlay::Input().
MUTE_ACTIONS_ON
LocalizedString MUTE_ACTIONS_ON("ScreenDebugOverlay", "Mute actions on") static
Referenced by DebugLineMuteActions::DoAndLog(), and ScreenDebugOverlay::Input().
OFF
LocalizedString OFF("ScreenDebugOverlay", "off") static
Referenced by IDebugLine::GetDisplayValue(), DebugLineAutoplay::GetDisplayValue(), DebugLineAssist::GetDisplayValue(), and DebugLineAutosync::GetDisplayValue().
ON
LocalizedString ON("ScreenDebugOverlay", "on") static
Referenced by IDebugLine::GetDisplayValue(), and DebugLineAutoplay::GetDisplayValue().
OR
LocalizedString OR("ScreenDebugOverlay", "or") static
PAGE_SPACING_X
const ThemeMetric<float> PAGE_SPACING_X("ScreenDebugOverlay", "PageSpacingX") static
Referenced by ScreenDebugOverlay::Init().
PAGE_START_X
const ThemeMetric<float> PAGE_START_X("ScreenDebugOverlay", "PageStartX") static
Referenced by ScreenDebugOverlay::Init().
PROFILE
LocalizedString PROFILE("ScreenDebugOverlay", "Profile") static
Referenced by DebugLineProfileSlot::GetDisplayTitle().
PULL_BACK_CAMERA
LocalizedString PULL_BACK_CAMERA("ScreenDebugOverlay", "Pull Back Camera") static
Referenced by DebugLinePullBackCamera::GetDisplayTitle().
RELOAD
LocalizedString RELOAD("ScreenDebugOverlay", "Reload") static
Referenced by DebugLineReloadCurrentScreen::GetDisplayTitle().
RELOAD_OVERLAY_SCREENS
LocalizedString RELOAD_OVERLAY_SCREENS("ScreenDebugOverlay", "Reload Overlay Screens") static
Referenced by DebugLineReloadOverlayScreens::GetDisplayTitle().
RELOAD_THEME_AND_TEXTURES
LocalizedString RELOAD_THEME_AND_TEXTURES("ScreenDebugOverlay", "Reload Theme and Textures") static
Referenced by DebugLineReloadTheme::GetDisplayTitle().
RENDERING_STATS
LocalizedString RENDERING_STATS("ScreenDebugOverlay", "Rendering Stats") static
Referenced by DebugLineStats::GetDisplayTitle().
REPLAY
LocalizedString REPLAY("ScreenDebugOverlay", "REPLAY") static
Referenced by DebugLineAutoplay::GetDisplayValue().
RESET_KEY_MAP
LocalizedString RESET_KEY_MAP("ScreenDebugOverlay", "Reset key mapping to default") static
Referenced by DebugLineResetKeyMapping::GetDisplayTitle().
RESTART
LocalizedString RESTART("ScreenDebugOverlay", "Restart") static
Referenced by DebugLineRestartCurrentScreen::GetDisplayTitle().
SCREEN_OFF
LocalizedString SCREEN_OFF("ScreenDebugOverlay", "Send Off To Screen") static
Referenced by DebugLineCurrentScreenOff::GetDisplayTitle().
SCREEN_ON
LocalizedString SCREEN_ON("ScreenDebugOverlay", "Send On To Screen") static
Referenced by DebugLineCurrentScreenOn::GetDisplayTitle().
SCREEN_SHOW_MASKS
LocalizedString SCREEN_SHOW_MASKS("ScreenDebugOverlay", "Show Masks") static
Referenced by DebugLineShowMasks::GetDisplayTitle().
SCREEN_TEST_MODE
LocalizedString SCREEN_TEST_MODE("ScreenDebugOverlay", "Screen Test Mode") static
SEND_NOTES_ENDED
LocalizedString SEND_NOTES_ENDED("ScreenDebugOverlay", "Send Notes Ended") static
Referenced by DebugLineSendNotesEnded::GetDisplayTitle().
SHOW_RECENT_ERRORS
LocalizedString SHOW_RECENT_ERRORS("ScreenDebugOverlay", "Show Recent Errors") static
Referenced by DebugLineShowRecentErrors::GetDisplayTitle().
SLOW
LocalizedString SLOW("ScreenDebugOverlay", "Slow") static
Referenced by DebugLineSlow::GetDisplayTitle().
SONG
LocalizedString SONG("ScreenDebugOverlay", "Song") static
Referenced by DebugLineAutosync::GetDisplayValue().
SYNC_TEMPO
LocalizedString SYNC_TEMPO("ScreenDebugOverlay", "Tempo") static
Referenced by DebugLineAutosync::GetDisplayValue().
TOGGLE_ERRORS
LocalizedString TOGGLE_ERRORS("ScreenDebugOverlay", "Toggle Errors") static
Referenced by DebugLineToggleErrors::GetDisplayTitle().
UPTIME
LocalizedString UPTIME("ScreenDebugOverlay", "Uptime") static
Referenced by DebugLineUptime::GetDisplayTitle().
VISUAL_DELAY_DOWN
LocalizedString VISUAL_DELAY_DOWN("ScreenDebugOverlay", "Visual Delay Down") static
Referenced by DebugLineVisualDelayDown::GetDisplayTitle().
VISUAL_DELAY_UP
LocalizedString VISUAL_DELAY_UP("ScreenDebugOverlay", "Visual Delay Up") static
Referenced by DebugLineVisualDelayUp::GetDisplayTitle().
VOLUME_DOWN
LocalizedString VOLUME_DOWN("ScreenDebugOverlay", "Volume Down") static
Referenced by DebugLineVolumeDown::GetDisplayTitle().
VOLUME_UP
LocalizedString VOLUME_UP("ScreenDebugOverlay", "Volume Up") static
Referenced by DebugLineVolumeUp::GetDisplayTitle().
VSYNC
LocalizedString VSYNC("ScreenDebugOverlay", "Vsync") static
Referenced by DebugLineVsync::GetDisplayTitle().
WRITE_PREFERENCES
LocalizedString WRITE_PREFERENCES("ScreenDebugOverlay", "Write Preferences") static
Referenced by DebugLineWritePreferences::GetDisplayTitle().
WRITE_PROFILES
LocalizedString WRITE_PROFILES("ScreenDebugOverlay", "Write Profiles") static
Referenced by DebugLineWriteProfiles::GetDisplayTitle().