Etterna: RenderTarget Class Reference
RenderTarget Class Reference abstract
#include <RageDisplay_D3D.h>
Public Member Functions
virtual ~RenderTarget ()=default
virtual void Create (const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut)=0
virtual unsigned GetTexture () const =0
virtual void StartRenderingTo ()=0
virtual void FinishRenderingTo ()=0
virtual bool InvertY () const
const RenderTargetParam & GetParam () const
virtual ~RenderTarget ()=default
virtual void Create (const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut)=0
virtual unsigned GetTexture () const =0
virtual void StartRenderingTo ()=0
virtual void FinishRenderingTo ()=0
virtual bool InvertY () const
const RenderTargetParam & GetParam () const
Protected Attributes
RenderTargetParam m_Param
Constructor & Destructor Documentation
~RenderTarget() [1/2]
virtual RenderTarget::~RenderTarget () virtual default
~RenderTarget() [2/2]
virtual RenderTarget::~RenderTarget () virtual default
Member Function Documentation
Create() [1/2]
virtual void RenderTarget::Create (const RenderTargetParam & param, int & iTextureWidthOut, int & iTextureHeightOut) pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
Create() [2/2]
virtual void RenderTarget::Create (const RenderTargetParam & param, int & iTextureWidthOut, int & iTextureHeightOut) pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
Referenced by RageDisplay_Legacy::CreateRenderTarget().
FinishRenderingTo() [1/2]
virtual void RenderTarget::FinishRenderingTo () pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
FinishRenderingTo() [2/2]
virtual void RenderTarget::FinishRenderingTo () pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
Referenced by RageDisplay_D3D::SetRenderTarget(), and RageDisplay_Legacy::SetRenderTarget().
GetParam() [1/2]
const RenderTargetParam& RenderTarget::GetParam () const inline
References m_Param.
GetParam() [2/2]
const RenderTargetParam& RenderTarget::GetParam () const inline
References m_Param.
GetTexture() [1/2]
virtual unsigned RenderTarget::GetTexture () const pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
GetTexture() [2/2]
virtual unsigned RenderTarget::GetTexture () const pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
Referenced by RageDisplay_Legacy::CreateRenderTarget().
InvertY() [1/2]
virtual bool RenderTarget::InvertY () const inline virtual
Reimplemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, and RenderTarget_Win32.
InvertY() [2/2]
virtual bool RenderTarget::InvertY () const inline virtual
Reimplemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, and RenderTarget_Win32.
StartRenderingTo() [1/2]
virtual void RenderTarget::StartRenderingTo () pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
StartRenderingTo() [2/2]
virtual void RenderTarget::StartRenderingTo () pure virtual
Implemented in RenderTarget_FramebufferObject, D3DRenderTarget_FramebufferObject, RenderTarget_X11, RenderTarget_Win32, and RenderTarget_MacOSX.
Member Data Documentation
m_Param
RenderTargetParam RenderTarget::m_Param protected
Referenced by RenderTarget_Win32::Create(), D3DRenderTarget_FramebufferObject::Create(), and GetParam().
The documentation for this class was generated from the following files:
RageDisplay_D3D.h
RageDisplay_OGL_Helpers.h