Etterna: WheelNotifyIcon Class Reference
WheelNotifyIcon Class Reference
A little graphic to the side of the song's text banner in the MusicWheel.
#include <WheelNotifyIcon.h>
Classes
struct Flags
Public Member Functions
WheelNotifyIcon ()
void SetFlags (Flags flags)
void Update (float fDeltaTime) override
bool EarlyAbortDraw () const override
Allow the Actor to be aborted early.
Public Member Functions inherited from Sprite
Sprite ()
Sprite (const Sprite &cpy)
~Sprite () override
void InitState () override
void LoadFromNode (const XNode *pNode) override
Sprite * Copy () const override
void DrawPrimitives () override
Draw the primitives of the Actor.
void UpdateAnimationState ()
virtual void Load (const RageTextureID &ID)
void SetTexture (RageTexture *pTexture)
void UnloadTexture ()
RageTexture * GetTexture ()
void EnableAnimation (bool bEnable) override
int GetNumStates () const override
void SetState (int iNewState) override
int GetState ()
float GetAnimationLengthSeconds () const override
virtual void RecalcAnimationLengthSeconds ()
void SetSecondsIntoAnimation (float fSeconds) override
void SetStateProperties (const vector< State > &new_states)
RString GetTexturePath () const
void SetCustomTextureRect (const RectF &new_texcoord_frect)
void SetCustomTextureCoords (float fTexCoords[8])
void SetCustomImageRect (RectF rectImageCoords)
void SetCustomImageCoords (float fImageCoords[8])
void SetCustomPosCoords (float fPosCoords[8])
const RectF * GetCurrentTextureCoordRect () const
const RectF * GetTextureCoordRectForState (int iState) const
void StopUsingCustomCoords ()
void StopUsingCustomPosCoords ()
void GetActiveTextureCoords (float fTexCoordsOut[8]) const
void StretchTexCoords (float fX, float fY)
void AddImageCoords (float fX, float fY)
void SetEffectMode (EffectMode em)
void LoadFromCached (const RString &sDir, const RString &sPath)
void SetTexCoordVelocity (float fVelX, float fVelY)
void ScaleToClipped (float fWidth, float fHeight)
Scale the Sprite while maintaining the aspect ratio.
void CropTo (float fWidth, float fHeight)
void PushSelf (lua_State *L) override
void SetAllStateDelays (float fDelay)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void BeginDraw ()
Start the drawing and push the transform on the world matrix stack.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
virtual void EndDraw ()
Pop the transform from the world matrix stack.
bool IsFirstUpdate () const
virtual void UpdateInternal (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
virtual void FinishTweening ()
virtual void HurryTweening (float factor)
virtual float GetTweenTimeLeft () const
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
virtual void SetZTestMode (ZTestMode mode)
virtual void SetZWrite (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
virtual void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void HandleMessage (const Message &msg) override
virtual void SetUpdateRate (float)
virtual float GetUpdateRate ()
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Types
enum Icons {
training = 0, best1, best2, best3,
edits, long_ver, marathon, empty
}
What types of icons are available for the Song?
Protected Attributes
vector< Icons > m_vIconsToShow
the list of Icons to show.
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Sprite
static Sprite * NewBlankSprite ()
static RageTextureID SongBGTexture (RageTextureID ID)
static RageTextureID SongBannerTexture (RageTextureID ID)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Sprite
bool m_DecodeMovie
bool m_use_effect_clock_for_texcoords
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from Sprite
void LoadFromTexture (const RageTextureID &ID)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A little graphic to the side of the song's text banner in the MusicWheel.
Member Enumeration Documentation
Icons
enum WheelNotifyIcon::Icons protected
What types of icons are available for the Song?
Enumerator
training
best1
best2
best3
edits
long_ver
marathon
empty
Constructor & Destructor Documentation
WheelNotifyIcon()
WheelNotifyIcon::WheelNotifyIcon ()
References ThemeManager::GetPathG(), Sprite::Load(), Actor::StopAnimating(), and THEME.
Member Function Documentation
EarlyAbortDraw()
bool WheelNotifyIcon::EarlyAbortDraw () const override virtual
Allow the Actor to be aborted early.
Subclasses may wish to overwrite this to allow for aborted actors.
Returns
false, as by default Actors shouldn't be aborted on drawing.
Reimplemented from Sprite.
References Sprite::EarlyAbortDraw(), and m_vIconsToShow.
SetFlags()
void WheelNotifyIcon::SetFlags (Flags flags)
References WheelNotifyIcon::Flags::bEdits, best1, best2, best3, WheelNotifyIcon::Flags::bHasBeginnerOr1Meter, BLINK_BEST_ICON, edits, empty, FAIL_M, WheelNotifyIcon::Flags::iPlayersBestNumber, WheelNotifyIcon::Flags::iStagesForSong, long_ver, m_vIconsToShow, marathon, min(), NUM_ICONS_TO_SHOW, SHOW_TRAINING, ssprintf(), training, and Update().
Referenced by MusicWheelItem::LoadFromWheelItemData().
Update()
void WheelNotifyIcon::Update (float fDeltaTime) override virtual
Reimplemented from Sprite.
References RageTimer::GetTimeSinceStartFast(), m_vIconsToShow, Sprite::SetState(), and Sprite::Update().
Referenced by SetFlags().
Member Data Documentation
m_vIconsToShow
vector<Icons> WheelNotifyIcon::m_vIconsToShow protected
the list of Icons to show.
Referenced by EarlyAbortDraw(), SetFlags(), and Update().
The documentation for this class was generated from the following files:
WheelNotifyIcon.h
WheelNotifyIcon.cpp