Etterna: NoteTypes.cpp File Reference
NoteTypes.cpp File Reference
#include "global.h"
#include "NoteTypes.h"
#include "LocalizedString.h"
#include "LuaManager.h"
#include "RageUtil.h"
#include "XmlFile.h"
#include "LuaBinding.h"
Classes
class LunaTapNoteResult
Allow Lua to have access to the TapNoteResult.
class LunaHoldNoteResult
Allow Lua to have access to the HoldNoteResult.
class LunaTapNote
Allow Lua to have access to the TapNote.
Functions
XToString (TapNoteType)
XToLocalizedString (TapNoteType)
LuaXType (TapNoteType)
XToString (TapNoteSubType)
XToLocalizedString (TapNoteSubType)
LuaXType (TapNoteSubType)
XToString (TapNoteSource)
XToLocalizedString (TapNoteSource)
LuaXType (TapNoteSource)
XToString (NoteType)
LuaXType (NoteType)
XToLocalizedString (NoteType)
float NoteTypeToBeat (NoteType nt)
Convert the NoteType to a beat representation.
int NoteTypeToRow (NoteType nt)
NoteType GetNoteType (int row)
Retrieve the proper quantized NoteType for the note.
NoteType BeatToNoteType (float fBeat)
bool IsNoteOfType (int row, NoteType t)
Determine if the row has a particular type of quantized note.
Variables
TapNote TAP_EMPTY (TapNoteType_Empty, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_TAP (TapNoteType_Tap, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_LIFT (TapNoteType_Lift, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_HOLD_HEAD (TapNoteType_HoldHead, TapNoteSubType_Hold, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_ROLL_HEAD (TapNoteType_HoldHead, TapNoteSubType_Roll, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_MINE (TapNoteType_Mine, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_AUTO_KEYSOUND (TapNoteType_AutoKeysound, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ORIGINAL_FAKE (TapNoteType_Fake, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
TapNote TAP_ADDITION_TAP (TapNoteType_Tap, TapNoteSubType_Invalid, TapNoteSource_Addition, -1)
TapNote TAP_ADDITION_MINE (TapNoteType_Mine, TapNoteSubType_Invalid, TapNoteSource_Addition, -1)
static const char * TapNoteTypeNames []
static const char * TapNoteSubTypeNames []
static const char * TapNoteSourceNames []
static const char * NoteTypeNames []
static const int BEATS_PER_MEASURE = 4
The number of beats per measure.
static const int ROWS_PER_MEASURE = ROWS_PER_BEAT * BEATS_PER_MEASURE
The number of rows used in a measure.
Function Documentation
BeatToNoteType()
NoteType BeatToNoteType (float fBeat)
References BeatToNoteRow(), and GetNoteType().
Referenced by NoteDisplay::DrawActor(), NoteDisplay::GetHoldSprite(), and NoteDisplay::GetTapActor().
GetNoteType()
NoteType GetNoteType (int row)
Retrieve the proper quantized NoteType for the note.
Parameters
row The row to check for.
Returns
the quantized NoteType.
References NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, and ROWS_PER_MEASURE.
Referenced by BeatToNoteType(), IsNoteOfType(), ScreenGameplay::SendCrossedMessages(), and Player::Step().
IsNoteOfType()
bool IsNoteOfType (int row, NoteType t)
Determine if the row has a particular type of quantized note.
Parameters
row the row in the Steps.
t the quantized NoteType to check for.
Returns
true if the NoteType is t, false otherwise.
References GetNoteType().
LuaXType() [1/4]
LuaXType (TapNoteType)
LuaXType() [2/4]
LuaXType (TapNoteSubType)
LuaXType() [3/4]
LuaXType (TapNoteSource)
LuaXType() [4/4]
LuaXType (NoteType)
NoteTypeToBeat()
float NoteTypeToBeat (NoteType nt)
Convert the NoteType to a beat representation.
Parameters
nt the NoteType to check.
Returns
the proper beat.
References FAIL_M, NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, NoteType_Invalid, and ssprintf().
Referenced by NoteDataUtil::GetETTNoteDataString(), NoteDataUtil::GetSmallestNoteTypeInRange(), NoteDataUtil::GetSMNoteDataString(), and NoteDataUtil::SnapToNearestNoteType().
NoteTypeToRow()
int NoteTypeToRow (NoteType nt)
References FAIL_M, NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, and NoteType_Invalid.
XToLocalizedString() [1/4]
XToLocalizedString (TapNoteType)
XToLocalizedString() [2/4]
XToLocalizedString (TapNoteSubType)
XToLocalizedString() [3/4]
XToLocalizedString (TapNoteSource)
XToLocalizedString() [4/4]
XToLocalizedString (NoteType)
XToString() [1/4]
XToString (TapNoteType)
XToString() [2/4]
XToString (TapNoteSubType)
XToString() [3/4]
XToString (TapNoteSource)
XToString() [4/4]
XToString (NoteType)
Variable Documentation
BEATS_PER_MEASURE
const int BEATS_PER_MEASURE = 4 static
The number of beats per measure.
FIXME: Look at the time signature of the song and use that instead at some point.
NoteTypeNames
const char* NoteTypeNames[] static
Initial value:
= {
    "4th", "8th", "12th", "16th", "24th", "32nd", "48th", "64th", "192nd",
}
ROWS_PER_MEASURE
const int ROWS_PER_MEASURE = ROWS_PER_BEAT * BEATS_PER_MEASURE static
The number of rows used in a measure.
FIXME: Similar to the above, use time signatures and don't force hard-coded values.
Referenced by GetNoteType().
TAP_ADDITION_MINE
TapNote TAP_ADDITION_MINE(TapNoteType_Mine, TapNoteSubType_Invalid, TapNoteSource_Addition, -1)
Referenced by NoteDataUtil::AddMines().
TAP_ADDITION_TAP
TapNote TAP_ADDITION_TAP(TapNoteType_Tap, TapNoteSubType_Invalid, TapNoteSource_Addition, -1)
Referenced by NoteDataUtil::AnchorJS(), NoteDataUtil::Echo(), NoteDataUtil::IcyWorld(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::JackJS(), NoteDataUtil::Stomp(), and NoteDataUtil::Wide().
TAP_EMPTY
TapNote TAP_EMPTY(TapNoteType_Empty, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by NoteData::AddHoldNote(), NoteData::ClearRangeForTrack(), NoteDataUtil::CollapseLeft(), Player::DoTapScoreNone(), GenerateCacheDataStructure(), NoteData::GetTapNote(), Player::HandleHoldCheckpoint(), NoteDataWithScoring::LastTapNoteWithResult(), NoteDataUtil::Little(), AutoKeysounds::LoadAutoplaySoundsInto(), LoadFromKSFFile(), NotesToDWIString(), ParseNoteData(), PlaceAutoKeysound(), BMSChartReader::ReadNoteData(), NoteDataUtil::RemoveFakes(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), NoteData::SetTapNote(), NoteDataUtil::SnapToNearestNoteType(), and WriteDWINotesField().
TAP_ORIGINAL_AUTO_KEYSOUND
TapNote TAP_ORIGINAL_AUTO_KEYSOUND(TapNoteType_AutoKeysound, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by LoadFromSMNoteDataStringWithPlayer(), and BMSChartReader::ReadNoteData().
TAP_ORIGINAL_FAKE
TapNote TAP_ORIGINAL_FAKE(TapNoteType_Fake, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_HOLD_HEAD
TapNote TAP_ORIGINAL_HOLD_HEAD(TapNoteType_HoldHead, TapNoteSubType_Hold, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::ConvertTapsToHolds(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), OsuLoader::LoadNoteDataFromParsedData(), and ParseNoteData().
TAP_ORIGINAL_LIFT
TapNote TAP_ORIGINAL_LIFT(TapNoteType_Lift, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), and OsuLoader::LoadNoteDataFromParsedData().
TAP_ORIGINAL_MINE
TapNote TAP_ORIGINAL_MINE(TapNoteType_Mine, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_ROLL_HEAD
TapNote TAP_ORIGINAL_ROLL_HEAD(TapNoteType_HoldHead, TapNoteSubType_Roll, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_TAP
TapNote TAP_ORIGINAL_TAP(TapNoteType_Tap, TapNoteSubType_Invalid, TapNoteSource_Original, -1)
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), OsuLoader::LoadNoteDataFromParsedData(), ParseNoteData(), and BMSChartReader::ReadNoteData().
TapNoteSourceNames
const char* TapNoteSourceNames[] static
Initial value:
= {
    "Original",
    "Addition",
}
TapNoteSubTypeNames
const char* TapNoteSubTypeNames[] static
Initial value:
= {
    "Hold",
    "Roll",
}
TapNoteTypeNames
const char* TapNoteTypeNames[] static
Initial value:
= {
    "Empty", "Tap",  "HoldHead",     "HoldTail",
    "Mine",  "Lift", "AutoKeySound", "Fake",
}