Etterna: RageDisplay Class Reference
RageDisplay Class Reference abstract
#include <RageDisplay.h>
Classes
struct RagePixelFormatDesc
Public Types
enum GraphicsFileFormat { SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_LOW_QUAL, SAVE_LOSSY_HIGH_QUAL }
Public Member Functions
virtual const RagePixelFormatDesc * GetPixelFormatDesc (RagePixelFormat pf) const =0
RageDisplay ()
virtual ~RageDisplay ()
virtual RString Init (const VideoModeParams &p, bool bAllowUnacceleratedRenderer)=0
virtual RString GetApiDescription () const =0
virtual void GetDisplayResolutions (DisplayResolutions &out) const =0
void SetPresentTime (std::chrono::nanoseconds presentTime)
RString SetVideoMode (VideoModeParams p, bool &bNeedReloadTextures)
virtual void ResolutionChanged ()
bool IsD3D ()
virtual bool BeginFrame ()
virtual void EndFrame ()
virtual const VideoModeParams * GetActualVideoModeParams () const =0
bool IsWindowed ()
virtual void SetBlendMode (BlendMode mode)=0
virtual bool SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime=false)=0
virtual bool SupportsThreadedRendering ()
virtual bool SupportsPerVertexMatrixScale ()=0
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void BeginConcurrentRendering ()
virtual void EndConcurrentRendering ()
virtual unsigned CreateTexture (RagePixelFormat pixfmt, RageSurface *img, bool bGenerateMipMaps)=0
virtual void UpdateTexture (unsigned iTexHandle, RageSurface *img, int xoffset, int yoffset, int width, int height)=0
virtual void DeleteTexture (unsigned iTexHandle)=0
virtual RageTextureLock * CreateTextureLock ()
virtual void ClearAllTextures ()=0
virtual int GetNumTextureUnits ()=0
virtual void SetTexture (TextureUnit, unsigned)=0
virtual void SetTextureMode (TextureUnit, TextureMode)=0
virtual void SetTextureWrapping (TextureUnit, bool)=0
virtual int GetMaxTextureSize () const =0
virtual void SetTextureFiltering (TextureUnit, bool)=0
virtual void SetEffectMode (EffectMode)
virtual bool IsEffectModeSupported (EffectMode effect)
bool SupportsRenderToTexture () const
virtual unsigned CreateRenderTarget (const RenderTargetParam &, int &, int &)
virtual unsigned GetRenderTarget ()
virtual void SetRenderTarget (unsigned, bool=true)
virtual bool IsZTestEnabled () const =0
virtual bool IsZWriteEnabled () const =0
virtual void SetZWrite (bool)=0
virtual void SetZTestMode (ZTestMode)=0
virtual void SetZBias (float)=0
virtual void ClearZBuffer ()=0
virtual void SetCullMode (CullMode mode)=0
virtual void SetAlphaTest (bool b)=0
virtual void SetMaterial (const RageColor &emissive, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, float shininess)=0
virtual void SetLighting (bool b)=0
virtual void SetLightOff (int index)=0
virtual void SetLightDirectional (int index, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, const RageVector3 &dir)=0
virtual void SetSphereEnvironmentMapping (TextureUnit tu, bool b)=0
virtual void SetCelShaded (int stage)=0
virtual RageCompiledGeometry * CreateCompiledGeometry ()=0
virtual void DeleteCompiledGeometry (RageCompiledGeometry *p)=0
void DrawQuads (const RageSpriteVertex v[], int iNumVerts)
void DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawFan (const RageSpriteVertex v[], int iNumVerts)
void DrawStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
void DrawCompiledGeometry (const RageCompiledGeometry *p, int iMeshIndex, const vector< msMesh > &vMeshes)
void DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawCircle (const RageSpriteVertex &v, float radius)
void DrawQuad (const RageSpriteVertex v[])
virtual void SetPolygonMode (PolygonMode)
virtual void SetLineWidth (float)
bool SaveScreenshot (const RString &sPath, GraphicsFileFormat format)
virtual RString GetTextureDiagnostics (unsigned) const
virtual RageSurface * CreateScreenshot ()=0
virtual RageSurface * GetTexture (unsigned)
bool IsPredictiveFrameLimit () const
int GetFPS () const
int GetVPF () const
int GetCumFPS () const
virtual void ResetStats ()
virtual void ProcessStatsOnFlip ()
virtual RString GetStats () const
void StatsAddVerts (int iNumVertsRendered)
void PushMatrix ()
void PopMatrix ()
void Translate (float x, float y, float z)
void TranslateWorld (float x, float y, float z)
void Scale (float x, float y, float z)
void RotateX (float deg)
void RotateY (float deg)
void RotateZ (float deg)
void SkewX (float fAmount)
void SkewY (float fAmount)
void MultMatrix (const RageMatrix &f)
void PostMultMatrix (const RageMatrix &f)
void PreMultMatrix (const RageMatrix &f)
void LoadIdentity ()
void TexturePushMatrix ()
void TexturePopMatrix ()
void TextureTranslate (float x, float y)
void TextureTranslate (const RageVector2 &v)
void CameraPushMatrix ()
void CameraPopMatrix ()
void LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
void LoadLookAt (float fov, const RageVector3 &Eye, const RageVector3 &At, const RageVector3 &Up)
void CenteringPushMatrix ()
void CenteringPopMatrix ()
void ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
RageSurface * CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void *pixels, int width, int height, int pitch)
RagePixelFormat FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime=false)
void PushSelf (lua_State *L)
Protected Member Functions
virtual void DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawFanInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawStripInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawCompiledGeometryInternal (const RageCompiledGeometry *p, int iMeshIndex)=0
virtual void DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
virtual void DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts)=0
virtual void DrawCircleInternal (const RageSpriteVertex &v, float radius)
virtual bool IsD3DInternal ()
virtual RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut)=0
void DrawPolyLine (const RageSpriteVertex &p1, const RageSpriteVertex &p2, float LineWidth)
void DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void SetDefaultRenderStates ()
RageMatrix GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar)
virtual RageMatrix GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf)
virtual RageMatrix GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf)
RageMatrix GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight)
void UpdateCentering ()
const RageMatrix * GetCentering () const
const RageMatrix * GetProjectionTop () const
const RageMatrix * GetViewTop () const
const RageMatrix * GetWorldTop () const
const RageMatrix * GetTextureTop () const
void FrameLimitBeforeVsync ()
void FrameLimitAfterVsync (int iFPS)
Friends
class RageTexture
Member Enumeration Documentation
GraphicsFileFormat
enum RageDisplay::GraphicsFileFormat
Enumerator
SAVE_LOSSLESS
SAVE_LOSSLESS_SENSIBLE
SAVE_LOSSY_LOW_QUAL
SAVE_LOSSY_HIGH_QUAL
Constructor & Destructor Documentation
RageDisplay()
RageDisplay::RageDisplay ()
References LuaManager::Get(), L, LUA, PushSelf(), RageMatrixIdentity(), and LuaManager::Release().
~RageDisplay()
RageDisplay::~RageDisplay () virtual
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
BeginConcurrentRendering()
void RageDisplay::BeginConcurrentRendering () virtual
Reimplemented in RageDisplay_Legacy.
References SetDefaultRenderStates().
Referenced by RageDisplay_Legacy::BeginConcurrentRendering(), and ConcurrentRenderer::RenderThread().
BeginConcurrentRenderingMainThread()
virtual void RageDisplay::BeginConcurrentRenderingMainThread () inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by ConcurrentRenderer::Start().
BeginFrame()
bool RageDisplay::BeginFrame () virtual
Reimplemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
References SetDefaultRenderStates().
Referenced by RageDisplay_GLES2::BeginFrame(), RageDisplay_D3D::BeginFrame(), RageDisplay_Legacy::BeginFrame(), and ScreenManager::Draw().
CameraPopMatrix()
void RageDisplay::CameraPopMatrix ()
References MatrixStack::Pop().
Referenced by ScreenManager::Draw(), DancingCharacters::DrawPrimitives(), ActorFrame::EndDraw(), RageTextureRenderTarget::FinishRenderingTo(), Player::PopPlayerMatrix(), RageDisplay_D3D::SetRenderTarget(), and RageDisplay_Legacy::SetRenderTarget().
CameraPushMatrix()
void RageDisplay::CameraPushMatrix ()
References MatrixStack::Push().
Referenced by ActorFrame::BeginDraw(), RageTextureRenderTarget::BeginRenderingTo(), ScreenManager::Draw(), DancingCharacters::DrawPrimitives(), Player::PushPlayerMatrix(), RageDisplay_D3D::SetRenderTarget(), and RageDisplay_Legacy::SetRenderTarget().
CenteringPopMatrix()
void RageDisplay::CenteringPopMatrix ()
References ASSERT, g_CenteringStack(), and UpdateCentering().
Referenced by RageTextureRenderTarget::FinishRenderingTo().
CenteringPushMatrix()
void RageDisplay::CenteringPushMatrix ()
References ASSERT, and g_CenteringStack().
Referenced by RageTextureRenderTarget::BeginRenderingTo().
ChangeCentering()
void RageDisplay::ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
References g_CenteringStack(), and UpdateCentering().
Referenced by RageTextureRenderTarget::BeginRenderingTo(), ScreenDebugOverlay::Update(), and update_centering().
ClearAllTextures()
virtual void RageDisplay::ClearAllTextures () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
ClearZBuffer()
virtual void RageDisplay::ClearZBuffer () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteField::DrawPrimitives(), BeginnerHelper::DrawPrimitives(), BackgroundImpl::DrawPrimitives(), NoteDisplay::DrawTapsInRange(), and Actor::SetGlobalRenderStates().
CreateCompiledGeometry()
virtual RageCompiledGeometry* RageDisplay::CreateCompiledGeometry () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::LoadPieces(), and RageModelGeometry::RageModelGeometry().
CreateRenderTarget()
virtual unsigned RageDisplay::CreateRenderTarget (const RenderTargetParam & , int & , int &) inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_D3D.
Referenced by RageTextureRenderTarget::Create().
CreateScreenshot()
virtual RageSurface* RageDisplay::CreateScreenshot () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageTextureManager::GetScreenSurface(), and SaveScreenshot().
CreateSurfaceFromPixfmt()
RageSurface * RageDisplay::CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void * pixels, int width, int height, int pitch)
References RageDisplay::RagePixelFormatDesc::bpp, CreateSurfaceFrom(), GetPixelFormatDesc(), and RageDisplay::RagePixelFormatDesc::masks.
Referenced by RageDisplay_D3D::CreateScreenshot(), and RageDisplay_D3D::UpdateTexture().
CreateTexture()
virtual unsigned RageDisplay::CreateTexture (RagePixelFormat pixfmt, RageSurface * img, bool bGenerateMipMaps) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageBitmapTexture::Create(), ImageTexture::Create(), MovieTexture_DShow::CreateTexture(), MovieTexture_Generic::CreateTexture(), RageMovieTexture_Generic_Intermediate::CreateTexture(), and MovieTexture_Null::MovieTexture_Null().
CreateTextureLock()
virtual RageTextureLock* RageDisplay::CreateTextureLock () inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by MovieTexture_Generic::CreateTexture().
DeleteCompiledGeometry()
virtual void RageDisplay::DeleteCompiledGeometry (RageCompiledGeometry * p) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::Clear(), and RageModelGeometry::~RageModelGeometry().
DeleteTexture()
virtual void RageDisplay::DeleteTexture (unsigned iTexHandle) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageBitmapTexture::Destroy(), RageTextureRenderTarget::Destroy(), ImageTexture::Destroy(), MovieTexture_Generic::DestroyTexture(), MovieTexture_DShow::~MovieTexture_DShow(), MovieTexture_Null::~MovieTexture_Null(), and RageMovieTexture_Generic_Intermediate::~RageMovieTexture_Generic_Intermediate().
DrawCircle()
void RageDisplay::DrawCircle (const RageSpriteVertex & v, float radius)
References DrawCircleInternal().
Referenced by DrawLineStripInternal().
DrawCircleInternal()
void RageDisplay::DrawCircleInternal (const RageSpriteVertex & v, float radius) protected virtual
References DrawFan(), RageSpriteVertex::p, PI, RageFastCos(), RageFastSin(), RageVector3::x, and RageVector3::y.
Referenced by DrawCircle().
DrawCompiledGeometry()
void RageDisplay::DrawCompiledGeometry (const RageCompiledGeometry * p, int iMeshIndex, const vector< msMesh > & vMeshes)
References DrawCompiledGeometryInternal(), and StatsAddVerts().
Referenced by Model::DrawMesh().
DrawCompiledGeometryInternal()
virtual void RageDisplay::DrawCompiledGeometryInternal (const RageCompiledGeometry * p, int iMeshIndex) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawCompiledGeometry().
DrawFan()
void RageDisplay::DrawFan (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawFanInternal(), and StatsAddVerts().
Referenced by DrawCircleInternal(), ActorMultiVertex::DrawInternal(), GraphLine::DrawPrimitives(), and GrooveRadar::GrooveRadarValueMap::DrawPrimitives().
DrawFanInternal()
virtual void RageDisplay::DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawFan().
DrawLineStrip()
void RageDisplay::DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
References ASSERT, and DrawLineStripInternal().
Referenced by ActorMultiVertex::DrawInternal(), and GrooveRadar::GrooveRadarValueMap::DrawPrimitives().
DrawLineStripInternal()
void RageDisplay::DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth) protected virtual
Reimplemented in RageDisplay_Legacy, RageDisplay_Null, and RageDisplay_GLES2.
References ASSERT, DrawCircle(), DrawPolyLines(), PrefsManager::m_bSmoothLines, and PREFSMAN.
Referenced by DrawLineStrip(), and RageDisplay_Legacy::DrawLineStripInternal().
DrawPolyLine()
void RageDisplay::DrawPolyLine (const RageSpriteVertex & p1, const RageSpriteVertex & p2, float LineWidth) protected
References DrawQuad(), f, RageSpriteVertex::p, RageVector3::x, and RageVector3::y.
DrawPolyLines()
void RageDisplay::DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth) protected
References DrawQuads(), f, RageSpriteVertex::p, RageVector3::x, and RageVector3::y.
Referenced by DrawLineStripInternal().
DrawQuad()
void RageDisplay::DrawQuad (const RageSpriteVertex v[]) inline
References DrawQuads().
Referenced by DrawPolyLine(), ActorMultiTexture::DrawPrimitives(), and Sprite::DrawTexture().
DrawQuads()
void RageDisplay::DrawQuads (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawQuadsInternal(), and StatsAddVerts().
Referenced by BitmapText::DrawChars(), ActorMultiVertex::DrawInternal(), DrawPolyLines(), GraphLine::DrawPrimitives(), and DrawQuad().
DrawQuadsInternal()
virtual void RageDisplay::DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawQuads().
DrawQuadStrip()
void RageDisplay::DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawQuadStripInternal(), and StatsAddVerts().
Referenced by ActorMultiVertex::DrawInternal(), and GraphBody::DrawPrimitives().
DrawQuadStripInternal()
virtual void RageDisplay::DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawQuadStrip().
DrawStrip()
void RageDisplay::DrawStrip (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawStripInternal(), and StatsAddVerts().
Referenced by ActorMultiVertex::DrawInternal().
DrawStripInternal()
virtual void RageDisplay::DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawStrip().
DrawSymmetricQuadStrip()
void RageDisplay::DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawSymmetricQuadStripInternal(), and StatsAddVerts().
Referenced by StripBuffer::Draw(), and ActorMultiVertex::DrawInternal().
DrawSymmetricQuadStripInternal()
virtual void RageDisplay::DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawSymmetricQuadStrip().
DrawTriangles()
void RageDisplay::DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
References ASSERT, DrawTrianglesInternal(), and StatsAddVerts().
Referenced by ActorMultiVertex::DrawInternal().
DrawTrianglesInternal()
virtual void RageDisplay::DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by DrawTriangles().
EndConcurrentRendering()
virtual void RageDisplay::EndConcurrentRendering () inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by ConcurrentRenderer::RenderThread().
EndConcurrentRenderingMainThread()
virtual void RageDisplay::EndConcurrentRenderingMainThread () inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by ConcurrentRenderer::Stop().
EndFrame()
void RageDisplay::EndFrame () virtual
Reimplemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
References ProcessStatsOnFlip().
Referenced by ScreenManager::Draw(), RageDisplay_GLES2::EndFrame(), RageDisplay_D3D::EndFrame(), and RageDisplay_Legacy::EndFrame().
FindPixelFormat()
RagePixelFormat RageDisplay::FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime = false)
References FOREACH_ENUM, GetPixelFormatDesc(), RagePixelFormat_Invalid, and SupportsTextureFormat().
Referenced by MovieTexture_Generic::CreateTexture(), and FindCompatibleAVFormat().
FrameLimitAfterVsync()
void RageDisplay::FrameLimitAfterVsync (int iFPS) protected
References g_fFrameLimit, g_fFrameLimitGameplay, g_fFrameLimitPercent, g_fPredictiveFrameLimit, g_FrameRenderTime, g_LastFrameEndedAt, g_LastFrameEndedAtRage, g_LastFramePresentTime, g_LastFrameRenderTime, gameplay, Preference< T >::Get(), Screen::GetScreenType(), ScreenManager::GetTopScreen(), PrefsManager::m_bVsync, PREFSMAN, SCREENMAN, and RageTimer::Touch().
Referenced by RageDisplay_GLES2::EndFrame(), and RageDisplay_D3D::EndFrame().
FrameLimitBeforeVsync()
void RageDisplay::FrameLimitBeforeVsync () protected
References ArchHooks::AppHasFocus(), g_fFrameLimit, g_fFrameLimitGameplay, g_fPredictiveFrameLimit, g_FrameRenderTime, g_LastFrameEndedAtRage, g_LastFrameRenderTime, gameplay, Preference< T >::Get(), RageTimer::GetDeltaTime(), Screen::GetScreenType(), ScreenManager::GetTopScreen(), HOOKS, RageTimer::IsZero(), and SCREENMAN.
Referenced by RageDisplay_GLES2::EndFrame(), and RageDisplay_D3D::EndFrame().
GetActualVideoModeParams()
virtual const VideoModeParams* RageDisplay::GetActualVideoModeParams () const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
Referenced by CheckGameLoopTimerSkips(), GetActualGraphicOptionsString(), GetCenteringMatrix(), LunaRageDisplay::GetDisplayHeight(), LunaRageDisplay::GetDisplayWidth(), GameSoundManager::GetFrameTimingAdjustment(), IsWindowed(), LoadLookAt(), SaveScreenshot(), and StoreActualGraphicOptions().
GetApiDescription()
virtual RString RageDisplay::GetApiDescription () const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
Referenced by GetActualGraphicOptionsString(), and GetStats().
GetCentering()
const RageMatrix * RageDisplay::GetCentering () const protected
References g_CenteringMatrix.
Referenced by RageDisplay_D3D::SendCurrentMatrices().
GetCenteringMatrix()
RageMatrix RageDisplay::GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight) protected
References f, GetActualVideoModeParams(), RageMatrixMultiply(), RageMatrixScaling(), RageMatrixTranslation(), and SCALE.
Referenced by RageDisplay_D3D::SendCurrentMatrices(), and UpdateCentering().
GetCumFPS()
int RageDisplay::GetCumFPS () const
References g_iCFPS.
Referenced by LunaRageDisplay::GetCumFPS(), and GetStats().
GetDisplayResolutions()
virtual void RageDisplay::GetDisplayResolutions (DisplayResolutions & out) const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
Referenced by cache_display_resolution_list(), and SetVideoMode().
GetFPS()
int RageDisplay::GetFPS () const
References g_iFPS.
Referenced by CheckGameLoopTimerSkips(), LunaRageDisplay::GetFPS(), GameSoundManager::GetFrameTimingAdjustment(), GetStats(), and ScreenStatsOverlay::UpdateSkips().
GetFrustumMatrix()
RageMatrix RageDisplay::GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf) protected virtual
Referenced by GetPerspectiveMatrix(), and LoadMenuPerspective().
GetMaxTextureSize()
virtual int RageDisplay::GetMaxTextureSize () const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageBitmapTexture::Create(), MovieTexture_DShow::Create(), and ImageTexture::Create().
GetNumTextureUnits()
virtual int RageDisplay::GetNumTextureUnits () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawPrimitives().
GetOrthoMatrix()
RageMatrix RageDisplay::GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) protected virtual
Reimplemented in RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageDisplay_D3D::GetOrthoMatrix(), and LoadMenuPerspective().
GetPerspectiveMatrix()
RageMatrix RageDisplay::GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar) protected
References f, GetFrustumMatrix(), and PI.
Referenced by LoadLookAt().
GetPixelFormatDesc()
virtual const RagePixelFormatDesc* RageDisplay::GetPixelFormatDesc (RagePixelFormat pf) const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
Referenced by RageBitmapTexture::Create(), CreateSurfaceFromPixfmt(), MovieTexture_DShow::CreateTexture(), FindPixelFormat(), RageDisplay_Legacy::GetImgPixelFormat(), and MovieTexture_Null::MovieTexture_Null().
GetProjectionTop()
const RageMatrix * RageDisplay::GetProjectionTop () const protected
References MatrixStack::GetTop().
Referenced by RageDisplay_D3D::SendCurrentMatrices().
GetRenderTarget()
virtual unsigned RageDisplay::GetRenderTarget () inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_D3D.
Referenced by RageTextureRenderTarget::BeginRenderingTo().
GetStats()
RString RageDisplay::GetStats () const virtual
References GetApiDescription(), GetCumFPS(), GetFPS(), GetVPF(), and ssprintf().
Referenced by ProcessStatsOnFlip(), and ScreenStatsOverlay::Update().
GetTexture()
virtual RageSurface* RageDisplay::GetTexture (unsigned) inline virtual
Reimplemented in RageDisplay_Legacy.
GetTextureDiagnostics()
virtual RString RageDisplay::GetTextureDiagnostics (unsigned) const inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by RageTextureManager::DiagnosticOutput().
GetTextureTop()
const RageMatrix * RageDisplay::GetTextureTop () const protected
References MatrixStack::GetTop().
Referenced by RageDisplay_D3D::SendCurrentMatrices().
GetViewTop()
const RageMatrix * RageDisplay::GetViewTop () const protected
References MatrixStack::GetTop().
Referenced by RageDisplay_D3D::SendCurrentMatrices().
GetVPF()
int RageDisplay::GetVPF () const
References g_iVPF.
Referenced by GetStats(), and LunaRageDisplay::GetVPF().
GetWorldTop()
const RageMatrix * RageDisplay::GetWorldTop () const protected
References MatrixStack::GetTop().
Referenced by RageDisplay_D3D::SendCurrentMatrices().
Init()
virtual RString RageDisplay::Init (const VideoModeParams & p, bool bAllowUnacceleratedRenderer) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_D3D, RageDisplay_GLES2, and RageDisplay_Null.
Referenced by CreateDisplay().
IsD3D()
bool RageDisplay::IsD3D ()
References IsD3DInternal().
IsD3DInternal()
bool RageDisplay::IsD3DInternal () protected virtual
Reimplemented in RageDisplay_Legacy, RageDisplay_Null, and RageDisplay_D3D.
Referenced by IsD3D().
IsEffectModeSupported()
virtual bool RageDisplay::IsEffectModeSupported (EffectMode effect) inline virtual
Reimplemented in RageDisplay_Legacy.
References EffectMode_Normal.
Referenced by FindCompatibleAVFormat().
IsPredictiveFrameLimit()
bool RageDisplay::IsPredictiveFrameLimit () const
References g_fPredictiveFrameLimit.
Referenced by ScreenStatsOverlay::UpdateSkips().
IsWindowed()
bool RageDisplay::IsWindowed () inline
References GetActualVideoModeParams().
IsZTestEnabled()
virtual bool RageDisplay::IsZTestEnabled () const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
IsZWriteEnabled()
virtual bool RageDisplay::IsZWriteEnabled () const pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
LoadIdentity()
void RageDisplay::LoadIdentity ()
References MatrixStack::LoadIdentity().
Referenced by RageTextureRenderTarget::BeginRenderingTo().
LoadLookAt()
void RageDisplay::LoadLookAt (float fov, const RageVector3 & Eye, const RageVector3 & At, const RageVector3 & Up)
References GetActualVideoModeParams(), GetPerspectiveMatrix(), MatrixStack::LoadMatrix(), RageLookAt(), MatrixStack::Scale(), RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by DancingCharacters::DrawPrimitives().
LoadMenuPerspective()
void RageDisplay::LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
References CLAMP(), f, GetFrustumMatrix(), GetOrthoMatrix(), NoteDataUtil::left, MatrixStack::LoadIdentity(), MatrixStack::LoadMatrix(), PI, RageLookAt(), NoteDataUtil::right, and SCALE.
Referenced by ActorFrame::BeginDraw(), RageTextureRenderTarget::BeginRenderingTo(), ScreenManager::Draw(), Player::PushPlayerMatrix(), and SetDefaultRenderStates().
MultMatrix()
void RageDisplay::MultMatrix (const RageMatrix & f) inline
References PostMultMatrix().
Referenced by Actor::BeginDraw().
PopMatrix()
void RageDisplay::PopMatrix ()
References MatrixStack::Pop().
Referenced by Model::DrawMesh(), BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), Sprite::DrawTexture(), Actor::EndDraw(), RageTextureRenderTarget::FinishRenderingTo(), and Player::PopPlayerMatrix().
PostMultMatrix()
void RageDisplay::PostMultMatrix (const RageMatrix & f)
References MatrixStack::MultMatrix().
Referenced by MultMatrix().
PreMultMatrix()
void RageDisplay::PreMultMatrix (const RageMatrix & f)
References MatrixStack::MultMatrixLocal().
Referenced by Actor::BeginDraw(), and Model::DrawMesh().
ProcessStatsOnFlip()
void RageDisplay::ProcessStatsOnFlip () virtual
References g_iCFPS, g_iFPS, g_iFramesRenderedSinceLastCheck, g_iFramesRenderedSinceLastReset, g_iNumChecksSinceLastReset, g_iVertsRenderedSinceLastCheck, g_iVPF, g_LastCheckTimer, GetStats(), LOG, LOG_FPS, PrefsManager::m_bShowStats, PREFSMAN, StdString::CStdStr< CT >::Replace(), and RageLog::Trace().
Referenced by RageDisplay_Null::EndFrame(), and EndFrame().
PushMatrix()
void RageDisplay::PushMatrix ()
References MatrixStack::Push().
Referenced by Actor::BeginDraw(), RageTextureRenderTarget::BeginRenderingTo(), Model::DrawMesh(), BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), Sprite::DrawTexture(), and Player::PushPlayerMatrix().
PushSelf()
void RageDisplay::PushSelf (lua_State * L)
Referenced by RageDisplay().
ResetStats()
void RageDisplay::ResetStats () virtual
References g_iFPS, g_iFramesRenderedSinceLastCheck, g_iFramesRenderedSinceLastReset, g_iNumChecksSinceLastReset, g_iVertsRenderedSinceLastCheck, g_iVPF, g_LastCheckTimer, LOG_FPS, PrefsManager::m_bShowStats, and PREFSMAN.
Referenced by ScreenManager::ZeroNextUpdate().
ResolutionChanged()
void RageDisplay::ResolutionChanged () virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_D3D.
References UpdateCentering().
Referenced by RageDisplay_D3D::ResolutionChanged(), RageDisplay_Legacy::ResolutionChanged(), RageDisplay_GLES2::TryVideoMode(), and LowLevelWindow_MacOSX::Update().
RotateX()
void RageDisplay::RotateX (float deg)
References MatrixStack::RotateXLocal().
RotateY()
void RageDisplay::RotateY (float deg)
References MatrixStack::RotateYLocal().
RotateZ()
void RageDisplay::RotateZ (float deg)
References MatrixStack::RotateZLocal().
SaveScreenshot()
bool RageDisplay::SaveScreenshot (const RString & sPath, GraphicsFileFormat format)
References ASSERT, CreateScreenshot(), DEFAULT_FAIL, GetActualVideoModeParams(), RageFile::GetError(), LOG, RageFile::Open(), SAFE_DELETE, SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_HIGH_QUAL, SAVE_LOSSY_LOW_QUAL, RageSurfaceUtils::SaveBMP(), RageSurfaceUtils::SaveJPEG(), RageSurfaceUtils::SavePNG(), RageTimer::Touch(), RageLog::Trace(), RageFile::WRITE, and RageSurfaceUtils::Zoom().
Referenced by StepMania::SaveScreenshot().
Scale()
void RageDisplay::Scale (float x, float y, float z)
References MatrixStack::ScaleLocal().
Referenced by Model::DrawPrimitives().
SetAlphaTest()
virtual void RageDisplay::SetAlphaTest (bool b) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by SetDefaultRenderStates().
SetBlendMode()
virtual void RageDisplay::SetBlendMode (BlendMode mode) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteDisplay::DrawHoldPart(), Model::DrawPrimitives(), SetDefaultRenderStates(), and Actor::SetGlobalRenderStates().
SetCelShaded()
virtual void RageDisplay::SetCelShaded (int stage) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawCelShaded().
SetCullMode()
virtual void RageDisplay::SetCullMode (CullMode mode) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawCelShaded(), NoteDisplay::DrawHoldPart(), SetDefaultRenderStates(), and Actor::SetGlobalRenderStates().
SetDefaultRenderStates()
void RageDisplay::SetDefaultRenderStates () protected
References BLEND_NORMAL, CULL_NONE, LoadMenuPerspective(), SetAlphaTest(), SetBlendMode(), SetCullMode(), SetLighting(), SetTextureFiltering(), SetZBias(), SetZTestMode(), SetZWrite(), TextureUnit_1, and ZTEST_OFF.
Referenced by BeginConcurrentRendering(), BeginFrame(), and RageDisplay_D3D::SetRenderTarget().
SetEffectMode()
virtual void RageDisplay::SetEffectMode (EffectMode) inline virtual
Reimplemented in RageDisplay_Legacy.
Referenced by ActorMultiVertex::DrawInternal(), ActorMultiTexture::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), and Sprite::DrawTexture().
SetLightDirectional()
virtual void RageDisplay::SetLightDirectional (int index, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, const RageVector3 & dir) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by ActorFrame::BeginDraw(), BeginnerHelper::DrawPrimitives(), and DancingCharacters::DrawPrimitives().
SetLighting()
virtual void RageDisplay::SetLighting (bool b) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by ActorFrame::BeginDraw(), BeginnerHelper::DrawPrimitives(), DancingCharacters::DrawPrimitives(), ActorFrame::EndDraw(), and SetDefaultRenderStates().
SetLightOff()
virtual void RageDisplay::SetLightOff (int index) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by BeginnerHelper::DrawPrimitives(), DancingCharacters::DrawPrimitives(), and ActorFrame::EndDraw().
SetLineWidth()
virtual void RageDisplay::SetLineWidth (float) inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_GLES2.
SetMaterial()
virtual void RageDisplay::SetMaterial (const RageColor & emissive, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, float shininess) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawPrimitives().
SetPolygonMode()
virtual void RageDisplay::SetPolygonMode (PolygonMode) inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_GLES2.
SetPresentTime()
void RageDisplay::SetPresentTime (std::chrono::nanoseconds presentTime)
References g_LastFramePresentTime.
Referenced by RageDisplay_D3D::EndFrame().
SetRenderTarget()
virtual void RageDisplay::SetRenderTarget (unsigned , bool = true) inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_D3D.
Referenced by RageTextureRenderTarget::BeginRenderingTo(), and RageTextureRenderTarget::FinishRenderingTo().
SetSphereEnvironmentMapping()
virtual void RageDisplay::SetSphereEnvironmentMapping (TextureUnit tu, bool b) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawPrimitives().
SetTexture()
virtual void RageDisplay::SetTexture (TextureUnit , unsigned) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by BitmapText::DrawChars(), NoteDisplay::DrawHoldPart(), ActorMultiTexture::DrawPrimitives(), Model::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), GraphBody::DrawPrimitives(), and Sprite::DrawTexture().
SetTextureFiltering()
virtual void RageDisplay::SetTextureFiltering (TextureUnit , bool) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by Model::DrawPrimitives(), SetDefaultRenderStates(), and Actor::SetTextureRenderStates().
SetTextureMode()
virtual void RageDisplay::SetTextureMode (TextureUnit , TextureMode) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteDisplay::DrawHoldBody(), ActorMultiTexture::DrawPrimitives(), Model::DrawPrimitives(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), BitmapText::DrawPrimitives(), GraphBody::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), and Sprite::DrawTexture().
SetTextureWrapping()
virtual void RageDisplay::SetTextureWrapping (TextureUnit , bool) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteDisplay::DrawHoldPart(), ActorMultiTexture::DrawPrimitives(), and Actor::SetTextureRenderStates().
SetVideoMode()
RString RageDisplay::SetVideoMode (VideoModeParams p, bool & bNeedReloadTextures)
References VideoModeParams::bpp, GetDisplayResolutions(), LocalizedString::GetValue(), VideoModeParams::height, DisplayResolution::iHeight, DisplayResolution::iWidth, Rage::join(), LOG, SETVIDEOMODE_FAILED, RageLog::Trace(), TryVideoMode(), and VideoModeParams::width.
Referenced by StepMania::ApplyGraphicOptions(), RageDisplay_Null::Init(), RageDisplay_D3D::Init(), and RageDisplay_GLES2::Init().
SetZBias()
virtual void RageDisplay::SetZBias (float) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by SetDefaultRenderStates(), and Actor::SetGlobalRenderStates().
SetZTestMode()
virtual void RageDisplay::SetZTestMode (ZTestMode) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteDisplay::DrawHoldBody(), SetDefaultRenderStates(), and Actor::SetGlobalRenderStates().
SetZWrite()
virtual void RageDisplay::SetZWrite (bool) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by NoteDisplay::DrawHoldBody(), SetDefaultRenderStates(), and Actor::SetGlobalRenderStates().
SkewX()
void RageDisplay::SkewX (float fAmount)
References MatrixStack::SkewX().
Referenced by Actor::BeginDraw().
SkewY()
void RageDisplay::SkewY (float fAmount)
References MatrixStack::SkewY().
Referenced by Actor::BeginDraw().
StatsAddVerts()
void RageDisplay::StatsAddVerts (int iNumVertsRendered)
References g_iVertsRenderedSinceLastCheck.
Referenced by DrawCompiledGeometry(), DrawFan(), DrawQuads(), DrawQuadStrip(), DrawStrip(), DrawSymmetricQuadStrip(), and DrawTriangles().
SupportsPerVertexMatrixScale()
virtual bool RageDisplay::SupportsPerVertexMatrixScale () pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageModelGeometry::LoadMilkshapeAscii().
SupportsRenderToTexture()
bool RageDisplay::SupportsRenderToTexture () const inline
SupportsTextureFormat()
virtual bool RageDisplay::SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime = false) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by RageBitmapTexture::Create(), ImageTexture::Create(), MovieTexture_DShow::CreateTexture(), MovieTexture_Generic::CreateTexture(), FindPixelFormat(), and MovieTexture_Null::MovieTexture_Null().
SupportsThreadedRendering()
virtual bool RageDisplay::SupportsThreadedRendering () inline virtual
Reimplemented in RageDisplay_Legacy, and RageDisplay_D3D.
TexturePopMatrix()
void RageDisplay::TexturePopMatrix ()
References MatrixStack::Pop().
Referenced by NoteDisplay::DrawActor(), Model::DrawPrimitives(), and Actor::EndDraw().
TexturePushMatrix()
void RageDisplay::TexturePushMatrix ()
References MatrixStack::Push().
Referenced by Actor::BeginDraw(), NoteDisplay::DrawActor(), and Model::DrawPrimitives().
TextureTranslate() [1/2]
void RageDisplay::TextureTranslate (float x, float y)
References MatrixStack::TranslateLocal().
Referenced by Actor::BeginDraw(), NoteDisplay::DrawActor(), Model::DrawPrimitives(), and TextureTranslate().
TextureTranslate() [2/2]
void RageDisplay::TextureTranslate (const RageVector2 & v) inline
References TextureTranslate(), RageVector2::x, and RageVector2::y.
Translate()
void RageDisplay::Translate (float x, float y, float z)
References MatrixStack::TranslateLocal().
TranslateWorld()
void RageDisplay::TranslateWorld (float x, float y, float z)
References MatrixStack::Translate().
Referenced by BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), and Sprite::DrawTexture().
TryVideoMode()
virtual RString RageDisplay::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) protected pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by SetVideoMode().
UpdateCentering()
void RageDisplay::UpdateCentering () protected
References g_CenteringStack(), GetCenteringMatrix(), Centering::m_iAddHeight, Centering::m_iAddWidth, Centering::m_iTranslateX, and Centering::m_iTranslateY.
Referenced by CenteringPopMatrix(), ChangeCentering(), and ResolutionChanged().
UpdateTexture()
virtual void RageDisplay::UpdateTexture (unsigned iTexHandle, RageSurface * img, int xoffset, int yoffset, int width, int height) pure virtual
Implemented in RageDisplay_Legacy, RageDisplay_Null, RageDisplay_D3D, and RageDisplay_GLES2.
Referenced by MovieTexture_DShow::CheckFrame(), RageTextureLock_OGL::Unlock(), and MovieTexture_Generic::UpdateFrame().
Friends And Related Function Documentation
RageTexture
friend class RageTexture friend
The documentation for this class was generated from the following files:
RageDisplay.h
RageDisplay.cpp