Etterna: ScreenDimensions Namespace Reference
ScreenDimensions Namespace Reference
ScreenDimensions - defines for screen resolutions.
Functions
float GetThemeAspectRatio ()
float GetScreenWidth ()
float GetScreenHeight ()
void ReloadScreenDimensions ()
Detailed Description
ScreenDimensions - defines for screen resolutions.
Function Documentation
GetScreenHeight()
float ScreenDimensions::GetScreenHeight ()
References ASSERT, PrefsManager::m_fDisplayAspectRatio, PREFSMAN, THEME_NATIVE_ASPECT, and THEME_SCREEN_HEIGHT.
GetScreenWidth()
float ScreenDimensions::GetScreenWidth ()
References ASSERT, PrefsManager::m_fDisplayAspectRatio, PREFSMAN, THEME_NATIVE_ASPECT, and THEME_SCREEN_WIDTH.
GetThemeAspectRatio()
float ScreenDimensions::GetThemeAspectRatio ()
References THEME_NATIVE_ASPECT.
ReloadScreenDimensions()
void ScreenDimensions::ReloadScreenDimensions ()
References ASPECT_SCALE_FACTOR, LUA, ThemeMetric< T >::Read(), SCREEN_BOTTOM, SCREEN_CENTER_X, SCREEN_CENTER_Y, SCREEN_HEIGHT, SCREEN_LEFT, SCREEN_RIGHT, SCREEN_TOP, SCREEN_WIDTH, LuaManager::SetGlobal(), THEME_SCREEN_HEIGHT, and THEME_SCREEN_WIDTH.
Referenced by ThemeManager::UpdateLuaGlobals().