Etterna: CryptManager.cpp File Reference
CryptManager.cpp File Reference
#include "CryptManager.h"
#include "CryptHelpers.h"
#include "LuaBinding.h"
#include "LuaManager.h"
#include "RageFile.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "global.h"
#include "libtomcrypt/src/headers/tomcrypt.h"
Classes
class LunaCryptManager
Allow Lua to have access to the CryptManager.
Macros
#define MAX_SIGNATURE_SIZE_BYTES 1024
Functions
static bool HashFile (RageFileBasic &f, unsigned char buf_hash[20], int iHash)
static bool WriteFile (const RString &sFile, const RString &sBuf)
Variables
CryptManager * CRYPTMAN
static const RString PRIVATE_KEY_PATH = "Data/private.rsa"
static const RString PUBLIC_KEY_PATH = "Data/public.rsa"
static const RString ALTERNATE_PUBLIC_KEY_DIR = "Data/keys/"
static const int KEY_LENGTH = 1024
static PRNGWrapper * g_pPRNG = NULL
Macro Definition Documentation
MAX_SIGNATURE_SIZE_BYTES
#define MAX_SIGNATURE_SIZE_BYTES 1024
Referenced by CryptManager::VerifyFileWithFile().
Function Documentation
HashFile()
static bool HashFile (RageFileBasic & f, unsigned char buf_hash[20], int iHash) static
References ASSERT_M, RageFileBasic::AtEOF(), RageFileBasic::GetDisplayPath(), RageFileBasic::GetError(), LOG, RageFileBasic::Read(), and RageLog::Warn().
Referenced by CryptManager::GetMD5ForFile(), CryptManager::GetSHA1ForFile(), CryptManager::Sign(), and CryptManager::Verify().
WriteFile()
static bool WriteFile (const RString & sFile, const RString & sBuf) static
References RageFile::Close(), FILEMAN, RageFile::Flush(), RageFile::GetError(), LOG, RageFile::Open(), RageFileManager::Remove(), RageLog::Warn(), RageFile::WRITE, and RageFile::Write().
Referenced by CryptManager::GenerateRSAKeyToFile(), and CryptManager::SignFileToFile().
Variable Documentation
ALTERNATE_PUBLIC_KEY_DIR
const RString ALTERNATE_PUBLIC_KEY_DIR = "Data/keys/" static
CRYPTMAN
CryptManager* CRYPTMAN
Initial value:
=
  NULL
Referenced by LunaProfile::AddScreenshot(), DoInstalls(), Song::GetFileHash(), ScreenEvaluation::Input(), Profile::SaveMachinePublicKeyToDir(), ShutdownGame(), and sm_main().
g_pPRNG
PRNGWrapper* g_pPRNG = NULL static
KEY_LENGTH
const int KEY_LENGTH = 1024 static
PRIVATE_KEY_PATH
const RString PRIVATE_KEY_PATH = "Data/private.rsa" static
Referenced by CryptManager::SignFileToFile().
PUBLIC_KEY_PATH
const RString PUBLIC_KEY_PATH = "Data/public.rsa" static
Referenced by CryptManager::GetPublicKeyFileName().