Etterna: DSoundBuf Class Reference
DSoundBuf Class Reference
#include <DSoundHelpers.h>
Public Types
enum hw { HW_HARDWARE, HW_SOFTWARE, HW_DONT_CARE }
enum { DYNAMIC_SAMPLERATE = -1 }
Public Member Functions
DSoundBuf ()
RString Init (DSound &ds, hw hardware, int iChannels, int iSampleRate, int iSampleBits, int iWriteAhead)
bool get_output_buf (char **pBuffer, unsigned *iBuffersize, int iChunksize)
void release_output_buf (char *pBuffer, unsigned iBuffersize)
void Play ()
void Stop ()
void SetVolume (float fVolume)
void SetSampleRate (int iRate)
int GetSampleRate () const
~DSoundBuf ()
int64_t GetPosition () const
int64_t GetOutputPosition () const
Private Member Functions
int buffersize_frames () const
int bytes_per_frame () const
void CheckWriteahead (int iCursorStart, int iCursorEnd)
void CheckUnderrun (int iCursorStart, int iCursorEnd)
Private Attributes
IDirectSoundBuffer * m_pBuffer
int m_iChannels
int m_iSampleRate
int m_iSampleBits
int m_iWriteAhead
int m_iVolume
int m_iBufferSize
int m_iWriteCursor
int m_iBufferBytesFilled
int m_iExtraWriteahead
int64_t m_iWriteCursorPos
int64_t m_iLastPosition
bool m_bPlaying
bool m_bBufferLocked
char * m_pLockedBuf1
char * m_pLockedBuf2
int m_iLockedSize1
int m_iLockedSize2
char * m_pTempBuffer
int m_iLastCursors [4][2]
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DYNAMIC_SAMPLERATE
hw
enum DSoundBuf::hw
Enumerator
HW_HARDWARE
HW_SOFTWARE
HW_DONT_CARE
Constructor & Destructor Documentation
DSoundBuf()
DSoundBuf::DSoundBuf ()
References m_pBuffer, and m_pTempBuffer.
~DSoundBuf()
DSoundBuf::~DSoundBuf ()
References m_pBuffer, and m_pTempBuffer.
Member Function Documentation
buffersize_frames()
int DSoundBuf::buffersize_frames () const inline private
References bytes_per_frame(), and m_iBufferSize.
Referenced by GetPosition().
bytes_per_frame()
int DSoundBuf::bytes_per_frame () const inline private
References m_iChannels, and m_iSampleBits.
Referenced by buffersize_frames(), CheckWriteahead(), get_output_buf(), GetPosition(), and Init().
CheckUnderrun()
void DSoundBuf::CheckUnderrun (int iCursorStart, int iCursorEnd) private
References contained(), LOG, m_iBufferBytesFilled, m_iBufferSize, m_iExtraWriteahead, m_iLastCursors, m_iWriteAhead, m_iWriteCursor, ssprintf(), RageLog::Trace(), and wrap().
Referenced by get_output_buf().
CheckWriteahead()
void DSoundBuf::CheckWriteahead (int iCursorStart, int iCursorEnd) private
References bytes_per_frame(), LOG, m_iBufferSize, m_iExtraWriteahead, m_iWriteAhead, RageLog::Trace(), RageLog::Warn(), and wrap().
Referenced by get_output_buf().
get_output_buf()
bool DSoundBuf::get_output_buf (char ** pBuffer, unsigned * iBuffersize, int iChunksize)
References ASSERT, bytes_per_frame(), CheckUnderrun(), CheckWriteahead(), LOG, m_bBufferLocked, m_bPlaying, m_iBufferBytesFilled, m_iBufferSize, m_iExtraWriteahead, m_iLastCursors, m_iLockedSize1, m_iLockedSize2, m_iWriteAhead, m_iWriteCursor, m_iWriteCursorPos, m_pBuffer, m_pLockedBuf1, m_pLockedBuf2, m_pTempBuffer, max(), min(), QuantizeUp(), ssprintf(), RageLog::Trace(), RageLog::Warn(), and wrap().
Referenced by RageSoundDriver_DSound_Software::MixerThread().
GetOutputPosition()
int64_t DSoundBuf::GetOutputPosition () const inline
References m_iWriteCursorPos.
Referenced by RageSoundDriver_DSound_Software::MixerThread().
GetPosition()
int64_t DSoundBuf::GetPosition () const
References ASSERT_M, buffersize_frames(), bytes_per_frame(), LOG, m_iBufferSize, m_iLastPosition, m_iWriteCursor, m_iWriteCursorPos, m_pBuffer, max(), ssprintf(), and RageLog::Warn().
Referenced by RageSoundDriver_DSound_Software::GetPosition(), and RageSoundDriver_DSound_Software::MixerThread().
GetSampleRate()
int DSoundBuf::GetSampleRate () const inline
References m_iSampleRate.
Init()
RString DSoundBuf::Init (DSound & ds, DSoundBuf::hw hardware, int iChannels, int iSampleRate, int iSampleBits, int iWriteAhead)
References bytes_per_frame(), DYNAMIC_SAMPLERATE, FAILED, DSound::GetDS(), HW_HARDWARE, LOG, m_bBufferLocked, m_bPlaying, m_iBufferBytesFilled, m_iBufferSize, m_iChannels, m_iExtraWriteahead, m_iLastCursors, m_iLastPosition, m_iSampleBits, m_iSampleRate, m_iVolume, m_iWriteAhead, m_iWriteCursor, m_iWriteCursorPos, m_pBuffer, m_pTempBuffer, max(), min(), RageLog::Warn(), and ZERO.
Referenced by RageSoundDriver_DSound_Software::Init().
Play()
void DSoundBuf::Play ()
References m_bPlaying, and m_pBuffer.
Referenced by RageSoundDriver_DSound_Software::MixerThread().
release_output_buf()
void DSoundBuf::release_output_buf (char * pBuffer, unsigned iBuffersize)
References m_bBufferLocked, m_iLockedSize1, m_iLockedSize2, m_pBuffer, m_pLockedBuf1, and m_pLockedBuf2.
Referenced by RageSoundDriver_DSound_Software::MixerThread().
SetSampleRate()
void DSoundBuf::SetSampleRate (int iRate)
References FAILED, m_iSampleRate, m_pBuffer, and RageException::Throw().
SetVolume()
void DSoundBuf::SetVolume (float fVolume)
References ASSERT_M, FAILED, LOG, m_iVolume, m_pBuffer, max(), ssprintf(), and RageLog::Warn().
Stop()
void DSoundBuf::Stop ()
References m_bPlaying, m_iBufferBytesFilled, m_iExtraWriteahead, m_iLastPosition, m_iWriteAhead, m_iWriteCursor, m_iWriteCursorPos, and m_pBuffer.
Referenced by RageSoundDriver_DSound_Software::MixerThread().
Member Data Documentation
m_bBufferLocked
bool DSoundBuf::m_bBufferLocked private
Referenced by get_output_buf(), Init(), and release_output_buf().
m_bPlaying
bool DSoundBuf::m_bPlaying private
Referenced by get_output_buf(), Init(), Play(), and Stop().
m_iBufferBytesFilled
int DSoundBuf::m_iBufferBytesFilled private
Referenced by CheckUnderrun(), get_output_buf(), Init(), and Stop().
m_iBufferSize
int DSoundBuf::m_iBufferSize private
Referenced by buffersize_frames(), CheckUnderrun(), CheckWriteahead(), get_output_buf(), GetPosition(), and Init().
m_iChannels
int DSoundBuf::m_iChannels private
Referenced by bytes_per_frame(), and Init().
m_iExtraWriteahead
int DSoundBuf::m_iExtraWriteahead private
Referenced by CheckUnderrun(), CheckWriteahead(), get_output_buf(), Init(), and Stop().
m_iLastCursors
int DSoundBuf::m_iLastCursors[4][2] private
Referenced by CheckUnderrun(), get_output_buf(), and Init().
m_iLastPosition
int64_t DSoundBuf::m_iLastPosition mutable private
Referenced by GetPosition(), Init(), and Stop().
m_iLockedSize1
int DSoundBuf::m_iLockedSize1 private
Referenced by get_output_buf(), and release_output_buf().
m_iLockedSize2
int DSoundBuf::m_iLockedSize2 private
Referenced by get_output_buf(), and release_output_buf().
m_iSampleBits
int DSoundBuf::m_iSampleBits private
Referenced by bytes_per_frame(), and Init().
m_iSampleRate
int DSoundBuf::m_iSampleRate private
Referenced by GetSampleRate(), Init(), and SetSampleRate().
m_iVolume
int DSoundBuf::m_iVolume private
Referenced by Init(), and SetVolume().
m_iWriteAhead
int DSoundBuf::m_iWriteAhead private
Referenced by CheckUnderrun(), CheckWriteahead(), get_output_buf(), Init(), and Stop().
m_iWriteCursor
int DSoundBuf::m_iWriteCursor private
Referenced by CheckUnderrun(), get_output_buf(), GetPosition(), Init(), and Stop().
m_iWriteCursorPos
int64_t DSoundBuf::m_iWriteCursorPos private
Referenced by get_output_buf(), GetOutputPosition(), GetPosition(), Init(), and Stop().
m_pBuffer
IDirectSoundBuffer* DSoundBuf::m_pBuffer private
Referenced by DSoundBuf(), get_output_buf(), GetPosition(), Init(), Play(), release_output_buf(), SetSampleRate(), SetVolume(), Stop(), and ~DSoundBuf().
m_pLockedBuf1
char* DSoundBuf::m_pLockedBuf1 private
Referenced by get_output_buf(), and release_output_buf().
m_pLockedBuf2
char * DSoundBuf::m_pLockedBuf2 private
Referenced by get_output_buf(), and release_output_buf().
m_pTempBuffer
char* DSoundBuf::m_pTempBuffer private
Referenced by DSoundBuf(), get_output_buf(), Init(), and ~DSoundBuf().
The documentation for this class was generated from the following files:
DSoundHelpers.h
DSoundHelpers.cpp