Etterna: TapScoreDistribution Struct Reference
TapScoreDistribution Struct Reference
Public Member Functions
void ChangeWeightsToPercents ()
void SetDefaultWeights ()
TapNoteScore GetTapNoteScore ()
Public Attributes
float fPercent [NUM_TapNoteScore]
Member Function Documentation
ChangeWeightsToPercents()
void TapScoreDistribution::ChangeWeightsToPercents () inline
Referenced by PlayerAI::InitFromDisk().
GetTapNoteScore()
TapNoteScore TapScoreDistribution::GetTapNoteScore () inline
References ASSERT_M, randomf(), ssprintf(), and TNS_W1.
Referenced by PlayerAI::GetTapNoteScore().
SetDefaultWeights()
void TapScoreDistribution::SetDefaultWeights () inline
References TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
Referenced by PlayerAI::InitFromDisk().
Member Data Documentation
fPercent
float TapScoreDistribution::fPercent[NUM_TapNoteScore]
Referenced by PlayerAI::InitFromDisk().
The documentation for this struct was generated from the following file:
PlayerAI.cpp