Etterna: RageSoundReader_WAV.cpp File Reference
RageSoundReader_WAV.cpp File Reference
#include "RageSoundReader_WAV.h"
#include "RageFileBasic.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "global.h"
Classes
struct WavReader
struct WavReaderPCM
struct WavReaderADPCM
Macros
#define FATAL_ERROR(s)
Functions
RString ReadString (RageFileBasic &f, int iSize, RString &sError)
Macro Definition Documentation
FATAL_ERROR
#define FATAL_ERROR (s)
Value:
{                                                                          \
        if (sError.size() == 0)                                                \
            sError = (s);                                                      \
        SetError(sError);                                                      \
        return OPEN_FATAL_ERROR;                                               \
    }
Referenced by RageSoundReader_WAV::Open().
Function Documentation
ReadString()
RString ReadString (RageFileBasic & f, int iSize, RString & sError)
References RageFileBasic::GetError(), RageFileBasic::Read(), and FileReading::ReadBytes().
Referenced by RageSoundReader_WAV::Open(), RageFileDriverZip::ProcessCdirFileHdr(), RageFileDriverZip::ReadEndCentralRecord(), and RageFileDriverZip::ReadLocalFileHeader().