Etterna: LunaRageTexture Class Reference
LunaRageTexture Class Reference
Allow Lua to have access to the RageTexture.
Public Member Functions
DEFINE_METHOD (GetSourceWidth, GetSourceWidth())
DEFINE_METHOD (GetSourceHeight, GetSourceHeight())
DEFINE_METHOD (GetTextureWidth, GetTextureWidth())
DEFINE_METHOD (GetTextureHeight, GetTextureHeight())
DEFINE_METHOD (GetImageWidth, GetImageWidth())
DEFINE_METHOD (GetImageHeight, GetImageHeight())
DEFINE_METHOD (GetPath, GetID().filename)
LunaRageTexture ()
Public Member Functions inherited from Luna< RageTexture >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int position (T *p, lua_State *L)
static int loop (T *p, lua_State *L)
static int rate (T *p, lua_State *L)
static int GetTextureCoordRect (T *p, lua_State *L)
static int GetNumFrames (T *p, lua_State *L)
static int Reload (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageTexture >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageTexture >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageTexture >
using T = RageTexture
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageTexture >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the RageTexture.
Constructor & Destructor Documentation
LunaRageTexture()
LunaRageTexture::LunaRageTexture () inline
References ADD_METHOD, GetNumFrames(), GetTextureCoordRect(), loop(), position(), rate(), and Reload().
Member Function Documentation
DEFINE_METHOD() [1/7]
LunaRageTexture::DEFINE_METHOD (GetSourceWidth , GetSourceWidth())
DEFINE_METHOD() [2/7]
LunaRageTexture::DEFINE_METHOD (GetSourceHeight , GetSourceHeight())
DEFINE_METHOD() [3/7]
LunaRageTexture::DEFINE_METHOD (GetTextureWidth , GetTextureWidth())
DEFINE_METHOD() [4/7]
LunaRageTexture::DEFINE_METHOD (GetTextureHeight , GetTextureHeight())
DEFINE_METHOD() [5/7]
LunaRageTexture::DEFINE_METHOD (GetImageWidth , GetImageWidth())
DEFINE_METHOD() [6/7]
LunaRageTexture::DEFINE_METHOD (GetImageHeight , GetImageHeight())
DEFINE_METHOD() [7/7]
LunaRageTexture::DEFINE_METHOD (GetPath , GetID(). filename)
GetNumFrames()
static int LunaRageTexture::GetNumFrames (T * p, lua_State * L) inline static
References RageTexture::GetNumFrames().
Referenced by LunaRageTexture().
GetTextureCoordRect()
static int LunaRageTexture::GetTextureCoordRect (T * p, lua_State * L) inline static
References StepMania::Rect< T >::bottom, RageTexture::GetTextureCoordRect(), IArg, StepMania::Rect< T >::left, StepMania::Rect< T >::right, and StepMania::Rect< T >::top.
Referenced by LunaRageTexture().
loop()
static int LunaRageTexture::loop (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and RageTexture::SetLooping().
Referenced by LunaRageTexture().
position()
static int LunaRageTexture::position (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and RageTexture::SetPosition().
Referenced by LunaRageTexture().
rate()
static int LunaRageTexture::rate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and RageTexture::SetPlaybackRate().
Referenced by LunaRageTexture().
Reload()
static int LunaRageTexture::Reload (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and RageTexture::Reload().
Referenced by LunaRageTexture().
The documentation for this class was generated from the following file:
RageTexture.cpp