Etterna: NCSplineHandler Struct Reference
NCSplineHandler Struct Reference
#include <NoteDisplay.h>
Public Member Functions
NCSplineHandler ()
float BeatToTValue (float song_beat, float note_beat) const
void EvalForBeat (float song_beat, float note_beat, RageVector3 &ret) const
void EvalDerivForBeat (float song_beat, float note_beat, RageVector3 &ret) const
void EvalForReceptor (float song_beat, RageVector3 &ret) const
void PushSelf (lua_State *L)
Static Public Member Functions
static void MakeWeightedAverage (NCSplineHandler &out, const NCSplineHandler &from, const NCSplineHandler &to, float between)
Public Attributes
CubicSplineN m_spline
NoteColumnSplineMode m_spline_mode
float m_receptor_t
float m_beats_per_t
bool m_subtract_song_beat_from_curr
Constructor & Destructor Documentation
NCSplineHandler()
NCSplineHandler::NCSplineHandler () inline
References m_beats_per_t, CubicSplineN::m_owned_by_actor, m_receptor_t, m_spline, m_spline_mode, m_subtract_song_beat_from_curr, NCSM_Disabled, and CubicSplineN::redimension().
Member Function Documentation
BeatToTValue()
float NCSplineHandler::BeatToTValue (float song_beat, float note_beat) const
References m_beats_per_t, m_receptor_t, and m_subtract_song_beat_from_curr.
Referenced by EvalDerivForBeat(), and EvalForBeat().
EvalDerivForBeat()
void NCSplineHandler::EvalDerivForBeat (float song_beat, float note_beat, RageVector3 & ret) const
References BeatToTValue(), CubicSplineN::evaluate_derivative(), and m_spline.
Referenced by NoteDisplay::DrawHoldPart().
EvalForBeat()
void NCSplineHandler::EvalForBeat (float song_beat, float note_beat, RageVector3 & ret) const
References BeatToTValue(), CubicSplineN::evaluate(), and m_spline.
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHoldPart(), NoteColumnRenderArgs::spae_pos_for_beat(), and NoteColumnRenderArgs::spae_zoom_for_beat().
EvalForReceptor()
void NCSplineHandler::EvalForReceptor (float song_beat, RageVector3 & ret) const
References CubicSplineN::evaluate(), m_beats_per_t, m_receptor_t, m_spline, and m_subtract_song_beat_from_curr.
Referenced by NoteColumnRenderer::UpdateReceptorGhostStuff().
MakeWeightedAverage()
void NCSplineHandler::MakeWeightedAverage (NCSplineHandler & out, const NCSplineHandler & from, const NCSplineHandler & to, float between) static
References BOOLS_FROM_CLOSEST, f, m_spline, and CubicSplineN::weighted_average().
PushSelf()
void NCSplineHandler::PushSelf (lua_State * L)
Member Data Documentation
m_beats_per_t
float NCSplineHandler::m_beats_per_t
Referenced by BeatToTValue(), EvalForReceptor(), and NCSplineHandler().
m_receptor_t
float NCSplineHandler::m_receptor_t
Referenced by BeatToTValue(), EvalForReceptor(), and NCSplineHandler().
m_spline
CubicSplineN NCSplineHandler::m_spline
Referenced by EvalDerivForBeat(), EvalForBeat(), EvalForReceptor(), LunaNCSplineHandler::get_spline(), MakeWeightedAverage(), NoteColumnRenderer::NCR_TweenState::NCR_TweenState(), and NCSplineHandler().
m_spline_mode
NoteColumnSplineMode NCSplineHandler::m_spline_mode
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHoldPart(), NCSplineHandler(), LunaNCSplineHandler::set_spline_mode(), NoteColumnRenderArgs::spae_pos_for_beat(), NoteColumnRenderArgs::spae_zoom_for_beat(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
m_subtract_song_beat_from_curr
bool NCSplineHandler::m_subtract_song_beat_from_curr
Referenced by BeatToTValue(), EvalForReceptor(), and NCSplineHandler().
The documentation for this struct was generated from the following files:
NoteDisplay.h
NoteDisplay.cpp