Etterna: LuaThreadVariable Class Reference
LuaThreadVariable Class Reference
#include <LuaManager.h>
Public Member Functions
LuaThreadVariable (const std::string &sName, const std::string &sValue)
LuaThreadVariable (const std::string &sName, const LuaReference &Value)
LuaThreadVariable (lua_State *L)
~LuaThreadVariable ()
Static Public Member Functions
static void GetThreadVariable (lua_State *L)
Private Member Functions
LuaThreadVariable (const LuaThreadVariable &cpy)
void SetFromStack (lua_State *L)
int AdjustCount (lua_State *L, int iAdd)
LuaThreadVariable & operator= (const LuaThreadVariable &rhs)
Static Private Member Functions
static bool PushThreadTable (lua_State *L, bool bCreate)
static std::string GetCurrentThreadIDString ()
Private Attributes
LuaReference * m_Name
LuaReference * m_pOldValue
Constructor & Destructor Documentation
LuaThreadVariable() [1/4]
LuaThreadVariable::LuaThreadVariable (const std::string & sName, const std::string & sValue)
References LuaManager::Get(), m_Name, m_pOldValue, LuaHelpers::Push(), LuaManager::Release(), LuaReference::SetFromStack(), and SetFromStack().
LuaThreadVariable() [2/4]
LuaThreadVariable::LuaThreadVariable (const std::string & sName, const LuaReference & Value)
References LuaManager::Get(), m_Name, m_pOldValue, LuaHelpers::Push(), LuaReference::PushSelf(), LuaManager::Release(), LuaReference::SetFromStack(), and SetFromStack().
LuaThreadVariable() [3/4]
LuaThreadVariable::LuaThreadVariable (lua_State * L)
References m_Name, m_pOldValue, LuaReference::SetFromStack(), and SetFromStack().
~LuaThreadVariable()
LuaThreadVariable::~LuaThreadVariable ()
References AdjustCount(), ASSERT, LuaManager::Get(), GetCurrentThreadIDString(), m_Name, m_pOldValue, LuaHelpers::Push(), LuaReference::PushSelf(), PushThreadTable(), and LuaManager::Release().
LuaThreadVariable() [4/4]
LuaThreadVariable::LuaThreadVariable (const LuaThreadVariable & cpy) private
Member Function Documentation
AdjustCount()
int LuaThreadVariable::AdjustCount (lua_State * L, int iAdd) private
References ASSERT.
Referenced by SetFromStack(), and ~LuaThreadVariable().
GetCurrentThreadIDString()
std::string LuaThreadVariable::GetCurrentThreadIDString () static private
References RageThread::GetCurrentThreadID(), and ssprintf().
Referenced by PushThreadTable(), and ~LuaThreadVariable().
GetThreadVariable()
void LuaThreadVariable::GetThreadVariable (lua_State * L) static
References PushThreadTable().
operator=()
LuaThreadVariable& LuaThreadVariable::operator= (const LuaThreadVariable & rhs) private
PushThreadTable()
bool LuaThreadVariable::PushThreadTable (lua_State * L, bool bCreate) static private
References GetCurrentThreadIDString(), and LuaHelpers::Push().
Referenced by GetThreadVariable(), SetFromStack(), and ~LuaThreadVariable().
SetFromStack()
void LuaThreadVariable::SetFromStack (lua_State * L) private
References AdjustCount(), ASSERT, LuaReference::IsSet(), m_Name, m_pOldValue, LuaReference::PushSelf(), PushThreadTable(), and LuaReference::SetFromStack().
Referenced by LuaThreadVariable().
Member Data Documentation
m_Name
LuaReference* LuaThreadVariable::m_Name private
Referenced by LuaThreadVariable(), SetFromStack(), and ~LuaThreadVariable().
m_pOldValue
LuaReference* LuaThreadVariable::m_pOldValue private
Referenced by LuaThreadVariable(), SetFromStack(), and ~LuaThreadVariable().
The documentation for this class was generated from the following files:
LuaManager.h
LuaManager.cpp