Etterna: RageTimer.cpp File Reference
RageTimer.cpp File Reference
#include "global.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "LuaManager.h"
Macros
#define TIMESTAMP_RESOLUTION 1000000
Functions
static uint64_t GetTime (bool)
Variables
const RageTimer RageZeroTimer (0, 0)
static uint64_t g_iStartTime = ArchHooks::GetMicrosecondsSinceStart(true)
Macro Definition Documentation
TIMESTAMP_RESOLUTION
#define TIMESTAMP_RESOLUTION 1000000
Referenced by RageTimer::Difference(), and RageTimer::Sum().
Function Documentation
GetTime()
static uint64_t GetTime (bool) static
References ArchHooks::GetMicrosecondsSinceStart().
Referenced by RageTimer::GetTimeSinceStart(), RageTimer::GetUsecsSinceStart(), and RageTimer::Touch().
Variable Documentation
g_iStartTime
uint64_t g_iStartTime = ArchHooks::GetMicrosecondsSinceStart(true) static
Referenced by RageTimer::GetTimeSinceStart(), and RageTimer::GetUsecsSinceStart().
RageZeroTimer
const RageTimer RageZeroTimer(0, 0)
Referenced by RageSoundDriver::ClampHardwareFrame(), and RageSoundBase::GetStartTime().