Etterna: InputHandler_SextetStream::Impl Class Reference
InputHandler_SextetStream::Impl Class Reference abstract
Public Member Functions
Impl (InputHandler_SextetStream *_this)
virtual ~Impl ()
virtual void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
void GetNewState (uint8_t *buffer, RString &line)
DeviceButton ButtonAtIndex (size_t index)
void ReactToChanges (const uint8_t *newStateBuffer)
void RunInputThread ()
Static Public Member Functions
static int StartInputThread (void *p)
Protected Member Functions
void ButtonPressed (const DeviceInput &di)
virtual LineReader * getUnvalidatedLineReader ()=0
void clearStateBuffer ()
void createThread ()
LineReader * getLineReader ()
Protected Attributes
uint8_t stateBuffer [STATE_BUFFER_SIZE]
size_t timeout_ms
RageThread inputThread
bool continueInputThread
Private Attributes
InputHandler_SextetStream * handler
Constructor & Destructor Documentation
Impl()
InputHandler_SextetStream::Impl::Impl (InputHandler_SextetStream * _this) inline
References BUTTON_COUNT, DEFAULT_TIMEOUT_MS, RageLog::Info(), and LOG.
~Impl()
virtual InputHandler_SextetStream::Impl::~Impl () inline virtual
References RageThread::IsCreated(), and RageThread::Wait().
Member Function Documentation
ButtonAtIndex()
DeviceButton InputHandler_SextetStream::Impl::ButtonAtIndex (size_t index) inline
References COUNT_JOY_BUTTON, COUNT_KEY, DeviceButton_Invalid, enum_add2(), FIRST_JOY_BUTTON, and FIRST_KEY.
ButtonPressed()
void InputHandler_SextetStream::Impl::ButtonPressed (const DeviceInput & di) inline protected
References InputHandler::ButtonPressed().
clearStateBuffer()
void InputHandler_SextetStream::Impl::clearStateBuffer () inline protected
References STATE_BUFFER_SIZE.
createThread()
void InputHandler_SextetStream::Impl::createThread () inline protected
References RageThread::Create(), and RageThread::SetName().
GetDevicesAndDescriptions()
virtual void InputHandler_SextetStream::Impl::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) inline virtual
References FIRST_DEVICE.
getLineReader()
LineReader* InputHandler_SextetStream::Impl::getLineReader () inline protected
GetNewState()
void InputHandler_SextetStream::Impl::GetNewState (uint8_t * buffer, RString & line) inline
References STATE_BUFFER_SIZE.
getUnvalidatedLineReader()
virtual LineReader* InputHandler_SextetStream::Impl::getUnvalidatedLineReader () protected pure virtual
ReactToChanges()
void InputHandler_SextetStream::Impl::ReactToChanges (const uint8_t * newStateBuffer) inline
References BUTTON_COUNT, FIRST_DEVICE, LOG, STATE_BUFFER_SIZE, and RageLog::Trace().
RunInputThread()
void InputHandler_SextetStream::Impl::RunInputThread () inline
References RageLog::Info(), LOG, STATE_BUFFER_SIZE, RageLog::Trace(), and RageLog::Warn().
StartInputThread()
static int InputHandler_SextetStream::Impl::StartInputThread (void * p) inline static
Member Data Documentation
continueInputThread
bool InputHandler_SextetStream::Impl::continueInputThread protected
handler
InputHandler_SextetStream* InputHandler_SextetStream::Impl::handler private
inputThread
RageThread InputHandler_SextetStream::Impl::inputThread protected
stateBuffer
uint8_t InputHandler_SextetStream::Impl::stateBuffer[STATE_BUFFER_SIZE] protected
timeout_ms
size_t InputHandler_SextetStream::Impl::timeout_ms protected
The documentation for this class was generated from the following file:
InputHandler_SextetStream.cpp