Etterna: RageCompiledGeometrySWD3D Class Reference
RageCompiledGeometrySWD3D Class Reference
Public Member Functions
void Allocate (const vector< msMesh > &vMeshes) override
void Change (const vector< msMesh > &vMeshes) override
void Draw (int iMeshIndex) const override
Public Member Functions inherited from RageCompiledGeometry
virtual ~RageCompiledGeometry ()
void Set (const vector< msMesh > &vMeshes, bool bNeedsNormals)
Protected Attributes
vector< RageModelVertex > m_vVertex
vector< msTriangle > m_vTriangles
Protected Attributes inherited from RageCompiledGeometry
vector< MeshInfo > m_vMeshInfo
bool m_bNeedsNormals
bool m_bAnyNeedsTextureMatrixScale
Additional Inherited Members
Protected Member Functions inherited from RageCompiledGeometry
size_t GetTotalVertices () const
size_t GetTotalTriangles () const
Member Function Documentation
Allocate()
void RageCompiledGeometrySWD3D::Allocate (const vector< msMesh > & vMeshes) inline override virtual
Implements RageCompiledGeometry.
References RageCompiledGeometry::GetTotalTriangles(), RageCompiledGeometry::GetTotalVertices(), m_vTriangles, m_vVertex, and max().
Change()
void RageCompiledGeometrySWD3D::Change (const vector< msMesh > & vMeshes) inline override virtual
Implements RageCompiledGeometry.
References RageCompiledGeometry::MeshInfo::iTriangleStart, RageCompiledGeometry::MeshInfo::iVertexStart, RageCompiledGeometry::m_vMeshInfo, m_vTriangles, m_vVertex, msMesh::Triangles, and msMesh::Vertices.
Draw()
void RageCompiledGeometrySWD3D::Draw (int iMeshIndex) const inline override virtual
Implements RageCompiledGeometry.
References D3DFVF_RageModelVertex, g_lastFVF, g_pd3dDevice, RageCompiledGeometry::MeshInfo::iTriangleCount, RageCompiledGeometry::MeshInfo::iTriangleStart, RageCompiledGeometry::MeshInfo::iVertexCount, RageCompiledGeometry::MeshInfo::iVertexStart, RageCompiledGeometry::MeshInfo::m_bNeedsTextureMatrixScale, RageCompiledGeometry::m_vMeshInfo, m_vTriangles, and m_vVertex.
Member Data Documentation
m_vTriangles
vector<msTriangle> RageCompiledGeometrySWD3D::m_vTriangles protected
Referenced by Allocate(), Change(), and Draw().
m_vVertex
vector<RageModelVertex> RageCompiledGeometrySWD3D::m_vVertex protected
Referenced by Allocate(), Change(), and Draw().
The documentation for this class was generated from the following file:
RageDisplay_D3D.cpp