Etterna: GameState Class Reference
GameState Class Reference
Holds game data that is not saved between sessions.
#include <GameState.h>
Classes
struct RankingFeat
Public Member Functions
GameState ()
Set up the GameState with initial values.
~GameState ()
void Reset ()
Reset the GameState back to initial values.
void ResetPlayer (PlayerNumber pn)
void ResetPlayerOptions (PlayerNumber pn)
void ApplyCmdline ()
void ApplyGameCommand (const RString &sCommand, PlayerNumber pn=PLAYER_INVALID)
void BeginGame ()
Start the game when the first player joins in.
void JoinPlayer (PlayerNumber pn)
void UnjoinPlayer (PlayerNumber pn)
bool JoinInput (PlayerNumber pn)
bool JoinPlayers ()
void LoadProfiles (bool bLoadEdits=true)
void SavePlayerProfiles ()
void SavePlayerProfile (PlayerNumber pn)
bool HaveProfileToLoad ()
bool HaveProfileToSave ()
void SaveLocalData ()
void AddStageToPlayer (PlayerNumber pn)
void LoadCurrentSettingsFromProfile (PlayerNumber pn)
void SaveCurrentSettingsToProfile (PlayerNumber pn)
Save the specified player's settings to his/her profile.
Song * GetDefaultSong () const
bool CanSafelyEnterGameplay (RString &reason)
void SetCompatibleStylesForPlayers ()
void ForceSharedSidesMatch ()
void ForceOtherPlayersToCompatibleSteps (PlayerNumber main)
void Update (float fDelta)
void SetCurGame (const Game *pGame)
State what the current game is.
bool DifficultiesLocked () const
bool ChangePreferredDifficultyAndStepsType (PlayerNumber pn, Difficulty dc, StepsType st)
bool ChangePreferredDifficulty (PlayerNumber pn, int dir)
Difficulty GetClosestShownDifficulty (PlayerNumber pn) const
Difficulty GetEasiestStepsDifficulty () const
Difficulty GetHardestStepsDifficulty () const
void SetNewStageSeed ()
bool PlayersCanJoin () const
Determine if a second player can join in at this time.
const Game * GetCurrentGame () const
const Style * GetCurrentStyle (PlayerNumber pn) const
void SetCurrentStyle (const Style *style, PlayerNumber pn)
bool SetCompatibleStyle (StepsType stype, PlayerNumber pn)
void GetPlayerInfo (PlayerNumber pn, bool &bIsEnabledOut, bool &bIsHumanOut)
bool IsPlayerEnabled (PlayerNumber pn) const
bool IsMultiPlayerEnabled (MultiPlayer mp) const
bool IsPlayerEnabled (const PlayerState *pPlayerState) const
int GetNumPlayersEnabled () const
bool IsHumanPlayer (PlayerNumber pn) const
Is the specified Player a human Player?
int GetNumHumanPlayers () const
PlayerNumber GetFirstHumanPlayer () const
PlayerNumber GetFirstDisabledPlayer () const
bool IsCpuPlayer (PlayerNumber pn) const
bool AnyPlayersAreCpu () const
PlayerNumber GetMasterPlayerNumber () const
Retrieve the present master player number.
void SetMasterPlayerNumber (const PlayerNumber p)
Set the master player number.
TimingData * GetProcessedTimingData () const
Retrieve the present timing data being processed.
void SetProcessedTimingData (TimingData *t)
Set the timing data to be used with processing.
bool ShowW1 () const
Do we show the W1 timing judgment?
bool IsEditing () const
int GetNumStagesForCurrentSongAndStepsOrCourse () const
void BeginStage ()
void CancelStage ()
void CommitStageStats ()
void FinishStage ()
int GetCourseSongIndex () const
RString GetPlayerDisplayName (PlayerNumber pn) const
int GetLoadingCourseSongIndex () const
RString GetEtternaVersion ()
bool IsPlaylistCourse ()
bool CountNotesSeparately ()
void GetAllUsedNoteSkins (vector< RString > &out) const
void ResetMusicStatistics ()
void SetPaused (bool p)
bool GetPaused ()
void UpdateSongPosition (float fPositionSeconds, const TimingData &timing, const RageTimer &timestamp=RageZeroTimer)
float GetSongPercent (float beat) const
bool AllAreInDangerOrWorse () const
bool OneIsHot () const
PlayerNumber GetBestPlayer () const
StageResult GetStageResult (PlayerNumber pn) const
void ResetStageStatistics ()
Call this function when it's time to play a new stage.
void GetDefaultPlayerOptions (PlayerOptions &po)
void GetDefaultSongOptions (SongOptions &so)
void ResetToDefaultSongOptions (ModsLevel l)
void ApplyPreferredModifiers (PlayerNumber pn, const RString &sModifiers)
void ApplyStageModifiers (PlayerNumber pn, const RString &sModifiers)
void ResetOptions ()
bool CurrentOptionsDisqualifyPlayer (PlayerNumber pn)
bool PlayerIsUsingModifier (PlayerNumber pn, const RString &sModifier)
FailType GetPlayerFailType (const PlayerState *pPlayerState) const
int GetNumSidesJoined () const
void GetRankingFeats (PlayerNumber pn, vector< RankingFeat > &vFeatsOut) const
bool AnyPlayerHasRankingFeats () const
void StoreRankingName (PlayerNumber pn, RString name)
bool IsTimeToPlayAttractSounds () const
void VisitAttractScreen (const RString sScreenName)
int GetNumCols (int pn)
bool IsEventMode () const
Profile * GetEditLocalProfile ()
void discordInit ()
void updateDiscordPresence (const RString &largeImageText, const RString &details, const RString &state, const int64_t endTime)
void updateDiscordPresenceMenu (const RString &largeImageText)
void PushSelf (lua_State *L)
Static Public Member Functions
static int GetNumStagesMultiplierForSong (const Song *pSong)
static int GetNumStagesForSongAndStyleType (const Song *pSong, StyleType st)
Public Attributes
BroadcastOnChangePtr< const Game > m_pCurGame
bool m_bSideIsJoined [NUM_PLAYERS]
Determine which side is joined.
MultiPlayerStatus m_MultiPlayerStatus [NUM_MultiPlayer]
BroadcastOnChange< PlayMode > m_PlayMode
bool m_bMultiplayer
int m_iNumMultiplayerNoteFields
RageTimer m_timeGameStarted
LuaTable * m_Environment
int m_iGameSeed
int m_iStageSeed
RString m_sStageGUID
BroadcastOnChange< RString > m_sPreferredSongGroup
bool m_bFailTypeWasExplicitlySet
BroadcastOnChange< StepsType > m_PreferredStepsType
BroadcastOnChange1D< Difficulty, NUM_PLAYERS > m_PreferredDifficulty
BroadcastOnChange< SortOrder > m_SortOrder
SortOrder m_PreferredSortOrder
EditMode m_EditMode
bool m_bDemonstrationOrJukebox
Are we in the demonstration or jukebox mode?
bool m_bJukeboxUsesModifiers
int m_iNumStagesOfThisSong
bool m_bInNetGameplay = false
int m_iCurrentStageIndex
Increase this every stage while not resetting on a continue.
int m_iPlayerStageTokens [NUM_PLAYERS]
The number of stages available for the players.
bool m_AdjustTokensBySongCostForFinalStageCheck
RString sExpandedSectionName
bool m_bLoadingNextSong
bool isplaylistcourse = false
BroadcastOnChangePtr< Song > m_pCurSong
Song * m_pPreferredSong
BroadcastOnChangePtr1D< Steps, NUM_PLAYERS > m_pCurSteps
SongPosition m_Position
BroadcastOnChange< bool > m_bGameplayLeadIn
RageTimer m_DanceStartTime
float m_DanceDuration
float m_fOpponentHealthPercent
float m_fTugLifePercentP1
ModsGroup< SongOptions > m_SongOptions
bool m_bDidModeChangeNoteSkin { false }
Did the current game mode change the default Noteskin?
Character * m_pCurCharacters [NUM_PLAYERS]
vector< RString * > m_vpsNamesThatWereFilled
deque< StageAward > m_vLastStageAwards [NUM_PLAYERS]
deque< PeakComboAward > m_vLastPeakComboAwards [NUM_PLAYERS]
int m_iNumTimesThroughAttract
PlayerState * m_pPlayerState [NUM_PLAYERS]
Allow access to each player's PlayerState.
PlayerState * m_pMultiPlayerState [NUM_MultiPlayer]
bool m_bTemporaryEventMode
bool m_bIsUsingStepTiming { true }
Is the game right now using Song timing or Steps timing?
BroadcastOnChange< RString > m_sEditLocalProfileID
bool m_bDopefish
Static Public Attributes
static const float MUSIC_SECONDS_INVALID = -5000.0f
static Preference< bool > m_bAutoJoin
static Preference< bool > DisableChordCohesion
Private Member Functions
GameState (const GameState &rhs)
GameState & operator= (const GameState &rhs)
Private Attributes
PlayerNumber masterPlayerNumber
The player number used with Styles where one player controls both sides.
TimingData * processedTiming
The TimingData that is used for processing certain functions.
BroadcastOnChangePtr< const Style > m_pCurStyle
Style const * m_SeparatedStyles [NUM_PlayerNumber]
RageTimer m_LastPositionTimer
float m_LastPositionSeconds
bool m_paused
Detailed Description
Holds game data that is not saved between sessions.
Constructor & Destructor Documentation
GameState() [1/2]
GameState::GameState ()
Set up the GameState with initial values.
References FOREACH_MultiPlayer, FOREACH_PlayerNumber, LuaManager::Get(), L, LUA, m_bDemonstrationOrJukebox, m_bDopefish, m_bSideIsJoined, m_Environment, m_iGameSeed, m_iNumTimesThroughAttract, m_iStageSeed, PlayerState::m_mp, m_pCurGame, m_pCurStyle, m_PlayMode, m_pMultiPlayerState, m_pPlayerState, m_SeparatedStyles, m_timeGameStarted, PLAYER_1, PlayMode_Invalid, PushSelf(), LuaManager::Release(), BroadcastOnChange< T >::Set(), BroadcastOnChangePtr< T >::Set(), PlayerState::SetPlayerNumber(), RageTimer::SetZero(), and sExpandedSectionName.
~GameState()
GameState::~GameState ()
References FOREACH_MultiPlayer, FOREACH_PlayerNumber, LUA, m_Environment, m_pMultiPlayerState, m_pPlayerState, processedTiming, SAFE_DELETE, and LuaManager::UnsetGlobal().
GameState() [2/2]
GameState::GameState (const GameState & rhs) private
Member Function Documentation
AddStageToPlayer()
void GameState::AddStageToPlayer (PlayerNumber pn)
References m_iPlayerStageTokens.
Referenced by LunaGameState::AddStageToPlayer().
AllAreInDangerOrWorse()
bool GameState::AllAreInDangerOrWorse () const
References FOREACH_EnabledPlayer, HealthState_Danger, and m_pPlayerState.
Referenced by BackgroundImpl::IsDangerAllVisible(), and ScreenGameplay::Update().
AnyPlayerHasRankingFeats()
bool GameState::AnyPlayerHasRankingFeats () const
References FOREACH_PlayerNumber, and GetRankingFeats().
AnyPlayersAreCpu()
bool GameState::AnyPlayersAreCpu () const
References FOREACH_CpuPlayer.
ApplyCmdline()
void GameState::ApplyCmdline ()
References ApplyGameCommand(), GetCommandlineArgument(), IsAnInt(), JoinPlayer(), NUM_PLAYERS, StringToInt(), and RageException::Throw().
Referenced by Reset().
ApplyGameCommand()
void GameState::ApplyGameCommand (const RString & sCommand, PlayerNumber pn = PLAYER_INVALID)
References GameCommand::Apply(), GameCommand::ApplyToAllPlayers(), GameCommand::IsPlayable(), GameCommand::Load(), ParseCommands(), PLAYER_INVALID, and LuaHelpers::ReportScriptErrorFmt().
Referenced by ApplyCmdline(), and LunaGameState::ApplyGameCommand().
ApplyPreferredModifiers()
void GameState::ApplyPreferredModifiers (PlayerNumber pn, const RString & sModifiers)
References ModsGroup< T >::FromString(), PlayerState::m_PlayerOptions, m_pPlayerState, m_SongOptions, and ModsLevel_Preferred.
Referenced by LunaGameState::ApplyPreferredModifiers(), GameCommand::ApplySelf(), and LoadCurrentSettingsFromProfile().
ApplyStageModifiers()
void GameState::ApplyStageModifiers (PlayerNumber pn, const RString & sModifiers)
References ModsGroup< T >::FromString(), PlayerState::m_PlayerOptions, m_pPlayerState, m_SongOptions, and ModsLevel_Stage.
Referenced by GameCommand::ApplySelf(), LunaGameState::ApplyStageModifiers(), and NoteField::CacheAllUsedNoteSkins().
BeginGame()
void GameState::BeginGame ()
Start the game when the first player joins in.
References m_iNumTimesThroughAttract, m_timeGameStarted, m_vpsNamesThatWereFilled, and RageTimer::Touch().
Referenced by JoinPlayer().
BeginStage()
void GameState::BeginStage ()
References ARE_STAGE_PLAYER_MODS_FORCED, ARE_STAGE_SONG_MODS_FORCED, ASSERT, ModsGroup< T >::Assign(), CurrentOptionsDisqualifyPlayer(), FOREACH_EnabledPlayer, FOREACH_HumanPlayer, FOREACH_PlayerNumber, CryptManager::GenerateRandomUUID(), GetNumStagesForCurrentSongAndStepsOrCourse(), ModsGroup< T >::GetPreferred(), ModsGroup< T >::GetSong(), IsCpuPlayer(), IsEventMode(), LOG, m_bDemonstrationOrJukebox, PlayerStageStats::m_bDisqualified, StatsManager::m_CurStageStats, SongOptions::m_fMusicRate, StageStats::m_fMusicRate, m_iNumStagesOfThisSong, m_iPlayerStageTokens, StageStats::m_player, PlayerState::m_PlayerOptions, m_pPlayerState, m_SongOptions, m_sStageGUID, ModsLevel_Stage, LuaHelpers::ReportScriptErrorFmt(), AdjustSync::ResetOriginalSyncData(), ResetStageStatistics(), STATSMAN, and RageLog::Warn().
Referenced by ScreenGameplay::Init().
CancelStage()
void GameState::CancelStage ()
References FOREACH_EnabledPlayer, m_iNumStagesOfThisSong, m_iPlayerStageTokens, and ResetStageStatistics().
Referenced by ScreenGameplay::StageFinished(), and ScreenGameplay::~ScreenGameplay().
CanSafelyEnterGameplay()
bool GameState::CanSafelyEnterGameplay (RString & reason)
References FOREACH_EnabledPlayer, GAMEMAN, GetCurrentStyle(), Steps::GetNoteData(), NoteData::GetNumTracks(), GameManager::GetStepsTypeInfo(), Style::m_iColsPerPlayer, m_pCurSong, m_pCurSteps, Steps::m_pSong, Style::m_StepsType, Steps::m_StepsType, ssprintf(), and StepsTypeInfo::szName.
Referenced by LunaGameState::CanSafelyEnterGameplay().
ChangePreferredDifficulty()
bool GameState::ChangePreferredDifficulty (PlayerNumber pn, int dir)
References CommonMetrics::DIFFICULTIES_TO_SHOW, enum_add2(), GetClosestShownDifficulty(), ThemeMetricDifficultiesToShow::GetValue(), m_PreferredDifficulty, and NUM_Difficulty.
Referenced by ScreenSelectMusic::ChangeSteps().
ChangePreferredDifficultyAndStepsType()
bool GameState::ChangePreferredDifficultyAndStepsType (PlayerNumber pn, Difficulty dc, StepsType st)
References DifficultiesLocked(), FOREACH_PlayerNumber, m_PreferredDifficulty, m_PreferredStepsType, and BroadcastOnChange< T >::Set().
Referenced by ScreenSelectMusic::ChangeSteps().
CommitStageStats()
void GameState::CommitStageStats ()
References StatsManager::CommitStatsToProfiles(), FOREACH_HumanPlayer, RageTimer::GetDeltaTime(), ProfileManager::GetProfile(), m_bDemonstrationOrJukebox, StatsManager::m_CurStageStats, Profile::m_iTotalSessionSeconds, m_timeGameStarted, max(), PROFILEMAN, and STATSMAN.
Referenced by ScreenGameplay::StageFinished().
CountNotesSeparately()
bool GameState::CountNotesSeparately ()
References DisableChordCohesion, Preference< T >::Get(), GetCurrentGame(), and Game::m_bCountNotesSeparately.
Referenced by DetermineScoreEligibility(), FillInHighScore(), ScoreKeeperNormal::GetPossibleDancePoints(), ScoreKeeperNormal::HandleHoldCheckpointScore(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), ScoreKeeperNormal::HandleTapRowScore(), Player::SetJudgment(), Player::Step(), Player::UpdateJudgedRows(), and Player::UpdateTapNotesMissedOlderThan().
CurrentOptionsDisqualifyPlayer()
bool GameState::CurrentOptionsDisqualifyPlayer (PlayerNumber pn)
References ModsGroup< T >::GetPreferred(), PlayerOptions::IsEasierForSongAndSteps(), IsHumanPlayer(), PrefsManager::m_bDisqualification, m_pCurSong, m_pCurSteps, PlayerState::m_PlayerOptions, m_pPlayerState, and PREFSMAN.
Referenced by BeginStage(), LunaGameState::CurrentOptionsDisqualifyPlayer(), and ScreenPlayerOptions::UpdateDisqualified().
DifficultiesLocked()
bool GameState::DifficultiesLocked () const
References GetCurrentStyle(), and PLAYER_INVALID.
Referenced by ChangePreferredDifficultyAndStepsType(), ScreenSelectMusic::ChangeSteps(), and ScreenSelectMusic::SwitchToPreferredDifficulty().
discordInit()
void GameState::discordInit ()
Referenced by SetCurGame().
FinishStage()
void GameState::FinishStage ()
References FOREACH_HumanPlayer, ProfileManager::GetProfile(), StatsManager::m_CurStageStats, PlayerStageStats::m_iCurCombo, Profile::m_iCurrentCombo, m_iCurrentStageIndex, m_iNumStagesOfThisSong, StageStats::m_player, PROFILEMAN, and STATSMAN.
Referenced by ScreenGameplay::StageFinished().
ForceOtherPlayersToCompatibleSteps()
void GameState::ForceOtherPlayersToCompatibleSteps (PlayerNumber main)
References FOREACH_EnabledPlayer, GAMEMAN, GetCurrentGame(), GameManager::GetFirstCompatibleStyle(), Steps::GetMusicFile(), GetNumPlayersEnabled(), m_pCurSteps, Steps::m_StepsType, main(), and StyleType_TwoPlayersSharedSides.
Referenced by ScreenSelectMusic::ChangeSteps(), and LunaGameState::SetCurrentSteps().
ForceSharedSidesMatch()
void GameState::ForceSharedSidesMatch ()
References ASSERT_M, FOREACH_EnabledPlayer, GetCurrentStyle(), GetNumPlayersEnabled(), m_pCurSteps, Style::m_StyleType, OPPOSITE_PLAYER, PLAYER_INVALID, SetCurrentStyle(), and StyleType_TwoPlayersSharedSides.
Referenced by ScreenSelectMusic::SelectCurrent().
GetAllUsedNoteSkins()
void GameState::GetAllUsedNoteSkins (vector< RString > & out) const
References FOREACH_EnabledPlayer, and m_pPlayerState.
Referenced by NoteField::CacheAllUsedNoteSkins().
GetBestPlayer()
PlayerNumber GameState::GetBestPlayer () const
References FOREACH_PlayerNumber, GetStageResult(), PLAYER_INVALID, and RESULT_WIN.
GetClosestShownDifficulty()
Difficulty GameState::GetClosestShownDifficulty (PlayerNumber pn) const
References CommonMetrics::DIFFICULTIES_TO_SHOW, FOREACH_CONST, ThemeMetricDifficultiesToShow::GetValue(), and m_PreferredDifficulty.
Referenced by ChangePreferredDifficulty(), and StepsDisplayList::GetCurrentRowIndex().
GetCourseSongIndex()
int GameState::GetCourseSongIndex () const
References FAIL_M, FOREACH_EnabledMultiPlayer, GetMasterPlayerNumber(), m_bMultiplayer, StatsManager::m_CurStageStats, PlayerStageStats::m_iSongsPlayed, StageStats::m_multiPlayer, StageStats::m_player, and STATSMAN.
Referenced by GetLoadingCourseSongIndex(), ScreenGameplay::LoadNextSong(), and LifeMeterTime::OnLoadSong().
GetCurrentGame()
const Game * GameState::GetCurrentGame () const
References ASSERT, and m_pCurGame.
Referenced by CountNotesSeparately(), ForceOtherPlayersToCompatibleSteps(), NoteDataWithScoring::GetActualRadarValues(), LunaGameState::GetCurrentGame(), GetCurrentStyle(), ScoreKeeperNormal::GetPossibleDancePoints(), ScoreKeeperNormal::GetPossibleGradePoints(), ScreenGameplay::Init(), StepMania::InitializeCurrentGame(), IsHumanPlayer(), Player::Load(), StepMania::ResetGame(), ScreenGameplay::SendCrossedMessages(), SetCurrentStyle(), sm_main(), and Player::Step().
GetCurrentStyle()
const Style * GameState::GetCurrentStyle (PlayerNumber pn) const
References GetCurrentGame(), m_pCurStyle, m_SeparatedStyles, NUM_PLAYERS, PLAYER_1, and PLAYER_2.
Referenced by ScreenSelectMusic::BeginScreen(), MusicWheel::BuildWheelItemDatas(), NoteField::CacheAllUsedNoteSkins(), NoteField::CacheNoteSkin(), CanSafelyEnterGameplay(), BeginnerHelper::CanUse(), ScreenGameplay::Center1Player(), LunaNoteField::check_column(), Player::CrossedRows(), GameCommand::DescribesCurrentMode(), DifficultiesLocked(), ReceptorArrowRow::DrawOverlay(), GhostArrowRow::DrawPrimitives(), ReceptorArrowRow::DrawPrimitives(), NoteField::DrawPrimitives(), Player::DrawPrimitives(), MusicWheel::FilterWheelItemDatas(), ForceSharedSidesMatch(), get_returned_column(), LunaGameState::GetCurrentStyle(), SongUtil::GetPlayableStepsTypes(), MusicWheel::GetPreferredSelectionForRandomOrPortal(), GetRankingFeats(), PlayerOptions::GetReversePercentForColumn(), LunaPlayerOptions::GetReversePercentForColumn(), SongUtil::GetSectionNameFromSongAndSort(), MusicWheel::GetSongList(), NoteField::GetWidth(), ArrowEffects::GetXPos(), ScreenGameplayLesson::Init(), ScreenHowToPlay::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), NoteField::InitColumnRenderers(), ScreenGameplay::Input(), IsHumanPlayer(), GameCommand::IsPlayable(), JoinPlayer(), SnapDisplay::Load(), ReceptorArrow::Load(), GhostArrowRow::Load(), ReceptorArrowRow::Load(), NoteField::Load(), ScoreKeeperNormal::Load(), Player::Load(), NoteDisplay::Load(), GameCommand::LoadOne(), ScreenNetSelectMusic::MenuDown(), ScreenNetSelectMusic::MusicChanged(), MusicWheelItem::RefreshGrades(), OptionRowHandlerListSteps::Reload(), ScreenGameplay::SendCrossedMessages(), SetCompatibleStyle(), LunaGameState::SetCompatibleStyleOrError(), LunaGameState::SetCurrentPlayMode(), SetCurrentStyle(), StepsDisplayList::SetFromGameState(), ScreenGameplay::SetupSong(), SongUtil::SortSongPointerArrayByGrades(), ScreenNetSelectMusic::StartSelectedSong(), ArrowEffects::Update(), ReceptorArrowRow::Update(), Player::Update(), ScreenNetSelectMusic::UpdateDifficulties(), Player::UpdateHoldNotes(), and ScreenNetEvaluation::UpdateStats().
GetDefaultPlayerOptions()
void GameState::GetDefaultPlayerOptions (PlayerOptions & po)
References CommonMetrics::DEFAULT_MODIFIERS, CommonMetrics::DEFAULT_NOTESKIN_NAME, PlayerOptions::FromString(), PlayerOptions::Init(), PrefsManager::m_sDefaultModifiers, PlayerOptions::m_sNoteSkin, and PREFSMAN.
Referenced by GameCommand::ApplySelf(), CodeDetector::DetectAndAdjustMusicOptions(), PlayerOptions::FromOneModString(), ResetPlayerOptions(), and PlayerState::ResetToDefaultPlayerOptions().
GetDefaultSong()
Song * GameState::GetDefaultSong () const
References DEFAULT_SONG, SongID::FromString(), and SongID::ToSong().
Referenced by Reset().
GetDefaultSongOptions()
void GameState::GetDefaultSongOptions (SongOptions & so)
References CommonMetrics::DEFAULT_MODIFIERS, SongOptions::FromString(), SongOptions::Init(), PrefsManager::m_sDefaultModifiers, and PREFSMAN.
Referenced by GameCommand::ApplySelf(), LunaGameState::GetDefaultSongOptions(), ResetToDefaultSongOptions(), and UnjoinPlayer().
GetEasiestStepsDifficulty()
Difficulty GameState::GetEasiestStepsDifficulty () const
References Difficulty_Invalid, FOREACH_HumanPlayer, m_pCurSteps, min(), and LuaHelpers::ReportScriptErrorFmt().
GetEditLocalProfile()
Profile * GameState::GetEditLocalProfile ()
References ProfileManager::GetLocalProfile(), m_sEditLocalProfileID, and PROFILEMAN.
Referenced by ScreenOptionsEditProfile::BeginScreen(), LunaGameState::GetEditLocalProfile(), and ScreenOptionsEditProfile::HandleScreenMessage().
GetEtternaVersion()
RString GameState::GetEtternaVersion () inline
Referenced by DownloadManager::RefreshLastVersion().
GetFirstDisabledPlayer()
PlayerNumber GameState::GetFirstDisabledPlayer () const
References FOREACH_PlayerNumber, IsPlayerEnabled(), and PLAYER_INVALID.
Referenced by ScreenGameplay::Init(), and ScreenGameplay::Update().
GetFirstHumanPlayer()
PlayerNumber GameState::GetFirstHumanPlayer () const
References FOREACH_HumanPlayer, and PLAYER_INVALID.
Referenced by ScreenGameplaySyncMachine::Init(), and ScreenGameplay::Init().
GetHardestStepsDifficulty()
Difficulty GameState::GetHardestStepsDifficulty () const
References Difficulty_Beginner, FOREACH_HumanPlayer, m_pCurSteps, max(), and LuaHelpers::ReportScriptErrorFmt().
GetLoadingCourseSongIndex()
int GameState::GetLoadingCourseSongIndex () const
References GetCourseSongIndex(), and m_bLoadingNextSong.
GetMasterPlayerNumber()
PlayerNumber GameState::GetMasterPlayerNumber () const
Retrieve the present master player number.
Returns
The master player number.
References masterPlayerNumber.
Referenced by ScreenMiniMenu::AfterChangeValueOrRow(), OptionRow::AfterImportOptions(), GameCommand::ApplySelf(), ScreenSelectMaster::ChangePage(), DebugLineAutoplay::DoAndLog(), DebugLineAssist::DoAndLog(), ScoreKeeperShared::DrawPrimitives(), Player::DrawPrimitives(), ScreenSongOptions::ExportOptions(), ScreenGameplayShared::FillPlayerInfo(), AutoKeysounds::FinishLoading(), GetCourseSongIndex(), ScreenOptionsManageProfiles::GetLocalProfileIndexWithFocus(), ScreenGameplayShared::GetPlayerInfoForInput(), SongUtil::GetSectionNameFromSongAndSort(), ScreenSelectMaster::GetSharedPlayer(), ScoreKeeperShared::HandleHoldActiveSeconds(), ScoreKeeperShared::HandleHoldCheckpointScore(), ScoreKeeperShared::HandleHoldScore(), ScreenSelectMusic::HandleMessage(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenSelect::HandleScreenMessage(), ScreenSelectMaster::HandleScreenMessage(), ScreenOptions::HandleScreenMessage(), ScoreKeeperShared::HandleTapRowScore(), ScoreKeeperShared::HandleTapScore(), ScoreKeeperShared::HandleTapScoreNone(), ScreenGameplayLesson::Init(), IsHumanPlayer(), GameCommand::IsPlayable(), JoinPlayer(), ScoreKeeperShared::Load(), SnapDisplay::Load(), AutoKeysounds::LoadAutoplaySoundsInto(), PaneDisplay::LoadFromNode(), Foreground::LoadFromSong(), ScreenGameplay::LoadNextSong(), GameCommand::LoadOne(), AutoKeysounds::LoadTracks(), ScoreKeeperShared::OnNextSong(), ScreenGameplay::PlayTicks(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsExportPackageSubPage::ProcessMenuStart(), OptionRowHandlerListSteps::Reload(), SetCurrentStyle(), SongUtil::SortSongPointerArrayByGrades(), ScreenSelectMusic::SwitchToPreferredDifficulty(), UnjoinPlayer(), ScoreKeeperShared::Update(), and NoteField::Update().
GetNumCols()
int GameState::GetNumCols (int pn)
References PlayerState::GetNumCols(), and m_pPlayerState.
Referenced by PlayerOptions::GetReversePercentForColumn().
GetNumHumanPlayers()
int GameState::GetNumHumanPlayers () const
References FOREACH_HumanPlayer.
Referenced by ScreenOptions::AfterChangeValueOrRow().
GetNumPlayersEnabled()
int GameState::GetNumPlayersEnabled () const
References FOREACH_EnabledPlayer.
Referenced by DancingCharacters::DancingCharacters(), ScreenSelectProfile::Finish(), AutoKeysounds::FinishLoading(), ForceOtherPlayersToCompatibleSteps(), ForceSharedSidesMatch(), SongUtil::GetPlayableStepsTypes(), GameSoundManager::GetPlayerBalance(), ScreenGameplay::Init(), AutoKeysounds::LoadAutoplaySoundsInto(), SMOProtocol::ReportStyle(), and MusicWheel::SetOpenSection().
GetNumSidesJoined()
int GameState::GetNumSidesJoined () const
References FOREACH_PlayerNumber, and m_bSideIsJoined.
Referenced by ScreenSelectMusic::BeginScreen(), ScreenSelect::Input(), JoinPlayer(), SetCompatibleStyle(), SetCompatibleStylesForPlayers(), SetCurrentStyle(), and LunaGameState::SetCurrentStyle().
GetNumStagesForCurrentSongAndStepsOrCourse()
int GameState::GetNumStagesForCurrentSongAndStepsOrCourse () const
References GetNumStagesMultiplierForSong(), m_pCurSong, and max().
Referenced by BeginStage().
GetNumStagesForSongAndStyleType()
static int GameState::GetNumStagesForSongAndStyleType (const Song * pSong, StyleType st) static
GetNumStagesMultiplierForSong()
int GameState::GetNumStagesMultiplierForSong (const Song * pSong) static
References ASSERT, Song::IsLong(), and Song::IsMarathon().
Referenced by MusicWheel::BuildWheelItemDatas(), GetNumStagesForCurrentSongAndStepsOrCourse(), SongCriteria::Matches(), and ScoreKeeperNormal::OnNextSong().
GetPaused()
bool GameState::GetPaused () inline
References m_paused.
Referenced by LunaScreenGameplay::JumpToReplayBookmark(), ScreenGameplay::LoadNextSong(), ScreenGameplay::SetRate(), LunaScreenGameplay::SetReplayPosition(), LunaScreenGameplay::SetReplayRate(), ScreenGameplay::SetSongPosition(), and ScreenGameplay::ToggleReplayPause().
GetPlayerDisplayName()
RString GameState::GetPlayerDisplayName (PlayerNumber pn) const
References ASSERT, CPU, ProfileManager::GetPlayerName(), LocalizedString::GetValue(), IsHumanPlayer(), IsPlayerEnabled(), PLAYER1, PLAYER2, and PROFILEMAN.
Referenced by ScreenSMOnlineLogin::HandleScreenMessage(), SMOProtocol::ReportStyle(), and ScreenSMOnlineLogin::SendLogin().
GetPlayerFailType()
FailType GameState::GetPlayerFailType (const PlayerState * pPlayerState) const
References ModsGroup< T >::GetCurrent(), PlayerOptions::m_FailType, PlayerState::m_PlayerNumber, and PlayerState::m_PlayerOptions.
Referenced by ScreenGameplay::HandleScreenMessage(), BackgroundImpl::IsDangerAllVisible(), and ScreenGameplay::Update().
GetPlayerInfo()
void GameState::GetPlayerInfo (PlayerNumber pn, bool & bIsEnabledOut, bool & bIsHumanOut)
GetProcessedTimingData()
TimingData * GameState::GetProcessedTimingData () const
Retrieve the present timing data being processed.
Returns
the timing data pointer.
References processedTiming.
Referenced by NoteDataUtil::CalculateRadarValues(), NoteDataWithScoring::GetActualRadarValues(), NoteData::GetNumHoldNotes(), NoteData::GetNumHoldNotesTwoPlayer(), NoteData::GetNumRolls(), NoteData::GetNumRollsTwoPlayer(), NoteData::GetNumRowsWithSimultaneousPresses(), NoteData::GetNumRowsWithSimultaneousTaps(), NoteData::GetNumRowsWithTap(), NoteData::GetNumRowsWithTapOrHoldHead(), NoteData::IsFake(), NoteData::IsLift(), NoteData::IsMine(), and NoteData::IsTap().
GetRankingFeats()
void GameState::GetRankingFeats (PlayerNumber pn, vector< RankingFeat > & vFeatsOut) const
References ASSERT, GameState::RankingFeat::Banner, GameState::RankingFeat::CATEGORY, CATEGORY_RECORD_FEATS, CHECKPOINT_M, DifficultyToString(), FAIL_M, GameState::RankingFeat::Feat, FOREACH_ENUM, GameState::RankingFeat::fPercentDP, BroadcastOnChange< T >::Get(), StageStats::GetAverageMeter(), Song::GetBackgroundPath(), Profile::GetCategoryHighScoreList(), GetCurrentStyle(), Steps::GetDifficulty(), StatsManager::GetFinalEvalStageStats(), HighScore::GetGrade(), HighScore::GetName(), HighScore::GetPercentDP(), ProfileManager::GetProfile(), HighScore::GetScore(), Profile::GetStepsHighScoreList(), Song::GetTranslitMainTitle(), GameState::RankingFeat::grade, Grade_NoData, Song::HasBackground(), GameState::RankingFeat::iScore, IsHumanPlayer(), m_PlayMode, Style::m_StepsType, StatsManager::m_vPlayedStageStats, PLAY_MODE_REGULAR, PlayModeToString(), PROFILE_RECORD_FEATS, PROFILEMAN, SongAndSteps::pSong, GameState::RankingFeat::pSong, SongAndSteps::pSteps, GameState::RankingFeat::pSteps, RANKING_TO_FILL_IN_MARKER, GameState::RankingFeat::SONG, ssprintf(), STATSMAN, GameState::RankingFeat::Type, and HighScoreList::vHighScores.
Referenced by AnyPlayerHasRankingFeats().
GetSongPercent()
float GameState::GetSongPercent (float beat) const
References Song::GetFirstSecond(), Song::GetLastSecond(), m_pCurSong, Song::m_SongTiming, and TimingData::WhereUAtBro().
Referenced by LunaGameState::GetSongPercent().
GetStageResult()
StageResult GameState::GetStageResult (PlayerNumber pn) const
References FOREACH_PlayerNumber, StatsManager::m_CurStageStats, PlayerStageStats::m_iActualDancePoints, StageStats::m_player, RESULT_DRAW, RESULT_LOSE, RESULT_WIN, and STATSMAN.
Referenced by GetBestPlayer(), LunaGameState::GetStageResult(), ScreenEvaluation::Init(), LunaGameState::IsDraw(), and LunaGameState::IsWinner().
HaveProfileToLoad()
bool GameState::HaveProfileToLoad ()
References FOREACH_HumanPlayer, ProfileManager::IsPersistentProfile(), ProfileManager::m_sDefaultLocalProfileID, and PROFILEMAN.
Referenced by ScreenProfileLoad::BeginScreen(), and ScreenSelectMusic::HandleMessage().
HaveProfileToSave()
bool GameState::HaveProfileToSave ()
References FOREACH_HumanPlayer, ProfileManager::IsPersistentProfile(), and PROFILEMAN.
Referenced by LunaScreenProfileSave::HaveProfileToSave().
IsCpuPlayer()
bool GameState::IsCpuPlayer (PlayerNumber pn) const
References IsHumanPlayer(), and IsPlayerEnabled().
Referenced by BeginStage(), GetNextCpuPlayer(), ScreenGameplay::LoadNextSong(), and ScreenGameplay::Update().
IsEditing()
bool GameState::IsEditing () const inline
References EditMode_Invalid.
Referenced by NoteField::DrawBeatBar(), NoteField::DrawPrimitives(), ArrowEffects::GetBrightness(), ScreenPlayerOptions::Init(), Player::Load(), OptionRowHandlerListSteps::Reload(), and AdjustSync::SaveSyncChanges().
IsEventMode()
bool GameState::IsEventMode () const
References PrefsManager::m_bEventMode, m_bTemporaryEventMode, and PREFSMAN.
Referenced by ProfileManager::AddStepsScore(), BeginStage(), HandleInputEvents(), and ScreenSelectMusic::SelectCurrent().
IsHumanPlayer()
bool GameState::IsHumanPlayer (PlayerNumber pn) const
Is the specified Player a human Player?
Parameters
pn the numbered Player to check.
Returns
true if it's a human Player, or false otherwise.
References FAIL_M, GetCurrentGame(), GetCurrentStyle(), GetMasterPlayerNumber(), m_bSideIsJoined, Style::m_StyleType, PLAYER_INVALID, ssprintf(), StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, and StyleType_TwoPlayersTwoSides.
Referenced by BeginnerHelper::AddPlayer(), ScreenOptions::AfterChangeValueOrRow(), OptionRow::AfterImportOptions(), ScreenSelectMusic::AfterStepsOrTrailChange(), ScreenContinue::BeginScreen(), ScreenSelectMaster::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenOptions::BeginScreen(), ScreenSelectMaster::ChangePage(), ScreenSelectMaster::ChangeSelection(), ScreenSelectMusic::ChangeSteps(), CurrentOptionsDisqualifyPlayer(), BeginnerHelper::DrawPrimitives(), ScreenSelectProfile::Finish(), LunaStatsManager::GetFinalGrade(), GetNextHumanPlayer(), GetNextPotentialCpuPlayer(), GetPlayerDisplayName(), GetRankingFeats(), ScreenOptionsMaster::ImportOptions(), ScreenOptions::Init(), ScreenPlayerOptions::Input(), ScreenContinue::Input(), ScreenSelectMusic::Input(), ScreenOptions::Input(), ScreenGameplay::Input(), IsCpuPlayer(), IsPlayerEnabled(), ScreenGameplay::LoadNextSong(), ScreenOptions::PositionRows(), OptionRow::PositionUnderlines(), ScreenOptions::RestartOptions(), BrightnessOverlay::SetActualBrightness(), ScreenSelectProfile::SetProfileIndex(), ScreenOptions::TweenCursor(), ScreenSelectMaster::TweenOnScreen(), ScreenPlayerOptions::UpdateDisqualified(), and StepsDisplayList::UpdatePositions().
IsMultiPlayerEnabled()
bool GameState::IsMultiPlayerEnabled (MultiPlayer mp) const
References m_MultiPlayerStatus, and MultiPlayerStatus_Joined.
Referenced by GetNextEnabledMultiPlayer(), ScreenGameplay::Input(), PlayerInfo::IsEnabled(), IsPlayerEnabled(), and ScoreDisplayAliveTime::UpdateNumber().
IsPlayerEnabled() [1/2]
bool GameState::IsPlayerEnabled (PlayerNumber pn) const
References IsHumanPlayer().
Referenced by DancingCharacters::DancingCharacters(), GetFirstDisabledPlayer(), GetNextEnabledPlayer(), GetPlayerDisplayName(), ScreenContinue::HandleMessage(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenEvaluation::Init(), ScreenGameplay::Init(), ScreenSelect::Input(), IsCpuPlayer(), PlayerInfo::IsEnabled(), IsPlayerEnabled(), LifeMeterBattery::Load(), DancingCharacters::LoadNextSong(), ScreenNetSelectMusic::MenuDown(), SMOProtocol::ProcessInput(), SMOProtocol::StartRequest(), ScoreDisplayOni::Update(), DancingCharacters::Update(), Player::Update(), ScoreDisplayAliveTime::UpdateNumber(), and MusicWheel::UpdateSwitch().
IsPlayerEnabled() [2/2]
bool GameState::IsPlayerEnabled (const PlayerState * pPlayerState) const
References IsMultiPlayerEnabled(), IsPlayerEnabled(), PlayerState::m_mp, PlayerState::m_PlayerNumber, MultiPlayer_Invalid, and PLAYER_INVALID.
IsPlaylistCourse()
bool GameState::IsPlaylistCourse () inline
References isplaylistcourse.
Referenced by ScreenSelectMusic::BeginScreen(), ScreenGameplay::HandleScreenMessage(), AdjustSync::HandleSongEnd(), ScreenGameplay::InitSongQueues(), ScreenSyncOverlay::Input(), and AdjustSync::IsSyncDataChanged().
IsTimeToPlayAttractSounds()
bool GameState::IsTimeToPlayAttractSounds () const
References ASF_NEVER, PrefsManager::m_AttractSoundFrequency, m_iNumTimesThroughAttract, and PREFSMAN.
Referenced by ScreenAttract::SetAttractVolume().
JoinInput()
bool GameState::JoinInput (PlayerNumber pn)
References Preference< T >::Get(), JoinPlayers(), and m_bAutoJoin.
Referenced by ScreenContinue::Input(), ScreenSelect::Input(), and LunaGameState::JoinInput().
JoinPlayer()
void GameState::JoinPlayer (PlayerNumber pn)
References BeginGame(), MessageManager::Broadcast(), GAMEMAN, GetCurrentStyle(), GameManager::GetFirstCompatibleStyle(), GetMasterPlayerNumber(), GetNumSidesJoined(), m_bSideIsJoined, m_pCurGame, Style::m_StepsType, Style::m_StyleType, Message_PlayerJoined, MessageIDToString(), MESSAGEMAN, PLAYER_1, PLAYER_INVALID, SetCurrentStyle(), SetMasterPlayerNumber(), Message::SetParam(), StepsType_dance_solo, StepsType_dance_threepanel, StepsType_popn_nine, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, and StyleType_TwoPlayersTwoSides.
Referenced by ApplyCmdline(), GameCommand::ApplySelf(), ScreenOptionsMaster::Init(), ScreenPackages::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), LunaGameState::JoinPlayer(), and ScreenSelectProfile::SetProfileIndex().
JoinPlayers()
bool GameState::JoinPlayers ()
References FOREACH_PlayerNumber.
Referenced by JoinInput().
LoadCurrentSettingsFromProfile()
void GameState::LoadCurrentSettingsFromProfile (PlayerNumber pn)
References ApplyPreferredModifiers(), Difficulty_Invalid, Profile::GetDefaultModifiers(), ProfileManager::GetProfile(), ProfileManager::IsPersistentProfile(), Profile::m_LastDifficulty, Profile::m_lastSong, Profile::m_LastStepsType, m_pCurGame, m_pPlayerState, m_pPreferredSong, m_PreferredDifficulty, m_PreferredSortOrder, m_PreferredStepsType, Profile::m_SortOrder, ModsLevel_Preferred, PO_GROUP_CALL, PROFILEMAN, BroadcastOnChange< T >::Set(), SortOrder_Invalid, StepsType_Invalid, and SongID::ToSong().
Referenced by ScreenSelectProfile::Finish(), and LoadProfiles().
LoadProfiles()
void GameState::LoadProfiles (bool bLoadEdits = true)
References FOREACH_HumanPlayer, ProfileManager::GetProfile(), ProfileManager::IsPersistentProfile(), LoadCurrentSettingsFromProfile(), ProfileManager::LoadFirstAvailableProfile(), Profile::m_iTotalSessions, and PROFILEMAN.
Referenced by ScreenProfileLoad::Continue(), ScreenSelectMusic::HandleMessage(), and LunaGameState::LoadProfiles().
OneIsHot()
bool GameState::OneIsHot () const
References FOREACH_EnabledPlayer, HealthState_Hot, and m_pPlayerState.
Referenced by ScreenGameplay::Update().
operator=()
GameState& GameState::operator= (const GameState & rhs) private
PlayerIsUsingModifier()
bool GameState::PlayerIsUsingModifier (PlayerNumber pn, const RString & sModifier)
References SongOptions::FromString(), PlayerOptions::FromString(), ModsGroup< T >::GetCurrent(), PlayerState::m_PlayerOptions, m_pPlayerState, and m_SongOptions.
PlayersCanJoin()
bool GameState::PlayersCanJoin () const
Determine if a second player can join in at this time.
Returns
true if a player can still enter the game, false otherwise.
PushSelf()
void GameState::PushSelf (lua_State * L)
Referenced by GameState().
Reset()
void GameState::Reset ()
Reset the GameState back to initial values.
References ApplyCmdline(), ASSERT, EditMode_Invalid, FOREACH_MultiPlayer, FOREACH_PlayerNumber, g_RandomNumberGenerator, GetDefaultSong(), GetDefaultSort(), GROUP_ALL, ModsGroup< T >::Init(), m_AdjustTokensBySongCostForFinalStageCheck, m_bDemonstrationOrJukebox, m_bFailTypeWasExplicitlySet, m_bGameplayLeadIn, m_bJukeboxUsesModifiers, m_bLoadingNextSong, m_bMultiplayer, m_bTemporaryEventMode, m_EditMode, m_Environment, m_iCurrentStageIndex, m_iGameSeed, m_iNumMultiplayerNoteFields, m_iNumStagesOfThisSong, m_iStageSeed, m_MultiPlayerStatus, m_paused, m_pCurGame, m_pCurSong, m_PlayMode, m_pMultiPlayerState, m_pPreferredSong, m_PreferredSortOrder, m_SongOptions, m_SortOrder, m_sPreferredSongGroup, m_timeGameStarted, MultiPlayerStatus_NotJoined, NOTESKIN, PLAYER_INVALID, PlayMode_Invalid, NoteSkinManager::RefreshNoteSkinData(), StatsManager::Reset(), PlayerState::Reset(), ResetMusicStatistics(), AdjustSync::ResetOriginalSyncData(), ResetStageStatistics(), BroadcastOnChange< T >::Set(), BroadcastOnChangePtr< T >::Set(), SetCurrentStyle(), SetMasterPlayerNumber(), RageTimer::SetZero(), sExpandedSectionName, SONGMAN, SortOrder_Invalid, STATSMAN, THEME, UnjoinPlayer(), and SongManager::UpdateShuffled().
Referenced by ScreenAttract::BeginScreen(), HandleGlobalInputs(), ScreenHowToPlay::HandleScreenMessage(), LunaGameState::Reset(), StepMania::ResetGame(), and ScreenTitleMenu::ScreenTitleMenu().
ResetMusicStatistics()
void GameState::ResetMusicStatistics ()
References FOREACH_PlayerNumber, m_LastPositionSeconds, m_LastPositionTimer, PlayerState::m_Position, m_Position, m_pPlayerState, SongPosition::Reset(), Actor::SetBGMTime(), and RageTimer::Touch().
Referenced by ScreenGameplay::LoadNextSong(), and Reset().
ResetOptions()
void GameState::ResetOptions ()
ResetPlayer()
void GameState::ResetPlayer (PlayerNumber pn)
References Difficulty_Invalid, m_iPlayerStageTokens, m_pCurSteps, m_pPlayerState, m_PreferredDifficulty, m_PreferredStepsType, PROFILEMAN, PlayerState::Reset(), ResetPlayerOptions(), BroadcastOnChange< T >::Set(), StepsType_Invalid, and ProfileManager::UnloadProfile().
Referenced by ScreenContinue::BeginScreen(), and UnjoinPlayer().
ResetPlayerOptions()
void GameState::ResetPlayerOptions (PlayerNumber pn)
References ModsGroup< T >::Assign(), GetDefaultPlayerOptions(), PlayerState::m_PlayerOptions, m_pPlayerState, and ModsLevel_Preferred.
Referenced by ResetPlayer(), and LunaGameState::ResetPlayerOptions().
ResetStageStatistics()
void GameState::ResetStageStatistics ()
Call this function when it's time to play a new stage.
References FOREACH_PlayerNumber, g_RandomNumberGenerator, ProfileManager::GetProfile(), HealthState_Alive, PrefsManager::m_bComboContinuesBetweenSongs, StatsManager::m_CurStageStats, m_fOpponentHealthPercent, m_fTugLifePercentP1, PlayerState::m_HealthState, PlayerStageStats::m_iCurCombo, Profile::m_iCurrentCombo, m_iCurrentStageIndex, m_iStageSeed, StageStats::m_player, m_pPlayerState, m_vLastPeakComboAwards, m_vLastStageAwards, PREFSMAN, PROFILEMAN, and STATSMAN.
Referenced by BeginStage(), CancelStage(), and Reset().
ResetToDefaultSongOptions()
void GameState::ResetToDefaultSongOptions (ModsLevel l)
References ModsGroup< T >::Assign(), GetDefaultSongOptions(), and m_SongOptions.
Referenced by OptionsList::Start().
SaveCurrentSettingsToProfile()
void GameState::SaveCurrentSettingsToProfile (PlayerNumber pn)
Save the specified player's settings to his/her profile.
This is called at the beginning of each stage.
Parameters
pn the PlayerNumber to save the stats to.
References Difficulty_Invalid, SongID::FromSong(), ProfileManager::GetProfile(), ProfileManager::IsPersistentProfile(), IsSongSort(), m_bDemonstrationOrJukebox, Profile::m_LastDifficulty, Profile::m_lastSong, Profile::m_LastStepsType, m_pCurGame, m_pPlayerState, m_pPreferredSong, m_PreferredDifficulty, m_PreferredSortOrder, m_PreferredStepsType, Profile::m_SortOrder, PROFILEMAN, Profile::SetDefaultModifiers(), and StepsType_Invalid.
Referenced by DebugLineWriteProfiles::DoAndLog(), and Profile::SaveAllToDir().
SaveLocalData()
void GameState::SaveLocalData ()
SavePlayerProfile()
void GameState::SavePlayerProfile (PlayerNumber pn)
References ProfileManager::IsPersistentProfile(), m_pPlayerState, PC_HUMAN, PROFILEMAN, and ProfileManager::SaveProfile().
Referenced by DebugLineWriteProfiles::DoAndLog(), and SavePlayerProfiles().
SavePlayerProfiles()
void GameState::SavePlayerProfiles ()
References FOREACH_HumanPlayer, and SavePlayerProfile().
Referenced by ScreenProfileSave::Continue(), and LunaGameState::SaveProfiles().
SetCompatibleStyle()
bool GameState::SetCompatibleStyle (StepsType stype, PlayerNumber pn)
References CommonMetrics::AUTO_SET_STYLE, GAMEMAN, GetCurrentStyle(), GameManager::GetFirstCompatibleStyle(), GetNumSidesJoined(), m_pCurGame, Style::m_StepsType, and SetCurrentStyle().
Referenced by LunaGameState::SetCompatibleStyleOrError().
SetCompatibleStylesForPlayers()
void GameState::SetCompatibleStylesForPlayers ()
References FOREACH_EnabledPlayer, GAMEMAN, GameManager::GetFirstCompatibleStyle(), GetNumSidesJoined(), GameManager::GetStepsTypesForGame(), m_pCurGame, m_pCurSteps, SetCurrentStyle(), and StepsType_Invalid.
Referenced by ScreenSelectMusic::BeginScreen(), and ScreenSelectMusic::SelectCurrent().
SetCurGame()
void GameState::SetCurGame (const Game * pGame)
State what the current game is.
Call this instead of m_pCurGame.Set to make sure that PREFSMAN->m_sCurrentGame stays in sync.
Parameters
pGame the game to start using.
References discordInit(), m_pCurGame, Game::m_szName, PREFSMAN, BroadcastOnChangePtr< T >::Set(), PrefsManager::SetCurrentGame(), and updateDiscordPresenceMenu().
Referenced by StepMania::InitializeCurrentGame(), and SMOProtocol::ProcessInput().
SetCurrentStyle()
void GameState::SetCurrentStyle (const Style * style, PlayerNumber pn)
References FOREACH_PlayerNumber, GetCurrentGame(), GetCurrentStyle(), GetMasterPlayerNumber(), GetNumSidesJoined(), INPUTMAPPER, m_pCurStyle, m_SeparatedStyles, OPPOSITE_PLAYER, PLAYER_INVALID, BroadcastOnChangePtr< T >::Set(), InputMapper::SetJoinControllers(), StyleType_OnePlayerTwoSides, and UnjoinPlayer().
Referenced by GameCommand::ApplySelf(), ScreenContinue::BeginScreen(), ScreenSelectMusic::BeginScreen(), ForceSharedSidesMatch(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), JoinPlayer(), SMOProtocol::ProcessInput(), Reset(), SetCompatibleStyle(), SetCompatibleStylesForPlayers(), and LunaGameState::SetCurrentStyle().
SetMasterPlayerNumber()
void GameState::SetMasterPlayerNumber (const PlayerNumber p)
Set the master player number.
Parameters
p the master player number.
References masterPlayerNumber.
Referenced by ScreenHowToPlay::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), JoinPlayer(), Reset(), and UnjoinPlayer().
SetNewStageSeed()
void GameState::SetNewStageSeed ()
References g_RandomNumberGenerator, and m_iStageSeed.
SetPaused()
void GameState::SetPaused (bool p) inline
References m_paused.
Referenced by ScreenGameplay::Init(), and ScreenGameplay::ToggleReplayPause().
SetProcessedTimingData()
void GameState::SetProcessedTimingData (TimingData * t)
Set the timing data to be used with processing.
Parameters
t the timing data.
References processedTiming.
Referenced by Steps::CalculateRadarValues(), Player::CrossedRows(), ScoreKeeperNormal::Load(), ScoreKeeperNormal::OnNextSong(), and ScreenGameplay::SaveStats().
ShowW1()
bool GameState::ShowW1 () const
Do we show the W1 timing judgment?
Returns
true if we do, or false otherwise.
References ALLOW_W1_EVERYWHERE, ALLOW_W1_NEVER, FAIL_M, PrefsManager::m_AllowW1, PREFSMAN, and ssprintf().
Referenced by ScoreKeeperNormal::AddScoreInternal(), ScreenEvaluation::Init(), Player::Step(), ScoreKeeperNormal::TapNoteScoreToDancePoints(), and ScoreKeeperNormal::TapNoteScoreToGradePoints().
StoreRankingName()
void GameState::StoreRankingName (PlayerNumber pn, RString name)
UnjoinPlayer()
void GameState::UnjoinPlayer (PlayerNumber pn)
References ModsGroup< T >::Assign(), MessageManager::Broadcast(), FOREACH_HumanPlayer, GetDefaultSongOptions(), GetMasterPlayerNumber(), m_bDidModeChangeNoteSkin, m_bSideIsJoined, m_iPlayerStageTokens, m_SongOptions, Message_PlayerUnjoined, MessageIDToString(), MESSAGEMAN, ModsLevel_Preferred, PLAYER_INVALID, ResetPlayer(), SetMasterPlayerNumber(), Message::SetParam(), STATSMAN, and StatsManager::UnjoinPlayer().
Referenced by ScreenContinue::BeginScreen(), Reset(), SetCurrentStyle(), ScreenSelectProfile::SetProfileIndex(), and LunaGameState::UnjoinPlayer().
Update()
void GameState::Update (float fDelta)
References FOREACH_PlayerNumber, m_pPlayerState, m_SongOptions, PlayerState::Update(), and ModsGroup< T >::Update().
Referenced by GameLoop::RunGameLoop().
updateDiscordPresence()
void GameState::updateDiscordPresence (const RString & largeImageText, const RString & details, const RString & state, const int64_t endTime)
Referenced by LunaGameState::UpdateDiscordPresence().
updateDiscordPresenceMenu()
void GameState::updateDiscordPresenceMenu (const RString & largeImageText)
Referenced by SetCurGame(), and LunaGameState::UpdateDiscordMenu().
UpdateSongPosition()
void GameState::UpdateSongPosition (float fPositionSeconds, const TimingData & timing, const RageTimer & timestamp = RageZeroTimer)
References RageTimer::Ago(), FOREACH_EnabledPlayer, ModsGroup< T >::GetSong(), SongOptions::m_fMusicRate, SongPosition::m_fMusicSecondsVisible, SongPosition::m_fSongBeatNoOffset, SongPosition::m_fSongBeatVisible, m_LastPositionSeconds, m_LastPositionTimer, m_paused, m_pCurSteps, PlayerState::m_Position, m_Position, m_pPlayerState, m_SongOptions, Actor::SetBGMTime(), Actor::SetPlayerBGMBeat(), RageTimer::Touch(), and SongPosition::UpdateSongPosition().
Referenced by ScreenHowToPlay::Update(), GameSoundManager::Update(), and ScreenGameplay::UpdateSongPosition().
VisitAttractScreen()
void GameState::VisitAttractScreen (const RString sScreenName)
References CommonMetrics::FIRST_ATTRACT_SCREEN, and m_iNumTimesThroughAttract.
Referenced by ScreenAttract::BeginScreen().
Member Data Documentation
DisableChordCohesion
Preference< bool > GameState::DisableChordCohesion static
Referenced by CountNotesSeparately().
isplaylistcourse
bool GameState::isplaylistcourse = false
Referenced by ScreenSelectMusic::BeginScreen(), AdjustSync::GetSyncChangeTextSong(), ScreenGameplay::HandleScreenMessage(), IsPlaylistCourse(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
m_AdjustTokensBySongCostForFinalStageCheck
bool GameState::m_AdjustTokensBySongCostForFinalStageCheck
Referenced by Reset(), ScreenEvaluation::ScreenEvaluation(), ScreenGameplay::ScreenGameplay(), ScreenEvaluation::~ScreenEvaluation(), and ScreenGameplay::~ScreenGameplay().
m_bAutoJoin
Preference< bool > GameState::m_bAutoJoin static
Referenced by JoinInput().
m_bDemonstrationOrJukebox
bool GameState::m_bDemonstrationOrJukebox
Are we in the demonstration or jukebox mode?
ScreenGameplay often does special things when this is set to true.
Referenced by BeginStage(), CommitStageStats(), GameState(), Player::HandleHoldScore(), ScoreKeeperNormal::HandleTapRowScore(), Player::HandleTapRowScore(), ScreenHowToPlay::Init(), ScreenGameplay::Init(), ScreenGameplay::LoadNextSong(), ScreenGameplay::PlayAnnouncer(), Reset(), SaveCurrentSettingsToProfile(), SMOProtocol::StartRequest(), and Player::Update().
m_bDidModeChangeNoteSkin
bool GameState::m_bDidModeChangeNoteSkin { false }
Did the current game mode change the default Noteskin?
This is true if it has: see Edit/Sync Songs for a common example. Note: any mode that wants to use this must set it explicitly.
Referenced by UnjoinPlayer().
m_bDopefish
bool GameState::m_bDopefish
Referenced by LunaGameState::Dopefish(), GameState(), and sm_main().
m_bFailTypeWasExplicitlySet
bool GameState::m_bFailTypeWasExplicitlySet
Referenced by ScreenSongOptions::ExportOptions(), Reset(), and LunaGameState::SetFailTypeExplicitlySet().
m_bGameplayLeadIn
BroadcastOnChange<bool> GameState::m_bGameplayLeadIn
Referenced by ScreenGameplay::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenGameplayLesson::Init(), ScreenHowToPlay::Init(), ScreenGameplay::Init(), Reset(), DancingCharacters::Update(), and BrightnessOverlay::Update().
m_bInNetGameplay
bool GameState::m_bInNetGameplay = false
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), and ScreenGameplay::ScreenGameplay().
m_bIsUsingStepTiming
bool GameState::m_bIsUsingStepTiming { true }
Is the game right now using Song timing or Steps timing?
Different options are available depending on this setting.
Referenced by NoteField::DrawPrimitives(), PlayerState::GetDisplayedPosition(), and ArrowEffects::Update().
m_bJukeboxUsesModifiers
bool GameState::m_bJukeboxUsesModifiers
Referenced by Reset(), and LunaGameState::SetJukeboxUsesModifiers().
m_bLoadingNextSong
bool GameState::m_bLoadingNextSong
Referenced by GetLoadingCourseSongIndex(), ScreenGameplay::HandleScreenMessage(), and Reset().
m_bMultiplayer
bool GameState::m_bMultiplayer
Referenced by StatsManager::CommitStatsToProfiles(), GetCourseSongIndex(), SongUtil::GetPlayableStepsTypes(), HandleInputEvents(), Player::Init(), ScreenGameplay::Init(), ScreenGameplay::InitSongQueues(), ScreenGameplay::Input(), ScreenGameplay::LoadNextSong(), and Reset().
m_bSideIsJoined
bool GameState::m_bSideIsJoined[NUM_PLAYERS]
Determine which side is joined.
The left side is player 1, and the right side is player 2.
Referenced by GameState(), GetNumSidesJoined(), IsHumanPlayer(), JoinPlayer(), and UnjoinPlayer().
m_bTemporaryEventMode
bool GameState::m_bTemporaryEventMode
Referenced by IsEventMode(), Reset(), LunaGameState::SetTemporaryEventMode(), and ScreenNetSelectMusic::StartSelectedSong().
m_DanceDuration
float GameState::m_DanceDuration
Referenced by ScreenGameplay::HandleScreenMessage().
m_DanceStartTime
RageTimer GameState::m_DanceStartTime
Referenced by ScreenGameplay::HandleScreenMessage().
m_EditMode
EditMode GameState::m_EditMode
Referenced by NoteField::DrawPrimitives(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::MenuUp(), and Reset().
m_Environment
LuaTable* GameState::m_Environment
Referenced by GameCommand::ApplySelf(), LunaGameState::Env(), GameState(), Reset(), and ~GameState().
m_fOpponentHealthPercent
float GameState::m_fOpponentHealthPercent
Referenced by ScreenGameplay::PlayAnnouncer(), ResetStageStatistics(), and ScreenGameplay::Update().
m_fTugLifePercentP1
float GameState::m_fTugLifePercentP1
Referenced by ResetStageStatistics().
m_iCurrentStageIndex
int GameState::m_iCurrentStageIndex
Increase this every stage while not resetting on a continue.
This is cosmetic: it's not use for Stage or Screen branching logic.
Referenced by FinishStage(), ScreenGameplayLesson::Init(), ScreenEvaluation::Init(), Reset(), and ResetStageStatistics().
m_iGameSeed
int GameState::m_iGameSeed
Referenced by GameState(), LunaGameState::GetGameSeed(), and Reset().
m_iNumMultiplayerNoteFields
int GameState::m_iNumMultiplayerNoteFields
Referenced by ScreenGameplay::InitSongQueues(), and Reset().
m_iNumStagesOfThisSong
int GameState::m_iNumStagesOfThisSong
Referenced by BeginStage(), CancelStage(), FinishStage(), and Reset().
m_iNumTimesThroughAttract
int GameState::m_iNumTimesThroughAttract
Referenced by BeginGame(), GameState(), IsTimeToPlayAttractSounds(), and VisitAttractScreen().
m_iPlayerStageTokens
int GameState::m_iPlayerStageTokens[NUM_PLAYERS]
The number of stages available for the players.
This resets whenever a player joins or continues.
Referenced by AddStageToPlayer(), ScreenContinue::BeginScreen(), BeginStage(), CancelStage(), ScreenGameplayLesson::Init(), ScreenEvaluation::Init(), ResetPlayer(), ScreenGameplay::StageFinished(), and UnjoinPlayer().
m_iStageSeed
int GameState::m_iStageSeed
Referenced by GameState(), LunaGameState::GetStageSeed(), GetTrackMapping(), ArrowEffects::GetYOffset(), Reset(), ResetStageStatistics(), and SetNewStageSeed().
m_LastPositionSeconds
float GameState::m_LastPositionSeconds private
Referenced by ResetMusicStatistics(), and UpdateSongPosition().
m_LastPositionTimer
RageTimer GameState::m_LastPositionTimer private
Referenced by ResetMusicStatistics(), and UpdateSongPosition().
m_MultiPlayerStatus
MultiPlayerStatus GameState::m_MultiPlayerStatus[NUM_MultiPlayer]
Referenced by IsMultiPlayerEnabled(), and Reset().
m_paused
bool GameState::m_paused private
Referenced by GetPaused(), Reset(), SetPaused(), and UpdateSongPosition().
m_pCurCharacters
Character* GameState::m_pCurCharacters[NUM_PLAYERS]
Referenced by BeginnerHelper::AddPlayer(), GameCommand::ApplySelf(), DancingCharacters::DancingCharacters(), GameCommand::DescribesCurrentMode(), and BeginnerHelper::Init().
m_pCurGame
BroadcastOnChangePtr<const Game> GameState::m_pCurGame
Referenced by ScreenSelectMusic::BeginScreen(), DebugLineReloadTheme::DoAndLog(), NoteSkinManager::DoesNoteSkinExist(), GameState(), GetCurrentGame(), NoteSkinManager::GetDefaultNoteSkinName(), NoteSkinManager::GetNoteSkinNames(), SongUtil::GetPlayableStepsTypes(), HandleGlobalInputs(), ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), ScreenGameplay::Input(), JoinPlayer(), LoadCurrentSettingsFromProfile(), OptionRowHandlerListStyles::LoadInternal(), OptionRowHandlerListDifficulties::LoadInternal(), GameCommand::LoadOne(), SMOProtocol::ProcessInput(), ThemeMetricStepsTypesToShow::Read(), LunaGameState::RefreshNoteSkinData(), Reset(), SaveCurrentSettingsToProfile(), SetCompatibleStyle(), SetCompatibleStylesForPlayers(), SetCurGame(), LunaGameState::SetCurrentStyle(), and MusicWheel::SetOpenSection().
m_pCurSong
BroadcastOnChangePtr<Song> GameState::m_pCurSong
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::AfterStepsOrTrailChange(), GameCommand::ApplySelf(), AdjustSync::AutosyncOffset(), AdjustSync::AutosyncTempo(), ScreenOptionsCourseOverview::BeginScreen(), ScreenGameplay::BeginScreen(), CanSafelyEnterGameplay(), ScreenSelectMusic::ChangeSteps(), CurrentOptionsDisqualifyPlayer(), GameCommand::DescribesCurrentMode(), DebugLineConvertXML::DoAndLog(), NoteField::DrawPrimitives(), StageStats::FinalizeScores(), AutoKeysounds::FinishLoading(), LunaGameState::GetCurrentSong(), LunaGameState::GetCurrentStepsCredits(), PlayerState::GetDisplayedTiming(), SongManager::GetExtraStageInfo(), ScreenGameplay::GetMusicEndTiming(), GetNumStagesForCurrentSongAndStepsOrCourse(), PaneDisplay::GetPaneTextAndLevel(), GetPromptText(), OptionRow::GetRowTitle(), GetSongPercent(), AdjustSync::GetSyncChangeTextSong(), ScreenEvaluation::HandleMenuStart(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenGameplayLesson::Init(), ScreenHowToPlay::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), ScreenGameplay::InitSongQueues(), ScreenSyncOverlay::Input(), ScreenSelectMusic::Input(), PlayerOptions::IsEasierForSongAndSteps(), Player::Load(), AutoKeysounds::LoadAutoplaySoundsInto(), BGAnimationLayer::LoadFromAniLayerFile(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), DancingCharacters::LoadNextSong(), ScreenGameplay::LoadNextSong(), GameCommand::LoadOne(), ScreenNetSelectMusic::MenuDown(), ScreenNetSelectMusic::MusicChanged(), LifeMeterTime::OnLoadSong(), ScoreKeeperNormal::OnNextSong(), ScreenGameplay::PlayAnnouncer(), OptionRowHandlerListSteps::Reload(), MusicWheel::ReloadSongList(), Reset(), AdjustSync::ResetOriginalSyncData(), AdjustSync::RevertSyncChanges(), ScreenGameplay::SaveReplay(), ScreenGameplay::SaveStats(), AdjustSync::SaveSyncChanges(), ScreenNetSelectMusic::SelectCurrent(), MusicWheel::SelectSongOrCourse(), SMOProtocol::SelectUserSong(), ETTProtocol::SelectUserSong(), NetworkSyncManager::SelectUserSong(), ScreenGameplay::SendCrossedMessages(), Player::SetCombo(), LunaGameState::SetCurrentSong(), StepsDisplayList::SetFromGameState(), BPMDisplay::SetFromGameState(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::StartPlayingSong(), SMOProtocol::StartRequest(), ScreenNetSelectMusic::StartSelectedSong(), ScreenGameplay::ToggleReplayPause(), LyricDisplay::Update(), ScreenHowToPlay::Update(), GameSoundManager::Update(), SongMeterDisplay::Update(), DancingCharacters::Update(), Player::Update(), ScreenGameplay::Update(), ScreenNetSelectMusic::UpdateDifficulties(), ScreenGameplay::UpdateSongPosition(), ScreenNetEvaluation::UpdateStats(), ScreenSyncOverlay::UpdateText(), SongUtil::ValidateCurrentSongPreview(), and SongUtil::ValidateCurrentStepsChartName().
m_pCurSteps
BroadcastOnChangePtr1D<Steps, NUM_PLAYERS> GameState::m_pCurSteps
Referenced by ScreenSelectMusic::AfterStepsOrTrailChange(), GameCommand::ApplySelf(), PlayerStageStats::CalcSSR(), CanSafelyEnterGameplay(), ScreenSelectMusic::CheckBackgroundRequests(), CurrentOptionsDisqualifyPlayer(), GameCommand::DescribesCurrentMode(), DetermineScoreEligibility(), FillInHighScore(), StageStats::FinalizeScores(), ForceOtherPlayersToCompatibleSteps(), ForceSharedSidesMatch(), StepsDisplayList::GetCurrentRowIndex(), LunaGameState::GetCurrentSteps(), LunaGameState::GetCurrentStepsCredits(), PlayerState::GetDisplayedTiming(), GetEasiestStepsDifficulty(), GetHardestStepsDifficulty(), PaneDisplay::GetPaneTextAndLevel(), ArrowEffects::GetYOffset(), ScoreKeeperNormal::HandleComboInternal(), ScreenEvaluation::HandleMenuStart(), ScreenSelectMusic::HandleMessage(), ScoreKeeperNormal::HandleRowComboInternal(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), OptionRowHandlerStepsType::ImportOption(), ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), ScreenEvaluation::Init(), BackgroundImpl::Init(), ScreenGameplay::Init(), ScreenGameplay::InitSongQueues(), ScreenSyncOverlay::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), LunaProfile::IsCurrentChartPermamirror(), Player::Load(), AutoKeysounds::LoadAutoplaySoundsInto(), Foreground::LoadFromSong(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerStepsType::LoadInternal(), ScreenGameplay::LoadNextSong(), AutoKeysounds::LoadTracks(), LifeMeterTime::OnLoadSong(), DownloadManager::OnLogin(), GameplayAssist::PlayTicks(), MusicWheelItem::RefreshGrades(), ResetPlayer(), ScreenGameplay::SaveReplay(), ScreenGameplay::SaveStats(), ScreenSelectMusic::SelectCurrent(), ETTProtocol::SelectUserSong(), ScreenGameplay::SendCrossedMessages(), SetCompatibleStylesForPlayers(), LunaGameState::SetCurrentSteps(), StepsDisplay::SetFromGameState(), ScreenGameplay::SetupSong(), ScreenGameplay::SongFinished(), ScreenGameplay::StartPlayingSong(), SMOProtocol::StartRequest(), ScreenNetSelectMusic::StartSelectedSong(), Player::Step(), ScreenSelectMusic::SwitchToPreferredDifficulty(), ScreenNetSelectMusic::UpdateDifficulties(), UpdateSongPosition(), SongUtil::ValidateCurrentEditStepsDescription(), SongUtil::ValidateCurrentStepsChartName(), SongUtil::ValidateCurrentStepsCredit(), SongUtil::ValidateCurrentStepsDescription(), and SongUtil::ValidateCurrentStepsMusic().
m_pCurStyle
BroadcastOnChangePtr<const Style> GameState::m_pCurStyle private
Referenced by GameState(), GetCurrentStyle(), ScreenOptionsCourseOverview::ProcessMenuStart(), and SetCurrentStyle().
m_PlayMode
BroadcastOnChange<PlayMode> GameState::m_PlayMode
Referenced by GameCommand::ApplySelf(), ScreenSelectMusic::BeginScreen(), GameCommand::DescribesCurrentMode(), GameState(), GetRankingFeats(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), GameCommand::IsPlayable(), PlayerInfo::Load(), Reset(), LunaGameState::SetCurrentPlayMode(), LunaGameState::SetCurrentStyle(), MusicWheel::SetOpenSection(), and ScreenGameplay::Update().
m_pMultiPlayerState
PlayerState* GameState::m_pMultiPlayerState[NUM_MultiPlayer]
Referenced by DebugLineAutoplay::DoAndLog(), StageStats::FinalizeScores(), GameState(), LunaGameState::GetMultiPlayerState(), PlayerInfo::GetPlayerState(), Reset(), and ~GameState().
m_Position
SongPosition GameState::m_Position
Referenced by DancingCharacters::DrawPrimitives(), PlayerState::GetDisplayedPosition(), ArrowEffects::GetYOffset(), ScreenSyncOverlay::Input(), ScreenGameplay::PlayAnnouncer(), ResetMusicStatistics(), ScreenGameplay::SendCrossedMessages(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), BeginnerHelper::ShowStepCircle(), StartMusic(), ScreenGameplay::StartPlayingSong(), ScreenHowToPlay::Step(), BeginnerHelper::Step(), ScreenGameplay::ToggleReplayPause(), LyricDisplay::Update(), ArrowEffects::Update(), Foreground::Update(), ScreenHowToPlay::Update(), GameSoundManager::Update(), SoundEffectControl::Update(), BeginnerHelper::Update(), SongMeterDisplay::Update(), DancingCharacters::Update(), BackgroundImpl::Update(), ScreenGameplay::Update(), SongBPMDisplay::Update(), and UpdateSongPosition().
m_pPlayerState
PlayerState* GameState::m_pPlayerState[NUM_PLAYERS]
Allow access to each player's PlayerState.
Referenced by AllAreInDangerOrWorse(), ApplyPreferredModifiers(), GameCommand::ApplySelf(), ApplyStageModifiers(), BeginStage(), NoteField::CacheAllUsedNoteSkins(), CodeDetector::ChangeScrollSpeed(), CurrentOptionsDisqualifyPlayer(), GameCommand::DescribesCurrentMode(), CodeDetector::DetectAndAdjustMusicOptions(), DebugLineAutoplay::DoAndLog(), NoteField::ensure_note_displays_have_skin(), ScreenSongOptions::ExportOptions(), StageStats::FinalizeScores(), GameState(), GetAllUsedNoteSkins(), GetNumCols(), PlayerInfo::GetPlayerState(), LunaGameState::GetPlayerState(), LunaScreenGameplay::GetTrueBPS(), ScreenHowToPlay::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), ScreenPlayerOptions::Input(), ScreenGameplay::Input(), BackgroundImpl::IsDangerAllVisible(), PlayerInfo::Load(), LoadCurrentSettingsFromProfile(), PlayerInfo::LoadDummyP1(), OneIsHot(), PlayerIsUsingModifier(), LunaScreenSelectMusic::PlayReplay(), GameplayAssist::PlayTicks(), ETTProtocol::ReportHighScore(), SMOProtocol::ReportPlayerOptions(), ResetMusicStatistics(), ResetPlayer(), ResetPlayerOptions(), ResetStageStatistics(), SaveCurrentSettingsToProfile(), SavePlayerProfile(), ETTProtocol::SelectUserSong(), BrightnessOverlay::SetActualBrightness(), ModIconRow::SetFromGameState(), OptionsList::Start(), SMOProtocol::StartRequest(), ArrowEffects::Update(), ScreenHowToPlay::Update(), Update(), ScreenGameplay::Update(), ScreenPlayerOptions::UpdateDisqualified(), UpdateSongPosition(), and ~GameState().
m_pPreferredSong
Song* GameState::m_pPreferredSong
Referenced by ScreenSelectMusic::AfterMusicChange(), GameCommand::ApplySelf(), LunaGameState::GetPreferredSong(), LoadCurrentSettingsFromProfile(), Reset(), SaveCurrentSettingsToProfile(), MusicWheel::SelectSongOrCourse(), LunaGameState::SetPreferredSong(), and ScreenNetSelectMusic::StartSelectedSong().
m_PreferredDifficulty
BroadcastOnChange1D<Difficulty, NUM_PLAYERS> GameState::m_PreferredDifficulty
Referenced by GameCommand::ApplySelf(), ChangePreferredDifficulty(), ChangePreferredDifficultyAndStepsType(), GameCommand::DescribesCurrentMode(), GetClosestShownDifficulty(), MusicWheel::GetPreferredSelectionForRandomOrPortal(), OptionRowHandlerSteps::ImportOption(), ScreenNetSelectMusic::Init(), LoadCurrentSettingsFromProfile(), OptionRowHandlerSteps::LoadInternal(), ScreenNetSelectMusic::MenuDown(), ScreenNetSelectMusic::MusicChanged(), MusicWheelItem::RefreshGrades(), ResetPlayer(), SaveCurrentSettingsToProfile(), StepsDisplay::SetFromGameState(), LunaGameState::SetPreferredDifficulty(), ScreenNetSelectMusic::StartSelectedSong(), ScreenSelectMusic::SwitchToPreferredDifficulty(), and MusicWheel::UpdateSwitch().
m_PreferredSortOrder
SortOrder GameState::m_PreferredSortOrder
Referenced by GameCommand::ApplySelf(), MusicWheel::BeginScreen(), MusicWheel::ChangeSort(), GameCommand::DescribesCurrentMode(), LoadCurrentSettingsFromProfile(), Reset(), SaveCurrentSettingsToProfile(), MusicWheel::Select(), and ScreenNetSelectMusic::StartSelectedSong().
m_PreferredStepsType
BroadcastOnChange<StepsType> GameState::m_PreferredStepsType
Referenced by ChangePreferredDifficultyAndStepsType(), LoadCurrentSettingsFromProfile(), ResetPlayer(), SaveCurrentSettingsToProfile(), and ScreenSelectMusic::SwitchToPreferredDifficulty().
m_sEditLocalProfileID
BroadcastOnChange<RString> GameState::m_sEditLocalProfileID
Referenced by ScreenOptionsManageProfiles::AfterChangeRow(), ScreenOptionsEditProfile::AfterChangeValueInRow(), ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsEditProfile::BeginScreen(), ScreenOptionsEditProfile::ExportOptions(), GetEditLocalProfile(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenOptionsEditProfile::HandleScreenMessage(), ScreenOptionsEditProfile::ImportOptions(), and ValidateLocalProfileName().
m_SeparatedStyles
Style const* GameState::m_SeparatedStyles[NUM_PlayerNumber] private
Referenced by GameState(), GetCurrentStyle(), and SetCurrentStyle().
m_SongOptions
ModsGroup<SongOptions> GameState::m_SongOptions
Referenced by Playlist::AddChart(), Profile::AddGoal(), ApplyPreferredModifiers(), LunaGameState::ApplyPreferredSongOptionsToOtherLevels(), GameCommand::ApplySelf(), ApplyStageModifiers(), AdjustSync::AutosyncOffset(), BeginStage(), PlayerStageStats::CalcSSR(), CompareSongPointersByMSD(), BackgroundImpl::Layer::CreateRandomBGA(), GameCommand::DescribesCurrentMode(), DebugLineAssist::DoAndLog(), DebugLineAutosync::DoAndLog(), FillInHighScore(), StageStats::FinalizeScores(), TimingData::GetBeatAndBPSFromElapsedTime(), Song::GetDisplayBpms(), DebugLineAssist::GetDisplayValue(), DebugLineAutosync::GetDisplayValue(), TimingData::GetElapsedTimeFromBeat(), Player::GetMaxStepDistanceSeconds(), LunaGameState::GetSongOptions(), LunaGameState::GetSongOptionsObject(), LunaScreenGameplay::GetTrueBPS(), ArrowEffects::GetYOffset(), AdjustSync::HandleAutosync(), ScreenEvaluation::HandleMenuStart(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), AdjustSync::HandleSongEnd(), ScreenGameplaySyncMachine::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), ScreenGameplay::Input(), DebugLineAssist::IsEnabled(), DebugLineAutosync::IsEnabled(), Player::Load(), BackgroundImpl::LoadFromSong(), ScreenGameplay::LoadNextSong(), PlayerIsUsingModifier(), LunaScreenSelectMusic::PlayReplay(), GameplayAssist::PlayTicks(), LunaDownloadManager::RequestChartLeaderBoard(), Reset(), ResetToDefaultSongOptions(), ETTProtocol::SelectUserSong(), ScreenGameplay::SetRate(), LunaGameState::SetSongOptions(), ScreenGameplay::SetSongPosition(), ScreenGameplay::SetupSong(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::StartPlayingSong(), LunaScreenSelectMusic::StartPlaylistAsCourse(), SMOProtocol::StartRequest(), Player::Step(), ScreenGameplay::ToggleReplayPause(), UnjoinPlayer(), LyricDisplay::Update(), Foreground::Update(), GameSoundManager::Update(), DancingCharacters::Update(), Update(), ScreenGameplay::Update(), BackgroundImpl::Layer::UpdateCurBGChange(), Player::UpdateHoldNotes(), UpdateSongPosition(), ScreenSyncOverlay::UpdateText(), TimingData::WhereUAtBro(), and TimingData::WhereUAtBroNoOffset().
m_SortOrder
BroadcastOnChange<SortOrder> GameState::m_SortOrder
Referenced by ScreenSelectMusic::AfterMusicChange(), MusicWheel::BeginScreen(), MusicWheel::ChangeSort(), MusicWheel::GetPreferredSelectionForRandomOrPortal(), MusicWheel::NextSort(), MusicWheel::ReloadSongList(), Reset(), MusicWheel::SelectModeMenuItem(), MusicWheel::SelectSong(), MusicWheel::SelectSongAfterSearch(), MusicWheel::SelectSongOrCourse(), MusicWheel::SetOpenSection(), ScreenNetSelectMusic::StartSelectedSong(), and MusicWheel::UpdateSwitch().
m_sPreferredSongGroup
BroadcastOnChange<RString> GameState::m_sPreferredSongGroup
Referenced by GameCommand::ApplySelf(), MusicWheel::BeginScreen(), MusicWheel::BuildWheelItemDatas(), GameCommand::DescribesCurrentMode(), SongManager::GetExtraStageInfo(), MusicWheel::GetSongList(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), Reset(), and LunaGameState::SetPreferredSongGroup().
m_sStageGUID
RString GameState::m_sStageGUID
Referenced by BeginStage().
m_timeGameStarted
RageTimer GameState::m_timeGameStarted
Referenced by BeginGame(), CommitStageStats(), GameState(), and Reset().
m_vLastPeakComboAwards
deque<PeakComboAward> GameState::m_vLastPeakComboAwards[NUM_PLAYERS]
Referenced by PlayerStageStats::CalcAwards(), and ResetStageStatistics().
m_vLastStageAwards
deque<StageAward> GameState::m_vLastStageAwards[NUM_PLAYERS]
Referenced by PlayerStageStats::CalcAwards(), and ResetStageStatistics().
m_vpsNamesThatWereFilled
vector<RString*> GameState::m_vpsNamesThatWereFilled
Referenced by BeginGame().
masterPlayerNumber
PlayerNumber GameState::masterPlayerNumber private
The player number used with Styles where one player controls both sides.
Referenced by GetMasterPlayerNumber(), and SetMasterPlayerNumber().
MUSIC_SECONDS_INVALID
const float GameState::MUSIC_SECONDS_INVALID = -5000.0f static
Referenced by BackgroundImpl::Layer::UpdateCurBGChange().
processedTiming
TimingData* GameState::processedTiming private
The TimingData that is used for processing certain functions.
Referenced by GetProcessedTimingData(), SetProcessedTimingData(), and ~GameState().
sExpandedSectionName
RString GameState::sExpandedSectionName
Referenced by GameState(), LunaGameState::GetExpandedSectionName(), MusicWheelItem::LoadFromWheelItemData(), Reset(), and MusicWheel::SetOpenSection().
The documentation for this class was generated from the following files:
GameState.h
GameState.cpp