Etterna: Banner.cpp File Reference
Banner.cpp File Reference
#include "Banner.h"
#include "ActorUtil.h"
#include "Character.h"
#include "CharacterManager.h"
#include "ImageCache.h"
#include "PrefsManager.h"
#include "RageTextureManager.h"
#include "RageUtil.h"
#include "Song.h"
#include "SongManager.h"
#include "ThemeMetric.h"
#include "global.h"
#include "LuaBinding.h"
Classes
class LunaBanner
Allow Lua to have access to the Banner.
Functions
REGISTER_ACTOR_CLASS (Banner)
Variables
ThemeMetric< bool > SCROLL_RANDOM ("Banner", "ScrollRandom")
ThemeMetric< bool > SCROLL_ROULETTE ("Banner", "ScrollRoulette")
ThemeMetric< bool > SCROLL_MODE ("Banner", "ScrollMode")
ThemeMetric< bool > SCROLL_SORT_ORDER ("Banner", "ScrollSortOrder")
ThemeMetric< float > SCROLL_SPEED_DIVISOR ("Banner", "ScrollSpeedDivisor")
Function Documentation
REGISTER_ACTOR_CLASS()
REGISTER_ACTOR_CLASS (Banner)
Variable Documentation
SCROLL_MODE
ThemeMetric<bool> SCROLL_MODE("Banner", "ScrollMode")
Referenced by Banner::LoadMode().
SCROLL_RANDOM
ThemeMetric<bool> SCROLL_RANDOM("Banner", "ScrollRandom")
Referenced by Banner::LoadRandom().
SCROLL_ROULETTE
ThemeMetric<bool> SCROLL_ROULETTE("Banner", "ScrollRoulette")
Referenced by Banner::LoadRoulette().
SCROLL_SORT_ORDER
ThemeMetric<bool> SCROLL_SORT_ORDER("Banner", "ScrollSortOrder")
Referenced by Banner::LoadFromSortOrder().
SCROLL_SPEED_DIVISOR
ThemeMetric<float> SCROLL_SPEED_DIVISOR("Banner", "ScrollSpeedDivisor")
Referenced by Banner::Update().