Etterna: LoadingWindow_MacOSX Class Reference
LoadingWindow_MacOSX Class Reference
Loading window for Mac OS X.
#include <LoadingWindow_MacOSX.h>
Public Member Functions
LoadingWindow_MacOSX ()
~LoadingWindow_MacOSX ()
void SetText (const RString &str)
void SetSplash (const RageSurface *pSplash)
void SetProgress (const int progress)
void SetTotalWork (const int totalWork)
void SetIndeterminate (bool indeterminate)
Public Member Functions inherited from LoadingWindow
virtual RString Init ()
virtual ~LoadingWindow ()=default
virtual void SetIcon (const RageSurface *pIcon)
Additional Inherited Members
Static Public Member Functions inherited from LoadingWindow
static LoadingWindow * Create ()
Protected Attributes inherited from LoadingWindow
int m_progress
int m_totalWork
bool m_indeterminate
Detailed Description
Loading window for Mac OS X.
Constructor & Destructor Documentation
LoadingWindow_MacOSX()
LoadingWindow_MacOSX::LoadingWindow_MacOSX ()
~LoadingWindow_MacOSX()
LoadingWindow_MacOSX::~LoadingWindow_MacOSX ()
References LoadingWindowHelper::m_Pool.
Member Function Documentation
SetIndeterminate()
void LoadingWindow_MacOSX::SetIndeterminate (bool indeterminate) virtual
Reimplemented from LoadingWindow.
SetProgress()
void LoadingWindow_MacOSX::SetProgress (const int progress) virtual
Reimplemented from LoadingWindow.
SetSplash()
void LoadingWindow_MacOSX::SetSplash (const RageSurface * pSplash) virtual
Reimplemented from LoadingWindow.
References f, GetDirListing(), ThemeManager::GetPathG(), LoadingWindowHelper::m_Pool, RageFile::Open(), RageFile::Read(), and THEME.
SetText()
void LoadingWindow_MacOSX::SetText (const RString & str) virtual
Implements LoadingWindow.
SetTotalWork()
void LoadingWindow_MacOSX::SetTotalWork (const int totalWork) virtual
Reimplemented from LoadingWindow.
The documentation for this class was generated from the following files:
LoadingWindow_MacOSX.h
LoadingWindow_MacOSX.mm