Etterna: DebugLineAutosync Class Reference
DebugLineAutosync Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
Type GetType () const override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineAutosync::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References AutosyncType_Machine, AutosyncType_Song, AutosyncType_Tempo, MessageManager::Broadcast(), IDebugLine::DoAndLog(), GAMESTATE, ModsGroup< T >::GetSong(), SongOptions::m_AutosyncType, GameState::m_SongOptions, Message_AutosyncChanged, MESSAGEMAN, ModsLevel_Song, NUM_AutosyncType, SO_GROUP_ASSIGN, and wrap().
GetDisplayTitle()
RString DebugLineAutosync::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References AUTOSYNC, and LocalizedString::GetValue().
GetDisplayValue()
RString DebugLineAutosync::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References AutosyncType_Machine, AutosyncType_Off, AutosyncType_Song, AutosyncType_Tempo, FAIL_M, GAMESTATE, ModsGroup< T >::GetSong(), LocalizedString::GetValue(), SongOptions::m_AutosyncType, GameState::m_SongOptions, MACHINE, OFF, SONG, ssprintf(), and SYNC_TEMPO.
GetType()
Type DebugLineAutosync::GetType () const inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::gameplay_only.
IsEnabled()
bool DebugLineAutosync::IsEnabled () inline override private virtual
Implements IDebugLine.
References AutosyncType_Off, GAMESTATE, ModsGroup< T >::GetSong(), SongOptions::m_AutosyncType, and GameState::m_SongOptions.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp