Etterna: CircBuf< T > Class Template Reference
CircBuf< T > Class Template Reference
#include <RageUtil_CircularBuffer.h>
Public Member Functions
CircBuf ()
~CircBuf ()
void swap (CircBuf &rhs)
CircBuf & operator= (const CircBuf &rhs)
CircBuf (const CircBuf &cpy)
unsigned num_readable () const
unsigned num_writable () const
unsigned capacity () const
void reserve (unsigned n, int iBlockSize=1)
void clear ()
void advance_write_pointer (int n)
void advance_read_pointer (int n)
void get_write_pointers (T *pPointers[2], unsigned pSizes[2])
T * get_write_pointer (unsigned *pSizes)
void get_read_pointers (T *pPointers[2], unsigned pSizes[2])
bool write (const T *buffer, unsigned buffer_size)
bool read (T *buffer, unsigned buffer_size)
Private Attributes
T * buf
unsigned size
unsigned m_iBlockSize
volatile unsigned read_pos
volatile unsigned write_pos
Constructor & Destructor Documentation
CircBuf() [1/2]
template<class T> CircBuf< T >::CircBuf () inline
~CircBuf()
template<class T> CircBuf< T >::~CircBuf () inline
CircBuf() [2/2]
template<class T> CircBuf< T >::CircBuf (const CircBuf< T > & cpy) inline
Member Function Documentation
advance_read_pointer()
template<class T> void CircBuf< T >::advance_read_pointer (int n) inline
Referenced by CircBuf< RageSoundDriver::sound_block >::read().
advance_write_pointer()
template<class T> void CircBuf< T >::advance_write_pointer (int n) inline
Referenced by RageSoundReader_ThreadedBuffer::FillBlock(), and CircBuf< RageSoundDriver::sound_block >::write().
capacity()
template<class T> unsigned CircBuf< T >::capacity () const inline
clear()
template<class T> void CircBuf< T >::clear () inline
Referenced by CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::reserve(), and RageSoundReader_ThreadedBuffer::SetPosition().
get_read_pointers()
template<class T> void CircBuf< T >::get_read_pointers (T * pPointers[2], unsigned pSizes[2]) inline
Referenced by CircBuf< RageSoundDriver::sound_block >::read().
get_write_pointer()
template<class T> T* CircBuf< T >::get_write_pointer (unsigned * pSizes) inline
Referenced by RageSoundReader_ThreadedBuffer::FillBlock().
get_write_pointers()
template<class T> void CircBuf< T >::get_write_pointers (T * pPointers[2], unsigned pSizes[2]) inline
Referenced by CircBuf< RageSoundDriver::sound_block >::get_write_pointer(), and CircBuf< RageSoundDriver::sound_block >::write().
num_readable()
template<class T> unsigned CircBuf< T >::num_readable () const inline
Referenced by RageSoundReader_ThreadedBuffer::GetFilledFrames().
num_writable()
template<class T> unsigned CircBuf< T >::num_writable () const inline
Referenced by RageSoundReader_ThreadedBuffer::FillBlock(), and RageSoundReader_ThreadedBuffer::GetEmptyFrames().
operator=()
template<class T> CircBuf& CircBuf< T >::operator= (const CircBuf< T > & rhs) inline
read()
template<class T> bool CircBuf< T >::read (T * buffer, unsigned buffer_size) inline
Referenced by RageSoundReader_ThreadedBuffer::Read().
reserve()
template<class T> void CircBuf< T >::reserve (unsigned n, int iBlockSize = 1) inline
Referenced by RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer().
swap()
template<class T> void CircBuf< T >::swap (CircBuf< T > & rhs) inline
Referenced by CircBuf< RageSoundDriver::sound_block >::operator=().
write()
template<class T> bool CircBuf< T >::write (const T * buffer, unsigned buffer_size) inline
Member Data Documentation
buf
template<class T> T* CircBuf< T >::buf private
Referenced by CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::get_read_pointers(), CircBuf< RageSoundDriver::sound_block >::get_write_pointers(), CircBuf< RageSoundDriver::sound_block >::reserve(), CircBuf< RageSoundDriver::sound_block >::swap(), and CircBuf< RageSoundDriver::sound_block >::~CircBuf().
m_iBlockSize
template<class T> unsigned CircBuf< T >::m_iBlockSize private
Referenced by CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::get_write_pointers(), CircBuf< RageSoundDriver::sound_block >::num_writable(), and CircBuf< RageSoundDriver::sound_block >::swap().
read_pos
template<class T> volatile unsigned CircBuf< T >::read_pos private
Referenced by CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::get_read_pointers(), CircBuf< RageSoundDriver::sound_block >::get_write_pointers(), CircBuf< RageSoundDriver::sound_block >::num_readable(), CircBuf< RageSoundDriver::sound_block >::num_writable(), and CircBuf< RageSoundDriver::sound_block >::swap().
size
template<class T> unsigned CircBuf< T >::size private
Referenced by CircBuf< RageSoundDriver::sound_block >::capacity(), CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::num_writable(), CircBuf< RageSoundDriver::sound_block >::reserve(), and CircBuf< RageSoundDriver::sound_block >::swap().
write_pos
template<class T> volatile unsigned CircBuf< T >::write_pos private
Referenced by CircBuf< RageSoundDriver::sound_block >::CircBuf(), CircBuf< RageSoundDriver::sound_block >::get_read_pointers(), CircBuf< RageSoundDriver::sound_block >::get_write_pointers(), CircBuf< RageSoundDriver::sound_block >::num_readable(), CircBuf< RageSoundDriver::sound_block >::num_writable(), and CircBuf< RageSoundDriver::sound_block >::swap().
The documentation for this class was generated from the following file:
RageUtil_CircularBuffer.h