Etterna: BGAnimationLayer.cpp File Reference
BGAnimationLayer.cpp File Reference
#include "global.h"
#include "BGAnimationLayer.h"
#include "ActorUtil.h"
#include "AutoActor.h"
#include "GameState.h"
#include "RageDisplay.h"
#include "RageMath.h"
#include "ScreenDimensions.h"
#include "Song.h"
#include "Sprite.h"
#include "ThemeManager.h"
#include "XmlFile.h"
Macros
#define MAX_TILES_WIDE static_cast<int>(SCREEN_WIDTH / 32 + 2)
#define MAX_TILES_HIGH static_cast<int>(SCREEN_HEIGHT / 32 + 2)
#define MAX_SPRITES (MAX_TILES_WIDE * MAX_TILES_HIGH)
Functions
float GetOffScreenLeft (Actor *pActor)
float GetOffScreenRight (Actor *pActor)
float GetOffScreenTop (Actor *pActor)
float GetOffScreenBottom (Actor *pActor)
bool IsOffScreenLeft (Actor *pActor)
bool IsOffScreenRight (Actor *pActor)
bool IsOffScreenTop (Actor *pActor)
bool IsOffScreenBottom (Actor *pActor)
bool IsOffScreen (Actor *pActor)
float GetGuardRailLeft (Actor *pActor)
float GetGuardRailRight (Actor *pActor)
float GetGuardRailTop (Actor *pActor)
float GetGuardRailBottom (Actor *pActor)
bool HitGuardRailLeft (Actor *pActor)
bool HitGuardRailRight (Actor *pActor)
bool HitGuardRailTop (Actor *pActor)
bool HitGuardRailBottom (Actor *pActor)
Variables
const float PARTICLE_SPEED = 300
const float SPIRAL_MAX_ZOOM = 2
const float SPIRAL_MIN_ZOOM = 0.3f
Macro Definition Documentation
MAX_SPRITES
#define MAX_SPRITES (MAX_TILES_WIDE * MAX_TILES_HIGH)
Referenced by BGAnimationLayer::LoadFromAniLayerFile().
MAX_TILES_HIGH
#define MAX_TILES_HIGH static_cast<int>(SCREEN_HEIGHT / 32 + 2)
Referenced by BGAnimationLayer::LoadFromAniLayerFile().
MAX_TILES_WIDE
#define MAX_TILES_WIDE static_cast<int>(SCREEN_WIDTH / 32 + 2)
Referenced by BGAnimationLayer::LoadFromAniLayerFile().
Function Documentation
GetGuardRailBottom()
float GetGuardRailBottom (Actor * pActor) inline
References Actor::GetZoomedHeight(), and SCREEN_BOTTOM.
Referenced by HitGuardRailBottom(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetGuardRailLeft()
float GetGuardRailLeft (Actor * pActor) inline
References Actor::GetZoomedWidth(), and SCREEN_LEFT.
Referenced by HitGuardRailLeft(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetGuardRailRight()
float GetGuardRailRight (Actor * pActor) inline
References Actor::GetZoomedWidth(), and SCREEN_RIGHT.
Referenced by HitGuardRailRight(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetGuardRailTop()
float GetGuardRailTop (Actor * pActor) inline
References Actor::GetZoomedHeight(), and SCREEN_TOP.
Referenced by HitGuardRailTop(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetOffScreenBottom()
float GetOffScreenBottom (Actor * pActor) inline
References Actor::GetZoomedHeight(), and SCREEN_BOTTOM.
Referenced by IsOffScreenBottom(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetOffScreenLeft()
float GetOffScreenLeft (Actor * pActor) inline
References Actor::GetZoomedWidth(), and SCREEN_LEFT.
Referenced by IsOffScreenLeft(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetOffScreenRight()
float GetOffScreenRight (Actor * pActor) inline
References Actor::GetZoomedWidth(), and SCREEN_RIGHT.
Referenced by IsOffScreenRight(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
GetOffScreenTop()
float GetOffScreenTop (Actor * pActor) inline
References Actor::GetZoomedHeight(), and SCREEN_TOP.
Referenced by IsOffScreenTop(), BGAnimationLayer::LoadFromAniLayerFile(), and BGAnimationLayer::UpdateInternal().
HitGuardRailBottom()
bool HitGuardRailBottom (Actor * pActor) inline
References GetGuardRailBottom(), and Actor::GetY().
Referenced by BGAnimationLayer::UpdateInternal().
HitGuardRailLeft()
bool HitGuardRailLeft (Actor * pActor) inline
References GetGuardRailLeft(), and Actor::GetX().
Referenced by BGAnimationLayer::UpdateInternal().
HitGuardRailRight()
bool HitGuardRailRight (Actor * pActor) inline
References GetGuardRailRight(), and Actor::GetX().
Referenced by BGAnimationLayer::UpdateInternal().
HitGuardRailTop()
bool HitGuardRailTop (Actor * pActor) inline
References GetGuardRailTop(), and Actor::GetY().
Referenced by BGAnimationLayer::UpdateInternal().
IsOffScreen()
bool IsOffScreen (Actor * pActor) inline
References IsOffScreenBottom(), IsOffScreenLeft(), IsOffScreenRight(), and IsOffScreenTop().
IsOffScreenBottom()
bool IsOffScreenBottom (Actor * pActor) inline
References GetOffScreenBottom(), and Actor::GetY().
Referenced by IsOffScreen(), and BGAnimationLayer::UpdateInternal().
IsOffScreenLeft()
bool IsOffScreenLeft (Actor * pActor) inline
References GetOffScreenLeft(), and Actor::GetX().
Referenced by IsOffScreen(), and BGAnimationLayer::UpdateInternal().
IsOffScreenRight()
bool IsOffScreenRight (Actor * pActor) inline
References GetOffScreenRight(), and Actor::GetX().
Referenced by IsOffScreen(), and BGAnimationLayer::UpdateInternal().
IsOffScreenTop()
bool IsOffScreenTop (Actor * pActor) inline
References GetOffScreenTop(), and Actor::GetY().
Referenced by IsOffScreen(), and BGAnimationLayer::UpdateInternal().
Variable Documentation
PARTICLE_SPEED
const float PARTICLE_SPEED = 300
Referenced by BGAnimationLayer::LoadFromAniLayerFile().
SPIRAL_MAX_ZOOM
const float SPIRAL_MAX_ZOOM = 2
SPIRAL_MIN_ZOOM
const float SPIRAL_MIN_ZOOM = 0.3f