Etterna: AutoActor Class Reference
AutoActor Class Reference
A smart pointer for Actor.
#include <AutoActor.h>
Public Member Functions
AutoActor ()
~AutoActor ()
AutoActor (const AutoActor &cpy)
AutoActor & operator= (const AutoActor &cpy)
operator const Actor * () const
operator Actor * ()
const Actor * operator-> () const
Actor * operator-> ()
void Unload ()
bool IsLoaded () const
Determine if this actor is presently loaded.
void Load (Actor *pActor)
void Load (const RString &sPath)
void LoadB (const RString &sMetricsGroup, const RString &sElement)
void LoadActorFromNode (const XNode *pNode, Actor *pParent)
void LoadAndSetName (const RString &sScreenName, const RString &sActorName)
Protected Attributes
Actor * m_pActor
the Actor for which there is a smart pointer to.
Detailed Description
A smart pointer for Actor.
This creates the appropriate Actor derivative on load and automatically deletes the Actor on deconstruction.
Constructor & Destructor Documentation
AutoActor() [1/2]
AutoActor::AutoActor () inline
~AutoActor()
AutoActor::~AutoActor () inline
References Unload().
AutoActor() [2/2]
AutoActor::AutoActor (const AutoActor & cpy)
References Actor::Copy(), and m_pActor.
Member Function Documentation
IsLoaded()
bool AutoActor::IsLoaded () const inline
Determine if this actor is presently loaded.
Returns
true if it is loaded, or false otherwise.
References m_pActor.
Referenced by Transition::Reset(), HoldJudgment::ResetAnimation(), MeterDisplay::SetPercent(), Transition::StartTransitioning(), and ControllerStateDisplay::Update().
Load() [1/2]
void AutoActor::Load (Actor * pActor)
References m_pActor, and Unload().
Referenced by DancingCharacters::DancingCharacters(), GrooveRadar::GrooveRadar(), ScreenSyncOverlay::Init(), ScreenPlayerOptions::Init(), ScreenGameplayLesson::Init(), ScreenSystemLayer::Init(), ScreenNetSelectBase::Init(), ScreenWithMenuElements::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScoreDisplayLifeTime::Init(), BeginnerHelper::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Player::Init(), LifeMeterBar::LifeMeterBar(), MeterDisplay::Load(), DualScrollBar::Load(), ModIcon::Load(), GradeDisplay::Load(), HoldJudgment::Load(), RoomInfoDisplay::Load(), Transition::Load(), ReceptorArrow::Load(), LifeMeterBattery::Load(), LifeMeterTime::Load(), GraphDisplay::Load(), MenuTimer::Load(), OptionRowType::Load(), StepsDisplay::Load(), PaneDisplay::Load(), WheelBase::Load(), OptionsList::Load(), RoomWheelItem::Load(), ScreenMapControllers::ActionRow::Load(), LoadAndSetName(), LoadB(), BGAnimationLayer::LoadFromNode(), ControllerStateDisplay::LoadInternal(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayPercentage::ScoreDisplayPercentage(), and ScrollBar::ScrollBar().
Load() [2/2]
void AutoActor::Load (const RString & sPath)
References m_pActor, ActorUtil::MakeActor(), and Unload().
LoadActorFromNode()
void AutoActor::LoadActorFromNode (const XNode * pNode, Actor * pParent)
References ActorUtil::LoadFromNode(), m_pActor, and Unload().
Referenced by MeterDisplay::LoadFromNode(), and StepsDisplayList::LoadFromNode().
LoadAndSetName()
void AutoActor::LoadAndSetName (const RString & sScreenName, const RString & sActorName)
References ThemeManager::GetPathG(), Load(), ActorUtil::LoadAllCommands(), m_pActor, Actor::SetName(), and THEME.
LoadB()
void AutoActor::LoadB (const RString & sMetricsGroup, const RString & sElement)
References ASSERT, EC_BGANIMATIONS, ThemeManager::GetPathInfo(), Load(), ThemeManager::PathInfo::sMatchingElement, ThemeManager::PathInfo::sMatchingMetricsGroup, ThemeManager::PathInfo::sResolvedPath, and THEME.
Referenced by ScreenWithMenuElements::Init().
operator Actor *()
AutoActor::operator Actor * () inline
References m_pActor.
operator const Actor *()
AutoActor::operator const Actor * () const inline
References m_pActor.
operator->() [1/2]
const Actor* AutoActor::operator-> () const inline
References m_pActor.
operator->() [2/2]
Actor* AutoActor::operator-> () inline
References m_pActor.
operator=()
AutoActor & AutoActor::operator= (const AutoActor & cpy)
References Actor::Copy(), m_pActor, and Unload().
Unload()
void AutoActor::Unload ()
References m_pActor.
Referenced by Load(), LoadActorFromNode(), operator=(), and ~AutoActor().
Member Data Documentation
m_pActor
Actor* AutoActor::m_pActor protected
the Actor for which there is a smart pointer to.
Referenced by AutoActor(), IsLoaded(), Load(), LoadActorFromNode(), LoadAndSetName(), operator Actor *(), operator const Actor *(), operator->(), operator=(), and Unload().
The documentation for this class was generated from the following files:
AutoActor.h
AutoActor.cpp