Etterna: LunaPlaylist Class Reference
LunaPlaylist Class Reference
Public Member Functions
DEFINE_METHOD (GetAverageRating, GetAverageRating())
DEFINE_METHOD (GetName, GetName())
LunaPlaylist ()
Public Member Functions inherited from Luna< Playlist >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetChartkeys (T *p, lua_State *L)
static int GetAllSteps (T *p, lua_State *L)
static int GetSonglist (T *p, lua_State *L)
static int GetStepslist (T *p, lua_State *L)
static int AddChart (T *p, lua_State *L)
static int DeleteChart (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Playlist >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Playlist >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Playlist >
using T = Playlist
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Playlist >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaPlaylist()
LunaPlaylist::LunaPlaylist () inline
References ADD_METHOD.
Member Function Documentation
AddChart()
static int LunaPlaylist::AddChart (T * p, lua_State * L) inline static
References Playlist::AddChart(), PLAYER_1, PROFILEMAN, SArg, and ProfileManager::SaveProfile().
DEFINE_METHOD() [1/2]
LunaPlaylist::DEFINE_METHOD (GetAverageRating , GetAverageRating())
DEFINE_METHOD() [2/2]
LunaPlaylist::DEFINE_METHOD (GetName , GetName())
DeleteChart()
static int LunaPlaylist::DeleteChart (T * p, lua_State * L) inline static
References Playlist::DeleteChart(), IArg, PLAYER_1, PROFILEMAN, and ProfileManager::SaveProfile().
GetAllSteps()
static int LunaPlaylist::GetAllSteps (T * p, lua_State * L) inline static
References Playlist::chartlist.
GetChartkeys()
static int LunaPlaylist::GetChartkeys (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), Playlist::GetKeys(), and keys.
GetSonglist()
static int LunaPlaylist::GetSonglist (T * p, lua_State * L) inline static
References Playlist::chartlist.
GetStepslist()
static int LunaPlaylist::GetStepslist (T * p, lua_State * L) inline static
References Playlist::chartlist.
The documentation for this class was generated from the following file:
SongManager.cpp