Etterna: EventDevice Struct Reference
EventDevice Struct Reference
Public Member Functions
EventDevice ()
~EventDevice ()
bool Open (RString sFile, InputDevice dev)
bool IsOpen () const
void Close ()
Public Attributes
int m_iFD
RString m_sPath
RString m_sName
InputDevice m_Dev
int aiAbsMin [ABS_MAX]
int aiAbsMax [ABS_MAX]
DeviceButton aiAbsMappingHigh [ABS_MAX]
DeviceButton aiAbsMappingLow [ABS_MAX]
Constructor & Destructor Documentation
EventDevice()
EventDevice::EventDevice ()
References m_iFD.
~EventDevice()
EventDevice::~EventDevice ()
References Close().
Member Function Documentation
Close()
void EventDevice::Close () inline
References m_iFD.
Referenced by Open(), and ~EventDevice().
IsOpen()
bool EventDevice::IsOpen () const inline
References m_iFD.
Open()
bool EventDevice::Open (RString sFile, InputDevice dev)
References aiAbsMappingHigh, aiAbsMappingLow, aiAbsMax, aiAbsMin, ARRAYLEN, BitIsSet(), BustypeToString(), Close(), enum_add2(), RageLog::Info(), Rage::join(), JOY_AUX_1, JOY_AUX_3, JOY_DOWN, JOY_HAT_DOWN, JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_LEFT, JOY_LEFT_2, JOY_RIGHT, JOY_ROT_DOWN, JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_UP, JOY_ROT_Z_DOWN, JOY_ROT_Z_UP, JOY_UP, JOY_UP_2, JOY_Z_DOWN, JOY_Z_UP, LOG, m_Dev, m_iFD, m_sName, m_sPath, and RageLog::Warn().
Referenced by InputHandler_Linux_Event::TryDevice().
Member Data Documentation
aiAbsMappingHigh
DeviceButton EventDevice::aiAbsMappingHigh[ABS_MAX]
Referenced by Open().
aiAbsMappingLow
DeviceButton EventDevice::aiAbsMappingLow[ABS_MAX]
Referenced by Open().
aiAbsMax
int EventDevice::aiAbsMax[ABS_MAX]
Referenced by Open().
aiAbsMin
int EventDevice::aiAbsMin[ABS_MAX]
Referenced by Open().
m_Dev
InputDevice EventDevice::m_Dev
Referenced by InputHandler_Linux_Event::GetDevicesAndDescriptions(), and Open().
m_iFD
int EventDevice::m_iFD
Referenced by Close(), EventDevice(), IsOpen(), and Open().
m_sName
RString EventDevice::m_sName
Referenced by InputHandler_Linux_Event::GetDevicesAndDescriptions(), and Open().
m_sPath
RString EventDevice::m_sPath
Referenced by Open().
The documentation for this struct was generated from the following file:
InputHandler_Linux_Event.cpp