Etterna: RageFileDriverReadAhead Class Reference
RageFileDriverReadAhead Class Reference
#include <RageFileDriverReadAhead.h>
Public Member Functions
RageFileDriverReadAhead (RageFileBasic *pFile, int iCacheBytes, int iPostBufferReadAhead=-1)
RageFileDriverReadAhead (const RageFileDriverReadAhead &cpy)
~RageFileDriverReadAhead () override
RageFileDriverReadAhead * Copy () const override
void DeleteFileWhenFinished ()
RString GetError () const override
void ClearError () override
int ReadInternal (void *pBuffer, size_t iBytes) override
int WriteInternal (const void *pBuffer, size_t iBytes) override
int SeekInternal (int iOffset) override
int GetFileSize () const override
int GetFD () override
int Tell () const override
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
RString GetDisplayPath () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Static Public Member Functions
static bool FileSupported (RageFileBasic *pFile)
Private Member Functions
void FillBuffer (int iBytes)
Private Attributes
RageFileBasic * m_pFile
int m_iFilePos
bool m_bFileOwned
RString m_sBuffer
int m_iPostBufferReadAhead
bool m_bReadAheadNeeded
Additional Inherited Members
Protected Member Functions inherited from RageFileObj
virtual int FlushInternal ()
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileDriverReadAhead() [1/2]
RageFileDriverReadAhead::RageFileDriverReadAhead (RageFileBasic * pFile, int iCacheBytes, int iPostBufferReadAhead = -1)
References FillBuffer(), m_bFileOwned, m_iFilePos, m_iPostBufferReadAhead, m_pFile, and RageFileBasic::Tell().
Referenced by Copy().
RageFileDriverReadAhead() [2/2]
RageFileDriverReadAhead::RageFileDriverReadAhead (const RageFileDriverReadAhead & cpy)
References RageFileManagerReadAhead::CacheHintStreaming(), RageFileBasic::Copy(), m_bFileOwned, m_iFilePos, m_iPostBufferReadAhead, m_pFile, and m_sBuffer.
~RageFileDriverReadAhead()
RageFileDriverReadAhead::~RageFileDriverReadAhead () override
References m_bFileOwned, and m_pFile.
Member Function Documentation
ClearError()
void RageFileDriverReadAhead::ClearError () inline override virtual
Reimplemented from RageFileObj.
References RageFileBasic::ClearError(), and m_pFile.
Copy()
RageFileDriverReadAhead * RageFileDriverReadAhead::Copy () const override virtual
Reimplemented from RageFileObj.
References RageFileDriverReadAhead().
DeleteFileWhenFinished()
void RageFileDriverReadAhead::DeleteFileWhenFinished () inline
References m_bFileOwned.
FileSupported()
bool RageFileDriverReadAhead::FileSupported (RageFileBasic * pFile) static
References RageFileBasic::GetFD().
FillBuffer()
void RageFileDriverReadAhead::FillBuffer (int iBytes) private
References RageFileManagerReadAhead::CacheHintStreaming(), m_pFile, m_sBuffer, RageFileBasic::Read(), RageFileBasic::Seek(), and RageFileBasic::Tell().
Referenced by RageFileDriverReadAhead().
GetError()
RString RageFileDriverReadAhead::GetError () const inline override virtual
Reimplemented from RageFileObj.
References RageFileBasic::GetError(), and m_pFile.
GetFD()
int RageFileDriverReadAhead::GetFD () inline override virtual
Reimplemented from RageFileObj.
References RageFileBasic::GetFD(), and m_pFile.
GetFileSize()
int RageFileDriverReadAhead::GetFileSize () const inline override virtual
Implements RageFileObj.
References RageFileBasic::GetFileSize(), and m_pFile.
ReadInternal()
int RageFileDriverReadAhead::ReadInternal (void * pBuffer, size_t iBytes) override virtual
Implements RageFileObj.
References RageFileManagerReadAhead::DiscardCache(), m_bReadAheadNeeded, m_iFilePos, m_iPostBufferReadAhead, m_pFile, m_sBuffer, min(), RageFileBasic::Read(), and RageFileManagerReadAhead::ReadAhead().
SeekInternal()
int RageFileDriverReadAhead::SeekInternal (int iOffset) override virtual
Reimplemented from RageFileObj.
References m_iFilePos, m_pFile, m_sBuffer, and RageFileBasic::Seek().
Tell()
int RageFileDriverReadAhead::Tell () const inline override virtual
Reimplemented from RageFileObj.
References m_iFilePos.
WriteInternal()
int RageFileDriverReadAhead::WriteInternal (const void * pBuffer, size_t iBytes) inline override virtual
Implements RageFileObj.
References m_pFile, and RageFileBasic::Write().
Member Data Documentation
m_bFileOwned
bool RageFileDriverReadAhead::m_bFileOwned private
Referenced by DeleteFileWhenFinished(), RageFileDriverReadAhead(), and ~RageFileDriverReadAhead().
m_bReadAheadNeeded
bool RageFileDriverReadAhead::m_bReadAheadNeeded private
Referenced by ReadInternal().
m_iFilePos
int RageFileDriverReadAhead::m_iFilePos private
Referenced by RageFileDriverReadAhead(), ReadInternal(), SeekInternal(), and Tell().
m_iPostBufferReadAhead
int RageFileDriverReadAhead::m_iPostBufferReadAhead private
Referenced by RageFileDriverReadAhead(), and ReadInternal().
m_pFile
RageFileBasic* RageFileDriverReadAhead::m_pFile private
Referenced by ClearError(), FillBuffer(), GetError(), GetFD(), GetFileSize(), RageFileDriverReadAhead(), ReadInternal(), SeekInternal(), WriteInternal(), and ~RageFileDriverReadAhead().
m_sBuffer
RString RageFileDriverReadAhead::m_sBuffer private
Referenced by FillBuffer(), RageFileDriverReadAhead(), ReadInternal(), and SeekInternal().
The documentation for this class was generated from the following files:
RageFileDriverReadAhead.h
RageFileDriverReadAhead.cpp