Etterna: GameCommand Class Reference
GameCommand Class Reference
#include <GameCommand.h>
Public Member Functions
GameCommand ()
void Init ()
void Load (int iIndex, const Commands &cmds)
void LoadOne (const Command &cmd)
void ApplyToAllPlayers () const
void Apply (PlayerNumber pn) const
bool DescribesCurrentMode (PlayerNumber pn) const
bool DescribesCurrentModeForAllPlayers () const
bool IsPlayable (RString *why=NULL) const
bool IsZero () const
void ApplyCommitsScreens (bool bOn)
void PushSelf (lua_State *L)
Public Attributes
Commands m_Commands
RString m_sName
RString m_sText
bool m_bInvalid { true }
RString m_sInvalidReason
int m_iIndex { -1 }
MultiPlayer m_MultiPlayer { MultiPlayer_Invalid }
const Style * m_pStyle
PlayMode m_pm { PlayMode_Invalid }
Difficulty m_dc { Difficulty_Invalid }
RString m_sAnnouncer
RString m_sPreferredModifiers
RString m_sStageModifiers
RString m_sScreen
LuaReference m_LuaFunction
Song * m_pSong
Steps * m_pSteps
Character * m_pCharacter
std::map< RString, RString > m_SetEnv
std::map< RString, RString > m_SetPref
RString m_sSongGroup
SortOrder m_SortOrder { SortOrder_Invalid }
RString m_sSoundPath
vector< RString > m_vsScreensToPrepare
RString m_sProfileID
RString m_sUrl
bool m_bUrlExits { true }
bool m_bStopMusic { false }
bool m_bApplyDefaultOptions { false }
bool m_bFadeMusic { false }
float m_fMusicFadeOutVolume { -1 }
float m_fMusicFadeOutSeconds { -1 }
Private Member Functions
void Apply (const vector< PlayerNumber > &vpns) const
void ApplySelf (const vector< PlayerNumber > &vpns) const
Private Attributes
bool m_bApplyCommitsScreens { true }
Constructor & Destructor Documentation
GameCommand()
GameCommand::GameCommand () inline
References m_LuaFunction, and LuaReference::Unset().
Member Function Documentation
Apply() [1/2]
void GameCommand::Apply (PlayerNumber pn) const
Referenced by GameState::ApplyGameCommand(), ApplyToAllPlayers(), OptionRowHandlerList::ExportOption(), and ScreenSelect::HandleScreenMessage().
Apply() [2/2]
void GameCommand::Apply (const vector< PlayerNumber > & vpns) const private
References ApplySelf(), FOREACH_CONST, LoadOne(), m_bApplyCommitsScreens, m_bInvalid, m_Commands, and Commands::v.
ApplyCommitsScreens()
void GameCommand::ApplyCommitsScreens (bool bOn) inline
References m_bApplyCommitsScreens.
Referenced by ScreenSelect::Init(), OptionRowHandlerGameCommand::Init(), and OptionRowHandlerList::LoadInternal().
ApplySelf()
void GameCommand::ApplySelf (const vector< PlayerNumber > & vpns) const private
References ANNOUNCER, GameState::ApplyPreferredModifiers(), GameState::ApplyStageModifiers(), ASSERT, ModsGroup< T >::Assign(), COULD_NOT_LAUNCH_BROWSER, Difficulty_Invalid, GameSoundManager::DimMusic(), FOREACH_CONST, FOREACH_PlayerNumber, IPreference::FromString(), GAMESTATE, LuaManager::Get(), GameState::GetDefaultPlayerOptions(), GameState::GetDefaultSongOptions(), GameState::GetMasterPlayerNumber(), ThemeManager::GetPathS(), IPreference::GetPreferenceByName(), ArchHooks::GoToURL(), HOOKS, LuaReference::IsNil(), LuaReference::IsSet(), GameState::JoinPlayer(), L, LUA, m_bApplyCommitsScreens, m_bApplyDefaultOptions, m_bFadeMusic, m_bStopMusic, m_bUrlExits, m_dc, GameState::m_Environment, m_fMusicFadeOutSeconds, m_fMusicFadeOutVolume, m_LuaFunction, m_pCharacter, GameState::m_pCurCharacters, GameState::m_pCurSong, GameState::m_pCurSteps, PlayerState::m_PlayerOptions, GameState::m_PlayMode, m_pm, GameState::m_pPlayerState, GameState::m_pPreferredSong, GameState::m_PreferredDifficulty, GameState::m_PreferredSortOrder, m_pSong, m_pSteps, m_pStyle, m_sAnnouncer, ProfileManager::m_sDefaultLocalProfileID, m_SetEnv, m_SetPref, GameState::m_SongOptions, m_SortOrder, m_sPreferredModifiers, GameState::m_sPreferredSongGroup, m_sProfileID, m_sScreen, m_sSongGroup, m_sSoundPath, m_sStageModifiers, Style::m_StyleType, m_sUrl, m_vsScreensToPrepare, ModsLevel_Stage, PlayMode_Invalid, GameSoundManager::PlayOnce(), ScreenManager::PrepareScreen(), ScreenPrompt::Prompt(), LuaReference::PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptError(), LuaHelpers::RunScriptOnStack(), SCREENMAN, BroadcastOnChange< T >::Set(), BroadcastOnChangePtr< T >::Set(), GameState::SetCurrentStyle(), ScreenManager::SetNewScreen(), SM_None, SortOrder_Invalid, SOUND, GameSoundManager::StopMusic(), StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, StyleType_TwoPlayersTwoSides, AnnouncerManager::SwitchAnnouncer(), and THEME.
Referenced by Apply().
ApplyToAllPlayers()
void GameCommand::ApplyToAllPlayers () const
References Apply(), and FOREACH_PlayerNumber.
Referenced by GameState::ApplyGameCommand(), OptionRowHandlerGameCommand::ExportOption(), ScreenSelect::HandleScreenMessage(), ScreenSelectMaster::MenuStart(), and MusicWheel::Select().
DescribesCurrentMode()
bool GameCommand::DescribesCurrentMode (PlayerNumber pn) const
References ANNOUNCER, Difficulty_Invalid, FOREACH_HumanPlayer, SongOptions::FromString(), PlayerOptions::FromString(), GAMESTATE, BroadcastOnChangePtr< T >::Get(), AnnouncerManager::GetCurAnnouncerName(), GameState::GetCurrentStyle(), ModsGroup< T >::GetPreferred(), ModsGroup< T >::GetStage(), m_dc, m_pCharacter, GameState::m_pCurCharacters, GameState::m_pCurSong, GameState::m_pCurSteps, PlayerState::m_PlayerOptions, GameState::m_PlayMode, m_pm, GameState::m_pPlayerState, GameState::m_PreferredDifficulty, GameState::m_PreferredSortOrder, m_pSong, m_pSteps, m_pStyle, m_sAnnouncer, ProfileManager::m_sDefaultLocalProfileID, GameState::m_SongOptions, m_SortOrder, m_sPreferredModifiers, GameState::m_sPreferredSongGroup, m_sProfileID, m_sSongGroup, m_sStageModifiers, PlayMode_Invalid, and SortOrder_Invalid.
Referenced by DescribesCurrentModeForAllPlayers(), and OptionRowHandlerList::ImportOption().
DescribesCurrentModeForAllPlayers()
bool GameCommand::DescribesCurrentModeForAllPlayers () const
References DescribesCurrentMode(), and FOREACH_HumanPlayer.
Referenced by OptionRowHandlerList::ImportOption().
Init()
void GameCommand::Init ()
References Difficulty_Invalid, m_bApplyCommitsScreens, m_bApplyDefaultOptions, m_bFadeMusic, m_bInvalid, m_bStopMusic, m_bUrlExits, m_dc, m_fMusicFadeOutSeconds, m_fMusicFadeOutVolume, m_iIndex, m_LuaFunction, m_MultiPlayer, m_pCharacter, m_pm, m_pSong, m_pSteps, m_pStyle, m_sAnnouncer, m_sName, m_SortOrder, m_sPreferredModifiers, m_sProfileID, m_sScreen, m_sSoundPath, m_sStageModifiers, m_sText, m_sUrl, m_vsScreensToPrepare, MultiPlayer_Invalid, PlayMode_Invalid, SortOrder_Invalid, and LuaReference::Unset().
Referenced by OptionRowHandler::GetIconTextAndGameCommand(), OptionRowHandlerList::Init(), and OptionRowHandlerGameCommand::Init().
IsPlayable()
bool GameCommand::IsPlayable (RString * why = NULL) const
References AreStyleAndPlayModeCompatible(), StdString::CStdStr< CT >::CompareNoCase(), GAMESTATE, GameState::GetCurrentStyle(), GameState::GetMasterPlayerNumber(), SongManager::GetNumSongs(), m_bInvalid, GameState::m_PlayMode, m_pm, m_pStyle, m_sInvalidReason, m_sScreen, PlayMode_Invalid, PlayModeToString(), SONGMAN, and ssprintf().
Referenced by GameState::ApplyGameCommand(), MusicWheel::BuildWheelItemDatas(), and OptionRowHandlerList::LoadInternal().
IsZero()
bool GameCommand::IsZero () const
References Difficulty_Invalid, m_dc, m_pCharacter, m_pm, m_pSong, m_pSteps, m_pStyle, m_sAnnouncer, m_SortOrder, m_sPreferredModifiers, m_sProfileID, m_sSongGroup, m_sStageModifiers, m_sUrl, PlayMode_Invalid, and SortOrder_Invalid.
Referenced by OptionRowHandlerList::ImportOption(), and OptionRowHandlerList::LoadInternal().
Load()
void GameCommand::Load (int iIndex, const Commands & cmds)
References FOREACH_CONST, LoadOne(), m_bInvalid, m_Commands, m_iIndex, and Commands::v.
Referenced by GameState::ApplyGameCommand(), MusicWheel::BuildWheelItemDatas(), ScreenSelect::Init(), OptionRowHandlerList::LoadInternal(), and OptionRowHandlerGameCommand::LoadInternal().
LoadOne()
void GameCommand::LoadOne (const Command & cmd)
References CHECK_INVALID_COND, CHECK_INVALID_VALUE, Difficulty_Edit, Difficulty_Invalid, SongManager::DoesSongGroupExist(), SongManager::FindSong(), GameManager::GameAndStringToStyle(), GAMEMAN, GAMESTATE, GameState::GetCurrentStyle(), GameState::GetMasterPlayerNumber(), Command::GetName(), Command::GetOriginalCommandString(), IPreference::GetPreferenceByName(), SongUtil::GetStepsByDescription(), SongUtil::GetStepsByDifficulty(), ThemeManager::HasMetric(), LuaReference::IsNil(), ScreenManager::IsScreenNameValid(), m_bApplyDefaultOptions, m_bFadeMusic, m_bInvalid, m_bStopMusic, m_bUrlExits, m_dc, m_fMusicFadeOutSeconds, m_fMusicFadeOutVolume, m_LuaFunction, GameState::m_pCurGame, GameState::m_pCurSong, m_pm, m_pSong, m_pSteps, m_pStyle, m_sAnnouncer, m_SetEnv, m_SetPref, m_sName, m_SortOrder, m_sPreferredModifiers, m_sProfileID, m_sScreen, m_sSongGroup, m_sSoundPath, m_sStageModifiers, m_sText, m_sUrl, Command::m_vsArgs, m_vsScreensToPrepare, MAKE_INVALID, PlayMode_Invalid, SCREENMAN, LuaReference::SetFromExpression(), SONGMAN, SortOrder_Invalid, ssprintf(), StringToDifficulty(), StringToPlayMode(), StringToSortOrder(), and THEME.
Referenced by Apply(), and Load().
PushSelf()
void GameCommand::PushSelf (lua_State * L)
Member Data Documentation
m_bApplyCommitsScreens
bool GameCommand::m_bApplyCommitsScreens { true } private
Referenced by Apply(), ApplyCommitsScreens(), ApplySelf(), and Init().
m_bApplyDefaultOptions
bool GameCommand::m_bApplyDefaultOptions { false }
Referenced by ApplySelf(), Init(), and LoadOne().
m_bFadeMusic
bool GameCommand::m_bFadeMusic { false }
Referenced by ApplySelf(), Init(), and LoadOne().
m_bInvalid
bool GameCommand::m_bInvalid { true }
Referenced by Apply(), ScreenSelect::HandleScreenMessage(), ScreenSelectLanguage::Init(), Init(), IsPlayable(), Load(), and LoadOne().
m_bStopMusic
bool GameCommand::m_bStopMusic { false }
Referenced by ApplySelf(), Init(), and LoadOne().
m_bUrlExits
bool GameCommand::m_bUrlExits { true }
Referenced by ApplySelf(), Init(), and LoadOne().
m_Commands
Commands GameCommand::m_Commands
Referenced by Apply(), and Load().
m_dc
Difficulty GameCommand::m_dc { Difficulty_Invalid }
Referenced by ApplySelf(), DescribesCurrentMode(), Init(), IsZero(), OptionRowHandlerListDifficulties::LoadInternal(), LoadOne(), and OptionRowHandlerListSteps::Reload().
m_fMusicFadeOutSeconds
float GameCommand::m_fMusicFadeOutSeconds { -1 }
Referenced by ApplySelf(), Init(), and LoadOne().
m_fMusicFadeOutVolume
float GameCommand::m_fMusicFadeOutVolume { -1 }
Referenced by ApplySelf(), Init(), and LoadOne().
m_iIndex
int GameCommand::m_iIndex { -1 }
Referenced by LunaGameCommand::GetIndex(), ScreenSelectLanguage::Init(), Init(), and Load().
m_LuaFunction
LuaReference GameCommand::m_LuaFunction
Referenced by ApplySelf(), GameCommand(), Init(), and LoadOne().
m_MultiPlayer
MultiPlayer GameCommand::m_MultiPlayer { MultiPlayer_Invalid }
Referenced by LunaGameCommand::GetMultiPlayer(), and Init().
m_pCharacter
Character* GameCommand::m_pCharacter
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetCharacter(), Init(), IsZero(), and OptionRowHandlerListCharacters::LoadInternal().
m_pm
PlayMode GameCommand::m_pm { PlayMode_Invalid }
Referenced by ApplySelf(), DescribesCurrentMode(), Init(), IsPlayable(), IsZero(), and LoadOne().
m_pSong
Song* GameCommand::m_pSong
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetSong(), Init(), IsZero(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), and LoadOne().
m_pSteps
Steps* GameCommand::m_pSteps
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetSteps(), Init(), IsZero(), LoadOne(), and OptionRowHandlerListSteps::Reload().
m_pStyle
const Style* GameCommand::m_pStyle
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetStyle(), Init(), IsPlayable(), IsZero(), OptionRowHandlerListStyles::LoadInternal(), and LoadOne().
m_sAnnouncer
RString GameCommand::m_sAnnouncer
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetAnnouncer(), Init(), IsZero(), and LoadOne().
m_SetEnv
std::map<RString, RString> GameCommand::m_SetEnv
Referenced by ApplySelf(), and LoadOne().
m_SetPref
std::map<RString, RString> GameCommand::m_SetPref
Referenced by ApplySelf(), and LoadOne().
m_sInvalidReason
RString GameCommand::m_sInvalidReason
Referenced by IsPlayable().
m_sName
RString GameCommand::m_sName
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMaster::BeginScreen(), MusicWheel::BuildWheelItemDatas(), LunaGameCommand::GetName(), ScreenSelectLanguage::Init(), ScreenSelect::Init(), ScreenSelectMaster::Init(), Init(), OptionRowHandlerList::LoadInternal(), OptionRowHandlerGameCommand::LoadInternal(), LoadOne(), ScreenSelectMaster::MenuStart(), MusicWheel::Select(), MusicWheel::SelectModeMenuItem(), and OptionsList::Start().
m_SortOrder
SortOrder GameCommand::m_SortOrder { SortOrder_Invalid }
Referenced by ApplySelf(), DescribesCurrentMode(), Init(), IsZero(), and LoadOne().
m_sPreferredModifiers
RString GameCommand::m_sPreferredModifiers
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetPreferredModifiers(), Init(), IsZero(), OptionRowHandlerListNoteSkins::LoadInternal(), and LoadOne().
m_sProfileID
RString GameCommand::m_sProfileID
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetProfileID(), Init(), IsZero(), and LoadOne().
m_sScreen
RString GameCommand::m_sScreen
Referenced by ApplySelf(), OptionRowHandlerList::GetScreen(), LunaGameCommand::GetScreen(), OptionRowHandlerGameCommand::GetScreen(), ScreenSelect::HandleScreenMessage(), Init(), IsPlayable(), LoadOne(), and ScreenSelectMaster::MenuStart().
m_sSongGroup
RString GameCommand::m_sSongGroup
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetSongGroup(), IsZero(), OptionRowHandlerListGroups::LoadInternal(), and LoadOne().
m_sSoundPath
RString GameCommand::m_sSoundPath
Referenced by ApplySelf(), Init(), LoadOne(), and ScreenSelectMaster::MenuStart().
m_sStageModifiers
RString GameCommand::m_sStageModifiers
Referenced by ApplySelf(), DescribesCurrentMode(), LunaGameCommand::GetStageModifiers(), Init(), IsZero(), and LoadOne().
m_sText
RString GameCommand::m_sText
Referenced by LunaGameCommand::GetText(), ScreenSelectLanguage::Init(), Init(), and LoadOne().
m_sUrl
RString GameCommand::m_sUrl
Referenced by ApplySelf(), LunaGameCommand::GetUrl(), Init(), IsZero(), and LoadOne().
m_vsScreensToPrepare
vector<RString> GameCommand::m_vsScreensToPrepare
Referenced by ApplySelf(), Init(), and LoadOne().
The documentation for this class was generated from the following files:
GameCommand.h
GameCommand.cpp