Etterna: RageException Namespace Reference
RageException Namespace Reference
Namespace for throwing fatal errors.
Functions
void NORETURN Throw (const char *fmt,...) PRINTF(1
void NORETURN void SetCleanupHandler (void(*pHandler)(const RString &sError))
Detailed Description
Namespace for throwing fatal errors.
The original documentation stated this was a class for some reason.
Function Documentation
SetCleanupHandler()
void RageException::SetCleanupHandler (void(*)(const RString &sError) pHandler)
References g_CleanupHandler, g_HandlerThreadID, and RageThread::GetCurrentThreadID().
Referenced by sm_main().
Throw()
void RageException::Throw (const char * fmt, ...)
References ASSERT_M, RageLog::Flush(), g_CleanupHandler, g_HandlerThreadID, RageThread::GetCurrentThreadID(), RageThread::GetInvalidThreadID(), LOG, ssprintf(), RageLog::Trace(), and vssprintf().
Referenced by GameState::ApplyCmdline(), StepMania::ApplyGraphicOptions(), RageDisplay_D3D::BeginFrame(), CharacterManager::CharacterManager(), Regex::Compare(), Regex::Compile(), ConvertString(), RageFileObjDirect::Copy(), RageMovieTexture::Create(), InputHandler::Create(), MovieTexture_DShow::Create(), CreateDisplay(), RageDisplay_D3D::CreateTexture(), RageDisplay_Legacy::CreateTexture(), DerefRedir(), DSound::DSound(), FindBackBufferType(), FindEmptyThreadSlot(), Font::FontCompleteForString(), GameManager::GetDefaultGame(), Font::GetGlyph(), RageSoundReader_Vorbisfile::GetLength(), ThemeManager::GetMetricRaw(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfo(), ThemeManager::GetPathInfoToRaw(), RageSoundManager::Init(), InputHandler_DInput::InputHandler_DInput(), InputHandler_Linux_tty::InputHandler_Linux_tty(), AnimatedTexture::Load(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), Model::LoadPieces(), ThemeManager::LoadThemeMetrics(), LowLevelWindow_X11::LowLevelWindow_X11(), LuaPanic(), Nsis(), MovieTexture_DShow::Pause(), MovieTexture_DShow::Play(), RageFileObjDeflate::RageFileObjDeflate(), RageFileObjInflate::RageFileObjInflate(), RageSoundReader_Vorbisfile::Read(), RageTextureManager::RegisterTexture(), ActorUtil::ResolvePath(), SongManager::SanityCheckGroupDir(), DSoundBuf::SetSampleRate(), sm_main(), RageSoundDriver_PulseAudio::StreamWriteCb(), RageSemaphore::Wait(), and MovieTexture_DShow::~MovieTexture_DShow().