Etterna: ArchHooks_Win32 Class Reference
ArchHooks_Win32 Class Reference
#include <ArchHooks_Win32.h>
Public Member Functions
ArchHooks_Win32 ()
~ArchHooks_Win32 ()
RString GetArchName () const
void DumpDebugInfo ()
void RestartProgram ()
Re-exec the game.
bool CheckForMultipleInstances (int argc, char *argv[])
void SetTime (tm newtime)
void BoostPriority ()
void UnBoostPriority ()
void SetupConcurrentRenderingThread ()
Setup the rendering threads for concurrency.
bool GoToURL (const RString &sUrl)
virtual float GetDisplayAspectRatio ()
RString GetClipboard ()
Fetch the contents of the system clipboard.
int GetWindowWidth ()
Fetch the window width.
int GetWindowHeight ()
Fetch the window height.
Public Member Functions inherited from ArchHooks
ArchHooks ()
virtual ~ArchHooks ()=default
virtual void Init ()
void SetHasFocus (bool bAppHasFocus)
bool AppHasFocus () const
bool AppFocusChanged ()
void PushSelf (lua_State *L)
void RegisterWithLua ()
Additional Inherited Members
Static Public Member Functions inherited from ArchHooks
static ArchHooks * Create ()
static RString GetPreferredLanguage ()
static bool UserQuit ()
Determine if the user wants to quit (eg. ^C, or clicked a "close window" button).
static void SetUserQuit ()
static bool GetAndClearToggleWindowed ()
static void SetToggleWindowed ()
static int64_t GetMicrosecondsSinceStart (bool bAccurate)
static void MountInitialFilesystems (const RString &sDirOfExecutable)
static void MountUserFilesystems (const RString &sDirOfExecutable)
Constructor & Destructor Documentation
ArchHooks_Win32()
ArchHooks_Win32::ArchHooks_Win32 ()
References g_argc, g_argv, g_bIsMultipleInstance, g_hInstanceMutex, HOOKS, and PRODUCT_ID.
~ArchHooks_Win32()
ArchHooks_Win32::~ArchHooks_Win32 ()
References g_hInstanceMutex.
Member Function Documentation
BoostPriority()
void ArchHooks_Win32::BoostPriority () virtual
Reimplemented from ArchHooks.
References ABOVE_NORMAL_PRIORITY_CLASS, LOG, and RageLog::Warn().
CheckForMultipleInstances()
bool ArchHooks_Win32::CheckForMultipleInstances (int argc, char * argv[]) virtual
Reimplemented from ArchHooks.
References g_bIsMultipleInstance, GetEnabledPopup(), CallbackData::hParent, CallbackData::hResult, Rage::join(), and PRODUCT_ID.
DumpDebugInfo()
void ArchHooks_Win32::DumpDebugInfo () virtual
Reimplemented from ArchHooks.
GetArchName()
RString ArchHooks_Win32::GetArchName () const inline virtual
Reimplemented from ArchHooks.
GetClipboard()
RString ArchHooks_Win32::GetClipboard () virtual
Fetch the contents of the system clipboard.
Reimplemented from ArchHooks.
References LOG, unlikely, RageLog::Warn(), and WStringToRString().
GetDisplayAspectRatio()
float ArchHooks_Win32::GetDisplayAspectRatio () virtual
Implements ArchHooks.
References ASSERT, and ZERO.
GetWindowHeight()
int ArchHooks_Win32::GetWindowHeight () virtual
Fetch the window height.
Reimplemented from ArchHooks.
GetWindowWidth()
int ArchHooks_Win32::GetWindowWidth () virtual
Fetch the window width.
Reimplemented from ArchHooks.
GoToURL()
bool ArchHooks_Win32::GoToURL (const RString & sUrl) virtual
Reimplemented from ArchHooks.
RestartProgram()
void ArchHooks_Win32::RestartProgram () virtual
Re-exec the game.
If this is implemented, it doesn't return.
Reimplemented from ArchHooks.
SetTime()
void ArchHooks_Win32::SetTime (tm newtime) virtual
Reimplemented from ArchHooks.
References ZERO.
SetupConcurrentRenderingThread()
void ArchHooks_Win32::SetupConcurrentRenderingThread () virtual
Setup the rendering threads for concurrency.
The priority of the concurrent rendering thread may need to be boosted on some schedulers.
Reimplemented from ArchHooks.
UnBoostPriority()
void ArchHooks_Win32::UnBoostPriority () virtual
Reimplemented from ArchHooks.
The documentation for this class was generated from the following files:
ArchHooks_Win32.h
ArchHooks_Win32.cpp