Etterna: BroadcastOnChange< T > Class Template Reference
BroadcastOnChange< T > Class Template Reference
#include <MessageManager.h>
Public Member Functions
BroadcastOnChange (MessageID m)
const T Get () const
void Set (T t)
operator T () const
bool operator== (const T &other) const
bool operator!= (const T &other) const
Private Attributes
MessageID mSendWhenChanged
T val
Constructor & Destructor Documentation
BroadcastOnChange()
template<class T> BroadcastOnChange< T >::BroadcastOnChange (MessageID m) inline explicit
Member Function Documentation
Get()
template<class T> const T BroadcastOnChange< T >::Get () const inline
Referenced by GameState::GetRankingFeats(), and LuaHelpers::Push().
operator T()
template<class T> BroadcastOnChange< T >::operator T () const inline
References BroadcastOnChange< T >::val.
operator!=()
template<class T> bool BroadcastOnChange< T >::operator!= (const T & other) const inline
operator==()
template<class T> bool BroadcastOnChange< T >::operator== (const T & other) const inline
Set()
template<class T> void BroadcastOnChange< T >::Set (T t) inline
Referenced by GameCommand::ApplySelf(), MusicWheel::BeginScreen(), ScreenSelectMusic::BeginScreen(), GameState::ChangePreferredDifficultyAndStepsType(), MusicWheel::ChangeSort(), OptionRowHandlerSteps::ExportOption(), OptionRowHandlerStepsType::ExportOption(), GameState::GameState(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenGameplayLesson::Init(), ScreenHowToPlay::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), GameState::LoadCurrentSettingsFromProfile(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerStepsType::LoadInternal(), GameState::Reset(), GameState::ResetPlayer(), and LunaGameState::SetCurrentPlayMode().
Member Data Documentation
mSendWhenChanged
template<class T> MessageID BroadcastOnChange< T >::mSendWhenChanged private
val
template<class T> T BroadcastOnChange< T >::val private
Referenced by BroadcastOnChange< Difficulty >::Get(), and BroadcastOnChange< T >::operator T().
The documentation for this class was generated from the following file:
MessageManager.h