Etterna: LunaActorProxy Class Reference
LunaActorProxy Class Reference
Allow Lua to have access to the ActorProxy.
Public Member Functions
LunaActorProxy ()
Public Member Functions inherited from Luna< ActorProxy >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetTarget (T *p, lua_State *L)
static int GetTarget (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ActorProxy >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ActorProxy >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ActorProxy >
using T = ActorProxy
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ActorProxy >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ActorProxy.
Constructor & Destructor Documentation
LunaActorProxy()
LunaActorProxy::LunaActorProxy () inline
References ADD_METHOD, GetTarget(), and SetTarget().
Member Function Documentation
GetTarget()
static int LunaActorProxy::GetTarget (T * p, lua_State * L) inline static
References ActorProxy::GetTarget(), and Actor::PushSelf().
Referenced by LunaActorProxy().
SetTarget()
static int LunaActorProxy::SetTarget (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and ActorProxy::SetTarget().
Referenced by LunaActorProxy().
The documentation for this class was generated from the following file:
ActorProxy.cpp