Etterna: LunaActorSound Class Reference
LunaActorSound Class Reference
Allow Lua to have access to the ActorSound.
Public Member Functions
DEFINE_METHOD (get_is_action, m_is_action)
LunaActorSound ()
Public Member Functions inherited from Luna< ActorSound >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int load (T *p, lua_State *L)
static int play (T *p, lua_State *L)
static int pause (T *p, lua_State *L)
static int stop (T *p, lua_State *L)
static int get (T *p, lua_State *L)
static int set_is_action (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ActorSound >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ActorSound >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ActorSound >
using T = ActorSound
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ActorSound >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ActorSound.
Constructor & Destructor Documentation
LunaActorSound()
LunaActorSound::LunaActorSound () inline
References ADD_GET_SET_METHODS, ADD_METHOD, load(), pause(), play(), and stop().
Member Function Documentation
DEFINE_METHOD()
LunaActorSound::DEFINE_METHOD (get_is_action , m_is_action)
get()
static int LunaActorSound::get (T * p, lua_State * L) inline static
References L.
load()
static int LunaActorSound::load (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorSound::Load(), and SArg.
Referenced by LunaActorSound().
pause()
static int LunaActorSound::pause (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorSound::Pause().
Referenced by LunaActorSound().
play()
static int LunaActorSound::play (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorSound::Play().
Referenced by LunaActorSound().
set_is_action()
static int LunaActorSound::set_is_action (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorSound::m_is_action.
stop()
static int LunaActorSound::stop (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorSound::Stop().
Referenced by LunaActorSound().
The documentation for this class was generated from the following file:
ActorSound.cpp