Etterna: LuaManager Class Reference
LuaManager Class Reference
#include <LuaManager.h>
Public Member Functions
LuaManager ()
~LuaManager ()
Lua * Get ()
void Release (Lua *&p)
void YieldLua ()
void UnyieldLua ()
void RegisterTypes ()
void SetGlobal (const std::string &sName, int val)
void SetGlobal (const std::string &sName, const std::string &val)
void UnsetGlobal (const std::string &sName)
Static Public Member Functions
static void Register (RegisterWithLuaFn pfn)
Private Member Functions
LuaManager & operator= (const LuaManager &rhs)
LuaManager (const LuaManager &rhs)
Private Attributes
lua_State * m_pLuaMain
Constructor & Destructor Documentation
LuaManager() [1/2]
LuaManager::LuaManager ()
References ASSERT, L, LuaPanic(), m_pLuaMain, and RegisterTypes().
~LuaManager()
LuaManager::~LuaManager ()
References m_pLuaMain, and SAFE_DELETE.
LuaManager() [2/2]
LuaManager::LuaManager (const LuaManager & rhs) private
Member Function Documentation
Get()
Lua * LuaManager::Get ()
References ASSERT, Impl::g_ActiveStates, Impl::g_FreeStateList, Impl::g_pLock, RageMutex::IsLockedByThisThread(), RageMutex::Lock(), m_pLuaMain, and THREAD_POOL.
Referenced by Actor::Actor(), AnnouncerManager::AnnouncerManager(), GameCommand::ApplySelf(), ScoreKeeperNormal::CalcNextToastyAt(), CharacterManager::CharacterManager(), XmlFileUtil::CompileXNodeTree(), DynamicActorScroller::ConfigureActor(), LuaReference::Create(), LuaReference::CreateFromPush(), CryptManager::CryptManager(), LuaReference::DeepCopy(), DownloadManager::DownloadManager(), ActorFrame::DrawPrimitives(), OptionRowHandlerLua::ExportOption(), FilterManager::FilterManager(), FormatAnswerForDisplayFromLua(), GameManager::GameManager(), GameSoundManager::GameSoundManager(), GameState::GameState(), GetAndConvertMetric(), LuaHelpers::GetLuaInformation(), LuaReference::GetLuaType(), ThemeManager::GetMetric(), ThemeManager::GetMetricsGroupFallback(), Message::GetParam(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), XNodeLuaValue::GetValue(), ScreenWithMenuElements::HandleLuaMusicFile(), OptionRowHandlerLua::ImportOption(), ScreenSelect::Init(), ScreenSelectMaster::Init(), ScreenGameplay::Init(), ScreenOptions::InitMenu(), InputFilter::InputFilter(), ActorScroller::Load2(), NoteSkinManager::LoadActor(), Profile::LoadCustomFunction(), XMLProfile::LoadEttGeneralDataFromNode(), DynamicActorScroller::LoadFromNode(), ScoreDisplayAliveTime::LoadFromNode(), PercentageDisplay::LoadFromNode(), ActorScroller::LoadFromNode(), PaneDisplay::LoadFromNode(), Actor::LoadFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), OptionRowHandlerLua::LoadInternal(), NoteSkinManager::LoadNoteSkinDataRecursive(), LuaReference::LuaReference(), LuaTable::LuaTable(), LuaThreadVariable::LuaThreadVariable(), MemoryCardManager::MemoryCardManager(), Message::Message(), MessageManager::MessageManager(), NetworkSyncManager::NetworkSyncManager(), MusicWheel::NextSort(), NoteSkinManager::NoteSkinManager(), OptionRowHandlerLua::NotifyOfSelection(), LifeMeterBattery::OnSongEnded(), LuaReference::operator=(), ActorUtil::ParseActorCommands(), Screen::PassInputToLua(), PrefsManager::PrefsManager(), ProfileManager::ProfileManager(), RageDisplay::RageDisplay(), RageFileManager::RageFileManager(), RageInput::RageInput(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), PercentageDisplay::Refresh(), RegisterTypes(), ArchHooks::RegisterWithLua(), Actor::RunCommands(), LuaHelpers::RunScriptFile(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), ScoreManager::ScoreManager(), ScreenManager::ScreenManager(), LuaReference::Serialize(), PaneDisplay::SetContent(), OptionRowHandlerLua::SetEnabledForPlayers(), LuaReference::SetFromExpression(), SetGlobal(), Player::SetHoldJudgment(), Player::SetJudgment(), Message::SetParam(), Message::SetParamTable(), Actor::SetParent(), MenuTimer::SetText(), XNodeLuaValue::SetValue(), DynamicActorScroller::ShiftSubActors(), SongManager::SongManager(), StatsManager::StatsManager(), ThemeManager::ThemeManager(), LuaExpressionTransform::TransformItemDirect(), LuaReference::Unregister(), UnsetGlobal(), ActorFrame::UpdateInternal(), LuaClass::~LuaClass(), and LuaThreadVariable::~LuaThreadVariable().
operator=()
LuaManager& LuaManager::operator= (const LuaManager & rhs) private
Register()
void LuaManager::Register (RegisterWithLuaFn pfn) static
Referenced by RegisterLuaFunction::RegisterLuaFunction().
RegisterTypes()
void LuaManager::RegisterTypes ()
References Get(), and Release().
Referenced by LuaManager().
Release()
void LuaManager::Release (Lua *& p)
References ASSERT, Impl::g_ActiveStates, Impl::g_FreeStateList, Impl::g_pLock, and RageMutex::Unlock().
Referenced by Actor::Actor(), AnnouncerManager::AnnouncerManager(), GameCommand::ApplySelf(), ScoreKeeperNormal::CalcNextToastyAt(), CharacterManager::CharacterManager(), XmlFileUtil::CompileXNodeTree(), DynamicActorScroller::ConfigureActor(), LuaReference::Create(), LuaReference::CreateFromPush(), CryptManager::CryptManager(), LuaReference::DeepCopy(), DownloadManager::DownloadManager(), ActorFrame::DrawPrimitives(), OptionRowHandlerLua::ExportOption(), FilterManager::FilterManager(), FormatAnswerForDisplayFromLua(), GameManager::GameManager(), GameSoundManager::GameSoundManager(), GameState::GameState(), GetAndConvertMetric(), LuaHelpers::GetLuaInformation(), LuaReference::GetLuaType(), ThemeManager::GetMetric(), ThemeManager::GetMetricsGroupFallback(), Message::GetParam(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), XNodeLuaValue::GetValue(), ScreenWithMenuElements::HandleLuaMusicFile(), OptionRowHandlerLua::ImportOption(), ScreenSelect::Init(), ScreenSelectMaster::Init(), ScreenGameplay::Init(), ScreenOptions::InitMenu(), InputFilter::InputFilter(), ActorScroller::Load2(), NoteSkinManager::LoadActor(), Profile::LoadCustomFunction(), XMLProfile::LoadEttGeneralDataFromNode(), DynamicActorScroller::LoadFromNode(), ScoreDisplayAliveTime::LoadFromNode(), PercentageDisplay::LoadFromNode(), ActorScroller::LoadFromNode(), PaneDisplay::LoadFromNode(), Actor::LoadFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), OptionRowHandlerLua::LoadInternal(), NoteSkinManager::LoadNoteSkinDataRecursive(), LuaReference::LuaReference(), LuaTable::LuaTable(), LuaThreadVariable::LuaThreadVariable(), MemoryCardManager::MemoryCardManager(), Message::Message(), MessageManager::MessageManager(), NetworkSyncManager::NetworkSyncManager(), MusicWheel::NextSort(), NoteSkinManager::NoteSkinManager(), OptionRowHandlerLua::NotifyOfSelection(), LifeMeterBattery::OnSongEnded(), LuaReference::operator=(), ActorUtil::ParseActorCommands(), Screen::PassInputToLua(), PrefsManager::PrefsManager(), ProfileManager::ProfileManager(), RageDisplay::RageDisplay(), RageFileManager::RageFileManager(), RageInput::RageInput(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), PercentageDisplay::Refresh(), RegisterTypes(), ArchHooks::RegisterWithLua(), Actor::RunCommands(), LuaHelpers::RunScriptFile(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), ScoreManager::ScoreManager(), ScreenManager::ScreenManager(), LuaReference::Serialize(), PaneDisplay::SetContent(), OptionRowHandlerLua::SetEnabledForPlayers(), LuaReference::SetFromExpression(), SetGlobal(), Player::SetHoldJudgment(), Player::SetJudgment(), Message::SetParam(), Message::SetParamTable(), Actor::SetParent(), MenuTimer::SetText(), XNodeLuaValue::SetValue(), DynamicActorScroller::ShiftSubActors(), SongManager::SongManager(), StatsManager::StatsManager(), ThemeManager::ThemeManager(), LuaExpressionTransform::TransformItemDirect(), LuaReference::Unregister(), UnsetGlobal(), ActorFrame::UpdateInternal(), LuaClass::~LuaClass(), and LuaThreadVariable::~LuaThreadVariable().
SetGlobal() [1/2]
void LuaManager::SetGlobal (const std::string & sName, int val)
References Get(), L, LuaHelpers::Push(), and Release().
Referenced by ScreenDimensions::ReloadScreenDimensions().
SetGlobal() [2/2]
void LuaManager::SetGlobal (const std::string & sName, const std::string & val)
References Get(), L, LuaHelpers::Push(), and Release().
UnsetGlobal()
void LuaManager::UnsetGlobal (const std::string & sName)
References Get(), L, and Release().
Referenced by AnnouncerManager::~AnnouncerManager(), CharacterManager::~CharacterManager(), CryptManager::~CryptManager(), FilterManager::~FilterManager(), GameManager::~GameManager(), GameSoundManager::~GameSoundManager(), GameState::~GameState(), InputFilter::~InputFilter(), MemoryCardManager::~MemoryCardManager(), MessageManager::~MessageManager(), NoteSkinManager::~NoteSkinManager(), PrefsManager::~PrefsManager(), ProfileManager::~ProfileManager(), RageDisplay::~RageDisplay(), RageFileManager::~RageFileManager(), RageInput::~RageInput(), ScoreManager::~ScoreManager(), ScreenManager::~ScreenManager(), SongManager::~SongManager(), StatsManager::~StatsManager(), and ThemeManager::~ThemeManager().
UnyieldLua()
void LuaManager::UnyieldLua ()
References Impl::g_pLock, and RageMutex::Lock().
Referenced by LunaScreenProfileSave::Continue(), LunaScreenProfileLoad::Continue(), and LunaActor::Draw().
YieldLua()
void LuaManager::YieldLua ()
References ASSERT, Impl::g_pLock, RageMutex::IsLockedByThisThread(), and RageMutex::Unlock().
Referenced by LunaScreenProfileSave::Continue(), LunaScreenProfileLoad::Continue(), and LunaActor::Draw().
Member Data Documentation
m_pLuaMain
lua_State* LuaManager::m_pLuaMain private
Referenced by Get(), LuaManager(), and ~LuaManager().
The documentation for this class was generated from the following files:
LuaManager.h
LuaManager.cpp