Etterna: InputHandler_Linux_PIUIO Class Reference
InputHandler_Linux_PIUIO Class Reference
#include <InputHandler_Linux_PIUIO.h>
Public Member Functions
InputHandler_Linux_PIUIO ()
~InputHandler_Linux_PIUIO ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual bool DevicesChanged ()
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void InputThread ()
Static Private Member Functions
static int InputThread_Start (void *p)
Private Attributes
int fd
unsigned char lastInputs [8]
RageThread m_InputThread
bool m_bShutdown
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_Linux_PIUIO()
InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO ()
References RageThread::Create(), fd, RageLog::Info(), InputThread_Start(), LOG, m_bShutdown, m_InputThread, RageThread::SetName(), RageLog::Trace(), and RageLog::Warn().
~InputHandler_Linux_PIUIO()
InputHandler_Linux_PIUIO::~InputHandler_Linux_PIUIO ()
References fd, RageLog::Info(), RageThread::IsCreated(), LOG, m_bShutdown, m_InputThread, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
GetDevicesAndDescriptions()
void InputHandler_Linux_PIUIO::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References DEVICE_PIUIO.
InputThread()
void InputHandler_Linux_PIUIO::InputThread () private
References InputHandler::ButtonPressed(), DEVICE_JOY1, enum_add2(), fd, JOY_BUTTON_1, lastInputs, LOG, m_bShutdown, InputHandler::UpdateTimer(), and RageLog::Warn().
InputThread_Start()
int InputHandler_Linux_PIUIO::InputThread_Start (void * p) static private
Referenced by InputHandler_Linux_PIUIO().
Member Data Documentation
fd
int InputHandler_Linux_PIUIO::fd private
Referenced by InputHandler_Linux_PIUIO(), InputThread(), and ~InputHandler_Linux_PIUIO().
lastInputs
unsigned char InputHandler_Linux_PIUIO::lastInputs[8] private
Referenced by InputThread().
m_bShutdown
bool InputHandler_Linux_PIUIO::m_bShutdown private
Referenced by InputHandler_Linux_PIUIO(), InputThread(), and ~InputHandler_Linux_PIUIO().
m_InputThread
RageThread InputHandler_Linux_PIUIO::m_InputThread private
Referenced by InputHandler_Linux_PIUIO(), and ~InputHandler_Linux_PIUIO().
The documentation for this class was generated from the following files:
InputHandler_Linux_PIUIO.h
InputHandler_Linux_PIUIO.cpp