Etterna: RageTypes.h File Reference
RageTypes.h File Reference
#include "global.h"
#include "EnumHelper.h"
Classes
struct RageVector2
struct RageVector3
struct RageVector4
struct RageColor
class RageVColor
class StepMania::Rect< T >
struct RageSpriteVertex
struct RageModelVertex
struct RageMatrix
Namespaces
StepMania
Utility functions for controlling the whole game.
Macros
#define COMPARE(x)
Typedefs
using RectI = StepMania::Rect< int >
using RectF = StepMania::Rect< float >
Enumerations
enum BlendMode {
BLEND_NORMAL, BLEND_ADD, BLEND_SUBTRACT, BLEND_MODULATE,
BLEND_COPY_SRC, BLEND_ALPHA_MASK, BLEND_ALPHA_KNOCK_OUT, BLEND_ALPHA_MULTIPLY,
BLEND_WEIGHTED_MULTIPLY, BLEND_INVERT_DEST, BLEND_NO_EFFECT, NUM_BlendMode,
BlendMode_Invalid
}
enum TextureMode {
TextureMode_Modulate, TextureMode_Glow, TextureMode_Add, NUM_TextureMode,
TextureMode_Invalid
}
enum EffectMode {
EffectMode_Normal, EffectMode_Unpremultiply, EffectMode_ColorBurn, EffectMode_ColorDodge,
EffectMode_VividLight, EffectMode_HardMix, EffectMode_Overlay, EffectMode_Screen,
EffectMode_YUYV422, NUM_EffectMode, EffectMode_Invalid
}
enum CullMode {
CULL_BACK, CULL_FRONT, CULL_NONE, NUM_CullMode,
CullMode_Invalid
}
enum ZTestMode {
ZTEST_OFF, ZTEST_WRITE_ON_PASS, ZTEST_WRITE_ON_FAIL, NUM_ZTestMode,
ZTestMode_Invalid
}
enum PolygonMode { POLYGON_FILL, POLYGON_LINE, NUM_PolygonMode, PolygonMode_Invalid }
enum TextGlowMode {
TextGlowMode_Inner, TextGlowMode_Stroke, TextGlowMode_Both, NUM_TextGlowMode,
TextGlowMode_Invalid
}
Functions
LuaDeclareType (BlendMode)
LuaDeclareType (TextureMode)
LuaDeclareType (EffectMode)
LuaDeclareType (CullMode)
LuaDeclareType (ZTestMode)
LuaDeclareType (PolygonMode)
LuaDeclareType (TextGlowMode)
unsigned char FTOC (float a)
void lerp_rage_color (RageColor &out, RageColor const &a, RageColor const &b, float t)
void WeightedAvergeOfRSVs (RageSpriteVertex &average_out, RageSpriteVertex const &rsv1, RageSpriteVertex const &rsv2, float percent_between)
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if (x != other.x)                                                          \
    return false
Referenced by StepMania::Rect< float >::operator==().
Typedef Documentation
RectF
using RectF = StepMania::Rect<float>
RectI
using RectI = StepMania::Rect<int>
Enumeration Type Documentation
BlendMode
enum BlendMode
Enumerator
BLEND_NORMAL
BLEND_ADD
BLEND_SUBTRACT
BLEND_MODULATE
BLEND_COPY_SRC
BLEND_ALPHA_MASK
BLEND_ALPHA_KNOCK_OUT
BLEND_ALPHA_MULTIPLY
BLEND_WEIGHTED_MULTIPLY
BLEND_INVERT_DEST
BLEND_NO_EFFECT
NUM_BlendMode
BlendMode_Invalid
CullMode
enum CullMode
Enumerator
CULL_BACK
CULL_FRONT
CULL_NONE
NUM_CullMode
CullMode_Invalid
EffectMode
enum EffectMode
Enumerator
EffectMode_Normal
EffectMode_Unpremultiply
EffectMode_ColorBurn
EffectMode_ColorDodge
EffectMode_VividLight
EffectMode_HardMix
EffectMode_Overlay
EffectMode_Screen
EffectMode_YUYV422
NUM_EffectMode
EffectMode_Invalid
PolygonMode
enum PolygonMode
Enumerator
POLYGON_FILL
POLYGON_LINE
NUM_PolygonMode
PolygonMode_Invalid
TextGlowMode
enum TextGlowMode
Enumerator
TextGlowMode_Inner
TextGlowMode_Stroke
TextGlowMode_Both
NUM_TextGlowMode
TextGlowMode_Invalid
TextureMode
enum TextureMode
Enumerator
TextureMode_Modulate
TextureMode_Glow
TextureMode_Add
NUM_TextureMode
TextureMode_Invalid
ZTestMode
enum ZTestMode
Enumerator
ZTEST_OFF
ZTEST_WRITE_ON_PASS
ZTEST_WRITE_ON_FAIL
NUM_ZTestMode
ZTestMode_Invalid
Function Documentation
FTOC()
unsigned char FTOC (float a) inline
References CLAMP().
Referenced by RageVColor::operator=().
lerp_rage_color()
void lerp_rage_color (RageColor & out, RageColor const & a, RageColor const & b, float t)
References RageColor::a, RageColor::b, RageColor::g, lerp(), and RageColor::r.
Referenced by LuaFunc_lerp_color().
LuaDeclareType() [1/7]
LuaDeclareType (BlendMode)
LuaDeclareType() [2/7]
LuaDeclareType (TextureMode)
LuaDeclareType() [3/7]
LuaDeclareType (EffectMode)
LuaDeclareType() [4/7]
LuaDeclareType (CullMode)
LuaDeclareType() [5/7]
LuaDeclareType (ZTestMode)
LuaDeclareType() [6/7]
LuaDeclareType (PolygonMode)
LuaDeclareType() [7/7]
LuaDeclareType (TextGlowMode)
WeightedAvergeOfRSVs()
void WeightedAvergeOfRSVs (RageSpriteVertex & average_out, RageSpriteVertex const & rsv1, RageSpriteVertex const & rsv2, float percent_between)
References RageVColor::a, RageVColor::b, RageSpriteVertex::c, RageVColor::g, lerp(), RageSpriteVertex::n, RageSpriteVertex::p, RageVColor::r, and RageSpriteVertex::t.
Referenced by ActorMultiVertex::AMV_TweenState::MakeWeightedAverage().