Etterna: LunaSongManager Class Reference
LunaSongManager Class Reference
Allow Lua to have access to the SongManager.
Public Member Functions
DEFINE_METHOD (GetSongColor, GetSongColor(Luna< Song >::check(L, 1))) DEFINE_METHOD(GetSongGroupColor
GetSongGroupColor (SArg(1))) static int GetSongRank(T *p
if (index !=-1) lua_pushnumber(L
else lua_pushnil (L)
DEFINE_METHOD (ShortenGroupName, ShortenGroupName(SArg(1))) DEFINE_METHOD(GetSongGroupBannerPath
GetSongGroupBannerPath (SArg(1)))
DEFINE_METHOD (DoesSongGroupExist, DoesSongGroupExist(SArg(1)))
DEFINE_METHOD (IsChartLoaded, IsChartLoaded(SArg(1)))
LunaSongManager ()
Public Member Functions inherited from Luna< SongManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetPreferredSongs (T *p, lua_State *L)
static int GetAllSongs (T *p, lua_State *L)
static int DifferentialReload (T *p, lua_State *L)
static int GetPreferredSortSongs (T *p, lua_State *L)
static int FindSong (T *p, lua_State *L)
static int GetRandomSong (T *p, lua_State *L)
static int GetNumSongs (T *p, lua_State *L)
static int GetNumAdditionalSongs (T *p, lua_State *L)
static int GetNumSongGroups (T *p, lua_State *L)
static int GetSongFromSteps (T *p, lua_State *L)
static int GetExtraStageInfo (T *p, lua_State *L)
static int GetSongGroupNames (T *p, lua_State *L)
static int GetSongsInGroup (T *p, lua_State *L)
static int GetPopularSongs (T *p, lua_State *L)
static int SongToPreferredSortSectionName (T *p, lua_State *L)
static int WasLoadedFromAdditionalSongs (T *p, lua_State *L)
static int GetSongByChartKey (T *p, lua_State *L)
static int GetStepsByChartKey (T *p, lua_State *L)
static int GetNumCourses (T *p, lua_State *L)
static int GetActivePlaylist (T *p, lua_State *L)
static int SetActivePlaylist (T *p, lua_State *L)
static int NewPlaylist (T *p, lua_State *L)
static int GetPlaylists (T *p, lua_State *L)
static int DeletePlaylist (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< SongManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Public Attributes
lua_State * L
int index = p->GetSongRank(pSong)
index
return
Additional Inherited Members
Static Public Attributes inherited from Luna< SongManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< SongManager >
using T = SongManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< SongManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the SongManager.
Constructor & Destructor Documentation
LunaSongManager()
LunaSongManager::LunaSongManager () inline
References ADD_METHOD, DeletePlaylist(), DifferentialReload(), FindSong(), GetActivePlaylist(), GetAllSongs(), GetExtraStageInfo(), GetNumAdditionalSongs(), GetNumCourses(), GetNumSongGroups(), GetNumSongs(), GetPlaylists(), GetPopularSongs(), GetPreferredSortSongs(), GetRandomSong(), GetSongByChartKey(), GetSongFromSteps(), GetSongGroupBannerPath(), GetSongGroupNames(), GetSongsInGroup(), GetStepsByChartKey(), NewPlaylist(), SetActivePlaylist(), SetPreferredSongs(), SongToPreferredSortSectionName(), and WasLoadedFromAdditionalSongs().
Member Function Documentation
DEFINE_METHOD() [1/4]
LunaSongManager::DEFINE_METHOD (GetSongColor , GetSongColor(Luna< Song >::check(L, 1)))
DEFINE_METHOD() [2/4]
LunaSongManager::DEFINE_METHOD (ShortenGroupName , ShortenGroupName(SArg(1)))
DEFINE_METHOD() [3/4]
LunaSongManager::DEFINE_METHOD (DoesSongGroupExist , DoesSongGroupExist(SArg(1)))
DEFINE_METHOD() [4/4]
LunaSongManager::DEFINE_METHOD (IsChartLoaded , IsChartLoaded(SArg(1)))
DeletePlaylist()
static int LunaSongManager::DeletePlaylist (T * p, lua_State * L) inline static
References SongManager::DeletePlaylist(), PLAYER_1, PROFILEMAN, SArg, and ProfileManager::SaveProfile().
Referenced by LunaSongManager().
DifferentialReload()
static int LunaSongManager::DifferentialReload (T * p, lua_State * L) inline static
References SongManager::DifferentialReload().
Referenced by LunaSongManager().
FindSong()
static int LunaSongManager::FindSong (T * p, lua_State * L) inline static
References SongManager::FindSong(), lua_pushnil(), Song::PushSelf(), and SArg.
Referenced by LunaSongManager().
GetActivePlaylist()
static int LunaSongManager::GetActivePlaylist (T * p, lua_State * L) inline static
References SongManager::activeplaylist, and SongManager::GetPlaylists().
Referenced by LunaSongManager().
GetAllSongs()
static int LunaSongManager::GetAllSongs (T * p, lua_State * L) inline static
References SongManager::GetAllSongs(), and L.
Referenced by LunaSongManager().
GetExtraStageInfo()
static int LunaSongManager::GetExtraStageInfo (T * p, lua_State * L) inline static
References BArg, Luna< Type >::check(), SongManager::GetExtraStageInfo(), Steps::PushSelf(), and Song::PushSelf().
Referenced by LunaSongManager().
GetNumAdditionalSongs()
static int LunaSongManager::GetNumAdditionalSongs (T * p, lua_State * L) inline static
References SongManager::GetNumAdditionalSongs().
Referenced by LunaSongManager().
GetNumCourses()
static int LunaSongManager::GetNumCourses (T * p, lua_State * L) inline static
Referenced by LunaSongManager().
GetNumSongGroups()
static int LunaSongManager::GetNumSongGroups (T * p, lua_State * L) inline static
References SongManager::GetNumSongGroups().
Referenced by LunaSongManager().
GetNumSongs()
static int LunaSongManager::GetNumSongs (T * p, lua_State * L) inline static
References SongManager::GetNumSongs().
Referenced by LunaSongManager().
GetPlaylists()
static int LunaSongManager::GetPlaylists (T * p, lua_State * L) inline static
References FOREACHM, and SongManager::GetPlaylists().
Referenced by LunaSongManager().
GetPopularSongs()
static int LunaSongManager::GetPopularSongs (T * p, lua_State * L) inline static
References L.
Referenced by LunaSongManager().
GetPreferredSortSongs()
static int LunaSongManager::GetPreferredSortSongs (T * p, lua_State * L) inline static
References SongManager::GetPreferredSortSongs(), and L.
Referenced by LunaSongManager().
GetRandomSong()
static int LunaSongManager::GetRandomSong (T * p, lua_State * L) inline static
References SongManager::GetRandomSong(), lua_pushnil(), and Song::PushSelf().
Referenced by LunaSongManager().
GetSongByChartKey()
static int LunaSongManager::GetSongByChartKey (T * p, lua_State * L) inline static
References SongManager::GetSongByChartkey(), lua_pushnil(), Song::PushSelf(), and SArg.
Referenced by LunaSongManager().
GetSongFromSteps()
static int LunaSongManager::GetSongFromSteps (T * p, lua_State * L) inline static
References Luna< Type >::check(), lua_pushnil(), Steps::m_pSong, and Song::PushSelf().
Referenced by LunaSongManager().
GetSongGroupBannerPath()
LunaSongManager::GetSongGroupBannerPath (SArg(1))
Referenced by LunaSongManager().
GetSongGroupColor()
LunaSongManager::GetSongGroupColor (SArg(1))
GetSongGroupNames()
static int LunaSongManager::GetSongGroupNames (T * p, lua_State * L) inline static
References SongManager::GetSongGroupNames(), and L.
Referenced by LunaSongManager().
GetSongsInGroup()
static int LunaSongManager::GetSongsInGroup (T * p, lua_State * L) inline static
References SongManager::GetSongs(), L, and SArg.
Referenced by LunaSongManager().
GetStepsByChartKey()
static int LunaSongManager::GetStepsByChartKey (T * p, lua_State * L) inline static
References SongManager::GetStepsByChartkey(), lua_pushnil(), Steps::PushSelf(), and SArg.
Referenced by LunaSongManager().
if()
LunaSongManager::if (index ! = -1)
lua_pushnil()
else LunaSongManager::lua_pushnil (L)
Referenced by FindSong(), GetRandomSong(), GetSongByChartKey(), GetSongFromSteps(), and GetStepsByChartKey().
NewPlaylist()
static int LunaSongManager::NewPlaylist (T * p, lua_State * L) inline static
References makePlaylist(), SM_None, and ScreenTextEntry::TextEntry().
Referenced by LunaSongManager().
SetActivePlaylist()
static int LunaSongManager::SetActivePlaylist (T * p, lua_State * L) inline static
References SongManager::activeplaylist, and SArg.
Referenced by LunaSongManager().
SetPreferredSongs()
static int LunaSongManager::SetPreferredSongs (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and SongManager::UpdatePreferredSort().
Referenced by LunaSongManager().
SongToPreferredSortSectionName()
static int LunaSongManager::SongToPreferredSortSectionName (T * p, lua_State * L) inline static
References Luna< Type >::check(), and SongManager::SongToPreferredSortSectionName().
Referenced by LunaSongManager().
WasLoadedFromAdditionalSongs()
static int LunaSongManager::WasLoadedFromAdditionalSongs (T * p, lua_State * L) inline static
References Luna< Type >::check(), and SongManager::WasLoadedFromAdditionalSongs().
Referenced by LunaSongManager().
Member Data Documentation
index [1/2]
int LunaSongManager::index = p->GetSongRank(pSong)
index [2/2]
LunaSongManager::index
L
lua_State* LunaSongManager::L
Initial value:
{
        Song* pSong = Luna<Song>::check(L, 1)
Referenced by GetAllSongs(), GetPopularSongs(), GetPreferredSortSongs(), GetSongGroupNames(), and GetSongsInGroup().
return
LunaSongManager::return
The documentation for this class was generated from the following file:
SongManager.cpp