Etterna: LowLevelWindow_Win32.cpp File Reference
LowLevelWindow_Win32.cpp File Reference
#include "LowLevelWindow_Win32.h"
#include "LocalizedString.h"
#include "RageDisplay.h"
#include "RageDisplay_OGL.h"
#include "RageDisplay_OGL_Helpers.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Win32/DirectXHelpers.h"
#include "archutils/Win32/ErrorStrings.h"
#include "archutils/Win32/GraphicsWindow.h"
#include "global.h"
#include <GL/glew.h>
Classes
class RenderTarget_Win32
Functions
static void DestroyGraphicsWindowAndOpenGLContext ()
int ChooseWindowPixelFormat (const VideoModeParams &p, PIXELFORMATDESCRIPTOR *pixfmt)
void DumpPixelFormat (const PIXELFORMATDESCRIPTOR &pfd)
Variables
static PIXELFORMATDESCRIPTOR g_CurrentPixelFormat
static HGLRC g_HGLRC = NULL
static HGLRC g_HGLRC_Background = NULL
static LocalizedString OPENGL_NOT_AVAILABLE ("LowLevelWindow_Win32", "OpenGL hardware acceleration is not available.")
Function Documentation
ChooseWindowPixelFormat()
int ChooseWindowPixelFormat (const VideoModeParams & p, PIXELFORMATDESCRIPTOR * pixfmt)
References ASSERT, VideoModeParams::bpp, and ZERO.
Referenced by LowLevelWindow_Win32::TryVideoMode().
DestroyGraphicsWindowAndOpenGLContext()
static void DestroyGraphicsWindowAndOpenGLContext () static
References g_CurrentPixelFormat, g_HGLRC, g_HGLRC_Background, and ZERO.
Referenced by LowLevelWindow_Win32::TryVideoMode(), and LowLevelWindow_Win32::~LowLevelWindow_Win32().
DumpPixelFormat()
void DumpPixelFormat (const PIXELFORMATDESCRIPTOR & pfd)
References RageLog::Info(), LOG, ssprintf(), and RageLog::Warn().
Referenced by LowLevelWindow_Win32::TryVideoMode().
Variable Documentation
g_CurrentPixelFormat
PIXELFORMATDESCRIPTOR g_CurrentPixelFormat static
Referenced by DestroyGraphicsWindowAndOpenGLContext(), and LowLevelWindow_Win32::TryVideoMode().
g_HGLRC
HGLRC g_HGLRC = NULL static
Referenced by DestroyGraphicsWindowAndOpenGLContext(), LowLevelWindow_Win32::LowLevelWindow_Win32(), RenderTarget_Win32::StartRenderingTo(), and LowLevelWindow_Win32::TryVideoMode().
g_HGLRC_Background
HGLRC g_HGLRC_Background = NULL static
Referenced by LowLevelWindow_Win32::BeginConcurrentRendering(), DestroyGraphicsWindowAndOpenGLContext(), LowLevelWindow_Win32::LowLevelWindow_Win32(), LowLevelWindow_Win32::SupportsThreadedRendering(), and LowLevelWindow_Win32::TryVideoMode().
OPENGL_NOT_AVAILABLE
LocalizedString OPENGL_NOT_AVAILABLE("LowLevelWindow_Win32", "OpenGL hardware acceleration is not available.") static
Referenced by LowLevelWindow_Win32::IsSoftwareRenderer().