Etterna: Screen Class Reference
Screen Class Reference
Class that holds a screen-full of Actors.
#include <Screen.h>
Classes
struct QueuedScreenMessage
Holds the messages sent to a Screen.
Public Member Functions
~Screen () override
virtual void Init ()
This is called immediately after construction, to allow initializing after all derived classes exist.
virtual void BeginScreen ()
This is called immediately before the screen is used.
virtual void EndScreen ()
This is called when the screen is popped.
void Update (float fDeltaTime) override
virtual bool Input (const InputEventPlus &input)
virtual void HandleScreenMessage (ScreenMessage SM)
void SetLockInputSecs (float f)
void PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
void ClearMessageQueue ()
Clear the entire message queue.
void ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
virtual ScreenType GetScreenType () const
bool AllowOperatorMenuButton () const
virtual bool AllowLateJoin () const
Determine if we allow extra players to join in on this screen.
void PushSelf (lua_State *L) override
RString GetNextScreenName () const
RString GetPrevScreen () const
void SetNextScreenName (RString const &name)
void SetPrevScreenName (RString const &name)
bool PassInputToLua (const InputEventPlus &input)
void AddInputCallbackFromStack (lua_State *L)
void RemoveInputCallback (lua_State *L)
virtual bool AllowCallbackInput ()
virtual bool MenuUp (const InputEventPlus &)
virtual bool MenuDown (const InputEventPlus &)
virtual bool MenuLeft (const InputEventPlus &)
virtual bool MenuRight (const InputEventPlus &)
virtual bool MenuStart (const InputEventPlus &)
virtual bool MenuSelect (const InputEventPlus &)
virtual bool MenuBack (const InputEventPlus &)
virtual bool MenuCoin (const InputEventPlus &)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Static Public Member Functions
static void InitScreen (Screen *pScreen)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Static Protected Member Functions
static bool SortMessagesByDelayRemaining (const QueuedScreenMessage &m1, const QueuedScreenMessage &m2)
Protected Attributes
vector< QueuedScreenMessage > m_QueuedMessages
The list of messages that are sent to a Screen.
InputQueueCodeSet m_Codes
ThemeMetric< bool > ALLOW_OPERATOR_MENU_BUTTON
Do we allow the operator menu button to be pressed here?
ThemeMetric< bool > HANDLE_BACK_BUTTON
Do we handle the back button being pressed here?
ThemeMetric< float > REPEAT_RATE
ThemeMetric< float > REPEAT_DELAY
RString m_sNextScreen
The next screen to go to once this screen is done.
RString m_sPrevScreen
ScreenMessage m_smSendOnPop
float m_fLockInputSecs
bool m_bRunning
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Private Types
using callback_key_t = const void *
Private Member Functions
void InternalRemoveCallback (callback_key_t key)
Private Attributes
map< callback_key_t, LuaReference > m_InputCallbacks
vector< callback_key_t > orderedcallbacks
vector< callback_key_t > m_DelayedCallbackRemovals
bool m_CallingInputCallbacks
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
Class that holds a screen-full of Actors.
Member Typedef Documentation
callback_key_t
using Screen::callback_key_t = const void* private
Constructor & Destructor Documentation
~Screen()
Screen::~Screen () override default
Member Function Documentation
AddInputCallbackFromStack()
void Screen::AddInputCallbackFromStack (lua_State * L)
References m_InputCallbacks, and orderedcallbacks.
Referenced by LunaScreen::AddInputCallback().
AllowCallbackInput()
virtual bool Screen::AllowCallbackInput () inline virtual
Reimplemented in ScreenWithMenuElements.
Referenced by PassInputToLua().
AllowLateJoin()
virtual bool Screen::AllowLateJoin () const inline virtual
Determine if we allow extra players to join in on this screen.
Returns
false, for players should never be able to join while in progress.
Reimplemented in ScreenSelectMaster, ScreenSelectMusic, ScreenWithMenuElements, and ScreenContinue.
AllowOperatorMenuButton()
bool Screen::AllowOperatorMenuButton () const inline
References ALLOW_OPERATOR_MENU_BUTTON.
BeginScreen()
void Screen::BeginScreen () virtual
This is called immediately before the screen is used.
Reimplemented in ScreenMiniMenu, ScreenTextEntryVisual, ScreenTextEntry, ScreenGameplay, ScreenPrompt, ScreenOptions, ScreenSelectMusic, ScreenOptionsExportPackageSubPage, ScreenSelectMaster, ScreenOptionsToggleSongsSubPage, ScreenRanking, ScreenNetSelectMusic, ScreenMapControllers, ScreenOptionsExportPackage, ScreenWithMenuElements, ScreenAttract, ScreenOptionsToggleSongs, ScreenContinue, ScreenOptionsEditProfile, ScreenSplash, ScreenOptionsCourseOverview, ScreenPlayerOptions, ScreenSelect, ScreenSelectLanguage, ScreenOptionsManageProfiles, ScreenServiceAction, ScreenProfileLoad, and ScreenProfileSave.
References ThemeManager::GetMetricA(), Actor::m_bFirstUpdate, m_bRunning, m_fLockInputSecs, Actor::m_sName, m_sNextScreen, Actor::PlayCommand(), ActorFrame::RunCommands(), and THEME.
Referenced by ScreenWithMenuElements::BeginScreen(), DebugLineRestartCurrentScreen::DoAndLog(), ScreenManagerUtil::PushLoadedScreen(), and ScreenManager::ReloadOverlayScreens().
ClearMessageQueue() [1/2]
void Screen::ClearMessageQueue ()
Clear the entire message queue.
References m_QueuedMessages.
Referenced by ScreenGameplay::BeginBackingOutFromGameplay(), ScreenSelectMusic::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenGameplayLesson::Init(), and ScreenSelectMusic::Input().
ClearMessageQueue() [2/2]
void Screen::ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
Parameters
SM the specific ScreenMessage to get out of the Queue.
References m_QueuedMessages.
EndScreen()
void Screen::EndScreen () virtual
This is called when the screen is popped.
References m_bRunning, and Actor::PlayCommand().
Referenced by ScreenManager::PopTopScreenInternal().
GetNextScreenName()
RString Screen::GetNextScreenName () const
References m_sNextScreen, and NEXT_SCREEN.
Referenced by LunaScreen::GetNextScreenName(), ScreenSplash::HandleScreenMessage(), ScreenAttract::HandleScreenMessage(), ScreenOptions::HandleScreenMessage(), and HandleScreenMessage().
GetPrevScreen()
RString Screen::GetPrevScreen () const
References m_sPrevScreen, and PREV_SCREEN.
Referenced by ScreenWithMenuElements::Cancel(), LunaScreen::GetPrevScreenName(), HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), and ScreenGameplay::Input().
GetScreenType()
virtual ScreenType Screen::GetScreenType () const inline virtual
Reimplemented in ScreenGameplay, ScreenAttract, and ScreenGameplaySyncMachine.
References ALLOW_OPERATOR_MENU_BUTTON, game_menu, and system_menu.
Referenced by RageDisplay::FrameLimitAfterVsync(), RageDisplay::FrameLimitBeforeVsync(), IsGameplay(), and RageTextureManager::Update().
HandleScreenMessage()
void Screen::HandleScreenMessage (ScreenMessage SM) virtual
Reimplemented in ScreenMiniMenu, ScreenGameplay, ScreenEvaluation, ScreenOptions, ScreenSelectMaster, ScreenSelectMusic, ScreenRanking, ScreenNetEvaluation, ScreenNetSelectMusic, ScreenAttract, ScreenMapControllers, ScreenOptionsEditProfile, ScreenHowToPlay, ScreenOptionsCourseOverview, ScreenPackages, ScreenWithMenuElements, ScreenSelectProfile, ScreenGameplaySyncMachine, ScreenNetRoom, ScreenNetSelectBase, ScreenOptionsMaster, ScreenSelect, ScreenContinue, ScreenGameplayLesson, ScreenPlayerOptions, ScreenSplash, ScreenOptionsManageProfiles, ScreenNetworkOptions, ScreenSandbox, and ScreenSMOnlineLogin.
References f, GetNextScreenName(), GetPrevScreen(), INPUTFILTER, ScreenManager::IsStackedScreen(), m_smSendOnPop, ScreenManager::PopTopScreen(), REPEAT_DELAY, REPEAT_RATE, LuaHelpers::ReportScriptError(), InputFilter::ResetRepeatRate(), SCREENMAN, ScreenManager::SetNewScreen(), InputFilter::SetRepeatDelay(), InputFilter::SetRepeatRate(), SM_GainFocus, SM_GoToNextScreen, SM_GoToPrevScreen, and SM_LoseFocus.
Referenced by ScreenSandbox::HandleScreenMessage(), ScreenWithMenuElements::HandleScreenMessage(), ScreenManager::PopTopScreenInternal(), ScreenManager::SendMessageToTopScreen(), and Update().
Init()
void Screen::Init () virtual
This is called immediately after construction, to allow initializing after all derived classes exist.
Don't call it directly; use InitScreen instead.
Reimplemented in ScreenMiniMenu, ScreenTextEntryVisual, ScreenTextEntry, ScreenGameplay, ScreenEvaluation, ScreenPrompt, ScreenOptions, ScreenSelectMusic, ScreenOptionsExportPackageSubPage, ScreenSelectMaster, ScreenRanking, ScreenSetTime, ScreenDebugOverlay, ScreenNetSelectMusic, ScreenMapControllers, ScreenOptionsExportPackage, ScreenPackages, ScreenStatsOverlay, ScreenHowToPlay, ScreenNetRoom, ScreenReloadSongs, ScreenWithMenuElements, ScreenAttract, ScreenNetSelectBase, ScreenTestSound, ScreenInstallOverlay, ScreenSystemLayer, ScreenContinue, ScreenGameplayLesson, ScreenOptionsEditProfile, ScreenSelectProfile, ScreenSplash, ScreenTitleMenu, ScreenNetEvaluation, ScreenOptionsMaster, ScreenOptionsCourseOverview, ScreenPlayerOptions, ScreenSaveSync, ScreenSelect, ScreenExit, ScreenGameplaySyncMachine, ScreenOptionsManageProfiles, ScreenSelectLanguage, ScreenSyncOverlay, ScreenNetworkOptions, ScreenProfileLoad, ScreenSMOnlineLogin, and ScreenSongOptions.
References ALLOW_OPERATOR_MENU_BUTTON, GROUPED_SCREENS, ScreenManager::GroupScreen(), HANDLE_BACK_BUTTON, InputQueueCodeSet::Load(), ThemeMetric< T >::Load(), ActorUtil::LoadAllCommandsFromName(), LOG, m_bRunning, m_CallingInputCallbacks, m_Codes, m_smSendOnPop, Actor::m_sName, PERSIST_SCREENS, ScreenManager::PersistantScreen(), Actor::PlayCommandNoRecurse(), PREPARE_SCREENS, ScreenManager::PrepareScreen(), REPEAT_DELAY, REPEAT_RATE, SCREENMAN, ActorFrame::SetFOV(), SM_None, split(), and RageLog::Trace().
Referenced by ScreenExit::Init(), ScreenSyncOverlay::Init(), ScreenInstallOverlay::Init(), ScreenSystemLayer::Init(), ScreenTestSound::Init(), ScreenReloadSongs::Init(), ScreenWithMenuElements::Init(), ScreenStatsOverlay::Init(), ScreenDebugOverlay::Init(), and InitScreen().
InitScreen()
void Screen::InitScreen (Screen * pScreen) static
References Init().
Input()
bool Screen::Input (const InputEventPlus & input) virtual
Reimplemented in ScreenTextEntry, ScreenGameplay, ScreenEvaluation, ScreenOptions, ScreenPrompt, ScreenSelectMusic, ScreenSetTime, ScreenNetSelectMusic, ScreenAttract, ScreenDebugOverlay, ScreenMapControllers, ScreenTestSound, ScreenInstallOverlay, ScreenNetRoom, ScreenNetSelectBase, ScreenSelect, ScreenContinue, ScreenGameplayLesson, ScreenPlayerOptions, ScreenTitleMenu, ScreenGameplaySyncMachine, ScreenSelectProfile, ScreenSyncOverlay, ScreenTestInput, ScreenProfileLoad, ScreenProfileSave, ScreenInstructions, and ScreenSandbox.
References MessageManager::Broadcast(), DEVICE_MOUSE, InputEventPlus::DeviceI, GAME_BUTTON_BACK, GAME_BUTTON_COIN, GAME_BUTTON_MENUDOWN, GAME_BUTTON_MENULEFT, GAME_BUTTON_MENURIGHT, GAME_BUTTON_MENUUP, GAME_BUTTON_SELECT, GAME_BUTTON_START, HANDLE_BACK_BUTTON, ActorFrame::HandleMessage(), IET_FIRST_PRESS, IET_REPEAT, InputQueueCodeSet::InputMessage(), m_Codes, MenuBack(), MenuCoin(), MenuDown(), InputEventPlus::MenuI, MenuLeft(), MenuRight(), MenuSelect(), MenuStart(), MenuUp(), Message_LeftClick, Message_MiddleClick, Message_MouseWheelDown, Message_MouseWheelUp, Message_RightClick, MESSAGEMAN, MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT, MOUSE_WHEELDOWN, MOUSE_WHEELUP, and InputEventPlus::type.
Referenced by ScreenInstructions::Input(), ScreenSandbox::Input(), ScreenSyncOverlay::Input(), ScreenTestInput::Input(), ScreenSelectProfile::Input(), ScreenGameplayLesson::Input(), ScreenContinue::Input(), ScreenNetSelectBase::Input(), ScreenInstallOverlay::Input(), ScreenSelect::Input(), ScreenAttract::Input(), ScreenDebugOverlay::Input(), ScreenManager::Input(), ScreenNetSelectMusic::Input(), ScreenSetTime::Input(), ScreenSelectMusic::Input(), ScreenPrompt::Input(), ScreenOptions::Input(), ScreenEvaluation::Input(), and ScreenTextEntry::Input().
InternalRemoveCallback()
void Screen::InternalRemoveCallback (callback_key_t key) private
References m_InputCallbacks.
Referenced by PassInputToLua(), and RemoveInputCallback().
MenuBack()
virtual bool Screen::MenuBack (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntry, ScreenOptions, ScreenWithMenuElementsSimple, ScreenEvaluation, ScreenPrompt, ScreenSelectMusic, ScreenNetSelectMusic, ScreenSetTime, ScreenNetRoom, ScreenPackages, ScreenSelect, ScreenGameplayLesson, ScreenSplash, ScreenTestInput, ScreenSelectLanguage, and ScreenInstructions.
Referenced by Input(), ScreenPackages::MenuBack(), and ScreenNetRoom::MenuBack().
MenuCoin()
virtual bool Screen::MenuCoin (const InputEventPlus &) inline virtual
Referenced by Input().
MenuDown()
virtual bool Screen::MenuDown (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntryVisual, ScreenOptions, ScreenNetSelectMusic, ScreenSelectMaster, ScreenSetTime, ScreenNetEvaluation, ScreenPackages, and ScreenSelectProfile.
Referenced by Input(), and ScreenPackages::MenuDown().
MenuLeft()
virtual bool Screen::MenuLeft (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntryVisual, ScreenOptions, ScreenPrompt, ScreenNetRoom, ScreenNetSelectMusic, ScreenSelectMaster, ScreenSetTime, ScreenPackages, ScreenNetEvaluation, and ScreenSelectProfile.
Referenced by Input(), ScreenPackages::MenuLeft(), and ScreenNetRoom::MenuLeft().
MenuRight()
virtual bool Screen::MenuRight (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntryVisual, ScreenOptions, ScreenPrompt, ScreenNetRoom, ScreenNetSelectMusic, ScreenSelectMaster, ScreenSetTime, ScreenPackages, ScreenNetEvaluation, and ScreenSelectProfile.
Referenced by Input(), ScreenPackages::MenuRight(), and ScreenNetRoom::MenuRight().
MenuSelect()
virtual bool Screen::MenuSelect (const InputEventPlus &) inline virtual
Reimplemented in ScreenOptions, and ScreenSetTime.
Referenced by Input().
MenuStart()
virtual bool Screen::MenuStart (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntryVisual, ScreenTextEntry, ScreenOptions, ScreenWithMenuElementsSimple, ScreenEvaluation, ScreenPrompt, ScreenSelectMusic, ScreenSelectMaster, ScreenNetSelectMusic, ScreenNetRoom, ScreenSetTime, ScreenPackages, ScreenGameplayLesson, ScreenSplash, ScreenTestInput, ScreenNetworkOptions, ScreenSelectLanguage, ScreenInstructions, and ScreenSMOnlineLogin.
Referenced by ScreenWithMenuElements::HandleScreenMessage(), Input(), ScreenPackages::MenuStart(), and ScreenNetRoom::MenuStart().
MenuUp()
virtual bool Screen::MenuUp (const InputEventPlus &) inline virtual
Reimplemented in ScreenTextEntryVisual, ScreenOptions, ScreenNetSelectMusic, ScreenSelectMaster, ScreenSetTime, ScreenNetEvaluation, ScreenPackages, and ScreenSelectProfile.
Referenced by Input(), and ScreenPackages::MenuUp().
PassInputToLua()
bool Screen::PassInputToLua (const InputEventPlus & input)
References AllowCallbackInput(), DeviceInput::bDown, GameInput::button, DeviceInput::button, GameInput::controller, DeviceInput::device, InputEventPlus::DeviceI, RageInput::DeviceInputToChar(), GameButtonToString(), InputEventPlus::GameI, LuaManager::Get(), InputMapper::GetInputScheme(), INPUTMAN, INPUTMAPPER, InternalRemoveCallback(), DeviceInput::IsJoystick(), DeviceInput::IsMouse(), L, DeviceInput::level, LUA, m_CallingInputCallbacks, m_DelayedCallbackRemovals, m_fLockInputSecs, m_InputCallbacks, InputEventPlus::MenuI, InputEventPlus::mp, orderedcallbacks, InputEventPlus::pn, Enum::Push(), LuaHelpers::Push(), LuaManager::Release(), LuaHelpers::RunScriptOnStack(), DeviceInput::ts, InputEventPlus::type, and DeviceInput::z.
Referenced by ScreenManager::Input().
PostScreenMessage()
void Screen::PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
Parameters
SM the message to put on the screen.
fDelay The length of time it stays up.
References ASSERT, Screen::QueuedScreenMessage::fDelayRemaining, m_QueuedMessages, and Screen::QueuedScreenMessage::SM.
Referenced by ScreenOptions::BeginFadingOut(), ScreenSelectMaster::ChangePage(), ScreenRanking::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenSMOnlineLogin::Init(), ScreenEvaluation::Init(), ScreenSelectMusic::Input(), ScreenSelectLanguage::MenuStart(), ScreenSelectMaster::MenuStart(), ScreenManager::PostMessageToTopScreen(), ScreenSelectMusic::SelectCurrent(), and ScreenGameplay::Update().
PushSelf()
void Screen::PushSelf (lua_State * L) override virtual
Reimplemented from ActorFrame.
Reimplemented in ScreenGameplay, ScreenTextEntry, ScreenWithMenuElementsSimple, ScreenSelectMusic, ScreenEvaluation, ScreenOptions, ScreenSelectMaster, ScreenNetSelectBase, ScreenWithMenuElements, ScreenNetSelectMusic, ScreenAttract, ScreenNetRoom, ScreenSelectProfile, ScreenHowToPlay, ScreenPlayerOptions, ScreenNetEvaluation, ScreenProfileLoad, and ScreenProfileSave.
RemoveInputCallback()
void Screen::RemoveInputCallback (lua_State * L)
References InternalRemoveCallback(), m_CallingInputCallbacks, and m_DelayedCallbackRemovals.
Referenced by LunaScreen::RemoveInputCallback().
SetLockInputSecs()
void Screen::SetLockInputSecs (float f) inline
References f, and m_fLockInputSecs.
Referenced by LunaScreen::lockinput().
SetNextScreenName()
void Screen::SetNextScreenName (RString const & name)
References m_sNextScreen.
Referenced by LunaScreen::SetNextScreenName().
SetPrevScreenName()
void Screen::SetPrevScreenName (RString const & name)
References m_sPrevScreen.
Referenced by ScreenGameplay::Input(), and LunaScreen::SetPrevScreenName().
SortMessagesByDelayRemaining()
bool Screen::SortMessagesByDelayRemaining (const QueuedScreenMessage & m1, const QueuedScreenMessage & m2) static protected
References Screen::QueuedScreenMessage::fDelayRemaining.
Referenced by Update().
Update()
void Screen::Update (float fDeltaTime) override virtual
Reimplemented from Actor.
Reimplemented in ScreenTextEntry, ScreenGameplay, ScreenOptions, ScreenNetSelectMusic, ScreenSelectMusic, ScreenPackages, ScreenSetTime, ScreenDebugOverlay, ScreenMapControllers, ScreenWithMenuElements, ScreenStatsOverlay, ScreenTestSound, ScreenHowToPlay, ScreenReloadSongs, ScreenInstallOverlay, ScreenSelect, ScreenSyncOverlay, ScreenGameplaySyncMachine, and ScreenSandbox.
References CHECKPOINT_M, f, HandleScreenMessage(), m_fLockInputSecs, m_QueuedMessages, max(), ScreenMessageHelpers::ScreenMessageToString(), SortMessagesByDelayRemaining(), ssprintf(), and Actor::Update().
Referenced by ScreenSandbox::Update(), ScreenSyncOverlay::Update(), ScreenInstallOverlay::Update(), ScreenReloadSongs::Update(), ScreenTestSound::Update(), ScreenStatsOverlay::Update(), ScreenWithMenuElements::Update(), ScreenDebugOverlay::Update(), ScreenSetTime::Update(), and ScreenGameplay::Update().
Member Data Documentation
ALLOW_OPERATOR_MENU_BUTTON
ThemeMetric<bool> Screen::ALLOW_OPERATOR_MENU_BUTTON protected
Do we allow the operator menu button to be pressed here?
Referenced by AllowOperatorMenuButton(), GetScreenType(), and Init().
HANDLE_BACK_BUTTON
ThemeMetric<bool> Screen::HANDLE_BACK_BUTTON protected
Do we handle the back button being pressed here?
Referenced by Init(), and Input().
m_bRunning
bool Screen::m_bRunning protected
Referenced by BeginScreen(), EndScreen(), ScreenSelectMusic::HandleMessage(), and Init().
m_CallingInputCallbacks
bool Screen::m_CallingInputCallbacks private
Referenced by Init(), PassInputToLua(), and RemoveInputCallback().
m_Codes
InputQueueCodeSet Screen::m_Codes protected
Referenced by Init(), Input(), and ScreenGameplay::Input().
m_DelayedCallbackRemovals
vector<callback_key_t> Screen::m_DelayedCallbackRemovals private
Referenced by PassInputToLua(), and RemoveInputCallback().
m_fLockInputSecs
float Screen::m_fLockInputSecs protected
Referenced by ScreenMapControllers::BeginScreen(), ScreenSelectMaster::BeginScreen(), BeginScreen(), ScreenSelectMaster::ChangePage(), ScreenSelectMaster::HandleScreenMessage(), ScreenMapControllers::Input(), ScreenOptions::Input(), ScreenWithMenuElementsSimple::MenuBack(), ScreenSelectProfile::MenuDown(), ScreenSelectMaster::MenuDown(), ScreenSelectProfile::MenuLeft(), ScreenSelectMaster::MenuLeft(), ScreenSelectProfile::MenuRight(), ScreenSelectMaster::MenuRight(), ScreenSelectMaster::MenuStart(), ScreenSelectMusic::MenuStart(), ScreenWithMenuElementsSimple::MenuStart(), ScreenSelectProfile::MenuUp(), ScreenSelectMaster::MenuUp(), PassInputToLua(), SetLockInputSecs(), ScreenMapControllers::Update(), and Update().
m_InputCallbacks
map<callback_key_t, LuaReference> Screen::m_InputCallbacks private
Referenced by AddInputCallbackFromStack(), InternalRemoveCallback(), and PassInputToLua().
m_QueuedMessages
vector<QueuedScreenMessage> Screen::m_QueuedMessages protected
The list of messages that are sent to a Screen.
Referenced by ClearMessageQueue(), PostScreenMessage(), and Update().
m_smSendOnPop
ScreenMessage Screen::m_smSendOnPop protected
Referenced by ScreenPrompt::End(), HandleScreenMessage(), and Init().
m_sNextScreen
RString Screen::m_sNextScreen protected
The next screen to go to once this screen is done.
If this is blank, the NextScreen metric will be used.
Referenced by BeginScreen(), ScreenMiniMenu::BeginScreen(), ScreenWithMenuElements::Cancel(), GetNextScreenName(), ScreenSelect::HandleScreenMessage(), ScreenOptions::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), and SetNextScreenName().
m_sPrevScreen
RString Screen::m_sPrevScreen protected
Referenced by GetPrevScreen(), and SetPrevScreenName().
orderedcallbacks
vector<callback_key_t> Screen::orderedcallbacks private
Referenced by AddInputCallbackFromStack(), and PassInputToLua().
REPEAT_DELAY
ThemeMetric<float> Screen::REPEAT_DELAY protected
Referenced by HandleScreenMessage(), and Init().
REPEAT_RATE
ThemeMetric<float> Screen::REPEAT_RATE protected
Referenced by HandleScreenMessage(), and Init().
The documentation for this class was generated from the following files:
Screen.h
Screen.cpp