Etterna: CubicSpline.cpp File Reference
CubicSpline.cpp File Reference
#include "global.h"
#include "CubicSpline.h"
#include "RageUtil.h"
#include <list>
#include "LuaBinding.h"
Classes
struct SplineSolutionCache
struct SplineSolutionCache::Entry
struct LunaCubicSplineN
Macros
#define UNNAN(n)
#define RETURN_IF_EMPTY
#define DECLARE_P_AND_TFRAC
#define BOOLS_FROM_CLOSEST(closest)
#define SOLVE_LOOP(solvent)
#define CSN_EVAL_SOMETHING(something)
#define CSN_EVAL_RV_SOMETHING(something)
#define SET_GET_MEM(member, name)
#define LCSN_EVAL_SOMETHING(something)
#define SET_GET_LUA(name)
Functions
float loop_space_difference (float a, float b, float spatial_extent)
CSN_EVAL_SOMETHING (evaluate)
CSN_EVAL_SOMETHING (evaluate_derivative)
CSN_EVAL_SOMETHING (evaluate_second_derivative)
CSN_EVAL_SOMETHING (evaluate_third_derivative)
CSN_EVAL_RV_SOMETHING (evaluate)
CSN_EVAL_RV_SOMETHING (evaluate_derivative)
SET_GET_MEM (m_loop, loop)
SET_GET_MEM (m_polygonal, polygonal)
SET_GET_MEM (m_dirty, dirty)
LUA_REGISTER_CLASS (CubicSplineN)
int LuaFunc_create_spline (lua_State *L)
LUAFUNC_REGISTER_COMMON (create_spline)
Variables
const size_t solution_cache_limit = 16
SplineSolutionCache solution_cache
Macro Definition Documentation
BOOLS_FROM_CLOSEST
#define BOOLS_FROM_CLOSEST (closest)
Value:
out.set_loop((closest).get_loop());                                        \
    out.set_polygonal((closest).get_polygonal());
Referenced by CubicSplineN::weighted_average().
CSN_EVAL_RV_SOMETHING
#define CSN_EVAL_RV_SOMETHING (something)
Value:
void CubicSplineN::something(float t, RageVector3& v) const                \
    {                                                                          \
        ASSERT(m_splines.size() == 3);                                         \
        v.x = m_splines[0].something(t, m_loop);                               \
        v.y = m_splines[1].something(t, m_loop);                               \
        v.z = m_splines[2].something(t, m_loop);                               \
    }
CSN_EVAL_SOMETHING
#define CSN_EVAL_SOMETHING (something)
Value:
void CubicSplineN::something(float t, vector<float>& v) const              \
    {                                                                          \
        for (spline_cont_t::const_iterator spline = m_splines.begin();         \
             spline != m_splines.end();                                        \
             ++spline) {                                                       \
            v.push_back(spline->something(t, m_loop));                         \
        }                                                                      \
    }
DECLARE_P_AND_TFRAC
#define DECLARE_P_AND_TFRAC
Value:
size_t p = 0;                                                              \
    float tfrac = 0.0f;                                                        \
    p_and_tfrac_from_t(t, loop, p, tfrac);
Referenced by CubicSpline::evaluate(), CubicSpline::evaluate_derivative(), CubicSpline::evaluate_second_derivative(), and CubicSpline::evaluate_third_derivative().
LCSN_EVAL_SOMETHING
#define LCSN_EVAL_SOMETHING (something)
Value:
static int something(T* p, lua_State* L)                                   \
    {                                                                          \
        vector<float> pos;                                                     \
        p->something(FArg(1), pos);                                            \
        lua_createtable(L, pos.size(), 0);                                     \
        for (size_t i = 0; i < pos.size(); ++i) {                              \
            lua_pushnumber(L, pos[i]);                                         \
            lua_rawseti(L, -2, i + 1);                                         \
        }                                                                      \
        return 1;                                                              \
    }
RETURN_IF_EMPTY
#define RETURN_IF_EMPTY
Value:
if (m_points.empty()) {                                                    \
        return 0.0f;                                                           \
    }
Referenced by CubicSpline::evaluate(), CubicSpline::evaluate_derivative(), CubicSpline::evaluate_second_derivative(), and CubicSpline::evaluate_third_derivative().
SET_GET_LUA
#define SET_GET_LUA (name)
Value:
static int set_##name(T* p, lua_State* L)                                  \
    {                                                                          \
        p->set_##name(lua_toboolean(L, 1) != 0);                               \
        COMMON_RETURN_SELF;                                                    \
    }                                                                          \
    static int get_##name(T* p, lua_State* L)                                  \
    {                                                                          \
        lua_pushboolean(L, p->get_##name());                                   \
        return 1;                                                              \
    }
SET_GET_MEM
#define SET_GET_MEM (member, name)
Value:
void CubicSplineN::set_##name(bool b)                                      \
    {                                                                          \
        m_dirty = true;                                                        \
        (member) = b;                                                          \
    }                                                                          \
    bool CubicSplineN::get_##name() const { return member; }
SOLVE_LOOP
#define SOLVE_LOOP (solvent)
Value:
for (spline_cont_t::iterator spline = m_splines.begin();                   \
         spline != m_splines.end();                                            \
         ++spline) {                                                           \
        spline->solvent();                                                     \
    }
Referenced by CubicSplineN::solve().
UNNAN
#define UNNAN (n)
Value:
if ((n) != (n)) {                                                          \
        (n) = 0.0f;                                                            \
    }
Referenced by CubicSpline::set_results().
Function Documentation
CSN_EVAL_RV_SOMETHING() [1/2]
CSN_EVAL_RV_SOMETHING (evaluate)
CSN_EVAL_RV_SOMETHING() [2/2]
CSN_EVAL_RV_SOMETHING (evaluate_derivative)
CSN_EVAL_SOMETHING() [1/4]
CSN_EVAL_SOMETHING (evaluate)
CSN_EVAL_SOMETHING() [2/4]
CSN_EVAL_SOMETHING (evaluate_derivative)
CSN_EVAL_SOMETHING() [3/4]
CSN_EVAL_SOMETHING (evaluate_second_derivative)
CSN_EVAL_SOMETHING() [4/4]
CSN_EVAL_SOMETHING (evaluate_third_derivative)
loop_space_difference()
float loop_space_difference (float a, float b, float spatial_extent)
References f.
Referenced by CubicSpline::check_minimum_size(), CubicSpline::prep_inner(), CubicSpline::set_results(), CubicSpline::solve_looped(), CubicSpline::solve_polygonal(), and CubicSpline::solve_straight().
LUA_REGISTER_CLASS()
LUA_REGISTER_CLASS (CubicSplineN)
LuaFunc_create_spline()
int LuaFunc_create_spline (lua_State * L)
References CubicSplineN::PushSelf().
LUAFUNC_REGISTER_COMMON()
LUAFUNC_REGISTER_COMMON (create_spline)
SET_GET_MEM() [1/3]
SET_GET_MEM (m_loop , loop)
SET_GET_MEM() [2/3]
SET_GET_MEM (m_polygonal , polygonal)
SET_GET_MEM() [3/3]
SET_GET_MEM (m_dirty , dirty)
Variable Documentation
solution_cache
SplineSolutionCache solution_cache
solution_cache_limit
const size_t solution_cache_limit = 16
Referenced by SplineSolutionCache::add_to_cache().