Etterna: ConfOption Struct Reference
ConfOption Struct Reference
#include <ScreenOptionsMasterPrefs.h>
Public Types
using MoveData_t = void(*)(int &, bool, const ConfOption *)
Public Member Functions
void UpdateAvailableOptions ()
void MakeOptionsList (vector< RString > &out) const
int Get () const
void Put (int sel) const
int GetEffects () const
ConfOption (const char *n, MoveData_t m, const char *c0=NULL, const char *c1=NULL, const char *c2=NULL, const char *c3=NULL, const char *c4=NULL, const char *c5=NULL, const char *c6=NULL, const char *c7=NULL, const char *c8=NULL, const char *c9=NULL, const char *c10=NULL, const char *c11=NULL, const char *c12=NULL, const char *c13=NULL, const char *c14=NULL, const char *c15=NULL, const char *c16=NULL, const char *c17=NULL, const char *c18=NULL, const char *c19=NULL)
void AddOption (const RString &sName)
ConfOption (const char *n, MoveData_t m, void(*lst)(vector< RString > &out))
Static Public Member Functions
static struct ConfOption * Find (RString name)
Public Attributes
RString name
RString m_sPrefName
MoveData_t MoveData
int m_iEffects
bool m_bAllowThemeItems
vector< RString > names
void(* MakeOptionsListCB)(vector< RString > &out)
Member Typedef Documentation
MoveData_t
using ConfOption::MoveData_t = void (*)(int&, bool, const ConfOption*)
Constructor & Destructor Documentation
ConfOption() [1/2]
ConfOption::ConfOption (const char * n, MoveData_t m, const char * c0 = NULL, const char * c1 = NULL, const char * c2 = NULL, const char * c3 = NULL, const char * c4 = NULL, const char * c5 = NULL, const char * c6 = NULL, const char * c7 = NULL, const char * c8 = NULL, const char * c9 = NULL, const char * c10 = NULL, const char * c11 = NULL, const char * c12 = NULL, const char * c13 = NULL, const char * c14 = NULL, const char * c15 = NULL, const char * c16 = NULL, const char * c17 = NULL, const char * c18 = NULL, const char * c19 = NULL) inline
References MakeOptionsListCB, name, and PUSH.
ConfOption() [2/2]
ConfOption::ConfOption (const char * n, MoveData_t m, void(*)(vector< RString > &out) lst) inline
References MakeOptionsListCB.
Member Function Documentation
AddOption()
void ConfOption::AddOption (const RString & sName) inline
References PUSH.
Referenced by InitializeConfOptions().
Find()
ConfOption * ConfOption::Find (RString name) static
References StdString::CStdStr< CT >::CompareNoCase(), InitializeConfOptions(), and name.
Referenced by GetTimingDifficulty(), OptionRowHandlerConfig::LoadInternal(), LuaFunction(), and SetTimingDifficulty().
Get()
int ConfOption::Get () const inline
References MoveData.
Referenced by OptionRowHandlerConfig::ExportOption(), and OptionRowHandlerConfig::ImportOption().
GetEffects()
int ConfOption::GetEffects () const
References OPT_SAVE_PREFERENCES.
Referenced by OptionRowHandlerConfig::ExportOption().
MakeOptionsList()
void ConfOption::MakeOptionsList (vector< RString > & out) const
Referenced by Announcer(), DefaultNoteSkin(), GameSel(), OptionRowHandlerConfig::LoadInternal(), and RequestedTheme().
Put()
void ConfOption::Put (int sel) const inline
References MoveData.
Referenced by OptionRowHandlerConfig::ExportOption().
UpdateAvailableOptions()
void ConfOption::UpdateAvailableOptions ()
Referenced by OptionRowHandlerConfig::LoadInternal().
Member Data Documentation
m_bAllowThemeItems
bool ConfOption::m_bAllowThemeItems
Referenced by OptionRowHandlerConfig::LoadInternal().
m_iEffects
int ConfOption::m_iEffects
m_sPrefName
RString ConfOption::m_sPrefName
Referenced by MoveMap(), and MovePref().
MakeOptionsListCB
void(* ConfOption::MakeOptionsListCB) (vector< RString > &out)
Referenced by ConfOption().
MoveData
MoveData_t ConfOption::MoveData
Referenced by Get(), and Put().
name
RString ConfOption::name
Referenced by ConfOption(), Find(), and OptionRowHandlerConfig::LoadInternal().
names
vector<RString> ConfOption::names
The documentation for this struct was generated from the following files:
ScreenOptionsMasterPrefs.h
ScreenOptionsMasterPrefs.cpp