Etterna: ThemeMetricStepsTypesToShow Class Reference
ThemeMetricStepsTypesToShow Class Reference
#include <CommonMetrics.h>
Public Member Functions
ThemeMetricStepsTypesToShow ()
ThemeMetricStepsTypesToShow (const RString &sGroup, const RString &sName)
void Read ()
const vector< StepsType > & GetValue () const
Public Member Functions inherited from ThemeMetric< RString >
ThemeMetric (const RString &sGroup="", const RString &sName="")
ThemeMetric (const ThemeMetric< RString > &cpy)
~ThemeMetric () override
void Load (const RString &sGroup, const RString &sName)
Load the chosen metric from the .ini file.
void ChangeGroup (const RString &sGroup)
void Read () override
Actually read the metric and get its data.
void PushSelf (Lua *L)
void Clear () override
const RString & GetName () const
Retrieve the metric's name.
const RString & GetGroup () const
Retrieve the metric's group.
const RString & GetValue () const
Retrieve the metric's value.
operator const RString & () const
bool IsLoaded () const
bool operator== (const RString &input) const
Public Member Functions inherited from IThemeMetric
virtual ~IThemeMetric ()=default
Private Attributes
vector< StepsType > m_v
Additional Inherited Members
Protected Attributes inherited from ThemeMetric< RString >
RString m_sGroup
the metric's group.
RString m_sName
the metric's name.
LuaReference m_Value
the metric's value.
RString m_currentValue
bool m_bCallEachTime
Constructor & Destructor Documentation
ThemeMetricStepsTypesToShow() [1/2]
ThemeMetricStepsTypesToShow::ThemeMetricStepsTypesToShow () inline
ThemeMetricStepsTypesToShow() [2/2]
ThemeMetricStepsTypesToShow::ThemeMetricStepsTypesToShow (const RString & sGroup, const RString & sName)
References ThemeMetric< RString >::IsLoaded(), and Read().
Member Function Documentation
GetValue()
const vector< StepsType > & ThemeMetricStepsTypesToShow::GetValue () const
References m_v.
Referenced by SongUtil::GetPlayableStepsTypes(), ScreenRanking::Init(), and OptionRowHandlerStepsType::LoadInternal().
Read()
void ThemeMetricStepsTypesToShow::Read () virtual
Implements IThemeMetric.
References ASSERT, GAMEMAN, GAMESTATE, ThemeMetric< RString >::GetName(), GameManager::GetStepsTypesForGame(), GameState::m_pCurGame, m_v, ThemeMetric< T >::Read(), and RemoveStepsTypes().
Referenced by ThemeMetricStepsTypesToShow().
Member Data Documentation
m_v
vector<StepsType> ThemeMetricStepsTypesToShow::m_v private
Referenced by GetValue(), and Read().
The documentation for this class was generated from the following files:
CommonMetrics.h
CommonMetrics.cpp