Etterna: PlayerStageStats.cpp File Reference
PlayerStageStats.cpp File Reference
#include "global.h"
#include "PlayerStageStats.h"
#include "CommonMetrics.h"
#include "CryptManager.h"
#include "Foreach.h"
#include "GameState.h"
#include "LuaManager.h"
#include "MinaCalc.h"
#include "NoteData.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "ScoreKeeperNormal.h"
#include "Steps.h"
#include "ThemeManager.h"
#include "LuaBinding.h"
Macros
#define GRADE_PERCENT_TIER(i)
#define GRADE_TIER02_IS_ALL_W2S THEME->GetMetricB("PlayerStageStats", "GradeTier02IsAllW2s")
#define GRADE_TIER01_IS_ALL_W2S THEME->GetMetricB("PlayerStageStats", "GradeTier01IsAllW2s")
#define GRADE_TIER02_IS_FULL_COMBO THEME->GetMetricB("PlayerStageStats", "GradeTier02IsFullCombo")
Functions
Grade GetGradeFromPercent (float fPercent)
LuaFunction (GetGradeFromPercent, GetGradeFromPercent(FArg(1))) LuaFunction(FormatPercentScore
Variables
static ThemeMetric< TapNoteScore > g_MinScoreToMaintainCombo ("Gameplay", "MinScoreToMaintainCombo")
static ThemeMetric< bool > g_MineHitIncrementsMissCombo ("Gameplay", "MineHitIncrementsMissCombo")
const float LESSON_PASS_THRESHOLD = 0.8f
Macro Definition Documentation
GRADE_PERCENT_TIER
#define GRADE_PERCENT_TIER (i)
Value:
THEME->GetMetricF(\
      "PlayerStageStats",                                                      \
      ssprintf("GradePercent%s", GradeToString((Grade)(i)).c_str()))
GRADE_TIER01_IS_ALL_W2S
#define GRADE_TIER01_IS_ALL_W2S THEME->GetMetricB("PlayerStageStats", "GradeTier01IsAllW2s")
Referenced by PlayerStageStats::GetGrade().
GRADE_TIER02_IS_ALL_W2S
#define GRADE_TIER02_IS_ALL_W2S THEME->GetMetricB("PlayerStageStats", "GradeTier02IsAllW2s")
Referenced by PlayerStageStats::GetGrade().
GRADE_TIER02_IS_FULL_COMBO
#define GRADE_TIER02_IS_FULL_COMBO THEME->GetMetricB("PlayerStageStats", "GradeTier02IsFullCombo")
Referenced by PlayerStageStats::GetGrade().
Function Documentation
GetGradeFromPercent()
Grade GetGradeFromPercent (float fPercent)
References f, Grade_Tier01, Grade_Tier02, Grade_Tier03, Grade_Tier04, Grade_Tier05, Grade_Tier06, and Grade_Tier07.
Referenced by PlayerStageStats::GetGrade(), and PlayerStageStats::GetWifeGrade().
LuaFunction()
LuaFunction (GetGradeFromPercent , GetGradeFromPercent(FArg(1)))
Variable Documentation
g_MineHitIncrementsMissCombo
ThemeMetric<bool> g_MineHitIncrementsMissCombo("Gameplay", "MineHitIncrementsMissCombo") static
Referenced by PlayerStageStats::FullComboOfScore().
g_MinScoreToMaintainCombo
ThemeMetric<TapNoteScore> g_MinScoreToMaintainCombo("Gameplay", "MinScoreToMaintainCombo") static
Referenced by PlayerStageStats::GetGrade().
LESSON_PASS_THRESHOLD
const float LESSON_PASS_THRESHOLD = 0.8f
Referenced by PlayerStageStats::GetLessonScoreNeeded().