Etterna: NotesLoaderKSF.cpp File Reference
NotesLoaderKSF.cpp File Reference
#include "global.h"
#include "NotesLoaderKSF.h"
#include "MsdFile.h"
#include "NoteData.h"
#include "NoteTypes.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "RageUtil_CharConversions.h"
#include "Song.h"
#include "Steps.h"
Functions
static void HandleBunki (TimingData &timing, const float fEarlyBPM, const float fCurBPM, const float fGap, const float fPos)
static bool LoadFromKSFFile (const RString &sPath, Steps &out, Song &song, bool bKIUCompliant)
static void LoadTags (const RString &str, Song &out)
static void ProcessTickcounts (const RString &value, int &ticks, TimingData &timing)
static bool LoadGlobalData (const RString &sPath, Song &out, bool &bKIUCompliant)
Function Documentation
HandleBunki()
static void HandleBunki (TimingData & timing, const float fEarlyBPM, const float fCurBPM, const float fGap, const float fPos) static
References TimingData::AddSegment(), BeatToNoteRow(), LOG, and RageLog::Trace().
Referenced by LoadFromKSFFile(), and LoadGlobalData().
LoadFromKSFFile()
static bool LoadFromKSFFile (const RString & sPath, Steps & out, Song & song, bool bKIUCompliant) static
References NoteData::AddHoldNote(), TimingData::AddSegment(), BeatToNoteRow(), BeginsWith(), clamp, Difficulty_Beginner, Difficulty_Challenge, Difficulty_Easy, Difficulty_Edit, Difficulty_Hard, Difficulty_Medium, EndsWith(), FAIL_M, TimingData::GetBPMAtBeat(), TimingData::GetDelayAtRow(), MsdFile::GetError(), Steps::GetMeter(), NoteData::GetNumTracks(), MsdFile::GetNumValues(), Song::GetSpecifiedLastSecond(), TimingData::GetStopAtRow(), MsdFile::GetValue(), HandleBunki(), LOG, TimingData::m_fBeat0OffsetInSeconds, Steps::m_StepsType, Steps::m_Timing, StdString::CStdStr< CT >::MakeLower(), StdString::CStdStr< CT >::MakeUpper(), max(), MsdFile::ReadFile(), ROWS_PER_BEAT, TimingData::SetBPMAtBeat(), TimingData::SetDelayAtBeat(), Steps::SetDescription(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetNoteData(), NoteData::SetNumTracks(), Steps::SetSavedToDisk(), Song::SetSpecifiedLastSecond(), NoteData::SetTapNote(), TimingData::SetTickcountAtBeat(), split(), splitpath(), ssprintf(), StepsType_pump_couple, StepsType_pump_double, StepsType_pump_halfdouble, StepsType_pump_routine, StepsType_pump_single, StringToFloat(), StringToInt(), StripCrnl(), TAP_EMPTY, TAP_ORIGINAL_FAKE, TAP_ORIGINAL_HOLD_HEAD, TAP_ORIGINAL_LIFT, TAP_ORIGINAL_MINE, TAP_ORIGINAL_TAP, Steps::TidyUpData(), RageLog::Trace(), TrimLeft(), and RageLog::UserLog().
Referenced by KSFLoader::LoadFromDir(), and KSFLoader::LoadNoteDataFromSimfile().
LoadGlobalData()
static bool LoadGlobalData (const RString & sPath, Song & out, bool & bKIUCompliant) static
References TimingData::AddSegment(), ASSERT, BeginsWith(), GetDirListing(), MsdFile::GetError(), MsdFile::GetNumValues(), Song::GetSongDir(), MsdFile::GetValue(), HandleBunki(), HHMMSSToSeconds(), LoadTags(), LOG, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sMusicFile, Song::m_SongTiming, StdString::CStdStr< CT >::MakeUpper(), ProcessTickcounts(), MsdFile::ReadFile(), split(), StringToFloat(), StripCrnl(), TrimLeft(), and RageLog::UserLog().
Referenced by KSFLoader::LoadFromDir(), and KSFLoader::LoadNoteDataFromSimfile().
LoadTags()
static void LoadTags (const RString & str, Song & out) static
References ConvertString(), Song::m_sArtist, Song::m_sMainTitle, and split().
Referenced by LoadGlobalData().
ProcessTickcounts()
static void ProcessTickcounts (const RString & value, int & ticks, TimingData & timing) static
References TimingData::AddSegment(), CLAMP(), TickcountSegment::DEFAULT_TICK_COUNT, ROWS_PER_BEAT, and StringToInt().
Referenced by LoadGlobalData().