Etterna: NoteColumnRenderArgs Struct Reference
NoteColumnRenderArgs Struct Reference
#include <NoteDisplay.h>
Public Member Functions
void spae_pos_for_beat (const PlayerState *player_state, float beat, float y_offset, float y_reverse_offset, RageVector3 &sp_pos, RageVector3 &ae_pos) const
void spae_zoom_for_beat (const PlayerState *state, float beat, RageVector3 &sp_zoom, RageVector3 &ae_zoom) const
void SetPRZForActor (Actor *actor, const RageVector3 &sp_pos, const RageVector3 &ae_pos, const RageVector3 &sp_rot, const RageVector3 &ae_rot, const RageVector3 &sp_zoom, const RageVector3 &ae_zoom) const
Public Attributes
const NCSplineHandler * pos_handler
const NCSplineHandler * rot_handler
const NCSplineHandler * zoom_handler
RageColor diffuse
RageColor glow
float song_beat
int column
Member Function Documentation
SetPRZForActor()
void NoteColumnRenderArgs::SetPRZForActor (Actor * actor, const RageVector3 & sp_pos, const RageVector3 & ae_pos, const RageVector3 & sp_rot, const RageVector3 & ae_rot, const RageVector3 & sp_zoom, const RageVector3 & ae_zoom) const
References PI_180R, Actor::SetRotationX(), Actor::SetRotationY(), Actor::SetRotationZ(), Actor::SetX(), Actor::SetY(), Actor::SetZ(), Actor::SetZoomX(), Actor::SetZoomY(), Actor::SetZoomZ(), RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by NoteDisplay::DrawActor(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
spae_pos_for_beat()
void NoteColumnRenderArgs::spae_pos_for_beat (const PlayerState * player_state, float beat, float y_offset, float y_reverse_offset, RageVector3 & sp_pos, RageVector3 & ae_pos) const
References column, NCSplineHandler::EvalForBeat(), ArrowEffects::GetXYZPos(), NCSplineHandler::m_spline_mode, NCSM_Disabled, NCSM_Offset, NCSM_Position, pos_handler, and song_beat.
Referenced by NoteDisplay::DrawActor(), and NoteDisplay::DrawHoldPart().
spae_zoom_for_beat()
void NoteColumnRenderArgs::spae_zoom_for_beat (const PlayerState * state, float beat, RageVector3 & sp_zoom, RageVector3 & ae_zoom) const
References NCSplineHandler::EvalForBeat(), ArrowEffects::GetZoom(), NCSplineHandler::m_spline_mode, NCSM_Disabled, NCSM_Offset, NCSM_Position, song_beat, RageVector3::x, RageVector3::y, RageVector3::z, and zoom_handler.
Referenced by NoteDisplay::DrawActor().
Member Data Documentation
column
int NoteColumnRenderArgs::column
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldBody(), NoteDisplay::DrawHoldPart(), NoteDisplay::DrawHoldsInRange(), NoteDisplay::DrawTap(), and spae_pos_for_beat().
diffuse
RageColor NoteColumnRenderArgs::diffuse
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHoldPart(), NoteColumnRenderer::DrawPrimitives(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
glow
RageColor NoteColumnRenderArgs::glow
Referenced by NoteDisplay::DrawHoldBody(), NoteColumnRenderer::DrawPrimitives(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
pos_handler
const NCSplineHandler* NoteColumnRenderArgs::pos_handler
Referenced by NoteDisplay::DrawHoldPart(), NoteColumnRenderer::DrawPrimitives(), and spae_pos_for_beat().
rot_handler
const NCSplineHandler* NoteColumnRenderArgs::rot_handler
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHoldPart(), and NoteColumnRenderer::DrawPrimitives().
song_beat
float NoteColumnRenderArgs::song_beat
Referenced by NoteDisplay::DrawActor(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldPart(), NoteColumnRenderer::DrawPrimitives(), spae_pos_for_beat(), and spae_zoom_for_beat().
zoom_handler
const NCSplineHandler* NoteColumnRenderArgs::zoom_handler
Referenced by NoteDisplay::DrawHoldPart(), NoteColumnRenderer::DrawPrimitives(), and spae_zoom_for_beat().
The documentation for this struct was generated from the following files:
NoteDisplay.h
NoteDisplay.cpp