Etterna: RageSoundReader_ThreadedBuffer Class Reference
RageSoundReader_ThreadedBuffer Class Reference
#include <RageSoundReader_ThreadedBuffer.h>
Classes
struct Mapping
Public Member Functions
RageSoundReader_ThreadedBuffer (RageSoundReader *pSource)
RageSoundReader_ThreadedBuffer (const RageSoundReader_ThreadedBuffer &cpy)
~RageSoundReader_ThreadedBuffer () override
RageSoundReader_ThreadedBuffer * Copy () const override
int SetPosition (int iFrame) override
int Read (float *pBuffer, int iLength) override
int GetNextSourceFrame () const override
int GetLength () const override
int GetLength_Fast () const override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
void EnableBuffering ()
void EnableBuffering () const
bool DisableBuffering ()
bool DisableBuffering () const
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
int FillFrames (int iBytes)
int FillBlock ()
int GetFilledFrames () const
int GetEmptyFrames () const
void WaitUntilFrames (int iWaitUntilFrames)
void BufferingThread ()
Static Private Member Functions
static int StartBufferingThread (void *p)
Private Attributes
int m_iSampleRate
int m_iChannels
CircBuf< float > m_DataBuffer
list< Mapping > m_StreamPosition
bool m_bEOF
bool m_bEnabled
bool m_bFilling
RageEvent m_Event
RageThread m_Thread
bool m_bShutdownThread
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Constructor & Destructor Documentation
RageSoundReader_ThreadedBuffer() [1/2]
RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer (RageSoundReader * pSource)
References RageThread::Create(), g_iStreamingBufferFrames, RageSoundReader::GetNextSourceFrame(), RageSoundReader::GetNumChannels(), GetNumChannels(), RageSoundReader::GetSampleRate(), RageSoundReader::GetStreamToSourceRatio(), m_bEnabled, m_bEOF, m_bFilling, m_bShutdownThread, m_DataBuffer, m_iChannels, m_iSampleRate, m_StreamPosition, m_Thread, CircBuf< T >::reserve(), RageThread::SetName(), and StartBufferingThread().
Referenced by Copy().
RageSoundReader_ThreadedBuffer() [2/2]
RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer (const RageSoundReader_ThreadedBuffer & cpy)
References RageSoundReader::Copy(), RageThread::Create(), DisableBuffering(), EnableBuffering(), m_bEnabled, m_bEOF, m_bFilling, m_bShutdownThread, m_DataBuffer, m_iChannels, m_iSampleRate, RageSoundReader_Filter::m_pSource, m_StreamPosition, m_Thread, and StartBufferingThread().
~RageSoundReader_ThreadedBuffer()
RageSoundReader_ThreadedBuffer::~RageSoundReader_ThreadedBuffer () override
References RageEvent::Broadcast(), DisableBuffering(), RageMutex::Lock(), m_bShutdownThread, m_Event, m_Thread, RageMutex::Unlock(), and RageThread::Wait().
Member Function Documentation
BufferingThread()
void RageSoundReader_ThreadedBuffer::BufferingThread () private
References RageEvent::Broadcast(), FillFrames(), g_iMinFillFrames, g_iReadBlockSizeFrames, GetFilledFrames(), RageMutex::Lock(), m_bEnabled, m_bFilling, m_bShutdownThread, m_Event, m_iSampleRate, max(), RageTimer::Touch(), RageMutex::Unlock(), RageEvent::Wait(), and RageEvent::WaitTimeoutSupported().
Copy()
RageSoundReader_ThreadedBuffer* RageSoundReader_ThreadedBuffer::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_ThreadedBuffer().
DisableBuffering() [1/2]
bool RageSoundReader_ThreadedBuffer::DisableBuffering ()
References RageEvent::Broadcast(), RageMutex::Lock(), m_bEnabled, m_bFilling, m_Event, RageMutex::Unlock(), and RageEvent::Wait().
Referenced by DisableBuffering(), GetLength(), GetLength_Fast(), RageSoundReader_ThreadedBuffer(), SetPosition(), and ~RageSoundReader_ThreadedBuffer().
DisableBuffering() [2/2]
bool RageSoundReader_ThreadedBuffer::DisableBuffering () const inline
References DisableBuffering().
EnableBuffering() [1/2]
void RageSoundReader_ThreadedBuffer::EnableBuffering ()
References RageEvent::Broadcast(), RageMutex::Lock(), m_bEnabled, m_Event, and RageMutex::Unlock().
Referenced by EnableBuffering(), GetLength(), GetLength_Fast(), RageSoundReader_ThreadedBuffer(), Read(), and SetPosition().
EnableBuffering() [2/2]
void RageSoundReader_ThreadedBuffer::EnableBuffering () const inline
References EnableBuffering().
FillBlock()
int RageSoundReader_ThreadedBuffer::FillBlock () private
References CircBuf< T >::advance_write_pointer(), ASSERT, RageSoundReader::END_OF_FILE, g_iReadBlockSizeFrames, CircBuf< T >::get_write_pointer(), GetEmptyFrames(), GetNumChannels(), RageMutex::Lock(), m_bEOF, m_DataBuffer, m_Event, RageSoundReader_Filter::m_pSource, m_StreamPosition, min(), CircBuf< T >::num_writable(), RageSoundReader::RetriedRead(), and RageMutex::Unlock().
Referenced by FillFrames().
FillFrames()
int RageSoundReader_ThreadedBuffer::FillFrames (int iBytes) private
References FillBlock().
Referenced by BufferingThread().
GetEmptyFrames()
int RageSoundReader_ThreadedBuffer::GetEmptyFrames () const private
References g_iReadBlockSizeFrames, GetNumChannels(), m_DataBuffer, and CircBuf< T >::num_writable().
Referenced by FillBlock().
GetFilledFrames()
int RageSoundReader_ThreadedBuffer::GetFilledFrames () const private
References GetNumChannels(), m_DataBuffer, and CircBuf< T >::num_readable().
Referenced by BufferingThread(), and WaitUntilFrames().
GetLength()
int RageSoundReader_ThreadedBuffer::GetLength () const override virtual
Reimplemented from RageSoundReader_Filter.
References DisableBuffering(), EnableBuffering(), RageSoundReader::GetLength(), and RageSoundReader_Filter::m_pSource.
GetLength_Fast()
int RageSoundReader_ThreadedBuffer::GetLength_Fast () const override virtual
Reimplemented from RageSoundReader_Filter.
References DisableBuffering(), EnableBuffering(), RageSoundReader::GetLength_Fast(), and RageSoundReader_Filter::m_pSource.
GetNextSourceFrame()
int RageSoundReader_ThreadedBuffer::GetNextSourceFrame () const override virtual
Reimplemented from RageSoundReader_Filter.
References RageMutex::Lock(), m_Event, m_StreamPosition, and RageMutex::Unlock().
GetNumChannels()
unsigned RageSoundReader_ThreadedBuffer::GetNumChannels () const inline override virtual
Reimplemented from RageSoundReader_Filter.
References m_iChannels.
Referenced by FillBlock(), GetEmptyFrames(), GetFilledFrames(), RageSoundReader_ThreadedBuffer(), and Read().
GetSampleRate()
int RageSoundReader_ThreadedBuffer::GetSampleRate () const inline override virtual
Reimplemented from RageSoundReader_Filter.
References m_iSampleRate.
GetSource()
RageSoundReader* RageSoundReader_ThreadedBuffer::GetSource () inline override virtual
Reimplemented from RageSoundReader_Filter.
GetStreamToSourceRatio()
float RageSoundReader_ThreadedBuffer::GetStreamToSourceRatio () const override virtual
Reimplemented from RageSoundReader_Filter.
References RageMutex::Lock(), m_Event, m_StreamPosition, and RageMutex::Unlock().
Read()
int RageSoundReader_ThreadedBuffer::Read (float * pBuffer, int iLength) override virtual
Reimplemented from RageSoundReader_Filter.
References EnableBuffering(), RageSoundReader::END_OF_FILE, GetNumChannels(), RageSoundReader_ThreadedBuffer::Mapping::iFramesBuffered, RageSoundReader_ThreadedBuffer::Mapping::iPositionOfFirstFrame, RageMutex::Lock(), m_bEOF, m_DataBuffer, m_Event, m_StreamPosition, min(), CircBuf< T >::read(), RageMutex::Unlock(), and RageSoundReader::WOULD_BLOCK.
SetPosition()
int RageSoundReader_ThreadedBuffer::SetPosition (int iFrame) override virtual
Reimplemented from RageSoundReader_Filter.
References CircBuf< T >::clear(), DisableBuffering(), EnableBuffering(), m_bEOF, m_DataBuffer, m_StreamPosition, and RageSoundReader_Filter::SetPosition().
SetProperty()
bool RageSoundReader_ThreadedBuffer::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Filter::m_pSource, and RageSoundReader::SetProperty().
StartBufferingThread()
static int RageSoundReader_ThreadedBuffer::StartBufferingThread (void * p) inline static private
Referenced by RageSoundReader_ThreadedBuffer().
WaitUntilFrames()
void RageSoundReader_ThreadedBuffer::WaitUntilFrames (int iWaitUntilFrames) private
References ASSERT, GetFilledFrames(), RageMutex::Lock(), m_bEnabled, m_Event, RageMutex::Unlock(), and RageEvent::Wait().
Member Data Documentation
m_bEnabled
bool RageSoundReader_ThreadedBuffer::m_bEnabled private
Referenced by BufferingThread(), DisableBuffering(), EnableBuffering(), RageSoundReader_ThreadedBuffer(), and WaitUntilFrames().
m_bEOF
bool RageSoundReader_ThreadedBuffer::m_bEOF private
Referenced by FillBlock(), RageSoundReader_ThreadedBuffer(), Read(), and SetPosition().
m_bFilling
bool RageSoundReader_ThreadedBuffer::m_bFilling private
Referenced by BufferingThread(), DisableBuffering(), and RageSoundReader_ThreadedBuffer().
m_bShutdownThread
bool RageSoundReader_ThreadedBuffer::m_bShutdownThread private
Referenced by BufferingThread(), RageSoundReader_ThreadedBuffer(), and ~RageSoundReader_ThreadedBuffer().
m_DataBuffer
CircBuf<float> RageSoundReader_ThreadedBuffer::m_DataBuffer private
Referenced by FillBlock(), GetEmptyFrames(), GetFilledFrames(), RageSoundReader_ThreadedBuffer(), Read(), and SetPosition().
m_Event
RageEvent RageSoundReader_ThreadedBuffer::m_Event mutable private
Referenced by BufferingThread(), DisableBuffering(), EnableBuffering(), FillBlock(), GetNextSourceFrame(), GetStreamToSourceRatio(), Read(), WaitUntilFrames(), and ~RageSoundReader_ThreadedBuffer().
m_iChannels
int RageSoundReader_ThreadedBuffer::m_iChannels private
Referenced by GetNumChannels(), and RageSoundReader_ThreadedBuffer().
m_iSampleRate
int RageSoundReader_ThreadedBuffer::m_iSampleRate private
Referenced by BufferingThread(), GetSampleRate(), and RageSoundReader_ThreadedBuffer().
m_StreamPosition
list<Mapping> RageSoundReader_ThreadedBuffer::m_StreamPosition private
Referenced by FillBlock(), GetNextSourceFrame(), GetStreamToSourceRatio(), RageSoundReader_ThreadedBuffer(), Read(), and SetPosition().
m_Thread
RageThread RageSoundReader_ThreadedBuffer::m_Thread private
Referenced by RageSoundReader_ThreadedBuffer(), and ~RageSoundReader_ThreadedBuffer().
The documentation for this class was generated from the following files:
RageSoundReader_ThreadedBuffer.h
RageSoundReader_ThreadedBuffer.cpp