Etterna: picosha2::detail Namespace Reference
picosha2::detail Namespace Reference
Functions
byte_t mask_8bit (byte_t x)
word_t mask_32bit (word_t x)
word_t ch (word_t x, word_t y, word_t z)
word_t maj (word_t x, word_t y, word_t z)
word_t rotr (word_t x, std::size_t n)
word_t bsig0 (word_t x)
word_t bsig1 (word_t x)
word_t shr (word_t x, std::size_t n)
word_t ssig0 (word_t x)
word_t ssig1 (word_t x)
template<typename RaIter1 , typename RaIter2 >
void hash256_block (RaIter1 message_digest, RaIter2 first, RaIter2 last)
Variables
const word_t add_constant [64]
const word_t initial_message_digest [8]
Function Documentation
bsig0()
word_t picosha2::detail::bsig0 (word_t x) inline
References rotr().
Referenced by hash256_block().
bsig1()
word_t picosha2::detail::bsig1 (word_t x) inline
References rotr().
Referenced by hash256_block().
ch()
word_t picosha2::detail::ch (word_t x, word_t y, word_t z) inline
Referenced by Playlist::AddChart(), Chart::CreateNode(), Playlist::CreateNode(), ScoreManager::CreateNode(), hash256_block(), ScreenGameplay::InitSongQueues(), ScreenNetSelectBase::Input(), Playlist::LoadFromNode(), LoadFromSMNoteDataStringWithPlayer(), DBProfile::LoadPlayLists(), RageSoundMixBuffer::read_deinterlace(), StdString::CStdStr< CT >::Replace(), RStringToWstring(), DBProfile::SavePlayerScores(), DBProfile::SavePlayLists(), StdString::sstolower(), StdString::sstoupper(), LunaScreenSelectMusic::StartPlaylistAsCourse(), ETTProtocol::Update(), Rage::utf8_is_valid(), utf8_is_valid(), Rage::utf8_sanitize(), and utf8_sanitize().
hash256_block()
template<typename RaIter1 , typename RaIter2 > void picosha2::detail::hash256_block (RaIter1 message_digest, RaIter2 first, RaIter2 last)
References bsig0(), bsig1(), ch(), f, maj(), mask_32bit(), mask_8bit(), ssig0(), ssig1(), and w.
Referenced by picosha2::hash256_one_by_one::finish(), and picosha2::hash256_one_by_one::process().
maj()
word_t picosha2::detail::maj (word_t x, word_t y, word_t z) inline
Referenced by hash256_block().
mask_32bit()
word_t picosha2::detail::mask_32bit (word_t x) inline
Referenced by hash256_block(), and rotr().
mask_8bit()
byte_t picosha2::detail::mask_8bit (byte_t x) inline
Referenced by picosha2::hash256_one_by_one::get_hash_bytes(), and hash256_block().
rotr()
word_t picosha2::detail::rotr (word_t x, std::size_t n) inline
References mask_32bit().
Referenced by bsig0(), bsig1(), ssig0(), and ssig1().
shr()
word_t picosha2::detail::shr (word_t x, std::size_t n) inline
Referenced by ssig0(), and ssig1().
ssig0()
word_t picosha2::detail::ssig0 (word_t x) inline
References rotr(), and shr().
Referenced by hash256_block().
ssig1()
word_t picosha2::detail::ssig1 (word_t x) inline
References rotr(), and shr().
Referenced by hash256_block().
Variable Documentation
add_constant
const word_t picosha2::detail::add_constant[64]
Initial value:
= {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
    0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
    0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
    0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
    0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
}
initial_message_digest
const word_t picosha2::detail::initial_message_digest[8]
Initial value:
= { 0x6a09e667, 0xbb67ae85, 0x3c6ef372,
                                           0xa54ff53a, 0x510e527f, 0x9b05688c,
                                           0x1f83d9ab, 0x5be0cd19 }
Referenced by picosha2::hash256_one_by_one::init().