Etterna: WinWdmPin Struct Reference
WinWdmPin Struct Reference
Public Member Functions
WinWdmPin (WinWdmFilter *pParentFilter, int iPinId)
~WinWdmPin ()
bool Instantiate (const WAVEFORMATEX *pFormat, RString &sError)
void Close ()
bool SetState (KSSTATE state, RString &sError)
KSPIN_CONNECT * MakeFormat (const WAVEFORMATEX *pFormat) const
bool IsFormatSupported (const WAVEFORMATEX *pFormat) const
Public Attributes
HANDLE m_hHandle
WinWdmFilter * m_pParentFilter
int m_iPinId
vector< KSDATARANGE_AUDIO > m_dataRangesItem
Constructor & Destructor Documentation
WinWdmPin()
WinWdmPin::WinWdmPin (WinWdmFilter * pParentFilter, int iPinId) inline
References m_hHandle, m_iPinId, and m_pParentFilter.
~WinWdmPin()
WinWdmPin::~WinWdmPin () inline
References Close().
Member Function Documentation
Close()
void WinWdmPin::Close ()
References m_hHandle, m_pParentFilter, WinWdmFilter::Release(), and SetState().
Referenced by WinWdmStream::Close(), and ~WinWdmPin().
Instantiate()
bool WinWdmPin::Instantiate (const WAVEFORMATEX * pFormat, RString & sError)
References FunctionKsCreatePin, IsFormatSupported(), m_hHandle, WinWdmFilter::m_hHandle, m_pParentFilter, MakeFormat(), WinWdmFilter::Release(), and WinWdmFilter::Use().
Referenced by WinWdmFilter::InstantiateRenderPin().
IsFormatSupported()
bool WinWdmPin::IsFormatSupported (const WAVEFORMATEX * pFormat) const
References DEFINE_WAVEFORMATEX_GUID, and m_dataRangesItem.
Referenced by Instantiate().
MakeFormat()
KSPIN_CONNECT * WinWdmPin::MakeFormat (const WAVEFORMATEX * pFormat) const
References ASSERT, and m_iPinId.
Referenced by Instantiate().
SetState()
bool WinWdmPin::SetState (KSSTATE state, RString & sError)
References ASSERT, m_hHandle, and WdmSetPropertySimple().
Referenced by Close(), and RageSoundDriver_WDMKS::MixerThread().
Member Data Documentation
m_dataRangesItem
vector<KSDATARANGE_AUDIO> WinWdmPin::m_dataRangesItem
Referenced by WinWdmFilter::CreatePin(), RageSoundDriver_WDMKS::Init(), WinWdmFilter::InstantiateRenderPin(), and IsFormatSupported().
m_hHandle
HANDLE WinWdmPin::m_hHandle
Referenced by Close(), RageSoundDriver_WDMKS::GetPosition(), Instantiate(), WinWdmStream::Open(), SetState(), WinWdmStream::SubmitPacket(), and WinWdmPin().
m_iPinId
int WinWdmPin::m_iPinId
Referenced by MakeFormat(), and WinWdmPin().
m_pParentFilter
WinWdmFilter* WinWdmPin::m_pParentFilter
Referenced by Close(), Instantiate(), and WinWdmPin().
The documentation for this struct was generated from the following file:
RageSoundDriver_WDMKS.cpp