Etterna: GameStateMessageHandler Class Reference
GameStateMessageHandler Class Reference
Private Member Functions
void HandleMessage (const Message &msg) override
Additional Inherited Members
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Member Function Documentation
HandleMessage()
void GameStateMessageHandler::HandleMessage (const Message & msg) inline override private virtual
Implements IMessageSubscriber.
References FOREACH_HumanPlayer, Message::GetName(), LOG, RageLog::MapLog(), and ssprintf().
The documentation for this class was generated from the following file:
GameState.cpp