Etterna: RageSurface_Load_JPEG.h File Reference
RageSurface_Load_JPEG.h File Reference
#include "global.h"
#include "RageSurface_Load.h"
Functions
RageSurfaceUtils::OpenResult RageSurface_Load_JPEG (const RString &sPath, RageSurface *&ret, bool bHeaderOnly, RString &error)
Function Documentation
RageSurface_Load_JPEG()
RageSurfaceUtils::OpenResult RageSurface_Load_JPEG (const RString & sPath, RageSurface *& ret, bool bHeaderOnly, RString & error)
References my_jpeg_error_mgr::errorbuf, f, RageFile::GetError(), RageFile::Open(), RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, and RageSurface_Load_JPEG().