Etterna: Rage::ci_ascii_char_traits Struct Reference
Rage::ci_ascii_char_traits Struct Reference
A trait to allow for case insensitive strings...assuming ASCII.
#include <RageString.h>
Static Public Member Functions
static unsigned char asciiToLower (char c)
A helper function to cast to lowercase whenever possible.
static bool eq (char c1, char c2)
Determine if the two characters match.
static bool ne (char c1, char c2)
Determine if the two characters do not match.
static bool lt (char c1, char c2)
Determine if the first character is less than the other character.
static int compare (char const *c1, char const *c2, size_t n)
Compare the two characters to see the proper order.
static char const * find (char const *s, int n, char a)
Attempt to find the wanted character.
Detailed Description
A trait to allow for case insensitive strings...assuming ASCII.
Member Function Documentation
asciiToLower()
static unsigned char Rage::ci_ascii_char_traits::asciiToLower (char c) inline static
A helper function to cast to lowercase whenever possible.
Referenced by compare(), eq(), find(), lt(), and ne().
compare()
static int Rage::ci_ascii_char_traits::compare (char const * c1, char const * c2, size_t n) inline static
Compare the two characters to see the proper order.
References asciiToLower().
eq()
static bool Rage::ci_ascii_char_traits::eq (char c1, char c2) inline static
Determine if the two characters match.
References asciiToLower().
find()
static char const* Rage::ci_ascii_char_traits::find (char const * s, int n, char a) inline static
Attempt to find the wanted character.
References asciiToLower().
lt()
static bool Rage::ci_ascii_char_traits::lt (char c1, char c2) inline static
Determine if the first character is less than the other character.
References asciiToLower().
ne()
static bool Rage::ci_ascii_char_traits::ne (char c1, char c2) inline static
Determine if the two characters do not match.
References asciiToLower().
The documentation for this struct was generated from the following file:
RageString.h