Etterna: ScoresAtRate Struct Reference
ScoresAtRate Struct Reference
#include <ScoreManager.h>
Public Member Functions
ScoresAtRate ()
HighScore * AddScore (HighScore &hs)
vector< string > GetSortedKeys ()
void PushSelf (lua_State *L)
bool HandleNoCCPB (HighScore &hs)
XNode * CreateNode (const int &rate) const
void LoadFromNode (const XNode *node, const string &key, const float &rate, const string &profileID)
const vector< HighScore * > GetScores (const string) const
Public Attributes
HighScore * PBptr
HighScore * noccPBptr
Grade bestGrade
unordered_map< string, HighScore > scores
Constructor & Destructor Documentation
ScoresAtRate()
ScoresAtRate::ScoresAtRate ()
References bestGrade, Grade_Invalid, noccPBptr, PBptr, and scores.
Member Function Documentation
AddScore()
HighScore * ScoresAtRate::AddScore (HighScore & hs)
References ScoreManager::AddToKeyedIndex(), bestGrade, HighScore::GetChordCohesion(), HighScore::GetScoreKey(), HighScore::GetSSRNormPercent(), HighScore::GetWifeGrade(), min(), noccPBptr, PBptr, ScoreManager::RegisterScore(), and scores.
CreateNode()
XNode * ScoresAtRate::CreateNode (const int & rate) const
References XNode::AppendAttr(), XNode::AppendChild(), bestGrade, XNode::ChildrenEmpty(), f, FOREACHUM_CONST, HighScore::GetScoreKey(), GradeToString(), ScoreManager::minpercent, noccPBptr, PBptr, scores, and ssprintf().
GetScores()
const vector<HighScore*> ScoresAtRate::GetScores (const string) const
GetSortedKeys()
vector< string > ScoresAtRate::GetSortedKeys ()
References FOREACHM, FOREACHUM, and scores.
Referenced by LunaScoresAtRate::GetScores().
HandleNoCCPB()
bool ScoresAtRate::HandleNoCCPB (HighScore & hs)
References HighScore::GetChordCohesion(), HighScore::GetSSRNormPercent(), and noccPBptr.
Referenced by LoadFromNode().
LoadFromNode()
void ScoresAtRate::LoadFromNode (const XNode * node, const string & key, const float & rate, const string & profileID)
References ScoreManager::AddToKeyedIndex(), bestGrade, FOREACH_CONST_Child, HighScore::GetSSRNormPercent(), HandleNoCCPB(), min(), PBptr, ScoreManager::RegisterScore(), ScoreManager::RegisterScoreInProfile(), and scores.
PushSelf()
void ScoresAtRate::PushSelf (lua_State * L)
Referenced by LunaScoreManager::GetScoresByKey().
Member Data Documentation
bestGrade
Grade ScoresAtRate::bestGrade
Referenced by AddScore(), CreateNode(), LoadFromNode(), and ScoresAtRate().
noccPBptr
HighScore* ScoresAtRate::noccPBptr
Referenced by AddScore(), CreateNode(), HandleNoCCPB(), and ScoresAtRate().
PBptr
HighScore* ScoresAtRate::PBptr
Referenced by AddScore(), CreateNode(), LoadFromNode(), and ScoresAtRate().
scores
unordered_map<string, HighScore> ScoresAtRate::scores
Referenced by AddScore(), CreateNode(), LunaScoresAtRate::GetScores(), GetSortedKeys(), LoadFromNode(), and ScoresAtRate().
The documentation for this struct was generated from the following files:
ScoreManager.h
ScoreManager.cpp