Etterna: LowLevelWindow_MacOSX Class Reference
LowLevelWindow_MacOSX Class Reference
#include <LowLevelWindow_MacOSX.h>
Public Member Functions
LowLevelWindow_MacOSX ()
~LowLevelWindow_MacOSX ()
void * GetProcAddress (const RString &s)
RString TryVideoMode (const VideoModeParams &p, bool &newDeviceOut)
void GetDisplayResolutions (DisplayResolutions &dr) const
void SwapBuffers ()
void Update ()
const VideoModeParams * GetActualVideoModeParams () const
bool SupportsRenderToTexture () const
RenderTarget * CreateRenderTarget ()
bool SupportsThreadedRendering ()
void BeginConcurrentRendering ()
Public Member Functions inherited from LowLevelWindow
virtual ~LowLevelWindow ()=default
virtual void LogDebugInformation () const
virtual bool IsSoftwareRenderer (RString &)
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void EndConcurrentRendering ()
Private Member Functions
void ShutDownFullScreen ()
int ChangeDisplayMode (const VideoModeParams &p)
void SetActualParamsFromMode (CFDictionaryRef mode)
Private Attributes
VideoModeParams m_CurrentParams
id m_WindowDelegate
id m_Context
id m_BGContext
CFDictionaryRef m_CurrentDisplayMode
CGDirectDisplayID m_DisplayID
Additional Inherited Members
Static Public Member Functions inherited from LowLevelWindow
static LowLevelWindow * Create ()
Constructor & Destructor Documentation
LowLevelWindow_MacOSX()
LowLevelWindow_MacOSX::LowLevelWindow_MacOSX ()
References HOOKS, m_CurrentParams, m_WindowDelegate, POOL, SetActualParamsFromMode(), ArchHooks::SetHasFocus(), and VideoModeParams::windowed.
~LowLevelWindow_MacOSX()
LowLevelWindow_MacOSX::~LowLevelWindow_MacOSX ()
References m_BGContext, m_Context, m_WindowDelegate, POOL, and ShutDownFullScreen().
Member Function Documentation
BeginConcurrentRendering()
void LowLevelWindow_MacOSX::BeginConcurrentRendering () virtual
Reimplemented from LowLevelWindow.
References m_BGContext, m_CurrentParams, and VideoModeParams::windowed.
ChangeDisplayMode()
int LowLevelWindow_MacOSX::ChangeDisplayMode (const VideoModeParams & p) private
References VideoModeParams::bpp, VideoModeParams::height, m_CurrentDisplayMode, m_CurrentParams, m_DisplayID, VideoModeParams::rate, REFRESH_DEFAULT, SetActualParamsFromMode(), VideoModeParams::width, and VideoModeParams::windowed.
Referenced by TryVideoMode().
CreateRenderTarget()
RenderTarget * LowLevelWindow_MacOSX::CreateRenderTarget () virtual
Reimplemented from LowLevelWindow.
References m_Context.
GetActualVideoModeParams()
const VideoModeParams* LowLevelWindow_MacOSX::GetActualVideoModeParams () const inline virtual
Implements LowLevelWindow.
References m_CurrentParams.
GetDisplayResolutions()
void LowLevelWindow_MacOSX::GetDisplayResolutions (DisplayResolutions & dr) const virtual
Implements LowLevelWindow.
References ASSERT, GetBoolValue(), and GetIntValue().
GetProcAddress()
void * LowLevelWindow_MacOSX::GetProcAddress (const RString & s) virtual
Implements LowLevelWindow.
SetActualParamsFromMode()
void LowLevelWindow_MacOSX::SetActualParamsFromMode (CFDictionaryRef mode) private
References VideoModeParams::bpp, GetDisplayBitsPerPixel(), VideoModeParams::height, m_CurrentParams, VideoModeParams::rate, swap(), VideoModeParams::vsync, VideoModeParams::width, and VideoModeParams::windowed.
Referenced by ChangeDisplayMode(), LowLevelWindow_MacOSX(), ShutDownFullScreen(), and TryVideoMode().
ShutDownFullScreen()
void LowLevelWindow_MacOSX::ShutDownFullScreen () private
References ASSERT, f, m_BGContext, m_Context, m_CurrentDisplayMode, m_CurrentParams, m_DisplayID, SetActualParamsFromMode(), and VideoModeParams::windowed.
Referenced by TryVideoMode(), and ~LowLevelWindow_MacOSX().
SupportsRenderToTexture()
bool LowLevelWindow_MacOSX::SupportsRenderToTexture () const inline virtual
Reimplemented from LowLevelWindow.
SupportsThreadedRendering()
bool LowLevelWindow_MacOSX::SupportsThreadedRendering () inline virtual
Reimplemented from LowLevelWindow.
References m_BGContext.
SwapBuffers()
void LowLevelWindow_MacOSX::SwapBuffers () virtual
Implements LowLevelWindow.
TryVideoMode()
RString LowLevelWindow_MacOSX::TryVideoMode (const VideoModeParams & p, bool & newDeviceOut) virtual
Implements LowLevelWindow.
References ArchHooks::AppHasFocus(), ASSERT, VideoModeParams::bAnisotropicFiltering, VideoModeParams::bpp, VideoModeParams::bSmoothLines, VideoModeParams::bTrilinearFiltering, ChangeDisplayMode(), CreateOGLContext(), VideoModeParams::fDisplayAspectRatio, FULL_SCREEN, VideoModeParams::height, HOOKS, VideoModeParams::interlaced, m_BGContext, m_Context, m_CurrentParams, m_WindowDelegate, VideoModeParams::PAL, POOL, VideoModeParams::rate, SetActualParamsFromMode(), ShutDownFullScreen(), ssprintf(), swap(), VideoModeParams::vsync, VideoModeParams::width, WINDOWED, VideoModeParams::windowed, and X.
Update()
void LowLevelWindow_MacOSX::Update () virtual
Reimplemented from LowLevelWindow.
References DISPLAY, g_bResized, g_iHeight, g_iWidth, g_ResizeLock, VideoModeParams::height, likely, m_Context, m_CurrentParams, RageDisplay::ResolutionChanged(), LockMutex::Unlock(), and VideoModeParams::width.
Member Data Documentation
m_BGContext
id LowLevelWindow_MacOSX::m_BGContext private
Referenced by BeginConcurrentRendering(), ShutDownFullScreen(), SupportsThreadedRendering(), TryVideoMode(), and ~LowLevelWindow_MacOSX().
m_Context
id LowLevelWindow_MacOSX::m_Context private
Referenced by CreateRenderTarget(), ShutDownFullScreen(), TryVideoMode(), Update(), and ~LowLevelWindow_MacOSX().
m_CurrentDisplayMode
CFDictionaryRef LowLevelWindow_MacOSX::m_CurrentDisplayMode private
Referenced by ChangeDisplayMode(), and ShutDownFullScreen().
m_CurrentParams
VideoModeParams LowLevelWindow_MacOSX::m_CurrentParams private
Referenced by BeginConcurrentRendering(), ChangeDisplayMode(), GetActualVideoModeParams(), LowLevelWindow_MacOSX(), SetActualParamsFromMode(), ShutDownFullScreen(), TryVideoMode(), and Update().
m_DisplayID
CGDirectDisplayID LowLevelWindow_MacOSX::m_DisplayID private
Referenced by ChangeDisplayMode(), and ShutDownFullScreen().
m_WindowDelegate
id LowLevelWindow_MacOSX::m_WindowDelegate private
Referenced by LowLevelWindow_MacOSX(), TryVideoMode(), and ~LowLevelWindow_MacOSX().
The documentation for this class was generated from the following files:
LowLevelWindow_MacOSX.h
LowLevelWindow_MacOSX.mm