Etterna: ALSA9Dynamic.cpp File Reference
ALSA9Dynamic.cpp File Reference
#include "global.h"
#include <dlfcn.h>
#include <alsa/asoundlib.h>
#include "ALSA9Dynamic.h"
#include "RageUtil.h"
#include "ALSA9Functions.h"
Macros
#define ALSA_PCM_NEW_HW_PARAMS_API
#define ALSA_PCM_NEW_SW_PARAMS_API
#define FUNC(ret, name, proto) name##_f d##name = NULL
#define FUNC(ret, name, proto)
#define FUNC(ret, name, proto) d##name = NULL;
Functions
RString LoadALSA ()
void UnloadALSA ()
Variables
static void * Handle = NULL
static const RString lib = "libasound.so.2"
Macro Definition Documentation
ALSA_PCM_NEW_HW_PARAMS_API
#define ALSA_PCM_NEW_HW_PARAMS_API
ALSA_PCM_NEW_SW_PARAMS_API
#define ALSA_PCM_NEW_SW_PARAMS_API
FUNC [1/3]
#define FUNC (ret, name, proto) name##_f d##name = NULL
FUNC [2/3]
#define FUNC (ret, name, proto)
Value:
d##name = (name##_f)dlsym(Handle, "__" #name);                             \
    if (!d##name) {                                                            \
        d##name = (name##_f)dlsym(Handle, #name);                              \
        if (!d##name) {                                                        \
            error = "Couldn't load symbol " #name;                             \
            goto error;                                                        \
        }                                                                      \
    }
FUNC [3/3]
#define FUNC (ret, name, proto) d##name = NULL;
Function Documentation
LoadALSA()
RString LoadALSA ()
References ASSERT, Handle, IsADirectory(), ssprintf(), and UnloadALSA().
Referenced by RageSoundDriver_ALSA9_Software::Init().
UnloadALSA()
void UnloadALSA ()
References Handle.
Referenced by LoadALSA(), and RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software().
Variable Documentation
Handle
void* Handle = NULL static
Referenced by LoadALSA(), and UnloadALSA().
lib
const RString lib = "libasound.so.2" static