Etterna: BMSChart Class Reference
BMSChart Class Reference
Public Member Functions
BMSChart ()
bool Load (const RString &path)
bool GetHeader (const RString &header, RString &out)
void TidyUpData ()
Public Attributes
RString path
BMSObjects objects
BMSHeaders headers
BMSMeasures measures
map< int, bool > referencedTracks
Constructor & Destructor Documentation
BMSChart()
BMSChart::BMSChart () default
Member Function Documentation
GetHeader()
bool BMSChart::GetHeader (const RString & header, RString & out)
References headers.
Load()
bool BMSChart::Load (const RString & path)
References RageFile::AtEOF(), bmsCommandTree::doStatement(), bmsCommandTree::evaluateBMSTree(), RageFile::GetError(), RageFile::GetLine(), headers, LOG, StdString::CStdStr< CT >::MakeLower(), measures, objects, RageFile::Open(), path, bmsCommandTree::path, referencedTracks, StringToFloat(), StripCrnl(), TidyUpData(), and RageLog::UserLog().
Referenced by BMSSongLoader::Load(), and BMSLoader::LoadNoteDataFromSimfile().
TidyUpData()
void BMSChart::TidyUpData ()
References objects.
Referenced by Load().
Member Data Documentation
headers
BMSHeaders BMSChart::headers
Referenced by GetHeader(), BMSChartReader::GetKeysound(), Load(), BMSChartReader::ReadHeaders(), and BMSChartReader::ReadNoteData().
measures
BMSMeasures BMSChart::measures
Referenced by Load(), and BMSChartReader::ReadNoteData().
objects
BMSObjects BMSChart::objects
Referenced by Load(), BMSChartReader::ReadNoteData(), and TidyUpData().
path
RString BMSChart::path
Referenced by BMSChartReader::DetermineStepsType(), BMSChartReader::GetKeysound(), Load(), and BMSChartReader::ReadNoteData().
referencedTracks
map<int, bool> BMSChart::referencedTracks
Referenced by BMSChartReader::BMSChartReader(), and Load().
The documentation for this class was generated from the following file:
NotesLoaderBMS.cpp