Etterna: ScreenSetTime.cpp File Reference
ScreenSetTime.cpp File Reference
#include "ScreenSetTime.h"
#include "DateTime.h"
#include "EnumHelper.h"
#include "InputEventPlus.h"
#include "InputMapper.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "ThemeManager.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "global.h"
Macros
#define FOREACH_SetTimeSelection(s) FOREACH_ENUM(SetTimeSelection, s)
A foreach iterator through the time selections.
Functions
XToString (SetTimeSelection)
static float GetTitleX (SetTimeSelection s)
static float GetTitleY (SetTimeSelection s)
static float GetValueX (SetTimeSelection s)
static float GetValueY (SetTimeSelection s)
REGISTER_SCREEN_CLASS (ScreenSetTime)
Variables
static const char * SetTimeSelectionNames []
const float g_X [NUM_SetTimeSelection] = { 320, 320, 320, 320, 320, 320 }
const float g_Y [NUM_SetTimeSelection] = { 140, 180, 220, 260, 300, 340 }
Macro Definition Documentation
FOREACH_SetTimeSelection
#define FOREACH_SetTimeSelection (s) FOREACH_ENUM(SetTimeSelection, s)
A foreach iterator through the time selections.
Referenced by ScreenSetTime::Init(), and ScreenSetTime::MenuStart().
Function Documentation
GetTitleX()
static float GetTitleX (SetTimeSelection s) static
References g_X.
Referenced by ScreenSetTime::Init().
GetTitleY()
static float GetTitleY (SetTimeSelection s) static
References g_Y.
Referenced by ScreenSetTime::Init().
GetValueX()
static float GetValueX (SetTimeSelection s) static
References g_X.
Referenced by ScreenSetTime::Init().
GetValueY()
static float GetValueY (SetTimeSelection s) static
References g_Y.
Referenced by ScreenSetTime::Init().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenSetTime)
XToString()
XToString (SetTimeSelection)
Variable Documentation
g_X
const float g_X[NUM_SetTimeSelection] = { 320, 320, 320, 320, 320, 320 }
Referenced by GetTitleX(), and GetValueX().
g_Y
const float g_Y[NUM_SetTimeSelection] = { 140, 180, 220, 260, 300, 340 }
Referenced by GetTitleY(), and GetValueY().
SetTimeSelectionNames
const char* SetTimeSelectionNames[] static
Initial value:
= {
    "Year", "Month", "Day", "Hour", "Minute", "Second",
}