Etterna: RageFileObjMemFile Struct Reference
RageFileObjMemFile Struct Reference
Public Member Functions
RageFileObjMemFile ()
Static Public Member Functions
static void AddReference (RageFileObjMemFile *pFile)
static void ReleaseReference (RageFileObjMemFile *pFile)
Public Attributes
RString m_sBuf
int m_iRefs
RageMutex m_Mutex
Constructor & Destructor Documentation
RageFileObjMemFile()
RageFileObjMemFile::RageFileObjMemFile () inline
Member Function Documentation
AddReference()
static void RageFileObjMemFile::AddReference (RageFileObjMemFile * pFile) inline static
References RageMutex::Lock(), m_iRefs, m_Mutex, and RageMutex::Unlock().
Referenced by RageFileDriverMem::Open(), and RageFileObjMem::RageFileObjMem().
ReleaseReference()
static void RageFileObjMemFile::ReleaseReference (RageFileObjMemFile * pFile) inline static
References ASSERT, RageMutex::Lock(), m_iRefs, m_Mutex, and RageMutex::Unlock().
Referenced by RageFileDriverMem::Remove(), RageFileDriverMem::~RageFileDriverMem(), and RageFileObjMem::~RageFileObjMem().
Member Data Documentation
m_iRefs
int RageFileObjMemFile::m_iRefs
Referenced by AddReference(), and ReleaseReference().
m_Mutex
RageMutex RageFileObjMemFile::m_Mutex
Referenced by AddReference(), RageFileObjMem::GetFileSize(), RageFileObjMem::PutString(), RageFileObjMem::ReadInternal(), ReleaseReference(), and RageFileObjMem::WriteInternal().
m_sBuf
RString RageFileObjMemFile::m_sBuf
Referenced by RageFileObjMem::GetFileSize(), RageFileObjMem::GetString(), RageFileObjMem::PutString(), RageFileObjMem::ReadInternal(), and RageFileObjMem::WriteInternal().
The documentation for this struct was generated from the following file:
RageFileDriverMemory.cpp