Etterna: ActorUtil Namespace Reference
ActorUtil Namespace Reference
Utility functions for creating and manipulating Actors.
Functions
void InitFileTypeLists ()
vector< RString > const & GetTypeExtensionList (FileType ft)
void AddTypeExtensionsToList (FileType ft, vector< RString > &add_to)
void Register (const RString &sClassName, CreateActorFn pfn)
apActorCommands ParseActorCommands (const RString &sCommands, const RString &sName="")
void SetXY (Actor &actor, const RString &sMetricsGroup)
void PlayCommand (Actor &actor, const RString &sCommandName)
void OnCommand (Actor &actor)
void OffCommand (Actor &actor)
void LoadCommand (Actor &actor, const RString &sMetricsGroup, const RString &sCommandName)
void LoadCommandFromName (Actor &actor, const RString &sMetricsGroup, const RString &sCommandName, const RString &sName)
void LoadAllCommands (Actor &actor, const RString &sMetricsGroup)
void LoadAllCommandsFromName (Actor &actor, const RString &sMetricsGroup, const RString &sName)
void LoadAllCommandsAndSetXY (Actor &actor, const RString &sMetricsGroup)
void LoadAllCommandsAndOnCommand (Actor &actor, const RString &sMetricsGroup)
void SetXYAndOnCommand (Actor &actor, const RString &sMetricsGroup)
void LoadAllCommandsAndSetXYAndOnCommand (Actor &actor, const RString &sMetricsGroup)
void SetXY (Actor *pActor, const RString &sMetricsGroup)
void PlayCommand (Actor *pActor, const RString &sCommandName)
void OnCommand (Actor *pActor)
void OffCommand (Actor *pActor)
void LoadAllCommands (Actor *pActor, const RString &sMetricsGroup)
void LoadAllCommandsAndSetXY (Actor *pActor, const RString &sMetricsGroup)
void LoadAllCommandsAndOnCommand (Actor *pActor, const RString &sMetricsGroup)
void SetXYAndOnCommand (Actor *pActor, const RString &sMetricsGroup)
void LoadAllCommandsAndSetXYAndOnCommand (Actor *pActor, const RString &sMetricsGroup)
Actor * LoadFromNode (const XNode *pNode, Actor *pParentActor=nullptr)
Actor * MakeActor (const RString &sPath, Actor *pParentActor=nullptr)
RString GetSourcePath (const XNode *pNode)
RString GetWhere (const XNode *pNode)
bool GetAttrPath (const XNode *pNode, const RString &sName, RString &sOut, bool optional=false)
bool LoadTableFromStackShowErrors (Lua *L)
bool ResolvePath (RString &sPath, const RString &sName, bool optional=false)
void SortByZPosition (vector< Actor *> &vActors)
FileType GetFileType (const RString &sPath)
Detailed Description
Utility functions for creating and manipulating Actors.
Function Documentation
AddTypeExtensionsToList()
void ActorUtil::AddTypeExtensionsToList (FileType ft, vector< RString > & add_to)
Referenced by BMSSong::GetBackground(), and BMSSong::PrecacheBackgrounds().
GetAttrPath()
bool ActorUtil::GetAttrPath (const XNode * pNode, const RString & sName, RString & sOut, bool optional = false)
References XNode::GetAttrValue(), GetWhere(), StdString::CStdStr< CT >::Left(), LOG, ResolvePath(), and RageLog::Warn().
Referenced by HoldJudgment::LoadFromNode(), BGAnimationLayer::LoadFromNode(), BitmapText::LoadFromNode(), ActorSound::LoadFromNode(), DifficultyIcon::LoadFromNode(), Model::LoadFromNode(), Sprite::LoadFromNode(), and ActorMultiVertex::LoadFromNode().
GetFileType()
FileType ActorUtil::GetFileType (const RString & sPath)
References FileType_Invalid, FT_Directory, GetExtension(), IsADirectory(), and StdString::CStdStr< CT >::MakeLower().
Referenced by ScreenSelectMusic::AfterMusicChange(), convert_xmls_in_dir(), BackgroundImpl::Layer::CreateBackground(), ThemeManager::GetPathInfoToRaw(), ScreenWithMenuElements::HandleLuaMusicFile(), actor_template_t::load_node(), RageTextureManager::LoadTextureInternal(), and MakeActor().
GetSourcePath()
RString ActorUtil::GetSourcePath (const XNode * pNode)
References XNode::GetAttrValue().
Referenced by GetWhere(), and LoadFromNode().
GetTypeExtensionList()
vector< RString > const & ActorUtil::GetTypeExtensionList (FileType ft)
Referenced by SongManager::AddGroup(), BMSSong::AllocateKeysound(), Song::GetCacheFile(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), RageSurfaceUtils::LoadFile(), Song::LoadFromSongDir(), RageSoundReader_FileReader::OpenFile(), SongManager::SanityCheckGroupDir(), and Song::TidyUpData().
GetWhere()
RString ActorUtil::GetWhere (const XNode * pNode)
References XNode::GetAttrValue(), GetSourcePath(), and ssprintf().
Referenced by GetAttrPath(), DynamicActorScroller::LoadFromNode(), HoldJudgment::LoadFromNode(), MeterDisplay::LoadFromNode(), StepsDisplayList::LoadFromNode(), BitmapText::LoadFromNode(), DifficultyIcon::LoadFromNode(), PercentageDisplay::LoadFromNode(), Sprite::LoadFromNode(), and LoadFromNode().
InitFileTypeLists()
void ActorUtil::InitFileTypeLists ()
References FT_Bitmap, FT_Ini, FT_Lua, FT_Model, FT_Movie, FT_Sound, FT_Sprite, and FT_Xml.
Referenced by sm_main().
LoadAllCommands() [1/2]
void ActorUtil::LoadAllCommands (Actor & actor, const RString & sMetricsGroup)
References Actor::GetName(), and LoadAllCommandsFromName().
Referenced by BrightnessOverlay::BrightnessOverlay(), GrooveRadar::GrooveRadar(), ScreenGameplaySyncMachine::Init(), ScreenMapControllers::Init(), BeginnerHelper::Init(), ScreenRanking::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), ScreenTextEntryVisual::Init(), HoldJudgment::Load(), ModIcon::Load(), OptionListRow::Load(), PercentageDisplay::Load(), ModIconRow::Load(), GraphDisplay::Load(), OptionRowType::Load(), PaneDisplay::Load(), WheelBase::Load(), OptionsList::Load(), ScreenMapControllers::ActionRow::Load(), LoadAllCommands(), LoadAllCommandsAndOnCommand(), LoadAllCommandsAndSetXY(), LoadAllCommandsAndSetXYAndOnCommand(), AutoActor::LoadAndSetName(), LyricDisplay::LyricDisplay(), MusicWheelItem::MusicWheelItem(), ScreenNetEvaluation::RedoUserTexts(), and ScreenNetSelectBase::UpdateUsers().
LoadAllCommands() [2/2]
void ActorUtil::LoadAllCommands (Actor * pActor, const RString & sMetricsGroup) inline
References LoadAllCommands().
LoadAllCommandsAndOnCommand() [1/2]
void ActorUtil::LoadAllCommandsAndOnCommand (Actor & actor, const RString & sMetricsGroup) inline
References LoadAllCommands(), and OnCommand().
Referenced by FadingBanner::FadingBanner(), ScoreDisplayLifeTime::Init(), BeginnerHelper::Init(), TextBanner::Load(), MenuTimer::Load(), and LoadAllCommandsAndOnCommand().
LoadAllCommandsAndOnCommand() [2/2]
void ActorUtil::LoadAllCommandsAndOnCommand (Actor * pActor, const RString & sMetricsGroup) inline
References LoadAllCommandsAndOnCommand().
LoadAllCommandsAndSetXY() [1/2]
void ActorUtil::LoadAllCommandsAndSetXY (Actor & actor, const RString & sMetricsGroup) inline
References LoadAllCommands(), and SetXY().
Referenced by GrooveRadar::GrooveRadar(), ScreenHowToPlay::Init(), LifeMeterBar::LifeMeterBar(), LifeMeterBattery::Load(), MenuTimer::Load(), OptionRowType::Load(), LoadAllCommandsAndSetXY(), and ScoreDisplayNormal::ScoreDisplayNormal().
LoadAllCommandsAndSetXY() [2/2]
void ActorUtil::LoadAllCommandsAndSetXY (Actor * pActor, const RString & sMetricsGroup) inline
References LoadAllCommandsAndSetXY().
LoadAllCommandsAndSetXYAndOnCommand() [1/2]
void ActorUtil::LoadAllCommandsAndSetXYAndOnCommand (Actor & actor, const RString & sMetricsGroup) inline
References LoadAllCommands(), OnCommand(), and SetXY().
Referenced by ModIcon::Load(), StepsDisplay::Load(), and LoadAllCommandsAndSetXYAndOnCommand().
LoadAllCommandsAndSetXYAndOnCommand() [2/2]
void ActorUtil::LoadAllCommandsAndSetXYAndOnCommand (Actor * pActor, const RString & sMetricsGroup) inline
References LoadAllCommandsAndSetXYAndOnCommand().
LoadAllCommandsFromName()
void ActorUtil::LoadAllCommandsFromName (Actor & actor, const RString & sMetricsGroup, const RString & sName)
References EndsWith(), FOREACHS_CONST, ThemeManager::GetMetricsThatBeginWith(), LoadCommandFromName(), and THEME.
Referenced by Screen::Init(), PaneDisplay::Load(), and LoadAllCommands().
LoadCommand()
void ActorUtil::LoadCommand (Actor & actor, const RString & sMetricsGroup, const RString & sCommandName)
References Actor::GetName(), and LoadCommandFromName().
Referenced by ScoreDisplayLifeTime::Init(), and Player::Init().
LoadCommandFromName()
void ActorUtil::LoadCommandFromName (Actor & actor, const RString & sMetricsGroup, const RString & sCommandName, const RString & sName)
References Actor::AddCommand(), ThemeManager::GetMetricA(), and THEME.
Referenced by LoadAllCommandsFromName(), and LoadCommand().
LoadFromNode()
Actor * ActorUtil::LoadFromNode (const XNode * pNode, Actor * pParentActor = nullptr)
References ASSERT, Dirname(), g_pmapRegistrees, XNode::GetAttr(), XNode::GetAttrValue(), GetSourcePath(), GetWhere(), StdString::CStdStr< CT >::Left(), Actor::LoadFromNode(), MakeActor(), LuaHelpers::ReportScriptError(), ResolvePath(), Actor::SetParent(), and ssprintf().
Referenced by NoteSkinManager::LoadActor(), AutoActor::LoadActorFromNode(), ActorFrame::LoadChildrenFromNode(), BGAnimationLayer::LoadFromNode(), and MakeActor().
LoadTableFromStackShowErrors()
bool ActorUtil::LoadTableFromStackShowErrors (Lua * L)
References LuaReference::PushSelf(), LuaHelpers::ReportScriptError(), LuaHelpers::RunScriptOnStack(), LuaReference::SetFromStack(), and ssprintf().
Referenced by NoteSkinManager::PushActorTemplate().
MakeActor()
Actor * ActorUtil::MakeActor (const RString & sPath, Actor * pParentActor = nullptr)
References XmlFileUtil::AnnotateXNodeTree(), XNode::AppendAttr(), XmlFileUtil::CompileXNodeTree(), DoesFileExist(), FileTypeToString(), FT_Bitmap, FT_Directory, FT_Lua, FT_Model, FT_Movie, FT_Sprite, FT_Xml, XNode::GetChild(), GetFileType(), XmlFileUtil::LoadFromFileShowErrors(), LoadFromNode(), LOG, PrefsManager::m_bQuirksMode, PREFSMAN, IniFile::ReadFile(), StdString::CStdStr< CT >::Right(), and RageLog::Warn().
Referenced by LunaActorFrame::AddChildFromPath(), BackgroundImpl::Layer::CreateBackground(), ComboGraph::Load(), OptionRowType::Load(), AutoActor::Load(), BGAnimationLayer::LoadFromNode(), LoadFromNode(), Foreground::LoadFromSong(), and ScreenManager::PrepareScreen().
OffCommand() [1/2]
void ActorUtil::OffCommand (Actor & actor) inline
References ASSERT_M, Actor::GetLineage(), Actor::GetName(), Actor::HasCommand(), Actor::PlayCommand(), and ssprintf().
Referenced by OffCommand().
OffCommand() [2/2]
void ActorUtil::OffCommand (Actor * pActor) inline
References OffCommand().
OnCommand() [1/2]
void ActorUtil::OnCommand (Actor & actor) inline
References ASSERT_M, Actor::GetLineage(), Actor::HasCommand(), Actor::PlayCommand(), and ssprintf().
Referenced by LoadAllCommandsAndOnCommand(), LoadAllCommandsAndSetXYAndOnCommand(), OnCommand(), SetXYAndOnCommand(), and ScreenNetSelectBase::UpdateUsers().
OnCommand() [2/2]
void ActorUtil::OnCommand (Actor * pActor) inline
References OnCommand().
ParseActorCommands()
apActorCommands ActorUtil::ParseActorCommands (const RString & sCommands, const RString & sName = "")
References LuaManager::Get(), LUA, LuaHelpers::ParseCommandList(), and LuaManager::Release().
Referenced by NoteSkinManager::GetMetricA(), BackgroundImpl::Init(), Character::Load(), and BGAnimation::LoadFromNode().
PlayCommand() [1/2]
void ActorUtil::PlayCommand (Actor & actor, const RString & sCommandName) inline
References Actor::PlayCommand().
PlayCommand() [2/2]
void ActorUtil::PlayCommand (Actor * pActor, const RString & sCommandName) inline
References Actor::PlayCommand().
Register()
void ActorUtil::Register (const RString & sClassName, CreateActorFn pfn)
References ASSERT_M, g_pmapRegistrees, and ssprintf().
ResolvePath()
bool ActorUtil::ResolvePath (RString & sPath, const RString & sName, bool optional = false)
References CollapsePath(), DerefRedir(), DoesFileExist(), FAIL_M, FILEMAN, ThemeManager::FilterFileLanguages(), RageFileManager::FlushDirCache(), GetDirListing(), RageFileManager::GetFileType(), Rage::join(), LuaHelpers::ReportScriptError(), ssprintf(), THEME, RageException::Throw(), RageFileManager::TYPE_DIR, and RageFileManager::TYPE_FILE.
Referenced by GetAttrPath(), and LoadFromNode().
SetXY() [1/2]
void ActorUtil::SetXY (Actor & actor, const RString & sMetricsGroup)
References ASSERT, ThemeManager::GetMetricF(), Actor::GetName(), Actor::SetXY(), and THEME.
Referenced by PercentageDisplay::Load(), PaneDisplay::Load(), LoadAllCommandsAndSetXY(), LoadAllCommandsAndSetXYAndOnCommand(), MusicWheelItem::MusicWheelItem(), SetXY(), and SetXYAndOnCommand().
SetXY() [2/2]
void ActorUtil::SetXY (Actor * pActor, const RString & sMetricsGroup) inline
References SetXY().
SetXYAndOnCommand() [1/2]
void ActorUtil::SetXYAndOnCommand (Actor & actor, const RString & sMetricsGroup) inline
References OnCommand(), and SetXY().
Referenced by SetXYAndOnCommand().
SetXYAndOnCommand() [2/2]
void ActorUtil::SetXYAndOnCommand (Actor * pActor, const RString & sMetricsGroup) inline
References SetXYAndOnCommand().
SortByZPosition()
void ActorUtil::SortByZPosition (vector< Actor *> & vActors)
References CompareActorsByZPosition().
Referenced by ActorFrame::DrawPrimitives(), and ActorScroller::PositionItemsAndDrawPrimitives().