Etterna: RadarValues Struct Reference
RadarValues Struct Reference
Cached song statistics.
#include <RadarValues.h>
Public Member Functions
int operator[] (RadarCategory cat) const
int & operator[] (RadarCategory cat)
int operator[] (int cat) const
int & operator[] (int cat)
RadarValues ()
void MakeUnknown ()
void Zero ()
RadarValues & operator+= (const RadarValues &other)
Add one set of radar values to another.
bool operator== (const RadarValues &other) const
Determine if one set of radar values are equal to another.
bool operator!= (const RadarValues &other) const
Determine if one set of radar values are not equal to another.
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
RString ToString (int iMaxValues=-1) const
void FromString (const RString &sValues)
void PushSelf (lua_State *L)
Static Public Attributes
static ThemeMetric< bool > WRITE_SIMPLE_VALIES
static ThemeMetric< bool > WRITE_COMPLEX_VALIES
Private Attributes
int m_Values [NUM_RadarCategory]
Detailed Description
Cached song statistics.
Constructor & Destructor Documentation
RadarValues()
RadarValues::RadarValues ()
References MakeUnknown().
Member Function Documentation
CreateNode()
XNode * RadarValues::CreateNode () const
References XNode::AppendChild(), FOREACH_ENUM, and RadarCategoryToString().
Referenced by HighScoreImpl::CreateNode().
FromString()
void RadarValues::FromString (const RString & sValues)
References FOREACH_ENUM, MakeUnknown(), NUM_RadarCategory, split(), and StringToInt().
LoadFromNode()
void RadarValues::LoadFromNode (const XNode * pNode)
References ASSERT, FOREACH_ENUM, XNode::GetChildValue(), XNode::GetName(), RadarCategoryToString(), and Zero().
Referenced by HighScoreImpl::LoadFromNode().
MakeUnknown()
void RadarValues::MakeUnknown ()
References FOREACH_ENUM, and RADAR_VAL_UNKNOWN.
Referenced by FromString(), HighScoreImpl::HighScoreImpl(), and RadarValues().
operator!=()
bool RadarValues::operator!= (const RadarValues & other) const inline
Determine if one set of radar values are not equal to another.
Parameters
other The otehr set of radar values.
Returns
true if the two sets are not equal, false otherwise.
References operator==().
operator+=()
RadarValues& RadarValues::operator+= (const RadarValues & other) inline
Add one set of radar values to another.
Parameters
other The other set of radar values to add.
Returns
the new set of radar values.
References FOREACH_ENUM.
operator==()
bool RadarValues::operator== (const RadarValues & other) const inline
Determine if one set of radar values are equal to another.
Parameters
other The otehr set of radar values.
Returns
true if the two sets are equal, false otherwise.
References FOREACH_ENUM.
Referenced by operator!=().
operator[]() [1/4]
int RadarValues::operator[] (RadarCategory cat) const inline
operator[]() [2/4]
int& RadarValues::operator[] (RadarCategory cat) inline
operator[]() [3/4]
int RadarValues::operator[] (int cat) const inline
operator[]() [4/4]
int& RadarValues::operator[] (int cat) inline
PushSelf()
void RadarValues::PushSelf (lua_State * L)
Referenced by LunaSteps::GetRadarValues(), and LunaHighScore::GetRadarValues().
ToString()
RString RadarValues::ToString (int iMaxValues = -1) const
References IntToString(), Rage::join(), min(), and NUM_RadarCategory.
Zero()
void RadarValues::Zero ()
References FOREACH_ENUM.
Referenced by NoteDataUtil::CalculateRadarValues(), Steps::CalculateRadarValues(), PlayerStageStats::InternalInit(), LoadFromNode(), SetRadarValues(), and SongCacheIndex::SongFromStatement().
Member Data Documentation
m_Values
int RadarValues::m_Values[NUM_RadarCategory] private
WRITE_COMPLEX_VALIES
ThemeMetric<bool> RadarValues::WRITE_COMPLEX_VALIES static
WRITE_SIMPLE_VALIES
ThemeMetric<bool> RadarValues::WRITE_SIMPLE_VALIES static
The documentation for this struct was generated from the following files:
RadarValues.h
RadarValues.cpp