Etterna: RageTypes.cpp File Reference
RageTypes.cpp File Reference
#include "global.h"
#include "RageTypes.h"
#include "LuaManager.h"
Namespaces
LuaHelpers
Utilities for working with Lua.
Functions
void lerp_rage_color (RageColor &out, RageColor const &a, RageColor const &b, float t)
void WeightedAvergeOfRSVs (RageSpriteVertex &average_out, RageSpriteVertex const &rsv1, RageSpriteVertex const &rsv2, float percent_between)
template<>
bool LuaHelpers::FromStack< RageColor > (lua_State *L, RageColor &Object, int iOffset)
template<>
void LuaHelpers::Push< RageColor > (lua_State *L, const RageColor &Object)
XToString (CullMode)
LuaXType (CullMode)
XToString (BlendMode)
StringToX (BlendMode)
LuaXType (BlendMode)
XToString (TextureMode)
LuaXType (TextureMode)
XToString (EffectMode)
LuaXType (EffectMode)
XToString (ZTestMode)
LuaXType (ZTestMode)
XToString (TextGlowMode)
LuaXType (TextGlowMode)
int LuaFunc_color (lua_State *L)
LUAFUNC_REGISTER_COMMON (color)
int LuaFunc_lerp_color (lua_State *L)
LUAFUNC_REGISTER_COMMON (lerp_color)
Variables
static const char * CullModeNames [] = { "Back", "Front", "None" }
static const char * BlendModeNames []
static const char * TextureModeNames []
static const char * EffectModeNames []
static const char * ZTestModeNames [] = { "Off", "WriteOnPass", "WriteOnFail" }
static const char * TextGlowModeNames [] = { "Inner", "Stroke", "Both" }
Function Documentation
lerp_rage_color()
void lerp_rage_color (RageColor & out, RageColor const & a, RageColor const & b, float t)
References RageColor::a, RageColor::b, RageColor::g, lerp(), and RageColor::r.
Referenced by LuaFunc_lerp_color().
LuaFunc_color()
int LuaFunc_color (lua_State * L)
References RageColor::FromString(), RageColor::PushTable(), and SArg.
LuaFunc_lerp_color()
int LuaFunc_lerp_color (lua_State * L)
References FArg, RageColor::FromStack(), lerp_rage_color(), and RageColor::PushTable().
LUAFUNC_REGISTER_COMMON() [1/2]
LUAFUNC_REGISTER_COMMON (color)
LUAFUNC_REGISTER_COMMON() [2/2]
LUAFUNC_REGISTER_COMMON (lerp_color)
LuaXType() [1/6]
LuaXType (CullMode)
LuaXType() [2/6]
LuaXType (BlendMode)
LuaXType() [3/6]
LuaXType (TextureMode)
LuaXType() [4/6]
LuaXType (EffectMode)
LuaXType() [5/6]
LuaXType (ZTestMode)
LuaXType() [6/6]
LuaXType (TextGlowMode)
StringToX()
StringToX (BlendMode)
WeightedAvergeOfRSVs()
void WeightedAvergeOfRSVs (RageSpriteVertex & average_out, RageSpriteVertex const & rsv1, RageSpriteVertex const & rsv2, float percent_between)
References RageVColor::a, RageVColor::b, RageSpriteVertex::c, RageVColor::g, lerp(), RageSpriteVertex::n, RageSpriteVertex::p, RageVColor::r, and RageSpriteVertex::t.
Referenced by ActorMultiVertex::AMV_TweenState::MakeWeightedAverage().
XToString() [1/6]
XToString (CullMode)
XToString() [2/6]
XToString (BlendMode)
XToString() [3/6]
XToString (TextureMode)
XToString() [4/6]
XToString (EffectMode)
XToString() [5/6]
XToString (ZTestMode)
XToString() [6/6]
XToString (TextGlowMode)
Variable Documentation
BlendModeNames
const char* BlendModeNames[] static
Initial value:
= {
    "Normal",
    "Add",
    "Subtract",
    "Modulate",
    "CopySrc",
    "AlphaMask",
    "AlphaKnockOut",
    "AlphaMultiply",
    "WeightedMultiply",
    "InvertDest",
    "NoEffect"
}
CullModeNames
const char* CullModeNames[] = { "Back", "Front", "None" } static
EffectModeNames
const char* EffectModeNames[] static
Initial value:
= {
    "Normal",
    "Unpremultiply",
    "ColorBurn",
    "ColorDodge",
    "VividLight",
    "HardMix",
    "Overlay",
    "Screen",
    "YUYV422"
}
TextGlowModeNames
const char* TextGlowModeNames[] = { "Inner", "Stroke", "Both" } static
TextureModeNames
const char* TextureModeNames[] static
Initial value:
= {
    "Modulate",
    "Glow",
    "Add",
}
ZTestModeNames
const char* ZTestModeNames[] = { "Off", "WriteOnPass", "WriteOnFail" } static