Etterna: StepsUtil Namespace Reference
StepsUtil Namespace Reference
Utility functions for working with Steps.
Functions
void GetAllMatching (const SongCriteria &soc, const StepsCriteria &stc, vector< SongAndSteps > &out)
Retrieve all of the Steps that match the criteria.
void GetAllMatching (Song *pSong, const StepsCriteria &stc, vector< SongAndSteps > &out)
Retrieve all of the Steps that match the criteria.
void GetAllMatchingEndless (Song *pSong, const StepsCriteria &stc, vector< SongAndSteps > &out)
Retrieve all of the Steps that match the criteria, for Endless mode only.
bool HasMatching (const SongCriteria &soc, const StepsCriteria &stc)
Is there a Step that matches the criteria?
bool HasMatching (const Song *pSong, const StepsCriteria &stc)
Is there a Step that matches the criteria?
bool CompareNotesPointersByRadarValues (const Steps *pSteps1, const Steps *pSteps2)
bool CompareNotesPointersByMeter (const Steps *pSteps1, const Steps *pSteps2)
bool CompareNotesPointersByDifficulty (const Steps *pSteps1, const Steps *pSteps2)
void SortNotesArrayByDifficulty (vector< Steps *> &vpStepsInOut)
bool CompareStepsPointersByTypeAndDifficulty (const Steps *pStep1, const Steps *pStep2)
void SortStepsByTypeAndDifficulty (vector< Steps *> &vpStepsInOut)
void SortStepsPointerArrayByNumPlays (vector< Steps *> &vpStepsInOut, ProfileSlot slot, bool bDescending)
void SortStepsPointerArrayByNumPlays (vector< Steps *> &vpStepsInOut, const Profile *pProfile, bool bDescending)
bool CompareStepsPointersByDescription (const Steps *pStep1, const Steps *pStep2)
void SortStepsByDescription (vector< Steps *> &vpStepsInOut)
Detailed Description
Utility functions for working with Steps.
Function Documentation
CompareNotesPointersByDifficulty()
bool StepsUtil::CompareNotesPointersByDifficulty (const Steps * pSteps1, const Steps * pSteps2)
References Steps::GetDifficulty().
Referenced by SortNotesArrayByDifficulty().
CompareNotesPointersByMeter()
bool StepsUtil::CompareNotesPointersByMeter (const Steps * pSteps1, const Steps * pSteps2)
References Steps::GetMeter().
Referenced by CompareNotesPointersForExtra(), and SortNotesArrayByDifficulty().
CompareNotesPointersByRadarValues()
bool StepsUtil::CompareNotesPointersByRadarValues (const Steps * pSteps1, const Steps * pSteps2)
References Steps::GetRadarValues(), and RadarCategory_TapsAndHolds.
Referenced by CompareNotesPointersForExtra(), and SortNotesArrayByDifficulty().
CompareStepsPointersByDescription()
bool StepsUtil::CompareStepsPointersByDescription (const Steps * pStep1, const Steps * pStep2)
References StdString::CStdStr< CT >::CompareNoCase(), and Steps::GetDescription().
Referenced by SortNotesArrayByDifficulty(), and SortStepsByDescription().
CompareStepsPointersByTypeAndDifficulty()
bool StepsUtil::CompareStepsPointersByTypeAndDifficulty (const Steps * pStep1, const Steps * pStep2)
References Steps::GetDifficulty(), and Steps::m_StepsType.
Referenced by SortStepsByTypeAndDifficulty().
GetAllMatching() [1/2]
void StepsUtil::GetAllMatching (const SongCriteria & soc, const StepsCriteria & stc, vector< SongAndSteps > & out)
Retrieve all of the Steps that match the criteria.
Parameters
soc the SongCriteria to look for.
stc the StepsCriteria to look for.
out the SongsAndSteps that match.
References FOREACH_CONST, SongManager::GetSongs(), GROUP_ALL, SongCriteria::m_sGroupName, SongCriteria::Matches(), and SONGMAN.
Referenced by GetAllMatchingEndless().
GetAllMatching() [2/2]
void StepsUtil::GetAllMatching (Song * pSong, const StepsCriteria & stc, vector< SongAndSteps > & out)
Retrieve all of the Steps that match the criteria.
Parameters
pSong the Song we're checking in.
stc the StepsCriteria to look for.
out the SongsAndSteps that match.
References FOREACH_CONST, Song::GetAllSteps(), Song::GetStepsByStepsType(), StepsCriteria::m_st, StepsCriteria::Matches(), and StepsType_Invalid.
GetAllMatchingEndless()
void StepsUtil::GetAllMatchingEndless (Song * pSong, const StepsCriteria & stc, vector< SongAndSteps > & out)
Retrieve all of the Steps that match the criteria, for Endless mode only.
Parameters
pSong the Song we're checking in.
stc the StepsCriteria to look for.
out the SongsAndSteps that match.
References FOREACH_CONST, GetAllMatching(), Song::GetAllSteps(), Song::GetStepsByStepsType(), StepsCriteria::m_st, and StepsType_Invalid.
HasMatching() [1/2]
bool StepsUtil::HasMatching (const SongCriteria & soc, const StepsCriteria & stc)
Is there a Step that matches the criteria?
Parameters
soc the SongCriteria to look for.
stc the StepsCriteria to look for.
Returns
true if we find a match, false otherwise.
References FOREACH_CONST, SongManager::GetSongs(), GROUP_ALL, SongCriteria::m_sGroupName, SongCriteria::Matches(), and SONGMAN.
HasMatching() [2/2]
bool StepsUtil::HasMatching (const Song * pSong, const StepsCriteria & stc)
Is there a Step that matches the criteria?
Parameters
pSong the Song we're checking in.
stc the StepsCriteria to look for.
Returns
true if we find a match, false otherwise.
References FOREACH_CONST, Song::GetAllSteps(), Song::GetStepsByStepsType(), StepsCriteria::m_st, StepsCriteria::Matches(), and StepsType_Invalid.
SortNotesArrayByDifficulty()
void StepsUtil::SortNotesArrayByDifficulty (vector< Steps *> & vpStepsInOut)
References CompareNotesPointersByDifficulty(), CompareNotesPointersByMeter(), CompareNotesPointersByRadarValues(), and CompareStepsPointersByDescription().
Referenced by SongUtil::AdjustDuplicateSteps(), SongUtil::GetPlayableSteps(), ScreenGameplay::InitSongQueues(), OptionRowHandlerListSteps::Reload(), and SlideDuplicateDifficulties().
SortStepsByDescription()
void StepsUtil::SortStepsByDescription (vector< Steps *> & vpStepsInOut)
References CompareStepsPointersByDescription().
SortStepsByTypeAndDifficulty()
void StepsUtil::SortStepsByTypeAndDifficulty (vector< Steps *> & vpStepsInOut)
References CompareStepsPointersByTypeAndDifficulty().
Referenced by SongUtil::GetPlayableSteps().
SortStepsPointerArrayByNumPlays() [1/2]
void StepsUtil::SortStepsPointerArrayByNumPlays (vector< Steps *> & vpStepsInOut, ProfileSlot slot, bool bDescending)
References ProfileManager::GetProfile(), ProfileManager::IsPersistentProfile(), and PROFILEMAN.
SortStepsPointerArrayByNumPlays() [2/2]
void StepsUtil::SortStepsPointerArrayByNumPlays (vector< Steps *> & vpStepsInOut, const Profile * pProfile, bool bDescending)
References ASSERT, CompareStepsPointersBySortValueAscending(), CompareStepsPointersBySortValueDescending(), SongManager::GetAllSongs(), Song::GetAllSteps(), Profile::GetStepsNumTimesPlayed(), SONGMAN, ssprintf(), and steps_sort_val.