Etterna: NotesWriterSSC.cpp File Reference
NotesWriterSSC.cpp File Reference
#include "global.h"
#include "NotesWriterSSC.h"
#include "BackgroundUtil.h"
#include "Foreach.h"
#include "LocalizedString.h"
#include "NoteTypes.h"
#include "RageFile.h"
#include "RageLog.h"
#include "Song.h"
#include "Steps.h"
Classes
struct TimingTagWriter
Macros
#define WRITE_SEG_LOOP_OPEN(enum_type, seg_type, seg_name, to_func)
#define WRITE_SEG_LOOP_CLOSE
Functions
static RString JoinLineList (vector< RString > &lines)
Turn a vector of lines into a single line joined by newline characters.
static void GetTimingTags (vector< RString > &lines, const TimingData &timing, bool bIsSong=false)
static void write_tag (RageFile &f, RString const &format, std::string const &value)
static void WriteTimingTags (RageFile &f, const TimingData &timing, bool bIsSong=false)
static void WriteGlobalTags (RageFile &f, const Song &out)
Write out the common tags for .SSC files.
static void emplace_back_tag (vector< RString > &lines, RString const &format, RString const &value)
static RString GetSSCNoteData (const Song &song, const Steps &in, bool bSavingCache)
Retrieve the individual batches of NoteData.
Variables
static LocalizedString DESTINATION_ALREADY_EXISTS ("NotesWriterSSC", "Error renaming file. Destination file '%s' already exists.")
static LocalizedString ERROR_WRITING_FILE ("NotesWriterSSC", "Error writing file '%s'.")
Macro Definition Documentation
WRITE_SEG_LOOP_CLOSE
#define WRITE_SEG_LOOP_CLOSE
Value:
}                                                                          \
    writer.Finish();                                                           \
    }                                                                          \
    }
Referenced by GetTimingTags().
WRITE_SEG_LOOP_OPEN
#define WRITE_SEG_LOOP_OPEN (enum_type, seg_type, seg_name, to_func)
Value:
{                                                                          \
        vector<TimingSegment*> const& segs =                                   \
          timing.GetTimingSegments(enum_type);                                 \
        if (!segs.empty()) {                                                   \
            writer.Init(seg_name);                                             \
            for (auto&& seg : segs) {                                          \
                const seg_type* segment = to_func(seg);
Referenced by GetTimingTags().
Function Documentation
emplace_back_tag()
static void emplace_back_tag (vector< RString > & lines, RString const & format, RString const & value) static
References SmEscape(), and ssprintf().
Referenced by GetSSCNoteData().
GetSSCNoteData()
static RString GetSSCNoteData (const Song & song, const Steps & in, bool bSavingCache) static
Retrieve the individual batches of NoteData.
Parameters
song the Song in question.
in the Steps in question.
bSavingCache a flag to see if we're saving certain cache data.
Returns
the NoteData in RString form.
References Steps::Compress(), Steps::Decompress(), DifficultyToString(), DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, emplace_back_tag(), TimingData::empty(), FOREACH_ENUM, Steps::GetAllMSD(), Steps::GetChartKey(), Steps::GetChartName(), Steps::GetChartStyle(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetDisplayBPM(), Steps::GetFilename(), Steps::GetMaxBPM(), Steps::GetMeter(), Steps::GetMinBPM(), Steps::GetMusicFile(), Steps::GetRadarValues(), Steps::GetSMNoteData(), GetTimingTags(), Rage::join(), JoinLineList(), TimingData::m_fBeat0OffsetInSeconds, Steps::m_StepsTypeStr, Steps::m_Timing, Song::m_vsKeysoundFile, NotesWriterSSC::MSDToString(), SmEscape(), split(), ssprintf(), and TrimLeft().
Referenced by NotesWriterSSC::GetEditFileContents(), and NotesWriterSSC::Write().
GetTimingTags()
static void GetTimingTags (vector< RString > & lines, const TimingData & timing, bool bIsSong = false) static
References SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_DELAY, SEGMENT_FAKE, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_STOP, SEGMENT_TICKCOUNT, SEGMENT_TIME_SIG, SEGMENT_WARP, TimingTagWriter::Write(), WRITE_SEG_LOOP_CLOSE, and WRITE_SEG_LOOP_OPEN.
Referenced by GetSSCNoteData().
JoinLineList()
static RString JoinLineList (vector< RString > & lines) static
Turn a vector of lines into a single line joined by newline characters.
Parameters
lines the list of lines to join.
Returns
the joined lines.
References Rage::join(), and TrimRight().
Referenced by GetSSCNoteData().
write_tag()
static void write_tag (RageFile & f, RString const & format, std::string const & value) static
References RageFile::PutLine(), SmEscape(), and ssprintf().
Referenced by WriteGlobalTags(), and WriteTimingTags().
WriteGlobalTags()
static void WriteGlobalTags (RageFile & f, const Song & out) static
Write out the common tags for .SSC files.
Parameters
f the file in question.
out the Song in question.
References ASSERT_M, DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, FOREACH_BackgroundLayer, Song::GetBackgroundChanges(), Song::GetForegroundChanges(), Song::GetInstrumentTracksToVectorString(), Song::GetSpecifiedLastSecond(), Rage::join(), Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_PreviewFile, Song::m_sArtist, Song::m_sArtistTranslit, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_sDiscFile, Song::m_SelectionDisplay, Song::m_sGenre, Song::m_sJacketFile, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sOrigin, Song::m_sPreviewVidFile, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Song::m_vsKeysoundFile, RageFile::PutLine(), Song::SHOW_ALWAYS, Song::SHOW_NEVER, ssprintf(), STEPFILE_VERSION_NUMBER, RageFile::Write(), write_tag(), and WriteTimingTags().
Referenced by NotesWriterSSC::Write().
WriteTimingTags()
static void WriteTimingTags (RageFile & f, const TimingData & timing, bool bIsSong = false) static
References Rage::join(), SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_DELAY, SEGMENT_FAKE, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_STOP, SEGMENT_TICKCOUNT, SEGMENT_TIME_SIG, SEGMENT_WARP, TimingData::ToVectorString(), and write_tag().
Referenced by WriteGlobalTags().
Variable Documentation
DESTINATION_ALREADY_EXISTS
LocalizedString DESTINATION_ALREADY_EXISTS("NotesWriterSSC", "Error renaming file. Destination file '%s' already exists.") static
ERROR_WRITING_FILE
LocalizedString ERROR_WRITING_FILE("NotesWriterSSC", "Error writing file '%s'.") static