Etterna: XNodeLuaValue Class Reference
XNodeLuaValue Class Reference
Public Member Functions
XNodeValue * Copy () const override
template<typename T >
T GetValue () const
void GetValue (RString &out) const override
void GetValue (int &out) const override
void GetValue (float &out) const override
void GetValue (bool &out) const override
void GetValue (unsigned &out) const override
void PushValue (lua_State *L) const override
void SetValue (const RString &v) override
void SetValue (int v) override
void SetValue (float v) override
void SetValue (unsigned v) override
void SetValueFromStack (lua_State *L) override
Public Member Functions inherited from XNodeValue
virtual ~XNodeValue ()=default
template<typename T >
T GetValue () const
Public Attributes
LuaReference m_Value
Member Function Documentation
Copy()
XNodeValue* XNodeLuaValue::Copy () const inline override virtual
Implements XNodeValue.
GetValue() [1/6]
template<typename T > T XNodeLuaValue::GetValue () const inline
References T.
GetValue() [2/6]
void XNodeLuaValue::GetValue (RString & out) const override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Pop(), PushValue(), and LuaManager::Release().
GetValue() [3/6]
void XNodeLuaValue::GetValue (int & out) const override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Pop(), PushValue(), and LuaManager::Release().
GetValue() [4/6]
void XNodeLuaValue::GetValue (float & out) const override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Pop(), PushValue(), and LuaManager::Release().
GetValue() [5/6]
void XNodeLuaValue::GetValue (bool & out) const override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Pop(), PushValue(), and LuaManager::Release().
GetValue() [6/6]
void XNodeLuaValue::GetValue (unsigned & out) const override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Pop(), PushValue(), and LuaManager::Release().
PushValue()
void XNodeLuaValue::PushValue (lua_State * L) const override virtual
Implements XNodeValue.
References m_Value, and LuaReference::PushSelf().
Referenced by GetValue().
SetValue() [1/4]
void XNodeLuaValue::SetValue (const RString & v) override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetValueFromStack().
SetValue() [2/4]
void XNodeLuaValue::SetValue (int v) override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetValueFromStack().
SetValue() [3/4]
void XNodeLuaValue::SetValue (float v) override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetValueFromStack().
SetValue() [4/4]
void XNodeLuaValue::SetValue (unsigned v) override virtual
Implements XNodeValue.
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetValueFromStack().
SetValueFromStack()
void XNodeLuaValue::SetValueFromStack (lua_State * L) override virtual
Implements XNodeValue.
References m_Value, and LuaReference::SetFromStack().
Referenced by SetValue().
Member Data Documentation
m_Value
LuaReference XNodeLuaValue::m_Value
Referenced by PushValue(), and SetValueFromStack().
The documentation for this class was generated from the following file:
XmlFileUtil.cpp