Etterna: RageUnicode.cpp File Reference
RageUnicode.cpp File Reference
#include "global.h"
#include "RageUnicode.h"
#include <vector>
Namespaces
Rage
Functions
std::wstring convert_unicode_casing (std::wstring const &s, unsigned char const mapping[256])
void utf8_sanitize (std::string &s)
Sanitize the UTF-8 string.
Variables
unsigned char Rage::upperCase [256]
A mapping to allow for quick uppercase conversion.
unsigned char Rage::lowerCase [256]
A mapping to allow for quick lowercase conversion.
Function Documentation
convert_unicode_casing()
std::wstring convert_unicode_casing (std::wstring const & s, unsigned char const mapping[256])
Referenced by Rage::make_lower(), and Rage::make_upper().
utf8_sanitize()
void utf8_sanitize (std::string & s)
Sanitize the UTF-8 string.
References picosha2::detail::ch(), Rage::invalid_char, Rage::utf8_to_wchar_ec(), and Rage::wchar_to_utf8().