Etterna: LunaCryptManager Class Reference
LunaCryptManager Class Reference
Allow Lua to have access to the CryptManager.
Public Member Functions
LunaCryptManager ()
Public Member Functions inherited from Luna< CryptManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int MD5String (T *p, lua_State *L)
static int MD5File (T *p, lua_State *L)
static int SHA1String (T *p, lua_State *L)
static int SHA1File (T *p, lua_State *L)
static int GenerateRandomUUID (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< CryptManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< CryptManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< CryptManager >
using T = CryptManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< CryptManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the CryptManager.
Constructor & Destructor Documentation
LunaCryptManager()
LunaCryptManager::LunaCryptManager () inline
References ADD_METHOD, GenerateRandomUUID(), MD5File(), MD5String(), SHA1File(), and SHA1String().
Member Function Documentation
GenerateRandomUUID()
static int LunaCryptManager::GenerateRandomUUID (T * p, lua_State * L) inline static
References CryptManager::GenerateRandomUUID().
Referenced by LunaCryptManager().
MD5File()
static int LunaCryptManager::MD5File (T * p, lua_State * L) inline static
References CryptManager::GetMD5ForFile(), and SArg.
Referenced by LunaCryptManager().
MD5String()
static int LunaCryptManager::MD5String (T * p, lua_State * L) inline static
References CryptManager::GetMD5ForString(), and SArg.
Referenced by LunaCryptManager().
SHA1File()
static int LunaCryptManager::SHA1File (T * p, lua_State * L) inline static
References CryptManager::GetSHA1ForFile(), and SArg.
Referenced by LunaCryptManager().
SHA1String()
static int LunaCryptManager::SHA1String (T * p, lua_State * L) inline static
References CryptManager::GetSHA1ForString(), and SArg.
Referenced by LunaCryptManager().
The documentation for this class was generated from the following file:
CryptManager.cpp