Etterna: picosha2::impl Namespace Reference
picosha2::impl Namespace Reference
Functions
template<typename RaIter , typename OutIter >
void hash256_impl (RaIter first, RaIter last, OutIter first2, OutIter last2, int, std::random_access_iterator_tag)
template<typename InputIter , typename OutIter >
void hash256_impl (InputIter first, InputIter last, OutIter first2, OutIter last2, int buffer_size, std::input_iterator_tag)
Function Documentation
hash256_impl() [1/2]
template<typename RaIter , typename OutIter > void picosha2::impl::hash256_impl (RaIter first, RaIter last, OutIter first2, OutIter last2, int , std::random_access_iterator_tag)
References picosha2::hash256_one_by_one::finish(), picosha2::hash256_one_by_one::get_hash_bytes(), and picosha2::hash256_one_by_one::process().
Referenced by picosha2::hash256().
hash256_impl() [2/2]
template<typename InputIter , typename OutIter > void picosha2::impl::hash256_impl (InputIter first, InputIter last, OutIter first2, OutIter last2, int buffer_size, std::input_iterator_tag)
References picosha2::hash256_one_by_one::finish(), picosha2::hash256_one_by_one::get_hash_bytes(), and picosha2::hash256_one_by_one::process().