Etterna: NotesWriterSSC Namespace Reference
NotesWriterSSC Namespace Reference
Writes a Song to an .SSC file.
Functions
bool Write (RString &sPath, const Song &out, const vector< Steps *> &vpStepsToSave, bool bSavingCache)
Write the song out to a file.
void GetEditFileContents (const Song *pSong, const Steps *pSteps, RString &sOut)
Get some contents about the edit file first.
RString GetEditFileName (const Song *pSong, const Steps *pSteps)
Get the name of the edit file to use.
bool WriteEditFileToMachine (const Song *pSong, Steps *pSteps, RString &sErrorOut)
Write the edit file to the machine for future use.
RString MSDToString (MinaSD x)
RString MSDsAtRateToString (SDiffs x)
Detailed Description
Writes a Song to an .SSC file.
Function Documentation
GetEditFileContents()
void NotesWriterSSC::GetEditFileContents (const Song * pSong, const Steps * pSteps, RString & sOut)
Get some contents about the edit file first.
Parameters
pSong the Song in question.
pSteps the Steps in question.
sOut the start of the file contents.
References Song::GetSongDir(), GetSSCNoteData(), Rage::join(), split(), and ssprintf().
GetEditFileName()
RString NotesWriterSSC::GetEditFileName (const Song * pSong, const Steps * pSteps)
Get the name of the edit file to use.
Parameters
pSong the Song in question.
pSteps the Steps in question.
Returns
the name of the edit file.
References Steps::GetDescription(), Song::GetTranslitFullTitle(), Steps::m_StepsType, MakeValidFilename(), and StepsType_dance_double.
MSDsAtRateToString()
RString NotesWriterSSC::MSDsAtRateToString (SDiffs x)
Referenced by MSDToString().
MSDToString()
RString NotesWriterSSC::MSDToString (MinaSD x)
References MSDsAtRateToString().
Referenced by GetSSCNoteData(), and SongCacheIndex::InsertSteps().
Write()
bool NotesWriterSSC::Write (RString & sPath, const Song & out, const vector< Steps *> & vpStepsToSave, bool bSavingCache)
Write the song out to a file.
Parameters
sPath the path to write the file.
out the Song to be written out.
vpStepsToSave the Steps to save.
bSavingCache a flag to see if we're saving certain cache data.
Returns
its success or failure.
References f, RageFile::Flush(), FOREACH_CONST, Steps::GetChartKey(), RageFile::GetError(), Song::GetFirstSecond(), Song::GetLastSecond(), GetSSCNoteData(), RageLog::Info(), LOG, Song::m_bHasBanner, Song::m_bHasMusic, Song::m_fMusicLengthSeconds, Song::m_sSongFileName, RageFile::Open(), RageFile::PutLine(), RageFile::SLOW_FLUSH, ssprintf(), RageLog::UserLog(), RageFile::WRITE, and WriteGlobalTags().
Referenced by Song::SaveToSSCFile().
WriteEditFileToMachine()
bool NotesWriterSSC::WriteEditFileToMachine (const Song * pSong, Steps * pSteps, RString & sErrorOut)
Write the edit file to the machine for future use.
Parameters
pSong the Song in question.
pSteps the Steps in question.
sErrorOut any error messages that may have occurred.
Returns
its success or failure.