Etterna: LinuxInputManager Class Reference
LinuxInputManager Class Reference
#include <LinuxInputManager.h>
Public Member Functions
LinuxInputManager ()
void InitDriver (InputHandler_Linux_Joystick *drv)
void InitDriver (InputHandler_Linux_Event *drv)
~LinuxInputManager ()
Private Attributes
bool m_bEventEnabled
InputHandler_Linux_Event * m_EventDriver
vector< RString > m_vsPendingEventDevices
bool m_bJoystickEnabled
InputHandler_Linux_Joystick * m_JoystickDriver
vector< RString > m_vsPendingJoystickDevices
Constructor & Destructor Documentation
LinuxInputManager()
LinuxInputManager::LinuxInputManager ()
References g_sInputDrivers, getDevice(), RageLog::Info(), LOG, m_bEventEnabled, m_bJoystickEnabled, m_EventDriver, m_JoystickDriver, m_vsPendingEventDevices, m_vsPendingJoystickDevices, and RageLog::Warn().
~LinuxInputManager()
LinuxInputManager::~LinuxInputManager ()
Member Function Documentation
InitDriver() [1/2]
void LinuxInputManager::InitDriver (InputHandler_Linux_Joystick * drv)
References ASSERT, FOREACH, getDevice(), m_JoystickDriver, m_vsPendingJoystickDevices, and InputHandler_Linux_Joystick::TryDevice().
Referenced by InitDriver(), InputHandler_Linux_Event::InputHandler_Linux_Event(), and InputHandler_Linux_Joystick::InputHandler_Linux_Joystick().
InitDriver() [2/2]
void LinuxInputManager::InitDriver (InputHandler_Linux_Event * drv)
References ASSERT, FOREACH, getDevice(), InitDriver(), m_bJoystickEnabled, m_EventDriver, m_JoystickDriver, m_vsPendingEventDevices, m_vsPendingJoystickDevices, and InputHandler_Linux_Event::TryDevice().
Member Data Documentation
m_bEventEnabled
bool LinuxInputManager::m_bEventEnabled private
Referenced by LinuxInputManager().
m_bJoystickEnabled
bool LinuxInputManager::m_bJoystickEnabled private
Referenced by InitDriver(), and LinuxInputManager().
m_EventDriver
InputHandler_Linux_Event* LinuxInputManager::m_EventDriver private
Referenced by InitDriver(), and LinuxInputManager().
m_JoystickDriver
InputHandler_Linux_Joystick* LinuxInputManager::m_JoystickDriver private
Referenced by InitDriver(), and LinuxInputManager().
m_vsPendingEventDevices
vector<RString> LinuxInputManager::m_vsPendingEventDevices private
Referenced by InitDriver(), and LinuxInputManager().
m_vsPendingJoystickDevices
vector<RString> LinuxInputManager::m_vsPendingJoystickDevices private
Referenced by InitDriver(), and LinuxInputManager().
The documentation for this class was generated from the following files:
LinuxInputManager.h
LinuxInputManager.cpp