Etterna: AdjustSync.cpp File Reference
AdjustSync.cpp File Reference
#include "AdjustSync.h"
#include "Foreach.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "PrefsManager.h"
#include "ScreenManager.h"
#include "Song.h"
#include "SongManager.h"
#include "Steps.h"
#include "global.h"
Macros
#define SEGMENTS_MISMATCH_MESSAGE(orig, test, segments_name)
Variables
static LocalizedString AUTOSYNC_CORRECTION_APPLIED ("AdjustSync", "Autosync: Correction applied.")
static LocalizedString AUTOSYNC_CORRECTION_NOT_APPLIED ("AdjustSync", "Autosync: Correction NOT applied. Deviation too high.")
static LocalizedString EARLIER ("AdjustSync", "earlier")
static LocalizedString LATER ("AdjustSync", "later")
static LocalizedString GLOBAL_OFFSET_FROM ("AdjustSync", "Global Offset from %+.3f to %+.3f (notes %s)")
static LocalizedString SONG_OFFSET_FROM ("AdjustSync", "Song offset from %+.3f to %+.3f (notes %s)")
static LocalizedString TEMPO_SEGMENT_FROM ("AdjustSync", "%s BPM from %.3f BPM to %.3f BPM.")
static LocalizedString CHANGED_STOP ("AdjustSync", "The stop segment #%d changed from %+.3fs to %+.3fs (change of %+.3f).")
static LocalizedString ERROR ("AdjustSync", "Average Error %.5fs")
static LocalizedString ETC ("AdjustSync", "Etc.")
static LocalizedString TAPS_IGNORED ("AdjustSync", "%d taps ignored.")
Macro Definition Documentation
SEGMENTS_MISMATCH_MESSAGE
#define SEGMENTS_MISMATCH_MESSAGE (orig, test, segments_name)
Value:
if ((orig).size() != (test).size()) {                                      \
        LuaHelpers::ReportScriptError("The sync overlay's " #segments_name     \
                                      " segment list is a different size "     \
                                      "from the song's.  Please report this "  \
                                      "bug with steps to reproduce it.");      \
    }
Referenced by AdjustSync::GetSyncChangeTextSong().
Variable Documentation
AUTOSYNC_CORRECTION_APPLIED
LocalizedString AUTOSYNC_CORRECTION_APPLIED("AdjustSync", "Autosync: Correction applied.") static
Referenced by AdjustSync::AutosyncOffset(), and AdjustSync::AutosyncTempo().
AUTOSYNC_CORRECTION_NOT_APPLIED
LocalizedString AUTOSYNC_CORRECTION_NOT_APPLIED("AdjustSync", "Autosync: Correction NOT applied. Deviation too high.") static
Referenced by AdjustSync::AutosyncOffset(), and AdjustSync::AutosyncTempo().
CHANGED_STOP
LocalizedString CHANGED_STOP("AdjustSync", "The stop segment #%d changed from %+.3fs to %+.3fs (change of %+.3f).") static
Referenced by AdjustSync::GetSyncChangeTextSong().
EARLIER
LocalizedString EARLIER("AdjustSync", "earlier") static
Referenced by AdjustSync::GetSyncChangeTextGlobal(), and AdjustSync::GetSyncChangeTextSong().
ERROR
LocalizedString ERROR("AdjustSync", "Average Error %.5fs") static
Referenced by AdjustSync::GetSyncChangeTextSong().
ETC
LocalizedString ETC("AdjustSync", "Etc.") static
Referenced by AdjustSync::GetSyncChangeTextSong().
GLOBAL_OFFSET_FROM
LocalizedString GLOBAL_OFFSET_FROM("AdjustSync", "Global Offset from %+.3f to %+.3f (notes %s)") static
Referenced by AdjustSync::GetSyncChangeTextGlobal().
LATER
LocalizedString LATER("AdjustSync", "later") static
Referenced by AdjustSync::GetSyncChangeTextGlobal(), and AdjustSync::GetSyncChangeTextSong().
SONG_OFFSET_FROM
LocalizedString SONG_OFFSET_FROM("AdjustSync", "Song offset from %+.3f to %+.3f (notes %s)") static
Referenced by AdjustSync::GetSyncChangeTextSong().
TAPS_IGNORED
LocalizedString TAPS_IGNORED("AdjustSync", "%d taps ignored.") static
Referenced by AdjustSync::GetSyncChangeTextSong().
TEMPO_SEGMENT_FROM
LocalizedString TEMPO_SEGMENT_FROM("AdjustSync", "%s BPM from %.3f BPM to %.3f BPM.") static
Referenced by AdjustSync::GetSyncChangeTextSong().