Etterna: LunaScreenManager Class Reference
LunaScreenManager Class Reference
Allow Lua to have access to the ScreenManager.
Public Member Functions
SCRMAN_PLAY_SOUND (InvalidSound)
SCRMAN_PLAY_SOUND (StartSound)
SCRMAN_PLAY_SOUND (CoinSound)
SCRMAN_PLAY_SOUND (CancelSound)
SCRMAN_PLAY_SOUND (ScreenshotSound)
LunaScreenManager ()
Public Member Functions inherited from Luna< ScreenManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static void ValidateScreenName (lua_State *L, RString &name)
static int SetNewScreen (T *p, lua_State *L)
static int GetTopScreen (T *p, lua_State *L)
static int SystemMessage (T *p, lua_State *L)
static int ScreenIsPrepped (T *p, lua_State *L)
static int ScreenClassExists (T *p, lua_State *L)
static int AddNewScreenToTop (T *p, lua_State *L)
static int ReloadOverlayScreens (T *p, lua_State *L)
static int get_input_redirected (T *p, lua_State *L)
static int set_input_redirected (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScreenManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScreenManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenManager >
using T = ScreenManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ScreenManager.
Constructor & Destructor Documentation
LunaScreenManager()
LunaScreenManager::LunaScreenManager () inline
References ADD_GET_SET_METHODS, ADD_METHOD, and ScreenManagerUtil::ScreenIsPrepped().
Member Function Documentation
AddNewScreenToTop()
static int LunaScreenManager::AddNewScreenToTop (T * p, lua_State * L) inline static
References ScreenManager::AddNewScreenToTop(), COMMON_RETURN_SELF, SArg, SM_None, and ScreenMessageHelpers::ToScreenMessage().
get_input_redirected()
static int LunaScreenManager::get_input_redirected (T * p, lua_State * L) inline static
References ScreenManager::get_input_redirected(), and L.
GetTopScreen()
static int LunaScreenManager::GetTopScreen (T * p, lua_State * L) inline static
References ScreenManager::GetTopScreen(), and Actor::PushSelf().
ReloadOverlayScreens()
static int LunaScreenManager::ReloadOverlayScreens (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ScreenManager::ReloadOverlayScreens().
ScreenClassExists()
static int LunaScreenManager::ScreenClassExists (T * p, lua_State * L) inline static
References g_pmapRegistrees, and SArg.
ScreenIsPrepped()
static int LunaScreenManager::ScreenIsPrepped (T * p, lua_State * L) inline static
References SArg, and ScreenManagerUtil::ScreenIsPrepped().
SCRMAN_PLAY_SOUND() [1/5]
LunaScreenManager::SCRMAN_PLAY_SOUND (InvalidSound)
SCRMAN_PLAY_SOUND() [2/5]
LunaScreenManager::SCRMAN_PLAY_SOUND (StartSound)
SCRMAN_PLAY_SOUND() [3/5]
LunaScreenManager::SCRMAN_PLAY_SOUND (CoinSound)
SCRMAN_PLAY_SOUND() [4/5]
LunaScreenManager::SCRMAN_PLAY_SOUND (CancelSound)
SCRMAN_PLAY_SOUND() [5/5]
LunaScreenManager::SCRMAN_PLAY_SOUND (ScreenshotSound)
set_input_redirected()
static int LunaScreenManager::set_input_redirected (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, L, and ScreenManager::set_input_redirected().
SetNewScreen()
static int LunaScreenManager::SetNewScreen (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and ScreenManager::SetNewScreen().
SystemMessage()
static int LunaScreenManager::SystemMessage (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and ScreenManager::SystemMessage().
ValidateScreenName()
static void LunaScreenManager::ValidateScreenName (lua_State * L, RString & name) inline static
References g_pmapRegistrees, ThemeManager::GetMetric(), ScreenManager::SystemMessage(), and THEME.
The documentation for this class was generated from the following file:
ScreenManager.cpp