Etterna: LifeMeterTime.cpp File Reference
LifeMeterTime.cpp File Reference
#include "global.h"
#include "LifeMeterTime.h"
#include "GameState.h"
#include "MessageManager.h"
#include "PlayerState.h"
#include "Preference.h"
#include "Song.h"
#include "StatsManager.h"
#include "Steps.h"
#include "StreamDisplay.h"
#include "ThemeManager.h"
Functions
COMPILE_ASSERT (ARRAYLEN(g_fTimeMeterSecondsChangeInit)==NUM_ScoreEvent)
static void TimeMeterSecondsChangeInit (size_t i, RString &sNameOut, float &defaultValueOut)
Variables
const float FULL_LIFE_SECONDS = 1.5f * 60
static ThemeMetric< float > METER_WIDTH ("LifeMeterTime", "MeterWidth")
static ThemeMetric< float > METER_HEIGHT ("LifeMeterTime", "MeterHeight")
static ThemeMetric< float > DANGER_THRESHOLD ("LifeMeterTime", "DangerThreshold")
static ThemeMetric< float > INITIAL_VALUE ("LifeMeterTime", "InitialValue")
static ThemeMetric< float > MIN_LIFE_TIME ("LifeMeterTime", "MinLifeTime")
static const float g_fTimeMeterSecondsChangeInit []
static Preference1D< float > g_fTimeMeterSecondsChange (TimeMeterSecondsChangeInit, NUM_ScoreEvent)
Function Documentation
COMPILE_ASSERT()
COMPILE_ASSERT (ARRAYLEN(g_fTimeMeterSecondsChangeInit) = =NUM_ScoreEvent)
TimeMeterSecondsChangeInit()
static void TimeMeterSecondsChangeInit (size_t i, RString & sNameOut, float & defaultValueOut) static
References g_fTimeMeterSecondsChangeInit, and ScoreEventToString().
Variable Documentation
DANGER_THRESHOLD
ThemeMetric<float> DANGER_THRESHOLD("LifeMeterTime", "DangerThreshold") static
Referenced by LifeMeterTime::IsInDanger().
FULL_LIFE_SECONDS
const float FULL_LIFE_SECONDS = 1.5f * 60
Referenced by LifeMeterTime::GetLife().
g_fTimeMeterSecondsChange
Preference1D<float> g_fTimeMeterSecondsChange(TimeMeterSecondsChangeInit, NUM_ScoreEvent) static
Referenced by LifeMeterTime::ChangeLife(), and LifeMeterTime::OnLoadSong().
g_fTimeMeterSecondsChangeInit
const float g_fTimeMeterSecondsChangeInit[] static
Initial value:
= {
    +0.0f,
    +0.2f,
    +0.0f,
    -0.5f,
    -1.0f,
    -2.0f,
    -4.0f,
    -2.0f,
    -0.0f,
    -0.0f,
    -4.0f,
    -0.0f,
}
Referenced by TimeMeterSecondsChangeInit().
INITIAL_VALUE
ThemeMetric<float> INITIAL_VALUE("LifeMeterTime", "InitialValue") static
Referenced by LifeMeterTime::OnLoadSong().
METER_HEIGHT
ThemeMetric<float> METER_HEIGHT("LifeMeterTime", "MeterHeight") static
Referenced by LifeMeterTime::Load().
METER_WIDTH
ThemeMetric<float> METER_WIDTH("LifeMeterTime", "MeterWidth") static
Referenced by LifeMeterTime::Load().
MIN_LIFE_TIME
ThemeMetric<float> MIN_LIFE_TIME("LifeMeterTime", "MinLifeTime") static
Referenced by LifeMeterTime::OnLoadSong().