Etterna: CommandLineActions Namespace Reference
CommandLineActions Namespace Reference
The collection of command line actions.
Classes
class CommandLineArgs
The housing for the command line arguments.
Functions
void Handle (LoadingWindow *pLW)
Perform a utility function, then exit.
Variables
vector< CommandLineArgs > ToProcess
A list of command line arguemnts to process while the game is running. These args could have come from this process or passed to this process from another process.
Detailed Description
The collection of command line actions.
Function Documentation
Handle()
void CommandLineActions::Handle (LoadingWindow * pLW)
Perform a utility function, then exit.
Parameters
pLW the LoadingWindow that is presently not used?
References CommandLineActions::CommandLineArgs::argv, g_argc, g_argv, GetCommandlineArgument(), LuaInformation(), Nsis(), ToProcess, and Version().
Referenced by sm_main().
Variable Documentation
ToProcess
vector< CommandLineActions::CommandLineArgs > CommandLineActions::ToProcess
A list of command line arguemnts to process while the game is running. These args could have come from this process or passed to this process from another process.
Referenced by Handle(), and ScreenInstallOverlay::Update().