Etterna: RandomSample Class Reference
RandomSample Class Reference
#include <RandomSample.h>
Public Member Functions
RandomSample ()
virtual ~RandomSample ()
bool Load (const RString &sFilePath, int iMaxToLoad=1000)
void UnloadAll ()
void PlayRandom ()
void PlayCopyOfRandom ()
void Stop ()
Private Member Functions
bool LoadSoundDir (RString sDir, int iMaxToLoad)
bool LoadSound (const RString &sSoundFilePath)
int GetNextToPlay ()
Private Attributes
vector< RageSound * > m_pSamples
int m_iIndexLastPlayed
Constructor & Destructor Documentation
RandomSample()
RandomSample::RandomSample ()
References m_iIndexLastPlayed.
~RandomSample()
RandomSample::~RandomSample () virtual
References UnloadAll().
Member Function Documentation
GetNextToPlay()
int RandomSample::GetNextToPlay () private
References m_iIndexLastPlayed, m_pSamples, and RandomInt().
Referenced by PlayCopyOfRandom(), and PlayRandom().
Load()
bool RandomSample::Load (const RString & sFilePath, int iMaxToLoad = 1000)
References GetExtension(), LoadSound(), and LoadSoundDir().
Referenced by ScreenSelectMaster::Init().
LoadSound()
bool RandomSample::LoadSound (const RString & sSoundFilePath) private
References LOG, m_pSamples, and RageLog::Trace().
Referenced by Load(), and LoadSoundDir().
LoadSoundDir()
bool RandomSample::LoadSoundDir (RString sDir, int iMaxToLoad) private
References g_RandomNumberGenerator, GetDirListing(), LoadSound(), min(), StdString::CStdStr< CT >::Right(), and NoteDataUtil::shuffle.
Referenced by Load().
PlayCopyOfRandom()
void RandomSample::PlayCopyOfRandom ()
References GetNextToPlay(), and m_pSamples.
PlayRandom()
void RandomSample::PlayRandom ()
References GetNextToPlay(), and m_pSamples.
Referenced by ScreenSelectMaster::ChangePage().
Stop()
void RandomSample::Stop ()
References m_iIndexLastPlayed, and m_pSamples.
Referenced by ScreenSelectMaster::ChangePage().
UnloadAll()
void RandomSample::UnloadAll ()
References m_pSamples.
Referenced by ~RandomSample().
Member Data Documentation
m_iIndexLastPlayed
int RandomSample::m_iIndexLastPlayed private
Referenced by GetNextToPlay(), RandomSample(), and Stop().
m_pSamples
vector<RageSound*> RandomSample::m_pSamples private
Referenced by GetNextToPlay(), LoadSound(), PlayCopyOfRandom(), PlayRandom(), Stop(), and UnloadAll().
The documentation for this class was generated from the following files:
RandomSample.h
RandomSample.cpp