Etterna: ArrowEffects.cpp File Reference
ArrowEffects.cpp File Reference
#include "global.h"
#include "ArrowEffects.h"
#include "GameConstantsAndTypes.h"
#include "GameState.h"
#include "NoteDisplay.h"
#include "PlayerState.h"
#include "RageMath.h"
#include "RageTimer.h"
#include "ScreenDimensions.h"
#include "Song.h"
#include "Steps.h"
#include "Style.h"
#include "ThemeMetric.h"
#include "LuaBinding.h"
Macros
#define CENTER_LINE_Y 160
#define FADE_DIST_Y 40
Functions
float ArrowGetPercentVisible (float fYPosWithoutReverse)
static float GetNoteFieldHeight ()
static float GetDisplayedBeat (const PlayerState *pPlayerState, float beat)
static void ArrowGetReverseShiftAndScale (int iCol, float fYReverseOffsetPixels, float &fShiftOut, float &fScaleOut)
static float GetCenterLine ()
static float GetHiddenSudden ()
static float GetHiddenEndLine ()
static float GetHiddenStartLine ()
static float GetSuddenEndLine ()
static float GetSuddenStartLine ()
Variables
static ThemeMetric< float > ARROW_SPACING ("ArrowEffects", "ArrowSpacing")
static ThemeMetric< bool > QUANTIZE_ARROW_Y ("ArrowEffects", "QuantizeArrowYPosition")
static ThemeMetric< bool > HIDDEN_SUDDEN_PAST_RECEPTOR ("ArrowEffects", "DrawHiddenNotesAfterReceptor")
static ThemeMetric< float > BLINK_MOD_FREQUENCY ("ArrowEffects", "BlinkModFrequency")
static ThemeMetric< float > BOOST_MOD_MIN_CLAMP ("ArrowEffects", "BoostModMinClamp")
static ThemeMetric< float > BOOST_MOD_MAX_CLAMP ("ArrowEffects", "BoostModMaxClamp")
static ThemeMetric< float > BRAKE_MOD_MIN_CLAMP ("ArrowEffects", "BrakeModMinClamp")
static ThemeMetric< float > BRAKE_MOD_MAX_CLAMP ("ArrowEffects", "BrakeModMaxClamp")
static ThemeMetric< float > WAVE_MOD_MAGNITUDE ("ArrowEffects", "WaveModMagnitude")
static ThemeMetric< float > WAVE_MOD_HEIGHT ("ArrowEffects", "WaveModHeight")
static ThemeMetric< float > BOOMERANG_PEAK_PERCENTAGE ("ArrowEffects", "BoomerangPeakPercentage")
static ThemeMetric< float > EXPAND_MULTIPLIER_FREQUENCY ("ArrowEffects", "ExpandMultiplierFrequency")
static ThemeMetric< float > EXPAND_MULTIPLIER_SCALE_FROM_LOW ("ArrowEffects", "ExpandMultiplierScaleFromLow")
static ThemeMetric< float > EXPAND_MULTIPLIER_SCALE_FROM_HIGH ("ArrowEffects", "ExpandMultiplierScaleFromHigh")
static ThemeMetric< float > EXPAND_MULTIPLIER_SCALE_TO_LOW ("ArrowEffects", "ExpandMultiplierScaleToLow")
static ThemeMetric< float > EXPAND_MULTIPLIER_SCALE_TO_HIGH ("ArrowEffects", "ExpandMultiplierScaleToHigh")
static ThemeMetric< float > EXPAND_SPEED_SCALE_FROM_LOW ("ArrowEffects", "ExpandSpeedScaleFromLow")
static ThemeMetric< float > EXPAND_SPEED_SCALE_FROM_HIGH ("ArrowEffects", "ExpandSpeedScaleFromHigh")
static ThemeMetric< float > EXPAND_SPEED_SCALE_TO_LOW ("ArrowEffects", "ExpandSpeedScaleToLow")
static ThemeMetric< float > TIPSY_TIMER_FREQUENCY ("ArrowEffects", "TipsyTimerFrequency")
static ThemeMetric< float > TIPSY_COLUMN_FREQUENCY ("ArrowEffects", "TipsyColumnFrequency")
static ThemeMetric< float > TIPSY_ARROW_MAGNITUDE ("ArrowEffects", "TipsyArrowMagnitude")
static ThemeMetric< float > TIPSY_OFFSET_TIMER_FREQUENCY ("ArrowEffects", "TipsyOffsetTimerFrequency")
static ThemeMetric< float > TIPSY_OFFSET_COLUMN_FREQUENCY ("ArrowEffects", "TipsyOffsetColumnFrequency")
static ThemeMetric< float > TIPSY_OFFSET_ARROW_MAGNITUDE ("ArrowEffects", "TipsyOffsetArrowMagnitude")
static ThemeMetric< float > TORNADO_POSITION_SCALE_TO_LOW ("ArrowEffects", "TornadoPositionScaleToLow")
static ThemeMetric< float > TORNADO_POSITION_SCALE_TO_HIGH ("ArrowEffects", "TornadoPositionScaleToHigh")
static ThemeMetric< float > TORNADO_OFFSET_FREQUENCY ("ArrowEffects", "TornadoOffsetFrequency")
static ThemeMetric< float > TORNADO_OFFSET_SCALE_FROM_LOW ("ArrowEffects", "TornadoOffsetScaleFromLow")
static ThemeMetric< float > TORNADO_OFFSET_SCALE_FROM_HIGH ("ArrowEffects", "TornadoOffsetScaleFromHigh")
static ThemeMetric< float > DRUNK_COLUMN_FREQUENCY ("ArrowEffects", "DrunkColumnFrequency")
static ThemeMetric< float > DRUNK_OFFSET_FREQUENCY ("ArrowEffects", "DrunkOffsetFrequency")
static ThemeMetric< float > DRUNK_ARROW_MAGNITUDE ("ArrowEffects", "DrunkArrowMagnitude")
static ThemeMetric< float > BEAT_OFFSET_HEIGHT ("ArrowEffects", "BeatOffsetHeight")
static ThemeMetric< float > BEAT_PI_HEIGHT ("ArrowEffects", "BeatPIHeight")
static ThemeMetric< float > TINY_PERCENT_BASE ("ArrowEffects", "TinyPercentBase")
static ThemeMetric< float > TINY_PERCENT_GATE ("ArrowEffects", "TinyPercentGate")
static ThemeMetric< bool > DIZZY_HOLD_HEADS ("ArrowEffects", "DizzyHoldHeads")
static const PlayerOptions * curr_options = nullptr
static ThemeMetric< float > FRAME_WIDTH_EFFECTS_PIXELS_PER_SECOND ("ArrowEffects", "FrameWidthEffectsPixelsPerSecond")
static ThemeMetric< float > FRAME_WIDTH_EFFECTS_MIN_MULTIPLIER ("ArrowEffects", "FrameWidthEffectsMinMultiplier")
static ThemeMetric< float > FRAME_WIDTH_EFFECTS_MAX_MULTIPLIER ("ArrowEffects", "FrameWidthEffectsMaxMultiplier")
static ThemeMetric< bool > FRAME_WIDTH_LOCK_EFFECTS_TO_OVERLAPPING ("ArrowEffects", "FrameWidthLockEffectsToOverlapping")
static ThemeMetric< float > FRAME_WIDTH_LOCK_EFFECTS_TWEEN_PIXELS ("ArrowEffects", "FrameWidthLockEffectsTweenPixels")
ThemeMetric< float > FADE_BEFORE_TARGETS_PERCENT ("NoteField", "FadeBeforeTargetsPercent")
ThemeMetric< float > DRAW_DISTANCE_BEFORE_TARGET_PIXELS ("Player", "DrawDistanceBeforeTargetsPixels")
ThemeMetric< float > GRAY_ARROWS_Y_STANDARD ("Player", "ReceptorArrowsYStandard")
ThemeMetric< float > GRAY_ARROWS_Y_REVERSE ("Player", "ReceptorArrowsYReverse")
Macro Definition Documentation
CENTER_LINE_Y
#define CENTER_LINE_Y 160
Referenced by GetCenterLine().
FADE_DIST_Y
#define FADE_DIST_Y 40
Referenced by GetHiddenEndLine(), GetHiddenStartLine(), GetSuddenEndLine(), and GetSuddenStartLine().
Function Documentation
ArrowGetPercentVisible()
float ArrowGetPercentVisible (float fYPosWithoutReverse)
References PlayerOptions::APPEARANCE_BLINK, PlayerOptions::APPEARANCE_HIDDEN, PlayerOptions::APPEARANCE_RANDOMVANISH, PlayerOptions::APPEARANCE_STEALTH, PlayerOptions::APPEARANCE_SUDDEN, BLINK_MOD_FREQUENCY, clamp, CLAMP(), f, GetCenterLine(), GetHiddenEndLine(), GetHiddenStartLine(), GetSuddenEndLine(), GetSuddenStartLine(), RageTimer::GetTimeSinceStartFast(), HIDDEN_SUDDEN_PAST_RECEPTOR, PlayerOptions::m_fAppearances, Quantize(), RageFastSin(), and SCALE.
Referenced by ArrowEffects::GetAlpha(), and ArrowEffects::GetGlow().
ArrowGetReverseShiftAndScale()
static void ArrowGetReverseShiftAndScale (int iCol, float fYReverseOffsetPixels, float & fShiftOut, float & fScaleOut) static
References PlayerOptions::EFFECT_MINI, f, PlayerOptions::GetReversePercentForColumn(), PlayerOptions::m_fEffects, PlayerOptions::m_fScrolls, SCALE, and PlayerOptions::SCROLL_CENTERED.
Referenced by ArrowEffects::GetYOffsetFromYPos(), and ArrowEffects::GetYPos().
GetCenterLine()
static float GetCenterLine () static
References CENTER_LINE_Y, PlayerOptions::EFFECT_MINI, and PlayerOptions::m_fEffects.
Referenced by ArrowGetPercentVisible(), GetHiddenEndLine(), GetHiddenStartLine(), GetSuddenEndLine(), and GetSuddenStartLine().
GetDisplayedBeat()
static float GetDisplayedBeat (const PlayerState * pPlayerState, float beat) static
References PlayerState::m_CacheDisplayedBeat, and max().
Referenced by ArrowEffects::GetYOffset().
GetHiddenEndLine()
static float GetHiddenEndLine () static
References PlayerOptions::APPEARANCE_HIDDEN_OFFSET, f, FADE_DIST_Y, GetCenterLine(), GetHiddenSudden(), PlayerOptions::m_fAppearances, and SCALE.
Referenced by ArrowGetPercentVisible().
GetHiddenStartLine()
static float GetHiddenStartLine () static
References PlayerOptions::APPEARANCE_HIDDEN_OFFSET, f, FADE_DIST_Y, GetCenterLine(), GetHiddenSudden(), PlayerOptions::m_fAppearances, and SCALE.
Referenced by ArrowGetPercentVisible().
GetHiddenSudden()
static float GetHiddenSudden () static
References PlayerOptions::APPEARANCE_HIDDEN, PlayerOptions::APPEARANCE_SUDDEN, and PlayerOptions::m_fAppearances.
Referenced by GetHiddenEndLine(), GetHiddenStartLine(), GetSuddenEndLine(), and GetSuddenStartLine().
GetNoteFieldHeight()
static float GetNoteFieldHeight () static
References PlayerOptions::m_fPerspectiveTilt, and SCREEN_HEIGHT.
Referenced by ArrowEffects::GetYOffset().
GetSuddenEndLine()
static float GetSuddenEndLine () static
References PlayerOptions::APPEARANCE_SUDDEN_OFFSET, f, FADE_DIST_Y, GetCenterLine(), GetHiddenSudden(), PlayerOptions::m_fAppearances, and SCALE.
Referenced by ArrowGetPercentVisible().
GetSuddenStartLine()
static float GetSuddenStartLine () static
References PlayerOptions::APPEARANCE_SUDDEN_OFFSET, f, FADE_DIST_Y, GetCenterLine(), GetHiddenSudden(), PlayerOptions::m_fAppearances, and SCALE.
Referenced by ArrowGetPercentVisible().
Variable Documentation
ARROW_SPACING
ThemeMetric<float> ARROW_SPACING("ArrowEffects", "ArrowSpacing") static
Referenced by ArrowEffects::GetYOffset().
BEAT_OFFSET_HEIGHT
ThemeMetric<float> BEAT_OFFSET_HEIGHT("ArrowEffects", "BeatOffsetHeight") static
Referenced by ArrowEffects::GetXPos().
BEAT_PI_HEIGHT
ThemeMetric<float> BEAT_PI_HEIGHT("ArrowEffects", "BeatPIHeight") static
Referenced by ArrowEffects::GetXPos().
BLINK_MOD_FREQUENCY
ThemeMetric<float> BLINK_MOD_FREQUENCY("ArrowEffects", "BlinkModFrequency") static
Referenced by ArrowGetPercentVisible().
BOOMERANG_PEAK_PERCENTAGE
ThemeMetric<float> BOOMERANG_PEAK_PERCENTAGE("ArrowEffects", "BoomerangPeakPercentage") static
Referenced by ArrowEffects::GetYOffset().
BOOST_MOD_MAX_CLAMP
ThemeMetric<float> BOOST_MOD_MAX_CLAMP("ArrowEffects", "BoostModMaxClamp") static
Referenced by ArrowEffects::GetYOffset().
BOOST_MOD_MIN_CLAMP
ThemeMetric<float> BOOST_MOD_MIN_CLAMP("ArrowEffects", "BoostModMinClamp") static
Referenced by ArrowEffects::GetYOffset().
BRAKE_MOD_MAX_CLAMP
ThemeMetric<float> BRAKE_MOD_MAX_CLAMP("ArrowEffects", "BrakeModMaxClamp") static
Referenced by ArrowEffects::GetYOffset().
BRAKE_MOD_MIN_CLAMP
ThemeMetric<float> BRAKE_MOD_MIN_CLAMP("ArrowEffects", "BrakeModMinClamp") static
Referenced by ArrowEffects::GetYOffset().
curr_options
const PlayerOptions* curr_options = nullptr static
Referenced by NoteField::CalcPixelsBeforeAndAfterTargets(), and Player::DrawPrimitives().
DIZZY_HOLD_HEADS
ThemeMetric<bool> DIZZY_HOLD_HEADS("ArrowEffects", "DizzyHoldHeads") static
Referenced by ArrowEffects::GetRotationZ().
DRAW_DISTANCE_BEFORE_TARGET_PIXELS
ThemeMetric<float> DRAW_DISTANCE_BEFORE_TARGET_PIXELS("Player", "DrawDistanceBeforeTargetsPixels")
DRUNK_ARROW_MAGNITUDE
ThemeMetric<float> DRUNK_ARROW_MAGNITUDE("ArrowEffects", "DrunkArrowMagnitude") static
Referenced by ArrowEffects::GetXPos().
DRUNK_COLUMN_FREQUENCY
ThemeMetric<float> DRUNK_COLUMN_FREQUENCY("ArrowEffects", "DrunkColumnFrequency") static
Referenced by ArrowEffects::GetXPos().
DRUNK_OFFSET_FREQUENCY
ThemeMetric<float> DRUNK_OFFSET_FREQUENCY("ArrowEffects", "DrunkOffsetFrequency") static
Referenced by ArrowEffects::GetXPos().
EXPAND_MULTIPLIER_FREQUENCY
ThemeMetric<float> EXPAND_MULTIPLIER_FREQUENCY("ArrowEffects", "ExpandMultiplierFrequency") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_MULTIPLIER_SCALE_FROM_HIGH
ThemeMetric<float> EXPAND_MULTIPLIER_SCALE_FROM_HIGH("ArrowEffects", "ExpandMultiplierScaleFromHigh") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_MULTIPLIER_SCALE_FROM_LOW
ThemeMetric<float> EXPAND_MULTIPLIER_SCALE_FROM_LOW("ArrowEffects", "ExpandMultiplierScaleFromLow") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_MULTIPLIER_SCALE_TO_HIGH
ThemeMetric<float> EXPAND_MULTIPLIER_SCALE_TO_HIGH("ArrowEffects", "ExpandMultiplierScaleToHigh") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_MULTIPLIER_SCALE_TO_LOW
ThemeMetric<float> EXPAND_MULTIPLIER_SCALE_TO_LOW("ArrowEffects", "ExpandMultiplierScaleToLow") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_SPEED_SCALE_FROM_HIGH
ThemeMetric<float> EXPAND_SPEED_SCALE_FROM_HIGH("ArrowEffects", "ExpandSpeedScaleFromHigh") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_SPEED_SCALE_FROM_LOW
ThemeMetric<float> EXPAND_SPEED_SCALE_FROM_LOW("ArrowEffects", "ExpandSpeedScaleFromLow") static
Referenced by ArrowEffects::GetYOffset().
EXPAND_SPEED_SCALE_TO_LOW
ThemeMetric<float> EXPAND_SPEED_SCALE_TO_LOW("ArrowEffects", "ExpandSpeedScaleToLow") static
Referenced by ArrowEffects::GetYOffset().
FADE_BEFORE_TARGETS_PERCENT
ThemeMetric<float> FADE_BEFORE_TARGETS_PERCENT("NoteField", "FadeBeforeTargetsPercent")
FRAME_WIDTH_EFFECTS_MAX_MULTIPLIER
ThemeMetric<float> FRAME_WIDTH_EFFECTS_MAX_MULTIPLIER("ArrowEffects", "FrameWidthEffectsMaxMultiplier") static
Referenced by ArrowEffects::GetFrameWidthScale().
FRAME_WIDTH_EFFECTS_MIN_MULTIPLIER
ThemeMetric<float> FRAME_WIDTH_EFFECTS_MIN_MULTIPLIER("ArrowEffects", "FrameWidthEffectsMinMultiplier") static
Referenced by ArrowEffects::GetFrameWidthScale().
FRAME_WIDTH_EFFECTS_PIXELS_PER_SECOND
ThemeMetric<float> FRAME_WIDTH_EFFECTS_PIXELS_PER_SECOND("ArrowEffects", "FrameWidthEffectsPixelsPerSecond") static
Referenced by ArrowEffects::GetFrameWidthScale().
FRAME_WIDTH_LOCK_EFFECTS_TO_OVERLAPPING
ThemeMetric<bool> FRAME_WIDTH_LOCK_EFFECTS_TO_OVERLAPPING("ArrowEffects", "FrameWidthLockEffectsToOverlapping") static
Referenced by ArrowEffects::GetFrameWidthScale().
FRAME_WIDTH_LOCK_EFFECTS_TWEEN_PIXELS
ThemeMetric<float> FRAME_WIDTH_LOCK_EFFECTS_TWEEN_PIXELS("ArrowEffects", "FrameWidthLockEffectsTweenPixels") static
Referenced by ArrowEffects::GetFrameWidthScale().
GRAY_ARROWS_Y_REVERSE
ThemeMetric<float> GRAY_ARROWS_Y_REVERSE("Player", "ReceptorArrowsYReverse")
GRAY_ARROWS_Y_STANDARD
ThemeMetric<float> GRAY_ARROWS_Y_STANDARD("Player", "ReceptorArrowsYStandard")
HIDDEN_SUDDEN_PAST_RECEPTOR
ThemeMetric<bool> HIDDEN_SUDDEN_PAST_RECEPTOR("ArrowEffects", "DrawHiddenNotesAfterReceptor") static
Referenced by ArrowGetPercentVisible().
QUANTIZE_ARROW_Y
ThemeMetric<bool> QUANTIZE_ARROW_Y("ArrowEffects", "QuantizeArrowYPosition") static
Referenced by ArrowEffects::GetYPos().
TINY_PERCENT_BASE
ThemeMetric<float> TINY_PERCENT_BASE("ArrowEffects", "TinyPercentBase") static
Referenced by ArrowEffects::GetXPos().
TINY_PERCENT_GATE
ThemeMetric<float> TINY_PERCENT_GATE("ArrowEffects", "TinyPercentGate") static
Referenced by ArrowEffects::GetXPos().
TIPSY_ARROW_MAGNITUDE
ThemeMetric<float> TIPSY_ARROW_MAGNITUDE("ArrowEffects", "TipsyArrowMagnitude") static
Referenced by ArrowEffects::Update().
TIPSY_COLUMN_FREQUENCY
ThemeMetric<float> TIPSY_COLUMN_FREQUENCY("ArrowEffects", "TipsyColumnFrequency") static
Referenced by ArrowEffects::Update().
TIPSY_OFFSET_ARROW_MAGNITUDE
ThemeMetric<float> TIPSY_OFFSET_ARROW_MAGNITUDE("ArrowEffects", "TipsyOffsetArrowMagnitude") static
Referenced by ArrowEffects::Update().
TIPSY_OFFSET_COLUMN_FREQUENCY
ThemeMetric<float> TIPSY_OFFSET_COLUMN_FREQUENCY("ArrowEffects", "TipsyOffsetColumnFrequency") static
Referenced by ArrowEffects::Update().
TIPSY_OFFSET_TIMER_FREQUENCY
ThemeMetric<float> TIPSY_OFFSET_TIMER_FREQUENCY("ArrowEffects", "TipsyOffsetTimerFrequency") static
Referenced by ArrowEffects::Update().
TIPSY_TIMER_FREQUENCY
ThemeMetric<float> TIPSY_TIMER_FREQUENCY("ArrowEffects", "TipsyTimerFrequency") static
Referenced by ArrowEffects::Update().
TORNADO_OFFSET_FREQUENCY
ThemeMetric<float> TORNADO_OFFSET_FREQUENCY("ArrowEffects", "TornadoOffsetFrequency") static
Referenced by ArrowEffects::GetXPos().
TORNADO_OFFSET_SCALE_FROM_HIGH
ThemeMetric<float> TORNADO_OFFSET_SCALE_FROM_HIGH("ArrowEffects", "TornadoOffsetScaleFromHigh") static
Referenced by ArrowEffects::GetXPos().
TORNADO_OFFSET_SCALE_FROM_LOW
ThemeMetric<float> TORNADO_OFFSET_SCALE_FROM_LOW("ArrowEffects", "TornadoOffsetScaleFromLow") static
Referenced by ArrowEffects::GetXPos().
TORNADO_POSITION_SCALE_TO_HIGH
ThemeMetric<float> TORNADO_POSITION_SCALE_TO_HIGH("ArrowEffects", "TornadoPositionScaleToHigh") static
Referenced by ArrowEffects::GetXPos().
TORNADO_POSITION_SCALE_TO_LOW
ThemeMetric<float> TORNADO_POSITION_SCALE_TO_LOW("ArrowEffects", "TornadoPositionScaleToLow") static
Referenced by ArrowEffects::GetXPos().
WAVE_MOD_HEIGHT
ThemeMetric<float> WAVE_MOD_HEIGHT("ArrowEffects", "WaveModHeight") static
Referenced by ArrowEffects::GetYOffset().
WAVE_MOD_MAGNITUDE
ThemeMetric<float> WAVE_MOD_MAGNITUDE("ArrowEffects", "WaveModMagnitude") static
Referenced by ArrowEffects::GetYOffset().