Etterna: Background.cpp File Reference
Background.cpp File Reference
#include "global.h"
#include "Background.h"
#include "ActorUtil.h"
#include "BackgroundUtil.h"
#include "BeginnerHelper.h"
#include "DancingCharacters.h"
#include "GameConstantsAndTypes.h"
#include "GameState.h"
#include "NoteTypes.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "Quad.h"
#include "RageDisplay.h"
#include "RageTextureManager.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "ScreenDimensions.h"
#include "Song.h"
#include "StatsManager.h"
#include "Steps.h"
#include "ThemeMetric.h"
#include "XmlFile.h"
#include "XmlFileUtil.h"
#include <cfloat>
Classes
class BrightnessOverlay
struct BackgroundTransition
class BackgroundImpl
class BackgroundImpl::Layer
Functions
static RageColor GetBrightnessColor (float fBrightnessPercent)
Variables
static ThemeMetric< float > LEFT_EDGE ("Background", "LeftEdge")
static ThemeMetric< float > TOP_EDGE ("Background", "TopEdge")
static ThemeMetric< float > RIGHT_EDGE ("Background", "RightEdge")
static ThemeMetric< float > BOTTOM_EDGE ("Background", "BottomEdge")
static ThemeMetric< float > CLAMP_OUTPUT_PERCENT ("Background", "ClampOutputPercent")
static ThemeMetric< bool > SHOW_DANCING_CHARACTERS ("Background", "ShowDancingCharacters")
static ThemeMetric< bool > USE_STATIC_BG ("Background", "UseStaticBackground")
static ThemeMetric< float > RAND_BG_START_BEAT ("Background", "RandomBGStartBeat")
static ThemeMetric< float > RAND_BG_CHANGE_MEASURES ("Background", "RandomBGChangeMeasures")
static ThemeMetric< bool > RAND_BG_CHANGES_WHEN_BPM_CHANGES ("Background", "RandomBGChangesWhenBPMChangesAtMeasureStart")
static ThemeMetric< bool > RAND_BG_ENDS_AT_LAST_BEAT ("Background", "RandomBGEndsAtLastBeat")
static Preference< bool > g_bShowDanger ("ShowDanger", false)
static Preference< float > g_fBGBrightness ("BGBrightness", 0.2f)
static Preference< RandomBackgroundMode > g_RandomBackgroundMode ("RandomBackgroundMode", BGMODE_RANDOMMOVIES)
static Preference< int > g_iNumBackgrounds ("NumBackgrounds", 10)
static Preference< bool > g_bSongBackgrounds ("SongBackgrounds", true)
static float g_fBackgroundCenterWidth = 40
Function Documentation
GetBrightnessColor()
static RageColor GetBrightnessColor (float fBrightnessPercent) static
References RageColor::a, RageColor::b, CLAMP_OUTPUT_PERCENT, f, RageColor::g, and RageColor::r.
Referenced by BackgroundImpl::Init(), BrightnessOverlay::Set(), and BrightnessOverlay::SetActualBrightness().
Variable Documentation
BOTTOM_EDGE
ThemeMetric<float> BOTTOM_EDGE("Background", "BottomEdge") static
Referenced by BrightnessOverlay::BrightnessOverlay(), and BackgroundImpl::Init().
CLAMP_OUTPUT_PERCENT
ThemeMetric<float> CLAMP_OUTPUT_PERCENT("Background", "ClampOutputPercent") static
Referenced by GetBrightnessColor().
g_bShowDanger
Preference<bool> g_bShowDanger("ShowDanger", false) static
Referenced by BackgroundImpl::IsDangerAllVisible().
g_bSongBackgrounds
Preference<bool> g_bSongBackgrounds("SongBackgrounds", true) static
Referenced by BackgroundImpl::LoadFromSong().
g_fBackgroundCenterWidth
float g_fBackgroundCenterWidth = 40 static
Referenced by BrightnessOverlay::BrightnessOverlay().
g_fBGBrightness
Preference<float> g_fBGBrightness("BGBrightness", 0.2f) static
Referenced by BackgroundImpl::DrawPrimitives(), BackgroundImpl::LoadFromSong(), and BrightnessOverlay::SetActualBrightness().
g_iNumBackgrounds
Preference<int> g_iNumBackgrounds("NumBackgrounds", 10) static
Referenced by BackgroundImpl::LoadFromSong().
g_RandomBackgroundMode
Preference<RandomBackgroundMode> g_RandomBackgroundMode("RandomBackgroundMode", BGMODE_RANDOMMOVIES) static
Referenced by BackgroundImpl::Layer::CreateRandomBGA(), and BackgroundImpl::LoadFromSong().
LEFT_EDGE
ThemeMetric<float> LEFT_EDGE("Background", "LeftEdge") static
Referenced by BrightnessOverlay::BrightnessOverlay(), and BackgroundImpl::Init().
RAND_BG_CHANGE_MEASURES
ThemeMetric<float> RAND_BG_CHANGE_MEASURES("Background", "RandomBGChangeMeasures") static
Referenced by BackgroundImpl::LoadFromRandom().
RAND_BG_CHANGES_WHEN_BPM_CHANGES
ThemeMetric<bool> RAND_BG_CHANGES_WHEN_BPM_CHANGES("Background", "RandomBGChangesWhenBPMChangesAtMeasureStart") static
Referenced by BackgroundImpl::LoadFromRandom().
RAND_BG_ENDS_AT_LAST_BEAT
ThemeMetric<bool> RAND_BG_ENDS_AT_LAST_BEAT("Background", "RandomBGEndsAtLastBeat") static
Referenced by BackgroundImpl::LoadFromSong().
RAND_BG_START_BEAT
ThemeMetric<float> RAND_BG_START_BEAT("Background", "RandomBGStartBeat") static
Referenced by BackgroundImpl::LoadFromRandom().
RIGHT_EDGE
ThemeMetric<float> RIGHT_EDGE("Background", "RightEdge") static
Referenced by BrightnessOverlay::BrightnessOverlay(), and BackgroundImpl::Init().
SHOW_DANCING_CHARACTERS
ThemeMetric<bool> SHOW_DANCING_CHARACTERS("Background", "ShowDancingCharacters") static
TOP_EDGE
ThemeMetric<float> TOP_EDGE("Background", "TopEdge") static
Referenced by BrightnessOverlay::BrightnessOverlay(), and BackgroundImpl::Init().
USE_STATIC_BG
ThemeMetric<bool> USE_STATIC_BG("Background", "UseStaticBackground") static
Referenced by BackgroundImpl::Init().