Etterna: MsdFile Class Reference
MsdFile Class Reference
The class that reads the various .SSC, .SM, .SMA, .DWI, and .MSD files.
#include <MsdFile.h>
Classes
struct value_t
The list of params found in the files.
Public Member Functions
MsdFile ()
virtual ~MsdFile ()=default
Remove the MSDFile.
bool ReadFile (const RString &sFilePath, bool bUnescape)
Attempt to read an MSD file.
void ReadFromString (const RString &sString, bool bUnescape)
Attempt to read an MSD file.
RString GetError () const
Should an error take place, have an easy place to get it.
unsigned GetNumValues () const
Retrieve the number of values for each tag.
unsigned GetNumParams (unsigned val) const
Get the number of parameters for the current index.
const value_t & GetValue (unsigned val) const
Get the specified value.
RString GetParam (unsigned val, unsigned par) const
Retrieve the specified parameter.
Private Member Functions
void ReadBuf (const char *buf, int len, bool bUnescape)
Attempt to read an MSD file from the buffer.
void AddParam (const char *buf, int len)
Add a new parameter.
void AddValue ()
Add a new value.
Private Attributes
vector< value_t > values
The list of values.
RString error
The error string.
Detailed Description
The class that reads the various .SSC, .SM, .SMA, .DWI, and .MSD files.
Constructor & Destructor Documentation
MsdFile()
MsdFile::MsdFile () inline
~MsdFile()
virtual MsdFile::~MsdFile () virtual default
Remove the MSDFile.
Member Function Documentation
AddParam()
void MsdFile::AddParam (const char * buf, int len) private
Add a new parameter.
Parameters
buf the new parameter.
len the length of the new parameter.
References values.
Referenced by ReadBuf().
AddValue()
void MsdFile::AddValue () private
Add a new value.
References values.
Referenced by ReadBuf().
GetError()
RString MsdFile::GetError () const inline
Should an error take place, have an easy place to get it.
Returns
the current error.
References error.
Referenced by SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), and SSCLoader::LoadNoteDataFromSimfile().
GetNumParams()
unsigned MsdFile::GetNumParams (unsigned val) const inline
Get the number of parameters for the current index.
Parameters
val the current value index.
Returns
the number of params.
References GetNumValues(), and values.
Referenced by GetParam(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), DWILoader::LoadNoteDataFromSimfile(), and SMLoader::LoadNoteDataFromSimfile().
GetNumValues()
unsigned MsdFile::GetNumValues () const inline
Retrieve the number of values for each tag.
Returns
the nmber of values.
References values.
Referenced by GetNumParams(), GetParam(), GetValue(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), and SSCLoader::LoadNoteDataFromSimfile().
GetParam()
RString MsdFile::GetParam (unsigned val, unsigned par) const
Retrieve the specified parameter.
Parameters
val the current value index.
par the current parameter index.
Returns
the parameter in question.
References GetNumParams(), GetNumValues(), and values.
GetValue()
const value_t& MsdFile::GetValue (unsigned val) const inline
Get the specified value.
Parameters
val the current value index.
Returns
The specified value.
References ASSERT, GetNumValues(), and values.
Referenced by SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), and SSCLoader::LoadNoteDataFromSimfile().
ReadBuf()
void MsdFile::ReadBuf (const char * buf, int len, bool bUnescape) private
Attempt to read an MSD file from the buffer.
Parameters
buf the buffer containing the MSD file.
len the length of the buffer.
bUnescape a flag to see if we need to unescape values.
References AddParam(), AddValue(), and values.
Referenced by ReadFile(), and ReadFromString().
ReadFile()
bool MsdFile::ReadFile (const RString & sFilePath, bool bUnescape)
Attempt to read an MSD file.
Parameters
sFilePath the path to the file.
bUnescape a flag to see if we need to unescape values.
Returns
its success or failure.
References error, f, RageFile::GetError(), RageFile::GetFileSize(), RageFile::Open(), RageFile::Read(), and ReadBuf().
Referenced by SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), and SSCLoader::LoadNoteDataFromSimfile().
ReadFromString()
void MsdFile::ReadFromString (const RString & sString, bool bUnescape)
Attempt to read an MSD file.
Parameters
sString the path to the file.
bUnescape a flag to see if we need to unescape values.
Returns
its success or failure.
References ReadBuf().
Referenced by SMLoader::LoadEditFromBuffer().
Member Data Documentation
error
RString MsdFile::error private
The error string.
Referenced by GetError(), and ReadFile().
values
vector<value_t> MsdFile::values private
The list of values.
Referenced by AddParam(), AddValue(), GetNumParams(), GetNumValues(), GetParam(), GetValue(), and ReadBuf().
The documentation for this class was generated from the following files:
MsdFile.h
MsdFile.cpp