Etterna: RageSoundReader_Split Class Reference
RageSoundReader_Split Class Reference
#include <RageSoundReader_ChannelSplit.h>
Classes
struct ChannelMap
Public Member Functions
RageSoundReader_Split (const RageSoundReader_Split &cpy)
~RageSoundReader_Split () override
RageSoundReader_Split * Copy () const override
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RString GetError () const override
void AddSourceChannelToSound (int iFromChannel, int iToChannel)
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
RageSoundReader_Split (RageSoundSplitterImpl *pImpl)
Private Attributes
RageSoundSplitterImpl * m_pImpl
vector< ChannelMap > m_aChannels
int m_iPositionFrame
int m_iRequestFrames
int m_iNumOutputChannels
Friends
class RageSoundSplitterImpl
class RageSoundSplitter
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Constructor & Destructor Documentation
RageSoundReader_Split() [1/2]
RageSoundReader_Split::RageSoundReader_Split (const RageSoundReader_Split & cpy)
References m_aChannels, RageSoundSplitterImpl::m_apSounds, m_iNumOutputChannels, m_iPositionFrame, RageSoundSplitterImpl::m_iRefCount, m_iRequestFrames, and m_pImpl.
Referenced by Copy().
~RageSoundReader_Split()
RageSoundReader_Split::~RageSoundReader_Split () override
References RageSoundSplitterImpl::m_apSounds, m_pImpl, and RageSoundSplitterImpl::Release().
RageSoundReader_Split() [2/2]
RageSoundReader_Split::RageSoundReader_Split (RageSoundSplitterImpl * pImpl) private
References RageSoundSplitterImpl::m_apSounds, m_iNumOutputChannels, m_iPositionFrame, RageSoundSplitterImpl::m_iRefCount, m_iRequestFrames, m_pImpl, and pImpl.
Member Function Documentation
AddSourceChannelToSound()
void RageSoundReader_Split::AddSourceChannelToSound (int iFromChannel, int iToChannel)
References m_aChannels, m_iNumOutputChannels, and max().
Copy()
RageSoundReader_Split* RageSoundReader_Split::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_Split().
GetError()
RString RageSoundReader_Split::GetError () const override virtual
Implements RageSoundReader.
References RageSoundReader::GetError(), m_pImpl, and RageSoundSplitterImpl::m_pSource.
GetLength()
int RageSoundReader_Split::GetLength () const override virtual
Implements RageSoundReader.
References RageSoundReader::GetLength(), m_pImpl, and RageSoundSplitterImpl::m_pSource.
GetLength_Fast()
int RageSoundReader_Split::GetLength_Fast () const override virtual
Reimplemented from RageSoundReader.
References RageSoundReader::GetLength_Fast(), m_pImpl, and RageSoundSplitterImpl::m_pSource.
GetNextSourceFrame()
int RageSoundReader_Split::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References m_iPositionFrame.
GetNumChannels()
unsigned RageSoundReader_Split::GetNumChannels () const override virtual
Implements RageSoundReader.
References m_iNumOutputChannels.
GetSampleRate()
int RageSoundReader_Split::GetSampleRate () const override virtual
Implements RageSoundReader.
References RageSoundReader::GetSampleRate(), m_pImpl, and RageSoundSplitterImpl::m_pSource.
GetStreamToSourceRatio()
float RageSoundReader_Split::GetStreamToSourceRatio () const override virtual
Implements RageSoundReader.
Read()
int RageSoundReader_Split::Read (float * pBuf, int iFrames) override virtual
Implements RageSoundReader.
References RageSoundReader::GetNumChannels(), m_aChannels, RageSoundSplitterImpl::m_iBufferPositionFrames, RageSoundReader_Split::ChannelMap::m_iFromChannel, m_iNumOutputChannels, m_iPositionFrame, m_iRequestFrames, RageSoundReader_Split::ChannelMap::m_iToChannel, m_pImpl, RageSoundSplitterImpl::m_pSource, RageSoundSplitterImpl::m_sBuffer, min(), RageSoundMixBuffer::read(), RageSoundSplitterImpl::ReadBuffer(), RageSoundMixBuffer::SetWriteOffset(), and RageSoundMixBuffer::write().
SetPosition()
int RageSoundReader_Split::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References m_iPositionFrame.
SetProperty()
bool RageSoundReader_Split::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader.
References m_pImpl, RageSoundSplitterImpl::m_pSource, and RageSoundReader::SetProperty().
Friends And Related Function Documentation
RageSoundSplitter
friend class RageSoundSplitter friend
RageSoundSplitterImpl
friend class RageSoundSplitterImpl friend
Member Data Documentation
m_aChannels
vector<ChannelMap> RageSoundReader_Split::m_aChannels private
Referenced by AddSourceChannelToSound(), RageSoundReader_Split(), and Read().
m_iNumOutputChannels
int RageSoundReader_Split::m_iNumOutputChannels private
Referenced by AddSourceChannelToSound(), GetNumChannels(), RageSoundReader_Split(), and Read().
m_iPositionFrame
int RageSoundReader_Split::m_iPositionFrame private
Referenced by GetNextSourceFrame(), RageSoundReader_Split(), Read(), and SetPosition().
m_iRequestFrames
int RageSoundReader_Split::m_iRequestFrames private
Referenced by RageSoundReader_Split(), and Read().
m_pImpl
RageSoundSplitterImpl* RageSoundReader_Split::m_pImpl private
Referenced by GetError(), GetLength(), GetLength_Fast(), GetSampleRate(), RageSoundReader_Split(), Read(), SetProperty(), and ~RageSoundReader_Split().
The documentation for this class was generated from the following files:
RageSoundReader_ChannelSplit.h
RageSoundReader_ChannelSplit.cpp