Etterna: LunaRageDisplay Class Reference
LunaRageDisplay Class Reference
Allow Lua to have access to the RageDisplay.
Public Member Functions
LunaRageDisplay ()
Public Member Functions inherited from Luna< RageDisplay >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetDisplayWidth (T *p, lua_State *L)
static int GetDisplayHeight (T *p, lua_State *L)
static int GetFPS (T *p, lua_State *L)
static int GetVPF (T *p, lua_State *L)
static int GetCumFPS (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageDisplay >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageDisplay >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageDisplay >
using T = RageDisplay
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageDisplay >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the RageDisplay.
Constructor & Destructor Documentation
LunaRageDisplay()
LunaRageDisplay::LunaRageDisplay () inline
References ADD_METHOD, GetCumFPS(), GetDisplayHeight(), GetDisplayWidth(), GetFPS(), and GetVPF().
Member Function Documentation
GetCumFPS()
static int LunaRageDisplay::GetCumFPS (T * p, lua_State * L) inline static
References RageDisplay::GetCumFPS().
Referenced by LunaRageDisplay().
GetDisplayHeight()
static int LunaRageDisplay::GetDisplayHeight (T * p, lua_State * L) inline static
References RageDisplay::GetActualVideoModeParams(), VideoModeParams::height, and LuaHelpers::Push().
Referenced by LunaRageDisplay().
GetDisplayWidth()
static int LunaRageDisplay::GetDisplayWidth (T * p, lua_State * L) inline static
References RageDisplay::GetActualVideoModeParams(), LuaHelpers::Push(), and VideoModeParams::width.
Referenced by LunaRageDisplay().
GetFPS()
static int LunaRageDisplay::GetFPS (T * p, lua_State * L) inline static
References RageDisplay::GetFPS().
Referenced by LunaRageDisplay().
GetVPF()
static int LunaRageDisplay::GetVPF (T * p, lua_State * L) inline static
References RageDisplay::GetVPF().
Referenced by LunaRageDisplay().
The documentation for this class was generated from the following file:
RageDisplay.cpp