Etterna: LunaScreenGameplay Class Reference
LunaScreenGameplay Class Reference
Allow Lua to have access to the ScreenGameplay.
Public Member Functions
LunaScreenGameplay ()
Public Member Functions inherited from Luna< ScreenGameplay >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int Center1Player (T *p, lua_State *L)
static int GetLifeMeter (T *p, lua_State *L)
static int GetPlayerInfo (T *p, lua_State *L)
static int GetDummyPlayerInfo (T *p, lua_State *L)
static bool TurningPointsValid (lua_State *L, int index)
static bool AddAmountsValid (lua_State *L, int index)
static int begin_backing_out (T *p, lua_State *L)
static int GetTrueBPS (T *p, lua_State *L)
static int GetSongPosition (T *p, lua_State *L)
static int SetReplayPosition (T *p, lua_State *L)
static int SetReplayRate (T *p, lua_State *L)
static int ToggleReplayPause (T *p, lua_State *L)
static int SetReplayBookmark (T *p, lua_State *L)
static int JumpToReplayBookmark (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScreenGameplay >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScreenGameplay >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenGameplay >
using T = ScreenGameplay
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenGameplay >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ScreenGameplay.
Constructor & Destructor Documentation
LunaScreenGameplay()
LunaScreenGameplay::LunaScreenGameplay () inline
References ADD_METHOD, begin_backing_out(), Center1Player(), GetDummyPlayerInfo(), GetLifeMeter(), GetPlayerInfo(), GetSongPosition(), GetTrueBPS(), JumpToReplayBookmark(), SetReplayBookmark(), SetReplayPosition(), SetReplayRate(), and ToggleReplayPause().
Member Function Documentation
AddAmountsValid()
static bool LunaScreenGameplay::AddAmountsValid (lua_State * L, int index) inline static
References TurningPointsValid().
begin_backing_out()
static int LunaScreenGameplay::begin_backing_out (T * p, lua_State * L) inline static
References ScreenGameplay::BeginBackingOutFromGameplay(), and COMMON_RETURN_SELF.
Referenced by LunaScreenGameplay().
Center1Player()
static int LunaScreenGameplay::Center1Player (T * p, lua_State * L) inline static
References ScreenGameplay::Center1Player().
Referenced by LunaScreenGameplay().
GetDummyPlayerInfo()
static int LunaScreenGameplay::GetDummyPlayerInfo (T * p, lua_State * L) inline static
References ScreenGameplay::GetDummyPlayerInfo(), IArg, and PlayerInfo::PushSelf().
Referenced by LunaScreenGameplay().
GetLifeMeter()
static int LunaScreenGameplay::GetLifeMeter (T * p, lua_State * L) inline static
References ScreenGameplay::GetPlayerInfo(), L, and LifeMeter::PushSelf().
Referenced by LunaScreenGameplay().
GetPlayerInfo()
static int LunaScreenGameplay::GetPlayerInfo (T * p, lua_State * L) inline static
References ScreenGameplay::GetPlayerInfo(), L, and PlayerInfo::PushSelf().
Referenced by LunaScreenGameplay().
GetSongPosition()
static int LunaScreenGameplay::GetSongPosition (T * p, lua_State * L) inline static
References ScreenGameplay::GetSongPosition().
Referenced by LunaScreenGameplay().
GetTrueBPS()
static int LunaScreenGameplay::GetTrueBPS (T * p, lua_State * L) inline static
References GAMESTATE, ModsGroup< T >::GetCurrent(), L, SongPosition::m_fCurBPS, SongOptions::m_fMusicRate, PlayerState::m_Position, GameState::m_pPlayerState, and GameState::m_SongOptions.
Referenced by LunaScreenGameplay().
JumpToReplayBookmark()
static int LunaScreenGameplay::JumpToReplayBookmark (T * p, lua_State * L) inline static
References GAMESTATE, GameState::GetPaused(), GamePreferences::m_AutoPlay, ScreenGameplay::m_fReplayBookmarkSeconds, PC_REPLAY, and ScreenGameplay::SetSongPosition().
Referenced by LunaScreenGameplay().
SetReplayBookmark()
static int LunaScreenGameplay::SetReplayBookmark (T * p, lua_State * L) inline static
References FArg, GamePreferences::m_AutoPlay, ScreenGameplay::m_fReplayBookmarkSeconds, and PC_REPLAY.
Referenced by LunaScreenGameplay().
SetReplayPosition()
static int LunaScreenGameplay::SetReplayPosition (T * p, lua_State * L) inline static
References FArg, GAMESTATE, GameState::GetPaused(), GamePreferences::m_AutoPlay, PC_REPLAY, SCREENMAN, ScreenGameplay::SetSongPosition(), and ScreenManager::SystemMessage().
Referenced by LunaScreenGameplay().
SetReplayRate()
static int LunaScreenGameplay::SetReplayRate (T * p, lua_State * L) inline static
References f, FArg, GAMESTATE, GameState::GetPaused(), GamePreferences::m_AutoPlay, PC_REPLAY, SCREENMAN, ScreenGameplay::SetRate(), and ScreenManager::SystemMessage().
Referenced by LunaScreenGameplay().
ToggleReplayPause()
static int LunaScreenGameplay::ToggleReplayPause (T * p, lua_State * L) inline static
References GamePreferences::m_AutoPlay, PC_REPLAY, SCREENMAN, ScreenManager::SystemMessage(), and ScreenGameplay::ToggleReplayPause().
Referenced by LunaScreenGameplay().
TurningPointsValid()
static bool LunaScreenGameplay::TurningPointsValid (lua_State * L, int index) inline static
References FArg.
Referenced by AddAmountsValid().
The documentation for this class was generated from the following file:
ScreenGameplay.cpp