Etterna: StopSegment Struct Reference
StopSegment Struct Reference
Identifies when a song has a stop, DDR/ITG style.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
StopSegment (int iStartRow=ROW_INVALID, float fSeconds=0.0f)
StopSegment (const StopSegment &other)
float GetPause () const
void SetPause (float fSeconds)
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const StopSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
float m_fSeconds
The number of seconds to pause at the segment's row.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a song has a stop, DDR/ITG style.
Constructor & Destructor Documentation
StopSegment() [1/2]
StopSegment::StopSegment (int iStartRow = ROW_INVALID, float fSeconds = 0.0f) inline
Referenced by Copy().
StopSegment() [2/2]
StopSegment::StopSegment (const StopSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* StopSegment::Copy () const inline override virtual
Implements TimingSegment.
References StopSegment().
DebugPrint()
void StopSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetPause(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType StopSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Row.
GetPause()
float StopSegment::GetPause () const inline
References m_fSeconds.
Referenced by AdjustSync::AutosyncTempo(), DebugPrint(), TimingData::GetBeatInternal(), GetValues(), SongCacheIndex::InsertStepsTimingData(), TimingData::NegStopAndBPMCheck(), Serialize(), ToString(), NotesWriterDWI::Write(), and WriteGlobalTags().
GetType()
TimingSegmentType StopSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_STOP.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> StopSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetPause().
IsNotable()
bool StopSegment::IsNotable () const inline override virtual
Implements TimingSegment.
References m_fSeconds.
operator==() [1/2]
bool StopSegment::operator== (const StopSegment & other) const inline
References COMPARE_FLOAT, and m_fSeconds.
Referenced by operator==().
operator==() [2/2]
bool StopSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetPause()
void StopSegment::SetPause (float fSeconds) inline
References m_fSeconds.
ToString()
RString StopSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetPause(), IntToString(), and ssprintf().
Member Data Documentation
m_fSeconds
float StopSegment::m_fSeconds private
The number of seconds to pause at the segment's row.
Referenced by GetPause(), IsNotable(), operator==(), and SetPause().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp