Etterna: ScreenMapControllers.cpp File Reference
ScreenMapControllers.cpp File Reference
#include "ScreenMapControllers.h"
#include "InputEventPlus.h"
#include "InputMapper.h"
#include "LocalizedString.h"
#include "RageInput.h"
#include "RageLog.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "ScreenPrompt.h"
#include "ThemeManager.h"
#include "global.h"
Macros
#define BUTTONS_TO_MAP THEME->GetMetric(m_sName, "ButtonsToMap")
#define MAPPED_TO_COMMAND(gc, slot)
#define ADD_ACTION(index, a, b, c, d, e)
Functions
AutoScreenMessage (SM_DoSaveAndExit)
REGISTER_SCREEN_CLASS (ScreenMapControllers)
static bool IsAxis (const DeviceInput &DeviceI)
Variables
static LocalizedString INVALID_BUTTON ("ScreenMapControllers", "InvalidButton")
static LocalizedString SAVE_PROMPT ("ScreenMapControllers", "SavePrompt")
static const float g_fSecondsToWaitForInput = 0.05f
static const int NUM_CHANGABLE_SLOTS = NUM_SHOWN_GAME_TO_DEVICE_SLOTS - 1
static LocalizedString PLAYER_SLOTS ("ScreenMapControllers", "%s slots")
static LocalizedString SLOT_NAMES [3]
static LocalizedString KEYNAME ("ScreenMapControllers", "KeyName")
Macro Definition Documentation
ADD_ACTION
#define ADD_ACTION (index, a, b, c, d, e)
Value:
m_Line.push_back(new ActorFrame);                                          \
    m_Actions[index].Load(a, b, c, d, e);
Referenced by ScreenMapControllers::Init().
BUTTONS_TO_MAP
#define BUTTONS_TO_MAP THEME->GetMetric(m_sName, "ButtonsToMap")
Referenced by ScreenMapControllers::Init().
MAPPED_TO_COMMAND
#define MAPPED_TO_COMMAND (gc, slot)
Value:
THEME->GetMetricA(m_sName,                                                 \
                      ssprintf("MappedToP%iS%iCommand", (gc) + 1, (slot) + 1))
Referenced by ScreenMapControllers::Init().
Function Documentation
AutoScreenMessage()
AutoScreenMessage (SM_DoSaveAndExit)
IsAxis()
static bool IsAxis (const DeviceInput & DeviceI) static
References DeviceInput::button, DeviceInput::IsJoystick(), JOY_AUX_1, JOY_AUX_2, JOY_AUX_3, JOY_AUX_4, JOY_DOWN, JOY_DOWN_2, JOY_HAT_DOWN, JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_LEFT, JOY_LEFT_2, JOY_RIGHT, JOY_RIGHT_2, JOY_ROT_DOWN, JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_UP, JOY_ROT_Z_DOWN, JOY_ROT_Z_UP, JOY_UP, JOY_UP_2, JOY_Z_DOWN, and JOY_Z_UP.
Referenced by ScreenMapControllers::Input().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenMapControllers)
Variable Documentation
g_fSecondsToWaitForInput
const float g_fSecondsToWaitForInput = 0.05f static
Referenced by ScreenMapControllers::Update().
INVALID_BUTTON
LocalizedString INVALID_BUTTON("ScreenMapControllers", "InvalidButton") static
Referenced by ScreenMapControllers::Input().
KEYNAME
LocalizedString KEYNAME("ScreenMapControllers", "KeyName") static
Referenced by ScreenMapControllers::Init().
NUM_CHANGABLE_SLOTS
const int NUM_CHANGABLE_SLOTS = NUM_SHOWN_GAME_TO_DEVICE_SLOTS - 1 static
Referenced by ScreenMapControllers::CursorCanGoRight(), and ScreenMapControllers::Input().
PLAYER_SLOTS
LocalizedString PLAYER_SLOTS("ScreenMapControllers", "%s slots") static
Referenced by ScreenMapControllers::Init().
SAVE_PROMPT
LocalizedString SAVE_PROMPT("ScreenMapControllers", "SavePrompt") static
Referenced by ScreenMapControllers::ExitAction().
SLOT_NAMES
LocalizedString SLOT_NAMES[3] static
Initial value:
= {
    LocalizedString("ScreenMapControllers", "Primary"),
    LocalizedString("ScreenMapControllers", "Secondary"),
    LocalizedString("ScreenMapControllers", "Default")
}