Etterna: DownloadManager Class Reference
DownloadManager Class Reference
#include <DownloadManager.h>
Public Member Functions
DownloadManager ()
~DownloadManager ()
bool LoggedIn ()
void AddFavorite (string chartkey)
void RemoveFavorite (string chartkey)
void RefreshFavourites ()
void AddGoal (string chartkey, float wife, float rate, DateTime timeAssigned)
void UpdateGoal (string chartkey, float wife, float rate, bool achieved, DateTime timeAssigned, DateTime timeAchieved)
void RemoveGoal (string chartkey, float wife, float rate)
void EndSessionIfExists ()
void EndSession ()
void StartSession (string user, string pass, function< void(bool loggedIn)> done)
void OnLogin ()
bool UploadScores ()
void RefreshPackList (string url)
void init ()
Download * DownloadAndInstallPack (const string &url, string filename="")
Download * DownloadAndInstallPack (DownloadablePack *pack)
void Update (float fDeltaSeconds)
void UpdatePacks (float fDeltaSeconds)
void UpdateHTTP (float fDeltaSeconds)
bool InstallSmzip (const string &sZipFile)
void UpdateDLSpeed ()
void UpdateDLSpeed (bool gameplay)
string GetError ()
bool Error ()
bool EncodeSpaces (string &str)
void UploadScoreWithReplayData (HighScore *hs)
void UploadScore (HighScore *hs)
bool ShouldUploadScores ()
void AddSessionCookieToCURL (CURL *curlHandle)
void SetCURLPostToURL (CURL *curlHandle, string url)
void SetCURLURL (CURL *curlHandle, string url)
HTTPRequest * SendRequest (string requestName, vector< pair< string, string >> params, function< void(HTTPRequest &, CURLMsg *)> done, bool requireLogin=true, bool post=false, bool async=true, bool withBearer=true)
HTTPRequest * SendRequestToURL (string url, vector< pair< string, string >> params, function< void(HTTPRequest &, CURLMsg *)> done, bool requireLogin, bool post, bool async, bool withBearer)
void RefreshLastVersion ()
void RefreshRegisterPage ()
void MakeAThing (string chartkey)
void RequestChartLeaderBoard (string chartkey)
void RefreshUserData ()
void RefreshUserRank ()
void RefreshTop25 (Skillset ss)
void DownloadCoreBundle (string whichoneyo)
void RefreshCoreBundles ()
vector< DownloadablePack * > GetCoreBundle (string whichoneyo)
OnlineTopScore GetTopSkillsetScore (unsigned int rank, Skillset ss, bool &result)
float GetSkillsetRating (Skillset ss)
int GetSkillsetRank (Skillset ss)
void PushSelf (lua_State *L)
Public Attributes
map< string, Download * > downloads
vector< HTTPRequest * > HTTPRequests
map< string, Download * > finishedDownloads
map< string, Download * > pendingInstallDownloads
CURLM * mPackHandle { nullptr }
CURLM * mHTTPHandle { nullptr }
CURLMcode ret
int downloadingPacks { 0 }
int HTTPRunning { 0 }
bool loggingIn
bool gameplay { false }
bool initialized { false }
string error { "" }
vector< DownloadablePack > downloadablePacks
string authToken { "" }
string sessionUser { "" }
string sessionPass { "" }
string lastVersion
string registerPage
map< string, vector< OnlineScore > > chartLeaderboards
map< Skillset, int > sessionRanks
map< Skillset, double > sessionRatings
map< Skillset, vector< OnlineTopScore > > topScores
vector< string > favorites
vector< HighScore > athing
bool currentrateonly = false
bool topscoresonly = true
map< string, vector< DownloadablePack * > > bundles
RString mostrecentresult = ""
std::deque< DownloadablePack * > DownloadQueue
const int maxPacksToDownloadAtOnce = 1
const float DownloadCooldownTime = 5.f
float timeSinceLastDownload = 0.f
Packlist pl
Constructor & Destructor Documentation
DownloadManager()
DownloadManager::DownloadManager ()
References EmptyTempDLFileDir(), LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~DownloadManager()
DownloadManager::~DownloadManager ()
References downloads, EmptyTempDLFileDir(), EndSession(), LoggedIn(), mHTTPHandle, and mPackHandle.
Member Function Documentation
AddFavorite()
void DownloadManager::AddFavorite (string chartkey)
References DLMAN, LOG, HTTPRequest::result, SendRequest(), and RageLog::Warn().
AddGoal()
void DownloadManager::AddGoal (string chartkey, float wife, float rate, DateTime timeAssigned)
References DLMAN, DateTime::GetString(), and SendRequest().
AddSessionCookieToCURL()
void DownloadManager::AddSessionCookieToCURL (CURL * curlHandle) inline
DownloadAndInstallPack() [1/2]
Download * DownloadManager::DownloadAndInstallPack (const string & url, string filename = "")
References downloadingPacks, downloads, Download::handle, mPackHandle, ret, SCREENMAN, Download::StartMessage(), ScreenManager::SystemMessage(), and UpdateDLSpeed().
Referenced by DownloadAndInstallPack().
DownloadAndInstallPack() [2/2]
Download * DownloadManager::DownloadAndInstallPack (DownloadablePack * pack)
References DLMAN, DownloadAndInstallPack(), downloadingPacks, SongManager::GetSongGroupNames(), maxPacksToDownloadAtOnce, DownloadablePack::name, Download::p_Pack, SCREENMAN, SONGMAN, ScreenManager::SystemMessage(), and DownloadablePack::url.
DownloadCoreBundle()
void DownloadManager::DownloadCoreBundle (string whichoneyo)
References DLMAN, GetCoreBundle(), and DownloadablePack::size.
EncodeSpaces()
bool DownloadManager::EncodeSpaces (string & str)
Referenced by SetCURLURL().
EndSession()
void DownloadManager::EndSession ()
References authToken, MessageManager::Broadcast(), MESSAGEMAN, sessionPass, sessionRatings, sessionUser, and topScores.
Referenced by EndSessionIfExists(), and ~DownloadManager().
EndSessionIfExists()
void DownloadManager::EndSessionIfExists ()
References EndSession(), and LoggedIn().
Error()
bool DownloadManager::Error () inline
References error.
GetCoreBundle()
vector< DownloadablePack * > DownloadManager::GetCoreBundle (string whichoneyo)
References bundles.
Referenced by DownloadCoreBundle().
GetError()
string DownloadManager::GetError () inline
References error.
GetSkillsetRank()
int DownloadManager::GetSkillsetRank (Skillset ss)
References LoggedIn(), and sessionRanks.
GetSkillsetRating()
float DownloadManager::GetSkillsetRating (Skillset ss)
References LoggedIn(), and sessionRatings.
GetTopSkillsetScore()
OnlineTopScore DownloadManager::GetTopSkillsetScore (unsigned int rank, Skillset ss, bool & result)
References topScores.
init()
void DownloadManager::init ()
References initialized, packListURL, RefreshLastVersion(), RefreshPackList(), and RefreshRegisterPage().
Referenced by Update().
InstallSmzip()
bool DownloadManager::InstallSmzip (const string & sZipFile)
References downloadPacksToAdditionalSongs, StdString::CStdStr< CT >::EqualsNoCase(), FAIL_M, FileCopy(), FILEMAN, FOREACH_CONST, GetDirListing(), GetDirListingRecursive(), GetExtension(), RageFileManager::Mount(), SCREENMAN, splitpath(), ScreenManager::SystemMessage(), TEMP_ZIP_MOUNT_POINT, and RageFileManager::Unmount().
LoggedIn()
bool DownloadManager::LoggedIn ()
References authToken.
Referenced by EndSessionIfExists(), GetSkillsetRank(), GetSkillsetRating(), RefreshTop25(), RefreshUserData(), RefreshUserRank(), SendRequestToURL(), ShouldUploadScores(), UploadScore(), UploadScores(), UploadScoreWithReplayData(), and ~DownloadManager().
MakeAThing()
void DownloadManager::MakeAThing (string chartkey)
References athing, HighScore::avatar, DLMAN, FOREACH_ENUM, HNS_Held, HNS_LetGo, HighScore::scoreid, HighScore::SetChordCohesion(), HighScore::SetDateTime(), HighScore::SetHoldNoteScore(), HighScore::SetMaxCombo(), HighScore::SetModifiers(), HighScore::SetMusicRate(), HighScore::SetName(), HighScore::SetSkillsetSSR(), HighScore::SetTapNoteScore(), HighScore::SetWifeScore(), TNS_HitMine, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, and HighScore::userid.
Referenced by LunaDownloadManager::RequestChartLeaderBoard().
OnLogin()
void DownloadManager::OnLogin ()
References MessageManager::Broadcast(), DLMAN, FOREACH_ENUM, GAMESTATE, GameState::m_pCurSteps, MESSAGEMAN, and PLAYER_1.
PushSelf()
void DownloadManager::PushSelf (lua_State * L)
Referenced by DownloadManager().
RefreshCoreBundles()
void DownloadManager::RefreshCoreBundles ()
References bundles, DLMAN, HTTPRequest::result, and SendRequest().
RefreshFavourites()
void DownloadManager::RefreshFavourites ()
References MessageManager::Broadcast(), DLMAN, MESSAGEMAN, HTTPRequest::result, and SendRequest().
RefreshLastVersion()
void DownloadManager::RefreshLastVersion ()
References GAMESTATE, GameState::GetEtternaVersion(), lastVersion, HTTPRequest::result, and SendRequest().
Referenced by init().
RefreshPackList()
void DownloadManager::RefreshPackList (string url)
References DownloadablePack::avgDifficulty, DLMAN, DownloadablePack::id, DownloadablePack::name, HTTPRequest::result, SendRequestToURL(), DownloadablePack::size, and DownloadablePack::url.
Referenced by init().
RefreshRegisterPage()
void DownloadManager::RefreshRegisterPage ()
References registerPage, HTTPRequest::result, and SendRequest().
Referenced by init().
RefreshTop25()
void DownloadManager::RefreshTop25 (Skillset ss)
References MessageManager::Broadcast(), OnlineTopScore::chartkey, OnlineTopScore::difficulty, DLMAN, initCURLHandle(), LoggedIn(), MESSAGEMAN, OnlineTopScore::overall, OnlineTopScore::rate, HTTPRequest::result, OnlineTopScore::scorekey, SendRequest(), Skill_Overall, SkillsetToString(), OnlineTopScore::songName, OnlineTopScore::ssr, StringToDifficulty(), and OnlineTopScore::wifeScore.
RefreshUserData()
void DownloadManager::RefreshUserData ()
References MessageManager::Broadcast(), DLMAN, f, FOREACH_ENUM, LoggedIn(), MESSAGEMAN, HTTPRequest::result, SendRequest(), sessionUser, Skill_Overall, and SkillsetToString().
RefreshUserRank()
void DownloadManager::RefreshUserRank ()
References MessageManager::Broadcast(), DLMAN, FOREACH_ENUM, LoggedIn(), MESSAGEMAN, HTTPRequest::result, SendRequest(), sessionUser, and SkillsetToString().
RemoveFavorite()
void DownloadManager::RemoveFavorite (string chartkey)
References DLMAN, and SendRequest().
RemoveGoal()
void DownloadManager::RemoveGoal (string chartkey, float wife, float rate)
References DLMAN, and SendRequest().
RequestChartLeaderBoard()
void DownloadManager::RequestChartLeaderBoard (string chartkey)
References OnlineScore::avatar, OnlineScore::bad, MessageManager::Broadcast(), OnlineScore::datetime, DLMAN, FOREACH_ENUM, DateTime::FromString(), OnlineScore::good, OnlineScore::great, OnlineScore::held, OnlineScore::letgo, LOG, OnlineScore::marvelous, OnlineScore::maxcombo, MESSAGEMAN, OnlineScore::minehits, OnlineScore::miss, OnlineScore::modifiers, OnlineScore::nocc, OnlineScore::perfect, OnlineScore::playerRating, OnlineScore::rate, OnlineScore::replayData, HTTPRequest::result, OnlineScore::scoreid, SendRequest(), Message::SetParam(), SkillsetToString(), OnlineScore::SSRs, RageLog::Trace(), OnlineScore::userid, OnlineScore::username, OnlineScore::valid, and OnlineScore::wife.
SendRequest()
HTTPRequest * DownloadManager::SendRequest (string requestName, vector< pair< string, string >> params, function< void(HTTPRequest &, CURLMsg *)> done, bool requireLogin = true, bool post = false, bool async = true, bool withBearer = true)
References SendRequestToURL(), and serverURL.
Referenced by AddFavorite(), AddGoal(), RefreshCoreBundles(), RefreshFavourites(), RefreshLastVersion(), RefreshRegisterPage(), RefreshTop25(), RefreshUserData(), RefreshUserRank(), RemoveFavorite(), RemoveGoal(), RequestChartLeaderBoard(), and UpdateGoal().
SendRequestToURL()
HTTPRequest * DownloadManager::SendRequestToURL (string url, vector< pair< string, string >> params, function< void(HTTPRequest &, CURLMsg *)> done, bool requireLogin, bool post, bool async, bool withBearer)
References DLMAN, error, LoggedIn(), and HTTPRequest::result.
Referenced by RefreshPackList(), and SendRequest().
SetCURLPostToURL()
void DownloadManager::SetCURLPostToURL (CURL * curlHandle, string url) inline
References L, and SetCURLURL().
Referenced by UploadScore(), and UploadScoreWithReplayData().
SetCURLURL()
void DownloadManager::SetCURLURL (CURL * curlHandle, string url) inline
References checkProtocol(), and EncodeSpaces().
Referenced by SetCURLPostToURL().
ShouldUploadScores()
bool DownloadManager::ShouldUploadScores ()
References automaticSync, LoggedIn(), GamePreferences::m_AutoPlay, and PC_HUMAN.
StartSession()
void DownloadManager::StartSession (string user, string pass, function< void(bool loggedIn)> done = [](bool) { return; })
Update()
void DownloadManager::Update (float fDeltaSeconds)
References init(), initialized, UpdateHTTP(), and UpdatePacks().
UpdateDLSpeed() [1/2]
void DownloadManager::UpdateDLSpeed ()
References downloads, gameplay, maxDLPerSecond, and maxDLPerSecondGameplay.
Referenced by DownloadAndInstallPack(), UpdateDLSpeed(), and UpdatePacks().
UpdateDLSpeed() [2/2]
void DownloadManager::UpdateDLSpeed (bool gameplay)
References gameplay, and UpdateDLSpeed().
UpdateGoal()
void DownloadManager::UpdateGoal (string chartkey, float wife, float rate, bool achieved, DateTime timeAssigned, DateTime timeAchieved)
References DLMAN, DateTime::GetString(), and SendRequest().
UpdateHTTP()
void DownloadManager::UpdateHTTP (float fDeltaSeconds)
References error, HTTPRequests, HTTPRunning, LOG, mHTTPHandle, and RageLog::Trace().
Referenced by Update().
UpdatePacks()
void DownloadManager::UpdatePacks (float fDeltaSeconds)
References MessageManager::Broadcast(), SongManager::DifferentialReload(), DLMAN, DownloadCooldownTime, downloadingPacks, DownloadQueue, downloads, error, finishedDownloads, gameplay, ScreenManager::GetScreen(), maxPacksToDownloadAtOnce, MESSAGEMAN, mPackHandle, pendingInstallDownloads, SCREENMAN, SONGMAN, timeSinceLastDownload, and UpdateDLSpeed().
Referenced by Update().
UploadScore()
void DownloadManager::UploadScore (HighScore * hs)
References HighScore::AddUploadedServer(), CURLFormPostField(), DLMAN, error, initCURLHandle(), LoggedIn(), HTTPRequest::result, serverURL, SetCURLPOSTScore(), and SetCURLPostToURL().
Referenced by UploadScores().
UploadScores()
bool DownloadManager::UploadScores ()
References ScoreManager::GetAllPBPtrs(), LoggedIn(), SCOREMAN, serverURL, and UploadScore().
UploadScoreWithReplayData()
void DownloadManager::UploadScoreWithReplayData (HighScore * hs)
References HighScore::AddUploadedServer(), DLMAN, error, f, FOREACH_ENUM, HighScore::GetOffsetVector(), HighScore::GetTapNoteTypeVector(), HighScore::GetTrackVector(), HTTPRequest::handle, HTTPRunning, initCURLHandle(), LoggedIn(), HTTPRequest::result, serverURL, SetCURLFormPostField(), SetCURLPOSTScore(), SetCURLPostToURL(), Skill_Overall, SkillsetToString(), and HighScore::timeStamps.
Member Data Documentation
athing
vector<HighScore> DownloadManager::athing
Referenced by MakeAThing(), and LunaDownloadManager::RequestChartLeaderBoard().
authToken
string DownloadManager::authToken { "" }
Referenced by EndSession(), and LoggedIn().
bundles
map<string, vector<DownloadablePack*> > DownloadManager::bundles
Referenced by GetCoreBundle(), and RefreshCoreBundles().
chartLeaderboards
map<string, vector<OnlineScore> > DownloadManager::chartLeaderboards
currentrateonly
bool DownloadManager::currentrateonly = false
Referenced by LunaDownloadManager::GetCurrentRateFilter(), LunaDownloadManager::RequestChartLeaderBoard(), and LunaDownloadManager::ToggleRateFilter().
downloadablePacks
vector<DownloadablePack> DownloadManager::downloadablePacks
DownloadCooldownTime
const float DownloadManager::DownloadCooldownTime = 5.f
Referenced by UpdatePacks().
downloadingPacks
int DownloadManager::downloadingPacks { 0 }
Referenced by DownloadAndInstallPack(), and UpdatePacks().
DownloadQueue
std::deque<DownloadablePack*> DownloadManager::DownloadQueue
Referenced by UpdatePacks().
downloads
map<string, Download*> DownloadManager::downloads
Referenced by DownloadAndInstallPack(), UpdateDLSpeed(), UpdatePacks(), and ~DownloadManager().
error
string DownloadManager::error { "" }
Referenced by Error(), GetError(), SendRequestToURL(), UpdateHTTP(), UpdatePacks(), UploadScore(), and UploadScoreWithReplayData().
favorites
vector<string> DownloadManager::favorites
finishedDownloads
map<string, Download*> DownloadManager::finishedDownloads
Referenced by UpdatePacks().
gameplay
bool DownloadManager::gameplay { false }
Referenced by UpdateDLSpeed(), and UpdatePacks().
HTTPRequests
vector<HTTPRequest*> DownloadManager::HTTPRequests
Referenced by UpdateHTTP().
HTTPRunning
int DownloadManager::HTTPRunning { 0 }
Referenced by UpdateHTTP(), and UploadScoreWithReplayData().
initialized
bool DownloadManager::initialized { false }
Referenced by init(), and Update().
lastVersion
string DownloadManager::lastVersion
Initial value:
{
        ""
    }
Referenced by RefreshLastVersion().
loggingIn
bool DownloadManager::loggingIn
Initial value:
{
        false
    }
maxPacksToDownloadAtOnce
const int DownloadManager::maxPacksToDownloadAtOnce = 1
Referenced by DownloadAndInstallPack(), and UpdatePacks().
mHTTPHandle
CURLM* DownloadManager::mHTTPHandle { nullptr }
Referenced by UpdateHTTP(), and ~DownloadManager().
mostrecentresult
RString DownloadManager::mostrecentresult = ""
mPackHandle
CURLM* DownloadManager::mPackHandle { nullptr }
Referenced by DownloadAndInstallPack(), UpdatePacks(), and ~DownloadManager().
pendingInstallDownloads
map<string, Download*> DownloadManager::pendingInstallDownloads
Referenced by UpdatePacks().
pl
Packlist DownloadManager::pl
registerPage
string DownloadManager::registerPage
Initial value:
{
        ""
    }
Referenced by RefreshRegisterPage().
ret
CURLMcode DownloadManager::ret
Referenced by DownloadAndInstallPack().
sessionPass
string DownloadManager::sessionPass { "" }
Referenced by EndSession().
sessionRanks
map<Skillset, int> DownloadManager::sessionRanks
Referenced by GetSkillsetRank().
sessionRatings
map<Skillset, double> DownloadManager::sessionRatings
Referenced by EndSession(), and GetSkillsetRating().
sessionUser
string DownloadManager::sessionUser { "" }
Referenced by EndSession(), RefreshUserData(), and RefreshUserRank().
timeSinceLastDownload
float DownloadManager::timeSinceLastDownload = 0.f
Referenced by UpdatePacks().
topScores
map<Skillset, vector<OnlineTopScore> > DownloadManager::topScores
Referenced by EndSession(), and GetTopSkillsetScore().
topscoresonly
bool DownloadManager::topscoresonly = true
Referenced by LunaDownloadManager::GetTopScoresOnlyFilter(), LunaDownloadManager::RequestChartLeaderBoard(), and LunaDownloadManager::ToggleTopScoresOnlyFilter().
The documentation for this class was generated from the following files:
DownloadManager.h
DownloadManager.cpp