Etterna: RageFileObjMem Class Reference
RageFileObjMem Class Reference
#include <RageFileDriverMemory.h>
Public Member Functions
RageFileObjMem (RageFileObjMemFile *pFile=NULL)
RageFileObjMem (const RageFileObjMem &cpy)
~RageFileObjMem () override
int ReadInternal (void *buffer, size_t bytes) override
int WriteInternal (const void *buffer, size_t bytes) override
int SeekInternal (int offset) override
int GetFileSize () const override
RageFileObjMem * Copy () const override
const RString & GetString () const
void PutString (const RString &sBuf)
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
int GetFD () override
RString GetDisplayPath () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Private Attributes
RageFileObjMemFile * m_pFile
int m_iFilePos
Additional Inherited Members
Protected Member Functions inherited from RageFileObj
virtual int FlushInternal ()
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileObjMem() [1/2]
RageFileObjMem::RageFileObjMem (RageFileObjMemFile * pFile = NULL)
References RageFileObjMemFile::AddReference(), m_iFilePos, and m_pFile.
Referenced by Copy().
RageFileObjMem() [2/2]
RageFileObjMem::RageFileObjMem (const RageFileObjMem & cpy)
References RageFileObjMemFile::AddReference(), m_iFilePos, and m_pFile.
~RageFileObjMem()
RageFileObjMem::~RageFileObjMem () override
References m_pFile, and RageFileObjMemFile::ReleaseReference().
Member Function Documentation
Copy()
RageFileObjMem * RageFileObjMem::Copy () const override virtual
Reimplemented from RageFileObj.
References RageFileObjMem().
GetFileSize()
int RageFileObjMem::GetFileSize () const override virtual
Implements RageFileObj.
References LockMut, RageFileObjMemFile::m_Mutex, m_pFile, and RageFileObjMemFile::m_sBuf.
Referenced by ReadInternal(), and SeekInternal().
GetString()
const RString & RageFileObjMem::GetString () const
References m_pFile, and RageFileObjMemFile::m_sBuf.
Referenced by XmlFileUtil::GetXML(), and GzipString().
PutString()
void RageFileObjMem::PutString (const RString & sBuf)
References RageMutex::Lock(), RageFileObjMemFile::m_Mutex, m_pFile, RageFileObjMemFile::m_sBuf, and RageMutex::Unlock().
Referenced by GunzipString().
ReadInternal()
int RageFileObjMem::ReadInternal (void * buffer, size_t bytes) override virtual
Implements RageFileObj.
References GetFileSize(), LockMut, m_iFilePos, RageFileObjMemFile::m_Mutex, m_pFile, RageFileObjMemFile::m_sBuf, and min().
SeekInternal()
int RageFileObjMem::SeekInternal (int offset) override virtual
Reimplemented from RageFileObj.
References clamp, GetFileSize(), and m_iFilePos.
WriteInternal()
int RageFileObjMem::WriteInternal (const void * buffer, size_t bytes) override virtual
Implements RageFileObj.
References RageMutex::Lock(), m_iFilePos, RageFileObjMemFile::m_Mutex, m_pFile, RageFileObjMemFile::m_sBuf, and RageMutex::Unlock().
Member Data Documentation
m_iFilePos
int RageFileObjMem::m_iFilePos private
Referenced by RageFileObjMem(), ReadInternal(), SeekInternal(), and WriteInternal().
m_pFile
RageFileObjMemFile* RageFileObjMem::m_pFile private
Referenced by GetFileSize(), GetString(), PutString(), RageFileObjMem(), ReadInternal(), WriteInternal(), and ~RageFileObjMem().
The documentation for this class was generated from the following files:
RageFileDriverMemory.h
RageFileDriverMemory.cpp