Etterna: OptionRowHandlerSteps Class Reference
OptionRowHandlerSteps Class Reference
Public Member Functions
OptionRowHandlerSteps ()
void Init () override
bool LoadInternal (const Commands &cmds) override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual ReloadChanged Reload ()
virtual int GetDefaultOption () const
virtual void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const
virtual RString GetScreen (int) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
BroadcastOnChangePtr< Steps > * m_ppStepsToFill
BroadcastOnChange< Difficulty > * m_pDifficultyToFill
const BroadcastOnChange< StepsType > * m_pst
vector< Steps * > m_vSteps
vector< Difficulty > m_vDifficulties
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerSteps()
OptionRowHandlerSteps::OptionRowHandlerSteps () inline
References Init().
Member Function Documentation
ExportOption()
int OptionRowHandlerSteps::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References FOREACH_CONST, OptionRowHandlerUtil::GetOneSelection(), and BroadcastOnChange< T >::Set().
Referenced by ImportOption().
ImportOption()
void OptionRowHandlerSteps::ImportOption (OptionRow * pRow, const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References ASSERT, ExportOption(), FOREACH_CONST, GAMESTATE, and GameState::m_PreferredDifficulty.
Init()
void OptionRowHandlerSteps::Init () inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::Init().
Referenced by OptionRowHandlerSteps().
LoadInternal()
bool OptionRowHandlerSteps::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
References CHECK_BLANK_ARG, CHECK_WRONG_NUM_ARGS, Difficulty_Edit, FOREACH_ENUM, GAMESTATE, Command::GetArg(), Steps::GetDescription(), SongUtil::GetSteps(), SongUtil::GetStepsByDifficulty(), LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, GameState::m_pCurSong, GameState::m_pCurSteps, GameState::m_PreferredDifficulty, OptionRowDefinition::m_sName, OptionRowDefinition::m_vEnabledForPlayers, OptionRowDefinition::m_vsChoices, OptionRowHandler::m_vsReloadRowMessages, Message_CurrentSongChanged, Message_EditSourceStepsTypeChanged, Message_EditStepsTypeChanged, MessageIDToString(), ROW_INVALID_IF, Command::Arg::s, BroadcastOnChange< T >::Set(), and Commands::v.
Member Data Documentation
m_pDifficultyToFill
BroadcastOnChange<Difficulty>* OptionRowHandlerSteps::m_pDifficultyToFill
m_ppStepsToFill
BroadcastOnChangePtr<Steps>* OptionRowHandlerSteps::m_ppStepsToFill
m_pst
const BroadcastOnChange<StepsType>* OptionRowHandlerSteps::m_pst
m_vDifficulties
vector<Difficulty> OptionRowHandlerSteps::m_vDifficulties
m_vSteps
vector<Steps*> OptionRowHandlerSteps::m_vSteps
The documentation for this class was generated from the following file:
OptionRowHandler.cpp