Etterna: LunaMusicWheel Class Reference
LunaMusicWheel Class Reference
Public Member Functions
DEFINE_METHOD (GetSelectedSection, GetSelectedSection())
LunaMusicWheel ()
Public Member Functions inherited from Luna< MusicWheel >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int ChangeSort (T *p, lua_State *L)
static int IsRouletting (T *p, lua_State *L)
static int SelectSong (T *p, lua_State *L)
static int SongSearch (T *p, lua_State *L)
static int ReloadSongList (T *p, lua_State *L)
static int Move (T *p, lua_State *L)
static int MoveAndCheckType (T *p, lua_State *L)
static int FilterByStepKeys (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< MusicWheel >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< MusicWheel >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< MusicWheel >
using T = MusicWheel
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< MusicWheel >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaMusicWheel()
LunaMusicWheel::LunaMusicWheel () inline
References ADD_METHOD, ChangeSort(), FilterByStepKeys(), IsRouletting(), Move(), MoveAndCheckType(), ReloadSongList(), SelectSong(), and SongSearch().
Member Function Documentation
ChangeSort()
static int LunaMusicWheel::ChangeSort (T * p, lua_State * L) inline static
References MusicWheel::ChangeSort(), and L.
Referenced by LunaMusicWheel().
DEFINE_METHOD()
LunaMusicWheel::DEFINE_METHOD (GetSelectedSection , GetSelectedSection())
FilterByStepKeys()
static int LunaMusicWheel::FilterByStepKeys (T * p, lua_State * L) inline static
References LuaHelpers::ReadArrayFromTable(), MusicWheel::ReloadSongList(), and MusicWheel::SetHashList().
Referenced by LunaMusicWheel().
IsRouletting()
static int LunaMusicWheel::IsRouletting (T * p, lua_State * L) inline static
References MusicWheel::IsRouletting().
Referenced by LunaMusicWheel().
Move()
static int LunaMusicWheel::Move (T * p, lua_State * L) inline static
References IArg, and WheelBase::Move().
Referenced by LunaMusicWheel().
MoveAndCheckType()
static int LunaMusicWheel::MoveAndCheckType (T * p, lua_State * L) inline static
References MusicWheel::GetSelectedType(), IArg, WheelBase::Move(), and LuaHelpers::Push().
Referenced by LunaMusicWheel().
ReloadSongList()
static int LunaMusicWheel::ReloadSongList (T * p, lua_State * L) inline static
References MusicWheel::ReloadSongList().
Referenced by LunaMusicWheel().
SelectSong()
static int LunaMusicWheel::SelectSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), and MusicWheel::SelectSong().
Referenced by LunaMusicWheel().
SongSearch()
static int LunaMusicWheel::SongSearch (T * p, lua_State * L) inline static
References MusicWheel::ReloadSongList(), and SArg.
Referenced by LunaMusicWheel().
The documentation for this class was generated from the following file:
MusicWheel.cpp