Etterna: RageSoundDriver Class Reference
RageSoundDriver Class Reference abstract
#include <RageSoundDriver.h>
Classes
struct Sound
struct sound_block
Public Member Functions
RageSoundDriver ()
~RageSoundDriver () override
virtual RString Init ()
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual int64_t GetPosition () const =0
virtual void Update ()
virtual float GetPlayLatency () const
virtual int GetSampleRate () const
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Public Member Functions
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes
static DriverList m_pDriverList
Protected Member Functions
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
virtual void SetupDecodingThread ()
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Private Member Functions
int64_t ClampHardwareFrame (int64_t iHardwareFrame) const
void DecodeThread ()
RageSoundMixBuffer & MixIntoBuffer (int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
int GetDataForSound (Sound &s)
Static Private Member Functions
static int DecodeThread_start (void *p)
Private Attributes
RageMutex m_Mutex
RageMutex m_SoundListMutex
Sound m_Sounds [32]
int64_t m_iMaxHardwareFrame
bool m_bShutdownDecodeThread
RageThread m_DecodeThread
Friends
class RageSoundManager
Constructor & Destructor Documentation
RageSoundDriver()
RageSoundDriver::RageSoundDriver ()
References m_bShutdownDecodeThread, m_DecodeThread, m_iMaxHardwareFrame, SetDecodeBufferSize(), and RageThread::SetName().
~RageSoundDriver()
RageSoundDriver::~RageSoundDriver () override
References RageLog::Flush(), g_iTotalAhead, g_iTotalAheadCount, RageLog::Info(), RageThread::IsCreated(), LOG, m_bShutdownDecodeThread, m_DecodeThread, max(), RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
ClampHardwareFrame()
int64_t RageSoundDriver::ClampHardwareFrame (int64_t iHardwareFrame) const private
References RageTimer::Ago(), RageTimer::IsZero(), LOG, m_iMaxHardwareFrame, max(), RageZeroTimer, RageTimer::Touch(), and RageLog::Trace().
Referenced by GetHardwareFrame().
Create()
RageSoundDriver * RageSoundDriver::Create (const RString & sDrivers) static
References ASSERT, DriverList::Create(), RageSoundManager::fix_bogus_sound_driver_pref(), FOREACH_CONST, RageLog::Info(), Init(), Rage::join(), LOG, m_pDriverList, DriverList::m_pRegistrees, SAFE_DELETE, SOUNDMAN, split(), RageLog::Trace(), and RageLog::Warn().
Referenced by RageSoundManager::Init().
DecodeThread()
void RageSoundDriver::DecodeThread () private
References ARRAYLEN, ASSERT_M, CHECKPOINT_M, chunksize(), GetDataForSound(), GetSampleRate(), LockMut, m_bShutdownDecodeThread, RageSoundDriver::Sound::m_Buffer, m_Mutex, m_Sounds, RageSoundDriver::Sound::m_State, RageSoundDriver::Sound::PLAYING, SetupDecodingThread(), ssprintf(), RageSoundDriver::Sound::STOPPING, and RageSoundReader::WOULD_BLOCK.
DecodeThread_start()
int RageSoundDriver::DecodeThread_start (void * p) static private
Referenced by StartDecodeThread().
GetDataForSound()
int RageSoundDriver::GetDataForSound (Sound & s) private
References ARRAYLEN, ASSERT, channels, RageSoundBase::GetDataToPlay(), RageSoundDriver::sound_block::m_Buffer, RageSoundDriver::Sound::m_Buffer, RageSoundDriver::sound_block::m_BufferNext, RageSoundDriver::sound_block::m_FramesInBuffer, RageSoundDriver::sound_block::m_iPosition, and RageSoundDriver::Sound::m_pSound.
Referenced by DecodeThread(), and StartMixing().
GetDefaultSoundDriverList()
RString RageSoundDriver::GetDefaultSoundDriverList () static
Referenced by LuaFunc_get_sound_driver_list().
GetHardwareFrame()
int64_t RageSoundDriver::GetHardwareFrame (RageTimer * pTimer) const
References RageTimer::Ago(), ClampHardwareFrame(), GetPosition(), LOG, RageTimer::Touch(), and RageLog::Warn().
Referenced by RageSoundManager::GetPosition().
GetPlayLatency()
virtual float RageSoundDriver::GetPlayLatency () const inline virtual
Reimplemented in RageSoundDriver_OSS, RageSoundDriver_ALSA9_Software, RageSoundDriver_WDMKS, RageSoundDriver_WaveOut, RageSoundDriver_DSound_Software, and RageSoundDriver_AU.
Referenced by RageSoundManager::GetPlayLatency().
GetPosition()
virtual int64_t RageSoundDriver::GetPosition () const pure virtual
Implemented in RageSoundDriver_OSS, RageSoundDriver_ALSA9_Software, RageSoundDriver_JACK, RageSoundDriver_WDMKS, RageSoundDriver_PulseAudio, RageSoundDriver_AU, RageSoundDriver_WaveOut, RageSoundDriver_DSound_Software, and RageSoundDriver_Null.
Referenced by GetHardwareFrame().
GetSampleRate()
virtual int RageSoundDriver::GetSampleRate () const inline virtual
Reimplemented in RageSoundDriver_OSS, RageSoundDriver_ALSA9_Software, RageSoundDriver_WDMKS, RageSoundDriver_PulseAudio, RageSoundDriver_WaveOut, RageSoundDriver_DSound_Software, RageSoundDriver_JACK, RageSoundDriver_AU, and RageSoundDriver_Null.
Referenced by DecodeThread(), RageSoundManager::GetDriverSampleRate(), and MixIntoBuffer().
Init()
virtual RString RageSoundDriver::Init () inline virtual
Reimplemented in RageSoundDriver_OSS, RageSoundDriver_WDMKS, RageSoundDriver_ALSA9_Software, RageSoundDriver_JACK, RageSoundDriver_PulseAudio, RageSoundDriver_WaveOut, RageSoundDriver_DSound_Software, and RageSoundDriver_AU.
Referenced by Create().
Mix() [1/2]
void RageSoundDriver::Mix (int16_t * pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame) protected
References channels, MixIntoBuffer(), and RageSoundMixBuffer::read().
Referenced by RageSoundDriver_OSS::GetData(), RageSoundDriver_WaveOut::GetData(), RageSoundDriver_ALSA9_Software::GetData(), RageSoundDriver_DSound_Software::MixerThread(), RageSoundDriver_WDMKS::Read(), RageSoundDriver_AU::Render(), RageSoundDriver_PulseAudio::StreamWriteCb(), and RageSoundDriver_Null::Update().
Mix() [2/2]
void RageSoundDriver::Mix (float * pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame) protected
References channels, MixIntoBuffer(), and RageSoundMixBuffer::read().
MixDeinterlaced()
void RageSoundDriver::MixDeinterlaced (float ** pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame) protected
References channels, MixIntoBuffer(), and RageSoundMixBuffer::read_deinterlace().
Referenced by RageSoundDriver_JACK::ProcessCallback().
MixIntoBuffer()
RageSoundMixBuffer & RageSoundDriver::MixIntoBuffer (int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame) private
References RageTimer::Ago(), ARRAYLEN, ASSERT_M, channels, clamp, g_iTotalAhead, g_iTotalAheadCount, GetSampleRate(), RageSoundDriver::Sound::HALTING, RageSoundDriver::Sound::QueuedPosMap::iFrames, RageSoundDriver::Sound::QueuedPosMap::iHardwareFrame, RageThread::IsCreated(), RageSoundDriver::Sound::QueuedPosMap::iStreamFrame, RageTimer::IsZero(), RageSoundDriver::Sound::m_bPaused, RageSoundDriver::Sound::m_Buffer, RageSoundDriver::sound_block::m_BufferNext, m_DecodeThread, RageSoundDriver::sound_block::m_FramesInBuffer, RageSoundDriver::sound_block::m_iPosition, RageSoundDriver::Sound::m_PosMapQueue, m_Sounds, RageSoundDriver::Sound::m_StartTime, RageSoundDriver::Sound::m_State, min(), RageSoundDriver::Sound::PLAYING, RageSoundMixBuffer::SetWriteOffset(), RageTimer::SetZero(), RageSoundDriver::Sound::STOPPED, RageSoundDriver::Sound::STOPPING, swap(), underruns, and RageSoundMixBuffer::write().
Referenced by Mix(), and MixDeinterlaced().
PauseMixing()
bool RageSoundDriver::PauseMixing (RageSoundBase * pSound, bool bStop)
References ARRAYLEN, RageSoundDriver::Sound::AVAILABLE, LockMut, LOG, RageSoundDriver::Sound::m_bPaused, m_Mutex, m_Sounds, RageSoundDriver::Sound::m_State, RageSoundDriver::Sound::PLAYING, RageSoundDriver::Sound::STOPPING, and RageLog::Trace().
Referenced by RageSoundManager::Pause().
SetDecodeBufferSize()
void RageSoundDriver::SetDecodeBufferSize (int frames) protected
References ASSERT, frames_to_buffer, RageThread::IsCreated(), and m_DecodeThread.
Referenced by RageSoundDriver_WaveOut::Init(), RageSoundDriver_WDMKS::Init(), and RageSoundDriver().
SetupDecodingThread()
virtual void RageSoundDriver::SetupDecodingThread () inline protected virtual
Reimplemented in RageSoundDriver_OSS, RageSoundDriver_WDMKS, RageSoundDriver_WaveOut, RageSoundDriver_ALSA9_Software, RageSoundDriver_DSound_Software, and RageSoundDriver_AU.
Referenced by DecodeThread().
StartDecodeThread()
void RageSoundDriver::StartDecodeThread () protected
References ASSERT, RageThread::Create(), DecodeThread_start(), RageThread::IsCreated(), and m_DecodeThread.
Referenced by RageSoundDriver_AU::Init(), RageSoundDriver_DSound_Software::Init(), RageSoundDriver_WaveOut::Init(), RageSoundDriver_JACK::Init(), RageSoundDriver_ALSA9_Software::Init(), RageSoundDriver_PulseAudio::Init(), RageSoundDriver_WDMKS::Init(), RageSoundDriver_OSS::Init(), and RageSoundDriver_Null::RageSoundDriver_Null().
StartMixing()
void RageSoundDriver::StartMixing (RageSoundBase * pSound)
References RageSoundDriver::Sound::Allocate(), ARRAYLEN, RageSoundDriver::Sound::AVAILABLE, RageSoundDriver::Sound::BUFFERING, frames_to_buffer, GetDataForSound(), RageSoundBase::GetStartTime(), RageMutex::Lock(), RageSoundDriver::Sound::m_Buffer, RageSoundDriver::Sound::m_pSound, m_SoundListMutex, m_Sounds, RageSoundDriver::Sound::m_StartTime, RageSoundDriver::Sound::m_State, RageSoundDriver::Sound::PLAYING, and RageMutex::Unlock().
Referenced by RageSoundManager::StartMixing().
StopMixing()
void RageSoundDriver::StopMixing (RageSoundBase * pSound)
References ARRAYLEN, RageSoundDriver::Sound::AVAILABLE, RageSoundDriver::Sound::HALTING, RageMutex::Lock(), LOG, m_Mutex, RageSoundDriver::Sound::m_pSound, m_Sounds, RageSoundDriver::Sound::m_State, RageSoundBase::SoundIsFinishedPlaying(), RageSoundDriver::Sound::STOPPED, RageLog::Trace(), and RageMutex::Unlock().
Referenced by RageSoundManager::StopMixing().
Update()
void RageSoundDriver::Update () virtual
Reimplemented in RageSoundDriver_Null.
References ARRAYLEN, RageSoundDriver::Sound::AVAILABLE, RageSoundBase::CommitPlayingPosition(), RageSoundDriver::Sound::Deallocate(), RageTimer::GetTimeSinceStart(), RageSoundDriver::Sound::HALTING, RageSoundDriver::Sound::QueuedPosMap::iFrames, RageSoundDriver::Sound::QueuedPosMap::iHardwareFrame, RageSoundDriver::Sound::QueuedPosMap::iStreamFrame, RageMutex::Lock(), LOG, logged_underruns, m_Mutex, RageSoundDriver::Sound::m_pSound, m_Sounds, RageSoundDriver::Sound::m_State, RageLog::MapLog(), RageSoundBase::SoundIsFinishedPlaying(), RageSoundDriver::Sound::STOPPED, RageSoundDriver::Sound::STOPPING, RageLog::Trace(), underruns, and RageMutex::Unlock().
Referenced by RageSoundDriver_Null::Update(), and RageSoundManager::Update().
Friends And Related Function Documentation
RageSoundManager
friend class RageSoundManager friend
Member Data Documentation
m_bShutdownDecodeThread
bool RageSoundDriver::m_bShutdownDecodeThread private
Referenced by DecodeThread(), RageSoundDriver(), and ~RageSoundDriver().
m_DecodeThread
RageThread RageSoundDriver::m_DecodeThread private
Referenced by MixIntoBuffer(), RageSoundDriver(), SetDecodeBufferSize(), StartDecodeThread(), and ~RageSoundDriver().
m_iMaxHardwareFrame
int64_t RageSoundDriver::m_iMaxHardwareFrame mutable private
Referenced by ClampHardwareFrame(), and RageSoundDriver().
m_Mutex
RageMutex RageSoundDriver::m_Mutex private
Referenced by DecodeThread(), PauseMixing(), StopMixing(), and Update().
m_pDriverList
DriverList RageSoundDriver::m_pDriverList static
Referenced by Create().
m_SoundListMutex
RageMutex RageSoundDriver::m_SoundListMutex private
Referenced by StartMixing().
m_Sounds
Sound RageSoundDriver::m_Sounds[32] private
Referenced by DecodeThread(), MixIntoBuffer(), PauseMixing(), StartMixing(), StopMixing(), and Update().
The documentation for this class was generated from the following files:
RageSoundDriver.h
RageSoundDriver.cpp
RageSoundDriver_Generic_Software.cpp