Etterna: ConcurrentRenderer Class Reference
ConcurrentRenderer Class Reference
Public Member Functions
ConcurrentRenderer ()
~ConcurrentRenderer ()
void Start ()
void Stop ()
Private Types
enum State { RENDERING_IDLE, RENDERING_START, RENDERING_ACTIVE, RENDERING_END }
Private Member Functions
void RenderThread ()
Static Private Member Functions
static int StartRenderThread (void *p)
Private Attributes
RageThread m_Thread
RageEvent m_Event
bool m_bShutdown
State m_State
Member Enumeration Documentation
State
enum ConcurrentRenderer::State private
Enumerator
RENDERING_IDLE
RENDERING_START
RENDERING_ACTIVE
RENDERING_END
Constructor & Destructor Documentation
ConcurrentRenderer()
ConcurrentRenderer::ConcurrentRenderer ()
References RageThread::Create(), m_bShutdown, m_State, m_Thread, RENDERING_IDLE, RageThread::SetName(), and StartRenderThread().
~ConcurrentRenderer()
ConcurrentRenderer::~ConcurrentRenderer ()
References ASSERT, m_bShutdown, m_State, m_Thread, RENDERING_IDLE, and RageThread::Wait().
Member Function Documentation
RenderThread()
void ConcurrentRenderer::RenderThread () private
References ASSERT, RageDisplay::BeginConcurrentRendering(), DISPLAY, ScreenManager::Draw(), RageDisplay::EndConcurrentRendering(), g_AccurateGameplayTimer, HOOKS, RageMutex::Lock(), LOG, m_bShutdown, m_Event, m_State, RENDERING_ACTIVE, RENDERING_END, RENDERING_IDLE, RENDERING_START, SCREENMAN, ArchHooks::SetupConcurrentRenderingThread(), RageEvent::Signal(), RageLog::Trace(), RageMutex::Unlock(), ScreenManager::Update(), and RageEvent::Wait().
Start()
void ConcurrentRenderer::Start ()
References ASSERT, RageDisplay::BeginConcurrentRenderingMainThread(), DISPLAY, RageMutex::Lock(), m_Event, m_State, RENDERING_ACTIVE, RENDERING_IDLE, RENDERING_START, RageEvent::Signal(), RageMutex::Unlock(), and RageEvent::Wait().
Referenced by GameLoop::StartConcurrentRendering().
StartRenderThread()
int ConcurrentRenderer::StartRenderThread (void * p) static private
Referenced by ConcurrentRenderer().
Stop()
void ConcurrentRenderer::Stop ()
References ASSERT, DISPLAY, RageDisplay::EndConcurrentRenderingMainThread(), RageMutex::Lock(), m_Event, m_State, RENDERING_ACTIVE, RENDERING_END, RENDERING_IDLE, RageEvent::Signal(), RageMutex::Unlock(), and RageEvent::Wait().
Referenced by GameLoop::FinishConcurrentRendering().
Member Data Documentation
m_bShutdown
bool ConcurrentRenderer::m_bShutdown private
Referenced by ConcurrentRenderer(), RenderThread(), and ~ConcurrentRenderer().
m_Event
RageEvent ConcurrentRenderer::m_Event private
Referenced by RenderThread(), Start(), and Stop().
m_State
State ConcurrentRenderer::m_State private
Referenced by ConcurrentRenderer(), RenderThread(), Start(), Stop(), and ~ConcurrentRenderer().
m_Thread
RageThread ConcurrentRenderer::m_Thread private
Referenced by ConcurrentRenderer(), and ~ConcurrentRenderer().
The documentation for this class was generated from the following file:
GameLoop.cpp