Etterna: SMLoader Struct Reference
SMLoader Struct Reference
Reads a Song from an .SM file.
#include <NotesLoaderSM.h>
Public Member Functions
SMLoader ()
SMLoader (RString ext)
virtual ~SMLoader ()=default
virtual bool LoadFromDir (const RString &sPath, Song &out, bool load_autosave=false)
Attempt to load a song from a specified path.
virtual bool LoadNoteDataFromSimfile (const RString &path, Steps &out)
Retrieve the relevant notedata from the simfile.
virtual bool LoadFromSimfile (const RString &sPath, Song &out, bool bFromCache=false)
Attempt to load the specified sm file.
virtual void GetApplicableFiles (const RString &sPath, vector< RString > &out, bool load_autosave=false)
Retrieve the list of .sm files.
virtual bool LoadEditFromFile (const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL)
virtual bool LoadEditFromBuffer (const RString &sBuffer, const RString &sEditFilePath, ProfileSlot slot, Song *givenSong=NULL)
virtual bool LoadEditFromMsd (const MsdFile &msd, const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL)
virtual bool LoadFromBGChangesString (BackgroundChange &change, const RString &sBGChangeExpression)
void ParseBPMs (vector< pair< float, float >> &out, const RString &line, const int rowsPerBeat=-1)
Parse BPM Changes data from a string.
void ProcessBPMs (TimingData &out, const vector< pair< float, float >> &vBPMChanges)
Process the BPM Segments from the string.
void ParseStops (vector< pair< float, float >> &out, const RString line, const int rowsPerBeat=-1)
Parse Stops data from a string.
void ProcessStops (TimingData &out, const vector< pair< float, float >> &vStops)
Process the Stop Segments from the data.
void ProcessBPMsAndStops (TimingData &out, vector< pair< float, float >> &vBPMs, vector< pair< float, float >> &vStops)
Process BPM and stop segments from the data.
void ProcessDelays (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Delay Segments from the string.
void ProcessTimeSignatures (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Time Signature Segments from the string.
void ProcessTickcounts (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Tickcount Segments from the string.
virtual void ProcessSpeeds (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Speed Segments from the string.
virtual void ProcessCombos (TimingData &, const RString &line, int=-1)
virtual void ProcessFakes (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Fake Segments from the string.
virtual void ProcessBGChanges (Song &out, const RString &sValueName, const RString &sPath, const RString &sParam)
void ProcessInstrumentTracks (Song &out, const RString &sParam)
virtual void SetSongTitle (const RString &title)
Set the song title.
virtual RString GetSongTitle () const
Get the song title.
Static Public Member Functions
static void TidyUpData (Song &song, bool bFromCache)
Perform some cleanup on the loaded song.
static void ProcessDelays (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTimeSignatures (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTickcounts (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessSpeeds (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessFakes (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static float RowToBeat (const RString &line, const int rowsPerBeat)
Convert a row value to the proper beat value.
Protected Member Functions
virtual void LoadFromTokens (RString sStepsType, RString sDescription, RString sDifficulty, RString sMeter, RString sRadarValues, RString sNoteData, Steps &out)
Process the different tokens we have available to get NoteData.
RString GetFileExtension () const
Retrieve the file extension associated with this loader.
Private Attributes
const RString fileExt
The file extension in use.
RString songTitle
The song title that is being processed.
Detailed Description
Reads a Song from an .SM file.
Constructor & Destructor Documentation
SMLoader() [1/2]
SMLoader::SMLoader () inline
SMLoader() [2/2]
SMLoader::SMLoader (RString ext) inline
~SMLoader()
virtual SMLoader::~SMLoader () virtual default
Member Function Documentation
GetApplicableFiles()
void SMLoader::GetApplicableFiles (const RString & sPath, vector< RString > & out, bool load_autosave = false) virtual
Retrieve the list of .sm files.
Parameters
sPath a const reference to the path on the hard drive to check.
out a vector of files found in the path.
References GetDirListing(), and GetFileExtension().
Referenced by NotesLoader::LoadFromDir(), and LoadFromDir().
GetFileExtension()
RString SMLoader::GetFileExtension () const inline protected
Retrieve the file extension associated with this loader.
Returns
the file extension.
References fileExt.
Referenced by GetApplicableFiles().
GetSongTitle()
RString SMLoader::GetSongTitle () const virtual
Get the song title.
Returns
the song title.
References songTitle.
Referenced by ParseBPMs(), ParseStops(), SMALoader::ProcessBeatsPerMeasure(), ProcessBPMsAndStops(), SSCLoader::ProcessCombos(), ProcessDelays(), ProcessFakes(), SMALoader::ProcessMultipliers(), SMALoader::ProcessSpeeds(), ProcessSpeeds(), ProcessTickcounts(), ProcessTimeSignatures(), SetSongBPMs(), SetSongLabels(), SetSongScrolls(), SetSongStops(), SetSongWarps(), SetStepsBPMs(), SetStepsLabels(), SetStepsScrolls(), SetStepsStops(), and SetStepsWarps().
LoadEditFromBuffer()
bool SMLoader::LoadEditFromBuffer (const RString & sBuffer, const RString & sEditFilePath, ProfileSlot slot, Song * givenSong = NULL) virtual
References LoadEditFromMsd(), and MsdFile::ReadFromString().
LoadEditFromFile()
bool SMLoader::LoadEditFromFile (const RString & sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song * givenSong = NULL) virtual
Reimplemented in SSCLoader.
References FILEMAN, MsdFile::GetError(), RageFileManager::GetFileSizeInBytes(), LoadEditFromMsd(), LOG, MAX_EDIT_STEPS_SIZE_BYTES, MsdFile::ReadFile(), RageLog::Trace(), and RageLog::UserLog().
LoadEditFromMsd()
bool SMLoader::LoadEditFromMsd (const MsdFile & msd, const RString & sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song * givenSong = NULL) virtual
Reimplemented in SSCLoader.
References Song::AddSteps(), Song::CreateSteps(), Difficulty_Edit, SongManager::FindSong(), MsdFile::GetNumParams(), Song::GetNumStepsLoadedFromProfile(), MsdFile::GetNumValues(), MsdFile::GetValue(), Song::IsEditAlreadyLoaded(), LoadFromTokens(), LOG, StdString::CStdStr< CT >::MakeUpper(), MAX_EDITS_PER_SONG_PER_PROFILE, StdString::CStdStr< CT >::Replace(), SAFE_DELETE, Steps::SetDifficulty(), Steps::SetFilename(), Steps::SetLoadedFromProfile(), SetSongTitle(), SONGMAN, and RageLog::UserLog().
Referenced by LoadEditFromBuffer(), and LoadEditFromFile().
LoadFromBGChangesString()
bool SMLoader::LoadFromBGChangesString (BackgroundChange & change, const RString & sBGChangeExpression) virtual
References PrefsManager::m_bQuirksMode, BackgroundChange::m_def, BackgroundChange::m_fRate, BackgroundChange::m_fStartBeat, BackgroundDef::m_sColor1, BackgroundDef::m_sColor2, BackgroundDef::m_sEffect, BackgroundDef::m_sFile1, BackgroundDef::m_sFile2, BackgroundChange::m_sTransition, StdString::CStdStr< CT >::MakeLower(), min(), RageColor::NormalizeColorString(), PREFSMAN, StdString::CStdStr< CT >::Replace(), SBE_StretchNoLoop, SBE_StretchRewind, split(), StringToFloat(), and StringToInt().
Referenced by SMALoader::LoadFromSimfile(), ProcessBGChanges(), SetFGChanges(), SMSetFGChanges(), and SongCacheIndex::SongFromStatement().
LoadFromDir()
bool SMLoader::LoadFromDir (const RString & sPath, Song & out, bool load_autosave = false) virtual
Attempt to load a song from a specified path.
Parameters
sPath a const reference to the path on the hard drive to check.
out a reference to the Song that will retrieve the song information.
Returns
its success or failure.
References GetApplicableFiles(), and LoadFromSimfile().
Referenced by NotesLoader::LoadFromDir().
LoadFromSimfile()
bool SMLoader::LoadFromSimfile (const RString & sPath, Song & out, bool bFromCache = false) virtual
Attempt to load the specified sm file.
Parameters
sPath a const reference to the path on the hard drive to check.
out a reference to the Song that will retrieve the song information.
bFromCache a check to see if we are getting certain information from the cache file.
Returns
its success or failure.
Reimplemented in SSCLoader, and SMALoader.
References Song::AddSteps(), SMSongTagInfo::BPMChanges, Song::CreateSteps(), MsdFile::GetError(), MsdFile::GetNumParams(), MsdFile::GetNumValues(), MsdFile::GetValue(), handler, StdString::CStdStr< CT >::Left(), LoadFromTokens(), LOG, TimingData::m_sFile, Song::m_SongTiming, Song::m_sSongFileName, StdString::CStdStr< CT >::MakeUpper(), SMSongTagInfo::params, ProcessBPMsAndStops(), MsdFile::ReadFile(), Steps::SetFilename(), SMSetBGChanges(), sm_parser_helper_t::song_tag_handlers, SMSongTagInfo::Stops, TidyUpData(), and RageLog::UserLog().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), LoadFromDir(), and StartMusic().
LoadFromTokens()
void SMLoader::LoadFromTokens (RString sStepsType, RString sDescription, RString sDifficulty, RString sMeter, RString sRadarValues, RString sNoteData, Steps & out) protected virtual
Process the different tokens we have available to get NoteData.
Parameters
stepsType The current StepsType.
description The description of the chart.
difficulty The difficulty (in words) of the chart.
meter the difficulty (in numbers) of the chart.
radarValues the calculated radar values.
noteData the note data itself.
out the Steps getting the data.
References StdString::CStdStr< CT >::CompareNoCase(), Difficulty_Challenge, Difficulty_Hard, GAMEMAN, Steps::GetDifficulty(), Steps::m_StepsType, Steps::m_StepsTypeStr, OldStyleStringToDifficulty(), Steps::SetChartName(), Steps::SetCredit(), Steps::SetDescription(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetSavedToDisk(), Steps::SetSMNoteData(), StringToInt(), GameManager::StringToStepsType(), Steps::TidyUpData(), and Trim().
Referenced by LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), SMALoader::LoadFromSimfile(), and LoadFromSimfile().
LoadNoteDataFromSimfile()
bool SMLoader::LoadNoteDataFromSimfile (const RString & path, Steps & out) virtual
Retrieve the relevant notedata from the simfile.
Parameters
path the path where the simfile lives.
out the Steps we are loading the data into.
Reimplemented in SSCLoader.
References StdString::CStdStr< CT >::CompareNoCase(), GAMEMAN, Steps::GetDescription(), Steps::GetDifficulty(), MsdFile::GetError(), MsdFile::GetNumParams(), MsdFile::GetNumValues(), MsdFile::GetValue(), LOG, Steps::m_StepsType, StdString::CStdStr< CT >::MakeUpper(), OldStyleStringToDifficulty(), MsdFile::ReadFile(), StdString::CStdStr< CT >::Right(), Steps::SetSMNoteData(), StringToDifficulty(), GameManager::StringToStepsType(), Steps::TidyUpData(), Trim(), and RageLog::UserLog().
Referenced by Steps::GetNoteDataFromSimfile().
ParseBPMs()
void SMLoader::ParseBPMs (vector< pair< float, float >> & out, const RString & line, const int rowsPerBeat = -1)
Parse BPM Changes data from a string.
Parameters
out the vector to put the data in.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References GetSongTitle(), LOG, RowToBeat(), split(), StringToFloat(), and RageLog::UserLog().
Referenced by SMALoader::LoadFromSimfile(), and SMSetBPMs().
ParseStops()
void SMLoader::ParseStops (vector< pair< float, float >> & out, const RString line, const int rowsPerBeat = -1)
Parse Stops data from a string.
Parameters
out the vector to put the data in.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References f, GetSongTitle(), LOG, RowToBeat(), split(), StringToFloat(), and RageLog::UserLog().
Referenced by SMALoader::LoadFromSimfile(), and SMSetStops().
ProcessBGChanges()
void SMLoader::ProcessBGChanges (Song & out, const RString & sValueName, const RString & sPath, const RString & sParam) virtual
References Song::AddBackgroundChange(), BACKGROUND_LAYER_1, enum_add(), LoadFromBGChangesString(), LOG, NUM_BackgroundLayer, split(), and RageLog::UserLog().
Referenced by SMALoader::LoadFromSimfile(), SetBGChanges(), SMSetBGChanges(), and SongCacheIndex::SongFromStatement().
ProcessBPMs()
void SMLoader::ProcessBPMs (TimingData & out, const vector< pair< float, float >> & vBPMChanges)
Process the BPM Segments from the string.
Parameters
out the TimingData being modified.
vBPMChanges the vector of BPM Changes data.
ProcessBPMsAndStops()
void SMLoader::ProcessBPMsAndStops (TimingData & out, vector< pair< float, float >> & vBPMs, vector< pair< float, float >> & vStops)
Process BPM and stop segments from the data.
Parameters
out the TimingData being modified.
vBPMs the vector of BPM changes.
vStops the vector of stops.
References TimingData::AddSegment(), BeatToNoteRow(), FAST_BPM_WARP, GetSongTitle(), LOG, TimingData::m_fBeat0OffsetInSeconds, and RageLog::UserLog().
Referenced by SMALoader::LoadFromSimfile(), and LoadFromSimfile().
ProcessCombos()
virtual void SMLoader::ProcessCombos (TimingData & , const RString & line, int = -1) inline virtual
Reimplemented in SSCLoader.
ProcessDelays() [1/2]
void SMLoader::ProcessDelays (TimingData & out, const RString & line, const int rowsPerBeat = -1)
Process the Delay Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References GetSongTitle().
Referenced by SMALoader::LoadFromSimfile(), SetSongDelays(), SetStepsDelays(), SMSetDelays(), and SongCacheIndex::SongFromStatement().
ProcessDelays() [2/2]
void SMLoader::ProcessDelays (TimingData & out, const RString & line, const string & songname, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), f, LOG, RowToBeat(), split(), StringToFloat(), and RageLog::UserLog().
ProcessFakes() [1/2]
void SMLoader::ProcessFakes (TimingData & out, const RString & line, const int rowsPerBeat = -1) virtual
Process the Fake Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References GetSongTitle().
Referenced by SMALoader::LoadFromSimfile(), SetSongFakes(), SetStepsFakes(), and SongCacheIndex::SongFromStatement().
ProcessFakes() [2/2]
void SMLoader::ProcessFakes (TimingData & out, const RString & line, const string & songname, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), LOG, RowToBeat(), split(), StringToFloat(), and RageLog::UserLog().
ProcessInstrumentTracks()
void SMLoader::ProcessInstrumentTracks (Song & out, const RString & sParam)
References FOREACH_CONST, InstrumentTrack_Invalid, Song::m_sInstrumentTrackFile, split(), and StringToInstrumentTrack().
Referenced by SMALoader::LoadFromSimfile(), SetInstrumentTrack(), SMSetInstrumentTrack(), and SongCacheIndex::SongFromStatement().
ProcessSpeeds() [1/2]
void SMLoader::ProcessSpeeds (TimingData & out, const RString & line, const int rowsPerBeat = -1) virtual
Process the Speed Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
Reimplemented in SMALoader.
References GetSongTitle().
Referenced by SetSongSpeeds(), SetStepsSpeeds(), and SongCacheIndex::SongFromStatement().
ProcessSpeeds() [2/2]
void SMLoader::ProcessSpeeds (TimingData & out, const RString & line, const string & songname, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), FOREACH_CONST, LOG, RowToBeat(), split(), StringToFloat(), StringToInt(), SpeedSegment::UNIT_BEATS, SpeedSegment::UNIT_SECONDS, and RageLog::UserLog().
ProcessStops()
void SMLoader::ProcessStops (TimingData & out, const vector< pair< float, float >> & vStops)
Process the Stop Segments from the data.
Parameters
out the TimingData being modified.
vStops the vector of Stops data.
ProcessTickcounts() [1/2]
void SMLoader::ProcessTickcounts (TimingData & out, const RString & line, const int rowsPerBeat = -1)
Process the Tickcount Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References GetSongTitle().
Referenced by SMALoader::LoadFromSimfile(), SetSongTickCounts(), SetStepsTickCounts(), SMSetTickCounts(), and SongCacheIndex::SongFromStatement().
ProcessTickcounts() [2/2]
void SMLoader::ProcessTickcounts (TimingData & out, const RString & line, const string & songname, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), clamp, f, LOG, ROWS_PER_BEAT, RowToBeat(), split(), and RageLog::UserLog().
ProcessTimeSignatures() [1/2]
void SMLoader::ProcessTimeSignatures (TimingData & out, const RString & line, const int rowsPerBeat = -1)
Process the Time Signature Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
References GetSongTitle().
Referenced by SetSongTimeSignatures(), SetStepsTimeSignatures(), SMSetTimeSignatures(), and SongCacheIndex::SongFromStatement().
ProcessTimeSignatures() [2/2]
void SMLoader::ProcessTimeSignatures (TimingData & out, const RString & line, const string & songname, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), FOREACH_CONST, LOG, RowToBeat(), split(), StringToInt(), and RageLog::UserLog().
RowToBeat()
float SMLoader::RowToBeat (const RString & line, const int rowsPerBeat) static
Convert a row value to the proper beat value.
This is primarily used for assistance with converting SMA files.
Parameters
line The line that contains the value.
rowsPerBeat the number of rows per beat according to the original file.
Returns
the converted beat value.
References StringToFloat(), and Trim().
Referenced by ParseBPMs(), ParseStops(), ProcessDelays(), ProcessFakes(), SMALoader::ProcessMultipliers(), SMALoader::ProcessSpeeds(), ProcessSpeeds(), ProcessTickcounts(), and ProcessTimeSignatures().
SetSongTitle()
void SMLoader::SetSongTitle (const RString & title) virtual
Set the song title.
Parameters
t the song title.
References songTitle.
Referenced by LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), SMALoader::LoadFromSimfile(), SetTitle(), and SMSetTitle().
TidyUpData()
void SMLoader::TidyUpData (Song & song, bool bFromCache) static
Perform some cleanup on the loaded song.
Parameters
song a reference to the song that may need cleaning up.
bFromCache a flag to determine if this song is loaded from a cache file.
References BACKGROUND_LAYER_1, Song::GetBackgroundChanges(), Song::GetBackgroundPath(), Song::GetLastBeat(), IsAFile(), Song::m_sBackgroundFile, NO_SONG_BG_FILE, and Song::TidyUpData().
Referenced by SMALoader::LoadFromSimfile(), LoadFromSimfile(), SSCLoader::LoadFromSimfile(), and SongCacheIndex::SongFromStatement().
Member Data Documentation
fileExt
const RString SMLoader::fileExt private
The file extension in use.
Referenced by GetFileExtension().
songTitle
RString SMLoader::songTitle private
The song title that is being processed.
Referenced by GetSongTitle(), and SetSongTitle().
The documentation for this struct was generated from the following files:
NotesLoaderSM.h
NotesLoaderSM.cpp