Etterna: Playlist Struct Reference
Playlist Struct Reference
#include <Difficulty.h>
Public Member Functions
void Add (Chart ch)
void AddChart (const string &ck)
void SwapPosition ()
void Create ()
XNode * CreateNode () const
void LoadFromNode (const XNode *node)
int GetNumCharts ()
vector< string > GetKeys ()
string GetName ()
float GetAverageRating ()
void DeleteChart (int i)
void PushSelf (lua_State *L)
Public Attributes
RString name
vector< Chart > chartlist
vector< vector< string > > courseruns
Member Function Documentation
Add()
void Playlist::Add (Chart ch) inline
AddChart()
void Playlist::AddChart (const string & ck)
References picosha2::detail::ch(), chartlist, Chart::FromKey(), GAMESTATE, ModsGroup< T >::GetCurrent(), SongOptions::m_fMusicRate, GameState::m_SongOptions, and Chart::rate.
Referenced by LunaPlaylist::AddChart(), and SongManager::MakePlaylistFromFavorites().
Create()
void Playlist::Create ()
CreateNode()
XNode * Playlist::CreateNode () const
References XNode::AppendAttr(), XNode::AppendChild(), picosha2::detail::ch(), chartlist, XNode::ChildrenEmpty(), courseruns, FOREACH_CONST, and name.
DeleteChart()
void Playlist::DeleteChart (int i)
References chartlist.
Referenced by LunaPlaylist::DeleteChart(), and SongManager::MakePlaylistFromFavorites().
GetAverageRating()
float Playlist::GetAverageRating ()
References chartlist.
GetKeys()
vector< string > Playlist::GetKeys ()
References chartlist.
Referenced by LunaPlaylist::GetChartkeys().
GetName()
string Playlist::GetName () inline
References name.
GetNumCharts()
int Playlist::GetNumCharts () inline
LoadFromNode()
void Playlist::LoadFromNode (const XNode * node)
References ASSERT, picosha2::detail::ch(), chartlist, XNode::ChildrenEmpty(), courseruns, FOREACH_CONST_Child, XNode::GetAttrValue(), XNode::GetChild(), XNode::GetName(), Chart::LoadFromNode(), and name.
Referenced by XMLProfile::LoadPlaylistsFromNode().
PushSelf()
void Playlist::PushSelf (lua_State * L)
SwapPosition()
void Playlist::SwapPosition ()
Member Data Documentation
chartlist
vector<Chart> Playlist::chartlist
Referenced by AddChart(), CreateNode(), DeleteChart(), LunaPlaylist::GetAllSteps(), GetAverageRating(), GetKeys(), LunaPlaylist::GetSonglist(), LunaPlaylist::GetStepslist(), ScreenGameplay::InitSongQueues(), LoadFromNode(), DBProfile::LoadPlayLists(), SongManager::MakePlaylistFromFavorites(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
courseruns
vector<vector<string> > Playlist::courseruns
Referenced by CreateNode(), and LoadFromNode().
name
RString Playlist::name
Referenced by CreateNode(), GetName(), ScreenSelectMusic::HandleScreenMessage(), LoadFromNode(), DBProfile::LoadPlayLists(), XMLProfile::LoadPlaylistsFromNode(), makePlaylist(), and SongManager::MakePlaylistFromFavorites().
The documentation for this struct was generated from the following files:
Difficulty.h
SongManager.cpp