Etterna: AnnouncerManager Class Reference
AnnouncerManager Class Reference
The commentators who say seemlingly random things during gameplay.
#include <AnnouncerManager.h>
Public Member Functions
AnnouncerManager ()
~AnnouncerManager ()
void GetAnnouncerNames (vector< RString > &AddTo)
Retrieve the announcer names.
bool DoesAnnouncerExist (const RString &sAnnouncerName)
Determine if the specified announcer exists.
void SwitchAnnouncer (const RString &sNewAnnouncerName)
Switch to a new specified announcer.
RString GetCurAnnouncerName () const
Retrieve the current announcer's name.
void NextAnnouncer ()
RString GetPathTo (const RString &sFolderName)
bool HasSoundsFor (const RString &sFolderName)
void PushSelf (lua_State *L)
Protected Member Functions
RString GetPathTo (const RString &AnnouncerPath, const RString &sFolderName)
Static Protected Member Functions
static RString GetAnnouncerDirFromName (const RString &sAnnouncerName)
Protected Attributes
RString m_sCurAnnouncerName
the current announcer's name.
Detailed Description
The commentators who say seemlingly random things during gameplay.
Constructor & Destructor Documentation
AnnouncerManager()
AnnouncerManager::AnnouncerManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~AnnouncerManager()
AnnouncerManager::~AnnouncerManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
DoesAnnouncerExist()
bool AnnouncerManager::DoesAnnouncerExist (const RString & sAnnouncerName)
Determine if the specified announcer exists.
Parameters
sAnnouncerName the announcer we're checking for.
Returns
true if it exists, false otherwise.
References GetAnnouncerNames().
Referenced by LunaAnnouncerManager::DoesAnnouncerExist(), LunaAnnouncerManager::SetCurrentAnnouncer(), and SwitchAnnouncer().
GetAnnouncerDirFromName()
RString AnnouncerManager::GetAnnouncerDirFromName (const RString & sAnnouncerName) static protected
Referenced by GetPathTo().
GetAnnouncerNames()
void AnnouncerManager::GetAnnouncerNames (vector< RString > & AddTo)
Retrieve the announcer names.
Parameters
AddTo the list of announcer names.
References GetDirListing(), StripCvsAndSvn(), and StripMacResourceForks().
Referenced by AnnouncerChoices(), DoesAnnouncerExist(), LunaAnnouncerManager::GetAnnouncerNames(), and NextAnnouncer().
GetCurAnnouncerName()
RString AnnouncerManager::GetCurAnnouncerName () const inline
Retrieve the current announcer's name.
Returns
the current announcer's name.
References m_sCurAnnouncerName.
Referenced by Announcer(), GameCommand::DescribesCurrentMode(), LunaAnnouncerManager::GetCurrentAnnouncer(), and ScreenTitleMenu::Input().
GetPathTo() [1/2]
RString AnnouncerManager::GetPathTo (const RString & sFolderName)
References m_sCurAnnouncerName.
Referenced by ScreenEvaluation::HandleScreenMessage(), HasSoundsFor(), ScreenPlayerOptions::Init(), ScreenSelectMaster::Init(), ScreenEvaluation::Init(), ScreenSelectMaster::MenuStart(), and StartQueuedSounds().
GetPathTo() [2/2]
RString AnnouncerManager::GetPathTo (const RString & AnnouncerPath, const RString & sFolderName) protected
References aliases, DirectoryIsEmpty(), GetAnnouncerDirFromName(), LOG, RageFile::Open(), RageLog::Trace(), and RageFile::WRITE.
HasSoundsFor()
bool AnnouncerManager::HasSoundsFor (const RString & sFolderName)
References DirectoryIsEmpty(), and GetPathTo().
Referenced by ScreenEvaluation::Init().
NextAnnouncer()
void AnnouncerManager::NextAnnouncer ()
References EqualsNoCase(), GetAnnouncerNames(), m_sCurAnnouncerName, and SwitchAnnouncer().
Referenced by ScreenTitleMenu::Input().
PushSelf()
void AnnouncerManager::PushSelf (lua_State * L)
Referenced by AnnouncerManager().
SwitchAnnouncer()
void AnnouncerManager::SwitchAnnouncer (const RString & sNewAnnouncerName)
Switch to a new specified announcer.
Parameters
sNewAnnouncerName the new announcer the Player will be listening to.
References DoesAnnouncerExist(), and m_sCurAnnouncerName.
Referenced by Announcer(), GameCommand::ApplySelf(), StepMania::InitializeCurrentGame(), NextAnnouncer(), and LunaAnnouncerManager::SetCurrentAnnouncer().
Member Data Documentation
m_sCurAnnouncerName
RString AnnouncerManager::m_sCurAnnouncerName protected
the current announcer's name.
Referenced by GetCurAnnouncerName(), GetPathTo(), NextAnnouncer(), and SwitchAnnouncer().
The documentation for this class was generated from the following files:
AnnouncerManager.h
AnnouncerManager.cpp