Etterna: InputQueue Class Reference
InputQueue Class Reference
Stores a list of the most recently pressed MenuInputs for each player.
#include <InputQueue.h>
Public Member Functions
InputQueue ()
void RememberInput (const InputEventPlus &gi)
bool WasPressedRecently (GameController c, GameButton button, const std::chrono::steady_clock::time_point &OldestTimeAllowed, InputEventPlus *pIEP=nullptr)
const vector< InputEventPlus > & GetQueue (GameController c) const
void ClearQueue (GameController c)
Protected Attributes
vector< InputEventPlus > m_aQueue [NUM_GameController]
Detailed Description
Stores a list of the most recently pressed MenuInputs for each player.
Constructor & Destructor Documentation
InputQueue()
InputQueue::InputQueue ()
References FOREACH_ENUM, m_aQueue, and MAX_INPUT_QUEUE_LENGTH.
Member Function Documentation
ClearQueue()
void InputQueue::ClearQueue (GameController c)
References m_aQueue.
Referenced by InputQueueCode::EnteredCode().
GetQueue()
const vector<InputEventPlus>& InputQueue::GetQueue (GameController c) const inline
References m_aQueue.
Referenced by InputQueueCode::EnteredCode().
RememberInput()
void InputQueue::RememberInput (const InputEventPlus & gi)
References GameInput::controller, InputEventPlus::GameI, GameInput::IsValid(), m_aQueue, and MAX_INPUT_QUEUE_LENGTH.
Referenced by HandleInputEvents().
WasPressedRecently()
bool InputQueue::WasPressedRecently (GameController c, GameButton button, const std::chrono::steady_clock::time_point & OldestTimeAllowed, InputEventPlus * pIEP = nullptr)
References GameInput::button, InputEventPlus::DeviceI, InputEventPlus::GameI, m_aQueue, and DeviceInput::ts.
Member Data Documentation
m_aQueue
vector<InputEventPlus> InputQueue::m_aQueue[NUM_GameController] protected
Referenced by ClearQueue(), GetQueue(), InputQueue(), RememberInput(), and WasPressedRecently().
The documentation for this class was generated from the following files:
InputQueue.h
InputQueue.cpp