Etterna: TimingData.cpp File Reference
TimingData.cpp File Reference
#include "TimingData.h"
#include "Foreach.h"
#include "GameState.h"
#include "NoteTypes.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "ThemeManager.h"
#include "global.h"
#include <cfloat>
#include "LuaBinding.h"
Classes
struct ts_less
class LunaTimingData
Allow Lua to have access to the TimingData.
Macros
#define CLEAR_LOOKUP(lookup)
#define ERASE_SEG(s)
#define INC_INDEX(index)
#define INC_INDEX(index)
#define TIMING_DATA_RETURNS_NUMBERS THEME->GetMetricB("TimingData", "GetReturnsNumbers")
#define GET_FUNCTION(get_name, segment_name)
Enumerations
enum {
FOUND_WARP, FOUND_WARP_DESTINATION, FOUND_BPM_CHANGE, FOUND_STOP,
FOUND_DELAY, FOUND_STOP_DELAY, FOUND_MARKER, NOT_FOUND
}
Functions
static void EraseSegment (vector< TimingSegment *> &vSegs, int index, TimingSegment *cur)
TimingSegment * GetSegmentAtRow (int iNoteRow, TimingSegmentType tst)
RString SegInfoStr (const vector< TimingSegment *> &segs, unsigned int index, const RString &name)
TimingData::beat_start_lookup_t::const_iterator FindEntryInLookup (const TimingData::beat_start_lookup_t &lookup, float entry)
void FindEvent (int &event_row, int &event_type, TimingData::GetBeatStarts &start, float beat, bool find_marker, const vector< TimingSegment *> &bpms, const vector< TimingSegment *> &warps, const vector< TimingSegment *> &stops, const vector< TimingSegment *> &delays)
void TimingSegmentSetToLuaTable (TimingData *td, TimingSegmentType tst, lua_State *L)
Variables
static const int INVALID_INDEX = -1
static const TimingSegment * DummySegments [NUM_TimingSegmentType]
Macro Definition Documentation
CLEAR_LOOKUP
#define CLEAR_LOOKUP (lookup)
Value:
{                                                                          \
        (lookup).clear();                                                      \
        beat_start_lookup_t tmp = lookup;                                      \
        (lookup).swap(tmp);                                                    \
    }
Referenced by TimingData::ReleaseLookup().
ERASE_SEG
#define ERASE_SEG (s)
Value:
if (segs.size() > 1) {                                                     \
        EraseSegment(segs, s, segs[s]);                                        \
        --i;                                                                   \
        --last_affected;                                                       \
        erased = true;                                                         \
    }
Referenced by TimingData::ShiftRange().
GET_FUNCTION
#define GET_FUNCTION (get_name, segment_name)
Value:
static int get_name(T* p, lua_State* L)                                    \
    {                                                                          \
        if (lua_toboolean(L, 1)) {                                             \
            TimingSegmentSetToLuaTable(p, segment_name, L);                    \
        } else {                                                               \
            LuaHelpers::CreateTableFromArray(p->ToVectorString(segment_name),  \
                                             L);                               \
        }                                                                      \
        return 1;                                                              \
    }
INC_INDEX [1/2]
#define INC_INDEX (index)
Value:
++curr_segment;                                                            \
    ++(index);
Referenced by TimingData::GetBeatInternal(), and TimingData::GetElapsedTimeInternal().
INC_INDEX [2/2]
#define INC_INDEX (index)
Value:
++curr_segment;                                                            \
    ++(index);
TIMING_DATA_RETURNS_NUMBERS
#define TIMING_DATA_RETURNS_NUMBERS THEME->GetMetricB("TimingData", "GetReturnsNumbers")
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FOUND_WARP
FOUND_WARP_DESTINATION
FOUND_BPM_CHANGE
FOUND_STOP
FOUND_DELAY
FOUND_STOP_DELAY
FOUND_MARKER
NOT_FOUND
Function Documentation
EraseSegment()
static void EraseSegment (vector< TimingSegment *> & vSegs, int index, TimingSegment * cur) static
References TimingSegment::DebugPrint(), LOG, SAFE_DELETE, and RageLog::Trace().
Referenced by TimingData::AddSegment(), and TimingData::ClearRange().
FindEntryInLookup()
TimingData::beat_start_lookup_t::const_iterator FindEntryInLookup (const TimingData::beat_start_lookup_t & lookup, float entry)
Referenced by TimingData::GetBeatAndBPSFromElapsedTimeNoOffset(), and TimingData::GetElapsedTimeFromBeatNoOffset().
FindEvent()
void FindEvent (int & event_row, int & event_type, TimingData::GetBeatStarts & start, float beat, bool find_marker, const vector< TimingSegment *> & bpms, const vector< TimingSegment *> & warps, const vector< TimingSegment *> & stops, const vector< TimingSegment *> & delays)
References BeatToNoteRow(), TimingData::GetBeatStarts::bpm, TimingData::GetBeatStarts::delay, FOUND_BPM_CHANGE, FOUND_DELAY, FOUND_MARKER, FOUND_STOP, FOUND_STOP_DELAY, FOUND_WARP, FOUND_WARP_DESTINATION, TimingData::GetBeatStarts::is_warping, TimingData::GetBeatStarts::stop, TimingData::GetBeatStarts::warp, and TimingData::GetBeatStarts::warp_destination.
Referenced by TimingData::GetBeatInternal(), and TimingData::GetElapsedTimeInternal().
GetSegmentAtRow()
TimingSegment* GetSegmentAtRow (int iNoteRow, TimingSegmentType tst)
SegInfoStr()
RString SegInfoStr (const vector< TimingSegment *> & segs, unsigned int index, const RString & name)
References ssprintf().
Referenced by TimingData::DumpOneTable().
TimingSegmentSetToLuaTable()
void TimingSegmentSetToLuaTable (TimingData * td, TimingSegmentType tst, lua_State * L)
References TimingData::GetTimingSegments(), and SEGMENT_LABEL.
Variable Documentation
DummySegments
const TimingSegment* DummySegments[NUM_TimingSegmentType] static
Initial value:
= {
    NULL,
    new StopSegment,
    new DelaySegment,
    NULL,
    new WarpSegment,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    new FakeSegment
}
INVALID_INDEX
const int INVALID_INDEX = -1 static
Referenced by TimingData::AddSegment(), TimingData::ClearRange(), TimingData::GetSegmentIndexAtRow(), and TimingData::ShiftRange().