Etterna: LuaExpressionTransform Class Reference
LuaExpressionTransform Class Reference
Handle transforming a list of items.
#include <LuaExpressionTransform.h>
Classes
struct PositionOffsetAndItemIndex
Public Member Functions
LuaExpressionTransform ()
~LuaExpressionTransform ()
void SetFromReference (const LuaReference &ref)
void SetNumSubdivisions (int iNumSubdivisions)
void TransformItemCached (Actor &a, float fPositionOffsetFromCenter, int iItemIndex, int iNumItems)
void TransformItemDirect (Actor &a, float fPositionOffsetFromCenter, int iItemIndex, int iNumItems) const
const Actor::TweenState & GetTransformCached (float fPositionOffsetFromCenter, int iItemIndex, int iNumItems) const
void ClearCache ()
Protected Attributes
LuaReference m_exprTransformFunction
int m_iNumSubdivisions
std::map< PositionOffsetAndItemIndex, Actor::TweenState > m_mapPositionToTweenStateCache
Detailed Description
Handle transforming a list of items.
Cache item transforms based on fPositionOffsetFromCenter and iItemIndex for speed.
Constructor & Destructor Documentation
LuaExpressionTransform()
LuaExpressionTransform::LuaExpressionTransform ()
References m_iNumSubdivisions.
~LuaExpressionTransform()
LuaExpressionTransform::~LuaExpressionTransform () default
Member Function Documentation
ClearCache()
void LuaExpressionTransform::ClearCache () inline
References m_mapPositionToTweenStateCache.
Referenced by ScreenOptions::RestartOptions(), and ActorScroller::SetTransformFromReference().
GetTransformCached()
const Actor::TweenState & LuaExpressionTransform::GetTransformCached (float fPositionOffsetFromCenter, int iItemIndex, int iNumItems) const
References m_mapPositionToTweenStateCache, and TransformItemDirect().
Referenced by ScreenOptions::PositionRows(), and TransformItemCached().
SetFromReference()
void LuaExpressionTransform::SetFromReference (const LuaReference & ref)
References LuaReference::GetLuaType(), m_exprTransformFunction, LuaHelpers::ReportScriptError(), and LuaReference::SetFromNil().
Referenced by ScreenOptions::Init(), StreamDisplay::Load(), WheelBase::Load(), and ActorScroller::SetTransformFromReference().
SetNumSubdivisions()
void LuaExpressionTransform::SetNumSubdivisions (int iNumSubdivisions) inline
References ASSERT, and m_iNumSubdivisions.
Referenced by ActorScroller::SetNumSubdivisions().
TransformItemCached()
void LuaExpressionTransform::TransformItemCached (Actor & a, float fPositionOffsetFromCenter, int iItemIndex, int iNumItems)
References Actor::DestTweenState(), f, GetTransformCached(), m_iNumSubdivisions, Actor::TweenState::MakeWeightedAverage(), QuantizeDown(), QuantizeUp(), and SCALE.
Referenced by ActorScroller::PositionItemsAndDrawPrimitives(), and WheelBase::SetItemPosition().
TransformItemDirect()
void LuaExpressionTransform::TransformItemDirect (Actor & a, float fPositionOffsetFromCenter, int iItemIndex, int iNumItems) const
References LuaManager::Get(), LuaReference::IsNil(), L, LUA, m_exprTransformFunction, LuaHelpers::Push(), LuaReference::PushSelf(), Actor::PushSelf(), LuaManager::Release(), and LuaHelpers::RunScriptOnStack().
Referenced by GetTransformCached(), and StreamDisplay::Load().
Member Data Documentation
m_exprTransformFunction
LuaReference LuaExpressionTransform::m_exprTransformFunction protected
Referenced by SetFromReference(), and TransformItemDirect().
m_iNumSubdivisions
int LuaExpressionTransform::m_iNumSubdivisions protected
Referenced by LuaExpressionTransform(), SetNumSubdivisions(), and TransformItemCached().
m_mapPositionToTweenStateCache
std::map<PositionOffsetAndItemIndex, Actor::TweenState> LuaExpressionTransform::m_mapPositionToTweenStateCache mutable protected
Referenced by ClearCache(), and GetTransformCached().
The documentation for this class was generated from the following files:
LuaExpressionTransform.h
LuaExpressionTransform.cpp