Etterna: OptionRow.h File Reference
OptionRow.h File Reference
#include "ActorFrame.h"
#include "AutoActor.h"
#include "BitmapText.h"
#include "ModIcon.h"
#include "OptionsCursor.h"
#include "ThemeMetric.h"
Classes
class OptionRowType
class OptionRow
Functions
RString ITEMS_LONG_ROW_X_NAME (size_t p)
RString MOD_ICON_X_NAME (size_t p)
Function Documentation
ITEMS_LONG_ROW_X_NAME()
RString ITEMS_LONG_ROW_X_NAME (size_t p)
References ssprintf().
Referenced by OptionRowType::Load().
MOD_ICON_X_NAME()
RString MOD_ICON_X_NAME (size_t p)
References ssprintf().
Referenced by OptionRowType::Load().