Etterna: Player Class Reference
Player Class Reference
Accepts input, knocks down TapNotes that were stepped on, and keeps score for the player.
#include <Player.h>
Classes
struct PlayerNoteFieldPositioner
struct TrackRowTapNote
Public Member Functions
Player (NoteData &nd, bool bVisibleParts=true)
~Player () override
void Update (float fDeltaTime) override
void DrawPrimitives () override
Draw the primitives of the Actor.
void PushPlayerMatrix (float x, float skew, float center_y)
void PopPlayerMatrix ()
void DrawNoteFieldBoard ()
void UpdateHoldNotes (int iSongRow, float fDeltaTime, vector< TrackRowTapNote > &vTN)
void Init (const RString &sType, PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats, LifeMeter *pLM, ScoreDisplay *pScoreDisplay, ScoreDisplay *pSecondaryScoreDisplay, ScoreKeeper *pPrimaryScoreKeeper, ScoreKeeper *pSecondaryScoreKeeper)
void Load ()
void CrossedRows (int iLastRowCrossed, const std::chrono::steady_clock::time_point &now)
bool IsOniDead () const
TimingData GetPlayerTimingData () const
Retrieve the Player's TimingData.
void ScoreAllActiveHoldsLetGo ()
void DoTapScoreNone ()
void AddHoldToReplayData (int col, const TapNote *pTN, int RowOfOverlappingNoteOrRow)
void AddNoteToReplayData (int col, const TapNote *pTN, int RowOfOverlappingNoteOrRow)
void Step (int col, int row, const std::chrono::steady_clock::time_point &tm, bool bHeld, bool bRelease, float padStickSeconds=0.0f)
void FadeToFail ()
void CacheAllUsedNoteSkins ()
TapNoteScore GetLastTapNoteScore () const
void SetPaused (bool bPaused)
const NoteData & GetNoteData () const
bool HasVisibleParts () const
void SetActorWithJudgmentPosition (Actor *pActor)
void SetActorWithComboPosition (Actor *pActor)
void SetSendJudgmentAndComboMessages (bool b)
void RenderAllNotesIgnoreScores ()
void PushSelf (lua_State *L) override
PlayerState * GetPlayerState ()
void ChangeLife (float delta)
void SetLife (float value)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Static Public Member Functions
static float GetMaxStepDistanceSeconds ()
static float GetWindowSeconds (TimingWindow tw)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes
bool m_inside_lua_set_life
vector< int > nerv
size_t nervpos = 0
float maxwifescore = 0.f
float curwifescore = 0.f
float wifescorepersonalbest = 0.f
int totalwifescore
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions
void UpdateTapNotesMissedOlderThan (float fMissIfOlderThanThisBeat)
void UpdateJudgedRows (float fDeltaTime)
void FlashGhostRow (int iRow)
void HandleTapRowScore (unsigned row)
void HandleHoldScore (const TapNote &tn)
void HandleHoldCheckpoint (int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow, const vector< int > &viColsWithHold)
void DrawTapJudgments ()
void DrawHoldJudgments ()
void SendComboMessages (unsigned int iOldCombo, unsigned int iOldMissCombo)
void PlayKeysound (const TapNote &tn, TapNoteScore score)
void SetMineJudgment (TapNoteScore tns, int iTrack)
void SetJudgment (int iRow, int iFirstTrack, const TapNote &tn)
void SetJudgment (int iRow, int iFirstTrack, const TapNote &tn, TapNoteScore tns, float fTapNoteOffset)
void SetHoldJudgment (TapNote &tn, int iTrack, int iRow)
void SetCombo (unsigned int iCombo, unsigned int iMisses)
void IncrementComboOrMissCombo (bool bComboOrMissCombo)
void IncrementCombo ()
void IncrementMissCombo ()
void ChangeLife (TapNoteScore tns)
void ChangeLife (HoldNoteScore hns, TapNoteScore tns)
void ChangeLifeRecord ()
void ChangeWifeRecord ()
int GetClosestNoteDirectional (int col, int iStartRow, int iMaxRowsAhead, bool bAllowGraded, bool bForward) const
int GetClosestNote (int col, int iNoteRow, int iMaxRowsAhead, int iMaxRowsBehind, bool bAllowGraded) const
int GetClosestNonEmptyRowDirectional (int iStartRow, int iMaxRowsAhead, bool bAllowGraded, bool bForward) const
int GetClosestNonEmptyRow (int iNoteRow, int iMaxRowsAhead, int iMaxRowsBehind, bool bAllowGraded) const
void HideNote (int col, int row)
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
bool m_bLoaded
PlayerState * m_pPlayerState
The player's present state.
PlayerStageStats * m_pPlayerStageStats
The player's present stage stats.
TimingData * m_Timing
float m_fNoteFieldHeight
bool m_bPaused
bool m_bDelay
NoteData & m_NoteData
NoteField * m_pNoteField
vector< HoldJudgment * > m_vpHoldJudgment
AutoActor m_sprJudgment
AutoActor m_sprCombo
Actor * m_pActorWithJudgmentPosition
Actor * m_pActorWithComboPosition
TapNoteScore m_LastTapNoteScore
LifeMeter * m_pLifeMeter
ScoreDisplay * m_pScoreDisplay
ScoreDisplay * m_pSecondaryScoreDisplay
ScoreKeeper * m_pPrimaryScoreKeeper
ScoreKeeper * m_pSecondaryScoreKeeper
int m_iFirstUncrossedRow
NoteData::all_tracks_iterator * m_pIterNeedsTapJudging
NoteData::all_tracks_iterator * m_pIterNeedsHoldJudging
NoteData::all_tracks_iterator * m_pIterUncrossedRows
NoteData::all_tracks_iterator * m_pIterUnjudgedRows
NoteData::all_tracks_iterator * m_pIterUnjudgedMineRows
unsigned int m_iLastSeenCombo
bool m_bSeenComboYet
JudgedRows * m_pJudgedRows
RageSound m_soundMine
vector< bool > m_vbFretIsDown
vector< RageSound > m_vKeysounds
ThemeMetric< float > GRAY_ARROWS_Y_STANDARD
ThemeMetric< float > GRAY_ARROWS_Y_REVERSE
ThemeMetric< float > HOLD_JUDGMENT_Y_STANDARD
ThemeMetric< float > HOLD_JUDGMENT_Y_REVERSE
ThemeMetric< int > BRIGHT_GHOST_COMBO_THRESHOLD
ThemeMetric< bool > TAP_JUDGMENTS_UNDER_FIELD
ThemeMetric< bool > HOLD_JUDGMENTS_UNDER_FIELD
ThemeMetric< bool > COMBO_UNDER_FIELD
ThemeMetric< int > DRAW_DISTANCE_AFTER_TARGET_PIXELS
ThemeMetric< int > DRAW_DISTANCE_BEFORE_TARGET_PIXELS
TweenState m_tsJudgment [NUM_REVERSE][NUM_CENTERED]
TweenState m_tsCombo [NUM_REVERSE][NUM_CENTERED]
bool m_bSendJudgmentAndComboMessages
bool m_bTickHolds
bool m_drawing_notefield_board
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
Accepts input, knocks down TapNotes that were stepped on, and keeps score for the player.
Constructor & Destructor Documentation
Player()
Player::Player (NoteData & nd, bool bVisibleParts = true)
References PlayerAI::InitFromDisk(), m_bDelay, m_bLoaded, m_bPaused, m_bSendJudgmentAndComboMessages, m_drawing_notefield_board, m_fNoteFieldHeight, m_inside_lua_set_life, m_pIterNeedsHoldJudging, m_pIterNeedsTapJudging, m_pIterUncrossedRows, m_pIterUnjudgedMineRows, m_pIterUnjudgedRows, m_pJudgedRows, m_pLifeMeter, m_pNoteField, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pScoreDisplay, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, and Actor::SetName().
~Player()
Player::~Player () override
References m_pIterNeedsHoldJudging, m_pIterNeedsTapJudging, m_pIterUncrossedRows, m_pIterUnjudgedMineRows, m_pIterUnjudgedRows, m_pJudgedRows, m_pNoteField, m_vpHoldJudgment, and SAFE_DELETE.
Member Function Documentation
AddHoldToReplayData()
void Player::AddHoldToReplayData (int col, const TapNote * pTN, int RowOfOverlappingNoteOrRow)
References HoldNoteResult::hns, HNS_Held, TapNote::HoldResult, m_pPlayerStageStats, PlayerStageStats::m_vHoldReplayData, HoldReplayResult::row, TapNote::subType, HoldReplayResult::subType, and HoldReplayResult::track.
Referenced by SetHoldJudgment().
AddNoteToReplayData()
void Player::AddNoteToReplayData (int col, const TapNote * pTN, int RowOfOverlappingNoteOrRow)
References TapNoteResult::fTapNoteOffset, m_pPlayerStageStats, PlayerStageStats::m_vNoteRowVector, PlayerStageStats::m_vOffsetVector, PlayerStageStats::m_vTapNoteTypeVector, PlayerStageStats::m_vTrackVector, TapNote::result, and TapNote::type.
Referenced by SetJudgment(), and Step().
CacheAllUsedNoteSkins()
void Player::CacheAllUsedNoteSkins ()
References NoteField::CacheAllUsedNoteSkins(), and m_pNoteField.
ChangeLife() [1/3]
void Player::ChangeLife (float delta)
References LifeMeter::ChangeLife(), ChangeLifeRecord(), and m_pLifeMeter.
Referenced by LunaPlayer::ChangeLife(), HandleHoldCheckpoint(), HandleHoldScore(), HandleTapRowScore(), LunaPlayer::LunaPlayer(), and UpdateJudgedRows().
ChangeLife() [2/3]
void Player::ChangeLife (TapNoteScore tns) protected
References LifeMeter::ChangeLife(), ChangeLifeRecord(), and m_pLifeMeter.
ChangeLife() [3/3]
void Player::ChangeLife (HoldNoteScore hns, TapNoteScore tns) protected
References LifeMeter::ChangeLife(), ChangeLifeRecord(), and m_pLifeMeter.
ChangeLifeRecord()
void Player::ChangeLifeRecord () protected
References LifeMeter::GetLife(), StatsManager::m_CurStageStats, StageStats::m_fStepsSeconds, m_pLifeMeter, m_pPlayerStageStats, PlayerStageStats::SetLifeRecordAt(), and STATSMAN.
Referenced by ChangeLife(), and SetLife().
ChangeWifeRecord()
void Player::ChangeWifeRecord () protected
References curwifescore, StatsManager::m_CurStageStats, StageStats::m_fStepsSeconds, m_pPlayerStageStats, maxwifescore, PlayerStageStats::SetLifeRecordAt(), and STATSMAN.
Referenced by SetHoldJudgment(), SetJudgment(), and SetMineJudgment().
CrossedRows()
void Player::CrossedRows (int iLastRowCrossed, const std::chrono::steady_clock::time_point & now)
References CHECKPOINTS_TAPS_SEPARATE_JUDGMENT, HoldNoteResult::fLife, GAMESTATE, GameState::GetCurrentStyle(), NoteData::GetNumTapNotesInRow(), NoteData::GetNumTracks(), GetPlayerState(), InputMapper::GetSecsHeld(), NoteData::GetTapNote(), NoteData::GetTapNoteRangeAllTracks(), TimingData::GetTickcountAtRow(), HandleHoldCheckpoint(), TapNote::HoldResult, HoldNoteResult::iCheckpointsHit, HoldNoteResult::iCheckpointsMissed, INITIAL_HOLD_LIFE, INPUTMAPPER, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), InputMapper::IsBeingPressed(), PlayerStageStats::m_bDisqualified, m_bTickHolds, PrefsManager::m_fPadStickSeconds, m_iFirstUncrossedRow, PlayerState::m_mp, m_NoteData, m_pIterUncrossedRows, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, m_pPlayerStageStats, m_pPlayerState, m_Timing, PC_AUTOPLAY, PC_HUMAN, PC_REPLAY, PlayKeysound(), PREFSMAN, REQUIRE_STEP_ON_HOLD_HEADS, TapNote::result, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), ROWS_PER_BEAT, GameState::SetProcessedTimingData(), Step(), Style::StyleInputToGameInput(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_Mine, TapNoteResult::tns, TNS_None, NoteData::_all_tracks_iterator< ND, iter, TN >::Track(), and TapNote::type.
Referenced by Update().
DoTapScoreNone()
void Player::DoTapScoreNone ()
References BeatToNoteRow(), MessageManager::Broadcast(), LifeMeter::HandleTapScoreNone(), ScoreKeeper::HandleTapScoreNone(), SongPosition::m_fSongBeat, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, m_pLifeMeter, PlayerState::m_Position, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pSecondaryScoreKeeper, MESSAGEMAN, PENALIZE_TAP_SCORE_NONE, SendComboMessages(), SetJudgment(), TAP_EMPTY, and TNS_Miss.
Referenced by Step().
DrawHoldJudgments()
void Player::DrawHoldJudgments () protected
References ModsGroup< T >::GetCurrent(), NoteData::GetNumTracks(), PlayerOptions::m_fBlind, m_NoteData, PlayerState::m_PlayerOptions, m_pPlayerState, and m_vpHoldJudgment.
Referenced by DrawPrimitives().
DrawNoteFieldBoard()
void Player::DrawNoteFieldBoard ()
References Actor::Draw(), and m_drawing_notefield_board.
DrawPrimitives()
void Player::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from ActorFrame.
References COMBO_UNDER_FIELD, curr_options, Actor::Draw(), NoteField::DrawBoardPrimitive(), DrawHoldJudgments(), DrawTapJudgments(), PlayerOptions::EFFECT_MINI, GAMESTATE, ModsGroup< T >::GetCurrent(), GameState::GetCurrentStyle(), GameState::GetMasterPlayerNumber(), GetPlayerState(), PlayerOptions::GetReversePercentForColumn(), Actor::GetX(), Actor::GetY(), GRAY_ARROWS_Y_REVERSE, GRAY_ARROWS_Y_STANDARD, HOLD_JUDGMENTS_UNDER_FIELD, IsOniDead(), m_drawing_notefield_board, PlayerOptions::m_fBlind, PlayerOptions::m_fEffects, PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pNoteField, m_pPlayerState, m_sprCombo, Style::m_StyleType, StyleType_OnePlayerTwoSides, and TAP_JUDGMENTS_UNDER_FIELD.
DrawTapJudgments()
void Player::DrawTapJudgments () protected
References Actor::Draw(), ModsGroup< T >::GetCurrent(), PlayerOptions::m_fBlind, PlayerState::m_PlayerOptions, m_pPlayerState, and m_sprJudgment.
Referenced by DrawPrimitives().
FadeToFail()
void Player::FadeToFail ()
References NoteField::FadeToFail(), m_pNoteField, and SetCombo().
Referenced by ScreenGameplay::FailFadeRemovePlayer().
FlashGhostRow()
void Player::FlashGhostRow (int iRow) protected
References TapNoteResult::bHidden, BRIGHT_GHOST_COMBO_THRESHOLD, NoteField::DidTapNote(), ModsGroup< T >::GetCurrent(), NoteData::GetNumTracks(), NoteData::GetTapNote(), HideNote(), NoteDataWithScoring::LastTapNoteWithResult(), PlayerOptions::m_fBlind, PlayerStageStats::m_iCurCombo, PlayerOptions::m_MinTNSToHideNotes, m_NoteData, PlayerState::m_PlayerOptions, m_pNoteField, m_pPlayerStageStats, m_pPlayerState, TapNote::result, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Mine, TapNoteResult::tns, and TapNote::type.
Referenced by Step().
GetClosestNonEmptyRow()
int Player::GetClosestNonEmptyRow (int iNoteRow, int iMaxRowsAhead, int iMaxRowsBehind, bool bAllowGraded) const protected
References GetClosestNonEmptyRowDirectional(), SongPosition::m_fMusicSeconds, PlayerState::m_Position, m_pPlayerState, m_Timing, and TimingData::WhereUAtBro().
GetClosestNonEmptyRowDirectional()
int Player::GetClosestNonEmptyRowDirectional (int iStartRow, int iMaxRowsAhead, bool bAllowGraded, bool bForward) const protected
References NoteData::GetTapNoteRangeAllTracks(), NoteData::GetTapNoteRangeAllTracksReverse(), NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), TimingData::IsJudgableAtRow(), NoteDataWithScoring::IsRowCompletelyJudged(), m_NoteData, m_Timing, and NoteData::_all_tracks_iterator< ND, iter, TN >::Row().
Referenced by GetClosestNonEmptyRow().
GetClosestNote()
int Player::GetClosestNote (int col, int iNoteRow, int iMaxRowsAhead, int iMaxRowsBehind, bool bAllowGraded) const protected
References GetClosestNoteDirectional(), SongPosition::m_fMusicSeconds, PlayerState::m_Position, m_pPlayerState, m_Timing, and TimingData::WhereUAtBro().
Referenced by Step().
GetClosestNoteDirectional()
int Player::GetClosestNoteDirectional (int col, int iStartRow, int iMaxRowsAhead, bool bAllowGraded, bool bForward) const protected
References NoteData::GetTapNoteRange(), TimingData::IsJudgableAtRow(), m_NoteData, m_Timing, TapNote::result, swap(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteResult::tns, TNS_None, and TapNote::type.
Referenced by GetClosestNote().
GetLastTapNoteScore()
TapNoteScore Player::GetLastTapNoteScore () const inline
References m_LastTapNoteScore.
GetMaxStepDistanceSeconds()
float Player::GetMaxStepDistanceSeconds () static
References f, GAMESTATE, ModsGroup< T >::GetCurrent(), GetWindowSeconds(), m_fMaxInputLatencySeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, max(), TW_W1, TW_W2, TW_W3, TW_W4, and TW_W5.
Referenced by ScreenGameplay::GetMusicEndTiming(), Step(), Update(), and UpdateJudgedRows().
GetNoteData()
const NoteData& Player::GetNoteData () const inline
References m_NoteData.
Referenced by ScreenGameplay::PlayTicks().
GetPlayerState()
PlayerState* Player::GetPlayerState () inline
References m_pPlayerState.
Referenced by CrossedRows(), DrawPrimitives(), Init(), Load(), ScreenGameplay::PlayTicks(), Update(), and UpdateHoldNotes().
GetPlayerTimingData()
TimingData Player::GetPlayerTimingData () const inline
Retrieve the Player's TimingData.
This is primarily for a lua hook.
Returns
the TimingData in question.
References m_Timing.
Referenced by LunaPlayer::GetPlayerTimingData(), and LunaPlayer::LunaPlayer().
GetWindowSeconds()
float Player::GetWindowSeconds (TimingWindow tw) static
References m_fTimingWindowAdd, m_fTimingWindowScale, and m_fTimingWindowSeconds.
Referenced by GetMaxStepDistanceSeconds(), PlayerAI::GetTapNoteScoreForReplay(), Step(), and UpdateHoldNotes().
HandleHoldCheckpoint()
void Player::HandleHoldCheckpoint (int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow, const vector< int > & viColsWithHold) protected
References BRIGHT_GHOST_COMBO_THRESHOLD, ChangeLife(), CHECKPOINTS_FLASH_ON_HOLD, NoteField::DidHoldNote(), FOREACH_CONST, ScoreKeeper::HandleHoldCheckpointScore(), HNS_Held, TimingData::IsJudgableAtRow(), StatsManager::m_CurStageStats, StageStats::m_fStepsSeconds, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, m_NoteData, PlayerState::m_PlayerController, m_pNoteField, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pSecondaryScoreKeeper, m_Timing, PC_AUTOPLAY, SendComboMessages(), SetCombo(), SetJudgment(), STATSMAN, TAP_EMPTY, TNS_CheckpointHit, TNS_CheckpointMiss, and PlayerStageStats::UpdateComboList().
Referenced by CrossedRows().
HandleHoldScore()
void Player::HandleHoldScore (const TapNote & tn) protected
References ChangeLife(), GAMESTATE, ScoreKeeper::HandleHoldScore(), HoldNoteResult::hns, TapNote::HoldResult, GameState::m_bDemonstrationOrJukebox, PlayerStageStats::m_iScore, PlayerState::m_PlayerController, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pScoreDisplay, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, ScoreDisplay::OnJudgment(), PC_AUTOPLAY, TapNote::result, ScoreDisplay::SetScore(), and TapNoteResult::tns.
Referenced by ScoreAllActiveHoldsLetGo(), and UpdateHoldNotes().
HandleTapRowScore()
void Player::HandleTapRowScore (unsigned row) protected
References ChangeLife(), CROSSED, GAMESTATE, NoteData::GetNumTracks(), NoteData::GetTapNote(), ScoreKeeper::HandleTapRowScore(), ScoreKeeper::HandleTapScore(), NoteDataWithScoring::LastTapNoteWithResult(), GameState::m_bDemonstrationOrJukebox, StatsManager::m_CurStageStats, StageStats::m_fStepsSeconds, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, PlayerStageStats::m_iMaxCombo, PlayerStageStats::m_iScore, m_LastTapNoteScore, m_NoteData, PlayerState::m_PlayerController, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pScoreDisplay, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, max(), ScoreDisplay::OnJudgment(), PC_AUTOPLAY, ScreenManager::PostMessageToTopScreen(), TapNote::result, SCREENMAN, SendComboMessages(), SetCombo(), ScoreDisplay::SetScore(), STATSMAN, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Mine, TapNoteResult::tns, TNS_Miss, TapNote::type, and PlayerStageStats::UpdateComboList().
Referenced by Step(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
HasVisibleParts()
bool Player::HasVisibleParts () const inline
References m_pNoteField.
Referenced by Init(), and Update().
HideNote()
void Player::HideNote (int col, int row) inline protected
References NoteData::end(), NoteData::FindTapNote(), and m_NoteData.
Referenced by FlashGhostRow(), and Step().
IncrementCombo()
void Player::IncrementCombo () inline protected
References IncrementComboOrMissCombo().
Referenced by Step().
IncrementComboOrMissCombo()
void Player::IncrementComboOrMissCombo (bool bComboOrMissCombo) protected
References PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, m_pPlayerStageStats, SendComboMessages(), and SetCombo().
Referenced by IncrementCombo(), and IncrementMissCombo().
IncrementMissCombo()
void Player::IncrementMissCombo () inline protected
References IncrementComboOrMissCombo().
Referenced by UpdateHoldNotes().
Init()
void Player::Init (const RString & sType, PlayerState * pPlayerState, PlayerStageStats * pPlayerStageStats, LifeMeter * pLM, ScoreDisplay * pScoreDisplay, ScoreDisplay * pSecondaryScoreDisplay, ScoreKeeper * pPrimaryScoreKeeper, ScoreKeeper * pSecondaryScoreKeeper)
References ActorFrame::AddChild(), ASSERT, BRIGHT_GHOST_COMBO_THRESHOLD, COMBO_UNDER_FIELD, LuaReference::Create(), Actor::DestTweenState(), DRAW_DISTANCE_AFTER_TARGET_PIXELS, DRAW_DISTANCE_BEFORE_TARGET_PIXELS, FOREACH, FOREACH_EnabledMultiPlayer, FOREACH_EnabledPlayer, GAMESTATE, TimingData::GetActualBPM(), GameState::GetCurrentStyle(), Song::GetDisplayBpms(), LifeMeter::GetLife(), DisplayBpms::GetMax(), DisplayBpms::GetMaxWithin(), ThemeManager::GetPathG(), ThemeManager::GetPathS(), GameSoundManager::GetPlayerBalance(), GetPlayerState(), Style::GetUsesCenteredArrows(), GRAY_ARROWS_Y_REVERSE, GRAY_ARROWS_Y_STANDARD, Actor::HandleMessage(), HasVisibleParts(), HOLD_JUDGMENT_Y_REVERSE, HOLD_JUDGMENT_Y_STANDARD, HOLD_JUDGMENTS_UNDER_FIELD, NoteField::Init(), DisplayBpms::IsSecret(), HoldJudgment::Load(), AutoActor::Load(), ThemeMetric< T >::Load(), RageSound::Load(), ActorUtil::LoadAllCommands(), ActorUtil::LoadCommand(), GameState::m_bMultiplayer, m_bSeenComboYet, RageSoundLoadParams::m_bSupportPan, StatsManager::m_CurStageStats, m_fNoteFieldHeight, PlayerState::m_fReadBPM, StageStats::m_fStepsSeconds, Style::m_iColsPerPlayer, m_iLastSeenCombo, M_MOD_HIGH_CAP, PlayerState::m_mp, m_pActorWithComboPosition, m_pActorWithJudgmentPosition, GameState::m_pCurSong, PlayerState::m_PlayerNumber, m_pLifeMeter, m_pNoteField, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pScoreDisplay, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, Song::m_SongTiming, m_soundMine, m_sprCombo, m_sprJudgment, m_tsCombo, m_tsJudgment, m_vbFretIsDown, m_vpHoldJudgment, max(), NUM_CENTERED, NUM_REVERSE, PlayerStageStats::SetLifeRecordAt(), Actor::SetName(), PlayerState::SetNumCols(), Message::SetParam(), RageSound::SetProperty(), ActorFrame::SortByDrawOrder(), STATSMAN, TAP_JUDGMENTS_UNDER_FIELD, and THEME.
Referenced by ScreenHowToPlay::Init().
IsOniDead()
bool Player::IsOniDead () const
References ModsGroup< T >::GetStage(), LifeType_Battery, PlayerStageStats::m_bFailed, PlayerOptions::m_LifeType, PlayerState::m_PlayerOptions, m_pPlayerStageStats, and m_pPlayerState.
Referenced by DrawPrimitives(), Step(), and Update().
Load()
void Player::Load ()
References BeatToNoteRow(), TimingData::BuildAndGetEtaner(), TimingData::BuildAndGetEtar(), curwifescore, DRAW_DISTANCE_AFTER_TARGET_PIXELS, DRAW_DISTANCE_BEFORE_TARGET_PIXELS, GAMESTATE, GenerateCacheDataStructure(), ScoreManager::GetChartPBAt(), ModsGroup< T >::GetCurrent(), GameState::GetCurrentGame(), GameState::GetCurrentStyle(), NoteData::GetLastRow(), RageSound::GetLoadedFilePath(), NoteData::GetNonEmptyRowVector(), GameSoundManager::GetPlayerBalance(), GetPlayerState(), ModsGroup< T >::GetStage(), NoteData::GetTapNoteRangeAllTracks(), HighScore::GetWifeScore(), GRAY_ARROWS_Y_REVERSE, GRAY_ARROWS_Y_STANDARD, TimingData::HasWarps(), GameState::IsEditing(), LifeType_Battery, NoteField::Load(), RageSound::Load(), NoteData::LogNonEmptyRows(), PlayerStageStats::m_bFailed, m_bLoaded, RageSoundLoadParams::m_bSupportPan, Game::m_bTickHolds, m_bTickHolds, SongOptions::m_fMusicRate, SongPosition::m_fSongBeat, m_fTimingWindowScale, m_iFirstUncrossedRow, m_LastTapNoteScore, PlayerOptions::m_LifeType, m_NoteData, GameState::m_pCurSong, GameState::m_pCurSteps, m_pIterNeedsHoldJudging, m_pIterNeedsTapJudging, m_pIterUncrossedRows, m_pIterUnjudgedMineRows, m_pIterUnjudgedRows, m_pJudgedRows, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pNoteField, PlayerState::m_Position, m_pPlayerStageStats, m_pPlayerState, GameState::m_SongOptions, m_sprJudgment, Style::m_StepsType, m_Timing, m_vKeysounds, MAX_NOTE_ROW, maxwifescore, TimingData::NegStopAndBPMCheck(), nerv, Actor::PlayCommand(), PlayerState::playertargetgoal, RadarCategory_Holds, RadarCategory_Mines, RadarCategory_Rolls, JudgedRows::Reset(), SAFE_DELETE, SCOREMAN, SendComboMessages(), NoteData::SerializeNoteData(), SetCombo(), RageSound::SetProperty(), RageSound::SetStopModeFromString(), Actor::SetY(), TNS_None, totalwifescore, NoteDataUtil::TransformNoteData(), NoteData::UnsetSerializedNoteData(), TimingData::ValidSequentialAssumption, wifescorepersonalbest, and NoteData::WifeTotalScoreCalc().
Referenced by PlayerPlus::Load().
PlayKeysound()
void Player::PlayKeysound (const TapNote & tn, TapNoteScore score) protected
References Preference< T >::Get(), Preference< T >::GetPreferenceByName(), HoldNoteResult::hns, HNS_None, TapNote::HoldResult, TapNote::iKeysoundIndex, m_vKeysounds, TapNote::result, TapNoteType_HoldHead, TapNoteResult::tns, TNS_Miss, TNS_None, and TapNote::type.
Referenced by CrossedRows(), and Step().
PopPlayerMatrix()
void Player::PopPlayerMatrix ()
References RageDisplay::CameraPopMatrix(), DISPLAY, and RageDisplay::PopMatrix().
PushPlayerMatrix()
void Player::PushPlayerMatrix (float x, float skew, float center_y)
References RageDisplay::CameraPushMatrix(), DISPLAY, f, RageDisplay::LoadMenuPerspective(), RageDisplay::PushMatrix(), SCALE, SCREEN_CENTER_X, SCREEN_HEIGHT, and SCREEN_WIDTH.
Referenced by Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner().
PushSelf()
void Player::PushSelf (lua_State * L) override virtual
Reimplemented from ActorFrame.
RenderAllNotesIgnoreScores()
void Player::RenderAllNotesIgnoreScores ()
References DEBUG_ASSERT, NoteField::DrawPrimitives(), NoteData::end(), NoteData::FindTapNote(), FOREACH_NONEMPTY_ROW_ALL_TRACKS, NoteData::GetLastRow(), NoteData::GetNumTracks(), HoldNoteResult::hns, HNS_None, TapNote::HoldResult, m_NoteData, m_pNoteField, TapNoteType_Empty, TapNoteType_HoldHead, and TNS_None.
ScoreAllActiveHoldsLetGo()
void Player::ScoreAllActiveHoldsLetGo ()
References HoldNoteResult::bActive, BeatToNoteRow(), HoldNoteResult::fLife, NoteData::GetNumTracks(), NoteData::GetTapNoteRangeInclusive(), HandleHoldScore(), HoldNoteResult::hns, HNS_LetGo, TapNote::HoldResult, SongPosition::m_fSongBeat, m_NoteData, PlayerState::m_Position, m_pPlayerState, max(), PENALIZE_TAP_SCORE_NONE, and SetHoldJudgment().
SendComboMessages()
void Player::SendComboMessages (unsigned int iOldCombo, unsigned int iOldMissCombo) protected
References MessageManager::Broadcast(), COMBO_STOPPED_AT, LuaReference::CreateFromPush(), m_bSendJudgmentAndComboMessages, PlayerStageStats::m_iCurCombo, PlayerState::m_PlayerNumber, m_pPlayerStageStats, m_pPlayerState, MESSAGEMAN, ScreenManager::PostMessageToTopScreen(), SCREENMAN, and Message::SetParam().
Referenced by DoTapScoreNone(), HandleHoldCheckpoint(), HandleTapRowScore(), IncrementComboOrMissCombo(), and Load().
SetActorWithComboPosition()
void Player::SetActorWithComboPosition (Actor * pActor) inline
References m_pActorWithComboPosition.
Referenced by LunaPlayer::LunaPlayer(), and LunaPlayer::SetActorWithComboPosition().
SetActorWithJudgmentPosition()
void Player::SetActorWithJudgmentPosition (Actor * pActor) inline
References m_pActorWithJudgmentPosition.
Referenced by LunaPlayer::LunaPlayer(), and LunaPlayer::SetActorWithJudgmentPosition().
SetCombo()
void Player::SetCombo (unsigned int iCombo, unsigned int iMisses) protected
References PlayerStageStats::FullComboOfScore(), GAMESTATE, ActorFrame::HandleMessage(), m_bSeenComboYet, m_bSendJudgmentAndComboMessages, Song::m_fMusicLengthSeconds, SongPosition::m_fMusicSeconds, m_iLastSeenCombo, GameState::m_pCurSong, PlayerState::m_Position, m_pPlayerStageStats, m_pPlayerState, MILESTONE_CHECK, PERCENT_UNTIL_COLOR_COMBO, Actor::PlayCommand(), Message::SetParam(), TNS_W1, TNS_W2, TNS_W3, and TNS_W4.
Referenced by FadeToFail(), HandleHoldCheckpoint(), HandleTapRowScore(), IncrementComboOrMissCombo(), Load(), and SetMineJudgment().
SetHoldJudgment()
void Player::SetHoldJudgment (TapNote & tn, int iTrack, int iRow) protected
References AddHoldToReplayData(), ASSERT, MessageManager::Broadcast(), ChangeWifeRecord(), PlayerStageStats::CurWifeScore, curwifescore, LuaManager::Get(), HoldNoteResult::hns, HNS_LetGo, HNS_Missed, TapNote::HoldResult, L, LUA, m_bSendJudgmentAndComboMessages, PlayerStageStats::m_fWifeScore, PlayerStageStats::m_iHoldNoteScores, PlayerState::m_mp, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, m_pPlayerStageStats, m_pPlayerState, m_vpHoldJudgment, PlayerStageStats::MaxWifeScore, maxwifescore, MESSAGEMAN, PC_HUMAN, PlayerState::playertargetgoal, TapNote::PushSelf(), LuaManager::Release(), TapNote::result, Message::SetParam(), Message::SetParamFromStack(), TapNoteResult::tns, totalwifescore, and wifescorepersonalbest.
Referenced by ScoreAllActiveHoldsLetGo(), and UpdateHoldNotes().
SetJudgment() [1/2]
void Player::SetJudgment (int iRow, int iFirstTrack, const TapNote & tn) inline protected
References TapNoteResult::fTapNoteOffset, TapNote::result, and TapNoteResult::tns.
Referenced by DoTapScoreNone(), HandleHoldCheckpoint(), Step(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
SetJudgment() [2/2]
void Player::SetJudgment (int iRow, int iFirstTrack, const TapNote & tn, TapNoteScore tns, float fTapNoteOffset) protected
References AddNoteToReplayData(), MessageManager::Broadcast(), ChangeWifeRecord(), GameState::CountNotesSeparately(), PlayerStageStats::CurWifeScore, curwifescore, NoteData::end(), f, NoteData::FindTapNote(), TapNoteResult::fTapNoteOffset, GAMESTATE, LuaManager::Get(), NoteData::GetNumTracks(), hold, NoteData::IsHoldNoteAtRow(), L, LUA, m_bSendJudgmentAndComboMessages, m_fTimingWindowScale, PlayerStageStats::m_fWifeScore, PlayerStageStats::m_iTapNoteScores, PlayerState::m_mp, m_NoteData, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, m_pPlayerStageStats, m_pPlayerState, PlayerStageStats::m_vNoteRowVector, PlayerStageStats::m_vOffsetVector, PlayerStageStats::MaxWifeScore, maxwifescore, MESSAGEMAN, PC_HUMAN, PC_REPLAY, PlayerState::playertargetgoal, LuaManager::Release(), TapNote::result, Message::SetParam(), Message::SetParamFromStack(), TNS_Miss, totalwifescore, wife2(), and wifescorepersonalbest.
SetLife()
void Player::SetLife (float value)
References ChangeLifeRecord(), m_pLifeMeter, and LifeMeter::SetLife().
Referenced by LunaPlayer::LunaPlayer(), and LunaPlayer::SetLife().
SetMineJudgment()
void Player::SetMineJudgment (TapNoteScore tns, int iTrack) protected
References AVOID_MINE_INCREMENTS_COMBO, MessageManager::Broadcast(), ChangeWifeRecord(), PlayerStageStats::CurWifeScore, curwifescore, f, m_bSendJudgmentAndComboMessages, PlayerStageStats::m_fWifeScore, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, m_pPlayerStageStats, m_pPlayerState, PlayerStageStats::MaxWifeScore, maxwifescore, MESSAGEMAN, MINE_HIT_INCREMENTS_MISS_COMBO, PC_HUMAN, PC_REPLAY, PlayerState::playertargetgoal, SetCombo(), Message::SetParam(), TNS_AvoidMine, TNS_HitMine, totalwifescore, and wifescorepersonalbest.
Referenced by UpdateJudgedRows().
SetPaused()
void Player::SetPaused (bool bPaused) inline
References m_bPaused.
SetSendJudgmentAndComboMessages()
void Player::SetSendJudgmentAndComboMessages (bool b) inline
References m_bSendJudgmentAndComboMessages.
Step()
void Player::Step (int col, int row, const std::chrono::steady_clock::time_point & tm, bool bHeld, bool bRelease, float padStickSeconds = 0.0f)
References AddNoteToReplayData(), RageTimer::Ago(), BeatToNoteRow(), BRIGHT_GHOST_COMBO_THRESHOLD, MessageManager::Broadcast(), GameState::CountNotesSeparately(), DEBUG_ASSERT, DEFAULT_FAIL, NoteField::DidHoldNote(), NoteField::DidTapNote(), DoTapScoreNone(), NoteData::end(), f, FAIL_M, NoteData::FindTapNote(), FlashGhostRow(), HoldNoteResult::fLife, GAMESTATE, TimingData::GetBeatFromElapsedTime(), GetClosestNote(), ModsGroup< T >::GetCurrent(), GameState::GetCurrentGame(), GetMaxStepDistanceSeconds(), GetNoteType(), NoteData::GetTapNote(), PlayerAI::GetTapNoteOffsetForReplay(), NoteData::GetTapNoteRangeInclusive(), PlayerAI::GetTapNoteScore(), PlayerAI::GetTapNoteScoreForReplay(), GetWindowSeconds(), AdjustSync::HandleAutosync(), HandleTapRowScore(), HideNote(), HoldNoteResult::hns, HNS_Held, HNS_None, TapNote::HoldResult, TapNote::iDuration, HoldNoteResult::iLastHeldRow, IncrementCombo(), NoteData::IsHoldNoteAtRow(), TimingData::IsJudgableAtRow(), IsOniDead(), NoteDataWithScoring::IsRowCompletelyJudged(), NoteData::IsThereATapOrHoldHeadAtRow(), PlayerOptions::m_fBlind, SongOptions::m_fMusicRate, SongPosition::m_fMusicSeconds, SongPosition::m_fSongBeat, PlayerStageStats::m_iCurCombo, SongPosition::m_LastBeatUpdate, m_LastTapNoteScore, PlayerOptions::m_MinTNSToHideNotes, PlayerState::m_mp, m_NoteData, GameState::m_pCurSteps, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pNoteField, PlayerState::m_Position, m_pPlayerStageStats, m_pPlayerState, GameState::m_SongOptions, m_Timing, Game::MapTapNoteScore(), max(), MAX_NOTE_ROW, MESSAGEMAN, min(), nerv, nervpos, NoteRowToBeat(), NOTESKIN, NoteTypeToString(), PC_AUTOPLAY, PC_CPU, PC_HUMAN, PC_REPLAY, PlayKeysound(), randomf(), REQUIRE_STEP_ON_HOLD_HEADS, REQUIRE_STEP_ON_MINES, TapNote::result, ROLL_BODY_INCREMENTS_COMBO, ROWS_PER_BEAT, SetJudgment(), NoteSkinManager::SetLastSeenColor(), Message::SetParam(), GameState::ShowW1(), ssprintf(), NoteField::Step(), TapNote::subType, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Mine, TapNoteResult::tns, TNS_HitMine, TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, TW_Mine, TW_W1, TW_W2, TW_W3, TW_W4, TW_W5, TapNote::type, and TimingData::WhereUAtBro().
Referenced by CrossedRows(), ScreenGameplay::Input(), and Update().
Update()
void Player::Update (float fDeltaTime) override virtual
Reimplemented from Actor.
References ASSERT, ASSERT_M, BeatToNoteRow(), CrossedRows(), DEFAULT_FAIL, Actor::DestTweenState(), PlayerOptions::EFFECT_MINI, PlayerOptions::EFFECT_TINY, PlayerStageStats::everusedautoplay, f, HoldNoteResult::fLife, GAMESTATE, ModsGroup< T >::GetCurrent(), GameState::GetCurrentStyle(), GetMaxStepDistanceSeconds(), NoteData::GetNumTracks(), GetPlayerState(), PlayerOptions::GetReversePercentForColumn(), NoteData::GetTapNote(), ArrowEffects::GetXPos(), Actor::GetZoom(), ArrowEffects::GetZPos(), HasVisibleParts(), HoldNoteResult::hns, HNS_None, HOLD_JUDGMENT_Y_REVERSE, HOLD_JUDGMENT_Y_STANDARD, TapNote::HoldResult, INPUTMAPPER, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), InputMapper::IsBeingPressed(), NoteData::IsHoldNoteAtRow(), IsOniDead(), GameState::IsPlayerEnabled(), JUDGE_HOLD_NOTES_ON_SAME_ROW_TOGETHER, SongPosition::m_bDelay, m_bDelay, GameState::m_bDemonstrationOrJukebox, PlayerStageStats::m_bDisqualified, m_bLoaded, m_bPaused, StageStats::m_bUsedAutoplay, StatsManager::m_CurStageStats, PlayerOptions::m_fEffects, PlayerOptions::m_fScrolls, SongPosition::m_fSongBeat, Style::m_iColsPerPlayer, PlayerState::m_mp, m_NoteData, m_pActorWithComboPosition, m_pActorWithJudgmentPosition, GameState::m_pCurSong, m_pIterNeedsHoldJudging, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pNoteField, PlayerState::m_Position, m_pPlayerStageStats, m_pPlayerState, m_tsCombo, m_tsJudgment, m_vpHoldJudgment, Actor::TweenState::MakeWeightedAverage(), MAX_COLS_PER_PLAYER, min(), MultiPlayer_Invalid, NeedsHoldJudging(), PC_AUTOPLAY, PC_HUMAN, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), SCALE, PlayerOptions::SCROLL_CENTERED, ArrowEffects::SetCurrentOptions(), NoteField::SetPressed(), Actor::SetZoom(), ssprintf(), STATSMAN, Step(), Style::StyleInputToGameInput(), TapNote::subType, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_HoldHead, NoteData::_all_tracks_iterator< ND, iter, TN >::Track(), TapNote::type, Actor::Update(), UpdateHoldNotes(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
UpdateHoldNotes()
void Player::UpdateHoldNotes (int iSongRow, float fDeltaTime, vector< TrackRowTapNote > & vTN)
References ASSERT, HoldNoteResult::bActive, HoldNoteResult::bHeld, BRIGHT_GHOST_COMBO_THRESHOLD, COMBO_BREAK_ON_IMMEDIATE_HOLD_LET_GO, DEFAULT_FAIL, PlayerAI::DetermineIfHoldDropped(), NoteField::DidHoldNote(), PlayerStageStats::everusedautoplay, f, FAIL_M, HoldNoteResult::fLife, FOREACH, HoldNoteResult::fOverlappedTime, GAMESTATE, Preference< T >::Get(), ModsGroup< T >::GetCurrent(), GameState::GetCurrentStyle(), GetPlayerState(), Preference< T >::GetPreferenceByName(), GetWindowSeconds(), ScoreKeeper::HandleHoldActiveSeconds(), HandleHoldScore(), HoldNoteResult::hns, HNS_Held, HNS_LetGo, HNS_Missed, HNS_None, TapNote::HoldResult, TapNote::iDuration, TapNote::iKeysoundIndex, IMMEDIATE_HOLD_LET_GO, IncrementMissCombo(), INPUTMAPPER, InputMapper::IsBeingPressed(), GamePreferences::m_AutoPlay, PlayerStageStats::m_bDisqualified, m_bTickHolds, StageStats::m_bUsedAutoplay, StatsManager::m_CurStageStats, SongOptions::m_fMusicRate, PlayerStageStats::m_iCurCombo, PlayerState::m_mp, PlayerState::m_PlayerController, PlayerState::m_PlayerNumber, m_pNoteField, m_pPlayerStageStats, m_pPlayerState, m_pPrimaryScoreKeeper, m_pSecondaryScoreKeeper, GameState::m_SongOptions, m_vKeysounds, max(), MAX_HOLD_LIFE, min(), PC_AUTOPLAY, PC_HUMAN, PC_REPLAY, REQUIRE_STEP_ON_HOLD_HEADS, TapNote::result, SCORE_MISSED_HOLDS_AND_ROLLS, SetHoldJudgment(), ssprintf(), STATSMAN, Style::StyleInputToGameInput(), TapNote::subType, TapNoteSubType_Hold, TapNoteSubType_Invalid, TapNoteSubType_Roll, TapNoteResult::tns, TNS_Miss, TNS_None, TW_Checkpoint, TW_Hold, TW_Roll, and window.
Referenced by Update().
UpdateJudgedRows()
void Player::UpdateJudgedRows (float fDeltaTime) protected
References BeatToNoteRow(), TapNoteResult::bHidden, ChangeLife(), GameState::CountNotesSeparately(), DEFAULT_FAIL, NoteField::DidTapNote(), FOREACHS, g_bEnableMineSoundPlayback, GAMESTATE, TimingData::GetBeatFromElapsedTime(), NoteData::GetFirstTrackWithTapOrHoldHead(), GetMaxStepDistanceSeconds(), HandleTapRowScore(), ScoreKeeper::HandleTapScore(), TapNote::iKeysoundIndex, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), TimingData::IsJudgableAtRow(), NoteDataWithScoring::IsRowCompletelyJudged(), JudgedRows::JudgeRow(), NoteDataWithScoring::LastTapNoteWithResult(), SongPosition::m_fMusicSeconds, m_NoteData, m_pIterUnjudgedMineRows, m_pIterUnjudgedRows, m_pJudgedRows, m_pNoteField, PlayerState::m_Position, m_pPlayerState, m_pPrimaryScoreKeeper, m_pScoreDisplay, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, m_soundMine, m_Timing, m_vKeysounds, ScoreDisplay::OnJudgment(), TapNote::result, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), SetJudgment(), SetMineJudgment(), TapNoteType_Mine, TapNoteResult::tns, TNS_AvoidMine, TNS_HitMine, TNS_Miss, TNS_None, NoteData::_all_tracks_iterator< ND, iter, TN >::Track(), and TapNote::type.
Referenced by Update().
UpdateTapNotesMissedOlderThan()
void Player::UpdateTapNotesMissedOlderThan (float fMissIfOlderThanThisBeat) protected
References TimingData::GetBeatArgs::beat, BeatToNoteRow(), GameState::CountNotesSeparately(), TimingData::GetBeatArgs::delay_out, TimingData::GetBeatArgs::elapsed_time, TimingData::GetBeatArgs::freeze_out, GAMESTATE, TimingData::GetBeatAndBPSFromElapsedTime(), HandleTapRowScore(), ScoreKeeper::HandleTapScore(), NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), TimingData::IsJudgableAtRow(), SongPosition::m_fMusicSeconds, m_pIterNeedsTapJudging, PlayerState::m_Position, m_pPlayerState, m_pPrimaryScoreKeeper, m_pSecondaryScoreKeeper, m_Timing, NeedsTapJudging(), TapNote::result, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), SetJudgment(), TapNoteType_Mine, TapNoteResult::tns, TNS_AvoidMine, TNS_Miss, NoteData::_all_tracks_iterator< ND, iter, TN >::Track(), and TapNote::type.
Referenced by Update().
Member Data Documentation
BRIGHT_GHOST_COMBO_THRESHOLD
ThemeMetric<int> Player::BRIGHT_GHOST_COMBO_THRESHOLD protected
Referenced by FlashGhostRow(), HandleHoldCheckpoint(), Init(), Step(), and UpdateHoldNotes().
COMBO_UNDER_FIELD
ThemeMetric<bool> Player::COMBO_UNDER_FIELD protected
Referenced by DrawPrimitives(), and Init().
curwifescore
float Player::curwifescore = 0.f
Referenced by ChangeWifeRecord(), Load(), SetHoldJudgment(), SetJudgment(), and SetMineJudgment().
DRAW_DISTANCE_AFTER_TARGET_PIXELS
ThemeMetric<int> Player::DRAW_DISTANCE_AFTER_TARGET_PIXELS protected
Referenced by Init(), and Load().
DRAW_DISTANCE_BEFORE_TARGET_PIXELS
ThemeMetric<int> Player::DRAW_DISTANCE_BEFORE_TARGET_PIXELS protected
Referenced by Init(), and Load().
GRAY_ARROWS_Y_REVERSE
ThemeMetric<float> Player::GRAY_ARROWS_Y_REVERSE protected
Referenced by DrawPrimitives(), Init(), and Load().
GRAY_ARROWS_Y_STANDARD
ThemeMetric<float> Player::GRAY_ARROWS_Y_STANDARD protected
Referenced by DrawPrimitives(), Init(), and Load().
HOLD_JUDGMENT_Y_REVERSE
ThemeMetric<float> Player::HOLD_JUDGMENT_Y_REVERSE protected
Referenced by Init(), and Update().
HOLD_JUDGMENT_Y_STANDARD
ThemeMetric<float> Player::HOLD_JUDGMENT_Y_STANDARD protected
Referenced by Init(), and Update().
HOLD_JUDGMENTS_UNDER_FIELD
ThemeMetric<bool> Player::HOLD_JUDGMENTS_UNDER_FIELD protected
Referenced by DrawPrimitives(), and Init().
m_bDelay
bool Player::m_bDelay protected
Referenced by Player(), and Update().
m_bLoaded
bool Player::m_bLoaded protected
Referenced by Load(), Player(), and Update().
m_bPaused
bool Player::m_bPaused protected
Referenced by Player(), SetPaused(), and Update().
m_bSeenComboYet
bool Player::m_bSeenComboYet protected
Referenced by Init(), and SetCombo().
m_bSendJudgmentAndComboMessages
bool Player::m_bSendJudgmentAndComboMessages protected
Referenced by Player(), SendComboMessages(), SetCombo(), SetHoldJudgment(), SetJudgment(), SetMineJudgment(), and SetSendJudgmentAndComboMessages().
m_bTickHolds
bool Player::m_bTickHolds protected
Referenced by CrossedRows(), Load(), and UpdateHoldNotes().
m_drawing_notefield_board
bool Player::m_drawing_notefield_board protected
Referenced by DrawNoteFieldBoard(), DrawPrimitives(), and Player().
m_fNoteFieldHeight
float Player::m_fNoteFieldHeight protected
Referenced by Init(), and Player().
m_iFirstUncrossedRow
int Player::m_iFirstUncrossedRow protected
Referenced by CrossedRows(), and Load().
m_iLastSeenCombo
unsigned int Player::m_iLastSeenCombo protected
Referenced by Init(), and SetCombo().
m_inside_lua_set_life
bool Player::m_inside_lua_set_life
Referenced by LunaPlayer::ChangeLife(), Player(), and LunaPlayer::SetLife().
m_LastTapNoteScore
TapNoteScore Player::m_LastTapNoteScore protected
Referenced by GetLastTapNoteScore(), HandleTapRowScore(), Load(), and Step().
m_NoteData
NoteData& Player::m_NoteData protected
Referenced by CrossedRows(), DrawHoldJudgments(), FlashGhostRow(), GetClosestNonEmptyRowDirectional(), GetClosestNoteDirectional(), GetNoteData(), HandleHoldCheckpoint(), HandleTapRowScore(), HideNote(), Load(), RenderAllNotesIgnoreScores(), ScoreAllActiveHoldsLetGo(), SetJudgment(), Step(), Update(), and UpdateJudgedRows().
m_pActorWithComboPosition
Actor* Player::m_pActorWithComboPosition protected
Referenced by Init(), SetActorWithComboPosition(), and Update().
m_pActorWithJudgmentPosition
Actor* Player::m_pActorWithJudgmentPosition protected
Referenced by Init(), SetActorWithJudgmentPosition(), and Update().
m_pIterNeedsHoldJudging
NoteData::all_tracks_iterator* Player::m_pIterNeedsHoldJudging protected
Referenced by Load(), Player(), Update(), and ~Player().
m_pIterNeedsTapJudging
NoteData::all_tracks_iterator* Player::m_pIterNeedsTapJudging protected
Referenced by Load(), Player(), UpdateTapNotesMissedOlderThan(), and ~Player().
m_pIterUncrossedRows
NoteData::all_tracks_iterator* Player::m_pIterUncrossedRows protected
Referenced by CrossedRows(), Load(), Player(), and ~Player().
m_pIterUnjudgedMineRows
NoteData::all_tracks_iterator* Player::m_pIterUnjudgedMineRows protected
Referenced by Load(), Player(), UpdateJudgedRows(), and ~Player().
m_pIterUnjudgedRows
NoteData::all_tracks_iterator* Player::m_pIterUnjudgedRows protected
Referenced by Load(), Player(), UpdateJudgedRows(), and ~Player().
m_pJudgedRows
JudgedRows* Player::m_pJudgedRows protected
Referenced by Load(), Player(), UpdateJudgedRows(), and ~Player().
m_pLifeMeter
LifeMeter* Player::m_pLifeMeter protected
Referenced by ChangeLife(), ChangeLifeRecord(), DoTapScoreNone(), Init(), Player(), and SetLife().
m_pNoteField
NoteField* Player::m_pNoteField protected
Referenced by CacheAllUsedNoteSkins(), DrawPrimitives(), FadeToFail(), FlashGhostRow(), HandleHoldCheckpoint(), HasVisibleParts(), Init(), Load(), Player(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), RenderAllNotesIgnoreScores(), Step(), Update(), UpdateHoldNotes(), UpdateJudgedRows(), and ~Player().
m_pPlayerStageStats
PlayerStageStats* Player::m_pPlayerStageStats protected
The player's present stage stats.
Referenced by AddHoldToReplayData(), AddNoteToReplayData(), ChangeLifeRecord(), ChangeWifeRecord(), CrossedRows(), DoTapScoreNone(), FlashGhostRow(), HandleHoldCheckpoint(), HandleHoldScore(), HandleTapRowScore(), IncrementComboOrMissCombo(), Init(), IsOniDead(), Load(), Player(), SendComboMessages(), SetCombo(), SetHoldJudgment(), SetJudgment(), SetMineJudgment(), Step(), Update(), and UpdateHoldNotes().
m_pPlayerState
PlayerState* Player::m_pPlayerState protected
The player's present state.
Referenced by CrossedRows(), DoTapScoreNone(), DrawHoldJudgments(), DrawPrimitives(), DrawTapJudgments(), FlashGhostRow(), GetClosestNonEmptyRow(), GetClosestNote(), GetPlayerState(), HandleHoldCheckpoint(), HandleHoldScore(), HandleTapRowScore(), Init(), IsOniDead(), Load(), Player(), ScoreAllActiveHoldsLetGo(), SendComboMessages(), SetCombo(), SetHoldJudgment(), SetJudgment(), SetMineJudgment(), Step(), Update(), UpdateHoldNotes(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
m_pPrimaryScoreKeeper
ScoreKeeper* Player::m_pPrimaryScoreKeeper protected
Referenced by DoTapScoreNone(), HandleHoldCheckpoint(), HandleHoldScore(), HandleTapRowScore(), Init(), Player(), UpdateHoldNotes(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
m_pScoreDisplay
ScoreDisplay* Player::m_pScoreDisplay protected
Referenced by HandleHoldScore(), HandleTapRowScore(), Init(), Player(), and UpdateJudgedRows().
m_pSecondaryScoreDisplay
ScoreDisplay* Player::m_pSecondaryScoreDisplay protected
Referenced by HandleHoldScore(), HandleTapRowScore(), Init(), Player(), and UpdateJudgedRows().
m_pSecondaryScoreKeeper
ScoreKeeper* Player::m_pSecondaryScoreKeeper protected
Referenced by DoTapScoreNone(), HandleHoldCheckpoint(), HandleHoldScore(), HandleTapRowScore(), Init(), Player(), UpdateHoldNotes(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
m_soundMine
RageSound Player::m_soundMine protected
Referenced by Init(), and UpdateJudgedRows().
m_sprCombo
AutoActor Player::m_sprCombo protected
Referenced by DrawPrimitives(), and Init().
m_sprJudgment
AutoActor Player::m_sprJudgment protected
Referenced by DrawTapJudgments(), Init(), and Load().
m_Timing
TimingData* Player::m_Timing protected
Referenced by CrossedRows(), GetClosestNonEmptyRow(), GetClosestNonEmptyRowDirectional(), GetClosestNote(), GetClosestNoteDirectional(), GetPlayerTimingData(), HandleHoldCheckpoint(), Load(), Step(), UpdateJudgedRows(), and UpdateTapNotesMissedOlderThan().
m_tsCombo
TweenState Player::m_tsCombo[NUM_REVERSE][NUM_CENTERED] protected
Referenced by Init(), and Update().
m_tsJudgment
TweenState Player::m_tsJudgment[NUM_REVERSE][NUM_CENTERED] protected
Referenced by Init(), and Update().
m_vbFretIsDown
vector<bool> Player::m_vbFretIsDown protected
Referenced by Init().
m_vKeysounds
vector<RageSound> Player::m_vKeysounds protected
Referenced by Load(), PlayKeysound(), UpdateHoldNotes(), and UpdateJudgedRows().
m_vpHoldJudgment
vector<HoldJudgment*> Player::m_vpHoldJudgment protected
Referenced by DrawHoldJudgments(), Init(), SetHoldJudgment(), Update(), and ~Player().
maxwifescore
float Player::maxwifescore = 0.f
Referenced by ChangeWifeRecord(), Load(), SetHoldJudgment(), SetJudgment(), and SetMineJudgment().
nerv
vector<int> Player::nerv
Referenced by Load(), and Step().
nervpos
size_t Player::nervpos = 0
Referenced by Step().
TAP_JUDGMENTS_UNDER_FIELD
ThemeMetric<bool> Player::TAP_JUDGMENTS_UNDER_FIELD protected
Referenced by DrawPrimitives(), and Init().
totalwifescore
int Player::totalwifescore
Referenced by Load(), SetHoldJudgment(), SetJudgment(), and SetMineJudgment().
wifescorepersonalbest
float Player::wifescorepersonalbest = 0.f
Referenced by Load(), SetHoldJudgment(), SetJudgment(), and SetMineJudgment().
The documentation for this class was generated from the following files:
Player.h
Player.cpp