Etterna: XmlFileUtil.cpp File Reference
XmlFileUtil.cpp File Reference
#include "XmlFileUtil.h"
#include "Foreach.h"
#include "LuaManager.h"
#include "RageFile.h"
#include "RageFileDriverMemory.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "XmlFile.h"
#include "arch/Dialog/Dialog.h"
#include "global.h"
#include "LuaReference.h"
Classes
class XNodeLuaValue
Macros
#define WRITE(x)
Functions
static void InitEntities ()
static void tcsskip (const RString &s, RString::size_type &i)
static void SetString (const RString &s, int iStart, int iEnd, RString *ps, bool trim=false)
Variables
static const char chXMLTagOpen = '<'
static const char chXMLTagClose = '>'
static const char chXMLQuestion
static const char chXMLTagPre = '/'
static const char chXMLExclamation = '!'
static const char chXMLDash = '-'
static map< RString, RString > g_mapEntitiesToChars
static map< char, RString > g_mapCharsToEntities
Macro Definition Documentation
WRITE
#define WRITE (x)
Value:
if (f.Write(x) == -1)                                                      \
    return false
Function Documentation
InitEntities()
static void InitEntities () static
References g_mapCharsToEntities, and g_mapEntitiesToChars.
Referenced by XmlFileUtil::GetXML(), XmlFileUtil::Load(), and XmlFileUtil::SaveToFile().
SetString()
static void SetString (const RString & s, int iStart, int iEnd, RString * ps, bool trim = false) static
References Rage::trim().
tcsskip()
static void tcsskip (const RString & s, RString::size_type & i) static
Variable Documentation
chXMLDash
const char chXMLDash = '-' static
chXMLExclamation
const char chXMLExclamation = '!' static
chXMLQuestion
const char chXMLQuestion static
Initial value:
=
  '?'
chXMLTagClose
const char chXMLTagClose = '>' static
chXMLTagOpen
const char chXMLTagOpen = '<' static
chXMLTagPre
const char chXMLTagPre = '/' static
g_mapCharsToEntities
map<char, RString> g_mapCharsToEntities static
Referenced by InitEntities().
g_mapEntitiesToChars
map<RString, RString> g_mapEntitiesToChars static
Referenced by InitEntities().