Etterna: LunaPlayerState Class Reference
LunaPlayerState Class Reference
Allow Lua to have access to the PlayerState.
Public Member Functions
DEFINE_METHOD (GetPlayerNumber, m_PlayerNumber)
DEFINE_METHOD (GetMultiPlayerNumber, m_mp)
DEFINE_METHOD (GetPlayerController, m_PlayerController)
DEFINE_METHOD (GetHealthState, m_HealthState)
LunaPlayerState ()
Public Member Functions inherited from Luna< PlayerState >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int ApplyPreferredOptionsToOtherLevels (T *p, lua_State *L)
static int GetSongPosition (T *p, lua_State *L)
static int SetPlayerOptions (T *p, lua_State *L)
static int GetPlayerOptions (T *p, lua_State *L)
static int GetPlayerOptionsArray (T *p, lua_State *L)
static int GetPlayerOptionsString (T *p, lua_State *L)
static int GetCurrentPlayerOptions (T *p, lua_State *L)
static int GetSuperMeterLevel (T *p, lua_State *L)
static int SetTargetGoal (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< PlayerState >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< PlayerState >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< PlayerState >
using T = PlayerState
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< PlayerState >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the PlayerState.
Constructor & Destructor Documentation
LunaPlayerState()
LunaPlayerState::LunaPlayerState () inline
References ADD_METHOD, ApplyPreferredOptionsToOtherLevels(), GetCurrentPlayerOptions(), GetPlayerOptions(), GetPlayerOptionsArray(), GetPlayerOptionsString(), GetSongPosition(), GetSuperMeterLevel(), SetPlayerOptions(), and SetTargetGoal().
Member Function Documentation
ApplyPreferredOptionsToOtherLevels()
static int LunaPlayerState::ApplyPreferredOptionsToOtherLevels (T * p, lua_State * L) inline static
References ModsGroup< T >::Assign(), ModsGroup< T >::Get(), PlayerState::m_PlayerOptions, and ModsLevel_Preferred.
Referenced by LunaPlayerState().
DEFINE_METHOD() [1/4]
LunaPlayerState::DEFINE_METHOD (GetPlayerNumber , m_PlayerNumber)
DEFINE_METHOD() [2/4]
LunaPlayerState::DEFINE_METHOD (GetMultiPlayerNumber , m_mp)
DEFINE_METHOD() [3/4]
LunaPlayerState::DEFINE_METHOD (GetPlayerController , m_PlayerController)
DEFINE_METHOD() [4/4]
LunaPlayerState::DEFINE_METHOD (GetHealthState , m_HealthState)
GetCurrentPlayerOptions()
static int LunaPlayerState::GetCurrentPlayerOptions (T * p, lua_State * L) inline static
References ModsGroup< T >::GetCurrent(), PlayerState::m_PlayerOptions, and PlayerOptions::PushSelf().
Referenced by LunaPlayerState().
GetPlayerOptions()
static int LunaPlayerState::GetPlayerOptions (T * p, lua_State * L) inline static
References ModsGroup< T >::Get(), L, PlayerState::m_PlayerOptions, and PlayerOptions::PushSelf().
Referenced by LunaPlayerState().
GetPlayerOptionsArray()
static int LunaPlayerState::GetPlayerOptionsArray (T * p, lua_State * L) inline static
References ModsGroup< T >::Get(), PlayerOptions::GetMods(), L, and PlayerState::m_PlayerOptions.
Referenced by LunaPlayerState().
GetPlayerOptionsString()
static int LunaPlayerState::GetPlayerOptionsString (T * p, lua_State * L) inline static
References ModsGroup< T >::Get(), PlayerOptions::GetString(), L, PlayerState::m_PlayerOptions, and LuaHelpers::Push().
Referenced by LunaPlayerState().
GetSongPosition()
static int LunaPlayerState::GetSongPosition (T * p, lua_State * L) inline static
References PlayerState::m_Position, and SongPosition::PushSelf().
Referenced by LunaPlayerState().
GetSuperMeterLevel()
static int LunaPlayerState::GetSuperMeterLevel (T * p, lua_State * L) inline static
References f.
Referenced by LunaPlayerState().
SetPlayerOptions()
static int LunaPlayerState::SetPlayerOptions (T * p, lua_State * L) inline static
References ModsGroup< T >::Assign(), PlayerOptions::FromString(), L, PlayerState::m_PlayerOptions, and SArg.
Referenced by LunaPlayerState().
SetTargetGoal()
static int LunaPlayerState::SetTargetGoal (T * p, lua_State * L) inline static
References FArg, and PlayerState::playertargetgoal.
Referenced by LunaPlayerState().
The documentation for this class was generated from the following file:
PlayerState.cpp