Etterna: RageDisplay_Null Class Reference
RageDisplay_Null Class Reference
#include <RageDisplay_Null.h>
Public Member Functions
RageDisplay_Null ()
RString Init (const VideoModeParams &p, bool bAllowUnacceleratedRenderer) override
RString GetApiDescription () const override
void GetDisplayResolutions (DisplayResolutions &out) const override
const RagePixelFormatDesc * GetPixelFormatDesc (RagePixelFormat pf) const override
bool BeginFrame () override
void EndFrame () override
const VideoModeParams * GetActualVideoModeParams () const override
void SetBlendMode (BlendMode) override
bool SupportsTextureFormat (RagePixelFormat, bool=false) override
bool SupportsPerVertexMatrixScale () override
unsigned CreateTexture (RagePixelFormat, RageSurface *, bool) override
void UpdateTexture (unsigned, RageSurface *, int, int, int, int) override
void DeleteTexture (unsigned) override
void ClearAllTextures () override
int GetNumTextureUnits () override
void SetTexture (TextureUnit, unsigned) override
void SetTextureMode (TextureUnit, TextureMode) override
void SetTextureWrapping (TextureUnit, bool) override
int GetMaxTextureSize () const override
void SetTextureFiltering (TextureUnit, bool) override
bool IsZWriteEnabled () const override
bool IsZTestEnabled () const override
void SetZWrite (bool) override
void SetZBias (float) override
void SetZTestMode (ZTestMode) override
void ClearZBuffer () override
void SetCullMode (CullMode) override
void SetAlphaTest (bool) override
void SetMaterial (const RageColor &, const RageColor &, const RageColor &, const RageColor &, float) override
void SetLighting (bool) override
void SetLightOff (int) override
void SetLightDirectional (int, const RageColor &, const RageColor &, const RageColor &, const RageVector3 &) override
void SetSphereEnvironmentMapping (TextureUnit, bool) override
void SetCelShaded (int) override
bool IsD3DInternal () override
RageCompiledGeometry * CreateCompiledGeometry () override
void DeleteCompiledGeometry (RageCompiledGeometry *) override
Public Member Functions inherited from RageDisplay
RageDisplay ()
virtual ~RageDisplay ()
void SetPresentTime (std::chrono::nanoseconds presentTime)
RString SetVideoMode (VideoModeParams p, bool &bNeedReloadTextures)
virtual void ResolutionChanged ()
bool IsD3D ()
bool IsWindowed ()
virtual bool SupportsThreadedRendering ()
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void BeginConcurrentRendering ()
virtual void EndConcurrentRendering ()
virtual RageTextureLock * CreateTextureLock ()
virtual void SetEffectMode (EffectMode)
virtual bool IsEffectModeSupported (EffectMode effect)
bool SupportsRenderToTexture () const
virtual unsigned CreateRenderTarget (const RenderTargetParam &, int &, int &)
virtual unsigned GetRenderTarget ()
virtual void SetRenderTarget (unsigned, bool=true)
void DrawQuads (const RageSpriteVertex v[], int iNumVerts)
void DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawFan (const RageSpriteVertex v[], int iNumVerts)
void DrawStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
void DrawCompiledGeometry (const RageCompiledGeometry *p, int iMeshIndex, const vector< msMesh > &vMeshes)
void DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawCircle (const RageSpriteVertex &v, float radius)
void DrawQuad (const RageSpriteVertex v[])
virtual void SetPolygonMode (PolygonMode)
virtual void SetLineWidth (float)
bool SaveScreenshot (const RString &sPath, GraphicsFileFormat format)
virtual RString GetTextureDiagnostics (unsigned) const
virtual RageSurface * GetTexture (unsigned)
bool IsPredictiveFrameLimit () const
int GetFPS () const
int GetVPF () const
int GetCumFPS () const
virtual void ResetStats ()
virtual void ProcessStatsOnFlip ()
virtual RString GetStats () const
void StatsAddVerts (int iNumVertsRendered)
void PushMatrix ()
void PopMatrix ()
void Translate (float x, float y, float z)
void TranslateWorld (float x, float y, float z)
void Scale (float x, float y, float z)
void RotateX (float deg)
void RotateY (float deg)
void RotateZ (float deg)
void SkewX (float fAmount)
void SkewY (float fAmount)
void MultMatrix (const RageMatrix &f)
void PostMultMatrix (const RageMatrix &f)
void PreMultMatrix (const RageMatrix &f)
void LoadIdentity ()
void TexturePushMatrix ()
void TexturePopMatrix ()
void TextureTranslate (float x, float y)
void TextureTranslate (const RageVector2 &v)
void CameraPushMatrix ()
void CameraPopMatrix ()
void LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
void LoadLookAt (float fov, const RageVector3 &Eye, const RageVector3 &At, const RageVector3 &Up)
void CenteringPushMatrix ()
void CenteringPopMatrix ()
void ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
RageSurface * CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void *pixels, int width, int height, int pitch)
RagePixelFormat FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime=false)
void PushSelf (lua_State *L)
Protected Member Functions
void DrawQuadsInternal (const RageSpriteVertex v[], int) override
void DrawQuadStripInternal (const RageSpriteVertex v[], int) override
void DrawFanInternal (const RageSpriteVertex v[], int) override
void DrawStripInternal (const RageSpriteVertex v[], int) override
void DrawTrianglesInternal (const RageSpriteVertex v[], int) override
void DrawCompiledGeometryInternal (const RageCompiledGeometry *p, int) override
void DrawLineStripInternal (const RageSpriteVertex v[], int, float) override
void DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int) override
RString TryVideoMode (const VideoModeParams &p, bool &) override
RageSurface * CreateScreenshot () override
RageMatrix GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override
bool SupportsSurfaceFormat (RagePixelFormat)
Protected Member Functions inherited from RageDisplay
virtual void DrawCircleInternal (const RageSpriteVertex &v, float radius)
void DrawPolyLine (const RageSpriteVertex &p1, const RageSpriteVertex &p2, float LineWidth)
void DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void SetDefaultRenderStates ()
RageMatrix GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar)
virtual RageMatrix GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf)
RageMatrix GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight)
void UpdateCentering ()
const RageMatrix * GetCentering () const
const RageMatrix * GetProjectionTop () const
const RageMatrix * GetViewTop () const
const RageMatrix * GetWorldTop () const
const RageMatrix * GetTextureTop () const
void FrameLimitBeforeVsync ()
void FrameLimitAfterVsync (int iFPS)
Protected Attributes
VideoModeParams m_Params
Additional Inherited Members
Public Types inherited from RageDisplay
enum GraphicsFileFormat { SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_LOW_QUAL, SAVE_LOSSY_HIGH_QUAL }
Constructor & Destructor Documentation
RageDisplay_Null()
RageDisplay_Null::RageDisplay_Null ()
References LOG, and RageLog::MapLog().
Member Function Documentation
BeginFrame()
bool RageDisplay_Null::BeginFrame () inline override virtual
Reimplemented from RageDisplay.
ClearAllTextures()
void RageDisplay_Null::ClearAllTextures () inline override virtual
Implements RageDisplay.
ClearZBuffer()
void RageDisplay_Null::ClearZBuffer () inline override virtual
Implements RageDisplay.
CreateCompiledGeometry()
RageCompiledGeometry * RageDisplay_Null::CreateCompiledGeometry () override virtual
Implements RageDisplay.
CreateScreenshot()
RageSurface * RageDisplay_Null::CreateScreenshot () override protected virtual
Implements RageDisplay.
References RageDisplay::RagePixelFormatDesc::bpp, CreateSurface(), RageDisplay::RagePixelFormatDesc::masks, RageSurface::pitch, RageSurface::pixels, and RagePixelFormat_RGB8.
CreateTexture()
unsigned RageDisplay_Null::CreateTexture (RagePixelFormat , RageSurface * , bool) inline override virtual
Implements RageDisplay.
DeleteCompiledGeometry()
void RageDisplay_Null::DeleteCompiledGeometry (RageCompiledGeometry * p) override virtual
Implements RageDisplay.
DeleteTexture()
void RageDisplay_Null::DeleteTexture (unsigned) inline override virtual
Implements RageDisplay.
DrawCompiledGeometryInternal()
void RageDisplay_Null::DrawCompiledGeometryInternal (const RageCompiledGeometry * p, int) inline override protected virtual
Implements RageDisplay.
DrawFanInternal()
void RageDisplay_Null::DrawFanInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
DrawLineStripInternal()
void RageDisplay_Null::DrawLineStripInternal (const RageSpriteVertex v[], int , float) inline override protected virtual
Reimplemented from RageDisplay.
DrawQuadsInternal()
void RageDisplay_Null::DrawQuadsInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
DrawQuadStripInternal()
void RageDisplay_Null::DrawQuadStripInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
DrawStripInternal()
void RageDisplay_Null::DrawStripInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
DrawSymmetricQuadStripInternal()
void RageDisplay_Null::DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
DrawTrianglesInternal()
void RageDisplay_Null::DrawTrianglesInternal (const RageSpriteVertex v[], int) inline override protected virtual
Implements RageDisplay.
EndFrame()
void RageDisplay_Null::EndFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::ProcessStatsOnFlip().
GetActualVideoModeParams()
const VideoModeParams* RageDisplay_Null::GetActualVideoModeParams () const inline override virtual
Implements RageDisplay.
References m_Params.
GetApiDescription()
RString RageDisplay_Null::GetApiDescription () const inline override virtual
Implements RageDisplay.
GetDisplayResolutions()
void RageDisplay_Null::GetDisplayResolutions (DisplayResolutions & out) const override virtual
Implements RageDisplay.
GetMaxTextureSize()
int RageDisplay_Null::GetMaxTextureSize () const inline override virtual
Implements RageDisplay.
GetNumTextureUnits()
int RageDisplay_Null::GetNumTextureUnits () inline override virtual
Implements RageDisplay.
GetOrthoMatrix()
RageMatrix RageDisplay_Null::GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override protected virtual
Reimplemented from RageDisplay.
GetPixelFormatDesc()
const RageDisplay::RagePixelFormatDesc * RageDisplay_Null::GetPixelFormatDesc (RagePixelFormat pf) const override virtual
Implements RageDisplay.
References ASSERT, and NUM_RagePixelFormat.
Init()
RString RageDisplay_Null::Init (const VideoModeParams & p, bool bAllowUnacceleratedRenderer) override virtual
Implements RageDisplay.
References RageDisplay::SetVideoMode().
IsD3DInternal()
bool RageDisplay_Null::IsD3DInternal () override virtual
Reimplemented from RageDisplay.
IsZTestEnabled()
bool RageDisplay_Null::IsZTestEnabled () const inline override virtual
Implements RageDisplay.
IsZWriteEnabled()
bool RageDisplay_Null::IsZWriteEnabled () const inline override virtual
Implements RageDisplay.
SetAlphaTest()
void RageDisplay_Null::SetAlphaTest (bool) inline override virtual
Implements RageDisplay.
SetBlendMode()
void RageDisplay_Null::SetBlendMode (BlendMode) inline override virtual
Implements RageDisplay.
SetCelShaded()
void RageDisplay_Null::SetCelShaded (int) inline override virtual
Implements RageDisplay.
SetCullMode()
void RageDisplay_Null::SetCullMode (CullMode) inline override virtual
Implements RageDisplay.
SetLightDirectional()
void RageDisplay_Null::SetLightDirectional (int , const RageColor & , const RageColor & , const RageColor & , const RageVector3 &) inline override virtual
Implements RageDisplay.
SetLighting()
void RageDisplay_Null::SetLighting (bool) inline override virtual
Implements RageDisplay.
SetLightOff()
void RageDisplay_Null::SetLightOff (int) inline override virtual
Implements RageDisplay.
SetMaterial()
void RageDisplay_Null::SetMaterial (const RageColor & , const RageColor & , const RageColor & , const RageColor & , float) inline override virtual
Implements RageDisplay.
SetSphereEnvironmentMapping()
void RageDisplay_Null::SetSphereEnvironmentMapping (TextureUnit , bool) inline override virtual
Implements RageDisplay.
SetTexture()
void RageDisplay_Null::SetTexture (TextureUnit , unsigned) inline override virtual
Implements RageDisplay.
SetTextureFiltering()
void RageDisplay_Null::SetTextureFiltering (TextureUnit , bool) inline override virtual
Implements RageDisplay.
SetTextureMode()
void RageDisplay_Null::SetTextureMode (TextureUnit , TextureMode) inline override virtual
Implements RageDisplay.
SetTextureWrapping()
void RageDisplay_Null::SetTextureWrapping (TextureUnit , bool) inline override virtual
Implements RageDisplay.
SetZBias()
void RageDisplay_Null::SetZBias (float) inline override virtual
Implements RageDisplay.
SetZTestMode()
void RageDisplay_Null::SetZTestMode (ZTestMode) inline override virtual
Implements RageDisplay.
SetZWrite()
void RageDisplay_Null::SetZWrite (bool) inline override virtual
Implements RageDisplay.
SupportsPerVertexMatrixScale()
bool RageDisplay_Null::SupportsPerVertexMatrixScale () inline override virtual
Implements RageDisplay.
SupportsSurfaceFormat()
bool RageDisplay_Null::SupportsSurfaceFormat (RagePixelFormat) inline protected
SupportsTextureFormat()
bool RageDisplay_Null::SupportsTextureFormat (RagePixelFormat , bool = false) inline override virtual
Implements RageDisplay.
TryVideoMode()
RString RageDisplay_Null::TryVideoMode (const VideoModeParams & p, bool &) inline override protected virtual
Implements RageDisplay.
UpdateTexture()
void RageDisplay_Null::UpdateTexture (unsigned , RageSurface * , int , int , int , int) inline override virtual
Implements RageDisplay.
Member Data Documentation
m_Params
VideoModeParams RageDisplay_Null::m_Params protected
Referenced by GetActualVideoModeParams().
The documentation for this class was generated from the following files:
RageDisplay_Null.h
RageDisplay_Null.cpp