Etterna: RageUtil_FileDB.cpp File Reference
RageUtil_FileDB.cpp File Reference
#include "global.h"
#include "RageUtil_FileDB.h"
#include "RageLog.h"
#include "RageUtil.h"
Functions
static void SplitPath (RString sPath, RString &sDir, RString &sName)
Function Documentation
SplitPath()
static void SplitPath (RString sPath, RString & sDir, RString & sName) static
References CollapsePath(), and StdString::CStdStr< CT >::Right().
Referenced by FilenameDB::DelFile(), FilenameDB::GetFile(), FilenameDB::GetFileHash(), FilenameDB::GetFileSize(), and FilenameDB::GetFileType().