Etterna: RageString.cpp File Reference
RageString.cpp File Reference
#include "global.h"
#include "RageString.h"
#include "RageUnicode.h"
#include <algorithm>
#include <cstdlib>
#include <sstream>
Macros
#define likely(x) (x)
#define unlikely(x) (x)
Functions
void make_upper (char *p, size_t len)
void make_lower (char *p, size_t len)
template<class S >
static int DelimitorLength (S const &delimitor)
static int DelimitorLength (char delimitor)
static int DelimitorLength (wchar_t delimitor)
template<class S , class C >
std::vector< S > do_split (S const &source, C const delimitor, Rage::EmptyEntries const shouldIgnore)
template<class S >
void do_split (S const &source, S const &delimitor, int &start, int &size, int len, Rage::EmptyEntries const shouldIgnore)
int unicode_do_casing (char *p, size_t iLen, const unsigned char pMapping[256])
Macro Definition Documentation
likely
#define likely (x) (x)
Referenced by make_lower(), and make_upper().
unlikely
#define unlikely (x) (x)
Referenced by make_lower(), and make_upper().
Function Documentation
DelimitorLength() [1/3]
template<class S > static int DelimitorLength (S const & delimitor) static
Referenced by do_split().
DelimitorLength() [2/3]
static int DelimitorLength (char delimitor) static
DelimitorLength() [3/3]
static int DelimitorLength (wchar_t delimitor) static
do_split() [1/2]
template<class S , class C > std::vector<S> do_split (S const & source, C const delimitor, Rage::EmptyEntries const shouldIgnore)
References DelimitorLength(), and Rage::include.
Referenced by Rage::split(), and Rage::split_in_place().
do_split() [2/2]
template<class S > void do_split (S const & source, S const & delimitor, int & start, int & size, int len, Rage::EmptyEntries const shouldIgnore)
References min(), and Rage::skip.
make_lower()
void make_lower (char * p, size_t len)
References likely, Rage::lowerCase, unicode_do_casing(), and unlikely.
Referenced by Rage::make_lower().
make_upper()
void make_upper (char * p, size_t len)
References likely, unicode_do_casing(), unlikely, and Rage::upperCase.
Referenced by Rage::make_upper().
unicode_do_casing()
int unicode_do_casing (char * p, size_t iLen, const unsigned char pMapping[256])
References L, Rage::utf8_to_wchar(), and Rage::wchar_to_utf8().
Referenced by make_lower(), and make_upper().