Etterna: LunaLifeMeterBattery Class Reference
LunaLifeMeterBattery Class Reference
Allow Lua to have access to the LifeMeterBattery.
Public Member Functions
LunaLifeMeterBattery ()
Public Member Functions inherited from Luna< LifeMeterBattery >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetLivesLeft (T *p, lua_State *L)
static int GetTotalLives (T *p, lua_State *L)
static int ChangeLives (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< LifeMeterBattery >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< LifeMeterBattery >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< LifeMeterBattery >
using T = LifeMeterBattery
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< LifeMeterBattery >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the LifeMeterBattery.
Constructor & Destructor Documentation
LunaLifeMeterBattery()
LunaLifeMeterBattery::LunaLifeMeterBattery () inline
References ADD_METHOD, ChangeLives(), GetLivesLeft(), and GetTotalLives().
Member Function Documentation
ChangeLives()
static int LunaLifeMeterBattery::ChangeLives (T * p, lua_State * L) inline static
References LifeMeterBattery::ChangeLives(), COMMON_RETURN_SELF, and IArg.
Referenced by LunaLifeMeterBattery().
GetLivesLeft()
static int LunaLifeMeterBattery::GetLivesLeft (T * p, lua_State * L) inline static
References LifeMeterBattery::GetLivesLeft().
Referenced by LunaLifeMeterBattery().
GetTotalLives()
static int LunaLifeMeterBattery::GetTotalLives (T * p, lua_State * L) inline static
References LifeMeterBattery::GetTotalLives().
Referenced by LunaLifeMeterBattery().
The documentation for this class was generated from the following file:
LifeMeterBattery.cpp