Etterna: FontPage Class Reference
FontPage Class Reference
#include <Font.h>
Public Member Functions
FontPage ()
~FontPage ()
void Load (const FontPageSettings &cfg)
int GetCenter () const
Public Attributes
int m_iHeight { 0 }
int m_iLineSpacing { 0 }
float m_fVshift { 0 }
int m_iDrawExtraPixelsLeft { 0 }
int m_iDrawExtraPixelsRight { 0 }
FontPageTextures m_FontPageTextures
RString m_sTexturePath
vector< glyph > m_aGlyphs
All glyphs in this list will point to m_pTexture.
map< wchar_t, int > m_iCharToGlyphNo
Private Member Functions
void SetExtraPixels (int iDrawExtraPixelsLeft, int DrawExtraPixelsRight)
void SetTextureCoords (const vector< int > &aiWidths, int iAdvanceExtraPixels)
Constructor & Destructor Documentation
FontPage()
FontPage::FontPage ()
~FontPage()
FontPage::~FontPage ()
References m_FontPageTextures, RageTexture::m_lastRefTime, FontPageTextures::m_pTextureMain, FontPageTextures::m_pTextureStroke, TEXTUREMAN, RageTimer::Touch(), and RageTextureManager::UnloadTexture().
Member Function Documentation
GetCenter()
int FontPage::GetCenter () const inline
References m_iHeight.
Referenced by Font::GetCenter().
Load()
void FontPage::Load (const FontPageSettings & cfg)
References RageTextureID::AdditionalTextureHints, FontPageSettings::CharToGlyphNo, RageTextureID::filename, RageTextureManager::GetDefaultTextureID(), RageTexture::GetNumFrames(), RageTexture::GetSourceFrameHeight(), RageTexture::GetSourceFrameWidth(), IsAFile(), RageTextureManager::LoadTexture(), m_FontPageTextures, FontPageSettings::m_fScaleAllWidthsBy, m_fVshift, FontPageSettings::m_iAddToAllWidths, FontPageSettings::m_iAdvanceExtraPixels, FontPageSettings::m_iBaseline, m_iCharToGlyphNo, FontPageSettings::m_iDefaultWidth, FontPageSettings::m_iDrawExtraPixelsLeft, m_iDrawExtraPixelsLeft, FontPageSettings::m_iDrawExtraPixelsRight, m_iDrawExtraPixelsRight, m_iHeight, FontPageSettings::m_iLineSpacing, m_iLineSpacing, FontPageSettings::m_iTop, FontPageSettings::m_mapGlyphWidths, FontPageTextures::m_pTextureMain, FontPageTextures::m_pTextureStroke, FontPageSettings::m_sTextureHints, FontPageSettings::m_sTexturePath, m_sTexturePath, StdString::CStdStr< CT >::Replace(), LuaHelpers::ReportScriptErrorFmt(), SetExtraPixels(), SetTextureCoords(), and TEXTUREMAN.
Referenced by Font::Load().
SetExtraPixels()
void FontPage::SetExtraPixels (int iDrawExtraPixelsLeft, int DrawExtraPixelsRight) private
References f, RageTexture::GetSourceFrameWidth(), RageTexture::GetSourceToTexCoordsRatioX(), m_aGlyphs, m_FontPageTextures, FontPageTextures::m_pTextureMain, and min().
Referenced by Load().
SetTextureCoords()
void FontPage::SetTextureCoords (const vector< int > & aiWidths, int iAdvanceExtraPixels) private
References RageTexture::GetNumFrames(), RageTexture::GetSourceFrameHeight(), RageTexture::GetSourceFrameWidth(), RageTexture::GetSourceToTexCoordsRatioX(), RageTexture::GetTextureCoordRect(), StepMania::Rect< T >::left, m_aGlyphs, glyph::m_fHeight, glyph::m_fHshift, glyph::m_FontPageTextures, m_FontPageTextures, glyph::m_fWidth, glyph::m_iHadvance, glyph::m_pPage, FontPageTextures::m_pTextureMain, glyph::m_TexRect, and StepMania::Rect< T >::right.
Referenced by Load().
Member Data Documentation
m_aGlyphs
vector<glyph> FontPage::m_aGlyphs
All glyphs in this list will point to m_pTexture.
Referenced by Font::AddPage(), Font::SetDefaultGlyph(), SetExtraPixels(), and SetTextureCoords().
m_FontPageTextures
FontPageTextures FontPage::m_FontPageTextures
Referenced by Load(), Font::Load(), SetExtraPixels(), SetTextureCoords(), and ~FontPage().
m_fVshift
float FontPage::m_fVshift { 0 }
Referenced by BitmapText::BuildChars(), and Load().
m_iCharToGlyphNo
map<wchar_t, int> FontPage::m_iCharToGlyphNo
Referenced by Font::AddPage(), Load(), and Font::Load().
m_iDrawExtraPixelsLeft
int FontPage::m_iDrawExtraPixelsLeft { 0 }
Referenced by Load().
m_iDrawExtraPixelsRight
int FontPage::m_iDrawExtraPixelsRight { 0 }
Referenced by Load().
m_iHeight
int FontPage::m_iHeight { 0 }
Referenced by GetCenter(), Font::GetHeight(), Font::GetLineHeightInSourcePixels(), and Load().
m_iLineSpacing
int FontPage::m_iLineSpacing { 0 }
Referenced by Font::GetLineSpacing(), and Load().
m_sTexturePath
RString FontPage::m_sTexturePath
Referenced by Load().
The documentation for this class was generated from the following files:
Font.h
Font.cpp