Etterna: XmlToLua.h File Reference
XmlToLua.h File Reference
#include "global.h"
Functions
void convert_xmls_in_dir (RString const &dirname)
Function Documentation
convert_xmls_in_dir()
void convert_xmls_in_dir (RString const & dirname)
References convert_xml_file(), convert_xmls_in_dir(), FILEMAN, FT_Directory, FT_Xml, RageFileManager::GetDirListing(), and ActorUtil::GetFileType().
Referenced by convert_xmls_in_dir(), DebugLineConvertXML::DoAndLog(), and LuaFunc_convert_xml_bgs().