Etterna: FontCharAliases.cpp File Reference
FontCharAliases.cpp File Reference
#include "global.h"
#include "FontCharAliases.h"
#include "Font.h"
#include "RageUtil.h"
#include <map>
Macros
#define INTERNAL 0xE000
Typedefs
typedef map< RString, wchar_t, StdString::StdStringLessNoCase > aliasmap
Functions
static void InitCharAliases ()
Variables
static aliasmap CharAliases
static map< RString, RString > CharAliasRepl
Macro Definition Documentation
INTERNAL
#define INTERNAL 0xE000
Referenced by InitCharAliases().
Typedef Documentation
aliasmap
typedef map<RString, wchar_t, StdString::StdStringLessNoCase> aliasmap
Function Documentation
InitCharAliases()
static void InitCharAliases () static
References aliases, CharAliases, CharAliasRepl, FONT_DEFAULT_GLYPH, INTERNAL, INVALID_CHAR, StdString::CStdStr< CT >::MakeLower(), and WcharToUTF8().
Referenced by FontCharAliases::GetChar(), and FontCharAliases::ReplaceMarkers().
Variable Documentation
CharAliases
aliasmap CharAliases static
Referenced by FontCharAliases::GetChar(), and InitCharAliases().
CharAliasRepl
map<RString, RString> CharAliasRepl static
Referenced by InitCharAliases(), and FontCharAliases::ReplaceMarkers().