Etterna: SampleHistory Class Reference
SampleHistory Class Reference
Store a trailing history of values, and retrieve values with interpolation.
#include <SampleHistory.h>
Public Member Functions
SampleHistory ()
void AddSample (float fSample, float fDeltaTime)
float GetSample (float fSecondsAgo) const
Private Member Functions
float GetSampleNum (float fSamplesAgo) const
Private Attributes
vector< float > m_afHistory
int m_iLastHistory
int m_iHistorySamplesPerSecond
float m_fHistorySeconds
float m_fToSample
Detailed Description
Store a trailing history of values, and retrieve values with interpolation.
Constructor & Destructor Documentation
SampleHistory()
SampleHistory::SampleHistory ()
References m_afHistory, m_fHistorySeconds, m_fToSample, m_iHistorySamplesPerSecond, m_iLastHistory, and sample_step_size().
Member Function Documentation
AddSample()
void SampleHistory::AddSample (float fSample, float fDeltaTime)
References f, m_afHistory, m_fToSample, m_iHistorySamplesPerSecond, m_iLastHistory, min(), and sample_step_size().
Referenced by SoundEffectControl::Update().
GetSample()
float SampleHistory::GetSample (float fSecondsAgo) const
References GetSampleNum(), and m_iHistorySamplesPerSecond.
Referenced by ArrowEffects::GetFrameWidthScale().
GetSampleNum()
float SampleHistory::GetSampleNum (float fSamplesAgo) const private
References f, lerp(), m_afHistory, m_iLastHistory, min(), and wrap().
Referenced by GetSample().
Member Data Documentation
m_afHistory
vector<float> SampleHistory::m_afHistory private
Referenced by AddSample(), GetSampleNum(), and SampleHistory().
m_fHistorySeconds
float SampleHistory::m_fHistorySeconds private
Referenced by SampleHistory().
m_fToSample
float SampleHistory::m_fToSample private
Referenced by AddSample(), and SampleHistory().
m_iHistorySamplesPerSecond
int SampleHistory::m_iHistorySamplesPerSecond private
Referenced by AddSample(), GetSample(), and SampleHistory().
m_iLastHistory
int SampleHistory::m_iLastHistory private
Referenced by AddSample(), GetSampleNum(), and SampleHistory().
The documentation for this class was generated from the following files:
SampleHistory.h
SampleHistory.cpp