Etterna: CTextureRenderer Class Reference
CTextureRenderer Class Reference
#include <MovieTexture_DShowHelper.h>
Public Member Functions
CTextureRenderer ()
~CTextureRenderer ()
HRESULT CheckMediaType (const CMediaType *pmt)
HRESULT SetMediaType (const CMediaType *pmt)
HRESULT DoRenderSample (IMediaSample *pMediaSample)
void OnReceiveFirstSample (IMediaSample *pSample)
long GetVidWidth () const
long GetVidHeight () const
void SetRenderTarget (MovieTexture_DShow *pTexture)
Public Attributes
RageSemaphore m_OneFrameDecoded
Protected Attributes
long m_lVidWidth
long m_lVidHeight
long m_lVidPitch
char * output
MovieTexture_DShow * m_pTexture
Constructor & Destructor Documentation
CTextureRenderer()
CTextureRenderer::CTextureRenderer ()
~CTextureRenderer()
CTextureRenderer::~CTextureRenderer ()
Member Function Documentation
CheckMediaType()
HRESULT CTextureRenderer::CheckMediaType (const CMediaType * pmt)
DoRenderSample()
HRESULT CTextureRenderer::DoRenderSample (IMediaSample * pMediaSample)
GetVidHeight()
long CTextureRenderer::GetVidHeight () const inline
References m_lVidHeight.
Referenced by MovieTexture_DShow::Create().
GetVidWidth()
long CTextureRenderer::GetVidWidth () const inline
References m_lVidWidth.
Referenced by MovieTexture_DShow::Create().
OnReceiveFirstSample()
void CTextureRenderer::OnReceiveFirstSample (IMediaSample * pSample)
SetMediaType()
HRESULT CTextureRenderer::SetMediaType (const CMediaType * pmt)
SetRenderTarget()
void CTextureRenderer::SetRenderTarget (MovieTexture_DShow * pTexture)
Referenced by MovieTexture_DShow::Create().
Member Data Documentation
m_lVidHeight
long CTextureRenderer::m_lVidHeight protected
Referenced by GetVidHeight().
m_lVidPitch
long CTextureRenderer::m_lVidPitch protected
m_lVidWidth
long CTextureRenderer::m_lVidWidth protected
Referenced by GetVidWidth().
m_OneFrameDecoded
RageSemaphore CTextureRenderer::m_OneFrameDecoded
Referenced by MovieTexture_DShow::Create().
m_pTexture
MovieTexture_DShow* CTextureRenderer::m_pTexture protected
output
char* CTextureRenderer::output protected
The documentation for this class was generated from the following files:
MovieTexture_DShowHelper.h
MovieTexture_DShowHelper.cpp