Etterna: RageFileDriverDirect Class Reference
RageFileDriverDirect Class Reference
File driver for accessing a regular filesystem.
#include <RageFileDriverDirect.h>
Public Member Functions
RageFileDriverDirect (const RString &sRoot)
RageFileBasic * Open (const RString &sPath, int iMode, int &iError) override
bool Move (const RString &sOldPath, const RString &sNewPath) override
bool Remove (const RString &sPath) override
bool Remount (const RString &sPath) override
Public Member Functions inherited from RageFileDriver
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void FlushDirCache (const RString &sPath)
virtual void CacheFile (const RString &)
Private Attributes
RString m_sRoot
Additional Inherited Members
Public Types inherited from RageFileDriver
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Attributes inherited from RageFileDriver
FilenameDB * FDB
Detailed Description
File driver for accessing a regular filesystem.
Constructor & Destructor Documentation
RageFileDriverDirect()
RageFileDriverDirect::RageFileDriverDirect (const RString & sRoot) explicit
References Remount().
Member Function Documentation
Move()
bool RageFileDriverDirect::Move (const RString & sOldPath, const RString & sNewPath) override virtual
Reimplemented from RageFileDriver.
Reimplemented in RageFileDriverDirectReadOnly.
References FilenameDB::AddFile(), CreateDirectories(), FilenameDB::DelFile(), Dirname(), DoRename, RageFileDriver::FDB, FilenameDB::GetFileHash(), FilenameDB::GetFileSize(), RageFileDriver::GetFileType(), m_sRoot, FilenameDB::ResolvePath(), ssprintf(), TRACE, RageFileManager::TYPE_NONE, and WARN.
Open()
RageFileBasic * RageFileDriverDirect::Open (const RString & sPath, int iMode, int & iError) override virtual
Implements RageFileDriver.
Reimplemented in RageFileDriverDirectReadOnly.
References ASSERT, CreateDirectories(), Dirname(), RageFileDriver::FDB, RageFileDriver::GetFileType(), m_sRoot, MakeFileObjDirect(), FilenameDB::ResolvePath(), RageFileManager::TYPE_DIR, and RageFile::WRITE.
Referenced by RageFileDriverDirectReadOnly::Open().
Remount()
bool RageFileDriverDirect::Remount (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
References CreateDirectories(), RageFileDriver::FDB, and m_sRoot.
Referenced by RageFileDriverDirect().
Remove()
bool RageFileDriverDirect::Remove (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
Reimplemented in RageFileDriverDirectReadOnly.
References FilenameDB::DelFile(), DoRemove, FAIL_M, RageFileDriver::FDB, RageFileDriver::GetFileType(), m_sRoot, FilenameDB::ResolvePath(), ssprintf(), TRACE, RageFileManager::TYPE_DIR, RageFileManager::TYPE_FILE, RageFileManager::TYPE_NONE, and WARN.
Member Data Documentation
m_sRoot
RString RageFileDriverDirect::m_sRoot private
Referenced by Move(), Open(), Remount(), and Remove().
The documentation for this class was generated from the following files:
RageFileDriverDirect.h
RageFileDriverDirect.cpp