Etterna: ScoreKeeperShared Class Reference
ScoreKeeperShared Class Reference
ScoreKeeper for Routine mode.
#include <ScoreKeeperShared.h>
Public Member Functions
ScoreKeeperShared (PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
virtual void Load (const vector< Song *> &apSongs, const vector< Steps *> &apSteps) override
void DrawPrimitives () override
void Update (float fDelta) override
void OnNextSong (int iSongInCourseIndex, const Steps *pSteps, const NoteData *pNoteData) override
void HandleTapScore (const TapNote &tn) override
void HandleTapRowScore (const NoteData &nd, int iRow) override
void HandleHoldScore (const TapNote &tn) override
void HandleHoldActiveSeconds (float fMusicSecondsHeld) override
void HandleHoldCheckpointScore (const NoteData &nd, int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow) override
void HandleTapScoreNone () override
Public Member Functions inherited from ScoreKeeperNormal
ScoreKeeperNormal (PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
int TapNoteScoreToDancePoints (TapNoteScore tns) const
int HoldNoteScoreToDancePoints (HoldNoteScore hns) const
int TapNoteScoreToGradePoints (TapNoteScore tns) const
int HoldNoteScoreToGradePoints (HoldNoteScore hns) const
Public Member Functions inherited from ScoreKeeper
ScoreKeeper (PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
virtual ~ScoreKeeper ()=default
Additional Inherited Members
Static Public Member Functions inherited from ScoreKeeperNormal
static int GetPossibleDancePoints (NoteData *nd, const TimingData *td, float fSongSeconds)
static int GetPossibleDancePoints (NoteData *ndPre, NoteData *ndPost, const TimingData *td, float fSongSeconds)
static int GetPossibleGradePoints (NoteData *nd, const TimingData *td, float fSongSeconds)
static int GetPossibleGradePoints (NoteData *ndPre, NoteData *ndPost, const TimingData *td, float fSongSeconds)
static int TapNoteScoreToDancePoints (TapNoteScore tns, bool bBeginner)
static int HoldNoteScoreToDancePoints (HoldNoteScore hns, bool bBeginner)
static int TapNoteScoreToGradePoints (TapNoteScore tns, bool bBeginner)
static int HoldNoteScoreToGradePoints (HoldNoteScore hns, bool bBeginner)
Static Public Member Functions inherited from ScoreKeeper
static ScoreKeeper * MakeScoreKeeper (const RString &sClassName, PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
Protected Member Functions inherited from ScoreKeeper
void GetScoreOfLastTapInRow (const NoteData &nd, int iRow, TapNoteScore &tnsOut, int &iNumTapsInRowOut)
Protected Attributes inherited from ScoreKeeper
PlayerState * m_pPlayerState
PlayerStageStats * m_pPlayerStageStats
Detailed Description
ScoreKeeper for Routine mode.
Constructor & Destructor Documentation
ScoreKeeperShared()
ScoreKeeperShared::ScoreKeeperShared (PlayerState * pPlayerState, PlayerStageStats * pPlayerStageStats)
Member Function Documentation
DrawPrimitives()
void ScoreKeeperShared::DrawPrimitives () override virtual
Reimplemented from ScoreKeeper.
References ScoreKeeper::DrawPrimitives(), GAMESTATE, GameState::GetMasterPlayerNumber(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleHoldActiveSeconds()
void ScoreKeeperShared::HandleHoldActiveSeconds (float fMusicSecondsHeld) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleHoldActiveSeconds(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleHoldCheckpointScore()
void ScoreKeeperShared::HandleHoldCheckpointScore (const NoteData & nd, int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleHoldCheckpointScore(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleHoldScore()
void ScoreKeeperShared::HandleHoldScore (const TapNote & tn) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleHoldScore(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleTapRowScore()
void ScoreKeeperShared::HandleTapRowScore (const NoteData & nd, int iRow) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleTapRowScore(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleTapScore()
void ScoreKeeperShared::HandleTapScore (const TapNote & tn) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleTapScore(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
HandleTapScoreNone()
void ScoreKeeperShared::HandleTapScoreNone () override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::HandleTapScoreNone(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
Load()
void ScoreKeeperShared::Load (const vector< Song *> & apSongs, const vector< Steps *> & apSteps) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), ScoreKeeperNormal::Load(), PlayerState::m_PlayerNumber, and ScoreKeeper::m_pPlayerState.
OnNextSong()
void ScoreKeeperShared::OnNextSong (int iSongInCourseIndex, const Steps * pSteps, const NoteData * pNoteData) override virtual
Reimplemented from ScoreKeeperNormal.
References GAMESTATE, GameState::GetMasterPlayerNumber(), PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerState, and ScoreKeeperNormal::OnNextSong().
Update()
void ScoreKeeperShared::Update (float fDelta) override virtual
Reimplemented from ScoreKeeper.
References GAMESTATE, GameState::GetMasterPlayerNumber(), PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerState, and ScoreKeeper::Update().
The documentation for this class was generated from the following files:
ScoreKeeperShared.h
ScoreKeeperShared.cpp