Etterna: BPMSegment Struct Reference
BPMSegment Struct Reference
Identifies when a song changes its BPM.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
BPMSegment (int iStartRow=ROW_INVALID, float fBPM=0.0f)
BPMSegment (const BPMSegment &other)
float GetBPS () const
float GetBPM () const
void SetBPS (float fBPS)
void SetBPM (float fBPM)
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const BPMSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
float m_fBPS
The number of beats per second within this BPMSegment.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a song changes its BPM.
Constructor & Destructor Documentation
BPMSegment() [1/2]
BPMSegment::BPMSegment (int iStartRow = ROW_INVALID, float fBPM = 0.0f) inline
References SetBPM().
Referenced by Copy().
BPMSegment() [2/2]
BPMSegment::BPMSegment (const BPMSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* BPMSegment::Copy () const inline override virtual
Implements TimingSegment.
References BPMSegment().
DebugPrint()
void BPMSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetBPM(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetBPM()
float BPMSegment::GetBPM () const inline
References m_fBPS.
Referenced by AdjustSync::AutosyncTempo(), DebugPrint(), GetValues(), SongCacheIndex::InsertStepsTimingData(), TimingData::MultiplyBPMInBeatRange(), TimingData::NegStopAndBPMCheck(), TimingData::ScaleRegion(), Serialize(), ToString(), NotesWriterDWI::Write(), and WriteGlobalTags().
GetBPS()
float BPMSegment::GetBPS () const inline
References m_fBPS.
Referenced by ScreenSyncOverlay::Input(), and TimingData::MultiplyBPMInBeatRange().
GetEffectType()
SegmentEffectType BPMSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetType()
TimingSegmentType BPMSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_BPM.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> BPMSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetBPM().
IsNotable()
bool BPMSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool BPMSegment::operator== (const BPMSegment & other) const inline
References COMPARE_FLOAT, and m_fBPS.
Referenced by operator==().
operator==() [2/2]
bool BPMSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetBPM()
void BPMSegment::SetBPM (float fBPM) inline
References m_fBPS.
Referenced by BPMSegment(), TimingData::MultiplyBPMInBeatRange(), and TimingData::ScaleRegion().
SetBPS()
void BPMSegment::SetBPS (float fBPS) inline
References m_fBPS.
Referenced by ScreenSyncOverlay::Input().
ToString()
RString BPMSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetBPM(), IntToString(), and ssprintf().
Member Data Documentation
m_fBPS
float BPMSegment::m_fBPS private
The number of beats per second within this BPMSegment.
Referenced by GetBPM(), GetBPS(), operator==(), SetBPM(), and SetBPS().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp