Etterna: MatrixStack Class Reference
MatrixStack Class Reference
Public Member Functions
MatrixStack ()
void Pop ()
void Push ()
void LoadIdentity ()
void LoadMatrix (const RageMatrix &m)
void MultMatrix (const RageMatrix &m)
void MultMatrixLocal (const RageMatrix &m)
void RotateX (float degrees)
void RotateY (float degrees)
void RotateZ (float degrees)
void RotateXLocal (float degrees)
void RotateYLocal (float degrees)
void RotateZLocal (float degrees)
void Scale (float x, float y, float z)
void ScaleLocal (float x, float y, float z)
void Translate (float x, float y, float z)
void TranslateLocal (float x, float y, float z)
void SkewX (float fAmount)
void SkewY (float fAmount)
const RageMatrix * GetTop () const
void SetTop (const RageMatrix &m)
Private Attributes
vector< RageMatrix > stack
Constructor & Destructor Documentation
MatrixStack()
MatrixStack::MatrixStack () inline
References LoadIdentity().
Member Function Documentation
GetTop()
const RageMatrix* MatrixStack::GetTop () const inline
Referenced by RageDisplay::GetProjectionTop(), RageDisplay::GetTextureTop(), RageDisplay::GetViewTop(), and RageDisplay::GetWorldTop().
LoadIdentity()
void MatrixStack::LoadIdentity () inline
References RageMatrixIdentity().
Referenced by RageDisplay::LoadIdentity(), RageDisplay::LoadMenuPerspective(), and MatrixStack().
LoadMatrix()
void MatrixStack::LoadMatrix (const RageMatrix & m) inline
Referenced by RageDisplay::LoadLookAt(), and RageDisplay::LoadMenuPerspective().
MultMatrix()
void MatrixStack::MultMatrix (const RageMatrix & m) inline
References RageMatrixMultiply().
Referenced by RageDisplay::PostMultMatrix(), RotateX(), RotateY(), RotateZ(), Scale(), and Translate().
MultMatrixLocal()
void MatrixStack::MultMatrixLocal (const RageMatrix & m) inline
References RageMatrixMultiply().
Referenced by RageDisplay::PreMultMatrix(), RotateXLocal(), RotateYLocal(), RotateZLocal(), ScaleLocal(), SkewX(), SkewY(), and TranslateLocal().
Pop()
void MatrixStack::Pop () inline
References ASSERT.
Referenced by RageDisplay::CameraPopMatrix(), RageDisplay::PopMatrix(), and RageDisplay::TexturePopMatrix().
Push()
void MatrixStack::Push () inline
References ASSERT.
Referenced by RageDisplay::CameraPushMatrix(), RageDisplay::PushMatrix(), and RageDisplay::TexturePushMatrix().
RotateX()
void MatrixStack::RotateX (float degrees) inline
References MultMatrix(), and RageMatrixRotationX().
RotateXLocal()
void MatrixStack::RotateXLocal (float degrees) inline
References MultMatrixLocal(), and RageMatrixRotationX().
Referenced by RageDisplay::RotateX().
RotateY()
void MatrixStack::RotateY (float degrees) inline
References MultMatrix(), and RageMatrixRotationY().
RotateYLocal()
void MatrixStack::RotateYLocal (float degrees) inline
References MultMatrixLocal(), and RageMatrixRotationY().
Referenced by RageDisplay::RotateY().
RotateZ()
void MatrixStack::RotateZ (float degrees) inline
References MultMatrix(), and RageMatrixRotationZ().
RotateZLocal()
void MatrixStack::RotateZLocal (float degrees) inline
References MultMatrixLocal(), and RageMatrixRotationZ().
Referenced by RageDisplay::RotateZ().
Scale()
void MatrixStack::Scale (float x, float y, float z) inline
References MultMatrix(), and RageMatrixScaling().
Referenced by RageDisplay::LoadLookAt().
ScaleLocal()
void MatrixStack::ScaleLocal (float x, float y, float z) inline
References MultMatrixLocal(), and RageMatrixScaling().
Referenced by RageDisplay::Scale().
SetTop()
void MatrixStack::SetTop (const RageMatrix & m) inline
SkewX()
void MatrixStack::SkewX (float fAmount) inline
References MultMatrixLocal(), and RageMatrixSkewX().
Referenced by RageDisplay::SkewX().
SkewY()
void MatrixStack::SkewY (float fAmount) inline
References MultMatrixLocal(), and RageMatrixSkewY().
Referenced by RageDisplay::SkewY().
Translate()
void MatrixStack::Translate (float x, float y, float z) inline
References MultMatrix(), and RageMatrixTranslation().
Referenced by RageDisplay::TranslateWorld().
TranslateLocal()
void MatrixStack::TranslateLocal (float x, float y, float z) inline
References MultMatrixLocal(), and RageMatrixTranslation().
Referenced by RageDisplay::TextureTranslate(), and RageDisplay::Translate().
Member Data Documentation
stack
vector<RageMatrix> MatrixStack::stack private
The documentation for this class was generated from the following file:
RageDisplay.cpp