Etterna: SoundEffectControl Class Reference
SoundEffectControl Class Reference
Control a sound property through user input.
#include <SoundEffectControl.h>
Public Member Functions
SoundEffectControl ()
void Load (const RString &sType, PlayerState *pPlayerState, const NoteData *pNoteData)
void SetSoundReader (RageSoundReader *pPlayer)
void ReleaseSound ()
void Update (float fDeltaTime)
Private Member Functions
void HoldsBeingHeld (int iRow, int &iHoldsHeld, int &iHoldsLetGo) const
Private Attributes
ThemeMetric< RString > SOUND_PROPERTY
ThemeMetric< bool > LOCK_TO_HOLD
ThemeMetric< float > PROPERTY_MIN
ThemeMetric< float > PROPERTY_CENTER
ThemeMetric< float > PROPERTY_MAX
PlayerState * m_pPlayerState
bool m_bLocked
float m_fSample
float m_fLastLevel
const NoteData * m_pNoteData
RageSoundReader * m_pSoundReader
Detailed Description
Control a sound property through user input.
Constructor & Destructor Documentation
SoundEffectControl()
SoundEffectControl::SoundEffectControl ()
References m_bLocked, m_fLastLevel, m_fSample, m_pNoteData, and m_pPlayerState.
Member Function Documentation
HoldsBeingHeld()
void SoundEffectControl::HoldsBeingHeld (int iRow, int & iHoldsHeld, int & iHoldsLetGo) const private
References HoldNoteResult::bActive, NoteData::GetNumTracks(), NoteData::GetTapNoteRangeInclusive(), HoldNoteResult::hns, HNS_LetGo, TapNote::HoldResult, m_pNoteData, TapNoteType_HoldHead, and TapNote::type.
Referenced by Update().
Load()
void SoundEffectControl::Load (const RString & sType, PlayerState * pPlayerState, const NoteData * pNoteData)
References ThemeMetric< T >::Load(), LOCK_TO_HOLD, m_pNoteData, m_pPlayerState, PROPERTY_CENTER, PROPERTY_MAX, PROPERTY_MIN, and SOUND_PROPERTY.
ReleaseSound()
void SoundEffectControl::ReleaseSound () inline
References SetSoundReader().
SetSoundReader()
void SoundEffectControl::SetSoundReader (RageSoundReader * pPlayer)
References m_pSoundReader.
Referenced by ReleaseSound().
Update()
void SoundEffectControl::Update (float fDeltaTime)
References SampleHistory::AddSample(), BeatToNoteRow(), CLAMP(), f, GAME_BUTTON_EFFECT_DOWN, GAME_BUTTON_EFFECT_UP, GAMESTATE, InputMapper::GetLevel(), HoldsBeingHeld(), INPUTMAPPER, LOCK_TO_HOLD, m_bLocked, PlayerState::m_EffectHistory, m_fLastLevel, m_fSample, SongPosition::m_fSongBeat, PlayerState::m_PlayerNumber, GameState::m_Position, m_pPlayerState, m_pSoundReader, PROPERTY_CENTER, PROPERTY_MAX, PROPERTY_MIN, SCALE, RageSoundReader::SetProperty(), and SOUND_PROPERTY.
Member Data Documentation
LOCK_TO_HOLD
ThemeMetric<bool> SoundEffectControl::LOCK_TO_HOLD private
Referenced by Load(), and Update().
m_bLocked
bool SoundEffectControl::m_bLocked private
Referenced by SoundEffectControl(), and Update().
m_fLastLevel
float SoundEffectControl::m_fLastLevel private
Referenced by SoundEffectControl(), and Update().
m_fSample
float SoundEffectControl::m_fSample private
Referenced by SoundEffectControl(), and Update().
m_pNoteData
const NoteData* SoundEffectControl::m_pNoteData private
Referenced by HoldsBeingHeld(), Load(), and SoundEffectControl().
m_pPlayerState
PlayerState* SoundEffectControl::m_pPlayerState private
Referenced by Load(), SoundEffectControl(), and Update().
m_pSoundReader
RageSoundReader* SoundEffectControl::m_pSoundReader private
Referenced by SetSoundReader(), and Update().
PROPERTY_CENTER
ThemeMetric<float> SoundEffectControl::PROPERTY_CENTER private
Referenced by Load(), and Update().
PROPERTY_MAX
ThemeMetric<float> SoundEffectControl::PROPERTY_MAX private
Referenced by Load(), and Update().
PROPERTY_MIN
ThemeMetric<float> SoundEffectControl::PROPERTY_MIN private
Referenced by Load(), and Update().
SOUND_PROPERTY
ThemeMetric<RString> SoundEffectControl::SOUND_PROPERTY private
Referenced by Load(), and Update().
The documentation for this class was generated from the following files:
SoundEffectControl.h
SoundEffectControl.cpp