Etterna: NotesWriterJson Namespace Reference
NotesWriterJson Namespace Reference
Functions
bool WriteSong (const RString &sFile, const Song &out, bool bWriteSteps)
bool WriteSteps (const RString &sFile, const Steps &out)
Function Documentation
WriteSong()
bool NotesWriterJson::WriteSong (const RString & sFile, const Song & out, bool bWriteSteps)
References DISPLAY_BPM_SPECIFIED, FOREACH_BackgroundLayer, FOREACH_CONST, Song::GetAllSteps(), Song::GetBackgroundChanges(), Song::GetFirstBeat(), Song::GetForegroundChanges(), Song::GetLastBeat(), Song::GetSongDir(), Song::m_bHasBanner, Song::m_bHasMusic, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicLengthSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_LyricSegments, Song::m_sArtist, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_SelectionDisplay, Song::m_sGenre, Song::m_sGroupName, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sSongFileName, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Song::m_vsKeysoundFile, Serialize(), JsonUtil::SerializeArrayValues(), JsonUtil::SerializeVectorObjects(), Song::SHOW_ALWAYS, Song::SHOW_NEVER, StringConversion::ToString(), and JsonUtil::WriteFile().
Referenced by Song::SaveToJsonFile().
WriteSteps()
bool NotesWriterJson::WriteSteps (const RString & sFile, const Steps & out)
References Serialize(), and JsonUtil::WriteFile().