Etterna: LuaReference Class Reference
LuaReference Class Reference
A self-cleaning Lua reference.
#include <LuaReference.h>
Public Member Functions
LuaReference ()
virtual ~LuaReference ()
LuaReference (const LuaReference &cpy)
LuaReference & operator= (const LuaReference &cpy)
LuaReference (Lua *L)
void swap (LuaReference &other)
void SetFromStack (Lua *L)
void SetFromNil ()
bool SetFromExpression (const std::string &sExpression)
void DeepCopy ()
Deep-copy tables, detaching this reference from any others.
virtual void PushSelf (Lua *L) const
bool IsSet () const
Determine if the reference is set.
bool IsNil () const
Determine if the reference is nil.
void Unset ()
int GetLuaType () const
std::string Serialize () const
Static Public Member Functions
template<typename T >
static LuaReference Create (const T &val)
template<class T >
static LuaReference CreateFromPush (T &obj)
Private Member Functions
void Unregister ()
Private Attributes
int m_iReference
Detailed Description
A self-cleaning Lua reference.
Constructor & Destructor Documentation
LuaReference() [1/3]
LuaReference::LuaReference ()
~LuaReference()
LuaReference::~LuaReference () virtual
References Unregister().
LuaReference() [2/3]
LuaReference::LuaReference (const LuaReference & cpy)
References LuaManager::Get(), L, LUA, m_iReference, and LuaManager::Release().
LuaReference() [3/3]
LuaReference::LuaReference (Lua * L) inline
References SetFromStack().
Member Function Documentation
Create()
template<typename T > static LuaReference LuaReference::Create (const T & val) inline static
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetFromStack().
Referenced by ScreenGameplayLesson::Init(), ScreenSelectMaster::Init(), ScreenEvaluation::Init(), Player::Init(), LifeMeterBattery::Load(), PaneDisplay::Load(), ControllerStateDisplay::LoadInternal(), NoteSkinManager::PushActorTemplate(), LifeMeterTime::SendLifeChangedMessage(), and LyricDisplay::Update().
CreateFromPush()
template<class T > static LuaReference LuaReference::CreateFromPush (T & obj) inline static
References LuaManager::Get(), L, LUA, PushSelf(), LuaManager::Release(), and SetFromStack().
Referenced by LifeMeterBar::AfterLifeChanged(), LifeMeterBattery::BroadcastLifeChanged(), Download::Failed(), ScoreDisplayNormal::Init(), Download::Install(), StepsDisplay::Load(), Player::SendComboMessages(), LifeMeterTime::SendLifeChangedMessage(), and StepsDisplay::SetInternal().
DeepCopy()
void LuaReference::DeepCopy ()
Deep-copy tables, detaching this reference from any others.
References LuaHelpers::DeepCopy(), LuaManager::Get(), L, LUA, PushSelf(), LuaManager::Release(), and SetFromStack().
Referenced by LuaClass::LuaClass(), and LuaClass::operator=().
GetLuaType()
int LuaReference::GetLuaType () const
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
Referenced by ScreenSelectMaster::Init(), ScreenGameplay::Init(), PercentageDisplay::Load(), PercentageDisplay::LoadFromNode(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), PercentageDisplay::Refresh(), OptionRowHandlerLua::SanityCheckTable(), and LuaExpressionTransform::SetFromReference().
IsNil()
bool LuaReference::IsNil () const
Determine if the reference is nil.
Returns
true if it's nil.
References m_iReference.
Referenced by GameCommand::ApplySelf(), ActorFrame::DrawPrimitives(), ScreenTextEntry::End(), FormatAnswerForDisplayFromLua(), ActorScroller::LoadFromNode(), GameCommand::LoadOne(), NoteSkinManager::PushActorTemplate(), Actor::RunCommands(), OptionRowHandlerLua::SetEnabledForPlayers(), LuaExpressionTransform::TransformItemDirect(), ScreenTextEntry::TryAppendToAnswer(), ScreenTextEntry::UpdateAnswerText(), and ActorFrame::UpdateInternal().
IsSet()
bool LuaReference::IsSet () const
Determine if the reference is set.
SetFromNil() counts as being set.
Returns
true if it's set.
References m_iReference.
Referenced by GameCommand::ApplySelf(), ScreenTextEntry::End(), FormatAnswerForDisplayFromLua(), GetGlobalTable(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), ThemeMetric< AutoPtrCopyOnWrite >::IsLoaded(), LuaClass::LuaClass(), LuaClass::operator=(), Actor::PlayCommandNoRecurse(), ThemeMetric< AutoPtrCopyOnWrite >::PushSelf(), Actor::RunCommands(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), LuaThreadVariable::SetFromStack(), ScreenTextEntry::TryAppendToAnswer(), and ScreenTextEntry::UpdateAnswerText().
operator=()
LuaReference & LuaReference::operator= (const LuaReference & cpy)
References LuaManager::Get(), L, LUA, m_iReference, LuaManager::Release(), and Unregister().
Referenced by LuaClass::operator=().
PushSelf()
void LuaReference::PushSelf (Lua * L) const virtual
References m_iReference.
Referenced by Actor::Actor(), GameCommand::ApplySelf(), CheckEnum(), DynamicActorScroller::ConfigureActor(), CreateFromPush(), DeepCopy(), ActorFrame::DrawPrimitives(), LunaGameState::Env(), OptionRowHandlerLua::ExportOption(), FormatAnswerForDisplayFromLua(), LuaTable::Get(), LunaStyle::GetColumnInfo(), LunaActorFrame::GetDrawFunction(), GetGlobalTable(), GetLuaType(), LunaNoteSkinManager::GetMetricA(), LunaProfile::GetUserTable(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), OptionRowHandlerLua::ImportOption(), ScreenSelectMaster::Init(), ScreenGameplay::Init(), Profile::LoadCustomFunction(), DynamicActorScroller::LoadFromNode(), OptionRowHandlerLua::LoadInternal(), NoteSkinManager::LoadNoteSkinDataRecursive(), ActorUtil::LoadTableFromStackShowErrors(), LuaThreadVariable::LuaThreadVariable(), Message::Message(), OptionRowHandlerLua::NotifyOfSelection(), Enum::Push(), NoteSkinManager::PushActorTemplate(), Actor::PushContext(), Message::PushParamTable(), ThemeMetric< AutoPtrCopyOnWrite >::PushSelf(), XNodeLuaValue::PushValue(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), PercentageDisplay::Refresh(), Actor::RunCommands(), OptionRowHandlerLua::SanityCheckTable(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), Serialize(), LuaTable::Set(), OptionRowHandlerLua::SetEnabledForPlayers(), LuaThreadVariable::SetFromStack(), Enum::SetMetatable(), Message::SetParamTable(), MenuTimer::SetText(), LuaExpressionTransform::TransformItemDirect(), ActorFrame::UpdateInternal(), LuaClass::~LuaClass(), and LuaThreadVariable::~LuaThreadVariable().
Serialize()
std::string LuaReference::Serialize () const
References ASSERT_M, LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
SetFromExpression()
bool LuaReference::SetFromExpression (const std::string & sExpression)
References LuaManager::Get(), L, LUA, LuaManager::Release(), LuaHelpers::RunExpression(), and SetFromStack().
Referenced by PercentageDisplay::Load(), PercentageDisplay::LoadFromNode(), OptionRowHandlerLua::LoadInternal(), GameCommand::LoadOne(), PercentageDisplay::PercentageDisplay(), and ActorScroller::SetTransformFromExpression().
SetFromNil()
void LuaReference::SetFromNil ()
References m_iReference, and Unregister().
Referenced by ActorFrame::ActorFrame(), NoteField::NoteField(), LocalizedStringImplThemeMetric::Read(), and LuaExpressionTransform::SetFromReference().
SetFromStack()
void LuaReference::SetFromStack (Lua * L)
References m_iReference.
Referenced by LunaActor::addcommand(), LunaMessageManager::Broadcast(), Create(), CreateFromPush(), DeepCopy(), GetGlobalTable(), ThemeManager::GetMetric(), XMLProfile::LoadEttGeneralDataFromNode(), DynamicActorScroller::LoadFromNode(), PercentageDisplay::LoadFromNode(), ActorScroller::LoadFromNode(), Actor::LoadFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), OptionRowHandlerLua::LoadInternal(), NoteSkinManager::LoadNoteSkinDataRecursive(), ActorUtil::LoadTableFromStackShowErrors(), LuaReference(), LuaTable::LuaTable(), LuaThreadVariable::LuaThreadVariable(), Message::Message(), LunaActor::playcommand(), LunaActorFrame::RunCommandsOnChildren(), LunaActorFrame::runcommandsonleaves(), LunaActor::RunCommandsRecursively(), LunaActorFrame::SetDrawFunction(), SetFromExpression(), LuaThreadVariable::SetFromStack(), Message::SetParamTable(), LunaActorFrame::SetUpdateFunction(), XNodeLuaValue::SetValueFromStack(), and XmlFileUtil::XNodeFromTable().
swap()
void LuaReference::swap (LuaReference & other) inline
Unregister()
void LuaReference::Unregister () private
References LuaManager::Get(), L, LUA, m_iReference, and LuaManager::Release().
Referenced by operator=(), SetFromNil(), Unset(), and ~LuaReference().
Unset()
void LuaReference::Unset () inline
References Unregister().
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::Clear(), GameCommand::GameCommand(), GameCommand::Init(), OptionRowHandlerLua::Init(), Profile::InitGeneralData(), Profile::Profile(), and ThemeMetric< AutoPtrCopyOnWrite >::Read().
Member Data Documentation
m_iReference
int LuaReference::m_iReference private
Referenced by IsNil(), IsSet(), LuaReference(), operator=(), PushSelf(), SetFromNil(), SetFromStack(), and Unregister().
The documentation for this class was generated from the following files:
LuaReference.h
LuaReference.cpp