Etterna: ScreenSaveSync.cpp File Reference
ScreenSaveSync.cpp File Reference
#include "ScreenSaveSync.h"
#include "AdjustSync.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "PrefsManager.h"
#include "Song.h"
#include "global.h"
Functions
static RString GetPromptText ()
static void SaveSyncChanges (void *pThrowAway)
static void RevertSyncChanges (void *pThrowAway)
Variables
static LocalizedString CHANGED_TIMING_OF ("ScreenSaveSync", "You have changed the timing of")
static LocalizedString WOULD_YOU_LIKE_TO_SAVE ("ScreenSaveSync", "Would you like to save these changes?")
static LocalizedString CHOOSING_NO_WILL_DISCARD ("ScreenSaveSync", "Choosing NO will discard your changes.")
Function Documentation
GetPromptText()
static RString GetPromptText () static
References CHANGED_TIMING_OF, CHOOSING_NO_WILL_DISCARD, GAMESTATE, Song::GetDisplayFullTitle(), AdjustSync::GetSyncChangeTextGlobal(), AdjustSync::GetSyncChangeTextSong(), LocalizedString::GetValue(), Rage::join(), GameState::m_pCurSong, ssprintf(), and WOULD_YOU_LIKE_TO_SAVE.
Referenced by ScreenSaveSync::Init(), and ScreenSaveSync::PromptSaveSync().
RevertSyncChanges()
static void RevertSyncChanges (void * pThrowAway) static
References AdjustSync::RevertSyncChanges().
Referenced by ScreenSaveSync::Init(), ScreenSyncOverlay::Input(), and ScreenSaveSync::PromptSaveSync().
SaveSyncChanges()
static void SaveSyncChanges (void * pThrowAway) static
References AdjustSync::SaveSyncChanges().
Referenced by ScreenSaveSync::Init(), and ScreenSaveSync::PromptSaveSync().
Variable Documentation
CHANGED_TIMING_OF
LocalizedString CHANGED_TIMING_OF("ScreenSaveSync", "You have changed the timing of") static
Referenced by GetPromptText().
CHOOSING_NO_WILL_DISCARD
LocalizedString CHOOSING_NO_WILL_DISCARD("ScreenSaveSync", "Choosing NO will discard your changes.") static
Referenced by GetPromptText().
WOULD_YOU_LIKE_TO_SAVE
LocalizedString WOULD_YOU_LIKE_TO_SAVE("ScreenSaveSync", "Would you like to save these changes?") static
Referenced by GetPromptText().