Etterna: SMALoader Struct Reference
SMALoader Struct Reference
Reads a Song from a .SMA file.
#include <NotesLoaderSMA.h>
Public Member Functions
SMALoader ()
bool LoadFromSimfile (const RString &sPath, Song &out, bool bFromCache=false) override
Attempt to load the specified sm file.
void ProcessBeatsPerMeasure (TimingData &out, const RString &sParam)
void ProcessMultipliers (TimingData &out, int iRowsPerBeat, const RString &sParam)
void ProcessSpeeds (TimingData &out, const RString &line, int rowsPerBeat) override
Process the Speed Segments from the string.
Public Member Functions inherited from SMLoader
SMLoader ()
SMLoader (RString ext)
virtual ~SMLoader ()=default
virtual bool LoadFromDir (const RString &sPath, Song &out, bool load_autosave=false)
Attempt to load a song from a specified path.
virtual bool LoadNoteDataFromSimfile (const RString &path, Steps &out)
Retrieve the relevant notedata from the simfile.
virtual void GetApplicableFiles (const RString &sPath, vector< RString > &out, bool load_autosave=false)
Retrieve the list of .sm files.
virtual bool LoadEditFromFile (const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL)
virtual bool LoadEditFromBuffer (const RString &sBuffer, const RString &sEditFilePath, ProfileSlot slot, Song *givenSong=NULL)
virtual bool LoadEditFromMsd (const MsdFile &msd, const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL)
virtual bool LoadFromBGChangesString (BackgroundChange &change, const RString &sBGChangeExpression)
void ParseBPMs (vector< pair< float, float >> &out, const RString &line, const int rowsPerBeat=-1)
Parse BPM Changes data from a string.
void ProcessBPMs (TimingData &out, const vector< pair< float, float >> &vBPMChanges)
Process the BPM Segments from the string.
void ParseStops (vector< pair< float, float >> &out, const RString line, const int rowsPerBeat=-1)
Parse Stops data from a string.
void ProcessStops (TimingData &out, const vector< pair< float, float >> &vStops)
Process the Stop Segments from the data.
void ProcessBPMsAndStops (TimingData &out, vector< pair< float, float >> &vBPMs, vector< pair< float, float >> &vStops)
Process BPM and stop segments from the data.
void ProcessDelays (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Delay Segments from the string.
void ProcessTimeSignatures (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Time Signature Segments from the string.
void ProcessTickcounts (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Tickcount Segments from the string.
virtual void ProcessCombos (TimingData &, const RString &line, int=-1)
virtual void ProcessFakes (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Fake Segments from the string.
virtual void ProcessBGChanges (Song &out, const RString &sValueName, const RString &sPath, const RString &sParam)
void ProcessInstrumentTracks (Song &out, const RString &sParam)
virtual void SetSongTitle (const RString &title)
Set the song title.
virtual RString GetSongTitle () const
Get the song title.
Additional Inherited Members
Static Public Member Functions inherited from SMLoader
static void TidyUpData (Song &song, bool bFromCache)
Perform some cleanup on the loaded song.
static void ProcessDelays (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTimeSignatures (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTickcounts (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessSpeeds (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessFakes (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static float RowToBeat (const RString &line, const int rowsPerBeat)
Convert a row value to the proper beat value.
Protected Member Functions inherited from SMLoader
virtual void LoadFromTokens (RString sStepsType, RString sDescription, RString sDifficulty, RString sMeter, RString sRadarValues, RString sNoteData, Steps &out)
Process the different tokens we have available to get NoteData.
RString GetFileExtension () const
Retrieve the file extension associated with this loader.
Detailed Description
Reads a Song from a .SMA file.
Constructor & Destructor Documentation
SMALoader()
SMALoader::SMALoader () inline
Member Function Documentation
LoadFromSimfile()
bool SMALoader::LoadFromSimfile (const RString & sPath, Song & out, bool bFromCache = false) override virtual
Attempt to load the specified sm file.
Parameters
sPath a const reference to the path on the hard drive to check.
out a reference to the Song that will retrieve the song information.
bFromCache a check to see if we are getting certain information from the cache file.
Returns
its success or failure.
Reimplemented from SMLoader.
References Song::AddForegroundChange(), Song::AddSteps(), DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, EqualsNoCase(), MsdFile::GetError(), MsdFile::GetNumParams(), MsdFile::GetNumValues(), MsdFile::GetValue(), HHMMSSToSeconds(), StdString::CStdStr< CT >::Left(), SMLoader::LoadFromBGChangesString(), SMLoader::LoadFromTokens(), LOG, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_sArtist, Song::m_sArtistTranslit, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_SelectionDisplay, TimingData::m_sFile, Song::m_sGenre, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sPreviewVidFile, Song::m_sSongFileName, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Steps::m_Timing, Song::m_vsKeysoundFile, StdString::CStdStr< CT >::MakeUpper(), SMLoader::ParseBPMs(), SMLoader::ParseStops(), ProcessBeatsPerMeasure(), SMLoader::ProcessBGChanges(), SMLoader::ProcessBPMsAndStops(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SMLoader::ProcessInstrumentTracks(), ProcessMultipliers(), ProcessSpeeds(), SMLoader::ProcessTickcounts(), MsdFile::ReadFile(), Steps::SetFilename(), SMLoader::SetSongTitle(), Song::SHOW_ALWAYS, Song::SHOW_NEVER, split(), StringToFloat(), StringToInt(), SMLoader::TidyUpData(), RageLog::Trace(), Trim(), and RageLog::UserLog().
ProcessBeatsPerMeasure()
void SMALoader::ProcessBeatsPerMeasure (TimingData & out, const RString & sParam)
References TimingData::AddSegment(), BeatToNoteRow(), FOREACH_CONST, SMLoader::GetSongTitle(), LOG, split(), StringToFloat(), StringToInt(), and RageLog::UserLog().
Referenced by LoadFromSimfile().
ProcessMultipliers()
void SMALoader::ProcessMultipliers (TimingData & out, int iRowsPerBeat, const RString & sParam)
References TimingData::AddSegment(), BeatToNoteRow(), f, SMLoader::GetSongTitle(), LOG, SMLoader::RowToBeat(), split(), StringToInt(), and RageLog::UserLog().
Referenced by LoadFromSimfile().
ProcessSpeeds()
void SMALoader::ProcessSpeeds (TimingData & out, const RString & line, int rowsPerBeat) override virtual
Process the Speed Segments from the string.
Parameters
out the TimingData being modified.
line the string in question.
rowsPerBeat the number of rows per beat for this purpose.
Reimplemented from SMLoader.
References TimingData::AddSegment(), BeatToNoteRow(), FOREACH_CONST, SMLoader::GetSongTitle(), LOG, SMLoader::RowToBeat(), split(), StringToFloat(), Trim(), SpeedSegment::UNIT_BEATS, SpeedSegment::UNIT_SECONDS, and RageLog::UserLog().
Referenced by LoadFromSimfile().
The documentation for this struct was generated from the following files:
NotesLoaderSMA.h
NotesLoaderSMA.cpp