Etterna: NetProtocol Class Reference
NetProtocol Class Reference
#include <NetworkSyncManager.h>
Public Member Functions
virtual bool Connect (NetworkSyncManager *n, unsigned short port, RString address)
virtual void close ()
virtual void Update (NetworkSyncManager *n, float fDeltaTime)
virtual void CreateNewRoom (RString name, RString desc, RString password)
virtual void SelectUserSong (NetworkSyncManager *n, Song *song)
virtual void EnterRoom (RString name, RString password)
virtual void LeaveRoom (NetworkSyncManager *n)
virtual void RequestRoomInfo (RString name)
virtual void SendChat (const RString &message, string tab, int type)
virtual void ReportNSSOnOff (int i)
virtual void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset, int numNotes)
virtual void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset)
virtual void ReportHighScore (HighScore *hs, PlayerStageStats &pss)
virtual void ReportSongOver (NetworkSyncManager *n)
virtual void ReportStyle (NetworkSyncManager *n)
virtual void StartRequest (NetworkSyncManager *n, short position)
virtual void Login (RString user, RString pass)
virtual void Logout ()
virtual void OnMusicSelect ()
virtual void OffMusicSelect ()
virtual void OnRoomSelect ()
virtual void OffRoomSelect ()
virtual void OnOptions ()
virtual void OffOptions ()
virtual void OnEval ()
virtual void OffEval ()
Public Attributes
RString serverName
int serverVersion { 0 }
Member Function Documentation
close()
virtual void NetProtocol::close () inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Connect()
virtual bool NetProtocol::Connect (NetworkSyncManager * n, unsigned short port, RString address) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
CreateNewRoom()
virtual void NetProtocol::CreateNewRoom (RString name, RString desc, RString password) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::CreateNewRoom().
EnterRoom()
virtual void NetProtocol::EnterRoom (RString name, RString password) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::EnterRoom().
LeaveRoom()
virtual void NetProtocol::LeaveRoom (NetworkSyncManager * n) inline virtual
Reimplemented in ETTProtocol.
Referenced by NetworkSyncManager::LeaveRoom().
Login()
virtual void NetProtocol::Login (RString user, RString pass) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::Login().
Logout()
virtual void NetProtocol::Logout () inline virtual
Reimplemented in ETTProtocol.
Referenced by NetworkSyncManager::Logout().
OffEval()
virtual void NetProtocol::OffEval () inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::OffEval().
OffMusicSelect()
virtual void NetProtocol::OffMusicSelect () inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::OffMusicSelect().
OffOptions()
virtual void NetProtocol::OffOptions () inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::OffOptions().
OffRoomSelect()
virtual void NetProtocol::OffRoomSelect () inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::OffRoomSelect().
OnEval()
virtual void NetProtocol::OnEval () inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::OnEval().
OnMusicSelect()
virtual void NetProtocol::OnMusicSelect () inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::OnMusicSelect().
OnOptions()
virtual void NetProtocol::OnOptions () inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::OnOptions().
OnRoomSelect()
virtual void NetProtocol::OnRoomSelect () inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::OnRoomSelect().
ReportHighScore()
virtual void NetProtocol::ReportHighScore (HighScore * hs, PlayerStageStats & pss) inline virtual
Reimplemented in ETTProtocol.
Referenced by NetworkSyncManager::ReportHighScore().
ReportNSSOnOff()
virtual void NetProtocol::ReportNSSOnOff (int i) inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::ReportNSSOnOff().
ReportScore() [1/2]
virtual void NetProtocol::ReportScore (NetworkSyncManager * n, int playerID, int step, int score, int combo, float offset, int numNotes) inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::ReportScore().
ReportScore() [2/2]
virtual void NetProtocol::ReportScore (NetworkSyncManager * n, int playerID, int step, int score, int combo, float offset) inline virtual
Reimplemented in SMOProtocol.
ReportSongOver()
virtual void NetProtocol::ReportSongOver (NetworkSyncManager * n) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::ReportSongOver().
ReportStyle()
virtual void NetProtocol::ReportStyle (NetworkSyncManager * n) inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::ReportStyle().
RequestRoomInfo()
virtual void NetProtocol::RequestRoomInfo (RString name) inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::RequestRoomInfo().
SelectUserSong()
virtual void NetProtocol::SelectUserSong (NetworkSyncManager * n, Song * song) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::SelectUserSong().
SendChat()
virtual void NetProtocol::SendChat (const RString & message, string tab, int type) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::SendChat().
StartRequest()
virtual void NetProtocol::StartRequest (NetworkSyncManager * n, short position) inline virtual
Reimplemented in SMOProtocol.
Referenced by NetworkSyncManager::StartRequest().
Update()
virtual void NetProtocol::Update (NetworkSyncManager * n, float fDeltaTime) inline virtual
Reimplemented in ETTProtocol, and SMOProtocol.
Referenced by NetworkSyncManager::Update().
Member Data Documentation
serverName
RString NetProtocol::serverName
Referenced by SMOProtocol::close(), ETTProtocol::close(), SMOProtocol::Connect(), NetworkSyncManager::DisplayStartupStatus(), NetworkSyncManager::GetServerName(), NetworkSyncManager::PostStartUp(), and ETTProtocol::Update().
serverVersion
int NetProtocol::serverVersion { 0 }
Referenced by SMOProtocol::close(), ETTProtocol::close(), SMOProtocol::Connect(), NetworkSyncManager::GetServerVersion(), NetworkSyncManager::PostStartUp(), SMOProtocol::ProcessInput(), SMOProtocol::SelectUserSong(), SMOProtocol::StartRequest(), and ETTProtocol::Update().
The documentation for this class was generated from the following file:
NetworkSyncManager.h