Etterna: ThreadData Class Reference
ThreadData Class Reference
#include <RageThreads.h>
Public Member Functions
void waitForUpdate ()
void setUpdated (bool b)
bool getUpdated ()
Public Attributes
std::atomic< int > _threadsFinished { 0 }
std::atomic< int > _progress { 0 }
std::mutex _updatedMutex
std::condition_variable _updatedCV
void * data { nullptr }
Private Attributes
std::atomic< bool > _updated { false }
Member Function Documentation
getUpdated()
bool ThreadData::getUpdated () inline
References _updated.
Referenced by waitForUpdate().
setUpdated()
void ThreadData::setUpdated (bool b) inline
References _updated, _updatedCV, and _updatedMutex.
Referenced by SongCacheIndex::LoadCache(), SongManager::LoadStepManiaSongDir(), parallelExecution(), and ScoreManager::RecalculateSSRs().
waitForUpdate()
void ThreadData::waitForUpdate () inline
References _updatedCV, _updatedMutex, and getUpdated().
Referenced by SongCacheIndex::LoadCache(), and parallelExecution().
Member Data Documentation
_progress
std::atomic<int> ThreadData::_progress { 0 }
Referenced by SongCacheIndex::LoadCache(), SongManager::LoadStepManiaSongDir(), parallelExecution(), and ScoreManager::RecalculateSSRs().
_threadsFinished
std::atomic<int> ThreadData::_threadsFinished { 0 }
Referenced by SongCacheIndex::LoadCache(), and parallelExecution().
_updated
std::atomic<bool> ThreadData::_updated { false } private
Referenced by getUpdated(), and setUpdated().
_updatedCV
std::condition_variable ThreadData::_updatedCV
Referenced by setUpdated(), and waitForUpdate().
_updatedMutex
std::mutex ThreadData::_updatedMutex
Referenced by setUpdated(), and waitForUpdate().
data
void* ThreadData::data { nullptr }
Referenced by SongManager::LoadStepManiaSongDir(), parallelExecution(), and ScoreManager::RecalculateSSRs().
The documentation for this class was generated from the following file:
RageThreads.h