Etterna: NoteField.cpp File Reference
NoteField.cpp File Reference
#include "NoteField.h"
#include "ArrowEffects.h"
#include "BackgroundUtil.h"
#include "CommonMetrics.h"
#include "GameConstantsAndTypes.h"
#include "GameState.h"
#include "NoteData.h"
#include "NoteSkinManager.h"
#include "PlayerState.h"
#include "RageDisplay.h"
#include "RageLog.h"
#include "RageMath.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "ScreenDimensions.h"
#include "Song.h"
#include "Style.h"
#include "ThemeManager.h"
#include "global.h"
#include <cfloat>
#include "LuaBinding.h"
Classes
class LunaNoteField
Allow Lua to have access to the Notefield.
Macros
#define IS_ON_SCREEN(fBeat)
#define draw_all_segments(str_exp, name, caps_name)
#define OPEN_CALLBACK_BLOCK(member_name)
#define OPEN_RUN_BLOCK(arg_count)
#define CLOSE_RUN_AND_CALLBACK_BLOCKS
#define PUSH_COLUMN lua_pushnumber(L, col + 1)
#define SET_CALLBACK_GENERIC(callback_name, member_name)
Functions
void FindDisplayedBeats (const PlayerState *pPlayerState, float &firstBeat, float &lastBeat, int iDrawDistanceAfterTargetsPixels, int iDrawDistanceBeforeTargetsPixels)
static RString RoutineNoteSkinName (size_t i)
static CacheNoteStat GetNumNotesFromBeginning (const PlayerState *pPlayerState, float beat)
static int GetNumNotesRange (const PlayerState *pPlayerState, float fLow, float fHigh)
static void get_returned_column (Lua *L, PlayerNumber pn, int index, int &col)
template<class T >
static void get_returned_score (Lua *L, int index, T &score)
static void get_returned_bright (Lua *L, int index, bool &bright)
Variables
static ThemeMetric< bool > SHOW_BOARD ("NoteField", "ShowBoard")
static ThemeMetric< bool > SHOW_BEAT_BARS ("NoteField", "ShowBeatBars")
static ThemeMetric< float > FADE_BEFORE_TARGETS_PERCENT ("NoteField", "FadeBeforeTargetsPercent")
static ThemeMetric< float > BAR_MEASURE_ALPHA ("NoteField", "BarMeasureAlpha")
static ThemeMetric< float > BAR_4TH_ALPHA ("NoteField", "Bar4thAlpha")
static ThemeMetric< float > BAR_8TH_ALPHA ("NoteField", "Bar8thAlpha")
static ThemeMetric< float > BAR_16TH_ALPHA ("NoteField", "Bar16thAlpha")
static ThemeMetric< float > FADE_FAIL_TIME ("NoteField", "FadeFailTime")
static Preference< float > ihatethisprogram ("NotefieldXRatio", 1.f)
static ThemeMetric1D< RString > ROUTINE_NOTESKIN ("NoteField", RoutineNoteSkinName, NUM_PLAYERS)
static ThemeMetric< RageColor > AREA_HIGHLIGHT_COLOR ("NoteField", "AreaHighlightColor")
static ThemeMetric< RageColor > BPM_COLOR ("NoteField", "BPMColor")
static ThemeMetric< RageColor > STOP_COLOR ("NoteField", "StopColor")
static ThemeMetric< RageColor > DELAY_COLOR ("NoteField", "DelayColor")
static ThemeMetric< RageColor > WARP_COLOR ("NoteField", "WarpColor")
static ThemeMetric< RageColor > TIME_SIG_COLOR ("NoteField", "TimeSignatureColor")
static ThemeMetric< RageColor > TICKCOUNT_COLOR ("NoteField", "TickcountColor")
static ThemeMetric< RageColor > COMBO_COLOR ("NoteField", "ComboColor")
static ThemeMetric< RageColor > LABEL_COLOR ("NoteField", "LabelColor")
static ThemeMetric< RageColor > SPEED_COLOR ("NoteField", "SpeedColor")
static ThemeMetric< RageColor > SCROLL_COLOR ("NoteField", "ScrollColor")
static ThemeMetric< RageColor > FAKE_COLOR ("NoteField", "FakeColor")
static ThemeMetric< bool > BPM_IS_LEFT_SIDE ("NoteField", "BPMIsLeftSide")
static ThemeMetric< bool > STOP_IS_LEFT_SIDE ("NoteField", "StopIsLeftSide")
static ThemeMetric< bool > DELAY_IS_LEFT_SIDE ("NoteField", "DelayIsLeftSide")
static ThemeMetric< bool > WARP_IS_LEFT_SIDE ("NoteField", "WarpIsLeftSide")
static ThemeMetric< bool > TIME_SIG_IS_LEFT_SIDE ("NoteField", "TimeSignatureIsLeftSide")
static ThemeMetric< bool > TICKCOUNT_IS_LEFT_SIDE ("NoteField", "TickcountIsLeftSide")
static ThemeMetric< bool > COMBO_IS_LEFT_SIDE ("NoteField", "ComboIsLeftSide")
static ThemeMetric< bool > LABEL_IS_LEFT_SIDE ("NoteField", "LabelIsLeftSide")
static ThemeMetric< bool > SPEED_IS_LEFT_SIDE ("NoteField", "SpeedIsLeftSide")
static ThemeMetric< bool > SCROLL_IS_LEFT_SIDE ("NoteField", "ScrollIsLeftSide")
static ThemeMetric< bool > FAKE_IS_LEFT_SIDE ("NoteField", "FakeIsLeftSide")
static ThemeMetric< float > BPM_OFFSETX ("NoteField", "BPMOffsetX")
static ThemeMetric< float > STOP_OFFSETX ("NoteField", "StopOffsetX")
static ThemeMetric< float > DELAY_OFFSETX ("NoteField", "DelayOffsetX")
static ThemeMetric< float > WARP_OFFSETX ("NoteField", "WarpOffsetX")
static ThemeMetric< float > TIME_SIG_OFFSETX ("NoteField", "TimeSignatureOffsetX")
static ThemeMetric< float > TICKCOUNT_OFFSETX ("NoteField", "TickcountOffsetX")
static ThemeMetric< float > COMBO_OFFSETX ("NoteField", "ComboOffsetX")
static ThemeMetric< float > LABEL_OFFSETX ("NoteField", "LabelOffsetX")
static ThemeMetric< float > SPEED_OFFSETX ("NoteField", "SpeedOffsetX")
static ThemeMetric< float > SCROLL_OFFSETX ("NoteField", "ScrollOffsetX")
static ThemeMetric< float > FAKE_OFFSETX ("NoteField", "FakeOffsetX")
Macro Definition Documentation
CLOSE_RUN_AND_CALLBACK_BLOCKS
#define CLOSE_RUN_AND_CALLBACK_BLOCKS
Value:
}                                                                          \
    lua_settop(L, 0);                                                          \
    LUA->Release(L);                                                           \
    }
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), NoteField::SetPressed(), and NoteField::Step().
draw_all_segments
#define draw_all_segments (str_exp, name, caps_name)
Value:
horiz_align = caps_name##_IS_LEFT_SIDE ? align_right : align_left;         \
    side_sign = caps_name##_IS_LEFT_SIDE ? -1.f : 1.f;                         \
    for (unsigned int i = 0; i < segs[SEGMENT_##caps_name]->size(); ++i) {     \
        const name##Segment* seg = To##name((*segs[SEGMENT_##caps_name])[i]);  \
        if (seg->GetRow() >= m_FieldRenderArgs.first_row &&                    \
            seg->GetRow() <= m_FieldRenderArgs.last_row &&                     \
            IS_ON_SCREEN(seg->GetBeat())) {                                    \
            draw_timing_segment_text(str_exp,                                  \
                                     seg->GetBeat(),                           \
                                     side_sign,                                \
                                     caps_name##_OFFSETX,                      \
                                     horiz_align,                              \
                                     caps_name##_COLOR,                        \
                                     text_glow);                               \
        }                                                                      \
    }
Referenced by NoteField::DrawPrimitives().
IS_ON_SCREEN
#define IS_ON_SCREEN (fBeat)
Value:
(m_FieldRenderArgs.first_beat <= (fBeat) &&                                \
     (fBeat) <= m_FieldRenderArgs.last_beat)
Referenced by NoteField::DrawPrimitives().
OPEN_CALLBACK_BLOCK
#define OPEN_CALLBACK_BLOCK (member_name)
Value:
if (!from_lua && !(member_name).IsNil()) {                                 \
        Lua* L = LUA->Get();                                                   \
        (member_name).PushSelf(L);
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), NoteField::SetPressed(), and NoteField::Step().
OPEN_RUN_BLOCK
#define OPEN_RUN_BLOCK (arg_count)
Value:
RString error = "Error running callback: ";                                \
    if (LuaHelpers::RunScriptOnStack(L, error, arg_count, arg_count, true)) {
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), NoteField::SetPressed(), and NoteField::Step().
PUSH_COLUMN
#define PUSH_COLUMN lua_pushnumber(L, col + 1)
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), NoteField::SetPressed(), and NoteField::Step().
SET_CALLBACK_GENERIC
#define SET_CALLBACK_GENERIC (callback_name, member_name)
Value:
static int callback_name(T* p, lua_State* L)                               \
    {                                                                          \
        if (lua_isnoneornil(L, 1)) {                                           \
            p->member_name.SetFromNil();                                       \
        } else if (lua_isfunction(L, 1)) {                                     \
            p->member_name.SetFromStack(L);                                    \
        } else {                                                               \
            luaL_error(L,                                                      \
                       #callback_name "Callback argument must be nil (to "     \
                                      "clear the callback) or a function (to " \
                                      "set the callback).");                   \
        }                                                                      \
        return 0;                                                              \
    }
Function Documentation
FindDisplayedBeats()
void FindDisplayedBeats (const PlayerState * pPlayerState, float & firstBeat, float & lastBeat, int iDrawDistanceAfterTargetsPixels, int iDrawDistanceBeforeTargetsPixels)
References PlayerOptions::ACCEL_BOOMERANG, f, ModsGroup< T >::GetCurrent(), PlayerState::GetDisplayedPosition(), TimingData::GetDisplayedSpeedPercent(), PlayerState::GetDisplayedTiming(), ArrowEffects::GetYOffset(), PlayerOptions::m_fAccels, SongPosition::m_fMusicSecondsVisible, SongPosition::m_fSongBeat, SongPosition::m_fSongBeatVisible, PlayerState::m_PlayerOptions, and min().
Referenced by NoteField::DrawPrimitives().
get_returned_bright()
static void get_returned_bright (Lua * L, int index, bool & bright) static
Referenced by NoteField::DidHoldNote(), and NoteField::DidTapNote().
get_returned_column()
static void get_returned_column (Lua * L, PlayerNumber pn, int index, int & col) static
References GAMESTATE, GameState::GetCurrentStyle(), Style::m_iColsPerPlayer, and LuaHelpers::ReportScriptErrorFmt().
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), NoteField::SetPressed(), and NoteField::Step().
get_returned_score()
template<class T > static void get_returned_score (Lua * L, int index, T & score) static
References L, and T.
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), and NoteField::Step().
GetNumNotesFromBeginning()
static CacheNoteStat GetNumNotesFromBeginning (const PlayerState * pPlayerState, float beat) static
References PlayerState::m_CacheNoteStat, and max().
Referenced by GetNumNotesRange().
GetNumNotesRange()
static int GetNumNotesRange (const PlayerState * pPlayerState, float fLow, float fHigh) static
References GetNumNotesFromBeginning(), CacheNoteStat::notesLower, and CacheNoteStat::notesUpper.
RoutineNoteSkinName()
static RString RoutineNoteSkinName (size_t i) static
References ssprintf().
Variable Documentation
AREA_HIGHLIGHT_COLOR
ThemeMetric<RageColor> AREA_HIGHLIGHT_COLOR("NoteField", "AreaHighlightColor") static
Referenced by NoteField::DrawAreaHighlight().
BAR_16TH_ALPHA
ThemeMetric<float> BAR_16TH_ALPHA("NoteField", "Bar16thAlpha") static
Referenced by NoteField::DrawBeatBar().
BAR_4TH_ALPHA
ThemeMetric<float> BAR_4TH_ALPHA("NoteField", "Bar4thAlpha") static
Referenced by NoteField::DrawBeatBar().
BAR_8TH_ALPHA
ThemeMetric<float> BAR_8TH_ALPHA("NoteField", "Bar8thAlpha") static
Referenced by NoteField::DrawBeatBar().
BAR_MEASURE_ALPHA
ThemeMetric<float> BAR_MEASURE_ALPHA("NoteField", "BarMeasureAlpha") static
Referenced by NoteField::DrawBeatBar().
BPM_COLOR
ThemeMetric<RageColor> BPM_COLOR("NoteField", "BPMColor") static
BPM_IS_LEFT_SIDE
ThemeMetric<bool> BPM_IS_LEFT_SIDE("NoteField", "BPMIsLeftSide") static
BPM_OFFSETX
ThemeMetric<float> BPM_OFFSETX("NoteField", "BPMOffsetX") static
COMBO_COLOR
ThemeMetric<RageColor> COMBO_COLOR("NoteField", "ComboColor") static
COMBO_IS_LEFT_SIDE
ThemeMetric<bool> COMBO_IS_LEFT_SIDE("NoteField", "ComboIsLeftSide") static
COMBO_OFFSETX
ThemeMetric<float> COMBO_OFFSETX("NoteField", "ComboOffsetX") static
DELAY_COLOR
ThemeMetric<RageColor> DELAY_COLOR("NoteField", "DelayColor") static
DELAY_IS_LEFT_SIDE
ThemeMetric<bool> DELAY_IS_LEFT_SIDE("NoteField", "DelayIsLeftSide") static
DELAY_OFFSETX
ThemeMetric<float> DELAY_OFFSETX("NoteField", "DelayOffsetX") static
FADE_BEFORE_TARGETS_PERCENT
ThemeMetric<float> FADE_BEFORE_TARGETS_PERCENT("NoteField", "FadeBeforeTargetsPercent") static
Referenced by NoteField::DrawBoard(), and NoteField::DrawPrimitives().
FADE_FAIL_TIME
ThemeMetric<float> FADE_FAIL_TIME("NoteField", "FadeFailTime") static
Referenced by NoteField::Update().
FAKE_COLOR
ThemeMetric<RageColor> FAKE_COLOR("NoteField", "FakeColor") static
FAKE_IS_LEFT_SIDE
ThemeMetric<bool> FAKE_IS_LEFT_SIDE("NoteField", "FakeIsLeftSide") static
FAKE_OFFSETX
ThemeMetric<float> FAKE_OFFSETX("NoteField", "FakeOffsetX") static
ihatethisprogram
Preference<float> ihatethisprogram("NotefieldXRatio", 1.f) static
Referenced by NoteField::Init().
LABEL_COLOR
ThemeMetric<RageColor> LABEL_COLOR("NoteField", "LabelColor") static
LABEL_IS_LEFT_SIDE
ThemeMetric<bool> LABEL_IS_LEFT_SIDE("NoteField", "LabelIsLeftSide") static
LABEL_OFFSETX
ThemeMetric<float> LABEL_OFFSETX("NoteField", "LabelOffsetX") static
ROUTINE_NOTESKIN
ThemeMetric1D<RString> ROUTINE_NOTESKIN("NoteField", RoutineNoteSkinName, NUM_PLAYERS) static
Referenced by NoteField::CacheAllUsedNoteSkins().
SCROLL_COLOR
ThemeMetric<RageColor> SCROLL_COLOR("NoteField", "ScrollColor") static
SCROLL_IS_LEFT_SIDE
ThemeMetric<bool> SCROLL_IS_LEFT_SIDE("NoteField", "ScrollIsLeftSide") static
SCROLL_OFFSETX
ThemeMetric<float> SCROLL_OFFSETX("NoteField", "ScrollOffsetX") static
SHOW_BEAT_BARS
ThemeMetric<bool> SHOW_BEAT_BARS("NoteField", "ShowBeatBars") static
Referenced by NoteField::DrawPrimitives().
SHOW_BOARD
ThemeMetric<bool> SHOW_BOARD("NoteField", "ShowBoard") static
Referenced by NoteField::DrawBoardPrimitive().
SPEED_COLOR
ThemeMetric<RageColor> SPEED_COLOR("NoteField", "SpeedColor") static
SPEED_IS_LEFT_SIDE
ThemeMetric<bool> SPEED_IS_LEFT_SIDE("NoteField", "SpeedIsLeftSide") static
SPEED_OFFSETX
ThemeMetric<float> SPEED_OFFSETX("NoteField", "SpeedOffsetX") static
STOP_COLOR
ThemeMetric<RageColor> STOP_COLOR("NoteField", "StopColor") static
STOP_IS_LEFT_SIDE
ThemeMetric<bool> STOP_IS_LEFT_SIDE("NoteField", "StopIsLeftSide") static
STOP_OFFSETX
ThemeMetric<float> STOP_OFFSETX("NoteField", "StopOffsetX") static
TICKCOUNT_COLOR
ThemeMetric<RageColor> TICKCOUNT_COLOR("NoteField", "TickcountColor") static
TICKCOUNT_IS_LEFT_SIDE
ThemeMetric<bool> TICKCOUNT_IS_LEFT_SIDE("NoteField", "TickcountIsLeftSide") static
TICKCOUNT_OFFSETX
ThemeMetric<float> TICKCOUNT_OFFSETX("NoteField", "TickcountOffsetX") static
TIME_SIG_COLOR
ThemeMetric<RageColor> TIME_SIG_COLOR("NoteField", "TimeSignatureColor") static
TIME_SIG_IS_LEFT_SIDE
ThemeMetric<bool> TIME_SIG_IS_LEFT_SIDE("NoteField", "TimeSignatureIsLeftSide") static
TIME_SIG_OFFSETX
ThemeMetric<float> TIME_SIG_OFFSETX("NoteField", "TimeSignatureOffsetX") static
WARP_COLOR
ThemeMetric<RageColor> WARP_COLOR("NoteField", "WarpColor") static
WARP_IS_LEFT_SIDE
ThemeMetric<bool> WARP_IS_LEFT_SIDE("NoteField", "WarpIsLeftSide") static
WARP_OFFSETX
ThemeMetric<float> WARP_OFFSETX("NoteField", "WarpOffsetX") static