Etterna: InputHandler_Win32_MIDI.cpp File Reference
InputHandler_Win32_MIDI.cpp File Reference
#include "InputHandler_Win32_MIDI.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "global.h"
#include <mmsystem.h>
#include <windows.h>
Functions
REGISTER_INPUT_HANDLER_CLASS2 (MIDI, Win32_MIDI)
static void CALLBACK midiCallback (HMIDIIN g_device, UINT status, DWORD instancePtr, DWORD data, DWORD timestamp)
static RString GetMidiError (MMRESULT result)
Variables
static HMIDIIN g_device
Function Documentation
GetMidiError()
static RString GetMidiError (MMRESULT result) static
Referenced by InputHandler_Win32_MIDI::InputHandler_Win32_MIDI(), and InputHandler_Win32_MIDI::~InputHandler_Win32_MIDI().
midiCallback()
static void CALLBACK midiCallback (HMIDIIN g_device, UINT status, DWORD instancePtr, DWORD data, DWORD timestamp) static
References DEVICE_MIDI, enum_add2(), MIDI_FIRST, and DeviceInput::ts.
Referenced by InputHandler_Win32_MIDI::InputHandler_Win32_MIDI().
REGISTER_INPUT_HANDLER_CLASS2()
REGISTER_INPUT_HANDLER_CLASS2 (MIDI , Win32_MIDI)
Variable Documentation
g_device
HMIDIIN g_device static
Referenced by InputHandler_Win32_MIDI::InputHandler_Win32_MIDI(), and InputHandler_Win32_MIDI::~InputHandler_Win32_MIDI().