Etterna: NotesLoaderJson.cpp File Reference
NotesLoaderJson.cpp File Reference
#include "global.h"
#include "NotesLoaderJson.h"
#include "BackgroundUtil.h"
#include "GameManager.h"
#include "JsonUtil.h"
#include "NoteData.h"
#include "RageUtil.h"
#include "Song.h"
#include "Steps.h"
#include "TimingData.h"
#include "json/value.h"
Functions
static void Deserialize (TimingSegment *seg, const Json::Value &root)
static void Deserialize (BPMSegment &seg, const Json::Value &root)
static void Deserialize (StopSegment &seg, const Json::Value &root)
static void Deserialize (TimingData &td, const Json::Value &root)
static void Deserialize (LyricSegment &o, const Json::Value &root)
static void Deserialize (BackgroundDef &o, const Json::Value &root)
static void Deserialize (BackgroundChange &o, const Json::Value &root)
static void Deserialize (TapNote &o, const Json::Value &root)
static void Deserialize (StepsType st, NoteData &nd, const Json::Value &root)
static void Deserialize (RadarValues &o, const Json::Value &root)
static void Deserialize (Steps &o, const Json::Value &root)
static void Deserialize (Song &out, const Json::Value &root)
Function Documentation
Deserialize() [1/12]
static void Deserialize (TimingSegment * seg, const Json::Value & root) static
References TimingSegment::GetType(), SEGMENT_BPM, and SEGMENT_STOP.
Referenced by Deserialize(), JsonUtil::DeserializeArrayObjects(), JsonUtil::DeserializeStringToObjectMap(), and NotesLoaderJson::LoadFromJsonFile().
Deserialize() [2/12]
static void Deserialize (BPMSegment & seg, const Json::Value & root) static
References Deserialize().
Deserialize() [3/12]
static void Deserialize (StopSegment & seg, const Json::Value & root) static
References Deserialize().
Deserialize() [4/12]
static void Deserialize (TimingData & td, const Json::Value & root) static
References TimingData::AddSegment(), Deserialize(), and JsonUtil::DeserializeVectorPointers().
Deserialize() [5/12]
static void Deserialize (LyricSegment & o, const Json::Value & root) static
References RageColor::FromString(), LyricSegment::m_Color, LyricSegment::m_fStartTime, and LyricSegment::m_sLyric.
Deserialize() [6/12]
static void Deserialize (BackgroundDef & o, const Json::Value & root) static
References BackgroundDef::m_sColor1, BackgroundDef::m_sEffect, BackgroundDef::m_sFile1, and BackgroundDef::m_sFile2.
Deserialize() [7/12]
static void Deserialize (BackgroundChange & o, const Json::Value & root) static
References Deserialize(), BackgroundChange::m_def, BackgroundChange::m_fRate, BackgroundChange::m_fStartBeat, and BackgroundChange::m_sTransition.
Deserialize() [8/12]
static void Deserialize (TapNote & o, const Json::Value & root) static
References TapNote::iDuration, TapNote::iKeysoundIndex, TapNote::pn, TapNote::subType, and TapNote::type.
Deserialize() [9/12]
static void Deserialize (StepsType st, NoteData & nd, const Json::Value & root) static
References BeatToNoteRow(), Deserialize(), NoteData::GetNumTracks(), NoteData::SetNumTracks(), and NoteData::SetTapNote().
Deserialize() [10/12]
static void Deserialize (RadarValues & o, const Json::Value & root) static
References FOREACH_ENUM, and RadarCategoryToString().
Deserialize() [11/12]
static void Deserialize (Steps & o, const Json::Value & root) static
References Steps::Decompress(), Deserialize(), GAMEMAN, Steps::m_StepsType, Steps::SetCachedRadarValues(), Steps::SetDescription(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetNoteData(), StringToDifficulty(), and GameManager::StringToStepsType().
Deserialize() [12/12]
static void Deserialize (Song & out, const Json::Value & root) static
References Song::AddSteps(), Deserialize(), JsonUtil::DeserializeArrayValuesIntoVector(), JsonUtil::DeserializeVectorObjects(), DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, StdString::CStdStr< CT >::EqualsNoCase(), FOREACH, FOREACH_BackgroundLayer, Song::GetBackgroundChanges(), Song::GetForegroundChanges(), Song::m_bHasBanner, Song::m_bHasMusic, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicLengthSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_LyricSegments, Song::m_sArtist, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_SelectionDisplay, Song::m_sGenre, Song::m_sGroupName, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sSongFileName, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Song::m_vsKeysoundFile, Song::SetSongDir(), Song::SHOW_ALWAYS, and Song::SHOW_NEVER.