Etterna: ArchHooks Class Reference
ArchHooks Class Reference abstract
#include <ArchHooks.h>
Public Member Functions
ArchHooks ()
virtual ~ArchHooks ()=default
virtual void Init ()
virtual RString GetArchName () const
virtual void DumpDebugInfo ()
virtual void RestartProgram ()
Re-exec the game.
virtual bool CheckForMultipleInstances (int, char *[])
virtual void SetTime (tm)
virtual void BoostPriority ()
virtual void UnBoostPriority ()
virtual void SetupConcurrentRenderingThread ()
Setup the rendering threads for concurrency.
void SetHasFocus (bool bAppHasFocus)
bool AppHasFocus () const
bool AppFocusChanged ()
virtual bool GoToURL (const RString &sUrl)
virtual float GetDisplayAspectRatio ()=0
virtual RString GetClipboard ()
Fetch the contents of the system clipboard.
virtual int GetWindowWidth ()
Fetch the window width.
virtual int GetWindowHeight ()
Fetch the window height.
void PushSelf (lua_State *L)
void RegisterWithLua ()
Static Public Member Functions
static ArchHooks * Create ()
static RString GetPreferredLanguage ()
static bool UserQuit ()
Determine if the user wants to quit (eg. ^C, or clicked a "close window" button).
static void SetUserQuit ()
static bool GetAndClearToggleWindowed ()
static void SetToggleWindowed ()
static int64_t GetMicrosecondsSinceStart (bool bAccurate)
static void MountInitialFilesystems (const RString &sDirOfExecutable)
static void MountUserFilesystems (const RString &sDirOfExecutable)
Static Private Member Functions
static int64_t FixupTimeIfLooped (int64_t usecs)
static int64_t FixupTimeIfBackwards (int64_t usecs)
Private Attributes
bool m_bHasFocus
bool m_bFocusChanged
Static Private Attributes
static bool g_bQuitting = false
static bool g_bToggleWindowed = false
Constructor & Destructor Documentation
ArchHooks()
ArchHooks::ArchHooks ()
~ArchHooks()
virtual ArchHooks::~ArchHooks () virtual default
Member Function Documentation
AppFocusChanged()
bool ArchHooks::AppFocusChanged ()
References g_Mutex, LockMut, and m_bFocusChanged.
Referenced by CheckFocus().
AppHasFocus()
bool ArchHooks::AppHasFocus () const inline
References m_bHasFocus.
Referenced by CheckFocus(), RageDisplay::FrameLimitBeforeVsync(), HandleInputEvents(), and LowLevelWindow_MacOSX::TryVideoMode().
BoostPriority()
virtual void ArchHooks::BoostPriority () inline virtual
Reimplemented in ArchHooks_Win32.
Referenced by CheckFocus(), and GameLoop::RunGameLoop().
CheckForMultipleInstances()
virtual bool ArchHooks::CheckForMultipleInstances (int , char * []) inline virtual
Reimplemented in ArchHooks_Win32.
Referenced by sm_main().
Create()
ArchHooks * ArchHooks::Create () static
References ARCH_HOOKS.
Referenced by sm_main().
DumpDebugInfo()
virtual void ArchHooks::DumpDebugInfo () inline virtual
Reimplemented in ArchHooks_Win32, ArchHooks_MacOSX, and ArchHooks_Unix.
Referenced by sm_main().
FixupTimeIfBackwards()
int64_t ArchHooks::FixupTimeIfBackwards (int64_t usecs) static private
FixupTimeIfLooped()
int64_t ArchHooks::FixupTimeIfLooped (int64_t usecs) static private
GetAndClearToggleWindowed()
bool ArchHooks::GetAndClearToggleWindowed () static
References g_bToggleWindowed, g_Mutex, and LockMut.
Referenced by HandleInputEvents().
GetArchName()
virtual RString ArchHooks::GetArchName () const inline virtual
Reimplemented in ArchHooks_Win32, ArchHooks_MacOSX, and ArchHooks_Unix.
GetClipboard()
RString ArchHooks::GetClipboard () virtual
Fetch the contents of the system clipboard.
Reimplemented in ArchHooks_Win32, and ArchHooks_Unix.
References LOG, and RageLog::Warn().
Referenced by ScreenTextEntry::Input(), and ScreenNetSelectBase::PasteClipboard().
GetDisplayAspectRatio()
virtual float ArchHooks::GetDisplayAspectRatio () pure virtual
Implemented in ArchHooks_Win32, ArchHooks_Unix, and ArchHooks_MacOSX.
GetMicrosecondsSinceStart()
int64_t ArchHooks::GetMicrosecondsSinceStart (bool bAccurate) static
References unlikely.
Referenced by GetTime().
GetPreferredLanguage()
RString ArchHooks::GetPreferredLanguage () static
References LOG, and RageLog::Warn().
Referenced by ScreenSelectLanguage::GetDefaultChoice(), and ThemeManager::GetDefaultLanguage().
GetWindowHeight()
int ArchHooks::GetWindowHeight () virtual
Fetch the window height.
Reimplemented in ArchHooks_Win32.
References PrefsManager::m_iDisplayHeight, and PREFSMAN.
Referenced by LunaInputFilter::GetMouseY().
GetWindowWidth()
int ArchHooks::GetWindowWidth () virtual
Fetch the window width.
Reimplemented in ArchHooks_Win32.
References PrefsManager::m_fDisplayAspectRatio, PrefsManager::m_iDisplayHeight, and PREFSMAN.
Referenced by LunaInputFilter::GetMouseX().
GoToURL()
bool ArchHooks::GoToURL (const RString & sUrl) virtual
Reimplemented in ArchHooks_Win32, ArchHooks_Unix, and ArchHooks_MacOSX.
Referenced by GameCommand::ApplySelf(), and sm_main().
Init()
virtual void ArchHooks::Init () inline virtual
Reimplemented in ArchHooks_MacOSX, and ArchHooks_Unix.
Referenced by sm_main().
MountInitialFilesystems()
void ArchHooks::MountInitialFilesystems (const RString & sDirOfExecutable) static
References FILEMAN, and RageFileManager::Mount().
Referenced by RageFileManager::MountInitialFilesystems().
MountUserFilesystems()
void ArchHooks::MountUserFilesystems (const RString & sDirOfExecutable) static
References FILEMAN, RageFileManager::Mount(), PathForFolderType(), PRODUCT_ID, ssprintf(), and SpecialFiles::USER_PACKAGES_DIR.
Referenced by RageFileManager::MountUserFilesystems().
PushSelf()
void ArchHooks::PushSelf (lua_State * L)
Referenced by RegisterWithLua().
RegisterWithLua()
void ArchHooks::RegisterWithLua ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
Referenced by sm_main().
RestartProgram()
virtual void ArchHooks::RestartProgram () inline virtual
Re-exec the game.
If this is implemented, it doesn't return.
Reimplemented in ArchHooks_Win32.
Referenced by HandleException().
SetHasFocus()
void ArchHooks::SetHasFocus (bool bAppHasFocus)
References g_Mutex, LockMut, LOG, m_bFocusChanged, m_bHasFocus, and RageLog::Trace().
Referenced by LowLevelWindow_MacOSX::LowLevelWindow_MacOSX(), SMWindowDelegate::windowDidBecomeKey:, and SMWindowDelegate::windowDidResignKey:.
SetTime()
virtual void ArchHooks::SetTime (tm) inline virtual
Reimplemented in ArchHooks_Win32, and ArchHooks_Unix.
Referenced by ScreenSetTime::MenuStart().
SetToggleWindowed()
void ArchHooks::SetToggleWindowed () static
References g_bToggleWindowed, g_Mutex, and LockMut.
Referenced by HandleGlobalInputs().
SetupConcurrentRenderingThread()
virtual void ArchHooks::SetupConcurrentRenderingThread () inline virtual
Setup the rendering threads for concurrency.
The priority of the concurrent rendering thread may need to be boosted on some schedulers.
Reimplemented in ArchHooks_Win32.
Referenced by ConcurrentRenderer::RenderThread().
SetUserQuit()
static void ArchHooks::SetUserQuit () inline static
References g_bQuitting.
Referenced by DoCleanShutdown(), HandleGlobalInputs(), ScreenExit::Init(), and SMWindowDelegate::windowWillClose:.
UnBoostPriority()
virtual void ArchHooks::UnBoostPriority () inline virtual
Reimplemented in ArchHooks_Win32.
Referenced by CheckFocus(), and GameLoop::RunGameLoop().
UserQuit()
static bool ArchHooks::UserQuit () inline static
Determine if the user wants to quit (eg. ^C, or clicked a "close window" button).
Returns
true if the user wants to quit, false otherwise.
References g_bQuitting.
Referenced by GameLoop::RunGameLoop(), and sm_main().
Member Data Documentation
g_bQuitting
bool ArchHooks::g_bQuitting = false static private
Referenced by SetUserQuit(), and UserQuit().
g_bToggleWindowed
bool ArchHooks::g_bToggleWindowed = false static private
Referenced by GetAndClearToggleWindowed(), and SetToggleWindowed().
m_bFocusChanged
bool ArchHooks::m_bFocusChanged private
Referenced by AppFocusChanged(), and SetHasFocus().
m_bHasFocus
bool ArchHooks::m_bHasFocus private
Referenced by AppHasFocus(), and SetHasFocus().
The documentation for this class was generated from the following files:
ArchHooks.h
ArchHooks.cpp
ArchHooks_MacOSX.mm
ArchHooks_Unix.cpp
ArchHooks_Win32Static.cpp
ArchHooksUtil.cpp