Etterna: RageFileManager Class Reference
RageFileManager Class Reference
File utilities and high-level manager for RageFile objects.
#include <RageFileManager.h>
Classes
struct DriverLocation
Public Types
enum FileType { TYPE_FILE, TYPE_DIR, TYPE_NONE }
Public Member Functions
RageFileManager (const RString &argv0)
~RageFileManager ()
void MountInitialFilesystems ()
void MountUserFilesystems ()
void GetDirListing (const RString &sPath, vector< RString > &AddTo, bool bOnlyDirs, bool bReturnPathToo)
void GetDirListingWithMultipleExtensions (const RString &sPath, vector< RString > const &ExtensionList, vector< RString > &AddTo, bool bOnlyDirs=false, bool bReturnPathToo=false)
bool Move (const RString &sOldPath, const RString &sNewPath)
bool Remove (const RString &sPath)
bool DeleteRecursive (const RString &sPath)
void CreateDir (const RString &sDir)
FileType GetFileType (const RString &sPath)
bool IsAFile (const RString &sPath)
bool IsADirectory (const RString &sPath)
bool DoesFileExist (const RString &sPath)
int GetFileSizeInBytes (const RString &sPath)
int GetFileHash (const RString &sPath)
RString ResolvePath (const RString &path)
Get the absolte path from the VPS.
bool Mount (const RString &sType, const RString &sRealPath, const RString &sMountPoint, bool bAddToEnd=true)
void Mount (RageFileDriver *pDriver, const RString &sMountPoint, bool bAddToEnd=true)
void Unmount (const RString &sType, const RString &sRoot, const RString &sMountPoint)
void Remount (const RString &sMountpoint, const RString &sPath)
bool IsMounted (const RString &MountPoint)
void GetLoadedDrivers (vector< DriverLocation > &asMounts)
void FlushDirCache (const RString &sPath=RString())
RageFileBasic * Open (const RString &sPath, int iMode, int &iError)
void CacheFile (const RageFileBasic *fb, const RString &sPath)
RageFileDriver * GetFileDriver (RString sMountpoint)
void ReleaseFileDriver (RageFileDriver *pDriver)
void PushSelf (lua_State *L)
Private Member Functions
RageFileBasic * OpenForReading (const RString &sPath, int iMode, int &iError)
RageFileBasic * OpenForWriting (const RString &sPath, int iMode, int &iError)
Detailed Description
File utilities and high-level manager for RageFile objects.
Member Enumeration Documentation
FileType
enum RageFileManager::FileType
Enumerator
TYPE_FILE
TYPE_DIR
TYPE_NONE
Constructor & Destructor Documentation
RageFileManager()
RageFileManager::RageFileManager (const RString & argv0)
References ChangeToDirOfExecutable(), CHECKPOINT_M, g_Mountpoints, g_pDrivers, LuaManager::Get(), L, LUA, LoadedDriver::m_pDriver, Mount(), PushSelf(), and LuaManager::Release().
~RageFileManager()
RageFileManager::~RageFileManager ()
References g_Mutex, g_pDrivers, LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
CacheFile()
void RageFileManager::CacheFile (const RageFileBasic * fb, const RString & sPath)
References ASSERT_M, g_mFileDriverMap, NormalizePath(), and ssprintf().
Referenced by RageFile::Close().
CreateDir()
void RageFileManager::CreateDir (const RString & sDir)
References RageFile::Close(), f, RageFile::Open(), Remove(), and RageFile::WRITE.
Referenced by Profile::SaveAllToDir(), SongCacheIndex::SongCacheIndex(), and HighScoreImpl::WriteReplayData().
DeleteRecursive()
bool RageFileManager::DeleteRecursive (const RString & sPath)
References DeleteRecursive().
Referenced by ScreenNetSelectMusic::OnConfirmSongDeletion(), and ScreenSelectMusic::OnConfirmSongDeletion().
DoesFileExist()
bool RageFileManager::DoesFileExist (const RString & sPath)
References GetFileType(), and TYPE_NONE.
Referenced by DoesFileExist(), LunaRageFileManager::DoesFileExist(), Song::HasAutosaveFile(), Profile::LoadTypeFromDir(), Profile::MergeScoresFromOtherProfile(), and Song::RemoveAutosave().
FlushDirCache()
void RageFileManager::FlushDirCache (const RString & sPath = RString())
References g_pDrivers, LockMut, and NormalizePath().
Referenced by ProfileManager::DeleteLocalProfile(), SongManager::DifferentialReload(), NoteSkinManager::GetPath(), FileTransfer::HTTPUpdate(), Profile::MakeUniqueFileNameNoExtension(), ThemeManager::ReloadMetrics(), ActorUtil::ResolvePath(), Song::Save(), and SyncFiles().
GetDirListing()
void RageFileManager::GetDirListing (const RString & sPath, vector< RString > & AddTo, bool bOnlyDirs, bool bReturnPathToo)
References RageFileDriver::GetDirListing(), LoadedDriver::GetPath(), ieq(), ilt(), LoadedDriver::m_pDriver, LoadedDriver::m_sMountPoint, NormalizePath(), ReferenceAllDrivers(), StripMacResourceForks(), and UnreferenceAllDrivers().
Referenced by convert_xmls_in_dir(), EmptyTempDLFileDir(), Song::GetCacheFile(), GetDirListing(), LunaRageFileManager::GetDirListing(), GetDirListingWithMultipleExtensions(), actor_template_t::load_node(), and Song::TidyUpData().
GetDirListingWithMultipleExtensions()
void RageFileManager::GetDirListingWithMultipleExtensions (const RString & sPath, vector< RString > const & ExtensionList, vector< RString > & AddTo, bool bOnlyDirs = false, bool bReturnPathToo = false)
References GetDirListing(), and GetExtension().
Referenced by SongManager::AddGroup(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), Song::LoadFromSongDir(), and BMSSong::PrecacheBackgrounds().
GetFileDriver()
RageFileDriver * RageFileManager::GetFileDriver (RString sMountpoint)
References FixSlashesInPlace(), g_pDrivers, RageMutex::Lock(), StdString::CStdStr< CT >::Right(), and RageMutex::Unlock().
Referenced by Remount(), and ThreadedFileWorker::ThreadedFileWorker().
GetFileHash()
int RageFileManager::GetFileHash (const RString & sPath)
References NormalizePath(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by GetHashForFile(), and LunaRageFileManager::GetHashForFile().
GetFileSizeInBytes()
int RageFileManager::GetFileSizeInBytes (const RString & sPath)
References NormalizePath(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by LunaRageFileManager::GetFileSizeBytes(), GetFileSizeInBytes(), Profile::LoadEditableDataFromDir(), SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), and CryptManager::VerifyFileWithFile().
GetFileType()
RageFileManager::FileType RageFileManager::GetFileType (const RString & sPath)
References NormalizePath(), ReferenceAllDrivers(), TYPE_NONE, and UnreferenceAllDrivers().
Referenced by DoesFileExist(), IsADirectory(), IsAFile(), and ActorUtil::ResolvePath().
GetLoadedDrivers()
void RageFileManager::GetLoadedDrivers (vector< DriverLocation > & asMounts)
References g_pDrivers, LockMut, RageFileManager::DriverLocation::MountPoint, RageFileManager::DriverLocation::Root, and RageFileManager::DriverLocation::Type.
IsADirectory()
bool RageFileManager::IsADirectory (const RString & sPath)
References GetFileType(), and TYPE_DIR.
Referenced by SongManager::InitSongsFromDisk(), IsADirectory(), actor_template_t::load_node(), Profile::LoadAllFromDir(), NoteSkinManager::LoadNoteSkinDataRecursive(), SongCacheIndex::SongCacheIndex(), and HighScoreImpl::WriteReplayData().
IsAFile()
bool RageFileManager::IsAFile (const RString & sPath)
References GetFileType(), and TYPE_FILE.
Referenced by EmptyTempDLFileDir(), IsAFile(), NoteSkinManager::LoadNoteSkinDataRecursive(), XMLProfile::MoveBackupToDir(), DBProfile::MoveBackupToDir(), Profile::MoveBackupToDir(), SongCacheIndex::OpenDB(), XMLProfile::SaveEttXmlToDir(), and XMLProfile::SaveStatsXmlToDir().
IsMounted()
bool RageFileManager::IsMounted (const RString & MountPoint)
References g_pDrivers, and LockMut.
Mount() [1/2]
bool RageFileManager::Mount (const RString & sType, const RString & sRealPath, const RString & sMountPoint, bool bAddToEnd = true)
References AddFilesystemDriver(), AdjustMountpoint(), ASSERT, CHECKPOINT_M, FixSlashesInPlace(), LOG, LoadedDriver::m_pDriver, MakeFileDriver(), ssprintf(), Unmount(), and RageLog::Warn().
Referenced by DownloadManager::InstallSmzip(), InstallSmzipOsArg(), ArchHooks::MountInitialFilesystems(), MountTreeOfZips(), ArchHooks::MountUserFilesystems(), RageFileManager(), and sm_main().
Mount() [2/2]
void RageFileManager::Mount (RageFileDriver * pDriver, const RString & sMountPoint, bool bAddToEnd = true)
References AddFilesystemDriver(), AdjustMountpoint(), and LoadedDriver::m_pDriver.
MountInitialFilesystems()
void RageFileManager::MountInitialFilesystems ()
References HOOKS, and ArchHooks::MountInitialFilesystems().
Referenced by sm_main().
MountUserFilesystems()
void RageFileManager::MountUserFilesystems ()
References HOOKS, and ArchHooks::MountUserFilesystems().
Referenced by sm_main().
Move()
bool RageFileManager::Move (const RString & sOldPath, const RString & sNewPath)
References NormalizePath(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by Profile::LoadAllFromDir(), Profile::MergeScoresFromOtherProfile(), XMLProfile::MoveBackupToDir(), DBProfile::MoveBackupToDir(), and Profile::MoveBackupToDir().
Open()
RageFileBasic * RageFileManager::Open (const RString & sPath, int iMode, int & iError)
References NormalizePath(), OpenForReading(), OpenForWriting(), PathUsesSlowFlush(), RageFile::SLOW_FLUSH, and RageFile::WRITE.
Referenced by XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), XMLProfile::LoadStatsXmlForConversion(), and RageFile::Open().
OpenForReading()
RageFileBasic * RageFileManager::OpenForReading (const RString & sPath, int iMode, int & iError) private
References LoadedDriver::GetPath(), LoadedDriver::m_pDriver, RageFileDriver::Open(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by Open().
OpenForWriting()
RageFileBasic * RageFileManager::OpenForWriting (const RString & sPath, int iMode, int & iError) private
References ASSERT, RageFileDriver::ERROR_WRITING_NOT_SUPPORTED, g_mFileDriverMap, LoadedDriver::GetPath(), RageFileDriver::GetPathValue(), LoadedDriver::m_pDriver, RageFileDriver::Open(), ReferenceAllDrivers(), SortBySecond(), and UnreferenceAllDrivers().
Referenced by Open().
PushSelf()
void RageFileManager::PushSelf (lua_State * L)
Referenced by RageFileManager().
ReleaseFileDriver()
void RageFileManager::ReleaseFileDriver (RageFileDriver * pDriver)
References ASSERT, RageEvent::Broadcast(), g_pDrivers, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by Remount(), and ThreadedFileWorker::~ThreadedFileWorker().
Remount()
void RageFileManager::Remount (const RString & sMountpoint, const RString & sPath)
References RageFileDriver::FlushDirCache(), GetFileDriver(), LOG, ReleaseFileDriver(), RageFileDriver::Remount(), and RageLog::Warn().
Remove()
bool RageFileManager::Remove (const RString & sPath)
References NormalizePath(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by FileTransfer::Cancel(), ScreenPackages::CancelDownload(), CreateDir(), SongCacheIndex::DeleteDB(), DeleteEmptyDirectories(), DeleteRecursive(), EmptyDir(), EmptyTempDLFileDir(), BackgroundLoader::FinishedWithCachedFile(), CryptManager::GenerateRSAKeyToFile(), BackgroundLoader::LoadThread(), Song::ReloadFromSongDir(), Song::RemoveAutosave(), Song::Save(), XMLProfile::SaveEttXmlToDir(), XMLProfile::SaveStatsXmlToDir(), SyncFiles(), WriteFile(), BackgroundLoader::~BackgroundLoader(), and Download::~Download().
ResolvePath()
RString RageFileManager::ResolvePath (const RString & path)
Get the absolte path from the VPS.
Parameters
path the VPS path.
Returns
the absolute path.
References LoadedDriver::GetPath(), LoadedDriver::m_sMountPoint, LoadedDriver::m_sRoot, LoadedDriver::m_sType, NormalizePath(), ReferenceAllDrivers(), and UnreferenceAllDrivers().
Referenced by SongCacheIndex::DeleteDB(), DBProfile::LoadDBFromDir(), SongCacheIndex::OpenDB(), and DBProfile::SaveDBToDir().
Unmount()
void RageFileManager::Unmount (const RString & sType, const RString & sRoot, const RString & sMountPoint)
References FixSlashesInPlace(), g_pDrivers, RageFileDriverMountpoints::LoadFromDrivers(), RageMutex::Lock(), StdString::CStdStr< CT >::Right(), RageMutex::Unlock(), and RageEvent::Wait().
Referenced by DownloadManager::InstallSmzip(), InstallSmzipOsArg(), and Mount().
The documentation for this class was generated from the following files:
RageFileManager.h
RageFileManager.cpp