Etterna: LyricsLoader Class Reference
LyricsLoader Class Reference
Loads lyrics from an LRC file.
#include <LyricsLoader.h>
Public Member Functions
bool LoadFromLRCFile (const RString &sPath, Song &out)
Load the lyrics into the Song.
Detailed Description
Loads lyrics from an LRC file.
Member Function Documentation
LoadFromLRCFile()
bool LyricsLoader::LoadFromLRCFile (const RString & sPath, Song & out)
Load the lyrics into the Song.
Parameters
sPath the path to the Lyrics.
out the Song to receive the Lyrics.
References Song::AddLyricSegment(), ASSERT, Regex::Compare(), CompareLyricSegments(), f, RageFile::GetError(), RageFile::GetLine(), RageFile::GetPath(), HHMMSSToSeconds(), LOG, LYRICS_DEFAULT_COLOR, LyricSegment::m_Color, LyricSegment::m_fStartTime, Song::m_LyricSegments, LyricSegment::m_sLyric, RageFile::Open(), StdString::CStdStr< CT >::Replace(), LuaHelpers::ReportScriptErrorFmt(), StripCrnl(), RageLog::Trace(), and Rage::utf8_remove_bom().
Referenced by ScreenGameplay::LoadNextSong().
The documentation for this class was generated from the following files:
LyricsLoader.h
LyricsLoader.cpp