Etterna: ezsockets.cpp File Reference
ezsockets.cpp File Reference
#include "global.h"
#include "Preference.h"
#include "ezsockets.h"
#include <iostream>
#include <sys/socket.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>
Macros
#define SOCKET_ERROR (-1)
#define SOCKET_NONE 0
#define INVALID_SOCKET (-1)
Functions
bool SetSocketBlocking (int fd, bool blocking)
timeval timevalFromMs (unsigned int ms)
bool checkCanRead (int sock, timeval &timeout)
bool checkCanWrite (int sock, timeval &timeout)
istream & operator>> (istream &is, EzSockets &obj)
ostream & operator<< (ostream &os, EzSockets &obj)
Variables
static Preference< unsigned int > timeoutMiliseconds ("ConnectionMilisecondsTimeout", 7000)
Macro Definition Documentation
INVALID_SOCKET
#define INVALID_SOCKET (-1)
Referenced by EzSockets::EzSockets().
SOCKET_ERROR
#define SOCKET_ERROR (-1)
Referenced by EzSockets::accept(), and EzSockets::listen().
SOCKET_NONE
#define SOCKET_NONE 0
Referenced by EzSockets::check(), and EzSockets::create().
Function Documentation
checkCanRead()
bool checkCanRead (int sock, timeval & timeout) inline
Referenced by EzSockets::CanRead().
checkCanWrite()
bool checkCanWrite (int sock, timeval & timeout) inline
Referenced by EzSockets::CanWrite().
operator<<()
ostream& operator<< (ostream & os, EzSockets & obj)
References EzSockets::ReadStr().
operator>>()
istream& operator>> (istream & is, EzSockets & obj)
References EzSockets::SendStr().
SetSocketBlocking()
bool SetSocketBlocking (int fd, bool blocking)
Returns true on success, or false if there was an error
Referenced by EzSockets::CanConnect(), and EzSockets::connect().
timevalFromMs()
timeval timevalFromMs (unsigned int ms) inline
Referenced by EzSockets::CanRead(), EzSockets::CanWrite(), EzSockets::create(), and EzSockets::EzSockets().
Variable Documentation
timeoutMiliseconds
Preference<unsigned int> timeoutMiliseconds("ConnectionMilisecondsTimeout", 7000) static
Referenced by EzSockets::create(), and EzSockets::EzSockets().