Etterna: LunaThemeManager Class Reference
LunaThemeManager Class Reference
Allow Lua to have access to the ThemeManager.
Public Member Functions
GENERAL_GET_PATH (GetPathF)
GENERAL_GET_PATH (GetPathG)
GENERAL_GET_PATH (GetPathB)
GENERAL_GET_PATH (GetPathS)
GENERAL_GET_PATH (GetPathO)
DEFINE_METHOD (GetCurrentThemeDirectory, GetCurThemeDir())
DEFINE_METHOD (GetCurLanguage, GetCurLanguage())
DEFINE_METHOD (DoesThemeExist, DoesThemeExist(SArg(1)))
DEFINE_METHOD (IsThemeSelectable, IsThemeSelectable(SArg(1)))
DEFINE_METHOD (DoesLanguageExist, DoesLanguageExist(SArg(1)))
DEFINE_METHOD (GetCurThemeName, GetCurThemeName())
LunaThemeManager ()
Public Member Functions inherited from Luna< ThemeManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int ReloadMetrics (T *p, lua_State *L)
static int HasMetric (T *p, lua_State *L)
static int GetMetric (T *p, lua_State *L)
static int HasString (T *p, lua_State *L)
static int GetString (T *p, lua_State *L)
static int GetPathInfoB (T *p, lua_State *L)
static int RunLuaScripts (T *p, lua_State *L)
static int GetSelectableThemeNames (T *p, lua_State *L)
static int GetNumSelectableThemes (T *p, lua_State *L)
static int GetThemeDisplayName (T *p, lua_State *L)
static int GetThemeAuthor (T *p, lua_State *L)
static void PushMetricNamesInGroup (IniFile const &ini, lua_State *L)
static int GetMetricNamesInGroup (T *p, lua_State *L)
static int GetStringNamesInGroup (T *p, lua_State *L)
static int SetTheme (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ThemeManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ThemeManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ThemeManager >
using T = ThemeManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ThemeManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ThemeManager.
Constructor & Destructor Documentation
LunaThemeManager()
LunaThemeManager::LunaThemeManager () inline
References ADD_METHOD, GetMetric(), GetMetricNamesInGroup(), GetNumSelectableThemes(), GetPathInfoB(), GetSelectableThemeNames(), GetString(), GetStringNamesInGroup(), GetThemeAuthor(), GetThemeDisplayName(), HasMetric(), HasString(), ReloadMetrics(), RunLuaScripts(), and SetTheme().
Member Function Documentation
DEFINE_METHOD() [1/6]
LunaThemeManager::DEFINE_METHOD (GetCurrentThemeDirectory , GetCurThemeDir())
DEFINE_METHOD() [2/6]
LunaThemeManager::DEFINE_METHOD (GetCurLanguage , GetCurLanguage())
DEFINE_METHOD() [3/6]
LunaThemeManager::DEFINE_METHOD (DoesThemeExist , DoesThemeExist(SArg(1)))
DEFINE_METHOD() [4/6]
LunaThemeManager::DEFINE_METHOD (IsThemeSelectable , IsThemeSelectable(SArg(1)))
DEFINE_METHOD() [5/6]
LunaThemeManager::DEFINE_METHOD (DoesLanguageExist , DoesLanguageExist(SArg(1)))
DEFINE_METHOD() [6/6]
LunaThemeManager::DEFINE_METHOD (GetCurThemeName , GetCurThemeName())
GENERAL_GET_PATH() [1/5]
LunaThemeManager::GENERAL_GET_PATH (GetPathF)
GENERAL_GET_PATH() [2/5]
LunaThemeManager::GENERAL_GET_PATH (GetPathG)
GENERAL_GET_PATH() [3/5]
LunaThemeManager::GENERAL_GET_PATH (GetPathB)
GENERAL_GET_PATH() [4/5]
LunaThemeManager::GENERAL_GET_PATH (GetPathS)
GENERAL_GET_PATH() [5/5]
LunaThemeManager::GENERAL_GET_PATH (GetPathO)
GetMetric()
static int LunaThemeManager::GetMetric (T * p, lua_State * L) inline static
References ThemeManager::PushMetric(), and SArg.
Referenced by LunaThemeManager().
GetMetricNamesInGroup()
static int LunaThemeManager::GetMetricNamesInGroup (T * p, lua_State * L) inline static
References LoadedThemeData::iniMetrics, and PushMetricNamesInGroup().
Referenced by LunaThemeManager().
GetNumSelectableThemes()
static int LunaThemeManager::GetNumSelectableThemes (T * p, lua_State * L) inline static
References ThemeManager::GetNumSelectableThemes().
Referenced by LunaThemeManager().
GetPathInfoB()
static int LunaThemeManager::GetPathInfoB (T * p, lua_State * L) inline static
References EC_BGANIMATIONS, ThemeManager::GetPathInfo(), SArg, ThemeManager::PathInfo::sMatchingElement, ThemeManager::PathInfo::sMatchingMetricsGroup, and ThemeManager::PathInfo::sResolvedPath.
Referenced by LunaThemeManager().
GetSelectableThemeNames()
static int LunaThemeManager::GetSelectableThemeNames (T * p, lua_State * L) inline static
References ThemeManager::GetSelectableThemeNames(), and L.
Referenced by LunaThemeManager().
GetString()
static int LunaThemeManager::GetString (T * p, lua_State * L) inline static
References ThemeManager::GetString(), and SArg.
Referenced by LunaThemeManager().
GetStringNamesInGroup()
static int LunaThemeManager::GetStringNamesInGroup (T * p, lua_State * L) inline static
References LoadedThemeData::iniStrings, and PushMetricNamesInGroup().
Referenced by LunaThemeManager().
GetThemeAuthor()
static int LunaThemeManager::GetThemeAuthor (T * p, lua_State * L) inline static
References ThemeManager::GetCurThemeName(), and ThemeManager::GetThemeAuthor().
Referenced by LunaThemeManager().
GetThemeDisplayName()
static int LunaThemeManager::GetThemeDisplayName (T * p, lua_State * L) inline static
References ThemeManager::GetCurThemeName(), and ThemeManager::GetThemeDisplayName().
Referenced by LunaThemeManager().
HasMetric()
static int LunaThemeManager::HasMetric (T * p, lua_State * L) inline static
References ThemeManager::HasMetric(), and SArg.
Referenced by LunaThemeManager().
HasString()
static int LunaThemeManager::HasString (T * p, lua_State * L) inline static
References ThemeManager::HasString(), and SArg.
Referenced by LunaThemeManager().
PushMetricNamesInGroup()
static void LunaThemeManager::PushMetricNamesInGroup (IniFile const & ini, lua_State * L) inline static
References XNode::GetChild(), XNode::m_attrs, LuaHelpers::Push(), and SArg.
Referenced by GetMetricNamesInGroup(), and GetStringNamesInGroup().
ReloadMetrics()
static int LunaThemeManager::ReloadMetrics (T * p, lua_State * L) inline static
References ThemeManager::ReloadMetrics().
Referenced by LunaThemeManager().
RunLuaScripts()
static int LunaThemeManager::RunLuaScripts (T * p, lua_State * L) inline static
References ThemeManager::RunLuaScripts(), and SArg.
Referenced by LunaThemeManager().
SetTheme()
static int LunaThemeManager::SetTheme (T * p, lua_State * L) inline static
References GameLoop::ChangeTheme(), ThemeManager::IsThemeSelectable(), and SArg.
Referenced by LunaThemeManager().
The documentation for this class was generated from the following file:
ThemeManager.cpp