Etterna: LoadingWindow_Win32 Class Reference
LoadingWindow_Win32 Class Reference
#include <LoadingWindow_Win32.h>
Public Member Functions
LoadingWindow_Win32 ()
~LoadingWindow_Win32 ()
void Paint ()
void InternalPaint ()
void SetText (const RString &sText)
void SetTextInternal ()
void SetIcon (const RageSurface *pIcon)
void SetSplash (const RageSurface *pSplash)
void SetProgress (const int progress)
void SetTotalWork (const int totalWork)
void SetIndeterminate (bool indeterminate)
Public Member Functions inherited from LoadingWindow
virtual RString Init ()
virtual ~LoadingWindow ()=default
Static Private Member Functions
static BOOL CALLBACK WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Private Attributes
AppInstance handle
HWND hwnd
HICON m_hIcon
HFONT f
LOGFONT lf
string progress
RString lastText
HGDIOBJ bitMapBG
HDC hdcBG
Additional Inherited Members
Static Public Member Functions inherited from LoadingWindow
static LoadingWindow * Create ()
Protected Attributes inherited from LoadingWindow
int m_progress
int m_totalWork
bool m_indeterminate
Constructor & Destructor Documentation
LoadingWindow_Win32()
LoadingWindow_Win32::LoadingWindow_Win32 ()
References _tcscpy, ASSERT, bitMapBG, f, FONT_COLOR, FONT_FILE, FONT_HEIGHT, FONT_NAME, handle, hdcBG, hwnd, lf, m_hIcon, Paint(), RageFileManagerUtil::sDirOfExecutable, SetText(), and WndProc().
~LoadingWindow_Win32()
LoadingWindow_Win32::~LoadingWindow_Win32 ()
References f, hwnd, and m_hIcon.
Member Function Documentation
InternalPaint()
void LoadingWindow_Win32::InternalPaint ()
References bitMapBG, f, FONT_COLOR, FONT_HEIGHT, FONT_X, FONT_Y, and hwnd.
Referenced by Paint(), and WndProc().
Paint()
void LoadingWindow_Win32::Paint ()
References hwnd, and InternalPaint().
Referenced by LoadingWindow_Win32(), and SetTextInternal().
SetIcon()
void LoadingWindow_Win32::SetIcon (const RageSurface * pIcon) virtual
Reimplemented from LoadingWindow.
References hwnd, and m_hIcon.
SetIndeterminate()
void LoadingWindow_Win32::SetIndeterminate (bool indeterminate) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_indeterminate, and SetTextInternal().
SetProgress()
void LoadingWindow_Win32::SetProgress (const int progress) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_progress, progress, and SetTextInternal().
SetSplash()
void LoadingWindow_Win32::SetSplash (const RageSurface * pSplash) virtual
Reimplemented from LoadingWindow.
References g_hBitmap, hwnd, and LoadWin32Surface().
SetText()
void LoadingWindow_Win32::SetText (const RString & sText) virtual
Implements LoadingWindow.
References lastText, and SetTextInternal().
Referenced by LoadingWindow_Win32().
SetTextInternal()
void LoadingWindow_Win32::SetTextInternal ()
References lastText, LoadingWindow::m_indeterminate, LoadingWindow::m_progress, LoadingWindow::m_totalWork, Paint(), progress, and split().
Referenced by SetIndeterminate(), SetProgress(), SetText(), and SetTotalWork().
SetTotalWork()
void LoadingWindow_Win32::SetTotalWork (const int totalWork) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_totalWork, and SetTextInternal().
WndProc()
BOOL CALLBACK LoadingWindow_Win32::WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) static private
References g_hBitmap, GetDirListing(), InternalPaint(), LoadWin32Surface(), and PRODUCT_ID.
Referenced by LoadingWindow_Win32().
Member Data Documentation
bitMapBG
HGDIOBJ LoadingWindow_Win32::bitMapBG private
Referenced by InternalPaint(), and LoadingWindow_Win32().
f
HFONT LoadingWindow_Win32::f private
Referenced by InternalPaint(), LoadingWindow_Win32(), res_t::operator float(), and ~LoadingWindow_Win32().
handle
AppInstance LoadingWindow_Win32::handle private
Referenced by LoadingWindow_Win32().
hdcBG
HDC LoadingWindow_Win32::hdcBG private
Referenced by LoadingWindow_Win32().
hwnd
HWND LoadingWindow_Win32::hwnd private
Referenced by InternalPaint(), LoadingWindow_Win32(), Paint(), SetIcon(), SetSplash(), and ~LoadingWindow_Win32().
lastText
RString LoadingWindow_Win32::lastText private
Referenced by SetText(), and SetTextInternal().
lf
LOGFONT LoadingWindow_Win32::lf private
Referenced by LoadingWindow_Win32().
m_hIcon
HICON LoadingWindow_Win32::m_hIcon private
Referenced by LoadingWindow_Win32(), SetIcon(), and ~LoadingWindow_Win32().
progress
string LoadingWindow_Win32::progress private
Referenced by SetProgress(), and SetTextInternal().
The documentation for this class was generated from the following files:
LoadingWindow_Win32.h
LoadingWindow_Win32.cpp