Etterna: LunaGameManager Class Reference
LunaGameManager Class Reference
Allow Lua to have access to the GameManager.
Public Member Functions
LunaGameManager ()
Public Member Functions inherited from Luna< GameManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int StepsTypeToLocalizedString (T *p, lua_State *L)
static int GetFirstStepsTypeForGame (T *p, lua_State *L)
static int IsGameEnabled (T *p, lua_State *L)
static int GetStylesForGame (T *p, lua_State *L)
static int GetEnabledGames (T *p, lua_State *L)
static int SetGame (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< GameManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< GameManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< GameManager >
using T = GameManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< GameManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the GameManager.
Constructor & Destructor Documentation
LunaGameManager()
LunaGameManager::LunaGameManager () inline
References ADD_METHOD, GetEnabledGames(), GetFirstStepsTypeForGame(), GetStylesForGame(), IsGameEnabled(), SetGame(), and StepsTypeToLocalizedString().
Member Function Documentation
GetEnabledGames()
static int LunaGameManager::GetEnabledGames (T * p, lua_State * L) inline static
References GameManager::GetEnabledGames().
Referenced by LunaGameManager().
GetFirstStepsTypeForGame()
static int LunaGameManager::GetFirstStepsTypeForGame (T * p, lua_State * L) inline static
References ASSERT, Luna< Type >::check(), GameManager::GetStepsTypesForGame(), and LuaHelpers::Push().
Referenced by LunaGameManager().
GetStylesForGame()
static int LunaGameManager::GetStylesForGame (T * p, lua_State * L) inline static
References Game::m_apStyles, Style::PushSelf(), SArg, and GameManager::StringToGame().
Referenced by LunaGameManager().
IsGameEnabled()
static int LunaGameManager::IsGameEnabled (T * p, lua_State * L) inline static
References GameManager::IsGameEnabled(), SArg, and GameManager::StringToGame().
Referenced by LunaGameManager().
SetGame()
static int LunaGameManager::SetGame (T * p, lua_State * L) inline static
References GameLoop::ChangeGame(), ThemeManager::IsThemeSelectable(), SArg, GameManager::StringToGame(), and THEME.
Referenced by LunaGameManager().
StepsTypeToLocalizedString()
static int LunaGameManager::StepsTypeToLocalizedString (T * p, lua_State * L) inline static
References StepsTypeInfo::GetLocalizedString(), and GameManager::GetStepsTypeInfo().
Referenced by LunaGameManager().
The documentation for this class was generated from the following file:
GameManager.cpp