Etterna: CachedObjectPointer< T > Class Template Reference
CachedObjectPointer< T > Class Template Reference
#include <RageUtil_CachedObject.h>
Public Types
using Object = CachedObject< T >
Public Member Functions
CachedObjectPointer ()
CachedObjectPointer (const CachedObjectPointer &cpy)
~CachedObjectPointer ()
bool Get (T **pRet) const
void Set (T *p)
void Unset ()
Private Attributes
T * m_pCache
bool m_bCacheIsSet
Friends
class CachedObject< T >
Member Typedef Documentation
Object
template<typename T> using CachedObjectPointer< T >::Object = CachedObject<T>
Constructor & Destructor Documentation
CachedObjectPointer() [1/2]
template<typename T> CachedObjectPointer< T >::CachedObjectPointer () inline
CachedObjectPointer() [2/2]
template<typename T> CachedObjectPointer< T >::CachedObjectPointer (const CachedObjectPointer< T > & cpy) inline
~CachedObjectPointer()
template<typename T> CachedObjectPointer< T >::~CachedObjectPointer () inline
Member Function Documentation
Get()
template<typename T> bool CachedObjectPointer< T >::Get (T ** pRet) const inline
Referenced by SongID::ToSong().
Set()
template<typename T> void CachedObjectPointer< T >::Set (T * p) inline
Referenced by SongID::ToSong(), and StepsID::ToSteps().
Unset()
template<typename T> void CachedObjectPointer< T >::Unset () inline
Referenced by SongID::FromSong(), StepsID::FromSteps(), StepsID::LoadFromNode(), SongID::LoadFromNode(), SongID::LoadFromString(), and SongID::SongID().
Friends And Related Function Documentation
CachedObject< T >
template<typename T> friend class CachedObject< T > friend
Member Data Documentation
m_bCacheIsSet
template<typename T> bool CachedObjectPointer< T >::m_bCacheIsSet private
Referenced by CachedObjectPointer< Steps >::Get(), CachedObjectPointer< Steps >::Set(), and CachedObjectPointer< Steps >::Unset().
m_pCache
template<typename T> T* CachedObjectPointer< T >::m_pCache private
Referenced by CachedObjectPointer< Steps >::Get(), CachedObjectPointer< Steps >::Set(), and CachedObjectPointer< Steps >::Unset().
The documentation for this class was generated from the following file:
RageUtil_CachedObject.h