Etterna: RageSoundDriver_WaveOut.cpp File Reference
RageSoundDriver_WaveOut.cpp File Reference
#include "RageSoundDriver_WaveOut.h"
#include "global.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageSound.h"
#include "RageSoundManager.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "archutils/Win32/ErrorStrings.h"
Functions
REGISTER_SOUND_DRIVER_CLASS (WaveOut)
static RString wo_ssprintf (MMRESULT err, const char *szFmt,...)
Variables
const int channels = 2
const int bytes_per_frame = channels * 2
const int buffersize_frames = 1024 * 8
const int buffersize = buffersize_frames * bytes_per_frame
const int num_chunks = 8
const int chunksize_frames = buffersize_frames / num_chunks
const int chunksize = buffersize / num_chunks
Function Documentation
REGISTER_SOUND_DRIVER_CLASS()
REGISTER_SOUND_DRIVER_CLASS (WaveOut)
wo_ssprintf()
static RString wo_ssprintf (MMRESULT err, const char * szFmt, ...) static
References ssprintf(), and vssprintf().
Referenced by RageSoundDriver_WaveOut::GetData(), RageSoundDriver_WaveOut::GetPosition(), and RageSoundDriver_WaveOut::Init().
Variable Documentation
buffersize
const int buffersize = buffersize_frames * bytes_per_frame
buffersize_frames
const int buffersize_frames = 1024 * 8
Referenced by RageSoundDriver_WaveOut::GetPlayLatency(), and RageSoundDriver_WaveOut::Init().
bytes_per_frame
const int bytes_per_frame = channels * 2
channels
const int channels = 2
Referenced by RageSoundDriver_WaveOut::Init().
chunksize
const int chunksize = buffersize / num_chunks
Referenced by RageSoundDriver_OSS::GetData(), and RageSoundDriver_WaveOut::Init().
chunksize_frames
const int chunksize_frames = buffersize_frames / num_chunks
Referenced by RageSoundDriver_WaveOut::GetData(), and RageSoundDriver_WaveOut::GetPlayLatency().
num_chunks
const int num_chunks = 8
Referenced by RageSoundDriver_WaveOut::GetData(), RageSoundDriver_WaveOut::Init(), and RageSoundDriver_WaveOut::~RageSoundDriver_WaveOut().