Etterna: ssc_parser_helper_t Struct Reference
ssc_parser_helper_t Struct Reference
Public Member Functions
ssc_parser_helper_t ()
Public Attributes
steps_handler_map_t steps_tag_handlers
song_handler_map_t song_tag_handlers
load_note_data_handler_map_t load_note_data_handlers
Constructor & Destructor Documentation
ssc_parser_helper_t()
ssc_parser_helper_t::ssc_parser_helper_t () inline
References SSC::LNDID_chartname, SSC::LNDID_credit, SSC::LNDID_description, SSC::LNDID_difficulty, SSC::LNDID_meter, SSC::LNDID_notedata, SSC::LNDID_notes, SSC::LNDID_notes2, SSC::LNDID_stepstype, SSC::LNDID_version, SetArtist(), SetArtistTranslit(), SetBackground(), SetBanner(), SetBGChanges(), SetCDImage(), SetCDTitle(), SetChartKey(), SetChartName(), SetChartStyle(), SetCredit(), SetDescription(), SetDifficulty(), SetDiscImage(), SetDisplayBPM(), SetFGChanges(), SetFirstSecond(), SetGenre(), SetHasBanner(), SetHasMusic(), SetInstrumentTrack(), SetJacket(), SetKeysounds(), SetLastSecond(), SetLastSecondHint(), SetLyricsPath(), SetMainTitleTranslit(), SetMeter(), SetMSDValues(), SetMusic(), SetMusicLength(), SetOffset(), SetOrigin(), SetPreview(), SetPreviewVid(), SetRadarValues(), SetSampleLength(), SetSampleStart(), SetSelectable(), SetSongBPMs(), SetSongCombos(), SetSongDelays(), SetSongFakes(), SetSongFilename(), SetSongLabels(), SetSongScrolls(), SetSongSpeeds(), SetSongStops(), SetSongTickCounts(), SetSongTimeSignatures(), SetSongWarps(), SetStepsBPMs(), SetStepsCombos(), SetStepsDelays(), SetStepsDisplayBPM(), SetStepsFakes(), SetStepsLabels(), SetStepsMusic(), SetStepsOffset(), SetStepsScrolls(), SetStepsSpeeds(), SetStepsStops(), SetStepsTickCounts(), SetStepsTimeSignatures(), SetStepsType(), SetStepsVersion(), SetStepsWarps(), SetSubtitle(), SetSubtitleTranslit(), SetTitle(), and SetVersion().
Member Data Documentation
load_note_data_handlers
load_note_data_handler_map_t ssc_parser_helper_t::load_note_data_handlers
Referenced by SSCLoader::LoadNoteDataFromSimfile().
song_tag_handlers
song_handler_map_t ssc_parser_helper_t::song_tag_handlers
Referenced by SSCLoader::LoadFromSimfile().
steps_tag_handlers
steps_handler_map_t ssc_parser_helper_t::steps_tag_handlers
Referenced by SSCLoader::LoadEditFromMsd(), and SSCLoader::LoadFromSimfile().
The documentation for this struct was generated from the following file:
NotesLoaderSSC.cpp