Etterna: MinaCalc.h File Reference
MinaCalc.h File Reference
#include "NoteDataStructures.h"
#include <vector>
Classes
class Hand
class Calc
Macros
#define MINACALC_API
Typedefs
typedef vector< float > SDiffs
typedef vector< SDiffs > MinaSD
typedef vector< vector< float > > Finger
typedef vector< Finger > ProcessedFingers
typedef vector< float > JackSeq
Functions
MINACALC_API vector< float > MinaSDCalc (const vector< NoteInfo > &NoteInfo, int numTracks, float musicrate, float goal, float timingscale, bool negbpms)
MINACALC_API MinaSD MinaSDCalc (const vector< NoteInfo > &NoteInfo, int numTracks, float goal, float timingscale, bool negbpms)
MINACALC_API int GetCalcVersion ()
Macro Definition Documentation
MINACALC_API
#define MINACALC_API
Typedef Documentation
Finger
typedef vector<vector<float> > Finger
JackSeq
typedef vector<float> JackSeq
MinaSD
typedef vector<SDiffs> MinaSD
ProcessedFingers
typedef vector<Finger> ProcessedFingers
SDiffs
typedef vector<float> SDiffs
Function Documentation
GetCalcVersion()
MINACALC_API int GetCalcVersion ()
Referenced by ScoreManager::AggregateSSRs(), FillInHighScore(), ScoreManager::RecalculateSSRs(), and ScoresForChart::SetTopScores().
MinaSDCalc() [1/2]
MINACALC_API vector<float> MinaSDCalc (const vector< NoteInfo > & NoteInfo, int numTracks, float musicrate, float goal, float timingscale, bool negbpms)
Referenced by Steps::CalcEtternaMetadata(), PlayerStageStats::CalcSSR(), and ScoreManager::RecalculateSSRs().
MinaSDCalc() [2/2]
MINACALC_API MinaSD MinaSDCalc (const vector< NoteInfo > & NoteInfo, int numTracks, float goal, float timingscale, bool negbpms)