Etterna: AutoKeysounds Class Reference
AutoKeysounds Class Reference
Handle playback of auto keysound notes.
#include <AutoKeysounds.h>
Public Member Functions
void Load (PlayerNumber pn, const NoteData &ndAutoKeysoundsOnly)
void Update (float fDelta)
void FinishLoading ()
Finish loading the main sounds, and setup the auto keysounds if any.
RageSound * GetSound ()
RageSoundReader * GetSharedSound ()
RageSoundReader * GetPlayerSound (PlayerNumber pn)
Protected Member Functions
void LoadAutoplaySoundsInto (RageSoundReader_Chain *pChain)
Static Protected Member Functions
static void LoadTracks (const Song *pSong, RageSoundReader *&pGlobal, RageSoundReader *&pPlayer1, RageSoundReader *&pPlayer2)
Protected Attributes
NoteData m_ndAutoKeysoundsOnly [NUM_PLAYERS]
vector< RageSound > m_vKeysounds
RageSound m_sSound
RageSoundReader * m_pChain
RageSoundReader * m_pPlayerSounds [NUM_PLAYERS]
RageSoundReader * m_pSharedSound
Detailed Description
Handle playback of auto keysound notes.
Member Function Documentation
FinishLoading()
void AutoKeysounds::FinishLoading ()
Finish loading the main sounds, and setup the auto keysounds if any.
References ASSERT, ASSERT_M, f, FOREACH, GAMESTATE, RageSoundManager::GetDriverSampleRate(), GameState::GetMasterPlayerNumber(), GameState::GetNumPlayersEnabled(), LoadAutoplaySoundsInto(), RageSound::LoadSoundReader(), LoadTracks(), m_pChain, GameState::m_pCurSong, m_pPlayerSounds, m_pSharedSound, Song::m_sMainTitle, m_sSound, PLAYER_1, PLAYER_2, RageSoundReader_Chain::SetPreferredSampleRate(), SOUNDMAN, ssprintf(), swap(), and RageSound::Unload().
Referenced by ScreenGameplay::LoadNextSong().
GetPlayerSound()
RageSoundReader* AutoKeysounds::GetPlayerSound (PlayerNumber pn) inline
References m_pPlayerSounds, and PLAYER_INVALID.
Referenced by ScreenGameplay::HandleMessage(), and ScreenGameplay::LoadNextSong().
GetSharedSound()
RageSoundReader* AutoKeysounds::GetSharedSound () inline
References m_pSharedSound.
Referenced by ScreenGameplay::HandleMessage(), and ScreenGameplay::LoadNextSong().
GetSound()
RageSound* AutoKeysounds::GetSound () inline
References m_sSound.
Referenced by ScreenGameplay::LoadNextSong().
Load()
void AutoKeysounds::Load (PlayerNumber pn, const NoteData & ndAutoKeysoundsOnly)
References m_ndAutoKeysoundsOnly.
Referenced by ScreenGameplay::SetupSong().
LoadAutoplaySoundsInto()
void AutoKeysounds::LoadAutoplaySoundsInto (RageSoundReader_Chain * pChain) protected
References RageSoundReader_Chain::AddSound(), ASSERT, FOREACH_EnabledPlayer, GAMESTATE, GameState::GetMasterPlayerNumber(), GameState::GetNumPlayersEnabled(), NoteData::GetNumTracks(), RageSoundManager::GetPlayLatency(), Song::GetSongDir(), NoteData::GetTapNote(), TapNote::iKeysoundIndex, RageSoundReader_Chain::LoadSound(), m_ndAutoKeysoundsOnly, GameState::m_pCurSong, GameState::m_pCurSteps, Song::m_vsKeysoundFile, min(), NoteRowToBeat(), NUM_PLAYERS, PLAYER_1, SOUNDMAN, TAP_EMPTY, and TapNoteType_AutoKeysound.
Referenced by FinishLoading().
LoadTracks()
void AutoKeysounds::LoadTracks (const Song * pSong, RageSoundReader *& pGlobal, RageSoundReader *& pPlayer1, RageSoundReader *& pPlayer2) static protected
References FOREACH, FOREACH_ENUM, GAMESTATE, RageSoundManager::GetDriverSampleRate(), Song::GetInstrumentTrackPath(), GameState::GetMasterPlayerNumber(), Song::HasInstrumentTrack(), InstrumentTrack_Guitar, GameState::m_pCurSteps, RageSoundReader_FileReader::OpenFile(), and SOUNDMAN.
Referenced by FinishLoading().
Update()
void AutoKeysounds::Update (float fDelta)
Referenced by ScreenGameplay::Update().
Member Data Documentation
m_ndAutoKeysoundsOnly
NoteData AutoKeysounds::m_ndAutoKeysoundsOnly[NUM_PLAYERS] protected
Referenced by Load(), and LoadAutoplaySoundsInto().
m_pChain
RageSoundReader* AutoKeysounds::m_pChain protected
Referenced by FinishLoading().
m_pPlayerSounds
RageSoundReader* AutoKeysounds::m_pPlayerSounds[NUM_PLAYERS] protected
Referenced by FinishLoading(), and GetPlayerSound().
m_pSharedSound
RageSoundReader* AutoKeysounds::m_pSharedSound protected
Referenced by FinishLoading(), and GetSharedSound().
m_sSound
RageSound AutoKeysounds::m_sSound protected
Referenced by FinishLoading(), and GetSound().
m_vKeysounds
vector<RageSound> AutoKeysounds::m_vKeysounds protected
The documentation for this class was generated from the following files:
AutoKeysounds.h
AutoKeysounds.cpp