Etterna: RageFileObjGzip Class Reference
RageFileObjGzip Class Reference
#include <RageFileDriverDeflate.h>
Public Member Functions
RageFileObjGzip (RageFileBasic *pFile)
int Start ()
int Finish ()
Public Member Functions inherited from RageFileObjDeflate
RageFileObjDeflate (RageFileBasic *pOutput)
~RageFileObjDeflate () override
int GetFileSize () const override
void DeleteFileWhenFinished ()
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
int GetFD () override
RString GetDisplayPath () const override
RageFileBasic * Copy () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Private Attributes
int m_iDataStartOffset
Additional Inherited Members
Protected Member Functions inherited from RageFileObjDeflate
int ReadInternal (void *, size_t) override
int WriteInternal (const void *pBuffer, size_t iBytes) override
int FlushInternal () override
Protected Member Functions inherited from RageFileObj
virtual int SeekInternal (int)
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObjDeflate
RageFileBasic * m_pFile
z_stream * m_pDeflate
bool m_bFileOwned
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileObjGzip()
RageFileObjGzip::RageFileObjGzip (RageFileBasic * pFile)
References m_iDataStartOffset.
Member Function Documentation
Finish()
int RageFileObjGzip::Finish ()
References ASSERT, RageFileBasic::Flush(), RageFileObj::Flush(), RageFileObj::GetCRC32(), RageFileBasic::GetError(), m_iDataStartOffset, RageFileObjDeflate::m_pFile, RageFileObj::SetError(), Swap32LE(), RageFileObj::Tell(), and RageFileBasic::Write().
Referenced by GzipString(), XMLProfile::SaveEttXmlToDir(), and XMLProfile::SaveStatsXmlToDir().
Start()
int RageFileObjGzip::Start ()
References ASSERT, RageFileObj::EnableCRC32(), m_iDataStartOffset, RageFileObjDeflate::m_pFile, RageFileObj::Tell(), and RageFileBasic::Write().
Referenced by GzipString(), XMLProfile::SaveEttXmlToDir(), and XMLProfile::SaveStatsXmlToDir().
Member Data Documentation
m_iDataStartOffset
int RageFileObjGzip::m_iDataStartOffset private
Referenced by Finish(), RageFileObjGzip(), and Start().
The documentation for this class was generated from the following files:
RageFileDriverDeflate.h
RageFileDriverDeflate.cpp