Etterna: Command.h File Reference
Command.h File Reference
#include "global.h"
Classes
class Command
struct Command::Arg
class Commands
Functions
void ParseCommands (const RString &sCmds, Commands &vCmdsOut, bool bLegacy)
Commands ParseCommands (const RString &sCmds)
Function Documentation
ParseCommands() [1/2]
void ParseCommands (const RString & sCmds, Commands & vCmdsOut, bool bLegacy)
References Command::Load(), split(), SplitWithQuotes(), and Commands::v.
Referenced by GameState::ApplyGameCommand(), ScreenOptionsManageProfiles::BeginScreen(), MusicWheel::BuildWheelItemDatas(), ScreenOptionsMaster::Init(), ScreenSelect::Init(), OptionsList::Load(), OptionRowHandlerList::LoadInternal(), LuaHelpers::ParseCommandList(), and ParseCommands().
ParseCommands() [2/2]
Commands ParseCommands (const RString & sCmds)
References ParseCommands().