Etterna: LoadingWindow_Win32.cpp File Reference
LoadingWindow_Win32.cpp File Reference
#include "RageUtil.h"
#include "global.h"
#include "CommCtrl.h"
#include "Dwmapi.h"
#include "LoadingWindow_Win32.h"
#include "LocalizedString.h"
#include "ProductInfo.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageSurface_Load.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "archutils/win32/ErrorStrings.h"
#include "archutils/win32/WindowIcon.h"
#include "archutils/win32/WindowsResources.h"
#include <Commdlg.h>
#include <tchar.h>
#include <wchar.h>
#include <windows.h>
#include "RageSurfaceUtils_Zoom.h"
Functions
static HBITMAP LoadWin32Surface (const RageSurface *pSplash, HWND hWnd)
static HBITMAP LoadWin32Surface (RString sFile, HWND hWnd)
Variables
static HBITMAP g_hBitmap = NULL
RString text [3]
const float FONT_HEIGHT = 12
const string FONT_FILE = "Data/Roboto-Light.ttf"
const string FONT_NAME = "Roboto Light"
const auto FONT_COLOR = RGB(240, 240, 240)
const int FONT_Y = 98
const int FONT_X = 20
LoadingWindow_Win32 * w
Function Documentation
LoadWin32Surface() [1/2]
static HBITMAP LoadWin32Surface (const RageSurface * pSplash, HWND hWnd) static
References ASSERT_M, RageSurfaceUtils::Blit(), RageSurfaceFormat::BytesPerPixel, CreateSurface(), RageSurface::fmt, RageSurface::h, RageSurface::pitch, RageSurface::pixels, RageSurface::w, and RageSurfaceUtils::Zoom().
Referenced by LoadWin32Surface(), LoadingWindow_Win32::SetSplash(), and LoadingWindow_Win32::WndProc().
LoadWin32Surface() [2/2]
static HBITMAP LoadWin32Surface (RString sFile, HWND hWnd) static
References RageSurfaceUtils::LoadFile(), and LoadWin32Surface().
Variable Documentation
FONT_COLOR
const auto FONT_COLOR = RGB(240, 240, 240)
Referenced by LoadingWindow_Win32::InternalPaint(), and LoadingWindow_Win32::LoadingWindow_Win32().
FONT_FILE
const string FONT_FILE = "Data/Roboto-Light.ttf"
Referenced by LoadingWindow_Win32::LoadingWindow_Win32().
FONT_HEIGHT
const float FONT_HEIGHT = 12
Referenced by LoadingWindow_Win32::InternalPaint(), and LoadingWindow_Win32::LoadingWindow_Win32().
FONT_NAME
const string FONT_NAME = "Roboto Light"
Referenced by LoadingWindow_Win32::LoadingWindow_Win32().
FONT_X
const int FONT_X = 20
Referenced by LoadingWindow_Win32::InternalPaint().
FONT_Y
const int FONT_Y = 98
Referenced by LoadingWindow_Win32::InternalPaint().
g_hBitmap
HBITMAP g_hBitmap = NULL static
Referenced by LoadingWindow_Win32::SetSplash(), and LoadingWindow_Win32::WndProc().
text
RString text[3]
Referenced by ScreenOptions::AfterChangeValueOrRow(), OptionRow::GetWidthXY(), ScreenMapControllers::Init(), ScreenTextEntryVisual::Init(), BitmapText::LoadFromNode(), and ScreenNetSelectBase::SetInputText().
w
LoadingWindow_Win32* w
Referenced by BitmapText::BuildChars(), picosha2::detail::hash256_block(), MakeValidFilename(), res_t::operator float(), and res_t::operator-=().