Etterna: RenderTarget_X11 Class Reference
RenderTarget_X11 Class Reference
Public Member Functions
RenderTarget_X11 (LowLevelWindow_X11 *pWind)
~RenderTarget_X11 ()
void Create (const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut)
unsigned GetTexture () const
void StartRenderingTo ()
void FinishRenderingTo ()
virtual bool InvertY () const
Public Member Functions inherited from RenderTarget
virtual ~RenderTarget ()=default
const RenderTargetParam & GetParam () const
virtual ~RenderTarget ()=default
const RenderTargetParam & GetParam () const
Private Attributes
int m_iWidth
int m_iHeight
LowLevelWindow_X11 * m_pWind
GLXPbuffer m_iPbuffer
GLXContext m_pPbufferContext
unsigned int m_iTexHandle
GLXContext m_pOldContext
GLXDrawable m_pOldDrawable
Additional Inherited Members
Protected Attributes inherited from RenderTarget
RenderTargetParam m_Param
Constructor & Destructor Documentation
RenderTarget_X11()
RenderTarget_X11::RenderTarget_X11 (LowLevelWindow_X11 * pWind)
~RenderTarget_X11()
RenderTarget_X11::~RenderTarget_X11 ()
Member Function Documentation
Create()
void RenderTarget_X11::Create (const RenderTargetParam & param, int & iTextureWidthOut, int & iTextureHeightOut) virtual
Implements RenderTarget.
References ASSERT, ASSERT_M, RenderTargetParam::bWithAlpha, RenderTargetParam::bWithDepthBuffer, g_pContext, RageDisplay_Legacy_Helpers::GLToString(), RenderTargetParam::iHeight, RenderTargetParam::iWidth, LOG, power_of_two(), and RageLog::Trace().
FinishRenderingTo()
void RenderTarget_X11::FinishRenderingTo () virtual
Implements RenderTarget.
References ASSERT_M, and RageDisplay_Legacy_Helpers::GLToString().
GetTexture()
unsigned RenderTarget_X11::GetTexture () const inline virtual
Implements RenderTarget.
InvertY()
virtual bool RenderTarget_X11::InvertY () const inline virtual
Reimplemented from RenderTarget.
StartRenderingTo()
void RenderTarget_X11::StartRenderingTo () virtual
Implements RenderTarget.
Member Data Documentation
m_iHeight
int RenderTarget_X11::m_iHeight private
m_iPbuffer
GLXPbuffer RenderTarget_X11::m_iPbuffer private
m_iTexHandle
unsigned int RenderTarget_X11::m_iTexHandle private
m_iWidth
int RenderTarget_X11::m_iWidth private
m_pOldContext
GLXContext RenderTarget_X11::m_pOldContext private
m_pOldDrawable
GLXDrawable RenderTarget_X11::m_pOldDrawable private
m_pPbufferContext
GLXContext RenderTarget_X11::m_pPbufferContext private
m_pWind
LowLevelWindow_X11* RenderTarget_X11::m_pWind private
The documentation for this class was generated from the following file:
LowLevelWindow_X11.cpp