Etterna: CachedObject< T > Class Template Reference
CachedObject< T > Class Template Reference
Cached object pointers with automatic invalidation.
#include <RageUtil_CachedObject.h>
Public Member Functions
CachedObject ()
CachedObject (const CachedObject &cpy)
~CachedObject ()
CachedObject & operator= (const CachedObject &rhs)
Static Public Member Functions
static void ClearCacheAll ()
static void ClearCacheSpecific (const T *pObject)
static void ClearCacheNegative ()
Private Types
using ObjectPointer = CachedObjectPointer< T >
Static Private Member Functions
static void Register (ObjectPointer *p)
static void Unregister (ObjectPointer *p)
Private Attributes
const T * m_pObject
Static Private Attributes
static set< ObjectPointer * > m_spObjectPointers
Friends
class CachedObjectPointer< T >
Detailed Description
template<typename T>
class CachedObject< T >
Cached object pointers with automatic invalidation.
Member Typedef Documentation
ObjectPointer
template<typename T> using CachedObject< T >::ObjectPointer = CachedObjectPointer<T> private
Constructor & Destructor Documentation
CachedObject() [1/2]
template<typename T> CachedObject< T >::CachedObject () inline
CachedObject() [2/2]
template<typename T> CachedObject< T >::CachedObject (const CachedObject< T > & cpy) inline
~CachedObject()
template<typename T> CachedObject< T >::~CachedObject () inline
Member Function Documentation
ClearCacheAll()
template<typename T> static void CachedObject< T >::ClearCacheAll () inline static
ClearCacheNegative()
template<typename T> static void CachedObject< T >::ClearCacheNegative () inline static
Referenced by CachedObject< Steps >::CachedObject().
ClearCacheSpecific()
template<typename T> static void CachedObject< T >::ClearCacheSpecific (const T * pObject) inline static
Referenced by CachedObject< Steps >::~CachedObject().
operator=()
template<typename T> CachedObject& CachedObject< T >::operator= (const CachedObject< T > & rhs) inline
Register()
template<typename T> static void CachedObject< T >::Register (ObjectPointer * p) inline static private
Referenced by CachedObjectPointer< Steps >::CachedObjectPointer().
Unregister()
template<typename T> static void CachedObject< T >::Unregister (ObjectPointer * p) inline static private
Referenced by CachedObjectPointer< Steps >::~CachedObjectPointer().
Friends And Related Function Documentation
CachedObjectPointer< T >
template<typename T> friend class CachedObjectPointer< T > friend
Member Data Documentation
m_pObject
template<typename T> const T* CachedObject< T >::m_pObject private
Referenced by CachedObject< Steps >::~CachedObject().
m_spObjectPointers
template<typename T> set< CachedObjectPointer< T > * > CachedObject< T >::m_spObjectPointers static private
Initial value:
=
  set<CachedObjectPointer<T>*>()
Referenced by CachedObject< Steps >::ClearCacheAll(), CachedObject< Steps >::ClearCacheNegative(), CachedObject< Steps >::ClearCacheSpecific(), CachedObject< Steps >::Register(), and CachedObject< Steps >::Unregister().
The documentation for this class was generated from the following file:
RageUtil_CachedObject.h