Etterna: NotesLoaderJson Namespace Reference
NotesLoaderJson Namespace Reference
Functions
void GetApplicableFiles (const RString &sPath, vector< RString > &out)
bool LoadFromDir (const RString &sPath, Song &out)
bool LoadFromJsonFile (const RString &sPath, Song &out)
Function Documentation
GetApplicableFiles()
void NotesLoaderJson::GetApplicableFiles (const RString & sPath, vector< RString > & out)
References GetDirListing().
LoadFromDir()
bool NotesLoaderJson::LoadFromDir (const RString & sPath, Song & out)
References LoadFromJsonFile().
LoadFromJsonFile()
bool NotesLoaderJson::LoadFromJsonFile (const RString & sPath, Song & out)
References Deserialize(), and JsonUtil::LoadFromFileShowErrors().
Referenced by LoadFromDir().