Etterna: Rage Namespace Reference
Rage Namespace Reference
Classes
struct ci_ascii_char_traits
A trait to allow for case insensitive strings...assuming ASCII.
struct ci_ascii_string_equal
struct ci_ascii_string_less
struct std_string_ci_equal
struct std_string_ci_less
Typedefs
using ci_ascii_string = std::basic_string< char, ci_ascii_char_traits >
Enumerations
enum EmptyEntries : bool { EmptyEntries::include, EmptyEntries::skip }
A flag indicating whether to skip entries during splitting a string.
Functions
std::string head (std::string const &source, int32_t const length)
Get the first x characters of a string. Allow negative warping.
std::string tail (std::string const &source, int32_t const length)
Get the last x characters of a string. Allow negative warping.
bool starts_with (std::string const &source, std::string const &target)
Determine if the source string begins with the specified content.
bool ends_with (std::string const &source, std::string const &target)
Determine if the source string ends with the specified content.
std::string hexify (wchar_t const src, unsigned int dstlen)
Offer a clean way of hexify-ing a wide character. Primarily used for fonts.
void replace (std::string &target, char from, char to)
Offer a clean way of replacing all occurances of a character with a different character.
void replace (std::string &target, std::string const &from, std::string const &to)
Offer a clean way of replacing all occurances of a string with a different string.
std::string make_upper (std::string const &source)
Convert the string into its uppercase variant.
std::string make_lower (std::string const &source)
Convert the string into its lowercase variant.
std::string join (std::string const &delimiter, std::vector< std::string > const &source)
Join all of the strings together into one string.
std::string join (std::string const &delimiter, std::vector< std::string >::const_iterator start, std::vector< std::string >::const_iterator finish)
Join all of the strings together into one string.
std::vector< std::string > split (std::string const &source, std::string const &delimiter)
Split a string into a vector based on the delimiter.
std::vector< std::string > split (std::string const &source, std::string const &delimiter, EmptyEntries shouldSkipEmptyEntries)
Split a string into a vector based on the delimiter.
std::vector< std::wstring > split (std::wstring const &source, std::wstring const &delimiter)
Split a string into a vector based on the delimiter.
std::vector< std::wstring > split (std::wstring const &source, std::wstring const &delimiter, EmptyEntries shouldSkipEmptyEntries)
Split a string into a vector based on the delimiter.
void split_in_place (std::string const &source, std::string const &delimitor, int &start, int &size)
Split "in-place" using indexes.
void split_in_place (std::string const &source, std::string const &delimitor, int &start, int &size, EmptyEntries shouldSkipEmptyEntries)
Split "in-place" using indexes.
void split_in_place (std::wstring const &source, std::wstring const &delimitor, int &start, int &size)
Split "in-place" using indexes.
void split_in_place (std::wstring const &source, std::wstring const &delimitor, int &start, int &size, EmptyEntries shouldSkipEmptyEntries)
Split "in-place" using indexes.
void split_in_place (std::string const &source, std::string const &delimitor, int &start, int &size, int len)
Split "in-place" using indexes.
void split_in_place (std::string const &source, std::string const &delimitor, int &start, int &size, int len, EmptyEntries shouldSkipEmptyEntries)
Split "in-place" using indexes.
void split_in_place (std::wstring const &source, std::wstring const &delimitor, int &start, int &size, int len)
Split "in-place" using indexes.
void split_in_place (std::wstring const &source, std::wstring const &delimitor, int &start, int &size, int len, EmptyEntries shouldSkipEmptyEntries)
Split "in-place" using indexes.
std::string trim_left (std::string const &source)
Trim the front of the string of all whitespace characters.
std::string trim_left (std::string const &source, std::string const &delimiters)
Trim the front of the string of all characters of the caller's choosing.
std::string trim_right (std::string const &source)
Trim the back of the string of all whitespace characters.
std::string trim_right (std::string const &source, std::string const &delimiters)
Trim the back of the string of all characters of the caller's choosing.
std::string trim (std::string const &source)
Trim the front and back of the string of all whitespace characters.
std::string trim (std::string const &source, std::string const &delimiters)
Trim the front and back of the string of all characters of the caller's choosing.
std::string base_name (std::string const &dir)
Retrieve the last named component of a directory/file.
std::string dir_name (std::string const &dir)
Retrieve all except the last named component of a directory/file.
void utf8_sanitize (std::string &s)
Sanitize the UTF-8 string.
int utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
bool is_utf8_continuation_byte (char p)
Determine if the byte is an official continuation byte.
bool utf8_to_wchar_ec (std::string const &s, unsigned &start, wchar_t &ch)
Decode a code point and place within the output variable.
bool utf8_to_wchar (char const *s, size_t iLength, unsigned &start, wchar_t &ch)
Decode a code point and place within the output variable.
void wchar_to_utf8 (wchar_t ch, std::string &out)
Analyze the wide character and turn into a UTF-8 string.
wchar_t utf8_get_char (std::string const &s)
Attempt to get a wide character from the UTF-8 string.
bool utf8_is_valid (const std::string &s)
Determine if the string passed in is a valid UTF-8 string.
void utf8_remove_bom (std::string &s)
Remove the starting Byte Order Mark (BOM) form the string if it exists.
std::wstring make_lower (std::wstring const &s)
Convert a wide string to its lowercase variant.
wchar_t make_lower (wchar_t const &s)
Convert a wide string to its lowercase variant.
std::wstring make_upper (std::wstring const &s)
Convert a wide string to its uppercase variant.
wchar_t make_upper (wchar_t const &s)
Convert a wide string to its uppercase variant.
Variables
unsigned char upperCase [256]
A mapping to allow for quick uppercase conversion.
unsigned char lowerCase [256]
A mapping to allow for quick lowercase conversion.
wchar_t const invalid_char = 0xFFFD
The unicode replacement character, FFFD.
Typedef Documentation
ci_ascii_string
using Rage::ci_ascii_string = typedef std::basic_string<char, ci_ascii_char_traits>
Enumeration Type Documentation
EmptyEntries
enum Rage::EmptyEntries : bool strong
A flag indicating whether to skip entries during splitting a string.
Enumerator
include
skip
Function Documentation
base_name()
std::string Rage::base_name (std::string const & dir)
Retrieve the last named component of a directory/file.
dir_name()
std::string Rage::dir_name (std::string const & dir)
Retrieve all except the last named component of a directory/file.
ends_with()
bool Rage::ends_with (std::string const & source, std::string const & target) inline
Determine if the source string ends with the specified content.
References tail().
Referenced by Song::TidyUpData().
head()
std::string Rage::head (std::string const & source, int32_t const length)
Get the first x characters of a string. Allow negative warping.
This comes from http://stackoverflow.com/a/7597469/445373
Referenced by NoteData::CopyRange(), and starts_with().
hexify()
std::string Rage::hexify (wchar_t const src, unsigned int dstlen)
Offer a clean way of hexify-ing a wide character. Primarily used for fonts.
See http://stackoverflow.com/a/8024386
is_utf8_continuation_byte()
bool Rage::is_utf8_continuation_byte (char p)
Determine if the byte is an official continuation byte.
Referenced by utf8_to_wchar_ec().
join() [1/2]
std::string Rage::join (std::string const & delimiter, std::vector< std::string > const & source)
Join all of the strings together into one string.
Referenced by FilenameDB::AddFile(), ScreenServiceAction::BeginScreen(), InputMapper::CheckForChangedInputDevicesAndRemap(), ArchHooks_Win32::CheckForMultipleInstances(), CopyEdits(), RageSoundDriver::Create(), NoteField::DrawPrimitives(), FillInHighScore(), RageInput::GetDisplayDevicesString(), NotesWriterSM::GetEditFileContents(), NotesWriterSSC::GetEditFileContents(), GetETTNoteData(), PlayerOptions::GetLocalizedMods(), SongOptions::GetLocalizedString(), GetMountDir(), Command::GetOriginalCommandString(), NoteSkinManager::GetPathFromDirAndFile(), GetPromptText(), GetSMNotesTag(), GetSSCNoteData(), SongOptions::GetString(), PlayerOptions::GetString(), BackgroundChange::GetTextDescription(), RageDisplay_GLES2::Init(), ScreenSelectMaster::Init(), RageDisplay_Legacy::Init(), ScreenEvaluation::Init(), JoinLineList(), Font::Load(), EventDevice::Open(), ActorUtil::ResolvePath(), ScreenMapControllers::SanityCheckWrapper(), SongManager::SaveEnabledSongsToPref(), SetPrefsDefaultModifiers(), RageDisplay::SetVideoMode(), actor_template_t::store_cmd(), Song::TidyUpData(), RadarValues::ToString(), ScreenInstallOverlay::Update(), InputList::Update(), ScreenSyncOverlay::UpdateText(), WriteGlobalTags(), InputMappings::WriteMappings(), and WriteTimingTags().
join() [2/2]
std::string Rage::join (std::string const & delimiter, std::vector< std::string >::const_iterator start, std::vector< std::string >::const_iterator finish)
Join all of the strings together into one string.
References append.
make_lower() [1/3]
std::wstring Rage::make_lower (std::wstring const & s)
Convert a wide string to its lowercase variant.
References convert_unicode_casing(), and lowerCase.
make_lower() [2/3]
wchar_t Rage::make_lower (wchar_t const & s)
Convert a wide string to its lowercase variant.
References make_lower().
make_lower() [3/3]
std::string Rage::make_lower (std::string const & source)
Convert the string into its lowercase variant.
References make_lower().
Referenced by MusicWheel::BuildWheelItemDatas(), make_lower(), LuaHelpers::ParseCommandList(), LunaProfile::SortByName(), and LunaPacklist::SortByName().
make_upper() [1/3]
std::string Rage::make_upper (std::string const & source)
Convert the string into its uppercase variant.
References make_upper().
Referenced by make_upper().
make_upper() [2/3]
std::wstring Rage::make_upper (std::wstring const & s)
Convert a wide string to its uppercase variant.
References convert_unicode_casing(), and upperCase.
make_upper() [3/3]
wchar_t Rage::make_upper (wchar_t const & s)
Convert a wide string to its uppercase variant.
References make_upper().
replace() [1/2]
void Rage::replace (std::string & target, char from, char to)
Offer a clean way of replacing all occurances of a character with a different character.
See http://stackoverflow.com/a/2896627
Referenced by LuaHelpers::ParseCommandList(), and StdString::CStdStr< CT >::Replace().
replace() [2/2]
void Rage::replace (std::string & target, std::string const & from, std::string const & to)
Offer a clean way of replacing all occurances of a string with a different string.
See http://stackoverflow.com/a/29752943
split() [1/4]
std::vector< std::string > Rage::split (std::string const & source, std::string const & delimiter)
Split a string into a vector based on the delimiter.
References skip.
Referenced by split().
split() [2/4]
std::vector< std::string > Rage::split (std::string const & source, std::string const & delimiter, Rage::EmptyEntries shouldIgnoreEmptyEntries)
Split a string into a vector based on the delimiter.
References do_split().
split() [3/4]
std::vector< std::wstring > Rage::split (std::wstring const & source, std::wstring const & delimiter)
Split a string into a vector based on the delimiter.
References include, and split().
split() [4/4]
std::vector< std::wstring > Rage::split (std::wstring const & source, std::wstring const & delimiter, Rage::EmptyEntries shouldIgnoreEmptyEntries)
Split a string into a vector based on the delimiter.
References do_split().
split_in_place() [1/8]
void Rage::split_in_place (std::string const & source, std::string const & delimitor, int & start, int & size)
Split "in-place" using indexes.
Parameters
source The string to "split".
delimiter The phrase to "split" the string by.
start An in-out parameter indicating the starting position of the string to "split" from.
size An in-out parameter to indicate how far to read in.
References do_split(), and skip.
split_in_place() [2/8]
void Rage::split_in_place (std::string const & source, std::string const & delimitor, int & start, int & size, Rage::EmptyEntries shouldIgnore)
Split "in-place" using indexes.
Parameters
source The string to "split".
delimiter The phrase to "split" the string by.
start An in-out parameter indicating the starting position of the string to "split" from.
size An in-out parameter to indicate how far to read in.
shouldSkipEmptyEntries a flag to indicate if empty elements from the split should be skipped or not.
References do_split().
split_in_place() [3/8]
void Rage::split_in_place (std::wstring const & source, std::wstring const & delimitor, int & start, int & size)
Split "in-place" using indexes.
Parameters
source The string to "split".
delimiter The phrase to "split" the string by.
start An in-out parameter indicating the starting position of the string to "split" from.
size An in-out parameter to indicate how far to read in.
References do_split(), and skip.
split_in_place() [4/8]
void Rage::split_in_place (std::wstring const & source, std::wstring const & delimitor, int & start, int & size, Rage::EmptyEntries shouldIgnore)
Split "in-place" using indexes.
Parameters
source The string to "split".
delimiter The phrase to "split" the string by.
start An in-out parameter indicating the starting position of the string to "split" from.
size An in-out parameter to indicate how far to read in.
shouldSkipEmptyEntries a flag to indicate if empty elements from the split should be skipped or not.
References do_split().
split_in_place() [5/8]
void Rage::split_in_place (std::string const & source, std::string const & delimitor, int & start, int & size, int len)
Split "in-place" using indexes.
References do_split(), and skip.
split_in_place() [6/8]
void Rage::split_in_place (std::string const & source, std::string const & delimitor, int & start, int & size, int len, Rage::EmptyEntries shouldIgnore)
Split "in-place" using indexes.
References do_split().
split_in_place() [7/8]
void Rage::split_in_place (std::wstring const & source, std::wstring const & delimitor, int & start, int & size, int len)
Split "in-place" using indexes.
References do_split(), and skip.
split_in_place() [8/8]
void Rage::split_in_place (std::wstring const & source, std::wstring const & delimitor, int & start, int & size, int len, Rage::EmptyEntries shouldIgnore)
Split "in-place" using indexes.
References do_split().
starts_with()
bool Rage::starts_with (std::string const & source, std::string const & target) inline
Determine if the source string begins with the specified content.
References head().
Referenced by checkProtocol(), and Song::TidyUpData().
tail()
std::string Rage::tail (std::string const & source, int32_t const length)
Get the last x characters of a string. Allow negative warping.
This comes from http://stackoverflow.com/a/7597469/445373
Referenced by ends_with(), and NoteDataUtil::InsertHoldTails().
trim() [1/2]
std::string Rage::trim (std::string const & source)
Trim the front and back of the string of all whitespace characters.
Referenced by SetString().
trim() [2/2]
std::string Rage::trim (std::string const & source, std::string const & delimiters)
Trim the front and back of the string of all characters of the caller's choosing.
trim_left() [1/2]
std::string Rage::trim_left (std::string const & source)
Trim the front of the string of all whitespace characters.
trim_left() [2/2]
std::string Rage::trim_left (std::string const & source, std::string const & delimiters)
Trim the front of the string of all characters of the caller's choosing.
trim_right() [1/2]
std::string Rage::trim_right (std::string const & source)
Trim the back of the string of all whitespace characters.
trim_right() [2/2]
std::string Rage::trim_right (std::string const & source, std::string const & delimiters)
Trim the back of the string of all characters of the caller's choosing.
utf8_get_char()
wchar_t Rage::utf8_get_char (std::string const & s)
Attempt to get a wide character from the UTF-8 string.
Returns
the appropriate wide character if one exists, or an appropiate default character if one does not.
References invalid_char, and utf8_to_wchar_ec().
Referenced by Font::LoadFontPageSettings(), ColorBitmapText::ResetText(), and ColorBitmapText::SetText().
utf8_get_char_len()
int Rage::utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
Referenced by Font::LoadFontPageSettings(), ColorBitmapText::ResetText(), ColorBitmapText::SetText(), utf8_to_wchar(), and utf8_to_wchar_ec().
utf8_is_valid()
bool Rage::utf8_is_valid (const std::string & s)
Determine if the string passed in is a valid UTF-8 string.
Returns
true if it's a valid UTF-8 string.
References picosha2::detail::ch(), and utf8_to_wchar_ec().
Referenced by BMSSong::AllocateKeysound(), ConvertString(), and BMSSong::GetBackground().
utf8_remove_bom()
void Rage::utf8_remove_bom (std::string & s)
Remove the starting Byte Order Mark (BOM) form the string if it exists.
Referenced by LyricsLoader::LoadFromLRCFile(), CsvFile::ReadFile(), and IniFile::ReadFile().
utf8_sanitize()
void Rage::utf8_sanitize (std::string & s)
Sanitize the UTF-8 string.
References picosha2::detail::ch(), invalid_char, utf8_to_wchar_ec(), and wchar_to_utf8().
utf8_to_wchar()
bool Rage::utf8_to_wchar (char const * s, size_t iLength, unsigned & start, wchar_t & ch)
Decode a code point and place within the output variable.
This variant only does enough error checking to prevent crashing.
Returns
true if a valid encoded string was found.
References L, and utf8_get_char_len().
Referenced by unicode_do_casing().
utf8_to_wchar_ec()
bool Rage::utf8_to_wchar_ec (std::string const & s, unsigned & start, wchar_t & ch)
Decode a code point and place within the output variable.
Returns
true if a valid encoded string was found.
References is_utf8_continuation_byte(), and utf8_get_char_len().
Referenced by utf8_get_char(), utf8_is_valid(), and utf8_sanitize().
wchar_to_utf8()
void Rage::wchar_to_utf8 (wchar_t ch, std::string & out)
Analyze the wide character and turn into a UTF-8 string.
Referenced by unicode_do_casing(), and utf8_sanitize().
Variable Documentation
invalid_char
wchar_t const Rage::invalid_char = 0xFFFD
The unicode replacement character, FFFD.
Referenced by utf8_get_char(), and utf8_sanitize().
lowerCase
unsigned char Rage::lowerCase
Initial value:
= {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x6B,
    0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B,
    0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3,
    0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB,
    0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7,
    0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xC0, 0xC1, 0xC2, 0xC3,
    0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
    0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xF7, 0xD8, 0xD9, 0xDA, 0xDB,
    0xDC, 0xDD, 0xDE, 0xFF
}
A mapping to allow for quick lowercase conversion.
Referenced by make_lower(), and make_lower().
upperCase
unsigned char Rage::upperCase
Initial value:
= {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47,
    0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F, 0x50, 0x51, 0x52, 0x53,
    0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
    0x60, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B,
    0x4C, 0x4D, 0x4E, 0x4F, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
    0x58, 0x59, 0x5A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B,
    0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3,
    0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB,
    0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7,
    0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xC0, 0xC1, 0xC2, 0xC3,
    0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
    0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xF7, 0xD8, 0xD9, 0xDA, 0xDB,
    0xDC, 0xDD, 0xDE, 0xFF
}
A mapping to allow for quick uppercase conversion.
Referenced by make_upper(), and make_upper().