Etterna: ScreenOptionsManageProfiles.cpp File Reference
ScreenOptionsManageProfiles.cpp File Reference
#include "ScreenOptionsManageProfiles.h"
#include "CommonMetrics.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "OptionRowHandler.h"
#include "ProfileManager.h"
#include "RageLog.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "ScreenMiniMenu.h"
#include "ScreenPrompt.h"
#include "ScreenTextEntry.h"
#include "global.h"
Macros
#define SHOW_CREATE_NEW (!PROFILEMAN->FixedProfiles())
#define FOREACH_ProfileAction(i) FOREACH_ENUM(ProfileAction, i)
Loop through each ProfileAction.
#define ADD_ACTION(i)
Enumerations
enum ProfileAction {
ProfileAction_SetDefaultP1, ProfileAction_SetDefaultP2, ProfileAction_Edit, ProfileAction_Rename,
ProfileAction_Delete, ProfileAction_Clear, ProfileAction_MergeToMachine, ProfileAction_MergeToMachineSkipTotal,
ProfileAction_MergeToP1, ProfileAction_MergeToP2, ProfileAction_ChangeToGuest, ProfileAction_ChangeToNormal,
ProfileAction_ChangeToTest, ProfileAction_MoveUp, ProfileAction_MoveDown, NUM_ProfileAction
}
Functions
AutoScreenMessage (SM_BackFromEnterNameForNew)
AutoScreenMessage (SM_BackFromRename)
AutoScreenMessage (SM_BackFromDeleteConfirm)
AutoScreenMessage (SM_BackFromClearConfirm)
AutoScreenMessage (SM_BackFromContextMenu)
XToString (ProfileAction)
XToLocalizedString (ProfileAction)
static bool ValidateLocalProfileName (const RString &sAnswer, RString &sErrorOut)
REGISTER_SCREEN_CLASS (ScreenOptionsManageProfiles)
Variables
static LocalizedString NEW_PROFILE_DEFAULT_NAME ("ScreenOptionsManageProfiles", "NewProfileDefaultName")
static const char * ProfileActionNames []
static MenuDef g_TempMenu ("ScreenMiniMenuContext")
static LocalizedString PROFILE_NAME_BLANK ("ScreenEditMenu", "Profile name cannot be blank.")
static LocalizedString PROFILE_NAME_CONFLICTS ("ScreenEditMenu", "The name you chose conflicts " "with another profile. Please " "use a different name.")
static LocalizedString CONFIRM_DELETE_PROFILE ("ScreenOptionsManageProfiles", "Are you sure you want to delete the profile '%s'?")
static LocalizedString CONFIRM_CLEAR_PROFILE ("ScreenOptionsManageProfiles", "Are you sure you want to clear all data in the profile '%s'?")
static LocalizedString ENTER_PROFILE_NAME ("ScreenOptionsManageProfiles", "Enter a name for the profile.")
Macro Definition Documentation
ADD_ACTION
#define ADD_ACTION (i)
Value:
g_TempMenu.rows.push_back(MenuRowDef(i,                                    \
                                         ProfileActionToLocalizedString(i),    \
                                         true,                                 \
                                         EditMode_Home,                        \
                                         false,                                \
                                         false,                                \
                                         0,                                    \
                                         ""));
Referenced by ScreenOptionsManageProfiles::ProcessMenuStart().
FOREACH_ProfileAction
#define FOREACH_ProfileAction (i) FOREACH_ENUM(ProfileAction, i)
Loop through each ProfileAction.
SHOW_CREATE_NEW
#define SHOW_CREATE_NEW (!PROFILEMAN->FixedProfiles())
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsManageProfiles::GetLocalProfileIndexWithFocus(), and ScreenOptionsManageProfiles::ProcessMenuStart().
Enumeration Type Documentation
ProfileAction
enum ProfileAction
Enumerator
ProfileAction_SetDefaultP1
ProfileAction_SetDefaultP2
ProfileAction_Edit
ProfileAction_Rename
ProfileAction_Delete
ProfileAction_Clear
ProfileAction_MergeToMachine
ProfileAction_MergeToMachineSkipTotal
ProfileAction_MergeToP1
ProfileAction_MergeToP2
ProfileAction_ChangeToGuest
ProfileAction_ChangeToNormal
ProfileAction_ChangeToTest
ProfileAction_MoveUp
ProfileAction_MoveDown
NUM_ProfileAction
Function Documentation
AutoScreenMessage() [1/5]
AutoScreenMessage (SM_BackFromEnterNameForNew)
AutoScreenMessage() [2/5]
AutoScreenMessage (SM_BackFromRename)
AutoScreenMessage() [3/5]
AutoScreenMessage (SM_BackFromDeleteConfirm)
AutoScreenMessage() [4/5]
AutoScreenMessage (SM_BackFromClearConfirm)
AutoScreenMessage() [5/5]
AutoScreenMessage (SM_BackFromContextMenu)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenOptionsManageProfiles)
ValidateLocalProfileName()
static bool ValidateLocalProfileName (const RString & sAnswer, RString & sErrorOut) static
References GAMESTATE, ProfileManager::GetLocalProfile(), ProfileManager::GetLocalProfileDisplayNames(), Profile::m_sDisplayName, GameState::m_sEditLocalProfileID, PROFILE_NAME_BLANK, PROFILE_NAME_CONFLICTS, and PROFILEMAN.
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage(), and ScreenOptionsManageProfiles::ProcessMenuStart().
XToLocalizedString()
XToLocalizedString (ProfileAction)
XToString()
XToString (ProfileAction)
Variable Documentation
CONFIRM_CLEAR_PROFILE
LocalizedString CONFIRM_CLEAR_PROFILE("ScreenOptionsManageProfiles", "Are you sure you want to clear all data in the profile '%s'?") static
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
CONFIRM_DELETE_PROFILE
LocalizedString CONFIRM_DELETE_PROFILE("ScreenOptionsManageProfiles", "Are you sure you want to delete the profile '%s'?") static
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
ENTER_PROFILE_NAME
LocalizedString ENTER_PROFILE_NAME("ScreenOptionsManageProfiles", "Enter a name for the profile.") static
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage(), and ScreenOptionsManageProfiles::ProcessMenuStart().
g_TempMenu
MenuDef g_TempMenu("ScreenMiniMenuContext") static
Referenced by ScreenOptionsManageProfiles::ProcessMenuStart().
NEW_PROFILE_DEFAULT_NAME
LocalizedString NEW_PROFILE_DEFAULT_NAME("ScreenOptionsManageProfiles", "NewProfileDefaultName") static
Referenced by ScreenOptionsManageProfiles::ProcessMenuStart().
PROFILE_NAME_BLANK
LocalizedString PROFILE_NAME_BLANK("ScreenEditMenu", "Profile name cannot be blank.") static
Referenced by ValidateLocalProfileName().
PROFILE_NAME_CONFLICTS
LocalizedString PROFILE_NAME_CONFLICTS("ScreenEditMenu", "The name you chose conflicts " "with another profile. Please " "use a different name.") static
Referenced by ValidateLocalProfileName().
ProfileActionNames
const char* ProfileActionNames[] static
Initial value:
= {
    "SetDefaultP1", "SetDefaultP2", "Edit",           "Rename",
    "Delete",       "Clear",        "MergeToMachine", "MergeToMachineSkipTotal",
    "MergeToP1",    "MergeToP2",    "ChangeToGuest",  "ChangeToNormal",
    "ChangeToTest", "MoveUp",       "MoveDown",
}