Etterna: CubicSpline Struct Reference
CubicSpline Struct Reference
#include <CubicSpline.h>
Classes
struct SplinePoint
Public Member Functions
CubicSpline ()=default
void solve_looped ()
void solve_straight ()
void solve_polygonal ()
void p_and_tfrac_from_t (float t, bool loop, size_t &p, float &tfrac) const
float evaluate (float t, bool loop) const
float evaluate_derivative (float t, bool loop) const
float evaluate_second_derivative (float t, bool loop) const
float evaluate_third_derivative (float t, bool loop) const
void set_point (size_t i, float v)
void set_coefficients (size_t i, float b, float c, float d)
void get_coefficients (size_t i, float &b, float &c, float &d) const
void set_point_and_coefficients (size_t i, float a, float b, float c, float d)
void get_point_and_coefficients (size_t i, float &a, float &b, float &c, float &d) const
void resize (size_t s)
size_t size () const
bool empty () const
Public Attributes
float m_spatial_extent { 0.0f }
Private Member Functions
bool check_minimum_size ()
void prep_inner (size_t last, vector< float > &results)
void set_results (size_t last, vector< float > &diagonals, vector< float > &results)
Private Attributes
vector< SplinePoint > m_points
Constructor & Destructor Documentation
CubicSpline()
CubicSpline::CubicSpline () default
Member Function Documentation
check_minimum_size()
bool CubicSpline::check_minimum_size () private
References loop_space_difference(), m_points, and m_spatial_extent.
Referenced by solve_looped(), solve_polygonal(), and solve_straight().
empty()
bool CubicSpline::empty () const
References m_points.
evaluate()
float CubicSpline::evaluate (float t, bool loop) const
References DECLARE_P_AND_TFRAC, m_points, and RETURN_IF_EMPTY.
evaluate_derivative()
float CubicSpline::evaluate_derivative (float t, bool loop) const
References DECLARE_P_AND_TFRAC, f, m_points, and RETURN_IF_EMPTY.
evaluate_second_derivative()
float CubicSpline::evaluate_second_derivative (float t, bool loop) const
References DECLARE_P_AND_TFRAC, f, m_points, and RETURN_IF_EMPTY.
evaluate_third_derivative()
float CubicSpline::evaluate_third_derivative (float t, bool loop) const
References DECLARE_P_AND_TFRAC, m_points, and RETURN_IF_EMPTY.
get_coefficients()
void CubicSpline::get_coefficients (size_t i, float & b, float & c, float & d) const
References ASSERT_M, and m_points.
Referenced by get_point_and_coefficients().
get_point_and_coefficients()
void CubicSpline::get_point_and_coefficients (size_t i, float & a, float & b, float & c, float & d) const
References get_coefficients(), and m_points.
p_and_tfrac_from_t()
void CubicSpline::p_and_tfrac_from_t (float t, bool loop, size_t & p, float & tfrac) const
References f, and m_points.
prep_inner()
void CubicSpline::prep_inner (size_t last, vector< float > & results) private
References loop_space_difference(), m_points, and m_spatial_extent.
Referenced by solve_looped(), and solve_straight().
resize()
void CubicSpline::resize (size_t s)
References m_points.
set_coefficients()
void CubicSpline::set_coefficients (size_t i, float b, float c, float d)
References ASSERT_M, and m_points.
Referenced by set_point_and_coefficients().
set_point()
void CubicSpline::set_point (size_t i, float v)
References ASSERT_M, and m_points.
set_point_and_coefficients()
void CubicSpline::set_point_and_coefficients (size_t i, float a, float b, float c, float d)
References m_points, and set_coefficients().
set_results()
void CubicSpline::set_results (size_t last, vector< float > & diagonals, vector< float > & results) private
References loop_space_difference(), m_points, m_spatial_extent, and UNNAN.
Referenced by solve_looped(), and solve_straight().
size()
size_t CubicSpline::size () const
References m_points.
solve_looped()
void CubicSpline::solve_looped ()
References check_minimum_size(), loop_space_difference(), m_points, m_spatial_extent, prep_inner(), set_results(), and SplineSolutionCache::solve_diagonals_looped().
solve_polygonal()
void CubicSpline::solve_polygonal ()
References check_minimum_size(), loop_space_difference(), m_points, and m_spatial_extent.
solve_straight()
void CubicSpline::solve_straight ()
References check_minimum_size(), loop_space_difference(), m_points, m_spatial_extent, prep_inner(), set_results(), and SplineSolutionCache::solve_diagonals_straight().
Member Data Documentation
m_points
vector<SplinePoint> CubicSpline::m_points private
Referenced by check_minimum_size(), empty(), evaluate(), evaluate_derivative(), evaluate_second_derivative(), evaluate_third_derivative(), get_coefficients(), get_point_and_coefficients(), p_and_tfrac_from_t(), prep_inner(), resize(), set_coefficients(), set_point(), set_point_and_coefficients(), set_results(), size(), solve_looped(), solve_polygonal(), and solve_straight().
m_spatial_extent
float CubicSpline::m_spatial_extent { 0.0f }
Referenced by check_minimum_size(), prep_inner(), set_results(), solve_looped(), solve_polygonal(), and solve_straight().
The documentation for this struct was generated from the following files:
CubicSpline.h
CubicSpline.cpp