Etterna: NoteDataWithScoring Namespace Reference
NoteDataWithScoring Namespace Reference
NoteData with scores for each TapNote and HoldNote.
Functions
bool IsRowCompletelyJudged (const NoteData &in, unsigned iRow, PlayerNumber plnum=PlayerNumber_Invalid)
Has the current row of NoteData been judged completely?
TapNoteScore MinTapNoteScore (const NoteData &in, unsigned iRow, PlayerNumber plnum=PlayerNumber_Invalid)
const TapNote & LastTapNoteWithResult (const NoteData &in, unsigned iRow, PlayerNumber plnum=PlayerNumber_Invalid)
void GetActualRadarValues (const NoteData &in, const PlayerStageStats &pss, float song_seconds, RadarValues &out)
Detailed Description
NoteData with scores for each TapNote and HoldNote.
Function Documentation
GetActualRadarValues()
void NoteDataWithScoring::GetActualRadarValues (const NoteData & in, const PlayerStageStats & pss, float song_seconds, RadarValues & out)
References garv_state::curr_row, DEFAULT_FAIL, DoRowEndRadarActualCalc(), FOREACH_ENUM, GAMESTATE, GameState::GetCurrentGame(), GameState::GetProcessedTimingData(), NoteData::GetTapNoteRangeAllTracks(), garv_state::hands_hit, HNS_Held, garv_state::hold_ends, garv_state::holds_held, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), TimingData::IsJudgableAtRow(), garv_state::judgable, garv_state::jumps_hit, garv_state::last_time_on_row, garv_state::last_tns_on_row, garv_state::lifts_hit, garv_state::lifts_tns, Game::m_bTickHolds, PlayerStageStats::m_player_number, MAX_NOTE_ROW, garv_state::mines_avoided, garv_state::notes_hit, garv_state::notes_hit_for_stream, garv_state::num_holds_on_curr_row, garv_state::num_notes_on_curr_row, PLAYER_INVALID, RadarCategory_Fakes, RadarCategory_Hands, RadarCategory_Holds, RadarCategory_Jumps, RadarCategory_Lifts, RadarCategory_Mines, RadarCategory_Notes, RadarCategory_Rolls, RadarCategory_TapsAndHolds, garv_state::rolls_held, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), garv_state::stream_tns, TapNoteScore_Invalid, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_HoldTail, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, garv_state::taps_hit, garv_state::taps_tns, TNS_AvoidMine, UpdateHittable(), and garv_state::worst_tns_on_row.
Referenced by ScreenGameplay::SaveStats().
IsRowCompletelyJudged()
bool NoteDataWithScoring::IsRowCompletelyJudged (const NoteData & in, unsigned iRow, PlayerNumber plnum = PlayerNumber_Invalid)
Has the current row of NoteData been judged completely?
Parameters
in the entire Notedata.
iRow the row to check. If valid, only consider notes for that PlayerNumber
Returns
true if it has been completley judged, or false otherwise.
References MinTapNoteScore(), and TNS_Miss.
Referenced by Player::GetClosestNonEmptyRowDirectional(), Player::Step(), and Player::UpdateJudgedRows().
LastTapNoteWithResult()
const TapNote & NoteDataWithScoring::LastTapNoteWithResult (const NoteData & in, unsigned iRow, PlayerNumber plnum = PlayerNumber_Invalid)
References NoteData::GetTapNote(), and TAP_EMPTY.
Referenced by Player::FlashGhostRow(), ScoreKeeper::GetScoreOfLastTapInRow(), ScoreKeeperNormal::HandleTapRowScore(), Player::HandleTapRowScore(), and Player::UpdateJudgedRows().
MinTapNoteScore()
TapNoteScore NoteDataWithScoring::MinTapNoteScore (const NoteData & in, unsigned iRow, PlayerNumber plnum = PlayerNumber_Invalid)
References NoteData::GetNumTracks(), NoteData::GetTapNote(), min(), PlayerNumber_Invalid, TapNote::pn, TapNote::result, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Mine, TapNoteResult::tns, TNS_W1, and TapNote::type.
Referenced by IsRowCompletelyJudged().