Etterna: BMSLoader Namespace Reference
BMSLoader Namespace Reference
Reads a Song from a set of .BMS files.
Functions
void GetApplicableFiles (const RString &sPath, vector< RString > &out)
bool LoadFromDir (const RString &sDir, Song &out)
bool LoadNoteDataFromSimfile (const RString &cachePath, Steps &out)
Detailed Description
Reads a Song from a set of .BMS files.
Function Documentation
GetApplicableFiles()
void BMSLoader::GetApplicableFiles (const RString & sPath, vector< RString > & out)
References GetDirListing().
Referenced by LoadFromDir(), NotesLoader::LoadFromDir(), DWILoader::LoadFromDir(), and OsuLoader::LoadFromDir().
LoadFromDir()
bool BMSLoader::LoadFromDir (const RString & sDir, Song & out)
References ASSERT, GetApplicableFiles(), LOG, Song::m_vsKeysoundFile, and RageLog::Trace().
Referenced by NotesLoader::LoadFromDir().
LoadNoteDataFromSimfile()
bool BMSLoader::LoadNoteDataFromSimfile (const RString & cachePath, Steps & out)
References BMSChart::Load(), Steps::m_pSong, and BMSChartReader::Read().
Referenced by Steps::GetNoteDataFromSimfile().