Etterna: RageUtil_AutoPtr.h File Reference
RageUtil_AutoPtr.h File Reference
#include "global.h"
Classes
class AutoPtrCopyOnWrite< T >
struct HiddenPtrTraits< T >
class HiddenPtr< T >
Macros
#define REGISTER_CLASS_TRAITS(T, CopyExpr)
Functions
template<class T >
void swap (AutoPtrCopyOnWrite< T > &a, AutoPtrCopyOnWrite< T > &b)
template<class T >
void swap (HiddenPtr< T > &a, HiddenPtr< T > &b)
Macro Definition Documentation
REGISTER_CLASS_TRAITS
#define REGISTER_CLASS_TRAITS (T, CopyExpr)
Value:
template<>                                                                 \
    T* HiddenPtrTraits<T>::Copy(const T* pCopy)                                \
    {                                                                          \
        return CopyExpr;                                                       \
    }                                                                          \
    template<>                                                                 \
    void HiddenPtrTraits<T>::Delete(T* p)                                      \
    {                                                                          \
        delete p;                                                              \
    }
Function Documentation
swap() [1/2]
template<class T > void swap (AutoPtrCopyOnWrite< T > & a, AutoPtrCopyOnWrite< T > & b) inline
References AutoPtrCopyOnWrite< T >::Swap().
Referenced by NoteDisplay::DrawHold(), NoteDisplay::DrawHoldBody(), NoteDisplay::DrawHoldPart(), AutoKeysounds::FinishLoading(), Player::GetClosestNoteDirectional(), HandleInputEvents(), MovieTexture_DShow::Init(), RageSoundDriver::MixIntoBuffer(), OptimizeDWIPair(), RageSurfaceUtils::Palettize(), RageSoundUtil::Pan(), ScoreManager::PutScoreAtTheTop(), LowLevelWindow_MacOSX::SetActualParamsFromMode(), RageTexturePreloader::Swap(), CircBuf< RageSoundDriver::sound_block >::swap(), AutoPtrCopyOnWrite< LuaReference >::Swap(), HiddenPtr< NoteData >::Swap(), and LowLevelWindow_MacOSX::TryVideoMode().
swap() [2/2]
template<class T > void swap (HiddenPtr< T > & a, HiddenPtr< T > & b) inline
References HiddenPtr< T >::Swap().