Etterna: WarpSegment Struct Reference
WarpSegment Struct Reference
Identifies when a song needs to warp to a new beat.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
TimingSegment * Copy () const override
bool IsNotable () const override
void DebugPrint () const override
WarpSegment ()
WarpSegment (const WarpSegment &other)
WarpSegment (int iStartRow, int iLengthRows)
WarpSegment (int iStartRow, float fBeats)
int GetLengthRows () const
float GetLengthBeats () const
float GetLength () const
void SetLength (int iRows)
void SetLength (float fBeats)
void Scale (int start, int length, int newLength) override
Scales itself.
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const WarpSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
int m_iLengthRows
The number of rows the WarpSegment will warp past.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a song needs to warp to a new beat.
A warp segment is used to replicate the effects of Negative BPMs without abusing negative BPMs. Negative BPMs should be converted to warp segments. WarpAt=WarpToRelative is the format, where both are in beats. (Technically they're both rows though.)
Constructor & Destructor Documentation
WarpSegment() [1/4]
WarpSegment::WarpSegment () inline
Referenced by Copy().
WarpSegment() [2/4]
WarpSegment::WarpSegment (const WarpSegment & other) inline
WarpSegment() [3/4]
WarpSegment::WarpSegment (int iStartRow, int iLengthRows) inline
WarpSegment() [4/4]
WarpSegment::WarpSegment (int iStartRow, float fBeats) inline
Member Function Documentation
Copy()
TimingSegment* WarpSegment::Copy () const inline override virtual
Implements TimingSegment.
References WarpSegment().
DebugPrint()
void WarpSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLengthBeats(), GetLengthRows(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType WarpSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Range.
GetLength()
float WarpSegment::GetLength () const inline
References GetLengthBeats().
Referenced by TimingData::GetBeatInternal(), TimingData::GetElapsedTimeInternal(), GetValues(), SongCacheIndex::InsertStepsTimingData(), TimingData::IsWarpAtRow(), Scale(), ToString(), and WriteGlobalTags().
GetLengthBeats()
float WarpSegment::GetLengthBeats () const inline
References m_iLengthRows, and ToBeat().
Referenced by DebugPrint(), and GetLength().
GetLengthRows()
int WarpSegment::GetLengthRows () const inline
References m_iLengthRows.
Referenced by DebugPrint().
GetType()
TimingSegmentType WarpSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_WARP.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> WarpSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetLength().
IsNotable()
bool WarpSegment::IsNotable () const inline override virtual
Implements TimingSegment.
References m_iLengthRows.
operator==() [1/2]
bool WarpSegment::operator== (const WarpSegment & other) const inline
References COMPARE, and m_iLengthRows.
Referenced by operator==().
operator==() [2/2]
bool WarpSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
Scale()
void WarpSegment::Scale (int start, int length, int newLength) override virtual
Scales itself.
Parameters
start Starting row
length Length in rows
newLength The new length in rows
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLength(), NoteRowToBeat(), TimingSegment::Scale(), ScalePosition(), and SetLength().
SetLength() [1/2]
void WarpSegment::SetLength (int iRows) inline
References m_iLengthRows, and ToNoteRow().
Referenced by Scale().
SetLength() [2/2]
void WarpSegment::SetLength (float fBeats) inline
References m_iLengthRows, and ToNoteRow().
ToString()
RString WarpSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLength(), IntToString(), and ssprintf().
Member Data Documentation
m_iLengthRows
int WarpSegment::m_iLengthRows private
The number of rows the WarpSegment will warp past.
Referenced by GetLengthBeats(), GetLengthRows(), IsNotable(), operator==(), and SetLength().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp