Etterna: InputHandler_Win32_Pump Class Reference
InputHandler_Win32_Pump Class Reference
#include <InputHandler_Win32_Pump.h>
Public Member Functions
void Update ()
InputHandler_Win32_Pump ()
~InputHandler_Win32_Pump ()
RString GetDeviceSpecificInputString (const DeviceInput &di)
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual bool DevicesChanged ()
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void InputThreadMain ()
void HandleInput (int devno, int event)
Static Private Member Functions
static int InputThread_Start (void *p)
Private Attributes
USBDevice * m_pDevice
RageThread InputThread
bool m_bShutdown
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_Win32_Pump()
InputHandler_Win32_Pump::InputHandler_Win32_Pump ()
References RageThread::Create(), RageLog::Info(), InputThread, InputThread_Start(), LOG, m_bShutdown, PrefsManager::m_bThreadedInput, m_pDevice, NUM_PUMPS, PREFSMAN, and RageThread::SetName().
~InputHandler_Win32_Pump()
InputHandler_Win32_Pump::~InputHandler_Win32_Pump ()
References InputThread, RageThread::IsCreated(), LOG, m_bShutdown, m_pDevice, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
GetDevicesAndDescriptions()
void InputHandler_Win32_Pump::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References DEVICE_PUMP1, m_pDevice, and NUM_PUMPS.
GetDeviceSpecificInputString()
RString InputHandler_Win32_Pump::GetDeviceSpecificInputString (const DeviceInput & di) virtual
Reimplemented from InputHandler.
References DeviceInput::button, InputHandler::GetDeviceSpecificInputString(), JOY_BUTTON_1, JOY_BUTTON_10, JOY_BUTTON_11, JOY_BUTTON_2, JOY_BUTTON_3, JOY_BUTTON_4, JOY_BUTTON_5, JOY_BUTTON_6, JOY_BUTTON_7, JOY_BUTTON_8, and JOY_BUTTON_9.
HandleInput()
void InputHandler_Win32_Pump::HandleInput (int devno, int event) private
References ARRAYLEN, InputHandler::ButtonPressed(), DEVICE_PUMP1, enum_add2(), InputThread, RageThread::IsCreated(), JOY_BUTTON_1, and DeviceInput::ts.
Referenced by InputThreadMain(), and Update().
InputThread_Start()
int InputHandler_Win32_Pump::InputThread_Start (void * p) static private
Referenced by InputHandler_Win32_Pump().
InputThreadMain()
void InputHandler_Win32_Pump::InputThreadMain () private
References CHECKPOINT, f, HandleInput(), LOG, m_bShutdown, m_pDevice, NUM_PUMPS, InputHandler::UpdateTimer(), and RageLog::Warn().
Update()
void InputHandler_Win32_Pump::Update () virtual
Reimplemented from InputHandler.
References HandleInput(), InputThread, RageThread::IsCreated(), m_pDevice, NUM_PUMPS, and InputHandler::UpdateTimer().
Member Data Documentation
InputThread
RageThread InputHandler_Win32_Pump::InputThread private
Referenced by HandleInput(), InputHandler_Win32_Pump(), Update(), and ~InputHandler_Win32_Pump().
m_bShutdown
bool InputHandler_Win32_Pump::m_bShutdown private
Referenced by InputHandler_Win32_Pump(), InputThreadMain(), and ~InputHandler_Win32_Pump().
m_pDevice
USBDevice* InputHandler_Win32_Pump::m_pDevice private
Referenced by GetDevicesAndDescriptions(), InputHandler_Win32_Pump(), InputThreadMain(), Update(), and ~InputHandler_Win32_Pump().
The documentation for this class was generated from the following files:
InputHandler_Win32_Pump.h
InputHandler_Win32_Pump.cpp