Etterna: ImageTexture Struct Reference
ImageTexture Struct Reference
Public Member Functions
unsigned GetTexHandle () const override
ImageTexture (RageTextureID id, RageSurface *&pImage, int iWidth, int iHeight)
~ImageTexture () override
void Create ()
void Destroy ()
void Reload () override
void Invalidate () override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Update (float)
virtual void SetPosition (float)
virtual void DecodeSeconds (float)
virtual void SetPlaybackRate (float)
virtual bool IsAMovie () const
virtual void SetLooping (bool)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Public Attributes
unsigned m_uTexHandle
RageSurface *& m_pImage
int m_iWidth
int m_iHeight
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Additional Inherited Members
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
ImageTexture()
ImageTexture::ImageTexture (RageTextureID id, RageSurface *& pImage, int iWidth, int iHeight) inline
References Create().
~ImageTexture()
ImageTexture::~ImageTexture () inline override
References Destroy().
Member Function Documentation
Create()
void ImageTexture::Create () inline
References ASSERT, RageSurfaceFormat::BitsPerPixel, RageTexture::CreateFrameRects(), RageDisplay::CreateTexture(), DISPLAY, RageSurface::fmt, RageTexture::GetID(), RageDisplay::GetMaxTextureSize(), RageSurface::h, LOG, m_iHeight, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_iWidth, min(), power_of_two(), RagePixelFormat_PAL, RagePixelFormat_RGB5A1, RagePixelFormat_RGBA4, RageDisplay::SupportsTextureFormat(), RageSurface::w, RageLog::Warn(), and RageSurfaceUtils::Zoom().
Referenced by ImageTexture(), and Reload().
Destroy()
void ImageTexture::Destroy () inline
References RageDisplay::DeleteTexture(), and DISPLAY.
Referenced by Reload(), and ~ImageTexture().
GetTexHandle()
unsigned ImageTexture::GetTexHandle () const inline override virtual
Implements RageTexture.
References m_uTexHandle.
Invalidate()
void ImageTexture::Invalidate () inline override virtual
Reimplemented from RageTexture.
Reload()
void ImageTexture::Reload () inline override virtual
Reimplemented from RageTexture.
References Create(), and Destroy().
Member Data Documentation
m_iHeight
int ImageTexture::m_iHeight
Referenced by Create().
m_iWidth
int ImageTexture::m_iWidth
Referenced by Create().
m_pImage
RageSurface*& ImageTexture::m_pImage
m_uTexHandle
unsigned ImageTexture::m_uTexHandle
Referenced by GetTexHandle().
The documentation for this struct was generated from the following file:
ImageCache.cpp