Etterna: MessageSubscriber Class Reference
MessageSubscriber Class Reference
#include <MessageManager.h>
Public Member Functions
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
virtual void HandleMessage (const Message &msg)=0
void ClearMessages (const RString &sMessage="")
Private Attributes
vector< RString > m_vsSubscribedTo
Constructor & Destructor Documentation
MessageSubscriber() [1/2]
MessageSubscriber::MessageSubscriber () inline
MessageSubscriber() [2/2]
MessageSubscriber::MessageSubscriber (const MessageSubscriber & cpy)
References FOREACH_CONST, m_vsSubscribedTo, and SubscribeToMessage().
Member Function Documentation
operator=()
MessageSubscriber & MessageSubscriber::operator= (const MessageSubscriber & cpy)
References FOREACH_CONST, m_vsSubscribedTo, SubscribeToMessage(), and UnsubscribeAll().
Referenced by BitmapText::operator=().
SubscribeToMessage() [1/2]
void MessageSubscriber::SubscribeToMessage (MessageID message)
References m_vsSubscribedTo, MessageIDToString(), and MessageManager::Subscribe().
Referenced by Actor::AddCommand(), GameStateImpl::GameStateImpl(), ScreenGameplaySyncMachine::Init(), ScreenSelect::Init(), ScreenContinue::Init(), ScreenStatsOverlay::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenGameplay::Init(), HoldJudgment::LoadFromMultiPlayer(), MessageSubscriber(), ModIconRow::ModIconRow(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), operator=(), ScreenMapControllers::ScreenMapControllers(), and StepsDisplayList::StepsDisplayList().
SubscribeToMessage() [2/2]
void MessageSubscriber::SubscribeToMessage (const RString & sMessageName)
References m_vsSubscribedTo, and MessageManager::Subscribe().
UnsubscribeAll()
void MessageSubscriber::UnsubscribeAll ()
References FOREACH_CONST, m_vsSubscribedTo, and MessageManager::Unsubscribe().
Referenced by operator=(), and Actor::~Actor().
Member Data Documentation
m_vsSubscribedTo
vector<RString> MessageSubscriber::m_vsSubscribedTo private
Referenced by MessageSubscriber(), operator=(), SubscribeToMessage(), and UnsubscribeAll().
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cpp