Etterna: Difficulty.cpp File Reference
Difficulty.cpp File Reference
#include "global.h"
#include "Difficulty.h"
#include "GameConstantsAndTypes.h"
#include "GameState.h"
#include "LuaManager.h"
#include "Steps.h"
#include "ThemeMetric.h"
#include "LuaBinding.h"
Classes
struct OldStyleStringToDifficultyMapHolder
Functions
XToString (Difficulty)
StringToX (Difficulty)
LuaXType (Difficulty)
Difficulty OldStyleStringToDifficulty (const RString &sDC)
LuaFunction (OldStyleStringToDifficulty, OldStyleStringToDifficulty(SArg(1)))
RString GetCustomDifficulty (StepsType st, Difficulty dc)
LuaFunction (GetCustomDifficulty, GetCustomDifficulty(Enum::Check< StepsType >(L, 1), Enum::Check< Difficulty >(L, 2)))
RString CustomDifficultyToLocalizedString (const RString &sCustomDifficulty)
LuaFunction (CustomDifficultyToLocalizedString, CustomDifficultyToLocalizedString(SArg(1)))
RString StepsToCustomDifficulty (const Steps *pSteps)
LuaFunction (StepsToCustomDifficulty, StepsToCustomDifficulty(Luna< Steps >::check(L, 1)))
Variables
static const char * DifficultyNames []
OldStyleStringToDifficultyMapHolder OldStyleStringToDifficulty_converter
static ThemeMetric< RString > NAMES ("CustomDifficulty", "Names")
Function Documentation
CustomDifficultyToLocalizedString()
RString CustomDifficultyToLocalizedString (const RString & sCustomDifficulty)
References ThemeManager::GetString(), and THEME.
Referenced by LunaGameState::GetCurrentStepsCredits(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSteps::Reload(), and StepsDisplay::SetInternal().
GetCustomDifficulty()
RString GetCustomDifficulty (StepsType st, Difficulty dc)
References Difficulty_Edit, Difficulty_Invalid, DifficultyToString(), FOREACH, ThemeMetric< T >::GetValue(), NAMES, split(), and StepsType_Invalid.
Referenced by LunaGameState::GetCurrentStepsCredits(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSteps::Reload(), StepsDisplay::SetInternal(), and StepsToCustomDifficulty().
LuaFunction() [1/4]
LuaFunction (OldStyleStringToDifficulty , OldStyleStringToDifficulty(SArg(1)))
LuaFunction() [2/4]
LuaFunction (GetCustomDifficulty , GetCustomDifficulty(Enum::Check< StepsType >(L, 1), Enum::Check< Difficulty >(L, 2)))
LuaFunction() [3/4]
LuaFunction (CustomDifficultyToLocalizedString , CustomDifficultyToLocalizedString(SArg(1)))
LuaFunction() [4/4]
LuaFunction (StepsToCustomDifficulty , StepsToCustomDifficulty(Luna< Steps >::check(L, 1)))
LuaXType()
LuaXType (Difficulty)
OldStyleStringToDifficulty()
Difficulty OldStyleStringToDifficulty (const RString & sDC)
References OldStyleStringToDifficultyMapHolder::conversion_map, Difficulty_Invalid, and StdString::CStdStr< CT >::MakeLower().
Referenced by SMLoader::LoadFromTokens(), and SMLoader::LoadNoteDataFromSimfile().
StepsToCustomDifficulty()
RString StepsToCustomDifficulty (const Steps * pSteps)
References GetCustomDifficulty(), Steps::GetDifficulty(), and Steps::m_StepsType.
Referenced by StepsDisplay::SetInternal().
StringToX()
StringToX (Difficulty)
XToString()
XToString (Difficulty)
Variable Documentation
DifficultyNames
const char* DifficultyNames[] static
Initial value:
= {
    "Beginner", "Easy", "Medium", "Hard", "Challenge", "Edit",
}
NAMES
ThemeMetric<RString> NAMES("CustomDifficulty", "Names") static
Referenced by GetCustomDifficulty().
OldStyleStringToDifficulty_converter
OldStyleStringToDifficultyMapHolder OldStyleStringToDifficulty_converter