Etterna: LunaActorFrame Class Reference
LunaActorFrame Class Reference
Allow Lua to have access to the ActorFrame.
Public Member Functions
DEFINE_METHOD (GetUpdateRate, GetUpdateRate())
LunaActorFrame ()
Public Member Functions inherited from Luna< ActorFrame >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int playcommandonchildren (T *p, lua_State *L)
static int playcommandonleaves (T *p, lua_State *L)
static int runcommandsonleaves (T *p, lua_State *L)
static int RunCommandsOnChildren (T *p, lua_State *L)
static int propagate (T *p, lua_State *L)
static int fov (T *p, lua_State *L)
static int SetUpdateRate (T *p, lua_State *L)
static int SetFOV (T *p, lua_State *L)
static int vanishpoint (T *p, lua_State *L)
static int GetChild (T *p, lua_State *L)
static int GetChildren (T *p, lua_State *L)
static int GetNumChildren (T *p, lua_State *L)
static int SetDrawByZPosition (T *p, lua_State *L)
static int SetDrawFunction (T *p, lua_State *L)
static int GetDrawFunction (T *p, lua_State *L)
static int SetUpdateFunction (T *p, lua_State *L)
static int SortByDrawOrder (T *p, lua_State *L)
static int SetAmbientLightColor (T *p, lua_State *L)
static int SetDiffuseLightColor (T *p, lua_State *L)
static int SetSpecularLightColor (T *p, lua_State *L)
static int SetLightDirection (T *p, lua_State *L)
static int AddChildFromPath (T *p, lua_State *L)
static int RemoveChild (T *p, lua_State *L)
static int RemoveAllChildren (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ActorFrame >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ActorFrame >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ActorFrame >
using T = ActorFrame
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ActorFrame >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ActorFrame.
Constructor & Destructor Documentation
LunaActorFrame()
LunaActorFrame::LunaActorFrame () inline
References ADD_METHOD, AddChildFromPath(), fov(), GetChild(), GetChildren(), GetDrawFunction(), GetNumChildren(), playcommandonchildren(), playcommandonleaves(), propagate(), RemoveAllChildren(), RemoveChild(), RunCommandsOnChildren(), runcommandsonleaves(), SetAmbientLightColor(), SetDiffuseLightColor(), SetDrawByZPosition(), SetDrawFunction(), SetFOV(), SetLightDirection(), SetSpecularLightColor(), SetUpdateFunction(), SetUpdateRate(), SortByDrawOrder(), and vanishpoint().
Member Function Documentation
AddChildFromPath()
static int LunaActorFrame::AddChildFromPath (T * p, lua_State * L) inline static
References ActorFrame::AddChild(), ActorUtil::MakeActor(), and SArg.
Referenced by LunaActorFrame().
DEFINE_METHOD()
LunaActorFrame::DEFINE_METHOD (GetUpdateRate , GetUpdateRate())
fov()
static int LunaActorFrame::fov (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorFrame::SetFOV().
Referenced by LunaActorFrame().
GetChild()
static int LunaActorFrame::GetChild (T * p, lua_State * L) inline static
References ActorFrame::PushChildTable(), and SArg.
Referenced by LunaActorFrame().
GetChildren()
static int LunaActorFrame::GetChildren (T * p, lua_State * L) inline static
References ActorFrame::PushChildrenTable().
Referenced by LunaActorFrame().
GetDrawFunction()
static int LunaActorFrame::GetDrawFunction (T * p, lua_State * L) inline static
References ActorFrame::GetDrawFunction(), and LuaReference::PushSelf().
Referenced by LunaActorFrame().
GetNumChildren()
static int LunaActorFrame::GetNumChildren (T * p, lua_State * L) inline static
References ActorFrame::GetNumChildren().
Referenced by LunaActorFrame().
playcommandonchildren()
static int LunaActorFrame::playcommandonchildren (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::PlayCommandOnChildren(), and SArg.
Referenced by LunaActorFrame().
playcommandonleaves()
static int LunaActorFrame::playcommandonleaves (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::PlayCommandOnLeaves(), and SArg.
Referenced by LunaActorFrame().
propagate()
static int LunaActorFrame::propagate (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and ActorFrame::SetPropagateCommands().
Referenced by LunaActorFrame().
RemoveAllChildren()
static int LunaActorFrame::RemoveAllChildren (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorFrame::DeleteAllChildren().
Referenced by LunaActorFrame().
RemoveChild()
static int LunaActorFrame::RemoveChild (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::GetChild(), ActorFrame::RemoveChild(), SAFE_DELETE, and SArg.
Referenced by LunaActorFrame().
RunCommandsOnChildren()
static int LunaActorFrame::RunCommandsOnChildren (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::RunCommandsOnChildren(), and LuaReference::SetFromStack().
Referenced by LunaActorFrame().
runcommandsonleaves()
static int LunaActorFrame::runcommandsonleaves (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::RunCommandsOnLeaves(), and LuaReference::SetFromStack().
Referenced by LunaActorFrame().
SetAmbientLightColor()
static int LunaActorFrame::SetAmbientLightColor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and ActorFrame::SetAmbientLightColor().
Referenced by LunaActorFrame().
SetDiffuseLightColor()
static int LunaActorFrame::SetDiffuseLightColor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and ActorFrame::SetDiffuseLightColor().
Referenced by LunaActorFrame().
SetDrawByZPosition()
static int LunaActorFrame::SetDrawByZPosition (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorFrame::SetDrawByZPosition().
Referenced by LunaActorFrame().
SetDrawFunction()
static int LunaActorFrame::SetDrawFunction (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorFrame::SetDrawFunction(), and LuaReference::SetFromStack().
Referenced by LunaActorFrame().
SetFOV()
static int LunaActorFrame::SetFOV (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorFrame::SetFOV().
Referenced by LunaActorFrame().
SetLightDirection()
static int LunaActorFrame::SetLightDirection (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, LuaHelpers::ReadArrayFromTable(), and ActorFrame::SetLightDirection().
Referenced by LunaActorFrame().
SetSpecularLightColor()
static int LunaActorFrame::SetSpecularLightColor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and ActorFrame::SetSpecularLightColor().
Referenced by LunaActorFrame().
SetUpdateFunction()
static int LunaActorFrame::SetUpdateFunction (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, LuaReference::SetFromStack(), and ActorFrame::SetUpdateFunction().
Referenced by LunaActorFrame().
SetUpdateRate()
static int LunaActorFrame::SetUpdateRate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorFrame::SetUpdateRate().
Referenced by LunaActorFrame().
SortByDrawOrder()
static int LunaActorFrame::SortByDrawOrder (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorFrame::SortByDrawOrder().
Referenced by LunaActorFrame().
vanishpoint()
static int LunaActorFrame::vanishpoint (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorFrame::SetVanishPoint().
Referenced by LunaActorFrame().
The documentation for this class was generated from the following file:
ActorFrame.cpp