Etterna: ScreenSelectMusic.cpp File Reference
ScreenSelectMusic.cpp File Reference
#include "ScreenSelectMusic.h"
#include "ActorUtil.h"
#include "CodeDetector.h"
#include "CommonMetrics.h"
#include "DownloadManager.h"
#include "Foreach.h"
#include "Game.h"
#include "GameConstantsAndTypes.h"
#include "GameManager.h"
#include "GamePreferences.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "ImageCache.h"
#include "InputEventPlus.h"
#include "InputMapper.h"
#include "MenuTimer.h"
#include "OptionsList.h"
#include "PlayerAI.h"
#include "PlayerOptions.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "ProfileManager.h"
#include "RageFileManager.h"
#include "RageInput.h"
#include "RageLog.h"
#include "RageTextureManager.h"
#include "ScoreManager.h"
#include "ScreenManager.h"
#include "ScreenPrompt.h"
#include "ScreenTextEntry.h"
#include "Song.h"
#include "SongManager.h"
#include "StageStats.h"
#include "StatsManager.h"
#include "Steps.h"
#include "StepsUtil.h"
#include "Style.h"
#include "global.h"
#include "LuaBinding.h"
Classes
class LunaScreenSelectMusic
Allow Lua to have access to the ScreenSelectMusic.
Macros
#define SHOW_OPTIONS_MESSAGE_SECONDS THEME->GetMetricF(m_sName, "ShowOptionsMessageSeconds")
Functions
XToString (SelectionState)
AutoScreenMessage (SM_AllowOptionsMenuRepeat)
AutoScreenMessage (SM_SongChanged)
AutoScreenMessage (SM_SortOrderChanging)
AutoScreenMessage (SM_SortOrderChanged)
AutoScreenMessage (SM_BackFromPlayerOptions)
AutoScreenMessage (SM_ConfirmDeleteSong)
AutoScreenMessage (SM_BackFromNamePlaylist)
REGISTER_SCREEN_CLASS (ScreenSelectMusic)
Variables
static const char * SelectionStateNames []
const int NUM_SCORE_DIGITS = 9
The maximum number of digits for the ScoreDisplay.
static const ThemeMetric< int > HARD_COMMENT_METER ("ScreenSelectMusic", "HardCommentMeter")
static RString g_sCDTitlePath
static bool g_bWantFallbackCdTitle
static bool g_bCDTitleWaiting = false
static RString g_sBannerPath
static bool g_bBannerWaiting = false
static bool g_bSampleMusicWaiting = false
static RageTimer g_StartedLoadingAt (RageZeroTimer)
static RageTimer g_ScreenStartedLoadingAt (RageZeroTimer)
RageTimer g_CanOpenOptionsList (RageZeroTimer)
static LocalizedString PERMANENTLY_DELETE ("ScreenSelectMusic", "PermanentlyDelete")
Macro Definition Documentation
SHOW_OPTIONS_MESSAGE_SECONDS
#define SHOW_OPTIONS_MESSAGE_SECONDS THEME->GetMetricF(m_sName, "ShowOptionsMessageSeconds")
Referenced by ScreenSelectMusic::SelectCurrent().
Function Documentation
AutoScreenMessage() [1/7]
AutoScreenMessage (SM_AllowOptionsMenuRepeat)
AutoScreenMessage() [2/7]
AutoScreenMessage (SM_SongChanged)
AutoScreenMessage() [3/7]
AutoScreenMessage (SM_SortOrderChanging)
AutoScreenMessage() [4/7]
AutoScreenMessage (SM_SortOrderChanged)
AutoScreenMessage() [5/7]
AutoScreenMessage (SM_BackFromPlayerOptions)
AutoScreenMessage() [6/7]
AutoScreenMessage (SM_ConfirmDeleteSong)
AutoScreenMessage() [7/7]
AutoScreenMessage (SM_BackFromNamePlaylist)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenSelectMusic)
XToString()
XToString (SelectionState)
Variable Documentation
g_bBannerWaiting
bool g_bBannerWaiting = false static
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::CheckBackgroundRequests(), and ScreenSelectMusic::SelectCurrent().
g_bCDTitleWaiting
bool g_bCDTitleWaiting = false static
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::CheckBackgroundRequests(), and ScreenSelectMusic::SelectCurrent().
g_bSampleMusicWaiting
bool g_bSampleMusicWaiting = false static
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::CheckBackgroundRequests(), and ScreenSelectMusic::SelectCurrent().
g_bWantFallbackCdTitle
bool g_bWantFallbackCdTitle static
Referenced by ScreenSelectMusic::AfterMusicChange(), and ScreenSelectMusic::CheckBackgroundRequests().
g_CanOpenOptionsList
RageTimer g_CanOpenOptionsList(RageZeroTimer)
Referenced by ScreenSelectMusic::Input().
g_sBannerPath
RString g_sBannerPath static
Referenced by ScreenSelectMusic::CheckBackgroundRequests().
g_sCDTitlePath
RString g_sCDTitlePath static
g_ScreenStartedLoadingAt
RageTimer g_ScreenStartedLoadingAt(RageZeroTimer) static
Referenced by ScreenSelectMusic::BeginScreen(), ScreenSelectMusic::CheckBackgroundRequests(), and ScreenSelectMusic::Init().
g_StartedLoadingAt
RageTimer g_StartedLoadingAt(RageZeroTimer) static
Referenced by ScreenSelectMusic::AfterMusicChange(), and ScreenSelectMusic::CheckBackgroundRequests().
HARD_COMMENT_METER
const ThemeMetric<int> HARD_COMMENT_METER("ScreenSelectMusic", "HardCommentMeter") static
Referenced by ScreenSelectMusic::SelectCurrent().
NUM_SCORE_DIGITS
const int NUM_SCORE_DIGITS = 9
The maximum number of digits for the ScoreDisplay.
Referenced by ScreenSelectMusic::AfterStepsOrTrailChange().
PERMANENTLY_DELETE
LocalizedString PERMANENTLY_DELETE("ScreenSelectMusic", "PermanentlyDelete") static
Referenced by ScreenSelectMusic::Input().
SelectionStateNames
const char* SelectionStateNames[] static
Initial value:
= { "SelectingSong",
                                             "SelectingSteps",
                                             "Finalized" }