Etterna: LunaScreenSelectMusic Class Reference
LunaScreenSelectMusic Class Reference
Allow Lua to have access to the ScreenSelectMusic.
Public Member Functions
LunaScreenSelectMusic ()
Public Member Functions inherited from Luna< ScreenSelectMusic >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetGoToOptions (T *p, lua_State *L)
static int GetMusicWheel (T *p, lua_State *L)
static int OpenOptionsList (T *p, lua_State *L)
static int CanOpenOptionsList (T *p, lua_State *L)
static int SelectCurrent (T *p, lua_State *L)
static int GetSelectionState (T *p, lua_State *L)
static int StartPlaylistAsCourse (T *p, lua_State *L)
static int PlayReplay (T *p, lua_State *L)
static int ShowEvalScreenForScore (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScreenSelectMusic >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScreenSelectMusic >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenSelectMusic >
using T = ScreenSelectMusic
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenSelectMusic >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ScreenSelectMusic.
Constructor & Destructor Documentation
LunaScreenSelectMusic()
LunaScreenSelectMusic::LunaScreenSelectMusic () inline
References ADD_METHOD, CanOpenOptionsList(), GetGoToOptions(), GetMusicWheel(), GetSelectionState(), OpenOptionsList(), PlayReplay(), SelectCurrent(), ShowEvalScreenForScore(), and StartPlaylistAsCourse().
Member Function Documentation
CanOpenOptionsList()
static int LunaScreenSelectMusic::CanOpenOptionsList (T * p, lua_State * L) inline static
References ScreenSelectMusic::can_open_options_list(), and L.
Referenced by LunaScreenSelectMusic().
GetGoToOptions()
static int LunaScreenSelectMusic::GetGoToOptions (T * p, lua_State * L) inline static
References ScreenSelectMusic::GetGoToOptions().
Referenced by LunaScreenSelectMusic().
GetMusicWheel()
static int LunaScreenSelectMusic::GetMusicWheel (T * p, lua_State * L) inline static
References ScreenSelectMusic::GetMusicWheel(), and MusicWheel::PushSelf().
Referenced by LunaScreenSelectMusic().
GetSelectionState()
static int LunaScreenSelectMusic::GetSelectionState (T * p, lua_State * L) inline static
References ScreenSelectMusic::GetSelectionState().
Referenced by LunaScreenSelectMusic().
OpenOptionsList()
static int LunaScreenSelectMusic::OpenOptionsList (T * p, lua_State * L) inline static
References ScreenSelectMusic::can_open_options_list(), COMMON_RETURN_SELF, L, and ScreenSelectMusic::OpenOptionsList().
Referenced by LunaScreenSelectMusic().
PlayReplay()
static int LunaScreenSelectMusic::PlayReplay (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), Luna< Type >::check(), GAMEMAN, GAMESTATE, ModsGroup< T >::GetCurrent(), HighScore::GetMusicRate(), ModsGroup< T >::GetPreferred(), HighScore::GetScoreKey(), ModsGroup< T >::GetSong(), PlayerOptions::GetString(), LOG, GamePreferences::m_AutoPlay, GameManager::m_bResetModifiers, SongOptions::m_fMusicRate, GameManager::m_fPreviousRate, PlayerState::m_PlayerController, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, GameManager::m_sModsToReset, GameState::m_SongOptions, MESSAGEMAN, PC_REPLAY, PLAYER_1, ScreenSelectMusic::SelectCurrent(), PlayerAI::SetScoreData(), and RageLog::Trace().
Referenced by LunaScreenSelectMusic().
SelectCurrent()
static int LunaScreenSelectMusic::SelectCurrent (T * p, lua_State * L) inline static
References ScreenSelectMusic::SelectCurrent().
Referenced by LunaScreenSelectMusic().
ShowEvalScreenForScore()
static int LunaScreenSelectMusic::ShowEvalScreenForScore (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), Luna< Type >::check(), GAMEMAN, GAMESTATE, ModsGroup< T >::GetCurrent(), ScoreManager::GetMostRecentScore(), HighScore::GetMusicRate(), ModsGroup< T >::GetPreferred(), HighScore::GetScoreKey(), ModsGroup< T >::GetSong(), HighScore::GetWifeScore(), StageStats::Init(), HighScore::LoadReplayData(), LOG, GamePreferences::m_AutoPlay, GameManager::m_bResetModifiers, StatsManager::m_CurStageStats, SongOptions::m_fMusicRate, GameManager::m_fPreviousRate, PlayerStageStats::m_HighScore, GameState::m_pCurSong, StageStats::m_player, GameState::m_SongOptions, StatsManager::m_vPlayedStageStats, StageStats::m_vpPlayedSongs, MESSAGEMAN, NUM_HoldNoteScore, NUM_TapNoteScore, PC_REPLAY, ScoreManager::PutScoreAtTheTop(), SCOREMAN, SCREENMAN, ScreenManager::SetNewScreen(), STATSMAN, TNS_Miss, and RageLog::Trace().
Referenced by LunaScreenSelectMusic().
StartPlaylistAsCourse()
static int LunaScreenSelectMusic::StartPlaylistAsCourse (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), picosha2::detail::ch(), Playlist::chartlist, FOREACH, GAMESTATE, ScreenSelectMusic::GetMusicWheel(), SongManager::GetPlaylists(), ModsGroup< T >::GetPreferred(), GameState::isplaylistcourse, SongOptions::m_fMusicRate, GameState::m_SongOptions, MESSAGEMAN, PLAYER_1, SongManager::playlistcourse, SArg, ScreenSelectMusic::SelectCurrent(), MusicWheel::SelectSong(), and SONGMAN.
Referenced by LunaScreenSelectMusic().
The documentation for this class was generated from the following file:
ScreenSelectMusic.cpp