Etterna: InputHandler_Win32_Para.cpp File Reference
InputHandler_Win32_Para.cpp File Reference
#include "InputHandler_Win32_Para.h"
#include "global.h"
#include "RageInputDevice.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Win32/USB.h"
#include "archutils/Win32/ddk/setupapi.h"
#include "archutils/Win32/ddk/hidsdi.h"
Functions
REGISTER_INPUT_HANDLER_CLASS2 (Para, Win32_Para)
static void InitHack (HANDLE h)
Function Documentation
InitHack()
static void InitHack (HANDLE h) static
References RageLog::Info(), LOG, and RageLog::Warn().
Referenced by InputHandler_Win32_Para::InputHandler_Win32_Para().
REGISTER_INPUT_HANDLER_CLASS2()
REGISTER_INPUT_HANDLER_CLASS2 (Para , Win32_Para)