Etterna: PlayerInfo Class Reference
PlayerInfo Class Reference
#include <ScreenGameplay.h>
Public Member Functions
PlayerInfo ()
~PlayerInfo ()
void Load (PlayerNumber pn, MultiPlayer mp, bool bShowNoteField, int iAddToDifficulty)
void LoadDummyP1 (int iDummyIndex, int iAddToDifficulty)
void ShowOniGameOver ()
The player has lost all of their lives: show the special game over.
MultiPlayer GetPlayerStateAndStageStatsIndex ()
Retrieve the player's state and stage stats index.
PlayerState * GetPlayerState ()
PlayerStageStats * GetPlayerStageStats ()
PlayerNumber GetStepsAndTrailIndex ()
bool IsEnabled ()
Determine if the player information is enabled.
bool IsMultiPlayer () const
Determine if we're in MultiPlayer.
RString GetName () const
Retrieve the name of the Player based on the mode.
void PushSelf (lua_State *L)
Public Attributes
PlayerNumber m_pn
The present Player's number.
MultiPlayer m_mp { MultiPlayer_Invalid }
The present Player's multiplayer number.
bool m_bIsDummy { false }
int m_iDummyIndex { 0 }
int m_iAddToDifficulty { 0 }
bool m_bPlayerEnabled { false }
PlayerState m_PlayerStateDummy
PlayerStageStats m_PlayerStageStatsDummy
SoundEffectControl m_SoundEffectControl
vector< Steps * > m_vpStepsQueue
The list of Steps a player has to go through in this set.
LifeMeter * m_pLifeMeter
The LifeMeter showing a Player's health.
BitmapText * m_ptextStepsDescription
The description of the current Steps.
ScoreDisplay * m_pPrimaryScoreDisplay
The display for the primary ScoreKeeper.
ScoreDisplay * m_pSecondaryScoreDisplay
The display for the secondary ScoreKeeper.
ScoreKeeper * m_pPrimaryScoreKeeper
The primary ScoreKeeper for keeping track of the score.
ScoreKeeper * m_pSecondaryScoreKeeper
The secondary ScoreKeeper. Only used in PLAY_MODE_RAVE.
BitmapText * m_ptextPlayerOptions
The current PlayerOptions that are activated.
NoteData m_NoteData
The current attack modifiers that are in play for the moment.
Player * m_pPlayer
The specific Player that is going to play.
StepsDisplay * m_pStepsDisplay
AutoActor m_sprOniGameOver
Constructor & Destructor Documentation
PlayerInfo()
PlayerInfo::PlayerInfo ()
~PlayerInfo()
PlayerInfo::~PlayerInfo ()
References m_pLifeMeter, m_pPlayer, m_pPrimaryScoreDisplay, m_pPrimaryScoreKeeper, m_pSecondaryScoreDisplay, m_pSecondaryScoreKeeper, m_pStepsDisplay, m_ptextPlayerOptions, m_ptextStepsDescription, and SAFE_DELETE.
Member Function Documentation
GetName()
RString PlayerInfo::GetName () const inline
Retrieve the name of the Player based on the mode.
Returns
the name of the Player.
References IsMultiPlayer(), m_bIsDummy, m_iDummyIndex, m_mp, m_pn, MultiPlayerToString(), PlayerNumberToString(), and ssprintf().
GetPlayerStageStats()
PlayerStageStats * PlayerInfo::GetPlayerStageStats ()
References GetPlayerStateAndStageStatsIndex(), IsMultiPlayer(), m_bIsDummy, StatsManager::m_CurStageStats, StageStats::m_player, m_PlayerStageStatsDummy, and STATSMAN.
Referenced by Load().
GetPlayerState()
PlayerState * PlayerInfo::GetPlayerState ()
References GAMESTATE, GetPlayerStateAndStageStatsIndex(), IsMultiPlayer(), m_bIsDummy, m_PlayerStateDummy, GameState::m_pMultiPlayerState, and GameState::m_pPlayerState.
Referenced by Load().
GetPlayerStateAndStageStatsIndex()
MultiPlayer PlayerInfo::GetPlayerStateAndStageStatsIndex () inline
Retrieve the player's state and stage stats index.
Returns
the player's state and stage stats index.
References m_mp, m_pn, and PLAYER_INVALID.
Referenced by GetPlayerStageStats(), and GetPlayerState().
GetStepsAndTrailIndex()
PlayerNumber PlayerInfo::GetStepsAndTrailIndex () inline
References m_pn, PLAYER_1, and PLAYER_INVALID.
IsEnabled()
bool PlayerInfo::IsEnabled ()
Determine if the player information is enabled.
Returns
its success or failure.
References FAIL_M, GAMESTATE, GameState::IsMultiPlayerEnabled(), GameState::IsPlayerEnabled(), m_bIsDummy, m_mp, m_pn, MultiPlayer_Invalid, and PLAYER_INVALID.
Referenced by Load(), and LoadDummyP1().
IsMultiPlayer()
bool PlayerInfo::IsMultiPlayer () const inline
Determine if we're in MultiPlayer.
Returns
true if it is MultiPlayer, false otherwise.
References m_mp, and MultiPlayer_Invalid.
Referenced by GetName(), GetPlayerStageStats(), GetPlayerState(), and Load().
Load()
void PlayerInfo::Load (PlayerNumber pn, MultiPlayer mp, bool bShowNoteField, int iAddToDifficulty)
References FAIL_M, GAMESTATE, GetPlayerStageStats(), GetPlayerState(), ScoreDisplay::Init(), IsEnabled(), IsMultiPlayer(), m_bIsDummy, m_bPlayerEnabled, m_iAddToDifficulty, m_mp, m_NoteData, PlayerState::m_PlayerOptions, GameState::m_PlayMode, m_pLifeMeter, m_pn, m_pPlayer, GameState::m_pPlayerState, m_pPrimaryScoreDisplay, m_pPrimaryScoreKeeper, m_pSecondaryScoreDisplay, m_pStepsDisplay, m_ptextPlayerOptions, m_ptextStepsDescription, ScoreKeeper::MakeScoreKeeper(), PLAY_MODE_REGULAR, PLAYER_1, SCORE_KEEPER_CLASS, and ssprintf().
LoadDummyP1()
void PlayerInfo::LoadDummyP1 (int iDummyIndex, int iAddToDifficulty)
References GAMESTATE, IsEnabled(), m_bIsDummy, m_bPlayerEnabled, m_iAddToDifficulty, m_iDummyIndex, m_NoteData, m_PlayerStateDummy, m_pn, m_pPlayer, GameState::m_pPlayerState, and PLAYER_1.
PushSelf()
void PlayerInfo::PushSelf (lua_State * L)
Referenced by LunaScreenGameplay::GetDummyPlayerInfo(), and LunaScreenGameplay::GetPlayerInfo().
ShowOniGameOver()
void PlayerInfo::ShowOniGameOver ()
The player has lost all of their lives: show the special game over.
References m_sprOniGameOver, and Actor::PlayCommand().
Referenced by ScreenGameplay::FailFadeRemovePlayer().
Member Data Documentation
m_bIsDummy
bool PlayerInfo::m_bIsDummy { false }
Referenced by GetName(), GetPlayerStageStats(), GetPlayerState(), IsEnabled(), Load(), and LoadDummyP1().
m_bPlayerEnabled
bool PlayerInfo::m_bPlayerEnabled { false }
Referenced by Load(), and LoadDummyP1().
m_iAddToDifficulty
int PlayerInfo::m_iAddToDifficulty { 0 }
Referenced by Load(), and LoadDummyP1().
m_iDummyIndex
int PlayerInfo::m_iDummyIndex { 0 }
Referenced by GetName(), and LoadDummyP1().
m_mp
MultiPlayer PlayerInfo::m_mp { MultiPlayer_Invalid }
The present Player's multiplayer number.
Referenced by GetName(), GetPlayerStateAndStageStatsIndex(), IsEnabled(), IsMultiPlayer(), and Load().
m_NoteData
NoteData PlayerInfo::m_NoteData
The current attack modifiers that are in play for the moment.
The NoteData the Player has to get through.
Referenced by ScreenGameplay::FailFadeRemovePlayer(), Load(), and LoadDummyP1().
m_PlayerStageStatsDummy
PlayerStageStats PlayerInfo::m_PlayerStageStatsDummy
Referenced by GetPlayerStageStats().
m_PlayerStateDummy
PlayerState PlayerInfo::m_PlayerStateDummy
Referenced by GetPlayerState(), and LoadDummyP1().
m_pLifeMeter
LifeMeter* PlayerInfo::m_pLifeMeter
The LifeMeter showing a Player's health.
Referenced by LunaPlayerInfo::GetLifeMeter(), Load(), and ~PlayerInfo().
m_pn
PlayerNumber PlayerInfo::m_pn
The present Player's number.
Referenced by GetName(), GetPlayerStateAndStageStatsIndex(), GetStepsAndTrailIndex(), IsEnabled(), Load(), and LoadDummyP1().
m_pPlayer
Player* PlayerInfo::m_pPlayer
The specific Player that is going to play.
Referenced by ScreenGameplay::FailFadeRemovePlayer(), ScreenGameplay::Input(), Load(), LoadDummyP1(), and ~PlayerInfo().
m_pPrimaryScoreDisplay
ScoreDisplay* PlayerInfo::m_pPrimaryScoreDisplay
The display for the primary ScoreKeeper.
Referenced by Load(), and ~PlayerInfo().
m_pPrimaryScoreKeeper
ScoreKeeper* PlayerInfo::m_pPrimaryScoreKeeper
The primary ScoreKeeper for keeping track of the score.
Referenced by Load(), and ~PlayerInfo().
m_pSecondaryScoreDisplay
ScoreDisplay* PlayerInfo::m_pSecondaryScoreDisplay
The display for the secondary ScoreKeeper.
Referenced by Load(), and ~PlayerInfo().
m_pSecondaryScoreKeeper
ScoreKeeper* PlayerInfo::m_pSecondaryScoreKeeper
The secondary ScoreKeeper. Only used in PLAY_MODE_RAVE.
Referenced by ~PlayerInfo().
m_pStepsDisplay
StepsDisplay* PlayerInfo::m_pStepsDisplay
Referenced by Load(), and ~PlayerInfo().
m_ptextPlayerOptions
BitmapText* PlayerInfo::m_ptextPlayerOptions
The current PlayerOptions that are activated.
Referenced by Load(), and ~PlayerInfo().
m_ptextStepsDescription
BitmapText* PlayerInfo::m_ptextStepsDescription
The description of the current Steps.
Referenced by Load(), and ~PlayerInfo().
m_SoundEffectControl
SoundEffectControl PlayerInfo::m_SoundEffectControl
m_sprOniGameOver
AutoActor PlayerInfo::m_sprOniGameOver
Referenced by ShowOniGameOver().
m_vpStepsQueue
vector<Steps*> PlayerInfo::m_vpStepsQueue
The list of Steps a player has to go through in this set.
The size may be greater than 1 if playing a course.
Referenced by LunaPlayerInfo::GetStepsQueueWrapped().
The documentation for this class was generated from the following files:
ScreenGameplay.h
ScreenGameplay.cpp