Etterna: PolyphaseFilterCache Namespace Reference
PolyphaseFilterCache Namespace Reference
Utilities for working with the PolyphaseFilter cache.
Typedefs
typedef map< pair< int, float >, PolyphaseFilter * > FilterMap
Functions
const PolyphaseFilter * MakePolyphaseFilter (int iUpFactor, float fCutoffFrequency)
const PolyphaseFilter * FindNearestPolyphaseFilter (int iUpFactor, float fCutoffFrequency)
Variables
static RageMutex PolyphaseFiltersLock ("PolyphaseFiltersLock")
static FilterMap g_mapPolyphaseFilters
Detailed Description
Utilities for working with the PolyphaseFilter cache.
Typedef Documentation
FilterMap
typedef map<pair<int, float>, PolyphaseFilter*> PolyphaseFilterCache::FilterMap
Function Documentation
FindNearestPolyphaseFilter()
const PolyphaseFilter* PolyphaseFilterCache::FindNearestPolyphaseFilter (int iUpFactor, float fCutoffFrequency)
References ASSERT, f, RageMutex::Lock(), PolyphaseFiltersLock, and RageMutex::Unlock().
Referenced by RageSoundResampler_Polyphase::GetFilter().
MakePolyphaseFilter()
const PolyphaseFilter* PolyphaseFilterCache::MakePolyphaseFilter (int iUpFactor, float fCutoffFrequency)
References L, RageMutex::Lock(), PolyphaseFiltersLock, and RageMutex::Unlock().
Referenced by RageSoundResampler_Polyphase::RageSoundResampler_Polyphase().
Variable Documentation
g_mapPolyphaseFilters
FilterMap PolyphaseFilterCache::g_mapPolyphaseFilters static
PolyphaseFiltersLock
RageMutex PolyphaseFilterCache::PolyphaseFiltersLock("PolyphaseFiltersLock") static
Referenced by FindNearestPolyphaseFilter(), and MakePolyphaseFilter().