Etterna: MovieTexture_DShow Class Reference
MovieTexture_DShow Class Reference
#include <MovieTexture_DShow.h>
Public Member Functions
MovieTexture_DShow (RageTextureID ID)
virtual ~MovieTexture_DShow ()
RString Init ()
void Invalidate ()
void Update (float fDeltaTime)
virtual void Reload ()
virtual void Play ()
virtual void Pause ()
virtual void SetPosition (float fSeconds)
virtual void SetPlaybackRate (float fRate)
void SetLooping (bool bLooping=true)
void NewData (const char *pBuffer)
Public Member Functions inherited from RageMovieTexture
RageMovieTexture (const RageTextureID &ID)
~RageMovieTexture () override=default
bool IsAMovie () const override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void DecodeSeconds (float)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Private Member Functions
RString Create ()
void CreateTexture ()
void SkipUpdates ()
void StopSkippingUpdates ()
void CheckFrame ()
RString GetActiveFilterList ()
unsigned GetTexHandle () const
Private Attributes
const char * buffer
RageSemaphore buffer_lock
RageSemaphore buffer_finished
unsigned m_uTexHandle
CComPtr< IGraphBuilder > m_pGB
bool m_bLoop
bool m_bPlaying
Additional Inherited Members
Static Public Member Functions inherited from RageMovieTexture
static RageMovieTexture * Create (const RageTextureID &ID)
static bool GetFourCC (const RString &fn, RString &handler, RString &type)
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
MovieTexture_DShow()
MovieTexture_DShow::MovieTexture_DShow (RageTextureID ID)
References buffer, GetVideoCodecDebugInfo(), LOG, m_bLoop, m_bPlaying, m_uTexHandle, and RageLog::Trace().
~MovieTexture_DShow()
MovieTexture_DShow::~MovieTexture_DShow () virtual
References RageDisplay::DeleteTexture(), DISPLAY, FAILED, RageLog::Flush(), LOG, m_pGB, m_uTexHandle, SkipUpdates(), RageException::Throw(), and RageLog::Trace().
Member Function Documentation
CheckFrame()
void MovieTexture_DShow::CheckFrame () private
References buffer, buffer_finished, CHECKPOINT, CreateSurfaceFrom(), CreateTexture(), DISPLAY, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, m_uTexHandle, RageSemaphore::Post(), and RageDisplay::UpdateTexture().
Referenced by Create(), SkipUpdates(), and Update().
Create()
RString MovieTexture_DShow::Create () private
References CheckFrame(), CHECKPOINT, CreateTexture(), DISPLAY, FAILED, RageTextureID::filename, GetActiveFilterList(), RageTexture::GetID(), RageDisplay::GetMaxTextureSize(), CTextureRenderer::GetVidHeight(), CTextureRenderer::GetVidWidth(), RageTextureID::iAlphaBits, RageTextureID::iMaxSize, L, LOG, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, CTextureRenderer::m_OneFrameDecoded, m_pGB, min(), Pause(), Play(), power_of_two(), PrintCodecError(), RStringToWstring(), CTextureRenderer::SetRenderTarget(), RageException::Throw(), RageLog::Trace(), and RageSemaphore::Wait().
Referenced by Init().
CreateTexture()
void MovieTexture_DShow::CreateTexture () private
References RageDisplay::RagePixelFormatDesc::bpp, CreateSurface(), RageDisplay::CreateTexture(), DISPLAY, FAIL_M, RageDisplay::GetPixelFormatDesc(), RageTextureManager::GetPrefs(), RageTextureManagerPrefs::m_iMovieColorDepth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_uTexHandle, RageDisplay::RagePixelFormatDesc::masks, RagePixelFormat_RGB5, RagePixelFormat_RGB8, RagePixelFormat_RGBA4, RagePixelFormat_RGBA8, ssprintf(), RageDisplay::SupportsTextureFormat(), and TEXTUREMAN.
Referenced by CheckFrame(), and Create().
GetActiveFilterList()
RString MovieTexture_DShow::GetActiveFilterList () private
References FAILED, m_pGB, and WStringToRString().
Referenced by Create().
GetTexHandle()
unsigned MovieTexture_DShow::GetTexHandle () const inline private virtual
Implements RageTexture.
References m_uTexHandle.
Init()
RString MovieTexture_DShow::Init ()
References Create(), RageTexture::CreateFrameRects(), RageTexture::m_TextureCoordRects, and swap().
Referenced by RageMovieTextureDriver_DShow::Create().
Invalidate()
void MovieTexture_DShow::Invalidate () inline virtual
Reimplemented from RageTexture.
References m_uTexHandle.
NewData()
void MovieTexture_DShow::NewData (const char * pBuffer)
References ASSERT, buffer, buffer_finished, buffer_lock, RageSemaphore::Post(), RageSemaphore::TryWait(), and RageSemaphore::Wait().
Pause()
void MovieTexture_DShow::Pause () virtual
References FAILED, m_pGB, SkipUpdates(), StopSkippingUpdates(), and RageException::Throw().
Referenced by Create(), and SetPlaybackRate().
Play()
void MovieTexture_DShow::Play () virtual
References FAILED, LOG, m_bPlaying, m_pGB, SkipUpdates(), StopSkippingUpdates(), RageException::Throw(), and RageLog::Trace().
Referenced by Create().
Reload()
void MovieTexture_DShow::Reload () virtual
Implements RageMovieTexture.
SetLooping()
void MovieTexture_DShow::SetLooping (bool bLooping = true) inline virtual
Reimplemented from RageMovieTexture.
References m_bLoop.
SetPlaybackRate()
void MovieTexture_DShow::SetPlaybackRate (float fRate) virtual
Implements RageMovieTexture.
References FAILED, m_pGB, Pause(), SkipUpdates(), and StopSkippingUpdates().
SetPosition()
void MovieTexture_DShow::SetPosition (float fSeconds) virtual
Implements RageMovieTexture.
References m_pGB, SkipUpdates(), and StopSkippingUpdates().
Referenced by Update().
SkipUpdates()
void MovieTexture_DShow::SkipUpdates () private
References buffer_lock, CheckFrame(), and RageSemaphore::TryWait().
Referenced by Pause(), Play(), SetPlaybackRate(), SetPosition(), and ~MovieTexture_DShow().
StopSkippingUpdates()
void MovieTexture_DShow::StopSkippingUpdates () private
References buffer_lock, and RageSemaphore::Post().
Referenced by Pause(), Play(), SetPlaybackRate(), and SetPosition().
Update()
void MovieTexture_DShow::Update (float fDeltaTime) virtual
Reimplemented from RageMovieTexture.
References CheckFrame(), CHECKPOINT, m_bLoop, m_pGB, and SetPosition().
Member Data Documentation
buffer
const char* MovieTexture_DShow::buffer private
Referenced by CheckFrame(), MovieTexture_DShow(), and NewData().
buffer_finished
RageSemaphore MovieTexture_DShow::buffer_finished private
Referenced by CheckFrame(), and NewData().
buffer_lock
RageSemaphore MovieTexture_DShow::buffer_lock private
Referenced by NewData(), SkipUpdates(), and StopSkippingUpdates().
m_bLoop
bool MovieTexture_DShow::m_bLoop private
Referenced by MovieTexture_DShow(), SetLooping(), and Update().
m_bPlaying
bool MovieTexture_DShow::m_bPlaying private
Referenced by MovieTexture_DShow(), and Play().
m_pGB
CComPtr<IGraphBuilder> MovieTexture_DShow::m_pGB private
Referenced by Create(), GetActiveFilterList(), Pause(), Play(), SetPlaybackRate(), SetPosition(), Update(), and ~MovieTexture_DShow().
m_uTexHandle
unsigned MovieTexture_DShow::m_uTexHandle private
Referenced by CheckFrame(), CreateTexture(), GetTexHandle(), Invalidate(), MovieTexture_DShow(), and ~MovieTexture_DShow().
The documentation for this class was generated from the following files:
MovieTexture_DShow.h
MovieTexture_DShow.cpp