Etterna: StringConversion Namespace Reference
StringConversion Namespace Reference
Utilities for converting the RStrings.
Functions
template<>
RString ToString< StepsType > (const StepsType &value)
template<>
bool FromString< TapNoteScore > (const RString &value, TapNoteScore &out)
template<>
bool FromString< int > (const RString &sValue, int &out)
template<>
bool FromString< unsigned > (const RString &sValue, unsigned &out)
template<>
bool FromString< float > (const RString &sValue, float &out)
template<>
bool FromString< bool > (const RString &sValue, bool &out)
template<>
RString ToString< int > (const int &value)
template<>
RString ToString< unsigned > (const unsigned &value)
template<>
RString ToString< float > (const float &value)
template<>
RString ToString< bool > (const bool &value)
template<typename T >
bool FromString (const RString &sValue, T &out)
template<typename T >
RString ToString (const T &value)
template<>
bool FromString< RString > (const RString &sValue, RString &out)
template<>
RString ToString< RString > (const RString &value)
Detailed Description
Utilities for converting the RStrings.
Function Documentation
FromString()
template<typename T > bool StringConversion::FromString (const RString & sValue, T & out)
Referenced by PlayerOptions::FromOneModString(), Model::LoadMaterialsFromMilkshapeAscii(), MoveMap(), MovePref(), and MovePref< bool >().
FromString< bool >()
template<> bool StringConversion::FromString< bool > (const RString & sValue, bool & out)
References StringToInt().
FromString< float >()
template<> bool StringConversion::FromString< float > (const RString & sValue, float & out)
FromString< int >()
template<> bool StringConversion::FromString< int > (const RString & sValue, int & out)
FromString< RString >()
template<> bool StringConversion::FromString< RString > (const RString & sValue, RString & out) inline
FromString< TapNoteScore >()
template<> bool StringConversion::FromString< TapNoteScore > (const RString & value, TapNoteScore & out)
References StringToTapNoteScore(), and TapNoteScore_Invalid.
FromString< unsigned >()
template<> bool StringConversion::FromString< unsigned > (const RString & sValue, unsigned & out)
ToString()
template<typename T > RString StringConversion::ToString (const T & value)
Referenced by Profile::ImportScoresToEtterna(), ScreenHowToPlay::Init(), MoveMap(), MovePref(), Serialize(), SetTimingDifficulty(), TimingData::ToVectorString(), and NotesWriterJson::WriteSong().
ToString< bool >()
template<> RString StringConversion::ToString< bool > (const bool & value)
References ssprintf().
Referenced by MovePref< bool >().
ToString< float >()
template<> RString StringConversion::ToString< float > (const float & value)
References ssprintf().
ToString< int >()
template<> RString StringConversion::ToString< int > (const int & value)
References ssprintf().
ToString< RString >()
template<> RString StringConversion::ToString< RString > (const RString & value) inline
ToString< StepsType >()
template<> RString StringConversion::ToString< StepsType > (const StepsType & value)
References StepsTypeToString().
ToString< unsigned >()
template<> RString StringConversion::ToString< unsigned > (const unsigned & value)
References ssprintf().