Etterna: SMOProtocol Class Reference
SMOProtocol Class Reference
#include <NetworkSyncManager.h>
Public Member Functions
SMOProtocol ()
~SMOProtocol ()
bool Connect (NetworkSyncManager *n, unsigned short port, RString address) override
void close () override
void Update (NetworkSyncManager *n, float fDeltaTime) override
void SelectUserSong (NetworkSyncManager *n, Song *song) override
void CreateNewRoom (RString name, RString desc, RString password) override
void EnterRoom (RString name, RString password) override
void RequestRoomInfo (RString name) override
void ReportPlayerOptions ()
void SendChat (const RString &message, string tab, int type) override
void ReportNSSOnOff (int i) override
void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset, int numNotes) override
void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset) override
void ReportSongOver (NetworkSyncManager *n) override
void ReportStyle (NetworkSyncManager *n) override
void StartRequest (NetworkSyncManager *n, short position) override
void ProcessInput (NetworkSyncManager *n)
void Login (RString user, RString pass) override
void OnMusicSelect () override
void OffMusicSelect () override
void OnRoomSelect () override
void OffRoomSelect () override
void OnOptions () override
void OffOptions () override
void OnEval () override
void OffEval () override
Public Member Functions inherited from NetProtocol
virtual void LeaveRoom (NetworkSyncManager *n)
virtual void ReportHighScore (HighScore *hs, PlayerStageStats &pss)
virtual void Logout ()
Static Public Member Functions
static void DealWithSMOnlinePack (PacketFunctions &SMOnlinePacket, ScreenNetSelectMusic *s)
static void DealWithSMOnlinePack (PacketFunctions &SMOnlinePacket, ScreenNetRoom *s)
static int DealWithSMOnlinePack (PacketFunctions &SMOnlinePacket, ScreenSMOnlineLogin *s, RString &response)
Public Attributes
PacketFunctions SMOnlinePacket
Public Attributes inherited from NetProtocol
RString serverName
int serverVersion { 0 }
Private Member Functions
bool TryConnect (unsigned short port, RString address)
void SendSMOnline ()
Private Attributes
EzSockets * NetPlayerClient
EzSockets * BroadcastReception
PacketFunctions m_packet
int m_iSalt
Constructor & Destructor Documentation
SMOProtocol()
SMOProtocol::SMOProtocol ()
References EzSockets::bind(), EzSockets::blocking, BroadcastReception, EzSockets::create(), and NetPlayerClient.
~SMOProtocol()
SMOProtocol::~SMOProtocol ()
References BroadcastReception, EzSockets::close(), NetPlayerClient, and SAFE_DELETE.
Member Function Documentation
close()
void SMOProtocol::close () override virtual
Reimplemented from NetProtocol.
References EzSockets::close(), NetPlayerClient, NetProtocol::serverName, and NetProtocol::serverVersion.
Referenced by NetworkSyncManager::CloseConnection().
Connect()
bool SMOProtocol::Connect (NetworkSyncManager * n, unsigned short port, RString address) override virtual
Reimplemented from NetProtocol.
References EzSockets::blocking, EzSockets::CanConnect(), PacketFunctions::ClearPacket(), CONNECTION_SUCCESSFUL, PacketFunctions::Data, LocalizedString::GetValue(), NetworkSyncManager::isSMOnline, LOG, m_iSalt, m_packet, NetworkSyncManager::m_startupStatus, NETMAXBUFFERSIZE, NetPlayerClient, NETPROTOCOLVERSION, NSCHello, NSServerOffset, PacketFunctions::Position, PRODUCT_FAMILY, product_version, PacketFunctions::Read1(), PacketFunctions::Read4(), PacketFunctions::ReadNT(), EzSockets::ReadPack(), SCREENMAN, EzSockets::SendPack(), NetProtocol::serverName, NetProtocol::serverVersion, ssprintf(), ScreenManager::SystemMessage(), TryConnect(), RageLog::Warn(), PacketFunctions::Write1(), and PacketFunctions::WriteNT().
Referenced by NetworkSyncManager::PostStartUp().
CreateNewRoom()
void SMOProtocol::CreateNewRoom (RString name, RString desc, RString password) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), SendSMOnline(), SMOnlinePacket, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
DealWithSMOnlinePack() [1/3]
void SMOProtocol::DealWithSMOnlinePack (PacketFunctions & SMOnlinePacket, ScreenNetSelectMusic * s) static
References ThemeManager::GetMetric(), PacketFunctions::Read1(), PacketFunctions::ReadNT(), SCREENMAN, ScreenManager::SetNewScreen(), and THEME.
Referenced by ScreenSMOnlineLogin::HandleScreenMessage(), ScreenNetRoom::HandleScreenMessage(), and ScreenNetSelectMusic::HandleScreenMessage().
DealWithSMOnlinePack() [2/3]
void SMOProtocol::DealWithSMOnlinePack (PacketFunctions & SMOnlinePacket, ScreenNetRoom * s) static
References MessageManager::Broadcast(), ThemeManager::GetMetric(), ScreenNetRoom::m_roomInfo, NetworkSyncManager::m_Rooms, RoomInfo::maxPlayers, Message_UpdateScreenHeader, MessageIDToString(), MESSAGEMAN, RoomInfo::numPlayers, RoomInfo::players, PacketFunctions::Read1(), PacketFunctions::ReadNT(), SCREENMAN, RoomData::SetDescription(), RoomData::SetName(), ScreenManager::SetNewScreen(), Message::SetParam(), RoomInfoDisplay::SetRoomInfo(), RoomInfo::songArtist, RoomInfo::songSubTitle, RoomInfo::songTitle, THEME, and ScreenNetRoom::UpdateRoomsList().
DealWithSMOnlinePack() [3/3]
int SMOProtocol::DealWithSMOnlinePack (PacketFunctions & SMOnlinePacket, ScreenSMOnlineLogin * s, RString & response) static
References ThemeManager::GetMetric(), NetworkSyncManager::loggedIn, PacketFunctions::Read1(), PacketFunctions::ReadNT(), SCREENMAN, ScreenManager::SetNewScreen(), and THEME.
EnterRoom()
void SMOProtocol::EnterRoom (RString name, RString password) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), SendSMOnline(), SMOnlinePacket, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
Login()
void SMOProtocol::Login (RString user, RString pass) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), m_iSalt, NetworkSyncManager::MD5Hex(), SendSMOnline(), SMOnlinePacket, ssprintf(), PacketFunctions::Write1(), and PacketFunctions::WriteNT().
OffEval()
void SMOProtocol::OffEval () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
OffMusicSelect()
void SMOProtocol::OffMusicSelect () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
OffOptions()
void SMOProtocol::OffOptions () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff(), and ReportPlayerOptions().
OffRoomSelect()
void SMOProtocol::OffRoomSelect () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
OnEval()
void SMOProtocol::OnEval () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
OnMusicSelect()
void SMOProtocol::OnMusicSelect () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff(), and ReportPlayerOptions().
OnOptions()
void SMOProtocol::OnOptions () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
OnRoomSelect()
void SMOProtocol::OnRoomSelect () override virtual
Reimplemented from NetProtocol.
References ReportNSSOnOff().
ProcessInput()
void SMOProtocol::ProcessInput (NetworkSyncManager * n)
References MessageManager::Broadcast(), PacketFunctions::ClearPacket(), EzSockets::close(), CONNECTION_DROPPED, PacketFunctions::Data, NetworkSyncManager::fl_PlayerNames, NetworkSyncManager::fl_PlayerStates, FLU, GameManager::GameAndStringToStyle(), GAMEMAN, GAMESTATE, GradeToLocalizedString(), EzSockets::IsError(), GameState::IsPlayerEnabled(), NetworkSyncManager::isSMOnline, LOG, NetworkSyncManager::loggedIn, NetworkSyncManager::m_ActivePlayer, NetworkSyncManager::m_ActivePlayers, NetworkSyncManager::m_EvalPlayerData, NetworkSyncManager::m_iSelectMode, m_packet, GameState::m_pCurGame, NetworkSyncManager::m_PlayerNames, NetworkSyncManager::m_PlayerStatus, NetworkSyncManager::m_sArtist, NetworkSyncManager::m_sChatText, NetworkSyncManager::m_Scoreboard, NetworkSyncManager::m_scoreboardchange, NetworkSyncManager::m_sFileHash, NetworkSyncManager::m_sMainTitle, NetworkSyncManager::m_sSubTitle, MESSAGEMAN, NETMAXBUFFERSIZE, NETNUMTAPSCORES, NetPlayerClient, NSCAttack, NSCCM, NSCGON, NSCGSR, NSCGSU, NSCHello, NSCPing, NSCPingR, NSCRSG, NSCSMOnline, NSCSMS, NSCSU, NSCUUL, NSSB_COMBO, NSSB_GRADE, NSSB_NAMES, NSServerOffset, PLAYER_INVALID, PacketFunctions::Position, PacketFunctions::Read1(), PacketFunctions::Read2(), PacketFunctions::Read4(), PacketFunctions::ReadNT(), EzSockets::ReadPack(), StdString::CStdStr< CT >::Right(), SCREENMAN, ScreenManager::SendMessageToTopScreen(), EzSockets::SendPack(), NetProtocol::serverVersion, GameState::SetCurGame(), GameState::SetCurrentStyle(), ScreenManager::SetNewScreen(), PacketFunctions::size, EzSockets::skCONNECTED, SMOnlinePacket, ssprintf(), EzSockets::state, GameManager::StringToGame(), ScreenManager::SystemMessage(), ScreenManager::SystemMessageNoAnimate(), RageLog::Trace(), EzSockets::update(), NetworkSyncManager::useSMserver, and PacketFunctions::Write1().
Referenced by Update().
ReportNSSOnOff()
void SMOProtocol::ReportNSSOnOff (int i) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, m_packet, NetPlayerClient, NSCSMS, PacketFunctions::Position, EzSockets::SendPack(), and PacketFunctions::Write1().
Referenced by OffEval(), OffMusicSelect(), OffOptions(), OffRoomSelect(), OnEval(), OnMusicSelect(), OnOptions(), and OnRoomSelect().
ReportPlayerOptions()
void SMOProtocol::ReportPlayerOptions ()
References PacketFunctions::ClearPacket(), PacketFunctions::Data, GAMESTATE, ModsGroup< T >::GetCurrent(), PlayerOptions::GetString(), m_packet, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, NetPlayerClient, NSCUPOpts, PLAYER_1, PacketFunctions::Position, EzSockets::SendPack(), PacketFunctions::Write1(), and PacketFunctions::WriteNT().
Referenced by OffOptions(), and OnMusicSelect().
ReportScore() [1/2]
void SMOProtocol::ReportScore (NetworkSyncManager * n, int playerID, int step, int score, int combo, float offset, int numNotes) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, f, PlayerStageStats::GetGrade(), LOG, PlayerStageStats::m_bFailed, StatsManager::m_CurStageStats, m_packet, StageStats::m_player, NetworkSyncManager::m_playerLife, NetPlayerClient, NSCGSU, PacketFunctions::Position, EzSockets::SendPack(), SMOST_HITMINE, SMOST_W1, STATSMAN, RageLog::Trace(), NetworkSyncManager::TranslateStepType(), NetworkSyncManager::useSMserver, PacketFunctions::Write1(), PacketFunctions::Write2(), and PacketFunctions::Write4().
ReportScore() [2/2]
void SMOProtocol::ReportScore (NetworkSyncManager * n, int playerID, int step, int score, int combo, float offset) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, f, PlayerStageStats::GetGrade(), LOG, PlayerStageStats::m_bFailed, StatsManager::m_CurStageStats, m_packet, StageStats::m_player, NetworkSyncManager::m_playerLife, NetPlayerClient, NSCGSU, PacketFunctions::Position, EzSockets::SendPack(), SMOST_HITMINE, SMOST_W1, STATSMAN, RageLog::Trace(), NetworkSyncManager::TranslateStepType(), NetworkSyncManager::useSMserver, PacketFunctions::Write1(), PacketFunctions::Write2(), and PacketFunctions::Write4().
ReportSongOver()
void SMOProtocol::ReportSongOver (NetworkSyncManager * n) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, m_packet, NetPlayerClient, NSCGON, PacketFunctions::Position, EzSockets::SendPack(), NetworkSyncManager::useSMserver, and PacketFunctions::Write1().
ReportStyle()
void SMOProtocol::ReportStyle (NetworkSyncManager * n) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, GAMESTATE, GameState::GetNumPlayersEnabled(), GameState::GetPlayerDisplayName(), LOG, m_packet, NetPlayerClient, NSCSU, PLAYER_1, PacketFunctions::Position, EzSockets::SendPack(), RageLog::Trace(), NetworkSyncManager::useSMserver, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
RequestRoomInfo()
void SMOProtocol::RequestRoomInfo (RString name) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), SendSMOnline(), SMOnlinePacket, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
SelectUserSong()
void SMOProtocol::SelectUserSong (NetworkSyncManager * n, Song * song) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, GAMESTATE, Song::GetFileHash(), NetworkSyncManager::m_iSelectMode, m_packet, GameState::m_pCurSong, NetworkSyncManager::m_sArtist, NetworkSyncManager::m_sMainTitle, NetworkSyncManager::m_sSubTitle, NetPlayerClient, NSCRSG, PacketFunctions::Position, EzSockets::SendPack(), NetProtocol::serverVersion, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
SendChat()
void SMOProtocol::SendChat (const RString & message, string tab, int type) override virtual
Reimplemented from NetProtocol.
References PacketFunctions::ClearPacket(), PacketFunctions::Data, m_packet, NetPlayerClient, NSCCM, PacketFunctions::Position, EzSockets::SendPack(), PacketFunctions::Write1(), and PacketFunctions::WriteNT().
SendSMOnline()
void SMOProtocol::SendSMOnline () private
References PacketFunctions::Data, m_packet, NetPlayerClient, NSCSMOnline, PacketFunctions::Position, EzSockets::SendPack(), and SMOnlinePacket.
Referenced by CreateNewRoom(), EnterRoom(), Login(), and RequestRoomInfo().
StartRequest()
void SMOProtocol::StartRequest (NetworkSyncManager * n, short position) override virtual
Reimplemented from NetProtocol.
References EzSockets::blocking, PacketFunctions::ClearPacket(), PacketFunctions::Data, FOREACH_PlayerNumber, GAMESTATE, Steps::GetChartKey(), ModsGroup< T >::GetCurrent(), Steps::GetDifficulty(), Song::GetFileHash(), Steps::GetMeter(), SongOptions::GetString(), PlayerOptions::GetString(), GameState::IsPlayerEnabled(), LOG, GameState::m_bDemonstrationOrJukebox, SongOptions::m_fMusicRate, m_packet, GameState::m_pCurSong, GameState::m_pCurSteps, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, Song::m_sArtist, Song::m_sMainTitle, GameState::m_SongOptions, Song::m_sSubTitle, NETMAXBUFFERSIZE, NetPlayerClient, NSCGSR, NSServerOffset, PLAYER_1, PLAYER_2, PacketFunctions::Position, PacketFunctions::Read1(), EzSockets::ReadPack(), EzSockets::SendPack(), NetProtocol::serverVersion, RageLog::Trace(), NetworkSyncManager::useSMserver, PacketFunctions::Write1(), and PacketFunctions::WriteNT().
TryConnect()
bool SMOProtocol::TryConnect (unsigned short port, RString address) private
References EzSockets::connect(), EzSockets::create(), and NetPlayerClient.
Referenced by Connect().
Update()
void SMOProtocol::Update (NetworkSyncManager * n, float fDeltaTime) override virtual
Reimplemented from NetProtocol.
References NetServerInfo::Address, BroadcastReception, PacketFunctions::Data, EzSockets::fromAddr, EzSockets::LongFromAddrIn(), NetworkSyncManager::m_vAllLANServers, NetServerInfo::Name, PacketFunctions::Position, ProcessInput(), PacketFunctions::Read1(), PacketFunctions::Read2(), PacketFunctions::ReadNT(), EzSockets::ReadPack(), ssprintf(), and NetworkSyncManager::useSMserver.
Member Data Documentation
BroadcastReception
EzSockets* SMOProtocol::BroadcastReception private
Referenced by SMOProtocol(), Update(), and ~SMOProtocol().
m_iSalt
int SMOProtocol::m_iSalt private
Referenced by Connect(), and Login().
m_packet
PacketFunctions SMOProtocol::m_packet private
Referenced by Connect(), ProcessInput(), ReportNSSOnOff(), ReportPlayerOptions(), ReportScore(), ReportSongOver(), ReportStyle(), SelectUserSong(), SendChat(), SendSMOnline(), and StartRequest().
NetPlayerClient
EzSockets* SMOProtocol::NetPlayerClient private
Referenced by close(), Connect(), ProcessInput(), ReportNSSOnOff(), ReportPlayerOptions(), ReportScore(), ReportSongOver(), ReportStyle(), SelectUserSong(), SendChat(), SendSMOnline(), SMOProtocol(), StartRequest(), TryConnect(), and ~SMOProtocol().
SMOnlinePacket
PacketFunctions SMOProtocol::SMOnlinePacket
Referenced by CreateNewRoom(), EnterRoom(), Login(), ProcessInput(), RequestRoomInfo(), and SendSMOnline().
The documentation for this class was generated from the following files:
NetworkSyncManager.h
NetworkSyncManager.cpp