Etterna: LunaRageQuadratic Struct Reference
LunaRageQuadratic Struct Reference
Public Member Functions
LunaRageQuadratic ()
Public Member Functions inherited from Luna< RageQuadratic >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int evaluate (T *p, lua_State *L)
static int get_bezier (T *p, lua_State *L)
static int get_bezier_end (T *p, lua_State *L)
static int get_bezier_start (T *p, lua_State *L)
static int get_slope (T *p, lua_State *L)
static int set_from_bezier (T *p, lua_State *L)
static int set_from_cubic (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageQuadratic >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageQuadratic >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageQuadratic >
using T = RageQuadratic
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageQuadratic >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaRageQuadratic()
LunaRageQuadratic::LunaRageQuadratic () inline
References ADD_METHOD, evaluate(), get_bezier(), get_bezier_end(), get_bezier_start(), get_slope(), set_from_bezier(), and set_from_cubic().
Member Function Documentation
evaluate()
static int LunaRageQuadratic::evaluate (T * p, lua_State * L) inline static
References RageQuadratic::Evaluate(), and FArg.
Referenced by LunaRageQuadratic().
get_bezier()
static int LunaRageQuadratic::get_bezier (T * p, lua_State * L) inline static
References RageQuadratic::GetBezier().
Referenced by LunaRageQuadratic().
get_bezier_end()
static int LunaRageQuadratic::get_bezier_end (T * p, lua_State * L) inline static
References RageQuadratic::GetBezierEnd().
Referenced by LunaRageQuadratic().
get_bezier_start()
static int LunaRageQuadratic::get_bezier_start (T * p, lua_State * L) inline static
References RageQuadratic::GetBezierStart().
Referenced by LunaRageQuadratic().
get_slope()
static int LunaRageQuadratic::get_slope (T * p, lua_State * L) inline static
References FArg, and RageQuadratic::GetSlope().
Referenced by LunaRageQuadratic().
set_from_bezier()
static int LunaRageQuadratic::set_from_bezier (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and RageQuadratic::SetFromBezier().
Referenced by LunaRageQuadratic().
set_from_cubic()
static int LunaRageQuadratic::set_from_cubic (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and RageQuadratic::SetFromCubic().
Referenced by LunaRageQuadratic().
The documentation for this struct was generated from the following file:
RageMath.cpp