Etterna: ScreenGameplaySyncMachine.cpp File Reference
ScreenGameplaySyncMachine.cpp File Reference
#include "ScreenGameplaySyncMachine.h"
#include "AdjustSync.h"
#include "GameManager.h"
#include "GamePreferences.h"
#include "GameState.h"
#include "InputEventPlus.h"
#include "NetworkSyncManager.h"
#include "NotesLoaderSM.h"
#include "NotesLoaderSSC.h"
#include "PrefsManager.h"
#include "ScreenDimensions.h"
#include "SongUtil.h"
#include "global.h"
Functions
REGISTER_SCREEN_CLASS (ScreenGameplaySyncMachine)
Variables
static LocalizedString OLD_OFFSET ("ScreenGameplaySyncMachine", "Old offset")
static LocalizedString NEW_OFFSET ("ScreenGameplaySyncMachine", "New offset")
static LocalizedString COLLECTING_SAMPLE ("ScreenGameplaySyncMachine", "Collecting sample")
static LocalizedString STANDARD_DEVIATION ("ScreenGameplaySyncMachine", "Standard deviation")
Function Documentation
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenGameplaySyncMachine)
Variable Documentation
COLLECTING_SAMPLE
LocalizedString COLLECTING_SAMPLE("ScreenGameplaySyncMachine", "Collecting sample") static
Referenced by ScreenGameplaySyncMachine::RefreshText().
NEW_OFFSET
LocalizedString NEW_OFFSET("ScreenGameplaySyncMachine", "New offset") static
Referenced by ScreenGameplaySyncMachine::RefreshText().
OLD_OFFSET
LocalizedString OLD_OFFSET("ScreenGameplaySyncMachine", "Old offset") static
Referenced by ScreenGameplaySyncMachine::RefreshText().
STANDARD_DEVIATION
LocalizedString STANDARD_DEVIATION("ScreenGameplaySyncMachine", "Standard deviation") static
Referenced by ScreenGameplaySyncMachine::RefreshText().