Etterna: Profile Class Reference
Profile Class Reference
Player data that persists between sessions.
#include <Profile.h>
Classes
struct HighScoresForASong
struct HighScoresForASteps
Public Member Functions
Profile ()
Set up the Profile with default values.
RString GetDisplayNameOrHighScoreName () const
Character * GetCharacter () const
void SetCharacter (const RString &sCharacterID)
int GetTotalNumSongsPassed () const
int GetTotalStepsWithTopGrade (StepsType st, Difficulty d, Grade g) const
float GetSongsPossible (StepsType st, Difficulty dc) const
float GetSongsActual (StepsType st, Difficulty dc) const
float GetSongsPercentComplete (StepsType st, Difficulty dc) const
float GetSongsAndCoursesPercentCompleteAllDifficulties (StepsType st) const
bool GetDefaultModifiers (const Game *pGameType, RString &sModifiersOut) const
void SetDefaultModifiers (const Game *pGameType, const RString &sModifiers)
Song * GetMostPopularSong () const
void AddStepTotals (int iNumTapsAndHolds, int iNumJumps, int iNumHolds, int iNumRolls, int iNumMines, int iNumHands, int iNumLifts)
RString * GetGuid ()
void AddToFavorites (const string &ck)
void AddToPermaMirror (const string &ck)
void RemoveFromFavorites (const string &ck)
void RemoveFromPermaMirror (const string &ck)
void AddGoal (const string &ck)
void RemoveGoal (const string &ck, DateTime assigned)
void FillGoalTable ()
bool HasGoal (const string &ck)
ScoreGoal & GetLowestGoalForRate (const string &ck, float rate)
void SetAnyAchievedGoals (const string &ck, float &rate, const HighScore &pscore)
void AddStepsHighScore (const Song *pSong, const Steps *pSteps, HighScore hs, int &iIndexOut)
const HighScoreList & GetStepsHighScoreList (const Song *pSong, const Steps *pSteps) const
HighScoreList & GetStepsHighScoreList (const Song *pSong, const Steps *pSteps)
int GetStepsNumTimesPlayed (const Song *pSong, const Steps *pSteps) const
void IncrementStepsPlayCount (const Song *pSong, const Steps *pSteps)
Grade GetBestGrade (const Song *pSong, StepsType st) const
void GetGrades (const Song *pSong, StepsType st, int iCounts[NUM_Grade]) const
int GetSongNumTimesPlayed (const Song *pSong) const
int GetSongNumTimesPlayed (const SongID &songID) const
DateTime GetSongLastPlayedDateTime (const Song *pSong) const
bool HasPassedSteps (const Song *pSong, const Steps *pSteps) const
bool HasPassedAnyStepsInSong (const Song *pSong) const
void GetAllUsedHighScoreNames (std::set< RString > &names)
void MergeScoresFromOtherProfile (Profile *other, bool skip_totals, RString const &from_dir, RString const &to_dir)
void AddCategoryHighScore (StepsType st, RankingCategory rc, HighScore hs, int &iIndexOut)
HighScoreList & GetCategoryHighScoreList (StepsType st, RankingCategory rc)
const HighScoreList & GetCategoryHighScoreList (StepsType st, RankingCategory rc) const
int GetCategoryNumTimesPlayed (StepsType st) const
void IncrementCategoryPlayCount (StepsType st, RankingCategory rc)
void AddScreenshot (const Screenshot &screenshot)
int GetNextScreenshotIndex ()
void InitAll ()
void InitEditableData ()
void InitGeneralData ()
void InitSongScores ()
void InitCategoryScores ()
void InitScreenshotData ()
void ClearStats ()
void swap (Profile &other)
void HandleStatsPrefixChange (RString dir, bool require_signature)
ProfileLoadResult LoadAllFromDir (const RString &sDir, bool bRequireSignature, LoadingWindow *ld)
ProfileLoadResult LoadStatsFromDir (RString dir, bool require_signature)
void LoadTypeFromDir (const RString &dir)
void LoadCustomFunction (const RString &sDir)
bool SaveAllToDir (const RString &sDir, bool bSignData) const
ProfileLoadResult LoadEditableDataFromDir (const RString &sDir)
void ImportScoresToEtterna ()
void SaveTypeToDir (const RString &dir) const
void SaveEditableDataToDir (const RString &sDir) const
void CalculateStatsFromScores (LoadingWindow *ld)
void CalculateStatsFromScores ()
void SaveStatsWebPageToDir (const RString &sDir) const
void SaveMachinePublicKeyToDir (const RString &sDir) const
void PushSelf (lua_State *L)
Static Public Member Functions
static RString MakeGuid ()
static void MoveBackupToDir (const RString &sFromDir, const RString &sToDir)
static RString MakeUniqueFileNameNoExtension (const RString &sDir, const RString &sFileNameBeginning)
static RString MakeFileNameNoExtension (const RString &sFileNameBeginning, int iIndex)
Public Attributes
ProfileType m_Type { ProfileType_Normal }
int m_ListPriority { 0 }
map< string, Playlist > allplaylists
RString m_sDisplayName
RString m_sCharacterID
RString m_sProfileID
RString m_sLastUsedHighScoreName
The last used name for high scoring purposes.
RString m_sGuid
map< RString, RString > m_sDefaultModifiers
SortOrder m_SortOrder { SortOrder_Invalid }
Difficulty m_LastDifficulty { Difficulty_Invalid }
StepsType m_LastStepsType { StepsType_Invalid }
SongID m_lastSong
int m_iCurrentCombo { 0 }
int m_iTotalSessions { 0 }
int m_iTotalSessionSeconds { 0 }
int m_iTotalGameplaySeconds { 0 }
int m_iTotalDancePoints { 0 }
int m_iNumExtraStagesPassed { 0 }
int m_iNumExtraStagesFailed { 0 }
int m_iNumToasties { 0 }
int m_iTotalTapsAndHolds { 0 }
int m_iTotalJumps { 0 }
int m_iTotalHolds { 0 }
int m_iTotalRolls { 0 }
int m_iTotalMines { 0 }
int m_iTotalHands { 0 }
int m_iTotalLifts { 0 }
float m_fPlayerRating
float m_fPlayerSkillsets [NUM_Skillset]
bool m_bNewProfile { false }
Is this a brand new profile?
string profiledir
bool IsEtternaProfile { false }
RString m_sLastPlayedMachineGuid
Which machine did we play on last, based on the Guid?
DateTime m_LastPlayedDate
int m_iNumSongsPlayedByPlayMode [NUM_PlayMode]
map< StyleID, int > m_iNumSongsPlayedByStyle
int m_iNumSongsPlayedByDifficulty [NUM_Difficulty]
int m_iNumSongsPlayedByMeter [MAX_METER+1]
int m_iNumTotalSongsPlayed { 0 }
Count the total number of songs played.
int m_iNumStagesPassedByPlayMode [NUM_PlayMode]
int m_iNumStagesPassedByGrade [NUM_Grade]
set< string > FavoritedCharts
set< string > PermaMirrorCharts
unordered_map< string, GoalsForChart > goalmap
vector< ScoreGoal * > goaltable
int sortmode = 1
int filtermode = 1
bool asc = false
LuaTable m_UserTable
std::map< SongID, HighScoresForASong > m_SongHighScores
HighScoreList m_CategoryHighScores [NUM_StepsType][NUM_RankingCategory]
vector< Screenshot > m_vScreenshots
Private Member Functions
const HighScoresForASong * GetHighScoresForASong (const SongID &songID) const
Private Attributes
XMLProfile XMLProf
DBProfile DBProf
Detailed Description
Player data that persists between sessions.
This can be stored on a local disk or on a memory card.
Constructor & Destructor Documentation
Profile()
Profile::Profile () inline
Set up the Profile with default values.
Note: there are probably a lot of variables.
References FOREACH_ENUM, DateTime::Init(), HighScoreList::Init(), m_CategoryHighScores, m_iNumSongsPlayedByDifficulty, m_iNumSongsPlayedByMeter, m_iNumSongsPlayedByPlayMode, m_iNumStagesPassedByGrade, m_iNumStagesPassedByPlayMode, m_LastPlayedDate, m_lastSong, m_UserTable, LuaReference::Unset(), SongID::Unset(), and ZERO.
Member Function Documentation
AddCategoryHighScore()
void Profile::AddCategoryHighScore (StepsType st, RankingCategory rc, HighScore hs, int & iIndexOut)
References HighScoreList::AddHighScore(), and m_CategoryHighScores.
Referenced by ProfileManager::AddCategoryScore().
AddGoal()
void Profile::AddGoal (const string & ck)
References MessageManager::Broadcast(), ScoreGoal::chartkey, ScoreGoal::CheckVacuity(), DLMAN, FillGoalTable(), GAMESTATE, ModsGroup< T >::GetCurrent(), DateTime::GetNowDateTime(), goalmap, SongOptions::m_fMusicRate, GameState::m_SongOptions, MESSAGEMAN, ScoreGoal::percent, ScoreGoal::rate, and ScoreGoal::timeassigned.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
AddScreenshot()
void Profile::AddScreenshot (const Screenshot & screenshot)
References m_vScreenshots.
Referenced by LunaProfile::AddScreenshot(), ScreenEvaluation::Input(), and LunaProfile::LunaProfile().
AddStepsHighScore()
void Profile::AddStepsHighScore (const Song * pSong, const Steps * pSteps, HighScore hs, int & iIndexOut)
References HighScoreList::AddHighScore(), and GetStepsHighScoreList().
Referenced by ProfileManager::AddStepsScore(), and FillProfileStats().
AddStepTotals()
void Profile::AddStepTotals (int iNumTapsAndHolds, int iNumJumps, int iNumHolds, int iNumRolls, int iNumMines, int iNumHands, int iNumLifts)
References m_iTotalHands, m_iTotalHolds, m_iTotalJumps, m_iTotalLifts, m_iTotalMines, m_iTotalRolls, and m_iTotalTapsAndHolds.
Referenced by ProfileManager::AddStepTotals().
AddToFavorites()
void Profile::AddToFavorites (const string & ck) inline
References FavoritedCharts.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
AddToPermaMirror()
void Profile::AddToPermaMirror (const string & ck) inline
References PermaMirrorCharts.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
CalculateStatsFromScores() [1/2]
void Profile::CalculateStatsFromScores (LoadingWindow * ld)
References ScoreManager::CalcPlayerRating(), ScoreManager::GetAllProfileScores(), HighScore::GetSurvivalSeconds(), HighScore::GetTapNoteScore(), LOG, m_fPlayerRating, m_fPlayerSkillsets, m_iNumTotalSongsPlayed, m_iTotalDancePoints, m_iTotalGameplaySeconds, m_iTotalHolds, m_iTotalMines, m_iTotalTapsAndHolds, m_sProfileID, ScoreManager::RecalculateSSRs(), SCOREMAN, TNS_HitMine, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, and RageLog::Trace().
CalculateStatsFromScores() [2/2]
void Profile::CalculateStatsFromScores ()
References ScoreManager::CalcPlayerRating(), ScoreManager::GetAllProfileScores(), HighScore::GetHoldNoteScore(), HighScore::GetSurvivalSeconds(), HighScore::GetTapNoteScore(), HNS_Held, LOG, m_fPlayerRating, m_fPlayerSkillsets, m_iNumTotalSongsPlayed, m_iTotalDancePoints, m_iTotalGameplaySeconds, m_iTotalHolds, m_iTotalMines, m_iTotalTapsAndHolds, m_sProfileID, ScoreManager::RecalculateSSRs(), SCOREMAN, TNS_HitMine, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, and RageLog::Trace().
Referenced by ImportScoresToEtterna(), and LoadAllFromDir().
ClearStats()
void Profile::ClearStats ()
References InitAll(), and m_sGuid.
Referenced by DebugLineClearProfileStats::DoAndLog(), and HandleStatsPrefixChange().
FillGoalTable()
void Profile::FillGoalTable ()
References SongManager::GetStepsByChartkey(), goalmap, goaltable, SONGMAN, and ScoreGoal::timeassigned.
Referenced by AddGoal(), LunaProfile::SetFromAll(), and LunaProfile::ToggleFilter().
GetAllUsedHighScoreNames()
void Profile::GetAllUsedHighScoreNames (std::set< RString > & names)
References GET_NAMES_FROM_MAP, and m_SongHighScores.
Referenced by LunaProfile::GetAllUsedHighScoreNames(), and LunaProfile::LunaProfile().
GetBestGrade()
Grade Profile::GetBestGrade (const Song * pSong, StepsType st) const
References FOREACH_ENUM_N, Song::GetAllSteps(), ScoreManager::GetBestGradeFor(), Steps::GetChartKey(), SongUtil::GetStepsByDifficulty(), Grade_Invalid, and SCOREMAN.
Referenced by SongUtil::SortSongPointerArrayByGrades().
GetCategoryHighScoreList() [1/2]
HighScoreList & Profile::GetCategoryHighScoreList (StepsType st, RankingCategory rc)
References m_CategoryHighScores.
Referenced by LunaProfile::GetCategoryHighScoreList(), GameState::GetRankingFeats(), XMLProfile::LoadCategoryScoresFromNode(), LunaProfile::LunaProfile(), and XMLProfile::SaveCategoryScoresCreateNode().
GetCategoryHighScoreList() [2/2]
const HighScoreList & Profile::GetCategoryHighScoreList (StepsType st, RankingCategory rc) const
GetCategoryNumTimesPlayed()
int Profile::GetCategoryNumTimesPlayed (StepsType st) const
References FOREACH_ENUM, HighScoreList::GetNumTimesPlayed(), and m_CategoryHighScores.
Referenced by XMLProfile::SaveCategoryScoresCreateNode().
GetCharacter()
Character * Profile::GetCharacter () const
References CHARMAN, FOREACH_CONST, CharacterManager::GetCharacters(), CharacterManager::GetDefaultCharacter(), and m_sCharacterID.
Referenced by LunaProfile::GetCharacter(), and LunaProfile::LunaProfile().
GetDefaultModifiers()
bool Profile::GetDefaultModifiers (const Game * pGameType, RString & sModifiersOut) const
References m_sDefaultModifiers, and Game::m_szName.
Referenced by GameState::LoadCurrentSettingsFromProfile().
GetDisplayNameOrHighScoreName()
RString Profile::GetDisplayNameOrHighScoreName () const
References m_sDisplayName, and m_sLastUsedHighScoreName.
Referenced by ProfileManager::GetPlayerName(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
GetGrades()
void Profile::GetGrades (const Song * pSong, StepsType st, int iCounts[NUM_Grade]) const
References FOREACH_ENUM, FOREACHM_CONST, SongID::FromSong(), HighScore::GetGrade(), GetHighScoresForASong(), HighScoreList::GetTopScore(), Profile::HighScoresForASteps::hsl, and Profile::HighScoresForASong::m_StepsHighScores.
Referenced by SongUtil::GetSectionNameFromSongAndSort().
GetGuid()
RString* Profile::GetGuid () inline
References m_sGuid.
Referenced by XMLProfile::LoadEttGeneralDataFromNode().
GetHighScoresForASong()
const Profile::HighScoresForASong * Profile::GetHighScoresForASong (const SongID & songID) const private
References m_SongHighScores.
Referenced by GetGrades(), and GetSongNumTimesPlayed().
GetLowestGoalForRate()
ScoreGoal & Profile::GetLowestGoalForRate (const string & ck, float rate)
References goalmap, ScoreGoal::percent, and ScoreGoal::rate.
GetMostPopularSong()
Song * Profile::GetMostPopularSong () const
References FOREACHM_CONST, and m_SongHighScores.
Referenced by LunaProfile::GetMostPopularSong(), and LunaProfile::LunaProfile().
GetNextScreenshotIndex()
int Profile::GetNextScreenshotIndex () inline
GetSongLastPlayedDateTime()
DateTime Profile::GetSongLastPlayedDateTime (const Song * pSong) const
References ASSERT, FOREACHM_CONST, SongID::FromSong(), HighScoreList::GetLastPlayed(), HighScoreList::GetNumTimesPlayed(), and m_SongHighScores.
GetSongNumTimesPlayed() [1/2]
int Profile::GetSongNumTimesPlayed (const Song * pSong) const
References SongID::FromSong().
Referenced by ProfileManager::GetSongNumTimesPlayed(), LunaProfile::GetSongNumTimesPlayed(), LunaProfile::LunaProfile(), XMLProfile::SaveSongScoresCreateNode(), and SongUtil::SortSongPointerArrayByNumPlays().
GetSongNumTimesPlayed() [2/2]
int Profile::GetSongNumTimesPlayed (const SongID & songID) const
References FOREACHM_CONST, GetHighScoresForASong(), HighScoreList::GetNumTimesPlayed(), Profile::HighScoresForASteps::hsl, and Profile::HighScoresForASong::m_StepsHighScores.
GetSongsActual()
float Profile::GetSongsActual (StepsType st, Difficulty dc) const
References CHECKPOINT_M, DifficultyToString(), FOREACHM_CONST, Steps::GetDifficulty(), HighScore::GetPercentDP(), Song::GetSongDir(), HighScoreList::GetTopScore(), Profile::HighScoresForASteps::hsl, m_SongHighScores, Profile::HighScoresForASong::m_StepsHighScores, Steps::m_StepsType, ssprintf(), StepsID::ToSteps(), and StepsID::ToString().
Referenced by LunaProfile::GetSongsActual(), GetSongsPercentComplete(), and LunaProfile::LunaProfile().
GetSongsAndCoursesPercentCompleteAllDifficulties()
float Profile::GetSongsAndCoursesPercentCompleteAllDifficulties (StepsType st) const
GetSongsPercentComplete()
float Profile::GetSongsPercentComplete (StepsType st, Difficulty dc) const
References GetSongsActual(), and GetSongsPossible().
Referenced by LunaProfile::GetSongsPercentComplete(), and LunaProfile::LunaProfile().
GetSongsPossible()
float Profile::GetSongsPossible (StepsType st, Difficulty dc) const
References SongManager::GetAllSongs(), Song::GetAllSteps(), Steps::GetDifficulty(), Steps::m_StepsType, and SONGMAN.
Referenced by GetSongsPercentComplete(), LunaProfile::GetSongsPossible(), and LunaProfile::LunaProfile().
GetStepsHighScoreList() [1/2]
const HighScoreList & Profile::GetStepsHighScoreList (const Song * pSong, const Steps * pSteps) const
Referenced by AddStepsHighScore(), ScreenSelectMusic::AfterStepsOrTrailChange(), LunaProfile::GetHighScoreList(), PaneDisplay::GetPaneTextAndLevel(), GameState::GetRankingFeats(), GetStepsNumTimesPlayed(), GetTotalStepsWithTopGrade(), HasPassedSteps(), and IncrementStepsPlayCount().
GetStepsHighScoreList() [2/2]
HighScoreList & Profile::GetStepsHighScoreList (const Song * pSong, const Steps * pSteps)
References SongID::FromSong(), StepsID::FromSteps(), Profile::HighScoresForASteps::hsl, m_SongHighScores, and Profile::HighScoresForASong::m_StepsHighScores.
GetStepsNumTimesPlayed()
int Profile::GetStepsNumTimesPlayed (const Song * pSong, const Steps * pSteps) const
References HighScoreList::GetNumTimesPlayed(), and GetStepsHighScoreList().
Referenced by StepsUtil::SortStepsPointerArrayByNumPlays().
GetTotalNumSongsPassed()
int Profile::GetTotalNumSongsPassed () const
References FOREACH_ENUM, and m_iNumStagesPassedByPlayMode.
GetTotalStepsWithTopGrade()
int Profile::GetTotalStepsWithTopGrade (StepsType st, Difficulty d, Grade g) const
References FOREACH_CONST, SongManager::GetAllSongs(), GetStepsHighScoreList(), SONGMAN, and HighScoreList::vHighScores.
Referenced by LunaProfile::GetTotalStepsWithTopGrade(), and LunaProfile::LunaProfile().
HandleStatsPrefixChange()
void Profile::HandleStatsPrefixChange (RString dir, bool require_signature)
References ClearStats(), ProfileManager::GetStatsPrefix(), IsAFile(), LoadAllFromDir(), m_iTotalGameplaySeconds, m_iTotalSessions, m_iTotalSessionSeconds, m_LastDifficulty, m_lastSong, m_LastStepsType, m_ListPriority, m_sCharacterID, m_sDefaultModifiers, m_sDisplayName, m_sGuid, m_sLastUsedHighScoreName, m_SortOrder, m_Type, m_UserTable, PROFILEMAN, SaveAllToDir(), and STATS_XML.
HasGoal()
bool Profile::HasGoal (const string & ck) inline
Referenced by SetAnyAchievedGoals().
HasPassedAnyStepsInSong()
bool Profile::HasPassedAnyStepsInSong (const Song * pSong) const
References FOREACH_CONST, Song::GetAllSteps(), and HasPassedSteps().
Referenced by LunaProfile::HasPassedAnyStepsInSong(), and LunaProfile::LunaProfile().
HasPassedSteps()
bool Profile::HasPassedSteps (const Song * pSong, const Steps * pSteps) const
References HighScore::GetGrade(), GetStepsHighScoreList(), HighScoreList::GetTopScore(), Grade_Failed, and Grade_NoData.
Referenced by HasPassedAnyStepsInSong().
ImportScoresToEtterna()
void Profile::ImportScoresToEtterna ()
References CalculateStatsFromScores(), FOREACHM, SongID::FromSong(), SongManager::GetAllSongs(), Steps::GetChartKey(), Song::GetDisplayMainTitle(), Steps::GetRadarValues(), StepsID::GetStepsType(), HighScore::GetTapNoteScore(), ScoreManager::ImportScore(), IsEtternaProfile, StepsID::IsValid(), XMLProfile::LoadStatsXmlForConversion(), LOG, Song::m_sGroupName, m_SongHighScores, m_sProfileID, Profile::HighScoresForASong::m_StepsHighScores, PLAYER_1, PROFILEMAN, RadarCategory_Notes, RadarCategory_TapsAndHolds, ProfileManager::SaveProfile(), SCOREMAN, SCREENMAN, HighScore::SetChartKey(), Song::SetSongDir(), SONGMAN, StepsType_dance_single, ScreenManager::SystemMessage(), TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, StepsID::ToSteps(), StepsID::ToString(), SongID::ToString(), StringConversion::ToString(), RageLog::Trace(), and XMLProf.
Referenced by ProfileManager::ConvertProfile(), and LoadAllFromDir().
IncrementCategoryPlayCount()
void Profile::IncrementCategoryPlayCount (StepsType st, RankingCategory rc)
References DateTime::GetNowDate(), HighScoreList::IncrementPlayCount(), and m_CategoryHighScores.
Referenced by ProfileManager::IncrementCategoryPlayCount().
IncrementStepsPlayCount()
void Profile::IncrementStepsPlayCount (const Song * pSong, const Steps * pSteps)
References DateTime::GetNowDate(), GetStepsHighScoreList(), and HighScoreList::IncrementPlayCount().
Referenced by FillProfileStats(), and ProfileManager::IncrementStepsPlayCount().
InitAll()
void Profile::InitAll () inline
References InitCategoryScores(), InitEditableData(), InitGeneralData(), InitScreenshotData(), and InitSongScores().
Referenced by ClearStats(), and LoadAllFromDir().
InitCategoryScores()
void Profile::InitCategoryScores ()
References FOREACH_ENUM, HighScoreList::Init(), and m_CategoryHighScores.
Referenced by InitAll().
InitEditableData()
void Profile::InitEditableData ()
References m_sCharacterID, m_sDisplayName, and m_sLastUsedHighScoreName.
Referenced by InitAll().
InitGeneralData()
void Profile::InitGeneralData ()
References Difficulty_Invalid, FOREACH_ENUM, DateTime::Init(), m_fPlayerRating, m_fPlayerSkillsets, m_iCurrentCombo, m_iNumExtraStagesFailed, m_iNumExtraStagesPassed, m_iNumSongsPlayedByDifficulty, m_iNumSongsPlayedByMeter, m_iNumSongsPlayedByPlayMode, m_iNumSongsPlayedByStyle, m_iNumStagesPassedByGrade, m_iNumStagesPassedByPlayMode, m_iNumToasties, m_iNumTotalSongsPlayed, m_iTotalDancePoints, m_iTotalGameplaySeconds, m_iTotalHands, m_iTotalHolds, m_iTotalJumps, m_iTotalLifts, m_iTotalMines, m_iTotalRolls, m_iTotalSessions, m_iTotalSessionSeconds, m_iTotalTapsAndHolds, m_LastDifficulty, m_LastPlayedDate, m_lastSong, m_LastStepsType, m_sGuid, m_sLastPlayedMachineGuid, m_SortOrder, m_UserTable, MakeGuid(), MAX_METER, SortOrder_Invalid, StepsType_Invalid, LuaReference::Unset(), SongID::Unset(), and ZERO.
Referenced by InitAll().
InitScreenshotData()
void Profile::InitScreenshotData ()
References m_vScreenshots.
Referenced by InitAll().
InitSongScores()
void Profile::InitSongScores ()
References m_SongHighScores.
Referenced by FillProfileStats(), and InitAll().
LoadAllFromDir()
ProfileLoadResult Profile::LoadAllFromDir (const RString & sDir, bool bRequireSignature, LoadingWindow * ld)
References RageTimer::Ago(), ASSERT, CalculateStatsFromScores(), DBProf, FILEMAN, GetDirListing(), ImportScoresToEtterna(), InitAll(), RageFileManager::IsADirectory(), IsEtternaProfile, ld_update, LoadEditableDataFromDir(), XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), LoadTypeFromDir(), LOG, max(), RageFileManager::Move(), ProfileLoadResult_Success, StdString::CStdStr< CT >::Right(), LoadingWindow::SetIndeterminate(), XMLProfile::SetLoadingProfile(), DBProfile::SetLoadingProfile(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), RageTimer::Touch(), RageLog::Trace(), and XMLProf.
Referenced by HandleStatsPrefixChange(), and ProfileManager::LoadProfile().
LoadCustomFunction()
void Profile::LoadCustomFunction (const RString & sDir)
References ASSERT_M, LuaManager::Get(), ThemeManager::GetMetricR(), L, LUA, LuaHelpers::Push(), LuaReference::PushSelf(), PushSelf(), LuaManager::Release(), LuaHelpers::RunScriptOnStack(), and THEME.
Referenced by ProfileManager::LoadLocalProfileFromMachine().
LoadEditableDataFromDir()
ProfileLoadResult Profile::LoadEditableDataFromDir (const RString & sDir)
References EDITABLE_INI, FILEMAN, RageFileManager::GetFileSizeInBytes(), IniFile::GetValue(), IsAFile(), m_sCharacterID, m_sDisplayName, m_sLastUsedHighScoreName, MAX_EDITABLE_INI_SIZE_BYTES, PROFILE_MAX_DISPLAY_NAME_LENGTH, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, IniFile::ReadFile(), LuaHelpers::ReportScriptErrorFmt(), RStringToWstring(), and WStringToRString().
Referenced by LoadAllFromDir().
LoadStatsFromDir()
ProfileLoadResult Profile::LoadStatsFromDir (RString dir, bool require_signature)
References XMLProfile::LoadStatsFromDir(), and XMLProf.
LoadTypeFromDir()
void Profile::LoadTypeFromDir (const RString & dir)
References RageFileManager::DoesFileExist(), FILEMAN, XNode::GetAttrValue(), XNode::GetChild(), m_ListPriority, m_Type, NUM_ProfileType, ProfileType_Normal, IniFile::ReadFile(), and TYPE_INI.
Referenced by LoadAllFromDir(), and ProfileManager::RefreshLocalProfilesFromDisk().
MakeFileNameNoExtension()
RString Profile::MakeFileNameNoExtension (const RString & sFileNameBeginning, int iIndex) static
References ssprintf().
Referenced by MakeUniqueFileNameNoExtension().
MakeGuid()
RString Profile::MakeGuid () static
References CryptManager::GetRandomBytes(), GUID_SIZE_BYTES, and ssprintf().
Referenced by InitGeneralData(), and MakeRandomHighScore().
MakeUniqueFileNameNoExtension()
RString Profile::MakeUniqueFileNameNoExtension (const RString & sDir, const RString & sFileNameBeginning) static
References ASSERT, Regex::Compare(), FILEMAN, RageFileManager::FlushDirCache(), GetDirListing(), MakeFileNameNoExtension(), and StringToInt().
MergeScoresFromOtherProfile()
void Profile::MergeScoresFromOtherProfile (Profile * other, bool skip_totals, RString const & from_dir, RString const & to_dir)
References RageFileManager::DoesFileExist(), FILEMAN, FOREACH_ENUM, m_iNumExtraStagesFailed, m_iNumExtraStagesPassed, m_iNumSongsPlayedByDifficulty, m_iNumSongsPlayedByMeter, m_iNumSongsPlayedByPlayMode, m_iNumStagesPassedByGrade, m_iNumStagesPassedByPlayMode, m_iNumToasties, m_iNumTotalSongsPlayed, m_iTotalDancePoints, m_iTotalGameplaySeconds, m_iTotalHands, m_iTotalHolds, m_iTotalJumps, m_iTotalLifts, m_iTotalMines, m_iTotalRolls, m_iTotalSessions, m_iTotalSessionSeconds, m_iTotalTapsAndHolds, m_SongHighScores, m_vScreenshots, MAX_METER, MERGE_FIELD, MERGE_SCORES_IN_MEMBER, and RageFileManager::Move().
Referenced by ProfileManager::MergeLocalProfiles().
MoveBackupToDir()
void Profile::MoveBackupToDir (const RString & sFromDir, const RString & sToDir) static
References DONT_SHARE_SIG, FILEMAN, RageFileManager::IsAFile(), RageFileManager::Move(), and XMLProfile::MoveBackupToDir().
Referenced by ProfileManager::ConvertProfile(), and ProfileManager::SaveProfile().
PushSelf()
void Profile::PushSelf (lua_State * L)
Referenced by LunaGameState::GetEditLocalProfile(), LunaProfileManager::GetLocalProfile(), LunaProfileManager::GetLocalProfileFromIndex(), LunaProfileManager::GetMachineProfile(), LunaProfileManager::GetProfile(), and LoadCustomFunction().
RemoveFromFavorites()
void Profile::RemoveFromFavorites (const string & ck)
References FavoritedCharts.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
RemoveFromPermaMirror()
void Profile::RemoveFromPermaMirror (const string & ck)
References PermaMirrorCharts.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
RemoveGoal()
void Profile::RemoveGoal (const string & ck, DateTime assigned)
References DLMAN, and goalmap.
Referenced by LunaScoreGoal::Delete().
SaveAllToDir()
bool Profile::SaveAllToDir (const RString & sDir, bool bSignData) const
References RageFileManager::CreateDir(), FILEMAN, GAMESTATE, DateTime::GetNowDate(), m_LastPlayedDate, PLAYER_1, GameState::SaveCurrentSettingsToProfile(), SaveEditableDataToDir(), XMLProfile::SaveEttXmlToDir(), SaveStatsWebPageToDir(), SaveTypeToDir(), and XMLProf.
Referenced by ProfileManager::CreateLocalProfile(), HandleStatsPrefixChange(), ProfileManager::SaveLocalProfile(), and ProfileManager::SaveProfile().
SaveEditableDataToDir()
void Profile::SaveEditableDataToDir (const RString & sDir) const
References m_sCharacterID, m_sDisplayName, m_sLastUsedHighScoreName, IniFile::SetValue(), and IniFile::WriteFile().
Referenced by LunaProfile::RenameProfile(), and SaveAllToDir().
SaveMachinePublicKeyToDir()
void Profile::SaveMachinePublicKeyToDir (const RString & sDir) const
References CRYPTMAN, FileCopy(), CryptManager::GetPublicKeyFileName(), IsAFile(), PrefsManager::m_bSignProfileData, PREFSMAN, and PUBLIC_KEY_FILE.
SaveStatsWebPageToDir()
void Profile::SaveStatsWebPageToDir (const RString & sDir) const
References ASSERT, and PROFILEMAN.
Referenced by SaveAllToDir().
SaveTypeToDir()
void Profile::SaveTypeToDir (const RString & dir) const
References m_ListPriority, m_Type, IniFile::SetValue(), and IniFile::WriteFile().
Referenced by InsertProfileIntoList(), ProfileManager::MoveProfilePriority(), and SaveAllToDir().
SetAnyAchievedGoals()
void Profile::SetAnyAchievedGoals (const string & ck, float & rate, const HighScore & pscore)
References ScoreGoal::achieved, ScoreGoal::chartkey, CHECKPOINT_M, DLMAN, f, HighScore::GetDateTime(), HighScore::GetScoreKey(), HighScore::GetWifeScore(), goalmap, HasGoal(), ScoreGoal::percent, ScoreGoal::rate, ScoreGoal::scorekey, ScoreGoal::timeachieved, and ScoreGoal::timeassigned.
Referenced by StageStats::FinalizeScores().
SetCharacter()
void Profile::SetCharacter (const RString & sCharacterID)
References CHARMAN, CharacterManager::GetCharacterFromID(), and m_sCharacterID.
Referenced by LunaProfile::LunaProfile(), and LunaProfile::SetCharacter().
SetDefaultModifiers()
void Profile::SetDefaultModifiers (const Game * pGameType, const RString & sModifiers)
References m_sDefaultModifiers, and Game::m_szName.
Referenced by GameState::SaveCurrentSettingsToProfile().
swap()
void Profile::swap (Profile & other)
References m_bNewProfile, m_CategoryHighScores, m_iCurrentCombo, m_iNumExtraStagesFailed, m_iNumExtraStagesPassed, m_iNumSongsPlayedByDifficulty, m_iNumSongsPlayedByMeter, m_iNumSongsPlayedByPlayMode, m_iNumSongsPlayedByStyle, m_iNumStagesPassedByGrade, m_iNumStagesPassedByPlayMode, m_iNumToasties, m_iNumTotalSongsPlayed, m_iTotalDancePoints, m_iTotalGameplaySeconds, m_iTotalHands, m_iTotalHolds, m_iTotalJumps, m_iTotalLifts, m_iTotalMines, m_iTotalRolls, m_iTotalSessions, m_iTotalSessionSeconds, m_iTotalTapsAndHolds, m_LastPlayedDate, m_sCharacterID, m_sDisplayName, m_sGuid, m_sLastPlayedMachineGuid, m_sLastUsedHighScoreName, m_SongHighScores, m_UserTable, m_vScreenshots, MAX_METER, NUM_Difficulty, NUM_Grade, NUM_PlayMode, NUM_RankingCategory, NUM_StepsType, SWAP_ARRAY, SWAP_GENERAL, and SWAP_STR_MEMBER.
Referenced by DirAndProfile::swap().
Member Data Documentation
allplaylists
map<string, Playlist> Profile::allplaylists
Referenced by SongManager::GetPlaylists(), ScreenSelectMusic::Input(), XMLProfile::LoadFavoritesFromNode(), DBProfile::LoadPlayLists(), XMLProfile::LoadPlaylistsFromNode(), XMLProfile::SaveEttXmlCreateNode(), DBProfile::SavePlayLists(), and XMLProfile::SavePlaylistsCreateNode().
asc
bool Profile::asc = false
Referenced by LunaProfile::SetFromAll(), LunaProfile::SortByDate(), LunaProfile::SortByDiff(), LunaProfile::SortByName(), LunaProfile::SortByPriority(), and LunaProfile::SortByRate().
DBProf
DBProfile Profile::DBProf private
Referenced by LoadAllFromDir().
FavoritedCharts
set<string> Profile::FavoritedCharts
Referenced by AddToFavorites(), ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), LunaProfile::GetNumFaves(), ScreenNetSelectMusic::Init(), ScreenSelectMusic::Input(), XMLProfile::LoadFavoritesFromNode(), DBProfile::LoadFavourites(), XMLProfile::LoadGeneralDataFromNode(), RemoveFromFavorites(), XMLProfile::SaveEttXmlCreateNode(), XMLProfile::SaveFavoritesCreateNode(), DBProfile::SaveFavourites(), and XMLProfile::SaveGeneralDataCreateNode().
filtermode
int Profile::filtermode = 1
Referenced by LunaProfile::GetFilterMode(), LunaProfile::SetFromAll(), and LunaProfile::ToggleFilter().
goalmap
unordered_map<string, GoalsForChart> Profile::goalmap
Referenced by AddGoal(), ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), FillGoalTable(), LunaProfile::GetEasiestGoalForChartAndRate(), GetLowestGoalForRate(), ScreenNetSelectMusic::Init(), DBProfile::LoadScoreGoals(), XMLProfile::LoadScoreGoalsFromNode(), RemoveGoal(), XMLProfile::SaveEttXmlCreateNode(), DBProfile::SaveScoreGoals(), XMLProfile::SaveScoreGoalsCreateNode(), and SetAnyAchievedGoals().
goaltable
vector<ScoreGoal*> Profile::goaltable
Referenced by FillGoalTable(), LunaProfile::GetGoalTable(), LunaProfile::SortByDate(), LunaProfile::SortByDiff(), LunaProfile::SortByName(), LunaProfile::SortByPriority(), LunaProfile::SortByRate(), and LunaProfile::ToggleFilter().
IsEtternaProfile
bool Profile::IsEtternaProfile { false }
Referenced by ImportScoresToEtterna(), LoadAllFromDir(), and XMLProfile::LoadEttFromDir().
m_bNewProfile
bool Profile::m_bNewProfile { false }
Is this a brand new profile?
Referenced by swap().
m_CategoryHighScores
HighScoreList Profile::m_CategoryHighScores[NUM_StepsType][NUM_RankingCategory]
Referenced by AddCategoryHighScore(), GetCategoryHighScoreList(), GetCategoryNumTimesPlayed(), IncrementCategoryPlayCount(), InitCategoryScores(), Profile(), and swap().
m_fPlayerRating
float Profile::m_fPlayerRating
Referenced by AddPlayerStatsToProfile(), CalculateStatsFromScores(), LunaProfile::GetPlayerRating(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
m_fPlayerSkillsets
float Profile::m_fPlayerSkillsets[NUM_Skillset]
Referenced by AddPlayerStatsToProfile(), CalculateStatsFromScores(), LunaProfile::GetPlayerSkillsetRating(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
m_iCurrentCombo
int Profile::m_iCurrentCombo { 0 }
Referenced by GameState::FinishStage(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), GameState::ResetStageStatistics(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumExtraStagesFailed
int Profile::m_iNumExtraStagesFailed { 0 }
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumExtraStagesPassed
int Profile::m_iNumExtraStagesPassed { 0 }
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumSongsPlayedByDifficulty
int Profile::m_iNumSongsPlayedByDifficulty[NUM_Difficulty]
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), Profile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumSongsPlayedByMeter
int Profile::m_iNumSongsPlayedByMeter[MAX_METER+1]
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), Profile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumSongsPlayedByPlayMode
int Profile::m_iNumSongsPlayedByPlayMode[NUM_PlayMode]
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), Profile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumSongsPlayedByStyle
map<StyleID, int> Profile::m_iNumSongsPlayedByStyle
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumStagesPassedByGrade
int Profile::m_iNumStagesPassedByGrade[NUM_Grade]
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), Profile(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumStagesPassedByPlayMode
int Profile::m_iNumStagesPassedByPlayMode[NUM_PlayMode]
Referenced by GetTotalNumSongsPassed(), InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), Profile(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumToasties
int Profile::m_iNumToasties { 0 }
Referenced by LunaProfile::GetNumToasties(), ProfileManager::IncrementToastiesCount(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iNumTotalSongsPlayed
int Profile::m_iNumTotalSongsPlayed { 0 }
Count the total number of songs played.
This stat counts once per song, even if two players are active.
Referenced by CalculateStatsFromScores(), StatsManager::CommitStatsToProfiles(), LunaProfile::GetNumTotalSongsPlayed(), LunaProfile::GetTotalNumSongsPlayed(), InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalDancePoints
int Profile::m_iTotalDancePoints { 0 }
Referenced by CalculateStatsFromScores(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalGameplaySeconds
int Profile::m_iTotalGameplaySeconds { 0 }
Referenced by CalculateStatsFromScores(), StatsManager::CommitStatsToProfiles(), LunaProfile::GetTotalGameplaySeconds(), HandleStatsPrefixChange(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalHands
int Profile::m_iTotalHands { 0 }
Referenced by AddStepTotals(), LunaProfile::GetTotalHands(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalHolds
int Profile::m_iTotalHolds { 0 }
Referenced by AddStepTotals(), CalculateStatsFromScores(), LunaProfile::GetTotalHolds(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalJumps
int Profile::m_iTotalJumps { 0 }
Referenced by AddStepTotals(), LunaProfile::GetTotalJumps(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalLifts
int Profile::m_iTotalLifts { 0 }
Referenced by AddStepTotals(), LunaProfile::GetTotalLifts(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalMines
int Profile::m_iTotalMines { 0 }
Referenced by AddStepTotals(), CalculateStatsFromScores(), LunaProfile::GetTotalMines(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalRolls
int Profile::m_iTotalRolls { 0 }
Referenced by AddStepTotals(), LunaProfile::GetTotalRolls(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalSessions
int Profile::m_iTotalSessions { 0 }
Referenced by LunaProfile::GetTotalSessions(), HandleStatsPrefixChange(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), GameState::LoadProfiles(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalSessionSeconds
int Profile::m_iTotalSessionSeconds { 0 }
Referenced by GameState::CommitStageStats(), LunaProfile::GetTotalSessionSeconds(), HandleStatsPrefixChange(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_iTotalTapsAndHolds
int Profile::m_iTotalTapsAndHolds { 0 }
Referenced by AddStepTotals(), CalculateStatsFromScores(), LunaProfile::GetTotalTapsAndHolds(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_LastDifficulty
Difficulty Profile::m_LastDifficulty { Difficulty_Invalid }
Referenced by HandleStatsPrefixChange(), InitGeneralData(), GameState::LoadCurrentSettingsFromProfile(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), GameState::SaveCurrentSettingsToProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), and DBProfile::SaveGeneralData().
m_LastPlayedDate
DateTime Profile::m_LastPlayedDate mutable
Referenced by InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), Profile(), SaveAllToDir(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_lastSong
SongID Profile::m_lastSong
Referenced by StageStats::FinalizeScores(), LunaProfile::GetLastPlayedSong(), HandleStatsPrefixChange(), InitGeneralData(), GameState::LoadCurrentSettingsFromProfile(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), Profile(), GameState::SaveCurrentSettingsToProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
m_LastStepsType
StepsType Profile::m_LastStepsType { StepsType_Invalid }
Referenced by HandleStatsPrefixChange(), InitGeneralData(), GameState::LoadCurrentSettingsFromProfile(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), GameState::SaveCurrentSettingsToProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
m_ListPriority
int Profile::m_ListPriority { 0 }
Referenced by HandleStatsPrefixChange(), InsertProfileIntoList(), LoadTypeFromDir(), ProfileManager::MoveProfilePriority(), ProfileManager::RefreshLocalProfilesFromDisk(), and SaveTypeToDir().
m_sCharacterID
RString Profile::m_sCharacterID
Referenced by ProfileManager::CreateLocalProfile(), ScreenOptionsEditProfile::ExportOptions(), GetCharacter(), HandleStatsPrefixChange(), ScreenOptionsEditProfile::ImportOptions(), ProfileManager::Init(), InitEditableData(), LoadEditableDataFromDir(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::LoadStatsXmlFromNode(), SaveEditableDataToDir(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), SetCharacter(), and swap().
m_sDefaultModifiers
map<RString, RString> Profile::m_sDefaultModifiers
Referenced by GetDefaultModifiers(), HandleStatsPrefixChange(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and SetDefaultModifiers().
m_sDisplayName
RString Profile::m_sDisplayName
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ProfileManager::CreateLocalProfile(), LunaProfile::GetDisplayName(), GetDisplayNameOrHighScoreName(), ScreenOptionsManageProfiles::HandleScreenMessage(), HandleStatsPrefixChange(), InitEditableData(), LoadEditableDataFromDir(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::LoadStatsXmlFromNode(), LunaProfile::RenameProfile(), SaveEditableDataToDir(), ScreenGameplay::SaveReplay(), LunaProfile::SetDisplayName(), swap(), and ValidateLocalProfileName().
m_sGuid
RString Profile::m_sGuid
Referenced by ClearStats(), StageStats::FinalizeScores(), GetGuid(), HandleStatsPrefixChange(), InitGeneralData(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), ScreenGameplay::SaveReplay(), and swap().
m_sLastPlayedMachineGuid
RString Profile::m_sLastPlayedMachineGuid mutable
Which machine did we play on last, based on the Guid?
This is mutable because it's overwritten on save, but is usually const everywhere else. It was decided to keep const on the whole save chain and keep this mutable. -Chris
Referenced by InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_sLastUsedHighScoreName
RString Profile::m_sLastUsedHighScoreName
The last used name for high scoring purposes.
This really shouldn't be in "editable", but it's needed in the smaller editable file so that it can be ready quickly.
Referenced by ProfileManager::AddStepsScore(), GetDisplayNameOrHighScoreName(), LunaProfile::GetLastUsedHighScoreName(), HandleStatsPrefixChange(), InitEditableData(), LoadEditableDataFromDir(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::LoadStatsXmlFromNode(), SaveEditableDataToDir(), XMLProfile::SaveGeneralDataCreateNode(), LunaProfile::SetLastUsedHighScoreName(), and swap().
m_SongHighScores
std::map<SongID, HighScoresForASong> Profile::m_SongHighScores
Referenced by GetAllUsedHighScoreNames(), GetHighScoresForASong(), GetMostPopularSong(), GetSongLastPlayedDateTime(), GetSongsActual(), GetStepsHighScoreList(), ImportScoresToEtterna(), InitSongScores(), XMLProfile::LoadSongScoresFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveSongScoresCreateNode(), and swap().
m_SortOrder
SortOrder Profile::m_SortOrder { SortOrder_Invalid }
Referenced by HandleStatsPrefixChange(), InitGeneralData(), GameState::LoadCurrentSettingsFromProfile(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), GameState::SaveCurrentSettingsToProfile(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
m_sProfileID
RString Profile::m_sProfileID
Referenced by AddPlayerStatsToProfile(), CalculateStatsFromScores(), ProfileManager::CreateLocalProfile(), ImportScoresToEtterna(), XMLProfile::LoadEttScoresFromNode(), ProfileManager::RefreshLocalProfilesFromDisk(), LunaProfile::RenameProfile(), and XMLProfile::SaveEttScoresCreateNode().
m_Type
ProfileType Profile::m_Type { ProfileType_Normal }
Referenced by ProfileManager::ChangeProfileType(), HandleStatsPrefixChange(), InsertProfileIntoList(), LoadTypeFromDir(), ProfileManager::MoveProfilePriority(), ProfileManager::RefreshLocalProfilesFromDisk(), and SaveTypeToDir().
m_UserTable
LuaTable Profile::m_UserTable
Referenced by LunaProfile::GetUserTable(), HandleStatsPrefixChange(), InitGeneralData(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), Profile(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), and swap().
m_vScreenshots
vector<Screenshot> Profile::m_vScreenshots
Referenced by AddScreenshot(), InitScreenshotData(), XMLProfile::LoadScreenshotDataFromNode(), MergeScoresFromOtherProfile(), XMLProfile::SaveScreenshotDataCreateNode(), and swap().
PermaMirrorCharts
set<string> Profile::PermaMirrorCharts
Referenced by AddToPermaMirror(), LunaProfile::IsCurrentChartPermamirror(), XMLProfile::LoadPermaMirrorFromNode(), DBProfile::LoadPermaMirrors(), RemoveFromPermaMirror(), XMLProfile::SaveEttXmlCreateNode(), XMLProfile::SavePermaMirrorCreateNode(), and DBProfile::SavePermaMirrors().
profiledir
string Profile::profiledir
sortmode
int Profile::sortmode = 1
Referenced by LunaProfile::SortByDate(), LunaProfile::SortByDiff(), LunaProfile::SortByName(), LunaProfile::SortByPriority(), and LunaProfile::SortByRate().
XMLProf
XMLProfile Profile::XMLProf private
Referenced by ImportScoresToEtterna(), LoadAllFromDir(), LoadStatsFromDir(), and SaveAllToDir().
The documentation for this class was generated from the following files:
Profile.h
Profile.cpp