Etterna: NetworkSyncManager Class Reference
NetworkSyncManager Class Reference
Uses ezsockets for primitive song syncing and score reporting.
#include <NetworkSyncManager.h>
Public Member Functions
NetworkSyncManager (LoadingWindow *ld=NULL)
~NetworkSyncManager ()
void ReportScore (int playerID, int step, int score, int combo, float offset)
void ReportScore (int playerID, int step, int score, int combo, float offset, int numNotes)
void ReportHighScore (HighScore *hs, PlayerStageStats &pss)
void ReportSongOver ()
void ReportStyle ()
void ReportNSSOnOff (int i)
void OnMusicSelect ()
void OffMusicSelect ()
void OnRoomSelect ()
void OffRoomSelect ()
void OnOptions ()
void OffOptions ()
void OnEval ()
void OffEval ()
void StartRequest (short position)
RString GetServerName ()
void CreateNewRoom (RString name, RString desc="", RString password="")
void EnterRoom (RString name, RString password="")
void LeaveRoom ()
void RequestRoomInfo (RString name)
void PostStartUp (const RString &ServerIP)
bool IsETTP ()
void CloseConnection ()
void DisplayStartupStatus ()
void Update (float fDeltaTime)
bool ChangedScoreboard (int Column)
void SendChat (const RString &message, string tab="", int type=0)
void SelectUserSong ()
int GetServerVersion ()
RString MD5Hex (const RString &sInput)
void GetListOfLANServers (vector< NetServerInfo > &AllServers)
void Login (RString user, RString pass)
void Logout ()
SMOStepType TranslateStepType (int score)
void PushSelf (lua_State *L)
Static Public Member Functions
static unsigned long GetCurrentSMBuild (LoadingWindow *ld)
Public Attributes
SMOProtocol SMOP
ETTProtocol ETTP
NetProtocol * curProtocol { nullptr }
int m_playerLife
bool useSMserver
bool isSMOnline
bool loggedIn
string loginResponse
Chat chat
vector< int > m_PlayerStatus
int m_ActivePlayers
vector< int > m_ActivePlayer
vector< RString > m_PlayerNames
vector< std::string > fl_PlayerNames
vector< int > fl_PlayerStates
vector< EndOfGame_PlayerData > m_EvalPlayerData
RString m_Scoreboard [NUM_NSScoreBoardColumn]
RString m_WaitingChat
RString m_sMainTitle
RString m_sArtist
RString m_sSubTitle
RString m_sFileHash
string chartkey
Song * song { nullptr }
Steps * steps { nullptr }
Difficulty difficulty
int meter
int rate
int m_sHash
int m_iSelectMode
RString m_sChatText
StepManiaLanServer * LANserver
int m_startupStatus
vector< RoomData > m_Rooms
vector< NetServerInfo > m_vAllLANServers
bool m_scoreboardchange [NUM_NSScoreBoardColumn]
Private Member Functions
void ProcessInput ()
void StartUp ()
Private Attributes
int m_playerID
int m_step
int m_score
int m_combo
Detailed Description
Uses ezsockets for primitive song syncing and score reporting.
Constructor & Destructor Documentation
NetworkSyncManager()
NetworkSyncManager::NetworkSyncManager (LoadingWindow * ld = NULL)
References LuaManager::Get(), isSMOnline, L, LANserver, loggedIn, LUA, m_ActivePlayers, m_startupStatus, PushSelf(), LuaManager::Release(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetText(), StartUp(), and useSMserver.
~NetworkSyncManager()
NetworkSyncManager::~NetworkSyncManager ()
Member Function Documentation
ChangedScoreboard()
bool NetworkSyncManager::ChangedScoreboard (int Column)
References m_scoreboardchange.
Referenced by ScreenGameplay::Update().
CloseConnection()
void NetworkSyncManager::CloseConnection ()
References MessageManager::Broadcast(), chartkey, SMOProtocol::close(), ETTProtocol::close(), curProtocol, difficulty, Difficulty_Invalid, ETTP, isSMOnline, loggedIn, loginResponse, m_sArtist, m_sChatText, m_sFileHash, m_sMainTitle, m_sSubTitle, m_startupStatus, MESSAGEMAN, meter, rate, SMOP, song, steps, and useSMserver.
Referenced by CloseNetworkConnection(), ScreenGameplaySyncMachine::Init(), ScreenNetworkOptions::MenuStart(), PostStartUp(), and ETTProtocol::Update().
CreateNewRoom()
void NetworkSyncManager::CreateNewRoom (RString name, RString desc = "", RString password = "")
References NetProtocol::CreateNewRoom(), and curProtocol.
Referenced by ScreenNetRoom::CreateNewRoom().
DisplayStartupStatus()
void NetworkSyncManager::DisplayStartupStatus ()
References CONNECTION_FAILED, CONNECTION_SUCCESSFUL, curProtocol, LocalizedString::GetValue(), m_startupStatus, SCREENMAN, NetProtocol::serverName, ssprintf(), and ScreenManager::SystemMessage().
Referenced by sm_main(), and ETTProtocol::Update().
EnterRoom()
void NetworkSyncManager::EnterRoom (RString name, RString password = "")
References curProtocol, and NetProtocol::EnterRoom().
Referenced by ScreenNetRoom::HandleScreenMessage(), and ScreenNetRoom::SelectCurrent().
GetCurrentSMBuild()
unsigned long NetworkSyncManager::GetCurrentSMBuild (LoadingWindow * ld) static
References EzSockets::blocking, EzSockets::close(), EzSockets::connect(), EzSockets::create(), StdString::CStdStr< CT >::Left(), NETMAXBUFFERSIZE, EzSockets::pReadData(), PRODUCT_ID, SAFE_DELETE, EzSockets::SendData(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), split(), ssprintf(), and Trim().
Referenced by sm_main().
GetListOfLANServers()
void NetworkSyncManager::GetListOfLANServers (vector< NetServerInfo > & AllServers)
References m_vAllLANServers.
GetServerName()
RString NetworkSyncManager::GetServerName ()
References curProtocol, and NetProtocol::serverName.
GetServerVersion()
int NetworkSyncManager::GetServerVersion ()
References curProtocol, and NetProtocol::serverVersion.
Referenced by ScreenNetSelectMusic::HandleScreenMessage().
IsETTP()
bool NetworkSyncManager::IsETTP ()
References curProtocol, and ETTP.
Referenced by ScreenNetSelectBase::HandleScreenMessage(), ScreenNetSelectBase::Init(), ScreenNetSelectBase::Input(), ScreenNetSelectBase::Scroll(), and ScreenNetSelectBase::TweenOffScreen().
LeaveRoom()
void NetworkSyncManager::LeaveRoom ()
References curProtocol, and NetProtocol::LeaveRoom().
Referenced by ScreenNetSelectMusic::HandleScreenMessage().
Login()
void NetworkSyncManager::Login (RString user, RString pass)
References curProtocol, and NetProtocol::Login().
Referenced by ScreenSMOnlineLogin::SendLogin().
Logout()
void NetworkSyncManager::Logout ()
References curProtocol, and NetProtocol::Logout().
MD5Hex()
RString NetworkSyncManager::MD5Hex (const RString & sInput)
References BinaryToHex(), CryptManager::GetMD5ForString(), and StdString::CStdStr< CT >::MakeUpper().
Referenced by SMOProtocol::Login().
OffEval()
void NetworkSyncManager::OffEval ()
References curProtocol, and NetProtocol::OffEval().
Referenced by ScreenNetEvaluation::HandleScreenMessage().
OffMusicSelect()
void NetworkSyncManager::OffMusicSelect ()
References curProtocol, and NetProtocol::OffMusicSelect().
Referenced by ScreenNetSelectMusic::TweenOffScreen().
OffOptions()
void NetworkSyncManager::OffOptions ()
References curProtocol, and NetProtocol::OffOptions().
Referenced by ScreenNetSelectMusic::HandleScreenMessage().
OffRoomSelect()
void NetworkSyncManager::OffRoomSelect ()
References curProtocol, and NetProtocol::OffRoomSelect().
Referenced by ScreenNetRoom::TweenOffScreen().
OnEval()
void NetworkSyncManager::OnEval ()
References curProtocol, and NetProtocol::OnEval().
Referenced by ScreenNetEvaluation::Init().
OnMusicSelect()
void NetworkSyncManager::OnMusicSelect ()
References curProtocol, and NetProtocol::OnMusicSelect().
Referenced by ScreenNetSelectMusic::Init().
OnOptions()
void NetworkSyncManager::OnOptions ()
References curProtocol, and NetProtocol::OnOptions().
Referenced by ScreenNetSelectMusic::MenuUp().
OnRoomSelect()
void NetworkSyncManager::OnRoomSelect ()
References curProtocol, and NetProtocol::OnRoomSelect().
Referenced by ScreenNetRoom::Init().
PostStartUp()
void NetworkSyncManager::PostStartUp (const RString & ServerIP)
References MessageManager::Broadcast(), chartkey, chat, CloseConnection(), SMOProtocol::Connect(), curProtocol, difficulty, Difficulty_Invalid, RageLog::Info(), LOG, loggedIn, m_sArtist, m_sFileHash, m_sMainTitle, m_sSubTitle, m_startupStatus, MESSAGEMAN, meter, rate, Chat::rawMap, NetProtocol::serverName, NetProtocol::serverVersion, Preference< T >::Set(), SMOP, song, steps, useSMserver, and RageLog::Warn().
Referenced by ConnectToServer(), ScreenNetworkOptions::HandleScreenMessage(), and StartUp().
ProcessInput()
void NetworkSyncManager::ProcessInput () private
PushSelf()
void NetworkSyncManager::PushSelf (lua_State * L)
Referenced by NetworkSyncManager().
ReportHighScore()
void NetworkSyncManager::ReportHighScore (HighScore * hs, PlayerStageStats & pss)
References curProtocol, and NetProtocol::ReportHighScore().
Referenced by StageStats::FinalizeScores().
ReportNSSOnOff()
void NetworkSyncManager::ReportNSSOnOff (int i)
References curProtocol, and NetProtocol::ReportNSSOnOff().
ReportScore() [1/2]
void NetworkSyncManager::ReportScore (int playerID, int step, int score, int combo, float offset)
References curProtocol, and NetProtocol::ReportScore().
Referenced by ScoreKeeperNormal::HandleHoldScore(), ScoreKeeperNormal::HandleTapRowScore(), and ScoreKeeperNormal::HandleTapScore().
ReportScore() [2/2]
void NetworkSyncManager::ReportScore (int playerID, int step, int score, int combo, float offset, int numNotes)
References curProtocol, and NetProtocol::ReportScore().
ReportSongOver()
void NetworkSyncManager::ReportSongOver ()
References curProtocol, and NetProtocol::ReportSongOver().
Referenced by ScreenGameplay::~ScreenGameplay().
ReportStyle()
void NetworkSyncManager::ReportStyle ()
References curProtocol, and NetProtocol::ReportStyle().
Referenced by LuaFunction().
RequestRoomInfo()
void NetworkSyncManager::RequestRoomInfo (RString name)
References curProtocol, and NetProtocol::RequestRoomInfo().
Referenced by RoomInfoDisplay::RequestRoomInfo().
SelectUserSong()
void NetworkSyncManager::SelectUserSong ()
References curProtocol, GAMESTATE, m_EvalPlayerData, GameState::m_pCurSong, and NetProtocol::SelectUserSong().
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), and ScreenNetSelectMusic::SelectCurrent().
SendChat()
void NetworkSyncManager::SendChat (const RString & message, string tab = "", int type = 0)
References curProtocol, and NetProtocol::SendChat().
Referenced by ScreenNetSelectBase::Input().
StartRequest()
void NetworkSyncManager::StartRequest (short position)
References curProtocol, m_EvalPlayerData, and NetProtocol::StartRequest().
Referenced by ScreenGameplay::BeginScreen(), and ScreenGameplay::Init().
StartUp()
void NetworkSyncManager::StartUp () private
References autoConnectMultiplayer, GetCommandlineArgument(), and PostStartUp().
Referenced by NetworkSyncManager().
TranslateStepType()
SMOStepType NetworkSyncManager::TranslateStepType (int score)
References HNS_Held, HNS_LetGo, SMOST_AVOIDMINE, SMOST_HELD, SMOST_HITMINE, SMOST_LETGO, SMOST_MISS, SMOST_UNUSED, SMOST_W1, SMOST_W2, SMOST_W3, SMOST_W4, SMOST_W5, TapNoteScore_Invalid, TNS_AvoidMine, TNS_HitMine, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
Referenced by SMOProtocol::ReportScore().
Update()
void NetworkSyncManager::Update (float fDeltaTime)
References curProtocol, and NetProtocol::Update().
Referenced by GameLoop::RunGameLoop().
Member Data Documentation
chartkey
string NetworkSyncManager::chartkey
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ETTProtocol::LeaveRoom(), and PostStartUp().
chat
Chat NetworkSyncManager::chat
Referenced by PostStartUp(), and ETTProtocol::Update().
curProtocol
NetProtocol* NetworkSyncManager::curProtocol { nullptr }
Referenced by CloseConnection(), CreateNewRoom(), DisplayStartupStatus(), EnterRoom(), GetServerName(), GetServerVersion(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenNetRoom::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), IsETTP(), LeaveRoom(), Login(), Logout(), OffEval(), OffMusicSelect(), OffOptions(), OffRoomSelect(), OnEval(), OnMusicSelect(), OnOptions(), OnRoomSelect(), PostStartUp(), ReportHighScore(), ReportNSSOnOff(), ReportScore(), ReportSongOver(), ReportStyle(), RequestRoomInfo(), SelectUserSong(), SendChat(), StartRequest(), and Update().
difficulty
Difficulty NetworkSyncManager::difficulty
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ETTProtocol::LeaveRoom(), and PostStartUp().
ETTP
ETTProtocol NetworkSyncManager::ETTP
Referenced by CloseConnection(), and IsETTP().
fl_PlayerNames
vector<std::string> NetworkSyncManager::fl_PlayerNames
Referenced by LunaScreenNetSelectBase::GetFriendName(), LunaScreenNetSelectBase::GetFriendQty(), and SMOProtocol::ProcessInput().
fl_PlayerStates
vector<int> NetworkSyncManager::fl_PlayerStates
Referenced by LunaScreenNetSelectBase::GetFriendState(), and SMOProtocol::ProcessInput().
isSMOnline
bool NetworkSyncManager::isSMOnline
Referenced by CloseConnection(), SMOProtocol::Connect(), ETTProtocol::Connect(), StageStats::FinalizeScores(), NetworkSyncManager(), SMOProtocol::ProcessInput(), and ETTProtocol::Update().
LANserver
StepManiaLanServer* NetworkSyncManager::LANserver
Referenced by NetworkSyncManager().
loggedIn
bool NetworkSyncManager::loggedIn
Referenced by CloseConnection(), SMOProtocol::DealWithSMOnlinePack(), ScreenSMOnlineLogin::HandleScreenMessage(), NetworkSyncManager(), PostStartUp(), SMOProtocol::ProcessInput(), and ETTProtocol::Update().
loginResponse
string NetworkSyncManager::loginResponse
Referenced by CloseConnection(), ScreenSMOnlineLogin::HandleScreenMessage(), ETTProtocol::Login(), and ETTProtocol::Update().
m_ActivePlayer
vector<int> NetworkSyncManager::m_ActivePlayer
Referenced by LunaScreenNetSelectBase::GetUserState(), SMOProtocol::ProcessInput(), ETTProtocol::Update(), and ScreenNetSelectBase::UpdateUsers().
m_ActivePlayers
int NetworkSyncManager::m_ActivePlayers
Referenced by ScreenNetEvaluation::HandleScreenMessage(), NetworkSyncManager(), SMOProtocol::ProcessInput(), ScreenNetEvaluation::RedoUserTexts(), and ETTProtocol::Update().
m_combo
int NetworkSyncManager::m_combo private
m_EvalPlayerData
vector<EndOfGame_PlayerData> NetworkSyncManager::m_EvalPlayerData
Referenced by LunaScreenNetEvaluation::GetHighScore(), LunaScreenNetEvaluation::GetOptions(), ScreenNetEvaluation::HandleScreenMessage(), SMOProtocol::ProcessInput(), SelectUserSong(), StartRequest(), ETTProtocol::Update(), and ScreenNetEvaluation::UpdateStats().
m_iSelectMode
int NetworkSyncManager::m_iSelectMode
Referenced by LunaScreenNetSelectMusic::GetSelectionState(), ScreenNetSelectMusic::HandleScreenMessage(), SMOProtocol::ProcessInput(), ScreenNetSelectMusic::SelectCurrent(), and SMOProtocol::SelectUserSong().
m_playerID
int NetworkSyncManager::m_playerID private
m_playerLife
int NetworkSyncManager::m_playerLife
Referenced by SMOProtocol::ReportScore(), and ScreenGameplay::Update().
m_PlayerNames
vector<RString> NetworkSyncManager::m_PlayerNames
Referenced by ScreenNetEvaluation::HandleScreenMessage(), SMOProtocol::ProcessInput(), ETTProtocol::Update(), and ScreenNetSelectBase::UpdateUsers().
m_PlayerStatus
vector<int> NetworkSyncManager::m_PlayerStatus
Referenced by LunaScreenNetSelectBase::GetUserState(), SMOProtocol::ProcessInput(), ETTProtocol::Update(), and ScreenNetSelectBase::UpdateUsers().
m_Rooms
vector<RoomData> NetworkSyncManager::m_Rooms
Referenced by SMOProtocol::DealWithSMOnlinePack(), ETTProtocol::EnterRoom(), ScreenNetRoom::Init(), and ETTProtocol::Update().
m_sArtist
RString NetworkSyncManager::m_sArtist
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), PostStartUp(), SMOProtocol::ProcessInput(), ScreenNetSelectMusic::SelectCurrent(), SMOProtocol::SelectUserSong(), and ETTProtocol::SelectUserSong().
m_sChatText
RString NetworkSyncManager::m_sChatText
Referenced by CloseConnection(), ScreenNetSelectBase::HandleScreenMessage(), ScreenNetSelectBase::Init(), and SMOProtocol::ProcessInput().
m_score
int NetworkSyncManager::m_score private
m_Scoreboard
RString NetworkSyncManager::m_Scoreboard[NUM_NSScoreBoardColumn]
Referenced by ScreenGameplay::Init(), SMOProtocol::ProcessInput(), and ScreenGameplay::Update().
m_scoreboardchange
bool NetworkSyncManager::m_scoreboardchange[NUM_NSScoreBoardColumn]
Referenced by ChangedScoreboard(), and SMOProtocol::ProcessInput().
m_sFileHash
RString NetworkSyncManager::m_sFileHash
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), PostStartUp(), and SMOProtocol::ProcessInput().
m_sHash
int NetworkSyncManager::m_sHash
m_sMainTitle
RString NetworkSyncManager::m_sMainTitle
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), PostStartUp(), SMOProtocol::ProcessInput(), ScreenNetSelectMusic::SelectCurrent(), SMOProtocol::SelectUserSong(), and ETTProtocol::SelectUserSong().
m_sSubTitle
RString NetworkSyncManager::m_sSubTitle
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), PostStartUp(), SMOProtocol::ProcessInput(), ScreenNetSelectMusic::SelectCurrent(), SMOProtocol::SelectUserSong(), and ETTProtocol::SelectUserSong().
m_startupStatus
int NetworkSyncManager::m_startupStatus
Referenced by CloseConnection(), SMOProtocol::Connect(), DisplayStartupStatus(), NetworkSyncManager(), and PostStartUp().
m_step
int NetworkSyncManager::m_step private
m_vAllLANServers
vector<NetServerInfo> NetworkSyncManager::m_vAllLANServers
Referenced by GetListOfLANServers(), and SMOProtocol::Update().
m_WaitingChat
RString NetworkSyncManager::m_WaitingChat
meter
int NetworkSyncManager::meter
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ETTProtocol::LeaveRoom(), and PostStartUp().
rate
int NetworkSyncManager::rate
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), and PostStartUp().
SMOP
SMOProtocol NetworkSyncManager::SMOP
Referenced by CloseConnection(), and PostStartUp().
song
Song* NetworkSyncManager::song { nullptr }
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), PostStartUp(), ETTProtocol::SelectUserSong(), and ETTProtocol::Update().
steps
Steps* NetworkSyncManager::steps { nullptr }
Referenced by CloseConnection(), ETTProtocol::FindJsonChart(), ScreenNetSelectMusic::HandleScreenMessage(), ETTProtocol::LeaveRoom(), and PostStartUp().
useSMserver
bool NetworkSyncManager::useSMserver
Referenced by ScreenGameplay::BeginScreen(), CloseConnection(), ScreenNetworkOptions::Init(), ScreenGameplay::Init(), ScreenNetSelectBase::Input(), ScreenNetSelectMusic::Input(), ScreenNetworkOptions::MenuStart(), NetworkSyncManager(), PostStartUp(), SMOProtocol::ProcessInput(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), ScreenNetSelectMusic::SelectCurrent(), SMOProtocol::StartRequest(), ScreenGameplay::Update(), and SMOProtocol::Update().
The documentation for this class was generated from the following files:
NetworkSyncManager.h
NetworkSyncManager.cpp