Etterna: FileTransfer Class Reference
FileTransfer Class Reference
#include <FileDownload.h>
Public Member Functions
FileTransfer ()
~FileTransfer ()
void StartDownload (const RString &sURL, const RString &sDestFile)
void StartUpload (const RString &sURL, const RString &sSrcFile, const RString &sDestFile)
void Cancel ()
RString Update (float fDeltaTime)
bool IsFinished () const
void Finish ()
int GetResponseCode () const
RString GetResponse () const
RString GetStatus () const
Private Types
enum TransferType { download, upload }
Private Member Functions
void StartTransfer (TransferType type, const RString &sURL, const RString &sSrcFile, const RString &sDestFile)
void HTTPUpdate ()
bool ParseHTTPAddress (const RString &URL, RString &Proto, RString &Server, int &Port, RString &Addy)
void UpdateProgress ()
Private Attributes
int m_iPackagesPos
int m_iLinksPos
int m_iDLorLST
bool m_bIsDownloading
float m_fLastUpdate
long m_bytesLastUpdate
RString m_sStatus
EzSockets m_wSocket
bool m_bGotHeader
RageFile m_fOutputFile
RString m_sEndName
bool m_bSavingFile
RString m_sBaseAddress
long m_iTotalBytes
long m_iDownloaded
long m_iResponseCode
RString m_sResponseName
RString m_sBUFFER
bool m_bFinished
Member Enumeration Documentation
TransferType
enum FileTransfer::TransferType private
Enumerator
download
upload
Constructor & Destructor Documentation
FileTransfer()
FileTransfer::FileTransfer ()
References RageFile::Close(), m_bFinished, m_bIsDownloading, m_fLastUpdate, m_fOutputFile, m_iDownloaded, m_iLinksPos, m_iPackagesPos, m_iTotalBytes, m_sStatus, RageFile::Open(), UpdateProgress(), and RageFile::WRITE.
~FileTransfer()
FileTransfer::~FileTransfer ()
References RageFile::Close(), and m_fOutputFile.
Member Function Documentation
Cancel()
void FileTransfer::Cancel ()
References RageFile::Close(), EzSockets::close(), FILEMAN, m_bGotHeader, m_bIsDownloading, m_fOutputFile, m_iDownloaded, m_sBUFFER, m_sEndName, m_sStatus, m_wSocket, and RageFileManager::Remove().
Finish()
void FileTransfer::Finish ()
References IsFinished(), and Update().
GetResponse()
RString FileTransfer::GetResponse () const inline
References m_sBUFFER.
GetResponseCode()
int FileTransfer::GetResponseCode () const inline
References m_iResponseCode.
GetStatus()
RString FileTransfer::GetStatus () const inline
References m_sStatus.
HTTPUpdate()
void FileTransfer::HTTPUpdate () private
References RageFile::Close(), EzSockets::close(), FILEMAN, FindEndOfHeaders(), RageFile::Flush(), RageFileManager::FlushDirCache(), RageFile::GetRealPath(), m_bFinished, m_bGotHeader, m_bIsDownloading, m_bSavingFile, m_fOutputFile, m_iDownloaded, m_iResponseCode, m_iTotalBytes, m_sBUFFER, m_sResponseName, m_sStatus, m_wSocket, EzSockets::ReadData(), EzSockets::skDISCONNECTED, EzSockets::skERROR, ssprintf(), EzSockets::state, StringToInt(), and RageFile::Write().
Referenced by Update().
IsFinished()
bool FileTransfer::IsFinished () const inline
References m_bFinished.
Referenced by Finish().
ParseHTTPAddress()
bool FileTransfer::ParseHTTPAddress (const RString & URL, RString & Proto, RString & Server, int & Port, RString & Addy) private
References ASSERT, Regex::Compare(), and StringToInt().
Referenced by StartTransfer().
StartDownload()
void FileTransfer::StartDownload (const RString & sURL, const RString & sDestFile)
References download, and StartTransfer().
StartTransfer()
void FileTransfer::StartTransfer (TransferType type, const RString & sURL, const RString & sSrcFile, const RString & sDestFile) private
References Basename(), EzSockets::blocking, EzSockets::close(), EzSockets::connect(), EzSockets::create(), Dirname(), download, f, FAIL_M, FOREACH_CONST, Preference< T >::Get(), RageFile::GetError(), RageFile::GetFileSize(), m_bFinished, m_bGotHeader, m_bIsDownloading, m_bSavingFile, m_fOutputFile, m_sBaseAddress, m_sBUFFER, m_sEndName, m_sStatus, m_wSocket, RageFile::Open(), ParseHTTPAddress(), RageFile::Read(), StdString::CStdStr< CT >::Right(), EzSockets::SendData(), ssprintf(), RageFile::STREAMED, UpdateProgress(), upload, URLEncode(), and RageFile::WRITE.
Referenced by StartDownload(), and StartUpload().
StartUpload()
void FileTransfer::StartUpload (const RString & sURL, const RString & sSrcFile, const RString & sDestFile)
References StartTransfer(), and upload.
Update()
RString FileTransfer::Update (float fDeltaTime)
References HTTPUpdate(), m_bGotHeader, m_bIsDownloading, m_bytesLastUpdate, m_fLastUpdate, m_iDownloaded, m_sStatus, ssprintf(), and UpdateProgress().
Referenced by Finish().
UpdateProgress()
void FileTransfer::UpdateProgress () private
Referenced by FileTransfer(), StartTransfer(), and Update().
Member Data Documentation
m_bFinished
bool FileTransfer::m_bFinished private
Referenced by FileTransfer(), HTTPUpdate(), IsFinished(), and StartTransfer().
m_bGotHeader
bool FileTransfer::m_bGotHeader private
Referenced by Cancel(), HTTPUpdate(), StartTransfer(), and Update().
m_bIsDownloading
bool FileTransfer::m_bIsDownloading private
Referenced by Cancel(), FileTransfer(), HTTPUpdate(), StartTransfer(), and Update().
m_bSavingFile
bool FileTransfer::m_bSavingFile private
Referenced by HTTPUpdate(), and StartTransfer().
m_bytesLastUpdate
long FileTransfer::m_bytesLastUpdate private
Referenced by Update().
m_fLastUpdate
float FileTransfer::m_fLastUpdate private
Referenced by FileTransfer(), and Update().
m_fOutputFile
RageFile FileTransfer::m_fOutputFile private
Referenced by Cancel(), FileTransfer(), HTTPUpdate(), StartTransfer(), and ~FileTransfer().
m_iDLorLST
int FileTransfer::m_iDLorLST private
m_iDownloaded
long FileTransfer::m_iDownloaded private
Referenced by Cancel(), FileTransfer(), HTTPUpdate(), and Update().
m_iLinksPos
int FileTransfer::m_iLinksPos private
Referenced by FileTransfer().
m_iPackagesPos
int FileTransfer::m_iPackagesPos private
Referenced by FileTransfer().
m_iResponseCode
long FileTransfer::m_iResponseCode private
Referenced by GetResponseCode(), and HTTPUpdate().
m_iTotalBytes
long FileTransfer::m_iTotalBytes private
Referenced by FileTransfer(), and HTTPUpdate().
m_sBaseAddress
RString FileTransfer::m_sBaseAddress private
Referenced by StartTransfer().
m_sBUFFER
RString FileTransfer::m_sBUFFER private
Referenced by Cancel(), GetResponse(), HTTPUpdate(), and StartTransfer().
m_sEndName
RString FileTransfer::m_sEndName private
Referenced by Cancel(), and StartTransfer().
m_sResponseName
RString FileTransfer::m_sResponseName private
Referenced by HTTPUpdate().
m_sStatus
RString FileTransfer::m_sStatus private
Referenced by Cancel(), FileTransfer(), GetStatus(), HTTPUpdate(), StartTransfer(), and Update().
m_wSocket
EzSockets FileTransfer::m_wSocket private
Referenced by Cancel(), HTTPUpdate(), and StartTransfer().
The documentation for this class was generated from the following files:
FileDownload.h
FileDownload.cpp