Etterna: RageFileDriverTimeout.cpp File Reference
RageFileDriverTimeout.cpp File Reference
#include "RageFileDriverTimeout.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "RageUtil_FileDB.h"
#include "RageUtil_WorkerThread.h"
#include "global.h"
#include <cerrno>
Classes
class ThreadedFileWorker
class RageFileObjTimeout
class TimedFilenameDB
struct FileDriverEntry_Timeout
Enumerations
enum ThreadRequest {
REQ_OPEN, REQ_CLOSE, REQ_GET_FILE_SIZE, REQ_GET_FD,
REQ_READ, REQ_WRITE, REQ_SEEK, REQ_FLUSH,
REQ_COPY, REQ_POPULATE_FILE_SET, REQ_FLUSH_DIR_CACHE, REQ_MOVE,
REQ_REMOVE
}
Variables
static vector< ThreadedFileWorker * > g_apWorkers
static RageMutex g_apWorkersMutex ("WorkersMutex")
FileDriverEntry_Timeout g_RegisterDriver
Enumeration Type Documentation
ThreadRequest
enum ThreadRequest
Enumerator
REQ_OPEN
REQ_CLOSE
REQ_GET_FILE_SIZE
REQ_GET_FD
REQ_READ
REQ_WRITE
REQ_SEEK
REQ_FLUSH
REQ_COPY
REQ_POPULATE_FILE_SET
REQ_FLUSH_DIR_CACHE
REQ_MOVE
REQ_REMOVE
Variable Documentation
g_apWorkers
vector<ThreadedFileWorker*> g_apWorkers static
Referenced by RageFileDriverTimeout::SetTimeout(), ThreadedFileWorker::ThreadedFileWorker(), and ThreadedFileWorker::~ThreadedFileWorker().
g_apWorkersMutex
RageMutex g_apWorkersMutex("WorkersMutex") static
Referenced by RageFileDriverTimeout::SetTimeout(), ThreadedFileWorker::ThreadedFileWorker(), and ThreadedFileWorker::~ThreadedFileWorker().
g_RegisterDriver
FileDriverEntry_Timeout g_RegisterDriver static