Etterna: ArchHooks_Unix.cpp File Reference
ArchHooks_Unix.cpp File Reference
#include "ArchHooks_Unix.h"
#include "LocalizedString.h"
#include "ProductInfo.h"
#include "RageLog.h"
#include "RageThreads.h"
#include "RageUtil.h"
#include "SpecialFiles.h"
#include "archutils/Common/PthreadHelpers.h"
#include "archutils/Unix/AssertionHandler.h"
#include "archutils/Unix/EmergencyShutdown.h"
#include "archutils/Unix/GetSysInfo.h"
#include "archutils/Unix/SignalHandler.h"
#include "global.h"
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "RageFileManager.h"
#include <sys/stat.h>
Macros
#define _CS_GNU_LIBC_VERSION 2
Functions
static bool IsFatalSignal (int signal)
static bool DoCleanShutdown (int signal, siginfo_t *si, const ucontext_t *uc)
static bool EmergencyShutdown (int signal, siginfo_t *si, const ucontext_t *uc)
static RString LibcVersion ()
Variables
static LocalizedString COULDNT_FIND_SONGS ("ArchHooks_Unix", "Couldn't find 'Songs'")
Macro Definition Documentation
_CS_GNU_LIBC_VERSION
#define _CS_GNU_LIBC_VERSION 2
Referenced by LibcVersion().
Function Documentation
DoCleanShutdown()
static bool DoCleanShutdown (int signal, siginfo_t * si, const ucontext_t * uc) static
References IsFatalSignal(), and ArchHooks::SetUserQuit().
Referenced by ArchHooks_Unix::Init().
EmergencyShutdown()
static bool EmergencyShutdown (int signal, siginfo_t * si, const ucontext_t * uc) static
References DoEmergencyShutdown(), and IsFatalSignal().
Referenced by ArchHooks_Unix::Init().
IsFatalSignal()
static bool IsFatalSignal (int signal) static
Referenced by DoCleanShutdown(), and EmergencyShutdown().
LibcVersion()
static RString LibcVersion () static
References _CS_GNU_LIBC_VERSION.
Referenced by ArchHooks_Unix::DumpDebugInfo().
Variable Documentation
COULDNT_FIND_SONGS
LocalizedString COULDNT_FIND_SONGS("ArchHooks_Unix", "Couldn't find 'Songs'") static