Etterna: Enum Namespace Reference
Enum Namespace Reference
Lua helpers for Enumerators.
Functions
template<typename T >
static T Check (lua_State *L, int iPos, bool bAllowInvalid=false, bool bAllowAnything=false)
template<typename T >
static void Push (lua_State *L, T iVal)
void SetMetatable (lua_State *L, LuaReference &EnumTable, LuaReference &EnumIndexTable, const char *szName)
Detailed Description
Lua helpers for Enumerators.
Function Documentation
Check()
template<typename T > static T Enum::Check (lua_State * L, int iPos, bool bAllowInvalid = false, bool bAllowAnything = false) static
References CheckEnum(), and T.
Push()
template<typename T > static void Enum::Push (lua_State * L, T iVal) static
References LuaReference::PushSelf().
Referenced by NoteField::DidHoldNote(), NoteField::DidTapNote(), LunaStatsManager::GetBestFinalGrade(), LunaActorMultiVertex::GetCurrDrawMode(), LunaActorMultiVertex::GetDestDrawMode(), ScreenGameplay::Init(), Screen::PassInputToLua(), and NoteField::Step().
SetMetatable()
void Enum::SetMetatable (lua_State * L, LuaReference & EnumTable, LuaReference & EnumIndexTable, const char * szName)
References PushEnumMethodTable(), LuaReference::PushSelf(), and LuaHelpers::PushValueFunc().