Etterna: InputScheme Class Reference
InputScheme Class Reference
#include <InputMapper.h>
Classes
struct GameButtonInfo
Public Member Functions
GameButton ButtonNameToIndex (const RString &sButtonName) const
GameButton GameButtonToMenuButton (GameButton gb) const
void MenuButtonToGameInputs (GameButton MenuI, PlayerNumber pn, vector< GameInput > &GameIout) const
void MenuButtonToGameButtons (GameButton MenuI, vector< GameButton > &aGameButtons) const
const GameButtonInfo * GetGameButtonInfo (GameButton gb) const
const char * GetGameButtonName (GameButton gb) const
Public Attributes
const char * m_szName
int m_iButtonsPerController
GameButtonInfo m_GameButtonInfo [NUM_GameButton]
const AutoMappings * m_pAutoMappings
Member Function Documentation
ButtonNameToIndex()
GameButton InputScheme::ButtonNameToIndex (const RString & sButtonName) const
References GameButton_Invalid, GetGameButtonName(), and m_iButtonsPerController.
Referenced by ScreenSelectMusic::Init(), and InputQueueCode::Load().
GameButtonToMenuButton()
GameButton InputScheme::GameButtonToMenuButton (GameButton gb) const
References GAME_BUTTON_NEXT, GameButton_Invalid, GetGameButtonInfo(), PrefsManager::m_bOnlyDedicatedMenuButtons, InputScheme::GameButtonInfo::m_SecondaryMenuButton, and PREFSMAN.
Referenced by InputMapper::GameButtonToMenuButton(), ScreenMapControllers::Init(), and InputList::Update().
GetGameButtonInfo()
const InputScheme::GameButtonInfo * InputScheme::GetGameButtonInfo (GameButton gb) const
References ARRAYLEN, COMPILE_ASSERT, GAME_BUTTON_NEXT, and m_GameButtonInfo.
Referenced by GameButtonToMenuButton(), GetGameButtonName(), and MenuButtonToGameButtons().
GetGameButtonName()
const char * InputScheme::GetGameButtonName (GameButton gb) const
References GameButton_Invalid, GetGameButtonInfo(), and InputScheme::GameButtonInfo::m_szName.
Referenced by ButtonNameToIndex(), Style::ColToButtonName(), and GameButtonToString().
MenuButtonToGameButtons()
void InputScheme::MenuButtonToGameButtons (GameButton MenuI, vector< GameButton > & aGameButtons) const
References ASSERT, FOREACH_ENUM, GAME_BUTTON_NEXT, GameButton_Invalid, GetGameButtonInfo(), PrefsManager::m_bOnlyDedicatedMenuButtons, InputScheme::GameButtonInfo::m_SecondaryMenuButton, and PREFSMAN.
Referenced by MenuButtonToGameInputs().
MenuButtonToGameInputs()
void InputScheme::MenuButtonToGameInputs (GameButton MenuI, PlayerNumber pn, vector< GameInput > & GameIout) const
References ASSERT, FOREACH, GameButton_Invalid, GameController_1, GameController_2, MenuButtonToGameButtons(), and PLAYER_INVALID.
Referenced by InputMapper::CheckButtonAndAddToReason(), and InputMapper::MenuToGame().
Member Data Documentation
m_GameButtonInfo
GameButtonInfo InputScheme::m_GameButtonInfo[NUM_GameButton]
Referenced by GetGameButtonInfo().
m_iButtonsPerController
int InputScheme::m_iButtonsPerController
Referenced by ButtonNameToIndex(), and Style::StyleInputToGameInput().
m_pAutoMappings
const AutoMappings* InputScheme::m_pAutoMappings
Referenced by InputMapper::AddDefaultMappingsForCurrentGameIfUnmapped().
m_szName
const char* InputScheme::m_szName
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), InputMappings::ReadMappings(), and InputMappings::WriteMappings().
The documentation for this class was generated from the following files:
InputMapper.h
InputMapper.cpp