Etterna: XmlFileUtil Namespace Reference
XmlFileUtil Namespace Reference
A little graphic to the left of the song's text banner in the MusicWheel.
Functions
bool LoadFromFileShowErrors (XNode &xml, const RString &sFile)
bool LoadFromFileShowErrors (XNode &xml, RageFileBasic &f)
void Load (XNode *pNode, const RString &sXml, RString &sErrorOut)
bool GetXML (const XNode *pNode, RageFileBasic &f, bool bWriteTabs=true)
RString GetXML (const XNode *pNode)
bool SaveToFile (const XNode *pNode, const RString &sFile, const RString &sStylesheet="", bool bWriteTabs=true)
bool SaveToFile (const XNode *pNode, RageFileBasic &f, const RString &sStylesheet="", bool bWriteTabs=true)
void AnnotateXNodeTree (XNode *pNode, const RString &sFile)
void CompileXNodeTree (XNode *pNode, const RString &sFile)
XNode * XNodeFromTable (lua_State *L)
void MergeIniUnder (XNode *pFrom, XNode *pTo)
Detailed Description
A little graphic to the left of the song's text banner in the MusicWheel.
This is designed to help work with XML files.
Function Documentation
AnnotateXNodeTree()
void XmlFileUtil::AnnotateXNodeTree (XNode * pNode, const RString & sFile)
References XNode::AppendAttr(), Dirname(), and FOREACH_Child.
Referenced by ActorUtil::MakeActor().
CompileXNodeTree()
void XmlFileUtil::CompileXNodeTree (XNode * pNode, const RString & sFile)
References FOREACH_Attr, FOREACH_Child, LuaManager::Get(), LUA, and LuaManager::Release().
Referenced by ActorUtil::MakeActor().
GetXML() [1/2]
bool XmlFileUtil::GetXML (const XNode * pNode, RageFileBasic & f, bool bWriteTabs = true)
References InitEntities().
Referenced by BackgroundImpl::Layer::UpdateCurBGChange().
GetXML() [2/2]
RString XmlFileUtil::GetXML (const XNode * pNode)
References f, RageFileObjMem::GetString(), and InitEntities().
Load()
void XmlFileUtil::Load (XNode * pNode, const RString & sXml, RString & sErrorOut)
References InitEntities().
Referenced by LoadFromFileShowErrors(), and LunaScreenTextEntry::LunaScreenTextEntry().
LoadFromFileShowErrors() [1/2]
bool XmlFileUtil::LoadFromFileShowErrors (XNode & xml, const RString & sFile)
References f, RageFile::GetError(), JsonUtil::LoadFromFileShowErrors(), RageFile::Open(), RageFile::READ, LuaHelpers::ReportScriptError(), LuaHelpers::ReportScriptErrorFmt(), and ssprintf().
Referenced by convert_xml_file(), BackgroundImpl::Init(), TitleSubst::Load(), XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), XMLProfile::LoadStatsXmlForConversion(), and ActorUtil::MakeActor().
LoadFromFileShowErrors() [2/2]
bool XmlFileUtil::LoadFromFileShowErrors (XNode & xml, RageFileBasic & f)
References RageFileBasic::GetError(), Load(), RageFileBasic::Read(), LuaHelpers::ReportScriptError(), and ssprintf().
MergeIniUnder()
void XmlFileUtil::MergeIniUnder (XNode * pFrom, XNode * pTo)
References XNode::AppendAttrFrom(), XNode::AppendChild(), FOREACH_Attr, XNode::GetChild(), XNode::GetChildrenBegin(), XNode::GetChildrenEnd(), XNode::GetName(), and XNode::RemoveChild().
Referenced by NoteSkinManager::LoadNoteSkinDataRecursive(), and ThemeManager::LoadThemeMetrics().
SaveToFile() [1/2]
bool XmlFileUtil::SaveToFile (const XNode * pNode, const RString & sFile, const RString & sStylesheet = "", bool bWriteTabs = true)
References f, RageFile::GetError(), RageFile::Open(), LuaHelpers::ReportScriptErrorFmt(), and RageFile::WRITE.
Referenced by LuaInformation(), XMLProfile::SaveEttXmlToDir(), ScreenGameplay::SaveReplay(), and XMLProfile::SaveStatsXmlToDir().
SaveToFile() [2/2]
bool XmlFileUtil::SaveToFile (const XNode * pNode, RageFileBasic & f, const RString & sStylesheet = "", bool bWriteTabs = true)
References RageFileBasic::Flush(), InitEntities(), and RageFileBasic::PutLine().
XNodeFromTable()
XNode * XmlFileUtil::XNodeFromTable (lua_State * L)
References LuaReference::SetFromStack().
Referenced by NoteSkinManager::LoadActor(), XMLProfile::SaveEttGeneralDataCreateNode(), and XMLProfile::SaveGeneralDataCreateNode().