Etterna: RageSurface_Load_GIF.h File Reference
RageSurface_Load_GIF.h File Reference
#include "global.h"
#include "RageSurface_Load.h"
Functions
RageSurfaceUtils::OpenResult RageSurface_Load_GIF (const RString &sPath, RageSurface *&ret, bool bHeaderOnly, RString &error)
Function Documentation
RageSurface_Load_GIF()
RageSurfaceUtils::OpenResult RageSurface_Load_GIF (const RString & sPath, RageSurface *& ret, bool bHeaderOnly, RString & error)
References RageSurfaceColor::a, BitSet, RageSurfacePalette::colors, f, RageSurface::fmt, GetDataBlock(), RageFile::GetError(), INTERLACE, label, LM_to_uint, LOCALCOLORMAP, MAXCOLORMAPSIZE, RageFile::Open(), RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, RageSurfaceFormat::palette, ReadImage(), ReadOK, ReadPalette(), and ssprintf().
Referenced by TryOpenFile().