Etterna: MovieTexture.cpp File Reference
MovieTexture.cpp File Reference
#include "MovieTexture.h"
#include "Foreach.h"
#include "LocalizedString.h"
#include "MovieTexture_Null.h"
#include "PrefsManager.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "arch/arch_default.h"
#include "global.h"
Macros
#define HANDLE_ERROR(x)
Functions
void ForceToAscii (RString &str)
static void DumpAVIDebugInfo (const RString &fn)
Variables
static Preference< RString > g_sMovieDrivers ("MovieDrivers", "")
static LocalizedString MOVIE_DRIVERS_EMPTY ("Arch", "Movie Drivers cannot be empty.")
static LocalizedString COULDNT_CREATE_MOVIE_DRIVER ("Arch", "Couldn't create a movie driver.")
Macro Definition Documentation
HANDLE_ERROR
#define HANDLE_ERROR (x)
Value:
{                                                                          \
        LOG->Warn("Error reading %s: %s", fn.c_str(), x);                      \
        handler = type = "";                                                   \
        return false;                                                          \
    }
Referenced by RageMovieTexture::GetFourCC().
Function Documentation
DumpAVIDebugInfo()
static void DumpAVIDebugInfo (const RString & fn) static
References RageMovieTexture::GetFourCC(), handler, LOG, and RageLog::Trace().
Referenced by RageMovieTexture::Create().
ForceToAscii()
void ForceToAscii (RString & str)
Referenced by RageMovieTexture::GetFourCC().
Variable Documentation
COULDNT_CREATE_MOVIE_DRIVER
LocalizedString COULDNT_CREATE_MOVIE_DRIVER("Arch", "Couldn't create a movie driver.") static
Referenced by RageMovieTexture::Create().
g_sMovieDrivers
Preference<RString> g_sMovieDrivers("MovieDrivers", "") static
Referenced by RageMovieTexture::Create().
MOVIE_DRIVERS_EMPTY
LocalizedString MOVIE_DRIVERS_EMPTY("Arch", "Movie Drivers cannot be empty.") static
Referenced by RageMovieTexture::Create().