Etterna: RageSoundReader_FileReader Class Reference
RageSoundReader_FileReader Class Reference abstract
#include <RageSoundReader_FileReader.h>
Public Types
enum OpenResult { OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT = 1, OPEN_FATAL_ERROR = 2 }
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Public Member Functions
virtual OpenResult Open (RageFileBasic *pFile)=0
float GetStreamToSourceRatio () const override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual int GetLength () const =0
virtual int GetLength_Fast () const
virtual int SetPosition (int iFrame)=0
virtual int Read (float *pBuf, int iFrames)=0
virtual ~RageSoundReader ()=default
virtual RageSoundReader * Copy () const =0
virtual int GetSampleRate () const =0
virtual unsigned GetNumChannels () const =0
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
virtual int GetNextSourceFrame () const =0
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Static Public Member Functions
static RageSoundReader_FileReader * OpenFile (const RString &filename, RString &error, bool *pPrebuffer=NULL)
Protected Member Functions
void SetError (const RString &sError) const
Protected Attributes
HiddenPtr< RageFileBasic > m_pFile
Static Private Member Functions
static RageSoundReader_FileReader * TryOpenFile (RageFileBasic *pFile, RString &error, const RString &format, bool &bKeepTrying)
Private Attributes
RString m_sError
Member Enumeration Documentation
OpenResult
enum RageSoundReader_FileReader::OpenResult
Enumerator
OPEN_OK
OPEN_UNKNOWN_FILE_FORMAT
OPEN_FATAL_ERROR
Member Function Documentation
GetError()
RString RageSoundReader_FileReader::GetError () const inline override virtual
Implements RageSoundReader.
References m_sError.
Referenced by RageSoundReader_MP3::Open(), and TryOpenFile().
GetStreamToSourceRatio()
float RageSoundReader_FileReader::GetStreamToSourceRatio () const inline override virtual
Implements RageSoundReader.
Open()
virtual OpenResult RageSoundReader_FileReader::Open (RageFileBasic * pFile) pure virtual
Implemented in RageSoundReader_MP3, RageSoundReader_WAV, and RageSoundReader_Vorbisfile.
Referenced by TryOpenFile().
OpenFile()
RageSoundReader_FileReader * RageSoundReader_FileReader::OpenFile (const RString & filename, RString & error, bool * pPrebuffer = NULL) static
References RageFileBasic::Copy(), FileCopy(), FT_Sound, RageFileBasic::GetDisplayPath(), GetExtension(), RageFileBasic::GetFileSize(), ActorUtil::GetTypeExtensionList(), LOG, StdString::CStdStr< CT >::MakeLower(), RageFileBasic::Seek(), TryOpenFile(), and RageLog::UserLog().
Referenced by RageSound::Load(), RageSoundReader_Chain::LoadSound(), AutoKeysounds::LoadTracks(), LuaFunc_get_music_file_length(), and Song::TidyUpData().
SetError()
void RageSoundReader_FileReader::SetError (const RString & sError) const inline protected
References m_sError.
Referenced by RageSoundReader_MP3::do_mad_frame_decode(), RageSoundReader_MP3::fill_buffer(), RageSoundReader_MP3::GetLengthInternal(), RageSoundReader_Vorbisfile::Open(), RageSoundReader_WAV::Open(), RageSoundReader_MP3::Open(), RageSoundReader_Vorbisfile::Read(), RageSoundReader_MP3::seek_stream_to_byte(), and RageSoundReader_Vorbisfile::SetPosition().
TryOpenFile()
RageSoundReader_FileReader * RageSoundReader_FileReader::TryOpenFile (RageFileBasic * pFile, RString & error, const RString & format, bool & bKeepTrying) static private
References StdString::CStdStr< CT >::CompareNoCase(), GetError(), LOG, Open(), OPEN_FATAL_ERROR, OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT, and RageLog::Trace().
Referenced by OpenFile().
Member Data Documentation
m_pFile
HiddenPtr<RageFileBasic> RageSoundReader_FileReader::m_pFile protected
Referenced by RageSoundReader_Vorbisfile::Copy(), RageSoundReader_WAV::Copy(), RageSoundReader_MP3::Copy(), RageSoundReader_MP3::fill_buffer(), RageSoundReader_MP3::MADLIB_rewind(), RageSoundReader_Vorbisfile::Open(), RageSoundReader_WAV::Open(), RageSoundReader_MP3::Open(), and RageSoundReader_MP3::seek_stream_to_byte().
m_sError
RString RageSoundReader_FileReader::m_sError mutable private
Referenced by GetError(), and SetError().
The documentation for this class was generated from the following files:
RageSoundReader_FileReader.h
RageSoundReader_FileReader.cpp