Etterna: actor_template_t Struct Reference
actor_template_t Struct Reference
Public Member Functions
void make_space_for_frame (int id)
void store_cmd (RString const &cmd_name, RString const &full_cmd)
void store_field (RString const &field_name, RString const &value, bool cmd_convert, RString const &pref="", RString const &suf="")
void store_field (RString const &field_name, XNodeValue const *value, bool cmd_convert, RString const &pref="", RString const &suf="")
void rename_field (RString const &old_name, RString const &new_name)
RString get_field (RString const &field_name)
void load_frames_from_file (RString const &fname, RString const &rel_path)
void load_model_from_file (RString const &fname, RString const &rel_path)
void load_node (XNode const &node, RString const &dirname, condition_set_t &conditions)
void output_to_file (RageFile *file, RString const &indent)
Public Attributes
RString type
field_cont_t fields
RString condition
RString name
vector< frame_t > frames
vector< actor_template_t > children
RString x
RString y
Member Function Documentation
get_field()
RString actor_template_t::get_field (RString const & field_name)
References fields.
Referenced by output_to_file().
load_frames_from_file()
void actor_template_t::load_frames_from_file (RString const & fname, RString const & rel_path)
References FOREACH_CONST_Attr, frames, XNode::GetChild(), IniFile::GetError(), StdString::CStdStr< CT >::Left(), LOG, make_space_for_frame(), IniFile::ReadFile(), store_field(), StringToInt(), and RageLog::Trace().
Referenced by load_node().
load_model_from_file()
void actor_template_t::load_model_from_file (RString const & fname, RString const & rel_path)
References FOREACH_CONST_Attr, XNode::GetChild(), IniFile::GetError(), LOG, IniFile::ReadFile(), store_field(), and RageLog::Trace().
Referenced by load_node().
load_node()
void actor_template_t::load_node (XNode const & node, RString const & dirname, condition_set_t & conditions)
References add_extension_to_relative_path_from_found_file(), children, condition, Dirname(), fields, FILEMAN, FOREACH_CONST_Attr, FOREACH_CONST_Child, FT_Bitmap, FT_Ini, FT_Lua, FT_Model, FT_Movie, FT_Sound, FT_Sprite, FT_Xml, XNode::GetChild(), RageFileManager::GetDirListing(), GetExtension(), ActorUtil::GetFileType(), XNode::GetName(), RageFileManager::IsADirectory(), load_frames_from_file(), load_model_from_file(), load_node(), name, rename_field(), set_type, SetExtension(), store_field(), type, unique_name(), x, and y.
Referenced by convert_xml_file(), and load_node().
make_space_for_frame()
void actor_template_t::make_space_for_frame (int id)
References frames.
Referenced by load_frames_from_file().
output_to_file()
void actor_template_t::output_to_file (RageFile * file, RString const & indent)
References children, condition, fields, FloatToString(), frames, get_field(), IntToString(), name, type, unique_name(), and RageFile::Write().
Referenced by convert_xml_file().
rename_field()
void actor_template_t::rename_field (RString const & old_name, RString const & new_name)
References fields.
Referenced by load_node().
store_cmd()
void actor_template_t::store_cmd (RString const & cmd_name, RString const & full_cmd)
References convert_lua_chunk(), fields, Rage::join(), StdString::CStdStr< CT >::Left(), StdString::CStdStr< CT >::Right(), split(), TWEEN_QUEUE_MAX, and unique_name().
Referenced by store_field().
store_field() [1/2]
void actor_template_t::store_field (RString const & field_name, RString const & value, bool cmd_convert, RString const & pref = "", RString const & suf = "")
References fields, StdString::CStdStr< CT >::Left(), StdString::CStdStr< CT >::MakeLower(), StdString::CStdStr< CT >::Right(), and store_cmd().
Referenced by load_frames_from_file(), load_model_from_file(), load_node(), and store_field().
store_field() [2/2]
void actor_template_t::store_field (RString const & field_name, XNodeValue const * value, bool cmd_convert, RString const & pref = "", RString const & suf = "")
References XNodeValue::GetValue(), and store_field().
Member Data Documentation
children
vector<actor_template_t> actor_template_t::children
Referenced by load_node(), and output_to_file().
condition
RString actor_template_t::condition
Referenced by load_node(), and output_to_file().
fields
field_cont_t actor_template_t::fields
Referenced by get_field(), load_node(), output_to_file(), rename_field(), store_cmd(), and store_field().
frames
vector<frame_t> actor_template_t::frames
Referenced by load_frames_from_file(), make_space_for_frame(), and output_to_file().
name
RString actor_template_t::name
Referenced by load_node(), and output_to_file().
type
RString actor_template_t::type
Referenced by load_node(), and output_to_file().
x
RString actor_template_t::x
Referenced by load_node().
y
RString actor_template_t::y
Referenced by load_node().
The documentation for this struct was generated from the following file:
XmlToLua.cpp