Etterna: OptionRowHandlerListCharacters Class Reference
OptionRowHandlerListCharacters Class Reference
Private Member Functions
bool LoadInternal (const Commands &) override
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Public Member Functions inherited from OptionRowHandlerList
OptionRowHandlerList ()
void Init () override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
int GetDefaultOption () const override
void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const override
RString GetScreen (int iChoice) const override
ReloadChanged Reload () override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes inherited from OptionRowHandlerList
vector< GameCommand > m_aListEntries
GameCommand m_Default
bool m_bUseModNameForIcon
vector< RString > m_vsBroadcastOnExport
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Member Function Documentation
LoadInternal()
bool OptionRowHandlerListCharacters::LoadInternal (const Commands &) inline override private virtual
Reimplemented from OptionRowHandlerList.
References CHARMAN, CharacterManager::GetCharacters(), CharacterManager::GetDefaultCharacter(), Character::GetDisplayName(), OptionRowHandlerList::m_aListEntries, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowHandlerList::m_Default, OptionRowDefinition::m_iDefault, GameCommand::m_pCharacter, OptionRowDefinition::m_sName, OptionRowDefinition::m_vsChoices, StdString::CStdStr< CT >::MakeUpper(), and OFF.
The documentation for this class was generated from the following file:
OptionRowHandler.cpp