Etterna: LoadingWindow Class Reference
LoadingWindow Class Reference abstract
Opens and displays the loading banner.
#include <LoadingWindow.h>
Public Member Functions
virtual RString Init ()
virtual ~LoadingWindow ()=default
virtual void SetText (const RString &str)=0
virtual void SetIcon (const RageSurface *pIcon)
virtual void SetSplash (const RageSurface *pSplash)
virtual void SetProgress (const int progress)
virtual void SetTotalWork (const int totalWork)
virtual void SetIndeterminate (bool indeterminate)
Static Public Member Functions
static LoadingWindow * Create ()
Protected Attributes
int m_progress
int m_totalWork
bool m_indeterminate
Detailed Description
Opens and displays the loading banner.
Constructor & Destructor Documentation
~LoadingWindow()
virtual LoadingWindow::~LoadingWindow () virtual default
Member Function Documentation
Create()
LoadingWindow * LoadingWindow::Create () static
References ASSERT, RageLog::Info(), Init(), LOG, PrefsManager::m_bShowLoadingWindow, PREFSMAN, SAFE_DELETE, SetIndeterminate(), and split().
Referenced by sm_main().
Init()
virtual RString LoadingWindow::Init () inline virtual
Reimplemented in LoadingWindow_Gtk.
Referenced by Create().
SetIcon()
virtual void LoadingWindow::SetIcon (const RageSurface * pIcon) inline virtual
Reimplemented in LoadingWindow_Win32, and LoadingWindow_Gtk.
Referenced by sm_main().
SetIndeterminate()
virtual void LoadingWindow::SetIndeterminate (bool indeterminate) inline virtual
Reimplemented in LoadingWindow_Win32, LoadingWindow_Gtk, and LoadingWindow_MacOSX.
References m_indeterminate.
Referenced by Create(), NetworkSyncManager::GetCurrentSMBuild(), SongManager::InitSongsFromDisk(), Profile::LoadAllFromDir(), SongCacheIndex::LoadCache(), SongCacheIndex::LoadHyperCache(), SongManager::LoadStepManiaSongDir(), NetworkSyncManager::NetworkSyncManager(), ScoreManager::RecalculateSSRs(), and LoadingWindow_Gtk::SetIndeterminate().
SetProgress()
virtual void LoadingWindow::SetProgress (const int progress) inline virtual
Reimplemented in LoadingWindow_Win32, LoadingWindow_Gtk, and LoadingWindow_MacOSX.
References m_progress.
Referenced by NetworkSyncManager::GetCurrentSMBuild(), SongManager::InitSongsFromDisk(), Profile::LoadAllFromDir(), SongCacheIndex::LoadCache(), SongCacheIndex::LoadHyperCache(), SongManager::LoadStepManiaSongDir(), ScoreManager::RecalculateSSRs(), and LoadingWindow_Gtk::SetProgress().
SetSplash()
virtual void LoadingWindow::SetSplash (const RageSurface * pSplash) inline virtual
Reimplemented in LoadingWindow_Win32, LoadingWindow_Gtk, LoadingWindow_MacOSX, and LoadingWindow_Null.
Referenced by sm_main().
SetText()
virtual void LoadingWindow::SetText (const RString & str) pure virtual
Implemented in ScreenReloadSongsLoadingWindow, LoadingWindow_Win32, LoadingWindow_Gtk, LoadingWindow_MacOSX, and LoadingWindow_Null.
Referenced by NetworkSyncManager::GetCurrentSMBuild(), SongManager::InitSongsFromDisk(), Profile::LoadAllFromDir(), SongCacheIndex::LoadCache(), SongCacheIndex::LoadHyperCache(), SongManager::LoadStepManiaSongDir(), NetworkSyncManager::NetworkSyncManager(), ScoreManager::RecalculateSSRs(), and ProfileManager::RefreshLocalProfilesFromDisk().
SetTotalWork()
virtual void LoadingWindow::SetTotalWork (const int totalWork) inline virtual
Reimplemented in LoadingWindow_Win32, LoadingWindow_Gtk, and LoadingWindow_MacOSX.
References m_totalWork.
Referenced by NetworkSyncManager::GetCurrentSMBuild(), SongManager::InitSongsFromDisk(), Profile::LoadAllFromDir(), SongCacheIndex::LoadCache(), SongCacheIndex::LoadHyperCache(), SongManager::LoadStepManiaSongDir(), ScoreManager::RecalculateSSRs(), and LoadingWindow_Gtk::SetTotalWork().
Member Data Documentation
m_indeterminate
bool LoadingWindow::m_indeterminate protected
Referenced by SetIndeterminate(), LoadingWindow_Gtk::SetIndeterminate(), LoadingWindow_Win32::SetIndeterminate(), and LoadingWindow_Win32::SetTextInternal().
m_progress
int LoadingWindow::m_progress protected
Referenced by SetProgress(), LoadingWindow_Gtk::SetProgress(), LoadingWindow_Win32::SetProgress(), LoadingWindow_Win32::SetTextInternal(), and LoadingWindow_Gtk::SetTotalWork().
m_totalWork
int LoadingWindow::m_totalWork protected
Referenced by LoadingWindow_Gtk::SetProgress(), LoadingWindow_Win32::SetTextInternal(), SetTotalWork(), LoadingWindow_Gtk::SetTotalWork(), and LoadingWindow_Win32::SetTotalWork().
The documentation for this class was generated from the following files:
LoadingWindow.h
LoadingWindow.cpp