Etterna: MovieTexture_FFMpeg.cpp File Reference
MovieTexture_FFMpeg.cpp File Reference
#include "MovieTexture_FFMpeg.h"
#include "global.h"
#include "RageDisplay.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageUtil.h"
#include <cerrno>
Functions
static void FixLilEndian ()
static int FindCompatibleAVFormat (bool bHighColor)
static RString averr_ssprintf (int err, const char *fmt,...)
static int AVIORageFile_ReadPacket (void *opaque, uint8_t *buf, int buf_size)
static int64_t AVIORageFile_Seek (void *opaque, int64_t offset, int whence)
REGISTER_MOVIE_TEXTURE_CLASS (FFMpeg)
Function Documentation
averr_ssprintf()
static RString averr_ssprintf (int err, const char * fmt, ...) static
References ASSERT, ssprintf(), and vssprintf().
Referenced by MovieDecoder_FFMpeg::Open(), and MovieDecoder_FFMpeg::OpenCodec().
AVIORageFile_ReadPacket()
static int AVIORageFile_ReadPacket (void * opaque, uint8_t * buf, int buf_size) static
References f, and RageFile::Read().
Referenced by MovieDecoder_FFMpeg::Open().
AVIORageFile_Seek()
static int64_t AVIORageFile_Seek (void * opaque, int64_t offset, int whence) static
References f, RageFile::GetFileSize(), LOG, RageFile::Seek(), and RageLog::Trace().
Referenced by MovieDecoder_FFMpeg::Open().
FindCompatibleAVFormat()
static int FindCompatibleAVFormat (bool bHighColor) static
References AVPixelFormats, AVPixelFormat_t::bHighColor, AVPixelFormat_t::bpp, DISPLAY, RageDisplay::FindPixelFormat(), MovieTexture_Generic::GetEffectMode(), RageDisplay::IsEffectModeSupported(), AVPixelFormat_t::masks, PixelFormatYCbCr_Invalid, RagePixelFormat_Invalid, and AVPixelFormat_t::YUV.
Referenced by RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface().
FixLilEndian()
static void FixLilEndian () static
References AVPixelFormats, AVPixelFormat_t::bByteSwapOnLittleEndian, AVPixelFormat_t::bpp, FAIL_M, AVPixelFormat_t::masks, ssprintf(), Swap24(), and Swap32().
Referenced by RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface(), and MovieDecoder_FFMpeg::MovieDecoder_FFMpeg().
REGISTER_MOVIE_TEXTURE_CLASS()
REGISTER_MOVIE_TEXTURE_CLASS (FFMpeg)