Etterna: LunaTimingData Class Reference
LunaTimingData Class Reference
Allow Lua to have access to the TimingData.
Public Member Functions
GET_FUNCTION (GetWarps, SEGMENT_WARP)
GET_FUNCTION (GetFakes, SEGMENT_FAKE)
GET_FUNCTION (GetScrolls, SEGMENT_SCROLL)
GET_FUNCTION (GetSpeeds, SEGMENT_SPEED)
GET_FUNCTION (GetTimeSignatures, SEGMENT_TIME_SIG)
GET_FUNCTION (GetCombos, SEGMENT_COMBO)
GET_FUNCTION (GetTickcounts, SEGMENT_TICKCOUNT)
GET_FUNCTION (GetStops, SEGMENT_STOP)
GET_FUNCTION (GetDelays, SEGMENT_DELAY)
GET_FUNCTION (GetLabels, SEGMENT_LABEL)
GET_FUNCTION (GetBPMsAndTimes, SEGMENT_BPM)
LunaTimingData ()
Public Member Functions inherited from Luna< TimingData >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int HasStops (T *p, lua_State *L)
static int HasDelays (T *p, lua_State *L)
static int HasBPMChanges (T *p, lua_State *L)
static int HasWarps (T *p, lua_State *L)
static int HasFakes (T *p, lua_State *L)
static int HasSpeedChanges (T *p, lua_State *L)
static int HasScrollChanges (T *p, lua_State *L)
static int GetBPMs (T *p, lua_State *L)
static int GetActualBPM (T *p, lua_State *L)
static int HasNegativeBPMs (T *p, lua_State *L)
static int GetBPMAtBeat (T *p, lua_State *L)
static int GetBeatFromElapsedTime (T *p, lua_State *L)
static int GetElapsedTimeFromBeat (T *p, lua_State *L)
static int GetElapsedTimeFromNoteRow (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< TimingData >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< TimingData >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< TimingData >
using T = TimingData
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< TimingData >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the TimingData.
Constructor & Destructor Documentation
LunaTimingData()
LunaTimingData::LunaTimingData () inline
References ADD_METHOD, GetActualBPM(), GetBeatFromElapsedTime(), GetBPMAtBeat(), GetBPMs(), GetElapsedTimeFromBeat(), GetElapsedTimeFromNoteRow(), HasBPMChanges(), HasDelays(), HasFakes(), HasNegativeBPMs(), HasScrollChanges(), HasSpeedChanges(), HasStops(), and HasWarps().
Member Function Documentation
GET_FUNCTION() [1/11]
LunaTimingData::GET_FUNCTION (GetWarps , SEGMENT_WARP)
GET_FUNCTION() [2/11]
LunaTimingData::GET_FUNCTION (GetFakes , SEGMENT_FAKE)
GET_FUNCTION() [3/11]
LunaTimingData::GET_FUNCTION (GetScrolls , SEGMENT_SCROLL)
GET_FUNCTION() [4/11]
LunaTimingData::GET_FUNCTION (GetSpeeds , SEGMENT_SPEED)
GET_FUNCTION() [5/11]
LunaTimingData::GET_FUNCTION (GetTimeSignatures , SEGMENT_TIME_SIG)
GET_FUNCTION() [6/11]
LunaTimingData::GET_FUNCTION (GetCombos , SEGMENT_COMBO)
GET_FUNCTION() [7/11]
LunaTimingData::GET_FUNCTION (GetTickcounts , SEGMENT_TICKCOUNT)
GET_FUNCTION() [8/11]
LunaTimingData::GET_FUNCTION (GetStops , SEGMENT_STOP)
GET_FUNCTION() [9/11]
LunaTimingData::GET_FUNCTION (GetDelays , SEGMENT_DELAY)
GET_FUNCTION() [10/11]
LunaTimingData::GET_FUNCTION (GetLabels , SEGMENT_LABEL)
GET_FUNCTION() [11/11]
LunaTimingData::GET_FUNCTION (GetBPMsAndTimes , SEGMENT_BPM)
GetActualBPM()
static int LunaTimingData::GetActualBPM (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and TimingData::GetActualBPM().
Referenced by LunaTimingData().
GetBeatFromElapsedTime()
static int LunaTimingData::GetBeatFromElapsedTime (T * p, lua_State * L) inline static
References FArg, and TimingData::GetBeatFromElapsedTime().
Referenced by LunaTimingData().
GetBPMAtBeat()
static int LunaTimingData::GetBPMAtBeat (T * p, lua_State * L) inline static
References FArg, and TimingData::GetBPMAtBeat().
Referenced by LunaTimingData().
GetBPMs()
static int LunaTimingData::GetBPMs (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), TimingData::GetTimingSegments(), and SEGMENT_BPM.
Referenced by LunaTimingData().
GetElapsedTimeFromBeat()
static int LunaTimingData::GetElapsedTimeFromBeat (T * p, lua_State * L) inline static
References FArg, and TimingData::WhereUAtBro().
Referenced by LunaTimingData().
GetElapsedTimeFromNoteRow()
static int LunaTimingData::GetElapsedTimeFromNoteRow (T * p, lua_State * L) inline static
References IArg, and TimingData::WhereUAtBro().
Referenced by LunaTimingData().
HasBPMChanges()
static int LunaTimingData::HasBPMChanges (T * p, lua_State * L) inline static
References TimingData::HasBpmChanges().
Referenced by LunaTimingData().
HasDelays()
static int LunaTimingData::HasDelays (T * p, lua_State * L) inline static
References TimingData::HasDelays().
Referenced by LunaTimingData().
HasFakes()
static int LunaTimingData::HasFakes (T * p, lua_State * L) inline static
References TimingData::HasFakes().
Referenced by LunaTimingData().
HasNegativeBPMs()
static int LunaTimingData::HasNegativeBPMs (T * p, lua_State * L) inline static
References TimingData::HasWarps().
Referenced by LunaTimingData().
HasScrollChanges()
static int LunaTimingData::HasScrollChanges (T * p, lua_State * L) inline static
References TimingData::HasScrollChanges().
Referenced by LunaTimingData().
HasSpeedChanges()
static int LunaTimingData::HasSpeedChanges (T * p, lua_State * L) inline static
References TimingData::HasSpeedChanges().
Referenced by LunaTimingData().
HasStops()
static int LunaTimingData::HasStops (T * p, lua_State * L) inline static
References TimingData::HasStops().
Referenced by LunaTimingData().
HasWarps()
static int LunaTimingData::HasWarps (T * p, lua_State * L) inline static
References TimingData::HasWarps().
Referenced by LunaTimingData().
The documentation for this class was generated from the following file:
TimingData.cpp