Etterna: RageThreadRegister Class Reference
RageThreadRegister Class Reference
Register a thread created outside of RageThread.
#include <RageThreads.h>
Public Member Functions
RageThreadRegister (const RString &sName)
~RageThreadRegister ()
Private Member Functions
RageThreadRegister & operator= (const RageThreadRegister &rhs)=delete
RageThreadRegister (const RageThreadRegister &rhs)=delete
Private Attributes
ThreadSlot * m_pSlot
Detailed Description
Register a thread created outside of RageThread.
This gives it a name for RageThread::GetCurrentThreadName, and allocates a slot for checkpoints.
Constructor & Destructor Documentation
RageThreadRegister() [1/2]
RageThreadRegister::RageThreadRegister (const RString & sName)
References FindEmptyThreadSlot(), GetThreadSlotsLock(), InitThreads(), LockMut, ThreadSlot::m_iID, ThreadSlot::m_pImpl, m_pSlot, ThreadSlot::m_szName, and ThreadSlot::m_szThreadFormattedOutput.
~RageThreadRegister()
RageThreadRegister::~RageThreadRegister ()
References GetThreadSlotsLock(), LockMut, m_pSlot, and ThreadSlot::Release().
RageThreadRegister() [2/2]
RageThreadRegister::RageThreadRegister (const RageThreadRegister & rhs) private delete
Member Function Documentation
operator=()
RageThreadRegister& RageThreadRegister::operator= (const RageThreadRegister & rhs) private delete
Member Data Documentation
m_pSlot
ThreadSlot* RageThreadRegister::m_pSlot private
Referenced by RageThreadRegister(), and ~RageThreadRegister().
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp