Etterna: RageSoundDriver_AU Class Reference
RageSoundDriver_AU Class Reference
#include <RageSoundDriver_AU.h>
Public Member Functions
RageSoundDriver_AU ()
RString Init ()
~RageSoundDriver_AU ()
float GetPlayLatency () const
int GetSampleRate () const
int64_t GetPosition () const
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Protected Member Functions
void SetupDecodingThread ()
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Static Private Member Functions
static OSStatus Render (void *inRefCon, AudioUnitRenderActionFlags *ioActionFlags, const AudioTimeStamp *inTimeStamp, UInt32 inBusNumber, UInt32 inNumberFrames, AudioBufferList *ioData)
static void NameHALThread (CFRunLoopObserverRef, CFRunLoopActivity activity, void *inRefCon)
Private Attributes
double m_TimeScale
AudioUnit m_OutputUnit
int m_iSampleRate
bool m_bDone
bool m_bStarted
RageThreadRegister * m_pIOThread
RageThreadRegister * m_pNotificationThread
RageSemaphore m_Semaphore
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Constructor & Destructor Documentation
RageSoundDriver_AU()
RageSoundDriver_AU::RageSoundDriver_AU ()
~RageSoundDriver_AU()
RageSoundDriver_AU::~RageSoundDriver_AU ()
References m_bDone, m_bStarted, m_OutputUnit, m_pIOThread, m_pNotificationThread, m_Semaphore, and RageSemaphore::Wait().
Member Function Documentation
GetPlayLatency()
float RageSoundDriver_AU::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
References LOG, m_OutputUnit, RageLog::Warn(), and WERROR.
GetPosition()
int64_t RageSoundDriver_AU::GetPosition () const virtual
Implements RageSoundDriver.
References m_TimeScale.
GetSampleRate()
int RageSoundDriver_AU::GetSampleRate () const inline virtual
Reimplemented from RageSoundDriver.
References m_iSampleRate.
Init()
RString RageSoundDriver_AU::Init () virtual
Reimplemented from RageSoundDriver.
References ERROR, kBitsPerChannel, kBytesPerFrame, kBytesPerPacket, kChannelsPerFrame, kFormatFlags, kFramesPerPacket, LOG, m_bStarted, m_iSampleRate, PrefsManager::m_iSoundPreferredSampleRate, m_OutputUnit, m_TimeScale, PREFSMAN, Render(), SetSampleRate(), RageSoundDriver::StartDecodeThread(), RageLog::Warn(), and WERROR.
NameHALThread()
static void RageSoundDriver_AU::NameHALThread (CFRunLoopObserverRef , CFRunLoopActivity activity, void * inRefCon) static private
Render()
OSStatus RageSoundDriver_AU::Render (void * inRefCon, AudioUnitRenderActionFlags * ioActionFlags, const AudioTimeStamp * inTimeStamp, UInt32 inBusNumber, UInt32 inNumberFrames, AudioBufferList * ioData) static private
References m_bDone, m_OutputUnit, m_pIOThread, m_Semaphore, m_TimeScale, RageSoundDriver::Mix(), RageSemaphore::Post(), and unlikely.
Referenced by Init().
SetupDecodingThread()
void RageSoundDriver_AU::SetupDecodingThread () protected virtual
Reimplemented from RageSoundDriver.
References f, LOG, and RageLog::Warn().
Member Data Documentation
m_bDone
bool RageSoundDriver_AU::m_bDone private
Referenced by Render(), and ~RageSoundDriver_AU().
m_bStarted
bool RageSoundDriver_AU::m_bStarted private
Referenced by Init(), and ~RageSoundDriver_AU().
m_iSampleRate
int RageSoundDriver_AU::m_iSampleRate private
Referenced by GetSampleRate(), and Init().
m_OutputUnit
AudioUnit RageSoundDriver_AU::m_OutputUnit private
Referenced by GetPlayLatency(), Init(), Render(), and ~RageSoundDriver_AU().
m_pIOThread
RageThreadRegister* RageSoundDriver_AU::m_pIOThread private
Referenced by Render(), and ~RageSoundDriver_AU().
m_pNotificationThread
RageThreadRegister* RageSoundDriver_AU::m_pNotificationThread private
Referenced by ~RageSoundDriver_AU().
m_Semaphore
RageSemaphore RageSoundDriver_AU::m_Semaphore private
Referenced by Render(), and ~RageSoundDriver_AU().
m_TimeScale
double RageSoundDriver_AU::m_TimeScale private
Referenced by GetPosition(), Init(), and Render().
The documentation for this class was generated from the following files:
RageSoundDriver_AU.h
RageSoundDriver_AU.cpp