Etterna: DriverList Struct Reference
DriverList Struct Reference
#include <RageDriver.h>
Public Member Functions
void Add (const istring &sName, CreateRageDriverFn pfn)
RageDriver * Create (const RString &sDriverName)
Public Attributes
map< istring, CreateRageDriverFn > * m_pRegistrees
Member Function Documentation
Add()
void DriverList::Add (const istring & sName, CreateRageDriverFn pfn)
References ASSERT, and m_pRegistrees.
Referenced by RegisterRageDriver::RegisterRageDriver().
Create()
RageDriver * DriverList::Create (const RString & sDriverName)
References m_pRegistrees.
Referenced by RageMovieTexture::Create(), RageSoundDriver::Create(), and InputHandler::Create().
Member Data Documentation
m_pRegistrees
map<istring, CreateRageDriverFn>* DriverList::m_pRegistrees
Referenced by Add(), RageSoundDriver::Create(), and Create().
The documentation for this struct was generated from the following files:
RageDriver.h
RageDriver.cpp