Etterna: NoteDisplay Class Reference
NoteDisplay Class Reference
Draws TapNotes and HoldNotes.
#include <NoteDisplay.h>
Classes
struct draw_hold_part_args
Public Member Functions
NoteDisplay ()
~NoteDisplay ()
void Load (int iColNum, const PlayerState *pPlayerState, float fYReverseOffsetPixels)
bool DrawHoldsInRange (const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, const vector< NoteData::TrackMap::const_iterator > &tap_set)
bool DrawTapsInRange (const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, const vector< NoteData::TrackMap::const_iterator > &tap_set)
void DrawTap (const TapNote &tn, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, float fBeat, bool bOnSameRowAsHoldStart, bool bOnSameRowAsRollBeat, bool bIsAddition, float fPercentFadeToFail)
Draw the TapNote onto the NoteField.
void DrawHold (const TapNote &tn, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, int iRow, bool bIsBeingHeld, const HoldNoteResult &Result, bool bIsAddition, float fPercentFadeToFail)
bool DrawHoldHeadForTapsOnSameRow () const
bool DrawRollHeadForTapsOnSameRow () const
Static Public Member Functions
static void Update (float fDeltaTime)
Private Member Functions
void SetActiveFrame (float fNoteBeat, Actor &actorToSet, float fAnimationLength, bool bVivid)
Actor * GetTapActor (NoteColorActor &nca, NotePart part, float fNoteBeat)
Actor * GetHoldActor (NoteColorActor nca[NUM_HoldType][NUM_ActiveType], NotePart part, float fNoteBeat, bool bIsRoll, bool bIsBeingHeld)
Sprite * GetHoldSprite (NoteColorSprite ncs[NUM_HoldType][NUM_ActiveType], NotePart part, float fNoteBeat, bool bIsRoll, bool bIsBeingHeld)
void DrawActor (const TapNote &tn, Actor *pActor, NotePart part, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, float fYOffset, float fBeat, bool bIsAddition, float fPercentFadeToFail, float fColorScale, bool is_being_held)
void DrawHoldPart (vector< Sprite *> &vpSpr, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, const draw_hold_part_args &part_args, bool glow, int part_type)
void DrawHoldBodyInternal (vector< Sprite *> &sprite_top, vector< Sprite *> &sprite_body, vector< Sprite *> &sprite_bottom, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, draw_hold_part_args &part_args, const float head_minus_top, const float tail_plus_bottom, const float y_head, const float y_tail, const float y_length, const float top_beat, const float bottom_beat, bool glow)
void DrawHoldBody (const TapNote &tn, const NoteFieldRenderArgs &field_args, const NoteColumnRenderArgs &column_args, float beat, bool being_held, float y_head, float y_tail, float y_end, float percent_fade_to_fail, float color_scale, float top_beat, float bottom_beat)
Private Attributes
const PlayerState * m_pPlayerState
NoteMetricCache_t * cache
NoteColorActor m_TapNote
NoteColorActor m_TapMine
NoteColorActor m_TapLift
NoteColorActor m_TapFake
NoteColorActor m_HoldHead [NUM_HoldType][NUM_ActiveType]
NoteColorSprite m_HoldTopCap [NUM_HoldType][NUM_ActiveType]
NoteColorSprite m_HoldBody [NUM_HoldType][NUM_ActiveType]
NoteColorSprite m_HoldBottomCap [NUM_HoldType][NUM_ActiveType]
NoteColorActor m_HoldTail [NUM_HoldType][NUM_ActiveType]
float m_fYReverseOffsetPixels
Detailed Description
Draws TapNotes and HoldNotes.
Constructor & Destructor Documentation
NoteDisplay()
NoteDisplay::NoteDisplay ()
References cache.
~NoteDisplay()
NoteDisplay::~NoteDisplay ()
References cache.
Member Function Documentation
DrawActor()
void NoteDisplay::DrawActor (const TapNote & tn, Actor * pActor, NotePart part, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, float fYOffset, float fBeat, bool bIsAddition, float fPercentFadeToFail, float fColorScale, bool is_being_held) private
References RageColor::a, RageColor::b, BeatToNoteType(), cache, clamp, NoteColumnRenderArgs::column, NoteColumnRenderArgs::diffuse, DISPLAY, Actor::Draw(), NoteFieldRenderArgs::draw_pixels_after_targets, NoteFieldRenderArgs::draw_pixels_before_targets, NCSplineHandler::EvalForBeat(), NoteFieldRenderArgs::fade_before_targets, FAIL_M, RageColor::g, ArrowEffects::GetAlpha(), ArrowEffects::GetBrightness(), ArrowEffects::GetGlow(), ArrowEffects::GetRotationX(), ArrowEffects::GetRotationY(), ArrowEffects::GetRotationZ(), IsVectorZero(), NoteMetricCache_t::m_fAdditionTextureCoordOffset, NoteMetricCache_t::m_fNoteColorTextureCoordSpacing, m_fYReverseOffsetPixels, NoteMetricCache_t::m_iNoteColorCount, NoteMetricCache_t::m_NoteColorType, m_pPlayerState, NCSplineHandler::m_spline_mode, NCSM_Disabled, NCSM_Offset, NCSM_Position, NoteColorType_Denominator, NoteColorType_Progress, RageColor::r, NoteColumnRenderArgs::rot_handler, Actor::SetDiffuse(), Actor::SetGlow(), NoteColumnRenderArgs::SetPRZForActor(), NoteColumnRenderArgs::song_beat, NoteColumnRenderArgs::spae_pos_for_beat(), NoteColumnRenderArgs::spae_zoom_for_beat(), ssprintf(), TapNoteType_AutoKeysound, TapNoteType_HoldHead, TapNoteType_HoldTail, RageDisplay::TexturePopMatrix(), RageDisplay::TexturePushMatrix(), RageDisplay::TextureTranslate(), TapNote::type, RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by DrawHold(), and DrawTap().
DrawHold()
void NoteDisplay::DrawHold (const TapNote & tn, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, int iRow, bool bIsBeingHeld, const HoldNoteResult & Result, bool bIsAddition, float fPercentFadeToFail)
References HoldNoteResult::bActive, cache, NoteColumnRenderArgs::column, DrawActor(), DrawHoldBody(), HoldNoteResult::fLife, ModsGroup< T >::GetCurrent(), GetHoldActor(), PlayerOptions::GetReversePercentForColumn(), ArrowEffects::GetYOffset(), ArrowEffects::GetYPos(), TapNote::HoldResult, HoldSize, TapNote::iDuration, HoldNoteResult::iLastHeldRow, NoteMetricCache_t::m_bFlipHeadAndTailWhenReverse, NoteMetricCache_t::m_bHoldHeadIsAboveWavyParts, NoteMetricCache_t::m_bHoldTailIsAboveWavyParts, NoteMetricCache_t::m_fHoldLetGoGrayPercent, m_fYReverseOffsetPixels, m_HoldHead, m_HoldTail, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, m_pPlayerState, NoteMetricCache_t::m_UseShrinkHolds, max(), NotePart_HoldHead, NotePart_HoldTail, NoteRowToBeat(), NoteRowToVisibleBeat(), SCALE, NoteColumnRenderArgs::song_beat, TapNote::subType, swap(), and TapNoteSubType_Roll.
Referenced by DrawHoldsInRange().
DrawHoldBody()
void NoteDisplay::DrawHoldBody (const TapNote & tn, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, float beat, bool being_held, float y_head, float y_tail, float y_end, float percent_fade_to_fail, float color_scale, float top_beat, float bottom_beat) private
References RageColor::a, NoteDisplay::draw_hold_part_args::anchor_to_top, cache, NoteDisplay::draw_hold_part_args::color_scale, NoteColumnRenderArgs::column, DISPLAY, NoteFieldRenderArgs::draw_pixels_after_targets, NoteFieldRenderArgs::draw_pixels_before_targets, DrawHoldBodyInternal(), NoteDisplay::draw_hold_part_args::flip_texture_vertically, HoldNoteResult::fOverlappedTime, ModsGroup< T >::GetCurrent(), GetHoldSprite(), PlayerOptions::GetReversePercentForColumn(), Actor::GetUnzoomedHeight(), ArrowEffects::GetYPos(), ArrowEffects::GetZoom(), NoteColumnRenderArgs::glow, TapNote::HoldResult, NoteMetricCache_t::m_bFlipHoldBodyWhenReverse, NoteMetricCache_t::m_bHoldActiveIsAddLayer, NoteMetricCache_t::m_bTopHoldAnchorWhenReverse, m_fYReverseOffsetPixels, m_HoldBody, m_HoldBottomCap, m_HoldTopCap, NoteMetricCache_t::m_iStartDrawingHoldBodyOffsetFromHead, NoteMetricCache_t::m_iStopDrawingHoldBodyOffsetFromTail, PlayerState::m_PlayerOptions, m_pPlayerState, ArrowEffects::NeedZBuffer(), NotePart_HoldBody, NotePart_HoldBottomCap, NotePart_HoldTopCap, NoteDisplay::draw_hold_part_args::overlapped_time, NoteDisplay::draw_hold_part_args::percent_fade_to_fail, NoteFieldRenderArgs::selection_begin_marker, NoteFieldRenderArgs::selection_end_marker, RageDisplay::SetTextureMode(), RageDisplay::SetZTestMode(), RageDisplay::SetZWrite(), TapNote::subType, swap(), TapNoteSubType_Roll, TextureMode_Glow, TextureMode_Modulate, TextureUnit_1, NoteDisplay::draw_hold_part_args::y_end_pos, NoteDisplay::draw_hold_part_args::y_start_pos, NoteDisplay::draw_hold_part_args::y_step, ZTEST_OFF, and ZTEST_WRITE_ON_PASS.
Referenced by DrawHold().
DrawHoldBodyInternal()
void NoteDisplay::DrawHoldBodyInternal (vector< Sprite *> & sprite_top, vector< Sprite *> & sprite_body, vector< Sprite *> & sprite_bottom, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, draw_hold_part_args & part_args, const float head_minus_top, const float tail_plus_bottom, const float y_head, const float y_tail, const float y_length, const float top_beat, const float bottom_beat, bool glow) private
References NoteDisplay::draw_hold_part_args::bottom_beat, DrawHoldPart(), hpt_body, hpt_bottom, hpt_top, max(), NoteDisplay::draw_hold_part_args::top_beat, NoteDisplay::draw_hold_part_args::wrapping, NoteDisplay::draw_hold_part_args::y_bottom, NoteDisplay::draw_hold_part_args::y_length, NoteDisplay::draw_hold_part_args::y_start_pos, and NoteDisplay::draw_hold_part_args::y_top.
Referenced by DrawHoldBody().
DrawHoldHeadForTapsOnSameRow()
bool NoteDisplay::DrawHoldHeadForTapsOnSameRow () const
References cache, and NoteMetricCache_t::m_bDrawHoldHeadForTapsOnSameRow.
Referenced by DrawTapsInRange().
DrawHoldPart()
void NoteDisplay::DrawHoldPart (vector< Sprite *> & vpSpr, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, const draw_hold_part_args & part_args, bool glow, int part_type) private
References RageColor::a, NoteDisplay::draw_hold_part_args::anchor_to_top, ArrowGetAlphaOrGlow(), ASSERT, RageColor::b, BLEND_ADD, BLEND_NORMAL, StepMania::Rect< T >::bottom, NoteDisplay::draw_hold_part_args::bottom_beat, RageSpriteVertex::c, cache, NoteDisplay::draw_hold_part_args::color_scale, NoteColumnRenderArgs::column, CULL_NONE, NoteColumnRenderArgs::diffuse, DISPLAY, StripBuffer::Draw(), NoteFieldRenderArgs::draw_pixels_before_targets, NCSplineHandler::EvalDerivForBeat(), NCSplineHandler::EvalForBeat(), f, NoteFieldRenderArgs::fade_before_targets, NoteDisplay::draw_hold_part_args::flip_texture_vertically, FOREACH, StripBuffer::Free(), RageColor::g, Sprite::GetCurrentTextureCoordRect(), ArrowEffects::GetFrameWidthScale(), ArrowEffects::GetRotationY(), RageTexture::GetTexHandle(), Actor::GetUnzoomedHeight(), Actor::GetUnzoomedWidth(), ArrowEffects::GetYOffsetFromYPos(), ArrowEffects::GetZoom(), hpt_body, hpt_bottom, StripBuffer::Init(), StepMania::Rect< T >::left, m_fYReverseOffsetPixels, m_pPlayerState, NCSplineHandler::m_spline_mode, NoteMetricCache_t::m_UseStretchHolds, max(), min(), NCSM_Disabled, NCSM_Offset, NCSM_Position, NoteDisplay::draw_hold_part_args::overlapped_time, RageSpriteVertex::p, NoteDisplay::draw_hold_part_args::percent_fade_to_fail, PI_180R, NoteColumnRenderArgs::pos_handler, RageColor::r, RageAARotate(), RageVec3Cross(), RageVec3Normalize(), StepMania::Rect< T >::right, NoteColumnRenderArgs::rot_handler, SCALE, RageDisplay::SetBlendMode(), RageDisplay::SetCullMode(), RageDisplay::SetTexture(), RageDisplay::SetTextureWrapping(), NoteColumnRenderArgs::song_beat, NoteColumnRenderArgs::spae_pos_for_beat(), swap(), RageSpriteVertex::t, TextureUnit_1, StepMania::Rect< T >::top, NoteDisplay::draw_hold_part_args::top_beat, StripBuffer::v, NoteDisplay::draw_hold_part_args::wrapping, RageVector3::x, RageVector3::y, NoteDisplay::draw_hold_part_args::y_bottom, NoteDisplay::draw_hold_part_args::y_end_pos, NoteDisplay::draw_hold_part_args::y_length, NoteDisplay::draw_hold_part_args::y_start_pos, NoteDisplay::draw_hold_part_args::y_step, NoteDisplay::draw_hold_part_args::y_top, RageVector3::z, and NoteColumnRenderArgs::zoom_handler.
Referenced by DrawHoldBodyInternal().
DrawHoldsInRange()
bool NoteDisplay::DrawHoldsInRange (const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, const vector< NoteData::TrackMap::const_iterator > & tap_set)
References ASSERT_M, HoldNoteResult::bActive, HoldNoteResult::bHeld, NoteColumnRenderArgs::column, NoteFieldRenderArgs::draw_pixels_after_targets, NoteFieldRenderArgs::draw_pixels_before_targets, DrawHold(), NoteFieldRenderArgs::fail_fade, HoldNoteResult::fLife, PlayerState::GetDisplayedPosition(), ArrowEffects::GetYOffset(), NoteFieldRenderArgs::ghost_row, TapNote::HoldResult, TapNote::iDuration, SongPosition::m_fSongBeat, m_pPlayerState, NoteRowToBeat(), NoteRowToVisibleBeat(), NoteFieldRenderArgs::selection_begin_marker, NoteFieldRenderArgs::selection_end_marker, NoteFieldRenderArgs::selection_glow, GhostArrowRow::SetHoldShowing(), TapNote::source, ssprintf(), and TapNoteSource_Addition.
DrawRollHeadForTapsOnSameRow()
bool NoteDisplay::DrawRollHeadForTapsOnSameRow () const
References cache, and NoteMetricCache_t::m_bDrawRollHeadForTapsOnSameRow.
Referenced by DrawTapsInRange().
DrawTap()
void NoteDisplay::DrawTap (const TapNote & tn, const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, float fBeat, bool bOnSameRowAsHoldStart, bool bOnSameRowAsRollBeat, bool bIsAddition, float fPercentFadeToFail)
Draw the TapNote onto the NoteField.
Parameters
tn the TapNote in question.
iCol the column.
float fBeat the beat to draw them on.
bOnSameRowAsHoldStart a flag to see if a hold is on the same beat.
bOnSameRowAsRollStart a flag to see if a roll is on the same beat.
bIsAddition a flag to see if this note was added via mods.
fPercentFadeToFail at what point do the notes fade on failure?
fReverseOffsetPixels How are the notes adjusted on Reverse?
fDrawDistanceAfterTargetsPixels how much to draw after the receptors.
fDrawDistanceBeforeTargetsPixels how much ot draw before the receptors.
fFadeInPercentOfDrawFar when to start fading in.
References cache, NoteColumnRenderArgs::column, DrawActor(), f, GetHoldActor(), GetTapActor(), ArrowEffects::GetYOffset(), NoteMetricCache_t::m_bDrawHoldHeadForTapsOnSameRow, NoteMetricCache_t::m_bDrawRollHeadForTapsOnSameRow, NoteMetricCache_t::m_bTapHoldRollOnRowMeansHold, m_HoldHead, m_pPlayerState, m_TapFake, m_TapLift, m_TapMine, m_TapNote, NotePart_Fake, NotePart_HoldHead, NotePart_Lift, NotePart_Mine, NotePart_Tap, TapNoteType_Fake, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and TapNote::type.
Referenced by DrawTapsInRange().
DrawTapsInRange()
bool NoteDisplay::DrawTapsInRange (const NoteFieldRenderArgs & field_args, const NoteColumnRenderArgs & column_args, const vector< NoteData::TrackMap::const_iterator > & tap_set)
References ASSERT_M, RageDisplay::ClearZBuffer(), DISPLAY, DrawHoldHeadForTapsOnSameRow(), DrawRollHeadForTapsOnSameRow(), DrawTap(), NoteFieldRenderArgs::fail_fade, PlayerState::GetDisplayedPosition(), NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteFieldRenderArgs::last_row, PrefsManager::m_FastNoteRendering, SongPosition::m_fMusicSeconds, SongPosition::m_fSongBeat, m_pPlayerState, NoteFieldRenderArgs::note_data, NoteRowToBeat(), NoteRowToVisibleBeat(), PREFSMAN, NoteFieldRenderArgs::selection_begin_marker, NoteFieldRenderArgs::selection_end_marker, NoteFieldRenderArgs::selection_glow, TapNote::source, ssprintf(), TapNote::subType, TapNoteSource_Addition, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_HoldHead, and TapNote::type.
GetHoldActor()
Actor * NoteDisplay::GetHoldActor (NoteColorActor nca[NUM_HoldType][NUM_ActiveType], NotePart part, float fNoteBeat, bool bIsRoll, bool bIsBeingHeld) private
References active, GetTapActor(), hold, inactive, and roll.
Referenced by DrawHold(), and DrawTap().
GetHoldSprite()
Sprite * NoteDisplay::GetHoldSprite (NoteColorSprite ncs[NUM_HoldType][NUM_ActiveType], NotePart part, float fNoteBeat, bool bIsRoll, bool bIsBeingHeld) private
References active, BeatToNoteType(), cache, hold, inactive, NoteMetricCache_t::m_bAnimationIsVivid, NoteMetricCache_t::m_fAnimationLength, NoteTypeToString(), roll, and SetActiveFrame().
Referenced by DrawHoldBody().
GetTapActor()
Actor * NoteDisplay::GetTapActor (NoteColorActor & nca, NotePart part, float fNoteBeat) private
References BeatToNoteType(), cache, NoteColorActor::Get(), NoteMetricCache_t::m_bAnimationIsVivid, NoteMetricCache_t::m_fAnimationLength, NoteTypeToString(), and SetActiveFrame().
Referenced by DrawTap(), and GetHoldActor().
Load()
void NoteDisplay::Load (int iColNum, const PlayerState * pPlayerState, float fYReverseOffsetPixels)
References ActiveTypeToString(), cache, Style::ColToButtonName(), FOREACH_ActiveType, FOREACH_HoldType, GAMESTATE, GameState::GetCurrentStyle(), HoldTypeToString(), NoteColorActor::Load(), NoteColorSprite::Load(), NoteMetricCache_t::Load(), m_fYReverseOffsetPixels, m_HoldBody, m_HoldBottomCap, m_HoldHead, m_HoldTail, m_HoldTopCap, PlayerState::m_PlayerNumber, m_pPlayerState, m_TapFake, m_TapLift, m_TapMine, m_TapNote, and Style::StyleInputToGameInput().
Referenced by NoteField::CacheNoteSkin().
SetActiveFrame()
void NoteDisplay::SetActiveFrame (float fNoteBeat, Actor & actorToSet, float fAnimationLength, bool bVivid) private
References cache, f, Actor::GetAnimationLengthSeconds(), NoteMetricCache_t::m_bAnimationBasedOnBeats, SongPosition::m_fMusicSeconds, SongPosition::m_fSongBeat, PlayerState::m_Position, m_pPlayerState, QuantizeDown(), Actor::SetSecondsIntoAnimation(), and wrap().
Referenced by GetHoldSprite(), and GetTapActor().
Update()
void NoteDisplay::Update (float fDeltaTime) static
References g_NoteResource, NoteResource::m_pActor, and Actor::Update().
Referenced by NoteField::Update().
Member Data Documentation
cache
NoteMetricCache_t* NoteDisplay::cache private
Referenced by DrawActor(), DrawHold(), DrawHoldBody(), DrawHoldHeadForTapsOnSameRow(), DrawHoldPart(), DrawRollHeadForTapsOnSameRow(), DrawTap(), GetHoldSprite(), GetTapActor(), Load(), NoteDisplay(), SetActiveFrame(), and ~NoteDisplay().
m_fYReverseOffsetPixels
float NoteDisplay::m_fYReverseOffsetPixels private
Referenced by DrawActor(), DrawHold(), DrawHoldBody(), DrawHoldPart(), and Load().
m_HoldBody
NoteColorSprite NoteDisplay::m_HoldBody[NUM_HoldType][NUM_ActiveType] private
Referenced by DrawHoldBody(), and Load().
m_HoldBottomCap
NoteColorSprite NoteDisplay::m_HoldBottomCap[NUM_HoldType][NUM_ActiveType] private
Referenced by DrawHoldBody(), and Load().
m_HoldHead
NoteColorActor NoteDisplay::m_HoldHead[NUM_HoldType][NUM_ActiveType] private
Referenced by DrawHold(), DrawTap(), and Load().
m_HoldTail
NoteColorActor NoteDisplay::m_HoldTail[NUM_HoldType][NUM_ActiveType] private
Referenced by DrawHold(), and Load().
m_HoldTopCap
NoteColorSprite NoteDisplay::m_HoldTopCap[NUM_HoldType][NUM_ActiveType] private
Referenced by DrawHoldBody(), and Load().
m_pPlayerState
const PlayerState* NoteDisplay::m_pPlayerState private
Referenced by DrawActor(), DrawHold(), DrawHoldBody(), DrawHoldPart(), DrawHoldsInRange(), DrawTap(), DrawTapsInRange(), Load(), and SetActiveFrame().
m_TapFake
NoteColorActor NoteDisplay::m_TapFake private
Referenced by DrawTap(), and Load().
m_TapLift
NoteColorActor NoteDisplay::m_TapLift private
Referenced by DrawTap(), and Load().
m_TapMine
NoteColorActor NoteDisplay::m_TapMine private
Referenced by DrawTap(), and Load().
m_TapNote
NoteColorActor NoteDisplay::m_TapNote private
Referenced by DrawTap(), and Load().
The documentation for this class was generated from the following files:
NoteDisplay.h
NoteDisplay.cpp