Etterna: Alsa9Buf Class Reference
Alsa9Buf Class Reference
#include <ALSA9Helpers.h>
Public Member Functions
Alsa9Buf ()
RString Init (int channels, int iWriteahead, int iChunkSize, int iSampleRate)
~Alsa9Buf ()
int GetNumFramesToFill ()
bool WaitUntilFramesCanBeFilled (int timeout_ms)
void Write (const int16_t *buffer, int frames)
void Play ()
void Stop ()
void SetVolume (float vol)
int GetSampleRate () const
int64_t GetPosition () const
int64_t GetPlayPos () const
Static Public Member Functions
static void InitializeErrorHandler ()
static void GetSoundCardDebugInfo ()
static RString GetHardwareID (RString name="")
Private Member Functions
bool Recover (int r)
bool SetHWParams ()
bool SetSWParams ()
Static Private Member Functions
static void ErrorHandler (const char *file, int line, const char *function, int err, const char *fmt,...)
Private Attributes
int channels
int samplebits
unsigned samplerate
int buffersize
int64_t last_cursor_pos
snd_pcm_uframes_t preferred_writeahead
snd_pcm_uframes_t preferred_chunksize
snd_pcm_uframes_t writeahead
snd_pcm_uframes_t chunksize
snd_pcm_t * pcm
Constructor & Destructor Documentation
Alsa9Buf()
Alsa9Buf::Alsa9Buf ()
References last_cursor_pos, pcm, preferred_chunksize, preferred_writeahead, samplebits, and samplerate.
~Alsa9Buf()
Alsa9Buf::~Alsa9Buf ()
References pcm.
Member Function Documentation
ErrorHandler()
void Alsa9Buf::ErrorHandler (const char * file, int line, const char * function, int err, const char * fmt, ...) static private
References LOG, ssprintf(), RageLog::Trace(), and vssprintf().
Referenced by InitializeErrorHandler().
GetHardwareID()
RString Alsa9Buf::GetHardwareID (RString name = "") static
References DeviceName(), dsnd_ctl_card_info_alloca, RageLog::Info(), InitializeErrorHandler(), and LOG.
GetNumFramesToFill()
int Alsa9Buf::GetNumFramesToFill ()
References chunksize, clamp, LOG, max(), pcm, samplerate, RageLog::Trace(), and writeahead.
Referenced by RageSoundDriver_ALSA9_Software::GetData().
GetPlayPos()
int64_t Alsa9Buf::GetPlayPos () const inline
References last_cursor_pos.
Referenced by RageSoundDriver_ALSA9_Software::GetData().
GetPosition()
int64_t Alsa9Buf::GetPosition () const
References ALSA_ASSERT, last_cursor_pos, and pcm.
Referenced by RageSoundDriver_ALSA9_Software::GetData(), and RageSoundDriver_ALSA9_Software::GetPosition().
GetSampleRate()
int Alsa9Buf::GetSampleRate () const inline
References samplerate.
Referenced by RageSoundDriver_ALSA9_Software::Init().
GetSoundCardDebugInfo()
void Alsa9Buf::GetSoundCardDebugInfo () static
References DoesFileExist(), dsnd_ctl_card_info_alloca, dsnd_pcm_info_alloca, GetFileContents(), RageLog::Info(), InitializeErrorHandler(), LOG, PrefsManager::m_iSoundDevice, PREFSMAN, and ssprintf().
Referenced by Init().
Init()
RString Alsa9Buf::Init (int channels, int iWriteahead, int iChunkSize, int iSampleRate)
References channels, CHECKPOINT, chunksize, DeviceName(), GetSoundCardDebugInfo(), RageLog::Info(), InitializeErrorHandler(), LOG, pcm, preferred_chunksize, preferred_writeahead, samplerate, SetHWParams(), SetSWParams(), ssprintf(), and writeahead.
Referenced by RageSoundDriver_ALSA9_Software::Init().
InitializeErrorHandler()
void Alsa9Buf::InitializeErrorHandler () static
References ErrorHandler().
Referenced by GetHardwareID(), GetSoundCardDebugInfo(), and Init().
Play()
void Alsa9Buf::Play ()
Recover()
bool Alsa9Buf::Recover (int r) private
References ALSA_ASSERT, LOG, pcm, and RageLog::Trace().
SetHWParams()
bool Alsa9Buf::SetHWParams () private
References ALSA_ASSERT, ALSA_CHECK, chunksize, dsnd_pcm_hw_params_alloca, pcm, preferred_chunksize, preferred_writeahead, samplerate, and writeahead.
Referenced by Init().
SetSWParams()
bool Alsa9Buf::SetSWParams () private
References ALSA_ASSERT, chunksize, dsnd_pcm_sw_params_alloca, and pcm.
Referenced by Init().
SetVolume()
void Alsa9Buf::SetVolume (float vol)
Stop()
void Alsa9Buf::Stop ()
References last_cursor_pos, and pcm.
WaitUntilFramesCanBeFilled()
bool Alsa9Buf::WaitUntilFramesCanBeFilled (int timeout_ms)
References ALSA_ASSERT, and pcm.
Referenced by RageSoundDriver_ALSA9_Software::MixerThread().
Write()
void Alsa9Buf::Write (const int16_t * buffer, int frames)
References last_cursor_pos, LOG, pcm, and RageLog::Trace().
Referenced by RageSoundDriver_ALSA9_Software::GetData().
Member Data Documentation
buffersize
int Alsa9Buf::buffersize private
channels
int Alsa9Buf::channels private
Referenced by Init().
chunksize
snd_pcm_uframes_t Alsa9Buf::chunksize private
Referenced by GetNumFramesToFill(), Init(), SetHWParams(), and SetSWParams().
last_cursor_pos
int64_t Alsa9Buf::last_cursor_pos private
Referenced by Alsa9Buf(), GetPlayPos(), GetPosition(), Stop(), and Write().
pcm
snd_pcm_t* Alsa9Buf::pcm private
Referenced by Alsa9Buf(), GetNumFramesToFill(), GetPosition(), Init(), Recover(), SetHWParams(), SetSWParams(), Stop(), WaitUntilFramesCanBeFilled(), Write(), and ~Alsa9Buf().
preferred_chunksize
snd_pcm_uframes_t Alsa9Buf::preferred_chunksize private
Referenced by Alsa9Buf(), Init(), and SetHWParams().
preferred_writeahead
snd_pcm_uframes_t Alsa9Buf::preferred_writeahead private
Referenced by Alsa9Buf(), Init(), and SetHWParams().
samplebits
int Alsa9Buf::samplebits private
Referenced by Alsa9Buf().
samplerate
unsigned Alsa9Buf::samplerate private
Referenced by Alsa9Buf(), GetNumFramesToFill(), GetSampleRate(), Init(), and SetHWParams().
writeahead
snd_pcm_uframes_t Alsa9Buf::writeahead private
Referenced by GetNumFramesToFill(), Init(), and SetHWParams().
The documentation for this class was generated from the following files:
ALSA9Helpers.h
ALSA9Helpers.cpp