Etterna: LunaStyle Class Reference
LunaStyle Class Reference
Allow Lua to have access to the Style.
Public Member Functions
LunaStyle ()
Public Member Functions inherited from Luna< Style >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetName (T *p, lua_State *L)
static int NeedsZoomOutWith2Players (T *p, lua_State *L)
static int GetWidth (T *p, lua_State *L)
static int GetColumnInfo (T *p, lua_State *L)
static int GetColumnDrawOrder (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Style >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Style >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Style >
using T = Style
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Style >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Style.
Constructor & Destructor Documentation
LunaStyle()
LunaStyle::LunaStyle () inline
References ADD_METHOD, GetColumnDrawOrder(), GetColumnInfo(), GetName(), GetWidth(), and NeedsZoomOutWith2Players().
Member Function Documentation
GetColumnDrawOrder()
static int LunaStyle::GetColumnDrawOrder (T * p, lua_State * L) inline static
References IArg, Style::m_iColsPerPlayer, Style::m_iColumnDrawOrder, NUM_PLAYERS, and LuaHelpers::ReportScriptErrorFmt().
Referenced by LunaStyle().
GetColumnInfo()
static int LunaStyle::GetColumnInfo (T * p, lua_State * L) inline static
References IArg, L, LuaReference::PushSelf(), LuaHelpers::ReportScriptErrorFmt(), and LuaTable::Set().
Referenced by LunaStyle().
GetName()
static int LunaStyle::GetName (T * p, lua_State * L) inline static
References Style::m_szName, and LuaHelpers::Push().
Referenced by LunaStyle().
GetWidth()
static int LunaStyle::GetWidth (T * p, lua_State * L) inline static
References Style::GetWidth(), and L.
Referenced by LunaStyle().
NeedsZoomOutWith2Players()
static int LunaStyle::NeedsZoomOutWith2Players (T * p, lua_State * L) inline static
Referenced by LunaStyle().
The documentation for this class was generated from the following file:
Style.cpp