Etterna: Character Class Reference
Character Class Reference
A persona that defines attacks for use in battle.
#include <Character.h>
Public Member Functions
Character ()
~Character ()=default
bool Load (RString sCharDir)
RString GetTakingABreakPath () const
RString GetCardPath () const
RString GetIconPath () const
RString GetModelPath () const
RString GetRestAnimationPath () const
RString GetWarmUpAnimationPath () const
RString GetDanceAnimationPath () const
RString GetSongSelectIconPath () const
RString GetStageIconPath () const
bool Has2DElems ()
bool IsDefaultCharacter () const
void DemandGraphics ()
void UndemandGraphics ()
void PushSelf (Lua *L)
const RString & GetDisplayName ()
Public Attributes
RString m_sCharDir
RString m_sCharacterID
apActorCommands m_cmdInit
bool m_bUsableInRave { false }
Is this character playable in the Rave mode?
RageTexturePreloader m_Preload
int m_iPreloadRefcount { 0 }
Private Attributes
RString m_sDisplayName
RString m_sCardPath
RString m_sIconPath
Detailed Description
A persona that defines attacks for use in battle.
Constructor & Destructor Documentation
Character()
Character::Character ()
~Character()
Character::~Character () default
Member Function Documentation
DemandGraphics()
void Character::DemandGraphics ()
References GetIconPath(), RageTexturePreloader::Load(), m_iPreloadRefcount, and m_Preload.
GetCardPath()
RString Character::GetCardPath () const inline
References m_sCardPath.
Referenced by LunaCharacter::GetCardPath(), and Banner::LoadCardFromCharacter().
GetDanceAnimationPath()
RString Character::GetDanceAnimationPath () const
References DerefRedir(), GetRandomFileInDir(), and m_sCharDir.
Referenced by DancingCharacters::DancingCharacters(), and LunaCharacter::GetDanceAnimationPath().
GetDisplayName()
const RString& Character::GetDisplayName () inline
References m_sCharacterID, and m_sDisplayName.
Referenced by LunaCharacter::GetDisplayName(), ProfileManager::Init(), and OptionRowHandlerListCharacters::LoadInternal().
GetIconPath()
RString Character::GetIconPath () const inline
References m_sIconPath.
Referenced by DemandGraphics(), LunaCharacter::GetIconPath(), Banner::LoadFallbackCharacterIcon(), and Banner::LoadIconFromCharacter().
GetModelPath()
RString Character::GetModelPath () const
References DoesFileExist(), and m_sCharDir.
Referenced by BeginnerHelper::AddPlayer(), DancingCharacters::DancingCharacters(), LunaCharacter::GetModelPath(), ScreenHowToPlay::Init(), and BeginnerHelper::Init().
GetRestAnimationPath()
RString Character::GetRestAnimationPath () const
References DerefRedir(), GetRandomFileInDir(), and m_sCharDir.
Referenced by DancingCharacters::DancingCharacters(), LunaCharacter::GetRestAnimationPath(), ScreenHowToPlay::Init(), and BeginnerHelper::Init().
GetSongSelectIconPath()
RString Character::GetSongSelectIconPath () const
References GetDirListing(), and m_sCharDir.
Referenced by LunaCharacter::GetSongSelectIconPath().
GetStageIconPath()
RString Character::GetStageIconPath () const
References GetDirListing(), and m_sCharDir.
Referenced by LunaCharacter::GetStageIconPath().
GetTakingABreakPath()
RString Character::GetTakingABreakPath () const
References GetDirListing(), and m_sCharDir.
GetWarmUpAnimationPath()
RString Character::GetWarmUpAnimationPath () const
References DerefRedir(), GetRandomFileInDir(), and m_sCharDir.
Referenced by DancingCharacters::DancingCharacters(), and LunaCharacter::GetWarmUpAnimationPath().
Has2DElems()
bool Character::Has2DElems ()
References DoesFileExist(), and m_sCharDir.
IsDefaultCharacter()
bool Character::IsDefaultCharacter () const inline
References StdString::CStdStr< CT >::CompareNoCase(), and m_sCharacterID.
Load()
bool Character::Load (RString sCharDir)
References GetDirListing(), IniFile::GetValue(), m_cmdInit, m_sCardPath, m_sCharacterID, m_sCharDir, m_sDisplayName, m_sIconPath, ActorUtil::ParseActorCommands(), IniFile::ReadFile(), StdString::CStdStr< CT >::Right(), and split().
Referenced by CharacterManager::CharacterManager().
PushSelf()
void Character::PushSelf (Lua * L)
Referenced by LunaCharacterManager::GetCharacter(), LunaGameCommand::GetCharacter(), LunaProfile::GetCharacter(), and LunaCharacterManager::GetRandomCharacter().
UndemandGraphics()
void Character::UndemandGraphics ()
References m_iPreloadRefcount, m_Preload, and RageTexturePreloader::UnloadAll().
Member Data Documentation
m_bUsableInRave
bool Character::m_bUsableInRave { false }
Is this character playable in the Rave mode?
All of the variables listed below here will be filled in if true.
m_cmdInit
apActorCommands Character::m_cmdInit
Referenced by DancingCharacters::DancingCharacters(), ScreenHowToPlay::Init(), and Load().
m_iPreloadRefcount
int Character::m_iPreloadRefcount { 0 }
Referenced by DemandGraphics(), and UndemandGraphics().
m_Preload
RageTexturePreloader Character::m_Preload
Referenced by DemandGraphics(), and UndemandGraphics().
m_sCardPath
RString Character::m_sCardPath private
Referenced by GetCardPath(), and Load().
m_sCharacterID
RString Character::m_sCharacterID
Referenced by ProfileManager::CreateLocalProfile(), LunaCharacter::GetCharacterID(), GetDisplayName(), IsDefaultCharacter(), and Load().
m_sCharDir
RString Character::m_sCharDir
Referenced by DancingCharacters::DancingCharacters(), LunaCharacter::GetCharacterDir(), GetDanceAnimationPath(), GetModelPath(), GetRestAnimationPath(), GetSongSelectIconPath(), GetStageIconPath(), GetTakingABreakPath(), GetWarmUpAnimationPath(), Has2DElems(), and Load().
m_sDisplayName
RString Character::m_sDisplayName private
Referenced by GetDisplayName(), and Load().
m_sIconPath
RString Character::m_sIconPath private
Referenced by GetIconPath(), and Load().
The documentation for this class was generated from the following files:
Character.h
Character.cpp