Etterna: ThemeManager Class Reference
ThemeManager Class Reference
Manages theme paths and metrics.
#include <ThemeManager.h>
Classes
struct PathInfo
Public Member Functions
ThemeManager ()
~ThemeManager ()
void GetThemeNames (vector< RString > &AddTo)
void GetSelectableThemeNames (vector< RString > &AddTo)
int GetNumSelectableThemes ()
bool DoesThemeExist (const RString &sThemeName)
bool IsThemeSelectable (RString const &name)
bool IsThemeNameValid (RString const &name)
RString GetThemeDisplayName (const RString &sThemeName)
RString GetThemeAuthor (const RString &sThemeName)
void GetLanguages (vector< RString > &AddTo)
bool DoesLanguageExist (const RString &sLanguage)
void SwitchThemeAndLanguage (const RString &sThemeName, const RString &sLanguage, bool bPseudoLocalize, bool bForceThemeReload=false)
void UpdateLuaGlobals ()
RString GetCurThemeName () const
bool IsThemeLoaded () const
RString GetCurLanguage () const
RString GetCurThemeDir () const
RString GetNextTheme ()
RString GetNextSelectableTheme ()
void ReloadMetrics ()
void ReloadSubscribers ()
void ClearSubscribers ()
void GetOptionNames (vector< RString > &AddTo)
bool GetPathInfo (PathInfo &out, ElementCategory category, const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPath (ElementCategory category, const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPathB (const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPathF (const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPathG (const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPathS (const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
RString GetPathO (const RString &sMetricsGroup, const RString &sElement, bool bOptional=false)
void ClearThemePathCache ()
bool HasMetric (const RString &sMetricsGroup, const RString &sValueName)
void PushMetric (Lua *L, const RString &sMetricsGroup, const RString &sValueName)
RString GetMetric (const RString &sMetricsGroup, const RString &sValueName)
int GetMetricI (const RString &sMetricsGroup, const RString &sValueName)
float GetMetricF (const RString &sMetricsGroup, const RString &sValueName)
bool GetMetricB (const RString &sMetricsGroup, const RString &sValueName)
RageColor GetMetricC (const RString &sMetricsGroup, const RString &sValueName)
LuaReference GetMetricR (const RString &sMetricsGroup, const RString &sValueName)
apActorCommands GetMetricA (const RString &sMetricsGroup, const RString &sValueName)
void GetMetric (const RString &sMetricsGroup, const RString &sValueName, LuaReference &valueOut)
bool HasString (const RString &sMetricsGroup, const RString &sValueName)
RString GetString (const RString &sMetricsGroup, const RString &sValueName)
void GetString (const RString &sMetricsGroup, const RString &sValueName, RString &valueOut)
void FilterFileLanguages (vector< RString > &asElementPaths)
void GetMetricsThatBeginWith (const RString &sMetricsGroup, const RString &sValueName, set< RString > &vsValueNamesOut)
RString GetMetricsGroupFallback (const RString &sMetricsGroup)
void RunLuaScripts (const RString &sMask, bool bUseThemeDir=false)
void PushSelf (lua_State *L)
Static Public Member Functions
static void EvaluateString (RString &sText)
static RString GetBlankGraphicPath ()
static void Subscribe (IThemeMetric *p)
static void Unsubscribe (IThemeMetric *p)
Protected Member Functions
void LoadThemeMetrics (const RString &sThemeName, const RString &sLanguage_)
RString GetMetricRaw (const IniFile &ini, const RString &sMetricsGroup, const RString &sValueName)
bool GetMetricRawRecursive (const IniFile &ini, const RString &sMetricsGroup, const RString &sValueName, RString &sRet)
bool GetPathInfoToAndFallback (PathInfo &out, ElementCategory category, const RString &sMetricsGroup, const RString &sFile)
bool GetPathInfoToRaw (PathInfo &out, const RString &sThemeName, ElementCategory category, const RString &sMetricsGroup, const RString &sFile)
RString GetElementDir (const RString &sThemeName)
void GetOptionalLanguageIniPaths (vector< RString > &vsPathsOut, const RString &sThemeName, const RString &sLanguage)
RString GetDefaultLanguage ()
Static Protected Member Functions
static RString GetThemeDirFromName (const RString &sThemeName)
static RString GetMetricsIniPath (const RString &sThemeName)
static void GetLanguagesForTheme (const RString &sThemeName, vector< RString > &asLanguagesOut)
static RString GetLanguageIniPath (const RString &sThemeName, const RString &sLanguage)
Protected Attributes
RString m_sCurThemeName
RString m_sCurLanguage
bool m_bPseudoLocalize
Detailed Description
Manages theme paths and metrics.
Constructor & Destructor Documentation
ThemeManager()
ThemeManager::ThemeManager ()
References LuaManager::Get(), GetThemeNames(), L, LUA, m_bPseudoLocalize, m_sCurThemeName, PushSelf(), and LuaManager::Release().
~ThemeManager()
ThemeManager::~ThemeManager ()
References g_vThemes, LUA, SAFE_DELETE, and LuaManager::UnsetGlobal().
Member Function Documentation
ClearSubscribers()
void ThemeManager::ClearSubscribers ()
References FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
ClearThemePathCache()
void ThemeManager::ClearThemePathCache ()
References g_ThemePathCache, and NUM_ElementCategory.
Referenced by ReloadMetrics(), and SwitchThemeAndLanguage().
DoesLanguageExist()
bool ThemeManager::DoesLanguageExist (const RString & sLanguage)
References StdString::CStdStr< CT >::CompareNoCase(), and GetLanguages().
DoesThemeExist()
bool ThemeManager::DoesThemeExist (const RString & sThemeName)
References StdString::CStdStr< CT >::CompareNoCase(), and GetThemeNames().
Referenced by IsThemeSelectable(), and StepMania::ResetGame().
EvaluateString()
void ThemeManager::EvaluateString (RString & sText) static
References FontCharAliases::ReplaceMarkers().
Referenced by BitmapText::LoadFromNode().
FilterFileLanguages()
void ThemeManager::FilterFileLanguages (vector< RString > & asElementPaths)
References SpecialFiles::BASE_LANGUAGE, and m_sCurLanguage.
Referenced by GetPathInfoToRaw(), and ActorUtil::ResolvePath().
GetBlankGraphicPath()
RString ThemeManager::GetBlankGraphicPath () static
References SpecialFiles::BASE_THEME_NAME, EC_GRAPHICS, ElementCategoryToString(), and SpecialFiles::THEMES_DIR.
Referenced by BackgroundImpl::Layer::CreateBackground().
GetCurLanguage()
RString ThemeManager::GetCurLanguage () const inline
References m_sCurLanguage.
Referenced by LocalizedStringImplThemeMetric::GetLocalized(), Language(), and StepMania::ResetGame().
GetCurThemeDir()
RString ThemeManager::GetCurThemeDir () const inline
References GetThemeDirFromName(), and m_sCurThemeName.
Referenced by NoteSkinManager::LoadNoteSkinDataRecursive(), NoteSkinManager::RefreshNoteSkinData(), and ReloadMetrics().
GetCurThemeName()
RString ThemeManager::GetCurThemeName () const inline
References m_sCurThemeName.
Referenced by LunaThemeManager::GetThemeAuthor(), LunaThemeManager::GetThemeDisplayName(), Language(), ScreenSelectLanguage::MenuStart(), StepMania::ResetGame(), and Subscribe().
GetDefaultLanguage()
RString ThemeManager::GetDefaultLanguage () protected
References ArchHooks::GetPreferredLanguage(), and HOOKS.
Referenced by SwitchThemeAndLanguage().
GetElementDir()
RString ThemeManager::GetElementDir (const RString & sThemeName) protected
GetLanguageIniPath()
RString ThemeManager::GetLanguageIniPath (const RString & sThemeName, const RString & sLanguage) static protected
References GetThemeDirFromName(), and SpecialFiles::LANGUAGES_SUBDIR.
Referenced by LoadThemeMetrics().
GetLanguages()
void ThemeManager::GetLanguages (vector< RString > & AddTo)
References EqualsNoCase(), g_vThemes, and GetLanguagesForTheme().
Referenced by DoesLanguageExist(), ScreenSelectLanguage::Init(), Language(), and LanguageChoices().
GetLanguagesForTheme()
void ThemeManager::GetLanguagesForTheme (const RString & sThemeName, vector< RString > & asLanguagesOut) static protected
References FOREACH_CONST, GetDirListing(), GetThemeDirFromName(), SpecialFiles::LANGUAGES_SUBDIR, StdString::CStdStr< CT >::Left(), and SpecialFiles::METRICS_FILE.
Referenced by GetLanguages().
GetMetric() [1/2]
RString ThemeManager::GetMetric (const RString & sMetricsGroup, const RString & sValueName)
References GetAndConvertMetric().
Referenced by ScreenServiceAction::BeginScreen(), SMOProtocol::DealWithSMOnlinePack(), NoteSkinManager::GetDefaultNoteSkinName(), GetMetricA(), GetMetricR(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenNetRoom::HandleScreenMessage(), ScreenPackages::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::Init(), ScreenGameplay::Init(), ScreenManager::IsScreenNameValid(), PercentageDisplay::Load(), TextBanner::Load(), ScreenManager::MakeNewScreen(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), CodeDetector::RefreshCacheItems(), ScreenManager::ReloadOverlayScreens(), ETTProtocol::Update(), and LunaScreenManager::ValidateScreenName().
GetMetric() [2/2]
void ThemeManager::GetMetric (const RString & sMetricsGroup, const RString & sValueName, LuaReference & valueOut)
References LuaManager::Get(), L, LUA, PushMetric(), LuaManager::Release(), and LuaReference::SetFromStack().
GetMetricA()
apActorCommands ThemeManager::GetMetricA (const RString & sMetricsGroup, const RString & sValueName)
References GetMetric().
Referenced by Screen::BeginScreen(), ScreenMapControllers::Init(), ScreenPackages::Init(), HelpDisplay::Load(), TextBanner::Load(), ActorUtil::LoadCommandFromName(), and ScreenNetSelectBase::UpdateUsers().
GetMetricB()
bool ThemeManager::GetMetricB (const RString & sMetricsGroup, const RString & sValueName)
References GetAndConvertMetric().
Referenced by ScreenPackages::Init(), PercentageDisplay::Load(), StreamDisplay::Load(), and ScreenNetEvaluation::UpdateStats().
GetMetricC()
RageColor ThemeManager::GetMetricC (const RString & sMetricsGroup, const RString & sValueName)
References GetAndConvertMetric().
Referenced by RoomWheel::BuildFromRoomDatas(), and RoomWheel::Load().
GetMetricF()
float ThemeManager::GetMetricF (const RString & sMetricsGroup, const RString & sValueName)
References GetAndConvertMetric().
Referenced by ScreenMapControllers::BeginScreen(), ScreenNetEvaluation::Init(), HelpDisplay::Load(), StreamDisplay::Load(), ScreenNetEvaluation::RedoUserTexts(), ScreenMapControllers::SanityCheckWrapper(), ScreenMapControllers::SetListMode(), StreamDisplay::SetPercent(), and ActorUtil::SetXY().
GetMetricI()
int ThemeManager::GetMetricI (const RString & sMetricsGroup, const RString & sValueName)
References GetAndConvertMetric().
Referenced by StepMania::GetHighResolutionTextures(), ScreenMapControllers::Init(), PercentageDisplay::Load(), and GraphDisplay::Load().
GetMetricR()
LuaReference ThemeManager::GetMetricR (const RString & sMetricsGroup, const RString & sValueName)
References GetMetric().
Referenced by ScreenSelectMaster::Init(), ScreenOptions::Init(), PercentageDisplay::Load(), MenuTimer::Load(), StreamDisplay::Load(), WheelBase::Load(), and Profile::LoadCustomFunction().
GetMetricRaw()
RString ThemeManager::GetMetricRaw (const IniFile & ini, const RString & sMetricsGroup, const RString & sValueName) protected
References SpecialFiles::BASE_THEME_NAME, FAIL_M, GetMetricRawRecursive(), GetMetricsIniPath(), LoadedThemeData::iniMetrics, LoadedThemeData::iniStrings, LOG, m_sCurThemeName, ReloadMetrics(), LuaHelpers::ReportScriptError(), ssprintf(), RageException::Throw(), and RageLog::UserLog().
Referenced by GetString(), and PushMetric().
GetMetricRawRecursive()
bool ThemeManager::GetMetricRawRecursive (const IniFile & ini, const RString & sMetricsGroup, const RString & sValueName, RString & sRet) protected
References ASSERT, GetMetricsGroupFallback(), IniFile::GetValue(), and LuaHelpers::ReportScriptErrorFmt().
Referenced by GetMetricRaw(), GetMetricsGroupFallback(), HasMetric(), and HasString().
GetMetricsGroupFallback()
RString ThemeManager::GetMetricsGroupFallback (const RString & sMetricsGroup)
References ASSERT, LuaManager::Get(), GetMetricRawRecursive(), LoadedThemeData::iniMetrics, L, LUA, LuaHelpers::Pop(), LuaManager::Release(), and LuaHelpers::RunExpression().
Referenced by GetMetricRawRecursive(), GetMetricsThatBeginWith(), and GetPathInfoToAndFallback().
GetMetricsIniPath()
RString ThemeManager::GetMetricsIniPath (const RString & sThemeName) static protected
References GetThemeDirFromName(), and SpecialFiles::METRICS_FILE.
Referenced by GetMetricRaw(), and LoadThemeMetrics().
GetMetricsThatBeginWith()
void ThemeManager::GetMetricsThatBeginWith (const RString & sMetricsGroup, const RString & sValueName, set< RString > & vsValueNamesOut)
References XNode::GetChild(), GetMetricsGroupFallback(), LoadedThemeData::iniMetrics, StdString::CStdStr< CT >::Left(), and XNode::m_attrs.
Referenced by ActorUtil::LoadAllCommandsFromName().
GetNextSelectableTheme()
RString ThemeManager::GetNextSelectableTheme ()
References GetSelectableThemeNames(), and m_sCurThemeName.
Referenced by ScreenTitleMenu::Input().
GetNextTheme()
RString ThemeManager::GetNextTheme ()
References GetThemeNames(), and m_sCurThemeName.
GetNumSelectableThemes()
int ThemeManager::GetNumSelectableThemes ()
References GetSelectableThemeNames().
Referenced by LunaThemeManager::GetNumSelectableThemes().
GetOptionalLanguageIniPaths()
void ThemeManager::GetOptionalLanguageIniPaths (vector< RString > & vsPathsOut, const RString & sThemeName, const RString & sLanguage) protected
References GetDirListing(), GetThemeDirFromName(), and SpecialFiles::LANGUAGES_SUBDIR.
Referenced by LoadThemeMetrics().
GetOptionNames()
void ThemeManager::GetOptionNames (vector< RString > & AddTo)
References FOREACH_CONST_Attr, XNode::GetChild(), and LoadedThemeData::iniStrings.
GetPath()
RString ThemeManager::GetPath (ElementCategory category, const RString & sMetricsGroup, const RString & sElement, bool bOptional = false)
References ElementCategoryToString(), GetPathInfo(), LuaHelpers::ReportScriptErrorFmt(), and ThemeManager::PathInfo::sResolvedPath.
Referenced by GetPathB(), GetPathF(), GetPathG(), GetPathO(), and GetPathS().
GetPathB()
RString ThemeManager::GetPathB (const RString & sMetricsGroup, const RString & sElement, bool bOptional = false) inline
References EC_BGANIMATIONS, and GetPath().
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), ScreenSongOptions::Init(), ScreenSyncOverlay::Init(), ScreenSystemLayer::Init(), ScreenWithMenuElements::Init(), ScreenGameplay::Init(), and ScreenManager::PrepareScreen().
GetPathF()
RString ThemeManager::GetPathF (const RString & sMetricsGroup, const RString & sElement, bool bOptional = false) inline
References EC_FONTS, and GetPath().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenInstallOverlay::Init(), ScreenTestSound::Init(), ScreenNetSelectBase::Init(), ScreenReloadSongs::Init(), ScoreDisplayLifeTime::Init(), ScreenStatsOverlay::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), ScreenRanking::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), ModIcon::Load(), RoomInfoDisplay::Load(), OptionListRow::Load(), PercentageDisplay::Load(), LifeMeterBattery::Load(), TextBanner::Load(), MenuTimer::Load(), OptionRowType::Load(), StepsDisplay::Load(), PaneDisplay::Load(), RoomWheelItem::Load(), Font::Load(), BitmapText::LoadFromNode(), PercentageDisplay::LoadFromNode(), LyricDisplay::LyricDisplay(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), ScreenNetEvaluation::RedoUserTexts(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayOni::ScoreDisplayOni(), RoomInfoDisplay::SetRoomInfo(), and ScreenNetSelectBase::UpdateUsers().
GetPathG()
RString ThemeManager::GetPathG (const RString & sMetricsGroup, const RString & sElement, bool bOptional = false) inline
References EC_GRAPHICS, and GetPath().
Referenced by BackgroundImpl::Layer::CreateBackground(), StepMania::GetPreferredVideoModeParams(), GrooveRadar::GrooveRadar(), ScreenPlayerOptions::Init(), ScreenNetSelectBase::Init(), ScoreDisplayLifeTime::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), BeginnerHelper::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), ScreenTextEntryVisual::Init(), LifeMeterBar::LifeMeterBar(), DualScrollBar::Load(), RoomInfoDisplay::Load(), GradeDisplay::Load(), ModIcon::Load(), OptionListRow::Load(), ComboGraph::Load(), LifeMeterBattery::Load(), LifeMeterTime::Load(), GraphDisplay::Load(), MenuTimer::Load(), OptionRowType::Load(), StepsDisplay::Load(), StreamDisplay::Load(), WheelBase::Load(), PaneDisplay::Load(), OptionsList::Load(), RoomWheelItem::Load(), ScreenMapControllers::ActionRow::Load(), AutoActor::LoadAndSetName(), FadingBanner::LoadCustom(), Banner::LoadFallback(), Banner::LoadFallbackBG(), BGAnimationLayer::LoadFromAniLayerFile(), Sprite::LoadFromCached(), Banner::LoadFromSortOrder(), Banner::LoadGroupFallback(), ControllerStateDisplay::LoadInternal(), Banner::LoadMode(), Banner::LoadRandom(), Banner::LoadRoulette(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayOni::ScoreDisplayOni(), ScoreDisplayPercentage::ScoreDisplayPercentage(), ScrollBar::ScrollBar(), LoadingWindow_MacOSX::SetSplash(), sm_main(), SnapDisplay::SnapDisplay(), and WheelNotifyIcon::WheelNotifyIcon().
GetPathInfo()
bool ThemeManager::GetPathInfo (PathInfo & out, ElementCategory category, const RString & sMetricsGroup, const RString & sElement, bool bOptional = false)
References SpecialFiles::BASE_THEME_NAME, DEFAULT_FAIL, EC_OTHER, ElementCategoryToString(), FAIL_M, g_ThemePathCache, GetPathInfoToAndFallback(), GetThemeDirFromName(), LOG, m_sCurThemeName, MetricsGroupAndElementToFileName(), ReloadMetrics(), LuaHelpers::ScriptErrorMessage(), RageException::Throw(), RageLog::UserLog(), and RageLog::Warn().
Referenced by GetPath(), LunaThemeManager::GetPathInfoB(), GetPathInfoToRaw(), and AutoActor::LoadB().
GetPathInfoToAndFallback()
bool ThemeManager::GetPathInfoToAndFallback (PathInfo & out, ElementCategory category, const RString & sMetricsGroup, const RString & sFile) protected
References FOREACHD_CONST, g_vThemes, GetMetricsGroupFallback(), GetPathInfoToRaw(), MetricsGroupAndElementToFileName(), and LuaHelpers::ReportScriptErrorFmt().
Referenced by GetPathInfo().
GetPathInfoToRaw()
bool ThemeManager::GetPathInfoToRaw (PathInfo & out, const RString & sThemeName, ElementCategory category, const RString & sMetricsGroup, const RString & sFile) protected
References StdString::CStdStr< CT >::CompareNoCase(), DoesFileExist(), EC_BGANIMATIONS, EC_FONTS, EC_GRAPHICS, EC_OTHER, EC_SOUNDS, ElementCategoryToString(), FileNameToMetricsGroupAndElement(), FilterFileLanguages(), FT_Bitmap, FT_Directory, FT_Ini, FT_Lua, FT_Model, FT_Movie, FT_Sound, FT_Sprite, FT_Xml, g_ThemePathCache, GetDirListing(), GetExtension(), GetFileContents(), ActorUtil::GetFileType(), GetPathInfo(), GetThemeDirFromName(), MetricsGroupAndElementToFileName(), ReloadMetrics(), LuaHelpers::ReportScriptError(), ThemeManager::PathInfo::sMatchingElement, ThemeManager::PathInfo::sMatchingMetricsGroup, ThemeManager::PathInfo::sResolvedPath, ssprintf(), and RageException::Throw().
Referenced by GetPathInfoToAndFallback().
GetPathO()
RString ThemeManager::GetPathO (const RString & sMetricsGroup, const RString & sElement, bool bOptional = false) inline
References EC_OTHER, and GetPath().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), and SongManager::UpdatePreferredSort().
GetPathS()
RString ThemeManager::GetPathS (const RString & sMetricsGroup, const RString & sElement, bool bOptional = false) inline
References EC_SOUNDS, and GetPath().
Referenced by GameCommand::ApplySelf(), AutoScreenMessage(), ScreenGameplay::FailFadeRemovePlayer(), ScreenAttract::HandleScreenMessage(), ScreenSMOnlineLogin::Init(), GameplayAssist::Init(), ScreenNetRoom::Init(), ScreenWithMenuElements::Init(), ScreenMapControllers::Init(), ScreenNetSelectMusic::Init(), ScreenSetTime::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), LifeMeterBattery::LifeMeterBattery(), LifeMeterTime::Load(), MenuTimer::Load(), MusicWheel::Load(), WheelBase::Load(), and ScreenManager::ThemeChanged().
GetSelectableThemeNames()
void ThemeManager::GetSelectableThemeNames (vector< RString > & AddTo)
References GetThemeNames(), and IsThemeNameValid().
Referenced by GetNextSelectableTheme(), GetNumSelectableThemes(), LunaThemeManager::GetSelectableThemeNames(), RequestedTheme(), SwitchThemeAndLanguage(), and ThemeChoices().
GetString() [1/2]
RString ThemeManager::GetString (const RString & sMetricsGroup, const RString & sValueName)
References ASSERT, DEBUG_ASSERT, GetMetricRaw(), LoadedThemeData::iniStrings, m_bPseudoLocalize, PseudoLocalize(), StdString::CStdStr< CT >::Replace(), FontCharAliases::ReplaceMarkers(), and LuaHelpers::ReportScriptError().
Referenced by CustomDifficultyToLocalizedString(), GameButtonToLocalizedString(), StepsTypeInfo::GetLocalizedString(), GetString(), LunaThemeManager::GetString(), GradeToLocalizedString(), ScreenSelectLanguage::Init(), ScreenTextEntryVisual::Init(), LanguageChoices(), MusicWheelItem::LoadFromWheelItemData(), CommonMetrics::LocalizeOptionItem(), OPTION_EXPLANATION(), OptionRowHandler::OptionTitle(), LocalizedStringImplThemeMetric::Read(), ScreenMapControllers::SanityCheckWrapper(), and GameManager::StyleToLocalizedString().
GetString() [2/2]
void ThemeManager::GetString (const RString & sMetricsGroup, const RString & sValueName, RString & valueOut) inline
References GetString().
GetThemeAuthor()
RString ThemeManager::GetThemeAuthor (const RString & sThemeName)
References GetThemeDirFromName(), IniFile::GetValue(), and IniFile::ReadFile().
Referenced by LunaThemeManager::GetThemeAuthor().
GetThemeDirFromName()
RString ThemeManager::GetThemeDirFromName (const RString & sThemeName) static protected
References SpecialFiles::THEMES_DIR.
Referenced by GetCurThemeDir(), GetLanguageIniPath(), GetLanguagesForTheme(), GetMetricsIniPath(), GetOptionalLanguageIniPaths(), GetPathInfo(), GetPathInfoToRaw(), GetThemeAuthor(), GetThemeDisplayName(), and RunLuaScripts().
GetThemeDisplayName()
RString ThemeManager::GetThemeDisplayName (const RString & sThemeName)
References GetThemeDirFromName(), IniFile::GetValue(), and IniFile::ReadFile().
Referenced by LunaThemeManager::GetThemeDisplayName(), and ThemeChoices().
GetThemeNames()
void ThemeManager::GetThemeNames (vector< RString > & AddTo)
References GetDirListing(), StripCvsAndSvn(), StripMacResourceForks(), and SpecialFiles::THEMES_DIR.
Referenced by DoesThemeExist(), GetNextTheme(), GetSelectableThemeNames(), and ThemeManager().
HasMetric()
bool ThemeManager::HasMetric (const RString & sMetricsGroup, const RString & sValueName)
References GetMetricRawRecursive(), and LoadedThemeData::iniMetrics.
Referenced by LunaThemeManager::HasMetric(), ScreenSelectMaster::Init(), ScreenManager::IsScreenNameValid(), and GameCommand::LoadOne().
HasString()
bool ThemeManager::HasString (const RString & sMetricsGroup, const RString & sValueName)
References GetMetricRawRecursive(), and LoadedThemeData::iniStrings.
Referenced by StepsTypeInfo::GetLocalizedString(), GradeToLocalizedString(), LunaThemeManager::HasString(), CommonMetrics::LocalizeOptionItem(), and GameManager::StyleToLocalizedString().
IsThemeLoaded()
bool ThemeManager::IsThemeLoaded () const inline
References m_sCurThemeName.
Referenced by LocalizedStringImplThemeMetric::GetLocalized(), LocalizedStringImplThemeMetric::Read(), and ThemeMetric< AutoPtrCopyOnWrite >::Read().
IsThemeNameValid()
bool ThemeManager::IsThemeNameValid (RString const & name)
References StdString::CStdStr< CT >::Left().
Referenced by GetSelectableThemeNames(), and IsThemeSelectable().
IsThemeSelectable()
bool ThemeManager::IsThemeSelectable (RString const & name)
References DoesThemeExist(), and IsThemeNameValid().
Referenced by LunaGameManager::SetGame(), LunaThemeManager::SetTheme(), and SwitchThemeAndLanguage().
LoadThemeMetrics()
void ThemeManager::LoadThemeMetrics (const RString & sThemeName, const RString & sLanguage_) protected
References ASSERT_M, SpecialFiles::BASE_LANGUAGE, SpecialFiles::BASE_THEME_NAME, LoadedThemeData::ClearAll(), Regex::Compare(), StdString::CStdStr< CT >::CompareNoCase(), FOREACH_CONST, g_vThemes, GetCommandlineArgument(), GetLanguageIniPath(), GetMetricsIniPath(), GetOptionalLanguageIniPaths(), IniFile::GetValue(), LoadedThemeData::iniMetrics, LoadedThemeData::iniStrings, LOG, m_sCurLanguage, m_sCurThemeName, RageLog::MapLog(), XmlFileUtil::MergeIniUnder(), IniFile::ReadFile(), IniFile::SetValue(), Theme::sThemeName, and RageException::Throw().
Referenced by ReloadMetrics(), and SwitchThemeAndLanguage().
PushMetric()
void ThemeManager::PushMetric (Lua * L, const RString & sMetricsGroup, const RString & sValueName)
References EndsWith(), GetMetricRaw(), LoadedThemeData::iniMetrics, LuaHelpers::ParseCommandList(), LuaHelpers::ReportScriptError(), LuaHelpers::RunExpression(), and ssprintf().
Referenced by GetAndConvertMetric(), GetMetric(), and LunaThemeManager::GetMetric().
PushSelf()
void ThemeManager::PushSelf (lua_State * L)
Referenced by ThemeManager().
ReloadMetrics()
void ThemeManager::ReloadMetrics ()
References ClearThemePathCache(), FILEMAN, RageFileManager::FlushDirCache(), GetCurThemeDir(), LoadThemeMetrics(), m_sCurLanguage, m_sCurThemeName, and ReloadSubscribers().
Referenced by DebugLineReloadTheme::DoAndLog(), GetMetricRaw(), GetPathInfo(), GetPathInfoToRaw(), HandleGlobalInputs(), and LunaThemeManager::ReloadMetrics().
ReloadSubscribers()
void ThemeManager::ReloadSubscribers ()
References FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
Referenced by ScreenOptionsMaster::HandleScreenMessage(), ReloadMetrics(), and SwitchThemeAndLanguage().
RunLuaScripts()
void ThemeManager::RunLuaScripts (const RString & sMask, bool bUseThemeDir = false)
References FOREACH_CONST, g_vThemes, GetDirListing(), GetThemeDirFromName(), LOG, m_sCurThemeName, LuaHelpers::RunScriptFile(), SortRStringArray(), StripCvsAndSvn(), StripMacResourceForks(), RageLog::Trace(), and RageLog::Warn().
Referenced by LunaThemeManager::RunLuaScripts(), and UpdateLuaGlobals().
Subscribe()
void ThemeManager::Subscribe (IThemeMetric * p) static
References GetCurThemeName(), IThemeMetric::Read(), and SubscriptionManager< T >::Subscribe().
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::ThemeMetric().
SwitchThemeAndLanguage()
void ThemeManager::SwitchThemeAndLanguage (const RString & sThemeName, const RString & sLanguage, bool bPseudoLocalize, bool bForceThemeReload = false)
References ASSERT_M, ClearThemePathCache(), LocalizedStringImplThemeMetric::Create(), GetDefaultLanguage(), GetSelectableThemeNames(), IsThemeSelectable(), LoadThemeMetrics(), LOG, m_bPseudoLocalize, m_sCurLanguage, m_sCurThemeName, PrefsManager::m_sDefaultTheme, PrefsManager::m_sTheme, PREFSMAN, LocalizedString::RegisterLocalizer(), ReloadSubscribers(), SCREENMAN, ScreenManager::ThemeChanged(), RageLog::Trace(), UpdateLuaGlobals(), and RageLog::Warn().
Referenced by StepMania::InitializeCurrentGame(), Language(), ScreenSelectLanguage::MenuStart(), and StepMania::ResetGame().
Unsubscribe()
void ThemeManager::Unsubscribe (IThemeMetric * p) static
References SubscriptionManager< T >::Unsubscribe().
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::~ThemeMetric().
UpdateLuaGlobals()
void ThemeManager::UpdateLuaGlobals ()
References ScreenDimensions::ReloadScreenDimensions(), and RunLuaScripts().
Referenced by HandleGlobalInputs(), ScreenOptionsMaster::HandleScreenMessage(), and SwitchThemeAndLanguage().
Member Data Documentation
m_bPseudoLocalize
bool ThemeManager::m_bPseudoLocalize protected
Referenced by GetString(), SwitchThemeAndLanguage(), and ThemeManager().
m_sCurLanguage
RString ThemeManager::m_sCurLanguage protected
Referenced by FilterFileLanguages(), GetCurLanguage(), LoadThemeMetrics(), ReloadMetrics(), and SwitchThemeAndLanguage().
m_sCurThemeName
RString ThemeManager::m_sCurThemeName protected
Referenced by GetCurThemeDir(), GetCurThemeName(), GetMetricRaw(), GetNextSelectableTheme(), GetNextTheme(), GetPathInfo(), IsThemeLoaded(), LoadThemeMetrics(), ReloadMetrics(), RunLuaScripts(), SwitchThemeAndLanguage(), and ThemeManager().
The documentation for this class was generated from the following files:
ThemeManager.h
ThemeManager.cpp