Etterna: CompareLanguageTag Struct Reference
CompareLanguageTag Struct Reference
Public Member Functions
CompareLanguageTag (const RString &sLang)
bool operator() (const RString &sFile) const
Public Attributes
RString m_sLanguageString
Constructor & Destructor Documentation
CompareLanguageTag()
CompareLanguageTag::CompareLanguageTag (const RString & sLang) inline
References LOG, StdString::CStdStr< CT >::MakeLower(), and RageLog::Trace().
Member Function Documentation
operator()()
bool CompareLanguageTag::operator() (const RString & sFile) const inline
References StdString::CStdStr< CT >::MakeLower().
Member Data Documentation
m_sLanguageString
RString CompareLanguageTag::m_sLanguageString
The documentation for this struct was generated from the following file:
ThemeManager.cpp