Etterna: LoadingWindow_GtkModule.cpp File Reference
LoadingWindow_GtkModule.cpp File Reference
#include "LoadingWindow_GtkModule.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageSurface_Load.h"
#include "RageUtil.h"
#include "global.h"
#include <gtk/gtk.h>
Functions
const char * Init (int *argc, char ***argv)
void Shutdown ()
void SetText (const char *s)
void DeletePixels (guchar *pixels, gpointer data)
GdkPixbuf * MakePixbuf (const RageSurface *pSrc)
void SetIcon (const RageSurface *pSrcImg)
void SetSplash (const RageSurface *pSplash)
void SetProgress (int progress, int totalWork)
void SetIndeterminate (bool indeterminate)
Variables
static GtkWidget * label
static GtkWidget * window
static GtkWidget * splash
static GtkWidget * progressBar
Function Documentation
DeletePixels()
void DeletePixels (guchar * pixels, gpointer data)
Referenced by MakePixbuf().
Init()
const char* Init (int * argc, char *** argv)
References label, progressBar, splash, and window.
Referenced by ModsGroup< SongOptions >::Init(), and sm_main().
MakePixbuf()
GdkPixbuf* MakePixbuf (const RageSurface * pSrc)
References RageSurfaceUtils::Blit(), CreateSurface(), DeletePixels(), RageSurface::h, RageSurface::pitch, RageSurface::pixels, RageSurface::pixels_owned, and RageSurface::w.
Referenced by SetIcon(), and SetSplash().
SetIcon()
void SetIcon (const RageSurface * pSrcImg)
References MakePixbuf(), and window.
SetIndeterminate()
void SetIndeterminate (bool indeterminate)
References progressBar.
SetProgress()
void SetProgress (int progress, int totalWork)
References progressBar.
SetSplash()
void SetSplash (const RageSurface * pSplash)
References MakePixbuf(), and splash.
SetText()
void SetText (const char * s)
References label.
Referenced by ScreenPrompt::BeginScreen(), LyricDisplay::Init(), RoomInfoDisplay::SetRoomInfo(), and ScreenGameplay::Update().
Shutdown()
void Shutdown ()
References window.
Referenced by FindBackBufferType(), HandleException(), ShutdownGame(), LowLevelWindow_Win32::~LowLevelWindow_Win32(), and RageDisplay_D3D::~RageDisplay_D3D().
Variable Documentation
label
GtkWidget* label static
Referenced by Init(), RageSurface_Load_GIF(), and SetText().
progressBar
GtkWidget* progressBar static
Referenced by Init(), SetIndeterminate(), and SetProgress().
splash
GtkWidget* splash static
Referenced by Init(), and SetSplash().
window
GtkWidget* window static
Referenced by Init(), SetIcon(), Shutdown(), Player::UpdateHoldNotes(), and SMWindowDelegate::windowDidResize:.