Etterna: BMSSongLoader Class Reference
BMSSongLoader Class Reference
Public Member Functions
BMSSongLoader (RString songDir, Song *outSong)
bool Load (RString fileName)
void AddToSong ()
Private Attributes
RString dir
BMSSong song
vector< BMSStepsInfo > loadedSteps
Constructor & Destructor Documentation
BMSSongLoader()
BMSSongLoader::BMSSongLoader (RString songDir, Song * outSong)
Member Function Documentation
AddToSong()
void BMSSongLoader::AddToSong ()
References Song::AddBackgroundChange(), BMSChartInfo::artist, BACKGROUND_LAYER_1, BMSChartInfo::backgroundChanges, BMSChartInfo::backgroundFile, BMSChartInfo::bannerFile, ConvertString(), Difficulty_Beginner, Difficulty_Challenge, Difficulty_Easy, Difficulty_Edit, Difficulty_Hard, Difficulty_Medium, dir, FindLargestInitialSubstring(), BMSChartInfo::genre, Steps::GetFilename(), NotesLoader::GetMainAndSubTitlesFromFullTitle(), BMSSong::GetSong(), BMSStepsInfo::info, loadedSteps, LOG, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_PreviewFile, Song::m_sArtist, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sGenre, Song::m_sMainTitle, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sSongFileName, Song::m_sSubTitle, Steps::m_StepsType, Steps::m_Timing, main(), StdString::CStdStr< CT >::MakeLower(), BMSChartInfo::musicFile, NoteRowToBeat(), BMSChartInfo::previewFile, BMSChartInfo::previewStart, SBE_Centered, SBE_StretchNoLoop, SearchForDifficulty(), Steps::SetDifficulty(), SlideDuplicateDifficulties(), song, BMSChartInfo::stageFile, BMSStepsInfo::steps, StepsType_beat_double5, StepsType_beat_double7, StepsType_beat_single5, StepsType_beat_single7, StepsType_beat_versus5, StepsType_beat_versus7, BMSChartInfo::title, and RageLog::UserLog().
Load()
bool BMSSongLoader::Load (RString fileName)
References Song::AddSteps(), Song::CreateSteps(), dir, BMSSong::GetSong(), BMSChartReader::info, BMSChart::Load(), loadedSteps, BMSChartReader::Read(), Steps::SetFilename(), and song.
Member Data Documentation
dir
RString BMSSongLoader::dir private
Referenced by AddToSong(), and Load().
loadedSteps
vector<BMSStepsInfo> BMSSongLoader::loadedSteps private
Referenced by AddToSong(), and Load().
song
BMSSong BMSSongLoader::song private
Referenced by AddToSong(), and Load().
The documentation for this class was generated from the following file:
NotesLoaderBMS.cpp