Etterna: NotesWriterSM.cpp File Reference
NotesWriterSM.cpp File Reference
#include "global.h"
#include "NotesWriterSM.h"
#include "BackgroundUtil.h"
#include "Foreach.h"
#include "GameManager.h"
#include "LocalizedString.h"
#include "NoteTypes.h"
#include "ProfileManager.h"
#include "RageFile.h"
#include "Song.h"
#include "Steps.h"
#include "ThemeMetric.h"
Functions
static void WriteGlobalTags (RageFile &f, Song &out)
Write out the common tags for .SM files.
static RString JoinLineList (vector< RString > &lines)
Turn a vector of lines into a single line joined by newline characters.
static RString GetSMNotesTag (const Song &song, const Steps &in)
Retrieve the notes from the #NOTES tag.
Variables
ThemeMetric< bool > USE_CREDIT ("NotesWriterSM", "DescriptionUsesCreditField")
static LocalizedString DESTINATION_ALREADY_EXISTS ("NotesWriterSM", "Error renaming file. Destination file '%s' already exists.")
static LocalizedString ERROR_WRITING_FILE ("NotesWriterSM", "Error writing file '%s'.")
Function Documentation
GetSMNotesTag()
static RString GetSMNotesTag (const Song & song, const Steps & in) static
Retrieve the notes from the #NOTES tag.
Parameters
song the Song in question.
in the Steps in question.
Returns
the #NOTES tag.
References DifficultyToString(), Steps::GetChartName(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetMeter(), Steps::GetRadarValues(), Steps::GetSMNoteData(), IntToString(), Rage::join(), JoinLineList(), Steps::m_StepsTypeStr, Song::m_vsKeysoundFile, SmEscape(), split(), ssprintf(), and USE_CREDIT.
Referenced by NotesWriterSM::GetEditFileContents(), and NotesWriterSM::Write().
JoinLineList()
static RString JoinLineList (vector< RString > & lines) static
Turn a vector of lines into a single line joined by newline characters.
Parameters
lines the list of lines to join.
Returns
the joined lines.
References Rage::join(), and TrimRight().
Referenced by GetSMNotesTag().
WriteGlobalTags()
static void WriteGlobalTags (RageFile & f, Song & out) static
Write out the common tags for .SM files.
Parameters
f the file in question.
out the Song in question.
References DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, FAIL_M, FOREACH_BackgroundLayer, FOREACH_CONST, FOREACHM, Song::GetBackgroundChanges(), TimingSegment::GetBeat(), BPMSegment::GetBPM(), TimingData::GetBPMAtRow(), Song::GetForegroundChanges(), WarpSegment::GetLength(), StopSegment::GetPause(), TimingSegment::GetRow(), Song::GetSpecifiedLastBeat(), TimingData::GetTimingSegments(), Rage::join(), Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_sArtist, Song::m_sArtistTranslit, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_SelectionDisplay, Song::m_sGenre, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Song::m_vsKeysoundFile, NoteRowToBeat(), RageFile::PutLine(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENT_WARP, Song::SHOW_ALWAYS, Song::SHOW_NEVER, SmEscape(), ssprintf(), and RageFile::Write().
Referenced by NotesWriterSM::Write().
Variable Documentation
DESTINATION_ALREADY_EXISTS
LocalizedString DESTINATION_ALREADY_EXISTS("NotesWriterSM", "Error renaming file. Destination file '%s' already exists.") static
ERROR_WRITING_FILE
LocalizedString ERROR_WRITING_FILE("NotesWriterSM", "Error writing file '%s'.") static
USE_CREDIT
ThemeMetric<bool> USE_CREDIT("NotesWriterSM", "DescriptionUsesCreditField")
Referenced by GetSMNotesTag().