Etterna: NotesLoaderDWI.cpp File Reference
NotesLoaderDWI.cpp File Reference
#include "global.h"
#include "NotesLoaderDWI.h"
#include "Difficulty.h"
#include "GameInput.h"
#include "MsdFile.h"
#include "NoteData.h"
#include "NotesLoader.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "RageUtil_CharConversions.h"
#include "Song.h"
#include "Steps.h"
#include <map>
Enumerations
enum DanceNotes {
DANCE_NOTE_NONE = 0, DANCE_NOTE_PAD1_LEFT, DANCE_NOTE_PAD1_UPLEFT, DANCE_NOTE_PAD1_DOWN,
DANCE_NOTE_PAD1_UP, DANCE_NOTE_PAD1_UPRIGHT, DANCE_NOTE_PAD1_RIGHT, DANCE_NOTE_PAD2_LEFT,
DANCE_NOTE_PAD2_UPLEFT, DANCE_NOTE_PAD2_DOWN, DANCE_NOTE_PAD2_UP, DANCE_NOTE_PAD2_UPRIGHT,
DANCE_NOTE_PAD2_RIGHT
}
The different types of core DWI arrows and pads.
Functions
Difficulty DwiCompatibleStringToDifficulty (const RString &sDC)
static void DWIcharToNote (char c, GameController i, int &note1Out, int &note2Out, const RString &sPath)
Turn the individual character to the proper note.
static void DWIcharToNoteCol (char c, GameController i, int &col1Out, int &col2Out, const RString &sPath, map< int, int > &mapDanceNoteToColumn)
Determine the note column[s] to place notes.
static bool Is192 (const RString &sStepData, size_t pos)
Determine if the note in question is a 192nd note.
static StepsType GetTypeFromMode (const RString &mode)
static NoteData ParseNoteData (RString &step1, RString &step2, Steps &out, const RString &path)
static bool LoadFromDWITokens (RString sMode, RString sDescription, RString sNumFeet, RString sStepData1, RString sStepData2, Steps &out, const RString &sPath)
Look through the notes tag to extract the data.
static float ParseBrokenDWITimestamp (const RString &arg1, const RString &arg2, const RString &arg3)
Turn the DWI style timestamp into a compatible time for our system.
Variables
const int BEATS_PER_MEASURE = 4
All DWI files use 4 beats per measure.
Enumeration Type Documentation
DanceNotes
enum DanceNotes
The different types of core DWI arrows and pads.
Enumerator
DANCE_NOTE_NONE
DANCE_NOTE_PAD1_LEFT
DANCE_NOTE_PAD1_UPLEFT
DANCE_NOTE_PAD1_DOWN
DANCE_NOTE_PAD1_UP
DANCE_NOTE_PAD1_UPRIGHT
DANCE_NOTE_PAD1_RIGHT
DANCE_NOTE_PAD2_LEFT
DANCE_NOTE_PAD2_UPLEFT
DANCE_NOTE_PAD2_DOWN
DANCE_NOTE_PAD2_UP
DANCE_NOTE_PAD2_UPRIGHT
DANCE_NOTE_PAD2_RIGHT
Function Documentation
DWIcharToNote()
static void DWIcharToNote (char c, GameController i, int & note1Out, int & note2Out, const RString & sPath) static
Turn the individual character to the proper note.
Parameters
c The character in question.
i The player.
note1Out The first result based on the character.
note2Out The second result based on the character.
sPath the path to the file.
References DANCE_NOTE_NONE, DANCE_NOTE_PAD1_DOWN, DANCE_NOTE_PAD1_LEFT, DANCE_NOTE_PAD1_RIGHT, DANCE_NOTE_PAD1_UP, DANCE_NOTE_PAD1_UPLEFT, DANCE_NOTE_PAD1_UPRIGHT, FAIL_M, GameController_1, GameController_2, LOG, ssprintf(), and RageLog::UserLog().
Referenced by DWIcharToNoteCol().
DWIcharToNoteCol()
static void DWIcharToNoteCol (char c, GameController i, int & col1Out, int & col2Out, const RString & sPath, map< int, int > & mapDanceNoteToColumn) static
Determine the note column[s] to place notes.
Parameters
c The character in question.
i The player.
col1Out The first result based on the character.
col2Out The second result based on the character.
sPath the path to the file.
mapDanceNoteToColumn a map to pass to keep track of column info.
References DANCE_NOTE_NONE, and DWIcharToNote().
Referenced by ParseNoteData().
DwiCompatibleStringToDifficulty()
Difficulty DwiCompatibleStringToDifficulty (const RString & sDC)
References Difficulty_Beginner, Difficulty_Challenge, Difficulty_Easy, Difficulty_Edit, Difficulty_Hard, Difficulty_Invalid, Difficulty_Medium, and StdString::CStdStr< CT >::MakeLower().
Referenced by LoadFromDWITokens(), and DWILoader::LoadNoteDataFromSimfile().
GetTypeFromMode()
static StepsType GetTypeFromMode (const RString & mode) static
References ASSERT_M, StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, and StepsType_Invalid.
Referenced by LoadFromDWITokens(), and DWILoader::LoadNoteDataFromSimfile().
Is192()
static bool Is192 (const RString & sStepData, size_t pos) static
Determine if the note in question is a 192nd note.
DWI used to use <...> to indicate 1/192nd notes; at some point, <...> was changed to indicate jumps, and `' was used for 1/192nds. So, we have to do a check to figure out what it really means. If it contains 0s, it's most likely 192nds; otherwise, it's most likely a jump. Search for a 0 before the next >:
Parameters
sStepData the step data.
pos the position of the step data.
Returns
true if it's a 192nd note, false otherwise.
Referenced by ParseNoteData().
LoadFromDWITokens()
static bool LoadFromDWITokens (RString sMode, RString sDescription, RString sNumFeet, RString sStepData1, RString sStepData2, Steps & out, const RString & sPath) static
Look through the notes tag to extract the data.
Parameters
sMode the steps type.
sDescription the difficulty.
sNumFeet the meter.
sStepData1 the guaranteed step data.
sStepData2 used if sMode is double or couple.
out the step data.
sPath the path to the file.
Returns
the success or failure of the operation.
References CHECKPOINT_M, DwiCompatibleStringToDifficulty(), GetTypeFromMode(), Steps::m_StepsType, ParseNoteData(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetNoteData(), Steps::SetSavedToDisk(), StringToInt(), and Steps::TidyUpData().
Referenced by DWILoader::LoadFromDir().
ParseBrokenDWITimestamp()
static float ParseBrokenDWITimestamp (const RString & arg1, const RString & arg2, const RString & arg3) static
Turn the DWI style timestamp into a compatible time for our system.
This value can be in either "HH:MM:SS.sssss", "MM:SS.sssss", "SSS.sssss" or milliseconds.
Parameters
arg1 Either hours, minutes, or seconds, depending on other args.
arg2 Either minutes or seconds, depending on other args.
arg3 Seconds if not empty.
Returns
the proper timestamp.
References HHMMSSToSeconds(), and StringToFloat().
Referenced by DWILoader::LoadFromDir().
ParseNoteData()
static NoteData ParseNoteData (RString & step1, RString & step2, Steps & out, const RString & path) static
References ASSERT, BEATS_PER_MEASURE, BeatToNoteRow(), DANCE_NOTE_PAD1_DOWN, DANCE_NOTE_PAD1_LEFT, DANCE_NOTE_PAD1_RIGHT, DANCE_NOTE_PAD1_UP, DANCE_NOTE_PAD1_UPLEFT, DANCE_NOTE_PAD1_UPRIGHT, DANCE_NOTE_PAD2_DOWN, DANCE_NOTE_PAD2_LEFT, DANCE_NOTE_PAD2_RIGHT, DANCE_NOTE_PAD2_UP, DEFAULT_FAIL, DifficultyToString(), DWIcharToNoteCol(), FOREACH_NONEMPTY_ROW_IN_TRACK, Steps::GetDifficulty(), NoteData::GetNextTapNoteRowForTrack(), NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, Is192(), LOG, Steps::m_StepsType, StdString::CStdStr< CT >::Replace(), NoteData::SetNumTracks(), NoteData::SetTapNote(), StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, TAP_EMPTY, TAP_ORIGINAL_HOLD_HEAD, TAP_ORIGINAL_TAP, TapNoteType_Empty, TapNoteType_HoldHead, TapNote::type, and RageLog::UserLog().
Referenced by LoadFromDWITokens(), and DWILoader::LoadNoteDataFromSimfile().
Variable Documentation
BEATS_PER_MEASURE
const int BEATS_PER_MEASURE = 4
All DWI files use 4 beats per measure.
Referenced by ParseNoteData().