Etterna: TimingTagWriter Struct Reference
TimingTagWriter Struct Reference
Public Member Functions
TimingTagWriter (vector< RString > *pvsLines)
void Write (const int row, const char *value)
void Write (const int row, const float value)
void Write (const int row, const int value)
void Write (const int row, const int a, const int b)
void Write (const int row, const float a, const float b)
void Write (const int row, const float a, const float b, const unsigned short c)
void Init (const RString sTag)
void Finish ()
TimingTagWriter (vector< RString > *pvsLines)
void Write (const int row, const char *value)
void Write (const int row, const float value)
void Write (const int row, const int value)
void Write (const int row, const int a, const int b)
void Write (const int row, const float a, const float b)
void Write (const int row, const float a, const float b, const unsigned short c)
void Init (const RString sTag)
void Finish ()
Public Attributes
vector< RString > * m_pvsLines
RString m_sNext
Constructor & Destructor Documentation
TimingTagWriter() [1/2]
TimingTagWriter::TimingTagWriter (vector< RString > * pvsLines) inline
TimingTagWriter() [2/2]
TimingTagWriter::TimingTagWriter (vector< RString > * pvsLines) inline
Member Function Documentation
Finish() [1/2]
void TimingTagWriter::Finish () inline
Finish() [2/2]
void TimingTagWriter::Finish () inline
Init() [1/2]
void TimingTagWriter::Init (const RString sTag) inline
Init() [2/2]
void TimingTagWriter::Init (const RString sTag) inline
Write() [1/12]
void TimingTagWriter::Write (const int row, const char * value) inline
References NoteRowToBeat(), and ssprintf().
Referenced by GetTimingTags(), and Write().
Write() [2/12]
void TimingTagWriter::Write (const int row, const char * value) inline
References NoteRowToBeat(), and ssprintf().
Write() [3/12]
void TimingTagWriter::Write (const int row, const float value) inline
References ssprintf(), and Write().
Write() [4/12]
void TimingTagWriter::Write (const int row, const float value) inline
References ssprintf(), and Write().
Write() [5/12]
void TimingTagWriter::Write (const int row, const int value) inline
References ssprintf(), and Write().
Write() [6/12]
void TimingTagWriter::Write (const int row, const int value) inline
References ssprintf(), and Write().
Write() [7/12]
void TimingTagWriter::Write (const int row, const int a, const int b) inline
References ssprintf(), and Write().
Write() [8/12]
void TimingTagWriter::Write (const int row, const int a, const int b) inline
References ssprintf(), and Write().
Write() [9/12]
void TimingTagWriter::Write (const int row, const float a, const float b) inline
References ssprintf(), and Write().
Write() [10/12]
void TimingTagWriter::Write (const int row, const float a, const float b) inline
References ssprintf(), and Write().
Write() [11/12]
void TimingTagWriter::Write (const int row, const float a, const float b, const unsigned short c) inline
References ssprintf(), and Write().
Write() [12/12]
void TimingTagWriter::Write (const int row, const float a, const float b, const unsigned short c) inline
References ssprintf(), and Write().
Member Data Documentation
m_pvsLines
vector< RString > * TimingTagWriter::m_pvsLines
m_sNext
RString TimingTagWriter::m_sNext
The documentation for this struct was generated from the following files:
NotesWriterETT.cpp
NotesWriterSSC.cpp