Etterna: RageMovieTexture Class Reference
RageMovieTexture Class Reference abstract
#include <MovieTexture.h>
Public Member Functions
RageMovieTexture (const RageTextureID &ID)
~RageMovieTexture () override=default
void Update (float) override
void Reload () override=0
void SetPosition (float fSeconds) override=0
void SetPlaybackRate (float fRate) override=0
void SetLooping (bool=true) override
bool IsAMovie () const override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Invalidate ()
virtual unsigned GetTexHandle () const =0
virtual void DecodeSeconds (float)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Static Public Member Functions
static RageMovieTexture * Create (const RageTextureID &ID)
static bool GetFourCC (const RString &fn, RString &handler, RString &type)
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Additional Inherited Members
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
RageMovieTexture()
RageMovieTexture::RageMovieTexture (const RageTextureID & ID) inline
~RageMovieTexture()
RageMovieTexture::~RageMovieTexture () override default
Member Function Documentation
Create()
RageMovieTexture * RageMovieTexture::Create (const RageTextureID & ID) static
References ASSERT, COULDNT_CREATE_MOVIE_DRIVER, DriverList::Create(), RageMovieTextureDriver::Create(), DumpAVIDebugInfo(), RageTextureID::filename, FOREACH_CONST, g_sMovieDrivers, LocalizedString::GetValue(), LOG, MOVIE_DRIVERS_EMPTY, SAFE_DELETE, split(), RageException::Throw(), and RageLog::Trace().
Referenced by RageTextureManager::LoadTextureInternal().
GetFourCC()
bool RageMovieTexture::GetFourCC (const RString & fn, RString & handler, RString & type) static
References StdString::CStdStr< CT >::CompareNoCase(), ForceToAscii(), HANDLE_ERROR, RageFile::Open(), RageFile::Read(), RageFile::Seek(), and splitpath().
Referenced by DumpAVIDebugInfo().
IsAMovie()
bool RageMovieTexture::IsAMovie () const inline override virtual
Reimplemented from RageTexture.
Reload()
void RageMovieTexture::Reload () override pure virtual
Reimplemented from RageTexture.
Implemented in MovieTexture_Generic, MovieTexture_DShow, and MovieTexture_Null.
SetLooping()
void RageMovieTexture::SetLooping (bool = true) inline override virtual
Reimplemented from RageTexture.
Reimplemented in MovieTexture_Generic, MovieTexture_DShow, and MovieTexture_Null.
SetPlaybackRate()
void RageMovieTexture::SetPlaybackRate (float fRate) override pure virtual
Reimplemented from RageTexture.
Implemented in MovieTexture_Generic, MovieTexture_DShow, and MovieTexture_Null.
SetPosition()
void RageMovieTexture::SetPosition (float fSeconds) override pure virtual
Reimplemented from RageTexture.
Implemented in MovieTexture_Generic, MovieTexture_DShow, and MovieTexture_Null.
Update()
void RageMovieTexture::Update (float) inline override virtual
Reimplemented from RageTexture.
Reimplemented in MovieTexture_DShow, and MovieTexture_Null.
The documentation for this class was generated from the following files:
MovieTexture.h
MovieTexture.cpp