Etterna: ProfileManager Class Reference
ProfileManager Class Reference
#include <ProfileManager.h>
Public Member Functions
ProfileManager ()
~ProfileManager ()
void Init (LoadingWindow *ld)
bool FixedProfiles () const
void UnloadAllLocalProfiles ()
void RefreshLocalProfilesFromDisk ()
void RefreshLocalProfilesFromDisk (LoadingWindow *ld)
const Profile * GetLocalProfile (const RString &sProfileID) const
Profile * GetLocalProfile (const RString &sProfileID)
Profile * GetLocalProfileFromIndex (int iIndex)
RString GetLocalProfileIDFromIndex (int iIndex)
bool CreateLocalProfile (const RString &sName, RString &sProfileIDOut)
void AddLocalProfileByID (Profile *pProfile, const RString &sProfileID)
bool RenameLocalProfile (const RString &sProfileID, const RString &sNewName)
bool DeleteLocalProfile (const RString &sProfileID)
void GetLocalProfileIDs (vector< RString > &vsProfileIDsOut) const
void GetLocalProfileDisplayNames (vector< RString > &vsProfileDisplayNamesOut) const
int GetLocalProfileIndexFromID (const RString &sProfileID) const
int GetNumLocalProfiles () const
RString GetStatsPrefix ()
void SetStatsPrefix (RString const &prefix)
bool LoadFirstAvailableProfile (PlayerNumber pn, bool bLoadEdits=true)
bool LoadLocalProfileFromMachine (PlayerNumber pn)
bool SaveProfile (PlayerNumber pn) const
bool ConvertProfile (PlayerNumber pn)
bool SaveLocalProfile (const RString &sProfileID)
void UnloadProfile (PlayerNumber pn)
void MergeLocalProfiles (RString const &from_id, RString const &to_id)
void ChangeProfileType (int index, ProfileType new_type)
void MoveProfilePriority (int index, bool up)
void IncrementToastiesCount (PlayerNumber pn)
void AddStepTotals (PlayerNumber pn, int iNumTapsAndHolds, int iNumJumps, int iNumHolds, int iNumRolls, int iNumMines, int iNumHands, int iNumLifts)
bool IsPersistentProfile (PlayerNumber pn) const
bool IsPersistentProfile (ProfileSlot slot) const
const Profile * GetProfile (PlayerNumber pn) const
Profile * GetProfile (PlayerNumber pn)
const Profile * GetProfile (ProfileSlot slot) const
Profile * GetProfile (ProfileSlot slot)
const RString & GetProfileDir (ProfileSlot slot) const
RString GetPlayerName (PlayerNumber pn) const
bool LastLoadWasTamperedOrCorrupt (PlayerNumber pn) const
bool LastLoadWasFromLastGood (PlayerNumber pn) const
int GetSongNumTimesPlayed (const Song *pSong, ProfileSlot card) const
bool IsSongNew (const Song *pSong) const
void AddStepsScore (const Song *pSong, const Steps *pSteps, PlayerNumber pn, const HighScore &hs, int &iPersonalIndexOut, int &iMachineIndexOut)
void IncrementStepsPlayCount (const Song *pSong, const Steps *pSteps, PlayerNumber pn)
void AddCategoryScore (StepsType st, RankingCategory rc, PlayerNumber pn, const HighScore &hs, int &iPersonalIndexOut, int &iMachineIndexOut)
void IncrementCategoryPlayCount (StepsType st, RankingCategory rc, PlayerNumber pn)
void PushSelf (lua_State *L)
Static Public Attributes
static Preference1D< RString > m_sDefaultLocalProfileID
Private Member Functions
ProfileLoadResult LoadProfile (PlayerNumber pn, const RString &sProfileDir)
Private Attributes
RString m_sProfileDir [NUM_PLAYERS]
RString m_stats_prefix
Profile * dummy
bool m_bLastLoadWasTamperedOrCorrupt [NUM_PLAYERS]
bool m_bLastLoadWasFromLastGood [NUM_PLAYERS]
bool m_bNeedToBackUpLastLoad [NUM_PLAYERS]
bool m_bNewProfile [NUM_PLAYERS]
Constructor & Destructor Documentation
ProfileManager()
ProfileManager::ProfileManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~ProfileManager()
ProfileManager::~ProfileManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
AddCategoryScore()
void ProfileManager::AddCategoryScore (StepsType st, RankingCategory rc, PlayerNumber pn, const HighScore & hs, int & iPersonalIndexOut, int & iMachineIndexOut)
References Profile::AddCategoryHighScore(), GetProfile(), IsPersistentProfile(), RANKING_TO_FILL_IN_MARKER, and HighScore::SetName().
AddLocalProfileByID()
void ProfileManager::AddLocalProfileByID (Profile * pProfile, const RString & sProfileID)
References InsertProfileIntoList(), LocalProfileIDToDir(), DirAndProfile::profile, and DirAndProfile::sDir.
Referenced by CreateLocalProfile().
AddStepsScore()
void ProfileManager::AddStepsScore (const Song * pSong, const Steps * pSteps, PlayerNumber pn, const HighScore & hs, int & iPersonalIndexOut, int & iMachineIndexOut)
References Profile::AddStepsHighScore(), GAMESTATE, HighScore::GetPercentDP(), GetProfile(), GameState::IsEventMode(), IsPersistentProfile(), Profile::m_sLastUsedHighScoreName, max(), RANKING_TO_FILL_IN_MARKER, HighScore::SetName(), and HighScore::SetPercentDP().
AddStepTotals()
void ProfileManager::AddStepTotals (PlayerNumber pn, int iNumTapsAndHolds, int iNumJumps, int iNumHolds, int iNumRolls, int iNumMines, int iNumHands, int iNumLifts)
References Profile::AddStepTotals(), GetProfile(), and IsPersistentProfile().
Referenced by StatsManager::CommitStatsToProfiles().
ChangeProfileType()
void ProfileManager::ChangeProfileType (int index, ProfileType new_type)
References g_vLocalProfile, InsertProfileIntoList(), Profile::m_Type, and DirAndProfile::profile.
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
ConvertProfile()
bool ProfileManager::ConvertProfile (PlayerNumber pn)
References GetProfile(), Profile::ImportScoresToEtterna(), LAST_GOOD_SUBDIR, m_bNeedToBackUpLastLoad, m_sProfileDir, and Profile::MoveBackupToDir().
Referenced by LunaProfileManager::ConvertProfile().
CreateLocalProfile()
bool ProfileManager::CreateLocalProfile (const RString & sName, RString & sProfileIDOut)
References AddLocalProfileByID(), ASSERT, ASSERT_M, CHARMAN, FOREACH_CONST, GetLocalProfileIDs(), CharacterManager::GetRandomCharacter(), ID_DIGITS_STR, LocalProfileIDToDir(), PrefsManager::m_bSignProfileData, Character::m_sCharacterID, Profile::m_sCharacterID, Profile::m_sDisplayName, Profile::m_sProfileID, max(), MAX_ID, PREFSMAN, Profile::SaveAllToDir(), and ssprintf().
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage(), and Init().
DeleteLocalProfile()
bool ProfileManager::DeleteLocalProfile (const RString & sProfileID)
References ASSERT, DeleteRecursive(), FILEMAN, RageFileManager::FlushDirCache(), FOREACH, FOREACH_CONST, g_vLocalProfile, GetLocalProfile(), LocalProfileIDToDir(), LOG, m_sDefaultLocalProfileID, and RageLog::Warn().
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
FixedProfiles()
bool ProfileManager::FixedProfiles () const
References FIXED_PROFILES.
Referenced by ScreenOptionsManageProfiles::ProcessMenuStart().
GetLocalProfile() [1/2]
const Profile * ProfileManager::GetLocalProfile (const RString & sProfileID) const
References dummy, FOREACH_CONST, g_vLocalProfile, and LocalProfileIDToDir().
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsEditProfile::BeginScreen(), DeleteLocalProfile(), ScreenOptionsEditProfile::ExportOptions(), GameState::GetEditLocalProfile(), LunaProfileManager::GetLocalProfile(), GetProfile(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenOptionsEditProfile::ImportOptions(), Init(), LoadLocalProfileFromMachine(), MergeLocalProfiles(), RenameLocalProfile(), SaveLocalProfile(), and ValidateLocalProfileName().
GetLocalProfile() [2/2]
Profile* ProfileManager::GetLocalProfile (const RString & sProfileID) inline
GetLocalProfileDisplayNames()
void ProfileManager::GetLocalProfileDisplayNames (vector< RString > & vsProfileDisplayNamesOut) const
References FOREACH_CONST, and g_vLocalProfile.
Referenced by LunaProfileManager::GetLocalProfileDisplayNames(), ScreenSMOnlineLogin::Init(), ScreenOptionsManageProfiles::ProcessMenuStart(), and ValidateLocalProfileName().
GetLocalProfileFromIndex()
Profile * ProfileManager::GetLocalProfileFromIndex (int iIndex)
References g_vLocalProfile.
Referenced by LunaProfileManager::GetLocalProfileFromIndex().
GetLocalProfileIDFromIndex()
RString ProfileManager::GetLocalProfileIDFromIndex (int iIndex)
References g_vLocalProfile, and LocalProfileDirToID().
Referenced by ScreenSelectProfile::Finish(), and LunaProfileManager::GetLocalProfileIDFromIndex().
GetLocalProfileIDs()
void ProfileManager::GetLocalProfileIDs (vector< RString > & vsProfileIDsOut) const
References FOREACH_CONST, g_vLocalProfile, and LocalProfileDirToID().
Referenced by ScreenOptionsManageProfiles::BeginScreen(), CreateLocalProfile(), ScreenSMOnlineLogin::ExportOptions(), LunaProfileManager::GetLocalProfileIDs(), ScreenSMOnlineLogin::GetSelectedProfileID(), and ScreenSMOnlineLogin::ImportOptions().
GetLocalProfileIndexFromID()
int ProfileManager::GetLocalProfileIndexFromID (const RString & sProfileID) const
References FOREACH_CONST, g_vLocalProfile, and LocalProfileIDToDir().
Referenced by LunaProfileManager::GetLocalProfileIndexFromID().
GetNumLocalProfiles()
int ProfileManager::GetNumLocalProfiles () const
References g_vLocalProfile.
Referenced by ScreenSelectProfile::Finish(), LunaProfileManager::GetLocalProfileFromIndex(), LunaProfileManager::GetLocalProfileIDFromIndex(), LunaProfileManager::GetNumLocalProfiles(), ScreenOptionsManageProfiles::HandleScreenMessage(), and ScreenSelectProfile::SetProfileIndex().
GetPlayerName()
RString ProfileManager::GetPlayerName (PlayerNumber pn) const
References Profile::GetDisplayNameOrHighScoreName(), and GetProfile().
Referenced by GameState::GetPlayerDisplayName(), and LunaProfileManager::GetPlayerName().
GetProfile() [1/4]
const Profile * ProfileManager::GetProfile (PlayerNumber pn) const
References GetLocalProfile(), LocalProfileDirToID(), m_sProfileDir, and PLAYER_1.
Referenced by AddCategoryScore(), AddStepsScore(), AddStepTotals(), ScreenSelectMusic::AfterStepsOrTrailChange(), ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), GameState::CommitStageStats(), StatsManager::CommitStatsToProfiles(), ConvertProfile(), LunaScoreGoal::Delete(), DebugLineClearProfileStats::DoAndLog(), DebugLineFillProfileStats::DoAndLog(), StageStats::FinalizeScores(), GameState::FinishStage(), LunaProfileManager::GetMachineProfile(), PaneDisplay::GetPaneTextAndLevel(), GetPlayerName(), SongManager::GetPlaylists(), GetProfile(), LunaProfileManager::GetProfile(), GameState::GetRankingFeats(), SongUtil::GetSectionNameFromSongAndSort(), GetSongNumTimesPlayed(), IncrementCategoryPlayCount(), IncrementStepsPlayCount(), IncrementToastiesCount(), ScreenNetSelectMusic::Init(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), ScreenEvaluation::Input(), GameState::LoadCurrentSettingsFromProfile(), LoadLocalProfileFromMachine(), LoadProfile(), GameState::LoadProfiles(), GameState::ResetStageStatistics(), GameState::SaveCurrentSettingsToProfile(), SaveProfile(), ScreenGameplay::SaveReplay(), SongUtil::SortSongPointerArrayByGrades(), SongUtil::SortSongPointerArrayByNumPlays(), and StepsUtil::SortStepsPointerArrayByNumPlays().
GetProfile() [2/4]
Profile* ProfileManager::GetProfile (PlayerNumber pn) inline
GetProfile() [3/4]
const Profile * ProfileManager::GetProfile (ProfileSlot slot) const
References FAIL_M, GetProfile(), ProfileSlot_Player1, and ProfileSlot_Player2.
GetProfile() [4/4]
Profile* ProfileManager::GetProfile (ProfileSlot slot) inline
GetProfileDir()
const RString & ProfileManager::GetProfileDir (ProfileSlot slot) const
References FAIL_M, m_sProfileDir, ProfileSlot_Player1, and ProfileSlot_Player2.
Referenced by LunaProfileManager::GetProfileDir(), ScreenEvaluation::Input(), LuaFunc_SaveScreenshot(), and DBProfile::WriteReplayData().
GetSongNumTimesPlayed()
int ProfileManager::GetSongNumTimesPlayed (const Song * pSong, ProfileSlot card) const
References GetProfile(), and Profile::GetSongNumTimesPlayed().
Referenced by LunaProfileManager::GetSongNumTimesPlayed(), and IsSongNew().
GetStatsPrefix()
RString ProfileManager::GetStatsPrefix () inline
References m_stats_prefix.
Referenced by LunaProfileManager::GetStatsPrefix(), Profile::HandleStatsPrefixChange(), XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), XMLProfile::SaveEttXmlToDir(), and XMLProfile::SaveStatsXmlToDir().
IncrementCategoryPlayCount()
void ProfileManager::IncrementCategoryPlayCount (StepsType st, RankingCategory rc, PlayerNumber pn)
References GetProfile(), Profile::IncrementCategoryPlayCount(), and IsPersistentProfile().
IncrementStepsPlayCount()
void ProfileManager::IncrementStepsPlayCount (const Song * pSong, const Steps * pSteps, PlayerNumber pn)
References GetProfile(), Profile::IncrementStepsPlayCount(), and IsPersistentProfile().
Referenced by ScreenGameplay::LoadNextSong().
IncrementToastiesCount()
void ProfileManager::IncrementToastiesCount (PlayerNumber pn)
References GetProfile(), IsPersistentProfile(), and Profile::m_iNumToasties.
Referenced by ScoreKeeperNormal::HandleTapRowScore().
Init()
void ProfileManager::Init (LoadingWindow * ld)
References ASSERT, ASSERT_M, CHARMAN, CreateLocalProfile(), dummy, FIXED_PROFILE_CHARACTER_ID, FIXED_PROFILES, FOREACH_PlayerNumber, g_vLocalProfile, CharacterManager::GetCharacterFromID(), Character::GetDisplayName(), GetLocalProfile(), m_bLastLoadWasFromLastGood, m_bLastLoadWasTamperedOrCorrupt, m_bNeedToBackUpLastLoad, m_bNewProfile, Profile::m_sCharacterID, m_sProfileDir, NUM_FIXED_PROFILES, PLAYER_1, RefreshLocalProfilesFromDisk(), and SaveLocalProfile().
Referenced by sm_main().
IsPersistentProfile() [1/2]
bool ProfileManager::IsPersistentProfile (PlayerNumber pn) const inline
References m_sProfileDir.
Referenced by AddCategoryScore(), AddStepsScore(), AddStepTotals(), StageStats::FinalizeScores(), PaneDisplay::GetPaneTextAndLevel(), GameState::HaveProfileToLoad(), GameState::HaveProfileToSave(), IncrementCategoryPlayCount(), IncrementStepsPlayCount(), IncrementToastiesCount(), ScreenEvaluation::Input(), LunaProfileManager::IsPersistentProfile(), IsSelectProfilePersistent(), GameState::LoadCurrentSettingsFromProfile(), GameState::LoadProfiles(), MusicWheelItem::RefreshGrades(), GameState::SaveCurrentSettingsToProfile(), GameState::SavePlayerProfile(), SongUtil::SortSongPointerArrayByNumPlays(), and StepsUtil::SortStepsPointerArrayByNumPlays().
IsPersistentProfile() [2/2]
bool ProfileManager::IsPersistentProfile (ProfileSlot slot) const
IsSongNew()
bool ProfileManager::IsSongNew (const Song * pSong) const inline
References GetSongNumTimesPlayed(), and ProfileSlot_Player1.
Referenced by LunaProfileManager::IsSongNew(), and ScreenSelectMusic::SelectCurrent().
LastLoadWasFromLastGood()
bool ProfileManager::LastLoadWasFromLastGood (PlayerNumber pn) const
References m_bLastLoadWasFromLastGood, and m_sProfileDir.
LastLoadWasTamperedOrCorrupt()
bool ProfileManager::LastLoadWasTamperedOrCorrupt (PlayerNumber pn) const
References m_bLastLoadWasTamperedOrCorrupt, and m_sProfileDir.
Referenced by LunaProfileManager::LastLoadWasTamperedOrCorrupt().
LoadFirstAvailableProfile()
bool ProfileManager::LoadFirstAvailableProfile (PlayerNumber pn, bool bLoadEdits = true)
References LoadLocalProfileFromMachine().
Referenced by ScreenEvaluation::Init(), and GameState::LoadProfiles().
LoadLocalProfileFromMachine()
bool ProfileManager::LoadLocalProfileFromMachine (PlayerNumber pn)
References GetLocalProfile(), GetProfile(), Profile::LoadCustomFunction(), LocalProfileIDToDir(), m_bLastLoadWasFromLastGood, m_sDefaultLocalProfileID, and m_sProfileDir.
Referenced by ScreenSelectProfile::Finish(), ScreenSMOnlineLogin::HandleScreenMessage(), and LoadFirstAvailableProfile().
LoadProfile()
ProfileLoadResult ProfileManager::LoadProfile (PlayerNumber pn, const RString & sProfileDir) private
References ASSERT, GetProfile(), LAST_GOOD_SUBDIR, Profile::LoadAllFromDir(), LOG, m_bLastLoadWasFromLastGood, m_bLastLoadWasTamperedOrCorrupt, m_bNeedToBackUpLastLoad, PrefsManager::m_bSignProfileData, m_sProfileDir, PREFSMAN, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, StdString::CStdStr< CT >::Right(), and RageLog::Trace().
MergeLocalProfiles()
void ProfileManager::MergeLocalProfiles (RString const & from_id, RString const & to_id)
References GetLocalProfile(), LocalProfileIDToDir(), and Profile::MergeScoresFromOtherProfile().
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
MoveProfilePriority()
void ProfileManager::MoveProfilePriority (int index, bool up)
References g_vLocalProfile, Profile::m_ListPriority, Profile::m_Type, DirAndProfile::profile, Profile::SaveTypeToDir(), and DirAndProfile::sDir.
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
PushSelf()
void ProfileManager::PushSelf (lua_State * L)
Referenced by ProfileManager().
RefreshLocalProfilesFromDisk() [1/2]
void ProfileManager::RefreshLocalProfilesFromDisk ()
Referenced by Init().
RefreshLocalProfilesFromDisk() [2/2]
void ProfileManager::RefreshLocalProfilesFromDisk (LoadingWindow * ld)
References add_category_to_global_list(), FOREACH, FOREACH_CONST, g_vLocalProfile, GetDirListing(), Profile::LoadTypeFromDir(), PrefsManager::m_bSignProfileData, Profile::m_ListPriority, Profile::m_sProfileID, Profile::m_Type, PREFSMAN, DirAndProfile::profile, ProfileType_Guest, ProfileType_Normal, ProfileType_Test, DirAndProfile::sDir, LoadingWindow::SetText(), and UnloadAllLocalProfiles().
RenameLocalProfile()
bool ProfileManager::RenameLocalProfile (const RString & sProfileID, const RString & sNewName)
References ASSERT, GetLocalProfile(), LocalProfileIDToDir(), PrefsManager::m_bSignProfileData, and PREFSMAN.
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage().
SaveLocalProfile()
bool ProfileManager::SaveLocalProfile (const RString & sProfileID)
References ASSERT, GetLocalProfile(), LocalProfileIDToDir(), PrefsManager::m_bSignProfileData, PREFSMAN, and Profile::SaveAllToDir().
Referenced by ScreenOptionsEditProfile::HandleScreenMessage(), Init(), and LunaProfileManager::SaveLocalProfile().
SaveProfile()
bool ProfileManager::SaveProfile (PlayerNumber pn) const
References GetProfile(), LAST_GOOD_SUBDIR, m_bNeedToBackUpLastLoad, PrefsManager::m_bSignProfileData, m_sProfileDir, Profile::MoveBackupToDir(), PREFSMAN, and Profile::SaveAllToDir().
Referenced by LunaPlaylist::AddChart(), LunaChart::ChangeRate(), LunaPlaylist::DeleteChart(), LunaSongManager::DeletePlaylist(), Profile::ImportScoresToEtterna(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), makePlaylist(), GameState::SavePlayerProfile(), and LunaProfileManager::SaveProfile().
SetStatsPrefix()
void ProfileManager::SetStatsPrefix (RString const & prefix)
References g_vLocalProfile, PrefsManager::m_bSignProfileData, m_stats_prefix, and PREFSMAN.
Referenced by LunaProfileManager::SetStatsPrefix().
UnloadAllLocalProfiles()
void ProfileManager::UnloadAllLocalProfiles ()
References g_vLocalProfile.
Referenced by RefreshLocalProfilesFromDisk().
UnloadProfile()
void ProfileManager::UnloadProfile (PlayerNumber pn)
References SongManager::FreeAllLoadedFromProfile(), m_bLastLoadWasFromLastGood, m_bLastLoadWasTamperedOrCorrupt, m_bNeedToBackUpLastLoad, m_sProfileDir, and SONGMAN.
Referenced by ScreenSelectProfile::Finish(), and GameState::ResetPlayer().
Member Data Documentation
dummy
Profile* ProfileManager::dummy private
Referenced by GetLocalProfile(), and Init().
m_bLastLoadWasFromLastGood
bool ProfileManager::m_bLastLoadWasFromLastGood[NUM_PLAYERS] private
Referenced by Init(), LastLoadWasFromLastGood(), LoadLocalProfileFromMachine(), LoadProfile(), and UnloadProfile().
m_bLastLoadWasTamperedOrCorrupt
bool ProfileManager::m_bLastLoadWasTamperedOrCorrupt[NUM_PLAYERS] private
Referenced by Init(), LastLoadWasTamperedOrCorrupt(), LoadProfile(), and UnloadProfile().
m_bNeedToBackUpLastLoad
bool ProfileManager::m_bNeedToBackUpLastLoad[NUM_PLAYERS] mutable private
Referenced by ConvertProfile(), Init(), LoadProfile(), SaveProfile(), and UnloadProfile().
m_bNewProfile
bool ProfileManager::m_bNewProfile[NUM_PLAYERS] private
Referenced by Init().
m_sDefaultLocalProfileID
Preference1D< RString > ProfileManager::m_sDefaultLocalProfileID static
Referenced by GameCommand::ApplySelf(), ScreenOptionsManageProfiles::BeginScreen(), DeleteLocalProfile(), GameCommand::DescribesCurrentMode(), ScreenSMOnlineLogin::ExportOptions(), ScreenSelectProfile::Finish(), ScreenOptionsManageProfiles::HandleScreenMessage(), GameState::HaveProfileToLoad(), ScreenSMOnlineLogin::ImportOptions(), and LoadLocalProfileFromMachine().
m_sProfileDir
RString ProfileManager::m_sProfileDir[NUM_PLAYERS] private
Referenced by ConvertProfile(), GetProfile(), GetProfileDir(), Init(), IsPersistentProfile(), LastLoadWasFromLastGood(), LastLoadWasTamperedOrCorrupt(), LoadLocalProfileFromMachine(), LoadProfile(), SaveProfile(), and UnloadProfile().
m_stats_prefix
RString ProfileManager::m_stats_prefix private
Referenced by GetStatsPrefix(), and SetStatsPrefix().
The documentation for this class was generated from the following files:
ProfileManager.h
ProfileManager.cpp