Etterna: RageSoundDriver_ALSA9_Software Class Reference
RageSoundDriver_ALSA9_Software Class Reference
#include <RageSoundDriver_ALSA9_Software.h>
Public Member Functions
RageSoundDriver_ALSA9_Software ()
~RageSoundDriver_ALSA9_Software ()
RString Init ()
int64_t GetPosition () const
float GetPlayLatency () const
int GetSampleRate () const
void SetupDecodingThread ()
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void MixerThread ()
bool GetData ()
Static Private Member Functions
static int MixerThread_start (void *p)
Private Attributes
bool m_bShutdown
int m_iSampleRate
Alsa9Buf * m_pPCM
RageThread m_MixingThread
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_ALSA9_Software()
RageSoundDriver_ALSA9_Software::RageSoundDriver_ALSA9_Software ()
References m_bShutdown, and m_pPCM.
~RageSoundDriver_ALSA9_Software()
RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software ()
References RageThread::IsCreated(), LOG, m_bShutdown, m_MixingThread, m_pPCM, RageLog::Trace(), UnloadALSA(), and RageThread::Wait().
Member Function Documentation
GetData()
bool RageSoundDriver_ALSA9_Software::GetData () private
References Alsa9Buf::GetNumFramesToFill(), Alsa9Buf::GetPlayPos(), Alsa9Buf::GetPosition(), m_pPCM, RageSoundDriver::Mix(), samples_per_frame, and Alsa9Buf::Write().
Referenced by MixerThread().
GetPlayLatency()
float RageSoundDriver_ALSA9_Software::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
References g_iMaxWriteahead, and m_iSampleRate.
GetPosition()
int64_t RageSoundDriver_ALSA9_Software::GetPosition () const virtual
Implements RageSoundDriver.
References Alsa9Buf::GetPosition(), and m_pPCM.
GetSampleRate()
int RageSoundDriver_ALSA9_Software::GetSampleRate () const inline virtual
Reimplemented from RageSoundDriver.
References m_iSampleRate.
Init()
RString RageSoundDriver_ALSA9_Software::Init () virtual
Reimplemented from RageSoundDriver.
References channels, RageThread::Create(), g_iMaxWriteahead, g_iMaxWriteahead_linux_26, Alsa9Buf::GetSampleRate(), Alsa9Buf::Init(), LoadALSA(), LOG, m_iSampleRate, PrefsManager::m_iSoundPreferredSampleRate, PrefsManager::m_iSoundWriteAhead, m_MixingThread, m_pPCM, MixerThread_start(), num_chunks, PREFSMAN, safe_writeahead, RageThread::SetName(), ssprintf(), RageSoundDriver::StartDecodeThread(), and RageLog::Trace().
MixerThread()
void RageSoundDriver_ALSA9_Software::MixerThread () private
References GetData(), m_bShutdown, m_pPCM, and Alsa9Buf::WaitUntilFramesCanBeFilled().
MixerThread_start()
int RageSoundDriver_ALSA9_Software::MixerThread_start (void * p) static private
Referenced by Init().
SetupDecodingThread()
void RageSoundDriver_ALSA9_Software::SetupDecodingThread () virtual
Reimplemented from RageSoundDriver.
Member Data Documentation
m_bShutdown
bool RageSoundDriver_ALSA9_Software::m_bShutdown private
Referenced by MixerThread(), RageSoundDriver_ALSA9_Software(), and ~RageSoundDriver_ALSA9_Software().
m_iSampleRate
int RageSoundDriver_ALSA9_Software::m_iSampleRate private
Referenced by GetPlayLatency(), GetSampleRate(), and Init().
m_MixingThread
RageThread RageSoundDriver_ALSA9_Software::m_MixingThread private
Referenced by Init(), and ~RageSoundDriver_ALSA9_Software().
m_pPCM
Alsa9Buf* RageSoundDriver_ALSA9_Software::m_pPCM private
Referenced by GetData(), GetPosition(), Init(), MixerThread(), RageSoundDriver_ALSA9_Software(), and ~RageSoundDriver_ALSA9_Software().
The documentation for this class was generated from the following files:
RageSoundDriver_ALSA9_Software.h
RageSoundDriver_ALSA9_Software.cpp