Etterna: WinWdmFilter Struct Reference
WinWdmFilter Struct Reference
Public Member Functions
WinWdmFilter ()
~WinWdmFilter ()
WinWdmPin * CreatePin (unsigned long iPinId, RString &sError)
WinWdmPin * InstantiateRenderPin (DeviceSampleFormat &PreferredOutputSampleFormat, int &iPreferredOutputChannels, int &iPreferredSampleRate, RString &sError)
WinWdmPin * InstantiateRenderPin (const WAVEFORMATEX *wfex, RString &sError)
bool Use (RString &sError)
void Release ()
Static Public Member Functions
static WinWdmFilter * Create (const RString &sFilterName, const RString &sFriendlyName, RString &sError)
Public Attributes
HANDLE m_hHandle
vector< WinWdmPin * > m_apPins
RString m_sFilterName
RString m_sFriendlyName
int m_iUsageCount
Constructor & Destructor Documentation
WinWdmFilter()
WinWdmFilter::WinWdmFilter () inline
References m_hHandle, and m_iUsageCount.
Referenced by Create().
~WinWdmFilter()
WinWdmFilter::~WinWdmFilter () inline
References m_apPins, and m_hHandle.
Member Function Documentation
Create()
WinWdmFilter * WinWdmFilter::Create (const RString & sFilterName, const RString & sFriendlyName, RString & sError) static
References CreatePin(), m_apPins, m_hHandle, m_sFilterName, m_sFriendlyName, Release(), Use(), WdmGetPinPropertySimple(), and WinWdmFilter().
Referenced by BuildFilterList().
CreatePin()
WinWdmPin * WinWdmFilter::CreatePin (unsigned long iPinId, RString & sError)
References CHECKPOINT_M, WinWdmPin::m_dataRangesItem, m_hHandle, WdmGetPinPropertyMulti(), and WdmGetPinPropertySimple().
Referenced by Create().
InstantiateRenderPin() [1/2]
WinWdmPin * WinWdmFilter::InstantiateRenderPin (DeviceSampleFormat & PreferredOutputSampleFormat, int & iPreferredOutputChannels, int & iPreferredSampleRate, RString & sError)
References DeviceSampleFormat_Float32, DeviceSampleFormat_Int16, DeviceSampleFormat_Int24, DeviceSampleFormat_Int32, FillWFEXT(), FOREACH, FOREACH_CONST, LOG, m_apPins, WinWdmPin::m_dataRangesItem, MoveToBeginning(), and RageLog::Trace().
Referenced by WinWdmStream::Open().
InstantiateRenderPin() [2/2]
WinWdmPin * WinWdmFilter::InstantiateRenderPin (const WAVEFORMATEX * wfex, RString & sError)
References WinWdmPin::Instantiate(), and m_apPins.
Release()
void WinWdmFilter::Release ()
References ASSERT, m_hHandle, and m_iUsageCount.
Referenced by WinWdmPin::Close(), Create(), and WinWdmPin::Instantiate().
Use()
bool WinWdmFilter::Use (RString & sError)
References m_hHandle, m_iUsageCount, and m_sFilterName.
Referenced by Create(), and WinWdmPin::Instantiate().
Member Data Documentation
m_apPins
vector<WinWdmPin*> WinWdmFilter::m_apPins
Referenced by Create(), RageSoundDriver_WDMKS::Init(), InstantiateRenderPin(), and ~WinWdmFilter().
m_hHandle
HANDLE WinWdmFilter::m_hHandle
Referenced by Create(), CreatePin(), WinWdmPin::Instantiate(), Release(), Use(), WinWdmFilter(), and ~WinWdmFilter().
m_iUsageCount
int WinWdmFilter::m_iUsageCount
Referenced by Release(), Use(), and WinWdmFilter().
m_sFilterName
RString WinWdmFilter::m_sFilterName
Referenced by Create(), and Use().
m_sFriendlyName
RString WinWdmFilter::m_sFriendlyName
Referenced by Create(), and RageSoundDriver_WDMKS::Init().
The documentation for this struct was generated from the following file:
RageSoundDriver_WDMKS.cpp