Etterna: DebugLineReloadTheme Class Reference
DebugLineReloadTheme Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineReloadTheme::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), GAMESTATE, GameState::m_pCurGame, NOTESKIN, CodeDetector::RefreshCacheItems(), NoteSkinManager::RefreshNoteSkinData(), RageTextureManager::ReloadAll(), ThemeManager::ReloadMetrics(), TEXTUREMAN, and THEME.
GetDisplayTitle()
RString DebugLineReloadTheme::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and RELOAD_THEME_AND_TEXTURES.
GetDisplayValue()
RString DebugLineReloadTheme::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPageName()
RString DebugLineReloadTheme::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineReloadTheme::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp