Etterna: RageSoundManager Class Reference
RageSoundManager Class Reference
#include <RageSoundManager.h>
Public Member Functions
RageSoundManager ()
~RageSoundManager ()
void Shutdown ()
void Init ()
float GetMixVolume () const
void SetMixVolume ()
float GetVolumeOfNonCriticalSounds () const
void SetVolumeOfNonCriticalSounds (float fVolumeOfNonCriticalSounds)
void Update ()
void StartMixing (RageSoundBase *snd)
void StopMixing (RageSoundBase *snd)
bool Pause (RageSoundBase *snd, bool bPause)
int64_t GetPosition (RageTimer *pTimer) const
float GetPlayLatency () const
int GetDriverSampleRate () const
RageSoundReader * GetLoadedSound (const RString &sPath)
void AddLoadedSound (const RString &sPath, RageSoundReader_Preload *pSound)
void fix_bogus_sound_driver_pref (RString const &valid_setting)
Private Member Functions
RageSoundManager & operator= (const RageSoundManager &rhs)
RageSoundManager (const RageSoundManager &rhs)
Private Attributes
map< RString, RageSoundReader_Preload * > m_mapPreloadedSounds
RageSoundDriver * m_pDriver
float m_fMixVolume { 1.0f }
float m_fVolumeOfNonCriticalSounds { 1.0f }
Constructor & Destructor Documentation
RageSoundManager() [1/2]
RageSoundManager::RageSoundManager ()
~RageSoundManager()
RageSoundManager::~RageSoundManager ()
References FOREACHM, m_mapPreloadedSounds, and m_pDriver.
RageSoundManager() [2/2]
RageSoundManager::RageSoundManager (const RageSoundManager & rhs) private
Member Function Documentation
AddLoadedSound()
void RageSoundManager::AddLoadedSound (const RString & sPath, RageSoundReader_Preload * pSound)
References ASSERT_M, RageSoundReader_Preload::Copy(), g_SoundManMutex, LockMut, m_mapPreloadedSounds, and StdString::CStdStr< CT >::MakeLower().
Referenced by RageSound::Load().
fix_bogus_sound_driver_pref()
void RageSoundManager::fix_bogus_sound_driver_pref (RString const & valid_setting)
References g_sSoundDrivers.
Referenced by RageSoundDriver::Create().
GetDriverSampleRate()
int RageSoundManager::GetDriverSampleRate () const
References RageSoundDriver::GetSampleRate(), and m_pDriver.
Referenced by AutoKeysounds::FinishLoading(), RageSound::LoadSoundReader(), and AutoKeysounds::LoadTracks().
GetLoadedSound()
RageSoundReader * RageSoundManager::GetLoadedSound (const RString & sPath)
References g_SoundManMutex, LockMut, m_mapPreloadedSounds, and StdString::CStdStr< CT >::MakeLower().
Referenced by RageSound::Load().
GetMixVolume()
float RageSoundManager::GetMixVolume () const inline
References m_fMixVolume.
Referenced by RageSound::ApplyParams().
GetPlayLatency()
float RageSoundManager::GetPlayLatency () const
References RageSoundDriver::GetPlayLatency(), and m_pDriver.
Referenced by AutoKeysounds::LoadAutoplaySoundsInto(), GameplayAssist::PlayTicks(), and StartMusic().
GetPosition()
int64_t RageSoundManager::GetPosition (RageTimer * pTimer) const
References RageSoundDriver::GetHardwareFrame(), and m_pDriver.
Referenced by RageSound::GetPositionSeconds(), and RageSound::SoundIsFinishedPlaying().
GetVolumeOfNonCriticalSounds()
float RageSoundManager::GetVolumeOfNonCriticalSounds () const inline
References m_fVolumeOfNonCriticalSounds.
Referenced by RageSound::StartPlaying().
Init()
void RageSoundManager::Init ()
References COULDNT_FIND_SOUND_DRIVER, RageSoundDriver::Create(), g_sSoundDrivers, LocalizedString::GetValue(), m_pDriver, and RageException::Throw().
Referenced by sm_main().
operator=()
RageSoundManager& RageSoundManager::operator= (const RageSoundManager & rhs) private
Pause()
bool RageSoundManager::Pause (RageSoundBase * snd, bool bPause)
References m_pDriver, and RageSoundDriver::PauseMixing().
Referenced by RageSound::Pause().
SetMixVolume()
void RageSoundManager::SetMixVolume ()
References clamp, g_fSoundVolume, g_SoundManMutex, Preference< T >::Get(), RageMutex::Lock(), m_fMixVolume, and RageMutex::Unlock().
Referenced by ChangeVolume(), ScreenOptionsMaster::HandleScreenMessage(), StepMania::ResetPreferences(), and sm_main().
SetVolumeOfNonCriticalSounds()
void RageSoundManager::SetVolumeOfNonCriticalSounds (float fVolumeOfNonCriticalSounds)
References g_SoundManMutex, RageMutex::Lock(), m_fVolumeOfNonCriticalSounds, and RageMutex::Unlock().
Referenced by ScreenAttract::SetAttractVolume().
Shutdown()
void RageSoundManager::Shutdown ()
References m_pDriver, and SAFE_DELETE.
Referenced by ShutdownGame().
StartMixing()
void RageSoundManager::StartMixing (RageSoundBase * snd)
References m_pDriver, and RageSoundDriver::StartMixing().
Referenced by RageSound::StartPlaying().
StopMixing()
void RageSoundManager::StopMixing (RageSoundBase * snd)
References m_pDriver, and RageSoundDriver::StopMixing().
Referenced by RageSound::StopPlaying().
Update()
void RageSoundManager::Update ()
References g_SoundManMutex, RageMutex::Lock(), LOG, m_mapPreloadedSounds, m_pDriver, RageLog::Trace(), RageMutex::Unlock(), and RageSoundDriver::Update().
Referenced by GameLoop::RunGameLoop().
Member Data Documentation
m_fMixVolume
float RageSoundManager::m_fMixVolume { 1.0f } private
Referenced by GetMixVolume(), and SetMixVolume().
m_fVolumeOfNonCriticalSounds
float RageSoundManager::m_fVolumeOfNonCriticalSounds { 1.0f } private
Referenced by GetVolumeOfNonCriticalSounds(), and SetVolumeOfNonCriticalSounds().
m_mapPreloadedSounds
map<RString, RageSoundReader_Preload*> RageSoundManager::m_mapPreloadedSounds private
Referenced by AddLoadedSound(), GetLoadedSound(), Update(), and ~RageSoundManager().
m_pDriver
RageSoundDriver* RageSoundManager::m_pDriver private
Referenced by GetDriverSampleRate(), GetPlayLatency(), GetPosition(), Init(), Pause(), Shutdown(), StartMixing(), StopMixing(), Update(), and ~RageSoundManager().
The documentation for this class was generated from the following files:
RageSoundManager.h
RageSoundManager.cpp