Etterna: DebugLineVsync Class Reference
DebugLineVsync Class Reference
Private Member Functions
RString GetDisplayTitle () override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual RString GetDisplayValue ()
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineVsync::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References StepMania::ApplyGraphicOptions(), IDebugLine::DoAndLog(), PrefsManager::m_bVsync, PREFSMAN, and Preference< T >::Set().
GetDisplayTitle()
RString DebugLineVsync::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and VSYNC.
IsEnabled()
bool DebugLineVsync::IsEnabled () inline override private virtual
Implements IDebugLine.
References Preference< T >::Get(), PrefsManager::m_bVsync, and PREFSMAN.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp