Etterna: SongManager Class Reference
SongManager Class Reference
The holder for the Songs and its Steps.
#include <SongManager.h>
Classes
struct Comp
struct PreferredSortSection
Public Member Functions
SongManager ()
~SongManager ()
void InitSongsFromDisk (LoadingWindow *ld)
void FreeSongs ()
void UnlistSong (Song *song)
void Cleanup ()
void Invalidate (const Song *pStaleSong)
void SaveEnabledSongsToPref ()
void LoadEnabledSongsFromPref ()
int GetNumStepsLoadedFromProfile ()
void FreeAllLoadedFromProfile (ProfileSlot slot=ProfileSlot_Invalid)
void InitAll (LoadingWindow *ld)
int DifferentialReload ()
int DifferentialReloadDir (string dir)
void PreloadSongImages ()
bool IsGroupNeverCached (const RString &group) const
void SetFavoritedStatus (set< string > &favs)
void SetPermaMirroredStatus (set< string > &pmir)
void SetHasGoal (unordered_map< string, GoalsForChart > &goalmap)
RString GetSongGroupBannerPath (const RString &sSongGroup) const
void GetSongGroupNames (vector< RString > &AddTo) const
const vector< RString > & GetSongGroupNames () const
bool DoesSongGroupExist (const RString &sSongGroup) const
RageColor GetSongGroupColor (const RString &sSongGroupName, map< string, Playlist > &playlists=GetPlaylists()) const
RageColor GetSongColor (const Song *pSong) const
Steps * GetStepsByChartkey (RString ck)
Song * GetSongByChartkey (RString ck)
bool IsChartLoaded (RString ck)
void ResetGroupColors ()
const vector< Song * > & GetSongs (const RString &sGroupName) const
Retrieve all of the songs that belong to a particular group.
const vector< Song * > & GetAllSongs () const
Retrieve all of the songs in the game.
const vector< Song * > & GetPopularSongs () const
Retrieve all of the popular songs.
const vector< Song * > & GetSongsOfCurrentGame (const RString &sGroupName) const
Retrieve all of the songs in a group that have at least one valid step for the current gametype.
const vector< Song * > & GetAllSongsOfCurrentGame () const
Retrieve all of the songs in the game that have at least one valid step for the current gametype.
void GetFavoriteSongs (vector< Song *> &songs) const
void GetPreferredSortSongs (vector< Song *> &AddTo) const
RString SongToPreferredSortSectionName (const Song *pSong) const
Song * FindSong (RString sPath) const
Song * FindSong (RString sGroup, RString sSong) const
int GetNumSongs () const
Retrieve the number of songs in the game.
int GetNumAdditionalSongs () const
int GetNumSongGroups () const
Song * GetRandomSong ()
RString GetSongGroupByIndex (unsigned index)
int GetSongRank (Song *pSong)
void GetStepsLoadedFromProfile (vector< Steps *> &AddTo, ProfileSlot slot) const
void DeleteSteps (Steps *pSteps)
bool WasLoadedFromAdditionalSongs (const Song *pSong) const
void GetExtraStageInfo (bool bExtra2, const Style *s, Song *&pSongOut, Steps *&pStepsOut)
Song * GetSongFromDir (RString sDir) const
void UpdateShuffled ()
void UpdatePreferredSort (const RString &sPreferredSongs="PreferredSongs.txt", const RString &sPreferredCourses="PreferredCourses.txt")
void SortSongs ()
void PushSelf (lua_State *L)
string ReconcileBustedKeys (const string &ck)
void ReconcileChartKeysForReloadedSong (const Song *reloadedSong, vector< string > oldChartkeys)
void MakeSongGroupsFromPlaylists (map< string, Playlist > &playlists=GetPlaylists())
void DeletePlaylist (const string &ck, map< string, Playlist > &playlists=GetPlaylists())
void MakePlaylistFromFavorites (set< string > &favs, map< string, Playlist > &playlists=GetPlaylists())
void FinalizeSong (Song *pNewSong, const RString &dir)
Static Public Member Functions
static map< string, Playlist > & GetPlaylists ()
static RString ShortenGroupName (const RString &sLongGroupName)
Public Attributes
string activeplaylist = ""
string playlistcourse = ""
map< string, string > keyconversionmap
map< string, vector< Song * > > groupderps
vector< string > playlistGroups
Protected Types
typedef vector< Song * > SongPointerVector
Protected Member Functions
void LoadStepManiaSongDir (RString sDir, LoadingWindow *ld)
void LoadDWISongDir (const RString &sDir)
void SanityCheckGroupDir (const RString &sDir) const
bool AddGroup (const RString &sDir, const RString &sGroupDirName)
void AddSongToList (Song *new_song)
void AddKeyedPointers (Song *new_song)
Protected Attributes
vector< Song * > m_pSongs
All of the songs that can be played.
map< RString, Song * > m_SongsByDir
vector< pair< pair< RString, unsigned int >, Song * > * > cache
unordered_map< string, Song * > SongsByKey
unordered_map< string, Steps * > StepsByKey
set< RString > m_GroupsToNeverCache
vector< Song * > m_pDeletedSongs
Hold pointers to all the songs that have been deleted from disk but must at least be kept temporarily alive for smooth audio transitions.
vector< Song * > m_pPopularSongs
The most popular songs ranked by number of plays.
vector< Song * > m_pShuffledSongs
vector< PreferredSortSection > m_vPreferredSongSort
vector< RString > m_sSongGroupNames
vector< RString > m_sSongGroupBannerPaths
map< RString, SongPointerVector, Comp > m_mapSongGroupIndex
RageTexturePreloader m_TexturePreload
ThemeMetric< int > NUM_SONG_GROUP_COLORS
ThemeMetric1D< RageColor > SONG_GROUP_COLOR
Detailed Description
The holder for the Songs and its Steps.
Member Typedef Documentation
SongPointerVector
typedef vector<Song*> SongManager::SongPointerVector protected
Constructor & Destructor Documentation
SongManager()
SongManager::SongManager ()
References LuaManager::Get(), L, ThemeMetric< T >::Load(), ThemeMetric1D< T >::Load(), LUA, NUM_SONG_GROUP_COLORS, PushSelf(), LuaManager::Release(), SONG_GROUP_COLOR, and SONG_GROUP_COLOR_NAME().
~SongManager()
SongManager::~SongManager ()
References FreeSongs(), LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
AddGroup()
bool SongManager::AddGroup (const RString & sDir, const RString & sGroupDirName) protected
References FILEMAN, FT_Bitmap, RageFileManager::GetDirListingWithMultipleExtensions(), ActorUtil::GetTypeExtensionList(), m_sSongGroupBannerPaths, and m_sSongGroupNames.
Referenced by DifferentialReloadDir(), FinalizeSong(), and LoadStepManiaSongDir().
AddKeyedPointers()
void SongManager::AddKeyedPointers (Song * new_song) protected
References Song::GetAllSteps(), groupderps, Song::m_sGroupName, SongsByKey, and StepsByKey.
Referenced by DifferentialReloadDir(), FinalizeSong(), and LoadStepManiaSongDir().
AddSongToList()
void SongManager::AddSongToList (Song * new_song) protected
References Song::GetSongDir(), m_pSongs, m_SongsByDir, StdString::CStdStr< CT >::MakeLower(), and Song::SetEnabled().
Referenced by DifferentialReloadDir(), FinalizeSong(), and LoadStepManiaSongDir().
Cleanup()
void SongManager::Cleanup ()
References Steps::Compress(), Song::GetAllSteps(), and m_pSongs.
Referenced by ScreenManagerUtil::AfterDeleteScreen().
DeletePlaylist()
void SongManager::DeletePlaylist (const string & ck, map< string, Playlist > & playlists = GetPlaylists())
References activeplaylist, and groupderps.
Referenced by LunaSongManager::DeletePlaylist().
DeleteSteps()
void SongManager::DeleteSteps (Steps * pSteps)
References Song::DeleteSteps(), and Steps::m_pSong.
DifferentialReload()
int SongManager::DifferentialReload ()
References MessageManager::Broadcast(), DifferentialReloadDir(), FILEMAN, RageFileManager::FlushDirCache(), LoadEnabledSongsFromPref(), MESSAGEMAN, Message::SetParam(), and SpecialFiles::SONGS_DIR.
Referenced by ScreenNetSelectMusic::DifferentialReload(), ScreenSelectMusic::DifferentialReload(), LunaSongManager::DifferentialReload(), and DownloadManager::UpdatePacks().
DifferentialReloadDir()
int SongManager::DifferentialReloadDir (string dir)
References AddGroup(), AddKeyedPointers(), AddSongToList(), Basename(), MessageManager::Broadcast(), ImageCache::CacheImage(), ScreenManager::Draw(), FOREACH_CONST, GetDirListing(), Song::GetMainTitle(), GetSongGroupBannerPath(), IMAGECACHE, Song::LoadFromSongDir(), LOG, m_mapSongGroupIndex, m_SongsByDir, StdString::CStdStr< CT >::MakeLower(), MESSAGEMAN, SanityCheckGroupDir(), SCREENMAN, Message::SetParam(), SortRStringArray(), StripCvsAndSvn(), StripMacResourceForks(), and RageLog::Trace().
Referenced by DifferentialReload().
DoesSongGroupExist()
bool SongManager::DoesSongGroupExist (const RString & sSongGroup) const
References m_sSongGroupNames.
Referenced by GameCommand::LoadOne(), and UpdatePreferredSort().
FinalizeSong()
void SongManager::FinalizeSong (Song * pNewSong, const RString & dir)
References AddGroup(), AddKeyedPointers(), AddSongToList(), ImageCache::CacheImage(), GetSongGroupBannerPath(), IMAGECACHE, m_mapSongGroupIndex, and Song::m_sGroupName.
Referenced by InitSongsFromDisk().
FindSong() [1/2]
Song * SongManager::FindSong (RString sPath) const
References StdString::CStdStr< CT >::Replace(), and split().
Referenced by LunaSongManager::FindSong(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), GameCommand::LoadOne(), and UpdatePreferredSort().
FindSong() [2/2]
Song * SongManager::FindSong (RString sGroup, RString sSong) const
References FOREACH_CONST, GetSongs(), and GROUP_ALL.
FreeAllLoadedFromProfile()
void SongManager::FreeAllLoadedFromProfile (ProfileSlot slot = ProfileSlot_Invalid)
References FOREACH, StatsManager::GetStepsInUse(), m_pSongs, STATSMAN, and UpdateShuffled().
Referenced by ProfileManager::UnloadProfile().
FreeSongs()
void SongManager::FreeSongs ()
References groupderps, m_mapSongGroupIndex, m_pDeletedSongs, m_pPopularSongs, m_pShuffledSongs, m_pSongs, m_SongsByDir, m_sSongGroupBannerPaths, m_sSongGroupNames, SAFE_DELETE, SongsByKey, and StepsByKey.
Referenced by ~SongManager().
GetAllSongs()
const vector<Song*>& SongManager::GetAllSongs () const inline
Retrieve all of the songs in the game.
Returns
all of the songs.
References GetSongs(), and GROUP_ALL.
Referenced by DoInstalls(), FillProfileStats(), ETTProtocol::FindJsonChart(), SongUtil::GetAllSongGenres(), LunaSongManager::GetAllSongs(), MusicWheel::GetSongList(), Profile::GetSongsPossible(), GetStepsLoadedFromProfile(), Profile::GetTotalStepsWithTopGrade(), ScreenNetSelectMusic::HandleScreenMessage(), Profile::ImportScoresToEtterna(), PreloadSongImages(), SaveEnabledSongsToPref(), and StepsUtil::SortStepsPointerArrayByNumPlays().
GetAllSongsOfCurrentGame()
const vector<Song*>& SongManager::GetAllSongsOfCurrentGame () const
Retrieve all of the songs in the game that have at least one valid step for the current gametype.
Returns
the songs within the game that have at least one valid Step.
GetExtraStageInfo()
void SongManager::GetExtraStageInfo (bool bExtra2, const Style * s, Song *& pSongOut, Steps *& pStepsOut)
References ASSERT, ASSERT_M, CompareNotesPointersForExtra(), EXTRA_STAGE2_DIFFICULTY_MAX, GAMESTATE, BroadcastOnChangePtr< T >::Get(), Steps::GetMeter(), GetRandomSong(), Song::GetSongDir(), GetSongs(), SongUtil::GetSteps(), GROUP_ALL, GameState::m_pCurSong, Song::m_sGroupName, GameState::m_sPreferredSongGroup, Style::m_StepsType, LuaHelpers::ReportScriptErrorFmt(), BroadcastOnChangePtr< T >::Set(), and ssprintf().
Referenced by LunaSongManager::GetExtraStageInfo().
GetFavoriteSongs()
void SongManager::GetFavoriteSongs (vector< Song *> & songs) const
References FOREACH_CONST, and m_pSongs.
Referenced by MusicWheel::GetSongList().
GetNumAdditionalSongs()
int SongManager::GetNumAdditionalSongs () const
References FOREACH_CONST, m_pSongs, and WasLoadedFromAdditionalSongs().
Referenced by LunaSongManager::GetNumAdditionalSongs().
GetNumSongGroups()
int SongManager::GetNumSongGroups () const
References m_sSongGroupNames.
Referenced by LunaSongManager::GetNumSongGroups(), MusicWheel::JumpToNextGroup(), MusicWheel::JumpToPrevGroup(), and MusicWheel::SetOpenSection().
GetNumSongs()
int SongManager::GetNumSongs () const
Retrieve the number of songs in the game.
Returns
the number of songs.
References m_pSongs.
Referenced by LunaSongManager::GetNumSongs(), and GameCommand::IsPlayable().
GetNumStepsLoadedFromProfile()
int SongManager::GetNumStepsLoadedFromProfile ()
References FOREACH, m_pSongs, and ProfileSlot_Invalid.
GetPlaylists()
map< string, Playlist > & SongManager::GetPlaylists () static
References Profile::allplaylists, ProfileManager::GetProfile(), PLAYER_1, and PROFILEMAN.
Referenced by LunaSongManager::GetActivePlaylist(), LunaSongManager::GetPlaylists(), ScreenSelectMusic::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenGameplay::InitSongQueues(), ScreenSelectMusic::Input(), makePlaylist(), MusicWheel::SelectSong(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
GetPopularSongs()
const vector<Song*>& SongManager::GetPopularSongs () const inline
Retrieve all of the popular songs.
Popularity is determined specifically by the number of times a song is chosen.
Returns
all of the popular songs.
References m_pPopularSongs.
Referenced by MusicWheel::GetSongList().
GetPreferredSortSongs()
void SongManager::GetPreferredSortSongs (vector< Song *> & AddTo) const
References FOREACH_CONST, m_pSongs, and m_vPreferredSongSort.
Referenced by LunaSongManager::GetPreferredSortSongs(), and MusicWheel::GetSongList().
GetRandomSong()
Song * SongManager::GetRandomSong ()
References m_pShuffledSongs, and wrap().
Referenced by GetExtraStageInfo(), LunaSongManager::GetRandomSong(), and ScreenEvaluation::Init().
GetSongByChartkey()
Song * SongManager::GetSongByChartkey (RString ck)
References SongsByKey.
Referenced by ETTProtocol::FindJsonChart(), Chart::FromKey(), LunaSongManager::GetSongByChartKey(), MakeSongGroupsFromPlaylists(), and LunaProfile::SortByName().
GetSongColor()
RageColor SongManager::GetSongColor (const Song * pSong) const
References ASSERT, Difficulty_Challenge, Difficulty_Edit, EXTRA_COLOR, EXTRA_COLOR_METER, FOREACH_CONST, Song::GetAllSteps(), Steps::GetDifficulty(), Steps::GetMeter(), GetSongGroupColor(), ThemeMetric1D< T >::GetValue(), Song::m_sGroupName, m_vPreferredSongSort, NUM_SONG_GROUP_COLORS, SONG_GROUP_COLOR, and USE_PREFERRED_SORT_COLOR.
Referenced by MusicWheel::BuildWheelItemDatas().
GetSongFromDir()
Song * SongManager::GetSongFromDir (RString sDir) const
References m_SongsByDir, StdString::CStdStr< CT >::MakeLower(), StdString::CStdStr< CT >::Replace(), and StdString::CStdStr< CT >::Right().
Referenced by SongID::ToSong().
GetSongGroupBannerPath()
RString SongManager::GetSongGroupBannerPath (const RString & sSongGroup) const
References m_sSongGroupBannerPaths, and m_sSongGroupNames.
Referenced by ScreenSelectMusic::AfterMusicChange(), DifferentialReloadDir(), FinalizeSong(), FadingBanner::LoadFromSongGroup(), Banner::LoadFromSongGroup(), and LoadStepManiaSongDir().
GetSongGroupByIndex()
RString SongManager::GetSongGroupByIndex (unsigned index) inline
References m_sSongGroupNames.
Referenced by MusicWheel::BeginScreen(), MusicWheel::ChangeMusic(), MusicWheel::JumpToNextGroup(), MusicWheel::JumpToPrevGroup(), and MusicWheel::SetOpenSection().
GetSongGroupColor()
RageColor SongManager::GetSongGroupColor (const RString & sSongGroupName, map< string, Playlist > & playlists = GetPlaylists()) const
References ASSERT_M, ThemeMetric1D< T >::GetValue(), m_sSongGroupNames, NUM_SONG_GROUP_COLORS, SONG_GROUP_COLOR, and ssprintf().
Referenced by MusicWheel::BuildWheelItemDatas(), and GetSongColor().
GetSongGroupNames() [1/2]
void SongManager::GetSongGroupNames (vector< RString > & AddTo) const
References m_sSongGroupNames.
Referenced by ScreenOptionsToggleSongs::BeginScreen(), ScreenOptionsExportPackageSubPage::BeginScreen(), DownloadManager::DownloadAndInstallPack(), LunaSongManager::GetSongGroupNames(), OptionRowHandlerListGroups::LoadInternal(), and MusicWheel::SearchGroupNames().
GetSongGroupNames() [2/2]
const vector< RString > & SongManager::GetSongGroupNames () const
References m_sSongGroupNames.
GetSongRank()
int SongManager::GetSongRank (Song * pSong)
References FindIndex(), and m_pPopularSongs.
GetSongs()
const vector< Song * > & SongManager::GetSongs (const RString & sGroupName) const
Retrieve all of the songs that belong to a particular group.
Parameters
sGroupName the name of the group.
Returns
the songs that belong in the group.
References GROUP_ALL, m_mapSongGroupIndex, and m_pSongs.
Referenced by ScreenOptionsToggleSongsSubPage::BeginScreen(), FindSong(), StepsUtil::GetAllMatching(), GetAllSongs(), GetExtraStageInfo(), MusicWheel::GetSongList(), LunaSongManager::GetSongsInGroup(), StepsUtil::HasMatching(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), and UpdatePreferredSort().
GetSongsOfCurrentGame()
const vector<Song*>& SongManager::GetSongsOfCurrentGame (const RString & sGroupName) const
Retrieve all of the songs in a group that have at least one valid step for the current gametype.
Parameters
sGroupName the name of the group.
Returns
the songs within the group that have at least one valid Step.
GetStepsByChartkey()
Steps * SongManager::GetStepsByChartkey (RString ck)
References StepsByKey.
Referenced by Profile::FillGoalTable(), StageStats::FinalizeScores(), Chart::FromKey(), LunaSongManager::GetStepsByChartKey(), ScoreManager::RecalculateSSRs(), ETTProtocol::ReportHighScore(), SetCURLPOSTScore(), and LunaProfile::SortByDiff().
GetStepsLoadedFromProfile()
void SongManager::GetStepsLoadedFromProfile (vector< Steps *> & AddTo, ProfileSlot slot) const
References FOREACH_CONST, and GetAllSongs().
InitAll()
void SongManager::InitAll (LoadingWindow * ld)
References InitSongsFromDisk(), m_GroupsToNeverCache, PrefsManager::m_NeverCacheList, PREFSMAN, and split().
Referenced by sm_main().
InitSongsFromDisk()
void SongManager::InitSongsFromDisk (LoadingWindow * ld)
References cache, SongCacheIndex::delay_save_cache, SongCacheIndex::DeleteSongFromDB(), FILEMAN, FinalizeSong(), Preference< T >::Get(), RageTimer::GetDeltaTime(), GetHashForDirectory(), RageFileManager::IsADirectory(), SongCacheIndex::LoadCache(), LoadEnabledSongsFromPref(), LoadStepManiaSongDir(), LOG, PrefsManager::m_bBlindlyTrustCache, PrefsManager::m_bFastLoad, PrefsManager::m_bShrinkSongCache, m_pSongs, max(), PREFSMAN, LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), SONGINDEX, songLoadingSONGMANMutex, SpecialFiles::SONGS_DIR, and RageLog::Trace().
Referenced by InitAll().
Invalidate()
void SongManager::Invalidate (const Song * pStaleSong)
References UpdateShuffled().
IsChartLoaded()
bool SongManager::IsChartLoaded (RString ck) inline
References SongsByKey.
Referenced by ScoreManager::GetAllPBPtrs(), ScoreManager::SetAllTopScores(), and ScoreManager::SortTopSSRPtrs().
IsGroupNeverCached()
bool SongManager::IsGroupNeverCached (const RString & group) const
References m_GroupsToNeverCache.
Referenced by Song::SaveToCacheFile().
LoadDWISongDir()
void SongManager::LoadDWISongDir (const RString & sDir) protected
LoadEnabledSongsFromPref()
void SongManager::LoadEnabledSongsFromPref ()
References FOREACH_CONST, SongID::FromString(), g_sDisabledSongs, Song::SetEnabled(), split(), and SongID::ToSong().
Referenced by DifferentialReload(), and InitSongsFromDisk().
LoadStepManiaSongDir()
void SongManager::LoadStepManiaSongDir (RString sDir, LoadingWindow * ld) protected
References ThreadData::_progress, AddGroup(), AddKeyedPointers(), AddSongToList(), Basename(), ImageCache::CacheImage(), CHECKPOINT_M, ThreadData::data, diskLoadGroupMutex, diskLoadSongMutex, FOREACH_CONST, GetDirListing(), GetSongGroupBannerPath(), IMAGECACHE, Song::LoadFromSongDir(), LOG, m_mapSongGroupIndex, m_SongsByDir, StdString::CStdStr< CT >::MakeLower(), max(), SanityCheckGroupDir(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), ThreadData::setUpdated(), SortRStringArray(), StripCvsAndSvn(), StripMacResourceForks(), and RageLog::Trace().
Referenced by InitSongsFromDisk().
MakePlaylistFromFavorites()
void SongManager::MakePlaylistFromFavorites (set< string > & favs, map< string, Playlist > & playlists = GetPlaylists())
References Playlist::AddChart(), Playlist::chartlist, Playlist::DeleteChart(), and Playlist::name.
Referenced by ScreenSelectMusic::Input(), XMLProfile::LoadFavoritesFromNode(), and DBProfile::LoadFavourites().
MakeSongGroupsFromPlaylists()
void SongManager::MakeSongGroupsFromPlaylists (map< string, Playlist > & playlists = GetPlaylists())
References GetSongByChartkey(), groupderps, playlistGroups, PlaylistsAreSongGroups, and SongUtil::SortSongPointerArrayByTitle().
Referenced by ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenNetSelectMusic::Init(), and ScreenSelectMusic::Init().
PreloadSongImages()
void SongManager::PreloadSongImages ()
References GetAllSongs(), IMGCACHE_FULL, RageTexturePreloader::Load(), PrefsManager::m_ImageCache, m_TexturePreload, PREFSMAN, Sprite::SongBannerTexture(), and RageTexturePreloader::Swap().
Referenced by sm_main().
PushSelf()
void SongManager::PushSelf (lua_State * L)
Referenced by SongManager().
ReconcileBustedKeys()
string SongManager::ReconcileBustedKeys (const string & ck)
References keyconversionmap, and StepsByKey.
Referenced by XMLProfile::LoadFavoritesFromNode(), Chart::LoadFromNode(), ScoreManager::LoadFromNode(), XMLProfile::LoadPermaMirrorFromNode(), and XMLProfile::LoadScoreGoalsFromNode().
ReconcileChartKeysForReloadedSong()
void SongManager::ReconcileChartKeysForReloadedSong (const Song * reloadedSong, vector< string > oldChartkeys)
References Song::GetAllSteps(), and StepsByKey.
Referenced by ScreenSelectMusic::Input().
ResetGroupColors()
void SongManager::ResetGroupColors ()
References ThemeMetric1D< T >::Clear(), ThemeMetric< T >::Load(), ThemeMetric1D< T >::Load(), NUM_SONG_GROUP_COLORS, SONG_GROUP_COLOR, and SONG_GROUP_COLOR_NAME().
Referenced by ScreenManager::ThemeChanged().
SanityCheckGroupDir()
void SongManager::SanityCheckGroupDir (const RString & sDir) const protected
References FOLDER_CONTAINS_MUSIC_FILES, FOREACH, FOREACH_CONST, FT_Sound, GetDirListing(), GetExtension(), ActorUtil::GetTypeExtensionList(), LocalizedString::GetValue(), and RageException::Throw().
Referenced by DifferentialReloadDir(), and LoadStepManiaSongDir().
SaveEnabledSongsToPref()
void SongManager::SaveEnabledSongsToPref ()
References FOREACH_CONST, SongID::FromSong(), g_sDisabledSongs, GetAllSongs(), Song::GetEnabled(), Rage::join(), and SongID::ToString().
Referenced by ScreenOptionsToggleSongsSubPage::ExportOptions().
SetFavoritedStatus()
void SongManager::SetFavoritedStatus (set< string > & favs)
References FOREACH, FOREACH_CONST, and m_pSongs.
Referenced by ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenNetSelectMusic::Init(), XMLProfile::LoadFavoritesFromNode(), DBProfile::LoadFavourites(), and XMLProfile::LoadGeneralDataFromNode().
SetHasGoal()
void SongManager::SetHasGoal (unordered_map< string, GoalsForChart > & goalmap)
References FOREACH, FOREACH_CONST, and m_pSongs.
Referenced by ScreenNetSelectMusic::BeginScreen(), ScreenSelectMusic::BeginScreen(), and ScreenNetSelectMusic::Init().
SetPermaMirroredStatus()
void SongManager::SetPermaMirroredStatus (set< string > & pmir)
References FOREACH, FOREACH_CONST, and m_pSongs.
Referenced by XMLProfile::LoadPermaMirrorFromNode(), and DBProfile::LoadPermaMirrors().
ShortenGroupName()
RString SongManager::ShortenGroupName (const RString & sLongGroupName) static
References TitleSubst::Subst(), and TitleFields::Title.
Referenced by MusicWheelItem::LoadFromWheelItemData().
SongToPreferredSortSectionName()
RString SongManager::SongToPreferredSortSectionName (const Song * pSong) const
References FOREACH_CONST, and m_vPreferredSongSort.
Referenced by SongUtil::GetSectionNameFromSongAndSort(), and LunaSongManager::SongToPreferredSortSectionName().
SortSongs()
void SongManager::SortSongs ()
References m_pSongs, and SongUtil::SortSongPointerArrayByTitle().
Referenced by MusicWheel::Load().
UnlistSong()
void SongManager::UnlistSong (Song * song)
References m_pDeletedSongs, m_pPopularSongs, m_pShuffledSongs, and m_pSongs.
Referenced by ScreenNetSelectMusic::OnConfirmSongDeletion(), and ScreenSelectMusic::OnConfirmSongDeletion().
UpdatePreferredSort()
void SongManager::UpdatePreferredSort (const RString & sPreferredSongs = "PreferredSongs.txt", const RString & sPreferredCourses = "PreferredCourses.txt")
References ASSERT, BeginsWith(), DoesSongGroupExist(), EndsWith(), FindSong(), FOREACH, FOREACH_CONST, GetFileContents(), ThemeManager::GetPathO(), GetSongs(), StdString::CStdStr< CT >::Left(), m_vPreferredSongSort, StdString::CStdStr< CT >::Right(), SongManager::PreferredSortSection::sName, THEME, TrimLeft(), TrimRight(), and SongManager::PreferredSortSection::vpSongs.
Referenced by LunaSongManager::SetPreferredSongs(), and sm_main().
UpdateShuffled()
void SongManager::UpdateShuffled ()
References g_RandomNumberGenerator, m_pShuffledSongs, m_pSongs, and NoteDataUtil::shuffle.
Referenced by FreeAllLoadedFromProfile(), Invalidate(), and GameState::Reset().
WasLoadedFromAdditionalSongs()
bool SongManager::WasLoadedFromAdditionalSongs (const Song * pSong) const
References BeginsWith(), and Song::GetSongDir().
Referenced by GetNumAdditionalSongs(), and LunaSongManager::WasLoadedFromAdditionalSongs().
Member Data Documentation
activeplaylist
string SongManager::activeplaylist = ""
Referenced by DeletePlaylist(), LunaSongManager::GetActivePlaylist(), ScreenSelectMusic::HandleScreenMessage(), ScreenSelectMusic::Input(), DBProfile::LoadPlayLists(), XMLProfile::LoadPlaylistsFromNode(), makePlaylist(), and LunaSongManager::SetActivePlaylist().
cache
vector<pair<pair<RString, unsigned int>, Song*>*> SongManager::cache protected
Referenced by InitSongsFromDisk().
groupderps
map<string, vector<Song*> > SongManager::groupderps
Referenced by AddKeyedPointers(), MusicWheel::BuildWheelItemDatas(), DeletePlaylist(), FreeSongs(), and MakeSongGroupsFromPlaylists().
keyconversionmap
map<string, string> SongManager::keyconversionmap
Referenced by Steps::CalcEtternaMetadata(), and ReconcileBustedKeys().
m_GroupsToNeverCache
set<RString> SongManager::m_GroupsToNeverCache protected
Referenced by InitAll(), and IsGroupNeverCached().
m_mapSongGroupIndex
map<RString, SongPointerVector, Comp> SongManager::m_mapSongGroupIndex protected
Referenced by DifferentialReloadDir(), FinalizeSong(), FreeSongs(), GetSongs(), and LoadStepManiaSongDir().
m_pDeletedSongs
vector<Song*> SongManager::m_pDeletedSongs protected
Hold pointers to all the songs that have been deleted from disk but must at least be kept temporarily alive for smooth audio transitions.
Referenced by FreeSongs(), and UnlistSong().
m_pPopularSongs
vector<Song*> SongManager::m_pPopularSongs protected
The most popular songs ranked by number of plays.
Referenced by FreeSongs(), GetPopularSongs(), GetSongRank(), and UnlistSong().
m_pShuffledSongs
vector<Song*> SongManager::m_pShuffledSongs protected
Referenced by FreeSongs(), GetRandomSong(), UnlistSong(), and UpdateShuffled().
m_pSongs
vector<Song*> SongManager::m_pSongs protected
All of the songs that can be played.
Referenced by AddSongToList(), Cleanup(), FreeAllLoadedFromProfile(), FreeSongs(), GetFavoriteSongs(), GetNumAdditionalSongs(), GetNumSongs(), GetNumStepsLoadedFromProfile(), GetPreferredSortSongs(), GetSongs(), InitSongsFromDisk(), SetFavoritedStatus(), SetHasGoal(), SetPermaMirroredStatus(), SortSongs(), UnlistSong(), and UpdateShuffled().
m_SongsByDir
map<RString, Song*> SongManager::m_SongsByDir protected
Referenced by AddSongToList(), DifferentialReloadDir(), FreeSongs(), GetSongFromDir(), and LoadStepManiaSongDir().
m_sSongGroupBannerPaths
vector<RString> SongManager::m_sSongGroupBannerPaths protected
Referenced by AddGroup(), FreeSongs(), and GetSongGroupBannerPath().
m_sSongGroupNames
vector<RString> SongManager::m_sSongGroupNames protected
Referenced by AddGroup(), DoesSongGroupExist(), FreeSongs(), GetNumSongGroups(), GetSongGroupBannerPath(), GetSongGroupByIndex(), GetSongGroupColor(), and GetSongGroupNames().
m_TexturePreload
RageTexturePreloader SongManager::m_TexturePreload protected
Referenced by PreloadSongImages().
m_vPreferredSongSort
vector<PreferredSortSection> SongManager::m_vPreferredSongSort protected
Referenced by GetPreferredSortSongs(), GetSongColor(), SongToPreferredSortSectionName(), and UpdatePreferredSort().
NUM_SONG_GROUP_COLORS
ThemeMetric<int> SongManager::NUM_SONG_GROUP_COLORS protected
Referenced by GetSongColor(), GetSongGroupColor(), ResetGroupColors(), and SongManager().
playlistcourse
string SongManager::playlistcourse = ""
Referenced by ScreenSelectMusic::BeginScreen(), ScreenGameplay::HandleScreenMessage(), ScreenGameplay::InitSongQueues(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
playlistGroups
vector<string> SongManager::playlistGroups
Referenced by MakeSongGroupsFromPlaylists().
SONG_GROUP_COLOR
ThemeMetric1D<RageColor> SongManager::SONG_GROUP_COLOR protected
Referenced by GetSongColor(), GetSongGroupColor(), ResetGroupColors(), and SongManager().
SongsByKey
unordered_map<string, Song*> SongManager::SongsByKey protected
Referenced by AddKeyedPointers(), FreeSongs(), GetSongByChartkey(), and IsChartLoaded().
StepsByKey
unordered_map<string, Steps*> SongManager::StepsByKey protected
Referenced by AddKeyedPointers(), FreeSongs(), GetStepsByChartkey(), ReconcileBustedKeys(), and ReconcileChartKeysForReloadedSong().
The documentation for this class was generated from the following files:
SongManager.h
SongManager.cpp