Etterna: RageSurfaceUtils_Zoom.cpp File Reference
RageSurfaceUtils_Zoom.cpp File Reference
#include "global.h"
#include "RageSurfaceUtils_Zoom.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageUtil.h"
#include <vector>
Functions
static void InitVectors (vector< int > &s0, vector< int > &s1, vector< uint32_t > &percent, int src, int dst)
static void ZoomSurface (const RageSurface *src, RageSurface *dst)
Function Documentation
InitVectors()
static void InitVectors (vector< int > & s0, vector< int > & s1, vector< uint32_t > & percent, int src, int dst) static
References clamp, and f.
Referenced by ZoomSurface().
ZoomSurface()
static void ZoomSurface (const RageSurface * src, RageSurface * dst) static
References RageSurface::h, InitVectors(), RageSurface::pitch, RageSurface::pixels, and RageSurface::w.
Referenced by RageSurfaceUtils::Zoom().