Etterna: LunaBitmapText Class Reference
LunaBitmapText Class Reference
Allow Lua to have access to the BitmapText.
Public Member Functions
MAX_DIMENSION (maxwidth, SetMaxWidth)
MAX_DIMENSION (maxheight, SetMaxHeight)
GETTER_SETTER_BOOL_METHOD (mult_attrs_with_diffuse)
DEFINE_METHOD (getstrokecolor, GetStrokeColor())
LunaBitmapText ()
Public Member Functions inherited from Luna< BitmapText >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int wrapwidthpixels (T *p, lua_State *L)
static int max_dimension_use_zoom (T *p, lua_State *L)
static int vertspacing (T *p, lua_State *L)
static int settext (T *p, lua_State *L)
static int rainbowscroll (T *p, lua_State *L)
static int jitter (T *p, lua_State *L)
static int distort (T *p, lua_State *L)
static int undistort (T *p, lua_State *L)
static int GetText (T *p, lua_State *L)
static int AddAttribute (T *p, lua_State *L)
static int ClearAttributes (T *p, lua_State *L)
static int strokecolor (T *p, lua_State *L)
static int uppercase (T *p, lua_State *L)
static int textglowmode (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< BitmapText >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< BitmapText >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< BitmapText >
using T = BitmapText
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< BitmapText >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the BitmapText.
Constructor & Destructor Documentation
LunaBitmapText()
LunaBitmapText::LunaBitmapText () inline
References ADD_GET_SET_METHODS, ADD_METHOD, BitmapText::AddAttribute(), BitmapText::ClearAttributes(), and BitmapText::GetText().
Member Function Documentation
AddAttribute()
static int LunaBitmapText::AddAttribute (T * p, lua_State * L) inline static
References BitmapText::AddAttribute(), COMMON_RETURN_SELF, BitmapText::Attribute::FromStack(), BitmapText::GetDefaultAttribute(), and IArg.
ClearAttributes()
static int LunaBitmapText::ClearAttributes (T * p, lua_State * L) inline static
References BitmapText::ClearAttributes(), and COMMON_RETURN_SELF.
DEFINE_METHOD()
LunaBitmapText::DEFINE_METHOD (getstrokecolor , GetStrokeColor())
distort()
static int LunaBitmapText::distort (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and BitmapText::SetDistortion().
GETTER_SETTER_BOOL_METHOD()
LunaBitmapText::GETTER_SETTER_BOOL_METHOD (mult_attrs_with_diffuse)
GetText()
static int LunaBitmapText::GetText (T * p, lua_State * L) inline static
References BitmapText::GetText().
jitter()
static int LunaBitmapText::jitter (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and BitmapText::SetJitter().
MAX_DIMENSION() [1/2]
LunaBitmapText::MAX_DIMENSION (maxwidth , SetMaxWidth)
MAX_DIMENSION() [2/2]
LunaBitmapText::MAX_DIMENSION (maxheight , SetMaxHeight)
max_dimension_use_zoom()
static int LunaBitmapText::max_dimension_use_zoom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and BitmapText::SetMaxDimUseZoom().
rainbowscroll()
static int LunaBitmapText::rainbowscroll (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and BitmapText::SetRainbowScroll().
settext()
static int LunaBitmapText::settext (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, StdString::CStdStr< CT >::Replace(), FontCharAliases::ReplaceMarkers(), SArg, and BitmapText::SetText().
strokecolor()
static int LunaBitmapText::strokecolor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and BitmapText::SetStrokeColor().
textglowmode()
static int LunaBitmapText::textglowmode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and BitmapText::SetTextGlowMode().
undistort()
static int LunaBitmapText::undistort (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and BitmapText::UnSetDistortion().
uppercase()
static int LunaBitmapText::uppercase (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and BitmapText::SetUppercase().
vertspacing()
static int LunaBitmapText::vertspacing (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and BitmapText::SetVertSpacing().
wrapwidthpixels()
static int LunaBitmapText::wrapwidthpixels (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and BitmapText::SetWrapWidthPixels().
The documentation for this class was generated from the following file:
BitmapText.cpp