Etterna: InputHandler_Win32_MIDI Class Reference
InputHandler_Win32_MIDI Class Reference
#include <InputHandler_Win32_MIDI.h>
Public Member Functions
InputHandler_Win32_MIDI ()
~InputHandler_Win32_MIDI ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
void SetDev (DeviceInput key)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual bool DevicesChanged ()
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Attributes
bool m_bFoundDevice
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_Win32_MIDI()
InputHandler_Win32_MIDI::InputHandler_Win32_MIDI ()
References g_device, GetMidiError(), LOG, m_bFoundDevice, midiCallback(), and RageLog::Warn().
~InputHandler_Win32_MIDI()
InputHandler_Win32_MIDI::~InputHandler_Win32_MIDI ()
References g_device, GetMidiError(), LOG, and RageLog::Warn().
Member Function Documentation
GetDevicesAndDescriptions()
void InputHandler_Win32_MIDI::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References DEVICE_MIDI, and m_bFoundDevice.
SetDev()
void InputHandler_Win32_MIDI::SetDev (DeviceInput key) inline
References InputHandler::ButtonPressed().
Member Data Documentation
m_bFoundDevice
bool InputHandler_Win32_MIDI::m_bFoundDevice private
Referenced by GetDevicesAndDescriptions(), and InputHandler_Win32_MIDI().
The documentation for this class was generated from the following files:
InputHandler_Win32_MIDI.h
InputHandler_Win32_MIDI.cpp