Etterna: LunaWheelBase Class Reference
LunaWheelBase Class Reference
Allow Lua to have access to the WheelBase.
Public Member Functions
LunaWheelBase ()
Public Member Functions inherited from Luna< WheelBase >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int Move (T *p, lua_State *L)
static int GetWheelItem (T *p, lua_State *L)
static int IsSettled (T *p, lua_State *L)
static int SetOpenSection (T *p, lua_State *L)
static int GetCurrentIndex (T *p, lua_State *L)
static int GetNumItems (T *p, lua_State *L)
static int IsLocked (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< WheelBase >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< WheelBase >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< WheelBase >
using T = WheelBase
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< WheelBase >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the WheelBase.
Constructor & Destructor Documentation
LunaWheelBase()
LunaWheelBase::LunaWheelBase () inline
References ADD_METHOD, GetCurrentIndex(), GetNumItems(), GetWheelItem(), IsLocked(), IsSettled(), Move(), and SetOpenSection().
Member Function Documentation
GetCurrentIndex()
static int LunaWheelBase::GetCurrentIndex (T * p, lua_State * L) inline static
References WheelBase::GetCurrentIndex().
Referenced by LunaWheelBase().
GetNumItems()
static int LunaWheelBase::GetNumItems (T * p, lua_State * L) inline static
References WheelBase::GetNumItems().
Referenced by LunaWheelBase().
GetWheelItem()
static int LunaWheelBase::GetWheelItem (T * p, lua_State * L) inline static
References WheelBase::GetWheelItem(), IArg, and WheelItemBase::PushSelf().
Referenced by LunaWheelBase().
IsLocked()
static int LunaWheelBase::IsLocked (T * p, lua_State * L) inline static
Referenced by LunaWheelBase().
IsSettled()
static int LunaWheelBase::IsSettled (T * p, lua_State * L) inline static
References WheelBase::IsSettled().
Referenced by LunaWheelBase().
Move()
static int LunaWheelBase::Move (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and WheelBase::Move().
Referenced by LunaWheelBase().
SetOpenSection()
static int LunaWheelBase::SetOpenSection (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and WheelBase::SetOpenSection().
Referenced by LunaWheelBase().
The documentation for this class was generated from the following file:
WheelBase.cpp