Etterna: Player::PlayerNoteFieldPositioner Struct Reference
Player::PlayerNoteFieldPositioner Struct Reference
#include <Player.h>
Public Member Functions
PlayerNoteFieldPositioner (Player *p, float x, float tilt, float skew, float mini, float center_y, bool reverse)
~PlayerNoteFieldPositioner ()
Public Attributes
Player * player
float original_y
float y_offset
Constructor & Destructor Documentation
PlayerNoteFieldPositioner()
Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner (Player * p, float x, float tilt, float skew, float mini, float center_y, bool reverse)
References f, Actor::GetY(), Player::m_pNoteField, original_y, player, Player::PushPlayerMatrix(), SCALE, Actor::SetRotationX(), Actor::SetY(), Actor::SetZoom(), and y_offset.
~PlayerNoteFieldPositioner()
Player::PlayerNoteFieldPositioner::~PlayerNoteFieldPositioner ()
Member Data Documentation
original_y
float Player::PlayerNoteFieldPositioner::original_y
Referenced by PlayerNoteFieldPositioner().
player
Player* Player::PlayerNoteFieldPositioner::player
Referenced by PlayerNoteFieldPositioner().
y_offset
float Player::PlayerNoteFieldPositioner::y_offset
Referenced by PlayerNoteFieldPositioner().
The documentation for this struct was generated from the following files:
Player.h
Player.cpp