Etterna: RageSoundMixBuffer Class Reference
RageSoundMixBuffer Class Reference
#include <RageSoundMixBuffer.h>
Public Member Functions
RageSoundMixBuffer ()
~RageSoundMixBuffer ()
void write (const float *pBuf, unsigned iSize, int iSourceStride=1, int iDestStride=1)
void Extend (unsigned iSamples)
void read (int16_t *pBuf)
void read (float *pBuf)
void read_deinterlace (float **pBufs, int channels)
float * read ()
unsigned size () const
void SetWriteOffset (int iOffset)
Private Attributes
float * m_pMixbuf
unsigned m_iBufSize
unsigned m_iBufUsed
int m_iOffset
Constructor & Destructor Documentation
RageSoundMixBuffer()
RageSoundMixBuffer::RageSoundMixBuffer ()
References m_iBufSize, m_iBufUsed, m_iOffset, and m_pMixbuf.
~RageSoundMixBuffer()
RageSoundMixBuffer::~RageSoundMixBuffer ()
References m_pMixbuf.
Member Function Documentation
Extend()
void RageSoundMixBuffer::Extend (unsigned iSamples)
References m_iBufSize, m_iBufUsed, m_iOffset, and m_pMixbuf.
Referenced by write().
read() [1/3]
void RageSoundMixBuffer::read (int16_t * pBuf)
References clamp, f, m_iBufUsed, and m_pMixbuf.
Referenced by RageSoundDriver::Mix(), RageSoundReader_Merge::Read(), RageSoundReader_Split::Read(), and RageSoundReader_Chain::Read().
read() [2/3]
void RageSoundMixBuffer::read (float * pBuf)
References m_iBufUsed, and m_pMixbuf.
read() [3/3]
float* RageSoundMixBuffer::read () inline
References m_pMixbuf.
read_deinterlace()
void RageSoundMixBuffer::read_deinterlace (float ** pBufs, int channels)
References picosha2::detail::ch(), channels, m_iBufUsed, and m_pMixbuf.
Referenced by RageSoundDriver::MixDeinterlaced().
SetWriteOffset()
void RageSoundMixBuffer::SetWriteOffset (int iOffset)
References m_iOffset.
Referenced by RageSoundDriver::MixIntoBuffer(), RageSoundReader_Merge::Read(), RageSoundReader_Split::Read(), and RageSoundReader_Chain::Read().
size()
unsigned RageSoundMixBuffer::size () const inline
References m_iBufUsed.
Referenced by RageSoundReader_Merge::Read(), and RageSoundReader_Chain::Read().
write()
void RageSoundMixBuffer::write (const float * pBuf, unsigned iSize, int iSourceStride = 1, int iDestStride = 1)
References Extend(), m_iOffset, and m_pMixbuf.
Referenced by RageSoundDriver::MixIntoBuffer(), RageSoundReader_Merge::Read(), RageSoundReader_Split::Read(), and RageSoundReader_Chain::Read().
Member Data Documentation
m_iBufSize
unsigned RageSoundMixBuffer::m_iBufSize private
Referenced by Extend(), and RageSoundMixBuffer().
m_iBufUsed
unsigned RageSoundMixBuffer::m_iBufUsed private
Referenced by Extend(), RageSoundMixBuffer(), read(), read_deinterlace(), and size().
m_iOffset
int RageSoundMixBuffer::m_iOffset private
Referenced by Extend(), RageSoundMixBuffer(), SetWriteOffset(), and write().
m_pMixbuf
float* RageSoundMixBuffer::m_pMixbuf private
Referenced by Extend(), RageSoundMixBuffer(), read(), read_deinterlace(), write(), and ~RageSoundMixBuffer().
The documentation for this class was generated from the following files:
RageSoundMixBuffer.h
RageSoundMixBuffer.cpp