Etterna: DebugLineVisualDelayUp Class Reference
DebugLineVisualDelayUp Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Preference< float > * GetPref ()
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineVisualDelayUp::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References ChangeVisualDelay(), IDebugLine::DoAndLog(), and f.
GetDisplayTitle()
RString DebugLineVisualDelayUp::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and VISUAL_DELAY_UP.
GetDisplayValue()
RString DebugLineVisualDelayUp::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References GetPref(), and ssprintf().
GetPref()
Preference<float>* DebugLineVisualDelayUp::GetPref () inline private
References Preference< T >::GetPreferenceByName().
Referenced by GetDisplayValue().
IsEnabled()
bool DebugLineVisualDelayUp::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp