Etterna: BitmapText Class Reference
BitmapText Class Reference
An actor that holds a Font and draws text to the screen.
#include <BitmapText.h>
Classes
struct Attribute
struct BMT_TweenState
Public Member Functions
BitmapText ()
BitmapText (const BitmapText &cpy)
BitmapText & operator= (const BitmapText &cpy)
~BitmapText () override
void LoadFromNode (const XNode *pNode) override
BitmapText * Copy () const override
BMT_TweenState & BMT_DestTweenState ()
BMT_TweenState const & BMT_DestTweenState () const
void SetCurrentTweenStart () override
void EraseHeadTween () override
void UpdatePercentThroughTween (float between) override
void BeginTweening (float time, ITween *interp) override
virtual void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
void StopTweening () override
void FinishTweening () override
bool LoadFromFont (const RString &sFontName)
bool LoadFromTextureAndChars (const RString &sTexturePath, const RString &sChars)
virtual void SetText (const RString &sText, const RString &sAlternateText="", int iWrapWidthPixels=-1)
void SetVertSpacing (int iSpacing)
void SetMaxWidth (float fMaxWidth)
void SetMaxHeight (float fMaxHeight)
void SetMaxDimUseZoom (bool use)
void SetWrapWidthPixels (int iWrapWidthPixels)
void CropLineToWidth (size_t l, int width)
void CropToWidth (int width)
bool EarlyAbortDraw () const override
Allow the Actor to be aborted early.
void DrawPrimitives () override
Draw the primitives of the Actor.
void SetUppercase (bool b)
void SetRainbowScroll (bool b)
void SetJitter (bool b)
void SetDistortion (float f)
void UnSetDistortion ()
void set_mult_attrs_with_diffuse (bool m)
bool get_mult_attrs_with_diffuse ()
void SetHorizAlign (float f) override
void SetStrokeColor (const RageColor &c)
RageColor const & GetStrokeColor ()
void SetCurrStrokeColor (const RageColor &c)
RageColor const & GetCurrStrokeColor ()
void SetTextGlowMode (TextGlowMode tgm)
void GetLines (vector< wstring > &wTextLines) const
const vector< wstring > & GetLines () const
RString GetText () const
bool StringWillUseAlternate (const RString &sText, const RString &sAlternateText) const
Attribute GetDefaultAttribute () const
void AddAttribute (size_t iPos, const Attribute &attr)
void ClearAttributes ()
void PushSelf (lua_State *L) override
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
virtual void InitState ()
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void BeginDraw ()
Start the drawing and push the transform on the world matrix stack.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
virtual void EndDraw ()
Pop the transform from the world matrix stack.
bool IsFirstUpdate () const
virtual void Update (float fDeltaTime)
virtual void UpdateInternal (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
virtual void HurryTweening (float factor)
virtual float GetTweenTimeLeft () const
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
virtual void SetZTestMode (ZTestMode mode)
virtual void SetZWrite (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
virtual void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void HandleMessage (const Message &msg) override
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
virtual void SetUpdateRate (float)
virtual float GetUpdateRate ()
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Member Functions
void BuildChars ()
void DrawChars (bool bUseStrokeTexture)
void UpdateBaseZoom ()
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
Font * m_pFont
bool m_bUppercase
RString m_sText
vector< wstring > m_wTextLines
vector< int > m_iLineWidths
int m_iWrapWidthPixels
float m_fMaxWidth
float m_fMaxHeight
bool m_MaxDimensionUsesZoom
bool m_bRainbowScroll
bool m_bJitter
bool m_bUsingDistortion
bool m_mult_attrs_with_diffuse
float m_fDistortion
int m_iVertSpacing
vector< RageSpriteVertex > m_aVertices
vector< FontPageTextures * > m_vpFontPageTextures
map< size_t, Attribute > m_mAttributes
bool m_bHasGlowAttribute
TextGlowMode m_TextGlowMode
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Private Member Functions
void SetTextInternal ()
Private Attributes
vector< BMT_TweenState > BMT_Tweens
BMT_TweenState BMT_current
BMT_TweenState BMT_start
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
An actor that holds a Font and draws text to the screen.
Constructor & Destructor Documentation
BitmapText() [1/2]
BitmapText::BitmapText ()
References m_bHasGlowAttribute, m_bJitter, m_bRainbowScroll, m_bUppercase, m_bUsingDistortion, m_fDistortion, m_fMaxHeight, m_fMaxWidth, m_iVertSpacing, m_iWrapWidthPixels, m_MaxDimensionUsesZoom, m_mult_attrs_with_diffuse, m_pFont, m_TextGlowMode, NUM_RAINBOW_COLORS, RAINBOW_COLOR, RAINBOW_COLORS, Actor::SetShadowLength(), and TextGlowMode_Both.
BitmapText() [2/2]
BitmapText::BitmapText (const BitmapText & cpy)
References m_pFont.
~BitmapText()
BitmapText::~BitmapText () override
References FONT, m_pFont, and FontManager::UnloadFont().
Member Function Documentation
AddAttribute()
void BitmapText::AddAttribute (size_t iPos, const Attribute & attr)
References RageColor::a, FOREACH_CONST, BitmapText::Attribute::glow, m_bHasGlowAttribute, m_mAttributes, and m_wTextLines.
Referenced by LunaBitmapText::AddAttribute(), and LunaBitmapText::LunaBitmapText().
BeginTweening() [1/2]
void BitmapText::BeginTweening (float time, ITween * interp) override virtual
Reimplemented from Actor.
References Actor::BeginTweening(), BMT_current, and BMT_Tweens.
Referenced by ScreenGameplay::AbortGiveUpText(), ScreenStatsOverlay::AddTimestampLine(), ScreenSetTime::Init(), and ScreenSetTime::MenuStart().
BeginTweening() [2/2]
virtual void BitmapText::BeginTweening (float time, TweenType tt = TWEEN_LINEAR) inline virtual
References Actor::BeginTweening().
BMT_DestTweenState() [1/2]
BMT_TweenState& BitmapText::BMT_DestTweenState () inline
References BMT_current, and BMT_Tweens.
Referenced by BMT_DestTweenState(), FinishTweening(), GetStrokeColor(), and SetStrokeColor().
BMT_DestTweenState() [2/2]
BMT_TweenState const& BitmapText::BMT_DestTweenState () const inline
References BMT_DestTweenState().
BuildChars()
void BitmapText::BuildChars () protected
References StepMania::Rect< T >::bottom, f, glyph::GetFontPageTextures(), Font::GetGlyph(), Font::GetHeight(), Font::GetLineSpacing(), Font::GetLineWidthInSourcePixels(), RageTimer::GetTimeSinceStartFast(), Font::IsRightToLeft(), StepMania::Rect< T >::left, m_aVertices, m_bUsingDistortion, m_fDistortion, glyph::m_fHeight, Actor::m_fHorizAlign, glyph::m_fHshift, FontPage::m_fVshift, glyph::m_fWidth, glyph::m_iHadvance, m_iLineWidths, m_iVertSpacing, m_pFont, glyph::m_pPage, Actor::m_size, glyph::m_TexRect, m_vpFontPageTextures, m_wTextLines, max(), RageSpriteVertex::p, StepMania::Rect< T >::right, SCALE, RageSpriteVertex::t, StepMania::Rect< T >::top, w, RageVector2::x, and RageVector2::y.
Referenced by CropToWidth(), LoadFromFont(), LoadFromTextureAndChars(), ColorBitmapText::ResetText(), set_mult_attrs_with_diffuse(), SetDistortion(), SetHorizAlign(), ColorBitmapText::SetMaxLines(), ColorBitmapText::SetText(), SetTextInternal(), SetUppercase(), SetVertSpacing(), and UnSetDistortion().
ClearAttributes()
void BitmapText::ClearAttributes ()
References m_bHasGlowAttribute, and m_mAttributes.
Referenced by LunaBitmapText::ClearAttributes(), LunaBitmapText::LunaBitmapText(), and SetText().
Copy()
BitmapText* BitmapText::Copy () const override virtual
Reimplemented from Actor.
Reimplemented in SongBPMDisplay, ColorBitmapText, InputList, DeviceList, ScoreDisplayAliveTime, BPMDisplay, HelpDisplay, and RollingNumbers.
Referenced by ScreenTextEntryVisual::Init(), and ComboGraph::Set().
CropLineToWidth()
void BitmapText::CropLineToWidth (size_t l, int width)
References Font::GetGlyphsThatFit(), m_iLineWidths, m_pFont, and m_wTextLines.
Referenced by CropToWidth().
CropToWidth()
void BitmapText::CropToWidth (int width)
References BuildChars(), CropLineToWidth(), and m_wTextLines.
Referenced by ModIcon::Set().
DrawChars()
void BitmapText::DrawChars (bool bUseStrokeTexture) protected
References StepMania::Rect< T >::bottom, clamp, Actor::TweenState::crop, DISPLAY, RageDisplay::DrawQuads(), f, Actor::TweenState::fade, StepMania::Rect< T >::left, m_aVertices, Actor::m_pTempState, m_vpFontPageTextures, StepMania::Rect< T >::right, SCALE, RageDisplay::SetTexture(), TextureUnit_1, and StepMania::Rect< T >::top.
Referenced by DrawPrimitives(), and ColorBitmapText::DrawPrimitives().
DrawPrimitives()
void BitmapText::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from Actor.
Reimplemented in ColorBitmapText, and RollingNumbers.
References RageColor::a, ASSERT, BitmapText::Attribute::diffuse, Actor::TweenState::diffuse, DISPLAY, DrawChars(), f, GetCurrStrokeColor(), RageTimer::GetTimeSinceStartFast(), BitmapText::Attribute::glow, Actor::TweenState::glow, BitmapText::Attribute::length, m_aVertices, m_bHasGlowAttribute, m_bJitter, m_bRainbowScroll, Actor::m_fShadowLengthX, Actor::m_fShadowLengthY, Actor::m_internalDiffuse, Actor::m_internalGlow, m_mAttributes, m_mult_attrs_with_diffuse, Actor::m_pTempState, Actor::m_ShadowColor, m_TextGlowMode, min(), NUM_DIFFUSE_COLORS, RageDisplay::PopMatrix(), RageDisplay::PushMatrix(), RAINBOW_COLORS, Actor::SetGlobalRenderStates(), RageDisplay::SetTextureMode(), TextGlowMode_Inner, TextureMode_Glow, TextureMode_Modulate, TextureUnit_1, and RageDisplay::TranslateWorld().
Referenced by RollingNumbers::DrawPart().
EarlyAbortDraw()
bool BitmapText::EarlyAbortDraw () const override virtual
Allow the Actor to be aborted early.
Subclasses may wish to overwrite this to allow for aborted actors.
Returns
false, as by default Actors shouldn't be aborted on drawing.
Reimplemented from Actor.
References m_wTextLines.
EraseHeadTween()
void BitmapText::EraseHeadTween () override virtual
Reimplemented from Actor.
References BMT_current, and BMT_Tweens.
FinishTweening()
void BitmapText::FinishTweening () override virtual
Reimplemented from Actor.
References BMT_current, BMT_DestTweenState(), BMT_Tweens, and Actor::FinishTweening().
Referenced by ScreenOptions::AfterChangeValueOrRow(), and ScreenDebugOverlay::Input().
get_mult_attrs_with_diffuse()
bool BitmapText::get_mult_attrs_with_diffuse ()
References m_mult_attrs_with_diffuse.
GetCurrStrokeColor()
RageColor const& BitmapText::GetCurrStrokeColor () inline
References BMT_current, and BitmapText::BMT_TweenState::GetStrokeColor().
Referenced by RollingNumbers::DrawPrimitives(), and DrawPrimitives().
GetDefaultAttribute()
BitmapText::Attribute BitmapText::GetDefaultAttribute () const
References BitmapText::Attribute::diffuse, Actor::GetDiffuses(), Actor::GetGlow(), and BitmapText::Attribute::glow.
Referenced by LunaBitmapText::AddAttribute().
GetLines() [1/2]
void BitmapText::GetLines (vector< wstring > & wTextLines) const inline
References m_wTextLines.
GetLines() [2/2]
const vector<wstring>& BitmapText::GetLines () const inline
References m_wTextLines.
GetStrokeColor()
RageColor const& BitmapText::GetStrokeColor () inline
References BMT_DestTweenState(), and BitmapText::BMT_TweenState::GetStrokeColor().
GetText()
RString BitmapText::GetText () const inline
References m_sText.
Referenced by ScreenOptions::AfterChangeValueOrRow(), RollingNumbers::DrawPrimitives(), LunaBPMDisplay::GetText(), LunaBitmapText::GetText(), and LunaBitmapText::LunaBitmapText().
LoadFromFont()
bool BitmapText::LoadFromFont (const RString & sFontName)
References BuildChars(), CHECKPOINT_M, FONT, Font::GetDefaultStrokeColor(), FontManager::LoadFont(), m_pFont, SetStrokeColor(), ssprintf(), and FontManager::UnloadFont().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenInstallOverlay::Init(), ScreenTestSound::Init(), ScreenNetSelectBase::Init(), ScreenReloadSongs::Init(), ScoreDisplayLifeTime::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScreenStatsOverlay::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), ScreenRanking::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), ModIcon::Load(), RoomInfoDisplay::Load(), LifeMeterBattery::Load(), PercentageDisplay::Load(), TextBanner::Load(), MenuTimer::Load(), OptionRowType::Load(), StepsDisplay::Load(), PaneDisplay::Load(), RoomWheelItem::Load(), LoadFromNode(), PercentageDisplay::LoadFromNode(), LyricDisplay::LyricDisplay(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), ScoreDisplayNormal::ScoreDisplayNormal(), and ScoreDisplayOni::ScoreDisplayOni().
LoadFromNode()
void BitmapText::LoadFromNode (const XNode * pNode) override virtual
Reimplemented from Actor.
Reimplemented in BPMDisplay, and ScoreDisplayAliveTime.
References ThemeManager::EvaluateString(), ActorUtil::GetAttrPath(), XNode::GetAttrValue(), ThemeManager::GetPathF(), ActorUtil::GetWhere(), LoadFromFont(), Actor::LoadFromNode(), LuaHelpers::ReportScriptErrorFmt(), SetText(), text, and THEME.
Referenced by ScoreDisplayAliveTime::LoadFromNode(), PercentageDisplay::LoadFromNode(), and BPMDisplay::LoadFromNode().
LoadFromTextureAndChars()
bool BitmapText::LoadFromTextureAndChars (const RString & sTexturePath, const RString & sChars)
References BuildChars(), CHECKPOINT_M, FONT, FontManager::LoadFont(), m_pFont, ssprintf(), and FontManager::UnloadFont().
Referenced by StepsDisplay::Load().
operator=()
BitmapText & BitmapText::operator= (const BitmapText & cpy)
References BMT_current, BMT_start, BMT_Tweens, FontManager::CopyFont(), CPY, FONT, m_aVertices, m_bHasGlowAttribute, m_bJitter, m_bRainbowScroll, m_bUppercase, m_bUsingDistortion, m_fDistortion, m_fMaxHeight, m_fMaxWidth, m_iLineWidths, m_iVertSpacing, m_iWrapWidthPixels, m_mAttributes, m_MaxDimensionUsesZoom, m_mult_attrs_with_diffuse, m_pFont, m_sText, m_vpFontPageTextures, m_wTextLines, MessageSubscriber::operator=(), and FontManager::UnloadFont().
PushSelf()
void BitmapText::PushSelf (lua_State * L) override virtual
Reimplemented from Actor.
Reimplemented in ColorBitmapText, BPMDisplay, HelpDisplay, RollingNumbers, and ScoreDisplayAliveTime.
Referenced by PaneDisplay::SetContent().
set_mult_attrs_with_diffuse()
void BitmapText::set_mult_attrs_with_diffuse (bool m)
References BuildChars(), and m_mult_attrs_with_diffuse.
SetCurrentTweenStart()
void BitmapText::SetCurrentTweenStart () override virtual
Reimplemented from Actor.
References BMT_current, and BMT_start.
SetCurrStrokeColor()
void BitmapText::SetCurrStrokeColor (const RageColor & c) inline
References BMT_current, and BitmapText::BMT_TweenState::SetStrokeColor().
Referenced by RollingNumbers::DrawPart().
SetDistortion()
void BitmapText::SetDistortion (float f)
References BuildChars(), f, m_bUsingDistortion, and m_fDistortion.
Referenced by LunaBitmapText::distort().
SetHorizAlign()
void BitmapText::SetHorizAlign (float f) override virtual
Reimplemented from Actor.
References BuildChars(), Actor::m_fHorizAlign, and Actor::SetHorizAlign().
Referenced by NoteField::DrawBeatBar(), ScreenDebugOverlay::Init(), RoomInfoDisplay::Load(), and NoteField::set_text_measure_number_for_draw().
SetJitter()
void BitmapText::SetJitter (bool b) inline
References m_bJitter.
Referenced by LunaBitmapText::jitter().
SetMaxDimUseZoom()
void BitmapText::SetMaxDimUseZoom (bool use)
References m_MaxDimensionUsesZoom.
Referenced by LunaBitmapText::max_dimension_use_zoom().
SetMaxHeight()
void BitmapText::SetMaxHeight (float fMaxHeight)
References m_fMaxHeight, and UpdateBaseZoom().
SetMaxWidth()
void BitmapText::SetMaxWidth (float fMaxWidth)
References m_fMaxWidth, and UpdateBaseZoom().
Referenced by ScreenReloadSongs::Init(), and ScreenPackages::Init().
SetRainbowScroll()
void BitmapText::SetRainbowScroll (bool b) inline
References m_bRainbowScroll.
Referenced by LunaBitmapText::rainbowscroll().
SetStrokeColor()
void BitmapText::SetStrokeColor (const RageColor & c) inline
References BMT_DestTweenState(), and BitmapText::BMT_TweenState::SetStrokeColor().
Referenced by LoadFromFont(), and LunaBitmapText::strokecolor().
SetText()
void BitmapText::SetText (const RString & sText, const RString & sAlternateText = "", int iWrapWidthPixels = -1) virtual
Reimplemented in ColorBitmapText.
References ASSERT, ClearAttributes(), m_bUppercase, m_iWrapWidthPixels, m_pFont, m_sText, StdString::CStdStr< CT >::MakeUpper(), SetTextInternal(), and StringWillUseAlternate().
Referenced by ScreenGameplay::AbortGiveUpText(), ScreenStatsOverlay::AddTimestampLine(), ScreenOptions::AfterChangeValueOrRow(), ScreenSelectMusic::AfterStepsOrTrailChange(), ScreenPrompt::BeginScreen(), ScreenTextEntry::BeginScreen(), OptionRow::ChoicesChanged(), NoteField::draw_timing_segment_text(), NoteField::DrawBeatBar(), NoteField::DrawBGChangeText(), ScreenTestSound::Init(), ScreenMapControllers::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), ScreenTextEntryVisual::Init(), OptionRow::InitText(), ScreenGameplay::Input(), RoomInfoDisplay::Load(), PercentageDisplay::Load(), LoadFromNode(), MusicWheelItem::LoadFromWheelItemData(), RoomWheelItem::LoadFromWheelItemData(), ScreenGameplay::LoadNextSong(), BPMDisplay::NoBPM(), ScreenMapControllers::Refresh(), PercentageDisplay::Refresh(), LifeMeterBattery::Refresh(), ScreenGameplaySyncMachine::RefreshText(), ModIcon::Set(), ComboGraph::Set(), BPMDisplay::SetBPMRange(), PaneDisplay::SetContent(), OptionRow::SetExitText(), TextBanner::SetFromString(), StepsDisplay::SetInternal(), ScreenRanking::SetPage(), RoomInfoDisplay::SetRoom(), RoomInfoDisplay::SetRoomInfo(), ScoreDisplayNormal::SetText(), ScreenReloadSongsLoadingWindow::SetText(), MenuTimer::SetText(), LunaBitmapText::settext(), HelpDisplay::SetTips(), BPMDisplay::SetVarious(), DeviceList::Update(), ScoreDisplayOni::Update(), ScreenStatsOverlay::Update(), ScreenMapControllers::Update(), ScoreDisplayLifeTime::Update(), BPMDisplay::Update(), ScreenSetTime::Update(), HelpDisplay::Update(), InputList::Update(), ScreenTextEntry::UpdateAnswerText(), ScreenPackages::UpdateLinksList(), ScoreDisplayAliveTime::UpdateNumber(), ScreenPackages::UpdatePackagesList(), ScreenPackages::UpdateProgress(), ScreenNetEvaluation::UpdateStats(), ScreenTestSound::UpdateText(), ScreenDebugOverlay::UpdateText(), and RollingNumbers::UpdateText().
SetTextGlowMode()
void BitmapText::SetTextGlowMode (TextGlowMode tgm) inline
References m_TextGlowMode.
Referenced by LunaBitmapText::textglowmode().
SetTextInternal()
void BitmapText::SetTextInternal () private
References BuildChars(), Font::GetLineWidthInSourcePixels(), L, m_iWrapWidthPixels, m_pFont, m_sText, m_wTextLines, RStringToWstring(), split(), and UpdateBaseZoom().
Referenced by SetText(), and SetWrapWidthPixels().
SetUppercase()
void BitmapText::SetUppercase (bool b)
References BuildChars(), and m_bUppercase.
Referenced by LunaBitmapText::uppercase().
SetVertSpacing()
void BitmapText::SetVertSpacing (int iSpacing)
References BuildChars(), and m_iVertSpacing.
Referenced by LunaBitmapText::vertspacing().
SetWrapWidthPixels()
void BitmapText::SetWrapWidthPixels (int iWrapWidthPixels)
References ASSERT, m_iWrapWidthPixels, m_pFont, and SetTextInternal().
Referenced by ScreenNetSelectBase::Init(), NoteField::NoteField(), and LunaBitmapText::wrapwidthpixels().
StopTweening()
void BitmapText::StopTweening () override virtual
Reimplemented from Actor.
References BMT_Tweens, and Actor::StopTweening().
Referenced by ScreenGameplay::AbortGiveUpText(), and ScreenStatsOverlay::AddTimestampLine().
StringWillUseAlternate()
bool BitmapText::StringWillUseAlternate (const RString & sText, const RString & sAlternateText) const
References ASSERT, Font::FontCompleteForString(), m_pFont, and RStringToWstring().
Referenced by SetText(), and ColorBitmapText::SetText().
UnSetDistortion()
void BitmapText::UnSetDistortion ()
References BuildChars(), and m_bUsingDistortion.
Referenced by LunaBitmapText::undistort().
UpdateBaseZoom()
void BitmapText::UpdateBaseZoom () protected
References APPLY_DIMENSION_ZOOM, Actor::GetUnzoomedHeight(), Actor::GetUnzoomedWidth(), Actor::GetZoomX(), Actor::GetZoomY(), m_fMaxHeight, m_fMaxWidth, Actor::SetBaseZoomX(), and Actor::SetBaseZoomY().
Referenced by ColorBitmapText::ResetText(), SetMaxHeight(), SetMaxWidth(), ColorBitmapText::SetText(), and SetTextInternal().
UpdatePercentThroughTween()
void BitmapText::UpdatePercentThroughTween (float between) override virtual
Reimplemented from Actor.
References BMT_current, BMT_start, BMT_Tweens, and BitmapText::BMT_TweenState::MakeWeightedAverage().
Member Data Documentation
BMT_current
BMT_TweenState BitmapText::BMT_current private
Referenced by BeginTweening(), BMT_DestTweenState(), EraseHeadTween(), FinishTweening(), GetCurrStrokeColor(), operator=(), SetCurrentTweenStart(), SetCurrStrokeColor(), and UpdatePercentThroughTween().
BMT_start
BMT_TweenState BitmapText::BMT_start private
Referenced by operator=(), SetCurrentTweenStart(), and UpdatePercentThroughTween().
BMT_Tweens
vector<BMT_TweenState> BitmapText::BMT_Tweens private
Referenced by BeginTweening(), BMT_DestTweenState(), EraseHeadTween(), FinishTweening(), operator=(), StopTweening(), and UpdatePercentThroughTween().
m_aVertices
vector<RageSpriteVertex> BitmapText::m_aVertices protected
Referenced by BuildChars(), DrawChars(), DrawPrimitives(), ColorBitmapText::DrawPrimitives(), and operator=().
m_bHasGlowAttribute
bool BitmapText::m_bHasGlowAttribute protected
Referenced by AddAttribute(), BitmapText(), ClearAttributes(), DrawPrimitives(), and operator=().
m_bJitter
bool BitmapText::m_bJitter protected
Referenced by BitmapText(), DrawPrimitives(), operator=(), and SetJitter().
m_bRainbowScroll
bool BitmapText::m_bRainbowScroll protected
Referenced by BitmapText(), DrawPrimitives(), operator=(), and SetRainbowScroll().
m_bUppercase
bool BitmapText::m_bUppercase protected
Referenced by BitmapText(), operator=(), SetText(), and SetUppercase().
m_bUsingDistortion
bool BitmapText::m_bUsingDistortion protected
Referenced by BitmapText(), BuildChars(), operator=(), SetDistortion(), and UnSetDistortion().
m_fDistortion
float BitmapText::m_fDistortion protected
Referenced by BitmapText(), BuildChars(), operator=(), and SetDistortion().
m_fMaxHeight
float BitmapText::m_fMaxHeight protected
Referenced by BitmapText(), operator=(), SetMaxHeight(), and UpdateBaseZoom().
m_fMaxWidth
float BitmapText::m_fMaxWidth protected
Referenced by BitmapText(), operator=(), SetMaxWidth(), and UpdateBaseZoom().
m_iLineWidths
vector<int> BitmapText::m_iLineWidths protected
Referenced by BuildChars(), CropLineToWidth(), operator=(), ColorBitmapText::SetMaxLines(), and ColorBitmapText::SimpleAddLine().
m_iVertSpacing
int BitmapText::m_iVertSpacing protected
Referenced by BitmapText(), BuildChars(), operator=(), and SetVertSpacing().
m_iWrapWidthPixels
int BitmapText::m_iWrapWidthPixels protected
Referenced by BitmapText(), operator=(), ColorBitmapText::ResetText(), SetText(), ColorBitmapText::SetText(), SetTextInternal(), and SetWrapWidthPixels().
m_mAttributes
map<size_t, Attribute> BitmapText::m_mAttributes protected
Referenced by AddAttribute(), ClearAttributes(), DrawPrimitives(), and operator=().
m_MaxDimensionUsesZoom
bool BitmapText::m_MaxDimensionUsesZoom protected
Referenced by BitmapText(), operator=(), and SetMaxDimUseZoom().
m_mult_attrs_with_diffuse
bool BitmapText::m_mult_attrs_with_diffuse protected
Referenced by BitmapText(), DrawPrimitives(), get_mult_attrs_with_diffuse(), operator=(), and set_mult_attrs_with_diffuse().
m_pFont
Font* BitmapText::m_pFont protected
Referenced by BitmapText(), BuildChars(), CropLineToWidth(), LoadFromFont(), LoadFromTextureAndChars(), operator=(), ColorBitmapText::ResetText(), SetText(), ColorBitmapText::SetText(), SetTextInternal(), SetWrapWidthPixels(), StringWillUseAlternate(), and ~BitmapText().
m_sText
RString BitmapText::m_sText protected
Referenced by GetText(), operator=(), ColorBitmapText::ResetText(), SetText(), ColorBitmapText::SetText(), and SetTextInternal().
m_TextGlowMode
TextGlowMode BitmapText::m_TextGlowMode protected
Referenced by BitmapText(), DrawPrimitives(), and SetTextGlowMode().
m_vpFontPageTextures
vector<FontPageTextures*> BitmapText::m_vpFontPageTextures protected
Referenced by BuildChars(), DrawChars(), and operator=().
m_wTextLines
vector<wstring> BitmapText::m_wTextLines protected
Referenced by AddAttribute(), BuildChars(), CropLineToWidth(), CropToWidth(), EarlyAbortDraw(), GetLines(), operator=(), ColorBitmapText::ResetText(), ColorBitmapText::SetMaxLines(), ColorBitmapText::SetText(), SetTextInternal(), and ColorBitmapText::SimpleAddLine().
The documentation for this class was generated from the following files:
BitmapText.h
BitmapText.cpp