Etterna: NoteDataUtil.h File Reference
NoteDataUtil.h File Reference
#include "GameConstantsAndTypes.h"
#include "NoteTypes.h"
Namespaces
NoteDataUtil
Utility functions that deal with NoteData.
Enumerations
enum NoteDataUtil::TrackMapping {
NoteDataUtil::left, NoteDataUtil::right, NoteDataUtil::mirror, NoteDataUtil::backwards,
NoteDataUtil::shuffle, NoteDataUtil::soft_shuffle, NoteDataUtil::super_shuffle, NoteDataUtil::stomp,
NoteDataUtil::swap_up_down, NoteDataUtil::NUM_TRACK_MAPPINGS
}
The types of transformations available for the NoteData.
Functions
void PlaceAutoKeysound (NoteData &out, int row, TapNote akTap)
int FindLongestOverlappingHoldNoteForAnyTrack (const NoteData &in, int iRow)
void LightTransformHelper (const NoteData &in, NoteData &out, const vector< int > &aiTracks)
NoteType NoteDataUtil::GetSmallestNoteTypeForMeasure (const NoteData &nd, int iMeasureIndex)
NoteType NoteDataUtil::GetSmallestNoteTypeInRange (const NoteData &nd, int iStartIndex, int iEndIndex)
void NoteDataUtil::LoadFromSMNoteDataString (NoteData &out, const RString &sSMNoteData)
void NoteDataUtil::LoadFromETTNoteDataString (NoteData &out, const RString &sSMNoteData)
void NoteDataUtil::GetSMNoteDataString (const NoteData &in, RString &notes_out)
void NoteDataUtil::GetETTNoteDataString (const NoteData &in, RString &notes_out)
void NoteDataUtil::LoadTransformedSlidingWindow (const NoteData &in, NoteData &out, int iNewNumTracks)
Autogenerate notes from one type to another.
void NoteDataUtil::LoadOverlapped (const NoteData &in, NoteData &out, int iNewNumTracks)
Autogenerate notes from one type to another.
void NoteDataUtil::LoadTransformedLights (const NoteData &in, NoteData &out, int iNewNumTracks)
void NoteDataUtil::LoadTransformedLightsFromTwo (const NoteData &marquee, const NoteData &bass, NoteData &out)
void NoteDataUtil::InsertHoldTails (NoteData &inout)
void NoteDataUtil::CalculateRadarValues (const NoteData &in, float fSongSeconds, RadarValues &out, TimingData *td=nullptr)
void NoteDataUtil::RemoveHoldNotes (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the Hold notes.
void NoteDataUtil::ChangeRollsToHolds (NoteData &in, int iStartIndex, int iEndIndex)
void NoteDataUtil::ChangeHoldsToRolls (NoteData &in, int iStartIndex, int iEndIndex)
void NoteDataUtil::RemoveSimultaneousNotes (NoteData &inout, int iMaxSimultaneous, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::RemoveJumps (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::RemoveHands (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::RemoveQuads (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::RemoveSpecificTapNotes (NoteData &inout, TapNoteType tn, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of a specific TapNote Type.
void NoteDataUtil::RemoveMines (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the mines from the chart.
void NoteDataUtil::RemoveLifts (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the lifts from the chart.
void NoteDataUtil::RemoveFakes (NoteData &inout, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the fakes from the chart.
void NoteDataUtil::RemoveStretch (NoteData &inout, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::RemoveAllButOneTap (NoteData &inout, int row)
void NoteDataUtil::RemoveAllButPlayer (NoteData &inout, PlayerNumber pn)
void NoteDataUtil::Turn (NoteData &inout, StepsType st, TrackMapping tt, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Little (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Wide (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Big (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Quick (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::BMRize (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Skippy (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::InsertIntelligentTaps (NoteData &in, int iWindowSizeRows, int iInsertOffsetRows, int iWindowStrideRows, bool bSkippy, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::AddMines (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Echo (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Stomp (NoteData &inout, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::JackJS (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::AnchorJS (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::IcyWorld (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Planted (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Floored (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Twister (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::ConvertTapsToHolds (NoteData &inout, int iSimultaneousHolds, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::ConvertAdditionsToRegular (NoteData &inout)
Convert all taps added via transforms into original style tap notes.
void NoteDataUtil::Backwards (NoteData &inout)
void NoteDataUtil::SwapSides (NoteData &inout)
void NoteDataUtil::CopyLeftToRight (NoteData &inout)
void NoteDataUtil::CopyRightToLeft (NoteData &inout)
void NoteDataUtil::ClearLeft (NoteData &inout)
void NoteDataUtil::ClearRight (NoteData &inout)
void NoteDataUtil::CollapseToOne (NoteData &inout)
void NoteDataUtil::CollapseLeft (NoteData &inout)
void NoteDataUtil::ShiftTracks (NoteData &inout, int iShiftBy)
void NoteDataUtil::ShiftLeft (NoteData &inout)
void NoteDataUtil::ShiftRight (NoteData &inout)
void NoteDataUtil::SwapUpDown (NoteData &inout, StepsType st)
void NoteDataUtil::ArbitraryRemap (NoteData &inout, int *mapping)
void NoteDataUtil::SnapToNearestNoteType (NoteData &inout, NoteType nt1, NoteType nt2, int iStartIndex, int iEndIndex)
void NoteDataUtil::SnapToNearestNoteType (NoteData &inout, NoteType nt, int iStartIndex, int iEndIndex)
bool NoteDataUtil::RowPassesValidMask (NoteData &inout, int row, const bool bValidMask[])
void NoteDataUtil::TransformNoteData (NoteData &nd, TimingData const &timing_data, const PlayerOptions &po, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::Scale (NoteData &nd, float fScale)
void NoteDataUtil::ScaleRegion (NoteData &nd, float fScale, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void NoteDataUtil::InsertRows (NoteData &nd, int iStartIndex, int iRowsToShift)
void NoteDataUtil::DeleteRows (NoteData &nd, int iStartIndex, int iRowsToShift)
void NoteDataUtil::RemoveAllTapsOfType (NoteData &ndInOut, TapNoteType typeToRemove)
void NoteDataUtil::RemoveAllTapsExceptForType (NoteData &ndInOut, TapNoteType typeToKeep)
int NoteDataUtil::GetMaxNonEmptyTrack (const NoteData &in)
bool NoteDataUtil::AnyTapsAndHoldsInTrackRange (const NoteData &in, int iTrack, int iStart, int iEnd)
bool NoteDataUtil::GetNextEditorPosition (const NoteData &in, int &rowInOut)
bool NoteDataUtil::GetPrevEditorPosition (const NoteData &in, int &rowInOut)
unsigned int NoteDataUtil::GetTotalHoldTicks (NoteData *nd, const TimingData *td)
Count the number of hold ticks that will fire, assuming that tickholds are on.
Detailed Description
Author
Chris Danford, Glenn Maynard (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Function Documentation
FindLongestOverlappingHoldNoteForAnyTrack()
int FindLongestOverlappingHoldNoteForAnyTrack (const NoteData & in, int iRow)
References NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, max(), TapNoteType_HoldHead, and TapNote::type.
LightTransformHelper()
void LightTransformHelper (const NoteData & in, NoteData & out, const vector< int > & aiTracks)
PlaceAutoKeysound()
void PlaceAutoKeysound (NoteData & out, int row, TapNote akTap)
References NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::IsHoldNoteAtRow(), NoteData::SetTapNote(), TAP_EMPTY, TapNoteType_AutoKeysound, and TapNote::type.
Referenced by NoteDataUtil::LoadOverlapped().