Etterna: IniFile Class Reference
IniFile Class Reference
The functions to read and write .INI files.
#include <IniFile.h>
Public Member Functions
IniFile ()
Set up an INI file with the defaults.
RString GetPath () const
Retrieve the filename of the last file loaded.
const RString & GetError () const
Retrieve any errors that have occurred.
bool ReadFile (const RString &sPath)
bool ReadFile (RageFileBasic &sFile)
bool WriteFile (const RString &sPath) const
bool WriteFile (RageFileBasic &sFile) const
template<typename T >
bool GetValue (const RString &sKey, const RString &sValueName, T &value) const
template<typename T >
void SetValue (const RString &sKey, const RString &sValueName, const T &value)
template<typename T >
void SetKeyValue (XNode *keynode, const RString &sValueName, const T &value)
bool DeleteKey (const RString &keyname)
bool DeleteValue (const RString &keyname, const RString &valuename)
bool RenameKey (const RString &from, const RString &to)
Rename a key.
Public Member Functions inherited from XNode
void SetName (const RString &sName)
const RString & GetName () const
template<typename T >
void GetTextValue (T &out) const
const XNodeValue * GetAttr (const RString &sAttrName) const
XNodeValue * GetAttr (const RString &sAttrName)
template<typename T >
bool GetAttrValue (const RString &sName, T &out) const
bool PushAttrValue (lua_State *L, const RString &sName) const
XNodes::iterator GetChildrenBegin ()
XNodes::const_iterator GetChildrenBegin () const
XNodes::iterator GetChildrenEnd ()
XNodes::const_iterator GetChildrenEnd () const
bool ChildrenEmpty () const
const XNode * GetChild (const RString &sName) const
XNode * GetChild (const RString &sName)
template<typename T >
bool GetChildValue (const RString &sName, T &out) const
bool PushChildValue (lua_State *L, const RString &sName) const
template<typename T >
XNode * AppendChild (const RString &sName, T value)
XNode * AppendChild (const RString &sName)
XNode * AppendChild (XNode *node)
bool RemoveChild (XNode *node, bool bDelete=true)
void RemoveChildFromByName (XNode *node)
void RenameChildInByName (XNode *node)
XNodeValue * AppendAttrFrom (const RString &sName, XNodeValue *pValue, bool bOverwrite=true)
XNodeValue * AppendAttr (const RString &sName)
template<typename T >
XNodeValue * AppendAttr (const RString &sName, T value)
bool RemoveAttr (const RString &sName)
XNode ()
XNode (const RString &sName)
XNode (const XNode &cpy)
~XNode ()
void Clear ()
Private Attributes
RString m_sPath
RString m_sError
Additional Inherited Members
Public Attributes inherited from XNode
RString m_sName
XAttrs m_attrs
Static Public Attributes inherited from XNode
static const RString TEXT_ATTRIBUTE = "__TEXT__"
Detailed Description
The functions to read and write .INI files.
Constructor & Destructor Documentation
IniFile()
IniFile::IniFile ()
Set up an INI file with the defaults.
Member Function Documentation
DeleteKey()
bool IniFile::DeleteKey (const RString & keyname)
References XNode::GetChild(), and XNode::RemoveChild().
Referenced by InputMappings::WriteMappings().
DeleteValue()
bool IniFile::DeleteValue (const RString & keyname, const RString & valuename)
References XNode::GetChild(), and XNode::RemoveAttr().
GetError()
const RString& IniFile::GetError () const inline
Retrieve any errors that have occurred.
Returns
the latest error.
Referenced by AnimatedTexture::Load(), actor_template_t::load_frames_from_file(), actor_template_t::load_model_from_file(), and InputMappings::ReadMappings().
GetPath()
RString IniFile::GetPath () const inline
Retrieve the filename of the last file loaded.
Returns
the filename.
Referenced by Font::LoadFontPageSettings().
GetValue()
template<typename T > bool IniFile::GetValue (const RString & sKey, const RString & sValueName, T & value) const inline
References XNode::GetAttrValue(), and T.
Referenced by ImageCache::CacheImage(), SongCacheIndex::GetCacheHash(), ThemeManager::GetMetricRawRecursive(), ThemeManager::GetThemeAuthor(), ThemeManager::GetThemeDisplayName(), Character::Load(), Font::Load(), ImageCache::LoadCachedImage(), Profile::LoadEditableDataFromDir(), Font::LoadFontPageSettings(), NoteSkinManager::LoadNoteSkinDataRecursive(), ThemeManager::LoadThemeMetrics(), PrefsManager::ReadDefaultsFromIni(), ImageCache::ReadFromDisk(), PrefsManager::ReadGamePrefsFromIni(), InputMappings::ReadMappings(), and PrefsManager::ReadPrefsFromIni().
ReadFile() [1/2]
bool IniFile::ReadFile (const RString & sPath)
References CHECKPOINT_M, f, RageFile::GetError(), LOG, m_sError, m_sPath, RageFile::Open(), ssprintf(), and RageLog::Trace().
Referenced by BGAnimation::AddLayersFromAniDir(), ThemeManager::GetThemeAuthor(), ThemeManager::GetThemeDisplayName(), PlayerAI::InitFromDisk(), Character::Load(), AnimatedTexture::Load(), Font::Load(), actor_template_t::load_frames_from_file(), actor_template_t::load_model_from_file(), Profile::LoadEditableDataFromDir(), BGAnimation::LoadFromAniDir(), NoteSkinManager::LoadNoteSkinDataRecursive(), ThemeManager::LoadThemeMetrics(), Profile::LoadTypeFromDir(), ActorUtil::MakeActor(), Nsis(), PrefsManager::ReadDefaultsFromFile(), ImageCache::ReadFromDisk(), PrefsManager::ReadGamePrefsFromIni(), InputMappings::ReadMappings(), PrefsManager::ReadPrefsFromFile(), and InputMappings::WriteMappings().
ReadFile() [2/2]
bool IniFile::ReadFile (RageFileBasic & sFile)
References XNode::AppendChild(), XNode::GetChild(), RageFileBasic::GetError(), RageFileBasic::GetLine(), StdString::CStdStr< CT >::Left(), m_sError, StdString::CStdStr< CT >::Right(), SetKeyValue(), Trim(), and Rage::utf8_remove_bom().
RenameKey()
bool IniFile::RenameKey (const RString & from, const RString & to)
Rename a key.
For example, call RenameKey("foo", "main") after reading an INI where [foo] is an alias to [main]. If to already exists, nothing happens.
Parameters
from the key to rename.
to the new key name.
Returns
its success or failure.
References XNode::GetChild(), XNode::RenameChildInByName(), and XNode::SetName().
Referenced by Font::Load(), and Font::LoadFontPageSettings().
SetKeyValue()
template<typename T > void IniFile::SetKeyValue (XNode * keynode, const RString & sValueName, const T & value) inline
References XNode::AppendAttr(), and T.
Referenced by ReadFile().
SetValue()
template<typename T > void IniFile::SetValue (const RString & sKey, const RString & sValueName, const T & value) inline
References XNode::AppendAttr(), and T.
Referenced by ImageCache::CacheImageInternal(), ThemeManager::LoadThemeMetrics(), ImageCache::ReadFromDisk(), Profile::SaveEditableDataToDir(), PrefsManager::SavePrefsToIni(), and Profile::SaveTypeToDir().
WriteFile() [1/2]
bool IniFile::WriteFile (const RString & sPath) const
References f, RageFile::Flush(), RageFile::GetError(), LOG, m_sError, RageFile::Open(), RageLog::Warn(), and RageFile::WRITE.
Referenced by ImageCache::CacheImageInternal(), ImageCache::ReadFromDisk(), Profile::SaveEditableDataToDir(), PrefsManager::SavePrefsToDisk(), Profile::SaveTypeToDir(), and InputMappings::WriteMappings().
WriteFile() [2/2]
bool IniFile::WriteFile (RageFileBasic & sFile) const
References DEBUG_ASSERT, FOREACH_CONST_Attr, FOREACH_CONST_Child, RageFileBasic::GetError(), m_sError, and RageFileBasic::PutLine().
Member Data Documentation
m_sError
RString IniFile::m_sError mutable private
Referenced by ReadFile(), and WriteFile().
m_sPath
RString IniFile::m_sPath private
Referenced by ReadFile().
The documentation for this class was generated from the following files:
IniFile.h
IniFile.cpp