Etterna: LunaHoldJudgment Class Reference
LunaHoldJudgment Class Reference
Allow Lua to have access to the HoldJudgment.
Public Member Functions
LunaHoldJudgment ()
Public Member Functions inherited from Luna< HoldJudgment >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int LoadFromMultiPlayer (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< HoldJudgment >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< HoldJudgment >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< HoldJudgment >
using T = HoldJudgment
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< HoldJudgment >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the HoldJudgment.
Constructor & Destructor Documentation
LunaHoldJudgment()
LunaHoldJudgment::LunaHoldJudgment () inline
References ADD_METHOD, and LoadFromMultiPlayer().
Member Function Documentation
LoadFromMultiPlayer()
static int LunaHoldJudgment::LoadFromMultiPlayer (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and HoldJudgment::LoadFromMultiPlayer().
Referenced by LunaHoldJudgment().
The documentation for this class was generated from the following file:
HoldJudgment.cpp