Etterna: RageMath.cpp File Reference
RageMath.cpp File Reference
#include "RageMath.h"
#include "RageTypes.h"
#include "global.h"
#include <cfloat>
#include "LuaBinding.h"
Classes
struct sine_initter
struct LunaRageQuadratic
struct LunaRageBezier2D
Macros
#define m00 m[0][0]
#define m01 m[0][1]
#define m02 m[0][2]
#define m03 m[0][3]
#define m10 m[1][0]
#define m11 m[1][1]
#define m12 m[1][2]
#define m13 m[1][3]
#define m20 m[2][0]
#define m21 m[2][1]
#define m22 m[2][2]
#define m23 m[2][3]
#define m30 m[3][0]
#define m31 m[3][1]
#define m32 m[3][2]
#define m33 m[3][3]
#define SET_SAMPLE(sample)
Functions
void RageVec3ClearBounds (RageVector3 &mins, RageVector3 &maxs)
void RageVec3AddToBounds (const RageVector3 &p, RageVector3 &mins, RageVector3 &maxs)
void RageVec2Normalize (RageVector2 *pOut, const RageVector2 *pV)
void RageVec3Normalize (RageVector3 *pOut, const RageVector3 *pV)
void VectorFloatNormalize (vector< float > &v)
void RageVec3Cross (RageVector3 *ret, RageVector3 const *a, RageVector3 const *b)
void RageVec3TransformCoord (RageVector3 *pOut, const RageVector3 *pV, const RageMatrix *pM)
void RageVec3TransformNormal (RageVector3 *pOut, const RageVector3 *pV, const RageMatrix *pM)
void RageVec4TransformCoord (RageVector4 *pOut, const RageVector4 *pV, const RageMatrix *pM)
void RageMatrixIdentity (RageMatrix *pOut)
void RageMatrixMultiply (RageMatrix *pOut, const RageMatrix *pA, const RageMatrix *pB)
void RageMatrixTranslation (RageMatrix *pOut, float x, float y, float z)
void RageMatrixScaling (RageMatrix *pOut, float x, float y, float z)
void RageMatrixSkewX (RageMatrix *pOut, float fAmount)
void RageMatrixSkewY (RageMatrix *pOut, float fAmount)
void RageMatrixTranslate (RageMatrix *pOut, float fTransX, float fTransY, float fTransZ)
void RageMatrixScale (RageMatrix *pOut, float fScaleX, float fScaleY, float fScaleZ)
void RageMatrixRotationX (RageMatrix *pOut, float theta)
void RageMatrixRotationY (RageMatrix *pOut, float theta)
void RageMatrixRotationZ (RageMatrix *pOut, float theta)
void RageMatrixRotationXYZ (RageMatrix *pOut, float rX, float rY, float rZ)
void RageAARotate (RageVector3 *inret, RageVector3 const *axis, float angle)
void RageQuatMultiply (RageVector4 *pOut, const RageVector4 &pA, const RageVector4 &pB)
RageVector4 RageQuatFromH (float theta)
RageVector4 RageQuatFromP (float theta)
RageVector4 RageQuatFromR (float theta)
void RageQuatFromHPR (RageVector4 *pOut, RageVector3 hpr)
void RageQuatFromPRH (RageVector4 *pOut, RageVector3 prh)
void RageMatrixFromQuat (RageMatrix *pOut, const RageVector4 &q)
void RageQuatSlerp (RageVector4 *pOut, const RageVector4 &from, const RageVector4 &to, float t)
RageMatrix RageLookAt (float eyex, float eyey, float eyez, float centerx, float centery, float centerz, float upx, float upy, float upz)
void RageMatrixAngles (RageMatrix *pOut, const RageVector3 &angles)
void RageMatrixTranspose (RageMatrix *pOut, const RageMatrix *pIn)
float RageFastSin (float angle)
float RageFastCos (float x)
LUA_REGISTER_CLASS (RageQuadratic)
LUA_REGISTER_CLASS (RageBezier2D)
int LuaFunc_create_bezier (lua_State *L)
LUAFUNC_REGISTER_COMMON (create_bezier)
Variables
static const unsigned int sine_table_size = 1024
static const unsigned int sine_index_mod = sine_table_size * 2
static const double sine_table_index_mult
static float sine_table [sine_table_size]
static sine_initter sinner
Macro Definition Documentation
m00
#define m00 m[0][0]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m01
#define m01 m[0][1]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m02
#define m02 m[0][2]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m03
#define m03 m[0][3]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m10
#define m10 m[1][0]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m11
#define m11 m[1][1]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m12
#define m12 m[1][2]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m13
#define m13 m[1][3]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m20
#define m20 m[2][0]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m21
#define m21 m[2][1]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m22
#define m22 m[2][2]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m23
#define m23 m[2][3]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m30
#define m30 m[3][0]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m31
#define m31 m[3][1]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m32
#define m32 m[3][2]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
m33
#define m33 m[3][3]
Referenced by RageMatrix::GetTranspose(), and RageMatrix::RageMatrix().
SET_SAMPLE
#define SET_SAMPLE (sample)
Value:
if (sample##_index >= sine_table_size) {                                   \
        (sample) = -sine_table[sample##_index - sine_table_size];              \
    } else {                                                                   \
        (sample) = sine_table[sample##_index];                                 \
    }
Referenced by RageFastSin().
Function Documentation
LUA_REGISTER_CLASS() [1/2]
LUA_REGISTER_CLASS (RageQuadratic)
LUA_REGISTER_CLASS() [2/2]
LUA_REGISTER_CLASS (RageBezier2D)
LuaFunc_create_bezier()
int LuaFunc_create_bezier (lua_State * L)
References RageBezier2D::PushSelf().
LUAFUNC_REGISTER_COMMON()
LUAFUNC_REGISTER_COMMON (create_bezier)
RageAARotate()
void RageAARotate (RageVector3 * inret, RageVector3 const * axis, float angle)
References RageFastCos(), RageFastSin(), RageQuatMultiply(), RageVector3::x, RageVector4::x, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
Referenced by NoteDisplay::DrawHoldPart().
RageFastCos()
float RageFastCos (float x)
References f, PI, and RageFastSin().
Referenced by RageDisplay::DrawCircleInternal(), NoteField::DrawPrimitives(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ArrowEffects::GetXPos(), ArrowEffects::GetYOffset(), GraphLine::MakeCircle(), Actor::PreDraw(), RageAARotate(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationXYZ(), RageMatrixRotationY(), RageMatrixRotationZ(), RageQuatFromH(), RageQuatFromHPR(), RageQuatFromP(), RageQuatFromPRH(), RageQuatFromR(), TweenSpring::Tween(), and ArrowEffects::Update().
RageFastSin()
float RageFastSin (float angle)
References lerp(), second, SET_SAMPLE, sine_index_mod, and sine_table_index_mult.
Referenced by ArrowGetPercentVisible(), RageDisplay::DrawCircleInternal(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ArrowEffects::GetXPos(), ArrowEffects::GetYOffset(), ArrowEffects::GetZPos(), GraphLine::MakeCircle(), Actor::PreDraw(), RageAARotate(), RageFastCos(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationXYZ(), RageMatrixRotationY(), RageMatrixRotationZ(), RageQuatFromH(), RageQuatFromHPR(), RageQuatFromP(), RageQuatFromPRH(), RageQuatFromR(), and RageQuatSlerp().
RageLookAt()
RageMatrix RageLookAt (float eyex, float eyey, float eyez, float centerx, float centery, float centerz, float upx, float upy, float upz)
References RageMatrixMultiply(), RageMatrixTranslation(), RageVec3Normalize(), and X.
Referenced by RageDisplay::LoadLookAt(), and RageDisplay::LoadMenuPerspective().
RageMatrixAngles()
void RageMatrixAngles (RageMatrix * pOut, const RageVector3 & angles)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by Model::PlayAnimation().
RageMatrixFromQuat()
void RageMatrixFromQuat (RageMatrix * pOut, const RageVector4 & q)
References RageVector4::w, RageVector4::x, RageVector4::y, and RageVector4::z.
Referenced by Actor::BeginDraw(), and Model::SetBones().
RageMatrixIdentity()
void RageMatrixIdentity (RageMatrix * pOut)
Referenced by MatrixStack::LoadIdentity(), RageDisplay::RageDisplay(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationY(), RageMatrixRotationZ(), RageMatrixScaling(), RageMatrixSkewX(), RageMatrixSkewY(), RageMatrixTranslation(), and Model::SetBones().
RageMatrixMultiply()
void RageMatrixMultiply (RageMatrix * pOut, const RageMatrix * pA, const RageMatrix * pB)
Referenced by RageDisplay::GetCenteringMatrix(), RageDisplay_D3D::GetOrthoMatrix(), MatrixStack::MultMatrix(), MatrixStack::MultMatrixLocal(), Model::PlayAnimation(), RageLookAt(), RageDisplay_D3D::SendCurrentMatrices(), RageDisplay_Legacy::SendCurrentMatrices(), and Model::SetBones().
RageMatrixRotationX()
void RageMatrixRotationX (RageMatrix * pOut, float theta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by MatrixStack::RotateX(), and MatrixStack::RotateXLocal().
RageMatrixRotationXYZ()
void RageMatrixRotationXYZ (RageMatrix * pOut, float rX, float rY, float rZ)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::BeginDraw().
RageMatrixRotationY()
void RageMatrixRotationY (RageMatrix * pOut, float theta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by DancingCharacters::DrawPrimitives(), MatrixStack::RotateY(), and MatrixStack::RotateYLocal().
RageMatrixRotationZ()
void RageMatrixRotationZ (RageMatrix * pOut, float theta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by MatrixStack::RotateZ(), and MatrixStack::RotateZLocal().
RageMatrixScale()
void RageMatrixScale (RageMatrix * pOut, float fScaleX, float fScaleY, float fScaleZ)
Referenced by Actor::BeginDraw(), RageDisplay_D3D::SendCurrentMatrices(), and RageDisplay_Legacy::SendCurrentMatrices().
RageMatrixScaling()
void RageMatrixScaling (RageMatrix * pOut, float x, float y, float z)
References RageMatrixIdentity().
Referenced by RageDisplay::GetCenteringMatrix(), RageDisplay_D3D::GetOrthoMatrix(), MatrixStack::Scale(), and MatrixStack::ScaleLocal().
RageMatrixSkewX()
void RageMatrixSkewX (RageMatrix * pOut, float fAmount)
References RageMatrix::m, and RageMatrixIdentity().
Referenced by MatrixStack::SkewX().
RageMatrixSkewY()
void RageMatrixSkewY (RageMatrix * pOut, float fAmount)
References RageMatrix::m, and RageMatrixIdentity().
Referenced by MatrixStack::SkewY().
RageMatrixTranslate()
void RageMatrixTranslate (RageMatrix * pOut, float fTransX, float fTransY, float fTransZ)
Referenced by Actor::BeginDraw().
RageMatrixTranslation()
void RageMatrixTranslation (RageMatrix * pOut, float x, float y, float z)
References RageMatrixIdentity().
Referenced by RageDisplay::GetCenteringMatrix(), RageDisplay_D3D::GetOrthoMatrix(), RageLookAt(), MatrixStack::Translate(), and MatrixStack::TranslateLocal().
RageMatrixTranspose()
void RageMatrixTranspose (RageMatrix * pOut, const RageMatrix * pIn)
Referenced by Model::PlayAnimation().
RageQuatFromH()
RageVector4 RageQuatFromH (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationH().
RageQuatFromHPR()
void RageQuatFromHPR (RageVector4 * pOut, RageVector3 hpr)
References PI, RageFastCos(), RageFastSin(), RageVector4::w, RageVector3::x, RageVector4::x, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
Referenced by msAnimation::LoadMilkshapeAsciiBones().
RageQuatFromP()
RageVector4 RageQuatFromP (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationP().
RageQuatFromPRH()
void RageQuatFromPRH (RageVector4 * pOut, RageVector3 prh)
References PI, RageFastCos(), RageFastSin(), RageVector4::w, RageVector3::x, RageVector4::x, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
RageQuatFromR()
RageVector4 RageQuatFromR (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationR().
RageQuatMultiply()
void RageQuatMultiply (RageVector4 * pOut, const RageVector4 & pA, const RageVector4 & pB)
References RageVector4::w, RageVector4::x, RageVector4::y, and RageVector4::z.
Referenced by Actor::AddRotationH(), Actor::AddRotationP(), Actor::AddRotationR(), and RageAARotate().
RageQuatSlerp()
void RageQuatSlerp (RageVector4 * pOut, const RageVector4 & from, const RageVector4 & to, float t)
References f, and RageFastSin().
Referenced by Actor::TweenState::MakeWeightedAverage(), and Model::SetBones().
RageVec2Normalize()
void RageVec2Normalize (RageVector2 * pOut, const RageVector2 * pV)
References scale().
RageVec3AddToBounds()
void RageVec3AddToBounds (const RageVector3 & p, RageVector3 & mins, RageVector3 & maxs)
References max(), min(), RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by RageModelGeometry::LoadMilkshapeAscii().
RageVec3ClearBounds()
void RageVec3ClearBounds (RageVector3 & mins, RageVector3 & maxs)
Referenced by RageModelGeometry::LoadMilkshapeAscii().
RageVec3Cross()
void RageVec3Cross (RageVector3 * ret, RageVector3 const * a, RageVector3 const * b)
Referenced by NoteDisplay::DrawHoldPart().
RageVec3Normalize()
void RageVec3Normalize (RageVector3 * pOut, const RageVector3 * pV)
References scale().
Referenced by NoteDisplay::DrawHoldPart(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), RageModelGeometry::LoadMilkshapeAscii(), and RageLookAt().
RageVec3TransformCoord()
void RageVec3TransformCoord (RageVector3 * pOut, const RageVector3 * pV, const RageMatrix * pM)
References RageVec4TransformCoord(), RageVector4::w, RageVector4::x, RageVector4::y, and RageVector4::z.
Referenced by DancingCharacters::DrawPrimitives(), and Model::UpdateTempGeometry().
RageVec3TransformNormal()
void RageVec3TransformNormal (RageVector3 * pOut, const RageVector3 * pV, const RageMatrix * pM)
References RageVec4TransformCoord(), RageVector4::x, RageVector4::y, and RageVector4::z.
Referenced by Model::PlayAnimation(), and Model::UpdateTempGeometry().
RageVec4TransformCoord()
void RageVec4TransformCoord (RageVector4 * pOut, const RageVector4 * pV, const RageMatrix * pM)
References RageVector4::w, RageVector4::x, RageVector4::y, and RageVector4::z.
Referenced by RageVec3TransformCoord(), and RageVec3TransformNormal().
VectorFloatNormalize()
void VectorFloatNormalize (vector< float > & v)
References ASSERT_M, and scale().
Variable Documentation
sine_index_mod
const unsigned int sine_index_mod = sine_table_size * 2 static
Referenced by RageFastSin().
sine_table
float sine_table[sine_table_size] static
sine_table_index_mult
const double sine_table_index_mult static
Initial value:
=
  static_cast<double>(sine_index_mod) / (PI * 2)
Referenced by RageFastSin().
sine_table_size
const unsigned int sine_table_size = 1024 static
Referenced by sine_initter::sine_initter().
sinner
sine_initter sinner static