Etterna: StdString Namespace Reference
StdString Namespace Reference
Inline functions on which CStdString relies on.
Classes
class CStdStr
Our wrapper for std::string.
struct StdStringEqualsNoCase
struct StdStringLessNoCase
Typedefs
typedef std::string::size_type SS_SIZETYPE
typedef std::string::pointer SS_PTRTYPE
typedef CStdStr< char > CStdStringA
Typedef the class names based on the template.
Functions
char sstoupper (char ch)
Turn the character into its uppercase equivalent.
char sstolower (char ch)
Turn the character into its lowercase equivalent.
void ssasn (std::string &sDst, const std::string &sSrc)
Assign one string to another.
void ssasn (std::string &sDst, PCSTR pA)
Assign one string to another.
void ssadd (std::string &sDst, const std::string &sSrc)
Concatenate one string with another.
void ssadd (std::string &sDst, PCSTR pA)
Concatenate one string with another.
template<typename CT >
int ssicmp (const CT *pA1, const CT *pA2)
Perform a case insensitive comparison of the two strings.
void sslwr (char *pT, size_t nLen)
void ssupr (char *pT, size_t nLen)
void sslwr (wchar_t *pT, size_t nLen)
void ssupr (wchar_t *pT, size_t nLen)
template<typename CT >
CStdStr< CT > operator+ (const CStdStr< CT > &str1, const CStdStr< CT > &str2)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > operator+ (const CStdStr< CT > &str, CT t)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > operator+ (const CStdStr< CT > &str, PCSTR pA)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > operator+ (PCSTR pA, const CStdStr< CT > &str)
Another way to concatenate two strings together.
Detailed Description
Inline functions on which CStdString relies on.
Usually for generic text mapping, we rely on preprocessor macro definitions to map to string functions. However the CStdStr<> template cannot use macro-based generic text mappings because its character types do not get resolved until template processing which comes AFTER macro processing. In other words, UNICODE is of little help to us in the CStdStr template.
Therefore, to keep the CStdStr declaration simple, we have these inline functions. The template calls them often. Since they are inline (and NOT exported when this is built as a DLL), they will probably be resolved away to nothing.
Without these functions, the CStdStr<> template would probably have to broken out into two, almost identical classes. Either that or it would be a huge, convoluted mess, with tons of "if" statements all over the place checking the size of template parameter CT.
In several cases, you will see two versions of each function. One version is the more portable, standard way of doing things, while the other is the non-standard, but often significantly faster Visual C++ way.
Typedef Documentation
CStdStringA
typedef CStdStr<char> StdString::CStdStringA
Typedef the class names based on the template.
SS_PTRTYPE
typedef std::string::pointer StdString::SS_PTRTYPE
SS_SIZETYPE
typedef std::string::size_type StdString::SS_SIZETYPE
Function Documentation
operator+() [1/4]
template<typename CT > CStdStr<CT> StdString::operator+ (const CStdStr< CT > & str1, const CStdStr< CT > & str2)
Another way to concatenate two strings together.
Parameters
str1 the original string.
str2 the string to be added.
Returns
the longer string.
operator+() [2/4]
template<typename CT > CStdStr<CT> StdString::operator+ (const CStdStr< CT > & str, CT t)
Another way to concatenate two strings together.
Parameters
str the original string.
t the string to be added.
Returns
the longer string.
operator+() [3/4]
template<typename CT > CStdStr<CT> StdString::operator+ (const CStdStr< CT > & str, PCSTR pA)
Another way to concatenate two strings together.
Parameters
str the original string.
pA the string to be added.
Returns
the longer string.
operator+() [4/4]
template<typename CT > CStdStr<CT> StdString::operator+ (PCSTR pA, const CStdStr< CT > & str)
Another way to concatenate two strings together.
Parameters
pA the original string.
str the string to be added.
Returns
the longer string.
ssadd() [1/2]
void StdString::ssadd (std::string & sDst, const std::string & sSrc) inline
Concatenate one string with another.
Parameters
sDst the original string.
sSrc the string being added.
Referenced by StdString::CStdStr< CT >::operator+=().
ssadd() [2/2]
void StdString::ssadd (std::string & sDst, PCSTR pA) inline
Concatenate one string with another.
Parameters
sDst the original string.
pA the string being added.
ssasn() [1/2]
void StdString::ssasn (std::string & sDst, const std::string & sSrc) inline
Assign one string to another.
Parameters
sDst the destination string.
sSrc the source string.
Referenced by StdString::CStdStr< CT >::operator=().
ssasn() [2/2]
void StdString::ssasn (std::string & sDst, PCSTR pA) inline
Assign one string to another.
Parameters
sDst the destination string.
pA the source string.
References Q172398.
ssicmp()
template<typename CT > int StdString::ssicmp (const CT * pA1, const CT * pA2) inline
Perform a case insensitive comparison of the two strings.
Parameters
pA1 the first string.
pA2 the second string.
Returns
>0 if pA1 > pA2, <0 if pA1 < pA2, or 0 otherwise.
References f, and sstolower().
Referenced by StdString::CStdStr< CT >::CompareNoCase(), StdString::StdStringLessNoCase::operator()(), and StdString::StdStringEqualsNoCase::operator()().
sslwr() [1/2]
void StdString::sslwr (char * pT, size_t nLen) inline
References MakeLower().
Referenced by StdString::CStdStr< CT >::MakeLower().
sslwr() [2/2]
void StdString::sslwr (wchar_t * pT, size_t nLen) inline
References MakeLower().
sstolower()
char StdString::sstolower (char ch) inline
Turn the character into its lowercase equivalent.
Parameters
ch the character to convert.
Returns
the converted character.
References picosha2::detail::ch().
Referenced by ssicmp().
sstoupper()
char StdString::sstoupper (char ch) inline
Turn the character into its uppercase equivalent.
Parameters
ch the character to convert.
Returns
the converted character.
References picosha2::detail::ch().
ssupr() [1/2]
void StdString::ssupr (char * pT, size_t nLen) inline
References MakeUpper().
Referenced by StdString::CStdStr< CT >::MakeUpper().
ssupr() [2/2]
void StdString::ssupr (wchar_t * pT, size_t nLen) inline
References MakeUpper().