Etterna: LabelSegment Struct Reference
LabelSegment Struct Reference
Identifies when a chart is entering a different section.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
LabelSegment (int iStartRow=ROW_INVALID, const RString &sLabel=RString())
LabelSegment (const LabelSegment &other)
const RString & GetLabel () const
void SetLabel (const RString &sLabel)
RString ToString (int dec) const override
bool operator== (const LabelSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
virtual vector< float > GetValues () const
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
RString m_sLabel
The label/section name for this point.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a chart is entering a different section.
This is meant for helping to identify different sections of a chart versus relying on measures and beats alone.
Constructor & Destructor Documentation
LabelSegment() [1/2]
LabelSegment::LabelSegment (int iStartRow = ROW_INVALID, const RString & sLabel = RString()) inline
Referenced by Copy().
LabelSegment() [2/2]
LabelSegment::LabelSegment (const LabelSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* LabelSegment::Copy () const inline override virtual
Implements TimingSegment.
References LabelSegment().
DebugPrint()
void LabelSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLabel(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType LabelSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetLabel()
const RString& LabelSegment::GetLabel () const inline
References m_sLabel.
Referenced by DebugPrint(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetType()
TimingSegmentType LabelSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_LABEL.
Referenced by DebugPrint(), and operator==().
IsNotable()
bool LabelSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool LabelSegment::operator== (const LabelSegment & other) const inline
References COMPARE, and m_sLabel.
Referenced by operator==().
operator==() [2/2]
bool LabelSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetLabel()
void LabelSegment::SetLabel (const RString & sLabel) inline
References m_sLabel.
ToString()
RString LabelSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLabel(), IntToString(), and ssprintf().
Member Data Documentation
m_sLabel
RString LabelSegment::m_sLabel private
The label/section name for this point.
Referenced by GetLabel(), operator==(), and SetLabel().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp