Etterna: ScreenServiceAction.cpp File Reference
ScreenServiceAction.cpp File Reference
#include "ScreenServiceAction.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "NotesLoaderSSC.h"
#include "PlayerState.h"
#include "ProfileManager.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "Song.h"
#include "SongManager.h"
#include "StepMania.h"
#include "ThemeManager.h"
#include "global.h"
Functions
static void CopyEdits (const RString &sFromProfileDir, const RString &sToProfileDir, int &iNumSucceeded, int &iNumOverwritten, int &iNumIgnored, int &iNumErrored)
static RString CopyEdits (const RString &sFromProfileDir, const RString &sToProfileDir, const RString &sDisplayDir)
static void SyncFiles (const RString &sFromDir, const RString &sToDir, const RString &sMask, int &iNumAdded, int &iNumDeleted, int &iNumOverwritten, int &iNumFailed)
static void SyncEdits (const RString &sFromDir, const RString &sToDir, int &iNumAdded, int &iNumDeleted, int &iNumOverwritten, int &iNumFailed)
static RString ResetPreferences ()
REGISTER_SCREEN_CLASS (ScreenServiceAction)
Variables
static LocalizedString EDITS_CLEARED ("ScreenServiceAction", "%d edits cleared, %d errors.")
static LocalizedString STATS_NOT_SAVED ("ScreenServiceAction", "Stats not saved - No memory cards ready.")
static LocalizedString STATS_NOT_LOADED ("ScreenServiceAction", "Stats not loaded - No memory cards ready.")
static LocalizedString THERE_IS_NO_PROFILE ("ScreenServiceAction", "There is no machine profile on P%d card.")
static LocalizedString PROFILE_CORRUPT ("ScreenServiceAction", "The profile on P%d card contains corrupt or tampered data.")
static LocalizedString EDITS_NOT_COPIED ("ScreenServiceAction", "Edits not copied - No memory cards ready.")
static LocalizedString COPIED_TO_CARD ("ScreenServiceAction", "Copied to P%d card:")
static LocalizedString COPIED ("ScreenServiceAction", "%d copied")
static LocalizedString OVERWRITTEN ("ScreenServiceAction", "%d overwritten")
static LocalizedString ADDED ("ScreenServiceAction", "%d added")
static LocalizedString IGNORED ("ScreenServiceAction", "%d ignored")
static LocalizedString FAILED ("ScreenServiceAction", "%d failed")
static LocalizedString DELETED ("ScreenServiceAction", "%d deleted")
static LocalizedString COPIED_FROM_CARD ("ScreenServiceAction", "Copied from P%d card:")
static LocalizedString PREFERENCES_RESET ("ScreenServiceAction", "Preferences reset.")
Function Documentation
CopyEdits() [1/2]
static void CopyEdits (const RString & sFromProfileDir, const RString & sToProfileDir, int & iNumSucceeded, int & iNumOverwritten, int & iNumIgnored, int & iNumErrored) static
References DoesFileExist(), EDIT_STEPS_SUBDIR, FileCopy(), FOREACH_CONST, and GetDirListing().
Referenced by CopyEdits().
CopyEdits() [2/2]
static RString CopyEdits (const RString & sFromProfileDir, const RString & sToProfileDir, const RString & sDisplayDir) static
References COPIED, CopyEdits(), FAILED, LocalizedString::GetValue(), IGNORED, Rage::join(), OVERWRITTEN, and ssprintf().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenServiceAction)
ResetPreferences()
static RString ResetPreferences () static
References LocalizedString::GetValue(), PREFERENCES_RESET, and StepMania::ResetPreferences().
Referenced by ScreenServiceAction::BeginScreen().
SyncEdits()
static void SyncEdits (const RString & sFromDir, const RString & sToDir, int & iNumAdded, int & iNumDeleted, int & iNumOverwritten, int & iNumFailed) static
References EDIT_STEPS_SUBDIR, and SyncFiles().
SyncFiles()
static void SyncFiles (const RString & sFromDir, const RString & sToDir, const RString & sMask, int & iNumAdded, int & iNumDeleted, int & iNumOverwritten, int & iNumFailed) static
References DoesFileExist(), FileCopy(), FILEMAN, RageFileManager::FlushDirCache(), GetAsNotInBs(), GetDirListing(), LOG, RageFileManager::Remove(), and RageLog::Trace().
Referenced by SyncEdits().
Variable Documentation
ADDED
LocalizedString ADDED("ScreenServiceAction", "%d added") static
COPIED
LocalizedString COPIED("ScreenServiceAction", "%d copied") static
Referenced by CopyEdits().
COPIED_FROM_CARD
LocalizedString COPIED_FROM_CARD("ScreenServiceAction", "Copied from P%d card:") static
COPIED_TO_CARD
LocalizedString COPIED_TO_CARD("ScreenServiceAction", "Copied to P%d card:") static
DELETED
LocalizedString DELETED("ScreenServiceAction", "%d deleted") static
EDITS_CLEARED
LocalizedString EDITS_CLEARED("ScreenServiceAction", "%d edits cleared, %d errors.") static
EDITS_NOT_COPIED
LocalizedString EDITS_NOT_COPIED("ScreenServiceAction", "Edits not copied - No memory cards ready.") static
FAILED
LocalizedString FAILED("ScreenServiceAction", "%d failed") static
Referenced by CopyEdits(), MovieTexture_DShow::Create(), RageDisplay_D3D::CreateTexture(), DSound::DSound(), FindBackBufferType(), MovieTexture_DShow::GetActiveFilterList(), RageDisplay_D3D::Init(), DSound::Init(), DSoundBuf::Init(), InputHandler_DInput::InputThreadMain(), DSound::IsEmulated(), MovieTexture_DShow::Pause(), MovieTexture_DShow::Play(), SetD3DParams(), MovieTexture_DShow::SetPlaybackRate(), DSound::SetPrimaryBufferMode(), RageDisplay_D3D::SetRenderTarget(), DSoundBuf::SetSampleRate(), DSoundBuf::SetVolume(), and MovieTexture_DShow::~MovieTexture_DShow().
IGNORED
LocalizedString IGNORED("ScreenServiceAction", "%d ignored") static
Referenced by CopyEdits().
OVERWRITTEN
LocalizedString OVERWRITTEN("ScreenServiceAction", "%d overwritten") static
Referenced by CopyEdits().
PREFERENCES_RESET
LocalizedString PREFERENCES_RESET("ScreenServiceAction", "Preferences reset.") static
Referenced by ResetPreferences().
PROFILE_CORRUPT
LocalizedString PROFILE_CORRUPT("ScreenServiceAction", "The profile on P%d card contains corrupt or tampered data.") static
STATS_NOT_LOADED
LocalizedString STATS_NOT_LOADED("ScreenServiceAction", "Stats not loaded - No memory cards ready.") static
STATS_NOT_SAVED
LocalizedString STATS_NOT_SAVED("ScreenServiceAction", "Stats not saved - No memory cards ready.") static
THERE_IS_NO_PROFILE
LocalizedString THERE_IS_NO_PROFILE("ScreenServiceAction", "There is no machine profile on P%d card.") static