Etterna: ScreenManager Class Reference
ScreenManager Class Reference
Manager/container for Screens.
#include <ScreenManager.h>
Public Member Functions
ScreenManager ()
~ScreenManager ()
void Update (float fDeltaTime)
void Draw ()
void Input (const InputEventPlus &input)
void SetNewScreen (const RString &sName)
void AddNewScreenToTop (const RString &sName, ScreenMessage SendOnPop=SM_None)
void PrepareScreen (const RString &sScreenName)
Create and cache the requested Screen.
void GroupScreen (const RString &sScreenName)
void PersistantScreen (const RString &sScreenName)
void PopTopScreen (ScreenMessage SM)
void PopAllScreens ()
Screen * GetTopScreen ()
Screen * GetScreen (int iPosition)
bool AllowOperatorMenuButton () const
bool IsScreenNameValid (RString const &name) const
void SystemMessage (const RString &sMessage)
void SystemMessageNoAnimate (const RString &sMessage)
void HideSystemMessage ()
void PostMessageToTopScreen (ScreenMessage SM, float fDelay)
void SendMessageToTopScreen (ScreenMessage SM)
void RefreshCreditsMessages ()
void ThemeChanged ()
void ReloadOverlayScreens ()
void ReloadOverlayScreensAfterInputFinishes ()
bool IsStackedScreen (const Screen *pScreen) const
Is this Screen in the main Screen stack, but not the bottommost Screen?
bool get_input_redirected (PlayerNumber pn)
void set_input_redirected (PlayerNumber pn, bool redir)
void PushSelf (lua_State *L)
void PlaySharedBackgroundOffCommand ()
void ZeroNextUpdate ()
void PlayStartSound ()
void PlayCoinSound ()
void PlayCancelSound ()
void PlayInvalidSound ()
void PlayScreenshotSound ()
Private Member Functions
Screen * MakeNewScreen (const RString &sName)
void LoadDelayedScreen ()
bool ActivatePreparedScreenAndBackground (const RString &sScreenName)
ScreenMessage PopTopScreenInternal (bool bSendLoseFocus=true)
Private Attributes
RString m_sDelayedScreen
RString m_sDelayedConcurrentPrepare
ScreenMessage m_OnDonePreparingScreen
ScreenMessage m_PopTopScreen
bool m_bZeroNextUpdate
bool m_bReloadOverlayScreensAfterInput
std::vector< bool > m_input_redirected
RageSound m_soundStart
RageSound m_soundCoin
The sound played when a coin has been put into the machine.
RageSound m_soundCancel
RageSound m_soundInvalid
RageSound m_soundScreenshot
The sound played when a Player wishes to take a picture of their Score.
Detailed Description
Manager/container for Screens.
Constructor & Destructor Documentation
ScreenManager()
ScreenManager::ScreenManager ()
References ScreenManagerUtil::g_pSharedBGA, LuaManager::Get(), L, LUA, LuaManager::Release(), and SM_Invalid.
~ScreenManager()
ScreenManager::~ScreenManager ()
References ScreenManagerUtil::DeletePreparedScreens(), ScreenManagerUtil::g_OverlayScreens, ScreenManagerUtil::g_pSharedBGA, ScreenManagerUtil::g_ScreenStack, LOG, LUA, SAFE_DELETE, RageLog::Trace(), RageLog::UnmapLog(), and LuaManager::UnsetGlobal().
Member Function Documentation
ActivatePreparedScreenAndBackground()
bool ScreenManager::ActivatePreparedScreenAndBackground (const RString & sScreenName) private
References FOREACH, ScreenManagerUtil::g_pSharedBGA, ScreenManagerUtil::g_vPreparedBackgrounds, Actor::GetName(), ThemeManager::GetPathB(), ScreenManagerUtil::GetPreppedScreen(), Actor::PlayCommand(), ScreenManagerUtil::PushLoadedScreen(), and THEME.
AddNewScreenToTop()
void ScreenManager::AddNewScreenToTop (const RString & sName, ScreenMessage SendOnPop = SM_None)
References ASSERT_M, ScreenManagerUtil::g_ScreenStack, ScreenManagerUtil::GetPreppedScreen(), ScreenManagerUtil::LoadedScreen::m_SendOnPop, ScreenManagerUtil::PushLoadedScreen(), SM_LoseFocus, and ssprintf().
Referenced by LunaScreenManager::AddNewScreenToTop(), ScreenSelectMusic::Input(), ScreenNetSelectMusic::MenuUp(), ScreenMiniMenu::MiniMenu(), ScreenPrompt::Prompt(), and ScreenTextEntry::TextEntry().
AllowOperatorMenuButton()
bool ScreenManager::AllowOperatorMenuButton () const
References FOREACH, and ScreenManagerUtil::g_ScreenStack.
Referenced by HandleGlobalInputs().
Draw()
void ScreenManager::Draw ()
References RageDisplay::BeginFrame(), RageDisplay::CameraPopMatrix(), RageDisplay::CameraPushMatrix(), DISPLAY, Actor::Draw(), RageDisplay::EndFrame(), ScreenManagerUtil::g_OverlayScreens, ScreenManagerUtil::g_pSharedBGA, ScreenManagerUtil::g_ScreenStack, RageDisplay::LoadMenuPerspective(), SCREEN_CENTER_X, SCREEN_CENTER_Y, SCREEN_HEIGHT, and SCREEN_WIDTH.
Referenced by SongManager::DifferentialReloadDir(), ScreenReloadSongsLoadingWindow::Paint(), ConcurrentRenderer::RenderThread(), and GameLoop::RunGameLoop().
get_input_redirected()
bool ScreenManager::get_input_redirected (PlayerNumber pn)
Referenced by LunaScreenManager::get_input_redirected().
GetScreen()
Screen * ScreenManager::GetScreen (int iPosition)
References ScreenManagerUtil::g_ScreenStack.
Referenced by DebugLineReloadCurrentScreen::DoAndLog(), DoInstalls(), and DownloadManager::UpdatePacks().
GetTopScreen()
Screen * ScreenManager::GetTopScreen ()
References ScreenManagerUtil::g_ScreenStack.
Referenced by DebugLineRestartCurrentScreen::DoAndLog(), DebugLineCurrentScreenOn::DoAndLog(), DebugLineCurrentScreenOff::DoAndLog(), RageDisplay::FrameLimitAfterVsync(), RageDisplay::FrameLimitBeforeVsync(), DebugLineReloadCurrentScreen::GetDisplayValue(), DebugLineRestartCurrentScreen::GetDisplayValue(), DebugLineCurrentScreenOn::GetDisplayValue(), DebugLineCurrentScreenOff::GetDisplayValue(), LunaScreenManager::GetTopScreen(), HandleInputEvents(), ScreenGameplay::Input(), IsGameplay(), ScreenMiniMenu::MiniMenu(), RageTextureManager::Update(), and ScreenGameplay::Update().
GroupScreen()
void ScreenManager::GroupScreen (const RString & sScreenName)
References ScreenManagerUtil::g_setGroupedScreens.
Referenced by Screen::Init().
HideSystemMessage()
void ScreenManager::HideSystemMessage ()
References MessageManager::Broadcast(), and MESSAGEMAN.
Input()
void ScreenManager::Input (const InputEventPlus & input)
References ScreenManagerUtil::g_OverlayScreens, ScreenManagerUtil::g_ScreenStack, Screen::Input(), Screen::PassInputToLua(), and InputEventPlus::pn.
Referenced by HandleInputEvents().
IsScreenNameValid()
bool ScreenManager::IsScreenNameValid (RString const & name) const
References g_pmapRegistrees, ThemeManager::GetMetric(), ThemeManager::HasMetric(), and THEME.
Referenced by StepMania::GetInitialScreen(), and GameCommand::LoadOne().
IsStackedScreen()
bool ScreenManager::IsStackedScreen (const Screen * pScreen) const
Is this Screen in the main Screen stack, but not the bottommost Screen?
If this function returns true, the screen should exit by popping itself, not by loading another Screen.
Parameters
pScreen the Screen to check.
Returns
true if it's on the stack while not on the bottom, or false otherwise.
References ScreenManagerUtil::g_ScreenStack.
Referenced by Screen::HandleScreenMessage(), and ScreenWithMenuElements::TweenOffScreen().
LoadDelayedScreen()
void ScreenManager::LoadDelayedScreen () private
References ScreenManagerUtil::AfterDeleteScreen(), ASSERT, ScreenManagerUtil::BeforeDeleteScreen(), MessageManager::Broadcast(), ScreenManagerUtil::DeletePreparedScreens(), FOREACH, g_bDelayedScreenLoad, ScreenManagerUtil::g_setGroupedScreens, ScreenManagerUtil::GrabPreparedActors(), Message_ScreenChanged, MESSAGEMAN, LuaHelpers::ReportScriptError(), and SAFE_DELETE.
MakeNewScreen()
Screen * ScreenManager::MakeNewScreen (const RString & sName) private
References g_pmapRegistrees, RageTimer::GetDeltaTime(), ThemeManager::GetMetric(), LOG, LuaHelpers::ReportScriptErrorFmt(), THEME, and RageLog::Trace().
PersistantScreen()
void ScreenManager::PersistantScreen (const RString & sScreenName)
References ScreenManagerUtil::g_setPersistantScreens.
Referenced by Screen::Init().
PlayCancelSound()
void ScreenManager::PlayCancelSound ()
References PLAY_CRITICAL.
PlayCoinSound()
void ScreenManager::PlayCoinSound ()
References PLAY_CRITICAL.
PlayInvalidSound()
void ScreenManager::PlayInvalidSound ()
References PLAY_CRITICAL.
Referenced by ScreenTextEntry::BackspaceInAnswer(), StepMania::ClearCredits(), ScreenMapControllers::Input(), ScreenOptionsCourseOverview::ProcessMenuStart(), StepMania::SaveScreenshot(), and ScreenTextEntry::TryAppendToAnswer().
PlayScreenshotSound()
void ScreenManager::PlayScreenshotSound ()
References PLAY_CRITICAL.
Referenced by StepMania::SaveScreenshot().
PlaySharedBackgroundOffCommand()
void ScreenManager::PlaySharedBackgroundOffCommand ()
References ScreenManagerUtil::g_pSharedBGA, and Actor::PlayCommand().
Referenced by ScreenWithMenuElements::TweenOffScreen().
PlayStartSound()
void ScreenManager::PlayStartSound ()
References PLAY_CRITICAL.
Referenced by ScreenAttract::AttractInput(), ScreenPrompt::End(), ScreenTextEntry::End(), ScreenMapControllers::ExitAction(), ScreenPlayerOptions::Input(), ScreenSelect::Input(), ScreenMapControllers::Input(), ScreenTestInput::MenuBack(), ScreenSetTime::MenuStart(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), MusicWheel::Select(), ScreenSelectProfile::SetProfileIndex(), ScreenMapControllers::Update(), and MusicWheel::UpdateSwitch().
PopAllScreens()
void ScreenManager::PopAllScreens ()
References ScreenManagerUtil::DeletePreparedScreens(), and ScreenManagerUtil::g_ScreenStack.
Referenced by DebugLineReloadCurrentScreen::DoAndLog(), and HandleGlobalInputs().
PopTopScreen()
void ScreenManager::PopTopScreen (ScreenMessage SM)
References ASSERT, and ScreenManagerUtil::g_ScreenStack.
Referenced by Screen::HandleScreenMessage(), and ScreenMiniMenu::HandleScreenMessage().
PopTopScreenInternal()
ScreenMessage ScreenManager::PopTopScreenInternal (bool bSendLoseFocus = true) private
References ScreenManagerUtil::AfterDeleteScreen(), ScreenManagerUtil::BeforeDeleteScreen(), Screen::EndScreen(), ScreenManagerUtil::g_ScreenStack, ScreenManagerUtil::g_setPersistantScreens, ScreenManagerUtil::g_vPreparedScreens, Actor::GetName(), Screen::HandleScreenMessage(), LOG, ScreenManagerUtil::LoadedScreen::m_bDeleteWhenDone, ScreenManagerUtil::LoadedScreen::m_pScreen, ScreenManagerUtil::LoadedScreen::m_SendOnPop, RageLog::MapLog(), SAFE_DELETE, SM_LoseFocus, SM_None, and RageLog::UnmapLog().
PostMessageToTopScreen()
void ScreenManager::PostMessageToTopScreen (ScreenMessage SM, float fDelay)
References Screen::PostScreenMessage().
Referenced by ScreenAttract::AttractInput(), MusicWheel::ChangeMusic(), MusicWheel::ChangeSort(), DebugLineSendNotesEnded::DoAndLog(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScoreKeeperNormal::HandleTapRowScore(), Player::HandleTapRowScore(), RoomWheel::Move(), WheelBase::MoveSpecific(), ScreenManagerUtil::PushLoadedScreen(), MusicWheel::ReloadSongList(), MusicWheel::Select(), RoomWheel::Select(), Player::SendComboMessages(), ScreenReloadSongs::Update(), MenuTimer::Update(), ScreenNetSelectMusic::Update(), ScreenGameplay::Update(), and MusicWheel::UpdateSwitch().
PrepareScreen()
void ScreenManager::PrepareScreen (const RString & sScreenName)
Create and cache the requested Screen.
This is so that the next call to SetNewScreen for this Screen will be very quick.
Parameters
sScreenName the Screen to prepare.
References FOREACH, ScreenManagerUtil::g_pSharedBGA, ScreenManagerUtil::g_vPreparedBackgrounds, ScreenManagerUtil::g_vPreparedScreens, Actor::GetName(), ThemeManager::GetPathB(), LOG, ScreenManagerUtil::LoadedScreen::m_pScreen, ActorUtil::MakeActor(), ScreenManagerUtil::ScreenIsPrepped(), Actor::SetName(), THEME, and RageLog::Trace().
Referenced by GameCommand::ApplySelf(), ScreenSplash::HandleScreenMessage(), and Screen::Init().
PushSelf()
void ScreenManager::PushSelf (lua_State * L)
RefreshCreditsMessages()
void ScreenManager::RefreshCreditsMessages ()
References MessageManager::Broadcast(), and MESSAGEMAN.
Referenced by ScreenSelect::HandleScreenMessage(), and ScreenManagerUtil::PushLoadedScreen().
ReloadOverlayScreens()
void ScreenManager::ReloadOverlayScreens ()
References Screen::BeginScreen(), ScreenManagerUtil::g_OverlayScreens, ThemeManager::GetMetric(), Actor::GetName(), SAFE_DELETE, split(), and THEME.
Referenced by HandleGlobalInputs(), and LunaScreenManager::ReloadOverlayScreens().
ReloadOverlayScreensAfterInputFinishes()
void ScreenManager::ReloadOverlayScreensAfterInputFinishes ()
Referenced by DebugLineReloadOverlayScreens::DoAndLog().
SendMessageToTopScreen()
void ScreenManager::SendMessageToTopScreen (ScreenMessage SM)
References Screen::HandleScreenMessage().
Referenced by ETTProtocol::Login(), SMOProtocol::ProcessInput(), ETTProtocol::Update(), and Transition::UpdateInternal().
set_input_redirected()
void ScreenManager::set_input_redirected (PlayerNumber pn, bool redir)
Referenced by ScreenGameplay::LoadNextSong(), and LunaScreenManager::set_input_redirected().
SetNewScreen()
void ScreenManager::SetNewScreen (const RString & sName)
References ASSERT.
Referenced by GameCommand::ApplySelf(), ScreenSelectMusic::BeginScreen(), SMOProtocol::DealWithSMOnlinePack(), DebugLineReloadCurrentScreen::DoAndLog(), DoInstalls(), ScreenAttract::GoToStartScreen(), HandleGlobalInputs(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenNetRoom::HandleScreenMessage(), ScreenOptionsCourseOverview::HandleScreenMessage(), ScreenPackages::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), Screen::HandleScreenMessage(), ScreenTitleMenu::Input(), SMOProtocol::ProcessInput(), ScreenOptionsToggleSongs::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), ScreenOptionsExportPackageSubPage::ProcessMenuStart(), LunaScreenManager::SetNewScreen(), LunaScreenSelectMusic::ShowEvalScreenForScore(), sm_main(), ScreenSelect::Update(), ETTProtocol::Update(), and ScreenNetworkOptions::UpdateConnectStatus().
SystemMessage()
void ScreenManager::SystemMessage (const RString & sMessage)
References MessageManager::Broadcast(), LOG, MESSAGEMAN, Message::SetParam(), and RageLog::Trace().
Referenced by StepMania::ApplyGraphicOptions(), AdjustSync::AutosyncOffset(), AdjustSync::AutosyncTempo(), ScreenPackages::CancelDownload(), SMOProtocol::Connect(), NetworkSyncManager::DisplayStartupStatus(), DebugLineMuteActions::DoAndLog(), DownloadManager::DownloadAndInstallPack(), HandleGlobalInputs(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsCourseOverview::HandleScreenMessage(), Profile::ImportScoresToEtterna(), ScreenSyncOverlay::Input(), ScreenTitleMenu::Input(), ScreenMapControllers::Input(), ScreenDebugOverlay::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), DownloadManager::InstallSmzip(), InstallSmzipOsArg(), ScreenPackages::MenuBack(), ScreenNetworkOptions::MenuStart(), SMOProtocol::ProcessInput(), ScreenOptionsCourseOverview::ProcessMenuStart(), GameLoop::RunGameLoop(), LunaScreenGameplay::SetReplayPosition(), LunaScreenGameplay::SetReplayRate(), sm_main(), LunaScreenManager::SystemMessage(), ScreenGameplay::ToggleReplayPause(), LunaScreenGameplay::ToggleReplayPause(), and LunaScreenManager::ValidateScreenName().
SystemMessageNoAnimate()
void ScreenManager::SystemMessageNoAnimate (const RString & sMessage)
References MessageManager::Broadcast(), MESSAGEMAN, and Message::SetParam().
Referenced by SMOProtocol::ProcessInput().
ThemeChanged()
void ScreenManager::ThemeChanged ()
References ScreenManagerUtil::g_pSharedBGA, ThemeManager::GetPathS(), LOG, SongManager::ResetGroupColors(), SAFE_DELETE, SONGMAN, THEME, and RageLog::Trace().
Referenced by ScreenOptionsMaster::HandleScreenMessage(), sm_main(), and ThemeManager::SwitchThemeAndLanguage().
Update()
void ScreenManager::Update (float fDeltaTime)
References ASSERT, GameSoundManager::Flush(), ScreenManagerUtil::g_OverlayScreens, ScreenManagerUtil::g_pSharedBGA, ScreenManagerUtil::g_ScreenStack, LOG, SM_GainFocus, SM_Invalid, SOUND, RageLog::Trace(), and Actor::Update().
Referenced by ConcurrentRenderer::RenderThread(), and GameLoop::RunGameLoop().
ZeroNextUpdate()
void ScreenManager::ZeroNextUpdate ()
References DISPLAY, and RageDisplay::ResetStats().
Referenced by ScreenManagerUtil::BeforeDeleteScreen(), ScreenProfileSave::Continue(), ScreenProfileLoad::Continue(), FillProfileStats(), ScreenSelectMusic::HandleMessage(), ScreenGameplay::LoadNextSong(), LunaGameState::LoadProfiles(), LunaGameState::SaveProfiles(), and ScreenRanking::SetPage().
Member Data Documentation
m_bReloadOverlayScreensAfterInput
bool ScreenManager::m_bReloadOverlayScreensAfterInput private
m_bZeroNextUpdate
bool ScreenManager::m_bZeroNextUpdate private
m_input_redirected
std::vector<bool> ScreenManager::m_input_redirected private
m_OnDonePreparingScreen
ScreenMessage ScreenManager::m_OnDonePreparingScreen private
m_PopTopScreen
ScreenMessage ScreenManager::m_PopTopScreen private
m_sDelayedConcurrentPrepare
RString ScreenManager::m_sDelayedConcurrentPrepare private
m_sDelayedScreen
RString ScreenManager::m_sDelayedScreen private
m_soundCancel
RageSound ScreenManager::m_soundCancel private
m_soundCoin
RageSound ScreenManager::m_soundCoin private
The sound played when a coin has been put into the machine.
m_soundInvalid
RageSound ScreenManager::m_soundInvalid private
m_soundScreenshot
RageSound ScreenManager::m_soundScreenshot private
The sound played when a Player wishes to take a picture of their Score.
m_soundStart
RageSound ScreenManager::m_soundStart private
The documentation for this class was generated from the following files:
ScreenManager.h
ScreenManager.cpp