Etterna: RageSoundReader_MP3 Class Reference
RageSoundReader_MP3 Class Reference
#include <RageSoundReader_MP3.h>
Public Member Functions
OpenResult Open (RageFileBasic *pFile)
void Close ()
int GetLength () const
int GetLength_Fast () const
int SetPosition (int iSample)
int Read (float *pBuf, int iFrames)
unsigned GetNumChannels () const
int GetSampleRate () const
int GetNextSourceFrame () const
bool SetProperty (const std::string &sProperty, float fValue)
RageSoundReader_MP3 ()
~RageSoundReader_MP3 ()
RageSoundReader_MP3 (const RageSoundReader_MP3 &)
RageSoundReader_MP3 * Copy () const
Public Member Functions inherited from RageSoundReader_FileReader
float GetStreamToSourceRatio () const override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
bool MADLIB_rewind ()
int SetPosition_toc (int iSample, bool Xing)
int SetPosition_hard (int iSample)
int SetPosition_estimate (int iSample)
int fill_buffer ()
int do_mad_frame_decode (bool headers_only=false)
int resync ()
void synth_output ()
int seek_stream_to_byte (int byte)
bool handle_first_frame ()
int GetLengthInternal (bool fast)
int GetLengthConst (bool fast) const
Private Attributes
int SampleRate
int Channels
bool m_bAccurateSync
madlib_t * mad
Additional Inherited Members
Public Types inherited from RageSoundReader_FileReader
enum OpenResult { OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT = 1, OPEN_FATAL_ERROR = 2 }
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Static Public Member Functions inherited from RageSoundReader_FileReader
static RageSoundReader_FileReader * OpenFile (const RString &filename, RString &error, bool *pPrebuffer=NULL)
Protected Member Functions inherited from RageSoundReader_FileReader
void SetError (const RString &sError) const
Protected Attributes inherited from RageSoundReader_FileReader
HiddenPtr< RageFileBasic > m_pFile
Constructor & Destructor Documentation
RageSoundReader_MP3() [1/2]
RageSoundReader_MP3::RageSoundReader_MP3 ()
References madlib_t::bitrate, madlib_t::first_frame, madlib_t::Frame, madlib_t::has_xing, madlib_t::header_bytes, madlib_t::inbuf_filepos, madlib_t::length, m_bAccurateSync, mad, madlib_t::Stream, madlib_t::Synth, madlib_t::Timer, and madlib_t::timer_accurate.
Referenced by Copy().
~RageSoundReader_MP3()
RageSoundReader_MP3::~RageSoundReader_MP3 ()
References madlib_t::Frame, mad, madlib_t::Stream, and madlib_t::Synth.
RageSoundReader_MP3() [2/2]
RageSoundReader_MP3::RageSoundReader_MP3 (const RageSoundReader_MP3 &)
Member Function Documentation
Close()
void RageSoundReader_MP3::Close ()
Copy()
RageSoundReader_MP3 * RageSoundReader_MP3::Copy () const virtual
Implements RageSoundReader.
References madlib_t::bitrate, Channels, RageFileBasic::Copy(), madlib_t::filesize, madlib_t::framelength, madlib_t::length, m_bAccurateSync, RageSoundReader_FileReader::m_pFile, mad, RageSoundReader_MP3(), SampleRate, and RageFileBasic::Seek().
Referenced by GetLengthConst().
do_mad_frame_decode()
int RageSoundReader_MP3::do_mad_frame_decode (bool headers_only = false) private
References fill_buffer(), fill_frame_index_cache(), madlib_t::first_frame, madlib_t::Frame, get_this_frame_byte(), handle_first_frame(), madlib_t::header_bytes, id3_tag_query(), mad, RageSoundReader_FileReader::SetError(), madlib_t::Stream, madlib_t::Synth, and madlib_t::Timer.
Referenced by GetLengthInternal(), Open(), Read(), SetPosition_estimate(), SetPosition_hard(), and SetPosition_toc().
fill_buffer()
int RageSoundReader_MP3::fill_buffer () private
References RageFileBasic::AtEOF(), RageFileBasic::GetError(), madlib_t::inbuf, madlib_t::inbuf_filepos, RageSoundReader_FileReader::m_pFile, mad, RageFileBasic::Read(), RageSoundReader_FileReader::SetError(), and madlib_t::Stream.
Referenced by do_mad_frame_decode().
GetLength()
int RageSoundReader_MP3::GetLength () const inline virtual
Implements RageSoundReader.
References GetLengthConst().
GetLength_Fast()
int RageSoundReader_MP3::GetLength_Fast () const inline virtual
Reimplemented from RageSoundReader.
References GetLengthConst().
GetLengthConst()
int RageSoundReader_MP3::GetLengthConst (bool fast) const private
References Copy(), and GetLengthInternal().
Referenced by GetLength(), and GetLength_Fast().
GetLengthInternal()
int RageSoundReader_MP3::GetLengthInternal (bool fast) private
References madlib_t::bitrate, do_mad_frame_decode(), madlib_t::filesize, madlib_t::Frame, madlib_t::framelength, madlib_t::has_xing, madlib_t::length, mad, MADLIB_rewind(), seek_stream_to_byte(), RageSoundReader_FileReader::SetError(), and madlib_t::Timer.
Referenced by GetLengthConst().
GetNextSourceFrame()
int RageSoundReader_MP3::GetNextSourceFrame () const virtual
Implements RageSoundReader.
References Channels, madlib_t::Frame, mad, madlib_t::outpos, and madlib_t::Timer.
GetNumChannels()
unsigned RageSoundReader_MP3::GetNumChannels () const inline virtual
Implements RageSoundReader.
References Channels.
Referenced by Read().
GetSampleRate()
int RageSoundReader_MP3::GetSampleRate () const inline virtual
Implements RageSoundReader.
References SampleRate.
handle_first_frame()
bool RageSoundReader_MP3::handle_first_frame () private
References madlib_t::bitrate, xing::bytes, madlib_t::filesize, madlib_t::Frame, xing::frames, get_this_frame_byte(), madlib_t::has_xing, madlib_t::header_bytes, xing::INFO, madlib_t::length, mad, max(), madlib_t::Stream, xing::type, xing::XING, xing_init(), xing_parse(), and madlib_t::xingtag.
Referenced by do_mad_frame_decode().
MADLIB_rewind()
bool RageSoundReader_MP3::MADLIB_rewind () private
References madlib_t::first_frame, madlib_t::Frame, madlib_t::inbuf_filepos, RageSoundReader_FileReader::m_pFile, mad, madlib_t::outleft, madlib_t::outpos, RageFileBasic::Seek(), madlib_t::Stream, madlib_t::Synth, and madlib_t::Timer.
Referenced by GetLengthInternal(), SetPosition(), and SetPosition_hard().
Open()
RageSoundReader_FileReader::OpenResult RageSoundReader_MP3::Open (RageFileBasic * pFile) virtual
Implements RageSoundReader_FileReader.
References ASSERT, madlib_t::bitrate, Channels, do_mad_frame_decode(), f, madlib_t::filesize, madlib_t::Frame, madlib_t::framelength, RageSoundReader_FileReader::GetError(), RageFileBasic::GetFileSize(), madlib_t::header_bytes, madlib_t::length, RageSoundReader_FileReader::m_pFile, mad, RageSoundReader_FileReader::OPEN_OK, RageSoundReader_FileReader::OPEN_UNKNOWN_FILE_FORMAT, madlib_t::outpos, SampleRate, RageSoundReader_FileReader::SetError(), and synth_output().
Read()
int RageSoundReader_MP3::Read (float * pBuf, int iFrames) virtual
Implements RageSoundReader.
References do_mad_frame_decode(), RageSoundReader::END_OF_FILE, GetNumChannels(), mad, min(), madlib_t::outbuf, madlib_t::outleft, madlib_t::outpos, RageSoundReader::RSRERROR, and synth_output().
resync()
int RageSoundReader_MP3::resync () private
seek_stream_to_byte()
int RageSoundReader_MP3::seek_stream_to_byte (int byte) private
References madlib_t::first_frame, madlib_t::Frame, madlib_t::inbuf_filepos, RageSoundReader_FileReader::m_pFile, mad, madlib_t::outleft, madlib_t::outpos, RageFileBasic::Seek(), RageSoundReader_FileReader::SetError(), madlib_t::Stream, madlib_t::Synth, and madlib_t::tocmap.
Referenced by GetLengthInternal(), SetPosition_estimate(), and SetPosition_toc().
SetPosition()
int RageSoundReader_MP3::SetPosition (int iSample) virtual
Implements RageSoundReader.
References madlib_t::has_xing, m_bAccurateSync, mad, MADLIB_rewind(), SetPosition_estimate(), SetPosition_hard(), and SetPosition_toc().
SetPosition_estimate()
int RageSoundReader_MP3::SetPosition_estimate (int iSample) private
References madlib_t::bitrate, do_mad_frame_decode(), madlib_t::Frame, madlib_t::framelength, get_this_frame_byte(), madlib_t::header_bytes, mad, madlib_t::outleft, seek_stream_to_byte(), synth_output(), madlib_t::Timer, and madlib_t::timer_accurate.
Referenced by SetPosition().
SetPosition_hard()
int RageSoundReader_MP3::SetPosition_hard (int iSample) private
References Channels, do_mad_frame_decode(), madlib_t::Frame, madlib_t::framelength, mad, mad_timer_sub(), MADLIB_rewind(), madlib_t::outleft, madlib_t::outpos, SampleRate, synth_output(), and madlib_t::Timer.
Referenced by SetPosition().
SetPosition_toc()
int RageSoundReader_MP3::SetPosition_toc (int iSample, bool Xing) private
References ASSERT, do_mad_frame_decode(), madlib_t::filesize, get_this_frame_byte(), madlib_t::has_xing, madlib_t::length, mad, max(), SampleRate, seek_stream_to_byte(), synth_output(), madlib_t::Timer, madlib_t::timer_accurate, xing::toc, madlib_t::tocmap, and madlib_t::xingtag.
Referenced by SetPosition().
SetProperty()
bool RageSoundReader_MP3::SetProperty (const std::string & sProperty, float fValue)
References m_bAccurateSync, and RageSoundReader::SetProperty().
synth_output()
void RageSoundReader_MP3::synth_output () private
References Channels, madlib_t::Frame, mad, madlib_t::outbuf, madlib_t::outleft, madlib_t::outpos, scale(), and madlib_t::Synth.
Referenced by Open(), Read(), SetPosition_estimate(), SetPosition_hard(), and SetPosition_toc().
Member Data Documentation
Channels
int RageSoundReader_MP3::Channels private
Referenced by Copy(), GetNextSourceFrame(), GetNumChannels(), Open(), SetPosition_hard(), and synth_output().
m_bAccurateSync
bool RageSoundReader_MP3::m_bAccurateSync private
Referenced by Copy(), RageSoundReader_MP3(), SetPosition(), and SetProperty().
mad
madlib_t* RageSoundReader_MP3::mad private
Referenced by Copy(), do_mad_frame_decode(), fill_buffer(), GetLengthInternal(), GetNextSourceFrame(), handle_first_frame(), MADLIB_rewind(), Open(), RageSoundReader_MP3(), Read(), seek_stream_to_byte(), SetPosition(), SetPosition_estimate(), SetPosition_hard(), SetPosition_toc(), synth_output(), and ~RageSoundReader_MP3().
SampleRate
int RageSoundReader_MP3::SampleRate private
Referenced by Copy(), GetSampleRate(), Open(), SetPosition_hard(), and SetPosition_toc().
The documentation for this class was generated from the following files:
RageSoundReader_MP3.h
RageSoundReader_MP3.cpp