Etterna: JsonUtil Namespace Reference
JsonUtil Namespace Reference
Functions
bool LoadFromString (Json::Value &root, const RString &sData, RString &sErrorOut)
bool LoadFromStringShowErrors (Json::Value &root, const RString &sData)
bool LoadFromFileShowErrors (Json::Value &root, const RString &sFile)
bool LoadFromFileShowErrors (Json::Value &root, RageFileBasic &f)
bool WriteFile (const Json::Value &root, const RString &sFile, bool bMinified)
template<class T >
static void SerializeVectorObjects (const vector< T > &v, void fn(const T &, Json::Value &), Json::Value &root)
template<class T >
static void SerializeVectorPointers (const vector< const T *> &v, void fn(const T &, Json::Value &), Json::Value &root)
template<class T >
static void SerializeVectorPointers (const vector< T *> &v, void fn(const T &, Json::Value &), Json::Value &root)
template<class T >
static void SerializeVectorPointers (const vector< const T *> &v, void fn(const T *, Json::Value &), Json::Value &root)
template<typename V , typename T >
static void SerializeArray (const V &v, void fn(const T *, Json::Value &), Json::Value &root)
template<typename V >
static void SerializeArrayValues (const V &v, Json::Value &root)
template<typename V >
static void SerializeArrayObjects (const V &v, Json::Value &root)
template<typename M , typename E , typename F >
static void SerializeStringToObjectMap (const M &m, F fnEnumToString, Json::Value &root)
template<typename M , typename E , typename F >
static void SerializeStringToValueMap (const M &m, F fnToString, Json::Value &root)
template<typename M >
static void SerializeValueToValueMap (const M &m, Json::Value &root)
template<typename V >
static void SerializeObjectToObjectMapAsArray (const V &v, const RString &sKeyName, const RString &sValueName, Json::Value &root)
template<typename V >
static void SerializeObjectToValueMapAsArray (const V &v, const RString &sKeyName, const RString &sValueName, Json::Value &root)
template<class T >
static void SerializeVectorValues (const vector< T > &v, Json::Value &root)
template<class T >
static void DeserializeVectorObjects (vector< T > &v, void fn(T &, const Json::Value &), const Json::Value &root)
template<typename V >
static void DeserializeArrayObjects (V &v, const Json::Value &root)
template<class T >
static void DeserializeVectorPointers (vector< T *> &v, void fn(T &, const Json::Value &), const Json::Value &root)
template<class T >
static void DeserializeVectorPointers (vector< T *> &v, void fn(T *, const Json::Value &), const Json::Value &root)
template<class T , class P >
static void DeserializeVectorPointersParam (vector< T *> &v, void fn(T &, const Json::Value &), const Json::Value &root, const P param)
template<class T >
static void DeserializeArrayValues (vector< T > &v, const Json::Value &root)
template<typename S , typename T >
static void DeserializeArrayValuesIntoSet (S &s, const Json::Value &root)
template<typename T >
static void DeserializeArrayValuesIntoVector (vector< T > &v, const Json::Value &root)
template<typename M >
static void DeserializeValueToValueMap (M &m, const Json::Value &root)
template<typename M , typename E , typename F >
static void DeserializeStringToValueMap (M &m, F fnToValue, const Json::Value &root)
template<typename M , typename E , typename F >
static void DeserializeStringToObjectMap (M &m, F fnToValue, const Json::Value &root)
template<typename K , typename V >
static void DeserializeObjectToObjectMapAsArray (map< K, V > &m, const RString &sKeyName, const RString &sValueName, const Json::Value &root)
template<typename K , typename V >
static void DeserializeObjectToValueMapAsArray (map< K, V > &m, const RString &sKeyName, const RString &sValueName, const Json::Value &root)
template<class T >
static void DeserializeVectorValues (vector< T > &v, const Json::Value &root)
Function Documentation
DeserializeArrayObjects()
template<typename V > static void JsonUtil::DeserializeArrayObjects (V & v, const Json::Value & root) static
References Deserialize().
DeserializeArrayValues()
template<class T > static void JsonUtil::DeserializeArrayValues (vector< T > & v, const Json::Value & root) static
References T.
DeserializeArrayValuesIntoSet()
template<typename S , typename T > static void JsonUtil::DeserializeArrayValuesIntoSet (S & s, const Json::Value & root) static
References T.
DeserializeArrayValuesIntoVector()
template<typename T > static void JsonUtil::DeserializeArrayValuesIntoVector (vector< T > & v, const Json::Value & root) static
References T.
Referenced by Deserialize().
DeserializeObjectToObjectMapAsArray()
template<typename K , typename V > static void JsonUtil::DeserializeObjectToObjectMapAsArray (map< K, V > & m, const RString & sKeyName, const RString & sValueName, const Json::Value & root) static
References ASSERT.
DeserializeObjectToValueMapAsArray()
template<typename K , typename V > static void JsonUtil::DeserializeObjectToValueMapAsArray (map< K, V > & m, const RString & sKeyName, const RString & sValueName, const Json::Value & root) static
DeserializeStringToObjectMap()
template<typename M , typename E , typename F > static void JsonUtil::DeserializeStringToObjectMap (M & m, F fnToValue, const Json::Value & root) static
References Deserialize().
DeserializeStringToValueMap()
template<typename M , typename E , typename F > static void JsonUtil::DeserializeStringToValueMap (M & m, F fnToValue, const Json::Value & root) static
DeserializeValueToValueMap()
template<typename M > static void JsonUtil::DeserializeValueToValueMap (M & m, const Json::Value & root) static
DeserializeVectorObjects()
template<class T > static void JsonUtil::DeserializeVectorObjects (vector< T > & v, void fnT &, const Json::Value &, const Json::Value & root) static
Referenced by Deserialize().
DeserializeVectorPointers() [1/2]
template<class T > static void JsonUtil::DeserializeVectorPointers (vector< T *> & v, void fnT &, const Json::Value &, const Json::Value & root) static
References SAFE_DELETE, and T.
Referenced by Deserialize().
DeserializeVectorPointers() [2/2]
template<class T > static void JsonUtil::DeserializeVectorPointers (vector< T *> & v, void fnT *, const Json::Value &, const Json::Value & root) static
References SAFE_DELETE, and T.
DeserializeVectorPointersParam()
template<class T , class P > static void JsonUtil::DeserializeVectorPointersParam (vector< T *> & v, void fnT &, const Json::Value &, const Json::Value & root, const P param) static
References SAFE_DELETE, and T.
DeserializeVectorValues()
template<class T > static void JsonUtil::DeserializeVectorValues (vector< T > & v, const Json::Value & root) static
LoadFromFileShowErrors() [1/2]
bool JsonUtil::LoadFromFileShowErrors (Json::Value & root, const RString & sFile)
References f, RageFile::GetError(), LOG, RageFile::Open(), RageFile::READ, and RageLog::Warn().
Referenced by XmlFileUtil::LoadFromFileShowErrors(), and NotesLoaderJson::LoadFromJsonFile().
LoadFromFileShowErrors() [2/2]
bool JsonUtil::LoadFromFileShowErrors (Json::Value & root, RageFileBasic & f)
References RageFileBasic::GetFileSize(), LoadFromStringShowErrors(), and RageFileBasic::Read().
LoadFromString()
bool JsonUtil::LoadFromString (Json::Value & root, const RString & sData, RString & sErrorOut)
References LOG, and RageLog::Warn().
Referenced by LoadFromStringShowErrors().
LoadFromStringShowErrors()
bool JsonUtil::LoadFromStringShowErrors (Json::Value & root, const RString & sData)
References LoadFromString().
Referenced by LoadFromFileShowErrors().
SerializeArray()
template<typename V , typename T > static void JsonUtil::SerializeArray (const V & v, void fnconst T *, Json::Value &, Json::Value & root) static
SerializeArrayObjects()
template<typename V > static void JsonUtil::SerializeArrayObjects (const V & v, Json::Value & root) static
SerializeArrayValues()
template<typename V > static void JsonUtil::SerializeArrayValues (const V & v, Json::Value & root) static
Referenced by NotesWriterJson::WriteSong().
SerializeObjectToObjectMapAsArray()
template<typename V > static void JsonUtil::SerializeObjectToObjectMapAsArray (const V & v, const RString & sKeyName, const RString & sValueName, Json::Value & root) static
SerializeObjectToValueMapAsArray()
template<typename V > static void JsonUtil::SerializeObjectToValueMapAsArray (const V & v, const RString & sKeyName, const RString & sValueName, Json::Value & root) static
SerializeStringToObjectMap()
template<typename M , typename E , typename F > static void JsonUtil::SerializeStringToObjectMap (const M & m, F fnEnumToString, Json::Value & root) static
SerializeStringToValueMap()
template<typename M , typename E , typename F > static void JsonUtil::SerializeStringToValueMap (const M & m, F fnToString, Json::Value & root) static
SerializeValueToValueMap()
template<typename M > static void JsonUtil::SerializeValueToValueMap (const M & m, Json::Value & root) static
SerializeVectorObjects()
template<class T > static void JsonUtil::SerializeVectorObjects (const vector< T > & v, void fnconst T &, Json::Value &, Json::Value & root) static
Referenced by NotesWriterJson::WriteSong().
SerializeVectorPointers() [1/3]
template<class T > static void JsonUtil::SerializeVectorPointers (const vector< const T *> & v, void fnconst T &, Json::Value &, Json::Value & root) static
Referenced by Serialize().
SerializeVectorPointers() [2/3]
template<class T > static void JsonUtil::SerializeVectorPointers (const vector< T *> & v, void fnconst T &, Json::Value &, Json::Value & root) static
SerializeVectorPointers() [3/3]
template<class T > static void JsonUtil::SerializeVectorPointers (const vector< const T *> & v, void fnconst T *, Json::Value &, Json::Value & root) static
SerializeVectorValues()
template<class T > static void JsonUtil::SerializeVectorValues (const vector< T > & v, Json::Value & root) static
WriteFile()
bool JsonUtil::WriteFile (const Json::Value & root, const RString & sFile, bool bMinified)
References f, RageFile::GetError(), LOG, RageFile::Open(), RageLog::Warn(), RageFile::WRITE, and RageFile::Write().
Referenced by NotesWriterJson::WriteSong(), and NotesWriterJson::WriteSteps().