Etterna: SpeedSegment Struct Reference
SpeedSegment Struct Reference
Identifies when the arrow scroll changes.
#include <TimingSegments.h>
Public Types
enum BaseUnit { UNIT_BEATS, UNIT_SECONDS }
The type of unit used for segment scaling.
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
SpeedSegment (int iStartRow=ROW_INVALID, float fRatio=1.0f, float fDelay=0.0f, BaseUnit unit=UNIT_BEATS)
SpeedSegment (const SpeedSegment &other)
float GetRatio () const
void SetRatio (float fRatio)
float GetDelay () const
void SetDelay (float fDelay)
BaseUnit GetUnit () const
void SetUnit (BaseUnit unit)
void Scale (int start, int length, int newLength) override
Scales itself.
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const SpeedSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
float m_fRatio
The percentage by which the Player's BPM is multiplied.
float m_fDelay
The number of beats or seconds to wait before applying. A value of 0 means this is immediate.
BaseUnit m_Unit
The mode that this segment uses for the math.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when the arrow scroll changes.
SpeedSegments take a Player's scrolling BPM (Step's BPM * speed mod), and then multiplies it with the percentage value. No matter the player's speed mod, the ratio will be the same. Unlike forced attacks, these cannot be turned off at a set time: reset it by setting the percentage back to 1.
These were inspired by the Pump It Up series.
Member Enumeration Documentation
BaseUnit
enum SpeedSegment::BaseUnit
The type of unit used for segment scaling.
Enumerator
UNIT_BEATS
UNIT_SECONDS
Constructor & Destructor Documentation
SpeedSegment() [1/2]
SpeedSegment::SpeedSegment (int iStartRow = ROW_INVALID, float fRatio = 1.0f, float fDelay = 0.0f, BaseUnit unit = UNIT_BEATS) inline
Referenced by Copy().
SpeedSegment() [2/2]
SpeedSegment::SpeedSegment (const SpeedSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* SpeedSegment::Copy () const inline override virtual
Implements TimingSegment.
References SpeedSegment().
DebugPrint()
void SpeedSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetDelay(), GetRatio(), TimingSegment::GetRow(), GetType(), GetUnit(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetDelay()
float SpeedSegment::GetDelay () const inline
References m_fDelay.
Referenced by DebugPrint(), TimingData::GetDisplayedSpeedPercent(), GetValues(), SongCacheIndex::InsertStepsTimingData(), Scale(), TimingData::SetSpeedModeAtRow(), TimingData::SetSpeedPercentAtRow(), and ToString().
GetEffectType()
SegmentEffectType SpeedSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetRatio()
float SpeedSegment::GetRatio () const inline
References m_fRatio.
Referenced by DebugPrint(), TimingData::GetDisplayedSpeedPercent(), GetValues(), SongCacheIndex::InsertStepsTimingData(), TimingData::SetSpeedModeAtRow(), TimingData::SetSpeedWaitAtRow(), and ToString().
GetType()
TimingSegmentType SpeedSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_SPEED.
Referenced by DebugPrint(), and operator==().
GetUnit()
BaseUnit SpeedSegment::GetUnit () const inline
References m_Unit.
Referenced by DebugPrint(), TimingData::GetDisplayedSpeedPercent(), GetValues(), SongCacheIndex::InsertStepsTimingData(), Scale(), TimingData::SetSpeedPercentAtRow(), TimingData::SetSpeedWaitAtRow(), and ToString().
GetValues()
vector< float > SpeedSegment::GetValues () const override virtual
Reimplemented from TimingSegment.
References GetDelay(), GetRatio(), and GetUnit().
IsNotable()
bool SpeedSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool SpeedSegment::operator== (const SpeedSegment & other) const inline
References COMPARE, COMPARE_FLOAT, m_fDelay, m_fRatio, and m_Unit.
Referenced by operator==().
operator==() [2/2]
bool SpeedSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
Scale()
void SpeedSegment::Scale (int start, int length, int newLength) override virtual
Scales itself.
Parameters
start Starting row
length Length in rows
newLength The new length in rows
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetDelay(), GetUnit(), NoteRowToBeat(), TimingSegment::Scale(), ScalePosition(), and SetDelay().
SetDelay()
void SpeedSegment::SetDelay (float fDelay) inline
References m_fDelay.
Referenced by Scale().
SetRatio()
void SpeedSegment::SetRatio (float fRatio) inline
References m_fRatio.
SetUnit()
void SpeedSegment::SetUnit (BaseUnit unit) inline
References m_Unit.
ToString()
RString SpeedSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetDelay(), GetRatio(), GetUnit(), IntToString(), and ssprintf().
Member Data Documentation
m_fDelay
float SpeedSegment::m_fDelay private
The number of beats or seconds to wait before applying. A value of 0 means this is immediate.
Referenced by GetDelay(), operator==(), and SetDelay().
m_fRatio
float SpeedSegment::m_fRatio private
The percentage by which the Player's BPM is multiplied.
Referenced by GetRatio(), operator==(), and SetRatio().
m_Unit
BaseUnit SpeedSegment::m_Unit private
The mode that this segment uses for the math.
Referenced by GetUnit(), operator==(), and SetUnit().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp