Etterna: LunaAnnouncerManager Class Reference
LunaAnnouncerManager Class Reference
Allow Lua to have access to the AnnouncerManager.
Public Member Functions
LunaAnnouncerManager ()
Public Member Functions inherited from Luna< AnnouncerManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int DoesAnnouncerExist (T *p, lua_State *L)
static int GetAnnouncerNames (T *p, lua_State *L)
static int GetCurrentAnnouncer (T *p, lua_State *L)
static int SetCurrentAnnouncer (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< AnnouncerManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< AnnouncerManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< AnnouncerManager >
using T = AnnouncerManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< AnnouncerManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the AnnouncerManager.
Constructor & Destructor Documentation
LunaAnnouncerManager()
LunaAnnouncerManager::LunaAnnouncerManager () inline
References ADD_METHOD, DoesAnnouncerExist(), GetAnnouncerNames(), GetCurrentAnnouncer(), and SetCurrentAnnouncer().
Member Function Documentation
DoesAnnouncerExist()
static int LunaAnnouncerManager::DoesAnnouncerExist (T * p, lua_State * L) inline static
References AnnouncerManager::DoesAnnouncerExist(), and SArg.
Referenced by LunaAnnouncerManager().
GetAnnouncerNames()
static int LunaAnnouncerManager::GetAnnouncerNames (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and AnnouncerManager::GetAnnouncerNames().
Referenced by LunaAnnouncerManager().
GetCurrentAnnouncer()
static int LunaAnnouncerManager::GetCurrentAnnouncer (T * p, lua_State * L) inline static
References AnnouncerManager::GetCurAnnouncerName().
Referenced by LunaAnnouncerManager().
SetCurrentAnnouncer()
static int LunaAnnouncerManager::SetCurrentAnnouncer (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, AnnouncerManager::DoesAnnouncerExist(), SArg, and AnnouncerManager::SwitchAnnouncer().
Referenced by LunaAnnouncerManager().
The documentation for this class was generated from the following file:
AnnouncerManager.cpp