Etterna: ScreenMapControllers::ActionRow Struct Reference
ScreenMapControllers::ActionRow Struct Reference
Public Member Functions
void Load (RString const &scr_name, RString const &name, ScreenMapControllers::action_fun_t action, ActorFrame *line, ActorScroller *scroller)
Public Attributes
RString m_name
AutoActor m_actor
action_fun_t m_action
Member Function Documentation
Load()
void ScreenMapControllers::ActionRow::Load (RString const & scr_name, RString const & name, ScreenMapControllers::action_fun_t action, ActorFrame * line, ActorScroller * scroller)
References ActorFrame::AddChild(), ThemeManager::GetPathG(), AutoActor::Load(), ActorUtil::LoadAllCommands(), m_action, m_actor, StdString::CStdStr< CT >::MakeLower(), Actor::SetName(), and THEME.
Member Data Documentation
m_action
action_fun_t ScreenMapControllers::ActionRow::m_action
Referenced by Load().
m_actor
AutoActor ScreenMapControllers::ActionRow::m_actor
Referenced by Load().
m_name
RString ScreenMapControllers::ActionRow::m_name
The documentation for this struct was generated from the following files:
ScreenMapControllers.h
ScreenMapControllers.cpp