Etterna: ScoreKeeperNormal.cpp File Reference
ScoreKeeperNormal.cpp File Reference
#include "ScoreKeeperNormal.h"
#include "Game.h"
#include "GamePreferences.h"
#include "GameState.h"
#include "NetworkSyncManager.h"
#include "NoteData.h"
#include "NoteDataUtil.h"
#include "NoteDataWithScoring.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "ProfileManager.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "Song.h"
#include "SongManager.h"
#include "StageStats.h"
#include "Steps.h"
#include "Style.h"
#include "TimingData.h"
#include "global.h"
Functions
static RString PercentScoreWeightName (size_t i)
static RString GradeWeightName (size_t i)
static int GetScore (int p, int Z, int64_t S, int n)
Variables
static ThemeMetric1D< int > g_iPercentScoreWeight ("ScoreKeeperNormal", PercentScoreWeightName, NUM_ScoreEvent)
static ThemeMetric1D< int > g_iGradeWeight ("ScoreKeeperNormal", GradeWeightName, NUM_ScoreEvent)
ThemeMetric< bool > PENALIZE_TAP_SCORE_NONE
Function Documentation
GetScore()
static int GetScore (int p, int Z, int64_t S, int n) static
Referenced by ScoreKeeperNormal::AddScoreInternal().
GradeWeightName()
static RString GradeWeightName (size_t i) static
References ScoreEventToString().
PercentScoreWeightName()
static RString PercentScoreWeightName (size_t i) static
References ScoreEventToString().
Variable Documentation
g_iGradeWeight
ThemeMetric1D<int> g_iGradeWeight("ScoreKeeperNormal", GradeWeightName, NUM_ScoreEvent) static
Referenced by ScoreKeeperNormal::GetPossibleGradePoints(), ScoreKeeperNormal::HoldNoteScoreToGradePoints(), and ScoreKeeperNormal::TapNoteScoreToGradePoints().
g_iPercentScoreWeight
ThemeMetric1D<int> g_iPercentScoreWeight("ScoreKeeperNormal", PercentScoreWeightName, NUM_ScoreEvent) static
Referenced by ScoreKeeperNormal::GetPossibleDancePoints(), ScoreKeeperNormal::HoldNoteScoreToDancePoints(), and ScoreKeeperNormal::TapNoteScoreToDancePoints().
PENALIZE_TAP_SCORE_NONE
ThemeMetric<bool> PENALIZE_TAP_SCORE_NONE
Referenced by Player::DoTapScoreNone(), and Player::ScoreAllActiveHoldsLetGo().