Etterna: BMSChartReader Class Reference
BMSChartReader Class Reference
Public Member Functions
BMSChartReader (BMSChart *chart, Steps *steps, BMSSong *song)
bool Read ()
Steps * GetSteps ()
Public Attributes
BMSChartInfo info
int player
float initialBPM
Private Member Functions
void ReadHeaders ()
void CalculateStepsType ()
bool ReadNoteData ()
StepsType DetermineStepsType ()
int GetKeysound (const BMSObject &obj)
Private Attributes
BMSChart * in
Steps * out
BMSSong * song
int lntype
RString lnobj
int nonEmptyTracksCount
map< int, bool > nonEmptyTracks
map< RString, int > mapValueToKeysoundIndex
Constructor & Destructor Documentation
BMSChartReader()
BMSChartReader::BMSChartReader (BMSChart * chart, Steps * steps, BMSSong * song)
References in, nonEmptyTracks, out, BMSChart::referencedTracks, and song.
Member Function Documentation
CalculateStepsType()
void BMSChartReader::CalculateStepsType () private
References DetermineStepsType(), GAMEMAN, GameManager::GetStepsTypeInfo(), Steps::m_StepsType, Steps::m_StepsTypeStr, nonEmptyTracks, nonEmptyTracksCount, out, StepsType_Invalid, and StepsTypeInfo::szName.
Referenced by Read().
DetermineStepsType()
StepsType BMSChartReader::DetermineStepsType () private
References BMS_RAW_P1_KEY1, BMS_RAW_P1_KEY2, BMS_RAW_P1_KEY3, BMS_RAW_P1_KEY4, BMS_RAW_P1_KEY5, BMS_RAW_P1_KEY6, BMS_RAW_P1_KEY7, BMS_RAW_P1_TURN, BMS_RAW_P2_KEY2, in, LOG, nonEmptyTracks, nonEmptyTracksCount, BMSChart::path, player, StepsType_beat_double5, StepsType_beat_double7, StepsType_beat_single5, StepsType_beat_single7, StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_Invalid, StepsType_kb7_single, StepsType_popn_five, StepsType_popn_nine, and RageLog::UserLog().
Referenced by CalculateStepsType().
GetKeysound()
int BMSChartReader::GetKeysound (const BMSObject & obj) private
References BMSSong::AllocateKeysound(), BMSChart::headers, in, mapValueToKeysoundIndex, BMSChart::path, song, and BMSObject::value.
Referenced by ReadNoteData().
GetSteps()
Steps * BMSChartReader::GetSteps ()
References out.
Read()
bool BMSChartReader::Read ()
References CalculateStepsType(), ReadHeaders(), and ReadNoteData().
Referenced by BMSSongLoader::Load(), and BMSLoader::LoadNoteDataFromSimfile().
ReadHeaders()
void BMSChartReader::ReadHeaders () private
References BMSChartInfo::artist, BMSChartInfo::backgroundFile, BMSChartInfo::bannerFile, BMSChartInfo::genre, BMSChart::headers, in, info, initialBPM, lnobj, lntype, TimingData::m_fBeat0OffsetInSeconds, Steps::m_Timing, StdString::CStdStr< CT >::MakeLower(), BMSChartInfo::musicFile, NUM_Difficulty, out, player, BMSChartInfo::previewFile, BMSChartInfo::previewStart, Steps::SetCredit(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetMusicFile(), BMSChartInfo::stageFile, StringToFloat(), StringToInt(), and BMSChartInfo::title.
Referenced by Read().
ReadNoteData()
bool BMSChartReader::ReadNoteData () private
References NoteData::AddHoldNote(), ASSERT_M, BMSChartInfo::backgroundChanges, BeatToNoteRow(), BMS_RAW_P1_KEY1, BMS_RAW_P1_KEY2, BMS_RAW_P1_KEY3, BMS_RAW_P1_KEY4, BMS_RAW_P1_KEY5, BMS_RAW_P1_KEY6, BMS_RAW_P1_KEY7, BMS_RAW_P1_TURN, BMS_RAW_P2_KEY1, BMS_RAW_P2_KEY2, BMS_RAW_P2_KEY3, BMS_RAW_P2_KEY4, BMS_RAW_P2_KEY5, BMS_RAW_P2_KEY6, BMS_RAW_P2_KEY7, BMS_RAW_P2_TURN, BMSObject::channel, bmFrac::den, BMSObject::flag, GAMEMAN, BMSSong::GetBackground(), GetKeysound(), GameManager::GetStepsTypeInfo(), NoteData::GetTapNote(), BMSChart::headers, hold, TapNote::iKeysoundIndex, in, BMSAutoKeysound::index, info, initialBPM, StepsTypeInfo::iNumTracks, NoteData::IsHoldNoteAtRow(), lnobj, LOG, TimingData::m_fBeat0OffsetInSeconds, Steps::m_StepsType, Steps::m_Timing, BMSObject::measure, BMSChart::measures, nonEmptyTracks, bmFrac::num, BMSChart::objects, out, BMSChart::path, BMSObject::position, BMSAutoKeysound::row, TimingData::SetBPMAtRow(), Steps::SetNoteData(), NoteData::SetNumTracks(), Steps::SetSavedToDisk(), TimingData::SetStopAtRow(), NoteData::SetTapNote(), TimingData::SetTimeSignatureAtRow(), song, ssprintf(), StepsType_beat_double5, StepsType_beat_double7, StepsType_beat_single5, StepsType_beat_single7, StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, StepsType_Invalid, StepsType_kb7_single, StepsType_popn_five, StepsType_popn_nine, StringToFloat(), TapNote::subType, TAP_EMPTY, TAP_ORIGINAL_AUTO_KEYSOUND, TAP_ORIGINAL_TAP, TapNoteSubType_Hold, TapNoteType_HoldHead, Steps::TidyUpData(), TimingData::TidyUpData(), toFraction(), TapNote::type, RageLog::UserLog(), and BMSObject::value.
Referenced by Read().
Member Data Documentation
in
BMSChart* BMSChartReader::in private
Referenced by BMSChartReader(), DetermineStepsType(), GetKeysound(), ReadHeaders(), and ReadNoteData().
info
BMSChartInfo BMSChartReader::info
Referenced by BMSSongLoader::Load(), ReadHeaders(), and ReadNoteData().
initialBPM
float BMSChartReader::initialBPM
Referenced by ReadHeaders(), and ReadNoteData().
lnobj
RString BMSChartReader::lnobj private
Referenced by ReadHeaders(), and ReadNoteData().
lntype
int BMSChartReader::lntype private
Referenced by ReadHeaders().
mapValueToKeysoundIndex
map<RString, int> BMSChartReader::mapValueToKeysoundIndex private
Referenced by GetKeysound().
nonEmptyTracks
map<int, bool> BMSChartReader::nonEmptyTracks private
Referenced by BMSChartReader(), CalculateStepsType(), DetermineStepsType(), and ReadNoteData().
nonEmptyTracksCount
int BMSChartReader::nonEmptyTracksCount private
Referenced by CalculateStepsType(), and DetermineStepsType().
out
Steps* BMSChartReader::out private
Referenced by BMSChartReader(), CalculateStepsType(), GetSteps(), ReadHeaders(), and ReadNoteData().
player
int BMSChartReader::player
Referenced by DetermineStepsType(), and ReadHeaders().
song
BMSSong* BMSChartReader::song private
Referenced by BMSChartReader(), GetKeysound(), and ReadNoteData().
The documentation for this class was generated from the following file:
NotesLoaderBMS.cpp