Etterna: Sprite Class Reference
Sprite Class Reference
A bitmap Actor that animates and moves around.
#include <Sprite.h>
Classes
struct State
The Sprite's present state.
Public Member Functions
Sprite ()
Sprite (const Sprite &cpy)
~Sprite () override
void InitState () override
void LoadFromNode (const XNode *pNode) override
Sprite * Copy () const override
bool EarlyAbortDraw () const override
Allow the Actor to be aborted early.
void DrawPrimitives () override
Draw the primitives of the Actor.
void Update (float fDeltaTime) override
void UpdateAnimationState ()
virtual void Load (const RageTextureID &ID)
void SetTexture (RageTexture *pTexture)
void UnloadTexture ()
RageTexture * GetTexture ()
void EnableAnimation (bool bEnable) override
int GetNumStates () const override
void SetState (int iNewState) override
int GetState ()
float GetAnimationLengthSeconds () const override
virtual void RecalcAnimationLengthSeconds ()
void SetSecondsIntoAnimation (float fSeconds) override
void SetStateProperties (const vector< State > &new_states)
RString GetTexturePath () const
void SetCustomTextureRect (const RectF &new_texcoord_frect)
void SetCustomTextureCoords (float fTexCoords[8])
void SetCustomImageRect (RectF rectImageCoords)
void SetCustomImageCoords (float fImageCoords[8])
void SetCustomPosCoords (float fPosCoords[8])
const RectF * GetCurrentTextureCoordRect () const
const RectF * GetTextureCoordRectForState (int iState) const
void StopUsingCustomCoords ()
void StopUsingCustomPosCoords ()
void GetActiveTextureCoords (float fTexCoordsOut[8]) const
void StretchTexCoords (float fX, float fY)
void AddImageCoords (float fX, float fY)
void SetEffectMode (EffectMode em)
void LoadFromCached (const RString &sDir, const RString &sPath)
void SetTexCoordVelocity (float fVelX, float fVelY)
void ScaleToClipped (float fWidth, float fHeight)
Scale the Sprite while maintaining the aspect ratio.
void CropTo (float fWidth, float fHeight)
void PushSelf (lua_State *L) override
void SetAllStateDelays (float fDelay)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void BeginDraw ()
Start the drawing and push the transform on the world matrix stack.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
virtual void EndDraw ()
Pop the transform from the world matrix stack.
bool IsFirstUpdate () const
virtual void UpdateInternal (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
virtual void FinishTweening ()
virtual void HurryTweening (float factor)
virtual float GetTweenTimeLeft () const
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
virtual void SetZTestMode (ZTestMode mode)
virtual void SetZWrite (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
virtual void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void HandleMessage (const Message &msg) override
virtual void SetUpdateRate (float)
virtual float GetUpdateRate ()
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Static Public Member Functions
static Sprite * NewBlankSprite ()
static RageTextureID SongBGTexture (RageTextureID ID)
static RageTextureID SongBannerTexture (RageTextureID ID)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes
bool m_DecodeMovie
bool m_use_effect_clock_for_texcoords
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions
void LoadFromTexture (const RageTextureID &ID)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Private Member Functions
void LoadStatesFromTexture ()
void DrawTexture (const TweenState *state)
Private Attributes
RageTexture * m_pTexture
vector< State > m_States
int m_iCurState
float m_fSecsIntoState
The number of seconds that have elapsed since we switched to this frame.
float m_animation_length_seconds
EffectMode m_EffectMode
bool m_bUsingCustomTexCoords
bool m_bUsingCustomPosCoords
bool m_bSkipNextUpdate
float m_CustomTexCoords [8]
Set up the coordinates for the texture.
float m_CustomPosCoords [8]
Set up the coordinates for the position.
float m_fRememberedClipWidth
float m_fRememberedClipHeight
float m_fTexCoordVelocityX
float m_fTexCoordVelocityY
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A bitmap Actor that animates and moves around.
Constructor & Destructor Documentation
Sprite() [1/2]
Sprite::Sprite ()
References EffectMode_Normal, m_animation_length_seconds, m_bSkipNextUpdate, m_bUsingCustomPosCoords, m_bUsingCustomTexCoords, m_DecodeMovie, m_EffectMode, m_fRememberedClipHeight, m_fRememberedClipWidth, m_fSecsIntoState, m_fTexCoordVelocityX, m_fTexCoordVelocityY, m_iCurState, m_pTexture, and m_use_effect_clock_for_texcoords.
Referenced by NewBlankSprite().
Sprite() [2/2]
Sprite::Sprite (const Sprite & cpy)
References RageTextureManager::CopyTexture(), CPY, m_animation_length_seconds, m_bSkipNextUpdate, m_bUsingCustomPosCoords, m_bUsingCustomTexCoords, m_CustomPosCoords, m_CustomTexCoords, m_DecodeMovie, m_EffectMode, m_fRememberedClipHeight, m_fRememberedClipWidth, m_fSecsIntoState, m_fTexCoordVelocityX, m_fTexCoordVelocityY, m_iCurState, m_pTexture, m_States, m_use_effect_clock_for_texcoords, and TEXTUREMAN.
~Sprite()
Sprite::~Sprite () override
References UnloadTexture().
Member Function Documentation
AddImageCoords()
void Sprite::AddImageCoords (float fX, float fY)
References GetActiveTextureCoords(), RageTexture::GetTextureHeight(), RageTexture::GetTextureWidth(), m_pTexture, and SetCustomTextureCoords().
Referenced by LunaSprite::addimagecoords().
Copy()
Sprite* Sprite::Copy () const override virtual
Reimplemented from Actor.
CropTo()
void Sprite::CropTo (float fWidth, float fHeight)
References Actor::GetX(), Actor::GetY(), Actor::GetZoomedHeight(), Actor::GetZoomedWidth(), m_fRememberedClipHeight, m_fRememberedClipWidth, m_pTexture, Actor::m_size, Actor::ScaleToCover(), SetCustomImageRect(), Actor::SetXY(), Actor::SetZoom(), and StopUsingCustomCoords().
Referenced by LunaSprite::CropTo().
DrawPrimitives()
void Sprite::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from Actor.
References RageColor::a, StepMania::Rect< T >::bottom, Actor::TweenState::crop, Actor::TweenState::diffuse, DrawTexture(), Actor::TweenState::fade, StepMania::Rect< T >::left, Actor::m_pTempState, StepMania::Rect< T >::right, SCALE, and StepMania::Rect< T >::top.
DrawTexture()
void Sprite::DrawTexture (const TweenState * state) private
References RageColor::a, StepMania::Rect< T >::bottom, RageSpriteVertex::c, CLAMP(), Actor::TweenState::crop, Actor::TweenState::diffuse, DISPLAY, RageDisplay::DrawQuad(), EffectMode_Normal, f, GetActiveTextureCoords(), RageTexture::GetTexHandle(), Actor::TweenState::glow, IF_CROP_POS, NoteDataUtil::left, StepMania::Rect< T >::left, m_bUsingCustomPosCoords, m_CustomPosCoords, m_EffectMode, Actor::m_fShadowLengthX, Actor::m_fShadowLengthY, m_pTexture, Actor::m_ShadowColor, Actor::m_size, RageSpriteVertex::p, RageDisplay::PopMatrix(), RageDisplay::PushMatrix(), NoteDataUtil::right, StepMania::Rect< T >::right, SCALE, RageDisplay::SetEffectMode(), Actor::SetGlobalRenderStates(), RageDisplay::SetTexture(), RageDisplay::SetTextureMode(), Actor::SetTextureRenderStates(), RageSpriteVertex::t, TextureMode_Glow, TextureMode_Modulate, TextureUnit_1, StepMania::Rect< T >::top, RageDisplay::TranslateWorld(), RageVector2::x, RageVector3::x, RageVector2::y, and RageVector3::y.
Referenced by DrawPrimitives().
EarlyAbortDraw()
bool Sprite::EarlyAbortDraw () const override virtual
Allow the Actor to be aborted early.
Subclasses may wish to overwrite this to allow for aborted actors.
Returns
false, as by default Actors shouldn't be aborted on drawing.
Reimplemented from Actor.
Reimplemented in WheelNotifyIcon.
References m_pTexture.
Referenced by DifficultyIcon::EarlyAbortDraw(), and WheelNotifyIcon::EarlyAbortDraw().
EnableAnimation()
void Sprite::EnableAnimation (bool bEnable) override virtual
Reimplemented from Actor.
References Actor::EnableAnimation(), Actor::m_bIsAnimating, and m_bSkipNextUpdate.
GetActiveTextureCoords()
void Sprite::GetActiveTextureCoords (float fTexCoordsOut[8]) const
References GetCurrentTextureCoordRect(), m_bUsingCustomTexCoords, m_CustomTexCoords, and TexCoordArrayFromRect().
Referenced by AddImageCoords(), DrawTexture(), StretchTexCoords(), and Update().
GetAnimationLengthSeconds()
float Sprite::GetAnimationLengthSeconds () const inline override virtual
Reimplemented from Actor.
References m_animation_length_seconds.
Referenced by LunaSprite::GetAnimationLengthSeconds(), and Update().
GetCurrentTextureCoordRect()
const RectF * Sprite::GetCurrentTextureCoordRect () const
References GetTextureCoordRectForState(), and m_iCurState.
Referenced by NoteDisplay::DrawHoldPart(), GetActiveTextureCoords(), and Banner::Update().
GetNumStates()
int Sprite::GetNumStates () const override virtual
Reimplemented from Actor.
References m_States.
Referenced by LunaSprite::GetNumStates(), DifficultyIcon::Load(), and DifficultyIcon::SetFromDifficulty().
GetState()
int Sprite::GetState () inline
References m_iCurState.
Referenced by LunaSprite::GetState().
GetTexture()
RageTexture* Sprite::GetTexture () inline
References m_pTexture.
Referenced by LunaSprite::GetTexture(), FadingBanner::Load(), and LunaSprite::SetStateProperties().
GetTextureCoordRectForState()
const RectF * Sprite::GetTextureCoordRectForState (int iState) const
References ASSERT_M, m_States, and ssprintf().
Referenced by GetCurrentTextureCoordRect().
GetTexturePath()
RString Sprite::GetTexturePath () const
References RageTextureID::filename, RageTexture::GetID(), and m_pTexture.
InitState()
void Sprite::InitState () override virtual
Reimplemented from Actor.
References Actor::InitState(), m_bSkipNextUpdate, m_fSecsIntoState, and m_iCurState.
Load()
void Sprite::Load (const RageTextureID & ID) virtual
Reimplemented in Banner, and DifficultyIcon.
References RageTextureID::filename, LoadFromTexture(), and LoadStatesFromTexture().
Referenced by ScreenSelectMusic::CheckBackgroundRequests(), GrooveRadar::GrooveRadar(), ScreenPackages::Init(), BeginnerHelper::Init(), ScreenSelectMusic::Init(), ScreenEvaluation::Init(), DifficultyIcon::Load(), Banner::Load(), StreamDisplay::Load(), LunaSprite::Load(), LunaSprite::LoadBackground(), LunaSprite::LoadBanner(), BGAnimationLayer::LoadFromAniLayerFile(), LoadFromCached(), NoteField::NoteField(), Quad::Quad(), ScoreDisplayOni::ScoreDisplayOni(), SnapDisplay::SnapDisplay(), and WheelNotifyIcon::WheelNotifyIcon().
LoadFromCached()
void Sprite::LoadFromCached (const RString & sDir, const RString & sPath)
References ThemeManager::GetPathG(), IMAGECACHE, IsAFile(), RageTextureManager::IsTextureRegistered(), Load(), ImageCache::LoadCachedImage(), TEXTUREMAN, and THEME.
Referenced by LunaSprite::LoadFromCached().
LoadFromNode()
void Sprite::LoadFromNode (const XNode * pNode) override virtual
Reimplemented from Actor.
References StepMania::Rect< T >::bottom, f, Sprite::State::fDelay, ActorUtil::GetAttrPath(), XNode::GetAttrValue(), XNode::GetChild(), RageTexture::GetNumFrames(), RageTexture::GetSourceToTexCoordsRatioX(), RageTexture::GetSourceToTexCoordsRatioY(), RageTexture::GetTextureCoordRect(), ActorUtil::GetWhere(), RageTextureManager::IsTextureRegistered(), StepMania::Rect< T >::left, Actor::LoadFromNode(), LoadFromTexture(), LoadStatesFromTexture(), m_pTexture, Actor::m_size, m_States, RecalcAnimationLengthSeconds(), Sprite::State::rect, LuaHelpers::ReportScriptErrorFmt(), StepMania::Rect< T >::right, SCALE, ssprintf(), TEXTUREMAN, StepMania::Rect< T >::top, RageVector2::x, and RageVector2::y.
LoadFromTexture()
void Sprite::LoadFromTexture (const RageTextureID & ID) protected
References RageTexture::GetID(), RageTextureManager::LoadTexture(), m_pTexture, SetTexture(), and TEXTUREMAN.
Referenced by Load(), and LoadFromNode().
LoadStatesFromTexture()
void Sprite::LoadStatesFromTexture () private
References Sprite::State::fDelay, RageTexture::GetNumFrames(), RageTexture::GetTextureCoordRect(), m_pTexture, m_States, RecalcAnimationLengthSeconds(), and Sprite::State::rect.
Referenced by Load(), LoadFromNode(), and SetTexture().
NewBlankSprite()
Sprite * Sprite::NewBlankSprite () static
References RageTextureManager::GetDefaultTextureID(), Sprite(), and TEXTUREMAN.
Referenced by NoteSkinManager::LoadActor().
PushSelf()
void Sprite::PushSelf (lua_State * L) override virtual
Reimplemented from Actor.
RecalcAnimationLengthSeconds()
void Sprite::RecalcAnimationLengthSeconds () virtual
References FOREACH_CONST, m_animation_length_seconds, and m_States.
Referenced by LoadFromNode(), LoadStatesFromTexture(), SetAllStateDelays(), and SetStateProperties().
ScaleToClipped()
void Sprite::ScaleToClipped (float fWidth, float fHeight)
Scale the Sprite while maintaining the aspect ratio.
It has to fit within and become clipped to the given parameters.
Parameters
fWidth the new width.
fHeight the new height.
References Actor::GetX(), Actor::GetY(), Actor::GetZoomedHeight(), Actor::GetZoomedWidth(), m_fRememberedClipHeight, m_fRememberedClipWidth, m_pTexture, Actor::m_size, max(), Actor::ScaleToCover(), SetCustomImageRect(), Actor::SetXY(), Actor::SetZoom(), and StopUsingCustomCoords().
Referenced by ScreenEvaluation::Init(), LunaBanner::scaletoclipped(), LunaBanner::ScaleToClipped(), LunaSprite::scaletoclipped(), and SetTexture().
SetAllStateDelays()
void Sprite::SetAllStateDelays (float fDelay)
References m_States, and RecalcAnimationLengthSeconds().
Referenced by LunaSprite::SetAllStateDelays().
SetCustomImageCoords()
void Sprite::SetCustomImageCoords (float fImageCoords[8])
References RageTexture::GetImageHeight(), RageTexture::GetImageWidth(), RageTexture::GetTextureHeight(), RageTexture::GetTextureWidth(), m_pTexture, and SetCustomTextureCoords().
SetCustomImageRect()
void Sprite::SetCustomImageRect (RectF rectImageCoords)
References StepMania::Rect< T >::bottom, RageTexture::GetImageHeight(), RageTexture::GetImageWidth(), RageTexture::GetTextureHeight(), RageTexture::GetTextureWidth(), StepMania::Rect< T >::left, m_pTexture, StepMania::Rect< T >::right, SetCustomTextureRect(), and StepMania::Rect< T >::top.
Referenced by CropTo(), ScaleToClipped(), and LunaSprite::SetCustomImageRect().
SetCustomPosCoords()
void Sprite::SetCustomPosCoords (float fPosCoords[8])
References m_bUsingCustomPosCoords, and m_CustomPosCoords.
Referenced by LunaSprite::SetCustomPosCoords().
SetCustomTextureCoords()
void Sprite::SetCustomTextureCoords (float fTexCoords[8])
References Actor::m_bTextureWrapping, m_bUsingCustomTexCoords, and m_CustomTexCoords.
Referenced by AddImageCoords(), SetCustomImageCoords(), StretchTexCoords(), Banner::Update(), and Update().
SetCustomTextureRect()
void Sprite::SetCustomTextureRect (const RectF & new_texcoord_frect)
References Actor::m_bTextureWrapping, m_bUsingCustomTexCoords, m_CustomTexCoords, and TexCoordArrayFromRect().
Referenced by LunaSprite::customtexturerect(), NoteField::DrawBeatBar(), and SetCustomImageRect().
SetEffectMode()
void Sprite::SetEffectMode (EffectMode em) inline
References m_EffectMode.
Referenced by MovieTexture_Generic::CreateTexture(), and LunaSprite::SetEffectMode().
SetSecondsIntoAnimation()
void Sprite::SetSecondsIntoAnimation (float fSeconds) override virtual
Reimplemented from Actor.
References m_fSecsIntoState, m_pTexture, RageTexture::SetPosition(), SetState(), and UpdateAnimationState().
Referenced by FadingBanner::Load(), and LunaSprite::SetSecondsIntoAnimation().
SetState()
void Sprite::SetState (int iNewState) override virtual
Reimplemented from Actor.
References CLAMP(), RageTextureID::filename, RageTexture::GetID(), m_fSecsIntoState, m_iCurState, m_pTexture, Actor::m_sName, m_States, LuaHelpers::ReportScriptError(), and ssprintf().
Referenced by NoteField::DrawBeatBar(), GrooveRadar::GrooveRadar(), ScreenEvaluation::Init(), DifficultyIcon::SetFromDifficulty(), SetSecondsIntoAnimation(), LunaSprite::setstate(), SetStateProperties(), UnloadTexture(), and WheelNotifyIcon::Update().
SetStateProperties()
void Sprite::SetStateProperties (const vector< State > & new_states) inline
References m_States, RecalcAnimationLengthSeconds(), and SetState().
Referenced by LunaSprite::SetStateProperties().
SetTexCoordVelocity()
void Sprite::SetTexCoordVelocity (float fVelX, float fVelY)
References m_fTexCoordVelocityX, and m_fTexCoordVelocityY.
Referenced by LunaSprite::texcoordvelocity().
SetTexture()
void Sprite::SetTexture (RageTexture * pTexture)
References ASSERT, RageTexture::GetSourceFrameHeight(), RageTexture::GetSourceFrameWidth(), RageTexture::GetTextureHeight(), RageTexture::GetTextureWidth(), LoadStatesFromTexture(), m_fRememberedClipHeight, m_fRememberedClipWidth, m_pTexture, Actor::m_size, m_States, ScaleToClipped(), UnloadTexture(), RageVector2::x, and RageVector2::y.
Referenced by MovieTexture_Generic::CreateTexture(), LoadFromTexture(), and LunaSprite::SetTexture().
SongBannerTexture()
RageTextureID Sprite::SongBannerTexture (RageTextureID ID) static
References RageTextureID::bHotPinkColorKey, RageTextureID::iColorDepth, and RageTextureID::TEX_VOLATILE.
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::CheckBackgroundRequests(), ScreenSelectMusic::Init(), Banner::Load(), LunaSprite::LoadBanner(), ImageCache::LoadCachedImage(), Banner::LoadFromCachedBanner(), FadingBanner::LoadFromCachedBanner(), and SongManager::PreloadSongImages().
SongBGTexture()
RageTextureID Sprite::SongBGTexture (RageTextureID ID) static
References RageTextureID::bDither, RageTextureID::bMipMaps, RageTextureID::iAlphaBits, and RageTextureID::TEX_VOLATILE.
Referenced by LunaSprite::LoadBackground(), and BGAnimationLayer::LoadFromAniLayerFile().
StopUsingCustomCoords()
void Sprite::StopUsingCustomCoords ()
References m_bUsingCustomTexCoords.
Referenced by CropTo(), and ScaleToClipped().
StopUsingCustomPosCoords()
void Sprite::StopUsingCustomPosCoords ()
References m_bUsingCustomPosCoords.
Referenced by LunaSprite::StopUsingCustomPosCoords().
StretchTexCoords()
void Sprite::StretchTexCoords (float fX, float fY)
References GetActiveTextureCoords(), and SetCustomTextureCoords().
Referenced by LunaSprite::stretchtexcoords(), and BGAnimationLayer::UpdateInternal().
UnloadTexture()
void Sprite::UnloadTexture ()
References m_pTexture, SetState(), TEXTUREMAN, and RageTextureManager::UnloadTexture().
Referenced by ScreenSelectMusic::AfterMusicChange(), MovieTexture_Generic::CreateTexture(), FadingBanner::Load(), LunaSprite::Load(), SetTexture(), and ~Sprite().
Update()
void Sprite::Update (float fDeltaTime) override virtual
Reimplemented from Actor.
Reimplemented in WheelNotifyIcon.
References RageTexture::DecodeSeconds(), GetActiveTextureCoords(), GetAnimationLengthSeconds(), Actor::GetEffectDeltaTime(), Actor::m_bIsAnimating, m_bSkipNextUpdate, Actor::m_bTextureWrapping, m_DecodeMovie, m_fSecsIntoState, m_fTexCoordVelocityX, m_fTexCoordVelocityY, m_pTexture, m_use_effect_clock_for_texcoords, max(), SetCustomTextureCoords(), Actor::Update(), UpdateAnimationState(), and wrap().
Referenced by NoteField::Update(), Banner::Update(), BeginnerHelper::Update(), and WheelNotifyIcon::Update().
UpdateAnimationState()
void Sprite::UpdateAnimationState ()
References m_fSecsIntoState, m_iCurState, m_States, min_state_delay, and Actor::PlayCommand().
Referenced by SetSecondsIntoAnimation(), and Update().
Member Data Documentation
m_animation_length_seconds
float Sprite::m_animation_length_seconds private
Referenced by GetAnimationLengthSeconds(), RecalcAnimationLengthSeconds(), and Sprite().
m_bSkipNextUpdate
bool Sprite::m_bSkipNextUpdate private
Referenced by EnableAnimation(), InitState(), Sprite(), and Update().
m_bUsingCustomPosCoords
bool Sprite::m_bUsingCustomPosCoords private
Referenced by DrawTexture(), SetCustomPosCoords(), Sprite(), and StopUsingCustomPosCoords().
m_bUsingCustomTexCoords
bool Sprite::m_bUsingCustomTexCoords private
Referenced by GetActiveTextureCoords(), SetCustomTextureCoords(), SetCustomTextureRect(), Sprite(), and StopUsingCustomCoords().
m_CustomPosCoords
float Sprite::m_CustomPosCoords[8] private
Set up the coordinates for the position.
These are offsets for the quad the sprite will be drawn to. The first two are the (x, y) offsets for the top left. The remaining six are for the (x, y) coordinates for bottom left, bottom right, and top right respectively. These are offsets instead of a replacement for m_size to avoid complicating the cropping code.
Referenced by DrawTexture(), SetCustomPosCoords(), and Sprite().
m_CustomTexCoords
float Sprite::m_CustomTexCoords[8] private
Set up the coordinates for the texture.
The first two parameters are the (x, y) coordinates for the top left. The remaining six are for the (x, y) coordinates for bottom left, bottom right, and top right respectively.
Referenced by GetActiveTextureCoords(), SetCustomTextureCoords(), SetCustomTextureRect(), and Sprite().
m_DecodeMovie
bool Sprite::m_DecodeMovie
Referenced by LunaSprite::SetDecodeMovie(), Sprite(), and Update().
m_EffectMode
EffectMode Sprite::m_EffectMode private
Referenced by DrawTexture(), SetEffectMode(), and Sprite().
m_fRememberedClipHeight
float Sprite::m_fRememberedClipHeight private
Referenced by CropTo(), ScaleToClipped(), SetTexture(), and Sprite().
m_fRememberedClipWidth
float Sprite::m_fRememberedClipWidth private
Referenced by CropTo(), ScaleToClipped(), SetTexture(), and Sprite().
m_fSecsIntoState
float Sprite::m_fSecsIntoState private
The number of seconds that have elapsed since we switched to this frame.
Referenced by InitState(), SetSecondsIntoAnimation(), SetState(), Sprite(), Update(), and UpdateAnimationState().
m_fTexCoordVelocityX
float Sprite::m_fTexCoordVelocityX private
Referenced by SetTexCoordVelocity(), Sprite(), and Update().
m_fTexCoordVelocityY
float Sprite::m_fTexCoordVelocityY private
Referenced by SetTexCoordVelocity(), Sprite(), and Update().
m_iCurState
int Sprite::m_iCurState private
Referenced by GetCurrentTextureCoordRect(), GetState(), InitState(), SetState(), Sprite(), and UpdateAnimationState().
m_pTexture
RageTexture* Sprite::m_pTexture private
Referenced by AddImageCoords(), CropTo(), DrawTexture(), EarlyAbortDraw(), GetTexture(), GetTexturePath(), LoadFromNode(), LoadFromTexture(), LoadStatesFromTexture(), ScaleToClipped(), SetCustomImageCoords(), SetCustomImageRect(), SetSecondsIntoAnimation(), SetState(), SetTexture(), Sprite(), UnloadTexture(), and Update().
m_States
vector<State> Sprite::m_States private
Referenced by GetNumStates(), GetTextureCoordRectForState(), LoadFromNode(), LoadStatesFromTexture(), RecalcAnimationLengthSeconds(), SetAllStateDelays(), SetState(), SetStateProperties(), SetTexture(), Sprite(), and UpdateAnimationState().
m_use_effect_clock_for_texcoords
bool Sprite::m_use_effect_clock_for_texcoords
Referenced by LunaSprite::get_use_effect_clock_for_texcoords(), LunaSprite::set_use_effect_clock_for_texcoords(), Sprite(), and Update().
The documentation for this class was generated from the following files:
Sprite.h
Sprite.cpp