Etterna: GameConstantsAndTypes.h File Reference
GameConstantsAndTypes.h File Reference
#include "global.h"
#include "EnumHelper.h"
#include <cfloat>
Classes
struct DisplayBpms
The list of BPMs to display.
Enumerations
enum Skillset {
Skill_Overall, Skill_Stream, Skill_Jumpstream, Skill_Handstream,
Skill_Stamina, Skill_JackSpeed, Skill_Chordjack, Skill_Technical,
NUM_Skillset, Skillset_Invalid
}
enum NSScoreBoardColumn {
NSSB_NAMES = 0, NSSB_COMBO, NSSB_GRADE, NUM_NSScoreBoardColumn,
NSScoreBoardColumn_Invalid
}
enum ValidationKey { ValidationKey_Brittle, ValidationKey_Weak, NUM_ValidationKey, ValidationKey_Invalid }
enum RadarCategory {
RadarCategory_Notes, RadarCategory_TapsAndHolds, RadarCategory_Jumps, RadarCategory_Holds,
RadarCategory_Mines, RadarCategory_Hands, RadarCategory_Rolls, RadarCategory_Lifts,
RadarCategory_Fakes, NUM_RadarCategory, RadarCategory_Invalid
}
The various radar categories available.
enum StepsTypeCategory { StepsTypeCategory_Single, StepsTypeCategory_Double, StepsTypeCategory_Couple, StepsTypeCategory_Routine }
The different game categories available to play.
enum StepsType {
StepsType_dance_single = 0, StepsType_dance_double, StepsType_dance_couple, StepsType_dance_solo,
StepsType_dance_threepanel, StepsType_dance_routine, StepsType_pump_single, StepsType_pump_halfdouble,
StepsType_pump_double, StepsType_pump_couple, StepsType_pump_routine, StepsType_kb7_single,
StepsType_ez2_single, StepsType_ez2_double, StepsType_ez2_real, StepsType_para_single,
StepsType_ds3ddx_single, StepsType_beat_single5, StepsType_beat_versus5, StepsType_beat_double5,
StepsType_beat_single7, StepsType_beat_versus7, StepsType_beat_double7, StepsType_maniax_single,
StepsType_maniax_double, StepsType_techno_single4, StepsType_techno_single5, StepsType_techno_single8,
StepsType_techno_double4, StepsType_techno_double5, StepsType_techno_double8, StepsType_popn_five,
StepsType_popn_nine, NUM_StepsType, StepsType_Invalid
}
The different steps types for playing.
enum PlayMode { PLAY_MODE_REGULAR, NUM_PlayMode, PlayMode_Invalid }
The various play modes available.
enum SortOrder {
SORT_PREFERRED, SORT_GROUP, SORT_TITLE, SORT_BPM,
SORT_POPULARITY, SORT_TOP_GRADES, SORT_ARTIST, SORT_GENRE,
SORT_MODE_MENU, SORT_RECENT, SORT_FAVORITES, SORT_Overall,
SORT_Stream, SORT_Jumpstream, SORT_Handstream, SORT_Stamina,
SORT_JackSpeed, SORT_Chordjack, SORT_Technical, SORT_LENGTH,
NUM_SortOrder, SortOrder_Invalid
}
The list of ways to sort songs.
enum TapNoteScore {
TNS_None, TNS_HitMine, TNS_AvoidMine, TNS_CheckpointMiss,
TNS_Miss, TNS_W5, TNS_W4, TNS_W3,
TNS_W2, TNS_W1, TNS_CheckpointHit, NUM_TapNoteScore,
TapNoteScore_Invalid
}
The list of tap note scores available during play.
enum HoldNoteScore {
HNS_None, HNS_LetGo, HNS_Held, HNS_Missed,
NUM_HoldNoteScore, HoldNoteScore_Invalid
}
The list of hold note scores available during play.
enum TimingWindow {
TW_W1, TW_W2, TW_W3, TW_W4,
TW_W5, TW_Mine, TW_Hold, TW_Roll,
TW_Checkpoint, NUM_TimingWindow
}
The list of timing windows to deal with when playing.
enum ScoreEvent {
SE_CheckpointHit, SE_W1, SE_W2, SE_W3,
SE_W4, SE_W5, SE_Miss, SE_HitMine,
SE_CheckpointMiss, SE_Held, SE_LetGo, SE_Missed,
NUM_ScoreEvent
}
The list of score events that can take place while playing.
enum GameButtonType { GameButtonType_Step, GameButtonType_Menu }
The list of game button types available for all game modes.
enum TapNoteScoreJudgeType { TapNoteScoreJudgeType_MinimumScore, TapNoteScoreJudgeType_LastScore, NUM_TapNoteScoreJudgeType, TapNoteScoreJudgeType_Invalid }
The list of judge types for the tap note scores.
enum ProfileSlot { ProfileSlot_Player1, ProfileSlot_Player2, NUM_ProfileSlot, ProfileSlot_Invalid }
The profile slots available. This is mainly for Profiles and Memory Cards.
enum RankingCategory {
RANKING_A, RANKING_B, RANKING_C, RANKING_D,
NUM_RankingCategory, RankingCategory_Invalid
}
The different ranking categories based on difficulty meter average.
enum PlayerController {
PC_HUMAN, PC_AUTOPLAY, PC_CPU, PC_REPLAY,
NUM_PlayerController, PlayerController_Invalid
}
The different types of players in the game.
enum HealthState {
HealthState_Hot, HealthState_Alive, HealthState_Danger, HealthState_Dead,
NUM_HealthState, HealthState_Invalid
}
The different health bar states.
enum StageResult {
RESULT_WIN, RESULT_LOSE, RESULT_DRAW, NUM_StageResult,
StageResult_Invalid
}
The different stage results during battle.
enum StageAward {
StageAward_FullComboW3, StageAward_SingleDigitW3, StageAward_OneW3, StageAward_FullComboW2,
StageAward_SingleDigitW2, StageAward_OneW2, StageAward_FullComboW1, StageAward_80PercentW3,
StageAward_90PercentW3, StageAward_100PercentW3, NUM_StageAward, StageAward_Invalid
}
The various stage awards that can be given based on excellent play.
enum PeakComboAward {
PeakComboAward_1000, PeakComboAward_2000, PeakComboAward_3000, PeakComboAward_4000,
PeakComboAward_5000, PeakComboAward_6000, PeakComboAward_7000, PeakComboAward_8000,
PeakComboAward_9000, PeakComboAward_10000, NUM_PeakComboAward, PeakComboAward_Invalid
}
The various peak combo awards should such a combo be attained during play.
enum StyleType {
StyleType_OnePlayerOneSide, StyleType_TwoPlayersTwoSides, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides,
NUM_StyleType, StyleType_Invalid
}
The various style types available.
enum EditMode {
EditMode_Practice, EditMode_Home, EditMode_Full, NUM_EditMode,
EditMode_Invalid
}
The different types of Edit modes available.
enum SampleMusicPreviewMode {
SampleMusicPreviewMode_Normal, SampleMusicPreviewMode_StartToPreview, SampleMusicPreviewMode_ScreenMusic, SampleMusicPreviewMode_LastSong,
NUM_SampleMusicPreviewMode, SampleMusicPreviewMode_Invalid
}
The different types of sample music previews available.
enum Stage {
Stage_1st, Stage_2nd, Stage_3rd, Stage_4th,
Stage_5th, Stage_6th, Stage_Next, Stage_Final,
Stage_Extra1, Stage_Extra2, Stage_Event, Stage_Demo,
NUM_Stage, Stage_Invalid
}
The different kinds of Stages available.
enum ProfileLoadResult { ProfileLoadResult_Success, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered }
The different results of loading a profile.
enum MultiPlayerStatus {
MultiPlayerStatus_Joined, MultiPlayerStatus_NotJoined, MultiPlayerStatus_Unplugged, MultiPlayerStatus_MissingMultitap,
NUM_MultiPlayerStatus, MultiPlayerStatus_Invalid
}
The different statuses for multiplayer.
enum FailType {
FailType_Immediate, FailType_ImmediateContinue, FailType_EndOfSong, FailType_Off,
NUM_FailType, FailType_Invalid
}
How can the Player fail a song?
Functions
const RString & SkillsetToString (Skillset ss)
const RString & ValidationKeyToString (ValidationKey ss)
const RString & RadarCategoryToString (RadarCategory cat)
Turn the radar category into a proper string.
const RString & RadarCategoryToLocalizedString (RadarCategory cat)
Turn the radar category into a proper localized string.
LuaDeclareType (RadarCategory)
LuaDeclareType (StepsType)
const RString & PlayModeToString (PlayMode pm)
Turn the play mode into a proper string.
const RString & PlayModeToLocalizedString (PlayMode pm)
Turn the play mode into a proper localized string.
PlayMode StringToPlayMode (const RString &s)
Turn the string into the proper play mode.
LuaDeclareType (PlayMode)
const RString & SortOrderToString (SortOrder so)
Turn the sort order into a proper string.
const RString & SortOrderToLocalizedString (SortOrder so)
Turn the sort order into a proper localized string.
SortOrder StringToSortOrder (const RString &str)
Turn the string into the proper sort order.
LuaDeclareType (SortOrder)
bool IsSongSort (SortOrder so)
Determine if the sort order in question is for songs or not.
const RString & TapNoteScoreToString (TapNoteScore tns)
Turn the tap note score into a proper string.
const RString & TapNoteScoreToLocalizedString (TapNoteScore tns)
Turn the tap note score into a proper localized string.
TapNoteScore StringToTapNoteScore (const RString &str)
Turn the string into the proper tap note score.
LuaDeclareType (TapNoteScore)
const RString & HoldNoteScoreToString (HoldNoteScore hns)
Turn the hold note score into a proper string.
const RString & HoldNoteScoreToLocalizedString (HoldNoteScore hns)
Turn the hold note score into a proper localized string.
HoldNoteScore StringToHoldNoteScore (const RString &str)
Turn the string into the proper hold note score.
LuaDeclareType (HoldNoteScore)
const RString & TimingWindowToString (TimingWindow tw)
const RString & ScoreEventToString (ScoreEvent se)
const RString & TapNoteScoreJudgeTypeToString (TapNoteScoreJudgeType jt)
LuaDeclareType (TapNoteScoreJudgeType)
const RString & ProfileSlotToString (ProfileSlot ps)
LuaDeclareType (ProfileSlot)
const RString & RankingCategoryToString (RankingCategory rc)
RankingCategory StringToRankingCategory (const RString &rc)
LuaDeclareType (RankingCategory)
bool IsRankingToFillIn (const RString &sName)
RankingCategory AverageMeterToRankingCategory (int iAverageMeter)
const RString & PlayerControllerToString (PlayerController pc)
LuaDeclareType (PlayerController)
LuaDeclareType (HealthState)
LuaDeclareType (StageResult)
const RString & StageAwardToString (StageAward pma)
const RString & StageAwardToLocalizedString (StageAward pma)
StageAward StringToStageAward (const RString &pma)
LuaDeclareType (StageAward)
const RString & PeakComboAwardToString (PeakComboAward pma)
const RString & PeakComboAwardToLocalizedString (PeakComboAward pma)
PeakComboAward StringToPeakComboAward (const RString &pma)
LuaDeclareType (PeakComboAward)
const RString & StyleTypeToString (StyleType s)
StyleType StringToStyleType (const RString &s)
LuaDeclareType (StyleType)
const RString & EditModeToString (EditMode em)
EditMode StringToEditMode (const RString &s)
LuaDeclareType (EditMode)
const RString & SampleMusicPreviewModeToString (SampleMusicPreviewMode)
SampleMusicPreviewMode StringToSampleMusicPreviewMode (const RString &s)
LuaDeclareType (SampleMusicPreviewMode)
const RString & StageToString (Stage s)
LuaDeclareType (Stage)
const RString & StageToLocalizedString (Stage i)
const RString & MultiPlayerStatusToString (MultiPlayerStatus i)
const RString & FailTypeToString (FailType cat)
const RString & FailTypeToLocalizedString (FailType cat)
LuaDeclareType (FailType)
Variables
const int MIN_METER = 1
Define the mininum difficulty value allowed.
const int MAX_METER = 35
Define the maximum difficulty value allowed.
const int MAX_NUM_CREDITS = 20
The maximum number of credits for coin mode.
const SortOrder MAX_SELECTABLE_SORT = static_cast<SortOrder>(SORT_RECENT - 1)
Only allow certain sort modes to be selectable.
const vector< RString > RANKING_TO_FILL_IN_MARKER
const RString GROUP_ALL
Detailed Description
Author
Chris Danford, Chris Gomez (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Enumeration Type Documentation
EditMode
enum EditMode
The different types of Edit modes available.
Enumerator
EditMode_Practice
EditMode_Home
EditMode_Full
NUM_EditMode
EditMode_Invalid
FailType
enum FailType
How can the Player fail a song?
Enumerator
FailType_Immediate
fail immediately when life touches 0
FailType_ImmediateContinue
Same as above, but allow playing the rest of the song
FailType_EndOfSong
fail if life is at 0 when the song ends
FailType_Off
never fail
NUM_FailType
FailType_Invalid
GameButtonType
enum GameButtonType
The list of game button types available for all game modes.
Enumerator
GameButtonType_Step
GameButtonType_Menu
HealthState
enum HealthState
The different health bar states.
Enumerator
HealthState_Hot
The health bar is very full.
HealthState_Alive
The health bar is at a decent size.
HealthState_Danger
The health bar is about to run out.
HealthState_Dead
The health bar is drained completely.
NUM_HealthState
HealthState_Invalid
HoldNoteScore
enum HoldNoteScore
The list of hold note scores available during play.
Enumerator
HNS_None
The HoldNote was not scored yet.
HNS_LetGo
The HoldNote has passed, but the player missed it.
HNS_Held
The HoldNote has passed, and was successfully held all the way.
HNS_Missed
The HoldNote has passed, and was never initialized.
NUM_HoldNoteScore
The number of hold note scores.
HoldNoteScore_Invalid
MultiPlayerStatus
enum MultiPlayerStatus
The different statuses for multiplayer.
Enumerator
MultiPlayerStatus_Joined
MultiPlayerStatus_NotJoined
MultiPlayerStatus_Unplugged
MultiPlayerStatus_MissingMultitap
NUM_MultiPlayerStatus
MultiPlayerStatus_Invalid
NSScoreBoardColumn
enum NSScoreBoardColumn
Enumerator
NSSB_NAMES
NSSB_COMBO
NSSB_GRADE
NUM_NSScoreBoardColumn
NSScoreBoardColumn_Invalid
PeakComboAward
enum PeakComboAward
The various peak combo awards should such a combo be attained during play.
Enumerator
PeakComboAward_1000
PeakComboAward_2000
PeakComboAward_3000
PeakComboAward_4000
PeakComboAward_5000
PeakComboAward_6000
PeakComboAward_7000
PeakComboAward_8000
PeakComboAward_9000
PeakComboAward_10000
NUM_PeakComboAward
PeakComboAward_Invalid
PlayerController
enum PlayerController
The different types of players in the game.
Enumerator
PC_HUMAN
PC_AUTOPLAY
PC_CPU
PC_REPLAY
NUM_PlayerController
PlayerController_Invalid
PlayMode
enum PlayMode
The various play modes available.
Enumerator
PLAY_MODE_REGULAR
The normal game mode, often with a set number of stages.
NUM_PlayMode
PlayMode_Invalid
ProfileLoadResult
enum ProfileLoadResult
The different results of loading a profile.
Enumerator
ProfileLoadResult_Success
ProfileLoadResult_FailedNoProfile
ProfileLoadResult_FailedTampered
ProfileSlot
enum ProfileSlot
The profile slots available. This is mainly for Profiles and Memory Cards.
Enumerator
ProfileSlot_Player1
ProfileSlot_Player2
NUM_ProfileSlot
ProfileSlot_Invalid
RadarCategory
enum RadarCategory
The various radar categories available.
This is just cached song data. Not all of it may actually be displayed in the radar.
Enumerator
RadarCategory_Notes
How many notes are in the song?
RadarCategory_TapsAndHolds
How many taps and holds are in the song?
RadarCategory_Jumps
How many jumps are in the song?
RadarCategory_Holds
How many holds are in the song?
RadarCategory_Mines
How many mines are in the song?
RadarCategory_Hands
How many hands are in the song?
RadarCategory_Rolls
How many rolls are in the song?
RadarCategory_Lifts
How many lifts are in the song?
RadarCategory_Fakes
How many fakes are in the song?
NUM_RadarCategory
The number of radar categories.
RadarCategory_Invalid
RankingCategory
enum RankingCategory
The different ranking categories based on difficulty meter average.
Enumerator
RANKING_A
1-3 meter per song avg.
RANKING_B
4-6 meter per song avg.
RANKING_C
7-9 meter per song avg.
RANKING_D
10+ meter per song avg, not counting extra stages.
NUM_RankingCategory
The number of ranking categories.
RankingCategory_Invalid
SampleMusicPreviewMode
enum SampleMusicPreviewMode
The different types of sample music previews available.
These were originally from the deleted screen ScreenEz2SelectMusic. (if no confirm type is mentioned, there is none.)
0 = play music as you select; SampleMusicPreviewMode_Normal 1 = no music plays, select 1x to play preview music, select again to confirm 2 = no music plays at all (SampleMusicPreviewMode_ScreenMusic
redir to silent) 3 = play music as select, 2x to confirm (SampleMusicPreviewMode_Normal + [SSMusic] TwoPartConfirmsOnly) 4 = screen music plays; SampleMusicPreviewMode_ScreenMusic
Enumerator
SampleMusicPreviewMode_Normal
Music is played as the song is highlighted.
SampleMusicPreviewMode_StartToPreview
SampleMusicPreviewMode_ScreenMusic
No music plays. Select it once to preview the music, then once more to select the song.
SampleMusicPreviewMode_LastSong
continue playing the last song
NUM_SampleMusicPreviewMode
SampleMusicPreviewMode_Invalid
ScoreEvent
enum ScoreEvent
The list of score events that can take place while playing.
Enumerator
SE_CheckpointHit
SE_W1
SE_W2
SE_W3
SE_W4
SE_W5
SE_Miss
SE_HitMine
SE_CheckpointMiss
SE_Held
SE_LetGo
SE_Missed
NUM_ScoreEvent
Skillset
enum Skillset
Enumerator
Skill_Overall
Skill_Stream
Skill_Jumpstream
Skill_Handstream
Skill_Stamina
Skill_JackSpeed
Skill_Chordjack
Skill_Technical
NUM_Skillset
Skillset_Invalid
SortOrder
enum SortOrder
The list of ways to sort songs.
Enumerator
SORT_PREFERRED
Sort by the user's preferred settings.
SORT_GROUP
Sort by the groups the Songs are in.
SORT_TITLE
Sort by the Song's title.
SORT_BPM
Sort by the Song's BPM.
SORT_POPULARITY
Sort by how popular the Song is.
SORT_TOP_GRADES
Sort by the highest grades earned on a Song.
SORT_ARTIST
Sort by the name of the artist of the Song.
SORT_GENRE
Sort by the Song's genre.
SORT_MODE_MENU
Have access to the menu for choosing the sort.
SORT_RECENT
SORT_FAVORITES
SORT_Overall
SORT_Stream
SORT_Jumpstream
SORT_Handstream
SORT_Stamina
SORT_JackSpeed
SORT_Chordjack
SORT_Technical
SORT_LENGTH
NUM_SortOrder
SortOrder_Invalid
Stage
enum Stage
The different kinds of Stages available.
These are shared stage values shown in StageDisplay. These are not per-player.
Enumerator
Stage_1st
The first stage.
Stage_2nd
The second stage.
Stage_3rd
The third stage.
Stage_4th
The fourth stage.
Stage_5th
The fifth stage.
Stage_6th
The sixth stage.
Stage_Next
Somewhere between the sixth and final stage. This won't normally happen because 7 stages is the max in the UI.
Stage_Final
The last stage.
Stage_Extra1
The first bonus stage, AKA the extra stage.
Stage_Extra2
The last bonus stage, AKA the encore extra stage.
Stage_Event
Playing in event mode.
Stage_Demo
Playing the demonstration.
NUM_Stage
The number of stage types.
Stage_Invalid
StageAward
enum StageAward
The various stage awards that can be given based on excellent play.
Enumerator
StageAward_FullComboW3
A full great combo (or equivalent) was earned.
StageAward_SingleDigitW3
A single digit great combo (or equivalent) was earned.
StageAward_OneW3
Only one great (or equivalent) was earned.
StageAward_FullComboW2
A full excellent combo (or equivalent) was earned.
StageAward_SingleDigitW2
A single digit excellent combo (or equivalent) was earned.
StageAward_OneW2
Only one excellent (or equivalent) was earned.
StageAward_FullComboW1
All fantastics (or equivalent) were earned.
StageAward_80PercentW3
StageAward_90PercentW3
StageAward_100PercentW3
NUM_StageAward
StageAward_Invalid
StageResult
enum StageResult
The different stage results during battle.
Enumerator
RESULT_WIN
The player has won the battle.
RESULT_LOSE
The player has lost the battle.
RESULT_DRAW
The player has tied with the competitor.
NUM_StageResult
StageResult_Invalid
StepsType
enum StepsType
The different steps types for playing.
Enumerator
StepsType_dance_single
StepsType_dance_double
StepsType_dance_couple
StepsType_dance_solo
StepsType_dance_threepanel
StepsType_dance_routine
StepsType_pump_single
StepsType_pump_halfdouble
StepsType_pump_double
StepsType_pump_couple
StepsType_pump_routine
StepsType_kb7_single
StepsType_ez2_single
StepsType_ez2_double
StepsType_ez2_real
StepsType_para_single
StepsType_ds3ddx_single
StepsType_beat_single5
StepsType_beat_versus5
StepsType_beat_double5
StepsType_beat_single7
StepsType_beat_versus7
StepsType_beat_double7
StepsType_maniax_single
StepsType_maniax_double
StepsType_techno_single4
StepsType_techno_single5
StepsType_techno_single8
StepsType_techno_double4
StepsType_techno_double5
StepsType_techno_double8
StepsType_popn_five
StepsType_popn_nine
NUM_StepsType
StepsType_Invalid
StepsTypeCategory
enum StepsTypeCategory
The different game categories available to play.
Enumerator
StepsTypeCategory_Single
One person plays on one side.
StepsTypeCategory_Double
One person plays on both sides.
StepsTypeCategory_Couple
Two players play on their own side.
StepsTypeCategory_Routine
Two players share both sides together.
StyleType
enum StyleType
The various style types available.
Enumerator
StyleType_OnePlayerOneSide
Single style
StyleType_TwoPlayersTwoSides
Versus style
StyleType_OnePlayerTwoSides
Double style
StyleType_TwoPlayersSharedSides
Routine style
NUM_StyleType
StyleType_Invalid
TapNoteScore
enum TapNoteScore
The list of tap note scores available during play.
Enumerator
TNS_None
There is no score involved with this one.
TNS_HitMine
A mine was hit successfully.
TNS_AvoidMine
A mine was avoided successfully.
TNS_CheckpointMiss
A checkpoint was missed during a hold.
TNS_Miss
A note was missed entirely.
TNS_W5
A note was almost missed, but not quite.
TNS_W4
A note was hit either a bit early or a bit late.
TNS_W3
A note was hit with decent accuracy, but not the best.
TNS_W2
A note was hit off by just a miniscule amount. This used to be the best rating.
TNS_W1
A note was hit perfectly.
TNS_CheckpointHit
A checkpoint was held during a hold.
NUM_TapNoteScore
The number of Tap Note Scores available.
TapNoteScore_Invalid
TapNoteScoreJudgeType
enum TapNoteScoreJudgeType
The list of judge types for the tap note scores.
Enumerator
TapNoteScoreJudgeType_MinimumScore
TapNoteScoreJudgeType_LastScore
NUM_TapNoteScoreJudgeType
TapNoteScoreJudgeType_Invalid
TimingWindow
enum TimingWindow
The list of timing windows to deal with when playing.
Enumerator
TW_W1
TW_W2
TW_W3
TW_W4
TW_W5
TW_Mine
TW_Hold
TW_Roll
TW_Checkpoint
NUM_TimingWindow
ValidationKey
enum ValidationKey
Enumerator
ValidationKey_Brittle
ValidationKey_Weak
NUM_ValidationKey
ValidationKey_Invalid
Function Documentation
AverageMeterToRankingCategory()
RankingCategory AverageMeterToRankingCategory (int iAverageMeter)
References RANKING_A, RANKING_B, RANKING_C, and RANKING_D.
EditModeToString()
const RString& EditModeToString (EditMode em)
FailTypeToLocalizedString()
const RString& FailTypeToLocalizedString (FailType cat)
FailTypeToString()
const RString& FailTypeToString (FailType cat)
HoldNoteScoreToLocalizedString()
const RString& HoldNoteScoreToLocalizedString (HoldNoteScore hns)
Turn the hold note score into a proper localized string.
Parameters
hns the hold note score.
Returns
the localized string version of the hold note score.
HoldNoteScoreToString()
const RString& HoldNoteScoreToString (HoldNoteScore hns)
Turn the hold note score into a proper string.
Parameters
hns the hold note score.
Returns
the string version of the hold note score.
Referenced by HighScoreImpl::CreateEttNode(), HighScoreImpl::CreateNode(), GhostArrowRow::DidHoldNote(), ScoreDisplayLifeTime::Init(), HighScoreImpl::LoadFromEttNode(), and HighScoreImpl::LoadFromNode().
IsRankingToFillIn()
bool IsRankingToFillIn (const RString & sName) inline
Referenced by HighScoreImpl::CreateNode().
IsSongSort()
bool IsSongSort (SortOrder so) inline
Determine if the sort order in question is for songs or not.
This function is mainly used for saving sort order to the profile. -aj
References SORT_GENRE, and SORT_PREFERRED.
Referenced by MusicWheel::ChangeSort(), and GameState::SaveCurrentSettingsToProfile().
LuaDeclareType() [1/19]
LuaDeclareType (RadarCategory)
LuaDeclareType() [2/19]
LuaDeclareType (StepsType)
LuaDeclareType() [3/19]
LuaDeclareType (PlayMode)
LuaDeclareType() [4/19]
LuaDeclareType (SortOrder)
LuaDeclareType() [5/19]
LuaDeclareType (TapNoteScore)
LuaDeclareType() [6/19]
LuaDeclareType (HoldNoteScore)
LuaDeclareType() [7/19]
LuaDeclareType (TapNoteScoreJudgeType)
LuaDeclareType() [8/19]
LuaDeclareType (ProfileSlot)
LuaDeclareType() [9/19]
LuaDeclareType (RankingCategory)
LuaDeclareType() [10/19]
LuaDeclareType (PlayerController)
LuaDeclareType() [11/19]
LuaDeclareType (HealthState)
LuaDeclareType() [12/19]
LuaDeclareType (StageResult)
LuaDeclareType() [13/19]
LuaDeclareType (StageAward)
LuaDeclareType() [14/19]
LuaDeclareType (PeakComboAward)
LuaDeclareType() [15/19]
LuaDeclareType (StyleType)
LuaDeclareType() [16/19]
LuaDeclareType (EditMode)
LuaDeclareType() [17/19]
LuaDeclareType (SampleMusicPreviewMode)
LuaDeclareType() [18/19]
LuaDeclareType (Stage)
LuaDeclareType() [19/19]
LuaDeclareType (FailType)
MultiPlayerStatusToString()
const RString& MultiPlayerStatusToString (MultiPlayerStatus i)
PeakComboAwardToLocalizedString()
const RString& PeakComboAwardToLocalizedString (PeakComboAward pma)
PeakComboAwardToString()
const RString& PeakComboAwardToString (PeakComboAward pma)
Referenced by HighScoreImpl::CreateNode().
PlayerControllerToString()
const RString& PlayerControllerToString (PlayerController pc)
PlayModeToLocalizedString()
const RString& PlayModeToLocalizedString (PlayMode pm)
Turn the play mode into a proper localized string.
Parameters
pm the play mode.
Returns
the localized string version of the play mode.
PlayModeToString()
const RString& PlayModeToString (PlayMode pm)
Turn the play mode into a proper string.
Parameters
pm the play mode.
Returns
the string version of the play mode.
Referenced by GameState::GetRankingFeats(), GameCommand::IsPlayable(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveEttGeneralDataCreateNode(), and XMLProfile::SaveGeneralDataCreateNode().
ProfileSlotToString()
const RString& ProfileSlotToString (ProfileSlot ps)
RadarCategoryToLocalizedString()
const RString& RadarCategoryToLocalizedString (RadarCategory cat)
Turn the radar category into a proper localized string.
Parameters
cat the radar category.
Returns
the localized string version of the radar category.
RadarCategoryToString()
const RString& RadarCategoryToString (RadarCategory cat)
Turn the radar category into a proper string.
Parameters
cat the radar category.
Returns
the string version of the radar category.
Referenced by RadarValues::CreateNode(), Deserialize(), RadarValues::LoadFromNode(), and Serialize().
RankingCategoryToString()
const RString& RankingCategoryToString (RankingCategory rc)
Referenced by XMLProfile::SaveCategoryScoresCreateNode().
SampleMusicPreviewModeToString()
const RString& SampleMusicPreviewModeToString (SampleMusicPreviewMode)
ScoreEventToString()
const RString& ScoreEventToString (ScoreEvent se)
Referenced by GradeWeightName(), LIFE_PERCENT_CHANGE_NAME(), PercentScoreWeightName(), and TimeMeterSecondsChangeInit().
SkillsetToString()
const RString& SkillsetToString (Skillset ss)
Referenced by HighScoreImpl::CreateEttNode(), HighScoreImpl::CreateNode(), LunaSteps::GetRelevantSkillsetsByMSDRank(), LunaDownloadManager::GetTopChartScore(), XMLProfile::LoadEttGeneralDataFromNode(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), XMLProfile::LoadGeneralDataFromNode(), DownloadManager::RefreshTop25(), DownloadManager::RefreshUserData(), DownloadManager::RefreshUserRank(), ETTProtocol::ReportHighScore(), DownloadManager::RequestChartLeaderBoard(), DBProfile::SaveDBToDir(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), ETTProtocol::Update(), and DownloadManager::UploadScoreWithReplayData().
SortOrderToLocalizedString()
const RString& SortOrderToLocalizedString (SortOrder so)
Turn the sort order into a proper localized string.
Parameters
so the sort order.
Returns
the localized string version of the sort order.
SortOrderToString()
const RString& SortOrderToString (SortOrder so)
Turn the sort order into a proper string.
Parameters
so the sort order.
Returns
the string version of the sort order.
Referenced by Banner::LoadFromSortOrder(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), and XMLProfile::SaveGeneralDataCreateNode().
StageAwardToLocalizedString()
const RString& StageAwardToLocalizedString (StageAward pma)
StageAwardToString()
const RString& StageAwardToString (StageAward pma)
Referenced by HighScoreImpl::CreateNode().
StageToLocalizedString()
const RString& StageToLocalizedString (Stage i)
StageToString()
const RString& StageToString (Stage s)
StringToEditMode()
EditMode StringToEditMode (const RString & s)
StringToHoldNoteScore()
HoldNoteScore StringToHoldNoteScore (const RString & str)
Turn the string into the proper hold note score.
Parameters
str the string.
Returns
the hold note score based on the string.
References HNS_Held, HNS_LetGo, HNS_Missed, HNS_None, and HoldNoteScore_Invalid.
StringToPeakComboAward()
PeakComboAward StringToPeakComboAward (const RString & pma)
Referenced by HighScoreImpl::LoadFromNode().
StringToPlayMode()
PlayMode StringToPlayMode (const RString & s)
Turn the string into the proper play mode.
Parameters
s the string.
Returns
the play mode based on the string.
Referenced by GameCommand::LoadOne().
StringToRankingCategory()
RankingCategory StringToRankingCategory (const RString & rc)
Referenced by XMLProfile::LoadCategoryScoresFromNode().
StringToSampleMusicPreviewMode()
SampleMusicPreviewMode StringToSampleMusicPreviewMode (const RString & s)
StringToSortOrder()
SortOrder StringToSortOrder (const RString & str)
Turn the string into the proper sort order.
Parameters
str the string.
Returns
the sort order based on the string.
Referenced by GetDefaultSort(), XMLProfile::LoadEttGeneralDataFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), and GameCommand::LoadOne().
StringToStageAward()
StageAward StringToStageAward (const RString & pma)
Referenced by HighScoreImpl::LoadFromNode().
StringToStyleType()
StyleType StringToStyleType (const RString & s)
StringToTapNoteScore()
TapNoteScore StringToTapNoteScore (const RString & str)
Turn the string into the proper tap note score.
Parameters
str the string.
Returns
the tap note score based on the string.
References tns_conversion_helper::conversion_map, and TapNoteScore_Invalid.
Referenced by StringConversion::FromString< TapNoteScore >().
StyleTypeToString()
const RString& StyleTypeToString (StyleType s)
TapNoteScoreJudgeTypeToString()
const RString& TapNoteScoreJudgeTypeToString (TapNoteScoreJudgeType jt)
TapNoteScoreToLocalizedString()
const RString& TapNoteScoreToLocalizedString (TapNoteScore tns)
Turn the tap note score into a proper localized string.
Parameters
tns the tap note score.
Returns
the localized string version of the tap note score.
TapNoteScoreToString()
const RString& TapNoteScoreToString (TapNoteScore tns)
Turn the tap note score into a proper string.
Parameters
tns the tap note score.
Returns
the string version of the tap note score.
Referenced by HighScoreImpl::CreateEttNode(), TapNoteResult::CreateNode(), HighScoreImpl::CreateNode(), GhostArrowRow::DidTapNote(), ScoreDisplayLifeTime::Init(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), and ReceptorArrow::Step().
TimingWindowToString()
const RString& TimingWindowToString (TimingWindow tw)
Referenced by TimingWindowSecondsInit().
ValidationKeyToString()
const RString& ValidationKeyToString (ValidationKey ss)
Referenced by HighScoreImpl::CreateEttNode(), and HighScoreImpl::LoadFromEttNode().
Variable Documentation
GROUP_ALL
const RString GROUP_ALL
MAX_METER
const int MAX_METER = 35
Define the maximum difficulty value allowed.
35 is used rather than 13 due to a variety of Profile data. For more examples, see Profile::InitGeneralData(). -aj
Referenced by Profile::InitGeneralData(), XMLProfile::LoadGeneralDataFromNode(), ScreenGameplay::LoadNextSong(), Profile::MergeScoresFromOtherProfile(), XMLProfile::SaveGeneralDataCreateNode(), and Profile::swap().
MAX_NUM_CREDITS
const int MAX_NUM_CREDITS = 20
The maximum number of credits for coin mode.
MAX_SELECTABLE_SORT
const SortOrder MAX_SELECTABLE_SORT = static_cast<SortOrder>(SORT_RECENT - 1)
Only allow certain sort modes to be selectable.
MIN_METER
const int MIN_METER = 1
Define the mininum difficulty value allowed.
Referenced by ScreenGameplay::LoadNextSong().
RANKING_TO_FILL_IN_MARKER
const vector<RString> RANKING_TO_FILL_IN_MARKER
Referenced by ProfileManager::AddCategoryScore(), ProfileManager::AddStepsScore(), StageStats::FinalizeScores(), GameState::GetRankingFeats(), and LunaHighScore::IsFillInMarker().