Etterna: RageSurface_Save_JPEG.cpp File Reference
RageSurface_Save_JPEG.cpp File Reference
#include "global.h"
#include "RageSurface_Save_JPEG.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageFile.h"
#include "RageUtil.h"
#include "jpeglib.h"
Classes
struct my_destination_mgr
Namespaces
jpeg
A helper to get the jpeg lib.
Macros
#define OUTPUT_BUFFER_SIZE 4096
Functions
static void init_destination (jpeg::j_compress_ptr cinfo)
static jpeg::boolean empty_output_buffer (jpeg::j_compress_ptr cinfo)
static void term_destination (jpeg::j_compress_ptr cinfo)
static void jpeg_RageFile_dest (jpeg::j_compress_ptr cinfo, RageFile &f)
Macro Definition Documentation
OUTPUT_BUFFER_SIZE
#define OUTPUT_BUFFER_SIZE 4096
Referenced by empty_output_buffer(), jpeg_RageFile_dest(), and term_destination().
Function Documentation
empty_output_buffer()
static jpeg::boolean empty_output_buffer (jpeg::j_compress_ptr cinfo) static
References my_destination_mgr::buffer, my_destination_mgr::f, OUTPUT_BUFFER_SIZE, my_destination_mgr::pub, and RageFile::Write().
Referenced by jpeg_RageFile_dest().
init_destination()
static void init_destination (jpeg::j_compress_ptr cinfo) static
Referenced by jpeg_RageFile_dest().
jpeg_RageFile_dest()
static void jpeg_RageFile_dest (jpeg::j_compress_ptr cinfo, RageFile & f) static
References ASSERT, my_destination_mgr::buffer, empty_output_buffer(), my_destination_mgr::f, init_destination(), OUTPUT_BUFFER_SIZE, my_destination_mgr::pub, and term_destination().
Referenced by RageSurfaceUtils::SaveJPEG().
term_destination()
static void term_destination (jpeg::j_compress_ptr cinfo) static
References my_destination_mgr::buffer, my_destination_mgr::f, OUTPUT_BUFFER_SIZE, my_destination_mgr::pub, and RageFile::Write().
Referenced by jpeg_RageFile_dest().