Etterna: LunaScoreGoal Class Reference
LunaScoreGoal Class Reference
Public Member Functions
DEFINE_METHOD (GetRate, rate)
DEFINE_METHOD (GetPercent, percent)
DEFINE_METHOD (GetPriority, priority)
DEFINE_METHOD (IsAchieved, achieved)
DEFINE_METHOD (GetComment, comment)
DEFINE_METHOD (GetChartKey, chartkey)
DEFINE_METHOD (WhenAssigned, timeassigned.GetString())
LunaScoreGoal ()
Public Member Functions inherited from Luna< ScoreGoal >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int WhenAchieved (T *p, lua_State *L)
static int SetRate (T *p, lua_State *L)
static int SetPercent (T *p, lua_State *L)
static int SetPriority (T *p, lua_State *L)
static int SetComment (T *p, lua_State *L)
static int Delete (T *p, lua_State *L)
static int GetPBUpTo (T *p, lua_State *L)
static int IsVacuous (T *p, lua_State *L)
static int AchievedBy (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScoreGoal >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScoreGoal >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScoreGoal >
using T = ScoreGoal
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScoreGoal >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaScoreGoal()
LunaScoreGoal::LunaScoreGoal () inline
References ADD_METHOD.
Member Function Documentation
AchievedBy()
static int LunaScoreGoal::AchievedBy (T * p, lua_State * L) inline static
References ScoreGoal::achieved, and ScoreGoal::scorekey.
DEFINE_METHOD() [1/7]
LunaScoreGoal::DEFINE_METHOD (GetRate , rate)
DEFINE_METHOD() [2/7]
LunaScoreGoal::DEFINE_METHOD (GetPercent , percent)
DEFINE_METHOD() [3/7]
LunaScoreGoal::DEFINE_METHOD (GetPriority , priority)
DEFINE_METHOD() [4/7]
LunaScoreGoal::DEFINE_METHOD (IsAchieved , achieved)
DEFINE_METHOD() [5/7]
LunaScoreGoal::DEFINE_METHOD (GetComment , comment)
DEFINE_METHOD() [6/7]
LunaScoreGoal::DEFINE_METHOD (GetChartKey , chartkey)
DEFINE_METHOD() [7/7]
LunaScoreGoal::DEFINE_METHOD (WhenAssigned , timeassigned. GetString())
Delete()
static int LunaScoreGoal::Delete (T * p, lua_State * L) inline static
References ScoreGoal::chartkey, ProfileManager::GetProfile(), PLAYER_1, PROFILEMAN, Profile::RemoveGoal(), and ScoreGoal::timeassigned.
GetPBUpTo()
static int LunaScoreGoal::GetPBUpTo (T * p, lua_State * L) inline static
References ScoreGoal::GetPBUpTo(), and HighScore::PushSelf().
IsVacuous()
static int LunaScoreGoal::IsVacuous (T * p, lua_State * L) inline static
References ScoreGoal::achieved, ScoreGoal::CheckVacuity(), and ScoreGoal::vacuous.
SetComment()
static int LunaScoreGoal::SetComment (T * p, lua_State * L) inline static
References ScoreGoal::comment, and SArg.
SetPercent()
static int LunaScoreGoal::SetPercent (T * p, lua_State * L) inline static
References ScoreGoal::achieved, ScoreGoal::CheckVacuity(), CLAMP(), f, FArg, ScoreGoal::percent, and ScoreGoal::UploadIfNotVacuous().
SetPriority()
static int LunaScoreGoal::SetPriority (T * p, lua_State * L) inline static
References ScoreGoal::achieved, CLAMP(), IArg, ScoreGoal::priority, and ScoreGoal::UploadIfNotVacuous().
SetRate()
static int LunaScoreGoal::SetRate (T * p, lua_State * L) inline static
References ScoreGoal::achieved, ScoreGoal::CheckVacuity(), CLAMP(), f, FArg, ScoreGoal::rate, and ScoreGoal::UploadIfNotVacuous().
WhenAchieved()
static int LunaScoreGoal::WhenAchieved (T * p, lua_State * L) inline static
References ScoreGoal::achieved, DateTime::GetString(), and ScoreGoal::timeachieved.
The documentation for this class was generated from the following file:
Profile.cpp