Etterna: InputHandler_Linux_Event Class Reference
InputHandler_Linux_Event Class Reference
#include <InputHandler_Linux_Event.h>
Public Member Functions
InputHandler_Linux_Event ()
~InputHandler_Linux_Event ()
bool TryDevice (RString devfile)
bool DevicesChanged ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void StartThread ()
void StopThread ()
void InputThread ()
Static Private Member Functions
static int InputThread_Start (void *p)
Private Attributes
RageThread m_InputThread
InputDevice m_NextDevice
bool m_bShutdown
bool m_bDevicesChanged
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_Linux_Event()
InputHandler_Linux_Event::InputHandler_Linux_Event ()
References DEVICE_JOY10, g_apEventDevices, LinuxInputManager::InitDriver(), LINUXINPUT, m_bDevicesChanged, m_NextDevice, and StartThread().
~InputHandler_Linux_Event()
InputHandler_Linux_Event::~InputHandler_Linux_Event ()
References g_apEventDevices, RageThread::IsCreated(), m_InputThread, and StopThread().
Member Function Documentation
DevicesChanged()
bool InputHandler_Linux_Event::DevicesChanged () inline virtual
Reimplemented from InputHandler.
References m_bDevicesChanged.
GetDevicesAndDescriptions()
void InputHandler_Linux_Event::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References g_apEventDevices, m_bDevicesChanged, EventDevice::m_Dev, and EventDevice::m_sName.
InputThread()
void InputHandler_Linux_Event::InputThread () private
References ASSERT_M, InputHandler::ButtonPressed(), enum_add2(), g_apEventDevices, JOY_BUTTON_1, LOG, GamePreferences::m_AxisFix, m_bShutdown, max(), SCALE, ssprintf(), InputHandler::UpdateTimer(), RageLog::Warn(), and wrap().
InputThread_Start()
int InputHandler_Linux_Event::InputThread_Start (void * p) static private
Referenced by StartThread().
StartThread()
void InputHandler_Linux_Event::StartThread () private
References RageThread::Create(), InputThread_Start(), m_bShutdown, m_InputThread, and RageThread::SetName().
Referenced by InputHandler_Linux_Event(), and TryDevice().
StopThread()
void InputHandler_Linux_Event::StopThread () private
References LOG, m_bShutdown, m_InputThread, RageLog::Trace(), and RageThread::Wait().
Referenced by TryDevice(), and ~InputHandler_Linux_Event().
TryDevice()
bool InputHandler_Linux_Event::TryDevice (RString devfile)
References enum_add2(), g_apEventDevices, RageLog::Info(), RageThread::IsCreated(), LOG, m_bDevicesChanged, m_InputThread, m_NextDevice, EventDevice::Open(), StartThread(), and StopThread().
Referenced by LinuxInputManager::InitDriver().
Member Data Documentation
m_bDevicesChanged
bool InputHandler_Linux_Event::m_bDevicesChanged private
Referenced by DevicesChanged(), GetDevicesAndDescriptions(), InputHandler_Linux_Event(), and TryDevice().
m_bShutdown
bool InputHandler_Linux_Event::m_bShutdown private
Referenced by InputThread(), StartThread(), and StopThread().
m_InputThread
RageThread InputHandler_Linux_Event::m_InputThread private
Referenced by StartThread(), StopThread(), TryDevice(), and ~InputHandler_Linux_Event().
m_NextDevice
InputDevice InputHandler_Linux_Event::m_NextDevice private
Referenced by InputHandler_Linux_Event(), and TryDevice().
The documentation for this class was generated from the following files:
InputHandler_Linux_Event.h
InputHandler_Linux_Event.cpp