Etterna: RageSurface_Load_BMP.cpp File Reference
RageSurface_Load_BMP.cpp File Reference
#include "global.h"
#include "RageSurface_Load_BMP.h"
#include "RageFile.h"
#include "RageSurface.h"
#include "RageUtil.h"
Macros
#define FATAL_ERROR(s)
Enumerations
enum { COMP_BI_RGB = 0, COMP_BI_RLE4, COMP_BI_RLE8, COMP_BI_BITFIELDS }
Functions
static RageSurfaceUtils::OpenResult LoadBMP (RageFile &f, RageSurface *&img, RString &sError)
RageSurfaceUtils::OpenResult RageSurface_Load_BMP (const RString &sPath, RageSurface *&img, bool bHeaderOnly, RString &error)
Macro Definition Documentation
FATAL_ERROR
#define FATAL_ERROR (s)
Value:
{                                                                          \
        if (sError.size() == 0)                                                \
            sError = (s);                                                      \
        return RageSurfaceUtils::OPEN_FATAL_ERROR;                             \
    }
Referenced by LoadBMP().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COMP_BI_RGB
COMP_BI_RLE4
COMP_BI_RLE8
COMP_BI_BITFIELDS
Function Documentation
LoadBMP()
static RageSurfaceUtils::OpenResult LoadBMP (RageFile & f, RageSurface *& img, RString & sError) static
References RageSurfaceColor::a, RageSurfaceColor::b, RageSurfacePalette::colors, COMP_BI_BITFIELDS, COMP_BI_RGB, CreateSurface(), FATAL_ERROR, RageSurface::fmt, RageSurfaceColor::g, RageFile::GetError(), max(), RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, RageFile::Read(), FileReading::read_8(), FileReading::read_u16_le(), FileReading::read_u32_le(), FileReading::ReadBytes(), RageFile::Seek(), ssprintf(), Swap16LE(), Swap24LE(), Swap32LE(), and ZERO.
Referenced by RageSurface_Load_BMP().
RageSurface_Load_BMP()
RageSurfaceUtils::OpenResult RageSurface_Load_BMP (const RString & sPath, RageSurface *& img, bool bHeaderOnly, RString & error)
References f, RageFile::GetError(), LoadBMP(), RageFile::Open(), RageSurfaceUtils::OPEN_FATAL_ERROR, and RageSurfaceUtils::OPEN_OK.
Referenced by TryOpenFile().