Etterna: ScreenDimensions.cpp File Reference
ScreenDimensions.cpp File Reference
#include "ScreenDimensions.h"
#include "LuaManager.h"
#include "Preference.h"
#include "PrefsManager.h"
#include "ThemeMetric.h"
#include "global.h"
Functions
LuaFunction (GetScreenAspectRatio, PREFSMAN->m_fDisplayAspectRatio)
LuaFunction (GetThemeAspectRatio, ScreenDimensions::GetThemeAspectRatio())
Variables
static ThemeMetric< float > THEME_SCREEN_WIDTH ("Common", "ScreenWidth")
static ThemeMetric< float > THEME_SCREEN_HEIGHT ("Common", "ScreenHeight")
Function Documentation
LuaFunction() [1/2]
LuaFunction (GetScreenAspectRatio , PREFSMAN-> m_fDisplayAspectRatio)
LuaFunction() [2/2]
LuaFunction (GetThemeAspectRatio , ScreenDimensions::GetThemeAspectRatio())
Variable Documentation
THEME_SCREEN_HEIGHT
ThemeMetric<float> THEME_SCREEN_HEIGHT("Common", "ScreenHeight") static
Referenced by ScreenDimensions::GetScreenHeight(), and ScreenDimensions::ReloadScreenDimensions().
THEME_SCREEN_WIDTH
ThemeMetric<float> THEME_SCREEN_WIDTH("Common", "ScreenWidth") static
Referenced by ScreenDimensions::GetScreenWidth(), and ScreenDimensions::ReloadScreenDimensions().