Etterna: RageSoundReader_Chain Class Reference
RageSoundReader_Chain Class Reference
#include <RageSoundReader_Chain.h>
Classes
struct Sound
Public Member Functions
RageSoundReader_Chain ()
~RageSoundReader_Chain () override
RageSoundReader_Chain * Copy () const override
void SetPreferredSampleRate (int iSampleRate)
int LoadSound (RString sPath)
int LoadSound (RageSoundReader *pSound)
void AddSound (int iIndex, float fOffsetSecs, float fPan)
void Finish ()
int GetNumSounds () const
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
int GetSampleRateInternal () const
void ActivateSound (Sound *s)
void ReleaseSound (Sound *s)
Private Attributes
int m_iPreferredSampleRate
int m_iActualSampleRate
unsigned m_iChannels
map< RString, RageSoundReader * > m_apNamedSounds
vector< RageSoundReader * > m_apLoadedSounds
vector< Sound > m_aSounds
int m_iCurrentFrame
unsigned m_iNextSound
vector< Sound * > m_apActiveSounds
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Constructor & Destructor Documentation
RageSoundReader_Chain()
RageSoundReader_Chain::RageSoundReader_Chain ()
References m_iActualSampleRate, m_iChannels, m_iCurrentFrame, m_iNextSound, and m_iPreferredSampleRate.
~RageSoundReader_Chain()
RageSoundReader_Chain::~RageSoundReader_Chain () override
References FOREACH, m_apActiveSounds, m_apLoadedSounds, and ReleaseSound().
Member Function Documentation
ActivateSound()
void RageSoundReader_Chain::ActivateSound (Sound * s) private
References RageSoundReader::Copy(), RageSoundReader_Chain::Sound::fPan, RageSoundReader::GetNumChannels(), GetNumChannels(), RageSoundReader_Chain::Sound::iIndex, m_apActiveSounds, m_apLoadedSounds, RageSoundReader_Chain::Sound::pSound, and RageSoundReader::SetProperty().
Referenced by Read(), and SetPosition().
AddSound()
void RageSoundReader_Chain::AddSound (int iIndex, float fOffsetSecs, float fPan)
References RageSoundReader_Chain::Sound::fPan, RageSoundReader_Chain::Sound::iIndex, RageSoundReader_Chain::Sound::iOffsetMS, m_aSounds, and RageSoundReader_Chain::Sound::pSound.
Referenced by AutoKeysounds::LoadAutoplaySoundsInto().
Copy()
RageSoundReader_Chain * RageSoundReader_Chain::Copy () const override virtual
Implements RageSoundReader.
References FAIL_M.
Finish()
void RageSoundReader_Chain::Finish ()
References FOREACH, GetSampleRateInternal(), RageSoundReader_Chain::Sound::iIndex, LOG, m_apLoadedSounds, m_aSounds, m_iActualSampleRate, m_iChannels, m_iPreferredSampleRate, max(), RageSoundReader_Preload::PreloadSound(), and RageLog::Warn().
GetError()
RString RageSoundReader_Chain::GetError () const inline override virtual
Implements RageSoundReader.
GetLength()
int RageSoundReader_Chain::GetLength () const override virtual
Implements RageSoundReader.
References RageSoundReader::GetLength(), RageSoundReader_Chain::Sound::iIndex, RageSoundReader_Chain::Sound::iOffsetMS, m_apLoadedSounds, m_aSounds, and max().
GetLength_Fast()
int RageSoundReader_Chain::GetLength_Fast () const override virtual
Reimplemented from RageSoundReader.
References RageSoundReader::GetLength_Fast(), RageSoundReader_Chain::Sound::iIndex, RageSoundReader_Chain::Sound::iOffsetMS, m_apLoadedSounds, m_aSounds, and max().
GetNextSourceFrame()
int RageSoundReader_Chain::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References m_iCurrentFrame.
GetNumChannels()
unsigned RageSoundReader_Chain::GetNumChannels () const inline override virtual
Implements RageSoundReader.
References m_iChannels.
Referenced by ActivateSound().
GetNumSounds()
int RageSoundReader_Chain::GetNumSounds () const inline
References m_aSounds.
GetSampleRate()
int RageSoundReader_Chain::GetSampleRate () const inline override virtual
Implements RageSoundReader.
References m_iActualSampleRate.
Referenced by SetPosition().
GetSampleRateInternal()
int RageSoundReader_Chain::GetSampleRateInternal () const private
References FOREACH_CONST, m_apLoadedSounds, and m_iPreferredSampleRate.
Referenced by Finish().
GetStreamToSourceRatio()
float RageSoundReader_Chain::GetStreamToSourceRatio () const override virtual
Implements RageSoundReader.
References f, LOG, m_apActiveSounds, and RageLog::Warn().
LoadSound() [1/2]
int RageSoundReader_Chain::LoadSound (RString sPath)
References FAIL_M, LOG, m_apLoadedSounds, m_apNamedSounds, StdString::CStdStr< CT >::MakeLower(), RageSoundReader_FileReader::OpenFile(), and RageLog::Warn().
Referenced by AutoKeysounds::LoadAutoplaySoundsInto().
LoadSound() [2/2]
int RageSoundReader_Chain::LoadSound (RageSoundReader * pSound)
References m_apLoadedSounds.
Read()
int RageSoundReader_Chain::Read (float * pBuf, int iFrames) override virtual
Implements RageSoundReader.
References ActivateSound(), ARRAYLEN, ASSERT, ASSERT_M, RageSoundReader::END_OF_FILE, RageSoundReader::GetNumChannels(), m_apActiveSounds, m_aSounds, m_iActualSampleRate, m_iChannels, m_iCurrentFrame, m_iNextSound, min(), RageSoundMixBuffer::read(), ReleaseSound(), RageSoundReader::RetriedRead(), RageSoundMixBuffer::SetWriteOffset(), RageSoundMixBuffer::size(), ssprintf(), and RageSoundMixBuffer::write().
ReleaseSound()
void RageSoundReader_Chain::ReleaseSound (Sound * s) private
References ASSERT, m_apActiveSounds, and RageSoundReader_Chain::Sound::pSound.
Referenced by Read(), SetPosition(), and ~RageSoundReader_Chain().
SetPosition()
int RageSoundReader_Chain::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References ActivateSound(), RageSoundReader_Chain::Sound::GetOffsetFrame(), GetSampleRate(), m_apActiveSounds, m_aSounds, m_iCurrentFrame, m_iNextSound, RageSoundReader_Chain::Sound::pSound, ReleaseSound(), and RageSoundReader::SetPosition().
SetPreferredSampleRate()
void RageSoundReader_Chain::SetPreferredSampleRate (int iSampleRate) inline
References m_iPreferredSampleRate.
Referenced by AutoKeysounds::FinishLoading().
SetProperty()
bool RageSoundReader_Chain::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader.
References m_apActiveSounds.
Member Data Documentation
m_apActiveSounds
vector<Sound*> RageSoundReader_Chain::m_apActiveSounds private
Referenced by ActivateSound(), GetStreamToSourceRatio(), Read(), ReleaseSound(), SetPosition(), SetProperty(), and ~RageSoundReader_Chain().
m_apLoadedSounds
vector<RageSoundReader*> RageSoundReader_Chain::m_apLoadedSounds private
Referenced by ActivateSound(), Finish(), GetLength(), GetLength_Fast(), GetSampleRateInternal(), LoadSound(), and ~RageSoundReader_Chain().
m_apNamedSounds
map<RString, RageSoundReader*> RageSoundReader_Chain::m_apNamedSounds private
Referenced by LoadSound().
m_aSounds
vector<Sound> RageSoundReader_Chain::m_aSounds private
Referenced by AddSound(), Finish(), GetLength(), GetLength_Fast(), GetNumSounds(), Read(), and SetPosition().
m_iActualSampleRate
int RageSoundReader_Chain::m_iActualSampleRate private
Referenced by Finish(), GetSampleRate(), RageSoundReader_Chain(), and Read().
m_iChannels
unsigned RageSoundReader_Chain::m_iChannels private
Referenced by Finish(), GetNumChannels(), RageSoundReader_Chain(), and Read().
m_iCurrentFrame
int RageSoundReader_Chain::m_iCurrentFrame private
Referenced by GetNextSourceFrame(), RageSoundReader_Chain(), Read(), and SetPosition().
m_iNextSound
unsigned RageSoundReader_Chain::m_iNextSound private
Referenced by RageSoundReader_Chain(), Read(), and SetPosition().
m_iPreferredSampleRate
int RageSoundReader_Chain::m_iPreferredSampleRate private
Referenced by Finish(), GetSampleRateInternal(), RageSoundReader_Chain(), and SetPreferredSampleRate().
The documentation for this class was generated from the following files:
RageSoundReader_Chain.h
RageSoundReader_Chain.cpp