Etterna: SSC Namespace Reference
SSC Namespace Reference
Classes
struct SongTagInfo
struct StepsTagInfo
Enumerations
enum LoadNoteDataTagIDs {
LNDID_version, LNDID_stepstype, LNDID_chartname, LNDID_description,
LNDID_difficulty, LNDID_meter, LNDID_credit, LNDID_notes,
LNDID_notes2, LNDID_notedata
}
Functions
vector< float > msdsplit (const RString &s)
Enumeration Type Documentation
LoadNoteDataTagIDs
enum SSC::LoadNoteDataTagIDs
Enumerator
LNDID_version
LNDID_stepstype
LNDID_chartname
LNDID_description
LNDID_difficulty
LNDID_meter
LNDID_credit
LNDID_notes
LNDID_notes2
LNDID_notedata
Function Documentation
msdsplit()
vector< float > SSC::msdsplit (const RString & s)
References StringToFloat().
Referenced by SetMSDValues(), and SongCacheIndex::SongFromStatement().