Etterna: Command.cpp File Reference
Command.cpp File Reference
#include "global.h"
#include "Command.h"
#include "Foreach.h"
#include "RageUtil.h"
Functions
static void SplitWithQuotes (const RString sSource, const char Delimitor, vector< RString > &asOut, const bool bIgnoreEmpty)
void ParseCommands (const RString &sCommands, Commands &vCommandsOut, bool bLegacy)
Commands ParseCommands (const RString &sCommands)
Function Documentation
ParseCommands() [1/2]
void ParseCommands (const RString & sCommands, Commands & vCommandsOut, bool bLegacy)
References Command::Load(), split(), SplitWithQuotes(), and Commands::v.
Referenced by GameState::ApplyGameCommand(), ScreenOptionsManageProfiles::BeginScreen(), MusicWheel::BuildWheelItemDatas(), ScreenOptionsMaster::Init(), ScreenSelect::Init(), OptionsList::Load(), OptionRowHandlerList::LoadInternal(), LuaHelpers::ParseCommandList(), and ParseCommands().
ParseCommands() [2/2]
Commands ParseCommands (const RString & sCommands)
References ParseCommands().
SplitWithQuotes()
static void SplitWithQuotes (const RString sSource, const char Delimitor, vector< RString > & asOut, const bool bIgnoreEmpty) static
Referenced by ParseCommands().