Etterna: HighScore Struct Reference
HighScore Struct Reference
The high score that is earned by a player.
#include <HighScore.h>
Public Member Functions
HighScore ()
string GetName () const
Retrieve the name of the player that set the high score.
string GetChartKey () const
int GetSSRCalcVersion () const
Grade GetGrade () const
Retrieve the grade earned from this score.
unsigned int GetScore () const
Retrieve the score earned.
bool IsEmpty () const
Determine if any judgments were tallied during this run.
Grade GetWifeGrade () const
float ConvertDpToWife ()
float GetPercentDP () const
float GetWifeScore () const
float GetWifePoints () const
float GetSSRNormPercent () const
float GetMusicRate () const
float GetJudgeScale () const
bool GetChordCohesion () const
bool GetEtternaValid () const
bool IsUploadedToServer (string s) const
const vector< float > & GetOffsetVector () const
const vector< int > & GetNoteRowVector () const
const vector< int > & GetTrackVector () const
const vector< TapNoteType > & GetTapNoteTypeVector () const
const vector< HoldReplayResult > & GetHoldReplayDataVector () const
vector< float > GetCopyOfOffsetVector () const
vector< int > GetCopyOfNoteRowVector () const
vector< int > GetCopyOfTrackVector () const
vector< TapNoteType > GetCopyOfTapNoteTypeVector () const
vector< HoldReplayResult > GetCopyOfHoldReplayDataVector () const
string GetScoreKey () const
int GetTopScore () const
int GetReplayType () const
float GetSurviveSeconds () const
Determine how many seconds the player had left in Survival mode.
float GetSurvivalSeconds () const
unsigned int GetMaxCombo () const
StageAward GetStageAward () const
PeakComboAward GetPeakComboAward () const
string GetModifiers () const
Get the modifiers used for this run.
DateTime GetDateTime () const
string GetPlayerGuid () const
string GetMachineGuid () const
int GetProductID () const
int GetTapNoteScore (TapNoteScore tns) const
int GetHoldNoteScore (HoldNoteScore tns) const
const RadarValues & GetRadarValues () const
float GetLifeRemainingSeconds () const
bool GetDisqualified () const
Determine if this score was from a situation that would cause disqualification.
void SetName (const string &sName)
Set the name of the Player that earned the score.
void SetChartKey (const string &ck)
void SetSSRCalcVersion (int cv)
void SetGrade (Grade g)
void SetScore (unsigned int iScore)
void SetPercentDP (float f)
void SetWifeScore (float f)
void SetWifePoints (float f)
void SetSSRNormPercent (float f)
void SetMusicRate (float f)
void SetSurviveSeconds (float f)
void SetJudgeScale (float f)
void SetChordCohesion (bool b)
void SetEtternaValid (bool b)
void AddUploadedServer (string s)
void SetOffsetVector (const vector< float > &v)
void SetNoteRowVector (const vector< int > &v)
void SetTrackVector (const vector< int > &v)
void SetTapNoteTypeVector (const vector< TapNoteType > &v)
void SetHoldReplayDataVector (const vector< HoldReplayResult > &v)
void SetScoreKey (const string &ck)
void SetRescoreJudgeVector (const vector< int > &v)
void SetAliveSeconds (float f)
void SetMaxCombo (unsigned int i)
void SetStageAward (StageAward a)
void SetPeakComboAward (PeakComboAward a)
void SetModifiers (const string &s)
void SetDateTime (DateTime d)
void SetPlayerGuid (const string &s)
void SetMachineGuid (const string &s)
void SetProductID (int i)
void SetTapNoteScore (TapNoteScore tns, int i)
void SetHoldNoteScore (HoldNoteScore tns, int i)
void SetRadarValues (const RadarValues &rv)
void SetLifeRemainingSeconds (float f)
void SetDisqualified (bool b)
void SetReplayType (int i)
string * GetNameMutable ()
const string * GetNameMutable () const
void Unset ()
bool operator< (HighScore const &other) const
bool operator> (HighScore const &other) const
bool operator<= (HighScore const &other) const
bool operator>= (HighScore const &other) const
bool operator== (HighScore const &other) const
bool operator!= (HighScore const &other) const
XNode * CreateNode () const
XNode * CreateEttNode () const
void LoadFromNode (const XNode *pNode)
void LoadFromEttNode (const XNode *pNode)
bool WriteReplayData ()
bool WriteInputData (const vector< float > &oop)
bool LoadReplayData ()
bool LoadReplayDataBasic ()
bool LoadReplayDataFull ()
bool HasReplayData ()
void UnloadReplayData ()
void ResetSkillsets ()
bool Is39import () const
string GetDisplayName () const
float RescoreToWifeJudge (int x)
float RescoreToWifeJudgeDuringLoad (int x)
float RescoreToDPJudge (int x)
float GetSkillsetSSR (Skillset ss) const
void SetSkillsetSSR (Skillset ss, float ssr)
void SetValidationKey (ValidationKey vk, string k)
void SetTopScore (int i)
string GenerateValidationKeys ()
string GetValidationKey (ValidationKey vk) const
vector< int > GetRescoreJudgeVector (int x)
void PushSelf (lua_State *L)
Public Attributes
vector< float > timeStamps
string scoreid
int userid
string avatar
int norms = 0
int musics = 0
int judges = 0
Private Attributes
HiddenPtr< HighScoreImpl > m_Impl
Detailed Description
The high score that is earned by a player.
This is scoring data that is persisted between sessions.
Constructor & Destructor Documentation
HighScore()
HighScore::HighScore ()
Member Function Documentation
AddUploadedServer()
void HighScore::AddUploadedServer (string s)
References m_Impl, and HighScoreImpl::uploaded.
Referenced by DownloadManager::UploadScore(), and DownloadManager::UploadScoreWithReplayData().
ConvertDpToWife()
float HighScore::ConvertDpToWife ()
References f, FOREACH_ENUM, HighScoreImpl::fWifeScore, HighScoreImpl::grade, Grade_Failed, HighScoreImpl::iTapNoteScores, m_Impl, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, and wife2().
Referenced by LoadFromNode().
CreateEttNode()
XNode * HighScore::CreateEttNode () const
References HighScoreImpl::CreateEttNode(), and m_Impl.
CreateNode()
XNode * HighScore::CreateNode () const
References HighScoreImpl::CreateNode(), and m_Impl.
Referenced by HighScoreList::CreateNode(), and Screenshot::CreateNode().
GenerateValidationKeys()
string HighScore::GenerateValidationKeys ()
References f, FOREACH_ENUM, GetChartKey(), GetChordCohesion(), GetEtternaValid(), GetHoldNoteScore(), GetJudgeScale(), GetMachineGuid(), GetModifiers(), GetMusicRate(), GetScoreKey(), GetSSRNormPercent(), GetTapNoteScore(), GetWifeGrade(), GradeToString(), picosha2::hash256_hex_string(), HNS_None, judges, musics, norms, SetValidationKey(), TNS_AvoidMine, TNS_CheckpointHit, TNS_CheckpointMiss, TNS_None, and ValidationKey_Brittle.
Referenced by FillInHighScore(), and SetCURLPOSTScore().
GetChartKey()
string HighScore::GetChartKey () const
References HighScoreImpl::ChartKey, and m_Impl.
Referenced by ScoreManager::AddScore(), StageStats::FinalizeScores(), GenerateValidationKeys(), ScoreManager::ImportScore(), ETTProtocol::ReportHighScore(), and SetCURLPOSTScore().
GetChordCohesion()
bool HighScore::GetChordCohesion () const
References HighScoreImpl::bNoChordCohesion, and m_Impl.
Referenced by ScoresAtRate::AddScore(), GenerateValidationKeys(), ScoresAtRate::HandleNoCCPB(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetCopyOfHoldReplayDataVector()
vector< HoldReplayResult > HighScore::GetCopyOfHoldReplayDataVector () const
References m_Impl, and HighScoreImpl::vHoldReplayDataVector.
Referenced by PlayerAI::SetScoreData().
GetCopyOfNoteRowVector()
vector< int > HighScore::GetCopyOfNoteRowVector () const
References m_Impl, and HighScoreImpl::vNoteRowVector.
Referenced by PlayerAI::SetScoreData().
GetCopyOfOffsetVector()
vector< float > HighScore::GetCopyOfOffsetVector () const
References m_Impl, and HighScoreImpl::vOffsetVector.
Referenced by PlayerAI::SetScoreData().
GetCopyOfTapNoteTypeVector()
vector< TapNoteType > HighScore::GetCopyOfTapNoteTypeVector () const
References m_Impl, and HighScoreImpl::vTapNoteTypeVector.
Referenced by PlayerAI::SetScoreData().
GetCopyOfTrackVector()
vector< int > HighScore::GetCopyOfTrackVector () const
References m_Impl, and HighScoreImpl::vTrackVector.
Referenced by PlayerAI::SetScoreData().
GetDateTime()
DateTime HighScore::GetDateTime () const
References HighScoreImpl::dateTime, and m_Impl.
Referenced by FillInHighScore(), LunaHighScore::GetDate(), DBProfile::LoadPlayerScores(), Screenshot::operator<(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), Profile::SetAnyAchievedGoals(), and SetCURLPOSTScore().
GetDisplayName()
string HighScore::GetDisplayName () const
References EMPTY_NAME, and GetName().
GetDisqualified()
bool HighScore::GetDisqualified () const
Determine if this score was from a situation that would cause disqualification.
Returns
true if the score would be disqualified, false otherwise.
References HighScoreImpl::bDisqualified, and m_Impl.
GetEtternaValid()
bool HighScore::GetEtternaValid () const
References HighScoreImpl::bEtternaValid, and m_Impl.
Referenced by FillInHighScore(), GenerateValidationKeys(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), SetCURLPOSTScore(), and LunaHighScore::ToggleEtternaValidation().
GetGrade()
Grade HighScore::GetGrade () const
Retrieve the grade earned from this score.
Returns
the grade.
References HighScoreImpl::grade, and m_Impl.
Referenced by Profile::GetGrades(), GameState::GetRankingFeats(), Profile::HasPassedSteps(), DBProfile::LoadPlayerScores(), and SetCURLPOSTScore().
GetHoldNoteScore()
int HighScore::GetHoldNoteScore (HoldNoteScore tns) const
References HighScoreImpl::iHoldNoteScores, and m_Impl.
Referenced by Profile::CalculateStatsFromScores(), GenerateValidationKeys(), LunaHighScore::GetHoldNoteScore(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetHoldReplayDataVector()
const vector< HoldReplayResult > & HighScore::GetHoldReplayDataVector () const
References m_Impl, and HighScoreImpl::vHoldReplayDataVector.
GetJudgeScale()
float HighScore::GetJudgeScale () const
References HighScoreImpl::fJudgeScale, and m_Impl.
Referenced by GenerateValidationKeys(), LunaHighScore::GetJudgeScale(), and DBProfile::SavePlayerScores().
GetLifeRemainingSeconds()
float HighScore::GetLifeRemainingSeconds () const
References HighScoreImpl::fLifeRemainingSeconds, and m_Impl.
Referenced by GetSurvivalSeconds().
GetMachineGuid()
string HighScore::GetMachineGuid () const
References m_Impl, and HighScoreImpl::sMachineGuid.
Referenced by GenerateValidationKeys(), ETTProtocol::ReportHighScore(), and SetCURLPOSTScore().
GetMaxCombo()
unsigned int HighScore::GetMaxCombo () const
References HighScoreImpl::iMaxCombo, and m_Impl.
Referenced by LunaHighScore::GetJudgmentString(), LunaHighScore::GetMaxCombo(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetModifiers()
string HighScore::GetModifiers () const
Get the modifiers used for this run.
Returns
the modifiers.
References m_Impl, and HighScoreImpl::sModifiers.
Referenced by GenerateValidationKeys(), LunaHighScore::GetModifiers(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetMusicRate()
float HighScore::GetMusicRate () const
References HighScoreImpl::fMusicRate, and m_Impl.
Referenced by ScoresForChart::AddScore(), StageStats::FinalizeScores(), GenerateValidationKeys(), LunaHighScore::GetMusicRate(), LunaScreenSelectMusic::PlayReplay(), ETTProtocol::ReportHighScore(), and LunaScreenSelectMusic::ShowEvalScreenForScore().
GetName()
string HighScore::GetName () const
Retrieve the name of the player that set the high score.
Returns
the name of the player.
References m_Impl, and HighScoreImpl::sName.
Referenced by GetDisplayName(), LunaHighScore::GetName(), PaneDisplay::GetPaneTextAndLevel(), GameState::GetRankingFeats(), and LunaHighScore::IsFillInMarker().
GetNameMutable() [1/2]
string * HighScore::GetNameMutable ()
References m_Impl, and HighScoreImpl::sName.
Referenced by GetNameMutable().
GetNameMutable() [2/2]
const string* HighScore::GetNameMutable () const inline
References GetNameMutable().
GetNoteRowVector()
const vector< int > & HighScore::GetNoteRowVector () const
References m_Impl, and HighScoreImpl::vNoteRowVector.
Referenced by LunaHighScore::GetNoteRowVector(), DBProfile::SavePlayerScores(), and DBProfile::WriteReplayData().
GetOffsetVector()
const vector< float > & HighScore::GetOffsetVector () const
References m_Impl, and HighScoreImpl::vOffsetVector.
Referenced by LunaHighScore::GetOffsetVector(), DBProfile::SavePlayerScores(), DownloadManager::UploadScoreWithReplayData(), and DBProfile::WriteReplayData().
GetPeakComboAward()
PeakComboAward HighScore::GetPeakComboAward () const
References m_Impl, and HighScoreImpl::peakComboAward.
GetPercentDP()
float HighScore::GetPercentDP () const
References HighScoreImpl::fPercentDP, and m_Impl.
Referenced by ProfileManager::AddStepsScore(), PaneDisplay::GetPaneTextAndLevel(), LunaHighScore::GetPercentDP(), GameState::GetRankingFeats(), and Profile::GetSongsActual().
GetPlayerGuid()
string HighScore::GetPlayerGuid () const
References m_Impl, and HighScoreImpl::sPlayerGuid.
GetProductID()
int HighScore::GetProductID () const
References HighScoreImpl::iProductID, and m_Impl.
GetRadarValues()
const RadarValues & HighScore::GetRadarValues () const
References m_Impl, and HighScoreImpl::radarValues.
Referenced by LunaHighScore::GetRadarValues().
GetReplayType()
int HighScore::GetReplayType () const
References m_Impl, and HighScoreImpl::ReplayType.
Referenced by PlayerAI::GetTapNoteOffsetForReplay(), and PlayerAI::SetScoreData().
GetRescoreJudgeVector()
vector< int > HighScore::GetRescoreJudgeVector (int x)
References m_Impl, RescoreToDPJudge(), and HighScoreImpl::vRescoreJudgeVector.
Referenced by LunaHighScore::RescoreJudges().
GetScore()
unsigned int HighScore::GetScore () const
Retrieve the score earned.
Returns
the score.
References HighScoreImpl::iScore, and m_Impl.
Referenced by ScreenSelectMusic::AfterStepsOrTrailChange(), GameState::GetRankingFeats(), and LunaHighScore::GetScore().
GetScoreKey()
string HighScore::GetScoreKey () const
References m_Impl, and HighScoreImpl::ScoreKey.
Referenced by ScoresAtRate::AddScore(), ScoreManager::AddToKeyedIndex(), ScoresAtRate::CreateNode(), StageStats::FinalizeScores(), GenerateValidationKeys(), DBProfile::LoadPlayerScores(), LunaScreenSelectMusic::PlayReplay(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), Profile::SetAnyAchievedGoals(), SetCURLPOSTScore(), LunaScreenSelectMusic::ShowEvalScreenForScore(), and DBProfile::WriteReplayData().
GetSkillsetSSR()
float HighScore::GetSkillsetSSR (Skillset ss) const
References HighScoreImpl::fSkillsetSSRs, and m_Impl.
Referenced by LunaHighScore::GetSkillsetSSR(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), ScoresForChart::SetTopScores(), and ScoreManager::SortTopSSRPtrs().
GetSSRCalcVersion()
int HighScore::GetSSRCalcVersion () const
References m_Impl, and HighScoreImpl::SSRCalcVersion.
Referenced by ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetSSRNormPercent()
float HighScore::GetSSRNormPercent () const
References HighScoreImpl::fSSRNormPercent, and m_Impl.
Referenced by ScoresAtRate::AddScore(), FillInHighScore(), GenerateValidationKeys(), ScoresAtRate::HandleNoCCPB(), ScoresAtRate::LoadFromNode(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and ETTProtocol::Update().
GetStageAward()
StageAward HighScore::GetStageAward () const
References m_Impl, and HighScoreImpl::stageAward.
GetSurvivalSeconds()
float HighScore::GetSurvivalSeconds () const
References GetLifeRemainingSeconds(), and GetSurviveSeconds().
Referenced by Profile::CalculateStatsFromScores(), and LunaHighScore::GetSurvivalSeconds().
GetSurviveSeconds()
float HighScore::GetSurviveSeconds () const
Determine how many seconds the player had left in Survival mode.
Returns
the number of seconds left.
References HighScoreImpl::fSurviveSeconds, and m_Impl.
Referenced by GetSurvivalSeconds(), and DBProfile::SavePlayerScores().
GetTapNoteScore()
int HighScore::GetTapNoteScore (TapNoteScore tns) const
References HighScoreImpl::iTapNoteScores, and m_Impl.
Referenced by Profile::CalculateStatsFromScores(), GenerateValidationKeys(), LunaHighScore::GetJudgmentString(), LunaHighScore::GetTapNoteScore(), Profile::ImportScoresToEtterna(), ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetTapNoteTypeVector()
const vector< TapNoteType > & HighScore::GetTapNoteTypeVector () const
References m_Impl, and HighScoreImpl::vTapNoteTypeVector.
Referenced by LunaHighScore::GetTapNoteTypeVector(), and DownloadManager::UploadScoreWithReplayData().
GetTopScore()
int HighScore::GetTopScore () const
References m_Impl, and HighScoreImpl::TopScore.
Referenced by ScoreManager::AddScore(), ETTProtocol::ReportHighScore(), and SetCURLPOSTScore().
GetTrackVector()
const vector< int > & HighScore::GetTrackVector () const
References m_Impl, and HighScoreImpl::vTrackVector.
Referenced by LunaHighScore::GetTrackVector(), and DownloadManager::UploadScoreWithReplayData().
GetValidationKey()
string HighScore::GetValidationKey (ValidationKey vk) const
References m_Impl, and HighScoreImpl::ValidationKeys.
Referenced by ETTProtocol::ReportHighScore(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetWifeGrade()
Grade HighScore::GetWifeGrade () const
References HighScoreImpl::GetWifeGrade(), and m_Impl.
Referenced by HighScoreList::AddHighScore(), ScoresAtRate::AddScore(), ScoresForChart::AddScore(), GenerateValidationKeys(), DBProfile::LoadPlayerScores(), DBProfile::SavePlayerScores(), and SetCURLPOSTScore().
GetWifePoints()
float HighScore::GetWifePoints () const
References HighScoreImpl::fWifePoints, and m_Impl.
Referenced by LunaHighScore::GetWifePoints(), and SetCURLPOSTScore().
GetWifeScore()
float HighScore::GetWifeScore () const
References HighScoreImpl::fWifeScore, and m_Impl.
Referenced by ScoreGoal::CheckVacuity(), LunaHighScore::GetWifeScore(), Player::Load(), DBProfile::LoadPlayerScores(), operator<(), DBProfile::SavePlayerScores(), Profile::SetAnyAchievedGoals(), SetCURLPOSTScore(), and LunaScreenSelectMusic::ShowEvalScreenForScore().
HasReplayData()
bool HighScore::HasReplayData ()
References BASIC_REPLAY_DIR, DoesFileExist(), FULL_REPLAY_DIR, m_Impl, and HighScoreImpl::ScoreKey.
Is39import()
bool HighScore::Is39import () const
References HighScoreImpl::is39import, and m_Impl.
IsEmpty()
bool HighScore::IsEmpty () const
Determine if any judgments were tallied during this run.
Returns
true if no judgments were recorded, false otherwise.
References HNS_Held, HighScoreImpl::iHoldNoteScores, HighScoreImpl::iTapNoteScores, m_Impl, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
IsUploadedToServer()
bool HighScore::IsUploadedToServer (string s) const
References m_Impl, and HighScoreImpl::uploaded.
LoadFromEttNode()
void HighScore::LoadFromEttNode (const XNode * pNode)
References HighScoreImpl::fSSRNormPercent, HighScoreImpl::fWifeScore, HighScoreImpl::grade, Grade_Failed, HighScoreImpl::LoadFromEttNode(), m_Impl, RescoreToWifeJudgeDuringLoad(), HighScoreImpl::vNoteRowVector, and HighScoreImpl::vOffsetVector.
LoadFromNode()
void HighScore::LoadFromNode (const XNode * pNode)
References HighScoreImpl::bEtternaValid, ConvertDpToWife(), HighScoreImpl::fSSRNormPercent, HighScoreImpl::fWifeScore, HighScoreImpl::grade, Grade_Failed, HighScoreImpl::LoadFromNode(), m_Impl, RescoreToWifeJudgeDuringLoad(), HighScoreImpl::vNoteRowVector, and HighScoreImpl::vOffsetVector.
Referenced by Screenshot::LoadFromNode().
LoadReplayData()
bool HighScore::LoadReplayData ()
References LoadReplayDataBasic(), and LoadReplayDataFull().
Referenced by LunaHighScore::GetNoteRowVector(), LunaHighScore::GetOffsetVector(), LunaHighScore::GetTapNoteTypeVector(), LunaHighScore::GetTrackVector(), RescoreToWifeJudge(), RescoreToWifeJudgeDuringLoad(), DBProfile::SavePlayerScores(), PlayerAI::SetScoreData(), and LunaScreenSelectMusic::ShowEvalScreenForScore().
LoadReplayDataBasic()
bool HighScore::LoadReplayDataBasic ()
References BASIC_REPLAY_DIR, LOG, m_Impl, HighScoreImpl::ReplayType, HighScoreImpl::ScoreKey, SetNoteRowVector(), SetOffsetVector(), RageLog::Trace(), HighScoreImpl::vNoteRowVector, HighScoreImpl::vOffsetVector, and RageLog::Warn().
Referenced by LoadReplayData().
LoadReplayDataFull()
bool HighScore::LoadReplayDataFull ()
References FULL_REPLAY_DIR, LOG, m_Impl, NUM_TapNoteSubType, HighScoreImpl::ReplayType, HoldReplayResult::row, HighScoreImpl::ScoreKey, SetNoteRowVector(), SetOffsetVector(), SetTapNoteTypeVector(), SetTrackVector(), HoldReplayResult::subType, TapNoteSubType_Hold, TapNoteType_Invalid, TapNoteType_Tap, RageLog::Trace(), HoldReplayResult::track, HighScoreImpl::vNoteRowVector, HighScoreImpl::vOffsetVector, HighScoreImpl::vTrackVector, and RageLog::Warn().
Referenced by LoadReplayData().
operator!=()
bool HighScore::operator!= (HighScore const & other) const
References operator==().
operator<()
bool HighScore::operator< (HighScore const & other) const
References GetWifeScore().
Referenced by operator>=().
operator<=()
bool HighScore::operator<= (HighScore const & other) const
References operator>().
operator==()
bool HighScore::operator== (HighScore const & other) const
References m_Impl.
Referenced by operator!=().
operator>()
bool HighScore::operator> (HighScore const & other) const
Referenced by operator<=().
operator>=()
bool HighScore::operator>= (HighScore const & other) const
References operator<().
PushSelf()
void HighScore::PushSelf (lua_State * L)
Referenced by LunaScoreManager::GetMostRecentScore(), LunaScoreGoal::GetPBUpTo(), LunaScoresAtRate::GetScores(), and LunaScoreManager::GetTopSSRHighScore().
RescoreToDPJudge()
float HighScore::RescoreToDPJudge (int x)
References f, FOREACH_CONST, HNS_Held, HNS_LetGo, HNS_Missed, HighScoreImpl::iHoldNoteScores, HighScoreImpl::iTapNoteScores, m_Impl, RadarCategory_Holds, RadarCategory_Rolls, HighScoreImpl::radarValues, SetRescoreJudgeVector(), TNS_HitMine, and HighScoreImpl::vOffsetVector.
Referenced by GetRescoreJudgeVector(), and LunaHighScore::RescoreToDPJudge().
RescoreToWifeJudge()
float HighScore::RescoreToWifeJudge (int x)
References f, HighScoreImpl::fWifeScore, HNS_LetGo, HNS_Missed, HighScoreImpl::iHoldNoteScores, HighScoreImpl::iTapNoteScores, LoadReplayData(), m_Impl, HighScoreImpl::ReplayType, TNS_HitMine, HighScoreImpl::vOffsetVector, and wife2().
Referenced by FillInHighScore(), and LunaHighScore::RescoreToWifeJudge().
RescoreToWifeJudgeDuringLoad()
float HighScore::RescoreToWifeJudgeDuringLoad (int x)
References f, HighScoreImpl::fWifeScore, HNS_LetGo, HNS_Missed, HighScoreImpl::iHoldNoteScores, HighScoreImpl::iTapNoteScores, LoadReplayData(), m_Impl, HighScoreImpl::ReplayType, TNS_HitMine, UnloadReplayData(), HighScoreImpl::vOffsetVector, and wife2().
Referenced by LoadFromEttNode(), and LoadFromNode().
ResetSkillsets()
void HighScore::ResetSkillsets ()
References m_Impl, and HighScoreImpl::ResetSkillsets().
SetAliveSeconds()
void HighScore::SetAliveSeconds (float f)
References f, HighScoreImpl::fSurviveSeconds, and m_Impl.
Referenced by FillInHighScore(), and MakeRandomHighScore().
SetChartKey()
void HighScore::SetChartKey (const string & ck)
References HighScoreImpl::ChartKey, and m_Impl.
Referenced by FillInHighScore(), Profile::ImportScoresToEtterna(), DBProfile::LoadPlayerScores(), and ETTProtocol::Update().
SetChordCohesion()
void HighScore::SetChordCohesion (bool b)
References HighScoreImpl::bNoChordCohesion, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), and ETTProtocol::Update().
SetDateTime()
void HighScore::SetDateTime (DateTime d)
References HighScoreImpl::dateTime, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), MakeRandomHighScore(), and ETTProtocol::Update().
SetDisqualified()
void HighScore::SetDisqualified (bool b)
References HighScoreImpl::bDisqualified, and m_Impl.
Referenced by FillInHighScore().
SetEtternaValid()
void HighScore::SetEtternaValid (bool b)
References HighScoreImpl::bEtternaValid, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), LunaHighScore::ToggleEtternaValidation(), and ETTProtocol::Update().
SetGrade()
void HighScore::SetGrade (Grade g)
References HighScoreImpl::grade, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), MakeRandomHighScore(), and ETTProtocol::Update().
SetHoldNoteScore()
void HighScore::SetHoldNoteScore (HoldNoteScore tns, int i)
References HighScoreImpl::iHoldNoteScores, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), MakeRandomHighScore(), and ETTProtocol::Update().
SetHoldReplayDataVector()
void HighScore::SetHoldReplayDataVector (const vector< HoldReplayResult > & v)
References m_Impl, and HighScoreImpl::vHoldReplayDataVector.
Referenced by FillInHighScore().
SetJudgeScale()
void HighScore::SetJudgeScale (float f)
References f, HighScoreImpl::fJudgeScale, and m_Impl.
Referenced by FillInHighScore(), and DBProfile::LoadPlayerScores().
SetLifeRemainingSeconds()
void HighScore::SetLifeRemainingSeconds (float f)
References f, HighScoreImpl::fLifeRemainingSeconds, and m_Impl.
Referenced by FillInHighScore().
SetMachineGuid()
void HighScore::SetMachineGuid (const string & s)
References m_Impl, and HighScoreImpl::sMachineGuid.
Referenced by FillInHighScore(), and MakeRandomHighScore().
SetMaxCombo()
void HighScore::SetMaxCombo (unsigned int i)
References HighScoreImpl::iMaxCombo, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), and ETTProtocol::Update().
SetModifiers()
void HighScore::SetModifiers (const string & s)
References m_Impl, and HighScoreImpl::sModifiers.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), MakeRandomHighScore(), and ETTProtocol::Update().
SetMusicRate()
void HighScore::SetMusicRate (float f)
References f, HighScoreImpl::fMusicRate, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), and ETTProtocol::Update().
SetName()
void HighScore::SetName (const string & sName)
Set the name of the Player that earned the score.
Parameters
sName the name of the Player.
References m_Impl, and HighScoreImpl::sName.
Referenced by ProfileManager::AddCategoryScore(), ProfileManager::AddStepsScore(), FillInHighScore(), DownloadManager::MakeAThing(), and MakeRandomHighScore().
SetNoteRowVector()
void HighScore::SetNoteRowVector (const vector< int > & v)
References m_Impl, and HighScoreImpl::vNoteRowVector.
Referenced by FillInHighScore(), LoadReplayDataBasic(), LoadReplayDataFull(), and ETTProtocol::Update().
SetOffsetVector()
void HighScore::SetOffsetVector (const vector< float > & v)
References m_Impl, and HighScoreImpl::vOffsetVector.
Referenced by FillInHighScore(), LoadReplayDataBasic(), LoadReplayDataFull(), and ETTProtocol::Update().
SetPeakComboAward()
void HighScore::SetPeakComboAward (PeakComboAward a)
References m_Impl, and HighScoreImpl::peakComboAward.
Referenced by FillInHighScore().
SetPercentDP()
void HighScore::SetPercentDP (float f)
References f, HighScoreImpl::fPercentDP, and m_Impl.
Referenced by ProfileManager::AddStepsScore(), FillInHighScore(), and MakeRandomHighScore().
SetPlayerGuid()
void HighScore::SetPlayerGuid (const string & s)
References m_Impl, and HighScoreImpl::sPlayerGuid.
Referenced by FillInHighScore(), and MakeRandomHighScore().
SetProductID()
void HighScore::SetProductID (int i)
References HighScoreImpl::iProductID, and m_Impl.
Referenced by MakeRandomHighScore().
SetRadarValues()
void HighScore::SetRadarValues (const RadarValues & rv)
References m_Impl, and HighScoreImpl::radarValues.
Referenced by FillInHighScore(), ScreenEvaluation::Init(), and MakeRandomHighScore().
SetReplayType()
void HighScore::SetReplayType (int i)
References m_Impl, and HighScoreImpl::ReplayType.
Referenced by FillInHighScore().
SetRescoreJudgeVector()
void HighScore::SetRescoreJudgeVector (const vector< int > & v)
References m_Impl, and HighScoreImpl::vRescoreJudgeVector.
Referenced by RescoreToDPJudge().
SetScore()
void HighScore::SetScore (unsigned int iScore)
References HighScoreImpl::iScore, and m_Impl.
Referenced by FillInHighScore(), and MakeRandomHighScore().
SetScoreKey()
void HighScore::SetScoreKey (const string & ck)
References m_Impl, and HighScoreImpl::ScoreKey.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), and ETTProtocol::Update().
SetSkillsetSSR()
void HighScore::SetSkillsetSSR (Skillset ss, float ssr)
References HighScoreImpl::fSkillsetSSRs, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), and ETTProtocol::Update().
SetSSRCalcVersion()
void HighScore::SetSSRCalcVersion (int cv)
References m_Impl, and HighScoreImpl::SSRCalcVersion.
Referenced by FillInHighScore(), and DBProfile::LoadPlayerScores().
SetSSRNormPercent()
void HighScore::SetSSRNormPercent (float f)
References f, HighScoreImpl::fSSRNormPercent, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), and ETTProtocol::Update().
SetStageAward()
void HighScore::SetStageAward (StageAward a)
References m_Impl, and HighScoreImpl::stageAward.
Referenced by FillInHighScore().
SetSurviveSeconds()
void HighScore::SetSurviveSeconds (float f)
References f, HighScoreImpl::fSurviveSeconds, and m_Impl.
Referenced by DBProfile::LoadPlayerScores().
SetTapNoteScore()
void HighScore::SetTapNoteScore (TapNoteScore tns, int i)
References HighScoreImpl::iTapNoteScores, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), MakeRandomHighScore(), and ETTProtocol::Update().
SetTapNoteTypeVector()
void HighScore::SetTapNoteTypeVector (const vector< TapNoteType > & v)
References m_Impl, and HighScoreImpl::vTapNoteTypeVector.
Referenced by FillInHighScore(), and LoadReplayDataFull().
SetTopScore()
void HighScore::SetTopScore (int i)
References m_Impl, and HighScoreImpl::TopScore.
Referenced by ScoresForChart::AddScore(), and StageStats::FinalizeScores().
SetTrackVector()
void HighScore::SetTrackVector (const vector< int > & v)
References m_Impl, and HighScoreImpl::vTrackVector.
Referenced by FillInHighScore(), and LoadReplayDataFull().
SetValidationKey()
void HighScore::SetValidationKey (ValidationKey vk, string k)
References m_Impl, and HighScoreImpl::ValidationKeys.
Referenced by GenerateValidationKeys(), and DBProfile::LoadPlayerScores().
SetWifePoints()
void HighScore::SetWifePoints (float f)
References f, HighScoreImpl::fWifePoints, and m_Impl.
Referenced by FillInHighScore().
SetWifeScore()
void HighScore::SetWifeScore (float f)
References f, HighScoreImpl::fWifeScore, and m_Impl.
Referenced by FillInHighScore(), DBProfile::LoadPlayerScores(), DownloadManager::MakeAThing(), and ETTProtocol::Update().
UnloadReplayData()
void HighScore::UnloadReplayData ()
References m_Impl, and HighScoreImpl::UnloadReplayData().
Referenced by StageStats::FinalizeScores(), LunaHighScore::GetNoteRowVector(), LunaHighScore::GetOffsetVector(), LunaHighScore::GetTapNoteTypeVector(), LunaHighScore::GetTrackVector(), RescoreToWifeJudgeDuringLoad(), and DBProfile::SavePlayerScores().
Unset()
void HighScore::Unset ()
References m_Impl.
WriteInputData()
bool HighScore::WriteInputData (const vector< float > & oop)
References append, ASSERT, FULL_REPLAY_DIR, LOG, m_Impl, HighScoreImpl::ScoreKey, RageLog::Trace(), and RageLog::Warn().
Referenced by FillInHighScore().
WriteReplayData()
bool HighScore::WriteReplayData ()
References m_Impl, and HighScoreImpl::WriteReplayData().
Referenced by StageStats::FinalizeScores().
Member Data Documentation
avatar
string HighScore::avatar
Referenced by LunaHighScore::GetAvatar(), and DownloadManager::MakeAThing().
judges
int HighScore::judges = 0
Referenced by GenerateValidationKeys(), and SetCURLPOSTScore().
m_Impl
HiddenPtr<HighScoreImpl> HighScore::m_Impl private
Referenced by AddUploadedServer(), ConvertDpToWife(), CreateEttNode(), CreateNode(), GetChartKey(), GetChordCohesion(), GetCopyOfHoldReplayDataVector(), GetCopyOfNoteRowVector(), GetCopyOfOffsetVector(), GetCopyOfTapNoteTypeVector(), GetCopyOfTrackVector(), GetDateTime(), GetDisqualified(), GetEtternaValid(), GetGrade(), GetHoldNoteScore(), GetHoldReplayDataVector(), GetJudgeScale(), GetLifeRemainingSeconds(), GetMachineGuid(), GetMaxCombo(), GetModifiers(), GetMusicRate(), GetName(), GetNameMutable(), GetNoteRowVector(), GetOffsetVector(), GetPeakComboAward(), GetPercentDP(), GetPlayerGuid(), GetProductID(), GetRadarValues(), GetReplayType(), GetRescoreJudgeVector(), GetScore(), GetScoreKey(), GetSkillsetSSR(), GetSSRCalcVersion(), GetSSRNormPercent(), GetStageAward(), GetSurviveSeconds(), GetTapNoteScore(), GetTapNoteTypeVector(), GetTopScore(), GetTrackVector(), GetValidationKey(), GetWifeGrade(), GetWifePoints(), GetWifeScore(), HasReplayData(), Is39import(), IsEmpty(), IsUploadedToServer(), LoadFromEttNode(), LoadFromNode(), LoadReplayDataBasic(), LoadReplayDataFull(), operator==(), RescoreToDPJudge(), RescoreToWifeJudge(), RescoreToWifeJudgeDuringLoad(), ResetSkillsets(), SetAliveSeconds(), SetChartKey(), SetChordCohesion(), SetDateTime(), SetDisqualified(), SetEtternaValid(), SetGrade(), SetHoldNoteScore(), SetHoldReplayDataVector(), SetJudgeScale(), SetLifeRemainingSeconds(), SetMachineGuid(), SetMaxCombo(), SetModifiers(), SetMusicRate(), SetName(), SetNoteRowVector(), SetOffsetVector(), SetPeakComboAward(), SetPercentDP(), SetPlayerGuid(), SetProductID(), SetRadarValues(), SetReplayType(), SetRescoreJudgeVector(), SetScore(), SetScoreKey(), SetSkillsetSSR(), SetSSRCalcVersion(), SetSSRNormPercent(), SetStageAward(), SetSurviveSeconds(), SetTapNoteScore(), SetTapNoteTypeVector(), SetTopScore(), SetTrackVector(), SetValidationKey(), SetWifePoints(), SetWifeScore(), UnloadReplayData(), Unset(), WriteInputData(), and WriteReplayData().
musics
int HighScore::musics = 0
Referenced by GenerateValidationKeys(), and SetCURLPOSTScore().
norms
int HighScore::norms = 0
Referenced by GenerateValidationKeys(), and SetCURLPOSTScore().
scoreid
string HighScore::scoreid
Referenced by LunaHighScore::GetScoreid(), and DownloadManager::MakeAThing().
timeStamps
vector<float> HighScore::timeStamps
Referenced by StageStats::FinalizeScores(), and DownloadManager::UploadScoreWithReplayData().
userid
int HighScore::userid
Referenced by LunaHighScore::GetUserid(), and DownloadManager::MakeAThing().
The documentation for this struct was generated from the following files:
HighScore.h
HighScore.cpp