Etterna: RageUtil_CharConversions.h File Reference
RageUtil_CharConversions.h File Reference
#include "global.h"
Functions
bool ConvertString (RString &str, const RString &encodings)
Function Documentation
ConvertString()
bool ConvertString (RString & str, const RString & encodings)
References AttemptEnglishConversion(), AttemptJapaneseConversion(), AttemptKoreanConversion(), split(), RageException::Throw(), and Rage::utf8_is_valid().
Referenced by BMSSongLoader::AddToSong(), DWILoader::LoadFromDir(), LoadTags(), and OsuLoader::SetMetadata().