Etterna: InputHandler_MacOSX_HID Class Reference
InputHandler_MacOSX_HID Class Reference
#include <InputHandler_MacOSX_HID.h>
Public Member Functions
InputHandler_MacOSX_HID ()
~InputHandler_MacOSX_HID ()
bool DevicesChanged ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
RString GetDeviceSpecificInputString (const DeviceInput &di)
wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Public Member Functions
static void QueueCallback (void *target, int result, void *refcon, void *sender)
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Private Member Functions
void StartDevices ()
void AddDevices (int usagePage, int usage, InputDevice &id)
Static Private Member Functions
static int Run (void *data)
static void DeviceAdded (void *refCon, io_iterator_t iter)
static void DeviceChanged (void *refCon, io_service_t service, natural_t messageType, void *arg)
Private Attributes
vector< HIDDevice * > m_vDevices
RageThread m_InputThread
RageSemaphore m_Sem
CFRunLoopRef m_LoopRef
CFRunLoopSourceRef m_SourceRef
vector< io_iterator_t > m_vIters
IONotificationPortRef m_NotifyPort
RageMutex m_ChangeLock
bool m_bChanged
Additional Inherited Members
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_MacOSX_HID()
InputHandler_MacOSX_HID::InputHandler_MacOSX_HID ()
References AddDevices(), RageThread::Create(), DEVICE_JOY1, DEVICE_KEYBOARD, DEVICE_MOUSE, DEVICE_PUMP1, LOG, m_bChanged, PrefsManager::m_bThreadedInput, m_InputThread, m_LoopRef, m_NotifyPort, m_Sem, PREFSMAN, Run(), RageThread::SetName(), StartDevices(), RageLog::Trace(), and RageSemaphore::Wait().
~InputHandler_MacOSX_HID()
InputHandler_MacOSX_HID::~InputHandler_MacOSX_HID ()
References FOREACH, LOG, PrefsManager::m_bThreadedInput, m_InputThread, m_LoopRef, m_NotifyPort, m_SourceRef, m_vDevices, m_vIters, PREFSMAN, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
AddDevices()
void InputHandler_MacOSX_HID::AddDevices (int usagePage, int usage, InputDevice & id) private
References DeviceAdded(), DeviceChanged(), enum_add(), GetMatchingDictionary(), LOG, m_NotifyPort, m_vDevices, m_vIters, MakeDevice(), and RageLog::Trace().
Referenced by InputHandler_MacOSX_HID().
DeviceAdded()
void InputHandler_MacOSX_HID::DeviceAdded (void * refCon, io_iterator_t iter) static private
References LockMut, m_bChanged, and m_ChangeLock.
Referenced by AddDevices().
DeviceButtonToChar()
wchar_t InputHandler_MacOSX_HID::DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers) virtual
Reimplemented from InputHandler.
References InputHandler::ApplyKeyModifiers(), InputHandler::DeviceButtonToChar(), KEY_DEL, KEY_DOWN, KEY_END, KEY_ENTER, KEY_ESC, KEY_F1, KEY_F16, KEY_HOME, KEY_KP_ENTER, KEY_LEFT, KEY_NUMLOCK, KEY_PAUSE, KEY_PGDN, KEY_PGUP, KEY_PRTSC, KEY_RIGHT, KEY_SCRLLOCK, KEY_TAB, KEY_UP, KeyCodeToChar(), L, MOUSE_LEFT, MOUSE_RIGHT, MOUSE_WHEELDOWN, MOUSE_WHEELUP, MOUSE_X_LEFT, MOUSE_X_RIGHT, MOUSE_Y_DOWN, and MOUSE_Y_UP.
DeviceChanged()
void InputHandler_MacOSX_HID::DeviceChanged (void * refCon, io_service_t service, natural_t messageType, void * arg) static private
References LockMut, m_bChanged, and m_ChangeLock.
Referenced by AddDevices().
DevicesChanged()
bool InputHandler_MacOSX_HID::DevicesChanged () inline virtual
Reimplemented from InputHandler.
References LockMut, and m_bChanged.
GetDevicesAndDescriptions()
void InputHandler_MacOSX_HID::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References FOREACH_CONST, and m_vDevices.
GetDeviceSpecificInputString()
RString InputHandler_MacOSX_HID::GetDeviceSpecificInputString (const DeviceInput & di) virtual
Reimplemented from InputHandler.
References DeviceInput::button, DeviceInput::device, DEVICE_KEYBOARD, DEVICE_PUMP1, DEVICE_PUMP2, InputHandler::GetDeviceSpecificInputString(), JOY_BUTTON_1, JOY_BUTTON_10, JOY_BUTTON_11, JOY_BUTTON_2, JOY_BUTTON_3, JOY_BUTTON_4, JOY_BUTTON_5, JOY_BUTTON_6, JOY_BUTTON_7, JOY_BUTTON_8, JOY_BUTTON_9, KEY_BACK, KEY_DEL, KEY_ENTER, KEY_INSERT, KEY_LALT, KEY_LMETA, KEY_RALT, KEY_RMETA, and OTHER.
QueueCallback()
void InputHandler_MacOSX_HID::QueueCallback (void * target, int result, void * refcon, void * sender) static
References InputFilter::ButtonPressed(), FOREACH_CONST, INPUTFILTER, and m_vDevices.
Referenced by StartDevices().
Run()
int InputHandler_MacOSX_HID::Run (void * data) static private
References f, LOG, m_LoopRef, m_Sem, m_SourceRef, RunLoopStarted(), StartDevices(), RageLog::Trace(), and RageLog::Warn().
Referenced by InputHandler_MacOSX_HID().
StartDevices()
void InputHandler_MacOSX_HID::StartDevices () private
References ASSERT, FOREACH, m_LoopRef, m_NotifyPort, m_vDevices, and QueueCallback().
Referenced by InputHandler_MacOSX_HID(), and Run().
Member Data Documentation
m_bChanged
bool InputHandler_MacOSX_HID::m_bChanged private
Referenced by DeviceAdded(), DeviceChanged(), DevicesChanged(), and InputHandler_MacOSX_HID().
m_ChangeLock
RageMutex InputHandler_MacOSX_HID::m_ChangeLock private
Referenced by DeviceAdded(), and DeviceChanged().
m_InputThread
RageThread InputHandler_MacOSX_HID::m_InputThread private
Referenced by InputHandler_MacOSX_HID(), and ~InputHandler_MacOSX_HID().
m_LoopRef
CFRunLoopRef InputHandler_MacOSX_HID::m_LoopRef private
Referenced by InputHandler_MacOSX_HID(), Run(), StartDevices(), and ~InputHandler_MacOSX_HID().
m_NotifyPort
IONotificationPortRef InputHandler_MacOSX_HID::m_NotifyPort private
Referenced by AddDevices(), InputHandler_MacOSX_HID(), StartDevices(), and ~InputHandler_MacOSX_HID().
m_Sem
RageSemaphore InputHandler_MacOSX_HID::m_Sem private
Referenced by InputHandler_MacOSX_HID(), and Run().
m_SourceRef
CFRunLoopSourceRef InputHandler_MacOSX_HID::m_SourceRef private
Referenced by Run(), and ~InputHandler_MacOSX_HID().
m_vDevices
vector<HIDDevice*> InputHandler_MacOSX_HID::m_vDevices private
Referenced by AddDevices(), GetDevicesAndDescriptions(), QueueCallback(), StartDevices(), and ~InputHandler_MacOSX_HID().
m_vIters
vector<io_iterator_t> InputHandler_MacOSX_HID::m_vIters private
Referenced by AddDevices(), and ~InputHandler_MacOSX_HID().
The documentation for this class was generated from the following files:
InputHandler_MacOSX_HID.h
InputHandler_MacOSX_HID.cpp