Etterna: RageSoundReader_Preload Class Reference
RageSoundReader_Preload Class Reference
#include <RageSoundReader_Preload.h>
Public Member Functions
RageSoundReader_Preload ()
bool Open (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuffer, int iLength) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RString GetError () const override
int GetReferenceCount () const
RageSoundReader_Preload * Copy () const override
~RageSoundReader_Preload () override=default
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Static Public Member Functions
static bool PreloadSound (RageSoundReader *&pSound)
Private Member Functions
int GetTotalFrames () const
Private Attributes
AutoPtrCopyOnWrite< RString > m_Buffer
bool m_bBufferIs16Bit { false }
int m_iPosition { 0 }
int m_iSampleRate { 0 }
unsigned m_iChannels { 0 }
float m_fRate { 0.0f }
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Constructor & Destructor Documentation
RageSoundReader_Preload()
RageSoundReader_Preload::RageSoundReader_Preload ()
References g_bSoundPreload16bit, Preference< T >::Get(), and m_bBufferIs16Bit.
Referenced by Copy(), and PreloadSound().
~RageSoundReader_Preload()
RageSoundReader_Preload::~RageSoundReader_Preload () override default
Member Function Documentation
Copy()
RageSoundReader_Preload * RageSoundReader_Preload::Copy () const override virtual
Implements RageSoundReader.
References RageSoundReader_Preload().
Referenced by RageSoundManager::AddLoadedSound().
GetError()
RString RageSoundReader_Preload::GetError () const inline override virtual
Implements RageSoundReader.
GetLength()
int RageSoundReader_Preload::GetLength () const override virtual
Implements RageSoundReader.
References f, GetTotalFrames(), and m_iSampleRate.
Referenced by GetLength_Fast().
GetLength_Fast()
int RageSoundReader_Preload::GetLength_Fast () const override virtual
Reimplemented from RageSoundReader.
References GetLength().
GetNextSourceFrame()
int RageSoundReader_Preload::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References m_fRate, and m_iPosition.
GetNumChannels()
unsigned RageSoundReader_Preload::GetNumChannels () const inline override virtual
Implements RageSoundReader.
References m_iChannels.
GetReferenceCount()
int RageSoundReader_Preload::GetReferenceCount () const
References m_Buffer.
GetSampleRate()
int RageSoundReader_Preload::GetSampleRate () const inline override virtual
Implements RageSoundReader.
References m_iSampleRate.
GetStreamToSourceRatio()
float RageSoundReader_Preload::GetStreamToSourceRatio () const inline override virtual
Implements RageSoundReader.
References m_fRate.
GetTotalFrames()
int RageSoundReader_Preload::GetTotalFrames () const private
References framesize, and m_Buffer.
Referenced by GetLength().
Open()
bool RageSoundReader_Preload::Open (RageSoundReader * pSource)
References ARRAYLEN, ASSERT, RageSoundUtil::ConvertFloatToNativeInt16(), RageSoundReader::END_OF_FILE, g_iSoundPreloadMaxSamples, Preference< T >::Get(), RageSoundReader::GetLength_Fast(), RageSoundReader::GetNumChannels(), RageSoundReader::GetSampleRate(), RageSoundReader::GetStreamToSourceRatio(), m_bBufferIs16Bit, m_Buffer, m_fRate, m_iChannels, m_iPosition, m_iSampleRate, RageSoundReader::Read(), and samplesize.
PreloadSound()
bool RageSoundReader_Preload::PreloadSound (RageSoundReader *& pSound) static
References RageSoundReader_Preload(), and RageSoundReader::SetPosition().
Referenced by RageSoundReader_Chain::Finish(), and RageSound::Load().
Read()
int RageSoundReader_Preload::Read (float * pBuffer, int iLength) override virtual
Implements RageSoundReader.
References RageSoundUtil::ConvertNativeInt16ToFloat(), RageSoundReader::END_OF_FILE, framesize, m_bBufferIs16Bit, m_Buffer, m_iChannels, m_iPosition, and min().
SetPosition()
int RageSoundReader_Preload::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References framesize, m_Buffer, m_fRate, and m_iPosition.
Member Data Documentation
m_bBufferIs16Bit
bool RageSoundReader_Preload::m_bBufferIs16Bit { false } private
Referenced by Open(), RageSoundReader_Preload(), and Read().
m_Buffer
AutoPtrCopyOnWrite<RString> RageSoundReader_Preload::m_Buffer private
Referenced by GetReferenceCount(), GetTotalFrames(), Open(), Read(), and SetPosition().
m_fRate
float RageSoundReader_Preload::m_fRate { 0.0f } private
Referenced by GetNextSourceFrame(), GetStreamToSourceRatio(), Open(), and SetPosition().
m_iChannels
unsigned RageSoundReader_Preload::m_iChannels { 0 } private
Referenced by GetNumChannels(), Open(), and Read().
m_iPosition
int RageSoundReader_Preload::m_iPosition { 0 } private
Referenced by GetNextSourceFrame(), Open(), Read(), and SetPosition().
m_iSampleRate
int RageSoundReader_Preload::m_iSampleRate { 0 } private
Referenced by GetLength(), GetSampleRate(), and Open().
The documentation for this class was generated from the following files:
RageSoundReader_Preload.h
RageSoundReader_Preload.cpp