Etterna: ScreenNetRoom.cpp File Reference
ScreenNetRoom.cpp File Reference
#include "global.h"
#include "GameState.h"
#include "InputEventPlus.h"
#include "LocalizedString.h"
#include "NetworkSyncManager.h"
#include "ScreenManager.h"
#include "ScreenNetRoom.h"
#include "ScreenTextEntry.h"
#include "ThemeManager.h"
#include "WheelItemBase.h"
#include "LuaBinding.h"
Classes
class LunaScreenNetRoom
Allow Lua to have access to the PlayerState.
Functions
AutoScreenMessage (SM_SMOnlinePack)
AutoScreenMessage (SM_BackFromRoomName)
AutoScreenMessage (SM_BackFromRoomDesc)
AutoScreenMessage (SM_BackFromRoomPass)
AutoScreenMessage (SM_BackFromReqPass)
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage (SM_RoomInfoDeploy)
AutoScreenMessage (ETTP_Disconnect)
AutoScreenMessage (ETTP_RoomsChange)
REGISTER_SCREEN_CLASS (ScreenNetRoom)
Variables
static LocalizedString ENTER_ROOM_DESCRIPTION ("ScreenNetRoom", "Enter a description for the room:")
static LocalizedString ENTER_ROOM_PASSWORD ("ScreenNetRoom", "Enter a password for the room (blank, no password):")
static LocalizedString ENTER_ROOM_REQPASSWORD ("ScreenNetRoom", "Enter Room's Password:")
Function Documentation
AutoScreenMessage() [1/9]
AutoScreenMessage (SM_SMOnlinePack)
AutoScreenMessage() [2/9]
AutoScreenMessage (SM_BackFromRoomName)
AutoScreenMessage() [3/9]
AutoScreenMessage (SM_BackFromRoomDesc)
AutoScreenMessage() [4/9]
AutoScreenMessage (SM_BackFromRoomPass)
AutoScreenMessage() [5/9]
AutoScreenMessage (SM_BackFromReqPass)
AutoScreenMessage() [6/9]
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage() [7/9]
AutoScreenMessage (SM_RoomInfoDeploy)
AutoScreenMessage() [8/9]
AutoScreenMessage (ETTP_Disconnect)
AutoScreenMessage() [9/9]
AutoScreenMessage (ETTP_RoomsChange)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenNetRoom)
Variable Documentation
ENTER_ROOM_DESCRIPTION
LocalizedString ENTER_ROOM_DESCRIPTION("ScreenNetRoom", "Enter a description for the room:") static
Referenced by ScreenNetRoom::HandleScreenMessage().
ENTER_ROOM_PASSWORD
LocalizedString ENTER_ROOM_PASSWORD("ScreenNetRoom", "Enter a password for the room (blank, no password):") static
Referenced by ScreenNetRoom::HandleScreenMessage().
ENTER_ROOM_REQPASSWORD
LocalizedString ENTER_ROOM_REQPASSWORD("ScreenNetRoom", "Enter Room's Password:") static
Referenced by ScreenNetRoom::SelectCurrent().