Etterna: Character.cpp File Reference
Character.cpp File Reference
#include "global.h"
#include "Character.h"
#include "ActorUtil.h"
#include "IniFile.h"
#include "RageTextureID.h"
#include "RageUtil.h"
#include "LuaBinding.h"
Classes
class LunaCharacter
Allow Lua to have access to the Character.
Functions
RString GetRandomFileInDir (const RString &sDir)
Function Documentation
GetRandomFileInDir()
RString GetRandomFileInDir (const RString & sDir)
References GetDirListing(), and RandomInt().
Referenced by Character::GetDanceAnimationPath(), Character::GetRestAnimationPath(), and Character::GetWarmUpAnimationPath().