Etterna: DownloadManager.cpp File Reference
DownloadManager.cpp File Reference
#include "global.h"
#include "CommandLineActions.h"
#include "DownloadManager.h"
#include "Foreach.h"
#include "GamePreferences.h"
#include "GameState.h"
#include "Grade.h"
#include "PlayerStageStats.h"
#include "Preference.h"
#include "ProfileManager.h"
#include "RageFile.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageString.h"
#include "ScoreManager.h"
#include "ScreenInstallOverlay.h"
#include "ScreenManager.h"
#include "ScreenNetSelectMusic.h"
#include "ScreenSelectMusic.h"
#include "Song.h"
#include "SongManager.h"
#include "SpecialFiles.h"
#include "curl/curl.h"
#include <FilterManager.h>
#include <nlohmann/json.hpp>
#include <unordered_set>
#include "LuaBinding.h"
#include "LuaManager.h"
Classes
class ReadThis
class LunaDownloadManager
Allow Lua to have access to the ProfileManager.
class LunaPacklist
class LunaDownloadablePack
class LunaDownload
Typedefs
using json = nlohmann::json
Functions
size_t write_memory_buffer (void *contents, size_t size, size_t nmemb, void *userp)
string ComputerIdentity ()
size_t ReadThisReadCallback (void *dest, size_t size, size_t nmemb, void *userp)
int ReadThisSeekCallback (void *arg, curl_off_t offset, int origin)
int progressfunc (void *clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
size_t write_data (void *dlBuffer, size_t size, size_t nmemb, void *pnf)
bool ends_with (std::string const &value, std::string const &ending)
Determine if the source string ends with the specified content.
bool starts_with (std::string const &value, std::string const &start)
Determine if the source string begins with the specified content.
void checkProtocol (string &url)
CURL * initBasicCURLHandle ()
CURL * initCURLHandle (bool withBearer)
bool addFileToForm (curl_httppost *&form, curl_httppost *&lastPtr, string field, string fileName, string filePath, RString &contents)
void SetCURLResultsString (CURL *curlHandle, string *str)
void CURLFormPostField (CURL *curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, const char *field, const char *value)
void SetCURLFormPostField (CURL *curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, char *field, char *value)
void SetCURLFormPostField (CURL *curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, const char *field, string value)
void SetCURLFormPostField (CURL *curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, string field, string value)
template<typename T >
void SetCURLFormPostField (CURL *curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, string field, T value)
void EmptyTempDLFileDir ()
void SetCURLPOSTScore (CURL *&curlHandle, curl_httppost *&form, curl_httppost *&lastPtr, HighScore *&hs)
std::vector< std::string > split (const std::string &s, char delimiter)
float mythicalmathymathsProbablyUnderratedness (string chartkey)
float overratedness (string chartkey)
bool findStringIC (const std::string &strHaystack, const std::string &strNeedle)
Try to find in the Haystack the Needle - ignore case.
Variables
shared_ptr< DownloadManager > DLMAN = nullptr
static Preference< unsigned int > maxDLPerSecond ("maximumBytesDownloadedPerSecond", 0)
static Preference< unsigned int > maxDLPerSecondGameplay ("maximumBytesDownloadedPerSecondDuringGameplay", 1000000)
static Preference< RString > packListURL ("PackListURL", "https://api.etternaonline.com/v2/packs")
static Preference< RString > serverURL ("BaseAPIURL", "https://api.etternaonline.com/v2")
static Preference< unsigned int > automaticSync ("automaticScoreSync", 1)
static Preference< unsigned int > downloadPacksToAdditionalSongs ("downloadPacksToAdditionalSongs", 0)
static const string TEMP_ZIP_MOUNT_POINT = "/@temp-zip/"
static const string CLIENT_DATA_KEY
static const string DL_DIR = SpecialFiles::CACHE_DIR + "Downloads/"
Typedef Documentation
json
using json = nlohmann::json
Function Documentation
addFileToForm()
bool addFileToForm (curl_httppost *& form, curl_httppost *& lastPtr, string field, string fileName, string filePath, RString & contents) inline
References RageFile::Close(), RageFile::GetFileSize(), RageFile::Open(), and RageFile::Read().
checkProtocol()
void checkProtocol (string & url) inline
References starts_with().
Referenced by DownloadManager::SetCURLURL().
ComputerIdentity()
string ComputerIdentity ()
CURLFormPostField()
void CURLFormPostField (CURL * curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, const char * field, const char * value)
Referenced by SetCURLFormPostField(), and DownloadManager::UploadScore().
EmptyTempDLFileDir()
void EmptyTempDLFileDir () inline
References DL_DIR, FILEMAN, RageFileManager::GetDirListing(), RageFileManager::IsAFile(), and RageFileManager::Remove().
Referenced by DownloadManager::DownloadManager(), and DownloadManager::~DownloadManager().
ends_with()
bool ends_with (std::string const & value, std::string const & ending) inline
Determine if the source string ends with the specified content.
References Rage::tail().
Referenced by Song::TidyUpData().
findStringIC()
bool findStringIC (const std::string & strHaystack, const std::string & strNeedle)
Try to find in the Haystack the Needle - ignore case.
Referenced by LunaPacklist::FilterAndSearch().
initBasicCURLHandle()
CURL* initBasicCURLHandle () inline
References L.
Referenced by Download::Download(), and initCURLHandle().
initCURLHandle()
CURL* initCURLHandle (bool withBearer) inline
References DLMAN, and initBasicCURLHandle().
Referenced by DownloadManager::RefreshTop25(), DownloadManager::UploadScore(), and DownloadManager::UploadScoreWithReplayData().
mythicalmathymathsProbablyUnderratedness()
float mythicalmathymathsProbablyUnderratedness (string chartkey)
References DLMAN, and Skill_Overall.
overratedness()
float overratedness (string chartkey)
References DLMAN, f, min(), and Skill_Overall.
progressfunc()
int progressfunc (void * clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
References ProgressData::total.
Referenced by Download::Download().
ReadThisReadCallback()
size_t ReadThisReadCallback (void * dest, size_t size, size_t nmemb, void * userp)
References ReadThis::file, and RageFile::Read().
ReadThisSeekCallback()
int ReadThisSeekCallback (void * arg, curl_off_t offset, int origin)
SetCURLFormPostField() [1/4]
void SetCURLFormPostField (CURL * curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, char * field, char * value) inline
References CURLFormPostField().
Referenced by SetCURLPOSTScore(), and DownloadManager::UploadScoreWithReplayData().
SetCURLFormPostField() [2/4]
void SetCURLFormPostField (CURL * curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, const char * field, string value) inline
References CURLFormPostField().
SetCURLFormPostField() [3/4]
void SetCURLFormPostField (CURL * curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, string field, string value) inline
References CURLFormPostField().
SetCURLFormPostField() [4/4]
template<typename T > void SetCURLFormPostField (CURL * curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, string field, T value) inline
References CURLFormPostField().
SetCURLPOSTScore()
void SetCURLPOSTScore (CURL *& curlHandle, curl_httppost *& form, curl_httppost *& lastPtr, HighScore *& hs) inline
References HighScore::GenerateValidationKeys(), HighScore::GetChartKey(), HighScore::GetChordCohesion(), HighScore::GetDateTime(), HighScore::GetEtternaValid(), HighScore::GetGrade(), HighScore::GetHoldNoteScore(), HighScore::GetMachineGuid(), HighScore::GetMaxCombo(), HighScore::GetModifiers(), HighScore::GetScoreKey(), HighScore::GetSSRCalcVersion(), SongManager::GetStepsByChartkey(), DateTime::GetString(), HighScore::GetTapNoteScore(), HighScore::GetTopScore(), HighScore::GetValidationKey(), HighScore::GetWifeGrade(), HighScore::GetWifePoints(), HighScore::GetWifeScore(), GradeToString(), HNS_Held, HNS_LetGo, HNS_Missed, HighScore::judges, HighScore::musics, HighScore::norms, SetCURLFormPostField(), SONGMAN, StepsType_dance_single, TNS_HitMine, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, and ValidationKey_Brittle.
Referenced by DownloadManager::UploadScore(), and DownloadManager::UploadScoreWithReplayData().
SetCURLResultsString()
void SetCURLResultsString (CURL * curlHandle, string * str) inline
References write_memory_buffer().
split()
std::vector<std::string> split (const std::string & s, char delimiter)
Referenced by FilenameDB::AddFile(), ScreenServiceAction::BeginScreen(), MusicWheel::BuildWheelItemDatas(), InputMapper::CheckForChangedInputDevicesAndRemap(), RageSoundDriver_JACK::ConnectPorts(), ConvertString(), LoadingWindow::Create(), RageMovieTexture::Create(), RageSoundDriver::Create(), InputHandler::Create(), CreateDirectories(), CreateDisplay(), Song::FinalizeLoading(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), SongOptions::FromString(), RadarValues::FromString(), PlayerOptions::FromString(), NetworkSyncManager::GetCurrentSMBuild(), GetCustomDifficulty(), GetDirOfExecutable(), NotesWriterSM::GetEditFileContents(), NotesWriterSSC::GetEditFileContents(), PlayerOptions::GetLocalizedMods(), GetMountDir(), RageFileDriver::GetPathValue(), GetSMNotesTag(), GetSSCNoteData(), RageDisplay_GLES2::Init(), ScreenSelect::Init(), ScreenOptionsMaster::Init(), ScreenMapControllers::Init(), ScreenSelectMaster::Init(), RageDisplay_Legacy::Init(), Screen::Init(), InputQueueCodeSet::Load(), Command::Load(), ModIcon::Load(), Character::Load(), MusicWheel::Load(), InputQueueCode::Load(), OptionsList::Load(), Font::Load(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), LoadFromSMNoteDataStringWithPlayer(), Song::LoadFromSongDir(), LoadGlobalData(), LoadTags(), LuaFunc_get_sound_driver_list(), Song::Matches(), SMLoader::ParseBPMs(), ParseCommands(), SMLoader::ParseStops(), SMALoader::ProcessBeatsPerMeasure(), SMLoader::ProcessBGChanges(), SSCLoader::ProcessBPMs(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SMLoader::ProcessInstrumentTracks(), SSCLoader::ProcessLabels(), SMALoader::ProcessMultipliers(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SMLoader::ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), SSCLoader::ProcessWarps(), ThemeMetricDifficultiesToShow::Read(), ImageCache::ReadFromDisk(), InputMappings::ReadMappings(), ScreenManager::ReloadOverlayScreens(), RemoveStepsTypes(), FilenameDB::ResolvePath(), SetFGChanges(), ModIconRow::SetFromGameState(), SetKeysounds(), SetRadarValues(), LoadingWindow_Win32::SetTextInternal(), BitmapText::SetTextInternal(), LunaHelpDisplay::SetTipsColonSeparated(), sm_main(), SMSetFGChanges(), SMSetKeysounds(), Song::Song(), SongCacheIndex::SongFromStatement(), SortNoteSkins(), actor_template_t::store_cmd(), Song::TidyUpData(), RageLog::Write(), and RageLog::~RageLog().
starts_with()
bool starts_with (std::string const & value, std::string const & start) inline
Determine if the source string begins with the specified content.
References Rage::head().
Referenced by checkProtocol(), and Song::TidyUpData().
write_data()
size_t write_data (void * dlBuffer, size_t size, size_t nmemb, void * pnf)
References RageFileWrapper::stop.
Referenced by Download::Download().
write_memory_buffer()
size_t write_memory_buffer (void * contents, size_t size, size_t nmemb, void * userp)
References append.
Referenced by SetCURLResultsString().
Variable Documentation
automaticSync
Preference<unsigned int> automaticSync("automaticScoreSync", 1) static
Referenced by DownloadManager::ShouldUploadScores().
CLIENT_DATA_KEY
const string CLIENT_DATA_KEY static
Initial value:
=
  "4406B28A97B326DA5346A9885B0C9DEE8D66F89B562CF5E337AC04C17EB95C40"
DL_DIR
const string DL_DIR = SpecialFiles::CACHE_DIR + "Downloads/" static
Referenced by EmptyTempDLFileDir(), and Download::MakeTempFileName().
DLMAN
shared_ptr<DownloadManager> DLMAN = nullptr
Referenced by DownloadManager::AddFavorite(), DownloadManager::AddGoal(), Profile::AddGoal(), ScreenSelectMusic::CheckBackgroundRequests(), DoInstalls(), Download::Download(), LunaDownloadablePack::DownloadAndInstall(), DownloadManager::DownloadAndInstallPack(), DownloadManager::DownloadCoreBundle(), LunaDownloadManager::DownloadCoreBundle(), LunaPacklist::FilterAndSearch(), StageStats::FinalizeScores(), LunaDownloadManager::GetCoreBundle(), LunaDownloadablePack::GetDownload(), LunaDownloadManager::GetDownloadingPacks(), LunaDownloadManager::GetDownloads(), LunaDownloadManager::GetLastVersion(), LunaDownloadManager::GetPacklist(), LunaDownloadManager::GetRegisterPage(), LunaDownloadManager::GetSkillsetRank(), LunaDownloadManager::GetSkillsetRating(), LunaDownloadManager::GetToken(), LunaDownloadManager::GetTopChartScore(), LunaDownloadManager::GetTopChartScoreCount(), LunaDownloadManager::GetTopSkillsetScore(), LunaDownloadManager::GetUsername(), ScreenSelectMusic::HandleScreenMessage(), initCURLHandle(), ScreenSelectMusic::Input(), Download::Install(), InstallSmzipOsArg(), LunaDownloadManager::IsLoggedIn(), LunaDownloadablePack::IsQueued(), LunaDownloadManager::Login(), LunaDownloadManager::LoginWithToken(), LunaDownloadManager::Logout(), DownloadManager::MakeAThing(), mythicalmathymathsProbablyUnderratedness(), DownloadManager::OnLogin(), overratedness(), DownloadManager::RefreshCoreBundles(), DownloadManager::RefreshFavourites(), DownloadManager::RefreshPackList(), DownloadManager::RefreshTop25(), DownloadManager::RefreshUserData(), DownloadManager::RefreshUserRank(), DownloadManager::RemoveFavorite(), DownloadManager::RemoveGoal(), Profile::RemoveGoal(), DownloadManager::RequestChartLeaderBoard(), GameLoop::RunGameLoop(), ScreenGameplay::ScreenGameplay(), ScreenSelectMusic::SelectCurrent(), DownloadManager::SendRequestToURL(), Profile::SetAnyAchievedGoals(), LunaPacklist::SetFromAll(), LunaPacklist::SetFromCoreBundle(), ShutdownGame(), sm_main(), ScreenInstallOverlay::Update(), DownloadManager::UpdateGoal(), DownloadManager::UpdatePacks(), ScoreGoal::UploadIfNotVacuous(), DownloadManager::UploadScore(), DownloadManager::UploadScoreWithReplayData(), and ScreenGameplay::~ScreenGameplay().
downloadPacksToAdditionalSongs
Preference<unsigned int> downloadPacksToAdditionalSongs("downloadPacksToAdditionalSongs", 0) static
Referenced by DownloadManager::InstallSmzip().
maxDLPerSecond
Preference<unsigned int> maxDLPerSecond("maximumBytesDownloadedPerSecond", 0) static
Referenced by DownloadManager::UpdateDLSpeed().
maxDLPerSecondGameplay
Preference<unsigned int> maxDLPerSecondGameplay("maximumBytesDownloadedPerSecondDuringGameplay", 1000000) static
Referenced by DownloadManager::UpdateDLSpeed().
packListURL
Preference<RString> packListURL("PackListURL", "https://api.etternaonline.com/v2/packs") static
Referenced by DownloadManager::init().
serverURL
Preference<RString> serverURL("BaseAPIURL", "https://api.etternaonline.com/v2") static
Referenced by DownloadManager::SendRequest(), DownloadManager::UploadScore(), DownloadManager::UploadScores(), and DownloadManager::UploadScoreWithReplayData().
TEMP_ZIP_MOUNT_POINT
const string TEMP_ZIP_MOUNT_POINT = "/@temp-zip/" static
Referenced by DownloadManager::InstallSmzip().