Etterna: RageFileDriverDeflate.cpp File Reference
RageFileDriverDeflate.cpp File Reference
#include "global.h"
#include "RageFileDriverDeflate.h"
#include "RageFile.h"
#include "RageFileDriverSlice.h"
#include "RageUtil.h"
#include <memory>
#include <zlib.h>
#include "RageFileDriverMemory.h"
Macros
#define FTEXT 1 << 0
#define FHCRC 1 << 1
#define FEXTRA 1 << 2
#define FNAME 1 << 3
#define FCOMMENT 1 << 4
#define UNSUPPORTED_MASK ~((1 << 5) - 1)
Functions
RageFileObjInflate * GunzipFile (RageFileBasic *pFile_, RString &sError, uint32_t *iCRC32)
void GzipString (const RString &sIn, RString &sOut)
bool GunzipString (const RString &sIn, RString &sOut, RString &sError)
Macro Definition Documentation
FCOMMENT
#define FCOMMENT 1 << 4
Referenced by GunzipFile().
FEXTRA
#define FEXTRA 1 << 2
Referenced by GunzipFile().
FHCRC
#define FHCRC 1 << 1
Referenced by GunzipFile().
FNAME
#define FNAME 1 << 3
Referenced by GunzipFile().
FTEXT
#define FTEXT 1 << 0
UNSUPPORTED_MASK
#define UNSUPPORTED_MASK ~((1 << 5) - 1)
Referenced by GunzipFile().
Function Documentation
GunzipFile()
RageFileObjInflate* GunzipFile (RageFileBasic * pFile_, RString & sError, uint32_t * iCRC32)
References ASSERT, RageFileDriverSlice::DeleteFileWhenFinished(), RageFileObjInflate::DeleteFileWhenFinished(), RageFileObj::EnableCRC32(), FCOMMENT, FEXTRA, FHCRC, FNAME, FileReading::read_16_le(), FileReading::read_32_le(), FileReading::read_8(), FileReading::read_u16_le(), FileReading::read_u32_le(), FileReading::ReadBytes(), FileReading::Seek(), FileReading::SkipBytes(), ssprintf(), and UNSUPPORTED_MASK.
Referenced by GunzipString(), XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), and XMLProfile::LoadStatsXmlForConversion().
GunzipString()
bool GunzipString (const RString & sIn, RString & sOut, RString & sError)
References ASSERT, RageFileBasic::GetCRC32(), GunzipFile(), RageFileObjMem::PutString(), RageFileBasic::Read(), and SAFE_DELETE.
GzipString()
void GzipString (const RString & sIn, RString & sOut)
References RageFileObjGzip::Finish(), RageFileObjMem::GetString(), RageFileObjGzip::Start(), and RageFileObj::Write().