Etterna: ScreenMessageHelpers Namespace Reference
ScreenMessageHelpers Namespace Reference
Helpers for the ScreenMessages.
Functions
ScreenMessage ToScreenMessage (const RString &Name)
RString ScreenMessageToString (ScreenMessage SM)
Detailed Description
Helpers for the ScreenMessages.
Function Documentation
ScreenMessageToString()
RString ScreenMessageHelpers::ScreenMessageToString (ScreenMessage SM)
References FOREACHM, and m_pScreenMessages.
Referenced by ScreenGameplay::HandleScreenMessage(), and Screen::Update().
ToScreenMessage()
ScreenMessage ScreenMessageHelpers::ToScreenMessage (const RString & Name)
References m_pScreenMessages.
Referenced by LunaScreenManager::AddNewScreenToTop(), ScreenTextEntry::TextEntrySettings::FromStack(), LunaScreen::PostScreenMessage(), and LunaScreenWithMenuElements::StartTransitioningScreen().