Etterna: DebugLineRestartCurrentScreen Class Reference
DebugLineRestartCurrentScreen Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
bool ForceOffAfterUse () const override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineRestartCurrentScreen::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References Screen::BeginScreen(), IDebugLine::DoAndLog(), ScreenManager::GetTopScreen(), and SCREENMAN.
ForceOffAfterUse()
bool DebugLineRestartCurrentScreen::ForceOffAfterUse () const inline override private virtual
Reimplemented from IDebugLine.
GetDisplayTitle()
RString DebugLineRestartCurrentScreen::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and RESTART.
GetDisplayValue()
RString DebugLineRestartCurrentScreen::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References Actor::GetName(), ScreenManager::GetTopScreen(), and SCREENMAN.
GetPageName()
RString DebugLineRestartCurrentScreen::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineRestartCurrentScreen::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp