Etterna: RageWorkerThread Class Reference
RageWorkerThread Class Reference abstract
#include <RageUtil_WorkerThread.h>
Public Member Functions
RageWorkerThread (const RString &sName)
virtual ~RageWorkerThread ()
void SetTimeout (float fSeconds)
bool TimeoutEnabled () const
bool IsTimedOut () const
bool WaitForOneHeartbeat ()
Protected Member Functions
void StartThread ()
void StopThread ()
bool DoRequest (int iRequest)
virtual void HandleRequest (int iRequest)=0
virtual void RequestTimedOut ()
void SetHeartbeat (float fSeconds)
virtual void DoHeartbeat ()
Private Types
enum { REQ_SHUTDOWN = -1, REQ_NONE = -2 }
Private Member Functions
void WorkerMain ()
Static Private Member Functions
static int StartWorkerMain (void *pThis)
Private Attributes
RageThread m_WorkerThread
RageEvent m_WorkerEvent
RString m_sName
int m_iRequest
bool m_bRequestFinished
bool m_bTimedOut
RageTimer m_Timeout
float m_fHeartbeat
RageTimer m_NextHeartbeat
RageEvent m_HeartbeatEvent
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
REQ_SHUTDOWN
REQ_NONE
Constructor & Destructor Documentation
RageWorkerThread()
RageWorkerThread::RageWorkerThread (const RString & sName)
References m_bRequestFinished, m_bTimedOut, m_fHeartbeat, m_iRequest, m_sName, m_Timeout, m_WorkerThread, REQ_NONE, RageThread::SetName(), and RageTimer::SetZero().
~RageWorkerThread()
RageWorkerThread::~RageWorkerThread () virtual
References ASSERT, RageThread::IsCreated(), and m_WorkerThread.
Member Function Documentation
DoHeartbeat()
virtual void RageWorkerThread::DoHeartbeat () inline protected virtual
Referenced by WorkerMain().
DoRequest()
bool RageWorkerThread::DoRequest (int iRequest) protected
References ASSERT, RageEvent::Broadcast(), RageTimer::IsZero(), RageMutex::Lock(), LOG, m_bRequestFinished, m_bTimedOut, m_iRequest, m_sName, m_Timeout, m_WorkerEvent, REQ_NONE, REQ_SHUTDOWN, RageMutex::Unlock(), RageEvent::Wait(), and RageLog::Warn().
Referenced by ThreadedFileWorker::Close(), ThreadedFileWorker::Copy(), ThreadedFileWorker::Flush(), ThreadedFileWorker::FlushDirCache(), ThreadedFileWorker::GetFD(), ThreadedFileWorker::GetFileSize(), ThreadedFileWorker::Move(), ThreadedFileWorker::Open(), ThreadedFileWorker::PopulateFileSet(), ThreadedFileWorker::Read(), ThreadedFileWorker::Remove(), ThreadedFileWorker::Seek(), StopThread(), and ThreadedFileWorker::Write().
HandleRequest()
virtual void RageWorkerThread::HandleRequest (int iRequest) protected pure virtual
Implemented in ThreadedFileWorker.
Referenced by WorkerMain().
IsTimedOut()
bool RageWorkerThread::IsTimedOut () const inline
References m_bTimedOut.
Referenced by ThreadedFileWorker::Close(), ThreadedFileWorker::Copy(), ThreadedFileWorker::Flush(), ThreadedFileWorker::FlushDirCache(), ThreadedFileWorker::GetFD(), ThreadedFileWorker::GetFileSize(), ThreadedFileWorker::Move(), ThreadedFileWorker::Open(), ThreadedFileWorker::PopulateFileSet(), ThreadedFileWorker::Read(), ThreadedFileWorker::Remove(), ThreadedFileWorker::Seek(), and ThreadedFileWorker::Write().
RequestTimedOut()
virtual void RageWorkerThread::RequestTimedOut () inline protected virtual
Reimplemented in ThreadedFileWorker.
Referenced by WorkerMain().
SetHeartbeat()
void RageWorkerThread::SetHeartbeat (float fSeconds) inline protected
References m_fHeartbeat, m_NextHeartbeat, and RageTimer::Touch().
SetTimeout()
void RageWorkerThread::SetTimeout (float fSeconds)
References RageMutex::Lock(), m_Timeout, m_WorkerEvent, RageTimer::SetZero(), RageTimer::Touch(), and RageMutex::Unlock().
Referenced by ThreadedFileWorker::FlushDirCache(), and StopThread().
StartThread()
void RageWorkerThread::StartThread () protected
References ASSERT, RageThread::Create(), RageThread::IsCreated(), m_WorkerThread, and StartWorkerMain().
Referenced by ThreadedFileWorker::ThreadedFileWorker().
StartWorkerMain()
static int RageWorkerThread::StartWorkerMain (void * pThis) inline static private
Referenced by StartThread().
StopThread()
void RageWorkerThread::StopThread () protected
References DoRequest(), RageMutex::Lock(), LOG, m_bTimedOut, m_sName, m_WorkerEvent, m_WorkerThread, REQ_SHUTDOWN, SetTimeout(), RageLog::Trace(), RageMutex::Unlock(), RageThread::Wait(), and RageEvent::Wait().
Referenced by ThreadedFileWorker::~ThreadedFileWorker().
TimeoutEnabled()
bool RageWorkerThread::TimeoutEnabled () const inline
References RageTimer::IsZero(), and m_Timeout.
Referenced by ThreadedFileWorker::FlushDirCache().
WaitForOneHeartbeat()
bool RageWorkerThread::WaitForOneHeartbeat ()
References ASSERT, RageMutex::Lock(), m_fHeartbeat, m_HeartbeatEvent, m_Timeout, RageMutex::Unlock(), and RageEvent::Wait().
WorkerMain()
void RageWorkerThread::WorkerMain () private
References RageEvent::Broadcast(), CHECKPOINT_M, DoHeartbeat(), HandleRequest(), RageMutex::Lock(), LOG, m_bRequestFinished, m_bTimedOut, m_fHeartbeat, m_HeartbeatEvent, m_iRequest, m_NextHeartbeat, m_WorkerEvent, REQ_NONE, REQ_SHUTDOWN, RequestTimedOut(), ssprintf(), RageTimer::Touch(), RageLog::Trace(), RageMutex::Unlock(), and RageEvent::Wait().
Member Data Documentation
m_bRequestFinished
bool RageWorkerThread::m_bRequestFinished private
Referenced by DoRequest(), RageWorkerThread(), and WorkerMain().
m_bTimedOut
bool RageWorkerThread::m_bTimedOut private
Referenced by DoRequest(), IsTimedOut(), RageWorkerThread(), StopThread(), and WorkerMain().
m_fHeartbeat
float RageWorkerThread::m_fHeartbeat private
Referenced by RageWorkerThread(), SetHeartbeat(), WaitForOneHeartbeat(), and WorkerMain().
m_HeartbeatEvent
RageEvent RageWorkerThread::m_HeartbeatEvent private
Referenced by WaitForOneHeartbeat(), and WorkerMain().
m_iRequest
int RageWorkerThread::m_iRequest private
Referenced by DoRequest(), RageWorkerThread(), and WorkerMain().
m_NextHeartbeat
RageTimer RageWorkerThread::m_NextHeartbeat private
Referenced by SetHeartbeat(), and WorkerMain().
m_sName
RString RageWorkerThread::m_sName private
Referenced by DoRequest(), RageWorkerThread(), and StopThread().
m_Timeout
RageTimer RageWorkerThread::m_Timeout private
Referenced by DoRequest(), RageWorkerThread(), SetTimeout(), TimeoutEnabled(), and WaitForOneHeartbeat().
m_WorkerEvent
RageEvent RageWorkerThread::m_WorkerEvent private
Referenced by DoRequest(), SetTimeout(), StopThread(), and WorkerMain().
m_WorkerThread
RageThread RageWorkerThread::m_WorkerThread private
Referenced by RageWorkerThread(), StartThread(), StopThread(), and ~RageWorkerThread().
The documentation for this class was generated from the following files:
RageUtil_WorkerThread.h
RageUtil_WorkerThread.cpp