Etterna: Difficulty.h File Reference
Difficulty.h File Reference
#include "EnumHelper.h"
#include "GameConstantsAndTypes.h"
Classes
struct Chart
struct Playlist
Enumerations
enum Difficulty {
Difficulty_Beginner, Difficulty_Easy, Difficulty_Medium, Difficulty_Hard,
Difficulty_Challenge, Difficulty_Edit, NUM_Difficulty, Difficulty_Invalid
}
Functions
const RString & DifficultyToString (Difficulty dc)
Difficulty StringToDifficulty (const RString &sDC)
LuaDeclareType (Difficulty)
Difficulty OldStyleStringToDifficulty (const RString &sDC)
RString GetCustomDifficulty (StepsType st, Difficulty dc)
RString CustomDifficultyToLocalizedString (const RString &sCustomDifficulty)
RString StepsToCustomDifficulty (const Steps *pSteps)
Enumeration Type Documentation
Difficulty
enum Difficulty
Enumerator
Difficulty_Beginner
Difficulty_Easy
Difficulty_Medium
Difficulty_Hard
Difficulty_Challenge
Difficulty_Edit
NUM_Difficulty
Difficulty_Invalid
Function Documentation
CustomDifficultyToLocalizedString()
RString CustomDifficultyToLocalizedString (const RString & sCustomDifficulty)
References ThemeManager::GetString(), and THEME.
Referenced by LunaGameState::GetCurrentStepsCredits(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSteps::Reload(), and StepsDisplay::SetInternal().
DifficultyToString()
const RString& DifficultyToString (Difficulty dc)
Referenced by SongUtil::AdjustDuplicateSteps(), Chart::CreateNode(), StepsID::CreateNode(), Steps::Decompress(), GetCustomDifficulty(), GetETTNoteData(), GameState::GetRankingFeats(), GetSMNotesTag(), Profile::GetSongsActual(), GetSSCNoteData(), Song::IsEditAlreadyLoaded(), XMLProfile::LoadGeneralDataFromNode(), ParseNoteData(), MusicWheelItem::RefreshGrades(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), SearchForDifficulty(), ETTProtocol::SelectUserSong(), Serialize(), and StepsID::ToString().
GetCustomDifficulty()
RString GetCustomDifficulty (StepsType st, Difficulty dc)
References Difficulty_Edit, Difficulty_Invalid, DifficultyToString(), FOREACH, ThemeMetric< T >::GetValue(), NAMES, split(), and StepsType_Invalid.
Referenced by LunaGameState::GetCurrentStepsCredits(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSteps::Reload(), StepsDisplay::SetInternal(), and StepsToCustomDifficulty().
LuaDeclareType()
LuaDeclareType (Difficulty)
OldStyleStringToDifficulty()
Difficulty OldStyleStringToDifficulty (const RString & sDC)
References OldStyleStringToDifficultyMapHolder::conversion_map, Difficulty_Invalid, and StdString::CStdStr< CT >::MakeLower().
Referenced by SMLoader::LoadFromTokens(), and SMLoader::LoadNoteDataFromSimfile().
StepsToCustomDifficulty()
RString StepsToCustomDifficulty (const Steps * pSteps)
References GetCustomDifficulty(), Steps::GetDifficulty(), and Steps::m_StepsType.
Referenced by StepsDisplay::SetInternal().
StringToDifficulty()
Difficulty StringToDifficulty (const RString & sDC)
Referenced by Deserialize(), ETTProtocol::FindJsonChart(), XMLProfile::LoadEttGeneralDataFromNode(), Chart::LoadFromNode(), StepsID::LoadFromNode(), XMLProfile::LoadGeneralDataFromNode(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), GameCommand::LoadOne(), ThemeMetricDifficultiesToShow::Read(), DownloadManager::RefreshTop25(), SetDifficulty(), and Steps::TidyUpData().