Etterna: IDebugLine Class Reference
IDebugLine Class Reference abstract
Public Types
enum Type { all_screens, gameplay_only }
Public Member Functions
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual RString GetDisplayTitle ()=0
virtual RString GetDisplayValue ()
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
virtual bool IsEnabled ()=0
virtual void DoAndLog (RString &sMessageOut)
Public Attributes
DeviceInput m_Button
Member Enumeration Documentation
Type
enum IDebugLine::Type
Enumerator
all_screens
gameplay_only
Constructor & Destructor Documentation
IDebugLine()
IDebugLine::IDebugLine () inline
References g_pvpSubscribers.
~IDebugLine()
virtual IDebugLine::~IDebugLine () virtual default
Member Function Documentation
DoAndLog()
virtual void IDebugLine::DoAndLog (RString & sMessageOut) inline virtual
Reimplemented in DebugLineUptime, DebugLineForceCrash, DebugLineVisualDelayDown, DebugLineVisualDelayUp, DebugLineVolumeDown, DebugLineVolumeUp, DebugLinePullBackCamera, DebugLineFlushLog, DebugLineMenuTimer, DebugLineWritePreferences, DebugLineWriteProfiles, DebugLineConvertXML, DebugLineClearErrors, DebugLineShowRecentErrors, DebugLineToggleErrors, DebugLineReloadOverlayScreens, DebugLineReloadTheme, DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, DebugLineRestartCurrentScreen, DebugLineReloadCurrentScreen, DebugLineMuteActions, DebugLineResetKeyMapping, DebugLineSendNotesEnded, DebugLineFillProfileStats, DebugLineClearProfileStats, DebugLineProfileSlot, DebugLineShowMasks, DebugLineAllowMultitexture, DebugLineVsync, DebugLineStats, DebugLineHalt, DebugLineSlow, DebugLineAutosync, DebugLineAssist, and DebugLineAutoplay.
References GetDisplayTitle(), and GetDisplayValue().
Referenced by DebugLineAutoplay::DoAndLog(), DebugLineAssist::DoAndLog(), DebugLineAutosync::DoAndLog(), DebugLineSlow::DoAndLog(), DebugLineHalt::DoAndLog(), DebugLineStats::DoAndLog(), DebugLineVsync::DoAndLog(), DebugLineAllowMultitexture::DoAndLog(), DebugLineShowMasks::DoAndLog(), DebugLineProfileSlot::DoAndLog(), DebugLineClearProfileStats::DoAndLog(), DebugLineFillProfileStats::DoAndLog(), DebugLineSendNotesEnded::DoAndLog(), DebugLineResetKeyMapping::DoAndLog(), DebugLineMuteActions::DoAndLog(), DebugLineReloadCurrentScreen::DoAndLog(), DebugLineRestartCurrentScreen::DoAndLog(), DebugLineCurrentScreenOn::DoAndLog(), DebugLineCurrentScreenOff::DoAndLog(), DebugLineReloadTheme::DoAndLog(), DebugLineReloadOverlayScreens::DoAndLog(), DebugLineToggleErrors::DoAndLog(), DebugLineShowRecentErrors::DoAndLog(), DebugLineClearErrors::DoAndLog(), DebugLineConvertXML::DoAndLog(), DebugLineWriteProfiles::DoAndLog(), DebugLineWritePreferences::DoAndLog(), DebugLineMenuTimer::DoAndLog(), DebugLineFlushLog::DoAndLog(), DebugLinePullBackCamera::DoAndLog(), DebugLineVolumeUp::DoAndLog(), DebugLineVolumeDown::DoAndLog(), DebugLineVisualDelayUp::DoAndLog(), and DebugLineVisualDelayDown::DoAndLog().
ForceOffAfterUse()
virtual bool IDebugLine::ForceOffAfterUse () const inline virtual
Reimplemented in DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, and DebugLineRestartCurrentScreen.
GetDisplayTitle()
virtual RString IDebugLine::GetDisplayTitle () pure virtual
Implemented in DebugLineUptime, DebugLineForceCrash, DebugLineVisualDelayDown, DebugLineVisualDelayUp, DebugLineVolumeDown, DebugLineVolumeUp, DebugLinePullBackCamera, DebugLineFlushLog, DebugLineMenuTimer, DebugLineWritePreferences, DebugLineWriteProfiles, DebugLineConvertXML, DebugLineClearErrors, DebugLineShowRecentErrors, DebugLineToggleErrors, DebugLineReloadOverlayScreens, DebugLineReloadTheme, DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, DebugLineRestartCurrentScreen, DebugLineReloadCurrentScreen, DebugLineMuteActions, DebugLineResetKeyMapping, DebugLineSendNotesEnded, DebugLineFillProfileStats, DebugLineClearProfileStats, DebugLineProfileSlot, DebugLineShowMasks, DebugLineAllowMultitexture, DebugLineVsync, DebugLineStats, DebugLineHalt, DebugLineSlow, DebugLineAutosync, DebugLineAssist, and DebugLineAutoplay.
Referenced by DoAndLog().
GetDisplayValue()
virtual RString IDebugLine::GetDisplayValue () inline virtual
Reimplemented in DebugLineUptime, DebugLineForceCrash, DebugLineVisualDelayDown, DebugLineVisualDelayUp, DebugLineVolumeDown, DebugLineVolumeUp, DebugLinePullBackCamera, DebugLineFlushLog, DebugLineMenuTimer, DebugLineWritePreferences, DebugLineWriteProfiles, DebugLineConvertXML, DebugLineClearErrors, DebugLineShowRecentErrors, DebugLineToggleErrors, DebugLineReloadOverlayScreens, DebugLineReloadTheme, DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, DebugLineRestartCurrentScreen, DebugLineReloadCurrentScreen, DebugLineMuteActions, DebugLineResetKeyMapping, DebugLineSendNotesEnded, DebugLineFillProfileStats, DebugLineClearProfileStats, DebugLineProfileSlot, DebugLineAutosync, DebugLineAssist, and DebugLineAutoplay.
References LocalizedString::GetValue(), IsEnabled(), OFF, and ON.
Referenced by DoAndLog().
GetPageName()
virtual RString IDebugLine::GetPageName () const inline virtual
Reimplemented in DebugLineWriteProfiles, DebugLineConvertXML, DebugLineClearErrors, DebugLineShowRecentErrors, DebugLineToggleErrors, DebugLineReloadOverlayScreens, DebugLineReloadTheme, DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, DebugLineRestartCurrentScreen, DebugLineReloadCurrentScreen, DebugLineFillProfileStats, DebugLineClearProfileStats, DebugLineProfileSlot, and DebugLineShowMasks.
GetType()
virtual Type IDebugLine::GetType () const inline virtual
Reimplemented in DebugLineAutosync, DebugLineAssist, and DebugLineAutoplay.
References all_screens.
Referenced by GetDebugButtonName().
IsEnabled()
virtual bool IDebugLine::IsEnabled () pure virtual
Implemented in DebugLineUptime, DebugLineForceCrash, DebugLineVisualDelayDown, DebugLineVisualDelayUp, DebugLineVolumeDown, DebugLineVolumeUp, DebugLinePullBackCamera, DebugLineFlushLog, DebugLineMenuTimer, DebugLineWritePreferences, DebugLineWriteProfiles, DebugLineConvertXML, DebugLineClearErrors, DebugLineShowRecentErrors, DebugLineToggleErrors, DebugLineReloadOverlayScreens, DebugLineReloadTheme, DebugLineCurrentScreenOff, DebugLineCurrentScreenOn, DebugLineRestartCurrentScreen, DebugLineReloadCurrentScreen, DebugLineMuteActions, DebugLineResetKeyMapping, DebugLineSendNotesEnded, DebugLineFillProfileStats, DebugLineClearProfileStats, DebugLineProfileSlot, DebugLineShowMasks, DebugLineAllowMultitexture, DebugLineVsync, DebugLineStats, DebugLineHalt, DebugLineSlow, DebugLineAutosync, DebugLineAssist, and DebugLineAutoplay.
Referenced by GetDisplayValue().
Member Data Documentation
m_Button
DeviceInput IDebugLine::m_Button
Referenced by GetDebugButtonName().
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp