Etterna: RageTextureRenderTarget Class Reference
RageTextureRenderTarget Class Reference
#include <RageTextureRenderTarget.h>
Public Member Functions
RageTextureRenderTarget (const RageTextureID &name, const RenderTargetParam &param)
~RageTextureRenderTarget () override
void Invalidate () override
void Reload () override
unsigned GetTexHandle () const override
void BeginRenderingTo (bool bPreserveTexture=true)
void FinishRenderingTo ()
void PushSelf (lua_State *L) override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Update (float)
virtual void SetPosition (float)
virtual void DecodeSeconds (float)
virtual void SetPlaybackRate (float)
virtual bool IsAMovie () const
virtual void SetLooping (bool)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
Private Member Functions
void Create ()
void Destroy ()
Private Attributes
const RenderTargetParam m_Param
unsigned m_iTexHandle
unsigned m_iPreviousRenderTarget
Additional Inherited Members
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
RageTextureRenderTarget()
RageTextureRenderTarget::RageTextureRenderTarget (const RageTextureID & name, const RenderTargetParam & param)
References Create().
~RageTextureRenderTarget()
RageTextureRenderTarget::~RageTextureRenderTarget () override
References Destroy().
Member Function Documentation
BeginRenderingTo()
void RageTextureRenderTarget::BeginRenderingTo (bool bPreserveTexture = true)
References RageDisplay::CameraPushMatrix(), RageDisplay::CenteringPushMatrix(), RageDisplay::ChangeCentering(), DISPLAY, RageDisplay::GetRenderTarget(), RageDisplay::LoadIdentity(), RageDisplay::LoadMenuPerspective(), RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, m_iPreviousRenderTarget, m_iTexHandle, RageDisplay::PushMatrix(), and RageDisplay::SetRenderTarget().
Referenced by LunaRageTextureRenderTarget::BeginRenderingTo(), ActorFrameTexture::DrawPrimitives(), and MovieTexture_Generic::UpdateFrame().
Create()
void RageTextureRenderTarget::Create () private
References RageTexture::CreateFrameRects(), RageDisplay::CreateRenderTarget(), DISPLAY, RenderTargetParam::iHeight, RenderTargetParam::iWidth, RageTexture::m_iFramesHigh, RageTexture::m_iFramesWide, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, m_iTexHandle, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, and m_Param.
Referenced by RageTextureRenderTarget(), and Reload().
Destroy()
void RageTextureRenderTarget::Destroy () private
References RageDisplay::DeleteTexture(), DISPLAY, and m_iTexHandle.
Referenced by Reload(), and ~RageTextureRenderTarget().
FinishRenderingTo()
void RageTextureRenderTarget::FinishRenderingTo ()
References RageDisplay::CameraPopMatrix(), RageDisplay::CenteringPopMatrix(), DISPLAY, m_iPreviousRenderTarget, RageDisplay::PopMatrix(), and RageDisplay::SetRenderTarget().
Referenced by ActorFrameTexture::DrawPrimitives(), LunaRageTextureRenderTarget::FinishRenderingTo(), and MovieTexture_Generic::UpdateFrame().
GetTexHandle()
unsigned RageTextureRenderTarget::GetTexHandle () const inline override virtual
Implements RageTexture.
References m_iTexHandle.
Referenced by MovieTexture_Generic::GetTexHandle().
Invalidate()
void RageTextureRenderTarget::Invalidate () inline override virtual
Reimplemented from RageTexture.
References m_iTexHandle.
PushSelf()
void RageTextureRenderTarget::PushSelf (lua_State * L) override virtual
Reimplemented from RageTexture.
Reload()
void RageTextureRenderTarget::Reload () override virtual
Reimplemented from RageTexture.
References Create(), and Destroy().
Member Data Documentation
m_iPreviousRenderTarget
unsigned RageTextureRenderTarget::m_iPreviousRenderTarget private
Referenced by BeginRenderingTo(), and FinishRenderingTo().
m_iTexHandle
unsigned RageTextureRenderTarget::m_iTexHandle private
Referenced by BeginRenderingTo(), Create(), Destroy(), GetTexHandle(), and Invalidate().
m_Param
const RenderTargetParam RageTextureRenderTarget::m_Param private
Referenced by Create().
The documentation for this class was generated from the following files:
RageTextureRenderTarget.h
RageTextureRenderTarget.cpp