Etterna: LuaBinding Class Reference
LuaBinding Class Reference abstract
#include <LuaBinding.h>
Inherited by Luna< Type >, Luna< Actor >, Luna< ActorFrame >, Luna< ActorFrameTexture >, Luna< ActorMultiTexture >, Luna< ActorMultiVertex >, Luna< ActorProxy >, Luna< ActorScroller >, Luna< ActorSound >, Luna< AnnouncerManager >, Luna< ArchHooks >, Luna< Banner >, Luna< BitmapText >, Luna< BPMDisplay >, Luna< Character >, Luna< CharacterManager >, Luna< Chart >, Luna< ColorBitmapText >, Luna< ComboGraph >, Luna< ControllerStateDisplay >, Luna< CryptManager >, Luna< CubicSplineN >, Luna< DifficultyIcon >, Luna< Download >, Luna< DownloadablePack >, Luna< DownloadManager >, Luna< FadingBanner >, Luna< FilterManager >, Luna< Game >, Luna< GameCommand >, Luna< GameManager >, Luna< GameSoundManager >, Luna< GameState >, Luna< GradeDisplay >, Luna< GraphDisplay >, Luna< GrooveRadar >, Luna< HelpDisplay >, Luna< HighScore >, Luna< HighScoreList >, Luna< HoldJudgment >, Luna< HoldNoteResult >, Luna< InputFilter >, Luna< LifeMeter >, Luna< LifeMeterBattery >, Luna< MemoryCardManager >, Luna< MenuTimer >, Luna< MessageManager >, Luna< MeterDisplay >, Luna< Model >, Luna< ModIconRow >, Luna< MusicWheel >, Luna< NCSplineHandler >, Luna< NoteColumnRenderer >, Luna< NoteField >, Luna< NoteSkinManager >, Luna< OptionRow >, Luna< Packlist >, Luna< PaneDisplay >, Luna< PercentageDisplay >, Luna< Player >, Luna< PlayerInfo >, Luna< PlayerOptions >, Luna< PlayerState >, Luna< Playlist >, Luna< PrefsManager >, Luna< Profile >, Luna< ProfileManager >, Luna< RadarValues >, Luna< RageBezier2D >, Luna< RageDisplay >, Luna< RageFile >, Luna< RageFileManager >, Luna< RageInput >, Luna< RageQuadratic >, Luna< RageSound >, Luna< RageTexture >, Luna< RageTextureRenderTarget >, Luna< RollingNumbers >, Luna< RoomWheel >, Luna< ScoreDisplayAliveTime >, Luna< ScoreGoal >, Luna< ScoreManager >, Luna< ScoresAtRate >, Luna< ScoresForChart >, Luna< Screen >, Luna< ScreenAttract >, Luna< ScreenEvaluation >, Luna< ScreenGameplay >, Luna< ScreenHowToPlay >, Luna< ScreenManager >, Luna< ScreenNetEvaluation >, Luna< ScreenNetRoom >, Luna< ScreenNetSelectBase >, Luna< ScreenNetSelectMusic >, Luna< ScreenOptions >, Luna< ScreenPlayerOptions >, Luna< ScreenProfileLoad >, Luna< ScreenProfileSave >, Luna< ScreenSelectMaster >, Luna< ScreenSelectMusic >, Luna< ScreenSelectProfile >, Luna< ScreenTextEntry >, Luna< ScreenWithMenuElements >, Luna< ScreenWithMenuElementsSimple >, Luna< Song >, Luna< SongManager >, Luna< SongOptions >, Luna< SongPosition >, Luna< Sprite >, Luna< StageStats >, Luna< StatsManager >, Luna< Steps >, Luna< StepsDisplay >, Luna< StepsDisplayList >, Luna< Style >, Luna< TapNote >, Luna< TapNoteResult >, Luna< TextBanner >, Luna< ThemeManager >, Luna< TimingData >, Luna< WheelBase >, and Luna< WheelItemBase >.
Public Member Functions
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
virtual const std::string & GetClassName () const =0
virtual const std::string & GetBaseClassName () const =0
Static Public Member Functions
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Protected Member Functions
virtual void Register (Lua *L, int iMethods, int iMetatable)=0
Static Protected Member Functions
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LuaBinding()
LuaBinding::LuaBinding ()
References SubscriptionManager< T >::Subscribe().
~LuaBinding()
LuaBinding::~LuaBinding () virtual
References SubscriptionManager< T >::Unsubscribe().
Member Function Documentation
ApplyDerivedType()
void LuaBinding::ApplyDerivedType (Lua * L, const std::string & sClassname, void * pSelf) static
References ASSERT, ASSERT_M, GetGlobalTable(), and ssprintf().
CheckLuaObjectType()
bool LuaBinding::CheckLuaObjectType (lua_State * L, int narg, std::string const & szType) static
Referenced by Luna< GameSoundManager >::check(), LunaProfile::GetHighScoreList(), and LunaProfile::GetHighScoreListIfExists().
CreateMethodsTable()
void LuaBinding::CreateMethodsTable (lua_State * L, const std::string & szName) static protected
Referenced by Register().
Equal()
bool LuaBinding::Equal (lua_State * L) static protected
Referenced by PushEqual().
GetBaseClassName()
virtual const std::string& LuaBinding::GetBaseClassName () const pure virtual
Implemented in Luna< Type >, Luna< ArchHooks >, Luna< PlayerOptions >, Luna< GameManager >, Luna< PlayerState >, Luna< HelpDisplay >, Luna< StepsDisplayList >, Luna< TextBanner >, Luna< GameState >, Luna< HoldNoteResult >, Luna< RoomWheel >, Luna< StatsManager >, Luna< ScoreDisplayAliveTime >, Luna< ScoresAtRate >, Luna< RageDisplay >, Luna< ScreenHowToPlay >, Luna< GradeDisplay >, Luna< Game >, Luna< ScreenNetRoom >, Luna< ModIconRow >, Luna< ScreenManager >, Luna< HighScoreList >, Luna< Download >, Luna< ScoreManager >, Luna< RageTexture >, Luna< ScreenNetSelectBase >, Luna< RageBezier2D >, Luna< Actor >, Luna< NoteField >, Luna< PlayerInfo >, Luna< BitmapText >, Luna< RageSound >, Luna< Sprite >, Luna< NoteSkinManager >, Luna< ActorFrameTexture >, Luna< RollingNumbers >, Luna< RageInput >, Luna< DownloadManager >, Luna< GameCommand >, Luna< MemoryCardManager >, Luna< HighScore >, Luna< PercentageDisplay >, Luna< ActorFrame >, Luna< Profile >, Luna< SongManager >, Luna< FilterManager >, Luna< GraphDisplay >, Luna< TapNote >, Luna< ComboGraph >, Luna< LifeMeter >, Luna< SongOptions >, Luna< ActorScroller >, Luna< ScoresForChart >, Luna< StageStats >, Luna< PaneDisplay >, Luna< OptionRow >, Luna< Packlist >, Luna< ActorMultiVertex >, Luna< RadarValues >, Luna< ScreenGameplay >, Luna< SongPosition >, Luna< RageQuadratic >, Luna< ProfileManager >, Luna< FadingBanner >, Luna< ActorSound >, Luna< ScreenNetEvaluation >, Luna< CubicSplineN >, Luna< Chart >, Luna< Song >, Luna< DownloadablePack >, Luna< CryptManager >, Luna< Model >, Luna< StepsDisplay >, Luna< HoldJudgment >, Luna< ScreenSelectMusic >, Luna< AnnouncerManager >, Luna< RageFile >, Luna< RageFileManager >, Luna< Steps >, Luna< NCSplineHandler >, Luna< ScreenTextEntry >, Luna< ScreenWithMenuElements >, Luna< MessageManager >, Luna< ScreenSelectMaster >, Luna< DifficultyIcon >, Luna< ScreenAttract >, Luna< ScreenWithMenuElementsSimple >, Luna< LifeMeterBattery >, Luna< PrefsManager >, Luna< ThemeManager >, Luna< ControllerStateDisplay >, Luna< InputFilter >, Luna< Banner >, Luna< ScreenProfileSave >, Luna< ScoreGoal >, Luna< ScreenNetSelectMusic >, Luna< BPMDisplay >, Luna< ScreenOptions >, Luna< ScreenProfileLoad >, Luna< ActorProxy >, Luna< ActorMultiTexture >, Luna< MeterDisplay >, Luna< Screen >, Luna< WheelItemBase >, Luna< MusicWheel >, Luna< Character >, Luna< TimingData >, Luna< Style >, Luna< ScreenEvaluation >, Luna< ScreenSelectProfile >, Luna< RageTextureRenderTarget >, Luna< MenuTimer >, Luna< GrooveRadar >, Luna< NoteColumnRenderer >, Luna< CharacterManager >, Luna< ScreenPlayerOptions >, Luna< WheelBase >, Luna< Player >, Luna< TapNoteResult >, Luna< ColorBitmapText >, Luna< Playlist >, and Luna< GameSoundManager >.
Referenced by IsDerivedClass(), and Register().
GetClassName()
virtual const std::string& LuaBinding::GetClassName () const pure virtual
Implemented in Luna< Type >, Luna< ArchHooks >, Luna< PlayerOptions >, Luna< GameManager >, Luna< PlayerState >, Luna< HelpDisplay >, Luna< StepsDisplayList >, Luna< TextBanner >, Luna< GameState >, Luna< HoldNoteResult >, Luna< RoomWheel >, Luna< StatsManager >, Luna< ScoreDisplayAliveTime >, Luna< ScoresAtRate >, Luna< RageDisplay >, Luna< ScreenHowToPlay >, Luna< GradeDisplay >, Luna< Game >, Luna< ScreenNetRoom >, Luna< ModIconRow >, Luna< ScreenManager >, Luna< HighScoreList >, Luna< Download >, Luna< ScoreManager >, Luna< RageTexture >, Luna< ScreenNetSelectBase >, Luna< RageBezier2D >, Luna< Actor >, Luna< NoteField >, Luna< PlayerInfo >, Luna< BitmapText >, Luna< RageSound >, Luna< Sprite >, Luna< NoteSkinManager >, Luna< ActorFrameTexture >, Luna< RollingNumbers >, Luna< RageInput >, Luna< DownloadManager >, Luna< GameCommand >, Luna< MemoryCardManager >, Luna< HighScore >, Luna< PercentageDisplay >, Luna< ActorFrame >, Luna< Profile >, Luna< SongManager >, Luna< FilterManager >, Luna< GraphDisplay >, Luna< TapNote >, Luna< ComboGraph >, Luna< LifeMeter >, Luna< SongOptions >, Luna< ActorScroller >, Luna< ScoresForChart >, Luna< StageStats >, Luna< PaneDisplay >, Luna< OptionRow >, Luna< Packlist >, Luna< ActorMultiVertex >, Luna< RadarValues >, Luna< ScreenGameplay >, Luna< SongPosition >, Luna< RageQuadratic >, Luna< ProfileManager >, Luna< FadingBanner >, Luna< ActorSound >, Luna< ScreenNetEvaluation >, Luna< CubicSplineN >, Luna< Chart >, Luna< Song >, Luna< DownloadablePack >, Luna< CryptManager >, Luna< Model >, Luna< StepsDisplay >, Luna< HoldJudgment >, Luna< ScreenSelectMusic >, Luna< AnnouncerManager >, Luna< RageFile >, Luna< RageFileManager >, Luna< Steps >, Luna< NCSplineHandler >, Luna< ScreenTextEntry >, Luna< ScreenWithMenuElements >, Luna< MessageManager >, Luna< ScreenSelectMaster >, Luna< DifficultyIcon >, Luna< ScreenAttract >, Luna< ScreenWithMenuElementsSimple >, Luna< LifeMeterBattery >, Luna< PrefsManager >, Luna< ThemeManager >, Luna< ControllerStateDisplay >, Luna< InputFilter >, Luna< Banner >, Luna< ScreenProfileSave >, Luna< ScoreGoal >, Luna< ScreenNetSelectMusic >, Luna< BPMDisplay >, Luna< ScreenOptions >, Luna< ScreenProfileLoad >, Luna< ActorProxy >, Luna< ActorMultiTexture >, Luna< MeterDisplay >, Luna< Screen >, Luna< WheelItemBase >, Luna< MusicWheel >, Luna< Character >, Luna< TimingData >, Luna< Style >, Luna< ScreenEvaluation >, Luna< ScreenSelectProfile >, Luna< RageTextureRenderTarget >, Luna< MenuTimer >, Luna< GrooveRadar >, Luna< NoteColumnRenderer >, Luna< CharacterManager >, Luna< ScreenPlayerOptions >, Luna< WheelBase >, Luna< Player >, Luna< TapNoteResult >, Luna< ColorBitmapText >, Luna< Playlist >, and Luna< GameSoundManager >.
Referenced by IsDerivedClass(), and Register().
GetPointerFromStack()
void * LuaBinding::GetPointerFromStack (Lua * L, const std::string & sType, int iArg) static protected
References LuaHelpers::AbsIndex(), and GetGlobalTable().
Referenced by Luna< GameSoundManager >::get().
IsDerivedClass()
bool LuaBinding::IsDerivedClass () const inline
References GetBaseClassName(), and GetClassName().
Referenced by Register().
PushEqual()
int LuaBinding::PushEqual (lua_State * L) static protected
References Equal().
Referenced by Register().
Register() [1/2]
void LuaBinding::Register (lua_State * L)
References ASSERT, CreateMethodsTable(), LuaHelpers::FromStack(), GetBaseClassName(), GetClassName(), IsDerivedClass(), PushEqual(), and LuaHelpers::PushValueFunc().
Register() [2/2]
virtual void LuaBinding::Register (Lua * L, int iMethods, int iMetatable) protected pure virtual
Implemented in Luna< Type >, Luna< ArchHooks >, Luna< PlayerOptions >, Luna< GameManager >, Luna< PlayerState >, Luna< HelpDisplay >, Luna< StepsDisplayList >, Luna< TextBanner >, Luna< GameState >, Luna< HoldNoteResult >, Luna< RoomWheel >, Luna< StatsManager >, Luna< ScoreDisplayAliveTime >, Luna< ScoresAtRate >, Luna< RageDisplay >, Luna< ScreenHowToPlay >, Luna< GradeDisplay >, Luna< Game >, Luna< ScreenNetRoom >, Luna< ModIconRow >, Luna< ScreenManager >, Luna< HighScoreList >, Luna< Download >, Luna< ScoreManager >, Luna< RageTexture >, Luna< ScreenNetSelectBase >, Luna< RageBezier2D >, Luna< Actor >, Luna< NoteField >, Luna< PlayerInfo >, Luna< BitmapText >, Luna< RageSound >, Luna< Sprite >, Luna< NoteSkinManager >, Luna< ActorFrameTexture >, Luna< RollingNumbers >, Luna< RageInput >, Luna< DownloadManager >, Luna< GameCommand >, Luna< MemoryCardManager >, Luna< HighScore >, Luna< PercentageDisplay >, Luna< ActorFrame >, Luna< Profile >, Luna< SongManager >, Luna< FilterManager >, Luna< GraphDisplay >, Luna< TapNote >, Luna< ComboGraph >, Luna< LifeMeter >, Luna< SongOptions >, Luna< ActorScroller >, Luna< ScoresForChart >, Luna< StageStats >, Luna< PaneDisplay >, Luna< OptionRow >, Luna< Packlist >, Luna< ActorMultiVertex >, Luna< RadarValues >, Luna< ScreenGameplay >, Luna< SongPosition >, Luna< RageQuadratic >, Luna< ProfileManager >, Luna< FadingBanner >, Luna< ActorSound >, Luna< ScreenNetEvaluation >, Luna< CubicSplineN >, Luna< Chart >, Luna< Song >, Luna< DownloadablePack >, Luna< CryptManager >, Luna< Model >, Luna< StepsDisplay >, Luna< HoldJudgment >, Luna< ScreenSelectMusic >, Luna< AnnouncerManager >, Luna< RageFile >, Luna< RageFileManager >, Luna< Steps >, Luna< NCSplineHandler >, Luna< ScreenTextEntry >, Luna< ScreenWithMenuElements >, Luna< MessageManager >, Luna< ScreenSelectMaster >, Luna< DifficultyIcon >, Luna< ScreenAttract >, Luna< ScreenWithMenuElementsSimple >, Luna< LifeMeterBattery >, Luna< PrefsManager >, Luna< ThemeManager >, Luna< ControllerStateDisplay >, Luna< InputFilter >, Luna< Banner >, Luna< ScreenProfileSave >, Luna< ScoreGoal >, Luna< ScreenNetSelectMusic >, Luna< BPMDisplay >, Luna< ScreenOptions >, Luna< ScreenProfileLoad >, Luna< ActorProxy >, Luna< ActorMultiTexture >, Luna< MeterDisplay >, Luna< Screen >, Luna< WheelItemBase >, Luna< MusicWheel >, Luna< Character >, Luna< TimingData >, Luna< Style >, Luna< ScreenEvaluation >, Luna< ScreenSelectProfile >, Luna< RageTextureRenderTarget >, Luna< MenuTimer >, Luna< GrooveRadar >, Luna< NoteColumnRenderer >, Luna< CharacterManager >, Luna< ScreenPlayerOptions >, Luna< WheelBase >, Luna< Player >, Luna< TapNoteResult >, Luna< ColorBitmapText >, Luna< Playlist >, and Luna< GameSoundManager >.
RegisterTypes()
static void LuaBinding::RegisterTypes (lua_State * L) static
The documentation for this class was generated from the following files:
LuaBinding.h
LuaBinding.cpp