Etterna: LunaNoteSkinManager Class Reference
LunaNoteSkinManager Class Reference
Allow Lua to have access to the NoteSkinManager.
Public Member Functions
DEFINE_METHOD (GetPath, GetPath(SArg(1), SArg(2)))
DEFINE_METHOD (GetMetric, GetMetric(SArg(1), SArg(2)))
DEFINE_METHOD (GetMetricI, GetMetricI(SArg(1), SArg(2)))
DEFINE_METHOD (GetMetricF, GetMetricF(SArg(1), SArg(2)))
DEFINE_METHOD (GetMetricB, GetMetricB(SArg(1), SArg(2)))
FOR_NOTESKIN (GetPath, 2)
FOR_NOTESKIN (GetMetric, 2)
FOR_NOTESKIN (GetMetricI, 2)
FOR_NOTESKIN (GetMetricF, 2)
FOR_NOTESKIN (GetMetricB, 2)
FOR_NOTESKIN (GetMetricA, 2)
FOR_NOTESKIN (LoadActor, 2)
LunaNoteSkinManager ()
Public Member Functions inherited from Luna< NoteSkinManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetMetricA (T *p, lua_State *L)
static int LoadActor (T *p, lua_State *L)
static int GetNoteSkinNames (T *p, lua_State *L)
static int DoesNoteSkinExist (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< NoteSkinManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< NoteSkinManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< NoteSkinManager >
using T = NoteSkinManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< NoteSkinManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the NoteSkinManager.
Constructor & Destructor Documentation
LunaNoteSkinManager()
LunaNoteSkinManager::LunaNoteSkinManager () inline
References ADD_METHOD, DoesNoteSkinExist(), GetMetricA(), GetNoteSkinNames(), and LoadActor().
Member Function Documentation
DEFINE_METHOD() [1/5]
LunaNoteSkinManager::DEFINE_METHOD (GetPath , GetPath(SArg(1), SArg(2)))
DEFINE_METHOD() [2/5]
LunaNoteSkinManager::DEFINE_METHOD (GetMetric , GetMetric(SArg(1), SArg(2)))
DEFINE_METHOD() [3/5]
LunaNoteSkinManager::DEFINE_METHOD (GetMetricI , GetMetricI(SArg(1), SArg(2)))
DEFINE_METHOD() [4/5]
LunaNoteSkinManager::DEFINE_METHOD (GetMetricF , GetMetricF(SArg(1), SArg(2)))
DEFINE_METHOD() [5/5]
LunaNoteSkinManager::DEFINE_METHOD (GetMetricB , GetMetricB(SArg(1), SArg(2)))
DoesNoteSkinExist()
static int LunaNoteSkinManager::DoesNoteSkinExist (T * p, lua_State * L) inline static
References NoteSkinManager::DoesNoteSkinExist(), and SArg.
Referenced by LunaNoteSkinManager().
FOR_NOTESKIN() [1/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetPath , 2)
FOR_NOTESKIN() [2/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetMetric , 2)
FOR_NOTESKIN() [3/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetMetricI , 2)
FOR_NOTESKIN() [4/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetMetricF , 2)
FOR_NOTESKIN() [5/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetMetricB , 2)
FOR_NOTESKIN() [6/7]
LunaNoteSkinManager::FOR_NOTESKIN (GetMetricA , 2)
FOR_NOTESKIN() [7/7]
LunaNoteSkinManager::FOR_NOTESKIN (LoadActor , 2)
GetMetricA()
static int LunaNoteSkinManager::GetMetricA (T * p, lua_State * L) inline static
References NoteSkinManager::GetMetricA(), LuaReference::PushSelf(), and SArg.
Referenced by LunaNoteSkinManager().
GetNoteSkinNames()
static int LunaNoteSkinManager::GetNoteSkinNames (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and NoteSkinManager::GetNoteSkinNames().
Referenced by LunaNoteSkinManager().
LoadActor()
static int LunaNoteSkinManager::LoadActor (T * p, lua_State * L) inline static
References NoteSkinManager::PushActorTemplate(), and SArg.
Referenced by LunaNoteSkinManager().
The documentation for this class was generated from the following file:
NoteSkinManager.cpp