Etterna: OptionRowHandlerListSteps Class Reference
OptionRowHandlerListSteps Class Reference
Private Member Functions
bool LoadInternal (const Commands &) override
ReloadChanged Reload () override
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Public Member Functions inherited from OptionRowHandlerList
OptionRowHandlerList ()
void Init () override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
int GetDefaultOption () const override
void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const override
RString GetScreen (int iChoice) const override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes inherited from OptionRowHandlerList
vector< GameCommand > m_aListEntries
GameCommand m_Default
bool m_bUseModNameForIcon
vector< RString > m_vsBroadcastOnExport
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Member Function Documentation
LoadInternal()
bool OptionRowHandlerListSteps::LoadInternal (const Commands &) inline override private virtual
Reimplemented from OptionRowHandlerList.
References OptionRowDefinition::m_bAllowThemeItems, OptionRowHandler::m_Def, OptionRowDefinition::m_sName, and Reload().
Reload()
ReloadChanged OptionRowHandlerListSteps::Reload () inline override private virtual
Reimplemented from OptionRowHandlerList.
References CustomDifficultyToLocalizedString(), Difficulty_Edit, GAMESTATE, Steps::GetChartName(), GameState::GetCurrentStyle(), GetCustomDifficulty(), Steps::GetDescription(), Steps::GetDifficulty(), GameState::GetMasterPlayerNumber(), Steps::GetMeter(), SongUtil::GetSteps(), Steps::IsAnEdit(), GameState::IsEditing(), OptionRowHandlerList::m_aListEntries, GameCommand::m_dc, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, GameState::m_pCurSong, GameCommand::m_pSteps, Steps::m_StepsType, OptionRowDefinition::m_vsChoices, OptionRowHandler::RELOAD_CHANGED_ALL, StepsUtil::SortNotesArrayByDifficulty(), ssprintf(), STEPS_ROW_LAYOUT_TYPE, STEPS_USE_CHART_NAME, and StringToLayoutType().
Referenced by LoadInternal().
The documentation for this class was generated from the following file:
OptionRowHandler.cpp