Etterna: TimeSignatureSegment Struct Reference
TimeSignatureSegment Struct Reference
Identifies when a song changes its time signature.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
TimeSignatureSegment (int iStartRow=ROW_INVALID, int iNum=4, int iDenom=4)
TimeSignatureSegment (const TimeSignatureSegment &other)
int GetNum () const
void SetNum (int num)
int GetDen () const
void SetDen (int den)
void Set (int num, int den)
RString ToString (int dec) const override
vector< float > GetValues () const override
int GetNoteRowsPerMeasure () const
Retrieve the number of note rows per measure within the TimeSignatureSegment.
bool operator== (const TimeSignatureSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
int m_iNumerator
int m_iDenominator
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a song changes its time signature.
This only supports simple time signatures. The upper number (called the numerator here, though this isn't properly a fraction) is the number of beats per measure. The lower number (denominator here) is the note value representing one beat.
Constructor & Destructor Documentation
TimeSignatureSegment() [1/2]
TimeSignatureSegment::TimeSignatureSegment (int iStartRow = ROW_INVALID, int iNum = 4, int iDenom = 4) inline
Referenced by Copy().
TimeSignatureSegment() [2/2]
TimeSignatureSegment::TimeSignatureSegment (const TimeSignatureSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* TimeSignatureSegment::Copy () const inline override virtual
Implements TimingSegment.
References TimeSignatureSegment().
DebugPrint()
void TimeSignatureSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetDen(), GetNum(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetDen()
int TimeSignatureSegment::GetDen () const inline
References m_iDenominator.
Referenced by DebugPrint(), NoteField::DrawPrimitives(), GetValues(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetEffectType()
SegmentEffectType TimeSignatureSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetNoteRowsPerMeasure()
int TimeSignatureSegment::GetNoteRowsPerMeasure () const inline
Retrieve the number of note rows per measure within the TimeSignatureSegment.
With BeatToNoteRow(1) rows per beat, then we should have BeatToNoteRow(1)*m_iNumerator beats per measure. But if we assume that every BeatToNoteRow(1) rows is a quarter note, and we want the beats to be 1/m_iDenominator notes, then we should have BeatToNoteRow(1)*4 is rows per whole note and thus BeatToNoteRow(1)*4/m_iDenominator is rows per beat. Multiplying by m_iNumerator gives rows per measure.
Returns
the number of note rows per measure.
References BeatToNoteRow(), m_iDenominator, and m_iNumerator.
Referenced by BackgroundImpl::LoadFromRandom(), and TimingData::NoteRowToMeasureAndBeat().
GetNum()
int TimeSignatureSegment::GetNum () const inline
References m_iNumerator.
Referenced by DebugPrint(), NoteField::DrawPrimitives(), GetValues(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetType()
TimingSegmentType TimeSignatureSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_TIME_SIG.
Referenced by DebugPrint(), and operator==().
GetValues()
vector< float > TimeSignatureSegment::GetValues () const override virtual
Reimplemented from TimingSegment.
References GetDen(), and GetNum().
IsNotable()
bool TimeSignatureSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool TimeSignatureSegment::operator== (const TimeSignatureSegment & other) const inline
References COMPARE, m_iDenominator, and m_iNumerator.
Referenced by operator==().
operator==() [2/2]
bool TimeSignatureSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
Set()
void TimeSignatureSegment::Set (int num, int den) inline
References m_iDenominator, and m_iNumerator.
SetDen()
void TimeSignatureSegment::SetDen (int den) inline
References m_iDenominator.
SetNum()
void TimeSignatureSegment::SetNum (int num) inline
References m_iNumerator.
ToString()
RString TimeSignatureSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetDen(), GetNum(), IntToString(), and ssprintf().
Member Data Documentation
m_iDenominator
int TimeSignatureSegment::m_iDenominator private
Referenced by GetDen(), GetNoteRowsPerMeasure(), operator==(), Set(), and SetDen().
m_iNumerator
int TimeSignatureSegment::m_iNumerator private
Referenced by GetNoteRowsPerMeasure(), GetNum(), operator==(), Set(), and SetNum().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp