Etterna: RageSoundDriver_Null Class Reference
RageSoundDriver_Null Class Reference
#include <RageSoundDriver_Null.h>
Public Member Functions
RageSoundDriver_Null ()
int64_t GetPosition () const
int GetSampleRate () const
void Update ()
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
virtual RString Init ()
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual float GetPlayLatency () const
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Attributes
int64_t m_iLastCursorPos
int m_iSampleRate
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
virtual void SetupDecodingThread ()
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_Null()
RageSoundDriver_Null::RageSoundDriver_Null ()
References GetPosition(), m_iLastCursorPos, m_iSampleRate, PrefsManager::m_iSoundPreferredSampleRate, PREFSMAN, and RageSoundDriver::StartDecodeThread().
Member Function Documentation
GetPosition()
int64_t RageSoundDriver_Null::GetPosition () const virtual
Implements RageSoundDriver.
References RageTimer::GetTimeSinceStart(), and m_iSampleRate.
Referenced by RageSoundDriver_Null(), and Update().
GetSampleRate()
int RageSoundDriver_Null::GetSampleRate () const virtual
Reimplemented from RageSoundDriver.
References m_iSampleRate.
Update()
void RageSoundDriver_Null::Update () virtual
Reimplemented from RageSoundDriver.
References channels, GetPosition(), m_iLastCursorPos, RageSoundDriver::Mix(), and RageSoundDriver::Update().
Member Data Documentation
m_iLastCursorPos
int64_t RageSoundDriver_Null::m_iLastCursorPos private
Referenced by RageSoundDriver_Null(), and Update().
m_iSampleRate
int RageSoundDriver_Null::m_iSampleRate private
Referenced by GetPosition(), GetSampleRate(), and RageSoundDriver_Null().
The documentation for this class was generated from the following files:
RageSoundDriver_Null.h
RageSoundDriver_Null.cpp