Etterna: RageUtil.cpp File Reference
RageUtil.cpp File Reference
#include "global.h"
#include "RageUtil.h"
#include "Foreach.h"
#include "LocalizedString.h"
#include "LuaBinding.h"
#include "LuaManager.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageSoundReader_FileReader.h"
#include <cfloat>
#include <ctime>
#include <map>
#include <numeric>
#include <sstream>
#include "../extern/pcre/pcre.h"
Namespaces
StringConversion
Utilities for converting the RStrings.
Macros
#define FMT_BLOCK_SIZE 2048
#define TONUMBER_NICE(dest, num_name, index)
Functions
bool HexToBinary (const RString &, RString &)
void utf8_sanitize (RString &)
void UnicodeUpperLower (wchar_t *, size_t, const unsigned char *)
LUA_REGISTER_NAMESPACE (MersenneTwister)
void seed_lua_prng ()
void fapproach (float &val, float other_val, float to_move)
float fmodfp (float x, float y)
int power_of_two (int input)
bool IsAnInt (const RString &s)
bool IsHexVal (const RString &s)
RString BinaryToHex (const void *pData_, int iNumBytes)
RString BinaryToHex (const RString &sString)
bool HexToBinary (const RString &s, unsigned char *stringOut)
float HHMMSSToSeconds (const RString &sHHMMSS)
RString SecondsToHHMMSS (float fSecs)
RString SecondsToMMSSMsMs (float fSecs)
RString SecondsToMSSMsMs (float fSecs)
RString SecondsToMMSSMsMsMs (float fSecs)
RString SecondsToMSS (float fSecs)
RString SecondsToMMSS (float fSecs)
RString PrettyPercent (float fNumerator, float fDenominator)
RString Commify (int iNum)
RString Commify (const RString &num, const RString &sep, const RString &dot)
RString FormatNumberAndSuffix (int i)
struct tm GetLocalTime ()
RString ssprintf (const char *fmt,...)
RString vssprintf (const char *szFormat, va_list argList)
RString ConvertI64FormatString (const RString &sStr)
void GetLanguageInfos (vector< const LanguageInfo *> &vAddTo)
const LanguageInfo * GetLanguageInfo (const RString &sIsoCode)
RString join (const RString &sDeliminator, const vector< RString > &sSource)
RString join (const RString &sDelimitor, vector< RString >::const_iterator begin, vector< RString >::const_iterator end)
std::string luajoin (const std::string &sDeliminator, const vector< std::string > &sSource)
std::string luajoin (const std::string &sDelimitor, vector< std::string >::const_iterator begin, vector< std::string >::const_iterator end)
RString SmEscape (const RString &sUnescaped)
RString SmEscape (const char *cUnescaped, int len)
RString DwiEscape (const RString &sUnescaped)
RString DwiEscape (const char *cUnescaped, int len)
template<class S >
static int DelimitorLength (const S &Delimitor)
static int DelimitorLength (char Delimitor)
static int DelimitorLength (wchar_t Delimitor)
template<class S , class C >
void do_split (const S &Source, const C Delimitor, vector< S > &AddIt, const bool bIgnoreEmpty)
void split (const RString &sSource, const RString &sDelimitor, vector< RString > &asAddIt, const bool bIgnoreEmpty)
void split (const wstring &sSource, const wstring &sDelimitor, vector< wstring > &asAddIt, const bool bIgnoreEmpty)
template<class S >
void do_split (const S &Source, const S &Delimitor, int &begin, int &size, int len, const bool bIgnoreEmpty)
void split (const RString &Source, const RString &Delimitor, int &begin, int &size, int len, const bool bIgnoreEmpty)
void split (const wstring &Source, const wstring &Delimitor, int &begin, int &size, int len, const bool bIgnoreEmpty)
void split (const RString &Source, const RString &Delimitor, int &begin, int &size, const bool bIgnoreEmpty)
void split (const wstring &Source, const wstring &Delimitor, int &begin, int &size, const bool bIgnoreEmpty)
void splitpath (const RString &sPath, RString &sDir, RString &sFilename, RString &sExt)
RString SetExtension (const RString &sPath, const RString &sExt)
RString GetExtension (const RString &sPath)
RString GetFileNameWithoutExtension (const RString &sPath)
void MakeValidFilename (RString &sName)
bool FindFirstFilenameContaining (const vector< RString > &filenames, RString &out, const vector< RString > &starts_with, const vector< RString > &contains, const vector< RString > &ends_with)
void SetCommandlineArguments (int argc, char **argv)
void GetCommandLineArguments (int &argc, char **&argv)
bool GetCommandlineArgument (const RString &option, RString *argument, int iIndex)
RString GetCwd ()
void CRC32 (unsigned int &iCRC, const void *pVoidBuffer, size_t iSize)
unsigned int GetHashForString (const RString &s)
bool DirectoryIsEmpty (const RString &sDir)
bool CompareRStringsAsc (const RString &sStr1, const RString &sStr2)
bool CompareRStringsDesc (const RString &sStr1, const RString &sStr2)
void SortRStringArray (vector< RString > &arrayRStrings, const bool bSortAscending)
float calc_mean (const float *pStart, const float *pEnd)
float calc_stddev (const float *pStart, const float *pEnd, bool bSample)
bool CalcLeastSquares (const vector< pair< float, float >> &vCoordinates, float &fSlope, float &fIntercept, float &fError)
void FilterHighErrorPoints (vector< pair< float, float >> &vCoordinates, float fSlope, float fIntercept, float fCutoff)
void TrimLeft (RString &sStr, const char *s)
void TrimRight (RString &sStr, const char *s)
void Trim (RString &sStr, const char *s)
void StripCrnl (RString &s)
bool BeginsWith (const RString &sTestThis, const RString &sBeginning)
bool EndsWith (const RString &sTestThis, const RString &sEnding)
RString URLEncode (const RString &sStr)
static bool CVSOrSVN (const RString &s)
void StripCvsAndSvn (vector< RString > &vs)
static bool MacResourceFork (const RString &s)
void StripMacResourceForks (vector< RString > &vs)
RString DerefRedir (const RString &_path)
bool GetFileContents (const RString &sPath, RString &sOut, bool bOneLine)
bool GetFileContents (const std::string &sPath, std::string &sOut, bool bOneLine)
bool GetFileContents (const RString &sFile, vector< RString > &asOut)
bool GetFileContents (const std::string &sFile, vector< std::string > &asOut)
int utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
static bool is_utf8_continuation_byte (char c)
bool utf8_to_wchar_ec (const RString &s, unsigned &start, wchar_t &ch)
bool utf8_to_wchar (const char *s, size_t iLength, unsigned &start, wchar_t &ch)
Decode a code point and place within the output variable.
void wchar_to_utf8 (wchar_t ch, RString &out)
wchar_t utf8_get_char (const RString &s)
bool utf8_is_valid (const RString &s)
void utf8_remove_bom (RString &sLine)
void MakeUpper (char *p, size_t iLen)
void MakeLower (char *p, size_t iLen)
void MakeUpper (wchar_t *p, size_t iLen)
void MakeLower (wchar_t *p, size_t iLen)
int StringToInt (const RString &sString)
Have a standard way of converting Strings to integers.
RString IntToString (const int &iNum)
Have a standard way of converting integers to Strings.
float StringToFloat (const RString &sString)
bool StringToFloat (const RString &sString, float &fOut)
RString FloatToString (const float &num)
wstring RStringToWstring (const RString &s)
RString WStringToRString (const wstring &sStr)
RString WcharToUTF8 (wchar_t c)
void ReplaceEntityText (RString &sText, const map< RString, RString > &m)
void ReplaceEntityText (RString &sText, const map< char, RString > &m)
void Replace_Unicode_Markers (RString &sText)
RString WcharDisplayText (wchar_t c)
RString Basename (const RString &sDir)
RString Dirname (const RString &dir)
RString Capitalize (const RString &s)
void FixSlashesInPlace (RString &sPath)
void CollapsePath (RString &sPath, bool bRemoveLeadingDot)
template<>
bool StringConversion::FromString< int > (const RString &sValue, int &out)
template<>
bool StringConversion::FromString< unsigned > (const RString &sValue, unsigned &out)
template<>
bool StringConversion::FromString< float > (const RString &sValue, float &out)
template<>
bool StringConversion::FromString< bool > (const RString &sValue, bool &out)
template<>
RString StringConversion::ToString< int > (const int &value)
template<>
RString StringConversion::ToString< unsigned > (const unsigned &value)
template<>
RString StringConversion::ToString< float > (const float &value)
template<>
RString StringConversion::ToString< bool > (const bool &value)
bool FileCopy (const RString &sSrcFile, const RString &sDstFile)
bool FileCopy (RageFileBasic &in, RageFileBasic &out, RString &sError, bool *bReadError)
LuaFunction (SecondsToMSSMsMs, SecondsToMSSMsMs(FArg(1))) LuaFunction(SecondsToHHMMSS
SecondsToHHMMSS (FArg(1))) LuaFunction(SecondsToMMSSMsMs
SecondsToMMSSMsMs (FArg(1))) LuaFunction(SecondsToMMSSMsMsMs
SecondsToMMSSMsMsMs (FArg(1))) LuaFunction(SecondsToMSS
SecondsToMSS (FArg(1))) LuaFunction(SecondsToMMSS
SecondsToMMSS (FArg(1))) LuaFunction(FormatNumberAndSuffix
FormatNumberAndSuffix (IArg(1))) LuaFunction(Basename
Basename (SArg(1))) static RString MakeLower(RString s)
LuaFunction (Lowercase, MakeLower(SArg(1))) static RString MakeUpper(RString s)
LuaFunction (Uppercase, MakeUpper(SArg(1))) LuaFunction(mbstrlen
int RStringToWstring (SArg(1)).length()) LuaFunction(URLEncode
int URLEncode (SArg(1)))
LuaFunction (PrettyPercent, PrettyPercent(FArg(1), FArg(2)))
LuaFunction (lerp, lerp(FArg(1), FArg(2), FArg(3)))
int LuaFunc_commify (lua_State *L)
LUAFUNC_REGISTER_COMMON (commify)
void luafunc_approach_internal (lua_State *L, int valind, int goalind, int speedind, float mult)
void luafunc_approach_internal (lua_State *L, int valind, int goalind, int speedind, const float mult, int process_index)
int LuaFunc_approach (lua_State *L)
LUAFUNC_REGISTER_COMMON (approach)
int LuaFunc_multiapproach (lua_State *L)
LUAFUNC_REGISTER_COMMON (multiapproach)
int LuaFunc_get_music_file_length (lua_State *L)
LUAFUNC_REGISTER_COMMON (get_music_file_length)
Variables
RandomGen g_RandomNumberGenerator
static LocalizedString NUM_PREFIX ("RageUtil", "NumPrefix")
static LocalizedString NUM_ST ("RageUtil", "NumSt")
static LocalizedString NUM_ND ("RageUtil", "NumNd")
static LocalizedString NUM_RD ("RageUtil", "NumRd")
static LocalizedString NUM_TH ("RageUtil", "NumTh")
static const LanguageInfo g_langs []
int g_argc = 0
char ** g_argv = NULL
const wchar_t INVALID_CHAR = 0xFFFD
unsigned char g_UpperCase [256]
unsigned char g_LowerCase [256]
Macro Definition Documentation
FMT_BLOCK_SIZE
#define FMT_BLOCK_SIZE 2048
Referenced by vssprintf().
TONUMBER_NICE
#define TONUMBER_NICE (dest, num_name, index)
Value:
if (!lua_isnumber(L, index)) {                                             \
        luaL_error(L,                                                          \
                   "approach: " #num_name " for approach %d is not a number.", \
                   process_index);                                             \
    }                                                                          \
    (dest) = static_cast<float>(lua_tonumber(L, index));
Referenced by luafunc_approach_internal().
Function Documentation
Basename() [1/2]
RString Basename (const RString & sDir)
Referenced by DirectFilenameDB::CacheFile(), ChangeToDirOfExecutable(), RageTextureManager::DiagnosticOutput(), SongManager::DifferentialReloadDir(), ScreenPackages::EnterURL(), FilenameDB::FlushDirCache(), FilenameDB::GetFileSet(), BackgroundUtil::GetGlobalBGAnimations(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), RageSound::Load(), BGAnimation::LoadFromAniDir(), SongManager::LoadStepManiaSongDir(), LocalProfileDirToID(), MakeTempFilename(), Download::MakeTempFileName(), FileTransfer::StartTransfer(), Song::TidyUpData(), GameSoundManager::Update(), and ScreenTestSound::UpdateText().
Basename() [2/2]
Basename (SArg(1))
BeginsWith()
bool BeginsWith (const RString & sTestThis, const RString & sBeginning)
References ASSERT.
Referenced by IsHTTPProtocol(), LoadFromKSFFile(), LoadGlobalData(), DirectFilenameDB::PopulateFileSet(), PrefsManager::ReadGamePrefsFromIni(), SongManager::UpdatePreferredSort(), and SongManager::WasLoadedFromAdditionalSongs().
BinaryToHex() [1/2]
RString BinaryToHex (const void * pData_, int iNumBytes)
References ssprintf().
Referenced by LunaProfile::AddScreenshot(), BinaryToHex(), HighScoreImpl::CreateEttNode(), DoInstalls(), FillInHighScore(), Steps::GenerateBustedChartKey(), Steps::GenerateChartKey(), Song::GetFileHash(), ScreenEvaluation::Input(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), DBProfile::LoadPlayerScores(), NetworkSyncManager::MD5Hex(), and DBProfile::SavePlayerScores().
BinaryToHex() [2/2]
RString BinaryToHex (const RString & sString)
References BinaryToHex().
calc_mean()
float calc_mean (const float * pStart, const float * pEnd)
References f.
Referenced by AdjustSync::AutosyncOffset(), and calc_stddev().
calc_stddev()
float calc_stddev (const float * pStart, const float * pEnd, bool bSample)
References calc_mean().
Referenced by AdjustSync::AutosyncOffset().
CalcLeastSquares()
bool CalcLeastSquares (const vector< pair< float, float >> & vCoordinates, float & fSlope, float & fIntercept, float & fError)
Referenced by AdjustSync::AutosyncTempo().
Capitalize()
RString Capitalize (const RString & s)
References MakeUpper().
Referenced by SongUtil::AdjustDuplicateSteps(), GhostArrowRow::DidHoldNote(), GhostArrowRow::DidTapNote(), InputHandler::GetDeviceSpecificInputString(), RageInput::GetLocalizedInputString(), InputHandler::GetLocalizedInputString(), PlayerOptions::GetLocalizedMods(), PlayerOptions::GetMods(), ReceptorArrow::Step(), and GameManager::StyleToLocalizedString().
CollapsePath()
void CollapsePath (RString & sPath, bool bRemoveLeadingDot)
Referenced by BGAnimation::AddLayersFromAniDir(), ChangeToDirOfExecutable(), DerefRedir(), Song::GetSongAssetPath(), HoldJudgment::LoadFromNode(), BGAnimationLayer::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), NormalizePath(), ActorUtil::ResolvePath(), RageTextureID::SetFilename(), and SplitPath().
Commify() [1/2]
RString Commify (int iNum)
References Commify(), and ssprintf().
Referenced by Commify(), LuaFunc_commify(), and RollingNumbers::UpdateText().
Commify() [2/2]
RString Commify (const RString & num, const RString & sep, const RString & dot)
CompareRStringsAsc()
bool CompareRStringsAsc (const RString & sStr1, const RString & sStr2)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by CompareSongPointersByBPM(), CompareSongPointersByLength(), SongManager::Comp::operator()(), and SortRStringArray().
CompareRStringsDesc()
bool CompareRStringsDesc (const RString & sStr1, const RString & sStr2)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by SortRStringArray().
ConvertI64FormatString()
RString ConvertI64FormatString (const RString & sStr)
Referenced by ActorFrameTexture::ActorFrameTexture().
CRC32()
void CRC32 (unsigned int & iCRC, const void * pVoidBuffer, size_t iSize)
Referenced by GetHashForString().
CVSOrSVN()
static bool CVSOrSVN (const RString & s) static
References StdString::CStdStr< CT >::EqualsNoCase(), and StdString::CStdStr< CT >::Right().
Referenced by StripCvsAndSvn().
DelimitorLength() [1/3]
template<class S > static int DelimitorLength (const S & Delimitor) static
Referenced by do_split().
DelimitorLength() [2/3]
static int DelimitorLength (char Delimitor) static
DelimitorLength() [3/3]
static int DelimitorLength (wchar_t Delimitor) static
DerefRedir()
RString DerefRedir (const RString & _path)
References CollapsePath(), Dirname(), GetDirListing(), GetExtension(), GetFileContents(), and RageException::Throw().
Referenced by Character::GetDanceAnimationPath(), Character::GetRestAnimationPath(), Character::GetWarmUpAnimationPath(), and ActorUtil::ResolvePath().
DirectoryIsEmpty()
bool DirectoryIsEmpty (const RString & sDir)
References DoesFileExist(), and GetDirListing().
Referenced by AnnouncerManager::GetPathTo(), and AnnouncerManager::HasSoundsFor().
Dirname()
RString Dirname (const RString & dir)
Referenced by BMSSong::AllocateKeysound(), XmlFileUtil::AnnotateXNodeTree(), DirectFilenameDB::CacheFile(), FilenameDB::CacheFile(), DerefRedir(), ScreenPackages::EnterURL(), RageFileObjDirect::FinalFlush(), FilenameDB::FlushDirCache(), BMSSong::GetBackground(), FilenameDB::GetFileSet(), ScreenGameplaySyncMachine::Init(), AnimatedTexture::Load(), actor_template_t::load_node(), ActorUtil::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), MakeTempFilename(), RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), FileTransfer::StartTransfer(), and RageFileObjDirect::~RageFileObjDirect().
do_split() [1/2]
template<class S , class C > void do_split (const S & Source, const C Delimitor, vector< S > & AddIt, const bool bIgnoreEmpty)
References DelimitorLength().
Referenced by split().
do_split() [2/2]
template<class S > void do_split (const S & Source, const S & Delimitor, int & begin, int & size, int len, const bool bIgnoreEmpty)
References min().
DwiEscape() [1/2]
RString DwiEscape (const RString & sUnescaped)
References DwiEscape().
Referenced by DwiEscape(), and NotesWriterDWI::Write().
DwiEscape() [2/2]
RString DwiEscape (const char * cUnescaped, int len)
EndsWith()
bool EndsWith (const RString & sTestThis, const RString & sEnding)
References ASSERT.
Referenced by ActorUtil::LoadAllCommandsFromName(), LoadFromKSFFile(), Actor::LoadFromNode(), ThemeManager::PushMetric(), and SongManager::UpdatePreferredSort().
fapproach()
void fapproach (float & val, float other_val, float to_move)
References ASSERT_M, and ssprintf().
Referenced by PlayerOptions::Approach(), luafunc_approach_internal(), GameSoundManager::Update(), RollingNumbers::Update(), ScreenDebugOverlay::Update(), and ActorScroller::UpdateInternal().
FileCopy() [1/2]
bool FileCopy (const RString & sSrcFile, const RString & sDstFile)
References StdString::CStdStr< CT >::CompareNoCase(), FileCopy(), LOG, RageFile::Open(), RageFile::READ, RageLog::Warn(), and RageFile::WRITE.
Referenced by CopyEdits(), FileCopy(), DownloadManager::InstallSmzip(), RageSoundReader_FileReader::OpenFile(), Song::Save(), Profile::SaveMachinePublicKeyToDir(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), Song::SaveToSSCFile(), and SyncFiles().
FileCopy() [2/2]
bool FileCopy (RageFileBasic & in, RageFileBasic & out, RString & sError, bool * bReadError)
References RageFileBasic::Flush(), RageFileBasic::GetError(), RageFileBasic::Read(), ssprintf(), and RageFileBasic::Write().
FilterHighErrorPoints()
void FilterHighErrorPoints (vector< pair< float, float >> & vCoordinates, float fSlope, float fIntercept, float fCutoff)
Referenced by AdjustSync::AutosyncTempo().
FindFirstFilenameContaining()
bool FindFirstFilenameContaining (const vector< RString > & filenames, RString & out, const vector< RString > & starts_with, const vector< RString > & contains, const vector< RString > & ends_with)
References GetFileNameWithoutExtension(), and StdString::CStdStr< CT >::MakeLower().
Referenced by Song::TidyUpData().
FixSlashesInPlace()
void FixSlashesInPlace (RString & sPath)
Referenced by AdjustMountpoint(), FixupPath(), RageFileManager::GetFileDriver(), BGAnimationLayer::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), RageFileManager::Mount(), NormalizePath(), RageFile::Open(), and RageFileManager::Unmount().
FloatToString()
RString FloatToString (const float & num)
Referenced by convert_xpos(), convert_ypos(), HighScoreImpl::CreateEttNode(), NoteField::DrawPrimitives(), actor_template_t::output_to_file(), and TimingSegment::ToString().
fmodfp()
float fmodfp (float x, float y)
Referenced by Actor::PreDraw(), and StartMusic().
FormatNumberAndSuffix() [1/2]
RString FormatNumberAndSuffix (int i)
References LocalizedString::GetValue(), NUM_ND, NUM_PREFIX, NUM_RD, NUM_ST, NUM_TH, and ssprintf().
Referenced by AdjustSync::GetSyncChangeTextSong().
FormatNumberAndSuffix() [2/2]
FormatNumberAndSuffix (IArg(1))
GetCommandlineArgument()
bool GetCommandlineArgument (const RString & option, RString * argument, int iIndex)
References StdString::CStdStr< CT >::CompareNoCase(), and g_argc.
Referenced by GameState::ApplyCmdline(), PrefsManager::GetPreferencesSection(), CommandLineActions::Handle(), StepMania::InitializeCurrentGame(), ThemeManager::LoadThemeMetrics(), sm_main(), and NetworkSyncManager::StartUp().
GetCommandLineArguments()
void GetCommandLineArguments (int & argc, char **& argv)
References g_argc, and g_argv.
GetCwd()
RString GetCwd ()
References ASSERT.
Referenced by ChangeToDirOfExecutable(), and GetDirOfExecutable().
GetExtension()
RString GetExtension (const RString & sPath)
Referenced by DerefRedir(), DoInstalls(), Song::GetCacheFile(), RageFileManager::GetDirListingWithMultipleExtensions(), ActorUtil::GetFileType(), Steps::GetNoteDataFromSimfile(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfoToRaw(), DownloadManager::InstallSmzip(), IsPackageFile(), RandomSample::Load(), Model::Load(), AnimatedTexture::Load(), Font::Load(), actor_template_t::load_node(), RageSurfaceUtils::LoadFile(), SSCLoader::LoadNoteDataFromSimfile(), RageSoundReader_FileReader::OpenFile(), Song::RemoveAutosave(), SongManager::SanityCheckGroupDir(), Song::SaveToETTFile(), Song::SaveToSSCFile(), StartMusic(), and Song::TidyUpData().
GetFileContents() [1/4]
bool GetFileContents (const RString & sPath, RString & sOut, bool bOneLine)
References RageFile::GetError(), RageFile::GetFileSize(), RageFile::GetLine(), IsAFile(), LOG, RageFile::Open(), RageFile::Read(), StripCrnl(), and RageLog::Warn().
Referenced by DerefRedir(), CryptManager::GenerateGlobalKeys(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfoToRaw(), PrefsManager::GetPreferencesSection(), Alsa9Buf::GetSoundCardDebugInfo(), ScreenWithMenuElements::HandleLuaMusicFile(), NoteSkinManager::LoadNoteSkinDataRecursive(), LuaHelpers::run_script_file_in_state(), LuaHelpers::RunScriptFile(), CryptManager::SignFileToFile(), SongManager::UpdatePreferredSort(), and CryptManager::VerifyFileWithFile().
GetFileContents() [2/4]
bool GetFileContents (const std::string & sPath, std::string & sOut, bool bOneLine)
References RageFile::GetError(), RageFile::GetFileSize(), RageFile::GetLine(), IsAFile(), LOG, RageFile::Open(), RageFile::Read(), StripCrnl(), and RageLog::Warn().
GetFileContents() [3/4]
bool GetFileContents (const RString & sFile, vector< RString > & asOut)
References RageFile::GetError(), RageFile::GetLine(), LOG, RageFile::Open(), and RageLog::Warn().
GetFileContents() [4/4]
bool GetFileContents (const std::string & sFile, vector< std::string > & asOut)
References RageFile::GetError(), RageFile::GetLine(), LOG, RageFile::Open(), and RageLog::Warn().
GetFileNameWithoutExtension()
RString GetFileNameWithoutExtension (const RString & sPath)
References splitpath().
Referenced by FindFirstFilenameContaining(), BackgroundUtil::GetBackgroundEffects(), and BackgroundUtil::GetBackgroundTransitions().
GetHashForString()
unsigned int GetHashForString (const RString & s)
References CRC32().
Referenced by Steps::GetHash(), GetHashForDirectory(), and BackgroundImpl::LoadFromSong().
GetLanguageInfo()
const LanguageInfo* GetLanguageInfo (const RString & sIsoCode)
References ARRAYLEN, StdString::CStdStr< CT >::EqualsNoCase(), and LanguageInfo::szIsoCode.
Referenced by ScreenSelectLanguage::Init(), LanguageChoices(), and Nsis().
GetLanguageInfos()
void GetLanguageInfos (vector< const LanguageInfo *> & vAddTo)
References ARRAYLEN.
GetLocalTime()
struct tm GetLocalTime ()
HexToBinary() [1/2]
bool HexToBinary (const RString & s, RString & sOut)
HexToBinary() [2/2]
bool HexToBinary (const RString & s, unsigned char * stringOut)
References IsHexVal().
HHMMSSToSeconds()
float HHMMSSToSeconds (const RString & sHHMMSS)
References split(), StringToFloat(), and StringToInt().
Referenced by LyricsLoader::LoadFromLRCFile(), SMALoader::LoadFromSimfile(), LoadGlobalData(), ParseBrokenDWITimestamp(), SetSampleLength(), SetSampleStart(), SMSetSampleLength(), and SMSetSampleStart().
IntToString()
RString IntToString (const int & iNum)
Have a standard way of converting integers to Strings.
Parameters
iNum the integer to convert.
Returns
the string we are after.
Referenced by GetSMNotesTag(), MenuRowDef::MenuRowDef(), actor_template_t::output_to_file(), RadarValues::ToString(), FakeSegment::ToString(), WarpSegment::ToString(), TickcountSegment::ToString(), ComboSegment::ToString(), LabelSegment::ToString(), BPMSegment::ToString(), TimeSignatureSegment::ToString(), SpeedSegment::ToString(), ScrollSegment::ToString(), StopSegment::ToString(), and DelaySegment::ToString().
is_utf8_continuation_byte()
static bool is_utf8_continuation_byte (char c) inline static
Referenced by utf8_to_wchar_ec().
IsAnInt()
bool IsAnInt (const RString & s)
Referenced by GameState::ApplyCmdline(), ActorFrame::LoadChildrenFromNode(), and Font::LoadFontPageSettings().
IsHexVal()
bool IsHexVal (const RString & s)
Referenced by HexToBinary(), and Font::LoadFontPageSettings().
join() [1/2]
RString join (const RString & sDeliminator, const vector< RString > & sSource)
join() [2/2]
RString join (const RString & sDelimitor, vector< RString >::const_iterator begin, vector< RString >::const_iterator end)
LUA_REGISTER_NAMESPACE()
LUA_REGISTER_NAMESPACE (MersenneTwister)
LuaFunc_approach()
int LuaFunc_approach (lua_State * L)
References f, and luafunc_approach_internal().
luafunc_approach_internal() [1/2]
void luafunc_approach_internal (lua_State * L, int valind, int goalind, int speedind, float mult)
Referenced by LuaFunc_approach(), and LuaFunc_multiapproach().
luafunc_approach_internal() [2/2]
void luafunc_approach_internal (lua_State * L, int valind, int goalind, int speedind, const float mult, int process_index)
References fapproach(), and TONUMBER_NICE.
LuaFunc_commify()
int LuaFunc_commify (lua_State * L)
References Commify(), LuaHelpers::Push(), and SArg.
LuaFunc_get_music_file_length()
int LuaFunc_get_music_file_length (lua_State * L)
References RageSoundReader::GetLength(), RageSoundReader_FileReader::OpenFile(), and SArg.
LuaFunc_multiapproach()
int LuaFunc_multiapproach (lua_State * L)
References luafunc_approach_internal().
LUAFUNC_REGISTER_COMMON() [1/4]
LUAFUNC_REGISTER_COMMON (commify)
LUAFUNC_REGISTER_COMMON() [2/4]
LUAFUNC_REGISTER_COMMON (approach)
LUAFUNC_REGISTER_COMMON() [3/4]
LUAFUNC_REGISTER_COMMON (multiapproach)
LUAFUNC_REGISTER_COMMON() [4/4]
LUAFUNC_REGISTER_COMMON (get_music_file_length)
LuaFunction() [1/5]
LuaFunction (SecondsToMSSMsMs , SecondsToMSSMsMs(FArg(1)))
LuaFunction() [2/5]
LuaFunction (Lowercase , MakeLower(SArg(1)))
LuaFunction() [3/5]
LuaFunction (Uppercase , MakeUpper(SArg(1)))
LuaFunction() [4/5]
LuaFunction (PrettyPercent , PrettyPercent(FArg(1), FArg(2)))
LuaFunction() [5/5]
LuaFunction (lerp , lerp(FArg(1), FArg(2), FArg(3)))
luajoin() [1/2]
std::string luajoin (const std::string & sDeliminator, const vector< std::string > & sSource)
Referenced by GetLuaStack().
luajoin() [2/2]
std::string luajoin (const std::string & sDelimitor, vector< std::string >::const_iterator begin, vector< std::string >::const_iterator end)
MacResourceFork()
static bool MacResourceFork (const RString & s) static
References StdString::CStdStr< CT >::EqualsNoCase(), and StdString::CStdStr< CT >::Left().
Referenced by StripMacResourceForks().
MakeLower() [1/2]
void MakeLower (char * p, size_t iLen)
Referenced by StdString::sslwr().
MakeLower() [2/2]
void MakeLower (wchar_t * p, size_t iLen)
References L.
MakeUpper() [1/2]
void MakeUpper (char * p, size_t iLen)
Referenced by InputHandler::ApplyKeyModifiers(), Capitalize(), ScreenNetSelectBase::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), and StdString::ssupr().
MakeUpper() [2/2]
void MakeUpper (wchar_t * p, size_t iLen)
References L.
MakeValidFilename()
void MakeValidFilename (RString & sName)
References L, RStringToWstring(), w, and WStringToRString().
Referenced by NotesWriterSM::GetEditFileName(), and NotesWriterSSC::GetEditFileName().
power_of_two()
int power_of_two (int input)
Referenced by ImageCache::CacheImageInternal(), RageBitmapTexture::Create(), MovieTexture_DShow::Create(), RenderTarget_MacOSX::Create(), ImageTexture::Create(), RenderTarget_Win32::Create(), RenderTarget_X11::Create(), D3DRenderTarget_FramebufferObject::Create(), RenderTarget_FramebufferObject::Create(), RageDisplay_D3D::CreateTexture(), RageDisplay_Legacy::CreateTexture(), MovieTexture_Generic::CreateTexture(), and MovieTexture_Null::MovieTexture_Null().
PrettyPercent()
RString PrettyPercent (float fNumerator, float fDenominator)
References ssprintf().
Referenced by PrettyPercent().
Replace_Unicode_Markers()
void Replace_Unicode_Markers (RString & sText)
References INVALID_CHAR, and WcharToUTF8().
Referenced by FontCharAliases::ReplaceMarkers().
ReplaceEntityText() [1/2]
void ReplaceEntityText (RString & sText, const map< RString, RString > & m)
References StdString::CStdStr< CT >::MakeLower().
Referenced by FontCharAliases::ReplaceMarkers().
ReplaceEntityText() [2/2]
void ReplaceEntityText (RString & sText, const map< char, RString > & m)
References ASSERT, and FOREACHM_CONST.
RStringToWstring() [1/2]
wstring RStringToWstring (const RString & s)
References picosha2::detail::ch(), INVALID_CHAR, L, and utf8_to_wchar().
Referenced by ScreenTextEntry::BeginScreen(), MovieTexture_DShow::Create(), Profile::LoadEditableDataFromDir(), Font::LoadFontPageSettings(), MakeValidFilename(), BitmapText::SetTextInternal(), ColorBitmapText::SimpleAddLine(), BitmapText::StringWillUseAlternate(), and ScreenTextEntry::TryAppendToAnswer().
RStringToWstring() [2/2]
int RStringToWstring (SArg(1))
SecondsToHHMMSS() [1/2]
RString SecondsToHHMMSS (float fSecs)
References ssprintf().
SecondsToHHMMSS() [2/2]
SecondsToHHMMSS (FArg(1))
SecondsToMMSS() [1/2]
RString SecondsToMMSS (float fSecs)
References ssprintf().
Referenced by SongUtil::GetSectionNameFromSongAndSort().
SecondsToMMSS() [2/2]
SecondsToMMSS (FArg(1))
SecondsToMMSSMsMs() [1/2]
RString SecondsToMMSSMsMs (float fSecs)
References min(), and ssprintf().
Referenced by ScreenEvaluation::Init(), ScoreDisplayOni::Update(), and ScoreDisplayAliveTime::UpdateNumber().
SecondsToMMSSMsMs() [2/2]
SecondsToMMSSMsMs (FArg(1))
SecondsToMMSSMsMsMs() [1/2]
RString SecondsToMMSSMsMsMs (float fSecs)
References min(), and ssprintf().
Referenced by DebugLineUptime::GetDisplayValue(), and RageLog::Write().
SecondsToMMSSMsMsMs() [2/2]
SecondsToMMSSMsMsMs (FArg(1))
SecondsToMSS() [1/2]
RString SecondsToMSS (float fSecs)
References ssprintf().
SecondsToMSS() [2/2]
SecondsToMSS (FArg(1))
SecondsToMSSMsMs()
RString SecondsToMSSMsMs (float fSecs)
References min(), and ssprintf().
Referenced by ScoreDisplayLifeTime::Update().
seed_lua_prng()
void seed_lua_prng ()
Referenced by sm_main().
SetCommandlineArguments()
void SetCommandlineArguments (int argc, char ** argv)
Referenced by sm_main().
SetExtension()
RString SetExtension (const RString & sPath, const RString & sExt)
References splitpath().
Referenced by BMSSong::AllocateKeysound(), BMSSong::GetBackground(), Song::GetFileHash(), Font::GetFontPaths(), Song::HasAutosaveFile(), actor_template_t::load_node(), GameSoundManager::PlayMusic(), BMSSong::PrecacheBackgrounds(), Song::RemoveAutosave(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), and Song::SaveToSSCFile().
SmEscape() [1/2]
RString SmEscape (const RString & sUnescaped)
References SmEscape().
Referenced by emplace_back_tag(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), SmEscape(), BackgroundChange::ToString(), write_tag(), and WriteGlobalTags().
SmEscape() [2/2]
RString SmEscape (const char * cUnescaped, int len)
SortRStringArray()
void SortRStringArray (vector< RString > & arrayRStrings, const bool bSortAscending)
References CompareRStringsAsc(), and CompareRStringsDesc().
Referenced by SongManager::DifferentialReloadDir(), ScreenSelectLanguage::Init(), Language(), LanguageChoices(), BGAnimation::LoadFromAniDir(), SongManager::LoadStepManiaSongDir(), and ThemeManager::RunLuaScripts().
split() [1/6]
void split (const RString & sSource, const RString & sDelimitor, vector< RString > & asAddIt, const bool bIgnoreEmpty)
References do_split().
Referenced by HHMMSSToSeconds().
split() [2/6]
void split (const wstring & sSource, const wstring & sDelimitor, vector< wstring > & asAddIt, const bool bIgnoreEmpty)
References do_split().
split() [3/6]
void split (const RString & Source, const RString & Delimitor, int & begin, int & size, int len, const bool bIgnoreEmpty)
References do_split().
split() [4/6]
void split (const wstring & Source, const wstring & Delimitor, int & begin, int & size, int len, const bool bIgnoreEmpty)
References do_split().
split() [5/6]
void split (const RString & Source, const RString & Delimitor, int & begin, int & size, const bool bIgnoreEmpty)
References do_split().
split() [6/6]
void split (const wstring & Source, const wstring & Delimitor, int & begin, int & size, const bool bIgnoreEmpty)
References do_split().
splitpath()
void splitpath (const RString & sPath, RString & sDir, RString & sFilename, RString & sExt)
References ASSERT, and Regex::Compare().
Referenced by CharacterManager::CharacterManager(), GetFileNameWithoutExtension(), RageMovieTexture::GetFourCC(), DownloadManager::InstallSmzip(), InstallSmzipOsArg(), LoadFromKSFFile(), Nsis(), and SetExtension().
ssprintf()
RString ssprintf (const char * fmt, ...)
References vssprintf().
Referenced by ActorFrameTexture::ActorFrameTexture(), ActorFrame::AddChild(), NoteData::AddHoldNote(), ScreenManager::AddNewScreenToTop(), AddPart(), Song::AddSteps(), ScreenOptions::AfterChangeValueOrRow(), ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::AfterStepsOrTrailChange(), LuaBinding::ApplyDerivedType(), StageStats::AssertValid(), ATTACK_DISPLAY_X_NAME(), AdjustSync::AutosyncOffset(), averr_ssprintf(), BackgroundLoader::BackgroundLoader(), ScreenOptionsManageProfiles::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenPrompt::BeginScreen(), BinaryToHex(), BustypeToString(), DirectFilenameDB::CacheFile(), RageFileManager::CacheFile(), ScreenPrompt::CanGoRight(), GameState::CanSafelyEnterGameplay(), LifeMeterBar::ChangeLife(), LifeMeterTime::ChangeLife(), ScreenSelectMaster::ChangePage(), ScreenSetTime::ChangeValue(), CheckCodecVersion(), CheckEnum(), CheckPalettedTextures(), DSoundBuf::CheckUnderrun(), CHOICE_NAME(), Commify(), CompileShader(), SMOProtocol::Connect(), RageSoundReader_Vorbisfile::Copy(), CopyEdits(), RageBitmapTexture::Create(), RenderTarget_FramebufferObject::Create(), BackgroundImpl::Layer::CreateBackground(), CreateDirectories(), CreateDisplay(), ITween::CreateFromType(), ProfileManager::CreateLocalProfile(), ScoresAtRate::CreateNode(), Chart::CreateNode(), MovieTexture_DShow::CreateTexture(), MovieTexture_Generic::CreateTexture(), CURSOR_OFFSET_X_FROM_ICON_NAME(), CURSOR_OFFSET_Y_FROM_ICON_NAME(), CUSTOM_WHEEL_ITEM_COLOR(), CUSTOM_WHEEL_ITEM_NAME(), DayInYearToString(), WavReaderADPCM::DecodeADPCMBlock(), RageSoundDriver::DecodeThread(), DefaultLocalProfileIDInit(), DeleteNoteResource(), DeviceButtonToString(), RageTextureManager::DiagnosticOutput(), GhostArrowRow::DidTapNote(), DisplayResolutionChoices(), NetworkSyncManager::DisplayStartupStatus(), DebugLineVolumeDown::DoAndLog(), DebugLineVisualDelayDown::DoAndLog(), NoteDisplay::DrawActor(), NoteField::DrawBeatBar(), NoteDisplay::DrawHoldsInRange(), NoteField::DrawPrimitives(), NoteDisplay::DrawTapsInRange(), ArchHooks_MacOSX::DumpDebugInfo(), TimingData::DumpOneTable(), DumpPixelFormat(), DWIcharToNote(), emplace_back_tag(), NoteField::ensure_note_displays_have_skin(), ScreenPackages::EnterURL(), DSound::EnumCallback(), EnumToString(), Alsa9Buf::ErrorHandler(), EventDeviceExists(), ScreenOptionsMaster::ExportOptions(), ExportPackage(), fapproach(), FileCopy(), RageFileObj::FillReadBuf(), RageFileObjDirect::FinalFlush(), RageSurfaceUtils::FindSurfaceTraits(), BackgroundLoader::FinishedWithCachedFile(), AutoKeysounds::FinishLoading(), FixLilEndian(), FixLittleEndian(), ScreenTextEntry::FloatValidate(), RageFileObjDeflate::FlushInternal(), FormatNumberAndSuffix(), PlayerStageStats::FormatPercentScore(), PlayerOptions::FromOneModString(), RageTextureManager::GarbageCollect(), CryptManager::GenerateRandomUUID(), GenerateRankingToFillInMarker(), DSoundBuf::get_output_buf(), GetActualGraphicOptionsString(), SongCacheIndex::GetCacheFilePath(), NetworkSyncManager::GetCurrentSMBuild(), LuaThreadVariable::GetCurrentThreadIDString(), RageSoundDriver_OSS::GetData(), RageSound::GetDataToPlay(), GetDebugButtonName(), RageInput::GetDisplayDevicesString(), DebugLineAutoplay::GetDisplayValue(), DebugLineAutosync::GetDisplayValue(), DebugLineVolumeUp::GetDisplayValue(), DebugLineVisualDelayUp::GetDisplayValue(), NotesWriterSM::GetEditFileContents(), NotesWriterSSC::GetEditFileContents(), GameManager::GetEditorStyleForStepsType(), GetETTNoteData(), SongManager::GetExtraStageInfo(), RageFileObjDirect::GetFileSize(), GetFilterToFileNames(), GameManager::GetHowToPlayStyleForGame(), GameManager::GetIndexFromGame(), LunaHighScore::GetJudgmentString(), Actor::GetLineage(), LuaHelpers::GetLuaInformation(), GetLuaStack(), ThemeManager::GetMetricRaw(), SongOptions::GetMods(), PlayerOptions::GetMods(), GetMountDir(), PlayerInfo::GetName(), PaneDisplay::GetPaneTextAndLevel(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfoToRaw(), RageSoundDriver_OSS::GetPosition(), DSoundBuf::GetPosition(), GetPromptText(), GameState::GetRankingFeats(), OptionRow::GetRowTitle(), SongUtil::GetSectionNameFromSongAndSort(), NoteDataUtil::GetSMNoteDataString(), GetSMNotesTag(), Song::GetSongFilePath(), SongManager::GetSongGroupColor(), Profile::GetSongsActual(), Alsa9Buf::GetSoundCardDebugInfo(), GetSSCNoteData(), RageDisplay::GetStats(), GameManager::GetStepsTypeInfo(), DateTime::GetString(), AdjustSync::GetSyncChangeTextGlobal(), AdjustSync::GetSyncChangeTextSong(), NoteData::GetTapNoteRange(), TapScoreDistribution::GetTapNoteScore(), BackgroundChange::GetTextDescription(), OptionRow::GetTextItemForRow(), Sprite::GetTextureCoordRectForState(), ActorUtil::GetWhere(), ScreenOptions::GetWidthXY(), RageDisplay_Legacy_Helpers::GLToString(), GradeToString(), GrooveRadar::GrooveRadar(), GUIDToString(), GunzipFile(), AdjustSync::HandleAutosync(), GameStateMessageHandler::HandleMessage(), ThreadedFileWorker::HandleRequest(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), HourInDayToLocalizedString(), HourInDayToString(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), OptionRowHandlerList::ImportOption(), ScreenNetEvaluation::Init(), ScreenPlayerOptions::Init(), ScreenSelect::Init(), RageDisplay_GLES2::Init(), LoadingWindow_Gtk::Init(), RageSoundDriver_ALSA9_Software::Init(), RageSoundDriver_PulseAudio::Init(), ScreenMapControllers::Init(), BeginnerHelper::Init(), ScreenNetSelectMusic::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), RageSoundDriver_OSS::Init(), ScreenSelectMusic::Init(), RageDisplay_Legacy::Init(), Alsa9Buf::Init(), ScreenOptions::Init(), ScreenEvaluation::Init(), MovieTexture_Generic::Init(), WavReaderPCM::Init(), ScreenGameplay::Init(), WavReaderADPCM::Init(), PlayerAI::InitFromDisk(), InitializeConfOptions(), OptionRow::InitText(), ScreenSyncOverlay::Input(), ScreenPlayerOptions::Input(), ScreenDebugOverlay::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), InputHandler_Linux_Event::InputThread(), SongCacheIndex::InsertSteps(), SongCacheIndex::InsertStepsTimingData(), ScreenTextEntry::IntValidate(), Song::IsEditAlreadyLoaded(), GameState::IsHumanPlayer(), GameCommand::IsPlayable(), ITEMS_LONG_ROW_X_NAME(), LastWeekToString(), RageFileDriverZip::Load(), DualScrollBar::Load(), LifeMeterBar::Load(), LifeMeterBattery::Load(), DifficultyIcon::Load(), MenuTimer::Load(), NoteField::Load(), PlayerInfo::Load(), AnimatedTexture::Load(), RageSound::Load(), Font::Load(), LoadALSA(), LoadBMP(), FontManager::LoadFont(), BGAnimationLayer::LoadFromAniLayerFile(), XmlFileUtil::LoadFromFileShowErrors(), BitmapText::LoadFromFont(), LoadFromKSFFile(), BGAnimation::LoadFromNode(), BGAnimationLayer::LoadFromNode(), StepsDisplayList::LoadFromNode(), Sprite::LoadFromNode(), ActorUtil::LoadFromNode(), BackgroundImpl::LoadFromSong(), Banner::LoadFromSortOrder(), BitmapText::LoadFromTextureAndChars(), MusicWheelItem::LoadFromWheelItemData(), XMLProfile::LoadGeneralDataFromNode(), ImageCache::LoadImage(), RageModelGeometry::LoadMilkshapeAscii(), GameCommand::LoadOne(), RageSurfaceUtils::LoadSurface(), ActorUtil::LoadTableFromStackShowErrors(), RageTextureManager::LoadTextureInternal(), NoteData::LoadTransformed(), RageMutex::Lock(), SMOProtocol::Login(), Profile::MakeFileNameNoExtension(), Profile::MakeGuid(), LifeMeter::MakeLifeMeter(), MakeNoteResource(), ScoreKeeper::MakeScoreKeeper(), SongUtil::MakeUniqueEditDescription(), FontPageSettings::MapRange(), ScreenSelectMaster::MenuStart(), MOD_ICON_X_NAME(), ModuleError(), RageFileManager::Mount(), ArchHooks::MountUserFilesystems(), RageFileDriverDirect::Move(), RageFileDriverTimeout::Move(), MusicWheelItem::MusicWheelItem(), NoteTypeToBeat(), Nsis(), ActorUtil::OffCommand(), ActorUtil::OnCommand(), RageSoundReader_WAV::Open(), MovieDecoder_FFMpeg::Open(), MovieDecoder_FFMpeg::OpenCodec(), OptimizeDWIString(), ov_ssprintf(), RageFileDriverZip::ParseZipfile(), PathForFolderType(), DirectFilenameDB::PopulateFileSet(), ScreenOptions::PositionCursor(), Actor::PreDraw(), PrettyPercent(), PrintCodecError(), RageFileDriverZip::ProcessCdirFileHdr(), SMOProtocol::ProcessInput(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsExportPackageSubPage::ProcessMenuStart(), ThemeManager::PushMetric(), RageFileObjDeflate::RageFileObjDeflate(), RageFileObjInflate::RageFileObjInflate(), RageSurface_Load_GIF(), RageSurface_Load_XPM(), ScoresForChart::RateKeyToDisplayString(), RageSoundReader_Vorbisfile::Read(), RageSoundReader_Chain::Read(), RageFileDriverZip::ReadEndCentralRecord(), CsvFile::ReadFile(), IniFile::ReadFile(), RageFileObjInflate::ReadInternal(), RageFileDriverZip::ReadLocalFileHeader(), BMSChartReader::ReadNoteData(), ScreenNetEvaluation::RedoUserTexts(), PercentageDisplay::Refresh(), LifeMeterBattery::Refresh(), ScreenGameplaySyncMachine::RefreshText(), ActorUtil::Register(), RegisterScreenClass::RegisterScreenClass(), OptionRowHandlerListSteps::Reload(), RageFileDriverDirect::Remove(), RageFileDriverTimeout::Remove(), Regex::Replace(), LuaHelpers::ReportScriptErrorFmt(), ActorUtil::ResolvePath(), RoutineNoteSkinName(), LuaHelpers::run_script_file_in_state(), LuaHelpers::RunExpression(), LuaHelpers::RunScriptFile(), XMLProfile::SaveGeneralDataCreateNode(), ScreenGameplay::SaveReplay(), Song::SaveToETTFile(), Song::SaveToSSCFile(), SecondsToHHMMSS(), SecondsToMMSS(), SecondsToMMSSMsMs(), SecondsToMMSSMsMsMs(), SecondsToMSS(), SecondsToMSSMsMs(), SECTION_COLORS_NAME(), RageFileDriverZip::SeekToEndCentralRecord(), SegInfoStr(), OptionRowHandlerUtil::SelectExactlyOne(), ComboGraph::Set(), RageDisplay_D3D::SetBlendMode(), BPMDisplay::SetBpmFromSong(), BPMDisplay::SetBPMRange(), RageDisplay_GLES2::SetCullMode(), RageDisplay_D3D::SetCullMode(), RageDisplay_Legacy::SetCullMode(), SetD3DParams(), Actor::SetEffectTiming(), WheelNotifyIcon::SetFlags(), HoldJudgment::SetHoldJudgment(), InputMappings::SetInputMap(), StepsDisplay::SetInternal(), ScreenRanking::SetPage(), RageDisplay_GLES2::SetPolygonMode(), RageDisplay_Legacy::SetPolygonMode(), RoomInfoDisplay::SetRoomInfo(), Sprite::SetState(), ArchHooks_Unix::SetTime(), ActorScroller::SetTransformFromHeight(), ActorScroller::SetTransformFromWidth(), XNodeStringValue::SetValue(), DSoundBuf::SetVolume(), RageDisplay_GLES2::SetZTestMode(), RageDisplay_D3D::SetZTestMode(), RageDisplay_Legacy::SetZTestMode(), GameState::ShowW1(), SONG_GROUP_COLOR_NAME(), SongUtil::SortSongPointerArrayByNumPlays(), SongUtil::SortSongPointerArrayByStepsTypeAndMeter(), StepsUtil::SortStepsPointerArrayByNumPlays(), StartQueuedSounds(), FileTransfer::StartTransfer(), Player::Step(), STEPS_TYPE_COLOR_NAME(), Style::StyleInputToGameInput(), MessageManager::Subscribe(), SuperShuffleTaps(), ThreadedFileWorker::ThreadedFileWorker(), RageException::Throw(), TimingWindowSecondsInit(), ToDerived(), StepsID::ToSteps(), BackgroundChange::ToString(), FakeSegment::ToString(), StepsID::ToString(), WarpSegment::ToString(), TickcountSegment::ToString(), ComboSegment::ToString(), RageColor::ToString(), LabelSegment::ToString(), BPMSegment::ToString(), TimeSignatureSegment::ToString(), SpeedSegment::ToString(), ScrollSegment::ToString(), StopSegment::ToString(), DelaySegment::ToString(), StringConversion::ToString< bool >(), StringConversion::ToString< float >(), StringConversion::ToString< int >(), StringConversion::ToString< unsigned >(), InputHandler_Linux_Joystick::TryDevice(), LowLevelWindow_Win32::TryVideoMode(), LowLevelWindow_MacOSX::TryVideoMode(), RageDisplay_D3D::TryVideoMode(), ScreenOptions::TweenCursor(), FontManager::UnloadFont(), RageTextureManager::UnloadTexture(), GameSoundManager::Update(), FileTransfer::Update(), BPMDisplay::Update(), ScreenSetTime::Update(), ScreenPackages::Update(), InputList::Update(), Player::Update(), Screen::Update(), ScreenGameplay::Update(), SMOProtocol::Update(), Actor::Update(), OptionRow::UpdateEnabledDisabled(), Player::UpdateHoldNotes(), BGAnimationLayer::UpdateInternal(), RageLog::UpdateMappedLog(), InputHandler_DInput::UpdatePolled(), ScreenStatsOverlay::UpdateSkips(), SongPosition::UpdateSongPosition(), MusicWheel::UpdateSwitch(), WheelBase::UpdateSwitch(), ScreenSyncOverlay::UpdateText(), ScreenTestSound::UpdateText(), RollingNumbers::UpdateText(), ScreenNetSelectBase::UpdateUsers(), URLEncode(), RageLog::UserLog(), SongUtil::ValidateCurrentEditStepsDescription(), SongUtil::ValidateCurrentSongPreview(), SongUtil::ValidateCurrentStepsChartName(), SongUtil::ValidateCurrentStepsCredit(), SongUtil::ValidateCurrentStepsMusic(), Version(), RageSemaphore::Wait(), WARNING_COMMAND_NAME(), WcharDisplayText(), wo_ssprintf(), RageWorkerThread::WorkerMain(), NotesWriterDWI::Write(), NotesWriterSSC::Write(), NotesWriterETT::Write(), TimingTagWriter::Write(), RageFileObj::Write(), write_lua_table_to_file(), write_lua_value_to_file(), write_tag(), WriteDWINotesField(), WriteDWINotesTag(), WriteGlobalTags(), RageFileObjDeflate::WriteInternal(), WriteLogHeader(), RageSurfaceUtils::Zoom(), RageFileObjDeflate::~RageFileObjDeflate(), RageFileObjDirect::~RageFileObjDirect(), and RageFileObjInflate::~RageFileObjInflate().
StringToFloat() [1/2]
float StringToFloat (const RString & sString)
Referenced by ScreenTextEntry::FloatValidate(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), NoteSkinManager::GetMetricF(), XNodeStringValue::GetValue(), HHMMSSToSeconds(), BMSChart::Load(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromKSFFile(), Chart::LoadFromNode(), HighScoreImpl::LoadFromNode(), SMALoader::LoadFromSimfile(), LoadGlobalData(), SSCLoader::LoadNoteDataFromSimfile(), SSC::msdsplit(), HighScoreImpl::OffsetsToVector(), SMLoader::ParseBPMs(), ParseBrokenDWITimestamp(), SMLoader::ParseStops(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessBPMs(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SSCLoader::ProcessLabels(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SSCLoader::ProcessWarps(), BMSChartReader::ReadHeaders(), BMSChartReader::ReadNoteData(), SMLoader::RowToBeat(), SetDisplayBPM(), SetFirstSecond(), SetLastSecond(), SetLastSecondHint(), SetMusicLength(), SetOffset(), SetStepsDisplayBPM(), SetStepsOffset(), SetStepsVersion(), SetupExtensions(), SetVersion(), SMSetDisplayBPM(), and SMSetOffset().
StringToFloat() [2/2]
bool StringToFloat (const RString & sString, float & fOut)
StringToInt()
int StringToInt (const RString & sString)
Have a standard way of converting Strings to integers.
Parameters
sString the string to convert.
Returns
the integer we are after.
Referenced by GameState::ApplyCmdline(), bmsCommandTree::doStatement(), PlayerOptions::FromOneModString(), RadarValues::FromString(), StringConversion::FromString< bool >(), RageTexture::GetFrameDimensionsFromFileName(), NoteSkinManager::GetMetricB(), NoteSkinManager::GetMetricI(), GetResolutionFromFileName(), XNodeStringValue::GetValue(), HHMMSSToSeconds(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), actor_template_t::load_frames_from_file(), Font::LoadFontPageSettings(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromDWITokens(), LoadFromKSFFile(), BGAnimationLayer::LoadFromNode(), ScoresForChart::LoadFromNode(), HighScoreImpl::LoadFromNode(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), OptionRowHandlerList::LoadInternal(), DWILoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), Profile::MakeUniqueFileNameNoExtension(), HighScoreImpl::NoteRowsToVector(), FileTransfer::ParseHTTPAddress(), ScreenPackages::ParseHTTPAddress(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessCombos(), SMALoader::ProcessMultipliers(), SMLoader::ProcessSpeeds(), ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), BMSChartReader::ReadHeaders(), ScreenGameplay::SaveReplay(), SetHasBanner(), SetHasMusic(), SetMeter(), SetRadarValues(), SetSelectable(), SMSetSelectable(), and SongCacheIndex::SongFromStatement().
StripCrnl()
void StripCrnl (RString & s)
Referenced by GetFileContents(), BMSChart::Load(), LoadFromKSFFile(), LyricsLoader::LoadFromLRCFile(), and LoadGlobalData().
StripCvsAndSvn()
void StripCvsAndSvn (vector< RString > & vs)
References CVSOrSVN(), and RemoveIf().
StripMacResourceForks()
void StripMacResourceForks (vector< RString > & vs)
References MacResourceFork(), and RemoveIf().
Referenced by ScreenOptionsExportPackageSubPage::BeginScreen(), CharacterManager::CharacterManager(), SongManager::DifferentialReloadDir(), NoteSkinManager::GetAllNoteSkinNamesForGame(), AnnouncerManager::GetAnnouncerNames(), RageFileManager::GetDirListing(), ThemeManager::GetThemeNames(), SongManager::LoadStepManiaSongDir(), NoteSkinManager::RefreshNoteSkinData(), and ThemeManager::RunLuaScripts().
Trim()
void Trim (RString & sStr, const char * s)
Referenced by FixupPath(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), NetworkSyncManager::GetCurrentSMBuild(), Command::GetName(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), SMALoader::ProcessSpeeds(), IniFile::ReadFile(), SMLoader::RowToBeat(), SetChartName(), SetCredit(), SetDescription(), SongCacheIndex::SongFromStatement(), Song::TidyUpData(), BackgroundImpl::Layer::UpdateCurBGChange(), and RageLog::~RageLog().
TrimLeft()
void TrimLeft (RString & sStr, const char * s)
Referenced by GetETTNoteData(), GetSSCNoteData(), Font::LoadFontPageSettings(), LoadFromKSFFile(), LoadGlobalData(), and SongManager::UpdatePreferredSort().
TrimRight()
void TrimRight (RString & sStr, const char * s)
Referenced by GetInfoLog(), JoinLineList(), SSCLoader::ProcessLabels(), and SongManager::UpdatePreferredSort().
UnicodeUpperLower()
void UnicodeUpperLower (wchar_t * , size_t , const unsigned char *)
URLEncode() [1/2]
RString URLEncode (const RString & sStr)
References ssprintf().
Referenced by ScreenPackages::EnterURL(), and FileTransfer::StartTransfer().
URLEncode() [2/2]
int URLEncode (SArg(1))
utf8_get_char()
wchar_t utf8_get_char (const RString & s)
References INVALID_CHAR, and utf8_to_wchar_ec().
utf8_get_char_len()
int utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
Referenced by Font::LoadFontPageSettings(), ColorBitmapText::ResetText(), ColorBitmapText::SetText(), Rage::utf8_to_wchar(), utf8_to_wchar(), Rage::utf8_to_wchar_ec(), and utf8_to_wchar_ec().
utf8_is_valid()
bool utf8_is_valid (const RString & s)
References picosha2::detail::ch(), and utf8_to_wchar_ec().
utf8_remove_bom()
void utf8_remove_bom (RString & sLine)
utf8_sanitize()
void utf8_sanitize (RString & s)
References picosha2::detail::ch(), INVALID_CHAR, utf8_to_wchar_ec(), and wchar_to_utf8().
utf8_to_wchar()
bool utf8_to_wchar (const char * s, size_t iLength, unsigned & start, wchar_t & ch)
Decode a code point and place within the output variable.
This variant only does enough error checking to prevent crashing.
Returns
true if a valid encoded string was found.
References L, Rage::utf8_get_char_len(), and utf8_get_char_len().
Referenced by RStringToWstring(), and unicode_do_casing().
utf8_to_wchar_ec()
bool utf8_to_wchar_ec (const RString & s, unsigned & start, wchar_t & ch)
References is_utf8_continuation_byte(), and utf8_get_char_len().
Referenced by utf8_get_char(), utf8_is_valid(), and utf8_sanitize().
vssprintf()
RString vssprintf (const char * szFormat, va_list argList)
References FMT_BLOCK_SIZE.
Referenced by averr_ssprintf(), Alsa9Buf::ErrorHandler(), RageLog::Info(), RageLog::MapLog(), ov_ssprintf(), ssprintf(), RageException::Throw(), RageLog::Time(), RageLog::Trace(), RageLog::UserLog(), RageLog::Warn(), and wo_ssprintf().
wchar_to_utf8()
void wchar_to_utf8 (wchar_t ch, RString & out)
Referenced by utf8_sanitize(), WcharToUTF8(), and WStringToRString().
WcharDisplayText()
RString WcharDisplayText (wchar_t c)
References ssprintf().
Referenced by Font::Load().
WcharToUTF8()
RString WcharToUTF8 (wchar_t c)
References wchar_to_utf8().
Referenced by InitCharAliases(), and Replace_Unicode_Markers().
WStringToRString()
RString WStringToRString (const wstring & sStr)
References wchar_to_utf8().
Referenced by ScreenTextEntry::End(), MovieTexture_DShow::GetActiveFilterList(), ArchHooks_Win32::GetClipboard(), InputHandler::GetDeviceSpecificInputString(), InputHandler::GetLocalizedInputString(), GetVideoCodecDebugInfo(), ScreenNetSelectBase::Input(), ScreenTextEntry::Input(), Profile::LoadEditableDataFromDir(), MakeValidFilename(), ScreenTextEntry::TryAppendToAnswer(), and ScreenTextEntry::UpdateAnswerText().
Variable Documentation
g_argc
int g_argc = 0
Referenced by ArchHooks_Win32::ArchHooks_Win32(), GetCommandlineArgument(), GetCommandLineArguments(), CommandLineActions::Handle(), ArchHooks_Unix::Init(), ArchHooks_MacOSX::Init(), LoadingWindow_Gtk::Init(), and WriteLogHeader().
g_argv
char** g_argv = NULL
Referenced by ArchHooks_Win32::ArchHooks_Win32(), GetCommandLineArguments(), CommandLineActions::Handle(), ArchHooks_Unix::Init(), ArchHooks_MacOSX::Init(), LoadingWindow_Gtk::Init(), and WriteLogHeader().
g_langs
const LanguageInfo g_langs[] static
g_LowerCase
unsigned char g_LowerCase[256]
Initial value:
= {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x6B,
    0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B,
    0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3,
    0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB,
    0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7,
    0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xC0, 0xC1, 0xC2, 0xC3,
    0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
    0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xF7, 0xD8, 0xD9, 0xDA, 0xDB,
    0xDC, 0xDD, 0xDE, 0xFF,
}
g_RandomNumberGenerator
RandomGen g_RandomNumberGenerator
Referenced by bmsCommandTree::doStatement(), RandomSample::LoadSoundDir(), random_up_to(), RandomFloat(), RandomInt(), GameState::Reset(), GameState::ResetStageStatistics(), GameState::SetNewStageSeed(), sm_main(), and SongManager::UpdateShuffled().
g_UpperCase
unsigned char g_UpperCase[256]
Initial value:
= {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47,
    0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F, 0x50, 0x51, 0x52, 0x53,
    0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
    0x60, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B,
    0x4C, 0x4D, 0x4E, 0x4F, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
    0x58, 0x59, 0x5A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B,
    0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3,
    0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB,
    0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7,
    0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xC0, 0xC1, 0xC2, 0xC3,
    0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
    0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xF7, 0xD8, 0xD9, 0xDA, 0xDB,
    0xDC, 0xDD, 0xDE, 0xFF,
}
Referenced by char_traits_char_nocase::eq(), char_traits_char_nocase::fasttoupper(), char_traits_char_nocase::lt(), and char_traits_char_nocase::ne().
INVALID_CHAR
const wchar_t INVALID_CHAR = 0xFFFD
Referenced by InitCharAliases(), Replace_Unicode_Markers(), RStringToWstring(), utf8_get_char(), and utf8_sanitize().
NUM_ND
LocalizedString NUM_ND("RageUtil", "NumNd") static
Referenced by FormatNumberAndSuffix().
NUM_PREFIX
LocalizedString NUM_PREFIX("RageUtil", "NumPrefix") static
Referenced by FormatNumberAndSuffix().
NUM_RD
LocalizedString NUM_RD("RageUtil", "NumRd") static
Referenced by FormatNumberAndSuffix().
NUM_ST
LocalizedString NUM_ST("RageUtil", "NumSt") static
Referenced by FormatNumberAndSuffix().
NUM_TH
LocalizedString NUM_TH("RageUtil", "NumTh") static
Referenced by FormatNumberAndSuffix().