Etterna: RageSoundDriver_DSound_Software Class Reference
RageSoundDriver_DSound_Software Class Reference
#include <RageSoundDriver_DSound_Software.h>
Public Member Functions
RageSoundDriver_DSound_Software ()
virtual ~RageSoundDriver_DSound_Software ()
RString Init ()
int64_t GetPosition () const
float GetPlayLatency () const
int GetSampleRate () const
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Protected Member Functions
void SetupDecodingThread ()
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Private Member Functions
void MixerThread ()
Static Private Member Functions
static int MixerThread_start (void *p)
Private Attributes
DSound ds
DSoundBuf * m_pPCM
int m_iSampleRate
bool m_bShutdownMixerThread
RageThread m_MixingThread
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Constructor & Destructor Documentation
RageSoundDriver_DSound_Software()
RageSoundDriver_DSound_Software::RageSoundDriver_DSound_Software ()
References m_bShutdownMixerThread, and m_pPCM.
~RageSoundDriver_DSound_Software()
RageSoundDriver_DSound_Software::~RageSoundDriver_DSound_Software () virtual
References RageLog::Flush(), RageThread::IsCreated(), LOG, m_bShutdownMixerThread, m_MixingThread, m_pPCM, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
GetPlayLatency()
float RageSoundDriver_DSound_Software::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
References f, g_iMaxWriteahead, and m_iSampleRate.
GetPosition()
int64_t RageSoundDriver_DSound_Software::GetPosition () const virtual
Implements RageSoundDriver.
References DSoundBuf::GetPosition(), and m_pPCM.
GetSampleRate()
int RageSoundDriver_DSound_Software::GetSampleRate () const virtual
Reimplemented from RageSoundDriver.
References m_iSampleRate.
Init()
RString RageSoundDriver_DSound_Software::Init () virtual
Reimplemented from RageSoundDriver.
References channels, RageThread::Create(), ds, g_iMaxWriteahead, DSoundBuf::HW_DONT_CARE, RageLog::Info(), DSound::Init(), DSoundBuf::Init(), DSound::IsEmulated(), LOG, m_iSampleRate, PrefsManager::m_iSoundPreferredSampleRate, PrefsManager::m_iSoundWriteAhead, m_MixingThread, m_pPCM, MixerThread_start(), PREFSMAN, safe_writeahead, RageThread::SetName(), and RageSoundDriver::StartDecodeThread().
MixerThread()
void RageSoundDriver_DSound_Software::MixerThread () private
References bytes_per_frame, chunksize(), DSoundBuf::get_output_buf(), DSoundBuf::GetOutputPosition(), DSoundBuf::GetPosition(), LOG, m_bShutdownMixerThread, m_iSampleRate, m_pPCM, RageSoundDriver::Mix(), DSoundBuf::Play(), DSoundBuf::release_output_buf(), DSoundBuf::Stop(), and RageLog::Warn().
MixerThread_start()
int RageSoundDriver_DSound_Software::MixerThread_start (void * p) static private
Referenced by Init().
SetupDecodingThread()
void RageSoundDriver_DSound_Software::SetupDecodingThread () protected virtual
Reimplemented from RageSoundDriver.
References LOG, and RageLog::Warn().
Member Data Documentation
ds
DSound RageSoundDriver_DSound_Software::ds private
Referenced by Init().
m_bShutdownMixerThread
bool RageSoundDriver_DSound_Software::m_bShutdownMixerThread private
Referenced by MixerThread(), RageSoundDriver_DSound_Software(), and ~RageSoundDriver_DSound_Software().
m_iSampleRate
int RageSoundDriver_DSound_Software::m_iSampleRate private
Referenced by GetPlayLatency(), GetSampleRate(), Init(), and MixerThread().
m_MixingThread
RageThread RageSoundDriver_DSound_Software::m_MixingThread private
Referenced by Init(), and ~RageSoundDriver_DSound_Software().
m_pPCM
DSoundBuf* RageSoundDriver_DSound_Software::m_pPCM private
Referenced by GetPosition(), Init(), MixerThread(), RageSoundDriver_DSound_Software(), and ~RageSoundDriver_DSound_Software().
The documentation for this class was generated from the following files:
RageSoundDriver_DSound_Software.h
RageSoundDriver_DSound_Software.cpp