Etterna: GoalsForChart Struct Reference
GoalsForChart Struct Reference
#include <Profile.h>
Public Member Functions
void Add (ScoreGoal &sg)
vector< ScoreGoal > & Get ()
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
Public Attributes
vector< ScoreGoal > goals
Member Function Documentation
Add()
void GoalsForChart::Add (ScoreGoal & sg) inline
References goals.
Referenced by LoadFromNode().
CreateNode()
XNode * GoalsForChart::CreateNode () const
References XNode::AppendAttr(), XNode::AppendChild(), FOREACH_CONST, and goals.
Referenced by XMLProfile::SaveScoreGoalsCreateNode().
Get()
vector<ScoreGoal>& GoalsForChart::Get () inline
References goals.
LoadFromNode()
void GoalsForChart::LoadFromNode (const XNode * pNode)
References Add(), FOREACH_CONST_Child, XNode::GetAttrValue(), goals, and ScoreGoal::LoadFromNode().
Member Data Documentation
goals
vector<ScoreGoal> GoalsForChart::goals
Referenced by Add(), CreateNode(), Get(), LoadFromNode(), and DBProfile::SaveScoreGoals().
The documentation for this struct was generated from the following files:
Profile.h
XMLProfile.cpp