Etterna: LunaScreenNetSelectBase Class Reference
LunaScreenNetSelectBase Class Reference
Allow Lua to have access to the PlayerState.
Public Member Functions
LunaScreenNetSelectBase ()
Public Member Functions inherited from Luna< ScreenNetSelectBase >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Private Member Functions
static int ChatboxInput (T *p, lua_State *L)
static int UsersVisible (T *p, lua_State *L)
static int ChatboxVisible (T *p, lua_State *L)
static int GetUserQty (T *p, lua_State *L)
static int GetUser (T *p, lua_State *L)
static int GetUserState (T *p, lua_State *L)
static int GetFriendQty (T *p, lua_State *L)
static int GetFriendName (T *p, lua_State *L)
static int GetFriendState (T *p, lua_State *L)
static int ScrollChatUp (T *p, lua_State *L)
static int ScrollChatDown (T *p, lua_State *L)
static int ShowNextMsg (T *p, lua_State *L)
static int ShowPreviousMsg (T *p, lua_State *L)
static int GetChatScroll (T *p, lua_State *L)
static int GetChatLines (T *p, lua_State *L)
static int PasteClipboard (T *p, lua_State *L)
Additional Inherited Members
Static Public Member Functions inherited from Luna< ScreenNetSelectBase >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Static Public Attributes inherited from Luna< ScreenNetSelectBase >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenNetSelectBase >
using T = ScreenNetSelectBase
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenNetSelectBase >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the PlayerState.
Constructor & Destructor Documentation
LunaScreenNetSelectBase()
LunaScreenNetSelectBase::LunaScreenNetSelectBase () inline
References ADD_METHOD, ChatboxInput(), ChatboxVisible(), GetChatLines(), GetChatScroll(), GetFriendName(), GetFriendQty(), GetFriendState(), GetUser(), GetUserQty(), GetUserState(), PasteClipboard(), ScrollChatDown(), ScrollChatUp(), ShowNextMsg(), ShowPreviousMsg(), and UsersVisible().
Member Function Documentation
ChatboxInput()
static int LunaScreenNetSelectBase::ChatboxInput (T * p, lua_State * L) inline static private
References BArg, and ScreenNetSelectBase::enableChatboxInput.
Referenced by LunaScreenNetSelectBase().
ChatboxVisible()
static int LunaScreenNetSelectBase::ChatboxVisible (T * p, lua_State * L) inline static private
References BArg, and ScreenNetSelectBase::SetChatboxVisible().
Referenced by LunaScreenNetSelectBase().
GetChatLines()
static int LunaScreenNetSelectBase::GetChatLines (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::GetLines().
Referenced by LunaScreenNetSelectBase().
GetChatScroll()
static int LunaScreenNetSelectBase::GetChatScroll (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::GetScroll().
Referenced by LunaScreenNetSelectBase().
GetFriendName()
static int LunaScreenNetSelectBase::GetFriendName (T * p, lua_State * L) inline static private
References NetworkSyncManager::fl_PlayerNames, IArg, and NSMAN.
Referenced by LunaScreenNetSelectBase().
GetFriendQty()
static int LunaScreenNetSelectBase::GetFriendQty (T * p, lua_State * L) inline static private
References NetworkSyncManager::fl_PlayerNames, and NSMAN.
Referenced by LunaScreenNetSelectBase().
GetFriendState()
static int LunaScreenNetSelectBase::GetFriendState (T * p, lua_State * L) inline static private
References NetworkSyncManager::fl_PlayerStates, IArg, and NSMAN.
Referenced by LunaScreenNetSelectBase().
GetUser()
static int LunaScreenNetSelectBase::GetUser (T * p, lua_State * L) inline static private
References IArg, and ScreenNetSelectBase::ToUsers().
Referenced by LunaScreenNetSelectBase().
GetUserQty()
static int LunaScreenNetSelectBase::GetUserQty (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::ToUsers().
Referenced by LunaScreenNetSelectBase().
GetUserState()
static int LunaScreenNetSelectBase::GetUserState (T * p, lua_State * L) inline static private
References IArg, NetworkSyncManager::m_ActivePlayer, NetworkSyncManager::m_PlayerStatus, NSMAN, and ScreenNetSelectBase::ToUsers().
Referenced by LunaScreenNetSelectBase().
PasteClipboard()
static int LunaScreenNetSelectBase::PasteClipboard (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::PasteClipboard().
Referenced by LunaScreenNetSelectBase().
ScrollChatDown()
static int LunaScreenNetSelectBase::ScrollChatDown (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::Scroll().
Referenced by LunaScreenNetSelectBase().
ScrollChatUp()
static int LunaScreenNetSelectBase::ScrollChatUp (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::Scroll().
Referenced by LunaScreenNetSelectBase().
ShowNextMsg()
static int LunaScreenNetSelectBase::ShowNextMsg (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::ShowNextMsg().
Referenced by LunaScreenNetSelectBase().
ShowPreviousMsg()
static int LunaScreenNetSelectBase::ShowPreviousMsg (T * p, lua_State * L) inline static private
References ScreenNetSelectBase::ShowPreviousMsg().
Referenced by LunaScreenNetSelectBase().
UsersVisible()
static int LunaScreenNetSelectBase::UsersVisible (T * p, lua_State * L) inline static private
References BArg, and ScreenNetSelectBase::SetUsersVisible().
Referenced by LunaScreenNetSelectBase().
The documentation for this class was generated from the following file:
ScreenNetSelectBase.cpp