Etterna: GameLoop Namespace Reference
GameLoop Namespace Reference
Main rendering and update loop.
Functions
void RunGameLoop ()
void SetUpdateRate (float fUpdateRate)
void ChangeTheme (const RString &sNewTheme)
void ChangeGame (const RString &new_game, const RString &new_theme="")
void StartConcurrentRendering ()
void FinishConcurrentRendering ()
Detailed Description
Main rendering and update loop.
Function Documentation
ChangeGame()
void GameLoop::ChangeGame (const RString & new_game, const RString & new_theme = "")
Referenced by ScreenOptionsMaster::HandleScreenMessage(), and LunaGameManager::SetGame().
ChangeTheme()
void GameLoop::ChangeTheme (const RString & sNewTheme)
Referenced by ScreenOptionsMaster::HandleScreenMessage(), ScreenTitleMenu::Input(), and LunaThemeManager::SetTheme().
FinishConcurrentRendering()
void GameLoop::FinishConcurrentRendering ()
References ConcurrentRenderer::Stop().
RunGameLoop()
void GameLoop::RunGameLoop ()
References ArchHooks::BoostPriority(), ChangeAppPri(), CheckFocus(), InputMapper::CheckForChangedInputDevicesAndRemap(), CheckGameLoopTimerSkips(), RageInput::DevicesChanged(), DLMAN, ScreenManager::Draw(), f, g_AccurateGameplayTimer, g_fConstantUpdateDeltaSeconds, g_fUpdateRate, GAMESTATE, HandleInputEvents(), HOOKS, INPUTFILTER, INPUTMAN, INPUTMAPPER, RageInput::LoadDrivers(), NSMAN, InputFilter::Reset(), SCREENMAN, SOUND, SOUNDMAN, ScreenManager::SystemMessage(), TEXTUREMAN, ArchHooks::UnBoostPriority(), GameSoundManager::Update(), ScreenManager::Update(), RageSoundManager::Update(), RageTextureManager::Update(), GameState::Update(), NetworkSyncManager::Update(), and ArchHooks::UserQuit().
Referenced by sm_main().
SetUpdateRate()
void GameLoop::SetUpdateRate (float fUpdateRate)
References g_fUpdateRate.
Referenced by ScreenDebugOverlay::Update().
StartConcurrentRendering()
void GameLoop::StartConcurrentRendering ()
References ConcurrentRenderer::Start().