Etterna: BMSSong Class Reference
BMSSong Class Reference
Public Member Functions
BMSSong (Song *song)
int AllocateKeysound (RString filename, RString path)
bool GetBackground (RString filename, RString path, RString &bgfile)
Song * GetSong ()
Private Member Functions
void PrecacheBackgrounds (const RString &dir)
Private Attributes
map< RString, int > mapKeysoundToIndex
Song * out
bool backgroundsPrecached
map< RString, RString > mapBackground
Constructor & Destructor Documentation
BMSSong()
BMSSong::BMSSong (Song * song) explicit
References backgroundsPrecached, Song::m_vsKeysoundFile, mapKeysoundToIndex, and out.
Member Function Documentation
AllocateKeysound()
int BMSSong::AllocateKeysound (RString filename, RString path)
References Dirname(), FT_Sound, Song::GetSongDir(), ActorUtil::GetTypeExtensionList(), IsAFile(), LOG, Song::m_vsKeysoundFile, mapKeysoundToIndex, out, SetExtension(), RageLog::UserLog(), and Rage::utf8_is_valid().
Referenced by BMSChartReader::GetKeysound().
GetBackground()
bool BMSSong::GetBackground (RString filename, RString path, RString & bgfile)
References ActorUtil::AddTypeExtensionsToList(), backgroundsPrecached, Dirname(), FT_Bitmap, FT_Movie, Song::GetSongDir(), IsAFile(), LOG, mapBackground, out, PrecacheBackgrounds(), SetExtension(), RageLog::UserLog(), and Rage::utf8_is_valid().
Referenced by BMSChartReader::ReadNoteData().
GetSong()
Song * BMSSong::GetSong ()
References out.
Referenced by BMSSongLoader::AddToSong(), and BMSSongLoader::Load().
PrecacheBackgrounds()
void BMSSong::PrecacheBackgrounds (const RString & dir) private
References ActorUtil::AddTypeExtensionsToList(), backgroundsPrecached, FILEMAN, FT_Bitmap, FT_Movie, RageFileManager::GetDirListingWithMultipleExtensions(), mapBackground, and SetExtension().
Referenced by GetBackground().
Member Data Documentation
backgroundsPrecached
bool BMSSong::backgroundsPrecached private
Referenced by BMSSong(), GetBackground(), and PrecacheBackgrounds().
mapBackground
map<RString, RString> BMSSong::mapBackground private
Referenced by GetBackground(), and PrecacheBackgrounds().
mapKeysoundToIndex
map<RString, int> BMSSong::mapKeysoundToIndex private
Referenced by AllocateKeysound(), and BMSSong().
out
Song* BMSSong::out private
Referenced by AllocateKeysound(), BMSSong(), GetBackground(), and GetSong().
The documentation for this class was generated from the following file:
NotesLoaderBMS.cpp