Etterna: InputQueueCode Struct Reference
InputQueueCode Struct Reference
#include <InputQueue.h>
Classes
struct ButtonPress
Public Member Functions
bool Load (RString sButtonsNames)
bool EnteredCode (GameController controller) const
InputQueueCode ()
Private Attributes
vector< ButtonPress > m_aPresses
float m_fMaxSecondsBack
Constructor & Destructor Documentation
InputQueueCode()
InputQueueCode::InputQueueCode () inline
Member Function Documentation
EnteredCode()
bool InputQueueCode::EnteredCode (GameController controller) const
References GameInput::button, InputQueue::ClearQueue(), InputEventPlus::DeviceI, g_fSimultaneousThreshold, GameController_Invalid, InputEventPlus::GameI, InputQueue::GetQueue(), InputEventPlus::InputList, INPUTMAPPER, InputMapper::IsBeingPressed(), InputQueueCode::ButtonPress::m_aButtonsToHold, InputQueueCode::ButtonPress::m_aButtonsToNotHold, InputQueueCode::ButtonPress::m_aButtonsToPress, m_aPresses, InputQueueCode::ButtonPress::m_bAllowIntermediatePresses, m_fMaxSecondsBack, InputQueueCode::ButtonPress::m_InputTypes, min(), MultiPlayer_Invalid, DeviceInput::ts, and InputEventPlus::type.
Referenced by CodeDetector::EnteredCode().
Load()
bool InputQueueCode::Load (RString sButtonsNames)
References InputScheme::ButtonNameToIndex(), f, FOREACH, GameButton_Invalid, InputMapper::GetInputScheme(), IET_FIRST_PRESS, IET_RELEASE, IET_REPEAT, INPUTMAPPER, StdString::CStdStr< CT >::Left(), LOG, m_aPresses, m_fMaxSecondsBack, split(), and RageLog::Trace().
Referenced by InputQueueCodeSet::Load(), and CodeDetector::RefreshCacheItems().
Member Data Documentation
m_aPresses
vector<ButtonPress> InputQueueCode::m_aPresses private
Referenced by EnteredCode(), and Load().
m_fMaxSecondsBack
float InputQueueCode::m_fMaxSecondsBack private
Referenced by EnteredCode(), and Load().
The documentation for this struct was generated from the following files:
InputQueue.h
InputQueue.cpp