Etterna: ModsGroup< T > Class Template Reference
ModsGroup< T > Class Template Reference
#include <ModsGroup.h>
Public Member Functions
void Init ()
void Update (float fDelta)
template<typename U >
void Assign (ModsLevel level, U T::*member, const U &val)
template<typename U , int n>
void Assign_n (ModsLevel level, U(T::*member)[n], size_t index, const U &val)
void Assign (ModsLevel level, const T &val)
void Call (ModsLevel level, void(T::*fun)())
void FromString (ModsLevel level, const RString &str)
void SetCurrentToLevel (ModsLevel level)
const T & Get (ModsLevel l) const
const T & GetPreferred () const
const T & GetStage () const
const T & GetSong () const
const T & GetCurrent () const
T & Get (ModsLevel l)
T & GetPreferred ()
T & GetStage ()
T & GetSong ()
T & GetCurrent ()
Private Attributes
T m_ [NUM_ModsLevel]
RageTimer m_Timer
Member Function Documentation
Assign() [1/2]
template<class T> template<typename U > void ModsGroup< T >::Assign (ModsLevel level, U T::* member, const U & val) inline
Referenced by LunaPlayerState::ApplyPreferredOptionsToOtherLevels(), LunaGameState::ApplyPreferredSongOptionsToOtherLevels(), GameCommand::ApplySelf(), GameState::BeginStage(), CodeDetector::DetectAndAdjustMusicOptions(), GameState::ResetPlayerOptions(), PlayerState::ResetToDefaultPlayerOptions(), GameState::ResetToDefaultSongOptions(), LunaPlayerState::SetPlayerOptions(), LunaGameState::SetSongOptions(), GameState::UnjoinPlayer(), and ScreenPlayerOptions::UpdateDisqualified().
Assign() [2/2]
template<class T> void ModsGroup< T >::Assign (ModsLevel level, const T & val) inline
Assign_n()
template<class T> template<typename U , int n> void ModsGroup< T >::Assign_n (ModsLevel level, U(T::*) member[n], size_t index, const U & val) inline
Call()
template<class T> void ModsGroup< T >::Call (ModsLevel level, void(T::*)() fun) inline
Referenced by ModsGroup< SongOptions >::Init().
FromString()
template<class T> void ModsGroup< T >::FromString (ModsLevel level, const RString & str) inline
Referenced by GameState::ApplyPreferredModifiers(), GameState::ApplyStageModifiers(), and ModsGroup< SongOptions >::FromString().
Get() [1/2]
template<class T> const T& ModsGroup< T >::Get (ModsLevel l) const inline
Referenced by LunaPlayerState::ApplyPreferredOptionsToOtherLevels(), LunaGameState::ApplyPreferredSongOptionsToOtherLevels(), CompareSongPointersByMSD(), LunaPlayerState::GetPlayerOptions(), LunaPlayerState::GetPlayerOptionsArray(), LunaPlayerState::GetPlayerOptionsString(), LunaGameState::GetSongOptions(), LunaGameState::GetSongOptionsObject(), and PlayerState::SetPlayerNumber().
Get() [2/2]
template<class T> T& ModsGroup< T >::Get (ModsLevel l) inline
GetCurrent() [1/2]
template<class T> const T& ModsGroup< T >::GetCurrent () const inline
Referenced by Playlist::AddChart(), Profile::AddGoal(), AdjustSync::AutosyncOffset(), NoteField::CacheAllUsedNoteSkins(), NoteField::CalcPixelsBeforeAndAfterTargets(), PlayerStageStats::CalcSSR(), BackgroundImpl::Layer::CreateRandomBGA(), NoteField::DrawBeatBar(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldBody(), Player::DrawHoldJudgments(), NoteField::DrawPrimitives(), Player::DrawPrimitives(), Player::DrawTapJudgments(), NoteField::ensure_note_displays_have_skin(), FillInHighScore(), StageStats::FinalizeScores(), FindDisplayedBeats(), Player::FlashGhostRow(), TimingData::GetBeatAndBPSFromElapsedTime(), LunaPlayerState::GetCurrentPlayerOptions(), Song::GetDisplayBpms(), TimingData::GetElapsedTimeFromBeat(), Player::GetMaxStepDistanceSeconds(), GameState::GetPlayerFailType(), LunaScreenGameplay::GetTrueBPS(), ArrowEffects::GetYOffset(), AdjustSync::HandleAutosync(), ScreenEvaluation::HandleMenuStart(), ScreenGameplay::HandleScreenMessage(), AdjustSync::HandleSongEnd(), ScoreKeeperNormal::HandleTapRowScore(), ScreenGameplay::Input(), LifeMeterBar::IsFailing(), ReceptorArrow::Load(), Player::Load(), BackgroundImpl::LoadFromSong(), ScreenGameplay::LoadNextSong(), GameState::PlayerIsUsingModifier(), LunaScreenSelectMusic::PlayReplay(), GameplayAssist::PlayTicks(), ETTProtocol::ReportHighScore(), SMOProtocol::ReportPlayerOptions(), LunaDownloadManager::RequestChartLeaderBoard(), ETTProtocol::SelectUserSong(), BrightnessOverlay::SetActualBrightness(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), ScreenGameplay::SetupSong(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::StartPlayingSong(), SMOProtocol::StartRequest(), Player::Step(), ScreenGameplay::ToggleReplayPause(), LyricDisplay::Update(), ArrowEffects::Update(), ReceptorArrowRow::Update(), Foreground::Update(), ReceptorArrow::Update(), NoteField::Update(), DancingCharacters::Update(), Player::Update(), ScreenGameplay::Update(), BackgroundImpl::Layer::UpdateCurBGChange(), Player::UpdateHoldNotes(), ScreenSyncOverlay::UpdateText(), TimingData::WhereUAtBro(), and TimingData::WhereUAtBroNoOffset().
GetCurrent() [2/2]
template<class T> T& ModsGroup< T >::GetCurrent () inline
GetPreferred() [1/2]
template<class T> const T& ModsGroup< T >::GetPreferred () const inline
Referenced by GameState::BeginStage(), CodeDetector::ChangeScrollSpeed(), GameState::CurrentOptionsDisqualifyPlayer(), GameCommand::DescribesCurrentMode(), CodeDetector::DetectAndAdjustMusicOptions(), NoteField::ensure_note_displays_have_skin(), ScreenSongOptions::ExportOptions(), ScreenEvaluation::HandleMenuStart(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenEvaluation::Init(), ScreenGameplay::Input(), LunaScreenSelectMusic::PlayReplay(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), LunaScreenSelectMusic::ShowEvalScreenForScore(), LunaScreenSelectMusic::StartPlaylistAsCourse(), GameSoundManager::Update(), ScreenGameplay::Update(), and ScreenPlayerOptions::UpdateDisqualified().
GetPreferred() [2/2]
template<class T> T& ModsGroup< T >::GetPreferred () inline
GetSong() [1/2]
template<class T> const T& ModsGroup< T >::GetSong () const inline
Referenced by GameState::BeginStage(), LifeMeterBar::ChangeLife(), DebugLineAssist::DoAndLog(), DebugLineAutosync::DoAndLog(), DebugLineAssist::GetDisplayValue(), DebugLineAutosync::GetDisplayValue(), LifeMeterBattery::GetLife(), LifeMeterBattery::GetRemainingLives(), LifeMeterBattery::GetTotalLives(), ScreenEvaluation::HandleMenuStart(), ScreenGameplay::HandleScreenMessage(), ScreenGameplay::Input(), DebugLineAssist::IsEnabled(), DebugLineAutosync::IsEnabled(), LifeMeterBattery::IsHot(), LifeMeterBattery::OnSongEnded(), LunaScreenSelectMusic::PlayReplay(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::Update(), and GameState::UpdateSongPosition().
GetSong() [2/2]
template<class T> T& ModsGroup< T >::GetSong () inline
GetStage() [1/2]
template<class T> const T& ModsGroup< T >::GetStage () const inline
Referenced by NoteField::CacheAllUsedNoteSkins(), GameCommand::DescribesCurrentMode(), DetermineScoreEligibility(), FillInHighScore(), ScreenGameplay::HandleScreenMessage(), ScreenEvaluation::Init(), ScreenGameplay::Init(), Player::IsOniDead(), LifeMeterBar::Load(), LifeMeterBattery::Load(), ScoreKeeperNormal::Load(), Player::Load(), and ModIconRow::SetFromGameState().
GetStage() [2/2]
template<class T> T& ModsGroup< T >::GetStage () inline
Init()
template<class T> void ModsGroup< T >::Init () inline
Referenced by PlayerState::Reset(), and GameState::Reset().
SetCurrentToLevel()
template<class T> void ModsGroup< T >::SetCurrentToLevel (ModsLevel level) inline
Update()
template<class T> void ModsGroup< T >::Update (float fDelta) inline
Referenced by PlayerState::Update(), and GameState::Update().
Member Data Documentation
m_
template<class T> T ModsGroup< T >::m_[NUM_ModsLevel] private
m_Timer
template<class T> RageTimer ModsGroup< T >::m_Timer private
The documentation for this class was generated from the following file:
ModsGroup.h