Etterna: Actor.cpp File Reference
Actor.cpp File Reference
#include "global.h"
#include "Actor.h"
#include "ActorFrame.h"
#include "ActorUtil.h"
#include "GamePreferences.h"
#include "LuaBinding.h"
#include "LuaReference.h"
#include "MessageManager.h"
#include "Preference.h"
#include "RageDisplay.h"
#include "RageMath.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "ThemeManager.h"
#include "XmlFile.h"
#include <typeinfo>
Classes
class HiddenActor
Set up a hidden Actor that won't be drawn.
class LunaActor
Allow Lua to have access to the Actor.
Macros
#define CPY(x) x = cpy.x
#define COMPARE(x)
Functions
REGISTER_ACTOR_CLASS_WITH_NAME (HiddenActor, Actor)
XToString (HorizAlign)
LuaXType (HorizAlign)
XToString (VertAlign)
LuaXType (VertAlign)
static bool GetMessageNameFromCommandName (const RString &sCommandName, RString &sMessageNameOut)
static void generic_global_timer_update (float new_time, float &effect_delta_time, float &time_into_effect)
Variables
static Preference< bool > g_bShowMasks ("ShowMasks", false)
static const float default_effect_period = 1.0f
static const char * HorizAlignNames [] = { "Left", "Center", "Right" }
static const char * VertAlignNames [] = { "Top", "Middle", "Bottom" }
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if ((x) != other.x)                                                        \
        return false;
Referenced by Actor::TweenState::operator==().
CPY
#define CPY (x) x = cpy.x
Referenced by Actor::Actor().
Function Documentation
generic_global_timer_update()
static void generic_global_timer_update (float new_time, float & effect_delta_time, float & time_into_effect) static
Referenced by Actor::UpdateInternal().
GetMessageNameFromCommandName()
static bool GetMessageNameFromCommandName (const RString & sCommandName, RString & sMessageNameOut) static
References StdString::CStdStr< CT >::Left(), and StdString::CStdStr< CT >::Right().
Referenced by Actor::AddCommand().
LuaXType() [1/2]
LuaXType (HorizAlign)
LuaXType() [2/2]
LuaXType (VertAlign)
REGISTER_ACTOR_CLASS_WITH_NAME()
REGISTER_ACTOR_CLASS_WITH_NAME (HiddenActor , Actor)
XToString() [1/2]
XToString (HorizAlign)
XToString() [2/2]
XToString (VertAlign)
Variable Documentation
default_effect_period
const float default_effect_period = 1.0f static
Referenced by Actor::InitState().
g_bShowMasks
Preference<bool> g_bShowMasks("ShowMasks", false) static
Referenced by Actor::SetGlobalRenderStates().
HorizAlignNames
const char* HorizAlignNames[] = { "Left", "Center", "Right" } static
VertAlignNames
const char* VertAlignNames[] = { "Top", "Middle", "Bottom" } static