Etterna: LunaActorScroller Class Reference
LunaActorScroller Class Reference
Allow Lua to have access to the ActorScroller.
Public Member Functions
LunaActorScroller ()
Public Member Functions inherited from Luna< ActorScroller >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int PositionItems (T *p, lua_State *L)
static int SetTransformFromFunction (T *p, lua_State *L)
static int SetTransformFromHeight (T *p, lua_State *L)
static int SetTransformFromWidth (T *p, lua_State *L)
static int SetCurrentAndDestinationItem (T *p, lua_State *L)
static int SetDestinationItem (T *p, lua_State *L)
static int GetSecondsToDestination (T *p, lua_State *L)
static int SetSecondsPerItem (T *p, lua_State *L)
static int GetSecondsPauseBetweenItems (T *p, lua_State *L)
static int SetSecondsPauseBetweenItems (T *p, lua_State *L)
static int SetPauseCountdownSeconds (T *p, lua_State *L)
static int SetNumSubdivisions (T *p, lua_State *L)
static int ScrollThroughAllItems (T *p, lua_State *L)
static int ScrollWithPadding (T *p, lua_State *L)
static int SetFastCatchup (T *p, lua_State *L)
static int SetLoop (T *p, lua_State *L)
static int SetWrap (T *p, lua_State *L)
static int SetMask (T *p, lua_State *L)
static int SetNumItemsToDraw (T *p, lua_State *L)
static int GetFullScrollLengthSeconds (T *p, lua_State *L)
static int GetCurrentItem (T *p, lua_State *L)
static int GetDestinationItem (T *p, lua_State *L)
static int GetNumItems (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ActorScroller >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ActorScroller >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ActorScroller >
using T = ActorScroller
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ActorScroller >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ActorScroller.
Constructor & Destructor Documentation
LunaActorScroller()
LunaActorScroller::LunaActorScroller () inline
References ADD_METHOD, GetCurrentItem(), GetDestinationItem(), GetFullScrollLengthSeconds(), GetNumItems(), GetSecondsPauseBetweenItems(), GetSecondsToDestination(), PositionItems(), ScrollThroughAllItems(), ScrollWithPadding(), SetCurrentAndDestinationItem(), SetDestinationItem(), SetFastCatchup(), SetLoop(), SetMask(), SetNumItemsToDraw(), SetNumSubdivisions(), SetPauseCountdownSeconds(), SetSecondsPauseBetweenItems(), SetSecondsPerItem(), SetTransformFromFunction(), SetTransformFromHeight(), SetTransformFromWidth(), and SetWrap().
Member Function Documentation
GetCurrentItem()
static int LunaActorScroller::GetCurrentItem (T * p, lua_State * L) inline static
References ActorScroller::GetCurrentItem().
Referenced by LunaActorScroller().
GetDestinationItem()
static int LunaActorScroller::GetDestinationItem (T * p, lua_State * L) inline static
References ActorScroller::GetDestinationItem().
Referenced by LunaActorScroller().
GetFullScrollLengthSeconds()
static int LunaActorScroller::GetFullScrollLengthSeconds (T * p, lua_State * L) inline static
References ActorScroller::GetSecondsForCompleteScrollThrough().
Referenced by LunaActorScroller().
GetNumItems()
static int LunaActorScroller::GetNumItems (T * p, lua_State * L) inline static
References ActorScroller::GetNumItems().
Referenced by LunaActorScroller().
GetSecondsPauseBetweenItems()
static int LunaActorScroller::GetSecondsPauseBetweenItems (T * p, lua_State * L) inline static
References ActorScroller::GetSecondsPauseBetweenItems().
Referenced by LunaActorScroller().
GetSecondsToDestination()
static int LunaActorScroller::GetSecondsToDestination (T * p, lua_State * L) inline static
References ActorScroller::GetSecondsToDestination().
Referenced by LunaActorScroller().
PositionItems()
static int LunaActorScroller::PositionItems (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorScroller::PositionItems().
Referenced by LunaActorScroller().
ScrollThroughAllItems()
static int LunaActorScroller::ScrollThroughAllItems (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorScroller::ScrollThroughAllItems().
Referenced by LunaActorScroller().
ScrollWithPadding()
static int LunaActorScroller::ScrollWithPadding (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::ScrollWithPadding().
Referenced by LunaActorScroller().
SetCurrentAndDestinationItem()
static int LunaActorScroller::SetCurrentAndDestinationItem (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetCurrentAndDestinationItem().
Referenced by LunaActorScroller().
SetDestinationItem()
static int LunaActorScroller::SetDestinationItem (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetDestinationItem().
Referenced by LunaActorScroller().
SetFastCatchup()
static int LunaActorScroller::SetFastCatchup (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorScroller::SetFastCatchup().
Referenced by LunaActorScroller().
SetLoop()
static int LunaActorScroller::SetLoop (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorScroller::SetLoop().
Referenced by LunaActorScroller().
SetMask()
static int LunaActorScroller::SetMask (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorScroller::EnableMask(), and FArg.
Referenced by LunaActorScroller().
SetNumItemsToDraw()
static int LunaActorScroller::SetNumItemsToDraw (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetNumItemsToDraw().
Referenced by LunaActorScroller().
SetNumSubdivisions()
static int LunaActorScroller::SetNumSubdivisions (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and ActorScroller::SetNumSubdivisions().
Referenced by LunaActorScroller().
SetPauseCountdownSeconds()
static int LunaActorScroller::SetPauseCountdownSeconds (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetPauseCountdownSeconds().
Referenced by LunaActorScroller().
SetSecondsPauseBetweenItems()
static int LunaActorScroller::SetSecondsPauseBetweenItems (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetSecondsPauseBetweenItems().
Referenced by LunaActorScroller().
SetSecondsPerItem()
static int LunaActorScroller::SetSecondsPerItem (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetSecondsPerItem().
Referenced by LunaActorScroller().
SetTransformFromFunction()
static int LunaActorScroller::SetTransformFromFunction (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, LuaHelpers::FromStack(), and ActorScroller::SetTransformFromReference().
Referenced by LunaActorScroller().
SetTransformFromHeight()
static int LunaActorScroller::SetTransformFromHeight (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetTransformFromHeight().
Referenced by LunaActorScroller().
SetTransformFromWidth()
static int LunaActorScroller::SetTransformFromWidth (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorScroller::SetTransformFromWidth().
Referenced by LunaActorScroller().
SetWrap()
static int LunaActorScroller::SetWrap (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and ActorScroller::SetWrap().
Referenced by LunaActorScroller().
The documentation for this class was generated from the following file:
ActorScroller.cpp