Etterna: AdjustSync Class Reference
AdjustSync Class Reference
Allows for adjusting the sync of a song.
#include <AdjustSync.h>
Static Public Member Functions
static void ResetOriginalSyncData ()
static void ResetAutosync ()
static bool IsSyncDataChanged ()
static void SaveSyncChanges ()
static void RevertSyncChanges ()
static void HandleAutosync (float fNoteOffBySeconds, float fStepTime)
static void HandleSongEnd ()
static void AutosyncOffset ()
static void AutosyncTempo ()
static void GetSyncChangeTextGlobal (vector< RString > &vsAddTo)
static void GetSyncChangeTextSong (vector< RString > &vsAddTo)
Static Public Attributes
static vector< TimingData > s_vpTimingDataOriginal
The original TimingData before adjustments were made.
static float s_fGlobalOffsetSecondsOriginal = 0.0f
static const int OFFSET_SAMPLE_COUNT = 24
The minimum number of steps to hit for syncing purposes.
static float s_fAutosyncOffset [OFFSET_SAMPLE_COUNT]
static int s_iAutosyncOffsetSample = 0
static float s_fStandardDeviation = 0.0f
static const float ERROR_TOO_HIGH = 0.025f
static vector< pair< float, float > > s_vAutosyncTempoData
static float s_fAverageError = 0.0f
static int s_iStepsFiltered = 0
Detailed Description
Allows for adjusting the sync of a song.
This class defines two ways of adjusting the sync of a song. The first adjusts only the offset, "on the fly". It can adjust either the song itself or the machine. The other style adjusts both the BPM and the offset of the song, but it needs more data.
Member Function Documentation
AutosyncOffset()
void AdjustSync::AutosyncOffset () static
References AUTOSYNC_CORRECTION_APPLIED, AUTOSYNC_CORRECTION_NOT_APPLIED, AutosyncType_Machine, AutosyncType_Song, calc_mean(), calc_stddev(), f, FAIL_M, FOREACH, GAMESTATE, Song::GetAllSteps(), ModsGroup< T >::GetCurrent(), LocalizedString::GetValue(), SongOptions::m_AutosyncType, TimingData::m_fBeat0OffsetInSeconds, PrefsManager::m_fGlobalOffsetSeconds, GameState::m_pCurSong, GameState::m_SongOptions, Song::m_SongTiming, OFFSET_SAMPLE_COUNT, PREFSMAN, s_fAutosyncOffset, s_fStandardDeviation, s_iAutosyncOffsetSample, SCREENMAN, Preference< T >::Set(), ssprintf(), and ScreenManager::SystemMessage().
Referenced by HandleAutosync().
AutosyncTempo()
void AdjustSync::AutosyncTempo () static
References TimingData::AddSegment(), AUTOSYNC_CORRECTION_APPLIED, AUTOSYNC_CORRECTION_NOT_APPLIED, CalcLeastSquares(), ERROR_TOO_HIGH, FilterHighErrorPoints(), GAMESTATE, BPMSegment::GetBPM(), StopSegment::GetPause(), DelaySegment::GetPause(), TimingSegment::GetRow(), TimingData::GetTimingSegments(), LocalizedString::GetValue(), TimingData::m_fBeat0OffsetInSeconds, GameState::m_pCurSong, Song::m_SongTiming, s_fAverageError, s_iStepsFiltered, s_vAutosyncTempoData, SCREENMAN, SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, and ScreenManager::SystemMessage().
Referenced by HandleSongEnd().
GetSyncChangeTextGlobal()
void AdjustSync::GetSyncChangeTextGlobal (vector< RString > & vsAddTo) static
References EARLIER, f, LocalizedString::GetValue(), GLOBAL_OFFSET_FROM, LATER, PrefsManager::m_fGlobalOffsetSeconds, PREFSMAN, Quantize(), s_fGlobalOffsetSecondsOriginal, and ssprintf().
Referenced by GetPromptText(), IsSyncDataChanged(), and ScreenSyncOverlay::UpdateText().
GetSyncChangeTextSong()
void AdjustSync::GetSyncChangeTextSong (vector< RString > & vsAddTo) static
References CHANGED_STOP, EARLIER, ERROR, ETC, f, FormatNumberAndSuffix(), GAMESTATE, BroadcastOnChangePtr< T >::Get(), TimingData::GetTimingSegments(), LocalizedString::GetValue(), GameState::isplaylistcourse, LATER, TimingData::m_fBeat0OffsetInSeconds, GameState::m_pCurSong, Song::m_SongTiming, Quantize(), s_fAverageError, s_iStepsFiltered, s_vpTimingDataOriginal, SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENTS_MISMATCH_MESSAGE, SONG_OFFSET_FROM, ssprintf(), TAPS_IGNORED, and TEMPO_SEGMENT_FROM.
Referenced by GetPromptText(), IsSyncDataChanged(), and ScreenSyncOverlay::UpdateText().
HandleAutosync()
void AdjustSync::HandleAutosync (float fNoteOffBySeconds, float fStepTime) static
References AutosyncOffset(), AutosyncType_Machine, AutosyncType_Off, AutosyncType_Song, AutosyncType_Tempo, FAIL_M, GAMESTATE, ModsGroup< T >::GetCurrent(), SongOptions::m_AutosyncType, GameState::m_SongOptions, OFFSET_SAMPLE_COUNT, s_fAutosyncOffset, s_iAutosyncOffsetSample, s_vAutosyncTempoData, and ssprintf().
Referenced by Player::Step().
HandleSongEnd()
void AdjustSync::HandleSongEnd () static
References AutosyncTempo(), AutosyncType_Tempo, GAMESTATE, ModsGroup< T >::GetCurrent(), GameState::IsPlaylistCourse(), SongOptions::m_AutosyncType, and GameState::m_SongOptions.
Referenced by ScreenGameplay::SongFinished().
IsSyncDataChanged()
bool AdjustSync::IsSyncDataChanged () static
References GAMESTATE, GetSyncChangeTextGlobal(), GetSyncChangeTextSong(), and GameState::IsPlaylistCourse().
Referenced by StageStats::FinalizeScores(), and ScreenGameplay::HandleScreenMessage().
ResetAutosync()
void AdjustSync::ResetAutosync () static
References s_iAutosyncOffsetSample, and s_vAutosyncTempoData.
Referenced by ScreenGameplaySyncMachine::ResetAndRestartCurrentSong(), and ResetOriginalSyncData().
ResetOriginalSyncData()
void AdjustSync::ResetOriginalSyncData () static
References FOREACH, GAMESTATE, Song::GetAllSteps(), PrefsManager::m_fGlobalOffsetSeconds, GameState::m_pCurSong, Song::m_SongTiming, PREFSMAN, ResetAutosync(), s_fGlobalOffsetSecondsOriginal, and s_vpTimingDataOriginal.
Referenced by GameState::BeginStage(), ScreenGameplaySyncMachine::Init(), GameState::Reset(), RevertSyncChanges(), and SaveSyncChanges().
RevertSyncChanges()
void AdjustSync::RevertSyncChanges () static
References FOREACH, GAMESTATE, Song::GetAllSteps(), PrefsManager::m_fGlobalOffsetSeconds, GameState::m_pCurSong, Song::m_SongTiming, PREFSMAN, ResetOriginalSyncData(), s_fAverageError, s_fGlobalOffsetSecondsOriginal, s_fStandardDeviation, s_vpTimingDataOriginal, and Preference< T >::Set().
Referenced by ScreenSyncOverlay::Input(), and RevertSyncChanges().
SaveSyncChanges()
void AdjustSync::SaveSyncChanges () static
References MessageManager::Broadcast(), GAMESTATE, GameState::IsEditing(), PrefsManager::m_fGlobalOffsetSeconds, GameState::m_pCurSong, Song::m_SongTiming, Message_SongModified, MESSAGEMAN, PREFSMAN, Song::ReloadFromSongDir(), ResetOriginalSyncData(), s_fAverageError, s_fGlobalOffsetSecondsOriginal, s_fStandardDeviation, s_vpTimingDataOriginal, Song::Save(), and PrefsManager::SavePrefsToDisk().
Referenced by SaveSyncChanges().
Member Data Documentation
ERROR_TOO_HIGH
const float AdjustSync::ERROR_TOO_HIGH = 0.025f static
Referenced by AutosyncTempo().
OFFSET_SAMPLE_COUNT
const int AdjustSync::OFFSET_SAMPLE_COUNT = 24 static
The minimum number of steps to hit for syncing purposes.
Referenced by AutosyncOffset(), HandleAutosync(), ScreenGameplaySyncMachine::RefreshText(), and ScreenSyncOverlay::UpdateText().
s_fAutosyncOffset
float AdjustSync::s_fAutosyncOffset static
Referenced by AutosyncOffset(), and HandleAutosync().
s_fAverageError
float AdjustSync::s_fAverageError = 0.0f static
Referenced by AutosyncTempo(), GetSyncChangeTextSong(), RevertSyncChanges(), and SaveSyncChanges().
s_fGlobalOffsetSecondsOriginal
float AdjustSync::s_fGlobalOffsetSecondsOriginal = 0.0f static
Referenced by GetSyncChangeTextGlobal(), ScreenGameplaySyncMachine::RefreshText(), ResetOriginalSyncData(), RevertSyncChanges(), SaveSyncChanges(), and ScreenSyncOverlay::UpdateText().
s_fStandardDeviation
float AdjustSync::s_fStandardDeviation = 0.0f static
Referenced by AutosyncOffset(), ScreenGameplaySyncMachine::RefreshText(), RevertSyncChanges(), SaveSyncChanges(), and ScreenSyncOverlay::UpdateText().
s_iAutosyncOffsetSample
int AdjustSync::s_iAutosyncOffsetSample = 0 static
Referenced by AutosyncOffset(), HandleAutosync(), ScreenGameplaySyncMachine::RefreshText(), ResetAutosync(), and ScreenSyncOverlay::UpdateText().
s_iStepsFiltered
int AdjustSync::s_iStepsFiltered = 0 static
Referenced by AutosyncTempo(), and GetSyncChangeTextSong().
s_vAutosyncTempoData
vector< pair< float, float > > AdjustSync::s_vAutosyncTempoData static
Referenced by AutosyncTempo(), HandleAutosync(), and ResetAutosync().
s_vpTimingDataOriginal
vector< TimingData > AdjustSync::s_vpTimingDataOriginal static
The original TimingData before adjustments were made.
This is designed to work with Split Timing.
Referenced by GetSyncChangeTextSong(), ResetOriginalSyncData(), RevertSyncChanges(), and SaveSyncChanges().
The documentation for this class was generated from the following files:
AdjustSync.h
AdjustSync.cpp