Etterna: XNodeStringValue Class Reference
XNodeStringValue Class Reference
#include <XmlFile.h>
Public Member Functions
XNodeValue * Copy () const override
void GetValue (RString &out) const override
void GetValue (int &out) const override
void GetValue (float &out) const override
void GetValue (bool &out) const override
void GetValue (unsigned &out) const override
void PushValue (lua_State *L) const override
void SetValue (const RString &v) override
void SetValue (int v) override
void SetValue (float v) override
void SetValue (unsigned v) override
void SetValueFromStack (lua_State *L) override
Public Member Functions inherited from XNodeValue
virtual ~XNodeValue ()=default
template<typename T >
T GetValue () const
Public Attributes
RString m_sValue
Member Function Documentation
Copy()
XNodeValue* XNodeStringValue::Copy () const inline override virtual
Implements XNodeValue.
GetValue() [1/5]
void XNodeStringValue::GetValue (RString & out) const override virtual
Implements XNodeValue.
References m_sValue.
GetValue() [2/5]
void XNodeStringValue::GetValue (int & out) const override virtual
Implements XNodeValue.
References m_sValue, and StringToInt().
GetValue() [3/5]
void XNodeStringValue::GetValue (float & out) const override virtual
Implements XNodeValue.
References m_sValue, and StringToFloat().
GetValue() [4/5]
void XNodeStringValue::GetValue (bool & out) const override virtual
Implements XNodeValue.
References m_sValue, and StringToInt().
GetValue() [5/5]
void XNodeStringValue::GetValue (unsigned & out) const override virtual
Implements XNodeValue.
References m_sValue.
PushValue()
void XNodeStringValue::PushValue (lua_State * L) const override virtual
Implements XNodeValue.
References m_sValue, and LuaHelpers::Push().
SetValue() [1/4]
void XNodeStringValue::SetValue (const RString & v) override virtual
Implements XNodeValue.
References m_sValue.
SetValue() [2/4]
void XNodeStringValue::SetValue (int v) override virtual
Implements XNodeValue.
References m_sValue, and ssprintf().
SetValue() [3/4]
void XNodeStringValue::SetValue (float v) override virtual
Implements XNodeValue.
References m_sValue, and ssprintf().
SetValue() [4/4]
void XNodeStringValue::SetValue (unsigned v) override virtual
Implements XNodeValue.
References m_sValue, and ssprintf().
SetValueFromStack()
void XNodeStringValue::SetValueFromStack (lua_State * L) override virtual
Implements XNodeValue.
References m_sValue, and LuaHelpers::Pop().
Member Data Documentation
m_sValue
RString XNodeStringValue::m_sValue
Referenced by GetValue(), PushValue(), SetValue(), and SetValueFromStack().
The documentation for this class was generated from the following files:
XmlFile.h
XmlFile.cpp