Etterna: Download Class Reference
Download Class Reference
#include <DownloadManager.h>
Public Member Functions
Download (string url, string filename="", function< void(Download *)> done=[](Download *) { return;})
~Download ()
void Install ()
void Update (float fDeltaSeconds)
void Failed ()
string StartMessage ()
string Status ()
void PushSelf (lua_State *L)
Public Attributes
function< void(Download *)> Done
CURL * handle { nullptr }
int running { 1 }
ProgressData progress
string speed { "" }
curl_off_t downloadedAtLastUpdate { 0 }
curl_off_t lastUpdateDone { 0 }
string m_Url { "" }
RageFileWrapper p_RFWrapper
DownloadablePack * p_Pack { nullptr }
string m_TempFileName { "" }
Protected Member Functions
string MakeTempFileName (string s)
Constructor & Destructor Documentation
Download()
Download::Download (string url, string filename = "", function< void(Download *)> done = [](Download*) { return; })
References ASSERT, DLMAN, Done, RageFileWrapper::file, handle, initBasicCURLHandle(), m_TempFileName, m_Url, MakeTempFileName(), RageFile::Open(), p_RFWrapper, progress, progressfunc(), and write_data().
~Download()
Download::~Download ()
References DownloadablePack::downloading, FILEMAN, m_TempFileName, p_Pack, and RageFileManager::Remove().
Member Function Documentation
Failed()
void Download::Failed ()
References MessageManager::Broadcast(), LuaReference::CreateFromPush(), MESSAGEMAN, p_Pack, and Message::SetParam().
Install()
void Download::Install ()
References MessageManager::Broadcast(), LuaReference::CreateFromPush(), DLMAN, m_TempFileName, MESSAGEMAN, p_Pack, and Message::SetParam().
MakeTempFileName()
string Download::MakeTempFileName (string s) protected
References Basename(), and DL_DIR.
Referenced by Download().
PushSelf()
void Download::PushSelf (lua_State * L)
Referenced by LunaDownloadablePack::DownloadAndInstall().
StartMessage()
string Download::StartMessage () inline
References m_TempFileName, and m_Url.
Referenced by DownloadManager::DownloadAndInstallPack().
Status()
string Download::Status () inline
References RageFileWrapper::bytes, ProgressData::downloaded, m_TempFileName, p_RFWrapper, progress, speed, and ProgressData::total.
Update()
void Download::Update (float fDeltaSeconds)
References ProgressData::downloaded, downloadedAtLastUpdate, progress, speed, and ProgressData::time.
Member Data Documentation
Done
function<void(Download*)> Download::Done
Referenced by Download().
downloadedAtLastUpdate
curl_off_t Download::downloadedAtLastUpdate { 0 }
Referenced by Update().
handle
CURL* Download::handle { nullptr }
Referenced by Download(), and DownloadManager::DownloadAndInstallPack().
lastUpdateDone
curl_off_t Download::lastUpdateDone { 0 }
m_TempFileName
string Download::m_TempFileName { "" }
Referenced by Download(), Install(), StartMessage(), Status(), and ~Download().
m_Url
string Download::m_Url { "" }
Referenced by Download(), and StartMessage().
p_Pack
DownloadablePack* Download::p_Pack { nullptr }
Referenced by DownloadManager::DownloadAndInstallPack(), Failed(), Install(), and ~Download().
p_RFWrapper
RageFileWrapper Download::p_RFWrapper
Referenced by Download(), Status(), and LunaDownload::Stop().
progress
ProgressData Download::progress
Referenced by Download(), LunaDownload::GetKBDownloaded(), LunaDownload::GetTotalKB(), Status(), and Update().
running
int Download::running { 1 }
speed
string Download::speed { "" }
Referenced by LunaDownload::GetKBPerSecond(), Status(), and Update().
The documentation for this class was generated from the following files:
DownloadManager.h
DownloadManager.cpp