Etterna: LunaTextBanner Class Reference
LunaTextBanner Class Reference
Allow Lua to have access to the TextBanner.
Public Member Functions
LunaTextBanner ()
Public Member Functions inherited from Luna< TextBanner >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int Load (T *p, lua_State *L)
static int SetFromSong (T *p, lua_State *L)
static int SetFromString (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< TextBanner >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< TextBanner >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< TextBanner >
using T = TextBanner
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< TextBanner >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the TextBanner.
Constructor & Destructor Documentation
LunaTextBanner()
LunaTextBanner::LunaTextBanner () inline
References ADD_METHOD, Load(), SetFromSong(), and SetFromString().
Member Function Documentation
Load()
static int LunaTextBanner::Load (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, TextBanner::Load(), and SArg.
Referenced by LunaTextBanner().
SetFromSong()
static int LunaTextBanner::SetFromSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and TextBanner::SetFromSong().
Referenced by LunaTextBanner().
SetFromString()
static int LunaTextBanner::SetFromString (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and TextBanner::SetFromString().
Referenced by LunaTextBanner().
The documentation for this class was generated from the following file:
TextBanner.cpp