Etterna: GameSoundManager.cpp File Reference
GameSoundManager.cpp File Reference
#include "global.h"
#include "GameSoundManager.h"
#include "AnnouncerManager.h"
#include "GameState.h"
#include "LuaManager.h"
#include "NoteData.h"
#include "NotesLoaderSM.h"
#include "NotesLoaderSSC.h"
#include "PrefsManager.h"
#include "RageDisplay.h"
#include "RageLog.h"
#include "RageSound.h"
#include "RageSoundManager.h"
#include "RageUtil.h"
#include "Song.h"
#include "TimingData.h"
#include "arch/Sound/RageSoundDriver.h"
#include "LuaBinding.h"
Classes
struct MusicPlaying
struct MusicToPlay
class LunaGameSoundManager
Allow Lua to have access to the GameSoundManager.
Enumerations
enum FadeState { FADE_NONE, FADE_OUT, FADE_WAIT, FADE_IN }
Functions
static void StartMusic (MusicToPlay &ToPlay)
static void DoPlayOnce (RString sPath)
static void DoPlayOnceFromDir (RString sPath)
static bool SoundWaiting ()
static void StartQueuedSounds ()
int MusicThread_start (void *p)
LUA_REGISTER_CLASS (GameSoundManager)
int LuaFunc_get_sound_driver_list (lua_State *L)
LUAFUNC_REGISTER_COMMON (get_sound_driver_list)
Variables
GameSoundManager * SOUND = NULL
static RageEvent * g_Mutex
static bool g_UpdatingTimer
static bool g_Shutdown
static bool g_bFlushing = false
static FadeState g_FadeState = FADE_NONE
static float g_fDimVolume = 1.0f
static float g_fOriginalVolume = 1.0f
static float g_fDimDurationRemaining = 0.0f
static bool g_bWasPlayingOnLastUpdate = false
static MusicPlaying * g_Playing
static RageThread MusicThread
vector< RString > g_SoundsToPlayOnce
vector< RString > g_SoundsToPlayOnceFromDir
vector< RString > g_SoundsToPlayOnceFromAnnouncer
vector< MusicToPlay > g_MusicsToPlay
static GameSoundManager::PlayMusicParams g_FallbackMusicParams
Enumeration Type Documentation
FadeState
enum FadeState
Enumerator
FADE_NONE
FADE_OUT
FADE_WAIT
FADE_IN
Function Documentation
DoPlayOnce()
static void DoPlayOnce (RString sPath) static
References RageSound::Load().
Referenced by DoPlayOnceFromDir(), and StartQueuedSounds().
DoPlayOnceFromDir()
static void DoPlayOnceFromDir (RString sPath) static
References DoPlayOnce(), GetDirListing(), RandomInt(), and StdString::CStdStr< CT >::Right().
Referenced by StartQueuedSounds().
LUA_REGISTER_CLASS()
LUA_REGISTER_CLASS (GameSoundManager)
LuaFunc_get_sound_driver_list()
int LuaFunc_get_sound_driver_list (lua_State * L)
References RageSoundDriver::GetDefaultSoundDriverList(), and split().
LUAFUNC_REGISTER_COMMON()
LUAFUNC_REGISTER_COMMON (get_sound_driver_list)
MusicThread_start()
int MusicThread_start (void * p)
References g_bFlushing, g_Shutdown, RageMutex::Lock(), RageEvent::Signal(), SoundWaiting(), StartQueuedSounds(), RageMutex::Unlock(), and RageEvent::Wait().
Referenced by GameSoundManager::GameSoundManager().
SoundWaiting()
static bool SoundWaiting () static
References g_MusicsToPlay, g_SoundsToPlayOnce, g_SoundsToPlayOnceFromAnnouncer, and g_SoundsToPlayOnceFromDir.
Referenced by MusicThread_start().
StartMusic()
static void StartMusic (MusicToPlay & ToPlay) static
References MusicToPlay::bAlignBeat, MusicToPlay::bApplyMusicRate, MusicToPlay::bForceLoop, StdString::CStdStr< CT >::EqualsNoCase(), FADE_NONE, MusicToPlay::fFadeInLengthSeconds, MusicToPlay::fFadeOutLengthSeconds, MusicToPlay::fLengthSeconds, fmodfp(), MusicToPlay::fStartSecond, g_FadeState, g_Playing, g_UpdatingTimer, GAMESTATE, TimingData::GetBeatFromElapsedTimeNoOffset(), TimingData::GetElapsedTimeFromBeatNoOffset(), GetExtension(), RageSound::GetLoadedFilePath(), RageSoundManager::GetPlayLatency(), MusicToPlay::HasTiming, IsAFile(), RageSound::IsPlaying(), L, SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), RageMutex::Lock(), LockMut, LOG, MusicPlaying::m_bApplyMusicRate, MusicPlaying::m_bHasTiming, RageSoundLoadParams::m_bSupportRateChanging, MusicPlaying::m_bTimingDelayed, TimingData::m_fBeat0OffsetInSeconds, RageSoundParams::m_fFadeInSeconds, RageSoundParams::m_fFadeOutSeconds, SongPosition::m_fMusicSeconds, SongPosition::m_fSongBeatNoOffset, SongPosition::m_LastBeatUpdate, RageSoundParams::m_LengthSeconds, RageSoundParams::M_LOOP, MusicPlaying::m_Music, MusicPlaying::m_NewTiming, GameState::m_Position, MusicToPlay::m_sFile, Song::m_SongTiming, RageSoundParams::m_StartSecond, RageSoundParams::m_StartTime, MusicToPlay::m_sTimingFile, MusicPlaying::m_Timing, MusicToPlay::m_TimingData, min(), RageSound::SetParams(), SOUNDMAN, RageSound::StartPlaying(), RageLog::Trace(), RageMutex::Unlock(), LockMutex::Unlock(), and TimingData::WhereUAtBroNoOffset().
Referenced by StartQueuedSounds().
StartQueuedSounds()
static void StartQueuedSounds () static
References ANNOUNCER, CHECKPOINT_M, DoPlayOnce(), DoPlayOnceFromDir(), g_MusicsToPlay, g_SoundsToPlayOnce, g_SoundsToPlayOnceFromAnnouncer, g_SoundsToPlayOnceFromDir, AnnouncerManager::GetPathTo(), RageMutex::Lock(), MusicPlaying::m_Music, ssprintf(), StartMusic(), and RageMutex::Unlock().
Referenced by MusicThread_start().
Variable Documentation
g_bFlushing
bool g_bFlushing = false static
Referenced by GameSoundManager::Flush(), and MusicThread_start().
g_bWasPlayingOnLastUpdate
bool g_bWasPlayingOnLastUpdate = false static
Referenced by GameSoundManager::Update().
g_FadeState
FadeState g_FadeState = FADE_NONE static
Referenced by GameSoundManager::DimMusic(), StartMusic(), and GameSoundManager::Update().
g_FallbackMusicParams
GameSoundManager::PlayMusicParams g_FallbackMusicParams static
g_fDimDurationRemaining
float g_fDimDurationRemaining = 0.0f static
Referenced by GameSoundManager::DimMusic(), and GameSoundManager::Update().
g_fDimVolume
float g_fDimVolume = 1.0f static
Referenced by GameSoundManager::DimMusic(), and GameSoundManager::Update().
g_fOriginalVolume
float g_fOriginalVolume = 1.0f static
Referenced by GameSoundManager::DimMusic(), and GameSoundManager::Update().
g_MusicsToPlay
vector<MusicToPlay> g_MusicsToPlay
Referenced by GameSoundManager::PlayMusic(), SoundWaiting(), and StartQueuedSounds().
g_Mutex
RageEvent* g_Mutex static
g_Playing
MusicPlaying* g_Playing static
Referenced by StartMusic().
g_Shutdown
bool g_Shutdown static
Referenced by GameSoundManager::GameSoundManager(), MusicThread_start(), and GameSoundManager::~GameSoundManager().
g_SoundsToPlayOnce
vector<RString> g_SoundsToPlayOnce
Referenced by GameSoundManager::PlayOnce(), SoundWaiting(), and StartQueuedSounds().
g_SoundsToPlayOnceFromAnnouncer
vector<RString> g_SoundsToPlayOnceFromAnnouncer
Referenced by GameSoundManager::PlayOnceFromAnnouncer(), SoundWaiting(), and StartQueuedSounds().
g_SoundsToPlayOnceFromDir
vector<RString> g_SoundsToPlayOnceFromDir
Referenced by GameSoundManager::PlayOnceFromDir(), SoundWaiting(), and StartQueuedSounds().
g_UpdatingTimer
bool g_UpdatingTimer static
Referenced by GameSoundManager::GameSoundManager(), GameSoundManager::HandleSongTimer(), StartMusic(), and GameSoundManager::Update().
MusicThread
RageThread MusicThread static
SOUND
GameSoundManager* SOUND = NULL
Referenced by ScreenSelectMusic::AfterMusicChange(), GameCommand::ApplySelf(), ScreenWithMenuElements::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenGameplay::BeginScreen(), ScreenWithMenuElements::Cancel(), ScreenSelectMusic::CheckBackgroundRequests(), DebugLineReloadCurrentScreen::DoAndLog(), ScreenGameplay::FailFadeRemovePlayer(), ScreenNetSelectBase::HandleScreenMessage(), ScreenHowToPlay::HandleScreenMessage(), ScreenAttract::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenEvaluation::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenSMOnlineLogin::Init(), ScreenPlayerOptions::Init(), ScreenTitleMenu::Init(), ScreenEvaluation::Init(), ScreenNetSelectMusic::MenuBack(), ScreenSelectMaster::MenuStart(), ScreenNetSelectMusic::MusicChanged(), ScreenGameplay::PlayAnnouncer(), GameLoop::RunGameLoop(), ScreenSelectMusic::SelectCurrent(), ShutdownGame(), sm_main(), ScreenWithMenuElements::StartPlayingMusic(), ScreenSelect::Update(), ScreenManager::Update(), MenuTimer::Update(), ScreenSelectMusic::Update(), and ScreenGameplay::UpdateSongPosition().