Etterna: MemoryCardManager Class Reference
MemoryCardManager Class Reference
#include <MemoryCardManager.h>
Public Member Functions
MemoryCardManager ()
~MemoryCardManager ()
void PushSelf (lua_State *L)
Constructor & Destructor Documentation
MemoryCardManager()
MemoryCardManager::MemoryCardManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~MemoryCardManager()
MemoryCardManager::~MemoryCardManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
PushSelf()
void MemoryCardManager::PushSelf (lua_State * L)
Referenced by MemoryCardManager().
The documentation for this class was generated from the following files:
MemoryCardManager.h
MemoryCardManager.cpp