Etterna: RageSoundReader_Merge Class Reference
RageSoundReader_Merge Class Reference
Chain different sounds together.
#include <RageSoundReader_Merge.h>
Public Member Functions
RageSoundReader_Merge ()
~RageSoundReader_Merge () override
RageSoundReader_Merge (const RageSoundReader_Merge &cpy)
RageSoundReader_Merge * Copy () const override
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RString GetError () const override
void AddSound (RageSoundReader *pSound)
void Finish (int iPreferredSampleRate)
Finish adding sounds.
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
int GetSampleRateInternal () const
Private Attributes
int m_iSampleRate
unsigned m_iChannels
vector< RageSoundReader * > m_aSounds
int m_iNextSourceFrame
float m_fCurrentStreamToSourceRatio
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Detailed Description
Chain different sounds together.
Constructor & Destructor Documentation
RageSoundReader_Merge() [1/2]
RageSoundReader_Merge::RageSoundReader_Merge ()
References m_fCurrentStreamToSourceRatio, m_iChannels, m_iNextSourceFrame, and m_iSampleRate.
Referenced by Copy().
~RageSoundReader_Merge()
RageSoundReader_Merge::~RageSoundReader_Merge () override
References FOREACH, and m_aSounds.
RageSoundReader_Merge() [2/2]
RageSoundReader_Merge::RageSoundReader_Merge (const RageSoundReader_Merge & cpy)
References FOREACH_CONST, m_aSounds, m_fCurrentStreamToSourceRatio, m_iChannels, m_iNextSourceFrame, and m_iSampleRate.
Member Function Documentation
AddSound()
void RageSoundReader_Merge::AddSound (RageSoundReader * pSound)
References m_aSounds.
Copy()
RageSoundReader_Merge* RageSoundReader_Merge::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_Merge().
Finish()
void RageSoundReader_Merge::Finish (int iPreferredSampleRate)
Finish adding sounds.
Parameters
iPreferredSampleRate the sample rate for the sounds.
References FOREACH, GetNumChannels(), GetSampleRateInternal(), LOG, m_aSounds, m_iChannels, m_iSampleRate, max(), and RageLog::Warn().
GetError()
RString RageSoundReader_Merge::GetError () const inline override virtual
Implements RageSoundReader.
GetLength()
int RageSoundReader_Merge::GetLength () const override virtual
Implements RageSoundReader.
References m_aSounds, and max().
GetLength_Fast()
int RageSoundReader_Merge::GetLength_Fast () const override virtual
Reimplemented from RageSoundReader.
References m_aSounds, and max().
GetNextSourceFrame()
int RageSoundReader_Merge::GetNextSourceFrame () const inline override virtual
Implements RageSoundReader.
References m_iNextSourceFrame.
Referenced by Read().
GetNumChannels()
unsigned RageSoundReader_Merge::GetNumChannels () const inline override virtual
Implements RageSoundReader.
References m_iChannels.
Referenced by Finish().
GetSampleRate()
int RageSoundReader_Merge::GetSampleRate () const inline override virtual
Implements RageSoundReader.
References m_iSampleRate.
GetSampleRateInternal()
int RageSoundReader_Merge::GetSampleRateInternal () const private
References FOREACH_CONST, and m_aSounds.
Referenced by Finish().
GetStreamToSourceRatio()
float RageSoundReader_Merge::GetStreamToSourceRatio () const inline override virtual
Implements RageSoundReader.
References m_fCurrentStreamToSourceRatio.
Read()
int RageSoundReader_Merge::Read (float * pBuf, int iFrames) override virtual
Implements RageSoundReader.
References ARRAYLEN, ASSERT, Difference(), RageSoundReader::END_OF_FILE, ERROR_CORRECTION_THRESHOLD, GetNextSourceFrame(), RageSoundReader::GetNextSourceFrame(), RageSoundReader::GetNumChannels(), RageSoundReader::GetStreamToSourceRatio(), LOG, m_aSounds, m_fCurrentStreamToSourceRatio, m_iChannels, m_iNextSourceFrame, min(), RageSoundReader::Read(), RageSoundMixBuffer::read(), RageSoundMixBuffer::SetWriteOffset(), RageSoundMixBuffer::size(), RageLog::Trace(), and RageSoundMixBuffer::write().
SetPosition()
int RageSoundReader_Merge::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References m_aSounds, m_iNextSourceFrame, and RageSoundReader::SetPosition().
SetProperty()
bool RageSoundReader_Merge::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader.
References m_aSounds.
Member Data Documentation
m_aSounds
vector<RageSoundReader*> RageSoundReader_Merge::m_aSounds private
Referenced by AddSound(), Finish(), GetLength(), GetLength_Fast(), GetSampleRateInternal(), RageSoundReader_Merge(), Read(), SetPosition(), SetProperty(), and ~RageSoundReader_Merge().
m_fCurrentStreamToSourceRatio
float RageSoundReader_Merge::m_fCurrentStreamToSourceRatio private
Referenced by GetStreamToSourceRatio(), RageSoundReader_Merge(), and Read().
m_iChannels
unsigned RageSoundReader_Merge::m_iChannels private
Referenced by Finish(), GetNumChannels(), RageSoundReader_Merge(), and Read().
m_iNextSourceFrame
int RageSoundReader_Merge::m_iNextSourceFrame private
Referenced by GetNextSourceFrame(), RageSoundReader_Merge(), Read(), and SetPosition().
m_iSampleRate
int RageSoundReader_Merge::m_iSampleRate private
Referenced by Finish(), GetSampleRate(), and RageSoundReader_Merge().
The documentation for this class was generated from the following files:
RageSoundReader_Merge.h
RageSoundReader_Merge.cpp