Etterna: Screenshot Struct Reference
Screenshot Struct Reference
the picture taken of the high score.
#include <HighScore.h>
Public Member Functions
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
bool operator< (Screenshot const &rhs) const
bool operator== (Screenshot const &rhs) const
Public Attributes
RString sFileName
the filename of the screen shot. There is no directory part.
RString sMD5
The MD5 hash of the screen shot file above.
HighScore highScore
The actual high score in question.
Detailed Description
the picture taken of the high score.
Member Function Documentation
CreateNode()
XNode * Screenshot::CreateNode () const
References XNode::AppendChild(), HighScore::CreateNode(), highScore, sFileName, and sMD5.
LoadFromNode()
void Screenshot::LoadFromNode (const XNode * pNode)
References ASSERT, XNode::GetChild(), XNode::GetChildValue(), XNode::GetName(), highScore, HighScore::LoadFromNode(), sFileName, and sMD5.
Referenced by XMLProfile::LoadScreenshotDataFromNode().
operator<()
bool Screenshot::operator< (Screenshot const & rhs) const inline
References HighScore::GetDateTime(), and highScore.
operator==()
bool Screenshot::operator== (Screenshot const & rhs) const inline
References sFileName.
Member Data Documentation
highScore
HighScore Screenshot::highScore
The actual high score in question.
Referenced by LunaProfile::AddScreenshot(), CreateNode(), ScreenEvaluation::Input(), LoadFromNode(), and operator<().
sFileName
RString Screenshot::sFileName
the filename of the screen shot. There is no directory part.
Referenced by LunaProfile::AddScreenshot(), CreateNode(), ScreenEvaluation::Input(), LoadFromNode(), and operator==().
sMD5
RString Screenshot::sMD5
The MD5 hash of the screen shot file above.
Referenced by LunaProfile::AddScreenshot(), CreateNode(), ScreenEvaluation::Input(), and LoadFromNode().
The documentation for this struct was generated from the following files:
HighScore.h
HighScore.cpp