Etterna: ScreenOptionsMasterPrefs.cpp File Reference
ScreenOptionsMasterPrefs.cpp File Reference
#include "ScreenOptionsMasterPrefs.h"
#include "AnnouncerManager.h"
#include "DisplayResolutions.h"
#include "Foreach.h"
#include "Game.h"
#include "GameConstantsAndTypes.h"
#include "GameManager.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "NoteSkinManager.h"
#include "PlayerOptions.h"
#include "PrefsManager.h"
#include "RageDisplay.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "SongOptions.h"
#include "SpecialFiles.h"
#include "StepMania.h"
#include "ThemeManager.h"
#include "global.h"
#include "LuaManager.h"
Classes
struct res_t
Macros
#define remove_empty_back()
#define ADD(x) g_ConfOptions.push_back(x)
Functions
static void GetPrefsDefaultModifiers (PlayerOptions &po, SongOptions &so)
static void SetPrefsDefaultModifiers (const PlayerOptions &po, const SongOptions &so)
template<class T , class U >
int FindClosestEntry (T value, const U *mapping, unsigned cnt)
template<class T >
static void MoveMap (int &sel, T &opt, bool ToSel, const T *mapping, unsigned cnt)
template<class T >
static void MoveMap (int &sel, IPreference &opt, bool ToSel, const T *mapping, unsigned cnt)
template<class T >
static void MoveMap (int &sel, const ConfOption *pConfOption, bool ToSel, const T *mapping, unsigned cnt)
template<class T >
static void MovePref (int &iSel, bool bToSel, const ConfOption *pConfOption)
template<>
void MovePref< bool > (int &iSel, bool bToSel, const ConfOption *pConfOption)
static void MoveNop (int &iSel, bool bToSel, const ConfOption *pConfOption)
static void GameChoices (vector< RString > &out)
static void GameSel (int &sel, bool ToSel, const ConfOption *pConfOption)
static void LanguageChoices (vector< RString > &out)
static void Language (int &sel, bool ToSel, const ConfOption *pConfOption)
static void ThemeChoices (vector< RString > &out)
static void cache_display_resolution_list ()
static void DisplayResolutionChoices (vector< RString > &out)
static void RequestedTheme (int &sel, bool ToSel, const ConfOption *pConfOption)
static void AnnouncerChoices (vector< RString > &out)
static void Announcer (int &sel, bool ToSel, const ConfOption *pConfOption)
static void DefaultNoteSkinChoices (vector< RString > &out)
static void DefaultNoteSkin (int &sel, bool ToSel, const ConfOption *pConfOption)
static void DefaultFailChoices (vector< RString > &out)
static void DefaultFailType (int &sel, bool to_sel, const ConfOption *conf_option)
static void BGBrightness (int &sel, bool ToSel, const ConfOption *pConfOption)
static void BGBrightnessNoZero (int &sel, bool ToSel, const ConfOption *pConfOption)
static void BGBrightnessOrStatic (int &sel, bool ToSel, const ConfOption *pConfOption)
static void NumBackgrounds (int &sel, bool ToSel, const ConfOption *pConfOption)
static void MusicWheelSwitchSpeed (int &sel, bool ToSel, const ConfOption *pConfOption)
static void InputDebounceTime (int &sel, bool to_sel, ConfOption const *conf_option)
static void TimingWindowScale (int &sel, bool ToSel, const ConfOption *pConfOption)
Timing Window scale.
static void LifeDifficulty (int &sel, bool ToSel, const ConfOption *pConfOption)
Life Difficulty scale.
static int GetTimingDifficulty ()
LuaFunction (GetTimingDifficulty, GetTimingDifficulty())
static int SetTimingDifficulty (float judge)
LuaFunction (SetTimingDifficulty, SetTimingDifficulty(FArg(1))) static int GetLifeDifficulty()
LuaFunction (GetLifeDifficulty, GetLifeDifficulty())
bool operator< (res_t const &lhs, res_t const &rhs)
bool operator> (res_t const &lhs, res_t const &rhs)
bool operator<= (res_t const &lhs, res_t const &rhs)
bool operator>= (res_t const &lhs, res_t const &rhs)
res_t operator- (res_t lhs, res_t const &rhs)
static void DisplayResolutionM (int &sel, bool ToSel, const ConfOption *pConfOption)
static void DisplayColorDepth (int &sel, bool ToSel, const ConfOption *pConfOption)
static void MaxTextureResolution (int &sel, bool ToSel, const ConfOption *pConfOption)
static void TextureColorDepth (int &sel, bool ToSel, const ConfOption *pConfOption)
static void MovieColorDepth (int &sel, bool ToSel, const ConfOption *pConfOption)
static void RefreshRate (int &sel, bool ToSel, const ConfOption *pConfOption)
static void DisplayAspectRatio (int &sel, bool ToSel, const ConfOption *pConfOption)
static void WideScreen16_10 (int &sel, bool ToSel, const ConfOption *pConfOption)
static void WideScreen16_9 (int &sel, bool ToSel, const ConfOption *pConfOption)
static void SoundVolume (int &sel, bool ToSel, const ConfOption *pConfOption)
static void SoundVolumeAttract (int &sel, bool ToSel, const ConfOption *pConfOption)
static void VisualDelaySeconds (int &sel, bool ToSel, const ConfOption *pConfOption)
static void GlobalOffsetSeconds (int &sel, bool ToSel, const ConfOption *pConfOption)
static void EditRecordModeLeadIn (int &sel, bool to_sel, const ConfOption *conf_option)
static void EditClearPromptThreshold (int &sel, bool to_sel, const ConfOption *conf_option)
static void InitializeConfOptions ()
Variables
static DisplayResolutions display_resolution_list
static LocalizedString OFF ("ScreenOptionsMasterPrefs", "Off")
static vector< ConfOption > g_ConfOptions
Detailed Description
Author
Glenn Maynard (c) 2003-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
ADD
#define ADD (x) g_ConfOptions.push_back(x)
Referenced by InitializeConfOptions().
remove_empty_back
#define remove_empty_back ()
Value:
if (as.back() == "") {                                                     \
        as.pop_back();                                                         \
    }
Referenced by SetPrefsDefaultModifiers().
Function Documentation
Announcer()
static void Announcer (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ANNOUNCER, AnnouncerManager::GetCurAnnouncerName(), PrefsManager::m_sAnnouncer, ConfOption::MakeOptionsList(), PREFSMAN, and AnnouncerManager::SwitchAnnouncer().
Referenced by InitializeConfOptions().
AnnouncerChoices()
static void AnnouncerChoices (vector< RString > & out) static
References ANNOUNCER, AnnouncerManager::GetAnnouncerNames(), and OFF.
Referenced by InitializeConfOptions().
BGBrightness()
static void BGBrightness (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
BGBrightnessNoZero()
static void BGBrightnessNoZero (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
BGBrightnessOrStatic()
static void BGBrightnessOrStatic (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, IPreference::FromString(), IPreference::GetPreferenceByName(), MoveMap(), and IPreference::ToString().
Referenced by InitializeConfOptions().
cache_display_resolution_list()
static void cache_display_resolution_list () static
References DISPLAY, display_resolution_list, and RageDisplay::GetDisplayResolutions().
Referenced by DisplayResolutionChoices(), and DisplayResolutionM().
DefaultFailChoices()
static void DefaultFailChoices (vector< RString > & out) static
Referenced by InitializeConfOptions().
DefaultFailType()
static void DefaultFailType (int & sel, bool to_sel, const ConfOption * conf_option) static
References PlayerOptions::FromString(), GetPrefsDefaultModifiers(), PlayerOptions::m_FailType, PrefsManager::m_sDefaultModifiers, PREFSMAN, and SetPrefsDefaultModifiers().
Referenced by InitializeConfOptions().
DefaultNoteSkin()
static void DefaultNoteSkin (int & sel, bool ToSel, const ConfOption * pConfOption) static
References PlayerOptions::FromString(), GetPrefsDefaultModifiers(), PrefsManager::m_sDefaultModifiers, PlayerOptions::m_sNoteSkin, ConfOption::MakeOptionsList(), PREFSMAN, and SetPrefsDefaultModifiers().
Referenced by InitializeConfOptions().
DefaultNoteSkinChoices()
static void DefaultNoteSkinChoices (vector< RString > & out) static
References NoteSkinManager::GetNoteSkinNames(), and NOTESKIN.
Referenced by InitializeConfOptions().
DisplayAspectRatio()
static void DisplayAspectRatio (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
DisplayColorDepth()
static void DisplayColorDepth (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
DisplayResolutionChoices()
static void DisplayResolutionChoices (vector< RString > & out) static
References cache_display_resolution_list(), display_resolution_list, FOREACHS_CONST, and ssprintf().
Referenced by InitializeConfOptions().
DisplayResolutionM()
static void DisplayResolutionM (int & sel, bool ToSel, const ConfOption * pConfOption) static
References cache_display_resolution_list(), display_resolution_list, FOREACHS_CONST, res_t::h, PrefsManager::m_iDisplayHeight, PrefsManager::m_iDisplayWidth, MoveMap(), PREFSMAN, Preference< T >::Set(), and res_t::w.
Referenced by InitializeConfOptions().
EditClearPromptThreshold()
static void EditClearPromptThreshold (int & sel, bool to_sel, const ConfOption * conf_option) static
References ARRAYLEN, and MoveMap().
EditRecordModeLeadIn()
static void EditRecordModeLeadIn (int & sel, bool to_sel, const ConfOption * conf_option) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
FindClosestEntry()
template<class T , class U > int FindClosestEntry (T value, const U * mapping, unsigned cnt)
Referenced by MoveMap().
GameChoices()
static void GameChoices (vector< RString > & out) static
References FOREACH, GAMEMAN, and GameManager::GetEnabledGames().
Referenced by InitializeConfOptions().
GameSel()
static void GameSel (int & sel, bool ToSel, const ConfOption * pConfOption) static
References GAMEMAN, PrefsManager::GetCurrentGame(), GameManager::GetEnabledGames(), ConfOption::MakeOptionsList(), PREFSMAN, and PrefsManager::SetCurrentGame().
Referenced by InitializeConfOptions().
GetPrefsDefaultModifiers()
static void GetPrefsDefaultModifiers (PlayerOptions & po, SongOptions & so) static
References SongOptions::FromString(), PlayerOptions::FromString(), PrefsManager::m_sDefaultModifiers, and PREFSMAN.
Referenced by DefaultFailType(), and DefaultNoteSkin().
GetTimingDifficulty()
static int GetTimingDifficulty () static
References ConfOption::Find(), and TimingWindowScale().
GlobalOffsetSeconds()
static void GlobalOffsetSeconds (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, f, MoveMap(), and SCALE.
Referenced by InitializeConfOptions().
InitializeConfOptions()
static void InitializeConfOptions () static
References ADD, ConfOption::AddOption(), Announcer(), AnnouncerChoices(), BGBrightness(), BGBrightnessNoZero(), BGBrightnessOrStatic(), DefaultFailChoices(), DefaultFailType(), DefaultNoteSkin(), DefaultNoteSkinChoices(), display_resolution_list, DisplayAspectRatio(), DisplayColorDepth(), DisplayResolutionChoices(), DisplayResolutionM(), EditRecordModeLeadIn(), GameChoices(), GameSel(), GlobalOffsetSeconds(), InputDebounceTime(), Language(), LanguageChoices(), LifeDifficulty(), MaxTextureResolution(), MoveNop(), MovePref< bool >(), MovieColorDepth(), MusicWheelSwitchSpeed(), NumBackgrounds(), OPT_APPLY_ASPECT_RATIO, OPT_APPLY_GRAPHICS, OPT_APPLY_SONG, OPT_APPLY_SOUND, OPT_APPLY_THEME, OPT_CHANGE_GAME, RefreshRate(), RequestedTheme(), SoundVolume(), SoundVolumeAttract(), ssprintf(), TextureColorDepth(), ThemeChoices(), TimingWindowScale(), VisualDelaySeconds(), WideScreen16_10(), and WideScreen16_9().
Referenced by ConfOption::Find().
InputDebounceTime()
static void InputDebounceTime (int & sel, bool to_sel, ConfOption const * conf_option) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
Language()
static void Language (int & sel, bool ToSel, const ConfOption * pConfOption) static
References SpecialFiles::BASE_LANGUAGE, ThemeManager::GetCurLanguage(), ThemeManager::GetCurThemeName(), ThemeManager::GetLanguages(), LOG, PrefsManager::m_bPseudoLocalize, PrefsManager::m_sLanguage, PREFSMAN, SortRStringArray(), ThemeManager::SwitchThemeAndLanguage(), THEME, and RageLog::Warn().
Referenced by InitializeConfOptions().
LanguageChoices()
static void LanguageChoices (vector< RString > & out) static
References FOREACH_CONST, GetLanguageInfo(), ThemeManager::GetLanguages(), ThemeManager::GetString(), SortRStringArray(), LanguageInfo::szEnglishName, and THEME.
Referenced by InitializeConfOptions().
LifeDifficulty()
static void LifeDifficulty (int & sel, bool ToSel, const ConfOption * pConfOption) static
Life Difficulty scale.
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions(), and LuaFunction().
LuaFunction() [1/3]
LuaFunction (GetTimingDifficulty , GetTimingDifficulty())
LuaFunction() [2/3]
LuaFunction (SetTimingDifficulty , SetTimingDifficulty(FArg(1)))
References ConfOption::Find(), and LifeDifficulty().
LuaFunction() [3/3]
LuaFunction (GetLifeDifficulty , GetLifeDifficulty())
MaxTextureResolution()
static void MaxTextureResolution (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
MoveMap() [1/3]
template<class T > static void MoveMap (int & sel, T & opt, bool ToSel, const T * mapping, unsigned cnt) static
References FindClosestEntry().
Referenced by BGBrightness(), BGBrightnessNoZero(), BGBrightnessOrStatic(), DisplayAspectRatio(), DisplayColorDepth(), DisplayResolutionM(), EditClearPromptThreshold(), EditRecordModeLeadIn(), GlobalOffsetSeconds(), InputDebounceTime(), LifeDifficulty(), MaxTextureResolution(), MoveMap(), MovieColorDepth(), MusicWheelSwitchSpeed(), NumBackgrounds(), RefreshRate(), SoundVolume(), SoundVolumeAttract(), TextureColorDepth(), TimingWindowScale(), VisualDelaySeconds(), WideScreen16_10(), and WideScreen16_9().
MoveMap() [2/3]
template<class T > static void MoveMap (int & sel, IPreference & opt, bool ToSel, const T * mapping, unsigned cnt) static
References FindClosestEntry(), IPreference::FromString(), StringConversion::FromString(), IPreference::ToString(), and StringConversion::ToString().
MoveMap() [3/3]
template<class T > static void MoveMap (int & sel, const ConfOption * pConfOption, bool ToSel, const T * mapping, unsigned cnt) static
References ASSERT, ASSERT_M, IPreference::GetPreferenceByName(), ConfOption::m_sPrefName, and MoveMap().
MoveNop()
static void MoveNop (int & iSel, bool bToSel, const ConfOption * pConfOption) static
Referenced by InitializeConfOptions().
MovePref()
template<class T > static void MovePref (int & iSel, bool bToSel, const ConfOption * pConfOption) static
References ASSERT_M, IPreference::FromString(), StringConversion::FromString(), IPreference::GetPreferenceByName(), ConfOption::m_sPrefName, T, IPreference::ToString(), and StringConversion::ToString().
MovePref< bool >()
template<> void MovePref< bool > (int & iSel, bool bToSel, const ConfOption * pConfOption)
References ASSERT_M, IPreference::FromString(), StringConversion::FromString(), IPreference::GetPreferenceByName(), IPreference::ToString(), and StringConversion::ToString< bool >().
Referenced by InitializeConfOptions().
MovieColorDepth()
static void MovieColorDepth (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
MusicWheelSwitchSpeed()
static void MusicWheelSwitchSpeed (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
NumBackgrounds()
static void NumBackgrounds (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
operator-()
res_t operator- (res_t lhs, res_t const & rhs) inline
operator<()
bool operator< (res_t const & lhs, res_t const & rhs) inline
References res_t::h, and res_t::w.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (res_t const & lhs, res_t const & rhs) inline
References operator<().
operator>()
bool operator> (res_t const & lhs, res_t const & rhs) inline
References operator<().
operator>=()
bool operator>= (res_t const & lhs, res_t const & rhs) inline
References operator<().
RefreshRate()
static void RefreshRate (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, MoveMap(), and REFRESH_DEFAULT.
Referenced by InitializeConfOptions().
RequestedTheme()
static void RequestedTheme (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ThemeManager::GetSelectableThemeNames(), PrefsManager::m_sTheme, ConfOption::MakeOptionsList(), PREFSMAN, and THEME.
Referenced by InitializeConfOptions().
SetPrefsDefaultModifiers()
static void SetPrefsDefaultModifiers (const PlayerOptions & po, const SongOptions & so) static
References SongOptions::GetString(), PlayerOptions::GetString(), Rage::join(), PrefsManager::m_sDefaultModifiers, PREFSMAN, and remove_empty_back.
Referenced by DefaultFailType(), and DefaultNoteSkin().
SetTimingDifficulty()
static int SetTimingDifficulty (float judge) static
References ConfOption::Find(), IPreference::FromString(), IPreference::GetPreferenceByName(), and StringConversion::ToString().
SoundVolume()
static void SoundVolume (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
SoundVolumeAttract()
static void SoundVolumeAttract (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
TextureColorDepth()
static void TextureColorDepth (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
ThemeChoices()
static void ThemeChoices (vector< RString > & out) static
References FOREACH, ThemeManager::GetSelectableThemeNames(), ThemeManager::GetThemeDisplayName(), and THEME.
Referenced by InitializeConfOptions().
TimingWindowScale()
static void TimingWindowScale (int & sel, bool ToSel, const ConfOption * pConfOption) static
Timing Window scale.
References ARRAYLEN, and MoveMap().
Referenced by GetTimingDifficulty(), and InitializeConfOptions().
VisualDelaySeconds()
static void VisualDelaySeconds (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
WideScreen16_10()
static void WideScreen16_10 (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
WideScreen16_9()
static void WideScreen16_9 (int & sel, bool ToSel, const ConfOption * pConfOption) static
References ARRAYLEN, and MoveMap().
Referenced by InitializeConfOptions().
Variable Documentation
display_resolution_list
DisplayResolutions display_resolution_list static
Referenced by cache_display_resolution_list(), DisplayResolutionChoices(), DisplayResolutionM(), and InitializeConfOptions().
g_ConfOptions
vector<ConfOption> g_ConfOptions static
OFF
LocalizedString OFF("ScreenOptionsMasterPrefs", "Off") static
Referenced by AnnouncerChoices().