Etterna: RageTexturePreloader Class Reference
RageTexturePreloader Class Reference
Load the textures in advance for using them later.
#include <RageTexturePreloader.h>
Public Member Functions
RageTexturePreloader ()
RageTexturePreloader (const RageTexturePreloader &cpy)
RageTexturePreloader & operator= (const RageTexturePreloader &rhs)
~RageTexturePreloader ()
void Load (const RageTextureID &ID)
void UnloadAll ()
void Swap (RageTexturePreloader &rhs)
Private Attributes
vector< RageTexture * > m_apTextures
Detailed Description
Load the textures in advance for using them later.
Constructor & Destructor Documentation
RageTexturePreloader() [1/2]
RageTexturePreloader::RageTexturePreloader () inline
RageTexturePreloader() [2/2]
RageTexturePreloader::RageTexturePreloader (const RageTexturePreloader & cpy) inline
~RageTexturePreloader()
RageTexturePreloader::~RageTexturePreloader ()
References UnloadAll().
Member Function Documentation
Load()
void RageTexturePreloader::Load (const RageTextureID & ID)
References ASSERT, RageTextureManager::LoadTexture(), m_apTextures, and TEXTUREMAN.
Referenced by Character::DemandGraphics(), ScreenSelectMusic::Init(), and SongManager::PreloadSongImages().
operator=()
RageTexturePreloader & RageTexturePreloader::operator= (const RageTexturePreloader & rhs)
References RageTextureManager::CopyTexture(), m_apTextures, TEXTUREMAN, and UnloadAll().
Swap()
void RageTexturePreloader::Swap (RageTexturePreloader & rhs) inline
References m_apTextures, and swap().
Referenced by SongManager::PreloadSongImages().
UnloadAll()
void RageTexturePreloader::UnloadAll ()
References m_apTextures, TEXTUREMAN, and RageTextureManager::UnloadTexture().
Referenced by operator=(), Character::UndemandGraphics(), and ~RageTexturePreloader().
Member Data Documentation
m_apTextures
vector<RageTexture*> RageTexturePreloader::m_apTextures private
Referenced by Load(), operator=(), Swap(), and UnloadAll().
The documentation for this class was generated from the following files:
RageTexturePreloader.h
RageTexturePreloader.cpp