Etterna: RageSurface_Save_PNG.cpp File Reference
RageSurface_Save_PNG.cpp File Reference
#include "RageSurface_Save_PNG.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageUtil.h"
#include "global.h"
#include <png.h>
Classes
struct error_info
Functions
static void SafePngError (png_struct *pPng, const RString &sStr)
static void RageFile_png_write (png_struct *pPng, png_byte *pData, png_size_t iSize)
static void RageFile_png_flush (png_struct *pPng)
static void PNG_Error (png_struct *pPng, const char *szError)
static void PNG_Warning (png_struct *png, const char *warning)
static bool RageSurface_Save_PNG (RageFile &f, char szErrorbuf[1024], RageSurface *pImgIn)
Function Documentation
PNG_Error()
static void PNG_Error (png_struct * pPng, const char * szError) static
References error_info::szErr.
Referenced by RageSurface_Save_PNG().
PNG_Warning()
static void PNG_Warning (png_struct * png, const char * warning) static
References LOG, and RageLog::Trace().
Referenced by RageSurface_Save_PNG().
RageFile_png_flush()
static void RageFile_png_flush (png_struct * pPng) static
References RageFile::Flush(), RageFile::GetError(), and SafePngError().
Referenced by RageSurface_Save_PNG().
RageFile_png_write()
static void RageFile_png_write (png_struct * pPng, png_byte * pData, png_size_t iSize) static
References RageFile::GetError(), SafePngError(), and RageFile::Write().
Referenced by RageSurface_Save_PNG().
RageSurface_Save_PNG()
static bool RageSurface_Save_PNG (RageFile & f, char szErrorbuf[1024], RageSurface * pImgIn) static
References RageSurfaceUtils::ConvertSurface(), RageSurface::h, RageSurface::pitch, RageSurface::pixels, PNG_Error(), PNG_Warning(), RageFile_png_flush(), RageFile_png_write(), Swap32BE(), error_info::szErr, and RageSurface::w.
Referenced by RageSurfaceUtils::SavePNG().
SafePngError()
static void SafePngError (png_struct * pPng, const RString & sStr) static
Referenced by RageFile_png_flush(), and RageFile_png_write().