Etterna: RageSoundReader_Filter Class Reference
RageSoundReader_Filter Class Reference
#include <RageSoundReader_Filter.h>
Public Member Functions
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
virtual RageSoundReader * Copy () const =0
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Protected Attributes
HiddenPtr< RageSoundReader > m_pSource
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Constructor & Destructor Documentation
RageSoundReader_Filter()
RageSoundReader_Filter::RageSoundReader_Filter (RageSoundReader * pSource) inline
Member Function Documentation
GetError()
RString RageSoundReader_Filter::GetError () const inline override virtual
Implements RageSoundReader.
References RageSoundReader::GetError(), and m_pSource.
GetLength()
int RageSoundReader_Filter::GetLength () const inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer.
References RageSoundReader::GetLength(), and m_pSource.
GetLength_Fast()
int RageSoundReader_Filter::GetLength_Fast () const inline override virtual
Reimplemented from RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer.
References RageSoundReader::GetLength_Fast(), and m_pSource.
GetNextSourceFrame()
int RageSoundReader_Filter::GetNextSourceFrame () const inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, RageSoundReader_Resample_Good, and RageSoundReader_SpeedChange.
References RageSoundReader::GetNextSourceFrame(), and m_pSource.
Referenced by RageSoundReader_SpeedChange::GetNextSourceFrame().
GetNumChannels()
unsigned RageSoundReader_Filter::GetNumChannels () const inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, and RageSoundReader_Pan.
References RageSoundReader::GetNumChannels(), and m_pSource.
Referenced by RageSoundReader_Extend::GetData(), RageSoundReader_Pan::GetNumChannels(), RageSoundReader_Extend::Read(), and RageSoundReader_PostBuffering::Read().
GetSampleRate()
int RageSoundReader_Filter::GetSampleRate () const inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_Resample_Good, and RageSoundReader_ThreadedBuffer.
References RageSoundReader::GetSampleRate(), and m_pSource.
Referenced by RageSoundReader_SpeedChange::GetWindowSizeFrames(), RageSoundReader_PitchChange::RageSoundReader_PitchChange(), and RageSoundReader_Extend::SetProperty().
GetSource()
RageSoundReader* RageSoundReader_Filter::GetSource () inline override virtual
Reimplemented from RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer.
References m_pSource.
Referenced by RageSoundReader_PitchChange::RageSoundReader_PitchChange().
GetStreamToSourceRatio()
float RageSoundReader_Filter::GetStreamToSourceRatio () const inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, RageSoundReader_Resample_Good, and RageSoundReader_SpeedChange.
References RageSoundReader::GetStreamToSourceRatio(), and m_pSource.
Referenced by RageSoundReader_SpeedChange::GetStreamToSourceRatio(), and RageSoundReader_PitchChange::Read().
Read()
int RageSoundReader_Filter::Read (float * pBuf, int iFrames) inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, RageSoundReader_PitchChange, RageSoundReader_Resample_Good, RageSoundReader_Pan, RageSoundReader_PostBuffering, and RageSoundReader_SpeedChange.
References m_pSource, and RageSoundReader::Read().
Referenced by RageSoundReader_Extend::GetData(), and RageSoundReader_PitchChange::Read().
SetPosition()
int RageSoundReader_Filter::SetPosition (int iFrame) inline override virtual
Implements RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, RageSoundReader_Resample_Good, and RageSoundReader_SpeedChange.
References m_pSource, and RageSoundReader::SetPosition().
Referenced by RageSoundReader_SpeedChange::SetPosition(), and RageSoundReader_ThreadedBuffer::SetPosition().
SetProperty()
bool RageSoundReader_Filter::SetProperty (const RString & sProperty, float fValue) inline override virtual
Reimplemented from RageSoundReader.
Reimplemented in RageSoundReader_ThreadedBuffer, RageSoundReader_Resample_Good, RageSoundReader_SpeedChange, RageSoundReader_PitchChange, RageSoundReader_Pan, and RageSoundReader_PostBuffering.
References m_pSource, and RageSoundReader::SetProperty().
Referenced by RageSoundReader_PostBuffering::SetProperty(), RageSoundReader_Pan::SetProperty(), RageSoundReader_PitchChange::SetProperty(), and RageSoundReader_SpeedChange::SetProperty().
Member Data Documentation
m_pSource
HiddenPtr<RageSoundReader> RageSoundReader_Filter::m_pSource protected
Referenced by RageSoundReader_ThreadedBuffer::FillBlock(), RageSoundReader_SpeedChange::FillData(), RageSoundReader_Extend::GetData(), GetError(), RageSoundReader_Resample_Good::GetFactors(), GetLength(), RageSoundReader_ThreadedBuffer::GetLength(), GetLength_Fast(), RageSoundReader_ThreadedBuffer::GetLength_Fast(), RageSoundReader_Resample_Good::GetNextSourceFrame(), GetNextSourceFrame(), GetNumChannels(), GetSampleRate(), GetSource(), RageSoundReader_Resample_Good::GetStreamToSourceRatio(), GetStreamToSourceRatio(), RageSoundReader_PitchChange::RageSoundReader_PitchChange(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageSoundReader_SpeedChange::Read(), RageSoundReader_PostBuffering::Read(), RageSoundReader_Pan::Read(), RageSoundReader_Resample_Good::Read(), Read(), RageSoundReader_Resample_Good::ReopenResampler(), RageSoundReader_Resample_Good::Reset(), RageSoundReader_Extend::SetPosition(), RageSoundReader_Resample_Good::SetPosition(), SetPosition(), RageSoundReader_Resample_Good::SetProperty(), RageSoundReader_ThreadedBuffer::SetProperty(), and SetProperty().
The documentation for this class was generated from the following file:
RageSoundReader_Filter.h