Etterna: RageThread Class Reference
RageThread Class Reference
Thread, mutex, semaphore, and event classes.
#include <RageThreads.h>
Public Member Functions
RageThread ()
RageThread (const RageThread &cpy)
~RageThread ()
void SetName (const RString &n)
RString GetName () const
void Create (int(*fn)(void *), void *data)
void Halt (bool Kill=false)
void Resume ()
int Wait ()
bool IsCreated () const
Static Public Member Functions
static void HaltAllThreads (bool Kill=false)
static void ResumeAllThreads ()
static uint64_t GetCurrentThreadID ()
static const char * GetCurrentThreadName ()
static const char * GetThreadNameByID (uint64_t iID)
static bool EnumThreadIDs (int n, uint64_t &iID)
static bool GetSupportsTLS ()
static void SetSupportsTLS (bool b)
static bool GetIsShowingDialog ()
static void SetIsShowingDialog (bool b)
static uint64_t GetInvalidThreadID ()
Private Member Functions
RageThread & operator= (const RageThread &rhs)
Private Attributes
ThreadSlot * m_pSlot
RString m_sName
Static Private Attributes
static bool s_bSystemSupportsTLS = false
static bool s_bIsShowingDialog = false
Detailed Description
Thread, mutex, semaphore, and event classes.
Constructor & Destructor Documentation
RageThread() [1/2]
RageThread::RageThread ()
RageThread() [2/2]
RageThread::RageThread (const RageThread & cpy)
~RageThread()
RageThread::~RageThread ()
References m_pSlot, and Wait().
Member Function Documentation
Create()
void RageThread::Create (int(*)(void *) fn, void * data)
References ASSERT, FindEmptyThreadSlot(), GetThreadSlotsLock(), InitThreads(), LockMut, LOG, ThreadSlot::m_iID, ThreadSlot::m_pImpl, m_pSlot, m_sName, ThreadSlot::m_szName, ThreadSlot::m_szThreadFormattedOutput, and RageLog::Trace().
Referenced by BackgroundLoader::BackgroundLoader(), ConcurrentRenderer::ConcurrentRenderer(), InputHandler_SextetStream::Impl::createThread(), GameSoundManager::GameSoundManager(), RageSoundDriver_DSound_Software::Init(), RageSoundDriver_WaveOut::Init(), RageSoundDriver_ALSA9_Software::Init(), RageSoundDriver_WDMKS::Init(), RageSoundDriver_OSS::Init(), InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO(), InputHandler_MacOSX_HID::InputHandler_MacOSX_HID(), InputHandler_Win32_Pump::InputHandler_Win32_Pump(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageSoundDriver::StartDecodeThread(), InputHandler_Linux_Event::StartThread(), InputHandler_Linux_Joystick::StartThread(), RageWorkerThread::StartThread(), and InputHandler_DInput::StartThread().
EnumThreadIDs()
bool RageThread::EnumThreadIDs (int n, uint64_t & iID) static
References GetThreadSlotsLock(), LockMut, ThreadSlot::m_bUsed, ThreadSlot::m_iID, and MAX_THREADS.
GetCurrentThreadID()
uint64_t RageThread::GetCurrentThreadID () static
Referenced by LuaThreadVariable::GetCurrentThreadIDString(), GetCurrentThreadName(), GetCurThreadSlot(), RageException::SetCleanupHandler(), and RageException::Throw().
GetCurrentThreadName()
const char * RageThread::GetCurrentThreadName () static
References GetCurrentThreadID(), and GetThreadNameByID().
GetInvalidThreadID()
uint64_t RageThread::GetInvalidThreadID () static
Referenced by RageException::Throw().
GetIsShowingDialog()
static bool RageThread::GetIsShowingDialog () inline static
References s_bIsShowingDialog.
Referenced by RageSemaphore::Wait().
GetName()
RString RageThread::GetName () const inline
References m_sName.
GetSupportsTLS()
static bool RageThread::GetSupportsTLS () inline static
References s_bSystemSupportsTLS.
Referenced by sm_main().
GetThreadNameByID()
const char * RageThread::GetThreadNameByID (uint64_t iID) static
References ThreadSlot::GetThreadName(), and GetThreadSlotFromID().
Referenced by GetCurrentThreadName().
Halt()
void RageThread::Halt (bool Kill = false)
References ASSERT, ThreadSlot::m_pImpl, and m_pSlot.
HaltAllThreads()
void RageThread::HaltAllThreads (bool Kill = false) static
IsCreated()
bool RageThread::IsCreated () const inline
References m_pSlot.
Referenced by InputHandler_Linux_Joystick::GetDevicesAndDescriptions(), InputHandler_Win32_Pump::HandleInput(), RageSoundDriver::MixIntoBuffer(), RageSoundDriver::SetDecodeBufferSize(), InputHandler_DInput::ShutdownThread(), RageSoundDriver::StartDecodeThread(), RageWorkerThread::StartThread(), InputHandler_DInput::StartThread(), InputHandler_Linux_Event::TryDevice(), InputHandler_Linux_Joystick::TryDevice(), InputHandler_Win32_Pump::Update(), InputHandler_DInput::Update(), InputHandler_SextetStream::Impl::~Impl(), InputHandler_Linux_Event::~InputHandler_Linux_Event(), InputHandler_Linux_Joystick::~InputHandler_Linux_Joystick(), InputHandler_Linux_PIUIO::~InputHandler_Linux_PIUIO(), InputHandler_Win32_Pump::~InputHandler_Win32_Pump(), RageSoundDriver::~RageSoundDriver(), RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software(), RageSoundDriver_DSound_Software::~RageSoundDriver_DSound_Software(), RageSoundDriver_OSS::~RageSoundDriver_OSS(), RageSoundDriver_WaveOut::~RageSoundDriver_WaveOut(), RageSoundDriver_WDMKS::~RageSoundDriver_WDMKS(), and RageWorkerThread::~RageWorkerThread().
operator=()
RageThread& RageThread::operator= (const RageThread & rhs) private
Resume()
void RageThread::Resume ()
References ASSERT, ThreadSlot::m_pImpl, and m_pSlot.
ResumeAllThreads()
void RageThread::ResumeAllThreads () static
SetIsShowingDialog()
static void RageThread::SetIsShowingDialog (bool b) inline static
References s_bIsShowingDialog.
SetName()
void RageThread::SetName (const RString & n) inline
References m_sName.
Referenced by BackgroundLoader::BackgroundLoader(), ConcurrentRenderer::ConcurrentRenderer(), InputHandler_SextetStream::Impl::createThread(), GameSoundManager::GameSoundManager(), RageSoundDriver_DSound_Software::Init(), RageSoundDriver_WaveOut::Init(), RageSoundDriver_ALSA9_Software::Init(), RageSoundDriver_WDMKS::Init(), RageSoundDriver_OSS::Init(), InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO(), InputHandler_MacOSX_HID::InputHandler_MacOSX_HID(), InputHandler_Win32_Pump::InputHandler_Win32_Pump(), RageSoundDriver::RageSoundDriver(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageWorkerThread::RageWorkerThread(), InputHandler_Linux_Event::StartThread(), InputHandler_Linux_Joystick::StartThread(), and InputHandler_DInput::StartThread().
SetSupportsTLS()
static void RageThread::SetSupportsTLS (bool b) inline static
References s_bSystemSupportsTLS.
Wait()
int RageThread::Wait ()
References ASSERT, GetThreadSlotsLock(), LockMut, ThreadSlot::m_pImpl, m_pSlot, and ThreadSlot::Release().
Referenced by InputHandler_DInput::ShutdownThread(), InputHandler_Linux_Event::StopThread(), InputHandler_Linux_Joystick::StopThread(), RageWorkerThread::StopThread(), BackgroundLoader::~BackgroundLoader(), ConcurrentRenderer::~ConcurrentRenderer(), GameSoundManager::~GameSoundManager(), InputHandler_SextetStream::Impl::~Impl(), InputHandler_Linux_PIUIO::~InputHandler_Linux_PIUIO(), InputHandler_MacOSX_HID::~InputHandler_MacOSX_HID(), InputHandler_Win32_Pump::~InputHandler_Win32_Pump(), RageSoundDriver::~RageSoundDriver(), RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software(), RageSoundDriver_DSound_Software::~RageSoundDriver_DSound_Software(), RageSoundDriver_OSS::~RageSoundDriver_OSS(), RageSoundDriver_WaveOut::~RageSoundDriver_WaveOut(), RageSoundDriver_WDMKS::~RageSoundDriver_WDMKS(), RageSoundReader_ThreadedBuffer::~RageSoundReader_ThreadedBuffer(), and ~RageThread().
Member Data Documentation
m_pSlot
ThreadSlot* RageThread::m_pSlot private
Referenced by Create(), Halt(), IsCreated(), Resume(), Wait(), and ~RageThread().
m_sName
RString RageThread::m_sName private
Referenced by Create(), GetName(), and SetName().
s_bIsShowingDialog
bool RageThread::s_bIsShowingDialog = false static private
Referenced by GetIsShowingDialog(), and SetIsShowingDialog().
s_bSystemSupportsTLS
bool RageThread::s_bSystemSupportsTLS = false static private
Referenced by GetSupportsTLS(), and SetSupportsTLS().
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp