Etterna: NoteTypes.h File Reference
NoteTypes.h File Reference
#include "GameConstantsAndTypes.h"
#include "PlayerNumber.h"
#include "RageLog.h"
Classes
struct TapNoteResult
The result of hitting (or missing) a tap note.
struct HoldNoteResult
The result of holding (or letting go of) a hold note.
struct TapNote
The various properties of a tap note.
struct HoldReplayResult
struct TapReplayResult
Macros
#define COMPARE(x)
Enumerations
enum TapNoteType {
TapNoteType_Empty, TapNoteType_Tap, TapNoteType_HoldHead, TapNoteType_HoldTail,
TapNoteType_Mine, TapNoteType_Lift, TapNoteType_AutoKeysound, TapNoteType_Fake,
NUM_TapNoteType, TapNoteType_Invalid
}
What is the TapNote's core type?
enum TapNoteSubType { TapNoteSubType_Hold, TapNoteSubType_Roll, NUM_TapNoteSubType, TapNoteSubType_Invalid }
The list of a TapNote's sub types.
enum TapNoteSource { TapNoteSource_Original, TapNoteSource_Addition, NUM_TapNoteSource, TapNoteSource_Invalid }
The different places a TapNote could come from.
enum NoteType {
NOTE_TYPE_4TH, NOTE_TYPE_8TH, NOTE_TYPE_12TH, NOTE_TYPE_16TH,
NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_64TH,
NOTE_TYPE_192ND, NUM_NoteType, NoteType_Invalid
}
The list of quantized note types allowed at present.
Functions
const RString & TapNoteTypeToString (TapNoteType tnt)
const RString & TapNoteTypeToLocalizedString (TapNoteType tnt)
LuaDeclareType (TapNoteType)
const RString & TapNoteSubTypeToString (TapNoteSubType tnst)
const RString & TapNoteSubTypeToLocalizedString (TapNoteSubType tnst)
LuaDeclareType (TapNoteSubType)
const RString & TapNoteSourceToString (TapNoteSource tns)
const RString & TapNoteSourceToLocalizedString (TapNoteSource tns)
LuaDeclareType (TapNoteSource)
const RString & NoteTypeToString (NoteType nt)
const RString & NoteTypeToLocalizedString (NoteType nt)
LuaDeclareType (NoteType)
float NoteTypeToBeat (NoteType nt)
Convert the NoteType to a beat representation.
int NoteTypeToRow (NoteType nt)
NoteType GetNoteType (int row)
Retrieve the proper quantized NoteType for the note.
NoteType BeatToNoteType (float fBeat)
bool IsNoteOfType (int row, NoteType t)
Determine if the row has a particular type of quantized note.
int BeatToNoteRow (float fBeatNum)
Convert the beat into a note row.
float NoteRowToBeat (int iRow)
Convert the note row to a beat.
static int ToNoteRow (int row)
Convert the note row to note row (returns itself).
static int ToNoteRow (float beat)
Convert the beat to note row.
static float ToBeat (int row)
Convert the note row to beat.
static float ToBeat (float beat)
Convert the beat row to beat (return itself).
template<typename T >
T ScalePosition (T start, T length, T newLength, T position)
Scales the position.
Variables
TapNote TAP_EMPTY
TapNote TAP_ORIGINAL_TAP
TapNote TAP_ORIGINAL_HOLD_HEAD
TapNote TAP_ORIGINAL_ROLL_HEAD
TapNote TAP_ORIGINAL_MINE
TapNote TAP_ORIGINAL_LIFT
TapNote TAP_ORIGINAL_ATTACK
TapNote TAP_ORIGINAL_AUTO_KEYSOUND
TapNote TAP_ORIGINAL_FAKE
TapNote TAP_ADDITION_TAP
TapNote TAP_ADDITION_MINE
const int MAX_NOTE_TRACKS = 16
The number of tracks allowed.
const int ROWS_PER_BEAT = 48
The number of rows per beat.
const int MAX_NOTE_ROW = (1 << 30)
The max number of rows allowed for a Steps pattern.
Detailed Description
Author
Chris Danford, Glenn Maynard (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if (x != other.x)                                                          \
    return false
Referenced by TapNote::operator==().
Enumeration Type Documentation
NoteType
enum NoteType
The list of quantized note types allowed at present.
Enumerator
NOTE_TYPE_4TH
quarter note
NOTE_TYPE_8TH
eighth note
NOTE_TYPE_12TH
quarter note triplet
NOTE_TYPE_16TH
sixteenth note
NOTE_TYPE_24TH
eighth note triplet
NOTE_TYPE_32ND
thirty-second note
NOTE_TYPE_48TH
sixteenth note triplet
NOTE_TYPE_64TH
sixty-fourth note
NOTE_TYPE_192ND
sixty-fourth note triplet
NUM_NoteType
NoteType_Invalid
TapNoteSource
enum TapNoteSource
The different places a TapNote could come from.
Enumerator
TapNoteSource_Original
This note is part of the original NoteData.
TapNoteSource_Addition
This note is additional note added by a transform.
NUM_TapNoteSource
TapNoteSource_Invalid
TapNoteSubType
enum TapNoteSubType
The list of a TapNote's sub types.
Enumerator
TapNoteSubType_Hold
The start of a traditional hold note.
TapNoteSubType_Roll
The start of a roll note that must be hit repeatedly.
NUM_TapNoteSubType
TapNoteSubType_Invalid
TapNoteType
enum TapNoteType
What is the TapNote's core type?
Enumerator
TapNoteType_Empty
There is no note here.
TapNoteType_Tap
The player simply steps on this.
TapNoteType_HoldHead
This is graded like the Tap type, but should be held.
TapNoteType_HoldTail
In 2sand3s mode, holds are deleted and hold_tail is added.
TapNoteType_Mine
In most modes, it is suggested to not step on these mines.
TapNoteType_Lift
Lift your foot up when it crosses the target area.
TapNoteType_AutoKeysound
A special sound is played when this note crosses the target area.
TapNoteType_Fake
This arrow can't be scored for or against the player.
NUM_TapNoteType
TapNoteType_Invalid
Function Documentation
BeatToNoteRow()
int BeatToNoteRow (float fBeatNum) inline
Convert the beat into a note row.
Parameters
fBeatNum the beat to convert.
Returns
the note row.
References ROWS_PER_BEAT.
Referenced by NoteDataUtil::AddMines(), BeatToNoteType(), NoteDataUtil::Big(), NoteDataUtil::ConvertTapsToHolds(), Deserialize(), Player::DoTapScoreNone(), NoteField::DrawPrimitives(), NoteDataUtil::Echo(), FindEvent(), TimingData::GetBPMAtBeat(), TimingData::GetComboAtBeat(), TimingData::GetDelayAtBeat(), TimingData::GetFakeAtBeat(), TimingData::GetLabelAtBeat(), TimingData::GetMissComboAtBeat(), TimingData::GetNextSegmentBeatAtBeat(), TimeSignatureSegment::GetNoteRowsPerMeasure(), TimingData::GetPreviousSegmentBeatAtBeat(), TimingData::GetScrollAtBeat(), TimingData::GetSegmentAtBeat(), TimingData::GetSegmentIndexAtBeat(), TimingData::GetSpeedModeAtBeat(), TimingData::GetSpeedPercentAtBeat(), TimingData::GetSpeedWaitAtBeat(), TimingData::GetStopAtBeat(), TimingData::GetTickcountAtBeat(), TimingData::GetWarpAtBeat(), ArrowEffects::GetYOffset(), HandleBunki(), TimingData::IsFakeAtBeat(), TimingData::IsJudgableAtBeat(), TimingData::IsWarpAtBeat(), Player::Load(), DWILoader::LoadFromDir(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), BackgroundImpl::LoadFromRandom(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::LoadOverlapped(), ParseNoteData(), GameplayAssist::PlayTicks(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessBPMs(), SMLoader::ProcessBPMsAndStops(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SSCLoader::ProcessLabels(), SMALoader::ProcessMultipliers(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SMLoader::ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), SSCLoader::ProcessWarps(), NoteDataUtil::Quick(), BMSChartReader::ReadNoteData(), Player::ScoreAllActiveHoldsLetGo(), ScreenGameplay::SendCrossedMessages(), TimingSegment::SetBeat(), TimingData::SetBPMAtBeat(), TimingData::SetDelayAtBeat(), TimingData::SetLabelAtBeat(), TimingData::SetScrollAtBeat(), TimingData::SetSpeedAtBeat(), TimingData::SetSpeedModeAtBeat(), TimingData::SetSpeedPercentAtBeat(), TimingData::SetSpeedWaitAtBeat(), TimingData::SetStopAtBeat(), TimingData::SetTickcountAtBeat(), TimingData::SetTimeSignatureAtBeat(), TimingData::SetWarpAtBeat(), NoteDataUtil::Skippy(), NoteDataUtil::SnapToNearestNoteType(), ScreenHowToPlay::Step(), Player::Step(), NoteDataUtil::Stomp(), ToNoteRow(), ScreenHowToPlay::Update(), GameSoundManager::Update(), SoundEffectControl::Update(), BeginnerHelper::Update(), Player::Update(), Player::UpdateJudgedRows(), Player::UpdateTapNotesMissedOlderThan(), TimingData::WhereUAtBro(), TimingData::WhereUAtBroNoOffset(), NoteDataUtil::Wide(), and WriteDWINotesField().
BeatToNoteType()
NoteType BeatToNoteType (float fBeat)
References BeatToNoteRow(), and GetNoteType().
Referenced by NoteDisplay::DrawActor(), NoteDisplay::GetHoldSprite(), and NoteDisplay::GetTapActor().
GetNoteType()
NoteType GetNoteType (int row)
Retrieve the proper quantized NoteType for the note.
Parameters
row The row to check for.
Returns
the quantized NoteType.
References NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, and ROWS_PER_MEASURE.
Referenced by BeatToNoteType(), IsNoteOfType(), ScreenGameplay::SendCrossedMessages(), and Player::Step().
IsNoteOfType()
bool IsNoteOfType (int row, NoteType t)
Determine if the row has a particular type of quantized note.
Parameters
row the row in the Steps.
t the quantized NoteType to check for.
Returns
true if the NoteType is t, false otherwise.
References GetNoteType().
LuaDeclareType() [1/4]
LuaDeclareType (TapNoteType)
LuaDeclareType() [2/4]
LuaDeclareType (TapNoteSubType)
LuaDeclareType() [3/4]
LuaDeclareType (TapNoteSource)
LuaDeclareType() [4/4]
LuaDeclareType (NoteType)
NoteRowToBeat()
float NoteRowToBeat (int iRow) inline
Convert the note row to a beat.
Parameters
iRow the row to convert.
Returns
the beat.
References ROWS_PER_BEAT.
Referenced by BMSSongLoader::AddToSong(), TimingData::BuildAndGetEtaner(), TimingData::BuildAndGetEtar(), NoteField::DrawAreaHighlight(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldsInRange(), NoteField::DrawMarkerBar(), NoteField::DrawPrimitives(), NoteDisplay::DrawTapsInRange(), GenerateCacheDataStructure(), TimingSegment::GetBeat(), TimingData::GetBeatInternal(), TimingData::GetElapsedTimeInternal(), NoteData::GetFirstBeat(), LunaTapNote::GetHoldDuration(), NoteData::GetLastBeat(), HoldNoteResult::GetLastHeldBeat(), TimingData::GetNextSegmentBeatAtRow(), TimingData::GetPreviousSegmentBeatAtRow(), SongCacheIndex::InsertStepsTimingData(), TimingData::IsFakeAtRow(), TimingData::IsWarpAtRow(), AutoKeysounds::LoadAutoplaySoundsInto(), DWILoader::LoadFromDir(), BackgroundImpl::LoadFromRandom(), LoadFromSMNoteDataStringWithPlayer(), NoteRowToVisibleBeat(), GameplayAssist::PlayTicks(), TimingData::PrepareLookup(), FakeSegment::Scale(), WarpSegment::Scale(), SpeedSegment::Scale(), Serialize(), Player::Step(), ToBeat(), TimingData::WhereUAtBro(), NoteDataUtil::Wide(), TimingTagWriter::Write(), and WriteGlobalTags().
NoteTypeToBeat()
float NoteTypeToBeat (NoteType nt)
Convert the NoteType to a beat representation.
Parameters
nt the NoteType to check.
Returns
the proper beat.
References FAIL_M, NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, NoteType_Invalid, and ssprintf().
Referenced by NoteDataUtil::GetETTNoteDataString(), NoteDataUtil::GetSmallestNoteTypeInRange(), NoteDataUtil::GetSMNoteDataString(), and NoteDataUtil::SnapToNearestNoteType().
NoteTypeToLocalizedString()
const RString& NoteTypeToLocalizedString (NoteType nt)
NoteTypeToRow()
int NoteTypeToRow (NoteType nt)
References FAIL_M, NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, and NoteType_Invalid.
NoteTypeToString()
const RString& NoteTypeToString (NoteType nt)
Referenced by NoteDisplay::GetHoldSprite(), NoteDisplay::GetTapActor(), and Player::Step().
ScalePosition()
template<typename T > T ScalePosition (T start, T length, T newLength, T position) inline
Scales the position.
Parameters
T start - the starting row of the scaling region
T length - the length of the scaling region
T newLength - the new length of the scaling region
T position - the position to scale
Returns
T the scaled position
Referenced by TimingSegment::Scale(), FakeSegment::Scale(), WarpSegment::Scale(), and SpeedSegment::Scale().
TapNoteSourceToLocalizedString()
const RString& TapNoteSourceToLocalizedString (TapNoteSource tns)
TapNoteSourceToString()
const RString& TapNoteSourceToString (TapNoteSource tns)
TapNoteSubTypeToLocalizedString()
const RString& TapNoteSubTypeToLocalizedString (TapNoteSubType tnst)
TapNoteSubTypeToString()
const RString& TapNoteSubTypeToString (TapNoteSubType tnst)
TapNoteTypeToLocalizedString()
const RString& TapNoteTypeToLocalizedString (TapNoteType tnt)
TapNoteTypeToString()
const RString& TapNoteTypeToString (TapNoteType tnt)
Referenced by TapNote::TapNote().
ToBeat() [1/2]
static float ToBeat (int row) inline static
Convert the note row to beat.
Parameters
row the row to convert.
References NoteRowToBeat().
Referenced by FakeSegment::GetLengthBeats(), and WarpSegment::GetLengthBeats().
ToBeat() [2/2]
static float ToBeat (float beat) inline static
Convert the beat row to beat (return itself).
Parameters
beat the beat to convert.
ToNoteRow() [1/2]
static int ToNoteRow (int row) inline static
Convert the note row to note row (returns itself).
Parameters
row the row to convert.
Referenced by FakeSegment::SetLength(), and WarpSegment::SetLength().
ToNoteRow() [2/2]
static int ToNoteRow (float beat) inline static
Convert the beat to note row.
Parameters
beat the beat to convert.
References BeatToNoteRow().
Variable Documentation
MAX_NOTE_ROW
const int MAX_NOTE_ROW = (1 << 30)
The max number of rows allowed for a Steps pattern.
Referenced by NoteDataUtil::CalculateRadarValues(), NoteDataUtil::ClearLeft(), NoteData::ClearRangeForTrack(), NoteDataUtil::ClearRight(), NoteDataUtil::DeleteRows(), GenerateCacheDataStructure(), NoteDataWithScoring::GetActualRadarValues(), NoteData::GetLastRow(), NoteDataUtil::GetNextEditorPosition(), NoteData::GetNextTapNoteRowForAllTracks(), NoteDataUtil::GetPrevEditorPosition(), NoteData::GetPrevTapNoteRowForAllTracks(), NoteData::GetTapNoteRange(), NoteDataUtil::InsertRows(), Player::Load(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::LoadOverlapped(), Serialize(), and Player::Step().
MAX_NOTE_TRACKS
const int MAX_NOTE_TRACKS = 16
The number of tracks allowed.
TODO: Don't have a hard-coded track limit.
Referenced by GetTrackMapping(), NoteDataUtil::LoadOverlapped(), NoteDataUtil::ShiftTracks(), NoteDataUtil::Stomp(), NoteDataUtil::SwapSides(), NoteDataUtil::SwapUpDown(), and NoteDataUtil::Turn().
ROWS_PER_BEAT
const int ROWS_PER_BEAT = 48
The number of rows per beat.
This is a divisor for our "fixed-point" time/beat representation. It must be evenly divisible by 2, 3, and 4, to exactly represent 8th, 12th and 16th notes.
XXX: Some other forks try to keep this flexible by putting this in the simfile. Is this a recommended course of action? -Wolfman2000
Referenced by BeatToNoteRow(), Player::CrossedRows(), NoteDataUtil::GetETTNoteDataString(), NoteDataUtil::GetSmallestNoteTypeInRange(), NoteDataUtil::GetSMNoteDataString(), NoteDataUtil::GetTotalHoldTicks(), NoteDataUtil::Little(), LoadFromKSFFile(), NoteRowToBeat(), SMLoader::ProcessTickcounts(), ProcessTickcounts(), Player::Step(), GameSoundManager::Update(), NoteDataUtil::Wide(), and NotesWriterDWI::Write().
TAP_ADDITION_MINE
TapNote TAP_ADDITION_MINE
Referenced by NoteDataUtil::AddMines().
TAP_ADDITION_TAP
TapNote TAP_ADDITION_TAP
Referenced by NoteDataUtil::AnchorJS(), NoteDataUtil::Echo(), NoteDataUtil::IcyWorld(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::JackJS(), NoteDataUtil::Stomp(), and NoteDataUtil::Wide().
TAP_EMPTY
TapNote TAP_EMPTY
Referenced by NoteData::AddHoldNote(), NoteData::ClearRangeForTrack(), NoteDataUtil::CollapseLeft(), Player::DoTapScoreNone(), GenerateCacheDataStructure(), NoteData::GetTapNote(), Player::HandleHoldCheckpoint(), NoteDataWithScoring::LastTapNoteWithResult(), NoteDataUtil::Little(), AutoKeysounds::LoadAutoplaySoundsInto(), LoadFromKSFFile(), NotesToDWIString(), ParseNoteData(), PlaceAutoKeysound(), BMSChartReader::ReadNoteData(), NoteDataUtil::RemoveFakes(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), NoteData::SetTapNote(), NoteDataUtil::SnapToNearestNoteType(), and WriteDWINotesField().
TAP_ORIGINAL_ATTACK
TapNote TAP_ORIGINAL_ATTACK
TAP_ORIGINAL_AUTO_KEYSOUND
TapNote TAP_ORIGINAL_AUTO_KEYSOUND
Referenced by LoadFromSMNoteDataStringWithPlayer(), and BMSChartReader::ReadNoteData().
TAP_ORIGINAL_FAKE
TapNote TAP_ORIGINAL_FAKE
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_HOLD_HEAD
TapNote TAP_ORIGINAL_HOLD_HEAD
Referenced by NoteDataUtil::ConvertTapsToHolds(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), OsuLoader::LoadNoteDataFromParsedData(), and ParseNoteData().
TAP_ORIGINAL_LIFT
TapNote TAP_ORIGINAL_LIFT
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), and OsuLoader::LoadNoteDataFromParsedData().
TAP_ORIGINAL_MINE
TapNote TAP_ORIGINAL_MINE
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_ROLL_HEAD
TapNote TAP_ORIGINAL_ROLL_HEAD
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), and LoadFromSMNoteDataStringWithPlayer().
TAP_ORIGINAL_TAP
TapNote TAP_ORIGINAL_TAP
Referenced by NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), OsuLoader::LoadNoteDataFromParsedData(), ParseNoteData(), and BMSChartReader::ReadNoteData().