Etterna: RageFileDriverDirectHelpers.cpp File Reference
RageFileDriverDirectHelpers.cpp File Reference
#include "global.h"
#include "RageFileDriverDirectHelpers.h"
#include "Foreach.h"
#include "RageUtil.h"
#include <cerrno>
#include <sys/stat.h>
Functions
RString DoPathReplace (const RString &sPath)
bool CreateDirectories (const RString &Path)
Function Documentation
CreateDirectories()
bool CreateDirectories (const RString & Path)
References DoMkdir, DoStat, StdString::CStdStr< CT >::Left(), split(), ssprintf(), and WARN.
Referenced by RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), and RageFileDriverDirect::Remount().
DoPathReplace()
RString DoPathReplace (const RString & sPath)
Referenced by RageFileObjDirect::~RageFileObjDirect().