Etterna: DateTime.h File Reference
DateTime.h File Reference
#include "EnumHelper.h"
#include <ctime>
Classes
struct DateTime
A standard way of determining the date and the time.
Enumerations
enum Month { NUM_Month = 12, Month_Invalid }
Which month are we focusing on?
Functions
int StringToDayInYear (const RString &sDayInYear)
RString DayInYearToString (int iDayInYearIndex)
RString LastDayToString (int iLastDayIndex)
RString LastDayToLocalizedString (int iLastDayIndex)
RString DayOfWeekToString (int iDayOfWeekIndex)
RString DayOfWeekToLocalizedString (int iDayOfWeekIndex)
RString HourInDayToString (int iHourIndex)
RString HourInDayToLocalizedString (int iHourIndex)
const RString & MonthToString (Month month)
const RString & MonthToLocalizedString (Month month)
RString LastWeekToString (int iLastWeekIndex)
RString LastWeekToLocalizedString (int iLastWeekIndex)
LuaDeclareType (Month)
tm AddDays (tm start, int iDaysToMove)
tm GetYesterday (tm start)
int GetDayOfWeek (tm time)
tm GetNextSunday (tm start)
tm GetDayInYearAndYear (int iDayInYearIndex, int iYear)
Variables
const int NUM_LAST_DAYS = 7
The number of days we check for previously.
const int NUM_LAST_WEEKS = 52
The number of weeks we check for previously.
const int DAYS_IN_YEAR = 366
The number of days that are in a year.
const int HOURS_IN_DAY = 24
The number of hours in a day.
const int DAYS_IN_WEEK = 7
The number of days that are in a week.
Detailed Description
Author
Chris Danford (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Enumeration Type Documentation
Month
enum Month
Which month are we focusing on?
Is there any reason why the actual months aren't defined in here? -Wolfman2000
Enumerator
NUM_Month
The number of months in the year.
Month_Invalid
There should be no month at this point.
Function Documentation
AddDays()
tm AddDays (tm start, int iDaysToMove)
Referenced by GetNextSunday(), and GetYesterday().
DayInYearToString()
RString DayInYearToString (int iDayInYearIndex)
References ssprintf().
DayOfWeekToLocalizedString()
RString DayOfWeekToLocalizedString (int iDayOfWeekIndex)
DayOfWeekToString()
RString DayOfWeekToString (int iDayOfWeekIndex)
References DAY_OF_WEEK_TO_NAME.
GetDayInYearAndYear()
tm GetDayInYearAndYear (int iDayInYearIndex, int iYear)
References ZERO.
GetDayOfWeek()
int GetDayOfWeek (tm time)
References ASSERT, and DAYS_IN_WEEK.
Referenced by GetNextSunday().
GetNextSunday()
tm GetNextSunday (tm start)
References AddDays(), DAYS_IN_WEEK, and GetDayOfWeek().
GetYesterday()
tm GetYesterday (tm start)
References AddDays().
HourInDayToLocalizedString()
RString HourInDayToLocalizedString (int iHourIndex)
References ssprintf(), and wrap().
HourInDayToString()
RString HourInDayToString (int iHourIndex)
References ssprintf().
LastDayToLocalizedString()
RString LastDayToLocalizedString (int iLastDayIndex)
References LastDayToString(), and StdString::CStdStr< CT >::Replace().
LastDayToString()
RString LastDayToString (int iLastDayIndex)
Referenced by LastDayToLocalizedString().
LastWeekToLocalizedString()
RString LastWeekToLocalizedString (int iLastWeekIndex)
References LastWeekToString(), and StdString::CStdStr< CT >::Replace().
LastWeekToString()
RString LastWeekToString (int iLastWeekIndex)
References ssprintf().
Referenced by LastWeekToLocalizedString().
LuaDeclareType()
LuaDeclareType (Month)
MonthToLocalizedString()
const RString& MonthToLocalizedString (Month month)
MonthToString()
const RString& MonthToString (Month month)
Referenced by ScreenSetTime::Update().
StringToDayInYear()
int StringToDayInYear (const RString & sDayInYear)
Variable Documentation
DAYS_IN_WEEK
const int DAYS_IN_WEEK = 7
The number of days that are in a week.
Referenced by GetDayOfWeek(), and GetNextSunday().
DAYS_IN_YEAR
const int DAYS_IN_YEAR = 366
The number of days that are in a year.
This is set up to be a maximum for leap years.
HOURS_IN_DAY
const int HOURS_IN_DAY = 24
The number of hours in a day.
NUM_LAST_DAYS
const int NUM_LAST_DAYS = 7
The number of days we check for previously.
NUM_LAST_WEEKS
const int NUM_LAST_WEEKS = 52
The number of weeks we check for previously.