Etterna: RageTimer Class Reference
RageTimer Class Reference
#include <RageTimer.h>
Public Member Functions
RageTimer ()
RageTimer (int secs, int us)
float Ago () const
void Touch ()
bool IsZero () const
void SetZero ()
float GetDeltaTime ()
float PeekDeltaTime () const
RageTimer Half () const
RageTimer operator+ (float tm) const
RageTimer operator- (float tm) const
void operator+= (float tm)
void operator-= (float tm)
float operator- (const RageTimer &rhs) const
bool operator< (const RageTimer &rhs) const
Static Public Member Functions
static float GetTimeSinceStart (bool bAccurate=true)
static float GetTimeSinceStartFast ()
static uint64_t GetUsecsSinceStart ()
Public Attributes
unsigned m_secs { 0 }
unsigned m_us { 0 }
Static Private Member Functions
static RageTimer Sum (const RageTimer &lhs, float tm)
static float Difference (const RageTimer &lhs, const RageTimer &rhs)
Constructor & Destructor Documentation
RageTimer() [1/2]
RageTimer::RageTimer () inline
References Touch().
RageTimer() [2/2]
RageTimer::RageTimer (int secs, int us) inline
Member Function Documentation
Ago()
float RageTimer::Ago () const
Referenced by ScreenSelectMusic::CheckBackgroundRequests(), RageSoundDriver::ClampHardwareFrame(), InputHandler_DInput::DevicesChanged(), RageSoundDriver::GetHardwareFrame(), Half(), ScreenGameplay::HandleScreenMessage(), ScreenSelectMusic::Input(), Profile::LoadAllFromDir(), RageSoundDriver::MixIntoBuffer(), PeekDeltaTime(), RageSound::StartPlaying(), Player::Step(), ScreenGameplay::Update(), GameState::UpdateSongPosition(), and ScreenDebugOverlay::UpdateText().
Difference()
float RageTimer::Difference (const RageTimer & lhs, const RageTimer & rhs) static private
References m_secs, m_us, and TIMESTAMP_RESOLUTION.
Referenced by GetDeltaTime(), and operator-().
GetDeltaTime()
float RageTimer::GetDeltaTime ()
References Difference().
Referenced by ScreenSelect::BeginScreen(), ScreenSelectMusic::BeginScreen(), GameState::CommitStageStats(), RageDisplay::FrameLimitBeforeVsync(), HandleGlobalInputs(), SongManager::InitSongsFromDisk(), ScreenSelect::Input(), ScreenSelectMusic::Input(), ScreenManager::MakeNewScreen(), ScreenReloadSongsLoadingWindow::Paint(), DirectFilenameDB::PopulateFileSet(), pos_map_queue::Search(), ScreenSelect::Update(), ScreenSelectMusic::Update(), WheelBase::Update(), ModsGroup< SongOptions >::Update(), and ScreenGameplay::Update().
GetTimeSinceStart()
float RageTimer::GetTimeSinceStart (bool bAccurate = true) static
References g_iStartTime, and GetTime().
Referenced by DebugLineUptime::GetDisplayValue(), RageSoundDriver_Null::GetPosition(), GetTimeSinceStartFast(), MusicWheel::readyWheelItemsData(), LockMutex::Unlock(), RageSoundDriver::Update(), and RageLog::Write().
GetTimeSinceStartFast()
static float RageTimer::GetTimeSinceStartFast () inline static
References GetTimeSinceStart().
Referenced by ArrowGetPercentVisible(), BitmapText::BuildChars(), NoteField::DrawPrimitives(), BitmapText::DrawPrimitives(), ArrowEffects::GetXPos(), ArrowEffects::Update(), WheelNotifyIcon::Update(), and BGAnimationLayer::UpdateInternal().
GetUsecsSinceStart()
uint64_t RageTimer::GetUsecsSinceStart () static
References g_iStartTime, and GetTime().
Referenced by Actor::UpdateInternal().
Half()
RageTimer RageTimer::Half () const
References Ago().
IsZero()
bool RageTimer::IsZero () const inline
References m_secs, and m_us.
Referenced by ScreenGameplay::AbortGiveUp(), ScreenGameplay::AbortSkipSong(), RageSoundDriver::ClampHardwareFrame(), RageWorkerThread::DoRequest(), RageDisplay::FrameLimitBeforeVsync(), ScreenMapControllers::Input(), ScreenGameplay::Input(), RageSoundDriver::MixIntoBuffer(), RageSound::StartPlaying(), RageWorkerThread::TimeoutEnabled(), ScreenMapControllers::Update(), ScreenGameplay::Update(), SongPosition::UpdateSongPosition(), and RageEvent::Wait().
operator+()
RageTimer RageTimer::operator+ (float tm) const
References Sum().
operator+=()
void RageTimer::operator+= (float tm) inline
operator-() [1/2]
RageTimer RageTimer::operator- (float tm) const inline
operator-() [2/2]
float RageTimer::operator- (const RageTimer & rhs) const
References Difference().
operator-=()
void RageTimer::operator-= (float tm) inline
operator<()
bool RageTimer::operator< (const RageTimer & rhs) const
References m_secs, and m_us.
PeekDeltaTime()
float RageTimer::PeekDeltaTime () const inline
References Ago().
Referenced by FilenameDB::GetFileSet(), ScreenReloadSongsLoadingWindow::Paint(), pos_map_queue::Search(), RageTextureManager::UnloadTexture(), ScreenSelect::Update(), RoomInfoDisplay::Update(), ScreenMapControllers::Update(), ScreenSelectMusic::Update(), WheelBase::Update(), RageTextureManager::Update(), and ScreenTextEntry::Update().
SetZero()
void RageTimer::SetZero () inline
References m_secs, and m_us.
Referenced by ScreenGameplay::AbortGiveUp(), ScreenGameplay::AbortSkipSong(), ScreenMapControllers::BeginScreen(), DancingCharacters::DancingCharacters(), GameState::GameState(), ScreenGameplay::Init(), RageSoundDriver::MixIntoBuffer(), RageWorkerThread::RageWorkerThread(), GameState::Reset(), RageWorkerThread::SetTimeout(), and ScreenMapControllers::Update().
Sum()
RageTimer RageTimer::Sum (const RageTimer & lhs, float tm) static private
References m_secs, m_us, and TIMESTAMP_RESOLUTION.
Referenced by operator+().
Touch()
void RageTimer::Touch ()
References GetTime(), m_secs, and m_us.
Referenced by ScreenSelectMusic::AfterMusicChange(), GameState::BeginGame(), ScreenSelectMusic::BeginScreen(), RageSoundReader_ThreadedBuffer::BufferingThread(), RageSoundDriver::ClampHardwareFrame(), InputHandler_DInput::DevicesChanged(), DebugLineHalt::DoAndLog(), RageDisplay::FrameLimitAfterVsync(), FilenameDB::GetFileSet(), RageSoundDriver::GetHardwareFrame(), ScreenGameplay::HandleScreenMessage(), ScreenSelectMusic::Init(), ScreenSelectMusic::Input(), ScreenGameplay::Input(), Profile::LoadAllFromDir(), RageTextureManager::LoadTexture(), RageTimer(), ScoreManager::RecalculateSSRs(), GameState::ResetMusicStatistics(), RageDisplay::SaveScreenshot(), RageWorkerThread::SetHeartbeat(), RoomInfoDisplay::SetRoomInfo(), RageWorkerThread::SetTimeout(), ScreenMapControllers::StartWaitingForPress(), RageTextureManager::Update(), ScreenTextEntry::Update(), SongPosition::UpdateSongPosition(), GameState::UpdateSongPosition(), ScreenDebugOverlay::UpdateText(), RageWorkerThread::WorkerMain(), and FontPage::~FontPage().
Member Data Documentation
m_secs
unsigned RageTimer::m_secs { 0 }
Referenced by Difference(), IsZero(), operator<(), SetZero(), Sum(), and Touch().
m_us
unsigned RageTimer::m_us { 0 }
Referenced by Difference(), IsZero(), operator<(), SetZero(), Sum(), and Touch().
The documentation for this class was generated from the following files:
RageTimer.h
RageTimer.cpp