Etterna: LunaScreenSelectProfile Class Reference
LunaScreenSelectProfile Class Reference
Allow Lua to have access to the ScreenSelectProfile.
Public Member Functions
LunaScreenSelectProfile ()
Public Member Functions inherited from Luna< ScreenSelectProfile >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetProfileIndex (T *p, lua_State *L)
static int GetProfileIndex (T *p, lua_State *L)
static int Finish (T *p, lua_State *L)
static int Cancel (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScreenSelectProfile >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScreenSelectProfile >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenSelectProfile >
using T = ScreenSelectProfile
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenSelectProfile >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ScreenSelectProfile.
Constructor & Destructor Documentation
LunaScreenSelectProfile()
LunaScreenSelectProfile::LunaScreenSelectProfile () inline
References ADD_METHOD, Cancel(), Finish(), GetProfileIndex(), and SetProfileIndex().
Member Function Documentation
Cancel()
static int LunaScreenSelectProfile::Cancel (T * p, lua_State * L) inline static
References ScreenWithMenuElements::Cancel(), and SM_GoToPrevScreen.
Referenced by LunaScreenSelectProfile().
Finish()
static int LunaScreenSelectProfile::Finish (T * p, lua_State * L) inline static
References ScreenSelectProfile::Finish(), and LuaHelpers::Push().
Referenced by LunaScreenSelectProfile().
GetProfileIndex()
static int LunaScreenSelectProfile::GetProfileIndex (T * p, lua_State * L) inline static
References ScreenSelectProfile::GetProfileIndex(), L, and LuaHelpers::Push().
Referenced by LunaScreenSelectProfile().
SetProfileIndex()
static int LunaScreenSelectProfile::SetProfileIndex (T * p, lua_State * L) inline static
References IArg, L, LuaHelpers::Push(), and ScreenSelectProfile::SetProfileIndex().
Referenced by LunaScreenSelectProfile().
The documentation for this class was generated from the following file:
ScreenSelectProfile.cpp