Etterna: RageUtil.h File Reference
RageUtil.h File Reference
#include "global.h"
#include <map>
#include <random>
#include <sstream>
#include <vector>
Classes
struct ConvertValueHelper< TO, FROM >
struct LanguageInfo
class Regex
struct char_traits_char_nocase
Namespaces
StringConversion
Utilities for converting the RStrings.
Macros
#define SAFE_DELETE(p)
Safely delete pointers.
#define SAFE_DELETE_ARRAY(p)
Safely delete array pointers.
#define ZERO(x) memset(&(x), 0, sizeof(x))
Zero out the memory.
#define COPY(a, b)
Copy from a to b.
#define ARRAYLEN(a) (sizeof(a) / sizeof((a)[0]))
Get the length of the array.
#define clamp(val, low, high) (max((low), min((val), (high))))
If outside the range from low to high, bring it within range.
#define SCALE(x, l1, h1, l2, h2) (((x) - (l1)) * ((h2) - (l2)) / ((h1) - (l1)) + (l2))
Scales x so that l1 corresponds to l2 and h1 corresponds to h2.
Typedefs
typedef std::mt19937 RandomGen
typedef basic_string< char, char_traits_char_nocase > istring
Functions
float min (float a, int b)
float min (int a, float b)
float max (float a, int b)
float max (int a, float b)
unsigned long min (unsigned int a, unsigned long b)
unsigned long min (unsigned long a, unsigned int b)
unsigned long max (unsigned int a, unsigned long b)
unsigned long max (unsigned long a, unsigned int b)
template<typename T , typename U >
U lerp (T x, U l, U h)
template<typename T , typename U , typename V >
bool CLAMP (T &x, U l, V h)
template<class T >
bool ENUM_CLAMP (T &x, T l, T h)
float wife2 (float maxms, float ts)
void wrap (int &x, int n)
void wrap (unsigned &x, unsigned n)
void wrap (float &x, float n)
float fracf (float f)
template<class T >
void CircularShift (vector< T > &v, int dist)
template<typename Type , typename Ret >
static Ret * CreateClass ()
template<typename Container , typename Predicate >
void RemoveIf (Container &c, Predicate p)
template<typename Container , typename Value >
void RemoveIfEqual (Container &c, const Value &v)
template<typename TO , typename FROM >
ConvertValueHelper< TO, FROM > ConvertValue (FROM *pValue)
template<typename T >
static void enum_add (T &val, int iAmt)
template<typename T >
static T enum_add2 (T val, int iAmt)
template<typename T >
static T enum_cycle (T val, int iMax, int iAmt=1)
uint32_t Swap32 (uint32_t n)
uint32_t Swap24 (uint32_t n)
uint16_t Swap16 (uint16_t n)
uint32_t Swap32BE (uint32_t n)
uint32_t Swap24BE (uint32_t n)
uint16_t Swap16BE (uint16_t n)
uint32_t Swap32LE (uint32_t n)
uint32_t Swap24LE (uint32_t n)
uint16_t Swap16LE (uint16_t n)
void seed_lua_prng ()
int random_up_to (RandomGen &rng, int limit)
int random_up_to (int limit)
float RandomFloat ()
Generate a random float between 0 inclusive and 1 exclusive.
float RandomFloat (float fLow, float fHigh)
Return a float between the low and high values.
int RandomInt (int low, int high)
int RandomInt (int n)
float randomf (const float low=-1.0f, const float high=1.0f)
float Quantize (const float f, const float fRoundInterval)
int Quantize (const int i, const int iRoundInterval)
float ftruncf (const float f, const float fTruncInterval)
int QuantizeUp (int i, int iInterval)
float QuantizeUp (float i, float iInterval)
int QuantizeDown (int i, int iInterval)
float QuantizeDown (float i, float iInterval)
void fapproach (float &val, float other_val, float to_move)
float fmodfp (float x, float y)
int power_of_two (int input)
bool IsAnInt (const RString &s)
bool IsHexVal (const RString &s)
RString BinaryToHex (const void *pData_, int iNumBytes)
RString BinaryToHex (const RString &sString)
bool HexToBinary (const RString &s, unsigned char *stringOut)
bool HexToBinary (const RString &s, RString *sOut)
float HHMMSSToSeconds (const RString &sHMS)
RString SecondsToHHMMSS (float fSecs)
RString SecondsToMSSMsMs (float fSecs)
RString SecondsToMMSSMsMs (float fSecs)
RString SecondsToMMSSMsMsMs (float fSecs)
RString SecondsToMSS (float fSecs)
RString SecondsToMMSS (float fSecs)
RString PrettyPercent (float fNumerator, float fDenominator)
RString PrettyPercent (int fNumerator, int fDenominator)
RString Commify (int iNum)
RString Commify (const RString &num, const RString &sep=",", const RString &dot=".")
RString FormatNumberAndSuffix (int i)
struct tm GetLocalTime ()
RString ssprintf (const char *fmt,...) PRINTF(1
RString RString vssprintf (const char *fmt, va_list argList)
RString ConvertI64FormatString (const RString &sStr)
void splitpath (const RString &Path, RString &Dir, RString &Filename, RString &Ext)
RString SetExtension (const RString &path, const RString &ext)
RString GetExtension (const RString &sPath)
RString GetFileNameWithoutExtension (const RString &sPath)
void MakeValidFilename (RString &sName)
bool FindFirstFilenameContaining (const vector< RString > &filenames, RString &out, const vector< RString > &starts_with, const vector< RString > &contains, const vector< RString > &ends_with)
int utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
bool utf8_to_wchar (const char *s, size_t iLength, unsigned &start, wchar_t &ch)
Decode a code point and place within the output variable.
bool utf8_to_wchar_ec (const RString &s, unsigned &start, wchar_t &ch)
void wchar_to_utf8 (wchar_t ch, RString &out)
wchar_t utf8_get_char (const RString &s)
bool utf8_is_valid (const RString &s)
void utf8_remove_bom (RString &s)
void MakeUpper (char *p, size_t iLen)
void MakeLower (char *p, size_t iLen)
void MakeUpper (wchar_t *p, size_t iLen)
void MakeLower (wchar_t *p, size_t iLen)
int StringToInt (const RString &sString)
Have a standard way of converting Strings to integers.
RString IntToString (const int &iNum)
Have a standard way of converting integers to Strings.
float StringToFloat (const RString &sString)
RString FloatToString (const float &num)
bool StringToFloat (const RString &sString, float &fOut)
template<class T >
bool operator>> (const RString &lhs, T &rhs)
RString WStringToRString (const wstring &sString)
RString WcharToUTF8 (wchar_t c)
wstring RStringToWstring (const RString &sString)
void GetLanguageInfos (vector< const LanguageInfo *> &vAddTo)
const LanguageInfo * GetLanguageInfo (const RString &sIsoCode)
RString GetLanguageNameFromISO639Code (const RString &sName)
void split (const RString &sSource, const RString &sDelimitor, vector< RString > &asAddIt, const bool bIgnoreEmpty=true)
void split (const wstring &sSource, const wstring &sDelimitor, vector< wstring > &asAddIt, const bool bIgnoreEmpty=true)
void split (const RString &sSource, const RString &sDelimitor, int &iBegin, int &iSize, bool bIgnoreEmpty=true)
void split (const wstring &sSource, const wstring &sDelimitor, int &iBegin, int &iSize, bool bIgnoreEmpty=true)
void split (const RString &sSource, const RString &sDelimitor, int &iBegin, int &iSize, int iLen, bool bIgnoreEmpty)
void split (const wstring &sSource, const wstring &sDelimitor, int &iBegin, int &iSize, int iLen, bool bIgnoreEmpty)
RString join (const RString &sDelimitor, const vector< RString > &sSource)
RString join (const RString &sDelimitor, vector< RString >::const_iterator begin, vector< RString >::const_iterator end)
std::string luajoin (const std::string &sDelimitor, const vector< std::string > &sSource)
std::string luajoin (const std::string &sDelimitor, vector< std::string >::const_iterator begin, vector< std::string >::const_iterator end)
RString SmEscape (const RString &sUnescaped)
RString SmEscape (const char *cUnescaped, int len)
RString DwiEscape (const RString &sUnescaped)
RString DwiEscape (const char *cUnescaped, int len)
RString GetCwd ()
void SetCommandlineArguments (int argc, char **argv)
void GetCommandLineArguments (int &argc, char **&argv)
bool GetCommandlineArgument (const RString &option, RString *argument=nullptr, int iIndex=0)
void CRC32 (unsigned int &iCRC, const void *pBuffer, size_t iSize)
unsigned int GetHashForString (const RString &s)
unsigned int GetHashForFile (const RString &sPath)
unsigned int GetHashForDirectory (const RString &sDir)
bool DirectoryIsEmpty (const RString &sPath)
bool CompareRStringsAsc (const RString &sStr1, const RString &sStr2)
bool CompareRStringsDesc (const RString &sStr1, const RString &sStr2)
void SortRStringArray (vector< RString > &asAddTo, const bool bSortAscending=true)
float calc_mean (const float *pStart, const float *pEnd)
float calc_stddev (const float *pStart, const float *pEnd, bool bSample=false)
bool CalcLeastSquares (const vector< pair< float, float >> &vCoordinates, float &fSlope, float &fIntercept, float &fError)
void FilterHighErrorPoints (vector< pair< float, float >> &vCoordinates, float fSlope, float fIntercept, float fCutoff)
template<class T1 , class T2 >
int FindIndex (T1 begin, T1 end, const T2 *p)
template<class T >
T Increment (T a)
template<class T >
T Decrement (T a)
void TrimLeft (RString &sStr, const char *szTrim="\\")
void TrimRight (RString &sStr, const char *szTrim="\\")
void Trim (RString &sStr, const char *szTrim="\\")
void StripCrnl (RString &sStr)
bool BeginsWith (const RString &sTestThis, const RString &sBeginning)
bool EndsWith (const RString &sTestThis, const RString &sEnding)
RString URLEncode (const RString &sStr)
void StripCvsAndSvn (vector< RString > &vs)
void StripMacResourceForks (vector< RString > &vs)
RString DerefRedir (const RString &sPath)
bool GetFileContents (const RString &sPath, RString &sOut, bool bOneLine=false)
bool GetFileContents (const RString &sFile, vector< RString > &asOut)
bool GetFileContents (const std::string &sPath, std::string &sOut, bool bOneLine=false)
bool GetFileContents (const std::string &sFile, vector< std::string > &asOut)
void ReplaceEntityText (RString &sText, const map< RString, RString > &m)
void ReplaceEntityText (RString &sText, const map< char, RString > &m)
void Replace_Unicode_Markers (RString &Text)
RString WcharDisplayText (wchar_t c)
RString Basename (const RString &dir)
RString Dirname (const RString &dir)
RString Capitalize (const RString &s)
void GetDirListing (const RString &sPath, vector< RString > &AddTo, bool bOnlyDirs=false, bool bReturnPathToo=false)
void GetDirListingRecursive (const RString &sDir, const RString &sMatch, vector< RString > &AddTo)
void GetDirListingRecursive (RageFileDriver *prfd, const RString &sDir, const RString &sMatch, vector< RString > &AddTo)
bool DeleteRecursive (const RString &sDir)
bool DeleteRecursive (RageFileDriver *prfd, const RString &sDir)
bool DoesFileExist (const RString &sPath)
bool IsAFile (const RString &sPath)
bool IsADirectory (const RString &sPath)
int GetFileSizeInBytes (const RString &sFilePath)
void FixSlashesInPlace (RString &sPath)
void CollapsePath (RString &sPath, bool bRemoveLeadingDot=false)
template<typename T >
bool StringConversion::FromString (const RString &sValue, T &out)
template<typename T >
RString StringConversion::ToString (const T &value)
template<>
bool StringConversion::FromString< RString > (const RString &sValue, RString &out)
template<>
RString StringConversion::ToString< RString > (const RString &value)
bool FileCopy (const RString &sSrcFile, const RString &sDstFile)
bool FileCopy (RageFileBasic &in, RageFileBasic &out, RString &sError, bool *bReadError=nullptr)
template<class T >
void GetAsNotInBs (const vector< T > &as, const vector< T > &bs, vector< T > &difference)
template<class T >
void GetConnectsDisconnects (const vector< T > &before, const vector< T > &after, vector< T > &disconnects, vector< T > &connects)
Variables
RandomGen g_RandomNumberGenerator
const wchar_t INVALID_CHAR
int g_argc
char ** g_argv
unsigned char g_UpperCase [256]
unsigned char g_LowerCase [256]
Detailed Description
Author
Chris Danford, Glenn Maynard (c) 2001-2005
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
ARRAYLEN
#define ARRAYLEN (a) (sizeof(a) / sizeof((a)[0]))
Get the length of the array.
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), BGBrightness(), BGBrightnessNoZero(), BGBrightnessOrStatic(), CheckVideoDefaultSettings(), RageSoundDriver::DecodeThread(), DisplayAspectRatio(), DisplayColorDepth(), GraphBody::DrawPrimitives(), EditClearPromptThreshold(), EditRecordModeLeadIn(), RageSoundDriver::GetDataForSound(), GameManager::GetDefaultGame(), GameManager::GetEnabledGames(), InputScheme::GetGameButtonInfo(), GameManager::GetGameFromIndex(), Font::GetGlyph(), GameManager::GetIndexFromGame(), GetLanguageInfo(), GetLanguageInfos(), NotesLoader::GetMainAndSubTitlesFromFullTitle(), Game::GetPerButtonInfo(), GameManager::GetStepsTypeInfo(), GlobalOffsetSeconds(), InputHandler_Win32_Pump::HandleInput(), InputDebounceTime(), LifeDifficulty(), Font::Load(), MaxTextureResolution(), RageSoundDriver::MixIntoBuffer(), MovieColorDepth(), MusicWheelSwitchSpeed(), NumBackgrounds(), RageSoundReader_Preload::Open(), EventDevice::Open(), Actor::TweenState::operator==(), PathUsesSlowFlush(), RageSoundDriver::PauseMixing(), RageSoundReader_Merge::Read(), RageSoundReader_Chain::Read(), RefreshRate(), NoteDataUtil::RemoveStretch(), ScrollBar::ScrollBar(), GraphDisplay::Set(), ScrollBar::SetPercentage(), SoundVolume(), SoundVolumeAttract(), RageSoundDriver::StartMixing(), RageSoundDriver::StopMixing(), GameManager::StringToGame(), TextureColorDepth(), TimingWindowScale(), RageSoundDriver::Update(), VisualDelaySeconds(), WideScreen16_10(), and WideScreen16_9().
clamp
#define clamp (val, low, high) (max((low), min((val), (high))))
If outside the range from low to high, bring it within range.
Referenced by Model::AdvanceFrame(), ArrowGetPercentVisible(), RageSurfaceUtils::BlitTransform(), RageSoundUtil::ConvertFloatToNativeInt16(), NoteData::CopyRange(), NoteDisplay::DrawActor(), BitmapText::DrawChars(), RageDisplay_Legacy::DrawLineStripInternal(), EDDitherPixel(), RageSoundUtil::Fade(), FourCCToString(), TimingData::GetActualBPM(), DisplayBpms::GetMaxWithin(), Alsa9Buf::GetNumFramesToFill(), ScreenSelectMaster::Init(), InitVectors(), HighScoreImpl::LoadFromEttNode(), LoadFromKSFFile(), HighScoreImpl::LoadFromNode(), ScreenGameplay::LoadNextSong(), DBProfile::LoadPlayerScores(), RageSoundDriver::MixIntoBuffer(), RageSurfaceUtils::Palettize(), RageSurfaceUtils::PalettizeToGrayscale(), ActorScroller::PositionItemsAndDrawPrimitives(), SMLoader::ProcessTickcounts(), RageSoundMixBuffer::read(), RageFileObjMem::SeekInternal(), ModIconRow::SetFromGameState(), GrooveRadar::GrooveRadarValueMap::SetFromSteps(), RageSoundManager::SetMixVolume(), Model::SetPosition(), RageColor::ToString(), WheelBase::Update(), and RageSurfaceUtils::Zoom().
COPY
#define COPY (a, b)
Value:
do {                                                                       \
        ASSERT(sizeof(a) == sizeof(b));                                        \
        memcpy(&(a), &(b), sizeof(a));                                         \
    } while (false)
Copy from a to b.
SAFE_DELETE
#define SAFE_DELETE (p)
Value:
do {                                                                       \
        delete (p);                                                            \
        (p) = NULL;                                                            \
    } while (false)
Safely delete pointers.
Referenced by TimingData::AddSegment(), CharacterManager::CharacterManager(), OptionRow::Clear(), TimingData::Clear(), LoadingWindow::Create(), RageMovieTexture::Create(), RageSoundDriver::Create(), RageMovieTextureDriver_FFMpeg::Create(), RageMovieTextureDriver_DShow::Create(), CreateDisplay(), LocalizedString::CreateImpl(), MovieTexture_Generic::CreateTexture(), ScreenManagerUtil::DeletePreparedScreens(), RageTextureManager::DeleteTexture(), JsonUtil::DeserializeVectorPointers(), JsonUtil::DeserializeVectorPointersParam(), LunaRageFile::destroy(), LunaRageBezier2D::destroy(), LunaCubicSplineN::destroy(), EraseSegment(), SongManager::FreeSongs(), NetworkSyncManager::GetCurrentSMBuild(), GunzipString(), TZip::iclose(), ScreenSMOnlineLogin::Init(), ScreenOptions::InitMenu(), InputHandler_Win32_Para::InputHandler_Win32_Para(), WheelBase::Load(), Player::Load(), ScreenManager::LoadDelayedScreen(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), TZip::open_file(), ScreenManager::PopTopScreenInternal(), ThreadSlot::Release(), ScreenManager::ReloadOverlayScreens(), LunaActorFrame::RemoveChild(), RoomWheel::RemoveItem(), Actor::RemoveWrapperState(), ThreadedFileWorker::RequestTimedOut(), Song::Reset(), ScreenGameplay::SaveReplay(), RageDisplay::SaveScreenshot(), RoomInfoDisplay::SetRoomInfo(), RageSoundManager::Shutdown(), ShutdownGame(), sm_main(), ScreenManager::ThemeChanged(), ModelManager::UnloadModel(), BackgroundImpl::Layer::UpdateCurBGChange(), Actor::~Actor(), Background::~Background(), CharacterManager::~CharacterManager(), CryptManager::~CryptManager(), FilterManager::~FilterManager(), GameSoundManager::~GameSoundManager(), GameState::~GameState(), GraphDisplay::~GraphDisplay(), LifeMeterBar::~LifeMeterBar(), LocalizedString::~LocalizedString(), LuaManager::~LuaManager(), ModelManager::~ModelManager(), ModIconRow::~ModIconRow(), MusicWheelItem::~MusicWheelItem(), Player::~Player(), PlayerInfo::~PlayerInfo(), Preference1D< StdString::CStdStr >::~Preference1D(), RageLog::~RageLog(), RageTextureManager::~RageTextureManager(), RoomInfoDisplay::~RoomInfoDisplay(), RoomWheel::~RoomWheel(), ScreenDebugOverlay::~ScreenDebugOverlay(), ScreenGameplay::~ScreenGameplay(), ScreenManager::~ScreenManager(), ScreenMapControllers::~ScreenMapControllers(), ScreenOptions::~ScreenOptions(), ScreenTextEntryVisual::~ScreenTextEntryVisual(), ScreenWithMenuElements::~ScreenWithMenuElements(), SMOProtocol::~SMOProtocol(), Song::~Song(), ThemeManager::~ThemeManager(), and WheelBase::~WheelBase().
SAFE_DELETE_ARRAY
#define SAFE_DELETE_ARRAY (p)
Value:
do {                                                                       \
        delete[](p);                                                           \
        (p) = NULL;                                                            \
    } while (false)
Safely delete array pointers.
Referenced by ThreadedFileWorker::RequestTimedOut().
SCALE
#define SCALE (x, l1, h1, l2, h2) (((x) - (l1)) * ((h2) - (l2)) / ((h1) - (l1)) + (l2))
Scales x so that l1 corresponds to l2 and h1 corresponds to h2.
This does not modify x, so it MUST assign the result to something! Do the multiply before the divide to that integer scales have more precision.
One such example: SCALE(x, 0, 1, L, H); interpolate between L and H.
Referenced by ArrowGetPercentVisible(), ArrowGetReverseShiftAndScale(), Actor::BeginDraw(), ScreenTextEntryVisual::BeginScreen(), blit_rgba_to_rgba(), BitmapText::BuildChars(), NoteField::CalcPixelsBeforeAndAfterTargets(), NoteField::DrawBeatBar(), BitmapText::DrawChars(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldPart(), NoteField::DrawPrimitives(), Sprite::DrawPrimitives(), DancingCharacters::DrawPrimitives(), Sprite::DrawTexture(), RageBezier2D::EvaluateYFromX(), RageSoundUtil::Fade(), ArrowEffects::GetAlpha(), ArrowEffects::GetBrightness(), RageDisplay::GetCenteringMatrix(), ArrowEffects::GetFrameWidthScale(), ArrowEffects::GetGlow(), GetHiddenEndLine(), GetHiddenStartLine(), PlayerStageStats::GetLifeRecord(), PlayerStageStats::GetLifeRecordLerpAt(), LunaInputFilter::GetMouseX(), LunaInputFilter::GetMouseY(), PlayerOptions::GetReversePercentForColumn(), GetSuddenEndLine(), GetSuddenStartLine(), PlayerStageStats::GetWifeRecord(), PlayerStageStats::GetWifeRecordLerpAt(), ArrowEffects::GetXPos(), ArrowEffects::GetYOffset(), GlobalOffsetSeconds(), ScreenStatsOverlay::Init(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), ModIconRow::Load(), Sprite::LoadFromNode(), RageDisplay::LoadMenuPerspective(), ScreenGameplay::LoadNextSong(), MakeRandomHighScore(), RageSoundUtil::Pan(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), Actor::PreDraw(), Player::PushPlayerMatrix(), RandomFloat(), RageSoundReader_Extend::Read(), RageSoundReader_SpeedChange::Read(), ComboGraph::Set(), GraphDisplay::Set(), Model::SetBones(), MeterDisplay::SetPercent(), ScrollBar::SetPercentage(), DualScrollBar::SetPercentage(), SetPixelMapForSurface(), RageSoundReader_Resample_Good::SetPosition(), LunaSprite::SetStateProperties(), RageDisplay_GLES2::SetZBias(), RageDisplay_D3D::SetZBias(), RageDisplay_Legacy::SetZBias(), sine_initter::sine_initter(), LuaExpressionTransform::TransformItemCached(), ArrowEffects::Update(), SoundEffectControl::Update(), DancingCharacters::Update(), SongMeterDisplay::Update(), Player::Update(), InputHandler_DInput::UpdateBuffered(), InputHandler_DInput::UpdatePolled(), and GraphDisplay::UpdateVerts().
ZERO
#define ZERO (x) memset(&(x), 0, sizeof(x))
Zero out the memory.
Referenced by acolorhash_hash::acolorhash_hash(), ScreenSelectMusic::BeginScreen(), ChooseWindowPixelFormat(), OptionRow::Clear(), DestroyGraphicsWindowAndOpenGLContext(), CodeDetector::DetectAndAdjustMusicOptions(), InputHandler_DInput::DeviceButtonToChar(), ScreenOptionsMaster::ExportOptions(), FilterManager::FilterManager(), PlayerOptions::FromOneModString(), GetDayInYearAndYear(), ArchHooks_Win32::GetDisplayAspectRatio(), HighScoreImpl::HighScoreImpl(), RageSoundDriver_WaveOut::Init(), DSoundBuf::Init(), ScreenEvaluation::Init(), PlayerOptions::Init(), DateTime::Init(), Profile::InitGeneralData(), PlayerStageStats::InternalInit(), Font::Load(), LoadBMP(), OptionRow::OptionRow(), PlayerOptions::PlayerOptions(), Profile::Profile(), ScancodeAndKeysToChar(), ScreenSelectMaster::ScreenSelectMaster(), RageDisplay_D3D::SetLightDirectional(), PlayerOptions::SetOneAccel(), PlayerOptions::SetOneAppearance(), PlayerOptions::SetOneEffect(), PlayerOptions::SetOneScroll(), SetPresentParametersFromVideoModeParams(), ArchHooks_Win32::SetTime(), SetupFormat(), PlayerOptions::ToggleOneTurn(), InputHandler_Linux_Joystick::TryDevice(), and LowLevelWindow_Win32::TryVideoMode().
Typedef Documentation
istring
typedef basic_string<char, char_traits_char_nocase> istring
RandomGen
typedef std::mt19937 RandomGen
Function Documentation
Basename()
RString Basename (const RString & dir)
Referenced by DirectFilenameDB::CacheFile(), ChangeToDirOfExecutable(), RageTextureManager::DiagnosticOutput(), SongManager::DifferentialReloadDir(), ScreenPackages::EnterURL(), FilenameDB::FlushDirCache(), FilenameDB::GetFileSet(), BackgroundUtil::GetGlobalBGAnimations(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), RageSound::Load(), BGAnimation::LoadFromAniDir(), SongManager::LoadStepManiaSongDir(), LocalProfileDirToID(), MakeTempFilename(), Download::MakeTempFileName(), FileTransfer::StartTransfer(), Song::TidyUpData(), GameSoundManager::Update(), and ScreenTestSound::UpdateText().
BeginsWith()
bool BeginsWith (const RString & sTestThis, const RString & sBeginning)
References ASSERT.
Referenced by IsHTTPProtocol(), LoadFromKSFFile(), LoadGlobalData(), DirectFilenameDB::PopulateFileSet(), PrefsManager::ReadGamePrefsFromIni(), SongManager::UpdatePreferredSort(), and SongManager::WasLoadedFromAdditionalSongs().
BinaryToHex() [1/2]
RString BinaryToHex (const void * pData_, int iNumBytes)
References ssprintf().
Referenced by LunaProfile::AddScreenshot(), BinaryToHex(), HighScoreImpl::CreateEttNode(), DoInstalls(), FillInHighScore(), Steps::GenerateBustedChartKey(), Steps::GenerateChartKey(), Song::GetFileHash(), ScreenEvaluation::Input(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), DBProfile::LoadPlayerScores(), NetworkSyncManager::MD5Hex(), and DBProfile::SavePlayerScores().
BinaryToHex() [2/2]
RString BinaryToHex (const RString & sString)
References BinaryToHex().
calc_mean()
float calc_mean (const float * pStart, const float * pEnd)
References f.
Referenced by AdjustSync::AutosyncOffset(), and calc_stddev().
calc_stddev()
float calc_stddev (const float * pStart, const float * pEnd, bool bSample = false)
References calc_mean().
Referenced by AdjustSync::AutosyncOffset().
CalcLeastSquares()
bool CalcLeastSquares (const vector< pair< float, float >> & vCoordinates, float & fSlope, float & fIntercept, float & fError)
Referenced by AdjustSync::AutosyncTempo().
Capitalize()
RString Capitalize (const RString & s)
References MakeUpper().
Referenced by SongUtil::AdjustDuplicateSteps(), GhostArrowRow::DidHoldNote(), GhostArrowRow::DidTapNote(), InputHandler::GetDeviceSpecificInputString(), RageInput::GetLocalizedInputString(), InputHandler::GetLocalizedInputString(), PlayerOptions::GetLocalizedMods(), PlayerOptions::GetMods(), ReceptorArrow::Step(), and GameManager::StyleToLocalizedString().
CircularShift()
template<class T > void CircularShift (vector< T > & v, int dist)
References T.
Referenced by WheelBase::RebuildWheelItems(), and ActorScroller::ShiftSubActors().
CLAMP()
template<typename T , typename U , typename V > bool CLAMP (T & x, U l, V h)
References T.
Referenced by ScreenSelectMusic::AfterStepsOrTrailChange(), ArrowGetPercentVisible(), ScreenSelectMaster::BeginScreen(), ScoreManager::CalcPlayerRating(), LifeMeterBar::ChangeLife(), LunaChart::ChangeRate(), ScreenSelectMusic::ChangeSteps(), ScreenOptions::ChangeValueInRowRelative(), ChangeVisualDelay(), ChangeVolume(), NoteField::DrawBeatBar(), NoteField::DrawPrimitives(), Sprite::DrawTexture(), EDDitherPixel(), LifeMeterBar::FillForHowToPlay(), FTOC(), ArrowEffects::GetBrightness(), ArrowEffects::GetFrameWidthScale(), Song::GetHighestOfSkillsetAllSteps(), LifeMeterTime::GetLife(), LunaSteps::GetMSD(), LunaSteps::GetRelevantSkillsetsByMSDRank(), ArrowEffects::GetYOffset(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenGameplay::InitSongQueues(), ScreenDebugOverlay::Input(), RageDisplay::LoadMenuPerspective(), NoteDataUtil::LoadTransformedSlidingWindow(), ProcessTickcounts(), PercentageDisplay::Refresh(), GraphDisplay::Set(), LifeMeterBar::SetLife(), LunaFilterManager::SetMaxFilterRate(), LunaFilterManager::SetMinFilterRate(), LunaScoreGoal::SetPercent(), LunaScoreGoal::SetPriority(), LunaScoreGoal::SetRate(), AnimatedTexture::SetState(), Sprite::SetState(), ScreenSelectMusic::SwitchToPreferredDifficulty(), ArrowEffects::Update(), ReceptorArrowRow::Update(), LifeMeterBar::Update(), SoundEffectControl::Update(), StreamDisplay::Update(), DancingCharacters::Update(), SongMeterDisplay::Update(), CubicSplineN::weighted_average(), and NoteDataUtil::Wide().
CollapsePath()
void CollapsePath (RString & sPath, bool bRemoveLeadingDot = false)
Referenced by BGAnimation::AddLayersFromAniDir(), ChangeToDirOfExecutable(), DerefRedir(), Song::GetSongAssetPath(), HoldJudgment::LoadFromNode(), BGAnimationLayer::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), NormalizePath(), ActorUtil::ResolvePath(), RageTextureID::SetFilename(), and SplitPath().
Commify() [1/2]
RString Commify (int iNum)
References Commify(), and ssprintf().
Referenced by Commify(), LuaFunc_commify(), and RollingNumbers::UpdateText().
Commify() [2/2]
RString Commify (const RString & num, const RString & sep = ",", const RString & dot = ".")
CompareRStringsAsc()
bool CompareRStringsAsc (const RString & sStr1, const RString & sStr2)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by CompareSongPointersByBPM(), CompareSongPointersByLength(), SongManager::Comp::operator()(), and SortRStringArray().
CompareRStringsDesc()
bool CompareRStringsDesc (const RString & sStr1, const RString & sStr2)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by SortRStringArray().
ConvertI64FormatString()
RString ConvertI64FormatString (const RString & sStr)
Referenced by ActorFrameTexture::ActorFrameTexture().
ConvertValue()
template<typename TO , typename FROM > ConvertValueHelper<TO, FROM> ConvertValue (FROM * pValue)
CRC32()
void CRC32 (unsigned int & iCRC, const void * pBuffer, size_t iSize)
Referenced by GetHashForString().
CreateClass()
template<typename Type , typename Ret > static Ret* CreateClass () static
Decrement()
template<class T > T Decrement (T a)
Referenced by NoteData::GetTapNoteRangeInclusive().
DeleteRecursive() [1/2]
bool DeleteRecursive (const RString & sDir)
References ASSERT, DeleteRecursive(), FOREACH_CONST, GetDirListing(), IsADirectory(), RageFileManager::Remove(), and StdString::CStdStr< CT >::Right().
DeleteRecursive() [2/2]
bool DeleteRecursive (RageFileDriver * prfd, const RString & sDir)
References ASSERT, DeleteRecursive(), FOREACH_CONST, RageFileDriver::GetDirListing(), IsADirectory(), RageFileManager::Remove(), and StdString::CStdStr< CT >::Right().
Referenced by ProfileManager::DeleteLocalProfile(), RageFileManager::DeleteRecursive(), and DeleteRecursive().
DerefRedir()
RString DerefRedir (const RString & sPath)
References CollapsePath(), Dirname(), GetDirListing(), GetExtension(), GetFileContents(), and RageException::Throw().
Referenced by Character::GetDanceAnimationPath(), Character::GetRestAnimationPath(), Character::GetWarmUpAnimationPath(), and ActorUtil::ResolvePath().
DirectoryIsEmpty()
bool DirectoryIsEmpty (const RString & sPath)
References DoesFileExist(), and GetDirListing().
Referenced by AnnouncerManager::GetPathTo(), and AnnouncerManager::HasSoundsFor().
Dirname()
RString Dirname (const RString & dir)
Referenced by BMSSong::AllocateKeysound(), XmlFileUtil::AnnotateXNodeTree(), DirectFilenameDB::CacheFile(), FilenameDB::CacheFile(), DerefRedir(), ScreenPackages::EnterURL(), RageFileObjDirect::FinalFlush(), FilenameDB::FlushDirCache(), BMSSong::GetBackground(), FilenameDB::GetFileSet(), ScreenGameplaySyncMachine::Init(), AnimatedTexture::Load(), actor_template_t::load_node(), ActorUtil::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), MakeTempFilename(), RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), FileTransfer::StartTransfer(), and RageFileObjDirect::~RageFileObjDirect().
DoesFileExist()
bool DoesFileExist (const RString & sPath)
References RageFileManager::DoesFileExist().
Referenced by BeginnerHelper::AddPlayer(), ImageCache::CacheImage(), BeginnerHelper::CanUse(), CopyEdits(), BackgroundImpl::Layer::CreateBackground(), DancingCharacters::DancingCharacters(), DirectoryIsEmpty(), CryptManager::GenerateGlobalKeys(), Character::GetModelPath(), ThemeManager::GetPathInfoToRaw(), Song::GetSongAssetPath(), Alsa9Buf::GetSoundCardDebugInfo(), Character::Has2DElems(), HighScore::HasReplayData(), HaveAllCharAnimations(), ScreenHowToPlay::Init(), BGAnimation::LoadFromAniDir(), Foreground::LoadFromSong(), ActorUtil::MakeActor(), ActorUtil::ResolvePath(), sm_main(), SyncFiles(), SongUtil::ValidateCurrentSongPreview(), and SongUtil::ValidateCurrentStepsMusic().
DwiEscape() [1/2]
RString DwiEscape (const RString & sUnescaped)
References DwiEscape().
Referenced by DwiEscape(), and NotesWriterDWI::Write().
DwiEscape() [2/2]
RString DwiEscape (const char * cUnescaped, int len)
EndsWith()
bool EndsWith (const RString & sTestThis, const RString & sEnding)
References ASSERT.
Referenced by ActorUtil::LoadAllCommandsFromName(), LoadFromKSFFile(), Actor::LoadFromNode(), ThemeManager::PushMetric(), and SongManager::UpdatePreferredSort().
enum_add()
template<typename T > static void enum_add (T & val, int iAmt) static
References T.
Referenced by InputHandler_MacOSX_HID::AddDevices(), ModsGroup< SongOptions >::Assign(), ModsGroup< SongOptions >::Assign_n(), ModsGroup< SongOptions >::Call(), DebugLineProfileSlot::DoAndLog(), ModsGroup< SongOptions >::FromString(), PlayerStageStats::GetBestFullComboTapNoteScore(), GetNextCpuPlayer(), GetNextEnabledMultiPlayer(), GetNextEnabledPlayer(), GetNextHumanPlayer(), GetNextPotentialCpuPlayer(), ScreenEvaluation::Init(), SnapDisplay::NextSnapMode(), SnapDisplay::PrevSnapMode(), and SMLoader::ProcessBGChanges().
enum_add2()
template<typename T > static T enum_add2 (T val, int iAmt) static
References T.
Referenced by InputHandler_SextetStream::Impl::ButtonAtIndex(), GameState::ChangePreferredDifficulty(), ActorMultiTexture::DrawPrimitives(), EnumDevicesCallback(), InputHandler_Win32_Pump::HandleInput(), ScoreKeeperNormal::HandleTapRowScore(), ScoreKeeperNormal::HandleTapScoreNone(), InputMapper::InputDeviceToMultiPlayer(), InputHandler_Linux_PIUIO::InputThread(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), midiCallback(), ScreenTextEntryVisual::MoveY(), InputMapper::MultiPlayerToInputDevice(), EventDevice::Open(), SetTextureUnit(), StringToDeviceButton(), InputHandler_Linux_Event::TryDevice(), InputHandler_DInput::UpdateBuffered(), InputHandler_DInput::UpdatePolled(), and XSymToDeviceButton().
ENUM_CLAMP()
template<class T > bool ENUM_CLAMP (T & x, T l, T h)
Referenced by ScreenPrompt::BeginScreen(), and ScreenSetTime::ChangeSelection().
enum_cycle()
template<typename T > static T enum_cycle (T val, int iMax, int iAmt = 1) static
References T.
fapproach()
void fapproach (float & val, float other_val, float to_move)
References ASSERT_M, and ssprintf().
Referenced by PlayerOptions::Approach(), luafunc_approach_internal(), GameSoundManager::Update(), RollingNumbers::Update(), ScreenDebugOverlay::Update(), and ActorScroller::UpdateInternal().
FileCopy() [1/2]
bool FileCopy (const RString & sSrcFile, const RString & sDstFile)
References StdString::CStdStr< CT >::CompareNoCase(), FileCopy(), LOG, RageFile::Open(), RageFile::READ, RageLog::Warn(), and RageFile::WRITE.
Referenced by CopyEdits(), FileCopy(), DownloadManager::InstallSmzip(), RageSoundReader_FileReader::OpenFile(), Song::Save(), Profile::SaveMachinePublicKeyToDir(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), Song::SaveToSSCFile(), and SyncFiles().
FileCopy() [2/2]
bool FileCopy (RageFileBasic & in, RageFileBasic & out, RString & sError, bool * bReadError = nullptr)
References RageFileBasic::Flush(), RageFileBasic::GetError(), RageFileBasic::Read(), ssprintf(), and RageFileBasic::Write().
FilterHighErrorPoints()
void FilterHighErrorPoints (vector< pair< float, float >> & vCoordinates, float fSlope, float fIntercept, float fCutoff)
Referenced by AdjustSync::AutosyncTempo().
FindFirstFilenameContaining()
bool FindFirstFilenameContaining (const vector< RString > & filenames, RString & out, const vector< RString > & starts_with, const vector< RString > & contains, const vector< RString > & ends_with)
References GetFileNameWithoutExtension(), and StdString::CStdStr< CT >::MakeLower().
Referenced by Song::TidyUpData().
FindIndex()
template<class T1 , class T2 > int FindIndex (T1 begin, T1 end, const T2 * p)
Referenced by SongManager::GetSongRank().
FixSlashesInPlace()
void FixSlashesInPlace (RString & sPath)
Referenced by AdjustMountpoint(), FixupPath(), RageFileManager::GetFileDriver(), BGAnimationLayer::LoadFromNode(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), RageFileManager::Mount(), NormalizePath(), RageFile::Open(), and RageFileManager::Unmount().
FloatToString()
RString FloatToString (const float & num)
Referenced by convert_xpos(), convert_ypos(), HighScoreImpl::CreateEttNode(), NoteField::DrawPrimitives(), actor_template_t::output_to_file(), and TimingSegment::ToString().
fmodfp()
float fmodfp (float x, float y)
Referenced by Actor::PreDraw(), and StartMusic().
FormatNumberAndSuffix()
RString FormatNumberAndSuffix (int i)
References LocalizedString::GetValue(), NUM_ND, NUM_PREFIX, NUM_RD, NUM_ST, NUM_TH, and ssprintf().
Referenced by AdjustSync::GetSyncChangeTextSong().
fracf()
float fracf (float f) inline
ftruncf()
float ftruncf (const float f, const float fTruncInterval) inline
References f.
Referenced by PlayerStageStats::MakePercentScore(), and InputFilter::Update().
GetAsNotInBs()
template<class T > void GetAsNotInBs (const vector< T > & as, const vector< T > & bs, vector< T > & difference)
Referenced by GetConnectsDisconnects(), and SyncFiles().
GetCommandlineArgument()
bool GetCommandlineArgument (const RString & option, RString * argument = nullptr, int iIndex = 0)
References StdString::CStdStr< CT >::CompareNoCase(), and g_argc.
Referenced by GameState::ApplyCmdline(), PrefsManager::GetPreferencesSection(), CommandLineActions::Handle(), StepMania::InitializeCurrentGame(), ThemeManager::LoadThemeMetrics(), sm_main(), and NetworkSyncManager::StartUp().
GetCommandLineArguments()
void GetCommandLineArguments (int & argc, char **& argv)
References g_argc, and g_argv.
GetConnectsDisconnects()
template<class T > void GetConnectsDisconnects (const vector< T > & before, const vector< T > & after, vector< T > & disconnects, vector< T > & connects)
References GetAsNotInBs().
Referenced by InputMapper::CheckForChangedInputDevicesAndRemap().
GetCwd()
RString GetCwd ()
References ASSERT.
Referenced by ChangeToDirOfExecutable(), and GetDirOfExecutable().
GetDirListing()
void GetDirListing (const RString & sPath, vector< RString > & AddTo, bool bOnlyDirs = false, bool bReturnPathToo = false)
References RageFileManager::GetDirListing().
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), ScreenOptionsExportPackageSubPage::BeginScreen(), CharacterManager::CharacterManager(), CopyEdits(), DeleteEmptyDirectories(), DeleteRecursive(), DerefRedir(), SongManager::DifferentialReloadDir(), DirectoryIsEmpty(), DoPlayOnceFromDir(), EmptyDir(), ScreenPackages::EnterURL(), NoteSkinManager::GetAllNoteSkinNamesForGame(), AnnouncerManager::GetAnnouncerNames(), KSFLoader::GetApplicableFiles(), BMSLoader::GetApplicableFiles(), NotesLoaderJson::GetApplicableFiles(), DWILoader::GetApplicableFiles(), OsuLoader::GetApplicableFiles(), SMLoader::GetApplicableFiles(), BackgroundUtil::GetBackgroundEffects(), BackgroundUtil::GetBackgroundTransitions(), GetDirListingRecursive(), Font::GetFontPaths(), BackgroundUtil::GetGlobalBGAnimations(), GetHashForDirectory(), ThemeManager::GetLanguagesForTheme(), ThemeManager::GetOptionalLanguageIniPaths(), NoteSkinManager::GetPathFromDirAndFile(), ThemeManager::GetPathInfoToRaw(), GetRandomFileInDir(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), Character::GetSongSelectIconPath(), Character::GetStageIconPath(), Character::GetTakingABreakPath(), ThemeManager::GetThemeNames(), ScreenGameplayLesson::Init(), DownloadManager::InstallSmzip(), Character::Load(), Profile::LoadAllFromDir(), BGAnimation::LoadFromAniDir(), KSFLoader::LoadFromDir(), LoadGlobalData(), RandomSample::LoadSoundDir(), SongManager::LoadStepManiaSongDir(), Profile::MakeUniqueFileNameNoExtension(), MountTreeOfZips(), Nsis(), ProfileManager::RefreshLocalProfilesFromDisk(), NoteSkinManager::RefreshNoteSkinData(), ScreenPackages::RefreshPackages(), ActorUtil::ResolvePath(), ThemeManager::RunLuaScripts(), SongManager::SanityCheckGroupDir(), Song::Save(), ScreenGameplay::SaveReplay(), LoadingWindow_MacOSX::SetSplash(), SyncFiles(), CryptManager::VerifyFileWithFile(), and LoadingWindow_Win32::WndProc().
GetDirListingRecursive() [1/2]
void GetDirListingRecursive (const RString & sDir, const RString & sMatch, vector< RString > & AddTo)
References ASSERT, GetDirListing(), IsADirectory(), and StdString::CStdStr< CT >::Right().
Referenced by DownloadManager::InstallSmzip().
GetDirListingRecursive() [2/2]
void GetDirListingRecursive (RageFileDriver * prfd, const RString & sDir, const RString & sMatch, vector< RString > & AddTo)
References ASSERT, RageFileDriver::GetDirListing(), RageFileDriver::GetFileType(), StdString::CStdStr< CT >::Right(), and RageFileManager::TYPE_DIR.
GetExtension()
RString GetExtension (const RString & sPath)
Referenced by DerefRedir(), DoInstalls(), Song::GetCacheFile(), RageFileManager::GetDirListingWithMultipleExtensions(), ActorUtil::GetFileType(), Steps::GetNoteDataFromSimfile(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfoToRaw(), DownloadManager::InstallSmzip(), IsPackageFile(), RandomSample::Load(), Model::Load(), AnimatedTexture::Load(), Font::Load(), actor_template_t::load_node(), RageSurfaceUtils::LoadFile(), SSCLoader::LoadNoteDataFromSimfile(), RageSoundReader_FileReader::OpenFile(), Song::RemoveAutosave(), SongManager::SanityCheckGroupDir(), Song::SaveToETTFile(), Song::SaveToSSCFile(), StartMusic(), and Song::TidyUpData().
GetFileContents() [1/4]
bool GetFileContents (const RString & sPath, RString & sOut, bool bOneLine = false)
References RageFile::GetError(), RageFile::GetFileSize(), RageFile::GetLine(), IsAFile(), LOG, RageFile::Open(), RageFile::Read(), StripCrnl(), and RageLog::Warn().
Referenced by DerefRedir(), CryptManager::GenerateGlobalKeys(), NoteSkinManager::GetPath(), ThemeManager::GetPathInfoToRaw(), PrefsManager::GetPreferencesSection(), Alsa9Buf::GetSoundCardDebugInfo(), ScreenWithMenuElements::HandleLuaMusicFile(), NoteSkinManager::LoadNoteSkinDataRecursive(), LuaHelpers::run_script_file_in_state(), LuaHelpers::RunScriptFile(), CryptManager::SignFileToFile(), SongManager::UpdatePreferredSort(), and CryptManager::VerifyFileWithFile().
GetFileContents() [2/4]
bool GetFileContents (const RString & sFile, vector< RString > & asOut)
References RageFile::GetError(), RageFile::GetLine(), LOG, RageFile::Open(), and RageLog::Warn().
GetFileContents() [3/4]
bool GetFileContents (const std::string & sPath, std::string & sOut, bool bOneLine = false)
References RageFile::GetError(), RageFile::GetFileSize(), RageFile::GetLine(), IsAFile(), LOG, RageFile::Open(), RageFile::Read(), StripCrnl(), and RageLog::Warn().
GetFileContents() [4/4]
bool GetFileContents (const std::string & sFile, vector< std::string > & asOut)
References RageFile::GetError(), RageFile::GetLine(), LOG, RageFile::Open(), and RageLog::Warn().
GetFileNameWithoutExtension()
RString GetFileNameWithoutExtension (const RString & sPath)
References splitpath().
Referenced by FindFirstFilenameContaining(), BackgroundUtil::GetBackgroundEffects(), and BackgroundUtil::GetBackgroundTransitions().
GetFileSizeInBytes()
int GetFileSizeInBytes (const RString & sFilePath)
References RageFileManager::GetFileSizeInBytes().
GetHashForDirectory()
unsigned int GetHashForDirectory (const RString & sDir)
References GetDirListing(), GetHashForFile(), and GetHashForString().
Referenced by SongCacheIndex::CacheSong(), SongCacheIndex::DeleteSongFromDB(), SongManager::InitSongsFromDisk(), and SongCacheIndex::LoadSongFromCache().
GetHashForFile()
unsigned int GetHashForFile (const RString & sPath)
References RageFileManager::GetFileHash().
Referenced by ImageCache::CacheImage(), ImageCache::CacheImageInternal(), and GetHashForDirectory().
GetHashForString()
unsigned int GetHashForString (const RString & s)
References CRC32().
Referenced by Steps::GetHash(), GetHashForDirectory(), and BackgroundImpl::LoadFromSong().
GetLanguageInfo()
const LanguageInfo* GetLanguageInfo (const RString & sIsoCode)
References ARRAYLEN, StdString::CStdStr< CT >::EqualsNoCase(), and LanguageInfo::szIsoCode.
Referenced by ScreenSelectLanguage::Init(), LanguageChoices(), and Nsis().
GetLanguageInfos()
void GetLanguageInfos (vector< const LanguageInfo *> & vAddTo)
References ARRAYLEN.
GetLanguageNameFromISO639Code()
RString GetLanguageNameFromISO639Code (const RString & sName)
GetLocalTime()
struct tm GetLocalTime ()
HexToBinary() [1/2]
bool HexToBinary (const RString & s, unsigned char * stringOut)
References IsHexVal().
HexToBinary() [2/2]
bool HexToBinary (const RString & s, RString * sOut)
HHMMSSToSeconds()
float HHMMSSToSeconds (const RString & sHMS)
References split(), StringToFloat(), and StringToInt().
Referenced by LyricsLoader::LoadFromLRCFile(), SMALoader::LoadFromSimfile(), LoadGlobalData(), ParseBrokenDWITimestamp(), SetSampleLength(), SetSampleStart(), SMSetSampleLength(), and SMSetSampleStart().
Increment()
template<class T > T Increment (T a)
Referenced by LoadFromSMNoteDataStringWithPlayer().
IntToString()
RString IntToString (const int & iNum)
Have a standard way of converting integers to Strings.
Parameters
iNum the integer to convert.
Returns
the string we are after.
Referenced by GetSMNotesTag(), MenuRowDef::MenuRowDef(), actor_template_t::output_to_file(), RadarValues::ToString(), FakeSegment::ToString(), WarpSegment::ToString(), TickcountSegment::ToString(), ComboSegment::ToString(), LabelSegment::ToString(), BPMSegment::ToString(), TimeSignatureSegment::ToString(), SpeedSegment::ToString(), ScrollSegment::ToString(), StopSegment::ToString(), and DelaySegment::ToString().
IsADirectory()
bool IsADirectory (const RString & sPath)
References RageFileManager::IsADirectory().
Referenced by BGAnimation::AddLayersFromAniDir(), RageSoundDriver_OSS::CheckOSSVersion(), DeleteEmptyDirectories(), DeleteRecursive(), EmptyDir(), GetDirListingRecursive(), ActorUtil::GetFileType(), LoadALSA(), BGAnimation::LoadFromAniDir(), and MountTreeOfZips().
IsAFile()
bool IsAFile (const RString & sPath)
References RageFileManager::IsAFile().
Referenced by BMSSong::AllocateKeysound(), ScreenSelectMusic::CheckBackgroundRequests(), BMSSong::GetBackground(), GetFileContents(), Song::GetFileHash(), Profile::HandleStatsPrefixChange(), Song::HasBackground(), Song::HasBanner(), Song::HasCDImage(), Song::HasCDTitle(), Song::HasDisc(), Song::HasInstrumentTrack(), Song::HasJacket(), Song::HasLyrics(), Song::HasMusic(), Song::HasPreviewVid(), FontPage::Load(), Profile::LoadEditableDataFromDir(), XMLProfile::LoadEttFromDir(), Sprite::LoadFromCached(), Banner::LoadFromCachedBanner(), FadingBanner::LoadFromCachedBanner(), Model::LoadMaterialsFromMilkshapeAscii(), XMLProfile::LoadStatsFromDir(), XMLProfile::LoadStatsXmlForConversion(), MountTreeOfZips(), Profile::SaveMachinePublicKeyToDir(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), Song::SaveToSSCFile(), CryptManager::Sign(), StartMusic(), and SMLoader::TidyUpData().
IsAnInt()
bool IsAnInt (const RString & s)
Referenced by GameState::ApplyCmdline(), ActorFrame::LoadChildrenFromNode(), and Font::LoadFontPageSettings().
IsHexVal()
bool IsHexVal (const RString & s)
Referenced by HexToBinary(), and Font::LoadFontPageSettings().
join() [1/2]
RString join (const RString & sDelimitor, const vector< RString > & sSource)
join() [2/2]
RString join (const RString & sDelimitor, vector< RString >::const_iterator begin, vector< RString >::const_iterator end)
lerp()
template<typename T , typename U > U lerp (T x, U l, U h)
Referenced by Steps::GetMSD(), SampleHistory::GetSampleNum(), lerp_rage_color(), BitmapText::BMT_TweenState::MakeWeightedAverage(), ActorMultiVertex::AMV_TweenState::MakeWeightedAverage(), Actor::TweenState::MakeWeightedAverage(), RageFastSin(), CubicSplineN::weighted_average(), and WeightedAvergeOfRSVs().
luajoin() [1/2]
std::string luajoin (const std::string & sDelimitor, const vector< std::string > & sSource)
Referenced by GetLuaStack().
luajoin() [2/2]
std::string luajoin (const std::string & sDelimitor, vector< std::string >::const_iterator begin, vector< std::string >::const_iterator end)
MakeLower() [1/2]
void MakeLower (char * p, size_t iLen)
MakeLower() [2/2]
void MakeLower (wchar_t * p, size_t iLen)
MakeUpper() [1/2]
void MakeUpper (char * p, size_t iLen)
MakeUpper() [2/2]
void MakeUpper (wchar_t * p, size_t iLen)
MakeValidFilename()
void MakeValidFilename (RString & sName)
References L, RStringToWstring(), w, and WStringToRString().
Referenced by NotesWriterSM::GetEditFileName(), and NotesWriterSSC::GetEditFileName().
max() [1/4]
float max (float a, int b) inline
Referenced by NoteData::AddHoldNote(), RageSoundReader_Split::AddSourceChannelToSound(), ProfileManager::AddStepsScore(), ScoreManager::AggregateSSRs(), RageCompiledGeometrySWD3D::Allocate(), RageCompiledGeometrySWOGL::Allocate(), blit_rgba_to_rgba(), RageSoundReader_ThreadedBuffer::BufferingThread(), BitmapText::BuildChars(), ImageCache::CacheImageInternal(), RageSoundDriver::ClampHardwareFrame(), GameState::CommitStageStats(), RageBitmapTexture::Create(), ProfileManager::CreateLocalProfile(), WavReaderADPCM::DecodeADPCMBlock(), ScreenSelectMaster::DoMenuStart(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldBodyInternal(), NoteDisplay::DrawHoldPart(), RollingNumbers::DrawPrimitives(), RageDisplay_D3D::DrawQuadsInternal(), RageDisplay_D3D::DrawQuadStripInternal(), RageDisplay_D3D::DrawSymmetricQuadStripInternal(), RageDisplay_Legacy::DrawSymmetricQuadStripInternal(), NoteField::FadeToFail(), LunaPacklist::FilterAndSearch(), FindLongestOverlappingHoldNoteForAnyTrack(), RageSurfaceUtils::FindSurfaceTraits(), RageSoundReader_Chain::Finish(), RageSoundReader_Merge::Finish(), Steps::GenerateChartKey(), DSoundBuf::get_output_buf(), TimingData::GetActualBPM(), RageSoundReader_Extend::GetData(), GetDisplayedBeat(), NoteDataUtil::GetETTNoteDataString(), PlayerStageStats::GetGrade(), GameState::GetHardestStepsDifficulty(), NoteData::GetLastRow(), RageSoundReader_Merge::GetLength(), RageSoundReader_Chain::GetLength(), WavReaderADPCM::GetLength(), RageSoundReader_Merge::GetLength_Fast(), RageSoundReader_Chain::GetLength_Fast(), InputMapper::GetLevel(), Font::GetLineHeightInSourcePixels(), Player::GetMaxStepDistanceSeconds(), DisplayBpms::GetMaxWithin(), Style::GetMinAndMaxColX(), ScreenGameplay::GetMusicEndTiming(), RageSoundReader_Pan::GetNumChannels(), Alsa9Buf::GetNumFramesToFill(), GetNumNotesFromBeginning(), GameState::GetNumStagesForCurrentSongAndStepsOrCourse(), Model::GetNumStates(), SongUtil::GetPlayableStepsTypes(), DSoundBuf::GetPosition(), ScoreKeeperNormal::GetPossibleDancePoints(), ScoreKeeperNormal::GetPossibleGradePoints(), NoteDataUtil::GetPrevEditorPosition(), NoteData::GetPrevTapNoteRowForAllTracks(), ActorMultiVertex::AMV_TweenState::GetSafeNumToDraw(), InputMapper::GetSecsHeld(), TimingData::GetSegmentIndexAtRow(), NoteDataUtil::GetSMNoteDataString(), PlayerAI::GetTapNoteScoreForReplay(), ActorFrame::GetTweenTimeLeft(), LunaStatsManager::GetWorstGrade(), RageSoundReader_MP3::handle_first_frame(), Player::HandleTapRowScore(), DSoundBuf::Init(), Player::Init(), SongManager::InitSongsFromDisk(), ScreenContinue::Input(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), NoteDataUtil::InsertIntelligentTaps(), StdString::CStdStr< CT >::Left(), Profile::LoadAllFromDir(), LoadBMP(), SongCacheIndex::LoadCache(), LoadFromKSFFile(), BackgroundImpl::LoadFromRandom(), SongCacheIndex::LoadHyperCache(), msAnimation::LoadMilkshapeAsciiBones(), OsuLoader::LoadNoteDataFromParsedData(), SongManager::LoadStepManiaSongDir(), PlayerStageStats::MakePercentScore(), mediancut(), ScreenSelectMaster::MenuStart(), WinWdmStream::Open(), EzSockets::PeekPack(), GameplayAssist::PlayTicks(), ScreenOptions::PositionRows(), RageSoundResampler_Polyphase::RageSoundResampler_Polyphase(), RageVec3AddToBounds(), random_up_to(), CircBuf< RageSoundDriver::sound_block >::read(), RageSoundSplitterImpl::ReadBuffer(), Model::RecalcAnimationLengthSeconds(), Song::ReCalculateRadarValuesAndLastSecond(), ScoreManager::RecalculateSSRs(), NoteDataUtil::RemoveSimultaneousNotes(), JudgedRows::Resize(), StdString::CStdStr< CT >::Right(), Sprite::ScaleToClipped(), Player::ScoreAllActiveHoldsLetGo(), RageFileDriverZip::SeekToEndCentralRecord(), MusicWheel::Select(), ScreenSelectMusic::SelectCurrent(), ScreenGameplay::SendCrossedMessages(), ComboGraph::Set(), BPMDisplay::SetBPMRange(), Checkpoints::SetCheckpoint(), OptionListRow::SetFromHandler(), StepsDisplay::SetInternal(), PlayerStageStats::SetLifeRecordAt(), setmax(), ColorBitmapText::SetMaxLines(), RageSoundReader_Extend::SetPosition(), RageSoundReader_MP3::SetPosition_toc(), OsuLoader::SetTimingData(), DSoundBuf::SetVolume(), PlayerStageStats::SetWifeRecordAt(), TimingData::ShiftRange(), ScreenGameplay::StartPlayingSong(), ScreenWithMenuElements::StartTransitioningScreen(), RageSoundReader_SpeedChange::Step(), Player::Step(), ScreenTextEntry::TryAppendToAnswer(), LyricDisplay::Update(), ArrowEffects::Update(), Foreground::Update(), GameSoundManager::Update(), MenuTimer::Update(), LifeMeterTime::Update(), HelpDisplay::Update(), Sprite::Update(), WheelBase::Update(), Screen::Update(), ActorMultiVertex::Update(), ScreenTextEntry::UpdateAnswerText(), InputHandler_DInput::UpdateBuffered(), PlayerStageStats::UpdateComboList(), BackgroundImpl::Layer::UpdateCurBGChange(), Player::UpdateHoldNotes(), ScreenPackages::UpdateLinksList(), ScreenPackages::UpdatePackagesList(), InputHandler_DInput::UpdatePolled(), StepsDisplayList::UpdatePositions(), CircBuf< RageSoundDriver::sound_block >::write(), and RageSoundDriver::~RageSoundDriver().
max() [2/4]
float max (int a, float b) inline
max() [3/4]
unsigned long max (unsigned int a, unsigned long b) inline
max() [4/4]
unsigned long max (unsigned long a, unsigned int b) inline
min() [1/4]
float min (float a, int b) inline
Referenced by HighScoreList::AddHighScore(), NoteData::AddHoldNote(), SampleHistory::AddSample(), ScoresAtRate::AddScore(), ScoresForChart::AddScore(), RageLog::AddToInfo(), RageTextureManager::AdjustTextureID(), RageSurfaceUtils::Blit(), ImageCache::CacheImageInternal(), LifeMeterBar::ChangeLife(), CompareNotesPointersForExtra(), RageBitmapTexture::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), WavReaderADPCM::DecodeADPCMBlock(), do_split(), NoteDisplay::DrawHoldPart(), BitmapText::DrawPrimitives(), NoteDataUtil::Echo(), InputQueueCode::EnteredCode(), RageSoundReader_ThreadedBuffer::FillBlock(), MusicWheel::FilterWheelItemDatas(), FindDisplayedBeats(), Steps::GenerateBustedChartKey(), DSoundBuf::get_output_buf(), TimingData::GetActualBPM(), RageLog::GetAdditionalLog(), LunaStatsManager::GetBestFinalGrade(), LunaStatsManager::GetBestGrade(), RageSoundReader_SpeedChange::GetCursorAvail(), RageSoundResampler_Polyphase::GetCutoffFrequency(), RageSoundReader_Extend::GetData(), GameState::GetEasiestStepsDifficulty(), NoteData::GetFirstRow(), GameSoundManager::GetFrameTimingAdjustment(), DisplayBpms::GetMin(), Style::GetMinAndMaxColX(), StageStats::GetMinimumMissCombo(), NoteDataUtil::GetNextEditorPosition(), NoteData::GetNextTapNoteRowForAllTracks(), SampleHistory::GetSampleNum(), TimingData::GetSegmentIndexAtRow(), ArrowEffects::GetXPos(), ScoreKeeperNormal::HandleComboInternal(), ScoreKeeperNormal::HandleRowComboInternal(), ScoreKeeperNormal::HandleTapRowScore(), DSoundBuf::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), NoteDataUtil::InsertIntelligentTaps(), StdString::CStdStr< CT >::Left(), AutoKeysounds::LoadAutoplaySoundsInto(), OsuLoader::LoadChartData(), BGAnimationLayer::LoadFromAniLayerFile(), SMLoader::LoadFromBGChangesString(), ScoresAtRate::LoadFromNode(), ScoresForChart::LoadFromNode(), HighScoreList::LoadFromNode(), BackgroundImpl::LoadFromRandom(), BackgroundImpl::LoadFromSong(), OsuLoader::LoadNoteDataFromParsedData(), DBProfile::LoadPlayerScores(), RandomSample::LoadSoundDir(), mediancut(), NoteDataWithScoring::MinTapNoteScore(), RageSoundDriver::MixIntoBuffer(), LifeMeterBattery::OnSongEnded(), overratedness(), RageSurfaceUtils::Palettize(), RageSurfaceUtils::PalettizeToGrayscale(), ScreenOptions::PositionRows(), RageFile_JPEG_skip_input_data(), RageVec3AddToBounds(), RageSoundReader_Extend::Read(), RageSoundReader_SpeedChange::Read(), RageSoundReader_Vorbisfile::Read(), RageSoundReader_Preload::Read(), RageSoundReader_Merge::Read(), RageSoundReader_Split::Read(), RageSoundReader_ThreadedBuffer::Read(), RageSoundReader_MP3::Read(), RageSoundReader_Chain::Read(), RageFileObj::Read(), WavReaderPCM::Read(), CircBuf< RageSoundDriver::sound_block >::read(), RageSoundSplitterImpl::ReadBuffer(), RageFileDriverSlice::ReadInternal(), RageFileObjMem::ReadInternal(), RageFileObjInflate::ReadInternal(), RageFileDriverReadAhead::ReadInternal(), Song::ReCalculateRadarValuesAndLastSecond(), ScreenMapControllers::Refresh(), ColorBitmapText::ResetText(), StdString::CStdStr< CT >::Right(), SecondsToMMSSMsMs(), SecondsToMMSSMsMsMs(), SecondsToMSSMsMs(), RageFileDriverSlice::SeekInternal(), RageFileObjInflate::SeekInternal(), BPMDisplay::SetBPMRange(), FontPage::SetExtraPixels(), WheelNotifyIcon::SetFlags(), StepsDisplay::SetInternal(), PlayerStageStats::SetLifeRecordAt(), ColorBitmapText::SetMaxLines(), setmin(), SetStepsDisplayBPM(), ColorBitmapText::SetText(), PlayerStageStats::SetWifeRecordAt(), TimingData::ShiftRange(), SlideDuplicateDifficulties(), MenuTimer::Stall(), StartMusic(), RageSoundReader_SpeedChange::Step(), Player::Step(), RadarValues::ToString(), ArrowEffects::Update(), NoteField::Update(), WheelBase::Update(), Player::Update(), GrooveRadar::GrooveRadarValueMap::Update(), PlayerStageStats::UpdateComboList(), OptionRow::UpdateEnabledDisabled(), Player::UpdateHoldNotes(), ScreenPackages::UpdateLinksList(), RageLog::UpdateMappedLog(), ScreenPackages::UpdatePackagesList(), StepsDisplayList::UpdatePositions(), OptionRow::UpdateText(), Actor::UpdateTweening(), RageTextureManager::VolatileTexture(), and CircBuf< RageSoundDriver::sound_block >::write().
min() [2/4]
float min (int a, float b) inline
min() [3/4]
unsigned long min (unsigned int a, unsigned long b) inline
min() [4/4]
unsigned long min (unsigned long a, unsigned int b) inline
operator>>()
template<class T > bool operator>> (const RString & lhs, T & rhs)
power_of_two()
int power_of_two (int input)
Referenced by ImageCache::CacheImageInternal(), RageBitmapTexture::Create(), MovieTexture_DShow::Create(), RenderTarget_MacOSX::Create(), ImageTexture::Create(), RenderTarget_Win32::Create(), RenderTarget_X11::Create(), D3DRenderTarget_FramebufferObject::Create(), RenderTarget_FramebufferObject::Create(), RageDisplay_D3D::CreateTexture(), RageDisplay_Legacy::CreateTexture(), MovieTexture_Generic::CreateTexture(), and MovieTexture_Null::MovieTexture_Null().
PrettyPercent() [1/2]
RString PrettyPercent (float fNumerator, float fDenominator)
References ssprintf().
Referenced by PrettyPercent().
PrettyPercent() [2/2]
RString PrettyPercent (int fNumerator, int fDenominator) inline
References PrettyPercent().
Quantize() [1/2]
float Quantize (const float f, const float fRoundInterval) inline
Referenced by ArrowGetPercentVisible(), NoteDataUtil::Echo(), AdjustSync::GetSyncChangeTextGlobal(), AdjustSync::GetSyncChangeTextSong(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::SnapToNearestNoteType(), and NoteDataUtil::Wide().
Quantize() [2/2]
int Quantize (const int i, const int iRoundInterval) inline
QuantizeDown() [1/2]
int QuantizeDown (int i, int iInterval) inline
Referenced by NoteDisplay::SetActiveFrame(), and LuaExpressionTransform::TransformItemCached().
QuantizeDown() [2/2]
float QuantizeDown (float i, float iInterval) inline
QuantizeUp() [1/2]
int QuantizeUp (int i, int iInterval) inline
Referenced by DSoundBuf::get_output_buf(), WavReaderPCM::Init(), WavReaderPCM::Read(), and LuaExpressionTransform::TransformItemCached().
QuantizeUp() [2/2]
float QuantizeUp (float i, float iInterval) inline
random_up_to() [1/2]
int random_up_to (RandomGen & rng, int limit) inline
References max().
Referenced by bmsCommandTree::doStatement(), FillProfileStats(), ScreenEvaluation::Init(), random_up_to(), and RandomInt().
random_up_to() [2/2]
int random_up_to (int limit) inline
References g_RandomNumberGenerator, and random_up_to().
randomf()
float randomf (const float low = -1.0f, const float high = 1.0f) inline
References RandomFloat().
Referenced by FillProfileStats(), TapScoreDistribution::GetTapNoteScore(), ScreenEvaluation::Init(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), MakeRandomHighScore(), Actor::PreDraw(), Player::Step(), and MusicWheel::UpdateSwitch().
RandomFloat() [1/2]
float RandomFloat () inline
Generate a random float between 0 inclusive and 1 exclusive.
Returns
the random float.
References g_RandomNumberGenerator.
Referenced by PlayerOptions::ChooseRandomModifiers(), randomf(), RandomFloat(), and BPMDisplay::Update().
RandomFloat() [2/2]
float RandomFloat (float fLow, float fHigh) inline
Return a float between the low and high values.
Parameters
fLow the low value, inclusive.
fHigh the high value, inclusive.
Returns
the random float.
References f, RandomFloat(), and SCALE.
RandomInt() [1/2]
int RandomInt (int low, int high) inline
References g_RandomNumberGenerator, and random_up_to().
Referenced by PlayerOptions::ChooseRandomModifiers(), DoPlayOnceFromDir(), RandomSample::GetNextToPlay(), MusicWheel::GetPreferredSelectionForRandomOrPortal(), CharacterManager::GetRandomCharacter(), GetRandomFileInDir(), ScreenEvaluation::Init(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), MakeRandomHighScore(), Neg1OrPos1(), MusicWheel::Select(), SuperShuffleTaps(), and DancingCharacters::Update().
RandomInt() [2/2]
int RandomInt (int n) inline
References g_RandomNumberGenerator, and random_up_to().
RemoveIf()
template<typename Container , typename Predicate > void RemoveIf (Container & c, Predicate p)
Referenced by StripCvsAndSvn(), and StripMacResourceForks().
RemoveIfEqual()
template<typename Container , typename Value > void RemoveIfEqual (Container & c, const Value & v)
Replace_Unicode_Markers()
void Replace_Unicode_Markers (RString & Text)
References INVALID_CHAR, and WcharToUTF8().
Referenced by FontCharAliases::ReplaceMarkers().
ReplaceEntityText() [1/2]
void ReplaceEntityText (RString & sText, const map< RString, RString > & m)
References StdString::CStdStr< CT >::MakeLower().
Referenced by FontCharAliases::ReplaceMarkers().
ReplaceEntityText() [2/2]
void ReplaceEntityText (RString & sText, const map< char, RString > & m)
References ASSERT, and FOREACHM_CONST.
RStringToWstring()
wstring RStringToWstring (const RString & sString)
References picosha2::detail::ch(), INVALID_CHAR, L, and utf8_to_wchar().
Referenced by ScreenTextEntry::BeginScreen(), MovieTexture_DShow::Create(), Profile::LoadEditableDataFromDir(), Font::LoadFontPageSettings(), MakeValidFilename(), BitmapText::SetTextInternal(), ColorBitmapText::SimpleAddLine(), BitmapText::StringWillUseAlternate(), and ScreenTextEntry::TryAppendToAnswer().
SecondsToHHMMSS()
RString SecondsToHHMMSS (float fSecs)
References ssprintf().
SecondsToMMSS()
RString SecondsToMMSS (float fSecs)
References ssprintf().
Referenced by SongUtil::GetSectionNameFromSongAndSort().
SecondsToMMSSMsMs()
RString SecondsToMMSSMsMs (float fSecs)
References min(), and ssprintf().
Referenced by ScreenEvaluation::Init(), ScoreDisplayOni::Update(), and ScoreDisplayAliveTime::UpdateNumber().
SecondsToMMSSMsMsMs()
RString SecondsToMMSSMsMsMs (float fSecs)
References min(), and ssprintf().
Referenced by DebugLineUptime::GetDisplayValue(), and RageLog::Write().
SecondsToMSS()
RString SecondsToMSS (float fSecs)
References ssprintf().
SecondsToMSSMsMs()
RString SecondsToMSSMsMs (float fSecs)
References min(), and ssprintf().
Referenced by ScoreDisplayLifeTime::Update().
seed_lua_prng()
void seed_lua_prng ()
Referenced by sm_main().
SetCommandlineArguments()
void SetCommandlineArguments (int argc, char ** argv)
Referenced by sm_main().
SetExtension()
RString SetExtension (const RString & path, const RString & ext)
References splitpath().
Referenced by BMSSong::AllocateKeysound(), BMSSong::GetBackground(), Song::GetFileHash(), Font::GetFontPaths(), Song::HasAutosaveFile(), actor_template_t::load_node(), GameSoundManager::PlayMusic(), BMSSong::PrecacheBackgrounds(), Song::RemoveAutosave(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), and Song::SaveToSSCFile().
SmEscape() [1/2]
RString SmEscape (const RString & sUnescaped)
References SmEscape().
Referenced by emplace_back_tag(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), SmEscape(), BackgroundChange::ToString(), write_tag(), and WriteGlobalTags().
SmEscape() [2/2]
RString SmEscape (const char * cUnescaped, int len)
SortRStringArray()
void SortRStringArray (vector< RString > & asAddTo, const bool bSortAscending = true)
References CompareRStringsAsc(), and CompareRStringsDesc().
Referenced by SongManager::DifferentialReloadDir(), ScreenSelectLanguage::Init(), Language(), LanguageChoices(), BGAnimation::LoadFromAniDir(), SongManager::LoadStepManiaSongDir(), and ThemeManager::RunLuaScripts().
split() [1/6]
void split (const RString & sSource, const RString & sDelimitor, vector< RString > & asAddIt, const bool bIgnoreEmpty = true)
References do_split().
Referenced by HHMMSSToSeconds().
split() [2/6]
void split (const wstring & sSource, const wstring & sDelimitor, vector< wstring > & asAddIt, const bool bIgnoreEmpty = true)
References do_split().
split() [3/6]
void split (const RString & sSource, const RString & sDelimitor, int & iBegin, int & iSize, bool bIgnoreEmpty = true)
References do_split().
split() [4/6]
void split (const wstring & sSource, const wstring & sDelimitor, int & iBegin, int & iSize, bool bIgnoreEmpty = true)
References do_split().
split() [5/6]
void split (const RString & sSource, const RString & sDelimitor, int & iBegin, int & iSize, int iLen, bool bIgnoreEmpty)
References do_split().
split() [6/6]
void split (const wstring & sSource, const wstring & sDelimitor, int & iBegin, int & iSize, int iLen, bool bIgnoreEmpty)
References do_split().
splitpath()
void splitpath (const RString & Path, RString & Dir, RString & Filename, RString & Ext)
References ASSERT, and Regex::Compare().
Referenced by CharacterManager::CharacterManager(), GetFileNameWithoutExtension(), RageMovieTexture::GetFourCC(), DownloadManager::InstallSmzip(), InstallSmzipOsArg(), LoadFromKSFFile(), Nsis(), and SetExtension().
ssprintf()
RString ssprintf (const char * fmt, ...)
StringToFloat() [1/2]
float StringToFloat (const RString & sString)
Referenced by ScreenTextEntry::FloatValidate(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), NoteSkinManager::GetMetricF(), XNodeStringValue::GetValue(), HHMMSSToSeconds(), BMSChart::Load(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromKSFFile(), Chart::LoadFromNode(), HighScoreImpl::LoadFromNode(), SMALoader::LoadFromSimfile(), LoadGlobalData(), SSCLoader::LoadNoteDataFromSimfile(), SSC::msdsplit(), HighScoreImpl::OffsetsToVector(), SMLoader::ParseBPMs(), ParseBrokenDWITimestamp(), SMLoader::ParseStops(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessBPMs(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SSCLoader::ProcessLabels(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SSCLoader::ProcessWarps(), BMSChartReader::ReadHeaders(), BMSChartReader::ReadNoteData(), SMLoader::RowToBeat(), SetDisplayBPM(), SetFirstSecond(), SetLastSecond(), SetLastSecondHint(), SetMusicLength(), SetOffset(), SetStepsDisplayBPM(), SetStepsOffset(), SetStepsVersion(), SetupExtensions(), SetVersion(), SMSetDisplayBPM(), and SMSetOffset().
StringToFloat() [2/2]
bool StringToFloat (const RString & sString, float & fOut)
StringToInt()
int StringToInt (const RString & sString)
Have a standard way of converting Strings to integers.
Parameters
sString the string to convert.
Returns
the integer we are after.
Referenced by GameState::ApplyCmdline(), bmsCommandTree::doStatement(), PlayerOptions::FromOneModString(), RadarValues::FromString(), StringConversion::FromString< bool >(), RageTexture::GetFrameDimensionsFromFileName(), NoteSkinManager::GetMetricB(), NoteSkinManager::GetMetricI(), GetResolutionFromFileName(), XNodeStringValue::GetValue(), HHMMSSToSeconds(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), actor_template_t::load_frames_from_file(), Font::LoadFontPageSettings(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromDWITokens(), LoadFromKSFFile(), BGAnimationLayer::LoadFromNode(), ScoresForChart::LoadFromNode(), HighScoreImpl::LoadFromNode(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), OptionRowHandlerList::LoadInternal(), DWILoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), Profile::MakeUniqueFileNameNoExtension(), HighScoreImpl::NoteRowsToVector(), FileTransfer::ParseHTTPAddress(), ScreenPackages::ParseHTTPAddress(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessCombos(), SMALoader::ProcessMultipliers(), SMLoader::ProcessSpeeds(), ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), BMSChartReader::ReadHeaders(), ScreenGameplay::SaveReplay(), SetHasBanner(), SetHasMusic(), SetMeter(), SetRadarValues(), SetSelectable(), SMSetSelectable(), and SongCacheIndex::SongFromStatement().
StripCrnl()
void StripCrnl (RString & sStr)
Referenced by GetFileContents(), BMSChart::Load(), LoadFromKSFFile(), LyricsLoader::LoadFromLRCFile(), and LoadGlobalData().
StripCvsAndSvn()
void StripCvsAndSvn (vector< RString > & vs)
References CVSOrSVN(), and RemoveIf().
StripMacResourceForks()
void StripMacResourceForks (vector< RString > & vs)
References MacResourceFork(), and RemoveIf().
Referenced by ScreenOptionsExportPackageSubPage::BeginScreen(), CharacterManager::CharacterManager(), SongManager::DifferentialReloadDir(), NoteSkinManager::GetAllNoteSkinNamesForGame(), AnnouncerManager::GetAnnouncerNames(), RageFileManager::GetDirListing(), ThemeManager::GetThemeNames(), SongManager::LoadStepManiaSongDir(), NoteSkinManager::RefreshNoteSkinData(), and ThemeManager::RunLuaScripts().
Swap16()
uint16_t Swap16 (uint16_t n) inline
Referenced by Swap16LE().
Swap16BE()
uint16_t Swap16BE (uint16_t n) inline
Swap16LE()
uint16_t Swap16LE (uint16_t n) inline
References Swap16().
Referenced by LoadBMP(), FileReading::read_16_le(), FileReading::read_u16_le(), and write_le16().
Swap24()
uint32_t Swap24 (uint32_t n) inline
References Swap32().
Referenced by FixLilEndian(), FixLittleEndian(), and Swap24LE().
Swap24BE()
uint32_t Swap24BE (uint32_t n) inline
Referenced by RageSurface_Load_JPEG(), and RageSurfaceUtils::SaveJPEG().
Swap24LE()
uint32_t Swap24LE (uint32_t n) inline
References Swap24().
Referenced by LoadBMP(), and RageSurfaceUtils::SaveBMP().
Swap32()
uint32_t Swap32 (uint32_t n) inline
Referenced by FixLilEndian(), FixLittleEndian(), Swap24(), and Swap32LE().
Swap32BE()
uint32_t Swap32BE (uint32_t n) inline
Referenced by RageSurfaceUtils::Palettize(), and RageSurface_Save_PNG().
Swap32LE()
uint32_t Swap32LE (uint32_t n) inline
References Swap32().
Referenced by RageFileObjGzip::Finish(), LoadBMP(), FileReading::read_32_le(), FileReading::read_u32_le(), and write_le32().
Trim()
void Trim (RString & sStr, const char * szTrim = "\\")
Referenced by FixupPath(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), NetworkSyncManager::GetCurrentSMBuild(), Command::GetName(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), SMALoader::ProcessSpeeds(), IniFile::ReadFile(), SMLoader::RowToBeat(), SetChartName(), SetCredit(), SetDescription(), SongCacheIndex::SongFromStatement(), Song::TidyUpData(), BackgroundImpl::Layer::UpdateCurBGChange(), and RageLog::~RageLog().
TrimLeft()
void TrimLeft (RString & sStr, const char * szTrim = "\\")
Referenced by GetETTNoteData(), GetSSCNoteData(), Font::LoadFontPageSettings(), LoadFromKSFFile(), LoadGlobalData(), and SongManager::UpdatePreferredSort().
TrimRight()
void TrimRight (RString & sStr, const char * szTrim = "\\")
Referenced by GetInfoLog(), JoinLineList(), SSCLoader::ProcessLabels(), and SongManager::UpdatePreferredSort().
URLEncode()
RString URLEncode (const RString & sStr)
References ssprintf().
Referenced by ScreenPackages::EnterURL(), and FileTransfer::StartTransfer().
utf8_get_char()
wchar_t utf8_get_char (const RString & s)
References INVALID_CHAR, and utf8_to_wchar_ec().
utf8_get_char_len()
int utf8_get_char_len (char p)
Given a UTF-8 byte, return the length of the codepoint.
Referenced by utf8_to_wchar(), and utf8_to_wchar_ec().
utf8_is_valid()
bool utf8_is_valid (const RString & s)
References picosha2::detail::ch(), and utf8_to_wchar_ec().
utf8_remove_bom()
void utf8_remove_bom (RString & s)
utf8_to_wchar()
bool utf8_to_wchar (const char * s, size_t iLength, unsigned & start, wchar_t & ch)
Decode a code point and place within the output variable.
This variant only does enough error checking to prevent crashing.
Returns
true if a valid encoded string was found.
References L, and utf8_get_char_len().
Referenced by RStringToWstring().
utf8_to_wchar_ec()
bool utf8_to_wchar_ec (const RString & s, unsigned & start, wchar_t & ch)
References is_utf8_continuation_byte(), and utf8_get_char_len().
Referenced by utf8_get_char(), utf8_is_valid(), and utf8_sanitize().
vssprintf()
RString RString vssprintf (const char * fmt, va_list argList)
References FMT_BLOCK_SIZE.
Referenced by averr_ssprintf(), Alsa9Buf::ErrorHandler(), RageLog::Info(), RageLog::MapLog(), ov_ssprintf(), ssprintf(), RageException::Throw(), RageLog::Time(), RageLog::Trace(), RageLog::UserLog(), RageLog::Warn(), and wo_ssprintf().
wchar_to_utf8()
void wchar_to_utf8 (wchar_t ch, RString & out)
Referenced by utf8_sanitize(), WcharToUTF8(), and WStringToRString().
WcharDisplayText()
RString WcharDisplayText (wchar_t c)
References ssprintf().
Referenced by Font::Load().
WcharToUTF8()
RString WcharToUTF8 (wchar_t c)
References wchar_to_utf8().
Referenced by InitCharAliases(), and Replace_Unicode_Markers().
wife2()
float wife2 (float maxms, float ts) inline
Referenced by HighScore::ConvertDpToWife(), HighScore::RescoreToWifeJudge(), HighScore::RescoreToWifeJudgeDuringLoad(), HighScoreImpl::RescoreToWifeTS(), and Player::SetJudgment().
wrap() [1/3]
void wrap (int & x, int n) inline
Referenced by Model::AdvanceFrame(), FadingBanner::BeforeChange(), WheelBase::ChangeMusic(), MusicWheel::ChangeMusic(), ScreenSelectMusic::ChangeSteps(), ScreenOptions::ChangeValueInRowRelative(), DSoundBuf::CheckUnderrun(), DSoundBuf::CheckWriteahead(), DebugLineAutosync::DoAndLog(), FadingBanner::DrawPrimitives(), WheelBase::FirstVisibleIndex(), DSoundBuf::get_output_buf(), SongManager::GetRandomSong(), SampleHistory::GetSampleNum(), HourInDayToLocalizedString(), ScreenSelectMaster::Init(), OptionsList::Input(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), FadingBanner::Load(), NoteDataUtil::LoadOverlapped(), ScreenOptions::MoveRowRelative(), ScreenTextEntryVisual::MoveX(), ScreenTextEntryVisual::MoveY(), MusicWheel::NextSort(), ActorScroller::PositionItemsAndDrawPrimitives(), WheelBase::RebuildWheelItems(), NoteDisplay::SetActiveFrame(), ScrollBar::SetPercentage(), DynamicActorScroller::ShiftSubActors(), NoteDataUtil::ShiftTracks(), NoteField::Update(), Sprite::Update(), ActorMultiVertex::Update(), and Actor::UpdateInternal().
wrap() [2/3]
void wrap (unsigned & x, unsigned n) inline
wrap() [3/3]
void wrap (float & x, float n) inline
WStringToRString()
RString WStringToRString (const wstring & sString)
References wchar_to_utf8().
Referenced by ScreenTextEntry::End(), MovieTexture_DShow::GetActiveFilterList(), ArchHooks_Win32::GetClipboard(), InputHandler::GetDeviceSpecificInputString(), InputHandler::GetLocalizedInputString(), GetVideoCodecDebugInfo(), ScreenNetSelectBase::Input(), ScreenTextEntry::Input(), Profile::LoadEditableDataFromDir(), MakeValidFilename(), ScreenTextEntry::TryAppendToAnswer(), and ScreenTextEntry::UpdateAnswerText().
Variable Documentation
g_argc
int g_argc
Referenced by ArchHooks_Win32::ArchHooks_Win32(), GetCommandlineArgument(), GetCommandLineArguments(), CommandLineActions::Handle(), ArchHooks_Unix::Init(), ArchHooks_MacOSX::Init(), LoadingWindow_Gtk::Init(), and WriteLogHeader().
g_argv
char** g_argv
Referenced by ArchHooks_Win32::ArchHooks_Win32(), GetCommandLineArguments(), CommandLineActions::Handle(), ArchHooks_Unix::Init(), ArchHooks_MacOSX::Init(), LoadingWindow_Gtk::Init(), and WriteLogHeader().
g_LowerCase
unsigned char g_LowerCase[256]
g_RandomNumberGenerator
RandomGen g_RandomNumberGenerator
Referenced by bmsCommandTree::doStatement(), RandomSample::LoadSoundDir(), random_up_to(), RandomFloat(), RandomInt(), GameState::Reset(), GameState::ResetStageStatistics(), GameState::SetNewStageSeed(), sm_main(), and SongManager::UpdateShuffled().
g_UpperCase
unsigned char g_UpperCase[256]
Referenced by char_traits_char_nocase::eq(), char_traits_char_nocase::fasttoupper(), char_traits_char_nocase::lt(), and char_traits_char_nocase::ne().
INVALID_CHAR
const wchar_t INVALID_CHAR
Referenced by InitCharAliases(), Replace_Unicode_Markers(), RStringToWstring(), utf8_get_char(), and utf8_sanitize().