Etterna: StdString::CStdStr< CT > Class Template Reference
StdString::CStdStr< CT > Class Template Reference
Our wrapper for std::string.
#include <StdString.h>
Public Member Functions
CStdStr ()
CStdStr (const MYTYPE &str)
CStdStr (const std::string &str)
CStdStr (PCMYSTR pT, MYSIZE n)
CStdStr (PCSTR pA)
CStdStr (MYCITER first, MYCITER last)
CStdStr (MYSIZE nSize, MYVAL ch, const MYALLOC &al=MYALLOC())
MYTYPE & operator= (const MYTYPE &str)
MYTYPE & operator= (const std::string &str)
MYTYPE & operator= (PCSTR pA)
MYTYPE & operator= (CT t)
MYTYPE & operator+= (const MYTYPE &str)
MYTYPE & operator+= (const std::string &str)
MYTYPE & operator+= (PCSTR pA)
MYTYPE & operator+= (CT t)
MYTYPE & MakeUpper ()
MYTYPE & MakeLower ()
CT * GetBuffer (int nMinLen=-1)
void ReleaseBuffer (int nNewLen=-1)
int CompareNoCase (PCMYSTR szThat) const
bool EqualsNoCase (PCMYSTR szThat) const
MYTYPE Left (int nCount) const
int Replace (CT chOld, CT chNew)
int Replace (PCMYSTR szOld, PCMYSTR szNew)
MYTYPE Right (int nCount) const
CT & operator[] (int nIdx)
const CT & operator[] (int nIdx) const
CT & operator[] (unsigned int nIdx)
const CT & operator[] (unsigned int nIdx) const
CT & operator[] (long unsigned int nIdx)
const CT & operator[] (long unsigned int nIdx) const
CT & operator[] (long long unsigned int nIdx)
const CT & operator[] (long long unsigned int nIdx) const
operator const CT * () const
Private Types
typedef std::basic_string< CT > MYBASE
typedef CStdStr< CT > MYTYPE
typedef MYBASE::const_pointer PCMYSTR
typedef MYBASE::pointer PMYSTR
typedef MYBASE::iterator MYITER
typedef MYBASE::const_iterator MYCITER
typedef MYBASE::reverse_iterator MYRITER
typedef MYBASE::size_type MYSIZE
typedef MYBASE::value_type MYVAL
typedef MYBASE::allocator_type MYALLOC
typedef MYBASE::traits_type MYTRAITS
Friends
MYTYPE operator+EMP_TEMP (const MYTYPE &str1, const MYTYPE &str2)
MYTYPE operator+EMP_TEMP (const MYTYPE &str, CT t)
MYTYPE operator+EMP_TEMP (const MYTYPE &str, PCSTR sz)
MYTYPE operator+EMP_TEMP (PCSTR pA, const MYTYPE &str)
Detailed Description
template<typename CT>
class StdString::CStdStr< CT >
Our wrapper for std::string.
Member Typedef Documentation
MYALLOC
template<typename CT> typedef MYBASE::allocator_type StdString::CStdStr< CT >::MYALLOC private
MYBASE
template<typename CT> typedef std::basic_string<CT> StdString::CStdStr< CT >::MYBASE private
MYCITER
template<typename CT> typedef MYBASE::const_iterator StdString::CStdStr< CT >::MYCITER private
MYITER
template<typename CT> typedef MYBASE::iterator StdString::CStdStr< CT >::MYITER private
MYRITER
template<typename CT> typedef MYBASE::reverse_iterator StdString::CStdStr< CT >::MYRITER private
MYSIZE
template<typename CT> typedef MYBASE::size_type StdString::CStdStr< CT >::MYSIZE private
MYTRAITS
template<typename CT> typedef MYBASE::traits_type StdString::CStdStr< CT >::MYTRAITS private
MYTYPE
template<typename CT> typedef CStdStr<CT> StdString::CStdStr< CT >::MYTYPE private
MYVAL
template<typename CT> typedef MYBASE::value_type StdString::CStdStr< CT >::MYVAL private
PCMYSTR
template<typename CT> typedef MYBASE::const_pointer StdString::CStdStr< CT >::PCMYSTR private
PMYSTR
template<typename CT> typedef MYBASE::pointer StdString::CStdStr< CT >::PMYSTR private
Constructor & Destructor Documentation
CStdStr() [1/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr () inline
CStdStr() [2/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (const MYTYPE & str) inline
CStdStr() [3/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (const std::string & str) inline
CStdStr() [4/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (PCMYSTR pT, MYSIZE n) inline
CStdStr() [5/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (PCSTR pA) inline
CStdStr() [6/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (MYCITER first, MYCITER last) inline
CStdStr() [7/7]
template<typename CT> StdString::CStdStr< CT >::CStdStr (MYSIZE nSize, MYVAL ch, const MYALLOC & al = MYALLOC()) inline
Member Function Documentation
CompareNoCase()
template<typename CT> int StdString::CStdStr< CT >::CompareNoCase (PCMYSTR szThat) const inline
References StdString::ssicmp().
Referenced by CharacterManager::CharacterManager(), CheckCodecVersion(), CompareRStringsAsc(), CompareRStringsDesc(), CompareSongPointersByMSD(), CompareSongPointersByTitle(), StepsUtil::CompareStepsPointersByDescription(), CreateDisplay(), ThemeManager::DoesLanguageExist(), ThemeManager::DoesThemeExist(), ScreenPackages::EnterURL(), StdString::CStdStr< CT >::EqualsNoCase(), FileCopy(), ConfOption::Find(), GameManager::GameAndStringToStyle(), GetCommandlineArgument(), RageMovieTexture::GetFourCC(), ThemeManager::GetPathInfoToRaw(), OptionRow::GetRowTitle(), ScreenNetSelectMusic::HandleScreenMessage(), ieq(), ilt(), Character::IsDefaultCharacter(), GameCommand::IsPlayable(), AnimatedTexture::Load(), SMLoader::LoadFromTokens(), SMLoader::LoadNoteDataFromSimfile(), NoteSkinManager::LoadNoteSkinDataRecursive(), ThemeManager::LoadThemeMetrics(), OptionRowHandlerUtil::Make(), FontPageSettings::MapRange(), Song::Matches(), ScreenNetSelectMusic::MusicChanged(), OptionRowHandlerList::Reload(), ColorBitmapText::ResetText(), ColorBitmapText::SetText(), GameManager::StringToGame(), Song::TidyUpData(), TryOpenFile(), and RageSoundReader_FileReader::TryOpenFile().
EqualsNoCase()
template<typename CT> bool StdString::CStdStr< CT >::EqualsNoCase (PCMYSTR szThat) const inline
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), CVSOrSVN(), Deserialize(), EqualsNoCase(), GetLanguageInfo(), DownloadManager::InstallSmzip(), IsPackageFile(), DWILoader::LoadFromDir(), BGAnimationLayer::LoadFromNode(), DWILoader::LoadNoteDataFromSimfile(), MacResourceFork(), ModIcon::Set(), Actor::SetEffectClockString(), StartMusic(), and Song::TidyUpData().
GetBuffer()
template<typename CT> CT* StdString::CStdStr< CT >::GetBuffer (int nMinLen = -1) inline
Referenced by StdString::CStdStr< CT >::MakeLower(), and StdString::CStdStr< CT >::MakeUpper().
Left()
template<typename CT> MYTYPE StdString::CStdStr< CT >::Left (int nCount) const inline
References max(), and min().
Referenced by add_extension_to_relative_path_from_found_file(), AdjustMountpoint(), convert_xml_file(), CreateDirectories(), FileNameToMetricsGroupAndElement(), SongID::FromSong(), ActorUtil::GetAttrPath(), NetworkSyncManager::GetCurrentSMBuild(), ThemeManager::GetLanguagesForTheme(), NotesLoader::GetMainAndSubTitlesFromFullTitle(), GetMessageNameFromCommandName(), ThemeManager::GetMetricsThatBeginWith(), LoadedDriver::GetPath(), SongUtil::GetSectionNameFromSongAndSort(), ScreenSelect::Init(), ThemeManager::IsThemeNameValid(), InputQueueCode::Load(), actor_template_t::load_frames_from_file(), BGAnimation::LoadFromAniDir(), Actor::LoadFromNode(), ActorUtil::LoadFromNode(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), MacResourceFork(), SongUtil::MakeUniqueEditDescription(), Steps::MakeValidEditDescription(), CsvFile::ReadFile(), IniFile::ReadFile(), actor_template_t::store_cmd(), actor_template_t::store_field(), Song::TidyUpData(), SongID::ToSong(), SongManager::UpdatePreferredSort(), and Actor::UpdateTweening().
MakeLower()
template<typename CT> MYTYPE& StdString::CStdStr< CT >::MakeLower () inline
References StdString::CStdStr< CT >::GetBuffer(), and StdString::sslwr().
Referenced by RageSoundManager::AddLoadedSound(), SongManager::AddSongToList(), BMSSongLoader::AddToSong(), blend_conv(), NoteField::CacheAllUsedNoteSkins(), CharacterManager::CharacterManager(), CheckEnum(), CompareLanguageTag::CompareLanguageTag(), RageBitmapTexture::Create(), cull_conv(), FilenameDB::DelFile(), SongManager::DifferentialReloadDir(), bmsCommandTree::doStatement(), DwiCompatibleStringToDifficulty(), NoteField::ensure_note_displays_have_skin(), File::equal(), FindFirstFilenameContaining(), FilenameDB::FlushDirCache(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), FontCharmaps::get_char_map(), FilenameDB::GetFileSet(), FileSet::GetFilesMatching(), ActorUtil::GetFileType(), RageSoundManager::GetLoadedSound(), NoteSkinManager::GetMetric(), Steps::GetNoteDataFromSimfile(), NoteSkinManager::GetPath(), SongManager::GetSongFromDir(), InitCharAliases(), Model::Load(), ScreenMapControllers::ActionRow::Load(), BMSChart::Load(), RageSurfaceUtils::LoadFile(), BGAnimationLayer::LoadFromAniLayerFile(), SMLoader::LoadFromBGChangesString(), DWILoader::LoadFromDir(), LoadFromKSFFile(), BGAnimationLayer::LoadFromNode(), SSCLoader::LoadNoteDataFromSimfile(), RageSoundReader_Chain::LoadSound(), SongManager::LoadStepManiaSongDir(), OldStyleStringToDifficulty(), RageSoundReader_FileReader::OpenFile(), CompareLanguageTag::operator()(), BMSChartReader::ReadHeaders(), NoteSkinManager::RefreshNoteSkinData(), ReplaceEntityText(), SearchForDifficulty(), MusicWheel::SearchGroupNames(), File::SetName(), actor_template_t::store_field(), GameManager::StringToStepsType(), and Song::TidyUpData().
MakeUpper()
template<typename CT> MYTYPE& StdString::CStdStr< CT >::MakeUpper () inline
References StdString::CStdStr< CT >::GetBuffer(), and StdString::ssupr().
Referenced by SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), Font::LoadFontPageSettings(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), OptionRowHandlerListCharacters::LoadInternal(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), SongUtil::MakeSortString(), NetworkSyncManager::MD5Hex(), Nsis(), BitmapText::SetText(), and StringToGrade().
operator const CT *()
template<typename CT> StdString::CStdStr< CT >::operator const CT * () const inline
operator+=() [1/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator+= (const MYTYPE & str) inline
References StdString::ssadd().
operator+=() [2/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator+= (const std::string & str) inline
References StdString::ssadd().
operator+=() [3/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator+= (PCSTR pA) inline
References StdString::ssadd().
operator+=() [4/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator+= (CT t) inline
References append.
operator=() [1/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator= (const MYTYPE & str) inline
References StdString::ssasn().
operator=() [2/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator= (const std::string & str) inline
References StdString::ssasn().
operator=() [3/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator= (PCSTR pA) inline
References StdString::ssasn().
operator=() [4/4]
template<typename CT> MYTYPE& StdString::CStdStr< CT >::operator= (CT t) inline
References Q172398.
operator[]() [1/8]
template<typename CT> CT& StdString::CStdStr< CT >::operator[] (int nIdx) inline
operator[]() [2/8]
template<typename CT> const CT& StdString::CStdStr< CT >::operator[] (int nIdx) const inline
operator[]() [3/8]
template<typename CT> CT& StdString::CStdStr< CT >::operator[] (unsigned int nIdx) inline
operator[]() [4/8]
template<typename CT> const CT& StdString::CStdStr< CT >::operator[] (unsigned int nIdx) const inline
operator[]() [5/8]
template<typename CT> CT& StdString::CStdStr< CT >::operator[] (long unsigned int nIdx) inline
operator[]() [6/8]
template<typename CT> const CT& StdString::CStdStr< CT >::operator[] (long unsigned int nIdx) const inline
operator[]() [7/8]
template<typename CT> CT& StdString::CStdStr< CT >::operator[] (long long unsigned int nIdx) inline
operator[]() [8/8]
template<typename CT> const CT& StdString::CStdStr< CT >::operator[] (long long unsigned int nIdx) const inline
ReleaseBuffer()
template<typename CT> void StdString::CStdStr< CT >::ReleaseBuffer (int nNewLen = -1) inline
Replace() [1/2]
template<typename CT> int StdString::CStdStr< CT >::Replace (CT chOld, CT chNew) inline
Referenced by convert_lua_chunk(), SongManager::FindSong(), GetDirOfExecutable(), FilenameDB::GetFileSet(), Steps::GetNoteDataFromSimfile(), SongManager::GetSongFromDir(), ThemeManager::GetString(), ScreenSelectMaster::Init(), LastDayToLocalizedString(), LastWeekToLocalizedString(), FontPage::Load(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), SMLoader::LoadFromBGChangesString(), LyricsLoader::LoadFromLRCFile(), SongCacheIndex::MangleName(), Song::Matches(), Nsis(), ParseNoteData(), RageDisplay::ProcessStatsOnFlip(), PseudoLocalize(), PercentageDisplay::Refresh(), Regex::Replace(), ReplaceInvalidFileNameChars(), StepMania::SaveScreenshot(), ModIcon::Set(), DirectFilenameDB::SetRoot(), LunaBitmapText::settext(), StepsTypeToString(), and CsvFile::WriteFile().
Replace() [2/2]
template<typename CT> int StdString::CStdStr< CT >::Replace (PCMYSTR szOld, PCMYSTR szNew) inline
References picosha2::detail::ch(), and Rage::replace().
Right()
template<typename CT> MYTYPE StdString::CStdStr< CT >::Right (int nCount) const inline
References max(), and min().
Referenced by AdjustMountpoint(), CVSOrSVN(), DeleteRecursive(), DoPlayOnceFromDir(), ScreenPackages::EnterURL(), FileNameToMetricsGroupAndElement(), GetDirListingRecursive(), RageFileManager::GetFileDriver(), BackgroundUtil::GetGlobalRandomMovies(), GetMessageNameFromCommandName(), LoadedDriver::GetPath(), SongManager::GetSongFromDir(), ScreenGameplaySyncMachine::Init(), ScreenSelect::Init(), ScreenHowToPlay::Init(), Character::Load(), Profile::LoadAllFromDir(), BGAnimation::LoadFromAniDir(), Song::LoadFromSongDir(), SMLoader::LoadNoteDataFromSimfile(), ProfileManager::LoadProfile(), RandomSample::LoadSoundDir(), ActorUtil::MakeActor(), DirectFilenameDB::PopulateFileSet(), SMOProtocol::ProcessInput(), IniFile::ReadFile(), PrefsManager::ReadGamePrefsFromIni(), DirectFilenameDB::SetRoot(), SplitPath(), FileTransfer::StartTransfer(), actor_template_t::store_cmd(), actor_template_t::store_field(), RageFileManager::Unmount(), and SongManager::UpdatePreferredSort().
Friends And Related Function Documentation
operator+EMP_TEMP [1/4]
template<typename CT> MYTYPE operator+EMP_TEMP (const MYTYPE & str1, const MYTYPE & str2) friend
operator+EMP_TEMP [2/4]
template<typename CT> MYTYPE operator+EMP_TEMP (const MYTYPE & str, CT t) friend
operator+EMP_TEMP [3/4]
template<typename CT> MYTYPE operator+EMP_TEMP (const MYTYPE & str, PCSTR sz) friend
operator+EMP_TEMP [4/4]
template<typename CT> MYTYPE operator+EMP_TEMP (PCSTR pA, const MYTYPE & str) friend
The documentation for this class was generated from the following file:
StdString.h