Etterna: WavReaderADPCM Struct Reference
WavReaderADPCM Struct Reference
Public Member Functions
WavReaderADPCM (RageFileBasic &f, const RageSoundReader_WAV::WavData &data)
~WavReaderADPCM () override
bool Init () override
void SetEOF ()
bool DecodeADPCMBlock ()
int Read (float *buf, int iFrames) override
int GetLength () const override
int SetPosition (int iFrame) override
int GetNextSourceFrame () const override
Public Member Functions inherited from WavReader
WavReader (RageFileBasic &f, const RageSoundReader_WAV::WavData &data)
virtual ~WavReader ()=default
RString GetError () const
Public Attributes
vector< int16_t > m_iaCoef1
vector< int16_t > m_iaCoef2
int16_t m_iFramesPerBlock
float * m_pBuffer
int m_iBufferAvail
int m_iBufferUsed
Additional Inherited Members
Protected Attributes inherited from WavReader
RageFileBasic & m_File
const RageSoundReader_WAV::WavData & m_WavData
RString m_sError
Constructor & Destructor Documentation
WavReaderADPCM()
WavReaderADPCM::WavReaderADPCM (RageFileBasic & f, const RageSoundReader_WAV::WavData & data) inline
~WavReaderADPCM()
WavReaderADPCM::~WavReaderADPCM () inline override
References m_pBuffer.
Member Function Documentation
DecodeADPCMBlock()
bool WavReaderADPCM::DecodeADPCMBlock () inline
References ASSERT_M, RageFileBasic::AtEOF(), RageFileBasic::GetDisplayPath(), RageFileBasic::GetError(), LOG, WavReader::m_File, RageSoundReader_WAV::WavData::m_iBlockAlign, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, m_iFramesPerBlock, m_pBuffer, WavReader::m_sError, WavReader::m_WavData, max(), min(), RageFileBasic::Read(), FileReading::read_16_le(), FileReading::read_8(), ssprintf(), RageFileBasic::Tell(), and RageLog::Trace().
Referenced by Read(), and SetPosition().
GetLength()
int WavReaderADPCM::GetLength () const inline override virtual
Implements WavReader.
References RageSoundReader_WAV::WavData::m_iBlockAlign, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkSize, m_iFramesPerBlock, RageSoundReader_WAV::WavData::m_iSampleRate, WavReader::m_WavData, and max().
GetNextSourceFrame()
int WavReaderADPCM::GetNextSourceFrame () const inline override virtual
Implements WavReader.
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iBlockAlign, m_iBufferUsed, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, m_iFramesPerBlock, WavReader::m_WavData, and RageFileBasic::Tell().
Init()
bool WavReaderADPCM::Init () inline override virtual
Implements WavReader.
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iExtraFmtPos, WavReader::m_sError, WavReader::m_WavData, FileReading::read_16_le(), RageFileBasic::Seek(), and ssprintf().
Read()
int WavReaderADPCM::Read (float * buf, int iFrames) inline override virtual
Implements WavReader.
References DecodeADPCMBlock(), RageSoundReader::END_OF_FILE, RageSoundReader_WAV::WavData::m_iChannels, WavReader::m_WavData, and RageSoundReader::RSRERROR.
SetEOF()
void WavReaderADPCM::SetEOF () inline
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, WavReader::m_WavData, and RageFileBasic::Seek().
Referenced by SetPosition().
SetPosition()
int WavReaderADPCM::SetPosition (int iFrame) inline override virtual
Implements WavReader.
References DecodeADPCMBlock(), WavReader::m_File, RageSoundReader_WAV::WavData::m_iBlockAlign, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, m_iFramesPerBlock, WavReader::m_WavData, RageFileBasic::Seek(), and SetEOF().
Member Data Documentation
m_iaCoef1
vector<int16_t> WavReaderADPCM::m_iaCoef1
m_iaCoef2
vector<int16_t> WavReaderADPCM::m_iaCoef2
m_iBufferAvail
int WavReaderADPCM::m_iBufferAvail
m_iBufferUsed
int WavReaderADPCM::m_iBufferUsed
Referenced by GetNextSourceFrame().
m_iFramesPerBlock
int16_t WavReaderADPCM::m_iFramesPerBlock
Referenced by DecodeADPCMBlock(), GetLength(), GetNextSourceFrame(), and SetPosition().
m_pBuffer
float* WavReaderADPCM::m_pBuffer
Referenced by DecodeADPCMBlock(), and ~WavReaderADPCM().
The documentation for this struct was generated from the following file:
RageSoundReader_WAV.cpp