Etterna: RageFileObj Class Reference
RageFileObj Class Reference abstract
#include <RageFileBasic.h>
Public Member Functions
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
int GetFileSize () const override=0
int GetFD () override
RString GetDisplayPath () const override
RageFileBasic * Copy () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Protected Member Functions
virtual int SeekInternal (int)
virtual int ReadInternal (void *pBuffer, size_t iBytes)=0
virtual int WriteInternal (const void *pBuffer, size_t iBytes)=0
virtual int FlushInternal ()
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes
RString m_sError
Private Types
enum { BSIZE = 1024 }
Private Member Functions
int FillReadBuf ()
void ResetReadBuf ()
int EmptyWriteBuf ()
RageFileObj & operator= (const RageFileObj &rhs)
Private Attributes
bool m_bEOF
int m_iFilePos
char * m_pReadBuffer
char * m_pReadBuf
int m_iReadBufAvail
char * m_pWriteBuffer
int m_iWriteBufferPos
int m_iWriteBufferSize
int m_iWriteBufferUsed
bool m_bCRC32Enabled
uint32_t m_iCRC32
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
BSIZE
Constructor & Destructor Documentation
RageFileObj() [1/2]
RageFileObj::RageFileObj ()
References m_bCRC32Enabled, m_bEOF, m_iCRC32, m_iFilePos, m_iReadBufAvail, m_iWriteBufferPos, m_iWriteBufferUsed, m_pReadBuffer, m_pWriteBuffer, and ResetReadBuf().
RageFileObj() [2/2]
RageFileObj::RageFileObj (const RageFileObj & cpy)
References BSIZE, m_bCRC32Enabled, m_bEOF, m_iCRC32, m_iFilePos, m_iReadBufAvail, m_iWriteBufferPos, m_iWriteBufferSize, m_iWriteBufferUsed, m_pReadBuf, m_pReadBuffer, and m_pWriteBuffer.
~RageFileObj()
RageFileObj::~RageFileObj () override
References m_pReadBuffer, and m_pWriteBuffer.
Member Function Documentation
AtEOF()
bool RageFileObj::AtEOF () const inline override virtual
Implements RageFileBasic.
References m_bEOF.
ClearError()
void RageFileObj::ClearError () inline override virtual
Implements RageFileBasic.
Reimplemented in RageFileDriverReadAhead.
References SetError().
Copy()
RageFileBasic* RageFileObj::Copy () const inline override virtual
Implements RageFileBasic.
Reimplemented in RageFileObjTimeout, RageFileObjDirect, RageFileObjInflate, RageFileObjMem, RageFileDriverReadAhead, and RageFileDriverSlice.
References FAIL_M.
EmptyWriteBuf()
int RageFileObj::EmptyWriteBuf () private
References m_iFilePos, m_iWriteBufferPos, m_iWriteBufferUsed, m_pWriteBuffer, SeekInternal(), and WriteInternal().
Referenced by Flush(), and Write().
EnableCRC32()
void RageFileObj::EnableCRC32 (bool on = true) override virtual
Implements RageFileBasic.
References m_bCRC32Enabled, and m_iCRC32.
Referenced by GunzipFile(), and RageFileObjGzip::Start().
EnableReadBuffering()
void RageFileObj::EnableReadBuffering () protected
References BSIZE, and m_pReadBuffer.
Referenced by GetLine(), and RageFileObjTimeout::RageFileObjTimeout().
EnableWriteBuffering()
void RageFileObj::EnableWriteBuffering (int iBytes = 1024 * 64) protected
References m_iFilePos, m_iWriteBufferPos, m_iWriteBufferSize, and m_pWriteBuffer.
Referenced by RageFileObjDirect::RageFileObjDirect(), and RageFileObjTimeout::RageFileObjTimeout().
FillReadBuf()
int RageFileObj::FillReadBuf () private
References ASSERT, ASSERT_M, BSIZE, m_iReadBufAvail, m_pReadBuf, m_pReadBuffer, ReadInternal(), and ssprintf().
Referenced by GetLine(), and Read().
Flush()
int RageFileObj::Flush () override virtual
Implements RageFileBasic.
References EmptyWriteBuf(), and FlushInternal().
Referenced by RageFileObjDirect::FinalFlush(), RageFileObjGzip::Finish(), and RageFileObjTimeout::~RageFileObjTimeout().
FlushInternal()
virtual int RageFileObj::FlushInternal () inline protected virtual
Reimplemented in RageFileObjTimeout, RageFileObjDeflate, and RageFileObjDirect.
Referenced by Flush().
GetCRC32()
bool RageFileObj::GetCRC32 (uint32_t * iRet) override virtual
Implements RageFileBasic.
References m_bCRC32Enabled, and m_iCRC32.
Referenced by RageFileObjGzip::Finish().
GetDisplayPath()
RString RageFileObj::GetDisplayPath () const inline override virtual
Reimplemented from RageFileBasic.
Reimplemented in RageFileObjDirect.
GetError()
RString RageFileObj::GetError () const inline override virtual
Implements RageFileBasic.
Reimplemented in RageFileDriverReadAhead.
References m_sError.
GetFD()
int RageFileObj::GetFD () inline override virtual
Implements RageFileBasic.
Reimplemented in RageFileObjTimeout, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, and RageFileDriverSlice.
GetFileSize()
int RageFileObj::GetFileSize () const override pure virtual
Implements RageFileBasic.
Implemented in RageFileObjTimeout, RageFileObjDeflate, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, RageFileDriverSlice, and RageFileObjMem.
Referenced by Read(), and Seek().
GetLine()
int RageFileObj::GetLine (RString & out) override virtual
Implements RageFileBasic.
References ASSERT, EnableReadBuffering(), FillReadBuf(), m_bEOF, m_iFilePos, m_iReadBufAvail, m_pReadBuf, and m_pReadBuffer.
operator=()
RageFileObj& RageFileObj::operator= (const RageFileObj & rhs) private
PutLine()
int RageFileObj::PutLine (const RString & str) override virtual
Implements RageFileBasic.
References NEWLINE, and Write().
Read() [1/3]
int RageFileObj::Read (void * pBuffer, size_t iBytes) override virtual
Implements RageFileBasic.
References ASSERT, BSIZE, CRC32, FillReadBuf(), m_bCRC32Enabled, m_bEOF, m_iCRC32, m_iFilePos, m_iReadBufAvail, m_pReadBuf, m_pReadBuffer, min(), and ReadInternal().
Referenced by Read().
Read() [2/3]
int RageFileObj::Read (RString & buffer, int bytes = -1) override virtual
Implements RageFileBasic.
References GetFileSize(), min(), and Read().
Read() [3/3]
int RageFileObj::Read (void * buffer, size_t bytes, int nmemb) override virtual
Implements RageFileBasic.
References Read(), Seek(), and Tell().
ReadInternal()
virtual int RageFileObj::ReadInternal (void * pBuffer, size_t iBytes) protected pure virtual
Implemented in RageFileObjTimeout, RageFileObjDeflate, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, RageFileObjMem, and RageFileDriverSlice.
Referenced by FillReadBuf(), and Read().
ResetReadBuf()
void RageFileObj::ResetReadBuf () private
References m_iReadBufAvail, m_pReadBuf, and m_pReadBuffer.
Referenced by RageFileObj(), and Seek().
Seek() [1/2]
int RageFileObj::Seek (int iOffset) override virtual
Implements RageFileBasic.
References m_bCRC32Enabled, m_bEOF, m_iFilePos, ResetReadBuf(), and SeekInternal().
Referenced by RageFileObjDirect::Copy(), Read(), and Seek().
Seek() [2/2]
int RageFileObj::Seek (int offset, int whence) override virtual
Implements RageFileBasic.
References GetFileSize(), Seek(), and Tell().
SeekInternal()
virtual int RageFileObj::SeekInternal (int) inline protected virtual
Reimplemented in RageFileObjTimeout, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, RageFileDriverSlice, and RageFileObjMem.
References FAIL_M.
Referenced by EmptyWriteBuf(), and Seek().
SetError()
void RageFileObj::SetError (const RString & sError) inline protected
References m_sError.
Referenced by ClearError(), RageFileObjDirect::FinalFlush(), RageFileObjGzip::Finish(), RageFileObjDirect::FlushInternal(), RageFileObjDeflate::FlushInternal(), RageFileObjTimeout::FlushInternal(), RageFileObjTimeout::GetFD(), RageFileObjInflate::ReadInternal(), RageFileDriverSlice::ReadInternal(), RageFileObjDirect::ReadInternal(), RageFileObjDeflate::ReadInternal(), RageFileObjTimeout::ReadInternal(), RageFileDriverSlice::SeekInternal(), RageFileObjTimeout::SeekInternal(), RageFileDriverSlice::WriteInternal(), RageFileObjInflate::WriteInternal(), RageFileObjDirect::WriteInternal(), RageFileObjDeflate::WriteInternal(), RageFileObjTimeout::WriteInternal(), and RageFileObjDirect::~RageFileObjDirect().
Tell()
int RageFileObj::Tell () const inline override virtual
Implements RageFileBasic.
Reimplemented in RageFileDriverReadAhead.
References m_iFilePos.
Referenced by RageFileObjGzip::Finish(), Read(), Seek(), and RageFileObjGzip::Start().
Write() [1/3]
int RageFileObj::Write (const void * pBuffer, size_t iBytes) override virtual
Implements RageFileBasic.
References ASSERT_M, CRC32, EmptyWriteBuf(), m_bCRC32Enabled, m_iCRC32, m_iFilePos, m_iWriteBufferPos, m_iWriteBufferSize, m_iWriteBufferUsed, m_pWriteBuffer, ssprintf(), and WriteInternal().
Referenced by GzipString(), PutLine(), and Write().
Write() [2/3]
int RageFileObj::Write (const RString & sString) inline override virtual
Implements RageFileBasic.
References Write().
Write() [3/3]
int RageFileObj::Write (const void * buffer, size_t bytes, int nmemb) override virtual
Implements RageFileBasic.
References Write().
WriteInternal()
virtual int RageFileObj::WriteInternal (const void * pBuffer, size_t iBytes) protected pure virtual
Implemented in RageFileObjTimeout, RageFileObjDeflate, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, RageFileObjMem, and RageFileDriverSlice.
Referenced by EmptyWriteBuf(), and Write().
Member Data Documentation
m_bCRC32Enabled
bool RageFileObj::m_bCRC32Enabled private
Referenced by EnableCRC32(), GetCRC32(), RageFileObj(), Read(), Seek(), and Write().
m_bEOF
bool RageFileObj::m_bEOF private
Referenced by AtEOF(), GetLine(), RageFileObj(), Read(), and Seek().
m_iCRC32
uint32_t RageFileObj::m_iCRC32 private
Referenced by EnableCRC32(), GetCRC32(), RageFileObj(), Read(), and Write().
m_iFilePos
int RageFileObj::m_iFilePos private
Referenced by EmptyWriteBuf(), EnableWriteBuffering(), GetLine(), RageFileObj(), Read(), Seek(), Tell(), and Write().
m_iReadBufAvail
int RageFileObj::m_iReadBufAvail private
Referenced by FillReadBuf(), GetLine(), RageFileObj(), Read(), and ResetReadBuf().
m_iWriteBufferPos
int RageFileObj::m_iWriteBufferPos private
Referenced by EmptyWriteBuf(), EnableWriteBuffering(), RageFileObj(), and Write().
m_iWriteBufferSize
int RageFileObj::m_iWriteBufferSize private
Referenced by EnableWriteBuffering(), RageFileObj(), and Write().
m_iWriteBufferUsed
int RageFileObj::m_iWriteBufferUsed private
Referenced by EmptyWriteBuf(), RageFileObj(), and Write().
m_pReadBuf
char* RageFileObj::m_pReadBuf private
Referenced by FillReadBuf(), GetLine(), RageFileObj(), Read(), and ResetReadBuf().
m_pReadBuffer
char* RageFileObj::m_pReadBuffer private
Referenced by EnableReadBuffering(), FillReadBuf(), GetLine(), RageFileObj(), Read(), ResetReadBuf(), and ~RageFileObj().
m_pWriteBuffer
char* RageFileObj::m_pWriteBuffer private
Referenced by EmptyWriteBuf(), EnableWriteBuffering(), RageFileObj(), Write(), and ~RageFileObj().
m_sError
RString RageFileObj::m_sError protected
Referenced by GetError(), and SetError().
The documentation for this class was generated from the following files:
RageFileBasic.h
RageFileBasic.cpp