Etterna: Chart Struct Reference
Chart Struct Reference
#include <Difficulty.h>
Public Member Functions
bool IsLoaded ()
void FromKey (const string &ck)
XNode * CreateNode (bool includerate) const
void LoadFromNode (const XNode *node)
void PushSelf (lua_State *L)
Public Attributes
string key
RString lastsong
RString lastpack
Difficulty lastdiff = Difficulty_Invalid
float rate = 1.f
Song * songptr
Steps * stepsptr
bool loaded = false
Member Function Documentation
CreateNode()
XNode * Chart::CreateNode (bool includerate) const
References XNode::AppendAttr(), picosha2::detail::ch(), DifficultyToString(), key, lastdiff, lastpack, lastsong, rate, and ssprintf().
Referenced by ScoresForChart::CreateNode().
FromKey()
void Chart::FromKey (const string & ck)
References Steps::GetDifficulty(), Song::GetDisplayMainTitle(), SongManager::GetSongByChartkey(), SongManager::GetStepsByChartkey(), key, lastdiff, lastpack, lastsong, loaded, Song::m_sGroupName, songptr, and stepsptr.
Referenced by Playlist::AddChart(), ScoresForChart::CreateNode(), LoadFromNode(), DBProfile::LoadPlayLists(), and DBProfile::SavePlayerScores().
IsLoaded()
bool Chart::IsLoaded () inline
References loaded.
LoadFromNode()
void Chart::LoadFromNode (const XNode * node)
References ASSERT, FromKey(), XNode::GetAttrValue(), XNode::GetName(), key, lastdiff, lastpack, lastsong, rate, SongManager::ReconcileBustedKeys(), StringToDifficulty(), and StringToFloat().
Referenced by Playlist::LoadFromNode(), and ScoresForChart::LoadFromNode().
PushSelf()
void Chart::PushSelf (lua_State * L)
Member Data Documentation
key
string Chart::key
Referenced by CreateNode(), FromKey(), LoadFromNode(), ScoresForChart::LoadFromNode(), DBProfile::LoadPlayLists(), and DBProfile::SavePlayerScores().
lastdiff
Difficulty Chart::lastdiff = Difficulty_Invalid
Referenced by CreateNode(), FromKey(), LoadFromNode(), DBProfile::LoadPlayLists(), and DBProfile::SavePlayerScores().
lastpack
RString Chart::lastpack
Referenced by CreateNode(), FromKey(), LoadFromNode(), ScoresForChart::LoadFromNode(), DBProfile::LoadPlayLists(), and DBProfile::SavePlayerScores().
lastsong
RString Chart::lastsong
Referenced by CreateNode(), FromKey(), LoadFromNode(), ScoresForChart::LoadFromNode(), DBProfile::LoadPlayLists(), and DBProfile::SavePlayerScores().
loaded
bool Chart::loaded = false
Referenced by FromKey(), and IsLoaded().
rate
float Chart::rate = 1.f
Referenced by Playlist::AddChart(), LunaChart::ChangeRate(), CreateNode(), LoadFromNode(), and DBProfile::LoadPlayLists().
songptr
Song* Chart::songptr
Referenced by FromKey().
stepsptr
Steps* Chart::stepsptr
Referenced by FromKey().
The documentation for this struct was generated from the following files:
Difficulty.h
SongManager.cpp