Etterna: ScreenMapControllers Class Reference
ScreenMapControllers Class Reference
#include <ScreenMapControllers.h>
Classes
struct ActionRow
struct KeyToMap
struct SetListEntry
Public Member Functions
ScreenMapControllers ()
~ScreenMapControllers () override
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
void Update (float fDeltaTime) override
bool Input (const InputEventPlus &input) override
void HandleMessage (const Message &msg) override
void HandleScreenMessage (ScreenMessage SM) override
Public Member Functions inherited from ScreenWithMenuElements
ScreenWithMenuElements ()
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
~ScreenWithMenuElements () override
void HandleScreenMessage (ScreenMessage SM) override
void Update (float fDeltaTime) override
void StartTransitioningScreen (ScreenMessage smSendWhenDone)
virtual void Cancel (ScreenMessage smSendWhenDone)
bool IsTransitioning ()
bool AllowCallbackInput () override
void StopTimer ()
void ResetTimer ()
virtual void TweenOnScreen ()
virtual void TweenOffScreen ()
void PushSelf (lua_State *L) override
bool AllowLateJoin () const override
Determine if we allow extra players to join in on this screen.
Public Member Functions inherited from Screen
~Screen () override
virtual void EndScreen ()
This is called when the screen is popped.
void SetLockInputSecs (float f)
void PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
void ClearMessageQueue ()
Clear the entire message queue.
void ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
virtual ScreenType GetScreenType () const
bool AllowOperatorMenuButton () const
RString GetNextScreenName () const
RString GetPrevScreen () const
void SetNextScreenName (RString const &name)
void SetPrevScreenName (RString const &name)
bool PassInputToLua (const InputEventPlus &input)
void AddInputCallbackFromStack (lua_State *L)
void RemoveInputCallback (lua_State *L)
virtual bool MenuUp (const InputEventPlus &)
virtual bool MenuDown (const InputEventPlus &)
virtual bool MenuLeft (const InputEventPlus &)
virtual bool MenuRight (const InputEventPlus &)
virtual bool MenuStart (const InputEventPlus &)
virtual bool MenuSelect (const InputEventPlus &)
virtual bool MenuBack (const InputEventPlus &)
virtual bool MenuCoin (const InputEventPlus &)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Private Types
using action_fun_t = void(ScreenMapControllers::*)()
Private Member Functions
Actor * GetActorWithFocus ()
void BeforeChangeFocus ()
void AfterChangeFocus ()
void Refresh ()
void DismissWarning ()
bool CursorOnAction ()
bool CursorOnHeader ()
bool CursorOnKey ()
bool CursorCanGoUp ()
bool CursorCanGoDown ()
bool CursorCanGoLeft ()
bool CursorCanGoRight ()
int CurKeyIndex ()
int CurActionIndex ()
void SetCursorFromSetListCurrent ()
void StartWaitingForPress ()
void ClearToDefault ()
void ReloadFromDisk ()
void SaveToDisk ()
void SetListMode ()
void ExitAction ()
bool SanityCheckWrapper ()
Private Attributes
unsigned int m_CurController
unsigned int m_CurButton
unsigned int m_CurSlot
unsigned int m_MaxDestItem
bool m_ChangeOccurred
RageTimer m_WaitingForPress
DeviceInput m_DeviceIToMap
vector< KeyToMap > m_KeysToMap
BitmapText m_textDevices
BitmapText m_textLabel [NUM_GameController]
BitmapText m_ListHeaderCenter
BitmapText m_ListHeaderLabels [NUM_GameController][NUM_SHOWN_GAME_TO_DEVICE_SLOTS]
float m_AutoDismissWarningSecs
AutoActor m_Warning
float m_AutoDismissNoSetListPromptSecs
AutoActor m_NoSetListPrompt
float m_AutoDismissSanitySecs
AutoActor m_SanityMessage
set< SetListEntry > m_SetList
set< SetListEntry >::iterator m_SetListCurrent
bool m_InSetListMode
vector< ActionRow > m_Actions
vector< ActorFrame * > m_Line
ActorScroller m_LineScroller
RageSound m_soundChange
RageSound m_soundDelete
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Screen
static void InitScreen (Screen *pScreen)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from ScreenWithMenuElements
bool m_bShouldAllowLateJoin
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from ScreenWithMenuElements
RString HandleLuaMusicFile (RString const &path)
virtual void StartPlayingMusic ()
void SetHelpText (const RString &s)
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Static Protected Member Functions inherited from Screen
static bool SortMessagesByDelayRemaining (const QueuedScreenMessage &m1, const QueuedScreenMessage &m2)
Protected Attributes inherited from ScreenWithMenuElements
AutoActor m_sprUnderlay
MenuTimer * m_MenuTimer
AutoActor m_sprOverlay
vector< Actor * > m_vDecorations
Transition m_In
Transition m_Out
Transition m_Cancel
ThemeMetric< bool > PLAY_MUSIC
ThemeMetric< bool > MUSIC_ALIGN_BEAT
ThemeMetric< float > DELAY_MUSIC_SECONDS
ThemeMetric< bool > CANCEL_TRANSITIONS_OUT
ThemeMetric< float > TIMER_SECONDS
ThemeMetric< RString > TIMER_METRICS_GROUP
ThemeMetric< bool > RESET_GAMESTATE
Protected Attributes inherited from Screen
vector< QueuedScreenMessage > m_QueuedMessages
The list of messages that are sent to a Screen.
InputQueueCodeSet m_Codes
ThemeMetric< bool > ALLOW_OPERATOR_MENU_BUTTON
Do we allow the operator menu button to be pressed here?
ThemeMetric< bool > HANDLE_BACK_BUTTON
Do we handle the back button being pressed here?
ThemeMetric< float > REPEAT_RATE
ThemeMetric< float > REPEAT_DELAY
RString m_sNextScreen
The next screen to go to once this screen is done.
RString m_sPrevScreen
ScreenMessage m_smSendOnPop
float m_fLockInputSecs
bool m_bRunning
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Member Typedef Documentation
action_fun_t
using ScreenMapControllers::action_fun_t = void (ScreenMapControllers::*)() private
Constructor & Destructor Documentation
ScreenMapControllers()
ScreenMapControllers::ScreenMapControllers ()
References m_ChangeOccurred, m_InSetListMode, Message_AutoJoyMappingApplied, and MessageSubscriber::SubscribeToMessage().
~ScreenMapControllers()
ScreenMapControllers::~ScreenMapControllers () override
References m_Line, and SAFE_DELETE.
Member Function Documentation
AfterChangeFocus()
void ScreenMapControllers::AfterChangeFocus () private
References GetActorWithFocus(), and Actor::PlayCommand().
Referenced by BeginScreen(), Input(), SetListMode(), and Update().
BeforeChangeFocus()
void ScreenMapControllers::BeforeChangeFocus () private
References GetActorWithFocus(), and Actor::PlayCommand().
Referenced by Input(), SetListMode(), and Update().
BeginScreen()
void ScreenMapControllers::BeginScreen () override virtual
This is called immediately before the screen is used.
Reimplemented from Screen.
References AfterChangeFocus(), ScreenWithMenuElements::BeginScreen(), f, ThemeManager::GetMetricF(), Actor::HasCommand(), m_AutoDismissNoSetListPromptSecs, m_AutoDismissSanitySecs, m_AutoDismissWarningSecs, m_CurButton, m_CurController, m_CurSlot, Screen::m_fLockInputSecs, Actor::m_sName, m_WaitingForPress, m_Warning, Actor::PlayCommand(), Refresh(), Actor::SetHibernate(), RageTimer::SetZero(), and THEME.
ClearToDefault()
void ScreenMapControllers::ClearToDefault () private
References INPUTMAPPER, and InputMapper::ResetMappingsToDefault().
Referenced by Init().
CurActionIndex()
int ScreenMapControllers::CurActionIndex () private
References m_CurButton, and m_KeysToMap.
Referenced by GetActorWithFocus(), and Input().
CurKeyIndex()
int ScreenMapControllers::CurKeyIndex () private
References m_CurButton.
Referenced by GetActorWithFocus(), Input(), StartWaitingForPress(), and Update().
CursorCanGoDown()
bool ScreenMapControllers::CursorCanGoDown () private
References m_Actions, m_CurButton, and m_KeysToMap.
Referenced by Input().
CursorCanGoLeft()
bool ScreenMapControllers::CursorCanGoLeft () private
References CursorOnAction(), m_CurController, and m_CurSlot.
Referenced by Input().
CursorCanGoRight()
bool ScreenMapControllers::CursorCanGoRight () private
References CursorOnAction(), m_CurController, m_CurSlot, NUM_CHANGABLE_SLOTS, and NUM_GameController.
Referenced by Input().
CursorCanGoUp()
bool ScreenMapControllers::CursorCanGoUp () private
References m_CurButton.
Referenced by Input().
CursorOnAction()
bool ScreenMapControllers::CursorOnAction () private
References m_CurButton, and m_KeysToMap.
Referenced by CursorCanGoLeft(), CursorCanGoRight(), CursorOnKey(), GetActorWithFocus(), and Input().
CursorOnHeader()
bool ScreenMapControllers::CursorOnHeader () private
References m_CurButton.
Referenced by CursorOnKey(), GetActorWithFocus(), and Input().
CursorOnKey()
bool ScreenMapControllers::CursorOnKey () private
References CursorOnAction(), and CursorOnHeader().
Referenced by Input(), and Update().
DismissWarning()
void ScreenMapControllers::DismissWarning () private
References m_Warning, and Actor::PlayCommand().
Referenced by Input(), and Update().
ExitAction()
void ScreenMapControllers::ExitAction () private
References ANSWER_YES, m_ChangeOccurred, ScreenManager::PlayStartSound(), ScreenPrompt::Prompt(), PROMPT_YES_NO_CANCEL, SanityCheckWrapper(), SAVE_PROMPT, SCREENMAN, SM_GoToNextScreen, and ScreenWithMenuElements::StartTransitioningScreen().
Referenced by Init(), and Input().
GetActorWithFocus()
Actor * ScreenMapControllers::GetActorWithFocus () private
References CurActionIndex(), CurKeyIndex(), CursorOnAction(), CursorOnHeader(), m_Actions, m_CurController, m_CurSlot, m_KeysToMap, m_ListHeaderLabels, and ScreenMapControllers::KeyToMap::m_textMappedTo.
Referenced by AfterChangeFocus(), BeforeChangeFocus(), and Input().
HandleMessage()
void ScreenMapControllers::HandleMessage (const Message & msg) override virtual
Reimplemented from ActorFrame.
References ActorFrame::HandleMessage(), Message_AutoJoyMappingApplied, and Refresh().
HandleScreenMessage()
void ScreenMapControllers::HandleScreenMessage (ScreenMessage SM) override virtual
Reimplemented from Screen.
References ANSWER_CANCEL, ANSWER_NO, ANSWER_YES, DEFAULT_FAIL, ScreenWithMenuElements::HandleScreenMessage(), ReloadFromDisk(), ScreenPrompt::s_LastAnswer, SaveToDisk(), SM_GoToNextScreen, and ScreenWithMenuElements::StartTransitioningScreen().
Init()
void ScreenMapControllers::Init () override virtual
This is called immediately after construction, to allow initializing after all derived classes exist.
Don't call it directly; use InitScreen instead.
Reimplemented from Screen.
References ADD_ACTION, ActorFrame::AddChild(), BUTTONS_TO_MAP, ClearToDefault(), DRAW_ORDER_TRANSITIONS, ExitAction(), FOREACH_ENUM, FOREACH_GameButtonInScheme, GameButton_Invalid, GameButtonToLocalizedString(), InputScheme::GameButtonToMenuButton(), InputMapper::GetInputScheme(), ThemeManager::GetMetricA(), ThemeManager::GetMetricI(), ActorFrame::GetNumChildren(), ThemeManager::GetPathF(), ThemeManager::GetPathG(), ThemeManager::GetPathS(), LocalizedString::GetValue(), ScreenWithMenuElements::Init(), INPUTMAPPER, KEYNAME, AutoActor::Load(), RageSound::Load(), ActorScroller::Load2(), LOAD_ALL_COMMANDS, LOAD_ALL_COMMANDS_AND_SET_XY, ActorUtil::LoadAllCommands(), BitmapText::LoadFromFont(), m_Actions, ScreenMapControllers::KeyToMap::m_GameButton, m_KeysToMap, m_Line, m_LineScroller, m_ListHeaderCenter, m_ListHeaderLabels, m_MaxDestItem, m_NoSetListPrompt, m_SanityMessage, Actor::m_sName, m_soundChange, m_soundDelete, m_textDevices, m_textLabel, ScreenMapControllers::KeyToMap::m_textMappedTo, m_Warning, MAPPED_TO_COMMAND, NUM_SHOWN_GAME_TO_DEVICE_SLOTS, PLAYER_SLOTS, PlayerNumberToLocalizedString(), PlayerNumberToString(), ReloadFromDisk(), Actor::RunCommands(), SaveToDisk(), Actor::SetDrawOrder(), SetListMode(), Actor::SetName(), ActorScroller::SetNumItemsToDraw(), BitmapText::SetText(), split(), ssprintf(), StringToGameButton(), text, and THEME.
Input()
bool ScreenMapControllers::Input (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References InputMapper::AddDefaultMappingsForCurrentGameIfUnmapped(), AfterChangeFocus(), BeforeChangeFocus(), DeviceInput::button, InputMapper::ClearFromInputMap(), CurActionIndex(), CurKeyIndex(), CursorCanGoDown(), CursorCanGoLeft(), CursorCanGoRight(), CursorCanGoUp(), CursorOnAction(), CursorOnHeader(), CursorOnKey(), DeviceInput::device, DEVICE_KEYBOARD, InputEventPlus::DeviceI, DismissWarning(), ExitAction(), f, GetActorWithFocus(), IET_FIRST_PRESS, IET_REPEAT, INPUTMAPPER, INVALID_BUTTON, IsAxis(), ScreenWithMenuElements::IsTransitioning(), DeviceInput::IsValid(), RageTimer::IsZero(), KEY_BACK, KEY_Cm, KEY_DEL, KEY_DOWN, KEY_ENTER, KEY_ESC, KEY_F1, KEY_F12, KEY_KP_ENTER, KEY_LEFT, KEY_RIGHT, KEY_SPACE, KEY_UP, LOG, m_Actions, m_AutoDismissNoSetListPromptSecs, m_AutoDismissSanitySecs, m_AutoDismissWarningSecs, m_CurButton, m_CurController, m_CurSlot, m_DeviceIToMap, Screen::m_fLockInputSecs, ScreenMapControllers::KeyToMap::m_GameButton, m_KeysToMap, m_NoSetListPrompt, m_SanityMessage, m_SetList, m_soundChange, m_soundDelete, m_WaitingForPress, NUM_CHANGABLE_SLOTS, RageSound::Play(), Actor::PlayCommand(), ScreenManager::PlayInvalidSound(), ScreenManager::PlayStartSound(), Refresh(), SCREENMAN, StartWaitingForPress(), ScreenManager::SystemMessage(), RageLog::Trace(), and InputEventPlus::type.
Refresh()
void ScreenMapControllers::Refresh () private
References FOREACH_ENUM, InputMapper::GameToDevice(), RageInput::GetDeviceSpecificInputString(), INPUTMAN, INPUTMAPPER, m_CurButton, ScreenMapControllers::KeyToMap::m_GameButton, m_KeysToMap, m_LineScroller, m_MaxDestItem, ScreenMapControllers::KeyToMap::m_textMappedTo, min(), NUM_SHOWN_GAME_TO_DEVICE_SLOTS, ActorScroller::SetDestinationItem(), and BitmapText::SetText().
Referenced by BeginScreen(), HandleMessage(), Input(), and Update().
ReloadFromDisk()
void ScreenMapControllers::ReloadFromDisk () private
References INPUTMAPPER, and InputMapper::ReadMappingsFromDisk().
Referenced by HandleScreenMessage(), and Init().
SanityCheckWrapper()
bool ScreenMapControllers::SanityCheckWrapper () private
References FOREACH, ThemeManager::GetMetricF(), ThemeManager::GetString(), Actor::HandleMessage(), INPUTMAPPER, Rage::join(), m_AutoDismissSanitySecs, m_SanityMessage, Actor::m_sName, InputMapper::SanityCheckMappings(), Message::SetParam(), and THEME.
Referenced by ExitAction(), and SaveToDisk().
SaveToDisk()
void ScreenMapControllers::SaveToDisk () private
References INPUTMAPPER, m_ChangeOccurred, SanityCheckWrapper(), and InputMapper::SaveMappingsToDisk().
Referenced by HandleScreenMessage(), and Init().
SetCursorFromSetListCurrent()
void ScreenMapControllers::SetCursorFromSetListCurrent () private
References m_CurButton, m_CurController, m_CurSlot, and m_SetListCurrent.
Referenced by SetListMode(), and Update().
SetListMode()
void ScreenMapControllers::SetListMode () private
References AfterChangeFocus(), BeforeChangeFocus(), ThemeManager::GetMetricF(), m_AutoDismissNoSetListPromptSecs, m_InSetListMode, m_NoSetListPrompt, m_SetList, m_SetListCurrent, Actor::m_sName, Actor::PlayCommand(), SetCursorFromSetListCurrent(), StartWaitingForPress(), and THEME.
Referenced by Init().
StartWaitingForPress()
void ScreenMapControllers::StartWaitingForPress () private
References CurKeyIndex(), m_CurController, m_CurSlot, m_DeviceIToMap, m_KeysToMap, ScreenMapControllers::KeyToMap::m_textMappedTo, m_WaitingForPress, DeviceInput::MakeInvalid(), Actor::PlayCommand(), and RageTimer::Touch().
Referenced by Input(), SetListMode(), and Update().
Update()
void ScreenMapControllers::Update (float fDeltaTime) override virtual
Reimplemented from Screen.
References InputMapper::AddDefaultMappingsForCurrentGameIfUnmapped(), AfterChangeFocus(), ASSERT, BeforeChangeFocus(), CurKeyIndex(), CursorOnKey(), DismissWarning(), f, g_fSecondsToWaitForInput, RageInput::GetDisplayDevicesString(), INPUTMAN, INPUTMAPPER, DeviceInput::IsValid(), RageTimer::IsZero(), m_AutoDismissNoSetListPromptSecs, m_AutoDismissSanitySecs, m_AutoDismissWarningSecs, m_ChangeOccurred, m_CurController, m_CurSlot, m_DeviceIToMap, Screen::m_fLockInputSecs, ScreenMapControllers::KeyToMap::m_GameButton, m_InSetListMode, m_KeysToMap, m_NoSetListPrompt, m_SanityMessage, m_SetList, m_SetListCurrent, m_textDevices, ScreenMapControllers::KeyToMap::m_textMappedTo, m_WaitingForPress, RageTimer::PeekDeltaTime(), Actor::PlayCommand(), ScreenManager::PlayStartSound(), Refresh(), SCREENMAN, SetCursorFromSetListCurrent(), InputMapper::SetInputMap(), BitmapText::SetText(), RageTimer::SetZero(), StartWaitingForPress(), and ScreenWithMenuElements::Update().
Member Data Documentation
m_Actions
vector<ActionRow> ScreenMapControllers::m_Actions private
Referenced by CursorCanGoDown(), GetActorWithFocus(), Init(), and Input().
m_AutoDismissNoSetListPromptSecs
float ScreenMapControllers::m_AutoDismissNoSetListPromptSecs private
Referenced by BeginScreen(), Input(), SetListMode(), and Update().
m_AutoDismissSanitySecs
float ScreenMapControllers::m_AutoDismissSanitySecs private
Referenced by BeginScreen(), Input(), SanityCheckWrapper(), and Update().
m_AutoDismissWarningSecs
float ScreenMapControllers::m_AutoDismissWarningSecs private
Referenced by BeginScreen(), Input(), and Update().
m_ChangeOccurred
bool ScreenMapControllers::m_ChangeOccurred private
Referenced by ExitAction(), SaveToDisk(), ScreenMapControllers(), and Update().
m_CurButton
unsigned int ScreenMapControllers::m_CurButton private
Referenced by BeginScreen(), CurActionIndex(), CurKeyIndex(), CursorCanGoDown(), CursorCanGoUp(), CursorOnAction(), CursorOnHeader(), Input(), Refresh(), and SetCursorFromSetListCurrent().
m_CurController
unsigned int ScreenMapControllers::m_CurController private
Referenced by BeginScreen(), CursorCanGoLeft(), CursorCanGoRight(), GetActorWithFocus(), Input(), SetCursorFromSetListCurrent(), StartWaitingForPress(), and Update().
m_CurSlot
unsigned int ScreenMapControllers::m_CurSlot private
Referenced by BeginScreen(), CursorCanGoLeft(), CursorCanGoRight(), GetActorWithFocus(), Input(), SetCursorFromSetListCurrent(), StartWaitingForPress(), and Update().
m_DeviceIToMap
DeviceInput ScreenMapControllers::m_DeviceIToMap private
Referenced by Input(), StartWaitingForPress(), and Update().
m_InSetListMode
bool ScreenMapControllers::m_InSetListMode private
Referenced by ScreenMapControllers(), SetListMode(), and Update().
m_KeysToMap
vector<KeyToMap> ScreenMapControllers::m_KeysToMap private
Referenced by CurActionIndex(), CursorCanGoDown(), CursorOnAction(), GetActorWithFocus(), Init(), Input(), Refresh(), StartWaitingForPress(), and Update().
m_Line
vector<ActorFrame*> ScreenMapControllers::m_Line private
Referenced by Init(), and ~ScreenMapControllers().
m_LineScroller
ActorScroller ScreenMapControllers::m_LineScroller private
Referenced by Init(), and Refresh().
m_ListHeaderCenter
BitmapText ScreenMapControllers::m_ListHeaderCenter private
Referenced by Init().
m_ListHeaderLabels
BitmapText ScreenMapControllers::m_ListHeaderLabels[NUM_GameController][NUM_SHOWN_GAME_TO_DEVICE_SLOTS] private
Referenced by GetActorWithFocus(), and Init().
m_MaxDestItem
unsigned int ScreenMapControllers::m_MaxDestItem private
Referenced by Init(), and Refresh().
m_NoSetListPrompt
AutoActor ScreenMapControllers::m_NoSetListPrompt private
Referenced by Init(), Input(), SetListMode(), and Update().
m_SanityMessage
AutoActor ScreenMapControllers::m_SanityMessage private
Referenced by Init(), Input(), SanityCheckWrapper(), and Update().
m_SetList
set<SetListEntry> ScreenMapControllers::m_SetList private
Referenced by Input(), SetListMode(), and Update().
m_SetListCurrent
set<SetListEntry>::iterator ScreenMapControllers::m_SetListCurrent private
Referenced by SetCursorFromSetListCurrent(), SetListMode(), and Update().
m_soundChange
RageSound ScreenMapControllers::m_soundChange private
Referenced by Init(), and Input().
m_soundDelete
RageSound ScreenMapControllers::m_soundDelete private
Referenced by Init(), and Input().
m_textDevices
BitmapText ScreenMapControllers::m_textDevices private
Referenced by Init(), and Update().
m_textLabel
BitmapText ScreenMapControllers::m_textLabel[NUM_GameController] private
Referenced by Init().
m_WaitingForPress
RageTimer ScreenMapControllers::m_WaitingForPress private
Referenced by BeginScreen(), Input(), StartWaitingForPress(), and Update().
m_Warning
AutoActor ScreenMapControllers::m_Warning private
Referenced by BeginScreen(), DismissWarning(), and Init().
The documentation for this class was generated from the following files:
ScreenMapControllers.h
ScreenMapControllers.cpp