Etterna: RageException.cpp File Reference
RageException.cpp File Reference
#include "global.h"
#include "RageException.h"
#include "RageLog.h"
#include "RageThreads.h"
#include "RageUtil.h"
#include <cstdarg>
Variables
static uint64_t g_HandlerThreadID = RageThread::GetInvalidThreadID()
static void(* g_CleanupHandler)(const RString &sError) = NULL
Variable Documentation
g_CleanupHandler
void(* g_CleanupHandler) (const RString &sError) = NULL static
Referenced by RageException::SetCleanupHandler(), and RageException::Throw().
g_HandlerThreadID
uint64_t g_HandlerThreadID = RageThread::GetInvalidThreadID() static
Referenced by RageException::SetCleanupHandler(), and RageException::Throw().