Etterna: GameSoundManager Class Reference
GameSoundManager Class Reference
High-level sound utilities.
#include <GameSoundManager.h>
Classes
struct PlayMusicParams
Public Member Functions
GameSoundManager ()
~GameSoundManager ()
void Update (float fDeltaTime)
void PlayMusic (PlayMusicParams params, PlayMusicParams FallbackMusicParams=PlayMusicParams())
void PlayMusic (const RString &sFile, const TimingData *pTiming=NULL, bool force_loop=false, float start_sec=0, float length_sec=-1, float fFadeInLengthSeconds=0, float fade_len=0, bool align_beat=true, bool bApplyMusicRate=false)
void StopMusic ()
void DimMusic (float fVolume, float fDurationSeconds)
RString GetMusicPath () const
void Flush ()
void PlayOnce (const RString &sPath)
void PlayOnceFromDir (const RString &sDir)
void PlayOnceFromAnnouncer (const RString &sFolderName)
void HandleSongTimer (bool on=true)
float GetFrameTimingAdjustment (float fDeltaTime)
void PushSelf (lua_State *L)
Static Public Member Functions
static float GetPlayerBalance (PlayerNumber pn)
Detailed Description
High-level sound utilities.
Constructor & Destructor Documentation
GameSoundManager()
GameSoundManager::GameSoundManager ()
References ASSERT, RageThread::Create(), g_Shutdown, g_UpdatingTimer, LuaManager::Get(), L, LUA, MusicThread_start(), PushSelf(), LuaManager::Release(), RageThread::SetName(), and SOUNDMAN.
~GameSoundManager()
GameSoundManager::~GameSoundManager ()
References RageEvent::Broadcast(), g_Shutdown, RageMutex::Lock(), LOG, LUA, SAFE_DELETE, RageLog::Trace(), RageMutex::Unlock(), LuaManager::UnsetGlobal(), and RageThread::Wait().
Member Function Documentation
DimMusic()
void GameSoundManager::DimMusic (float fVolume, float fDurationSeconds)
References FADE_NONE, FADE_OUT, g_FadeState, g_fDimDurationRemaining, g_fDimVolume, g_fOriginalVolume, RageSound::GetParams(), LockMut, MusicPlaying::m_Music, and RageSoundParams::m_Volume.
Referenced by GameCommand::ApplySelf(), and LunaGameSoundManager::DimMusic().
Flush()
void GameSoundManager::Flush ()
References RageEvent::Broadcast(), g_bFlushing, RageMutex::Lock(), RageMutex::Unlock(), and RageEvent::Wait().
Referenced by ScreenManager::Update().
GetFrameTimingAdjustment()
float GameSoundManager::GetFrameTimingAdjustment (float fDeltaTime)
References DISPLAY, RageDisplay::GetActualVideoModeParams(), RageDisplay::GetFPS(), and min().
Referenced by Update(), and ScreenGameplay::UpdateSongPosition().
GetMusicPath()
RString GameSoundManager::GetMusicPath () const
References RageSound::GetLoadedFilePath(), LockMut, and MusicPlaying::m_Music.
Referenced by ScreenSelectMusic::AfterMusicChange(), and ScreenNetSelectMusic::MusicChanged().
GetPlayerBalance()
float GameSoundManager::GetPlayerBalance (PlayerNumber pn) static
References GAMESTATE, GameState::GetNumPlayersEnabled(), and PLAYER_1.
Referenced by ScreenSelectMusic::ChangeSteps(), LunaGameSoundManager::GetPlayerBalance(), Player::Init(), and Player::Load().
HandleSongTimer()
void GameSoundManager::HandleSongTimer (bool on = true)
References g_UpdatingTimer, and LockMut.
Referenced by ScreenHowToPlay::HandleScreenMessage(), and ScreenGameplay::HandleScreenMessage().
PlayMusic() [1/2]
void GameSoundManager::PlayMusic (PlayMusicParams params, PlayMusicParams FallbackMusicParams = PlayMusicParams())
References GameSoundManager::PlayMusicParams::bAlignBeat, MusicToPlay::bAlignBeat, GameSoundManager::PlayMusicParams::bApplyMusicRate, MusicToPlay::bApplyMusicRate, GameSoundManager::PlayMusicParams::bForceLoop, MusicToPlay::bForceLoop, RageEvent::Broadcast(), GameSoundManager::PlayMusicParams::fFadeInLengthSeconds, MusicToPlay::fFadeInLengthSeconds, GameSoundManager::PlayMusicParams::fFadeOutLengthSeconds, MusicToPlay::fFadeOutLengthSeconds, GameSoundManager::PlayMusicParams::fLengthSeconds, MusicToPlay::fLengthSeconds, GameSoundManager::PlayMusicParams::fStartSecond, MusicToPlay::fStartSecond, g_MusicsToPlay, MusicToPlay::HasTiming, RageMutex::Lock(), MusicToPlay::m_sFile, MusicToPlay::m_sTimingFile, MusicToPlay::m_TimingData, GameSoundManager::PlayMusicParams::pTiming, SetExtension(), GameSoundManager::PlayMusicParams::sFile, and RageMutex::Unlock().
Referenced by ScreenSelectMusic::CheckBackgroundRequests(), ScreenSMOnlineLogin::Init(), ScreenNetSelectMusic::MusicChanged(), PlayMusic(), LunaGameSoundManager::PlayMusicPart(), ScreenWithMenuElements::StartPlayingMusic(), StopMusic(), and Update().
PlayMusic() [2/2]
void GameSoundManager::PlayMusic (const RString & sFile, const TimingData * pTiming = NULL, bool force_loop = false, float start_sec = 0, float length_sec = -1, float fFadeInLengthSeconds = 0, float fade_len = 0, bool align_beat = true, bool bApplyMusicRate = false)
References GameSoundManager::PlayMusicParams::bAlignBeat, GameSoundManager::PlayMusicParams::bApplyMusicRate, GameSoundManager::PlayMusicParams::bForceLoop, GameSoundManager::PlayMusicParams::fFadeInLengthSeconds, GameSoundManager::PlayMusicParams::fFadeOutLengthSeconds, GameSoundManager::PlayMusicParams::fLengthSeconds, GameSoundManager::PlayMusicParams::fStartSecond, PlayMusic(), GameSoundManager::PlayMusicParams::pTiming, and GameSoundManager::PlayMusicParams::sFile.
PlayOnce()
void GameSoundManager::PlayOnce (const RString & sPath)
References RageEvent::Broadcast(), g_SoundsToPlayOnce, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by GameCommand::ApplySelf(), and LunaGameSoundManager::PlayOnce().
PlayOnceFromAnnouncer()
void GameSoundManager::PlayOnceFromAnnouncer (const RString & sFolderName)
References RageEvent::Broadcast(), g_SoundsToPlayOnceFromAnnouncer, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by ScreenWithMenuElements::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenGameplay::BeginScreen(), ScreenGameplay::HandleScreenMessage(), ScreenTitleMenu::Init(), ScreenGameplay::PlayAnnouncer(), LunaGameSoundManager::PlayAnnouncer(), ScreenSelectMusic::SelectCurrent(), ScreenSelect::Update(), MenuTimer::Update(), and ScreenSelectMusic::Update().
PlayOnceFromDir()
void GameSoundManager::PlayOnceFromDir (const RString & sDir)
References RageEvent::Broadcast(), g_SoundsToPlayOnceFromDir, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by ScreenGameplay::FailFadeRemovePlayer(), ScreenEvaluation::HandleScreenMessage(), ScreenPlayerOptions::Init(), ScreenEvaluation::Init(), and ScreenSelectMaster::MenuStart().
PushSelf()
void GameSoundManager::PushSelf (lua_State * L)
Referenced by GameSoundManager().
StopMusic()
void GameSoundManager::StopMusic () inline
References PlayMusic().
Referenced by ScreenSelectMusic::AfterMusicChange(), GameCommand::ApplySelf(), ScreenWithMenuElements::Cancel(), DebugLineReloadCurrentScreen::DoAndLog(), ScreenNetSelectBase::HandleScreenMessage(), ScreenAttract::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::MenuBack(), ScreenNetSelectMusic::MusicChanged(), and LunaGameSoundManager::StopMusic().
Update()
void GameSoundManager::Update (float fDeltaTime)
References Basename(), BeatToNoteRow(), MessageManager::Broadcast(), CHECKPOINT_M, f, FADE_IN, FADE_NONE, FADE_OUT, FADE_WAIT, fapproach(), g_bWasPlayingOnLastUpdate, g_FadeState, g_fDimDurationRemaining, g_fDimVolume, g_fOriginalVolume, g_UpdatingTimer, GAMESTATE, GetFrameTimingAdjustment(), RageSound::GetLoadedFilePath(), RageSound::GetParams(), RageSound::GetPlaybackRate(), RageSound::GetPositionSeconds(), ModsGroup< T >::GetPreferred(), RageSound::IsPlaying(), RageMutex::Lock(), LockMut, LOG, MusicPlaying::m_bApplyMusicRate, PrefsManager::m_bLogSkips, MusicPlaying::m_bTimingDelayed, RageSoundParams::m_fFadeInSeconds, RageSoundParams::m_fFadeOutSeconds, SongOptions::m_fMusicRate, SongPosition::m_fMusicSeconds, SongPosition::m_fSongBeat, RageSoundParams::m_fSpeed, SongPosition::m_LastBeatUpdate, MusicPlaying::m_Music, MusicPlaying::m_NewTiming, GameState::m_pCurSong, GameState::m_Position, GameState::m_SongOptions, MusicPlaying::m_Timing, RageSoundParams::m_Volume, max(), MESSAGEMAN, PlayMusic(), PREFSMAN, ROWS_PER_BEAT, Message::SetParam(), RageSound::SetParams(), GameSoundManager::PlayMusicParams::sFile, ssprintf(), RageLog::Trace(), RageMutex::Unlock(), and GameState::UpdateSongPosition().
Referenced by GameLoop::RunGameLoop().
The documentation for this class was generated from the following files:
GameSoundManager.h
GameSoundManager.cpp