Etterna: RageDisplay_GLES2 Class Reference
RageDisplay_GLES2 Class Reference
#include <RageDisplay_GLES2.h>
Public Member Functions
RageDisplay_GLES2 ()
~RageDisplay_GLES2 () override
RString Init (const VideoModeParams &p, bool bAllowUnacceleratedRenderer) override
RString GetApiDescription () const override
virtual void GetDisplayResolutions (DisplayResolutions &out) const override
const RagePixelFormatDesc * GetPixelFormatDesc (RagePixelFormat pf) const override
bool BeginFrame () override
void EndFrame () override
const VideoModeParams * GetActualVideoModeParams () const override
void SetBlendMode (BlendMode mode) override
bool SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime=false) override
bool SupportsPerVertexMatrixScale () override
unsigned CreateTexture (RagePixelFormat pixfmt, RageSurface *img, bool bGenerateMipMaps) override
void UpdateTexture (unsigned iTexHandle, RageSurface *img, int xoffset, int yoffset, int width, int height) override
void DeleteTexture (unsigned iTexHandle) override
void ClearAllTextures () override
int GetNumTextureUnits () override
void SetTexture (TextureUnit tu, unsigned iTexture) override
void SetTextureMode (TextureUnit tu, TextureMode tm) override
void SetTextureWrapping (TextureUnit tu, bool b) override
int GetMaxTextureSize () const override
void SetTextureFiltering (TextureUnit tu, bool b) override
bool IsZWriteEnabled () const override
bool IsZTestEnabled () const override
void SetZWrite (bool b) override
void SetZBias (float f) override
void SetZTestMode (ZTestMode mode) override
void ClearZBuffer () override
void SetCullMode (CullMode mode) override
void SetAlphaTest (bool b) override
void SetMaterial (const RageColor &emissive, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, float shininess) override
void SetLighting (bool b) override
void SetLightOff (int index) override
void SetLightDirectional (int index, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, const RageVector3 &dir) override
void SetSphereEnvironmentMapping (TextureUnit tu, bool b) override
void SetCelShaded (int stage) override
void SetLineWidth (float fWidth) override
void SetPolygonMode (PolygonMode pm) override
RageCompiledGeometry * CreateCompiledGeometry () override
void DeleteCompiledGeometry (RageCompiledGeometry *p) override
Public Member Functions inherited from RageDisplay
RageDisplay ()
virtual ~RageDisplay ()
void SetPresentTime (std::chrono::nanoseconds presentTime)
RString SetVideoMode (VideoModeParams p, bool &bNeedReloadTextures)
virtual void ResolutionChanged ()
bool IsD3D ()
bool IsWindowed ()
virtual bool SupportsThreadedRendering ()
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void BeginConcurrentRendering ()
virtual void EndConcurrentRendering ()
virtual RageTextureLock * CreateTextureLock ()
virtual void SetEffectMode (EffectMode)
virtual bool IsEffectModeSupported (EffectMode effect)
bool SupportsRenderToTexture () const
virtual unsigned CreateRenderTarget (const RenderTargetParam &, int &, int &)
virtual unsigned GetRenderTarget ()
virtual void SetRenderTarget (unsigned, bool=true)
void DrawQuads (const RageSpriteVertex v[], int iNumVerts)
void DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawFan (const RageSpriteVertex v[], int iNumVerts)
void DrawStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
void DrawCompiledGeometry (const RageCompiledGeometry *p, int iMeshIndex, const vector< msMesh > &vMeshes)
void DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawCircle (const RageSpriteVertex &v, float radius)
void DrawQuad (const RageSpriteVertex v[])
bool SaveScreenshot (const RString &sPath, GraphicsFileFormat format)
virtual RString GetTextureDiagnostics (unsigned) const
virtual RageSurface * GetTexture (unsigned)
bool IsPredictiveFrameLimit () const
int GetFPS () const
int GetVPF () const
int GetCumFPS () const
virtual void ResetStats ()
virtual void ProcessStatsOnFlip ()
virtual RString GetStats () const
void StatsAddVerts (int iNumVertsRendered)
void PushMatrix ()
void PopMatrix ()
void Translate (float x, float y, float z)
void TranslateWorld (float x, float y, float z)
void Scale (float x, float y, float z)
void RotateX (float deg)
void RotateY (float deg)
void RotateZ (float deg)
void SkewX (float fAmount)
void SkewY (float fAmount)
void MultMatrix (const RageMatrix &f)
void PostMultMatrix (const RageMatrix &f)
void PreMultMatrix (const RageMatrix &f)
void LoadIdentity ()
void TexturePushMatrix ()
void TexturePopMatrix ()
void TextureTranslate (float x, float y)
void TextureTranslate (const RageVector2 &v)
void CameraPushMatrix ()
void CameraPopMatrix ()
void LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
void LoadLookAt (float fov, const RageVector3 &Eye, const RageVector3 &At, const RageVector3 &Up)
void CenteringPushMatrix ()
void CenteringPopMatrix ()
void ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
RageSurface * CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void *pixels, int width, int height, int pitch)
RagePixelFormat FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime=false)
void PushSelf (lua_State *L)
Protected Member Functions
void DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawCompiledGeometryInternal (const RageCompiledGeometry *p, int iMeshIndex) override
void DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth) override
void DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut) override
RageSurface * CreateScreenshot () override
RageMatrix GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override
bool SupportsSurfaceFormat (RagePixelFormat pixfmt)
bool SupportsRenderToTexture () const
Protected Member Functions inherited from RageDisplay
virtual void DrawCircleInternal (const RageSpriteVertex &v, float radius)
virtual bool IsD3DInternal ()
void DrawPolyLine (const RageSpriteVertex &p1, const RageSpriteVertex &p2, float LineWidth)
void DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void SetDefaultRenderStates ()
RageMatrix GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar)
virtual RageMatrix GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf)
RageMatrix GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight)
void UpdateCentering ()
const RageMatrix * GetCentering () const
const RageMatrix * GetProjectionTop () const
const RageMatrix * GetViewTop () const
const RageMatrix * GetWorldTop () const
const RageMatrix * GetTextureTop () const
void FrameLimitBeforeVsync ()
void FrameLimitAfterVsync (int iFPS)
Additional Inherited Members
Public Types inherited from RageDisplay
enum GraphicsFileFormat { SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_LOW_QUAL, SAVE_LOSSY_HIGH_QUAL }
Constructor & Destructor Documentation
RageDisplay_GLES2()
RageDisplay_GLES2::RageDisplay_GLES2 ()
References FixLittleEndian(), LOG, RageLog::MapLog(), and RageLog::Trace().
~RageDisplay_GLES2()
RageDisplay_GLES2::~RageDisplay_GLES2 () override
References g_pWind.
Member Function Documentation
BeginFrame()
bool RageDisplay_GLES2::BeginFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::BeginFrame(), f, LowLevelWindow::GetActualVideoModeParams(), VideoModeParams::height, SetZWrite(), and VideoModeParams::width.
ClearAllTextures()
void RageDisplay_GLES2::ClearAllTextures () override virtual
Implements RageDisplay.
References FOREACH_ENUM, and SetTexture().
ClearZBuffer()
void RageDisplay_GLES2::ClearZBuffer () override virtual
Implements RageDisplay.
References IsZWriteEnabled(), and SetZWrite().
CreateCompiledGeometry()
RageCompiledGeometry * RageDisplay_GLES2::CreateCompiledGeometry () override virtual
Implements RageDisplay.
CreateScreenshot()
RageSurface * RageDisplay_GLES2::CreateScreenshot () override protected virtual
Implements RageDisplay.
References RageDisplay::RagePixelFormatDesc::bpp, CreateSurface(), RageDisplay::RagePixelFormatDesc::masks, RageSurface::pitch, RageSurface::pixels, and RagePixelFormat_RGB8.
CreateTexture()
unsigned RageDisplay_GLES2::CreateTexture (RagePixelFormat pixfmt, RageSurface * img, bool bGenerateMipMaps) override virtual
Implements RageDisplay.
DeleteCompiledGeometry()
void RageDisplay_GLES2::DeleteCompiledGeometry (RageCompiledGeometry * p) override virtual
Implements RageDisplay.
DeleteTexture()
void RageDisplay_GLES2::DeleteTexture (unsigned iTexHandle) override virtual
Implements RageDisplay.
DrawCompiledGeometryInternal()
void RageDisplay_GLES2::DrawCompiledGeometryInternal (const RageCompiledGeometry * p, int iMeshIndex) override protected virtual
Implements RageDisplay.
DrawFanInternal()
void RageDisplay_GLES2::DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
DrawLineStripInternal()
void RageDisplay_GLES2::DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth) override protected virtual
Reimplemented from RageDisplay.
DrawQuadsInternal()
void RageDisplay_GLES2::DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
DrawQuadStripInternal()
void RageDisplay_GLES2::DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
DrawStripInternal()
void RageDisplay_GLES2::DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
DrawSymmetricQuadStripInternal()
void RageDisplay_GLES2::DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
DrawTrianglesInternal()
void RageDisplay_GLES2::DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
EndFrame()
void RageDisplay_GLES2::EndFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::EndFrame(), RageDisplay::FrameLimitAfterVsync(), RageDisplay::FrameLimitBeforeVsync(), LowLevelWindow::GetActualVideoModeParams(), VideoModeParams::rate, LowLevelWindow::SwapBuffers(), and LowLevelWindow::Update().
GetActualVideoModeParams()
const VideoModeParams * RageDisplay_GLES2::GetActualVideoModeParams () const override virtual
Implements RageDisplay.
References LowLevelWindow::GetActualVideoModeParams().
GetApiDescription()
RString RageDisplay_GLES2::GetApiDescription () const override virtual
Implements RageDisplay.
GetDisplayResolutions()
void RageDisplay_GLES2::GetDisplayResolutions (DisplayResolutions & out) const override virtual
Implements RageDisplay.
References LowLevelWindow::GetDisplayResolutions().
GetMaxTextureSize()
int RageDisplay_GLES2::GetMaxTextureSize () const override virtual
Implements RageDisplay.
GetNumTextureUnits()
int RageDisplay_GLES2::GetNumTextureUnits () override virtual
Implements RageDisplay.
GetOrthoMatrix()
RageMatrix RageDisplay_GLES2::GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override protected virtual
Reimplemented from RageDisplay.
GetPixelFormatDesc()
const RageDisplay::RagePixelFormatDesc * RageDisplay_GLES2::GetPixelFormatDesc (RagePixelFormat pf) const override virtual
Implements RageDisplay.
References ASSERT.
Init()
RString RageDisplay_GLES2::Init (const VideoModeParams & p, bool bAllowUnacceleratedRenderer) override virtual
Implements RageDisplay.
References LowLevelWindow::Create(), RageLog::Info(), Rage::join(), LOG, LowLevelWindow::LogDebugInformation(), RageDisplay::SetVideoMode(), split(), and ssprintf().
IsZTestEnabled()
bool RageDisplay_GLES2::IsZTestEnabled () const override virtual
Implements RageDisplay.
IsZWriteEnabled()
bool RageDisplay_GLES2::IsZWriteEnabled () const override virtual
Implements RageDisplay.
Referenced by ClearZBuffer().
SetAlphaTest()
void RageDisplay_GLES2::SetAlphaTest (bool b) override virtual
Implements RageDisplay.
SetBlendMode()
void RageDisplay_GLES2::SetBlendMode (BlendMode mode) override virtual
Implements RageDisplay.
SetCelShaded()
void RageDisplay_GLES2::SetCelShaded (int stage) override virtual
Implements RageDisplay.
SetCullMode()
void RageDisplay_GLES2::SetCullMode (CullMode mode) override virtual
Implements RageDisplay.
References CULL_BACK, CULL_FRONT, CULL_NONE, FAIL_M, and ssprintf().
SetLightDirectional()
void RageDisplay_GLES2::SetLightDirectional (int index, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, const RageVector3 & dir) override virtual
Implements RageDisplay.
SetLighting()
void RageDisplay_GLES2::SetLighting (bool b) override virtual
Implements RageDisplay.
SetLightOff()
void RageDisplay_GLES2::SetLightOff (int index) override virtual
Implements RageDisplay.
SetLineWidth()
void RageDisplay_GLES2::SetLineWidth (float fWidth) override virtual
Reimplemented from RageDisplay.
SetMaterial()
void RageDisplay_GLES2::SetMaterial (const RageColor & emissive, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, float shininess) override virtual
Implements RageDisplay.
SetPolygonMode()
void RageDisplay_GLES2::SetPolygonMode (PolygonMode pm) override virtual
Reimplemented from RageDisplay.
References FAIL_M, POLYGON_FILL, POLYGON_LINE, and ssprintf().
SetSphereEnvironmentMapping()
void RageDisplay_GLES2::SetSphereEnvironmentMapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
SetTexture()
void RageDisplay_GLES2::SetTexture (TextureUnit tu, unsigned iTexture) override virtual
Implements RageDisplay.
References SetTextureUnit().
Referenced by ClearAllTextures().
SetTextureFiltering()
void RageDisplay_GLES2::SetTextureFiltering (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References VideoModeParams::bTrilinearFiltering, and LowLevelWindow::GetActualVideoModeParams().
SetTextureMode()
void RageDisplay_GLES2::SetTextureMode (TextureUnit tu, TextureMode tm) override virtual
Implements RageDisplay.
SetTextureWrapping()
void RageDisplay_GLES2::SetTextureWrapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
SetZBias()
void RageDisplay_GLES2::SetZBias (float f) override virtual
Implements RageDisplay.
References SCALE.
SetZTestMode()
void RageDisplay_GLES2::SetZTestMode (ZTestMode mode) override virtual
Implements RageDisplay.
References FAIL_M, ssprintf(), ZTEST_OFF, ZTEST_WRITE_ON_FAIL, and ZTEST_WRITE_ON_PASS.
SetZWrite()
void RageDisplay_GLES2::SetZWrite (bool b) override virtual
Implements RageDisplay.
Referenced by BeginFrame(), and ClearZBuffer().
SupportsPerVertexMatrixScale()
bool RageDisplay_GLES2::SupportsPerVertexMatrixScale () override virtual
Implements RageDisplay.
SupportsRenderToTexture()
bool RageDisplay_GLES2::SupportsRenderToTexture () const inline protected
SupportsSurfaceFormat()
bool RageDisplay_GLES2::SupportsSurfaceFormat (RagePixelFormat pixfmt) protected
References g_GLPixFmtInfo.
Referenced by SupportsTextureFormat().
SupportsTextureFormat()
bool RageDisplay_GLES2::SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime = false) override virtual
Implements RageDisplay.
References g_GLPixFmtInfo, and SupportsSurfaceFormat().
TryVideoMode()
RString RageDisplay_GLES2::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) override protected virtual
Implements RageDisplay.
References VideoModeParams::bpp, VideoModeParams::height, RageTextureManager::InvalidateTextures(), LOG, VideoModeParams::rate, RageDisplay::ResolutionChanged(), TEXTUREMAN, LowLevelWindow::TryVideoMode(), VideoModeParams::vsync, RageLog::Warn(), VideoModeParams::width, and VideoModeParams::windowed.
UpdateTexture()
void RageDisplay_GLES2::UpdateTexture (unsigned iTexHandle, RageSurface * img, int xoffset, int yoffset, int width, int height) override virtual
Implements RageDisplay.
The documentation for this class was generated from the following files:
RageDisplay_GLES2.h
RageDisplay_GLES2.cpp