Etterna: XNodeValue Class Reference
XNodeValue Class Reference abstract
#include <XmlFile.h>
Public Member Functions
virtual ~XNodeValue ()=default
virtual XNodeValue * Copy () const =0
virtual void GetValue (RString &out) const =0
virtual void GetValue (int &out) const =0
virtual void GetValue (float &out) const =0
virtual void GetValue (bool &out) const =0
virtual void GetValue (unsigned &out) const =0
virtual void PushValue (lua_State *L) const =0
template<typename T >
T GetValue () const
virtual void SetValue (const RString &v)=0
virtual void SetValue (int v)=0
virtual void SetValue (float v)=0
virtual void SetValue (unsigned v)=0
virtual void SetValueFromStack (lua_State *L)=0
Constructor & Destructor Documentation
~XNodeValue()
virtual XNodeValue::~XNodeValue () virtual default
Member Function Documentation
Copy()
virtual XNodeValue* XNodeValue::Copy () const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
GetValue() [1/6]
virtual void XNodeValue::GetValue (RString & out) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
Referenced by XNode::GetAttrValue(), Font::LoadFontPageSettings(), Actor::LoadFromNode(), and actor_template_t::store_field().
GetValue() [2/6]
virtual void XNodeValue::GetValue (int & out) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
GetValue() [3/6]
virtual void XNodeValue::GetValue (float & out) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
GetValue() [4/6]
virtual void XNodeValue::GetValue (bool & out) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
GetValue() [5/6]
virtual void XNodeValue::GetValue (unsigned & out) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
GetValue() [6/6]
template<typename T > T XNodeValue::GetValue () const inline
References T.
PushValue()
virtual void XNodeValue::PushValue (lua_State * L) const pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
Referenced by Actor::LoadFromNode(), XNode::PushAttrValue(), and XNode::PushChildValue().
SetValue() [1/4]
virtual void XNodeValue::SetValue (const RString & v) pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
Referenced by XNode::AppendAttr().
SetValue() [2/4]
virtual void XNodeValue::SetValue (int v) pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
SetValue() [3/4]
virtual void XNodeValue::SetValue (float v) pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
SetValue() [4/4]
virtual void XNodeValue::SetValue (unsigned v) pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
SetValueFromStack()
virtual void XNodeValue::SetValueFromStack (lua_State * L) pure virtual
Implemented in XNodeLuaValue, and XNodeStringValue.
The documentation for this class was generated from the following file:
XmlFile.h