Etterna: OptionsList Class Reference
OptionsList Class Reference
A popup options list.
#include <OptionsList.h>
Public Member Functions
OptionsList ()
~OptionsList () override
void Load (const RString &sType, PlayerNumber pn)
void Reset ()
void Link (OptionsList *pLink)
void Open ()
Show the top-level menu.
void Close ()
Close all menus (for menu timer).
bool Input (const InputEventPlus &input)
bool IsOpened () const
bool Start ()
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushSelf (lua_State *L) override
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
virtual void Update (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Private Member Functions
void SelectItem (const RString &sRowName, int iMenuItem)
void MoveItem (const RString &sRowName, int iMove)
void SwitchMenu (int iDir)
void PositionCursor ()
void SelectionsChanged (const RString &sRowName)
void UpdateMenuFromSelections ()
RString GetCurrentRow () const
const OptionRowHandler * GetCurrentHandler ()
int GetOneSelection (const RString &sRow, bool bAllowFail=false) const
void SwitchToCurrentRow ()
void TweenOnCurrentRow (bool bForward)
void SetDefaultCurrentRow ()
void Push (const RString &sDest)
void Pop ()
void ImportRow (const RString &sRow)
void ExportRow (const RString &sRow)
Static Private Member Functions
static int FindScreenInHandler (const OptionRowHandler *pHandler, const RString &sScreen)
Private Attributes
ThemeMetric< RString > TOP_MENU
InputQueueCodeSet m_Codes
OptionsList * m_pLinked
bool m_bStartIsDown
bool m_bAcceptStartRelease
vector< RString > m_asLoadedRows
map< RString, OptionRowHandler * > m_Rows
map< RString, vector< bool > > m_bSelections
set< RString > m_setDirectRows
set< RString > m_setTopMenus
PlayerNumber m_pn
AutoActor m_Cursor
OptionListRow m_Row [2]
int m_iCurrentRow
vector< RString > m_asMenuStack
int m_iMenuStackSelection
Friends
class OptionListRow
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A popup options list.
Constructor & Destructor Documentation
OptionsList()
OptionsList::OptionsList ()
References m_iCurrentRow, and m_pLinked.
~OptionsList()
OptionsList::~OptionsList () override
References FOREACHM, and m_Rows.
Member Function Documentation
Close()
void OptionsList::Close ()
Close all menus (for menu timer).
References MessageManager::Broadcast(), m_asMenuStack, m_bStartIsDown, m_pn, MESSAGEMAN, Actor::PlayCommand(), and Message::SetParam().
Referenced by Input(), Pop(), and ScreenSelectMusic::SelectCurrent().
ExportRow()
void OptionsList::ExportRow (const RString & sRow) private
References m_bSelections, m_pn, m_Rows, m_setTopMenus, and NUM_PLAYERS.
Referenced by SelectionsChanged().
FindScreenInHandler()
int OptionsList::FindScreenInHandler (const OptionRowHandler * pHandler, const RString & sScreen) static private
References OptionRowHandler::GetScreen(), OptionRowHandler::m_Def, and OptionRowDefinition::m_vsChoices.
Referenced by Pop(), and SwitchMenu().
GetCurrentHandler()
const OptionRowHandler * OptionsList::GetCurrentHandler () private
References GetCurrentRow(), and m_Rows.
Referenced by Input(), Pop(), Start(), SwitchToCurrentRow(), and UpdateMenuFromSelections().
GetCurrentRow()
RString OptionsList::GetCurrentRow () const private
References ASSERT, and m_asMenuStack.
Referenced by GetCurrentHandler(), Start(), and UpdateMenuFromSelections().
GetOneSelection()
int OptionsList::GetOneSelection (const RString & sRow, bool bAllowFail = false) const private
References ASSERT, ASSERT_M, and m_bSelections.
Referenced by Input(), SetDefaultCurrentRow(), OptionListRow::SetTextFromHandler(), and OptionListRow::SetUnderlines().
ImportRow()
void OptionsList::ImportRow (const RString & sRow) private
References OptionRowHandler::ImportOption(), m_bSelections, OptionRowHandler::m_Def, m_pn, m_Rows, m_setTopMenus, OptionRowDefinition::m_vsChoices, and NUM_PLAYERS.
Referenced by Reset(), and Start().
Input()
bool OptionsList::Input (const InputEventPlus & input)
References MessageManager::Broadcast(), Close(), GAME_BUTTON_LEFT, GAME_BUTTON_RIGHT, GAME_BUTTON_SELECT, GAME_BUTTON_START, GetCurrentHandler(), GetOneSelection(), OptionRowHandler::GetScreen(), ActorFrame::HandleMessage(), IET_FIRST_PRESS, IET_RELEASE, INPUTMAPPER, InputQueueCodeSet::InputMessage(), InputMapper::IsBeingPressed(), m_asMenuStack, m_bAcceptStartRelease, m_bSelections, m_bStartIsDown, m_Codes, OptionRowHandler::m_Def, m_iMenuStackSelection, m_Rows, OptionRowDefinition::m_selectType, m_setDirectRows, OptionRowDefinition::m_vsChoices, InputEventPlus::MenuI, MESSAGEMAN, InputEventPlus::pn, PositionCursor(), SELECT_ONE, SelectItem(), Message::SetParam(), Start(), SwitchMenu(), InputEventPlus::type, and wrap().
Referenced by ScreenSelectMusic::Input().
IsOpened()
bool OptionsList::IsOpened () const inline
References m_asMenuStack.
Referenced by SelectionsChanged().
Link()
void OptionsList::Link (OptionsList * pLink) inline
References m_pLinked.
Referenced by ScreenSelectMusic::Init().
Load()
void OptionsList::Load (const RString & sType, PlayerNumber pn)
References ActorFrame::AddChild(), DIRECT_LINES, ActorFrame::FinishTweening(), FOREACH, Commands::GetOriginalCommandString(), ThemeManager::GetPathG(), OptionRowHandler::GetScreen(), LINE, InputQueueCodeSet::Load(), OptionListRow::Load(), AutoActor::Load(), ThemeMetric< T >::Load(), ActorUtil::LoadAllCommands(), m_asLoadedRows, m_bStartIsDown, m_Codes, m_Cursor, OptionRowHandler::m_Def, m_pn, m_Row, m_Rows, m_setDirectRows, m_setTopMenus, Actor::m_sName, OptionRowDefinition::m_vsChoices, OptionRowHandlerUtil::Make(), ParseCommands(), Actor::PlayCommand(), LuaHelpers::ReportScriptErrorFmt(), Actor::SetName(), split(), THEME, TOP_MENU, and TOP_MENUS.
Referenced by ScreenSelectMusic::Init().
MoveItem()
void OptionsList::MoveItem (const RString & sRowName, int iMove) private
Open()
void OptionsList::Open ()
Show the top-level menu.
References ASSERT, MessageManager::Broadcast(), ActorFrame::FinishTweening(), m_asMenuStack, m_iCurrentRow, m_pn, m_Row, MESSAGEMAN, Actor::PlayCommand(), Push(), OptionListRow::SetFromHandler(), Message::SetParam(), and TOP_MENU.
Referenced by ScreenSelectMusic::Input(), and ScreenSelectMusic::OpenOptionsList().
Pop()
void OptionsList::Pop () private
References Close(), FindScreenInHandler(), GetCurrentHandler(), m_asMenuStack, m_iMenuStackSelection, SetDefaultCurrentRow(), SwitchToCurrentRow(), and TweenOnCurrentRow().
Referenced by Start().
PositionCursor()
void OptionsList::PositionCursor () private
References m_Cursor, m_iCurrentRow, m_iMenuStackSelection, m_Row, and OptionListRow::PositionCursor().
Referenced by Input(), Start(), and SwitchToCurrentRow().
Push()
void OptionsList::Push (const RString & sDest) private
References m_asMenuStack, SetDefaultCurrentRow(), and SwitchToCurrentRow().
Referenced by Open(), and Start().
Reset()
void OptionsList::Reset ()
References FOREACHM, ImportRow(), and m_Rows.
Referenced by ScreenSelectMusic::BeginScreen().
SelectionsChanged()
void OptionsList::SelectionsChanged (const RString & sRowName) private
References ExportRow(), IsOpened(), OptionRowDefinition::m_bOneChoiceForAllPlayers, m_bSelections, OptionRowHandler::m_Def, m_pLinked, m_Rows, and UpdateMenuFromSelections().
Referenced by SelectItem(), and Start().
SelectItem()
void OptionsList::SelectItem (const RString & sRowName, int iMenuItem) private
References m_bSelections, OptionRowHandler::m_Def, m_Rows, OptionRowDefinition::m_selectType, SELECT_MULTIPLE, SelectionsChanged(), and UpdateMenuFromSelections().
Referenced by Input(), and Start().
SetDefaultCurrentRow()
void OptionsList::SetDefaultCurrentRow () private
References GetOneSelection(), m_asMenuStack, OptionRowHandler::m_Def, m_iMenuStackSelection, m_Rows, OptionRowDefinition::m_selectType, and SELECT_ONE.
Referenced by Pop(), Push(), and SwitchMenu().
Start()
bool OptionsList::Start ()
References MessageManager::Broadcast(), FOREACHM, GAMESTATE, GetCurrentHandler(), GetCurrentRow(), OptionRowHandler::GetIconTextAndGameCommand(), OptionRowHandler::GetScreen(), ImportRow(), m_asMenuStack, m_bSelections, m_iMenuStackSelection, m_pn, GameState::m_pPlayerState, m_Rows, GameCommand::m_sName, MESSAGEMAN, ModsLevel_Preferred, Pop(), PositionCursor(), Push(), PlayerState::ResetToDefaultPlayerOptions(), GameState::ResetToDefaultSongOptions(), SelectionsChanged(), SelectItem(), Message::SetParam(), TweenOnCurrentRow(), and UpdateMenuFromSelections().
Referenced by Input().
SwitchMenu()
void OptionsList::SwitchMenu (int iDir) private
References FindScreenInHandler(), OptionRowHandler::GetScreen(), m_asMenuStack, OptionRowHandler::m_Def, m_Rows, OptionRowDefinition::m_vsChoices, SetDefaultCurrentRow(), SwitchToCurrentRow(), and TweenOnCurrentRow().
Referenced by Input().
SwitchToCurrentRow()
void OptionsList::SwitchToCurrentRow () private
References MessageManager::Broadcast(), GetCurrentHandler(), m_asMenuStack, m_bSelections, m_iCurrentRow, m_pn, m_Row, MESSAGEMAN, PositionCursor(), OptionListRow::SetFromHandler(), Message::SetParam(), and OptionListRow::SetUnderlines().
Referenced by Pop(), Push(), and SwitchMenu().
TweenOnCurrentRow()
void OptionsList::TweenOnCurrentRow (bool bForward) private
References m_iCurrentRow, m_Row, and Actor::PlayCommand().
Referenced by Pop(), Start(), and SwitchMenu().
UpdateMenuFromSelections()
void OptionsList::UpdateMenuFromSelections () private
References GetCurrentHandler(), GetCurrentRow(), m_bSelections, m_iCurrentRow, m_Row, OptionListRow::SetTextFromHandler(), and OptionListRow::SetUnderlines().
Referenced by SelectionsChanged(), SelectItem(), and Start().
Friends And Related Function Documentation
OptionListRow
friend class OptionListRow friend
Member Data Documentation
m_asLoadedRows
vector<RString> OptionsList::m_asLoadedRows private
Referenced by Load().
m_asMenuStack
vector<RString> OptionsList::m_asMenuStack private
Referenced by Close(), GetCurrentRow(), Input(), IsOpened(), Open(), Pop(), Push(), SetDefaultCurrentRow(), Start(), SwitchMenu(), and SwitchToCurrentRow().
m_bAcceptStartRelease
bool OptionsList::m_bAcceptStartRelease private
Referenced by Input().
m_bSelections
map<RString, vector<bool> > OptionsList::m_bSelections private
Referenced by ExportRow(), GetOneSelection(), ImportRow(), Input(), SelectionsChanged(), SelectItem(), OptionListRow::SetUnderlines(), Start(), SwitchToCurrentRow(), and UpdateMenuFromSelections().
m_bStartIsDown
bool OptionsList::m_bStartIsDown private
Referenced by Close(), Input(), and Load().
m_Codes
InputQueueCodeSet OptionsList::m_Codes private
Referenced by Input(), and Load().
m_Cursor
AutoActor OptionsList::m_Cursor private
Referenced by Load(), and PositionCursor().
m_iCurrentRow
int OptionsList::m_iCurrentRow private
Referenced by Open(), OptionsList(), PositionCursor(), SwitchToCurrentRow(), TweenOnCurrentRow(), and UpdateMenuFromSelections().
m_iMenuStackSelection
int OptionsList::m_iMenuStackSelection private
Referenced by Input(), Pop(), PositionCursor(), SetDefaultCurrentRow(), and Start().
m_pLinked
OptionsList* OptionsList::m_pLinked private
Referenced by Link(), OptionsList(), and SelectionsChanged().
m_pn
PlayerNumber OptionsList::m_pn private
Referenced by Close(), ExportRow(), ImportRow(), Load(), Open(), Start(), and SwitchToCurrentRow().
m_Row
OptionListRow OptionsList::m_Row[2] private
Referenced by Load(), Open(), PositionCursor(), SwitchToCurrentRow(), TweenOnCurrentRow(), and UpdateMenuFromSelections().
m_Rows
map<RString, OptionRowHandler*> OptionsList::m_Rows private
Referenced by ExportRow(), GetCurrentHandler(), ImportRow(), Input(), Load(), Reset(), SelectionsChanged(), SelectItem(), SetDefaultCurrentRow(), OptionListRow::SetTextFromHandler(), OptionListRow::SetUnderlines(), Start(), SwitchMenu(), and ~OptionsList().
m_setDirectRows
set<RString> OptionsList::m_setDirectRows private
Referenced by Input(), Load(), and OptionListRow::SetTextFromHandler().
m_setTopMenus
set<RString> OptionsList::m_setTopMenus private
Referenced by ExportRow(), ImportRow(), and Load().
TOP_MENU
ThemeMetric<RString> OptionsList::TOP_MENU private
Referenced by Load(), and Open().
The documentation for this class was generated from the following files:
OptionsList.h
OptionsList.cpp