Etterna: FileReading Namespace Reference
FileReading Namespace Reference
Convenience wrappers for reading binary files.
Functions
void ReadBytes (RageFileBasic &f, void *buf, int size, RString &sError)
void SkipBytes (RageFileBasic &f, int size, RString &sError)
void Seek (RageFileBasic &f, int iOffset, RString &sError)
RString ReadString (RageFileBasic &f, int size, RString &sError)
uint8_t read_8 (RageFileBasic &f, RString &sError)
int16_t read_16_le (RageFileBasic &f, RString &sError)
uint16_t read_u16_le (RageFileBasic &f, RString &sError)
int32_t read_32_le (RageFileBasic &f, RString &sError)
uint32_t read_u32_le (RageFileBasic &f, RString &sError)
Detailed Description
Convenience wrappers for reading binary files.
Function Documentation
read_16_le()
int16_t FileReading::read_16_le (RageFileBasic & f, RString & sError)
References ReadBytes(), and Swap16LE().
Referenced by WavReaderADPCM::DecodeADPCMBlock(), GunzipFile(), WavReaderADPCM::Init(), RageSoundReader_WAV::Open(), RageFileDriverZip::ProcessCdirFileHdr(), RageFileDriverZip::ReadEndCentralRecord(), and RageFileDriverZip::ReadLocalFileHeader().
read_32_le()
int32_t FileReading::read_32_le (RageFileBasic & f, RString & sError)
References ReadBytes(), and Swap32LE().
Referenced by GunzipFile(), RageSoundReader_WAV::Open(), RageFileDriverZip::ProcessCdirFileHdr(), and RageFileDriverZip::ReadEndCentralRecord().
read_8()
uint8_t FileReading::read_8 (RageFileBasic & f, RString & sError)
References ReadBytes().
Referenced by WavReaderADPCM::DecodeADPCMBlock(), GunzipFile(), LoadBMP(), and RageFileDriverZip::ProcessCdirFileHdr().
read_u16_le()
uint16_t FileReading::read_u16_le (RageFileBasic & f, RString & sError)
References ReadBytes(), and Swap16LE().
Referenced by GunzipFile(), and LoadBMP().
read_u32_le()
uint32_t FileReading::read_u32_le (RageFileBasic & f, RString & sError)
References ReadBytes(), and Swap32LE().
Referenced by GunzipFile(), and LoadBMP().
ReadBytes()
void FileReading::ReadBytes (RageFileBasic & f, void * buf, int size, RString & sError)
References RageFileBasic::GetError(), and RageFileBasic::Read().
Referenced by GunzipFile(), LoadBMP(), read_16_le(), read_32_le(), read_8(), read_u16_le(), read_u32_le(), and ReadString().
ReadString()
RString FileReading::ReadString (RageFileBasic & f, int size, RString & sError)
References RageFileBasic::GetError(), and RageFileBasic::Read().
Referenced by RageFileDriverZip::ProcessCdirFileHdr(), RageFileDriverZip::ReadEndCentralRecord(), and RageFileDriverZip::ReadLocalFileHeader().
Seek()
void FileReading::Seek (RageFileBasic & f, int iOffset, RString & sError)
References RageFileBasic::GetError(), and RageFileBasic::Seek().
Referenced by GunzipFile(), and SkipBytes().
SkipBytes()
void FileReading::SkipBytes (RageFileBasic & f, int size, RString & sError)
References Seek(), and RageFileBasic::Tell().
Referenced by GunzipFile(), RageFileDriverZip::ProcessCdirFileHdr(), and RageFileDriverZip::ReadLocalFileHeader().