Etterna: RoomInfoDisplay.cpp File Reference
RoomInfoDisplay.cpp File Reference
#include "global.h"
#include "RoomInfoDisplay.h"
#include "ActorUtil.h"
#include "LocalizedString.h"
#include "NetworkSyncManager.h"
Functions
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage (SM_RoomInfoDeploy)
Variables
static LocalizedString LAST_ROUND_INFO ("RoomInfoDisplay", "Last Round Info:")
static LocalizedString ROOM_NAME ("RoomInfoDisplay", "Room Name:")
static LocalizedString ROOM_DESC ("RoomInfoDisplay", "Room Description:")
static LocalizedString SONG_TITLE ("RoomInfoDisplay", "Song Title:")
static LocalizedString SONG_SUB_TITLE ("RoomInfoDisplay", "Song Subtitle:")
static LocalizedString SONG_ARTIST ("RoomInfoDisplay", "Song Artist:")
static LocalizedString PLAYERS ("RoomInfoDisplay", "Players")
Function Documentation
AutoScreenMessage() [1/2]
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage() [2/2]
AutoScreenMessage (SM_RoomInfoDeploy)
Variable Documentation
LAST_ROUND_INFO
LocalizedString LAST_ROUND_INFO("RoomInfoDisplay", "Last Round Info:") static
Referenced by RoomInfoDisplay::Load().
PLAYERS
LocalizedString PLAYERS("RoomInfoDisplay", "Players") static
Referenced by RoomInfoDisplay::SetRoomInfo().
ROOM_DESC
LocalizedString ROOM_DESC("RoomInfoDisplay", "Room Description:") static
Referenced by RoomInfoDisplay::SetRoom().
ROOM_NAME
LocalizedString ROOM_NAME("RoomInfoDisplay", "Room Name:") static
Referenced by RoomInfoDisplay::SetRoom().
SONG_ARTIST
LocalizedString SONG_ARTIST("RoomInfoDisplay", "Song Artist:") static
Referenced by RoomInfoDisplay::SetRoomInfo().
SONG_SUB_TITLE
LocalizedString SONG_SUB_TITLE("RoomInfoDisplay", "Song Subtitle:") static
Referenced by RoomInfoDisplay::SetRoomInfo().
SONG_TITLE
LocalizedString SONG_TITLE("RoomInfoDisplay", "Song Title:") static
Referenced by RoomInfoDisplay::SetRoomInfo().