Etterna: SSCLoader Struct Reference
SSCLoader Struct Reference
The SSCLoader handles all of the parsing needed for .ssc files.
#include <NotesLoaderSSC.h>
Public Member Functions
SSCLoader ()
bool LoadFromSimfile (const RString &sPath, Song &out, bool bFromCache=false) override
Attempt to load the specified ssc file.
bool LoadEditFromFile (const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL) override
Attempt to load an edit from the hard drive.
bool LoadEditFromMsd (const MsdFile &msd, const RString &sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song *givenSong=NULL) override
Attempt to parse the edit file in question.
bool LoadNoteDataFromSimfile (const RString &cachePath, Steps &out) override
Retrieve the specific NoteData from the file.
void ProcessCombos (TimingData &, const RString &line, const int=-1) override
Public Member Functions inherited from SMLoader
SMLoader ()
SMLoader (RString ext)
virtual ~SMLoader ()=default
virtual bool LoadFromDir (const RString &sPath, Song &out, bool load_autosave=false)
Attempt to load a song from a specified path.
virtual void GetApplicableFiles (const RString &sPath, vector< RString > &out, bool load_autosave=false)
Retrieve the list of .sm files.
virtual bool LoadEditFromBuffer (const RString &sBuffer, const RString &sEditFilePath, ProfileSlot slot, Song *givenSong=NULL)
virtual bool LoadFromBGChangesString (BackgroundChange &change, const RString &sBGChangeExpression)
void ParseBPMs (vector< pair< float, float >> &out, const RString &line, const int rowsPerBeat=-1)
Parse BPM Changes data from a string.
void ProcessBPMs (TimingData &out, const vector< pair< float, float >> &vBPMChanges)
Process the BPM Segments from the string.
void ParseStops (vector< pair< float, float >> &out, const RString line, const int rowsPerBeat=-1)
Parse Stops data from a string.
void ProcessStops (TimingData &out, const vector< pair< float, float >> &vStops)
Process the Stop Segments from the data.
void ProcessBPMsAndStops (TimingData &out, vector< pair< float, float >> &vBPMs, vector< pair< float, float >> &vStops)
Process BPM and stop segments from the data.
void ProcessDelays (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Delay Segments from the string.
void ProcessTimeSignatures (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Time Signature Segments from the string.
void ProcessTickcounts (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Tickcount Segments from the string.
virtual void ProcessSpeeds (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Speed Segments from the string.
virtual void ProcessFakes (TimingData &out, const RString &line, const int rowsPerBeat=-1)
Process the Fake Segments from the string.
virtual void ProcessBGChanges (Song &out, const RString &sValueName, const RString &sPath, const RString &sParam)
void ProcessInstrumentTracks (Song &out, const RString &sParam)
virtual void SetSongTitle (const RString &title)
Set the song title.
virtual RString GetSongTitle () const
Get the song title.
Static Public Member Functions
static void ProcessBPMs (TimingData &, const RString &sParam, const string &songName)
static void ProcessStops (TimingData &, const RString &sParam, const string &songName)
static void ProcessWarps (TimingData &, const RString &sParam, const float, const string &songName)
static void ProcessLabels (TimingData &out, const RString &sParam, const string &songName)
static void ProcessCombos (TimingData &, const RString &line, const string &songName, const int=-1)
static void ProcessScrolls (TimingData &, const RString sParam, const string &songName)
Static Public Member Functions inherited from SMLoader
static void TidyUpData (Song &song, bool bFromCache)
Perform some cleanup on the loaded song.
static void ProcessDelays (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTimeSignatures (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessTickcounts (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessSpeeds (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static void ProcessFakes (TimingData &out, const RString &line, const string &songname, const int rowsPerBeat=-1)
static float RowToBeat (const RString &line, const int rowsPerBeat)
Convert a row value to the proper beat value.
Additional Inherited Members
Protected Member Functions inherited from SMLoader
virtual void LoadFromTokens (RString sStepsType, RString sDescription, RString sDifficulty, RString sMeter, RString sRadarValues, RString sNoteData, Steps &out)
Process the different tokens we have available to get NoteData.
RString GetFileExtension () const
Retrieve the file extension associated with this loader.
Detailed Description
The SSCLoader handles all of the parsing needed for .ssc files.
Constructor & Destructor Documentation
SSCLoader()
SSCLoader::SSCLoader () inline
Member Function Documentation
LoadEditFromFile()
bool SSCLoader::LoadEditFromFile (const RString & sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song * givenSong = NULL) override virtual
Attempt to load an edit from the hard drive.
Parameters
sEditFilePath a path on the hard drive to check.
slot the Profile of the user with the edit.
bAddStepsToSong a flag to determine if we add the edit steps to the song file.
Returns
its success or failure.
Reimplemented from SMLoader.
References FILEMAN, MsdFile::GetError(), RageFileManager::GetFileSizeInBytes(), LoadEditFromMsd(), LOG, MAX_EDIT_STEPS_SIZE_BYTES, MsdFile::ReadFile(), RageLog::Trace(), and RageLog::UserLog().
LoadEditFromMsd()
bool SSCLoader::LoadEditFromMsd (const MsdFile & msd, const RString & sEditFilePath, ProfileSlot slot, bool bAddStepsToSong, Song * givenSong = NULL) override virtual
Attempt to parse the edit file in question.
Parameters
msd the edit file itself.
sEditFilePath a const reference to a path on the hard drive to check.
slot the Profile of the user with the edit.
bAddStepsToSong a flag to determine if we add the edit steps to the song file.
Returns
its success or failure.
Reimplemented from SMLoader.
References Song::AddSteps(), Song::CreateSteps(), Difficulty_Edit, SongManager::FindSong(), SSC::StepsTagInfo::for_load_edit, MsdFile::GetNumParams(), Song::GetNumStepsLoadedFromProfile(), MsdFile::GetNumValues(), MsdFile::GetValue(), handler, SSC::StepsTagInfo::has_own_timing, Song::IsEditAlreadyLoaded(), SMLoader::LoadFromTokens(), LOG, Steps::m_Timing, StdString::CStdStr< CT >::MakeUpper(), MAX_EDITS_PER_SONG_PER_PROFILE, SSC::StepsTagInfo::params, StdString::CStdStr< CT >::Replace(), SAFE_DELETE, Steps::SetDifficulty(), Steps::SetFilename(), Steps::SetLoadedFromProfile(), Steps::SetSMNoteData(), SMLoader::SetSongTitle(), SSC::StepsTagInfo::song, SONGMAN, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, ssc_parser_helper_t::steps_tag_handlers, Steps::TidyUpData(), SSC::StepsTagInfo::timing, and RageLog::UserLog().
Referenced by LoadEditFromFile().
LoadFromSimfile()
bool SSCLoader::LoadFromSimfile (const RString & sPath, Song & out, bool bFromCache = false) override virtual
Attempt to load the specified ssc file.
Parameters
sPath a const reference to the path on the hard drive to check.
out a reference to the Song that will retrieve the song information.
bFromCache a check to see if we are getting certain information from the cache file.
Returns
its success or failure.
Reimplemented from SMLoader.
References Song::AddSteps(), Song::CreateSteps(), MsdFile::GetError(), MsdFile::GetNumValues(), GETTING_SONG_INFO, GETTING_STEP_INFO, MsdFile::GetValue(), handler, SSC::StepsTagInfo::has_own_timing, StdString::CStdStr< CT >::Left(), LOG, TimingData::m_fBeat0OffsetInSeconds, Song::m_fVersion, TimingData::m_sFile, Song::m_SongTiming, Song::m_sSongFileName, Steps::m_Timing, StdString::CStdStr< CT >::MakeUpper(), SSC::StepsTagInfo::params, SSC::SongTagInfo::params, MsdFile::ReadFile(), SetBGChanges(), Steps::SetFilename(), Steps::SetSMNoteData(), ssc_parser_helper_t::song_tag_handlers, STEPFILE_VERSION_NUMBER, SSC::StepsTagInfo::steps, ssc_parser_helper_t::steps_tag_handlers, SMLoader::TidyUpData(), Steps::TidyUpData(), SSC::StepsTagInfo::timing, and RageLog::UserLog().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), and StartMusic().
LoadNoteDataFromSimfile()
bool SSCLoader::LoadNoteDataFromSimfile (const RString & cachePath, Steps & out) override virtual
Retrieve the specific NoteData from the file.
Parameters
cachePath the path to the cache file.
out the Steps to receive just the particular notedata.
Returns
true if successful, false otherwise.
Reimplemented from SMLoader.
References Difficulty_Edit, GAMEMAN, Steps::GetChartName(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetDifficulty(), MsdFile::GetError(), GetExtension(), Steps::GetMeter(), MsdFile::GetNumValues(), MsdFile::GetValue(), handler, SSC::LNDID_chartname, SSC::LNDID_credit, SSC::LNDID_description, SSC::LNDID_difficulty, SSC::LNDID_meter, SSC::LNDID_notedata, SSC::LNDID_notes, SSC::LNDID_notes2, SSC::LNDID_stepstype, SSC::LNDID_version, ssc_parser_helper_t::load_note_data_handlers, LOG, Steps::m_StepsType, StdString::CStdStr< CT >::MakeLower(), StdString::CStdStr< CT >::MakeUpper(), MsdFile::ReadFile(), Steps::SetSMNoteData(), StringToDifficulty(), StringToFloat(), StringToInt(), GameManager::StringToStepsType(), Steps::TidyUpData(), RageLog::Trace(), Trim(), RageLog::UserLog(), and VERSION_CHART_NAME_TAG.
Referenced by Steps::GetNoteDataFromSimfile().
ProcessBPMs()
void SSCLoader::ProcessBPMs (TimingData & out, const RString & sParam, const string & songName) static
References TimingData::AddSegment(), BeatToNoteRow(), LOG, split(), StringToFloat(), and RageLog::UserLog().
Referenced by SetSongBPMs(), SetStepsBPMs(), and SongCacheIndex::SongFromStatement().
ProcessCombos() [1/2]
void SSCLoader::ProcessCombos (TimingData & out, const RString & line, const string & songName, const int rowsPerBeat = -1) static
References TimingData::AddSegment(), BeatToNoteRow(), f, LOG, split(), StringToFloat(), StringToInt(), and RageLog::UserLog().
Referenced by ProcessCombos(), SetSongCombos(), SetStepsCombos(), and SongCacheIndex::SongFromStatement().
ProcessCombos() [2/2]
void SSCLoader::ProcessCombos (TimingData & out, const RString & line, const int rowsPerBeat = -1) override virtual
Reimplemented from SMLoader.
References SMLoader::GetSongTitle(), and ProcessCombos().
ProcessLabels()
void SSCLoader::ProcessLabels (TimingData & out, const RString & sParam, const string & songName) static
References TimingData::AddSegment(), BeatToNoteRow(), f, LOG, split(), StringToFloat(), TrimRight(), and RageLog::UserLog().
Referenced by SetSongLabels(), SetStepsLabels(), and SongCacheIndex::SongFromStatement().
ProcessScrolls()
void SSCLoader::ProcessScrolls (TimingData & out, const RString sParam, const string & songName) static
References TimingData::AddSegment(), BeatToNoteRow(), FOREACH_CONST, LOG, split(), StringToFloat(), and RageLog::UserLog().
Referenced by SetSongScrolls(), SetStepsScrolls(), and SongCacheIndex::SongFromStatement().
ProcessStops()
void SSCLoader::ProcessStops (TimingData & out, const RString & sParam, const string & songName) static
References TimingData::AddSegment(), BeatToNoteRow(), LOG, split(), StringToFloat(), and RageLog::UserLog().
Referenced by SetSongStops(), SetStepsStops(), and SongCacheIndex::SongFromStatement().
ProcessWarps()
void SSCLoader::ProcessWarps (TimingData & out, const RString & sParam, const float fVersion, const string & songName) static
References TimingData::AddSegment(), BeatToNoteRow(), LOG, split(), StringToFloat(), and RageLog::UserLog().
Referenced by SetSongWarps(), SetStepsWarps(), and SongCacheIndex::SongFromStatement().
The documentation for this struct was generated from the following files:
NotesLoaderSSC.h
NotesLoaderSSC.cpp