Etterna: Song Class Reference
Song Class Reference
Holds all music metadata and steps for one song.
#include <Song.h>
Public Types
enum SelectionDisplay { SHOW_ALWAYS, SHOW_NEVER }
When should this song be displayed in the music wheel?
typedef vector< BackgroundChange > VBackgroundChange
Public Member Functions
void SetSongDir (const RString &sDir)
RString GetSongDir ()
Song ()
~Song ()
void Reset ()
void DetachSteps ()
void FinalizeLoading ()
Load a song from the chosen directory.
bool LoadFromSongDir (RString sDir, bool load_autosave=false)
bool ReloadFromSongDir (const RString &sDir)
bool ReloadFromSongDir ()
RString GetFileHash ()
bool HasAutosaveFile ()
bool LoadAutosaveFile ()
void TidyUpData (bool fromCache=false, bool duringCache=false)
Call this after loading a song to clean up invalid data.
void ReCalculateRadarValuesAndLastSecond (bool fromCache=false, bool duringCache=false)
Get the new radar values, and determine the last second at the same time. This is called by TidyUpData, after saving the Song.
void TranslateTitles ()
Translate any titles that aren't in english. This is called by TidyUpData.
bool SaveToSSCFile (const RString &sPath, bool bSavingCache, bool autosave=false)
Save to the new SSC file format.
bool SaveToETTFile (const RString &sPath, bool bSavingCache, bool autosave=false)
void Save (bool autosave=false)
Save to the SSC and SM files no matter what.
bool SaveToJsonFile (const RString &sPath)
Save the current Song to a JSON file.
bool SaveToCacheFile ()
Save the current Song to a cache file using the preferred format.
bool SaveToSMFile ()
Save the current Song to a SM file.
bool SaveToDWIFile ()
Save the current Song to a DWI file if possible.
void RemoveAutosave ()
bool WasLoadedFromAutosave () const
const RString & GetSongFilePath () const
RString GetCacheFilePath () const
const RString & GetSongDir () const
RString GetDisplayMainTitle () const
RString GetDisplaySubTitle () const
RString GetDisplayArtist () const
RString GetMainTitle () const
RString GetTranslitMainTitle () const
Retrieve the transliterated title, or the main title if there is no translit.
vector< Steps * > GetStepsToSave (bool bSavingCache=true, string path="")
RString GetTranslitSubTitle () const
Retrieve the transliterated subtitle, or the main subtitle if there is no translit.
RString GetTranslitArtist () const
Retrieve the transliterated artist, or the main artist if there is no translit.
RString GetDisplayFullTitle () const
RString GetTranslitFullTitle () const
RString GetMusicPath () const
RString GetInstrumentTrackPath (InstrumentTrack it) const
RString GetBannerPath () const
RString GetJacketPath () const
RString GetCDImagePath () const
RString GetDiscPath () const
RString GetLyricsPath () const
RString GetBackgroundPath () const
RString GetCDTitlePath () const
RString GetPreviewVidPath () const
RString GetPreviewMusicPath () const
float GetPreviewStartSeconds () const
std::string GetCacheFile (std::string sPath)
float GetHighestOfSkillsetAllSteps (int x, float rate) const
bool IsSkillsetHighestOfAnySteps (Skillset ss, float rate)
bool HasChartByHash (const string &hash)
bool HasMusic () const
bool HasInstrumentTrack (InstrumentTrack it) const
bool HasBanner () const
Does this song have a banner?
bool HasBackground () const
Does this song have a background image?
bool HasJacket () const
bool HasCDImage () const
bool HasDisc () const
bool HasCDTitle () const
bool HasBGChanges () const
bool HasLyrics () const
bool HasAttacks () const
bool HasPreviewVid () const
bool Matches (const RString &sGroup, const RString &sSong) const
float GetFirstBeat () const
float GetFirstSecond () const
float GetLastBeat () const
float GetLastSecond () const
float GetSpecifiedLastBeat () const
float GetSpecifiedLastSecond () const
void SetFirstSecond (float f)
void SetLastSecond (float f)
void SetSpecifiedLastSecond (float f)
const vector< BackgroundChange > & GetBackgroundChanges (BackgroundLayer bl) const
vector< BackgroundChange > & GetBackgroundChanges (BackgroundLayer bl)
const vector< BackgroundChange > & GetForegroundChanges () const
vector< BackgroundChange > & GetForegroundChanges ()
vector< RString > GetBGChanges1ToVectorString () const
vector< RString > GetBGChanges2ToVectorString () const
vector< RString > GetFGChanges1ToVectorString () const
vector< RString > GetInstrumentTracksToVectorString () const
void AddBackgroundChange (BackgroundLayer blLayer, BackgroundChange seg)
void AddForegroundChange (BackgroundChange seg)
void AddLyricSegment (LyricSegment seg)
void GetDisplayBpms (DisplayBpms &AddTo) const
const BackgroundChange & GetBackgroundAtBeat (BackgroundLayer iLayer, float fBeat) const
Steps * CreateSteps ()
void InitSteps (Steps *pSteps)
RString GetOrTryAtLeastToGetSimfileAuthor ()
bool HasSignificantBpmChangesOrStops () const
float GetStepsSeconds () const
bool IsLong () const
bool IsMarathon () const
bool SongCompleteForStyle (const Style *st) const
bool HasStepsType (StepsType st) const
bool HasStepsTypeAndDifficulty (StepsType st, Difficulty dc) const
const vector< Steps * > & GetAllSteps () const
const vector< Steps * > & GetStepsByStepsType (StepsType st) const
bool IsEasy (StepsType st) const
bool IsTutorial () const
bool HasEdits (StepsType st) const
bool IsFavorited ()
void SetFavorited (bool b)
bool HasGoal ()
void SetHasGoal (bool b)
bool IsPermaMirror ()
void SetPermaMirror (bool b)
void SetEnabled (bool b)
bool GetEnabled () const
bool ShowInDemonstrationAndRanking () const
void AddSteps (Steps *pSteps)
Add the chosen Steps to the Song. We are responsible for deleting the memory pointed to by pSteps!
void DeleteSteps (const Steps *pSteps, bool bReAutoGen=true)
void FreeAllLoadedFromProfile (ProfileSlot slot=ProfileSlot_Invalid, const set< Steps *> *setInUse=NULL)
bool WasLoadedFromProfile () const
void GetStepsLoadedFromProfile (ProfileSlot slot, vector< Steps *> &vpStepsOut) const
int GetNumStepsLoadedFromProfile (ProfileSlot slot) const
bool IsEditAlreadyLoaded (Steps *pSteps) const
bool IsStepsUsingDifferentTiming (Steps *pSteps) const
bool AnyChartUsesSplitTiming () const
void PushSelf (lua_State *L)
Static Public Member Functions
static RString GetSongAssetPath (RString sPath, const RString &sSongPath)
Public Attributes
enum Song::SelectionDisplay m_SelectionDisplay
RString m_sFileHash
RString m_sSongFileName
Filename associated with this file. This will always have a .SSC extension. If we loaded a .SSC, this will point to it, but if we loaded any other type, this will point to a generated .SSC filename.
RString m_sGroupName
The group this Song is in.
ProfileSlot m_LoadedFromProfile
the Profile this came from. This is ProfileSlot_Invalid if it wasn't loaded from a profile.
bool m_bIsSymLink
Is the song file itself a symlink to another file?
bool m_bEnabled
RString m_sMainTitle
The title of the Song.
RString m_sSubTitle
The subtitle of the Song, if it exists.
RString m_sArtist
The artist of the Song, if it exists.
RString m_sMainTitleTranslit
The transliterated title of the Song, if it exists.
RString m_sSubTitleTranslit
The transliterated subtitle of the Song, if it exists.
RString m_sArtistTranslit
The transliterated artist of the Song, if it exists.
float m_fVersion
The version of the song/file.
RString m_sGenre
The genre of the song/file.
RString m_sCredit
The person who worked with the song file who should be credited. This is read and saved, but never actually used.
RString m_sOrigin
RString m_sMusicFile
RString m_PreviewFile
RString m_sInstrumentTrackFile [NUM_InstrumentTrack]
float m_fMusicLengthSeconds
The length of the music file.
float m_fMusicSampleStartSeconds
float m_fMusicSampleLengthSeconds
DisplayBPM m_DisplayBPMType
float m_fSpecifiedBPMMin
float m_fSpecifiedBPMMax
RString m_sBannerFile
RString m_sJacketFile
RString m_sCDFile
RString m_sDiscFile
RString m_sLyricsFile
The location of the lyrics file, if it exists.
RString m_sBackgroundFile
RString m_sCDTitleFile
RString m_sPreviewVidFile
vector< RString > ImageDir
bool m_bHasMusic
bool m_bHasBanner
bool m_bHasBackground
TimingData m_SongTiming
The Song's TimingData.
vector< LyricSegment > m_LyricSegments
The list of LyricSegments. This must be sorted before gameplay.
vector< RString > m_vsKeysoundFile
An array of keysound file names (e.g. "beep.wav"). The index in this array corresponds to the index in TapNote. If you change the index in here, you must change all NoteData too. Any note that doesn't have a value in the range of this array means "this note doesn't have a keysound".
CachedObject< Song > m_CachedObject
vector< Steps * > m_vpSteps
vector< Steps * > m_UnknownStyleSteps
Private Member Functions
vector< RString > GetChangesToVectorString (const vector< BackgroundChange > &changes) const
Private Attributes
RString m_sSongDir
float firstSecond
The first second that a note is hit.
float lastSecond
The last second that a note is hit.
float specifiedLastSecond
The last second of the song for playing purposes.
AutoPtrCopyOnWrite< VBackgroundChange > m_BackgroundChanges [NUM_BackgroundLayer]
The background changes (sorted by layer) that are for this Song. This uses an AutoPtr instead of a raw pointer so that the auto gen'd copy constructor works correctly. This must be sorted before gameplay.
AutoPtrCopyOnWrite< VBackgroundChange > m_ForegroundChanges
The foreground changes that are for this Song. This uses an AutoPtr instead of a raw pointer so that the auto gen'd copy constructor works correctly. This must be sorted before gameplay.
bool isfavorited = false
bool permamirror = false
bool hasgoal = false
bool m_loaded_from_autosave
vector< Steps * > m_vpStepsByType [NUM_StepsType]
the Steps that belong to this Song.
Detailed Description
Holds all music metadata and steps for one song.
Member Typedef Documentation
VBackgroundChange
typedef vector<BackgroundChange> Song::VBackgroundChange
Member Enumeration Documentation
SelectionDisplay
enum Song::SelectionDisplay
When should this song be displayed in the music wheel?
Enumerator
SHOW_ALWAYS
always show on the wheel.
SHOW_NEVER
never show on the wheel (unless song hiding is turned off).
Constructor & Destructor Documentation
Song()
Song::Song ()
References DEFAULT_MUSIC_SAMPLE_LENGTH, DISPLAY_BPM_ACTUAL, firstSecond, FOREACH_BackgroundLayer, ImageDir, CommonMetrics::IMAGES_TO_CACHE, lastSecond, m_BackgroundChanges, m_bEnabled, m_bHasBackground, m_bHasBanner, m_bHasMusic, m_bIsSymLink, m_DisplayBPMType, m_fMusicLengthSeconds, m_fMusicSampleLengthSeconds, m_fMusicSampleStartSeconds, m_ForegroundChanges, m_fSpecifiedBPMMax, m_fSpecifiedBPMMin, m_fVersion, m_loaded_from_autosave, m_LoadedFromProfile, m_SelectionDisplay, ProfileSlot_Invalid, SHOW_ALWAYS, specifiedLastSecond, split(), and STEPFILE_VERSION_NUMBER.
~Song()
Song::~Song ()
References FOREACH, m_UnknownStyleSteps, m_vpSteps, and SAFE_DELETE.
Member Function Documentation
AddBackgroundChange()
void Song::AddBackgroundChange (BackgroundLayer blLayer, BackgroundChange seg)
References BackgroundUtil::AddBackgroundChange(), ASSERT, FOREACH, GetBackgroundChanges(), BackgroundChange::m_fStartBeat, and NUM_BackgroundLayer.
Referenced by BMSSongLoader::AddToSong(), SMLoader::ProcessBGChanges(), and TidyUpData().
AddForegroundChange()
void Song::AddForegroundChange (BackgroundChange seg)
References BackgroundUtil::AddBackgroundChange(), and GetForegroundChanges().
Referenced by SMALoader::LoadFromSimfile(), SetFGChanges(), SMSetFGChanges(), and SongCacheIndex::SongFromStatement().
AddLyricSegment()
void Song::AddLyricSegment (LyricSegment seg)
References m_LyricSegments.
Referenced by LyricsLoader::LoadFromLRCFile().
AddSteps()
void Song::AddSteps (Steps * pSteps)
Add the chosen Steps to the Song. We are responsible for deleting the memory pointed to by pSteps!
Parameters
pSteps the new steps.
References ASSERT_M, Steps::m_StepsType, m_UnknownStyleSteps, m_vpSteps, m_vpStepsByType, NUM_StepsType, ssprintf(), and StepsType_Invalid.
Referenced by Deserialize(), BMSSongLoader::Load(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), KSFLoader::LoadFromDir(), DWILoader::LoadFromDir(), OsuLoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), ReloadFromSongDir(), and SongCacheIndex::SongFromStatement().
AnyChartUsesSplitTiming()
bool Song::AnyChartUsesSplitTiming () const
References FOREACH_CONST, and m_vpSteps.
CreateSteps()
Steps * Song::CreateSteps ()
References InitSteps().
Referenced by BMSSongLoader::Load(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), KSFLoader::LoadFromDir(), DWILoader::LoadFromDir(), OsuLoader::LoadFromDir(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), KSFLoader::LoadNoteDataFromSimfile(), and SongCacheIndex::SongFromStatement().
DeleteSteps()
void Song::DeleteSteps (const Steps * pSteps, bool bReAutoGen = true)
References Steps::m_StepsType, m_vpSteps, and m_vpStepsByType.
Referenced by SongUtil::DeleteDuplicateSteps(), SongManager::DeleteSteps(), and FreeAllLoadedFromProfile().
DetachSteps()
void Song::DetachSteps ()
References FOREACH_ENUM, m_UnknownStyleSteps, m_vpSteps, and m_vpStepsByType.
FinalizeLoading()
void Song::FinalizeLoading ()
Load a song from the chosen directory.
This assumes that there is no song present right now.
Parameters
sDir the song directory from which to load.
References ASSERT, FOREACH, GetCacheFile(), IMAGECACHE, ImageDir, IMGCACHE_LOW_RES_PRELOAD, ImageCache::LoadImage(), PrefsManager::m_ImageCache, m_sGroupName, m_sSongDir, m_vpSteps, PREFSMAN, and split().
Referenced by LoadFromSongDir().
FreeAllLoadedFromProfile()
void Song::FreeAllLoadedFromProfile (ProfileSlot slot = ProfileSlot_Invalid, const set< Steps *> * setInUse = NULL)
References DeleteSteps(), Steps::GetLoadedFromProfileSlot(), m_vpSteps, ProfileSlot_Invalid, and Steps::WasLoadedFromProfile().
GetAllSteps()
const vector<Steps*>& Song::GetAllSteps () const inline
References m_vpSteps.
Referenced by SongManager::AddKeyedPointers(), AdjustSync::AutosyncOffset(), SongManager::Cleanup(), DoInstalls(), StepsUtil::GetAllMatching(), StepsUtil::GetAllMatchingEndless(), LunaSong::GetAllSteps(), Profile::GetBestGrade(), SongUtil::GetClosestNotes(), GetHighestOfSkillsetAllSteps(), SongManager::GetSongColor(), Profile::GetSongsPossible(), SongUtil::GetSteps(), SongUtil::GetStepsByDifficulty(), SongUtil::GetStepsByMeter(), HasChartByHash(), StepsUtil::HasMatching(), Profile::HasPassedAnyStepsInSong(), ScreenEvaluation::Init(), ScreenSyncOverlay::Input(), ScreenSelectMusic::Input(), SongUtil::IsChartNameUnique(), SongUtil::IsEditDescriptionUnique(), IsSkillsetHighestOfAnySteps(), SongUtil::IsSongPlayable(), OsuLoader::LoadChartData(), SongManager::ReconcileChartKeysForReloadedSong(), AdjustSync::ResetOriginalSyncData(), AdjustSync::RevertSyncChanges(), StepsUtil::SortStepsPointerArrayByNumPlays(), NotesWriterDWI::Write(), and NotesWriterJson::WriteSong().
GetBackgroundAtBeat()
const BackgroundChange & Song::GetBackgroundAtBeat (BackgroundLayer iLayer, float fBeat) const
References GetBackgroundChanges().
GetBackgroundChanges() [1/2]
const vector< BackgroundChange > & Song::GetBackgroundChanges (BackgroundLayer bl) const
References m_BackgroundChanges.
Referenced by AddBackgroundChange(), BackgroundUtil::BakeAllBackgroundChanges(), SongCacheIndex::CacheSong(), Deserialize(), NoteField::DrawPrimitives(), GetBackgroundAtBeat(), LunaSong::GetBGChanges(), GetBGChanges1ToVectorString(), GetBGChanges2ToVectorString(), HasBGChanges(), BackgroundImpl::LoadFromSong(), SMLoader::TidyUpData(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
GetBackgroundChanges() [2/2]
vector< BackgroundChange > & Song::GetBackgroundChanges (BackgroundLayer bl)
References AutoPtrCopyOnWrite< T >::Get(), and m_BackgroundChanges.
GetBackgroundPath()
RString Song::GetBackgroundPath () const
References GetSongAssetPath(), m_sBackgroundFile, and m_sSongDir.
Referenced by BackgroundImpl::Layer::CreateBackground(), DoInstalls(), LunaSong::GetBackgroundPath(), GetCacheFile(), GameState::GetRankingFeats(), HasBackground(), BGAnimationLayer::LoadFromAniLayerFile(), and SMLoader::TidyUpData().
GetBannerPath()
RString Song::GetBannerPath () const
References GetSongAssetPath(), m_sBannerFile, and m_sSongDir.
Referenced by ScreenSelectMusic::AfterMusicChange(), DoInstalls(), LunaSong::GetBannerPath(), GetCacheFile(), HasBanner(), FadingBanner::LoadFromSong(), and Banner::LoadFromSong().
GetBGChanges1ToVectorString()
vector< RString > Song::GetBGChanges1ToVectorString () const
References BACKGROUND_LAYER_1, GetBackgroundChanges(), and GetChangesToVectorString().
GetBGChanges2ToVectorString()
vector< RString > Song::GetBGChanges2ToVectorString () const
References BACKGROUND_LAYER_2, GetBackgroundChanges(), and GetChangesToVectorString().
GetCacheFile()
std::string Song::GetCacheFile (std::string sPath)
References FILEMAN, FT_Bitmap, GetBackgroundPath(), GetBannerPath(), GetCDImagePath(), GetCDTitlePath(), RageFileManager::GetDirListing(), GetDiscPath(), GetExtension(), GetJacketPath(), GetSongAssetPath(), ActorUtil::GetTypeExtensionList(), and m_sSongDir.
Referenced by FinalizeLoading(), and TidyUpData().
GetCacheFilePath()
RString Song::GetCacheFilePath () const
References SongCacheIndex::GetCacheFilePath(), and m_sSongDir.
Referenced by ReloadFromSongDir().
GetCDImagePath()
RString Song::GetCDImagePath () const
References GetSongAssetPath(), m_sCDFile, and m_sSongDir.
Referenced by GetCacheFile(), LunaSong::GetCDImagePath(), and HasCDImage().
GetCDTitlePath()
RString Song::GetCDTitlePath () const
References GetSongAssetPath(), m_sCDTitleFile, and m_sSongDir.
Referenced by ScreenSelectMusic::AfterMusicChange(), DoInstalls(), GetCacheFile(), LunaSong::GetCDTitlePath(), and HasCDTitle().
GetChangesToVectorString()
vector< RString > Song::GetChangesToVectorString (const vector< BackgroundChange > & changes) const private
References FOREACH_CONST.
Referenced by GetBGChanges1ToVectorString(), GetBGChanges2ToVectorString(), and GetFGChanges1ToVectorString().
GetDiscPath()
RString Song::GetDiscPath () const
References GetSongAssetPath(), m_sDiscFile, and m_sSongDir.
Referenced by GetCacheFile(), LunaSong::GetDiscPath(), and HasDisc().
GetDisplayArtist()
RString Song::GetDisplayArtist () const
References GetTranslitArtist(), PrefsManager::m_bShowNativeLanguage, m_sArtist, and PREFSMAN.
Referenced by LunaSong::GetDisplayArtist(), ScreenGameplay::SaveReplay(), and TextBanner::SetFromSong().
GetDisplayBpms()
void Song::GetDisplayBpms (DisplayBpms & AddTo) const
References DisplayBpms::Add(), DISPLAY_BPM_SPECIFIED, GAMESTATE, TimingData::GetActualBPM(), ModsGroup< T >::GetCurrent(), m_DisplayBPMType, SongOptions::m_fMusicRate, m_fSpecifiedBPMMax, m_fSpecifiedBPMMin, GameState::m_SongOptions, and m_SongTiming.
Referenced by CompareSongPointersByBPM(), LunaSong::GetDisplayBpms(), OptionRow::GetRowTitle(), SongUtil::GetSectionNameFromSongAndSort(), Player::Init(), LunaSong::IsDisplayBpmConstant(), LunaSong::IsDisplayBpmSecret(), PlayerOptions::IsEasierForSongAndSteps(), IsEasy(), and BPMDisplay::SetBpmFromSong().
GetDisplayFullTitle()
RString Song::GetDisplayFullTitle () const
References GetDisplayMainTitle(), and GetDisplaySubTitle().
Referenced by LunaSong::GetDisplayFullTitle(), GetPromptText(), and ScreenGameplay::SaveReplay().
GetDisplayMainTitle()
RString Song::GetDisplayMainTitle () const
References GetTranslitMainTitle(), PrefsManager::m_bShowNativeLanguage, m_sMainTitle, and PREFSMAN.
Referenced by Chart::FromKey(), GetDisplayFullTitle(), LunaSong::GetDisplayMainTitle(), Profile::ImportScoresToEtterna(), ScreenSelectMusic::Input(), MusicWheel::ReloadSongList(), TextBanner::SetFromSong(), and LunaProfile::SortByName().
GetDisplaySubTitle()
RString Song::GetDisplaySubTitle () const
References GetTranslitSubTitle(), PrefsManager::m_bShowNativeLanguage, m_sSubTitle, and PREFSMAN.
Referenced by GetDisplayFullTitle(), LunaSong::GetDisplaySubTitle(), and TextBanner::SetFromSong().
GetEnabled()
bool Song::GetEnabled () const inline
References m_bEnabled.
Referenced by LunaSong::IsEnabled(), and SongManager::SaveEnabledSongsToPref().
GetFGChanges1ToVectorString()
vector< RString > Song::GetFGChanges1ToVectorString () const
References GetChangesToVectorString(), and GetForegroundChanges().
GetFileHash()
RString Song::GetFileHash ()
References BinaryToHex(), CRYPTMAN, CryptManager::GetSHA1ForFile(), GetSongFilePath(), IsAFile(), m_sFileHash, and SetExtension().
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), SMOProtocol::SelectUserSong(), ETTProtocol::SelectUserSong(), and SMOProtocol::StartRequest().
GetFirstBeat()
float Song::GetFirstBeat () const
References firstSecond, TimingData::GetBeatFromElapsedTime(), and m_SongTiming.
Referenced by LunaSong::GetFirstBeat(), BackgroundImpl::LoadFromSong(), DancingCharacters::LoadNextSong(), ScreenGameplay::PlayAnnouncer(), DancingCharacters::Update(), ScreenGameplay::Update(), and NotesWriterJson::WriteSong().
GetFirstSecond()
float Song::GetFirstSecond () const
References firstSecond.
Referenced by SongCacheIndex::CacheSong(), LunaSong::GetFirstSecond(), GameState::GetSongPercent(), GetStepsSeconds(), ScreenGameplay::StartPlayingSong(), SongMeterDisplay::Update(), NotesWriterSSC::Write(), and NotesWriterETT::Write().
GetForegroundChanges() [1/2]
const vector< BackgroundChange > & Song::GetForegroundChanges () const
References m_ForegroundChanges.
Referenced by AddForegroundChange(), SongCacheIndex::CacheSong(), Deserialize(), GetFGChanges1ToVectorString(), Foreground::LoadFromSong(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
GetForegroundChanges() [2/2]
vector< BackgroundChange > & Song::GetForegroundChanges ()
References AutoPtrCopyOnWrite< T >::Get(), and m_ForegroundChanges.
GetHighestOfSkillsetAllSteps()
float Song::GetHighestOfSkillsetAllSteps (int x, float rate) const
References CLAMP(), f, FOREACH, and GetAllSteps().
Referenced by CompareSongPointersByMSD().
GetInstrumentTrackPath()
RString Song::GetInstrumentTrackPath (InstrumentTrack it) const
References GetSongAssetPath(), m_sInstrumentTrackFile, and m_sSongDir.
Referenced by HasInstrumentTrack(), and AutoKeysounds::LoadTracks().
GetInstrumentTracksToVectorString()
vector< RString > Song::GetInstrumentTracksToVectorString () const
References FOREACH_ENUM, HasInstrumentTrack(), InstrumentTrackToString(), and m_sInstrumentTrackFile.
Referenced by SongCacheIndex::CacheSong(), and WriteGlobalTags().
GetJacketPath()
RString Song::GetJacketPath () const
References GetSongAssetPath(), m_sJacketFile, and m_sSongDir.
Referenced by GetCacheFile(), LunaSong::GetJacketPath(), and HasJacket().
GetLastBeat()
float Song::GetLastBeat () const
References TimingData::GetBeatFromElapsedTime(), lastSecond, and m_SongTiming.
Referenced by LunaSong::GetLastBeat(), BackgroundImpl::LoadFromSong(), SMLoader::TidyUpData(), ScreenGameplay::Update(), and NotesWriterJson::WriteSong().
GetLastSecond()
float Song::GetLastSecond () const
References lastSecond.
Referenced by SongCacheIndex::CacheSong(), LunaSong::GetLastSecond(), ScreenGameplay::GetMusicEndTiming(), GameState::GetSongPercent(), GetStepsSeconds(), TidyUpData(), LyricDisplay::Update(), SongMeterDisplay::Update(), NotesWriterSSC::Write(), and NotesWriterETT::Write().
GetLyricsPath()
RString Song::GetLyricsPath () const
References GetSongAssetPath(), m_sLyricsFile, and m_sSongDir.
Referenced by LunaSong::GetLyricsPath(), HasLyrics(), and ScreenGameplay::LoadNextSong().
GetMainTitle()
RString Song::GetMainTitle () const
References m_sMainTitle.
Referenced by SongManager::DifferentialReloadDir(), LunaSong::GetMainTitle(), and SongCacheIndex::SongFromStatement().
GetMusicPath()
RString Song::GetMusicPath () const
References GetSongAssetPath(), m_sMusicFile, and m_sSongDir.
Referenced by LunaSong::GetMusicPath(), GetPreviewMusicPath(), HasMusic(), ScreenNetSelectMusic::MusicChanged(), and TidyUpData().
GetNumStepsLoadedFromProfile()
int Song::GetNumStepsLoadedFromProfile (ProfileSlot slot) const
References Steps::GetLoadedFromProfileSlot(), and m_vpSteps.
Referenced by SMLoader::LoadEditFromMsd(), and SSCLoader::LoadEditFromMsd().
GetOrTryAtLeastToGetSimfileAuthor()
RString Song::GetOrTryAtLeastToGetSimfileAuthor ()
References GetSongDir(), and m_sCredit.
Referenced by LunaSong::GetOrTryAtLeastToGetSimfileAuthor().
GetPreviewMusicPath()
RString Song::GetPreviewMusicPath () const
References GetMusicPath(), GetSongAssetPath(), m_PreviewFile, and m_sSongDir.
Referenced by ScreenSelectMusic::AfterMusicChange(), LunaSong::GetPreviewMusicPath(), ScreenNetSelectMusic::MusicChanged(), TidyUpData(), and SongUtil::ValidateCurrentSongPreview().
GetPreviewStartSeconds()
float Song::GetPreviewStartSeconds () const
References m_fMusicSampleStartSeconds, and m_PreviewFile.
Referenced by ScreenSelectMusic::AfterMusicChange(), LunaSong::GetSampleStart(), and ScreenNetSelectMusic::MusicChanged().
GetPreviewVidPath()
RString Song::GetPreviewVidPath () const
References GetSongAssetPath(), m_sPreviewVidFile, and m_sSongDir.
Referenced by LunaSong::GetPreviewVidPath(), and HasPreviewVid().
GetSongAssetPath()
RString Song::GetSongAssetPath (RString sPath, const RString & sSongPath) static
References CollapsePath(), and DoesFileExist().
Referenced by GetBackgroundPath(), GetBannerPath(), GetCacheFile(), GetCDImagePath(), GetCDTitlePath(), GetDiscPath(), GetInstrumentTrackPath(), GetJacketPath(), GetLyricsPath(), Steps::GetMusicPath(), GetMusicPath(), GetPreviewMusicPath(), and GetPreviewVidPath().
GetSongDir() [1/2]
RString Song::GetSongDir () inline
References m_sSongDir.
Referenced by SongManager::AddSongToList(), BMSSong::AllocateKeysound(), SongCacheIndex::CacheSong(), SongUtil::DeleteDuplicateSteps(), SongCacheIndex::DeleteSongFromDB(), DebugLineConvertXML::DoAndLog(), SongID::FromSong(), BMSSong::GetBackground(), NotesWriterSM::GetEditFileContents(), NotesWriterSSC::GetEditFileContents(), SongManager::GetExtraStageInfo(), Steps::GetMusicPath(), GetOrTryAtLeastToGetSimfileAuthor(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), LunaSong::GetSongDir(), BackgroundUtil::GetSongMovies(), Profile::GetSongsActual(), ScreenGameplayLesson::Init(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), AutoKeysounds::LoadAutoplaySoundsInto(), LoadAutosaveFile(), KSFLoader::LoadFromDir(), Foreground::LoadFromSong(), BackgroundImpl::LoadFromSong(), LoadGlobalData(), SongCacheIndex::LoadSongFromCache(), Matches(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), ReloadFromSongDir(), Save(), TidyUpData(), SongManager::WasLoadedFromAdditionalSongs(), and NotesWriterJson::WriteSong().
GetSongDir() [2/2]
const RString& Song::GetSongDir () const inline
References m_sSongDir.
GetSongFilePath()
const RString & Song::GetSongFilePath () const
References ASSERT_M, m_sMainTitle, m_sSongFileName, and ssprintf().
Referenced by CompareSongPointersByBPM(), CompareSongPointersByLength(), CompareSongPointersByMSD(), CompareSongPointersByTitle(), GetFileHash(), LunaSong::GetSongFilePath(), Save(), SaveToDWIFile(), and SaveToSMFile().
GetSpecifiedLastBeat()
float Song::GetSpecifiedLastBeat () const
References TimingData::GetBeatFromElapsedTime(), m_SongTiming, and specifiedLastSecond.
Referenced by WriteGlobalTags().
GetSpecifiedLastSecond()
float Song::GetSpecifiedLastSecond () const
References specifiedLastSecond.
Referenced by SongCacheIndex::CacheSong(), LoadFromKSFFile(), and WriteGlobalTags().
GetStepsByStepsType()
const vector<Steps*>& Song::GetStepsByStepsType (StepsType st) const inline
References m_vpStepsByType.
Referenced by StepsUtil::GetAllMatching(), StepsUtil::GetAllMatchingEndless(), SongUtil::GetClosestNotes(), SongUtil::GetSteps(), SongUtil::GetStepsByDifficulty(), SongUtil::GetStepsByMeter(), LunaSong::GetStepsByStepsType(), StepsUtil::HasMatching(), ScreenNetSelectMusic::MenuDown(), and ScreenNetSelectMusic::MusicChanged().
GetStepsLoadedFromProfile()
void Song::GetStepsLoadedFromProfile (ProfileSlot slot, vector< Steps *> & vpStepsOut) const
References Steps::GetLoadedFromProfileSlot(), and m_vpSteps.
GetStepsSeconds()
float Song::GetStepsSeconds () const
References GetFirstSecond(), and GetLastSecond().
Referenced by LunaSong::GetStepsSeconds(), and ScreenEvaluation::Init().
GetStepsToSave()
vector< Steps * > Song::GetStepsToSave (bool bSavingCache = true, string path = "")
References FOREACH_CONST, m_UnknownStyleSteps, m_vpSteps, Steps::SetFilename(), and Steps::WasLoadedFromProfile().
Referenced by SongCacheIndex::CacheSong(), SaveToETTFile(), SaveToSMFile(), and SaveToSSCFile().
GetTranslitArtist()
RString Song::GetTranslitArtist () const inline
Retrieve the transliterated artist, or the main artist if there is no translit.
Returns
the proper artist.
References m_sArtist, and m_sArtistTranslit.
Referenced by GetDisplayArtist(), SongUtil::GetSectionNameFromSongAndSort(), LunaSong::GetTranslitArtist(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::SelectCurrent(), TextBanner::SetFromSong(), and NotesWriterDWI::Write().
GetTranslitFullTitle()
RString Song::GetTranslitFullTitle () const
References GetTranslitMainTitle(), and GetTranslitSubTitle().
Referenced by ScreenOptionsToggleSongsSubPage::BeginScreen(), NotesWriterSM::GetEditFileName(), NotesWriterSSC::GetEditFileName(), LunaSong::GetTranslitFullTitle(), and NotesWriterDWI::Write().
GetTranslitMainTitle()
RString Song::GetTranslitMainTitle () const inline
Retrieve the transliterated title, or the main title if there is no translit.
Returns
the proper title.
References m_sMainTitle, and m_sMainTitleTranslit.
Referenced by CompareSongPointersByTitle(), GetDisplayMainTitle(), GameState::GetRankingFeats(), SongUtil::GetSectionNameFromSongAndSort(), GetTranslitFullTitle(), LunaSong::GetTranslitMainTitle(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::SelectCurrent(), and TextBanner::SetFromSong().
GetTranslitSubTitle()
RString Song::GetTranslitSubTitle () const inline
Retrieve the transliterated subtitle, or the main subtitle if there is no translit.
Returns
the proper subtitle.
References m_sSubTitle, and m_sSubTitleTranslit.
Referenced by CompareSongPointersByTitle(), GetDisplaySubTitle(), GetTranslitFullTitle(), LunaSong::GetTranslitSubTitle(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::SelectCurrent(), and TextBanner::SetFromSong().
HasAttacks()
bool Song::HasAttacks () const
HasAutosaveFile()
bool Song::HasAutosaveFile ()
References RageFileManager::DoesFileExist(), FILEMAN, m_sSongFileName, and SetExtension().
HasBackground()
bool Song::HasBackground () const
Does this song have a background image?
Returns
true if it does, false otherwise.
References GetBackgroundPath(), IsAFile(), and m_sBackgroundFile.
Referenced by BackgroundImpl::Layer::CreateBackground(), DoInstalls(), GameState::GetRankingFeats(), LunaSong::HasBackground(), BGAnimationLayer::LoadFromAniLayerFile(), and TidyUpData().
HasBanner()
bool Song::HasBanner () const
Does this song have a banner?
Returns
true if it does, false otherwise.
References GetBannerPath(), IsAFile(), and m_sBannerFile.
Referenced by DoInstalls(), LunaSong::HasBanner(), Banner::LoadFromSong(), and TidyUpData().
HasBGChanges()
bool Song::HasBGChanges () const
References FOREACH_BackgroundLayer, and GetBackgroundChanges().
Referenced by LunaSong::HasBGChanges(), BackgroundImpl::LoadFromSong(), and TidyUpData().
HasCDImage()
bool Song::HasCDImage () const
References GetCDImagePath(), IsAFile(), and m_sCDFile.
Referenced by LunaSong::HasCDImage(), and TidyUpData().
HasCDTitle()
bool Song::HasCDTitle () const
References GetCDTitlePath(), IsAFile(), and m_sCDTitleFile.
Referenced by DoInstalls(), LunaSong::HasCDTitle(), and TidyUpData().
HasChartByHash()
bool Song::HasChartByHash (const string & hash)
References FOREACH, and GetAllSteps().
HasDisc()
bool Song::HasDisc () const
References GetDiscPath(), IsAFile(), and m_sDiscFile.
Referenced by LunaSong::HasDisc(), and TidyUpData().
HasEdits()
bool Song::HasEdits (StepsType st) const
References Difficulty_Edit, Steps::GetDifficulty(), Steps::m_StepsType, and m_vpSteps.
Referenced by MusicWheel::BuildWheelItemDatas(), and LunaSong::HasEdits().
HasGoal()
bool Song::HasGoal () inline
References hasgoal.
HasInstrumentTrack()
bool Song::HasInstrumentTrack (InstrumentTrack it) const
References GetInstrumentTrackPath(), IsAFile(), and m_sInstrumentTrackFile.
Referenced by GetInstrumentTracksToVectorString(), and AutoKeysounds::LoadTracks().
HasJacket()
bool Song::HasJacket () const
References GetJacketPath(), IsAFile(), and m_sJacketFile.
Referenced by LunaSong::HasJacket(), and TidyUpData().
HasLyrics()
bool Song::HasLyrics () const
References GetLyricsPath(), IsAFile(), and m_sLyricsFile.
Referenced by LunaSong::HasLyrics(), ScreenGameplay::LoadNextSong(), and TidyUpData().
HasMusic()
bool Song::HasMusic () const
References GetMusicPath(), IsAFile(), m_sMusicFile, and m_vsKeysoundFile.
Referenced by LunaSong::HasMusic(), ScreenNetSelectMusic::MusicChanged(), and TidyUpData().
HasPreviewVid()
bool Song::HasPreviewVid () const
References GetPreviewVidPath(), IsAFile(), and m_sPreviewVidFile.
Referenced by LunaSong::HasPreviewVid().
HasSignificantBpmChangesOrStops()
bool Song::HasSignificantBpmChangesOrStops () const
References DISPLAY_BPM_SPECIFIED, TimingData::HasBpmChanges(), TimingData::HasDelays(), TimingData::HasStops(), m_DisplayBPMType, m_fSpecifiedBPMMax, m_fSpecifiedBPMMin, and m_SongTiming.
Referenced by LunaSong::HasSignificantBPMChangesOrStops().
HasStepsType()
bool Song::HasStepsType (StepsType st) const
References SongUtil::GetOneSteps().
Referenced by MusicWheel::FilterWheelItemDatas(), MusicWheel::GetSongList(), LunaSong::HasStepsType(), and SongCompleteForStyle().
HasStepsTypeAndDifficulty()
bool Song::HasStepsTypeAndDifficulty (StepsType st, Difficulty dc) const
References SongUtil::GetOneSteps().
Referenced by MusicWheel::GetPreferredSelectionForRandomOrPortal(), and LunaSong::HasStepsTypeAndDifficulty().
InitSteps()
void Song::InitSteps (Steps * pSteps)
References m_DisplayBPMType, m_fSpecifiedBPMMax, m_fSpecifiedBPMMin, Steps::SetDisplayBPM(), Steps::SetMaxBPM(), and Steps::SetMinBPM().
Referenced by CreateSteps().
IsEasy()
bool Song::IsEasy (StepsType st) const
References Difficulty_Beginner, Difficulty_Easy, GetDisplayBpms(), DisplayBpms::GetMax(), Steps::GetMeter(), DisplayBpms::GetMin(), and SongUtil::GetStepsByDifficulty().
Referenced by MusicWheel::BuildWheelItemDatas(), and LunaSong::IsEasy().
IsEditAlreadyLoaded()
bool Song::IsEditAlreadyLoaded (Steps * pSteps) const
References ASSERT_M, Difficulty_Edit, DifficultyToString(), Steps::GetDifficulty(), Steps::GetHash(), m_sMainTitle, Steps::m_StepsType, m_vpSteps, and ssprintf().
Referenced by SMLoader::LoadEditFromMsd(), and SSCLoader::LoadEditFromMsd().
IsFavorited()
bool Song::IsFavorited () inline
References isfavorited.
Referenced by ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), and LunaSong::IsFavorited().
IsLong()
bool Song::IsLong () const
References g_fLongVerSongSeconds, IsMarathon(), and m_fMusicLengthSeconds.
Referenced by GameState::GetNumStagesMultiplierForSong(), and LunaSong::IsLong().
IsMarathon()
bool Song::IsMarathon () const
References g_fMarathonVerSongSeconds, and m_fMusicLengthSeconds.
Referenced by GameState::GetNumStagesMultiplierForSong(), IsLong(), and LunaSong::IsMarathon().
IsPermaMirror()
bool Song::IsPermaMirror () inline
References permamirror.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
IsSkillsetHighestOfAnySteps()
bool Song::IsSkillsetHighestOfAnySteps (Skillset ss, float rate)
References FOREACH, FOREACHM, GetAllSteps(), NUM_Skillset, and Skillset_Invalid.
IsStepsUsingDifferentTiming()
bool Song::IsStepsUsingDifferentTiming (Steps * pSteps) const
References TimingData::empty(), and Steps::m_Timing.
Referenced by LunaSong::IsStepsUsingDifferentTiming().
IsTutorial()
bool Song::IsTutorial () const
References Difficulty_Beginner, FOREACH_CONST, and m_vpSteps.
Referenced by LunaSong::IsTutorial(), SongCriteria::Matches(), MusicWheel::SetOpenSection(), and ShowInDemonstrationAndRanking().
LoadAutosaveFile()
bool Song::LoadAutosaveFile ()
References GetSongDir(), LoadFromSongDir(), m_loaded_from_autosave, TimingData::m_sFile, m_SongTiming, m_sSongFileName, and Reset().
LoadFromSongDir()
bool Song::LoadFromSongDir (RString sDir, bool load_autosave = false)
References ASSERT_M, BlacklistedImages, FILEMAN, FinalizeLoading(), FT_Sound, RageFileManager::GetDirListingWithMultipleExtensions(), ActorUtil::GetTypeExtensionList(), NotesLoader::LoadFromDir(), LOG, m_bHasMusic, m_sSongDir, m_sSongFileName, StdString::CStdStr< CT >::Right(), SaveToCacheFile(), split(), TidyUpData(), and RageLog::UserLog().
Referenced by SongManager::DifferentialReloadDir(), LoadAutosaveFile(), SongManager::LoadStepManiaSongDir(), and ReloadFromSongDir().
Matches()
bool Song::Matches (const RString & sGroup, const RString & sSong) const
References ASSERT, StdString::CStdStr< CT >::CompareNoCase(), GetSongDir(), m_sGroupName, StdString::CStdStr< CT >::Replace(), and split().
PushSelf()
void Song::PushSelf (lua_State * L)
Referenced by LunaSongManager::FindSong(), LunaGameState::GetCurrentSong(), LunaSongManager::GetExtraStageInfo(), LunaProfile::GetLastPlayedSong(), LunaProfile::GetMostPopularSong(), LunaGameState::GetPreferredSong(), LunaSongManager::GetRandomSong(), LunaGameCommand::GetSong(), LunaSongManager::GetSongByChartKey(), and LunaSongManager::GetSongFromSteps().
ReCalculateRadarValuesAndLastSecond()
void Song::ReCalculateRadarValuesAndLastSecond (bool fromCache = false, bool duringCache = false)
Get the new radar values, and determine the last second at the same time. This is called by TidyUpData, after saving the Song.
Parameters
fromCache was this data loaded from the cache file?
duringCache was this data loaded during the cache process?
References firstSecond, lastSecond, m_fMusicLengthSeconds, m_vpSteps, max(), min(), and specifiedLastSecond.
Referenced by Save(), and TidyUpData().
ReloadFromSongDir() [1/2]
bool Song::ReloadFromSongDir (const RString & sDir)
References AddSteps(), SongCacheIndex::DeleteSongFromDBByDir(), FILEMAN, FOREACH_ENUM, StepsID::FromSteps(), GetCacheFilePath(), GetSongDir(), RageTextureManager::IsTextureRegistered(), LoadFromSongDir(), RageTextureManager::LoadTexture(), m_sBackgroundFile, m_sBannerFile, m_sCDFile, m_sCDTitleFile, m_sDiscFile, m_sJacketFile, m_sPreviewVidFile, m_vpSteps, m_vpStepsByType, RageTexture::Reload(), RageFileManager::Remove(), SONGINDEX, and TEXTUREMAN.
Referenced by ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), LunaSong::ReloadFromSongDir(), and AdjustSync::SaveSyncChanges().
ReloadFromSongDir() [2/2]
bool Song::ReloadFromSongDir () inline
References GetSongDir(), and ReloadFromSongDir().
Referenced by ReloadFromSongDir().
RemoveAutosave()
void Song::RemoveAutosave ()
References RageFileManager::DoesFileExist(), FILEMAN, GetExtension(), m_loaded_from_autosave, m_sSongFileName, RageFileManager::Remove(), and SetExtension().
Referenced by SaveToETTFile(), and SaveToSSCFile().
Reset()
void Song::Reset ()
References FOREACH, FOREACH_ENUM, m_UnknownStyleSteps, m_vpSteps, m_vpStepsByType, and SAFE_DELETE.
Referenced by LoadAutosaveFile().
Save()
void Song::Save (bool autosave = false)
Save to the SSC and SM files no matter what.
References SongCacheIndex::DeleteSongFromDBByDir(), FileCopy(), FILEMAN, RageFileManager::FlushDirCache(), GetDirListing(), GetSongDir(), GetSongFilePath(), LOG, m_sSongDir, ReCalculateRadarValuesAndLastSecond(), RageFileManager::Remove(), SaveToCacheFile(), SaveToSSCFile(), SONGINDEX, RageLog::Trace(), TranslateTitles(), and RageLog::UserLog().
Referenced by AdjustSync::SaveSyncChanges().
SaveToCacheFile()
bool Song::SaveToCacheFile ()
Save the current Song to a cache file using the preferred format.
Returns
its success or failure.
References SongCacheIndex::CacheSong(), SongManager::IsGroupNeverCached(), m_sGroupName, m_sSongDir, SONGINDEX, and SONGMAN.
Referenced by LoadFromSongDir(), and Save().
SaveToDWIFile()
bool Song::SaveToDWIFile ()
Save the current Song to a DWI file if possible.
Returns
its success or failure.
References FileCopy(), GetSongFilePath(), IsAFile(), LOG, SetExtension(), RageLog::Trace(), and NotesWriterDWI::Write().
SaveToETTFile()
bool Song::SaveToETTFile (const RString & sPath, bool bSavingCache, bool autosave = false)
References FileCopy(), FOREACH, g_BackUpAllSongSaves, Preference< T >::Get(), GetExtension(), GetStepsToSave(), IsAFile(), LOG, RemoveAutosave(), SetExtension(), ssprintf(), RageLog::Trace(), and NotesWriterETT::Write().
SaveToJsonFile()
bool Song::SaveToJsonFile (const RString & sPath)
Save the current Song to a JSON file.
Returns
its success or failure.
References LOG, RageLog::Trace(), and NotesWriterJson::WriteSong().
SaveToSMFile()
bool Song::SaveToSMFile ()
Save the current Song to a SM file.
Returns
its success or failure.
References FileCopy(), GetSongFilePath(), GetStepsToSave(), IsAFile(), LOG, SetExtension(), RageLog::Trace(), and NotesWriterSM::Write().
SaveToSSCFile()
bool Song::SaveToSSCFile (const RString & sPath, bool bSavingCache, bool autosave = false)
Save to the new SSC file format.
Parameters
sPath the path where we're saving the file.
bSavingCache a flag to determine if we're saving cache data.
References SongCacheIndex::CacheSong(), FileCopy(), FOREACH, g_BackUpAllSongSaves, Preference< T >::Get(), GetExtension(), GetStepsToSave(), IsAFile(), LOG, m_sSongFileName, RemoveAutosave(), SetExtension(), SONGINDEX, ssprintf(), RageLog::Trace(), and NotesWriterSSC::Write().
Referenced by Save().
SetEnabled()
void Song::SetEnabled (bool b) inline
Referenced by SongManager::AddSongToList(), and SongManager::LoadEnabledSongsFromPref().
SetFavorited()
void Song::SetFavorited (bool b) inline
References isfavorited.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
SetFirstSecond()
void Song::SetFirstSecond (float f)
References f, and firstSecond.
Referenced by SetFirstSecond(), and SongCacheIndex::SongFromStatement().
SetHasGoal()
void Song::SetHasGoal (bool b) inline
References hasgoal.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
SetLastSecond()
void Song::SetLastSecond (float f)
References f, and lastSecond.
Referenced by SetLastSecond(), and SongCacheIndex::SongFromStatement().
SetPermaMirror()
void Song::SetPermaMirror (bool b) inline
References permamirror.
Referenced by ScreenNetSelectMusic::Input(), and ScreenSelectMusic::Input().
SetSongDir()
void Song::SetSongDir (const RString & sDir) inline
Referenced by Deserialize(), Profile::ImportScoresToEtterna(), ScreenGameplaySyncMachine::Init(), and SongCacheIndex::SongFromStatement().
SetSpecifiedLastSecond()
void Song::SetSpecifiedLastSecond (float f)
References f, and specifiedLastSecond.
Referenced by LoadFromKSFFile(), SetLastSecondHint(), and SongCacheIndex::SongFromStatement().
ShowInDemonstrationAndRanking()
bool Song::ShowInDemonstrationAndRanking () const
References IsTutorial().
Referenced by LunaSong::ShowInDemonstrationAndRanking().
SongCompleteForStyle()
bool Song::SongCompleteForStyle (const Style * st) const
References HasStepsType(), and Style::m_StepsType.
TidyUpData()
void Song::TidyUpData (bool fromCache = false, bool duringCache = false)
Call this after loading a song to clean up invalid data.
Parameters
fromCache was this data loaded from the cache file?
duringCache was this data loaded during the cache process?
References AddBackgroundChange(), SongUtil::AdjustDuplicateSteps(), ASSERT_M, BACKGROUND_LAYER_1, Basename(), BlacklistedImages, CHECKPOINT_M, CLEAR_NOT_HAS, StdString::CStdStr< CT >::CompareNoCase(), contains(), DEFAULT_MUSIC_SAMPLE_LENGTH, ends_with(), StdString::CStdStr< CT >::EqualsNoCase(), f, FILEMAN, FindFirstFilenameContaining(), FixupPath(), FOREACH, FOREACH_ENUM, FT_Bitmap, FT_Movie, FT_Sound, TimingData::GetBeatFromElapsedTime(), GetCacheFile(), RageFileManager::GetDirListing(), GetExtension(), GetLastSecond(), RageSoundReader::GetLength(), NotesLoader::GetMainAndSubTitlesFromFullTitle(), GetMusicPath(), GetPreviewMusicPath(), GetSongDir(), ActorUtil::GetTypeExtensionList(), RageSurface::h, HasBackground(), HasBanner(), HasBGChanges(), HasCDImage(), HasCDTitle(), HasDisc(), HasJacket(), HasLyrics(), HasMusic(), IMAGECACHE, ImageDir, Rage::join(), lastSecond, StdString::CStdStr< CT >::Left(), RageSurfaceUtils::LoadFile(), ImageCache::LoadImage(), LOG, m_bHasBackground, m_bHasBanner, m_bHasMusic, m_fMusicLengthSeconds, m_fMusicSampleLengthSeconds, m_fMusicSampleStartSeconds, m_PreviewFile, m_sArtist, m_sBackgroundFile, m_sBannerFile, m_sCDFile, m_sCDTitleFile, m_sDiscFile, m_sInstrumentTrackFile, m_sJacketFile, m_sLyricsFile, m_sMainTitle, m_sMusicFile, m_SongTiming, m_sSongDir, m_sSubTitle, m_vpSteps, StdString::CStdStr< CT >::MakeLower(), RageSoundReader_FileReader::OpenFile(), ReCalculateRadarValuesAndLastSecond(), SBE_StretchNoLoop, split(), starts_with(), TimingData::TidyUpData(), RageLog::Trace(), TranslateTitles(), Trim(), RageLog::UserLog(), RageSurface::w, and TimingData::WhereUAtBro().
Referenced by ScreenGameplaySyncMachine::Init(), LoadFromSongDir(), SongCacheIndex::SongFromStatement(), and SMLoader::TidyUpData().
TranslateTitles()
void Song::TranslateTitles ()
Translate any titles that aren't in english. This is called by TidyUpData.
References TitleFields::LoadFromStrings(), m_sArtist, m_sArtistTranslit, m_sMainTitle, m_sMainTitleTranslit, m_sSubTitle, m_sSubTitleTranslit, TitleFields::SaveToStrings(), and TitleSubst::Subst().
Referenced by Save(), and TidyUpData().
WasLoadedFromAutosave()
bool Song::WasLoadedFromAutosave () const inline
References m_loaded_from_autosave.
WasLoadedFromProfile()
bool Song::WasLoadedFromProfile () const inline
References ProfileSlot_Invalid.
Member Data Documentation
firstSecond
float Song::firstSecond private
The first second that a note is hit.
Referenced by GetFirstBeat(), GetFirstSecond(), ReCalculateRadarValuesAndLastSecond(), SetFirstSecond(), and Song().
hasgoal
bool Song::hasgoal = false private
Referenced by HasGoal(), and SetHasGoal().
ImageDir
vector<RString> Song::ImageDir
Referenced by FinalizeLoading(), Song(), and TidyUpData().
isfavorited
bool Song::isfavorited = false private
Referenced by IsFavorited(), and SetFavorited().
lastSecond
float Song::lastSecond private
The last second that a note is hit.
Referenced by GetLastBeat(), GetLastSecond(), ReCalculateRadarValuesAndLastSecond(), SetLastSecond(), Song(), and TidyUpData().
m_BackgroundChanges
AutoPtrCopyOnWrite<VBackgroundChange> Song::m_BackgroundChanges[NUM_BackgroundLayer] private
The background changes (sorted by layer) that are for this Song. This uses an AutoPtr instead of a raw pointer so that the auto gen'd copy constructor works correctly. This must be sorted before gameplay.
Referenced by GetBackgroundChanges(), and Song().
m_bEnabled
bool Song::m_bEnabled
Referenced by GetEnabled(), and Song().
m_bHasBackground
bool Song::m_bHasBackground
Referenced by Song(), and TidyUpData().
m_bHasBanner
bool Song::m_bHasBanner
Referenced by SongCacheIndex::CacheSong(), Deserialize(), SetHasBanner(), Song(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterSSC::Write(), NotesWriterETT::Write(), and NotesWriterJson::WriteSong().
m_bHasMusic
bool Song::m_bHasMusic
Referenced by SongCacheIndex::CacheSong(), Deserialize(), LoadFromSongDir(), SetHasMusic(), Song(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterSSC::Write(), NotesWriterETT::Write(), and NotesWriterJson::WriteSong().
m_bIsSymLink
bool Song::m_bIsSymLink
Is the song file itself a symlink to another file?
Referenced by Song().
m_CachedObject
CachedObject<Song> Song::m_CachedObject
m_DisplayBPMType
DisplayBPM Song::m_DisplayBPMType
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetDisplayBpms(), HasSignificantBpmChangesOrStops(), InitSteps(), LunaSong::IsDisplayBpmRandom(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), BPMDisplay::SetBpmFromSong(), SetDisplayBPM(), OsuLoader::SetTimingData(), SMSetDisplayBPM(), Song(), SongCacheIndex::SongFromStatement(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_fMusicLengthSeconds
float Song::m_fMusicLengthSeconds
The length of the music file.
Referenced by SongCacheIndex::CacheSong(), CompareSongPointersByLength(), Deserialize(), ScreenGameplay::GetMusicEndTiming(), SongUtil::GetSectionNameFromSongAndSort(), IsLong(), IsMarathon(), ScoreKeeperNormal::Load(), LunaSong::MusicLengthSeconds(), LifeMeterTime::OnLoadSong(), ReCalculateRadarValuesAndLastSecond(), ScreenGameplay::SaveStats(), Player::SetCombo(), SetMusicLength(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), Song(), SongCacheIndex::SongFromStatement(), ScreenGameplay::StartPlayingSong(), TidyUpData(), ScreenGameplay::ToggleReplayPause(), NotesWriterSSC::Write(), NotesWriterETT::Write(), and NotesWriterJson::WriteSong().
m_fMusicSampleLengthSeconds
float Song::m_fMusicSampleLengthSeconds
Referenced by BMSSongLoader::AddToSong(), ScreenSelectMusic::AfterMusicChange(), SongCacheIndex::CacheSong(), Deserialize(), LunaSong::GetSampleLength(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), LoadGlobalData(), ScreenNetSelectMusic::MusicChanged(), SetSampleLength(), OsuLoader::SetTimingData(), SMSetSampleLength(), Song(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_fMusicSampleStartSeconds
float Song::m_fMusicSampleStartSeconds
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), GetPreviewStartSeconds(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), LoadGlobalData(), SetSampleStart(), OsuLoader::SetTimingData(), SMSetSampleStart(), Song(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_ForegroundChanges
AutoPtrCopyOnWrite<VBackgroundChange> Song::m_ForegroundChanges private
The foreground changes that are for this Song. This uses an AutoPtr instead of a raw pointer so that the auto gen'd copy constructor works correctly. This must be sorted before gameplay.
Referenced by GetForegroundChanges(), and Song().
m_fSpecifiedBPMMax
float Song::m_fSpecifiedBPMMax
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetDisplayBpms(), HasSignificantBpmChangesOrStops(), InitSteps(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SetDisplayBPM(), SMSetDisplayBPM(), Song(), SongCacheIndex::SongFromStatement(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_fSpecifiedBPMMin
float Song::m_fSpecifiedBPMMin
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetDisplayBpms(), HasSignificantBpmChangesOrStops(), InitSteps(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SetDisplayBPM(), SMSetDisplayBPM(), Song(), SongCacheIndex::SongFromStatement(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_fVersion
float Song::m_fVersion
The version of the song/file.
Referenced by SSCLoader::LoadFromSimfile(), SetDescription(), SetSongWarps(), SetStepsBPMs(), SetStepsCombos(), SetStepsDelays(), SetStepsFakes(), SetStepsLabels(), SetStepsOffset(), SetStepsScrolls(), SetStepsSpeeds(), SetStepsStops(), SetStepsTickCounts(), SetStepsTimeSignatures(), SetStepsVersion(), SetStepsWarps(), SetVersion(), Song(), and SongCacheIndex::SongFromStatement().
m_loaded_from_autosave
bool Song::m_loaded_from_autosave private
Referenced by LoadAutosaveFile(), RemoveAutosave(), Song(), and WasLoadedFromAutosave().
m_LoadedFromProfile
ProfileSlot Song::m_LoadedFromProfile
the Profile this came from. This is ProfileSlot_Invalid if it wasn't loaded from a profile.
Referenced by Song().
m_LyricSegments
vector<LyricSegment> Song::m_LyricSegments
The list of LyricSegments. This must be sorted before gameplay.
Referenced by AddLyricSegment(), Deserialize(), LyricsLoader::LoadFromLRCFile(), LyricDisplay::Update(), and NotesWriterJson::WriteSong().
m_PreviewFile
RString Song::m_PreviewFile
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), GetPreviewMusicPath(), GetPreviewStartSeconds(), SetPreview(), SongCacheIndex::SongFromStatement(), TidyUpData(), SongUtil::ValidateCurrentSongPreview(), and WriteGlobalTags().
m_sArtist
RString Song::m_sArtist
The artist of the Song, if it exists.
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), GetDisplayArtist(), GetTranslitArtist(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), LoadTags(), ETTProtocol::SelectUserSong(), SetArtist(), OsuLoader::SetMetadata(), SMSetArtist(), SongCacheIndex::SongFromStatement(), SMOProtocol::StartRequest(), TidyUpData(), TranslateTitles(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sArtistTranslit
RString Song::m_sArtistTranslit
The transliterated artist of the Song, if it exists.
Referenced by SongCacheIndex::CacheSong(), GetTranslitArtist(), SMALoader::LoadFromSimfile(), SetArtistTranslit(), SMSetArtistTranslit(), SongCacheIndex::SongFromStatement(), TranslateTitles(), and WriteGlobalTags().
m_sBackgroundFile
RString Song::m_sBackgroundFile
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), DoInstalls(), GetBackgroundPath(), HasBackground(), SMALoader::LoadFromSimfile(), LoadGlobalData(), ReloadFromSongDir(), SetBackground(), SMSetBackground(), SongCacheIndex::SongFromStatement(), SMLoader::TidyUpData(), TidyUpData(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sBannerFile
RString Song::m_sBannerFile
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), DoInstalls(), GetBannerPath(), HasBanner(), SMALoader::LoadFromSimfile(), LoadGlobalData(), ReloadFromSongDir(), SetBanner(), SMSetBanner(), SongCacheIndex::SongFromStatement(), TidyUpData(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sCDFile
RString Song::m_sCDFile
Referenced by SongCacheIndex::CacheSong(), GetCDImagePath(), HasCDImage(), ReloadFromSongDir(), SetCDImage(), SongCacheIndex::SongFromStatement(), TidyUpData(), and WriteGlobalTags().
m_sCDTitleFile
RString Song::m_sCDTitleFile
Referenced by SongCacheIndex::CacheSong(), Deserialize(), DoInstalls(), GetCDTitlePath(), HasCDTitle(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), ReloadFromSongDir(), SetCDTitle(), SMSetCDTitle(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sCredit
RString Song::m_sCredit
The person who worked with the song file who should be credited. This is read and saved, but never actually used.
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetOrTryAtLeastToGetSimfileAuthor(), SMALoader::LoadFromSimfile(), SetCredit(), SMSetCredit(), SongCacheIndex::SongFromStatement(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sDiscFile
RString Song::m_sDiscFile
Referenced by SongCacheIndex::CacheSong(), GetDiscPath(), HasDisc(), ReloadFromSongDir(), SetDiscImage(), SongCacheIndex::SongFromStatement(), TidyUpData(), and WriteGlobalTags().
m_SelectionDisplay
enum Song::SelectionDisplay Song::m_SelectionDisplay
Referenced by SongCacheIndex::CacheSong(), Deserialize(), SMALoader::LoadFromSimfile(), SetSelectable(), SMSetSelectable(), Song(), SongCacheIndex::SongFromStatement(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sFileHash
RString Song::m_sFileHash
Referenced by GetFileHash().
m_sGenre
RString Song::m_sGenre
The genre of the song/file.
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), CompareSongPointersByGenre(), Deserialize(), GetFilterToFileNames(), LunaSong::GetGenre(), SongUtil::GetSectionNameFromSongAndSort(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SongCriteria::Matches(), SetGenre(), OsuLoader::SetMetadata(), SMSetGenre(), SongCacheIndex::SongFromStatement(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sGroupName
RString Song::m_sGroupName
The group this Song is in.
Referenced by SongManager::AddKeyedPointers(), MusicWheel::BuildWheelItemDatas(), SongUtil::CompareSongPointersByGroup(), CompareSongPointersByGroup(), Deserialize(), FinalizeLoading(), SongManager::FinalizeSong(), Chart::FromKey(), SongManager::GetExtraStageInfo(), GetFilterToFileNames(), LunaSong::GetGroupName(), SongUtil::GetSectionNameFromSongAndSort(), SongManager::GetSongColor(), Profile::ImportScoresToEtterna(), SongCriteria::Matches(), Matches(), SaveToCacheFile(), and NotesWriterJson::WriteSong().
m_sInstrumentTrackFile
RString Song::m_sInstrumentTrackFile[NUM_InstrumentTrack]
Referenced by GetInstrumentTrackPath(), GetInstrumentTracksToVectorString(), HasInstrumentTrack(), SMLoader::ProcessInstrumentTracks(), and TidyUpData().
m_sJacketFile
RString Song::m_sJacketFile
Referenced by SongCacheIndex::CacheSong(), GetJacketPath(), HasJacket(), ReloadFromSongDir(), SetJacket(), SongCacheIndex::SongFromStatement(), TidyUpData(), and WriteGlobalTags().
m_sLyricsFile
RString Song::m_sLyricsFile
The location of the lyrics file, if it exists.
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetLyricsPath(), HasLyrics(), SMALoader::LoadFromSimfile(), SetLyricsPath(), SMSetLyricsPath(), SongCacheIndex::SongFromStatement(), TidyUpData(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sMainTitle
RString Song::m_sMainTitle
The title of the Song.
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), AutoKeysounds::FinishLoading(), GetDisplayMainTitle(), GetMainTitle(), GetSongFilePath(), GetTranslitMainTitle(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), IsEditAlreadyLoaded(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), LoadTags(), ETTProtocol::SelectUserSong(), OsuLoader::SetMetadata(), SetTitle(), SMSetTitle(), SongCacheIndex::SongFromStatement(), SMOProtocol::StartRequest(), TidyUpData(), TranslateTitles(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sMainTitleTranslit
RString Song::m_sMainTitleTranslit
The transliterated title of the Song, if it exists.
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetTranslitMainTitle(), SMALoader::LoadFromSimfile(), SetMainTitleTranslit(), SMSetTitleTranslit(), SongCacheIndex::SongFromStatement(), TranslateTitles(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sMusicFile
RString Song::m_sMusicFile
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), Steps::GetMusicPath(), GetMusicPath(), HasMusic(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), LoadGlobalData(), OsuLoader::SetMetadata(), SetMusic(), SMSetMusic(), SongCacheIndex::SongFromStatement(), TidyUpData(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_SongTiming
TimingData Song::m_SongTiming
The Song's TimingData.
Referenced by BMSSongLoader::AddToSong(), ScreenSelectMusic::AfterMusicChange(), AdjustSync::AutosyncOffset(), AdjustSync::AutosyncTempo(), SongCacheIndex::CacheSong(), Deserialize(), GetDisplayBpms(), PlayerState::GetDisplayedTiming(), GetFirstBeat(), GetLastBeat(), GameState::GetSongPercent(), GetSpecifiedLastBeat(), AdjustSync::GetSyncChangeTextSong(), Steps::GetTimingData(), LunaSong::GetTimingData(), HasSignificantBpmChangesOrStops(), ScreenHowToPlay::Init(), Player::Init(), ScreenSyncOverlay::Input(), LoadAutosaveFile(), DWILoader::LoadFromDir(), BackgroundImpl::LoadFromRandom(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), OsuLoader::LoadNoteDataFromParsedData(), OsuLoader::MsToNoteRow(), ScreenNetSelectMusic::MusicChanged(), AdjustSync::ResetOriginalSyncData(), AdjustSync::RevertSyncChanges(), AdjustSync::SaveSyncChanges(), ScreenGameplay::SendCrossedMessages(), SetOffset(), SetSongBPMs(), SetSongCombos(), SetSongDelays(), SetSongFakes(), SetSongLabels(), SetSongScrolls(), SetSongSpeeds(), SetSongStops(), SetSongTickCounts(), SetSongTimeSignatures(), SetSongWarps(), OsuLoader::SetTimingData(), SMSetDelays(), SMSetOffset(), SMSetTickCounts(), SMSetTimeSignatures(), SongCacheIndex::SongFromStatement(), StartMusic(), TidyUpData(), Foreground::Update(), ScreenHowToPlay::Update(), BackgroundImpl::Layer::UpdateCurBGChange(), ScreenGameplay::UpdateSongPosition(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sOrigin
RString Song::m_sOrigin
Referenced by SongCacheIndex::CacheSong(), LunaSong::GetOrigin(), SetOrigin(), SongCacheIndex::SongFromStatement(), and WriteGlobalTags().
m_sPreviewVidFile
RString Song::m_sPreviewVidFile
Referenced by SongCacheIndex::CacheSong(), GetPreviewVidPath(), HasPreviewVid(), SMALoader::LoadFromSimfile(), ReloadFromSongDir(), SetPreviewVid(), SongCacheIndex::SongFromStatement(), and WriteGlobalTags().
m_sSongDir
RString Song::m_sSongDir private
Referenced by FinalizeLoading(), GetBackgroundPath(), GetBannerPath(), GetCacheFile(), GetCacheFilePath(), GetCDImagePath(), GetCDTitlePath(), GetDiscPath(), GetInstrumentTrackPath(), GetJacketPath(), GetLyricsPath(), GetMusicPath(), GetPreviewMusicPath(), GetPreviewVidPath(), GetSongDir(), LoadFromSongDir(), Save(), SaveToCacheFile(), and TidyUpData().
m_sSongFileName
RString Song::m_sSongFileName
Filename associated with this file. This will always have a .SSC extension. If we loaded a .SSC, this will point to it, but if we loaded any other type, this will point to a generated .SSC filename.
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), GetSongFilePath(), HasAutosaveFile(), LoadAutosaveFile(), KSFLoader::LoadFromDir(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadFromSongDir(), RemoveAutosave(), SaveToSSCFile(), SetSongFilename(), SongCacheIndex::SongFromStatement(), Steps::TidyUpData(), NotesWriterSSC::Write(), NotesWriterETT::Write(), and NotesWriterJson::WriteSong().
m_sSubTitle
RString Song::m_sSubTitle
The subtitle of the Song, if it exists.
Referenced by BMSSongLoader::AddToSong(), SongCacheIndex::CacheSong(), Deserialize(), GetDisplaySubTitle(), GetTranslitSubTitle(), DWILoader::LoadFromDir(), SMALoader::LoadFromSimfile(), ETTProtocol::SelectUserSong(), OsuLoader::SetMetadata(), SetSubtitle(), SMSetSubtitle(), SongCacheIndex::SongFromStatement(), SMOProtocol::StartRequest(), TidyUpData(), TranslateTitles(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sSubTitleTranslit
RString Song::m_sSubTitleTranslit
The transliterated subtitle of the Song, if it exists.
Referenced by SongCacheIndex::CacheSong(), Deserialize(), GetTranslitSubTitle(), SMALoader::LoadFromSimfile(), SetSubtitleTranslit(), SMSetSubtitleTranslit(), SongCacheIndex::SongFromStatement(), TranslateTitles(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_UnknownStyleSteps
vector<Steps*> Song::m_UnknownStyleSteps
Referenced by AddSteps(), DetachSteps(), DoInstalls(), GetStepsToSave(), Reset(), and ~Song().
m_vpSteps
vector<Steps*> Song::m_vpSteps
Referenced by AddSteps(), AnyChartUsesSplitTiming(), DeleteSteps(), DetachSteps(), DoInstalls(), FinalizeLoading(), FreeAllLoadedFromProfile(), GetAllSteps(), GetNumStepsLoadedFromProfile(), GetStepsLoadedFromProfile(), GetStepsToSave(), HasEdits(), IsEditAlreadyLoaded(), IsTutorial(), ReCalculateRadarValuesAndLastSecond(), ReloadFromSongDir(), Reset(), TidyUpData(), and ~Song().
m_vpStepsByType
vector<Steps*> Song::m_vpStepsByType[NUM_StepsType] private
the Steps that belong to this Song.
the Steps of a particular StepsType that belong to this Song.
Referenced by AddSteps(), DeleteSteps(), DetachSteps(), GetStepsByStepsType(), ReloadFromSongDir(), and Reset().
m_vsKeysoundFile
vector<RString> Song::m_vsKeysoundFile
An array of keysound file names (e.g. "beep.wav"). The index in this array corresponds to the index in TapNote. If you change the index in here, you must change all NoteData too. Any note that doesn't have a value in the range of this array means "this note doesn't have a keysound".
Referenced by BMSSong::AllocateKeysound(), BMSSong::BMSSong(), SongCacheIndex::CacheSong(), Deserialize(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), HasMusic(), AutoKeysounds::LoadAutoplaySoundsInto(), BMSLoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SetKeysounds(), SMSetKeysounds(), SongCacheIndex::SongFromStatement(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
permamirror
bool Song::permamirror = false private
Referenced by IsPermaMirror(), and SetPermaMirror().
specifiedLastSecond
float Song::specifiedLastSecond private
The last second of the song for playing purposes.
Referenced by GetSpecifiedLastBeat(), GetSpecifiedLastSecond(), ReCalculateRadarValuesAndLastSecond(), SetSpecifiedLastSecond(), and Song().
The documentation for this class was generated from the following files:
Song.h
Song.cpp