Etterna: RageSoundDriver_WDMKS.cpp File Reference
RageSoundDriver_WDMKS.cpp File Reference
#include "RageSoundDriver_WDMKS.h"
#include "Foreach.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Win32/ErrorStrings.h"
#include "global.h"
#include <ks.h>
#include <ksmedia.h>
#include <mmsystem.h>
#include <setupapi.h>
#include <windows.h>
#include <winioctl.h>
Classes
struct WinWdmPin
struct WinWdmFilter
struct WinWdmStream
Macros
#define _INC_MMREG
#define _NTRTL_ /* Turn off default definition of DEFINE_GUIDEX */
#define DEFINE_WAVEFORMATEX_GUID(x) (USHORT)(x), 0x0000, 0x0010, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71
#define KSAUDIO_SPEAKER_5POINT1_SURROUND
#define KSAUDIO_SPEAKER_7POINT1_SURROUND
#define MAX_CHUNKS 4
Typedefs
typedef KSDDKAPI DWORD WINAPI KSCREATEPIN(HANDLE, PKSPIN_CONNECT, ACCESS_MASK, PHANDLE)
Enumerations
enum DeviceSampleFormat {
DeviceSampleFormat_Float32, DeviceSampleFormat_Int16, DeviceSampleFormat_Int24, DeviceSampleFormat_Int32,
NUM_DeviceSampleFormat, DeviceSampleFormat_Invalid
}
Functions
static int GetBytesPerSample (DeviceSampleFormat sf)
static RString GUIDToString (const GUID *pGuid)
static bool WdmSyncIoctl (HANDLE hHandle, unsigned long ioctlNumber, void *pIn, unsigned long iInSize, void *pOut, unsigned long iOutSize, unsigned long *pBytesReturned, RString &sError)
static bool WdmGetPropertySimple (HANDLE hHandle, const GUID *pGuidPropertySet, unsigned long iProperty, void *pValue, unsigned long iValueSize, void *pInstance, unsigned long iInstanceSize, RString &sError)
static bool WdmSetPropertySimple (HANDLE hHandle, const GUID *pGuidPropertySet, unsigned long iProperty, void *pValue, unsigned long iValueSize, void *instance, unsigned long iInstanceSize, RString &sError)
static bool WdmGetPinPropertySimple (HANDLE hHandle, unsigned long iPinId, const GUID *pGuidPropertySet, unsigned long iProperty, void *pValue, unsigned long iInstanceSize, RString &sError)
static bool WdmGetPinPropertyMulti (HANDLE hHandle, unsigned long iPinId, const GUID *pGuidPropertySet, unsigned long iProperty, KSMULTIPLE_ITEM **ksMultipleItem, RString &sError)
template<typename T , typename U >
void MoveToBeginning (vector< T > &v, const U &item)
static void FillWFEXT (WAVEFORMATEXTENSIBLE *pwfext, DeviceSampleFormat sampleFormat, int sampleRate, int channelCount)
static bool GetDevicePath (HANDLE hHandle, SP_DEVICE_INTERFACE_DATA *pInterfaceData, RString &sPath)
static bool BuildFilterList (vector< WinWdmFilter *> &aFilters, RString &sError)
static bool PaWinWdm_Initialize (RString &sError)
REGISTER_SOUND_DRIVER_CLASS (WDMKS)
Variables
static HMODULE DllKsUser = NULL
static KSCREATEPIN * FunctionKsCreatePin = NULL
Macro Definition Documentation
_INC_MMREG
#define _INC_MMREG
_NTRTL_
#define _NTRTL_ /* Turn off default definition of DEFINE_GUIDEX */
DEFINE_WAVEFORMATEX_GUID
#define DEFINE_WAVEFORMATEX_GUID (x) (USHORT)(x), 0x0000, 0x0010, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71
Referenced by WinWdmPin::IsFormatSupported().
KSAUDIO_SPEAKER_5POINT1_SURROUND
#define KSAUDIO_SPEAKER_5POINT1_SURROUND
Value:
(SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER |         \
     SPEAKER_LOW_FREQUENCY | SPEAKER_SIDE_LEFT | SPEAKER_SIDE_RIGHT)
KSAUDIO_SPEAKER_7POINT1_SURROUND
#define KSAUDIO_SPEAKER_7POINT1_SURROUND
Value:
(SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER |         \
     SPEAKER_LOW_FREQUENCY | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT |          \
     SPEAKER_SIDE_LEFT | SPEAKER_SIDE_RIGHT)
Referenced by FillWFEXT().
MAX_CHUNKS
#define MAX_CHUNKS 4
Referenced by RageSoundDriver_WDMKS::MixerThread(), WinWdmStream::Open(), and WinWdmStream::WinWdmStream().
Typedef Documentation
KSCREATEPIN
typedef KSDDKAPI DWORD WINAPI KSCREATEPIN(HANDLE, PKSPIN_CONNECT, ACCESS_MASK, PHANDLE)
Enumeration Type Documentation
DeviceSampleFormat
enum DeviceSampleFormat
Enumerator
DeviceSampleFormat_Float32
DeviceSampleFormat_Int16
DeviceSampleFormat_Int24
DeviceSampleFormat_Int32
NUM_DeviceSampleFormat
DeviceSampleFormat_Invalid
Function Documentation
BuildFilterList()
static bool BuildFilterList (vector< WinWdmFilter *> & aFilters, RString & sError) static
References CHECKPOINT_M, WinWdmFilter::Create(), GetDevicePath(), LOG, MAX_PATH, and RageLog::Trace().
Referenced by RageSoundDriver_WDMKS::Init().
FillWFEXT()
static void FillWFEXT (WAVEFORMATEXTENSIBLE * pwfext, DeviceSampleFormat sampleFormat, int sampleRate, int channelCount) static
References DeviceSampleFormat_Float32, DeviceSampleFormat_Int16, DeviceSampleFormat_Int24, DeviceSampleFormat_Int32, GetBytesPerSample(), and KSAUDIO_SPEAKER_7POINT1_SURROUND.
Referenced by WinWdmFilter::InstantiateRenderPin().
GetBytesPerSample()
static int GetBytesPerSample (DeviceSampleFormat sf) static
References DEFAULT_FAIL, DeviceSampleFormat_Float32, DeviceSampleFormat_Int16, DeviceSampleFormat_Int24, and DeviceSampleFormat_Int32.
Referenced by FillWFEXT(), and WinWdmStream::Open().
GetDevicePath()
static bool GetDevicePath (HANDLE hHandle, SP_DEVICE_INTERFACE_DATA * pInterfaceData, RString & sPath) static
References MAX_PATH.
Referenced by BuildFilterList().
GUIDToString()
static RString GUIDToString (const GUID * pGuid) static
References ssprintf().
MoveToBeginning()
template<typename T , typename U > void MoveToBeginning (vector< T > & v, const U & item)
Referenced by WinWdmFilter::InstantiateRenderPin().
PaWinWdm_Initialize()
static bool PaWinWdm_Initialize (RString & sError) static
References DllKsUser, and FunctionKsCreatePin.
Referenced by RageSoundDriver_WDMKS::Init().
REGISTER_SOUND_DRIVER_CLASS()
REGISTER_SOUND_DRIVER_CLASS (WDMKS)
WdmGetPinPropertyMulti()
static bool WdmGetPinPropertyMulti (HANDLE hHandle, unsigned long iPinId, const GUID * pGuidPropertySet, unsigned long iProperty, KSMULTIPLE_ITEM ** ksMultipleItem, RString & sError) static
References ASSERT, and WdmSyncIoctl().
Referenced by WinWdmFilter::CreatePin().
WdmGetPinPropertySimple()
static bool WdmGetPinPropertySimple (HANDLE hHandle, unsigned long iPinId, const GUID * pGuidPropertySet, unsigned long iProperty, void * pValue, unsigned long iInstanceSize, RString & sError) static
References WdmSyncIoctl().
Referenced by WinWdmFilter::Create(), and WinWdmFilter::CreatePin().
WdmGetPropertySimple()
static bool WdmGetPropertySimple (HANDLE hHandle, const GUID * pGuidPropertySet, unsigned long iProperty, void * pValue, unsigned long iValueSize, void * pInstance, unsigned long iInstanceSize, RString & sError) static
References WdmSyncIoctl().
Referenced by RageSoundDriver_WDMKS::GetPosition(), and WinWdmStream::Open().
WdmSetPropertySimple()
static bool WdmSetPropertySimple (HANDLE hHandle, const GUID * pGuidPropertySet, unsigned long iProperty, void * pValue, unsigned long iValueSize, void * instance, unsigned long iInstanceSize, RString & sError) static
References WdmSyncIoctl().
Referenced by WinWdmPin::SetState().
WdmSyncIoctl()
static bool WdmSyncIoctl (HANDLE hHandle, unsigned long ioctlNumber, void * pIn, unsigned long iInSize, void * pOut, unsigned long iOutSize, unsigned long * pBytesReturned, RString & sError) static
References ASSERT.
Referenced by WdmGetPinPropertyMulti(), WdmGetPinPropertySimple(), WdmGetPropertySimple(), and WdmSetPropertySimple().
Variable Documentation
DllKsUser
HMODULE DllKsUser = NULL static
Referenced by PaWinWdm_Initialize().
FunctionKsCreatePin
KSCREATEPIN* FunctionKsCreatePin = NULL static
Referenced by WinWdmPin::Instantiate(), and PaWinWdm_Initialize().