Etterna: RageSurfaceUtils_Dither.cpp File Reference
RageSurfaceUtils_Dither.cpp File Reference
#include "global.h"
#include "RageSurfaceUtils_Dither.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageUtil.h"
Macros
#define DitherMatDim 4
Functions
static uint8_t DitherPixel (int x, int y, int intensity, int conv)
static uint8_t EDDitherPixel (int x, int y, int intensity, int conv, int32_t &accumError)
Variables
static const int DitherMat [DitherMatDim][DitherMatDim]
static int DitherMatCalc [DitherMatDim][DitherMatDim]
Macro Definition Documentation
DitherMatDim
#define DitherMatDim 4
Referenced by DitherPixel(), and RageSurfaceUtils::OrderedDither().
Function Documentation
DitherPixel()
static uint8_t DitherPixel (int x, int y, int intensity, int conv) static
References DitherMatCalc, and DitherMatDim.
Referenced by RageSurfaceUtils::OrderedDither().
EDDitherPixel()
static uint8_t EDDitherPixel (int x, int y, int intensity, int conv, int32_t & accumError) static
References clamp, and CLAMP().
Referenced by RageSurfaceUtils::ErrorDiffusionDither().
Variable Documentation
DitherMat
const int DitherMat[DitherMatDim][DitherMatDim] static
Initial value:
= { { 0, 8, 2, 10 },
                                                           { 12, 4, 14, 6 },
                                                           { 3, 11, 1, 9 },
                                                           { 15, 7, 13, 5 } }
Referenced by RageSurfaceUtils::OrderedDither().
DitherMatCalc
int DitherMatCalc[DitherMatDim][DitherMatDim] static
Referenced by DitherPixel(), and RageSurfaceUtils::OrderedDither().