Etterna: RageThreads.cpp File Reference
RageThreads.cpp File Reference
#include "global.h"
#include "RageLog.h"
#include "RageThreads.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include <atomic>
#include <mutex>
#include <thread>
#include <set>
#include "arch/Threads/Threads.h"
Classes
struct ThreadSlot
struct ThreadSlot::ThreadCheckpoint
Macros
#define MAX_THREADS 128
#define CHECKPOINT_COUNT 5
Functions
static RageMutex & GetThreadSlotsLock ()
static int FindEmptyThreadSlot ()
static void InitThreads ()
static ThreadSlot * GetThreadSlotFromID (uint64_t iID)
static ThreadSlot * GetCurThreadSlot ()
static ThreadSlot * GetUnknownThreadSlot ()
static const char * GetCheckpointLog (int slotno, int lineno)
Variables
static ThreadSlot g_ThreadSlots [MAX_THREADS]
struct ThreadSlot * g_pUnknownThreadSlot = NULL
static bool g_LogCheckpoints = false
Macro Definition Documentation
CHECKPOINT_COUNT
#define CHECKPOINT_COUNT 5
Referenced by ThreadSlot::GetFormattedCheckpoint(), and Checkpoints::SetCheckpoint().
MAX_THREADS
#define MAX_THREADS 128
Referenced by RageThread::EnumThreadIDs(), FindEmptyThreadSlot(), and Checkpoints::GetLogs().
Function Documentation
FindEmptyThreadSlot()
static int FindEmptyThreadSlot () static
References GetThreadSlotsLock(), LockMut, ThreadSlot::m_bUsed, MAX_THREADS, and RageException::Throw().
Referenced by RageThread::Create(), InitThreads(), and RageThreadRegister::RageThreadRegister().
GetCheckpointLog()
static const char* GetCheckpointLog (int slotno, int lineno) static
References ThreadSlot::GetFormattedCheckpoint(), ThreadSlot::m_bUsed, and ThreadSlot::m_szThreadFormattedOutput.
Referenced by Checkpoints::GetLogs().
GetCurThreadSlot()
static ThreadSlot* GetCurThreadSlot () static
References RageThread::GetCurrentThreadID(), and GetThreadSlotFromID().
Referenced by Checkpoints::SetCheckpoint().
GetThreadSlotFromID()
static ThreadSlot* GetThreadSlotFromID (uint64_t iID) static
References InitThreads().
Referenced by GetCurThreadSlot(), RageThread::GetThreadNameByID(), RageMutex::Lock(), and RageSemaphore::Wait().
GetThreadSlotsLock()
static RageMutex& GetThreadSlotsLock () static
Referenced by RageThread::Create(), RageThread::EnumThreadIDs(), FindEmptyThreadSlot(), InitThreads(), RageMutex::Lock(), RageThreadRegister::RageThreadRegister(), RageThread::Wait(), and RageThreadRegister::~RageThreadRegister().
GetUnknownThreadSlot()
static ThreadSlot* GetUnknownThreadSlot () static
References g_pUnknownThreadSlot.
Referenced by Checkpoints::SetCheckpoint().
InitThreads()
static void InitThreads () static
References FindEmptyThreadSlot(), GetThreadSlotsLock(), LockMut, ThreadSlot::m_iID, ThreadSlot::m_szName, and ThreadSlot::m_szThreadFormattedOutput.
Referenced by RageThread::Create(), GetThreadSlotFromID(), and RageThreadRegister::RageThreadRegister().
Variable Documentation
g_LogCheckpoints
bool g_LogCheckpoints = false static
g_pUnknownThreadSlot
struct ThreadSlot* g_pUnknownThreadSlot = NULL
Referenced by GetUnknownThreadSlot().
g_ThreadSlots
ThreadSlot g_ThreadSlots[MAX_THREADS] static