Etterna: LunaHelpDisplay Class Reference
LunaHelpDisplay Class Reference
Allow Lua to have access to the HelpDisplay.
Public Member Functions
LunaHelpDisplay ()
Public Member Functions inherited from Luna< HelpDisplay >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int settips (T *p, lua_State *L)
static int SetTipsColonSeparated (T *p, lua_State *L)
static int gettips (T *p, lua_State *L)
static int SetSecsBetweenSwitches (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< HelpDisplay >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< HelpDisplay >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< HelpDisplay >
using T = HelpDisplay
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< HelpDisplay >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the HelpDisplay.
Constructor & Destructor Documentation
LunaHelpDisplay()
LunaHelpDisplay::LunaHelpDisplay () inline
References ADD_METHOD, gettips(), SetSecsBetweenSwitches(), settips(), and SetTipsColonSeparated().
Member Function Documentation
gettips()
static int LunaHelpDisplay::gettips (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and HelpDisplay::GetTips().
Referenced by LunaHelpDisplay().
SetSecsBetweenSwitches()
static int LunaHelpDisplay::SetSecsBetweenSwitches (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and HelpDisplay::SetSecsBetweenSwitches().
Referenced by LunaHelpDisplay().
settips()
static int LunaHelpDisplay::settips (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, LuaHelpers::ReadArrayFromTable(), FontCharAliases::ReplaceMarkers(), and HelpDisplay::SetTips().
Referenced by LunaHelpDisplay().
SetTipsColonSeparated()
static int LunaHelpDisplay::SetTipsColonSeparated (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, HelpDisplay::SetTips(), and split().
Referenced by LunaHelpDisplay().
The documentation for this class was generated from the following file:
HelpDisplay.cpp