Etterna: InputQueueCodeSet Class Reference
InputQueueCodeSet Class Reference
#include <CodeSet.h>
Public Member Functions
void Load (const RString &sType)
RString Input (const InputEventPlus &input) const
bool InputMessage (const InputEventPlus &input, Message &msg) const
Private Attributes
vector< InputQueueCode > m_aCodes
vector< RString > m_asCodeNames
Member Function Documentation
Input()
RString InputQueueCodeSet::Input (const InputEventPlus & input) const
References GameInput::controller, InputEventPlus::GameI, m_aCodes, and m_asCodeNames.
Referenced by InputMessage().
InputMessage()
bool InputQueueCodeSet::InputMessage (const InputEventPlus & input, Message & msg) const
References Input(), InputEventPlus::pn, Message::SetName(), and Message::SetParam().
Referenced by OptionsList::Input(), Screen::Input(), and ScreenGameplay::Input().
Load()
void InputQueueCodeSet::Load (const RString & sType)
References CODE, CODE_NAMES, InputQueueCode::Load(), m_aCodes, m_asCodeNames, and split().
Referenced by Screen::Init(), and OptionsList::Load().
Member Data Documentation
m_aCodes
vector<InputQueueCode> InputQueueCodeSet::m_aCodes private
Referenced by Input(), and Load().
m_asCodeNames
vector<RString> InputQueueCodeSet::m_asCodeNames private
Referenced by Input(), and Load().
The documentation for this class was generated from the following files:
CodeSet.h
CodeSet.cpp