Etterna: RageSoundReader_Vorbisfile Class Reference
RageSoundReader_Vorbisfile Class Reference
#include <RageSoundReader_Vorbisfile.h>
Public Member Functions
OpenResult Open (RageFileBasic *pFile) override
int GetLength () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
int GetNextSourceFrame () const override
RageSoundReader_Vorbisfile ()
~RageSoundReader_Vorbisfile () override
RageSoundReader_Vorbisfile * Copy () const override
Public Member Functions inherited from RageSoundReader_FileReader
float GetStreamToSourceRatio () const override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual int GetLength_Fast () const
virtual ~RageSoundReader ()=default
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
bool FillBuf ()
Private Attributes
OggVorbis_File * vf
bool eof
RString filename
int read_offset
unsigned channels
Additional Inherited Members
Public Types inherited from RageSoundReader_FileReader
enum OpenResult { OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT = 1, OPEN_FATAL_ERROR = 2 }
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Static Public Member Functions inherited from RageSoundReader_FileReader
static RageSoundReader_FileReader * OpenFile (const RString &filename, RString &error, bool *pPrebuffer=NULL)
Protected Member Functions inherited from RageSoundReader_FileReader
void SetError (const RString &sError) const
Protected Attributes inherited from RageSoundReader_FileReader
HiddenPtr< RageFileBasic > m_pFile
Constructor & Destructor Documentation
RageSoundReader_Vorbisfile()
RageSoundReader_Vorbisfile::RageSoundReader_Vorbisfile ()
References vf.
Referenced by Copy().
~RageSoundReader_Vorbisfile()
RageSoundReader_Vorbisfile::~RageSoundReader_Vorbisfile () override
References vf.
Member Function Documentation
Copy()
RageSoundReader_Vorbisfile * RageSoundReader_Vorbisfile::Copy () const override virtual
Implements RageSoundReader.
References RageFileBasic::Copy(), FAIL_M, RageSoundReader_FileReader::m_pFile, RageSoundReader_FileReader::OPEN_OK, RageSoundReader_Vorbisfile(), RageFileBasic::Seek(), and ssprintf().
FillBuf()
bool RageSoundReader_Vorbisfile::FillBuf () private
GetLength()
int RageSoundReader_Vorbisfile::GetLength () const override virtual
Implements RageSoundReader.
References RageException::Throw(), and vf.
GetNextSourceFrame()
int RageSoundReader_Vorbisfile::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References ASSERT, and vf.
GetNumChannels()
unsigned RageSoundReader_Vorbisfile::GetNumChannels () const inline override virtual
Implements RageSoundReader.
References channels.
GetSampleRate()
int RageSoundReader_Vorbisfile::GetSampleRate () const override virtual
Implements RageSoundReader.
References ASSERT, and vf.
Open()
RageSoundReader_FileReader::OpenResult RageSoundReader_Vorbisfile::Open (RageFileBasic * pFile) override virtual
Implements RageSoundReader_FileReader.
References channels, eof, RageSoundReader_FileReader::m_pFile, OggRageFile_close_func(), OggRageFile_read_func(), OggRageFile_seek_func(), OggRageFile_tell_func(), RageSoundReader_FileReader::OPEN_FATAL_ERROR, RageSoundReader_FileReader::OPEN_OK, RageSoundReader_FileReader::OPEN_UNKNOWN_FILE_FORMAT, ov_ssprintf(), read_offset, RageSoundReader_FileReader::SetError(), and vf.
Read()
int RageSoundReader_Vorbisfile::Read (float * pBuf, int iFrames) override virtual
Implements RageSoundReader.
References ASSERT, bytes_per_frame, channels, CHECKPOINT_M, RageSoundReader::END_OF_FILE, eof, f, filename, LOG, min(), read_offset, RageSoundReader::RSRERROR, RageSoundReader_FileReader::SetError(), ssprintf(), RageException::Throw(), RageLog::Trace(), and vf.
SetPosition()
int RageSoundReader_Vorbisfile::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References eof, ov_ssprintf(), read_offset, RageSoundReader_FileReader::SetError(), and vf.
Member Data Documentation
channels
unsigned RageSoundReader_Vorbisfile::channels private
Referenced by GetNumChannels(), Open(), and Read().
eof
bool RageSoundReader_Vorbisfile::eof private
Referenced by Open(), Read(), and SetPosition().
filename
RString RageSoundReader_Vorbisfile::filename private
Referenced by Read().
read_offset
int RageSoundReader_Vorbisfile::read_offset private
Referenced by Open(), Read(), and SetPosition().
vf
OggVorbis_File* RageSoundReader_Vorbisfile::vf private
Referenced by GetLength(), GetNextSourceFrame(), GetSampleRate(), Open(), RageSoundReader_Vorbisfile(), Read(), SetPosition(), and ~RageSoundReader_Vorbisfile().
The documentation for this class was generated from the following files:
RageSoundReader_Vorbisfile.h
RageSoundReader_Vorbisfile.cpp