Etterna: InputHandler_Linux_Event.cpp File Reference
InputHandler_Linux_Event.cpp File Reference
#include "InputHandler_Linux_Event.h"
#include "GamePreferences.h"
#include "LinuxInputManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "global.h"
#include <errno.h>
#include <linux/input.h>
#include <sys/stat.h>
#include <sys/types.h>
Classes
struct EventDevice
Functions
REGISTER_INPUT_HANDLER_CLASS2 (LinuxEvent, Linux_Event)
static RString BustypeToString (int iBus)
static bool EventDeviceExists (int iNum)
static bool BitIsSet (const uint8_t *pArray, uint32_t iBit)
Variables
static vector< EventDevice * > g_apEventDevices
Function Documentation
BitIsSet()
static bool BitIsSet (const uint8_t * pArray, uint32_t iBit) static
Referenced by EventDevice::Open().
BustypeToString()
static RString BustypeToString (int iBus) static
References ssprintf().
Referenced by EventDevice::Open().
EventDeviceExists()
static bool EventDeviceExists (int iNum) static
References ssprintf().
REGISTER_INPUT_HANDLER_CLASS2()
REGISTER_INPUT_HANDLER_CLASS2 (LinuxEvent , Linux_Event)
Variable Documentation
g_apEventDevices
vector<EventDevice*> g_apEventDevices static
Referenced by InputHandler_Linux_Event::GetDevicesAndDescriptions(), InputHandler_Linux_Event::InputHandler_Linux_Event(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Event::TryDevice(), and InputHandler_Linux_Event::~InputHandler_Linux_Event().