Etterna: BackgroundImpl::Layer Class Reference
BackgroundImpl::Layer Class Reference
Public Member Functions
Layer ()
void Unload ()
bool CreateBackground (const Song *pSong, const BackgroundDef &bd, Actor *pParent)
BackgroundDef CreateRandomBGA (const Song *pSong, const RString &sEffect, deque< BackgroundDef > &RandomBGAnimations, Actor *pParent)
int FindBGSegmentForBeat (float fBeat) const
void UpdateCurBGChange (const Song *pSong, float fLastMusicSeconds, float fCurrentTime, const map< RString, BackgroundTransition > &mapNameToTransition)
Public Attributes
map< BackgroundDef, Actor * > m_BGAnimations
vector< BackgroundChange > m_aBGChanges
int m_iCurBGChangeIndex
Actor * m_pCurrentBGA
Actor * m_pFadingBGA
Constructor & Destructor Documentation
Layer()
BackgroundImpl::Layer::Layer ()
References m_iCurBGChangeIndex, m_pCurrentBGA, and m_pFadingBGA.
Member Function Documentation
CreateBackground()
bool BackgroundImpl::Layer::CreateBackground (const Song * pSong, const BackgroundDef & bd, Actor * pParent)
References Actor::Actor(), ASSERT, DoesFileExist(), FT_Bitmap, FT_Directory, FT_Lua, FT_Model, FT_Movie, FT_Sprite, FT_Xml, BackgroundUtil::GetBackgroundEffects(), Song::GetBackgroundPath(), ThemeManager::GetBlankGraphicPath(), ActorUtil::GetFileType(), BackgroundUtil::GetGlobalBGAnimations(), BackgroundUtil::GetGlobalRandomMovies(), ThemeManager::GetPathG(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), Song::HasBackground(), BackgroundDef::m_sColor1, BackgroundDef::m_sColor2, BackgroundDef::m_sEffect, BackgroundDef::m_sFile1, BackgroundDef::m_sFile2, ActorUtil::MakeActor(), LuaHelpers::ReportScriptErrorFmt(), SBE_Centered, SBE_StretchNormal, SBE_UpperLeft, SONG_BACKGROUND_FILE, ssprintf(), and THEME.
Referenced by BackgroundImpl::LoadFromSong().
CreateRandomBGA()
BackgroundDef BackgroundImpl::Layer::CreateRandomBGA (const Song * pSong, const RString & sEffect, deque< BackgroundDef > & RandomBGAnimations, Actor * pParent)
References ASSERT, BGMODE_OFF, g_RandomBackgroundMode, GAMESTATE, ModsGroup< T >::GetCurrent(), SongOptions::m_bStaticBackground, BackgroundDef::m_sEffect, and GameState::m_SongOptions.
Referenced by BackgroundImpl::LoadFromRandom(), and BackgroundImpl::LoadFromSong().
FindBGSegmentForBeat()
int BackgroundImpl::Layer::FindBGSegmentForBeat (float fBeat) const
Unload()
void BackgroundImpl::Layer::Unload ()
References FOREACHM.
Referenced by BackgroundImpl::Unload().
UpdateCurBGChange()
void BackgroundImpl::Layer::UpdateCurBGChange (const Song * pSong, float fLastMusicSeconds, float fCurrentTime, const map< RString, BackgroundTransition > & mapNameToTransition)
References ASSERT, TimingData::GetBeatArgs::beat, BackgroundTransition::cmdLeaves, BackgroundTransition::cmdRoot, BackgroundDef::CreateNode(), TimingData::GetBeatArgs::elapsed_time, GAMESTATE, TimingData::GetBeatAndBPSFromElapsedTime(), ModsGroup< T >::GetCurrent(), XmlFileUtil::GetXML(), BackgroundChange::m_def, SongOptions::m_fMusicRate, BackgroundChange::m_fRate, BackgroundChange::m_fStartBeat, GameState::m_SongOptions, Song::m_SongTiming, BackgroundChange::m_sTransition, max(), GameState::MUSIC_SECONDS_INVALID, LuaHelpers::ReportScriptErrorFmt(), SAFE_DELETE, Trim(), and TimingData::WhereUAtBro().
Referenced by BackgroundImpl::Update().
Member Data Documentation
m_aBGChanges
vector<BackgroundChange> BackgroundImpl::Layer::m_aBGChanges
Referenced by BackgroundImpl::GetLoadedBackgroundChanges(), BackgroundImpl::LoadFromRandom(), and BackgroundImpl::LoadFromSong().
m_BGAnimations
map<BackgroundDef, Actor*> BackgroundImpl::Layer::m_BGAnimations
Referenced by BackgroundImpl::LoadFromSong().
m_iCurBGChangeIndex
int BackgroundImpl::Layer::m_iCurBGChangeIndex
Referenced by Layer().
m_pCurrentBGA
Actor* BackgroundImpl::Layer::m_pCurrentBGA
Referenced by BackgroundImpl::DrawPrimitives(), and Layer().
m_pFadingBGA
Actor* BackgroundImpl::Layer::m_pFadingBGA
Referenced by BackgroundImpl::DrawPrimitives(), and Layer().
The documentation for this class was generated from the following file:
Background.cpp