Etterna: RageBezier2D Class Reference
RageBezier2D Class Reference
#include <RageMath.h>
Public Member Functions
void SetFromBezier (float fC1X, float fC2X, float fC3X, float fC4X, float fC1Y, float fC2Y, float fC3Y, float fC4Y)
void Evaluate (float fT, float *pX, float *pY) const
float EvaluateYFromX (float fX) const
RageQuadratic & get_x ()
RageQuadratic & get_y ()
void PushSelf (lua_State *L)
Private Attributes
RageQuadratic m_X
RageQuadratic m_Y
Member Function Documentation
Evaluate()
void RageBezier2D::Evaluate (float fT, float * pX, float * pY) const
References RageQuadratic::Evaluate(), m_X, and m_Y.
Referenced by LunaRageBezier2D::evaluate().
EvaluateYFromX()
float RageBezier2D::EvaluateYFromX (float fX) const
References RageQuadratic::Evaluate(), f, RageQuadratic::GetBezierEnd(), RageQuadratic::GetBezierStart(), RageQuadratic::GetSlope(), m_X, m_Y, SCALE, and unlikely.
Referenced by LunaRageBezier2D::evaluate_y_from_x(), and InterpolateBezier2D::Tween().
get_x()
RageQuadratic& RageBezier2D::get_x () inline
References m_X.
Referenced by LunaRageBezier2D::get_x().
get_y()
RageQuadratic& RageBezier2D::get_y () inline
References m_Y.
Referenced by LunaRageBezier2D::get_y().
PushSelf()
void RageBezier2D::PushSelf (lua_State * L)
Referenced by LuaFunc_create_bezier().
SetFromBezier()
void RageBezier2D::SetFromBezier (float fC1X, float fC2X, float fC3X, float fC4X, float fC1Y, float fC2Y, float fC3Y, float fC4Y)
References m_X, m_Y, and RageQuadratic::SetFromBezier().
Referenced by ITween::CreateFromStack(), and LunaRageBezier2D::set_from_bezier().
Member Data Documentation
m_X
RageQuadratic RageBezier2D::m_X private
Referenced by Evaluate(), EvaluateYFromX(), get_x(), and SetFromBezier().
m_Y
RageQuadratic RageBezier2D::m_Y private
Referenced by Evaluate(), EvaluateYFromX(), get_y(), and SetFromBezier().
The documentation for this class was generated from the following files:
RageMath.h
RageMath.cpp