Etterna: DebugLineFillProfileStats Class Reference
DebugLineFillProfileStats Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineFillProfileStats::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), FillProfileStats(), g_ProfileSlot, ProfileManager::GetProfile(), and PROFILEMAN.
GetDisplayTitle()
RString DebugLineFillProfileStats::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References FILL_PROFILE_STATS, and LocalizedString::GetValue().
GetDisplayValue()
RString DebugLineFillProfileStats::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPageName()
RString DebugLineFillProfileStats::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineFillProfileStats::IsEnabled () inline override private virtual
Implements IDebugLine.
References IsSelectProfilePersistent().
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp