Etterna: XMLProfile Class Reference
XMLProfile Class Reference
#include <XMLProfile.h>
Public Member Functions
void LoadStatsXmlForConversion ()
ProfileLoadResult LoadEttFromDir (RString dir)
ProfileLoadResult LoadStatsFromDir (RString dir, bool require_signature)
bool SaveStatsXmlToDir (RString sDir, bool bSignData, const Profile *profile)
bool SaveEttXmlToDir (RString sDir, const Profile *profile) const
void SetLoadingProfile (Profile *p)
Static Public Member Functions
static void MoveBackupToDir (const RString &sFromDir, const RString &sToDir)
Private Member Functions
ProfileLoadResult LoadStatsXmlFromNode (const XNode *pNode, bool bIgnoreEditable=true)
ProfileLoadResult LoadEttXmlFromNode (const XNode *pNode)
void LoadEttGeneralDataFromNode (const XNode *pNode)
void LoadEttScoresFromNode (const XNode *pNode)
void LoadFavoritesFromNode (const XNode *pNode)
void LoadPermaMirrorFromNode (const XNode *pNode)
void LoadScoreGoalsFromNode (const XNode *pNode)
void LoadPlaylistsFromNode (const XNode *pNode)
void LoadGeneralDataFromNode (const XNode *pNode)
void LoadSongScoresFromNode (const XNode *pNode)
void LoadCategoryScoresFromNode (const XNode *pNode)
void LoadScreenshotDataFromNode (const XNode *pNode)
XNode * SaveEttGeneralDataCreateNode (const Profile *profile) const
XNode * SaveEttScoresCreateNode (const Profile *profile) const
XNode * SaveEttXmlCreateNode (const Profile *profile) const
XNode * SaveFavoritesCreateNode (const Profile *profile) const
XNode * SavePermaMirrorCreateNode (const Profile *profile) const
XNode * SaveScoreGoalsCreateNode (const Profile *profile) const
XNode * SavePlaylistsCreateNode (const Profile *profile) const
XNode * SaveStatsXmlCreateNode (const Profile *profile) const
XNode * SaveGeneralDataCreateNode (const Profile *profile) const
XNode * SaveSongScoresCreateNode (const Profile *profile) const
XNode * SaveCategoryScoresCreateNode (const Profile *profile) const
XNode * SaveScreenshotDataCreateNode (const Profile *profile) const
XNode * SaveCoinDataCreateNode (const Profile *profile) const
Private Attributes
Profile * loadingProfile
RString profiledir
Member Function Documentation
LoadCategoryScoresFromNode()
void XMLProfile::LoadCategoryScoresFromNode (const XNode * pNode) private
References ASSERT, CHECKPOINT_M, FOREACH_CONST_Child, GAMEMAN, Profile::GetCategoryHighScoreList(), XNode::GetChild(), XNode::GetName(), HighScoreList::LoadFromNode(), loadingProfile, RankingCategory_Invalid, StepsType_Invalid, StringToRankingCategory(), GameManager::StringToStepsType(), WARN_AND_CONTINUE, and WARN_AND_CONTINUE_M.
LoadEttFromDir()
ProfileLoadResult XMLProfile::LoadEttFromDir (RString dir)
References ETT_XML, FILEMAN, ProfileManager::GetStatsPrefix(), GunzipFile(), IsAFile(), Profile::IsEtternaProfile, LoadEttXmlFromNode(), XmlFileUtil::LoadFromFileShowErrors(), loadingProfile, LOG, RageFileManager::Open(), profiledir, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, PROFILEMAN, RageFile::READ, STATS_XML_GZ, and RageLog::Trace().
Referenced by Profile::LoadAllFromDir().
LoadEttGeneralDataFromNode()
void XMLProfile::LoadEttGeneralDataFromNode (const XNode * pNode) private
References ASSERT, CHECKPOINT_M, LuaHelpers::CreateTableFromXNode(), FOREACH_CONST_Child, FOREACH_ENUM, DateTime::FromString(), GAMEMAN, LuaManager::Get(), XNode::GetChild(), XNode::GetChildValue(), Profile::GetGuid(), XNode::GetName(), L, SongID::LoadFromNode(), loadingProfile, LUA, Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iCurrentCombo, Profile::m_iNumToasties, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastDifficulty, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sDisplayName, Profile::m_sLastUsedHighScoreName, Profile::m_SortOrder, Profile::m_UserTable, LuaManager::Release(), LuaReference::SetFromStack(), SkillsetToString(), StringToDifficulty(), StringToSortOrder(), and GameManager::StringToStepsType().
Referenced by LoadEttXmlFromNode().
LoadEttScoresFromNode()
void XMLProfile::LoadEttScoresFromNode (const XNode * pNode) private
References CHECKPOINT_M, ScoreManager::LoadFromNode(), loadingProfile, Profile::m_sProfileID, and SCOREMAN.
Referenced by LoadEttXmlFromNode().
LoadEttXmlFromNode()
ProfileLoadResult XMLProfile::LoadEttXmlFromNode (const XNode * pNode) private
References XNode::GetChild(), XNode::GetName(), LoadEttGeneralDataFromNode(), LoadEttScoresFromNode(), LoadFavoritesFromNode(), LoadPermaMirrorFromNode(), LoadPlaylistsFromNode(), LoadScoreGoalsFromNode(), ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, and WARN_M.
Referenced by LoadEttFromDir().
LoadFavoritesFromNode()
void XMLProfile::LoadFavoritesFromNode (const XNode * pNode) private
References Profile::allplaylists, CHECKPOINT_M, Profile::FavoritedCharts, FOREACH_CONST_Child, loadingProfile, SongManager::MakePlaylistFromFavorites(), SongManager::ReconcileBustedKeys(), SongManager::SetFavoritedStatus(), and SONGMAN.
Referenced by LoadEttXmlFromNode().
LoadGeneralDataFromNode()
void XMLProfile::LoadGeneralDataFromNode (const XNode * pNode) private
References ASSERT, LuaHelpers::CreateTableFromXNode(), DifficultyToString(), Profile::FavoritedCharts, FOREACH_CONST_Child, FOREACH_ENUM, FOREACHS, DateTime::FromString(), GAMEMAN, LuaManager::Get(), XNode::GetChild(), XNode::GetChildValue(), XNode::GetName(), GradeToString(), StyleID::IsValid(), L, StyleID::LoadFromNode(), SongID::LoadFromNode(), loadingProfile, LUA, Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iCurrentCombo, Profile::m_iNumExtraStagesFailed, Profile::m_iNumExtraStagesPassed, Profile::m_iNumSongsPlayedByDifficulty, Profile::m_iNumSongsPlayedByMeter, Profile::m_iNumSongsPlayedByPlayMode, Profile::m_iNumSongsPlayedByStyle, Profile::m_iNumStagesPassedByGrade, Profile::m_iNumStagesPassedByPlayMode, Profile::m_iNumToasties, Profile::m_iNumTotalSongsPlayed, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastDifficulty, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sDisplayName, Profile::m_sGuid, Profile::m_sLastPlayedMachineGuid, Profile::m_sLastUsedHighScoreName, Profile::m_SortOrder, Profile::m_UserTable, MAX_METER, PlayModeToString(), LuaManager::Release(), SongManager::SetFavoritedStatus(), LuaReference::SetFromStack(), SkillsetToString(), SONGMAN, ssprintf(), StringToDifficulty(), StringToSortOrder(), GameManager::StringToStepsType(), and WARN_AND_CONTINUE.
LoadPermaMirrorFromNode()
void XMLProfile::LoadPermaMirrorFromNode (const XNode * pNode) private
References CHECKPOINT_M, FOREACH_CONST_Child, loadingProfile, Profile::PermaMirrorCharts, SongManager::ReconcileBustedKeys(), SongManager::SetPermaMirroredStatus(), and SONGMAN.
Referenced by LoadEttXmlFromNode().
LoadPlaylistsFromNode()
void XMLProfile::LoadPlaylistsFromNode (const XNode * pNode) private
References SongManager::activeplaylist, Profile::allplaylists, CHECKPOINT_M, FOREACH_CONST_Child, Playlist::LoadFromNode(), loadingProfile, Playlist::name, and SONGMAN.
Referenced by LoadEttXmlFromNode().
LoadScoreGoalsFromNode()
void XMLProfile::LoadScoreGoalsFromNode (const XNode * pNode) private
References CHECKPOINT_M, FOREACH_CONST_Child, Profile::goalmap, loadingProfile, SongManager::ReconcileBustedKeys(), and SONGMAN.
Referenced by LoadEttXmlFromNode().
LoadScreenshotDataFromNode()
void XMLProfile::LoadScreenshotDataFromNode (const XNode * pNode) private
References ASSERT, CHECKPOINT_M, FOREACH_CONST_Child, XNode::GetName(), Screenshot::LoadFromNode(), loadingProfile, Profile::m_vScreenshots, and WARN_AND_CONTINUE_M.
LoadSongScoresFromNode()
void XMLProfile::LoadSongScoresFromNode (const XNode * pNode) private
References ASSERT, CHECKPOINT_M, FOREACH_CONST_Child, XNode::GetChild(), XNode::GetName(), StepsID::IsValid(), HighScoreList::LoadFromNode(), StepsID::LoadFromNode(), SongID::LoadFromNode(), loadingProfile, Profile::m_SongHighScores, and WARN_AND_CONTINUE.
Referenced by LoadStatsXmlForConversion().
LoadStatsFromDir()
ProfileLoadResult XMLProfile::LoadStatsFromDir (RString dir, bool require_signature)
References DONT_SHARE_SIG, FILEMAN, ProfileManager::GetStatsPrefix(), GunzipFile(), IsAFile(), XmlFileUtil::LoadFromFileShowErrors(), LoadStatsXmlFromNode(), LOG, RageFileManager::Open(), profiledir, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, PROFILEMAN, RageFile::READ, LuaHelpers::ReportScriptErrorFmt(), SIGNATURE_APPEND, STATS_XML, STATS_XML_GZ, RageLog::Trace(), and CryptManager::VerifyFileWithFile().
Referenced by Profile::LoadAllFromDir(), and Profile::LoadStatsFromDir().
LoadStatsXmlForConversion()
void XMLProfile::LoadStatsXmlForConversion ()
References FILEMAN, XNode::GetChild(), GunzipFile(), IsAFile(), XmlFileUtil::LoadFromFileShowErrors(), LoadSongScoresFromNode(), RageFileManager::Open(), profiledir, RageFile::READ, STATS_XML, and STATS_XML_GZ.
Referenced by Profile::ImportScoresToEtterna().
LoadStatsXmlFromNode()
ProfileLoadResult XMLProfile::LoadStatsXmlFromNode (const XNode * pNode, bool bIgnoreEditable = true) private
References XNode::GetName(), LOAD_NODE, loadingProfile, Profile::m_sCharacterID, Profile::m_sDisplayName, Profile::m_sLastUsedHighScoreName, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, and WARN_M.
Referenced by LoadStatsFromDir().
MoveBackupToDir()
void XMLProfile::MoveBackupToDir (const RString & sFromDir, const RString & sToDir) static
References FILEMAN, RageFileManager::IsAFile(), RageFileManager::Move(), and SIGNATURE_APPEND.
Referenced by Profile::MoveBackupToDir().
SaveCategoryScoresCreateNode()
XNode * XMLProfile::SaveCategoryScoresCreateNode (const Profile * profile) const private
References XNode::AppendAttr(), XNode::AppendChild(), ASSERT, CHECKPOINT_M, HighScoreList::CreateNode(), FOREACH_ENUM, GAMEMAN, Profile::GetCategoryHighScoreList(), Profile::GetCategoryNumTimesPlayed(), HighScoreList::GetNumTimesPlayed(), GameManager::GetStepsTypeInfo(), RankingCategoryToString(), and StepsTypeInfo::szName.
Referenced by SaveStatsXmlCreateNode().
SaveCoinDataCreateNode()
XNode* XMLProfile::SaveCoinDataCreateNode (const Profile * profile) const private
SaveEttGeneralDataCreateNode()
XNode * XMLProfile::SaveEttGeneralDataCreateNode (const Profile * profile) const private
References XNode::AppendChild(), CHECKPOINT_M, SongID::CreateNode(), Difficulty_Invalid, DifficultyToString(), FOREACH_ENUM, FOREACHM_CONST, GAMEMAN, LuaManager::Get(), Profile::GetDisplayNameOrHighScoreName(), GameManager::GetStepsTypeInfo(), DateTime::GetString(), LuaReference::IsSet(), L, LUA, Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iNumStagesPassedByPlayMode, Profile::m_iNumToasties, Profile::m_iNumTotalSongsPlayed, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastDifficulty, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sGuid, Profile::m_sLastPlayedMachineGuid, XNode::m_sName, Profile::m_SortOrder, Profile::m_UserTable, PlayModeToString(), LuaReference::PushSelf(), LuaManager::Release(), SkillsetToString(), SortOrderToString(), StepsType_Invalid, StepsTypeInfo::szName, and XmlFileUtil::XNodeFromTable().
Referenced by SaveEttXmlCreateNode().
SaveEttScoresCreateNode()
XNode * XMLProfile::SaveEttScoresCreateNode (const Profile * profile) const private
References ASSERT, CHECKPOINT_M, ScoreManager::CreateNode(), Profile::m_sProfileID, SCOREMAN, and ScoreManager::SetAllTopScores().
Referenced by SaveEttXmlCreateNode().
SaveEttXmlCreateNode()
XNode * XMLProfile::SaveEttXmlCreateNode (const Profile * profile) const private
References Profile::allplaylists, XNode::AppendChild(), Profile::FavoritedCharts, Profile::goalmap, Profile::PermaMirrorCharts, SaveEttGeneralDataCreateNode(), SaveEttScoresCreateNode(), SaveFavoritesCreateNode(), SavePermaMirrorCreateNode(), SavePlaylistsCreateNode(), and SaveScoreGoalsCreateNode().
Referenced by SaveEttXmlToDir().
SaveEttXmlToDir()
bool XMLProfile::SaveEttXmlToDir (RString sDir, const Profile * profile) const
References ETT_XML, f, FILEMAN, RageFileObjGzip::Finish(), g_bProfileDataCompress, RageFile::GetError(), ProfileManager::GetStatsPrefix(), RageFileManager::IsAFile(), LOG, RageFile::Open(), PROFILEMAN, RageFileManager::Remove(), LuaHelpers::ReportScriptErrorFmt(), SaveEttXmlCreateNode(), XmlFileUtil::SaveToFile(), RageFileObjGzip::Start(), RageLog::Trace(), and RageFile::WRITE.
Referenced by Profile::SaveAllToDir().
SaveFavoritesCreateNode()
XNode * XMLProfile::SaveFavoritesCreateNode (const Profile * profile) const private
References XNode::AppendChild(), CHECKPOINT_M, Profile::FavoritedCharts, and FOREACHS_CONST.
Referenced by SaveEttXmlCreateNode().
SaveGeneralDataCreateNode()
XNode * XMLProfile::SaveGeneralDataCreateNode (const Profile * profile) const private
References XNode::AppendAttr(), XNode::AppendChild(), StyleID::CreateNode(), SongID::CreateNode(), Difficulty_Invalid, DifficultyToString(), Profile::FavoritedCharts, FOREACH_ENUM, FOREACHM_CONST, FOREACHS_CONST, GAMEMAN, LuaManager::Get(), Profile::GetDisplayNameOrHighScoreName(), GameManager::GetStepsTypeInfo(), DateTime::GetString(), GradeToString(), LuaReference::IsSet(), L, LUA, Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iCurrentCombo, Profile::m_iNumExtraStagesFailed, Profile::m_iNumExtraStagesPassed, Profile::m_iNumSongsPlayedByDifficulty, Profile::m_iNumSongsPlayedByMeter, Profile::m_iNumSongsPlayedByPlayMode, Profile::m_iNumSongsPlayedByStyle, Profile::m_iNumStagesPassedByGrade, Profile::m_iNumStagesPassedByPlayMode, Profile::m_iNumToasties, Profile::m_iNumTotalSongsPlayed, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sGuid, Profile::m_sLastPlayedMachineGuid, Profile::m_sLastUsedHighScoreName, XNode::m_sName, Profile::m_SortOrder, Profile::m_UserTable, MAX_METER, PlayModeToString(), LuaReference::PushSelf(), LuaManager::Release(), SkillsetToString(), SortOrderToString(), ssprintf(), StepsType_Invalid, StepsTypeInfo::szName, XNode::TEXT_ATTRIBUTE, and XmlFileUtil::XNodeFromTable().
Referenced by SaveStatsXmlCreateNode().
SavePermaMirrorCreateNode()
XNode * XMLProfile::SavePermaMirrorCreateNode (const Profile * profile) const private
References XNode::AppendChild(), CHECKPOINT_M, FOREACHS_CONST, and Profile::PermaMirrorCharts.
Referenced by SaveEttXmlCreateNode().
SavePlaylistsCreateNode()
XNode * XMLProfile::SavePlaylistsCreateNode (const Profile * profile) const private
References Profile::allplaylists, XNode::AppendChild(), CHECKPOINT_M, and FOREACHM_CONST.
Referenced by SaveEttXmlCreateNode().
SaveScoreGoalsCreateNode()
XNode * XMLProfile::SaveScoreGoalsCreateNode (const Profile * profile) const private
References XNode::AppendChild(), CHECKPOINT_M, GoalsForChart::CreateNode(), FOREACHUM_CONST, and Profile::goalmap.
Referenced by SaveEttXmlCreateNode().
SaveScreenshotDataCreateNode()
XNode * XMLProfile::SaveScreenshotDataCreateNode (const Profile * profile) const private
References XNode::AppendChild(), ASSERT, CHECKPOINT_M, FOREACH_CONST, and Profile::m_vScreenshots.
Referenced by SaveStatsXmlCreateNode().
SaveSongScoresCreateNode()
XNode * XMLProfile::SaveSongScoresCreateNode (const Profile * profile) const private
References XNode::AppendChild(), ASSERT, CHECKPOINT_M, HighScoreList::CreateNode(), StepsID::CreateNode(), SongID::CreateNode(), FOREACHM_CONST, HighScoreList::GetNumTimesPlayed(), Profile::GetSongNumTimesPlayed(), Profile::HighScoresForASteps::hsl, Profile::m_SongHighScores, and Profile::HighScoresForASong::m_StepsHighScores.
Referenced by SaveStatsXmlCreateNode().
SaveStatsXmlCreateNode()
XNode * XMLProfile::SaveStatsXmlCreateNode (const Profile * profile) const private
References XNode::AppendChild(), SaveCategoryScoresCreateNode(), SaveGeneralDataCreateNode(), SaveScreenshotDataCreateNode(), and SaveSongScoresCreateNode().
Referenced by SaveStatsXmlToDir().
SaveStatsXmlToDir()
bool XMLProfile::SaveStatsXmlToDir (RString sDir, bool bSignData, const Profile * profile)
References DONT_SHARE_SIG, f, FILEMAN, RageFileObjGzip::Finish(), g_bProfileDataCompress, RageFile::GetError(), ProfileManager::GetStatsPrefix(), RageFileManager::IsAFile(), LOG, RageFile::Open(), PROFILEMAN, RageFileManager::Remove(), LuaHelpers::ReportScriptErrorFmt(), SaveStatsXmlCreateNode(), XmlFileUtil::SaveToFile(), SIGNATURE_APPEND, CryptManager::SignFileToFile(), RageFileObjGzip::Start(), STATS_XML, STATS_XML_GZ, RageLog::Trace(), and RageFile::WRITE.
SetLoadingProfile()
void XMLProfile::SetLoadingProfile (Profile * p) inline
References loadingProfile.
Referenced by Profile::LoadAllFromDir().
Member Data Documentation
loadingProfile
Profile* XMLProfile::loadingProfile private
Referenced by LoadCategoryScoresFromNode(), LoadEttFromDir(), LoadEttGeneralDataFromNode(), LoadEttScoresFromNode(), LoadFavoritesFromNode(), LoadGeneralDataFromNode(), LoadPermaMirrorFromNode(), LoadPlaylistsFromNode(), LoadScoreGoalsFromNode(), LoadScreenshotDataFromNode(), LoadSongScoresFromNode(), LoadStatsXmlFromNode(), and SetLoadingProfile().
profiledir
RString XMLProfile::profiledir private
Referenced by LoadEttFromDir(), LoadStatsFromDir(), and LoadStatsXmlForConversion().
The documentation for this class was generated from the following files:
XMLProfile.h
XMLProfile.cpp