Etterna: LunaSteps Class Reference
LunaSteps Class Reference
Allow Lua to have access to the Steps.
Public Member Functions
LunaSteps ()
Public Member Functions inherited from Luna< Steps >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int HasSignificantTimingChanges (T *p, lua_State *L)
static int HasAttacks (T *p, lua_State *L)
static int GetRadarValues (T *p, lua_State *L)
static int GetRelevantRadars (T *p, lua_State *L)
static int GetTimingData (T *p, lua_State *L)
static int GetHash (T *p, lua_State *L)
static int GetChartName (T *p, lua_State *L)
static int GetDisplayBpms (T *p, lua_State *L)
static int IsDisplayBpmSecret (T *p, lua_State *L)
static int IsDisplayBpmConstant (T *p, lua_State *L)
static int IsDisplayBpmRandom (T *p, lua_State *L)
static int GetDisplayBPMType (T *p, lua_State *L)
static int GetChartKey (T *p, lua_State *L)
static int GetMSD (T *p, lua_State *L)
static int GetRelevantSkillsetsByMSDRank (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Steps >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Steps >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Steps >
using T = Steps
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Steps >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Steps.
Constructor & Destructor Documentation
LunaSteps()
LunaSteps::LunaSteps () inline
References ADD_METHOD, GetChartKey(), GetChartName(), GetDisplayBpms(), GetDisplayBPMType(), GetHash(), GetMSD(), GetRadarValues(), GetRelevantRadars(), GetRelevantSkillsetsByMSDRank(), GetTimingData(), HasAttacks(), HasSignificantTimingChanges(), IsDisplayBpmConstant(), IsDisplayBpmRandom(), and IsDisplayBpmSecret().
Member Function Documentation
GetChartKey()
static int LunaSteps::GetChartKey (T * p, lua_State * L) inline static
References Steps::GetChartKey().
Referenced by LunaSteps().
GetChartName()
static int LunaSteps::GetChartName (T * p, lua_State * L) inline static
References Steps::GetChartName().
Referenced by LunaSteps().
GetDisplayBpms()
static int LunaSteps::GetDisplayBpms (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), Steps::GetDisplayBpms(), DisplayBpms::GetMax(), and DisplayBpms::GetMin().
Referenced by LunaSteps().
GetDisplayBPMType()
static int LunaSteps::GetDisplayBPMType (T * p, lua_State * L) inline static
References LuaHelpers::Push().
Referenced by LunaSteps().
GetHash()
static int LunaSteps::GetHash (T * p, lua_State * L) inline static
References Steps::GetHash().
Referenced by LunaSteps().
GetMSD()
static int LunaSteps::GetMSD (T * p, lua_State * L) inline static
References CLAMP(), f, FArg, Steps::GetMSD(), and IArg.
Referenced by LunaSteps().
GetRadarValues()
static int LunaSteps::GetRadarValues (T * p, lua_State * L) inline static
References Steps::GetRadarValues(), L, PLAYER_1, and RadarValues::PushSelf().
Referenced by LunaSteps().
GetRelevantRadars()
static int LunaSteps::GetRelevantRadars (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and Steps::GetRadarValues().
Referenced by LunaSteps().
GetRelevantSkillsetsByMSDRank()
static int LunaSteps::GetRelevantSkillsetsByMSDRank (T * p, lua_State * L) inline static
References CLAMP(), f, FArg, FOREACHM, IArg, NUM_Skillset, Skillset_Invalid, SkillsetToString(), and Steps::SortSkillsetsAtRate().
Referenced by LunaSteps().
GetTimingData()
static int LunaSteps::GetTimingData (T * p, lua_State * L) inline static
References Steps::GetTimingData(), and TimingData::PushSelf().
Referenced by LunaSteps().
HasAttacks()
static int LunaSteps::HasAttacks (T * p, lua_State * L) inline static
Referenced by LunaSteps().
HasSignificantTimingChanges()
static int LunaSteps::HasSignificantTimingChanges (T * p, lua_State * L) inline static
Referenced by LunaSteps().
IsDisplayBpmConstant()
static int LunaSteps::IsDisplayBpmConstant (T * p, lua_State * L) inline static
References DisplayBpms::BpmIsConstant(), and Steps::GetDisplayBpms().
Referenced by LunaSteps().
IsDisplayBpmRandom()
static int LunaSteps::IsDisplayBpmRandom (T * p, lua_State * L) inline static
References DISPLAY_BPM_RANDOM, and Steps::GetDisplayBPM().
Referenced by LunaSteps().
IsDisplayBpmSecret()
static int LunaSteps::IsDisplayBpmSecret (T * p, lua_State * L) inline static
References Steps::GetDisplayBpms(), and DisplayBpms::IsSecret().
Referenced by LunaSteps().
The documentation for this class was generated from the following file:
Steps.cpp