Etterna: DebugLineAssist Class Reference
DebugLineAssist Class Reference
Private Member Functions
RString GetDisplayTitle () override
Type GetType () const override
RString GetDisplayValue () override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineAssist::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References ASSERT, DEVICE_KEYBOARD, IDebugLine::DoAndLog(), GAMESTATE, GameState::GetMasterPlayerNumber(), ModsGroup< T >::GetSong(), INPUTFILTER, InputFilter::IsBeingPressed(), KEY_LSHIFT, SongOptions::m_bAssistClap, SongOptions::m_bAssistMetronome, GameState::m_SongOptions, ModsLevel_Preferred, PLAYER_INVALID, and SO_GROUP_ASSIGN.
GetDisplayTitle()
RString DebugLineAssist::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References ASSIST, and LocalizedString::GetValue().
GetDisplayValue()
RString DebugLineAssist::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References GAMESTATE, SongOptions::GetLocalizedString(), ModsGroup< T >::GetSong(), LocalizedString::GetValue(), SongOptions::m_bAssistClap, SongOptions::m_bAssistMetronome, GameState::m_SongOptions, and OFF.
GetType()
Type DebugLineAssist::GetType () const inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::gameplay_only.
IsEnabled()
bool DebugLineAssist::IsEnabled () inline override private virtual
Implements IDebugLine.
References GAMESTATE, ModsGroup< T >::GetSong(), SongOptions::m_bAssistClap, SongOptions::m_bAssistMetronome, and GameState::m_SongOptions.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp