Etterna: WavReaderPCM Struct Reference
WavReaderPCM Struct Reference
Public Member Functions
WavReaderPCM (RageFileBasic &f, const RageSoundReader_WAV::WavData &data)
bool Init () override
int Read (float *buf, int iFrames) override
int GetLength () const override
int SetPosition (int iFrame) override
int GetNextSourceFrame () const override
Public Member Functions inherited from WavReader
WavReader (RageFileBasic &f, const RageSoundReader_WAV::WavData &data)
virtual ~WavReader ()=default
RString GetError () const
Additional Inherited Members
Protected Attributes inherited from WavReader
RageFileBasic & m_File
const RageSoundReader_WAV::WavData & m_WavData
RString m_sError
Constructor & Destructor Documentation
WavReaderPCM()
WavReaderPCM::WavReaderPCM (RageFileBasic & f, const RageSoundReader_WAV::WavData & data) inline
Member Function Documentation
GetLength()
int WavReaderPCM::GetLength () const inline override virtual
Implements WavReader.
References RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkSize, RageSoundReader_WAV::WavData::m_iSampleRate, and WavReader::m_WavData.
GetNextSourceFrame()
int WavReaderPCM::GetNextSourceFrame () const inline override virtual
Implements WavReader.
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, WavReader::m_WavData, and RageFileBasic::Tell().
Init()
bool WavReaderPCM::Init () inline override virtual
Implements WavReader.
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iFormatTag, WavReader::m_sError, WavReader::m_WavData, QuantizeUp(), RageFileBasic::Seek(), and ssprintf().
Read()
int WavReaderPCM::Read (float * buf, int iFrames) inline override virtual
Implements WavReader.
References RageSoundReader::END_OF_FILE, WavReader::m_File, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, RageSoundReader_WAV::WavData::m_iFormatTag, WavReader::m_WavData, min(), QuantizeUp(), RageFileBasic::Read(), and RageFileBasic::Tell().
SetPosition()
int WavReaderPCM::SetPosition (int iFrame) inline override virtual
Implements WavReader.
References WavReader::m_File, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, WavReader::m_WavData, and RageFileBasic::Seek().
The documentation for this struct was generated from the following file:
RageSoundReader_WAV.cpp