Etterna: DSound Class Reference
DSound Class Reference
#include <DSoundHelpers.h>
Public Member Functions
IDirectSound * GetDS () const
bool IsEmulated () const
DSound ()
~DSound ()
RString Init ()
Private Member Functions
void SetPrimaryBufferMode ()
Static Private Member Functions
static BOOL CALLBACK EnumCallback (LPGUID lpGuid, LPCSTR lpcstrDescription, LPCSTR lpcstrModule, LPVOID lpContext)
Private Attributes
IDirectSound * m_pDS
Constructor & Destructor Documentation
DSound()
DSound::DSound ()
References FAILED, m_pDS, and RageException::Throw().
~DSound()
DSound::~DSound ()
References m_pDS.
Member Function Documentation
EnumCallback()
BOOL CALLBACK DSound::EnumCallback (LPGUID lpGuid, LPCSTR lpcstrDescription, LPCSTR lpcstrModule, LPVOID lpContext) static private
References RageLog::Info(), LOG, and ssprintf().
Referenced by Init().
GetDS()
IDirectSound* DSound::GetDS () const inline
References m_pDS.
Referenced by DSoundBuf::Init(), and SetPrimaryBufferMode().
Init()
RString DSound::Init ()
References EnumCallback(), FAILED, RageLog::Info(), LOG, m_pDS, SetPrimaryBufferMode(), and RageLog::Warn().
Referenced by RageSoundDriver_DSound_Software::Init().
IsEmulated()
bool DSound::IsEmulated () const
References FAILED, LOG, m_pDS, and RageLog::Warn().
Referenced by RageSoundDriver_DSound_Software::Init().
SetPrimaryBufferMode()
void DSound::SetPrimaryBufferMode () private
References FAILED, GetDS(), LOG, and RageLog::Warn().
Referenced by Init().
Member Data Documentation
m_pDS
IDirectSound* DSound::m_pDS private
Referenced by DSound(), GetDS(), Init(), IsEmulated(), and ~DSound().
The documentation for this class was generated from the following files:
DSoundHelpers.h
DSoundHelpers.cpp