Etterna: RageFile Class Reference
RageFile Class Reference
High-level file access.
#include <RageFile.h>
Public Types
enum { READ = 0x1, WRITE = 0x2, STREAMED = 0x4, SLOW_FLUSH = 0x8 }
Public Member Functions
RageFile ()
~RageFile () override
RageFile (const RageFile &cpy)
RageFile * Copy () const override
const RString & GetRealPath () const
RString GetPath () const
bool Open (const RString &path, int mode=READ)
void Close ()
bool IsOpen () const
int GetMode () const
bool AtEOF () const override
RString GetError () const override
void ClearError () override
int Tell () const override
int Seek (int offset) override
int GetFileSize () const override
int GetFD () override
int Read (void *buffer, size_t bytes) override
int Read (RString &buffer, int bytes=-1) override
int Write (const void *buffer, size_t bytes) override
int Write (const RString &string) override
int Flush () override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Seek (int offset, int whence) override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
virtual void PushSelf (lua_State *L)
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
virtual RString GetDisplayPath () const
Private Member Functions
void SetError (const RString &err)
RageFile & operator= (const RageFile &rhs)
Private Attributes
RageFileBasic * m_File
RString m_Path
RString m_sError
int m_Mode
Detailed Description
High-level file access.
This is the high-level interface, which interfaces with RageFileObj implementations and RageFileManager.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
READ
WRITE
STREAMED
SLOW_FLUSH
Constructor & Destructor Documentation
RageFile() [1/2]
RageFile::RageFile ()
References m_File.
Referenced by Copy().
~RageFile()
RageFile::~RageFile () inline override
References Close().
RageFile() [2/2]
RageFile::RageFile (const RageFile & cpy)
References RageFileBasic::Copy(), m_File, m_Mode, and m_Path.
Member Function Documentation
AtEOF()
bool RageFile::AtEOF () const override virtual
Implements RageFileBasic.
References ASSERT_READ, RageFileBasic::AtEOF(), and m_File.
Referenced by LunaRageFile::AtEOF(), BMSChart::Load(), and BackgroundLoader::LoadThread().
ClearError()
void RageFile::ClearError () override virtual
Implements RageFileBasic.
References RageFileBasic::ClearError(), m_File, and m_sError.
Referenced by LunaRageFile::ClearError().
Close()
void RageFile::Close ()
References RageFileManager::CacheFile(), FILEMAN, m_File, m_Mode, m_Path, and WRITE.
Referenced by addFileToForm(), FileTransfer::Cancel(), ScreenPackages::CancelDownload(), LunaRageFile::Close(), TZip::Close(), convert_xml_file(), RageFileManager::CreateDir(), DoInstalls(), FileTransfer::FileTransfer(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), ScreenPackages::Init(), BackgroundLoader::LoadThread(), Open(), LuaHelpers::save_lua_table_to_file(), RageLog::SetInfoToDisk(), RageLog::SetLogToDisk(), RageLog::SetUserLogToDisk(), ScreenPackages::TweenOffScreen(), WriteFile(), FileTransfer::~FileTransfer(), MovieDecoder_FFMpeg::~MovieDecoder_FFMpeg(), ~RageFile(), and RageLog::~RageLog().
Copy()
RageFile * RageFile::Copy () const override virtual
Implements RageFileBasic.
References RageFile().
EnableCRC32()
void RageFile::EnableCRC32 (bool on = true) override virtual
Implements RageFileBasic.
References ASSERT_OPEN, RageFileBasic::EnableCRC32(), and m_File.
Flush()
int RageFile::Flush () override virtual
Implements RageFileBasic.
References RageFileBasic::Flush(), m_File, and SetError().
Referenced by RageLog::Flush(), LunaRageFile::Flush(), FileTransfer::HTTPUpdate(), RageFile_png_flush(), RageSurfaceUtils::SaveBMP(), NotesWriterSM::Write(), NotesWriterSSC::Write(), NotesWriterETT::Write(), IniFile::WriteFile(), and WriteFile().
GetCRC32()
bool RageFile::GetCRC32 (uint32_t * iRet) override virtual
Implements RageFileBasic.
References ASSERT_OPEN, RageFileBasic::GetCRC32(), and m_File.
GetError()
RString RageFile::GetError () const override virtual
Implements RageFileBasic.
References RageFileBasic::GetError(), m_File, and m_sError.
Referenced by CompileShader(), convert_xml_file(), ScreenPackages::EnterURL(), ExportPackage(), LunaRageFile::GetError(), GetFileContents(), BMSChart::Load(), LoadBMP(), RageSurfaceUtils::LoadFile(), JsonUtil::LoadFromFileShowErrors(), XmlFileUtil::LoadFromFileShowErrors(), LyricsLoader::LoadFromLRCFile(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), OsuLoader::LoadNoteDataFromSimfile(), MovieDecoder_FFMpeg::Open(), RageFile_png_flush(), RageFile_png_write(), RageLog::RageLog(), RageSurface_Load_BMP(), RageSurface_Load_GIF(), RageSurface_Load_JPEG(), RageSurface_Load_PNG(), CsvFile::ReadFile(), IniFile::ReadFile(), MsdFile::ReadFile(), LuaHelpers::save_lua_table_to_file(), XMLProfile::SaveEttXmlToDir(), RageDisplay::SaveScreenshot(), XMLProfile::SaveStatsXmlToDir(), XmlFileUtil::SaveToFile(), RageLog::SetInfoToDisk(), RageLog::SetLogToDisk(), RageLog::SetUserLogToDisk(), CryptManager::Sign(), FileTransfer::StartTransfer(), CryptManager::VerifyFileWithFile(), NotesWriterDWI::Write(), NotesWriterSM::Write(), NotesWriterSSC::Write(), NotesWriterETT::Write(), WriteBytes(), CsvFile::WriteFile(), JsonUtil::WriteFile(), IniFile::WriteFile(), and WriteFile().
GetFD()
int RageFile::GetFD () override virtual
Implements RageFileBasic.
References ASSERT_READ, RageFileBasic::GetFD(), and m_File.
GetFileSize()
int RageFile::GetFileSize () const override virtual
Implements RageFileBasic.
References ASSERT_READ, RageFileBasic::GetFileSize(), and m_File.
Referenced by addFileToForm(), AVIORageFile_Seek(), CompileShader(), GetFileContents(), OsuLoader::LoadNoteDataFromSimfile(), TZip::open_file(), MsdFile::ReadFile(), and FileTransfer::StartTransfer().
GetLine()
int RageFile::GetLine (RString & out) override virtual
Implements RageFileBasic.
References ASSERT_READ, RageFileBasic::GetLine(), and m_File.
Referenced by GetFileContents(), LunaRageFile::GetLine(), BMSChart::Load(), LyricsLoader::LoadFromLRCFile(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), and msAnimation::LoadMilkshapeAsciiBones().
GetMode()
int RageFile::GetMode () const inline
References m_Mode.
Referenced by LunaRageFile::can_safely_read(), and LunaRageFile::can_safely_write().
GetPath()
RString RageFile::GetPath () const
References RageFileBasic::GetDisplayPath(), GetRealPath(), IsOpen(), and m_File.
Referenced by LunaRageFile::can_safely_read(), LunaRageFile::can_safely_write(), DoInstalls(), LyricsLoader::LoadFromLRCFile(), and LunaRageFile::safely_opened().
GetRealPath()
const RString& RageFile::GetRealPath () const inline
References m_Path.
Referenced by GetPath(), and FileTransfer::HTTPUpdate().
IsOpen()
bool RageFile::IsOpen () const inline
References m_File.
Referenced by GetPath(), LunaRageFile::safely_opened(), RageLog::SetInfoToDisk(), RageLog::SetLogToDisk(), RageLog::SetUserLogToDisk(), and RageLog::Write().
Open()
bool RageFile::Open (const RString & path, int mode = READ)
References ASSERT, Close(), FILEMAN, FixSlashesInPlace(), m_File, m_Mode, m_Path, RageFileManager::Open(), READ, SetError(), and WRITE.
Referenced by addFileToForm(), CompileShader(), convert_xml_file(), RageFileManager::CreateDir(), DoInstalls(), Download::Download(), ScreenPackages::EnterURL(), ExportPackage(), FileCopy(), FileTransfer::FileTransfer(), GetFileContents(), RageMovieTexture::GetFourCC(), CryptManager::GetMD5ForFile(), AnnouncerManager::GetPathTo(), CryptManager::GetSHA1ForFile(), ScreenPackages::Init(), BMSChart::Load(), RageSurfaceUtils::LoadFile(), OsuLoader::LoadFromDir(), JsonUtil::LoadFromFileShowErrors(), XmlFileUtil::LoadFromFileShowErrors(), LyricsLoader::LoadFromLRCFile(), Model::LoadMaterialsFromMilkshapeAscii(), RageModelGeometry::LoadMilkshapeAscii(), msAnimation::LoadMilkshapeAsciiBones(), OsuLoader::LoadNoteDataFromSimfile(), RageSurfaceUtils::LoadSurface(), BackgroundLoader::LoadThread(), Nsis(), MovieDecoder_FFMpeg::Open(), LunaRageFile::Open(), TZip::open_file(), RageLog::RageLog(), RageSurface_Load_BMP(), RageSurface_Load_GIF(), RageSurface_Load_JPEG(), RageSurface_Load_PNG(), CsvFile::ReadFile(), IniFile::ReadFile(), MsdFile::ReadFile(), LuaHelpers::save_lua_table_to_file(), XMLProfile::SaveEttXmlToDir(), RageDisplay::SaveScreenshot(), XMLProfile::SaveStatsXmlToDir(), RageSurfaceUtils::SaveSurface(), XmlFileUtil::SaveToFile(), RageLog::SetInfoToDisk(), RageLog::SetLogToDisk(), LoadingWindow_MacOSX::SetSplash(), RageLog::SetUserLogToDisk(), CryptManager::Sign(), FileTransfer::StartTransfer(), CryptManager::VerifyFileWithFile(), NotesWriterDWI::Write(), NotesWriterSM::Write(), NotesWriterSSC::Write(), NotesWriterETT::Write(), CsvFile::WriteFile(), JsonUtil::WriteFile(), IniFile::WriteFile(), and WriteFile().
operator=()
RageFile& RageFile::operator= (const RageFile & rhs) private
PushSelf()
virtual void RageFile::PushSelf (lua_State * L) virtual
Referenced by RageFileUtil::CreateRageFile().
PutLine()
int RageFile::PutLine (const RString & str) override virtual
Implements RageFileBasic.
References ASSERT_WRITE, m_File, and RageFileBasic::PutLine().
Referenced by Nsis(), LunaRageFile::PutLine(), NotesWriterDWI::Write(), NotesWriterSM::Write(), NotesWriterSSC::Write(), NotesWriterETT::Write(), RageLog::Write(), write_tag(), WriteDWINotesField(), WriteDWINotesTag(), and WriteGlobalTags().
Read() [1/3]
int RageFile::Read (void * buffer, size_t bytes) override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Read().
Referenced by addFileToForm(), AVIORageFile_ReadPacket(), CompileShader(), GetFileContents(), RageMovieTexture::GetFourCC(), LoadBMP(), OsuLoader::LoadFromDir(), OsuLoader::LoadNoteDataFromSimfile(), RageSurfaceUtils::LoadSurface(), BackgroundLoader::LoadThread(), RageFile_JPEG_fill_input_buffer(), LunaRageFile::Read(), TZip::read(), LunaRageFile::ReadBytes(), MsdFile::ReadFile(), ReadThisReadCallback(), LoadingWindow_MacOSX::SetSplash(), and FileTransfer::StartTransfer().
Read() [2/3]
int RageFile::Read (RString & buffer, int bytes = -1) override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Read().
Read() [3/3]
int RageFile::Read (void * buffer, size_t bytes, int nmemb) override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Read().
Seek() [1/2]
int RageFile::Seek (int offset) override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Seek().
Referenced by AVIORageFile_Seek(), RageMovieTexture::GetFourCC(), LoadBMP(), RageFile_JPEG_skip_input_data(), and LunaRageFile::Seek().
Seek() [2/2]
int RageFile::Seek (int offset, int whence) override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Seek().
SetError()
void RageFile::SetError (const RString & err) private
References RageFileBasic::ClearError(), m_File, and m_sError.
Referenced by Flush(), and Open().
Tell()
int RageFile::Tell () const override virtual
Implements RageFileBasic.
References ASSERT_READ, m_File, and RageFileBasic::Tell().
Referenced by RageFile_JPEG_skip_input_data(), and LunaRageFile::Tell().
Write() [1/3]
int RageFile::Write (const void * buffer, size_t bytes) override virtual
Implements RageFileBasic.
References ASSERT_WRITE, m_File, and RageFileBasic::Write().
Referenced by convert_xml_file(), empty_output_buffer(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), BackgroundLoader::LoadThread(), actor_template_t::output_to_file(), RageFile_png_write(), LuaHelpers::save_lua_table_to_file(), RageSurfaceUtils::SaveSurface(), term_destination(), NotesWriterDWI::Write(), Write(), LunaRageFile::Write(), TZip::write(), write_lua_table_to_file(), write_lua_value_to_file(), WriteBytes(), WriteDWINotesField(), WriteDWINotesTag(), JsonUtil::WriteFile(), WriteFile(), and WriteGlobalTags().
Write() [2/3]
int RageFile::Write (const RString & string) inline override virtual
Implements RageFileBasic.
References Write().
Write() [3/3]
int RageFile::Write (const void * buffer, size_t bytes, int nmemb) override virtual
Implements RageFileBasic.
References ASSERT_WRITE, m_File, and RageFileBasic::Write().
Member Data Documentation
m_File
RageFileBasic* RageFile::m_File private
Referenced by AtEOF(), ClearError(), Close(), EnableCRC32(), Flush(), GetCRC32(), GetError(), GetFD(), GetFileSize(), GetLine(), GetPath(), IsOpen(), Open(), PutLine(), RageFile(), Read(), Seek(), SetError(), Tell(), and Write().
m_Mode
int RageFile::m_Mode private
Referenced by Close(), GetMode(), Open(), and RageFile().
m_Path
RString RageFile::m_Path private
Referenced by Close(), GetRealPath(), Open(), and RageFile().
m_sError
RString RageFile::m_sError private
Referenced by ClearError(), GetError(), and SetError().
The documentation for this class was generated from the following files:
RageFile.h
RageFile.cpp