Etterna: LunaPlayer Class Reference
LunaPlayer Class Reference
Allow Lua to have access to the Player.
Public Member Functions
LunaPlayer ()
Public Member Functions inherited from Luna< Player >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetLife (T *p, lua_State *L)
static int ChangeLife (T *p, lua_State *L)
static int SetActorWithJudgmentPosition (T *p, lua_State *L)
static int SetActorWithComboPosition (T *p, lua_State *L)
static int GetPlayerTimingData (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Player >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Player >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Player >
using T = Player
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Player >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Player.
Constructor & Destructor Documentation
LunaPlayer()
LunaPlayer::LunaPlayer () inline
References ADD_METHOD, Player::ChangeLife(), Player::GetPlayerTimingData(), Player::SetActorWithComboPosition(), Player::SetActorWithJudgmentPosition(), and Player::SetLife().
Member Function Documentation
ChangeLife()
static int LunaPlayer::ChangeLife (T * p, lua_State * L) inline static
References Player::ChangeLife(), COMMON_RETURN_SELF, FArg, and Player::m_inside_lua_set_life.
GetPlayerTimingData()
static int LunaPlayer::GetPlayerTimingData (T * p, lua_State * L) inline static
References Player::GetPlayerTimingData(), and TimingData::PushSelf().
SetActorWithComboPosition()
static int LunaPlayer::SetActorWithComboPosition (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Player::SetActorWithComboPosition().
SetActorWithJudgmentPosition()
static int LunaPlayer::SetActorWithJudgmentPosition (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Player::SetActorWithJudgmentPosition().
SetLife()
static int LunaPlayer::SetLife (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, Player::m_inside_lua_set_life, and Player::SetLife().
The documentation for this class was generated from the following file:
Player.cpp