Etterna: RageSoundReader_SpeedChange Class Reference
RageSoundReader_SpeedChange Class Reference
#include <RageSoundReader_SpeedChange.h>
Classes
struct ChannelInfo
Public Member Functions
RageSoundReader_SpeedChange (RageSoundReader *pSource)
virtual int SetPosition (int iFrame)
virtual int Read (float *pBuf, int iFrames)
virtual RageSoundReader_SpeedChange * Copy () const
virtual bool SetProperty (const RString &sProperty, float fValue)
virtual int GetNextSourceFrame () const
virtual float GetStreamToSourceRatio () const
void SetSpeedRatio (float fRatio)
bool NextReadWillStep () const
float GetRatio () const
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int GetSampleRate () const override
unsigned GetNumChannels () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Protected Member Functions
int FillData (int iMax)
void EraseData (int iToDelete)
int Step ()
void Reset ()
int GetCursorAvail () const
int GetWindowSizeFrames () const
int GetToleranceFrames () const
Protected Attributes
int m_iDataBufferAvailFrames
vector< ChannelInfo > m_Channels
int m_iUncorrelatedPos
int m_iPos
float m_fSpeedRatio
float m_fTrailingSpeedRatio
float m_fErrorFrames
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Constructor & Destructor Documentation
RageSoundReader_SpeedChange()
RageSoundReader_SpeedChange::RageSoundReader_SpeedChange (RageSoundReader * pSource)
References f, RageSoundReader::GetNumChannels(), m_Channels, m_fSpeedRatio, m_fTrailingSpeedRatio, m_iDataBufferAvailFrames, Reset(), and SetSpeedRatio().
Referenced by Copy().
Member Function Documentation
Copy()
virtual RageSoundReader_SpeedChange* RageSoundReader_SpeedChange::Copy () const inline virtual
Implements RageSoundReader.
References RageSoundReader_SpeedChange().
EraseData()
void RageSoundReader_SpeedChange::EraseData (int iToDelete) protected
References ASSERT, m_Channels, RageSoundReader_SpeedChange::ChannelInfo::m_DataBuffer, RageSoundReader_SpeedChange::ChannelInfo::m_iCorrelatedPos, m_iDataBufferAvailFrames, and m_iUncorrelatedPos.
Referenced by Step().
FillData()
int RageSoundReader_SpeedChange::FillData (int iMax) protected
References RageSoundReader::END_OF_FILE, m_Channels, RageSoundReader_SpeedChange::ChannelInfo::m_DataBuffer, m_iDataBufferAvailFrames, RageSoundReader_Filter::m_pSource, and RageSoundReader::Read().
Referenced by Step().
GetCursorAvail()
int RageSoundReader_SpeedChange::GetCursorAvail () const protected
References GetWindowSizeFrames(), m_Channels, m_iDataBufferAvailFrames, m_iPos, and min().
Referenced by GetStreamToSourceRatio(), NextReadWillStep(), and Read().
GetNextSourceFrame()
int RageSoundReader_SpeedChange::GetNextSourceFrame () const virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Filter::GetNextSourceFrame(), m_fTrailingSpeedRatio, m_iDataBufferAvailFrames, m_iPos, and m_iUncorrelatedPos.
GetRatio()
float RageSoundReader_SpeedChange::GetRatio () const inline
References m_fSpeedRatio.
GetStreamToSourceRatio()
float RageSoundReader_SpeedChange::GetStreamToSourceRatio () const virtual
Reimplemented from RageSoundReader_Filter.
References GetCursorAvail(), RageSoundReader_Filter::GetStreamToSourceRatio(), m_fSpeedRatio, and m_fTrailingSpeedRatio.
GetToleranceFrames()
int RageSoundReader_SpeedChange::GetToleranceFrames () const inline protected
References GetWindowSizeFrames().
Referenced by Step().
GetWindowSizeFrames()
int RageSoundReader_SpeedChange::GetWindowSizeFrames () const protected
References RageSoundReader_Filter::GetSampleRate(), and WINDOW_SIZE_MS.
Referenced by GetCursorAvail(), GetToleranceFrames(), Read(), and Step().
NextReadWillStep()
bool RageSoundReader_SpeedChange::NextReadWillStep () const inline
References GetCursorAvail().
Referenced by RageSoundReader_PitchChange::Read().
Read()
int RageSoundReader_SpeedChange::Read (float * pBuf, int iFrames) virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader::END_OF_FILE, f, GetCursorAvail(), GetWindowSizeFrames(), m_Channels, RageSoundReader_SpeedChange::ChannelInfo::m_DataBuffer, m_fSpeedRatio, m_fTrailingSpeedRatio, RageSoundReader_SpeedChange::ChannelInfo::m_iCorrelatedPos, m_iDataBufferAvailFrames, RageSoundReader_SpeedChange::ChannelInfo::m_iLastCorrelatedPos, m_iPos, RageSoundReader_Filter::m_pSource, min(), RageSoundReader::Read(), SCALE, and Step().
Reset()
void RageSoundReader_SpeedChange::Reset () protected
References m_Channels, m_fErrorFrames, m_fSpeedRatio, m_fTrailingSpeedRatio, RageSoundReader_SpeedChange::ChannelInfo::m_iCorrelatedPos, m_iDataBufferAvailFrames, RageSoundReader_SpeedChange::ChannelInfo::m_iLastCorrelatedPos, m_iPos, and m_iUncorrelatedPos.
Referenced by RageSoundReader_SpeedChange(), and SetPosition().
SetPosition()
int RageSoundReader_SpeedChange::SetPosition (int iFrame) virtual
Reimplemented from RageSoundReader_Filter.
References Reset(), and RageSoundReader_Filter::SetPosition().
SetProperty()
bool RageSoundReader_SpeedChange::SetProperty (const RString & sProperty, float fValue) virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Filter::SetProperty(), and SetSpeedRatio().
SetSpeedRatio()
void RageSoundReader_SpeedChange::SetSpeedRatio (float fRatio)
References m_fSpeedRatio, m_fTrailingSpeedRatio, and m_iDataBufferAvailFrames.
Referenced by RageSoundReader_SpeedChange(), RageSoundReader_PitchChange::Read(), and SetProperty().
Step()
int RageSoundReader_SpeedChange::Step () protected
References ASSERT, EraseData(), FillData(), FindClosestMatch(), GetToleranceFrames(), GetWindowSizeFrames(), m_Channels, RageSoundReader_SpeedChange::ChannelInfo::m_DataBuffer, m_fErrorFrames, m_fSpeedRatio, m_fTrailingSpeedRatio, RageSoundReader_SpeedChange::ChannelInfo::m_iCorrelatedPos, m_iDataBufferAvailFrames, RageSoundReader_SpeedChange::ChannelInfo::m_iLastCorrelatedPos, m_iPos, m_iUncorrelatedPos, max(), and min().
Referenced by Read().
Member Data Documentation
m_Channels
vector<ChannelInfo> RageSoundReader_SpeedChange::m_Channels protected
Referenced by EraseData(), FillData(), GetCursorAvail(), RageSoundReader_SpeedChange(), Read(), Reset(), and Step().
m_fErrorFrames
float RageSoundReader_SpeedChange::m_fErrorFrames protected
Referenced by Reset(), and Step().
m_fSpeedRatio
float RageSoundReader_SpeedChange::m_fSpeedRatio protected
Referenced by GetRatio(), GetStreamToSourceRatio(), RageSoundReader_SpeedChange(), Read(), Reset(), SetSpeedRatio(), and Step().
m_fTrailingSpeedRatio
float RageSoundReader_SpeedChange::m_fTrailingSpeedRatio protected
Referenced by GetNextSourceFrame(), GetStreamToSourceRatio(), RageSoundReader_SpeedChange(), Read(), Reset(), SetSpeedRatio(), and Step().
m_iDataBufferAvailFrames
int RageSoundReader_SpeedChange::m_iDataBufferAvailFrames protected
Referenced by EraseData(), FillData(), GetCursorAvail(), GetNextSourceFrame(), RageSoundReader_SpeedChange(), Read(), Reset(), SetSpeedRatio(), and Step().
m_iPos
int RageSoundReader_SpeedChange::m_iPos protected
Referenced by GetCursorAvail(), GetNextSourceFrame(), Read(), Reset(), and Step().
m_iUncorrelatedPos
int RageSoundReader_SpeedChange::m_iUncorrelatedPos protected
Referenced by EraseData(), GetNextSourceFrame(), Reset(), and Step().
The documentation for this class was generated from the following files:
RageSoundReader_SpeedChange.h
RageSoundReader_SpeedChange.cpp