Etterna: Player.cpp File Reference
Player.cpp File Reference
#include "global.h"
#include "Player.h"
#include "ActorUtil.h"
#include "AdjustSync.h"
#include "ArrowEffects.h"
#include "DancingCharacters.h"
#include "Game.h"
#include "GameCommand.h"
#include "GameConstantsAndTypes.h"
#include "GamePreferences.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "HoldJudgment.h"
#include "InputMapper.h"
#include "LifeMeter.h"
#include "MessageManager.h"
#include "NetworkSyncManager.h"
#include "NoteDataUtil.h"
#include "NoteDataWithScoring.h"
#include "NoteField.h"
#include "NoteSkinManager.h"
#include "PlayerAI.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "Profile.h"
#include "ProfileManager.h"
#include "RageDisplay.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "ScoreDisplay.h"
#include "ScoreKeeperNormal.h"
#include "ScoreManager.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "Song.h"
#include "SongManager.h"
#include "StageStats.h"
#include "StatsManager.h"
#include "Steps.h"
#include "Style.h"
#include "ThemeManager.h"
#include "ThemeMetric.h"
#include "LuaBinding.h"
Classes
class JudgedRows
Helper class to ensure that each row is only judged once without taking too much memory.
class LunaPlayer
Allow Lua to have access to the Player.
Macros
#define CROSSED(x) (iOldCombo < (x) && iCurCombo >= (x))
#define MILESTONE_CHECK(amount) ((iCombo / (amount)) > (m_iLastSeenCombo / (amount)))
Functions
RString ATTACK_DISPLAY_X_NAME (size_t p, size_t both_sides)
void TimingWindowSecondsInit (size_t i, RString &sNameOut, float &defaultValueOut)
static bool NeedsTapJudging (const TapNote &tn)
Determine if a TapNote needs a tap note style judgment.
static bool NeedsHoldJudging (const TapNote &tn)
Determine if a TapNote needs a hold note style judgment.
static void GenerateCacheDataStructure (PlayerState *pPlayerState, const NoteData &notes)
Variables
static Preference< float > m_fTimingWindowScale ("TimingWindowScale", 1.0f)
static Preference< float > m_fTimingWindowAdd ("TimingWindowAdd", 0)
static Preference1D< float > m_fTimingWindowSeconds (TimingWindowSecondsInit, NUM_TimingWindow)
static Preference< float > m_fTimingWindowJump ("TimingWindowJump", 0.25)
static Preference< float > m_fMaxInputLatencySeconds ("MaxInputLatencySeconds", 0.0)
static Preference< bool > g_bEnableMineSoundPlayback ("EnableMineHitSound", true)
ThemeMetric< float > INITIAL_HOLD_LIFE ("Player", "InitialHoldLife")
How much life is in a hold note when you start on it?
ThemeMetric< float > MAX_HOLD_LIFE ("Player", "MaxHoldLife")
How much hold life is possible to have when holding a hold note?
ThemeMetric< bool > PENALIZE_TAP_SCORE_NONE ("Player", "PenalizeTapScoreNone")
ThemeMetric< bool > JUDGE_HOLD_NOTES_ON_SAME_ROW_TOGETHER ("Player", "JudgeHoldNotesOnSameRowTogether")
ThemeMetric< bool > CHECKPOINTS_FLASH_ON_HOLD ("Player", "CheckpointsFlashOnHold")
ThemeMetric< bool > IMMEDIATE_HOLD_LET_GO ("Player", "ImmediateHoldLetGo")
ThemeMetric< bool > COMBO_BREAK_ON_IMMEDIATE_HOLD_LET_GO ("Player", "ComboBreakOnImmediateHoldLetGo")
ThemeMetric< bool > REQUIRE_STEP_ON_HOLD_HEADS ("Player", "RequireStepOnHoldHeads")
Must a Player step on a hold head for a hold to activate?
ThemeMetric< bool > REQUIRE_STEP_ON_MINES ("Player", "RequireStepOnMines")
Must a Player step on a mine for it to activate?
ThemeMetric< bool > ROLL_BODY_INCREMENTS_COMBO ("Player", "RollBodyIncrementsCombo")
Does repeatedly stepping on a roll to keep it alive increment the combo?
ThemeMetric< bool > AVOID_MINE_INCREMENTS_COMBO ("Gameplay", "AvoidMineIncrementsCombo")
Does not stepping on a mine increase the combo?
ThemeMetric< bool > MINE_HIT_INCREMENTS_MISS_COMBO ("Gameplay", "MineHitIncrementsMissCombo")
Does stepping on a mine increment the miss combo?
ThemeMetric< bool > CHECKPOINTS_TAPS_SEPARATE_JUDGMENT ("Player", "CheckpointsTapsSeparateJudgment")
Are checkpoints and taps considered separate judgments?
ThemeMetric< bool > SCORE_MISSED_HOLDS_AND_ROLLS ("Player", "ScoreMissedHoldsAndRolls")
Do we score missed holds and rolls with HoldNoteScores?
ThemeMetric< float > PERCENT_UNTIL_COLOR_COMBO ("Player", "PercentUntilColorCombo")
How much of the song must have gone by before a Player's combo is colored?
ThemeMetric< int > COMBO_STOPPED_AT ("Player", "ComboStoppedAt")
How much combo must be earned before the announcer says "Combo Stopped"?
ThemeMetric< float > ATTACK_RUN_TIME_RANDOM ("Player", "AttackRunTimeRandom")
ThemeMetric< float > ATTACK_RUN_TIME_MINE ("Player", "AttackRunTimeMine")
ThemeMetric< float > M_MOD_HIGH_CAP ("Player", "MModHighCap")
What is our highest cap for mMods?
ThemeMetric< bool > BATTLE_RAVE_MIRROR ("Player", "BattleRaveMirror")
Will battle modes have their steps mirrored or kept the same?
Macro Definition Documentation
CROSSED
#define CROSSED (x) (iOldCombo < (x) && iCurCombo >= (x))
Referenced by Player::HandleTapRowScore().
MILESTONE_CHECK
#define MILESTONE_CHECK (amount) ((iCombo / (amount)) > (m_iLastSeenCombo / (amount)))
Referenced by Player::SetCombo().
Function Documentation
ATTACK_DISPLAY_X_NAME()
RString ATTACK_DISPLAY_X_NAME (size_t p, size_t both_sides)
References ssprintf().
GenerateCacheDataStructure()
static void GenerateCacheDataStructure (PlayerState * pPlayerState, const NoteData & notes) static
References TimingSegment::GetBeat(), PlayerState::GetDisplayedTiming(), NoteData::GetNumTracks(), ScrollSegment::GetRatio(), NoteData::GetTapNote(), NoteData::GetTapNoteRangeAllTracks(), TimingData::GetTimingSegments(), NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), PlayerState::m_CacheDisplayedBeat, PlayerState::m_CacheNoteStat, MAX_NOTE_ROW, NoteRowToBeat(), NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), SEGMENT_SCROLL, and TAP_EMPTY.
Referenced by Player::Load().
NeedsHoldJudging()
static bool NeedsHoldJudging (const TapNote & tn) static
Determine if a TapNote needs a hold note style judgment.
Parameters
tn the TapNote in question.
Returns
true if it does, false otherwise.
References DEFAULT_FAIL, HoldNoteResult::hns, HNS_None, TapNote::HoldResult, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_HoldTail, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and TapNote::type.
Referenced by Player::Update().
NeedsTapJudging()
static bool NeedsTapJudging (const TapNote & tn) static
Determine if a TapNote needs a tap note style judgment.
Parameters
tn the TapNote in question.
Returns
true if it does, false otherwise.
References DEFAULT_FAIL, TapNote::result, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_HoldTail, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, TapNoteResult::tns, TNS_None, and TapNote::type.
Referenced by Player::UpdateTapNotesMissedOlderThan().
TimingWindowSecondsInit()
void TimingWindowSecondsInit (size_t i, RString & sNameOut, float & defaultValueOut)
References FAIL_M, ssprintf(), TimingWindowToString(), TW_Checkpoint, TW_Hold, TW_Mine, TW_Roll, TW_W1, TW_W2, TW_W3, TW_W4, and TW_W5.
Variable Documentation
ATTACK_RUN_TIME_MINE
ThemeMetric<float> ATTACK_RUN_TIME_MINE("Player", "AttackRunTimeMine")
ATTACK_RUN_TIME_RANDOM
ThemeMetric<float> ATTACK_RUN_TIME_RANDOM("Player", "AttackRunTimeRandom")
AVOID_MINE_INCREMENTS_COMBO
ThemeMetric<bool> AVOID_MINE_INCREMENTS_COMBO("Gameplay", "AvoidMineIncrementsCombo")
Does not stepping on a mine increase the combo?
If set to true, every mine missed will increment the combo. If set to false, missing a mine will not affect the combo.
Referenced by Player::SetMineJudgment().
BATTLE_RAVE_MIRROR
ThemeMetric<bool> BATTLE_RAVE_MIRROR("Player", "BattleRaveMirror")
Will battle modes have their steps mirrored or kept the same?
CHECKPOINTS_FLASH_ON_HOLD
ThemeMetric<bool> CHECKPOINTS_FLASH_ON_HOLD("Player", "CheckpointsFlashOnHold")
Referenced by Player::HandleHoldCheckpoint().
CHECKPOINTS_TAPS_SEPARATE_JUDGMENT
ThemeMetric<bool> CHECKPOINTS_TAPS_SEPARATE_JUDGMENT("Player", "CheckpointsTapsSeparateJudgment")
Are checkpoints and taps considered separate judgments?
If set to true, they are considered separate. If set to false, they are considered the same.
Referenced by Player::CrossedRows().
COMBO_BREAK_ON_IMMEDIATE_HOLD_LET_GO
ThemeMetric<bool> COMBO_BREAK_ON_IMMEDIATE_HOLD_LET_GO("Player", "ComboBreakOnImmediateHoldLetGo")
Referenced by Player::UpdateHoldNotes().
COMBO_STOPPED_AT
ThemeMetric<int> COMBO_STOPPED_AT("Player", "ComboStoppedAt")
How much combo must be earned before the announcer says "Combo Stopped"?
Referenced by Player::SendComboMessages().
g_bEnableMineSoundPlayback
Preference<bool> g_bEnableMineSoundPlayback("EnableMineHitSound", true) static
Referenced by Player::UpdateJudgedRows().
IMMEDIATE_HOLD_LET_GO
ThemeMetric<bool> IMMEDIATE_HOLD_LET_GO("Player", "ImmediateHoldLetGo")
Referenced by Player::UpdateHoldNotes().
INITIAL_HOLD_LIFE
ThemeMetric<float> INITIAL_HOLD_LIFE("Player", "InitialHoldLife")
How much life is in a hold note when you start on it?
Referenced by Player::CrossedRows().
JUDGE_HOLD_NOTES_ON_SAME_ROW_TOGETHER
ThemeMetric<bool> JUDGE_HOLD_NOTES_ON_SAME_ROW_TOGETHER("Player", "JudgeHoldNotesOnSameRowTogether")
Referenced by Player::Update().
m_fMaxInputLatencySeconds
Preference<float> m_fMaxInputLatencySeconds("MaxInputLatencySeconds", 0.0) static
Referenced by Player::GetMaxStepDistanceSeconds().
m_fTimingWindowAdd
Preference<float> m_fTimingWindowAdd("TimingWindowAdd", 0) static
Referenced by Player::GetWindowSeconds().
m_fTimingWindowJump
Preference<float> m_fTimingWindowJump("TimingWindowJump", 0.25) static
m_fTimingWindowScale
Preference<float> m_fTimingWindowScale("TimingWindowScale", 1.0f) static
Referenced by Player::GetWindowSeconds(), Player::Load(), and Player::SetJudgment().
m_fTimingWindowSeconds
Preference1D<float> m_fTimingWindowSeconds(TimingWindowSecondsInit, NUM_TimingWindow) static
Referenced by Player::GetWindowSeconds().
M_MOD_HIGH_CAP
ThemeMetric<float> M_MOD_HIGH_CAP("Player", "MModHighCap")
What is our highest cap for mMods?
If set to 0 or less, assume the song takes over.
Referenced by Player::Init().
MAX_HOLD_LIFE
ThemeMetric<float> MAX_HOLD_LIFE("Player", "MaxHoldLife")
How much hold life is possible to have when holding a hold note?
This was an sm-ssc addition.
Referenced by Player::UpdateHoldNotes().
MINE_HIT_INCREMENTS_MISS_COMBO
ThemeMetric<bool> MINE_HIT_INCREMENTS_MISS_COMBO("Gameplay", "MineHitIncrementsMissCombo")
Does stepping on a mine increment the miss combo?
If set to true, every mine stepped on will break the combo and increment the miss combo. If set to false, stepping on a mine will not affect the combo.
Referenced by Player::SetMineJudgment().
PENALIZE_TAP_SCORE_NONE
ThemeMetric<bool> PENALIZE_TAP_SCORE_NONE("Player", "PenalizeTapScoreNone")
Referenced by Player::DoTapScoreNone(), and Player::ScoreAllActiveHoldsLetGo().
PERCENT_UNTIL_COLOR_COMBO
ThemeMetric<float> PERCENT_UNTIL_COLOR_COMBO("Player", "PercentUntilColorCombo")
How much of the song must have gone by before a Player's combo is colored?
Referenced by Player::SetCombo().
REQUIRE_STEP_ON_HOLD_HEADS
ThemeMetric<bool> REQUIRE_STEP_ON_HOLD_HEADS("Player", "RequireStepOnHoldHeads")
Must a Player step on a hold head for a hold to activate?
If set to true, the Player must step on a hold head in order for the hold to activate. If set to false, merely holding your foot down as the hold head approaches will suffice.
Referenced by Player::CrossedRows(), Player::Step(), and Player::UpdateHoldNotes().
REQUIRE_STEP_ON_MINES
ThemeMetric<bool> REQUIRE_STEP_ON_MINES("Player", "RequireStepOnMines")
Must a Player step on a mine for it to activate?
If set to true, the Player must step on a mine for it to blow up. If set to false, merely holding your foot down as the mine approaches will suffice.
Referenced by Player::Step().
ROLL_BODY_INCREMENTS_COMBO
ThemeMetric<bool> ROLL_BODY_INCREMENTS_COMBO("Player", "RollBodyIncrementsCombo")
Does repeatedly stepping on a roll to keep it alive increment the combo?
If set to true, repeatedly stepping on a roll will increment the combo. If set to false, only the roll head causes the combo to be incremented.
For those wishing to make a theme very accurate to In The Groove 2, set this to false.
Referenced by Player::Step().
SCORE_MISSED_HOLDS_AND_ROLLS
ThemeMetric<bool> SCORE_MISSED_HOLDS_AND_ROLLS("Player", "ScoreMissedHoldsAndRolls")
Do we score missed holds and rolls with HoldNoteScores?
If set to true, missed holds and rolls are given LetGo judgments. If set to false, missed holds and rolls are given no judgment on the hold side of things.
Referenced by Player::UpdateHoldNotes().