Etterna: SongCacheIndex Class Reference
SongCacheIndex Class Reference
#include <SongCacheIndex.h>
Public Member Functions
SongCacheIndex ()
~SongCacheIndex ()
pair< RString, int > SongFromStatement (Song *song, SQLite::Statement &query)
void LoadHyperCache (LoadingWindow *ld, map< RString, Song *> &hyperCache)
void LoadCache (LoadingWindow *ld, vector< pair< pair< RString, unsigned int >, Song *> *> &cache)
void DeleteSongFromDBByCondition (string &condition)
void DeleteSongFromDB (Song *songPtr)
void DeleteSongFromDBByDir (string dir)
void DeleteSongFromDBByDirHash (unsigned int hash)
unsigned GetCacheHash (const RString &path) const
int64_t InsertStepsTimingData (const TimingData &timing)
int64_t InsertSteps (const Steps *pSteps, int64_t songID)
bool LoadSongFromCache (Song *song, string dir)
bool CacheSong (Song &song, string dir)
void StartTransaction ()
void FinishTransaction ()
Static Public Member Functions
static RString GetCacheFilePath (const RString &sGroup, const RString &sPath)
Public Attributes
SQLite::Database * db { nullptr }
bool delay_save_cache
Private Member Functions
bool OpenDB ()
void ResetDB ()
void DeleteDB ()
void CreateDBTables ()
Static Private Member Functions
static RString MangleName (const RString &Name)
Private Attributes
IniFile CacheIndex
bool DBEmpty { true }
SQLite::Transaction * curTransaction { nullptr }
Constructor & Destructor Documentation
SongCacheIndex()
SongCacheIndex::SongCacheIndex ()
References SpecialFiles::CACHE_DIR, RageFileManager::CreateDir(), DBEmpty, delay_save_cache, FILEMAN, RageFileManager::IsADirectory(), and OpenDB().
~SongCacheIndex()
SongCacheIndex::~SongCacheIndex ()
References curTransaction, and db.
Member Function Documentation
CacheSong()
bool SongCacheIndex::CacheSong (Song & song, string dir)
References ASSERT_M, db, DeleteSongFromDBByDir(), DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, FOREACH_BackgroundLayer, FOREACH_CONST, Song::GetBackgroundChanges(), Steps::GetChartKey(), Song::GetFirstSecond(), Song::GetForegroundChanges(), GetHashForDirectory(), Song::GetInstrumentTracksToVectorString(), Song::GetLastSecond(), Song::GetSongDir(), Song::GetSpecifiedLastSecond(), Song::GetStepsToSave(), RageLog::Info(), InsertSteps(), join(), LOG, Song::m_bHasBanner, Song::m_bHasMusic, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicLengthSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_PreviewFile, Song::m_sArtist, Song::m_sArtistTranslit, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_sDiscFile, Song::m_SelectionDisplay, Song::m_sGenre, Song::m_sJacketFile, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sOrigin, Song::m_sPreviewVidFile, Song::m_sSongFileName, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Song::m_vsKeysoundFile, SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_DELAY, SEGMENT_FAKE, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_STOP, SEGMENT_TICKCOUNT, SEGMENT_TIME_SIG, SEGMENT_WARP, Song::SHOW_ALWAYS, Song::SHOW_NEVER, STEPFILE_VERSION_NUMBER, TimingData::ToVectorString(), and RageLog::Trace().
Referenced by Song::SaveToCacheFile(), and Song::SaveToSSCFile().
CreateDBTables()
void SongCacheIndex::CreateDBTables () private
References CACHE_DB_VERSION, and db.
Referenced by ResetDB().
DeleteDB()
void SongCacheIndex::DeleteDB () private
References CACHE_DB, db, FILEMAN, RageFileManager::Remove(), and RageFileManager::ResolvePath().
Referenced by ResetDB().
DeleteSongFromDB()
void SongCacheIndex::DeleteSongFromDB (Song * songPtr)
References DeleteSongFromDBByCondition(), GetHashForDirectory(), and Song::GetSongDir().
Referenced by SongManager::InitSongsFromDisk().
DeleteSongFromDBByCondition()
void SongCacheIndex::DeleteSongFromDBByCondition (string & condition)
References db.
Referenced by DeleteSongFromDB(), DeleteSongFromDBByDir(), and DeleteSongFromDBByDirHash().
DeleteSongFromDBByDir()
void SongCacheIndex::DeleteSongFromDBByDir (string dir)
References DeleteSongFromDBByCondition().
Referenced by CacheSong(), Song::ReloadFromSongDir(), and Song::Save().
DeleteSongFromDBByDirHash()
void SongCacheIndex::DeleteSongFromDBByDirHash (unsigned int hash)
References DeleteSongFromDBByCondition().
FinishTransaction()
void SongCacheIndex::FinishTransaction ()
References curTransaction.
Referenced by OpenDB(), and sm_main().
GetCacheFilePath()
RString SongCacheIndex::GetCacheFilePath (const RString & sGroup, const RString & sPath) static
References SpecialFiles::CACHE_DIR, and ssprintf().
Referenced by Song::GetCacheFilePath(), and ImageCache::GetImageCachePath().
GetCacheHash()
unsigned SongCacheIndex::GetCacheHash (const RString & path) const
References CacheIndex, IniFile::GetValue(), and MangleName().
InsertSteps()
int64_t SongCacheIndex::InsertSteps (const Steps * pSteps, int64_t songID)
References db, DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, TimingData::empty(), FOREACH_ENUM, Steps::GetAllMSD(), Steps::GetChartKey(), Steps::GetChartName(), Steps::GetChartStyle(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetDisplayBPM(), Steps::GetFilename(), Steps::GetMaxBPM(), Steps::GetMeter(), Steps::GetMinBPM(), Steps::GetMusicFile(), Steps::GetRadarValues(), InsertStepsTimingData(), join(), Steps::m_StepsTypeStr, Steps::m_Timing, NotesWriterSSC::MSDToString(), SmEscape(), and ssprintf().
Referenced by CacheSong().
InsertStepsTimingData()
int64_t SongCacheIndex::InsertStepsTimingData (const TimingData & timing)
References db, BPMSegment::GetBPM(), ComboSegment::GetCombo(), SpeedSegment::GetDelay(), TimeSignatureSegment::GetDen(), LabelSegment::GetLabel(), WarpSegment::GetLength(), ComboSegment::GetMissCombo(), TimeSignatureSegment::GetNum(), StopSegment::GetPause(), DelaySegment::GetPause(), SpeedSegment::GetRatio(), ScrollSegment::GetRatio(), TimingSegment::GetRow(), TickcountSegment::GetTicks(), TimingData::GetTimingSegments(), SpeedSegment::GetUnit(), TimingData::m_fBeat0OffsetInSeconds, NoteRowToBeat(), SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_DELAY, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_STOP, SEGMENT_TICKCOUNT, SEGMENT_TIME_SIG, SEGMENT_WARP, and ssprintf().
Referenced by InsertSteps().
LoadCache()
void SongCacheIndex::LoadCache (LoadingWindow * ld, vector< pair< pair< RString, unsigned int >, Song *> *> & cache)
References ThreadData::_progress, ThreadData::_threadsFinished, db, join(), LOG, max(), ResetDB(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), ThreadData::setUpdated(), SongFromStatement(), RageLog::Trace(), and ThreadData::waitForUpdate().
Referenced by SongManager::InitSongsFromDisk().
LoadHyperCache()
void SongCacheIndex::LoadHyperCache (LoadingWindow * ld, map< RString, Song *> & hyperCache)
References db, LOG, max(), ResetDB(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), SongFromStatement(), and RageLog::Trace().
LoadSongFromCache()
bool SongCacheIndex::LoadSongFromCache (Song * song, string dir)
References db, GetHashForDirectory(), Song::GetSongDir(), LOG, ResetDB(), SongFromStatement(), and RageLog::Trace().
MangleName()
RString SongCacheIndex::MangleName (const RString & Name) static private
References StdString::CStdStr< CT >::Replace().
Referenced by GetCacheHash().
OpenDB()
bool SongCacheIndex::OpenDB () private
References CACHE_DB, CACHE_DB_VERSION, curTransaction, db, FILEMAN, FinishTransaction(), RageFileManager::IsAFile(), LOG, ResetDB(), RageFileManager::ResolvePath(), StartTransaction(), and RageLog::Trace().
Referenced by SongCacheIndex().
ResetDB()
void SongCacheIndex::ResetDB () private
References CreateDBTables(), and DeleteDB().
Referenced by LoadCache(), LoadHyperCache(), LoadSongFromCache(), and OpenDB().
SongFromStatement()
pair< RString, int > SongCacheIndex::SongFromStatement (Song * song, SQLite::Statement & query) inline
References Song::AddForegroundChange(), Song::AddSteps(), Song::CreateSteps(), db, DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, GAMEMAN, Song::GetMainTitle(), SMLoader::LoadFromBGChangesString(), LOG, Song::m_bHasBanner, Song::m_bHasMusic, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicLengthSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_fVersion, Song::m_PreviewFile, Song::m_sArtist, Song::m_sArtistTranslit, Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDFile, Song::m_sCDTitleFile, Song::m_sCredit, Song::m_sDiscFile, Song::m_SelectionDisplay, TimingData::m_sFile, Song::m_sGenre, Song::m_sJacketFile, Song::m_sLyricsFile, Song::m_sMainTitle, Song::m_sMainTitleTranslit, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sOrigin, Song::m_sPreviewVidFile, Song::m_sSongFileName, Song::m_sSubTitle, Song::m_sSubTitleTranslit, Steps::m_StepsType, Steps::m_StepsTypeStr, Steps::m_Timing, Song::m_vsKeysoundFile, SSC::msdsplit(), NUM_RadarCategory, SMLoader::ProcessBGChanges(), SSCLoader::ProcessBPMs(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SMLoader::ProcessInstrumentTracks(), SSCLoader::ProcessLabels(), SSCLoader::ProcessScrolls(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SMLoader::ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), SSCLoader::ProcessWarps(), Steps::SetAllMSD(), Steps::SetCachedRadarValues(), Steps::SetChartKey(), Steps::SetChartName(), Steps::SetChartStyle(), Steps::SetCredit(), Steps::SetDescription(), Steps::SetDifficulty(), Steps::SetDisplayBPM(), Steps::SetFilename(), Song::SetFirstSecond(), Song::SetLastSecond(), Steps::SetMaxBPM(), Steps::SetMeter(), Steps::SetMinBPM(), Steps::SetMusicFile(), Song::SetSongDir(), Song::SetSpecifiedLastSecond(), Song::SHOW_ALWAYS, Song::SHOW_NEVER, split(), STEPFILE_VERSION_NUMBER, StringToInt(), GameManager::StringToStepsType(), SMLoader::TidyUpData(), Song::TidyUpData(), Steps::TidyUpData(), Trim(), RageLog::Warn(), and RadarValues::Zero().
Referenced by LoadCache(), LoadHyperCache(), and LoadSongFromCache().
StartTransaction()
void SongCacheIndex::StartTransaction ()
References curTransaction, and db.
Referenced by OpenDB(), and sm_main().
Member Data Documentation
CacheIndex
IniFile SongCacheIndex::CacheIndex private
Referenced by GetCacheHash().
curTransaction
SQLite::Transaction* SongCacheIndex::curTransaction { nullptr } private
Referenced by FinishTransaction(), OpenDB(), StartTransaction(), and ~SongCacheIndex().
db
SQLite::Database* SongCacheIndex::db { nullptr }
Referenced by CacheSong(), CreateDBTables(), DeleteDB(), DeleteSongFromDBByCondition(), InsertSteps(), InsertStepsTimingData(), LoadCache(), LoadHyperCache(), LoadSongFromCache(), OpenDB(), SongFromStatement(), StartTransaction(), and ~SongCacheIndex().
DBEmpty
bool SongCacheIndex::DBEmpty { true } private
Referenced by SongCacheIndex().
delay_save_cache
bool SongCacheIndex::delay_save_cache
Referenced by SongManager::InitSongsFromDisk(), and SongCacheIndex().
The documentation for this class was generated from the following files:
SongCacheIndex.h
SongCacheIndex.cpp