Etterna: RageFileBasic Class Reference
RageFileBasic Class Reference abstract
#include <RageFileBasic.h>
Public Member Functions
virtual ~RageFileBasic ()=default
virtual RString GetError () const =0
virtual void ClearError ()=0
virtual bool AtEOF () const =0
virtual int Seek (int iOffset)=0
virtual int Seek (int offset, int whence)=0
virtual int Tell () const =0
virtual int Read (void *pBuffer, size_t iBytes)=0
virtual int Read (RString &buffer, int bytes=-1)=0
virtual int Read (void *buffer, size_t bytes, int nmemb)=0
virtual int Write (const void *pBuffer, size_t iBytes)=0
virtual int Write (const RString &sString)=0
virtual int Write (const void *buffer, size_t bytes, int nmemb)=0
virtual int Flush ()=0
virtual RString GetDisplayPath () const
virtual RageFileBasic * Copy () const =0
virtual int GetLine (RString &out)=0
virtual int PutLine (const RString &str)=0
virtual void EnableCRC32 (bool on=true)=0
virtual bool GetCRC32 (uint32_t *iRet)=0
virtual int GetFileSize () const =0
virtual int GetFD ()=0
Constructor & Destructor Documentation
~RageFileBasic()
virtual RageFileBasic::~RageFileBasic () virtual default
Member Function Documentation
AtEOF()
virtual bool RageFileBasic::AtEOF () const pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageFile::AtEOF(), WavReaderADPCM::DecodeADPCMBlock(), RageSoundReader_MP3::fill_buffer(), and HashFile().
ClearError()
virtual void RageFileBasic::ClearError () pure virtual
Implemented in RageFileObj, RageFile, and RageFileDriverReadAhead.
Referenced by RageFileDriverReadAhead::ClearError(), RageFile::ClearError(), and RageFile::SetError().
Copy()
virtual RageFileBasic* RageFileBasic::Copy () const pure virtual
Implemented in RageFileObjTimeout, RageFileObj, RageFileObjDirect, RageFile, RageFileObjInflate, RageFileObjMem, RageFileDriverReadAhead, and RageFileDriverSlice.
Referenced by RageSoundReader_Vorbisfile::Copy(), RageSoundReader_WAV::Copy(), RageSoundReader_MP3::Copy(), ThreadedFileWorker::HandleRequest(), RageFileDriverZip::Open(), RageSoundReader_FileReader::OpenFile(), RageFile::RageFile(), RageFileDriverReadAhead::RageFileDriverReadAhead(), RageFileDriverSlice::RageFileDriverSlice(), and RageFileObjInflate::RageFileObjInflate().
EnableCRC32()
virtual void RageFileBasic::EnableCRC32 (bool on = true) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageFile::EnableCRC32().
Flush()
virtual int RageFileBasic::Flush () pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by FileCopy(), RageFileObjGzip::Finish(), RageFile::Flush(), RageFileObjDeflate::FlushInternal(), ThreadedFileWorker::HandleRequest(), and XmlFileUtil::SaveToFile().
GetCRC32()
virtual bool RageFileBasic::GetCRC32 (uint32_t * iRet) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageFile::GetCRC32(), and GunzipString().
GetDisplayPath()
virtual RString RageFileBasic::GetDisplayPath () const inline virtual
Reimplemented in RageFileObj, and RageFileObjDirect.
Referenced by WavReaderADPCM::DecodeADPCMBlock(), RageFile::GetPath(), HashFile(), RageSoundReader_WAV::Open(), RageSoundReader_FileReader::OpenFile(), and CryptManager::Verify().
GetError()
virtual RString RageFileBasic::GetError () const pure virtual
Implemented in RageFileObj, RageFile, and RageFileDriverReadAhead.
Referenced by WavReaderADPCM::DecodeADPCMBlock(), FileCopy(), RageSoundReader_MP3::fill_buffer(), RageFileObjGzip::Finish(), RageFileObjDeflate::FlushInternal(), RageFileDriverReadAhead::GetError(), RageFile::GetError(), ThreadedFileWorker::HandleRequest(), HashFile(), XmlFileUtil::LoadFromFileShowErrors(), FileReading::ReadBytes(), CsvFile::ReadFile(), IniFile::ReadFile(), RageFileObjInflate::ReadInternal(), RageFileDriverSlice::ReadInternal(), FileReading::ReadString(), FileReading::Seek(), RageFileDriverSlice::SeekInternal(), RageFileDriverZip::SeekToEndCentralRecord(), CsvFile::WriteFile(), IniFile::WriteFile(), and RageFileObjDeflate::WriteInternal().
GetFD()
virtual int RageFileBasic::GetFD () pure virtual
Implemented in RageFileObjTimeout, RageFileObj, RageFile, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, and RageFileDriverSlice.
Referenced by RageFileManagerReadAhead::CacheHintStreaming(), RageFileDriverReadAhead::FileSupported(), RageFileDriverSlice::GetFD(), RageFileObjInflate::GetFD(), RageFileDriverReadAhead::GetFD(), and RageFile::GetFD().
GetFileSize()
virtual int RageFileBasic::GetFileSize () const pure virtual
Implemented in RageFileObjTimeout, RageFileObj, RageFile, RageFileObjDeflate, RageFileObjDirect, RageFileDriverReadAhead, RageFileObjInflate, RageFileDriverSlice, and RageFileObjMem.
Referenced by RageFileManagerReadAhead::CacheHintStreaming(), RageFileDriverReadAhead::GetFileSize(), RageFileObjDeflate::GetFileSize(), RageFile::GetFileSize(), ThreadedFileWorker::HandleRequest(), JsonUtil::LoadFromFileShowErrors(), RageSoundReader_WAV::Open(), RageSoundReader_MP3::Open(), RageSoundReader_FileReader::OpenFile(), RageFileObjInflate::SeekInternal(), and RageFileDriverZip::SeekToEndCentralRecord().
GetLine()
virtual int RageFileBasic::GetLine (RString & out) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageFile::GetLine(), CsvFile::ReadFile(), and IniFile::ReadFile().
PutLine()
virtual int RageFileBasic::PutLine (const RString & str) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageFile::PutLine(), XmlFileUtil::SaveToFile(), CsvFile::WriteFile(), and IniFile::WriteFile().
Read() [1/3]
virtual int RageFileBasic::Read (void * pBuffer, size_t iBytes) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by WavReaderADPCM::DecodeADPCMBlock(), FileCopy(), RageSoundReader_MP3::fill_buffer(), RageFileDriverReadAhead::FillBuffer(), GunzipString(), ThreadedFileWorker::HandleRequest(), HashFile(), JsonUtil::LoadFromFileShowErrors(), XmlFileUtil::LoadFromFileShowErrors(), RageFile::Read(), WavReaderPCM::Read(), FileReading::ReadBytes(), RageFileObjInflate::ReadInternal(), RageFileDriverSlice::ReadInternal(), RageFileDriverReadAhead::ReadInternal(), FileReading::ReadString(), and RageFileDriverZip::SeekToEndCentralRecord().
Read() [2/3]
virtual int RageFileBasic::Read (RString & buffer, int bytes = -1) pure virtual
Implemented in RageFileObj, and RageFile.
Read() [3/3]
virtual int RageFileBasic::Read (void * buffer, size_t bytes, int nmemb) pure virtual
Implemented in RageFileObj, and RageFile.
Seek() [1/2]
virtual int RageFileBasic::Seek (int iOffset) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by RageSoundReader_Vorbisfile::Copy(), RageSoundReader_WAV::Copy(), RageSoundReader_MP3::Copy(), RageFileDriverReadAhead::FillBuffer(), ThreadedFileWorker::HandleRequest(), WavReaderPCM::Init(), WavReaderADPCM::Init(), RageSoundReader_MP3::MADLIB_rewind(), RageSoundReader_WAV::Open(), RageSoundReader_FileReader::OpenFile(), RageFileDriverZip::ParseZipfile(), RageFileDriverSlice::ReadInternal(), RageFileDriverZip::ReadLocalFileHeader(), RageFile::Seek(), FileReading::Seek(), RageSoundReader_MP3::seek_stream_to_byte(), RageFileObjInflate::SeekInternal(), RageFileDriverSlice::SeekInternal(), RageFileDriverReadAhead::SeekInternal(), RageFileDriverZip::SeekToEndCentralRecord(), WavReaderADPCM::SetEOF(), WavReaderPCM::SetPosition(), and WavReaderADPCM::SetPosition().
Seek() [2/2]
virtual int RageFileBasic::Seek (int offset, int whence) pure virtual
Implemented in RageFileObj, and RageFile.
Tell()
virtual int RageFileBasic::Tell () const pure virtual
Implemented in RageFileObj, RageFile, and RageFileDriverReadAhead.
Referenced by RageFileManagerReadAhead::CacheHintStreaming(), WavReaderADPCM::DecodeADPCMBlock(), RageFileDriverReadAhead::FillBuffer(), WavReaderPCM::GetNextSourceFrame(), WavReaderADPCM::GetNextSourceFrame(), RageSoundReader_WAV::Open(), RageFileDriverReadAhead::RageFileDriverReadAhead(), WavReaderPCM::Read(), RageFileDriverZip::ReadLocalFileHeader(), FileReading::SkipBytes(), and RageFile::Tell().
Write() [1/3]
virtual int RageFileBasic::Write (const void * pBuffer, size_t iBytes) pure virtual
Implemented in RageFileObj, and RageFile.
Referenced by FileCopy(), RageFileObjGzip::Finish(), RageFileObjDeflate::FlushInternal(), ThreadedFileWorker::HandleRequest(), RageFileObjGzip::Start(), RageFile::Write(), RageFileDriverReadAhead::WriteInternal(), and RageFileObjDeflate::WriteInternal().
Write() [2/3]
virtual int RageFileBasic::Write (const RString & sString) pure virtual
Implemented in RageFileObj, and RageFile.
Write() [3/3]
virtual int RageFileBasic::Write (const void * buffer, size_t bytes, int nmemb) pure virtual
Implemented in RageFileObj, and RageFile.
The documentation for this class was generated from the following file:
RageFileBasic.h