Etterna: LunaSong Class Reference
LunaSong Class Reference
Allow Lua to have access to the Song.
Public Member Functions
LunaSong ()
Public Member Functions inherited from Luna< Song >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetDisplayFullTitle (T *p, lua_State *L)
static int GetTranslitFullTitle (T *p, lua_State *L)
static int GetDisplayMainTitle (T *p, lua_State *L)
static int GetMainTitle (T *p, lua_State *L)
static int GetTranslitMainTitle (T *p, lua_State *L)
static int GetDisplaySubTitle (T *p, lua_State *L)
static int GetTranslitSubTitle (T *p, lua_State *L)
static int GetDisplayArtist (T *p, lua_State *L)
static int GetTranslitArtist (T *p, lua_State *L)
static int GetGenre (T *p, lua_State *L)
static int GetOrigin (T *p, lua_State *L)
static int GetAllSteps (T *p, lua_State *L)
static int GetStepsByStepsType (T *p, lua_State *L)
static int GetSongDir (T *p, lua_State *L)
static int GetMusicPath (T *p, lua_State *L)
static int GetBannerPath (T *p, lua_State *L)
static int GetBackgroundPath (T *p, lua_State *L)
static int GetPreviewVidPath (T *p, lua_State *L)
static int GetPreviewMusicPath (T *p, lua_State *L)
static int GetJacketPath (T *p, lua_State *L)
static int GetCDImagePath (T *p, lua_State *L)
static int GetDiscPath (T *p, lua_State *L)
static int GetCDTitlePath (T *p, lua_State *L)
static int GetLyricsPath (T *p, lua_State *L)
static int GetSongFilePath (T *p, lua_State *L)
static int IsTutorial (T *p, lua_State *L)
static int IsEnabled (T *p, lua_State *L)
static int GetGroupName (T *p, lua_State *L)
static int MusicLengthSeconds (T *p, lua_State *L)
static int GetSampleStart (T *p, lua_State *L)
static int GetSampleLength (T *p, lua_State *L)
static int IsLong (T *p, lua_State *L)
static int IsMarathon (T *p, lua_State *L)
static int HasStepsType (T *p, lua_State *L)
static int HasStepsTypeAndDifficulty (T *p, lua_State *L)
static int IsStepsUsingDifferentTiming (T *p, lua_State *L)
static int GetOneSteps (T *p, lua_State *L)
static int GetTimingData (T *p, lua_State *L)
static int GetBGChanges (T *p, lua_State *L)
static int IsFavorited (T *p, lua_State *L)
static int HasMusic (T *p, lua_State *L)
static int HasBanner (T *p, lua_State *L)
static int HasBackground (T *p, lua_State *L)
static int HasPreviewVid (T *p, lua_State *L)
static int HasJacket (T *p, lua_State *L)
static int HasDisc (T *p, lua_State *L)
static int HasCDImage (T *p, lua_State *L)
static int HasCDTitle (T *p, lua_State *L)
static int HasBGChanges (T *p, lua_State *L)
static int HasLyrics (T *p, lua_State *L)
static int HasSignificantBPMChangesOrStops (T *p, lua_State *L)
static int HasEdits (T *p, lua_State *L)
static int IsEasy (T *p, lua_State *L)
static int GetStepsSeconds (T *p, lua_State *L)
static int ShowInDemonstrationAndRanking (T *p, lua_State *L)
static int GetFirstSecond (T *p, lua_State *L)
static int GetLastSecond (T *p, lua_State *L)
static int GetFirstBeat (T *p, lua_State *L)
static int GetLastBeat (T *p, lua_State *L)
static int HasAttacks (T *p, lua_State *L)
static int GetDisplayBpms (T *p, lua_State *L)
static int IsDisplayBpmSecret (T *p, lua_State *L)
static int IsDisplayBpmConstant (T *p, lua_State *L)
static int IsDisplayBpmRandom (T *p, lua_State *L)
static int ReloadFromSongDir (T *p, lua_State *L)
static int GetOrTryAtLeastToGetSimfileAuthor (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Song >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Song >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Song >
using T = Song
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Song >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Song.
Constructor & Destructor Documentation
LunaSong()
LunaSong::LunaSong () inline
References ADD_METHOD, GetAllSteps(), GetBackgroundPath(), GetBannerPath(), GetBGChanges(), GetCDImagePath(), GetCDTitlePath(), GetDiscPath(), GetDisplayArtist(), GetDisplayBpms(), GetDisplayFullTitle(), GetDisplayMainTitle(), GetDisplaySubTitle(), GetFirstBeat(), GetFirstSecond(), GetGenre(), GetGroupName(), GetJacketPath(), GetLastBeat(), GetLastSecond(), GetLyricsPath(), GetMainTitle(), GetMusicPath(), GetOneSteps(), GetOrigin(), GetOrTryAtLeastToGetSimfileAuthor(), GetPreviewMusicPath(), GetPreviewVidPath(), GetSampleLength(), GetSampleStart(), GetSongDir(), GetSongFilePath(), GetStepsByStepsType(), GetStepsSeconds(), GetTimingData(), GetTranslitArtist(), GetTranslitFullTitle(), GetTranslitMainTitle(), GetTranslitSubTitle(), HasAttacks(), HasBackground(), HasBanner(), HasBGChanges(), HasCDImage(), HasCDTitle(), HasDisc(), HasEdits(), HasJacket(), HasLyrics(), HasMusic(), HasPreviewVid(), HasSignificantBPMChangesOrStops(), HasStepsType(), HasStepsTypeAndDifficulty(), IsDisplayBpmConstant(), IsDisplayBpmRandom(), IsDisplayBpmSecret(), IsEasy(), IsEnabled(), IsFavorited(), IsLong(), IsMarathon(), IsStepsUsingDifferentTiming(), IsTutorial(), MusicLengthSeconds(), ReloadFromSongDir(), and ShowInDemonstrationAndRanking().
Member Function Documentation
GetAllSteps()
static int LunaSong::GetAllSteps (T * p, lua_State * L) inline static
References Song::GetAllSteps(), and L.
Referenced by LunaSong().
GetBackgroundPath()
static int LunaSong::GetBackgroundPath (T * p, lua_State * L) inline static
References Song::GetBackgroundPath().
Referenced by LunaSong().
GetBannerPath()
static int LunaSong::GetBannerPath (T * p, lua_State * L) inline static
References Song::GetBannerPath().
Referenced by LunaSong().
GetBGChanges()
static int LunaSong::GetBGChanges (T * p, lua_State * L) inline static
References BACKGROUND_LAYER_1, Song::GetBackgroundChanges(), and LuaHelpers::Push().
Referenced by LunaSong().
GetCDImagePath()
static int LunaSong::GetCDImagePath (T * p, lua_State * L) inline static
References Song::GetCDImagePath().
Referenced by LunaSong().
GetCDTitlePath()
static int LunaSong::GetCDTitlePath (T * p, lua_State * L) inline static
References Song::GetCDTitlePath().
Referenced by LunaSong().
GetDiscPath()
static int LunaSong::GetDiscPath (T * p, lua_State * L) inline static
References Song::GetDiscPath().
Referenced by LunaSong().
GetDisplayArtist()
static int LunaSong::GetDisplayArtist (T * p, lua_State * L) inline static
References Song::GetDisplayArtist().
Referenced by LunaSong().
GetDisplayBpms()
static int LunaSong::GetDisplayBpms (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), Song::GetDisplayBpms(), DisplayBpms::GetMax(), and DisplayBpms::GetMin().
Referenced by LunaSong().
GetDisplayFullTitle()
static int LunaSong::GetDisplayFullTitle (T * p, lua_State * L) inline static
References Song::GetDisplayFullTitle().
Referenced by LunaSong().
GetDisplayMainTitle()
static int LunaSong::GetDisplayMainTitle (T * p, lua_State * L) inline static
References Song::GetDisplayMainTitle().
Referenced by LunaSong().
GetDisplaySubTitle()
static int LunaSong::GetDisplaySubTitle (T * p, lua_State * L) inline static
References Song::GetDisplaySubTitle().
Referenced by LunaSong().
GetFirstBeat()
static int LunaSong::GetFirstBeat (T * p, lua_State * L) inline static
References Song::GetFirstBeat().
Referenced by LunaSong().
GetFirstSecond()
static int LunaSong::GetFirstSecond (T * p, lua_State * L) inline static
References Song::GetFirstSecond().
Referenced by LunaSong().
GetGenre()
static int LunaSong::GetGenre (T * p, lua_State * L) inline static
References Song::m_sGenre.
Referenced by LunaSong().
GetGroupName()
static int LunaSong::GetGroupName (T * p, lua_State * L) inline static
References Song::m_sGroupName.
Referenced by LunaSong().
GetJacketPath()
static int LunaSong::GetJacketPath (T * p, lua_State * L) inline static
References Song::GetJacketPath().
Referenced by LunaSong().
GetLastBeat()
static int LunaSong::GetLastBeat (T * p, lua_State * L) inline static
References Song::GetLastBeat().
Referenced by LunaSong().
GetLastSecond()
static int LunaSong::GetLastSecond (T * p, lua_State * L) inline static
References Song::GetLastSecond().
Referenced by LunaSong().
GetLyricsPath()
static int LunaSong::GetLyricsPath (T * p, lua_State * L) inline static
References Song::GetLyricsPath().
Referenced by LunaSong().
GetMainTitle()
static int LunaSong::GetMainTitle (T * p, lua_State * L) inline static
References Song::GetMainTitle().
Referenced by LunaSong().
GetMusicPath()
static int LunaSong::GetMusicPath (T * p, lua_State * L) inline static
References Song::GetMusicPath().
Referenced by LunaSong().
GetOneSteps()
static int LunaSong::GetOneSteps (T * p, lua_State * L) inline static
References SongUtil::GetOneSteps(), and L.
Referenced by LunaSong().
GetOrigin()
static int LunaSong::GetOrigin (T * p, lua_State * L) inline static
References Song::m_sOrigin.
Referenced by LunaSong().
GetOrTryAtLeastToGetSimfileAuthor()
static int LunaSong::GetOrTryAtLeastToGetSimfileAuthor (T * p, lua_State * L) inline static
References Song::GetOrTryAtLeastToGetSimfileAuthor().
Referenced by LunaSong().
GetPreviewMusicPath()
static int LunaSong::GetPreviewMusicPath (T * p, lua_State * L) inline static
References Song::GetPreviewMusicPath().
Referenced by LunaSong().
GetPreviewVidPath()
static int LunaSong::GetPreviewVidPath (T * p, lua_State * L) inline static
References Song::GetPreviewVidPath().
Referenced by LunaSong().
GetSampleLength()
static int LunaSong::GetSampleLength (T * p, lua_State * L) inline static
References Song::m_fMusicSampleLengthSeconds.
Referenced by LunaSong().
GetSampleStart()
static int LunaSong::GetSampleStart (T * p, lua_State * L) inline static
References Song::GetPreviewStartSeconds().
Referenced by LunaSong().
GetSongDir()
static int LunaSong::GetSongDir (T * p, lua_State * L) inline static
References Song::GetSongDir().
Referenced by LunaSong().
GetSongFilePath()
static int LunaSong::GetSongFilePath (T * p, lua_State * L) inline static
References Song::GetSongFilePath().
Referenced by LunaSong().
GetStepsByStepsType()
static int LunaSong::GetStepsByStepsType (T * p, lua_State * L) inline static
References Song::GetStepsByStepsType(), and L.
Referenced by LunaSong().
GetStepsSeconds()
static int LunaSong::GetStepsSeconds (T * p, lua_State * L) inline static
References Song::GetStepsSeconds().
Referenced by LunaSong().
GetTimingData()
static int LunaSong::GetTimingData (T * p, lua_State * L) inline static
References Song::m_SongTiming, and TimingData::PushSelf().
Referenced by LunaSong().
GetTranslitArtist()
static int LunaSong::GetTranslitArtist (T * p, lua_State * L) inline static
References Song::GetTranslitArtist().
Referenced by LunaSong().
GetTranslitFullTitle()
static int LunaSong::GetTranslitFullTitle (T * p, lua_State * L) inline static
References Song::GetTranslitFullTitle().
Referenced by LunaSong().
GetTranslitMainTitle()
static int LunaSong::GetTranslitMainTitle (T * p, lua_State * L) inline static
References Song::GetTranslitMainTitle().
Referenced by LunaSong().
GetTranslitSubTitle()
static int LunaSong::GetTranslitSubTitle (T * p, lua_State * L) inline static
References Song::GetTranslitSubTitle().
Referenced by LunaSong().
HasAttacks()
static int LunaSong::HasAttacks (T * p, lua_State * L) inline static
Referenced by LunaSong().
HasBackground()
static int LunaSong::HasBackground (T * p, lua_State * L) inline static
References Song::HasBackground().
Referenced by LunaSong().
HasBanner()
static int LunaSong::HasBanner (T * p, lua_State * L) inline static
References Song::HasBanner().
Referenced by LunaSong().
HasBGChanges()
static int LunaSong::HasBGChanges (T * p, lua_State * L) inline static
References Song::HasBGChanges().
Referenced by LunaSong().
HasCDImage()
static int LunaSong::HasCDImage (T * p, lua_State * L) inline static
References Song::HasCDImage().
Referenced by LunaSong().
HasCDTitle()
static int LunaSong::HasCDTitle (T * p, lua_State * L) inline static
References Song::HasCDTitle().
Referenced by LunaSong().
HasDisc()
static int LunaSong::HasDisc (T * p, lua_State * L) inline static
References Song::HasDisc().
Referenced by LunaSong().
HasEdits()
static int LunaSong::HasEdits (T * p, lua_State * L) inline static
References Song::HasEdits(), and L.
Referenced by LunaSong().
HasJacket()
static int LunaSong::HasJacket (T * p, lua_State * L) inline static
References Song::HasJacket().
Referenced by LunaSong().
HasLyrics()
static int LunaSong::HasLyrics (T * p, lua_State * L) inline static
References Song::HasLyrics().
Referenced by LunaSong().
HasMusic()
static int LunaSong::HasMusic (T * p, lua_State * L) inline static
References Song::HasMusic().
Referenced by LunaSong().
HasPreviewVid()
static int LunaSong::HasPreviewVid (T * p, lua_State * L) inline static
References Song::HasPreviewVid().
Referenced by LunaSong().
HasSignificantBPMChangesOrStops()
static int LunaSong::HasSignificantBPMChangesOrStops (T * p, lua_State * L) inline static
References Song::HasSignificantBpmChangesOrStops().
Referenced by LunaSong().
HasStepsType()
static int LunaSong::HasStepsType (T * p, lua_State * L) inline static
References Song::HasStepsType(), and L.
Referenced by LunaSong().
HasStepsTypeAndDifficulty()
static int LunaSong::HasStepsTypeAndDifficulty (T * p, lua_State * L) inline static
References Song::HasStepsTypeAndDifficulty(), and L.
Referenced by LunaSong().
IsDisplayBpmConstant()
static int LunaSong::IsDisplayBpmConstant (T * p, lua_State * L) inline static
References DisplayBpms::BpmIsConstant(), and Song::GetDisplayBpms().
Referenced by LunaSong().
IsDisplayBpmRandom()
static int LunaSong::IsDisplayBpmRandom (T * p, lua_State * L) inline static
References DISPLAY_BPM_RANDOM, and Song::m_DisplayBPMType.
Referenced by LunaSong().
IsDisplayBpmSecret()
static int LunaSong::IsDisplayBpmSecret (T * p, lua_State * L) inline static
References Song::GetDisplayBpms(), and DisplayBpms::IsSecret().
Referenced by LunaSong().
IsEasy()
static int LunaSong::IsEasy (T * p, lua_State * L) inline static
References Song::IsEasy(), and L.
Referenced by LunaSong().
IsEnabled()
static int LunaSong::IsEnabled (T * p, lua_State * L) inline static
References Song::GetEnabled().
Referenced by LunaSong().
IsFavorited()
static int LunaSong::IsFavorited (T * p, lua_State * L) inline static
References Song::IsFavorited().
Referenced by LunaSong().
IsLong()
static int LunaSong::IsLong (T * p, lua_State * L) inline static
References Song::IsLong().
Referenced by LunaSong().
IsMarathon()
static int LunaSong::IsMarathon (T * p, lua_State * L) inline static
References Song::IsMarathon().
Referenced by LunaSong().
IsStepsUsingDifferentTiming()
static int LunaSong::IsStepsUsingDifferentTiming (T * p, lua_State * L) inline static
References Song::IsStepsUsingDifferentTiming().
Referenced by LunaSong().
IsTutorial()
static int LunaSong::IsTutorial (T * p, lua_State * L) inline static
References Song::IsTutorial().
Referenced by LunaSong().
MusicLengthSeconds()
static int LunaSong::MusicLengthSeconds (T * p, lua_State * L) inline static
References Song::m_fMusicLengthSeconds.
Referenced by LunaSong().
ReloadFromSongDir()
static int LunaSong::ReloadFromSongDir (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Song::ReloadFromSongDir().
Referenced by LunaSong().
ShowInDemonstrationAndRanking()
static int LunaSong::ShowInDemonstrationAndRanking (T * p, lua_State * L) inline static
References Song::ShowInDemonstrationAndRanking().
Referenced by LunaSong().
The documentation for this class was generated from the following file:
Song.cpp