Etterna: MusicWheel.cpp File Reference
MusicWheel.cpp File Reference
#include "global.h"
#include "MusicWheel.h"
#include "ActorUtil.h"
#include "CommonMetrics.h"
#include "FilterManager.h"
#include "Foreach.h"
#include "GameCommand.h"
#include "GameManager.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "MessageManager.h"
#include "NetworkSyncManager.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "RageString.h"
#include "RageUtil.h"
#include "ScreenManager.h"
#include "Song.h"
#include "SongManager.h"
#include "SongUtil.h"
#include "Style.h"
#include "ThemeManager.h"
#include "LuaBinding.h"
Classes
class LunaMusicWheel
Macros
#define NUM_WHEEL_ITEMS (static_cast<int>(ceil(NUM_WHEEL_ITEMS_TO_DRAW + 2)))
#define WHEEL_TEXT(s) THEME->GetString("MusicWheel", ssprintf("%sText", s.c_str()));
#define CUSTOM_ITEM_WHEEL_TEXT(s) THEME->GetString("MusicWheel", ssprintf("CustomItem%sText", (s).c_str()));
#define NUM_PROBES 1000
Functions
static RString SECTION_COLORS_NAME (size_t i)
static RString CHOICE_NAME (RString s)
static RString CUSTOM_WHEEL_ITEM_NAME (RString s)
static RString CUSTOM_WHEEL_ITEM_COLOR (RString s)
AutoScreenMessage (SM_SongChanged)
AutoScreenMessage (SM_SortOrderChanging)
AutoScreenMessage (SM_SortOrderChanged)
bool contains (string container, string findme)
Variables
static LocalizedString EMPTY_STRING ("MusicWheel", "Empty")
Macro Definition Documentation
CUSTOM_ITEM_WHEEL_TEXT
#define CUSTOM_ITEM_WHEEL_TEXT (s) THEME->GetString("MusicWheel", ssprintf("CustomItem%sText", (s).c_str()));
NUM_PROBES
#define NUM_PROBES 1000
Referenced by MusicWheel::GetPreferredSelectionForRandomOrPortal().
NUM_WHEEL_ITEMS
#define NUM_WHEEL_ITEMS (static_cast<int>(ceil(NUM_WHEEL_ITEMS_TO_DRAW + 2)))
Referenced by RoomWheel::AddItem(), WheelBase::FirstVisibleIndex(), WheelBase::Load(), WheelBase::RebuildWheelItems(), WheelBase::SetItemPosition(), WheelBase::SetPositions(), WheelBase::Update(), and WheelBase::UpdateScrollbar().
WHEEL_TEXT
#define WHEEL_TEXT (s) THEME->GetString("MusicWheel", ssprintf("%sText", s.c_str()));
Referenced by MusicWheel::BuildWheelItemDatas().
Function Documentation
AutoScreenMessage() [1/3]
AutoScreenMessage (SM_SongChanged)
AutoScreenMessage() [2/3]
AutoScreenMessage (SM_SortOrderChanging)
AutoScreenMessage() [3/3]
AutoScreenMessage (SM_SortOrderChanged)
CHOICE_NAME()
static RString CHOICE_NAME (RString s) static
References ssprintf().
Referenced by MusicWheel::Load().
contains()
bool contains (string container, string findme)
Referenced by MusicWheel::FilterBySearch(), and Song::TidyUpData().
CUSTOM_WHEEL_ITEM_COLOR()
static RString CUSTOM_WHEEL_ITEM_COLOR (RString s) static
References ssprintf().
Referenced by MusicWheel::Load().
CUSTOM_WHEEL_ITEM_NAME()
static RString CUSTOM_WHEEL_ITEM_NAME (RString s) static
References ssprintf().
Referenced by MusicWheel::Load().
SECTION_COLORS_NAME()
static RString SECTION_COLORS_NAME (size_t i) static
References ssprintf().
Referenced by MusicWheel::Load().
Variable Documentation
EMPTY_STRING
LocalizedString EMPTY_STRING("MusicWheel", "Empty") static
Referenced by MusicWheel::FilterWheelItemDatas().