Etterna: GrooveRadar.cpp File Reference
GrooveRadar.cpp File Reference
#include "global.h"
#include "GrooveRadar.h"
#include "ActorUtil.h"
#include "RageDisplay.h"
#include "RageMath.h"
#include "RageUtil.h"
#include "Steps.h"
#include "ThemeManager.h"
#include "ThemeMetric.h"
#include "GameState.h"
#include "LuaBinding.h"
Classes
class LunaGrooveRadar
Allow Lua to have access to the GrooveRadar.
Functions
REGISTER_ACTOR_CLASS (GrooveRadar)
static float RADAR_VALUE_ROTATION (int iValueIndex)
Variables
static const ThemeMetric< float > RADAR_EDGE_WIDTH ("GrooveRadar", "EdgeWidth")
static const ThemeMetric< float > RADAR_CENTER_ALPHA ("GrooveRadar", "CenterAlpha")
static const int NUM_SHOWN_RADAR_CATEGORIES = 5
Function Documentation
RADAR_VALUE_ROTATION()
static float RADAR_VALUE_ROTATION (int iValueIndex) static
References PI.
Referenced by GrooveRadar::GrooveRadarValueMap::DrawPrimitives().
REGISTER_ACTOR_CLASS()
REGISTER_ACTOR_CLASS (GrooveRadar)
Variable Documentation
NUM_SHOWN_RADAR_CATEGORIES
const int NUM_SHOWN_RADAR_CATEGORIES = 5 static
Referenced by GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), GrooveRadar::GrooveRadar(), GrooveRadar::GrooveRadarValueMap::GrooveRadarValueMap(), GrooveRadar::GrooveRadarValueMap::SetFromSteps(), and GrooveRadar::GrooveRadarValueMap::SetFromValues().
RADAR_CENTER_ALPHA
const ThemeMetric<float> RADAR_CENTER_ALPHA("GrooveRadar", "CenterAlpha") static
Referenced by GrooveRadar::GrooveRadarValueMap::DrawPrimitives().
RADAR_EDGE_WIDTH
const ThemeMetric<float> RADAR_EDGE_WIDTH("GrooveRadar", "EdgeWidth") static
Referenced by GrooveRadar::GrooveRadarValueMap::DrawPrimitives().