Etterna: ImageCache Class Reference
ImageCache Class Reference
Maintains a cache of reduced-quality banners.
#include <ImageCache.h>
Public Member Functions
ImageCache ()
~ImageCache ()
void ReadFromDisk ()
RageTextureID LoadCachedImage (const std::string &sImageDir, const std::string &sImagePath)
void CacheImage (const std::string &sImageDir, const std::string &sImagePath)
void LoadImage (const std::string &sImageDir, const std::string &sImagePath)
void Demand (const std::string &sImageDir)
void Undemand (const std::string &sImageDir)
void OutputStats () const
Private Member Functions
void UnloadAllImages ()
void CacheImageInternal (const std::string &sImageDir, const std::string &sImagePath)
Static Private Member Functions
static std::string GetImageCachePath (const std::string &sImageDir, const std::string &sImagePath)
Private Attributes
IniFile ImageData
Detailed Description
Maintains a cache of reduced-quality banners.
Constructor & Destructor Documentation
ImageCache()
ImageCache::ImageCache ()
References ReadFromDisk().
~ImageCache()
ImageCache::~ImageCache ()
References UnloadAllImages().
Member Function Documentation
CacheImage()
void ImageCache::CacheImage (const std::string & sImageDir, const std::string & sImagePath)
References CacheImageInternal(), CHECKPOINT_M, DoesFileExist(), GetHashForFile(), GetImageCachePath(), IniFile::GetValue(), ImageData, IMGCACHE_LOW_RES_LOAD_ON_DEMAND, IMGCACHE_LOW_RES_PRELOAD, LoadImage(), PrefsManager::m_bFastLoad, PrefsManager::m_ImageCache, and PREFSMAN.
Referenced by SongManager::DifferentialReloadDir(), SongManager::FinalizeSong(), and SongManager::LoadStepManiaSongDir().
CacheImageInternal()
void ImageCache::CacheImageInternal (const std::string & sImageDir, const std::string & sImagePath) private
References RageSurfaceFormat::BytesPerPixel, closest(), CreateSurface(), RageSurface::fmt, g_bPalettedImageCache, g_ImagePathToImage, GetHashForFile(), GetImageCachePath(), RageSurface::h, IMAGE_CACHE_INDEX, ImageData, IMGCACHE_LOW_RES_PRELOAD, RageSurfaceUtils::LoadFile(), LOG, PrefsManager::m_ImageCache, max(), min(), RageSurfaceUtils::OrderedDither(), RageSurfaceUtils::Palettize(), power_of_two(), PREFSMAN, RageSurfaceUtils::SaveSurface(), IniFile::SetValue(), RageLog::UserLog(), RageSurface::w, IniFile::WriteFile(), and RageSurfaceUtils::Zoom().
Referenced by CacheImage(), and LoadImage().
Demand()
void ImageCache::Demand (const std::string & sImageDir)
References FOREACH_CONST_Child, g_iDemandRefcount, g_ImagePathToImage, GetImageCachePath(), ImageData, IMGCACHE_LOW_RES_LOAD_ON_DEMAND, RageSurfaceUtils::LoadSurface(), PrefsManager::m_ImageCache, and PREFSMAN.
Referenced by ScreenSelectMusic::Init().
GetImageCachePath()
std::string ImageCache::GetImageCachePath (const std::string & sImageDir, const std::string & sImagePath) static private
References SongCacheIndex::GetCacheFilePath().
Referenced by CacheImage(), CacheImageInternal(), Demand(), LoadCachedImage(), and LoadImage().
LoadCachedImage()
RageTextureID ImageCache::LoadCachedImage (const std::string & sImageDir, const std::string & sImagePath)
References ASSERT, g_ImagePathToImage, GetImageCachePath(), IniFile::GetValue(), ImageData, IMGCACHE_OFF, RageTextureManager::IsTextureRegistered(), LOG, PrefsManager::m_ImageCache, PREFSMAN, RageTextureManager::RegisterTexture(), Sprite::SongBannerTexture(), RageTextureID::TEX_VOLATILE, TEXTUREMAN, RageTextureManager::UnloadTexture(), RageLog::UserLog(), and RageLog::Warn().
Referenced by Sprite::LoadFromCached(), Banner::LoadFromCachedBanner(), and FadingBanner::LoadFromCachedBanner().
LoadImage()
void ImageCache::LoadImage (const std::string & sImageDir, const std::string & sImagePath)
References CacheImageInternal(), CHECKPOINT_M, g_ImagePathToImage, GetImageCachePath(), IMGCACHE_LOW_RES_LOAD_ON_DEMAND, IMGCACHE_LOW_RES_PRELOAD, RageSurfaceUtils::LoadSurface(), PrefsManager::m_ImageCache, PREFSMAN, and ssprintf().
Referenced by CacheImage(), Song::FinalizeLoading(), and Song::TidyUpData().
OutputStats()
void ImageCache::OutputStats () const
References FOREACHM_CONST, g_ImagePathToImage, RageSurface::h, RageLog::Info(), LOG, and RageSurface::pitch.
ReadFromDisk()
void ImageCache::ReadFromDisk ()
References SpecialFiles::CACHE_DIR, EmptyDir(), IniFile::GetValue(), IMAGE_CACHE_INDEX, IMAGE_CACHE_VERSION, ImageData, CommonMetrics::IMAGES_TO_CACHE, LOG, IniFile::ReadFile(), IniFile::SetValue(), split(), RageLog::Trace(), and IniFile::WriteFile().
Referenced by ImageCache().
Undemand()
void ImageCache::Undemand (const std::string & sImageDir)
References g_iDemandRefcount, IMGCACHE_LOW_RES_LOAD_ON_DEMAND, PrefsManager::m_ImageCache, PREFSMAN, and UnloadAllImages().
Referenced by ScreenSelectMusic::~ScreenSelectMusic().
UnloadAllImages()
void ImageCache::UnloadAllImages () private
References FOREACHM, and g_ImagePathToImage.
Referenced by Undemand(), and ~ImageCache().
Member Data Documentation
ImageData
IniFile ImageCache::ImageData private
Referenced by CacheImage(), CacheImageInternal(), Demand(), LoadCachedImage(), and ReadFromDisk().
The documentation for this class was generated from the following files:
ImageCache.h
ImageCache.cpp