Etterna: InputHandler_Linux_tty Class Reference
InputHandler_Linux_tty Class Reference
#include <InputHandler_Linux_tty.h>
Public Member Functions
void Update ()
InputHandler_Linux_tty ()
~InputHandler_Linux_tty ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual bool DevicesChanged ()
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Private Member Functions
static void OnCrash (int)
Private Attributes
int fd
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_Linux_tty()
InputHandler_Linux_tty::InputHandler_Linux_tty ()
References fd, keys, OnCrash(), saved_kbd_mode, saved_kbd_termios, SCANCODE_BREAK, SCANCODE_BREAK_ALTERNATIVE, SCANCODE_LEFTCONTROL, SCANCODE_LEFTSHIFT, SCANCODE_LEFTWIN, SCANCODE_PRINTSCREEN, SCANCODE_RIGHTCONTROL, SCANCODE_RIGHTSHIFT, SCANCODE_RIGHTWIN, and RageException::Throw().
~InputHandler_Linux_tty()
InputHandler_Linux_tty::~InputHandler_Linux_tty ()
References fd, LOG, saved_kbd_mode, saved_kbd_termios, and RageLog::Trace().
Member Function Documentation
GetDevicesAndDescriptions()
void InputHandler_Linux_tty::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References DEVICE_KEYBOARD.
OnCrash()
void InputHandler_Linux_tty::OnCrash (int signo) static private
References handler.
Referenced by InputHandler_Linux_tty().
Update()
void InputHandler_Linux_tty::Update () virtual
Reimplemented from InputHandler.
References InputHandler::ButtonPressed(), DEVICE_KEYBOARD, fd, keys, and InputHandler::UpdateTimer().
Member Data Documentation
fd
int InputHandler_Linux_tty::fd private
Referenced by InputHandler_Linux_tty(), Update(), and ~InputHandler_Linux_tty().
The documentation for this class was generated from the following files:
InputHandler_Linux_tty.h
InputHandler_Linux_tty.cpp