Etterna: TimingSegment Struct Reference
TimingSegment Struct Reference abstract
The base timing segment for make glorious benefit wolfman XXX: this should be an abstract class.
#include <TimingSegments.h>
Public Member Functions
virtual TimingSegmentType GetType () const
virtual SegmentEffectType GetEffectType () const
virtual TimingSegment * Copy () const =0
virtual bool IsNotable () const =0
virtual void DebugPrint () const
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
virtual RString ToString (int) const
virtual vector< float > GetValues () const
bool operator< (const TimingSegment &other) const
virtual bool operator== (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Static Public Attributes
static const double EPSILON = 1e-6
Private Attributes
int m_iStartRow
The row in which this segment activates.
Detailed Description
The base timing segment for make glorious benefit wolfman XXX: this should be an abstract class.
Constructor & Destructor Documentation
TimingSegment() [1/3]
TimingSegment::TimingSegment (int iRow = ROW_INVALID) inline
TimingSegment() [2/3]
TimingSegment::TimingSegment (float fBeat) inline
TimingSegment() [3/3]
TimingSegment::TimingSegment (const TimingSegment & other) inline
~TimingSegment()
virtual TimingSegment::~TimingSegment () virtual default
Member Function Documentation
Copy()
virtual TimingSegment* TimingSegment::Copy () const pure virtual
Implemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
Referenced by TimingData::AddSegment(), and TimingData::CopyRange().
DebugPrint()
void TimingSegment::DebugPrint () const virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
References GetBeat(), GetRow(), LOG, and RageLog::Trace().
Referenced by TimingData::AddSegment(), and EraseSegment().
GetBeat()
float TimingSegment::GetBeat () const inline
References m_iStartRow, and NoteRowToBeat().
Referenced by DebugPrint(), FakeSegment::DebugPrint(), WarpSegment::DebugPrint(), TickcountSegment::DebugPrint(), ComboSegment::DebugPrint(), LabelSegment::DebugPrint(), BPMSegment::DebugPrint(), TimeSignatureSegment::DebugPrint(), SpeedSegment::DebugPrint(), ScrollSegment::DebugPrint(), StopSegment::DebugPrint(), DelaySegment::DebugPrint(), GenerateCacheDataStructure(), TimingData::GetBeatInternal(), TimingData::GetDisplayedSpeedPercent(), TimingData::GetElapsedTimeInternal(), TimingData::IsFakeAtRow(), TimingData::IsWarpAtRow(), FakeSegment::Scale(), WarpSegment::Scale(), SpeedSegment::Scale(), Serialize(), ToString(), FakeSegment::ToString(), WarpSegment::ToString(), TickcountSegment::ToString(), ComboSegment::ToString(), LabelSegment::ToString(), BPMSegment::ToString(), TimeSignatureSegment::ToString(), SpeedSegment::ToString(), ScrollSegment::ToString(), StopSegment::ToString(), DelaySegment::ToString(), and WriteGlobalTags().
GetEffectType()
virtual SegmentEffectType TimingSegment::GetEffectType () const inline virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
References SegmentEffectType_Invalid.
Referenced by TimingData::AddSegment(), TimingData::DeleteRows(), and TimingData::GetSegmentAtRow().
GetRow()
int TimingSegment::GetRow () const inline
References m_iStartRow.
Referenced by TimingData::AddSegment(), AdjustSync::AutosyncTempo(), DebugPrint(), FakeSegment::DebugPrint(), WarpSegment::DebugPrint(), TickcountSegment::DebugPrint(), ComboSegment::DebugPrint(), LabelSegment::DebugPrint(), BPMSegment::DebugPrint(), TimeSignatureSegment::DebugPrint(), SpeedSegment::DebugPrint(), ScrollSegment::DebugPrint(), StopSegment::DebugPrint(), DelaySegment::DebugPrint(), TimingData::DeleteRows(), NoteField::DrawPrimitives(), TimingData::GetSegmentAtRow(), NoteDataUtil::GetTotalHoldTicks(), TimingData::InsertRows(), SongCacheIndex::InsertStepsTimingData(), BackgroundImpl::LoadFromRandom(), TimingData::MultiplyBPMInBeatRange(), TimingData::NoteRowToMeasureAndBeat(), operator<(), operator==(), Scale(), TimingData::ScaleRegion(), NotesWriterDWI::Write(), and WriteGlobalTags().
GetType()
virtual TimingSegmentType TimingSegment::GetType () const inline virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
References TimingSegmentType_Invalid.
Referenced by TimingData::AddSegment(), Deserialize(), FakeSegment::operator==(), WarpSegment::operator==(), TickcountSegment::operator==(), ComboSegment::operator==(), LabelSegment::operator==(), BPMSegment::operator==(), TimeSignatureSegment::operator==(), SpeedSegment::operator==(), ScrollSegment::operator==(), StopSegment::operator==(), DelaySegment::operator==(), Serialize(), and ToDerived().
GetValues()
virtual vector<float> TimingSegment::GetValues () const inline virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
IsNotable()
virtual bool TimingSegment::IsNotable () const pure virtual
Implemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
Referenced by TimingData::AddSegment().
operator!=()
virtual bool TimingSegment::operator!= (const TimingSegment & other) const inline virtual
References operator==().
operator<()
bool TimingSegment::operator< (const TimingSegment & other) const inline
References GetRow().
operator==()
virtual bool TimingSegment::operator== (const TimingSegment & other) const inline virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
References GetRow().
Referenced by operator!=().
Scale()
void TimingSegment::Scale (int start, int length, int newLength) virtual
Scales itself.
Parameters
start Starting row
length Length in rows
newLength The new length in rows
Reimplemented in SpeedSegment, WarpSegment, and FakeSegment.
References GetRow(), ScalePosition(), and SetRow().
Referenced by FakeSegment::Scale(), WarpSegment::Scale(), and SpeedSegment::Scale().
SetBeat()
void TimingSegment::SetBeat (float fBeat) inline
References BeatToNoteRow(), and SetRow().
SetRow()
void TimingSegment::SetRow (int iRow) inline
References m_iStartRow.
Referenced by TimingData::AddSegment(), TimingData::CopyRange(), TimingData::DeleteRows(), TimingData::InsertRows(), Scale(), and SetBeat().
ToString()
virtual RString TimingSegment::ToString (int) const inline virtual
Reimplemented in DelaySegment, StopSegment, ScrollSegment, SpeedSegment, TimeSignatureSegment, BPMSegment, LabelSegment, ComboSegment, TickcountSegment, WarpSegment, and FakeSegment.
References FloatToString(), and GetBeat().
Member Data Documentation
EPSILON
const double TimingSegment::EPSILON = 1e-6 static
m_iStartRow
int TimingSegment::m_iStartRow private
The row in which this segment activates.
Referenced by GetBeat(), GetRow(), and SetRow().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp