Etterna: NoteSkinManager Class Reference
NoteSkinManager Class Reference
Loads note skins.
#include <NoteSkinManager.h>
Public Member Functions
NoteSkinManager ()
~NoteSkinManager ()
void RefreshNoteSkinData (const Game *game)
void GetNoteSkinNames (const Game *game, vector< RString > &AddTo)
void GetNoteSkinNames (vector< RString > &AddTo)
bool NoteSkinNameInList (const RString &name, const vector< RString > &name_list)
bool DoesNoteSkinExist (const RString &sNoteSkin)
bool DoNoteSkinsExistForGame (const Game *pGame)
RString GetDefaultNoteSkinName ()
void ValidateNoteSkinName (RString &name)
void SetCurrentNoteSkin (const RString &sNoteSkin)
const RString & GetCurrentNoteSkin ()
void SetLastSeenColor (RString Color)
RString GetLastSeenColor ()
void SetPlayerNumber (PlayerNumber pn)
void SetGameController (GameController gc)
RString GetPath (const RString &sButtonName, const RString &sElement)
bool PushActorTemplate (Lua *L, const RString &sButton, const RString &sElement, bool bSpriteOnly, RString Color)
Actor * LoadActor (const RString &sButton, const RString &sElement, Actor *pParent=NULL, bool bSpriteOnly=false, RString Color="4th")
RString GetMetric (const RString &sButtonName, const RString &sValue)
int GetMetricI (const RString &sButtonName, const RString &sValueName)
float GetMetricF (const RString &sButtonName, const RString &sValueName)
bool GetMetricB (const RString &sButtonName, const RString &sValueName)
apActorCommands GetMetricA (const RString &sButtonName, const RString &sValueName)
void PushSelf (lua_State *L)
Protected Member Functions
RString GetPathFromDirAndFile (const RString &sDir, const RString &sFileName)
void GetAllNoteSkinNamesForGame (const Game *pGame, vector< RString > &AddTo)
bool LoadNoteSkinData (const RString &sNoteSkinName, NoteSkinData &data_out)
bool LoadNoteSkinDataRecursive (const RString &sNoteSkinName, NoteSkinData &data_out)
Protected Attributes
RString m_sCurrentNoteSkin
const Game * m_pCurGame
RString LastColor
PlayerNumber m_PlayerNumber
GameController m_GameController
Detailed Description
Loads note skins.
Constructor & Destructor Documentation
NoteSkinManager()
NoteSkinManager::NoteSkinManager ()
References GameController_Invalid, LuaManager::Get(), L, LUA, m_GameController, m_pCurGame, m_PlayerNumber, PlayerNumber_Invalid, PushSelf(), and LuaManager::Release().
~NoteSkinManager()
NoteSkinManager::~NoteSkinManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
DoesNoteSkinExist()
bool NoteSkinManager::DoesNoteSkinExist (const RString & sNoteSkin)
References GAMESTATE, GetAllNoteSkinNamesForGame(), GameState::m_pCurGame, and NoteSkinNameInList().
Referenced by LunaNoteSkinManager::DoesNoteSkinExist(), PlayerOptions::FromOneModString(), LunaPlayerOptions::NoteSkin(), PlayerOptions::operator=(), and ValidateNoteSkinName().
DoNoteSkinsExistForGame()
bool NoteSkinManager::DoNoteSkinsExistForGame (const Game * pGame)
References GetAllNoteSkinNamesForGame().
Referenced by GameManager::IsGameEnabled().
GetAllNoteSkinNamesForGame()
void NoteSkinManager::GetAllNoteSkinNamesForGame (const Game * pGame, vector< RString > & AddTo) protected
References GetDirListing(), m_pCurGame, Game::m_szName, SpecialFiles::NOTESKINS_DIR, StripCvsAndSvn(), and StripMacResourceForks().
Referenced by DoesNoteSkinExist(), DoNoteSkinsExistForGame(), GetDefaultNoteSkinName(), and GetNoteSkinNames().
GetCurrentNoteSkin()
const RString& NoteSkinManager::GetCurrentNoteSkin () inline
References m_sCurrentNoteSkin.
Referenced by LockNoteSkin::LockNoteSkin(), and MakeNoteResource().
GetDefaultNoteSkinName()
RString NoteSkinManager::GetDefaultNoteSkinName ()
References GAMESTATE, GetAllNoteSkinNamesForGame(), ThemeManager::GetMetric(), GameState::m_pCurGame, NoteSkinNameInList(), and THEME.
Referenced by PlayerOptions::FromOneModString(), and ValidateNoteSkinName().
GetLastSeenColor()
RString NoteSkinManager::GetLastSeenColor () inline
References LastColor.
Referenced by GhostArrowRow::DidHoldNote(), GhostArrowRow::DidTapNote(), and ReceptorArrow::Step().
GetMetric()
RString NoteSkinManager::GetMetric (const RString & sButtonName, const RString & sValue)
References ASSERT_M, m_sCurrentNoteSkin, StdString::CStdStr< CT >::MakeLower(), and LuaHelpers::ReportScriptError().
Referenced by GetMetricA(), GetMetricB(), GetMetricF(), GetMetricI(), and NoteMetricCache_t::Load().
GetMetricA()
apActorCommands NoteSkinManager::GetMetricA (const RString & sButtonName, const RString & sValueName)
References GetMetric(), and ActorUtil::ParseActorCommands().
Referenced by LunaNoteSkinManager::GetMetricA().
GetMetricB()
bool NoteSkinManager::GetMetricB (const RString & sButtonName, const RString & sValueName)
References GetMetric(), and StringToInt().
Referenced by NoteMetricCache_t::Load().
GetMetricF()
float NoteSkinManager::GetMetricF (const RString & sButtonName, const RString & sValueName)
References GetMetric(), and StringToFloat().
Referenced by NoteMetricCache_t::Load().
GetMetricI()
int NoteSkinManager::GetMetricI (const RString & sButtonName, const RString & sValueName)
References GetMetric(), and StringToInt().
Referenced by NoteMetricCache_t::Load().
GetNoteSkinNames() [1/2]
void NoteSkinManager::GetNoteSkinNames (const Game * game, vector< RString > & AddTo)
References GetAllNoteSkinNamesForGame().
Referenced by DefaultNoteSkinChoices(), GetNoteSkinNames(), LunaNoteSkinManager::GetNoteSkinNames(), and OptionRowHandlerListNoteSkins::LoadInternal().
GetNoteSkinNames() [2/2]
void NoteSkinManager::GetNoteSkinNames (vector< RString > & AddTo)
References GAMESTATE, GetNoteSkinNames(), and GameState::m_pCurGame.
GetPath()
RString NoteSkinManager::GetPath (const RString & sButtonName, const RString & sElement)
References ASSERT, FILEMAN, RageFileManager::FlushDirCache(), FOREACH_CONST, g_PathCache, GetExtension(), GetFileContents(), GetPathFromDirAndFile(), m_sCurrentNoteSkin, StdString::CStdStr< CT >::MakeLower(), LuaHelpers::ReportScriptError(), ssprintf(), and RageException::Throw().
GetPathFromDirAndFile()
RString NoteSkinManager::GetPathFromDirAndFile (const RString & sDir, const RString & sFileName) protected
References GetDirListing(), Rage::join(), and LuaHelpers::ReportScriptError().
Referenced by GetPath().
LoadActor()
Actor * NoteSkinManager::LoadActor (const RString & sButton, const RString & sElement, Actor * pParent = NULL, bool bSpriteOnly = false, RString Color = "4th")
References LuaManager::Get(), L, ActorUtil::LoadFromNode(), LUA, m_sCurrentNoteSkin, Sprite::NewBlankSprite(), PushActorTemplate(), LuaManager::Release(), LuaHelpers::ReportScriptErrorFmt(), and XmlFileUtil::XNodeFromTable().
Referenced by ReceptorArrow::Load(), GhostArrowRow::Load(), and MakeNoteResource().
LoadNoteSkinData()
bool NoteSkinManager::LoadNoteSkinData (const RString & sNoteSkinName, NoteSkinData & data_out) protected
References XNode::Clear(), LoadNoteSkinDataRecursive(), NoteSkinData::metrics, NoteSkinData::sName, and NoteSkinData::vsDirSearchOrder.
Referenced by RefreshNoteSkinData().
LoadNoteSkinDataRecursive()
bool NoteSkinManager::LoadNoteSkinDataRecursive (const RString & sNoteSkinName, NoteSkinData & data_out) protected
References StdString::CStdStr< CT >::CompareNoCase(), FILEMAN, GAME_BASE_NOTESKIN_NAME, GAME_COMMON_NOTESKIN_NAME, LuaManager::Get(), ThemeManager::GetCurThemeDir(), GetFileContents(), IniFile::GetValue(), GLOBAL_BASE_DIR, RageFileManager::IsADirectory(), RageFileManager::IsAFile(), L, LOG, LUA, NoteSkinData::m_Loader, m_pCurGame, Game::m_szName, XmlFileUtil::MergeIniUnder(), NoteSkinData::metrics, SpecialFiles::NOTESKINS_DIR, LuaReference::PushSelf(), IniFile::ReadFile(), LuaManager::Release(), LuaHelpers::ReportScriptError(), LuaHelpers::RunScript(), LuaReference::SetFromStack(), NoteSkinData::sName, THEME, RageLog::Trace(), and NoteSkinData::vsDirSearchOrder.
Referenced by LoadNoteSkinData().
NoteSkinNameInList()
bool NoteSkinManager::NoteSkinNameInList (const RString & name, const vector< RString > & name_list)
Referenced by DoesNoteSkinExist(), and GetDefaultNoteSkinName().
PushActorTemplate()
bool NoteSkinManager::PushActorTemplate (Lua * L, const RString & sButton, const RString & sElement, bool bSpriteOnly, RString Color)
References LuaReference::Create(), LuaReference::IsNil(), ActorUtil::LoadTableFromStackShowErrors(), m_GameController, NoteSkinData::m_Loader, m_PlayerNumber, m_sCurrentNoteSkin, LuaReference::PushSelf(), and LuaHelpers::ReportScriptError().
Referenced by LoadActor(), and LunaNoteSkinManager::LoadActor().
PushSelf()
void NoteSkinManager::PushSelf (lua_State * L)
Referenced by NoteSkinManager().
RefreshNoteSkinData()
void NoteSkinManager::RefreshNoteSkinData (const Game * game)
References g_PathCache, ThemeManager::GetCurThemeDir(), GetDirListing(), LoadNoteSkinData(), m_pCurGame, Game::m_szName, StdString::CStdStr< CT >::MakeLower(), SpecialFiles::NOTESKINS_DIR, StripCvsAndSvn(), StripMacResourceForks(), and THEME.
Referenced by DebugLineReloadTheme::DoAndLog(), HandleGlobalInputs(), LunaGameState::RefreshNoteSkinData(), and GameState::Reset().
SetCurrentNoteSkin()
void NoteSkinManager::SetCurrentNoteSkin (const RString & sNoteSkin) inline
References m_sCurrentNoteSkin.
Referenced by LockNoteSkin::LockNoteSkin(), and LockNoteSkin::~LockNoteSkin().
SetGameController()
void NoteSkinManager::SetGameController (GameController gc) inline
References m_GameController.
Referenced by ReceptorArrow::Load(), GhostArrowRow::Load(), and MakeNoteResource().
SetLastSeenColor()
void NoteSkinManager::SetLastSeenColor (RString Color) inline
References LastColor.
Referenced by Player::Step().
SetPlayerNumber()
void NoteSkinManager::SetPlayerNumber (PlayerNumber pn) inline
References m_PlayerNumber.
Referenced by ReceptorArrow::Load(), GhostArrowRow::Load(), and MakeNoteResource().
ValidateNoteSkinName()
void NoteSkinManager::ValidateNoteSkinName (RString & name)
References DoesNoteSkinExist(), GetDefaultNoteSkinName(), and LuaHelpers::ReportScriptError().
Referenced by NoteField::CacheAllUsedNoteSkins().
Member Data Documentation
LastColor
RString NoteSkinManager::LastColor protected
Referenced by GetLastSeenColor(), and SetLastSeenColor().
m_GameController
GameController NoteSkinManager::m_GameController protected
Referenced by NoteSkinManager(), PushActorTemplate(), and SetGameController().
m_pCurGame
const Game* NoteSkinManager::m_pCurGame protected
Referenced by GetAllNoteSkinNamesForGame(), LoadNoteSkinDataRecursive(), NoteSkinManager(), and RefreshNoteSkinData().
m_PlayerNumber
PlayerNumber NoteSkinManager::m_PlayerNumber protected
Referenced by NoteSkinManager(), PushActorTemplate(), and SetPlayerNumber().
m_sCurrentNoteSkin
RString NoteSkinManager::m_sCurrentNoteSkin protected
Referenced by GetCurrentNoteSkin(), GetMetric(), GetPath(), LoadActor(), PushActorTemplate(), and SetCurrentNoteSkin().
The documentation for this class was generated from the following files:
NoteSkinManager.h
NoteSkinManager.cpp