Etterna: MovieDecoder Class Reference
MovieDecoder Class Reference abstract
#include <MovieTexture_Generic.h>
Public Member Functions
virtual ~MovieDecoder ()
virtual RString Open (const RString &sFile)=0
virtual void Close ()=0
virtual void Rewind ()=0
virtual int DecodeFrame (float fTargetTime)=0
virtual void GetFrame (RageSurface *pOut)=0
virtual int GetWidth () const =0
virtual int GetHeight () const =0
virtual float GetSourceAspectRatio () const
virtual RageSurface * CreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, MovieDecoderPixelFormatYCbCr &fmtout)=0
virtual float GetTimestamp () const =0
virtual float GetFrameDuration () const =0
Constructor & Destructor Documentation
~MovieDecoder()
virtual MovieDecoder::~MovieDecoder () inline virtual
Member Function Documentation
Close()
virtual void MovieDecoder::Close () pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::~MovieTexture_Generic().
CreateCompatibleSurface()
virtual RageSurface* MovieDecoder::CreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, MovieDecoderPixelFormatYCbCr & fmtout) pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::CreateTexture().
DecodeFrame()
virtual int MovieDecoder::DecodeFrame (float fTargetTime) pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::DecodeFrame(), and MovieTexture_Generic::Init().
GetFrame()
virtual void MovieDecoder::GetFrame (RageSurface * pOut) pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::UpdateFrame().
GetFrameDuration()
virtual float MovieDecoder::GetFrameDuration () const pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::DecodeFrame().
GetHeight()
virtual int MovieDecoder::GetHeight () const pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::CreateTexture().
GetSourceAspectRatio()
virtual float MovieDecoder::GetSourceAspectRatio () const inline virtual
Referenced by MovieTexture_Generic::CreateTexture().
GetTimestamp()
virtual float MovieDecoder::GetTimestamp () const pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::CheckFrameTime(), and MovieTexture_Generic::DecodeFrame().
GetWidth()
virtual int MovieDecoder::GetWidth () const pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::CreateTexture().
Open()
virtual RString MovieDecoder::Open (const RString & sFile) pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::Init().
Rewind()
virtual void MovieDecoder::Rewind () pure virtual
Implemented in MovieDecoder_FFMpeg.
Referenced by MovieTexture_Generic::DecodeFrame().
The documentation for this class was generated from the following file:
MovieTexture_Generic.h