Etterna: CharacterManager Class Reference
CharacterManager Class Reference
Manage all of the Characters.
#include <CharacterManager.h>
Public Member Functions
CharacterManager ()
Set up the character manager.
~CharacterManager ()
Destroy the character manager.
void GetCharacters (vector< Character *> &vpCharactersOut)
Character * GetRandomCharacter ()
Get one installed character at random.
Character * GetDefaultCharacter ()
Get the character assigned as the default.
Character * GetCharacterFromID (const RString &sCharacterID)
void DemandGraphics ()
void UndemandGraphics ()
void PushSelf (lua_State *L)
Private Attributes
vector< Character * > m_pCharacters
Detailed Description
Manage all of the Characters.
Constructor & Destructor Documentation
CharacterManager()
CharacterManager::CharacterManager ()
Set up the character manager.
References CHARACTERS_DIR, StdString::CStdStr< CT >::CompareNoCase(), LuaManager::Get(), GetDirListing(), L, Character::Load(), LUA, m_pCharacters, StdString::CStdStr< CT >::MakeLower(), PushSelf(), LuaManager::Release(), SAFE_DELETE, splitpath(), StripCvsAndSvn(), StripMacResourceForks(), and RageException::Throw().
~CharacterManager()
CharacterManager::~CharacterManager ()
Destroy the character manager.
References LUA, m_pCharacters, SAFE_DELETE, and LuaManager::UnsetGlobal().
Member Function Documentation
DemandGraphics()
void CharacterManager::DemandGraphics ()
References FOREACH, and m_pCharacters.
GetCharacterFromID()
Character * CharacterManager::GetCharacterFromID (const RString & sCharacterID)
References m_pCharacters.
Referenced by LunaCharacterManager::GetCharacter(), ScreenHowToPlay::Init(), ProfileManager::Init(), and Profile::SetCharacter().
GetCharacters()
void CharacterManager::GetCharacters (vector< Character *> & vpCharactersOut)
References m_pCharacters.
Referenced by ScreenOptionsEditProfile::BeginScreen(), LunaCharacterManager::GetAllCharacters(), Profile::GetCharacter(), LunaCharacterManager::GetCharacterCount(), GetRandomCharacter(), ScreenHowToPlay::Init(), and OptionRowHandlerListCharacters::LoadInternal().
GetDefaultCharacter()
Character * CharacterManager::GetDefaultCharacter ()
Get the character assigned as the default.
Returns
The default character.
References FAIL_M, and m_pCharacters.
Referenced by Profile::GetCharacter(), GetRandomCharacter(), Banner::LoadFallbackCharacterIcon(), and OptionRowHandlerListCharacters::LoadInternal().
GetRandomCharacter()
Character * CharacterManager::GetRandomCharacter ()
Get one installed character at random.
Returns
The random character.
References GetCharacters(), GetDefaultCharacter(), and RandomInt().
Referenced by ProfileManager::CreateLocalProfile(), LunaCharacterManager::GetRandomCharacter(), and ScreenHowToPlay::Init().
PushSelf()
void CharacterManager::PushSelf (lua_State * L)
Referenced by CharacterManager().
UndemandGraphics()
void CharacterManager::UndemandGraphics ()
References FOREACH, and m_pCharacters.
Member Data Documentation
m_pCharacters
vector<Character*> CharacterManager::m_pCharacters private
Referenced by CharacterManager(), DemandGraphics(), GetCharacterFromID(), GetCharacters(), GetDefaultCharacter(), UndemandGraphics(), and ~CharacterManager().
The documentation for this class was generated from the following files:
CharacterManager.h
CharacterManager.cpp