Etterna: DebugLineProfileSlot Class Reference
DebugLineProfileSlot Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineProfileSlot::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), enum_add(), g_ProfileSlot, NUM_ProfileSlot, and ProfileSlot_Player1.
GetDisplayTitle()
RString DebugLineProfileSlot::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and PROFILE.
GetDisplayValue()
RString DebugLineProfileSlot::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References g_ProfileSlot, ProfileSlot_Player1, and ProfileSlot_Player2.
GetPageName()
RString DebugLineProfileSlot::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineProfileSlot::IsEnabled () inline override private virtual
Implements IDebugLine.
References IsSelectProfilePersistent().
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp