Etterna: RageFileManagerReadAhead Namespace Reference
RageFileManagerReadAhead Namespace Reference
Utilities for reading the RageFiles.
Functions
void Init ()
void Shutdown ()
void ReadAhead (RageFileBasic *pFile, int iBytes)
void DiscardCache (RageFileBasic *pFile, int iRelativePosition, int iBytes)
void CacheHintStreaming (RageFileBasic *pFile)
Detailed Description
Utilities for reading the RageFiles.
Function Documentation
CacheHintStreaming()
void RageFileManagerReadAhead::CacheHintStreaming (RageFileBasic * pFile)
References RageFileBasic::GetFD(), RageFileBasic::GetFileSize(), and RageFileBasic::Tell().
Referenced by RageFileDriverReadAhead::FillBuffer(), and RageFileDriverReadAhead::RageFileDriverReadAhead().
DiscardCache()
void RageFileManagerReadAhead::DiscardCache (RageFileBasic * pFile, int iRelativePosition, int iBytes)
Referenced by RageFileDriverReadAhead::ReadInternal().
Init()
void RageFileManagerReadAhead::Init ()
ReadAhead()
void RageFileManagerReadAhead::ReadAhead (RageFileBasic * pFile, int iBytes)
Referenced by RageFileDriverReadAhead::ReadInternal().
Shutdown()
void RageFileManagerReadAhead::Shutdown ()
References window.
Referenced by FindBackBufferType(), HandleException(), ShutdownGame(), LowLevelWindow_Win32::~LowLevelWindow_Win32(), and RageDisplay_D3D::~RageDisplay_D3D().