Etterna: RageCompiledGeometrySWOGL Class Reference
RageCompiledGeometrySWOGL Class Reference
Public Member Functions
void Allocate (const vector< msMesh > &vMeshes) override
void Change (const vector< msMesh > &vMeshes) override
void Draw (int iMeshIndex) const override
Public Member Functions inherited from RageCompiledGeometry
virtual ~RageCompiledGeometry ()
void Set (const vector< msMesh > &vMeshes, bool bNeedsNormals)
Protected Attributes
vector< RageVector3 > m_vPosition
vector< RageVector2 > m_vTexture
vector< RageVector3 > m_vNormal
vector< msTriangle > m_vTriangles
vector< RageVector2 > m_vTexMatrixScale
Protected Attributes inherited from RageCompiledGeometry
vector< MeshInfo > m_vMeshInfo
bool m_bNeedsNormals
bool m_bAnyNeedsTextureMatrixScale
Additional Inherited Members
Protected Member Functions inherited from RageCompiledGeometry
size_t GetTotalVertices () const
size_t GetTotalTriangles () const
Member Function Documentation
Allocate()
void RageCompiledGeometrySWOGL::Allocate (const vector< msMesh > & vMeshes) inline override virtual
Implements RageCompiledGeometry.
Reimplemented in RageCompiledGeometryHWOGL.
References max().
Referenced by RageCompiledGeometryHWOGL::Allocate().
Change()
void RageCompiledGeometrySWOGL::Change (const vector< msMesh > & vMeshes) inline override virtual
Implements RageCompiledGeometry.
Reimplemented in RageCompiledGeometryHWOGL.
References RageCompiledGeometry::MeshInfo::iTriangleStart, RageCompiledGeometry::MeshInfo::iVertexStart, msMesh::Triangles, and msMesh::Vertices.
Referenced by RageCompiledGeometryHWOGL::Change().
Draw()
void RageCompiledGeometrySWOGL::Draw (int iMeshIndex) const inline override virtual
Implements RageCompiledGeometry.
Reimplemented in RageCompiledGeometryHWOGL.
References RageCompiledGeometry::MeshInfo::iTriangleCount, RageCompiledGeometry::MeshInfo::iTriangleStart, RageCompiledGeometry::MeshInfo::m_bNeedsTextureMatrixScale, and TurnOffHardwareVBO().
Member Data Documentation
m_vNormal
vector<RageVector3> RageCompiledGeometrySWOGL::m_vNormal protected
m_vPosition
vector<RageVector3> RageCompiledGeometrySWOGL::m_vPosition protected
m_vTexMatrixScale
vector<RageVector2> RageCompiledGeometrySWOGL::m_vTexMatrixScale protected
m_vTexture
vector<RageVector2> RageCompiledGeometrySWOGL::m_vTexture protected
m_vTriangles
vector<msTriangle> RageCompiledGeometrySWOGL::m_vTriangles protected
The documentation for this class was generated from the following file:
RageDisplay_OGL.cpp