Etterna: DirectFilenameDB Class Reference
DirectFilenameDB Class Reference
#include <RageFileDriverDirectHelpers.h>
Public Member Functions
DirectFilenameDB (const RString &root)
void SetRoot (const RString &root)
void CacheFile (const RString &sPath) override
Public Member Functions inherited from FilenameDB
FilenameDB ()
virtual ~FilenameDB ()
void AddFile (const RString &sPath, int iSize, int iHash, void *pPriv=NULL)
void DelFile (const RString &sPath)
void * GetFilePriv (const RString &sPath)
void GetFilesSimpleMatch (const RString &sDir, const RString &sFile, vector< RString > &asOut, bool bOnlyDirs)
bool ResolvePath (RString &sPath)
RageFileManager::FileType GetFileType (const RString &sPath)
int GetFileSize (const RString &sPath)
int GetFileHash (const RString &sFilePath)
void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
void FlushDirCache (const RString &sDir=RString())
void GetFileSetCopy (const RString &dir, FileSet &out)
Protected Member Functions
void PopulateFileSet (FileSet &fs, const RString &sPath) override
Protected Member Functions inherited from FilenameDB
const File * GetFile (const RString &sPath)
FileSet * GetFileSet (const RString &sDir, bool create=true)
void GetFilesEqualTo (const RString &sDir, const RString &sName, vector< RString > &asOut, bool bOnlyDirs)
void GetFilesMatching (const RString &sDir, const RString &sBeginning, const RString &sContaining, const RString &sEnding, vector< RString > &asOut, bool bOnlyDirs)
void DelFileSet (map< RString, FileSet *>::iterator dir)
Protected Attributes
RString root
Protected Attributes inherited from FilenameDB
RageEvent m_Mutex
map< RString, FileSet * > dirs
int ExpireSeconds { -1 }
Constructor & Destructor Documentation
DirectFilenameDB()
DirectFilenameDB::DirectFilenameDB (const RString & root)
References FilenameDB::ExpireSeconds, and SetRoot().
Member Function Documentation
CacheFile()
void DirectFilenameDB::CacheFile (const RString & sPath) override virtual
Reimplemented from FilenameDB.
References Basename(), CHECKPOINT_M, File::dir, Dirname(), DoFindFirstFile, DoStat, f, FileSet::files, FilenameDB::GetFileSet(), File::hash, FileSet::m_bFilled, FilenameDB::m_Mutex, root, File::size, ssprintf(), RageMutex::Unlock(), RageEvent::Wait(), and WARN.
PopulateFileSet()
void DirectFilenameDB::PopulateFileSet (FileSet & fs, const RString & sPath) override protected virtual
Reimplemented from FilenameDB.
References FileSet::age, BeginsWith(), CHECKPOINT_M, File::dir, DoFindFirstFile, DoStat, f, FileSet::files, FOREACH_CONST, RageTimer::GetDeltaTime(), File::hash, FilenameDB::ResolvePath(), StdString::CStdStr< CT >::Right(), root, File::SetName(), File::size, ssprintf(), and WARN.
SetRoot()
void DirectFilenameDB::SetRoot (const RString & root)
References StdString::CStdStr< CT >::Replace(), StdString::CStdStr< CT >::Right(), and root.
Referenced by DirectFilenameDB().
Member Data Documentation
root
RString DirectFilenameDB::root protected
Referenced by CacheFile(), PopulateFileSet(), and SetRoot().
The documentation for this class was generated from the following files:
RageFileDriverDirectHelpers.h
RageFileDriverDirectHelpers.cpp