Etterna: Font Class Reference
Font Class Reference
#include <Font.h>
Public Member Functions
Font ()
~Font ()
const glyph & GetGlyph (wchar_t c) const
int GetLineWidthInSourcePixels (const wstring &szLine) const
int GetLineHeightInSourcePixels (const wstring &szLine) const
int GetGlyphsThatFit (const wstring &line, int *width) const
bool FontCompleteForString (const wstring &str) const
void AddPage (FontPage *fp)
Add a FontPage to this font.
void MergeFont (Font &f)
Steal all of a font's pages.
void Load (const RString &sFontOrTextureFilePath, const RString &sChars)
void Unload ()
void Reload ()
void CapsOnly ()
int GetHeight () const
int GetCenter () const
int GetLineSpacing () const
void SetDefaultGlyph (FontPage *pPage)
bool IsRightToLeft () const
const RageColor & GetDefaultStrokeColor () const
Public Attributes
int m_iRefCount { 1 }
RString path
Private Member Functions
void LoadFontPageSettings (FontPageSettings &cfg, IniFile &ini, const RString &sTexturePath, const RString &PageName, const RString &sChars)
RString GetPageNameFromFileName (const RString &sFilename)
Font (const Font &rhs)
Font & operator= (const Font &rhs)
Static Private Member Functions
static void GetFontPaths (const RString &sFontOrTextureFilePath, vector< RString > &sTexturePaths)
Private Attributes
vector< FontPage * > m_apPages
List of pages and fonts that we use (and are responsible for freeing).
FontPage * m_pDefault
This is the primary fontpage of this font.
map< wchar_t, glyph * > m_iCharToGlyph
Map from characters to glyphs.
glyph * m_iCharToGlyphCache [128]
Each glyph is part of one of the pages[].
bool m_bRightToLeft { false }
True for Hebrew, Arabic, Urdu fonts.
RageColor m_DefaultStrokeColor
RString m_sChars
We keep this around only for reloading.
Constructor & Destructor Documentation
Font() [1/2]
Font::Font ()
~Font()
Font::~Font ()
References Unload().
Font() [2/2]
Font::Font (const Font & rhs) private
Member Function Documentation
AddPage()
void Font::AddPage (FontPage * fp)
Add a FontPage to this font.
Parameters
fp the FontPage to be added.
References FontPage::m_aGlyphs, m_apPages, m_iCharToGlyph, and FontPage::m_iCharToGlyphNo.
Referenced by Load().
CapsOnly()
void Font::CapsOnly ()
References m_iCharToGlyph.
Referenced by Load().
FontCompleteForString()
bool Font::FontCompleteForString (const wstring & str) const
References FONT_DEFAULT_GLYPH, GetGlyph(), m_iCharToGlyph, path, and RageException::Throw().
Referenced by BitmapText::StringWillUseAlternate().
GetCenter()
int Font::GetCenter () const inline
References FontPage::GetCenter(), and m_pDefault.
GetDefaultStrokeColor()
const RageColor& Font::GetDefaultStrokeColor () const inline
References m_DefaultStrokeColor.
Referenced by BitmapText::LoadFromFont().
GetFontPaths()
void Font::GetFontPaths (const RString & sFontOrTextureFilePath, vector< RString > & sTexturePaths) static private
References GetDirListing(), and SetExtension().
Referenced by Load().
GetGlyph()
const glyph & Font::GetGlyph (wchar_t c) const
References ARRAYLEN, FONT_DEFAULT_GLYPH, m_iCharToGlyph, m_iCharToGlyphCache, path, and RageException::Throw().
Referenced by BitmapText::BuildChars(), FontCompleteForString(), GetGlyphsThatFit(), GetLineHeightInSourcePixels(), and GetLineWidthInSourcePixels().
GetGlyphsThatFit()
int Font::GetGlyphsThatFit (const wstring & line, int * width) const
References GetGlyph(), GetLineWidthInSourcePixels(), and glyph::m_iHadvance.
Referenced by BitmapText::CropLineToWidth().
GetHeight()
int Font::GetHeight () const inline
References FontPage::m_iHeight, and m_pDefault.
Referenced by BitmapText::BuildChars().
GetLineHeightInSourcePixels()
int Font::GetLineHeightInSourcePixels (const wstring & szLine) const
References GetGlyph(), FontPage::m_iHeight, glyph::m_pPage, and max().
GetLineSpacing()
int Font::GetLineSpacing () const inline
References FontPage::m_iLineSpacing, and m_pDefault.
Referenced by BitmapText::BuildChars().
GetLineWidthInSourcePixels()
int Font::GetLineWidthInSourcePixels (const wstring & szLine) const
References GetGlyph(), and glyph::m_iHadvance.
Referenced by BitmapText::BuildChars(), GetGlyphsThatFit(), ColorBitmapText::ResetText(), ColorBitmapText::SetText(), and BitmapText::SetTextInternal().
GetPageNameFromFileName()
RString Font::GetPageNameFromFileName (const RString & sFilename) private
Referenced by Load().
IsRightToLeft()
bool Font::IsRightToLeft () const inline
References m_bRightToLeft.
Referenced by BitmapText::BuildChars().
Load()
void Font::Load (const RString & sFontOrTextureFilePath, const RString & sChars)
References AddPage(), ARRAYLEN, CapsOnly(), CHECKPOINT_M, RageColor::FromString(), GetExtension(), GetFontPaths(), RageTexture::GetNumFrames(), GetPageNameFromFileName(), ThemeManager::GetPathF(), IniFile::GetValue(), Rage::join(), FontPage::Load(), Load(), LoadFontPageSettings(), LoadStack, m_bRightToLeft, m_DefaultStrokeColor, FontPage::m_FontPageTextures, m_iCharToGlyph, m_iCharToGlyphCache, FontPage::m_iCharToGlyphNo, FontPageTextures::m_pTextureMain, m_sChars, MergeFont(), path, IniFile::ReadFile(), IniFile::RenameKey(), LuaHelpers::ReportScriptErrorFmt(), SetDefaultGlyph(), split(), ssprintf(), THEME, WcharDisplayText(), and ZERO.
Referenced by Load(), and Reload().
LoadFontPageSettings()
void Font::LoadFontPageSettings (FontPageSettings & cfg, IniFile & ini, const RString & sTexturePath, const RString & PageName, const RString & sChars) private
References ASSERT, FontPageSettings::CharToGlyphNo, Regex::Compare(), FOREACH_CONST_Attr, FontCharAliases::GetChar(), XNode::GetChild(), RageTexture::GetFrameDimensionsFromFileName(), IniFile::GetPath(), XNodeValue::GetValue(), IniFile::GetValue(), IsAnInt(), IsHexVal(), LOG, FontPageSettings::m_fScaleAllWidthsBy, FontPageSettings::m_iAddToAllWidths, FontPageSettings::m_iAdvanceExtraPixels, FontPageSettings::m_iBaseline, FontPageSettings::m_iDefaultWidth, FontPageSettings::m_iDrawExtraPixelsLeft, FontPageSettings::m_iDrawExtraPixelsRight, FontPageSettings::m_iLineSpacing, FontPageSettings::m_iTop, FontPageSettings::m_mapGlyphWidths, FontPageSettings::m_sTextureHints, FontPageSettings::m_sTexturePath, StdString::CStdStr< CT >::MakeUpper(), FontPageSettings::MapRange(), IniFile::RenameKey(), LuaHelpers::ReportScriptErrorFmt(), RStringToWstring(), StringToInt(), RageLog::Trace(), TrimLeft(), Rage::utf8_get_char(), Rage::utf8_get_char_len(), and RageLog::Warn().
Referenced by Load().
MergeFont()
void Font::MergeFont (Font & f)
Steal all of a font's pages.
Parameters
f the font whose pages we are stealing.
References m_apPages, m_iCharToGlyph, and m_pDefault.
Referenced by Load().
operator=()
Font& Font::operator= (const Font & rhs) private
Reload()
void Font::Reload ()
References Load(), m_sChars, path, LuaHelpers::ReportScriptError(), and Unload().
SetDefaultGlyph()
void Font::SetDefaultGlyph (FontPage * pPage)
References ASSERT, FontPage::m_aGlyphs, m_pDefault, path, and LuaHelpers::ReportScriptErrorFmt().
Referenced by Load().
Unload()
void Font::Unload ()
References m_apPages, m_iCharToGlyph, and m_pDefault.
Referenced by Reload(), and ~Font().
Member Data Documentation
m_apPages
vector<FontPage*> Font::m_apPages private
List of pages and fonts that we use (and are responsible for freeing).
Referenced by AddPage(), MergeFont(), and Unload().
m_bRightToLeft
bool Font::m_bRightToLeft { false } private
True for Hebrew, Arabic, Urdu fonts.
This will also change the way glyphs from the default FontPage are rendered. There may be a better way to handle this.
Referenced by IsRightToLeft(), and Load().
m_DefaultStrokeColor
RageColor Font::m_DefaultStrokeColor private
Referenced by GetDefaultStrokeColor(), and Load().
m_iCharToGlyph
map<wchar_t, glyph*> Font::m_iCharToGlyph private
Map from characters to glyphs.
Referenced by AddPage(), CapsOnly(), FontCompleteForString(), GetGlyph(), Load(), MergeFont(), and Unload().
m_iCharToGlyphCache
glyph* Font::m_iCharToGlyphCache[128] private
Each glyph is part of one of the pages[].
Referenced by GetGlyph(), and Load().
m_iRefCount
int Font::m_iRefCount { 1 }
Referenced by FontManager::CopyFont(), FontManager::LoadFont(), FontManager::UnloadFont(), and FontManager::~FontManager().
m_pDefault
FontPage* Font::m_pDefault private
This is the primary fontpage of this font.
The font-wide height, center, etc. is pulled from it. (This is one of pages[].)
Referenced by GetCenter(), GetHeight(), GetLineSpacing(), MergeFont(), SetDefaultGlyph(), and Unload().
m_sChars
RString Font::m_sChars private
We keep this around only for reloading.
Referenced by Load(), and Reload().
path
RString Font::path
Referenced by FontCompleteForString(), GetGlyph(), Load(), Reload(), SetDefaultGlyph(), and FontManager::UnloadFont().
The documentation for this class was generated from the following files:
Font.h
Font.cpp