Etterna: LunaRageBezier2D Struct Reference
LunaRageBezier2D Struct Reference
Public Member Functions
LunaRageBezier2D ()
Public Member Functions inherited from Luna< RageBezier2D >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int evaluate (T *p, lua_State *L)
static int evaluate_y_from_x (T *p, lua_State *L)
static int get_x (T *p, lua_State *L)
static int get_y (T *p, lua_State *L)
static int set_from_bezier (T *p, lua_State *L)
static int destroy (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageBezier2D >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageBezier2D >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageBezier2D >
using T = RageBezier2D
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageBezier2D >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaRageBezier2D()
LunaRageBezier2D::LunaRageBezier2D () inline
References ADD_METHOD, destroy(), evaluate(), evaluate_y_from_x(), get_x(), get_y(), and set_from_bezier().
Member Function Documentation
destroy()
static int LunaRageBezier2D::destroy (T * p, lua_State * L) inline static
References SAFE_DELETE.
Referenced by LunaRageBezier2D().
evaluate()
static int LunaRageBezier2D::evaluate (T * p, lua_State * L) inline static
References RageBezier2D::Evaluate(), and FArg.
Referenced by LunaRageBezier2D().
evaluate_y_from_x()
static int LunaRageBezier2D::evaluate_y_from_x (T * p, lua_State * L) inline static
References RageBezier2D::EvaluateYFromX(), and FArg.
Referenced by LunaRageBezier2D().
get_x()
static int LunaRageBezier2D::get_x (T * p, lua_State * L) inline static
References RageBezier2D::get_x(), and RageQuadratic::PushSelf().
Referenced by LunaRageBezier2D().
get_y()
static int LunaRageBezier2D::get_y (T * p, lua_State * L) inline static
References RageBezier2D::get_y(), and RageQuadratic::PushSelf().
Referenced by LunaRageBezier2D().
set_from_bezier()
static int LunaRageBezier2D::set_from_bezier (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and RageBezier2D::SetFromBezier().
Referenced by LunaRageBezier2D().
The documentation for this struct was generated from the following file:
RageMath.cpp