Etterna: GameplayAssist Class Reference
GameplayAssist Class Reference
The handclaps and metronomes ready to assist the player.
#include <GameplayAssist.h>
Public Member Functions
void Init ()
Load the sounds.
void PlayTicks (const NoteData &nd, const PlayerState *ps)
Play the sounds in question for the particular chart.
void StopPlaying ()
Stop playing the sounds.
Private Attributes
RageSound m_soundAssistClap
the sound made when a note is to be hit.
RageSound m_soundAssistMetronomeMeasure
the sound made when crossing a new measure.
RageSound m_soundAssistMetronomeBeat
the sound made when crossing a new beat.
Detailed Description
The handclaps and metronomes ready to assist the player.
Member Function Documentation
Init()
void GameplayAssist::Init ()
Load the sounds.
References ThemeManager::GetPathS(), RageSound::Load(), m_soundAssistClap, m_soundAssistMetronomeBeat, m_soundAssistMetronomeMeasure, and THEME.
Referenced by ScreenGameplay::Init().
PlayTicks()
void GameplayAssist::PlayTicks (const NoteData & nd, const PlayerState * ps)
Play the sounds in question for the particular chart.
Parameters
nd the note data used for playing the ticks.
ps the player's state (and number) for Split Timing.
References BeatToNoteRow(), f, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GAMESTATE, TimingData::GetBeatFromElapsedTimeNoOffset(), ModsGroup< T >::GetCurrent(), RageSoundManager::GetPlayLatency(), HealthState_Dead, TimingData::IsJudgableAtRow(), NoteData::IsThereATapOrHoldHeadAtRow(), SongOptions::m_bAssistClap, SongOptions::m_bAssistMetronome, SongOptions::m_fMusicRate, SongPosition::m_fMusicSeconds, PlayerState::m_HealthState, SongPosition::m_LastBeatUpdate, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, PlayerState::m_Position, GameState::m_pPlayerState, GameState::m_SongOptions, m_soundAssistClap, m_soundAssistMetronomeBeat, m_soundAssistMetronomeMeasure, RageSoundParams::m_StartTime, max(), NoteRowToBeat(), TimingData::NoteRowToMeasureAndBeat(), RageSound::Play(), SOUNDMAN, CommonMetrics::TICK_EARLY_SECONDS, and TimingData::WhereUAtBroNoOffset().
Referenced by ScreenGameplay::PlayTicks().
StopPlaying()
void GameplayAssist::StopPlaying ()
Stop playing the sounds.
References m_soundAssistClap, m_soundAssistMetronomeBeat, m_soundAssistMetronomeMeasure, and RageSound::StopPlaying().
Referenced by ScreenGameplay::BeginBackingOutFromGameplay(), ScreenGameplay::HandleScreenMessage(), and ScreenGameplay::~ScreenGameplay().
Member Data Documentation
m_soundAssistClap
RageSound GameplayAssist::m_soundAssistClap private
the sound made when a note is to be hit.
Referenced by Init(), PlayTicks(), and StopPlaying().
m_soundAssistMetronomeBeat
RageSound GameplayAssist::m_soundAssistMetronomeBeat private
the sound made when crossing a new beat.
Referenced by Init(), PlayTicks(), and StopPlaying().
m_soundAssistMetronomeMeasure
RageSound GameplayAssist::m_soundAssistMetronomeMeasure private
the sound made when crossing a new measure.
Referenced by Init(), PlayTicks(), and StopPlaying().
The documentation for this class was generated from the following files:
GameplayAssist.h
GameplayAssist.cpp