Etterna: ETTProtocol Class Reference
ETTProtocol Class Reference
#include <NetworkSyncManager.h>
Public Member Functions
bool Connect (NetworkSyncManager *n, unsigned short port, RString address) override
void close () override
void Update (NetworkSyncManager *n, float fDeltaTime) override
void Login (RString user, RString pass) override
void Logout () override
void SendChat (const RString &message, string tab, int type) override
void CreateNewRoom (RString name, RString desc, RString password) override
void EnterRoom (RString name, RString password) override
void LeaveRoom (NetworkSyncManager *n) override
void ReportSongOver (NetworkSyncManager *n) override
void SelectUserSong (NetworkSyncManager *n, Song *song) override
void OnOptions () override
void OffOptions () override
void OnEval () override
void OffEval () override
void ReportHighScore (HighScore *hs, PlayerStageStats &pss) override
void Send (const char *msg)
void Send (json msg)
Public Member Functions inherited from NetProtocol
virtual void RequestRoomInfo (RString name)
virtual void ReportNSSOnOff (int i)
virtual void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset, int numNotes)
virtual void ReportScore (NetworkSyncManager *n, int playerID, int step, int score, int combo, float offset)
virtual void ReportStyle (NetworkSyncManager *n)
virtual void StartRequest (NetworkSyncManager *n, short position)
virtual void OnMusicSelect ()
virtual void OffMusicSelect ()
virtual void OnRoomSelect ()
virtual void OffRoomSelect ()
Public Attributes
bool waitingForTimeout { false }
clock_t timeoutStart
double timeout
function< void(void)> onTimeout
string roomName
string roomDesc
bool inRoom { false }
Public Attributes inherited from NetProtocol
RString serverName
int serverVersion { 0 }
Private Member Functions
void FindJsonChart (NetworkSyncManager *n, json &ch)
Private Attributes
uWS::Hub * uWSh = new uWS::Hub()
vector< json > newMessages
unsigned int msgId { 0 }
bool error { false }
string errorMsg
uWS::WebSocket< uWS::CLIENT > * ws { nullptr }
int state = 0
Member Function Documentation
close()
void ETTProtocol::close () override virtual
Reimplemented from NetProtocol.
References inRoom, msgId, roomDesc, roomName, NetProtocol::serverName, NetProtocol::serverVersion, and uWSh.
Referenced by NetworkSyncManager::CloseConnection().
Connect()
bool ETTProtocol::Connect (NetworkSyncManager * n, unsigned short port, RString address) override virtual
Reimplemented from NetProtocol.
References EzSockets::CanConnect(), error, errorMsg, NetworkSyncManager::isSMOnline, LOG, logPackets, msgId, newMessages, startsWith(), RageLog::Trace(), uWSh, and ws.
CreateNewRoom()
void ETTProtocol::CreateNewRoom (RString name, RString desc, RString password) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_createroom, msgId, roomDesc, roomName, Send(), and ws.
EnterRoom()
void ETTProtocol::EnterRoom (RString name, RString password) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_enterroom, NetworkSyncManager::m_Rooms, msgId, roomDesc, roomName, Send(), and ws.
FindJsonChart()
void ETTProtocol::FindJsonChart (NetworkSyncManager * n, json & ch) private
References NetworkSyncManager::chartkey, NetworkSyncManager::difficulty, Difficulty_Invalid, SongManager::GetAllSongs(), SongManager::GetSongByChartkey(), NetworkSyncManager::m_sArtist, NetworkSyncManager::m_sFileHash, NetworkSyncManager::m_sMainTitle, NetworkSyncManager::m_sSubTitle, NetworkSyncManager::meter, NetworkSyncManager::rate, NetworkSyncManager::song, SONGMAN, NetworkSyncManager::steps, and StringToDifficulty().
Referenced by Update().
LeaveRoom()
void ETTProtocol::LeaveRoom (NetworkSyncManager * n) override virtual
Reimplemented from NetProtocol.
References NetworkSyncManager::chartkey, NetworkSyncManager::difficulty, Difficulty_Invalid, ettClientMessageMap, ettpc_leaveroom, inRoom, NetworkSyncManager::m_sArtist, NetworkSyncManager::m_sFileHash, NetworkSyncManager::m_sMainTitle, NetworkSyncManager::m_sSubTitle, NetworkSyncManager::meter, msgId, NetworkSyncManager::rate, roomDesc, roomName, Send(), NetworkSyncManager::song, NetworkSyncManager::steps, and ws.
Login()
void ETTProtocol::Login (RString user, RString pass) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_login, NetworkSyncManager::loginResponse, msgId, onTimeout, SCREENMAN, Send(), ScreenManager::SendMessageToTopScreen(), timeout, timeoutStart, waitingForTimeout, and ws.
Logout()
void ETTProtocol::Logout () override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_logout, Send(), and ws.
OffEval()
void ETTProtocol::OffEval () override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_closeeval, msgId, Send(), state, and ws.
OffOptions()
void ETTProtocol::OffOptions () override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_closeoptions, msgId, Send(), state, and ws.
OnEval()
void ETTProtocol::OnEval () override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_openeval, msgId, Send(), state, and ws.
OnOptions()
void ETTProtocol::OnOptions () override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_openoptions, msgId, Send(), state, and ws.
ReportHighScore()
void ETTProtocol::ReportHighScore (HighScore * hs, PlayerStageStats & pss) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_sendscore, FOREACH_ENUM, GAMESTATE, HighScore::GetChartKey(), HighScore::GetChordCohesion(), ModsGroup< T >::GetCurrent(), HighScore::GetDateTime(), HighScore::GetEtternaValid(), HighScore::GetHoldNoteScore(), HighScore::GetMachineGuid(), HighScore::GetMaxCombo(), HighScore::GetModifiers(), HighScore::GetMusicRate(), PlayerStageStats::GetNoteRowVector(), PlayerStageStats::GetOffsetVector(), HighScore::GetScoreKey(), HighScore::GetSkillsetSSR(), HighScore::GetSSRCalcVersion(), HighScore::GetSSRNormPercent(), SongManager::GetStepsByChartkey(), PlayerOptions::GetString(), DateTime::GetString(), HighScore::GetTapNoteScore(), Steps::GetTimingData(), HighScore::GetTopScore(), HighScore::GetValidationKey(), TimingData::HasWarps(), HNS_Held, HNS_LetGo, HNS_Missed, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, PLAYER_1, Send(), SkillsetToString(), SONGMAN, StepsType_dance_single, TNS_HitMine, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, ValidationKey_Brittle, and ws.
ReportSongOver()
void ETTProtocol::ReportSongOver (NetworkSyncManager * n) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_gameover, msgId, Send(), and ws.
SelectUserSong()
void ETTProtocol::SelectUserSong (NetworkSyncManager * n, Song * song) override virtual
Reimplemented from NetProtocol.
References DifficultyToString(), ettClientMessageMap, ettpc_selectchart, ettpc_startchart, GAMESTATE, ModsGroup< T >::GetCurrent(), Song::GetFileHash(), PlayerOptions::GetString(), SongOptions::m_fMusicRate, GameState::m_pCurSong, GameState::m_pCurSteps, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, Song::m_sArtist, NetworkSyncManager::m_sArtist, Song::m_sMainTitle, NetworkSyncManager::m_sMainTitle, GameState::m_SongOptions, Song::m_sSubTitle, NetworkSyncManager::m_sSubTitle, msgId, PLAYER_1, Send(), NetworkSyncManager::song, and ws.
Send() [1/2]
void ETTProtocol::Send (const char * msg)
References LOG, logPackets, RageLog::Trace(), and ws.
Referenced by CreateNewRoom(), EnterRoom(), LeaveRoom(), Login(), Logout(), OffEval(), OffOptions(), OnEval(), OnOptions(), ReportHighScore(), ReportSongOver(), SelectUserSong(), Send(), SendChat(), and Update().
Send() [2/2]
void ETTProtocol::Send (json msg)
References Send().
SendChat()
void ETTProtocol::SendChat (const RString & message, string tab, int type) override virtual
Reimplemented from NetProtocol.
References ettClientMessageMap, ettpc_sendchat, msgId, Send(), and ws.
Update()
void ETTProtocol::Update (NetworkSyncManager * n, float fDeltaTime) override virtual
Reimplemented from NetProtocol.
References MessageManager::Broadcast(), picosha2::detail::ch(), NetworkSyncManager::chat, NetworkSyncManager::CloseConnection(), NetworkSyncManager::DisplayStartupStatus(), error, ettClientMessageMap, ettpc_haschart, ettpc_hello, ettpc_missingchart, ettpc_notstartingchart, ettpc_ping, ettpc_startingchart, ETTPCVERSION, ettps_createroomresponse, ettps_deleteroom, ettps_enterroomresponse, ettps_gameplayleaderboard, ettps_hello, ettps_loginresponse, ettps_newroom, ettps_ping, ettps_recievechat, ettps_recievescore, ettps_roomlist, ettps_roomuserlist, ettps_selectchart, ettps_startchart, ettps_updateroom, ettServerMessageMap, FindJsonChart(), FOREACH_ENUM, PlayerStageStats::GetGrade(), ThemeManager::GetMetric(), HighScore::GetSSRNormPercent(), HNS_Held, HNS_LetGo, HNS_Missed, EndOfGame_PlayerData::hs, inRoom, NetworkSyncManager::isSMOnline, jsonToRoom(), LOG, NetworkSyncManager::loggedIn, NetworkSyncManager::loginResponse, NetworkSyncManager::m_ActivePlayer, NetworkSyncManager::m_ActivePlayers, NetworkSyncManager::m_EvalPlayerData, NetworkSyncManager::m_PlayerNames, NetworkSyncManager::m_PlayerStatus, NetworkSyncManager::m_Rooms, Message_UpdateScreenHeader, MessageIDToString(), MESSAGEMAN, msgId, EndOfGame_PlayerData::nameStr, newMessages, onTimeout, EndOfGame_PlayerData::playerOptions, roomDesc, roomName, SCREENMAN, Send(), ScreenManager::SendMessageToTopScreen(), NetProtocol::serverName, NetProtocol::serverVersion, HighScore::SetChartKey(), HighScore::SetChordCohesion(), HighScore::SetDateTime(), HighScore::SetEtternaValid(), HighScore::SetGrade(), HighScore::SetHoldNoteScore(), HighScore::SetMaxCombo(), HighScore::SetModifiers(), HighScore::SetMusicRate(), ScreenManager::SetNewScreen(), HighScore::SetNoteRowVector(), HighScore::SetOffsetVector(), Message::SetParam(), HighScore::SetScoreKey(), HighScore::SetSkillsetSSR(), HighScore::SetSSRNormPercent(), HighScore::SetTapNoteScore(), HighScore::SetWifeScore(), SkillsetToString(), NetworkSyncManager::song, state, EndOfGame_PlayerData::tapScores, THEME, timeout, timeoutStart, TNS_HitMine, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, RageLog::Trace(), uWSh, waitingForTimeout, and ws.
Member Data Documentation
error
bool ETTProtocol::error { false } private
Referenced by Connect(), and Update().
errorMsg
string ETTProtocol::errorMsg private
Referenced by Connect().
inRoom
bool ETTProtocol::inRoom { false }
Referenced by close(), LeaveRoom(), and Update().
msgId
unsigned int ETTProtocol::msgId { 0 } private
Referenced by close(), Connect(), CreateNewRoom(), EnterRoom(), LeaveRoom(), Login(), OffEval(), OffOptions(), OnEval(), OnOptions(), ReportSongOver(), SelectUserSong(), SendChat(), and Update().
newMessages
vector<json> ETTProtocol::newMessages private
Referenced by Connect(), and Update().
onTimeout
function<void(void)> ETTProtocol::onTimeout
Referenced by Login(), and Update().
roomDesc
string ETTProtocol::roomDesc
Referenced by close(), CreateNewRoom(), EnterRoom(), LeaveRoom(), and Update().
roomName
string ETTProtocol::roomName
Referenced by close(), CreateNewRoom(), EnterRoom(), LeaveRoom(), and Update().
state
int ETTProtocol::state = 0 private
Referenced by OffEval(), OffOptions(), OnEval(), OnOptions(), and Update().
timeout
double ETTProtocol::timeout
Referenced by Login(), and Update().
timeoutStart
clock_t ETTProtocol::timeoutStart
Referenced by Login(), and Update().
uWSh
uWS::Hub* ETTProtocol::uWSh = new uWS::Hub() private
Referenced by close(), Connect(), and Update().
waitingForTimeout
bool ETTProtocol::waitingForTimeout { false }
Referenced by Login(), and Update().
ws
uWS::WebSocket<uWS::CLIENT>* ETTProtocol::ws { nullptr } private
Referenced by Connect(), CreateNewRoom(), EnterRoom(), LeaveRoom(), Login(), Logout(), OffEval(), OffOptions(), OnEval(), OnOptions(), ReportHighScore(), ReportSongOver(), SelectUserSong(), Send(), SendChat(), and Update().
The documentation for this class was generated from the following files:
NetworkSyncManager.h
NetworkSyncManager.cpp