Etterna: BackgroundUtil Namespace Reference
BackgroundUtil Namespace Reference
Shared background-related routines.
Functions
void AddBackgroundChange (vector< BackgroundChange > &vBackgroundChanges, BackgroundChange seg)
void SortBackgroundChangesArray (vector< BackgroundChange > &vBackgroundChanges)
void GetBackgroundEffects (const RString &sName, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetBackgroundTransitions (const RString &sName, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetSongBGAnimations (const Song *pSong, const RString &sMatch, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetSongMovies (const Song *pSong, const RString &sMatch, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetSongBitmaps (const Song *pSong, const RString &sMatch, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetGlobalBGAnimations (const Song *pSong, const RString &sMatch, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut)
void GetGlobalRandomMovies (const Song *pSong, const RString &sMatch, vector< RString > &vsPathsOut, vector< RString > &vsNamesOut, bool bTryInsideOfSongGroupAndGenreFirst=true, bool bTryInsideOfSongGroupFirst=true)
void BakeAllBackgroundChanges (Song *pSong)
Detailed Description
Shared background-related routines.
Function Documentation
AddBackgroundChange()
void BackgroundUtil::AddBackgroundChange (vector< BackgroundChange > & vBackgroundChanges, BackgroundChange seg)
References CompareBackgroundChanges().
Referenced by Song::AddBackgroundChange(), and Song::AddForegroundChange().
BakeAllBackgroundChanges()
void BackgroundUtil::BakeAllBackgroundChanges (Song * pSong)
References FOREACH_BackgroundLayer, Song::GetBackgroundChanges(), Background::GetLoadedBackgroundChanges(), Background::LoadFromSong(), and NUM_BackgroundLayer.
GetBackgroundEffects()
void BackgroundUtil::GetBackgroundEffects (const RString & sName, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References FOREACH_CONST, GetDirListing(), GetFileNameWithoutExtension(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground().
GetBackgroundTransitions()
void BackgroundUtil::GetBackgroundTransitions (const RString & sName, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References FOREACH_CONST, GetDirListing(), GetFileNameWithoutExtension(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Init().
GetGlobalBGAnimations()
void BackgroundUtil::GetGlobalBGAnimations (const Song * pSong, const RString & sMatch, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References Basename(), FOREACH_CONST, GetDirListing(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground(), and BackgroundImpl::LoadFromSong().
GetGlobalRandomMovies()
void BackgroundUtil::GetGlobalRandomMovies (const Song * pSong, const RString & sMatch, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut, bool bTryInsideOfSongGroupAndGenreFirst = true, bool bTryInsideOfSongGroupFirst = true)
References FOREACH_CONST, StdString::CStdStr< CT >::Right(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground(), and BackgroundImpl::LoadFromSong().
GetSongBGAnimations()
void BackgroundUtil::GetSongBGAnimations (const Song * pSong, const RString & sMatch, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References Basename(), FOREACH_CONST, GetDirListing(), Song::GetSongDir(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground().
GetSongBitmaps()
void BackgroundUtil::GetSongBitmaps (const Song * pSong, const RString & sMatch, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References Basename(), FILEMAN, FOREACH_CONST, FT_Bitmap, GetDirListing(), RageFileManager::GetDirListingWithMultipleExtensions(), Song::GetSongDir(), ActorUtil::GetTypeExtensionList(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground().
GetSongMovies()
void BackgroundUtil::GetSongMovies (const Song * pSong, const RString & sMatch, vector< RString > & vsPathsOut, vector< RString > & vsNamesOut)
References Basename(), FILEMAN, FOREACH_CONST, FT_Movie, GetDirListing(), RageFileManager::GetDirListingWithMultipleExtensions(), Song::GetSongDir(), ActorUtil::GetTypeExtensionList(), and StripCvsAndSvn().
Referenced by BackgroundImpl::Layer::CreateBackground().
SortBackgroundChangesArray()
void BackgroundUtil::SortBackgroundChangesArray (vector< BackgroundChange > & vBackgroundChanges)
References CompareBackgroundChanges().
Referenced by BackgroundImpl::LoadFromSong().