Etterna: RageBitmapTexture.cpp File Reference
RageBitmapTexture.cpp File Reference
#include "global.h"
#include "RageBitmapTexture.h"
#include "RageDisplay.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageSurfaceUtils_Dither.h"
#include "RageSurfaceUtils_Zoom.h"
#include "RageSurface_Load.h"
#include "RageTextureManager.h"
#include "RageTypes.h"
#include "RageUtil.h"
#include "StepMania.h"
#include "arch/Dialog/Dialog.h"
Functions
static void GetResolutionFromFileName (RString sPath, int &iWidth, int &iHeight)
Function Documentation
GetResolutionFromFileName()
static void GetResolutionFromFileName (RString sPath, int & iWidth, int & iHeight) static
References Regex::Compare(), and StringToInt().
Referenced by RageBitmapTexture::Create().