Etterna: Regex Class Reference
Regex Class Reference
#include <RageUtil.h>
Public Member Functions
Regex (const RString &sPat="")
Regex (const Regex &rhs)
Regex & operator= (const Regex &rhs)
~Regex ()
bool IsSet () const
void Set (const RString &str)
bool Compare (const RString &sStr)
bool Compare (const RString &sStr, vector< RString > &asMatches)
bool Replace (const RString &sReplacement, const RString &sSubject, RString &sOut)
Private Member Functions
void Compile ()
void Release ()
Private Attributes
void * m_pReg
unsigned m_iBackrefs
RString m_sPattern
Constructor & Destructor Documentation
Regex() [1/2]
Regex::Regex (const RString & sPat = "")
References Set().
Regex() [2/2]
Regex::Regex (const Regex & rhs)
References m_sPattern, and Set().
~Regex()
Regex::~Regex ()
References Release().
Member Function Documentation
Compare() [1/2]
bool Regex::Compare (const RString & sStr)
References m_pReg, m_sPattern, and RageException::Throw().
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), CheckVideoDefaultSettings(), SongOptions::FromOneModString(), PlayerOptions::FromOneModString(), RageTexture::GetFrameDimensionsFromFileName(), GetResolutionFromFileName(), Font::LoadFontPageSettings(), LyricsLoader::LoadFromLRCFile(), ThemeManager::LoadThemeMetrics(), Profile::MakeUniqueFileNameNoExtension(), FileTransfer::ParseHTTPAddress(), ScreenPackages::ParseHTTPAddress(), Replace(), ScreenGameplay::SaveReplay(), and splitpath().
Compare() [2/2]
bool Regex::Compare (const RString & sStr, vector< RString > & asMatches)
References m_iBackrefs, m_pReg, m_sPattern, and RageException::Throw().
Compile()
void Regex::Compile () private
References ASSERT, m_iBackrefs, m_pReg, m_sPattern, and RageException::Throw().
Referenced by Set().
IsSet()
bool Regex::IsSet () const inline
References m_sPattern.
Referenced by TitleSubst::AddTrans().
operator=()
Regex & Regex::operator= (const Regex & rhs)
References m_sPattern, and Set().
Release()
void Regex::Release () private
References m_pReg, and m_sPattern.
Referenced by Set(), and ~Regex().
Replace()
bool Regex::Replace (const RString & sReplacement, const RString & sSubject, RString & sOut)
References Compare(), StdString::CStdStr< CT >::Replace(), and ssprintf().
Referenced by TitleTrans::Matches().
Set()
void Regex::Set (const RString & str)
References Compile(), m_sPattern, and Release().
Referenced by operator=(), and Regex().
Member Data Documentation
m_iBackrefs
unsigned Regex::m_iBackrefs private
Referenced by Compare(), and Compile().
m_pReg
void* Regex::m_pReg private
Referenced by Compare(), Compile(), and Release().
m_sPattern
RString Regex::m_sPattern private
Referenced by Compare(), Compile(), IsSet(), operator=(), Regex(), Release(), and Set().
The documentation for this class was generated from the following files:
RageUtil.h
RageUtil.cpp