Etterna: ArchHooks_Unix Class Reference
ArchHooks_Unix Class Reference
#include <ArchHooks_Unix.h>
Public Member Functions
void Init ()
RString GetArchName () const
void DumpDebugInfo ()
void SetTime (tm newtime)
int64_t GetMicrosecondsSinceStart ()
void MountInitialFilesystems (const RString &sDirOfExecutable)
float GetDisplayAspectRatio ()
bool GoToURL (const RString &sUrl)
RString GetClipboard ()
Fetch the contents of the system clipboard.
Public Member Functions inherited from ArchHooks
ArchHooks ()
virtual ~ArchHooks ()=default
virtual void RestartProgram ()
Re-exec the game.
virtual bool CheckForMultipleInstances (int, char *[])
virtual void BoostPriority ()
virtual void UnBoostPriority ()
virtual void SetupConcurrentRenderingThread ()
Setup the rendering threads for concurrency.
void SetHasFocus (bool bAppHasFocus)
bool AppHasFocus () const
bool AppFocusChanged ()
virtual int GetWindowWidth ()
Fetch the window width.
virtual int GetWindowHeight ()
Fetch the window height.
void PushSelf (lua_State *L)
void RegisterWithLua ()
Static Public Member Functions
static clockid_t GetClock ()
Static Public Member Functions inherited from ArchHooks
static ArchHooks * Create ()
static RString GetPreferredLanguage ()
static bool UserQuit ()
Determine if the user wants to quit (eg. ^C, or clicked a "close window" button).
static void SetUserQuit ()
static bool GetAndClearToggleWindowed ()
static void SetToggleWindowed ()
static int64_t GetMicrosecondsSinceStart (bool bAccurate)
static void MountInitialFilesystems (const RString &sDirOfExecutable)
static void MountUserFilesystems (const RString &sDirOfExecutable)
Member Function Documentation
DumpDebugInfo()
void ArchHooks_Unix::DumpDebugInfo () virtual
Reimplemented from ArchHooks.
References RageLog::Info(), LibcVersion(), and LOG.
GetArchName()
RString ArchHooks_Unix::GetArchName () const inline virtual
Reimplemented from ArchHooks.
GetClipboard()
RString ArchHooks_Unix::GetClipboard () virtual
Fetch the contents of the system clipboard.
Reimplemented from ArchHooks.
References ASSERT, LOG, and RageLog::Warn().
GetClock()
clockid_t ArchHooks_Unix::GetClock () static
GetDisplayAspectRatio()
float ArchHooks_Unix::GetDisplayAspectRatio () inline virtual
Implements ArchHooks.
GetMicrosecondsSinceStart()
int64_t ArchHooks_Unix::GetMicrosecondsSinceStart ()
GoToURL()
bool ArchHooks_Unix::GoToURL (const RString & sUrl) virtual
Reimplemented from ArchHooks.
Init()
void ArchHooks_Unix::Init () virtual
Reimplemented from ArchHooks.
References DoCleanShutdown(), DoCrashSignalHandler(), EmergencyShutdown(), g_argc, and g_argv.
MountInitialFilesystems()
void ArchHooks_Unix::MountInitialFilesystems (const RString & sDirOfExecutable)
SetTime()
void ArchHooks_Unix::SetTime (tm newtime) virtual
Reimplemented from ArchHooks.
References LOG, ssprintf(), and RageLog::Trace().
The documentation for this class was generated from the following files:
ArchHooks_Unix.h
ArchHooks_Unix.cpp