Etterna: ScreenSelectMaster.cpp File Reference
ScreenSelectMaster.cpp File Reference
#include "ScreenSelectMaster.h"
#include "ActorUtil.h"
#include "AnnouncerManager.h"
#include "Foreach.h"
#include "GameCommand.h"
#include "GameManager.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "InputEventPlus.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "ThemeManager.h"
#include "global.h"
#include <set>
#include "LuaBinding.h"
Classes
class LunaScreenSelectMaster
Allow Lua to have access to the ScreenSelectMaster.
Macros
#define GetActiveElementPlayerNumbers(vpns)
#define PLAYER_APPEND_NO_SPACE(p) (SHARED_SELECTION ? RString() : ssprintf("P%d", (p) + 1))
#define SET_POS_PART(i, part)
#define OPTIONAL_COMMAND(onoff)
Functions
XToString (MenuDir)
AutoScreenMessage (SM_PlayPostSwitchPage)
static RString CURSOR_OFFSET_X_FROM_ICON_NAME (size_t p)
static RString CURSOR_OFFSET_Y_FROM_ICON_NAME (size_t p)
static RString OPTION_ORDER_NAME (size_t dir)
REGISTER_SCREEN_CLASS (ScreenSelectMaster)
Variables
static const char * MenuDirNames []
Macro Definition Documentation
GetActiveElementPlayerNumbers
#define GetActiveElementPlayerNumbers (vpns)
Value:
if (SHARED_SELECTION) {                                                    \
        (vpns).push_back(PLAYER_1);                                            \
    } else {                                                                   \
        FOREACH_HumanPlayer(p)(vpns).push_back(p);                             \
    }
Referenced by ScreenSelectMaster::ChangePage(), ScreenSelectMaster::HandleScreenMessage(), ScreenSelectMaster::Init(), ScreenSelectMaster::TweenOffScreen(), ScreenSelectMaster::TweenOnScreen(), and ScreenSelectMaster::UpdateSelectableChoices().
OPTIONAL_COMMAND
#define OPTIONAL_COMMAND (onoff)
Value:
if (THEME->HasMetric(m_sName, "IconChoice" onoff "Command")) {             \
        m_vsprIcon[c]->AddCommand(                                             \
          onoff,                                                               \
          THEME->GetMetricA(m_sName, "IconChoice" onoff "Command"),            \
          false);                                                              \
    }
Referenced by ScreenSelectMaster::Init().
PLAYER_APPEND_NO_SPACE
#define PLAYER_APPEND_NO_SPACE (p) (SHARED_SELECTION ? RString() : ssprintf("P%d", (p) + 1))
Referenced by ScreenSelectMaster::Init().
SET_POS_PART
#define SET_POS_PART (i, part)
Value:
lua_rawgeti(L, -1, i);                                                     \
    pos.part = static_cast<float>(lua_tonumber(L, -1));                        \
    lua_pop(L, 1);
Referenced by ScreenSelectMaster::Init().
Function Documentation
AutoScreenMessage()
AutoScreenMessage (SM_PlayPostSwitchPage)
CURSOR_OFFSET_X_FROM_ICON_NAME()
static RString CURSOR_OFFSET_X_FROM_ICON_NAME (size_t p) static
References ssprintf().
Referenced by ScreenSelectMaster::Init().
CURSOR_OFFSET_Y_FROM_ICON_NAME()
static RString CURSOR_OFFSET_Y_FROM_ICON_NAME (size_t p) static
References ssprintf().
Referenced by ScreenSelectMaster::Init().
OPTION_ORDER_NAME()
static RString OPTION_ORDER_NAME (size_t dir) static
References MenuDirToString().
Referenced by ScreenSelectMaster::Init().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenSelectMaster)
XToString()
XToString (MenuDir)
Variable Documentation
MenuDirNames
const char* MenuDirNames[] static
Initial value:
= {
    "Up", "Down", "Left", "Right", "Auto",
}