Etterna: GameInput.cpp File Reference
GameInput.cpp File Reference
#include "global.h"
#include "GameInput.h"
#include "InputMapper.h"
#include "RageUtil.h"
#include "ThemeManager.h"
Functions
XToString (GameController)
StringToX (GameController)
LuaXType (GameController)
RString GameButtonToString (const InputScheme *pInputs, GameButton i)
RString GameButtonToLocalizedString (const InputScheme *pInputs, GameButton i)
GameButton StringToGameButton (const InputScheme *pInputs, const RString &s)
Variables
static const char * GameControllerNames []
Function Documentation
GameButtonToLocalizedString()
RString GameButtonToLocalizedString (const InputScheme * pInputs, GameButton i)
References GameButtonToString(), ThemeManager::GetString(), and THEME.
Referenced by ScreenMapControllers::Init(), and InputList::Update().
GameButtonToString()
RString GameButtonToString (const InputScheme * pInputs, GameButton i)
References InputScheme::GetGameButtonName().
Referenced by GameButtonToLocalizedString(), ScreenSelectMusic::Input(), Screen::PassInputToLua(), StringToGameButton(), and GameInput::ToString().
LuaXType()
LuaXType (GameController)
StringToGameButton()
GameButton StringToGameButton (const InputScheme * pInputs, const RString & s)
References FOREACH_GameButtonInScheme, GameButton_Invalid, and GameButtonToString().
Referenced by GameInput::FromString(), and ScreenMapControllers::Init().
StringToX()
StringToX (GameController)
XToString()
XToString (GameController)
Variable Documentation
GameControllerNames
const char* GameControllerNames[] static
Initial value:
= {
    "1",
    "2",
}