Etterna: Song.cpp File Reference
Song.cpp File Reference
#include "Song.h"
#include "ActorUtil.h"
#include "BackgroundUtil.h"
#include "CommonMetrics.h"
#include "FontCharAliases.h"
#include "Foreach.h"
#include "GameManager.h"
#include "ImageCache.h"
#include "LyricsLoader.h"
#include "NotesLoader.h"
#include "NotesLoaderSM.h"
#include "NotesLoaderSSC.h"
#include "NotesWriterDWI.h"
#include "NotesWriterETT.h"
#include "NotesWriterJson.h"
#include "NotesWriterSM.h"
#include "NotesWriterSSC.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageSoundReader_FileReader.h"
#include "RageSurface.h"
#include "RageSurface_Load.h"
#include "RageTextureManager.h"
#include "RageUtil.h"
#include "SongCacheIndex.h"
#include "SongManager.h"
#include "SongUtil.h"
#include "Sprite.h"
#include "Steps.h"
#include "StepsUtil.h"
#include "Style.h"
#include "TitleSubstitution.h"
#include "global.h"
#include "GameState.h"
#include <cfloat>
#include <ctime>
#include <set>
#include <CryptManager.h>
#include "LuaBinding.h"
Classes
class LunaSong
Allow Lua to have access to the Song.
Macros
#define CLEAR_NOT_HAS(has_name, field_name)
Functions
XToString (InstrumentTrack)
StringToX (InstrumentTrack)
void FixupPath (RString &path, const RString &sSongPath)
Variables
const int FILE_CACHE_VERSION = 239
The internal version of the cache for StepMania.
const float DEFAULT_MUSIC_SAMPLE_LENGTH = 25.f
How long does a song sample last by default?
static Preference< float > g_fLongVerSongSeconds ("LongVerSongSeconds", 60 *2.5f)
static Preference< float > g_fMarathonVerSongSeconds ("MarathonVerSongSeconds", 60 *5.f)
static Preference< bool > g_BackUpAllSongSaves ("BackUpAllSongSaves", false)
static const char * InstrumentTrackNames []
static set< RString > BlacklistedImages
Macro Definition Documentation
CLEAR_NOT_HAS
#define CLEAR_NOT_HAS (has_name, field_name)
Value:
if (!(has_name)) {                                                         \
        (field_name) = "";                                                     \
    }
Referenced by Song::TidyUpData().
Function Documentation
FixupPath()
void FixupPath (RString & path, const RString & sSongPath)
References FixSlashesInPlace(), and Trim().
Referenced by Song::TidyUpData().
StringToX()
StringToX (InstrumentTrack)
XToString()
XToString (InstrumentTrack)
Variable Documentation
BlacklistedImages
set<RString> BlacklistedImages static
Referenced by Song::LoadFromSongDir(), and Song::TidyUpData().
DEFAULT_MUSIC_SAMPLE_LENGTH
const float DEFAULT_MUSIC_SAMPLE_LENGTH = 25.f
How long does a song sample last by default?
Referenced by Song::Song(), and Song::TidyUpData().
FILE_CACHE_VERSION
const int FILE_CACHE_VERSION = 239
The internal version of the cache for StepMania.
Increment this value to invalidate the current cache.
g_BackUpAllSongSaves
Preference<bool> g_BackUpAllSongSaves("BackUpAllSongSaves", false) static
Referenced by Song::SaveToETTFile(), and Song::SaveToSSCFile().
g_fLongVerSongSeconds
Preference<float> g_fLongVerSongSeconds("LongVerSongSeconds", 60 *2.5f) static
Referenced by Song::IsLong().
g_fMarathonVerSongSeconds
Preference<float> g_fMarathonVerSongSeconds("MarathonVerSongSeconds", 60 *5.f) static
Referenced by Song::IsMarathon().
InstrumentTrackNames
const char* InstrumentTrackNames[] static
Initial value:
= {
    "Guitar",
    "Rhythm",
    "Bass",
}