Etterna: RageSurfaceUtils.cpp File Reference
RageSurfaceUtils.cpp File Reference
#include "global.h"
#include "RageSurfaceUtils.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageUtil.h"
#include <thread>
Classes
struct SurfaceHeader
Functions
static void FindAlphaRGB (const RageSurface *img, uint8_t &r, uint8_t &g, uint8_t &b, bool reverse)
static void SetAlphaRGB (const RageSurface *pImg, uint8_t r, uint8_t g, uint8_t b)
static void GetRawRGBAV_XY (const RageSurface *src, uint8_t *v, int x, int y)
static float scale (float x, float l1, float h1, float l2, float h2)
static bool blit_same_type (const RageSurface *src_surf, const RageSurface *dst_surf, int width, int height)
static bool blit_rgba_to_rgba (const RageSurface *src_surf, const RageSurface *dst_surf, int width, int height)
static bool blit_generic (const RageSurface *src_surf, const RageSurface *dst_surf, int width, int height)
static bool ImageUsesOffHotPink (const RageSurface *img)
Function Documentation
blit_generic()
static bool blit_generic (const RageSurface * src_surf, const RageSurface * dst_surf, int width, int height) static
References RageSurfaceColor::a, RageSurfaceColor::b, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, RageSurfaceUtils::decodepixel(), RageSurfaceUtils::encodepixel(), RageSurface::fmt, RageSurfaceColor::g, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, and RageSurfaceUtils::SetRGBAV().
Referenced by RageSurfaceUtils::Blit().
blit_rgba_to_rgba()
static bool blit_rgba_to_rgba (const RageSurface * src_surf, const RageSurface * dst_surf, int width, int height) static
References ASSERT, RageSurfaceFormat::BytesPerPixel, RageSurfaceUtils::decodepixel(), RageSurfaceUtils::encodepixel(), RageSurface::fmt, RageSurfaceFormat::Mask, max(), RageSurface::pitch, RageSurface::pixels, SCALE, and RageSurfaceFormat::Shift.
Referenced by RageSurfaceUtils::Blit().
blit_same_type()
static bool blit_same_type (const RageSurface * src_surf, const RageSurface * dst_surf, int width, int height) static
References RageSurfaceFormat::Amask, RageSurfaceFormat::Bmask, RageSurfaceFormat::BytesPerPixel, RageSurface::fmt, RageSurfaceFormat::Gmask, RageSurface::pitch, RageSurface::pixels, RageSurfaceFormat::Rmask, and RageSurface::w.
Referenced by RageSurfaceUtils::Blit().
FindAlphaRGB()
static void FindAlphaRGB (const RageSurface * img, uint8_t & r, uint8_t & g, uint8_t & b, bool reverse) static
References RageSurfaceColor::a, RageSurfaceFormat::Amask, RageSurfaceColor::b, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, RageSurfaceUtils::decodepixel(), RageSurface::fmt, RageSurfaceColor::g, RageSurfaceFormat::GetRGB(), RageSurface::h, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, and RageSurface::w.
Referenced by RageSurfaceUtils::FixHiddenAlpha().
GetRawRGBAV_XY()
static void GetRawRGBAV_XY (const RageSurface * src, uint8_t * v, int x, int y) inline static
References RageSurfaceFormat::BytesPerPixel, RageSurface::fmt, RageSurfaceUtils::GetRawRGBAV(), RageSurface::pitch, and RageSurface::pixels.
Referenced by RageSurfaceUtils::BlitTransform().
ImageUsesOffHotPink()
static bool ImageUsesOffHotPink (const RageSurface * img) static
References RageSurfaceFormat::BytesPerPixel, RageSurfaceUtils::decodepixel(), RageSurface::fmt, RageSurface::h, RageSurfaceFormat::MapRGBA(), RageSurface::pitch, RageSurface::pixels, and RageSurface::w.
Referenced by RageSurfaceUtils::ApplyHotPinkColorKey().
scale()
static float scale (float x, float l1, float h1, float l2, float h2) inline static
Referenced by RageSurfaceUtils::BlitTransform().
SetAlphaRGB()
static void SetAlphaRGB (const RageSurface * pImg, uint8_t r, uint8_t g, uint8_t b) static
References RageSurfaceColor::a, RageSurfaceFormat::Amask, RageSurfaceColor::b, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, RageSurfaceUtils::decodepixel(), RageSurfaceUtils::encodepixel(), RageSurface::fmt, RageSurfaceColor::g, RageSurface::h, RageSurfaceFormat::MapRGBA(), RageSurfacePalette::ncolors, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, and RageSurface::w.
Referenced by RageSurfaceUtils::FixHiddenAlpha().