Etterna: OptionRowHandlerList Class Reference
OptionRowHandlerList Class Reference
Public Member Functions
OptionRowHandlerList ()
void Init () override
bool LoadInternal (const Commands &cmds) override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
int GetDefaultOption () const override
void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const override
RString GetScreen (int iChoice) const override
ReloadChanged Reload () override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
vector< GameCommand > m_aListEntries
GameCommand m_Default
bool m_bUseModNameForIcon
vector< RString > m_vsBroadcastOnExport
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerList()
OptionRowHandlerList::OptionRowHandlerList () inline
References Init().
Member Function Documentation
ExportOption()
int OptionRowHandlerList::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::Apply(), MessageManager::Broadcast(), FOREACH_CONST, and MESSAGEMAN.
GetDefaultOption()
int OptionRowHandlerList::GetDefaultOption () const inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::m_Def, and OptionRowDefinition::m_iDefault.
GetIconTextAndGameCommand()
void OptionRowHandlerList::GetIconTextAndGameCommand (int iFirstSelection, RString & sIconTextOut, GameCommand & gcOut) const inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::m_Def, and OptionRowDefinition::m_vsChoices.
GetScreen()
RString OptionRowHandlerList::GetScreen (int iChoice) const inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::m_sScreen.
ImportOption()
void OptionRowHandlerList::ImportOption (OptionRow * pRow, const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References CHECKPOINT_M, GameCommand::DescribesCurrentMode(), GameCommand::DescribesCurrentModeForAllPlayers(), FOREACH_CONST, GameCommand::IsZero(), LOG, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_iDefault, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, SELECT_MULTIPLE, SELECT_ONE, OptionRowHandlerUtil::SelectExactlyOne(), ssprintf(), VerifySelected(), and RageLog::Warn().
Init()
void OptionRowHandlerList::Init () inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::Init(), and OptionRowHandler::Init().
Referenced by OptionRowHandlerList().
LoadInternal()
bool OptionRowHandlerList::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
Reimplemented in OptionRowHandlerListSongsInCurrentSongGroup, OptionRowHandlerListDifficulties, OptionRowHandlerListGroups, OptionRowHandlerListStyles, OptionRowHandlerListCharacters, OptionRowHandlerListSteps, and OptionRowHandlerListNoteSkins.
References GameCommand::ApplyCommitsScreens(), ASSERT, ENTRY, ENTRY_DEFAULT, ENTRY_MODE, Command::GetArg(), Command::GetName(), GameCommand::IsPlayable(), GameCommand::IsZero(), LAYOUT_SHOW_ONE_IN_ROW, GameCommand::Load(), OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_iDefault, OptionRowDefinition::m_layoutType, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, GameCommand::m_sName, OptionRowDefinition::m_vEnabledForPlayers, Command::m_vsArgs, OptionRowDefinition::m_vsChoices, OptionRowHandler::m_vsReloadRowMessages, NUM_PLAYERS, ParseCommands(), LuaHelpers::ReportScriptErrorFmt(), ROW_INVALID_IF, Command::Arg::s, SELECT_MULTIPLE, SELECT_NONE, SELECT_ONE, StringToInt(), and Commands::v.
Reload()
ReloadChanged OptionRowHandlerList::Reload () inline override virtual
Reimplemented from OptionRowHandler.
Reimplemented in OptionRowHandlerListSteps.
References StdString::CStdStr< CT >::CompareNoCase(), OptionRowHandler::m_Def, OptionRowDefinition::m_sName, OptionRowHandler::Reload(), and OptionRowHandler::RELOAD_CHANGED_ALL.
Member Data Documentation
m_aListEntries
vector<GameCommand> OptionRowHandlerList::m_aListEntries
Referenced by OptionRowHandlerListNoteSkins::LoadInternal(), OptionRowHandlerListCharacters::LoadInternal(), OptionRowHandlerListStyles::LoadInternal(), OptionRowHandlerListGroups::LoadInternal(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), and OptionRowHandlerListSteps::Reload().
m_bUseModNameForIcon
bool OptionRowHandlerList::m_bUseModNameForIcon
m_Default
GameCommand OptionRowHandlerList::m_Default
Referenced by OptionRowHandlerListCharacters::LoadInternal(), OptionRowHandlerListStyles::LoadInternal(), OptionRowHandlerListGroups::LoadInternal(), and OptionRowHandlerListDifficulties::LoadInternal().
m_vsBroadcastOnExport
vector<RString> OptionRowHandlerList::m_vsBroadcastOnExport
The documentation for this class was generated from the following file:
OptionRowHandler.cpp