Etterna: RageSurface_Load.cpp File Reference
RageSurface_Load.cpp File Reference
#include "global.h"
#include "RageSurface_Load.h"
#include "ActorUtil.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageSurface_Load_BMP.h"
#include "RageSurface_Load_GIF.h"
#include "RageSurface_Load_JPEG.h"
#include "RageSurface_Load_PNG.h"
#include "RageUtil.h"
#include <set>
Functions
static RageSurface * TryOpenFile (RString sPath, bool bHeaderOnly, RString &error, RString format, bool &bKeepTrying)
Function Documentation
TryOpenFile()
static RageSurface* TryOpenFile (RString sPath, bool bHeaderOnly, RString & error, RString format, bool & bKeepTrying) static
References ASSERT, StdString::CStdStr< CT >::CompareNoCase(), LOG, RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, RageSurface_Load_BMP(), RageSurface_Load_GIF(), RageSurface_Load_JPEG(), RageSurface_Load_PNG(), and RageLog::Trace().
Referenced by RageSurfaceUtils::LoadFile().