Etterna: ArchHooks_Win32Static.cpp File Reference
ArchHooks_Win32Static.cpp File Reference
#include "ArchHooks.h"
#include "ProductInfo.h"
#include "RageFileManager.h"
#include "RageUtil.h"
#include "SpecialFiles.h"
#include "archutils/Win32/SpecialDirs.h"
#include "global.h"
#include <mmsystem.h>
#include <windows.h>
Functions
static void InitTimer ()
static RString GetMountDir (const RString &sDirOfExecutable)
static RString LangIdToString (LANGID l)
static LANGID GetLanguageID ()
Variables
static bool g_bTimerInitialized
Function Documentation
GetLanguageID()
static LANGID GetLanguageID () static
GetMountDir()
static RString GetMountDir (const RString & sDirOfExecutable) static
References ASSERT_M, CHECKPOINT_M, Rage::join(), split(), and ssprintf().
InitTimer()
static void InitTimer () static
References g_bTimerInitialized.
LangIdToString()
static RString LangIdToString (LANGID l) static
Variable Documentation
g_bTimerInitialized
bool g_bTimerInitialized static
Referenced by InitTimer().