Etterna: TimingSegments.h File Reference
TimingSegments.h File Reference
#include "global.h"
#include "NoteTypes.h"
Classes
struct TimingSegment
The base timing segment for make glorious benefit wolfman XXX: this should be an abstract class.
struct FakeSegment
Identifies when a whole region of arrows is to be ignored.
struct WarpSegment
Identifies when a song needs to warp to a new beat.
struct TickcountSegment
Identifies when a chart is to have a different tickcount value for hold notes.
struct ComboSegment
Identifies when a chart is to have a different combo multiplier value.
struct LabelSegment
Identifies when a chart is entering a different section.
struct BPMSegment
Identifies when a song changes its BPM.
struct TimeSignatureSegment
Identifies when a song changes its time signature.
struct SpeedSegment
Identifies when the arrow scroll changes.
struct ScrollSegment
Identifies when the chart scroll changes.
struct StopSegment
Identifies when a song has a stop, DDR/ITG style.
struct DelaySegment
Identifies when a song has a delay, or pump style stop.
Macros
#define FOREACH_TimingSegmentType(tst) FOREACH_ENUM(TimingSegmentType, tst)
#define COMPARE(x)
#define COMPARE_FLOAT(x)
Enumerations
enum TimingSegmentType {
SEGMENT_BPM, SEGMENT_STOP, SEGMENT_DELAY, SEGMENT_TIME_SIG,
SEGMENT_WARP, SEGMENT_LABEL, SEGMENT_TICKCOUNT, SEGMENT_COMBO,
SEGMENT_SPEED, SEGMENT_SCROLL, SEGMENT_FAKE, NUM_TimingSegmentType,
TimingSegmentType_Invalid
}
enum SegmentEffectType {
SegmentEffectType_Row, SegmentEffectType_Range, SegmentEffectType_Indefinite, NUM_SegmentEffectType,
SegmentEffectType_Invalid
}
Functions
const RString & TimingSegmentTypeToString (TimingSegmentType tst)
Variables
const int ROW_INVALID = -1
Detailed Description
Author
Jason Felds (c) 2011
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if (this->x != other.x)                                                    \
    return false
Referenced by FakeSegment::operator==(), WarpSegment::operator==(), TickcountSegment::operator==(), ComboSegment::operator==(), LabelSegment::operator==(), TimeSignatureSegment::operator==(), and SpeedSegment::operator==().
COMPARE_FLOAT
#define COMPARE_FLOAT (x)
Value:
if (fabsf(this->x - other.x) > EPSILON)                                    \
    return false
Referenced by BPMSegment::operator==(), SpeedSegment::operator==(), ScrollSegment::operator==(), StopSegment::operator==(), and DelaySegment::operator==().
FOREACH_TimingSegmentType
#define FOREACH_TimingSegmentType (tst) FOREACH_ENUM(TimingSegmentType, tst)
Referenced by TimingData::Clear(), TimingData::ClearRange(), TimingData::Copy(), TimingData::CopyRange(), TimingData::DeleteRows(), NoteField::DrawPrimitives(), TimingData::empty(), TimingData::InsertRows(), TimingData::ScaleRegion(), and TimingData::ShiftRange().
Enumeration Type Documentation
SegmentEffectType
enum SegmentEffectType
Enumerator
SegmentEffectType_Row
SegmentEffectType_Range
SegmentEffectType_Indefinite
NUM_SegmentEffectType
SegmentEffectType_Invalid
TimingSegmentType
enum TimingSegmentType
Enumerator
SEGMENT_BPM
SEGMENT_STOP
SEGMENT_DELAY
SEGMENT_TIME_SIG
SEGMENT_WARP
SEGMENT_LABEL
SEGMENT_TICKCOUNT
SEGMENT_COMBO
SEGMENT_SPEED
SEGMENT_SCROLL
SEGMENT_FAKE
NUM_TimingSegmentType
TimingSegmentType_Invalid
Function Documentation
TimingSegmentTypeToString()
const RString& TimingSegmentTypeToString (TimingSegmentType tst)
Referenced by TimingData::AddSegment(), FakeSegment::DebugPrint(), WarpSegment::DebugPrint(), TickcountSegment::DebugPrint(), ComboSegment::DebugPrint(), LabelSegment::DebugPrint(), BPMSegment::DebugPrint(), TimeSignatureSegment::DebugPrint(), SpeedSegment::DebugPrint(), ScrollSegment::DebugPrint(), StopSegment::DebugPrint(), DelaySegment::DebugPrint(), and ToDerived().
Variable Documentation
ROW_INVALID
const int ROW_INVALID = -1