Etterna: KSFLoader Namespace Reference
KSFLoader Namespace Reference
Reads a Song from a set of .KSF files.
Functions
void GetApplicableFiles (const RString &sPath, vector< RString > &out)
bool LoadFromDir (const RString &sDir, Song &out)
bool LoadNoteDataFromSimfile (const RString &cachePath, Steps &out)
Detailed Description
Reads a Song from a set of .KSF files.
Function Documentation
GetApplicableFiles()
void KSFLoader::GetApplicableFiles (const RString & sPath, vector< RString > & out)
References GetDirListing().
Referenced by NotesLoader::LoadFromDir().
LoadFromDir()
bool KSFLoader::LoadFromDir (const RString & sDir, Song & out)
References Song::AddSteps(), ASSERT, Song::CreateSteps(), GetDirListing(), Song::GetSongDir(), LoadFromKSFFile(), LoadGlobalData(), LOG, Song::m_sSongFileName, Steps::SetFilename(), and RageLog::Trace().
Referenced by NotesLoader::LoadFromDir().
LoadNoteDataFromSimfile()
bool KSFLoader::LoadNoteDataFromSimfile (const RString & cachePath, Steps & out)
References Song::CreateSteps(), Steps::GetNoteData(), LoadFromKSFFile(), LoadGlobalData(), and Steps::SetNoteData().
Referenced by Steps::GetNoteDataFromSimfile().