Etterna: OptionRowHandlerUtil Namespace Reference
OptionRowHandlerUtil Namespace Reference
Utilities for the OptionRowHandlers.
Functions
OptionRowHandler * Make (const Commands &cmds)
OptionRowHandler * MakeNull ()
OptionRowHandler * MakeSimple (const MenuRowDef &mrd)
void SelectExactlyOne (int iSelection, vector< bool > &vbSelectedOut)
int GetOneSelection (const vector< bool > &vbSelected)
Detailed Description
Utilities for the OptionRowHandlers.
Function Documentation
GetOneSelection()
int OptionRowHandlerUtil::GetOneSelection (const vector< bool > & vbSelected)
References ASSERT.
Referenced by OptionRowHandlerSteps::ExportOption(), OptionRowHandlerConfig::ExportOption(), and OptionRowHandlerStepsType::ExportOption().
Make()
OptionRowHandler * OptionRowHandlerUtil::Make (const Commands & cmds)
References StdString::CStdStr< CT >::CompareNoCase(), Command::GetArg(), OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, Command::m_vsArgs, MAKE, ROW_INVALID_IF, Command::Arg::s, and Commands::v.
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsMaster::Init(), and OptionsList::Load().
MakeNull()
OptionRowHandler * OptionRowHandlerUtil::MakeNull ()
References MAKE.
Referenced by ScreenOptionsEditProfile::BeginScreen(), ScreenOptionsToggleSongs::BeginScreen(), ScreenOptionsExportPackage::BeginScreen(), ScreenOptionsToggleSongsSubPage::BeginScreen(), ScreenOptionsExportPackageSubPage::BeginScreen(), ScreenNetworkOptions::Init(), ScreenSMOnlineLogin::Init(), OptionRow::LoadExit(), and MakeSimple().
MakeSimple()
OptionRowHandler * OptionRowHandlerUtil::MakeSimple (const MenuRowDef & mrd)
References MenuRowDef::bEnabled, MenuRowDef::bThemeItems, MenuRowDef::bThemeTitle, MenuRowDef::choices, FOREACH, FOREACH_EnabledPlayer, LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bAllowThemeTitle, OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, OptionRowDefinition::m_vEnabledForPlayers, OptionRowDefinition::m_vsChoices, MakeNull(), MenuRowDef::pfnEnabled, FontCharAliases::ReplaceMarkers(), SELECT_ONE, and MenuRowDef::sName.
Referenced by ScreenOptionsCourseOverview::BeginScreen(), and ScreenMiniMenu::LoadMenu().
SelectExactlyOne()
void OptionRowHandlerUtil::SelectExactlyOne (int iSelection, vector< bool > & vbSelectedOut)
References ASSERT_M, and ssprintf().
Referenced by OptionRowHandlerList::ImportOption(), and OptionRowHandlerConfig::ImportOption().