Etterna: Actor Class Reference
Actor Class Reference
Base class for all objects that appear on the screen.
#include <Actor.h>
Classes
struct TweenInfo
Some general information about the Tween.
struct TweenState
The present state for the Tween.
struct TweenStateAndInfo
Public Types
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Public Member Functions
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
virtual Actor * Copy () const
virtual void InitState ()
virtual void LoadFromNode (const XNode *pNode)
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void BeginDraw ()
Start the drawing and push the transform on the world matrix stack.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
virtual void DrawPrimitives ()
Draw the primitives of the Actor.
virtual void EndDraw ()
Pop the transform from the world matrix stack.
bool IsFirstUpdate () const
virtual void Update (float fDeltaTime)
virtual void UpdateInternal (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
virtual void FinishTweening ()
virtual void HurryTweening (float factor)
virtual float GetTweenTimeLeft () const
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
virtual void SetZTestMode (ZTestMode mode)
virtual void SetZWrite (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushSelf (lua_State *L)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
virtual void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void HandleMessage (const Message &msg) override
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
virtual void SetUpdateRate (float)
virtual float GetUpdateRate ()
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Static Public Member Functions
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions
float GetEffectDeltaTime () const
Protected Attributes
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Static Protected Attributes
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Private Attributes
map< RString, apActorCommands > m_mapNameToCommands
Detailed Description
Base class for all objects that appear on the screen.
Member Enumeration Documentation
Effect
enum Actor::Effect
The list of the different effects.
todo: split out into diffuse effects and translation effects, or create an effect stack instead. -aj
Enumerator
no_effect
diffuse_blink
diffuse_shift
diffuse_ramp
glow_blink
glow_shift
glow_ramp
rainbow
wag
bounce
bob
pulse
spin
vibrate
EffectClock
enum Actor::EffectClock
Various values an Actor's effect can be tied to.
Enumerator
CLOCK_TIMER
CLOCK_TIMER_GLOBAL
CLOCK_BGM_TIME
CLOCK_BGM_BEAT
CLOCK_BGM_TIME_NO_OFFSET
CLOCK_BGM_BEAT_NO_OFFSET
CLOCK_BGM_BEAT_PLAYER1
CLOCK_BGM_BEAT_PLAYER2
CLOCK_LIGHT_1
CLOCK_LIGHT_LAST
NUM_CLOCKS
StretchType
enum Actor::StretchType
How do we handle stretching the Actor?
Enumerator
fit_inside
Have the Actor fit inside its parent, using the smaller zoom.
cover
Have the Actor cover its parent, using the larger zoom.
Constructor & Destructor Documentation
Actor() [1/2]
Actor::Actor ()
Set up the Actor with its initial settings.
References LuaManager::Get(), InitState(), L, LUA, m_bFirstUpdate, m_FakeParent, m_pLuaInstance, m_pParent, m_size, m_tween_uses_effect_delta, LuaReference::PushSelf(), and LuaManager::Release().
Referenced by Copy(), BackgroundImpl::Layer::CreateBackground(), and BGAnimation::LoadFromNode().
Actor() [2/2]
Actor::Actor (const Actor & cpy)
Copy a new Actor to the old one.
Parameters
cpy the new Actor to use in place of this one.
References ASSERT, CPY, m_baseRotation, m_baseScale, m_bClearZBuffer, m_bFirstUpdate, m_bIsAnimating, m_BlendMode, m_bTextureFiltering, m_bTextureWrapping, m_bVisible, m_bZWrite, m_CullMode, m_current, m_Effect, m_effect_hold_at_full, m_effect_hold_at_half, m_effect_hold_at_zero, m_effect_period, m_effect_ramp_to_full, m_effect_ramp_to_half, m_EffectClock, m_effectColor1, m_effectColor2, m_FakeParent, m_fBaseAlpha, m_fEffectDelta, m_fEffectOffset, m_fHibernateSecondsLeft, m_fHorizAlign, m_fSecsIntoEffect, m_fShadowLengthX, m_fShadowLengthY, m_fVertAlign, m_fZBias, m_iDrawOrder, m_internalDiffuse, m_internalGlow, m_mapNameToCommands, m_pLuaInstance, m_pParent, m_pTempState, m_ShadowColor, m_size, m_sName, m_start, m_Tweens, m_vEffectMagnitude, m_WrapperStates, and m_ZTestMode.
~Actor()
Actor::~Actor () override
References m_WrapperStates, SAFE_DELETE, StopTweening(), and MessageSubscriber::UnsubscribeAll().
Member Function Documentation
AddCommand()
void Actor::AddCommand (const RString & sCmdName, apActorCommands apac, bool warn = true)
References GetLineage(), GetMessageNameFromCommandName(), HasCommand(), m_mapNameToCommands, LuaHelpers::ReportScriptError(), and MessageSubscriber::SubscribeToMessage().
Referenced by LunaActor::addcommand(), TextBanner::Load(), ActorUtil::LoadCommandFromName(), and LoadFromNode().
AddRotationH()
void Actor::AddRotationH (float rot)
References DestTweenState(), RageQuatFromH(), and RageQuatMultiply().
Referenced by LunaActor::heading().
AddRotationP()
void Actor::AddRotationP (float rot)
References DestTweenState(), RageQuatFromP(), and RageQuatMultiply().
Referenced by LunaActor::pitch().
AddRotationR()
void Actor::AddRotationR (float rot)
References DestTweenState(), RageQuatFromR(), and RageQuatMultiply().
Referenced by LunaActor::roll().
AddRotationX()
void Actor::AddRotationX (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::x.
Referenced by LunaActor::addrotationx().
AddRotationY()
void Actor::AddRotationY (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::y.
Referenced by LunaActor::addrotationy().
AddRotationZ()
void Actor::AddRotationZ (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::z.
Referenced by LunaActor::addrotationz().
AddWrapperState()
void Actor::AddWrapperState ()
References ActorFrame::InitState(), and m_WrapperStates.
Referenced by LunaActor::AddWrapperState(), and LunaActor::LunaActor().
AddX()
void Actor::AddX (float x) inline
Add to the x position of this Actor.
Parameters
x the amount to add to the Actor's x position.
References GetDestX(), and SetX().
Referenced by LunaActor::addx().
AddY()
void Actor::AddY (float y) inline
Add to the y position of this Actor.
Parameters
y the amount to add to the Actor's y position.
References GetDestY(), and SetY().
Referenced by LunaActor::addy().
AddZ()
void Actor::AddZ (float z) inline
Add to the z position of this Actor.
Parameters
z the amount to add to the Actor's z position.
References GetDestZ(), and SetZ().
Referenced by LunaActor::addz().
BeginDraw()
void Actor::BeginDraw () virtual
Start the drawing and push the transform on the world matrix stack.
Reimplemented in ActorFrame.
References DISPLAY, f, Actor::TweenState::fSkewX, Actor::TweenState::fSkewY, m_baseRotation, m_baseScale, m_fHorizAlign, m_fVertAlign, m_pTempState, m_size, m_texTranslate, RageDisplay::MultMatrix(), Actor::TweenState::pos, RageDisplay::PreMultMatrix(), RageDisplay::PushMatrix(), Actor::TweenState::quat, RageMatrixFromQuat(), RageMatrixRotationXYZ(), RageMatrixScale(), RageMatrixTranslate(), Actor::TweenState::rotation, SCALE, Actor::TweenState::scale, RageDisplay::SkewX(), RageDisplay::SkewY(), RageDisplay::TexturePushMatrix(), RageDisplay::TextureTranslate(), unlikely, RageVector4::w, RageVector2::x, RageVector3::x, RageVector4::x, RageVector2::y, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
Referenced by ActorFrame::BeginDraw(), and Draw().
BeginTweening() [1/2]
void Actor::BeginTweening (float time, ITween * pInterp) virtual
Reimplemented in NoteColumnRenderer, ActorMultiVertex, and BitmapText.
References ASSERT, FinishTweening(), GetLineage(), GamePreferences::m_AutoPlay, m_current, Actor::TweenInfo::m_fTimeLeftInTween, Actor::TweenInfo::m_fTweenTime, Actor::TweenInfo::m_pTween, m_Tweens, PC_REPLAY, and LuaHelpers::ReportScriptErrorFmt().
Referenced by LunaActor::accelerate(), OptionsCursor::BeginTweening(), BitmapText::BeginTweening(), ActorMultiVertex::BeginTweening(), NoteColumnRenderer::BeginTweening(), BeginTweening(), LunaActor::decelerate(), LunaActor::linear(), QueueCommand(), QueueMessage(), OptionRow::SetDestination(), DualScrollBar::SetPercentage(), BeginnerHelper::ShowStepCircle(), Sleep(), LunaActor::spring(), ScreenHowToPlay::Step(), BeginnerHelper::Step(), and LunaActor::tween().
BeginTweening() [2/2]
void Actor::BeginTweening (float time, TweenType tt = TWEEN_LINEAR)
References ASSERT, BeginTweening(), and ITween::CreateFromType().
CalcPercentThroughTween()
void Actor::CalcPercentThroughTween ()
References m_current, Actor::TweenInfo::m_fTimeLeftInTween, Actor::TweenInfo::m_fTweenTime, Actor::TweenInfo::m_pTween, m_start, m_Tweens, Actor::TweenState::MakeWeightedAverage(), ITween::Tween(), and UpdatePercentThroughTween().
Referenced by UpdateTweening().
Copy()
Actor * Actor::Copy () const virtual
Reimplemented in SongBPMDisplay, ColorBitmapText, ActorFrameAutoDeleteChildren, ActorScrollerAutoDeleteChildren, GraphLine, RoomWheelItem, ControllerStateDisplay, ActorFrameTextureAutoDeleteChildren, WheelItemBase, ActorMultiVertex, MusicWheelItem, PaneDisplay, SongMeterDisplay, InputList, Sprite, HiddenActor, ActorScroller, StepsDisplay, DynamicActorScrollerAutoDeleteChildren, DeviceList, DifficultyIcon, PercentageDisplay, ScoreDisplayAliveTime, BitmapText, ModIconRow, ActorMultiTexture, Model, ActorFrame, Banner, BGAnimation, ComboGraph, StepsDisplayList, GraphDisplay, Quad, ActorProxy, BPMDisplay, GradeDisplay, MeterDisplay, GrooveRadar, TextBanner, ActorSound, HelpDisplay, RollingNumbers, ActorFrameTexture, FadingBanner, HoldJudgment, and DynamicActorScroller.
References Actor().
Referenced by AutoActor::AutoActor(), OptionRow::InitText(), AutoActor::operator=(), ComboGraph::Set(), and GraphDisplay::Set().
DestTweenState() [1/2]
TweenState& Actor::DestTweenState () inline
References m_current, and m_Tweens.
Referenced by AddRotationH(), AddRotationP(), AddRotationR(), AddRotationX(), AddRotationY(), AddRotationZ(), DestTweenState(), FinishTweening(), GetCropBottom(), GetCropLeft(), GetCropRight(), GetCropTop(), GetDestX(), GetDestY(), GetDestZ(), GetDiffuse(), GetDiffuseAlpha(), GetDiffuses(), GetGlow(), GetRotationX(), GetRotationY(), GetRotationZ(), GetSkewX(), GetSkewY(), GetZoom(), GetZoomedHeight(), GetZoomedWidth(), GetZoomX(), GetZoomY(), GetZoomZ(), Player::Init(), SetAux(), SetCropBottom(), SetCropLeft(), SetCropRight(), SetCropTop(), OptionRow::SetDestination(), SetDiffuse(), SetDiffuseBottomEdge(), SetDiffuseColor(), SetDiffuseLeftEdge(), SetDiffuseLowerLeft(), SetDiffuseLowerRight(), SetDiffuseRightEdge(), SetDiffuses(), SetDiffuseTopEdge(), SetDiffuseUpperLeft(), SetDiffuseUpperRight(), SetFadeBottom(), SetFadeLeft(), SetFadeRight(), SetFadeTop(), SetGlow(), SetRotationX(), SetRotationY(), SetRotationZ(), SetSkewX(), SetSkewY(), SetX(), SetXY(), SetY(), SetZ(), SetZoom(), SetZoomX(), SetZoomY(), SetZoomZ(), LuaExpressionTransform::TransformItemCached(), Player::Update(), and OptionRow::UpdateEnabledDisabled().
DestTweenState() [2/2]
const TweenState& Actor::DestTweenState () const inline
References DestTweenState().
Draw()
void Actor::Draw ()
Calls multiple functions for drawing the Actors.
It calls the following in order:
EarlyAbortDraw
BeginDraw
DrawPrimitives
EndDraw
References ASSERT, BeginDraw(), Actor::TweenState::diffuse, DrawPrimitives(), EarlyAbortDraw(), EndDraw(), Actor::TweenState::glow, m_bVisible, m_FakeParent, m_fHibernateSecondsLeft, m_pTempState, m_WrapperStates, PartiallyOpaque(), PostDraw(), PreDraw(), SetInternalDiffuse(), and SetInternalGlow().
Referenced by ScreenManager::Draw(), LunaActor::Draw(), NoteField::draw_timing_segment_text(), NoteDisplay::DrawActor(), NoteField::DrawAreaHighlight(), NoteField::DrawBeatBar(), NoteField::DrawBGChangeText(), NoteField::DrawBoard(), NoteField::DrawBoardPrimitive(), Model::DrawCelShaded(), WheelItemBase::DrawGrayBar(), NoteField::DrawMarkerBar(), Player::DrawNoteFieldBoard(), ActorProxy::DrawPrimitives(), NoteField::DrawPrimitives(), BeginnerHelper::DrawPrimitives(), FadingBanner::DrawPrimitives(), DancingCharacters::DrawPrimitives(), Player::DrawPrimitives(), BackgroundImpl::DrawPrimitives(), ScreenGameplay::DrawPrimitives(), Player::DrawTapJudgments(), LunaActor::LunaActor(), ActorScroller::PositionItemsAndDrawPrimitives(), and MovieTexture_Generic::UpdateFrame().
DrawPrimitives()
virtual void Actor::DrawPrimitives () inline virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented in NoteColumnRenderer, ColorBitmapText, ScreenGameplay, GraphBody, ActorFrame, ActorMultiVertex, BackgroundImpl, BitmapText, GrooveRadar::GrooveRadarValueMap, Player, WheelItemBase, Model, ActorFrameTexture, DancingCharacters, Sprite, FadingBanner, GraphLine, BeginnerHelper, ActorScroller, ActorMultiTexture, NoteField, RollingNumbers, ReceptorArrow, ReceptorArrowRow, GhostArrowRow, ActorProxy, and ScreenSandbox.
Referenced by Draw().
EarlyAbortDraw()
virtual bool Actor::EarlyAbortDraw () const inline virtual
Allow the Actor to be aborted early.
Subclasses may wish to overwrite this to allow for aborted actors.
Returns
false, as by default Actors shouldn't be aborted on drawing.
Reimplemented in ActorMultiVertex, BitmapText, Model, Sprite, Background, WheelNotifyIcon, ActorMultiTexture, Transition, DifficultyIcon, and ActorProxy.
Referenced by Draw(), and ActorProxy::EarlyAbortDraw().
EnableAnimation()
virtual void Actor::EnableAnimation (bool b) inline virtual
Reimplemented in ActorMultiVertex, and Sprite.
References m_bIsAnimating.
Referenced by LunaActor::animate(), Sprite::EnableAnimation(), ActorMultiVertex::EnableAnimation(), LunaActor::pause(), LunaActor::play(), OptionsCursor::SetCanGo(), StartAnimating(), and StopAnimating().
EndDraw()
void Actor::EndDraw () virtual
Pop the transform from the world matrix stack.
Reimplemented in ActorFrame.
References DISPLAY, m_texTranslate, RageDisplay::PopMatrix(), RageDisplay::TexturePopMatrix(), RageVector2::x, and RageVector2::y.
Referenced by Draw(), and ActorFrame::EndDraw().
EraseHeadTween()
virtual void Actor::EraseHeadTween () inline virtual
Reimplemented in NoteColumnRenderer, ActorMultiVertex, and BitmapText.
Referenced by UpdateTweening().
FinishTweening()
void Actor::FinishTweening () virtual
Reimplemented in NoteColumnRenderer, ActorFrame, ActorMultiVertex, and BitmapText.
References DestTweenState(), m_current, m_Tweens, and StopTweening().
Referenced by BeginTweening(), BitmapText::FinishTweening(), ActorMultiVertex::FinishTweening(), NoteColumnRenderer::FinishTweening(), LunaActor::finishtweening(), and Transition::Reset().
get_tween_uses_effect_delta()
bool Actor::get_tween_uses_effect_delta () inline
References m_tween_uses_effect_delta.
GetAnimationLengthSeconds()
virtual float Actor::GetAnimationLengthSeconds () const inline virtual
Reimplemented in ActorMultiVertex, Sprite, and Model.
Referenced by NoteDisplay::SetActiveFrame().
GetAux()
float Actor::GetAux () const inline
References Actor::TweenState::aux, and m_current.
Referenced by LunaActor::getaux().
GetBaseZoomX()
float Actor::GetBaseZoomX () const inline
References m_baseScale, and RageVector3::x.
Referenced by LunaActor::GetBaseZoomX(), and LunaActor::LunaActor().
GetBaseZoomY()
float Actor::GetBaseZoomY () const inline
References m_baseScale, and RageVector3::y.
Referenced by LunaActor::GetBaseZoomY(), and LunaActor::LunaActor().
GetBaseZoomZ()
float Actor::GetBaseZoomZ () const inline
References m_baseScale, and RageVector3::z.
Referenced by LunaActor::GetBaseZoomZ(), and LunaActor::LunaActor().
GetCommand()
const apActorCommands * Actor::GetCommand (const RString & sCommandName) const
References m_mapNameToCommands.
Referenced by LunaActor::GetCommand(), HasCommand(), LunaActor::LunaActor(), PlayCommandNoRecurse(), ActorFrame::PlayCommandOnChildren(), and ActorFrame::PlayCommandOnLeaves().
GetCropBottom()
float Actor::GetCropBottom () const inline
References StepMania::Rect< T >::bottom, Actor::TweenState::crop, and DestTweenState().
GetCropLeft()
float Actor::GetCropLeft () const inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::left.
GetCropRight()
float Actor::GetCropRight () const inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::right.
GetCropTop()
float Actor::GetCropTop () const inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::top.
GetCurrentDiffuseAlpha()
float Actor::GetCurrentDiffuseAlpha () const inline
References RageColor::a, Actor::TweenState::diffuse, and m_current.
Referenced by NoteField::Update().
GetDestX()
float Actor::GetDestX () const inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::x.
Referenced by AddX(), ScreenSelectMaster::GetCursorX(), LunaActor::GetDestX(), OptionRow::GetWidthXY(), LunaActor::LunaActor(), and ScreenOptions::TweenCursor().
GetDestY()
float Actor::GetDestY () const inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::y.
Referenced by AddY(), ScreenSelectMaster::GetCursorY(), LunaActor::GetDestY(), OptionRow::GetWidthXY(), LunaActor::LunaActor(), and ScreenOptions::TweenCursor().
GetDestZ()
float Actor::GetDestZ () const inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::z.
Referenced by AddZ(), LunaActor::GetDestZ(), and LunaActor::LunaActor().
GetDiffuse()
RageColor Actor::GetDiffuse () const inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by WheelItemBase::DrawGrayBar(), and LunaActor::LunaActor().
GetDiffuseAlpha()
float Actor::GetDiffuseAlpha () const inline
References RageColor::a, DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::LunaActor().
GetDiffuses()
RageColor Actor::GetDiffuses (int i) const inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by BitmapText::GetDefaultAttribute(), and SetDiffuseAlpha().
GetDrawOrder()
int Actor::GetDrawOrder () const inline
References m_iDrawOrder.
Referenced by CompareActorsByDrawOrder().
GetEffect()
Effect Actor::GetEffect () const inline
References m_Effect.
GetEffectDelta()
float Actor::GetEffectDelta () const inline
References m_fEffectDelta.
Referenced by LunaActor::GetEffectDelta(), and LunaActor::LunaActor().
GetEffectDeltaTime()
float Actor::GetEffectDeltaTime () const inline protected
References m_fEffectDelta.
Referenced by Sprite::Update(), and ActorMultiVertex::Update().
GetEffectMagnitude()
RageVector3 Actor::GetEffectMagnitude () const inline
References m_vEffectMagnitude.
Referenced by LunaActor::geteffectmagnitude().
GetEffectPeriod()
float Actor::GetEffectPeriod () const inline
References m_effect_period.
Referenced by PreDraw(), SetEffectBob(), and UpdateInternal().
GetFakeParent()
Actor* Actor::GetFakeParent () inline
References m_FakeParent.
Referenced by LunaActor::GetFakeParent(), and LunaActor::LunaActor().
GetGlow()
RageColor Actor::GetGlow () const inline
References DestTweenState(), and Actor::TweenState::glow.
Referenced by WheelItemBase::DrawGrayBar(), BitmapText::GetDefaultAttribute(), and LunaActor::LunaActor().
GetHorizAlign()
virtual float Actor::GetHorizAlign () inline virtual
References m_fHorizAlign.
Referenced by LunaActor::GetHAlign().
GetLineage()
RString Actor::GetLineage () const
Retrieve the Actor's lineage.
Returns
the Actor's lineage.
References GetLineage(), m_pParent, m_sName, and ssprintf().
Referenced by ActorFrame::AddChild(), AddCommand(), BeginTweening(), GetLineage(), ActorUtil::OffCommand(), ActorUtil::OnCommand(), and RunCommands().
GetName()
const RString& Actor::GetName () const inline
Retrieve the Actor's name.
Returns
the Actor's name.
References m_sName.
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), ActorFrame::AddChild(), DebugLineReloadCurrentScreen::DoAndLog(), DebugLineReloadCurrentScreen::GetDisplayValue(), DebugLineRestartCurrentScreen::GetDisplayValue(), DebugLineCurrentScreenOn::GetDisplayValue(), DebugLineCurrentScreenOff::GetDisplayValue(), LunaActor::GetName(), ActorUtil::LoadAllCommands(), ActorUtil::LoadCommand(), PercentageDisplay::LoadFromNode(), LunaActor::LunaActor(), ActorUtil::OffCommand(), ScreenManager::PopTopScreenInternal(), ScreenManager::PrepareScreen(), ScreenManagerUtil::PushLoadedScreen(), ScreenManager::ReloadOverlayScreens(), RoomInfoDisplay::SetRoomInfo(), ActorUtil::SetXY(), and ScreenNetEvaluation::UpdateStats().
GetNumStates()
virtual int Actor::GetNumStates () const inline virtual
Reimplemented in ActorMultiVertex, Sprite, and Model.
Referenced by LunaActor::GetNumStates(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), and LunaActor::LunaActor().
GetNumWrapperStates()
size_t Actor::GetNumWrapperStates () const inline
References m_WrapperStates.
Referenced by LunaActor::AddWrapperState(), LunaActor::get_state_index(), LunaActor::GetNumWrapperStates(), and LunaActor::LunaActor().
GetParent()
Actor* Actor::GetParent () inline
Retrieve the Actor's parent.
Returns
the Actor's parent.
References m_pParent.
Referenced by LunaActor::GetParent(), and LunaActor::LunaActor().
GetRotationX()
float Actor::GetRotationX () const inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::x.
Referenced by LunaActor::getrotation(), LunaActor::GetRotationX(), and LunaActor::LunaActor().
GetRotationY()
float Actor::GetRotationY () const inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::y.
Referenced by LunaActor::getrotation(), LunaActor::GetRotationY(), and LunaActor::LunaActor().
GetRotationZ()
float Actor::GetRotationZ () const inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::z.
Referenced by LunaActor::getrotation(), LunaActor::GetRotationZ(), and LunaActor::LunaActor().
GetSecsIntoEffect()
float Actor::GetSecsIntoEffect () const inline
References m_fSecsIntoEffect.
Referenced by LunaActor::GetSecsIntoEffect(), and LunaActor::LunaActor().
GetSkewX()
float Actor::GetSkewX (float) const inline
References DestTweenState(), and Actor::TweenState::fSkewX.
GetSkewY()
float Actor::GetSkewY (float) const inline
References DestTweenState(), and Actor::TweenState::fSkewY.
GetTweenTimeLeft()
float Actor::GetTweenTimeLeft () const virtual
Reimplemented in ActorFrame, and Transition.
References m_fHibernateSecondsLeft, and m_Tweens.
Referenced by Transition::GetTweenTimeLeft(), ActorFrame::GetTweenTimeLeft(), LunaActor::GetTweenTimeLeft(), LunaActor::LunaActor(), Foreground::Update(), and Transition::UpdateInternal().
GetUnzoomedHeight()
float Actor::GetUnzoomedHeight () const inline
References m_size, and RageVector2::y.
Referenced by NoteDisplay::DrawHoldBody(), NoteDisplay::DrawHoldPart(), LunaActor::GetHeight(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), ScrollBar::SetBarHeight(), NoteField::Update(), BitmapText::UpdateBaseZoom(), and ZoomToHeight().
GetUnzoomedWidth()
float Actor::GetUnzoomedWidth () const inline
References m_size, and RageVector2::x.
Referenced by NoteField::DrawBeatBar(), NoteDisplay::DrawHoldPart(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), OptionsCursor::GetBarWidth(), LunaActor::GetWidth(), ScreenEvaluation::Init(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), ScrollBar::SetPercentage(), MeterDisplay::SetStreamWidth(), BitmapText::UpdateBaseZoom(), ScreenPackages::UpdateProgress(), and ZoomToWidth().
GetUpdateRate()
virtual float Actor::GetUpdateRate () inline virtual
Reimplemented in ActorFrame.
GetVertAlign()
virtual float Actor::GetVertAlign () inline virtual
References m_fVertAlign.
Referenced by LunaActor::GetVAlign().
GetVisible()
bool Actor::GetVisible () const inline
Determine if the Actor is visible at this time.
Returns
true if it's visible, false otherwise.
References m_bVisible.
Referenced by ActorProxy::DrawPrimitives(), LunaActor::GetVisible(), DynamicActorScroller::LoadFromNode(), MusicWheelItem::LoadFromWheelItemData(), LunaActor::LunaActor(), ActorScroller::PositionItemsAndDrawPrimitives(), and Foreground::Update().
GetWrapperState()
Actor * Actor::GetWrapperState (size_t i)
References ASSERT, and m_WrapperStates.
Referenced by LunaActor::AddWrapperState(), LunaActor::GetWrapperState(), and LunaActor::LunaActor().
GetX()
float Actor::GetX () const inline
Retrieve the Actor's x position.
Returns
the Actor's x position.
References m_current, Actor::TweenState::pos, and RageVector3::x.
Referenced by Sprite::CropTo(), Player::DrawPrimitives(), LunaActor::GetX(), HitGuardRailLeft(), HitGuardRailRight(), IsOffScreenLeft(), IsOffScreenRight(), OptionsCursor::Load(), LunaActor::LunaActor(), ScreenPrompt::PositionCursor(), ScreenTextEntryVisual::PositionCursor(), Sprite::ScaleToClipped(), BGAnimationLayer::UpdateInternal(), and ScreenPackages::UpdateProgress().
GetY()
float Actor::GetY () const inline
Retrieve the Actor's y position.
Returns
the Actor's y position.
References m_current, Actor::TweenState::pos, and RageVector3::y.
Referenced by Sprite::CropTo(), Player::DrawPrimitives(), LunaActor::GetY(), HitGuardRailBottom(), HitGuardRailTop(), IsOffScreenBottom(), IsOffScreenTop(), LunaActor::LunaActor(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), ScreenPrompt::PositionCursor(), ScreenTextEntryVisual::PositionCursor(), Sprite::ScaleToClipped(), and BGAnimationLayer::UpdateInternal().
GetZ()
float Actor::GetZ () const inline
Retrieve the Actor's z position.
Returns
the Actor's z position.
References m_current, Actor::TweenState::pos, and RageVector3::z.
Referenced by CompareActorsByZPosition(), LunaActor::GetZ(), LunaActor::LunaActor(), and BGAnimationLayer::UpdateInternal().
GetZoom()
float Actor::GetZoom () const inline
Retrieve the general zoom factor, using the x coordinate of the Actor.
Note that this is not accurate in some cases.
Returns
the zoom factor for the x coordinate of the Actor.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::x.
Referenced by LunaActor::GetZoom(), LunaActor::LunaActor(), PreDraw(), and Player::Update().
GetZoomedHeight()
float Actor::GetZoomedHeight () const inline
References DestTweenState(), m_baseScale, m_size, Actor::TweenState::scale, RageVector2::y, and RageVector3::y.
Referenced by Sprite::CropTo(), GetGuardRailBottom(), GetGuardRailTop(), GetOffScreenBottom(), GetOffScreenTop(), LunaActor::GetZoomedHeight(), LunaActor::LunaActor(), Sprite::ScaleToClipped(), ScrollBar::SetPercentage(), and DualScrollBar::SetPercentage().
GetZoomedWidth()
float Actor::GetZoomedWidth () const inline
References DestTweenState(), m_baseScale, m_size, Actor::TweenState::scale, RageVector2::x, and RageVector3::x.
Referenced by Sprite::CropTo(), GetGuardRailLeft(), GetGuardRailRight(), GetOffScreenLeft(), GetOffScreenRight(), OptionRow::GetWidthXY(), LunaActor::GetZoomedWidth(), GrooveRadar::GrooveRadar(), OptionRow::InitText(), LunaActor::LunaActor(), and Sprite::ScaleToClipped().
GetZoomX()
float Actor::GetZoomX () const inline
Retrieve the zoom factor for the x coordinate of the Actor.
Returns
the zoom factor for the x coordinate of the Actor.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::x.
Referenced by OptionsCursor::GetBarWidth(), LunaActor::GetZoomX(), LunaActor::LunaActor(), and BitmapText::UpdateBaseZoom().
GetZoomY()
float Actor::GetZoomY () const inline
Retrieve the zoom factor for the y coordinate of the Actor.
Returns
the zoom factor for the y coordinate of the Actor.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::y.
Referenced by LunaActor::GetZoomY(), LunaActor::LunaActor(), and BitmapText::UpdateBaseZoom().
GetZoomZ()
float Actor::GetZoomZ () const inline
Retrieve the zoom factor for the z coordinate of the Actor.
Returns
the zoom factor for the z coordinate of the Actor.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::z.
Referenced by LunaActor::GetZoomZ(), and LunaActor::LunaActor().
HandleMessage()
void Actor::HandleMessage (const Message & msg) override virtual
Implements IMessageSubscriber.
Reimplemented in ScreenGameplay, OptionRow, ActorFrame, MusicWheelItem, ScreenSelectMaster, ScreenSelectMusic, NoteField, ModIconRow, ScoreDisplayAliveTime, ScreenMapControllers, StepsDisplayList, HoldJudgment, ScreenSelect, Foreground, ScreenContinue, and ScreenTitleMenu.
References PlayCommandNoRecurse().
Referenced by ScreenSelectMaster::ChangePage(), Foreground::HandleMessage(), ScoreDisplayAliveTime::HandleMessage(), ActorFrame::HandleMessage(), ScreenSelectMaster::HandleScreenMessage(), Player::Init(), PlayCommand(), LunaActor::playcommand(), MusicWheelItem::RefreshGrades(), ScreenMapControllers::SanityCheckWrapper(), StepsDisplay::SetInternal(), OptionRow::SetModIcon(), ReceptorArrow::SetNoteUpcoming(), ReceptorArrow::Step(), and ScreenSyncOverlay::UpdateText().
HasCommand()
bool Actor::HasCommand (const RString & sCmdName) const
References GetCommand().
Referenced by AddCommand(), ScreenMapControllers::BeginScreen(), ScoreDisplayLifeTime::Init(), PercentageDisplay::Load(), StepsDisplay::Load(), ActorUtil::OffCommand(), and ActorUtil::OnCommand().
HurryTweening()
void Actor::HurryTweening (float factor) virtual
Reimplemented in ActorFrame.
References m_Tweens.
Referenced by LunaActor::hurrytweening().
InitState()
void Actor::InitState () virtual
Reimplemented in Sprite, and ActorFrame.
References BLEND_NORMAL, CLOCK_TIMER, CULL_NONE, default_effect_period, f, Actor::TweenState::Init(), m_baseRotation, m_baseScale, m_bClearZBuffer, m_bIsAnimating, m_BlendMode, m_bTextureFiltering, m_bTextureWrapping, m_bVisible, m_bZWrite, m_CullMode, m_current, m_Effect, m_EffectClock, m_effectColor1, m_effectColor2, m_fBaseAlpha, m_fEffectDelta, m_fEffectOffset, m_fHibernateSecondsLeft, m_fHorizAlign, m_fSecsIntoEffect, m_fShadowLengthX, m_fShadowLengthY, m_fVertAlign, m_fZBias, m_iDrawOrder, m_internalDiffuse, m_internalGlow, m_pTempState, m_ShadowColor, m_start, m_texTranslate, m_vEffectMagnitude, m_ZTestMode, no_effect, SetEffectPeriod(), StopTweening(), and ZTEST_OFF.
Referenced by Actor(), ActorFrame::InitState(), and Sprite::InitState().
IsFirstUpdate()
bool Actor::IsFirstUpdate () const
References m_bFirstUpdate.
Referenced by HandleInputEvents(), ScreenReloadSongs::Update(), and ScreenGameplay::~ScreenGameplay().
LoadFromNode()
void Actor::LoadFromNode (const XNode * pNode) virtual
Reimplemented in PaneDisplay, ActorMultiVertex, Sprite, Model, ActorScroller, BPMDisplay, DifficultyIcon, PercentageDisplay, ActorSound, ScoreDisplayAliveTime, BitmapText, StepsDisplayList, ActorMultiTexture, TextBanner, ActorFrame, BGAnimationLayer, GrooveRadar, ActorProxy, BGAnimation, MeterDisplay, Quad, HoldJudgment, and DynamicActorScroller.
References AddCommand(), EndsWith(), FOREACH_CONST_Attr, LuaManager::Get(), XNodeValue::GetValue(), L, StdString::CStdStr< CT >::Left(), LUA, PlayCommandNoRecurse(), XNodeValue::PushValue(), LuaManager::Release(), SetBaseRotationX(), SetBaseRotationY(), SetBaseRotationZ(), SetBaseZoomX(), SetBaseZoomY(), SetBaseZoomZ(), LuaReference::SetFromStack(), and SetName().
Referenced by ActorProxy::LoadFromNode(), Quad::LoadFromNode(), ActorFrame::LoadFromNode(), ActorMultiTexture::LoadFromNode(), BitmapText::LoadFromNode(), ActorSound::LoadFromNode(), DifficultyIcon::LoadFromNode(), Model::LoadFromNode(), Sprite::LoadFromNode(), ActorMultiVertex::LoadFromNode(), and ActorUtil::LoadFromNode().
PartiallyOpaque()
bool Actor::PartiallyOpaque ()
References RageColor::a, Actor::TweenState::diffuse, Actor::TweenState::glow, and m_pTempState.
Referenced by Draw().
PlayCommand()
void Actor::PlayCommand (const RString & sCommandName) inline
References HandleMessage().
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), LifeMeterBattery::AddLives(), ScreenMapControllers::AfterChangeFocus(), ScreenOptions::AfterChangeValueOrRow(), FadingBanner::BeforeChange(), ScreenMapControllers::BeforeChangeFocus(), ScreenWithMenuElements::BeginScreen(), ScreenMapControllers::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenPrompt::BeginScreen(), Screen::BeginScreen(), ScreenWithMenuElements::Cancel(), ScreenSelectMaster::ChangePage(), ScreenSelectMaster::ChangeSelection(), OptionsList::Close(), ScreenMapControllers::DismissWarning(), DebugLineCurrentScreenOn::DoAndLog(), DebugLineCurrentScreenOff::DoAndLog(), ScreenSelectMaster::DoMenuStart(), ReceptorArrow::DrawPrimitives(), Screen::EndScreen(), BrightnessOverlay::FadeToActualBrightness(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenPlayerOptions::HandleScreenMessage(), ScreenNetEvaluation::HandleScreenMessage(), ScreenRanking::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenSyncOverlay::HideHelp(), ScreenOptions::Init(), ScreenTextEntryVisual::Init(), OptionRow::InitText(), ScreenPlayerOptions::Input(), ScreenMapControllers::Input(), ScreenDebugOverlay::Input(), ScreenSelectMusic::Input(), ScreenGameplay::Input(), RoomInfoDisplay::Load(), ReceptorArrow::Load(), WheelBase::Load(), OptionsList::Load(), Player::Load(), FadingBanner::LoadCustom(), ScreenGameplay::LoadNextSong(), FadingBanner::LoadRandom(), FadingBanner::LoadRoulette(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), ActorUtil::OffCommand(), ActorUtil::OnCommand(), OptionsList::Open(), ActorUtil::PlayCommand(), ScreenManager::PlaySharedBackgroundOffCommand(), OptionListRow::PositionCursor(), StepsDisplayList::PositionItems(), ScreenSelectMusic::SelectCurrent(), Player::SetCombo(), PaneDisplay::SetContent(), HoldJudgment::SetHoldJudgment(), ScreenMapControllers::SetListMode(), ReceptorArrow::SetNoteUpcoming(), MenuTimer::SetSeconds(), OptionListRow::SetUnderlines(), ScreenSyncOverlay::ShowHelp(), PlayerInfo::ShowOniGameOver(), Transition::StartTransitioning(), ScreenMapControllers::StartWaitingForPress(), ReceptorArrow::Step(), LifeMeterBattery::SubtractLives(), ScreenWithMenuElements::TweenOffScreen(), ScreenPrompt::TweenOffScreen(), WheelBase::TweenOffScreenForSort(), OptionsList::TweenOnCurrentRow(), ScreenWithMenuElements::TweenOnScreen(), WheelBase::TweenOnScreenForSort(), LyricDisplay::Update(), Foreground::Update(), ReceptorArrow::Update(), NoteField::Update(), ScreenMapControllers::Update(), ControllerStateDisplay::Update(), Sprite::UpdateAnimationState(), OptionRow::UpdateEnabledDisabled(), and UpdateTweening().
PlayCommandNoRecurse()
void Actor::PlayCommandNoRecurse (const Message & msg)
References GetCommand(), Message::GetName(), Message::GetParamTable(), LuaReference::IsSet(), and RunCommands().
Referenced by HandleMessage(), Screen::Init(), LoadFromNode(), and TextBanner::SetFromString().
PostDraw()
void Actor::PostDraw () virtual
Reset internal diffuse and glow.
References RageColor::a, m_internalDiffuse, and m_internalGlow.
Referenced by Draw().
PreDraw()
void Actor::PreDraw () virtual
Calculate values that may be needed for drawing.
References RageColor::a, ASSERT, ASSERT_M, RageColor::b, bob, bounce, Actor::TweenState::diffuse, diffuse_blink, diffuse_ramp, diffuse_shift, f, FAIL_M, fmodfp(), RageColor::g, GetEffectPeriod(), GetZoom(), Actor::TweenState::glow, glow_blink, glow_ramp, glow_shift, m_current, m_Effect, m_effect_hold_at_full, m_effect_hold_at_half, m_effect_ramp_to_full, m_effect_ramp_to_half, m_effectColor1, m_effectColor2, m_fBaseAlpha, m_fEffectOffset, m_fSecsIntoEffect, m_internalDiffuse, m_internalGlow, m_pTempState, m_vEffectMagnitude, no_effect, NUM_DIFFUSE_COLORS, PI, Actor::TweenState::pos, pulse, RageColor::r, RageFastCos(), RageFastSin(), rainbow, randomf(), Actor::TweenState::rotation, SCALE, Actor::TweenState::scale, spin, ssprintf(), vibrate, wag, RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by Draw().
PushContext()
void Actor::PushContext (lua_State * L) virtual
References m_pLuaInstance, and LuaReference::PushSelf().
Referenced by SetParent().
PushSelf()
virtual void Actor::PushSelf (lua_State * L) virtual
Reimplemented in NoteColumnRenderer, ColorBitmapText, ActorMultiVertex, ScreenGameplay, ScreenTextEntry, Player, BitmapText, OptionRow, RoomWheel, Screen, Sprite, WheelBase, WheelItemBase, ScreenWithMenuElementsSimple, ActorScroller, ActorFrame, ControllerStateDisplay, ScreenSelectMusic, MusicWheel, Model, ScreenEvaluation, NoteField, BPMDisplay, ScreenOptions, ScreenSelectMaster, LifeMeter, Banner, PaneDisplay, LifeMeterBattery, FadingBanner, ActorFrameTexture, MenuTimer, ScreenNetSelectBase, StepsDisplay, HelpDisplay, ScreenWithMenuElements, GrooveRadar, ActorMultiTexture, ScreenNetSelectMusic, DifficultyIcon, RollingNumbers, StepsDisplayList, ScreenAttract, ScreenNetRoom, TextBanner, ActorSound, ScoreDisplayAliveTime, ModIconRow, PercentageDisplay, GraphDisplay, ActorProxy, MeterDisplay, ScreenSelectProfile, ComboGraph, HoldJudgment, ScreenHowToPlay, GradeDisplay, ScreenPlayerOptions, ScreenNetEvaluation, ScreenProfileLoad, and ScreenProfileSave.
Referenced by AddToChildTable(), LunaActor::AddWrapperState(), DynamicActorScroller::ConfigureActor(), CreateChildTable(), LunaActor::GetFakeParent(), LunaActor::GetParent(), LunaActorProxy::GetTarget(), LunaScreenManager::GetTopScreen(), LunaActor::GetWrapperState(), RunCommands(), and LuaExpressionTransform::TransformItemDirect().
QueueCommand()
void Actor::QueueCommand (const RString & sCommandName)
References BeginTweening(), Actor::TweenInfo::m_sCommandName, m_Tweens, and TWEEN_LINEAR.
Referenced by LunaActor::queuecommand().
QueueMessage()
void Actor::QueueMessage (const RString & sMessageName)
References BeginTweening(), Actor::TweenInfo::m_sCommandName, m_Tweens, and TWEEN_LINEAR.
Referenced by LunaActor::queuemessage().
RecalcEffectPeriod()
void Actor::RecalcEffectPeriod ()
References m_effect_hold_at_full, m_effect_hold_at_half, m_effect_hold_at_zero, m_effect_period, m_effect_ramp_to_full, and m_effect_ramp_to_half.
Referenced by SetEffectPeriod(), and SetEffectTiming().
RemoveWrapperState()
void Actor::RemoveWrapperState (size_t i)
References ASSERT, m_WrapperStates, and SAFE_DELETE.
Referenced by LunaActor::LunaActor(), and LunaActor::RemoveWrapperState().
ResetEffectTimeIfDifferent()
void Actor::ResetEffectTimeIfDifferent (Effect new_effect)
References m_Effect, and m_fSecsIntoEffect.
Referenced by SetEffectDiffuseBlink(), SetEffectDiffuseRamp(), SetEffectDiffuseShift(), SetEffectGlowBlink(), SetEffectGlowRamp(), SetEffectGlowShift(), SetEffectRainbow(), and SetEffectWag().
RunCommands() [1/2]
void Actor::RunCommands (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) virtual
Reimplemented in ActorFrame.
References LuaManager::Get(), GetLineage(), LuaReference::IsNil(), LuaReference::IsSet(), L, LUA, LuaReference::PushSelf(), PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptErrorFmt(), and LuaHelpers::RunScriptOnStack().
Referenced by BPMDisplay::CycleRandomly(), DancingCharacters::DancingCharacters(), ScreenNetEvaluation::Init(), ScreenHowToPlay::Init(), ScreenPackages::Init(), ScreenMapControllers::Init(), ScreenEvaluation::Init(), HelpDisplay::Load(), BPMDisplay::Load(), BPMDisplay::NoBPM(), PlayCommandNoRecurse(), ActorFrame::RunCommands(), RunCommands(), RunCommandsOnLeaves(), RunCommandsRecursively(), and BPMDisplay::SetBPMRange().
RunCommands() [2/2]
void Actor::RunCommands (const apActorCommands & cmds, const LuaReference * pParamTable = nullptr) inline
References RunCommands().
RunCommandsOnLeaves()
virtual void Actor::RunCommandsOnLeaves (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) inline virtual
Reimplemented in ActorFrame.
References RunCommands().
RunCommandsRecursively()
virtual void Actor::RunCommandsRecursively (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) inline virtual
Reimplemented in ActorFrame.
References RunCommands().
Referenced by LunaActor::LunaActor(), ActorFrame::RunCommandsRecursively(), and LunaActor::RunCommandsRecursively().
ScaleTo()
void Actor::ScaleTo (const RectF & rect, StretchType st)
References cover, fit_inside, StepMania::Rect< T >::GetHeight(), StepMania::Rect< T >::GetWidth(), StepMania::Rect< T >::left, m_fHorizAlign, m_fVertAlign, m_size, SetRotationX(), SetRotationY(), SetX(), SetY(), SetZoom(), StepMania::Rect< T >::top, RageVector2::x, and RageVector2::y.
Referenced by ScaleToCover(), and ScaleToFitInside().
ScaleToCover()
void Actor::ScaleToCover (const RectF & rect) inline
References cover, and ScaleTo().
Referenced by Sprite::CropTo(), Sprite::ScaleToClipped(), and LunaActor::scaletocover().
ScaleToFitInside()
void Actor::ScaleToFitInside (const RectF & rect) inline
References fit_inside, and ScaleTo().
Referenced by LunaActor::scaletofit().
set_tween_uses_effect_delta()
void Actor::set_tween_uses_effect_delta (bool t) inline
References m_tween_uses_effect_delta.
SetAux()
void Actor::SetAux (float f) inline
References Actor::TweenState::aux, DestTweenState(), and f.
Referenced by LunaActor::aux().
SetBaseAlpha()
virtual void Actor::SetBaseAlpha (float fAlpha) inline virtual
References m_fBaseAlpha.
Referenced by LunaActor::basealpha().
SetBaseRotation()
void Actor::SetBaseRotation (const RageVector3 & rot) inline
References m_baseRotation.
SetBaseRotationX()
void Actor::SetBaseRotationX (float rot) inline
References m_baseRotation, and RageVector3::x.
Referenced by LunaActor::baserotationx(), and LoadFromNode().
SetBaseRotationY()
void Actor::SetBaseRotationY (float rot) inline
References m_baseRotation, and RageVector3::y.
Referenced by LunaActor::baserotationy(), and LoadFromNode().
SetBaseRotationZ()
void Actor::SetBaseRotationZ (float rot) inline
References m_baseRotation, and RageVector3::z.
Referenced by LunaActor::baserotationz(), and LoadFromNode().
SetBaseZoom()
void Actor::SetBaseZoom (float zoom) inline
References m_baseScale.
Referenced by LunaActor::basezoom().
SetBaseZoomX()
void Actor::SetBaseZoomX (float zoom) inline
References m_baseScale, and RageVector3::x.
Referenced by LunaActor::basezoomx(), NoteField::Init(), OptionRow::InitText(), LoadFromNode(), and BitmapText::UpdateBaseZoom().
SetBaseZoomY()
void Actor::SetBaseZoomY (float zoom) inline
References m_baseScale, and RageVector3::y.
Referenced by LunaActor::basezoomy(), LoadFromNode(), and BitmapText::UpdateBaseZoom().
SetBaseZoomZ()
void Actor::SetBaseZoomZ (float zoom) inline
References m_baseScale, and RageVector3::z.
Referenced by LunaActor::basezoomz(), and LoadFromNode().
SetBGMLight()
static void Actor::SetBGMLight (int iLightNumber, float fCabinetLights) static
SetBGMTime()
void Actor::SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset) static
References g_fCurrentBGMBeat, g_fCurrentBGMBeatNoOffset, g_fCurrentBGMTime, and g_fCurrentBGMTimeNoOffset.
Referenced by GameState::ResetMusicStatistics(), and GameState::UpdateSongPosition().
SetBlendMode()
void Actor::SetBlendMode (BlendMode mode) inline
References m_BlendMode.
Referenced by ActorScroller::ActorScroller(), LunaActor::blend(), and BGAnimationLayer::LoadFromAniLayerFile().
SetClearZBuffer()
void Actor::SetClearZBuffer (bool b) inline
References m_bClearZBuffer.
Referenced by LunaActor::clearzbuffer().
SetCropBottom()
void Actor::SetCropBottom (float percent) inline
References StepMania::Rect< T >::bottom, Actor::TweenState::crop, and DestTweenState().
Referenced by LunaActor::cropbottom().
SetCropLeft()
void Actor::SetCropLeft (float percent) inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::left.
Referenced by LunaActor::cropleft(), DualScrollBar::Load(), and ComboGraph::Set().
SetCropRight()
void Actor::SetCropRight (float percent) inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::right.
Referenced by LunaActor::cropright(), DualScrollBar::Load(), ComboGraph::Set(), MeterDisplay::SetPercent(), and StreamDisplay::Update().
SetCropTop()
void Actor::SetCropTop (float percent) inline
References Actor::TweenState::crop, DestTweenState(), and StepMania::Rect< T >::top.
Referenced by LunaActor::croptop().
SetCullMode()
virtual void Actor::SetCullMode (CullMode mode) inline virtual
References m_CullMode.
Referenced by LunaActor::backfacecull(), LunaActor::cullmode(), DancingCharacters::DancingCharacters(), ScreenHowToPlay::Init(), BeginnerHelper::Init(), and Model::Model().
SetCurrentTweenStart()
virtual void Actor::SetCurrentTweenStart () inline virtual
Reimplemented in NoteColumnRenderer, ActorMultiVertex, and BitmapText.
Referenced by UpdateTweening().
SetDiffuse()
virtual void Actor::SetDiffuse (const RageColor & c) inline virtual
References DestTweenState().
Referenced by ScreenGameplay::AbortGiveUpText(), ScreenStatsOverlay::AddTimestampLine(), LunaActor::diffuse(), NoteDisplay::DrawActor(), NoteField::DrawAreaHighlight(), NoteField::DrawBeatBar(), WheelItemBase::DrawGrayBar(), ScreenStatsOverlay::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), BackgroundImpl::Init(), MusicWheelItem::LoadFromWheelItemData(), RoomWheelItem::LoadFromWheelItemData(), ScreenSetTime::MenuStart(), HoldJudgment::ResetAnimation(), NoteField::set_text_measure_number_for_draw(), OptionsCursor::SetCanGo(), and ScreenDebugOverlay::UpdateText().
SetDiffuseAlpha()
virtual void Actor::SetDiffuseAlpha (float f) inline virtual
References RageColor::a, f, GetDiffuses(), NUM_DIFFUSE_COLORS, and SetDiffuses().
Referenced by LunaActor::diffusealpha(), StepsDisplayList::HideRows(), BeginnerHelper::Init(), OptionRow::PositionUnderlines(), BeginnerHelper::Step(), LifeMeterTime::Update(), and StreamDisplay::Update().
SetDiffuseBottomEdge()
void Actor::SetDiffuseBottomEdge (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffusebottomedge().
SetDiffuseColor()
void Actor::SetDiffuseColor (const RageColor & c)
References RageColor::b, DestTweenState(), RageColor::g, and RageColor::r.
Referenced by LunaActor::diffusecolor(), RoomWheelItem::LoadFromWheelItemData(), and ScreenRanking::SetPage().
SetDiffuseLeftEdge()
void Actor::SetDiffuseLeftEdge (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuseleftedge().
SetDiffuseLowerLeft()
void Actor::SetDiffuseLowerLeft (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuselowerleft().
SetDiffuseLowerRight()
void Actor::SetDiffuseLowerRight (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuselowerright().
SetDiffuseRightEdge()
void Actor::SetDiffuseRightEdge (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuserightedge().
SetDiffuses()
void Actor::SetDiffuses (int i, const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by SetDiffuseAlpha().
SetDiffuseTopEdge()
void Actor::SetDiffuseTopEdge (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffusetopedge().
SetDiffuseUpperLeft()
void Actor::SetDiffuseUpperLeft (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuseupperleft().
SetDiffuseUpperRight()
void Actor::SetDiffuseUpperRight (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::diffuse.
Referenced by LunaActor::diffuseupperright().
SetDrawOrder()
void Actor::SetDrawOrder (int iOrder) inline
References m_iDrawOrder.
Referenced by LunaActor::draworder(), ScreenPlayerOptions::Init(), ScreenGameplayLesson::Init(), ScreenWithMenuElements::Init(), ScreenNetRoom::Init(), ScreenMapControllers::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenGameplay::Init(), ScreenOptions::InitMenu(), and OptionRow::InitText().
SetEffectBob()
void Actor::SetEffectBob (float fPeriod, const RageVector3 & vect)
References ASSERT, bob, GetEffectPeriod(), m_Effect, m_fSecsIntoEffect, m_vEffectMagnitude, and SetEffectPeriod().
Referenced by LunaActor::bob().
SetEffectBounce()
void Actor::SetEffectBounce (float fPeriod, const RageVector3 & vect)
References ASSERT, bounce, m_Effect, m_fSecsIntoEffect, m_vEffectMagnitude, and SetEffectPeriod().
Referenced by LunaActor::bounce().
SetEffectClock()
void Actor::SetEffectClock (EffectClock c) inline
References m_EffectClock.
Referenced by LifeMeterTime::Load(), and SetEffectClockString().
SetEffectClockString()
void Actor::SetEffectClockString (const RString & s)
References CLOCK_BGM_BEAT, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_TIME, CLOCK_BGM_TIME_NO_OFFSET, CLOCK_TIMER, CLOCK_TIMER_GLOBAL, StdString::CStdStr< CT >::EqualsNoCase(), and SetEffectClock().
Referenced by LunaActor::effectclock().
SetEffectColor1()
void Actor::SetEffectColor1 (const RageColor & c) inline
References m_effectColor1.
Referenced by LunaActor::effectcolor1().
SetEffectColor2()
void Actor::SetEffectColor2 (const RageColor & c) inline
References m_effectColor2.
Referenced by LunaActor::effectcolor2().
SetEffectDiffuseBlink()
void Actor::SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, diffuse_blink, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by LunaActor::diffuseblink().
SetEffectDiffuseRamp()
void Actor::SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, diffuse_ramp, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by LunaActor::diffuseramp().
SetEffectDiffuseShift()
void Actor::SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, diffuse_shift, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by ScreenSetTime::ChangeSelection(), LunaActor::diffuseshift(), LifeMeterTime::Load(), BGAnimationLayer::LoadFromAniLayerFile(), and NoteField::NoteField().
SetEffectGlowBlink()
void Actor::SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, glow_blink, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by LunaActor::glowblink().
SetEffectGlowRamp()
void Actor::SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, glow_ramp, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by LunaActor::glowramp().
SetEffectGlowShift()
void Actor::SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor & c1, const RageColor & c2)
References ASSERT, glow_shift, m_effectColor1, m_effectColor2, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by LunaActor::glowshift().
SetEffectHoldAtFull()
bool Actor::SetEffectHoldAtFull (float haf, RString & err)
References m_effect_hold_at_half, m_effect_hold_at_zero, m_effect_ramp_to_full, m_effect_ramp_to_half, and SetEffectTiming().
Referenced by LunaActor::effect_hold_at_full().
SetEffectMagnitude()
void Actor::SetEffectMagnitude (const RageVector3 & vec) inline
References m_vEffectMagnitude.
Referenced by LunaActor::effectmagnitude().
SetEffectOffset()
void Actor::SetEffectOffset (float fTime) inline
References m_fEffectOffset.
Referenced by LunaActor::effectoffset().
SetEffectPeriod()
void Actor::SetEffectPeriod (float fTime)
References ASSERT, m_effect_hold_at_full, m_effect_hold_at_half, m_effect_hold_at_zero, m_effect_ramp_to_full, m_effect_ramp_to_half, and RecalcEffectPeriod().
Referenced by LunaActor::effectperiod(), InitState(), SetEffectBob(), SetEffectBounce(), SetEffectDiffuseBlink(), SetEffectDiffuseRamp(), SetEffectDiffuseShift(), SetEffectGlowBlink(), SetEffectGlowRamp(), SetEffectGlowShift(), SetEffectPulse(), SetEffectRainbow(), and SetEffectWag().
SetEffectPulse()
void Actor::SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
References ASSERT, m_Effect, m_vEffectMagnitude, pulse, and SetEffectPeriod().
Referenced by LunaActor::pulse().
SetEffectRainbow()
void Actor::SetEffectRainbow (float fEffectPeriodSeconds)
References ASSERT, rainbow, ResetEffectTimeIfDifferent(), and SetEffectPeriod().
Referenced by BGAnimationLayer::LoadFromAniLayerFile(), and LunaActor::rainbow().
SetEffectSpin()
void Actor::SetEffectSpin (const RageVector3 & vect)
References m_Effect, m_vEffectMagnitude, and spin.
Referenced by LunaActor::spin().
SetEffectTiming()
bool Actor::SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString & err)
References m_effect_hold_at_full, m_effect_hold_at_half, m_effect_hold_at_zero, m_effect_ramp_to_full, m_effect_ramp_to_half, RecalcEffectPeriod(), and ssprintf().
Referenced by LunaActor::effecttiming(), and SetEffectHoldAtFull().
SetEffectVibrate()
void Actor::SetEffectVibrate (const RageVector3 & vect)
References m_Effect, m_vEffectMagnitude, and vibrate.
Referenced by LunaActor::vibrate().
SetEffectWag()
void Actor::SetEffectWag (float fPeriod, const RageVector3 & vect)
References ASSERT, m_vEffectMagnitude, ResetEffectTimeIfDifferent(), SetEffectPeriod(), and wag.
Referenced by LunaActor::wag().
SetFadeBottom()
void Actor::SetFadeBottom (float percent) inline
References StepMania::Rect< T >::bottom, DestTweenState(), and Actor::TweenState::fade.
Referenced by LunaActor::fadebottom().
SetFadeLeft()
void Actor::SetFadeLeft (float percent) inline
References DestTweenState(), Actor::TweenState::fade, and StepMania::Rect< T >::left.
Referenced by LunaActor::fadeleft().
SetFadeRight()
void Actor::SetFadeRight (float percent) inline
References DestTweenState(), Actor::TweenState::fade, and StepMania::Rect< T >::right.
Referenced by LunaActor::faderight().
SetFadeTop()
void Actor::SetFadeTop (float percent) inline
References DestTweenState(), Actor::TweenState::fade, and StepMania::Rect< T >::top.
Referenced by LunaActor::fadetop().
SetFakeParent()
void Actor::SetFakeParent (Actor * mailman) inline
References m_FakeParent.
Referenced by LunaActor::LunaActor(), and LunaActor::SetFakeParent().
SetGlobalDiffuseColor()
void Actor::SetGlobalDiffuseColor (const RageColor & c)
References RageColor::b, Actor::TweenState::diffuse, RageColor::g, m_current, m_start, m_Tweens, NUM_DIFFUSE_COLORS, and RageColor::r.
SetGlobalRenderStates()
void Actor::SetGlobalRenderStates () virtual
Set the global rendering states of this Actor.
This should be called at the beginning of an Actor's DrawPrimitives() call.
References BLEND_NO_EFFECT, RageDisplay::ClearZBuffer(), DISPLAY, f, g_bShowMasks, Preference< T >::Get(), m_bClearZBuffer, m_BlendMode, m_bZWrite, m_CullMode, m_fZBias, m_ZTestMode, RageDisplay::SetBlendMode(), RageDisplay::SetCullMode(), RageDisplay::SetZBias(), RageDisplay::SetZTestMode(), and RageDisplay::SetZWrite().
Referenced by ActorMultiTexture::DrawPrimitives(), GraphLine::DrawPrimitives(), Model::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), BitmapText::DrawPrimitives(), GraphBody::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), and Sprite::DrawTexture().
SetGlow()
void Actor::SetGlow (const RageColor & c) inline
References DestTweenState(), and Actor::TweenState::glow.
Referenced by NoteDisplay::DrawActor(), NoteField::DrawBeatBar(), WheelItemBase::DrawGrayBar(), LunaActor::glow(), and NoteField::set_text_measure_number_for_draw().
SetHeight()
void Actor::SetHeight (float height) inline
References m_size, and RageVector2::y.
Referenced by ActorScroller::EnableMask(), ScreenNetEvaluation::Init(), ComboGraph::Load(), LunaActor::LunaActor(), LunaActor::SetHeight(), and LunaActor::setsize().
SetHibernate()
void Actor::SetHibernate (float fSecs) inline
References m_fHibernateSecondsLeft.
Referenced by ScreenMapControllers::BeginScreen(), LunaActor::hibernate(), ScreenWithMenuElements::StartTransitioningScreen(), and StepsDisplayList::TweenOnScreen().
SetHorizAlign() [1/2]
virtual void Actor::SetHorizAlign (float f) inline virtual
Reimplemented in BitmapText.
References f, and m_fHorizAlign.
Referenced by MovieTexture_Generic::CreateTexture(), LunaActor::halign(), LunaActor::horizalign(), BitmapText::SetHorizAlign(), and SetHorizAlign().
SetHorizAlign() [2/2]
void Actor::SetHorizAlign (HorizAlign ha) inline
References f, HorizAlign_Center, HorizAlign_Left, and SetHorizAlign().
SetInternalDiffuse()
void Actor::SetInternalDiffuse (const RageColor & c) inline
References m_internalDiffuse.
Referenced by Draw(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
SetInternalGlow()
void Actor::SetInternalGlow (const RageColor & c) inline
References m_internalGlow.
Referenced by Draw(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
SetName()
virtual void Actor::SetName (const RString & sName) inline virtual
Set the Actor's name to a new one.
Parameters
sName the new name for the Actor.
References m_sName.
Referenced by ScreenPrompt::BeginScreen(), FadingBanner::FadingBanner(), GrooveRadar::GrooveRadar(), ScreenGameplaySyncMachine::Init(), ScreenNetEvaluation::Init(), ScreenPlayerOptions::Init(), ScreenInstallOverlay::Init(), ScreenNetSelectBase::Init(), ScreenHowToPlay::Init(), ScreenNetRoom::Init(), ScreenReloadSongs::Init(), ScreenWithMenuElements::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScoreDisplayLifeTime::Init(), ScreenStatsOverlay::Init(), BeginnerHelper::Init(), ScreenNetSelectMusic::Init(), ScreenDebugOverlay::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), LifeMeterBar::LifeMeterBar(), DualScrollBar::Load(), ModIcon::Load(), HoldJudgment::Load(), RoomInfoDisplay::Load(), LifeMeterBattery::Load(), PercentageDisplay::Load(), ModIconRow::Load(), LifeMeterTime::Load(), TextBanner::Load(), GraphDisplay::Load(), MenuTimer::Load(), OptionRowType::Load(), StepsDisplay::Load(), PaneDisplay::Load(), WheelBase::Load(), OptionsList::Load(), RoomWheelItem::Load(), ScreenMapControllers::ActionRow::Load(), AutoActor::LoadAndSetName(), MeterDisplay::LoadFromNode(), LoadFromNode(), Foreground::LoadFromSong(), LyricDisplay::LyricDisplay(), MusicWheelItem::MusicWheelItem(), LunaActor::name(), NoteField::NoteField(), Player::Player(), ScreenManager::PrepareScreen(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayOni::ScoreDisplayOni(), ScoreDisplayPercentage::ScoreDisplayPercentage(), and WheelItemBase::WheelItemBase().
SetParent()
void Actor::SetParent (Actor * pParent)
Give this Actor a new parent.
Parameters
pParent the new parent Actor.
References LuaManager::Get(), L, LUA, m_pParent, PushContext(), and LuaManager::Release().
Referenced by ActorFrame::AddChild(), and ActorUtil::LoadFromNode().
SetPlayerBGMBeat()
void Actor::SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset) static
References g_vfCurrentBGMBeatPlayer, and g_vfCurrentBGMBeatPlayerNoOffset.
Referenced by GameState::UpdateSongPosition().
SetRotationX()
void Actor::SetRotationX (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::x.
Referenced by ScreenHowToPlay::Init(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), LunaActor::rotationx(), ScaleTo(), and NoteColumnRenderArgs::SetPRZForActor().
SetRotationY()
void Actor::SetRotationY (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::y.
Referenced by LunaActor::rotationy(), ScaleTo(), NoteColumnRenderArgs::SetPRZForActor(), ScreenHowToPlay::Step(), and BeginnerHelper::Step().
SetRotationZ()
void Actor::SetRotationZ (float rot) inline
References DestTweenState(), Actor::TweenState::rotation, and RageVector3::z.
Referenced by LunaActor::rotationz(), and NoteColumnRenderArgs::SetPRZForActor().
SetSecondsIntoAnimation()
virtual void Actor::SetSecondsIntoAnimation (float) inline virtual
Reimplemented in ActorMultiVertex, Sprite, and Model.
Referenced by NoteDisplay::SetActiveFrame().
SetShadowColor()
void Actor::SetShadowColor (const RageColor & c) inline
References m_ShadowColor.
Referenced by LunaActor::shadowcolor().
SetShadowLength()
void Actor::SetShadowLength (float fLength) inline
References m_fShadowLengthX, and m_fShadowLengthY.
Referenced by BitmapText::BitmapText(), ScreenPackages::Init(), ScreenStatsOverlay::Init(), ScreenRanking::Init(), ScreenEvaluation::Init(), ScreenGameplay::Init(), RoomInfoDisplay::Load(), NoteField::NoteField(), ScoreDisplayOni::ScoreDisplayOni(), and LunaActor::shadowlength().
SetShadowLengthX()
void Actor::SetShadowLengthX (float fLengthX) inline
References m_fShadowLengthX.
Referenced by LunaActor::shadowlengthx().
SetShadowLengthY()
void Actor::SetShadowLengthY (float fLengthY) inline
References m_fShadowLengthY.
Referenced by LunaActor::shadowlengthy().
SetSkewX()
void Actor::SetSkewX (float fAmount) inline
References DestTweenState(), and Actor::TweenState::fSkewX.
Referenced by LunaActor::skewx().
SetSkewY()
void Actor::SetSkewY (float fAmount) inline
References DestTweenState(), and Actor::TweenState::fSkewY.
Referenced by LunaActor::skewy().
SetState()
virtual void Actor::SetState (int) inline virtual
Reimplemented in Sprite, and Model.
Referenced by ScreenRanking::Init(), BGAnimationLayer::LoadFromAniLayerFile(), BGAnimationLayer::LoadFromNode(), HoldJudgment::SetHoldJudgment(), LunaActor::setstate(), and SnapDisplay::SnapModeChanged().
SetTextureFiltering()
void Actor::SetTextureFiltering (bool b) inline
References m_bTextureFiltering.
Referenced by LunaActor::LunaActor(), and LunaActor::SetTextureFiltering().
SetTextureRenderStates()
void Actor::SetTextureRenderStates () virtual
Set the texture rendering states of this Actor.
This should be called after setting a texture for the Actor.
References DISPLAY, m_bTextureFiltering, m_bTextureWrapping, RageDisplay::SetTextureFiltering(), RageDisplay::SetTextureWrapping(), and TextureUnit_1.
Referenced by GraphLine::DrawPrimitives(), Model::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), GraphBody::DrawPrimitives(), and Sprite::DrawTexture().
SetTextureTranslate()
void Actor::SetTextureTranslate (float x, float y) inline
References m_texTranslate, RageVector2::x, and RageVector2::y.
Referenced by LunaActor::texturetranslate().
SetTextureWrapping()
void Actor::SetTextureWrapping (bool b) inline
References m_bTextureWrapping.
Referenced by BGAnimationLayer::LoadFromNode(), and LunaActor::texturewrapping().
SetUpdateRate()
virtual void Actor::SetUpdateRate (float) inline virtual
Reimplemented in ActorFrame.
SetUseZBuffer()
void Actor::SetUseZBuffer (bool b) inline
References SetZTestMode(), SetZWrite(), ZTEST_OFF, and ZTEST_WRITE_ON_PASS.
Referenced by ActorScroller::ActorScroller(), Model::Model(), and LunaActor::zbuffer().
SetVertAlign() [1/2]
virtual void Actor::SetVertAlign (float f) inline virtual
References f, and m_fVertAlign.
Referenced by MovieTexture_Generic::CreateTexture(), ScreenGameplay::Init(), ScrollBar::ScrollBar(), SetVertAlign(), LunaActor::valign(), and LunaActor::vertalign().
SetVertAlign() [2/2]
void Actor::SetVertAlign (VertAlign va) inline
References f, SetVertAlign(), VertAlign_Middle, and VertAlign_Top.
SetVisible()
void Actor::SetVisible (bool b) inline
References m_bVisible.
Referenced by OptionRow::AfterImportOptions(), ScreenSelectMaster::BeginScreen(), ScreenSelectMusic::BeginScreen(), ScreenOptions::BeginScreen(), ActorScroller::DisableMask(), ActorProxy::DrawPrimitives(), ActorScroller::EnableMask(), DualScrollBar::EnablePlayer(), MenuTimer::EnableStealth(), HiddenActor::HiddenActor(), ScreenNetRoom::InfoSetVisible(), ScreenPlayerOptions::Init(), ScreenDebugOverlay::Init(), ScreenRanking::Init(), ScreenEvaluation::Init(), GradeDisplay::Load(), Foreground::LoadFromSong(), MusicWheelItem::LoadFromWheelItemData(), ScreenGameplay::LoadNextSong(), OptionRow::PositionUnderlines(), LifeMeterBattery::Refresh(), MusicWheelItem::RefreshGrades(), ScreenOptions::RestartOptions(), ModIcon::Set(), ComboGraph::Set(), GraphDisplay::Set(), ScreenNetSelectBase::SetChatboxVisible(), StepsDisplay::SetInternal(), ScreenRanking::SetPage(), WheelBase::SetPositions(), ScreenNetSelectBase::SetUsersVisible(), StepsDisplay::Unset(), ScreenSyncOverlay::Update(), Foreground::Update(), ScreenStatsOverlay::Update(), LifeMeterBar::Update(), ScreenDebugOverlay::Update(), StreamDisplay::Update(), ControllerStateDisplay::Update(), ScreenPlayerOptions::UpdateDisqualified(), ScreenDebugOverlay::UpdateText(), ScreenNetSelectBase::UpdateUsers(), and LunaActor::visible().
SetWidth()
void Actor::SetWidth (float width) inline
References m_size, and RageVector2::x.
Referenced by ActorScroller::EnableMask(), ScreenNetEvaluation::Init(), ScreenEvaluation::Init(), ComboGraph::Load(), LunaActor::LunaActor(), LunaActor::setsize(), LunaActor::SetWidth(), and ScreenPackages::UpdateProgress().
SetX()
void Actor::SetX (float x) inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::x.
Referenced by AddX(), DancingCharacters::DancingCharacters(), NoteField::DrawBeatBar(), ScreenStatsOverlay::Init(), BeginnerHelper::Init(), ScreenOptions::Init(), OptionRow::InitText(), SnapDisplay::Load(), OptionRow::PositionIcons(), OptionRow::PositionUnderlines(), ScaleTo(), ComboGraph::Set(), GraphDisplay::Set(), OptionsCursor::SetBarWidth(), MeterDisplay::SetPercent(), NoteColumnRenderArgs::SetPRZForActor(), BGAnimationLayer::UpdateInternal(), ScreenPackages::UpdateProgress(), ScreenDebugOverlay::UpdateText(), and LunaActor::x().
SetXY()
void Actor::SetXY (float x, float y) inline
References DestTweenState(), Actor::TweenState::pos, RageVector3::x, and RageVector3::y.
Referenced by ScreenTextEntryVisual::BeginScreen(), ScreenSelectMaster::ChangePage(), ScreenSelectMaster::ChangeSelection(), Sprite::CropTo(), DancingCharacters::DancingCharacters(), NoteField::DrawBeatBar(), ScreenNetEvaluation::Init(), ScreenTestSound::Init(), ScreenReloadSongs::Init(), BeginnerHelper::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), ScreenRanking::Init(), ScreenGameplay::Init(), ModIconRow::Load(), PaneDisplay::Load(), BGAnimationLayer::LoadFromNode(), ScreenMiniMenu::MiniMenu(), OptionListRow::PositionCursor(), ScreenPrompt::PositionCursor(), ScreenOptions::PositionCursor(), ScreenTextEntryVisual::PositionCursor(), HoldJudgment::ResetAnimation(), Sprite::ScaleToClipped(), NoteField::set_text_measure_number_for_draw(), ActorUtil::SetXY(), StretchTo(), ScreenOptions::TweenCursor(), ScreenSelectMaster::TweenOnScreen(), and LunaActor::xy().
SetY()
void Actor::SetY (float y) inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::y.
Referenced by AddY(), NoteField::DrawBeatBar(), ScreenStatsOverlay::Init(), BeginnerHelper::Init(), Player::Load(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), StepsDisplayList::PositionItems(), ScaleTo(), ScrollBar::SetBarHeight(), ScrollBar::SetPercentage(), DualScrollBar::SetPercentage(), NoteColumnRenderArgs::SetPRZForActor(), ScreenOptions::TweenCursor(), BGAnimationLayer::UpdateInternal(), ScreenDebugOverlay::UpdateText(), and LunaActor::y().
SetZ()
void Actor::SetZ (float z) inline
References DestTweenState(), Actor::TweenState::pos, and RageVector3::z.
Referenced by AddZ(), NoteColumnRenderArgs::SetPRZForActor(), BGAnimationLayer::UpdateInternal(), and LunaActor::z().
SetZBias()
void Actor::SetZBias (float f) inline
References f, and m_fZBias.
Referenced by LunaActor::zbias().
SetZoom()
void Actor::SetZoom (float zoom) inline
Set the zoom factor for all dimensions of the Actor.
Parameters
zoom the zoom factor for all dimensions.
References DestTweenState(), Actor::TweenState::scale, RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by Sprite::CropTo(), ScreenTestSound::Init(), BeginnerHelper::Init(), NoteField::Init(), BGAnimationLayer::LoadFromNode(), NoteField::NoteField(), Player::PlayerNoteFieldPositioner::PlayerNoteFieldPositioner(), ScaleTo(), Sprite::ScaleToClipped(), NoteField::set_text_measure_number_for_draw(), BeginnerHelper::ShowStepCircle(), Player::Update(), and LunaActor::zoom().
SetZoomX()
void Actor::SetZoomX (float zoom) inline
Set the zoom factor for the x dimension of the Actor.
Parameters
zoom the zoom factor for the x dimension.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::x.
Referenced by NoteField::DrawBeatBar(), NoteColumnRenderArgs::SetPRZForActor(), MeterDisplay::SetStreamWidth(), StretchTo(), ZoomToWidth(), and LunaActor::zoomx().
SetZoomY()
void Actor::SetZoomY (float zoom) inline
Set the zoom factor for the y dimension of the Actor.
Parameters
zoom the zoom factor for the y dimension.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::y.
Referenced by ScrollBar::SetBarHeight(), NoteColumnRenderArgs::SetPRZForActor(), StretchTo(), ZoomToHeight(), and LunaActor::zoomy().
SetZoomZ()
void Actor::SetZoomZ (float zoom) inline
Set the zoom factor for the z dimension of the Actor.
Parameters
zoom the zoom factor for the z dimension.
References DestTweenState(), Actor::TweenState::scale, and RageVector3::z.
Referenced by NoteColumnRenderArgs::SetPRZForActor(), and LunaActor::zoomz().
SetZTestMode()
virtual void Actor::SetZTestMode (ZTestMode mode) inline virtual
Reimplemented in ActorFrame.
References m_ZTestMode.
Referenced by SetUseZBuffer(), LunaActor::ztest(), and LunaActor::ztestmode().
SetZWrite()
virtual void Actor::SetZWrite (bool b) inline virtual
Reimplemented in ActorFrame.
References m_bZWrite.
Referenced by Model::DrawCelShaded(), SetUseZBuffer(), and LunaActor::zwrite().
Sleep()
void Actor::Sleep (float time)
References ASSERT, BeginTweening(), and TWEEN_LINEAR.
Referenced by LunaActor::sleep(), and BeginnerHelper::Step().
StartAnimating()
void Actor::StartAnimating () inline
References EnableAnimation().
StopAnimating()
void Actor::StopAnimating () inline
References EnableAnimation().
Referenced by GrooveRadar::GrooveRadar(), ScreenRanking::Init(), ScreenEvaluation::Init(), HoldJudgment::Load(), DifficultyIcon::Load(), BGAnimationLayer::LoadFromAniLayerFile(), NoteField::NoteField(), SnapDisplay::SnapDisplay(), and WheelNotifyIcon::WheelNotifyIcon().
StopEffect()
void Actor::StopEffect () inline
References m_Effect, and no_effect.
Referenced by ScreenPrompt::Change(), ScreenSetTime::ChangeSelection(), HoldJudgment::ResetAnimation(), BeginnerHelper::ShowStepCircle(), BeginnerHelper::Step(), LunaActor::stopeffect(), and MenuTimer::Update().
StopTweening()
void Actor::StopTweening () virtual
Reimplemented in NoteColumnRenderer, ActorMultiVertex, BitmapText, and OptionsCursor.
References m_Tweens.
Referenced by FinishTweening(), InitState(), HoldJudgment::ResetAnimation(), OptionRow::SetDestination(), DualScrollBar::SetPercentage(), BeginnerHelper::ShowStepCircle(), ScreenHowToPlay::Step(), BeginnerHelper::Step(), OptionsCursor::StopTweening(), BitmapText::StopTweening(), ActorMultiVertex::StopTweening(), NoteColumnRenderer::StopTweening(), LunaActor::stoptweening(), and ~Actor().
StretchTo()
void Actor::StretchTo (const RectF & rect)
References StepMania::Rect< T >::GetHeight(), StepMania::Rect< T >::GetWidth(), StepMania::Rect< T >::left, m_size, SetXY(), SetZoomX(), SetZoomY(), StepMania::Rect< T >::top, RageVector2::x, and RageVector2::y.
Referenced by NoteField::DrawAreaHighlight(), NoteField::DrawMarkerBar(), ScreenStatsOverlay::Init(), ScreenDebugOverlay::Init(), BackgroundImpl::Init(), BGAnimationLayer::LoadFromNode(), ScrollBar::SetPercentage(), and LunaActor::stretchto().
Update()
void Actor::Update (float fDeltaTime) virtual
Reimplemented in SongBPMDisplay, ScreenTextEntry, ScreenGameplay, BackgroundImpl, ActorMultiVertex, Screen, ControllerStateDisplay, BrightnessOverlay, GrooveRadar::GrooveRadarValueMap, Player, ScreenOptions, ScreenNetSelectMusic, WheelBase, Model, ScreenSelectMusic, Sprite, InputList, DancingCharacters, SongMeterDisplay, HelpDisplay, ScreenPackages, WheelNotifyIcon, BeginnerHelper, ScreenSetTime, Banner, BPMDisplay, ScreenDebugOverlay, StreamDisplay, LifeMeterTime, MenuTimer, PercentageDisplay, RollingNumbers, LifeMeterBar, LifeMeterBattery, NoteField, ScoreDisplayLifeTime, ScreenMapControllers, ScreenWithMenuElements, ScreenStatsOverlay, ScreenTestSound, ReceptorArrow, ScoreDisplayAliveTime, ScreenHowToPlay, ScoreDisplayOni, Foreground, ReceptorArrowRow, ScreenReloadSongs, DeviceList, RoomInfoDisplay, ScreenInstallOverlay, ScreenSelect, GhostArrowRow, ScreenSyncOverlay, ScreenGameplaySyncMachine, LyricDisplay, and ScreenSandbox.
References ASSERT_M, m_fHibernateSecondsLeft, m_WrapperStates, ssprintf(), and UpdateInternal().
Referenced by LyricDisplay::Update(), RoomInfoDisplay::Update(), DeviceList::Update(), Foreground::Update(), ReceptorArrowRow::Update(), ScoreDisplayOni::Update(), ReceptorArrow::Update(), ScoreDisplayAliveTime::Update(), NoteField::Update(), LifeMeterBattery::Update(), LifeMeterBar::Update(), ScoreDisplayLifeTime::Update(), PercentageDisplay::Update(), RollingNumbers::Update(), MenuTimer::Update(), ScreenManager::Update(), LifeMeterTime::Update(), BPMDisplay::Update(), StreamDisplay::Update(), BeginnerHelper::Update(), HelpDisplay::Update(), SongMeterDisplay::Update(), InputList::Update(), Sprite::Update(), Model::Update(), WheelBase::Update(), Player::Update(), GrooveRadar::GrooveRadarValueMap::Update(), BrightnessOverlay::Update(), ControllerStateDisplay::Update(), Screen::Update(), ActorMultiVertex::Update(), BackgroundImpl::Update(), NoteDisplay::Update(), FadingBanner::UpdateInternal(), and ActorFrame::UpdateInternal().
UpdateInternal()
void Actor::UpdateInternal (float fDeltaTime) virtual
Reimplemented in ActorFrame, FadingBanner, ActorScroller, BGAnimationLayer, and Transition.
References CLOCK_BGM_BEAT, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2, CLOCK_BGM_TIME, CLOCK_BGM_TIME_NO_OFFSET, CLOCK_TIMER, CLOCK_TIMER_GLOBAL, g_fCurrentBGMBeat, g_fCurrentBGMBeatNoOffset, g_fCurrentBGMTime, g_fCurrentBGMTimeNoOffset, g_vfCurrentBGMBeatPlayer, generic_global_timer_update(), GetEffectPeriod(), RageTimer::GetUsecsSinceStart(), m_bFirstUpdate, m_current, m_Effect, m_EffectClock, m_fEffectDelta, m_fSecsIntoEffect, m_tween_uses_effect_delta, m_vEffectMagnitude, PLAYER_1, PLAYER_2, Actor::TweenState::rotation, spin, UpdateTweening(), wrap(), RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by Update(), FadingBanner::UpdateInternal(), and ActorFrame::UpdateInternal().
UpdatePercentThroughTween()
virtual void Actor::UpdatePercentThroughTween (float PercentThroughTween) inline virtual
Reimplemented in NoteColumnRenderer, ActorMultiVertex, and BitmapText.
Referenced by CalcPercentThroughTween().
UpdateTweening()
void Actor::UpdateTweening (float fDeltaTime)
References MessageManager::Broadcast(), CalcPercentThroughTween(), EraseHeadTween(), StdString::CStdStr< CT >::Left(), m_current, Actor::TweenInfo::m_fTimeLeftInTween, Actor::TweenInfo::m_fTweenTime, Actor::TweenInfo::m_sCommandName, m_start, m_Tweens, MESSAGEMAN, min(), PlayCommand(), and SetCurrentTweenStart().
Referenced by UpdateInternal().
ZoomTo()
void Actor::ZoomTo (float fX, float fY) inline
References ZoomToHeight(), and ZoomToWidth().
Referenced by LunaActor::zoomto().
ZoomToHeight()
void Actor::ZoomToHeight (float zoom) inline
References GetUnzoomedHeight(), and SetZoomY().
Referenced by ComboGraph::Load(), LifeMeterTime::Load(), GraphDisplay::Load(), ZoomTo(), and LunaActor::zoomtoheight().
ZoomToWidth()
void Actor::ZoomToWidth (float zoom) inline
References GetUnzoomedWidth(), and SetZoomX().
Referenced by ComboGraph::Load(), LifeMeterTime::Load(), GraphDisplay::Load(), OptionsCursor::SetBarWidth(), ZoomTo(), and LunaActor::zoomtowidth().
Member Data Documentation
g_fCurrentBGMBeat
float Actor::g_fCurrentBGMBeat static protected
Referenced by SetBGMTime(), and UpdateInternal().
g_fCurrentBGMBeatNoOffset
float Actor::g_fCurrentBGMBeatNoOffset = 0 static protected
Referenced by SetBGMTime(), and UpdateInternal().
g_fCurrentBGMTime
float Actor::g_fCurrentBGMTime = 0 static protected
Referenced by SetBGMTime(), and UpdateInternal().
g_fCurrentBGMTimeNoOffset
float Actor::g_fCurrentBGMTimeNoOffset = 0 static protected
Referenced by SetBGMTime(), and UpdateInternal().
g_vfCurrentBGMBeatPlayer
vector< float > Actor::g_vfCurrentBGMBeatPlayer static protected
Referenced by SetPlayerBGMBeat(), and UpdateInternal().
g_vfCurrentBGMBeatPlayerNoOffset
vector< float > Actor::g_vfCurrentBGMBeatPlayerNoOffset static protected
Referenced by SetPlayerBGMBeat().
m_baseRotation
RageVector3 Actor::m_baseRotation protected
Referenced by Actor(), BeginDraw(), InitState(), SetBaseRotation(), SetBaseRotationX(), SetBaseRotationY(), and SetBaseRotationZ().
m_baseScale
RageVector3 Actor::m_baseScale protected
Referenced by Actor(), BeginDraw(), GetBaseZoomX(), GetBaseZoomY(), GetBaseZoomZ(), GetZoomedHeight(), GetZoomedWidth(), InitState(), SetBaseZoom(), SetBaseZoomX(), SetBaseZoomY(), and SetBaseZoomZ().
m_bClearZBuffer
bool Actor::m_bClearZBuffer protected
Referenced by Actor(), ActorFrame::DrawPrimitives(), InitState(), SetClearZBuffer(), and SetGlobalRenderStates().
m_bFirstUpdate
bool Actor::m_bFirstUpdate protected
Referenced by Actor(), Screen::BeginScreen(), IsFirstUpdate(), Transition::Reset(), NoteField::Update(), and UpdateInternal().
m_bIsAnimating
bool Actor::m_bIsAnimating protected
Referenced by Actor(), Sprite::EnableAnimation(), ActorMultiVertex::EnableAnimation(), EnableAnimation(), InitState(), Sprite::Update(), and ActorMultiVertex::Update().
m_BlendMode
BlendMode Actor::m_BlendMode protected
Referenced by Actor(), InitState(), SetBlendMode(), and SetGlobalRenderStates().
m_bTextureFiltering
bool Actor::m_bTextureFiltering protected
Referenced by Actor(), InitState(), SetTextureFiltering(), and SetTextureRenderStates().
m_bTextureWrapping
bool Actor::m_bTextureWrapping protected
Referenced by Actor(), ActorMultiTexture::DrawPrimitives(), InitState(), Model::Model(), Sprite::SetCustomTextureCoords(), Sprite::SetCustomTextureRect(), SetTextureRenderStates(), SetTextureWrapping(), and Sprite::Update().
m_bVisible
bool Actor::m_bVisible protected
Referenced by Actor(), Draw(), GetVisible(), InitState(), and SetVisible().
m_bZWrite
bool Actor::m_bZWrite protected
Referenced by Actor(), InitState(), SetGlobalRenderStates(), and SetZWrite().
m_CullMode
CullMode Actor::m_CullMode protected
Referenced by Actor(), InitState(), SetCullMode(), and SetGlobalRenderStates().
m_current
TweenState Actor::m_current protected
Referenced by Actor(), BeginTweening(), CalcPercentThroughTween(), DestTweenState(), FinishTweening(), GetAux(), GetCurrentDiffuseAlpha(), GetX(), GetY(), GetZ(), InitState(), PreDraw(), SetGlobalDiffuseColor(), UpdateInternal(), and UpdateTweening().
m_Effect
Effect Actor::m_Effect protected
Referenced by Actor(), GetEffect(), InitState(), PreDraw(), ResetEffectTimeIfDifferent(), SetEffectBob(), SetEffectBounce(), SetEffectPulse(), SetEffectSpin(), SetEffectVibrate(), StopEffect(), and UpdateInternal().
m_effect_hold_at_full
float Actor::m_effect_hold_at_full protected
Referenced by Actor(), PreDraw(), RecalcEffectPeriod(), SetEffectPeriod(), and SetEffectTiming().
m_effect_hold_at_half
float Actor::m_effect_hold_at_half protected
Referenced by Actor(), PreDraw(), RecalcEffectPeriod(), SetEffectHoldAtFull(), SetEffectPeriod(), and SetEffectTiming().
m_effect_hold_at_zero
float Actor::m_effect_hold_at_zero protected
Referenced by Actor(), RecalcEffectPeriod(), SetEffectHoldAtFull(), SetEffectPeriod(), and SetEffectTiming().
m_effect_period
float Actor::m_effect_period protected
Referenced by Actor(), GetEffectPeriod(), and RecalcEffectPeriod().
m_effect_ramp_to_full
float Actor::m_effect_ramp_to_full protected
Referenced by Actor(), PreDraw(), RecalcEffectPeriod(), SetEffectHoldAtFull(), SetEffectPeriod(), and SetEffectTiming().
m_effect_ramp_to_half
float Actor::m_effect_ramp_to_half protected
Referenced by Actor(), PreDraw(), RecalcEffectPeriod(), SetEffectHoldAtFull(), SetEffectPeriod(), and SetEffectTiming().
m_EffectClock
EffectClock Actor::m_EffectClock protected
Referenced by Actor(), InitState(), SetEffectClock(), and UpdateInternal().
m_effectColor1
RageColor Actor::m_effectColor1 protected
Referenced by Actor(), InitState(), PreDraw(), SetEffectColor1(), SetEffectDiffuseBlink(), SetEffectDiffuseRamp(), SetEffectDiffuseShift(), SetEffectGlowBlink(), SetEffectGlowRamp(), and SetEffectGlowShift().
m_effectColor2
RageColor Actor::m_effectColor2 protected
Referenced by Actor(), InitState(), PreDraw(), SetEffectColor2(), SetEffectDiffuseBlink(), SetEffectDiffuseRamp(), SetEffectDiffuseShift(), SetEffectGlowBlink(), SetEffectGlowRamp(), and SetEffectGlowShift().
m_FakeParent
Actor* Actor::m_FakeParent protected
Referenced by Actor(), Draw(), GetFakeParent(), and SetFakeParent().
m_fBaseAlpha
float Actor::m_fBaseAlpha protected
Referenced by Actor(), InitState(), PreDraw(), and SetBaseAlpha().
m_fEffectDelta
float Actor::m_fEffectDelta protected
Referenced by Actor(), GetEffectDelta(), GetEffectDeltaTime(), InitState(), and UpdateInternal().
m_fEffectOffset
float Actor::m_fEffectOffset protected
Referenced by Actor(), InitState(), PreDraw(), and SetEffectOffset().
m_fHibernateSecondsLeft
float Actor::m_fHibernateSecondsLeft protected
Referenced by Actor(), Draw(), GetTweenTimeLeft(), InitState(), SetHibernate(), HelpDisplay::Update(), and Update().
m_fHorizAlign
float Actor::m_fHorizAlign protected
The particular horizontal alignment.
Use the defined constant values for best effect.
Referenced by Actor(), BeginDraw(), BitmapText::BuildChars(), GetHorizAlign(), InitState(), ScaleTo(), BitmapText::SetHorizAlign(), and SetHorizAlign().
m_fSecsIntoEffect
float Actor::m_fSecsIntoEffect protected
Referenced by Actor(), GetSecsIntoEffect(), InitState(), PreDraw(), ResetEffectTimeIfDifferent(), SetEffectBob(), SetEffectBounce(), and UpdateInternal().
m_fShadowLengthX
float Actor::m_fShadowLengthX protected
Referenced by Actor(), BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), Sprite::DrawTexture(), InitState(), SetShadowLength(), and SetShadowLengthX().
m_fShadowLengthY
float Actor::m_fShadowLengthY protected
Referenced by Actor(), BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), Sprite::DrawTexture(), InitState(), SetShadowLength(), and SetShadowLengthY().
m_fVertAlign
float Actor::m_fVertAlign protected
The particular vertical alignment.
Use the defined constant values for best effect.
Referenced by Actor(), BeginDraw(), GetVertAlign(), InitState(), ScaleTo(), and SetVertAlign().
m_fZBias
float Actor::m_fZBias protected
The amount of bias.
If 0, there is no bias. If 1, there is a full bias.
Referenced by Actor(), InitState(), SetGlobalRenderStates(), and SetZBias().
m_iDrawOrder
int Actor::m_iDrawOrder protected
The draw order priority.
The lower this number is, the sooner it is drawn.
Referenced by Actor(), GetDrawOrder(), InitState(), and SetDrawOrder().
m_internalDiffuse
RageColor Actor::m_internalDiffuse protected
Referenced by Actor(), BitmapText::DrawPrimitives(), InitState(), PostDraw(), PreDraw(), and SetInternalDiffuse().
m_internalGlow
RageColor Actor::m_internalGlow protected
Referenced by Actor(), BitmapText::DrawPrimitives(), InitState(), PostDraw(), PreDraw(), and SetInternalGlow().
m_mapNameToCommands
map<RString, apActorCommands> Actor::m_mapNameToCommands private
Referenced by Actor(), AddCommand(), and GetCommand().
m_pLuaInstance
HiddenPtr<LuaClass> Actor::m_pLuaInstance
Referenced by Actor(), and PushContext().
m_pParent
Actor* Actor::m_pParent protected
the current parent of this Actor if it exists.
Referenced by Actor(), GetLineage(), GetParent(), and SetParent().
m_pTempState
TweenState* Actor::m_pTempState protected
Temporary variables that are filled just before drawing.
Referenced by Actor(), BeginDraw(), Draw(), BitmapText::DrawChars(), RollingNumbers::DrawPart(), RollingNumbers::DrawPrimitives(), ActorMultiTexture::DrawPrimitives(), GraphLine::DrawPrimitives(), Sprite::DrawPrimitives(), Model::DrawPrimitives(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), BitmapText::DrawPrimitives(), ActorFrame::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), NoteColumnRenderer::DrawPrimitives(), InitState(), PartiallyOpaque(), and PreDraw().
m_ShadowColor
RageColor Actor::m_ShadowColor protected
Referenced by Actor(), BitmapText::DrawPrimitives(), ColorBitmapText::DrawPrimitives(), Sprite::DrawTexture(), InitState(), and SetShadowColor().
m_size
RageVector2 Actor::m_size protected
Referenced by Actor(), BeginDraw(), BitmapText::BuildChars(), ActorFrameTexture::Create(), Sprite::CropTo(), ActorMultiTexture::DrawPrimitives(), Sprite::DrawTexture(), GetUnzoomedHeight(), GetUnzoomedWidth(), GetZoomedHeight(), GetZoomedWidth(), GraphDisplay::Load(), Sprite::LoadFromNode(), ScaleTo(), Sprite::ScaleToClipped(), SetHeight(), GrooveRadar::GrooveRadarValueMap::SetRadius(), ActorMultiTexture::SetSizeFromTexture(), Sprite::SetTexture(), SetWidth(), StretchTo(), and GraphDisplay::UpdateVerts().
m_sName
RString Actor::m_sName protected
the name of the Actor.
Referenced by Actor(), AutoScreenMessage(), ScreenOptionsManageProfiles::BeginScreen(), ScreenServiceAction::BeginScreen(), ScreenAttract::BeginScreen(), ScreenWithMenuElements::BeginScreen(), ScreenMapControllers::BeginScreen(), ScreenSelectMusic::BeginScreen(), Screen::BeginScreen(), RoomWheel::BuildFromRoomDatas(), ScreenGameplay::FailFadeRemovePlayer(), GetLineage(), GetName(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenNetRoom::HandleScreenMessage(), ScreenPackages::HandleScreenMessage(), ScreenAttract::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenOptions::HandleScreenMessage(), ScreenProfileLoad::Init(), ScreenGameplaySyncMachine::Init(), ScreenSyncOverlay::Init(), ScreenOptionsMaster::Init(), ScreenPlayerOptions::Init(), ScreenSelect::Init(), ScreenContinue::Init(), ScreenSplash::Init(), ScreenSystemLayer::Init(), ScreenNetSelectBase::Init(), ScreenAttract::Init(), ScreenHowToPlay::Init(), ScreenReloadSongs::Init(), ScreenWithMenuElements::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScreenStatsOverlay::Init(), ScreenNetSelectMusic::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Screen::Init(), ScreenGameplay::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), ScreenTitleMenu::Input(), RoomInfoDisplay::Load(), BPMDisplay::Load(), WheelBase::Load(), OptionsList::Load(), RoomWheel::Load(), StepsDisplayList::LoadFromNode(), ScreenSelectMaster::MenuStart(), ScreenNetEvaluation::RedoUserTexts(), ScreenMapControllers::SanityCheckWrapper(), ScreenMapControllers::SetListMode(), SetName(), Sprite::SetState(), ScreenSelect::Update(), ScreenSelectMusic::Update(), ScreenNetworkOptions::UpdateConnectStatus(), ScreenNetEvaluation::UpdateStats(), and ScreenNetSelectBase::UpdateUsers().
m_start
TweenState Actor::m_start protected
Referenced by Actor(), CalcPercentThroughTween(), InitState(), SetGlobalDiffuseColor(), and UpdateTweening().
m_texTranslate
RageVector2 Actor::m_texTranslate protected
Referenced by BeginDraw(), EndDraw(), InitState(), and SetTextureTranslate().
m_tween_uses_effect_delta
bool Actor::m_tween_uses_effect_delta protected
Referenced by Actor(), get_tween_uses_effect_delta(), set_tween_uses_effect_delta(), and UpdateInternal().
m_Tweens
vector<TweenStateAndInfo*> Actor::m_Tweens protected
Referenced by Actor(), BeginTweening(), CalcPercentThroughTween(), DestTweenState(), FinishTweening(), GetTweenTimeLeft(), HurryTweening(), QueueCommand(), QueueMessage(), SetGlobalDiffuseColor(), StopTweening(), and UpdateTweening().
m_vEffectMagnitude
RageVector3 Actor::m_vEffectMagnitude protected
Referenced by Actor(), GetEffectMagnitude(), InitState(), PreDraw(), SetEffectBob(), SetEffectBounce(), SetEffectMagnitude(), SetEffectPulse(), SetEffectSpin(), SetEffectVibrate(), SetEffectWag(), and UpdateInternal().
m_WrapperStates
vector<Actor*> Actor::m_WrapperStates protected
Referenced by Actor(), AddWrapperState(), Draw(), GetNumWrapperStates(), GetWrapperState(), RemoveWrapperState(), Update(), and ~Actor().
m_ZTestMode
ZTestMode Actor::m_ZTestMode protected
Referenced by Actor(), InitState(), SetGlobalRenderStates(), and SetZTestMode().
The documentation for this class was generated from the following files:
Actor.h
Actor.cpp