Etterna: NoteDisplay.cpp File Reference
NoteDisplay.cpp File Reference
#include "NoteDisplay.h"
#include "ActorUtil.h"
#include "ArrowEffects.h"
#include "Foreach.h"
#include "GameState.h"
#include "GhostArrowRow.h"
#include "LuaBinding.h"
#include "NoteData.h"
#include "NoteSkinManager.h"
#include "NoteTypes.h"
#include "PlayerState.h"
#include "RageDisplay.h"
#include "RageMath.h"
#include "RageTexture.h"
#include "ReceptorArrowRow.h"
#include "Sprite.h"
#include "Style.h"
#include "global.h"
Classes
struct NoteMetricCache_t
struct NoteSkinAndPath
struct NoteResource
struct StripBuffer
struct LunaNCSplineHandler
struct LunaNoteColumnRenderer
Macros
#define FOREACH_NotePart(i) FOREACH_ENUM(NotePart, i)
A foreach loop going through the different NoteParts.
#define BOOLS_FROM_CLOSEST(closest)
#define DTS_INNER(pn, tap_set, draw_func, disp)
#define DRAW_TAP_SET(tap_set, draw_func)
#define WEIGHT_FOR_ME(me) NCSplineHandler::MakeWeightedAverage(out.me, from.me, to.me, between);
#define SET_T(member, name)
#define SET_B(member, name)
#define GET_HANDLER(member, name)
Enumerations
enum hold_part_type { hpt_top, hpt_body, hpt_bottom }
Functions
const RString & NoteNotePartToString (NotePart i)
XToString (NotePart)
LuaXType (NotePart)
XToString (NoteColorType)
StringToX (NoteColorType)
LuaXType (NoteColorType)
XToString (NoteColumnSplineMode)
StringToX (NoteColumnSplineMode)
LuaXType (NoteColumnSplineMode)
static bool IsVectorZero (const RageVector2 &v)
static NoteResource * MakeNoteResource (const RString &sButton, const RString &sElement, PlayerNumber pn, GameController gc, bool bSpriteOnly, RString Color)
static void DeleteNoteResource (NoteResource *pRes)
XToString (HoldType)
XToString (ActiveType)
float NoteRowToVisibleBeat (const PlayerState *pPlayerState, int iRow)
static float ArrowGetAlphaOrGlow (bool bGlow, const PlayerState *pPlayerState, int iCol, float fYOffset, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar)
LUA_REGISTER_CLASS (NCSplineHandler)
Variables
static const double PI_180 = PI / 180.0
static const double PI_180R = 180.0 / PI
static const char * NotePartNames []
static const char * NoteColorTypeNames []
static const char * NoteColumnSplineModeNames []
struct NoteMetricCache_t * NoteMetricCache
static map< RString, map< NoteSkinAndPath, NoteResource * > > g_NoteResource
static const char * HoldTypeNames []
static const char * ActiveTypeNames []
static map< int, map< int, map< int, float > > > HoldSize
Macro Definition Documentation
BOOLS_FROM_CLOSEST
#define BOOLS_FROM_CLOSEST (closest)
Value:
out.m_spline_mode = (closest).m_spline_mode;                               \
    out.m_subtract_song_beat_from_curr =                                       \
      (closest).m_subtract_song_beat_from_curr;
Referenced by NCSplineHandler::MakeWeightedAverage().
DRAW_TAP_SET
#define DRAW_TAP_SET (tap_set, draw_func)
Value:
FOREACH_PlayerNumber(pn)                                                   \
    {                                                                          \
        DTS_INNER(pn, tap_set, draw_func, m_displays[pn]);                     \
    }
Referenced by NoteColumnRenderer::DrawPrimitives().
DTS_INNER
#define DTS_INNER (pn, tap_set, draw_func, disp)
Value:
if (!(tap_set)[pn].empty()) {                                              \
        any_upcoming |= (disp)->draw_func(                                     \
          *m_field_render_args, m_column_render_args, (tap_set)[pn]);          \
    }
Referenced by NoteColumnRenderer::DrawPrimitives().
FOREACH_NotePart
#define FOREACH_NotePart (i) FOREACH_ENUM(NotePart, i)
A foreach loop going through the different NoteParts.
Referenced by NoteMetricCache_t::Load().
GET_HANDLER
#define GET_HANDLER (member, name)
Value:
static int name(T* p, lua_State* L)                                        \
    {                                                                          \
        p->member->PushSelf(L);                                                \
        return 1;                                                              \
    }
SET_B
#define SET_B (member, name)
Value:
static int name(T* p, lua_State* L)                                        \
    {                                                                          \
        p->member = BArg(1);                                                   \
        COMMON_RETURN_SELF;                                                    \
    }
SET_T
#define SET_T (member, name)
Value:
static int name(T* p, lua_State* L)                                        \
    {                                                                          \
        p->member = FArg(1);                                                   \
        COMMON_RETURN_SELF;                                                    \
    }
WEIGHT_FOR_ME
#define WEIGHT_FOR_ME (me) NCSplineHandler::MakeWeightedAverage(out.me, from.me, to.me, between);
Referenced by NoteColumnRenderer::NCR_TweenState::MakeWeightedAverage().
Enumeration Type Documentation
hold_part_type
enum hold_part_type
Enumerator
hpt_top
hpt_body
hpt_bottom
Function Documentation
ArrowGetAlphaOrGlow()
static float ArrowGetAlphaOrGlow (bool bGlow, const PlayerState * pPlayerState, int iCol, float fYOffset, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar) static
References ArrowEffects::GetAlpha(), and ArrowEffects::GetGlow().
Referenced by NoteDisplay::DrawHoldPart().
DeleteNoteResource()
static void DeleteNoteResource (NoteResource * pRes) static
References ASSERT, ASSERT_M, g_NoteResource, NoteResource::m_iRefCount, NoteResource::m_nsap, and ssprintf().
Referenced by NoteColorActor::~NoteColorActor(), and NoteColorSprite::~NoteColorSprite().
IsVectorZero()
static bool IsVectorZero (const RageVector2 & v) static
References RageVector2::x, and RageVector2::y.
Referenced by NoteDisplay::DrawActor().
LUA_REGISTER_CLASS()
LUA_REGISTER_CLASS (NCSplineHandler)
LuaXType() [1/3]
LuaXType (NotePart)
LuaXType() [2/3]
LuaXType (NoteColorType)
LuaXType() [3/3]
LuaXType (NoteColumnSplineMode)
MakeNoteResource()
static NoteResource* MakeNoteResource (const RString & sButton, const RString & sElement, PlayerNumber pn, GameController gc, bool bSpriteOnly, RString Color) static
References ASSERT, g_NoteResource, NoteSkinManager::GetCurrentNoteSkin(), NoteSkinManager::LoadActor(), NoteResource::m_iRefCount, NOTESKIN, NoteSkinManager::SetGameController(), NoteSkinManager::SetPlayerNumber(), and ssprintf().
Referenced by NoteColorActor::Load(), and NoteColorSprite::Load().
NoteNotePartToString()
const RString& NoteNotePartToString (NotePart i)
NoteRowToVisibleBeat()
float NoteRowToVisibleBeat (const PlayerState * pPlayerState, int iRow) inline
References NoteRowToBeat().
Referenced by NoteDisplay::DrawHold(), NoteDisplay::DrawHoldsInRange(), and NoteDisplay::DrawTapsInRange().
StringToX() [1/2]
StringToX (NoteColorType)
StringToX() [2/2]
StringToX (NoteColumnSplineMode)
XToString() [1/5]
XToString (NotePart)
XToString() [2/5]
XToString (NoteColorType)
XToString() [3/5]
XToString (NoteColumnSplineMode)
XToString() [4/5]
XToString (HoldType)
XToString() [5/5]
XToString (ActiveType)
Variable Documentation
ActiveTypeNames
const char* ActiveTypeNames[] static
Initial value:
= {
    "Active",
    "Inactive",
}
g_NoteResource
map<RString, map<NoteSkinAndPath, NoteResource*> > g_NoteResource static
Referenced by DeleteNoteResource(), MakeNoteResource(), and NoteDisplay::Update().
HoldSize
map<int, map<int, map<int, float> > > HoldSize static
Referenced by NoteDisplay::DrawHold().
HoldTypeNames
const char* HoldTypeNames[] static
Initial value:
= {
    "Hold",
    "Roll",
}
NoteColorTypeNames
const char* NoteColorTypeNames[] static
Initial value:
= {
    "Denominator",
    "Progress",
}
NoteColumnSplineModeNames
const char* NoteColumnSplineModeNames[] static
Initial value:
= {
    "Disabled",
    "Offset",
    "Position",
}
NoteMetricCache
struct NoteMetricCache_t * NoteMetricCache
NotePartNames
const char* NotePartNames[] static
Initial value:
= {
    "TapNote",  "TapMine",  "TapLift",  "TapFake",     "HoldHead",
    "HoldTail", "HoldTopCap", "HoldBody", "HoldBottomCap",
}
PI_180
const double PI_180 = PI / 180.0 static
PI_180R
const double PI_180R = 180.0 / PI static
Referenced by NoteDisplay::DrawHoldPart(), and NoteColumnRenderArgs::SetPRZForActor().