Etterna: LWZState::Code Struct Reference
LWZState::Code Struct Reference
Public Member Functions
void Init ()
int Get (RageFile &f, int code_size)
Public Attributes
unsigned char buf [280]
int curbit
int lastbit
int last_byte
bool done
Member Function Documentation
Get()
int LWZState::Code::Get (RageFile & f, int code_size)
References LWZState::code_size, and GetDataBlock().
Referenced by LWZState::ReadByte().
Init()
void LWZState::Code::Init ()
References buf, curbit, done, last_byte, and lastbit.
Referenced by LWZState::Init().
Member Data Documentation
buf
unsigned char LWZState::Code::buf[280]
Referenced by Init().
curbit
int LWZState::Code::curbit
Referenced by Init().
done
bool LWZState::Code::done
Referenced by Init(), and LWZState::ReadByte().
last_byte
int LWZState::Code::last_byte
Referenced by Init().
lastbit
int LWZState::Code::lastbit
Referenced by Init().
The documentation for this struct was generated from the following file:
RageSurface_Load_GIF.cpp