Etterna: ScreenOptions Class Reference
ScreenOptions Class Reference abstract
A grid of options; the selected option is drawn with a highlight rectangle.
#include <ScreenOptions.h>
Public Member Functions
ScreenOptions ()
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
void InitMenu (const vector< OptionRowHandler *> &vHands)
~ScreenOptions () override
void Update (float fDeltaTime) override
bool Input (const InputEventPlus &input) override
void HandleScreenMessage (ScreenMessage SM) override
void TweenOnScreen () override
void TweenOffScreen () override
void PushSelf (lua_State *L) override
Public Member Functions inherited from ScreenWithMenuElements
ScreenWithMenuElements ()
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
~ScreenWithMenuElements () override
void HandleScreenMessage (ScreenMessage SM) override
void Update (float fDeltaTime) override
void StartTransitioningScreen (ScreenMessage smSendWhenDone)
virtual void Cancel (ScreenMessage smSendWhenDone)
bool IsTransitioning ()
bool AllowCallbackInput () override
void StopTimer ()
void ResetTimer ()
void PushSelf (lua_State *L) override
bool AllowLateJoin () const override
Determine if we allow extra players to join in on this screen.
Public Member Functions inherited from Screen
~Screen () override
virtual void EndScreen ()
This is called when the screen is popped.
void SetLockInputSecs (float f)
void PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
void ClearMessageQueue ()
Clear the entire message queue.
void ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
virtual ScreenType GetScreenType () const
bool AllowOperatorMenuButton () const
RString GetNextScreenName () const
RString GetPrevScreen () const
void SetNextScreenName (RString const &name)
void SetPrevScreenName (RString const &name)
bool PassInputToLua (const InputEventPlus &input)
void AddInputCallbackFromStack (lua_State *L)
void RemoveInputCallback (lua_State *L)
virtual bool MenuCoin (const InputEventPlus &)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Types
enum Navigation {
NAV_THREE_KEY, NAV_THREE_KEY_MENU, NAV_THREE_KEY_ALT, NAV_FIVE_KEY,
NAV_TOGGLE_THREE_KEY, NAV_TOGGLE_FIVE_KEY
}
Protected Member Functions
virtual void ImportOptions (int iRow, const vector< PlayerNumber > &vpns)=0
virtual void ExportOptions (int iRow, const vector< PlayerNumber > &vpns)=0
void RestartOptions ()
void GetWidthXY (PlayerNumber pn, int iRow, int iChoiceOnRow, int &iWidthOut, int &iXOut, int &iYOut) const
RString GetExplanationText (int iRow) const
void RefreshIcons (int iRow, PlayerNumber pn)
void PositionCursor (PlayerNumber pn)
void PositionRows (bool bTween)
void TweenCursor (PlayerNumber pn)
void StoreFocus (PlayerNumber pn)
void BeginFadingOut ()
virtual bool FocusedItemEndsScreen (PlayerNumber pn) const
RString GetNextScreenForFocusedItem (PlayerNumber pn) const
void ChangeValueInRowRelative (int iRow, PlayerNumber pn, int iDelta, bool bRepeat)
void ChangeValueInRowAbsolute (int iRow, PlayerNumber pn, int iChoiceIndex, bool bRepeat)
virtual void AfterChangeValueInRow (int iRow, PlayerNumber pn)
Perform an action after a row has changed its value.
bool MoveRowRelative (PlayerNumber pn, int iDir, bool bRepeat)
bool MoveRowAbsolute (PlayerNumber pn, int iRow)
virtual void AfterChangeRow (PlayerNumber pn)
Perform an action after moving to a new row.
virtual void AfterChangeValueOrRow (PlayerNumber pn)
bool MenuBack (const InputEventPlus &input) override
bool MenuStart (const InputEventPlus &input) override
virtual void ProcessMenuStart (const InputEventPlus &input)
bool MenuLeft (const InputEventPlus &input) override
bool MenuRight (const InputEventPlus &input) override
bool MenuUp (const InputEventPlus &input) override
bool MenuDown (const InputEventPlus &input) override
bool MenuSelect (const InputEventPlus &input) override
virtual void MenuUpDown (const InputEventPlus &input, int iDir)
int GetCurrentRow (PlayerNumber pn=PLAYER_1) const
bool AllAreOnLastRow () const
OptionRow * GetRow (int iRow) const
int GetNumRows () const
void SetNavigation (Navigation nav)
void SetInputMode (InputMode im)
Protected Member Functions inherited from ScreenWithMenuElements
RString HandleLuaMusicFile (RString const &path)
virtual void StartPlayingMusic ()
void SetHelpText (const RString &s)
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
vector< OptionRow * > m_pRows
Map menu lines to m_OptionRow entries.
int m_iCurrentRow [NUM_PLAYERS]
The current row each player is on.
OptionRowType m_OptionRowTypeNormal
OptionRowType m_OptionRowTypeExit
Navigation m_OptionsNavigation
InputMode m_InputMode
int m_iFocusX [NUM_PLAYERS]
bool m_bWasOnExit [NUM_PLAYERS]
bool m_bGotAtLeastOneStartPressed [NUM_PLAYERS]
True if at least one player pressed Start after selecting the song.
ActorFrame m_frameContainer
AutoActor m_sprPage
OptionsCursor m_Cursor [NUM_PLAYERS]
AutoActor m_sprLineHighlight [NUM_PLAYERS]
BitmapText m_textExplanation [NUM_PLAYERS]
BitmapText m_textExplanationTogether
DualScrollBar m_ScrollBar
AutoActor m_sprMore
RageSound m_SoundChangeCol
RageSound m_SoundNextRow
RageSound m_SoundPrevRow
RageSound m_SoundToggleOn
RageSound m_SoundToggleOff
RageSound m_SoundStart
ThemeMetric< int > NUM_ROWS_SHOWN
ThemeMetric< apActorCommands > ROW_INIT_COMMAND
ThemeMetric< apActorCommands > ROW_ON_COMMAND
ThemeMetric< apActorCommands > ROW_OFF_COMMAND
LuaExpressionTransform m_exprRowPositionTransformFunction
ThemeMetric< bool > SHOW_SCROLL_BAR
ThemeMetric< float > SCROLL_BAR_HEIGHT
ThemeMetric< float > SCROLL_BAR_TIME
ThemeMetric< float > LINE_HIGHLIGHT_X
ThemeMetric< bool > SHOW_EXIT_ROW
ThemeMetric< bool > SEPARATE_EXIT_ROW
ThemeMetric< float > SEPARATE_EXIT_ROW_Y
ThemeMetric< bool > SHOW_EXPLANATIONS
ThemeMetric< bool > ALLOW_REPEATING_CHANGE_VALUE_INPUT
ThemeMetric< float > CURSOR_TWEEN_SECONDS
ThemeMetric< bool > WRAP_VALUE_IN_ROW
ThemeMetric< RString > OPTION_ROW_NORMAL_METRICS_GROUP
ThemeMetric< RString > OPTION_ROW_EXIT_METRICS_GROUP
Protected Attributes inherited from ScreenWithMenuElements
AutoActor m_sprUnderlay
MenuTimer * m_MenuTimer
AutoActor m_sprOverlay
vector< Actor * > m_vDecorations
Transition m_In
Transition m_Out
Transition m_Cancel
ThemeMetric< bool > PLAY_MUSIC
ThemeMetric< bool > MUSIC_ALIGN_BEAT
ThemeMetric< float > DELAY_MUSIC_SECONDS
ThemeMetric< bool > CANCEL_TRANSITIONS_OUT
ThemeMetric< float > TIMER_SECONDS
ThemeMetric< RString > TIMER_METRICS_GROUP
ThemeMetric< bool > RESET_GAMESTATE
Protected Attributes inherited from Screen
vector< QueuedScreenMessage > m_QueuedMessages
The list of messages that are sent to a Screen.
InputQueueCodeSet m_Codes
ThemeMetric< bool > ALLOW_OPERATOR_MENU_BUTTON
Do we allow the operator menu button to be pressed here?
ThemeMetric< bool > HANDLE_BACK_BUTTON
Do we handle the back button being pressed here?
ThemeMetric< float > REPEAT_RATE
ThemeMetric< float > REPEAT_DELAY
RString m_sNextScreen
The next screen to go to once this screen is done.
RString m_sPrevScreen
ScreenMessage m_smSendOnPop
float m_fLockInputSecs
bool m_bRunning
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Friends
class LunaScreenOptions
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Screen
static void InitScreen (Screen *pScreen)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from ScreenWithMenuElements
bool m_bShouldAllowLateJoin
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Member Functions inherited from Screen
static bool SortMessagesByDelayRemaining (const QueuedScreenMessage &m1, const QueuedScreenMessage &m2)
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A grid of options; the selected option is drawn with a highlight rectangle.
Member Enumeration Documentation
Navigation
enum ScreenOptions::Navigation protected
Enumerator
NAV_THREE_KEY
NAV_THREE_KEY_MENU
NAV_THREE_KEY_ALT
NAV_FIVE_KEY
NAV_TOGGLE_THREE_KEY
NAV_TOGGLE_FIVE_KEY
Constructor & Destructor Documentation
ScreenOptions()
ScreenOptions::ScreenOptions ()
References INPUTMODE_SHARE_CURSOR, PrefsManager::m_iArcadeOptionsNavigation, m_InputMode, NAV_FIVE_KEY, NAV_THREE_KEY, NAV_THREE_KEY_ALT, PREFSMAN, and SetNavigation().
~ScreenOptions()
ScreenOptions::~ScreenOptions () override
References LOG, m_pRows, SAFE_DELETE, and RageLog::Trace().
Member Function Documentation
AfterChangeRow()
void ScreenOptions::AfterChangeRow (PlayerNumber pn) protected virtual
Perform an action after moving to a new row.
Override this to detect when the row has changed.
Reimplemented in ScreenOptionsManageProfiles.
References AfterChangeValueOrRow(), OptionRow::GetFirstItemGoesDown(), OptionRow::GetRowDef(), OptionRow::GetTextItemsSize(), GetWidthXY(), LAYOUT_SHOW_ONE_IN_ROW, m_iCurrentRow, m_iFocusX, OptionRowDefinition::m_layoutType, m_OptionsNavigation, m_pRows, NAV_TOGGLE_FIVE_KEY, and OptionRow::SetChoiceInRowWithFocus().
Referenced by ScreenOptionsManageProfiles::AfterChangeRow(), MoveRowAbsolute(), and RestartOptions().
AfterChangeValueInRow()
void ScreenOptions::AfterChangeValueInRow (int iRow, PlayerNumber pn) protected virtual
Perform an action after a row has changed its value.
Override this to detect when the value in a row has changed.
Reimplemented in ScreenOptionsEditProfile, and ScreenOptionsCourseOverview.
References AfterChangeValueOrRow().
Referenced by ScreenOptionsCourseOverview::AfterChangeValueInRow(), ScreenOptionsEditProfile::AfterChangeValueInRow(), and ChangeValueInRowRelative().
AfterChangeValueOrRow()
void ScreenOptions::AfterChangeValueOrRow (PlayerNumber pn) protected virtual
Reimplemented in ScreenMiniMenu.
References COMMAND, BitmapText::FinishTweening(), FOREACH_HumanPlayer, FOREACH_PlayerNumber, GAMESTATE, GetExplanationText(), GameState::GetNumHumanPlayers(), OptionRow::GetRowType(), BitmapText::GetText(), INPUTMODE_INDIVIDUAL, GameState::IsHumanPlayer(), m_bWasOnExit, m_iCurrentRow, m_InputMode, m_pRows, m_ScrollBar, m_sprMore, m_textExplanation, m_textExplanationTogether, ON_COMMAND, Actor::PlayCommand(), PositionRows(), RefreshIcons(), OptionRow::RowType_Exit, DualScrollBar::SetPercentage(), BitmapText::SetText(), SHOW_SCROLL_BAR, ssprintf(), text, and TweenCursor().
Referenced by AfterChangeRow(), AfterChangeValueInRow(), ScreenMiniMenu::AfterChangeValueOrRow(), and ProcessMenuStart().
AllAreOnLastRow()
bool ScreenOptions::AllAreOnLastRow () const protected
References FOREACH_HumanPlayer, m_iCurrentRow, and m_pRows.
Referenced by LunaScreenOptions::AllAreOnLastRow(), and ProcessMenuStart().
BeginFadingOut()
void ScreenOptions::BeginFadingOut () protected
References Screen::PostScreenMessage(), and SM_BeginFadingOut.
Referenced by ScreenOptionsManageProfiles::HandleScreenMessage(), HandleScreenMessage(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), and ProcessMenuStart().
BeginScreen()
void ScreenOptions::BeginScreen () override virtual
This is called immediately before the screen is used.
Reimplemented from Screen.
Reimplemented in ScreenOptionsExportPackageSubPage, ScreenOptionsToggleSongsSubPage, ScreenOptionsExportPackage, ScreenOptionsToggleSongs, ScreenOptionsEditProfile, ScreenOptionsCourseOverview, ScreenPlayerOptions, and ScreenOptionsManageProfiles.
References ScreenWithMenuElements::BeginScreen(), FOREACH_PlayerNumber, GAMESTATE, GameState::IsHumanPlayer(), m_bGotAtLeastOneStartPressed, m_Cursor, m_frameContainer, ON_COMMAND, RestartOptions(), Actor::SetVisible(), and ActorFrame::SortByDrawOrder().
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ScreenPlayerOptions::BeginScreen(), ScreenOptionsCourseOverview::BeginScreen(), ScreenOptionsEditProfile::BeginScreen(), ScreenOptionsToggleSongs::BeginScreen(), ScreenOptionsExportPackage::BeginScreen(), ScreenOptionsToggleSongsSubPage::BeginScreen(), ScreenOptionsExportPackageSubPage::BeginScreen(), and ScreenMiniMenu::BeginScreen().
ChangeValueInRowAbsolute()
void ScreenOptions::ChangeValueInRowAbsolute (int iRow, PlayerNumber pn, int iChoiceIndex, bool bRepeat) protected
References ASSERT, MessageManager::Broadcast(), ChangeValueInRowRelative(), OptionRow::GetChoiceInRowWithFocus(), OptionRow::GetRowDef(), m_pRows, OptionRowDefinition::m_vsChoices, MESSAGEMAN, and Message::SetParam().
ChangeValueInRowRelative()
void ScreenOptions::ChangeValueInRowRelative (int iRow, PlayerNumber pn, int iDelta, bool bRepeat) protected
References AfterChangeValueInRow(), ALLOW_REPEATING_CHANGE_VALUE_INPUT, CLAMP(), ExportOptions(), FOREACH_HumanPlayer, FOREACH_PlayerNumber, OptionRow::GetChoiceInRowWithFocus(), OptionRow::GetRowDef(), ThemeMetric< T >::GetValue(), INPUTMODE_SHARE_CURSOR, OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, m_InputMode, m_OptionsNavigation, m_pRows, OptionRowDefinition::m_selectType, m_SoundChangeCol, m_SoundNextRow, m_SoundPrevRow, OptionRowDefinition::m_vsChoices, MoveRowRelative(), NAV_THREE_KEY_MENU, NAV_TOGGLE_FIVE_KEY, NAV_TOGGLE_THREE_KEY, RageSound::Play(), SELECT_MULTIPLE, OptionRow::SetChoiceInRowWithFocus(), OptionRow::SetOneSelection(), StoreFocus(), wrap(), and WRAP_VALUE_IN_ROW.
Referenced by ChangeValueInRowAbsolute(), MenuLeft(), MenuRight(), and ProcessMenuStart().
ExportOptions()
virtual void ScreenOptions::ExportOptions (int iRow, const vector< PlayerNumber > & vpns) protected pure virtual
Implemented in ScreenMiniMenu, ScreenOptionsExportPackageSubPage, ScreenOptionsToggleSongsSubPage, ScreenOptionsExportPackage, ScreenOptionsMaster, ScreenOptionsToggleSongs, ScreenOptionsEditProfile, ScreenNetworkOptions, ScreenOptionsManageProfiles, ScreenOptionsCourseOverview, ScreenSMOnlineLogin, and ScreenSongOptions.
Referenced by ChangeValueInRowRelative(), HandleScreenMessage(), and ProcessMenuStart().
FocusedItemEndsScreen()
bool ScreenOptions::FocusedItemEndsScreen (PlayerNumber pn) const protected virtual
Reimplemented in ScreenMiniMenu.
References GetNextScreenForFocusedItem().
Referenced by LunaScreenOptions::FocusedItemEndsScreen(), and ProcessMenuStart().
GetCurrentRow()
int ScreenOptions::GetCurrentRow (PlayerNumber pn = PLAYER_1) const inline protected
References m_iCurrentRow.
Referenced by ScreenMiniMenu::ExportOptions(), LunaScreenOptions::GetCurrentRowIndex(), GetNextScreenForFocusedItem(), ScreenSMOnlineLogin::GetSelectedProfileID(), ScreenNetworkOptions::MenuStart(), MoveRowAbsolute(), ScreenOptionsToggleSongs::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), and ScreenOptionsEditProfile::ProcessMenuStart().
GetExplanationText()
RString ScreenOptions::GetExplanationText (int iRow) const protected
References ASSERT, OptionRow::GetRowDef(), ThemeMetric< T >::GetValue(), OptionRowDefinition::m_bAllowExplanation, m_pRows, OptionRowDefinition::m_sExplanationName, OptionRowDefinition::m_sName, OPTION_EXPLANATION(), and SHOW_EXPLANATIONS.
Referenced by AfterChangeValueOrRow(), and InitMenu().
GetNextScreenForFocusedItem()
RString ScreenOptions::GetNextScreenForFocusedItem (PlayerNumber pn) const protected
References ASSERT, GetCurrentRow(), OptionRowHandler::GetScreen(), and m_pRows.
Referenced by FocusedItemEndsScreen(), and HandleScreenMessage().
GetNumRows()
int ScreenOptions::GetNumRows () const inline protected
References m_pRows.
Referenced by LunaScreenOptions::GetOptionRow().
GetRow()
OptionRow* ScreenOptions::GetRow (int iRow) const inline protected
References m_pRows.
Referenced by LunaScreenOptions::GetOptionRow().
GetWidthXY()
void ScreenOptions::GetWidthXY (PlayerNumber pn, int iRow, int iChoiceOnRow, int & iWidthOut, int & iXOut, int & iYOut) const protected
References ASSERT_M, OptionRow::GetWidthXY(), m_pRows, and ssprintf().
Referenced by AfterChangeRow(), PositionCursor(), ScreenOptionsManageProfiles::ProcessMenuStart(), StoreFocus(), and TweenCursor().
HandleScreenMessage()
void ScreenOptions::HandleScreenMessage (ScreenMessage SM) override virtual
Reimplemented from Screen.
Reimplemented in ScreenOptionsEditProfile, ScreenOptionsCourseOverview, ScreenOptionsMaster, ScreenPlayerOptions, ScreenOptionsManageProfiles, and ScreenSMOnlineLogin.
References BeginFadingOut(), ExportOptions(), FOREACH_HumanPlayer, GAMESTATE, GameState::GetMasterPlayerNumber(), GetNextScreenForFocusedItem(), Screen::GetNextScreenName(), ScreenWithMenuElements::HandleScreenMessage(), ScreenWithMenuElements::IsTransitioning(), m_pRows, Actor::m_sName, Screen::m_sNextScreen, LuaHelpers::ReportScriptErrorFmt(), OptionRow::RowType_Exit, SM_BeginFadingOut, SM_GoToNextScreen, SM_MenuTimer, and ScreenWithMenuElements::StartTransitioningScreen().
Referenced by ScreenSMOnlineLogin::HandleScreenMessage(), ScreenNetworkOptions::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenOptionsMaster::HandleScreenMessage(), ScreenOptionsCourseOverview::HandleScreenMessage(), ScreenOptionsEditProfile::HandleScreenMessage(), and ScreenMiniMenu::HandleScreenMessage().
ImportOptions()
virtual void ScreenOptions::ImportOptions (int iRow, const vector< PlayerNumber > & vpns) protected pure virtual
Implemented in ScreenMiniMenu, ScreenOptionsExportPackageSubPage, ScreenOptionsToggleSongsSubPage, ScreenOptionsExportPackage, ScreenOptionsMaster, ScreenOptionsToggleSongs, ScreenOptionsEditProfile, ScreenNetworkOptions, ScreenOptionsManageProfiles, ScreenOptionsCourseOverview, and ScreenSMOnlineLogin.
Referenced by RestartOptions().
Init()
void ScreenOptions::Init () override virtual
This is called immediately after construction, to allow initializing after all derived classes exist.
Don't call it directly; use InitScreen instead.
Reimplemented from Screen.
Reimplemented in ScreenOptionsExportPackageSubPage, ScreenOptionsExportPackage, ScreenOptionsEditProfile, ScreenOptionsMaster, ScreenOptionsCourseOverview, ScreenPlayerOptions, ScreenOptionsManageProfiles, ScreenSMOnlineLogin, and ScreenSongOptions.
References ActorFrame::AddChild(), ALLOW_REPEATING_CHANGE_VALUE_INPUT, CURSOR_TWEEN_SECONDS, DualScrollBar::EnablePlayer(), FAIL_M, FOREACH_PlayerNumber, GAMESTATE, ThemeManager::GetMetricR(), ThemeManager::GetPathF(), ThemeManager::GetPathG(), ThemeManager::GetPathS(), ScreenWithMenuElements::Init(), INPUTMODE_INDIVIDUAL, INPUTMODE_SHARE_CURSOR, GameState::IsHumanPlayer(), LINE_HIGHLIGHT_X, DualScrollBar::Load(), OptionsCursor::Load(), OptionRowType::Load(), AutoActor::Load(), ThemeMetric< T >::Load(), RageSound::Load(), LOAD_ALL_COMMANDS, LOAD_ALL_COMMANDS_AND_SET_XY, BitmapText::LoadFromFont(), m_Cursor, m_exprRowPositionTransformFunction, m_frameContainer, m_InputMode, m_OptionRowTypeExit, m_OptionRowTypeNormal, m_ScrollBar, Actor::m_sName, m_SoundChangeCol, m_SoundNextRow, m_SoundPrevRow, m_SoundStart, m_SoundToggleOff, m_SoundToggleOn, m_sprLineHighlight, m_sprMore, m_sprPage, m_textExplanation, m_textExplanationTogether, NUM_ROWS_SHOWN, OPTION_ROW_EXIT_METRICS_GROUP, OPTION_ROW_NORMAL_METRICS_GROUP, Actor::PlayCommand(), PlayerNumberToString(), ROW_INIT_COMMAND, ROW_OFF_COMMAND, ROW_ON_COMMAND, SCROLL_BAR_HEIGHT, SCROLL_BAR_TIME, SEPARATE_EXIT_ROW, SEPARATE_EXIT_ROW_Y, DualScrollBar::SetBarHeight(), DualScrollBar::SetBarTime(), Actor::SetDrawOrder(), LuaExpressionTransform::SetFromReference(), Actor::SetName(), Actor::SetX(), SHOW_EXIT_ROW, SHOW_EXPLANATIONS, SHOW_SCROLL_BAR, ssprintf(), THEME, and WRAP_VALUE_IN_ROW.
Referenced by AutoScreenMessage(), ScreenNetworkOptions::Init(), ScreenSMOnlineLogin::Init(), ScreenOptionsManageProfiles::Init(), ScreenOptionsMaster::Init(), ScreenOptionsEditProfile::Init(), ScreenOptionsExportPackage::Init(), ScreenOptionsExportPackageSubPage::Init(), and ScreenMiniMenu::Init().
InitMenu()
void ScreenOptions::InitMenu (const vector< OptionRowHandler *> & vHands)
References ActorFrame::AddChild(), FOREACH, LuaManager::Get(), GetExplanationText(), L, OptionRow::LoadExit(), OptionRow::LoadNormal(), LOG, LUA, m_frameContainer, m_OptionRowTypeExit, m_OptionRowTypeNormal, m_OptionsNavigation, m_pRows, NAV_TOGGLE_THREE_KEY, LuaHelpers::Push(), LuaManager::Release(), ActorFrame::RemoveChild(), ROW_INIT_COMMAND, SAFE_DELETE, Actor::SetDrawOrder(), SHOW_EXIT_ROW, ActorFrame::SortByDrawOrder(), and RageLog::Trace().
Referenced by ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsCourseOverview::BeginScreen(), ScreenOptionsEditProfile::BeginScreen(), ScreenOptionsToggleSongs::BeginScreen(), ScreenOptionsExportPackage::BeginScreen(), ScreenOptionsToggleSongsSubPage::BeginScreen(), ScreenOptionsExportPackageSubPage::BeginScreen(), ScreenSMOnlineLogin::Init(), ScreenNetworkOptions::Init(), ScreenOptionsMaster::Init(), and ScreenMiniMenu::LoadMenu().
Input()
bool ScreenOptions::Input (const InputEventPlus & input) override virtual
Reimplemented from Screen.
Reimplemented in ScreenPlayerOptions.
References DEVICE_MOUSE, InputEventPlus::DeviceI, GAME_BUTTON_LEFT, GAME_BUTTON_MENULEFT, GAME_BUTTON_MENURIGHT, GAME_BUTTON_RIGHT, GAME_BUTTON_SELECT, GAME_BUTTON_START, GAMESTATE, IET_RELEASE, Screen::Input(), INPUTMAPPER, GameState::IsHumanPlayer(), Transition::IsTransitioning(), ScreenWithMenuElements::m_Cancel, Screen::m_fLockInputSecs, ScreenWithMenuElements::m_Out, InputEventPlus::MenuI, MOUSE_LEFT, MOUSE_WHEELDOWN, InputEventPlus::pn, InputMapper::ResetKeyRepeat(), and InputEventPlus::type.
Referenced by ScreenPlayerOptions::Input().
MenuBack()
bool ScreenOptions::MenuBack (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References ScreenWithMenuElements::Cancel(), and SM_GoToPrevScreen.
MenuDown()
bool ScreenOptions::MenuDown (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References MessageManager::Broadcast(), MenuUpDown(), Message_MenuDownP1, MESSAGEMAN, and InputEventPlus::pn.
Referenced by ProcessMenuStart().
MenuLeft()
bool ScreenOptions::MenuLeft (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References MessageManager::Broadcast(), ChangeValueInRowRelative(), IET_FIRST_PRESS, m_iCurrentRow, m_OptionsNavigation, MenuUpDown(), Message_MenuLeftP1, MESSAGEMAN, NAV_THREE_KEY_ALT, InputEventPlus::pn, and InputEventPlus::type.
MenuRight()
bool ScreenOptions::MenuRight (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References MessageManager::Broadcast(), ChangeValueInRowRelative(), IET_FIRST_PRESS, m_iCurrentRow, m_OptionsNavigation, MenuUpDown(), Message_MenuRightP1, MESSAGEMAN, NAV_THREE_KEY_ALT, InputEventPlus::pn, and InputEventPlus::type.
MenuSelect()
bool ScreenOptions::MenuSelect (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References MenuUpDown().
MenuStart()
bool ScreenOptions::MenuStart (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
Reimplemented in ScreenSMOnlineLogin.
References GAME_BUTTON_LEFT, GAME_BUTTON_RIGHT, IET_FIRST_PRESS, IET_RELEASE, INPUTMAPPER, InputMapper::IsBeingPressed(), m_bGotAtLeastOneStartPressed, m_OptionsNavigation, m_SoundPrevRow, MoveRowRelative(), NAV_THREE_KEY, NAV_TOGGLE_THREE_KEY, RageSound::Play(), InputEventPlus::pn, ProcessMenuStart(), and InputEventPlus::type.
Referenced by ScreenSMOnlineLogin::MenuStart(), and ScreenNetworkOptions::MenuStart().
MenuUp()
bool ScreenOptions::MenuUp (const InputEventPlus & input) override protected virtual
Reimplemented from Screen.
References MessageManager::Broadcast(), MenuUpDown(), Message_MenuUpP1, MESSAGEMAN, and InputEventPlus::pn.
MenuUpDown()
void ScreenOptions::MenuUpDown (const InputEventPlus & input, int iDir) protected virtual
References ASSERT, GAME_BUTTON_MENUDOWN, GAME_BUTTON_MENUUP, GAME_BUTTON_SELECT, GAME_BUTTON_START, IET_FIRST_PRESS, IET_REPEAT, INPUTMAPPER, InputMapper::IsBeingPressed(), m_SoundNextRow, m_SoundPrevRow, MoveRowRelative(), RageSound::Play(), InputEventPlus::pn, and InputEventPlus::type.
Referenced by MenuDown(), MenuLeft(), MenuRight(), MenuSelect(), and MenuUp().
MoveRowAbsolute()
bool ScreenOptions::MoveRowAbsolute (PlayerNumber pn, int iRow) protected
References AfterChangeRow(), MessageManager::Broadcast(), FOREACH_PlayerNumber, GetCurrentRow(), OptionRow::GetRowType(), INPUTMODE_INDIVIDUAL, m_iCurrentRow, m_InputMode, m_pRows, MESSAGEMAN, OptionRow::RowType_Exit, and Message::SetParam().
Referenced by ScreenOptionsManageProfiles::BeginScreen(), MoveRowRelative(), and ProcessMenuStart().
MoveRowRelative()
bool ScreenOptions::MoveRowRelative (PlayerNumber pn, int iDir, bool bRepeat) protected
References ASSERT, m_iCurrentRow, m_pRows, MoveRowAbsolute(), and wrap().
Referenced by ChangeValueInRowRelative(), MenuStart(), and MenuUpDown().
PositionCursor()
void ScreenOptions::PositionCursor (PlayerNumber pn) protected
References ASSERT_M, OptionRow::GetChoiceInRowWithFocus(), OptionRow::GetRowDef(), GetWidthXY(), m_Cursor, m_iCurrentRow, m_pRows, OptionRowDefinition::m_vsChoices, OptionsCursor::SetBarWidth(), OptionsCursor::SetCanGo(), Actor::SetXY(), and ssprintf().
Referenced by RestartOptions().
PositionRows()
void ScreenOptions::PositionRows (bool bTween) protected
References RageColor::a, Actor::TweenState::diffuse, FAIL_M, GAMESTATE, LuaExpressionTransform::GetTransformCached(), Actor::TweenState::Init(), INPUTMODE_SHARE_CURSOR, GameState::IsHumanPlayer(), m_exprRowPositionTransformFunction, m_iCurrentRow, m_InputMode, m_pRows, max(), min(), NUM_DIFFUSE_COLORS, NUM_ROWS_SHOWN, PLAYER_1, PLAYER_2, Actor::TweenState::pos, OptionRow::RowType_Exit, SEPARATE_EXIT_ROW, SEPARATE_EXIT_ROW_Y, OptionRow::SetDestination(), and RageVector3::y.
Referenced by AfterChangeValueOrRow(), and RestartOptions().
ProcessMenuStart()
void ScreenOptions::ProcessMenuStart (const InputEventPlus & input) protected virtual
Reimplemented in ScreenOptionsExportPackageSubPage, ScreenOptionsEditProfile, ScreenOptionsExportPackage, ScreenOptionsCourseOverview, ScreenOptionsManageProfiles, and ScreenOptionsToggleSongs.
References AfterChangeValueOrRow(), AllAreOnLastRow(), BeginFadingOut(), MessageManager::Broadcast(), ChangeValueInRowRelative(), ExportOptions(), FAIL_M, FocusedItemEndsScreen(), OptionRow::GetChoiceInRowWithFocus(), OptionRow::GetFirstItemGoesDown(), OptionRow::GetRowDef(), OptionRow::GetRowType(), OptionRow::GetSelected(), OptionRow::GoToFirstOnStart(), IET_FIRST_PRESS, ScreenWithMenuElements::IsTransitioning(), OptionRowDefinition::m_bOneChoiceForAllPlayers, m_iCurrentRow, m_OptionsNavigation, m_pRows, OptionRowDefinition::m_selectType, m_SoundNextRow, m_SoundStart, m_SoundToggleOff, m_SoundToggleOn, MenuDown(), MESSAGEMAN, MoveRowAbsolute(), NAV_FIVE_KEY, NAV_THREE_KEY, NAV_THREE_KEY_ALT, NAV_THREE_KEY_MENU, NAV_TOGGLE_FIVE_KEY, NAV_TOGGLE_THREE_KEY, RageSound::Play(), RageSound::PlayCopy(), InputEventPlus::pn, RefreshIcons(), OptionRow::RowType_Exit, SELECT_MULTIPLE, OptionRow::SetOneSelection(), OptionRow::SetOneSharedSelection(), Message::SetParam(), OptionRow::SetSelected(), SHOW_EXIT_ROW, and InputEventPlus::type.
Referenced by MenuStart(), ScreenOptionsToggleSongs::ProcessMenuStart(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), ScreenOptionsEditProfile::ProcessMenuStart(), and ScreenOptionsExportPackageSubPage::ProcessMenuStart().
PushSelf()
void ScreenOptions::PushSelf (lua_State * L) override virtual
Reimplemented from Screen.
Reimplemented in ScreenPlayerOptions.
RefreshIcons()
void ScreenOptions::RefreshIcons (int iRow, PlayerNumber pn) protected
References OptionRow::GetHandler(), OptionRowHandler::GetIconTextAndGameCommand(), OptionRow::GetOneSelection(), OptionRow::GetRowDef(), OptionRowDefinition::m_bOneChoiceForAllPlayers, m_OptionsNavigation, m_pRows, and NAV_TOGGLE_THREE_KEY.
Referenced by AfterChangeValueOrRow(), ProcessMenuStart(), and RestartOptions().
RestartOptions()
void ScreenOptions::RestartOptions () protected
References AfterChangeRow(), OptionRow::AfterImportOptions(), CHECKPOINT_M, LuaExpressionTransform::ClearCache(), FOREACH_HumanPlayer, FOREACH_PlayerNumber, GAMESTATE, OptionRow::GetRowDef(), ImportOptions(), OptionRowDefinition::IsEnabledForPlayer(), GameState::IsHumanPlayer(), m_bWasOnExit, m_exprRowPositionTransformFunction, m_iCurrentRow, m_iFocusX, m_pRows, m_sprLineHighlight, PositionCursor(), PositionRows(), RefreshIcons(), OptionRow::Reload(), and Actor::SetVisible().
Referenced by BeginScreen().
SetInputMode()
void ScreenOptions::SetInputMode (InputMode im) inline protected
References m_InputMode.
Referenced by ScreenOptionsManageProfiles::Init(), ScreenOptionsMaster::Init(), ScreenOptionsExportPackage::Init(), and ScreenOptionsExportPackageSubPage::Init().
SetNavigation()
void ScreenOptions::SetNavigation (Navigation nav) inline protected
References m_OptionsNavigation.
Referenced by AutoScreenMessage(), ScreenOptionsManageProfiles::Init(), ScreenOptionsMaster::Init(), ScreenOptionsExportPackage::Init(), ScreenOptionsExportPackageSubPage::Init(), ScreenMiniMenu::Init(), and ScreenOptions().
StoreFocus()
void ScreenOptions::StoreFocus (PlayerNumber pn) protected
References OptionRow::GetChoiceInRowWithFocus(), OptionRow::GetRowDef(), GetWidthXY(), LAYOUT_SHOW_ONE_IN_ROW, LOG, m_iCurrentRow, m_iFocusX, OptionRowDefinition::m_layoutType, m_pRows, and RageLog::Trace().
Referenced by ChangeValueInRowRelative().
TweenCursor()
void ScreenOptions::TweenCursor (PlayerNumber pn) protected
References ASSERT_M, OptionsCursor::BeginTweening(), COMMAND, CURSOR_TWEEN_SECONDS, GAMESTATE, OptionsCursor::GetBarWidth(), OptionRow::GetChoiceInRowWithFocus(), Actor::GetDestX(), Actor::GetDestY(), OptionRow::GetRowDef(), OptionRow::GetRowType(), GetWidthXY(), GameState::IsHumanPlayer(), LAYOUT_SHOW_ALL_IN_ROW, LAYOUT_SHOW_ONE_IN_ROW, m_Cursor, m_iCurrentRow, OptionRowDefinition::m_layoutType, m_pRows, m_sprLineHighlight, OptionRowDefinition::m_vsChoices, OptionRow::RowType_Exit, OptionsCursor::SetBarWidth(), OptionsCursor::SetCanGo(), Actor::SetXY(), Actor::SetY(), ssprintf(), and OptionsCursor::StopTweening().
Referenced by AfterChangeValueOrRow().
TweenOffScreen()
void ScreenOptions::TweenOffScreen () override virtual
Reimplemented from ScreenWithMenuElements.
References FOREACH, m_pRows, ROW_OFF_COMMAND, and ScreenWithMenuElements::TweenOffScreen().
TweenOnScreen()
void ScreenOptions::TweenOnScreen () override virtual
Reimplemented from ScreenWithMenuElements.
References FOREACH, m_frameContainer, m_pRows, ROW_ON_COMMAND, ActorFrame::SortByDrawOrder(), and ScreenWithMenuElements::TweenOnScreen().
Update()
void ScreenOptions::Update (float fDeltaTime) override virtual
Reimplemented from Screen.
References ScreenWithMenuElements::Update().
Friends And Related Function Documentation
LunaScreenOptions
friend class LunaScreenOptions friend
Member Data Documentation
ALLOW_REPEATING_CHANGE_VALUE_INPUT
ThemeMetric<bool> ScreenOptions::ALLOW_REPEATING_CHANGE_VALUE_INPUT protected
Referenced by ChangeValueInRowRelative(), and Init().
CURSOR_TWEEN_SECONDS
ThemeMetric<float> ScreenOptions::CURSOR_TWEEN_SECONDS protected
Referenced by Init(), and TweenCursor().
LINE_HIGHLIGHT_X
ThemeMetric<float> ScreenOptions::LINE_HIGHLIGHT_X protected
Referenced by Init().
m_bGotAtLeastOneStartPressed
bool ScreenOptions::m_bGotAtLeastOneStartPressed[NUM_PLAYERS] protected
True if at least one player pressed Start after selecting the song.
TRICKY: People hold Start to get to PlayerOptions, then the repeat events cause them to zip to the bottom. So, ignore Start repeat events until we've seen one first pressed event.
Referenced by BeginScreen(), and MenuStart().
m_bWasOnExit
bool ScreenOptions::m_bWasOnExit[NUM_PLAYERS] protected
Referenced by AfterChangeValueOrRow(), and RestartOptions().
m_Cursor
OptionsCursor ScreenOptions::m_Cursor[NUM_PLAYERS] protected
Referenced by BeginScreen(), Init(), PositionCursor(), and TweenCursor().
m_exprRowPositionTransformFunction
LuaExpressionTransform ScreenOptions::m_exprRowPositionTransformFunction protected
Referenced by Init(), PositionRows(), and RestartOptions().
m_frameContainer
ActorFrame ScreenOptions::m_frameContainer protected
Referenced by BeginScreen(), ScreenPlayerOptions::Init(), Init(), InitMenu(), and TweenOnScreen().
m_iCurrentRow
int ScreenOptions::m_iCurrentRow[NUM_PLAYERS] protected
The current row each player is on.
Referenced by AfterChangeRow(), AfterChangeValueOrRow(), AllAreOnLastRow(), ScreenOptionsMaster::ExportOptions(), GetCurrentRow(), ScreenOptionsManageProfiles::GetLocalProfileIndexWithFocus(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenOptionsCourseOverview::HandleScreenMessage(), ScreenPlayerOptions::Input(), MenuLeft(), MenuRight(), MoveRowAbsolute(), MoveRowRelative(), PositionCursor(), PositionRows(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptionsExportPackageSubPage::ProcessMenuStart(), ProcessMenuStart(), RestartOptions(), StoreFocus(), and TweenCursor().
m_iFocusX
int ScreenOptions::m_iFocusX[NUM_PLAYERS] protected
Referenced by AfterChangeRow(), RestartOptions(), and StoreFocus().
m_InputMode
InputMode ScreenOptions::m_InputMode protected
Referenced by AfterChangeValueOrRow(), ChangeValueInRowRelative(), Init(), MoveRowAbsolute(), PositionRows(), ScreenOptions(), and SetInputMode().
m_OptionRowTypeExit
OptionRowType ScreenOptions::m_OptionRowTypeExit protected
Referenced by Init(), and InitMenu().
m_OptionRowTypeNormal
OptionRowType ScreenOptions::m_OptionRowTypeNormal protected
Referenced by Init(), and InitMenu().
m_OptionsNavigation
Navigation ScreenOptions::m_OptionsNavigation protected
Referenced by AfterChangeRow(), ChangeValueInRowRelative(), InitMenu(), MenuLeft(), MenuRight(), MenuStart(), ProcessMenuStart(), RefreshIcons(), and SetNavigation().
m_pRows
vector<OptionRow*> ScreenOptions::m_pRows protected
Map menu lines to m_OptionRow entries.
Referenced by AfterChangeRow(), AfterChangeValueOrRow(), ScreenMiniMenu::AfterChangeValueOrRow(), AllAreOnLastRow(), ScreenPlayerOptions::BeginScreen(), ChangeValueInRowAbsolute(), ChangeValueInRowRelative(), ScreenOptionsCourseOverview::ExportOptions(), ScreenSMOnlineLogin::ExportOptions(), ScreenOptionsEditProfile::ExportOptions(), ScreenOptionsMaster::ExportOptions(), ScreenOptionsToggleSongsSubPage::ExportOptions(), ScreenMiniMenu::ExportOptions(), GetExplanationText(), ScreenOptionsManageProfiles::GetLocalProfileIndexWithFocus(), GetNextScreenForFocusedItem(), GetNumRows(), GetRow(), ScreenSMOnlineLogin::GetSelectedProfileID(), GetWidthXY(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenOptionsMaster::HandleScreenMessage(), HandleScreenMessage(), ScreenSMOnlineLogin::ImportOptions(), ScreenOptionsEditProfile::ImportOptions(), ScreenOptionsMaster::ImportOptions(), ScreenOptionsToggleSongsSubPage::ImportOptions(), ScreenMiniMenu::ImportOptions(), ScreenNetworkOptions::Init(), ScreenSMOnlineLogin::Init(), ScreenPlayerOptions::Init(), InitMenu(), ScreenPlayerOptions::Input(), ScreenNetworkOptions::MenuStart(), MoveRowAbsolute(), MoveRowRelative(), PositionCursor(), PositionRows(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptionsToggleSongs::ProcessMenuStart(), ScreenOptionsExportPackage::ProcessMenuStart(), ScreenOptionsExportPackageSubPage::ProcessMenuStart(), ProcessMenuStart(), RefreshIcons(), RestartOptions(), StoreFocus(), TweenCursor(), TweenOffScreen(), TweenOnScreen(), and ~ScreenOptions().
m_ScrollBar
DualScrollBar ScreenOptions::m_ScrollBar protected
Referenced by AfterChangeValueOrRow(), and Init().
m_SoundChangeCol
RageSound ScreenOptions::m_SoundChangeCol protected
Referenced by ChangeValueInRowRelative(), and Init().
m_SoundNextRow
RageSound ScreenOptions::m_SoundNextRow protected
Referenced by ChangeValueInRowRelative(), Init(), MenuUpDown(), and ProcessMenuStart().
m_SoundPrevRow
RageSound ScreenOptions::m_SoundPrevRow protected
Referenced by ChangeValueInRowRelative(), Init(), MenuStart(), and MenuUpDown().
m_SoundStart
RageSound ScreenOptions::m_SoundStart protected
Referenced by Init(), and ProcessMenuStart().
m_SoundToggleOff
RageSound ScreenOptions::m_SoundToggleOff protected
Referenced by Init(), and ProcessMenuStart().
m_SoundToggleOn
RageSound ScreenOptions::m_SoundToggleOn protected
Referenced by Init(), and ProcessMenuStart().
m_sprLineHighlight
AutoActor ScreenOptions::m_sprLineHighlight[NUM_PLAYERS] protected
Referenced by Init(), RestartOptions(), and TweenCursor().
m_sprMore
AutoActor ScreenOptions::m_sprMore protected
Referenced by AfterChangeValueOrRow(), and Init().
m_sprPage
AutoActor ScreenOptions::m_sprPage protected
Referenced by Init().
m_textExplanation
BitmapText ScreenOptions::m_textExplanation[NUM_PLAYERS] protected
Referenced by AfterChangeValueOrRow(), and Init().
m_textExplanationTogether
BitmapText ScreenOptions::m_textExplanationTogether protected
Referenced by AfterChangeValueOrRow(), and Init().
NUM_ROWS_SHOWN
ThemeMetric<int> ScreenOptions::NUM_ROWS_SHOWN protected
Referenced by Init(), and PositionRows().
OPTION_ROW_EXIT_METRICS_GROUP
ThemeMetric<RString> ScreenOptions::OPTION_ROW_EXIT_METRICS_GROUP protected
Referenced by Init().
OPTION_ROW_NORMAL_METRICS_GROUP
ThemeMetric<RString> ScreenOptions::OPTION_ROW_NORMAL_METRICS_GROUP protected
Referenced by Init().
ROW_INIT_COMMAND
ThemeMetric<apActorCommands> ScreenOptions::ROW_INIT_COMMAND protected
Referenced by Init(), and InitMenu().
ROW_OFF_COMMAND
ThemeMetric<apActorCommands> ScreenOptions::ROW_OFF_COMMAND protected
Referenced by Init(), and TweenOffScreen().
ROW_ON_COMMAND
ThemeMetric<apActorCommands> ScreenOptions::ROW_ON_COMMAND protected
Referenced by Init(), and TweenOnScreen().
SCROLL_BAR_HEIGHT
ThemeMetric<float> ScreenOptions::SCROLL_BAR_HEIGHT protected
Referenced by Init().
SCROLL_BAR_TIME
ThemeMetric<float> ScreenOptions::SCROLL_BAR_TIME protected
Referenced by Init().
SEPARATE_EXIT_ROW
ThemeMetric<bool> ScreenOptions::SEPARATE_EXIT_ROW protected
Referenced by Init(), and PositionRows().
SEPARATE_EXIT_ROW_Y
ThemeMetric<float> ScreenOptions::SEPARATE_EXIT_ROW_Y protected
Referenced by Init(), and PositionRows().
SHOW_EXIT_ROW
ThemeMetric<bool> ScreenOptions::SHOW_EXIT_ROW protected
Referenced by Init(), InitMenu(), and ProcessMenuStart().
SHOW_EXPLANATIONS
ThemeMetric<bool> ScreenOptions::SHOW_EXPLANATIONS protected
Referenced by GetExplanationText(), and Init().
SHOW_SCROLL_BAR
ThemeMetric<bool> ScreenOptions::SHOW_SCROLL_BAR protected
Referenced by AfterChangeValueOrRow(), and Init().
WRAP_VALUE_IN_ROW
ThemeMetric<bool> ScreenOptions::WRAP_VALUE_IN_ROW protected
Referenced by ChangeValueInRowRelative(), and Init().
The documentation for this class was generated from the following files:
ScreenOptions.h
ScreenOptions.cpp