Etterna: RageSemaphore Class Reference
RageSemaphore Class Reference
#include <RageThreads.h>
Public Member Functions
RageSemaphore (const RString &sName, int iInitialValue=0)
~RageSemaphore ()
RString GetName () const
int GetValue () const
void Post ()
void Wait (bool bFailOnTimeout=true)
bool TryWait ()
Private Member Functions
RageSemaphore & operator= (const RageSemaphore &rhs)=delete
RageSemaphore (const RageSemaphore &rhs)=delete
Private Attributes
SemaImpl * m_pSema
RString m_sName
Constructor & Destructor Documentation
RageSemaphore() [1/2]
RageSemaphore::RageSemaphore (const RString & sName, int iInitialValue = 0)
~RageSemaphore()
RageSemaphore::~RageSemaphore ()
References m_pSema.
RageSemaphore() [2/2]
RageSemaphore::RageSemaphore (const RageSemaphore & rhs) private delete
Member Function Documentation
GetName()
RString RageSemaphore::GetName () const inline
References m_sName.
Referenced by Wait().
GetValue()
int RageSemaphore::GetValue () const
References m_pSema.
operator=()
RageSemaphore& RageSemaphore::operator= (const RageSemaphore & rhs) private delete
Post()
void RageSemaphore::Post ()
References m_pSema.
Referenced by BackgroundLoader::CacheFile(), MovieTexture_DShow::CheckFrame(), RageSoundDriver_PulseAudio::CtxStateCb(), RageSoundDriver_PulseAudio::m_InitStream(), MovieTexture_DShow::NewData(), RageSoundDriver_AU::Render(), MovieTexture_DShow::StopSkippingUpdates(), RageSoundDriver_PulseAudio::StreamStateCb(), and BackgroundLoader::~BackgroundLoader().
TryWait()
bool RageSemaphore::TryWait ()
References m_pSema.
Referenced by MovieTexture_DShow::NewData(), and MovieTexture_DShow::SkipUpdates().
Wait()
void RageSemaphore::Wait (bool bFailOnTimeout = true)
References RageThread::GetIsShowingDialog(), GetName(), ThreadSlot::GetThreadName(), GetThreadSlotFromID(), m_pSema, ssprintf(), and RageException::Throw().
Referenced by MovieTexture_DShow::Create(), RageSoundDriver_PulseAudio::Init(), InputHandler_MacOSX_HID::InputHandler_MacOSX_HID(), BackgroundLoader::LoadThread(), MovieTexture_DShow::NewData(), and RageSoundDriver_AU::~RageSoundDriver_AU().
Member Data Documentation
m_pSema
SemaImpl* RageSemaphore::m_pSema private
Referenced by GetValue(), Post(), TryWait(), Wait(), and ~RageSemaphore().
m_sName
RString RageSemaphore::m_sName private
Referenced by GetName().
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp