Etterna: ThreadedFileWorker Class Reference
ThreadedFileWorker Class Reference
Public Member Functions
ThreadedFileWorker (RString sPath)
~ThreadedFileWorker () override
RageFileBasic * Open (const RString &sPath, int iMode, int &iErr)
void Close (RageFileBasic *pFile)
int GetFileSize (RageFileBasic *&pFile)
int GetFD (RageFileBasic *&pFile)
int Seek (RageFileBasic *&pFile, int iPos, RString &sError)
int Read (RageFileBasic *&pFile, void *pBuf, int iSize, RString &sError)
int Write (RageFileBasic *&pFile, const void *pBuf, int iSize, RString &sError)
int Flush (RageFileBasic *&pFile, RString &sError)
RageFileBasic * Copy (RageFileBasic *&pFile, RString &sError)
bool FlushDirCache (const RString &sPath)
int Move (const RString &sOldPath, const RString &sNewPath)
int Remove (const RString &sPath)
bool PopulateFileSet (FileSet &fs, const RString &sPath)
Public Member Functions inherited from RageWorkerThread
RageWorkerThread (const RString &sName)
virtual ~RageWorkerThread ()
void SetTimeout (float fSeconds)
bool TimeoutEnabled () const
bool IsTimedOut () const
bool WaitForOneHeartbeat ()
Protected Member Functions
void HandleRequest (int iRequest) override
void RequestTimedOut () override
Protected Member Functions inherited from RageWorkerThread
void StartThread ()
void StopThread ()
bool DoRequest (int iRequest)
void SetHeartbeat (float fSeconds)
virtual void DoHeartbeat ()
Private Attributes
RageFileDriver * m_pChildDriver
vector< RageFileBasic * > m_apDeletedFiles
RageMutex m_DeletedFilesLock
RString m_sRequestPath
RString m_sRequestPath2
RageFileBasic * m_pResultFile
FileSet m_ResultFileSet
int m_iRequestMode
RageFileBasic * m_pRequestFile
int m_iResultRequest
int m_iRequestSize
RString m_sResultError
int m_iRequestPos
char * m_pResultBuffer
char * m_pRequestBuffer
Constructor & Destructor Documentation
ThreadedFileWorker()
ThreadedFileWorker::ThreadedFileWorker (RString sPath) explicit
References FILEMAN, g_apWorkers, g_apWorkersMutex, RageFileManager::GetFileDriver(), RageMutex::Lock(), m_pChildDriver, m_pRequestBuffer, m_pRequestFile, m_pResultBuffer, m_pResultFile, ssprintf(), RageWorkerThread::StartThread(), RageMutex::Unlock(), and WARN.
~ThreadedFileWorker()
ThreadedFileWorker::~ThreadedFileWorker () override
References FILEMAN, g_apWorkers, g_apWorkersMutex, RageMutex::Lock(), m_pChildDriver, RageFileManager::ReleaseFileDriver(), RageWorkerThread::StopThread(), and RageMutex::Unlock().
Member Function Documentation
Close()
void ThreadedFileWorker::Close (RageFileBasic * pFile)
References ASSERT, RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), RageMutex::Lock(), m_apDeletedFiles, m_DeletedFilesLock, m_pChildDriver, m_pRequestFile, REQ_CLOSE, and RageMutex::Unlock().
Referenced by Copy(), Flush(), GetFD(), GetFileSize(), Read(), Seek(), Write(), and RageFileObjTimeout::~RageFileObjTimeout().
Copy()
RageFileBasic * ThreadedFileWorker::Copy (RageFileBasic *& pFile, RString & sError)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_pChildDriver, m_pRequestFile, m_pResultFile, and REQ_COPY.
Referenced by RageFileObjTimeout::Copy().
Flush()
int ThreadedFileWorker::Flush (RageFileBasic *& pFile, RString & sError)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iResultRequest, m_pChildDriver, m_pRequestFile, m_sResultError, and REQ_FLUSH.
Referenced by RageFileObjTimeout::FlushInternal().
FlushDirCache()
bool ThreadedFileWorker::FlushDirCache (const RString & sPath)
References RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), LOG, m_pChildDriver, m_sRequestPath, REQ_FLUSH_DIR_CACHE, RageWorkerThread::SetTimeout(), RageWorkerThread::TimeoutEnabled(), and RageLog::Trace().
Referenced by RageFileDriverTimeout::FlushDirCache().
GetFD()
int ThreadedFileWorker::GetFD (RageFileBasic *& pFile)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iResultRequest, m_pChildDriver, m_pRequestFile, and REQ_GET_FD.
Referenced by RageFileObjTimeout::GetFD().
GetFileSize()
int ThreadedFileWorker::GetFileSize (RageFileBasic *& pFile)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iResultRequest, m_pChildDriver, m_pRequestFile, and REQ_GET_FILE_SIZE.
Referenced by RageFileDriverTimeout::Open().
HandleRequest()
void ThreadedFileWorker::HandleRequest (int iRequest) override protected virtual
Implements RageWorkerThread.
References ASSERT, RageFileBasic::Copy(), FAIL_M, RageFileDriver::FDB, RageFileBasic::Flush(), RageFileDriver::FlushDirCache(), RageFileBasic::GetError(), FilenameDB::GetFileSetCopy(), RageFileBasic::GetFileSize(), RageMutex::Lock(), m_apDeletedFiles, m_DeletedFilesLock, m_iRequestMode, m_iRequestPos, m_iRequestSize, m_iResultRequest, m_pChildDriver, m_pRequestBuffer, m_pRequestFile, m_pResultBuffer, m_pResultFile, m_ResultFileSet, m_sRequestPath, m_sRequestPath2, m_sResultError, RageFileDriver::Move(), RageFileDriver::Open(), RageFileBasic::Read(), RageFileDriver::Remove(), REQ_CLOSE, REQ_COPY, REQ_FLUSH, REQ_FLUSH_DIR_CACHE, REQ_GET_FILE_SIZE, REQ_MOVE, REQ_OPEN, REQ_POPULATE_FILE_SET, REQ_READ, REQ_REMOVE, REQ_SEEK, REQ_WRITE, RageFileBasic::Seek(), ssprintf(), RageMutex::Unlock(), and RageFileBasic::Write().
Move()
int ThreadedFileWorker::Move (const RString & sOldPath, const RString & sNewPath)
References ASSERT, RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iResultRequest, m_pChildDriver, m_sRequestPath, m_sRequestPath2, and REQ_MOVE.
Referenced by RageFileDriverTimeout::Move().
Open()
RageFileBasic * ThreadedFileWorker::Open (const RString & sPath, int iMode, int & iErr)
References RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), LOG, m_iRequestMode, m_iResultRequest, m_pChildDriver, m_pResultFile, m_sRequestPath, REQ_OPEN, and RageLog::Trace().
Referenced by RageFileDriverTimeout::Open().
PopulateFileSet()
bool ThreadedFileWorker::PopulateFileSet (FileSet & fs, const RString & sPath)
References RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), LOG, m_pChildDriver, m_ResultFileSet, m_sRequestPath, REQ_POPULATE_FILE_SET, and RageLog::Trace().
Referenced by TimedFilenameDB::PopulateFileSet().
Read()
int ThreadedFileWorker::Read (RageFileBasic *& pFile, void * pBuf, int iSize, RString & sError)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iRequestSize, m_iResultRequest, m_pChildDriver, m_pRequestFile, m_pResultBuffer, m_sResultError, and REQ_READ.
Referenced by RageFileObjTimeout::ReadInternal().
Remove()
int ThreadedFileWorker::Remove (const RString & sPath)
References ASSERT, RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iResultRequest, m_pChildDriver, m_sRequestPath, and REQ_REMOVE.
Referenced by RageFileDriverTimeout::Remove().
RequestTimedOut()
void ThreadedFileWorker::RequestTimedOut () override protected virtual
Reimplemented from RageWorkerThread.
References m_pRequestBuffer, m_pRequestFile, m_pResultBuffer, m_pResultFile, SAFE_DELETE, and SAFE_DELETE_ARRAY.
Seek()
int ThreadedFileWorker::Seek (RageFileBasic *& pFile, int iPos, RString & sError)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iRequestPos, m_iResultRequest, m_pChildDriver, m_pRequestFile, m_sResultError, and REQ_SEEK.
Referenced by RageFileObjTimeout::SeekInternal().
Write()
int ThreadedFileWorker::Write (RageFileBasic *& pFile, const void * pBuf, int iSize, RString & sError)
References ASSERT, Close(), RageWorkerThread::DoRequest(), RageWorkerThread::IsTimedOut(), m_iRequestSize, m_iResultRequest, m_pChildDriver, m_pRequestBuffer, m_pRequestFile, m_sResultError, and REQ_WRITE.
Referenced by RageFileObjTimeout::WriteInternal().
Member Data Documentation
m_apDeletedFiles
vector<RageFileBasic*> ThreadedFileWorker::m_apDeletedFiles private
Referenced by Close(), and HandleRequest().
m_DeletedFilesLock
RageMutex ThreadedFileWorker::m_DeletedFilesLock private
Referenced by Close(), and HandleRequest().
m_iRequestMode
int ThreadedFileWorker::m_iRequestMode private
Referenced by HandleRequest(), and Open().
m_iRequestPos
int ThreadedFileWorker::m_iRequestPos private
Referenced by HandleRequest(), and Seek().
m_iRequestSize
int ThreadedFileWorker::m_iRequestSize private
Referenced by HandleRequest(), Read(), and Write().
m_iResultRequest
int ThreadedFileWorker::m_iResultRequest private
Referenced by Flush(), GetFD(), GetFileSize(), HandleRequest(), Move(), Open(), Read(), Remove(), Seek(), and Write().
m_pChildDriver
RageFileDriver* ThreadedFileWorker::m_pChildDriver private
Referenced by Close(), Copy(), Flush(), FlushDirCache(), GetFD(), GetFileSize(), HandleRequest(), Move(), Open(), PopulateFileSet(), Read(), Remove(), Seek(), ThreadedFileWorker(), Write(), and ~ThreadedFileWorker().
m_pRequestBuffer
char* ThreadedFileWorker::m_pRequestBuffer private
Referenced by HandleRequest(), RequestTimedOut(), ThreadedFileWorker(), and Write().
m_pRequestFile
RageFileBasic* ThreadedFileWorker::m_pRequestFile private
Referenced by Close(), Copy(), Flush(), GetFD(), GetFileSize(), HandleRequest(), Read(), RequestTimedOut(), Seek(), ThreadedFileWorker(), and Write().
m_pResultBuffer
char* ThreadedFileWorker::m_pResultBuffer private
Referenced by HandleRequest(), Read(), RequestTimedOut(), and ThreadedFileWorker().
m_pResultFile
RageFileBasic* ThreadedFileWorker::m_pResultFile private
Referenced by Copy(), HandleRequest(), Open(), RequestTimedOut(), and ThreadedFileWorker().
m_ResultFileSet
FileSet ThreadedFileWorker::m_ResultFileSet private
Referenced by HandleRequest(), and PopulateFileSet().
m_sRequestPath
RString ThreadedFileWorker::m_sRequestPath private
Referenced by FlushDirCache(), HandleRequest(), Move(), Open(), PopulateFileSet(), and Remove().
m_sRequestPath2
RString ThreadedFileWorker::m_sRequestPath2 private
Referenced by HandleRequest(), and Move().
m_sResultError
RString ThreadedFileWorker::m_sResultError private
Referenced by Flush(), HandleRequest(), Read(), Seek(), and Write().
The documentation for this class was generated from the following file:
RageFileDriverTimeout.cpp