Etterna: EzSockets Class Reference
EzSockets Class Reference
#include <ezsockets.h>
Public Types
enum SockState {
skDISCONNECTED = 0, skUNDEF1, skLISTENING, skUNDEF3,
skUNDEF4, skUNDEF5, skUNDEF6, skCONNECTED,
skERROR
}
Public Member Functions
EzSockets ()
~EzSockets ()
bool create ()
bool create (int Protocol)
bool create (int Protocol, int Type)
bool bind (unsigned short port)
bool listen ()
bool accept (EzSockets &socket)
bool setAddr (const std::string &host, unsigned short port)
bool connect (const string &host, unsigned short port)
void close ()
bool check ()
long uAddr ()
bool CanRead ()
bool CanRead (unsigned int msTimeout)
bool DataAvailable ()
bool DataAvailable (unsigned int msTimeout)
bool IsError ()
bool CanWrite ()
bool CanWrite (unsigned int msTimeout)
void update ()
void SendData (const string &outData)
void SendData (const char *data, unsigned int bytes)
int ReadData (char *data, unsigned int bytes)
int PeekData (char *data, unsigned int bytes)
void SendPack (const char *data, unsigned int bytes)
int ReadPack (char *data, unsigned int max)
int PeekPack (char *data, unsigned int max)
void SendStr (const string &data, char delim='\0')
int ReadStr (string &data, char delim='\0')
int PeekStr (string &data, char delim='\0')
char operator[] (int i)
int pUpdateWrite ()
int pUpdateRead ()
int pReadData (char *data)
int pWriteData (const char *data, int dataSize)
Static Public Member Functions
static bool CanConnect (const std::string &host, unsigned short port)
static unsigned long LongFromAddrIn (const sockaddr_in &s)
Public Attributes
bool blocking
struct sockaddr_in fromAddr
unsigned long fromAddr_len
string inBuffer
string outBuffer
SockState state
int lastCode
RString address
Private Attributes
int MAXCON
int sock
struct sockaddr_in addr
fd_set * scks
timeval * times
timeval timeout
Friends
istream & operator>> (istream &is, EzSockets &obj)
ostream & operator<< (ostream &os, const EzSockets &obj)
Member Enumeration Documentation
SockState
enum EzSockets::SockState
Enumerator
skDISCONNECTED
skUNDEF1
skLISTENING
skUNDEF3
skUNDEF4
skUNDEF5
skUNDEF6
skCONNECTED
skERROR
Constructor & Destructor Documentation
EzSockets()
EzSockets::EzSockets ()
References addr, blocking, INVALID_SOCKET, MAXCON, scks, skDISCONNECTED, sock, state, timeout, timeoutMiliseconds, times, and timevalFromMs().
~EzSockets()
EzSockets::~EzSockets ()
References close(), scks, and times.
Member Function Documentation
accept()
bool EzSockets::accept (EzSockets & socket)
References addr, address, blocking, CanRead(), lastCode, skCONNECTED, sock, SOCKET_ERROR, and state.
bind()
bool EzSockets::bind (unsigned short port)
References addr, check(), lastCode, and sock.
Referenced by SMOProtocol::SMOProtocol().
CanConnect()
bool EzSockets::CanConnect (const std::string & host, unsigned short port) static
References addr, CanWrite(), close(), connect(), create(), IsError(), setAddr(), SetSocketBlocking(), sock, and timeout.
Referenced by SMOProtocol::Connect(), and ETTProtocol::Connect().
CanRead() [1/2]
bool EzSockets::CanRead ()
References checkCanRead(), sock, and times.
Referenced by accept(), PeekData(), PeekPack(), and update().
CanRead() [2/2]
bool EzSockets::CanRead (unsigned int msTimeout)
References checkCanRead(), sock, and timevalFromMs().
CanWrite() [1/2]
bool EzSockets::CanWrite ()
References checkCanWrite(), sock, and times.
Referenced by CanConnect(), and update().
CanWrite() [2/2]
bool EzSockets::CanWrite (unsigned int msTimeout)
References checkCanWrite(), sock, and timevalFromMs().
check()
bool EzSockets::check ()
References sock, and SOCKET_NONE.
Referenced by bind(), and connect().
close()
void EzSockets::close ()
References inBuffer, outBuffer, skDISCONNECTED, sock, and state.
Referenced by FileTransfer::Cancel(), ScreenPackages::CancelDownload(), CanConnect(), SMOProtocol::close(), ScreenPackages::EnterURL(), NetworkSyncManager::GetCurrentSMBuild(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), SMOProtocol::ProcessInput(), FileTransfer::StartTransfer(), ~EzSockets(), and SMOProtocol::~SMOProtocol().
connect()
bool EzSockets::connect (const string & host, unsigned short port)
References addr, check(), setAddr(), SetSocketBlocking(), skCONNECTED, sock, state, and timeout.
Referenced by CanConnect(), ScreenPackages::EnterURL(), NetworkSyncManager::GetCurrentSMBuild(), FileTransfer::StartTransfer(), and SMOProtocol::TryConnect().
create() [1/3]
bool EzSockets::create ()
Referenced by CanConnect(), create(), ScreenPackages::EnterURL(), NetworkSyncManager::GetCurrentSMBuild(), SMOProtocol::SMOProtocol(), FileTransfer::StartTransfer(), and SMOProtocol::TryConnect().
create() [2/3]
bool EzSockets::create (int Protocol)
References create().
create() [3/3]
bool EzSockets::create (int Protocol, int Type)
References lastCode, skDISCONNECTED, sock, SOCKET_NONE, state, timeoutMiliseconds, and timevalFromMs().
DataAvailable() [1/2]
bool EzSockets::DataAvailable () inline
DataAvailable() [2/2]
bool EzSockets::DataAvailable (unsigned int msTimeout) inline
IsError()
bool EzSockets::IsError ()
References scks, skERROR, sock, state, and times.
Referenced by CanConnect(), PeekData(), PeekPack(), PeekStr(), SMOProtocol::ProcessInput(), SendData(), and update().
listen()
bool EzSockets::listen ()
References lastCode, MAXCON, skLISTENING, sock, SOCKET_ERROR, and state.
LongFromAddrIn()
unsigned long EzSockets::LongFromAddrIn (const sockaddr_in & s) static
Referenced by SMOProtocol::Update().
operator[]()
char EzSockets::operator[] (int i)
PeekData()
int EzSockets::PeekData (char * data, unsigned int bytes)
References blocking, CanRead(), inBuffer, IsError(), and pUpdateRead().
Referenced by PeekPack(), and ReadData().
PeekPack()
int EzSockets::PeekPack (char * data, unsigned int max)
References blocking, CanRead(), inBuffer, IsError(), max(), PeekData(), and pUpdateRead().
Referenced by ReadPack().
PeekStr()
int EzSockets::PeekStr (string & data, char delim = '\0')
References blocking, inBuffer, IsError(), and pUpdateRead().
Referenced by ReadStr().
pReadData()
int EzSockets::pReadData (char * data)
References fromAddr, fromAddr_len, skCONNECTED, skLISTENING, sock, and state.
Referenced by NetworkSyncManager::GetCurrentSMBuild(), and pUpdateRead().
pUpdateRead()
int EzSockets::pUpdateRead ()
References inBuffer, pReadData(), skERROR, and state.
Referenced by PeekData(), PeekPack(), PeekStr(), and update().
pUpdateWrite()
int EzSockets::pUpdateWrite ()
References outBuffer, pWriteData(), skERROR, and state.
Referenced by SendData(), and update().
pWriteData()
int EzSockets::pWriteData (const char * data, int dataSize)
References sock.
Referenced by pUpdateWrite().
ReadData()
int EzSockets::ReadData (char * data, unsigned int bytes)
References inBuffer, and PeekData().
Referenced by FileTransfer::HTTPUpdate(), and ScreenPackages::HTTPUpdate().
ReadPack()
int EzSockets::ReadPack (char * data, unsigned int max)
References inBuffer, and PeekPack().
Referenced by SMOProtocol::Connect(), SMOProtocol::ProcessInput(), SMOProtocol::StartRequest(), and SMOProtocol::Update().
ReadStr()
int EzSockets::ReadStr (string & data, char delim = '\0')
References inBuffer, and PeekStr().
Referenced by operator<<().
SendData() [1/2]
void EzSockets::SendData (const string & outData)
References blocking, IsError(), outBuffer, pUpdateWrite(), and update().
Referenced by ScreenPackages::EnterURL(), NetworkSyncManager::GetCurrentSMBuild(), SendPack(), SendStr(), and FileTransfer::StartTransfer().
SendData() [2/2]
void EzSockets::SendData (const char * data, unsigned int bytes)
References blocking, IsError(), outBuffer, pUpdateWrite(), and update().
SendPack()
void EzSockets::SendPack (const char * data, unsigned int bytes)
References outBuffer, and SendData().
Referenced by SMOProtocol::Connect(), SMOProtocol::ProcessInput(), SMOProtocol::ReportNSSOnOff(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), SMOProtocol::SendSMOnline(), and SMOProtocol::StartRequest().
SendStr()
void EzSockets::SendStr (const string & data, char delim = '\0')
References SendData().
Referenced by operator>>().
setAddr()
bool EzSockets::setAddr (const std::string & host, unsigned short port)
References addr.
Referenced by CanConnect(), and connect().
uAddr()
long EzSockets::uAddr ()
References addr.
update()
void EzSockets::update ()
References CanRead(), CanWrite(), IsError(), outBuffer, pUpdateRead(), and pUpdateWrite().
Referenced by SMOProtocol::ProcessInput(), and SendData().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const EzSockets & obj) friend
operator>>
istream& operator>> (istream & is, EzSockets & obj) friend
Member Data Documentation
addr
struct sockaddr_in EzSockets::addr private
Referenced by accept(), bind(), CanConnect(), connect(), EzSockets(), setAddr(), and uAddr().
address
RString EzSockets::address
Referenced by accept().
blocking
bool EzSockets::blocking
Referenced by accept(), SMOProtocol::Connect(), ScreenPackages::EnterURL(), EzSockets(), NetworkSyncManager::GetCurrentSMBuild(), PeekData(), PeekPack(), PeekStr(), SendData(), SMOProtocol::SMOProtocol(), SMOProtocol::StartRequest(), and FileTransfer::StartTransfer().
fromAddr
struct sockaddr_in EzSockets::fromAddr
Referenced by pReadData(), and SMOProtocol::Update().
fromAddr_len
unsigned long EzSockets::fromAddr_len
Referenced by pReadData().
inBuffer
string EzSockets::inBuffer
Referenced by close(), PeekData(), PeekPack(), PeekStr(), pUpdateRead(), ReadData(), ReadPack(), and ReadStr().
lastCode
int EzSockets::lastCode
Referenced by accept(), bind(), create(), and listen().
MAXCON
int EzSockets::MAXCON private
Referenced by EzSockets(), and listen().
outBuffer
string EzSockets::outBuffer
Referenced by close(), pUpdateWrite(), SendData(), SendPack(), and update().
scks
fd_set* EzSockets::scks private
Referenced by EzSockets(), IsError(), and ~EzSockets().
sock
int EzSockets::sock private
Referenced by accept(), bind(), CanConnect(), CanRead(), CanWrite(), check(), close(), connect(), create(), EzSockets(), IsError(), listen(), pReadData(), and pWriteData().
state
SockState EzSockets::state
Referenced by accept(), close(), connect(), create(), EzSockets(), FileTransfer::HTTPUpdate(), ScreenPackages::HTTPUpdate(), IsError(), listen(), pReadData(), SMOProtocol::ProcessInput(), pUpdateRead(), and pUpdateWrite().
timeout
timeval EzSockets::timeout private
Referenced by CanConnect(), connect(), and EzSockets().
times
timeval* EzSockets::times private
Referenced by CanRead(), CanWrite(), EzSockets(), IsError(), and ~EzSockets().
The documentation for this class was generated from the following files:
ezsockets.h
ezsockets.cpp