Etterna: CommonMetrics.cpp File Reference
CommonMetrics.cpp File Reference
#include "global.h"
#include "CommonMetrics.h"
#include "Foreach.h"
#include "GameManager.h"
#include "GameState.h"
#include "LuaManager.h"
#include "RageUtil.h"
Functions
static void RemoveStepsTypes (vector< StepsType > &inout, RString sStepsTypesToRemove)
LuaFunction (LocalizeOptionItem, CommonMetrics::LocalizeOptionItem(SArg(1), true))
Function Documentation
LuaFunction()
LuaFunction (LocalizeOptionItem , CommonMetrics::LocalizeOptionItem(SArg(1), true))
RemoveStepsTypes()
static void RemoveStepsTypes (vector< StepsType > & inout, RString sStepsTypesToRemove) static
References FOREACH_CONST, GAMEMAN, LuaHelpers::ReportScriptErrorFmt(), split(), StepsType_Invalid, and GameManager::StringToStepsType().
Referenced by ThemeMetricStepsTypesToShow::Read().