Etterna: DebugLineAllowMultitexture Class Reference
DebugLineAllowMultitexture Class Reference
Private Member Functions
RString GetDisplayTitle () override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual RString GetDisplayValue ()
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineAllowMultitexture::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), PrefsManager::m_bAllowMultitexture, PREFSMAN, and Preference< T >::Set().
GetDisplayTitle()
RString DebugLineAllowMultitexture::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and MULTITEXTURE.
IsEnabled()
bool DebugLineAllowMultitexture::IsEnabled () inline override private virtual
Implements IDebugLine.
References Preference< T >::Get(), PrefsManager::m_bAllowMultitexture, and PREFSMAN.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp