Etterna: DWILoader Namespace Reference
DWILoader Namespace Reference
The DWILoader handles parsing the .dwi file.
Functions
void GetApplicableFiles (const RString &sPath, vector< RString > &out)
Retrieve the list of .dwi files.
bool LoadFromDir (const RString &sPath, Song &out, set< RString > &BlacklistedImages)
Attempt to load a song from a specified path.
bool LoadNoteDataFromSimfile (const RString &path, Steps &out)
Detailed Description
The DWILoader handles parsing the .dwi file.
Function Documentation
GetApplicableFiles()
void DWILoader::GetApplicableFiles (const RString & sPath, vector< RString > & out)
Retrieve the list of .dwi files.
Parameters
sPath a const reference to the path on the hard drive to check.
out a vector of files found in the path.
References GetDirListing().
Referenced by NotesLoader::LoadFromDir().
LoadFromDir()
bool DWILoader::LoadFromDir (const RString & sPath, Song & out, set< RString > & BlacklistedImages)
Attempt to load a song from a specified path.
Parameters
sPath a const reference to the path on the hard drive to check.
out a reference to the Song that will retrieve the song information.
BlacklistedImages a set of images that aren't used.
Returns
its success or failure.
References TimingData::AddSegment(), Song::AddSteps(), ASSERT, BeatToNoteRow(), ConvertString(), Song::CreateSteps(), DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, StdString::CStdStr< CT >::EqualsNoCase(), f, BMSLoader::GetApplicableFiles(), MsdFile::GetError(), NotesLoader::GetMainAndSubTitlesFromFullTitle(), MsdFile::GetNumParams(), MsdFile::GetNumValues(), MsdFile::GetValue(), LoadFromDWITokens(), LOG, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_sArtist, Song::m_sCDTitleFile, Song::m_sGenre, Song::m_sMainTitle, Song::m_sMusicFile, Song::m_SongTiming, Song::m_sSongFileName, Song::m_sSubTitle, Steps::m_StepsType, StdString::CStdStr< CT >::MakeLower(), NoteRowToBeat(), ParseBrokenDWITimestamp(), MsdFile::ReadFile(), Steps::SetFilename(), split(), StepsType_Invalid, StringToFloat(), StringToInt(), RageLog::Trace(), unlikely, and RageLog::UserLog().
Referenced by NotesLoader::LoadFromDir().
LoadNoteDataFromSimfile()
bool DWILoader::LoadNoteDataFromSimfile (const RString & path, Steps & out)
References DwiCompatibleStringToDifficulty(), StdString::CStdStr< CT >::EqualsNoCase(), Steps::GetDifficulty(), MsdFile::GetError(), Steps::GetMeter(), MsdFile::GetNumParams(), MsdFile::GetNumValues(), GetTypeFromMode(), MsdFile::GetValue(), LOG, Steps::m_StepsType, ParseNoteData(), MsdFile::ReadFile(), Steps::SetNoteData(), StringToInt(), and RageLog::UserLog().
Referenced by Steps::GetNoteDataFromSimfile().