Etterna: OptionRowHandler Class Reference
OptionRowHandler Class Reference
Shows PlayerOptions and SongOptions in icon form.
#include <OptionRowHandler.h>
Public Types
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Public Member Functions
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
virtual void Init ()
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual bool LoadInternal (const Commands &)
virtual ReloadChanged Reload ()
virtual int GetDefaultOption () const
virtual void ImportOption (OptionRow *, const vector< PlayerNumber > &, vector< bool > vbSelectedOut[NUM_PLAYERS]) const
virtual int ExportOption (const vector< PlayerNumber > &, const vector< bool > vbSelected[NUM_PLAYERS]) const
virtual void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const
virtual RString GetScreen (int) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Detailed Description
Shows PlayerOptions and SongOptions in icon form.
Member Enumeration Documentation
ReloadChanged
enum OptionRowHandler::ReloadChanged
Enumerator
RELOAD_CHANGED_NONE
RELOAD_CHANGED_ENABLED
RELOAD_CHANGED_ALL
Constructor & Destructor Documentation
OptionRowHandler()
OptionRowHandler::OptionRowHandler () inline
~OptionRowHandler()
virtual OptionRowHandler::~OptionRowHandler () virtual default
Member Function Documentation
ExportOption()
virtual int OptionRowHandler::ExportOption (const vector< PlayerNumber > & , const vector< bool > vbSelected[NUM_PLAYERS]) const inline virtual
Reimplemented in OptionRowHandlerGameCommand, OptionRowHandlerStepsType, OptionRowHandlerConfig, OptionRowHandlerLua, OptionRowHandlerSteps, and OptionRowHandlerList.
Referenced by OptionRow::ExportOptions().
GetDefaultOption()
virtual int OptionRowHandler::GetDefaultOption () const inline virtual
Reimplemented in OptionRowHandlerList.
Referenced by OptionListRow::SetUnderlines().
GetIconTextAndGameCommand()
void OptionRowHandler::GetIconTextAndGameCommand (int iFirstSelection, RString & sIconTextOut, GameCommand & gcOut) const virtual
Reimplemented in OptionRowHandlerGameCommand, and OptionRowHandlerList.
References GameCommand::Init().
Referenced by ScreenOptions::RefreshIcons(), and OptionsList::Start().
GetScreen()
virtual RString OptionRowHandler::GetScreen (int) const inline virtual
Reimplemented in OptionRowHandlerGameCommand, and OptionRowHandlerList.
Referenced by OptionsList::FindScreenInHandler(), ScreenOptions::GetNextScreenForFocusedItem(), OptionsList::Input(), OptionsList::Load(), OptionListRow::SetTextFromHandler(), OptionListRow::SetUnderlines(), OptionsList::Start(), and OptionsList::SwitchMenu().
GetThemedItemText()
RString OptionRowHandler::GetThemedItemText (int iChoice) const
References CommonMetrics::LocalizeOptionItem(), OptionRowDefinition::m_bAllowThemeItems, m_Def, and OptionRowDefinition::m_vsChoices.
Referenced by OptionRow::GetThemedItemText(), and OptionListRow::SetTextFromHandler().
GoToFirstOnStart()
virtual bool OptionRowHandler::GoToFirstOnStart () inline virtual
Reimplemented in OptionRowHandlerLua.
Referenced by OptionRow::GoToFirstOnStart().
ImportOption()
virtual void OptionRowHandler::ImportOption (OptionRow * , const vector< PlayerNumber > & , vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline virtual
Reimplemented in OptionRowHandlerGameCommand, OptionRowHandlerStepsType, OptionRowHandlerConfig, OptionRowHandlerLua, OptionRowHandlerSteps, and OptionRowHandlerList.
Referenced by OptionRow::ImportOptions(), and OptionsList::ImportRow().
Init()
virtual void OptionRowHandler::Init () inline virtual
Reimplemented in OptionRowHandlerGameCommand, OptionRowHandlerStepsType, OptionRowHandlerConfig, OptionRowHandlerLua, OptionRowHandlerSteps, and OptionRowHandlerList.
References OptionRowDefinition::Init(), and m_vsReloadRowMessages.
Referenced by OptionRowHandlerList::Init(), OptionRowHandlerSteps::Init(), OptionRowHandlerLua::Init(), OptionRowHandlerConfig::Init(), OptionRowHandlerStepsType::Init(), OptionRowHandlerGameCommand::Init(), Load(), and OptionRowHandlerNull::OptionRowHandlerNull().
Load()
bool OptionRowHandler::Load (const Commands & cmds) inline
References Init(), and LoadInternal().
LoadInternal()
virtual bool OptionRowHandler::LoadInternal (const Commands &) inline virtual
Reimplemented in OptionRowHandlerGameCommand, OptionRowHandlerStepsType, OptionRowHandlerConfig, OptionRowHandlerLua, OptionRowHandlerListSongsInCurrentSongGroup, OptionRowHandlerListDifficulties, OptionRowHandlerListGroups, OptionRowHandlerListStyles, OptionRowHandlerListCharacters, OptionRowHandlerSteps, OptionRowHandlerListSteps, OptionRowHandlerListNoteSkins, and OptionRowHandlerList.
Referenced by Load().
NotifyOfSelection()
virtual bool OptionRowHandler::NotifyOfSelection (PlayerNumber pn, int choice) inline virtual
Reimplemented in OptionRowHandlerLua.
Referenced by OptionRow::NotifyHandlerOfSelection().
OptionTitle()
RString OptionRowHandler::OptionTitle () const
References ThemeManager::GetString(), OptionRowDefinition::m_bAllowThemeTitle, m_Def, OptionRowDefinition::m_sName, and THEME.
Referenced by OptionRow::GetRowTitle().
Reload()
virtual ReloadChanged OptionRowHandler::Reload () inline virtual
Reimplemented in OptionRowHandlerLua, OptionRowHandlerListSteps, and OptionRowHandlerList.
References RELOAD_CHANGED_NONE.
Referenced by OptionRow::Reload(), and OptionRowHandlerList::Reload().
Member Data Documentation
m_Def
OptionRowDefinition OptionRowHandler::m_Def
Referenced by OptionRow::AfterImportOptions(), ScreenOptionsManageProfiles::BeginScreen(), ScreenOptionsExportPackage::BeginScreen(), ScreenOptionsExportPackageSubPage::BeginScreen(), OptionRow::ChoicesChanged(), OptionRow::ExportOptions(), OptionsList::FindScreenInHandler(), OptionRow::GetChoiceInRowWithFocus(), OptionRowHandlerList::GetDefaultOption(), OptionRowHandlerList::GetIconTextAndGameCommand(), LunaOptionRow::GetNumChoices(), OptionRow::GetRowDef(), OptionRow::GetRowTitle(), OptionRow::GetSelected(), OptionRow::GetTextItemForRow(), GetThemedItemText(), OptionRowHandlerList::ImportOption(), OptionRow::ImportOptions(), OptionsList::ImportRow(), ScreenNetworkOptions::Init(), ScreenSMOnlineLogin::Init(), OptionRow::InitText(), OptionsList::Input(), OptionsList::Load(), OptionRow::LoadExit(), OptionRowHandlerList::LoadInternal(), OptionRowHandlerListNoteSkins::LoadInternal(), OptionRowHandlerListSteps::LoadInternal(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerListCharacters::LoadInternal(), OptionRowHandlerListStyles::LoadInternal(), OptionRowHandlerListGroups::LoadInternal(), OptionRowHandlerListDifficulties::LoadInternal(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), OptionRowHandlerLua::LoadInternal(), OptionRowHandlerConfig::LoadInternal(), OptionRowHandlerStepsType::LoadInternal(), OptionRowHandlerGameCommand::LoadInternal(), OptionRowHandlerUtil::Make(), OptionRowHandlerUtil::MakeSimple(), OptionRowHandlerLua::NotifyOfSelection(), LunaOptionRow::OneChoiceForAllPlayers(), OptionTitle(), OptionRow::PositionUnderlines(), OptionRowHandlerList::Reload(), OptionRowHandlerListSteps::Reload(), OptionRow::ResetFocusFromSelection(), OptionsList::SelectionsChanged(), OptionsList::SelectItem(), OptionRow::SetChoiceInRowWithFocus(), OptionsList::SetDefaultCurrentRow(), OptionRowHandlerLua::SetEnabledForPlayers(), OptionListRow::SetFromHandler(), OptionRow::SetOneSharedSelectionIfPresent(), OptionRow::SetSelected(), OptionListRow::SetTextFromHandler(), OptionListRow::SetUnderlines(), OptionsList::SwitchMenu(), OptionRow::UpdateEnabledDisabled(), and OptionRow::UpdateText().
m_vsReloadRowMessages
vector<RString> OptionRowHandler::m_vsReloadRowMessages
Referenced by OptionRow::Clear(), OptionRow::HandleMessage(), Init(), OptionRowHandlerList::LoadInternal(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerLua::LoadInternal(), OptionRowHandlerStepsType::LoadInternal(), and OptionRow::LoadNormal().
The documentation for this class was generated from the following files:
OptionRowHandler.h
OptionRowHandler.cpp