Etterna: StepsID Class Reference
StepsID Class Reference
#include <StepsUtil.h>
Public Member Functions
StepsID ()
Set up the StepsID with default values.
void Unset ()
void FromSteps (const Steps *p)
Steps * ToSteps (const Song *p, bool bAllowNull) const
bool operator< (const StepsID &rhs) const
bool operator== (const StepsID &rhs) const
bool MatchesStepsType (StepsType s) const
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
RString ToString () const
bool IsValid () const
StepsType GetStepsType () const
Difficulty GetDifficulty () const
RString GetKey () const
RString GetDescription () const
unsigned GetHash () const
Private Attributes
StepsType st { StepsType_Invalid }
Difficulty dc { Difficulty_Invalid }
RString ck
RString sDescription
unsigned uHash { 0 }
CachedObjectPointer< Steps > m_Cache
Constructor & Destructor Documentation
StepsID()
StepsID::StepsID () inline
Set up the StepsID with default values.
This used to call Unset(), which set the variables to the same thing.
Member Function Documentation
CreateNode()
XNode * StepsID::CreateNode () const
References XNode::AppendAttr(), ck, dc, Difficulty_Edit, DifficultyToString(), GAMEMAN, GameManager::GetStepsTypeInfo(), sDescription, st, StepsTypeInfo::szName, and uHash.
Referenced by ScreenGameplay::SaveReplay(), and XMLProfile::SaveSongScoresCreateNode().
FromSteps()
void StepsID::FromSteps (const Steps * p)
References ck, dc, Difficulty_Edit, Difficulty_Invalid, Steps::GetChartKey(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetHash(), m_Cache, Steps::m_StepsType, sDescription, st, StepsType_Invalid, uHash, and CachedObjectPointer< T >::Unset().
Referenced by Profile::GetStepsHighScoreList(), ScreenEvaluation::HandleMenuStart(), Song::ReloadFromSongDir(), ScreenGameplay::SaveReplay(), and Unset().
GetDescription()
RString StepsID::GetDescription () const inline
References dc, and Difficulty_Edit.
GetDifficulty()
Difficulty StepsID::GetDifficulty () const inline
References dc.
GetHash()
unsigned StepsID::GetHash () const inline
References uHash.
GetKey()
RString StepsID::GetKey () const inline
References ck.
GetStepsType()
StepsType StepsID::GetStepsType () const inline
References st.
Referenced by Profile::ImportScoresToEtterna().
IsValid()
bool StepsID::IsValid () const
References dc, Difficulty_Invalid, st, and StepsType_Invalid.
Referenced by Profile::ImportScoresToEtterna(), and XMLProfile::LoadSongScoresFromNode().
LoadFromNode()
void StepsID::LoadFromNode (const XNode * pNode)
References ASSERT, ck, dc, Difficulty_Edit, GAMEMAN, XNode::GetAttrValue(), XNode::GetName(), m_Cache, sDescription, st, StringToDifficulty(), GameManager::StringToStepsType(), uHash, and CachedObjectPointer< T >::Unset().
Referenced by XMLProfile::LoadSongScoresFromNode().
MatchesStepsType()
bool StepsID::MatchesStepsType (StepsType s) const inline
References st.
operator<()
bool StepsID::operator< (const StepsID & rhs) const
References COMP, dc, sDescription, st, and uHash.
operator==()
bool StepsID::operator== (const StepsID & rhs) const
References COMP, dc, sDescription, st, and uHash.
ToSteps()
Steps * StepsID::ToSteps (const Song * p, bool bAllowNull) const
References dc, Difficulty_Edit, Difficulty_Invalid, FAIL_M, SongID::FromSong(), SongUtil::GetOneSteps(), m_Cache, sDescription, CachedObjectPointer< T >::Set(), ssprintf(), st, StepsType_Invalid, and uHash.
Referenced by Profile::GetSongsActual(), and Profile::ImportScoresToEtterna().
ToString()
RString StepsID::ToString () const
References dc, Difficulty_Edit, DifficultyToString(), GAMEMAN, GameManager::GetStepsTypeInfo(), sDescription, ssprintf(), st, StepsTypeInfo::szName, and uHash.
Referenced by Profile::GetSongsActual(), and Profile::ImportScoresToEtterna().
Unset()
void StepsID::Unset () inline
References FromSteps().
Member Data Documentation
ck
RString StepsID::ck private
Referenced by CreateNode(), FromSteps(), GetKey(), and LoadFromNode().
dc
Difficulty StepsID::dc { Difficulty_Invalid } private
Referenced by CreateNode(), FromSteps(), GetDescription(), GetDifficulty(), IsValid(), LoadFromNode(), operator<(), operator==(), ToSteps(), and ToString().
m_Cache
CachedObjectPointer<Steps> StepsID::m_Cache mutable private
Referenced by FromSteps(), LoadFromNode(), and ToSteps().
sDescription
RString StepsID::sDescription private
Referenced by CreateNode(), FromSteps(), LoadFromNode(), operator<(), operator==(), ToSteps(), and ToString().
st
StepsType StepsID::st { StepsType_Invalid } private
Referenced by CreateNode(), FromSteps(), GetStepsType(), IsValid(), LoadFromNode(), MatchesStepsType(), operator<(), operator==(), ToSteps(), and ToString().
uHash
unsigned StepsID::uHash { 0 } private
Referenced by CreateNode(), FromSteps(), GetHash(), LoadFromNode(), operator<(), operator==(), ToSteps(), and ToString().
The documentation for this class was generated from the following files:
StepsUtil.h
StepsUtil.cpp