Etterna: ScreenTestInput.cpp File Reference
ScreenTestInput.cpp File Reference
#include "ScreenTestInput.h"
#include "InputEventPlus.h"
#include "InputMapper.h"
#include "LocalizedString.h"
#include "PrefsManager.h"
#include "RageInput.h"
#include "RageLog.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "ThemeManager.h"
#include "global.h"
Classes
class DeviceList
class InputList
Functions
REGISTER_ACTOR_CLASS (DeviceList)
REGISTER_ACTOR_CLASS (InputList)
REGISTER_SCREEN_CLASS (ScreenTestInput)
Variables
static LocalizedString CONTROLLER ("ScreenTestInput", "Controller")
static LocalizedString SECONDARY ("ScreenTestInput", "secondary")
static LocalizedString NOT_MAPPED ("ScreenTestInput", "not mapped")
Function Documentation
REGISTER_ACTOR_CLASS() [1/2]
REGISTER_ACTOR_CLASS (DeviceList)
REGISTER_ACTOR_CLASS() [2/2]
REGISTER_ACTOR_CLASS (InputList)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenTestInput)
Variable Documentation
CONTROLLER
LocalizedString CONTROLLER("ScreenTestInput", "Controller") static
Referenced by InputList::Update().
NOT_MAPPED
LocalizedString NOT_MAPPED("ScreenTestInput", "not mapped") static
Referenced by InputList::Update().
SECONDARY
LocalizedString SECONDARY("ScreenTestInput", "secondary") static
Referenced by InputList::Update().