Etterna: Checkpoints Namespace Reference
Checkpoints Namespace Reference
RageThreads defines (don't pull in all of RageThreads.h here)
Functions
void SetCheckpoint (const char *file, int line, const char *message)
void LogCheckpoints (bool yes=true)
void GetLogs (char *pBuf, int iSize, const char *delim)
Detailed Description
RageThreads defines (don't pull in all of RageThreads.h here)
Function Documentation
GetLogs()
void Checkpoints::GetLogs (char * pBuf, int iSize, const char * delim)
References GetCheckpointLog(), and MAX_THREADS.
LogCheckpoints()
void Checkpoints::LogCheckpoints (bool yes = true)
Referenced by ApplyLogPreferences().
SetCheckpoint()
void Checkpoints::SetCheckpoint (const char * file, int line, const char * message)
References CHECKPOINT_COUNT, GetCurThreadSlot(), GetUnknownThreadSlot(), LOG, ThreadSlot::m_Checkpoints, ThreadSlot::m_iCurCheckpoint, ThreadSlot::m_iNumCheckpoints, ThreadSlot::ThreadCheckpoint::m_szFormattedBuf, max(), ThreadSlot::ThreadCheckpoint::Set(), sm_crash(), and RageLog::Trace().