Etterna: LunaPrefsManager Class Reference
LunaPrefsManager Class Reference
Allow Lua to have access to the PrefsManager.
Public Member Functions
LunaPrefsManager ()
Public Member Functions inherited from Luna< PrefsManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetPreference (T *p, lua_State *L)
static int SetPreference (T *p, lua_State *L)
static int SetPreferenceToDefault (T *p, lua_State *L)
static int PreferenceExists (T *p, lua_State *L)
static int SavePreferences (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< PrefsManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< PrefsManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< PrefsManager >
using T = PrefsManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< PrefsManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the PrefsManager.
Constructor & Destructor Documentation
LunaPrefsManager()
LunaPrefsManager::LunaPrefsManager () inline
References ADD_METHOD.
Member Function Documentation
GetPreference()
static int LunaPrefsManager::GetPreference (T * p, lua_State * L) inline static
References IPreference::GetPreferenceByName(), IPreference::PushValue(), LuaHelpers::ReportScriptErrorFmt(), and SArg.
PreferenceExists()
static int LunaPrefsManager::PreferenceExists (T * p, lua_State * L) inline static
References IPreference::GetPreferenceByName(), and SArg.
SavePreferences()
static int LunaPrefsManager::SavePreferences (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and PrefsManager::SavePrefsToDisk().
SetPreference()
static int LunaPrefsManager::SetPreference (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IPreference::GetPreferenceByName(), LuaHelpers::ReportScriptErrorFmt(), SArg, and IPreference::SetFromStack().
SetPreferenceToDefault()
static int LunaPrefsManager::SetPreferenceToDefault (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IPreference::GetPreferenceByName(), IPreference::LoadDefault(), LOG, LuaHelpers::ReportScriptErrorFmt(), SArg, IPreference::ToString(), and RageLog::Trace().
The documentation for this class was generated from the following file:
PrefsManager.cpp