Etterna: InputHandler.cpp File Reference
InputHandler.cpp File Reference
#include "InputHandler.h"
#include "Foreach.h"
#include "InputFilter.h"
#include "LocalizedString.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "arch/arch_default.h"
#include "global.h"
Variables
static LocalizedString HOME ("DeviceButton", "Home")
static LocalizedString END ("DeviceButton", "End")
static LocalizedString UP ("DeviceButton", "Up")
static LocalizedString DOWN ("DeviceButton", "Down")
static LocalizedString SPACE ("DeviceButton", "Space")
static LocalizedString SHIFT ("DeviceButton", "Shift")
static LocalizedString CTRL ("DeviceButton", "Ctrl")
static LocalizedString ALT ("DeviceButton", "Alt")
static LocalizedString INSERT ("DeviceButton", "Insert")
static LocalizedString DEL ("DeviceButton", "Delete")
static LocalizedString PGUP ("DeviceButton", "PgUp")
static LocalizedString PGDN ("DeviceButton", "PgDn")
static LocalizedString BACKSLASH ("DeviceButton", "Backslash")
static LocalizedString INPUT_HANDLERS_EMPTY ("Arch", "Input Handlers cannot be empty.")
Variable Documentation
ALT
LocalizedString ALT("DeviceButton", "Alt") static
Referenced by InputHandler::GetLocalizedInputString().
BACKSLASH
LocalizedString BACKSLASH("DeviceButton", "Backslash") static
Referenced by InputHandler::GetLocalizedInputString().
CTRL
LocalizedString CTRL("DeviceButton", "Ctrl") static
Referenced by InputHandler::GetLocalizedInputString().
DEL
LocalizedString DEL("DeviceButton", "Delete") static
Referenced by InputHandler::GetLocalizedInputString().
DOWN
LocalizedString DOWN("DeviceButton", "Down") static
Referenced by InputHandler::GetLocalizedInputString().
END
LocalizedString END("DeviceButton", "End") static
Referenced by InputHandler::GetLocalizedInputString().
HOME
LocalizedString HOME("DeviceButton", "Home") static
Referenced by InputHandler::GetLocalizedInputString().
INPUT_HANDLERS_EMPTY
LocalizedString INPUT_HANDLERS_EMPTY("Arch", "Input Handlers cannot be empty.") static
Referenced by InputHandler::Create().
INSERT
LocalizedString INSERT("DeviceButton", "Insert") static
Referenced by InputHandler::GetLocalizedInputString().
PGDN
LocalizedString PGDN("DeviceButton", "PgDn") static
Referenced by InputHandler::GetLocalizedInputString().
PGUP
LocalizedString PGUP("DeviceButton", "PgUp") static
Referenced by InputHandler::GetLocalizedInputString().
SHIFT
LocalizedString SHIFT("DeviceButton", "Shift") static
Referenced by InputHandler::GetLocalizedInputString().
SPACE
LocalizedString SPACE("DeviceButton", "Space") static
Referenced by InputHandler::GetLocalizedInputString().
UP
LocalizedString UP("DeviceButton", "Up") static
Referenced by InputHandler::GetLocalizedInputString().