Etterna: TitleSubst Class Reference
TitleSubst Class Reference
Automatic translation for Song titles.
#include <TitleSubstitution.h>
Public Member Functions
TitleSubst (const RString &section)
~TitleSubst ()
void Load (const RString &filename, const RString &section)
void Subst (TitleFields &tf)
Private Member Functions
void AddTrans (const TitleTrans &tr)
Private Attributes
vector< TitleTrans * > ttab
Detailed Description
Automatic translation for Song titles.
Constructor & Destructor Documentation
TitleSubst()
TitleSubst::TitleSubst (const RString & section)
References Load().
~TitleSubst()
TitleSubst::~TitleSubst ()
References ttab.
Member Function Documentation
AddTrans()
void TitleSubst::AddTrans (const TitleTrans & tr) private
References TitleTrans::ArtistFrom, ASSERT, Regex::IsSet(), TitleTrans::SubFrom, TitleTrans::TitleFrom, and ttab.
Referenced by Load().
Load()
void TitleSubst::Load (const RString & filename, const RString & section)
References AddTrans(), FOREACH_CONST_Child, XNode::GetChild(), XmlFileUtil::LoadFromFileShowErrors(), and TitleTrans::LoadFromNode().
Referenced by TitleSubst().
Subst()
void TitleSubst::Subst (TitleFields & tf)
References TitleFields::Artist, TitleFields::ArtistTranslit, ERASE_MARKER, FOREACH_CONST, TitleTrans::Matches(), FontCharAliases::ReplaceMarkers(), TitleTrans::Replacement, TitleFields::Subtitle, TitleFields::SubtitleTranslit, TitleFields::Title, TitleFields::TitleTranslit, TitleTrans::translit, and ttab.
Referenced by SongManager::ShortenGroupName(), and Song::TranslateTitles().
Member Data Documentation
ttab
vector<TitleTrans*> TitleSubst::ttab private
Referenced by AddTrans(), Subst(), and ~TitleSubst().
The documentation for this class was generated from the following files:
TitleSubstitution.h
TitleSubstitution.cpp