Etterna: InputFilter Class Reference
InputFilter Class Reference
#include <InputFilter.h>
Public Member Functions
void ButtonPressed (const DeviceInput &di)
void SetButtonComment (const DeviceInput &di, const RString &sComment="")
void ResetDevice (InputDevice dev)
Release all buttons on the given device.
InputFilter ()
~InputFilter ()
void Reset ()
void Update (float fDeltaTime)
void SetRepeatRate (float fRepeatRate)
void SetRepeatDelay (float fDelay)
void ResetRepeatRate ()
void ResetKeyRepeat (const DeviceInput &di)
void RepeatStopKey (const DeviceInput &di)
Stop repeating the specified key until released.
bool IsBeingPressed (const DeviceInput &di, const DeviceInputList *pButtonState=nullptr) const
bool IsKBKeyPressed (DeviceButton k) const
bool IsControlPressed () const
bool IsShiftPressed () const
float GetSecsHeld (const DeviceInput &di, const DeviceInputList *pButtonState=nullptr) const
float GetLevel (const DeviceInput &di, const DeviceInputList *pButtonState=nullptr) const
RString GetButtonComment (const DeviceInput &di) const
void GetInputEvents (vector< InputEvent > &aEventOut)
void GetPressedButtons (vector< DeviceInput > &array) const
void UpdateCursorLocation (float _fX, float _fY)
void UpdateMouseWheel (float _fZ)
float GetCursorX ()
float GetCursorY ()
float GetMouseWheel ()
void PushSelf (lua_State *L)
Private Member Functions
void CheckButtonChange (ButtonState &bs, DeviceInput di, const std::chrono::steady_clock::time_point &now)
Check for reportable presses.
void ReportButtonChange (const DeviceInput &di, InputEventType t)
void MakeButtonStateList (vector< DeviceInput > &aInputOut) const
InputFilter (const InputFilter &rhs)
InputFilter & operator= (const InputFilter &rhs)
Private Attributes
vector< InputEvent > queue
RageMutex * queuemutex
MouseCoordinates m_MouseCoords
Constructor & Destructor Documentation
InputFilter() [1/2]
InputFilter::InputFilter ()
References MouseCoordinates::fX, MouseCoordinates::fY, MouseCoordinates::fZ, LuaManager::Get(), L, LUA, m_MouseCoords, PushSelf(), queuemutex, LuaManager::Release(), Reset(), and ResetRepeatRate().
~InputFilter()
InputFilter::~InputFilter ()
References LUA, queuemutex, and LuaManager::UnsetGlobal().
InputFilter() [2/2]
InputFilter::InputFilter (const InputFilter & rhs) private
Member Function Documentation
ButtonPressed()
void InputFilter::ButtonPressed (const DeviceInput & di)
References DeviceInput::bDown, DeviceInput::button, CheckButtonChange(), DeviceInput::device, LockMut, LOG, ButtonState::m_BeingHeld, ButtonState::m_BeingHeldTime, ButtonState::m_DeviceInput, MakeButtonStateList(), NUM_DeviceButton, NUM_InputDevice, queuemutex, RageLog::Trace(), DeviceInput::ts, and RageLog::Warn().
Referenced by InputHandler::ButtonPressed(), InputHandler_MacOSX_HID::QueueCallback(), and ResetDevice().
CheckButtonChange()
void InputFilter::CheckButtonChange (ButtonState & bs, DeviceInput di, const std::chrono::steady_clock::time_point & now) private
Check for reportable presses.
References DeviceInput::button, InputMapper::DeviceToGame(), g_fInputDebounceTime, IET_FIRST_PRESS, IET_RELEASE, INPUTMAPPER, DeviceInput::level, ButtonState::m_BeingHeld, ButtonState::m_BeingHeldTime, ButtonState::m_bLastReportedHeld, ButtonState::m_fSecsHeld, ButtonState::m_LastInputTime, ButtonState::m_LastReportTime, MakeButtonStateList(), MOUSE_WHEELDOWN, MOUSE_WHEELUP, ReportButtonChange(), and DeviceInput::ts.
Referenced by ButtonPressed(), and Update().
GetButtonComment()
RString InputFilter::GetButtonComment (const DeviceInput & di) const
References LockMut, and queuemutex.
Referenced by InputList::Update().
GetCursorX()
float InputFilter::GetCursorX () inline
References MouseCoordinates::fX, and m_MouseCoords.
Referenced by LunaInputFilter::GetMouseX().
GetCursorY()
float InputFilter::GetCursorY () inline
References MouseCoordinates::fY, and m_MouseCoords.
Referenced by LunaInputFilter::GetMouseY().
GetInputEvents()
void InputFilter::GetInputEvents (vector< InputEvent > & aEventOut)
References LockMut, queue, and queuemutex.
Referenced by HandleInputEvents().
GetLevel()
float InputFilter::GetLevel (const DeviceInput & di, const DeviceInputList * pButtonState = nullptr) const
References FindItemBinarySearch(), DeviceInput::level, LockMut, and queuemutex.
Referenced by InputMapper::GetLevel().
GetMouseWheel()
float InputFilter::GetMouseWheel () inline
References MouseCoordinates::fZ, and m_MouseCoords.
Referenced by LunaInputFilter::GetMouseWheel(), and InputHandler_X11::Update().
GetPressedButtons()
void InputFilter::GetPressedButtons (vector< DeviceInput > & array) const
References LockMut, and queuemutex.
Referenced by InputList::Update().
GetSecsHeld()
float InputFilter::GetSecsHeld (const DeviceInput & di, const DeviceInputList * pButtonState = nullptr) const
References FindItemBinarySearch(), LockMut, queuemutex, and DeviceInput::ts.
Referenced by InputMapper::GetSecsHeld(), ScreenSyncOverlay::Input(), and ScreenGameplay::Input().
IsBeingPressed()
bool InputFilter::IsBeingPressed (const DeviceInput & di, const DeviceInputList * pButtonState = nullptr) const
References DeviceInput::bDown, FindItemBinarySearch(), LockMut, and queuemutex.
Referenced by DebugLineAutoplay::DoAndLog(), DebugLineAssist::DoAndLog(), HandleGlobalInputs(), ScreenSyncOverlay::Input(), ScreenNetSelectBase::Input(), ScreenDebugOverlay::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), InputMapper::IsBeingPressed(), LunaInputFilter::IsBeingPressed(), IsKBKeyPressed(), and ScreenDebugOverlay::Update().
IsControlPressed()
bool InputFilter::IsControlPressed () const
References IsKBKeyPressed(), KEY_LCTRL, and KEY_RCTRL.
Referenced by InputHandler::ApplyKeyModifiers(), and ScreenTextEntry::Input().
IsKBKeyPressed()
bool InputFilter::IsKBKeyPressed (DeviceButton k) const
References DEVICE_KEYBOARD, and IsBeingPressed().
Referenced by IsControlPressed(), and IsShiftPressed().
IsShiftPressed()
bool InputFilter::IsShiftPressed () const
References IsKBKeyPressed(), KEY_LSHIFT, and KEY_RSHIFT.
Referenced by InputHandler::ApplyKeyModifiers().
MakeButtonStateList()
void InputFilter::MakeButtonStateList (vector< DeviceInput > & aInputOut) const private
References ButtonState::m_bLastReportedHeld, ButtonState::m_DeviceInput, and ButtonState::m_LastInputTime.
Referenced by ButtonPressed(), CheckButtonChange(), and Update().
operator=()
InputFilter& InputFilter::operator= (const InputFilter & rhs) private
PushSelf()
void InputFilter::PushSelf (lua_State * L)
Referenced by InputFilter().
RepeatStopKey()
void InputFilter::RepeatStopKey (const DeviceInput & di)
Stop repeating the specified key until released.
References LockMut, ButtonState::m_bLastReportedHeld, and queuemutex.
Referenced by InputMapper::RepeatStopKey().
ReportButtonChange()
void InputFilter::ReportButtonChange (const DeviceInput & di, InputEventType t) private
References InputEvent::di, InputEvent::m_ButtonState, queue, and InputEvent::type.
Referenced by CheckButtonChange(), and Update().
Reset()
void InputFilter::Reset ()
References FOREACH_InputDevice, and ResetDevice().
Referenced by CheckFocus(), InputFilter(), GameLoop::RunGameLoop(), and InputHandler_X11::Update().
ResetDevice()
void InputFilter::ResetDevice (InputDevice dev)
Release all buttons on the given device.
References DeviceButtonPair::button, ButtonPressed(), DeviceButtonPair::device, FOREACHM_CONST, LockMut, and queuemutex.
Referenced by InputHandler_DInput::PollAndAcquireDevices(), Reset(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::WindowReset().
ResetKeyRepeat()
void InputFilter::ResetKeyRepeat (const DeviceInput & di)
References LockMut, and queuemutex.
Referenced by InputMapper::ResetKeyRepeat().
ResetRepeatRate()
void InputFilter::ResetRepeatRate ()
References REPEATS_PER_SEC, SetRepeatDelay(), SetRepeatRate(), and TIME_BEFORE_REPEATS.
Referenced by Screen::HandleScreenMessage(), and InputFilter().
SetButtonComment()
void InputFilter::SetButtonComment (const DeviceInput & di, const RString & sComment = "")
References LockMut, ButtonState::m_sComment, and queuemutex.
SetRepeatDelay()
void InputFilter::SetRepeatDelay (float fDelay)
References g_fTimeBeforeRepeats.
Referenced by Screen::HandleScreenMessage(), and ResetRepeatRate().
SetRepeatRate()
void InputFilter::SetRepeatRate (float fRepeatRate)
References g_fTimeBetweenRepeats.
Referenced by Screen::HandleScreenMessage(), and ResetRepeatRate().
Update()
void InputFilter::Update (float fDeltaTime)
References DeviceInput::button, CheckButtonChange(), DeviceInput::device, DeviceButton_Invalid, f, FOREACH, FOREACHM, ftruncf(), g_fInputDebounceTime, g_fTimeBeforeRepeats, g_fTimeBetweenRepeats, IET_REPEAT, InputDevice_Invalid, INPUTMAN, DeviceInput::level, LockMut, ButtonState::m_bLastReportedHeld, ButtonState::m_DeviceInput, ButtonState::m_fSecsHeld, ButtonState::m_LastInputTime, ButtonState::m_LastReportTime, MakeButtonStateList(), queuemutex, ReportButtonChange(), DeviceInput::ts, and RageInput::Update().
Referenced by HandleInputEvents().
UpdateCursorLocation()
void InputFilter::UpdateCursorLocation (float _fX, float _fY)
References MouseCoordinates::fX, MouseCoordinates::fY, and m_MouseCoords.
Referenced by InputHandler_X11::Update(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
UpdateMouseWheel()
void InputFilter::UpdateMouseWheel (float _fZ)
References MouseCoordinates::fZ, and m_MouseCoords.
Referenced by InputHandler_X11::Update(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
Member Data Documentation
m_MouseCoords
MouseCoordinates InputFilter::m_MouseCoords private
Referenced by GetCursorX(), GetCursorY(), GetMouseWheel(), InputFilter(), UpdateCursorLocation(), and UpdateMouseWheel().
queue
vector<InputEvent> InputFilter::queue private
Referenced by GetInputEvents(), and ReportButtonChange().
queuemutex
RageMutex* InputFilter::queuemutex private
Referenced by ButtonPressed(), GetButtonComment(), GetInputEvents(), GetLevel(), GetPressedButtons(), GetSecsHeld(), InputFilter(), IsBeingPressed(), RepeatStopKey(), ResetDevice(), ResetKeyRepeat(), SetButtonComment(), Update(), and ~InputFilter().
The documentation for this class was generated from the following files:
InputFilter.h
InputFilter.cpp