Etterna: ArrowEffects Class Reference
ArrowEffects Class Reference
Functions that return properties of arrows based on Style and PlayerOptions.
#include <ArrowEffects.h>
Static Public Member Functions
static void Update ()
static void SetCurrentOptions (const PlayerOptions *options)
static float GetYOffset (const PlayerState *pPlayerState, int iCol, float fNoteBeat, float &fPeakYOffsetOut, bool &bIsPastPeakYOffset, bool bAbsolute=false)
static float GetYOffset (const PlayerState *pPlayerState, int iCol, float fNoteBeat, bool bAbsolute=false)
static void GetXYZPos (const PlayerState *player_state, int col, float y_offset, float y_reverse_offset, RageVector3 &ret, bool with_reverse=true)
static float GetYPos (int iCol, float fYOffset, float fYReverseOffsetPixels, bool WithReverse=true)
Retrieve the actual display position.
static float GetYOffsetFromYPos (int iCol, float YPos, float fYReverseOffsetPixels)
static float GetRotationZ (const PlayerState *pPlayerState, float fNoteBeat, bool bIsHoldHead)
static float ReceptorGetRotationZ (const PlayerState *pPlayerState)
static float GetRotationX (float fYOffset)
static float GetRotationY (float fYOffset)
static float GetXPos (const PlayerState *pPlayerState, int iCol, float fYOffset)
static float GetZPos (int iCol, float fYPos)
Retrieve the Z position.
static bool NeedZBuffer ()
static float GetAlpha (int iCol, float fYPos, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar)
static float GetGlow (int iCol, float fYPos, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar)
static float GetBrightness (const PlayerState *pPlayerState, float fNoteBeat)
Retrieve the current brightness.
static float GetZoom (const PlayerState *pPlayerState)
static float GetFrameWidthScale (const PlayerState *pPlayerState, float fYOffset, float fOverlappedTime)
Detailed Description
Functions that return properties of arrows based on Style and PlayerOptions.
Member Function Documentation
GetAlpha()
float ArrowEffects::GetAlpha (int iCol, float fYPos, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar) static
References ArrowGetPercentVisible(), f, GetYPos(), and SCALE.
Referenced by ArrowGetAlphaOrGlow(), and NoteDisplay::DrawActor().
GetBrightness()
float ArrowEffects::GetBrightness (const PlayerState * pPlayerState, float fNoteBeat) static
Retrieve the current brightness.
Note that this depends on fYOffset.
Parameters
pPlayerState the present PlayerState.
fNoteBeat the current beat.
Returns
the current brightness.
References CLAMP(), f, GAMESTATE, GameState::IsEditing(), SongPosition::m_fSongBeatVisible, PlayerState::m_Position, and SCALE.
Referenced by NoteDisplay::DrawActor().
GetFrameWidthScale()
float ArrowEffects::GetFrameWidthScale (const PlayerState * pPlayerState, float fYOffset, float fOverlappedTime) static
References CLAMP(), f, FRAME_WIDTH_EFFECTS_MAX_MULTIPLIER, FRAME_WIDTH_EFFECTS_MIN_MULTIPLIER, FRAME_WIDTH_EFFECTS_PIXELS_PER_SECOND, FRAME_WIDTH_LOCK_EFFECTS_TO_OVERLAPPING, FRAME_WIDTH_LOCK_EFFECTS_TWEEN_PIXELS, SampleHistory::GetSample(), PlayerState::m_EffectHistory, and SCALE.
Referenced by NoteDisplay::DrawHoldPart().
GetGlow()
float ArrowEffects::GetGlow (int iCol, float fYPos, float fPercentFadeToFail, float fYReverseOffsetPixels, float fDrawDistanceBeforeTargetsPixels, float fFadeInPercentOfDrawFar) static
References ArrowGetPercentVisible(), f, GetYPos(), and SCALE.
Referenced by ArrowGetAlphaOrGlow(), and NoteDisplay::DrawActor().
GetRotationX()
float ArrowEffects::GetRotationX (float fYOffset) static
References PlayerOptions::EFFECT_ROLL, and PlayerOptions::m_fEffects.
Referenced by NoteDisplay::DrawActor().
GetRotationY()
float ArrowEffects::GetRotationY (float fYOffset) static
References PlayerOptions::EFFECT_TWIRL, and PlayerOptions::m_fEffects.
Referenced by NoteDisplay::DrawActor(), and NoteDisplay::DrawHoldPart().
GetRotationZ()
float ArrowEffects::GetRotationZ (const PlayerState * pPlayerState, float fNoteBeat, bool bIsHoldHead) static
References DIZZY_HOLD_HEADS, PlayerOptions::EFFECT_CONFUSION, PlayerOptions::EFFECT_DIZZY, PlayerOptions::m_fEffects, SongPosition::m_fSongBeatVisible, PlayerState::m_Position, PI, and ReceptorGetRotationZ().
Referenced by NoteDisplay::DrawActor().
GetXPos()
float ArrowEffects::GetXPos (const PlayerState * pPlayerState, int iCol, float fYOffset) static
References ARROW_SIZE, BEAT_OFFSET_HEIGHT, BEAT_PI_HEIGHT, DEFAULT_FAIL, DRUNK_ARROW_MAGNITUDE, DRUNK_COLUMN_FREQUENCY, DRUNK_OFFSET_FREQUENCY, PlayerOptions::EFFECT_BEAT, PlayerOptions::EFFECT_DRUNK, PlayerOptions::EFFECT_FLIP, PlayerOptions::EFFECT_INVERT, PlayerOptions::EFFECT_TINY, PlayerOptions::EFFECT_TORNADO, PlayerOptions::EFFECT_XMODE, Style::ColumnInfo::fXOffset, GAMESTATE, GameState::GetCurrentStyle(), RageTimer::GetTimeSinceStartFast(), Style::m_ColumnInfo, PlayerOptions::m_fEffects, Style::m_iColsPerPlayer, PlayerState::m_NotefieldZoom, PlayerState::m_PlayerNumber, Style::m_StyleType, min(), PI, PLAYER_2, RageFastCos(), RageFastSin(), SCALE, SCREEN_HEIGHT, StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, StyleType_TwoPlayersTwoSides, TINY_PERCENT_BASE, TINY_PERCENT_GATE, TORNADO_OFFSET_FREQUENCY, TORNADO_OFFSET_SCALE_FROM_HIGH, TORNADO_OFFSET_SCALE_FROM_LOW, TORNADO_POSITION_SCALE_TO_HIGH, and TORNADO_POSITION_SCALE_TO_LOW.
Referenced by GetXYZPos(), and Player::Update().
GetXYZPos()
static void ArrowEffects::GetXYZPos (const PlayerState * player_state, int col, float y_offset, float y_reverse_offset, RageVector3 & ret, bool with_reverse = true) inline static
References GetXPos(), GetYPos(), GetZPos(), RageVector3::x, RageVector3::y, and RageVector3::z.
Referenced by NoteColumnRenderArgs::spae_pos_for_beat(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
GetYOffset() [1/2]
float ArrowEffects::GetYOffset (const PlayerState * pPlayerState, int iCol, float fNoteBeat, float & fPeakYOffsetOut, bool & bIsPastPeakYOffset, bool bAbsolute = false) static
References PlayerOptions::ACCEL_BOOMERANG, PlayerOptions::ACCEL_BOOST, PlayerOptions::ACCEL_BRAKE, PlayerOptions::ACCEL_EXPAND, PlayerOptions::ACCEL_WAVE, ARROW_SPACING, BeatToNoteRow(), BOOMERANG_PEAK_PERCENTAGE, BOOST_MOD_MAX_CLAMP, BOOST_MOD_MIN_CLAMP, BRAKE_MOD_MAX_CLAMP, BRAKE_MOD_MIN_CLAMP, CLAMP(), EXPAND_MULTIPLIER_FREQUENCY, EXPAND_MULTIPLIER_SCALE_FROM_HIGH, EXPAND_MULTIPLIER_SCALE_FROM_LOW, EXPAND_MULTIPLIER_SCALE_TO_HIGH, EXPAND_MULTIPLIER_SCALE_TO_LOW, EXPAND_SPEED_SCALE_FROM_HIGH, EXPAND_SPEED_SCALE_FROM_LOW, EXPAND_SPEED_SCALE_TO_LOW, f, GAMESTATE, ModsGroup< T >::GetCurrent(), GetDisplayedBeat(), PlayerState::GetDisplayedPosition(), TimingData::GetDisplayedSpeedPercent(), GetNoteFieldHeight(), Steps::GetTimingData(), PlayerOptions::m_fAccels, PlayerOptions::m_fMaxScrollBPM, SongOptions::m_fMusicRate, SongPosition::m_fMusicSecondsVisible, PlayerOptions::m_fRandomSpeed, PlayerState::m_fReadBPM, PlayerOptions::m_fScrollBPM, PlayerOptions::m_fScrollSpeed, SongPosition::m_fSongBeatVisible, PlayerOptions::m_fTimeSpacing, GameState::m_iStageSeed, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, GameState::m_Position, GameState::m_SongOptions, RageFastCos(), RageFastSin(), SCALE, SCREEN_HEIGHT, WAVE_MOD_HEIGHT, WAVE_MOD_MAGNITUDE, and TimingData::WhereUAtBro().
Referenced by NoteField::DrawAreaHighlight(), NoteField::DrawBeatBar(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldsInRange(), NoteField::DrawMarkerBar(), NoteDisplay::DrawTap(), FindDisplayedBeats(), GetYOffset(), NoteField::set_text_measure_number_for_draw(), and NoteField::Update().
GetYOffset() [2/2]
static float ArrowEffects::GetYOffset (const PlayerState * pPlayerState, int iCol, float fNoteBeat, bool bAbsolute = false) inline static
References GetYOffset().
GetYOffsetFromYPos()
float ArrowEffects::GetYOffsetFromYPos (int iCol, float YPos, float fYReverseOffsetPixels) static
References ArrowGetReverseShiftAndScale(), PlayerOptions::EFFECT_TIPSY, f, PlayerOptions::m_fEffects, and PlayerOptions::m_pn.
Referenced by NoteDisplay::DrawHoldPart().
GetYPos()
float ArrowEffects::GetYPos (int iCol, float fYOffset, float fYReverseOffsetPixels, bool WithReverse = true) static
Retrieve the actual display position.
In this case, reverse and post-reverse-effects are factored in (fYOffset -> YPos).
Parameters
pPlayerState the Player's state in question, including mods.
iCol the specific arrow column.
fYOffset the original display position.
fYReverseOffsetPixels the amount offset due to reverse.
WithReverse a flag to see if the Reverse mod is on.
Returns
the actual display position.
References ArrowGetReverseShiftAndScale(), PlayerOptions::EFFECT_TIPSY, f, PlayerOptions::m_fEffects, PlayerOptions::m_pn, and QUANTIZE_ARROW_Y.
Referenced by NoteField::DrawAreaHighlight(), NoteField::DrawBeatBar(), NoteField::DrawBoard(), NoteDisplay::DrawHold(), NoteDisplay::DrawHoldBody(), NoteField::DrawMarkerBar(), GetAlpha(), GetGlow(), GetXYZPos(), NoteField::set_text_measure_number_for_draw(), and NoteField::Update().
GetZoom()
float ArrowEffects::GetZoom (const PlayerState * pPlayerState) static
References PlayerOptions::EFFECT_TINY, f, PlayerOptions::m_fEffects, and PlayerState::m_NotefieldZoom.
Referenced by NoteDisplay::DrawHoldBody(), NoteDisplay::DrawHoldPart(), NoteField::GetWidth(), NoteField::set_text_measure_number_for_draw(), NoteColumnRenderArgs::spae_zoom_for_beat(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
GetZPos()
float ArrowEffects::GetZPos (int iCol, float fYPos) static
Retrieve the Z position.
This is normally 0. This is only visible with perspective modes.
Parameters
pPlayerState the Player's state, including the mods.
iCol the specific arrow column.
fYPos the Y position of the arrow.
Returns
the Z position.
References PlayerOptions::EFFECT_BUMPY, f, PlayerOptions::m_fEffects, and RageFastSin().
Referenced by GetXYZPos(), and Player::Update().
NeedZBuffer()
bool ArrowEffects::NeedZBuffer () static
References PlayerOptions::EFFECT_BUMPY, PlayerOptions::EFFECT_TWIRL, and PlayerOptions::m_fEffects.
Referenced by NoteDisplay::DrawHoldBody().
ReceptorGetRotationZ()
float ArrowEffects::ReceptorGetRotationZ (const PlayerState * pPlayerState) static
References PlayerOptions::EFFECT_CONFUSION, PlayerOptions::m_fEffects, SongPosition::m_fSongBeatVisible, PlayerState::m_Position, and PI.
Referenced by GetRotationZ(), and NoteColumnRenderer::UpdateReceptorGhostStuff().
SetCurrentOptions()
void ArrowEffects::SetCurrentOptions (const PlayerOptions * options) static
Referenced by NoteField::DrawPrimitives(), NoteField::Update(), and Player::Update().
Update()
void ArrowEffects::Update () static
References ARROW_SIZE, CLAMP(), PlayerOptions::EFFECT_BEAT, PlayerOptions::EFFECT_INVERT, PlayerOptions::EFFECT_TIPSY, PlayerOptions::EFFECT_TORNADO, f, FOREACH_EnabledPlayer, Style::ColumnInfo::fXOffset, GAMESTATE, ModsGroup< T >::GetCurrent(), GameState::GetCurrentStyle(), RageTimer::GetTimeSinceStartFast(), SongPosition::m_bDelay, SongPosition::m_bFreeze, GameState::m_bIsUsingStepTiming, Style::m_ColumnInfo, PlayerOptions::m_fEffects, SongPosition::m_fSongBeatVisible, Style::m_iColsPerPlayer, PlayerState::m_NotefieldZoom, PlayerState::m_PlayerOptions, PlayerState::m_Position, GameState::m_Position, GameState::m_pPlayerState, Style::m_StyleType, max(), MAX_COLS_PER_PLAYER, min(), PI, RageFastCos(), SCALE, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, TIPSY_ARROW_MAGNITUDE, TIPSY_COLUMN_FREQUENCY, TIPSY_OFFSET_ARROW_MAGNITUDE, TIPSY_OFFSET_COLUMN_FREQUENCY, TIPSY_OFFSET_TIMER_FREQUENCY, and TIPSY_TIMER_FREQUENCY.
Referenced by ReceptorArrowRow::Update(), and ScreenGameplay::Update().
The documentation for this class was generated from the following files:
ArrowEffects.h
ArrowEffects.cpp