Etterna: MusicWheel Class Reference
MusicWheel Class Reference
#include <MusicWheel.h>
Public Member Functions
~MusicWheel () override
void Load (const string &sType) override
void BeginScreen ()
bool ChangeSort (SortOrder new_so, bool allowSameSort=false)
bool NextSort ()
bool IsRouletting () const
bool Select () override
WheelItemDataType GetSelectedType ()
Song * GetSelectedSong ()
RString GetSelectedSection ()
Song * GetPreferredSelectionForRandomOrPortal ()
bool SelectSong (const Song *p)
bool SelectSection (const RString &SectionName)
void SetOpenSection (const RString &group) override
SortOrder GetSortOrder () const
void ChangeMusic (int dist) override
void FinishChangingSorts ()
void PlayerJoined ()
RString JumpToNextGroup ()
RString JumpToPrevGroup ()
const MusicWheelItemData * GetCurWheelItemData (int i)
virtual void ReloadSongList (bool searching, RString findme)
void SetHashList (const vector< string > &newHashList)
void PushSelf (lua_State *L) override
Public Member Functions inherited from WheelBase
~WheelBase () override
void BeginScreen ()
void Update (float fDeltaTime) override
virtual void Move (int n)
void ChangeMusicUnlessLocked (int n)
int IsMoving () const
bool IsSettled () const
void GetItemPosition (float fPosOffsetsFromMiddle, float &fX_out, float &fY_out, float &fZ_out, float &fRotationX_out)
void SetItemPosition (Actor &item, int item_index, float offset_from_middle)
WheelState GetWheelState ()
bool WheelIsLocked ()
void RebuildWheelItems (int dist=INT_MAX)
virtual void ReloadSongList ()
virtual unsigned int GetNumItems () const
bool IsEmpty ()
WheelItemBaseData * GetItem (unsigned int index)
WheelItemBaseData * LastSelected ()
WheelItemBase * GetWheelItem (int i)
RString GetExpandedSectionName ()
int GetCurrentIndex ()
WheelItemDataType GetSelectedType ()
void PushSelf (lua_State *L) override
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Member Functions
MusicWheelItem * MakeItem () override
void GetSongList (vector< Song *> &arraySongs, SortOrder so)
bool SelectSongOrCourse ()
bool SelectModeMenuItem ()
void FilterByStepKeys (vector< Song *> &inv)
void FilterBySearch (vector< Song *> &inv, RString findme)
bool SearchGroupNames (RString &findme)
void FilterBySkillsets (vector< Song *> &inv)
void UpdateSwitch () override
vector< MusicWheelItemData * > & getWheelItemsData (SortOrder so)
void readyWheelItemsData (SortOrder so, bool searching, RString findme)
bool WheelItemIsVisible (int n)
Protected Member Functions inherited from WheelBase
void TweenOnScreenForSort ()
void TweenOffScreenForSort ()
virtual bool MoveSpecific (int n)
void SetPositions ()
int FirstVisibleIndex ()
void UpdateScrollbar ()
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
vector< string > hashList
RString lastvalidsearch
RString groupnamesearchmatch
RString m_sLastModeMenuItem
SortOrder m_SortOrder
RageSound m_soundChangeSort
ThemeMetric< float > ROULETTE_SWITCH_SECONDS
ThemeMetric< int > ROULETTE_SLOW_DOWN_SWITCHES
ThemeMetric< int > NUM_SECTION_COLORS
ThemeMetric< RageColor > SONG_REAL_EXTRA_COLOR
ThemeMetric< RageColor > SORT_MENU_COLOR
ThemeMetric< bool > SHOW_ROULETTE
ThemeMetric< bool > SHOW_RANDOM
ThemeMetric< bool > SHOW_PORTAL
ThemeMetric< bool > RANDOM_PICKS_LOCKED_SONGS
ThemeMetric< int > MOST_PLAYED_SONGS_TO_SHOW
ThemeMetric< int > RECENT_SONGS_TO_SHOW
ThemeMetric< RString > MODE_MENU_CHOICE_NAMES
ThemeMetricMap< RString > CHOICE
ThemeMetric1D< RageColor > SECTION_COLORS
ThemeMetric< LuaReference > SORT_ORDERS
ThemeMetric< bool > SHOW_EASY_FLAG
ThemeMetric< bool > USE_SECTIONS_WITH_PREFERRED_GROUP
ThemeMetric< bool > HIDE_INACTIVE_SECTIONS
ThemeMetric< bool > HIDE_ACTIVE_SECTION_TITLE
ThemeMetric< bool > REMIND_WHEEL_POSITIONS
ThemeMetric< RageColor > ROULETTE_COLOR
ThemeMetric< RageColor > RANDOM_COLOR
ThemeMetric< RageColor > PORTAL_COLOR
ThemeMetric< RageColor > EMPTY_COLOR
vector< int > m_viWheelPositions
ThemeMetric< RString > CUSTOM_WHEEL_ITEM_NAMES
ThemeMetricMap< RString > CUSTOM_CHOICES
ThemeMetricMap< RageColor > CUSTOM_CHOICE_COLORS
Protected Attributes inherited from WheelBase
ScrollBar m_ScrollBar
AutoActor m_sprHighlight
vector< WheelItemBaseData * > m_CurWheelItemData
vector< WheelItemBase * > m_WheelBaseItems
WheelItemBaseData * m_LastSelection
bool m_bEmpty
int m_iSelection
RString m_sExpandedSectionName
int m_iSwitchesLeftInSpinDown
float m_fLockedWheelVelocity
int m_Moving
RageTimer m_MovingSoundTimer
float m_TimeBeforeMovingBegins
float m_SpinSpeed
WheelState m_WheelState
float m_fTimeLeftInState
float m_fPositionOffsetFromSelection
RageSound m_soundChangeMusic
RageSound m_soundExpand
RageSound m_soundCollapse
RageSound m_soundLocked
ThemeMetric< float > SWITCH_SECONDS
ThemeMetric< float > LOCKED_INITIAL_VELOCITY
ThemeMetric< int > SCROLL_BAR_HEIGHT
LuaExpressionTransform m_exprItemTransformFunction
ThemeMetric< float > NUM_WHEEL_ITEMS_TO_DRAW
ThemeMetric< RageColor > WHEEL_ITEM_LOCKED_COLOR
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Private Types
enum { INVALID, NEEDREFILTER, VALID }
Private Member Functions
void BuildWheelItemDatas (vector< MusicWheelItemData *> &arrayWheelItems, SortOrder so, bool searching, RString findme)
void FilterWheelItemDatas (vector< MusicWheelItemData *> &aUnFilteredDatas, vector< MusicWheelItemData *> &aFilteredData, SortOrder so)
void SelectSongAfterSearch ()
Private Attributes
enum MusicWheel:: { ... } m_WheelItemDatasStatus [NUM_SortOrder]
vector< MusicWheelItemData * > m__WheelItemDatas [NUM_SortOrder]
vector< MusicWheelItemData * > m__UnFilteredWheelItemDatas [NUM_SortOrder]
RString prevSongTitle
Friends
struct CompareSongPointerArrayBySectionName
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
INVALID
NEEDREFILTER
VALID
Constructor & Destructor Documentation
~MusicWheel()
MusicWheel::~MusicWheel () override
References FOREACH_ENUM, and m__UnFilteredWheelItemDatas.
Member Function Documentation
BeginScreen()
void MusicWheel::BeginScreen ()
References ASSERT, WheelBase::BeginScreen(), FOREACH_ENUM, GAMESTATE, SongManager::GetSongGroupByIndex(), getWheelItemsData(), GROUP_ALL, HIDE_INACTIVE_SECTIONS, INVALID, WheelBase::m_iSelection, GameState::m_PreferredSortOrder, WheelBase::m_sExpandedSectionName, m_sLastModeMenuItem, GameState::m_SortOrder, GameState::m_sPreferredSongGroup, m_viWheelPositions, m_WheelItemDatasStatus, NEEDREFILTER, WheelBase::RebuildWheelItems(), REMIND_WHEEL_POSITIONS, SelectSongOrCourse(), BroadcastOnChange< T >::Set(), SetOpenSection(), SONGMAN, SORT_MODE_MENU, and SortOrder_Invalid.
Referenced by ScreenSelectMusic::BeginScreen(), and ScreenNetSelectMusic::Init().
BuildWheelItemDatas()
void MusicWheel::BuildWheelItemDatas (vector< MusicWheelItemData *> & arrayWheelItems, SortOrder so, bool searching, RString findme) private
References FilterManager::AnyActiveFilter(), WheelNotifyIcon::Flags::bEdits, WheelNotifyIcon::Flags::bHasBeginnerOr1Meter, MessageManager::Broadcast(), CHOICE, FAIL_M, FilterBySearch(), FilterBySkillsets(), FilterByStepKeys(), FILTERMAN, FOREACHS, GAMESTATE, GameState::GetCurrentStyle(), GameState::GetNumStagesMultiplierForSong(), SongUtil::GetPlayableStepsTypes(), SongUtil::GetSectionNameFromSongAndSort(), SongManager::GetSongColor(), SongManager::GetSongGroupColor(), GetSongList(), ThemeMetric1D< T >::GetValue(), GROUP_ALL, SongManager::groupderps, Song::HasEdits(), hashList, Song::IsEasy(), GameCommand::IsPlayable(), WheelNotifyIcon::Flags::iStagesForSong, GameCommand::Load(), MusicWheelItemData::m_Flags, PrefsManager::m_MusicWheelUsesSections, MusicWheelItemData::m_pAction, MusicWheelItemData::m_pSong, Song::m_sGroupName, MusicWheelItemData::m_sLabel, GameCommand::m_sName, GameState::m_sPreferredSongGroup, Style::m_StepsType, Rage::make_lower(), MESSAGEMAN, MODE_MENU_CHOICE_NAMES, MOST_PLAYED_SONGS_TO_SHOW, MusicWheelUsesSections_ABC_ONLY, MusicWheelUsesSections_NEVER, NUM_SECTION_COLORS, ParseCommands(), PLAYER_INVALID, PREFSMAN, RECENT_SONGS_TO_SHOW, SECTION_COLORS, Message::SetParam(), SHOW_EASY_FLAG, Skill_Chordjack, Skill_Handstream, Skill_JackSpeed, Skill_Jumpstream, Skill_Overall, Skill_Stamina, Skill_Stream, Skill_Technical, SONGMAN, SORT_ARTIST, SORT_BPM, SORT_Chordjack, SORT_FAVORITES, SORT_GENRE, SORT_GROUP, SORT_Handstream, SORT_JackSpeed, SORT_Jumpstream, SORT_LENGTH, SORT_MENU_COLOR, SORT_MODE_MENU, SORT_Overall, SORT_POPULARITY, SORT_PREFERRED, SORT_RECENT, SORT_Stamina, SORT_Stream, SORT_Technical, SORT_TITLE, SORT_TOP_GRADES, SongUtil::SortSongPointerArrayByArtist(), SongUtil::SortSongPointerArrayByBPM(), SongUtil::SortSongPointerArrayByGenre(), SongUtil::SortSongPointerArrayByGrades(), SongUtil::SortSongPointerArrayByGroupAndMSD(), SongUtil::SortSongPointerArrayByGroupAndTitle(), SongUtil::SortSongPointerArrayByLength(), SongUtil::SortSongPointerArrayBySectionName(), SongUtil::SortSongPointerArrayByTitle(), split(), USE_SECTIONS_WITH_PREFERRED_GROUP, WHEEL_TEXT, WheelItemDataType_Section, WheelItemDataType_Song, and WheelItemDataType_Sort.
Referenced by readyWheelItemsData().
ChangeMusic()
void MusicWheel::ChangeMusic (int dist) override virtual
Reimplemented from WheelBase.
References SongManager::GetSongGroupByIndex(), HIDE_INACTIVE_SECTIONS, WheelBase::IsMoving(), WheelBase::m_CurWheelItemData, WheelBase::m_fPositionOffsetFromSelection, WheelBase::m_iSelection, WheelBase::m_sExpandedSectionName, WheelBase::m_soundChangeMusic, m_viWheelPositions, RageSound::Play(), ScreenManager::PostMessageToTopScreen(), WheelBase::RebuildWheelItems(), REMIND_WHEEL_POSITIONS, SCREENMAN, SONGMAN, and wrap().
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), ReloadSongList(), SelectSong(), SelectSongAfterSearch(), and UpdateSwitch().
ChangeSort()
bool MusicWheel::ChangeSort (SortOrder new_so, bool allowSameSort = false)
References ASSERT, GAMESTATE, getWheelItemsData(), IsSongSort(), GameState::m_PreferredSortOrder, GameState::m_SortOrder, m_soundChangeSort, WheelBase::m_WheelState, NUM_SortOrder, RageSound::Play(), ScreenManager::PostMessageToTopScreen(), SCREENMAN, BroadcastOnChange< T >::Set(), SORT_MODE_MENU, STATE_FLYING_ON_AFTER_NEXT_SORT, STATE_SELECTING, and WheelBase::TweenOffScreenForSort().
Referenced by LunaMusicWheel::ChangeSort(), ScreenSelectMusic::DetectCodes(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::MenuLeft(), ScreenNetSelectMusic::MenuRight(), NextSort(), and Select().
FilterBySearch()
void MusicWheel::FilterBySearch (vector< Song *> & inv, RString findme) protected
References contains(), findme(), groupnamesearchmatch, lastvalidsearch, and SearchGroupNames().
Referenced by BuildWheelItemDatas().
FilterBySkillsets()
void MusicWheel::FilterBySkillsets (vector< Song *> & inv) protected
References FilterManager::ExclusiveFilter, f, FILTERMAN, TimingData::GetElapsedTimeFromBeat(), FilterManager::HighestSkillsetsOnly, FilterManager::m_pPlayerState, FilterManager::MaxFilterRate, NUM_Skillset, FilterManager::SSFilterLowerBounds, FilterManager::SSFilterUpperBounds, and PlayerState::wtFFF.
Referenced by BuildWheelItemDatas().
FilterByStepKeys()
void MusicWheel::FilterByStepKeys (vector< Song *> & inv) protected
References FOREACH, and hashList.
Referenced by BuildWheelItemDatas().
FilterWheelItemDatas()
void MusicWheel::FilterWheelItemDatas (vector< MusicWheelItemData *> & aUnFilteredDatas, vector< MusicWheelItemData *> & aFilteredData, SortOrder so) private
References CommonMetrics::AUTO_SET_STYLE, EMPTY_COLOR, EMPTY_STRING, GAMESTATE, GameState::GetCurrentStyle(), Song::HasStepsType(), WheelNotifyIcon::Flags::iPlayersBestNumber, SongUtil::IsSongPlayable(), MusicWheelItemData::m_Flags, MusicWheelItemData::m_iSectionCount, MusicWheelItemData::m_pSong, Style::m_StepsType, WheelItemBaseData::m_sText, WheelItemBaseData::m_Type, min(), PLAYER_INVALID, SORT_POPULARITY, WheelItemDataType_Portal, WheelItemDataType_Random, WheelItemDataType_Section, and WheelItemDataType_Song.
Referenced by readyWheelItemsData().
FinishChangingSorts()
void MusicWheel::FinishChangingSorts ()
References ActorFrame::FinishTweening(), WheelBase::m_fTimeLeftInState, WheelBase::m_WheelState, and STATE_SELECTING.
Referenced by ScreenSelectMusic::HandleScreenMessage().
GetCurWheelItemData()
const MusicWheelItemData* MusicWheel::GetCurWheelItemData (int i) inline
References WheelBase::m_CurWheelItemData.
Referenced by ScreenSelectMusic::AfterMusicChange(), GetSelectedSection(), GetSelectedSong(), GetSelectedType(), Select(), SelectModeMenuItem(), SelectSong(), SetOpenSection(), and UpdateSwitch().
GetPreferredSelectionForRandomOrPortal()
Song * MusicWheel::GetPreferredSelectionForRandomOrPortal ()
References Difficulty_Edit, Difficulty_Invalid, FOREACH, FOREACH_HumanPlayer, GAMESTATE, GameState::GetCurrentStyle(), getWheelItemsData(), Song::HasStepsTypeAndDifficulty(), GameState::m_PreferredDifficulty, WheelBase::m_sExpandedSectionName, GameState::m_SortOrder, Style::m_StepsType, NUM_PROBES, PLAYER_INVALID, RandomInt(), LuaHelpers::ReportScriptError(), and WheelItemDataType_Song.
Referenced by GetSelectedSong().
GetSelectedSection()
RString MusicWheel::GetSelectedSection () inline
References GetCurWheelItemData(), WheelBase::m_iSelection, and WheelItemBaseData::m_sText.
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::DetectCodes(), and ReloadSongList().
GetSelectedSong()
Song * MusicWheel::GetSelectedSong ()
References GetCurWheelItemData(), GetPreferredSelectionForRandomOrPortal(), WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, MusicWheelItemData::m_pSong, and WheelItemDataType_Portal.
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), ScreenNetSelectMusic::SelectCurrent(), ScreenSelectMusic::SelectCurrent(), and ScreenNetSelectMusic::StartSelectedSong().
GetSelectedType()
WheelItemDataType MusicWheel::GetSelectedType () inline
References GetCurWheelItemData(), WheelBase::m_iSelection, and WheelItemBaseData::m_Type.
Referenced by ScreenSelectMusic::AfterMusicChange(), LunaMusicWheel::MoveAndCheckType(), and ScreenNetSelectMusic::SelectCurrent().
GetSongList()
void MusicWheel::GetSongList (vector< Song *> & arraySongs, SortOrder so) protected
References CommonMetrics::AUTO_SET_STYLE, FOREACHS, GAMESTATE, SongManager::GetAllSongs(), GameState::GetCurrentStyle(), SongManager::GetFavoriteSongs(), SongUtil::GetPlayableStepsTypes(), SongManager::GetPopularSongs(), SongManager::GetPreferredSortSongs(), SongManager::GetSongs(), GROUP_ALL, Song::HasStepsType(), GameState::m_sPreferredSongGroup, Style::m_StepsType, PLAYER_INVALID, SONGMAN, SORT_FAVORITES, SORT_GROUP, SORT_POPULARITY, SORT_PREFERRED, and USE_SECTIONS_WITH_PREFERRED_GROUP.
Referenced by BuildWheelItemDatas().
GetSortOrder()
SortOrder MusicWheel::GetSortOrder () const inline
References m_SortOrder.
getWheelItemsData()
vector< MusicWheelItemData * > & MusicWheel::getWheelItemsData (SortOrder so) protected
References m__WheelItemDatas, and readyWheelItemsData().
Referenced by BeginScreen(), ChangeSort(), GetPreferredSelectionForRandomOrPortal(), SelectModeMenuItem(), SelectSong(), SelectSongAfterSearch(), SelectSongOrCourse(), and SetOpenSection().
IsRouletting()
bool MusicWheel::IsRouletting () const
References WheelBase::m_WheelState, STATE_RANDOM_SPINNING, STATE_ROULETTE_SLOWING_DOWN, and STATE_ROULETTE_SPINNING.
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::HandleScreenMessage(), ScreenSelectMusic::Input(), and LunaMusicWheel::IsRouletting().
JumpToNextGroup()
RString MusicWheel::JumpToNextGroup ()
References SongManager::GetNumSongGroups(), SongManager::GetSongGroupByIndex(), HIDE_INACTIVE_SECTIONS, WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, WheelBase::m_sExpandedSectionName, SONGMAN, and WheelItemDataType_Section.
Referenced by ScreenSelectMusic::DetectCodes(), and ScreenSelectMusic::Input().
JumpToPrevGroup()
RString MusicWheel::JumpToPrevGroup ()
References SongManager::GetNumSongGroups(), SongManager::GetSongGroupByIndex(), HIDE_INACTIVE_SECTIONS, LOG, WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, WheelBase::m_sExpandedSectionName, SONGMAN, RageLog::Trace(), and WheelItemDataType_Section.
Referenced by ScreenSelectMusic::DetectCodes(), and ScreenSelectMusic::Input().
Load()
void MusicWheel::Load (const string & sType) override virtual
Reimplemented from WheelBase.
References CHOICE, CHOICE_NAME(), CUSTOM_CHOICE_COLORS, CUSTOM_CHOICES, CUSTOM_WHEEL_ITEM_COLOR(), CUSTOM_WHEEL_ITEM_NAME(), CUSTOM_WHEEL_ITEM_NAMES, EMPTY_COLOR, FOREACH_ENUM, ThemeManager::GetPathS(), HIDE_ACTIVE_SECTION_TITLE, HIDE_INACTIVE_SECTIONS, INVALID, WheelBase::Load(), ThemeMetric< T >::Load(), RageSound::Load(), ThemeMetric1D< T >::Load(), ThemeMetricMap< T >::Load(), m_soundChangeSort, WheelBase::m_soundCollapse, WheelBase::m_soundExpand, m_WheelItemDatasStatus, MODE_MENU_CHOICE_NAMES, MOST_PLAYED_SONGS_TO_SHOW, NUM_SECTION_COLORS, PORTAL_COLOR, RANDOM_COLOR, RANDOM_PICKS_LOCKED_SONGS, RECENT_SONGS_TO_SHOW, REMIND_WHEEL_POSITIONS, ROULETTE_COLOR, ROULETTE_SLOW_DOWN_SWITCHES, ROULETTE_SWITCH_SECONDS, SECTION_COLORS, SECTION_COLORS_NAME(), SHOW_EASY_FLAG, SHOW_PORTAL, SHOW_RANDOM, SHOW_ROULETTE, SONG_REAL_EXTRA_COLOR, SONGMAN, SORT_MENU_COLOR, SORT_ORDERS, SongManager::SortSongs(), split(), THEME, and USE_SECTIONS_WITH_PREFERRED_GROUP.
Referenced by ScreenNetSelectMusic::Init(), and ScreenSelectMusic::Init().
MakeItem()
MusicWheelItem * MusicWheel::MakeItem () override protected virtual
Implements WheelBase.
NextSort()
bool MusicWheel::NextSort ()
References ChangeSort(), FOREACH_LUATABLEI, GAMESTATE, LuaManager::Get(), L, LUA, GameState::m_SortOrder, ThemeMetric< T >::PushSelf(), LuaManager::Release(), SORT_MODE_MENU, SORT_ORDERS, and wrap().
Referenced by ScreenSelectMusic::DetectCodes(), and ScreenSelectMusic::Input().
PlayerJoined()
void MusicWheel::PlayerJoined ()
References FOREACH_ENUM, INVALID, WheelBase::m_sExpandedSectionName, m_WheelItemDatasStatus, and SetOpenSection().
Referenced by ScreenSelectMusic::HandleMessage().
PushSelf()
void MusicWheel::PushSelf (lua_State * L) override virtual
Reimplemented from ActorFrame.
Referenced by LunaScreenNetSelectMusic::GetMusicWheel(), and LunaScreenSelectMusic::GetMusicWheel().
readyWheelItemsData()
void MusicWheel::readyWheelItemsData (SortOrder so, bool searching, RString findme) protected
References BuildWheelItemDatas(), FilterWheelItemDatas(), RageTimer::GetTimeSinceStart(), INVALID, LOG, m__UnFilteredWheelItemDatas, m__WheelItemDatas, m_WheelItemDatasStatus, RageLog::Trace(), and VALID.
Referenced by getWheelItemsData(), and ReloadSongList().
ReloadSongList()
void MusicWheel::ReloadSongList (bool searching, RString findme) virtual
References ChangeMusic(), f, FOREACH_ENUM, GAMESTATE, Song::GetDisplayMainTitle(), GetSelectedSection(), groupnamesearchmatch, hashList, INVALID, lastvalidsearch, WheelBase::m_iSelection, GameState::m_pCurSong, WheelBase::m_sExpandedSectionName, GameState::m_SortOrder, m_WheelItemDatasStatus, ScreenManager::PostMessageToTopScreen(), prevSongTitle, readyWheelItemsData(), WheelBase::RebuildWheelItems(), SCREENMAN, SelectSection(), SelectSongAfterSearch(), and SetOpenSection().
Referenced by ScreenNetSelectMusic::DifferentialReload(), ScreenSelectMusic::DifferentialReload(), LunaMusicWheel::FilterByStepKeys(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), LunaMusicWheel::ReloadSongList(), and LunaMusicWheel::SongSearch().
SearchGroupNames()
bool MusicWheel::SearchGroupNames (RString & findme) protected
References SongManager::GetSongGroupNames(), groupnamesearchmatch, StdString::CStdStr< CT >::MakeLower(), and SONGMAN.
Referenced by FilterBySearch().
Select()
bool MusicWheel::Select () override virtual
Reimplemented from WheelBase.
References GameCommand::ApplyToAllPlayers(), ChangeSort(), f, GAMESTATE, GetCurWheelItemData(), LOG, WheelBase::m_CurWheelItemData, WheelBase::m_fLockedWheelVelocity, WheelBase::m_fPositionOffsetFromSelection, WheelBase::m_fTimeLeftInState, WheelBase::m_iSelection, WheelBase::m_iSwitchesLeftInSpinDown, WheelBase::m_Moving, MusicWheelItemData::m_pAction, GameState::m_PreferredSortOrder, m_sLastModeMenuItem, GameCommand::m_sName, WheelBase::m_WheelState, max(), ScreenManager::PlayStartSound(), ScreenManager::PostMessageToTopScreen(), RandomInt(), ROULETTE_SLOW_DOWN_SWITCHES, SCREENMAN, WheelBase::Select(), STATE_FLYING_OFF_BEFORE_NEXT_SORT, STATE_LOCKED, STATE_RANDOM_SPINNING, STATE_ROULETTE_SLOWING_DOWN, STATE_ROULETTE_SPINNING, RageLog::Trace(), WheelItemDataType_Custom, WheelItemDataType_Random, WheelItemDataType_Roulette, and WheelItemDataType_Sort.
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), ScreenNetSelectMusic::SelectCurrent(), and ScreenSelectMusic::SelectCurrent().
SelectModeMenuItem()
bool MusicWheel::SelectModeMenuItem () protected
References ASSERT, GAMESTATE, GetCurWheelItemData(), getWheelItemsData(), WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, MusicWheelItemData::m_pAction, m_sLastModeMenuItem, GameCommand::m_sName, GameState::m_SortOrder, SetOpenSection(), and SORT_MODE_MENU.
Referenced by UpdateSwitch().
SelectSection()
bool MusicWheel::SelectSection (const RString & SectionName)
References WheelBase::m_CurWheelItemData, and WheelBase::m_iSelection.
Referenced by ScreenSelectMusic::DetectCodes(), ScreenSelectMusic::Input(), ReloadSongList(), and SelectSongAfterSearch().
SelectSong()
bool MusicWheel::SelectSong (const Song * p)
References ChangeMusic(), GAMESTATE, GetCurWheelItemData(), WheelBase::GetExpandedSectionName(), SongManager::GetPlaylists(), getWheelItemsData(), WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, MusicWheelItemData::m_pSong, GameState::m_SortOrder, SetOpenSection(), and SONGMAN.
Referenced by ScreenNetSelectMusic::HandleScreenMessage(), LunaMusicWheel::SelectSong(), SelectSongOrCourse(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
SelectSongAfterSearch()
void MusicWheel::SelectSongAfterSearch () private
References ChangeMusic(), GAMESTATE, getWheelItemsData(), GameState::m_SortOrder, SelectSection(), and SetOpenSection().
Referenced by ReloadSongList().
SelectSongOrCourse()
bool MusicWheel::SelectSongOrCourse () protected
References GAMESTATE, getWheelItemsData(), LOG, GameState::m_pCurSong, GameState::m_pPreferredSong, GameState::m_SortOrder, SelectSong(), and RageLog::Trace().
Referenced by BeginScreen(), and UpdateSwitch().
SetHashList()
void MusicWheel::SetHashList (const vector< string > & newHashList)
References hashList.
Referenced by LunaMusicWheel::FilterByStepKeys().
SetOpenSection()
void MusicWheel::SetOpenSection (const RString & group) override virtual
Reimplemented from WheelBase.
References CommonMetrics::AUTO_SET_STYLE, GAMEMAN, GAMESTATE, GameManager::GetCompatibleStyles(), GetCurWheelItemData(), GameState::GetNumPlayersEnabled(), SongManager::GetNumSongGroups(), SongManager::GetSongGroupByIndex(), getWheelItemsData(), HIDE_ACTIVE_SECTION_TITLE, HIDE_INACTIVE_SECTIONS, Song::IsTutorial(), WheelBase::m_CurWheelItemData, WheelBase::m_iSelection, GameState::m_pCurGame, GameState::m_PlayMode, MusicWheelItemData::m_pSong, WheelBase::m_sExpandedSectionName, GameState::m_SortOrder, WheelItemBaseData::m_sText, WheelItemBaseData::m_Type, m_viWheelPositions, PLAY_MODE_REGULAR, WheelBase::RebuildWheelItems(), REMIND_WHEEL_POSITIONS, GameState::sExpandedSectionName, SONGMAN, WheelItemDataType_Course, WheelItemDataType_Section, and WheelItemDataType_Song.
Referenced by BeginScreen(), ScreenSelectMusic::DetectCodes(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::Input(), PlayerJoined(), ReloadSongList(), SelectModeMenuItem(), SelectSong(), SelectSongAfterSearch(), and UpdateSwitch().
UpdateSwitch()
void MusicWheel::UpdateSwitch () override protected virtual
Reimplemented from WheelBase.
References ASSERT, MessageManager::Broadcast(), ChangeMusic(), Difficulty_Invalid, f, FAIL_M, FOREACH_PlayerNumber, GAMESTATE, GetCurWheelItemData(), SongUtil::GetSectionNameFromSongAndSort(), SongUtil::GetStepsTypeAndDifficultyFromSortOrder(), GameState::IsPlayerEnabled(), LOG, WheelBase::m_fLockedWheelVelocity, WheelBase::m_fTimeLeftInState, WheelBase::m_iSelection, WheelBase::m_iSwitchesLeftInSpinDown, WheelBase::m_Moving, GameState::m_PreferredDifficulty, MusicWheelItemData::m_pSong, GameState::m_SortOrder, WheelBase::m_WheelState, MESSAGEMAN, ScreenManager::PlayStartSound(), ScreenManager::PostMessageToTopScreen(), randomf(), WheelBase::RebuildWheelItems(), SCREENMAN, SelectModeMenuItem(), SelectSongOrCourse(), SetOpenSection(), SORT_MODE_MENU, ssprintf(), STATE_FLYING_OFF_BEFORE_NEXT_SORT, STATE_FLYING_ON_AFTER_NEXT_SORT, STATE_LOCKED, STATE_RANDOM_SPINNING, STATE_ROULETTE_SLOWING_DOWN, STATE_ROULETTE_SPINNING, STATE_SELECTING, RageLog::Trace(), and WheelBase::TweenOnScreenForSort().
WheelItemIsVisible()
bool MusicWheel::WheelItemIsVisible (int n) protected
Friends And Related Function Documentation
CompareSongPointerArrayBySectionName
friend struct CompareSongPointerArrayBySectionName friend
Member Data Documentation
CHOICE
ThemeMetricMap<RString> MusicWheel::CHOICE protected
Referenced by BuildWheelItemDatas(), and Load().
CUSTOM_CHOICE_COLORS
ThemeMetricMap<RageColor> MusicWheel::CUSTOM_CHOICE_COLORS protected
Referenced by Load().
CUSTOM_CHOICES
ThemeMetricMap<RString> MusicWheel::CUSTOM_CHOICES protected
Referenced by Load().
CUSTOM_WHEEL_ITEM_NAMES
ThemeMetric<RString> MusicWheel::CUSTOM_WHEEL_ITEM_NAMES protected
Referenced by Load().
EMPTY_COLOR
ThemeMetric<RageColor> MusicWheel::EMPTY_COLOR protected
Referenced by FilterWheelItemDatas(), and Load().
groupnamesearchmatch
RString MusicWheel::groupnamesearchmatch protected
Referenced by FilterBySearch(), ReloadSongList(), and SearchGroupNames().
hashList
vector<string> MusicWheel::hashList protected
Referenced by BuildWheelItemDatas(), FilterByStepKeys(), ReloadSongList(), and SetHashList().
HIDE_ACTIVE_SECTION_TITLE
ThemeMetric<bool> MusicWheel::HIDE_ACTIVE_SECTION_TITLE protected
Referenced by Load(), and SetOpenSection().
HIDE_INACTIVE_SECTIONS
ThemeMetric<bool> MusicWheel::HIDE_INACTIVE_SECTIONS protected
Referenced by BeginScreen(), ChangeMusic(), JumpToNextGroup(), JumpToPrevGroup(), Load(), and SetOpenSection().
lastvalidsearch
RString MusicWheel::lastvalidsearch protected
Referenced by FilterBySearch(), and ReloadSongList().
m__UnFilteredWheelItemDatas
vector<MusicWheelItemData*> MusicWheel::m__UnFilteredWheelItemDatas[NUM_SortOrder] private
Referenced by readyWheelItemsData(), and ~MusicWheel().
m__WheelItemDatas
vector<MusicWheelItemData*> MusicWheel::m__WheelItemDatas[NUM_SortOrder] private
Referenced by getWheelItemsData(), and readyWheelItemsData().
m_sLastModeMenuItem
RString MusicWheel::m_sLastModeMenuItem protected
Referenced by BeginScreen(), Select(), and SelectModeMenuItem().
m_SortOrder
SortOrder MusicWheel::m_SortOrder protected
Referenced by GetSortOrder().
m_soundChangeSort
RageSound MusicWheel::m_soundChangeSort protected
Referenced by ChangeSort(), and Load().
m_viWheelPositions
vector<int> MusicWheel::m_viWheelPositions protected
Referenced by BeginScreen(), ChangeMusic(), and SetOpenSection().
m_WheelItemDatasStatus
enum { ... } MusicWheel::m_WheelItemDatasStatus[NUM_SortOrder]
Referenced by BeginScreen(), Load(), PlayerJoined(), readyWheelItemsData(), and ReloadSongList().
MODE_MENU_CHOICE_NAMES
ThemeMetric<RString> MusicWheel::MODE_MENU_CHOICE_NAMES protected
Referenced by BuildWheelItemDatas(), and Load().
MOST_PLAYED_SONGS_TO_SHOW
ThemeMetric<int> MusicWheel::MOST_PLAYED_SONGS_TO_SHOW protected
Referenced by BuildWheelItemDatas(), and Load().
NUM_SECTION_COLORS
ThemeMetric<int> MusicWheel::NUM_SECTION_COLORS protected
Referenced by BuildWheelItemDatas(), and Load().
PORTAL_COLOR
ThemeMetric<RageColor> MusicWheel::PORTAL_COLOR protected
Referenced by Load().
prevSongTitle
RString MusicWheel::prevSongTitle private
Referenced by ReloadSongList().
RANDOM_COLOR
ThemeMetric<RageColor> MusicWheel::RANDOM_COLOR protected
Referenced by Load().
RANDOM_PICKS_LOCKED_SONGS
ThemeMetric<bool> MusicWheel::RANDOM_PICKS_LOCKED_SONGS protected
Referenced by Load().
RECENT_SONGS_TO_SHOW
ThemeMetric<int> MusicWheel::RECENT_SONGS_TO_SHOW protected
Referenced by BuildWheelItemDatas(), and Load().
REMIND_WHEEL_POSITIONS
ThemeMetric<bool> MusicWheel::REMIND_WHEEL_POSITIONS protected
Referenced by BeginScreen(), ChangeMusic(), Load(), and SetOpenSection().
ROULETTE_COLOR
ThemeMetric<RageColor> MusicWheel::ROULETTE_COLOR protected
Referenced by Load().
ROULETTE_SLOW_DOWN_SWITCHES
ThemeMetric<int> MusicWheel::ROULETTE_SLOW_DOWN_SWITCHES protected
Referenced by Load(), and Select().
ROULETTE_SWITCH_SECONDS
ThemeMetric<float> MusicWheel::ROULETTE_SWITCH_SECONDS protected
Referenced by Load().
SECTION_COLORS
ThemeMetric1D<RageColor> MusicWheel::SECTION_COLORS protected
Referenced by BuildWheelItemDatas(), and Load().
SHOW_EASY_FLAG
ThemeMetric<bool> MusicWheel::SHOW_EASY_FLAG protected
Referenced by BuildWheelItemDatas(), and Load().
SHOW_PORTAL
ThemeMetric<bool> MusicWheel::SHOW_PORTAL protected
Referenced by Load().
SHOW_RANDOM
ThemeMetric<bool> MusicWheel::SHOW_RANDOM protected
Referenced by Load().
SHOW_ROULETTE
ThemeMetric<bool> MusicWheel::SHOW_ROULETTE protected
Referenced by Load().
SONG_REAL_EXTRA_COLOR
ThemeMetric<RageColor> MusicWheel::SONG_REAL_EXTRA_COLOR protected
Referenced by Load().
SORT_MENU_COLOR
ThemeMetric<RageColor> MusicWheel::SORT_MENU_COLOR protected
Referenced by BuildWheelItemDatas(), and Load().
SORT_ORDERS
ThemeMetric<LuaReference> MusicWheel::SORT_ORDERS protected
Referenced by Load(), and NextSort().
USE_SECTIONS_WITH_PREFERRED_GROUP
ThemeMetric<bool> MusicWheel::USE_SECTIONS_WITH_PREFERRED_GROUP protected
Referenced by BuildWheelItemDatas(), GetSongList(), and Load().
The documentation for this class was generated from the following files:
MusicWheel.h
MusicWheel.cpp