Etterna: RageMutex Class Reference
RageMutex Class Reference
#include <RageThreads.h>
Public Member Functions
RString GetName () const
void SetName (const RString &s)
virtual void Lock ()
virtual bool TryLock ()
virtual void Unlock ()
virtual bool IsLockedByThisThread () const
RageMutex (const RString &name)
virtual ~RageMutex ()
Protected Member Functions
void MarkLockedMutex ()
Protected Attributes
MutexImpl * m_pMutex
RString m_sName
int m_UniqueID
uint64_t m_LockedBy
int m_LockCnt
Private Member Functions
RageMutex & operator= (const RageMutex &rhs)
RageMutex (const RageMutex &rhs)
Constructor & Destructor Documentation
RageMutex() [1/2]
RageMutex::RageMutex (const RString & name)
~RageMutex()
RageMutex::~RageMutex () virtual
References m_pMutex.
RageMutex() [2/2]
RageMutex::RageMutex (const RageMutex & rhs) private
Member Function Documentation
GetName()
RString RageMutex::GetName () const inline
References m_sName.
Referenced by Lock().
IsLockedByThisThread()
bool RageMutex::IsLockedByThisThread () const virtual
References m_LockedBy.
Referenced by FilenameDB::AddFile(), RageEvent::Broadcast(), FilenameDB::DelFileSet(), LuaManager::Get(), FilenameDB::GetFile(), FilenameDB::GetFileHash(), FilenameDB::GetFilePriv(), FilenameDB::GetFilesEqualTo(), FilenameDB::GetFileSet(), FilenameDB::GetFileSize(), FilenameDB::GetFilesMatching(), FilenameDB::GetFileType(), RageEvent::Signal(), RageSound::StartPlaying(), RageSound::StopPlaying(), RageEvent::Wait(), and LuaManager::YieldLua().
Lock()
void RageMutex::Lock () virtual
References FAIL_M, GetName(), ThreadSlot::GetThreadName(), GetThreadSlotFromID(), GetThreadSlotsLock(), Lock(), ThreadSlot::m_iID, m_LockCnt, m_LockedBy, m_pMutex, ssprintf(), and Unlock().
Referenced by AddFilesystemDriver(), RageFileObjMemFile::AddReference(), RageSoundReader_ThreadedBuffer::BufferingThread(), ThreadedFileWorker::Close(), RageSound::CommitPlayingPosition(), RageSound::DeleteSelfWhenFinishedPlaying(), RageSoundReader_ThreadedBuffer::DisableBuffering(), RageWorkerThread::DoRequest(), RageSoundReader_ThreadedBuffer::EnableBuffering(), RageSoundReader_ThreadedBuffer::FillBlock(), PolyphaseFilterCache::FindNearestPolyphaseFilter(), GameSoundManager::Flush(), FilenameDB::FlushDirCache(), LuaManager::Get(), RageSound::GetDataToPlay(), RageFileManager::GetFileDriver(), FilenameDB::GetFileSet(), RageSoundReader_ThreadedBuffer::GetNextSourceFrame(), RageSoundReader_ThreadedBuffer::GetStreamToSourceRatio(), ThreadedFileWorker::HandleRequest(), CachedObjectHelpers::Lock(), Lock(), LockMutex::LockMutex(), PolyphaseFilterCache::MakePolyphaseFilter(), MusicThread_start(), RageFileDriverZip::Open(), GameSoundManager::PlayMusic(), GameSoundManager::PlayOnce(), GameSoundManager::PlayOnceFromAnnouncer(), GameSoundManager::PlayOnceFromDir(), RageFileObjMem::PutString(), RageSoundReader_ThreadedBuffer::Read(), ReferenceAllDrivers(), RageFileManager::ReleaseFileDriver(), RageFileObjMemFile::ReleaseReference(), ConcurrentRenderer::RenderThread(), FilenameDB::ResolvePath(), RageSoundManager::SetMixVolume(), RageWorkerThread::SetTimeout(), RageFileDriverTimeout::SetTimeout(), RageSoundManager::SetVolumeOfNonCriticalSounds(), RageSound::SoundIsFinishedPlaying(), ConcurrentRenderer::Start(), RageSoundDriver::StartMixing(), StartMusic(), StartQueuedSounds(), ConcurrentRenderer::Stop(), RageSoundDriver::StopMixing(), RageWorkerThread::StopThread(), ThreadedFileWorker::ThreadedFileWorker(), RageFileManager::Unmount(), UnreferenceAllDrivers(), LuaManager::UnyieldLua(), GameSoundManager::Update(), RageSoundManager::Update(), RageSoundDriver::Update(), RageWorkerThread::WaitForOneHeartbeat(), RageSoundReader_ThreadedBuffer::WaitUntilFrames(), RageWorkerThread::WorkerMain(), RageFileObjMem::WriteInternal(), GameSoundManager::~GameSoundManager(), RageSoundReader_ThreadedBuffer::~RageSoundReader_ThreadedBuffer(), and ThreadedFileWorker::~ThreadedFileWorker().
MarkLockedMutex()
void RageMutex::MarkLockedMutex () protected
operator=()
RageMutex& RageMutex::operator= (const RageMutex & rhs) private
SetName()
void RageMutex::SetName (const RString & s) inline
References m_sName.
Referenced by RageFileDriverZip::Load(), and RageSound::Load().
TryLock()
bool RageMutex::TryLock () virtual
References m_LockCnt, m_LockedBy, and m_pMutex.
Unlock()
void RageMutex::Unlock () virtual
References m_LockCnt, m_LockedBy, and m_pMutex.
Referenced by FilenameDB::AddFile(), AddFilesystemDriver(), RageFileObjMemFile::AddReference(), RageSoundReader_ThreadedBuffer::BufferingThread(), DirectFilenameDB::CacheFile(), ThreadedFileWorker::Close(), RageSound::CommitPlayingPosition(), RageSound::DeleteSelfWhenFinishedPlaying(), FilenameDB::DelFile(), RageSoundReader_ThreadedBuffer::DisableBuffering(), RageWorkerThread::DoRequest(), RageSoundReader_ThreadedBuffer::EnableBuffering(), RageSoundReader_ThreadedBuffer::FillBlock(), PolyphaseFilterCache::FindNearestPolyphaseFilter(), GameSoundManager::Flush(), FilenameDB::FlushDirCache(), RageSound::GetDataToPlay(), RageFileManager::GetFileDriver(), FilenameDB::GetFileHash(), FilenameDB::GetFilePriv(), FilenameDB::GetFilesEqualTo(), FilenameDB::GetFileSet(), FilenameDB::GetFileSetCopy(), FilenameDB::GetFileSize(), FilenameDB::GetFilesMatching(), FilenameDB::GetFileType(), RageSoundReader_ThreadedBuffer::GetNextSourceFrame(), RageSoundReader_ThreadedBuffer::GetStreamToSourceRatio(), ThreadedFileWorker::HandleRequest(), Lock(), PolyphaseFilterCache::MakePolyphaseFilter(), MusicThread_start(), RageFileDriverZip::Open(), GameSoundManager::PlayMusic(), GameSoundManager::PlayOnce(), GameSoundManager::PlayOnceFromAnnouncer(), GameSoundManager::PlayOnceFromDir(), RageFileObjMem::PutString(), RageSoundReader_ThreadedBuffer::Read(), ReferenceAllDrivers(), LuaManager::Release(), RageFileManager::ReleaseFileDriver(), RageFileObjMemFile::ReleaseReference(), ConcurrentRenderer::RenderThread(), FilenameDB::ResolvePath(), RageSoundManager::SetMixVolume(), RageWorkerThread::SetTimeout(), RageFileDriverTimeout::SetTimeout(), RageSoundManager::SetVolumeOfNonCriticalSounds(), RageSound::SoundIsFinishedPlaying(), ConcurrentRenderer::Start(), RageSoundDriver::StartMixing(), StartMusic(), StartQueuedSounds(), ConcurrentRenderer::Stop(), RageSoundDriver::StopMixing(), RageWorkerThread::StopThread(), ThreadedFileWorker::ThreadedFileWorker(), CachedObjectHelpers::Unlock(), LockMutex::Unlock(), RageFileManager::Unmount(), UnreferenceAllDrivers(), GameSoundManager::Update(), RageSoundManager::Update(), RageSoundDriver::Update(), RageWorkerThread::WaitForOneHeartbeat(), RageSoundReader_ThreadedBuffer::WaitUntilFrames(), RageWorkerThread::WorkerMain(), RageFileObjMem::WriteInternal(), LuaManager::YieldLua(), GameSoundManager::~GameSoundManager(), LockMutex::~LockMutex(), RageSoundReader_ThreadedBuffer::~RageSoundReader_ThreadedBuffer(), and ThreadedFileWorker::~ThreadedFileWorker().
Member Data Documentation
m_LockCnt
int RageMutex::m_LockCnt protected
Referenced by RageEvent::Broadcast(), Lock(), RageEvent::Signal(), TryLock(), Unlock(), and RageEvent::Wait().
m_LockedBy
uint64_t RageMutex::m_LockedBy protected
Referenced by IsLockedByThisThread(), Lock(), TryLock(), Unlock(), and RageEvent::Wait().
m_pMutex
MutexImpl* RageMutex::m_pMutex protected
Referenced by Lock(), TryLock(), Unlock(), and ~RageMutex().
m_sName
RString RageMutex::m_sName protected
Referenced by GetName(), and SetName().
m_UniqueID
int RageMutex::m_UniqueID protected
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp