Etterna: LunaSongOptions Class Reference
LunaSongOptions Class Reference
Allow Lua to have access to SongOptions.
Public Member Functions
ENUM_INTERFACE (AutosyncSetting, AutosyncType, AutosyncType)
BOOL_INTERFACE (AssistClap, AssistClap)
BOOL_INTERFACE (AssistMetronome, AssistMetronome)
BOOL_INTERFACE (StaticBackground, StaticBackground)
BOOL_INTERFACE (RandomBGOnly, RandomBGOnly)
BOOL_INTERFACE (SaveScore, SaveScore)
BOOL_INTERFACE (SaveReplay, SaveReplay)
LunaSongOptions ()
Public Member Functions inherited from Luna< SongOptions >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int MusicRate (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< SongOptions >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< SongOptions >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< SongOptions >
using T = SongOptions
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< SongOptions >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to SongOptions.
Constructor & Destructor Documentation
LunaSongOptions()
LunaSongOptions::LunaSongOptions () inline
References ADD_METHOD, and MusicRate().
Member Function Documentation
BOOL_INTERFACE() [1/6]
LunaSongOptions::BOOL_INTERFACE (AssistClap , AssistClap)
BOOL_INTERFACE() [2/6]
LunaSongOptions::BOOL_INTERFACE (AssistMetronome , AssistMetronome)
BOOL_INTERFACE() [3/6]
LunaSongOptions::BOOL_INTERFACE (StaticBackground , StaticBackground)
BOOL_INTERFACE() [4/6]
LunaSongOptions::BOOL_INTERFACE (RandomBGOnly , RandomBGOnly)
BOOL_INTERFACE() [5/6]
LunaSongOptions::BOOL_INTERFACE (SaveScore , SaveScore)
BOOL_INTERFACE() [6/6]
LunaSongOptions::BOOL_INTERFACE (SaveReplay , SaveReplay)
ENUM_INTERFACE()
LunaSongOptions::ENUM_INTERFACE (AutosyncSetting , AutosyncType , AutosyncType)
MusicRate()
static int LunaSongOptions::MusicRate (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), f, FArg, FArgGTEZero(), SongOptions::m_fMusicRate, SongOptions::m_SpeedfMusicRate, MESSAGEMAN, and OPTIONAL_RETURN_SELF.
Referenced by LunaSongOptions().
The documentation for this class was generated from the following file:
SongOptions.cpp