Etterna: SongID Class Reference
SongID Class Reference
#include <SongUtil.h>
Public Member Functions
SongID ()
Set up the SongID with default values.
void Unset ()
void FromSong (const Song *p)
Song * ToSong () const
bool operator< (const SongID &other) const
bool operator== (const SongID &other) const
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
void LoadFromString (const char *dir)
void FromString (RString _sDir)
RString ToString () const
bool IsValid () const
Private Attributes
RString sDir
CachedObjectPointer< Song > m_Cache
Constructor & Destructor Documentation
SongID()
SongID::SongID () inline
Set up the SongID with default values.
This used to call Unset() to do the same thing.
References CachedObjectPointer< T >::Unset().
Member Function Documentation
CreateNode()
XNode * SongID::CreateNode () const
References XNode::AppendAttr(), and sDir.
Referenced by XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), ScreenGameplay::SaveReplay(), and XMLProfile::SaveSongScoresCreateNode().
FromSong()
void SongID::FromSong (const Song * p)
References Song::GetSongDir(), StdString::CStdStr< CT >::Left(), m_Cache, sDir, and CachedObjectPointer< T >::Unset().
Referenced by StageStats::FinalizeScores(), Profile::GetGrades(), Profile::GetSongLastPlayedDateTime(), Profile::GetSongNumTimesPlayed(), Profile::GetStepsHighScoreList(), ScreenEvaluation::HandleMenuStart(), Profile::ImportScoresToEtterna(), GameState::SaveCurrentSettingsToProfile(), SongManager::SaveEnabledSongsToPref(), ScreenGameplay::SaveReplay(), StepsID::ToSteps(), and Unset().
FromString()
void SongID::FromString (RString _sDir) inline
Referenced by GameState::GetDefaultSong(), and SongManager::LoadEnabledSongsFromPref().
IsValid()
bool SongID::IsValid () const
References ToSong().
LoadFromNode()
void SongID::LoadFromNode (const XNode * pNode)
References ASSERT, XNode::GetAttrValue(), XNode::GetName(), m_Cache, sDir, and CachedObjectPointer< T >::Unset().
Referenced by XMLProfile::LoadEttGeneralDataFromNode(), XMLProfile::LoadGeneralDataFromNode(), and XMLProfile::LoadSongScoresFromNode().
LoadFromString()
void SongID::LoadFromString (const char * dir)
References m_Cache, sDir, and CachedObjectPointer< T >::Unset().
Referenced by DBProfile::LoadGeneralData().
operator<()
bool SongID::operator< (const SongID & other) const inline
References sDir.
operator==()
bool SongID::operator== (const SongID & other) const inline
References sDir.
ToSong()
Song * SongID::ToSong () const
References CachedObjectPointer< T >::Get(), SongManager::GetSongFromDir(), StdString::CStdStr< CT >::Left(), m_Cache, sDir, CachedObjectPointer< T >::Set(), and SONGMAN.
Referenced by GameState::GetDefaultSong(), LunaProfile::GetLastPlayedSong(), IsValid(), GameState::LoadCurrentSettingsFromProfile(), and SongManager::LoadEnabledSongsFromPref().
ToString()
RString SongID::ToString () const
References sDir.
Referenced by Profile::ImportScoresToEtterna(), SongManager::SaveEnabledSongsToPref(), and DBProfile::SaveGeneralData().
Unset()
void SongID::Unset () inline
References FromSong().
Referenced by Profile::InitGeneralData(), and Profile::Profile().
Member Data Documentation
m_Cache
CachedObjectPointer<Song> SongID::m_Cache mutable private
Referenced by FromSong(), LoadFromNode(), LoadFromString(), and ToSong().
sDir
RString SongID::sDir private
Referenced by CreateNode(), FromSong(), LoadFromNode(), LoadFromString(), operator<(), operator==(), ToSong(), and ToString().
The documentation for this class was generated from the following files:
SongUtil.h
SongUtil.cpp