Etterna: LockMutex Class Reference
LockMutex Class Reference
Lock a mutex on construction, unlock it on destruction.
#include <RageThreads.h>
Public Member Functions
LockMutex (RageMutex &mut, const char *file, int line)
LockMutex (RageMutex &mut)
~LockMutex ()
LockMutex (LockMutex &cpy)
void Unlock ()
Unlock the mutex (before this would normally go out of scope).
Private Member Functions
LockMutex & operator= (const LockMutex &rhs)=delete
Private Attributes
RageMutex & mutex
const char * file
int line
float locked_at
bool locked
Detailed Description
Lock a mutex on construction, unlock it on destruction.
Helps for functions with more than one return path.
Constructor & Destructor Documentation
LockMutex() [1/3]
LockMutex::LockMutex (RageMutex & mut, const char * file, int line)
References RageMutex::Lock(), and locked.
LockMutex() [2/3]
LockMutex::LockMutex (RageMutex & mut) inline
References RageMutex::Lock().
~LockMutex()
LockMutex::~LockMutex ()
References locked, and RageMutex::Unlock().
LockMutex() [3/3]
LockMutex::LockMutex (LockMutex & cpy) inline
References RageMutex::Lock().
Member Function Documentation
operator=()
LockMutex& LockMutex::operator= (const LockMutex & rhs) private delete
Unlock()
void LockMutex::Unlock ()
Unlock the mutex (before this would normally go out of scope).
This can only be called once.
References ASSERT, f, file, RageTimer::GetTimeSinceStart(), line, locked, locked_at, LOG, RageLog::Trace(), and RageMutex::Unlock().
Referenced by StartMusic(), and LowLevelWindow_MacOSX::Update().
Member Data Documentation
file
const char* LockMutex::file private
Referenced by Unlock().
line
int LockMutex::line private
Referenced by Unlock().
locked
bool LockMutex::locked private
Referenced by LockMutex(), Unlock(), and ~LockMutex().
locked_at
float LockMutex::locked_at private
Referenced by Unlock().
mutex
RageMutex& LockMutex::mutex private
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp