Etterna: StepMania.h File Reference
StepMania.h File Reference
#include "global.h"
Namespaces
StepMania
Utility functions for controlling the whole game.
Functions
int sm_main (int argc, char *argv[])
void StepMania::ApplyGraphicOptions ()
void StepMania::ResetPreferences ()
void StepMania::ResetGame ()
RString StepMania::GetInitialScreen ()
RString StepMania::GetSelectMusicScreen ()
void StepMania::InitializeCurrentGame (const Game *g)
RString StepMania::SaveScreenshot (const RString &Dir, bool SaveCompressed, bool MakeSignature, const RString &NamePrefix, const RString &NameSuffix)
void StepMania::InsertCoin (int iNum=1, bool bCountInBookkeeping=true)
void StepMania::InsertCredit ()
void StepMania::ClearCredits ()
void StepMania::GetPreferredVideoModeParams (VideoModeParams &paramsOut)
bool StepMania::GetHighResolutionTextures ()
Function Documentation
sm_main()
int sm_main (int argc, char * argv[])
References AdjustForChangedSystemCapabilities(), ANNOUNCER, ApplyLogPreferences(), CHARMAN, InputMapper::CheckForChangedInputDevicesAndRemap(), ArchHooks::CheckForMultipleInstances(), COULDNT_OPEN_LOADING_WINDOW, ArchHooks::Create(), LoadingWindow::Create(), CRYPTMAN, NetworkSyncManager::DisplayStartupStatus(), DLMAN, DoesFileExist(), ArchHooks::DumpDebugInfo(), FAIL_M, FILEMAN, FILTERMAN, SongCacheIndex::FinishTransaction(), FONT, g_bAllowMultipleInstances, g_RandomNumberGenerator, GAMEMAN, GAMESTATE, CryptManager::GenerateGlobalKeys(), Preference< T >::Get(), GetActualGraphicOptionsString(), GetCommandlineArgument(), GameState::GetCurrentGame(), NetworkSyncManager::GetCurrentSMBuild(), StepMania::GetInitialScreen(), ThemeManager::GetPathG(), RageThread::GetSupportsTLS(), LocalizedString::GetValue(), ArchHooks::GoToURL(), CommandLineActions::Handle(), HandleException(), HOOKS, IMAGECACHE, RageLog::Info(), ArchHooks::Init(), Init(), ProfileManager::Init(), RageSoundManager::Init(), SongManager::InitAll(), ActorUtil::InitFileTypeLists(), StepMania::InitializeCurrentGame(), INPUTFILTER, INPUTMAN, INPUTMAPPER, INPUTQUEUE, RageSurfaceUtils::LoadFile(), LOG, LUA, GameState::m_bDopefish, PrefsManager::m_bSignProfileData, PrefsManager::m_iSoundWriteAhead, PrefsManager::m_sAdditionalFolders, PrefsManager::m_sAdditionalSongFolders, MEMCARDMAN, MESSAGEMAN, RageFileManager::Mount(), RageFileManager::MountInitialFilesystems(), RageFileManager::MountUserFilesystems(), NOTESKIN, NSMAN, PREFSMAN, SongManager::PreloadSongImages(), PRODUCT_ID, PROFILEMAN, PrefsManager::ReadPrefsFromDisk(), CodeDetector::RefreshCacheItems(), ArchHooks::RegisterWithLua(), StepMania::ResetGame(), GameLoop::RunGameLoop(), SAFE_DELETE, PrefsManager::SavePrefsToDisk(), SCOREMAN, SCREENMAN, seed_lua_prng(), RageException::SetCleanupHandler(), SetCommandlineArguments(), LoadingWindow::SetIcon(), RageSoundManager::SetMixVolume(), ScreenManager::SetNewScreen(), LoadingWindow::SetSplash(), ShutdownGame(), SM_DOWNLOAD_URL, SONGINDEX, SONGMAN, SOUND, SOUNDMAN, split(), StartDisplay(), SongCacheIndex::StartTransaction(), STATSMAN, StoreActualGraphicOptions(), SwitchToLastPlayedGame(), ScreenManager::SystemMessage(), THEME, ScreenManager::ThemeChanged(), RageException::Throw(), SongManager::UpdatePreferredSort(), ArchHooks::UserQuit(), version_num, and WriteLogHeader().
Referenced by main().