Etterna: AnimatedTexture Class Reference
AnimatedTexture Class Reference
#include <ModelTypes.h>
Classes
struct AnimatedTextureState
Public Member Functions
AnimatedTexture ()
~AnimatedTexture ()
void LoadBlank ()
void Load (const RString &sTexOrIniFile)
void Unload ()
void Update (float fDelta)
RageTexture * GetCurrentTexture ()
int GetNumStates () const
void SetState (int iNewState)
float GetAnimationLengthSeconds () const
void SetSecondsIntoAnimation (float fSeconds)
float GetSecondsIntoAnimation () const
RageVector2 GetTextureTranslate ()
bool NeedsNormals () const
Public Attributes
bool m_bSphereMapped
BlendMode m_BlendMode
Private Attributes
RageVector2 m_vTexOffset
RageVector2 m_vTexVelocity
int m_iCurState
float m_fSecsIntoFrame
vector< AnimatedTextureState > vFrames
Constructor & Destructor Documentation
AnimatedTexture()
AnimatedTexture::AnimatedTexture ()
References BLEND_NORMAL, m_BlendMode, m_bSphereMapped, m_fSecsIntoFrame, m_iCurState, m_vTexOffset, and m_vTexVelocity.
~AnimatedTexture()
AnimatedTexture::~AnimatedTexture ()
References Unload().
Member Function Documentation
GetAnimationLengthSeconds()
float AnimatedTexture::GetAnimationLengthSeconds () const
References FOREACH_CONST, and vFrames.
Referenced by GetTextureTranslate(), and SetSecondsIntoAnimation().
GetCurrentTexture()
RageTexture * AnimatedTexture::GetCurrentTexture ()
References ASSERT, m_iCurState, and vFrames.
Referenced by Model::DrawPrimitives().
GetNumStates()
int AnimatedTexture::GetNumStates () const
References vFrames.
Referenced by SetState().
GetSecondsIntoAnimation()
float AnimatedTexture::GetSecondsIntoAnimation () const
References AnimatedTexture::AnimatedTextureState::fDelaySecs, m_fSecsIntoFrame, m_iCurState, and vFrames.
Referenced by GetTextureTranslate().
GetTextureTranslate()
RageVector2 AnimatedTexture::GetTextureTranslate ()
References ASSERT, GetAnimationLengthSeconds(), GetSecondsIntoAnimation(), m_iCurState, m_vTexOffset, m_vTexVelocity, and vFrames.
Referenced by Model::DrawPrimitives().
Load()
void AnimatedTexture::Load (const RString & sTexOrIniFile)
References ASSERT, RageTextureID::bHotPinkColorKey, BLEND_ADD, BLEND_NORMAL, RageTextureID::bMipMaps, RageTextureID::bStretch, StdString::CStdStr< CT >::CompareNoCase(), Dirname(), RageTextureID::filename, XNode::GetAttrValue(), XNode::GetChild(), IniFile::GetError(), GetExtension(), RageTextureManager::LoadTexture(), m_BlendMode, m_bSphereMapped, m_vTexOffset, m_vTexVelocity, IniFile::ReadFile(), ssprintf(), TEXTUREMAN, RageException::Throw(), vFrames, RageVector2::x, and RageVector2::y.
Referenced by Model::LoadMaterialsFromMilkshapeAscii().
LoadBlank()
void AnimatedTexture::LoadBlank ()
References vFrames.
Referenced by Model::LoadMaterialsFromMilkshapeAscii().
NeedsNormals()
bool AnimatedTexture::NeedsNormals () const inline
References m_bSphereMapped.
Referenced by msMaterial::NeedsNormals().
SetSecondsIntoAnimation()
void AnimatedTexture::SetSecondsIntoAnimation (float fSeconds)
References AnimatedTexture::AnimatedTextureState::fDelaySecs, GetAnimationLengthSeconds(), m_fSecsIntoFrame, m_iCurState, and vFrames.
SetState()
void AnimatedTexture::SetState (int iNewState)
References CLAMP(), GetNumStates(), and m_iCurState.
Unload()
void AnimatedTexture::Unload ()
References m_fSecsIntoFrame, m_iCurState, TEXTUREMAN, RageTextureManager::UnloadTexture(), and vFrames.
Referenced by ~AnimatedTexture().
Update()
void AnimatedTexture::Update (float fDelta)
References ASSERT, m_fSecsIntoFrame, m_iCurState, and vFrames.
Member Data Documentation
m_BlendMode
BlendMode AnimatedTexture::m_BlendMode
Referenced by AnimatedTexture(), and Load().
m_bSphereMapped
bool AnimatedTexture::m_bSphereMapped
Referenced by AnimatedTexture(), Model::DrawPrimitives(), Load(), and NeedsNormals().
m_fSecsIntoFrame
float AnimatedTexture::m_fSecsIntoFrame private
Referenced by AnimatedTexture(), GetSecondsIntoAnimation(), SetSecondsIntoAnimation(), Unload(), and Update().
m_iCurState
int AnimatedTexture::m_iCurState private
Referenced by AnimatedTexture(), GetCurrentTexture(), GetSecondsIntoAnimation(), GetTextureTranslate(), SetSecondsIntoAnimation(), SetState(), Unload(), and Update().
m_vTexOffset
RageVector2 AnimatedTexture::m_vTexOffset private
Referenced by AnimatedTexture(), GetTextureTranslate(), and Load().
m_vTexVelocity
RageVector2 AnimatedTexture::m_vTexVelocity private
Referenced by AnimatedTexture(), GetTextureTranslate(), and Load().
vFrames
vector<AnimatedTextureState> AnimatedTexture::vFrames private
Referenced by GetAnimationLengthSeconds(), GetCurrentTexture(), GetNumStates(), GetSecondsIntoAnimation(), GetTextureTranslate(), Load(), LoadBlank(), SetSecondsIntoAnimation(), Unload(), and Update().
The documentation for this class was generated from the following files:
ModelTypes.h
ModelTypes.cpp