Etterna: RageLog Class Reference
RageLog Class Reference
#include <RageLog.h>
Public Member Functions
RageLog ()
~RageLog ()
void Trace (const char *fmt,...) PRINTF(2
void void Warn (const char *fmt,...) PRINTF(2
void void void Info (const char *fmt,...) PRINTF(2
void void void void Time (const char *fmt,...) PRINTF(2
void void void void void UserLog (const RString &sType, const RString &sElement, const char *fmt,...) PRINTF(4
void void void void void void Flush ()
void MapLog (const RString &key, const char *fmt,...) PRINTF(3
void void UnmapLog (const RString &key)
void SetShowLogOutput (bool show)
void SetLogToDisk (bool b)
void SetInfoToDisk (bool b)
void SetUserLogToDisk (bool b)
void SetFlushing (bool b)
Static Public Member Functions
static const char * GetAdditionalLog ()
static const char * GetInfo ()
static const char * GetRecentLog (int n)
Private Member Functions
void Write (int, const RString &str)
void UpdateMappedLog ()
void AddToInfo (const RString &buf)
void AddToRecentLogs (const RString &buf)
Private Attributes
bool m_bLogToDisk { false }
bool m_bInfoToDisk { false }
bool m_bUserLogToDisk { false }
bool m_bFlush { false }
bool m_bShowLogOutput { false }
Constructor & Destructor Documentation
RageLog()
RageLog::RageLog ()
References RageFile::GetError(), RageFile::Open(), RageFile::STREAMED, TIME_PATH, and RageFile::WRITE.
~RageLog()
RageLog::~RageLog ()
References RageFile::Close(), Flush(), GetAdditionalLog(), Info(), SAFE_DELETE, SetShowLogOutput(), split(), and Trim().
Member Function Documentation
AddToInfo()
void RageLog::AddToInfo (const RString & buf) private
References min(), NEWLINE, staticlog, and staticlog_size.
Referenced by Write().
AddToRecentLogs()
void RageLog::AddToRecentLogs (const RString & buf) private
References backlog, backlog_cnt, BACKLOG_LINES, and backlog_start.
Referenced by Write().
Flush()
void RageLog::Flush ()
References RageFile::Flush().
Referenced by DebugLineFlushLog::DoAndLog(), RageException::Throw(), Write(), MovieTexture_DShow::~MovieTexture_DShow(), ~RageLog(), RageSoundDriver::~RageSoundDriver(), and RageSoundDriver_DSound_Software::~RageSoundDriver_DSound_Software().
GetAdditionalLog()
const char * RageLog::GetAdditionalLog () static
References g_AdditionalLogSize, g_AdditionalLogStr, and min().
Referenced by ~RageLog().
GetInfo()
const char * RageLog::GetInfo () static
References staticlog.
GetRecentLog()
const char * RageLog::GetRecentLog (int n) static
References backlog, backlog_cnt, BACKLOG_LINES, and backlog_start.
Info()
void RageLog::Info (const char * fmt, ...)
References vssprintf(), Write(), and WRITE_TO_INFO.
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), SongCacheIndex::CacheSong(), InputMapper::CheckForChangedInputDevicesAndRemap(), RageSoundDriver_OSS::CheckOSSVersion(), CheckPalettedTextures(), CheckReversePackedPixels(), CheckVideoDefaultSettings(), LoadingWindow::Create(), RageSoundDriver::Create(), ArchHooks_Unix::DumpDebugInfo(), ArchHooks_MacOSX::DumpDebugInfo(), DumpPixelFormat(), DSound::EnumCallback(), EnumDevicesCallback(), Alsa9Buf::GetHardwareID(), Alsa9Buf::GetSoundCardDebugInfo(), GetVideoCodecDebugInfo(), InputHandler_SextetStream::Impl::Impl(), RageDisplay_GLES2::Init(), RageSoundDriver_DSound_Software::Init(), RageSoundDriver_WaveOut::Init(), DSound::Init(), RageDisplay_Legacy::Init(), Alsa9Buf::Init(), InitHack(), InputHandler_DInput::InputHandler_DInput(), InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO(), InputHandler_Win32_Para::InputHandler_Win32_Para(), InputHandler_Win32_Pump::InputHandler_Win32_Pump(), LinuxInputManager::LinuxInputManager(), LowLevelWindow_X11::LogDebugInformation(), LowLevelWindow_X11::LowLevelWindow_X11(), EventDevice::Open(), DIDevice::Open(), WinWdmStream::Open(), ImageCache::OutputStats(), NetworkSyncManager::PostStartUp(), InputHandler_SextetStream::Impl::RunInputThread(), SetupExtensions(), sm_main(), InputHandler_Linux_Event::TryDevice(), InputHandler_Linux_Joystick::TryDevice(), NotesWriterSSC::Write(), NotesWriterETT::Write(), WriteLogHeader(), InputHandler_Linux_PIUIO::~InputHandler_Linux_PIUIO(), ~RageLog(), and RageSoundDriver::~RageSoundDriver().
MapLog()
void RageLog::MapLog (const RString & key, const char * fmt, ...)
References LogMaps, UpdateMappedLog(), and vssprintf().
Referenced by MovieTexture_Generic::DecodeSeconds(), GameStateMessageHandler::HandleMessage(), RageDisplay_D3D::Init(), ThemeManager::LoadThemeMetrics(), ScreenManager::PopTopScreenInternal(), ScreenManagerUtil::PushLoadedScreen(), RageDisplay_GLES2::RageDisplay_GLES2(), RageDisplay_Legacy::RageDisplay_Legacy(), RageDisplay_Null::RageDisplay_Null(), RageSoundDriver::Update(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
SetFlushing()
void RageLog::SetFlushing (bool b)
References m_bFlush.
Referenced by ApplyLogPreferences().
SetInfoToDisk()
void RageLog::SetInfoToDisk (bool b)
References RageFile::Close(), RageFile::GetError(), INFO_PATH, RageFile::IsOpen(), m_bInfoToDisk, RageFile::Open(), RageFile::STREAMED, and RageFile::WRITE.
Referenced by ApplyLogPreferences().
SetLogToDisk()
void RageLog::SetLogToDisk (bool b)
References RageFile::Close(), RageFile::GetError(), RageFile::IsOpen(), LOG_PATH, m_bLogToDisk, RageFile::Open(), RageFile::STREAMED, and RageFile::WRITE.
Referenced by ApplyLogPreferences().
SetShowLogOutput()
void RageLog::SetShowLogOutput (bool show)
References m_bShowLogOutput.
Referenced by ApplyLogPreferences(), and ~RageLog().
SetUserLogToDisk()
void RageLog::SetUserLogToDisk (bool b)
References RageFile::Close(), RageFile::GetError(), RageFile::IsOpen(), m_bUserLogToDisk, RageFile::Open(), RageFile::STREAMED, USER_PATH, and RageFile::WRITE.
Referenced by ApplyLogPreferences().
Time()
void RageLog::Time (const char * fmt, ...)
References vssprintf(), Write(), and WRITE_TO_TIME.
Trace()
void RageLog::Trace (const char * fmt, ...)
References vssprintf(), and Write().
Referenced by InputHandler_MacOSX_HID::AddDevices(), TimingData::AddSegment(), ActorMultiTexture::AddTexture(), AdjustForChangedSystemCapabilities(), ScreenSelectMusic::AfterMusicChange(), RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface(), AVIORageFile_Seek(), ScreenSelectMusic::BeginScreen(), MessageManager::Broadcast(), TimingData::BuildAndGetEtar(), BuildFilterList(), InputFilter::ButtonPressed(), NoteField::CacheNoteSkin(), SongCacheIndex::CacheSong(), Profile::CalculateStatsFromScores(), ScreenAttract::Cancel(), ChangeAppPri(), ScreenSelectMusic::ChangeSteps(), MovieTexture_Generic::CheckFrameTime(), CheckGameLoopTimerSkips(), DSoundBuf::CheckUnderrun(), CheckVideoDefaultSettings(), DSoundBuf::CheckWriteahead(), RageSoundDriver::ClampHardwareFrame(), StatsManager::CommitStatsToProfiles(), CompareLanguageTag::CompareLanguageTag(), CompileShader(), ETTProtocol::Connect(), convert_xml_file(), RageMovieTexture::Create(), RageSoundDriver::Create(), InputHandler::Create(), MovieTexture_DShow::Create(), RageThread::Create(), RenderTarget_X11::Create(), RageDisplay_Legacy::CreateTexture(), RageSoundDriver_PulseAudio::CtxStateCb(), D3DReduceParams(), TimingSegment::DebugPrint(), FakeSegment::DebugPrint(), WarpSegment::DebugPrint(), TickcountSegment::DebugPrint(), ComboSegment::DebugPrint(), LabelSegment::DebugPrint(), BPMSegment::DebugPrint(), TimeSignatureSegment::DebugPrint(), SpeedSegment::DebugPrint(), ScrollSegment::DebugPrint(), StopSegment::DebugPrint(), DelaySegment::DebugPrint(), WavReaderADPCM::DecodeADPCMBlock(), MovieTexture_Generic::DecodeFrame(), MovieDecoder_FFMpeg::DecodePacket(), SongUtil::DeleteDuplicateSteps(), TimingData::DeleteRows(), RageTextureManager::DiagnosticOutput(), SongManager::DifferentialReloadDir(), DumpAVIDebugInfo(), TimingData::DumpLookupTables(), TimingData::DumpOneTable(), EraseSegment(), Alsa9Buf::ErrorHandler(), StageStats::FinalizeScores(), FindBackBufferType(), FindEndOfHeaders(), ThreadedFileWorker::FlushDirCache(), ScreenTextEntry::TextEntrySettings::FromStack(), PlayerOptions::FromString(), RageTextureManager::GarbageCollect(), DSoundBuf::get_output_buf(), GetDeviceState(), TimingData::GetDisplayedSpeedPercent(), Alsa9Buf::GetNumFramesToFill(), AnnouncerManager::GetPathTo(), GetVideoCodecDebugInfo(), HandleBunki(), HandleGlobalInputs(), ScreenWithMenuElements::HandleLuaMusicFile(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsMaster::HandleScreenMessage(), ScreenNetEvaluation::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), Profile::ImportScoresToEtterna(), RageDisplay_D3D::Init(), RageSoundDriver_ALSA9_Software::Init(), RageSoundDriver_JACK::Init(), RageSoundDriver_PulseAudio::Init(), RageSoundDriver_WDMKS::Init(), RageSoundDriver_OSS::Init(), ScreenEvaluation::Init(), Screen::Init(), MovieTexture_Generic::Init(), ScreenGameplay::Init(), ScreenOptions::InitMenu(), InitShaders(), SongManager::InitSongsFromDisk(), ScreenTitleMenu::Input(), ScreenMapControllers::Input(), ScreenDebugOverlay::Input(), ScreenGameplay::Input(), InputHandler_DInput::InputHandler_DInput(), InputHandler_Linux_Joystick::InputHandler_Linux_Joystick(), InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO(), InputHandler_MacOSX_HID::InputHandler_MacOSX_HID(), InputHandler_DInput::InputThreadMain(), WinWdmFilter::InstantiateRenderPin(), BackgroundLoader::IsCacheFileFinished(), LowLevelWindow_Win32::IsSoftwareRenderer(), MusicWheel::JumpToPrevGroup(), PercentageDisplay::Load(), InputQueueCode::Load(), WheelBase::Load(), RoomWheel::Load(), RageSound::Load(), actor_template_t::load_frames_from_file(), actor_template_t::load_model_from_file(), Profile::LoadAllFromDir(), SongCacheIndex::LoadCache(), SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), XMLProfile::LoadEttFromDir(), Font::LoadFontPageSettings(), BMSLoader::LoadFromDir(), KSFLoader::LoadFromDir(), DWILoader::LoadFromDir(), LoadFromKSFFile(), LyricsLoader::LoadFromLRCFile(), MeterDisplay::LoadFromNode(), PercentageDisplay::LoadFromNode(), SMALoader::LoadFromSimfile(), SongCacheIndex::LoadHyperCache(), SSCLoader::LoadNoteDataFromSimfile(), NoteSkinManager::LoadNoteSkinDataRecursive(), ProfileManager::LoadProfile(), HighScore::LoadReplayDataBasic(), HighScore::LoadReplayDataFull(), SongCacheIndex::LoadSongFromCache(), RandomSample::LoadSound(), XMLProfile::LoadStatsFromDir(), SongManager::LoadStepManiaSongDir(), RageSurfaceUtils::LoadSurface(), BackgroundLoader::LoadThread(), RageSoundDriver_PulseAudio::m_InitStream(), ScreenManager::MakeNewScreen(), RageSoundDriver_OSS::MixerThread(), MountTreeOfZips(), MovieTexture_DShow::MovieTexture_DShow(), MovieTexture_Generic::MovieTexture_Generic(), MovieTexture_Null::MovieTexture_Null(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), MovieDecoder_FFMpeg::Open(), DIDevice::Open(), ThreadedFileWorker::Open(), MovieDecoder_FFMpeg::OpenCodec(), SongCacheIndex::OpenDB(), RageSoundDriver::PauseMixing(), MovieTexture_DShow::Play(), LunaScreenSelectMusic::PlayReplay(), PNG_Warning(), ThreadedFileWorker::PopulateFileSet(), ScreenManager::PrepareScreen(), SMOProtocol::ProcessInput(), RageDisplay::ProcessStatsOnFlip(), ScreenManagerUtil::PushLoadedScreen(), IPreference::PushValue(), RageDisplay_GLES2::RageDisplay_GLES2(), RageDisplay_Legacy::RageDisplay_Legacy(), RageInput::RageInput(), InputHandler_SextetStream::Impl::ReactToChanges(), RageSoundReader_Vorbisfile::Read(), RageSoundReader_Merge::Read(), CsvFile::ReadFile(), IniFile::ReadFile(), ImageCache::ReadFromDisk(), InputMappings::ReadMappings(), MusicWheel::readyWheelItemsData(), LuaHelpers::rec_print_table(), Alsa9Buf::Recover(), ConcurrentRenderer::RenderThread(), SMOProtocol::ReportScore(), SMOProtocol::ReportStyle(), DownloadManager::RequestChartLeaderBoard(), InputHandler_MacOSX_HID::Run(), InputHandler_SextetStream::Impl::RunInputThread(), ThemeManager::RunLuaScripts(), Song::Save(), XMLProfile::SaveEttXmlToDir(), RageDisplay::SaveScreenshot(), XMLProfile::SaveStatsXmlToDir(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToJsonFile(), Song::SaveToSMFile(), Song::SaveToSSCFile(), ScoreDisplayLifeTime::ScoreDisplayLifeTime(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayOni::ScoreDisplayOni(), pos_map_queue::Search(), SearchForDifficulty(), MusicWheel::Select(), WheelBase::Select(), MusicWheel::SelectSongOrCourse(), ETTProtocol::Send(), ComboGraph::Set(), Checkpoints::SetCheckpoint(), IPreference::SetFromStack(), ArchHooks::SetHasFocus(), MovieTexture_Generic::SetPosition(), LunaPrefsManager::SetPreferenceToDefault(), SetPresentParametersFromVideoModeParams(), ArchHooks_Unix::SetTime(), RageSoundDriver_OSS::SetupDecodingThread(), RageDisplay::SetVideoMode(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ShowWarningOrTrace(), InputHandler_DInput::ShutdownThread(), CryptManager::Sign(), StartMusic(), RageSound::StartPlaying(), SMOProtocol::StartRequest(), RageSoundDriver::StopMixing(), InputHandler_Linux_Event::StopThread(), InputHandler_Linux_Joystick::StopThread(), RageWorkerThread::StopThread(), ScreenOptions::StoreFocus(), RageSoundDriver_PulseAudio::StreamStateCb(), ThemeManager::SwitchThemeAndLanguage(), SyncFiles(), ScreenManager::SystemMessage(), TapNote::TapNote(), ScreenManager::ThemeChanged(), RageException::Throw(), Song::TidyUpData(), TryOpenFile(), RageSoundReader_FileReader::TryOpenFile(), LowLevelWindow_Win32::TryVideoMode(), NoteField::UncacheNoteSkin(), LockMutex::Unlock(), GameSoundManager::Update(), ScreenManager::Update(), RageSoundManager::Update(), RageSoundDriver::Update(), ScreenGameplay::Update(), ETTProtocol::Update(), InputHandler_DInput::UpdateBuffered(), DownloadManager::UpdateHTTP(), ScreenStatsOverlay::UpdateSkips(), MusicWheel::UpdateSwitch(), CryptManager::VerifyFileWithFile(), RageWorkerThread::WorkerMain(), Alsa9Buf::Write(), PacketFunctions::Write1(), WriteDWINotesTag(), CsvFile::WriteFile(), HighScore::WriteInputData(), WriteLogHeader(), HighScoreImpl::WriteReplayData(), FontManager::~FontManager(), GameSoundManager::~GameSoundManager(), InputHandler_Linux_PIUIO::~InputHandler_Linux_PIUIO(), InputHandler_Linux_tty::~InputHandler_Linux_tty(), InputHandler_MacOSX_HID::~InputHandler_MacOSX_HID(), InputHandler_Win32_Pump::~InputHandler_Win32_Pump(), ModelManager::~ModelManager(), MovieTexture_DShow::~MovieTexture_DShow(), RageDisplay_D3D::~RageDisplay_D3D(), RageSoundDriver::~RageSoundDriver(), RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software(), RageSoundDriver_DSound_Software::~RageSoundDriver_DSound_Software(), RageSoundDriver_OSS::~RageSoundDriver_OSS(), RageSoundDriver_WaveOut::~RageSoundDriver_WaveOut(), RageSoundDriver_WDMKS::~RageSoundDriver_WDMKS(), RageTextureManager::~RageTextureManager(), ScreenGameplay::~ScreenGameplay(), ScreenManager::~ScreenManager(), ScreenOptions::~ScreenOptions(), ScreenSelect::~ScreenSelect(), and ScreenSelectMusic::~ScreenSelectMusic().
UnmapLog()
void RageLog::UnmapLog (const RString & key)
References LogMaps, and UpdateMappedLog().
Referenced by ScreenManager::PopTopScreenInternal(), and ScreenManager::~ScreenManager().
UpdateMappedLog()
void RageLog::UpdateMappedLog () private
References FOREACHM_CONST, g_AdditionalLogSize, g_AdditionalLogStr, LogMaps, min(), NEWLINE, and ssprintf().
Referenced by MapLog(), and UnmapLog().
UserLog()
void RageLog::UserLog (const RString & sType, const RString & sElement, const char * fmt, ...)
References ssprintf(), vssprintf(), Write(), and WRITE_TO_USER_LOG.
Referenced by BMSSongLoader::AddToSong(), BMSSong::AllocateKeysound(), ImageCache::CacheImageInternal(), BMSChartReader::DetermineStepsType(), bmsCommandTree::doStatement(), DWIcharToNote(), BMSSong::GetBackground(), ThemeManager::GetMetricRaw(), ThemeManager::GetPathInfo(), BMSChart::Load(), ImageCache::LoadCachedImage(), SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), RageSurfaceUtils::LoadFile(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadFromSMNoteDataStringWithPlayer(), Song::LoadFromSongDir(), LoadGlobalData(), DWILoader::LoadNoteDataFromSimfile(), OsuLoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), RageSoundReader_FileReader::OpenFile(), SMLoader::ParseBPMs(), ParseNoteData(), SMLoader::ParseStops(), SMALoader::ProcessBeatsPerMeasure(), SMLoader::ProcessBGChanges(), SSCLoader::ProcessBPMs(), SMLoader::ProcessBPMsAndStops(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SSCLoader::ProcessLabels(), SMALoader::ProcessMultipliers(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SMLoader::ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), SSCLoader::ProcessWarps(), BMSChartReader::ReadNoteData(), Song::Save(), SetSelectable(), SMSetSelectable(), Song::TidyUpData(), TimingData::TidyUpData(), NotesWriterDWI::Write(), NotesWriterSM::Write(), NotesWriterSSC::Write(), and NotesWriterETT::Write().
Warn()
void RageLog::Warn (const char * fmt, ...)
References vssprintf(), Write(), WRITE_LOUD, and WRITE_TO_INFO.
Referenced by DownloadManager::AddFavorite(), ActorMultiTexture::AddTexture(), LowLevelWindow_Win32::BeginConcurrentRendering(), ScreenSelectMusic::BeginScreen(), GameState::BeginStage(), ArchHooks_Win32::BoostPriority(), TimingData::BuildAndGetEtar(), InputFilter::ButtonPressed(), InputHandler::ButtonPressed(), FilenameDB::CacheFile(), ChangeToDirOfExecutable(), CheckCodecVersion(), CheckForDirectInputDebugMode(), RageSoundDriver_OSS::CheckOSSVersion(), CheckVideoDefaultSettings(), DSoundBuf::CheckWriteahead(), CompileShader(), SMOProtocol::Connect(), RageSoundDriver::Create(), RageBitmapTexture::Create(), ImageTexture::Create(), D3DRenderTarget_FramebufferObject::Create(), MovieDecoder_FFMpeg::DecodePacket(), Steps::Decompress(), ProfileManager::DeleteLocalProfile(), CodeDetector::DetectAndAdjustMusicOptions(), InputHandler_DInput::DevicesChanged(), RageWorkerThread::DoRequest(), DumpPixelFormat(), FileCopy(), RageSoundReader_Chain::Finish(), RageSoundReader_Merge::Finish(), D3DRenderTarget_FramebufferObject::FinishRenderingTo(), FilenameDB::FlushDirCache(), CryptManager::GenerateGlobalKeys(), CryptManager::GenerateRSAKey(), DSoundBuf::get_output_buf(), ActorUtil::GetAttrPath(), ArchHooks_Unix::GetClipboard(), ArchHooks_Win32::GetClipboard(), ArchHooks::GetClipboard(), RageSound::GetDataToPlay(), getDevice(), FilenameDB::GetFile(), GetFileContents(), FilenameDB::GetFileSet(), MovieDecoder_FFMpeg::GetFrame(), RageSoundDriver::GetHardwareFrame(), RageSound::GetLengthSeconds(), LocalizedStringImplThemeMetric::GetLocalized(), CryptManager::GetMD5ForFile(), GetNumJoysticksSlow(), ThemeManager::GetPathInfo(), RageSoundDriver_AU::GetPlayLatency(), DSoundBuf::GetPosition(), ArchHooks::GetPreferredLanguage(), CryptManager::GetSHA1ForFile(), RageSoundReader_Chain::GetStreamToSourceRatio(), HashFile(), OptionRowHandlerList::ImportOption(), ArchHooks_MacOSX::Init(), RageSoundDriver_AU::Init(), RageSoundDriver_JACK::Init(), DSound::Init(), RageDisplay_Legacy::Init(), DSoundBuf::Init(), InitHack(), StepMania::InitializeCurrentGame(), InputHandler_Linux_PIUIO::InputHandler_Linux_PIUIO(), InputHandler_Win32_MIDI::InputHandler_Win32_MIDI(), InputHandler_Linux_PIUIO::InputThread(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), InputHandler_Win32_Pump::InputThreadMain(), InputHandler_DInput::InputThreadMain(), DSound::IsEmulated(), Language(), LinuxInputManager::LinuxInputManager(), RageSound::Load(), ImageCache::LoadCachedImage(), RageInput::LoadDrivers(), Font::LoadFontPageSettings(), JsonUtil::LoadFromFileShowErrors(), LoadFromSMNoteDataStringWithPlayer(), Foreground::LoadFromSong(), JsonUtil::LoadFromString(), HighScore::LoadReplayDataBasic(), HighScore::LoadReplayDataFull(), LoadShader(), RageSoundReader_Chain::LoadSound(), ActorUtil::MakeActor(), RageSoundDriver_WaveOut::MixerThread(), RageSoundDriver_WDMKS::MixerThread(), RageSoundDriver_DSound_Software::MixerThread(), RageFileManager::Mount(), TimingData::NegStopAndBPMCheck(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), RageSoundReader_WAV::Open(), EventDevice::Open(), LuaHelpers::ParseCommandList(), RageSound::Pause(), RageSound::Play(), NetworkSyncManager::PostStartUp(), RageFileManager::Remount(), LuaHelpers::ReportScriptError(), RageSoundReader::RetriedRead(), InputHandler_MacOSX_HID::Run(), InputHandler_SextetStream::Impl::RunInputThread(), ThemeManager::RunLuaScripts(), ScreenSelectMusic::SelectCurrent(), MovieTexture_Generic::SetPosition(), RageSound::SetPositionFrames(), DSound::SetPrimaryBufferMode(), RageDisplay_D3D::SetRenderTarget(), SetSampleRate(), ActorMultiTexture::SetTextureMode(), RageSoundDriver_AU::SetupDecodingThread(), RageSoundDriver_DSound_Software::SetupDecodingThread(), RageSoundDriver_WaveOut::SetupDecodingThread(), RageSoundDriver_WDMKS::SetupDecodingThread(), DSoundBuf::SetVolume(), ShowWarningOrTrace(), CryptManager::Sign(), SongCacheIndex::SongFromStatement(), D3DRenderTarget_FramebufferObject::StartRenderingTo(), StringToGrade(), ThemeManager::SwitchThemeAndLanguage(), SwitchToLastPlayedGame(), Steps::TidyUpData(), InputHandler_Linux_Joystick::TryDevice(), LowLevelWindow_Win32::TryVideoMode(), RageDisplay_GLES2::TryVideoMode(), RageDisplay_D3D::TryVideoMode(), ScreenDebugOverlay::UpdateText(), CryptManager::Verify(), CryptManager::VerifyFileWithFile(), JsonUtil::WriteFile(), IniFile::WriteFile(), WriteFile(), HighScore::WriteInputData(), HighScoreImpl::WriteReplayData(), and InputHandler_Win32_MIDI::~InputHandler_Win32_MIDI().
Write()
void RageLog::Write (int where, const RString & str) private
References AddToInfo(), AddToRecentLogs(), Flush(), RageTimer::GetTimeSinceStart(), RageFile::IsOpen(), LockMut, m_bFlush, m_bLogToDisk, m_bShowLogOutput, m_bUserLogToDisk, RageFile::PutLine(), SecondsToMMSSMsMsMs(), split(), WRITE_LOUD, WRITE_TO_INFO, WRITE_TO_TIME, and WRITE_TO_USER_LOG.
Referenced by Info(), Time(), Trace(), UserLog(), and Warn().
Member Data Documentation
m_bFlush
bool RageLog::m_bFlush { false } private
Referenced by SetFlushing(), and Write().
m_bInfoToDisk
bool RageLog::m_bInfoToDisk { false } private
Referenced by SetInfoToDisk().
m_bLogToDisk
bool RageLog::m_bLogToDisk { false } private
Referenced by SetLogToDisk(), and Write().
m_bShowLogOutput
bool RageLog::m_bShowLogOutput { false } private
Referenced by SetShowLogOutput(), and Write().
m_bUserLogToDisk
bool RageLog::m_bUserLogToDisk { false } private
Referenced by SetUserLogToDisk(), and Write().
The documentation for this class was generated from the following files:
RageLog.h
RageLog.cpp