Etterna: StepMania Namespace Reference
StepMania Namespace Reference
Utility functions for controlling the whole game.
Classes
class Rect
Functions
void ApplyGraphicOptions ()
void ResetPreferences ()
void ResetGame ()
RString GetInitialScreen ()
RString GetSelectMusicScreen ()
void InitializeCurrentGame (const Game *g)
RString SaveScreenshot (const RString &Dir, bool SaveCompressed, bool MakeSignature, const RString &NamePrefix, const RString &NameSuffix)
void InsertCoin (int iNum=1, bool bCountInBookkeeping=true)
void InsertCredit ()
void ClearCredits ()
void GetPreferredVideoModeParams (VideoModeParams &paramsOut)
bool GetHighResolutionTextures ()
Detailed Description
Utility functions for controlling the whole game.
Function Documentation
ApplyGraphicOptions()
void StepMania::ApplyGraphicOptions ()
References DISPLAY, GetActualGraphicOptionsString(), GetHighResolutionTextures(), GetPreferredVideoModeParams(), INPUTMAN, PrefsManager::m_bDelayedModelDelete, PrefsManager::m_bDelayedTextureDelete, PrefsManager::m_bForceMipMaps, PrefsManager::m_iMaxTextureResolution, PrefsManager::m_iMovieColorDepth, PrefsManager::m_iTextureColorDepth, MODELMAN, PREFSMAN, RageTextureManager::ReloadAll(), SCREENMAN, ModelManager::SetPrefs(), RageTextureManager::SetPrefs(), RageDisplay::SetVideoMode(), StoreActualGraphicOptions(), ScreenManager::SystemMessage(), TEXTUREMAN, RageException::Throw(), update_centering(), and RageInput::WindowReset().
Referenced by DebugLineVsync::DoAndLog(), HandleInputEvents(), and ResetPreferences().
ClearCredits()
void StepMania::ClearCredits ()
References MessageManager::Broadcast(), MESSAGEMAN, ScreenManager::PlayInvalidSound(), and SCREENMAN.
GetHighResolutionTextures()
bool StepMania::GetHighResolutionTextures ()
References ThemeManager::GetMetricI(), HighResolutionTextures_Auto, HighResolutionTextures_ForceOff, HighResolutionTextures_ForceOn, PrefsManager::m_HighResolutionTextures, PrefsManager::m_iDisplayHeight, PREFSMAN, and THEME.
Referenced by ApplyGraphicOptions(), RageBitmapTexture::Create(), and StartDisplay().
GetInitialScreen()
RString StepMania::GetInitialScreen ()
References ThemeMetric< T >::GetValue(), INITIAL_SCREEN, ScreenManager::IsScreenNameValid(), PrefsManager::m_sTestInitialScreen, PREFSMAN, and SCREENMAN.
Referenced by sm_main().
GetPreferredVideoModeParams()
void StepMania::GetPreferredVideoModeParams (VideoModeParams & paramsOut)
References ThemeManager::GetPathG(), PrefsManager::m_bAnisotropicFiltering, PrefsManager::m_bInterlaced, PrefsManager::m_bPAL, PrefsManager::m_bSmoothLines, PrefsManager::m_bTrilinearFiltering, PrefsManager::m_bVsync, PrefsManager::m_bWindowed, PrefsManager::m_fDisplayAspectRatio, PrefsManager::m_iDisplayColorDepth, PrefsManager::m_iDisplayHeight, PrefsManager::m_iDisplayWidth, PrefsManager::m_iRefreshRate, PREFSMAN, THEME, and CommonMetrics::WINDOW_TITLE.
Referenced by ApplyGraphicOptions(), and CreateDisplay().
GetSelectMusicScreen()
RString StepMania::GetSelectMusicScreen ()
References ThemeMetric< T >::GetValue(), and SELECT_MUSIC_SCREEN.
InitializeCurrentGame()
void StepMania::InitializeCurrentGame (const Game * g)
References ANNOUNCER, ASSERT, GAMEMAN, GAMESTATE, GetCommandlineArgument(), GameState::GetCurrentGame(), INPUTMAPPER, LOG, PrefsManager::m_bPseudoLocalize, Game::m_InputScheme, PrefsManager::m_sAnnouncer, PrefsManager::m_sLanguage, PrefsManager::m_sTheme, Game::m_szName, PREFSMAN, InputMapper::ReadMappingsFromDisk(), GameState::SetCurGame(), PrefsManager::SetCurrentGame(), InputMapper::SetInputScheme(), GameManager::StringToGame(), AnnouncerManager::SwitchAnnouncer(), ThemeManager::SwitchThemeAndLanguage(), THEME, and RageLog::Warn().
Referenced by sm_main(), and SwitchToLastPlayedGame().
InsertCoin()
void StepMania::InsertCoin (int iNum = 1, bool bCountInBookkeeping = true)
InsertCredit()
void StepMania::InsertCredit ()
ResetGame()
void StepMania::ResetGame ()
References RageTextureManager::DoDelayedDelete(), ThemeManager::DoesThemeExist(), GAMESTATE, ThemeManager::GetCurLanguage(), GameState::GetCurrentGame(), ThemeManager::GetCurThemeName(), PrefsManager::m_bPseudoLocalize, PrefsManager::m_sDefaultTheme, Game::m_szName, PREFSMAN, GameState::Reset(), PrefsManager::SavePrefsToDisk(), ThemeManager::SwitchThemeAndLanguage(), TEXTUREMAN, and THEME.
Referenced by sm_main().
ResetPreferences()
void StepMania::ResetPreferences ()
References ApplyGraphicOptions(), CheckVideoDefaultSettings(), PREFSMAN, PrefsManager::ResetToFactoryDefaults(), RageSoundManager::SetMixVolume(), and SOUNDMAN.
Referenced by ResetPreferences().
SaveScreenshot()
RString StepMania::SaveScreenshot (const RString & Dir, bool SaveCompressed, bool MakeSignature, const RString & NamePrefix, const RString & NameSuffix)
References DISPLAY, DateTime::GetNowDateTime(), DateTime::GetString(), PrefsManager::m_bSignProfileData, ScreenManager::PlayInvalidSound(), ScreenManager::PlayScreenshotSound(), PREFSMAN, StdString::CStdStr< CT >::Replace(), RageDisplay::SAVE_LOSSLESS_SENSIBLE, RageDisplay::SAVE_LOSSY_HIGH_QUAL, RageDisplay::SaveScreenshot(), SCREENMAN, and CryptManager::SignFileToFile().
Referenced by HandleGlobalInputs(), ScreenEvaluation::Input(), and LuaFunc_SaveScreenshot().