Etterna: NotesLoaderSSC.cpp File Reference
NotesLoaderSSC.cpp File Reference
#include "global.h"
#include "NotesLoaderSSC.h"
#include "BackgroundUtil.h"
#include "GameManager.h"
#include "MsdFile.h"
#include "NoteTypes.h"
#include "NotesLoaderSM.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "Song.h"
#include "SongManager.h"
#include "Steps.h"
Classes
struct ssc_parser_helper_t
Typedefs
using steps_tag_func_t = void(*)(SSC::StepsTagInfo &)
using song_tag_func_t = void(*)(SSC::SongTagInfo &)
typedef std::map< RString, steps_tag_func_t > steps_handler_map_t
typedef std::map< RString, song_tag_func_t > song_handler_map_t
typedef std::map< RString, SSC::LoadNoteDataTagIDs > load_note_data_handler_map_t
Functions
void SetVersion (SSC::SongTagInfo &info)
void SetTitle (SSC::SongTagInfo &info)
void SetSubtitle (SSC::SongTagInfo &info)
void SetArtist (SSC::SongTagInfo &info)
void SetMainTitleTranslit (SSC::SongTagInfo &info)
void SetSubtitleTranslit (SSC::SongTagInfo &info)
void SetArtistTranslit (SSC::SongTagInfo &info)
void SetGenre (SSC::SongTagInfo &info)
void SetOrigin (SSC::SongTagInfo &info)
void SetCredit (SSC::SongTagInfo &info)
void SetBanner (SSC::SongTagInfo &info)
void SetBackground (SSC::SongTagInfo &info)
void SetPreviewVid (SSC::SongTagInfo &info)
void SetJacket (SSC::SongTagInfo &info)
void SetCDImage (SSC::SongTagInfo &info)
void SetDiscImage (SSC::SongTagInfo &info)
void SetLyricsPath (SSC::SongTagInfo &info)
void SetCDTitle (SSC::SongTagInfo &info)
void SetMusic (SSC::SongTagInfo &info)
void SetPreview (SSC::SongTagInfo &info)
void SetInstrumentTrack (SSC::SongTagInfo &info)
void SetMusicLength (SSC::SongTagInfo &info)
void SetLastSecondHint (SSC::SongTagInfo &info)
void SetSampleStart (SSC::SongTagInfo &info)
void SetSampleLength (SSC::SongTagInfo &info)
void SetDisplayBPM (SSC::SongTagInfo &info)
void SetSelectable (SSC::SongTagInfo &info)
void SetBGChanges (SSC::SongTagInfo &info)
void SetFGChanges (SSC::SongTagInfo &info)
void SetKeysounds (SSC::SongTagInfo &info)
void SetOffset (SSC::SongTagInfo &info)
void SetSongStops (SSC::SongTagInfo &info)
void SetSongDelays (SSC::SongTagInfo &info)
void SetSongBPMs (SSC::SongTagInfo &info)
void SetSongWarps (SSC::SongTagInfo &info)
void SetSongLabels (SSC::SongTagInfo &info)
void SetSongTimeSignatures (SSC::SongTagInfo &info)
void SetSongTickCounts (SSC::SongTagInfo &info)
void SetSongCombos (SSC::SongTagInfo &info)
void SetSongSpeeds (SSC::SongTagInfo &info)
void SetSongScrolls (SSC::SongTagInfo &info)
void SetSongFakes (SSC::SongTagInfo &info)
void SetFirstSecond (SSC::SongTagInfo &info)
void SetLastSecond (SSC::SongTagInfo &info)
void SetSongFilename (SSC::SongTagInfo &info)
void SetHasMusic (SSC::SongTagInfo &info)
void SetHasBanner (SSC::SongTagInfo &info)
void SetStepsVersion (SSC::StepsTagInfo &info)
void SetChartName (SSC::StepsTagInfo &info)
void SetStepsType (SSC::StepsTagInfo &info)
void SetChartStyle (SSC::StepsTagInfo &info)
void SetDescription (SSC::StepsTagInfo &info)
void SetDifficulty (SSC::StepsTagInfo &info)
void SetMeter (SSC::StepsTagInfo &info)
void SetRadarValues (SSC::StepsTagInfo &info)
void SetCredit (SSC::StepsTagInfo &info)
void SetStepsMusic (SSC::StepsTagInfo &info)
void SetStepsBPMs (SSC::StepsTagInfo &info)
void SetStepsStops (SSC::StepsTagInfo &info)
void SetStepsDelays (SSC::StepsTagInfo &info)
void SetStepsTimeSignatures (SSC::StepsTagInfo &info)
void SetStepsTickCounts (SSC::StepsTagInfo &info)
void SetStepsCombos (SSC::StepsTagInfo &info)
void SetStepsWarps (SSC::StepsTagInfo &info)
void SetStepsSpeeds (SSC::StepsTagInfo &info)
void SetStepsScrolls (SSC::StepsTagInfo &info)
void SetStepsFakes (SSC::StepsTagInfo &info)
void SetStepsLabels (SSC::StepsTagInfo &info)
void SetStepsOffset (SSC::StepsTagInfo &info)
void SetStepsDisplayBPM (SSC::StepsTagInfo &info)
void SetChartKey (SSC::StepsTagInfo &info)
void SetMSDValues (SSC::StepsTagInfo &info)
Variables
ssc_parser_helper_t parser_helper
Typedef Documentation
load_note_data_handler_map_t
typedef std::map<RString, SSC::LoadNoteDataTagIDs> load_note_data_handler_map_t
song_handler_map_t
typedef std::map<RString, song_tag_func_t> song_handler_map_t
song_tag_func_t
using song_tag_func_t = void (*)(SSC::SongTagInfo&)
steps_handler_map_t
typedef std::map<RString, steps_tag_func_t> steps_handler_map_t
steps_tag_func_t
using steps_tag_func_t = void (*)(SSC::StepsTagInfo&)
Function Documentation
SetArtist()
void SetArtist (SSC::SongTagInfo & info)
References Song::m_sArtist, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetArtistTranslit()
void SetArtistTranslit (SSC::SongTagInfo & info)
References Song::m_sArtistTranslit, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetBackground()
void SetBackground (SSC::SongTagInfo & info)
References Song::m_sBackgroundFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetBanner()
void SetBanner (SSC::SongTagInfo & info)
References Song::m_sBannerFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetBGChanges()
void SetBGChanges (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, SSC::SongTagInfo::params, SSC::SongTagInfo::path, SMLoader::ProcessBGChanges(), and SSC::SongTagInfo::song.
Referenced by SSCLoader::LoadFromSimfile(), and ssc_parser_helper_t::ssc_parser_helper_t().
SetCDImage()
void SetCDImage (SSC::SongTagInfo & info)
References Song::m_sCDFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetCDTitle()
void SetCDTitle (SSC::SongTagInfo & info)
References Song::m_sCDTitleFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetChartKey()
void SetChartKey (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetChartKey(), and SSC::StepsTagInfo::steps.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetChartName()
void SetChartName (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetChartName(), SSC::StepsTagInfo::steps, and Trim().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetChartStyle()
void SetChartStyle (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetChartStyle(), SSC::StepsTagInfo::ssc_format, and SSC::StepsTagInfo::steps.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetCredit() [1/2]
void SetCredit (SSC::SongTagInfo & info)
References Song::m_sCredit, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and Trim().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetCredit() [2/2]
void SetCredit (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetCredit(), SSC::StepsTagInfo::ssc_format, and SSC::StepsTagInfo::steps.
SetDescription()
void SetDescription (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, Song::m_fVersion, SSC::StepsTagInfo::params, Steps::SetChartName(), Steps::SetDescription(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, Trim(), and VERSION_CHART_NAME_TAG.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetDifficulty()
void SetDifficulty (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetDifficulty(), SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, and StringToDifficulty().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetDiscImage()
void SetDiscImage (SSC::SongTagInfo & info)
References Song::m_sDiscFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetDisplayBPM()
void SetDisplayBPM (SSC::SongTagInfo & info)
References DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, Song::m_DisplayBPMType, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetFGChanges()
void SetFGChanges (SSC::SongTagInfo & info)
References Song::AddForegroundChange(), SSC::SongTagInfo::loader, SMLoader::LoadFromBGChangesString(), SSC::SongTagInfo::params, SSC::SongTagInfo::song, and split().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetFirstSecond()
void SetFirstSecond (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, SSC::SongTagInfo::params, Song::SetFirstSecond(), SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetGenre()
void SetGenre (SSC::SongTagInfo & info)
References Song::m_sGenre, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetHasBanner()
void SetHasBanner (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, Song::m_bHasBanner, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToInt().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetHasMusic()
void SetHasMusic (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, Song::m_bHasMusic, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToInt().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetInstrumentTrack()
void SetInstrumentTrack (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, SSC::SongTagInfo::params, SMLoader::ProcessInstrumentTracks(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetJacket()
void SetJacket (SSC::SongTagInfo & info)
References Song::m_sJacketFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetKeysounds()
void SetKeysounds (SSC::SongTagInfo & info)
References Song::m_vsKeysoundFile, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and split().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetLastSecond()
void SetLastSecond (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, SSC::SongTagInfo::params, Song::SetLastSecond(), SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetLastSecondHint()
void SetLastSecondHint (SSC::SongTagInfo & info)
References SSC::SongTagInfo::params, Song::SetSpecifiedLastSecond(), SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetLyricsPath()
void SetLyricsPath (SSC::SongTagInfo & info)
References Song::m_sLyricsFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetMainTitleTranslit()
void SetMainTitleTranslit (SSC::SongTagInfo & info)
References Song::m_sMainTitleTranslit, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetMeter()
void SetMeter (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetMeter(), SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, and StringToInt().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetMSDValues()
void SetMSDValues (SSC::StepsTagInfo & info)
References SSC::msdsplit(), SSC::StepsTagInfo::params, Steps::SetAllMSD(), and SSC::StepsTagInfo::steps.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetMusic()
void SetMusic (SSC::SongTagInfo & info)
References Song::m_sMusicFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetMusicLength()
void SetMusicLength (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, Song::m_fMusicLengthSeconds, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetOffset()
void SetOffset (SSC::SongTagInfo & info)
References TimingData::m_fBeat0OffsetInSeconds, Song::m_SongTiming, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetOrigin()
void SetOrigin (SSC::SongTagInfo & info)
References Song::m_sOrigin, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetPreview()
void SetPreview (SSC::SongTagInfo & info)
References Song::m_PreviewFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetPreviewVid()
void SetPreviewVid (SSC::SongTagInfo & info)
References Song::m_sPreviewVidFile, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetRadarValues()
void SetRadarValues (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::from_cache, NUM_RadarCategory, SSC::StepsTagInfo::params, Steps::SetCachedRadarValues(), split(), SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, StringToInt(), and RadarValues::Zero().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSampleLength()
void SetSampleLength (SSC::SongTagInfo & info)
References HHMMSSToSeconds(), Song::m_fMusicSampleLengthSeconds, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSampleStart()
void SetSampleStart (SSC::SongTagInfo & info)
References HHMMSSToSeconds(), Song::m_fMusicSampleStartSeconds, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSelectable()
void SetSelectable (SSC::SongTagInfo & info)
References EqualsNoCase(), LOG, Song::m_SelectionDisplay, SSC::SongTagInfo::params, SSC::SongTagInfo::path, Song::SHOW_ALWAYS, Song::SHOW_NEVER, SSC::SongTagInfo::song, StringToInt(), and RageLog::UserLog().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongBPMs()
void SetSongBPMs (SSC::SongTagInfo & info)
References SMLoader::GetSongTitle(), SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessBPMs(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongCombos()
void SetSongCombos (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessCombos(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongDelays()
void SetSongDelays (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SMLoader::ProcessDelays(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongFakes()
void SetSongFakes (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SMLoader::ProcessFakes(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongFilename()
void SetSongFilename (SSC::SongTagInfo & info)
References SSC::SongTagInfo::from_cache, Song::m_sSongFileName, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongLabels()
void SetSongLabels (SSC::SongTagInfo & info)
References SMLoader::GetSongTitle(), SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessLabels(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongScrolls()
void SetSongScrolls (SSC::SongTagInfo & info)
References SMLoader::GetSongTitle(), SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessScrolls(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongSpeeds()
void SetSongSpeeds (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SMLoader::ProcessSpeeds(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongStops()
void SetSongStops (SSC::SongTagInfo & info)
References SMLoader::GetSongTitle(), SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessStops(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongTickCounts()
void SetSongTickCounts (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SMLoader::ProcessTickcounts(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongTimeSignatures()
void SetSongTimeSignatures (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_SongTiming, SSC::SongTagInfo::params, SMLoader::ProcessTimeSignatures(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSongWarps()
void SetSongWarps (SSC::SongTagInfo & info)
References SMLoader::GetSongTitle(), SSC::SongTagInfo::loader, Song::m_fVersion, Song::m_SongTiming, SSC::SongTagInfo::params, SSCLoader::ProcessWarps(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsBPMs()
void SetStepsBPMs (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SMLoader::GetSongTitle(), SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessBPMs(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsCombos()
void SetStepsCombos (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessCombos(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsDelays()
void SetStepsDelays (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SMLoader::ProcessDelays(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsDisplayBPM()
void SetStepsDisplayBPM (SSC::StepsTagInfo & info)
References DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, min(), SSC::StepsTagInfo::params, Steps::SetDisplayBPM(), Steps::SetMaxBPM(), Steps::SetMinBPM(), SSC::StepsTagInfo::steps, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsFakes()
void SetStepsFakes (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SMLoader::ProcessFakes(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsLabels()
void SetStepsLabels (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SMLoader::GetSongTitle(), SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessLabels(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsMusic()
void SetStepsMusic (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::params, Steps::SetMusicFile(), and SSC::StepsTagInfo::steps.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsOffset()
void SetStepsOffset (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, TimingData::m_fBeat0OffsetInSeconds, Song::m_fVersion, SSC::StepsTagInfo::params, SSC::StepsTagInfo::song, StringToFloat(), SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsScrolls()
void SetStepsScrolls (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SMLoader::GetSongTitle(), SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessScrolls(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsSpeeds()
void SetStepsSpeeds (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SMLoader::ProcessSpeeds(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsStops()
void SetStepsStops (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SMLoader::GetSongTitle(), SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessStops(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsTickCounts()
void SetStepsTickCounts (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SMLoader::ProcessTickcounts(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsTimeSignatures()
void SetStepsTimeSignatures (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SMLoader::ProcessTimeSignatures(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsType()
void SetStepsType (SSC::StepsTagInfo & info)
References GAMEMAN, Steps::m_StepsType, Steps::m_StepsTypeStr, SSC::StepsTagInfo::params, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::steps, and GameManager::StringToStepsType().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsVersion()
void SetStepsVersion (SSC::StepsTagInfo & info)
References Song::m_fVersion, SSC::StepsTagInfo::params, SSC::StepsTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetStepsWarps()
void SetStepsWarps (SSC::StepsTagInfo & info)
References SSC::StepsTagInfo::for_load_edit, SMLoader::GetSongTitle(), SSC::StepsTagInfo::has_own_timing, SSC::StepsTagInfo::loader, Song::m_fVersion, SSC::StepsTagInfo::params, SSCLoader::ProcessWarps(), SSC::StepsTagInfo::song, SSC::StepsTagInfo::ssc_format, SSC::StepsTagInfo::timing, and VERSION_SPLIT_TIMING.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSubtitle()
void SetSubtitle (SSC::SongTagInfo & info)
References Song::m_sSubTitle, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetSubtitleTranslit()
void SetSubtitleTranslit (SSC::SongTagInfo & info)
References Song::m_sSubTitleTranslit, SSC::SongTagInfo::params, and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetTitle()
void SetTitle (SSC::SongTagInfo & info)
References SSC::SongTagInfo::loader, Song::m_sMainTitle, SSC::SongTagInfo::params, SMLoader::SetSongTitle(), and SSC::SongTagInfo::song.
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
SetVersion()
void SetVersion (SSC::SongTagInfo & info)
References Song::m_fVersion, SSC::SongTagInfo::params, SSC::SongTagInfo::song, and StringToFloat().
Referenced by ssc_parser_helper_t::ssc_parser_helper_t().
Variable Documentation
parser_helper
ssc_parser_helper_t parser_helper