Etterna: Steps Class Reference
Steps Class Reference
Holds note information for a Song.
#include <Steps.h>
Public Member Functions
Steps (Song *song)
Set up the Steps with initial values.
~Steps ()
Destroy the Steps that are no longer needed.
void CopyFrom (Steps *pSource, StepsType ntTo, float fMusicLengthSeconds)
void CreateBlank (StepsType ntTo)
void Compress () const
void Decompress () const
void Decompress ()
bool IsAnEdit () const
Determine if these steps were created by the autogenerator.
bool IsAPlayerEdit () const
Determine if this set of Steps is a player edit.
bool WasLoadedFromProfile () const
Determine if these steps were loaded from a player's profile.
ProfileSlot GetLoadedFromProfileSlot () const
RString GetDescription () const
Retrieve the description used for this edit.
RString GetChartStyle () const
Retrieve the ChartStyle used for this chart.
Difficulty GetDifficulty () const
Retrieve the difficulty used for this edit.
int GetMeter () const
Retrieve the meter used for this edit.
const RadarValues & GetRadarValues () const
RString GetCredit () const
Retrieve the author credit used for this edit.
RString GetChartName () const
void SetChartName (const RString &name)
void SetFilename (const RString &fn)
RString GetFilename () const
void SetSavedToDisk (bool b)
bool GetSavedToDisk () const
void SetDifficulty (Difficulty dc)
void SetDescription (const RString &sDescription)
void SetDifficultyAndDescription (Difficulty dc, const RString &sDescription)
void SetCredit (const RString &sCredit)
void SetChartStyle (const RString &sChartStyle)
void SetLoadedFromProfile (ProfileSlot slot)
void SetMeter (int meter)
void SetCachedRadarValues (const RadarValues &v)
float PredictMeter () const
unsigned GetHash () const
void GetNoteData (NoteData &noteDataOut) const
NoteData GetNoteData () const
void SetNoteData (const NoteData &noteDataNew)
void SetSMNoteData (const RString &notes_comp)
void GetSMNoteData (RString &notes_comp_out) const
bool GetNoteDataFromSimfile ()
Retrieve the NoteData from the original source.
bool IsNoteDataEmpty () const
Determine if we are missing any note data.
void GetETTNoteData (RString &notes_comp_out) const
void TidyUpData ()
void CalculateRadarValues (float fMusicLengthSeconds)
const TimingData * GetTimingData () const
Retrieves the appropriate timing data for the Steps. Falls back on the Song if needed.
TimingData * GetTimingData ()
const string & GetChartKey () const
void SetChartKey (const RString &k)
void SetAllMSD (const MinaSD &msd)
MinaSD GetAllMSD () const
map< float, Skillset > SortSkillsetsAtRate (float x, bool includeoverall)
void CalcEtternaMetadata ()
string GenerateBustedChartKey (NoteData &nd, TimingData *td, int cores)
void MakeBustedKeys ()
bool IsRecalcValid ()
float GetMSD (float x, int i) const
RString GenerateChartKey (NoteData &nd, TimingData *td)
void FillStringWithBPMs (size_t startRow, size_t endRow, vector< int > &nerv, NoteData &nd, TimingData *td, RString &inOut)
bool HasSignificantTimingChanges () const
Determine if the Steps have any major timing changes during gameplay.
bool HasAttacks () const
Determine if the Steps have any attacks.
const RString GetMusicPath () const
const RString & GetMusicFile () const
void SetMusicFile (const RString &file)
void PushSelf (lua_State *L)
void SetDisplayBPM (const DisplayBPM type)
DisplayBPM GetDisplayBPM () const
void SetMinBPM (const float f)
float GetMinBPM () const
void SetMaxBPM (const float f)
float GetMaxBPM () const
void GetDisplayBpms (DisplayBpms &addTo) const
Static Public Member Functions
static bool MakeValidEditDescription (RString &sPreferredDescription)
Public Attributes
TimingData m_Timing
The TimingData used by the Steps.
vector< float > thestuffs = { 0.f, 0.f, 0.f, 0.f, 0.f, 0.f, 0.f, 0.f }
MinaSD stuffnthings
vector< string > bustedkeys
float firstsecond = 0.f
float lastsecond = 0.f
StepsType m_StepsType
RString m_StepsTypeStr
The string form of the StepsType, for dealing with unrecognized styles.
Song * m_pSong
The Song these Steps are associated with.
CachedObject< Steps > m_CachedObject
Private Attributes
string ChartKey = ""
HiddenPtr< NoteData > m_pNoteData
bool m_bNoteDataIsFilled
RString m_sNoteDataCompressed
RString m_sFilename
The name of the file where these steps are stored.
bool m_bSavedToDisk
true if these Steps were loaded from or saved to disk.
RString m_MusicFile
allows the steps to specify their own music file.
ProfileSlot m_LoadedFromProfile
What profile was used? This is ProfileSlot_Invalid if not from a profile.
unsigned m_iHash
The hash of the steps. This is used only for Edit Steps.
RString m_sDescription
The name of the edit, or some other useful description. This used to also contain the step author's name.
RString m_sChartStyle
The style of the chart. (e.g. "Pad", "Keyboard")
Difficulty m_Difficulty
The difficulty that these steps are assigned to.
int m_iMeter
The numeric difficulty of the Steps, ranging from MIN_METER to MAX_METER.
RadarValues m_CachedRadarValues
The radar values used for each player.
bool m_bAreCachedRadarValuesJustLoaded
RString m_sCredit
The name of the person who created the Steps.
RString chartName
The name of the chart.
DisplayBPM displayBPMType
How is the BPM displayed for this chart?
float specifiedBPMMin
What is the minimum specified BPM?
float specifiedBPMMax
What is the maximum specified BPM? If this is a range, then min should not be equal to max.
Detailed Description
Holds note information for a Song.
A Song may have one or more Notes.
Constructor & Destructor Documentation
Steps()
Steps::Steps (Song * song)
Set up the Steps with initial values.
~Steps()
Steps::~Steps () default
Destroy the Steps that are no longer needed.
Member Function Documentation
CalcEtternaMetadata()
void Steps::CalcEtternaMetadata ()
References TimingData::BuildAndGetEtaner(), NoteData::BuildAndGetNerv(), ChartKey, firstsecond, GenerateBustedChartKey(), GenerateChartKey(), NoteData::GetNumTracks(), GetTimingData(), TimingData::HasWarps(), SongManager::keyconversionmap, lastsecond, m_pNoteData, MinaSDCalc(), NoteData::SerializeNoteData(), SONGMAN, stuffnthings, TimingData::UnsetEtaner(), NoteData::UnsetNerv(), and NoteData::UnsetSerializedNoteData().
CalculateRadarValues()
void Steps::CalculateRadarValues (float fMusicLengthSeconds)
References NoteDataUtil::CalculateRadarValues(), GAMESTATE, NoteData::GetNumTracks(), GetTimingData(), m_bAreCachedRadarValuesJustLoaded, m_CachedRadarValues, m_pNoteData, GameState::SetProcessedTimingData(), and RadarValues::Zero().
Referenced by CopyFrom().
Compress()
void Steps::Compress () const
References NoteDataUtil::GetSMNoteDataString(), NoteData::Init(), m_bNoteDataIsFilled, m_pNoteData, m_sFilename, and m_sNoteDataCompressed.
Referenced by SongManager::Cleanup(), DoInstalls(), GetSSCNoteData(), ScoreKeeperNormal::Load(), and ScoreManager::RecalculateSSRs().
CopyFrom()
void Steps::CopyFrom (Steps * pSource, StepsType ntTo, float fMusicLengthSeconds)
References CalculateRadarValues(), GAMEMAN, GetDescription(), GetDifficulty(), GetMeter(), GetNoteData(), GameManager::GetStepsTypeInfo(), StepsTypeInfo::iNumTracks, m_pSong, m_StepsType, m_StepsTypeStr, m_Timing, SetDescription(), SetDifficulty(), SetMeter(), SetNoteData(), NoteData::SetNumTracks(), and StepsTypeInfo::szName.
CreateBlank()
void Steps::CreateBlank (StepsType ntTo)
References GAMEMAN, GameManager::GetStepsTypeInfo(), StepsTypeInfo::iNumTracks, m_StepsType, m_StepsTypeStr, SetNoteData(), NoteData::SetNumTracks(), and StepsTypeInfo::szName.
Decompress() [1/2]
void Steps::Decompress () const
Referenced by Deserialize(), GetNoteData(), and GetSSCNoteData().
Decompress() [2/2]
void Steps::Decompress ()
References DifficultyToString(), GAMEMAN, GetNoteDataFromSimfile(), GetSMNoteData(), GameManager::GetStepsTypeInfo(), StepsTypeInfo::iNumTracks, NoteDataUtil::LoadFromSMNoteDataString(), LOG, m_bNoteDataIsFilled, m_Difficulty, m_pNoteData, m_sFilename, m_sNoteDataCompressed, m_StepsType, NoteData::SetNumTracks(), and RageLog::Warn().
FillStringWithBPMs()
void Steps::FillStringWithBPMs (size_t startRow, size_t endRow, vector< int > & nerv, NoteData & nd, TimingData * td, RString & inOut)
References f, TimingData::GetBPMAtRow(), NoteData::GetNumTracks(), NoteData::GetTapNote(), and TapNote::type.
Referenced by GenerateBustedChartKey(), and GenerateChartKey().
GenerateBustedChartKey()
string Steps::GenerateBustedChartKey (NoteData & nd, TimingData * td, int cores)
References BinaryToHex(), FillStringWithBPMs(), NoteData::GetNonEmptyRowVector(), CryptManager::GetSHA1ForString(), and min().
Referenced by CalcEtternaMetadata().
GenerateChartKey()
RString Steps::GenerateChartKey (NoteData & nd, TimingData * td)
References BinaryToHex(), FillStringWithBPMs(), NoteData::GetNonEmptyRowVector(), CryptManager::GetSHA1ForString(), and max().
Referenced by CalcEtternaMetadata().
GetAllMSD()
MinaSD Steps::GetAllMSD () const inline
References stuffnthings.
Referenced by GetETTNoteData(), GetSSCNoteData(), and SongCacheIndex::InsertSteps().
GetChartKey()
const string& Steps::GetChartKey () const inline
References ChartKey.
Referenced by SongCacheIndex::CacheSong(), DoInstalls(), StepsID::FromSteps(), Profile::GetBestGrade(), LunaSteps::GetChartKey(), GetETTNoteData(), GetSSCNoteData(), Profile::ImportScoresToEtterna(), SongCacheIndex::InsertSteps(), MusicWheelItem::RefreshGrades(), SMOProtocol::StartRequest(), NotesWriterSSC::Write(), and NotesWriterETT::Write().
GetChartName()
RString Steps::GetChartName () const inline
References chartName.
Referenced by LunaSteps::GetChartName(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), SongUtil::IsChartNameUnique(), SSCLoader::LoadNoteDataFromSimfile(), OptionRowHandlerListSteps::Reload(), and SongUtil::ValidateCurrentStepsChartName().
GetChartStyle()
RString Steps::GetChartStyle () const inline
Retrieve the ChartStyle used for this chart.
Returns
the description used for this chart.
References m_sChartStyle.
Referenced by GetETTNoteData(), GetSSCNoteData(), and SongCacheIndex::InsertSteps().
GetCredit()
RString Steps::GetCredit () const inline
Retrieve the author credit used for this edit.
Returns
the author credit used for this edit.
References m_sCredit.
Referenced by SongUtil::DeleteDuplicateSteps(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongUtil::GetSteps(), SongCacheIndex::InsertSteps(), SSCLoader::LoadNoteDataFromSimfile(), StepsDisplay::SetInternal(), and SongUtil::ValidateCurrentStepsCredit().
GetDescription()
RString Steps::GetDescription () const inline
Retrieve the description used for this edit.
Returns
the description used for this edit.
References m_sDescription.
Referenced by StepsUtil::CompareStepsPointersByDescription(), CopyFrom(), SongUtil::DeleteDuplicateSteps(), StepsID::FromSteps(), LunaGameState::GetCurrentStepsCredits(), NotesWriterSM::GetEditFileName(), NotesWriterSSC::GetEditFileName(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongUtil::GetSteps(), SongCacheIndex::InsertSteps(), SongUtil::IsEditDescriptionUnique(), OptionRowHandlerSteps::LoadInternal(), ScreenGameplay::LoadNextSong(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), OptionRowHandlerListSteps::Reload(), Serialize(), SetDifficulty(), StepsDisplay::SetInternal(), TidyUpData(), and SongUtil::ValidateCurrentStepsDescription().
GetDifficulty()
Difficulty Steps::GetDifficulty () const inline
Retrieve the difficulty used for this edit.
Returns
the difficulty used for this edit.
References m_Difficulty.
Referenced by ScreenSelectMusic::ChangeSteps(), StepsUtil::CompareNotesPointersByDifficulty(), CompareNotesPointersForExtra(), StepsUtil::CompareStepsPointersByTypeAndDifficulty(), CopyFrom(), Chart::FromKey(), StepsID::FromSteps(), SongUtil::GetClosestNotes(), LunaGameState::GetCurrentStepsCredits(), GetETTNoteData(), GameState::GetRankingFeats(), GetSMNotesTag(), SongManager::GetSongColor(), Profile::GetSongsActual(), Profile::GetSongsPossible(), GetSSCNoteData(), SongUtil::GetSteps(), SongUtil::GetStepsByDifficulty(), ScreenNetSelectMusic::HandleScreenMessage(), Song::HasEdits(), SongCacheIndex::InsertSteps(), Song::IsEditAlreadyLoaded(), SongUtil::IsEditDescriptionUnique(), SMLoader::LoadFromTokens(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), StepsCriteria::Matches(), ScoreKeeperNormal::OnNextSong(), ParseNoteData(), OptionRowHandlerListSteps::Reload(), SearchForDifficulty(), Serialize(), SetDescription(), SetDifficultyAndDescription(), DifficultyIcon::SetFromSteps(), StepsDisplay::SetFromSteps(), SongUtil::SortSongPointerArrayByStepsTypeAndMeter(), SMOProtocol::StartRequest(), StepsToCustomDifficulty(), TidyUpData(), and WriteDWINotesTag().
GetDisplayBPM()
DisplayBPM Steps::GetDisplayBPM () const inline
References displayBPMType.
Referenced by GetDisplayBpms(), GetETTNoteData(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), and LunaSteps::IsDisplayBpmRandom().
GetDisplayBpms()
void Steps::GetDisplayBpms (DisplayBpms & addTo) const
References DisplayBpms::Add(), DISPLAY_BPM_SPECIFIED, TimingData::GetActualBPM(), GetDisplayBPM(), GetMaxBPM(), GetMinBPM(), and GetTimingData().
Referenced by LunaSteps::GetDisplayBpms(), LunaSteps::IsDisplayBpmConstant(), and LunaSteps::IsDisplayBpmSecret().
GetETTNoteData()
void Steps::GetETTNoteData (RString & notes_comp_out) const
References NoteDataUtil::GetETTNoteDataString(), m_bNoteDataIsFilled, m_pNoteData, and m_sNoteDataCompressed.
Referenced by GetETTNoteData().
GetFilename()
RString Steps::GetFilename () const inline
References m_sFilename.
Referenced by BMSSongLoader::AddToSong(), GetNoteDataFromSimfile(), GetSSCNoteData(), and SongCacheIndex::InsertSteps().
GetHash()
unsigned Steps::GetHash () const
References GetHashForString(), NoteDataUtil::GetSMNoteDataString(), m_bNoteDataIsFilled, m_iHash, m_pNoteData, and m_sNoteDataCompressed.
Referenced by StepsID::FromSteps(), LunaSteps::GetHash(), SongUtil::GetSteps(), Song::IsEditAlreadyLoaded(), and Serialize().
GetLoadedFromProfileSlot()
ProfileSlot Steps::GetLoadedFromProfileSlot () const inline
References m_LoadedFromProfile.
Referenced by Song::FreeAllLoadedFromProfile(), Song::GetNumStepsLoadedFromProfile(), and Song::GetStepsLoadedFromProfile().
GetMaxBPM()
float Steps::GetMaxBPM () const inline
References specifiedBPMMax.
Referenced by GetDisplayBpms(), GetETTNoteData(), GetSSCNoteData(), HasSignificantTimingChanges(), and SongCacheIndex::InsertSteps().
GetMeter()
int Steps::GetMeter () const inline
Retrieve the meter used for this edit.
Returns
the meter used for this edit.
References m_iMeter.
Referenced by StepsUtil::CompareNotesPointersByMeter(), CopyFrom(), SongUtil::DeleteDuplicateSteps(), StageStats::GetAverageMeter(), GetETTNoteData(), SongManager::GetExtraStageInfo(), GetSMNotesTag(), SongManager::GetSongColor(), GetSSCNoteData(), SongUtil::GetSteps(), SongUtil::GetStepsByMeter(), SongCacheIndex::InsertSteps(), Song::IsEasy(), LoadFromKSFFile(), ScreenGameplay::LoadNextSong(), DWILoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), StepsCriteria::Matches(), OptionRowHandlerListSteps::Reload(), Serialize(), StepsDisplay::SetFromSteps(), SongUtil::SortSongPointerArrayByStepsTypeAndMeter(), SMOProtocol::StartRequest(), TidyUpData(), and WriteDWINotesTag().
GetMinBPM()
float Steps::GetMinBPM () const inline
References specifiedBPMMin.
Referenced by GetDisplayBpms(), GetETTNoteData(), GetSSCNoteData(), HasSignificantTimingChanges(), and SongCacheIndex::InsertSteps().
GetMSD()
float Steps::GetMSD (float x, int i) const
References f, lerp(), and stuffnthings.
Referenced by LunaSteps::GetMSD(), and LunaProfile::SortByDiff().
GetMusicFile()
const RString & Steps::GetMusicFile () const
References m_MusicFile.
Referenced by GameState::ForceOtherPlayersToCompatibleSteps(), GetETTNoteData(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), and SongUtil::ValidateCurrentStepsMusic().
GetMusicPath()
const RString Steps::GetMusicPath () const
References Song::GetSongAssetPath(), Song::GetSongDir(), m_MusicFile, m_pSong, and Song::m_sMusicFile.
Referenced by SongUtil::ValidateCurrentStepsMusic().
GetNoteData() [1/2]
void Steps::GetNoteData (NoteData & noteDataOut) const
References NoteData::ClearAll(), Decompress(), GAMEMAN, GameManager::GetStepsTypeInfo(), StepsTypeInfo::iNumTracks, m_bNoteDataIsFilled, m_pNoteData, m_StepsType, and NoteData::SetNumTracks().
Referenced by PlayerStageStats::CalcSSR(), GameState::CanSafelyEnterGameplay(), CopyFrom(), DoInstalls(), ScreenHowToPlay::Init(), ScoreKeeperNormal::Load(), ScreenGameplay::LoadNextSong(), KSFLoader::LoadNoteDataFromSimfile(), ScoreManager::RecalculateSSRs(), Serialize(), ScreenGameplay::SetupSong(), and WriteDWINotesField().
GetNoteData() [2/2]
NoteData Steps::GetNoteData () const
GetNoteDataFromSimfile()
bool Steps::GetNoteDataFromSimfile ()
Retrieve the NoteData from the original source.
Returns
true if successful, false for failure.
References GetExtension(), GetFilename(), KSFLoader::LoadNoteDataFromSimfile(), BMSLoader::LoadNoteDataFromSimfile(), DWILoader::LoadNoteDataFromSimfile(), OsuLoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), StdString::CStdStr< CT >::MakeLower(), and StdString::CStdStr< CT >::Replace().
Referenced by Decompress(), and ScreenGameplay::Init().
GetRadarValues()
const RadarValues& Steps::GetRadarValues () const inline
References m_CachedRadarValues.
Referenced by StepsUtil::CompareNotesPointersByRadarValues(), GetETTNoteData(), PaneDisplay::GetPaneTextAndLevel(), LunaSteps::GetRadarValues(), LunaSteps::GetRelevantRadars(), GetSMNotesTag(), GetSSCNoteData(), Profile::ImportScoresToEtterna(), SongCacheIndex::InsertSteps(), PlayerOptions::IsEasierForSongAndSteps(), LifeMeterTime::OnLoadSong(), ScoreManager::RecalculateSSRs(), and GrooveRadar::SetFromSteps().
GetSavedToDisk()
bool Steps::GetSavedToDisk () const inline
References m_bSavedToDisk.
GetSMNoteData()
void Steps::GetSMNoteData (RString & notes_comp_out) const
References NoteDataUtil::GetSMNoteDataString(), m_bNoteDataIsFilled, m_pNoteData, and m_sNoteDataCompressed.
Referenced by Decompress(), SongUtil::DeleteDuplicateSteps(), GetSMNotesTag(), and GetSSCNoteData().
GetTimingData() [1/2]
const TimingData * Steps::GetTimingData () const
Retrieves the appropriate timing data for the Steps. Falls back on the Song if needed.
References TimingData::empty(), m_pSong, Song::m_SongTiming, and m_Timing.
Referenced by CalcEtternaMetadata(), PlayerStageStats::CalcSSR(), CalculateRadarValues(), DoInstalls(), StageStats::FinalizeScores(), GetDisplayBpms(), PlayerState::GetDisplayedTiming(), GetTimingData(), LunaSteps::GetTimingData(), ArrowEffects::GetYOffset(), HasSignificantTimingChanges(), IsRecalcValid(), ScoreKeeperNormal::Load(), ScoreKeeperNormal::OnNextSong(), ScoreManager::RecalculateSSRs(), ETTProtocol::ReportHighScore(), and BPMDisplay::SetBpmFromSteps().
GetTimingData() [2/2]
TimingData* Steps::GetTimingData () inline
References GetTimingData().
HasAttacks()
bool Steps::HasAttacks () const
Determine if the Steps have any attacks.
Returns
true if it does, or false otherwise.
HasSignificantTimingChanges()
bool Steps::HasSignificantTimingChanges () const
Determine if the Steps have any major timing changes during gameplay.
Returns
true if it does, or false otherwise.
References GetMaxBPM(), GetMinBPM(), GetTimingData(), TimingData::HasBpmChanges(), TimingData::HasDelays(), TimingData::HasScrollChanges(), TimingData::HasSpeedChanges(), TimingData::HasStops(), and TimingData::HasWarps().
Referenced by PlayerOptions::IsEasierForSongAndSteps().
IsAnEdit()
bool Steps::IsAnEdit () const inline
Determine if these steps were created by the autogenerator.
Returns
true if they were, false otherwise. Determine if this set of Steps is an edit.
Edits have a special value of difficulty to make it easy to determine.
Returns
true if this is an edit, false otherwise.
References Difficulty_Edit, and m_Difficulty.
Referenced by IsAPlayerEdit(), OptionRowHandlerListSteps::Reload(), StepsDisplay::SetInternal(), SongUtil::ValidateCurrentEditStepsDescription(), and SongUtil::ValidateCurrentStepsDescription().
IsAPlayerEdit()
bool Steps::IsAPlayerEdit () const inline
Determine if this set of Steps is a player edit.
Player edits also have to be loaded from a player's profile slot, not the machine.
Returns
true if this is a player edit, false otherwise.
References IsAnEdit().
Referenced by PaneDisplay::GetPaneTextAndLevel().
IsNoteDataEmpty()
bool Steps::IsNoteDataEmpty () const
Determine if we are missing any note data.
This takes advantage of the fact that we usually compress our data.
Returns
true if our notedata is empty, false otherwise.
References m_bNoteDataIsFilled, and m_sNoteDataCompressed.
Referenced by ScreenGameplay::Init().
IsRecalcValid()
bool Steps::IsRecalcValid ()
References GetTimingData(), TimingData::HasWarps(), m_CachedRadarValues, m_StepsType, RadarCategory_Notes, and StepsType_dance_single.
Referenced by ScoreManager::RecalculateSSRs().
MakeBustedKeys()
void Steps::MakeBustedKeys ()
MakeValidEditDescription()
bool Steps::MakeValidEditDescription (RString & sPreferredDescription) static
References StdString::CStdStr< CT >::Left(), and MAX_STEPS_DESCRIPTION_LENGTH.
Referenced by SetDifficultyAndDescription().
PredictMeter()
float Steps::PredictMeter () const inline
PushSelf()
void Steps::PushSelf (lua_State * L)
Referenced by LunaSongManager::GetExtraStageInfo(), LunaGameCommand::GetSteps(), LunaSongManager::GetStepsByChartKey(), and LunaPlayerInfo::GetStepsQueueWrapped().
SetAllMSD()
void Steps::SetAllMSD (const MinaSD & msd) inline
Referenced by SetMSDValues(), and SongCacheIndex::SongFromStatement().
SetCachedRadarValues()
void Steps::SetCachedRadarValues (const RadarValues & v)
References m_bAreCachedRadarValuesJustLoaded, and m_CachedRadarValues.
Referenced by Deserialize(), SetRadarValues(), and SongCacheIndex::SongFromStatement().
SetChartKey()
void Steps::SetChartKey (const RString & k) inline
References ChartKey.
Referenced by SetChartKey(), and SongCacheIndex::SongFromStatement().
SetChartName()
void Steps::SetChartName (const RString & name) inline
References chartName.
Referenced by SMLoader::LoadFromTokens(), SetChartName(), SetDescription(), and SongCacheIndex::SongFromStatement().
SetChartStyle()
void Steps::SetChartStyle (const RString & sChartStyle)
References m_sChartStyle.
Referenced by SetChartStyle(), and SongCacheIndex::SongFromStatement().
SetCredit()
void Steps::SetCredit (const RString & sCredit)
References m_sCredit.
Referenced by SMLoader::LoadFromTokens(), BMSChartReader::ReadHeaders(), SetCredit(), and SongCacheIndex::SongFromStatement().
SetDescription()
void Steps::SetDescription (const RString & sDescription) inline
References GetDifficulty(), and SetDifficultyAndDescription().
Referenced by CopyFrom(), Deserialize(), LoadFromKSFFile(), SMLoader::LoadFromTokens(), SearchForDifficulty(), SetDescription(), and SongCacheIndex::SongFromStatement().
SetDifficulty()
void Steps::SetDifficulty (Difficulty dc) inline
References GetDescription(), and SetDifficultyAndDescription().
Referenced by BMSSongLoader::AddToSong(), CopyFrom(), Deserialize(), OsuLoader::LoadChartData(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), LoadFromDWITokens(), LoadFromKSFFile(), SMLoader::LoadFromTokens(), BMSChartReader::ReadHeaders(), SearchForDifficulty(), SetDifficulty(), SlideDuplicateDifficulties(), SongCacheIndex::SongFromStatement(), and TidyUpData().
SetDifficultyAndDescription()
void Steps::SetDifficultyAndDescription (Difficulty dc, const RString & sDescription)
References Difficulty_Edit, GetDifficulty(), m_Difficulty, m_sDescription, and MakeValidEditDescription().
Referenced by SetDescription(), and SetDifficulty().
SetDisplayBPM()
void Steps::SetDisplayBPM (const DisplayBPM type) inline
References displayBPMType.
Referenced by Song::InitSteps(), SetStepsDisplayBPM(), and SongCacheIndex::SongFromStatement().
SetFilename()
void Steps::SetFilename (const RString & fn) inline
References m_sFilename.
Referenced by Song::GetStepsToSave(), BMSSongLoader::Load(), SMLoader::LoadEditFromMsd(), SSCLoader::LoadEditFromMsd(), KSFLoader::LoadFromDir(), DWILoader::LoadFromDir(), OsuLoader::LoadFromDir(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), and SongCacheIndex::SongFromStatement().
SetLoadedFromProfile()
void Steps::SetLoadedFromProfile (ProfileSlot slot) inline
References m_LoadedFromProfile.
Referenced by SMLoader::LoadEditFromMsd(), and SSCLoader::LoadEditFromMsd().
SetMaxBPM()
void Steps::SetMaxBPM (const float f) inline
References f, and specifiedBPMMax.
Referenced by Song::InitSteps(), SetStepsDisplayBPM(), and SongCacheIndex::SongFromStatement().
SetMeter()
void Steps::SetMeter (int meter)
References m_iMeter.
Referenced by CopyFrom(), Deserialize(), OsuLoader::LoadChartData(), LoadFromDWITokens(), LoadFromKSFFile(), SMLoader::LoadFromTokens(), BMSChartReader::ReadHeaders(), SetMeter(), SongCacheIndex::SongFromStatement(), and TidyUpData().
SetMinBPM()
void Steps::SetMinBPM (const float f) inline
References f, and specifiedBPMMin.
Referenced by Song::InitSteps(), SetStepsDisplayBPM(), and SongCacheIndex::SongFromStatement().
SetMusicFile()
void Steps::SetMusicFile (const RString & file)
References m_MusicFile.
Referenced by BMSChartReader::ReadHeaders(), SetStepsMusic(), SongCacheIndex::SongFromStatement(), and SongUtil::ValidateCurrentStepsMusic().
SetNoteData()
void Steps::SetNoteData (const NoteData & noteDataNew)
References ASSERT, GAMEMAN, NoteData::GetNumTracks(), GameManager::GetStepsTypeInfo(), StepsTypeInfo::iNumTracks, m_bNoteDataIsFilled, m_iHash, m_pNoteData, m_sNoteDataCompressed, and m_StepsType.
Referenced by CopyFrom(), CreateBlank(), Deserialize(), LoadFromDWITokens(), LoadFromKSFFile(), OsuLoader::LoadNoteDataFromParsedData(), KSFLoader::LoadNoteDataFromSimfile(), DWILoader::LoadNoteDataFromSimfile(), and BMSChartReader::ReadNoteData().
SetSavedToDisk()
void Steps::SetSavedToDisk (bool b) inline
References m_bSavedToDisk.
Referenced by OsuLoader::LoadChartData(), LoadFromDWITokens(), LoadFromKSFFile(), SMLoader::LoadFromTokens(), and BMSChartReader::ReadNoteData().
SetSMNoteData()
void Steps::SetSMNoteData (const RString & notes_comp)
References NoteData::Init(), m_bNoteDataIsFilled, m_iHash, m_pNoteData, and m_sNoteDataCompressed.
Referenced by SSCLoader::LoadEditFromMsd(), SSCLoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), SMLoader::LoadNoteDataFromSimfile(), and SSCLoader::LoadNoteDataFromSimfile().
SortSkillsetsAtRate()
map< float, Skillset > Steps::SortSkillsetsAtRate (float x, bool includeoverall)
References FOREACH_ENUM, Skill_Overall, and stuffnthings.
Referenced by LunaSteps::GetRelevantSkillsetsByMSDRank().
TidyUpData()
void Steps::TidyUpData ()
References Difficulty_Beginner, Difficulty_Easy, Difficulty_Hard, Difficulty_Invalid, Difficulty_Medium, GAMEMAN, GetDescription(), GetDifficulty(), GetMeter(), GameManager::GetStepsTypeInfo(), LOG, m_pSong, Song::m_sSongFileName, m_StepsType, m_StepsTypeStr, SetDifficulty(), SetMeter(), StepsType_Invalid, StringToDifficulty(), StepsTypeInfo::szName, and RageLog::Warn().
Referenced by OsuLoader::LoadChartData(), SSCLoader::LoadEditFromMsd(), LoadFromDWITokens(), LoadFromKSFFile(), SSCLoader::LoadFromSimfile(), SMLoader::LoadFromTokens(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), BMSChartReader::ReadNoteData(), and SongCacheIndex::SongFromStatement().
WasLoadedFromProfile()
bool Steps::WasLoadedFromProfile () const inline
Determine if these steps were loaded from a player's profile.
Returns
true if they were from a player profile, false otherwise.
References m_LoadedFromProfile, and ProfileSlot_Invalid.
Referenced by DoInstalls(), Song::FreeAllLoadedFromProfile(), and Song::GetStepsToSave().
Member Data Documentation
bustedkeys
vector<string> Steps::bustedkeys
ChartKey
string Steps::ChartKey = "" private
Referenced by CalcEtternaMetadata(), GetChartKey(), and SetChartKey().
chartName
RString Steps::chartName private
The name of the chart.
Referenced by GetChartName(), and SetChartName().
displayBPMType
DisplayBPM Steps::displayBPMType private
How is the BPM displayed for this chart?
Referenced by GetDisplayBPM(), and SetDisplayBPM().
firstsecond
float Steps::firstsecond = 0.f
Referenced by CalcEtternaMetadata().
lastsecond
float Steps::lastsecond = 0.f
Referenced by CalcEtternaMetadata().
m_bAreCachedRadarValuesJustLoaded
bool Steps::m_bAreCachedRadarValuesJustLoaded private
Referenced by CalculateRadarValues(), and SetCachedRadarValues().
m_bNoteDataIsFilled
bool Steps::m_bNoteDataIsFilled mutable private
Referenced by Compress(), Decompress(), GetETTNoteData(), GetHash(), GetNoteData(), GetSMNoteData(), IsNoteDataEmpty(), SetNoteData(), and SetSMNoteData().
m_bSavedToDisk
bool Steps::m_bSavedToDisk private
true if these Steps were loaded from or saved to disk.
Referenced by GetSavedToDisk(), and SetSavedToDisk().
m_CachedObject
CachedObject<Steps> Steps::m_CachedObject
m_CachedRadarValues
RadarValues Steps::m_CachedRadarValues private
The radar values used for each player.
Referenced by CalculateRadarValues(), GetRadarValues(), IsRecalcValid(), and SetCachedRadarValues().
m_Difficulty
Difficulty Steps::m_Difficulty private
The difficulty that these steps are assigned to.
Referenced by Decompress(), GetDifficulty(), IsAnEdit(), and SetDifficultyAndDescription().
m_iHash
unsigned Steps::m_iHash mutable private
The hash of the steps. This is used only for Edit Steps.
Referenced by GetHash(), SetNoteData(), and SetSMNoteData().
m_iMeter
int Steps::m_iMeter private
The numeric difficulty of the Steps, ranging from MIN_METER to MAX_METER.
Referenced by GetMeter(), and SetMeter().
m_LoadedFromProfile
ProfileSlot Steps::m_LoadedFromProfile private
What profile was used? This is ProfileSlot_Invalid if not from a profile.
Referenced by GetLoadedFromProfileSlot(), SetLoadedFromProfile(), and WasLoadedFromProfile().
m_MusicFile
RString Steps::m_MusicFile private
allows the steps to specify their own music file.
Referenced by GetMusicFile(), GetMusicPath(), and SetMusicFile().
m_pNoteData
HiddenPtr<NoteData> Steps::m_pNoteData mutable private
Referenced by CalcEtternaMetadata(), CalculateRadarValues(), Compress(), Decompress(), GetETTNoteData(), GetHash(), GetNoteData(), GetSMNoteData(), SetNoteData(), and SetSMNoteData().
m_pSong
Song* Steps::m_pSong
The Song these Steps are associated with.
Referenced by GameState::CanSafelyEnterGameplay(), CopyFrom(), SongManager::DeleteSteps(), GetMusicPath(), LunaSongManager::GetSongFromSteps(), GetTimingData(), OsuLoader::LoadNoteDataFromParsedData(), BMSLoader::LoadNoteDataFromSimfile(), TidyUpData(), and SongUtil::ValidateCurrentEditStepsDescription().
m_sChartStyle
RString Steps::m_sChartStyle private
The style of the chart. (e.g. "Pad", "Keyboard")
Referenced by GetChartStyle(), and SetChartStyle().
m_sCredit
RString Steps::m_sCredit private
The name of the person who created the Steps.
Referenced by GetCredit(), and SetCredit().
m_sDescription
RString Steps::m_sDescription private
The name of the edit, or some other useful description. This used to also contain the step author's name.
Referenced by GetDescription(), and SetDifficultyAndDescription().
m_sFilename
RString Steps::m_sFilename private
The name of the file where these steps are stored.
Referenced by Compress(), Decompress(), GetFilename(), and SetFilename().
m_sNoteDataCompressed
RString Steps::m_sNoteDataCompressed mutable private
Referenced by Compress(), Decompress(), GetETTNoteData(), GetHash(), GetSMNoteData(), IsNoteDataEmpty(), SetNoteData(), and SetSMNoteData().
m_StepsType
StepsType Steps::m_StepsType
Referenced by Song::AddSteps(), BMSSongLoader::AddToSong(), BMSChartReader::CalculateStepsType(), GameState::CanSafelyEnterGameplay(), ScreenSelectMusic::ChangeSteps(), StepsUtil::CompareStepsPointersByTypeAndDifficulty(), CopyFrom(), CreateBlank(), Decompress(), Song::DeleteSteps(), Deserialize(), GameState::ForceOtherPlayersToCompatibleSteps(), StepsID::FromSteps(), LunaGameState::GetCurrentStepsCredits(), NotesWriterSM::GetEditFileName(), NotesWriterSSC::GetEditFileName(), GetNoteData(), Profile::GetSongsActual(), Profile::GetSongsPossible(), Song::HasEdits(), ScreenGameplay::InitSongQueues(), SongUtil::IsChartNameUnique(), Song::IsEditAlreadyLoaded(), SongUtil::IsEditDescriptionUnique(), IsRecalcValid(), ScoreKeeperNormal::Load(), OsuLoader::LoadChartData(), DWILoader::LoadFromDir(), LoadFromDWITokens(), LoadFromKSFFile(), SMLoader::LoadFromTokens(), DWILoader::LoadNoteDataFromSimfile(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), StepsCriteria::Matches(), ParseNoteData(), BMSChartReader::ReadNoteData(), OptionRowHandlerListSteps::Reload(), Serialize(), LunaGameState::SetCurrentSteps(), StepsDisplay::SetFromSteps(), SetNoteData(), SetStepsType(), SongCacheIndex::SongFromStatement(), StepsToCustomDifficulty(), TidyUpData(), SongUtil::ValidateCurrentStepsChartName(), NotesWriterDWI::Write(), WriteDWINotesField(), and WriteDWINotesTag().
m_StepsTypeStr
RString Steps::m_StepsTypeStr
The string form of the StepsType, for dealing with unrecognized styles.
Referenced by BMSChartReader::CalculateStepsType(), CopyFrom(), CreateBlank(), GetETTNoteData(), GetSMNotesTag(), GetSSCNoteData(), SongCacheIndex::InsertSteps(), SMLoader::LoadFromTokens(), SetStepsType(), SongCacheIndex::SongFromStatement(), and TidyUpData().
m_Timing
TimingData Steps::m_Timing
The TimingData used by the Steps.
This is required to allow Split Timing.
Referenced by BMSSongLoader::AddToSong(), CopyFrom(), GetETTNoteData(), GetSSCNoteData(), GetTimingData(), ScreenHowToPlay::Init(), SongCacheIndex::InsertSteps(), Song::IsStepsUsingDifferentTiming(), SSCLoader::LoadEditFromMsd(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), BMSChartReader::ReadHeaders(), BMSChartReader::ReadNoteData(), and SongCacheIndex::SongFromStatement().
specifiedBPMMax
float Steps::specifiedBPMMax private
What is the maximum specified BPM? If this is a range, then min should not be equal to max.
Referenced by GetMaxBPM(), and SetMaxBPM().
specifiedBPMMin
float Steps::specifiedBPMMin private
What is the minimum specified BPM?
Referenced by GetMinBPM(), and SetMinBPM().
stuffnthings
MinaSD Steps::stuffnthings
Initial value:
= { thestuffs, thestuffs, thestuffs, thestuffs,
                            thestuffs, thestuffs, thestuffs, thestuffs,
                            thestuffs, thestuffs, thestuffs, thestuffs,
                            thestuffs, thestuffs, thestuffs, thestuffs,
                            thestuffs, thestuffs, thestuffs, thestuffs,
                            thestuffs }
Referenced by CalcEtternaMetadata(), GetAllMSD(), GetMSD(), and SortSkillsetsAtRate().
thestuffs
vector<float> Steps::thestuffs = { 0.f, 0.f, 0.f, 0.f, 0.f, 0.f, 0.f, 0.f }
The documentation for this class was generated from the following files:
Steps.h
Steps.cpp