Etterna: ScoreKeeperNormal Class Reference
ScoreKeeperNormal Class Reference
The default ScoreKeeper implementation.
#include <ScoreKeeperNormal.h>
Public Member Functions
ScoreKeeperNormal (PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
void Load (const vector< Song *> &apSongs, const vector< Steps *> &apSteps) override
void OnNextSong (int iSongInCourseIndex, const Steps *pSteps, const NoteData *pNoteData) override
void HandleTapScore (const TapNote &tn) override
void HandleTapRowScore (const NoteData &nd, int iRow) override
void HandleHoldScore (const TapNote &tn) override
void HandleHoldActiveSeconds (float) override
void HandleHoldCheckpointScore (const NoteData &nd, int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow) override
void HandleTapScoreNone () override
int TapNoteScoreToDancePoints (TapNoteScore tns) const
int HoldNoteScoreToDancePoints (HoldNoteScore hns) const
int TapNoteScoreToGradePoints (TapNoteScore tns) const
int HoldNoteScoreToGradePoints (HoldNoteScore hns) const
Public Member Functions inherited from ScoreKeeper
ScoreKeeper (PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
virtual ~ScoreKeeper ()=default
virtual void DrawPrimitives ()
virtual void Update (float)
Static Public Member Functions
static int GetPossibleDancePoints (NoteData *nd, const TimingData *td, float fSongSeconds)
static int GetPossibleDancePoints (NoteData *ndPre, NoteData *ndPost, const TimingData *td, float fSongSeconds)
static int GetPossibleGradePoints (NoteData *nd, const TimingData *td, float fSongSeconds)
static int GetPossibleGradePoints (NoteData *ndPre, NoteData *ndPost, const TimingData *td, float fSongSeconds)
static int TapNoteScoreToDancePoints (TapNoteScore tns, bool bBeginner)
static int HoldNoteScoreToDancePoints (HoldNoteScore hns, bool bBeginner)
static int TapNoteScoreToGradePoints (TapNoteScore tns, bool bBeginner)
static int HoldNoteScoreToGradePoints (HoldNoteScore hns, bool bBeginner)
Static Public Member Functions inherited from ScoreKeeper
static ScoreKeeper * MakeScoreKeeper (const RString &sClassName, PlayerState *pPlayerState, PlayerStageStats *pPlayerStageStats)
Private Member Functions
void AddScoreInternal (TapNoteScore score)
int CalcNextToastyAt (int level)
virtual void AddTapScore (TapNoteScore tns)
virtual void AddHoldScore (HoldNoteScore hns)
virtual void AddTapRowScore (TapNoteScore tns, const NoteData &nd, int iRow)
void HandleTapNoteScoreInternal (const NoteData &nd, TapNoteScore tns, TapNoteScore maximum, int row, bool separately)
Take care of some internal work with our scoring systems.
void HandleComboInternal (int iNumHitContinueCombo, int iNumHitMaintainCombo, int iNumBreakCombo, int iRow=-1)
void HandleRowComboInternal (TapNoteScore tns, int iNumTapsInRow, int iRow=-1)
void GetRowCounts (const NoteData &nd, int iRow, int &iNumHitContinueCombo, int &iNumHitMaintainCombo, int &iNumBreakCombo)
Private Attributes
int m_iScoreRemainder
int m_iMaxPossiblePoints
int m_iTapNotesHit
int m_iNumTapsAndHolds
int m_iMaxScoreSoFar
int m_iPointBonus
int m_cur_toasty_combo
int m_cur_toasty_level
int m_next_toasty_at
bool m_bIsLastSongInCourse
bool m_bIsBeginner
int m_iNumNotesHitThisRow
ThemeMetric< bool > m_ComboIsPerRow
ThemeMetric< bool > m_MissComboIsPerRow
ThemeMetric< TapNoteScore > m_MinScoreToContinueCombo
ThemeMetric< TapNoteScore > m_MinScoreToMaintainCombo
ThemeMetric< TapNoteScore > m_MaxScoreToIncrementMissCombo
ThemeMetric< bool > m_MineHitIncrementsMissCombo
ThemeMetric< bool > m_AvoidMineIncrementsCombo
ThemeMetric< bool > m_UseInternalScoring
ThemeMetric< TapNoteScore > m_toasty_min_tns
ThemeMetric< LuaReference > m_toasty_trigger
vector< Steps * > m_apSteps
int m_lroundTo
int m_ComboBonusFactor [NUM_TapNoteScore]
Additional Inherited Members
Protected Member Functions inherited from ScoreKeeper
void GetScoreOfLastTapInRow (const NoteData &nd, int iRow, TapNoteScore &tnsOut, int &iNumTapsInRowOut)
Protected Attributes inherited from ScoreKeeper
PlayerState * m_pPlayerState
PlayerStageStats * m_pPlayerStageStats
Detailed Description
The default ScoreKeeper implementation.
Constructor & Destructor Documentation
ScoreKeeperNormal()
ScoreKeeperNormal::ScoreKeeperNormal (PlayerState * pPlayerState, PlayerStageStats * pPlayerStageStats)
Member Function Documentation
AddHoldScore()
void ScoreKeeperNormal::AddHoldScore (HoldNoteScore hns) private virtual
References AddScoreInternal(), HNS_Held, HNS_LetGo, TNS_W1, and TNS_W4.
Referenced by HandleHoldScore().
AddScoreInternal()
void ScoreKeeperNormal::AddScoreInternal (TapNoteScore score) private
References GAMESTATE, GetScore(), PlayerStageStats::m_bFailed, m_bIsLastSongInCourse, m_ComboBonusFactor, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMaxScore, m_iMaxPossiblePoints, m_iMaxScoreSoFar, m_iNumTapsAndHolds, m_iPointBonus, PlayerStageStats::m_iScore, m_iScoreRemainder, m_iTapNotesHit, m_lroundTo, ScoreKeeper::m_pPlayerStageStats, m_UseInternalScoring, GameState::ShowW1(), TNS_W1, TNS_W2, and TNS_W3.
Referenced by AddHoldScore(), and AddTapRowScore().
AddTapRowScore()
void ScoreKeeperNormal::AddTapRowScore (TapNoteScore tns, const NoteData & nd, int iRow) private virtual
References AddScoreInternal().
Referenced by HandleTapRowScore().
AddTapScore()
void ScoreKeeperNormal::AddTapScore (TapNoteScore tns) private virtual
Referenced by HandleTapScore().
CalcNextToastyAt()
int ScoreKeeperNormal::CalcNextToastyAt (int level) private
References LuaManager::Get(), L, LUA, m_next_toasty_at, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerState, m_toasty_trigger, LuaHelpers::Push(), ThemeMetric< T >::PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptError(), and LuaHelpers::RunScriptOnStack().
Referenced by HandleTapRowScore(), and Load().
GetPossibleDancePoints() [1/2]
int ScoreKeeperNormal::GetPossibleDancePoints (NoteData * nd, const TimingData * td, float fSongSeconds) static
References NoteDataUtil::CalculateRadarValues(), GameState::CountNotesSeparately(), g_iPercentScoreWeight, GAMESTATE, GameState::GetCurrentGame(), NoteData::GetNumTracksLCD(), NoteDataUtil::GetTotalHoldTicks(), HNS_Held, HoldNoteScoreToDancePoints(), Game::m_bTickHolds, RadarCategory_Holds, RadarCategory_Rolls, RadarCategory_TapsAndHolds, SE_CheckpointHit, TapNoteScoreToDancePoints(), and TNS_W1.
Referenced by GetPossibleDancePoints(), and Load().
GetPossibleDancePoints() [2/2]
int ScoreKeeperNormal::GetPossibleDancePoints (NoteData * ndPre, NoteData * ndPost, const TimingData * td, float fSongSeconds) static
References GetPossibleDancePoints(), and max().
GetPossibleGradePoints() [1/2]
int ScoreKeeperNormal::GetPossibleGradePoints (NoteData * nd, const TimingData * td, float fSongSeconds) static
References NoteDataUtil::CalculateRadarValues(), g_iGradeWeight, GAMESTATE, GameState::GetCurrentGame(), NoteDataUtil::GetTotalHoldTicks(), HNS_Held, HoldNoteScoreToGradePoints(), Game::m_bTickHolds, RadarCategory_Holds, RadarCategory_Rolls, RadarCategory_TapsAndHolds, SE_CheckpointHit, TapNoteScoreToGradePoints(), and TNS_W1.
Referenced by GetPossibleGradePoints(), and Load().
GetPossibleGradePoints() [2/2]
int ScoreKeeperNormal::GetPossibleGradePoints (NoteData * ndPre, NoteData * ndPost, const TimingData * td, float fSongSeconds) static
References GetPossibleGradePoints(), and max().
GetRowCounts()
void ScoreKeeperNormal::GetRowCounts (const NoteData & nd, int iRow, int & iNumHitContinueCombo, int & iNumHitMaintainCombo, int & iNumBreakCombo) private
References NoteData::GetNumTracks(), NoteData::GetTapNote(), m_MinScoreToContinueCombo, m_MinScoreToMaintainCombo, TapNote::result, TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Tap, TapNoteResult::tns, TNS_None, and TapNote::type.
Referenced by HandleTapRowScore().
HandleComboInternal()
void ScoreKeeperNormal::HandleComboInternal (int iNumHitContinueCombo, int iNumHitMaintainCombo, int iNumBreakCombo, int iRow = -1) private
References GAMESTATE, m_ComboIsPerRow, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, m_MissComboIsPerRow, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, and min().
Referenced by HandleHoldCheckpointScore(), HandleTapRowScore(), and HandleTapScore().
HandleHoldActiveSeconds()
void ScoreKeeperNormal::HandleHoldActiveSeconds (float) inline override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
Referenced by ScoreKeeperShared::HandleHoldActiveSeconds().
HandleHoldCheckpointScore()
void ScoreKeeperNormal::HandleHoldCheckpointScore (const NoteData & nd, int iRow, int iNumHoldsHeldThisRow, int iNumHoldsMissedThisRow) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References GameState::CountNotesSeparately(), GAMESTATE, HandleComboInternal(), HandleTapNoteScoreInternal(), TNS_CheckpointHit, and TNS_CheckpointMiss.
Referenced by ScoreKeeperShared::HandleHoldCheckpointScore().
HandleHoldScore()
void ScoreKeeperNormal::HandleHoldScore (const TapNote & tn) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References AddHoldScore(), MessageManager::Broadcast(), TapNoteResult::fTapNoteOffset, HoldNoteResult::hns, HNS_Held, HoldNoteScoreToDancePoints(), TapNote::HoldResult, PlayerStageStats::m_bFailed, PlayerStageStats::m_iActualDancePoints, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurPossibleDancePoints, PlayerStageStats::m_iHoldNoteScores, PlayerStageStats::m_iScore, PlayerState::m_mp, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, MESSAGEMAN, NSMAN, NetworkSyncManager::ReportScore(), TapNote::result, Message::SetParam(), and TapNoteScore_Invalid.
Referenced by ScoreKeeperShared::HandleHoldScore().
HandleRowComboInternal()
void ScoreKeeperNormal::HandleRowComboInternal (TapNoteScore tns, int iNumTapsInRow, int iRow = -1) private
References GAMESTATE, m_ComboIsPerRow, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iCurMissCombo, m_MaxScoreToIncrementMissCombo, m_MinScoreToContinueCombo, m_MinScoreToMaintainCombo, m_MissComboIsPerRow, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, and min().
Referenced by HandleTapRowScore().
HandleTapNoteScoreInternal()
void ScoreKeeperNormal::HandleTapNoteScoreInternal (const NoteData & nd, TapNoteScore tns, TapNoteScore maximum, int row, bool separately) private
Take care of some internal work with our scoring systems.
Parameters
tns the Tap Note score earned.
maximum the best tap note score possible.
row the row the score was earned. Mainly for ComboSegment stuff.
References GameState::CountNotesSeparately(), GAMESTATE, ComboSegment::GetCombo(), ComboSegment::GetMissCombo(), NoteData::GetNumTracks(), NoteData::GetNumTracksLCD(), NoteData::GetTapNote(), TapNote::IsNote(), PlayerStageStats::m_bFailed, PlayerStageStats::m_iActualDancePoints, PlayerStageStats::m_iCurPossibleDancePoints, PlayerStageStats::m_iTapNoteScores, m_MinScoreToContinueCombo, m_MinScoreToMaintainCombo, GameState::m_pCurSteps, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, TapNoteScoreToDancePoints(), TNS_CheckpointHit, and TNS_CheckpointMiss.
Referenced by HandleHoldCheckpointScore(), and HandleTapRowScore().
HandleTapRowScore()
void ScoreKeeperNormal::HandleTapRowScore (const NoteData & nd, int iRow) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References AddTapRowScore(), MessageManager::Broadcast(), CalcNextToastyAt(), GameState::CountNotesSeparately(), enum_add2(), TapNoteResult::fTapNoteOffset, GAMESTATE, ModsGroup< T >::GetCurrent(), GetRowCounts(), HandleComboInternal(), HandleRowComboInternal(), HandleTapNoteScoreInternal(), ProfileManager::IncrementToastiesCount(), NoteDataWithScoring::LastTapNoteWithResult(), GamePreferences::m_AutoPlay, GameState::m_bDemonstrationOrJukebox, m_cur_toasty_combo, m_cur_toasty_level, PlayerOptions::m_fPlayerAutoPlay, PlayerStageStats::m_iCurCombo, m_iNumNotesHitThisRow, PlayerStageStats::m_iScore, PlayerState::m_mp, m_next_toasty_at, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, m_toasty_min_tns, Message_CurrentComboChangedP1, MESSAGEMAN, min(), NSMAN, PC_HUMAN, PC_REPLAY, PLAYER_INVALID, ScreenManager::PostMessageToTopScreen(), PROFILEMAN, NetworkSyncManager::ReportScore(), TapNote::result, SCREENMAN, Message::SetParam(), TapNoteType_Lift, TapNoteResult::tns, TNS_W1, and TapNote::type.
Referenced by ScoreKeeperShared::HandleTapRowScore().
HandleTapScore()
void ScoreKeeperNormal::HandleTapScore (const TapNote & tn) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References AddTapScore(), MessageManager::Broadcast(), TapNoteResult::fTapNoteOffset, HandleComboInternal(), m_AvoidMineIncrementsCombo, PlayerStageStats::m_bFailed, PlayerStageStats::m_iActualDancePoints, PlayerStageStats::m_iCurCombo, PlayerStageStats::m_iScore, PlayerStageStats::m_iTapNoteScores, m_MineHitIncrementsMissCombo, PlayerState::m_mp, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, MESSAGEMAN, NSMAN, NetworkSyncManager::ReportScore(), TapNote::result, Message::SetParam(), TapNoteScoreToDancePoints(), TapNoteType_Mine, TapNoteResult::tns, TNS_AvoidMine, TNS_HitMine, and TapNote::type.
Referenced by ScoreKeeperShared::HandleTapScore().
HandleTapScoreNone()
void ScoreKeeperNormal::HandleTapScoreNone () override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References MessageManager::Broadcast(), enum_add2(), PlayerStageStats::m_iCurCombo, PlayerState::m_PlayerNumber, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, Message_CurrentComboChangedP1, MESSAGEMAN, and PLAYER_INVALID.
Referenced by ScoreKeeperShared::HandleTapScoreNone().
HoldNoteScoreToDancePoints() [1/2]
int ScoreKeeperNormal::HoldNoteScoreToDancePoints (HoldNoteScore hns) const
References m_bIsBeginner.
Referenced by GetPossibleDancePoints(), and HandleHoldScore().
HoldNoteScoreToDancePoints() [2/2]
int ScoreKeeperNormal::HoldNoteScoreToDancePoints (HoldNoteScore hns, bool bBeginner) static
References DEFAULT_FAIL, g_iPercentScoreWeight, HNS_Held, HNS_LetGo, HNS_Missed, HNS_None, SE_Held, SE_LetGo, and SE_Missed.
HoldNoteScoreToGradePoints() [1/2]
int ScoreKeeperNormal::HoldNoteScoreToGradePoints (HoldNoteScore hns) const
References m_bIsBeginner.
Referenced by PlayerStageStats::GetGrade(), and GetPossibleGradePoints().
HoldNoteScoreToGradePoints() [2/2]
int ScoreKeeperNormal::HoldNoteScoreToGradePoints (HoldNoteScore hns, bool bBeginner) static
References DEFAULT_FAIL, g_iGradeWeight, HNS_Held, HNS_LetGo, HNS_Missed, HNS_None, SE_Held, SE_LetGo, and SE_Missed.
Load()
void ScoreKeeperNormal::Load (const vector< Song *> & apSongs, const vector< Steps *> & apSteps) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References ASSERT, MessageManager::Broadcast(), CalcNextToastyAt(), Steps::Compress(), GAMESTATE, GameState::GetCurrentStyle(), Steps::GetNoteData(), GetPossibleDancePoints(), GetPossibleGradePoints(), ModsGroup< T >::GetStage(), Steps::GetTimingData(), Style::GetTransformedNoteDataForStyle(), ThemeMetric< T >::Load(), m_apSteps, m_AvoidMineIncrementsCombo, m_bIsLastSongInCourse, m_ComboBonusFactor, m_ComboIsPerRow, m_cur_toasty_combo, m_cur_toasty_level, Song::m_fMusicLengthSeconds, m_iMaxScoreSoFar, m_iNumNotesHitThisRow, m_iNumTapsAndHolds, m_iPointBonus, PlayerStageStats::m_iPossibleDancePoints, PlayerStageStats::m_iPossibleGradePoints, m_iScoreRemainder, m_lroundTo, m_MaxScoreToIncrementMissCombo, m_MineHitIncrementsMissCombo, m_MinScoreToContinueCombo, m_MinScoreToMaintainCombo, m_MissComboIsPerRow, PlayerState::m_mp, m_next_toasty_at, PlayerState::m_PlayerNumber, PlayerState::m_PlayerOptions, ScoreKeeper::m_pPlayerStageStats, ScoreKeeper::m_pPlayerState, Steps::m_StepsType, m_toasty_min_tns, m_toasty_trigger, m_UseInternalScoring, MESSAGEMAN, Message::SetParam(), GameState::SetProcessedTimingData(), and NoteDataUtil::TransformNoteData().
Referenced by ScoreKeeperShared::Load().
OnNextSong()
void ScoreKeeperNormal::OnNextSong (int iSongInCourseIndex, const Steps * pSteps, const NoteData * pNoteData) override virtual
Reimplemented from ScoreKeeper.
Reimplemented in ScoreKeeperShared.
References ASSERT, Difficulty_Beginner, GAMESTATE, Steps::GetDifficulty(), NoteData::GetNumHoldNotes(), NoteData::GetNumRolls(), NoteData::GetNumRowsWithTapOrHoldHead(), GameState::GetNumStagesMultiplierForSong(), Steps::GetTimingData(), m_bIsBeginner, m_iMaxPossiblePoints, PlayerStageStats::m_iMaxScore, m_iMaxScoreSoFar, m_iNumTapsAndHolds, m_iPointBonus, m_iTapNotesHit, GameState::m_pCurSong, ScoreKeeper::m_pPlayerStageStats, and GameState::SetProcessedTimingData().
Referenced by ScoreKeeperShared::OnNextSong().
TapNoteScoreToDancePoints() [1/2]
int ScoreKeeperNormal::TapNoteScoreToDancePoints (TapNoteScore tns) const
References m_bIsBeginner.
Referenced by GetPossibleDancePoints(), HandleTapNoteScoreInternal(), and HandleTapScore().
TapNoteScoreToDancePoints() [2/2]
int ScoreKeeperNormal::TapNoteScoreToDancePoints (TapNoteScore tns, bool bBeginner) static
References DEFAULT_FAIL, g_iPercentScoreWeight, GAMESTATE, SE_CheckpointHit, SE_CheckpointMiss, SE_HitMine, SE_Miss, SE_W1, SE_W2, SE_W3, SE_W4, SE_W5, GameState::ShowW1(), TNS_CheckpointHit, TNS_CheckpointMiss, TNS_HitMine, TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
TapNoteScoreToGradePoints() [1/2]
int ScoreKeeperNormal::TapNoteScoreToGradePoints (TapNoteScore tns) const
References m_bIsBeginner.
Referenced by PlayerStageStats::GetGrade(), GetPossibleGradePoints(), and ScreenEvaluation::Init().
TapNoteScoreToGradePoints() [2/2]
int ScoreKeeperNormal::TapNoteScoreToGradePoints (TapNoteScore tns, bool bBeginner) static
References DEFAULT_FAIL, g_iGradeWeight, GAMESTATE, SE_CheckpointHit, SE_CheckpointMiss, SE_HitMine, SE_Miss, SE_W1, SE_W2, SE_W3, SE_W4, SE_W5, GameState::ShowW1(), TNS_AvoidMine, TNS_CheckpointHit, TNS_CheckpointMiss, TNS_HitMine, TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
Member Data Documentation
m_apSteps
vector<Steps*> ScoreKeeperNormal::m_apSteps private
Referenced by Load().
m_AvoidMineIncrementsCombo
ThemeMetric<bool> ScoreKeeperNormal::m_AvoidMineIncrementsCombo private
Referenced by HandleTapScore(), and Load().
m_bIsBeginner
bool ScoreKeeperNormal::m_bIsBeginner private
Referenced by HoldNoteScoreToDancePoints(), HoldNoteScoreToGradePoints(), OnNextSong(), TapNoteScoreToDancePoints(), and TapNoteScoreToGradePoints().
m_bIsLastSongInCourse
bool ScoreKeeperNormal::m_bIsLastSongInCourse private
Referenced by AddScoreInternal(), and Load().
m_ComboBonusFactor
int ScoreKeeperNormal::m_ComboBonusFactor[NUM_TapNoteScore] private
Referenced by AddScoreInternal(), and Load().
m_ComboIsPerRow
ThemeMetric<bool> ScoreKeeperNormal::m_ComboIsPerRow private
Referenced by HandleComboInternal(), HandleRowComboInternal(), and Load().
m_cur_toasty_combo
int ScoreKeeperNormal::m_cur_toasty_combo private
Referenced by HandleTapRowScore(), and Load().
m_cur_toasty_level
int ScoreKeeperNormal::m_cur_toasty_level private
Referenced by HandleTapRowScore(), and Load().
m_iMaxPossiblePoints
int ScoreKeeperNormal::m_iMaxPossiblePoints private
Referenced by AddScoreInternal(), and OnNextSong().
m_iMaxScoreSoFar
int ScoreKeeperNormal::m_iMaxScoreSoFar private
Referenced by AddScoreInternal(), Load(), and OnNextSong().
m_iNumNotesHitThisRow
int ScoreKeeperNormal::m_iNumNotesHitThisRow private
Referenced by HandleTapRowScore(), and Load().
m_iNumTapsAndHolds
int ScoreKeeperNormal::m_iNumTapsAndHolds private
Referenced by AddScoreInternal(), Load(), and OnNextSong().
m_iPointBonus
int ScoreKeeperNormal::m_iPointBonus private
Referenced by AddScoreInternal(), Load(), and OnNextSong().
m_iScoreRemainder
int ScoreKeeperNormal::m_iScoreRemainder private
Referenced by AddScoreInternal(), and Load().
m_iTapNotesHit
int ScoreKeeperNormal::m_iTapNotesHit private
Referenced by AddScoreInternal(), and OnNextSong().
m_lroundTo
int ScoreKeeperNormal::m_lroundTo private
Referenced by AddScoreInternal(), and Load().
m_MaxScoreToIncrementMissCombo
ThemeMetric<TapNoteScore> ScoreKeeperNormal::m_MaxScoreToIncrementMissCombo private
Referenced by HandleRowComboInternal(), and Load().
m_MineHitIncrementsMissCombo
ThemeMetric<bool> ScoreKeeperNormal::m_MineHitIncrementsMissCombo private
Referenced by HandleTapScore(), and Load().
m_MinScoreToContinueCombo
ThemeMetric<TapNoteScore> ScoreKeeperNormal::m_MinScoreToContinueCombo private
Referenced by GetRowCounts(), HandleRowComboInternal(), HandleTapNoteScoreInternal(), and Load().
m_MinScoreToMaintainCombo
ThemeMetric<TapNoteScore> ScoreKeeperNormal::m_MinScoreToMaintainCombo private
Referenced by GetRowCounts(), HandleRowComboInternal(), HandleTapNoteScoreInternal(), and Load().
m_MissComboIsPerRow
ThemeMetric<bool> ScoreKeeperNormal::m_MissComboIsPerRow private
Referenced by HandleComboInternal(), HandleRowComboInternal(), and Load().
m_next_toasty_at
int ScoreKeeperNormal::m_next_toasty_at private
Referenced by CalcNextToastyAt(), HandleTapRowScore(), and Load().
m_toasty_min_tns
ThemeMetric<TapNoteScore> ScoreKeeperNormal::m_toasty_min_tns private
Referenced by HandleTapRowScore(), and Load().
m_toasty_trigger
ThemeMetric<LuaReference> ScoreKeeperNormal::m_toasty_trigger private
Referenced by CalcNextToastyAt(), and Load().
m_UseInternalScoring
ThemeMetric<bool> ScoreKeeperNormal::m_UseInternalScoring private
Referenced by AddScoreInternal(), and Load().
The documentation for this class was generated from the following files:
ScoreKeeperNormal.h
ScoreKeeperNormal.cpp