Etterna: LunaPacklist Class Reference
LunaPacklist Class Reference
Public Member Functions
LunaPacklist ()
Public Member Functions inherited from Luna< Packlist >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetPackTable (T *p, lua_State *L)
static int SetFromCoreBundle (T *p, lua_State *L)
static int FilterAndSearch (T *p, lua_State *L)
static int GetTotalSize (T *p, lua_State *L)
static int GetAvgDiff (T *p, lua_State *L)
static int SortByName (T *p, lua_State *L)
static int SortByDiff (T *p, lua_State *L)
static int SortBySize (T *p, lua_State *L)
static int SetFromAll (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Packlist >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Packlist >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Packlist >
using T = Packlist
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Packlist >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaPacklist()
LunaPacklist::LunaPacklist () inline
References ADD_METHOD.
Member Function Documentation
FilterAndSearch()
static int LunaPacklist::FilterAndSearch (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), DLMAN, findStringIC(), max(), MESSAGEMAN, Packlist::packs, and SArg.
GetAvgDiff()
static int LunaPacklist::GetAvgDiff (T * p, lua_State * L) inline static
References Packlist::packs.
GetPackTable()
static int LunaPacklist::GetPackTable (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and Packlist::packs.
GetTotalSize()
static int LunaPacklist::GetTotalSize (T * p, lua_State * L) inline static
References Packlist::packs.
SetFromAll()
static int LunaPacklist::SetFromAll (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), DLMAN, MESSAGEMAN, and Packlist::packs.
SetFromCoreBundle()
static int LunaPacklist::SetFromCoreBundle (T * p, lua_State * L) inline static
References MessageManager::Broadcast(), DLMAN, MESSAGEMAN, Packlist::packs, and SArg.
SortByDiff()
static int LunaPacklist::SortByDiff (T * p, lua_State * L) inline static
References Packlist::asc, DownloadablePack::avgDifficulty, MessageManager::Broadcast(), MESSAGEMAN, Packlist::packs, and Packlist::sortmode.
SortByName()
static int LunaPacklist::SortByName (T * p, lua_State * L) inline static
References Packlist::asc, MessageManager::Broadcast(), Rage::make_lower(), MESSAGEMAN, DownloadablePack::name, Packlist::packs, and Packlist::sortmode.
SortBySize()
static int LunaPacklist::SortBySize (T * p, lua_State * L) inline static
References Packlist::asc, MessageManager::Broadcast(), MESSAGEMAN, Packlist::packs, DownloadablePack::size, and Packlist::sortmode.
The documentation for this class was generated from the following file:
DownloadManager.cpp