Etterna: msAnimation Struct Reference
msAnimation Struct Reference
#include <ModelTypes.h>
Public Member Functions
int FindBoneByName (const RString &sName) const
bool LoadMilkshapeAsciiBones (const RString &sAniName, RString sPath)
Public Attributes
vector< msBone > Bones
int nTotalFrames
Member Function Documentation
FindBoneByName()
int msAnimation::FindBoneByName (const RString & sName) const inline
References Bones.
Referenced by Model::PlayAnimation(), and Model::SetBones().
LoadMilkshapeAsciiBones()
bool msAnimation::LoadMilkshapeAsciiBones (const RString & sAniName, RString sPath)
References Bones, Dirname(), f, FixSlashesInPlace(), msPositionKey::fTime, msRotationKey::fTime, RageFile::GetError(), RageFile::GetLine(), max(), MS_MAX_NAME, msBone::nFlags, nTotalFrames, RageFile::Open(), msPositionKey::Position, msBone::Position, msBone::PositionKeys, RadianToDegree, RageQuatFromHPR(), msRotationKey::Rotation, msBone::Rotation, msBone::RotationKeys, msBone::sName, msBone::sParentName, RageException::Throw(), and THROW.
Referenced by Model::LoadMilkshapeAsciiBones().
Member Data Documentation
Bones
vector<msBone> msAnimation::Bones
Referenced by FindBoneByName(), LoadMilkshapeAsciiBones(), Model::PlayAnimation(), and Model::SetBones().
nTotalFrames
int msAnimation::nTotalFrames
Referenced by Model::AdvanceFrame(), LoadMilkshapeAsciiBones(), and Model::SetPosition().
The documentation for this struct was generated from the following files:
ModelTypes.h
ModelTypes.cpp