Etterna: RageDisplay_D3D Class Reference
RageDisplay_D3D Class Reference
#include <RageDisplay_D3D.h>
Public Member Functions
RageDisplay_D3D ()
~RageDisplay_D3D () override
RString Init (const VideoModeParams &p, bool bAllowUnacceleratedRenderer) override
RString GetApiDescription () const override
virtual void GetDisplayResolutions (DisplayResolutions &out) const override
void ResolutionChanged () override
const RagePixelFormatDesc * GetPixelFormatDesc (RagePixelFormat pf) const override
bool BeginFrame () override
void EndFrame () override
const VideoModeParams * GetActualVideoModeParams () const override
void SetBlendMode (BlendMode mode) override
bool SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime=false) override
bool SupportsThreadedRendering () override
bool SupportsPerVertexMatrixScale () override
unsigned CreateTexture (RagePixelFormat pixfmt, RageSurface *img, bool bGenerateMipMaps) override
void UpdateTexture (unsigned iTexHandle, RageSurface *img, int xoffset, int yoffset, int width, int height) override
void DeleteTexture (unsigned iTexHandle) override
void ClearAllTextures () override
int GetNumTextureUnits () override
void SetTexture (TextureUnit tu, unsigned iTexture) override
void SetTextureMode (TextureUnit tu, TextureMode tm) override
void SetTextureWrapping (TextureUnit tu, bool b) override
int GetMaxTextureSize () const override
void SetTextureFiltering (TextureUnit tu, bool b) override
bool IsZWriteEnabled () const override
bool IsZTestEnabled () const override
void SetZWrite (bool b) override
void SetZBias (float f) override
void SetZTestMode (ZTestMode mode) override
void ClearZBuffer () override
void SetCullMode (CullMode mode) override
void SetAlphaTest (bool b) override
void SetMaterial (const RageColor &emissive, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, float shininess) override
void SetLighting (bool b) override
void SetLightOff (int index) override
void SetLightDirectional (int index, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, const RageVector3 &dir) override
unsigned CreateRenderTarget (const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut) override
unsigned GetRenderTarget () override
void SetRenderTarget (unsigned uTexHandle, bool bPreserveTexture) override
void SetSphereEnvironmentMapping (TextureUnit tu, bool b) override
void SetCelShaded (int stage) override
bool IsD3DInternal () override
RageCompiledGeometry * CreateCompiledGeometry () override
void DeleteCompiledGeometry (RageCompiledGeometry *p) override
Public Member Functions inherited from RageDisplay
RageDisplay ()
virtual ~RageDisplay ()
void SetPresentTime (std::chrono::nanoseconds presentTime)
RString SetVideoMode (VideoModeParams p, bool &bNeedReloadTextures)
bool IsD3D ()
bool IsWindowed ()
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void BeginConcurrentRendering ()
virtual void EndConcurrentRendering ()
virtual RageTextureLock * CreateTextureLock ()
virtual void SetEffectMode (EffectMode)
virtual bool IsEffectModeSupported (EffectMode effect)
bool SupportsRenderToTexture () const
void DrawQuads (const RageSpriteVertex v[], int iNumVerts)
void DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawFan (const RageSpriteVertex v[], int iNumVerts)
void DrawStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
void DrawCompiledGeometry (const RageCompiledGeometry *p, int iMeshIndex, const vector< msMesh > &vMeshes)
void DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawCircle (const RageSpriteVertex &v, float radius)
void DrawQuad (const RageSpriteVertex v[])
virtual void SetPolygonMode (PolygonMode)
virtual void SetLineWidth (float)
bool SaveScreenshot (const RString &sPath, GraphicsFileFormat format)
virtual RString GetTextureDiagnostics (unsigned) const
virtual RageSurface * GetTexture (unsigned)
bool IsPredictiveFrameLimit () const
int GetFPS () const
int GetVPF () const
int GetCumFPS () const
virtual void ResetStats ()
virtual void ProcessStatsOnFlip ()
virtual RString GetStats () const
void StatsAddVerts (int iNumVertsRendered)
void PushMatrix ()
void PopMatrix ()
void Translate (float x, float y, float z)
void TranslateWorld (float x, float y, float z)
void Scale (float x, float y, float z)
void RotateX (float deg)
void RotateY (float deg)
void RotateZ (float deg)
void SkewX (float fAmount)
void SkewY (float fAmount)
void MultMatrix (const RageMatrix &f)
void PostMultMatrix (const RageMatrix &f)
void PreMultMatrix (const RageMatrix &f)
void LoadIdentity ()
void TexturePushMatrix ()
void TexturePopMatrix ()
void TextureTranslate (float x, float y)
void TextureTranslate (const RageVector2 &v)
void CameraPushMatrix ()
void CameraPopMatrix ()
void LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
void LoadLookAt (float fov, const RageVector3 &Eye, const RageVector3 &At, const RageVector3 &Up)
void CenteringPushMatrix ()
void CenteringPopMatrix ()
void ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
RageSurface * CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void *pixels, int width, int height, int pitch)
RagePixelFormat FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime=false)
void PushSelf (lua_State *L)
Protected Member Functions
void DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawCompiledGeometryInternal (const RageCompiledGeometry *p, int iMeshIndex) override
RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut) override
RageSurface * CreateScreenshot () override
RageMatrix GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override
void RecoverFromDeviceLoss ()
void SendCurrentMatrices ()
Protected Member Functions inherited from RageDisplay
virtual void DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
virtual void DrawCircleInternal (const RageSpriteVertex &v, float radius)
void DrawPolyLine (const RageSpriteVertex &p1, const RageSpriteVertex &p2, float LineWidth)
void DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void SetDefaultRenderStates ()
RageMatrix GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar)
virtual RageMatrix GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf)
RageMatrix GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight)
void UpdateCentering ()
const RageMatrix * GetCentering () const
const RageMatrix * GetProjectionTop () const
const RageMatrix * GetViewTop () const
const RageMatrix * GetWorldTop () const
const RageMatrix * GetTextureTop () const
void FrameLimitBeforeVsync ()
void FrameLimitAfterVsync (int iFPS)
Additional Inherited Members
Public Types inherited from RageDisplay
enum GraphicsFileFormat { SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_LOW_QUAL, SAVE_LOSSY_HIGH_QUAL }
Constructor & Destructor Documentation
RageDisplay_D3D()
RageDisplay_D3D::RageDisplay_D3D () default
~RageDisplay_D3D()
RageDisplay_D3D::~RageDisplay_D3D () override
References g_D3D9_Module, g_pd3d, g_pd3dDevice, LOG, Shutdown(), and RageLog::Trace().
Member Function Documentation
BeginFrame()
bool RageDisplay_D3D::BeginFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::BeginFrame(), f, g_pd3dDevice, RecoverFromDeviceLoss(), SetD3DParams(), and RageException::Throw().
ClearAllTextures()
void RageDisplay_D3D::ClearAllTextures () override virtual
Implements RageDisplay.
References FOREACH_ENUM, and SetTexture().
ClearZBuffer()
void RageDisplay_D3D::ClearZBuffer () override virtual
Implements RageDisplay.
References f, and g_pd3dDevice.
CreateCompiledGeometry()
RageCompiledGeometry * RageDisplay_D3D::CreateCompiledGeometry () override virtual
Implements RageDisplay.
CreateRenderTarget()
unsigned RageDisplay_D3D::CreateRenderTarget (const RenderTargetParam & param, int & iTextureWidthOut, int & iTextureHeightOut) override virtual
Reimplemented from RageDisplay.
References ASSERT, D3DRenderTarget_FramebufferObject::Create(), and g_mapRenderTargets.
CreateScreenshot()
RageSurface * RageDisplay_D3D::CreateScreenshot () override protected virtual
Implements RageDisplay.
References RageSurfaceFormat::Amask, ASSERT, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::Bmask, RageSurfaceUtils::CopySurface(), CreateSurface(), RageDisplay::CreateSurfaceFromPixfmt(), RageSurface::fmt, g_pd3dDevice, RageSurfaceFormat::Gmask, RageSurface::h, RagePixelFormat_RGBA8, RageSurfaceFormat::Rmask, and RageSurface::w.
CreateTexture()
unsigned RageDisplay_D3D::CreateTexture (RagePixelFormat pixfmt, RageSurface * img, bool bGenerateMipMaps) override virtual
Implements RageDisplay.
References RageSurfaceColor::a, ASSERT, RageSurfaceColor::b, RageSurfacePalette::colors, D3DFORMATS, FAILED, RageSurface::fmt, RageSurfaceColor::g, g_pd3dDevice, g_TexResourceToTexturePalette, GetErrorString(), RageSurface::h, RageSurfacePalette::ncolors, TexturePalette::p, RageSurfaceFormat::palette, power_of_two(), RageSurfaceColor::r, RagePixelFormat_PAL, RagePixelFormatToString(), RageException::Throw(), UpdateTexture(), and RageSurface::w.
DeleteCompiledGeometry()
void RageDisplay_D3D::DeleteCompiledGeometry (RageCompiledGeometry * p) override virtual
Implements RageDisplay.
DeleteTexture()
void RageDisplay_D3D::DeleteTexture (unsigned iTexHandle) override virtual
Implements RageDisplay.
References g_mapRenderTargets, g_TexResourceToPaletteIndex, and g_TexResourceToTexturePalette.
DrawCompiledGeometryInternal()
void RageDisplay_D3D::DrawCompiledGeometryInternal (const RageCompiledGeometry * p, int iMeshIndex) override protected virtual
Implements RageDisplay.
References RageCompiledGeometry::Draw(), g_pd3dDevice, and SendCurrentMatrices().
DrawFanInternal()
void RageDisplay_D3D::DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, and SendCurrentMatrices().
DrawQuadsInternal()
void RageDisplay_D3D::DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, max(), and SendCurrentMatrices().
DrawQuadStripInternal()
void RageDisplay_D3D::DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, max(), and SendCurrentMatrices().
DrawStripInternal()
void RageDisplay_D3D::DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, and SendCurrentMatrices().
DrawSymmetricQuadStripInternal()
void RageDisplay_D3D::DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, max(), and SendCurrentMatrices().
DrawTrianglesInternal()
void RageDisplay_D3D::DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References D3DFVF_RageSpriteVertex, g_lastFVF, g_pd3dDevice, and SendCurrentMatrices().
EndFrame()
void RageDisplay_D3D::EndFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::EndFrame(), RageDisplay::FrameLimitAfterVsync(), RageDisplay::FrameLimitBeforeVsync(), g_pd3dDevice, GetActualVideoModeParams(), and RageDisplay::SetPresentTime().
GetActualVideoModeParams()
const VideoModeParams * RageDisplay_D3D::GetActualVideoModeParams () const override virtual
Implements RageDisplay.
Referenced by EndFrame(), and SetRenderTarget().
GetApiDescription()
RString RageDisplay_D3D::GetApiDescription () const inline override virtual
Implements RageDisplay.
GetDisplayResolutions()
void RageDisplay_D3D::GetDisplayResolutions (DisplayResolutions & out) const override virtual
Implements RageDisplay.
References g_DefaultAdapterFormat, and g_pd3d.
GetMaxTextureSize()
int RageDisplay_D3D::GetMaxTextureSize () const override virtual
Implements RageDisplay.
References g_DeviceCaps.
GetNumTextureUnits()
int RageDisplay_D3D::GetNumTextureUnits () override virtual
Implements RageDisplay.
References g_DeviceCaps.
GetOrthoMatrix()
RageMatrix RageDisplay_D3D::GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf) override protected virtual
Reimplemented from RageDisplay.
References f, RageDisplay::GetOrthoMatrix(), RageMatrixMultiply(), RageMatrixScaling(), and RageMatrixTranslation().
GetPixelFormatDesc()
const RageDisplay::RagePixelFormatDesc * RageDisplay_D3D::GetPixelFormatDesc (RagePixelFormat pf) const override virtual
Implements RageDisplay.
References ASSERT, NUM_RagePixelFormat, and PIXEL_FORMAT_DESC.
GetRenderTarget()
unsigned RageDisplay_D3D::GetRenderTarget () override virtual
Reimplemented from RageDisplay.
References g_mapRenderTargets.
Init()
RString RageDisplay_D3D::Init (const VideoModeParams & p, bool bAllowUnacceleratedRenderer) override virtual
Implements RageDisplay.
References D3D_NOT_INSTALLED, FAILED, g_DefaultAdapterFormat, g_DesktopMode, g_DeviceCaps, g_PaletteIndex, g_pd3d, LocalizedString::GetValue(), HARDWARE_ACCELERATION_NOT_AVAILABLE, LOG, RageLog::MapLog(), RageDisplay::SetVideoMode(), and RageLog::Trace().
IsD3DInternal()
bool RageDisplay_D3D::IsD3DInternal () override virtual
Reimplemented from RageDisplay.
IsZTestEnabled()
bool RageDisplay_D3D::IsZTestEnabled () const override virtual
Implements RageDisplay.
References g_pd3dDevice.
IsZWriteEnabled()
bool RageDisplay_D3D::IsZWriteEnabled () const override virtual
Implements RageDisplay.
References g_pd3dDevice.
RecoverFromDeviceLoss()
void RageDisplay_D3D::RecoverFromDeviceLoss () protected
References g_lastFVF.
Referenced by BeginFrame(), and TryVideoMode().
ResolutionChanged()
void RageDisplay_D3D::ResolutionChanged () override virtual
Reimplemented from RageDisplay.
References RageDisplay::ResolutionChanged().
Referenced by TryVideoMode().
SendCurrentMatrices()
void RageDisplay_D3D::SendCurrentMatrices () protected
References f, FOREACH_ENUM, g_bInvertY, g_bSphereMapping, g_pd3dDevice, RageDisplay::GetCentering(), RageDisplay::GetCenteringMatrix(), RageDisplay::GetProjectionTop(), RageDisplay::GetTextureTop(), RageDisplay::GetViewTop(), RageDisplay::GetWorldTop(), RageMatrix::m, RageMatrixMultiply(), and RageMatrixScale().
Referenced by DrawCompiledGeometryInternal(), DrawFanInternal(), DrawQuadsInternal(), DrawQuadStripInternal(), DrawStripInternal(), DrawSymmetricQuadStripInternal(), and DrawTrianglesInternal().
SetAlphaTest()
void RageDisplay_D3D::SetAlphaTest (bool b) override virtual
Implements RageDisplay.
References g_pd3dDevice.
SetBlendMode()
void RageDisplay_D3D::SetBlendMode (BlendMode mode) override virtual
Implements RageDisplay.
References BLEND_ADD, BLEND_ALPHA_KNOCK_OUT, BLEND_ALPHA_MASK, BLEND_ALPHA_MULTIPLY, BLEND_COPY_SRC, BLEND_INVERT_DEST, BLEND_MODULATE, BLEND_NO_EFFECT, BLEND_NORMAL, BLEND_SUBTRACT, BLEND_WEIGHTED_MULTIPLY, FAIL_M, g_pd3dDevice, and ssprintf().
SetCelShaded()
void RageDisplay_D3D::SetCelShaded (int stage) override virtual
Implements RageDisplay.
SetCullMode()
void RageDisplay_D3D::SetCullMode (CullMode mode) override virtual
Implements RageDisplay.
References CULL_BACK, CULL_FRONT, CULL_NONE, FAIL_M, g_pd3dDevice, and ssprintf().
SetLightDirectional()
void RageDisplay_D3D::SetLightDirectional (int index, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, const RageVector3 & dir) override virtual
Implements RageDisplay.
References g_pd3dDevice, RageVector3::x, RageVector3::y, RageVector3::z, and ZERO.
SetLighting()
void RageDisplay_D3D::SetLighting (bool b) override virtual
Implements RageDisplay.
References g_pd3dDevice.
SetLightOff()
void RageDisplay_D3D::SetLightOff (int index) override virtual
Implements RageDisplay.
References g_pd3dDevice.
SetMaterial()
void RageDisplay_D3D::SetMaterial (const RageColor & emissive, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, float shininess) override virtual
Implements RageDisplay.
References RageColor::b, RageColor::g, g_pd3dDevice, and RageColor::r.
SetRenderTarget()
void RageDisplay_D3D::SetRenderTarget (unsigned uTexHandle, bool bPreserveTexture) override virtual
Reimplemented from RageDisplay.
References ASSERT, RageDisplay::CameraPopMatrix(), RageDisplay::CameraPushMatrix(), DISPLAY, f, FAILED, RenderTarget::FinishRenderingTo(), g_bInvertY, g_mapRenderTargets, g_pd3dDevice, GetActualVideoModeParams(), VideoModeParams::height, LOG, RageDisplay::SetDefaultRenderStates(), SetZWrite(), RageLog::Warn(), and VideoModeParams::width.
SetSphereEnvironmentMapping()
void RageDisplay_D3D::SetSphereEnvironmentMapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References g_bSphereMapping.
SetTexture()
void RageDisplay_D3D::SetTexture (TextureUnit tu, unsigned iTexture) override virtual
Implements RageDisplay.
References g_DeviceCaps, g_pd3dDevice, and SetPalette().
Referenced by ClearAllTextures().
SetTextureFiltering()
void RageDisplay_D3D::SetTextureFiltering (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References g_DeviceCaps, and g_pd3dDevice.
SetTextureMode()
void RageDisplay_D3D::SetTextureMode (TextureUnit tu, TextureMode tm) override virtual
Implements RageDisplay.
References g_DeviceCaps, g_pd3dDevice, TextureMode_Add, TextureMode_Glow, and TextureMode_Modulate.
SetTextureWrapping()
void RageDisplay_D3D::SetTextureWrapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References g_DeviceCaps, and g_pd3dDevice.
SetZBias()
void RageDisplay_D3D::SetZBias (float f) override virtual
Implements RageDisplay.
References g_pd3dDevice, and SCALE.
SetZTestMode()
void RageDisplay_D3D::SetZTestMode (ZTestMode mode) override virtual
Implements RageDisplay.
References FAIL_M, g_pd3dDevice, ssprintf(), ZTEST_OFF, ZTEST_WRITE_ON_FAIL, and ZTEST_WRITE_ON_PASS.
SetZWrite()
void RageDisplay_D3D::SetZWrite (bool b) override virtual
Implements RageDisplay.
References g_pd3dDevice.
Referenced by SetRenderTarget().
SupportsPerVertexMatrixScale()
bool RageDisplay_D3D::SupportsPerVertexMatrixScale () inline override virtual
Implements RageDisplay.
SupportsTextureFormat()
bool RageDisplay_D3D::SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime = false) override virtual
Implements RageDisplay.
References D3DFORMATS, g_d3dpp, g_DeviceCaps, g_pd3d, and RagePixelFormat_PAL.
SupportsThreadedRendering()
bool RageDisplay_D3D::SupportsThreadedRendering () override virtual
Reimplemented from RageDisplay.
TryVideoMode()
RString RageDisplay_D3D::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) override protected virtual
Implements RageDisplay.
References VideoModeParams::bpp, D3DReduceParams(), FindBackBufferType(), g_d3dpp, g_pd3dDevice, VideoModeParams::height, LOG, VideoModeParams::rate, RecoverFromDeviceLoss(), REFRESH_DEFAULT, ResolutionChanged(), SetD3DParams(), SetPresentParametersFromVideoModeParams(), ssprintf(), VideoModeParams::vsync, RageLog::Warn(), VideoModeParams::width, and VideoModeParams::windowed.
UpdateTexture()
void RageDisplay_D3D::UpdateTexture (unsigned iTexHandle, RageSurface * img, int xoffset, int yoffset, int width, int height) override virtual
Implements RageDisplay.
References ASSERT, RageSurfaceUtils::Blit(), RageDisplay::CreateSurfaceFromPixfmt(), D3DFORMATS, and NUM_RagePixelFormat.
Referenced by CreateTexture().
The documentation for this class was generated from the following files:
RageDisplay_D3D.h
RageDisplay_D3D.cpp