Etterna: LunaInputFilter Class Reference
LunaInputFilter Class Reference
Allow Lua to have access to InputFilter.
Public Member Functions
DEFINE_METHOD (IsShiftPressed, IsShiftPressed())
DEFINE_METHOD (IsControlPressed, IsControlPressed())
LunaInputFilter ()
Public Member Functions inherited from Luna< InputFilter >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetMouseX (T *p, lua_State *L)
static int GetMouseY (T *p, lua_State *L)
static int GetMouseWheel (T *p, lua_State *L)
static int IsBeingPressed (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< InputFilter >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< InputFilter >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< InputFilter >
using T = InputFilter
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< InputFilter >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to InputFilter.
Constructor & Destructor Documentation
LunaInputFilter()
LunaInputFilter::LunaInputFilter () inline
References ADD_METHOD, GetMouseWheel(), GetMouseX(), GetMouseY(), and IsBeingPressed().
Member Function Documentation
DEFINE_METHOD() [1/2]
LunaInputFilter::DEFINE_METHOD (IsShiftPressed , IsShiftPressed())
DEFINE_METHOD() [2/2]
LunaInputFilter::DEFINE_METHOD (IsControlPressed , IsControlPressed())
GetMouseWheel()
static int LunaInputFilter::GetMouseWheel (T * p, lua_State * L) inline static
References InputFilter::GetMouseWheel().
Referenced by LunaInputFilter().
GetMouseX()
static int LunaInputFilter::GetMouseX (T * p, lua_State * L) inline static
References InputFilter::GetCursorX(), ArchHooks::GetWindowWidth(), HOOKS, SCALE, SCREEN_LEFT, and SCREEN_RIGHT.
Referenced by LunaInputFilter().
GetMouseY()
static int LunaInputFilter::GetMouseY (T * p, lua_State * L) inline static
References InputFilter::GetCursorY(), ArchHooks::GetWindowHeight(), HOOKS, SCALE, SCREEN_BOTTOM, and SCREEN_TOP.
Referenced by LunaInputFilter().
IsBeingPressed()
static int LunaInputFilter::IsBeingPressed (T * p, lua_State * L) inline static
References DEVICE_KEYBOARD, InputFilter::IsBeingPressed(), SArg, StringToDeviceButton(), and StringToInputDevice().
Referenced by LunaInputFilter().
The documentation for this class was generated from the following file:
InputFilter.cpp