Etterna: StepsCriteria Class Reference
StepsCriteria Class Reference
the criteria for finding certain Steps.
#include <StepsUtil.h>
Public Member Functions
StepsCriteria ()
Set up the initial criteria.
bool Matches (const Song *pSong, const Steps *pSteps) const
Determine if the Song and Steps match our criteria.
bool operator== (const StepsCriteria &other) const
Compare two StepsCriteria to see if they are equal.
bool operator!= (const StepsCriteria &other) const
Compare two StepsCriteria to see if they are not equal.
Public Attributes
Difficulty m_difficulty { Difficulty_Invalid }
the Difficulty to search for.
int m_iLowMeter { -1 }
The lowest meter to search for.
int m_iHighMeter { -1 }
The highest meter to search for.
StepsType m_st { StepsType_Invalid }
the step type to search for.
Detailed Description
the criteria for finding certain Steps.
Constructor & Destructor Documentation
StepsCriteria()
StepsCriteria::StepsCriteria () inline
Set up the initial criteria.
Member Function Documentation
Matches()
bool StepsCriteria::Matches (const Song * pSong, const Steps * pSteps) const
Determine if the Song and Steps match our criteria.
Parameters
pSong the Song to check for.
pSteps the Step to check for.
Returns
true if it matches, false otherwise.
References Difficulty_Invalid, Steps::GetDifficulty(), Steps::GetMeter(), m_difficulty, m_iHighMeter, m_iLowMeter, m_st, Steps::m_StepsType, and StepsType_Invalid.
Referenced by StepsUtil::GetAllMatching(), and StepsUtil::HasMatching().
operator!=()
bool StepsCriteria::operator!= (const StepsCriteria & other) const inline
Compare two StepsCriteria to see if they are not equal.
Parameters
other the StepsCriteria we are checking against.
Returns
true if they are not equal, false otherwise.
References operator==().
operator==()
bool StepsCriteria::operator== (const StepsCriteria & other) const inline
Compare two StepsCriteria to see if they are equal.
Parameters
other the StepsCriteria we are checking against.
Returns
true if they are equal, false otherwise.
References m_difficulty, m_iHighMeter, m_iLowMeter, m_st, and X.
Referenced by operator!=().
Member Data Documentation
m_difficulty
Difficulty StepsCriteria::m_difficulty { Difficulty_Invalid }
the Difficulty to search for.
Don't filter here if the Difficulty is Difficulty_Invalid.
Referenced by Matches(), and operator==().
m_iHighMeter
int StepsCriteria::m_iHighMeter { -1 }
The highest meter to search for.
Don't filter here if the meter is -1.
Referenced by Matches(), and operator==().
m_iLowMeter
int StepsCriteria::m_iLowMeter { -1 }
The lowest meter to search for.
Don't filter here if the meter is -1.
Referenced by Matches(), and operator==().
m_st
StepsType StepsCriteria::m_st { StepsType_Invalid }
the step type to search for.
Don't filter here if the StepsType is StepsType_Invalid.
Referenced by StepsUtil::GetAllMatching(), StepsUtil::GetAllMatchingEndless(), StepsUtil::HasMatching(), Matches(), and operator==().
The documentation for this class was generated from the following files:
StepsUtil.h
StepsUtil.cpp