Etterna: NoteColorActor Struct Reference
NoteColorActor Struct Reference
#include <NoteDisplay.h>
Public Member Functions
NoteColorActor ()
~NoteColorActor ()
void Load (const RString &sButton, const RString &sElement, PlayerNumber, GameController, RString)
Actor * Get (RString)
Private Attributes
map< RString, NoteResource * > g_p
Constructor & Destructor Documentation
NoteColorActor()
NoteColorActor::NoteColorActor ()
References g_p.
~NoteColorActor()
NoteColorActor::~NoteColorActor ()
References DeleteNoteResource(), and g_p.
Member Function Documentation
Get()
Actor * NoteColorActor::Get (RString Color)
References g_p.
Referenced by NoteDisplay::GetTapActor().
Load()
void NoteColorActor::Load (const RString & sButton, const RString & sElement, PlayerNumber pn, GameController gc, RString Color)
References g_p, and MakeNoteResource().
Referenced by NoteDisplay::Load().
Member Data Documentation
g_p
map<RString, NoteResource*> NoteColorActor::g_p private
Referenced by Get(), Load(), NoteColorActor(), and ~NoteColorActor().
The documentation for this struct was generated from the following files:
NoteDisplay.h
NoteDisplay.cpp