Etterna: ModelManager Class Reference
ModelManager Class Reference
Class for loading and releasing textures.
#include <ModelManager.h>
Public Member Functions
ModelManager ()
~ModelManager ()
RageModelGeometry * LoadMilkshapeAscii (const RString &sFile, bool bNeedNormals)
void UnloadModel (RageModelGeometry *m)
bool SetPrefs (const ModelManagerPrefs &prefs)
Set up new preferences.
const ModelManagerPrefs & GetPrefs ()
Protected Attributes
std::map< RString, RageModelGeometry * > m_mapFileToGeometry
ModelManagerPrefs m_Prefs
Detailed Description
Class for loading and releasing textures.
Funnily enough, the original documentation claimed this was an Interface.
Constructor & Destructor Documentation
ModelManager()
ModelManager::ModelManager () default
~ModelManager()
ModelManager::~ModelManager ()
References LOG, RageModelGeometry::m_iRefCount, m_mapFileToGeometry, SAFE_DELETE, and RageLog::Trace().
Member Function Documentation
GetPrefs()
const ModelManagerPrefs& ModelManager::GetPrefs () inline
References m_Prefs.
LoadMilkshapeAscii()
RageModelGeometry * ModelManager::LoadMilkshapeAscii (const RString & sFile, bool bNeedNormals)
References RageModelGeometry::LoadMilkshapeAscii(), RageModelGeometry::m_iRefCount, and m_mapFileToGeometry.
Referenced by Model::LoadPieces().
SetPrefs()
bool ModelManager::SetPrefs (const ModelManagerPrefs & prefs)
Set up new preferences.
Parameters
prefs the new preferences to set up.
Returns
true if the display needs to be reset, false otherwise.
References m_Prefs.
Referenced by StepMania::ApplyGraphicOptions(), and StartDisplay().
UnloadModel()
void ModelManager::UnloadModel (RageModelGeometry * m)
References ASSERT, FAIL_M, ModelManagerPrefs::m_bDelayedUnload, RageModelGeometry::m_iRefCount, m_mapFileToGeometry, m_Prefs, and SAFE_DELETE.
Referenced by Model::Clear().
Member Data Documentation
m_mapFileToGeometry
std::map<RString, RageModelGeometry*> ModelManager::m_mapFileToGeometry protected
Referenced by LoadMilkshapeAscii(), UnloadModel(), and ~ModelManager().
m_Prefs
ModelManagerPrefs ModelManager::m_Prefs protected
Referenced by GetPrefs(), SetPrefs(), and UnloadModel().
The documentation for this class was generated from the following files:
ModelManager.h
ModelManager.cpp