Etterna: FontCharAliases Namespace Reference
FontCharAliases Namespace Reference
Provides support for nonstandard characters in text.
Functions
void ReplaceMarkers (RString &sText)
bool GetChar (RString &codepoint, wchar_t &ch)
Detailed Description
Provides support for nonstandard characters in text.
Function Documentation
GetChar()
bool FontCharAliases::GetChar (RString & codepoint, wchar_t & ch)
References CharAliases, and InitCharAliases().
Referenced by Font::LoadFontPageSettings().
ReplaceMarkers()
void FontCharAliases::ReplaceMarkers (RString & sText)
References CharAliasRepl, InitCharAliases(), Replace_Unicode_Markers(), and ReplaceEntityText().
Referenced by ScreenTextEntry::End(), ThemeManager::EvaluateString(), ThemeManager::GetString(), OptionRowHandlerUtil::MakeSimple(), LunaBitmapText::settext(), LunaHelpDisplay::settips(), TitleSubst::Subst(), and ScreenTextEntry::UpdateAnswerText().