Etterna: InputHandler_X11 Class Reference
InputHandler_X11 Class Reference
#include <InputHandler_X11.h>
Public Member Functions
InputHandler_X11 ()
~InputHandler_X11 ()
void Update ()
void GetDevicesAndDescriptions (std::vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual bool DevicesChanged ()
virtual void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)=0
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_X11()
InputHandler_X11::InputHandler_X11 ()
~InputHandler_X11()
InputHandler_X11::~InputHandler_X11 ()
Member Function Documentation
GetDevicesAndDescriptions()
void InputHandler_X11::GetDevicesAndDescriptions (std::vector< InputDeviceInfo > & vDevicesOut)
References DEVICE_KEYBOARD, and DEVICE_MOUSE.
Update()
void InputHandler_X11::Update () virtual
Reimplemented from InputHandler.
References DEVICE_KEYBOARD, DEVICE_MOUSE, DeviceButton_Invalid, InputFilter::GetMouseWheel(), InputDevice_Invalid, INPUTFILTER, MOUSE_WHEELDOWN, MOUSE_WHEELUP, InputFilter::Reset(), InputFilter::UpdateCursorLocation(), InputFilter::UpdateMouseWheel(), InputHandler::UpdateTimer(), XMouseButtonToDeviceButton(), and XSymToDeviceButton().
The documentation for this class was generated from the following files:
InputHandler_X11.h
InputHandler_X11.cpp