Etterna: ThreadSlot::ThreadCheckpoint Struct Reference
ThreadSlot::ThreadCheckpoint Struct Reference
Public Member Functions
ThreadCheckpoint ()
void Set (const char *szFile, int iLine, const char *szMessage=NULL)
const char * GetFormattedCheckpoint ()
Public Attributes
const char * m_szFile
const char * m_szMessage
int m_iLine
char m_szFormattedBuf [1024]
Constructor & Destructor Documentation
ThreadCheckpoint()
ThreadSlot::ThreadCheckpoint::ThreadCheckpoint () inline
References Set().
Member Function Documentation
GetFormattedCheckpoint()
const char * ThreadSlot::ThreadCheckpoint::GetFormattedCheckpoint ()
Referenced by ThreadSlot::GetFormattedCheckpoint().
Set()
void ThreadSlot::ThreadCheckpoint::Set (const char * szFile, int iLine, const char * szMessage = NULL)
References m_iLine, m_szFile, m_szFormattedBuf, and m_szMessage.
Referenced by Checkpoints::SetCheckpoint(), and ThreadCheckpoint().
Member Data Documentation
m_iLine
int ThreadSlot::ThreadCheckpoint::m_iLine
Referenced by Set().
m_szFile
const char* ThreadSlot::ThreadCheckpoint::m_szFile
Referenced by Set().
m_szFormattedBuf
char ThreadSlot::ThreadCheckpoint::m_szFormattedBuf[1024]
Referenced by Set(), and Checkpoints::SetCheckpoint().
m_szMessage
const char * ThreadSlot::ThreadCheckpoint::m_szMessage
Referenced by Set().
The documentation for this struct was generated from the following file:
RageThreads.cpp