Etterna: LunaRageFile Class Reference
LunaRageFile Class Reference
Allow Lua to have access to the RageFile.
Public Member Functions
LunaRageFile ()
Public Member Functions inherited from Luna< RageFile >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static void safely_opened (T *p, lua_State *L)
static void can_safely_read (T *p, lua_State *L)
static void can_safely_write (T *p, lua_State *L)
static int destroy (T *p, lua_State *L)
static int Open (T *p, lua_State *L)
static int Close (T *p, lua_State *L)
static int Write (T *p, lua_State *L)
static int Flush (T *p, lua_State *L)
static int Read (T *p, lua_State *L)
static int ReadBytes (T *p, lua_State *L)
static int Seek (T *p, lua_State *L)
static int Tell (T *p, lua_State *L)
static int GetLine (T *p, lua_State *L)
static int PutLine (T *p, lua_State *L)
static int GetError (T *p, lua_State *L)
static int ClearError (T *p, lua_State *L)
static int AtEOF (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageFile >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageFile >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageFile >
using T = RageFile
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageFile >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the RageFile.
Constructor & Destructor Documentation
LunaRageFile()
LunaRageFile::LunaRageFile () inline
References ADD_METHOD, AtEOF(), ClearError(), Close(), destroy(), Flush(), GetError(), GetLine(), Open(), PutLine(), Read(), ReadBytes(), Seek(), Tell(), and Write().
Member Function Documentation
AtEOF()
static int LunaRageFile::AtEOF (T * p, lua_State * L) inline static
References RageFile::AtEOF(), and can_safely_read().
Referenced by LunaRageFile().
can_safely_read()
static void LunaRageFile::can_safely_read (T * p, lua_State * L) inline static
References RageFile::GetMode(), RageFile::GetPath(), RageFile::READ, and safely_opened().
Referenced by AtEOF(), GetLine(), Read(), ReadBytes(), Seek(), and Tell().
can_safely_write()
static void LunaRageFile::can_safely_write (T * p, lua_State * L) inline static
References RageFile::GetMode(), RageFile::GetPath(), safely_opened(), and RageFile::WRITE.
Referenced by PutLine(), and Write().
ClearError()
static int LunaRageFile::ClearError (T * p, lua_State * L) inline static
References RageFile::ClearError().
Referenced by LunaRageFile().
Close()
static int LunaRageFile::Close (T * p, lua_State * L) inline static
References RageFile::Close().
Referenced by LunaRageFile().
destroy()
static int LunaRageFile::destroy (T * p, lua_State * L) inline static
References SAFE_DELETE.
Referenced by LunaRageFile().
Flush()
static int LunaRageFile::Flush (T * p, lua_State * L) inline static
References RageFile::Flush().
Referenced by LunaRageFile().
GetError()
static int LunaRageFile::GetError (T * p, lua_State * L) inline static
References RageFile::GetError().
Referenced by LunaRageFile().
GetLine()
static int LunaRageFile::GetLine (T * p, lua_State * L) inline static
References can_safely_read(), and RageFile::GetLine().
Referenced by LunaRageFile().
Open()
static int LunaRageFile::Open (T * p, lua_State * L) inline static
References IArg, RageFile::Open(), and SArg.
Referenced by LunaRageFile().
PutLine()
static int LunaRageFile::PutLine (T * p, lua_State * L) inline static
References can_safely_write(), RageFile::PutLine(), and SArg.
Referenced by LunaRageFile().
Read()
static int LunaRageFile::Read (T * p, lua_State * L) inline static
References can_safely_read(), and RageFile::Read().
Referenced by LunaRageFile().
ReadBytes()
static int LunaRageFile::ReadBytes (T * p, lua_State * L) inline static
References can_safely_read(), IArg, and RageFile::Read().
Referenced by LunaRageFile().
safely_opened()
static void LunaRageFile::safely_opened (T * p, lua_State * L) inline static
References RageFile::GetPath(), and RageFile::IsOpen().
Referenced by can_safely_read(), and can_safely_write().
Seek()
static int LunaRageFile::Seek (T * p, lua_State * L) inline static
References can_safely_read(), IArg, and RageFile::Seek().
Referenced by LunaRageFile().
Tell()
static int LunaRageFile::Tell (T * p, lua_State * L) inline static
References can_safely_read(), and RageFile::Tell().
Referenced by LunaRageFile().
Write()
static int LunaRageFile::Write (T * p, lua_State * L) inline static
References can_safely_write(), SArg, and RageFile::Write().
Referenced by LunaRageFile().
The documentation for this class was generated from the following file:
RageFile.cpp