Etterna: MessageManager Class Reference
MessageManager Class Reference
Deliver messages to any part of the program as needed.
#include <MessageManager.h>
Public Member Functions
MessageManager ()
~MessageManager ()
void Subscribe (IMessageSubscriber *pSubscriber, const RString &sMessage)
void Subscribe (IMessageSubscriber *pSubscriber, MessageID m)
void Unsubscribe (IMessageSubscriber *pSubscriber, const RString &sMessage)
void Unsubscribe (IMessageSubscriber *pSubscriber, MessageID m)
void Broadcast (Message &msg) const
void Broadcast (const RString &sMessage) const
void Broadcast (MessageID m) const
bool IsSubscribedToMessage (IMessageSubscriber *pSubscriber, const RString &sMessage) const
bool IsSubscribedToMessage (IMessageSubscriber *pSubscriber, MessageID message) const
void SetLogging (bool set)
void PushSelf (lua_State *L)
Public Attributes
bool m_Logging
Detailed Description
Deliver messages to any part of the program as needed.
Constructor & Destructor Documentation
MessageManager()
MessageManager::MessageManager ()
References LuaManager::Get(), L, LUA, m_Logging, PushSelf(), and LuaManager::Release().
~MessageManager()
MessageManager::~MessageManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
Broadcast() [1/3]
void MessageManager::Broadcast (Message & msg) const
References FOREACHS_CONST, g_MessageToSubscribers, g_Mutex, Message::GetName(), IMessageSubscriber::HandleMessage(), LockMut, LOG, m_Logging, Message::SetBroadcast(), and RageLog::Trace().
Referenced by Profile::AddGoal(), LifeMeterBar::AfterLifeChanged(), ScreenSelectMusic::AfterStepsOrTrailChange(), Broadcast(), LunaMessageManager::Broadcast(), LifeMeterBattery::BroadcastLifeChanged(), BroadcastPreferenceChanged(), MusicWheel::BuildWheelItemDatas(), ScreenGameplayLesson::ChangeLessonPage(), ScreenSelectMaster::ChangePage(), ScreenSelectMusic::ChangeSteps(), ScreenOptions::ChangeValueInRowAbsolute(), InputMapper::CheckForChangedInputDevicesAndRemap(), StepMania::ClearCredits(), OptionsList::Close(), NetworkSyncManager::CloseConnection(), SMOProtocol::DealWithSMOnlinePack(), ScreenSelectMusic::DetectCodes(), SongManager::DifferentialReload(), SongManager::DifferentialReloadDir(), DebugLineAutosync::DoAndLog(), DebugLineShowRecentErrors::DoAndLog(), DebugLineClearErrors::DoAndLog(), Player::DoTapScoreNone(), DownloadManager::EndSession(), OptionRowHandlerList::ExportOption(), Download::Failed(), LunaPacklist::FilterAndSearch(), SongOptions::FromOneModString(), HandleGlobalInputs(), ScoreKeeperNormal::HandleHoldScore(), ScreenEvaluation::HandleMenuStart(), ScreenGameplayLesson::HandleScreenMessage(), ScreenNetSelectBase::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenSelectMusic::HandleScreenMessage(), ScreenSelectMaster::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScoreKeeperNormal::HandleTapRowScore(), ScoreKeeperNormal::HandleTapScore(), ScoreKeeperNormal::HandleTapScoreNone(), ScreenManager::HideSystemMessage(), ScreenTestInput::Input(), ScreenPlayerOptions::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), OptionsList::Input(), Screen::Input(), ScreenGameplay::Input(), Download::Install(), GameState::JoinPlayer(), ScoreKeeperNormal::Load(), ScreenManager::LoadDelayedScreen(), ScreenGameplay::LoadNextSong(), makePlaylist(), ScreenSelectProfile::MenuDown(), ScreenSelectMaster::MenuDown(), ScreenOptions::MenuDown(), ScreenSelectProfile::MenuLeft(), ScreenSelectMaster::MenuLeft(), ScreenOptions::MenuLeft(), ScreenSelectProfile::MenuRight(), ScreenSelectMaster::MenuRight(), ScreenOptions::MenuRight(), ScreenSelectMaster::MenuStart(), ScreenSelectProfile::MenuUp(), ScreenSelectMaster::MenuUp(), ScreenOptions::MenuUp(), ScreenOptions::MoveRowAbsolute(), LunaSongOptions::MusicRate(), DownloadManager::OnLogin(), OptionsList::Open(), LunaScreenSelectMusic::PlayReplay(), NetworkSyncManager::PostStartUp(), SMOProtocol::ProcessInput(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptions::ProcessMenuStart(), ScreenManager::RefreshCreditsMessages(), DownloadManager::RefreshFavourites(), DownloadManager::RefreshTop25(), DownloadManager::RefreshUserData(), DownloadManager::RefreshUserRank(), DownloadManager::RequestChartLeaderBoard(), AdjustSync::SaveSyncChanges(), LuaHelpers::ScriptErrorMessage(), ScreenSelectMusic::SelectCurrent(), Player::SendComboMessages(), ScreenGameplay::SendCrossedMessages(), LifeMeterTime::SendLifeChangedMessage(), BroadcastOnChange< Difficulty >::Set(), BroadcastOnChangePtr< const Style >::Set(), LunaPacklist::SetFromAll(), LunaPacklist::SetFromCoreBundle(), Player::SetHoldJudgment(), Player::SetJudgment(), PlayerStageStats::SetLifeRecordAt(), Player::SetMineJudgment(), LunaScreenSelectMusic::ShowEvalScreenForScore(), LunaPacklist::SortByDiff(), LunaPacklist::SortByName(), LunaPacklist::SortBySize(), OptionsList::Start(), LunaScreenSelectMusic::StartPlaylistAsCourse(), Player::Step(), OptionsList::SwitchToCurrentRow(), ScreenManager::SystemMessage(), ScreenManager::SystemMessageNoAnimate(), ScreenGameplay::ToggleReplayPause(), GameState::UnjoinPlayer(), ScreenInstallOverlay::Update(), GameSoundManager::Update(), BackgroundImpl::Update(), ScreenGameplay::Update(), ETTProtocol::Update(), DownloadManager::UpdatePacks(), ScreenSelectMusic::UpdateSelectButton(), ScreenNetEvaluation::UpdateStats(), MusicWheel::UpdateSwitch(), Actor::UpdateTweening(), and ScreenNetSelectBase::UpdateUsers().
Broadcast() [2/3]
void MessageManager::Broadcast (const RString & sMessage) const
References ASSERT, and Broadcast().
Broadcast() [3/3]
void MessageManager::Broadcast (MessageID m) const
References Broadcast(), and MessageIDToString().
IsSubscribedToMessage() [1/2]
bool MessageManager::IsSubscribedToMessage (IMessageSubscriber * pSubscriber, const RString & sMessage) const
References g_MessageToSubscribers.
Referenced by ScreenSelect::Init(), and IsSubscribedToMessage().
IsSubscribedToMessage() [2/2]
bool MessageManager::IsSubscribedToMessage (IMessageSubscriber * pSubscriber, MessageID message) const inline
References IsSubscribedToMessage(), and MessageIDToString().
PushSelf()
void MessageManager::PushSelf (lua_State * L)
Referenced by MessageManager().
SetLogging()
void MessageManager::SetLogging (bool set) inline
References m_Logging.
Referenced by LunaMessageManager::SetLogging().
Subscribe() [1/2]
void MessageManager::Subscribe (IMessageSubscriber * pSubscriber, const RString & sMessage)
References ASSERT_M, g_MessageToSubscribers, g_Mutex, LockMut, and ssprintf().
Referenced by ScreenSelect::Init(), OptionRow::LoadNormal(), Subscribe(), and MessageSubscriber::SubscribeToMessage().
Subscribe() [2/2]
void MessageManager::Subscribe (IMessageSubscriber * pSubscriber, MessageID m)
References MessageIDToString(), and Subscribe().
Unsubscribe() [1/2]
void MessageManager::Unsubscribe (IMessageSubscriber * pSubscriber, const RString & sMessage)
References ASSERT, g_MessageToSubscribers, g_Mutex, and LockMut.
Referenced by OptionRow::Clear(), Unsubscribe(), MessageSubscriber::UnsubscribeAll(), and ScreenSelect::~ScreenSelect().
Unsubscribe() [2/2]
void MessageManager::Unsubscribe (IMessageSubscriber * pSubscriber, MessageID m)
References MessageIDToString(), and Unsubscribe().
Member Data Documentation
m_Logging
bool MessageManager::m_Logging
Referenced by Broadcast(), MessageManager(), and SetLogging().
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cpp