Etterna: ScreenOptionsExportPackage.cpp File Reference
ScreenOptionsExportPackage.cpp File Reference
#include "ScreenOptionsExportPackage.h"
#include "CommonMetrics.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "OptionRowHandler.h"
#include "RageFile.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "ScreenMiniMenu.h"
#include "ScreenPrompt.h"
#include "SongManager.h"
#include "SpecialFiles.h"
#include "archutils/SpecialDirs.h"
#include "global.h"
Functions
REGISTER_SCREEN_CLASS (ScreenOptionsExportPackage)
REGISTER_SCREEN_CLASS (ScreenOptionsExportPackageSubPage)
static RString ReplaceInvalidFileNameChars (RString sOldFileName)
static bool ExportPackage (RString sPackageName, RString sDirToExport, RString &sErrorOut)
Function Documentation
ExportPackage()
static bool ExportPackage (RString sPackageName, RString sDirToExport, RString & sErrorOut) static
References f, RageFile::GetError(), RageFile::Open(), ssprintf(), and RageFile::WRITE.
Referenced by ScreenOptionsExportPackageSubPage::ProcessMenuStart().
REGISTER_SCREEN_CLASS() [1/2]
REGISTER_SCREEN_CLASS (ScreenOptionsExportPackage)
REGISTER_SCREEN_CLASS() [2/2]
REGISTER_SCREEN_CLASS (ScreenOptionsExportPackageSubPage)
ReplaceInvalidFileNameChars()
static RString ReplaceInvalidFileNameChars (RString sOldFileName) static
References StdString::CStdStr< CT >::Replace().
Referenced by ScreenOptionsExportPackageSubPage::ProcessMenuStart().