Etterna: RageFileDriverSlice Class Reference
RageFileDriverSlice Class Reference
#include <RageFileDriverSlice.h>
Public Member Functions
RageFileDriverSlice (RageFileBasic *pFile, int iOffset, int iFileSize)
RageFileDriverSlice (const RageFileDriverSlice &cpy)
~RageFileDriverSlice () override
RageFileDriverSlice * Copy () const override
void DeleteFileWhenFinished ()
int ReadInternal (void *pBuffer, size_t iBytes) override
int WriteInternal (const void *, size_t) override
int SeekInternal (int iOffset) override
int GetFileSize () const override
int GetFD () override
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
RString GetDisplayPath () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Private Attributes
RageFileBasic * m_pFile
int m_iFilePos
int m_iOffset
int m_iFileSize
bool m_bFileOwned
Additional Inherited Members
Protected Member Functions inherited from RageFileObj
virtual int FlushInternal ()
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileDriverSlice() [1/2]
RageFileDriverSlice::RageFileDriverSlice (RageFileBasic * pFile, int iOffset, int iFileSize)
References m_bFileOwned, m_iFilePos, m_iFileSize, m_iOffset, and m_pFile.
Referenced by Copy().
RageFileDriverSlice() [2/2]
RageFileDriverSlice::RageFileDriverSlice (const RageFileDriverSlice & cpy)
References RageFileBasic::Copy(), m_bFileOwned, m_iFilePos, m_iFileSize, m_iOffset, and m_pFile.
~RageFileDriverSlice()
RageFileDriverSlice::~RageFileDriverSlice () override
References m_bFileOwned, and m_pFile.
Member Function Documentation
Copy()
RageFileDriverSlice * RageFileDriverSlice::Copy () const override virtual
Reimplemented from RageFileObj.
References RageFileDriverSlice().
DeleteFileWhenFinished()
void RageFileDriverSlice::DeleteFileWhenFinished () inline
References m_bFileOwned.
Referenced by GunzipFile(), and RageFileDriverZip::Open().
GetFD()
int RageFileDriverSlice::GetFD () inline override virtual
Reimplemented from RageFileObj.
References RageFileBasic::GetFD(), and m_pFile.
GetFileSize()
int RageFileDriverSlice::GetFileSize () const inline override virtual
Implements RageFileObj.
References m_iFileSize.
ReadInternal()
int RageFileDriverSlice::ReadInternal (void * pBuffer, size_t iBytes) override virtual
Implements RageFileObj.
References RageFileBasic::GetError(), m_iFilePos, m_iFileSize, m_iOffset, m_pFile, min(), RageFileBasic::Read(), RageFileBasic::Seek(), and RageFileObj::SetError().
SeekInternal()
int RageFileDriverSlice::SeekInternal (int iOffset) override virtual
Reimplemented from RageFileObj.
References ASSERT, RageFileBasic::GetError(), m_iFilePos, m_iFileSize, m_iOffset, m_pFile, min(), RageFileBasic::Seek(), and RageFileObj::SetError().
WriteInternal()
int RageFileDriverSlice::WriteInternal (const void * , size_t) inline override virtual
Implements RageFileObj.
References RageFileObj::SetError().
Member Data Documentation
m_bFileOwned
bool RageFileDriverSlice::m_bFileOwned private
Referenced by DeleteFileWhenFinished(), RageFileDriverSlice(), and ~RageFileDriverSlice().
m_iFilePos
int RageFileDriverSlice::m_iFilePos private
Referenced by RageFileDriverSlice(), ReadInternal(), and SeekInternal().
m_iFileSize
int RageFileDriverSlice::m_iFileSize private
Referenced by GetFileSize(), RageFileDriverSlice(), ReadInternal(), and SeekInternal().
m_iOffset
int RageFileDriverSlice::m_iOffset private
Referenced by RageFileDriverSlice(), ReadInternal(), and SeekInternal().
m_pFile
RageFileBasic* RageFileDriverSlice::m_pFile private
Referenced by GetFD(), RageFileDriverSlice(), ReadInternal(), SeekInternal(), and ~RageFileDriverSlice().
The documentation for this class was generated from the following files:
RageFileDriverSlice.h
RageFileDriverSlice.cpp