Etterna: LunaGameCommand Class Reference
LunaGameCommand Class Reference
Allow Lua to have access to the GameCommand.
Public Member Functions
LunaGameCommand ()
Public Member Functions inherited from Luna< GameCommand >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetName (T *p, lua_State *L)
static int GetText (T *p, lua_State *L)
static int GetIndex (T *p, lua_State *L)
static int GetMultiPlayer (T *p, lua_State *L)
static int GetStyle (T *p, lua_State *L)
static int GetScreen (T *p, lua_State *L)
static int GetProfileID (T *p, lua_State *L)
static int GetSong (T *p, lua_State *L)
static int GetSteps (T *p, lua_State *L)
static int GetCharacter (T *p, lua_State *L)
static int GetSongGroup (T *p, lua_State *L)
static int GetUrl (T *p, lua_State *L)
static int GetAnnouncer (T *p, lua_State *L)
static int GetPreferredModifiers (T *p, lua_State *L)
static int GetStageModifiers (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< GameCommand >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< GameCommand >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< GameCommand >
using T = GameCommand
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< GameCommand >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the GameCommand.
Constructor & Destructor Documentation
LunaGameCommand()
LunaGameCommand::LunaGameCommand () inline
References ADD_METHOD, GetAnnouncer(), GetCharacter(), GetIndex(), GetMultiPlayer(), GetName(), GetPreferredModifiers(), GetProfileID(), GetScreen(), GetSong(), GetSongGroup(), GetStageModifiers(), GetSteps(), GetStyle(), GetText(), and GetUrl().
Member Function Documentation
GetAnnouncer()
static int LunaGameCommand::GetAnnouncer (T * p, lua_State * L) inline static
References GameCommand::m_sAnnouncer.
Referenced by LunaGameCommand().
GetCharacter()
static int LunaGameCommand::GetCharacter (T * p, lua_State * L) inline static
References GameCommand::m_pCharacter, and Character::PushSelf().
Referenced by LunaGameCommand().
GetIndex()
static int LunaGameCommand::GetIndex (T * p, lua_State * L) inline static
References GameCommand::m_iIndex.
Referenced by LunaGameCommand().
GetMultiPlayer()
static int LunaGameCommand::GetMultiPlayer (T * p, lua_State * L) inline static
References GameCommand::m_MultiPlayer.
Referenced by LunaGameCommand().
GetName()
static int LunaGameCommand::GetName (T * p, lua_State * L) inline static
References GameCommand::m_sName.
Referenced by LunaGameCommand().
GetPreferredModifiers()
static int LunaGameCommand::GetPreferredModifiers (T * p, lua_State * L) inline static
References GameCommand::m_sPreferredModifiers.
Referenced by LunaGameCommand().
GetProfileID()
static int LunaGameCommand::GetProfileID (T * p, lua_State * L) inline static
References GameCommand::m_sProfileID.
Referenced by LunaGameCommand().
GetScreen()
static int LunaGameCommand::GetScreen (T * p, lua_State * L) inline static
References GameCommand::m_sScreen.
Referenced by LunaGameCommand().
GetSong()
static int LunaGameCommand::GetSong (T * p, lua_State * L) inline static
References GameCommand::m_pSong, and Song::PushSelf().
Referenced by LunaGameCommand().
GetSongGroup()
static int LunaGameCommand::GetSongGroup (T * p, lua_State * L) inline static
References GameCommand::m_sSongGroup.
Referenced by LunaGameCommand().
GetStageModifiers()
static int LunaGameCommand::GetStageModifiers (T * p, lua_State * L) inline static
References GameCommand::m_sStageModifiers.
Referenced by LunaGameCommand().
GetSteps()
static int LunaGameCommand::GetSteps (T * p, lua_State * L) inline static
References GameCommand::m_pSteps, and Steps::PushSelf().
Referenced by LunaGameCommand().
GetStyle()
static int LunaGameCommand::GetStyle (T * p, lua_State * L) inline static
References GameCommand::m_pStyle, and Style::PushSelf().
Referenced by LunaGameCommand().
GetText()
static int LunaGameCommand::GetText (T * p, lua_State * L) inline static
References GameCommand::m_sText.
Referenced by LunaGameCommand().
GetUrl()
static int LunaGameCommand::GetUrl (T * p, lua_State * L) inline static
References GameCommand::m_sUrl.
Referenced by LunaGameCommand().
The documentation for this class was generated from the following file:
GameCommand.cpp