Etterna: RageUtil_CharConversions.cpp File Reference
RageUtil_CharConversions.cpp File Reference
#include "global.h"
#include "RageUtil_CharConversions.h"
#include "RageLog.h"
#include "RageUtil.h"
Functions
static bool AttemptEnglishConversion (RString &sText)
static bool AttemptKoreanConversion (RString &sText)
static bool AttemptJapaneseConversion (RString &sText)
bool ConvertString (RString &str, const RString &encodings)
Function Documentation
AttemptEnglishConversion()
static bool AttemptEnglishConversion (RString & sText) static
Referenced by ConvertString().
AttemptJapaneseConversion()
static bool AttemptJapaneseConversion (RString & sText) static
Referenced by ConvertString().
AttemptKoreanConversion()
static bool AttemptKoreanConversion (RString & sText) static
Referenced by ConvertString().
ConvertString()
bool ConvertString (RString & str, const RString & encodings)
References AttemptEnglishConversion(), AttemptJapaneseConversion(), AttemptKoreanConversion(), split(), RageException::Throw(), and Rage::utf8_is_valid().
Referenced by BMSSongLoader::AddToSong(), DWILoader::LoadFromDir(), LoadTags(), and OsuLoader::SetMetadata().