Etterna: JudgedRows Class Reference
JudgedRows Class Reference
Helper class to ensure that each row is only judged once without taking too much memory.
Public Member Functions
JudgedRows ()
bool JudgeRow (int iRow)
void Reset (int iStart)
Private Member Functions
void Resize (size_t iMin)
Private Attributes
vector< bool > m_vRows
int m_iStart { 0 }
int m_iOffset { 0 }
Detailed Description
Helper class to ensure that each row is only judged once without taking too much memory.
Constructor & Destructor Documentation
JudgedRows()
JudgedRows::JudgedRows () inline
References Resize().
Member Function Documentation
JudgeRow()
bool JudgedRows::JudgeRow (int iRow) inline
References m_iOffset, m_iStart, and Resize().
Referenced by Player::UpdateJudgedRows().
Reset()
void JudgedRows::Reset (int iStart) inline
References m_iOffset, and m_iStart.
Referenced by Player::Load().
Resize()
void JudgedRows::Resize (size_t iMin) inline private
References m_iOffset, and max().
Referenced by JudgedRows(), and JudgeRow().
Member Data Documentation
m_iOffset
int JudgedRows::m_iOffset { 0 } private
Referenced by JudgeRow(), Reset(), and Resize().
m_iStart
int JudgedRows::m_iStart { 0 } private
Referenced by JudgeRow(), and Reset().
m_vRows
vector<bool> JudgedRows::m_vRows private
The documentation for this class was generated from the following file:
Player.cpp