Etterna: RageFileManager.cpp File Reference
RageFileManager.cpp File Reference
#include "global.h"
#include "RageFileManager.h"
#include "Foreach.h"
#include "LuaManager.h"
#include "RageFile.h"
#include "RageFileDriver.h"
#include "RageLog.h"
#include "RageThreads.h"
#include "RageUtil.h"
#include "RageUtil_FileDB.h"
#include "arch/ArchHooks/ArchHooks.h"
#include <cerrno>
#include "LuaBinding.h"
Classes
struct LoadedDriver
class RageFileDriverMountpoints
class LunaRageFileManager
Allow Lua to have access to the RageFileManager.
Functions
static void ReferenceAllDrivers (vector< LoadedDriver *> &apDriverList)
static void UnreferenceAllDrivers (vector< LoadedDriver *> &apDriverList)
static RString ExtractDirectory (RString sPath)
static RString ReadlinkRecursive (RString sPath)
static RString GetDirOfExecutable (RString argv0)
static void ChangeToDirOfExecutable (const RString &argv0)
static void NormalizePath (RString &sPath)
bool ilt (const RString &a, const RString &b)
bool ieq (const RString &a, const RString &b)
static void AdjustMountpoint (RString &sMountPoint)
static void AddFilesystemDriver (LoadedDriver *pLoadedDriver, bool bAddToEnd)
static bool SortBySecond (const pair< int, int > &a, const pair< int, int > &b)
static bool PathUsesSlowFlush (const RString &sPath)
bool DoesFileExist (const RString &sPath)
bool IsAFile (const RString &sPath)
bool IsADirectory (const RString &sPath)
int GetFileSizeInBytes (const RString &sPath)
void GetDirListing (const RString &sPath, vector< RString > &AddTo, bool bOnlyDirs, bool bReturnPathToo)
void GetDirListingRecursive (const RString &sDir, const RString &sMatch, vector< RString > &AddTo)
void GetDirListingRecursive (RageFileDriver *prfd, const RString &sDir, const RString &sMatch, vector< RString > &AddTo)
bool DeleteRecursive (RageFileDriver *prfd, const RString &sDir)
bool DeleteRecursive (const RString &sDir)
unsigned int GetHashForFile (const RString &sPath)
unsigned int GetHashForDirectory (const RString &sDir)
Variables
RageFileManager * FILEMAN = NULL
static RageEvent * g_Mutex
static vector< LoadedDriver * > g_pDrivers
static map< const RageFileBasic *, LoadedDriver * > g_mFileDriverMap
static RageFileDriverMountpoints * g_Mountpoints = NULL
Function Documentation
AddFilesystemDriver()
static void AddFilesystemDriver (LoadedDriver * pLoadedDriver, bool bAddToEnd) static
References g_pDrivers, RageFileDriverMountpoints::LoadFromDrivers(), RageMutex::Lock(), and RageMutex::Unlock().
Referenced by RageFileManager::Mount().
AdjustMountpoint()
static void AdjustMountpoint (RString & sMountPoint) static
References ASSERT_M, FixSlashesInPlace(), StdString::CStdStr< CT >::Left(), and StdString::CStdStr< CT >::Right().
Referenced by RageFileManager::Mount().
ChangeToDirOfExecutable()
static void ChangeToDirOfExecutable (const RString & argv0) static
References Basename(), CollapsePath(), GetCwd(), GetDirOfExecutable(), LOG, and RageLog::Warn().
Referenced by RageFileManager::RageFileManager().
DeleteRecursive() [1/2]
bool DeleteRecursive (RageFileDriver * prfd, const RString & sDir)
References ASSERT, DeleteRecursive(), FOREACH_CONST, RageFileDriver::GetDirListing(), IsADirectory(), RageFileManager::Remove(), and StdString::CStdStr< CT >::Right().
Referenced by ProfileManager::DeleteLocalProfile(), RageFileManager::DeleteRecursive(), and DeleteRecursive().
DeleteRecursive() [2/2]
bool DeleteRecursive (const RString & sDir)
References ASSERT, DeleteRecursive(), FOREACH_CONST, GetDirListing(), IsADirectory(), RageFileManager::Remove(), and StdString::CStdStr< CT >::Right().
DoesFileExist()
bool DoesFileExist (const RString & sPath)
References RageFileManager::DoesFileExist().
Referenced by BeginnerHelper::AddPlayer(), ImageCache::CacheImage(), BeginnerHelper::CanUse(), CopyEdits(), BackgroundImpl::Layer::CreateBackground(), DancingCharacters::DancingCharacters(), DirectoryIsEmpty(), CryptManager::GenerateGlobalKeys(), Character::GetModelPath(), ThemeManager::GetPathInfoToRaw(), Song::GetSongAssetPath(), Alsa9Buf::GetSoundCardDebugInfo(), Character::Has2DElems(), HighScore::HasReplayData(), HaveAllCharAnimations(), ScreenHowToPlay::Init(), BGAnimation::LoadFromAniDir(), Foreground::LoadFromSong(), ActorUtil::MakeActor(), ActorUtil::ResolvePath(), sm_main(), SyncFiles(), SongUtil::ValidateCurrentSongPreview(), and SongUtil::ValidateCurrentStepsMusic().
ExtractDirectory()
static RString ExtractDirectory (RString sPath) static
Referenced by GetDirOfExecutable(), and ReadlinkRecursive().
GetDirListing()
void GetDirListing (const RString & sPath, vector< RString > & AddTo, bool bOnlyDirs, bool bReturnPathToo)
References RageFileManager::GetDirListing().
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), ScreenOptionsExportPackageSubPage::BeginScreen(), CharacterManager::CharacterManager(), CopyEdits(), DeleteEmptyDirectories(), DeleteRecursive(), DerefRedir(), SongManager::DifferentialReloadDir(), DirectoryIsEmpty(), DoPlayOnceFromDir(), EmptyDir(), ScreenPackages::EnterURL(), NoteSkinManager::GetAllNoteSkinNamesForGame(), AnnouncerManager::GetAnnouncerNames(), KSFLoader::GetApplicableFiles(), BMSLoader::GetApplicableFiles(), NotesLoaderJson::GetApplicableFiles(), DWILoader::GetApplicableFiles(), OsuLoader::GetApplicableFiles(), SMLoader::GetApplicableFiles(), BackgroundUtil::GetBackgroundEffects(), BackgroundUtil::GetBackgroundTransitions(), GetDirListingRecursive(), Font::GetFontPaths(), BackgroundUtil::GetGlobalBGAnimations(), GetHashForDirectory(), ThemeManager::GetLanguagesForTheme(), ThemeManager::GetOptionalLanguageIniPaths(), NoteSkinManager::GetPathFromDirAndFile(), ThemeManager::GetPathInfoToRaw(), GetRandomFileInDir(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), Character::GetSongSelectIconPath(), Character::GetStageIconPath(), Character::GetTakingABreakPath(), ThemeManager::GetThemeNames(), ScreenGameplayLesson::Init(), DownloadManager::InstallSmzip(), Character::Load(), Profile::LoadAllFromDir(), BGAnimation::LoadFromAniDir(), KSFLoader::LoadFromDir(), LoadGlobalData(), RandomSample::LoadSoundDir(), SongManager::LoadStepManiaSongDir(), Profile::MakeUniqueFileNameNoExtension(), MountTreeOfZips(), Nsis(), ProfileManager::RefreshLocalProfilesFromDisk(), NoteSkinManager::RefreshNoteSkinData(), ScreenPackages::RefreshPackages(), ActorUtil::ResolvePath(), ThemeManager::RunLuaScripts(), SongManager::SanityCheckGroupDir(), Song::Save(), ScreenGameplay::SaveReplay(), LoadingWindow_MacOSX::SetSplash(), SyncFiles(), CryptManager::VerifyFileWithFile(), and LoadingWindow_Win32::WndProc().
GetDirListingRecursive() [1/2]
void GetDirListingRecursive (const RString & sDir, const RString & sMatch, vector< RString > & AddTo)
References ASSERT, GetDirListing(), IsADirectory(), and StdString::CStdStr< CT >::Right().
Referenced by DownloadManager::InstallSmzip().
GetDirListingRecursive() [2/2]
void GetDirListingRecursive (RageFileDriver * prfd, const RString & sDir, const RString & sMatch, vector< RString > & AddTo)
References ASSERT, RageFileDriver::GetDirListing(), RageFileDriver::GetFileType(), StdString::CStdStr< CT >::Right(), and RageFileManager::TYPE_DIR.
GetDirOfExecutable()
static RString GetDirOfExecutable (RString argv0) static
References ExtractDirectory(), FOREACH, GetCwd(), MAX_PATH, ReadlinkRecursive(), StdString::CStdStr< CT >::Replace(), and split().
Referenced by ChangeToDirOfExecutable().
GetFileSizeInBytes()
int GetFileSizeInBytes (const RString & sPath)
References RageFileManager::GetFileSizeInBytes().
GetHashForDirectory()
unsigned int GetHashForDirectory (const RString & sDir)
References GetDirListing(), GetHashForFile(), and GetHashForString().
Referenced by SongCacheIndex::CacheSong(), SongCacheIndex::DeleteSongFromDB(), SongManager::InitSongsFromDisk(), and SongCacheIndex::LoadSongFromCache().
GetHashForFile()
unsigned int GetHashForFile (const RString & sPath)
References RageFileManager::GetFileHash().
Referenced by ImageCache::CacheImage(), ImageCache::CacheImageInternal(), and GetHashForDirectory().
ieq()
bool ieq (const RString & a, const RString & b)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by RageFileManager::GetDirListing().
ilt()
bool ilt (const RString & a, const RString & b)
References StdString::CStdStr< CT >::CompareNoCase().
Referenced by RageFileManager::GetDirListing().
IsADirectory()
bool IsADirectory (const RString & sPath)
References RageFileManager::IsADirectory().
Referenced by BGAnimation::AddLayersFromAniDir(), RageSoundDriver_OSS::CheckOSSVersion(), DeleteEmptyDirectories(), DeleteRecursive(), EmptyDir(), GetDirListingRecursive(), ActorUtil::GetFileType(), LoadALSA(), BGAnimation::LoadFromAniDir(), and MountTreeOfZips().
IsAFile()
bool IsAFile (const RString & sPath)
References RageFileManager::IsAFile().
Referenced by BMSSong::AllocateKeysound(), ScreenSelectMusic::CheckBackgroundRequests(), BMSSong::GetBackground(), GetFileContents(), Song::GetFileHash(), Profile::HandleStatsPrefixChange(), Song::HasBackground(), Song::HasBanner(), Song::HasCDImage(), Song::HasCDTitle(), Song::HasDisc(), Song::HasInstrumentTrack(), Song::HasJacket(), Song::HasLyrics(), Song::HasMusic(), Song::HasPreviewVid(), FontPage::Load(), Profile::LoadEditableDataFromDir(), XMLProfile::LoadEttFromDir(), Sprite::LoadFromCached(), Banner::LoadFromCachedBanner(), FadingBanner::LoadFromCachedBanner(), Model::LoadMaterialsFromMilkshapeAscii(), XMLProfile::LoadStatsFromDir(), XMLProfile::LoadStatsXmlForConversion(), MountTreeOfZips(), Profile::SaveMachinePublicKeyToDir(), Song::SaveToDWIFile(), Song::SaveToETTFile(), Song::SaveToSMFile(), Song::SaveToSSCFile(), CryptManager::Sign(), StartMusic(), and SMLoader::TidyUpData().
NormalizePath()
static void NormalizePath (RString & sPath) static
References CollapsePath(), and FixSlashesInPlace().
Referenced by RageFileManager::CacheFile(), RageFileManager::FlushDirCache(), RageFileManager::GetDirListing(), RageFileManager::GetFileHash(), RageFileManager::GetFileSizeInBytes(), RageFileManager::GetFileType(), RageFileManager::Move(), RageFileManager::Open(), RageFileManager::Remove(), and RageFileManager::ResolvePath().
PathUsesSlowFlush()
static bool PathUsesSlowFlush (const RString & sPath) static
References ARRAYLEN.
Referenced by RageFileManager::Open().
ReadlinkRecursive()
static RString ReadlinkRecursive (RString sPath) static
References ExtractDirectory().
Referenced by GetDirOfExecutable().
ReferenceAllDrivers()
static void ReferenceAllDrivers (vector< LoadedDriver *> & apDriverList) static
References g_pDrivers, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by RageFileManager::GetDirListing(), RageFileManager::GetFileHash(), RageFileManager::GetFileSizeInBytes(), RageFileManager::GetFileType(), RageFileManager::Move(), RageFileManager::OpenForReading(), RageFileManager::OpenForWriting(), RageFileManager::Remove(), and RageFileManager::ResolvePath().
SortBySecond()
static bool SortBySecond (const pair< int, int > & a, const pair< int, int > & b) static
Referenced by RageFileManager::OpenForWriting().
UnreferenceAllDrivers()
static void UnreferenceAllDrivers (vector< LoadedDriver *> & apDriverList) static
References RageEvent::Broadcast(), RageMutex::Lock(), and RageMutex::Unlock().
Referenced by RageFileManager::GetDirListing(), RageFileManager::GetFileHash(), RageFileManager::GetFileSizeInBytes(), RageFileManager::GetFileType(), RageFileManager::Move(), RageFileManager::OpenForReading(), RageFileManager::OpenForWriting(), RageFileManager::Remove(), and RageFileManager::ResolvePath().
Variable Documentation
FILEMAN
RageFileManager* FILEMAN = NULL
Referenced by SongManager::AddGroup(), FileTransfer::Cancel(), ScreenPackages::CancelDownload(), RageFile::Close(), convert_xmls_in_dir(), SongCacheIndex::DeleteDB(), DeleteEmptyDirectories(), ProfileManager::DeleteLocalProfile(), SongManager::DifferentialReload(), EmptyDir(), EmptyTempDLFileDir(), BackgroundLoader::FinishedWithCachedFile(), CryptManager::GenerateRSAKeyToFile(), Song::GetCacheFile(), NoteSkinManager::GetPath(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), Song::HasAutosaveFile(), FileTransfer::HTTPUpdate(), SongManager::InitSongsFromDisk(), DownloadManager::InstallSmzip(), InstallSmzipOsArg(), actor_template_t::load_node(), Profile::LoadAllFromDir(), DBProfile::LoadDBFromDir(), Profile::LoadEditableDataFromDir(), SMLoader::LoadEditFromFile(), SSCLoader::LoadEditFromFile(), XMLProfile::LoadEttFromDir(), Song::LoadFromSongDir(), NoteSkinManager::LoadNoteSkinDataRecursive(), XMLProfile::LoadStatsFromDir(), XMLProfile::LoadStatsXmlForConversion(), BackgroundLoader::LoadThread(), Profile::LoadTypeFromDir(), Profile::MakeUniqueFileNameNoExtension(), Profile::MergeScoresFromOtherProfile(), ArchHooks::MountInitialFilesystems(), MountTreeOfZips(), ArchHooks::MountUserFilesystems(), XMLProfile::MoveBackupToDir(), DBProfile::MoveBackupToDir(), Profile::MoveBackupToDir(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), RageFile::Open(), SongCacheIndex::OpenDB(), BMSSong::PrecacheBackgrounds(), Song::ReloadFromSongDir(), ThemeManager::ReloadMetrics(), Song::RemoveAutosave(), ActorUtil::ResolvePath(), Song::Save(), Profile::SaveAllToDir(), DBProfile::SaveDBToDir(), XMLProfile::SaveEttXmlToDir(), XMLProfile::SaveStatsXmlToDir(), ShutdownGame(), sm_main(), SongCacheIndex::SongCacheIndex(), SyncFiles(), ThreadedFileWorker::ThreadedFileWorker(), Song::TidyUpData(), CryptManager::VerifyFileWithFile(), WriteFile(), HighScoreImpl::WriteReplayData(), BackgroundLoader::~BackgroundLoader(), Download::~Download(), and ThreadedFileWorker::~ThreadedFileWorker().
g_mFileDriverMap
map<const RageFileBasic*, LoadedDriver*> g_mFileDriverMap static
Referenced by RageFileManager::CacheFile(), and RageFileManager::OpenForWriting().
g_Mountpoints
RageFileDriverMountpoints* g_Mountpoints = NULL static
Referenced by RageFileManager::RageFileManager().
g_Mutex
RageEvent* g_Mutex static
Referenced by RageFileManager::~RageFileManager().
g_pDrivers
vector<LoadedDriver*> g_pDrivers static
Referenced by AddFilesystemDriver(), RageFileManager::FlushDirCache(), RageFileManager::GetFileDriver(), RageFileManager::GetLoadedDrivers(), RageFileManager::IsMounted(), RageFileManager::RageFileManager(), ReferenceAllDrivers(), RageFileManager::ReleaseFileDriver(), RageFileManager::Unmount(), and RageFileManager::~RageFileManager().