Etterna: OsuLoader Namespace Reference
OsuLoader Namespace Reference
Functions
map< string, map< string, string > > ParseFileString (string fileContents)
void SeparateTagsAndContents (string fileContents, vector< string > &tagsOut, vector< vector< string >> &contentsOut)
void SetMetadata (map< string, map< string, string >>, Song &out)
void SetTimingData (map< string, map< string, string >>, Song &out)
void GetApplicableFiles (const RString &sPath, vector< RString > &out)
bool LoadFromDir (const RString &sPath, Song &out)
void LoadNoteDataFromParsedData (Steps *out, map< string, map< string, string >> parsedData)
bool LoadNoteDataFromSimfile (const RString &path, Steps &out)
bool LoadChartData (Song *song, Steps *chart, map< string, map< string, string >> parsedData)
int MsToNoteRow (int ms, Song *song)
Function Documentation
GetApplicableFiles()
void OsuLoader::GetApplicableFiles (const RString & sPath, vector< RString > & out)
References GetDirListing().
Referenced by NotesLoader::LoadFromDir().
LoadChartData()
bool OsuLoader::LoadChartData (Song * song, Steps * chart, map< string, map< string, string >> parsedData)
References Difficulty_Edit, Song::GetAllSteps(), Steps::m_StepsType, min(), Steps::SetDifficulty(), Steps::SetMeter(), Steps::SetSavedToDisk(), StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, StepsType_Invalid, StepsType_kb7_single, StepsType_pump_single, and Steps::TidyUpData().
Referenced by LoadFromDir().
LoadFromDir()
bool OsuLoader::LoadFromDir (const RString & sPath, Song & out)
References Song::AddSteps(), Song::CreateSteps(), f, BMSLoader::GetApplicableFiles(), LoadChartData(), LoadNoteDataFromParsedData(), RageFile::Open(), ParseFileString(), RageFile::Read(), Steps::SetFilename(), SetMetadata(), and SetTimingData().
Referenced by NotesLoader::LoadFromDir().
LoadNoteDataFromParsedData()
void OsuLoader::LoadNoteDataFromParsedData (Steps * out, map< string, map< string, string >> parsedData)
References NoteData::AddHoldNote(), TimingData::m_fBeat0OffsetInSeconds, Steps::m_pSong, Song::m_SongTiming, max(), min(), OsuNote::ms, OsuHold::msStart, MsToNoteRow(), Steps::SetNoteData(), NoteData::SetNumTracks(), NoteData::SetTapNote(), split(), TAP_ORIGINAL_HOLD_HEAD, TAP_ORIGINAL_LIFT, and TAP_ORIGINAL_TAP.
Referenced by LoadFromDir(), and LoadNoteDataFromSimfile().
LoadNoteDataFromSimfile()
bool OsuLoader::LoadNoteDataFromSimfile (const RString & path, Steps & out)
References f, RageFile::GetError(), RageFile::GetFileSize(), LoadNoteDataFromParsedData(), LOG, RageFile::Open(), ParseFileString(), RageFile::Read(), and RageLog::UserLog().
Referenced by Steps::GetNoteDataFromSimfile().
MsToNoteRow()
int OsuLoader::MsToNoteRow (int ms, Song * song)
References TimingData::GetBeatFromElapsedTimeNoOffset(), TimingData::m_fBeat0OffsetInSeconds, and Song::m_SongTiming.
Referenced by LoadNoteDataFromParsedData(), and SetTimingData().
ParseFileString()
map< string, map< string, string > > OsuLoader::ParseFileString (string fileContents)
References SeparateTagsAndContents().
Referenced by LoadFromDir(), and LoadNoteDataFromSimfile().
SeparateTagsAndContents()
void OsuLoader::SeparateTagsAndContents (string fileContents, vector< string > & tagsOut, vector< vector< string >> & contentsOut)
Referenced by ParseFileString().
SetMetadata()
void OsuLoader::SetMetadata (map< string, map< string, string >> parsedData, Song & out)
References ConvertString(), Song::m_sArtist, Song::m_sGenre, Song::m_sMainTitle, Song::m_sMusicFile, and Song::m_sSubTitle.
Referenced by LoadFromDir().
SetTimingData()
void OsuLoader::SetTimingData (map< string, map< string, string >> parsedData, Song & out)
References TimingData::AddSegment(), DISPLAY_BPM_ACTUAL, Song::m_DisplayBPMType, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_SongTiming, max(), MsToNoteRow(), second, and split().
Referenced by LoadFromDir().