Etterna: BackgroundUtil.cpp File Reference
BackgroundUtil.cpp File Reference
#include "BackgroundUtil.h"
#include "ActorUtil.h"
#include "Background.h"
#include "Foreach.h"
#include "IniFile.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "Song.h"
#include "global.h"
#include <set>
Macros
#define COMPARE(x)
Functions
static void StripCvsAndSvn (vector< RString > &vsPathsToStrip, vector< RString > &vsNamesToStrip)
int CompareBackgroundChanges (const BackgroundChange &seg1, const BackgroundChange &seg2)
static void GetFilterToFileNames (const RString sBaseDir, const Song *pSong, set< RString > &vsPossibleFileNamesOut)
Variables
const RString BACKGROUND_EFFECTS_DIR = "BackgroundEffects/"
const RString BACKGROUND_TRANSITIONS_DIR = "BackgroundTransitions/"
const RString BG_ANIMS_DIR = "BGAnimations/"
const RString VISUALIZATIONS_DIR = "Visualizations/"
const RString RANDOMMOVIES_DIR = "RandomMovies/"
const RString SONG_MOVIES_DIR = "SongMovies/"
const RString RANDOM_BACKGROUND_FILE = "-random-"
const RString NO_SONG_BG_FILE = "-nosongbg-"
const RString SONG_BACKGROUND_FILE = "songbackground"
const RString SBE_UpperLeft = "UpperLeft"
const RString SBE_Centered = "Centered"
const RString SBE_StretchNormal = "StretchNormal"
const RString SBE_StretchNoLoop = "StretchNoLoop"
const RString SBE_StretchRewind = "StretchRewind"
const RString SBT_CrossFade = "CrossFade"
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if ((x) < other.x)                                                         \
        return true;                                                           \
    else if ((x) > other.x)                                                    \
        return false;
Referenced by BackgroundDef::operator<().
Function Documentation
CompareBackgroundChanges()
int CompareBackgroundChanges (const BackgroundChange & seg1, const BackgroundChange & seg2)
References BackgroundChange::m_fStartBeat.
Referenced by BackgroundUtil::AddBackgroundChange(), and BackgroundUtil::SortBackgroundChangesArray().
GetFilterToFileNames()
static void GetFilterToFileNames (const RString sBaseDir, const Song * pSong, set< RString > & vsPossibleFileNamesOut) static
References ASSERT, ASSERT_M, FOREACH_CONST_Attr, XNode::GetChild(), Song::m_sGenre, Song::m_sGroupName, and ssprintf().
StripCvsAndSvn()
static void StripCvsAndSvn (vector< RString > & vsPathsToStrip, vector< RString > & vsNamesToStrip) static
References ASSERT.
Referenced by ScreenOptionsExportPackageSubPage::BeginScreen(), CharacterManager::CharacterManager(), SongManager::DifferentialReloadDir(), NoteSkinManager::GetAllNoteSkinNamesForGame(), AnnouncerManager::GetAnnouncerNames(), BackgroundUtil::GetBackgroundEffects(), BackgroundUtil::GetBackgroundTransitions(), BackgroundUtil::GetGlobalBGAnimations(), BackgroundUtil::GetGlobalRandomMovies(), BackgroundUtil::GetSongBGAnimations(), BackgroundUtil::GetSongBitmaps(), BackgroundUtil::GetSongMovies(), ThemeManager::GetThemeNames(), SongManager::LoadStepManiaSongDir(), NoteSkinManager::RefreshNoteSkinData(), and ThemeManager::RunLuaScripts().
Variable Documentation
BACKGROUND_EFFECTS_DIR
const RString BACKGROUND_EFFECTS_DIR = "BackgroundEffects/"
BACKGROUND_TRANSITIONS_DIR
const RString BACKGROUND_TRANSITIONS_DIR = "BackgroundTransitions/"
BG_ANIMS_DIR
const RString BG_ANIMS_DIR = "BGAnimations/"
NO_SONG_BG_FILE
const RString NO_SONG_BG_FILE = "-nosongbg-"
Referenced by SMLoader::TidyUpData().
RANDOM_BACKGROUND_FILE
const RString RANDOM_BACKGROUND_FILE = "-random-"
Referenced by BackgroundImpl::LoadFromSong().
RANDOMMOVIES_DIR
const RString RANDOMMOVIES_DIR = "RandomMovies/"
SBE_Centered
const RString SBE_Centered = "Centered"
Referenced by BMSSongLoader::AddToSong(), and BackgroundImpl::Layer::CreateBackground().
SBE_StretchNoLoop
const RString SBE_StretchNoLoop = "StretchNoLoop"
Referenced by BMSSongLoader::AddToSong(), SMLoader::LoadFromBGChangesString(), Song::TidyUpData(), and BackgroundChange::ToString().
SBE_StretchNormal
const RString SBE_StretchNormal = "StretchNormal"
Referenced by BackgroundImpl::Layer::CreateBackground().
SBE_StretchRewind
const RString SBE_StretchRewind = "StretchRewind"
Referenced by SMLoader::LoadFromBGChangesString(), and BackgroundChange::ToString().
SBE_UpperLeft
const RString SBE_UpperLeft = "UpperLeft"
Referenced by BackgroundImpl::Layer::CreateBackground().
SBT_CrossFade
const RString SBT_CrossFade = "CrossFade"
Referenced by BackgroundChange::ToString().
SONG_BACKGROUND_FILE
const RString SONG_BACKGROUND_FILE = "songbackground"
Referenced by BackgroundImpl::Layer::CreateBackground(), and BackgroundImpl::LoadFromSong().
SONG_MOVIES_DIR
const RString SONG_MOVIES_DIR = "SongMovies/"
VISUALIZATIONS_DIR
const RString VISUALIZATIONS_DIR = "Visualizations/"