Etterna: NotesLoader Namespace Reference
NotesLoader Namespace Reference
Base class for step file loaders.
Functions
void GetMainAndSubTitlesFromFullTitle (const RString &sFullTitle, RString &sMainTitleOut, RString &sSubTitleOut)
Identify the main and sub titles from a full title.
bool LoadFromDir (const RString &sPath, Song &out, set< RString > &BlacklistedImages, bool load_autosave=false)
Attempt to load a Song from the given directory.
Detailed Description
Base class for step file loaders.
Function Documentation
GetMainAndSubTitlesFromFullTitle()
void NotesLoader::GetMainAndSubTitlesFromFullTitle (const RString & sFullTitle, RString & sMainTitleOut, RString & sSubTitleOut)
Identify the main and sub titles from a full title.
Parameters
sFullTitle the full title.
sMainTitleOut the eventual main title.
sSubTitleOut the ventual sub title.
References ARRAYLEN, and StdString::CStdStr< CT >::Left().
Referenced by BMSSongLoader::AddToSong(), DWILoader::LoadFromDir(), and Song::TidyUpData().
LoadFromDir()
bool NotesLoader::LoadFromDir (const RString & sPath, Song & out, set< RString > & BlacklistedImages, bool load_autosave = false)
Attempt to load a Song from the given directory.
Parameters
sPath the path to the file.
out the Song in question.
BlacklistedImages images to exclude (DWI files only for some reason).
Returns
its success or failure.
References BMSLoader::GetApplicableFiles(), KSFLoader::GetApplicableFiles(), DWILoader::GetApplicableFiles(), OsuLoader::GetApplicableFiles(), SMLoader::GetApplicableFiles(), KSFLoader::LoadFromDir(), BMSLoader::LoadFromDir(), DWILoader::LoadFromDir(), SMLoader::LoadFromDir(), and OsuLoader::LoadFromDir().
Referenced by Song::LoadFromSongDir().