Etterna: LunaFadingBanner Class Reference
LunaFadingBanner Class Reference
Allow Lua to have access to the FadingBanner.
Public Member Functions
LunaFadingBanner ()
Public Member Functions inherited from Luna< FadingBanner >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int scaletoclipped (T *p, lua_State *L)
static int ScaleToClipped (T *p, lua_State *L)
static int LoadFromSong (T *p, lua_State *L)
static int LoadIconFromCharacter (T *p, lua_State *L)
static int LoadCardFromCharacter (T *p, lua_State *L)
static int LoadFromSongGroup (T *p, lua_State *L)
static int LoadRandom (T *p, lua_State *L)
static int LoadRoulette (T *p, lua_State *L)
static int LoadFallback (T *p, lua_State *L)
static int LoadFromSortOrder (T *p, lua_State *L)
static int GetLatestIndex (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< FadingBanner >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< FadingBanner >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< FadingBanner >
using T = FadingBanner
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< FadingBanner >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the FadingBanner.
Constructor & Destructor Documentation
LunaFadingBanner()
LunaFadingBanner::LunaFadingBanner () inline
References ADD_METHOD, GetLatestIndex(), LoadCardFromCharacter(), LoadFallback(), LoadFromSong(), LoadFromSongGroup(), LoadFromSortOrder(), LoadIconFromCharacter(), LoadRandom(), LoadRoulette(), scaletoclipped(), and ScaleToClipped().
Member Function Documentation
GetLatestIndex()
static int LunaFadingBanner::GetLatestIndex (T * p, lua_State * L) inline static
References FadingBanner::GetLatestIndex().
Referenced by LunaFadingBanner().
LoadCardFromCharacter()
static int LunaFadingBanner::LoadCardFromCharacter (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and FadingBanner::LoadIconFromCharacter().
Referenced by LunaFadingBanner().
LoadFallback()
static int LunaFadingBanner::LoadFallback (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and FadingBanner::LoadFallback().
Referenced by LunaFadingBanner().
LoadFromSong()
static int LunaFadingBanner::LoadFromSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and FadingBanner::LoadFromSong().
Referenced by LunaFadingBanner().
LoadFromSongGroup()
static int LunaFadingBanner::LoadFromSongGroup (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FadingBanner::LoadFromSongGroup(), and SArg.
Referenced by LunaFadingBanner().
LoadFromSortOrder()
static int LunaFadingBanner::LoadFromSortOrder (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, FadingBanner::LoadFromSortOrder(), and SortOrder_Invalid.
Referenced by LunaFadingBanner().
LoadIconFromCharacter()
static int LunaFadingBanner::LoadIconFromCharacter (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and FadingBanner::LoadIconFromCharacter().
Referenced by LunaFadingBanner().
LoadRandom()
static int LunaFadingBanner::LoadRandom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and FadingBanner::LoadRandom().
Referenced by LunaFadingBanner().
LoadRoulette()
static int LunaFadingBanner::LoadRoulette (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and FadingBanner::LoadRoulette().
Referenced by LunaFadingBanner().
scaletoclipped()
static int LunaFadingBanner::scaletoclipped (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and FadingBanner::ScaleToClipped().
Referenced by LunaFadingBanner().
ScaleToClipped()
static int LunaFadingBanner::ScaleToClipped (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and FadingBanner::ScaleToClipped().
Referenced by LunaFadingBanner().
The documentation for this class was generated from the following file:
FadingBanner.cpp