Etterna: ArchHooks_MacOSX.mm File Reference
ArchHooks_MacOSX.mm File Reference
#include "global.h"
#include "ArchHooks_MacOSX.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Unix/CrashHandler.h"
#include "archutils/Unix/SignalHandler.h"
#include "SpecialFiles.h"
#include "ProductInfo.h"
#include <CoreServices/CoreServices.h>
#include <ApplicationServices/ApplicationServices.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <mach/mach.h>
#include <mach/mach_time.h>
#include <IOKit/graphics/IOGraphicsLib.h>
#include <IOKit/IOKitLib.h>
#include <IOKit/IOKitKeys.h>
#include <IOKit/network/IOEthernetInterface.h>
#include <IOKit/network/IONetworkInterface.h>
#include <IOKit/network/IOEthernetController.h>
#import <Foundation/Foundation.h>
#include "RageFileManager.h"
Macros
#define GET_PARAM(name, var) (size = sizeof(var), sysctlbyname(name, &var, &size, NULL, 0))
Functions
static bool IsFatalSignal (int signal)
static bool DoCleanShutdown (int signal, siginfo_t *si, const ucontext_t *uc)
static bool DoCrashSignalHandler (int signal, siginfo_t *si, const ucontext_t *uc)
static bool DoEmergencyShutdown (int signal, siginfo_t *si, const ucontext_t *us)
static void PathForFolderType (char dir[PATH_MAX], OSType folderType)
static int GetIntValue (CFTypeRef r)
Macro Definition Documentation
GET_PARAM
#define GET_PARAM (name, var) (size = sizeof(var), sysctlbyname(name, &var, &size, NULL, 0))
Referenced by ArchHooks_MacOSX::DumpDebugInfo().
Function Documentation
DoCleanShutdown()
static bool DoCleanShutdown (int signal, siginfo_t * si, const ucontext_t * uc) static
References IsFatalSignal(), and ArchHooks::SetUserQuit().
Referenced by ArchHooks_MacOSX::Init().
DoCrashSignalHandler()
static bool DoCrashSignalHandler (int signal, siginfo_t * si, const ucontext_t * uc) static
References IsFatalSignal().
Referenced by ArchHooks_Unix::Init(), and ArchHooks_MacOSX::Init().
DoEmergencyShutdown()
static bool DoEmergencyShutdown (int signal, siginfo_t * si, const ucontext_t * us) static
References IsFatalSignal().
Referenced by EmergencyShutdown(), and ArchHooks_MacOSX::Init().
GetIntValue()
static int GetIntValue (CFTypeRef r) inline static
Referenced by ArchHooks_MacOSX::GetDisplayAspectRatio().
IsFatalSignal()
static bool IsFatalSignal (int signal) static
Referenced by DoCleanShutdown(), DoCrashSignalHandler(), and DoEmergencyShutdown().
PathForFolderType()
static void PathForFolderType (char dir[PATH_MAX], OSType folderType) static
References FAIL_M, and ssprintf().
Referenced by ArchHooks::MountUserFilesystems().