Etterna: ActorFrame Class Reference
ActorFrame Class Reference
A container for other Actors.
#include <ActorFrame.h>
Public Member Functions
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushSelf (lua_State *L) override
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
virtual void Update (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Member Functions
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
A container for other Actors.
Constructor & Destructor Documentation
ActorFrame() [1/2]
ActorFrame::ActorFrame ()
References m_ambientColor, m_bDeleteChildren, m_bDrawByZPosition, m_bLighting, m_bOverrideLighting, m_bPropagateCommands, m_diffuseColor, m_DrawFunction, m_fFOV, m_fUpdateRate, m_fVanishX, m_fVanishY, m_lightDirection, m_specularColor, m_UpdateFunction, SCREEN_CENTER_X, SCREEN_CENTER_Y, and LuaReference::SetFromNil().
Referenced by Copy().
ActorFrame() [2/2]
ActorFrame::ActorFrame (const ActorFrame & cpy)
References AddChild(), CPY, m_ambientColor, m_bDeleteChildren, m_bDrawByZPosition, m_bLighting, m_bOverrideLighting, m_bPropagateCommands, m_diffuseColor, m_DrawFunction, m_fFOV, m_fUpdateRate, m_fVanishX, m_fVanishY, m_lightDirection, m_specularColor, m_SubActors, and m_UpdateFunction.
~ActorFrame()
ActorFrame::~ActorFrame () override
References DeleteAllChildren(), and m_bDeleteChildren.
Member Function Documentation
AddChild()
void ActorFrame::AddChild (Actor * pActor) virtual
Add a new child to the ActorFrame.
Parameters
pActor the new Actor to add.
References ASSERT, Actor::GetLineage(), Actor::GetName(), m_SubActors, Actor::SetParent(), and ssprintf().
Referenced by ActorFrame(), LunaActorFrame::AddChildFromPath(), BGAnimation::AddLayersFromAniDir(), Background::Background(), BrightnessOverlay::BrightnessOverlay(), FadingBanner::FadingBanner(), GrooveRadar::GrooveRadar(), ScreenSyncOverlay::Init(), ScreenGameplaySyncMachine::Init(), ScreenNetEvaluation::Init(), ScreenPlayerOptions::Init(), ScreenGameplayLesson::Init(), ScreenInstallOverlay::Init(), ScreenSystemLayer::Init(), ScreenNetSelectBase::Init(), ScreenTestSound::Init(), ScreenNetRoom::Init(), ScreenReloadSongs::Init(), ScreenWithMenuElements::Init(), ScreenHowToPlay::Init(), ScreenMapControllers::Init(), ScreenPackages::Init(), ScreenStatsOverlay::Init(), ScoreDisplayLifeTime::Init(), BeginnerHelper::Init(), ScreenNetSelectMusic::Init(), ScreenDebugOverlay::Init(), ScreenSetTime::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), BackgroundImpl::Init(), Player::Init(), ScreenGameplay::Init(), ScreenTextEntry::Init(), ScreenTextEntryVisual::Init(), ScreenOptions::InitMenu(), OptionRow::InitText(), LifeMeterBar::LifeMeterBar(), MeterDisplay::Load(), DualScrollBar::Load(), ModIcon::Load(), GradeDisplay::Load(), RoomInfoDisplay::Load(), HoldJudgment::Load(), Transition::Load(), ReceptorArrow::Load(), ComboGraph::Load(), PercentageDisplay::Load(), LifeMeterBattery::Load(), ModIconRow::Load(), TextBanner::Load(), LifeMeterTime::Load(), GraphDisplay::Load(), ReceptorArrowRow::Load(), MenuTimer::Load(), StepsDisplay::Load(), StreamDisplay::Load(), WheelBase::Load(), PaneDisplay::Load(), OptionsList::Load(), RoomWheelItem::Load(), ScreenMapControllers::ActionRow::Load(), LoadChildrenFromNode(), BGAnimation::LoadFromAniDir(), BGAnimationLayer::LoadFromAniLayerFile(), DynamicActorScroller::LoadFromNode(), BGAnimation::LoadFromNode(), MeterDisplay::LoadFromNode(), BGAnimationLayer::LoadFromNode(), StepsDisplayList::LoadFromNode(), PercentageDisplay::LoadFromNode(), Foreground::LoadFromSong(), ControllerStateDisplay::LoadInternal(), LyricDisplay::LyricDisplay(), ModIcon::ModIcon(), MusicWheelItem::MusicWheelItem(), NoteField::NoteField(), OptionRow::OptionRow(), OptionsCursor::OptionsCursor(), ScreenNetEvaluation::RedoUserTexts(), RoomWheelItem::RoomWheelItem(), ScoreDisplayNormal::ScoreDisplayNormal(), ScoreDisplayOni::ScoreDisplayOni(), ScoreDisplayPercentage::ScoreDisplayPercentage(), ScrollBar::ScrollBar(), ComboGraph::Set(), GraphDisplay::Set(), OptionListRow::SetFromHandler(), RoomInfoDisplay::SetRoomInfo(), SnapDisplay::SnapDisplay(), TextBanner::TextBanner(), TransferChildren(), and ScreenNetSelectBase::UpdateUsers().
AutoLoadChildren()
virtual bool ActorFrame::AutoLoadChildren () const inline virtual
Reimplemented in ActorFrameAutoDeleteChildren, ActorScrollerAutoDeleteChildren, ActorFrameTextureAutoDeleteChildren, DynamicActorScrollerAutoDeleteChildren, and ComboGraph.
Referenced by LoadFromNode().
BeginDraw()
void ActorFrame::BeginDraw () override virtual
Start the drawing and push the transform on the world matrix stack.
Reimplemented from Actor.
References Actor::BeginDraw(), RageDisplay::CameraPushMatrix(), DISPLAY, RageDisplay::LoadMenuPerspective(), m_ambientColor, m_bLighting, m_bOverrideLighting, m_diffuseColor, m_fFOV, m_fVanishX, m_fVanishY, m_lightDirection, m_specularColor, SCREEN_HEIGHT, SCREEN_WIDTH, RageDisplay::SetLightDirectional(), and RageDisplay::SetLighting().
Copy()
ActorFrame * ActorFrame::Copy () const override virtual
Reimplemented from Actor.
Reimplemented in ActorFrameAutoDeleteChildren, ActorScrollerAutoDeleteChildren, RoomWheelItem, ControllerStateDisplay, ActorFrameTextureAutoDeleteChildren, WheelItemBase, MusicWheelItem, PaneDisplay, SongMeterDisplay, ActorScroller, StepsDisplay, DynamicActorScrollerAutoDeleteChildren, PercentageDisplay, ModIconRow, BGAnimation, ComboGraph, StepsDisplayList, GraphDisplay, GradeDisplay, MeterDisplay, GrooveRadar, TextBanner, ActorFrameTexture, FadingBanner, HoldJudgment, and DynamicActorScroller.
References ActorFrame().
DeleteAllChildren()
void ActorFrame::DeleteAllChildren ()
References m_SubActors.
Referenced by OptionRow::Clear(), OptionRow::InitText(), BGAnimation::LoadFromAniDir(), LunaActorFrame::RemoveAllChildren(), ~ActorFrame(), BGAnimation::~BGAnimation(), and BGAnimationLayer::~BGAnimationLayer().
DeleteChildrenWhenDone()
void ActorFrame::DeleteChildrenWhenDone (bool bDelete = true) inline
References m_bDeleteChildren.
Referenced by ActorFrameAutoDeleteChildren::ActorFrameAutoDeleteChildren(), ActorFrameTextureAutoDeleteChildren::ActorFrameTextureAutoDeleteChildren(), ActorScrollerAutoDeleteChildren::ActorScrollerAutoDeleteChildren(), ComboGraph::ComboGraph(), and DynamicActorScrollerAutoDeleteChildren::DynamicActorScrollerAutoDeleteChildren().
DrawPrimitives()
void ActorFrame::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from Actor.
Reimplemented in ScreenGameplay, BackgroundImpl, GrooveRadar::GrooveRadarValueMap, Player, WheelItemBase, ActorFrameTexture, DancingCharacters, FadingBanner, BeginnerHelper, ActorScroller, NoteField, ReceptorArrow, ReceptorArrowRow, GhostArrowRow, and ScreenSandbox.
References Actor::TweenState::diffuse, LuaManager::Get(), Actor::TweenState::glow, LuaReference::IsNil(), L, LUA, Actor::m_bClearZBuffer, m_bDrawByZPosition, m_DrawFunction, Actor::m_pTempState, m_SubActors, LuaReference::PushSelf(), PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptErrorFmt(), LuaHelpers::RunScriptOnStack(), ActorUtil::SortByZPosition(), and unlikely.
Referenced by ScreenSandbox::DrawPrimitives(), ReceptorArrow::DrawPrimitives(), BeginnerHelper::DrawPrimitives(), ActorFrameTexture::DrawPrimitives(), WheelItemBase::DrawPrimitives(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), BackgroundImpl::DrawPrimitives(), and ScreenGameplay::DrawPrimitives().
EndDraw()
void ActorFrame::EndDraw () override virtual
Pop the transform from the world matrix stack.
Reimplemented from Actor.
References RageDisplay::CameraPopMatrix(), DISPLAY, Actor::EndDraw(), m_bOverrideLighting, m_fFOV, RageDisplay::SetLighting(), and RageDisplay::SetLightOff().
FinishTweening()
void ActorFrame::FinishTweening () override virtual
Reimplemented from Actor.
Referenced by MusicWheel::FinishChangingSorts(), ScreenNetSelectMusic::HandleScreenMessage(), StepsDisplayList::HideRows(), DualScrollBar::Load(), RoomInfoDisplay::Load(), OptionsList::Load(), OptionsList::Open(), OptionListRow::SetFromHandler(), and StepsDisplayList::TweenOnScreen().
GetChild()
Actor * ActorFrame::GetChild (const RString & sName)
References FOREACH, and m_SubActors.
Referenced by LunaActorFrame::RemoveChild().
GetChildren()
vector<Actor*> ActorFrame::GetChildren () inline
References m_SubActors.
GetDrawFunction()
LuaReference ActorFrame::GetDrawFunction () const inline
References m_DrawFunction.
Referenced by LunaActorFrame::GetDrawFunction().
GetNumChildren()
int ActorFrame::GetNumChildren () const inline
References m_SubActors.
Referenced by LunaActorFrame::GetNumChildren(), ScreenMapControllers::Init(), WheelBase::Load(), and RoomWheelItem::RoomWheelItem().
GetTweenTimeLeft()
ZTestMode float float ActorFrame::GetTweenTimeLeft () const override virtual
Amount of time until all tweens (and all children's tweens) have stopped:
Reimplemented from Actor.
Reimplemented in Transition.
References Actor::GetTweenTimeLeft(), and max().
Referenced by ScreenSelectMaster::BeginScreen(), ScreenSelectMaster::ChangePage(), ScreenSelectMusic::CheckBackgroundRequests(), ScreenSelectMaster::DoMenuStart(), ScreenSelectMusic::HandleScreenMessage(), ScreenSelectMusic::Input(), ScreenSelectMusic::SelectCurrent(), ScreenWithMenuElements::StartTransitioningScreen(), WheelBase::TweenOffScreenForSort(), WheelBase::TweenOnScreenForSort(), and WheelBase::Update().
GetUpdateRate()
float ActorFrame::GetUpdateRate () inline override virtual
Reimplemented from Actor.
References m_fUpdateRate.
HandleMessage()
void ActorFrame::HandleMessage (const Message & msg) override virtual
Reimplemented from Actor.
Reimplemented in ScreenGameplay, OptionRow, MusicWheelItem, ScreenSelectMaster, ScreenSelectMusic, NoteField, ModIconRow, ScreenMapControllers, StepsDisplayList, HoldJudgment, ScreenSelect, Foreground, ScreenContinue, and ScreenTitleMenu.
References Actor::HandleMessage(), Message::IsBroadcast(), and m_SubActors.
Referenced by Foreground::HandleMessage(), ScreenContinue::HandleMessage(), ScreenSelect::HandleMessage(), HoldJudgment::HandleMessage(), StepsDisplayList::HandleMessage(), ScreenMapControllers::HandleMessage(), ModIconRow::HandleMessage(), NoteField::HandleMessage(), ScreenSelectMusic::HandleMessage(), MusicWheelItem::HandleMessage(), OptionRow::HandleMessage(), ScreenGameplay::HandleMessage(), ScoreDisplayNormal::Init(), OptionsList::Input(), Screen::Input(), StepsDisplay::Load(), Player::SetCombo(), ScreenWithMenuElements::SetHelpText(), and StepsDisplay::SetInternal().
HurryTweening()
void ActorFrame::HurryTweening (float factor) override virtual
Reimplemented from Actor.
InitState()
void ActorFrame::InitState () override virtual
Set up the initial state.
Reimplemented from Actor.
References FOREACH, Actor::InitState(), and m_SubActors.
Referenced by Actor::AddWrapperState().
LoadChildrenFromNode()
void ActorFrame::LoadChildrenFromNode (const XNode * pNode) protected
References AddChild(), ASSERT, FOREACH_CONST_Child, XNode::GetChild(), IsAnInt(), ActorUtil::LoadFromNode(), m_bDeleteChildren, and SortByDrawOrder().
Referenced by LoadFromNode().
LoadFromNode()
void ActorFrame::LoadFromNode (const XNode * pNode) override virtual
Reimplemented from Actor.
Reimplemented in PaneDisplay, ActorScroller, PercentageDisplay, StepsDisplayList, TextBanner, BGAnimationLayer, GrooveRadar, BGAnimation, MeterDisplay, HoldJudgment, and DynamicActorScroller.
References AutoLoadChildren(), RageColor::FromString(), XNode::GetAttrValue(), LoadChildrenFromNode(), Actor::LoadFromNode(), m_ambientColor, m_bLighting, m_bOverrideLighting, m_diffuseColor, m_fFOV, m_fUpdateRate, m_fVanishX, m_fVanishY, and m_specularColor.
Referenced by HoldJudgment::LoadFromNode(), BGAnimation::LoadFromNode(), MeterDisplay::LoadFromNode(), GrooveRadar::LoadFromNode(), TextBanner::LoadFromNode(), StepsDisplayList::LoadFromNode(), PercentageDisplay::LoadFromNode(), ActorScroller::LoadFromNode(), and PaneDisplay::LoadFromNode().
MoveToHead()
void ActorFrame::MoveToHead (Actor * pActor)
Move a particular actor to the head.
Parameters
pActor the actor to go to the head.
References FAIL_M, and m_SubActors.
Referenced by ScreenNetSelectMusic::Init().
MoveToTail()
void ActorFrame::MoveToTail (Actor * pActor)
Move a particular actor to the tail.
Parameters
pActor the actor to go to the tail.
References FAIL_M, and m_SubActors.
Referenced by ScreenHowToPlay::Init().
PlayCommandOnChildren()
void ActorFrame::PlayCommandOnChildren (const RString & sCommandName, const LuaReference * pParamTable = nullptr)
References Actor::GetCommand(), and RunCommandsOnChildren().
Referenced by LunaActorFrame::playcommandonchildren().
PlayCommandOnLeaves()
void ActorFrame::PlayCommandOnLeaves (const RString & sCommandName, const LuaReference * pParamTable = nullptr)
References Actor::GetCommand(), and RunCommandsOnLeaves().
Referenced by LunaActorFrame::playcommandonleaves().
PushChildrenTable()
void ActorFrame::PushChildrenTable (lua_State * L)
References AddToChildTable(), CreateChildTable(), FOREACH, m_SubActors, and LuaHelpers::Push().
Referenced by LunaActorFrame::GetChildren().
PushChildTable()
void ActorFrame::PushChildTable (lua_State * L, const RString & sName)
References AddToChildTable(), CreateChildTable(), FOREACH, and m_SubActors.
Referenced by LunaActorFrame::GetChild().
PushSelf()
void ActorFrame::PushSelf (lua_State * L) override virtual
Reimplemented from Actor.
Reimplemented in ScreenGameplay, ScreenTextEntry, Player, OptionRow, RoomWheel, Screen, WheelBase, WheelItemBase, ScreenWithMenuElementsSimple, ActorScroller, ControllerStateDisplay, ScreenSelectMusic, MusicWheel, ScreenEvaluation, NoteField, ScreenOptions, ScreenSelectMaster, LifeMeter, PaneDisplay, LifeMeterBattery, FadingBanner, ActorFrameTexture, MenuTimer, ScreenNetSelectBase, StepsDisplay, ScreenWithMenuElements, GrooveRadar, ScreenNetSelectMusic, StepsDisplayList, ScreenAttract, ScreenNetRoom, TextBanner, ModIconRow, PercentageDisplay, GraphDisplay, MeterDisplay, ScreenSelectProfile, ComboGraph, HoldJudgment, ScreenHowToPlay, GradeDisplay, ScreenPlayerOptions, ScreenNetEvaluation, ScreenProfileLoad, and ScreenProfileSave.
Referenced by DrawPrimitives(), and UpdateInternal().
RemoveAllChildren()
void ActorFrame::RemoveAllChildren ()
Remove all of the children from the frame.
References m_SubActors.
Referenced by OptionRow::Clear(), Transition::Load(), ModIcon::ModIcon(), OptionListRow::SetFromHandler(), TransferChildren(), ModIconRow::~ModIconRow(), and ScreenDebugOverlay::~ScreenDebugOverlay().
RemoveChild()
void ActorFrame::RemoveChild (Actor * pActor) virtual
Remove the specified child from the ActorFrame.
Parameters
pActor the Actor to remove.
References m_SubActors.
Referenced by ScreenOptions::InitMenu(), ScreenNetEvaluation::RedoUserTexts(), LunaActorFrame::RemoveChild(), RoomInfoDisplay::SetRoomInfo(), ScreenNetSelectBase::UpdateUsers(), and RoomInfoDisplay::~RoomInfoDisplay().
RunCommands() [1/2]
void ActorFrame::RunCommands (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) override virtual
Reimplemented from Actor.
References m_bPropagateCommands, Actor::RunCommands(), and RunCommandsOnChildren().
Referenced by Screen::BeginScreen(), RunCommands(), RunCommandsOnChildren(), and MenuTimer::Update().
RunCommands() [2/2]
void ActorFrame::RunCommands (const apActorCommands & cmds, const LuaReference * pParamTable = nullptr) inline
References RunCommands().
RunCommandsOnChildren() [1/2]
void ActorFrame::RunCommandsOnChildren (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) virtual
References m_SubActors, and RunCommands().
Referenced by PlayCommandOnChildren(), RunCommands(), RunCommandsOnChildren(), and LunaActorFrame::RunCommandsOnChildren().
RunCommandsOnChildren() [2/2]
void ActorFrame::RunCommandsOnChildren (const apActorCommands & cmds, const LuaReference * pParamTable = nullptr) inline
References RunCommandsOnChildren().
RunCommandsOnLeaves()
void ActorFrame::RunCommandsOnLeaves (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) override virtual
Reimplemented from Actor.
References m_SubActors.
Referenced by PlayCommandOnLeaves(), and LunaActorFrame::runcommandsonleaves().
RunCommandsRecursively()
void ActorFrame::RunCommandsRecursively (const LuaReference & cmds, const LuaReference * pParamTable = nullptr) override virtual
Reimplemented from Actor.
References m_SubActors, and Actor::RunCommandsRecursively().
SetAmbientLightColor()
void ActorFrame::SetAmbientLightColor (const RageColor & c) inline
References m_ambientColor.
Referenced by LunaActorFrame::SetAmbientLightColor().
SetCustomLighting()
void ActorFrame::SetCustomLighting (bool bCustomLighting) inline
References m_bOverrideLighting.
SetDiffuseLightColor()
void ActorFrame::SetDiffuseLightColor (const RageColor & c) inline
References m_diffuseColor.
Referenced by LunaActorFrame::SetDiffuseLightColor().
SetDrawByZPosition()
void ActorFrame::SetDrawByZPosition (bool b)
References m_bDrawByZPosition.
Referenced by LunaActorFrame::SetDrawByZPosition().
SetDrawFunction()
void ActorFrame::SetDrawFunction (const LuaReference & DrawFunction) inline
References m_DrawFunction.
Referenced by LunaActorFrame::SetDrawFunction().
SetFOV()
void ActorFrame::SetFOV (float fFOV) inline
References m_fFOV.
Referenced by LunaActorFrame::fov(), Screen::Init(), and LunaActorFrame::SetFOV().
SetLightDirection()
void ActorFrame::SetLightDirection (const RageVector3 & vec) inline
References m_lightDirection.
Referenced by LunaActorFrame::SetLightDirection().
SetPropagateCommands()
void ActorFrame::SetPropagateCommands (bool b) virtual
References m_bPropagateCommands.
Referenced by LunaActorFrame::propagate().
SetSpecularLightColor()
void ActorFrame::SetSpecularLightColor (const RageColor & c) inline
References m_specularColor.
Referenced by LunaActorFrame::SetSpecularLightColor().
SetUpdateFunction()
void ActorFrame::SetUpdateFunction (const LuaReference & UpdateFunction) inline
References m_UpdateFunction.
Referenced by LunaActorFrame::SetUpdateFunction().
SetUpdateRate()
void ActorFrame::SetUpdateRate (float rate) inline override virtual
Reimplemented from Actor.
References f, and m_fUpdateRate.
Referenced by LunaActorFrame::SetUpdateRate().
SetVanishPoint()
void ActorFrame::SetVanishPoint (float fX, float fY) inline
References m_fVanishX, and m_fVanishY.
Referenced by LunaActorFrame::vanishpoint().
SetZTestMode()
void ActorFrame::SetZTestMode (ZTestMode mode) override virtual
Reimplemented from Actor.
SetZWrite()
void ActorFrame::SetZWrite (bool b) override virtual
Reimplemented from Actor.
SortByDrawOrder()
void ActorFrame::SortByDrawOrder ()
References CompareActorsByDrawOrder(), and m_SubActors.
Referenced by ScreenWithMenuElements::BeginScreen(), ScreenOptions::BeginScreen(), ScreenRanking::HandleScreenMessage(), ScreenNetRoom::Init(), ScreenSelectMusic::Init(), Player::Init(), ScreenOptions::InitMenu(), OptionRow::InitText(), LoadChildrenFromNode(), Foreground::LoadFromSong(), LunaActorFrame::SortByDrawOrder(), and ScreenOptions::TweenOnScreen().
TransferChildren()
void ActorFrame::TransferChildren (ActorFrame * pTo)
References AddChild(), FOREACH, m_SubActors, and RemoveAllChildren().
UpdateInternal()
void ActorFrame::UpdateInternal (float fDeltaTime) override virtual
Reimplemented from Actor.
Reimplemented in FadingBanner, ActorScroller, BGAnimationLayer, and Transition.
References LuaManager::Get(), LuaReference::IsNil(), L, LUA, m_fUpdateRate, m_SubActors, m_UpdateFunction, LuaReference::PushSelf(), PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptErrorFmt(), LuaHelpers::RunScriptOnStack(), unlikely, Actor::Update(), and Actor::UpdateInternal().
Referenced by Transition::UpdateInternal(), BGAnimationLayer::UpdateInternal(), and ActorScroller::UpdateInternal().
Member Data Documentation
m_ambientColor
RageColor ActorFrame::m_ambientColor protected
Referenced by ActorFrame(), BeginDraw(), LoadFromNode(), and SetAmbientLightColor().
m_bDeleteChildren
bool ActorFrame::m_bDeleteChildren protected
Referenced by ActorFrame(), DeleteChildrenWhenDone(), LoadChildrenFromNode(), StreamDisplay::StreamDisplay(), and ~ActorFrame().
m_bDrawByZPosition
bool ActorFrame::m_bDrawByZPosition protected
Referenced by ActorFrame(), DrawPrimitives(), ActorScroller::PositionItemsAndDrawPrimitives(), and SetDrawByZPosition().
m_bLighting
bool ActorFrame::m_bLighting protected
Referenced by ActorFrame(), BeginDraw(), BGAnimationLayer::LoadFromNode(), and LoadFromNode().
m_bOverrideLighting
bool ActorFrame::m_bOverrideLighting protected
A flad to see if an override for the lighting is needed.
If true, set lightning to m_bLightning.
Referenced by ActorFrame(), BeginDraw(), EndDraw(), LoadFromNode(), and SetCustomLighting().
m_bPropagateCommands
bool ActorFrame::m_bPropagateCommands protected
Referenced by ActorFrame(), RunCommands(), and SetPropagateCommands().
m_diffuseColor
RageColor ActorFrame::m_diffuseColor protected
Referenced by ActorFrame(), BeginDraw(), LoadFromNode(), and SetDiffuseLightColor().
m_DrawFunction
LuaReference ActorFrame::m_DrawFunction protected
Referenced by ActorFrame(), DrawPrimitives(), GetDrawFunction(), and SetDrawFunction().
m_fFOV
float ActorFrame::m_fFOV protected
Referenced by ActorFrame(), BeginDraw(), EndDraw(), LoadFromNode(), BGAnimationLayer::LoadFromNode(), and SetFOV().
m_fUpdateRate
float ActorFrame::m_fUpdateRate protected
Referenced by ActorFrame(), GetUpdateRate(), LoadFromNode(), SetUpdateRate(), BGAnimationLayer::UpdateInternal(), and UpdateInternal().
m_fVanishX
float ActorFrame::m_fVanishX protected
Referenced by ActorFrame(), BeginDraw(), LoadFromNode(), and SetVanishPoint().
m_fVanishY
float ActorFrame::m_fVanishY protected
Referenced by ActorFrame(), BeginDraw(), LoadFromNode(), and SetVanishPoint().
m_lightDirection
RageVector3 ActorFrame::m_lightDirection protected
Referenced by ActorFrame(), BeginDraw(), and SetLightDirection().
m_specularColor
RageColor ActorFrame::m_specularColor protected
Referenced by ActorFrame(), BeginDraw(), LoadFromNode(), and SetSpecularLightColor().
m_SubActors
vector<Actor*> ActorFrame::m_SubActors protected
The children Actors used by the ActorFrame.
Referenced by ActorFrame(), AddChild(), DeleteAllChildren(), DrawPrimitives(), GetChild(), GetChildren(), GetNumChildren(), HandleMessage(), ScreenWithMenuElements::Init(), InitState(), ActorScroller::Load2(), BGAnimationLayer::LoadFromAniLayerFile(), DynamicActorScroller::LoadFromNode(), BGAnimationLayer::LoadFromNode(), MoveToHead(), MoveToTail(), OptionsCursor::OptionsCursor(), ActorScroller::PositionItemsAndDrawPrimitives(), PushChildrenTable(), PushChildTable(), RemoveAllChildren(), RemoveChild(), RunCommandsOnChildren(), RunCommandsOnLeaves(), RunCommandsRecursively(), DynamicActorScroller::ShiftSubActors(), ActorScroller::ShiftSubActors(), SortByDrawOrder(), TransferChildren(), Foreground::Unload(), BGAnimationLayer::UpdateInternal(), ActorScroller::UpdateInternal(), and UpdateInternal().
m_UpdateFunction
LuaReference ActorFrame::m_UpdateFunction protected
Referenced by ActorFrame(), SetUpdateFunction(), and UpdateInternal().
The documentation for this class was generated from the following files:
ActorFrame.h
ActorFrame.cpp