Etterna: LowLevelWindow Class Reference
LowLevelWindow Class Reference abstract
Handle low-level operations that OGL 1.x doesn't give us.
#include <LowLevelWindow.h>
Public Member Functions
virtual ~LowLevelWindow ()=default
virtual void * GetProcAddress (const RString &s)=0
virtual RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut)=0
virtual void GetDisplayResolutions (DisplayResolutions &out) const =0
virtual void LogDebugInformation () const
virtual bool IsSoftwareRenderer (RString &)
virtual void SwapBuffers ()=0
virtual void Update ()
virtual const VideoModeParams * GetActualVideoModeParams () const =0
virtual bool SupportsRenderToTexture () const
virtual RenderTarget * CreateRenderTarget ()
virtual bool SupportsThreadedRendering ()
virtual void BeginConcurrentRenderingMainThread ()
virtual void EndConcurrentRenderingMainThread ()
virtual void BeginConcurrentRendering ()
virtual void EndConcurrentRendering ()
Static Public Member Functions
static LowLevelWindow * Create ()
Detailed Description
Handle low-level operations that OGL 1.x doesn't give us.
Constructor & Destructor Documentation
~LowLevelWindow()
virtual LowLevelWindow::~LowLevelWindow () virtual default
Member Function Documentation
BeginConcurrentRendering()
virtual void LowLevelWindow::BeginConcurrentRendering () inline virtual
Reimplemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::BeginConcurrentRendering().
BeginConcurrentRenderingMainThread()
virtual void LowLevelWindow::BeginConcurrentRenderingMainThread () inline virtual
Reimplemented in LowLevelWindow_X11.
Referenced by RageDisplay_Legacy::BeginConcurrentRenderingMainThread().
Create()
LowLevelWindow * LowLevelWindow::Create () static
References ARCH_LOW_LEVEL_WINDOW.
Referenced by RageDisplay_GLES2::Init(), and RageDisplay_Legacy::Init().
CreateRenderTarget()
virtual RenderTarget* LowLevelWindow::CreateRenderTarget () inline virtual
Reimplemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::CreateRenderTarget().
EndConcurrentRendering()
virtual void LowLevelWindow::EndConcurrentRendering () inline virtual
Reimplemented in LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::EndConcurrentRendering().
EndConcurrentRenderingMainThread()
virtual void LowLevelWindow::EndConcurrentRenderingMainThread () inline virtual
Reimplemented in LowLevelWindow_X11.
Referenced by RageDisplay_Legacy::EndConcurrentRenderingMainThread().
GetActualVideoModeParams()
virtual const VideoModeParams* LowLevelWindow::GetActualVideoModeParams () const pure virtual
Implemented in LowLevelWindow_MacOSX, LowLevelWindow_Win32, and LowLevelWindow_X11.
Referenced by RageDisplay_GLES2::BeginFrame(), RageDisplay_Legacy::BeginFrame(), RageDisplay_Legacy::CreateScreenshot(), RageDisplay_Legacy::CreateTexture(), RageDisplay_Legacy::DrawLineStripInternal(), RageDisplay_GLES2::EndFrame(), RageDisplay_GLES2::GetActualVideoModeParams(), RageDisplay_Legacy::GetActualVideoModeParams(), RageDisplay_Legacy::SetRenderTarget(), RageDisplay_GLES2::SetTextureFiltering(), and RageDisplay_Legacy::SetTextureFiltering().
GetDisplayResolutions()
virtual void LowLevelWindow::GetDisplayResolutions (DisplayResolutions & out) const pure virtual
Implemented in LowLevelWindow_X11, LowLevelWindow_MacOSX, and LowLevelWindow_Win32.
Referenced by RageDisplay_GLES2::GetDisplayResolutions(), and RageDisplay_Legacy::GetDisplayResolutions().
GetProcAddress()
virtual void* LowLevelWindow::GetProcAddress (const RString & s) pure virtual
Implemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
IsSoftwareRenderer()
virtual bool LowLevelWindow::IsSoftwareRenderer (RString &) inline virtual
Reimplemented in LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::Init().
LogDebugInformation()
virtual void LowLevelWindow::LogDebugInformation () const inline virtual
Reimplemented in LowLevelWindow_X11.
Referenced by RageDisplay_GLES2::Init(), and RageDisplay_Legacy::Init().
SupportsRenderToTexture()
virtual bool LowLevelWindow::SupportsRenderToTexture () const inline virtual
Reimplemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::SupportsRenderToTexture().
SupportsThreadedRendering()
virtual bool LowLevelWindow::SupportsThreadedRendering () inline virtual
Reimplemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_Legacy::SupportsThreadedRendering().
SwapBuffers()
virtual void LowLevelWindow::SwapBuffers () pure virtual
Implemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_GLES2::EndFrame(), and RageDisplay_Legacy::EndFrame().
TryVideoMode()
virtual RString LowLevelWindow::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) pure virtual
Implemented in LowLevelWindow_MacOSX, LowLevelWindow_X11, and LowLevelWindow_Win32.
Referenced by RageDisplay_GLES2::TryVideoMode(), and RageDisplay_Legacy::TryVideoMode().
Update()
virtual void LowLevelWindow::Update () inline virtual
Reimplemented in LowLevelWindow_MacOSX, and LowLevelWindow_Win32.
Referenced by RageDisplay_GLES2::EndFrame(), and RageDisplay_Legacy::EndFrame().
The documentation for this class was generated from the following files:
LowLevelWindow.h
LowLevelWindow.cpp