Etterna: DisplayBpms Struct Reference
DisplayBpms Struct Reference
The list of BPMs to display.
#include <GameConstantsAndTypes.h>
Public Member Functions
void Add (float f)
Add a BPM to the list.
float GetMin () const
Retrieve the minimum BPM of the set.
float GetMax () const
Retrieve the maximum BPM of the set.
float GetMaxWithin (float highest=FLT_MAX) const
Retrieve the maximum BPM of the set, but no higher than a certain value.
bool BpmIsConstant () const
Determine if the BPM is really constant.
bool IsSecret () const
Determine if the BPM is meant to be a secret.
Public Attributes
vector< float > vfBpms
The list of the BPMs for the song.
Detailed Description
The list of BPMs to display.
Member Function Documentation
Add()
void DisplayBpms::Add (float f)
Add a BPM to the list.
Parameters
f the BPM to add.
References vfBpms.
Referenced by BPMDisplay::CycleRandomly(), Steps::GetDisplayBpms(), Song::GetDisplayBpms(), BPMDisplay::SetBpmFromSteps(), and BPMDisplay::SetConstantBpm().
BpmIsConstant()
bool DisplayBpms::BpmIsConstant () const
Determine if the BPM is really constant.
Returns
Whether the BPM is constant or not.
References GetMax(), and GetMin().
Referenced by OptionRow::GetRowTitle(), LunaSteps::IsDisplayBpmConstant(), and LunaSong::IsDisplayBpmConstant().
GetMax()
float DisplayBpms::GetMax () const
Retrieve the maximum BPM of the set.
Returns
the maximum BPM.
References GetMaxWithin().
Referenced by BpmIsConstant(), CompareSongPointersByBPM(), LunaSteps::GetDisplayBpms(), LunaSong::GetDisplayBpms(), OptionRow::GetRowTitle(), SongUtil::GetSectionNameFromSongAndSort(), Player::Init(), PlayerOptions::IsEasierForSongAndSteps(), and Song::IsEasy().
GetMaxWithin()
float DisplayBpms::GetMaxWithin (float highest = FLT_MAX) const
Retrieve the maximum BPM of the set, but no higher than a certain value.
Parameters
highest the highest BPM to use.
Returns
the maximum BPM.
References clamp, f, FOREACH_CONST, max(), and vfBpms.
Referenced by GetMax(), and Player::Init().
GetMin()
float DisplayBpms::GetMin () const
Retrieve the minimum BPM of the set.
Returns
the minimum BPM.
References f, FOREACH_CONST, min(), and vfBpms.
Referenced by BpmIsConstant(), LunaSteps::GetDisplayBpms(), LunaSong::GetDisplayBpms(), OptionRow::GetRowTitle(), and Song::IsEasy().
IsSecret()
bool DisplayBpms::IsSecret () const
Determine if the BPM is meant to be a secret.
Returns
Whether the BPM is a secret or not.
References f, FOREACH_CONST, and vfBpms.
Referenced by OptionRow::GetRowTitle(), Player::Init(), LunaSteps::IsDisplayBpmSecret(), and LunaSong::IsDisplayBpmSecret().
Member Data Documentation
vfBpms
vector<float> DisplayBpms::vfBpms
The list of the BPMs for the song.
Referenced by Add(), GetMaxWithin(), GetMin(), IsSecret(), and BPMDisplay::SetBPMRange().
The documentation for this struct was generated from the following files:
GameConstantsAndTypes.h
GameConstantsAndTypes.cpp