Etterna: NotesLoaderBMS.cpp File Reference
NotesLoaderBMS.cpp File Reference
#include "global.h"
#include "NotesLoaderBMS.h"
#include "ActorUtil.h"
#include "BackgroundUtil.h"
#include "GameConstantsAndTypes.h"
#include "GameManager.h"
#include "NoteData.h"
#include "NoteTypes.h"
#include "NotesLoader.h"
#include "RageFile.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageUtil_CharConversions.h"
#include "Song.h"
#include "SongManager.h"
#include "SongUtil.h"
#include "Steps.h"
#include "StepsUtil.h"
Classes
struct BMSObject
struct BMSMeasure
class BMSChart
struct bmsCommandTree
struct bmsCommandTree::bmsNodeS
class BMSSong
struct BMSChartInfo
class BMSChartReader
struct BMSAutoKeysound
struct bmFrac
struct BMSStepsInfo
class BMSSongLoader
Typedefs
typedef map< RString, RString > BMSHeaders
typedef map< int, BMSMeasure > BMSMeasures
typedef vector< BMSObject > BMSObjects
Enumerations
enum BmsRawChannel {
BMS_RAW_P1_KEY1 = 11, BMS_RAW_P1_KEY2 = 12, BMS_RAW_P1_KEY3 = 13, BMS_RAW_P1_KEY4 = 14,
BMS_RAW_P1_KEY5 = 15, BMS_RAW_P1_TURN = 16, BMS_RAW_P1_KEY6 = 18, BMS_RAW_P1_KEY7 = 19,
BMS_RAW_P2_KEY1 = 21, BMS_RAW_P2_KEY2 = 22, BMS_RAW_P2_KEY3 = 23, BMS_RAW_P2_KEY4 = 24,
BMS_RAW_P2_KEY5 = 25, BMS_RAW_P2_TURN = 26, BMS_RAW_P2_KEY6 = 28, BMS_RAW_P2_KEY7 = 29
}
Functions
static RString FindLargestInitialSubstring (const RString &string1, const RString &string2)
static void SearchForDifficulty (RString sTag, Steps *pOut)
static void SlideDuplicateDifficulties (Song &p)
bool operator< (BMSObject const &lhs, BMSObject const &rhs)
bool operator> (BMSObject const &lhs, BMSObject const &rhs)
bool operator<= (BMSObject const &lhs, BMSObject const &rhs)
bool operator>= (BMSObject const &lhs, BMSObject const &rhs)
bmFrac toFraction (double f)
Variables
const int MaxBMSElements = 1296
Typedef Documentation
BMSHeaders
typedef map<RString, RString> BMSHeaders
BMSMeasures
typedef map<int, BMSMeasure> BMSMeasures
BMSObjects
typedef vector<BMSObject> BMSObjects
Enumeration Type Documentation
BmsRawChannel
enum BmsRawChannel
Enumerator
BMS_RAW_P1_KEY1
BMS_RAW_P1_KEY2
BMS_RAW_P1_KEY3
BMS_RAW_P1_KEY4
BMS_RAW_P1_KEY5
BMS_RAW_P1_TURN
BMS_RAW_P1_KEY6
BMS_RAW_P1_KEY7
BMS_RAW_P2_KEY1
BMS_RAW_P2_KEY2
BMS_RAW_P2_KEY3
BMS_RAW_P2_KEY4
BMS_RAW_P2_KEY5
BMS_RAW_P2_TURN
BMS_RAW_P2_KEY6
BMS_RAW_P2_KEY7
Function Documentation
FindLargestInitialSubstring()
static RString FindLargestInitialSubstring (const RString & string1, const RString & string2) static
Referenced by BMSSongLoader::AddToSong().
operator<()
bool operator< (BMSObject const & lhs, BMSObject const & rhs) inline
References BMSObject::channel, BMSObject::measure, and BMSObject::position.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (BMSObject const & lhs, BMSObject const & rhs) inline
References operator<().
operator>()
bool operator> (BMSObject const & lhs, BMSObject const & rhs) inline
References operator<().
operator>=()
bool operator>= (BMSObject const & lhs, BMSObject const & rhs) inline
References operator<().
SearchForDifficulty()
static void SearchForDifficulty (RString sTag, Steps * pOut) static
References Difficulty_Easy, Difficulty_Edit, Difficulty_Hard, DifficultyToString(), Steps::GetDifficulty(), LOG, StdString::CStdStr< CT >::MakeLower(), Steps::SetDescription(), Steps::SetDifficulty(), and RageLog::Trace().
Referenced by BMSSongLoader::AddToSong().
SlideDuplicateDifficulties()
static void SlideDuplicateDifficulties (Song & p) static
References Difficulty_Challenge, Difficulty_Edit, FOREACH_ENUM, SongUtil::GetSteps(), min(), Steps::SetDifficulty(), and StepsUtil::SortNotesArrayByDifficulty().
Referenced by BMSSongLoader::AddToSong().
toFraction()
bmFrac toFraction (double f)
Referenced by BMSChartReader::ReadNoteData().
Variable Documentation
MaxBMSElements
const int MaxBMSElements = 1296