Etterna: SongUtil Namespace Reference
SongUtil Namespace Reference
A set of song utilities to make working with songs easier.
Functions
void GetSteps (const Song *pSong, vector< Steps *> &arrayAddTo, StepsType st=StepsType_Invalid, Difficulty dc=Difficulty_Invalid, int iMeterLow=-1, int iMeterHigh=-1, const RString &sDescription="", const RString &sCredit="", bool bIncludeAutoGen=true, unsigned uHash=0, int iMaxToGet=-1)
Steps * GetOneSteps (const Song *pSong, StepsType st=StepsType_Invalid, Difficulty dc=Difficulty_Invalid, int iMeterLow=-1, int iMeterHigh=-1, const RString &sDescription="", const RString &sCredit="", unsigned uHash=0, bool bIncludeAutoGen=true)
Steps * GetStepsByDifficulty (const Song *pSong, StepsType st, Difficulty dc, bool bIncludeAutoGen=true)
Steps * GetStepsByMeter (const Song *pSong, StepsType st, int iMeterLow, int iMeterHigh)
Steps * GetStepsByDescription (const Song *pSong, StepsType st, const RString &sDescription)
Steps * GetStepsByCredit (const Song *pSong, StepsType st, const RString &sCredit)
Steps * GetClosestNotes (const Song *pSong, StepsType st, Difficulty dc, bool bIgnoreLocked=false)
void AdjustDuplicateSteps (Song *pSong)
void DeleteDuplicateSteps (Song *pSong, vector< Steps *> &vSteps)
RString MakeSortString (RString s)
void SortSongPointerArrayByTitle (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByBPM (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByGrades (vector< Song *> &vpSongsInOut, bool bDescending)
void SortSongPointerArrayByArtist (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByDisplayArtist (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByGenre (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByGroupAndTitle (vector< Song *> &vpSongsInOut)
void SortSongPointerArrayByGroupAndMSD (vector< Song *> &vpSongsInOut, Skillset ss)
void SortSongPointerArrayByNumPlays (vector< Song *> &vpSongsInOut, ProfileSlot slot, bool bDescending)
void SortSongPointerArrayByNumPlays (vector< Song *> &vpSongsInOut, const Profile *pProfile, bool bDescending)
void SortSongPointerArrayByStepsTypeAndMeter (vector< Song *> &vpSongsInOut, StepsType st, Difficulty dc)
RString GetSectionNameFromSongAndSort (const Song *pSong, SortOrder so)
void SortSongPointerArrayBySectionName (vector< Song *> &vpSongsInOut, SortOrder so)
void SortSongPointerArrayByLength (vector< Song *> &vpSongsInOut)
int CompareSongPointersByGroup (const Song *pSong1, const Song *pSong2)
bool IsEditDescriptionUnique (const Song *pSong, StepsType st, const RString &sPreferredDescription, const Steps *pExclude)
Determine if the requested description for an edit is unique.
bool IsChartNameUnique (const Song *pSong, StepsType st, const RString &name, const Steps *pExclude)
RString MakeUniqueEditDescription (const Song *pSong, StepsType st, const RString &sPreferredDescription)
bool ValidateCurrentEditStepsDescription (const RString &sAnswer, RString &sErrorOut)
bool ValidateCurrentStepsDescription (const RString &sAnswer, RString &sErrorOut)
bool ValidateCurrentStepsCredit (const RString &sAnswer, RString &sErrorOut)
bool ValidateCurrentStepsChartName (const RString &answer, RString &error)
bool ValidateCurrentSongPreview (const RString &answer, RString &error)
bool ValidateCurrentStepsMusic (const RString &answer, RString &error)
void GetAllSongGenres (vector< RString > &vsOut)
void FilterSongs (const SongCriteria &sc, const vector< Song *> &in, vector< Song *> &out, bool doCareAboutGame=false)
Filter the selection of songs to only match certain criteria.
void GetPlayableStepsTypes (const Song *pSong, set< StepsType > &vOut)
void GetPlayableSteps (const Song *pSong, vector< Steps *> &vOut)
bool IsStepsTypePlayable (Song *pSong, StepsType st)
bool IsStepsPlayable (Song *pSong, Steps *pSteps)
bool IsSongPlayable (Song *s)
Determine if the song has any playable steps in the present game.
bool GetStepsTypeAndDifficultyFromSortOrder (SortOrder so, StepsType &st, Difficulty &dc)
Detailed Description
A set of song utilities to make working with songs easier.
Function Documentation
AdjustDuplicateSteps()
void SongUtil::AdjustDuplicateSteps (Song * pSong)
References Capitalize(), DeleteDuplicateSteps(), Difficulty_Edit, DifficultyToString(), FOREACH_ENUM, GetSteps(), and StepsUtil::SortNotesArrayByDifficulty().
Referenced by Song::TidyUpData().
CompareSongPointersByGroup()
int SongUtil::CompareSongPointersByGroup (const Song * pSong1, const Song * pSong2)
References Song::m_sGroupName.
Referenced by CompareSongPointersByGroupAndTitle().
DeleteDuplicateSteps()
void SongUtil::DeleteDuplicateSteps (Song * pSong, vector< Steps *> & vSteps)
References Song::DeleteSteps(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetMeter(), Steps::GetSMNoteData(), Song::GetSongDir(), LOG, RemoveInitialWhitespace(), and RageLog::Trace().
Referenced by AdjustDuplicateSteps().
FilterSongs()
void SongUtil::FilterSongs (const SongCriteria & sc, const vector< Song *> & in, vector< Song *> & out, bool doCareAboutGame = false)
Filter the selection of songs to only match certain criteria.
Parameters
sc the intended song criteria.
in the starting batch of songs.
out the resulting batch.
doCareAboutGame a flag to see if we should only get playable steps.
References FOREACH_CONST, IsSongPlayable(), and SongCriteria::Matches().
GetAllSongGenres()
void SongUtil::GetAllSongGenres (vector< RString > & vsOut)
References FOREACH_CONST, FOREACHS_CONST, SongManager::GetAllSongs(), and SONGMAN.
GetClosestNotes()
Steps * SongUtil::GetClosestNotes (const Song * pSong, StepsType st, Difficulty dc, bool bIgnoreLocked = false)
References ASSERT, Difficulty_Edit, Difficulty_Invalid, Song::GetAllSteps(), Steps::GetDifficulty(), Song::GetStepsByStepsType(), and StepsType_Invalid.
Referenced by ScreenHowToPlay::Init(), and SortSongPointerArrayByStepsTypeAndMeter().
GetOneSteps()
Steps * SongUtil::GetOneSteps (const Song * pSong, StepsType st = StepsType_Invalid, Difficulty dc = Difficulty_Invalid, int iMeterLow = -1, int iMeterHigh = -1, const RString & sDescription = "", const RString & sCredit = "", unsigned uHash = 0, bool bIncludeAutoGen = true)
References GetSteps().
Referenced by LunaSong::GetOneSteps(), Song::HasStepsType(), Song::HasStepsTypeAndDifficulty(), StepsID::ToSteps(), and ScreenNetEvaluation::UpdateStats().
GetPlayableSteps()
void SongUtil::GetPlayableSteps (const Song * pSong, vector< Steps *> & vOut)
References FOREACHS, GetPlayableStepsTypes(), GetSteps(), StepsUtil::SortNotesArrayByDifficulty(), and StepsUtil::SortStepsByTypeAndDifficulty().
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenGameplaySyncMachine::Init(), IsStepsPlayable(), and StepsDisplayList::SetFromGameState().
GetPlayableStepsTypes()
void SongUtil::GetPlayableStepsTypes (const Song * pSong, set< StepsType > & vOut)
References CommonMetrics::AUTO_SET_STYLE, DEFAULT_FAIL, FOREACH, FOREACHS, GAMEMAN, GAMESTATE, GameManager::GetCompatibleStyles(), GameState::GetCurrentStyle(), GameState::GetNumPlayersEnabled(), ThemeMetricStepsTypesToShow::GetValue(), GameState::m_bMultiplayer, GameState::m_pCurGame, Style::m_StyleType, max(), PLAYER_INVALID, CommonMetrics::STEPS_TYPES_TO_SHOW, StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, and StyleType_TwoPlayersTwoSides.
Referenced by MusicWheel::BuildWheelItemDatas(), GetPlayableSteps(), MusicWheel::GetSongList(), and IsStepsTypePlayable().
GetSectionNameFromSongAndSort()
RString SongUtil::GetSectionNameFromSongAndSort (const Song * pSong, SortOrder so)
References FAIL_M, GAMESTATE, GameState::GetCurrentStyle(), Song::GetDisplayBpms(), Profile::GetGrades(), GameState::GetMasterPlayerNumber(), DisplayBpms::GetMax(), ProfileManager::GetProfile(), Song::GetTranslitArtist(), Song::GetTranslitMainTitle(), LocalizedString::GetValue(), Grade_NoData, Grade_Tier01, GradeToLocalizedString(), StdString::CStdStr< CT >::Left(), Song::m_fMusicLengthSeconds, Song::m_sGenre, Song::m_sGroupName, MakeSortString(), NUM_Grade, PLAYER_1, PROFILEMAN, SecondsToMMSS(), SHOW_SECTIONS_IN_BPM_SORT, SONGMAN, SongManager::SongToPreferredSortSectionName(), SORT_ARTIST, SORT_BPM, SORT_BPM_DIVISION, SORT_Chordjack, SORT_FAVORITES, SORT_GENRE, SORT_GROUP, SORT_Handstream, SORT_JackSpeed, SORT_Jumpstream, SORT_LENGTH, SORT_MODE_MENU, SORT_NOT_AVAILABLE, SORT_OTHER, SORT_Overall, SORT_POPULARITY, SORT_PREFERRED, SORT_RECENT, SORT_Stamina, SORT_Stream, SORT_Technical, SORT_TITLE, SORT_TOP_GRADES, and ssprintf().
Referenced by MusicWheel::BuildWheelItemDatas(), SortSongPointerArrayBySectionName(), and MusicWheel::UpdateSwitch().
GetSteps()
void SongUtil::GetSteps (const Song * pSong, vector< Steps *> & arrayAddTo, StepsType st = StepsType_Invalid, Difficulty dc = Difficulty_Invalid, int iMeterLow = -1, int iMeterHigh = -1, const RString & sDescription = "", const RString & sCredit = "", bool bIncludeAutoGen = true, unsigned uHash = 0, int iMaxToGet = -1)
References Difficulty_Invalid, Song::GetAllSteps(), Steps::GetCredit(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetHash(), Steps::GetMeter(), Song::GetStepsByStepsType(), and StepsType_Invalid.
Referenced by AdjustDuplicateSteps(), SongManager::GetExtraStageInfo(), GetOneSteps(), GetPlayableSteps(), GetStepsByCredit(), GetStepsByDescription(), ScreenGameplay::InitSongQueues(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerListSteps::Reload(), SlideDuplicateDifficulties(), and ValidateCurrentEditStepsDescription().
GetStepsByCredit()
Steps * SongUtil::GetStepsByCredit (const Song * pSong, StepsType st, const RString & sCredit)
References Difficulty_Invalid, and GetSteps().
GetStepsByDescription()
Steps * SongUtil::GetStepsByDescription (const Song * pSong, StepsType st, const RString & sDescription)
References Difficulty_Invalid, and GetSteps().
Referenced by GameCommand::LoadOne().
GetStepsByDifficulty()
Steps * SongUtil::GetStepsByDifficulty (const Song * pSong, StepsType st, Difficulty dc, bool bIncludeAutoGen = true)
References Difficulty_Invalid, Song::GetAllSteps(), Steps::GetDifficulty(), Song::GetStepsByStepsType(), and StepsType_Invalid.
Referenced by Profile::GetBestGrade(), Song::IsEasy(), OptionRowHandlerSteps::LoadInternal(), GameCommand::LoadOne(), MusicWheelItem::RefreshGrades(), ScreenNetSelectMusic::StartSelectedSong(), and ScreenNetSelectMusic::UpdateDifficulties().
GetStepsByMeter()
Steps * SongUtil::GetStepsByMeter (const Song * pSong, StepsType st, int iMeterLow, int iMeterHigh)
References Song::GetAllSteps(), Steps::GetMeter(), Song::GetStepsByStepsType(), and StepsType_Invalid.
GetStepsTypeAndDifficultyFromSortOrder()
bool SongUtil::GetStepsTypeAndDifficultyFromSortOrder (SortOrder so, StepsType & st, Difficulty & dc)
Referenced by MusicWheel::UpdateSwitch().
IsChartNameUnique()
bool SongUtil::IsChartNameUnique (const Song * pSong, StepsType st, const RString & name, const Steps * pExclude)
References FOREACH_CONST, Song::GetAllSteps(), Steps::GetChartName(), and Steps::m_StepsType.
Referenced by ValidateCurrentStepsChartName().
IsEditDescriptionUnique()
bool SongUtil::IsEditDescriptionUnique (const Song * pSong, StepsType st, const RString & sPreferredDescription, const Steps * pExclude)
Determine if the requested description for an edit is unique.
Parameters
pSong the song the edit is for.
st the steps type for the edit.
sPreferredDescription the requested description.
pExclude the steps that want the description.
Returns
true if it is unique, false otherwise.
References Difficulty_Edit, FOREACH_CONST, Song::GetAllSteps(), Steps::GetDescription(), Steps::GetDifficulty(), and Steps::m_StepsType.
Referenced by MakeUniqueEditDescription().
IsSongPlayable()
bool SongUtil::IsSongPlayable (Song * s)
Determine if the song has any playable steps in the present game.
Parameters
s the current song.
Returns
true if the song has playable steps, false otherwise.
References FOREACH, Song::GetAllSteps(), and IsStepsPlayable().
Referenced by FilterSongs(), and MusicWheel::FilterWheelItemDatas().
IsStepsPlayable()
bool SongUtil::IsStepsPlayable (Song * pSong, Steps * pSteps)
References GetPlayableSteps().
Referenced by IsSongPlayable().
IsStepsTypePlayable()
bool SongUtil::IsStepsTypePlayable (Song * pSong, StepsType st)
References GetPlayableStepsTypes().
MakeSortString()
RString SongUtil::MakeSortString (RString s)
References StdString::CStdStr< CT >::MakeUpper().
Referenced by CompareSongPointersByTitle(), GetSectionNameFromSongAndSort(), SortSongPointerArrayByArtist(), SortSongPointerArrayByDisplayArtist(), and SortSongPointerArrayBySectionName().
MakeUniqueEditDescription()
RString SongUtil::MakeUniqueEditDescription (const Song * pSong, StepsType st, const RString & sPreferredDescription)
References FAIL_M, IsEditDescriptionUnique(), StdString::CStdStr< CT >::Left(), MAX_STEPS_DESCRIPTION_LENGTH, and ssprintf().
SortSongPointerArrayByArtist()
void SongUtil::SortSongPointerArrayByArtist (vector< Song *> & vpSongsInOut)
References CompareSongPointersBySortValueAscending(), g_mapSongSortVal, and MakeSortString().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByBPM()
void SongUtil::SortSongPointerArrayByBPM (vector< Song *> & vpSongsInOut)
References CompareSongPointersByBPM().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByDisplayArtist()
void SongUtil::SortSongPointerArrayByDisplayArtist (vector< Song *> & vpSongsInOut)
References CompareSongPointersBySortValueAscending(), g_mapSongSortVal, and MakeSortString().
SortSongPointerArrayByGenre()
void SongUtil::SortSongPointerArrayByGenre (vector< Song *> & vpSongsInOut)
References CompareSongPointersByGenre().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByGrades()
void SongUtil::SortSongPointerArrayByGrades (vector< Song *> & vpSongsInOut, bool bDescending)
References ASSERT, CompAscending(), CompDescending(), GAMESTATE, Profile::GetBestGrade(), GameState::GetCurrentStyle(), GameState::GetMasterPlayerNumber(), ProfileManager::GetProfile(), PLAYER_1, and PROFILEMAN.
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByGroupAndMSD()
void SongUtil::SortSongPointerArrayByGroupAndMSD (vector< Song *> & vpSongsInOut, Skillset ss)
References CompareSongPointersByGroupAndMSD().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByGroupAndTitle()
void SongUtil::SortSongPointerArrayByGroupAndTitle (vector< Song *> & vpSongsInOut)
References CompareSongPointersByGroupAndTitle().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByLength()
void SongUtil::SortSongPointerArrayByLength (vector< Song *> & vpSongsInOut)
References CompareSongPointersByLength().
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByNumPlays() [1/2]
void SongUtil::SortSongPointerArrayByNumPlays (vector< Song *> & vpSongsInOut, ProfileSlot slot, bool bDescending)
References ProfileManager::GetProfile(), ProfileManager::IsPersistentProfile(), and PROFILEMAN.
SortSongPointerArrayByNumPlays() [2/2]
void SongUtil::SortSongPointerArrayByNumPlays (vector< Song *> & vpSongsInOut, const Profile * pProfile, bool bDescending)
References ASSERT, CompareSongPointersBySortValueAscending(), CompareSongPointersBySortValueDescending(), g_mapSongSortVal, Profile::GetSongNumTimesPlayed(), and ssprintf().
SortSongPointerArrayBySectionName()
void SongUtil::SortSongPointerArrayBySectionName (vector< Song *> & vpSongsInOut, SortOrder so)
References CompareSongPointersBySortValueAscending(), g_mapSongSortVal, GetSectionNameFromSongAndSort(), LocalizedString::GetValue(), MakeSortString(), and SORT_OTHER.
Referenced by MusicWheel::BuildWheelItemDatas().
SortSongPointerArrayByStepsTypeAndMeter()
void SongUtil::SortSongPointerArrayByStepsTypeAndMeter (vector< Song *> & vpSongsInOut, StepsType st, Difficulty dc)
References CompareSongPointersBySortValueAscending(), g_mapSongSortVal, GetClosestNotes(), Steps::GetDifficulty(), Steps::GetMeter(), and ssprintf().
SortSongPointerArrayByTitle()
void SongUtil::SortSongPointerArrayByTitle (vector< Song *> & vpSongsInOut)
References CompareSongPointersByTitle().
Referenced by MusicWheel::BuildWheelItemDatas(), SongManager::MakeSongGroupsFromPlaylists(), and SongManager::SortSongs().
ValidateCurrentEditStepsDescription()
bool SongUtil::ValidateCurrentEditStepsDescription (const RString & sAnswer, RString & sErrorOut)
References ASSERT, Difficulty_Edit, EDIT_NAME_CANNOT_CONTAIN, EDIT_NAME_CONFLICTS, FOREACH_CONST, GAMESTATE, GetSteps(), LocalizedString::GetValue(), Steps::IsAnEdit(), GameState::m_pCurSteps, Steps::m_pSong, PLAYER_1, ssprintf(), StepsType_Invalid, and YOU_MUST_SUPPLY_NAME.
Referenced by ValidateCurrentStepsDescription().
ValidateCurrentSongPreview()
bool SongUtil::ValidateCurrentSongPreview (const RString & answer, RString & error)
References DoesFileExist(), GAMESTATE, Song::GetPreviewMusicPath(), LocalizedString::GetValue(), GameState::m_pCurSong, Song::m_PreviewFile, PREVIEW_DOES_NOT_EXIST, and ssprintf().
ValidateCurrentStepsChartName()
bool SongUtil::ValidateCurrentStepsChartName (const RString & answer, RString & error)
References CHART_NAME_CANNOT_CONTAIN, CHART_NAME_CONFLICTS, GAMESTATE, Steps::GetChartName(), LocalizedString::GetValue(), IsChartNameUnique(), GameState::m_pCurSong, GameState::m_pCurSteps, Steps::m_StepsType, PLAYER_1, and ssprintf().
ValidateCurrentStepsCredit()
bool SongUtil::ValidateCurrentStepsCredit (const RString & sAnswer, RString & sErrorOut)
References AUTHOR_NAME_CANNOT_CONTAIN, GAMESTATE, Steps::GetCredit(), LocalizedString::GetValue(), GameState::m_pCurSteps, PLAYER_1, and ssprintf().
ValidateCurrentStepsDescription()
bool SongUtil::ValidateCurrentStepsDescription (const RString & sAnswer, RString & sErrorOut)
References GAMESTATE, Steps::GetDescription(), Steps::IsAnEdit(), GameState::m_pCurSteps, PLAYER_1, and ValidateCurrentEditStepsDescription().
ValidateCurrentStepsMusic()
bool SongUtil::ValidateCurrentStepsMusic (const RString & answer, RString & error)
References DoesFileExist(), GAMESTATE, Steps::GetMusicFile(), Steps::GetMusicPath(), LocalizedString::GetValue(), GameState::m_pCurSteps, MUSIC_DOES_NOT_EXIST, PLAYER_1, Steps::SetMusicFile(), and ssprintf().