Etterna: LunaDownloadManager Class Reference
LunaDownloadManager Class Reference
Allow Lua to have access to the ProfileManager.
Public Member Functions
LunaDownloadManager ()
Public Member Functions inherited from Luna< DownloadManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetPacklist (T *p, lua_State *L)
static int GetDownloadingPacks (T *p, lua_State *L)
static int GetUsername (T *p, lua_State *L)
static int GetSkillsetRank (T *p, lua_State *L)
static int GetSkillsetRating (T *p, lua_State *L)
static int GetDownloads (T *p, lua_State *L)
static int IsLoggedIn (T *p, lua_State *L)
static int Login (T *p, lua_State *L)
static int LoginWithToken (T *p, lua_State *L)
static int Logout (T *p, lua_State *L)
static int GetLastVersion (T *p, lua_State *L)
static int GetRegisterPage (T *p, lua_State *L)
static int GetTopSkillsetScore (T *p, lua_State *L)
static int GetTopChartScoreCount (T *p, lua_State *L)
static int GetTopChartScore (T *p, lua_State *L)
static int GetCoreBundle (T *p, lua_State *L)
static int DownloadCoreBundle (T *p, lua_State *L)
static int GetToken (T *p, lua_State *L)
static int RequestChartLeaderBoard (T *p, lua_State *L)
static int ToggleRateFilter (T *p, lua_State *L)
static int GetCurrentRateFilter (T *p, lua_State *L)
static int ToggleTopScoresOnlyFilter (T *p, lua_State *L)
static int GetTopScoresOnlyFilter (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< DownloadManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< DownloadManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< DownloadManager >
using T = DownloadManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< DownloadManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ProfileManager.
Constructor & Destructor Documentation
LunaDownloadManager()
LunaDownloadManager::LunaDownloadManager () inline
References ADD_METHOD, DownloadCoreBundle(), GetCoreBundle(), GetCurrentRateFilter(), GetDownloadingPacks(), GetDownloads(), GetLastVersion(), GetPacklist(), GetRegisterPage(), GetSkillsetRank(), GetSkillsetRating(), GetToken(), GetTopChartScore(), GetTopChartScoreCount(), GetTopScoresOnlyFilter(), GetTopSkillsetScore(), GetUsername(), IsLoggedIn(), Login(), LoginWithToken(), Logout(), RequestChartLeaderBoard(), ToggleRateFilter(), and ToggleTopScoresOnlyFilter().
Member Function Documentation
DownloadCoreBundle()
static int LunaDownloadManager::DownloadCoreBundle (T * p, lua_State * L) inline static
References DLMAN, and SArg.
Referenced by LunaDownloadManager().
GetCoreBundle()
static int LunaDownloadManager::GetCoreBundle (T * p, lua_State * L) inline static
References DLMAN, and SArg.
Referenced by LunaDownloadManager().
GetCurrentRateFilter()
static int LunaDownloadManager::GetCurrentRateFilter (T * p, lua_State * L) inline static
References DownloadManager::currentrateonly.
Referenced by LunaDownloadManager().
GetDownloadingPacks()
static int LunaDownloadManager::GetDownloadingPacks (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetDownloads()
static int LunaDownloadManager::GetDownloads (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetLastVersion()
static int LunaDownloadManager::GetLastVersion (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetPacklist()
static int LunaDownloadManager::GetPacklist (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetRegisterPage()
static int LunaDownloadManager::GetRegisterPage (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetSkillsetRank()
static int LunaDownloadManager::GetSkillsetRank (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetSkillsetRating()
static int LunaDownloadManager::GetSkillsetRating (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetToken()
static int LunaDownloadManager::GetToken (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
GetTopChartScore()
static int LunaDownloadManager::GetTopChartScore (T * p, lua_State * L) inline static
References DLMAN, FOREACH_ENUM, IArg, NUM_Skillset, SArg, and SkillsetToString().
Referenced by LunaDownloadManager().
GetTopChartScoreCount()
static int LunaDownloadManager::GetTopChartScoreCount (T * p, lua_State * L) inline static
References DLMAN, and SArg.
Referenced by LunaDownloadManager().
GetTopScoresOnlyFilter()
static int LunaDownloadManager::GetTopScoresOnlyFilter (T * p, lua_State * L) inline static
References DownloadManager::topscoresonly.
Referenced by LunaDownloadManager().
GetTopSkillsetScore()
static int LunaDownloadManager::GetTopSkillsetScore (T * p, lua_State * L) inline static
References DLMAN, PlayerStageStats::GetGrade(), IArg, L, and LuaHelpers::Push().
Referenced by LunaDownloadManager().
GetUsername()
static int LunaDownloadManager::GetUsername (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
IsLoggedIn()
static int LunaDownloadManager::IsLoggedIn (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
Login()
static int LunaDownloadManager::Login (T * p, lua_State * L) inline static
References DLMAN, and SArg.
Referenced by LunaDownloadManager().
LoginWithToken()
static int LunaDownloadManager::LoginWithToken (T * p, lua_State * L) inline static
References DLMAN, and SArg.
Referenced by LunaDownloadManager().
Logout()
static int LunaDownloadManager::Logout (T * p, lua_State * L) inline static
References DLMAN.
Referenced by LunaDownloadManager().
RequestChartLeaderBoard()
static int LunaDownloadManager::RequestChartLeaderBoard (T * p, lua_State * L) inline static
References DownloadManager::athing, LuaHelpers::CreateTableFromArray(), DownloadManager::currentrateonly, f, GAMESTATE, ModsGroup< T >::GetCurrent(), SongOptions::m_fMusicRate, GameState::m_SongOptions, DownloadManager::MakeAThing(), SArg, and DownloadManager::topscoresonly.
Referenced by LunaDownloadManager().
ToggleRateFilter()
static int LunaDownloadManager::ToggleRateFilter (T * p, lua_State * L) inline static
References DownloadManager::currentrateonly.
Referenced by LunaDownloadManager().
ToggleTopScoresOnlyFilter()
static int LunaDownloadManager::ToggleTopScoresOnlyFilter (T * p, lua_State * L) inline static
References DownloadManager::topscoresonly.
Referenced by LunaDownloadManager().
The documentation for this class was generated from the following file:
DownloadManager.cpp