Etterna: StripBuffer Struct Reference
StripBuffer Struct Reference
Public Types
enum { size = 512 }
Public Member Functions
StripBuffer ()
~StripBuffer ()
void Init ()
void Draw ()
int Used () const
int Free () const
Public Attributes
RageSpriteVertex * buf
RageSpriteVertex * v
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
size
Constructor & Destructor Documentation
StripBuffer()
StripBuffer::StripBuffer () inline
References Init(), and size.
~StripBuffer()
StripBuffer::~StripBuffer () inline
Member Function Documentation
Draw()
void StripBuffer::Draw () inline
References DISPLAY, and RageDisplay::DrawSymmetricQuadStrip().
Referenced by NoteDisplay::DrawHoldPart().
Free()
int StripBuffer::Free () const inline
References size, and Used().
Referenced by NoteDisplay::DrawHoldPart().
Init()
void StripBuffer::Init () inline
References buf.
Referenced by NoteDisplay::DrawHoldPart(), and StripBuffer().
Used()
int StripBuffer::Used () const inline
References buf.
Referenced by Free().
Member Data Documentation
buf
RageSpriteVertex* StripBuffer::buf
Referenced by Init(), and Used().
v
RageSpriteVertex* StripBuffer::v
Referenced by NoteDisplay::DrawHoldPart().
The documentation for this struct was generated from the following file:
NoteDisplay.cpp