Etterna: char_traits_char_nocase Struct Reference
char_traits_char_nocase Struct Reference
#include <RageUtil.h>
Static Public Member Functions
static bool eq (char c1, char c2)
static bool ne (char c1, char c2)
static bool lt (char c1, char c2)
static int compare (const char *s1, const char *s2, size_t n)
static char fasttoupper (char a)
static const char * find (const char *s, int n, char a)
Member Function Documentation
compare()
static int char_traits_char_nocase::compare (const char * s1, const char * s2, size_t n) inline static
References fasttoupper().
eq()
static bool char_traits_char_nocase::eq (char c1, char c2) inline static
References g_UpperCase.
fasttoupper()
static char char_traits_char_nocase::fasttoupper (char a) inline static
References g_UpperCase.
Referenced by compare(), and find().
find()
static const char* char_traits_char_nocase::find (const char * s, int n, char a) inline static
References fasttoupper().
lt()
static bool char_traits_char_nocase::lt (char c1, char c2) inline static
References g_UpperCase.
ne()
static bool char_traits_char_nocase::ne (char c1, char c2) inline static
References g_UpperCase.
The documentation for this struct was generated from the following file:
RageUtil.h