Etterna: RageSurfaceUtils Namespace Reference
RageSurfaceUtils Namespace Reference
Utility functions for the RageSurfaces.
Enumerations
enum OpenResult { OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT = 1, OPEN_FATAL_ERROR = 2 }
enum { TRAIT_NO_TRANSPARENCY = 0x0001 }
enum { TRAIT_BOOL_TRANSPARENCY = 0x0002 }
Functions
RageSurface * LoadFile (const RString &sPath, RString &error, bool bHeaderOnly=false)
bool SaveBMP (RageSurface *surface, RageFile &f)
bool SaveJPEG (RageSurface *surface, RageFile &f, bool bHighQual=true)
bool SavePNG (RageSurface *pImg, RageFile &f, RString &sError)
uint32_t decodepixel (const uint8_t *p, int bpp)
void encodepixel (uint8_t *p, int bpp, uint32_t pixel)
void GetRawRGBAV (uint32_t pixel, const RageSurfaceFormat &fmt, uint8_t *v)
void GetRawRGBAV (const uint8_t *p, const RageSurfaceFormat &fmt, uint8_t *v)
void GetRGBAV (uint32_t pixel, const RageSurface *src, uint8_t *v)
void GetRGBAV (const uint8_t *p, const RageSurface *src, uint8_t *v)
uint32_t SetRawRGBAV (const RageSurfaceFormat &fmt, const uint8_t *v)
void SetRawRGBAV (uint8_t *p, const RageSurface *src, const uint8_t *v)
uint32_t SetRGBAV (const RageSurfaceFormat &fmt, const uint8_t *v)
void SetRGBAV (uint8_t *p, const RageSurface *src, const uint8_t *v)
void GetBitsPerChannel (const RageSurfaceFormat &fmt, uint32_t bits[4])
void CopySurface (const RageSurface *src, RageSurface *dest)
bool ConvertSurface (const RageSurface *src, RageSurface *&dst, int width, int height, int bpp, uint32_t R, uint32_t G, uint32_t B, uint32_t A)
void ConvertSurface (RageSurface *&image, int width, int height, int bpp, uint32_t R, uint32_t G, uint32_t B, uint32_t A)
void FixHiddenAlpha (RageSurface *img)
int FindSurfaceTraits (const RageSurface *img)
void BlitTransform (const RageSurface *src, RageSurface *dst, const float fCoords[8])
void Blit (const RageSurface *src, RageSurface *dst, int width=-1, int height=-1)
void CorrectBorderPixels (RageSurface *img, int width, int height)
bool SaveSurface (const RageSurface *img, const RString &file)
RageSurface * LoadSurface (const RString &file)
RageSurface * PalettizeToGrayscale (const RageSurface *src_surf, int GrayBits, int AlphaBits)
RageSurface * MakeDummySurface (int height, int width)
void ApplyHotPinkColorKey (RageSurface *&img)
void FlipVertically (RageSurface *img)
void OrderedDither (const RageSurface *src, RageSurface *dst)
void ErrorDiffusionDither (const RageSurface *src, RageSurface *dst)
void Palettize (RageSurface *&pImg, int iColors=256, bool bDither=true)
void Zoom (RageSurface *&src, int width, int height)
Detailed Description
Utility functions for the RageSurfaces.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TRAIT_NO_TRANSPARENCY
anonymous enum
anonymous enum
Enumerator
TRAIT_BOOL_TRANSPARENCY
OpenResult
enum RageSurfaceUtils::OpenResult
Enumerator
OPEN_OK
OPEN_UNKNOWN_FILE_FORMAT
OPEN_FATAL_ERROR
Function Documentation
ApplyHotPinkColorKey()
void RageSurfaceUtils::ApplyHotPinkColorKey (RageSurface *& img)
References RageSurfaceColor::a, RageSurfaceFormat::Amask, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, ConvertSurface(), decodepixel(), encodepixel(), RageSurface::fmt, RageSurface::h, ImageUsesOffHotPink(), RageSurfaceFormat::MapRGBA(), RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, and RageSurface::w.
Referenced by RageBitmapTexture::Create().
Blit()
void RageSurfaceUtils::Blit (const RageSurface * src, RageSurface * dst, int width = -1, int height = -1)
References blit_generic(), blit_rgba_to_rgba(), blit_same_type(), CorrectBorderPixels(), FAIL_M, RageSurface::h, min(), and RageSurface::w.
Referenced by CopySurface(), RageDisplay_Legacy::GetImgPixelFormat(), LoadWin32Surface(), MakePixbuf(), and RageDisplay_D3D::UpdateTexture().
BlitTransform()
void RageSurfaceUtils::BlitTransform (const RageSurface * src, RageSurface * dst, const float fCoords[8])
References RageSurfaceFormat::Amask, RageSurfaceFormat::Ashift, ASSERT, RageSurfaceFormat::BytesPerPixel, clamp, f, RageSurface::fmt, GetRawRGBAV_XY(), RageSurface::h, L, RageSurface::pitch, RageSurface::pixels, scale(), SetRawRGBAV(), and RageSurface::w.
ConvertSurface() [1/2]
bool RageSurfaceUtils::ConvertSurface (const RageSurface * src, RageSurface *& dst, int width, int height, int bpp, uint32_t R, uint32_t G, uint32_t B, uint32_t A)
References CopySurface(), CreateSurface(), RageSurfaceFormat::Equivalent(), RageSurface::fmt, RageSurface::h, and RageSurface::w.
Referenced by ApplyHotPinkColorKey(), ConvertSurface(), RageBitmapTexture::Create(), Palettize(), RageSurface_Save_PNG(), SaveJPEG(), and Zoom().
ConvertSurface() [2/2]
void RageSurfaceUtils::ConvertSurface (RageSurface *& image, int width, int height, int bpp, uint32_t R, uint32_t G, uint32_t B, uint32_t A)
References ConvertSurface().
CopySurface()
void RageSurfaceUtils::CopySurface (const RageSurface * src, RageSurface * dest)
References ASSERT, RageSurfaceFormat::BitsPerPixel, Blit(), RageSurface::fmt, and RageSurfaceFormat::palette.
Referenced by ConvertSurface(), RageDisplay_D3D::CreateScreenshot(), and SaveBMP().
CorrectBorderPixels()
void RageSurfaceUtils::CorrectBorderPixels (RageSurface * img, int width, int height)
References RageSurfaceFormat::BytesPerPixel, decodepixel(), encodepixel(), RageSurface::fmt, RageSurface::pitch, and RageSurface::pixels.
Referenced by Blit().
decodepixel()
uint32_t RageSurfaceUtils::decodepixel (const uint8_t * p, int bpp)
Referenced by ApplyHotPinkColorKey(), blit_generic(), blit_rgba_to_rgba(), CorrectBorderPixels(), FindAlphaRGB(), FindSurfaceTraits(), GetRawRGBAV(), GetRGBAV(), ImageUsesOffHotPink(), PalettizeToGrayscale(), and SetAlphaRGB().
encodepixel()
void RageSurfaceUtils::encodepixel (uint8_t * p, int bpp, uint32_t pixel)
Referenced by ApplyHotPinkColorKey(), blit_generic(), blit_rgba_to_rgba(), CorrectBorderPixels(), SetAlphaRGB(), SetRawRGBAV(), and SetRGBAV().
ErrorDiffusionDither()
void RageSurfaceUtils::ErrorDiffusionDither (const RageSurface * src, RageSurface * dst)
References ASSERT, RageSurfaceFormat::BytesPerPixel, EDDitherPixel(), RageSurface::fmt, GetBitsPerChannel(), GetRawRGBAV(), RageSurface::h, RageSurface::pitch, RageSurface::pixels, SetRawRGBAV(), and RageSurface::w.
Referenced by RageBitmapTexture::Create().
FindSurfaceTraits()
int RageSurfaceUtils::FindSurfaceTraits (const RageSurface * img)
References RageSurfaceColor::a, RageSurfaceFormat::Amask, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, decodepixel(), FAIL_M, RageSurface::fmt, RageSurface::h, max(), RageSurfacePalette::ncolors, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, ssprintf(), TRAIT_BOOL_TRANSPARENCY, TRAIT_NO_TRANSPARENCY, and RageSurface::w.
Referenced by RageBitmapTexture::Create().
FixHiddenAlpha()
void RageSurfaceUtils::FixHiddenAlpha (RageSurface * img)
References RageSurfaceFormat::Amask, RageSurfaceFormat::BitsPerPixel, FindAlphaRGB(), RageSurface::fmt, and SetAlphaRGB().
Referenced by RageBitmapTexture::Create().
FlipVertically()
void RageSurfaceUtils::FlipVertically (RageSurface * img)
References RageSurfaceFormat::BytesPerPixel, RageSurface::fmt, RageSurface::h, RageSurface::pitch, RageSurface::pixels, and RageSurface::w.
Referenced by RageDisplay_Legacy::CreateScreenshot().
GetBitsPerChannel()
void RageSurfaceUtils::GetBitsPerChannel (const RageSurfaceFormat & fmt, uint32_t bits[4])
References RageSurfaceFormat::Loss.
Referenced by ErrorDiffusionDither(), and OrderedDither().
GetRawRGBAV() [1/2]
void RageSurfaceUtils::GetRawRGBAV (uint32_t pixel, const RageSurfaceFormat & fmt, uint8_t * v)
References RageSurfaceColor::a, RageSurfaceFormat::Amask, RageSurfaceFormat::Ashift, RageSurfaceColor::b, RageSurfaceFormat::Bmask, RageSurfaceFormat::Bshift, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, RageSurfaceColor::g, RageSurfaceFormat::Gmask, RageSurfaceFormat::Gshift, RageSurfaceFormat::palette, RageSurfaceColor::r, RageSurfaceFormat::Rmask, and RageSurfaceFormat::Rshift.
Referenced by ErrorDiffusionDither(), GetRawRGBAV(), GetRawRGBAV_XY(), GetRGBAV(), and OrderedDither().
GetRawRGBAV() [2/2]
void RageSurfaceUtils::GetRawRGBAV (const uint8_t * p, const RageSurfaceFormat & fmt, uint8_t * v)
References RageSurfaceFormat::BytesPerPixel, decodepixel(), and GetRawRGBAV().
GetRGBAV() [1/2]
void RageSurfaceUtils::GetRGBAV (uint32_t pixel, const RageSurface * src, uint8_t * v)
References RageSurface::fmt, GetRawRGBAV(), and RageSurfaceFormat::Loss.
Referenced by GetRGBAV(), and PalettizeToGrayscale().
GetRGBAV() [2/2]
void RageSurfaceUtils::GetRGBAV (const uint8_t * p, const RageSurface * src, uint8_t * v)
References RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, decodepixel(), RageSurface::fmt, GetRGBAV(), and RageSurfaceFormat::palette.
LoadFile()
RageSurface * RageSurfaceUtils::LoadFile (const RString & sPath, RString & error, bool bHeaderOnly = false)
References FT_Bitmap, RageFile::GetError(), GetExtension(), ActorUtil::GetTypeExtensionList(), LOG, StdString::CStdStr< CT >::MakeLower(), RageFile::Open(), TryOpenFile(), and RageLog::UserLog().
Referenced by ImageCache::CacheImageInternal(), RageBitmapTexture::Create(), LoadWin32Surface(), sm_main(), and Song::TidyUpData().
LoadSurface()
RageSurface * RageSurfaceUtils::LoadSurface (const RString & file)
References SurfaceHeader::Amask, ASSERT, ASSERT_M, SurfaceHeader::Bmask, SurfaceHeader::bpp, RageSurfacePalette::colors, CreateSurface(), f, RageSurface::fmt, SurfaceHeader::Gmask, SurfaceHeader::height, LOG, RageSurfacePalette::ncolors, RageFile::Open(), RageSurfaceFormat::palette, RageSurface::pitch, SurfaceHeader::pitch, RageSurface::pixels, RageFile::Read(), SurfaceHeader::Rmask, ssprintf(), RageLog::Trace(), and SurfaceHeader::width.
Referenced by ImageCache::Demand(), and ImageCache::LoadImage().
MakeDummySurface()
RageSurface * RageSurfaceUtils::MakeDummySurface (int height, int width)
References RageSurfacePalette::colors, CreateSurface(), RageSurface::fmt, RageSurface::h, RageSurfaceFormat::palette, RageSurface::pitch, and RageSurface::pixels.
Referenced by RageBitmapTexture::Create().
OrderedDither()
void RageSurfaceUtils::OrderedDither (const RageSurface * src, RageSurface * dst)
References ASSERT, RageSurfaceFormat::BytesPerPixel, DitherMat, DitherMatCalc, DitherMatDim, DitherPixel(), RageSurface::fmt, GetBitsPerChannel(), GetRawRGBAV(), RageSurface::h, RageSurface::pitch, RageSurface::pixels, SetRawRGBAV(), and RageSurface::w.
Referenced by ImageCache::CacheImageInternal().
Palettize()
void RageSurfaceUtils::Palettize (RageSurface *& pImg, int iColors = 256, bool bDither = true)
References RageSurfaceColor::a, acolorhist_item::acolor, ASSERT, RageSurfaceColor::b, pixerror_t::c, clamp, RageSurfacePalette::colors, ConvertSurface(), CreateSurface(), RageSurface::fmt, FS_SCALE, RageSurfaceColor::g, RageSurface::h, MAXCOLORS, mediancut(), min(), RageSurfacePalette::ncolors, RageSurfaceFormat::palette, pam_addtoacolorhash(), PAM_ASSIGN, pam_computeacolorhist(), PAM_DEPTH, pam_freeacolorhist(), PAM_GETA, PAM_GETB, PAM_GETG, PAM_GETR, pam_lookupacolor(), RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, swap(), Swap32BE(), and RageSurface::w.
Referenced by ImageCache::CacheImageInternal().
PalettizeToGrayscale()
RageSurface * RageSurfaceUtils::PalettizeToGrayscale (const RageSurface * src_surf, int GrayBits, int AlphaBits)
References RageSurfaceColor::a, ASSERT, RageSurfaceColor::b, RageSurfaceFormat::BytesPerPixel, clamp, RageSurfacePalette::colors, CreateSurface(), decodepixel(), f, RageSurface::fmt, RageSurfaceColor::g, GetRGBAV(), RageSurface::h, L, RageSurfaceFormat::Loss, min(), RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageSurfaceColor::r, and RageSurface::w.
Referenced by RageBitmapTexture::Create().
SaveBMP()
bool RageSurfaceUtils::SaveBMP (RageSurface * surface, RageFile & f)
References RageSurfaceFormat::BytesPerPixel, CopySurface(), CreateSurface(), RageFile::Flush(), RageSurface::fmt, RageSurface::h, RageSurface::pitch, RageSurface::pixels, Swap24LE(), RageSurface::w, write_le16(), write_le32(), and WriteBytes().
Referenced by RageDisplay::SaveScreenshot().
SaveJPEG()
bool RageSurfaceUtils::SaveJPEG (RageSurface * surface, RageFile & f, bool bHighQual = true)
References ConvertSurface(), RageSurface::h, jpeg_RageFile_dest(), RageSurface::pitch, RageSurface::pixels, Swap24BE(), and RageSurface::w.
Referenced by RageDisplay::SaveScreenshot().
SavePNG()
bool RageSurfaceUtils::SavePNG (RageSurface * pImg, RageFile & f, RString & sError)
References RageSurface_Save_PNG().
Referenced by RageDisplay::SaveScreenshot().
SaveSurface()
bool RageSurfaceUtils::SaveSurface (const RageSurface * img, const RString & file)
References RageSurfaceFormat::Amask, SurfaceHeader::Amask, RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::Bmask, SurfaceHeader::Bmask, SurfaceHeader::bpp, RageSurfacePalette::colors, f, RageSurface::fmt, RageSurfaceFormat::Gmask, SurfaceHeader::Gmask, RageSurface::h, SurfaceHeader::height, RageSurfacePalette::ncolors, RageFile::Open(), RageSurfaceFormat::palette, RageSurface::pitch, SurfaceHeader::pitch, RageSurface::pixels, RageSurfaceFormat::Rmask, SurfaceHeader::Rmask, RageSurface::w, SurfaceHeader::width, RageFile::WRITE, and RageFile::Write().
Referenced by ImageCache::CacheImageInternal().
SetRawRGBAV() [1/2]
uint32_t RageSurfaceUtils::SetRawRGBAV (const RageSurfaceFormat & fmt, const uint8_t * v)
References RageSurfaceFormat::Ashift, RageSurfaceFormat::Bshift, RageSurfaceFormat::Gshift, and RageSurfaceFormat::Rshift.
Referenced by BlitTransform(), ErrorDiffusionDither(), OrderedDither(), and SetRawRGBAV().
SetRawRGBAV() [2/2]
void RageSurfaceUtils::SetRawRGBAV (uint8_t * p, const RageSurface * src, const uint8_t * v)
References RageSurfaceFormat::BytesPerPixel, encodepixel(), RageSurface::fmt, and SetRawRGBAV().
SetRGBAV() [1/2]
uint32_t RageSurfaceUtils::SetRGBAV (const RageSurfaceFormat & fmt, const uint8_t * v)
References RageSurfaceFormat::Loss, and RageSurfaceFormat::Shift.
Referenced by blit_generic(), and SetRGBAV().
SetRGBAV() [2/2]
void RageSurfaceUtils::SetRGBAV (uint8_t * p, const RageSurface * src, const uint8_t * v)
References RageSurfaceFormat::BytesPerPixel, encodepixel(), RageSurface::fmt, and SetRGBAV().
Zoom()
void RageSurfaceUtils::Zoom (RageSurface *& src, int width, int height)
References RageSurfaceFormat::Amask, ASSERT_M, RageSurfaceFormat::Bmask, RageSurfaceFormat::BytesPerPixel, clamp, ConvertSurface(), CreateSurface(), f, RageSurface::fmt, RageSurfaceFormat::Gmask, RageSurface::h, RageSurfaceFormat::Rmask, ssprintf(), RageSurface::w, and ZoomSurface().
Referenced by ImageCache::CacheImageInternal(), RageBitmapTexture::Create(), ImageTexture::Create(), LoadWin32Surface(), and RageDisplay::SaveScreenshot().