Etterna: RSAKeyWrapper Class Reference
RSAKeyWrapper Class Reference
#include <CryptHelpers.h>
Public Member Functions
RSAKeyWrapper ()
~RSAKeyWrapper ()
void Unload ()
void Generate (PRNGWrapper &prng, int iKeyLenBits)
bool Load (const RString &sKey, RString &sError)
Public Attributes
rsa_key m_Key
Constructor & Destructor Documentation
RSAKeyWrapper()
RSAKeyWrapper::RSAKeyWrapper ()
References m_Key.
~RSAKeyWrapper()
RSAKeyWrapper::~RSAKeyWrapper ()
References Unload().
Member Function Documentation
Generate()
void RSAKeyWrapper::Generate (PRNGWrapper & prng, int iKeyLenBits)
References ASSERT, PRNGWrapper::m_iPRNG, m_Key, PRNGWrapper::m_PRNG, and Unload().
Load()
bool RSAKeyWrapper::Load (const RString & sKey, RString & sError)
References m_Key, and Unload().
Referenced by CryptManager::GenerateGlobalKeys(), CryptManager::Sign(), and CryptManager::Verify().
Unload()
void RSAKeyWrapper::Unload ()
References m_Key.
Referenced by Generate(), Load(), and ~RSAKeyWrapper().
Member Data Documentation
m_Key
rsa_key RSAKeyWrapper::m_Key
Referenced by Generate(), Load(), RSAKeyWrapper(), CryptManager::Sign(), Unload(), and CryptManager::Verify().
The documentation for this class was generated from the following files:
CryptHelpers.h
CryptHelpers.cpp