Etterna: RageTextureID.h File Reference
RageTextureID.h File Reference
#include "global.h"
Classes
struct RageTextureID
Macros
#define EQUAL(a) (lhs.a == rhs.a)
#define COMP(a)
Functions
bool operator== (RageTextureID const &lhs, RageTextureID const &rhs)
bool operator!= (RageTextureID const &lhs, RageTextureID const &rhs)
bool operator< (RageTextureID const &lhs, RageTextureID const &rhs)
bool operator> (RageTextureID const &lhs, RageTextureID const &rhs)
bool operator<= (RageTextureID const &lhs, RageTextureID const &rhs)
bool operator>= (RageTextureID const &lhs, RageTextureID const &rhs)
Macro Definition Documentation
COMP
#define COMP (a)
Value:
if (lhs.a < rhs.a)                                                         \
        return true;                                                           \
    if (lhs.a > rhs.a)                                                         \
        return false;
Referenced by operator<().
EQUAL
#define EQUAL (a) (lhs.a == rhs.a)
Referenced by operator==().
Function Documentation
operator!=()
bool operator!= (RageTextureID const & lhs, RageTextureID const & rhs) inline
References operator==().
operator<()
bool operator< (RageTextureID const & lhs, RageTextureID const & rhs) inline
References COMP.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (RageTextureID const & lhs, RageTextureID const & rhs) inline
References operator<().
operator==()
bool operator== (RageTextureID const & lhs, RageTextureID const & rhs) inline
References EQUAL.
Referenced by operator!=().
operator>()
bool operator> (RageTextureID const & lhs, RageTextureID const & rhs) inline
References operator<().
operator>=()
bool operator>= (RageTextureID const & lhs, RageTextureID const & rhs) inline
References operator<().