Etterna: RageSound Class Reference
RageSound Class Reference
#include <RageSound.h>
Public Member Functions
RageSound ()
~RageSound () override
RageSound (const RageSound &cpy)
RageSound & operator= (const RageSound &cpy)
bool Load (const RString &sFile, bool bPrecache, const RageSoundLoadParams *pParams=nullptr)
bool Load (const RString &sFile)
void LoadSoundReader (RageSoundReader *pSound)
RageSoundReader * GetSoundReader ()
void Unload ()
bool IsLoaded () const
void DeleteSelfWhenFinishedPlaying ()
void StartPlaying ()
void StopPlaying ()
RString GetError () const
void Play (bool is_action, const RageSoundParams *params=nullptr)
void PlayCopy (bool is_action, const RageSoundParams *pParams=nullptr) const
void Stop ()
bool Pause (bool bPause)
float GetLengthSeconds ()
float GetPositionSeconds (bool *approximate=nullptr, RageTimer *Timestamp=nullptr) const
RString GetLoadedFilePath () const override
bool IsPlaying () const
float GetPlaybackRate () const
RageTimer GetStartTime () const override
void SetParams (const RageSoundParams &p)
const RageSoundParams & GetParams () const
bool SetProperty (const RString &sProperty, float fValue)
void SetStopModeFromString (const RString &sStopMode)
virtual void PushSelf (lua_State *L)
int GetDataToPlay (float *pBuffer, int iSize, int64_t &iStreamFrame, int &iBytesRead) override
void CommitPlayingPosition (int64_t iHardwareFrame, int64_t iStreamFrame, int iGotFrames) override
Public Member Functions inherited from RageSoundBase
virtual ~RageSoundBase ()=default
Private Member Functions
void ApplyParams ()
int GetSourceFrameFromHardwareFrame (int64_t iHardwareFrame, bool *bApproximate=nullptr) const
bool SetPositionFrames (int frames=-1)
RageSoundParams::StopMode_t GetStopMode () const
void SoundIsFinishedPlaying () override
Private Attributes
RageMutex m_Mutex
RageSoundReader * m_pSource
pos_map_queue m_HardwareToStreamMap
pos_map_queue m_StreamToSourceMap
RString m_sFilePath
RageSoundParams m_Param
int64_t m_iStreamFrame
int m_iStoppedSourceFrame { 0 }
bool m_bPlaying { false }
bool m_bDeleteWhenFinished { false }
RString m_sError
Constructor & Destructor Documentation
RageSound() [1/2]
RageSound::RageSound ()
References ASSERT, and SOUNDMAN.
Referenced by PlayCopy().
~RageSound()
RageSound::~RageSound () override
References Unload().
RageSound() [2/2]
RageSound::RageSound (const RageSound & cpy)
References ASSERT, m_pSource, and SOUNDMAN.
Member Function Documentation
ApplyParams()
void RageSound::ApplyParams () private
References f, RageSoundManager::GetMixVolume(), GetStopMode(), RageSoundParams::m_bIsCriticalSound, RageSoundParams::M_CONTINUE, RageSoundParams::m_fAttractVolume, RageSoundParams::m_fFadeInSeconds, RageSoundParams::m_fFadeOutSeconds, RageSoundParams::m_fPitch, RageSoundParams::m_fSpeed, RageSoundParams::m_LengthSeconds, RageSoundParams::M_LOOP, m_Param, m_pSource, RageSoundParams::m_StartSecond, RageSoundParams::M_STOP, RageSoundParams::m_Volume, RageSoundReader::SetProperty(), and SOUNDMAN.
Referenced by SetParams(), and StartPlaying().
CommitPlayingPosition()
void RageSound::CommitPlayingPosition (int64_t iHardwareFrame, int64_t iStreamFrame, int iGotFrames) override virtual
Implements RageSoundBase.
References pos_map_queue::Insert(), RageMutex::Lock(), m_HardwareToStreamMap, m_Mutex, and RageMutex::Unlock().
DeleteSelfWhenFinishedPlaying()
void RageSound::DeleteSelfWhenFinishedPlaying ()
References RageMutex::Lock(), m_bDeleteWhenFinished, m_bPlaying, m_Mutex, and RageMutex::Unlock().
GetDataToPlay()
int RageSound::GetDataToPlay (float * pBuffer, int iSize, int64_t & iStreamFrame, int & iBytesRead) override virtual
Implements RageSoundBase.
References ASSERT, ASSERT_M, RageSoundUtil::ConvertMonoToStereoInPlace(), RageSoundReader::GetError(), GetLoadedFilePath(), RageSoundReader::GetNumChannels(), pos_map_queue::Insert(), RageMutex::Lock(), LOG, m_bPlaying, m_iStreamFrame, m_Mutex, m_pSource, m_sError, m_StreamToSourceMap, RageSoundReader::RetriedRead(), RageSoundReader::RSRERROR, ssprintf(), RageMutex::Unlock(), and RageLog::Warn().
GetError()
RString RageSound::GetError () const inline
References m_sError.
GetLengthSeconds()
float RageSound::GetLengthSeconds ()
References RageSoundReader::GetError(), RageSoundReader::GetLength(), GetLoadedFilePath(), LOG, m_pSource, and RageLog::Warn().
GetLoadedFilePath()
RString RageSound::GetLoadedFilePath () const inline override virtual
Implements RageSoundBase.
References m_sFilePath.
Referenced by GetDataToPlay(), GetLengthSeconds(), GameSoundManager::GetMusicPath(), Player::Load(), SetPositionFrames(), StartMusic(), StartPlaying(), and GameSoundManager::Update().
GetParams()
const RageSoundParams& RageSound::GetParams () const inline
References m_Param.
Referenced by GameSoundManager::DimMusic(), ScreenTestSound::Input(), LunaRageSound::pitch(), LunaRageSound::SetParam(), LunaRageSound::speed(), GameSoundManager::Update(), ScreenGameplay::Update(), ScreenTestSound::UpdateText(), and LunaRageSound::volume().
GetPlaybackRate()
float RageSound::GetPlaybackRate () const
References RageSoundParams::m_fSpeed, and m_Param.
Referenced by GameSoundManager::Update().
GetPositionSeconds()
float RageSound::GetPositionSeconds (bool * approximate = nullptr, RageTimer * Timestamp = nullptr) const
References RageSoundManager::GetPosition(), GetSourceFrameFromHardwareFrame(), pos_map_queue::IsEmpty(), IsPlaying(), LockMut, m_HardwareToStreamMap, m_iStoppedSourceFrame, m_Mutex, m_StreamToSourceMap, samplerate, and SOUNDMAN.
Referenced by ScreenGameplay::GetSongPosition(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), ScreenGameplay::ToggleReplayPause(), GameSoundManager::Update(), and ScreenGameplay::UpdateSongPosition().
GetSoundReader()
RageSoundReader* RageSound::GetSoundReader () inline
References m_pSource.
Referenced by LunaRageSound::get_length().
GetSourceFrameFromHardwareFrame()
int RageSound::GetSourceFrameFromHardwareFrame (int64_t iHardwareFrame, bool * bApproximate = nullptr) const private
References pos_map_queue::IsEmpty(), m_HardwareToStreamMap, m_StreamToSourceMap, and pos_map_queue::Search().
Referenced by GetPositionSeconds(), and SoundIsFinishedPlaying().
GetStartTime()
RageTimer RageSound::GetStartTime () const override virtual
Reimplemented from RageSoundBase.
References m_Param, and RageSoundParams::m_StartTime.
GetStopMode()
RageSoundParams::StopMode_t RageSound::GetStopMode () const private
References RageSoundParams::M_AUTO, RageSoundParams::M_LOOP, m_Param, m_sFilePath, and RageSoundParams::M_STOP.
Referenced by ApplyParams().
IsLoaded()
bool RageSound::IsLoaded () const
References m_pSource.
Referenced by MenuTimer::Update().
IsPlaying()
bool RageSound::IsPlaying () const inline
References m_bPlaying.
Referenced by GetPositionSeconds(), Play(), StartMusic(), ScreenGameplay::StartPlayingSong(), Unload(), GameSoundManager::Update(), ScreenGameplay::UpdateSongPosition(), and ScreenTestSound::UpdateText().
Load() [1/2]
bool RageSound::Load (const RString & sFile, bool bPrecache, const RageSoundLoadParams * pParams = nullptr)
References RageSoundManager::AddLoadedSound(), Basename(), RageSoundManager::GetLoadedSound(), LoadSoundReader(), LOG, RageSoundLoadParams::m_bSupportPan, RageSoundLoadParams::m_bSupportRateChanging, m_Mutex, m_pSource, m_sFilePath, RageSoundReader_FileReader::OpenFile(), RageSoundReader_Preload::PreloadSound(), RageMutex::SetName(), SOUNDMAN, ssprintf(), RageLog::Trace(), and RageLog::Warn().
Referenced by AutoScreenMessage(), DoPlayOnce(), GameplayAssist::Init(), ScreenTestSound::Init(), ScreenNetRoom::Init(), ScreenMapControllers::Init(), ScreenNetSelectMusic::Init(), ScreenSetTime::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenPrompt::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenTextEntry::Init(), LifeMeterBattery::LifeMeterBattery(), ActorSound::Load(), LifeMeterTime::Load(), MenuTimer::Load(), MusicWheel::Load(), WheelBase::Load(), Player::Load(), Load(), and ActorSound::LoadFromNode().
Load() [2/2]
bool RageSound::Load (const RString & sFile)
References Load().
LoadSoundReader()
void RageSound::LoadSoundReader (RageSoundReader * pSound)
References RageSoundManager::GetDriverSampleRate(), RageSoundReader::GetSampleRate(), m_iStoppedSourceFrame, m_iStreamFrame, m_pSource, SOUNDMAN, and Unload().
Referenced by AutoKeysounds::FinishLoading(), and Load().
operator=()
RageSound & RageSound::operator= (const RageSound & cpy)
References ASSERT, RageSoundReader::Copy(), LockMut, m_bDeleteWhenFinished, m_bPlaying, m_iStoppedSourceFrame, m_iStreamFrame, m_Mutex, m_Param, m_pSource, and m_sFilePath.
Pause()
bool RageSound::Pause (bool bPause)
References LOG, m_pSource, RageSoundManager::Pause(), SOUNDMAN, and RageLog::Warn().
Referenced by ActorSound::Pause(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), and ScreenGameplay::ToggleReplayPause().
Play()
void RageSound::Play (bool is_action, const RageSoundParams * params = nullptr)
References IsPlaying(), LOG, PrefsManager::m_MuteActions, m_pSource, PlayCopy(), PREFSMAN, SetParams(), StartPlaying(), and RageLog::Warn().
Referenced by LifeMeterBattery::AddLives(), ScreenTextEntry::BackspaceInAnswer(), ScreenGameplay::BeginScreen(), ScreenPrompt::Change(), WheelBase::ChangeMusic(), MusicWheel::ChangeMusic(), WheelBase::ChangeMusicUnlessLocked(), ScreenSetTime::ChangeSelection(), MusicWheel::ChangeSort(), ScreenSetTime::ChangeValue(), ScreenOptions::ChangeValueInRowRelative(), ScreenSelectMusic::DetectCodes(), ScreenOptionsCourseOverview::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), ScreenTestSound::Input(), ScreenMapControllers::Input(), ScreenSelectMusic::Input(), ScreenSelectMaster::MenuDown(), ScreenSelectMaster::MenuLeft(), ScreenSelectMaster::MenuRight(), ScreenSelectLanguage::MenuStart(), ScreenEvaluation::MenuStart(), ScreenOptions::MenuStart(), ScreenSelectMaster::MenuUp(), ScreenOptions::MenuUpDown(), WheelBase::Move(), LifeMeterTime::OnLoadSong(), LifeMeterBattery::OnSongEnded(), ActorSound::Play(), GameplayAssist::PlayTicks(), ScreenOptionsCourseOverview::ProcessMenuStart(), ScreenOptions::ProcessMenuStart(), WheelBase::Select(), ScreenSelectMusic::SelectCurrent(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), ScreenGameplay::StartPlayingSong(), LifeMeterBattery::SubtractLives(), ScreenGameplay::ToggleReplayPause(), ScreenTextEntry::TryAppendToAnswer(), MenuTimer::Update(), and WheelBase::Update().
PlayCopy()
void RageSound::PlayCopy (bool is_action, const RageSoundParams * pParams = nullptr) const
References PrefsManager::m_MuteActions, PREFSMAN, and RageSound().
Referenced by ScreenSelectMusic::ChangeSteps(), ScreenSelectMaster::MenuStart(), Play(), and ScreenOptions::ProcessMenuStart().
PushSelf()
virtual void RageSound::PushSelf (lua_State * L) virtual
Referenced by ActorSound::PushSound().
SetParams()
void RageSound::SetParams (const RageSoundParams & p)
References ApplyParams(), and m_Param.
Referenced by ScreenTestSound::Input(), LunaRageSound::pitch(), Play(), LunaRageSound::SetParam(), LunaRageSound::speed(), StartMusic(), GameSoundManager::Update(), ScreenGameplay::Update(), and LunaRageSound::volume().
SetPositionFrames()
bool RageSound::SetPositionFrames (int frames = -1) private
References RageSoundReader::GetError(), GetLoadedFilePath(), LockMut, LOG, m_iStoppedSourceFrame, m_Mutex, m_pSource, m_sError, RageSoundReader::SetPosition(), and RageLog::Warn().
Referenced by StartPlaying().
SetProperty()
bool RageSound::SetProperty (const RString & sProperty, float fValue)
References m_pSource, and RageSoundReader::SetProperty().
Referenced by ScreenGameplay::BeginScreen(), ScreenSelectMusic::ChangeSteps(), Player::Init(), Player::Load(), LunaRageSound::SetProperty(), and ScreenGameplay::StartPlayingSong().
SetStopModeFromString()
void RageSound::SetStopModeFromString (const RString & sStopMode)
References RageSoundParams::M_AUTO, RageSoundParams::M_CONTINUE, RageSoundParams::M_LOOP, m_Param, and RageSoundParams::M_STOP.
Referenced by Player::Load().
SoundIsFinishedPlaying()
void RageSound::SoundIsFinishedPlaying () override private virtual
Implements RageSoundBase.
References pos_map_queue::Clear(), RageSoundManager::GetPosition(), GetSourceFrameFromHardwareFrame(), pos_map_queue::IsEmpty(), RageMutex::Lock(), m_bDeleteWhenFinished, m_bPlaying, m_HardwareToStreamMap, m_iStoppedSourceFrame, m_Mutex, m_StreamToSourceMap, SOUNDMAN, and RageMutex::Unlock().
StartPlaying()
void RageSound::StartPlaying ()
References RageTimer::Ago(), ApplyParams(), ASSERT, GetLoadedFilePath(), RageSoundManager::GetVolumeOfNonCriticalSounds(), RageMutex::IsLockedByThisThread(), RageTimer::IsZero(), LOG, m_bPlaying, RageSoundParams::m_fAttractVolume, m_Mutex, m_Param, RageSoundParams::m_StartSecond, RageSoundParams::m_StartTime, samplerate, SetPositionFrames(), SOUNDMAN, RageSoundManager::StartMixing(), and RageLog::Trace().
Referenced by Play(), and StartMusic().
Stop()
void RageSound::Stop ()
References StopPlaying().
Referenced by ScreenGameplay::BeginScreen(), ScreenGameplay::Cancel(), ScreenGameplay::HandleScreenMessage(), ScreenGameplaySyncMachine::ResetAndRestartCurrentSong(), ScreenGameplayLesson::ResetAndRestartCurrentSong(), ScreenGameplay::SetRate(), ScreenGameplay::SetSongPosition(), and ActorSound::Stop().
StopPlaying()
void RageSound::StopPlaying ()
References ASSERT, RageMutex::IsLockedByThisThread(), m_Mutex, SOUNDMAN, and RageSoundManager::StopMixing().
Referenced by ScreenGameplay::BeginBackingOutFromGameplay(), Stop(), GameplayAssist::StopPlaying(), Unload(), ScreenGameplay::Update(), and ScreenGameplay::~ScreenGameplay().
Unload()
void RageSound::Unload ()
References IsPlaying(), LockMut, m_Mutex, m_pSource, m_sFilePath, and StopPlaying().
Referenced by AutoKeysounds::FinishLoading(), LoadSoundReader(), and ~RageSound().
Member Data Documentation
m_bDeleteWhenFinished
bool RageSound::m_bDeleteWhenFinished { false } private
Referenced by DeleteSelfWhenFinishedPlaying(), operator=(), and SoundIsFinishedPlaying().
m_bPlaying
bool RageSound::m_bPlaying { false } private
Referenced by DeleteSelfWhenFinishedPlaying(), GetDataToPlay(), IsPlaying(), operator=(), SoundIsFinishedPlaying(), and StartPlaying().
m_HardwareToStreamMap
pos_map_queue RageSound::m_HardwareToStreamMap private
Referenced by CommitPlayingPosition(), GetPositionSeconds(), GetSourceFrameFromHardwareFrame(), and SoundIsFinishedPlaying().
m_iStoppedSourceFrame
int RageSound::m_iStoppedSourceFrame { 0 } private
Referenced by GetPositionSeconds(), LoadSoundReader(), operator=(), SetPositionFrames(), and SoundIsFinishedPlaying().
m_iStreamFrame
int64_t RageSound::m_iStreamFrame private
Referenced by GetDataToPlay(), LoadSoundReader(), and operator=().
m_Mutex
RageMutex RageSound::m_Mutex mutable private
Referenced by CommitPlayingPosition(), DeleteSelfWhenFinishedPlaying(), GetDataToPlay(), GetPositionSeconds(), Load(), operator=(), SetPositionFrames(), SoundIsFinishedPlaying(), StartPlaying(), StopPlaying(), and Unload().
m_Param
RageSoundParams RageSound::m_Param private
Referenced by ApplyParams(), GetParams(), GetPlaybackRate(), GetStartTime(), GetStopMode(), operator=(), SetParams(), SetStopModeFromString(), and StartPlaying().
m_pSource
RageSoundReader* RageSound::m_pSource private
Referenced by ApplyParams(), GetDataToPlay(), GetLengthSeconds(), GetSoundReader(), IsLoaded(), Load(), LoadSoundReader(), operator=(), Pause(), Play(), RageSound(), SetPositionFrames(), SetProperty(), and Unload().
m_sError
RString RageSound::m_sError private
Referenced by GetDataToPlay(), GetError(), and SetPositionFrames().
m_sFilePath
RString RageSound::m_sFilePath private
Referenced by GetLoadedFilePath(), GetStopMode(), Load(), operator=(), and Unload().
m_StreamToSourceMap
pos_map_queue RageSound::m_StreamToSourceMap private
Referenced by GetDataToPlay(), GetPositionSeconds(), GetSourceFrameFromHardwareFrame(), and SoundIsFinishedPlaying().
The documentation for this class was generated from the following files:
RageSound.h
RageSound.cpp