Etterna: LunaProfile Class Reference
LunaProfile Class Reference
Allow Lua to have access to the Profile.
Public Member Functions
DEFINE_METHOD (GetType, m_Type)
DEFINE_METHOD (GetPriority, m_ListPriority)
DEFINE_METHOD (GetTotalDancePoints, m_iTotalDancePoints)
DEFINE_METHOD (GetGUID, m_sGuid)
LunaProfile ()
Public Member Functions inherited from Luna< Profile >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int AddScreenshot (T *p, lua_State *L)
static int GetDisplayName (T *p, lua_State *L)
static int SetDisplayName (T *p, lua_State *L)
static int GetLastUsedHighScoreName (T *p, lua_State *L)
static int SetLastUsedHighScoreName (T *p, lua_State *L)
static int GetHighScoreList (T *p, lua_State *L)
static int GetCategoryHighScoreList (T *p, lua_State *L)
static int GetHighScoreListIfExists (T *p, lua_State *L)
static int GetAllUsedHighScoreNames (T *p, lua_State *L)
static int GetCharacter (T *p, lua_State *L)
static int SetCharacter (T *p, lua_State *L)
static int GetTotalNumSongsPlayed (T *p, lua_State *L)
static int GetSongsActual (T *p, lua_State *L)
static int GetSongsPossible (T *p, lua_State *L)
static int GetSongsPercentComplete (T *p, lua_State *L)
static int GetTotalStepsWithTopGrade (T *p, lua_State *L)
static int GetNumTotalSongsPlayed (T *p, lua_State *L)
static int GetTotalSessions (T *p, lua_State *L)
static int GetTotalSessionSeconds (T *p, lua_State *L)
static int GetTotalGameplaySeconds (T *p, lua_State *L)
static int GetPlayerRating (T *p, lua_State *L)
static int GetMostPopularSong (T *p, lua_State *L)
static int GetSongNumTimesPlayed (T *p, lua_State *L)
static int HasPassedAnyStepsInSong (T *p, lua_State *L)
static int GetNumToasties (T *p, lua_State *L)
static int GetTotalTapsAndHolds (T *p, lua_State *L)
static int GetTotalJumps (T *p, lua_State *L)
static int GetTotalHolds (T *p, lua_State *L)
static int GetTotalRolls (T *p, lua_State *L)
static int GetTotalMines (T *p, lua_State *L)
static int GetTotalHands (T *p, lua_State *L)
static int GetTotalLifts (T *p, lua_State *L)
static int GetUserTable (T *p, lua_State *L)
static int GetNumFaves (T *p, lua_State *L)
static int GetLastPlayedSong (T *p, lua_State *L)
static int GetPlayerSkillsetRating (T *p, lua_State *L)
static int GetGoalTable (T *p, lua_State *L)
static int SetFromAll (T *p, lua_State *L)
static int SortByDate (T *p, lua_State *L)
static int SortByRate (T *p, lua_State *L)
static int SortByName (T *p, lua_State *L)
static int SortByPriority (T *p, lua_State *L)
static int SortByDiff (T *p, lua_State *L)
static int ToggleFilter (T *p, lua_State *L)
static int GetFilterMode (T *p, lua_State *L)
static int GetIgnoreStepCountCalories (T *p, lua_State *L)
static int CalculateCaloriesFromHeartRate (T *p, lua_State *L)
static int IsCurrentChartPermamirror (T *p, lua_State *L)
static int GetEasiestGoalForChartAndRate (T *p, lua_State *L)
static int RenameProfile (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Profile >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Profile >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Profile >
using T = Profile
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Profile >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Profile.
Constructor & Destructor Documentation
LunaProfile()
LunaProfile::LunaProfile () inline
References ADD_METHOD, Profile::AddScreenshot(), Profile::GetAllUsedHighScoreNames(), Profile::GetCategoryHighScoreList(), Profile::GetCharacter(), Profile::GetMostPopularSong(), Profile::GetSongNumTimesPlayed(), Profile::GetSongsActual(), Profile::GetSongsPercentComplete(), Profile::GetSongsPossible(), Profile::GetTotalStepsWithTopGrade(), Profile::HasPassedAnyStepsInSong(), and Profile::SetCharacter().
Member Function Documentation
AddScreenshot()
static int LunaProfile::AddScreenshot (T * p, lua_State * L) inline static
References Profile::AddScreenshot(), BinaryToHex(), Luna< Type >::check(), COMMON_RETURN_SELF, CRYPTMAN, CryptManager::GetMD5ForFile(), Screenshot::highScore, SArg, Screenshot::sFileName, and Screenshot::sMD5.
CalculateCaloriesFromHeartRate()
static int LunaProfile::CalculateCaloriesFromHeartRate (T * p, lua_State * L) inline static
DEFINE_METHOD() [1/4]
LunaProfile::DEFINE_METHOD (GetType , m_Type)
DEFINE_METHOD() [2/4]
LunaProfile::DEFINE_METHOD (GetPriority , m_ListPriority)
DEFINE_METHOD() [3/4]
LunaProfile::DEFINE_METHOD (GetTotalDancePoints , m_iTotalDancePoints)
DEFINE_METHOD() [4/4]
LunaProfile::DEFINE_METHOD (GetGUID , m_sGuid)
GetAllUsedHighScoreNames()
static int LunaProfile::GetAllUsedHighScoreNames (T * p, lua_State * L) inline static
References Profile::GetAllUsedHighScoreNames().
GetCategoryHighScoreList()
static int LunaProfile::GetCategoryHighScoreList (T * p, lua_State * L) inline static
References Profile::GetCategoryHighScoreList(), L, and HighScoreList::PushSelf().
GetCharacter()
static int LunaProfile::GetCharacter (T * p, lua_State * L) inline static
References Profile::GetCharacter(), and Character::PushSelf().
GetDisplayName()
static int LunaProfile::GetDisplayName (T * p, lua_State * L) inline static
References Profile::m_sDisplayName.
GetEasiestGoalForChartAndRate()
static int LunaProfile::GetEasiestGoalForChartAndRate (T * p, lua_State * L) inline static
References f, FArg, Profile::goalmap, ScoreGoal::percent, ScoreGoal::PushSelf(), and SArg.
GetFilterMode()
static int LunaProfile::GetFilterMode (T * p, lua_State * L) inline static
References Profile::filtermode.
GetGoalTable()
static int LunaProfile::GetGoalTable (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and Profile::goaltable.
GetHighScoreList()
static int LunaProfile::GetHighScoreList (T * p, lua_State * L) inline static
References Luna< Type >::check(), LuaBinding::CheckLuaObjectType(), COMMON_RETURN_SELF, Profile::GetStepsHighScoreList(), and HighScoreList::PushSelf().
GetHighScoreListIfExists()
static int LunaProfile::GetHighScoreListIfExists (T * p, lua_State * L) inline static
References LuaBinding::CheckLuaObjectType(), and GET_IF_EXISTS.
GetIgnoreStepCountCalories()
static int LunaProfile::GetIgnoreStepCountCalories (T * p, lua_State * L) inline static
GetLastPlayedSong()
static int LunaProfile::GetLastPlayedSong (T * p, lua_State * L) inline static
References Profile::m_lastSong, Song::PushSelf(), and SongID::ToSong().
GetLastUsedHighScoreName()
static int LunaProfile::GetLastUsedHighScoreName (T * p, lua_State * L) inline static
References Profile::m_sLastUsedHighScoreName.
GetMostPopularSong()
static int LunaProfile::GetMostPopularSong (T * p, lua_State * L) inline static
References Profile::GetMostPopularSong(), and Song::PushSelf().
GetNumFaves()
static int LunaProfile::GetNumFaves (T * p, lua_State * L) inline static
References Profile::FavoritedCharts.
GetNumToasties()
static int LunaProfile::GetNumToasties (T * p, lua_State * L) inline static
References Profile::m_iNumToasties.
GetNumTotalSongsPlayed()
static int LunaProfile::GetNumTotalSongsPlayed (T * p, lua_State * L) inline static
References Profile::m_iNumTotalSongsPlayed.
GetPlayerRating()
static int LunaProfile::GetPlayerRating (T * p, lua_State * L) inline static
References Profile::m_fPlayerRating.
GetPlayerSkillsetRating()
static int LunaProfile::GetPlayerSkillsetRating (T * p, lua_State * L) inline static
References L, and Profile::m_fPlayerSkillsets.
GetSongNumTimesPlayed()
static int LunaProfile::GetSongNumTimesPlayed (T * p, lua_State * L) inline static
References ASSERT, Luna< Type >::check(), and Profile::GetSongNumTimesPlayed().
GetSongsActual()
static int LunaProfile::GetSongsActual (T * p, lua_State * L) inline static
References Profile::GetSongsActual().
GetSongsPercentComplete()
static int LunaProfile::GetSongsPercentComplete (T * p, lua_State * L) inline static
References Profile::GetSongsPercentComplete().
GetSongsPossible()
static int LunaProfile::GetSongsPossible (T * p, lua_State * L) inline static
References Profile::GetSongsPossible().
GetTotalGameplaySeconds()
static int LunaProfile::GetTotalGameplaySeconds (T * p, lua_State * L) inline static
References Profile::m_iTotalGameplaySeconds.
GetTotalHands()
static int LunaProfile::GetTotalHands (T * p, lua_State * L) inline static
References Profile::m_iTotalHands.
GetTotalHolds()
static int LunaProfile::GetTotalHolds (T * p, lua_State * L) inline static
References Profile::m_iTotalHolds.
GetTotalJumps()
static int LunaProfile::GetTotalJumps (T * p, lua_State * L) inline static
References Profile::m_iTotalJumps.
GetTotalLifts()
static int LunaProfile::GetTotalLifts (T * p, lua_State * L) inline static
References Profile::m_iTotalLifts.
GetTotalMines()
static int LunaProfile::GetTotalMines (T * p, lua_State * L) inline static
References Profile::m_iTotalMines.
GetTotalNumSongsPlayed()
static int LunaProfile::GetTotalNumSongsPlayed (T * p, lua_State * L) inline static
References Profile::m_iNumTotalSongsPlayed.
GetTotalRolls()
static int LunaProfile::GetTotalRolls (T * p, lua_State * L) inline static
References Profile::m_iTotalRolls.
GetTotalSessions()
static int LunaProfile::GetTotalSessions (T * p, lua_State * L) inline static
References Profile::m_iTotalSessions.
GetTotalSessionSeconds()
static int LunaProfile::GetTotalSessionSeconds (T * p, lua_State * L) inline static
References Profile::m_iTotalSessionSeconds.
GetTotalStepsWithTopGrade()
static int LunaProfile::GetTotalStepsWithTopGrade (T * p, lua_State * L) inline static
References Profile::GetTotalStepsWithTopGrade().
GetTotalTapsAndHolds()
static int LunaProfile::GetTotalTapsAndHolds (T * p, lua_State * L) inline static
References Profile::m_iTotalTapsAndHolds.
GetUserTable()
static int LunaProfile::GetUserTable (T * p, lua_State * L) inline static
References Profile::m_UserTable, and LuaReference::PushSelf().
HasPassedAnyStepsInSong()
static int LunaProfile::HasPassedAnyStepsInSong (T * p, lua_State * L) inline static
References ASSERT, Luna< Type >::check(), and Profile::HasPassedAnyStepsInSong().
IsCurrentChartPermamirror()
static int LunaProfile::IsCurrentChartPermamirror (T * p, lua_State * L) inline static
References GAMESTATE, GameState::m_pCurSteps, Profile::PermaMirrorCharts, and PLAYER_1.
RenameProfile()
static int LunaProfile::RenameProfile (T * p, lua_State * L) inline static
References Profile::m_sDisplayName, Profile::m_sProfileID, SArg, and Profile::SaveEditableDataToDir().
SetCharacter()
static int LunaProfile::SetCharacter (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and Profile::SetCharacter().
SetDisplayName()
static int LunaProfile::SetDisplayName (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Profile::m_sDisplayName, and SArg.
SetFromAll()
static int LunaProfile::SetFromAll (T * p, lua_State * L) inline static
References Profile::asc, Profile::FillGoalTable(), and Profile::filtermode.
SetLastUsedHighScoreName()
static int LunaProfile::SetLastUsedHighScoreName (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Profile::m_sLastUsedHighScoreName, and SArg.
SortByDate()
static int LunaProfile::SortByDate (T * p, lua_State * L) inline static
References Profile::asc, Profile::goaltable, Profile::sortmode, and ScoreGoal::timeassigned.
SortByDiff()
static int LunaProfile::SortByDiff (T * p, lua_State * L) inline static
References Profile::asc, ScoreGoal::chartkey, Steps::GetMSD(), SongManager::GetStepsByChartkey(), Profile::goaltable, ScoreGoal::rate, SONGMAN, and Profile::sortmode.
SortByName()
static int LunaProfile::SortByName (T * p, lua_State * L) inline static
References Profile::asc, ScoreGoal::chartkey, Song::GetDisplayMainTitle(), SongManager::GetSongByChartkey(), Profile::goaltable, Rage::make_lower(), SONGMAN, and Profile::sortmode.
SortByPriority()
static int LunaProfile::SortByPriority (T * p, lua_State * L) inline static
References Profile::asc, Profile::goaltable, ScoreGoal::priority, and Profile::sortmode.
SortByRate()
static int LunaProfile::SortByRate (T * p, lua_State * L) inline static
References Profile::asc, Profile::goaltable, ScoreGoal::rate, and Profile::sortmode.
ToggleFilter()
static int LunaProfile::ToggleFilter (T * p, lua_State * L) inline static
References Profile::FillGoalTable(), Profile::filtermode, and Profile::goaltable.
The documentation for this class was generated from the following file:
Profile.cpp