Etterna: RageSoundReader_PitchChange Class Reference
RageSoundReader_PitchChange Class Reference
#include <RageSoundReader_PitchChange.h>
Public Member Functions
RageSoundReader_PitchChange (RageSoundReader *pSource)
RageSoundReader_PitchChange (const RageSoundReader_PitchChange &cpy)
int Read (float *pBuf, int iFrames) override
bool SetProperty (const RString &sProperty, float fValue) override
void SetSpeedRatio (float fRatio)
void SetPitchRatio (float fRatio)
RageSoundReader_PitchChange * Copy () const override
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
RageSoundReader_PitchChange & operator= (const RageSoundReader_PitchChange &rhs)=delete
Private Attributes
RageSoundReader_SpeedChange * m_pSpeedChange
RageSoundReader_Resample_Good * m_pResample
float m_fSpeedRatio
float m_fPitchRatio
float m_fLastSetSpeedRatio
float m_fLastSetPitchRatio
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Constructor & Destructor Documentation
RageSoundReader_PitchChange() [1/2]
RageSoundReader_PitchChange::RageSoundReader_PitchChange (RageSoundReader * pSource)
References RageSoundReader_Filter::GetSampleRate(), m_fLastSetPitchRatio, m_fLastSetSpeedRatio, m_fPitchRatio, m_fSpeedRatio, m_pResample, RageSoundReader_Filter::m_pSource, and m_pSpeedChange.
Referenced by Copy().
RageSoundReader_PitchChange() [2/2]
RageSoundReader_PitchChange::RageSoundReader_PitchChange (const RageSoundReader_PitchChange & cpy)
References RageSoundReader_Filter::GetSource(), m_fLastSetPitchRatio, m_fLastSetSpeedRatio, m_fPitchRatio, m_fSpeedRatio, m_pResample, RageSoundReader_Filter::m_pSource, and m_pSpeedChange.
Member Function Documentation
Copy()
RageSoundReader_PitchChange* RageSoundReader_PitchChange::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_PitchChange().
operator=()
RageSoundReader_PitchChange& RageSoundReader_PitchChange::operator= (const RageSoundReader_PitchChange & rhs) private delete
Read()
int RageSoundReader_PitchChange::Read (float * pBuf, int iFrames) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Resample_Good::GetRate(), RageSoundReader_Filter::GetStreamToSourceRatio(), m_fLastSetPitchRatio, m_fLastSetSpeedRatio, m_fPitchRatio, m_fSpeedRatio, m_pResample, m_pSpeedChange, RageSoundReader_SpeedChange::NextReadWillStep(), RageSoundReader_Filter::Read(), RageSoundReader_Resample_Good::SetRate(), and RageSoundReader_SpeedChange::SetSpeedRatio().
SetPitchRatio()
void RageSoundReader_PitchChange::SetPitchRatio (float fRatio) inline
References m_fPitchRatio.
Referenced by SetProperty().
SetProperty()
bool RageSoundReader_PitchChange::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader_Filter.
References EnablePitchRates, Preference< T >::Get(), SetPitchRatio(), RageSoundReader_Filter::SetProperty(), and SetSpeedRatio().
SetSpeedRatio()
void RageSoundReader_PitchChange::SetSpeedRatio (float fRatio) inline
References m_fSpeedRatio.
Referenced by SetProperty().
Member Data Documentation
m_fLastSetPitchRatio
float RageSoundReader_PitchChange::m_fLastSetPitchRatio private
Referenced by RageSoundReader_PitchChange(), and Read().
m_fLastSetSpeedRatio
float RageSoundReader_PitchChange::m_fLastSetSpeedRatio private
Referenced by RageSoundReader_PitchChange(), and Read().
m_fPitchRatio
float RageSoundReader_PitchChange::m_fPitchRatio private
Referenced by RageSoundReader_PitchChange(), Read(), and SetPitchRatio().
m_fSpeedRatio
float RageSoundReader_PitchChange::m_fSpeedRatio private
Referenced by RageSoundReader_PitchChange(), Read(), and SetSpeedRatio().
m_pResample
RageSoundReader_Resample_Good* RageSoundReader_PitchChange::m_pResample private
Referenced by RageSoundReader_PitchChange(), and Read().
m_pSpeedChange
RageSoundReader_SpeedChange* RageSoundReader_PitchChange::m_pSpeedChange private
Referenced by RageSoundReader_PitchChange(), and Read().
The documentation for this class was generated from the following files:
RageSoundReader_PitchChange.h
RageSoundReader_PitchChange.cpp