Etterna: RageSoundReader Class Reference
RageSoundReader Class Reference abstract
#include <RageSoundReader.h>
Public Types
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Public Member Functions
virtual int GetLength () const =0
virtual int GetLength_Fast () const
virtual int SetPosition (int iFrame)=0
virtual int Read (float *pBuf, int iFrames)=0
virtual ~RageSoundReader ()=default
virtual RageSoundReader * Copy () const =0
virtual int GetSampleRate () const =0
virtual unsigned GetNumChannels () const =0
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
virtual int GetNextSourceFrame () const =0
virtual float GetStreamToSourceRatio () const =0
virtual RString GetError () const =0
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
RSRERROR
END_OF_FILE
WOULD_BLOCK
STREAM_LOOPED
Constructor & Destructor Documentation
~RageSoundReader()
virtual RageSoundReader::~RageSoundReader () virtual default
Member Function Documentation
Copy()
virtual RageSoundReader* RageSoundReader::Copy () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_MP3, RageSoundReader_Preload, RageSoundReader_WAV, RageSoundReader_PitchChange, RageSoundReader_Vorbisfile, RageSoundReader_Resample_Good, RageSoundReader_ThreadedBuffer, RageSoundReader_Extend, RageSoundReader_Split, RageSoundReader_SpeedChange, RageSoundReader_Chain, RageSoundReader_Merge, RageSoundReader_Pan, and RageSoundReader_PostBuffering.
Referenced by RageSoundReader_Chain::ActivateSound(), RageSound::operator=(), and RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer().
GetError()
virtual RString RageSoundReader::GetError () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_Filter, RageSoundReader_FileReader, RageSoundReader_Split, RageSoundReader_Merge, and RageSoundReader_Preload.
Referenced by RageSound::GetDataToPlay(), RageSoundReader_Split::GetError(), RageSoundReader_Filter::GetError(), RageSound::GetLengthSeconds(), and RageSound::SetPositionFrames().
GetLength()
virtual int RageSoundReader::GetLength () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_ThreadedBuffer, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_WAV, RageSoundReader_Merge, RageSoundReader_Filter, RageSoundReader_Preload, and RageSoundReader_Vorbisfile.
Referenced by LunaRageSound::get_length(), RageSoundReader_Filter::GetLength(), RageSoundReader_Split::GetLength(), RageSoundReader_ThreadedBuffer::GetLength(), RageSoundReader_Chain::GetLength(), GetLength_Fast(), RageSound::GetLengthSeconds(), LuaFunc_get_music_file_length(), and Song::TidyUpData().
GetLength_Fast()
virtual int RageSoundReader::GetLength_Fast () const inline virtual
Reimplemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_ThreadedBuffer, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_Filter, and RageSoundReader_Preload.
References GetLength().
Referenced by RageSoundReader_Filter::GetLength_Fast(), RageSoundReader_Split::GetLength_Fast(), RageSoundReader_ThreadedBuffer::GetLength_Fast(), RageSoundReader_Chain::GetLength_Fast(), and RageSoundReader_Preload::Open().
GetNextSourceFrame()
virtual int RageSoundReader::GetNextSourceFrame () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_Filter, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_ThreadedBuffer, RageSoundReader_WAV, RageSoundReader_Preload, RageSoundReader_Resample_Good, RageSoundReader_SpeedChange, RageSoundReader_Vorbisfile, and RageSoundReader_Extend.
Referenced by RageSoundReader_Extend::GetData(), RageSoundReader_Resample_Good::GetNextSourceFrame(), RageSoundReader_Filter::GetNextSourceFrame(), RageSoundReader_Extend::RageSoundReader_Extend(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageSoundReader_Merge::Read(), and RetriedRead().
GetNumChannels()
virtual unsigned RageSoundReader::GetNumChannels () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_ThreadedBuffer, RageSoundReader_Filter, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_WAV, RageSoundReader_Preload, RageSoundReader_Vorbisfile, and RageSoundReader_Pan.
Referenced by RageSoundReader_Chain::ActivateSound(), RageSound::GetDataToPlay(), RageSoundReader_Filter::GetNumChannels(), RageSoundReader_Preload::Open(), RageSoundReader_SpeedChange::RageSoundReader_SpeedChange(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageSoundReader_Pan::Read(), RageSoundReader_Merge::Read(), RageSoundReader_Split::Read(), RageSoundReader_Chain::Read(), RageSoundSplitterImpl::ReadBuffer(), RageSoundReader_Resample_Good::ReopenResampler(), and RageSoundReader_Resample_Good::Reset().
GetSampleRate()
virtual int RageSoundReader::GetSampleRate () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_Resample_Good, RageSoundReader_ThreadedBuffer, RageSoundReader_MP3, RageSoundReader_Filter, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_WAV, RageSoundReader_Preload, and RageSoundReader_Vorbisfile.
Referenced by RageSoundReader_Resample_Good::GetFactors(), RageSoundReader_Resample_Good::GetNextSourceFrame(), RageSoundReader_Split::GetSampleRate(), RageSoundReader_Filter::GetSampleRate(), RageSound::LoadSoundReader(), RageSoundReader_Preload::Open(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), and RageSoundReader_Resample_Good::SetPosition().
GetSource()
virtual RageSoundReader* RageSoundReader::GetSource () inline virtual
Reimplemented in RageSoundReader_Filter, and RageSoundReader_ThreadedBuffer.
GetStreamToSourceRatio()
virtual float RageSoundReader::GetStreamToSourceRatio () const pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_Filter, RageSoundReader_FileReader, RageSoundReader_ThreadedBuffer, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_Preload, RageSoundReader_Resample_Good, and RageSoundReader_SpeedChange.
Referenced by RageSoundReader_Resample_Good::GetStreamToSourceRatio(), RageSoundReader_Filter::GetStreamToSourceRatio(), RageSoundReader_Preload::Open(), RageSoundReader_ThreadedBuffer::RageSoundReader_ThreadedBuffer(), RageSoundReader_Merge::Read(), and RetriedRead().
Read()
virtual int RageSoundReader::Read (float * pBuf, int iFrames) pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_ThreadedBuffer, RageSoundReader_Filter, RageSoundReader_Merge, RageSoundReader_WAV, RageSoundReader_Preload, RageSoundReader_PitchChange, RageSoundReader_Resample_Good, RageSoundReader_Vorbisfile, RageSoundReader_Pan, RageSoundReader_PostBuffering, RageSoundReader_SpeedChange, and RageSoundReader_Extend.
Referenced by RageSoundReader_SpeedChange::FillData(), RageSoundReader_Preload::Open(), RageSoundReader_SpeedChange::Read(), RageSoundReader_PostBuffering::Read(), RageSoundReader_Pan::Read(), RageSoundReader_Resample_Good::Read(), RageSoundReader_Merge::Read(), RageSoundReader_Filter::Read(), RageSoundSplitterImpl::ReadBuffer(), and RetriedRead().
RetriedRead()
int RageSoundReader::RetriedRead (float * pBuffer, int iFrames, int * iSourceFrame = NULL, float * fRate = NULL)
References END_OF_FILE, GetNextSourceFrame(), GetStreamToSourceRatio(), LOG, Read(), STREAM_LOOPED, and RageLog::Warn().
Referenced by RageSoundReader_ThreadedBuffer::FillBlock(), RageSound::GetDataToPlay(), and RageSoundReader_Chain::Read().
SetPosition()
virtual int RageSoundReader::SetPosition (int iFrame) pure virtual
Implemented in RageSoundReader_Silence, RageSoundReader_Chain, RageSoundReader_MP3, RageSoundReader_Split, RageSoundReader_ThreadedBuffer, RageSoundReader_Merge, RageSoundReader_WAV, RageSoundReader_Filter, RageSoundReader_Preload, RageSoundReader_Resample_Good, RageSoundReader_Vorbisfile, RageSoundReader_SpeedChange, and RageSoundReader_Extend.
Referenced by RageSoundReader_Preload::PreloadSound(), RageSoundSplitterImpl::ReadBuffer(), RageSoundReader_Extend::SetPosition(), RageSoundReader_Resample_Good::SetPosition(), RageSoundReader_Filter::SetPosition(), RageSoundReader_Merge::SetPosition(), RageSoundReader_Chain::SetPosition(), and RageSound::SetPositionFrames().
SetProperty()
virtual bool RageSoundReader::SetProperty (const RString & , float) inline virtual
Reimplemented in RageSoundReader_Chain, RageSoundReader_Filter, RageSoundReader_ThreadedBuffer, RageSoundReader_Split, RageSoundReader_Merge, RageSoundReader_Resample_Good, RageSoundReader_SpeedChange, RageSoundReader_PitchChange, RageSoundReader_Pan, RageSoundReader_PostBuffering, and RageSoundReader_Extend.
Referenced by RageSoundReader_Chain::ActivateSound(), RageSound::ApplyParams(), ScreenGameplay::HandleMessage(), RageSoundReader_Resample_Good::SetProperty(), RageSoundReader_Split::SetProperty(), RageSoundReader_MP3::SetProperty(), RageSoundReader_ThreadedBuffer::SetProperty(), RageSoundReader_Filter::SetProperty(), RageSound::SetProperty(), and SoundEffectControl::Update().
The documentation for this class was generated from the following files:
RageSoundReader.h
RageSoundReader.cpp