Etterna: ActorMultiVertex Class Reference
ActorMultiVertex Class Reference
#include <ActorMultiVertex.h>
Classes
struct AMV_TweenState
struct State
Public Member Functions
ActorMultiVertex ()
ActorMultiVertex (const ActorMultiVertex &cpy)
~ActorMultiVertex () override
void LoadFromNode (const XNode *Node) override
ActorMultiVertex * Copy () const override
AMV_TweenState & AMV_DestTweenState ()
const AMV_TweenState & AMV_DestTweenState () const
void EnableAnimation (bool bEnable) override
void Update (float fDelta) override
bool EarlyAbortDraw () const override
Allow the Actor to be aborted early.
void DrawPrimitives () override
Draw the primitives of the Actor.
virtual void DrawInternal (const AMV_TweenState *TS)
void SetCurrentTweenStart () override
void EraseHeadTween () override
void UpdatePercentThroughTween (float PercentThroughTween) override
void BeginTweening (float time, ITween *pInterp) override
void StopTweening () override
void FinishTweening () override
void SetTexture (RageTexture *Texture)
RageTexture * GetTexture ()
void LoadFromTexture (const RageTextureID &ID)
void UnloadTexture ()
void SetNumVertices (size_t n)
void AddVertex ()
void AddVertices (int Add)
void SetEffectMode (EffectMode em)
void SetTextureMode (TextureMode tm)
void SetLineWidth (float width)
void SetDrawState (DrawMode dm, int first, int num)
DrawMode GetDestDrawMode () const
int GetDestFirstToDraw () const
int GetDestNumToDraw () const
DrawMode GetCurrDrawMode () const
int GetCurrFirstToDraw () const
int GetCurrNumToDraw () const
size_t GetNumVertices ()
void SetVertexPos (int index, float x, float y, float z)
void SetVertexColor (int index, const RageColor &c)
void SetVertexCoords (int index, float TexCoordX, float TexCoordY)
void SetVertsFromSplinesInternal (size_t num_splines, size_t start_vert)
void SetVertsFromSplines ()
CubicSplineN * GetSpline (size_t i)
int GetNumStates () const override
void AddState (const State &new_state)
void RemoveState (size_t i)
size_t GetState ()
State & GetStateData (size_t i)
void SetStateData (size_t i, const State &s)
void SetStateProperties (const vector< State > &new_states)
void SetState (size_t i)
void SetAllStateDelays (float delay)
float GetAnimationLengthSeconds () const override
void SetSecondsIntoAnimation (float seconds) override
void UpdateAnimationState (bool force_update=false)
size_t GetNumQuadStates () const
void AddQuadState (size_t s)
void RemoveQuadState (size_t i)
size_t GetQuadState (size_t i)
void SetQuadState (size_t i, size_t s)
void PushSelf (lua_State *L) override
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
virtual void InitState ()
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void BeginDraw ()
Start the drawing and push the transform on the world matrix stack.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
virtual void EndDraw ()
Pop the transform from the world matrix stack.
bool IsFirstUpdate () const
virtual void UpdateInternal (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
virtual void HurryTweening (float factor)
virtual float GetTweenTimeLeft () const
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
virtual void SetZTestMode (ZTestMode mode)
virtual void SetZWrite (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
virtual void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
virtual void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void HandleMessage (const Message &msg) override
virtual void SetState (int)
virtual void SetUpdateRate (float)
virtual float GetUpdateRate ()
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Public Attributes
bool _use_animation_state
bool _decode_movie
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Public Attributes
static const size_t num_vert_splines = 4
Private Attributes
RageTexture * _Texture
vector< RageSpriteVertex > _Vertices
vector< AMV_TweenState > AMV_Tweens
AMV_TweenState AMV_current
AMV_TweenState AMV_start
AMV_TweenState * AMV_TempState
EffectMode _EffectMode
TextureMode _TextureMode
vector< CubicSplineN > _splines
bool _skip_next_update
float _secs_into_state
size_t _cur_state
vector< State > _states
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Constructor & Destructor Documentation
ActorMultiVertex() [1/2]
ActorMultiVertex::ActorMultiVertex ()
References _cur_state, _decode_movie, _EffectMode, _secs_into_state, _skip_next_update, _splines, _Texture, _TextureMode, _use_animation_state, EffectMode_Normal, RageTextureManager::GetDefaultTextureID(), RageTextureManager::LoadTexture(), num_vert_splines, TEXTUREMAN, and TextureMode_Modulate.
ActorMultiVertex() [2/2]
ActorMultiVertex::ActorMultiVertex (const ActorMultiVertex & cpy)
References _cur_state, _EffectMode, _secs_into_state, _skip_next_update, _splines, _states, _Texture, _TextureMode, _use_animation_state, AMV_current, AMV_start, AMV_Tweens, RageTextureManager::CopyTexture(), CPY, and TEXTUREMAN.
~ActorMultiVertex()
ActorMultiVertex::~ActorMultiVertex () override
References UnloadTexture().
Member Function Documentation
AddQuadState()
void ActorMultiVertex::AddQuadState (size_t s) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::quad_states.
Referenced by LunaActorMultiVertex::AddQuadState(), and LunaActorMultiVertex::LunaActorMultiVertex().
AddState()
void ActorMultiVertex::AddState (const State & new_state) inline
References _states.
Referenced by LunaActorMultiVertex::AddState(), and LunaActorMultiVertex::LunaActorMultiVertex().
AddVertex()
void ActorMultiVertex::AddVertex ()
References AMV_current, AMV_start, AMV_Tweens, and ActorMultiVertex::AMV_TweenState::vertices.
AddVertices()
void ActorMultiVertex::AddVertices (int Add)
References AMV_current, AMV_DestTweenState(), AMV_start, AMV_Tweens, and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::SetVertex(), and LunaActorMultiVertex::SetVertices().
AMV_DestTweenState() [1/2]
AMV_TweenState& ActorMultiVertex::AMV_DestTweenState () inline
References AMV_current, and AMV_Tweens.
Referenced by AddQuadState(), AddVertices(), AMV_DestTweenState(), FinishTweening(), GetDestDrawMode(), GetDestFirstToDraw(), GetDestNumToDraw(), GetNumQuadStates(), GetNumVertices(), GetQuadState(), RemoveQuadState(), SetDrawState(), SetLineWidth(), SetQuadState(), SetVertexColor(), SetVertexCoords(), SetVertexPos(), SetVertsFromSplines(), SetVertsFromSplinesInternal(), and UpdateAnimationState().
AMV_DestTweenState() [2/2]
const AMV_TweenState& ActorMultiVertex::AMV_DestTweenState () const inline
References AMV_DestTweenState().
BeginTweening()
void ActorMultiVertex::BeginTweening (float time, ITween * pInterp) override virtual
Reimplemented from Actor.
References AMV_current, AMV_Tweens, and Actor::BeginTweening().
Copy()
ActorMultiVertex* ActorMultiVertex::Copy () const override virtual
Reimplemented from Actor.
DrawInternal()
void ActorMultiVertex::DrawInternal (const AMV_TweenState * TS) virtual
References ActorMultiVertex::AMV_TweenState::_DrawMode, _EffectMode, DISPLAY, RageDisplay::DrawFan(), RageDisplay::DrawLineStrip(), DrawMode_Fan, DrawMode_LineStrip, DrawMode_Quads, DrawMode_QuadStrip, DrawMode_Strip, DrawMode_SymmetricQuadStrip, DrawMode_Triangles, RageDisplay::DrawQuads(), RageDisplay::DrawQuadStrip(), RageDisplay::DrawStrip(), RageDisplay::DrawSymmetricQuadStrip(), RageDisplay::DrawTriangles(), EffectMode_Normal, ActorMultiVertex::AMV_TweenState::FirstToDraw, ActorMultiVertex::AMV_TweenState::GetSafeNumToDraw(), ActorMultiVertex::AMV_TweenState::line_width, ActorMultiVertex::AMV_TweenState::NumToDraw, RageDisplay::SetEffectMode(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by DrawPrimitives().
DrawPrimitives()
void ActorMultiVertex::DrawPrimitives () override virtual
Draw the primitives of the Actor.
Derivative classes should override this function.
Reimplemented from Actor.
References _EffectMode, _Texture, _TextureMode, RageColor::a, AMV_current, AMV_TempState, RageColor::b, Actor::TweenState::diffuse, DISPLAY, DrawInternal(), RageColor::g, RageTexture::GetTexHandle(), Actor::TweenState::glow, Actor::m_pTempState, MULT_COLOR_ELEMENTS, RageColor::r, RageDisplay::SetEffectMode(), Actor::SetGlobalRenderStates(), RageDisplay::SetTexture(), RageDisplay::SetTextureMode(), Actor::SetTextureRenderStates(), TextureMode_Glow, TextureUnit_1, and ActorMultiVertex::AMV_TweenState::vertices.
EarlyAbortDraw()
bool ActorMultiVertex::EarlyAbortDraw () const override virtual
Allow the Actor to be aborted early.
Subclasses may wish to overwrite this to allow for aborted actors.
Returns
false, as by default Actors shouldn't be aborted on drawing.
Reimplemented from Actor.
References ActorMultiVertex::AMV_TweenState::_DrawMode, AMV_current, ActorMultiVertex::AMV_TweenState::FirstToDraw, NUM_DrawMode, and ActorMultiVertex::AMV_TweenState::vertices.
EnableAnimation()
void ActorMultiVertex::EnableAnimation (bool bEnable) override virtual
Reimplemented from Actor.
References _skip_next_update, Actor::EnableAnimation(), and Actor::m_bIsAnimating.
EraseHeadTween()
void ActorMultiVertex::EraseHeadTween () override virtual
Reimplemented from Actor.
References AMV_current, and AMV_Tweens.
FinishTweening()
void ActorMultiVertex::FinishTweening () override virtual
Reimplemented from Actor.
References AMV_current, AMV_DestTweenState(), AMV_Tweens, and Actor::FinishTweening().
GetAnimationLengthSeconds()
float ActorMultiVertex::GetAnimationLengthSeconds () const override virtual
Reimplemented from Actor.
References _states, and FOREACH_CONST.
Referenced by Update().
GetCurrDrawMode()
DrawMode ActorMultiVertex::GetCurrDrawMode () const inline
References ActorMultiVertex::AMV_TweenState::_DrawMode, and AMV_current.
Referenced by LunaActorMultiVertex::GetCurrDrawMode(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetCurrFirstToDraw()
int ActorMultiVertex::GetCurrFirstToDraw () const inline
References AMV_current, and ActorMultiVertex::AMV_TweenState::FirstToDraw.
Referenced by LunaActorMultiVertex::GetCurrFirstToDraw(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetCurrNumToDraw()
int ActorMultiVertex::GetCurrNumToDraw () const inline
References AMV_current, and ActorMultiVertex::AMV_TweenState::NumToDraw.
Referenced by LunaActorMultiVertex::GetCurrNumToDraw(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetDestDrawMode()
DrawMode ActorMultiVertex::GetDestDrawMode () const inline
References ActorMultiVertex::AMV_TweenState::_DrawMode, and AMV_DestTweenState().
Referenced by LunaActorMultiVertex::GetDestDrawMode(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetDrawState().
GetDestFirstToDraw()
int ActorMultiVertex::GetDestFirstToDraw () const inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::FirstToDraw.
Referenced by LunaActorMultiVertex::GetDestFirstToDraw(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetDrawState().
GetDestNumToDraw()
int ActorMultiVertex::GetDestNumToDraw () const inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::NumToDraw.
Referenced by LunaActorMultiVertex::GetDestNumToDraw(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetDrawState().
GetNumQuadStates()
size_t ActorMultiVertex::GetNumQuadStates () const inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::quad_states.
Referenced by LunaActorMultiVertex::GetNumQuadStates(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::QuadStateIndex().
GetNumStates()
int ActorMultiVertex::GetNumStates () const inline override virtual
Reimplemented from Actor.
References _states.
Referenced by LunaActorMultiVertex::GetNumStates(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::ValidStateIndex().
GetNumVertices()
size_t ActorMultiVertex::GetNumVertices () inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::GetNumVertices(), LunaActorMultiVertex::LunaActorMultiVertex(), LunaActorMultiVertex::SetVertex(), and LunaActorMultiVertex::SetVertices().
GetQuadState()
size_t ActorMultiVertex::GetQuadState (size_t i) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::quad_states.
Referenced by LunaActorMultiVertex::GetQuadState(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetSpline()
CubicSplineN * ActorMultiVertex::GetSpline (size_t i)
References _splines, ASSERT, and num_vert_splines.
Referenced by LunaActorMultiVertex::GetSpline(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetState()
size_t ActorMultiVertex::GetState () inline
References _cur_state.
Referenced by LunaActorMultiVertex::GetState(), and LunaActorMultiVertex::LunaActorMultiVertex().
GetStateData()
State& ActorMultiVertex::GetStateData (size_t i) inline
References _states, and ASSERT.
Referenced by LunaActorMultiVertex::GetStateData(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetStateData().
GetTexture()
RageTexture* ActorMultiVertex::GetTexture () inline
References _Texture.
Referenced by LunaActorMultiVertex::AddState(), LunaActorMultiVertex::GetStateData(), LunaActorMultiVertex::GetTexture(), LunaActorMultiVertex::LunaActorMultiVertex(), LunaActorMultiVertex::SetStateData(), and LunaActorMultiVertex::SetStateProperties().
LoadFromNode()
void ActorMultiVertex::LoadFromNode (const XNode * Node) override virtual
Reimplemented from Actor.
References ActorUtil::GetAttrPath(), XNode::GetAttrValue(), RageTextureManager::IsTextureRegistered(), Actor::LoadFromNode(), LoadFromTexture(), and TEXTUREMAN.
LoadFromTexture()
void ActorMultiVertex::LoadFromTexture (const RageTextureID & ID)
References _Texture, RageTexture::GetID(), RageTextureManager::LoadTexture(), SetTexture(), and TEXTUREMAN.
Referenced by LoadFromNode(), and LunaActorMultiVertex::LoadTexture().
PushSelf()
void ActorMultiVertex::PushSelf (lua_State * L) override virtual
Reimplemented from Actor.
RemoveQuadState()
void ActorMultiVertex::RemoveQuadState (size_t i) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::quad_states.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::RemoveQuadState().
RemoveState()
void ActorMultiVertex::RemoveState (size_t i) inline
References _states, and ASSERT.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::RemoveState().
SetAllStateDelays()
void ActorMultiVertex::SetAllStateDelays (float delay)
References _states, and FOREACH.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetAllStateDelays().
SetCurrentTweenStart()
void ActorMultiVertex::SetCurrentTweenStart () override virtual
Reimplemented from Actor.
References AMV_current, and AMV_start.
SetDrawState()
void ActorMultiVertex::SetDrawState (DrawMode dm, int first, int num) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::SetDrawState().
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetDrawState().
SetEffectMode()
void ActorMultiVertex::SetEffectMode (EffectMode em) inline
References _EffectMode.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetEffectMode().
SetLineWidth()
void ActorMultiVertex::SetLineWidth (float width) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::line_width.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetLineWidth().
SetNumVertices()
void ActorMultiVertex::SetNumVertices (size_t n)
References AMV_current, AMV_start, AMV_Tweens, and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetNumVertices().
SetQuadState()
void ActorMultiVertex::SetQuadState (size_t i, size_t s) inline
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::quad_states.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetQuadState().
SetSecondsIntoAnimation()
void ActorMultiVertex::SetSecondsIntoAnimation (float seconds) override virtual
Reimplemented from Actor.
References _secs_into_state, _Texture, RageTexture::SetPosition(), SetState(), and UpdateAnimationState().
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetSecondsIntoAnimation().
SetState()
void ActorMultiVertex::SetState (size_t i)
References _cur_state, _secs_into_state, _states, and ASSERT.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), SetSecondsIntoAnimation(), LunaActorMultiVertex::SetState(), and SetStateProperties().
SetStateData()
void ActorMultiVertex::SetStateData (size_t i, const State & s) inline
References _states, and ASSERT.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex().
SetStateProperties()
void ActorMultiVertex::SetStateProperties (const vector< State > & new_states) inline
References _states, and SetState().
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetStateProperties().
SetTexture()
void ActorMultiVertex::SetTexture (RageTexture * Texture)
References _Texture, and UnloadTexture().
Referenced by LoadFromTexture(), LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetTexture().
SetTextureMode()
void ActorMultiVertex::SetTextureMode (TextureMode tm) inline
References _TextureMode.
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetTextureMode().
SetVertexColor()
void ActorMultiVertex::SetVertexColor (int index, const RageColor & c)
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::SetVertexFromStack().
SetVertexCoords()
void ActorMultiVertex::SetVertexCoords (int index, float TexCoordX, float TexCoordY)
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::SetVertexFromStack().
SetVertexPos()
void ActorMultiVertex::SetVertexPos (int index, float x, float y, float z)
References AMV_DestTweenState(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::SetVertexFromStack().
SetVertsFromSplines()
void ActorMultiVertex::SetVertsFromSplines ()
References ActorMultiVertex::AMV_TweenState::_DrawMode, AMV_DestTweenState(), DrawMode_Fan, DrawMode_LineStrip, DrawMode_Quads, DrawMode_QuadStrip, DrawMode_Strip, DrawMode_SymmetricQuadStrip, DrawMode_Triangles, and SetVertsFromSplinesInternal().
Referenced by LunaActorMultiVertex::LunaActorMultiVertex(), and LunaActorMultiVertex::SetVertsFromSplines().
SetVertsFromSplinesInternal()
void ActorMultiVertex::SetVertsFromSplinesInternal (size_t num_splines, size_t start_vert) inline
References _splines, AMV_DestTweenState(), f, ActorMultiVertex::AMV_TweenState::FirstToDraw, ActorMultiVertex::AMV_TweenState::GetSafeNumToDraw(), and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by SetVertsFromSplines().
StopTweening()
void ActorMultiVertex::StopTweening () override virtual
Reimplemented from Actor.
References AMV_Tweens, and Actor::StopTweening().
UnloadTexture()
void ActorMultiVertex::UnloadTexture ()
References _Texture, TEXTUREMAN, and RageTextureManager::UnloadTexture().
Referenced by LunaActorMultiVertex::LoadTexture(), SetTexture(), and ~ActorMultiVertex().
Update()
void ActorMultiVertex::Update (float fDelta) override virtual
Reimplemented from Actor.
References _decode_movie, _secs_into_state, _skip_next_update, _Texture, RageTexture::DecodeSeconds(), GetAnimationLengthSeconds(), Actor::GetEffectDeltaTime(), Actor::m_bIsAnimating, max(), Actor::Update(), UpdateAnimationState(), and wrap().
UpdateAnimationState()
void ActorMultiVertex::UpdateAnimationState (bool force_update = false)
References _cur_state, ActorMultiVertex::AMV_TweenState::_DrawMode, _secs_into_state, _states, _use_animation_state, AMV_DestTweenState(), DrawMode_Fan, DrawMode_LineStrip, DrawMode_Quads, DrawMode_QuadStrip, DrawMode_Strip, DrawMode_SymmetricQuadStrip, DrawMode_Triangles, ActorMultiVertex::AMV_TweenState::FirstToDraw, ActorMultiVertex::AMV_TweenState::GetSafeNumToDraw(), min_state_delay, ActorMultiVertex::AMV_TweenState::NumToDraw, ActorMultiVertex::AMV_TweenState::quad_states, STATE_ID, and ActorMultiVertex::AMV_TweenState::vertices.
Referenced by LunaActorMultiVertex::ForceStateUpdate(), SetSecondsIntoAnimation(), and Update().
UpdatePercentThroughTween()
void ActorMultiVertex::UpdatePercentThroughTween (float PercentThroughTween) override virtual
Reimplemented from Actor.
References AMV_current, AMV_start, AMV_Tweens, and ActorMultiVertex::AMV_TweenState::MakeWeightedAverage().
Member Data Documentation
_cur_state
size_t ActorMultiVertex::_cur_state private
Referenced by ActorMultiVertex(), GetState(), SetState(), and UpdateAnimationState().
_decode_movie
bool ActorMultiVertex::_decode_movie
Referenced by ActorMultiVertex(), LunaActorMultiVertex::SetDecodeMovie(), and Update().
_EffectMode
EffectMode ActorMultiVertex::_EffectMode private
Referenced by ActorMultiVertex(), DrawInternal(), DrawPrimitives(), and SetEffectMode().
_secs_into_state
float ActorMultiVertex::_secs_into_state private
Referenced by ActorMultiVertex(), SetSecondsIntoAnimation(), SetState(), Update(), and UpdateAnimationState().
_skip_next_update
bool ActorMultiVertex::_skip_next_update private
Referenced by ActorMultiVertex(), EnableAnimation(), and Update().
_splines
vector<CubicSplineN> ActorMultiVertex::_splines private
Referenced by ActorMultiVertex(), GetSpline(), and SetVertsFromSplinesInternal().
_states
vector<State> ActorMultiVertex::_states private
Referenced by ActorMultiVertex(), AddState(), GetAnimationLengthSeconds(), GetNumStates(), GetStateData(), RemoveState(), SetAllStateDelays(), SetState(), SetStateData(), SetStateProperties(), and UpdateAnimationState().
_Texture
RageTexture* ActorMultiVertex::_Texture private
Referenced by ActorMultiVertex(), DrawPrimitives(), GetTexture(), LoadFromTexture(), SetSecondsIntoAnimation(), SetTexture(), UnloadTexture(), and Update().
_TextureMode
TextureMode ActorMultiVertex::_TextureMode private
Referenced by ActorMultiVertex(), DrawPrimitives(), and SetTextureMode().
_use_animation_state
bool ActorMultiVertex::_use_animation_state
Referenced by ActorMultiVertex(), LunaActorMultiVertex::SetUseAnimationState(), and UpdateAnimationState().
_Vertices
vector<RageSpriteVertex> ActorMultiVertex::_Vertices private
AMV_current
AMV_TweenState ActorMultiVertex::AMV_current private
Referenced by ActorMultiVertex(), AddVertex(), AddVertices(), AMV_DestTweenState(), BeginTweening(), DrawPrimitives(), EarlyAbortDraw(), EraseHeadTween(), FinishTweening(), GetCurrDrawMode(), GetCurrFirstToDraw(), GetCurrNumToDraw(), SetCurrentTweenStart(), SetNumVertices(), and UpdatePercentThroughTween().
AMV_start
AMV_TweenState ActorMultiVertex::AMV_start private
Referenced by ActorMultiVertex(), AddVertex(), AddVertices(), SetCurrentTweenStart(), SetNumVertices(), and UpdatePercentThroughTween().
AMV_TempState
AMV_TweenState* ActorMultiVertex::AMV_TempState private
Referenced by DrawPrimitives().
AMV_Tweens
vector<AMV_TweenState> ActorMultiVertex::AMV_Tweens private
Referenced by ActorMultiVertex(), AddVertex(), AddVertices(), AMV_DestTweenState(), BeginTweening(), EraseHeadTween(), FinishTweening(), SetNumVertices(), StopTweening(), and UpdatePercentThroughTween().
num_vert_splines
const size_t ActorMultiVertex::num_vert_splines = 4 static
Referenced by ActorMultiVertex(), GetSpline(), and LunaActorMultiVertex::GetSpline().
The documentation for this class was generated from the following files:
ActorMultiVertex.h
ActorMultiVertex.cpp