Etterna: TZip Class Reference
TZip Class Reference
Public Member Functions
TZip ()
~TZip ()=default
ZRESULT Start (RageFile *f)
unsigned int write (const char *buf, unsigned int size)
bool oseek (unsigned int pos)
ZRESULT Close ()
ZRESULT open_file (const TCHAR *fn)
ZRESULT open_dir ()
ZRESULT set_times ()
unsigned read (char *buf, unsigned size)
ZRESULT iclose ()
ZRESULT ideflate (TZipFileInfo *zfi)
ZRESULT istore ()
ZRESULT Add (const TCHAR *odstzn, const TCHAR *src, unsigned long flags)
ZRESULT AddCentral ()
Static Public Member Functions
static unsigned sflush (void *param, const char *buf, unsigned *size)
static unsigned swrite (void *param, const char *buf, unsigned size)
Public Attributes
RageFile * pfout
unsigned ooffset { 0 }
ZRESULT oerr { 0u }
unsigned writ { 0 }
unsigned int opos
unsigned int mapsize
bool hasputcen { false }
TZipFileInfo * zfis
ulg attr
iztimes times
ulg timestamp
long isize
long ired
ulg crc
RageFile * hfin { nullptr }
const char * bufin
unsigned int lenin
unsigned int posin
ulg csize
char buf [16384]
Constructor & Destructor Documentation
TZip()
TZip::TZip () inline
~TZip()
TZip::~TZip () default
Member Function Documentation
Add()
ZRESULT TZip::Add (const TCHAR * odstzn, const TCHAR * src, unsigned long flags)
References _tcscpy, _tcslen, iztimes::atime, zlist::att, attr, zlist::atx, BINARY, zlist::cext, zlist::cextra, zlist::com, zlist::comment, zlist::crc, crc, csize, iztimes::ctime, zlist::dosflag, zlist::dsk, EB_C_UT_SIZE, EB_L_UT_SIZE, EB_LEN, EB_UT_FL_ATIME, EB_UT_FL_CTIME, EB_UT_FL_MTIME, EB_UT_LEN, zlist::ext, zlist::extra, FAIL_M, zlist::flg, hasputcen, zlist::how, iclose(), zlist::iname, isize, istore(), L, zlist::len, zlist::lflg, LOCHEAD, zlist::mark, MAX_PATH, iztimes::mtime, zlist::nam, zlist::name, zlist::nxt, oerr, zlist::off, ooffset, open_dir(), open_file(), putextended(), putlocal(), zlist::siz, STORE, swrite(), zlist::tim, times, timestamp, zlist::vem, zlist::ver, writ, ZE_OK, zfis, ZIP_FILENAME, ZIP_FOLDER, zlist::zname, ZR_ARGS, ZR_ENDED, ZR_FAILED, ZR_NOCHANGE, ZR_OK, and ZR_WRITE.
Referenced by CreateZip::AddDir(), and CreateZip::AddFile().
AddCentral()
ZRESULT TZip::AddCentral ()
References CENHEAD, zlist::cextra, ENDHEAD, zlist::nxt, ooffset, putcentral(), putend(), swrite(), writ, ZE_OK, zfis, ZR_OK, and ZR_WRITE.
Referenced by Close().
Close()
ZRESULT TZip::Close ()
References AddCentral(), RageFile::Close(), hasputcen, pfout, and ZR_OK.
Referenced by CreateZip::Finish().
iclose()
ZRESULT TZip::iclose ()
References hfin, ired, isize, SAFE_DELETE, ZR_MISSIZE, and ZR_OK.
Referenced by Add().
ideflate()
ZRESULT TZip::ideflate (TZipFileInfo * zfi)
istore()
ZRESULT TZip::istore ()
References buf, csize, EOF, read(), write(), ZR_MISSIZE, and ZR_OK.
Referenced by Add().
open_dir()
ZRESULT TZip::open_dir ()
References attr, bufin, crc, CRCVAL_INITIAL, csize, hfin, ired, isize, set_times(), ZIP_ATTR_DIRECTORY, ZIP_ATTR_DIRECTORY2, ZIP_ATTR_READABLE, and ZIP_ATTR_WRITEABLE.
Referenced by Add().
open_file()
ZRESULT TZip::open_file (const TCHAR * fn)
References attr, bufin, crc, CRCVAL_INITIAL, csize, RageFile::GetFileSize(), hfin, ired, isize, RageFile::Open(), SAFE_DELETE, set_times(), ZIP_ATTR_NORMAL_FILE, ZIP_ATTR_READABLE, ZIP_ATTR_WRITEABLE, ZR_ARGS, and ZR_NOFILE.
Referenced by Add().
oseek()
bool TZip::oseek (unsigned int pos)
References oerr, and ZR_SEEK.
read()
unsigned TZip::read (char * buf, unsigned size)
References bufin, crc, crc32(), hfin, ired, lenin, oerr, posin, RageFile::Read(), and ZR_NOTINITED.
Referenced by istore().
set_times()
ZRESULT TZip::set_times ()
References iztimes::atime, iztimes::ctime, filetime2dosdatetime(), iztimes::mtime, times, timestamp, and ZR_OK.
Referenced by open_dir(), and open_file().
sflush()
unsigned TZip::sflush (void * param, const char * buf, unsigned * size) static
References writ.
Start()
ZRESULT TZip::Start (RageFile * f)
References f, hasputcen, oerr, ooffset, pfout, writ, ZR_NOTINITED, and ZR_OK.
Referenced by CreateZip::Start().
swrite()
unsigned TZip::swrite (void * param, const char * buf, unsigned size) static
References write().
Referenced by Add(), and AddCentral().
write()
unsigned int TZip::write (const char * buf, unsigned int size)
References buf, oerr, pfout, writ, RageFile::Write(), and ZR_NOTINITED.
Referenced by istore(), and swrite().
Member Data Documentation
attr
ulg TZip::attr
Referenced by Add(), open_dir(), and open_file().
buf
char TZip::buf[16384]
Referenced by istore(), and write().
bufin
const char* TZip::bufin
Referenced by open_dir(), open_file(), and read().
crc
ulg TZip::crc
Referenced by Add(), open_dir(), open_file(), and read().
csize
ulg TZip::csize
Referenced by Add(), istore(), open_dir(), and open_file().
hasputcen
bool TZip::hasputcen { false }
Referenced by Add(), Close(), and Start().
hfin
RageFile* TZip::hfin { nullptr }
Referenced by iclose(), open_dir(), open_file(), and read().
ired
long TZip::ired
Referenced by iclose(), open_dir(), open_file(), and read().
isize
long TZip::isize
Referenced by Add(), iclose(), open_dir(), and open_file().
lenin
unsigned int TZip::lenin
Referenced by read().
mapsize
unsigned int TZip::mapsize
oerr
ZRESULT TZip::oerr { 0u }
Referenced by Add(), oseek(), read(), Start(), and write().
ooffset
unsigned TZip::ooffset { 0 }
Referenced by Add(), AddCentral(), and Start().
opos
unsigned int TZip::opos
pfout
RageFile* TZip::pfout
Referenced by Close(), Start(), and write().
posin
unsigned int TZip::posin
Referenced by read().
times
iztimes TZip::times
Referenced by Add(), and set_times().
timestamp
ulg TZip::timestamp
Referenced by Add(), and set_times().
writ
unsigned TZip::writ { 0 }
Referenced by Add(), AddCentral(), sflush(), Start(), and write().
zfis
TZipFileInfo* TZip::zfis
Initial value:
{
        nullptr
    }
Referenced by Add(), and AddCentral().
The documentation for this class was generated from the following file:
CreateZip.cpp