Etterna: NotesWriterDWI Namespace Reference
NotesWriterDWI Namespace Reference
Writes a Song to a .DWI file.
Functions
bool Write (const RString &sPath, const Song &out)
Write the song out to a file.
Detailed Description
Writes a Song to a .DWI file.
Function Documentation
Write()
bool NotesWriterDWI::Write (const RString & sPath, const Song & out)
Write the song out to a file.
Parameters
sPath the path to write the file.
out the Song to be written out.
Returns
its success or failure.
References ASSERT_M, DISPLAY_BPM_ACTUAL, DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, DwiEscape(), f, Song::GetAllSteps(), BPMSegment::GetBPM(), RageFile::GetError(), StopSegment::GetPause(), TimingSegment::GetRow(), TimingData::GetTimingSegments(), Song::GetTranslitArtist(), Song::GetTranslitFullTitle(), LOG, Song::m_DisplayBPMType, TimingData::m_fBeat0OffsetInSeconds, Song::m_fMusicSampleLengthSeconds, Song::m_fMusicSampleStartSeconds, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, Song::m_sCDTitleFile, Song::m_sMusicFile, Song::m_SongTiming, Steps::m_StepsType, RageFile::Open(), RageFile::PutLine(), ROWS_PER_BEAT, SEGMENT_BPM, SEGMENT_STOP, ssprintf(), StepsType_dance_couple, StepsType_dance_double, RageLog::UserLog(), RageFile::WRITE, RageFile::Write(), WriteDWINotesField(), and WriteDWINotesTag().
Referenced by Song::SaveToDWIFile().