Etterna: LunaNoteField Class Reference
LunaNoteField Class Reference
Allow Lua to have access to the Notefield.
Public Member Functions
SET_CALLBACK_GENERIC (set_step_callback, m_StepCallback)
SET_CALLBACK_GENERIC (set_set_pressed_callback, m_SetPressedCallback)
SET_CALLBACK_GENERIC (set_did_tap_note_callback, m_DidTapNoteCallback)
SET_CALLBACK_GENERIC (set_did_hold_note_callback, m_DidHoldNoteCallback)
LunaNoteField ()
Public Member Functions inherited from Luna< NoteField >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int check_column (lua_State *L, int index, PlayerNumber pn)
static int step (T *p, lua_State *L)
static int set_pressed (T *p, lua_State *L)
static int did_tap_note (T *p, lua_State *L)
static int did_hold_note (T *p, lua_State *L)
static int get_column_actors (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< NoteField >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< NoteField >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< NoteField >
using T = NoteField
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< NoteField >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Notefield.
Constructor & Destructor Documentation
LunaNoteField()
LunaNoteField::LunaNoteField () inline
References ADD_METHOD, did_hold_note(), did_tap_note(), get_column_actors(), set_pressed(), and step().
Member Function Documentation
check_column()
static int LunaNoteField::check_column (lua_State * L, int index, PlayerNumber pn) inline static
References GAMESTATE, GameState::GetCurrentStyle(), IArg, and Style::m_iColsPerPlayer.
Referenced by did_hold_note(), did_tap_note(), set_pressed(), and step().
did_hold_note()
static int LunaNoteField::did_hold_note (T * p, lua_State * L) inline static
References BArg, check_column(), NoteField::DidHoldNote(), NoteField::GetPlayerState(), L, and PlayerState::m_PlayerNumber.
Referenced by LunaNoteField().
did_tap_note()
static int LunaNoteField::did_tap_note (T * p, lua_State * L) inline static
References BArg, check_column(), NoteField::DidTapNote(), NoteField::GetPlayerState(), L, and PlayerState::m_PlayerNumber.
Referenced by LunaNoteField().
get_column_actors()
static int LunaNoteField::get_column_actors (T * p, lua_State * L) inline static
References NoteField::m_ColumnRenderers.
Referenced by LunaNoteField().
SET_CALLBACK_GENERIC() [1/4]
LunaNoteField::SET_CALLBACK_GENERIC (set_step_callback , m_StepCallback)
SET_CALLBACK_GENERIC() [2/4]
LunaNoteField::SET_CALLBACK_GENERIC (set_set_pressed_callback , m_SetPressedCallback)
SET_CALLBACK_GENERIC() [3/4]
LunaNoteField::SET_CALLBACK_GENERIC (set_did_tap_note_callback , m_DidTapNoteCallback)
SET_CALLBACK_GENERIC() [4/4]
LunaNoteField::SET_CALLBACK_GENERIC (set_did_hold_note_callback , m_DidHoldNoteCallback)
set_pressed()
static int LunaNoteField::set_pressed (T * p, lua_State * L) inline static
References check_column(), NoteField::GetPlayerState(), PlayerState::m_PlayerNumber, and NoteField::SetPressed().
Referenced by LunaNoteField().
step()
static int LunaNoteField::step (T * p, lua_State * L) inline static
References check_column(), NoteField::GetPlayerState(), L, PlayerState::m_PlayerNumber, and NoteField::Step().
Referenced by LunaNoteField().
The documentation for this class was generated from the following file:
NoteField.cpp