Etterna: ArchHooks_MacOSX Class Reference
ArchHooks_MacOSX Class Reference
#include <ArchHooks_MacOSX.h>
Public Member Functions
void Init ()
RString GetArchName () const
void DumpDebugInfo ()
RString GetPreferredLanguage ()
bool GoToURL (const RString &sUrl)
float GetDisplayAspectRatio ()
Public Member Functions inherited from ArchHooks
ArchHooks ()
virtual ~ArchHooks ()=default
virtual void RestartProgram ()
Re-exec the game.
virtual bool CheckForMultipleInstances (int, char *[])
virtual void SetTime (tm)
virtual void BoostPriority ()
virtual void UnBoostPriority ()
virtual void SetupConcurrentRenderingThread ()
Setup the rendering threads for concurrency.
void SetHasFocus (bool bAppHasFocus)
bool AppHasFocus () const
bool AppFocusChanged ()
virtual RString GetClipboard ()
Fetch the contents of the system clipboard.
virtual int GetWindowWidth ()
Fetch the window width.
virtual int GetWindowHeight ()
Fetch the window height.
void PushSelf (lua_State *L)
void RegisterWithLua ()
Additional Inherited Members
Static Public Member Functions inherited from ArchHooks
static ArchHooks * Create ()
static RString GetPreferredLanguage ()
static bool UserQuit ()
Determine if the user wants to quit (eg. ^C, or clicked a "close window" button).
static void SetUserQuit ()
static bool GetAndClearToggleWindowed ()
static void SetToggleWindowed ()
static int64_t GetMicrosecondsSinceStart (bool bAccurate)
static void MountInitialFilesystems (const RString &sDirOfExecutable)
static void MountUserFilesystems (const RString &sDirOfExecutable)
Member Function Documentation
DumpDebugInfo()
void ArchHooks_MacOSX::DumpDebugInfo () virtual
Reimplemented from ArchHooks.
References GET_PARAM, RageLog::Info(), LOG, and ssprintf().
GetArchName()
RString ArchHooks_MacOSX::GetArchName () const virtual
Reimplemented from ArchHooks.
GetDisplayAspectRatio()
float ArchHooks_MacOSX::GetDisplayAspectRatio () virtual
Implements ArchHooks.
References GetIntValue().
GetPreferredLanguage()
RString ArchHooks_MacOSX::GetPreferredLanguage ()
GoToURL()
bool ArchHooks_MacOSX::GoToURL (const RString & sUrl) virtual
Reimplemented from ArchHooks.
Init()
void ArchHooks_MacOSX::Init () virtual
Reimplemented from ArchHooks.
References DoCleanShutdown(), DoCrashSignalHandler(), DoEmergencyShutdown(), g_argc, g_argv, LOG, and RageLog::Warn().
The documentation for this class was generated from the following files:
ArchHooks_MacOSX.h
ArchHooks_MacOSX.mm