Etterna: NoteData::_all_tracks_iterator< ND, iter, TN > Class Template Reference
NoteData::_all_tracks_iterator< ND, iter, TN > Class Template Reference
#include <NoteData.h>
Public Member Functions
_all_tracks_iterator (ND &nd, int iStartRow, int iEndRow, bool bReverse, bool bInclusive)
_all_tracks_iterator (const _all_tracks_iterator &other)
~_all_tracks_iterator ()
_all_tracks_iterator & operator++ ()
_all_tracks_iterator operator++ (int dummy)
int Track () const
int Row () const
bool IsAtEnd () const
iter GetIter (int iTrack) const
TN & operator* ()
TN * operator-> ()
const TN & operator* () const
const TN * operator-> () const
void Revalidate (ND *notedata, vector< int > const &added_or_removed_tracks, bool added)
Private Member Functions
void Find (bool bReverse)
Private Attributes
ND * m_pNoteData
vector< iter > m_vBeginIters
vector< iter > m_vCurrentIters
vector< iter > m_vEndIters
int m_iTrack
bool m_bReverse
vector< int > m_PrevCurrentRows
bool m_Inclusive
int m_StartRow
int m_EndRow
Constructor & Destructor Documentation
_all_tracks_iterator() [1/2]
template<typename ND , typename iter , typename TN > NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator (ND & nd, int iStartRow, int iEndRow, bool bReverse, bool bInclusive)
References ASSERT, NoteData::begin(), NoteData::end(), NoteData::_all_tracks_iterator< ND, iter, TN >::Find(), NoteData::_all_tracks_iterator< ND, iter, TN >::m_bReverse, NoteData::_all_tracks_iterator< ND, iter, TN >::m_EndRow, NoteData::_all_tracks_iterator< ND, iter, TN >::m_Inclusive, NoteData::_all_tracks_iterator< ND, iter, TN >::m_pNoteData, NoteData::_all_tracks_iterator< ND, iter, TN >::m_PrevCurrentRows, NoteData::_all_tracks_iterator< ND, iter, TN >::m_StartRow, NoteData::_all_tracks_iterator< ND, iter, TN >::m_vBeginIters, NoteData::_all_tracks_iterator< ND, iter, TN >::m_vCurrentIters, and NoteData::_all_tracks_iterator< ND, iter, TN >::m_vEndIters.
_all_tracks_iterator() [2/2]
template<typename ND , typename iter , typename TN > NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator (const _all_tracks_iterator< ND, iter, TN > & other)
References NoteData::_all_tracks_iterator< ND, iter, TN >::m_pNoteData.
~_all_tracks_iterator()
template<typename ND , typename iter , typename TN > NoteData::_all_tracks_iterator< ND, iter, TN >::~_all_tracks_iterator ()
Member Function Documentation
Find()
template<typename ND , typename iter , typename TN > void NoteData::_all_tracks_iterator< ND, iter, TN >::Find (bool bReverse) private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
GetIter()
template<typename ND, typename iter, typename TN> iter NoteData::_all_tracks_iterator< ND, iter, TN >::GetIter (int iTrack) const inline
IsAtEnd()
template<typename ND, typename iter, typename TN> bool NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd () const inline
Referenced by NoteDataUtil::CalculateRadarValues(), NoteData::CreateNode(), Player::CrossedRows(), GenerateCacheDataStructure(), NoteDataWithScoring::GetActualRadarValues(), Player::GetClosestNonEmptyRowDirectional(), NoteData::_all_tracks_iterator< ND, iter, TN >::operator*(), NoteData::_all_tracks_iterator< ND, iter, TN >::operator->(), Player::Update(), Player::UpdateJudgedRows(), and Player::UpdateTapNotesMissedOlderThan().
operator*() [1/2]
template<typename ND, typename iter, typename TN> TN& NoteData::_all_tracks_iterator< ND, iter, TN >::operator* () inline
References DEBUG_ASSERT, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), and NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
operator*() [2/2]
template<typename ND, typename iter, typename TN> const TN& NoteData::_all_tracks_iterator< ND, iter, TN >::operator* () const inline
References DEBUG_ASSERT, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), and NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
operator++() [1/2]
template<typename ND , typename iter , typename TN > NoteData::_all_tracks_iterator< ND, iter, TN > & NoteData::_all_tracks_iterator< ND, iter, TN >::operator++ ()
operator++() [2/2]
template<typename ND , typename iter , typename TN > NoteData::_all_tracks_iterator< ND, iter, TN > NoteData::_all_tracks_iterator< ND, iter, TN >::operator++ (int dummy)
operator->() [1/2]
template<typename ND, typename iter, typename TN> TN* NoteData::_all_tracks_iterator< ND, iter, TN >::operator-> () inline
References DEBUG_ASSERT, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), and NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
operator->() [2/2]
template<typename ND, typename iter, typename TN> const TN* NoteData::_all_tracks_iterator< ND, iter, TN >::operator-> () const inline
References DEBUG_ASSERT, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), and NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
Revalidate()
template<typename ND , typename iter , typename TN > void NoteData::_all_tracks_iterator< ND, iter, TN >::Revalidate (ND * notedata, vector< int > const & added_or_removed_tracks, bool added)
References ASSERT, NoteData::begin(), and NoteData::end().
Row()
template<typename ND, typename iter, typename TN> int NoteData::_all_tracks_iterator< ND, iter, TN >::Row () const inline
References NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
Referenced by NoteDataUtil::CalculateRadarValues(), NoteData::CreateNode(), Player::CrossedRows(), GenerateCacheDataStructure(), NoteDataWithScoring::GetActualRadarValues(), Player::GetClosestNonEmptyRowDirectional(), Player::Update(), Player::UpdateJudgedRows(), and Player::UpdateTapNotesMissedOlderThan().
Track()
template<typename ND, typename iter, typename TN> int NoteData::_all_tracks_iterator< ND, iter, TN >::Track () const inline
References NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack.
Referenced by NoteData::CreateNode(), Player::CrossedRows(), Player::Update(), Player::UpdateJudgedRows(), and Player::UpdateTapNotesMissedOlderThan().
Member Data Documentation
m_bReverse
template<typename ND, typename iter, typename TN> bool NoteData::_all_tracks_iterator< ND, iter, TN >::m_bReverse private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_EndRow
template<typename ND, typename iter, typename TN> int NoteData::_all_tracks_iterator< ND, iter, TN >::m_EndRow private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_Inclusive
template<typename ND, typename iter, typename TN> bool NoteData::_all_tracks_iterator< ND, iter, TN >::m_Inclusive private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_iTrack
template<typename ND, typename iter, typename TN> int NoteData::_all_tracks_iterator< ND, iter, TN >::m_iTrack private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::operator*(), NoteData::_all_tracks_iterator< ND, iter, TN >::operator->(), NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), and NoteData::_all_tracks_iterator< ND, iter, TN >::Track().
m_pNoteData
template<typename ND, typename iter, typename TN> ND* NoteData::_all_tracks_iterator< ND, iter, TN >::m_pNoteData private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_PrevCurrentRows
template<typename ND, typename iter, typename TN> vector<int> NoteData::_all_tracks_iterator< ND, iter, TN >::m_PrevCurrentRows private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_StartRow
template<typename ND, typename iter, typename TN> int NoteData::_all_tracks_iterator< ND, iter, TN >::m_StartRow private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_vBeginIters
template<typename ND, typename iter, typename TN> vector<iter> NoteData::_all_tracks_iterator< ND, iter, TN >::m_vBeginIters private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_vCurrentIters
template<typename ND, typename iter, typename TN> vector<iter> NoteData::_all_tracks_iterator< ND, iter, TN >::m_vCurrentIters private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
m_vEndIters
template<typename ND, typename iter, typename TN> vector<iter> NoteData::_all_tracks_iterator< ND, iter, TN >::m_vEndIters private
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator().
The documentation for this class was generated from the following files:
NoteData.h
NoteData.cpp