Etterna: DateTime.cpp File Reference
DateTime.cpp File Reference
#include "DateTime.h"
#include "EnumHelper.h"
#include "LocalizedString.h"
#include "LuaManager.h"
#include "RageUtil.h"
#include "global.h"
Macros
#define COMPARE(v)
#define COMPARE(x)
#define COMPARE(v)
#define COPY_M(v) dtNow.v = tNow.v;
Functions
RString DayInYearToString (int iDayInYear)
int StringToDayInYear (const RString &sDayInYear)
RString LastDayToString (int iLastDayIndex)
RString DayOfWeekToString (int iDayOfWeekIndex)
RString HourInDayToString (int iHourInDayIndex)
XToString (Month)
XToLocalizedString (Month)
LuaXType (Month)
RString LastWeekToString (int iLastWeekIndex)
RString LastDayToLocalizedString (int iLastDayIndex)
RString LastWeekToLocalizedString (int iLastWeekIndex)
RString HourInDayToLocalizedString (int iHourIndex)
tm AddDays (tm start, int iDaysToMove)
tm GetYesterday (tm start)
int GetDayOfWeek (tm time)
tm GetNextSunday (tm start)
tm GetDayInYearAndYear (int iDayInYearIndex, int iYear)
LuaFunction (MonthToString, MonthToString(Enum::Check< Month >(L, 1)))
LuaFunction (MonthToLocalizedString, MonthToLocalizedString(Enum::Check< Month >(L, 1)))
LuaFunction (MonthOfYear, GetLocalTime().tm_mon)
LuaFunction (DayOfMonth, GetLocalTime().tm_mday)
LuaFunction (Hour, GetLocalTime().tm_hour)
LuaFunction (Minute, GetLocalTime().tm_min)
LuaFunction (Second, GetLocalTime().tm_sec)
LuaFunction (Year, GetLocalTime().tm_year+1900)
LuaFunction (Weekday, GetLocalTime().tm_wday)
LuaFunction (DayOfYear, GetLocalTime().tm_yday)
Variables
static const RString LAST_DAYS_NAME [NUM_LAST_DAYS]
static const char * DAY_OF_WEEK_TO_NAME [DAYS_IN_WEEK]
static const char * MonthNames []
Macro Definition Documentation
COMPARE [1/3]
#define COMPARE (v)
Value:
if ((v) != other.v)                                                        \
        return (v) < other.v;
Referenced by DateTime::operator<(), DateTime::operator==(), and DateTime::operator>().
COMPARE [2/3]
#define COMPARE (x)
Value:
if ((x) != other.x)                                                        \
        return false;
COMPARE [3/3]
#define COMPARE (v)
Value:
if ((v) != other.v)                                                        \
        return (v) > other.v;
COPY_M
#define COPY_M (v) dtNow.v = tNow.v;
Referenced by DateTime::GetNowDateTime().
Function Documentation
AddDays()
tm AddDays (tm start, int iDaysToMove)
Referenced by GetNextSunday(), and GetYesterday().
DayInYearToString()
RString DayInYearToString (int iDayInYear)
References ssprintf().
DayOfWeekToString()
RString DayOfWeekToString (int iDayOfWeekIndex)
References DAY_OF_WEEK_TO_NAME.
GetDayInYearAndYear()
tm GetDayInYearAndYear (int iDayInYearIndex, int iYear)
References ZERO.
GetDayOfWeek()
int GetDayOfWeek (tm time)
References ASSERT, and DAYS_IN_WEEK.
Referenced by GetNextSunday().
GetNextSunday()
tm GetNextSunday (tm start)
References AddDays(), DAYS_IN_WEEK, and GetDayOfWeek().
GetYesterday()
tm GetYesterday (tm start)
References AddDays().
HourInDayToLocalizedString()
RString HourInDayToLocalizedString (int iHourIndex)
References ssprintf(), and wrap().
HourInDayToString()
RString HourInDayToString (int iHourInDayIndex)
References ssprintf().
LastDayToLocalizedString()
RString LastDayToLocalizedString (int iLastDayIndex)
References LastDayToString(), and StdString::CStdStr< CT >::Replace().
LastDayToString()
RString LastDayToString (int iLastDayIndex)
Referenced by LastDayToLocalizedString().
LastWeekToLocalizedString()
RString LastWeekToLocalizedString (int iLastWeekIndex)
References LastWeekToString(), and StdString::CStdStr< CT >::Replace().
LastWeekToString()
RString LastWeekToString (int iLastWeekIndex)
References ssprintf().
Referenced by LastWeekToLocalizedString().
LuaFunction() [1/10]
LuaFunction (MonthToString , MonthToString(Enum::Check< Month >(L, 1)))
LuaFunction() [2/10]
LuaFunction (MonthToLocalizedString , MonthToLocalizedString(Enum::Check< Month >(L, 1)))
LuaFunction() [3/10]
LuaFunction (MonthOfYear , GetLocalTime(). tm_mon)
LuaFunction() [4/10]
LuaFunction (DayOfMonth , GetLocalTime(). tm_mday)
LuaFunction() [5/10]
LuaFunction (Hour , GetLocalTime(). tm_hour)
LuaFunction() [6/10]
LuaFunction (Minute , GetLocalTime(). tm_min)
LuaFunction() [7/10]
LuaFunction (Second , GetLocalTime(). tm_sec)
LuaFunction() [8/10]
LuaFunction (Year , GetLocalTime().tm_year+ 1900)
LuaFunction() [9/10]
LuaFunction (Weekday , GetLocalTime(). tm_wday)
LuaFunction() [10/10]
LuaFunction (DayOfYear , GetLocalTime(). tm_yday)
LuaXType()
LuaXType (Month)
StringToDayInYear()
int StringToDayInYear (const RString & sDayInYear)
XToLocalizedString()
XToLocalizedString (Month)
XToString()
XToString (Month)
Variable Documentation
DAY_OF_WEEK_TO_NAME
const char* DAY_OF_WEEK_TO_NAME[DAYS_IN_WEEK] static
Initial value:
= {
    "Sunday",   "Monday", "Tuesday",  "Wednesday",
    "Thursday", "Friday", "Saturday",
}
Referenced by DayOfWeekToString().
LAST_DAYS_NAME
const RString LAST_DAYS_NAME[NUM_LAST_DAYS] static
Initial value:
= {
    "Today", "Yesterday", "Day2Ago", "Day3Ago", "Day4Ago", "Day5Ago", "Day6Ago",
}
MonthNames
const char* MonthNames[] static
Initial value:
= {
    "January", "February", "March",     "April",   "May",     "June",
    "July", "August",   "September", "October", "November", "December",
}