Etterna: NotesLoaderSM.cpp File Reference
NotesLoaderSM.cpp File Reference
#include "global.h"
#include "NotesLoaderSM.h"
#include "BackgroundUtil.h"
#include "GameManager.h"
#include "MsdFile.h"
#include "NoteTypes.h"
#include "PrefsManager.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "Song.h"
#include "SongManager.h"
#include "Steps.h"
Classes
struct SMSongTagInfo
struct sm_parser_helper_t
Typedefs
using song_tag_func_t = void(*)(SMSongTagInfo &)
typedef std::map< RString, song_tag_func_t > song_handler_map_t
Functions
void SMSetTitle (SMSongTagInfo &info)
void SMSetSubtitle (SMSongTagInfo &info)
void SMSetArtist (SMSongTagInfo &info)
void SMSetTitleTranslit (SMSongTagInfo &info)
void SMSetSubtitleTranslit (SMSongTagInfo &info)
void SMSetArtistTranslit (SMSongTagInfo &info)
void SMSetGenre (SMSongTagInfo &info)
void SMSetCredit (SMSongTagInfo &info)
void SMSetBanner (SMSongTagInfo &info)
void SMSetBackground (SMSongTagInfo &info)
void SMSetLyricsPath (SMSongTagInfo &info)
void SMSetCDTitle (SMSongTagInfo &info)
void SMSetMusic (SMSongTagInfo &info)
void SMSetOffset (SMSongTagInfo &info)
void SMSetBPMs (SMSongTagInfo &info)
void SMSetStops (SMSongTagInfo &info)
void SMSetDelays (SMSongTagInfo &info)
void SMSetTimeSignatures (SMSongTagInfo &info)
void SMSetTickCounts (SMSongTagInfo &info)
void SMSetInstrumentTrack (SMSongTagInfo &info)
void SMSetSampleStart (SMSongTagInfo &info)
void SMSetSampleLength (SMSongTagInfo &info)
void SMSetDisplayBPM (SMSongTagInfo &info)
void SMSetSelectable (SMSongTagInfo &info)
void SMSetBGChanges (SMSongTagInfo &info)
void SMSetFGChanges (SMSongTagInfo &info)
void SMSetKeysounds (SMSongTagInfo &info)
Variables
sm_parser_helper_t sm_parser_helper
Typedef Documentation
song_handler_map_t
typedef std::map<RString, song_tag_func_t> song_handler_map_t
song_tag_func_t
using song_tag_func_t = void (*)(SMSongTagInfo&)
Function Documentation
SMSetArtist()
void SMSetArtist (SMSongTagInfo & info)
References Song::m_sArtist, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetArtistTranslit()
void SMSetArtistTranslit (SMSongTagInfo & info)
References Song::m_sArtistTranslit, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetBackground()
void SMSetBackground (SMSongTagInfo & info)
References Song::m_sBackgroundFile, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetBanner()
void SMSetBanner (SMSongTagInfo & info)
References Song::m_sBannerFile, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetBGChanges()
void SMSetBGChanges (SMSongTagInfo & info)
References SMSongTagInfo::loader, SMSongTagInfo::params, SMSongTagInfo::path, SMLoader::ProcessBGChanges(), and SMSongTagInfo::song.
Referenced by SMLoader::LoadFromSimfile(), and sm_parser_helper_t::sm_parser_helper_t().
SMSetBPMs()
void SMSetBPMs (SMSongTagInfo & info)
References SMSongTagInfo::BPMChanges, SMSongTagInfo::loader, SMSongTagInfo::params, and SMLoader::ParseBPMs().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetCDTitle()
void SMSetCDTitle (SMSongTagInfo & info)
References Song::m_sCDTitleFile, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetCredit()
void SMSetCredit (SMSongTagInfo & info)
References Song::m_sCredit, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetDelays()
void SMSetDelays (SMSongTagInfo & info)
References SMSongTagInfo::loader, Song::m_SongTiming, SMSongTagInfo::params, SMLoader::ProcessDelays(), and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetDisplayBPM()
void SMSetDisplayBPM (SMSongTagInfo & info)
References DISPLAY_BPM_RANDOM, DISPLAY_BPM_SPECIFIED, Song::m_DisplayBPMType, Song::m_fSpecifiedBPMMax, Song::m_fSpecifiedBPMMin, SMSongTagInfo::params, SMSongTagInfo::song, and StringToFloat().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetFGChanges()
void SMSetFGChanges (SMSongTagInfo & info)
References Song::AddForegroundChange(), SMSongTagInfo::loader, SMLoader::LoadFromBGChangesString(), SMSongTagInfo::params, SMSongTagInfo::song, and split().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetGenre()
void SMSetGenre (SMSongTagInfo & info)
References Song::m_sGenre, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetInstrumentTrack()
void SMSetInstrumentTrack (SMSongTagInfo & info)
References SMSongTagInfo::loader, SMSongTagInfo::params, SMLoader::ProcessInstrumentTracks(), and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetKeysounds()
void SMSetKeysounds (SMSongTagInfo & info)
References Song::m_vsKeysoundFile, SMSongTagInfo::params, SMSongTagInfo::song, and split().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetLyricsPath()
void SMSetLyricsPath (SMSongTagInfo & info)
References Song::m_sLyricsFile, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetMusic()
void SMSetMusic (SMSongTagInfo & info)
References Song::m_sMusicFile, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetOffset()
void SMSetOffset (SMSongTagInfo & info)
References TimingData::m_fBeat0OffsetInSeconds, Song::m_SongTiming, SMSongTagInfo::params, SMSongTagInfo::song, and StringToFloat().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetSampleLength()
void SMSetSampleLength (SMSongTagInfo & info)
References HHMMSSToSeconds(), Song::m_fMusicSampleLengthSeconds, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetSampleStart()
void SMSetSampleStart (SMSongTagInfo & info)
References HHMMSSToSeconds(), Song::m_fMusicSampleStartSeconds, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetSelectable()
void SMSetSelectable (SMSongTagInfo & info)
References EqualsNoCase(), LOG, Song::m_SelectionDisplay, SMSongTagInfo::params, SMSongTagInfo::path, Song::SHOW_ALWAYS, Song::SHOW_NEVER, SMSongTagInfo::song, StringToInt(), and RageLog::UserLog().
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetStops()
void SMSetStops (SMSongTagInfo & info)
References SMSongTagInfo::loader, SMSongTagInfo::params, SMLoader::ParseStops(), and SMSongTagInfo::Stops.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetSubtitle()
void SMSetSubtitle (SMSongTagInfo & info)
References Song::m_sSubTitle, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetSubtitleTranslit()
void SMSetSubtitleTranslit (SMSongTagInfo & info)
References Song::m_sSubTitleTranslit, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetTickCounts()
void SMSetTickCounts (SMSongTagInfo & info)
References SMSongTagInfo::loader, Song::m_SongTiming, SMSongTagInfo::params, SMLoader::ProcessTickcounts(), and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetTimeSignatures()
void SMSetTimeSignatures (SMSongTagInfo & info)
References SMSongTagInfo::loader, Song::m_SongTiming, SMSongTagInfo::params, SMLoader::ProcessTimeSignatures(), and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetTitle()
void SMSetTitle (SMSongTagInfo & info)
References SMSongTagInfo::loader, Song::m_sMainTitle, SMSongTagInfo::params, SMLoader::SetSongTitle(), and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
SMSetTitleTranslit()
void SMSetTitleTranslit (SMSongTagInfo & info)
References Song::m_sMainTitleTranslit, SMSongTagInfo::params, and SMSongTagInfo::song.
Referenced by sm_parser_helper_t::sm_parser_helper_t().
Variable Documentation
sm_parser_helper
sm_parser_helper_t sm_parser_helper