Etterna: RageFileObjDirect Class Reference
RageFileObjDirect Class Reference
This driver handles direct file access.
#include <RageFileDriverDirect.h>
Public Member Functions
RageFileObjDirect (const RString &sPath, int iFD, int iMode)
~RageFileObjDirect () override
int ReadInternal (void *pBuffer, size_t iBytes) override
int WriteInternal (const void *pBuffer, size_t iBytes) override
int FlushInternal () override
int SeekInternal (int offset) override
RageFileObjDirect * Copy () const override
RString GetDisplayPath () const override
int GetFileSize () const override
int GetFD () override
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Private Member Functions
bool FinalFlush ()
bool WriteFailed () const
RageFileObjDirect & operator= (const RageFileObjDirect &rhs)=delete
RageFileObjDirect (const RageFileObjDirect &rhs)=delete
Private Attributes
int m_iFD
int m_iMode
RString m_sPath
bool m_bWriteFailed
Additional Inherited Members
Protected Member Functions inherited from RageFileObj
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObj
RString m_sError
Detailed Description
This driver handles direct file access.
Constructor & Destructor Documentation
RageFileObjDirect() [1/2]
RageFileObjDirect::RageFileObjDirect (const RString & sPath, int iFD, int iMode)
References ASSERT, BUFSIZE, RageFileObj::EnableWriteBuffering(), m_bWriteFailed, m_iFD, m_iMode, m_sPath, and RageFile::WRITE.
~RageFileObjDirect()
RageFileObjDirect::~RageFileObjDirect () override
References Dirname(), DoPathReplace(), DoRemove, FinalFlush(), m_iFD, m_iMode, m_sPath, MakeTempFilename(), RageFileObj::SetError(), RageFile::SLOW_FLUSH, ssprintf(), RageFile::STREAMED, WARN, RageFile::WRITE, and WriteFailed().
RageFileObjDirect() [2/2]
RageFileObjDirect::RageFileObjDirect (const RageFileObjDirect & rhs) private delete
Member Function Documentation
Copy()
RageFileObjDirect * RageFileObjDirect::Copy () const override virtual
Reimplemented from RageFileObj.
References m_iFD, m_iMode, m_sPath, MakeFileObjDirect(), RageFileObj::Seek(), and RageException::Throw().
FinalFlush()
bool RageFileObjDirect::FinalFlush () private
References Dirname(), RageFileObj::Flush(), m_iFD, m_iMode, m_sPath, RageFileObj::SetError(), RageFile::SLOW_FLUSH, ssprintf(), WARN, and RageFile::WRITE.
Referenced by ~RageFileObjDirect().
FlushInternal()
int RageFileObjDirect::FlushInternal () override virtual
Reimplemented from RageFileObj.
References RageFileObj::SetError(), and WriteFailed().
GetDisplayPath()
RString RageFileObjDirect::GetDisplayPath () const inline override virtual
Reimplemented from RageFileObj.
References m_sPath.
GetFD()
int RageFileObjDirect::GetFD () override virtual
Reimplemented from RageFileObj.
References m_iFD.
GetFileSize()
int RageFileObjDirect::GetFileSize () const override virtual
Implements RageFileObj.
References ASSERT_M, m_iFD, m_sPath, and ssprintf().
operator=()
RageFileObjDirect& RageFileObjDirect::operator= (const RageFileObjDirect & rhs) private delete
ReadInternal()
int RageFileObjDirect::ReadInternal (void * pBuffer, size_t iBytes) override virtual
Implements RageFileObj.
References m_iFD, and RageFileObj::SetError().
SeekInternal()
int RageFileObjDirect::SeekInternal (int offset) override virtual
Reimplemented from RageFileObj.
References m_iFD.
WriteFailed()
bool RageFileObjDirect::WriteFailed () const inline private
References m_bWriteFailed, and RageFile::STREAMED.
Referenced by FlushInternal(), WriteInternal(), and ~RageFileObjDirect().
WriteInternal()
int RageFileObjDirect::WriteInternal (const void * pBuffer, size_t iBytes) override virtual
Implements RageFileObj.
References m_bWriteFailed, m_iFD, RetriedWrite(), RageFileObj::SetError(), and WriteFailed().
Member Data Documentation
m_bWriteFailed
bool RageFileObjDirect::m_bWriteFailed private
Referenced by RageFileObjDirect(), WriteFailed(), and WriteInternal().
m_iFD
int RageFileObjDirect::m_iFD private
Referenced by Copy(), FinalFlush(), GetFD(), GetFileSize(), RageFileObjDirect(), ReadInternal(), SeekInternal(), WriteInternal(), and ~RageFileObjDirect().
m_iMode
int RageFileObjDirect::m_iMode private
Referenced by Copy(), FinalFlush(), RageFileObjDirect(), and ~RageFileObjDirect().
m_sPath
RString RageFileObjDirect::m_sPath private
Referenced by Copy(), FinalFlush(), GetDisplayPath(), GetFileSize(), RageFileObjDirect(), and ~RageFileObjDirect().
The documentation for this class was generated from the following files:
RageFileDriverDirect.h
RageFileDriverDirect.cpp