Etterna: ScreenHowToPlay.cpp File Reference
ScreenHowToPlay.cpp File Reference
#include "ScreenHowToPlay.h"
#include "Character.h"
#include "CharacterManager.h"
#include "GameManager.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "LifeMeterBar.h"
#include "Model.h"
#include "NotesLoaderSM.h"
#include "NotesLoaderSSC.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "RageDisplay.h"
#include "SongUtil.h"
#include "StatsManager.h"
#include "Steps.h"
#include "Style.h"
#include "ThemeManager.h"
#include "ThemeMetric.h"
#include "global.h"
#include "LuaBinding.h"
Classes
class LunaScreenHowToPlay
Allow Lua to have access to the ScreenHowToPlay.
Macros
#define ST_LEFT 0x01
#define ST_DOWN 0x02
#define ST_UP 0x04
#define ST_RIGHT 0x08
#define ST_JUMPLR (ST_LEFT | ST_RIGHT)
#define ST_JUMPUD (ST_UP | ST_DOWN)
Enumerations
enum Animation {
ANIM_DANCE_PAD, ANIM_DANCE_PADS, ANIM_UP, ANIM_DOWN,
ANIM_LEFT, ANIM_RIGHT, ANIM_JUMPLR, NUM_ANIMATIONS,
ANIM_DANCE_PAD, ANIM_DANCE_PADS, ANIM_UP, ANIM_DOWN,
ANIM_LEFT, ANIM_RIGHT, ANIM_JUMPLR, NUM_ANIMATIONS
}
Functions
static RString GetAnimPath (Animation a)
static bool HaveAllCharAnimations ()
REGISTER_SCREEN_CLASS (ScreenHowToPlay)
Variables
static const ThemeMetric< int > NUM_W2S ("ScreenHowToPlay", "NumW2s")
static const ThemeMetric< int > NUM_MISSES ("ScreenHowToPlay", "NumMisses")
static const ThemeMetric< bool > USE_CHARACTER ("ScreenHowToPlay", "UseCharacter")
static const ThemeMetric< bool > USE_PAD ("ScreenHowToPlay", "UsePad")
static const ThemeMetric< bool > USE_PLAYER ("ScreenHowToPlay", "UsePlayer")
static const ThemeMetric< RString > CHARACTER_NAME ("ScreenHowToPlay", "CharacterName")
static const RString anims [NUM_ANIMATIONS]
Macro Definition Documentation
ST_DOWN
#define ST_DOWN 0x02
Referenced by ScreenHowToPlay::Step().
ST_JUMPLR
#define ST_JUMPLR (ST_LEFT | ST_RIGHT)
Referenced by ScreenHowToPlay::Step().
ST_JUMPUD
#define ST_JUMPUD (ST_UP | ST_DOWN)
Referenced by ScreenHowToPlay::Step().
ST_LEFT
#define ST_LEFT 0x01
Referenced by ScreenHowToPlay::Step().
ST_RIGHT
#define ST_RIGHT 0x08
Referenced by ScreenHowToPlay::Step().
ST_UP
#define ST_UP 0x04
Referenced by ScreenHowToPlay::Step().
Enumeration Type Documentation
Animation
enum Animation
Enumerator
ANIM_DANCE_PAD
ANIM_DANCE_PADS
ANIM_UP
ANIM_DOWN
ANIM_LEFT
ANIM_RIGHT
ANIM_JUMPLR
NUM_ANIMATIONS
ANIM_DANCE_PAD
ANIM_DANCE_PADS
ANIM_UP
ANIM_DOWN
ANIM_LEFT
ANIM_RIGHT
ANIM_JUMPLR
NUM_ANIMATIONS
Function Documentation
GetAnimPath()
static RString GetAnimPath (Animation a) static
Referenced by HaveAllCharAnimations(), and ScreenHowToPlay::Init().
HaveAllCharAnimations()
static bool HaveAllCharAnimations () static
References ANIM_UP, DoesFileExist(), GetAnimPath(), and NUM_ANIMATIONS.
Referenced by ScreenHowToPlay::Init().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenHowToPlay)
Variable Documentation
anims
const RString anims[NUM_ANIMATIONS] static
Initial value:
= {
    "DancePad.txt",
    "DancePads.txt",
    "BeginnerHelper_step-up.bones.txt",
    "BeginnerHelper_step-down.bones.txt",
    "BeginnerHelper_step-left.bones.txt",
    "BeginnerHelper_step-right.bones.txt",
    "BeginnerHelper_step-jumplr.bones.txt"
}
CHARACTER_NAME
const ThemeMetric<RString> CHARACTER_NAME("ScreenHowToPlay", "CharacterName") static
Referenced by ScreenHowToPlay::Init().
NUM_MISSES
const ThemeMetric<int> NUM_MISSES("ScreenHowToPlay", "NumMisses") static
Referenced by ScreenHowToPlay::Init().
NUM_W2S
const ThemeMetric<int> NUM_W2S("ScreenHowToPlay", "NumW2s") static
Referenced by ScreenHowToPlay::Init(), and ScreenHowToPlay::ScreenHowToPlay().
USE_CHARACTER
const ThemeMetric<bool> USE_CHARACTER("ScreenHowToPlay", "UseCharacter") static
Referenced by ScreenHowToPlay::Init().
USE_PAD
const ThemeMetric<bool> USE_PAD("ScreenHowToPlay", "UsePad") static
Referenced by ScreenHowToPlay::Init().
USE_PLAYER
const ThemeMetric<bool> USE_PLAYER("ScreenHowToPlay", "UsePlayer") static
Referenced by ScreenHowToPlay::Init().