Etterna: ScreenSMOnlineLogin.cpp File Reference
ScreenSMOnlineLogin.cpp File Reference
#include "global.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "NetworkSyncManager.h"
#include "OptionRowHandler.h"
#include "PrefsManager.h"
#include "ProfileManager.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "ScreenPrompt.h"
#include "ScreenSMOnlineLogin.h"
#include "ScreenTextEntry.h"
#include "ThemeManager.h"
Functions
REGISTER_SCREEN_CLASS (ScreenSMOnlineLogin)
AutoScreenMessage (SM_SMOnlinePack)
AutoScreenMessage (SM_PasswordDone)
AutoScreenMessage (SM_UsernameDone)
AutoScreenMessage (SM_NoProfilesDefined)
AutoScreenMessage (ETTP_Disconnect)
AutoScreenMessage (ETTP_LoginResponse)
Variables
static LocalizedString DEFINE_A_PROFILE ("ScreenSMOnlineLogin", "You must define a Profile.")
static LocalizedString UNIQUE_PROFILE ("ScreenSMOnlineLogin", "Each player needs a unique Profile.")
static LocalizedString YOU_ARE_LOGGING_ON_AS ("ScreenSMOnlineLogin", "You are logging on as:")
static LocalizedString ENTER_YOUR_PASSWORD ("ScreenSMOnlineLogin", "Enter your password.")
Function Documentation
AutoScreenMessage() [1/6]
AutoScreenMessage (SM_SMOnlinePack)
AutoScreenMessage() [2/6]
AutoScreenMessage (SM_PasswordDone)
AutoScreenMessage() [3/6]
AutoScreenMessage (SM_UsernameDone)
AutoScreenMessage() [4/6]
AutoScreenMessage (SM_NoProfilesDefined)
AutoScreenMessage() [5/6]
AutoScreenMessage (ETTP_Disconnect)
AutoScreenMessage() [6/6]
AutoScreenMessage (ETTP_LoginResponse)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenSMOnlineLogin)
Variable Documentation
DEFINE_A_PROFILE
LocalizedString DEFINE_A_PROFILE("ScreenSMOnlineLogin", "You must define a Profile.") static
Referenced by ScreenSMOnlineLogin::HandleScreenMessage().
ENTER_YOUR_PASSWORD
LocalizedString ENTER_YOUR_PASSWORD("ScreenSMOnlineLogin", "Enter your password.") static
Referenced by ScreenSMOnlineLogin::HandleScreenMessage().
UNIQUE_PROFILE
LocalizedString UNIQUE_PROFILE("ScreenSMOnlineLogin", "Each player needs a unique Profile.") static
Referenced by ScreenSMOnlineLogin::HandleScreenMessage().
YOU_ARE_LOGGING_ON_AS
LocalizedString YOU_ARE_LOGGING_ON_AS("ScreenSMOnlineLogin", "You are logging on as:") static
Referenced by ScreenSMOnlineLogin::HandleScreenMessage().