Etterna: RageSurface.h File Reference
RageSurface.h File Reference
#include "global.h"
Classes
struct RageSurfaceColor
struct RageSurfacePalette
struct RageSurfaceFormat
struct RageSurface
Functions
bool operator== (RageSurfaceColor const &lhs, RageSurfaceColor const &rhs)
bool operator!= (RageSurfaceColor const &lhs, RageSurfaceColor const &rhs)
RageSurface * CreateSurface (int width, int height, int bpp, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
RageSurface * CreateSurfaceFrom (int width, int height, int bpp, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask, uint8_t *pPixels, uint32_t pitch)
Function Documentation
CreateSurface()
RageSurface* CreateSurface (int width, int height, int bpp, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
References SetupFormat().
Referenced by RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface(), ImageCache::CacheImageInternal(), RageSurfaceUtils::ConvertSurface(), RageBitmapTexture::Create(), RageDisplay_GLES2::CreateScreenshot(), RageDisplay_D3D::CreateScreenshot(), RageDisplay_Null::CreateScreenshot(), RageDisplay_Legacy::CreateScreenshot(), MovieTexture_DShow::CreateTexture(), RageDisplay_Legacy::GetImgPixelFormat(), RageDisplay_Legacy::GetTexture(), LoadBMP(), RageSurfaceUtils::LoadSurface(), LoadWin32Surface(), RageSurfaceUtils::MakeDummySurface(), MakePixbuf(), MovieTexture_Null::MovieTexture_Null(), RageSurfaceUtils::Palettize(), RageSurfaceUtils::PalettizeToGrayscale(), RageSurface_Load_JPEG(), RageSurface_Load_XPM(), ReadImage(), RageSurfaceUtils::SaveBMP(), and RageSurfaceUtils::Zoom().
CreateSurfaceFrom()
RageSurface* CreateSurfaceFrom (int width, int height, int bpp, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask, uint8_t * pPixels, uint32_t pitch)
References SetupFormat().
Referenced by MovieTexture_DShow::CheckFrame(), RageDisplay::CreateSurfaceFromPixfmt(), and RageMovieTexture_Generic_Intermediate::CreateTexture().
operator!=()
bool operator!= (RageSurfaceColor const & lhs, RageSurfaceColor const & rhs) inline
References operator==().
operator==()
bool operator== (RageSurfaceColor const & lhs, RageSurfaceColor const & rhs) inline
References RageSurfaceColor::a, RageSurfaceColor::b, RageSurfaceColor::g, and RageSurfaceColor::r.
Referenced by operator!=().