Etterna: OptionRowHandlerConfig Class Reference
OptionRowHandlerConfig Class Reference
Public Member Functions
OptionRowHandlerConfig ()
void Init () override
bool LoadInternal (const Commands &cmds) override
void ImportOption (OptionRow *, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual ReloadChanged Reload ()
virtual int GetDefaultOption () const
virtual void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const
virtual RString GetScreen (int) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
const ConfOption * m_pOpt
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerConfig()
OptionRowHandlerConfig::OptionRowHandlerConfig () inline
References Init().
Member Function Documentation
ExportOption()
int OptionRowHandlerConfig::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References FOREACH_CONST, ConfOption::Get(), ConfOption::GetEffects(), OptionRowHandlerUtil::GetOneSelection(), and ConfOption::Put().
ImportOption()
void OptionRowHandlerConfig::ImportOption (OptionRow * , const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References FOREACH_CONST, ConfOption::Get(), and OptionRowHandlerUtil::SelectExactlyOne().
Init()
void OptionRowHandlerConfig::Init () inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::Init().
Referenced by LoadInternal(), and OptionRowHandlerConfig().
LoadInternal()
bool OptionRowHandlerConfig::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
References CHECK_BLANK_ARG, CHECK_WRONG_NUM_ARGS, ConfOption::Find(), Command::GetArg(), Init(), ConfOption::m_bAllowThemeItems, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_sName, OptionRowDefinition::m_vsChoices, ConfOption::MakeOptionsList(), ConfOption::name, ROW_INVALID_IF, Command::Arg::s, ConfOption::UpdateAvailableOptions(), and Commands::v.
Member Data Documentation
m_pOpt
const ConfOption* OptionRowHandlerConfig::m_pOpt
The documentation for this class was generated from the following file:
OptionRowHandler.cpp