Etterna: DebugLineShowRecentErrors Class Reference
DebugLineShowRecentErrors Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineShowRecentErrors::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References MessageManager::Broadcast(), IDebugLine::DoAndLog(), and MESSAGEMAN.
GetDisplayTitle()
RString DebugLineShowRecentErrors::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and SHOW_RECENT_ERRORS.
GetDisplayValue()
RString DebugLineShowRecentErrors::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPageName()
RString DebugLineShowRecentErrors::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineShowRecentErrors::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp