Etterna: LunaCharacter Class Reference
LunaCharacter Class Reference
Allow Lua to have access to the Character.
Public Member Functions
LunaCharacter ()
Public Member Functions inherited from Luna< Character >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetCardPath (T *p, lua_State *L)
static int GetIconPath (T *p, lua_State *L)
static int GetSongSelectIconPath (T *p, lua_State *L)
static int GetStageIconPath (T *p, lua_State *L)
static int GetModelPath (T *p, lua_State *L)
static int GetRestAnimationPath (T *p, lua_State *L)
static int GetWarmUpAnimationPath (T *p, lua_State *L)
static int GetDanceAnimationPath (T *p, lua_State *L)
static int GetCharacterDir (T *p, lua_State *L)
static int GetCharacterID (T *p, lua_State *L)
static int GetDisplayName (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Character >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Character >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Character >
using T = Character
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Character >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Character.
Constructor & Destructor Documentation
LunaCharacter()
LunaCharacter::LunaCharacter () inline
References ADD_METHOD, GetCardPath(), GetCharacterDir(), GetCharacterID(), GetDanceAnimationPath(), GetDisplayName(), GetIconPath(), GetModelPath(), GetRestAnimationPath(), GetSongSelectIconPath(), GetStageIconPath(), and GetWarmUpAnimationPath().
Member Function Documentation
GetCardPath()
static int LunaCharacter::GetCardPath (T * p, lua_State * L) inline static
References Character::GetCardPath().
Referenced by LunaCharacter().
GetCharacterDir()
static int LunaCharacter::GetCharacterDir (T * p, lua_State * L) inline static
References Character::m_sCharDir.
Referenced by LunaCharacter().
GetCharacterID()
static int LunaCharacter::GetCharacterID (T * p, lua_State * L) inline static
References Character::m_sCharacterID.
Referenced by LunaCharacter().
GetDanceAnimationPath()
static int LunaCharacter::GetDanceAnimationPath (T * p, lua_State * L) inline static
References Character::GetDanceAnimationPath().
Referenced by LunaCharacter().
GetDisplayName()
static int LunaCharacter::GetDisplayName (T * p, lua_State * L) inline static
References Character::GetDisplayName().
Referenced by LunaCharacter().
GetIconPath()
static int LunaCharacter::GetIconPath (T * p, lua_State * L) inline static
References Character::GetIconPath().
Referenced by LunaCharacter().
GetModelPath()
static int LunaCharacter::GetModelPath (T * p, lua_State * L) inline static
References Character::GetModelPath().
Referenced by LunaCharacter().
GetRestAnimationPath()
static int LunaCharacter::GetRestAnimationPath (T * p, lua_State * L) inline static
References Character::GetRestAnimationPath().
Referenced by LunaCharacter().
GetSongSelectIconPath()
static int LunaCharacter::GetSongSelectIconPath (T * p, lua_State * L) inline static
References Character::GetSongSelectIconPath().
Referenced by LunaCharacter().
GetStageIconPath()
static int LunaCharacter::GetStageIconPath (T * p, lua_State * L) inline static
References Character::GetStageIconPath().
Referenced by LunaCharacter().
GetWarmUpAnimationPath()
static int LunaCharacter::GetWarmUpAnimationPath (T * p, lua_State * L) inline static
References Character::GetWarmUpAnimationPath().
Referenced by LunaCharacter().
The documentation for this class was generated from the following file:
Character.cpp