Etterna: sm_parser_helper_t Struct Reference
sm_parser_helper_t Struct Reference
Public Member Functions
sm_parser_helper_t ()
Public Attributes
song_handler_map_t song_tag_handlers
Constructor & Destructor Documentation
sm_parser_helper_t()
sm_parser_helper_t::sm_parser_helper_t () inline
References SMSetArtist(), SMSetArtistTranslit(), SMSetBackground(), SMSetBanner(), SMSetBGChanges(), SMSetBPMs(), SMSetCDTitle(), SMSetCredit(), SMSetDelays(), SMSetDisplayBPM(), SMSetFGChanges(), SMSetGenre(), SMSetInstrumentTrack(), SMSetKeysounds(), SMSetLyricsPath(), SMSetMusic(), SMSetOffset(), SMSetSampleLength(), SMSetSampleStart(), SMSetSelectable(), SMSetStops(), SMSetSubtitle(), SMSetSubtitleTranslit(), SMSetTickCounts(), SMSetTimeSignatures(), SMSetTitle(), and SMSetTitleTranslit().
Member Data Documentation
song_tag_handlers
song_handler_map_t sm_parser_helper_t::song_tag_handlers
Referenced by SMLoader::LoadFromSimfile().
The documentation for this struct was generated from the following file:
NotesLoaderSM.cpp