Etterna: CryptManager Class Reference
CryptManager Class Reference
#include <CryptManager.h>
Public Member Functions
CryptManager ()
~CryptManager ()
void PushSelf (lua_State *L)
Static Public Member Functions
static void GenerateGlobalKeys ()
static void GenerateRSAKey (unsigned int keyLength, RString &sPrivKey, RString &sPubKey)
static void GenerateRSAKeyToFile (unsigned int keyLength, const RString &privFilename, const RString &pubFilename)
static void SignFileToFile (const RString &sPath, RString sSignatureFile="")
static bool Sign (const RString &sPath, RString &sSignatureOut, const RString &sPrivateKey)
static bool VerifyFileWithFile (const RString &sPath, const RString &sSignatureFile="")
static bool VerifyFileWithFile (const RString &sPath, RString sSignatureFile, const RString &sPublicKeyFile)
static bool Verify (RageFileBasic &file, const RString &sSignature, const RString &sPublicKey)
static void GetRandomBytes (void *pData, int iBytes)
static RString GenerateRandomUUID ()
static RString GetMD5ForFile (const RString &fn)
static RString GetMD5ForString (const RString &sData)
static RString GetSHA1ForString (const RString &sData)
static RString GetSHA1ForFile (const RString &fn)
static RString GetPublicKeyFileName ()
Constructor & Destructor Documentation
CryptManager()
CryptManager::CryptManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~CryptManager()
CryptManager::~CryptManager ()
References LUA, SAFE_DELETE, and LuaManager::UnsetGlobal().
Member Function Documentation
GenerateGlobalKeys()
void CryptManager::GenerateGlobalKeys () static
References DoesFileExist(), GenerateRSAKeyToFile(), GetFileContents(), RSAKeyWrapper::Load(), LOG, and RageLog::Warn().
Referenced by sm_main().
GenerateRandomUUID()
RString CryptManager::GenerateRandomUUID () static
References GetRandomBytes(), and ssprintf().
Referenced by GameState::BeginStage(), and LunaCryptManager::GenerateRandomUUID().
GenerateRSAKey()
void CryptManager::GenerateRSAKey (unsigned int keyLength, RString & sPrivKey, RString & sPubKey) static
References LOG, PRNGWrapper::m_iPRNG, PRNGWrapper::m_PRNG, and RageLog::Warn().
Referenced by GenerateRSAKeyToFile().
GenerateRSAKeyToFile()
void CryptManager::GenerateRSAKeyToFile (unsigned int keyLength, const RString & privFilename, const RString & pubFilename) static
References FILEMAN, GenerateRSAKey(), RageFileManager::Remove(), and WriteFile().
Referenced by GenerateGlobalKeys().
GetMD5ForFile()
RString CryptManager::GetMD5ForFile (const RString & fn) static
References ASSERT, HashFile(), LOG, RageFile::Open(), RageFile::READ, and RageLog::Warn().
Referenced by LunaProfile::AddScreenshot(), ScreenEvaluation::Input(), and LunaCryptManager::MD5File().
GetMD5ForString()
RString CryptManager::GetMD5ForString (const RString & sData) static
Referenced by NetworkSyncManager::MD5Hex(), and LunaCryptManager::MD5String().
GetPublicKeyFileName()
RString CryptManager::GetPublicKeyFileName () static
References PUBLIC_KEY_PATH.
Referenced by Profile::SaveMachinePublicKeyToDir().
GetRandomBytes()
void CryptManager::GetRandomBytes (void * pData, int iBytes) static
References ASSERT, PRNGWrapper::m_iPRNG, and PRNGWrapper::m_PRNG.
Referenced by GenerateRandomUUID(), and Profile::MakeGuid().
GetSHA1ForFile()
RString CryptManager::GetSHA1ForFile (const RString & fn) static
References ASSERT, HashFile(), LOG, RageFile::Open(), RageFile::READ, and RageLog::Warn().
Referenced by Song::GetFileHash(), and LunaCryptManager::SHA1File().
GetSHA1ForString()
RString CryptManager::GetSHA1ForString (const RString & sData) static
Referenced by HighScoreImpl::CreateEttNode(), DoInstalls(), FillInHighScore(), Steps::GenerateBustedChartKey(), Steps::GenerateChartKey(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), DBProfile::LoadPlayerScores(), DBProfile::SavePlayerScores(), and LunaCryptManager::SHA1String().
PushSelf()
void CryptManager::PushSelf (lua_State * L)
Referenced by CryptManager().
Sign()
bool CryptManager::Sign (const RString & sPath, RString & sSignatureOut, const RString & sPrivateKey) static
References ASSERT, RageFile::GetError(), HashFile(), IsAFile(), RSAKeyWrapper::Load(), LOG, PRNGWrapper::m_iPRNG, RSAKeyWrapper::m_Key, PRNGWrapper::m_PRNG, RageFile::Open(), RageLog::Trace(), and RageLog::Warn().
Referenced by SignFileToFile().
SignFileToFile()
void CryptManager::SignFileToFile (const RString & sPath, RString sSignatureFile = "") static
References GetFileContents(), PRIVATE_KEY_PATH, Sign(), SIGNATURE_APPEND, and WriteFile().
Referenced by StepMania::SaveScreenshot(), and XMLProfile::SaveStatsXmlToDir().
Verify()
bool CryptManager::Verify (RageFileBasic & file, const RString & sSignature, const RString & sPublicKey) static
References ASSERT, RageFileBasic::GetDisplayPath(), HashFile(), RSAKeyWrapper::Load(), LOG, RSAKeyWrapper::m_Key, and RageLog::Warn().
Referenced by VerifyFileWithFile().
VerifyFileWithFile() [1/2]
bool CryptManager::VerifyFileWithFile (const RString & sPath, const RString & sSignatureFile = "") static
References GetDirListing(), LOG, and RageLog::Trace().
Referenced by XMLProfile::LoadStatsFromDir().
VerifyFileWithFile() [2/2]
bool CryptManager::VerifyFileWithFile (const RString & sPath, RString sSignatureFile, const RString & sPublicKeyFile) static
References FILEMAN, RageFile::GetError(), GetFileContents(), RageFileManager::GetFileSizeInBytes(), LOG, MAX_SIGNATURE_SIZE_BYTES, RageFile::Open(), SIGNATURE_APPEND, Verify(), and RageLog::Warn().
The documentation for this class was generated from the following files:
CryptManager.h
CryptManager.cpp