Etterna: RageFileDriverZip Class Reference
RageFileDriverZip Class Reference
A read-only file driver for ZIPs.
#include <RageFileDriverZip.h>
Classes
struct FileInfo
Public Types
enum ZipCompressionMethod { STORED = 0, DEFLATED = 8 }
Public Types inherited from RageFileDriver
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Member Functions
RageFileDriverZip ()
RageFileDriverZip (const RString &sPath)
bool Load (const RString &sPath)
bool Load (RageFileBasic *pFile)
~RageFileDriverZip () override
RageFileBasic * Open (const RString &sPath, int iMode, int &iErr) override
void FlushDirCache (const RString &sPath) override
void DeleteFileWhenFinished ()
const FileInfo * GetFileInfo (const RString &sPath) const
RString GetGlobalComment () const
Public Member Functions inherited from RageFileDriver
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void CacheFile (const RString &)
virtual bool Move (const RString &, const RString &)
virtual bool Remove (const RString &)
virtual bool Remount (const RString &)
Private Member Functions
bool ParseZipfile ()
bool ReadEndCentralRecord (int &total_entries_central_dir, int &offset_start_central_directory)
int ProcessCdirFileHdr (FileInfo &info)
bool SeekToEndCentralRecord ()
bool ReadLocalFileHeader (FileInfo &info)
Private Attributes
bool m_bFileOwned
RageFileBasic * m_pZip
vector< FileInfo * > m_pFiles
RString m_sPath
RString m_sComment
RageMutex m_Mutex
Additional Inherited Members
Public Attributes inherited from RageFileDriver
FilenameDB * FDB
Detailed Description
A read-only file driver for ZIPs.
Member Enumeration Documentation
ZipCompressionMethod
enum RageFileDriverZip::ZipCompressionMethod
Enumerator
STORED
DEFLATED
Constructor & Destructor Documentation
RageFileDriverZip() [1/2]
RageFileDriverZip::RageFileDriverZip ()
References m_bFileOwned, and m_pZip.
RageFileDriverZip() [2/2]
RageFileDriverZip::RageFileDriverZip (const RString & sPath) explicit
References Load(), m_bFileOwned, and m_pZip.
~RageFileDriverZip()
RageFileDriverZip::~RageFileDriverZip () override
References m_bFileOwned, m_pFiles, and m_pZip.
Member Function Documentation
DeleteFileWhenFinished()
void RageFileDriverZip::DeleteFileWhenFinished () inline
References m_bFileOwned.
FlushDirCache()
void RageFileDriverZip::FlushDirCache (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
GetFileInfo()
const RageFileDriverZip::FileInfo * RageFileDriverZip::GetFileInfo (const RString & sPath) const
References RageFileDriver::FDB, and FilenameDB::GetFilePriv().
GetGlobalComment()
RString RageFileDriverZip::GetGlobalComment () const inline
References m_sComment.
Load() [1/2]
bool RageFileDriverZip::Load (const RString & sPath)
References ASSERT, m_bFileOwned, m_Mutex, m_pZip, m_sPath, ParseZipfile(), RageMutex::SetName(), ssprintf(), and WARN.
Referenced by RageFileDriverZip().
Load() [2/2]
bool RageFileDriverZip::Load (RageFileBasic * pFile)
References ASSERT, m_Mutex, m_pZip, m_sPath, ParseZipfile(), RageMutex::SetName(), and ssprintf().
Open()
RageFileBasic * RageFileDriverZip::Open (const RString & sPath, int iMode, int & iErr) override virtual
Implements RageFileDriver.
References RageFileBasic::Copy(), DEFLATED, RageFileDriverSlice::DeleteFileWhenFinished(), RageFileObjInflate::DeleteFileWhenFinished(), RageFileDriver::ERROR_WRITING_NOT_SUPPORTED, RageFileDriver::FDB, FilenameDB::GetFilePriv(), RageMutex::Lock(), m_Mutex, m_pZip, ReadLocalFileHeader(), STORED, RageMutex::Unlock(), and RageFile::WRITE.
ParseZipfile()
bool RageFileDriverZip::ParseZipfile () private
References FilenameDB::AddFile(), RageFileDriver::FDB, RageFileDriverZip::FileInfo::m_iDataOffset, m_pFiles, m_pZip, m_sPath, ProcessCdirFileHdr(), ReadEndCentralRecord(), RageFileBasic::Seek(), SeekToEndCentralRecord(), ssprintf(), and WARN.
Referenced by Load().
ProcessCdirFileHdr()
int RageFileDriverZip::ProcessCdirFileHdr (FileInfo & info) private
References DEFLATED, RageFileDriverZip::FileInfo::m_iCompressedSize, RageFileDriverZip::FileInfo::m_iCompressionMethod, RageFileDriverZip::FileInfo::m_iCRC32, RageFileDriverZip::FileInfo::m_iFilePermissions, RageFileDriverZip::FileInfo::m_iOffset, RageFileDriverZip::FileInfo::m_iUncompressedSize, m_pZip, RageFileDriverZip::FileInfo::m_sName, m_sPath, FileReading::read_16_le(), FileReading::read_32_le(), FileReading::read_8(), FileReading::ReadString(), FileReading::SkipBytes(), ssprintf(), STORED, and WARN.
Referenced by ParseZipfile().
ReadEndCentralRecord()
bool RageFileDriverZip::ReadEndCentralRecord (int & total_entries_central_dir, int & offset_start_central_directory) private
References m_pZip, m_sComment, m_sPath, FileReading::read_16_le(), FileReading::read_32_le(), FileReading::ReadString(), ssprintf(), and WARN.
Referenced by ParseZipfile().
ReadLocalFileHeader()
bool RageFileDriverZip::ReadLocalFileHeader (FileInfo & info) private
References RageFileDriverZip::FileInfo::m_iDataOffset, RageFileDriverZip::FileInfo::m_iOffset, m_pZip, RageFileDriverZip::FileInfo::m_sName, m_sPath, FileReading::read_16_le(), FileReading::ReadString(), RageFileBasic::Seek(), FileReading::SkipBytes(), ssprintf(), RageFileBasic::Tell(), and WARN.
Referenced by Open().
SeekToEndCentralRecord()
bool RageFileDriverZip::SeekToEndCentralRecord () private
References RageFileBasic::GetError(), RageFileBasic::GetFileSize(), m_pZip, m_sPath, max(), RageFileBasic::Read(), RageFileBasic::Seek(), ssprintf(), and WARN.
Referenced by ParseZipfile().
Member Data Documentation
m_bFileOwned
bool RageFileDriverZip::m_bFileOwned private
Referenced by DeleteFileWhenFinished(), Load(), RageFileDriverZip(), and ~RageFileDriverZip().
m_Mutex
RageMutex RageFileDriverZip::m_Mutex private
Referenced by Load(), and Open().
m_pFiles
vector<FileInfo*> RageFileDriverZip::m_pFiles private
Referenced by ParseZipfile(), and ~RageFileDriverZip().
m_pZip
RageFileBasic* RageFileDriverZip::m_pZip private
Referenced by Load(), Open(), ParseZipfile(), ProcessCdirFileHdr(), RageFileDriverZip(), ReadEndCentralRecord(), ReadLocalFileHeader(), SeekToEndCentralRecord(), and ~RageFileDriverZip().
m_sComment
RString RageFileDriverZip::m_sComment private
Referenced by GetGlobalComment(), and ReadEndCentralRecord().
m_sPath
RString RageFileDriverZip::m_sPath private
Referenced by Load(), ParseZipfile(), ProcessCdirFileHdr(), ReadEndCentralRecord(), ReadLocalFileHeader(), and SeekToEndCentralRecord().
The documentation for this class was generated from the following files:
RageFileDriverZip.h
RageFileDriverZip.cpp