Etterna: RageSurface_Load_GIF.cpp File Reference
RageSurface_Load_GIF.cpp File Reference
#include "global.h"
#include "RageSurface_Load_GIF.h"
#include "RageFile.h"
#include "RageSurface.h"
#include "RageUtil.h"
Classes
struct LWZState
struct LWZState::Code
Macros
#define MAXCOLORMAPSIZE 256
#define MAX_LWZ_BITS 12
#define INTERLACE 0x40
#define LOCALCOLORMAP 0x80
#define BitSet(byte, bit) (((byte) & (bit)) == (bit))
#define ReadOK(file, buffer, len) ((file).Read(buffer, len, 1) != 0)
#define LM_to_uint(a, b) (((b) << 8) | (a))
Functions
static RageSurface * ReadImage (RageFile &f, int len, int height, const RageSurfaceColor localColorMap[MAXCOLORMAPSIZE], int interlace, int ignore)
static bool ReadPalette (RageFile &f, int number, RageSurfaceColor buffer[MAXCOLORMAPSIZE])
static int GetDataBlock (RageFile &f, unsigned char *buf)
RageSurfaceUtils::OpenResult RageSurface_Load_GIF (const RString &sPath, RageSurface *&ret, bool bHeaderOnly, RString &error)
Macro Definition Documentation
BitSet
#define BitSet (byte, bit) (((byte) & (bit)) == (bit))
Referenced by RageSurface_Load_GIF().
INTERLACE
#define INTERLACE 0x40
Referenced by RageSurface_Load_GIF().
LM_to_uint
#define LM_to_uint (a, b) (((b) << 8) | (a))
Referenced by RageSurface_Load_GIF().
LOCALCOLORMAP
#define LOCALCOLORMAP 0x80
Referenced by RageSurface_Load_GIF().
MAX_LWZ_BITS
#define MAX_LWZ_BITS 12
Referenced by LWZState::ReadByte().
MAXCOLORMAPSIZE
#define MAXCOLORMAPSIZE 256
Referenced by RageSurface_Load_GIF().
ReadOK
#define ReadOK (file, buffer, len) ((file).Read(buffer, len, 1) != 0)
Referenced by GetDataBlock(), LWZState::Init(), RageSurface_Load_GIF(), and ReadPalette().
Function Documentation
GetDataBlock()
static int GetDataBlock (RageFile & f, unsigned char * buf) static
References ReadOK.
Referenced by LWZState::Code::Get(), RageSurface_Load_GIF(), and LWZState::ReadByte().
RageSurface_Load_GIF()
RageSurfaceUtils::OpenResult RageSurface_Load_GIF (const RString & sPath, RageSurface *& ret, bool bHeaderOnly, RString & error)
References RageSurfaceColor::a, BitSet, RageSurfacePalette::colors, f, RageSurface::fmt, GetDataBlock(), RageFile::GetError(), INTERLACE, label, LM_to_uint, LOCALCOLORMAP, MAXCOLORMAPSIZE, RageFile::Open(), RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, RageSurfaceFormat::palette, ReadImage(), ReadOK, ReadPalette(), and ssprintf().
Referenced by TryOpenFile().
ReadImage()
static RageSurface * ReadImage (RageFile & f, int len, int height, const RageSurfaceColor localColorMap[MAXCOLORMAPSIZE], int interlace, int ignore) static
References RageSurfacePalette::colors, CreateSurface(), RageSurface::fmt, LWZState::Init(), RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, and LWZState::ReadByte().
Referenced by RageSurface_Load_GIF().
ReadPalette()
static bool ReadPalette (RageFile & f, int number, RageSurfaceColor buffer[MAXCOLORMAPSIZE]) static
References ReadOK.
Referenced by RageSurface_Load_GIF().