Etterna: LoadingWindow_Gtk Class Reference
LoadingWindow_Gtk Class Reference
#include <LoadingWindow_Gtk.h>
Public Member Functions
LoadingWindow_Gtk ()
RString Init ()
~LoadingWindow_Gtk ()
void SetText (const RString &str)
void SetIcon (const RageSurface *pIcon)
void SetSplash (const RageSurface *pSplash)
void SetProgress (const int progress)
void SetTotalWork (const int totalWork)
void SetIndeterminate (bool indeterminate)
Public Member Functions inherited from LoadingWindow
virtual ~LoadingWindow ()=default
Additional Inherited Members
Static Public Member Functions inherited from LoadingWindow
static LoadingWindow * Create ()
Protected Attributes inherited from LoadingWindow
int m_progress
int m_totalWork
bool m_indeterminate
Constructor & Destructor Documentation
LoadingWindow_Gtk()
LoadingWindow_Gtk::LoadingWindow_Gtk ()
~LoadingWindow_Gtk()
LoadingWindow_Gtk::~LoadingWindow_Gtk ()
References Handle, and Module_Shutdown.
Member Function Documentation
Init()
RString LoadingWindow_Gtk::Init () virtual
Reimplemented from LoadingWindow.
References ASSERT, g_argc, g_argv, Handle, Module_Init, Module_SetIcon, Module_SetIndeterminate, Module_SetProgress, Module_SetSplash, Module_SetText, Module_Shutdown, ModuleError(), RageFileManagerUtil::sDirOfExecutable, and ssprintf().
SetIcon()
void LoadingWindow_Gtk::SetIcon (const RageSurface * pIcon) virtual
Reimplemented from LoadingWindow.
References Module_SetIcon.
SetIndeterminate()
void LoadingWindow_Gtk::SetIndeterminate (bool indeterminate) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_indeterminate, Module_SetIndeterminate, and LoadingWindow::SetIndeterminate().
SetProgress()
void LoadingWindow_Gtk::SetProgress (const int progress) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_progress, LoadingWindow::m_totalWork, Module_SetProgress, and LoadingWindow::SetProgress().
SetSplash()
void LoadingWindow_Gtk::SetSplash (const RageSurface * pSplash) virtual
Reimplemented from LoadingWindow.
References Module_SetSplash.
SetText()
void LoadingWindow_Gtk::SetText (const RString & str) virtual
Implements LoadingWindow.
References Module_SetText.
SetTotalWork()
void LoadingWindow_Gtk::SetTotalWork (const int totalWork) virtual
Reimplemented from LoadingWindow.
References LoadingWindow::m_progress, LoadingWindow::m_totalWork, Module_SetProgress, and LoadingWindow::SetTotalWork().
The documentation for this class was generated from the following files:
LoadingWindow_Gtk.h
LoadingWindow_Gtk.cpp