Etterna: FakeSegment Struct Reference
FakeSegment Struct Reference
Identifies when a whole region of arrows is to be ignored.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
TimingSegment * Copy () const override
bool IsNotable () const override
void DebugPrint () const override
FakeSegment ()
FakeSegment (int iStartRow, int iLengthRows)
FakeSegment (int iStartRow, float fBeats)
FakeSegment (const FakeSegment &other)
int GetLengthRows () const
float GetLengthBeats () const
float GetLength () const
void SetLength (int iRows)
void SetLength (float fBeats)
void Scale (int start, int length, int newLength) override
Scales itself.
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const FakeSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
int m_iLengthRows
The number of rows the FakeSegment is alive for.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a whole region of arrows is to be ignored.
FakeSegments are similar to the Fake Tap Notes in that the contents inside are neither for nor against the player. They can be useful for mission modes, in conjunction with WarpSegments, or perhaps other uses not thought up at the time of this comment. Unlike the Warp Segments, these are not magically jumped over: instead, these are drawn normally.
These were inspired by the Pump It Up series.
Constructor & Destructor Documentation
FakeSegment() [1/4]
FakeSegment::FakeSegment () inline
Referenced by Copy().
FakeSegment() [2/4]
FakeSegment::FakeSegment (int iStartRow, int iLengthRows) inline
FakeSegment() [3/4]
FakeSegment::FakeSegment (int iStartRow, float fBeats) inline
FakeSegment() [4/4]
FakeSegment::FakeSegment (const FakeSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* FakeSegment::Copy () const inline override virtual
Implements TimingSegment.
References FakeSegment().
DebugPrint()
void FakeSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLengthBeats(), GetLengthRows(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType FakeSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Range.
GetLength()
float FakeSegment::GetLength () const inline
References GetLengthBeats().
Referenced by GetValues(), TimingData::IsFakeAtRow(), Scale(), and ToString().
GetLengthBeats()
float FakeSegment::GetLengthBeats () const inline
References m_iLengthRows, and ToBeat().
Referenced by DebugPrint(), and GetLength().
GetLengthRows()
int FakeSegment::GetLengthRows () const inline
References m_iLengthRows.
Referenced by DebugPrint().
GetType()
TimingSegmentType FakeSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_FAKE.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> FakeSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetLength().
IsNotable()
bool FakeSegment::IsNotable () const inline override virtual
Implements TimingSegment.
References m_iLengthRows.
operator==() [1/2]
bool FakeSegment::operator== (const FakeSegment & other) const inline
References COMPARE, and m_iLengthRows.
Referenced by operator==().
operator==() [2/2]
bool FakeSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
Scale()
void FakeSegment::Scale (int start, int length, int newLength) override virtual
Scales itself.
Parameters
start Starting row
length Length in rows
newLength The new length in rows
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLength(), NoteRowToBeat(), TimingSegment::Scale(), ScalePosition(), and SetLength().
SetLength() [1/2]
void FakeSegment::SetLength (int iRows) inline
References m_iLengthRows, and ToNoteRow().
Referenced by Scale().
SetLength() [2/2]
void FakeSegment::SetLength (float fBeats) inline
References m_iLengthRows, and ToNoteRow().
ToString()
RString FakeSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetLength(), IntToString(), and ssprintf().
Member Data Documentation
m_iLengthRows
int FakeSegment::m_iLengthRows private
The number of rows the FakeSegment is alive for.
Referenced by GetLengthBeats(), GetLengthRows(), IsNotable(), operator==(), and SetLength().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp