Etterna: LunaSprite Class Reference
LunaSprite Class Reference
Allow Lua to have access to the Sprite.
Public Member Functions
DEFINE_METHOD (GetDecodeMovie, m_DecodeMovie)
LunaSprite ()
Public Member Functions inherited from Luna< Sprite >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int Load (T *p, lua_State *L)
static int LoadBackground (T *p, lua_State *L)
static int LoadBanner (T *p, lua_State *L)
static int customtexturerect (T *p, lua_State *L)
static int SetCustomImageRect (T *p, lua_State *L)
static int SetCustomPosCoords (T *p, lua_State *L)
static int StopUsingCustomPosCoords (T *p, lua_State *L)
static int texcoordvelocity (T *p, lua_State *L)
static int get_use_effect_clock_for_texcoords (T *p, lua_State *L)
static int set_use_effect_clock_for_texcoords (T *p, lua_State *L)
static int scaletoclipped (T *p, lua_State *L)
static int CropTo (T *p, lua_State *L)
static int stretchtexcoords (T *p, lua_State *L)
static int addimagecoords (T *p, lua_State *L)
static int setstate (T *p, lua_State *L)
static int GetState (T *p, lua_State *L)
static int SetStateProperties (T *p, lua_State *L)
static int GetAnimationLengthSeconds (T *p, lua_State *L)
static int SetSecondsIntoAnimation (T *p, lua_State *L)
static int SetTexture (T *p, lua_State *L)
static int GetTexture (T *p, lua_State *L)
static int SetEffectMode (T *p, lua_State *L)
static int GetNumStates (T *p, lua_State *L)
static int SetAllStateDelays (T *p, lua_State *L)
static int SetDecodeMovie (T *p, lua_State *L)
static int LoadFromCached (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Sprite >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Sprite >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Sprite >
using T = Sprite
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Sprite >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Sprite.
Constructor & Destructor Documentation
LunaSprite()
LunaSprite::LunaSprite () inline
References ADD_METHOD, addimagecoords(), CropTo(), customtexturerect(), get_use_effect_clock_for_texcoords(), GetAnimationLengthSeconds(), GetNumStates(), GetState(), GetTexture(), Load(), LoadBackground(), LoadBanner(), LoadFromCached(), scaletoclipped(), set_use_effect_clock_for_texcoords(), SetAllStateDelays(), SetCustomImageRect(), SetCustomPosCoords(), SetDecodeMovie(), SetEffectMode(), SetSecondsIntoAnimation(), setstate(), SetStateProperties(), SetTexture(), StopUsingCustomPosCoords(), stretchtexcoords(), and texcoordvelocity().
Member Function Documentation
addimagecoords()
static int LunaSprite::addimagecoords (T * p, lua_State * L) inline static
References Sprite::AddImageCoords(), COMMON_RETURN_SELF, and FArg.
Referenced by LunaSprite().
CropTo()
static int LunaSprite::CropTo (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Sprite::CropTo(), and FArg.
Referenced by LunaSprite().
customtexturerect()
static int LunaSprite::customtexturerect (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetCustomTextureRect().
Referenced by LunaSprite().
DEFINE_METHOD()
LunaSprite::DEFINE_METHOD (GetDecodeMovie , m_DecodeMovie)
get_use_effect_clock_for_texcoords()
static int LunaSprite::get_use_effect_clock_for_texcoords (T * p, lua_State * L) inline static
References Sprite::m_use_effect_clock_for_texcoords.
Referenced by LunaSprite().
GetAnimationLengthSeconds()
static int LunaSprite::GetAnimationLengthSeconds (T * p, lua_State * L) inline static
References Sprite::GetAnimationLengthSeconds().
Referenced by LunaSprite().
GetNumStates()
static int LunaSprite::GetNumStates (T * p, lua_State * L) inline static
References Sprite::GetNumStates().
Referenced by LunaSprite().
GetState()
static int LunaSprite::GetState (T * p, lua_State * L) inline static
References Sprite::GetState().
Referenced by LunaSprite().
GetTexture()
static int LunaSprite::GetTexture (T * p, lua_State * L) inline static
References Sprite::GetTexture(), and RageTexture::PushSelf().
Referenced by LunaSprite().
Load()
static int LunaSprite::Load (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Sprite::Load(), SArg, and Sprite::UnloadTexture().
Referenced by LunaSprite().
LoadBackground()
static int LunaSprite::LoadBackground (T * p, lua_State * L) inline static
References RageTextureManager::DisableOddDimensionWarning(), RageTextureManager::EnableOddDimensionWarning(), Sprite::Load(), SArg, Sprite::SongBGTexture(), and TEXTUREMAN.
Referenced by LunaSprite().
LoadBanner()
static int LunaSprite::LoadBanner (T * p, lua_State * L) inline static
References RageTextureManager::DisableOddDimensionWarning(), RageTextureManager::EnableOddDimensionWarning(), Sprite::Load(), SArg, Sprite::SongBannerTexture(), and TEXTUREMAN.
Referenced by LunaSprite().
LoadFromCached()
static int LunaSprite::LoadFromCached (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Sprite::LoadFromCached(), and SArg.
Referenced by LunaSprite().
scaletoclipped()
static int LunaSprite::scaletoclipped (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::ScaleToClipped().
Referenced by LunaSprite().
set_use_effect_clock_for_texcoords()
static int LunaSprite::set_use_effect_clock_for_texcoords (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and Sprite::m_use_effect_clock_for_texcoords.
Referenced by LunaSprite().
SetAllStateDelays()
static int LunaSprite::SetAllStateDelays (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetAllStateDelays().
Referenced by LunaSprite().
SetCustomImageRect()
static int LunaSprite::SetCustomImageRect (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetCustomImageRect().
Referenced by LunaSprite().
SetCustomPosCoords()
static int LunaSprite::SetCustomPosCoords (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetCustomPosCoords().
Referenced by LunaSprite().
SetDecodeMovie()
static int LunaSprite::SetDecodeMovie (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and Sprite::m_DecodeMovie.
Referenced by LunaSprite().
SetEffectMode()
static int LunaSprite::SetEffectMode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, and Sprite::SetEffectMode().
Referenced by LunaSprite().
SetSecondsIntoAnimation()
static int LunaSprite::SetSecondsIntoAnimation (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetSecondsIntoAnimation().
Referenced by LunaSprite().
setstate()
static int LunaSprite::setstate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and Sprite::SetState().
Referenced by LunaSprite().
SetStateProperties()
static int LunaSprite::SetStateProperties (T * p, lua_State * L) inline static
References StepMania::Rect< T >::bottom, COMMON_RETURN_SELF, f, FArg, Sprite::State::fDelay, RageTexture::GetNumFrames(), Sprite::GetTexture(), RageTexture::GetTextureCoordRect(), IArg, StepMania::Rect< T >::left, Sprite::State::rect, StepMania::Rect< T >::right, SCALE, Sprite::SetStateProperties(), and StepMania::Rect< T >::top.
Referenced by LunaSprite().
SetTexture()
static int LunaSprite::SetTexture (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, RageTextureManager::CopyTexture(), Sprite::SetTexture(), and TEXTUREMAN.
Referenced by LunaSprite().
StopUsingCustomPosCoords()
static int LunaSprite::StopUsingCustomPosCoords (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Sprite::StopUsingCustomPosCoords().
Referenced by LunaSprite().
stretchtexcoords()
static int LunaSprite::stretchtexcoords (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::StretchTexCoords().
Referenced by LunaSprite().
texcoordvelocity()
static int LunaSprite::texcoordvelocity (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::SetTexCoordVelocity().
Referenced by LunaSprite().
The documentation for this class was generated from the following file:
Sprite.cpp