Etterna: LunaWheelItemBase Class Reference
LunaWheelItemBase Class Reference
Allow Lua to have access to the WheelItemBase.
Public Member Functions
LunaWheelItemBase ()
Public Member Functions inherited from Luna< WheelItemBase >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetColor (T *p, lua_State *L)
static int GetText (T *p, lua_State *L)
static int GetType (T *p, lua_State *L)
static int IsLoaded (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< WheelItemBase >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< WheelItemBase >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< WheelItemBase >
using T = WheelItemBase
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< WheelItemBase >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the WheelItemBase.
Constructor & Destructor Documentation
LunaWheelItemBase()
LunaWheelItemBase::LunaWheelItemBase () inline
References ADD_METHOD, GetColor(), GetText(), GetType(), and IsLoaded().
Member Function Documentation
GetColor()
static int LunaWheelItemBase::GetColor (T * p, lua_State * L) inline static
References WheelItemBase::GetColor(), IS_LOADED_CHECK, and LuaHelpers::Push().
Referenced by LunaWheelItemBase().
GetText()
static int LunaWheelItemBase::GetText (T * p, lua_State * L) inline static
References WheelItemBase::GetText(), IS_LOADED_CHECK, and LuaHelpers::Push().
Referenced by LunaWheelItemBase().
GetType()
static int LunaWheelItemBase::GetType (T * p, lua_State * L) inline static
References WheelItemBase::GetType(), and IS_LOADED_CHECK.
Referenced by LunaWheelItemBase().
IsLoaded()
static int LunaWheelItemBase::IsLoaded (T * p, lua_State * L) inline static
References WheelItemBase::IsLoaded().
Referenced by LunaWheelItemBase().
The documentation for this class was generated from the following file:
WheelItemBase.cpp