Etterna: ScreenEvaluation Class Reference
ScreenEvaluation Class Reference
Shows the player their score after gameplay has ended.
#include <ScreenEvaluation.h>
Public Member Functions
ScreenEvaluation ()
~ScreenEvaluation () override
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
bool Input (const InputEventPlus &input) override
void HandleScreenMessage (ScreenMessage SM) override
bool MenuBack (const InputEventPlus &input) override
bool MenuStart (const InputEventPlus &input) override
void PushSelf (lua_State *L) override
StageStats * GetStageStats ()
Public Member Functions inherited from ScreenWithMenuElements
ScreenWithMenuElements ()
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
~ScreenWithMenuElements () override
void HandleScreenMessage (ScreenMessage SM) override
void Update (float fDeltaTime) override
void StartTransitioningScreen (ScreenMessage smSendWhenDone)
virtual void Cancel (ScreenMessage smSendWhenDone)
bool IsTransitioning ()
bool AllowCallbackInput () override
void StopTimer ()
void ResetTimer ()
virtual void TweenOnScreen ()
virtual void TweenOffScreen ()
void PushSelf (lua_State *L) override
bool AllowLateJoin () const override
Determine if we allow extra players to join in on this screen.
Public Member Functions inherited from Screen
~Screen () override
virtual void EndScreen ()
This is called when the screen is popped.
void SetLockInputSecs (float f)
void PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
void ClearMessageQueue ()
Clear the entire message queue.
void ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
virtual ScreenType GetScreenType () const
bool AllowOperatorMenuButton () const
RString GetNextScreenName () const
RString GetPrevScreen () const
void SetNextScreenName (RString const &name)
void SetPrevScreenName (RString const &name)
bool PassInputToLua (const InputEventPlus &input)
void AddInputCallbackFromStack (lua_State *L)
void RemoveInputCallback (lua_State *L)
virtual bool MenuUp (const InputEventPlus &)
virtual bool MenuDown (const InputEventPlus &)
virtual bool MenuLeft (const InputEventPlus &)
virtual bool MenuRight (const InputEventPlus &)
virtual bool MenuSelect (const InputEventPlus &)
virtual bool MenuCoin (const InputEventPlus &)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void HandleMessage (const Message &msg) override
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Member Functions
void HandleMenuStart ()
Protected Member Functions inherited from ScreenWithMenuElements
RString HandleLuaMusicFile (RString const &path)
virtual void StartPlayingMusic ()
void SetHelpText (const RString &s)
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
bool m_bSummary
StageStats * m_pStageStats
StageStats m_FinalEvalStageStats
Banner m_LargeBanner
AutoActor m_sprLargeBannerFrame
BitmapText m_textPlayerOptions [NUM_PLAYERS]
BitmapText m_textSongOptions
AutoActor m_sprDisqualified [NUM_PLAYERS]
Banner m_SmallBanner [MAX_SONGS_TO_SHOW]
AutoActor m_sprSmallBannerFrame [MAX_SONGS_TO_SHOW]
AutoActor m_sprGradeFrame [NUM_PLAYERS]
GradeDisplay m_Grades [NUM_PLAYERS]
PercentageDisplay m_Percent [NUM_PLAYERS]
AutoActor m_sprPercentFrame [NUM_PLAYERS]
AutoActor m_sprBonusFrame [NUM_PLAYERS]
Sprite m_sprPossibleBar [NUM_PLAYERS][NUM_RadarCategory]
Sprite m_sprActualBar [NUM_PLAYERS][NUM_RadarCategory]
AutoActor m_sprSurvivedFrame [NUM_PLAYERS]
BitmapText m_textSurvivedNumber [NUM_PLAYERS]
AutoActor m_sprWinFrame [NUM_PLAYERS]
Sprite m_sprWin [NUM_PLAYERS]
AutoActor m_sprSharedJudgmentLineLabels [NUM_JudgmentLine]
RollingNumbers m_textJudgmentLineNumber [NUM_JudgmentLine][NUM_PLAYERS]
AutoActor m_sprDetailFrame [NUM_PLAYERS]
BitmapText m_textDetailText [NUM_DetailLine][NUM_PLAYERS]
AutoActor m_sprScoreLabel
RollingNumbers m_textScore [NUM_PLAYERS]
AutoActor m_sprTimeLabel
BitmapText m_textTime [NUM_PLAYERS]
RageSound m_soundStart
ThemeMetric< bool > SUMMARY
ThemeMetric< RString > ROLLING_NUMBERS_CLASS
ThemeMetric< RString > ROLLING_NUMBERS_MAX_COMBO_CLASS
bool m_bSavedScreenshot [NUM_PLAYERS]
Did a player save a screenshot of their score?
Protected Attributes inherited from ScreenWithMenuElements
AutoActor m_sprUnderlay
MenuTimer * m_MenuTimer
AutoActor m_sprOverlay
vector< Actor * > m_vDecorations
Transition m_In
Transition m_Out
Transition m_Cancel
ThemeMetric< bool > PLAY_MUSIC
ThemeMetric< bool > MUSIC_ALIGN_BEAT
ThemeMetric< float > DELAY_MUSIC_SECONDS
ThemeMetric< bool > CANCEL_TRANSITIONS_OUT
ThemeMetric< float > TIMER_SECONDS
ThemeMetric< RString > TIMER_METRICS_GROUP
ThemeMetric< bool > RESET_GAMESTATE
Protected Attributes inherited from Screen
vector< QueuedScreenMessage > m_QueuedMessages
The list of messages that are sent to a Screen.
InputQueueCodeSet m_Codes
ThemeMetric< bool > ALLOW_OPERATOR_MENU_BUTTON
Do we allow the operator menu button to be pressed here?
ThemeMetric< bool > HANDLE_BACK_BUTTON
Do we handle the back button being pressed here?
ThemeMetric< float > REPEAT_RATE
ThemeMetric< float > REPEAT_DELAY
RString m_sNextScreen
The next screen to go to once this screen is done.
RString m_sPrevScreen
ScreenMessage m_smSendOnPop
float m_fLockInputSecs
bool m_bRunning
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Screen
static void InitScreen (Screen *pScreen)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from ScreenWithMenuElements
bool m_bShouldAllowLateJoin
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Member Functions inherited from Screen
static bool SortMessagesByDelayRemaining (const QueuedScreenMessage &m1, const QueuedScreenMessage &m2)
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Detailed Description
Shows the player their score after gameplay has ended.
Constructor & Destructor Documentation
ScreenEvaluation()
ScreenEvaluation::ScreenEvaluation ()
References GAMESTATE, and GameState::m_AdjustTokensBySongCostForFinalStageCheck.
~ScreenEvaluation()
ScreenEvaluation::~ScreenEvaluation () override
References GAMESTATE, and GameState::m_AdjustTokensBySongCostForFinalStageCheck.
Member Function Documentation
GetStageStats()
StageStats* ScreenEvaluation::GetStageStats () inline
References m_pStageStats.
Referenced by LunaScreenEvaluation::GetStageStats().
HandleMenuStart()
void ScreenEvaluation::HandleMenuStart () protected
References MessageManager::Broadcast(), SongID::FromSong(), StepsID::FromSteps(), GAMEMAN, GAMESTATE, ModsGroup< T >::GetCurrent(), ModsGroup< T >::GetPreferred(), ModsGroup< T >::GetSong(), GameManager::m_bResetModifiers, SongOptions::m_fMusicRate, GameManager::m_fPreviousRate, GameState::m_pCurSong, GameState::m_pCurSteps, GameManager::m_sModsToReset, GameState::m_SongOptions, MESSAGEMAN, PLAYER_1, SM_GoToNextScreen, and ScreenWithMenuElements::StartTransitioningScreen().
Referenced by MenuStart().
HandleScreenMessage()
void ScreenEvaluation::HandleScreenMessage (ScreenMessage SM) override virtual
Reimplemented from Screen.
Reimplemented in ScreenNetEvaluation.
References ANNOUNCER, AnnouncerManager::GetPathTo(), ScreenWithMenuElements::HandleScreenMessage(), GameSoundManager::PlayOnceFromDir(), and SOUND.
Referenced by ScreenNetEvaluation::HandleScreenMessage().
Init()
void ScreenEvaluation::Init () override virtual
This is called immediately after construction, to allow initializing after all derived classes exist.
Don't call it directly; use InitScreen instead.
Reimplemented from Screen.
Reimplemented in ScreenNetEvaluation.
References ActorFrame::AddChild(), ANNOUNCER, BANNER_HEIGHT, BANNER_WIDTH, BAR_ACTUAL_MAX_COMMAND, CHECKPOINTS_WITH_JUDGMENTS, CHEER_DELAY_SECONDS, LuaReference::Create(), DEFAULT_FAIL, DETAILLINE_FORMAT, enum_add(), f, StageStats::FinalizeScores(), FOREACH_EnabledPlayer, FOREACH_ENUM, FOREACH_PlayerNumber, PlayerStageStats::FullComboOfScore(), g_MinScoreToMaintainCombo, GameManager::GameAndStringToStyle(), GAMEMAN, GAMESTATE, Song::GetAllSteps(), GameState::GetCurrentStyle(), GameManager::GetDefaultGame(), StatsManager::GetFinalEvalStageStats(), PlayerOptions::GetLocalizedMods(), SongOptions::GetLocalizedString(), PlayerStageStats::GetMaxCombo(), ThemeManager::GetPathF(), ThemeManager::GetPathG(), ThemeManager::GetPathS(), AnnouncerManager::GetPathTo(), ModsGroup< T >::GetPreferred(), SongManager::GetRandomSong(), ModsGroup< T >::GetStage(), GameState::GetStageResult(), Song::GetStepsSeconds(), Actor::GetUnzoomedWidth(), Grade_Failed, Grade_NoData, Grade_Tier01, Grade_Tier02, Grade_Tier03, GradeToOldString(), AnnouncerManager::HasSoundsFor(), HNS_Held, ScreenWithMenuElements::Init(), GameState::IsPlayerEnabled(), Rage::join(), GameState::JoinPlayer(), JudgmentLine_Held, JudgmentLine_MaxCombo, JudgmentLine_Miss, JudgmentLine_W1, JudgmentLine_W2, JudgmentLine_W3, JudgmentLine_W4, JudgmentLine_W5, RollingNumbers::Load(), GradeDisplay::Load(), PercentageDisplay::Load(), AutoActor::Load(), Sprite::Load(), ThemeMetric< T >::Load(), RageSound::Load(), LOAD_ALL_COMMANDS_AND_SET_XY, ActorUtil::LoadAllCommands(), ProfileManager::LoadFirstAvailableProfile(), BitmapText::LoadFromFont(), Banner::LoadFromSong(), LOG, GamePreferences::m_AutoPlay, PlayerStageStats::m_bDisqualified, PlayerStageStats::m_bFailed, m_bSavedScreenshot, PlayerStageStats::Combo_t::m_cnt, StatsManager::m_CurStageStats, PlayerOptions::m_FailType, PlayerStageStats::m_fAliveSeconds, m_FinalEvalStageStats, PlayerStageStats::m_fLifeRemainingSeconds, m_Grades, PlayerStageStats::m_HighScore, PlayerStageStats::m_iActualDancePoints, PlayerStageStats::m_iCurCombo, GameState::m_iCurrentStageIndex, PlayerStageStats::m_iHoldNoteScores, PlayerStageStats::m_iMachineHighScoreIndex, PlayerStageStats::m_iPersonalHighScoreIndex, GameState::m_iPlayerStageTokens, PlayerStageStats::m_iPossibleDancePoints, PlayerStageStats::m_iPossibleGradePoints, PlayerStageStats::m_iScore, PlayerStageStats::m_iSongsPassed, PlayerStageStats::m_iStepsPlayed, PlayerStageStats::m_iTapNoteScores, m_LargeBanner, GameState::m_pCurSong, GameState::m_pCurSteps, PlayerStageStats::m_PeakComboAward, m_Percent, StageStats::m_player, PlayerState::m_PlayerOptions, StageStats::m_playMode, GameState::m_PlayMode, GameState::m_pPlayerState, m_pStageStats, PlayerStageStats::m_pStyle, PlayerStageStats::m_radarActual, PlayerStageStats::m_radarPossible, m_SmallBanner, Actor::m_sName, GameState::m_SongOptions, m_soundStart, m_sprActualBar, m_sprBonusFrame, m_sprDetailFrame, m_sprDisqualified, m_sprGradeFrame, m_sprLargeBannerFrame, m_sprPercentFrame, m_sprPossibleBar, m_sprScoreLabel, m_sprSharedJudgmentLineLabels, m_sprSmallBannerFrame, m_sprSurvivedFrame, m_sprTimeLabel, m_sprWin, m_sprWinFrame, StageStats::m_Stage, PlayerStageStats::m_StageAward, PrefsManager::m_sTestInitialScreen, m_textDetailText, m_textJudgmentLineNumber, m_textPlayerOptions, m_textScore, m_textSongOptions, m_textSurvivedNumber, m_textTime, StatsManager::m_vPlayedStageStats, StageStats::m_vpPlayedSongs, StageStats::m_vpPossibleSongs, PlayerStageStats::m_vpPossibleSteps, MAX_SONGS_TO_SHOW, min(), ModsLevel_Stage, NUM_DetailLine, NUM_PeakComboAward, NUM_PLAYERS, NUM_SHOWN_RADAR_CATEGORIES, NUM_StageAward, PC_REPLAY, PLAY_MODE_REGULAR, PLAYER_1, PLAYER_2, PLAYER_INVALID, PLAYER_OPTIONS_HIDE_FAIL_TYPE, PLAYER_OPTIONS_SEPARATOR, GameSoundManager::PlayOnceFromDir(), PO_GROUP_ASSIGN, PO_GROUP_ASSIGN_N, PO_GROUP_CALL, Screen::PostScreenMessage(), PREFSMAN, PROFILEMAN, RadarCategory_Fakes, RadarCategory_Hands, RadarCategory_Holds, RadarCategory_Jumps, RadarCategory_Lifts, RadarCategory_Mines, RadarCategory_Rolls, RadarCategory_TapsAndHolds, random_up_to(), randomf(), RandomInt(), LuaHelpers::ReportScriptError(), ROLLING_NUMBERS_CLASS, ROLLING_NUMBERS_MAX_COMBO_CLASS, Actor::RunCommands(), Sprite::ScaleToClipped(), SecondsToMMSSMsMs(), BroadcastOnChange< T >::Set(), BroadcastOnChangePtr< T >::Set(), SET_XY, GameState::SetCurrentStyle(), GradeDisplay::SetGrade(), PlayerStageStats::SetLifeRecordAt(), GameState::SetMasterPlayerNumber(), Actor::SetName(), HighScore::SetRadarValues(), Actor::SetShadowLength(), Sprite::SetState(), RollingNumbers::SetTargetNumber(), BitmapText::SetText(), Actor::SetVisible(), Actor::SetWidth(), SHOW_BANNER_AREA, SHOW_BONUS_AREA, SHOW_DETAIL_AREA, SHOW_GRADE_AREA, SHOW_JUDGMENT_LINE, SHOW_POINTS_AREA, SHOW_SCORE_AREA, SHOW_SHARED_JUDGMENT_LINE_LABELS, SHOW_SURVIVED_AREA, SHOW_TIME_AREA, SHOW_WIN_AREA, GameState::ShowW1(), SO_GROUP_ASSIGN, SONGMAN, SOUND, ssprintf(), Stage_1st, STATSMAN, Actor::StopAnimating(), SUMMARY, ScoreKeeperNormal::TapNoteScoreToGradePoints(), THEME, TNS_CheckpointHit, TNS_CheckpointMiss, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, RageLog::Trace(), PlayerOptions::TRANSFORM_ECHO, PlayerStageStats::UpdateComboList(), and ZERO.
Referenced by ScreenNetEvaluation::Init().
Input()
bool ScreenEvaluation::Input (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References Profile::AddScreenshot(), BinaryToHex(), CODE_SAVE_SCREENSHOT1, CODE_SAVE_SCREENSHOT2, GameInput::controller, CRYPTMAN, CodeDetector::EnteredCode(), InputEventPlus::GameI, CryptManager::GetMD5ForFile(), ProfileManager::GetProfile(), ProfileManager::GetProfileDir(), Screenshot::highScore, Screen::Input(), ProfileManager::IsPersistentProfile(), ScreenWithMenuElements::IsTransitioning(), GameInput::IsValid(), m_bSavedScreenshot, PlayerStageStats::m_HighScore, StageStats::m_player, m_pStageStats, InputEventPlus::pn, PROFILEMAN, StepMania::SaveScreenshot(), Screenshot::sFileName, and Screenshot::sMD5.
MenuBack()
bool ScreenEvaluation::MenuBack (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References MenuStart().
MenuStart()
bool ScreenEvaluation::MenuStart (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References HandleMenuStart(), ScreenWithMenuElements::IsTransitioning(), m_soundStart, and RageSound::Play().
Referenced by MenuBack().
PushSelf()
void ScreenEvaluation::PushSelf (lua_State * L) override virtual
Reimplemented from Screen.
Reimplemented in ScreenNetEvaluation.
Member Data Documentation
m_bSavedScreenshot
bool ScreenEvaluation::m_bSavedScreenshot[NUM_PLAYERS] protected
Did a player save a screenshot of their score?
Referenced by Init(), and Input().
m_bSummary
bool ScreenEvaluation::m_bSummary protected
m_FinalEvalStageStats
StageStats ScreenEvaluation::m_FinalEvalStageStats protected
Referenced by Init().
m_Grades
GradeDisplay ScreenEvaluation::m_Grades[NUM_PLAYERS] protected
Referenced by Init(), and ScreenNetEvaluation::UpdateStats().
m_LargeBanner
Banner ScreenEvaluation::m_LargeBanner protected
Referenced by Init().
m_Percent
PercentageDisplay ScreenEvaluation::m_Percent[NUM_PLAYERS] protected
Referenced by Init().
m_pStageStats
StageStats* ScreenEvaluation::m_pStageStats protected
Referenced by GetStageStats(), Init(), and Input().
m_SmallBanner
Banner ScreenEvaluation::m_SmallBanner[MAX_SONGS_TO_SHOW] protected
Referenced by Init().
m_soundStart
RageSound ScreenEvaluation::m_soundStart protected
Referenced by Init(), and MenuStart().
m_sprActualBar
Sprite ScreenEvaluation::m_sprActualBar[NUM_PLAYERS][NUM_RadarCategory] protected
Referenced by Init().
m_sprBonusFrame
AutoActor ScreenEvaluation::m_sprBonusFrame[NUM_PLAYERS] protected
Referenced by Init().
m_sprDetailFrame
AutoActor ScreenEvaluation::m_sprDetailFrame[NUM_PLAYERS] protected
Referenced by Init().
m_sprDisqualified
AutoActor ScreenEvaluation::m_sprDisqualified[NUM_PLAYERS] protected
Referenced by Init().
m_sprGradeFrame
AutoActor ScreenEvaluation::m_sprGradeFrame[NUM_PLAYERS] protected
Referenced by Init().
m_sprLargeBannerFrame
AutoActor ScreenEvaluation::m_sprLargeBannerFrame protected
Referenced by Init().
m_sprPercentFrame
AutoActor ScreenEvaluation::m_sprPercentFrame[NUM_PLAYERS] protected
Referenced by Init().
m_sprPossibleBar
Sprite ScreenEvaluation::m_sprPossibleBar[NUM_PLAYERS][NUM_RadarCategory] protected
Referenced by Init().
m_sprScoreLabel
AutoActor ScreenEvaluation::m_sprScoreLabel protected
Referenced by Init().
m_sprSharedJudgmentLineLabels
AutoActor ScreenEvaluation::m_sprSharedJudgmentLineLabels[NUM_JudgmentLine] protected
Referenced by Init().
m_sprSmallBannerFrame
AutoActor ScreenEvaluation::m_sprSmallBannerFrame[MAX_SONGS_TO_SHOW] protected
Referenced by Init().
m_sprSurvivedFrame
AutoActor ScreenEvaluation::m_sprSurvivedFrame[NUM_PLAYERS] protected
Referenced by Init().
m_sprTimeLabel
AutoActor ScreenEvaluation::m_sprTimeLabel protected
Referenced by Init().
m_sprWin
Sprite ScreenEvaluation::m_sprWin[NUM_PLAYERS] protected
Referenced by Init().
m_sprWinFrame
AutoActor ScreenEvaluation::m_sprWinFrame[NUM_PLAYERS] protected
Referenced by Init().
m_textDetailText
BitmapText ScreenEvaluation::m_textDetailText[NUM_DetailLine][NUM_PLAYERS] protected
Referenced by Init().
m_textJudgmentLineNumber
RollingNumbers ScreenEvaluation::m_textJudgmentLineNumber[NUM_JudgmentLine][NUM_PLAYERS] protected
Referenced by Init(), and ScreenNetEvaluation::UpdateStats().
m_textPlayerOptions
BitmapText ScreenEvaluation::m_textPlayerOptions[NUM_PLAYERS] protected
Referenced by Init(), and ScreenNetEvaluation::UpdateStats().
m_textScore
RollingNumbers ScreenEvaluation::m_textScore[NUM_PLAYERS] protected
Referenced by Init(), and ScreenNetEvaluation::UpdateStats().
m_textSongOptions
BitmapText ScreenEvaluation::m_textSongOptions protected
Referenced by Init().
m_textSurvivedNumber
BitmapText ScreenEvaluation::m_textSurvivedNumber[NUM_PLAYERS] protected
Referenced by Init().
m_textTime
BitmapText ScreenEvaluation::m_textTime[NUM_PLAYERS] protected
Referenced by Init().
ROLLING_NUMBERS_CLASS
ThemeMetric<RString> ScreenEvaluation::ROLLING_NUMBERS_CLASS protected
Referenced by Init().
ROLLING_NUMBERS_MAX_COMBO_CLASS
ThemeMetric<RString> ScreenEvaluation::ROLLING_NUMBERS_MAX_COMBO_CLASS protected
Referenced by Init().
SUMMARY
ThemeMetric<bool> ScreenEvaluation::SUMMARY protected
Referenced by Init().
The documentation for this class was generated from the following files:
ScreenEvaluation.h
ScreenEvaluation.cpp