Etterna: SMWindowDelegate Class Reference
SMWindowDelegate Class Reference
Instance Methods
(void) - windowDidBecomeKey:
(void) - windowDidResignKey:
(void) - windowWillClose:
(void) - windowDidResize:
(void) - setupWindow
(void) - closeWindow
(void) - setParams:
Public Attributes
NSWindow * m_Window
Method Documentation
closeWindow()
- (void) closeWindow
References m_Window.
setParams:()
- (void) setParams: (NSValue *) params
References VideoModeParams::height, m_Window, and VideoModeParams::width.
setupWindow()
- (void) setupWindow
References m_Window.
windowDidBecomeKey:()
- (void) windowDidBecomeKey: (NSNotification *) aNotification
References HOOKS, and ArchHooks::SetHasFocus().
windowDidResignKey:()
- (void) windowDidResignKey: (NSNotification *) aNotification
References HOOKS, and ArchHooks::SetHasFocus().
windowDidResize:()
- (void) windowDidResize: (NSNotification *) aNotification
References g_bResized, g_iHeight, g_iWidth, g_ResizeLock, LockMut, and window.
windowWillClose:()
- (void) windowWillClose: (NSNotification *) aNotification
References ArchHooks::SetUserQuit().
Member Data Documentation
m_Window
- (NSWindow*) m_Window
Referenced by closeWindow, setParams:, and setupWindow.
The documentation for this class was generated from the following file:
LowLevelWindow_MacOSX.mm