Etterna: CodeDetector Class Reference
CodeDetector Class Reference
#include <CodeDetector.h>
Public Member Functions
void ChangeScrollSpeed (GameController controller, bool bIncrement)
Static Public Member Functions
static void RefreshCacheItems (RString sClass="")
static bool EnteredPrevSteps (GameController controller)
static bool EnteredNextSteps (GameController controller)
static bool EnteredNextSort (GameController controller)
static bool EnteredModeMenu (GameController controller)
static bool DetectAndAdjustMusicOptions (GameController controller)
static bool EnteredCode (GameController controller, Code code)
static bool EnteredPrevGroup (GameController controller)
static bool EnteredNextGroup (GameController controller)
static bool EnteredCloseFolder (GameController controller)
Member Function Documentation
ChangeScrollSpeed()
void CodeDetector::ChangeScrollSpeed (GameController controller, bool bIncrement)
References InputMapper::ControllerToPlayerNumber(), PlayerOptions::FromString(), GAMESTATE, ModsGroup< T >::GetPreferred(), INPUTMAPPER, PlayerState::m_PlayerOptions, and GameState::m_pPlayerState.
DetectAndAdjustMusicOptions()
bool CodeDetector::DetectAndAdjustMusicOptions (GameController controller) static
References PlayerOptions::APPEARANCE_HIDDEN, PlayerOptions::APPEARANCE_RANDOMVANISH, ModsGroup< T >::Assign(), CODE_BACKWARDS, CODE_CANCEL_ALL, CODE_DARK, CODE_HIDDEN, CODE_HOLDS, CODE_LEFT, CODE_MINES, CODE_MIRROR, CODE_NEXT_ACCEL, CODE_NEXT_APPEARANCE, CODE_NEXT_EFFECT, CODE_NEXT_SCROLL_SPEED, CODE_NEXT_TRANSFORM, CODE_NEXT_TURN, CODE_PREVIOUS_SCROLL_SPEED, CODE_RANDOMVANISH, CODE_REVERSE, CODE_RIGHT, CODE_SHUFFLE, CODE_SUPER_SHUFFLE, InputMapper::ControllerToPlayerNumber(), DECREMENT_SCROLL_SPEED, EnteredCode(), FLOAT_TOGGLE, GAMESTATE, GameState::GetDefaultPlayerOptions(), ModsGroup< T >::GetPreferred(), INCREMENT_SCROLL_SPEED, INPUTMAPPER, LOG, PlayerOptions::m_bTransforms, PlayerOptions::m_fAppearances, PlayerOptions::m_fDark, PlayerOptions::m_fScrollSpeed, PlayerState::m_PlayerOptions, GameState::m_pPlayerState, ModsLevel_Preferred, PlayerOptions::NextAccel(), PlayerOptions::NextAppearance(), PlayerOptions::NextEffect(), PlayerOptions::NextScroll(), PlayerOptions::NextTransform(), PlayerOptions::NextTurn(), NUM_PlayerNumber, TOGGLE, PlayerOptions::ToggleOneTurn(), PlayerOptions::TRANSFORM_NOHOLDS, PlayerOptions::TRANSFORM_NOMINES, PlayerOptions::TURN_BACKWARDS, PlayerOptions::TURN_LEFT, PlayerOptions::TURN_MIRROR, PlayerOptions::TURN_RIGHT, PlayerOptions::TURN_SHUFFLE, PlayerOptions::TURN_SUPER_SHUFFLE, RageLog::Warn(), and ZERO.
Referenced by ScreenSelectMusic::DetectCodes().
EnteredCloseFolder()
bool CodeDetector::EnteredCloseFolder (GameController controller) static
References CODE_CLOSE_CURRENT_FOLDER, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredCode()
bool CodeDetector::EnteredCode (GameController controller, Code code) static
References InputQueueCode::EnteredCode().
Referenced by DetectAndAdjustMusicOptions(), EnteredCloseFolder(), EnteredModeMenu(), EnteredNextGroup(), EnteredNextSort(), EnteredNextSteps(), EnteredPrevGroup(), EnteredPrevSteps(), HandleInputEvents(), ScreenPlayerOptions::Input(), ScreenTitleMenu::Input(), and ScreenEvaluation::Input().
EnteredModeMenu()
bool CodeDetector::EnteredModeMenu (GameController controller) static
References CODE_MODE_MENU1, CODE_MODE_MENU2, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredNextGroup()
bool CodeDetector::EnteredNextGroup (GameController controller) static
References CODE_NEXT_GROUP, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredNextSort()
bool CodeDetector::EnteredNextSort (GameController controller) static
References CODE_NEXT_SORT1, CODE_NEXT_SORT2, CODE_NEXT_SORT3, CODE_NEXT_SORT4, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredNextSteps()
bool CodeDetector::EnteredNextSteps (GameController controller) static
References Code_NextSteps1, Code_NextSteps2, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredPrevGroup()
bool CodeDetector::EnteredPrevGroup (GameController controller) static
References CODE_PREV_GROUP, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
EnteredPrevSteps()
bool CodeDetector::EnteredPrevSteps (GameController controller) static
References Code_PrevSteps1, Code_PrevSteps2, and EnteredCode().
Referenced by ScreenSelectMusic::DetectCodes().
RefreshCacheItems()
void CodeDetector::RefreshCacheItems (RString sClass = "") static
References FOREACH_ENUM, ThemeManager::GetMetric(), InputQueueCode::Load(), and THEME.
Referenced by DebugLineReloadTheme::DoAndLog(), HandleGlobalInputs(), ScreenSelectMusic::HandleScreenMessage(), and sm_main().
The documentation for this class was generated from the following files:
CodeDetector.h
CodeDetector.cpp