Etterna: FontManager Class Reference
FontManager Class Reference
#include <FontManager.h>
Public Member Functions
FontManager ()
~FontManager ()
Font * LoadFont (const RString &sFontOrTextureFilePath, RString sChars="")
Font * CopyFont (Font *pFont)
void UnloadFont (Font *fp)
Constructor & Destructor Documentation
FontManager()
FontManager::FontManager () default
~FontManager()
FontManager::~FontManager ()
References g_mapPathToFont, LOG, Font::m_iRefCount, and RageLog::Trace().
Member Function Documentation
CopyFont()
Font * FontManager::CopyFont (Font * pFont)
References Font::m_iRefCount.
Referenced by BitmapText::operator=().
LoadFont()
Font * FontManager::LoadFont (const RString & sFontOrTextureFilePath, RString sChars = "")
References CHECKPOINT_M, f, g_mapPathToFont, Font::m_iRefCount, and ssprintf().
Referenced by BitmapText::LoadFromFont(), and BitmapText::LoadFromTextureAndChars().
UnloadFont()
void FontManager::UnloadFont (Font * fp)
References ASSERT_M, CHECKPOINT_M, FAIL_M, g_mapPathToFont, Font::m_iRefCount, Font::path, and ssprintf().
Referenced by BitmapText::LoadFromFont(), BitmapText::LoadFromTextureAndChars(), BitmapText::operator=(), and BitmapText::~BitmapText().
The documentation for this class was generated from the following files:
FontManager.h
FontManager.cpp