Etterna: NoteData Class Reference
NoteData Class Reference
Holds data about the notes that the player is supposed to hit.
#include <NoteData.h>
Classes
class _all_tracks_iterator
Public Types
typedef map< int, TapNote > TrackMap
typedef map< int, TapNote >::iterator iterator
typedef map< int, TapNote >::const_iterator const_iterator
typedef map< int, TapNote >::reverse_iterator reverse_iterator
typedef map< int, TapNote >::const_reverse_iterator const_reverse_iterator
typedef _all_tracks_iterator< NoteData, NoteData::iterator, TapNote > all_tracks_iterator
typedef _all_tracks_iterator< const NoteData, NoteData::const_iterator, const TapNote > all_tracks_const_iterator
using all_tracks_reverse_iterator = all_tracks_iterator
using all_tracks_const_reverse_iterator = all_tracks_const_iterator
Public Member Functions
NoteData ()
iterator begin (int iTrack)
const_iterator begin (int iTrack) const
reverse_iterator rbegin (int iTrack)
const_reverse_iterator rbegin (int iTrack) const
iterator end (int iTrack)
const_iterator end (int iTrack) const
reverse_iterator rend (int iTrack)
const_reverse_iterator rend (int iTrack) const
iterator lower_bound (int iTrack, int iRow)
const_iterator lower_bound (int iTrack, int iRow) const
iterator upper_bound (int iTrack, int iRow)
const_iterator upper_bound (int iTrack, int iRow) const
void swap (NoteData &nd)
void Init ()
void LogNonEmptyRows ()
void UnsetNerv ()
void UnsetSerializedNoteData ()
void UnsetSerializedNoteData2 ()
const vector< int > & BuildAndGetNerv ()
int WifeTotalScoreCalc (TimingData *td, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
vector< int > & GetNonEmptyRowVector ()
const vector< NoteInfo > & SerializeNoteData (const vector< float > &etaner)
vector< NoteInfo2 > & SerializeNoteData2 (const vector< float > &etaner)
int GetNumTracks () const
void SetNumTracks (int iNewNumTracks)
bool operator== (const NoteData &nd) const
bool operator!= (const NoteData &nd) const
const TapNote & GetTapNote (const unsigned &track, const int &row) const
iterator FindTapNote (unsigned iTrack, int iRow)
const_iterator FindTapNote (unsigned iTrack, int iRow) const
void RemoveTapNote (unsigned iTrack, iterator it)
void GetTapNoteRange (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator &begin, TrackMap::const_iterator &end) const
Return an iterator range for [rowBegin,rowEnd).
void GetTapNoteRange (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator &begin, TrackMap::iterator &end)
Return a constant iterator range for [rowBegin,rowEnd).
all_tracks_iterator GetTapNoteRangeAllTracks (int iStartRow, int iEndRow, bool bInclusive=false)
all_tracks_const_iterator GetTapNoteRangeAllTracks (int iStartRow, int iEndRow, bool bInclusive=false) const
all_tracks_reverse_iterator GetTapNoteRangeAllTracksReverse (int iStartRow, int iEndRow, bool bInclusive=false)
all_tracks_const_reverse_iterator GetTapNoteRangeAllTracksReverse (int iStartRow, int iEndRow, bool bInclusive=false) const
void RevalidateATIs (vector< int > const &added_or_removed_tracks, bool added)
void TransferATIs (NoteData &to)
void GetTapNoteRangeInclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator &begin, TrackMap::const_iterator &end, bool bIncludeAdjacent=false) const
void GetTapNoteRangeInclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator &begin, TrackMap::iterator &end, bool bIncludeAdjacent=false)
void GetTapNoteRangeExclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator &begin, TrackMap::const_iterator &end) const
void GetTapNoteRangeExclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator &begin, TrackMap::iterator &end)
bool GetNextTapNoteRowForTrack (int track, int &rowInOut, bool ignoreKeySounds=false) const
bool GetNextTapNoteRowForAllTracks (int &rowInOut) const
bool GetPrevTapNoteRowForTrack (int track, int &rowInOut) const
bool GetPrevTapNoteRowForAllTracks (int &rowInOut) const
void MoveTapNoteTrack (int dest, int src)
void SetTapNote (int track, int row, const TapNote &tn)
void AddHoldNote (int iTrack, int iStartRow, int iEndRow, TapNote tn)
Add a hold note, merging other overlapping holds and destroying tap notes underneath.
void ClearRangeForTrack (int rowBegin, int rowEnd, int iTrack)
void ClearRange (int rowBegin, int rowEnd)
void ClearAll ()
void CopyRange (const NoteData &from, int rowFromBegin, int rowFromEnd, int rowToBegin=0)
void CopyAll (const NoteData &from)
bool IsRowEmpty (int row) const
bool IsRangeEmpty (int track, int rowBegin, int rowEnd) const
int GetNumTapNonEmptyTracks (int row) const
void GetTapNonEmptyTracks (int row, set< int > &addTo) const
bool GetTapFirstNonEmptyTrack (int row, int &iNonEmptyTrackOut) const
bool GetTapFirstEmptyTrack (int row, int &iEmptyTrackOut) const
bool GetTapLastEmptyTrack (int row, int &iEmptyTrackOut) const
int GetNumTracksWithTap (int row) const
int GetNumTracksWithTapOrHoldHead (int row) const
int GetFirstTrackWithTap (int row) const
int GetFirstTrackWithTapOrHoldHead (int row) const
int GetLastTrackWithTapOrHoldHead (int row) const
bool IsThereATapAtRow (int row) const
bool IsThereATapOrHoldHeadAtRow (int row) const
void GetTracksHeldAtRow (int row, set< int > &addTo)
int GetNumTracksHeldAtRow (int row)
bool IsHoldNoteAtRow (int iTrack, int iRow, int *pHeadRow=NULL) const
bool IsHoldHeadOrBodyAtRow (int iTrack, int iRow, int *pHeadRow) const
bool IsEmpty () const
bool IsTrackEmpty (int iTrack) const
int GetFirstRow () const
int GetLastRow () const
float GetFirstBeat () const
float GetLastBeat () const
int GetNumTapNotes (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumTapNotesNoTiming (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumTapNotesInRow (int iRow) const
int GetNumMines (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumRowsWithTap (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumRowsWithTapOrHoldHead (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumHoldNotes (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumRolls (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumRowsWithSimultaneousTaps (int iMinTaps, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumJumps (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
bool RowNeedsAtLeastSimultaneousPresses (int iMinSimultaneousPresses, int row) const
bool RowNeedsHands (int row) const
int GetNumRowsWithSimultaneousPresses (int iMinSimultaneousPresses, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumHands (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumQuads (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumLifts (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
int GetNumFakes (int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW) const
pair< int, int > GetNumTapNotesTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumJumpsTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumHandsTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumQuadsTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumHoldNotesTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumMinesTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumRollsTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumLiftsTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
pair< int, int > GetNumFakesTwoPlayer (int startRow=0, int endRow=MAX_NOTE_ROW) const
int GetNumTracksLCD () const
void LoadTransformed (const NoteData &original, int iNewNumTracks, const int iOriginalTrackToTakeFrom[])
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
Private Member Functions
void CalcNumTracksLCD ()
bool IsPlayer1 (int track, const TapNote &tn) const
Determine whether this note is for Player 1 or Player 2.
bool IsTap (const TapNote &tn, int row) const
Determine if the note in question should be counted as a tap.
bool IsMine (const TapNote &tn, int row) const
Determine if the note in question should be counted as a mine.
bool IsLift (const TapNote &tn, int row) const
Determine if the note in question should be counted as a lift.
bool IsFake (const TapNote &tn, int row) const
Determine if the note in question should be counted as a fake.
pair< int, int > GetNumRowsWithSimultaneousTapsTwoPlayer (int minTaps=2, int startRow=0, int endRow=MAX_NOTE_ROW) const
void AddATIToList (all_tracks_iterator *iter) const
void AddATIToList (all_tracks_const_iterator *iter) const
void RemoveATIFromList (all_tracks_iterator *iter) const
void RemoveATIFromList (all_tracks_const_iterator *iter) const
Private Attributes
vector< TrackMap > m_TapNotes
int m_numTracksLCD
set< all_tracks_iterator * > m_atis
set< all_tracks_const_iterator * > m_const_atis
vector< int > NonEmptyRowVector
vector< NoteInfo > SerializedNoteData
vector< NoteInfo2 > SerializedNoteData2
Friends
class _all_tracks_iterator< NoteData, NoteData::iterator, TapNote >
class _all_tracks_iterator< const NoteData, NoteData::const_iterator, const TapNote >
Detailed Description
Holds data about the notes that the player is supposed to hit.
Member Typedef Documentation
all_tracks_const_iterator
typedef _all_tracks_iterator<const NoteData, NoteData::const_iterator, const TapNote> NoteData::all_tracks_const_iterator
all_tracks_const_reverse_iterator
using NoteData::all_tracks_const_reverse_iterator = all_tracks_const_iterator
all_tracks_iterator
typedef _all_tracks_iterator<NoteData, NoteData::iterator, TapNote> NoteData::all_tracks_iterator
all_tracks_reverse_iterator
using NoteData::all_tracks_reverse_iterator = all_tracks_iterator
const_iterator
typedef map<int, TapNote>::const_iterator NoteData::const_iterator
const_reverse_iterator
typedef map<int, TapNote>::const_reverse_iterator NoteData::const_reverse_iterator
iterator
typedef map<int, TapNote>::iterator NoteData::iterator
reverse_iterator
typedef map<int, TapNote>::reverse_iterator NoteData::reverse_iterator
TrackMap
typedef map<int, TapNote> NoteData::TrackMap
Constructor & Destructor Documentation
NoteData()
NoteData::NoteData () inline
Member Function Documentation
AddATIToList() [1/2]
void NoteData::AddATIToList (all_tracks_iterator * iter) const private
References m_atis.
AddATIToList() [2/2]
void NoteData::AddATIToList (all_tracks_const_iterator * iter) const private
AddHoldNote()
void NoteData::AddHoldNote (int iTrack, int iStartRow, int iEndRow, TapNote tn)
Add a hold note, merging other overlapping holds and destroying tap notes underneath.
Parameters
iTrack the column to work with.
iStartRow the starting row.
iEndRow the ending row.
tn the tap note.
References ASSERT, ASSERT_M, GetTapNoteRangeInclusive(), TapNote::iDuration, max(), min(), RemoveTapNote(), SetTapNote(), ssprintf(), TAP_EMPTY, TapNoteType_HoldHead, and TapNote::type.
Referenced by NoteDataUtil::ConvertTapsToHolds(), CopyRange(), LoadFromKSFFile(), OsuLoader::LoadNoteDataFromParsedData(), and BMSChartReader::ReadNoteData().
begin() [1/2]
iterator NoteData::begin (int iTrack) inline
References m_TapNotes.
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator(), GetTapNoteRangeExclusive(), GetTapNoteRangeInclusive(), NoteDataUtil::InsertHoldTails(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::RemoveAllButPlayer(), NoteDataUtil::RemoveAllTapsExceptForType(), NoteDataUtil::RemoveAllTapsOfType(), NoteData::_all_tracks_iterator< ND, iter, TN >::Revalidate(), NoteDataUtil::Scale(), and NoteDataUtil::ScaleRegion().
begin() [2/2]
const_iterator NoteData::begin (int iTrack) const inline
References m_TapNotes.
BuildAndGetNerv()
const vector<int>& NoteData::BuildAndGetNerv () inline
References LogNonEmptyRows(), and NonEmptyRowVector.
Referenced by Steps::CalcEtternaMetadata().
CalcNumTracksLCD()
void NoteData::CalcNumTracksLCD () private
References GetNumTracks(), and m_numTracksLCD.
Referenced by SetNumTracks().
ClearAll()
void NoteData::ClearAll ()
References GetNumTracks(), and m_TapNotes.
Referenced by Steps::GetNoteData().
ClearRange()
void NoteData::ClearRange (int rowBegin, int rowEnd)
References ClearRangeForTrack(), and GetNumTracks().
Referenced by CopyRange(), NoteDataUtil::DeleteRows(), and NoteDataUtil::InsertRows().
ClearRangeForTrack()
void NoteData::ClearRangeForTrack (int rowBegin, int rowEnd, int iTrack)
References GetTapNoteRangeInclusive(), TapNote::iDuration, m_TapNotes, MAX_NOTE_ROW, SetTapNote(), TAP_EMPTY, TapNoteType_HoldHead, and TapNote::type.
Referenced by NoteDataUtil::ClearLeft(), ClearRange(), NoteDataUtil::ClearRight(), and NoteDataUtil::SnapToNearestNoteType().
CopyAll()
void NoteData::CopyAll (const NoteData & from)
Referenced by BeginnerHelper::AddPlayer(), NoteDataUtil::ArbitraryRemap(), NoteDataUtil::SwapUpDown(), and NoteDataUtil::Turn().
CopyRange()
void NoteData::CopyRange (const NoteData & from, int rowFromBegin, int rowFromEnd, int rowToBegin = 0)
References AddHoldNote(), ASSERT, clamp, ClearRange(), GetNumTracks(), GetTapNoteRangeInclusive(), Rage::head(), TapNote::iDuration, SetTapNote(), TapNoteType_Empty, TapNoteType_HoldHead, and TapNote::type.
Referenced by NoteDataUtil::DeleteRows(), and NoteDataUtil::InsertRows().
CreateNode()
XNode * NoteData::CreateNode () const
References XNode::AppendAttr(), XNode::AppendChild(), GetLastRow(), GetTapNoteRangeAllTracks(), NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), and NoteData::_all_tracks_iterator< ND, iter, TN >::Track().
end() [1/2]
iterator NoteData::end (int iTrack) inline
References m_TapNotes.
Referenced by NoteData::_all_tracks_iterator< ND, iter, TN >::_all_tracks_iterator(), NoteDataUtil::CollapseToOne(), GetTapNoteRangeInclusive(), Player::HideNote(), NoteDataUtil::InsertHoldTails(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::RemoveAllButOneTap(), NoteDataUtil::RemoveAllButPlayer(), NoteDataUtil::RemoveAllTapsExceptForType(), NoteDataUtil::RemoveAllTapsOfType(), Player::RenderAllNotesIgnoreScores(), NoteData::_all_tracks_iterator< ND, iter, TN >::Revalidate(), NoteDataUtil::Scale(), NoteDataUtil::ScaleRegion(), Player::SetJudgment(), and Player::Step().
end() [2/2]
const_iterator NoteData::end (int iTrack) const inline
References m_TapNotes.
FindTapNote() [1/2]
iterator NoteData::FindTapNote (unsigned iTrack, int iRow) inline
References m_TapNotes.
Referenced by NoteDataUtil::CollapseToOne(), Player::HideNote(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::RemoveAllButOneTap(), Player::RenderAllNotesIgnoreScores(), Player::SetJudgment(), and Player::Step().
FindTapNote() [2/2]
const_iterator NoteData::FindTapNote (unsigned iTrack, int iRow) const inline
References m_TapNotes.
GetFirstBeat()
float NoteData::GetFirstBeat () const inline
References GetFirstRow(), and NoteRowToBeat().
GetFirstRow()
int NoteData::GetFirstRow () const
References GetNextTapNoteRowForTrack(), GetNumTracks(), and min().
Referenced by GetFirstBeat().
GetFirstTrackWithTap()
int NoteData::GetFirstTrackWithTap (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_Lift, TapNoteType_Tap, and TapNote::type.
Referenced by NoteDataUtil::Echo(), IsThereATapAtRow(), and NoteDataUtil::Wide().
GetFirstTrackWithTapOrHoldHead()
int NoteData::GetFirstTrackWithTapOrHoldHead (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Tap, and TapNote::type.
Referenced by IsThereATapOrHoldHeadAtRow(), and Player::UpdateJudgedRows().
GetLastBeat()
float NoteData::GetLastBeat () const inline
References GetLastRow(), and NoteRowToBeat().
Referenced by WriteDWINotesField().
GetLastRow()
int NoteData::GetLastRow () const
References GetNumTracks(), GetPrevTapNoteRowForTrack(), GetTapNote(), TapNote::iDuration, max(), MAX_NOTE_ROW, TapNoteType_HoldHead, and TapNote::type.
Referenced by NoteDataUtil::Backwards(), CreateNode(), NoteDataUtil::Echo(), GetLastBeat(), NoteDataUtil::GetTotalHoldTicks(), Player::Load(), and Player::RenderAllNotesIgnoreScores().
GetLastTrackWithTapOrHoldHead()
int NoteData::GetLastTrackWithTapOrHoldHead (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Tap, and TapNote::type.
GetNextTapNoteRowForAllTracks()
bool NoteData::GetNextTapNoteRowForAllTracks (int & rowInOut) const
References ASSERT, GetNextTapNoteRowForTrack(), GetNumTracks(), MAX_NOTE_ROW, and min().
Referenced by NoteDataUtil::GetNextEditorPosition().
GetNextTapNoteRowForTrack()
bool NoteData::GetNextTapNoteRowForTrack (int track, int & rowInOut, bool ignoreKeySounds = false) const
References ASSERT, m_TapNotes, and TapNoteType_AutoKeysound.
Referenced by GetFirstRow(), GetNextTapNoteRowForAllTracks(), IsEmpty(), and ParseNoteData().
GetNonEmptyRowVector()
vector<int>& NoteData::GetNonEmptyRowVector () inline
References NonEmptyRowVector.
Referenced by DoInstalls(), Steps::GenerateBustedChartKey(), Steps::GenerateChartKey(), Player::Load(), and ScoreManager::RecalculateSSRs().
GetNumFakes()
int NoteData::GetNumFakes (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and IsFake().
GetNumFakesTwoPlayer()
pair< int, int > NoteData::GetNumFakesTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), IsFake(), and IsPlayer1().
GetNumHands()
int NoteData::GetNumHands (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const inline
References GetNumRowsWithSimultaneousPresses().
GetNumHandsTwoPlayer()
pair< int, int > NoteData::GetNumHandsTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References GetNumRowsWithSimultaneousTapsTwoPlayer().
GetNumHoldNotes()
int NoteData::GetNumHoldNotes (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References GAMESTATE, GetNumTracks(), GameState::GetProcessedTimingData(), GetTapNoteRangeExclusive(), TimingData::IsJudgableAtRow(), TapNoteSubType_Hold, and TapNoteType_HoldHead.
Referenced by ScoreKeeperNormal::OnNextSong().
GetNumHoldNotesTwoPlayer()
pair< int, int > NoteData::GetNumHoldNotesTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References GAMESTATE, GetNumTracks(), GameState::GetProcessedTimingData(), GetTapNoteRangeExclusive(), TimingData::IsJudgableAtRow(), IsPlayer1(), TapNoteSubType_Hold, and TapNoteType_HoldHead.
GetNumJumps()
int NoteData::GetNumJumps (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const inline
References GetNumRowsWithSimultaneousTaps().
GetNumJumpsTwoPlayer()
pair< int, int > NoteData::GetNumJumpsTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References GetNumRowsWithSimultaneousTapsTwoPlayer().
GetNumLifts()
int NoteData::GetNumLifts (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and IsLift().
GetNumLiftsTwoPlayer()
pair< int, int > NoteData::GetNumLiftsTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), IsLift(), and IsPlayer1().
GetNumMines()
int NoteData::GetNumMines (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and IsMine().
GetNumMinesTwoPlayer()
pair< int, int > NoteData::GetNumMinesTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), IsMine(), and IsPlayer1().
GetNumQuads()
int NoteData::GetNumQuads (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const inline
References GetNumRowsWithSimultaneousPresses().
GetNumQuadsTwoPlayer()
pair< int, int > NoteData::GetNumQuadsTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References GetNumRowsWithSimultaneousTapsTwoPlayer().
GetNumRolls()
int NoteData::GetNumRolls (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References GAMESTATE, GetNumTracks(), GameState::GetProcessedTimingData(), GetTapNoteRangeExclusive(), TimingData::IsJudgableAtRow(), TapNoteSubType_Roll, and TapNoteType_HoldHead.
Referenced by ScoreKeeperNormal::OnNextSong().
GetNumRollsTwoPlayer()
pair< int, int > NoteData::GetNumRollsTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References GAMESTATE, GetNumTracks(), GameState::GetProcessedTimingData(), GetTapNoteRangeExclusive(), TimingData::IsJudgableAtRow(), IsPlayer1(), TapNoteSubType_Roll, and TapNoteType_HoldHead.
GetNumRowsWithSimultaneousPresses()
int NoteData::GetNumRowsWithSimultaneousPresses (int iMinSimultaneousPresses, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), and RowNeedsAtLeastSimultaneousPresses().
Referenced by GetNumHands(), and GetNumQuads().
GetNumRowsWithSimultaneousTaps()
int NoteData::GetNumRowsWithSimultaneousTaps (int iMinTaps, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GAMESTATE, GetNumTracks(), GameState::GetProcessedTimingData(), GetTapNote(), TimingData::IsJudgableAtRow(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Mine, and TapNote::type.
Referenced by GetNumJumps().
GetNumRowsWithSimultaneousTapsTwoPlayer()
pair< int, int > NoteData::GetNumRowsWithSimultaneousTapsTwoPlayer (int minTaps = 2, int startRow = 0, int endRow = MAX_NOTE_ROW) const private
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GetNumTracks(), GetTapNote(), IsPlayer1(), and IsTap().
Referenced by GetNumHandsTwoPlayer(), GetNumJumpsTwoPlayer(), and GetNumQuadsTwoPlayer().
GetNumRowsWithTap()
int NoteData::GetNumRowsWithTap (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), and IsThereATapAtRow().
GetNumRowsWithTapOrHoldHead()
int NoteData::GetNumRowsWithTapOrHoldHead (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), and IsThereATapOrHoldHeadAtRow().
Referenced by ScoreKeeperNormal::OnNextSong().
GetNumTapNonEmptyTracks()
int NoteData::GetNumTapNonEmptyTracks (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_Empty, and TapNote::type.
Referenced by NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::RemoveStretch(), and NoteDataUtil::Wide().
GetNumTapNotes()
int NoteData::GetNumTapNotes (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and IsTap().
GetNumTapNotesInRow()
int NoteData::GetNumTapNotesInRow (int iRow) const
References GetNumTracks(), GetTapNote(), and IsTap().
Referenced by Player::CrossedRows().
GetNumTapNotesNoTiming()
int NoteData::GetNumTapNotesNoTiming (int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and TapNoteType_Empty.
GetNumTapNotesTwoPlayer()
pair< int, int > NoteData::GetNumTapNotesTwoPlayer (int startRow = 0, int endRow = MAX_NOTE_ROW) const
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), IsPlayer1(), and IsTap().
GetNumTracks()
int NoteData::GetNumTracks () const inline
References m_TapNotes.
Referenced by NoteDataUtil::AddMines(), NoteDataUtil::ArbitraryRemap(), NoteDataUtil::Backwards(), Steps::CalcEtternaMetadata(), CalcNumTracksLCD(), Steps::CalculateRadarValues(), GameState::CanSafelyEnterGameplay(), NoteDataUtil::ChangeHoldsToRolls(), NoteDataUtil::ChangeRollsToHolds(), ClearAll(), NoteDataUtil::ClearLeft(), ClearRange(), NoteDataUtil::ClearRight(), NoteDataUtil::CollapseLeft(), NoteDataUtil::CollapseToOne(), NoteDataUtil::ConvertAdditionsToRegular(), NoteDataUtil::ConvertTapsToHolds(), CopyRange(), Player::CrossedRows(), NoteDataUtil::DeleteRows(), Deserialize(), Player::DrawHoldJudgments(), NoteField::DrawPrimitives(), NoteDisplay::DrawTapsInRange(), ScreenGameplay::FailFadeRemovePlayer(), Steps::FillStringWithBPMs(), FindLongestOverlappingHoldNoteForAnyTrack(), Player::FlashGhostRow(), GenerateCacheDataStructure(), NoteDataUtil::GetETTNoteDataString(), GetFirstRow(), GetFirstTrackWithTap(), GetFirstTrackWithTapOrHoldHead(), GetLastRow(), GetLastTrackWithTapOrHoldHead(), NoteDataUtil::GetMaxNonEmptyTrack(), NoteDataUtil::GetNextEditorPosition(), GetNextTapNoteRowForAllTracks(), GetNumFakes(), GetNumFakesTwoPlayer(), GetNumHoldNotes(), GetNumHoldNotesTwoPlayer(), GetNumLifts(), GetNumLiftsTwoPlayer(), GetNumMines(), GetNumMinesTwoPlayer(), GetNumRolls(), GetNumRollsTwoPlayer(), GetNumRowsWithSimultaneousTaps(), GetNumRowsWithSimultaneousTapsTwoPlayer(), GetNumTapNonEmptyTracks(), GetNumTapNotes(), GetNumTapNotesInRow(), GetNumTapNotesNoTiming(), GetNumTapNotesTwoPlayer(), GetNumTracksWithTap(), GetNumTracksWithTapOrHoldHead(), NoteDataUtil::GetPrevEditorPosition(), GetPrevTapNoteRowForAllTracks(), ScoreKeeperNormal::GetRowCounts(), ScoreKeeper::GetScoreOfLastTapInRow(), GetTapFirstEmptyTrack(), GetTapFirstNonEmptyTrack(), GetTapLastEmptyTrack(), GetTapNonEmptyTracks(), GetTapNoteRange(), GetTracksHeldAtRow(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), Player::HandleTapRowScore(), SoundEffectControl::HoldsBeingHeld(), NoteDataUtil::InsertHoldTails(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::InsertRows(), IsEmpty(), IsPlayer1(), IsRangeEmpty(), IsRowEmpty(), NoteDataUtil::Little(), NoteField::Load(), AutoKeysounds::LoadAutoplaySoundsInto(), LoadFromKSFFile(), NoteDataUtil::LoadFromSMNoteDataString(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::LoadOverlapped(), LoadTransformed(), NoteDataUtil::LoadTransformedSlidingWindow(), NoteDataWithScoring::MinTapNoteScore(), ParseNoteData(), PlaceAutoKeysound(), NoteDataUtil::RemoveAllButOneTap(), NoteDataUtil::RemoveAllButPlayer(), NoteDataUtil::RemoveAllTapsExceptForType(), NoteDataUtil::RemoveAllTapsOfType(), NoteDataUtil::RemoveFakes(), NoteDataUtil::RemoveHoldNotes(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), Player::RenderAllNotesIgnoreScores(), RowNeedsAtLeastSimultaneousPresses(), NoteDataUtil::RowPassesValidMask(), NoteDataUtil::Scale(), NoteDataUtil::ScaleRegion(), Player::ScoreAllActiveHoldsLetGo(), ScreenGameplay::SendCrossedMessages(), Serialize(), SerializeNoteData(), SerializeNoteData2(), Player::SetJudgment(), Steps::SetNoteData(), SetTapNote(), NoteDataUtil::ShiftTracks(), NoteDataUtil::SnapToNearestNoteType(), ScreenHowToPlay::Step(), NoteDataUtil::Stomp(), SuperShuffleTaps(), NoteDataUtil::SwapSides(), NoteDataUtil::SwapUpDown(), NoteDataUtil::Turn(), BeginnerHelper::Update(), Player::Update(), NoteDataUtil::Wide(), and WifeTotalScoreCalc().
GetNumTracksHeldAtRow()
int NoteData::GetNumTracksHeldAtRow (int row)
References GetTracksHeldAtRow().
Referenced by NoteDataUtil::AnchorJS(), NoteDataUtil::GetTotalHoldTicks(), NoteDataUtil::IcyWorld(), NoteDataUtil::JackJS(), and NoteDataUtil::Stomp().
GetNumTracksLCD()
int NoteData::GetNumTracksLCD () const
References m_numTracksLCD.
Referenced by ScoreKeeperNormal::GetPossibleDancePoints(), and ScoreKeeperNormal::HandleTapNoteScoreInternal().
GetNumTracksWithTap()
int NoteData::GetNumTracksWithTap (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_Lift, TapNoteType_Tap, and TapNote::type.
Referenced by NoteDataUtil::AnchorJS(), NoteDataUtil::IcyWorld(), NoteDataUtil::JackJS(), NoteDataUtil::Stomp(), and NoteDataUtil::Wide().
GetNumTracksWithTapOrHoldHead()
int NoteData::GetNumTracksWithTapOrHoldHead (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Tap, and TapNote::type.
Referenced by NoteDataUtil::InsertIntelligentTaps(), and NoteDataUtil::RemoveSimultaneousNotes().
GetPrevTapNoteRowForAllTracks()
bool NoteData::GetPrevTapNoteRowForAllTracks (int & rowInOut) const
References ASSERT, GetNumTracks(), GetPrevTapNoteRowForTrack(), max(), and MAX_NOTE_ROW.
Referenced by NoteDataUtil::GetPrevEditorPosition().
GetPrevTapNoteRowForTrack()
bool NoteData::GetPrevTapNoteRowForTrack (int track, int & rowInOut) const
References ASSERT, and m_TapNotes.
Referenced by GetLastRow(), NoteDataUtil::GetPrevEditorPosition(), and GetPrevTapNoteRowForAllTracks().
GetTapFirstEmptyTrack()
bool NoteData::GetTapFirstEmptyTrack (int row, int & iEmptyTrackOut) const
References GetNumTracks(), GetTapNote(), TapNoteType_Empty, and TapNote::type.
GetTapFirstNonEmptyTrack()
bool NoteData::GetTapFirstNonEmptyTrack (int row, int & iNonEmptyTrackOut) const
References GetNumTracks(), GetTapNote(), TapNoteType_Empty, and TapNote::type.
Referenced by NoteDataUtil::InsertIntelligentTaps().
GetTapLastEmptyTrack()
bool NoteData::GetTapLastEmptyTrack (int row, int & iEmptyTrackOut) const
References GetNumTracks(), GetTapNote(), and TapNoteType_Empty.
GetTapNonEmptyTracks()
void NoteData::GetTapNonEmptyTracks (int row, set< int > & addTo) const
References GetNumTracks(), GetTapNote(), TapNoteType_Empty, and TapNote::type.
Referenced by NoteDataUtil::ConvertTapsToHolds().
GetTapNote()
const TapNote& NoteData::GetTapNote (const unsigned & track, const int & row) const inline
References m_TapNotes, and TAP_EMPTY.
Referenced by NoteDataUtil::AddMines(), NoteDataUtil::AnchorJS(), NoteDataUtil::AnyTapsAndHoldsInTrackRange(), NoteDataUtil::Backwards(), NoteDataUtil::CollapseLeft(), NoteDataUtil::ConvertAdditionsToRegular(), NoteDataUtil::ConvertTapsToHolds(), Player::CrossedRows(), NoteDisplay::DrawTapsInRange(), Steps::FillStringWithBPMs(), FindLongestOverlappingHoldNoteForAnyTrack(), Player::FlashGhostRow(), GenerateCacheDataStructure(), GetFirstTrackWithTap(), GetFirstTrackWithTapOrHoldHead(), GetLastRow(), GetLastTrackWithTapOrHoldHead(), NoteDataUtil::GetNextEditorPosition(), GetNumFakes(), GetNumFakesTwoPlayer(), GetNumLifts(), GetNumLiftsTwoPlayer(), GetNumMines(), GetNumMinesTwoPlayer(), GetNumRowsWithSimultaneousTaps(), GetNumRowsWithSimultaneousTapsTwoPlayer(), GetNumTapNonEmptyTracks(), GetNumTapNotes(), GetNumTapNotesInRow(), GetNumTapNotesNoTiming(), GetNumTapNotesTwoPlayer(), GetNumTracksWithTap(), GetNumTracksWithTapOrHoldHead(), NoteDataUtil::GetPrevEditorPosition(), ScoreKeeperNormal::GetRowCounts(), ScoreKeeper::GetScoreOfLastTapInRow(), GetTapFirstEmptyTrack(), GetTapFirstNonEmptyTrack(), GetTapLastEmptyTrack(), GetTapNonEmptyTracks(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), Player::HandleTapRowScore(), NoteDataUtil::IcyWorld(), IsHoldHeadOrBodyAtRow(), IsHoldNoteAtRow(), IsRangeEmpty(), IsRowEmpty(), NoteDataUtil::JackJS(), NoteDataWithScoring::LastTapNoteWithResult(), AutoKeysounds::LoadAutoplaySoundsInto(), NoteDataUtil::LoadOverlapped(), NoteDataUtil::LoadTransformedSlidingWindow(), NoteDataWithScoring::MinTapNoteScore(), ParseNoteData(), PlaceAutoKeysound(), BMSChartReader::ReadNoteData(), NoteDataUtil::RemoveAllButOneTap(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), RowNeedsAtLeastSimultaneousPresses(), NoteDataUtil::RowPassesValidMask(), ScreenGameplay::SendCrossedMessages(), SerializeNoteData(), SerializeNoteData2(), NoteDataUtil::SnapToNearestNoteType(), ScreenHowToPlay::Step(), Player::Step(), NoteDataUtil::Stomp(), SuperShuffleTaps(), Player::Update(), NoteDataUtil::Wide(), WifeTotalScoreCalc(), and WriteDWINotesField().
GetTapNoteRange() [1/2]
void NoteData::GetTapNoteRange (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator & begin, TrackMap::const_iterator & end) const
Return an iterator range for [rowBegin,rowEnd).
This can be used to efficiently iterate trackwise over a range of notes. It's like FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, except it only requires two map searches (iterating is constant time), but the iterators will become invalid if the notes they represent disappear, so you need to pay attention to how you modify the data.
Parameters
iTrack the column to use.
iStartRow the starting point.
iEndRow the ending point.
begin the eventual beginning point of the range.
end the eventual end point of the range.
Referenced by Player::GetClosestNoteDirectional(), GetTapNoteRangeExclusive(), GetTapNoteRangeInclusive(), and Serialize().
GetTapNoteRange() [2/2]
void NoteData::GetTapNoteRange (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator & begin, TrackMap::iterator & end)
Return a constant iterator range for [rowBegin,rowEnd).
Parameters
iTrack the column to use.
iStartRow the starting point.
iEndRow the ending point.
begin the eventual beginning point of the range.
end the eventual end point of the range.
References ASSERT_M, GetNumTracks(), m_TapNotes, MAX_NOTE_ROW, and ssprintf().
GetTapNoteRangeAllTracks() [1/2]
all_tracks_iterator NoteData::GetTapNoteRangeAllTracks (int iStartRow, int iEndRow, bool bInclusive = false) inline
Referenced by NoteDataUtil::CalculateRadarValues(), CreateNode(), Player::CrossedRows(), GenerateCacheDataStructure(), NoteDataWithScoring::GetActualRadarValues(), Player::GetClosestNonEmptyRowDirectional(), and Player::Load().
GetTapNoteRangeAllTracks() [2/2]
all_tracks_const_iterator NoteData::GetTapNoteRangeAllTracks (int iStartRow, int iEndRow, bool bInclusive = false) const inline
GetTapNoteRangeAllTracksReverse() [1/2]
all_tracks_reverse_iterator NoteData::GetTapNoteRangeAllTracksReverse (int iStartRow, int iEndRow, bool bInclusive = false) inline
Referenced by Player::GetClosestNonEmptyRowDirectional().
GetTapNoteRangeAllTracksReverse() [2/2]
all_tracks_const_reverse_iterator NoteData::GetTapNoteRangeAllTracksReverse (int iStartRow, int iEndRow, bool bInclusive = false) const inline
GetTapNoteRangeExclusive() [1/2]
void NoteData::GetTapNoteRangeExclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator & begin, TrackMap::const_iterator & end) const
References GetTapNoteRange().
Referenced by GetNumHoldNotes(), GetNumHoldNotesTwoPlayer(), GetNumRolls(), and GetNumRollsTwoPlayer().
GetTapNoteRangeExclusive() [2/2]
void NoteData::GetTapNoteRangeExclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator & begin, TrackMap::iterator & end)
References begin(), GetTapNoteRange(), TapNote::iDuration, and TapNoteType_HoldHead.
GetTapNoteRangeInclusive() [1/2]
void NoteData::GetTapNoteRangeInclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::const_iterator & begin, TrackMap::const_iterator & end, bool bIncludeAdjacent = false) const
Referenced by AddHoldNote(), NoteDataUtil::ChangeHoldsToRolls(), NoteDataUtil::ChangeRollsToHolds(), ClearRangeForTrack(), CopyRange(), NoteColumnRenderer::DrawPrimitives(), SoundEffectControl::HoldsBeingHeld(), NoteDataUtil::RemoveHoldNotes(), Player::ScoreAllActiveHoldsLetGo(), and Player::Step().
GetTapNoteRangeInclusive() [2/2]
void NoteData::GetTapNoteRangeInclusive (int iTrack, int iStartRow, int iEndRow, TrackMap::iterator & begin, TrackMap::iterator & end, bool bIncludeAdjacent = false)
References begin(), Decrement(), end(), GetTapNoteRange(), TapNote::iDuration, TapNoteType_HoldHead, and TapNote::type.
GetTracksHeldAtRow()
void NoteData::GetTracksHeldAtRow (int row, set< int > & addTo)
References GetNumTracks(), and IsHoldNoteAtRow().
Referenced by NoteDataUtil::ConvertTapsToHolds(), NoteDataUtil::Echo(), GetNumTracksHeldAtRow(), and NoteDataUtil::RemoveSimultaneousNotes().
Init()
void NoteData::Init ()
References m_TapNotes, UnsetNerv(), UnsetSerializedNoteData(), and UnsetSerializedNoteData2().
Referenced by Steps::Compress(), ScreenGameplay::FailFadeRemovePlayer(), NoteDataUtil::LoadFromSMNoteDataString(), LoadTransformed(), NoteDataUtil::LoadTransformedSlidingWindow(), and Steps::SetSMNoteData().
IsEmpty()
bool NoteData::IsEmpty () const
References GetNextTapNoteRowForTrack(), and GetNumTracks().
IsFake()
bool NoteData::IsFake (const TapNote & tn, int row) const private
Determine if the note in question should be counted as a fake.
Parameters
tn the note in question.
row the row it lives in.
Returns
true if it's a fake, false otherwise.
References GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), TapNoteType_Fake, and TapNote::type.
Referenced by GetNumFakes(), and GetNumFakesTwoPlayer().
IsHoldHeadOrBodyAtRow()
bool NoteData::IsHoldHeadOrBodyAtRow (int iTrack, int iRow, int * pHeadRow) const
References GetTapNote(), IsHoldNoteAtRow(), TapNoteType_HoldHead, and TapNote::type.
Referenced by NoteDataUtil::GetNextEditorPosition().
IsHoldNoteAtRow()
bool NoteData::IsHoldNoteAtRow (int iTrack, int iRow, int * pHeadRow = NULL) const
References DEFAULT_FAIL, FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE_REVERSE, GetTapNote(), TapNote::iDuration, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and TapNote::type.
Referenced by NoteDataUtil::AnyTapsAndHoldsInTrackRange(), GetTracksHeldAtRow(), NoteDataUtil::InsertIntelligentTaps(), IsHoldHeadOrBodyAtRow(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::LoadTransformedSlidingWindow(), PlaceAutoKeysound(), BMSChartReader::ReadNoteData(), RowNeedsAtLeastSimultaneousPresses(), Player::SetJudgment(), NoteDataUtil::SnapToNearestNoteType(), Player::Step(), SuperShuffleTaps(), Player::Update(), and NoteDataUtil::Wide().
IsLift()
bool NoteData::IsLift (const TapNote & tn, int row) const private
Determine if the note in question should be counted as a lift.
Parameters
tn the note in question.
row the row it lives in.
Returns
true if it's a lift, false otherwise.
References GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), TapNoteType_Lift, and TapNote::type.
Referenced by GetNumLifts(), and GetNumLiftsTwoPlayer().
IsMine()
bool NoteData::IsMine (const TapNote & tn, int row) const private
Determine if the note in question should be counted as a mine.
Parameters
tn the note in question.
row the row it lives in.
Returns
true if it's a mine, false otherwise.
References GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), TapNoteType_Mine, and TapNote::type.
Referenced by GetNumMines(), and GetNumMinesTwoPlayer().
IsPlayer1()
bool NoteData::IsPlayer1 (int track, const TapNote & tn) const private
Determine whether this note is for Player 1 or Player 2.
Parameters
track the track/column the note is in.
tn the note in question. Required for routine mode.
Returns
true if it's for player 1, false for player 2.
References GetNumTracks().
Referenced by GetNumFakesTwoPlayer(), GetNumHoldNotesTwoPlayer(), GetNumLiftsTwoPlayer(), GetNumMinesTwoPlayer(), GetNumRollsTwoPlayer(), GetNumRowsWithSimultaneousTapsTwoPlayer(), and GetNumTapNotesTwoPlayer().
IsRangeEmpty()
bool NoteData::IsRangeEmpty (int track, int rowBegin, int rowEnd) const
References ASSERT, FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, GetNumTracks(), GetTapNote(), and TapNoteType_Empty.
Referenced by NoteDataUtil::AddMines().
IsRowEmpty()
bool NoteData::IsRowEmpty (int row) const
References GetNumTracks(), GetTapNote(), TapNoteType_Empty, and TapNote::type.
Referenced by NoteDataUtil::GetSmallestNoteTypeInRange().
IsTap()
bool NoteData::IsTap (const TapNote & tn, int row) const private
Determine if the note in question should be counted as a tap.
Parameters
tn the note in question.
row the row it lives in.
Returns
true if it's a tap, false otherwise.
References GAMESTATE, GameState::GetProcessedTimingData(), TimingData::IsJudgableAtRow(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Lift, TapNoteType_Mine, and TapNote::type.
Referenced by GetNumRowsWithSimultaneousTapsTwoPlayer(), GetNumTapNotes(), GetNumTapNotesInRow(), and GetNumTapNotesTwoPlayer().
IsThereATapAtRow()
bool NoteData::IsThereATapAtRow (int row) const inline
References GetFirstTrackWithTap().
Referenced by GetNumRowsWithTap(), ScreenHowToPlay::Step(), NoteDataUtil::Stomp(), and ScreenHowToPlay::Update().
IsThereATapOrHoldHeadAtRow()
bool NoteData::IsThereATapOrHoldHeadAtRow (int row) const inline
References GetFirstTrackWithTapOrHoldHead().
Referenced by GetNumRowsWithTapOrHoldHead(), GameplayAssist::PlayTicks(), and Player::Step().
IsTrackEmpty()
bool NoteData::IsTrackEmpty (int iTrack) const inline
References m_TapNotes.
Referenced by NoteDataUtil::GetMaxNonEmptyTrack().
LoadFromNode()
void NoteData::LoadFromNode (const XNode * pNode)
References FAIL_M.
LoadTransformed()
void NoteData::LoadTransformed (const NoteData & original, int iNewNumTracks, const int iOriginalTrackToTakeFrom[])
References ASSERT_M, GetNumTracks(), Init(), m_TapNotes, SetNumTracks(), and ssprintf().
Referenced by NoteDataUtil::ArbitraryRemap(), Style::GetTransformedNoteDataForStyle(), NoteDataUtil::ShiftTracks(), NoteDataUtil::SwapSides(), NoteDataUtil::SwapUpDown(), and NoteDataUtil::Turn().
LogNonEmptyRows()
void NoteData::LogNonEmptyRows ()
References FOREACH_NONEMPTY_ROW_ALL_TRACKS, and NonEmptyRowVector.
Referenced by BuildAndGetNerv(), DoInstalls(), Player::Load(), and ScoreManager::RecalculateSSRs().
lower_bound() [1/2]
iterator NoteData::lower_bound (int iTrack, int iRow) inline
References m_TapNotes.
lower_bound() [2/2]
const_iterator NoteData::lower_bound (int iTrack, int iRow) const inline
References m_TapNotes.
MoveTapNoteTrack()
void NoteData::MoveTapNoteTrack (int dest, int src)
References m_TapNotes.
operator!=()
bool NoteData::operator!= (const NoteData & nd) const inline
References m_TapNotes.
operator==()
bool NoteData::operator== (const NoteData & nd) const inline
References m_TapNotes.
rbegin() [1/2]
reverse_iterator NoteData::rbegin (int iTrack) inline
References m_TapNotes.
rbegin() [2/2]
const_reverse_iterator NoteData::rbegin (int iTrack) const inline
References m_TapNotes.
RemoveATIFromList() [1/2]
void NoteData::RemoveATIFromList (all_tracks_iterator * iter) const private
References m_atis.
RemoveATIFromList() [2/2]
void NoteData::RemoveATIFromList (all_tracks_const_iterator * iter) const private
RemoveTapNote()
void NoteData::RemoveTapNote (unsigned iTrack, iterator it) inline
References m_TapNotes.
Referenced by AddHoldNote(), NoteDataUtil::CollapseToOne(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::RemoveAllButOneTap(), NoteDataUtil::RemoveAllButPlayer(), NoteDataUtil::RemoveAllTapsExceptForType(), and NoteDataUtil::RemoveAllTapsOfType().
rend() [1/2]
reverse_iterator NoteData::rend (int iTrack) inline
References m_TapNotes.
rend() [2/2]
const_reverse_iterator NoteData::rend (int iTrack) const inline
References m_TapNotes.
RevalidateATIs()
void NoteData::RevalidateATIs (vector< int > const & added_or_removed_tracks, bool added)
References m_atis, and m_const_atis.
Referenced by NoteDataUtil::AddMines(), NoteDataUtil::AnchorJS(), NoteDataUtil::ArbitraryRemap(), NoteDataUtil::Backwards(), NoteDataUtil::ChangeHoldsToRolls(), NoteDataUtil::ChangeRollsToHolds(), NoteDataUtil::ConvertAdditionsToRegular(), NoteDataUtil::ConvertTapsToHolds(), NoteDataUtil::DeleteRows(), NoteDataUtil::Echo(), NoteDataUtil::IcyWorld(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::InsertRows(), NoteDataUtil::JackJS(), NoteDataUtil::Little(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromSMNoteDataStringWithPlayer(), NoteDataUtil::LoadOverlapped(), NoteDataUtil::LoadTransformedSlidingWindow(), NoteDataUtil::RemoveAllButOneTap(), NoteDataUtil::RemoveAllButPlayer(), NoteDataUtil::RemoveAllTapsExceptForType(), NoteDataUtil::RemoveAllTapsOfType(), NoteDataUtil::RemoveFakes(), NoteDataUtil::RemoveHoldNotes(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), NoteDataUtil::RemoveStretch(), NoteDataUtil::Scale(), NoteDataUtil::ScaleRegion(), NoteDataUtil::SnapToNearestNoteType(), NoteDataUtil::Stomp(), NoteDataUtil::SwapSides(), NoteDataUtil::SwapUpDown(), NoteDataUtil::TransformNoteData(), NoteDataUtil::Turn(), and NoteDataUtil::Wide().
RowNeedsAtLeastSimultaneousPresses()
bool NoteData::RowNeedsAtLeastSimultaneousPresses (int iMinSimultaneousPresses, int row) const
References GetNumTracks(), GetTapNote(), IsHoldNoteAtRow(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Lift, TapNoteType_Mine, and TapNote::type.
Referenced by GetNumRowsWithSimultaneousPresses(), and RowNeedsHands().
RowNeedsHands()
bool NoteData::RowNeedsHands (int row) const inline
References RowNeedsAtLeastSimultaneousPresses().
SerializeNoteData()
const vector< NoteInfo > & NoteData::SerializeNoteData (const vector< float > & etaner)
References GetNumTracks(), GetTapNote(), TapNote::IsNote(), NonEmptyRowVector, and SerializedNoteData.
Referenced by Steps::CalcEtternaMetadata(), DoInstalls(), Player::Load(), and ScoreManager::RecalculateSSRs().
SerializeNoteData2()
vector< NoteInfo2 > & NoteData::SerializeNoteData2 (const vector< float > & etaner)
References GetNumTracks(), GetTapNote(), TapNote::IsNote(), NonEmptyRowVector, and SerializedNoteData2.
SetNumTracks()
void NoteData::SetNumTracks (int iNewNumTracks)
References ASSERT, CalcNumTracksLCD(), and m_TapNotes.
Referenced by NoteDataUtil::Backwards(), Steps::CopyFrom(), Steps::CreateBlank(), Steps::Decompress(), NoteDataUtil::DeleteRows(), Deserialize(), ScreenGameplay::FailFadeRemovePlayer(), Steps::GetNoteData(), NoteDataUtil::InsertRows(), LoadFromKSFFile(), NoteDataUtil::LoadFromSMNoteDataString(), OsuLoader::LoadNoteDataFromParsedData(), NoteDataUtil::LoadOverlapped(), LoadTransformed(), NoteDataUtil::LoadTransformedSlidingWindow(), ParseNoteData(), BMSChartReader::ReadNoteData(), NoteDataUtil::Scale(), and NoteDataUtil::ScaleRegion().
SetTapNote()
void NoteData::SetTapNote (int track, int row, const TapNote & tn)
References DEBUG_ASSERT, GetNumTracks(), m_TapNotes, and TAP_EMPTY.
Referenced by AddHoldNote(), NoteDataUtil::AddMines(), NoteDataUtil::AnchorJS(), NoteDataUtil::Backwards(), ClearRangeForTrack(), NoteDataUtil::CollapseLeft(), NoteDataUtil::CollapseToOne(), NoteDataUtil::ConvertAdditionsToRegular(), CopyRange(), Deserialize(), NoteDataUtil::Echo(), NoteDataUtil::IcyWorld(), NoteDataUtil::InsertHoldTails(), NoteDataUtil::InsertIntelligentTaps(), NoteDataUtil::JackJS(), NoteDataUtil::Little(), NoteDataUtil::LoadFromETTNoteDataString(), LoadFromKSFFile(), LoadFromSMNoteDataStringWithPlayer(), OsuLoader::LoadNoteDataFromParsedData(), NoteDataUtil::LoadOverlapped(), NoteDataUtil::LoadTransformedSlidingWindow(), ParseNoteData(), PlaceAutoKeysound(), BMSChartReader::ReadNoteData(), NoteDataUtil::RemoveFakes(), NoteDataUtil::RemoveSimultaneousNotes(), NoteDataUtil::RemoveSpecificTapNotes(), NoteDataUtil::Scale(), NoteDataUtil::ScaleRegion(), NoteDataUtil::SnapToNearestNoteType(), NoteDataUtil::Stomp(), SuperShuffleTaps(), NoteDataUtil::Wide(), and WriteDWINotesField().
swap()
void NoteData::swap (NoteData & nd) inline
References m_atis, m_const_atis, and m_TapNotes.
Referenced by NoteDataUtil::Backwards(), NoteDataUtil::Scale(), and NoteDataUtil::ScaleRegion().
TransferATIs()
void NoteData::TransferATIs (NoteData & to)
UnsetNerv()
void NoteData::UnsetNerv () inline
References NonEmptyRowVector.
Referenced by Steps::CalcEtternaMetadata(), DoInstalls(), Init(), and ScoreManager::RecalculateSSRs().
UnsetSerializedNoteData()
void NoteData::UnsetSerializedNoteData () inline
References SerializedNoteData.
Referenced by Steps::CalcEtternaMetadata(), DoInstalls(), Init(), Player::Load(), and ScoreManager::RecalculateSSRs().
UnsetSerializedNoteData2()
void NoteData::UnsetSerializedNoteData2 () inline
References SerializedNoteData2.
Referenced by Init().
upper_bound() [1/2]
iterator NoteData::upper_bound (int iTrack, int iRow) inline
References m_TapNotes.
upper_bound() [2/2]
const_iterator NoteData::upper_bound (int iTrack, int iRow) const inline
References m_TapNotes.
WifeTotalScoreCalc()
int NoteData::WifeTotalScoreCalc (TimingData * td, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS, GetNumTracks(), GetTapNote(), TimingData::IsJudgableAtRow(), TapNoteType_Empty, TapNoteType_Fake, TapNoteType_Mine, and TapNote::type.
Referenced by Player::Load().
Friends And Related Function Documentation
_all_tracks_iterator< const NoteData, NoteData::const_iterator, const TapNote >
friend class _all_tracks_iterator< const NoteData, NoteData::const_iterator, const TapNote > friend
_all_tracks_iterator< NoteData, NoteData::iterator, TapNote >
friend class _all_tracks_iterator< NoteData, NoteData::iterator, TapNote > friend
Member Data Documentation
m_atis
set<all_tracks_iterator*> NoteData::m_atis mutable private
Referenced by AddATIToList(), RemoveATIFromList(), RevalidateATIs(), and swap().
m_const_atis
set<all_tracks_const_iterator*> NoteData::m_const_atis mutable private
Referenced by RevalidateATIs(), and swap().
m_numTracksLCD
int NoteData::m_numTracksLCD private
Referenced by CalcNumTracksLCD(), and GetNumTracksLCD().
m_TapNotes
vector<TrackMap> NoteData::m_TapNotes private
Referenced by begin(), ClearAll(), ClearRangeForTrack(), end(), FindTapNote(), GetNextTapNoteRowForTrack(), GetNumTracks(), GetPrevTapNoteRowForTrack(), GetTapNote(), GetTapNoteRange(), Init(), IsTrackEmpty(), LoadTransformed(), lower_bound(), MoveTapNoteTrack(), operator!=(), operator==(), rbegin(), RemoveTapNote(), rend(), SetNumTracks(), SetTapNote(), swap(), and upper_bound().
NonEmptyRowVector
vector<int> NoteData::NonEmptyRowVector private
Referenced by BuildAndGetNerv(), GetNonEmptyRowVector(), LogNonEmptyRows(), SerializeNoteData(), SerializeNoteData2(), and UnsetNerv().
SerializedNoteData
vector<NoteInfo> NoteData::SerializedNoteData private
Referenced by SerializeNoteData(), and UnsetSerializedNoteData().
SerializedNoteData2
vector<NoteInfo2> NoteData::SerializedNoteData2 private
Referenced by SerializeNoteData2(), and UnsetSerializedNoteData2().
The documentation for this class was generated from the following files:
NoteData.h
NoteData.cpp