Etterna: RoomWheel.cpp File Reference
RoomWheel.cpp File Reference
#include "global.h"
#include "RoomWheel.h"
#include "ActorUtil.h"
#include "LocalizedString.h"
#include "NetworkSyncManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "ScreenManager.h"
#include "ScreenTextEntry.h"
#include "LuaBinding.h"
Classes
class LunaRoomWheel
Functions
AutoScreenMessage (SM_BackFromRoomName)
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage (SM_RoomInfoDeploy)
bool findme (std::string str, std::string findme)
Variables
static LocalizedString EMPTY_STRING ("RoomWheel", "Empty")
static LocalizedString ENTER_ROOM_NAME ("RoomWheel", "Enter room name")
Function Documentation
AutoScreenMessage() [1/3]
AutoScreenMessage (SM_BackFromRoomName)
AutoScreenMessage() [2/3]
AutoScreenMessage (SM_RoomInfoRetract)
AutoScreenMessage() [3/3]
AutoScreenMessage (SM_RoomInfoDeploy)
findme()
bool findme (std::string str, std::string findme)
Referenced by MusicWheel::FilterBySearch(), RoomWheel::FilterBySearch(), RoomWheel::Search(), and LunaRoomWheel::Search().
Variable Documentation
EMPTY_STRING
LocalizedString EMPTY_STRING("RoomWheel", "Empty") static
Referenced by RoomWheel::BuildWheelItemsData().
ENTER_ROOM_NAME
LocalizedString ENTER_ROOM_NAME("RoomWheel", "Enter room name") static
Referenced by RoomWheel::Select().