Etterna: RageFileDriverTimeout Class Reference
RageFileDriverTimeout Class Reference
#include <RageFileDriverTimeout.h>
Public Member Functions
RageFileDriverTimeout (const RString &path)
~RageFileDriverTimeout () override
RageFileBasic * Open (const RString &path, int mode, int &err) override
void FlushDirCache (const RString &sPath) override
bool Move (const RString &sOldPath, const RString &sNewPath) override
bool Remove (const RString &sPath) override
Public Member Functions inherited from RageFileDriver
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void CacheFile (const RString &)
virtual bool Remount (const RString &)
Static Public Member Functions
static void SetTimeout (float fSeconds)
static void ResetTimeout ()
Private Attributes
ThreadedFileWorker * m_pWorker
Additional Inherited Members
Public Types inherited from RageFileDriver
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Attributes inherited from RageFileDriver
FilenameDB * FDB
Constructor & Destructor Documentation
RageFileDriverTimeout()
RageFileDriverTimeout::RageFileDriverTimeout (const RString & path) explicit
References RageFileDriver::FDB, and m_pWorker.
~RageFileDriverTimeout()
RageFileDriverTimeout::~RageFileDriverTimeout () override
References m_pWorker.
Member Function Documentation
FlushDirCache()
void RageFileDriverTimeout::FlushDirCache (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
References RageFileDriver::FlushDirCache(), ThreadedFileWorker::FlushDirCache(), and m_pWorker.
Move()
bool RageFileDriverTimeout::Move (const RString & sOldPath, const RString & sNewPath) override virtual
Reimplemented from RageFileDriver.
References m_pWorker, ThreadedFileWorker::Move(), ssprintf(), and WARN.
Open()
RageFileBasic * RageFileDriverTimeout::Open (const RString & path, int mode, int & err) override virtual
Implements RageFileDriver.
References ASSERT, ThreadedFileWorker::GetFileSize(), m_pWorker, ThreadedFileWorker::Open(), and RageFile::READ.
Remove()
bool RageFileDriverTimeout::Remove (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
References m_pWorker, ThreadedFileWorker::Remove(), ssprintf(), and WARN.
ResetTimeout()
static void RageFileDriverTimeout::ResetTimeout () inline static
References SetTimeout().
SetTimeout()
void RageFileDriverTimeout::SetTimeout (float fSeconds) static
References g_apWorkers, g_apWorkersMutex, RageMutex::Lock(), and RageMutex::Unlock().
Referenced by ResetTimeout().
Member Data Documentation
m_pWorker
ThreadedFileWorker* RageFileDriverTimeout::m_pWorker private
Referenced by FlushDirCache(), Move(), Open(), RageFileDriverTimeout(), Remove(), and ~RageFileDriverTimeout().
The documentation for this class was generated from the following files:
RageFileDriverTimeout.h
RageFileDriverTimeout.cpp