Etterna: NotesWriterSM Namespace Reference
NotesWriterSM Namespace Reference
Writes a Song to an .SM file.
Functions
bool Write (const RString &sPath, Song &out, const vector< Steps *> &vpStepsToSave)
Write the song out to a file.
void GetEditFileContents (const Song *pSong, const Steps *pSteps, RString &sOut)
Get some contents about the edit file first.
RString GetEditFileName (const Song *pSong, const Steps *pSteps)
Get the name of the edit file to use.
bool WriteEditFileToMachine (const Song *pSong, Steps *pSteps, RString &sErrorOut)
Write the edit file to the machine for future use.
Detailed Description
Writes a Song to an .SM file.
Function Documentation
GetEditFileContents()
void NotesWriterSM::GetEditFileContents (const Song * pSong, const Steps * pSteps, RString & sOut)
Get some contents about the edit file first.
Parameters
pSong the Song in question.
pSteps the Steps in question.
sOut the start of the file contents.
References GetSMNotesTag(), Song::GetSongDir(), Rage::join(), split(), and ssprintf().
GetEditFileName()
RString NotesWriterSM::GetEditFileName (const Song * pSong, const Steps * pSteps)
Get the name of the edit file to use.
Parameters
pSong the Song in question.
pSteps the Steps in question.
Returns
the name of the edit file.
References Steps::GetDescription(), Song::GetTranslitFullTitle(), Steps::m_StepsType, MakeValidFilename(), and StepsType_dance_double.
Write()
bool NotesWriterSM::Write (const RString & sPath, Song & out, const vector< Steps *> & vpStepsToSave)
Write the song out to a file.
Parameters
sPath the path to write the file.
out the Song to be written out.
Returns
its success or failure.
References f, RageFile::Flush(), FOREACH_CONST, RageFile::GetError(), GetSMNotesTag(), LOG, RageFile::Open(), RageFile::PutLine(), RageFile::SLOW_FLUSH, RageLog::UserLog(), RageFile::WRITE, and WriteGlobalTags().
Referenced by Song::SaveToSMFile().
WriteEditFileToMachine()
bool NotesWriterSM::WriteEditFileToMachine (const Song * pSong, Steps * pSteps, RString & sErrorOut)
Write the edit file to the machine for future use.
Parameters
pSong the Song in question.
pSteps the Steps in question.
sErrorOut any error messages that may have occurred.
Returns
its success or failure.