Etterna: NoteDataUtil Namespace Reference
NoteDataUtil Namespace Reference
Utility functions that deal with NoteData.
Enumerations
enum TrackMapping {
left, right, mirror, backwards,
shuffle, soft_shuffle, super_shuffle, stomp,
swap_up_down, NUM_TRACK_MAPPINGS
}
The types of transformations available for the NoteData.
Functions
NoteType GetSmallestNoteTypeForMeasure (const NoteData &nd, int iMeasureIndex)
NoteType GetSmallestNoteTypeInRange (const NoteData &nd, int iStartIndex, int iEndIndex)
void LoadFromSMNoteDataString (NoteData &out, const RString &sSMNoteData)
void LoadFromETTNoteDataString (NoteData &out, const RString &sSMNoteData)
void GetSMNoteDataString (const NoteData &in, RString &notes_out)
void GetETTNoteDataString (const NoteData &in, RString &notes_out)
void LoadTransformedSlidingWindow (const NoteData &in, NoteData &out, int iNewNumTracks)
Autogenerate notes from one type to another.
void LoadOverlapped (const NoteData &in, NoteData &out, int iNewNumTracks)
Autogenerate notes from one type to another.
void LoadTransformedLights (const NoteData &in, NoteData &out, int iNewNumTracks)
void LoadTransformedLightsFromTwo (const NoteData &marquee, const NoteData &bass, NoteData &out)
void InsertHoldTails (NoteData &inout)
void CalculateRadarValues (const NoteData &in, float fSongSeconds, RadarValues &out, TimingData *td=nullptr)
void RemoveHoldNotes (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the Hold notes.
void ChangeRollsToHolds (NoteData &in, int iStartIndex, int iEndIndex)
void ChangeHoldsToRolls (NoteData &in, int iStartIndex, int iEndIndex)
void RemoveSimultaneousNotes (NoteData &inout, int iMaxSimultaneous, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void RemoveJumps (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void RemoveHands (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void RemoveQuads (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void RemoveSpecificTapNotes (NoteData &inout, TapNoteType tn, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of a specific TapNote Type.
void RemoveMines (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the mines from the chart.
void RemoveLifts (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the lifts from the chart.
void RemoveFakes (NoteData &inout, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
Remove all of the fakes from the chart.
void RemoveStretch (NoteData &inout, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void RemoveAllButOneTap (NoteData &inout, int row)
void RemoveAllButPlayer (NoteData &inout, PlayerNumber pn)
void Turn (NoteData &inout, StepsType st, TrackMapping tt, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Little (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Wide (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Big (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Quick (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void BMRize (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Skippy (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void InsertIntelligentTaps (NoteData &in, int iWindowSizeRows, int iInsertOffsetRows, int iWindowStrideRows, bool bSkippy, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void AddMines (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Echo (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Stomp (NoteData &inout, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void JackJS (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void AnchorJS (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void IcyWorld (NoteData &inout, StepsType st, TimingData const &timing_data, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Planted (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Floored (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Twister (NoteData &inout, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void ConvertTapsToHolds (NoteData &inout, int iSimultaneousHolds, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void ConvertAdditionsToRegular (NoteData &inout)
Convert all taps added via transforms into original style tap notes.
void Backwards (NoteData &inout)
void SwapSides (NoteData &inout)
void CopyLeftToRight (NoteData &inout)
void CopyRightToLeft (NoteData &inout)
void ClearLeft (NoteData &inout)
void ClearRight (NoteData &inout)
void CollapseToOne (NoteData &inout)
void CollapseLeft (NoteData &inout)
void ShiftTracks (NoteData &inout, int iShiftBy)
void ShiftLeft (NoteData &inout)
void ShiftRight (NoteData &inout)
void SwapUpDown (NoteData &inout, StepsType st)
void ArbitraryRemap (NoteData &inout, int *mapping)
void SnapToNearestNoteType (NoteData &inout, NoteType nt1, NoteType nt2, int iStartIndex, int iEndIndex)
void SnapToNearestNoteType (NoteData &inout, NoteType nt, int iStartIndex, int iEndIndex)
bool RowPassesValidMask (NoteData &inout, int row, const bool bValidMask[])
void TransformNoteData (NoteData &nd, TimingData const &timing_data, const PlayerOptions &po, StepsType st, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void Scale (NoteData &nd, float fScale)
void ScaleRegion (NoteData &nd, float fScale, int iStartIndex=0, int iEndIndex=MAX_NOTE_ROW)
void InsertRows (NoteData &nd, int iStartIndex, int iRowsToShift)
void DeleteRows (NoteData &nd, int iStartIndex, int iRowsToShift)
void RemoveAllTapsOfType (NoteData &ndInOut, TapNoteType typeToRemove)
void RemoveAllTapsExceptForType (NoteData &ndInOut, TapNoteType typeToKeep)
int GetMaxNonEmptyTrack (const NoteData &in)
bool AnyTapsAndHoldsInTrackRange (const NoteData &in, int iTrack, int iStart, int iEnd)
bool GetNextEditorPosition (const NoteData &in, int &rowInOut)
bool GetPrevEditorPosition (const NoteData &in, int &rowInOut)
unsigned int GetTotalHoldTicks (NoteData *nd, const TimingData *td)
Count the number of hold ticks that will fire, assuming that tickholds are on.
Detailed Description
Utility functions that deal with NoteData.
Things should go in here if they can be (cleanly and efficiently) implemented using only NoteData's primitives; this improves abstraction and makes it much easier to change NoteData internally in the future.
Enumeration Type Documentation
TrackMapping
enum NoteDataUtil::TrackMapping
The types of transformations available for the NoteData.
Enumerator
left
The NoteData is arranged as if the player was facing to the left.
right
mirror
The NoteData is arranged as if facing a straight mirror.
backwards
The NoteData is arranged as if the player was facing backwards. This is NOT always the same as mirror.
shuffle
soft_shuffle
super_shuffle
stomp
swap_up_down
NUM_TRACK_MAPPINGS
Function Documentation
AddMines()
void NoteDataUtil::AddMines (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, NoteData::IsRangeEmpty(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_ADDITION_MINE, TapNoteType_HoldHead, TapNoteType_Tap, and TapNote::type.
Referenced by TransformNoteData().
AnchorJS()
void NoteDataUtil::AnchorJS (NoteData & inout, StepsType st, TimingData const & timing_data, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracksHeldAtRow(), NoteData::GetNumTracksWithTap(), NoteData::GetTapNote(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_ADDITION_TAP, TapNoteType_Tap, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
AnyTapsAndHoldsInTrackRange()
bool NoteDataUtil::AnyTapsAndHoldsInTrackRange (const NoteData & in, int iTrack, int iStart, int iEnd)
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetTapNote(), NoteData::IsHoldNoteAtRow(), TapNoteType_Empty, TapNoteType_Mine, and TapNote::type.
ArbitraryRemap()
void NoteDataUtil::ArbitraryRemap (NoteData & inout, int * mapping)
References NoteData::CopyAll(), NoteData::GetNumTracks(), NoteData::LoadTransformed(), and NoteData::RevalidateATIs().
Backwards()
void NoteDataUtil::Backwards (NoteData & inout)
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetLastRow(), NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, NoteData::RevalidateATIs(), NoteData::SetNumTracks(), NoteData::SetTapNote(), NoteData::swap(), TapNoteType_HoldHead, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions().
Big()
void NoteDataUtil::Big (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, and InsertIntelligentTaps().
Referenced by BMRize(), LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
BMRize()
void NoteDataUtil::BMRize (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References Big(), and Quick().
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
CalculateRadarValues()
void NoteDataUtil::CalculateRadarValues (const NoteData & in, float fSongSeconds, RadarValues & out, TimingData * td = nullptr)
References DoRowEndRadarCalc(), GAMESTATE, GameState::GetProcessedTimingData(), NoteData::GetTapNoteRangeAllTracks(), crv_state::hold_ends, NoteData::_all_tracks_iterator< ND, iter, TN >::IsAtEnd(), TimingData::IsJudgableAtRow(), crv_state::judgable, MAX_NOTE_ROW, crv_state::num_holds_on_curr_row, crv_state::num_notes_on_curr_row, RadarCategory_Fakes, RadarCategory_Holds, RadarCategory_Jumps, RadarCategory_Lifts, RadarCategory_Mines, RadarCategory_Notes, RadarCategory_Rolls, RadarCategory_TapsAndHolds, NoteData::_all_tracks_iterator< ND, iter, TN >::Row(), TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and RadarValues::Zero().
Referenced by Steps::CalculateRadarValues(), ScoreKeeperNormal::GetPossibleDancePoints(), ScoreKeeperNormal::GetPossibleGradePoints(), and ScreenGameplay::SaveStats().
ChangeHoldsToRolls()
void NoteDataUtil::ChangeHoldsToRolls (NoteData & in, int iStartIndex, int iEndIndex)
References NoteData::GetNumTracks(), NoteData::GetTapNoteRangeInclusive(), NoteData::RevalidateATIs(), TapNoteSubType_Hold, TapNoteSubType_Roll, and TapNoteType_HoldHead.
Referenced by TransformNoteData().
ChangeRollsToHolds()
void NoteDataUtil::ChangeRollsToHolds (NoteData & in, int iStartIndex, int iEndIndex)
References NoteData::GetNumTracks(), NoteData::GetTapNoteRangeInclusive(), NoteData::RevalidateATIs(), TapNoteSubType_Hold, TapNoteSubType_Roll, and TapNoteType_HoldHead.
Referenced by TransformNoteData().
ClearLeft()
void NoteDataUtil::ClearLeft (NoteData & inout)
References NoteData::ClearRangeForTrack(), NoteData::GetNumTracks(), and MAX_NOTE_ROW.
ClearRight()
void NoteDataUtil::ClearRight (NoteData & inout)
References NoteData::ClearRangeForTrack(), NoteData::GetNumTracks(), and MAX_NOTE_ROW.
CollapseLeft()
void NoteDataUtil::CollapseLeft (NoteData & inout)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS, NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::SetTapNote(), TAP_EMPTY, TapNoteType_Empty, and TapNote::type.
CollapseToOne()
void NoteDataUtil::CollapseToOne (NoteData & inout)
References NoteData::end(), NoteData::FindTapNote(), FOREACH_NONEMPTY_ROW_ALL_TRACKS, NoteData::GetNumTracks(), NoteData::RemoveTapNote(), and NoteData::SetTapNote().
ConvertAdditionsToRegular()
void NoteDataUtil::ConvertAdditionsToRegular (NoteData & inout)
Convert all taps added via transforms into original style tap notes.
Parameters
inout the NoteData to convert.
References FOREACH_NONEMPTY_ROW_IN_TRACK, NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TapNote::source, TapNoteSource_Addition, and TapNoteSource_Original.
ConvertTapsToHolds()
void NoteDataUtil::ConvertTapsToHolds (NoteData & inout, int iSimultaneousHolds, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References NoteData::AddHoldNote(), BeatToNoteRow(), FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracks(), NoteData::GetTapNonEmptyTracks(), NoteData::GetTapNote(), NoteData::GetTracksHeldAtRow(), NoteData::RevalidateATIs(), TAP_ORIGINAL_HOLD_HEAD, TapNoteType_Empty, TapNoteType_Tap, and TapNote::type.
Referenced by Floored(), Planted(), and Twister().
CopyLeftToRight()
void NoteDataUtil::CopyLeftToRight (NoteData & inout)
CopyRightToLeft()
void NoteDataUtil::CopyRightToLeft (NoteData & inout)
DeleteRows()
void NoteDataUtil::DeleteRows (NoteData & nd, int iStartIndex, int iRowsToShift)
References ASSERT, NoteData::ClearRange(), NoteData::CopyRange(), NoteData::GetNumTracks(), MAX_NOTE_ROW, NoteData::RevalidateATIs(), and NoteData::SetNumTracks().
Echo()
void NoteDataUtil::Echo (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetFirstTrackWithTap(), NoteData::GetLastRow(), NoteData::GetTracksHeldAtRow(), min(), Quantize(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), and TAP_ADDITION_TAP.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
Floored()
void NoteDataUtil::Floored (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ConvertTapsToHolds().
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
GetETTNoteDataString()
void NoteDataUtil::GetETTNoteDataString (const NoteData & in, RString & notes_out)
References BEATS_PER_MEASURE, FOREACH, NoteData::GetNumTracks(), GetSmallestNoteTypeForMeasure(), max(), NoteType_Invalid, NoteTypeToBeat(), ROWS_PER_BEAT, ROWS_PER_MEASURE, TapNote::subType, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_HoldTail, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and TapNote::type.
Referenced by Steps::GetETTNoteData().
GetMaxNonEmptyTrack()
int NoteDataUtil::GetMaxNonEmptyTrack (const NoteData & in)
References NoteData::GetNumTracks(), and NoteData::IsTrackEmpty().
GetNextEditorPosition()
bool NoteDataUtil::GetNextEditorPosition (const NoteData & in, int & rowInOut)
References ASSERT, NoteData::GetNextTapNoteRowForAllTracks(), NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, NoteData::IsHoldHeadOrBodyAtRow(), MAX_NOTE_ROW, and min().
GetPrevEditorPosition()
bool NoteDataUtil::GetPrevEditorPosition (const NoteData & in, int & rowInOut)
References ASSERT, NoteData::GetNumTracks(), NoteData::GetPrevTapNoteRowForAllTracks(), NoteData::GetPrevTapNoteRowForTrack(), NoteData::GetTapNote(), TapNote::iDuration, max(), MAX_NOTE_ROW, TapNoteType_HoldHead, and TapNote::type.
GetSmallestNoteTypeForMeasure()
NoteType NoteDataUtil::GetSmallestNoteTypeForMeasure (const NoteData & nd, int iMeasureIndex)
References GetSmallestNoteTypeInRange(), and ROWS_PER_MEASURE.
Referenced by GetETTNoteDataString(), GetSMNoteDataString(), and WriteDWINotesField().
GetSmallestNoteTypeInRange()
NoteType NoteDataUtil::GetSmallestNoteTypeInRange (const NoteData & nd, int iStartIndex, int iEndIndex)
References FOREACH_ENUM, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::IsRowEmpty(), NoteType_Invalid, NoteTypeToBeat(), and ROWS_PER_BEAT.
Referenced by GetSmallestNoteTypeForMeasure().
GetSMNoteDataString()
void NoteDataUtil::GetSMNoteDataString (const NoteData & in, RString & notes_out)
References BEATS_PER_MEASURE, FAIL_M, FOREACH, GetSmallestNoteTypeForMeasure(), TapNote::iKeysoundIndex, InsertHoldTails(), max(), NoteType_Invalid, NoteTypeToBeat(), ROWS_PER_BEAT, ROWS_PER_MEASURE, ssprintf(), TapNote::subType, TapNoteSubType_Hold, TapNoteSubType_Roll, TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_Fake, TapNoteType_HoldHead, TapNoteType_HoldTail, TapNoteType_Lift, TapNoteType_Mine, TapNoteType_Tap, and TapNote::type.
Referenced by Steps::Compress(), Steps::GetHash(), and Steps::GetSMNoteData().
GetTotalHoldTicks()
unsigned int NoteDataUtil::GetTotalHoldTicks (NoteData * nd, const TimingData * td)
Count the number of hold ticks that will fire, assuming that tickholds are on.
Parameters
td The TimingData from the relevant Steps.
References NoteData::GetLastRow(), NoteData::GetNumTracksHeldAtRow(), TimingSegment::GetRow(), TickcountSegment::GetTicks(), TimingData::GetTimingSegments(), ROWS_PER_BEAT, and SEGMENT_TICKCOUNT.
Referenced by ScoreKeeperNormal::GetPossibleDancePoints(), and ScoreKeeperNormal::GetPossibleGradePoints().
IcyWorld()
void NoteDataUtil::IcyWorld (NoteData & inout, StepsType st, TimingData const & timing_data, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracksHeldAtRow(), NoteData::GetNumTracksWithTap(), NoteData::GetTapNote(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_ADDITION_TAP, TapNoteType_Tap, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
InsertHoldTails()
void NoteDataUtil::InsertHoldTails (NoteData & inout)
References ASSERT, NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), TapNote::iDuration, NoteData::SetTapNote(), Rage::tail(), TapNoteType_HoldHead, TapNoteType_HoldTail, and TapNote::type.
Referenced by GetSMNoteDataString(), and WriteDWINotesField().
InsertIntelligentTaps()
void NoteDataUtil::InsertIntelligentTaps (NoteData & in, int iWindowSizeRows, int iInsertOffsetRows, int iWindowStrideRows, bool bSkippy, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ASSERT, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTapNonEmptyTracks(), NoteData::GetNumTracks(), NoteData::GetNumTracksWithTapOrHoldHead(), NoteData::GetTapFirstNonEmptyTrack(), NoteData::IsHoldNoteAtRow(), max(), min(), Quantize(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), and TAP_ADDITION_TAP.
Referenced by Big(), Quick(), and Skippy().
InsertRows()
void NoteDataUtil::InsertRows (NoteData & nd, int iStartIndex, int iRowsToShift)
References ASSERT, NoteData::ClearRange(), NoteData::CopyRange(), NoteData::GetNumTracks(), MAX_NOTE_ROW, NoteData::RevalidateATIs(), and NoteData::SetNumTracks().
JackJS()
void NoteDataUtil::JackJS (NoteData & inout, StepsType st, TimingData const & timing_data, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracksHeldAtRow(), NoteData::GetNumTracksWithTap(), NoteData::GetTapNote(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_ADDITION_TAP, TapNoteType_Tap, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
Little()
void NoteDataUtil::Little (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetNumTracks(), NoteData::RevalidateATIs(), ROWS_PER_BEAT, NoteData::SetTapNote(), and TAP_EMPTY.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
LoadFromETTNoteDataString()
void NoteDataUtil::LoadFromETTNoteDataString (NoteData & out, const RString & sSMNoteData)
References BEATS_PER_MEASURE, BeatToNoteRow(), NoteData::FindTapNote(), TapNote::iDuration, NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_ORIGINAL_FAKE, TAP_ORIGINAL_HOLD_HEAD, TAP_ORIGINAL_LIFT, TAP_ORIGINAL_MINE, TAP_ORIGINAL_ROLL_HEAD, and TAP_ORIGINAL_TAP.
LoadFromSMNoteDataString()
void NoteDataUtil::LoadFromSMNoteDataString (NoteData & out, const RString & sSMNoteData)
References NoteData::GetNumTracks(), NoteData::Init(), LoadFromSMNoteDataStringWithPlayer(), PLAYER_INVALID, and NoteData::SetNumTracks().
Referenced by Steps::Decompress().
LoadOverlapped()
void NoteDataUtil::LoadOverlapped (const NoteData & in, NoteData & out, int iNewNumTracks)
Autogenerate notes from one type to another.
NOTE: This code assumes that there are more columns in the original type.
Parameters
in The original NoteData.
out the new NoteData.
iNewNumTracks the number of tracks/columns of the new NoteData.
References BeatToNoteRow(), FOREACH_NONEMPTY_ROW_ALL_TRACKS, NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, TapNote::iKeysoundIndex, MAX_NOTE_ROW, MAX_NOTE_TRACKS, PlaceAutoKeysound(), PLAYER_INVALID, TapNote::pn, NoteData::RevalidateATIs(), NoteData::SetNumTracks(), NoteData::SetTapNote(), TapNoteType_AutoKeysound, TapNoteType_Empty, TapNoteType_HoldHead, TapNote::type, and wrap().
Referenced by LoadTransformedSlidingWindow().
LoadTransformedLights()
void NoteDataUtil::LoadTransformedLights (const NoteData & in, NoteData & out, int iNewNumTracks)
LoadTransformedLightsFromTwo()
void NoteDataUtil::LoadTransformedLightsFromTwo (const NoteData & marquee, const NoteData & bass, NoteData & out)
LoadTransformedSlidingWindow()
void NoteDataUtil::LoadTransformedSlidingWindow (const NoteData & in, NoteData & out, int iNewNumTracks)
Autogenerate notes from one type to another.
TODO: Look into a more intelligent way of doing so.
Parameters
in The original NoteData.
out the new NoteData.
iNewNumTracks the number of tracks/columns of the new NoteData.
References CLAMP(), FOREACH_NONEMPTY_ROW_ALL_TRACKS, NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::Init(), NoteData::IsHoldNoteAtRow(), LoadOverlapped(), PLAYER_INVALID, TapNote::pn, NoteData::RevalidateATIs(), ROWS_PER_MEASURE, NoteData::SetNumTracks(), and NoteData::SetTapNote().
Planted()
void NoteDataUtil::Planted (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ConvertTapsToHolds().
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
Quick()
void NoteDataUtil::Quick (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, and InsertIntelligentTaps().
Referenced by BMRize(), LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
RemoveAllButOneTap()
void NoteDataUtil::RemoveAllButOneTap (NoteData & inout, int row)
References NoteData::end(), NoteData::FindTapNote(), NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::RemoveTapNote(), NoteData::RevalidateATIs(), TapNoteType_Tap, and TapNote::type.
Referenced by RemoveStretch().
RemoveAllButPlayer()
void NoteDataUtil::RemoveAllButPlayer (NoteData & inout, PlayerNumber pn)
References NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), PLAYER_INVALID, NoteData::RemoveTapNote(), and NoteData::RevalidateATIs().
RemoveAllTapsExceptForType()
void NoteDataUtil::RemoveAllTapsExceptForType (NoteData & ndInOut, TapNoteType typeToKeep)
References NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), NoteData::RemoveTapNote(), and NoteData::RevalidateATIs().
Referenced by ScreenGameplay::SetupSong().
RemoveAllTapsOfType()
void NoteDataUtil::RemoveAllTapsOfType (NoteData & ndInOut, TapNoteType typeToRemove)
References NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), NoteData::RemoveTapNote(), and NoteData::RevalidateATIs().
Referenced by ScreenGameplay::SetupSong().
RemoveFakes()
void NoteDataUtil::RemoveFakes (NoteData & inout, TimingData const & timing_data, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
Remove all of the fakes from the chart.
Parameters
inout the Notedata to be transformed.
iStartIndex the starting point for transforming.
iEndIndex the ending point for transforming.
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetNumTracks(), TimingData::IsJudgableAtRow(), RemoveSpecificTapNotes(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_EMPTY, and TapNoteType_Fake.
Referenced by TransformNoteData().
RemoveHands()
void NoteDataUtil::RemoveHands (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References RemoveSimultaneousNotes().
Referenced by TransformNoteData().
RemoveHoldNotes()
void NoteDataUtil::RemoveHoldNotes (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
Remove all of the Hold notes.
Parameters
inout the Notedata to be transformed.
iStartIndex the starting point for transforming.
iEndIndex the ending point for transforming.
References NoteData::GetNumTracks(), NoteData::GetTapNoteRangeInclusive(), NoteData::RevalidateATIs(), TapNoteSubType_Hold, TapNoteType_HoldHead, and TapNoteType_Tap.
Referenced by TransformNoteData().
RemoveJumps()
void NoteDataUtil::RemoveJumps (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References RemoveSimultaneousNotes().
Referenced by TransformNoteData().
RemoveLifts()
void NoteDataUtil::RemoveLifts (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
Remove all of the lifts from the chart.
Parameters
inout the Notedata to be transformed.
iStartIndex the starting point for transforming.
iEndIndex the ending point for transforming.
References RemoveSpecificTapNotes(), and TapNoteType_Lift.
Referenced by TransformNoteData().
RemoveMines()
void NoteDataUtil::RemoveMines (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
Remove all of the mines from the chart.
Parameters
inout the Notedata to be transformed.
iStartIndex the starting point for transforming.
iEndIndex the ending point for transforming.
References RemoveSpecificTapNotes(), and TapNoteType_Mine.
Referenced by TransformNoteData().
RemoveQuads()
void NoteDataUtil::RemoveQuads (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References RemoveSimultaneousNotes().
Referenced by TransformNoteData().
RemoveSimultaneousNotes()
void NoteDataUtil::RemoveSimultaneousNotes (NoteData & inout, int iMaxSimultaneous, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracks(), NoteData::GetNumTracksWithTapOrHoldHead(), NoteData::GetTapNote(), NoteData::GetTracksHeldAtRow(), max(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_EMPTY, TapNoteType_HoldHead, TapNoteType_Tap, and TapNote::type.
Referenced by RemoveHands(), RemoveJumps(), and RemoveQuads().
RemoveSpecificTapNotes()
void NoteDataUtil::RemoveSpecificTapNotes (NoteData & inout, TapNoteType tn, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
Remove all of a specific TapNote Type.
Parameters
inout the Notedata to be transformed.
tn the TapNote Type to remove.
iStartIndex the starting point for transforming.
iEndIndex the ending point for transforming.
References FOREACH_NONEMPTY_ROW_IN_TRACK_RANGE, NoteData::GetNumTracks(), NoteData::GetTapNote(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_EMPTY, and TapNote::type.
Referenced by RemoveFakes(), RemoveLifts(), and RemoveMines().
RemoveStretch()
void NoteDataUtil::RemoveStretch (NoteData & inout, StepsType st, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ARRAYLEN, ValidRow::bValidMask, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTapNonEmptyTracks(), RemoveAllButOneTap(), NoteData::RevalidateATIs(), and RowPassesValidMask().
Referenced by TransformNoteData().
RowPassesValidMask()
bool NoteDataUtil::RowPassesValidMask (NoteData & inout, int row, const bool bValidMask[])
References NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNoteType_Empty, and TapNote::type.
Referenced by RemoveStretch().
Scale()
void NoteDataUtil::Scale (NoteData & nd, float fScale)
References ASSERT, NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), TapNote::iDuration, NoteData::RevalidateATIs(), NoteData::SetNumTracks(), NoteData::SetTapNote(), and NoteData::swap().
Referenced by TimingData::ScaleRegion().
ScaleRegion()
void NoteDataUtil::ScaleRegion (NoteData & nd, float fScale, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ASSERT, NoteData::begin(), NoteData::end(), NoteData::GetNumTracks(), GetScaledRow(), TapNote::iDuration, NoteData::RevalidateATIs(), NoteData::SetNumTracks(), NoteData::SetTapNote(), and NoteData::swap().
ShiftLeft()
void NoteDataUtil::ShiftLeft (NoteData & inout)
References ShiftTracks().
ShiftRight()
void NoteDataUtil::ShiftRight (NoteData & inout)
References ShiftTracks().
ShiftTracks()
void NoteDataUtil::ShiftTracks (NoteData & inout, int iShiftBy)
References NoteData::GetNumTracks(), NoteData::LoadTransformed(), MAX_NOTE_TRACKS, and wrap().
Referenced by ShiftLeft(), and ShiftRight().
Skippy()
void NoteDataUtil::Skippy (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, and InsertIntelligentTaps().
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
SnapToNearestNoteType() [1/2]
void NoteDataUtil::SnapToNearestNoteType (NoteData & inout, NoteType nt1, NoteType nt2, int iStartIndex, int iEndIndex)
References BeatToNoteRow(), NoteData::ClearRangeForTrack(), FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracks(), NoteData::GetTapNote(), TapNote::iDuration, NoteData::IsHoldNoteAtRow(), NoteType_Invalid, NoteTypeToBeat(), Quantize(), NoteData::RevalidateATIs(), NoteData::SetTapNote(), TAP_EMPTY, TapNoteType_Empty, TapNoteType_HoldHead, TapNoteType_Tap, and TapNote::type.
Referenced by SnapToNearestNoteType().
SnapToNearestNoteType() [2/2]
void NoteDataUtil::SnapToNearestNoteType (NoteData & inout, NoteType nt, int iStartIndex, int iEndIndex) inline
References NoteType_Invalid, and SnapToNearestNoteType().
Stomp()
void NoteDataUtil::Stomp (NoteData & inout, StepsType st, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), f, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetNumTracks(), NoteData::GetNumTracksHeldAtRow(), NoteData::GetNumTracksWithTap(), NoteData::GetTapNote(), GetTrackMapping(), NoteData::IsThereATapAtRow(), MAX_NOTE_TRACKS, NoteData::RevalidateATIs(), NoteData::SetTapNote(), stomp, TAP_ADDITION_TAP, TapNoteType_Tap, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
SwapSides()
void NoteDataUtil::SwapSides (NoteData & inout)
References NoteData::GetNumTracks(), NoteData::LoadTransformed(), MAX_NOTE_TRACKS, and NoteData::RevalidateATIs().
SwapUpDown()
void NoteDataUtil::SwapUpDown (NoteData & inout, StepsType st)
References NoteData::CopyAll(), NoteData::GetNumTracks(), GetTrackMapping(), NoteData::LoadTransformed(), MAX_NOTE_TRACKS, NoteData::RevalidateATIs(), and swap_up_down.
TransformNoteData()
void NoteDataUtil::TransformNoteData (NoteData & nd, TimingData const & timing_data, const PlayerOptions & po, StepsType st, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References AddMines(), AnchorJS(), backwards, Big(), BMRize(), ChangeHoldsToRolls(), ChangeRollsToHolds(), Echo(), Floored(), IcyWorld(), JackJS(), left, Little(), PlayerOptions::m_bTransforms, PlayerOptions::m_bTurns, mirror, Planted(), Quick(), RemoveFakes(), RemoveHands(), RemoveHoldNotes(), RemoveJumps(), RemoveLifts(), RemoveMines(), RemoveQuads(), RemoveStretch(), NoteData::RevalidateATIs(), right, shuffle, Skippy(), soft_shuffle, Stomp(), super_shuffle, PlayerOptions::TRANSFORM_ANCHORJS, PlayerOptions::TRANSFORM_BIG, PlayerOptions::TRANSFORM_BMRIZE, PlayerOptions::TRANSFORM_ECHO, PlayerOptions::TRANSFORM_FLOORED, PlayerOptions::TRANSFORM_HOLDROLLS, PlayerOptions::TRANSFORM_ICYWORLD, PlayerOptions::TRANSFORM_JACKJS, PlayerOptions::TRANSFORM_LITTLE, PlayerOptions::TRANSFORM_MINES, PlayerOptions::TRANSFORM_NOFAKES, PlayerOptions::TRANSFORM_NOHANDS, PlayerOptions::TRANSFORM_NOHOLDS, PlayerOptions::TRANSFORM_NOJUMPS, PlayerOptions::TRANSFORM_NOLIFTS, PlayerOptions::TRANSFORM_NOMINES, PlayerOptions::TRANSFORM_NOQUADS, PlayerOptions::TRANSFORM_NOROLLS, PlayerOptions::TRANSFORM_NOSTRETCH, PlayerOptions::TRANSFORM_PLANTED, PlayerOptions::TRANSFORM_QUICK, PlayerOptions::TRANSFORM_SKIPPY, PlayerOptions::TRANSFORM_STOMP, PlayerOptions::TRANSFORM_TWISTER, PlayerOptions::TRANSFORM_WIDE, Turn(), PlayerOptions::TURN_BACKWARDS, PlayerOptions::TURN_LEFT, PlayerOptions::TURN_MIRROR, PlayerOptions::TURN_RIGHT, PlayerOptions::TURN_SHUFFLE, PlayerOptions::TURN_SOFT_SHUFFLE, PlayerOptions::TURN_SUPER_SHUFFLE, Twister(), and Wide().
Referenced by ScoreKeeperNormal::Load(), and Player::Load().
Turn()
void NoteDataUtil::Turn (NoteData & inout, StepsType st, TrackMapping tt, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References NoteData::CopyAll(), NoteData::GetNumTracks(), GetTrackMapping(), NoteData::LoadTransformed(), MAX_NOTE_TRACKS, NoteData::RevalidateATIs(), super_shuffle, and SuperShuffleTaps().
Referenced by TransformNoteData().
Twister()
void NoteDataUtil::Twister (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References ConvertTapsToHolds().
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().
Wide()
void NoteDataUtil::Wide (NoteData & inout, int iStartIndex = 0, int iEndIndex = MAX_NOTE_ROW)
References BeatToNoteRow(), CLAMP(), f, FOREACH_NONEMPTY_ROW_ALL_TRACKS_RANGE, NoteData::GetFirstTrackWithTap(), NoteData::GetNumTapNonEmptyTracks(), NoteData::GetNumTracks(), NoteData::GetNumTracksWithTap(), NoteData::GetTapNote(), NoteData::IsHoldNoteAtRow(), NoteRowToBeat(), Quantize(), NoteData::RevalidateATIs(), ROWS_PER_BEAT, NoteData::SetTapNote(), TAP_ADDITION_TAP, TapNoteType_Empty, TapNoteType_Fake, and TapNote::type.
Referenced by LunaPlayerOptions::LunaPlayerOptions(), and TransformNoteData().