Etterna: SubscriptionManager< T > Class Template Reference
SubscriptionManager< T > Class Template Reference
#include <SubscriptionManager.h>
Public Member Functions
set< T * > & Get ()
void Subscribe (T *p)
void Unsubscribe (T *p)
Public Attributes
set< T * > * m_pSubscribers
Member Function Documentation
Get()
template<class T> set<T*>& SubscriptionManager< T >::Get () inline
References SubscriptionManager< T >::m_pSubscribers.
Subscribe()
template<class T> void SubscriptionManager< T >::Subscribe (T * p) inline
References ASSERT_M.
Referenced by IPreference::IPreference(), LocalizedString::LocalizedString(), LuaBinding::LuaBinding(), and ThemeManager::Subscribe().
Unsubscribe()
template<class T> void SubscriptionManager< T >::Unsubscribe (T * p) inline
References ASSERT.
Referenced by ThemeManager::Unsubscribe(), IPreference::~IPreference(), LocalizedString::~LocalizedString(), and LuaBinding::~LuaBinding().
Member Data Documentation
m_pSubscribers
template<class T> set<T*>* SubscriptionManager< T >::m_pSubscribers
Referenced by ThemeManager::ClearSubscribers(), SubscriptionManager< T >::Get(), IPreference::GetPreferenceByName(), IPreference::LoadAllDefaults(), IPreference::ReadAllDefaultsFromNode(), IPreference::ReadAllPrefsFromNode(), LocalizedString::RegisterLocalizer(), ThemeManager::ReloadSubscribers(), and IPreference::SavePrefsToNode().
The documentation for this class was generated from the following file:
SubscriptionManager.h