Etterna: OptionRowHandlerStepsType Class Reference
OptionRowHandlerStepsType Class Reference
Public Member Functions
OptionRowHandlerStepsType ()
void Init () override
bool LoadInternal (const Commands &cmds) override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual ReloadChanged Reload ()
virtual int GetDefaultOption () const
virtual void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const
virtual RString GetScreen (int) const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
BroadcastOnChange< StepsType > * m_pstToFill
vector< StepsType > m_vStepsTypesToShow
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerStepsType()
OptionRowHandlerStepsType::OptionRowHandlerStepsType () inline
References Init().
Member Function Documentation
ExportOption()
int OptionRowHandlerStepsType::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References FOREACH_CONST, OptionRowHandlerUtil::GetOneSelection(), and BroadcastOnChange< T >::Set().
ImportOption()
void OptionRowHandlerStepsType::ImportOption (OptionRow * pRow, const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References FOREACH_CONST, GAMESTATE, and GameState::m_pCurSteps.
Init()
void OptionRowHandlerStepsType::Init () inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::Init().
Referenced by OptionRowHandlerStepsType().
LoadInternal()
bool OptionRowHandlerStepsType::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
References CHECK_BLANK_ARG, CHECK_WRONG_NUM_ARGS, FOREACH_CONST, GAMEMAN, GAMESTATE, Command::GetArg(), StepsTypeInfo::GetLocalizedString(), GameManager::GetStepsTypeInfo(), ThemeMetricStepsTypesToShow::GetValue(), LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, GameState::m_pCurSteps, OptionRowDefinition::m_sName, OptionRowDefinition::m_vEnabledForPlayers, OptionRowDefinition::m_vsChoices, OptionRowHandler::m_vsReloadRowMessages, Message_CurrentStepsP1Changed, Message_EditStepsTypeChanged, MessageIDToString(), ROW_INVALID_IF, Command::Arg::s, BroadcastOnChange< T >::Set(), CommonMetrics::STEPS_TYPES_TO_SHOW, StepsType_Invalid, and Commands::v.
Member Data Documentation
m_pstToFill
BroadcastOnChange<StepsType>* OptionRowHandlerStepsType::m_pstToFill
m_vStepsTypesToShow
vector<StepsType> OptionRowHandlerStepsType::m_vStepsTypesToShow
The documentation for this class was generated from the following file:
OptionRowHandler.cpp