Etterna: RageSoundDriver_JACK Class Reference
RageSoundDriver_JACK Class Reference
#include <RageSoundDriver_JACK.h>
Public Member Functions
RageSoundDriver_JACK ()
~RageSoundDriver_JACK ()
RString Init ()
int GetSampleRate () const
int64_t GetPosition () const
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
virtual float GetPlayLatency () const
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
RString ConnectPorts ()
int ProcessCallback (jack_nframes_t nframes)
int SampleRateCallback (jack_nframes_t nframes)
Static Private Member Functions
static int ProcessTrampoline (jack_nframes_t nframes, void *arg)
static int SampleRateTrampoline (jack_nframes_t nframes, void *arg)
Private Attributes
jack_client_t * client
jack_port_t * port_l
jack_port_t * port_r
int sample_rate
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
virtual void SetupDecodingThread ()
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_JACK()
RageSoundDriver_JACK::RageSoundDriver_JACK ()
References client, port_l, and port_r.
~RageSoundDriver_JACK()
RageSoundDriver_JACK::~RageSoundDriver_JACK ()
References client, port_l, and port_r.
Member Function Documentation
ConnectPorts()
RString RageSoundDriver_JACK::ConnectPorts () private
References client, FOREACH, PrefsManager::m_iSoundDevice, port_l, port_r, PREFSMAN, and split().
Referenced by Init().
GetPosition()
int64_t RageSoundDriver_JACK::GetPosition () const virtual
Implements RageSoundDriver.
References client.
GetSampleRate()
int RageSoundDriver_JACK::GetSampleRate () const virtual
Reimplemented from RageSoundDriver.
References sample_rate.
Init()
RString RageSoundDriver_JACK::Init () virtual
Reimplemented from RageSoundDriver.
References client, ConnectPorts(), LOG, port_l, port_r, ProcessTrampoline(), PRODUCT_FAMILY, sample_rate, SampleRateTrampoline(), RageSoundDriver::StartDecodeThread(), RageLog::Trace(), and RageLog::Warn().
ProcessCallback()
int RageSoundDriver_JACK::ProcessCallback (jack_nframes_t nframes) private
References client, RageSoundDriver::MixDeinterlaced(), port_l, and port_r.
ProcessTrampoline()
int RageSoundDriver_JACK::ProcessTrampoline (jack_nframes_t nframes, void * arg) static private
Referenced by Init().
SampleRateCallback()
int RageSoundDriver_JACK::SampleRateCallback (jack_nframes_t nframes) private
References client, and sample_rate.
SampleRateTrampoline()
int RageSoundDriver_JACK::SampleRateTrampoline (jack_nframes_t nframes, void * arg) static private
Referenced by Init().
Member Data Documentation
client
jack_client_t* RageSoundDriver_JACK::client private
Referenced by ConnectPorts(), GetPosition(), Init(), ProcessCallback(), RageSoundDriver_JACK(), SampleRateCallback(), and ~RageSoundDriver_JACK().
port_l
jack_port_t* RageSoundDriver_JACK::port_l private
Referenced by ConnectPorts(), Init(), ProcessCallback(), RageSoundDriver_JACK(), and ~RageSoundDriver_JACK().
port_r
jack_port_t* RageSoundDriver_JACK::port_r private
Referenced by ConnectPorts(), Init(), ProcessCallback(), RageSoundDriver_JACK(), and ~RageSoundDriver_JACK().
sample_rate
int RageSoundDriver_JACK::sample_rate private
Referenced by GetSampleRate(), Init(), and SampleRateCallback().
The documentation for this class was generated from the following files:
RageSoundDriver_JACK.h
RageSoundDriver_JACK.cpp