Etterna: PacketFunctions Class Reference
PacketFunctions Class Reference
#include <NetworkSyncManager.h>
Public Member Functions
uint8_t Read1 ()
uint16_t Read2 ()
uint32_t Read4 ()
RString ReadNT ()
void Write1 (uint8_t Data)
void Write2 (uint16_t Data)
void Write4 (uint32_t Data)
void WriteNT (const RString &Data)
void ClearPacket ()
Public Attributes
unsigned char Data [NETMAXBUFFERSIZE]
int Position
int size
Member Function Documentation
ClearPacket()
void PacketFunctions::ClearPacket ()
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::Connect(), SMOProtocol::CreateNewRoom(), SMOProtocol::EnterRoom(), SMOProtocol::Login(), SMOProtocol::ProcessInput(), SMOProtocol::ReportNSSOnOff(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), SMOProtocol::RequestRoomInfo(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), and SMOProtocol::StartRequest().
Read1()
uint8_t PacketFunctions::Read1 ()
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::Connect(), SMOProtocol::DealWithSMOnlinePack(), SMOProtocol::ProcessInput(), SMOProtocol::StartRequest(), and SMOProtocol::Update().
Read2()
uint16_t PacketFunctions::Read2 ()
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::ProcessInput(), and SMOProtocol::Update().
Read4()
uint32_t PacketFunctions::Read4 ()
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::Connect(), and SMOProtocol::ProcessInput().
ReadNT()
RString PacketFunctions::ReadNT ()
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::Connect(), SMOProtocol::DealWithSMOnlinePack(), SMOProtocol::ProcessInput(), and SMOProtocol::Update().
Write1()
void PacketFunctions::Write1 (uint8_t Data)
References Data, LOG, NETMAXBUFFERSIZE, Position, and RageLog::Trace().
Referenced by SMOProtocol::Connect(), SMOProtocol::CreateNewRoom(), SMOProtocol::EnterRoom(), SMOProtocol::Login(), SMOProtocol::ProcessInput(), SMOProtocol::ReportNSSOnOff(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), SMOProtocol::RequestRoomInfo(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), and SMOProtocol::StartRequest().
Write2()
void PacketFunctions::Write2 (uint16_t Data)
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::ReportScore().
Write4()
void PacketFunctions::Write4 (uint32_t Data)
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::ReportScore().
WriteNT()
void PacketFunctions::WriteNT (const RString & Data)
References Data, NETMAXBUFFERSIZE, and Position.
Referenced by SMOProtocol::Connect(), SMOProtocol::CreateNewRoom(), SMOProtocol::EnterRoom(), SMOProtocol::Login(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportStyle(), SMOProtocol::RequestRoomInfo(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), and SMOProtocol::StartRequest().
Member Data Documentation
Data
unsigned char PacketFunctions::Data[NETMAXBUFFERSIZE]
Referenced by ClearPacket(), SMOProtocol::Connect(), SMOProtocol::ProcessInput(), Read1(), Read2(), Read4(), ReadNT(), SMOProtocol::ReportNSSOnOff(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), SMOProtocol::SendSMOnline(), SMOProtocol::StartRequest(), SMOProtocol::Update(), Write1(), Write2(), Write4(), and WriteNT().
Position
int PacketFunctions::Position
Referenced by ClearPacket(), SMOProtocol::Connect(), SMOProtocol::ProcessInput(), Read1(), Read2(), Read4(), ReadNT(), SMOProtocol::ReportNSSOnOff(), SMOProtocol::ReportPlayerOptions(), SMOProtocol::ReportScore(), SMOProtocol::ReportSongOver(), SMOProtocol::ReportStyle(), SMOProtocol::SelectUserSong(), SMOProtocol::SendChat(), SMOProtocol::SendSMOnline(), SMOProtocol::StartRequest(), SMOProtocol::Update(), Write1(), Write2(), Write4(), and WriteNT().
size
int PacketFunctions::size
Referenced by SMOProtocol::ProcessInput().
The documentation for this class was generated from the following files:
NetworkSyncManager.h
NetworkSyncManager.cpp