Etterna: CreateZip Class Reference
CreateZip Class Reference
#include <CreateZip.h>
Public Member Functions
CreateZip ()
bool Start (RageFile *f)
bool AddFile (RString fn)
bool AddDir (RString fn)
bool Finish ()
RString GetError ()
Private Attributes
TZip * hz
Constructor & Destructor Documentation
CreateZip()
CreateZip::CreateZip ()
References hz.
Member Function Documentation
AddDir()
bool CreateZip::AddDir (RString fn)
References TZip::Add(), hz, lasterrorZ, MakeDestZipFileName(), ZIP_FOLDER, and ZR_OK.
AddFile()
bool CreateZip::AddFile (RString fn)
References TZip::Add(), hz, lasterrorZ, MakeDestZipFileName(), ZIP_FILENAME, and ZR_OK.
Finish()
bool CreateZip::Finish ()
References TZip::Close(), hz, lasterrorZ, and ZR_OK.
GetError()
RString CreateZip::GetError ()
References FormatZipMessageZ(), and lasterrorZ.
Start()
bool CreateZip::Start (RageFile * f)
References hz, lasterrorZ, TZip::Start(), and ZR_OK.
Member Data Documentation
hz
TZip* CreateZip::hz private
Referenced by AddDir(), AddFile(), CreateZip(), Finish(), and Start().
The documentation for this class was generated from the following files:
CreateZip.h
CreateZip.cpp