Etterna: RageInputDevice.cpp File Reference
RageInputDevice.cpp File Reference
#include "RageInputDevice.h"
#include "Foreach.h"
#include "LocalizedString.h"
#include "RageUtil.h"
#include "global.h"
Functions
XToString (InputDeviceState)
XToLocalizedString (InputDeviceState)
LuaXType (InputDevice)
static void InitNames ()
RString DeviceButtonToString (DeviceButton key)
DeviceButton StringToDeviceButton (const RString &s)
LuaXType (DeviceButton)
XToString (InputDevice)
StringToX (InputDevice)
Variables
static const char * InputDeviceStateNames []
static map< DeviceButton, RString > g_mapNamesToString
static map< RString, DeviceButton > g_mapStringToNames
static const char * InputDeviceNames []
Function Documentation
DeviceButtonToString()
RString DeviceButtonToString (DeviceButton key)
References g_mapNamesToString, InitNames(), JOY_BUTTON_1, JOY_BUTTON_32, KEY_LAST_OTHER, KEY_OTHER_0, MIDI_FIRST, MIDI_LAST, and ssprintf().
Referenced by InputHandler::GetDeviceSpecificInputString(), RageInput::GetLocalizedInputString(), InputHandler::GetLocalizedInputString(), and DeviceInput::ToString().
InitNames()
static void InitNames () static
References FOREACHM, g_mapNamesToString, g_mapStringToNames, JOY_AUX_1, JOY_AUX_2, JOY_AUX_3, JOY_AUX_4, JOY_DOWN, JOY_DOWN_2, JOY_HAT_DOWN, JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_LEFT, JOY_LEFT_2, JOY_RIGHT, JOY_RIGHT_2, JOY_ROT_DOWN, JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_UP, JOY_ROT_Z_DOWN, JOY_ROT_Z_UP, JOY_UP, JOY_UP_2, JOY_Z_DOWN, JOY_Z_UP, KEY_BACK, KEY_BACKSLASH, KEY_CAPSLOCK, KEY_COLON, KEY_COMMA, KEY_DEL, KEY_DOWN, KEY_END, KEY_ENTER, KEY_ESC, KEY_F1, KEY_F10, KEY_F11, KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_FN, KEY_HOME, KEY_INSERT, KEY_KP_ASTERISK, KEY_KP_C0, KEY_KP_C1, KEY_KP_C2, KEY_KP_C3, KEY_KP_C4, KEY_KP_C5, KEY_KP_C6, KEY_KP_C7, KEY_KP_C8, KEY_KP_C9, KEY_KP_ENTER, KEY_KP_EQUAL, KEY_KP_HYPHEN, KEY_KP_PERIOD, KEY_KP_PLUS, KEY_KP_SLASH, KEY_LALT, KEY_LCTRL, KEY_LEFT, KEY_LMETA, KEY_LSHIFT, KEY_LSUPER, KEY_MENU, KEY_NUMLOCK, KEY_PAUSE, KEY_PERIOD, KEY_PGDN, KEY_PGUP, KEY_PRTSC, KEY_RALT, KEY_RCTRL, KEY_RIGHT, KEY_RMETA, KEY_RSHIFT, KEY_RSUPER, KEY_SCRLLOCK, KEY_SPACE, KEY_TAB, KEY_UP, MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT, MOUSE_WHEELDOWN, and MOUSE_WHEELUP.
Referenced by DeviceButtonToString(), and StringToDeviceButton().
LuaXType() [1/2]
LuaXType (InputDevice)
LuaXType() [2/2]
LuaXType (DeviceButton)
StringToDeviceButton()
DeviceButton StringToDeviceButton (const RString & s)
References DeviceButton_Invalid, enum_add2(), g_mapStringToNames, InitNames(), JOY_BUTTON_1, KEY_OTHER_0, MIDI_FIRST, and MOUSE_LEFT.
Referenced by DeviceInput::FromString(), and LunaInputFilter::IsBeingPressed().
StringToX()
StringToX (InputDevice)
XToLocalizedString()
XToLocalizedString (InputDeviceState)
XToString() [1/2]
XToString (InputDeviceState)
XToString() [2/2]
XToString (InputDevice)
Variable Documentation
g_mapNamesToString
map<DeviceButton, RString> g_mapNamesToString static
Referenced by DeviceButtonToString(), and InitNames().
g_mapStringToNames
map<RString, DeviceButton> g_mapStringToNames static
Referenced by InitNames(), and StringToDeviceButton().
InputDeviceNames
const char* InputDeviceNames[] static
Initial value:
= {
    "Key",   "Joy1",  "Joy2",  "Joy3",  "Joy4",  "Joy5",  "Joy6",  "Joy7",
    "Joy8",  "Joy9",  "Joy10", "Joy11", "Joy12", "Joy13", "Joy14", "Joy15",
    "Joy16", "Joy17", "Joy18", "Joy19", "Joy20", "Joy21", "Joy22", "Joy23",
    "Joy24", "Joy25", "Joy26", "Joy27", "Joy28", "Joy29", "Joy30", "Joy31",
    "Joy32", "Pump1", "Pump2", "Midi",  "Mouse", "PIUIO",
}
InputDeviceStateNames
const char* InputDeviceStateNames[] static
Initial value:
= {
    "Connected",
    "Unplugged",
    "NeedsMultitap",
    "NoInputHandler",
}