Etterna: LoadedDriver Struct Reference
LoadedDriver Struct Reference
Public Member Functions
LoadedDriver ()
RString GetPath (const RString &sPath) const
Public Attributes
RageFileDriver * m_pDriver
RString m_sType
RString m_sRoot
RString m_sMountPoint
int m_iRefs
Constructor & Destructor Documentation
LoadedDriver()
LoadedDriver::LoadedDriver () inline
Member Function Documentation
GetPath()
RString LoadedDriver::GetPath (const RString & sPath) const
References StdString::CStdStr< CT >::Left(), m_sMountPoint, and StdString::CStdStr< CT >::Right().
Referenced by RageFileManager::GetDirListing(), RageFileManager::OpenForReading(), RageFileManager::OpenForWriting(), and RageFileManager::ResolvePath().
Member Data Documentation
m_iRefs
int LoadedDriver::m_iRefs
m_pDriver
RageFileDriver* LoadedDriver::m_pDriver
Referenced by RageFileManager::GetDirListing(), RageFileManager::Mount(), RageFileManager::OpenForReading(), RageFileManager::OpenForWriting(), and RageFileManager::RageFileManager().
m_sMountPoint
RString LoadedDriver::m_sMountPoint
Referenced by RageFileManager::GetDirListing(), GetPath(), and RageFileManager::ResolvePath().
m_sRoot
RString LoadedDriver::m_sRoot
Referenced by RageFileManager::ResolvePath().
m_sType
RString LoadedDriver::m_sType
Referenced by RageFileManager::ResolvePath().
The documentation for this struct was generated from the following file:
RageFileManager.cpp