Etterna: ALSA9Dynamic.h File Reference
ALSA9Dynamic.h File Reference
#include "global.h"
#include <alsa/asoundlib.h>
#include "ALSA9Functions.h"
Macros
#define FUNC(ret, name, proto) typedef ret(*name##_f) proto
#define FUNC(ret, name, proto) extern name##_f d##name
#define dsnd_pcm_hw_params_alloca(ptr)
#define dsnd_pcm_sw_params_alloca(ptr)
#define dsnd_pcm_info_alloca(ptr)
#define dsnd_ctl_card_info_alloca(ptr)
#define dsnd_pcm_status_alloca(ptr)
Functions
RString LoadALSA ()
void UnloadALSA ()
Macro Definition Documentation
dsnd_ctl_card_info_alloca
#define dsnd_ctl_card_info_alloca (ptr)
Value:
{                                                                          \
        assert(ptr);                                                           \
        *ptr = (snd_ctl_card_info_t*)alloca(dsnd_ctl_card_info_sizeof());      \
        memset(*ptr, 0, dsnd_ctl_card_info_sizeof());                          \
    }
Referenced by Alsa9Buf::GetHardwareID(), and Alsa9Buf::GetSoundCardDebugInfo().
dsnd_pcm_hw_params_alloca
#define dsnd_pcm_hw_params_alloca (ptr)
Value:
{                                                                          \
        assert(ptr);                                                           \
        *ptr = (snd_pcm_hw_params_t*)alloca(dsnd_pcm_hw_params_sizeof());      \
        memset(*ptr, 0, dsnd_pcm_hw_params_sizeof());                          \
    }
Referenced by Alsa9Buf::SetHWParams().
dsnd_pcm_info_alloca
#define dsnd_pcm_info_alloca (ptr)
Value:
{                                                                          \
        assert(ptr);                                                           \
        *ptr = (snd_pcm_info_t*)alloca(dsnd_pcm_info_sizeof());                \
        memset(*ptr, 0, dsnd_pcm_info_sizeof());                               \
    }
Referenced by Alsa9Buf::GetSoundCardDebugInfo().
dsnd_pcm_status_alloca
#define dsnd_pcm_status_alloca (ptr)
Value:
do {                                                                       \
        assert(ptr);                                                           \
        *ptr = (snd_pcm_status_t*)alloca(dsnd_pcm_status_sizeof());            \
        memset(*ptr, 0, dsnd_pcm_status_sizeof());                             \
    } while (0)
dsnd_pcm_sw_params_alloca
#define dsnd_pcm_sw_params_alloca (ptr)
Value:
{                                                                          \
        assert(ptr);                                                           \
        *ptr = (snd_pcm_sw_params_t*)alloca(dsnd_pcm_sw_params_sizeof());      \
        memset(*ptr, 0, dsnd_pcm_sw_params_sizeof());                          \
    }
Referenced by Alsa9Buf::SetSWParams().
FUNC [1/2]
#define FUNC (ret, name, proto) typedef ret(*name##_f) proto
FUNC [2/2]
#define FUNC (ret, name, proto) extern name##_f d##name
Function Documentation
LoadALSA()
RString LoadALSA ()
References ASSERT, Handle, IsADirectory(), ssprintf(), and UnloadALSA().
Referenced by RageSoundDriver_ALSA9_Software::Init().
UnloadALSA()
void UnloadALSA ()
References Handle.
Referenced by LoadALSA(), and RageSoundDriver_ALSA9_Software::~RageSoundDriver_ALSA9_Software().