Etterna: RageFileDriverDeflate.h File Reference
RageFileDriverDeflate.h File Reference
#include "RageFileBasic.h"
Classes
class RageFileObjInflate
class RageFileObjDeflate
class RageFileObjGzip
Typedefs
using z_stream = struct z_stream_s
Functions
RageFileObjInflate * GunzipFile (RageFileBasic *pFile, RString &sError, uint32_t *iCRC32)
void GzipString (const RString &sIn, RString &sOut)
bool GunzipString (const RString &sIn, RString &sOut, RString &sError)
Typedef Documentation
z_stream
using z_stream = struct z_stream_s
Function Documentation
GunzipFile()
RageFileObjInflate* GunzipFile (RageFileBasic * pFile, RString & sError, uint32_t * iCRC32)
References ASSERT, RageFileDriverSlice::DeleteFileWhenFinished(), RageFileObjInflate::DeleteFileWhenFinished(), RageFileObj::EnableCRC32(), FCOMMENT, FEXTRA, FHCRC, FNAME, FileReading::read_16_le(), FileReading::read_32_le(), FileReading::read_8(), FileReading::read_u16_le(), FileReading::read_u32_le(), FileReading::ReadBytes(), FileReading::Seek(), FileReading::SkipBytes(), ssprintf(), and UNSUPPORTED_MASK.
Referenced by GunzipString(), XMLProfile::LoadEttFromDir(), XMLProfile::LoadStatsFromDir(), and XMLProfile::LoadStatsXmlForConversion().
GunzipString()
bool GunzipString (const RString & sIn, RString & sOut, RString & sError)
References ASSERT, RageFileBasic::GetCRC32(), GunzipFile(), RageFileObjMem::PutString(), RageFileBasic::Read(), and SAFE_DELETE.
GzipString()
void GzipString (const RString & sIn, RString & sOut)
References RageFileObjGzip::Finish(), RageFileObjMem::GetString(), RageFileObjGzip::Start(), and RageFileObj::Write().