Etterna: RageSurface_Load_JPEG.cpp File Reference
RageSurface_Load_JPEG.cpp File Reference
#include "RageSurface_Load_JPEG.h"
#include "RageFile.h"
#include "RageSurface.h"
#include "RageUtil.h"
#include "global.h"
#include <csetjmp>
#include "jerror.h"
#include "jpeglib.h"
Classes
struct my_jpeg_error_mgr
struct RageFile_source_mgr
Functions
void my_output_message (j_common_ptr cinfo)
void my_error_exit (j_common_ptr cinfo)
void RageFile_JPEG_init_source (j_decompress_ptr cinfo)
boolean RageFile_JPEG_fill_input_buffer (j_decompress_ptr cinfo)
void RageFile_JPEG_skip_input_data (j_decompress_ptr cinfo, long num_bytes)
void RageFile_JPEG_term_source (j_decompress_ptr cinfo)
static RageSurface * RageSurface_Load_JPEG (RageFile *f, const char *fn, char errorbuf[JMSG_LENGTH_MAX])
RageSurfaceUtils::OpenResult RageSurface_Load_JPEG (const RString &sPath, RageSurface *&ret, bool bHeaderOnly, RString &error)
Function Documentation
my_error_exit()
void my_error_exit (j_common_ptr cinfo)
References my_jpeg_error_mgr::setjmp_buffer.
Referenced by RageSurface_Load_JPEG().
my_output_message()
void my_output_message (j_common_ptr cinfo)
References my_jpeg_error_mgr::errorbuf.
Referenced by RageSurface_Load_JPEG().
RageFile_JPEG_fill_input_buffer()
boolean RageFile_JPEG_fill_input_buffer (j_decompress_ptr cinfo)
References RageFile_source_mgr::buffer, RageFile_source_mgr::file, RageFile_source_mgr::pub, RageFile::Read(), and RageFile_source_mgr::start_of_file.
Referenced by RageSurface_Load_JPEG().
RageFile_JPEG_init_source()
void RageFile_JPEG_init_source (j_decompress_ptr cinfo)
References RageFile_source_mgr::pub, and RageFile_source_mgr::start_of_file.
Referenced by RageSurface_Load_JPEG().
RageFile_JPEG_skip_input_data()
void RageFile_JPEG_skip_input_data (j_decompress_ptr cinfo, long num_bytes)
References RageFile_source_mgr::file, min(), RageFile_source_mgr::pub, RageFile::Seek(), and RageFile::Tell().
Referenced by RageSurface_Load_JPEG().
RageFile_JPEG_term_source()
void RageFile_JPEG_term_source (j_decompress_ptr cinfo)
Referenced by RageSurface_Load_JPEG().
RageSurface_Load_JPEG() [1/2]
static RageSurface* RageSurface_Load_JPEG (RageFile * f, const char * fn, char errorbuf[JMSG_LENGTH_MAX]) static
References RageSurfaceColor::a, RageSurfaceColor::b, RageSurfacePalette::colors, CreateSurface(), my_jpeg_error_mgr::errorbuf, f, RageFile_source_mgr::file, RageSurface::fmt, RageSurfaceColor::g, my_error_exit(), my_output_message(), RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, RageFile_source_mgr::pub, my_jpeg_error_mgr::pub, RageSurfaceColor::r, RageFile_JPEG_fill_input_buffer(), RageFile_JPEG_init_source(), RageFile_JPEG_skip_input_data(), RageFile_JPEG_term_source(), my_jpeg_error_mgr::setjmp_buffer, and Swap24BE().
Referenced by RageSurface_Load_JPEG(), and TryOpenFile().
RageSurface_Load_JPEG() [2/2]
RageSurfaceUtils::OpenResult RageSurface_Load_JPEG (const RString & sPath, RageSurface *& ret, bool bHeaderOnly, RString & error)
References my_jpeg_error_mgr::errorbuf, f, RageFile::GetError(), RageFile::Open(), RageSurfaceUtils::OPEN_FATAL_ERROR, RageSurfaceUtils::OPEN_OK, RageSurfaceUtils::OPEN_UNKNOWN_FILE_FORMAT, and RageSurface_Load_JPEG().