Etterna: LunaGameState Class Reference
LunaGameState Class Reference
Allow Lua to have access to the GameState.
Public Member Functions
DEFINE_METHOD (IsPlayerEnabled, IsPlayerEnabled(Enum::Check< PlayerNumber >(L, 1))) DEFINE_METHOD(IsHumanPlayer
IsHumanPlayer (Enum::Check< PlayerNumber >(L, 1))) DEFINE_METHOD(GetPlayerDisplayName
GetPlayerDisplayName (Enum::Check< PlayerNumber >(L, 1))) static int SetMultiplayer(T *p
DEFINE_METHOD (GetPreferredDifficulty, m_PreferredDifficulty[Enum::Check< PlayerNumber >(L, 1)]) DEFINE_METHOD(PlayerIsUsingModifier
PlayerIsUsingModifier (Enum::Check< PlayerNumber >(L, 1), SArg(2))) static int GetSongPosition(T *p
DEFINE_METHOD (IsSideJoined, m_bSideIsJoined[Enum::Check< PlayerNumber >(L, 1)]) DEFINE_METHOD(GetSongOptionsString
m_SongOptions GetCurrent ().GetString()) static int GetSessionTime(T *p
DEFINE_METHOD (GetEditLocalProfileID, m_sEditLocalProfileID.Get())
DEFINE_METHOD (GetPreferredSongGroup, m_sPreferredSongGroup.Get())
LunaGameState ()
Public Member Functions inherited from Luna< GameState >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetNumMultiplayerNoteFields (T *p, lua_State *L)
static int GetPlayerState (T *p, lua_State *L)
static int GetMultiPlayerState (T *p, lua_State *L)
static int ApplyGameCommand (T *p, lua_State *L)
static int GetCurrentSong (T *p, lua_State *L)
static int SetCurrentSong (T *p, lua_State *L)
static int CanSafelyEnterGameplay (T *p, lua_State *L)
static void SetCompatibleStyleOrError (T *p, lua_State *L, StepsType stype, PlayerNumber pn)
static int GetCurrentSteps (T *p, lua_State *L)
static int SetCurrentSteps (T *p, lua_State *L)
static int GetPreferredSong (T *p, lua_State *L)
static int SetPreferredSong (T *p, lua_State *L)
static int SetTemporaryEventMode (T *p, lua_State *L)
static int Env (T *p, lua_State *L)
static int SetPreferredDifficulty (T *p, lua_State *L)
static int GetSongOptions (T *p, lua_State *L)
static int GetSongOptionsObject (T *p, lua_State *L)
static int GetDefaultSongOptions (T *p, lua_State *L)
static int ApplyPreferredSongOptionsToOtherLevels (T *p, lua_State *L)
static int ApplyStageModifiers (T *p, lua_State *L)
static int ApplyPreferredModifiers (T *p, lua_State *L)
static int SetSongOptions (T *p, lua_State *L)
static int GetStageResult (T *p, lua_State *L)
static int IsWinner (T *p, lua_State *L)
static int IsDraw (T *p, lua_State *L)
static int GetCurrentGame (T *p, lua_State *L)
static int GetEditLocalProfile (T *p, lua_State *L)
static int GetCurrentStepsCredits (T *t, lua_State *L)
static int SetPreferredSongGroup (T *p, lua_State *L)
static int GetHumanPlayers (T *p, lua_State *L)
static int GetEnabledPlayers (T *, lua_State *L)
static int GetCurrentStyle (T *p, lua_State *L)
static int GetNumStagesForCurrentSongAndStepsOrCourse (T *, lua_State *L)
static int GetNumStagesLeft (T *p, lua_State *L)
static int GetGameSeed (T *p, lua_State *L)
static int GetStageSeed (T *p, lua_State *L)
static int SaveLocalData (T *p, lua_State *L)
static int SetJukeboxUsesModifiers (T *p, lua_State *L)
static int Reset (T *p, lua_State *L)
static int JoinPlayer (T *p, lua_State *L)
static int UnjoinPlayer (T *p, lua_State *L)
static int JoinInput (T *p, lua_State *L)
static int GetSongPercent (T *p, lua_State *L)
static int GetCharacter (T *p, lua_State *L)
static int SetCharacter (T *p, lua_State *L)
static int GetExpandedSectionName (T *p, lua_State *L)
static int AddStageToPlayer (T *p, lua_State *L)
static int InsertCoin (T *p, lua_State *L)
static int InsertCredit (T *p, lua_State *L)
static int CurrentOptionsDisqualifyPlayer (T *p, lua_State *L)
static int ResetPlayerOptions (T *p, lua_State *L)
static int RefreshNoteSkinData (T *p, lua_State *L)
static int Dopefish (T *p, lua_State *L)
static int LoadProfiles (T *p, lua_State *L)
static int SaveProfiles (T *p, lua_State *L)
static int SetFailTypeExplicitlySet (T *p, lua_State *L)
static int StoreRankingName (T *p, lua_State *L)
static bool AreStyleAndPlayModeCompatible (T *p, lua_State *L, const Style *style, PlayMode pm)
static int SetCurrentStyle (T *p, lua_State *L)
static int SetCurrentPlayMode (T *p, lua_State *L)
static int IsCourseMode (T *p, lua_State *L)
static int GetCoinMode (T *p, lua_State *L)
static int UpdateDiscordMenu (T *p, lua_State *L)
static int UpdateDiscordPresence (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< GameState >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Public Attributes
lua_State * L
COMMON_RETURN_SELF
return
m_SongOptions lua_State * L
Additional Inherited Members
Static Public Attributes inherited from Luna< GameState >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< GameState >
using T = GameState
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< GameState >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the GameState.
Constructor & Destructor Documentation
LunaGameState()
LunaGameState::LunaGameState () inline
References ADD_METHOD, AddStageToPlayer(), ApplyGameCommand(), ApplyPreferredModifiers(), ApplyPreferredSongOptionsToOtherLevels(), ApplyStageModifiers(), CanSafelyEnterGameplay(), CurrentOptionsDisqualifyPlayer(), Dopefish(), Env(), GetCharacter(), GetCoinMode(), GetCurrentGame(), GetCurrentSong(), GetCurrentSteps(), GetCurrentStepsCredits(), GetCurrentStyle(), GetDefaultSongOptions(), GetEditLocalProfile(), GetEnabledPlayers(), GetExpandedSectionName(), GetGameSeed(), GetHumanPlayers(), GetMultiPlayerState(), GetNumStagesForCurrentSongAndStepsOrCourse(), GetNumStagesLeft(), GetPlayerDisplayName(), GetPlayerState(), GetPreferredSong(), GetSongOptions(), GetSongOptionsObject(), GetSongPercent(), GetStageResult(), GetStageSeed(), InsertCoin(), InsertCredit(), IsCourseMode(), IsDraw(), IsHumanPlayer(), IsWinner(), JoinInput(), JoinPlayer(), LoadProfiles(), RefreshNoteSkinData(), Reset(), ResetPlayerOptions(), SaveLocalData(), SaveProfiles(), SetCharacter(), SetCurrentPlayMode(), SetCurrentSong(), SetCurrentSteps(), SetCurrentStyle(), SetFailTypeExplicitlySet(), SetJukeboxUsesModifiers(), SetNumMultiplayerNoteFields(), SetPreferredDifficulty(), SetPreferredSong(), SetPreferredSongGroup(), SetSongOptions(), SetTemporaryEventMode(), StoreRankingName(), UnjoinPlayer(), UpdateDiscordMenu(), and UpdateDiscordPresence().
Member Function Documentation
AddStageToPlayer()
static int LunaGameState::AddStageToPlayer (T * p, lua_State * L) inline static
References GameState::AddStageToPlayer(), and COMMON_RETURN_SELF.
Referenced by LunaGameState().
ApplyGameCommand()
static int LunaGameState::ApplyGameCommand (T * p, lua_State * L) inline static
References GameState::ApplyGameCommand(), COMMON_RETURN_SELF, L, PLAYER_INVALID, LuaHelpers::Push(), and SArg.
Referenced by LunaGameState().
ApplyPreferredModifiers()
static int LunaGameState::ApplyPreferredModifiers (T * p, lua_State * L) inline static
References GameState::ApplyPreferredModifiers(), COMMON_RETURN_SELF, and SArg.
Referenced by LunaGameState().
ApplyPreferredSongOptionsToOtherLevels()
static int LunaGameState::ApplyPreferredSongOptionsToOtherLevels (T * p, lua_State * L) inline static
References ModsGroup< T >::Assign(), ModsGroup< T >::Get(), GameState::m_SongOptions, and ModsLevel_Preferred.
Referenced by LunaGameState().
ApplyStageModifiers()
static int LunaGameState::ApplyStageModifiers (T * p, lua_State * L) inline static
References GameState::ApplyStageModifiers(), COMMON_RETURN_SELF, and SArg.
Referenced by LunaGameState().
AreStyleAndPlayModeCompatible()
static bool LunaGameState::AreStyleAndPlayModeCompatible (T * p, lua_State * L, const Style * style, PlayMode pm) inline static
Referenced by SetCurrentPlayMode(), and SetCurrentStyle().
CanSafelyEnterGameplay()
static int LunaGameState::CanSafelyEnterGameplay (T * p, lua_State * L) inline static
References GameState::CanSafelyEnterGameplay(), and LuaHelpers::Push().
Referenced by LunaGameState().
CurrentOptionsDisqualifyPlayer()
static int LunaGameState::CurrentOptionsDisqualifyPlayer (T * p, lua_State * L) inline static
References GameState::CurrentOptionsDisqualifyPlayer().
Referenced by LunaGameState().
DEFINE_METHOD() [1/5]
LunaGameState::DEFINE_METHOD (IsPlayerEnabled , IsPlayerEnabled(Enum::Check< PlayerNumber >(L, 1)))
DEFINE_METHOD() [2/5]
LunaGameState::DEFINE_METHOD (GetPreferredDifficulty , m_PreferredDifficulty [Enum::Check< PlayerNumber >(L, 1)])
DEFINE_METHOD() [3/5]
LunaGameState::DEFINE_METHOD (IsSideJoined , m_bSideIsJoined [Enum::Check< PlayerNumber >(L, 1)])
DEFINE_METHOD() [4/5]
LunaGameState::DEFINE_METHOD (GetEditLocalProfileID , m_sEditLocalProfileID. Get())
DEFINE_METHOD() [5/5]
LunaGameState::DEFINE_METHOD (GetPreferredSongGroup , m_sPreferredSongGroup. Get())
Dopefish()
static int LunaGameState::Dopefish (T * p, lua_State * L) inline static
References GameState::m_bDopefish.
Referenced by LunaGameState().
Env()
static int LunaGameState::Env (T * p, lua_State * L) inline static
References GameState::m_Environment, and LuaReference::PushSelf().
Referenced by LunaGameState().
GetCharacter()
static int LunaGameState::GetCharacter (T * p, lua_State * L) inline static
References L.
Referenced by LunaGameState().
GetCoinMode()
static int LunaGameState::GetCoinMode (T * p, lua_State * L) inline static
Referenced by LunaGameState().
GetCurrent()
m_SongOptions LunaGameState::GetCurrent ()
GetCurrentGame()
static int LunaGameState::GetCurrentGame (T * p, lua_State * L) inline static
References GameState::GetCurrentGame().
Referenced by LunaGameState().
GetCurrentSong()
static int LunaGameState::GetCurrentSong (T * p, lua_State * L) inline static
References GameState::m_pCurSong, and Song::PushSelf().
Referenced by LunaGameState().
GetCurrentSteps()
static int LunaGameState::GetCurrentSteps (T * p, lua_State * L) inline static
References L, and GameState::m_pCurSteps.
Referenced by LunaGameState().
GetCurrentStepsCredits()
static int LunaGameState::GetCurrentStepsCredits (T * t, lua_State * L) inline static
References CustomDifficultyToLocalizedString(), FOREACH_HumanPlayer, GetCustomDifficulty(), Steps::GetDescription(), Steps::GetDifficulty(), GameState::m_pCurSong, GameState::m_pCurSteps, and Steps::m_StepsType.
Referenced by LunaGameState().
GetCurrentStyle()
static int LunaGameState::GetCurrentStyle (T * p, lua_State * L) inline static
References GameState::GetCurrentStyle(), L, and LuaHelpers::Push().
Referenced by LunaGameState().
GetDefaultSongOptions()
static int LunaGameState::GetDefaultSongOptions (T * p, lua_State * L) inline static
References GameState::GetDefaultSongOptions(), and SongOptions::GetString().
Referenced by LunaGameState().
GetEditLocalProfile()
static int LunaGameState::GetEditLocalProfile (T * p, lua_State * L) inline static
References GameState::GetEditLocalProfile(), and Profile::PushSelf().
Referenced by LunaGameState().
GetEnabledPlayers()
static int LunaGameState::GetEnabledPlayers (T * , lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and FOREACH_EnabledPlayer.
Referenced by LunaGameState().
GetExpandedSectionName()
static int LunaGameState::GetExpandedSectionName (T * p, lua_State * L) inline static
References GameState::sExpandedSectionName.
Referenced by LunaGameState().
GetGameSeed()
static int LunaGameState::GetGameSeed (T * p, lua_State * L) inline static
References GameState::m_iGameSeed, and LuaHelpers::Push().
Referenced by LunaGameState().
GetHumanPlayers()
static int LunaGameState::GetHumanPlayers (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), FOREACH_HumanPlayer, and PLAYER_1.
Referenced by LunaGameState().
GetMultiPlayerState()
static int LunaGameState::GetMultiPlayerState (T * p, lua_State * L) inline static
References L, GameState::m_pMultiPlayerState, and PlayerState::PushSelf().
Referenced by LunaGameState().
GetNumStagesForCurrentSongAndStepsOrCourse()
static int LunaGameState::GetNumStagesForCurrentSongAndStepsOrCourse (T * , lua_State * L) inline static
Referenced by LunaGameState().
GetNumStagesLeft()
static int LunaGameState::GetNumStagesLeft (T * p, lua_State * L) inline static
Referenced by LunaGameState().
GetPlayerDisplayName()
LunaGameState::GetPlayerDisplayName (Enum::Check< PlayerNumber > L, 1)
Referenced by LunaGameState().
GetPlayerState()
static int LunaGameState::GetPlayerState (T * p, lua_State * L) inline static
References L, GameState::m_pPlayerState, and PlayerState::PushSelf().
Referenced by LunaGameState().
GetPreferredSong()
static int LunaGameState::GetPreferredSong (T * p, lua_State * L) inline static
References GameState::m_pPreferredSong, and Song::PushSelf().
Referenced by LunaGameState().
GetSongOptions()
static int LunaGameState::GetSongOptions (T * p, lua_State * L) inline static
References ModsGroup< T >::Get(), SongOptions::GetString(), L, GameState::m_SongOptions, and LuaHelpers::Push().
Referenced by LunaGameState().
GetSongOptionsObject()
static int LunaGameState::GetSongOptionsObject (T * p, lua_State * L) inline static
References ModsGroup< T >::Get(), L, GameState::m_SongOptions, and SongOptions::PushSelf().
Referenced by LunaGameState().
GetSongPercent()
static int LunaGameState::GetSongPercent (T * p, lua_State * L) inline static
References FArg, and GameState::GetSongPercent().
Referenced by LunaGameState().
GetStageResult()
static int LunaGameState::GetStageResult (T * p, lua_State * L) inline static
References GameState::GetStageResult(), L, and LuaHelpers::Push().
Referenced by LunaGameState().
GetStageSeed()
static int LunaGameState::GetStageSeed (T * p, lua_State * L) inline static
References GameState::m_iStageSeed, and LuaHelpers::Push().
Referenced by LunaGameState().
InsertCoin()
static int LunaGameState::InsertCoin (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF.
Referenced by LunaGameState().
InsertCredit()
static int LunaGameState::InsertCredit (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF.
Referenced by LunaGameState().
IsCourseMode()
static int LunaGameState::IsCourseMode (T * p, lua_State * L) inline static
Referenced by LunaGameState().
IsDraw()
static int LunaGameState::IsDraw (T * p, lua_State * L) inline static
References GameState::GetStageResult(), PLAYER_1, and RESULT_DRAW.
Referenced by LunaGameState().
IsHumanPlayer()
LunaGameState::IsHumanPlayer (Enum::Check< PlayerNumber > L, 1)
Referenced by LunaGameState().
IsWinner()
static int LunaGameState::IsWinner (T * p, lua_State * L) inline static
References GameState::GetStageResult(), L, and RESULT_WIN.
Referenced by LunaGameState().
JoinInput()
static int LunaGameState::JoinInput (T * p, lua_State * L) inline static
References GameState::JoinInput().
Referenced by LunaGameState().
JoinPlayer()
static int LunaGameState::JoinPlayer (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and GameState::JoinPlayer().
Referenced by LunaGameState().
LoadProfiles()
static int LunaGameState::LoadProfiles (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, GameState::LoadProfiles(), SCREENMAN, and ScreenManager::ZeroNextUpdate().
Referenced by LunaGameState().
PlayerIsUsingModifier()
LunaGameState::PlayerIsUsingModifier (Enum::Check< PlayerNumber > L, 1, SArg(2))
RefreshNoteSkinData()
static int LunaGameState::RefreshNoteSkinData (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, GameState::m_pCurGame, NOTESKIN, and NoteSkinManager::RefreshNoteSkinData().
Referenced by LunaGameState().
Reset()
static int LunaGameState::Reset (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and GameState::Reset().
Referenced by LunaGameState().
ResetPlayerOptions()
static int LunaGameState::ResetPlayerOptions (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and GameState::ResetPlayerOptions().
Referenced by LunaGameState().
SaveLocalData()
static int LunaGameState::SaveLocalData (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF.
Referenced by LunaGameState().
SaveProfiles()
static int LunaGameState::SaveProfiles (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, GameState::SavePlayerProfiles(), SCREENMAN, and ScreenManager::ZeroNextUpdate().
Referenced by LunaGameState().
SetCharacter()
static int LunaGameState::SetCharacter (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF.
Referenced by LunaGameState().
SetCompatibleStyleOrError()
static void LunaGameState::SetCompatibleStyleOrError (T * p, lua_State * L, StepsType stype, PlayerNumber pn) inline static
References GameState::GetCurrentStyle(), and GameState::SetCompatibleStyle().
Referenced by SetCurrentSteps().
SetCurrentPlayMode()
static int LunaGameState::SetCurrentPlayMode (T * p, lua_State * L) inline static
References AreStyleAndPlayModeCompatible(), COMMON_RETURN_SELF, GameState::GetCurrentStyle(), L, GameState::m_PlayMode, PLAYER_INVALID, and BroadcastOnChange< T >::Set().
Referenced by LunaGameState().
SetCurrentSong()
static int LunaGameState::SetCurrentSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, GameState::m_pCurSong, and BroadcastOnChangePtr< T >::Set().
Referenced by LunaGameState().
SetCurrentSteps()
static int LunaGameState::SetCurrentSteps (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, GameState::ForceOtherPlayersToCompatibleSteps(), L, GameState::m_pCurSteps, Steps::m_StepsType, and SetCompatibleStyleOrError().
Referenced by LunaGameState().
SetCurrentStyle()
static int LunaGameState::SetCurrentStyle (T * p, lua_State * L) inline static
References AreStyleAndPlayModeCompatible(), Luna< Type >::check(), COMMON_RETURN_SELF, GameManager::GameAndStringToStyle(), GAMEMAN, GameState::GetNumSidesJoined(), L, GameState::m_pCurGame, GameState::m_PlayMode, Style::m_StyleType, Style::m_szName, SArg, GameState::SetCurrentStyle(), StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, and StyleType_TwoPlayersTwoSides.
Referenced by LunaGameState().
SetFailTypeExplicitlySet()
static int LunaGameState::SetFailTypeExplicitlySet (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and GameState::m_bFailTypeWasExplicitlySet.
Referenced by LunaGameState().
SetJukeboxUsesModifiers()
static int LunaGameState::SetJukeboxUsesModifiers (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and GameState::m_bJukeboxUsesModifiers.
Referenced by LunaGameState().
SetNumMultiplayerNoteFields()
static int LunaGameState::SetNumMultiplayerNoteFields (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and IArg.
Referenced by LunaGameState().
SetPreferredDifficulty()
static int LunaGameState::SetPreferredDifficulty (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, and GameState::m_PreferredDifficulty.
Referenced by LunaGameState().
SetPreferredSong()
static int LunaGameState::SetPreferredSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and GameState::m_pPreferredSong.
Referenced by LunaGameState().
SetPreferredSongGroup()
static int LunaGameState::SetPreferredSongGroup (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, GameState::m_sPreferredSongGroup, and SArg.
Referenced by LunaGameState().
SetSongOptions()
static int LunaGameState::SetSongOptions (T * p, lua_State * L) inline static
References ModsGroup< T >::Assign(), COMMON_RETURN_SELF, SongOptions::FromString(), L, GameState::m_SongOptions, and SArg.
Referenced by LunaGameState().
SetTemporaryEventMode()
static int LunaGameState::SetTemporaryEventMode (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and GameState::m_bTemporaryEventMode.
Referenced by LunaGameState().
StoreRankingName()
static int LunaGameState::StoreRankingName (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF.
Referenced by LunaGameState().
UnjoinPlayer()
static int LunaGameState::UnjoinPlayer (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and GameState::UnjoinPlayer().
Referenced by LunaGameState().
UpdateDiscordMenu()
static int LunaGameState::UpdateDiscordMenu (T * p, lua_State * L) inline static
References SArg, and GameState::updateDiscordPresenceMenu().
Referenced by LunaGameState().
UpdateDiscordPresence()
static int LunaGameState::UpdateDiscordPresence (T * p, lua_State * L) inline static
References IArg, SArg, and GameState::updateDiscordPresence().
Referenced by LunaGameState().
Member Data Documentation
COMMON_RETURN_SELF
LunaGameState::COMMON_RETURN_SELF
Referenced by AddStageToPlayer(), ApplyGameCommand(), ApplyPreferredModifiers(), ApplyStageModifiers(), InsertCoin(), InsertCredit(), JoinPlayer(), LoadProfiles(), RefreshNoteSkinData(), Reset(), ResetPlayerOptions(), SaveLocalData(), SaveProfiles(), SetCharacter(), SetCurrentPlayMode(), SetCurrentSong(), SetCurrentSteps(), SetCurrentStyle(), SetFailTypeExplicitlySet(), SetJukeboxUsesModifiers(), SetNumMultiplayerNoteFields(), SetPreferredDifficulty(), SetPreferredSong(), SetPreferredSongGroup(), SetSongOptions(), SetTemporaryEventMode(), StoreRankingName(), and UnjoinPlayer().
L [1/2]
lua_State * LunaGameState::L
Initial value:
{
        p->m_bMultiplayer = BArg(1)
Referenced by ApplyGameCommand(), GetCharacter(), GetCurrentSteps(), GetCurrentStyle(), GetMultiPlayerState(), GetPlayerState(), GetSongOptions(), GetSongOptionsObject(), GetStageResult(), IsWinner(), SetCurrentPlayMode(), SetCurrentSteps(), SetCurrentStyle(), SetPreferredDifficulty(), and SetSongOptions().
L [2/2]
m_SongOptions lua_State* LunaGameState::L
Initial value:
{
        lua_pushnumber(L, p->m_timeGameStarted.GetTimeSinceStart())
return
LunaGameState::return
The documentation for this class was generated from the following file:
GameState.cpp