Etterna: picosha2::hash256_one_by_one Class Reference
picosha2::hash256_one_by_one Class Reference
#include <picosha2.h>
Public Member Functions
hash256_one_by_one ()
void init ()
template<typename RaIter >
void process (RaIter first, RaIter last)
void finish ()
template<typename OutIter >
void get_hash_bytes (OutIter first, OutIter last) const
Private Member Functions
void add_to_data_length (word_t n)
void write_data_bit_length (byte_t *begin)
Private Attributes
std::vector< byte_t > buffer_
word_t data_length_digits_ [4]
word_t h_ [8]
Constructor & Destructor Documentation
hash256_one_by_one()
picosha2::hash256_one_by_one::hash256_one_by_one () inline
References init().
Member Function Documentation
add_to_data_length()
void picosha2::hash256_one_by_one::add_to_data_length (word_t n) inline private
References data_length_digits_.
Referenced by process().
finish()
void picosha2::hash256_one_by_one::finish () inline
References buffer_, h_, picosha2::detail::hash256_block(), and write_data_bit_length().
Referenced by picosha2::impl::hash256_impl().
get_hash_bytes()
template<typename OutIter > void picosha2::hash256_one_by_one::get_hash_bytes (OutIter first, OutIter last) const inline
References h_, and picosha2::detail::mask_8bit().
Referenced by picosha2::get_hash_hex_string(), and picosha2::impl::hash256_impl().
init()
void picosha2::hash256_one_by_one::init () inline
References buffer_, data_length_digits_, h_, and picosha2::detail::initial_message_digest.
Referenced by hash256_one_by_one().
process()
template<typename RaIter > void picosha2::hash256_one_by_one::process (RaIter first, RaIter last) inline
References add_to_data_length(), buffer_, h_, and picosha2::detail::hash256_block().
Referenced by picosha2::impl::hash256_impl().
write_data_bit_length()
void picosha2::hash256_one_by_one::write_data_bit_length (byte_t * begin) inline private
References data_length_digits_.
Referenced by finish().
Member Data Documentation
buffer_
std::vector<byte_t> picosha2::hash256_one_by_one::buffer_ private
Referenced by finish(), init(), and process().
data_length_digits_
word_t picosha2::hash256_one_by_one::data_length_digits_[4] private
Referenced by add_to_data_length(), init(), and write_data_bit_length().
h_
word_t picosha2::hash256_one_by_one::h_[8] private
Referenced by finish(), get_hash_bytes(), init(), and process().
The documentation for this class was generated from the following file:
picosha2.h