Etterna: RageDisplay_Legacy_Helpers Namespace Reference
RageDisplay_Legacy_Helpers Namespace Reference
Utilities for working with the RageDisplay.
Functions
void Init ()
RString GLToString (GLenum e)
Detailed Description
Utilities for working with the RageDisplay.
Function Documentation
GLToString()
RString RageDisplay_Legacy_Helpers::GLToString (GLenum e)
References ssprintf().
Referenced by CheckPalettedTextures(), CheckReversePackedPixels(), RenderTarget_MacOSX::Create(), RenderTarget_X11::Create(), RageDisplay_Legacy::CreateTexture(), RenderTarget_MacOSX::FinishRenderingTo(), RenderTarget_X11::FinishRenderingTo(), and InitShaders().
Init()
void RageDisplay_Legacy_Helpers::Init ()
Referenced by RageDisplay_Legacy::RageDisplay_Legacy().