Etterna: RageEvent Class Reference
RageEvent Class Reference
#include <RageThreads.h>
Public Member Functions
RageEvent (const RString &name)
~RageEvent () override
bool Wait (RageTimer *pTimeout=nullptr)
void Signal ()
void Broadcast ()
bool WaitTimeoutSupported () const
RageEvent & operator= (const RageEvent &rhs)
RageEvent (const RageEvent &rhs)
Public Member Functions inherited from RageMutex
RString GetName () const
void SetName (const RString &s)
virtual void Lock ()
virtual bool TryLock ()
virtual void Unlock ()
virtual bool IsLockedByThisThread () const
RageMutex (const RString &name)
virtual ~RageMutex ()
Private Attributes
EventImpl * m_pEvent
Additional Inherited Members
Protected Member Functions inherited from RageMutex
void MarkLockedMutex ()
Protected Attributes inherited from RageMutex
MutexImpl * m_pMutex
RString m_sName
int m_UniqueID
uint64_t m_LockedBy
int m_LockCnt
Constructor & Destructor Documentation
RageEvent() [1/2]
RageEvent::RageEvent (const RString & name)
~RageEvent()
RageEvent::~RageEvent () override
References m_pEvent.
RageEvent() [2/2]
RageEvent::RageEvent (const RageEvent & rhs)
Member Function Documentation
Broadcast()
void RageEvent::Broadcast ()
References ASSERT, RageMutex::IsLockedByThisThread(), RageMutex::m_LockCnt, and m_pEvent.
Referenced by RageSoundReader_ThreadedBuffer::BufferingThread(), RageSoundReader_ThreadedBuffer::DisableBuffering(), RageWorkerThread::DoRequest(), RageSoundReader_ThreadedBuffer::EnableBuffering(), GameSoundManager::Flush(), FilenameDB::GetFileSet(), GameSoundManager::PlayMusic(), GameSoundManager::PlayOnce(), GameSoundManager::PlayOnceFromAnnouncer(), GameSoundManager::PlayOnceFromDir(), RageFileManager::ReleaseFileDriver(), UnreferenceAllDrivers(), RageWorkerThread::WorkerMain(), GameSoundManager::~GameSoundManager(), and RageSoundReader_ThreadedBuffer::~RageSoundReader_ThreadedBuffer().
operator=()
RageEvent& RageEvent::operator= (const RageEvent & rhs)
Signal()
void RageEvent::Signal ()
References ASSERT, RageMutex::IsLockedByThisThread(), RageMutex::m_LockCnt, and m_pEvent.
Referenced by MusicThread_start(), ConcurrentRenderer::RenderThread(), ConcurrentRenderer::Start(), and ConcurrentRenderer::Stop().
Wait()
bool RageEvent::Wait (RageTimer * pTimeout = nullptr)
References ASSERT, RageMutex::IsLockedByThisThread(), RageTimer::IsZero(), RageMutex::m_LockCnt, RageMutex::m_LockedBy, and m_pEvent.
Referenced by RageSoundReader_ThreadedBuffer::BufferingThread(), DirectFilenameDB::CacheFile(), RageSoundReader_ThreadedBuffer::DisableBuffering(), RageWorkerThread::DoRequest(), GameSoundManager::Flush(), FilenameDB::FlushDirCache(), FilenameDB::GetFileSet(), MusicThread_start(), ConcurrentRenderer::RenderThread(), ConcurrentRenderer::Start(), ConcurrentRenderer::Stop(), RageWorkerThread::StopThread(), RageFileManager::Unmount(), RageWorkerThread::WaitForOneHeartbeat(), RageSoundReader_ThreadedBuffer::WaitUntilFrames(), and RageWorkerThread::WorkerMain().
WaitTimeoutSupported()
bool RageEvent::WaitTimeoutSupported () const
References m_pEvent.
Referenced by RageSoundReader_ThreadedBuffer::BufferingThread().
Member Data Documentation
m_pEvent
EventImpl* RageEvent::m_pEvent private
Referenced by Broadcast(), Signal(), Wait(), WaitTimeoutSupported(), and ~RageEvent().
The documentation for this class was generated from the following files:
RageThreads.h
RageThreads.cpp