Etterna: RageInput Class Reference
RageInput Class Reference
#include <RageInput.h>
Public Member Functions
RageInput ()
~RageInput ()
void LoadDrivers ()
void Update ()
bool DevicesChanged ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vOut) const
void WindowReset ()
void AddHandler (InputHandler *pHandler)
InputHandler * GetHandlerForDevice (InputDevice id)
Return the first InputDriver for the requested InputDevice.
RString GetDeviceSpecificInputString (const DeviceInput &di)
RString GetLocalizedInputString (const DeviceInput &di)
wchar_t DeviceInputToChar (DeviceInput di, bool bUseCurrentKeyModifiers)
InputDeviceState GetInputDeviceState (InputDevice id)
RString GetDisplayDevicesString () const
void PushSelf (lua_State *L)
Constructor & Destructor Documentation
RageInput()
RageInput::RageInput ()
References LuaManager::Get(), L, LoadDrivers(), LOG, LUA, PushSelf(), LuaManager::Release(), and RageLog::Trace().
~RageInput()
RageInput::~RageInput ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
AddHandler()
void RageInput::AddHandler (InputHandler * pHandler)
References ASSERT, and FOREACH_CONST.
Referenced by LoadDrivers().
DeviceInputToChar()
wchar_t RageInput::DeviceInputToChar (DeviceInput di, bool bUseCurrentKeyModifiers)
References DeviceInput::button, DeviceInput::device, InputHandler::DeviceButtonToChar(), and GetHandlerForDevice().
Referenced by ScreenNetSelectBase::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), ScreenTextEntry::Input(), and Screen::PassInputToLua().
DevicesChanged()
bool RageInput::DevicesChanged ()
Referenced by GameLoop::RunGameLoop().
GetDevicesAndDescriptions()
void RageInput::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vOut) const
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), ChangeAppPri(), InputMapper::CheckForChangedInputDevicesAndRemap(), LunaRageInput::GetDescriptions(), and GetDisplayDevicesString().
GetDeviceSpecificInputString()
RString RageInput::GetDeviceSpecificInputString (const DeviceInput & di)
References DeviceInput::device, InputHandler::GetDeviceSpecificInputString(), GetHandlerForDevice(), and DeviceInput::ToString().
Referenced by GetDebugButtonName(), ScreenDebugOverlay::Init(), ScreenMapControllers::Refresh(), and InputList::Update().
GetDisplayDevicesString()
RString RageInput::GetDisplayDevicesString () const
References GetDevicesAndDescriptions(), InputDeviceToString(), Rage::join(), and ssprintf().
Referenced by DeviceList::Update(), and ScreenMapControllers::Update().
GetHandlerForDevice()
InputHandler * RageInput::GetHandlerForDevice (InputDevice id)
Return the first InputDriver for the requested InputDevice.
Referenced by DeviceInputToChar(), GetDeviceSpecificInputString(), GetInputDeviceState(), and GetLocalizedInputString().
GetInputDeviceState()
InputDeviceState RageInput::GetInputDeviceState (InputDevice id)
References GetHandlerForDevice(), InputHandler::GetInputDeviceState(), and InputDeviceState_NoInputHandler.
Referenced by ControllerStateDisplay::Update().
GetLocalizedInputString()
RString RageInput::GetLocalizedInputString (const DeviceInput & di)
References DeviceInput::button, Capitalize(), DeviceInput::device, DeviceButtonToString(), GetHandlerForDevice(), and InputHandler::GetLocalizedInputString().
LoadDrivers()
void RageInput::LoadDrivers ()
References AddHandler(), InputHandler::Create(), g_sInputDrivers, LocalizedString::GetValue(), LOG, NO_INPUT_DEVICES_LOADED, and RageLog::Warn().
Referenced by RageInput(), and GameLoop::RunGameLoop().
PushSelf()
void RageInput::PushSelf (lua_State * L)
Referenced by RageInput().
Update()
void RageInput::Update ()
Referenced by InputFilter::Update().
WindowReset()
void RageInput::WindowReset ()
Referenced by StepMania::ApplyGraphicOptions().
The documentation for this class was generated from the following files:
RageInput.h
RageInput.cpp