Etterna: RageSoundDriver_OSS Class Reference
RageSoundDriver_OSS Class Reference
#include <RageSoundDriver_OSS.h>
Public Member Functions
bool GetData ()
int GetSampleRate () const
int64_t GetPosition () const
float GetPlayLatency () const
void SetupDecodingThread ()
RageSoundDriver_OSS ()
RString Init ()
~RageSoundDriver_OSS ()
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void MixerThread ()
Static Private Member Functions
static int MixerThread_start (void *p)
static RString CheckOSSVersion (int fd)
Private Attributes
int fd
bool shutdown
int last_cursor_pos
int samplerate
RageThread MixingThread
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_OSS()
RageSoundDriver_OSS::RageSoundDriver_OSS ()
References fd, last_cursor_pos, and shutdown.
~RageSoundDriver_OSS()
RageSoundDriver_OSS::~RageSoundDriver_OSS ()
References fd, RageThread::IsCreated(), LOG, MixingThread, shutdown, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
CheckOSSVersion()
RString RageSoundDriver_OSS::CheckOSSVersion (int fd) static private
References ALSA_SNDRV_OSS_VERSION, RageLog::Info(), IsADirectory(), LOG, and RageLog::Warn().
Referenced by Init().
GetData()
bool RageSoundDriver_OSS::GetData ()
References bytes_per_frame, chunksize, FAIL_M, fd, GetPosition(), last_cursor_pos, RageSoundDriver::Mix(), and ssprintf().
Referenced by MixerThread().
GetPlayLatency()
float RageSoundDriver_OSS::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
GetPosition()
int64_t RageSoundDriver_OSS::GetPosition () const virtual
Implements RageSoundDriver.
References ASSERT, bytes_per_frame, FAIL_M, fd, last_cursor_pos, and ssprintf().
Referenced by GetData().
GetSampleRate()
int RageSoundDriver_OSS::GetSampleRate () const inline virtual
Reimplemented from RageSoundDriver.
References samplerate.
Init()
RString RageSoundDriver_OSS::Init () virtual
Reimplemented from RageSoundDriver.
References channels, CheckOSSVersion(), chunk_order, RageThread::Create(), fd, LOG, MixerThread_start(), MixingThread, num_chunks, samplerate, RageThread::SetName(), SNDCTL_DSP_SPEED, ssprintf(), RageSoundDriver::StartDecodeThread(), and RageLog::Trace().
MixerThread()
void RageSoundDriver_OSS::MixerThread () private
References f, fd, GetData(), LOG, shutdown, and RageLog::Trace().
MixerThread_start()
int RageSoundDriver_OSS::MixerThread_start (void * p) static private
Referenced by Init().
SetupDecodingThread()
void RageSoundDriver_OSS::SetupDecodingThread () virtual
Reimplemented from RageSoundDriver.
References LOG, and RageLog::Trace().
Member Data Documentation
fd
int RageSoundDriver_OSS::fd private
Referenced by GetData(), GetPosition(), Init(), MixerThread(), RageSoundDriver_OSS(), and ~RageSoundDriver_OSS().
last_cursor_pos
int RageSoundDriver_OSS::last_cursor_pos private
Referenced by GetData(), GetPosition(), and RageSoundDriver_OSS().
MixingThread
RageThread RageSoundDriver_OSS::MixingThread private
Referenced by Init(), and ~RageSoundDriver_OSS().
samplerate
int RageSoundDriver_OSS::samplerate private
Referenced by GetSampleRate(), and Init().
shutdown
bool RageSoundDriver_OSS::shutdown private
Referenced by MixerThread(), RageSoundDriver_OSS(), and ~RageSoundDriver_OSS().
The documentation for this class was generated from the following files:
RageSoundDriver_OSS.h
RageSoundDriver_OSS.cpp