Etterna: CubicSplineN Struct Reference
CubicSplineN Struct Reference
#include <CubicSpline.h>
Public Types
typedef vector< CubicSpline > spline_cont_t
Public Member Functions
CubicSplineN ()=default
void solve ()
void evaluate (float t, vector< float > &v) const
void evaluate_derivative (float t, vector< float > &v) const
void evaluate_second_derivative (float t, vector< float > &v) const
void evaluate_third_derivative (float t, vector< float > &v) const
void evaluate (float t, RageVector3 &v) const
void evaluate_derivative (float t, RageVector3 &v) const
void set_point (size_t i, const vector< float > &v)
void set_coefficients (size_t i, const vector< float > &b, const vector< float > &c, const vector< float > &d)
void get_coefficients (size_t i, vector< float > &b, vector< float > &c, vector< float > &d)
void set_spatial_extent (size_t i, float extent)
float get_spatial_extent (size_t i)
void resize (size_t s)
size_t size () const
void redimension (size_t d)
size_t dimension () const
bool empty () const
float get_max_t () const
void set_loop (bool l)
bool get_loop () const
void set_polygonal (bool p)
bool get_polygonal () const
void set_dirty (bool d)
bool get_dirty () const
void PushSelf (lua_State *L)
Static Public Member Functions
static void weighted_average (CubicSplineN &out, const CubicSplineN &from, const CubicSplineN &to, float between)
Public Attributes
bool m_owned_by_actor { false }
Private Attributes
bool m_loop { false }
bool m_polygonal { false }
bool m_dirty { true }
spline_cont_t m_splines
Member Typedef Documentation
spline_cont_t
typedef vector<CubicSpline> CubicSplineN::spline_cont_t
Constructor & Destructor Documentation
CubicSplineN()
CubicSplineN::CubicSplineN () default
Member Function Documentation
dimension()
size_t CubicSplineN::dimension () const
References m_splines.
Referenced by LunaCubicSplineN::dimension_index(), LunaCubicSplineN::get_coefficients(), LunaCubicSplineN::get_dimension(), LunaCubicSplineN::set_coefficients_from_stack(), LunaCubicSplineN::set_point_from_stack(), and weighted_average().
empty()
bool CubicSplineN::empty () const
References m_splines.
Referenced by LunaCubicSplineN::empty().
evaluate() [1/2]
void CubicSplineN::evaluate (float t, vector< float > & v) const
Referenced by NCSplineHandler::EvalForBeat(), and NCSplineHandler::EvalForReceptor().
evaluate() [2/2]
void CubicSplineN::evaluate (float t, RageVector3 & v) const
evaluate_derivative() [1/2]
void CubicSplineN::evaluate_derivative (float t, vector< float > & v) const
Referenced by NCSplineHandler::EvalDerivForBeat().
evaluate_derivative() [2/2]
void CubicSplineN::evaluate_derivative (float t, RageVector3 & v) const
evaluate_second_derivative()
void CubicSplineN::evaluate_second_derivative (float t, vector< float > & v) const
evaluate_third_derivative()
void CubicSplineN::evaluate_third_derivative (float t, vector< float > & v) const
get_coefficients()
void CubicSplineN::get_coefficients (size_t i, vector< float > & b, vector< float > & c, vector< float > & d)
References ASSERT_M, and m_splines.
Referenced by LunaCubicSplineN::get_coefficients().
get_dirty()
bool CubicSplineN::get_dirty () const
get_loop()
bool CubicSplineN::get_loop () const
get_max_t()
float CubicSplineN::get_max_t () const inline
References m_loop, and size().
Referenced by LunaCubicSplineN::get_max_t().
get_polygonal()
bool CubicSplineN::get_polygonal () const
get_spatial_extent()
float CubicSplineN::get_spatial_extent (size_t i)
References ASSERT_M, and m_splines.
Referenced by LunaCubicSplineN::get_spatial_extent().
PushSelf()
void CubicSplineN::PushSelf (lua_State * L)
Referenced by LunaNCSplineHandler::get_spline(), LunaActorMultiVertex::GetSpline(), and LuaFunc_create_spline().
redimension()
void CubicSplineN::redimension (size_t d)
References m_dirty, and m_splines.
Referenced by NCSplineHandler::NCSplineHandler(), and LunaCubicSplineN::set_dimension().
resize()
void CubicSplineN::resize (size_t s)
References m_dirty, and m_splines.
Referenced by LunaCubicSplineN::set_size(), and weighted_average().
set_coefficients()
void CubicSplineN::set_coefficients (size_t i, const vector< float > & b, const vector< float > & c, const vector< float > & d)
References ASSERT_M, m_dirty, and m_splines.
Referenced by LunaCubicSplineN::set_coefficients_from_stack().
set_dirty()
void CubicSplineN::set_dirty (bool d)
set_loop()
void CubicSplineN::set_loop (bool l)
set_point()
void CubicSplineN::set_point (size_t i, const vector< float > & v)
References ASSERT_M, m_dirty, and m_splines.
Referenced by LunaCubicSplineN::set_point_from_stack().
set_polygonal()
void CubicSplineN::set_polygonal (bool p)
set_spatial_extent()
void CubicSplineN::set_spatial_extent (size_t i, float extent)
References ASSERT_M, m_dirty, and m_splines.
Referenced by NoteColumnRenderer::NCR_TweenState::NCR_TweenState(), and LunaCubicSplineN::set_spatial_extent().
size()
size_t CubicSplineN::size () const
References m_splines.
Referenced by get_max_t(), LunaCubicSplineN::get_size(), LunaCubicSplineN::point_index(), and weighted_average().
solve()
void CubicSplineN::solve ()
References m_dirty, m_loop, m_polygonal, and SOLVE_LOOP.
Referenced by LunaCubicSplineN::solve().
weighted_average()
void CubicSplineN::weighted_average (CubicSplineN & out, const CubicSplineN & from, const CubicSplineN & to, float between) static
References ASSERT_M, BOOLS_FROM_CLOSEST, CLAMP(), dimension(), f, lerp(), m_splines, resize(), and size().
Referenced by NCSplineHandler::MakeWeightedAverage().
Member Data Documentation
m_dirty
bool CubicSplineN::m_dirty { true } private
Referenced by redimension(), resize(), set_coefficients(), set_point(), set_spatial_extent(), and solve().
m_loop
bool CubicSplineN::m_loop { false } private
Referenced by get_max_t(), and solve().
m_owned_by_actor
bool CubicSplineN::m_owned_by_actor { false }
Referenced by LunaCubicSplineN::destroy(), NCSplineHandler::NCSplineHandler(), and LunaCubicSplineN::set_dimension().
m_polygonal
bool CubicSplineN::m_polygonal { false } private
Referenced by solve().
m_splines
spline_cont_t CubicSplineN::m_splines private
Referenced by dimension(), empty(), get_coefficients(), get_spatial_extent(), redimension(), resize(), set_coefficients(), set_point(), set_spatial_extent(), size(), and weighted_average().
The documentation for this struct was generated from the following files:
CubicSpline.h
CubicSpline.cpp