Etterna: ThemeMetric1D< T > Class Template Reference
ThemeMetric1D< T > Class Template Reference
#include <ThemeMetric.h>
Public Member Functions
ThemeMetric1D (const RString &sGroup, MetricName1D pfn, size_t N)
ThemeMetric1D ()
void Load (const RString &sGroup, MetricName1D pfn, size_t N)
void Read () override
void Clear () override
const T & GetValue (size_t i) const
Public Member Functions inherited from IThemeMetric
virtual ~IThemeMetric ()=default
Private Types
using ThemeMetricT = ThemeMetric< T >
Private Attributes
vector< ThemeMetricT > m_metric
Member Typedef Documentation
ThemeMetricT
template<class T> using ThemeMetric1D< T >::ThemeMetricT = ThemeMetric<T> private
Constructor & Destructor Documentation
ThemeMetric1D() [1/2]
template<class T> ThemeMetric1D< T >::ThemeMetric1D (const RString & sGroup, MetricName1D pfn, size_t N) inline
ThemeMetric1D() [2/2]
template<class T> ThemeMetric1D< T >::ThemeMetric1D () inline
Member Function Documentation
Clear()
template<class T> void ThemeMetric1D< T >::Clear () inline override virtual
Implements IThemeMetric.
Referenced by ThemeMetric1D< AutoPtrCopyOnWrite >::Clear(), and SongManager::ResetGroupColors().
GetValue()
template<class T> const T& ThemeMetric1D< T >::GetValue (size_t i) const inline
Referenced by MusicWheel::BuildWheelItemDatas(), ScreenSelectMaster::GetCursorX(), ScreenSelectMaster::GetCursorY(), SongManager::GetSongColor(), SongManager::GetSongGroupColor(), OptionRow::InitText(), LifeMeterBar::LifeMeterBar(), OptionRow::PositionIcons(), and ScreenRanking::SetPage().
Load()
template<class T> void ThemeMetric1D< T >::Load (const RString & sGroup, MetricName1D pfn, size_t N) inline
Referenced by ScreenRanking::Init(), ScreenSelectMaster::Init(), LifeMeterBar::LifeMeterBar(), MusicWheel::Load(), OptionRowType::Load(), ThemeMetric1D< AutoPtrCopyOnWrite >::Load(), SongManager::ResetGroupColors(), SongManager::SongManager(), and ThemeMetric1D< AutoPtrCopyOnWrite >::ThemeMetric1D().
Read()
template<class T> void ThemeMetric1D< T >::Read () inline override virtual
Implements IThemeMetric.
Referenced by ThemeMetric1D< AutoPtrCopyOnWrite >::Read().
Member Data Documentation
m_metric
template<class T> vector<ThemeMetricT> ThemeMetric1D< T >::m_metric private
The documentation for this class was generated from the following file:
ThemeMetric.h