Etterna: FontCharmaps Namespace Reference
FontCharmaps Namespace Reference
Defines common frame to character mappings for Fonts.
Functions
const wchar_t * get_char_map (RString name)
Variables
const wchar_t M_SKIP = 0xFEFF
Detailed Description
Defines common frame to character mappings for Fonts.
Function Documentation
get_char_map()
const wchar_t * FontCharmaps::get_char_map (RString name)
References charmaps, Init(), and StdString::CStdStr< CT >::MakeLower().
Referenced by FontPageSettings::MapRange().
Variable Documentation
M_SKIP
const wchar_t FontCharmaps::M_SKIP = 0xFEFF
Referenced by FontPageSettings::MapRange().