Etterna: LunaCharacterManager Class Reference
LunaCharacterManager Class Reference
Allow Lua to have access to the CharacterManager.
Public Member Functions
LunaCharacterManager ()
Public Member Functions inherited from Luna< CharacterManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetCharacter (T *p, lua_State *L)
static int GetRandomCharacter (T *p, lua_State *L)
static int GetAllCharacters (T *p, lua_State *L)
static int GetCharacterCount (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< CharacterManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< CharacterManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< CharacterManager >
using T = CharacterManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< CharacterManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the CharacterManager.
Constructor & Destructor Documentation
LunaCharacterManager()
LunaCharacterManager::LunaCharacterManager () inline
References ADD_METHOD, GetAllCharacters(), GetCharacter(), GetCharacterCount(), and GetRandomCharacter().
Member Function Documentation
GetAllCharacters()
static int LunaCharacterManager::GetAllCharacters (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), and CharacterManager::GetCharacters().
Referenced by LunaCharacterManager().
GetCharacter()
static int LunaCharacterManager::GetCharacter (T * p, lua_State * L) inline static
References CharacterManager::GetCharacterFromID(), Character::PushSelf(), and SArg.
Referenced by LunaCharacterManager().
GetCharacterCount()
static int LunaCharacterManager::GetCharacterCount (T * p, lua_State * L) inline static
References CharacterManager::GetCharacters().
Referenced by LunaCharacterManager().
GetRandomCharacter()
static int LunaCharacterManager::GetRandomCharacter (T * p, lua_State * L) inline static
References CharacterManager::GetRandomCharacter(), and Character::PushSelf().
Referenced by LunaCharacterManager().
The documentation for this class was generated from the following file:
CharacterManager.cpp