Etterna: GameLoop.cpp File Reference
GameLoop.cpp File Reference
#include "global.h"
#include "GameLoop.h"
#include "PrefsManager.h"
#include "RageDisplay.h"
#include "RageSoundManager.h"
#include "RageTextureManager.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "DownloadManager.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "InputFilter.h"
#include "InputMapper.h"
#include "NetworkSyncManager.h"
#include "RageInput.h"
#include "ScreenManager.h"
#include "SongManager.h"
#include "ThemeManager.h"
#include <chrono>
#include "Game.h"
#include "GameManager.h"
#include "StepMania.h"
Classes
class ConcurrentRenderer
Functions
void HandleInputEvents (float fDeltaTime)
static void CheckGameLoopTimerSkips (float fDeltaTime)
static bool ChangeAppPri ()
static void CheckFocus ()
Variables
static auto g_AccurateGameplayTimer = std::chrono::steady_clock::now()
static Preference< bool > g_bNeverBoostAppPriority ("NeverBoostAppPriority", false)
static Preference< float > g_fConstantUpdateDeltaSeconds ("ConstantUpdateDeltaSeconds", 0)
static float g_fUpdateRate = 1
static RString g_NewTheme
static RString g_NewGame
static ConcurrentRenderer * g_pConcurrentRenderer = NULL
Function Documentation
ChangeAppPri()
static bool ChangeAppPri () static
References FOREACH_CONST, g_bNeverBoostAppPriority, Preference< T >::Get(), RageInput::GetDevicesAndDescriptions(), INPUTMAN, LOG, and RageLog::Trace().
Referenced by CheckFocus(), and GameLoop::RunGameLoop().
CheckFocus()
static void CheckFocus () static
References ArchHooks::AppFocusChanged(), ArchHooks::AppHasFocus(), ArchHooks::BoostPriority(), ChangeAppPri(), HOOKS, INPUTFILTER, InputFilter::Reset(), and ArchHooks::UnBoostPriority().
Referenced by GameLoop::RunGameLoop().
CheckGameLoopTimerSkips()
static void CheckGameLoopTimerSkips (float fDeltaTime) static
References DISPLAY, RageDisplay::GetActualVideoModeParams(), RageDisplay::GetFPS(), LOG, PrefsManager::m_bLogSkips, PREFSMAN, and RageLog::Trace().
Referenced by GameLoop::RunGameLoop().
HandleInputEvents()
void HandleInputEvents (float fDeltaTime)
References ArchHooks::AppHasFocus(), StepMania::ApplyGraphicOptions(), ASSERT, GameInput::button, CODE_BACK_IN_EVENT_MODE, GameInput::controller, InputMapper::ControllerToPlayerNumber(), DeviceInput::device, DEVICE_JOY1, InputEventPlus::DeviceI, InputMapper::DeviceToGame(), CodeDetector::EnteredCode(), FOREACH_ENUM, GAME_BUTTON_BACK, GameButton_Invalid, InputMapper::GameButtonToMenuButton(), InputEventPlus::GameI, GAMESTATE, ArchHooks::GetAndClearToggleWindowed(), InputFilter::GetInputEvents(), ScreenManager::GetTopScreen(), HandleGlobalInputs(), HOOKS, IET_FIRST_PRESS, ScreenManager::Input(), InputMapper::InputDeviceToMultiPlayer(), INPUTFILTER, InputEventPlus::InputList, INPUTMAPPER, INPUTQUEUE, GameState::IsEventMode(), Actor::IsFirstUpdate(), DeviceInput::IsJoystick(), GameInput::IsValid(), GameState::m_bMultiplayer, PrefsManager::m_bWindowed, InputEventPlus::MenuI, InputEventPlus::mp, MultiPlayer_Invalid, NUM_MultiPlayer, InputEventPlus::pn, PREFSMAN, InputQueue::RememberInput(), InputMapper::RepeatStopKey(), SCREENMAN, Preference< T >::Set(), swap(), InputEventPlus::type, and InputFilter::Update().
Referenced by GameLoop::RunGameLoop().
Variable Documentation
g_AccurateGameplayTimer
auto g_AccurateGameplayTimer = std::chrono::steady_clock::now() static
Referenced by ConcurrentRenderer::RenderThread(), and GameLoop::RunGameLoop().
g_bNeverBoostAppPriority
Preference<bool> g_bNeverBoostAppPriority("NeverBoostAppPriority", false) static
Referenced by ChangeAppPri().
g_fConstantUpdateDeltaSeconds
Preference<float> g_fConstantUpdateDeltaSeconds("ConstantUpdateDeltaSeconds", 0) static
Referenced by GameLoop::RunGameLoop().
g_fUpdateRate
float g_fUpdateRate = 1 static
Referenced by GameLoop::RunGameLoop(), and GameLoop::SetUpdateRate().
g_NewGame
RString g_NewGame static
g_NewTheme
RString g_NewTheme static
g_pConcurrentRenderer
ConcurrentRenderer* g_pConcurrentRenderer = NULL static