Etterna: ScreenNetworkOptions.cpp File Reference
ScreenNetworkOptions.cpp File Reference
#include "global.h"
#include "GameSoundManager.h"
#include "LocalizedString.h"
#include "NetworkSyncManager.h"
#include "OptionRowHandler.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "ScreenNetworkOptions.h"
#include "ScreenPrompt.h"
#include "ScreenTextEntry.h"
#include "ThemeManager.h"
Enumerations
enum NetworkOptionRow { PO_CONNECTION, PO_SCOREBOARD, PO_SERVERS, NUM_NETWORK_OPTIONS_LINES }
enum DisplayScoreboard { NO_SCOREBOARD_OFF = 0, NO_SCOREBOARD_ON }
Functions
AutoScreenMessage (SM_DoneConnecting)
REGISTER_SCREEN_CLASS (ScreenNetworkOptions)
Variables
static LocalizedString CLIENT_CONNECT ("ScreenNetworkOptions", "Connect")
static LocalizedString CLIENT_DISCONNECT ("ScreenNetworkOptions", "Disconnect")
static LocalizedString SCORE_ON ("ScreenNetworkOptions", "ScoreOn")
static LocalizedString SCORE_OFF ("ScreenNetworkOptions", "ScoreOff")
static LocalizedString DISCONNECTED ("ScreenNetworkOptions", "Disconnected from server.")
static LocalizedString ENTER_NETWORK_ADDRESS ("ScreenNetworkOptions", "Enter a network address.")
static LocalizedString CONNECT_TO_YOURSELF ("ScreenNetworkOptions", "Use 127.0.0.1 to connect to yourself.")
Preference< RString > g_sLastServer ("LastConnectedServer", "")
Enumeration Type Documentation
DisplayScoreboard
enum DisplayScoreboard
Enumerator
NO_SCOREBOARD_OFF
NO_SCOREBOARD_ON
NetworkOptionRow
enum NetworkOptionRow
Enumerator
PO_CONNECTION
PO_SCOREBOARD
PO_SERVERS
NUM_NETWORK_OPTIONS_LINES
Function Documentation
AutoScreenMessage()
AutoScreenMessage (SM_DoneConnecting)
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenNetworkOptions)
Variable Documentation
CLIENT_CONNECT
LocalizedString CLIENT_CONNECT("ScreenNetworkOptions", "Connect") static
Referenced by ScreenNetworkOptions::Init().
CLIENT_DISCONNECT
LocalizedString CLIENT_DISCONNECT("ScreenNetworkOptions", "Disconnect") static
Referenced by ScreenNetworkOptions::Init().
CONNECT_TO_YOURSELF
LocalizedString CONNECT_TO_YOURSELF("ScreenNetworkOptions", "Use 127.0.0.1 to connect to yourself.") static
Referenced by ScreenNetworkOptions::MenuStart().
DISCONNECTED
LocalizedString DISCONNECTED("ScreenNetworkOptions", "Disconnected from server.") static
Referenced by ScreenNetworkOptions::MenuStart().
ENTER_NETWORK_ADDRESS
LocalizedString ENTER_NETWORK_ADDRESS("ScreenNetworkOptions", "Enter a network address.") static
Referenced by ScreenNetworkOptions::MenuStart().
g_sLastServer
Preference<RString> g_sLastServer("LastConnectedServer", "")
Referenced by ScreenNetworkOptions::MenuStart().
SCORE_OFF
LocalizedString SCORE_OFF("ScreenNetworkOptions", "ScoreOff") static
Referenced by ScreenNetworkOptions::Init().
SCORE_ON
LocalizedString SCORE_ON("ScreenNetworkOptions", "ScoreOn") static
Referenced by ScreenNetworkOptions::Init().