Etterna: OptionRow Class Reference
OptionRow Class Reference
#include <OptionRow.h>
Public Types
enum RowType { RowType_Normal, RowType_Exit }
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Public Member Functions
OptionRow (const OptionRowType *pType)
~OptionRow () override
void Clear ()
void LoadNormal (OptionRowHandler *pHand, bool bFirstItemGoesDown)
void LoadExit ()
void SetModIcon (PlayerNumber pn, const RString &sText, GameCommand &gc)
void ImportOptions (const vector< PlayerNumber > &vpns)
int ExportOptions (const vector< PlayerNumber > &vpns, bool bRowHasFocus[NUM_PLAYERS])
void InitText (RowType type)
void AfterImportOptions (PlayerNumber pn)
RString GetRowTitle () const
void ChoicesChanged (RowType type, bool reset_focus=true)
void PositionUnderlines (PlayerNumber pn)
void PositionIcons (PlayerNumber pn)
void UpdateText (PlayerNumber pn)
bool GetRowHasFocus (PlayerNumber pn) const
void SetRowHasFocus (PlayerNumber pn, bool bRowHasFocus)
void UpdateEnabledDisabled ()
int GetOneSelection (PlayerNumber pn, bool bAllowFail=false) const
int GetOneSharedSelection (bool bAllowFail=false) const
void SetOneSelection (PlayerNumber pn, int iChoice)
void SetOneSharedSelection (int iChoice)
void SetOneSharedSelectionIfPresent (const RString &sChoice)
int GetChoiceInRowWithFocus (PlayerNumber pn) const
int GetChoiceInRowWithFocusShared () const
void SetChoiceInRowWithFocus (PlayerNumber pn, int iChoice)
void ResetFocusFromSelection (PlayerNumber pn)
bool GetSelected (PlayerNumber pn, int iChoice) const
bool SetSelected (PlayerNumber pn, int iChoice, bool b)
bool NotifyHandlerOfSelection (PlayerNumber pn, int choice)
const OptionRowDefinition & GetRowDef () const
OptionRowDefinition & GetRowDef ()
RowType GetRowType () const
const OptionRowHandler * GetHandler () const
const BitmapText & GetTextItemForRow (PlayerNumber pn, int iChoiceOnRow) const
void GetWidthXY (PlayerNumber pn, int iChoiceOnRow, int &iWidthOut, int &iXOut, int &iYOut) const
unsigned GetTextItemsSize () const
bool GetFirstItemGoesDown () const
bool GoToFirstOnStart ()
RString GetThemedItemText (int iChoice) const
void SetExitText (const RString &sExitText)
void Reload ()
void HandleMessage (const Message &msg) override
void PushSelf (lua_State *L) override
void SetDestination (Actor::TweenState &ts, bool bTween)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
virtual void Update (float fDeltaTime)
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Attributes
const OptionRowType * m_pParentType
RowType m_RowType
OptionRowHandler * m_pHand
ActorFrame m_Frame
vector< BitmapText * > m_textItems
vector< OptionsCursor * > m_Underline [NUM_PLAYERS]
Actor * m_sprFrame
BitmapText * m_textTitle
ModIcon * m_ModIcons [NUM_PLAYERS]
bool m_bFirstItemGoesDown
bool m_bRowHasFocus [NUM_PLAYERS]
int m_iChoiceInRowWithFocus [NUM_PLAYERS]
vector< bool > m_vbSelected [NUM_PLAYERS]
Actor::TweenState m_tsDestination
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Member Enumeration Documentation
RowType
enum OptionRow::RowType
Enumerator
RowType_Normal
RowType_Exit
Constructor & Destructor Documentation
OptionRow()
OptionRow::OptionRow (const OptionRowType * pType)
References ActorFrame::AddChild(), Clear(), Actor::TweenState::Init(), m_Frame, m_ModIcons, m_pHand, m_pParentType, m_textTitle, m_tsDestination, and ZERO.
~OptionRow()
OptionRow::~OptionRow () override
References Clear().
Member Function Documentation
AfterImportOptions()
void OptionRow::AfterImportOptions (PlayerNumber pn)
References ASSERT, FOREACH_PlayerNumber, GAMESTATE, GameState::GetMasterPlayerNumber(), GetOneSelection(), GameState::IsHumanPlayer(), LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, m_pHand, OptionRowDefinition::m_selectType, m_textItems, m_Underline, m_vbSelected, PLAYER_1, PLAYER_INVALID, PositionUnderlines(), ResetFocusFromSelection(), SELECT_ONE, and Actor::SetVisible().
Referenced by Reload(), and ScreenOptions::RestartOptions().
ChoicesChanged()
void OptionRow::ChoicesChanged (RowType type, bool reset_focus = true)
References ASSERT_M, FOREACH_PlayerNumber, GetRowTitle(), InitText(), m_bFirstItemGoesDown, OptionRowHandler::m_Def, m_pHand, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, m_textTitle, m_vbSelected, OptionRowDefinition::m_vsChoices, NEXT_ROW_NAME, SELECT_ONE, SetChoiceInRowWithFocus(), and BitmapText::SetText().
Referenced by LoadExit(), LoadNormal(), NotifyHandlerOfSelection(), and Reload().
Clear()
void OptionRow::Clear ()
References ActorFrame::DeleteAllChildren(), FOREACH_CONST, FOREACH_PlayerNumber, m_bFirstItemGoesDown, m_bRowHasFocus, m_Frame, m_iChoiceInRowWithFocus, m_pHand, m_textItems, m_Underline, m_vbSelected, OptionRowHandler::m_vsReloadRowMessages, MESSAGEMAN, ActorFrame::RemoveAllChildren(), SAFE_DELETE, MessageManager::Unsubscribe(), and ZERO.
Referenced by OptionRow(), and ~OptionRow().
ExportOptions()
int OptionRow::ExportOptions (const vector< PlayerNumber > & vpns, bool bRowHasFocus[NUM_PLAYERS])
References ASSERT, ERASE_ONE_BOOL_AT_FRONT_IF_NEEDED, OptionRowHandler::ExportOption(), FOREACH_CONST, GetChoiceInRowWithFocus(), INSERT_ONE_BOOL_AT_FRONT_IF_NEEDED, OptionRowHandler::m_Def, m_pHand, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, m_vbSelected, OptionRowDefinition::m_vsChoices, SELECT_NONE, and VerifySelected().
GetChoiceInRowWithFocus()
int OptionRow::GetChoiceInRowWithFocus (PlayerNumber pn) const
References OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_iChoiceInRowWithFocus, m_pHand, OptionRowDefinition::m_vsChoices, and PLAYER_1.
Referenced by ScreenOptions::ChangeValueInRowAbsolute(), ScreenOptions::ChangeValueInRowRelative(), ExportOptions(), GetChoiceInRowWithFocusShared(), ScreenOptions::PositionCursor(), PositionUnderlines(), ScreenOptions::ProcessMenuStart(), ScreenOptions::StoreFocus(), ScreenOptions::TweenCursor(), and UpdateEnabledDisabled().
GetChoiceInRowWithFocusShared()
int OptionRow::GetChoiceInRowWithFocusShared () const
References GetChoiceInRowWithFocus(), and PLAYER_1.
GetFirstItemGoesDown()
bool OptionRow::GetFirstItemGoesDown () const inline
References m_bFirstItemGoesDown.
Referenced by ScreenOptions::AfterChangeRow(), and ScreenOptions::ProcessMenuStart().
GetHandler()
const OptionRowHandler* OptionRow::GetHandler () const inline
References m_pHand.
Referenced by LunaOptionRow::GetNumChoices(), LunaOptionRow::OneChoiceForAllPlayers(), and ScreenOptions::RefreshIcons().
GetOneSelection()
int OptionRow::GetOneSelection (PlayerNumber pn, bool bAllowFail = false) const
References ASSERT, and m_vbSelected.
Referenced by AfterImportOptions(), GetOneSharedSelection(), ScreenOptions::RefreshIcons(), and ResetFocusFromSelection().
GetOneSharedSelection()
int OptionRow::GetOneSharedSelection (bool bAllowFail = false) const
References GetOneSelection(), and PLAYER_1.
Referenced by ScreenOptionsCourseOverview::ExportOptions(), ScreenOptionsEditProfile::ExportOptions(), ScreenOptionsToggleSongsSubPage::ExportOptions(), and ScreenSMOnlineLogin::GetSelectedProfileID().
GetRowDef() [1/2]
const OptionRowDefinition & OptionRow::GetRowDef () const
References OptionRowHandler::m_Def, and m_pHand.
Referenced by ScreenOptions::AfterChangeRow(), ScreenMiniMenu::AfterChangeValueOrRow(), ScreenOptions::ChangeValueInRowAbsolute(), ScreenOptions::ChangeValueInRowRelative(), ScreenOptionsCourseOverview::ExportOptions(), ScreenOptionsEditProfile::ExportOptions(), ScreenOptions::GetExplanationText(), ScreenOptions::PositionCursor(), ScreenOptions::ProcessMenuStart(), ScreenOptions::RefreshIcons(), ScreenOptions::RestartOptions(), ScreenOptions::StoreFocus(), and ScreenOptions::TweenCursor().
GetRowDef() [2/2]
OptionRowDefinition & OptionRow::GetRowDef ()
References OptionRowHandler::m_Def, and m_pHand.
GetRowHasFocus()
bool OptionRow::GetRowHasFocus (PlayerNumber pn) const inline
References m_bRowHasFocus.
GetRowTitle()
RString OptionRow::GetRowTitle () const
References DisplayBpms::BpmIsConstant(), StdString::CStdStr< CT >::CompareNoCase(), GAMESTATE, Song::GetDisplayBpms(), DisplayBpms::GetMax(), DisplayBpms::GetMin(), DisplayBpms::IsSecret(), OptionRowHandler::m_Def, GameState::m_pCurSong, m_pHand, m_pParentType, OptionRowDefinition::m_sName, OptionRowHandler::OptionTitle(), OptionRowType::SHOW_BPM_IN_SPEED_TITLE, and ssprintf().
Referenced by ChoicesChanged().
GetRowType()
RowType OptionRow::GetRowType () const inline
References m_RowType.
Referenced by ScreenOptions::AfterChangeValueOrRow(), ScreenOptionsManageProfiles::GetLocalProfileIndexWithFocus(), ScreenOptionsManageProfiles::HandleScreenMessage(), InitText(), ScreenOptions::MoveRowAbsolute(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenOptions::ProcessMenuStart(), and ScreenOptions::TweenCursor().
GetSelected()
bool OptionRow::GetSelected (PlayerNumber pn, int iChoice) const
References OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_pHand, m_vbSelected, and PLAYER_1.
Referenced by ScreenOptions::ProcessMenuStart().
GetTextItemForRow()
const BitmapText & OptionRow::GetTextItemForRow (PlayerNumber pn, int iChoiceOnRow) const
References ASSERT_M, FAIL_M, LAYOUT_SHOW_ALL_IN_ROW, LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, m_pHand, m_textItems, and ssprintf().
Referenced by GetWidthXY().
GetTextItemsSize()
unsigned OptionRow::GetTextItemsSize () const inline
References m_textItems.
Referenced by ScreenOptions::AfterChangeRow().
GetThemedItemText()
RString OptionRow::GetThemedItemText (int iChoice) const
References OptionRowHandler::GetThemedItemText(), CommonMetrics::LocalizeOptionItem(), m_bFirstItemGoesDown, m_pHand, m_RowType, and RowType_Exit.
Referenced by InitText(), and UpdateText().
GetWidthXY()
void OptionRow::GetWidthXY (PlayerNumber pn, int iChoiceOnRow, int & iWidthOut, int & iXOut, int & iYOut) const
References Actor::GetDestX(), Actor::GetDestY(), GetTextItemForRow(), Actor::GetZoomedWidth(), m_Frame, and text.
Referenced by ScreenOptions::GetWidthXY(), InitText(), and PositionUnderlines().
GoToFirstOnStart()
bool OptionRow::GoToFirstOnStart ()
References OptionRowHandler::GoToFirstOnStart(), and m_pHand.
Referenced by ScreenOptions::ProcessMenuStart().
HandleMessage()
void OptionRow::HandleMessage (const Message & msg) override virtual
Reimplemented from ActorFrame.
References FOREACH_CONST, Message::GetName(), ActorFrame::HandleMessage(), m_pHand, OptionRowHandler::m_vsReloadRowMessages, and Reload().
ImportOptions()
void OptionRow::ImportOptions (const vector< PlayerNumber > & vpns)
References ASSERT, ERASE_ONE_BOOL_AT_FRONT_IF_NEEDED, FOREACH, FOREACH_CONST, OptionRowHandler::ImportOption(), INSERT_ONE_BOOL_AT_FRONT_IF_NEEDED, OptionRowHandler::m_Def, m_pHand, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, m_vbSelected, OptionRowDefinition::m_vsChoices, and VerifySelected().
Referenced by NotifyHandlerOfSelection(), and Reload().
InitText()
void OptionRow::InitText (RowType type)
References ActorFrame::AddChild(), Actor::Copy(), ActorFrame::DeleteAllChildren(), FAIL_M, FOREACH_PlayerNumber, GetRowType(), GetThemedItemText(), ThemeMetric1D< T >::GetValue(), GetWidthXY(), Actor::GetZoomedWidth(), OptionRowType::ITEMS_END_X, OptionRowType::ITEMS_GAP_X, OptionRowType::ITEMS_LONG_ROW_SHARED_X, OptionRowType::ITEMS_LONG_ROW_X, OptionRowType::ITEMS_MIN_BASE_ZOOM, OptionRowType::ITEMS_START_X, LAYOUT_SHOW_ALL_IN_ROW, LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_Frame, OptionRowDefinition::m_layoutType, OptionRowType::m_ModIcon, m_ModIcons, m_pHand, m_pParentType, m_RowType, OptionRowType::m_sprFrame, m_sprFrame, OptionRowType::m_textItem, m_textItems, OptionRowType::m_textTitle, m_textTitle, OptionRowType::m_Underline, m_Underline, OptionRowDefinition::m_vsChoices, Actor::PlayCommand(), RowType_Exit, RowType_Normal, OptionsCursor::SetBarWidth(), Actor::SetBaseZoomX(), Actor::SetDrawOrder(), SetModIcon(), BitmapText::SetText(), Actor::SetX(), OptionRowType::SHOW_MOD_ICONS, OptionRowType::SHOW_UNDERLINES, ActorFrame::SortByDrawOrder(), ssprintf(), and UpdateText().
Referenced by ChoicesChanged().
LoadExit()
void OptionRow::LoadExit ()
References ChoicesChanged(), EXIT_NAME, LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, m_pHand, m_RowType, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, OptionRowDefinition::m_vsChoices, OptionRowHandlerUtil::MakeNull(), RowType_Exit, and SELECT_NONE.
Referenced by ScreenOptions::InitMenu().
LoadNormal()
void OptionRow::LoadNormal (OptionRowHandler * pHand, bool bFirstItemGoesDown)
References ChoicesChanged(), FOREACH_CONST, m_bFirstItemGoesDown, m_pHand, m_RowType, OptionRowHandler::m_vsReloadRowMessages, MESSAGEMAN, RowType_Normal, and MessageManager::Subscribe().
Referenced by ScreenOptions::InitMenu().
NotifyHandlerOfSelection()
bool OptionRow::NotifyHandlerOfSelection (PlayerNumber pn, int choice)
References ChoicesChanged(), FOREACH_HumanPlayer, FOREACH_PlayerNumber, ImportOptions(), m_bFirstItemGoesDown, m_pHand, m_RowType, OptionRowHandler::NotifyOfSelection(), PositionUnderlines(), and UpdateEnabledDisabled().
Referenced by SetOneSelection(), and SetSelected().
PositionIcons()
void OptionRow::PositionIcons (PlayerNumber pn)
References ThemeMetric1D< T >::GetValue(), m_ModIcons, m_pParentType, OptionRowType::MOD_ICON_X, and Actor::SetX().
PositionUnderlines()
void OptionRow::PositionUnderlines (PlayerNumber pn)
References RageColor::a, ASSERT, OptionsCursor::BeginTweening(), OptionRowType::COLOR_DISABLED, OptionRowType::COLOR_NOT_SELECTED, OptionRowType::COLOR_SELECTED, GAMESTATE, GetChoiceInRowWithFocus(), ThemeMetric< T >::GetValue(), GetWidthXY(), GameState::IsHumanPlayer(), LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, m_bRowHasFocus, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, m_pHand, m_pParentType, m_Underline, m_vbSelected, OptionRowDefinition::m_vEnabledForPlayers, OptionRowDefinition::m_vsChoices, PLAYER_1, OptionsCursor::SetBarWidth(), Actor::SetDiffuseAlpha(), Actor::SetVisible(), Actor::SetX(), OptionsCursor::StopTweening(), and OptionRowType::TWEEN_SECONDS.
Referenced by AfterImportOptions(), NotifyHandlerOfSelection(), and Reload().
PushSelf()
void OptionRow::PushSelf (lua_State * L) override virtual
Reimplemented from ActorFrame.
Referenced by LunaScreenOptions::GetOptionRow().
Reload()
void OptionRow::Reload ()
References AfterImportOptions(), ChoicesChanged(), FOREACH_HumanPlayer, ImportOptions(), m_pHand, m_RowType, PositionUnderlines(), OptionRowHandler::Reload(), OptionRowHandler::RELOAD_CHANGED_ALL, OptionRowHandler::RELOAD_CHANGED_ENABLED, OptionRowHandler::RELOAD_CHANGED_NONE, and UpdateEnabledDisabled().
Referenced by HandleMessage(), and ScreenOptions::RestartOptions().
ResetFocusFromSelection()
void OptionRow::ResetFocusFromSelection (PlayerNumber pn)
References GetOneSelection(), m_bFirstItemGoesDown, OptionRowHandler::m_Def, m_pHand, OptionRowDefinition::m_selectType, SELECT_ONE, and SetChoiceInRowWithFocus().
Referenced by AfterImportOptions().
SetChoiceInRowWithFocus()
void OptionRow::SetChoiceInRowWithFocus (PlayerNumber pn, int iChoice)
References ASSERT, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_iChoiceInRowWithFocus, m_pHand, OptionRowDefinition::m_vsChoices, PLAYER_1, and UpdateText().
Referenced by ScreenOptions::AfterChangeRow(), ScreenOptions::ChangeValueInRowRelative(), ChoicesChanged(), and ResetFocusFromSelection().
SetDestination()
void OptionRow::SetDestination (Actor::TweenState & ts, bool bTween)
References Actor::BeginTweening(), Actor::DestTweenState(), m_Frame, m_pParentType, Actor::StopTweening(), and OptionRowType::TWEEN_SECONDS.
Referenced by ScreenOptions::PositionRows().
SetExitText()
void OptionRow::SetExitText (const RString & sExitText)
References m_textItems, and BitmapText::SetText().
Referenced by ScreenSMOnlineLogin::Init().
SetModIcon()
void OptionRow::SetModIcon (PlayerNumber pn, const RString & sText, GameCommand & gc)
References Actor::HandleMessage(), m_ModIcons, m_sprFrame, ModIcon::Set(), and Message::SetParam().
Referenced by InitText().
SetOneSelection()
void OptionRow::SetOneSelection (PlayerNumber pn, int iChoice)
References FOREACH, m_vbSelected, and NotifyHandlerOfSelection().
Referenced by ScreenOptions::ChangeValueInRowRelative(), ScreenOptions::ProcessMenuStart(), and SetOneSharedSelection().
SetOneSharedSelection()
void OptionRow::SetOneSharedSelection (int iChoice)
References FOREACH_PlayerNumber, and SetOneSelection().
Referenced by ScreenOptionsToggleSongsSubPage::ImportOptions(), ScreenMiniMenu::ImportOptions(), ScreenOptions::ProcessMenuStart(), and SetOneSharedSelectionIfPresent().
SetOneSharedSelectionIfPresent()
void OptionRow::SetOneSharedSelectionIfPresent (const RString & sChoice)
References OptionRowHandler::m_Def, m_pHand, OptionRowDefinition::m_vsChoices, and SetOneSharedSelection().
Referenced by ScreenOptionsEditProfile::ImportOptions().
SetRowHasFocus()
void OptionRow::SetRowHasFocus (PlayerNumber pn, bool bRowHasFocus)
References m_bRowHasFocus.
SetSelected()
bool OptionRow::SetSelected (PlayerNumber pn, int iChoice, bool b)
References OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_pHand, m_vbSelected, NotifyHandlerOfSelection(), and PLAYER_1.
Referenced by ScreenOptions::ProcessMenuStart().
UpdateEnabledDisabled()
void OptionRow::UpdateEnabledDisabled ()
References OptionRowType::COLOR_DISABLED, OptionRowType::COLOR_NOT_SELECTED, OptionRowType::COLOR_SELECTED, Actor::DestTweenState(), Actor::TweenState::diffuse, FAIL_M, FOREACH_HumanPlayer, GetChoiceInRowWithFocus(), LAYOUT_SHOW_ALL_IN_ROW, LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, m_bRowHasFocus, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, m_pHand, m_pParentType, m_sprFrame, m_textItems, m_textTitle, OptionRowDefinition::m_vEnabledForPlayers, min(), Actor::PlayCommand(), ssprintf(), and OptionRowType::TWEEN_SECONDS.
Referenced by NotifyHandlerOfSelection(), and Reload().
UpdateText()
void OptionRow::UpdateText (PlayerNumber pn)
References GetThemedItemText(), LAYOUT_SHOW_ONE_IN_ROW, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_iChoiceInRowWithFocus, OptionRowDefinition::m_layoutType, m_pHand, m_textItems, and min().
Referenced by InitText(), and SetChoiceInRowWithFocus().
Member Data Documentation
m_bFirstItemGoesDown
bool OptionRow::m_bFirstItemGoesDown protected
Referenced by ChoicesChanged(), Clear(), GetFirstItemGoesDown(), GetThemedItemText(), LoadNormal(), NotifyHandlerOfSelection(), and ResetFocusFromSelection().
m_bRowHasFocus
bool OptionRow::m_bRowHasFocus[NUM_PLAYERS] protected
Referenced by Clear(), GetRowHasFocus(), PositionUnderlines(), SetRowHasFocus(), and UpdateEnabledDisabled().
m_Frame
ActorFrame OptionRow::m_Frame protected
Referenced by Clear(), GetWidthXY(), InitText(), OptionRow(), and SetDestination().
m_iChoiceInRowWithFocus
int OptionRow::m_iChoiceInRowWithFocus[NUM_PLAYERS] protected
Referenced by Clear(), GetChoiceInRowWithFocus(), SetChoiceInRowWithFocus(), and UpdateText().
m_ModIcons
ModIcon* OptionRow::m_ModIcons[NUM_PLAYERS] protected
Referenced by InitText(), OptionRow(), PositionIcons(), and SetModIcon().
m_pHand
OptionRowHandler* OptionRow::m_pHand protected
Referenced by AfterImportOptions(), ChoicesChanged(), Clear(), ExportOptions(), GetChoiceInRowWithFocus(), GetHandler(), GetRowDef(), GetRowTitle(), GetSelected(), GetTextItemForRow(), GetThemedItemText(), GoToFirstOnStart(), HandleMessage(), ImportOptions(), InitText(), LoadExit(), LoadNormal(), NotifyHandlerOfSelection(), OptionRow(), PositionUnderlines(), Reload(), ResetFocusFromSelection(), SetChoiceInRowWithFocus(), SetOneSharedSelectionIfPresent(), SetSelected(), UpdateEnabledDisabled(), and UpdateText().
m_pParentType
const OptionRowType* OptionRow::m_pParentType protected
Referenced by GetRowTitle(), InitText(), OptionRow(), PositionIcons(), PositionUnderlines(), SetDestination(), and UpdateEnabledDisabled().
m_RowType
RowType OptionRow::m_RowType protected
Referenced by GetRowType(), GetThemedItemText(), InitText(), LoadExit(), LoadNormal(), NotifyHandlerOfSelection(), and Reload().
m_sprFrame
Actor* OptionRow::m_sprFrame protected
Referenced by InitText(), SetModIcon(), and UpdateEnabledDisabled().
m_textItems
vector<BitmapText*> OptionRow::m_textItems protected
Referenced by AfterImportOptions(), Clear(), GetTextItemForRow(), GetTextItemsSize(), InitText(), SetExitText(), UpdateEnabledDisabled(), and UpdateText().
m_textTitle
BitmapText* OptionRow::m_textTitle protected
Referenced by ChoicesChanged(), InitText(), OptionRow(), and UpdateEnabledDisabled().
m_tsDestination
Actor::TweenState OptionRow::m_tsDestination protected
Referenced by OptionRow().
m_Underline
vector<OptionsCursor*> OptionRow::m_Underline[NUM_PLAYERS] protected
Referenced by AfterImportOptions(), Clear(), InitText(), and PositionUnderlines().
m_vbSelected
vector<bool> OptionRow::m_vbSelected[NUM_PLAYERS] protected
Referenced by AfterImportOptions(), ChoicesChanged(), Clear(), ExportOptions(), GetOneSelection(), GetSelected(), ImportOptions(), PositionUnderlines(), SetOneSelection(), and SetSelected().
The documentation for this class was generated from the following files:
OptionRow.h
OptionRow.cpp