Etterna: NotesWriterJson.cpp File Reference
NotesWriterJson.cpp File Reference
#include "global.h"
#include "NotesWriterJson.h"
#include "BackgroundUtil.h"
#include "GameManager.h"
#include "JsonUtil.h"
#include "NoteData.h"
#include "Song.h"
#include "Steps.h"
#include "TimingData.h"
#include "json/value.h"
Functions
static void Serialize (const TimingSegment &seg, Json::Value &root)
static void Serialize (const TimingData &td, Json::Value &root)
static void Serialize (const LyricSegment &o, Json::Value &root)
static void Serialize (const BackgroundDef &o, Json::Value &root)
static void Serialize (const BackgroundChange &o, Json::Value &root)
static void Serialize (const TapNote &o, Json::Value &root)
static void Serialize (const NoteData &o, Json::Value &root)
static void Serialize (const RadarValues &o, Json::Value &root)
static void Serialize (const Steps &o, Json::Value &root)
Function Documentation
Serialize() [1/9]
static void Serialize (const TimingSegment & seg, Json::Value & root) static
References TimingSegment::GetBeat(), BPMSegment::GetBPM(), StopSegment::GetPause(), TimingSegment::GetType(), and SEGMENT_BPM.
Referenced by Serialize(), NotesWriterJson::WriteSong(), and NotesWriterJson::WriteSteps().
Serialize() [2/9]
static void Serialize (const TimingData & td, Json::Value & root) static
References TimingData::GetTimingSegments(), SEGMENT_BPM, SEGMENT_STOP, Serialize(), and JsonUtil::SerializeVectorPointers().
Serialize() [3/9]
static void Serialize (const LyricSegment & o, Json::Value & root) static
References LyricSegment::m_Color, LyricSegment::m_fStartTime, LyricSegment::m_sLyric, and RageColor::ToString().
Serialize() [4/9]
static void Serialize (const BackgroundDef & o, Json::Value & root) static
References BackgroundDef::m_sColor1, BackgroundDef::m_sEffect, BackgroundDef::m_sFile1, and BackgroundDef::m_sFile2.
Serialize() [5/9]
static void Serialize (const BackgroundChange & o, Json::Value & root) static
References BackgroundChange::m_def, BackgroundChange::m_fRate, BackgroundChange::m_fStartBeat, BackgroundChange::m_sTransition, and Serialize().
Serialize() [6/9]
static void Serialize (const TapNote & o, Json::Value & root) static
References TapNote::iDuration, TapNote::iKeysoundIndex, PLAYER_INVALID, TapNote::pn, TapNote::subType, TapNoteType_HoldHead, TapNoteType_Tap, and TapNote::type.
Serialize() [7/9]
static void Serialize (const NoteData & o, Json::Value & root) static
References NoteData::GetNumTracks(), NoteData::GetTapNoteRange(), MAX_NOTE_ROW, NoteRowToBeat(), and Serialize().
Serialize() [8/9]
static void Serialize (const RadarValues & o, Json::Value & root) static
References FOREACH_ENUM, and RadarCategoryToString().
Serialize() [9/9]
static void Serialize (const Steps & o, Json::Value & root) static
References DifficultyToString(), Steps::GetDescription(), Steps::GetDifficulty(), Steps::GetHash(), Steps::GetMeter(), Steps::GetNoteData(), Steps::m_StepsType, Serialize(), and StringConversion::ToString().