Etterna: RageQuadratic Class Reference
RageQuadratic Class Reference
#include <RageMath.h>
Public Member Functions
void SetFromBezier (float fC1, float fC2, float fC3, float fC4)
void GetBezier (float &fC1, float &fC2, float &fC3, float &fC4) const
void SetFromCubic (float fX1, float fX2, float fX3, float fX4)
float Evaluate (float fT) const
float GetSlope (float fT) const
float GetBezierStart () const
float GetBezierEnd () const
void PushSelf (lua_State *L)
Private Attributes
float m_fA
float m_fB
float m_fC
float m_fD
Member Function Documentation
Evaluate()
float RageQuadratic::Evaluate (float fT) const
References m_fA, m_fB, m_fC, and m_fD.
Referenced by RageBezier2D::Evaluate(), LunaRageQuadratic::evaluate(), RageBezier2D::EvaluateYFromX(), and InterpolateBezier1D::Tween().
GetBezier()
void RageQuadratic::GetBezier (float & fC1, float & fC2, float & fC3, float & fC4) const
References m_fA, m_fB, m_fC, and m_fD.
Referenced by LunaRageQuadratic::get_bezier().
GetBezierEnd()
float RageQuadratic::GetBezierEnd () const inline
References m_fA, m_fB, m_fC, and m_fD.
Referenced by RageBezier2D::EvaluateYFromX(), and LunaRageQuadratic::get_bezier_end().
GetBezierStart()
float RageQuadratic::GetBezierStart () const inline
References m_fD.
Referenced by RageBezier2D::EvaluateYFromX(), and LunaRageQuadratic::get_bezier_start().
GetSlope()
float RageQuadratic::GetSlope (float fT) const
References m_fA, m_fB, and m_fC.
Referenced by RageBezier2D::EvaluateYFromX(), and LunaRageQuadratic::get_slope().
PushSelf()
void RageQuadratic::PushSelf (lua_State * L)
Referenced by LunaRageBezier2D::get_x(), and LunaRageBezier2D::get_y().
SetFromBezier()
void RageQuadratic::SetFromBezier (float fC1, float fC2, float fC3, float fC4)
References m_fA, m_fB, m_fC, and m_fD.
Referenced by ITween::CreateFromStack(), LunaRageQuadratic::set_from_bezier(), and RageBezier2D::SetFromBezier().
SetFromCubic()
void RageQuadratic::SetFromCubic (float fX1, float fX2, float fX3, float fX4)
References m_fA, m_fB, m_fC, and m_fD.
Referenced by LunaRageQuadratic::set_from_cubic().
Member Data Documentation
m_fA
float RageQuadratic::m_fA private
Referenced by Evaluate(), GetBezier(), GetBezierEnd(), GetSlope(), SetFromBezier(), and SetFromCubic().
m_fB
float RageQuadratic::m_fB private
Referenced by Evaluate(), GetBezier(), GetBezierEnd(), GetSlope(), SetFromBezier(), and SetFromCubic().
m_fC
float RageQuadratic::m_fC private
Referenced by Evaluate(), GetBezier(), GetBezierEnd(), GetSlope(), SetFromBezier(), and SetFromCubic().
m_fD
float RageQuadratic::m_fD private
Referenced by Evaluate(), GetBezier(), GetBezierEnd(), GetBezierStart(), SetFromBezier(), and SetFromCubic().
The documentation for this class was generated from the following files:
RageMath.h
RageMath.cpp