Etterna: LunaScoreManager Class Reference
LunaScoreManager Class Reference
Public Member Functions
LunaScoreManager ()
Public Member Functions inherited from Luna< ScoreManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetScoresByKey (T *p, lua_State *L)
static int SortSSRs (T *p, lua_State *L)
static int ValidateAllScores (T *p, lua_State *L)
static int GetTopSSRHighScore (T *p, lua_State *L)
static int GetMostRecentScore (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScoreManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScoreManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScoreManager >
using T = ScoreManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScoreManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaScoreManager()
LunaScoreManager::LunaScoreManager () inline
References ADD_METHOD.
Member Function Documentation
GetMostRecentScore()
static int LunaScoreManager::GetMostRecentScore (T * p, lua_State * L) inline static
References ScoreManager::GetMostRecentScore(), and HighScore::PushSelf().
GetScoresByKey()
static int LunaScoreManager::GetScoresByKey (T * p, lua_State * L) inline static
References ScoresForChart::GetPlayedRateDisplayStrings(), ScoresForChart::GetPlayedRateKeys(), ScoresForChart::GetScoresAtRate(), ScoreManager::GetScoresForChart(), LuaHelpers::Push(), ScoresAtRate::PushSelf(), and SArg.
GetTopSSRHighScore()
static int LunaScoreManager::GetTopSSRHighScore (T * p, lua_State * L) inline static
References ScoreManager::GetTopSSRHighScore(), IArg, and HighScore::PushSelf().
SortSSRs()
static int LunaScoreManager::SortSSRs (T * p, lua_State * L) inline static
References ScoreManager::SortTopSSRPtrs().
ValidateAllScores()
static int LunaScoreManager::ValidateAllScores (T * p, lua_State * L) inline static
References ScoreManager::EnableAllScores().
The documentation for this class was generated from the following file:
ScoreManager.cpp