Etterna: XNode Class Reference
XNode Class Reference
#include <XmlFile.h>
Public Member Functions
void SetName (const RString &sName)
const RString & GetName () const
template<typename T >
void GetTextValue (T &out) const
const XNodeValue * GetAttr (const RString &sAttrName) const
XNodeValue * GetAttr (const RString &sAttrName)
template<typename T >
bool GetAttrValue (const RString &sName, T &out) const
bool PushAttrValue (lua_State *L, const RString &sName) const
XNodes::iterator GetChildrenBegin ()
XNodes::const_iterator GetChildrenBegin () const
XNodes::iterator GetChildrenEnd ()
XNodes::const_iterator GetChildrenEnd () const
bool ChildrenEmpty () const
const XNode * GetChild (const RString &sName) const
XNode * GetChild (const RString &sName)
template<typename T >
bool GetChildValue (const RString &sName, T &out) const
bool PushChildValue (lua_State *L, const RString &sName) const
template<typename T >
XNode * AppendChild (const RString &sName, T value)
XNode * AppendChild (const RString &sName)
XNode * AppendChild (XNode *node)
bool RemoveChild (XNode *node, bool bDelete=true)
void RemoveChildFromByName (XNode *node)
void RenameChildInByName (XNode *node)
XNodeValue * AppendAttrFrom (const RString &sName, XNodeValue *pValue, bool bOverwrite=true)
XNodeValue * AppendAttr (const RString &sName)
template<typename T >
XNodeValue * AppendAttr (const RString &sName, T value)
bool RemoveAttr (const RString &sName)
XNode ()
XNode (const RString &sName)
XNode (const XNode &cpy)
~XNode ()
void Clear ()
Public Attributes
RString m_sName
XAttrs m_attrs
Static Public Attributes
static const RString TEXT_ATTRIBUTE = "__TEXT__"
Private Member Functions
void Free ()
XNode & operator= (const XNode &cpy)=delete
Private Attributes
XNodes m_childs
multimap< RString, XNode * > m_children_by_name
Constructor & Destructor Documentation
XNode() [1/3]
XNode::XNode () default
Referenced by AppendChild(), and XNode().
XNode() [2/3]
XNode::XNode (const RString & sName) explicit
References m_sName.
XNode() [3/3]
XNode::XNode (const XNode & cpy)
References AppendAttrFrom(), AppendChild(), FOREACH_CONST_Attr, FOREACH_CONST_Child, and XNode().
~XNode()
XNode::~XNode () inline
References Free().
Member Function Documentation
AppendAttr() [1/2]
XNodeValue * XNode::AppendAttr (const RString & sName)
References DEBUG_ASSERT, and m_attrs.
Referenced by XmlFileUtil::AnnotateXNodeTree(), AppendAttr(), AppendChild(), HighScoreImpl::CreateEttNode(), StyleID::CreateNode(), BackgroundDef::CreateNode(), TapNoteResult::CreateNode(), ScoresAtRate::CreateNode(), Chart::CreateNode(), Playlist::CreateNode(), GoalsForChart::CreateNode(), StepsID::CreateNode(), SongID::CreateNode(), NoteData::CreateNode(), LuaHelpers::GetLuaInformation(), LuaInformation(), ActorUtil::MakeActor(), XMLProfile::SaveCategoryScoresCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), ScreenGameplay::SaveReplay(), IniFile::SetKeyValue(), IniFile::SetValue(), InputMappings::WriteMappings(), and IPreference::WriteTo().
AppendAttr() [2/2]
template<typename T > XNodeValue* XNode::AppendAttr (const RString & sName, T value) inline
References AppendAttr(), and XNodeValue::SetValue().
AppendAttrFrom()
XNodeValue * XNode::AppendAttrFrom (const RString & sName, XNodeValue * pValue, bool bOverwrite = true)
References DEBUG_ASSERT, and m_attrs.
Referenced by XmlFileUtil::MergeIniUnder(), and XNode().
AppendChild() [1/3]
template<typename T > XNode* XNode::AppendChild (const RString & sName, T value) inline
References AppendAttr(), and TEXT_ATTRIBUTE.
Referenced by AppendChild(), HighScoreImpl::CreateEttNode(), ScoresAtRate::CreateNode(), RadarValues::CreateNode(), Playlist::CreateNode(), HighScoreImpl::CreateNode(), ScoresForChart::CreateNode(), ScoreGoal::CreateNode(), GoalsForChart::CreateNode(), ScoreManager::CreateNode(), TapNote::CreateNode(), HighScoreList::CreateNode(), Screenshot::CreateNode(), NoteData::CreateNode(), LuaHelpers::GetLuaInformation(), LuaInformation(), XmlFileUtil::MergeIniUnder(), IniFile::ReadFile(), XMLProfile::SaveCategoryScoresCreateNode(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveEttXmlCreateNode(), XMLProfile::SaveFavoritesCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), XMLProfile::SavePermaMirrorCreateNode(), XMLProfile::SavePlaylistsCreateNode(), PrefsManager::SavePrefsToIni(), ScreenGameplay::SaveReplay(), XMLProfile::SaveScoreGoalsCreateNode(), XMLProfile::SaveScreenshotDataCreateNode(), XMLProfile::SaveSongScoresCreateNode(), XMLProfile::SaveStatsXmlCreateNode(), InputMappings::WriteMappings(), and XNode().
AppendChild() [2/3]
XNode* XNode::AppendChild (const RString & sName) inline
References AppendChild(), and XNode().
AppendChild() [3/3]
XNode * XNode::AppendChild (XNode * node)
References DEBUG_ASSERT, m_children_by_name, m_childs, and m_sName.
ChildrenEmpty()
bool XNode::ChildrenEmpty () const inline
Referenced by ScoresAtRate::CreateNode(), Playlist::CreateNode(), and Playlist::LoadFromNode().
Clear()
void XNode::Clear ()
References Free().
Referenced by LoadedThemeData::ClearAll(), and NoteSkinManager::LoadNoteSkinData().
Free()
void XNode::Free () private
References FOREACH_Attr, FOREACH_Child, m_attrs, m_children_by_name, and m_childs.
Referenced by Clear(), and ~XNode().
GetAttr() [1/2]
const XNodeValue * XNode::GetAttr (const RString & sAttrName) const
References m_attrs.
Referenced by GetAttrValue(), ActorUtil::LoadFromNode(), PushAttrValue(), and PushChildValue().
GetAttr() [2/2]
XNodeValue * XNode::GetAttr (const RString & sAttrName)
References m_attrs.
GetAttrValue()
template<typename T > bool XNode::GetAttrValue (const RString & sName, T & out) const inline
References GetAttr(), and XNodeValue::GetValue().
Referenced by BGAnimation::AddLayersFromAniDir(), ActorUtil::GetAttrPath(), ActorUtil::GetSourcePath(), GetTextValue(), IniFile::GetValue(), ActorUtil::GetWhere(), BackgroundImpl::Init(), PlayerAI::InitFromDisk(), AnimatedTexture::Load(), MeterDisplay::LoadFromNode(), BGAnimation::LoadFromNode(), BGAnimationLayer::LoadFromNode(), ActorFrame::LoadFromNode(), BitmapText::LoadFromNode(), ActorSound::LoadFromNode(), PercentageDisplay::LoadFromNode(), StyleID::LoadFromNode(), ActorScroller::LoadFromNode(), Sprite::LoadFromNode(), ActorMultiVertex::LoadFromNode(), PaneDisplay::LoadFromNode(), Chart::LoadFromNode(), Playlist::LoadFromNode(), ScoresForChart::LoadFromNode(), GoalsForChart::LoadFromNode(), ActorUtil::LoadFromNode(), StepsID::LoadFromNode(), SongID::LoadFromNode(), Profile::LoadTypeFromDir(), IPreference::ReadDefaultFrom(), and IPreference::ReadFrom().
GetChild() [1/2]
const XNode * XNode::GetChild (const RString & sName) const
References m_children_by_name.
Referenced by BGAnimation::AddLayersFromAniDir(), IniFile::DeleteKey(), IniFile::DeleteValue(), GetChildValue(), GetFilterToFileNames(), ThemeManager::GetMetricsThatBeginWith(), ThemeManager::GetOptionNames(), PlayerAI::InitFromDisk(), AnimatedTexture::Load(), TitleSubst::Load(), actor_template_t::load_frames_from_file(), actor_template_t::load_model_from_file(), actor_template_t::load_node(), XMLProfile::LoadCategoryScoresFromNode(), ActorFrame::LoadChildrenFromNode(), XMLProfile::LoadEttGeneralDataFromNode(), XMLProfile::LoadEttXmlFromNode(), Font::LoadFontPageSettings(), BGAnimation::LoadFromAniDir(), HighScoreImpl::LoadFromEttNode(), MeterDisplay::LoadFromNode(), StepsDisplayList::LoadFromNode(), PercentageDisplay::LoadFromNode(), Sprite::LoadFromNode(), Playlist::LoadFromNode(), HighScoreImpl::LoadFromNode(), Screenshot::LoadFromNode(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::LoadSongScoresFromNode(), XMLProfile::LoadStatsXmlForConversion(), Profile::LoadTypeFromDir(), ActorUtil::MakeActor(), XmlFileUtil::MergeIniUnder(), PushChildValue(), LunaThemeManager::PushMetricNamesInGroup(), PrefsManager::ReadDefaultsFromIni(), IniFile::ReadFile(), InputMappings::ReadMappings(), PrefsManager::ReadPrefsFromIni(), IniFile::RenameKey(), PrefsManager::SavePrefsToIni(), and InputMappings::WriteMappings().
GetChild() [2/2]
XNode * XNode::GetChild (const RString & sName)
References m_children_by_name.
GetChildrenBegin() [1/2]
XNodes::iterator XNode::GetChildrenBegin () inline
Referenced by XmlFileUtil::MergeIniUnder().
GetChildrenBegin() [2/2]
XNodes::const_iterator XNode::GetChildrenBegin () const inline
GetChildrenEnd() [1/2]
XNodes::iterator XNode::GetChildrenEnd () inline
Referenced by XmlFileUtil::MergeIniUnder().
GetChildrenEnd() [2/2]
XNodes::const_iterator XNode::GetChildrenEnd () const inline
GetChildValue()
template<typename T > bool XNode::GetChildValue (const RString & sName, T & out) const inline
References GetChild(), and GetTextValue().
Referenced by XMLProfile::LoadEttGeneralDataFromNode(), HighScoreImpl::LoadFromEttNode(), RadarValues::LoadFromNode(), HighScoreImpl::LoadFromNode(), ScoreGoal::LoadFromNode(), Screenshot::LoadFromNode(), and XMLProfile::LoadGeneralDataFromNode().
GetName()
const RString& XNode::GetName () const inline
References m_sName.
Referenced by BackgroundImpl::Init(), actor_template_t::load_node(), XMLProfile::LoadCategoryScoresFromNode(), XMLProfile::LoadEttGeneralDataFromNode(), XMLProfile::LoadEttXmlFromNode(), StyleID::LoadFromNode(), TitleTrans::LoadFromNode(), Chart::LoadFromNode(), RadarValues::LoadFromNode(), Playlist::LoadFromNode(), ScoresForChart::LoadFromNode(), HighScoreImpl::LoadFromNode(), ScoreGoal::LoadFromNode(), HighScoreList::LoadFromNode(), StepsID::LoadFromNode(), Screenshot::LoadFromNode(), SongID::LoadFromNode(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::LoadScreenshotDataFromNode(), XMLProfile::LoadSongScoresFromNode(), XMLProfile::LoadStatsXmlFromNode(), XmlFileUtil::MergeIniUnder(), and RemoveChildFromByName().
GetTextValue()
template<typename T > void XNode::GetTextValue (T & out) const inline
References GetAttrValue().
Referenced by GetChildValue().
operator=()
XNode& XNode::operator= (const XNode & cpy) private delete
PushAttrValue()
bool XNode::PushAttrValue (lua_State * L, const RString & sName) const
References GetAttr(), and XNodeValue::PushValue().
Referenced by DynamicActorScroller::LoadFromNode(), ScoreDisplayAliveTime::LoadFromNode(), PercentageDisplay::LoadFromNode(), ActorScroller::LoadFromNode(), and PaneDisplay::LoadFromNode().
PushChildValue()
bool XNode::PushChildValue (lua_State * L, const RString & sName) const
References GetAttr(), GetChild(), and XNodeValue::PushValue().
RemoveAttr()
bool XNode::RemoveAttr (const RString & sName)
References m_attrs.
Referenced by IniFile::DeleteValue().
RemoveChild()
bool XNode::RemoveChild (XNode * node, bool bDelete = true)
References m_childs, and RemoveChildFromByName().
Referenced by IniFile::DeleteKey(), XmlFileUtil::MergeIniUnder(), and InputMappings::WriteMappings().
RemoveChildFromByName()
void XNode::RemoveChildFromByName (XNode * node)
References GetName(), m_children_by_name, and m_sName.
Referenced by RemoveChild(), and RenameChildInByName().
RenameChildInByName()
void XNode::RenameChildInByName (XNode * node)
References m_children_by_name, m_sName, and RemoveChildFromByName().
Referenced by IniFile::RenameKey().
SetName()
void XNode::SetName (const RString & sName) inline
Referenced by IniFile::RenameKey().
Member Data Documentation
m_attrs
XAttrs XNode::m_attrs
Referenced by AppendAttr(), AppendAttrFrom(), Free(), GetAttr(), ThemeManager::GetMetricsThatBeginWith(), LunaThemeManager::PushMetricNamesInGroup(), and RemoveAttr().
m_children_by_name
multimap<RString, XNode*> XNode::m_children_by_name private
Referenced by AppendChild(), Free(), GetChild(), RemoveChildFromByName(), and RenameChildInByName().
m_childs
XNodes XNode::m_childs private
Referenced by AppendChild(), Free(), and RemoveChild().
m_sName
RString XNode::m_sName
Referenced by AppendChild(), GetName(), RemoveChildFromByName(), RenameChildInByName(), XMLProfile::SaveEttGeneralDataCreateNode(), XMLProfile::SaveGeneralDataCreateNode(), and XNode().
TEXT_ATTRIBUTE
const RString XNode::TEXT_ATTRIBUTE = "__TEXT__" static
Referenced by AppendChild(), and XMLProfile::SaveGeneralDataCreateNode().
The documentation for this class was generated from the following files:
XmlFile.h
XmlFile.cpp