Etterna: RageSoundDriver_WDMKS Class Reference
RageSoundDriver_WDMKS Class Reference
#include <RageSoundDriver_WDMKS.h>
Public Member Functions
RageSoundDriver_WDMKS ()
~RageSoundDriver_WDMKS ()
RString Init ()
int64_t GetPosition () const
float GetPlayLatency () const
int GetSampleRate () const
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void MixerThread ()
bool Fill (int iPacket, RString &sError)
void Read (void *pData, int iFrames, int iLastCursorPos, int iCurrentFrame)
void SetupDecodingThread ()
Static Private Member Functions
static int MixerThread_start (void *p)
Private Attributes
RageThread MixingThread
bool m_bShutdown
int m_iLastCursorPos
HANDLE m_hSignal
WinWdmStream * m_pStream
WinWdmFilter * m_pFilter
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_WDMKS()
RageSoundDriver_WDMKS::RageSoundDriver_WDMKS ()
References m_bShutdown, m_hSignal, m_iLastCursorPos, m_pFilter, and m_pStream.
~RageSoundDriver_WDMKS()
RageSoundDriver_WDMKS::~RageSoundDriver_WDMKS ()
References RageThread::IsCreated(), LOG, m_bShutdown, m_hSignal, m_pFilter, m_pStream, MixingThread, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
Fill()
bool RageSoundDriver_WDMKS::Fill (int iPacket, RString & sError) private
References GetPosition(), WinWdmStream::m_iFramesPerChunk, m_iLastCursorPos, WinWdmStream::m_Packets, m_pStream, Read(), and WinWdmStream::SubmitPacket().
Referenced by MixerThread().
GetPlayLatency()
float RageSoundDriver_WDMKS::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
References WinWdmStream::m_iFramesPerChunk, WinWdmStream::m_iSampleRate, and m_pStream.
GetPosition()
int64_t RageSoundDriver_WDMKS::GetPosition () const virtual
Implements RageSoundDriver.
References ASSERT_M, WinWdmPin::m_hHandle, WinWdmStream::m_iBytesPerOutputSample, WinWdmStream::m_iDeviceOutputChannels, WinWdmStream::m_pPlaybackPin, m_pStream, and WdmGetPropertySimple().
Referenced by Fill().
GetSampleRate()
int RageSoundDriver_WDMKS::GetSampleRate () const virtual
Reimplemented from RageSoundDriver.
References WinWdmStream::m_iSampleRate, and m_pStream.
Init()
RString RageSoundDriver_WDMKS::Init () virtual
Reimplemented from RageSoundDriver.
References BuildFilterList(), RageThread::Create(), DeviceSampleFormat_Int16, FOREACH_CONST, LOG, WinWdmFilter::m_apPins, WinWdmPin::m_dataRangesItem, PrefsManager::m_iSoundPreferredSampleRate, PrefsManager::m_iSoundWriteAhead, m_pFilter, m_pStream, WinWdmFilter::m_sFriendlyName, MixerThread_start(), MixingThread, WinWdmStream::Open(), PaWinWdm_Initialize(), PREFSMAN, RageSoundDriver::SetDecodeBufferSize(), RageThread::SetName(), RageSoundDriver::StartDecodeThread(), and RageLog::Trace().
MixerThread()
void RageSoundDriver_WDMKS::MixerThread () private
References ASSERT, FAIL_M, Fill(), LOG, m_bShutdown, m_hSignal, WinWdmStream::m_iWriteAheadChunks, WinWdmStream::m_pPlaybackPin, m_pStream, WinWdmStream::m_Signal, MAX_CHUNKS, WinWdmPin::SetState(), and RageLog::Warn().
MixerThread_start()
int RageSoundDriver_WDMKS::MixerThread_start (void * p) static private
Referenced by Init().
Read()
void RageSoundDriver_WDMKS::Read (void * pData, int iFrames, int iLastCursorPos, int iCurrentFrame) private
References DeviceSampleFormat_Int16, WinWdmStream::m_DeviceSampleFormat, WinWdmStream::m_iBytesPerOutputSample, WinWdmStream::m_iDeviceOutputChannels, m_pStream, and RageSoundDriver::Mix().
Referenced by Fill().
SetupDecodingThread()
void RageSoundDriver_WDMKS::SetupDecodingThread () private virtual
Reimplemented from RageSoundDriver.
References LOG, and RageLog::Warn().
Member Data Documentation
m_bShutdown
bool RageSoundDriver_WDMKS::m_bShutdown private
Referenced by MixerThread(), RageSoundDriver_WDMKS(), and ~RageSoundDriver_WDMKS().
m_hSignal
HANDLE RageSoundDriver_WDMKS::m_hSignal private
Referenced by MixerThread(), RageSoundDriver_WDMKS(), and ~RageSoundDriver_WDMKS().
m_iLastCursorPos
int RageSoundDriver_WDMKS::m_iLastCursorPos private
Referenced by Fill(), and RageSoundDriver_WDMKS().
m_pFilter
WinWdmFilter* RageSoundDriver_WDMKS::m_pFilter private
Referenced by Init(), RageSoundDriver_WDMKS(), and ~RageSoundDriver_WDMKS().
m_pStream
WinWdmStream* RageSoundDriver_WDMKS::m_pStream private
Referenced by Fill(), GetPlayLatency(), GetPosition(), GetSampleRate(), Init(), MixerThread(), RageSoundDriver_WDMKS(), Read(), and ~RageSoundDriver_WDMKS().
MixingThread
RageThread RageSoundDriver_WDMKS::MixingThread private
Referenced by Init(), and ~RageSoundDriver_WDMKS().
The documentation for this class was generated from the following files:
RageSoundDriver_WDMKS.h
RageSoundDriver_WDMKS.cpp