Etterna: DebugLineVisualDelayDown Class Reference
DebugLineVisualDelayDown Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Preference< float > * GetPref ()
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineVisualDelayDown::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References ChangeVisualDelay(), IDebugLine::DoAndLog(), f, GetPref(), and ssprintf().
GetDisplayTitle()
RString DebugLineVisualDelayDown::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and VISUAL_DELAY_DOWN.
GetDisplayValue()
RString DebugLineVisualDelayDown::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPref()
Preference<float>* DebugLineVisualDelayDown::GetPref () inline private
References Preference< T >::GetPreferenceByName().
Referenced by DoAndLog().
IsEnabled()
bool DebugLineVisualDelayDown::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp