Etterna: WheelNotifyIcon.cpp File Reference
WheelNotifyIcon.cpp File Reference
#include "WheelNotifyIcon.h"
#include "GameConstantsAndTypes.h"
#include "MusicWheel.h"
#include "RageTimer.h"
#include "RageUtil.h"
#include "ThemeManager.h"
#include "global.h"
Variables
static ThemeMetric< bool > SHOW_TRAINING ("WheelNotifyIcon", "ShowTraining")
static ThemeMetric< bool > BLINK_BEST_ICON ("WheelNotifyIcon", "BlinkPlayersBest")
static ThemeMetric< int > NUM_ICONS_TO_SHOW ("WheelNotifyIcon", "NumIconsToShow")
Variable Documentation
BLINK_BEST_ICON
ThemeMetric<bool> BLINK_BEST_ICON("WheelNotifyIcon", "BlinkPlayersBest") static
Referenced by WheelNotifyIcon::SetFlags().
NUM_ICONS_TO_SHOW
ThemeMetric<int> NUM_ICONS_TO_SHOW("WheelNotifyIcon", "NumIconsToShow") static
Referenced by WheelNotifyIcon::SetFlags().
SHOW_TRAINING
ThemeMetric<bool> SHOW_TRAINING("WheelNotifyIcon", "ShowTraining") static
Referenced by WheelNotifyIcon::SetFlags().