Etterna: LocalizedString Class Reference
LocalizedString Class Reference
Get a String based on the user's natural language.
#include <LocalizedString.h>
Public Types
using MakeLocalizer = ILocalizedStringImpl *(*)()
Public Member Functions
LocalizedString (const RString &sGroup="", const RString &sName="")
LocalizedString (LocalizedString const &other)
~LocalizedString ()
void Load (const RString &sGroup, const RString &sName)
operator const RString & () const
const RString & GetValue () const
Static Public Member Functions
static void RegisterLocalizer (MakeLocalizer pFunc)
Private Member Functions
void CreateImpl ()
LocalizedString & operator= (const LocalizedString &rhs)=delete
Private Attributes
RString m_sGroup
RString m_sName
ILocalizedStringImpl * m_pImpl
Detailed Description
Get a String based on the user's natural language.
Member Typedef Documentation
MakeLocalizer
using LocalizedString::MakeLocalizer = ILocalizedStringImpl* (*)()
Constructor & Destructor Documentation
LocalizedString() [1/2]
LocalizedString::LocalizedString (const RString & sGroup = "", const RString & sName = "")
References CreateImpl(), m_pImpl, m_sGroup, m_sName, and SubscriptionManager< T >::Subscribe().
LocalizedString() [2/2]
LocalizedString::LocalizedString (LocalizedString const & other)
References CreateImpl(), m_pImpl, m_sGroup, m_sName, and SubscriptionManager< T >::Subscribe().
~LocalizedString()
LocalizedString::~LocalizedString ()
References m_pImpl, SAFE_DELETE, and SubscriptionManager< T >::Unsubscribe().
Member Function Documentation
CreateImpl()
void LocalizedString::CreateImpl () private
References g_pMakeLocalizedStringImpl, ILocalizedStringImpl::Load(), m_pImpl, m_sGroup, m_sName, and SAFE_DELETE.
Referenced by Load(), LocalizedString(), and RegisterLocalizer().
GetValue()
const RString & LocalizedString::GetValue () const
References ILocalizedStringImpl::GetLocalized(), and m_pImpl.
Referenced by AdjustSync::AutosyncOffset(), AdjustSync::AutosyncTempo(), ScreenPackages::CancelDownload(), InputMapper::CheckForChangedInputDevicesAndRemap(), SMOProtocol::Connect(), CopyEdits(), RageMovieTexture::Create(), InputHandler::Create(), CreateDisplay(), NetworkSyncManager::DisplayStartupStatus(), DebugLineMuteActions::DoAndLog(), ScreenPackages::EnterURL(), ScreenTextEntry::FloatValidate(), FormatNumberAndSuffix(), GetActualGraphicOptionsString(), GetDebugButtonName(), DebugLineAutoplay::GetDisplayTitle(), DebugLineAssist::GetDisplayTitle(), DebugLineAutosync::GetDisplayTitle(), DebugLineSlow::GetDisplayTitle(), DebugLineHalt::GetDisplayTitle(), DebugLineStats::GetDisplayTitle(), DebugLineVsync::GetDisplayTitle(), DebugLineAllowMultitexture::GetDisplayTitle(), DebugLineShowMasks::GetDisplayTitle(), DebugLineProfileSlot::GetDisplayTitle(), DebugLineClearProfileStats::GetDisplayTitle(), DebugLineFillProfileStats::GetDisplayTitle(), DebugLineSendNotesEnded::GetDisplayTitle(), DebugLineResetKeyMapping::GetDisplayTitle(), DebugLineMuteActions::GetDisplayTitle(), DebugLineReloadCurrentScreen::GetDisplayTitle(), DebugLineRestartCurrentScreen::GetDisplayTitle(), DebugLineCurrentScreenOn::GetDisplayTitle(), DebugLineCurrentScreenOff::GetDisplayTitle(), DebugLineReloadTheme::GetDisplayTitle(), DebugLineReloadOverlayScreens::GetDisplayTitle(), DebugLineToggleErrors::GetDisplayTitle(), DebugLineShowRecentErrors::GetDisplayTitle(), DebugLineClearErrors::GetDisplayTitle(), DebugLineConvertXML::GetDisplayTitle(), DebugLineWriteProfiles::GetDisplayTitle(), DebugLineWritePreferences::GetDisplayTitle(), DebugLineMenuTimer::GetDisplayTitle(), DebugLineFlushLog::GetDisplayTitle(), DebugLinePullBackCamera::GetDisplayTitle(), DebugLineVolumeUp::GetDisplayTitle(), DebugLineVolumeDown::GetDisplayTitle(), DebugLineVisualDelayUp::GetDisplayTitle(), DebugLineVisualDelayDown::GetDisplayTitle(), DebugLineForceCrash::GetDisplayTitle(), DebugLineUptime::GetDisplayTitle(), IDebugLine::GetDisplayValue(), DebugLineAutoplay::GetDisplayValue(), DebugLineAssist::GetDisplayValue(), DebugLineAutosync::GetDisplayValue(), InputHandler::GetLocalizedInputString(), GameState::GetPlayerDisplayName(), GetPromptText(), SongUtil::GetSectionNameFromSongAndSort(), AdjustSync::GetSyncChangeTextGlobal(), AdjustSync::GetSyncChangeTextSong(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptionsManageProfiles::HandleScreenMessage(), ScreenPackages::HTMLParse(), ScreenPackages::HTTPUpdate(), RageDisplay_D3D::Init(), ScreenMapControllers::Init(), RageSoundManager::Init(), RageDisplay_Legacy::Init(), ScreenTitleMenu::Input(), ScreenDebugOverlay::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), ScreenTextEntry::IntValidate(), RoomInfoDisplay::Load(), RageInput::LoadDrivers(), LowLevelWindow_X11::LowLevelWindow_X11(), ScreenNetworkOptions::MenuStart(), operator const RString &(), ScreenOptionsManageProfiles::ProcessMenuStart(), ScreenGameplaySyncMachine::RefreshText(), ResetPreferences(), SongManager::SanityCheckGroupDir(), RoomInfoDisplay::SetRoom(), RoomInfoDisplay::SetRoomInfo(), RageDisplay::SetVideoMode(), sm_main(), SongUtil::SortSongPointerArrayBySectionName(), ScreenPackages::Update(), InputList::Update(), ScreenSyncOverlay::UpdateText(), SongUtil::ValidateCurrentEditStepsDescription(), SongUtil::ValidateCurrentSongPreview(), SongUtil::ValidateCurrentStepsChartName(), SongUtil::ValidateCurrentStepsCredit(), and SongUtil::ValidateCurrentStepsMusic().
Load()
void LocalizedString::Load (const RString & sGroup, const RString & sName)
References CreateImpl(), m_sGroup, and m_sName.
Referenced by ScreenRanking::Init(), ScreenGameplay::Init(), and PaneDisplay::Load().
operator const RString &()
LocalizedString::operator const RString & () const inline
References GetValue().
operator=()
LocalizedString& LocalizedString::operator= (const LocalizedString & rhs) private delete
RegisterLocalizer()
void LocalizedString::RegisterLocalizer (MakeLocalizer pFunc) static
References CreateImpl(), FOREACHS, g_pMakeLocalizedStringImpl, and SubscriptionManager< T >::m_pSubscribers.
Referenced by ThemeManager::SwitchThemeAndLanguage().
Member Data Documentation
m_pImpl
ILocalizedStringImpl* LocalizedString::m_pImpl private
Referenced by CreateImpl(), GetValue(), LocalizedString(), and ~LocalizedString().
m_sGroup
RString LocalizedString::m_sGroup private
Referenced by CreateImpl(), Load(), and LocalizedString().
m_sName
RString LocalizedString::m_sName private
Referenced by CreateImpl(), Load(), and LocalizedString().
The documentation for this class was generated from the following files:
LocalizedString.h
LocalizedString.cpp