Etterna: StdString.h File Reference
StdString.h File Reference
#include <algorithm>
#include <functional>
#include <string>
#include <cctype>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>
Classes
class StdString::CStdStr< CT >
Our wrapper for std::string.
class StdString::CStdStr< CT >
Our wrapper for std::string.
struct StdString::StdStringLessNoCase
struct StdString::StdStringEqualsNoCase
Namespaces
StdString
Inline functions on which CStdString relies on.
Macros
#define STDSTRING_H
#define Q172398(x)
#define EMP_TEMP <>
#define CStdString CStdStringA
#define StdStringLessNoCase SSLNCA
#define StdStringEqualsNoCase SSENCA
Typedefs
typedef const char * PCSTR
typedef char * PSTR
typedef std::string::size_type StdString::SS_SIZETYPE
typedef std::string::pointer StdString::SS_PTRTYPE
typedef CStdStr< char > StdString::CStdStringA
Typedef the class names based on the template.
Functions
void MakeUpper (char *p, size_t iLen)
void MakeLower (char *p, size_t iLen)
void MakeUpper (wchar_t *p, size_t iLen)
void MakeLower (wchar_t *p, size_t iLen)
char StdString::sstoupper (char ch)
Turn the character into its uppercase equivalent.
char StdString::sstolower (char ch)
Turn the character into its lowercase equivalent.
void StdString::ssasn (std::string &sDst, const std::string &sSrc)
Assign one string to another.
void StdString::ssasn (std::string &sDst, PCSTR pA)
Assign one string to another.
void StdString::ssadd (std::string &sDst, const std::string &sSrc)
Concatenate one string with another.
void StdString::ssadd (std::string &sDst, PCSTR pA)
Concatenate one string with another.
template<typename CT >
int StdString::ssicmp (const CT *pA1, const CT *pA2)
Perform a case insensitive comparison of the two strings.
void StdString::sslwr (char *pT, size_t nLen)
void StdString::ssupr (char *pT, size_t nLen)
void StdString::sslwr (wchar_t *pT, size_t nLen)
void StdString::ssupr (wchar_t *pT, size_t nLen)
template<typename CT >
CStdStr< CT > StdString::operator+ (const CStdStr< CT > &str1, const CStdStr< CT > &str2)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > StdString::operator+ (const CStdStr< CT > &str, CT t)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > StdString::operator+ (const CStdStr< CT > &str, PCSTR pA)
Another way to concatenate two strings together.
template<typename CT >
CStdStr< CT > StdString::operator+ (PCSTR pA, const CStdStr< CT > &str)
Another way to concatenate two strings together.
Detailed Description
Author
Joseph M. O'Leary (c) 1999
LICENSE
COPYRIGHT: 1999 Joseph M. O'Leary. This code is free. Use it anywhere you want. Rewrite it, restructure it, whatever. Please don't blame me if it makes your $30 billion dollar satellite explode in orbit. If you redistribute it in any form, I'd appreciate it if you would leave this notice here.
If you find any bugs, please let me know:
   jmoleary@earthlink.net
   http://home.earthlink.net/~jmoleary
Macro Definition Documentation
CStdString
#define CStdString CStdStringA
EMP_TEMP
#define EMP_TEMP <>
Q172398
#define Q172398 (x)
Referenced by StdString::CStdStr< CT >::operator=(), and StdString::ssasn().
STDSTRING_H
#define STDSTRING_H
StdStringEqualsNoCase
#define StdStringEqualsNoCase SSENCA
StdStringLessNoCase
#define StdStringLessNoCase SSLNCA
Typedef Documentation
PCSTR
typedef const char* PCSTR
PSTR
typedef char* PSTR
Function Documentation
MakeLower() [1/2]
void MakeLower (char * p, size_t iLen)
Referenced by StdString::sslwr().
MakeLower() [2/2]
void MakeLower (wchar_t * p, size_t iLen)
References L.
MakeUpper() [1/2]
void MakeUpper (char * p, size_t iLen)
Referenced by InputHandler::ApplyKeyModifiers(), Capitalize(), ScreenNetSelectBase::Input(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), and StdString::ssupr().
MakeUpper() [2/2]
void MakeUpper (wchar_t * p, size_t iLen)
References L.