Etterna: RageSoundResampler_Polyphase Class Reference
RageSoundResampler_Polyphase Class Reference
Public Member Functions
RageSoundResampler_Polyphase (int iUpFactor, int iMinDownFactor, int iMaxDownFactor)
~RageSoundResampler_Polyphase ()
void SetDownFactor (int iDownFactor)
int Run (const float *pIn, int iSamplesIn, float *pOut, int iSamplesOut, int iSampleStride) const
void Reset ()
int NumInputsForOutputSamples (int iOut) const
int GetLatency () const
int GetFilled () const
RageSoundResampler_Polyphase (const RageSoundResampler_Polyphase &cpy)
Private Member Functions
float GetCutoffFrequency (int iDownFactor) const
const PolyphaseFilter * GetFilter (int iDownFactor) const
Private Attributes
const PolyphaseFilter * m_pPolyphase
PolyphaseFilter::State * m_pState
int m_iUpFactor
int m_iDownFactor
Constructor & Destructor Documentation
RageSoundResampler_Polyphase() [1/2]
RageSoundResampler_Polyphase::RageSoundResampler_Polyphase (int iUpFactor, int iMinDownFactor, int iMaxDownFactor) inline
References GetCutoffFrequency(), m_iUpFactor, m_pPolyphase, m_pState, PolyphaseFilterCache::MakePolyphaseFilter(), max(), SetDownFactor(), and PolyphaseFilter::State.
~RageSoundResampler_Polyphase()
RageSoundResampler_Polyphase::~RageSoundResampler_Polyphase () inline
References m_pState.
RageSoundResampler_Polyphase() [2/2]
RageSoundResampler_Polyphase::RageSoundResampler_Polyphase (const RageSoundResampler_Polyphase & cpy) inline
References m_iDownFactor, m_iUpFactor, m_pPolyphase, m_pState, and PolyphaseFilter::State.
Member Function Documentation
GetCutoffFrequency()
float RageSoundResampler_Polyphase::GetCutoffFrequency (int iDownFactor) const inline private
References f, m_iUpFactor, and min().
Referenced by GetFilter(), and RageSoundResampler_Polyphase().
GetFilled()
int RageSoundResampler_Polyphase::GetFilled () const inline
References PolyphaseFilter::State::m_iFilled, and m_pState.
GetFilter()
const PolyphaseFilter* RageSoundResampler_Polyphase::GetFilter (int iDownFactor) const inline private
References PolyphaseFilterCache::FindNearestPolyphaseFilter(), GetCutoffFrequency(), and m_iUpFactor.
Referenced by SetDownFactor().
GetLatency()
int RageSoundResampler_Polyphase::GetLatency () const inline
References PolyphaseFilter::GetLatency(), and m_pPolyphase.
NumInputsForOutputSamples()
int RageSoundResampler_Polyphase::NumInputsForOutputSamples (int iOut) const inline
References m_iDownFactor, m_pPolyphase, m_pState, and PolyphaseFilter::NumInputsForOutputSamples().
Reset()
void RageSoundResampler_Polyphase::Reset () inline
References m_iUpFactor, m_pState, and PolyphaseFilter::State.
Run()
int RageSoundResampler_Polyphase::Run (const float * pIn, int iSamplesIn, float * pOut, int iSamplesOut, int iSampleStride) const inline
References m_iDownFactor, m_pPolyphase, m_pState, and PolyphaseFilter::RunPolyphaseFilter().
SetDownFactor()
void RageSoundResampler_Polyphase::SetDownFactor (int iDownFactor) inline
References GetFilter(), m_iDownFactor, and m_pPolyphase.
Referenced by RageSoundResampler_Polyphase().
Member Data Documentation
m_iDownFactor
int RageSoundResampler_Polyphase::m_iDownFactor private
Referenced by NumInputsForOutputSamples(), RageSoundResampler_Polyphase(), Run(), and SetDownFactor().
m_iUpFactor
int RageSoundResampler_Polyphase::m_iUpFactor private
Referenced by GetCutoffFrequency(), GetFilter(), RageSoundResampler_Polyphase(), and Reset().
m_pPolyphase
const PolyphaseFilter* RageSoundResampler_Polyphase::m_pPolyphase private
Referenced by GetLatency(), NumInputsForOutputSamples(), RageSoundResampler_Polyphase(), Run(), and SetDownFactor().
m_pState
PolyphaseFilter::State* RageSoundResampler_Polyphase::m_pState private
Referenced by GetFilled(), NumInputsForOutputSamples(), RageSoundResampler_Polyphase(), Reset(), Run(), and ~RageSoundResampler_Polyphase().
The documentation for this class was generated from the following file:
RageSoundReader_Resample_Good.cpp