Etterna: ScreenDebugOverlay.h File Reference
ScreenDebugOverlay.h File Reference
#include "BitmapText.h"
#include "Quad.h"
#include "Screen.h"
Classes
class ScreenDebugOverlay
Functions
void ChangeVolume (float fDelta)
void ChangeVisualDelay (float fDelta)
Function Documentation
ChangeVisualDelay()
void ChangeVisualDelay (float fDelta)
References CLAMP(), f, Preference< T >::Get(), Preference< T >::GetPreferenceByName(), and Preference< T >::Set().
Referenced by DebugLineVisualDelayUp::DoAndLog(), and DebugLineVisualDelayDown::DoAndLog().
ChangeVolume()
void ChangeVolume (float fDelta)
References CLAMP(), f, Preference< T >::Get(), Preference< T >::GetPreferenceByName(), Preference< T >::Set(), RageSoundManager::SetMixVolume(), and SOUNDMAN.
Referenced by DebugLineVolumeUp::DoAndLog(), and DebugLineVolumeDown::DoAndLog().