Etterna: RageDisplay_OGL.cpp File Reference
RageDisplay_OGL.cpp File Reference
#include "global.h"
#include "RageDisplay_OGL.h"
#include "RageDisplay_OGL_Helpers.h"
#include "EnumHelper.h"
#include "Foreach.h"
#include "LocalizedString.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageMath.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageTextureManager.h"
#include "RageTypes.h"
#include "RageUtil.h"
#include "arch/LowLevelWindow/LowLevelWindow.h"
#include <chrono>
#include <set>
Classes
struct GLPixFmtInfo_t
class RageCompiledGeometrySWOGL
class InvalidateObject
class RageCompiledGeometryHWOGL
struct RageTextureLock_OGL
class RenderTarget_FramebufferObject
Macros
#define GL_CHECK_ERROR(f)
#define BUFFER_OFFSET(o) ((char*)(o))
Functions
static void InvalidateObjects ()
static void FixLittleEndian ()
static void TurnOffHardwareVBO ()
RString GetInfoLog (GLhandleARB h)
GLhandleARB CompileShader (GLenum ShaderType, RString sFile, vector< RString > asDefines)
GLhandleARB LoadShader (GLenum ShaderType, RString sFile, vector< RString > asDefines)
void InitShaders ()
static void CheckPalettedTextures ()
static void CheckReversePackedPixels ()
void SetupExtensions ()
static void SetupVertices (const RageSpriteVertex v[], int iNumVerts)
static bool SetTextureUnit (TextureUnit tu)
void SetPixelMapForSurface (int glImageFormat, int glTexFormat, const RageSurfacePalette *palette)
Variables
static bool g_bReversePackedPixelsWorks = true
static bool g_bColorIndexTableWorks = true
static float g_line_range [2]
static float g_point_range [2]
static int g_glVersion
static int g_gluVersion
static int g_iMaxTextureUnits = 0
static GLhandleARB g_bTextureMatrixShader = 0
static map< unsigned, RenderTarget * > g_mapRenderTargets
static RenderTarget * g_pCurrentRenderTarget = NULL
static LowLevelWindow * g_pWind
static bool g_bInvertY = false
static RageDisplay::RagePixelFormatDesc PIXEL_FORMAT_DESC [NUM_RagePixelFormat]
struct GLPixFmtInfo_t g_GLPixFmtInfo [NUM_RagePixelFormat]
static int g_iAttribTextureMatrixScale
static GLhandleARB g_bUnpremultiplyShader = 0
static GLhandleARB g_bColorBurnShader = 0
static GLhandleARB g_bColorDodgeShader = 0
static GLhandleARB g_bVividLightShader = 0
static GLhandleARB g_hHardMixShader = 0
static GLhandleARB g_hOverlayShader = 0
static GLhandleARB g_hScreenShader = 0
static GLhandleARB g_hYUYV422Shader = 0
static GLhandleARB g_gShellShader = 0
static GLhandleARB g_gCelShader = 0
static LocalizedString OBTAIN_AN_UPDATED_VIDEO_DRIVER ("RageDisplay_Legacy", "Obtain an updated driver from your video card manufacturer.")
static LocalizedString GLDIRECT_IS_NOT_COMPATIBLE ("RageDisplay_Legacy", "GLDirect was detected. " "GLDirect is not compatible " "with this game and should " "be disabled.")
static set< InvalidateObject * > g_InvalidateList
GLint iCelTexture1
GLint iCelTexture2 = 0
Macro Definition Documentation
BUFFER_OFFSET
#define BUFFER_OFFSET (o) ((char*)(o))
Referenced by RageCompiledGeometryHWOGL::Draw(), and RageTextureLock_OGL::Unlock().
GL_CHECK_ERROR
#define GL_CHECK_ERROR (f)
Value:
{                                                                          \
        GLenum glError = glGetError();                                         \
        if (glError != GL_NO_ERROR) {                                          \
            sError = ssprintf(f " failed (%s)", GLToString(glError).c_str());  \
            break;                                                             \
        }                                                                      \
    }
Referenced by CheckPalettedTextures().
Function Documentation
CheckPalettedTextures()
static void CheckPalettedTextures () static
References FlushGLErrors, GLPixFmtInfo_t::format, g_GLPixFmtInfo, GL_CHECK_ERROR, GL_TEXTURE_INDEX_SIZE_EXT, RageDisplay_Legacy_Helpers::GLToString(), RageLog::Info(), GLPixFmtInfo_t::internalfmt, LOG, RagePixelFormat_PAL, ssprintf(), and GLPixFmtInfo_t::type.
Referenced by SetupExtensions().
CheckReversePackedPixels()
static void CheckReversePackedPixels () static
References FlushGLErrors, g_bReversePackedPixelsWorks, RageDisplay_Legacy_Helpers::GLToString(), RageLog::Info(), and LOG.
Referenced by SetupExtensions().
CompileShader()
GLhandleARB CompileShader (GLenum ShaderType, RString sFile, vector< RString > asDefines)
References FOREACH, RageFile::GetError(), RageFile::GetFileSize(), GetInfoLog(), LOG, RageFile::Open(), RageFile::Read(), ssprintf(), RageLog::Trace(), and RageLog::Warn().
Referenced by LoadShader().
FixLittleEndian()
static void FixLittleEndian () static
References RageDisplay::RagePixelFormatDesc::bpp, FAIL_M, g_GLPixFmtInfo, RageDisplay::RagePixelFormatDesc::masks, NUM_RagePixelFormat, ssprintf(), Swap24(), and Swap32().
Referenced by RageDisplay_GLES2::RageDisplay_GLES2(), and RageDisplay_Legacy::RageDisplay_Legacy().
GetInfoLog()
RString GetInfoLog (GLhandleARB h)
References TrimRight().
Referenced by CompileShader(), and LoadShader().
InitShaders()
void InitShaders ()
References ASSERT_M, AssertNoGLError, FlushGLErrors, g_bColorBurnShader, g_bColorDodgeShader, g_bTextureMatrixShader, g_bUnpremultiplyShader, g_bVividLightShader, g_gCelShader, g_gShellShader, g_hHardMixShader, g_hOverlayShader, g_hScreenShader, g_hYUYV422Shader, g_iAttribTextureMatrixScale, RageDisplay_Legacy_Helpers::GLToString(), LoadShader(), LOG, and RageLog::Trace().
Referenced by RageDisplay_Legacy::TryVideoMode().
InvalidateObjects()
static void InvalidateObjects () static
References FOREACHS, and g_InvalidateList.
Referenced by RageDisplay_Legacy::TryVideoMode().
LoadShader()
GLhandleARB LoadShader (GLenum ShaderType, RString sFile, vector< RString > asDefines)
References CompileShader(), GetInfoLog(), LOG, and RageLog::Warn().
Referenced by InitShaders().
SetPixelMapForSurface()
void SetPixelMapForSurface (int glImageFormat, int glTexFormat, const RageSurfacePalette * palette)
References RageSurfaceColor::a, RageSurfaceColor::b, RageSurfacePalette::colors, DebugAssertNoGLError, DebugFlushGLErrors, RageSurfaceColor::g, RageSurfacePalette::ncolors, RageSurfaceColor::r, and SCALE.
Referenced by RageDisplay_Legacy::CreateTexture(), and RageDisplay_Legacy::UpdateTexture().
SetTextureUnit()
static bool SetTextureUnit (TextureUnit tu) static
References enum_add2(), g_iMaxTextureUnits, and TextureUnit_1.
Referenced by RageDisplay_Legacy::CreateTexture(), RageDisplay_Legacy::SetSphereEnvironmentMapping(), RageDisplay_Legacy::SetTexture(), RageDisplay_Legacy::SetTextureMode(), and RageDisplay_Legacy::SetTextureWrapping().
SetupExtensions()
void SetupExtensions ()
References CheckPalettedTextures(), CheckReversePackedPixels(), g_bColorIndexTableWorks, g_gluVersion, g_glVersion, g_iMaxTextureUnits, RageLog::Info(), LOG, and StringToFloat().
Referenced by RageDisplay_Legacy::TryVideoMode().
SetupVertices()
static void SetupVertices (const RageSpriteVertex v[], int iNumVerts) static
References RageVColor::a, RageVColor::b, RageSpriteVertex::c, RageVColor::g, RageSpriteVertex::n, RageSpriteVertex::p, RageVColor::r, and RageSpriteVertex::t.
Referenced by RageDisplay_Legacy::DrawFanInternal(), RageDisplay_Legacy::DrawLineStripInternal(), RageDisplay_Legacy::DrawQuadsInternal(), RageDisplay_Legacy::DrawQuadStripInternal(), RageDisplay_Legacy::DrawStripInternal(), RageDisplay_Legacy::DrawSymmetricQuadStripInternal(), and RageDisplay_Legacy::DrawTrianglesInternal().
TurnOffHardwareVBO()
static void TurnOffHardwareVBO () static
Referenced by RageCompiledGeometrySWOGL::Draw(), RageDisplay_Legacy::DrawCompiledGeometryInternal(), RageDisplay_Legacy::DrawFanInternal(), RageDisplay_Legacy::DrawQuadsInternal(), RageDisplay_Legacy::DrawQuadStripInternal(), RageDisplay_Legacy::DrawStripInternal(), RageDisplay_Legacy::DrawSymmetricQuadStripInternal(), and RageDisplay_Legacy::DrawTrianglesInternal().
Variable Documentation
g_bColorBurnShader
GLhandleARB g_bColorBurnShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_bColorDodgeShader
GLhandleARB g_bColorDodgeShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_bColorIndexTableWorks
bool g_bColorIndexTableWorks = true static
Referenced by RageDisplay_Legacy::GetImgPixelFormat(), and SetupExtensions().
g_bInvertY
bool g_bInvertY = false static
Referenced by RageDisplay_Legacy::SendCurrentMatrices(), and RageDisplay_Legacy::SetRenderTarget().
g_bReversePackedPixelsWorks
bool g_bReversePackedPixelsWorks = true static
Referenced by CheckReversePackedPixels(), and RageDisplay_Legacy::SupportsSurfaceFormat().
g_bTextureMatrixShader
GLhandleARB g_bTextureMatrixShader = 0 static
Referenced by RageCompiledGeometryHWOGL::Draw(), InitShaders(), RageDisplay_Legacy::RageDisplay_Legacy(), and RageDisplay_Legacy::SupportsPerVertexMatrixScale().
g_bUnpremultiplyShader
GLhandleARB g_bUnpremultiplyShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_bVividLightShader
GLhandleARB g_bVividLightShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_gCelShader
GLhandleARB g_gCelShader = 0 static
Referenced by InitShaders(), and RageDisplay_Legacy::SetCelShaded().
g_GLPixFmtInfo
struct GLPixFmtInfo_t g_GLPixFmtInfo[NUM_RagePixelFormat]
Referenced by CheckPalettedTextures(), RageDisplay_Legacy::CreateTexture(), FixLittleEndian(), RageDisplay_Legacy::GetTexture(), RageDisplay_GLES2::SupportsSurfaceFormat(), RageDisplay_Legacy::SupportsSurfaceFormat(), RageDisplay_GLES2::SupportsTextureFormat(), RageDisplay_Legacy::SupportsTextureFormat(), and RageDisplay_Legacy::UpdateTexture().
g_gluVersion
int g_gluVersion static
Referenced by RageDisplay_Legacy::CreateTexture(), and SetupExtensions().
g_glVersion
int g_glVersion static
Referenced by SetupExtensions().
g_gShellShader
GLhandleARB g_gShellShader = 0 static
Referenced by InitShaders(), and RageDisplay_Legacy::SetCelShaded().
g_hHardMixShader
GLhandleARB g_hHardMixShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_hOverlayShader
GLhandleARB g_hOverlayShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_hScreenShader
GLhandleARB g_hScreenShader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_hYUYV422Shader
GLhandleARB g_hYUYV422Shader = 0 static
Referenced by InitShaders(), RageDisplay_Legacy::IsEffectModeSupported(), and RageDisplay_Legacy::SetEffectMode().
g_iAttribTextureMatrixScale
int g_iAttribTextureMatrixScale static
Referenced by RageCompiledGeometryHWOGL::Draw(), and InitShaders().
g_iMaxTextureUnits
int g_iMaxTextureUnits = 0 static
Referenced by RageDisplay_Legacy::GetNumTextureUnits(), RageDisplay_Legacy::Init(), SetTextureUnit(), and SetupExtensions().
g_InvalidateList
set<InvalidateObject*> g_InvalidateList static
Referenced by InvalidateObject::InvalidateObject(), InvalidateObjects(), and InvalidateObject::~InvalidateObject().
g_line_range
float g_line_range[2] static
Referenced by RageDisplay_Legacy::DrawLineStripInternal(), and RageDisplay_Legacy::Init().
g_mapRenderTargets
map<unsigned, RenderTarget*> g_mapRenderTargets static
Referenced by RageDisplay_Legacy::CreateRenderTarget(), RageDisplay_Legacy::DeleteTexture(), RageDisplay_Legacy::GetRenderTarget(), RageDisplay_Legacy::SetRenderTarget(), and RageDisplay_Legacy::TryVideoMode().
g_pCurrentRenderTarget
RenderTarget* g_pCurrentRenderTarget = NULL static
g_point_range
float g_point_range[2] static
Referenced by RageDisplay_Legacy::DrawLineStripInternal(), and RageDisplay_Legacy::Init().
g_pWind
LowLevelWindow* g_pWind static
Referenced by RageDisplay_GLES2::~RageDisplay_GLES2(), and RageDisplay_Legacy::~RageDisplay_Legacy().
GLDIRECT_IS_NOT_COMPATIBLE
LocalizedString GLDIRECT_IS_NOT_COMPATIBLE("RageDisplay_Legacy", "GLDirect was detected. " "GLDirect is not compatible " "with this game and should " "be disabled.") static
Referenced by RageDisplay_Legacy::Init().
iCelTexture1
GLint iCelTexture1
iCelTexture2
GLint iCelTexture2 = 0
OBTAIN_AN_UPDATED_VIDEO_DRIVER
LocalizedString OBTAIN_AN_UPDATED_VIDEO_DRIVER("RageDisplay_Legacy", "Obtain an updated driver from your video card manufacturer.") static
Referenced by RageDisplay_Legacy::Init().
PIXEL_FORMAT_DESC
RageDisplay::RagePixelFormatDesc PIXEL_FORMAT_DESC[NUM_RagePixelFormat] static