Etterna: RageFileDriverDirect.cpp File Reference
RageFileDriverDirect.cpp File Reference
#include "global.h"
#include "RageFileDriverDirect.h"
#include "RageFile.h"
#include "RageFileDriverDirectHelpers.h"
#include "RageUtil.h"
#include "RageUtil_FileDB.h"
#include <cerrno>
Classes
struct FileDriverEntry_DIR
struct FileDriverEntry_DIRRO
Functions
static RString MakeTempFilename (const RString &sPath)
static RageFileObjDirect * MakeFileObjDirect (RString sPath, int iMode, int &iError)
static int RetriedWrite (int iFD, const void *pBuf, size_t iCount)
Variables
FileDriverEntry_DIR g_RegisterDriver
FileDriverEntry_DIRRO g_RegisterDriver2
static const unsigned int BUFSIZE = 1024 * 64
Function Documentation
MakeFileObjDirect()
static RageFileObjDirect* MakeFileObjDirect (RString sPath, int iMode, int & iError) static
References MakeTempFilename(), O_BINARY, RageFile::READ, and RageFile::STREAMED.
Referenced by RageFileObjDirect::Copy(), and RageFileDriverDirect::Open().
MakeTempFilename()
static RString MakeTempFilename (const RString & sPath) static
References Basename(), and Dirname().
Referenced by MakeFileObjDirect(), and RageFileObjDirect::~RageFileObjDirect().
RetriedWrite()
static int RetriedWrite (int iFD, const void * pBuf, size_t iCount) static
Referenced by RageFileObjDirect::WriteInternal().
Variable Documentation
BUFSIZE
const unsigned int BUFSIZE = 1024 * 64 static
Referenced by RageFileObjDirect::RageFileObjDirect().
g_RegisterDriver
FileDriverEntry_DIR g_RegisterDriver static
g_RegisterDriver2
FileDriverEntry_DIRRO g_RegisterDriver2 static