Etterna: ScoreManager Class Reference
ScoreManager Class Reference
#include <ScoreManager.h>
Public Member Functions
ScoreManager ()
~ScoreManager ()
vector< vector< HighScore * > > GetAllPBPtrs (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
HighScore * GetChartPBAt (const string &ck, float &rate, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
HighScore * GetChartPBUpTo (const string &ck, float &rate, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
Grade GetBestGradeFor (const string &ck, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
int AddScore (const HighScore &hs_, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void ImportScore (const HighScore &hs_, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void SortTopSSRPtrs (Skillset ss, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void RecalculateSSRs (LoadingWindow *ld, const string &profileID)
void EnableAllScores ()
void CalcPlayerRating (float &prating, float *pskillsets, const string &profileID)
float AggregateSSRs (Skillset ss, float rating, float res, int iter) const
float GetTopSSRValue (unsigned int rank, int ss)
HighScore * GetTopSSRHighScore (unsigned int rank, int ss)
bool KeyHasScores (const string &ck, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
bool HasAnyScores ()
void RatingOverTime ()
XNode * CreateNode (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID) const
void LoadFromNode (const XNode *node, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
ScoresForChart * GetScoresForChart (const string &ck, const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
vector< string > GetSortedKeys ()
void PushSelf (lua_State *L)
HighScore * GetMostRecentScore ()
void PutScoreAtTheTop (string scorekey)
const vector< HighScore * > & GetAllScores ()
const vector< HighScore * > & GetAllProfileScores (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void RegisterScore (HighScore *hs)
void AddToKeyedIndex (HighScore *hs)
void RegisterScoreInProfile (HighScore *hs_, const string &profileID)
void SetAllTopScores (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void PurgeScores ()
unordered_map< string, ScoresForChart > * GetProfileScores (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
void PurgeProfileScores (const string &profileID=PROFILEMAN->GetProfile(PLAYER_1) ->m_sProfileID)
Public Attributes
float minpercent = PREFSMAN->m_fMinPercentToSaveScores
Private Attributes
unordered_map< string, unordered_map< string, ScoresForChart > > pscores
vector< HighScore * > TopSSRs
vector< HighScore * > AllScores
unordered_map< string, vector< HighScore * > > AllProfileScores
unordered_map< string, HighScore * > ScoresByKey
Constructor & Destructor Documentation
ScoreManager()
ScoreManager::ScoreManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~ScoreManager()
ScoreManager::~ScoreManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
AddScore()
int ScoreManager::AddScore (const HighScore & hs_, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) inline
References HighScore::GetChartKey(), HighScore::GetTopScore(), pscores, and RegisterScoreInProfile().
Referenced by StageStats::FinalizeScores().
AddToKeyedIndex()
void ScoreManager::AddToKeyedIndex (HighScore * hs) inline
References HighScore::GetScoreKey(), and ScoresByKey.
Referenced by ScoresAtRate::AddScore(), ScoresAtRate::LoadFromNode(), and DBProfile::LoadPlayerScores().
AggregateSSRs()
float ScoreManager::AggregateSSRs (Skillset ss, float rating, float res, int iter) const
References f, GetCalcVersion(), max(), and TopSSRs.
Referenced by CalcPlayerRating().
CalcPlayerRating()
void ScoreManager::CalcPlayerRating (float & prating, float * pskillsets, const string & profileID)
References AggregateSSRs(), CLAMP(), f, FOREACH_ENUM, SetAllTopScores(), Skill_Overall, and SortTopSSRPtrs().
Referenced by AddPlayerStatsToProfile(), and Profile::CalculateStatsFromScores().
CreateNode()
XNode * ScoreManager::CreateNode (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) const
References XNode::AppendChild(), picosha2::detail::ch(), FOREACHUM_CONST, and pscores.
Referenced by XMLProfile::SaveEttScoresCreateNode().
EnableAllScores()
void ScoreManager::EnableAllScores ()
References AllScores.
Referenced by LunaScoreManager::ValidateAllScores().
GetAllPBPtrs()
vector< vector< HighScore * > > ScoreManager::GetAllPBPtrs (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References FOREACHUM, SongManager::IsChartLoaded(), pscores, and SONGMAN.
Referenced by DownloadManager::UploadScores().
GetAllProfileScores()
const vector<HighScore*>& ScoreManager::GetAllProfileScores (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) inline
References AllProfileScores.
Referenced by Profile::CalculateStatsFromScores().
GetAllScores()
const vector<HighScore*>& ScoreManager::GetAllScores () inline
References AllScores.
GetBestGradeFor()
Grade ScoreManager::GetBestGradeFor (const string & ck, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) inline
References Grade_Invalid, KeyHasScores(), and pscores.
Referenced by Profile::GetBestGrade(), and MusicWheelItem::RefreshGrades().
GetChartPBAt()
HighScore * ScoreManager::GetChartPBAt (const string & ck, float & rate, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References KeyHasScores(), and pscores.
Referenced by ScoreGoal::CheckVacuity(), and Player::Load().
GetChartPBUpTo()
HighScore * ScoreManager::GetChartPBUpTo (const string & ck, float & rate, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References KeyHasScores(), and pscores.
Referenced by ScoreGoal::GetPBUpTo().
GetMostRecentScore()
HighScore* ScoreManager::GetMostRecentScore () inline
References AllScores.
Referenced by LunaScoreManager::GetMostRecentScore(), and LunaScreenSelectMusic::ShowEvalScreenForScore().
GetProfileScores()
unordered_map<string, ScoresForChart>* ScoreManager::GetProfileScores (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) inline
References pscores.
Referenced by DBProfile::LoadPlayerScores(), and DBProfile::SavePlayerScores().
GetScoresForChart()
ScoresForChart * ScoreManager::GetScoresForChart (const string & ck, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References pscores.
Referenced by LunaScoreManager::GetScoresByKey().
GetSortedKeys()
vector<string> ScoreManager::GetSortedKeys ()
GetTopSSRHighScore()
HighScore * ScoreManager::GetTopSSRHighScore (unsigned int rank, int ss)
References NUM_Skillset, and TopSSRs.
Referenced by LunaScoreManager::GetTopSSRHighScore().
GetTopSSRValue()
float ScoreManager::GetTopSSRValue (unsigned int rank, int ss)
HasAnyScores()
bool ScoreManager::HasAnyScores () inline
References AllScores.
ImportScore()
void ScoreManager::ImportScore (const HighScore & hs_, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References HighScore::GetChartKey(), pscores, and RegisterScoreInProfile().
Referenced by Profile::ImportScoresToEtterna().
KeyHasScores()
bool ScoreManager::KeyHasScores (const string & ck, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID) inline
References pscores.
Referenced by GetBestGradeFor(), GetChartPBAt(), and GetChartPBUpTo().
LoadFromNode()
void ScoreManager::LoadFromNode (const XNode * node, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References FOREACH_CONST_Child, pscores, SongManager::ReconcileBustedKeys(), and SONGMAN.
Referenced by XMLProfile::LoadEttScoresFromNode().
PurgeProfileScores()
void ScoreManager::PurgeProfileScores (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References AllProfileScores, AllScores, pscores, ScoresByKey, and TopSSRs.
PurgeScores()
void ScoreManager::PurgeScores ()
References AllScores, pscores, ScoresByKey, and TopSSRs.
PushSelf()
void ScoreManager::PushSelf (lua_State * L)
Referenced by ScoreManager().
PutScoreAtTheTop()
void ScoreManager::PutScoreAtTheTop (string scorekey) inline
References AllScores, ScoresByKey, and swap().
Referenced by StageStats::FinalizeScores(), and LunaScreenSelectMusic::ShowEvalScreenForScore().
RatingOverTime()
void ScoreManager::RatingOverTime ()
References AllScores.
RecalculateSSRs()
void ScoreManager::RecalculateSSRs (LoadingWindow * ld, const string & profileID)
References ThreadData::_progress, active, AllProfileScores, TimingData::BuildAndGetEtaner(), Steps::Compress(), ThreadData::data, FOREACH_ENUM, GetCalcVersion(), NoteData::GetNonEmptyRowVector(), Steps::GetNoteData(), Steps::GetRadarValues(), SongManager::GetStepsByChartkey(), Steps::GetTimingData(), Grade_Failed, TimingData::HasWarps(), Steps::IsRecalcValid(), NoteData::LogNonEmptyRows(), max(), MinaSDCalc(), RadarCategory_Notes, NoteData::SerializeNoteData(), LoadingWindow::SetIndeterminate(), LoadingWindow::SetProgress(), LoadingWindow::SetText(), LoadingWindow::SetTotalWork(), ThreadData::setUpdated(), SONGMAN, TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, RageTimer::Touch(), TimingData::UnsetEtaner(), NoteData::UnsetNerv(), and NoteData::UnsetSerializedNoteData().
Referenced by Profile::CalculateStatsFromScores().
RegisterScore()
void ScoreManager::RegisterScore (HighScore * hs) inline
References AllScores.
Referenced by ScoresAtRate::AddScore(), ScoresAtRate::LoadFromNode(), and DBProfile::LoadPlayerScores().
RegisterScoreInProfile()
void ScoreManager::RegisterScoreInProfile (HighScore * hs_, const string & profileID)
References AllProfileScores.
Referenced by AddScore(), ImportScore(), and ScoresAtRate::LoadFromNode().
SetAllTopScores()
void ScoreManager::SetAllTopScores (const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References FOREACHUM, SongManager::IsChartLoaded(), pscores, and SONGMAN.
Referenced by CalcPlayerRating(), and XMLProfile::SaveEttScoresCreateNode().
SortTopSSRPtrs()
void ScoreManager::SortTopSSRPtrs (Skillset ss, const string & profileID = PROFILEMAN->GetProfile(PLAYER_1)->m_sProfileID)
References FOREACH, FOREACHUM, HighScore::GetSkillsetSSR(), SongManager::IsChartLoaded(), pscores, SONGMAN, and TopSSRs.
Referenced by CalcPlayerRating(), and LunaScoreManager::SortSSRs().
Member Data Documentation
AllProfileScores
unordered_map<string, vector<HighScore*> > ScoreManager::AllProfileScores private
Referenced by GetAllProfileScores(), PurgeProfileScores(), RecalculateSSRs(), and RegisterScoreInProfile().
AllScores
vector<HighScore*> ScoreManager::AllScores private
Referenced by EnableAllScores(), GetAllScores(), GetMostRecentScore(), HasAnyScores(), PurgeProfileScores(), PurgeScores(), PutScoreAtTheTop(), RatingOverTime(), and RegisterScore().
minpercent
float ScoreManager::minpercent = PREFSMAN->m_fMinPercentToSaveScores
Referenced by ScoresAtRate::CreateNode(), and DBProfile::SavePlayerScores().
pscores
unordered_map<string, unordered_map<string, ScoresForChart> > ScoreManager::pscores private
Referenced by AddScore(), CreateNode(), GetAllPBPtrs(), GetBestGradeFor(), GetChartPBAt(), GetChartPBUpTo(), GetProfileScores(), GetScoresForChart(), ImportScore(), KeyHasScores(), LoadFromNode(), PurgeProfileScores(), PurgeScores(), SetAllTopScores(), and SortTopSSRPtrs().
ScoresByKey
unordered_map<string, HighScore*> ScoreManager::ScoresByKey private
Referenced by AddToKeyedIndex(), PurgeProfileScores(), PurgeScores(), and PutScoreAtTheTop().
TopSSRs
vector<HighScore*> ScoreManager::TopSSRs private
Referenced by AggregateSSRs(), GetTopSSRHighScore(), PurgeProfileScores(), PurgeScores(), and SortTopSSRPtrs().
The documentation for this class was generated from the following files:
ScoreManager.h
ScoreManager.cpp