Etterna: PlayerAI Class Reference
PlayerAI Class Reference
#include <PlayerAI.h>
Static Public Member Functions
static void InitFromDisk ()
static TapNoteScore GetTapNoteScore (const PlayerState *pPlayerState)
static void SetScoreData (HighScore *pHighScore)
static float GetTapNoteOffsetForReplay (TapNote *pTN, int noteRow, int col)
static TapNoteScore GetTapNoteScoreForReplay (const PlayerState *pPlayerState, float fNoteOffset)
static bool DetermineIfHoldDropped (int noteRow, int col)
Static Public Attributes
static HighScore * pScoreData = nullptr
static map< int, vector< TapReplayResult > > m_ReplayTapMap
static map< int, vector< HoldReplayResult > > m_ReplayHoldMap
Member Function Documentation
DetermineIfHoldDropped()
bool PlayerAI::DetermineIfHoldDropped (int noteRow, int col) static
References m_ReplayHoldMap.
Referenced by Player::UpdateHoldNotes().
GetTapNoteOffsetForReplay()
float PlayerAI::GetTapNoteOffsetForReplay (TapNote * pTN, int noteRow, int col) static
References HighScore::GetReplayType(), m_ReplayTapMap, pScoreData, TapNoteType_Lift, TapNoteType_Mine, and TapNote::type.
Referenced by Player::Step().
GetTapNoteScore()
TapNoteScore PlayerAI::GetTapNoteScore (const PlayerState * pPlayerState) static
References TapScoreDistribution::GetTapNoteScore(), PlayerState::m_iCpuSkill, PlayerState::m_PlayerController, PC_AUTOPLAY, PC_REPLAY, TNS_Miss, and TNS_W1.
Referenced by Player::Step().
GetTapNoteScoreForReplay()
TapNoteScore PlayerAI::GetTapNoteScoreForReplay (const PlayerState * pPlayerState, float fNoteOffset) static
References f, Player::GetWindowSeconds(), max(), TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, TNS_W5, TW_W1, TW_W2, TW_W3, TW_W4, and TW_W5.
Referenced by Player::Step().
InitFromDisk()
void PlayerAI::InitFromDisk () static
References AI_PATH, TapScoreDistribution::ChangeWeightsToPercents(), TapScoreDistribution::fPercent, XNode::GetAttrValue(), XNode::GetChild(), NUM_SKILL_LEVELS, IniFile::ReadFile(), LuaHelpers::ReportScriptErrorFmt(), SET_MALF_IF, TapScoreDistribution::SetDefaultWeights(), ssprintf(), TNS_Miss, TNS_None, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
Referenced by Player::Player().
SetScoreData()
void PlayerAI::SetScoreData (HighScore * pHighScore) static
References HighScore::GetCopyOfHoldReplayDataVector(), HighScore::GetCopyOfNoteRowVector(), HighScore::GetCopyOfOffsetVector(), HighScore::GetCopyOfTapNoteTypeVector(), HighScore::GetCopyOfTrackVector(), HighScore::GetReplayType(), HighScore::LoadReplayData(), m_ReplayHoldMap, m_ReplayTapMap, TapReplayResult::offset, pScoreData, TapReplayResult::row, TapNoteType_Empty, TapReplayResult::track, and TapReplayResult::type.
Referenced by LunaScreenSelectMusic::PlayReplay(), and ScreenGameplay::ToggleReplayPause().
Member Data Documentation
m_ReplayHoldMap
map< int, vector< HoldReplayResult > > PlayerAI::m_ReplayHoldMap static
Referenced by DetermineIfHoldDropped(), and SetScoreData().
m_ReplayTapMap
map< int, vector< TapReplayResult > > PlayerAI::m_ReplayTapMap static
Referenced by GetTapNoteOffsetForReplay(), and SetScoreData().
pScoreData
HighScore * PlayerAI::pScoreData = nullptr static
Referenced by StageStats::FinalizeScores(), GetTapNoteOffsetForReplay(), SetScoreData(), and ScreenGameplay::ToggleReplayPause().
The documentation for this class was generated from the following files:
PlayerAI.h
PlayerAI.cpp