Etterna: RageSoundReader_Vorbisfile.cpp File Reference
RageSoundReader_Vorbisfile.cpp File Reference
#include "global.h"
#include "RageSoundReader_Vorbisfile.h"
#include "RageLog.h"
#include "RageUtil.h"
#include <vorbis/vorbisfile.h>
#include "RageFile.h"
Functions
static size_t OggRageFile_read_func (void *ptr, size_t size, size_t nmemb, void *datasource)
static int OggRageFile_seek_func (void *datasource, ogg_int64_t offset, int whence)
static int OggRageFile_close_func (void *datasource)
static long OggRageFile_tell_func (void *datasource)
static RString ov_ssprintf (int err, const char *fmt,...)
Function Documentation
OggRageFile_close_func()
static int OggRageFile_close_func (void * datasource) static
Referenced by RageSoundReader_Vorbisfile::Open().
OggRageFile_read_func()
static size_t OggRageFile_read_func (void * ptr, size_t size, size_t nmemb, void * datasource) static
References f.
Referenced by RageSoundReader_Vorbisfile::Open().
OggRageFile_seek_func()
static int OggRageFile_seek_func (void * datasource, ogg_int64_t offset, int whence) static
References f.
Referenced by RageSoundReader_Vorbisfile::Open().
OggRageFile_tell_func()
static long OggRageFile_tell_func (void * datasource) static
References f.
Referenced by RageSoundReader_Vorbisfile::Open().
ov_ssprintf()
static RString ov_ssprintf (int err, const char * fmt, ...) static
References ssprintf(), and vssprintf().
Referenced by RageSoundReader_Vorbisfile::Open(), and RageSoundReader_Vorbisfile::SetPosition().