Etterna: OptionRowHandlerLua Class Reference
OptionRowHandlerLua Class Reference
Public Member Functions
OptionRowHandlerLua ()
~OptionRowHandlerLua () override
void Init () override
bool SanityCheckTable (lua_State *L, RString &RowName)
void SetEnabledForPlayers ()
bool LoadInternal (const Commands &cmds) override
ReloadChanged Reload () override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
bool NotifyOfSelection (PlayerNumber pn, int choice) override
bool GoToFirstOnStart () override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual int GetDefaultOption () const
virtual void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const
virtual RString GetScreen (int) const
Public Attributes
LuaReference * m_pLuaTable
LuaReference m_EnabledForPlayersFunc
bool m_TableIsSane { false }
bool m_GoToFirstOnStart { false }
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerLua()
OptionRowHandlerLua::OptionRowHandlerLua () inline
References Init().
~OptionRowHandlerLua()
OptionRowHandlerLua::~OptionRowHandlerLua () inline override
References m_pLuaTable.
Member Function Documentation
ExportOption()
int OptionRowHandlerLua::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References ASSERT, LuaHelpers::CreateTableFromArrayB(), FOREACH_CONST, LuaManager::Get(), L, LUA, m_TableIsSane, LuaHelpers::Push(), LuaReference::PushSelf(), LuaManager::Release(), and LuaHelpers::RunScriptOnStack().
GoToFirstOnStart()
bool OptionRowHandlerLua::GoToFirstOnStart () inline override virtual
Reimplemented from OptionRowHandler.
References m_GoToFirstOnStart.
ImportOption()
void OptionRowHandlerLua::ImportOption (OptionRow * pRow, const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References ASSERT, LuaHelpers::CreateTableFromArrayB(), FOREACH_CONST, LuaManager::Get(), L, LUA, m_TableIsSane, LuaHelpers::Push(), LuaReference::PushSelf(), LuaHelpers::ReadArrayFromTableB(), LuaManager::Release(), and LuaHelpers::RunScriptOnStack().
Init()
void OptionRowHandlerLua::Init () inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::Init(), and LuaReference::Unset().
Referenced by OptionRowHandlerLua().
LoadInternal()
bool OptionRowHandlerLua::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
References ASSERT, CHECK_BLANK_ARG, CHECK_WRONG_NUM_ARGS, LuaManager::Get(), Command::GetArg(), L, LUA, OptionRowDefinition::m_bAllowThemeItems, OptionRowDefinition::m_bExportOnChange, OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, m_GoToFirstOnStart, OptionRowDefinition::m_layoutType, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, m_TableIsSane, OptionRowDefinition::m_vsChoices, OptionRowHandler::m_vsReloadRowMessages, LuaReference::PushSelf(), LuaManager::Release(), Command::Arg::s, SanityCheckTable(), SetEnabledForPlayers(), LuaReference::SetFromExpression(), LuaReference::SetFromStack(), StringToLayoutType(), StringToSelectType(), and Commands::v.
NotifyOfSelection()
bool OptionRowHandlerLua::NotifyOfSelection (PlayerNumber pn, int choice) inline override virtual
Reimplemented from OptionRowHandler.
References LuaManager::Get(), L, LUA, OptionRowHandler::m_Def, m_TableIsSane, OptionRowDefinition::m_vsChoices, LuaHelpers::Push(), LuaReference::PushSelf(), LuaManager::Release(), and LuaHelpers::RunScriptOnStack().
Reload()
ReloadChanged OptionRowHandlerLua::Reload () inline override virtual
Reimplemented from OptionRowHandler.
References OptionRowHandler::RELOAD_CHANGED_ENABLED, and SetEnabledForPlayers().
SanityCheckTable()
bool OptionRowHandlerLua::SanityCheckTable (lua_State * L, RString & RowName) inline
References LuaReference::GetLuaType(), L, LayoutType_Invalid, PlayerNumber_Invalid, LuaReference::PushSelf(), LuaHelpers::ReportScriptErrorFmt(), LuaHelpers::RunScriptOnStack(), SelectType_Invalid, StringToLayoutType(), StringToSelectType(), and TableContainsOnlyStrings().
Referenced by LoadInternal().
SetEnabledForPlayers()
void OptionRowHandlerLua::SetEnabledForPlayers () inline
References LuaManager::Get(), LuaReference::IsNil(), L, LUA, OptionRowHandler::m_Def, m_TableIsSane, OptionRowDefinition::m_vEnabledForPlayers, LuaReference::PushSelf(), LuaManager::Release(), and LuaHelpers::RunScriptOnStack().
Referenced by LoadInternal(), and Reload().
Member Data Documentation
m_EnabledForPlayersFunc
LuaReference OptionRowHandlerLua::m_EnabledForPlayersFunc
m_GoToFirstOnStart
bool OptionRowHandlerLua::m_GoToFirstOnStart { false }
Referenced by GoToFirstOnStart(), and LoadInternal().
m_pLuaTable
LuaReference* OptionRowHandlerLua::m_pLuaTable
Referenced by ~OptionRowHandlerLua().
m_TableIsSane
bool OptionRowHandlerLua::m_TableIsSane { false }
Referenced by ExportOption(), ImportOption(), LoadInternal(), NotifyOfSelection(), and SetEnabledForPlayers().
The documentation for this class was generated from the following file:
OptionRowHandler.cpp