Etterna: LunaModel Class Reference
LunaModel Class Reference
Allow Lua to have access to the Model.
Public Member Functions
LunaModel ()
Public Member Functions inherited from Luna< Model >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int position (T *p, lua_State *L)
static int playanimation (T *p, lua_State *L)
static int SetDefaultAnimation (T *p, lua_State *L)
static int GetDefaultAnimation (T *p, lua_State *L)
static int loop (T *p, lua_State *L)
static int rate (T *p, lua_State *L)
static int GetNumStates (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Model >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Model >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Model >
using T = Model
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Model >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Model.
Constructor & Destructor Documentation
LunaModel()
LunaModel::LunaModel () inline
References ADD_METHOD, GetDefaultAnimation(), GetNumStates(), loop(), playanimation(), position(), rate(), and SetDefaultAnimation().
Member Function Documentation
GetDefaultAnimation()
static int LunaModel::GetDefaultAnimation (T * p, lua_State * L) inline static
References Model::GetDefaultAnimation().
Referenced by LunaModel().
GetNumStates()
static int LunaModel::GetNumStates (T * p, lua_State * L) inline static
References Model::GetNumStates().
Referenced by LunaModel().
loop()
static int LunaModel::loop (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and Model::SetLoop().
Referenced by LunaModel().
playanimation()
static int LunaModel::playanimation (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, Model::PlayAnimation(), and SArg.
Referenced by LunaModel().
position()
static int LunaModel::position (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Model::SetPosition().
Referenced by LunaModel().
rate()
static int LunaModel::rate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Model::SetRate().
Referenced by LunaModel().
SetDefaultAnimation()
static int LunaModel::SetDefaultAnimation (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, SArg, and Model::SetDefaultAnimation().
Referenced by LunaModel().
The documentation for this class was generated from the following file:
Model.cpp