Etterna: LunaFilterManager Class Reference
LunaFilterManager Class Reference
Public Member Functions
LunaFilterManager ()
Public Member Functions inherited from Luna< FilterManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetSSFilter (T *p, lua_State *L)
static int GetSSFilter (T *p, lua_State *L)
static int ResetSSFilters (T *p, lua_State *L)
static int SetMaxFilterRate (T *p, lua_State *L)
static int GetMaxFilterRate (T *p, lua_State *L)
static int SetMinFilterRate (T *p, lua_State *L)
static int GetMinFilterRate (T *p, lua_State *L)
static int ToggleFilterMode (T *p, lua_State *L)
static int GetFilterMode (T *p, lua_State *L)
static int ToggleHighestSkillsetsOnly (T *p, lua_State *L)
static int GetHighestSkillsetsOnly (T *p, lua_State *L)
static int HelpImTrappedInAChineseFortuneCodingFactory (T *p, lua_State *L)
static int oopsimlazylol (T *p, lua_State *L)
static int grabposx (T *p, lua_State *L)
static int grabposy (T *p, lua_State *L)
static int savepos (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< FilterManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< FilterManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< FilterManager >
using T = FilterManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< FilterManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaFilterManager()
LunaFilterManager::LunaFilterManager () inline
References ADD_METHOD, GetFilterMode(), GetHighestSkillsetsOnly(), GetMaxFilterRate(), GetMinFilterRate(), GetSSFilter(), grabposx(), grabposy(), HelpImTrappedInAChineseFortuneCodingFactory(), oopsimlazylol(), ResetSSFilters(), savepos(), SetMaxFilterRate(), SetMinFilterRate(), SetSSFilter(), ToggleFilterMode(), and ToggleHighestSkillsetsOnly().
Member Function Documentation
GetFilterMode()
static int LunaFilterManager::GetFilterMode (T * p, lua_State * L) inline static
References FilterManager::ExclusiveFilter.
Referenced by LunaFilterManager().
GetHighestSkillsetsOnly()
static int LunaFilterManager::GetHighestSkillsetsOnly (T * p, lua_State * L) inline static
References FilterManager::HighestSkillsetsOnly.
Referenced by LunaFilterManager().
GetMaxFilterRate()
static int LunaFilterManager::GetMaxFilterRate (T * p, lua_State * L) inline static
References FilterManager::MaxFilterRate.
Referenced by LunaFilterManager().
GetMinFilterRate()
static int LunaFilterManager::GetMinFilterRate (T * p, lua_State * L) inline static
References FilterManager::m_pPlayerState.
Referenced by LunaFilterManager().
GetSSFilter()
static int LunaFilterManager::GetSSFilter (T * p, lua_State * L) inline static
References f, FilterManager::GetSSFilter(), and IArg.
Referenced by LunaFilterManager().
grabposx()
static int LunaFilterManager::grabposx (T * p, lua_State * L) inline static
References SArg, and FilterManager::watte.
Referenced by LunaFilterManager().
grabposy()
static int LunaFilterManager::grabposy (T * p, lua_State * L) inline static
References SArg, second, and FilterManager::watte.
Referenced by LunaFilterManager().
HelpImTrappedInAChineseFortuneCodingFactory()
static int LunaFilterManager::HelpImTrappedInAChineseFortuneCodingFactory (T * p, lua_State * L) inline static
References BArg, and FilterManager::galaxycollapsed.
Referenced by LunaFilterManager().
oopsimlazylol()
static int LunaFilterManager::oopsimlazylol (T * p, lua_State * L) inline static
References FilterManager::galaxycollapsed.
Referenced by LunaFilterManager().
ResetSSFilters()
static int LunaFilterManager::ResetSSFilters (T * p, lua_State * L) inline static
References FilterManager::ResetSSFilters().
Referenced by LunaFilterManager().
savepos()
static int LunaFilterManager::savepos (T * p, lua_State * L) inline static
References IArg, SArg, and FilterManager::watte.
Referenced by LunaFilterManager().
SetMaxFilterRate()
static int LunaFilterManager::SetMaxFilterRate (T * p, lua_State * L) inline static
References CLAMP(), FArg, FilterManager::m_pPlayerState, and FilterManager::MaxFilterRate.
Referenced by LunaFilterManager().
SetMinFilterRate()
static int LunaFilterManager::SetMinFilterRate (T * p, lua_State * L) inline static
References CLAMP(), f, FArg, FilterManager::m_pPlayerState, FilterManager::MaxFilterRate, and PlayerState::wtFFF.
Referenced by LunaFilterManager().
SetSSFilter()
static int LunaFilterManager::SetSSFilter (T * p, lua_State * L) inline static
References FArg, and IArg.
Referenced by LunaFilterManager().
ToggleFilterMode()
static int LunaFilterManager::ToggleFilterMode (T * p, lua_State * L) inline static
References FilterManager::ExclusiveFilter.
Referenced by LunaFilterManager().
ToggleHighestSkillsetsOnly()
static int LunaFilterManager::ToggleHighestSkillsetsOnly (T * p, lua_State * L) inline static
References FilterManager::HighestSkillsetsOnly.
Referenced by LunaFilterManager().
The documentation for this class was generated from the following file:
FilterManager.cpp