Etterna: ScreenInstallOverlay.cpp File Reference
ScreenInstallOverlay.cpp File Reference
#include "ScreenInstallOverlay.h"
#include "CryptManager.h"
#include "JsonUtil.h"
#include "Preference.h"
#include "RageFileManager.h"
#include "RageLog.h"
#include "ScreenManager.h"
#include "SpecialFiles.h"
#include "global.h"
#include "json/value.h"
#include "ActorUtil.h"
#include "CommandLineActions.h"
#include "CommonMetrics.h"
#include "GameManager.h"
#include "GameState.h"
#include "NoteData.h"
#include "ScreenDimensions.h"
#include "ScreenSelectMusic.h"
#include "Song.h"
#include "SongManager.h"
#include "StepMania.h"
#include "Steps.h"
#include <algorithm>
#include <fstream>
#include <iostream>
#include <iterator>
#include <vector>
#include "DownloadManager.h"
Classes
struct FileCopyResult
Functions
void InstallSmzipOsArg (const string &sOsZipFile)
static bool IsHTTPProtocol (const RString &arg)
static bool IsPackageFile (const RString &arg)
void DoInstalls (CommandLineActions::CommandLineArgs args)
REGISTER_SCREEN_CLASS (ScreenInstallOverlay)
Variables
const RString TEMP_OS_MOUNT_POINT = "/@temp-os/"
Function Documentation
DoInstalls()
void DoInstalls (CommandLineActions::CommandLineArgs args)
References CommandLineActions::CommandLineArgs::argv, BinaryToHex(), TimingData::BuildAndGetEtaner(), RageFile::Close(), Steps::Compress(), CRYPTMAN, DLMAN, f, FOREACH_CONST, SongManager::GetAllSongs(), Song::GetAllSteps(), Song::GetBackgroundPath(), Song::GetBannerPath(), Song::GetCDTitlePath(), Steps::GetChartKey(), GetExtension(), NoteData::GetNonEmptyRowVector(), Steps::GetNoteData(), RageFile::GetPath(), ScreenManager::GetScreen(), CryptManager::GetSHA1ForString(), Steps::GetTimingData(), Song::HasBackground(), Song::HasBanner(), Song::HasCDTitle(), InstallSmzipOsArg(), IsHTTPProtocol(), IsPackageFile(), NoteData::LogNonEmptyRows(), Song::m_sBackgroundFile, Song::m_sBannerFile, Song::m_sCDTitleFile, Song::m_UnknownStyleSteps, Song::m_vpSteps, RageFile::Open(), SCREENMAN, NoteData::SerializeNoteData(), ScreenManager::SetNewScreen(), SONGMAN, TimingData::UnsetEtaner(), NoteData::UnsetNerv(), NoteData::UnsetSerializedNoteData(), and Steps::WasLoadedFromProfile().
Referenced by ScreenInstallOverlay::Update().
InstallSmzipOsArg()
void InstallSmzipOsArg (const string & sOsZipFile)
References DLMAN, FAIL_M, FILEMAN, RageFileManager::Mount(), SCREENMAN, splitpath(), ScreenManager::SystemMessage(), and RageFileManager::Unmount().
Referenced by DoInstalls().
IsHTTPProtocol()
static bool IsHTTPProtocol (const RString & arg) static
References BeginsWith().
Referenced by DoInstalls().
IsPackageFile()
static bool IsPackageFile (const RString & arg) static
References StdString::CStdStr< CT >::EqualsNoCase(), and GetExtension().
Referenced by DoInstalls().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenInstallOverlay)
Variable Documentation
TEMP_OS_MOUNT_POINT
const RString TEMP_OS_MOUNT_POINT = "/@temp-os/"