Etterna: BackgroundLoader Class Reference
BackgroundLoader Class Reference
#include <RageUtil_BackgroundLoader.h>
Public Member Functions
BackgroundLoader ()
~BackgroundLoader ()
void CacheFile (const RString &file)
bool IsCacheFileFinished (const RString &sFile, RString &sActualPath)
void FinishedWithCachedFile (const RString &sFile)
void Abort ()
Private Member Functions
void LoadThread ()
RString GetRequest ()
RString GetCachePath (const RString &sPath) const
Static Private Member Functions
static int LoadThread_Start (void *p)
Private Attributes
RageThread m_LoadThread
bool m_bShutdownThread
RString m_sCachePathPrefix
RageSemaphore m_StartSem
RageMutex m_Mutex
vector< RString > m_CacheRequests
map< RString, int > m_FinishedRequests
bool m_sThreadIsActive
bool m_sThreadShouldAbort
Constructor & Destructor Documentation
BackgroundLoader()
BackgroundLoader::BackgroundLoader ()
References RageThread::Create(), g_bEnableBackgroundLoading, LoadThread_Start(), m_bShutdownThread, m_LoadThread, m_sCachePathPrefix, m_sThreadIsActive, m_sThreadShouldAbort, RageThread::SetName(), and ssprintf().
~BackgroundLoader()
BackgroundLoader::~BackgroundLoader ()
References Abort(), DeleteEmptyDirectories(), FILEMAN, g_bEnableBackgroundLoading, GetCachePath(), m_bShutdownThread, m_FinishedRequests, m_LoadThread, m_sCachePathPrefix, m_StartSem, RageSemaphore::Post(), RageFileManager::Remove(), and RageThread::Wait().
Member Function Documentation
Abort()
void BackgroundLoader::Abort ()
References FinishedWithCachedFile(), g_bEnableBackgroundLoading, GetRequest(), LockMut, m_FinishedRequests, m_Mutex, m_sThreadIsActive, and m_sThreadShouldAbort.
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::MenuBack(), ScreenSelectMusic::SelectCurrent(), and ~BackgroundLoader().
CacheFile()
void BackgroundLoader::CacheFile (const RString & file)
References g_bEnableBackgroundLoading, LockMut, m_CacheRequests, m_Mutex, m_StartSem, and RageSemaphore::Post().
Referenced by ScreenSelectMusic::AfterMusicChange().
FinishedWithCachedFile()
void BackgroundLoader::FinishedWithCachedFile (const RString & sFile)
References ASSERT_M, FILEMAN, g_bEnableBackgroundLoading, GetCachePath(), m_FinishedRequests, RageFileManager::Remove(), and ssprintf().
Referenced by Abort(), and ScreenSelectMusic::CheckBackgroundRequests().
GetCachePath()
RString BackgroundLoader::GetCachePath (const RString & sPath) const private
References m_sCachePathPrefix.
Referenced by FinishedWithCachedFile(), IsCacheFileFinished(), LoadThread(), and ~BackgroundLoader().
GetRequest()
RString BackgroundLoader::GetRequest () private
References g_bEnableBackgroundLoading, LockMut, m_CacheRequests, and m_Mutex.
Referenced by Abort(), and LoadThread().
IsCacheFileFinished()
bool BackgroundLoader::IsCacheFileFinished (const RString & sFile, RString & sActualPath)
References g_bEnableBackgroundLoading, g_bWriteToCache, GetCachePath(), LockMut, LOG, m_FinishedRequests, m_Mutex, and RageLog::Trace().
Referenced by ScreenSelectMusic::CheckBackgroundRequests().
LoadThread()
void BackgroundLoader::LoadThread () private
References RageFile::AtEOF(), RageFile::Close(), FILEMAN, g_bWriteToCache, GetCachePath(), GetRequest(), LockMut, LOG, m_bShutdownThread, m_FinishedRequests, m_Mutex, m_StartSem, m_sThreadIsActive, m_sThreadShouldAbort, RageFile::Open(), RageFile::Read(), RageFileManager::Remove(), RageLog::Trace(), RageSemaphore::Wait(), RageFile::WRITE, and RageFile::Write().
LoadThread_Start()
static int BackgroundLoader::LoadThread_Start (void * p) inline static private
Referenced by BackgroundLoader().
Member Data Documentation
m_bShutdownThread
bool BackgroundLoader::m_bShutdownThread private
Referenced by BackgroundLoader(), LoadThread(), and ~BackgroundLoader().
m_CacheRequests
vector<RString> BackgroundLoader::m_CacheRequests private
Referenced by CacheFile(), and GetRequest().
m_FinishedRequests
map<RString, int> BackgroundLoader::m_FinishedRequests private
Referenced by Abort(), FinishedWithCachedFile(), IsCacheFileFinished(), LoadThread(), and ~BackgroundLoader().
m_LoadThread
RageThread BackgroundLoader::m_LoadThread private
Referenced by BackgroundLoader(), and ~BackgroundLoader().
m_Mutex
RageMutex BackgroundLoader::m_Mutex private
Referenced by Abort(), CacheFile(), GetRequest(), IsCacheFileFinished(), and LoadThread().
m_sCachePathPrefix
RString BackgroundLoader::m_sCachePathPrefix private
Referenced by BackgroundLoader(), GetCachePath(), and ~BackgroundLoader().
m_StartSem
RageSemaphore BackgroundLoader::m_StartSem private
Referenced by CacheFile(), LoadThread(), and ~BackgroundLoader().
m_sThreadIsActive
bool BackgroundLoader::m_sThreadIsActive private
Referenced by Abort(), BackgroundLoader(), and LoadThread().
m_sThreadShouldAbort
bool BackgroundLoader::m_sThreadShouldAbort private
Referenced by Abort(), BackgroundLoader(), and LoadThread().
The documentation for this class was generated from the following files:
RageUtil_BackgroundLoader.h
RageUtil_BackgroundLoader.cpp