Etterna: NotesWriterETT Namespace Reference
NotesWriterETT Namespace Reference
Writes a Song to a .ETT file.
Functions
bool Write (RString &sPath, const Song &out, const vector< Steps *> &vpStepsToSave)
Write the song out to a file.
Detailed Description
Writes a Song to a .ETT file.
Function Documentation
Write()
bool NotesWriterETT::Write (RString & sPath, const Song & out, const vector< Steps *> & vpStepsToSave)
Write the song out to a file.
Parameters
sPath the path to write the file.
out the Song to be written out.
vpStepsToSave the Steps to save.
bSavingCache a flag to see if we're saving certain cache data.
Returns
its success or failure.
References f, RageFile::Flush(), FOREACH_CONST, Steps::GetChartKey(), RageFile::GetError(), GetETTNoteData(), Song::GetFirstSecond(), Song::GetLastSecond(), RageLog::Info(), LOG, Song::m_bHasBanner, Song::m_bHasMusic, Song::m_fMusicLengthSeconds, Song::m_sSongFileName, RageFile::Open(), RageFile::PutLine(), ssprintf(), RageLog::UserLog(), RageFile::WRITE, and WriteGlobalTags().
Referenced by Song::SaveToETTFile().