Etterna: RageSoundReader_MP3.cpp File Reference
RageSoundReader_MP3.cpp File Reference
#include "RageSoundReader_MP3.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "global.h"
#include <cerrno>
#include <cstdio>
#include <map>
#include "mad.h"
Classes
struct xing
struct madlib_t
struct madlib_t::mad_timer_compare_lt
Enumerations
enum tagtype { TAGTYPE_NONE = 0, TAGTYPE_ID3V1, TAGTYPE_ID3V2, TAGTYPE_ID3V2_FOOTER }
enum { XING_FRAMES = 0x00000001L, XING_BYTES = 0x00000002L, XING_TOC = 0x00000004L, XING_SCALE = 0x00000008L }
Functions
static tagtype tagtype (const unsigned char *data, id3_length_t length)
static unsigned long id3_parse_uint (const unsigned char **ptr, unsigned int bytes)
static unsigned long id3_parse_syncsafe (const unsigned char **ptr, unsigned int bytes)
static void parse_header (const unsigned char **ptr, unsigned int *version, int *flags, id3_length_t *size)
signed long id3_tag_query (const unsigned char *data, id3_length_t length)
void xing_init (struct xing *xing)
int xing_parse (struct xing *xing, struct mad_bitptr ptr, unsigned int bitlen)
static void mad_timer_sub (mad_timer_t *a, mad_timer_t b)
static float scale (mad_fixed_t sample)
static int get_this_frame_byte (const madlib_t *mad)
void fill_frame_index_cache (madlib_t *mad)
Variables
static const int ID3_TAG_FLAG_FOOTERPRESENT = 0x10
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
XING_FRAMES
XING_BYTES
XING_TOC
XING_SCALE
tagtype
enum tagtype
Enumerator
TAGTYPE_NONE
TAGTYPE_ID3V1
TAGTYPE_ID3V2
TAGTYPE_ID3V2_FOOTER
Function Documentation
fill_frame_index_cache()
void fill_frame_index_cache (madlib_t * mad)
References get_this_frame_byte(), madlib_t::Timer, madlib_t::timer_accurate, and madlib_t::tocmap.
Referenced by RageSoundReader_MP3::do_mad_frame_decode().
get_this_frame_byte()
static int get_this_frame_byte (const madlib_t * mad) static
References madlib_t::inbuf, madlib_t::inbuf_filepos, and madlib_t::Stream.
Referenced by RageSoundReader_MP3::do_mad_frame_decode(), fill_frame_index_cache(), RageSoundReader_MP3::handle_first_frame(), RageSoundReader_MP3::SetPosition_estimate(), and RageSoundReader_MP3::SetPosition_toc().
id3_parse_syncsafe()
static unsigned long id3_parse_syncsafe (const unsigned char ** ptr, unsigned int bytes) static
References ASSERT.
Referenced by parse_header().
id3_parse_uint()
static unsigned long id3_parse_uint (const unsigned char ** ptr, unsigned int bytes) static
References ASSERT.
Referenced by parse_header().
id3_tag_query()
signed long id3_tag_query (const unsigned char * data, id3_length_t length)
References ID3_TAG_FLAG_FOOTERPRESENT, parse_header(), TAGTYPE_ID3V1, TAGTYPE_ID3V2, TAGTYPE_ID3V2_FOOTER, and TAGTYPE_NONE.
Referenced by RageSoundReader_MP3::do_mad_frame_decode().
mad_timer_sub()
static void mad_timer_sub (mad_timer_t * a, mad_timer_t b) static
Referenced by RageSoundReader_MP3::SetPosition_hard().
parse_header()
static void parse_header (const unsigned char ** ptr, unsigned int * version, int * flags, id3_length_t * size) static
References id3_parse_syncsafe(), and id3_parse_uint().
Referenced by id3_tag_query().
scale()
static float scale (mad_fixed_t sample) static
Referenced by Actor::TweenState::operator==(), RageVec2Normalize(), RageVec3Normalize(), RageSoundReader_MP3::synth_output(), and VectorFloatNormalize().
tagtype()
static tagtype tagtype (const unsigned char * data, id3_length_t length) static
References TAGTYPE_ID3V1, TAGTYPE_ID3V2, TAGTYPE_ID3V2_FOOTER, and TAGTYPE_NONE.
xing_init()
void xing_init (struct xing * xing)
References xing::flags.
Referenced by RageSoundReader_MP3::handle_first_frame().
xing_parse()
int xing_parse (struct xing * xing, struct mad_bitptr ptr, unsigned int bitlen)
References xing::bytes, xing::flags, xing::frames, xing::INFO, xing::scale, xing::toc, xing::type, xing::XING, XING_BYTES, XING_FRAMES, XING_SCALE, and XING_TOC.
Referenced by RageSoundReader_MP3::handle_first_frame().
Variable Documentation
ID3_TAG_FLAG_FOOTERPRESENT
const int ID3_TAG_FLAG_FOOTERPRESENT = 0x10 static
Referenced by id3_tag_query().