Etterna: DBProfile Class Reference
DBProfile Class Reference
#include <DBProfile.h>
Public Member Functions
enum ProfileLoadResult LoadDBFromDir (string dir)
ProfileLoadResult LoadDBFromDir (string dir, Profile *profile)
ProfileLoadResult SaveDBToDir (string sDir, const Profile *profile, DBProfileMode mode) const
void MoveBackupToDir (const string &sFromDir, const string &sToDir, DBProfileMode mode)
void SetLoadingProfile (Profile *p)
Static Public Member Functions
static bool WriteReplayData (const HighScore *hs)
Private Member Functions
void LoadFavourites (SQLite::Database *db)
void LoadPlayLists (SQLite::Database *db)
void LoadPlayerScores (SQLite::Database *db)
bool LoadGeneralData (SQLite::Database *db)
void LoadPermaMirrors (SQLite::Database *db)
void LoadScoreGoals (SQLite::Database *db)
void SaveFavourites (SQLite::Database *db, const Profile *profile) const
void SavePlayLists (SQLite::Database *db, const Profile *profile) const
void SavePlayerScores (SQLite::Database *db, const Profile *profile, DBProfileMode mode) const
void SaveGeneralData (SQLite::Database *db, const Profile *profile) const
void SavePermaMirrors (SQLite::Database *db, const Profile *profile) const
void SaveScoreGoals (SQLite::Database *db, const Profile *profile) const
Static Private Member Functions
static int GetChartKeyID (SQLite::Database *db, string key)
static string GetChartKeyByID (SQLite::Database *db, int id)
static int FindOrCreateChartKey (SQLite::Database *db, string key)
static int FindOrCreateSong (SQLite::Database *db, string pack, string song)
static int FindOrCreateChart (SQLite::Database *db, string chartkey, string pack, string song, Difficulty diff)
static int GetScoreKeyID (SQLite::Database *db, string key)
static int FindOrCreateScoreKey (SQLite::Database *db, string key)
Private Attributes
Profile * loadingProfile { nullptr }
Member Function Documentation
FindOrCreateChart()
int DBProfile::FindOrCreateChart (SQLite::Database * db, string chartkey, string pack, string song, Difficulty diff) static private
References FindOrCreateChartKey(), and FindOrCreateSong().
Referenced by SavePlayLists().
FindOrCreateChartKey()
int DBProfile::FindOrCreateChartKey (SQLite::Database * db, string key) static private
References GetChartKeyID().
Referenced by FindOrCreateChart(), SaveFavourites(), SavePermaMirrors(), SavePlayerScores(), and SaveScoreGoals().
FindOrCreateScoreKey()
int DBProfile::FindOrCreateScoreKey (SQLite::Database * db, string key) static private
References GetScoreKeyID().
Referenced by SavePlayerScores(), and WriteReplayData().
FindOrCreateSong()
int DBProfile::FindOrCreateSong (SQLite::Database * db, string pack, string song) static private
Referenced by FindOrCreateChart(), and SavePlayerScores().
GetChartKeyByID()
string DBProfile::GetChartKeyByID (SQLite::Database * db, int id) static private
GetChartKeyID()
int DBProfile::GetChartKeyID (SQLite::Database * db, string key) static private
Referenced by FindOrCreateChartKey().
GetScoreKeyID()
int DBProfile::GetScoreKeyID (SQLite::Database * db, string key) static private
Referenced by FindOrCreateScoreKey().
LoadDBFromDir() [1/2]
ProfileLoadResult DBProfile::LoadDBFromDir (string dir, Profile * profile)
References LoadDBFromDir(), and loadingProfile.
LoadDBFromDir() [2/2]
ProfileLoadResult DBProfile::LoadDBFromDir (string dir)
References FILEMAN, LoadFavourites(), LoadPermaMirrors(), LoadPlayerScores(), LoadPlayLists(), LoadScoreGoals(), PROFILE_DB, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, and RageFileManager::ResolvePath().
Referenced by LoadDBFromDir().
LoadFavourites()
void DBProfile::LoadFavourites (SQLite::Database * db) private
References Profile::FavoritedCharts, loadingProfile, SongManager::MakePlaylistFromFavorites(), SongManager::SetFavoritedStatus(), and SONGMAN.
Referenced by LoadDBFromDir().
LoadGeneralData()
bool DBProfile::LoadGeneralData (SQLite::Database * db) private
References DateTime::FromString(), GAMEMAN, LuaManager::Get(), L, SongID::LoadFromString(), loadingProfile, LUA, Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iCurrentCombo, Profile::m_iNumToasties, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastDifficulty, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sDisplayName, Profile::m_sGuid, Profile::m_sLastUsedHighScoreName, Profile::m_SortOrder, Profile::m_UserTable, LuaManager::Release(), LuaReference::SetFromStack(), StringToSortOrder(), and GameManager::StringToStepsType().
LoadPermaMirrors()
void DBProfile::LoadPermaMirrors (SQLite::Database * db) private
References loadingProfile, Profile::PermaMirrorCharts, SongManager::SetPermaMirroredStatus(), and SONGMAN.
Referenced by LoadDBFromDir().
LoadPlayerScores()
void DBProfile::LoadPlayerScores (SQLite::Database * db) private
References ScoreManager::AddToKeyedIndex(), BinaryToHex(), clamp, FOREACH_ENUM, DateTime::FromString(), HighScore::GetDateTime(), HighScore::GetGrade(), ScoreManager::GetProfileScores(), HighScore::GetScoreKey(), CryptManager::GetSHA1ForString(), DateTime::GetString(), HighScore::GetWifeGrade(), HighScore::GetWifeScore(), Grade_Failed, Grade_Tier01, HNS_None, min(), ScoreManager::RegisterScore(), SCOREMAN, HighScore::SetChartKey(), HighScore::SetChordCohesion(), HighScore::SetDateTime(), HighScore::SetEtternaValid(), HighScore::SetGrade(), HighScore::SetHoldNoteScore(), HighScore::SetJudgeScale(), HighScore::SetMaxCombo(), HighScore::SetModifiers(), HighScore::SetMusicRate(), HighScore::SetScoreKey(), HighScore::SetSkillsetSSR(), HighScore::SetSSRCalcVersion(), HighScore::SetSSRNormPercent(), HighScore::SetSurviveSeconds(), HighScore::SetTapNoteScore(), HighScore::SetValidationKey(), HighScore::SetWifeScore(), TNS_CheckpointHit, TNS_CheckpointMiss, TNS_None, ValidationKey_Brittle, and ValidationKey_Weak.
Referenced by LoadDBFromDir().
LoadPlayLists()
void DBProfile::LoadPlayLists (SQLite::Database * db) private
References SongManager::activeplaylist, Profile::allplaylists, picosha2::detail::ch(), Playlist::chartlist, Chart::FromKey(), Chart::key, Chart::lastdiff, Chart::lastpack, Chart::lastsong, loadingProfile, Playlist::name, Chart::rate, and SONGMAN.
Referenced by LoadDBFromDir().
LoadScoreGoals()
void DBProfile::LoadScoreGoals (SQLite::Database * db) private
References ScoreGoal::comment, DateTime::FromString(), Profile::goalmap, loadingProfile, ScoreGoal::percent, ScoreGoal::priority, ScoreGoal::rate, ScoreGoal::scorekey, ScoreGoal::timeachieved, and ScoreGoal::timeassigned.
Referenced by LoadDBFromDir().
MoveBackupToDir()
void DBProfile::MoveBackupToDir (const string & sFromDir, const string & sToDir, DBProfileMode mode)
References FILEMAN, RageFileManager::IsAFile(), LocalWithoutReplayData, LocalWithReplayData, RageFileManager::Move(), PROFILE_DB, WRITE_ONLY_PROFILE_DB, and WriteOnlyWebExport.
SaveDBToDir()
ProfileLoadResult DBProfile::SaveDBToDir (string sDir, const Profile * profile, DBProfileMode mode) const
References FILEMAN, FOREACH_ENUM, LocalWithoutReplayData, LocalWithReplayData, PROFILE_DB, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, ProfileLoadResult_Success, RageFileManager::ResolvePath(), SaveFavourites(), SaveGeneralData(), SavePermaMirrors(), SavePlayerScores(), SavePlayLists(), SaveScoreGoals(), SkillsetToString(), WRITE_ONLY_PROFILE_DB, and WriteOnlyWebExport.
SaveFavourites()
void DBProfile::SaveFavourites (SQLite::Database * db, const Profile * profile) const private
References Profile::FavoritedCharts, FindOrCreateChartKey(), and FOREACHS_CONST.
Referenced by SaveDBToDir().
SaveGeneralData()
void DBProfile::SaveGeneralData (SQLite::Database * db, const Profile * profile) const private
References FOREACH_ENUM, FOREACHM_CONST, GAMEMAN, Profile::GetDisplayNameOrHighScoreName(), GameManager::GetStepsTypeInfo(), DateTime::GetString(), Profile::m_fPlayerRating, Profile::m_fPlayerSkillsets, Profile::m_iNumToasties, Profile::m_iNumTotalSongsPlayed, Profile::m_iTotalDancePoints, Profile::m_iTotalGameplaySeconds, Profile::m_iTotalHands, Profile::m_iTotalHolds, Profile::m_iTotalJumps, Profile::m_iTotalLifts, Profile::m_iTotalMines, Profile::m_iTotalRolls, Profile::m_iTotalSessions, Profile::m_iTotalSessionSeconds, Profile::m_iTotalTapsAndHolds, Profile::m_LastDifficulty, Profile::m_LastPlayedDate, Profile::m_lastSong, Profile::m_LastStepsType, Profile::m_sCharacterID, Profile::m_sDefaultModifiers, Profile::m_sGuid, Profile::m_sLastPlayedMachineGuid, Profile::m_SortOrder, NUM_StepsType, SortOrderToString(), StepsType_Invalid, StepsTypeInfo::szName, and SongID::ToString().
Referenced by SaveDBToDir().
SavePermaMirrors()
void DBProfile::SavePermaMirrors (SQLite::Database * db, const Profile * profile) const private
References FindOrCreateChartKey(), FOREACHS_CONST, and Profile::PermaMirrorCharts.
Referenced by SaveDBToDir().
SavePlayerScores()
void DBProfile::SavePlayerScores (SQLite::Database * db, const Profile * profile, DBProfileMode mode) const private
References BinaryToHex(), picosha2::detail::ch(), FindOrCreateChartKey(), FindOrCreateScoreKey(), FindOrCreateSong(), FOREACH_ENUM, FOREACHM, FOREACHUM, Chart::FromKey(), HighScore::GetChordCohesion(), HighScore::GetDateTime(), HighScore::GetEtternaValid(), HighScore::GetHoldNoteScore(), HighScore::GetJudgeScale(), HighScore::GetMaxCombo(), HighScore::GetModifiers(), HighScore::GetNoteRowVector(), HighScore::GetOffsetVector(), ScoreManager::GetProfileScores(), HighScore::GetScoreKey(), CryptManager::GetSHA1ForString(), HighScore::GetSkillsetSSR(), HighScore::GetSSRCalcVersion(), HighScore::GetSSRNormPercent(), DateTime::GetString(), HighScore::GetSurviveSeconds(), HighScore::GetTapNoteScore(), HighScore::GetValidationKey(), HighScore::GetWifeGrade(), HighScore::GetWifeScore(), Grade_Failed, GradeToString(), HNS_None, Chart::key, Chart::lastdiff, Chart::lastpack, Chart::lastsong, HighScore::LoadReplayData(), LocalWithReplayData, ScoreManager::minpercent, SCOREMAN, Skill_Overall, TNS_CheckpointHit, TNS_CheckpointMiss, TNS_None, HighScore::UnloadReplayData(), ValidationKey_Brittle, ValidationKey_Weak, and WriteOnlyWebExport.
Referenced by SaveDBToDir().
SavePlayLists()
void DBProfile::SavePlayLists (SQLite::Database * db, const Profile * profile) const private
References Profile::allplaylists, picosha2::detail::ch(), FindOrCreateChart(), FOREACH_CONST, and FOREACHM_CONST.
Referenced by SaveDBToDir().
SaveScoreGoals()
void DBProfile::SaveScoreGoals (SQLite::Database * db, const Profile * profile) const private
References FindOrCreateChartKey(), FOREACH_CONST, FOREACHUM_CONST, Profile::goalmap, and GoalsForChart::goals.
Referenced by SaveDBToDir().
SetLoadingProfile()
void DBProfile::SetLoadingProfile (Profile * p) inline
References loadingProfile.
Referenced by Profile::LoadAllFromDir().
WriteReplayData()
bool DBProfile::WriteReplayData (const HighScore * hs) static
References FindOrCreateScoreKey(), HighScore::GetNoteRowVector(), HighScore::GetOffsetVector(), ProfileManager::GetProfileDir(), HighScore::GetScoreKey(), PROFILE_DB, ProfileLoadResult_FailedNoProfile, ProfileLoadResult_FailedTampered, PROFILEMAN, and ProfileSlot_Player1.
Member Data Documentation
loadingProfile
Profile* DBProfile::loadingProfile { nullptr } private
Referenced by LoadDBFromDir(), LoadFavourites(), LoadGeneralData(), LoadPermaMirrors(), LoadPlayLists(), LoadScoreGoals(), and SetLoadingProfile().
The documentation for this class was generated from the following files:
DBProfile.h
DBProfile.cpp