Etterna: ThemeMetricDifficultiesToShow Class Reference
ThemeMetricDifficultiesToShow Class Reference
#include <CommonMetrics.h>
Public Member Functions
ThemeMetricDifficultiesToShow ()
ThemeMetricDifficultiesToShow (const RString &sGroup, const RString &sName)
void Read ()
const vector< Difficulty > & GetValue () const
Public Member Functions inherited from ThemeMetric< RString >
ThemeMetric (const RString &sGroup="", const RString &sName="")
ThemeMetric (const ThemeMetric< RString > &cpy)
~ThemeMetric () override
void Load (const RString &sGroup, const RString &sName)
Load the chosen metric from the .ini file.
void ChangeGroup (const RString &sGroup)
void Read () override
Actually read the metric and get its data.
void PushSelf (Lua *L)
void Clear () override
const RString & GetName () const
Retrieve the metric's name.
const RString & GetGroup () const
Retrieve the metric's group.
const RString & GetValue () const
Retrieve the metric's value.
operator const RString & () const
bool IsLoaded () const
bool operator== (const RString &input) const
Public Member Functions inherited from IThemeMetric
virtual ~IThemeMetric ()=default
Private Attributes
vector< Difficulty > m_v
Additional Inherited Members
Protected Attributes inherited from ThemeMetric< RString >
RString m_sGroup
the metric's group.
RString m_sName
the metric's name.
LuaReference m_Value
the metric's value.
RString m_currentValue
bool m_bCallEachTime
Constructor & Destructor Documentation
ThemeMetricDifficultiesToShow() [1/2]
ThemeMetricDifficultiesToShow::ThemeMetricDifficultiesToShow () inline
ThemeMetricDifficultiesToShow() [2/2]
ThemeMetricDifficultiesToShow::ThemeMetricDifficultiesToShow (const RString & sGroup, const RString & sName)
References ThemeMetric< RString >::IsLoaded(), and Read().
Member Function Documentation
GetValue()
const vector< Difficulty > & ThemeMetricDifficultiesToShow::GetValue () const
References m_v.
Referenced by GameState::ChangePreferredDifficulty(), GameState::GetClosestShownDifficulty(), and StepsDisplayList::SetFromGameState().
Read()
void ThemeMetricDifficultiesToShow::Read () virtual
Implements IThemeMetric.
References ASSERT, Difficulty_Invalid, FOREACH_CONST, ThemeMetric< RString >::GetName(), m_v, ThemeMetric< T >::Read(), LuaHelpers::ReportScriptError(), LuaHelpers::ReportScriptErrorFmt(), split(), and StringToDifficulty().
Referenced by ThemeMetricDifficultiesToShow().
Member Data Documentation
m_v
vector<Difficulty> ThemeMetricDifficultiesToShow::m_v private
Referenced by GetValue(), and Read().
The documentation for this class was generated from the following files:
CommonMetrics.h
CommonMetrics.cpp