Etterna: ScreenSyncOverlay.cpp File Reference
ScreenSyncOverlay.cpp File Reference
#include "ScreenSyncOverlay.h"
#include "ActorUtil.h"
#include "AdjustSync.h"
#include "GamePreferences.h"
#include "GameState.h"
#include "InputEventPlus.h"
#include "LocalizedString.h"
#include "PrefsManager.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "Song.h"
#include "global.h"
Functions
static bool IsGameplay ()
REGISTER_SCREEN_CLASS (ScreenSyncOverlay)
Variables
static bool previousGameplayState
bool g_bShowAutoplay = true
static LocalizedString AUTO_PLAY ("ScreenSyncOverlay", "AutoPlay")
static LocalizedString AUTO_PLAY_CPU ("ScreenSyncOverlay", "AutoPlayCPU")
static LocalizedString AUTO_PLAY_REPLAY ("ScreenSyncOverlay", "Replay")
static LocalizedString AUTO_SYNC_SONG ("ScreenSyncOverlay", "AutoSync Song")
static LocalizedString AUTO_SYNC_MACHINE ("ScreenSyncOverlay", "AutoSync Machine")
static LocalizedString AUTO_SYNC_TEMPO ("ScreenSyncOverlay", "AutoSync Tempo")
static LocalizedString OLD_OFFSET ("ScreenSyncOverlay", "Old offset")
static LocalizedString NEW_OFFSET ("ScreenSyncOverlay", "New offset")
static LocalizedString COLLECTING_SAMPLE ("ScreenSyncOverlay", "Collecting sample")
static LocalizedString STANDARD_DEVIATION ("ScreenSyncOverlay", "Standard deviation")
static LocalizedString CANT_SYNC_WHILE_PLAYING_A_COURSE ("ScreenSyncOverlay", "Can't sync while playing a course.")
static LocalizedString SYNC_CHANGES_REVERTED ("ScreenSyncOverlay", "Sync changes reverted.")
Function Documentation
IsGameplay()
static bool IsGameplay () static
References gameplay, Screen::GetScreenType(), ScreenManager::GetTopScreen(), and SCREENMAN.
Referenced by ScreenSyncOverlay::Input(), and ScreenSyncOverlay::Update().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenSyncOverlay)
Variable Documentation
AUTO_PLAY
LocalizedString AUTO_PLAY("ScreenSyncOverlay", "AutoPlay") static
Referenced by ScreenSyncOverlay::UpdateText().
AUTO_PLAY_CPU
LocalizedString AUTO_PLAY_CPU("ScreenSyncOverlay", "AutoPlayCPU") static
Referenced by ScreenSyncOverlay::UpdateText().
AUTO_PLAY_REPLAY
LocalizedString AUTO_PLAY_REPLAY("ScreenSyncOverlay", "Replay") static
Referenced by ScreenSyncOverlay::UpdateText().
AUTO_SYNC_MACHINE
LocalizedString AUTO_SYNC_MACHINE("ScreenSyncOverlay", "AutoSync Machine") static
Referenced by ScreenSyncOverlay::UpdateText().
AUTO_SYNC_SONG
LocalizedString AUTO_SYNC_SONG("ScreenSyncOverlay", "AutoSync Song") static
Referenced by ScreenSyncOverlay::UpdateText().
AUTO_SYNC_TEMPO
LocalizedString AUTO_SYNC_TEMPO("ScreenSyncOverlay", "AutoSync Tempo") static
Referenced by ScreenSyncOverlay::UpdateText().
CANT_SYNC_WHILE_PLAYING_A_COURSE
LocalizedString CANT_SYNC_WHILE_PLAYING_A_COURSE("ScreenSyncOverlay", "Can't sync while playing a course.") static
Referenced by ScreenSyncOverlay::Input().
COLLECTING_SAMPLE
LocalizedString COLLECTING_SAMPLE("ScreenSyncOverlay", "Collecting sample") static
Referenced by ScreenSyncOverlay::UpdateText().
g_bShowAutoplay
bool g_bShowAutoplay = true
Referenced by ScreenSyncOverlay::SetShowAutoplay(), and ScreenSyncOverlay::UpdateText().
NEW_OFFSET
LocalizedString NEW_OFFSET("ScreenSyncOverlay", "New offset") static
Referenced by ScreenSyncOverlay::UpdateText().
OLD_OFFSET
LocalizedString OLD_OFFSET("ScreenSyncOverlay", "Old offset") static
Referenced by ScreenSyncOverlay::UpdateText().
previousGameplayState
bool previousGameplayState static
Referenced by ScreenSyncOverlay::Init(), ScreenSyncOverlay::Input(), and ScreenSyncOverlay::Update().
STANDARD_DEVIATION
LocalizedString STANDARD_DEVIATION("ScreenSyncOverlay", "Standard deviation") static
Referenced by ScreenSyncOverlay::UpdateText().
SYNC_CHANGES_REVERTED
LocalizedString SYNC_CHANGES_REVERTED("ScreenSyncOverlay", "Sync changes reverted.") static
Referenced by ScreenSyncOverlay::Input().