Etterna: DebugLineReloadCurrentScreen Class Reference
DebugLineReloadCurrentScreen Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineReloadCurrentScreen::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), Actor::GetName(), ScreenManager::GetScreen(), ScreenManager::PopAllScreens(), SCREENMAN, ScreenManager::SetNewScreen(), SOUND, and GameSoundManager::StopMusic().
GetDisplayTitle()
RString DebugLineReloadCurrentScreen::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and RELOAD.
GetDisplayValue()
RString DebugLineReloadCurrentScreen::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References Actor::GetName(), ScreenManager::GetTopScreen(), and SCREENMAN.
GetPageName()
RString DebugLineReloadCurrentScreen::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineReloadCurrentScreen::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp