Etterna: InputHandler_DInput Class Reference
InputHandler_DInput Class Reference
#include <InputHandler_DirectInput.h>
Public Member Functions
InputHandler_DInput ()
~InputHandler_DInput ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
void Update ()
bool DevicesChanged ()
void WindowReset ()
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual InputDeviceState GetInputDeviceState (InputDevice)
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void UpdatePolled (DIDevice &device, const std::chrono::steady_clock::time_point &tm)
void UpdateBuffered (DIDevice &device, const std::chrono::steady_clock::time_point &tm)
void PollAndAcquireDevices (bool bBuffered)
void InputThreadMain ()
void StartThread ()
void ShutdownThread ()
Static Private Member Functions
static int InputThread_Start (void *p)
Private Attributes
RageThread m_InputThread
bool m_bShutdown
int m_iLastSeenNumHidDevices
int m_iNumTimesLeftToPollForJoysticksChanged
int m_iLastSeenNumJoysticks
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Constructor & Destructor Documentation
InputHandler_DInput()
InputHandler_DInput::InputHandler_DInput ()
References CheckForDirectInputDebugMode(), Devices, DIRECTINPUT_VERSION, EnumDevicesCallback(), g_dinput, g_iNumJoysticks, GetNumHidDevices(), GetNumJoysticksSlow(), RageLog::Info(), LOG, m_bShutdown, m_iLastSeenNumHidDevices, m_iLastSeenNumJoysticks, m_iNumTimesLeftToPollForJoysticksChanged, StartThread(), RageException::Throw(), and RageLog::Trace().
~InputHandler_DInput()
InputHandler_DInput::~InputHandler_DInput ()
References Devices, g_dinput, and ShutdownThread().
Member Function Documentation
DeviceButtonToChar()
wchar_t InputHandler_DInput::DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers) virtual
Reimplemented from InputHandler.
References InputHandler::DeviceButtonToChar(), Devices, FOREACH_CONST, KEY_BACK, KEY_ENTER, KEY_ESC, KEY_TAB, DIDevice::KEYBOARD, keys, ScancodeAndKeysToChar(), and ZERO.
DevicesChanged()
bool InputHandler_DInput::DevicesChanged () virtual
Reimplemented from InputHandler.
References RageTimer::Ago(), GetNumHidDevices(), GetNumJoysticksSlow(), LOG, m_iLastSeenNumHidDevices, m_iLastSeenNumJoysticks, m_iNumTimesLeftToPollForJoysticksChanged, POLL_FOR_JOYSTICK_CHANGES_EVERY_SECONDS, POLL_FOR_JOYSTICK_CHANGES_LENGTH_SECONDS, RageTimer::Touch(), and RageLog::Warn().
GetDevicesAndDescriptions()
void InputHandler_DInput::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References Devices.
InputThread_Start()
static int InputHandler_DInput::InputThread_Start (void * p) inline static private
Referenced by StartThread().
InputThreadMain()
void InputHandler_DInput::InputThreadMain () private
References CHECKPOINT, Devices, FAILED, Handle, LOG, m_bShutdown, PollAndAcquireDevices(), RageLog::Trace(), UpdateBuffered(), and RageLog::Warn().
PollAndAcquireDevices()
void InputHandler_DInput::PollAndAcquireDevices (bool bBuffered) private
References Devices, INPUTFILTER, and InputFilter::ResetDevice().
Referenced by InputThreadMain(), and Update().
ShutdownThread()
void InputHandler_DInput::ShutdownThread () private
References RageThread::IsCreated(), LOG, m_bShutdown, m_InputThread, RageLog::Trace(), and RageThread::Wait().
Referenced by WindowReset(), and ~InputHandler_DInput().
StartThread()
void InputHandler_DInput::StartThread () private
References ASSERT, RageThread::Create(), InputThread_Start(), RageThread::IsCreated(), PrefsManager::m_bThreadedInput, m_InputThread, PREFSMAN, and RageThread::SetName().
Referenced by InputHandler_DInput(), and WindowReset().
Update()
void InputHandler_DInput::Update () virtual
Reimplemented from InputHandler.
References Devices, RageThread::IsCreated(), m_InputThread, PollAndAcquireDevices(), UpdateBuffered(), UpdatePolled(), and InputHandler::UpdateTimer().
UpdateBuffered()
void InputHandler_DInput::UpdateBuffered (DIDevice & device, const std::chrono::steady_clock::time_point & tm) private
References input_t::AXIS, input_t::BUTTON, InputHandler::ButtonPressed(), DIDevice::dev, DIDevice::Device, DEVICE_MOUSE, DeviceButton_Invalid, enum_add2(), f, input_t::HAT, HAT_DOWN_MASK, HAT_LEFT_MASK, HAT_RIGHT_MASK, HAT_UP_MASK, INPUT_QSIZE, INPUTFILTER, DIDevice::Inputs, JOY_AUX_1, JOY_AUX_2, JOY_AUX_3, JOY_AUX_4, JOY_BUTTON_1, JOY_DOWN, JOY_HAT_DOWN, JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_LEFT, JOY_RIGHT, JOY_ROT_DOWN, JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_UP, JOY_ROT_Z_DOWN, JOY_ROT_Z_UP, JOY_UP, JOY_Z_DOWN, JOY_Z_UP, input_t::KEY, LOG, GamePreferences::m_AxisFix, DIDevice::m_sName, RageLog::MapLog(), max(), MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT, MOUSE_WHEELDOWN, MOUSE_WHEELUP, input_t::num, input_t::ofs, InputFilter::ResetDevice(), SCALE, RageLog::Trace(), TranslatePOV(), input_t::type, InputFilter::UpdateCursorLocation(), and InputFilter::UpdateMouseWheel().
Referenced by InputThreadMain(), and Update().
UpdatePolled()
void InputHandler_DInput::UpdatePolled (DIDevice & device, const std::chrono::steady_clock::time_point & tm) private
References input_t::AXIS, input_t::BUTTON, InputHandler::ButtonPressed(), DIDevice::dev, DIDevice::Device, DeviceButton_Invalid, enum_add2(), f, FAIL_M, GetDeviceState(), input_t::HAT, HAT_DOWN_MASK, HAT_LEFT_MASK, HAT_RIGHT_MASK, HAT_UP_MASK, INPUTFILTER, DIDevice::Inputs, JOY_AUX_1, JOY_AUX_2, JOY_AUX_3, JOY_AUX_4, JOY_BUTTON_1, JOY_DOWN, JOY_HAT_DOWN, JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_LEFT, JOY_RIGHT, JOY_ROT_DOWN, JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_UP, JOY_ROT_Z_DOWN, JOY_ROT_Z_UP, JOY_UP, JOY_Z_DOWN, JOY_Z_UP, DIDevice::JOYSTICK, DIDevice::KEYBOARD, keys, LOG, DIDevice::m_sName, RageLog::MapLog(), max(), DIDevice::MOUSE, MOUSE_LEFT, MOUSE_WHEELDOWN, MOUSE_WHEELUP, MOUSE_X_LEFT, MOUSE_X_RIGHT, MOUSE_Y_DOWN, MOUSE_Y_UP, input_t::num, input_t::ofs, SCALE, ssprintf(), TranslatePOV(), input_t::type, DIDevice::type, InputFilter::UpdateCursorLocation(), and InputFilter::UpdateMouseWheel().
Referenced by Update().
WindowReset()
void InputHandler_DInput::WindowReset () virtual
Reimplemented from InputHandler.
References ASSERT, Devices, INPUTFILTER, InputFilter::ResetDevice(), ShutdownThread(), and StartThread().
Member Data Documentation
m_bShutdown
bool InputHandler_DInput::m_bShutdown private
Referenced by InputHandler_DInput(), InputThreadMain(), and ShutdownThread().
m_iLastSeenNumHidDevices
int InputHandler_DInput::m_iLastSeenNumHidDevices private
Referenced by DevicesChanged(), and InputHandler_DInput().
m_iLastSeenNumJoysticks
int InputHandler_DInput::m_iLastSeenNumJoysticks private
Referenced by DevicesChanged(), and InputHandler_DInput().
m_InputThread
RageThread InputHandler_DInput::m_InputThread private
Referenced by ShutdownThread(), StartThread(), and Update().
m_iNumTimesLeftToPollForJoysticksChanged
int InputHandler_DInput::m_iNumTimesLeftToPollForJoysticksChanged private
Referenced by DevicesChanged(), and InputHandler_DInput().
The documentation for this class was generated from the following files:
InputHandler_DirectInput.h
InputHandler_DirectInput.cpp