Etterna: RageModelGeometry Class Reference
RageModelGeometry Class Reference
#include <RageModelGeometry.h>
Public Member Functions
RageModelGeometry ()
virtual ~RageModelGeometry ()
void LoadMilkshapeAscii (const RString &sMilkshapeAsciiFile, bool bNeedsNormals)
void OptimizeBones ()
void MergeMeshes (int iFromIndex, int iToIndex)
bool HasAnyPerVertexBones () const
Public Attributes
int m_iRefCount
vector< msMesh > m_Meshes
RageCompiledGeometry * m_pCompiledGeometry
RageVector3 m_vMins
RageVector3 m_vMaxs
Constructor & Destructor Documentation
RageModelGeometry()
RageModelGeometry::RageModelGeometry ()
References RageDisplay::CreateCompiledGeometry(), DISPLAY, m_iRefCount, and m_pCompiledGeometry.
~RageModelGeometry()
RageModelGeometry::~RageModelGeometry () virtual
References RageDisplay::DeleteCompiledGeometry(), DISPLAY, and m_pCompiledGeometry.
Member Function Documentation
HasAnyPerVertexBones()
bool RageModelGeometry::HasAnyPerVertexBones () const
References m_Meshes, and msMesh::Vertices.
Referenced by Model::LoadPieces().
LoadMilkshapeAscii()
void RageModelGeometry::LoadMilkshapeAscii (const RString & sMilkshapeAsciiFile, bool bNeedsNormals)
References ASSERT, ASSERT_M, RageModelVertex::bone, Dirname(), DISPLAY, f, FixSlashesInPlace(), RageFile::GetError(), RageFile::GetLine(), msMesh::m_iBoneIndex, m_Meshes, m_pCompiledGeometry, m_vMaxs, m_vMins, MergeMeshes(), MS_MAX_NAME, msMesh::nMaterialIndex, msTriangle::nVertexIndices, RageFile::Open(), OptimizeBones(), RageModelVertex::p, RageVec3AddToBounds(), RageVec3ClearBounds(), RageVec3Normalize(), RageCompiledGeometry::Set(), msMesh::sName, ssprintf(), RageDisplay::SupportsPerVertexMatrixScale(), RageModelVertex::t, RageModelVertex::TextureMatrixScale, RageException::Throw(), THROW, msMesh::Triangles, msMesh::Vertices, RageVector2::x, and RageVector2::y.
Referenced by ModelManager::LoadMilkshapeAscii().
MergeMeshes()
void RageModelGeometry::MergeMeshes (int iFromIndex, int iToIndex)
References m_Meshes, msMesh::Triangles, and msMesh::Vertices.
Referenced by LoadMilkshapeAscii().
OptimizeBones()
void RageModelGeometry::OptimizeBones ()
References msMesh::m_iBoneIndex, m_Meshes, and msMesh::Vertices.
Referenced by LoadMilkshapeAscii().
Member Data Documentation
m_iRefCount
int RageModelGeometry::m_iRefCount
Referenced by ModelManager::LoadMilkshapeAscii(), RageModelGeometry(), ModelManager::UnloadModel(), and ModelManager::~ModelManager().
m_Meshes
vector<msMesh> RageModelGeometry::m_Meshes
Referenced by Model::AdvanceFrame(), Model::DrawMesh(), Model::DrawPrimitives(), Model::EarlyAbortDraw(), HasAnyPerVertexBones(), LoadMilkshapeAscii(), Model::LoadPieces(), MergeMeshes(), OptimizeBones(), Model::PlayAnimation(), and Model::UpdateTempGeometry().
m_pCompiledGeometry
RageCompiledGeometry* RageModelGeometry::m_pCompiledGeometry
Referenced by Model::DrawMesh(), LoadMilkshapeAscii(), RageModelGeometry(), and ~RageModelGeometry().
m_vMaxs
RageVector3 RageModelGeometry::m_vMaxs
Referenced by LoadMilkshapeAscii().
m_vMins
RageVector3 RageModelGeometry::m_vMins
Referenced by LoadMilkshapeAscii().
The documentation for this class was generated from the following files:
RageModelGeometry.h
RageModelGeometry.cpp