Etterna: RageSurface.cpp File Reference
RageSurface.cpp File Reference
#include "global.h"
#include "RageSurface.h"
#include "RageUtil.h"
#include <climits>
Macros
#define COMP(a)
Functions
static int GetShiftFromMask (uint32_t mask)
static int GetBitsFromMask (uint32_t mask)
void SetupFormat (RageSurfaceFormat &fmt, int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
RageSurface * CreateSurface (int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
RageSurface * CreateSurfaceFrom (int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask, uint8_t *pPixels, uint32_t pitch)
Macro Definition Documentation
COMP
#define COMP (a)
Value:
if ((a) != rhs.a)                                                          \
        return false;
Referenced by RageSurfaceFormat::Equivalent().
Function Documentation
CreateSurface()
RageSurface* CreateSurface (int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
References SetupFormat().
Referenced by RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface(), ImageCache::CacheImageInternal(), RageSurfaceUtils::ConvertSurface(), RageBitmapTexture::Create(), RageDisplay_GLES2::CreateScreenshot(), RageDisplay_D3D::CreateScreenshot(), RageDisplay_Null::CreateScreenshot(), RageDisplay_Legacy::CreateScreenshot(), MovieTexture_DShow::CreateTexture(), RageDisplay_Legacy::GetImgPixelFormat(), RageDisplay_Legacy::GetTexture(), LoadBMP(), RageSurfaceUtils::LoadSurface(), LoadWin32Surface(), RageSurfaceUtils::MakeDummySurface(), MakePixbuf(), MovieTexture_Null::MovieTexture_Null(), RageSurfaceUtils::Palettize(), RageSurfaceUtils::PalettizeToGrayscale(), RageSurface_Load_JPEG(), RageSurface_Load_XPM(), ReadImage(), RageSurfaceUtils::SaveBMP(), and RageSurfaceUtils::Zoom().
CreateSurfaceFrom()
RageSurface* CreateSurfaceFrom (int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask, uint8_t * pPixels, uint32_t pitch)
References SetupFormat().
Referenced by MovieTexture_DShow::CheckFrame(), RageDisplay::CreateSurfaceFromPixfmt(), and RageMovieTexture_Generic_Intermediate::CreateTexture().
GetBitsFromMask()
static int GetBitsFromMask (uint32_t mask) static
References GetShiftFromMask().
Referenced by SetupFormat().
GetShiftFromMask()
static int GetShiftFromMask (uint32_t mask) static
Referenced by GetBitsFromMask(), and SetupFormat().
SetupFormat()
void SetupFormat (RageSurfaceFormat & fmt, int width, int height, int BitsPerPixel, uint32_t Rmask, uint32_t Gmask, uint32_t Bmask, uint32_t Amask)
References RageSurfaceFormat::BitsPerPixel, RageSurfaceFormat::BytesPerPixel, GetBitsFromMask(), GetShiftFromMask(), RageSurfaceFormat::Loss, RageSurfaceFormat::Mask, RageSurfacePalette::ncolors, RageSurfaceFormat::palette, RageSurfaceFormat::Shift, and ZERO.
Referenced by CreateSurface(), and CreateSurfaceFrom().