Etterna: RageSoundBase Class Reference
RageSoundBase Class Reference abstract
#include <RageSound.h>
Public Member Functions
virtual ~RageSoundBase ()=default
virtual void SoundIsFinishedPlaying ()=0
virtual int GetDataToPlay (float *buffer, int size, int64_t &iStreamFrame, int &got_bytes)=0
virtual void CommitPlayingPosition (int64_t iFrameno, int64_t iPosition, int iBytesRead)=0
virtual RageTimer GetStartTime () const
virtual RString GetLoadedFilePath () const =0
Constructor & Destructor Documentation
~RageSoundBase()
virtual RageSoundBase::~RageSoundBase () virtual default
Member Function Documentation
CommitPlayingPosition()
virtual void RageSoundBase::CommitPlayingPosition (int64_t iFrameno, int64_t iPosition, int iBytesRead) pure virtual
Implemented in RageSound.
Referenced by RageSoundDriver::Update().
GetDataToPlay()
virtual int RageSoundBase::GetDataToPlay (float * buffer, int size, int64_t & iStreamFrame, int & got_bytes) pure virtual
Implemented in RageSound.
Referenced by RageSoundDriver::GetDataForSound().
GetLoadedFilePath()
virtual RString RageSoundBase::GetLoadedFilePath () const pure virtual
Implemented in RageSound.
GetStartTime()
virtual RageTimer RageSoundBase::GetStartTime () const inline virtual
Reimplemented in RageSound.
References RageZeroTimer.
Referenced by RageSoundDriver::StartMixing().
SoundIsFinishedPlaying()
virtual void RageSoundBase::SoundIsFinishedPlaying () pure virtual
Implemented in RageSound.
Referenced by RageSoundDriver::StopMixing(), and RageSoundDriver::Update().
The documentation for this class was generated from the following file:
RageSound.h