Etterna: MovieTexture_DShow.cpp File Reference
MovieTexture_DShow.cpp File Reference
#include "global.h"
#include "MovieTexture_DShow.h"
#include "MovieTexture_DShowHelper.h"
#include "RageException.h"
#include "RageLog.h"
#include "RageSurface.h"
#include "RageTextureManager.h"
#include "RageUtil.h"
#include "arch/Dialog/Dialog.h"
#include "archutils/Win32/DirectXHelpers.h"
#include <vfw.h>
Functions
REGISTER_MOVIE_TEXTURE_CLASS (DShow)
static RString FourCCToString (int fcc)
static void CheckCodecVersion (RString codec, RString desc)
static void GetVideoCodecDebugInfo ()
RString PrintCodecError (HRESULT hr, RString s)
Function Documentation
CheckCodecVersion()
static void CheckCodecVersion (RString codec, RString desc) static
References StdString::CStdStr< CT >::CompareNoCase(), LOG, ssprintf(), and RageLog::Warn().
Referenced by GetVideoCodecDebugInfo().
FourCCToString()
static RString FourCCToString (int fcc) static
References clamp.
Referenced by GetVideoCodecDebugInfo().
GetVideoCodecDebugInfo()
static void GetVideoCodecDebugInfo () static
References CheckCodecVersion(), CHECKPOINT, FourCCToString(), RageLog::Info(), LOG, RageLog::Trace(), and WStringToRString().
Referenced by MovieTexture_DShow::MovieTexture_DShow().
PrintCodecError()
RString PrintCodecError (HRESULT hr, RString s)
References ssprintf().
Referenced by MovieTexture_DShow::Create().
REGISTER_MOVIE_TEXTURE_CLASS()
REGISTER_MOVIE_TEXTURE_CLASS (DShow)