Etterna: LunaTapNote Class Reference
LunaTapNote Class Reference
Allow Lua to have access to the TapNote.
Public Member Functions
DEFINE_METHOD (GetTapNoteType, type)
DEFINE_METHOD (GetTapNoteSubType, subType)
DEFINE_METHOD (GetTapNoteSource, source)
DEFINE_METHOD (GetPlayerNumber, pn)
DEFINE_METHOD (GetKeysoundIndex, iKeysoundIndex)
LunaTapNote ()
Public Member Functions inherited from Luna< TapNote >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetHoldDuration (T *p, lua_State *L)
static int GetTapNoteResult (T *p, lua_State *L)
static int GetHoldNoteResult (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< TapNote >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< TapNote >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< TapNote >
using T = TapNote
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< TapNote >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the TapNote.
Constructor & Destructor Documentation
LunaTapNote()
LunaTapNote::LunaTapNote () inline
References ADD_METHOD.
Member Function Documentation
DEFINE_METHOD() [1/5]
LunaTapNote::DEFINE_METHOD (GetTapNoteType , type)
DEFINE_METHOD() [2/5]
LunaTapNote::DEFINE_METHOD (GetTapNoteSubType , subType)
DEFINE_METHOD() [3/5]
LunaTapNote::DEFINE_METHOD (GetTapNoteSource , source)
DEFINE_METHOD() [4/5]
LunaTapNote::DEFINE_METHOD (GetPlayerNumber , pn)
DEFINE_METHOD() [5/5]
LunaTapNote::DEFINE_METHOD (GetKeysoundIndex , iKeysoundIndex)
GetHoldDuration()
static int LunaTapNote::GetHoldDuration (T * p, lua_State * L) inline static
References TapNote::iDuration, and NoteRowToBeat().
GetHoldNoteResult()
static int LunaTapNote::GetHoldNoteResult (T * p, lua_State * L) inline static
References TapNote::HoldResult, and HoldNoteResult::PushSelf().
GetTapNoteResult()
static int LunaTapNote::GetTapNoteResult (T * p, lua_State * L) inline static
References TapNoteResult::PushSelf(), and TapNote::result.
The documentation for this class was generated from the following file:
NoteTypes.cpp