Etterna: InputHandler_X11.cpp File Reference
InputHandler_X11.cpp File Reference
#include "InputHandler_X11.h"
#include "global.h"
#include <array>
#include "InputFilter.h"
#include "RageDisplay.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Unix/X11Helper.h"
#include <X11/Xlib.h>
#include <X11/keysym.h>
Macros
#define KEY_INV DeviceButton_Invalid
Functions
REGISTER_INPUT_HANDLER_CLASS (X11)
static DeviceButton XSymToDeviceButton (int key)
static DeviceButton XMouseButtonToDeviceButton (int button)
Macro Definition Documentation
KEY_INV
#define KEY_INV DeviceButton_Invalid
Referenced by XSymToDeviceButton().
Function Documentation
REGISTER_INPUT_HANDLER_CLASS()
REGISTER_INPUT_HANDLER_CLASS (X11)
XMouseButtonToDeviceButton()
static DeviceButton XMouseButtonToDeviceButton (int button) static
References DeviceButton_Invalid, MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT, MOUSE_WHEELDOWN, and MOUSE_WHEELUP.
Referenced by InputHandler_X11::Update().
XSymToDeviceButton()
static DeviceButton XSymToDeviceButton (int key) static
References DeviceButton_Invalid, enum_add2(), KEY_ACCENT, KEY_AMPER, KEY_ASTERISK, KEY_AT, KEY_BACK, KEY_BACKSLASH, KEY_C0, KEY_C1, KEY_C2, KEY_C3, KEY_C4, KEY_C5, KEY_C6, KEY_C7, KEY_C8, KEY_C9, KEY_CA, KEY_Ca, KEY_CAPSLOCK, KEY_CARAT, KEY_CB, KEY_Cb, KEY_CC, KEY_Cc, KEY_CD, KEY_Cd, KEY_CE, KEY_Ce, KEY_CF, KEY_Cf, KEY_CG, KEY_Cg, KEY_CH, KEY_Ch, KEY_CI, KEY_Ci, KEY_CJ, KEY_Cj, KEY_CK, KEY_Ck, KEY_CL, KEY_Cl, KEY_CM, KEY_Cm, KEY_CN, KEY_Cn, KEY_CO, KEY_Co, KEY_COLON, KEY_COMMA, KEY_CP, KEY_Cp, KEY_CQ, KEY_Cq, KEY_CR, KEY_Cr, KEY_CS, KEY_Cs, KEY_CT, KEY_Ct, KEY_CU, KEY_Cu, KEY_CV, KEY_Cv, KEY_CW, KEY_Cw, KEY_CX, KEY_Cx, KEY_CY, KEY_Cy, KEY_CZ, KEY_Cz, KEY_DEL, KEY_DOLLAR, KEY_DOWN, KEY_END, KEY_ENTER, KEY_EQUAL, KEY_ESC, KEY_EXCL, KEY_F1, KEY_F10, KEY_F11, KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_HASH, KEY_HOME, KEY_HYPHEN, KEY_INSERT, KEY_INV, KEY_KP_ASTERISK, KEY_KP_C0, KEY_KP_C1, KEY_KP_C2, KEY_KP_C3, KEY_KP_C4, KEY_KP_C5, KEY_KP_C6, KEY_KP_C7, KEY_KP_C8, KEY_KP_C9, KEY_KP_ENTER, KEY_KP_EQUAL, KEY_KP_HYPHEN, KEY_KP_PERIOD, KEY_KP_PLUS, KEY_KP_SLASH, KEY_LALT, KEY_LANGLE, KEY_LBRACE, KEY_LBRACKET, KEY_LCTRL, KEY_LEFT, KEY_LMETA, KEY_LPAREN, KEY_LSHIFT, KEY_LSUPER, KEY_MENU, KEY_NUMLOCK, KEY_PAUSE, KEY_PERCENT, KEY_PERIOD, KEY_PGDN, KEY_PGUP, KEY_PIPE, KEY_PLUS, KEY_PRTSC, KEY_QUESTION, KEY_QUOTE, KEY_RALT, KEY_RANGLE, KEY_RBRACE, KEY_RBRACKET, KEY_RCTRL, KEY_RIGHT, KEY_RMETA, KEY_RPAREN, KEY_RSHIFT, KEY_RSUPER, KEY_SCRLLOCK, KEY_SEMICOLON, KEY_SLASH, KEY_SPACE, KEY_SQUOTE, KEY_TAB, KEY_UNDERSCORE, KEY_UP, MOUSE_LEFT, MOUSE_MIDDLE, MOUSE_RIGHT, MOUSE_WHEELDOWN, and MOUSE_WHEELUP.
Referenced by InputHandler_X11::Update().