Etterna: ScreenSelectMusic Class Reference
ScreenSelectMusic Class Reference
#include <ScreenSelectMusic.h>
Public Member Functions
~ScreenSelectMusic () override
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
void Update (float fDeltaTime) override
bool Input (const InputEventPlus &input) override
void HandleMessage (const Message &msg) override
void HandleScreenMessage (ScreenMessage SM) override
bool AllowLateJoin () const override
Determine if we allow extra players to join in on this screen.
bool MenuStart (const InputEventPlus &input) override
bool MenuBack (const InputEventPlus &input) override
bool SelectCurrent (PlayerNumber pn)
void StartPlayingMusic () override
bool GetGoToOptions () const
MusicWheel * GetMusicWheel ()
void OpenOptionsList (PlayerNumber pn)
void OnConfirmSongDeletion ()
bool can_open_options_list (PlayerNumber pn)
void DifferentialReload ()
void PlayReplay (HighScore *score)
int GetSelectionState ()
void PushSelf (lua_State *L) override
Public Member Functions inherited from ScreenWithMenuElements
ScreenWithMenuElements ()
void Init () override
This is called immediately after construction, to allow initializing after all derived classes exist.
void BeginScreen () override
This is called immediately before the screen is used.
~ScreenWithMenuElements () override
void HandleScreenMessage (ScreenMessage SM) override
void Update (float fDeltaTime) override
void StartTransitioningScreen (ScreenMessage smSendWhenDone)
virtual void Cancel (ScreenMessage smSendWhenDone)
bool IsTransitioning ()
bool AllowCallbackInput () override
void StopTimer ()
void ResetTimer ()
virtual void TweenOnScreen ()
virtual void TweenOffScreen ()
void PushSelf (lua_State *L) override
bool AllowLateJoin () const override
Determine if we allow extra players to join in on this screen.
Public Member Functions inherited from Screen
~Screen () override
virtual void EndScreen ()
This is called when the screen is popped.
void SetLockInputSecs (float f)
void PostScreenMessage (ScreenMessage SM, float fDelay)
Put the specified message onto the screen for a specified time.
void ClearMessageQueue ()
Clear the entire message queue.
void ClearMessageQueue (ScreenMessage SM)
Clear the message queue of a specific ScreenMessage.
virtual ScreenType GetScreenType () const
bool AllowOperatorMenuButton () const
RString GetNextScreenName () const
RString GetPrevScreen () const
void SetNextScreenName (RString const &name)
void SetPrevScreenName (RString const &name)
bool PassInputToLua (const InputEventPlus &input)
void AddInputCallbackFromStack (lua_State *L)
void RemoveInputCallback (lua_State *L)
virtual bool MenuUp (const InputEventPlus &)
virtual bool MenuDown (const InputEventPlus &)
virtual bool MenuLeft (const InputEventPlus &)
virtual bool MenuRight (const InputEventPlus &)
virtual bool MenuSelect (const InputEventPlus &)
virtual bool MenuCoin (const InputEventPlus &)
Public Member Functions inherited from ActorFrame
ActorFrame ()
ActorFrame (const ActorFrame &cpy)
~ActorFrame () override
void InitState () override
Set up the initial state.
void LoadFromNode (const XNode *pNode) override
ActorFrame * Copy () const override
virtual void AddChild (Actor *pActor)
Add a new child to the ActorFrame.
virtual void RemoveChild (Actor *pActor)
Remove the specified child from the ActorFrame.
void TransferChildren (ActorFrame *pTo)
Actor * GetChild (const RString &sName)
vector< Actor * > GetChildren ()
int GetNumChildren () const
void RemoveAllChildren ()
Remove all of the children from the frame.
void MoveToTail (Actor *pActor)
Move a particular actor to the tail.
void MoveToHead (Actor *pActor)
Move a particular actor to the head.
void SortByDrawOrder ()
void SetDrawByZPosition (bool b)
void SetDrawFunction (const LuaReference &DrawFunction)
void SetUpdateFunction (const LuaReference &UpdateFunction)
LuaReference GetDrawFunction () const
virtual bool AutoLoadChildren () const
void DeleteChildrenWhenDone (bool bDelete=true)
void DeleteAllChildren ()
void PushChildrenTable (lua_State *L)
void PushChildTable (lua_State *L, const RString &sName)
void PlayCommandOnChildren (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void PlayCommandOnLeaves (const RString &sCommandName, const LuaReference *pParamTable=nullptr)
void RunCommandsRecursively (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
virtual void RunCommandsOnChildren (const LuaReference &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnChildren (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
void RunCommandsOnLeaves (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void UpdateInternal (float fDeltaTime) override
void BeginDraw () override
Start the drawing and push the transform on the world matrix stack.
void DrawPrimitives () override
Draw the primitives of the Actor.
void EndDraw () override
Pop the transform from the world matrix stack.
void SetZTestMode (ZTestMode mode) override
void SetZWrite (bool b) override
void FinishTweening () override
void HurryTweening (float factor) override
void SetUpdateRate (float rate) override
float GetUpdateRate () override
void SetFOV (float fFOV)
void SetVanishPoint (float fX, float fY)
void SetCustomLighting (bool bCustomLighting)
void SetAmbientLightColor (const RageColor &c)
void SetDiffuseLightColor (const RageColor &c)
void SetSpecularLightColor (const RageColor &c)
void SetLightDirection (const RageVector3 &vec)
virtual void SetPropagateCommands (bool b)
float GetTweenTimeLeft () const override
Amount of time until all tweens (and all children's tweens) have stopped:
void RunCommands (const LuaReference &cmds, const LuaReference *pParamTable=nullptr) override
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
Public Member Functions inherited from Actor
Actor ()
Set up the Actor with its initial settings.
Actor (const Actor &cpy)
Copy a new Actor to the old one.
~Actor () override
bool PartiallyOpaque ()
void Draw ()
Calls multiple functions for drawing the Actors.
virtual bool EarlyAbortDraw () const
Allow the Actor to be aborted early.
virtual void PreDraw ()
Calculate values that may be needed for drawing.
virtual void PostDraw ()
Reset internal diffuse and glow.
virtual void SetGlobalRenderStates ()
Set the global rendering states of this Actor.
virtual void SetTextureRenderStates ()
Set the texture rendering states of this Actor.
bool IsFirstUpdate () const
void UpdateTweening (float fDeltaTime)
void CalcPercentThroughTween ()
virtual void SetCurrentTweenStart ()
virtual void EraseHeadTween ()
virtual void UpdatePercentThroughTween (float PercentThroughTween)
bool get_tween_uses_effect_delta ()
void set_tween_uses_effect_delta (bool t)
const RString & GetName () const
Retrieve the Actor's name.
virtual void SetName (const RString &sName)
Set the Actor's name to a new one.
void SetParent (Actor *pParent)
Give this Actor a new parent.
Actor * GetParent ()
Retrieve the Actor's parent.
RString GetLineage () const
Retrieve the Actor's lineage.
void SetFakeParent (Actor *mailman)
Actor * GetFakeParent ()
void AddWrapperState ()
void RemoveWrapperState (size_t i)
Actor * GetWrapperState (size_t i)
size_t GetNumWrapperStates () const
float GetX () const
Retrieve the Actor's x position.
float GetY () const
Retrieve the Actor's y position.
float GetZ () const
Retrieve the Actor's z position.
float GetDestX () const
float GetDestY () const
float GetDestZ () const
void SetX (float x)
void SetY (float y)
void SetZ (float z)
void SetXY (float x, float y)
void AddX (float x)
Add to the x position of this Actor.
void AddY (float y)
Add to the y position of this Actor.
void AddZ (float z)
Add to the z position of this Actor.
float GetUnzoomedWidth () const
float GetUnzoomedHeight () const
float GetZoomedWidth () const
float GetZoomedHeight () const
void SetWidth (float width)
void SetHeight (float height)
float GetBaseZoomX () const
void SetBaseZoomX (float zoom)
float GetBaseZoomY () const
void SetBaseZoomY (float zoom)
float GetBaseZoomZ () const
void SetBaseZoomZ (float zoom)
void SetBaseZoom (float zoom)
void SetBaseRotationX (float rot)
void SetBaseRotationY (float rot)
void SetBaseRotationZ (float rot)
void SetBaseRotation (const RageVector3 &rot)
virtual void SetBaseAlpha (float fAlpha)
void SetInternalDiffuse (const RageColor &c)
void SetInternalGlow (const RageColor &c)
float GetZoom () const
Retrieve the general zoom factor, using the x coordinate of the Actor.
float GetZoomX () const
Retrieve the zoom factor for the x coordinate of the Actor.
float GetZoomY () const
Retrieve the zoom factor for the y coordinate of the Actor.
float GetZoomZ () const
Retrieve the zoom factor for the z coordinate of the Actor.
void SetZoom (float zoom)
Set the zoom factor for all dimensions of the Actor.
void SetZoomX (float zoom)
Set the zoom factor for the x dimension of the Actor.
void SetZoomY (float zoom)
Set the zoom factor for the y dimension of the Actor.
void SetZoomZ (float zoom)
Set the zoom factor for the z dimension of the Actor.
void ZoomTo (float fX, float fY)
void ZoomToWidth (float zoom)
void ZoomToHeight (float zoom)
float GetRotationX () const
float GetRotationY () const
float GetRotationZ () const
void SetRotationX (float rot)
void SetRotationY (float rot)
void SetRotationZ (float rot)
void AddRotationX (float rot)
void AddRotationY (float rot)
void AddRotationZ (float rot)
void AddRotationH (float rot)
void AddRotationP (float rot)
void AddRotationR (float rot)
void SetSkewX (float fAmount)
float GetSkewX (float) const
void SetSkewY (float fAmount)
float GetSkewY (float) const
float GetCropLeft () const
float GetCropTop () const
float GetCropRight () const
float GetCropBottom () const
void SetCropLeft (float percent)
void SetCropTop (float percent)
void SetCropRight (float percent)
void SetCropBottom (float percent)
void SetFadeLeft (float percent)
void SetFadeTop (float percent)
void SetFadeRight (float percent)
void SetFadeBottom (float percent)
void SetGlobalDiffuseColor (const RageColor &c)
virtual void SetDiffuse (const RageColor &c)
virtual void SetDiffuseAlpha (float f)
float GetCurrentDiffuseAlpha () const
void SetDiffuseColor (const RageColor &c)
void SetDiffuses (int i, const RageColor &c)
void SetDiffuseUpperLeft (const RageColor &c)
void SetDiffuseUpperRight (const RageColor &c)
void SetDiffuseLowerLeft (const RageColor &c)
void SetDiffuseLowerRight (const RageColor &c)
void SetDiffuseTopEdge (const RageColor &c)
void SetDiffuseRightEdge (const RageColor &c)
void SetDiffuseBottomEdge (const RageColor &c)
void SetDiffuseLeftEdge (const RageColor &c)
RageColor GetDiffuse () const
RageColor GetDiffuses (int i) const
float GetDiffuseAlpha () const
void SetGlow (const RageColor &c)
RageColor GetGlow () const
void SetAux (float f)
float GetAux () const
virtual void BeginTweening (float time, ITween *pInterp)
void BeginTweening (float time, TweenType tt=TWEEN_LINEAR)
virtual void StopTweening ()
void Sleep (float time)
void QueueCommand (const RString &sCommandName)
void QueueMessage (const RString &sMessageName)
TweenState & DestTweenState ()
const TweenState & DestTweenState () const
void ScaleToCover (const RectF &rect)
void ScaleToFitInside (const RectF &rect)
void ScaleTo (const RectF &rect, StretchType st)
void StretchTo (const RectF &rect)
virtual void SetHorizAlign (float f)
virtual void SetVertAlign (float f)
void SetHorizAlign (HorizAlign ha)
void SetVertAlign (VertAlign va)
virtual float GetHorizAlign ()
virtual float GetVertAlign ()
void StopEffect ()
Effect GetEffect () const
float GetSecsIntoEffect () const
float GetEffectDelta () const
void SetEffectColor1 (const RageColor &c)
void SetEffectColor2 (const RageColor &c)
void RecalcEffectPeriod ()
void SetEffectPeriod (float fTime)
float GetEffectPeriod () const
bool SetEffectTiming (float ramp_toh, float at_half, float ramp_tof, float at_zero, float at_full, RString &err)
bool SetEffectHoldAtFull (float haf, RString &err)
void SetEffectOffset (float fTime)
void SetEffectClock (EffectClock c)
void SetEffectClockString (const RString &s)
void SetEffectMagnitude (const RageVector3 &vec)
RageVector3 GetEffectMagnitude () const
void ResetEffectTimeIfDifferent (Effect new_effect)
void SetEffectDiffuseBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectDiffuseRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowBlink (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowShift (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectGlowRamp (float fEffectPeriodSeconds, const RageColor &c1, const RageColor &c2)
void SetEffectRainbow (float fEffectPeriodSeconds)
void SetEffectWag (float fPeriod, const RageVector3 &vect)
void SetEffectBounce (float fPeriod, const RageVector3 &vect)
void SetEffectBob (float fPeriod, const RageVector3 &vect)
void SetEffectPulse (float fPeriod, float fMinZoom, float fMaxZoom)
void SetEffectSpin (const RageVector3 &vect)
void SetEffectVibrate (const RageVector3 &vect)
bool GetVisible () const
Determine if the Actor is visible at this time.
void SetVisible (bool b)
void SetShadowLength (float fLength)
void SetShadowLengthX (float fLengthX)
void SetShadowLengthY (float fLengthY)
void SetShadowColor (const RageColor &c)
void SetHibernate (float fSecs)
void SetDrawOrder (int iOrder)
int GetDrawOrder () const
virtual void EnableAnimation (bool b)
void StartAnimating ()
void StopAnimating ()
void SetBlendMode (BlendMode mode)
void SetTextureTranslate (float x, float y)
void SetTextureWrapping (bool b)
void SetTextureFiltering (bool b)
void SetClearZBuffer (bool b)
void SetUseZBuffer (bool b)
void SetZBias (float f)
virtual void SetCullMode (CullMode mode)
virtual void PushContext (lua_State *L)
void AddCommand (const RString &sCmdName, apActorCommands apac, bool warn=true)
bool HasCommand (const RString &sCmdName) const
const apActorCommands * GetCommand (const RString &sCommandName) const
void PlayCommand (const RString &sCommandName)
void PlayCommandNoRecurse (const Message &msg)
void RunCommands (const apActorCommands &cmds, const LuaReference *pParamTable=nullptr)
virtual int GetNumStates () const
virtual void SetState (int)
virtual float GetAnimationLengthSeconds () const
virtual void SetSecondsIntoAnimation (float)
Public Member Functions inherited from MessageSubscriber
MessageSubscriber ()
MessageSubscriber (const MessageSubscriber &cpy)
MessageSubscriber & operator= (const MessageSubscriber &cpy)
void SubscribeToMessage (MessageID message)
void SubscribeToMessage (const RString &sMessageName)
void UnsubscribeAll ()
Public Member Functions inherited from IMessageSubscriber
virtual ~IMessageSubscriber ()=default
void ClearMessages (const RString &sMessage="")
Protected Member Functions
virtual bool GenericTweenOn () const
virtual bool GenericTweenOff () const
void UpdateSelectButton (PlayerNumber pn, bool bBeingPressed)
void ChangeSteps (PlayerNumber pn, int dir)
void AfterStepsOrTrailChange (const vector< PlayerNumber > &vpns)
void SwitchToPreferredDifficulty ()
void AfterMusicChange ()
void CheckBackgroundRequests (bool bForce)
bool DetectCodes (const InputEventPlus &input)
bool CanChangeSong () const
bool CanChangeSteps () const
SelectionState GetNextSelectionState () const
Protected Member Functions inherited from ScreenWithMenuElements
RString HandleLuaMusicFile (RString const &path)
void SetHelpText (const RString &s)
Protected Member Functions inherited from ActorFrame
void LoadChildrenFromNode (const XNode *pNode)
Protected Member Functions inherited from Actor
float GetEffectDeltaTime () const
Protected Attributes
vector< Steps * > m_vpSteps
int m_iSelection [NUM_PLAYERS]
RageTimer m_timerIdleComment
ThemeMetric< float > IDLE_COMMENT_SECONDS
ThemeMetric< float > SAMPLE_MUSIC_DELAY_INIT
ThemeMetric< float > SAMPLE_MUSIC_DELAY
ThemeMetric< bool > SAMPLE_MUSIC_LOOPS
ThemeMetric< SampleMusicPreviewMode > SAMPLE_MUSIC_PREVIEW_MODE
ThemeMetric< float > SAMPLE_MUSIC_FALLBACK_FADE_IN_SECONDS
ThemeMetric< float > SAMPLE_MUSIC_FADE_OUT_SECONDS
ThemeMetric< bool > DO_ROULETTE_ON_MENU_TIMER
ThemeMetric< float > ROULETTE_TIMER_SECONDS
ThemeMetric< bool > ALIGN_MUSIC_BEATS
ThemeMetric< RString > CODES
ThemeMetric< RString > MUSIC_WHEEL_TYPE
ThemeMetric< bool > OPTIONS_MENU_AVAILABLE
ThemeMetric< bool > SELECT_MENU_AVAILABLE
ThemeMetric< bool > MODE_MENU_AVAILABLE
ThemeMetric< bool > USE_OPTIONS_LIST
ThemeMetric< float > OPTIONS_LIST_TIMEOUT
ThemeMetric< bool > USE_PLAYER_SELECT_MENU
ThemeMetric< RString > SELECT_MENU_NAME
ThemeMetric< bool > SELECT_MENU_CHANGES_DIFFICULTY
ThemeMetric< bool > TWO_PART_SELECTION
ThemeMetric< bool > TWO_PART_CONFIRMS_ONLY
ThemeMetric< float > TWO_PART_TIMER_SECONDS
ThemeMetric< bool > WRAP_CHANGE_STEPS
ThemeMetric< bool > CHANGE_STEPS_WITH_GAME_BUTTONS
ThemeMetric< bool > CHANGE_GROUPS_WITH_GAME_BUTTONS
ThemeMetric< RString > NULL_SCORE_STRING
ThemeMetric< bool > PLAY_SOUND_ON_ENTERING_OPTIONS_MENU
GameButton m_GameButtonPreviousSong
GameButton m_GameButtonNextSong
GameButton m_GameButtonPreviousDifficulty
GameButton m_GameButtonNextDifficulty
GameButton m_GameButtonPreviousGroup
GameButton m_GameButtonNextGroup
RString m_sSectionMusicPath
RString m_sSortMusicPath
RString m_sRouletteMusicPath
RString m_sRandomMusicPath
RString m_sCourseMusicPath
RString m_sLoopMusicPath
RString m_sFallbackCDTitlePath
FadingBanner m_Banner
Sprite m_sprCDTitleFront
Sprite m_sprCDTitleBack
AutoActor m_sprHighScoreFrame [NUM_PLAYERS]
BitmapText m_textHighScore [NUM_PLAYERS]
MusicWheel m_MusicWheel
OptionsList m_OptionsList [NUM_PLAYERS]
SelectionState m_SelectionState
bool m_bStepsChosen [NUM_PLAYERS]
bool m_bGoToOptions
RString m_sSampleMusicToPlay
TimingData * m_pSampleMusicTimingData
float m_fSampleStartSeconds
float m_fSampleLengthSeconds
bool m_bAllowOptionsMenu
bool m_bAllowOptionsMenuRepeat
bool m_bSelectIsDown [NUM_PLAYERS]
bool m_bAcceptSelectRelease [NUM_PLAYERS]
RageSound m_soundStart
RageSound m_soundDifficultyEasier
RageSound m_soundDifficultyHarder
RageSound m_soundOptionsChange
RageSound m_soundLocked
BackgroundLoader m_BackgroundLoader
RageTexturePreloader m_TexturePreload
Song * m_pSongAwaitingDeletionConfirmation
Protected Attributes inherited from ScreenWithMenuElements
AutoActor m_sprUnderlay
MenuTimer * m_MenuTimer
AutoActor m_sprOverlay
vector< Actor * > m_vDecorations
Transition m_In
Transition m_Out
Transition m_Cancel
ThemeMetric< bool > PLAY_MUSIC
ThemeMetric< bool > MUSIC_ALIGN_BEAT
ThemeMetric< float > DELAY_MUSIC_SECONDS
ThemeMetric< bool > CANCEL_TRANSITIONS_OUT
ThemeMetric< float > TIMER_SECONDS
ThemeMetric< RString > TIMER_METRICS_GROUP
ThemeMetric< bool > RESET_GAMESTATE
Protected Attributes inherited from Screen
vector< QueuedScreenMessage > m_QueuedMessages
The list of messages that are sent to a Screen.
InputQueueCodeSet m_Codes
ThemeMetric< bool > ALLOW_OPERATOR_MENU_BUTTON
Do we allow the operator menu button to be pressed here?
ThemeMetric< bool > HANDLE_BACK_BUTTON
Do we handle the back button being pressed here?
ThemeMetric< float > REPEAT_RATE
ThemeMetric< float > REPEAT_DELAY
RString m_sNextScreen
The next screen to go to once this screen is done.
RString m_sPrevScreen
ScreenMessage m_smSendOnPop
float m_fLockInputSecs
bool m_bRunning
Protected Attributes inherited from ActorFrame
vector< Actor * > m_SubActors
The children Actors used by the ActorFrame.
bool m_bPropagateCommands
bool m_bDeleteChildren
bool m_bDrawByZPosition
LuaReference m_UpdateFunction
LuaReference m_DrawFunction
float m_fUpdateRate
float m_fFOV
float m_fVanishX
float m_fVanishY
bool m_bOverrideLighting
A flad to see if an override for the lighting is needed.
bool m_bLighting
RageColor m_ambientColor
RageColor m_diffuseColor
RageColor m_specularColor
RageVector3 m_lightDirection
Protected Attributes inherited from Actor
RString m_sName
the name of the Actor.
Actor * m_pParent
the current parent of this Actor if it exists.
Actor * m_FakeParent
vector< Actor * > m_WrapperStates
RageVector3 m_baseRotation
RageVector3 m_baseScale
float m_fBaseAlpha
RageColor m_internalDiffuse
RageColor m_internalGlow
RageVector2 m_size
TweenState m_current
TweenState m_start
vector< TweenStateAndInfo * > m_Tweens
TweenState * m_pTempState
Temporary variables that are filled just before drawing.
bool m_bFirstUpdate
float m_fHorizAlign
The particular horizontal alignment.
float m_fVertAlign
The particular vertical alignment.
Effect m_Effect
float m_fSecsIntoEffect
float m_fEffectDelta
float m_effect_ramp_to_half
float m_effect_hold_at_half
float m_effect_ramp_to_full
float m_effect_hold_at_full
float m_effect_hold_at_zero
float m_fEffectOffset
float m_effect_period
EffectClock m_EffectClock
bool m_tween_uses_effect_delta
RageColor m_effectColor1
RageColor m_effectColor2
RageVector3 m_vEffectMagnitude
bool m_bVisible
bool m_bIsAnimating
float m_fHibernateSecondsLeft
float m_fShadowLengthX
float m_fShadowLengthY
RageColor m_ShadowColor
int m_iDrawOrder
The draw order priority.
BlendMode m_BlendMode
ZTestMode m_ZTestMode
CullMode m_CullMode
RageVector2 m_texTranslate
bool m_bTextureWrapping
bool m_bTextureFiltering
bool m_bClearZBuffer
bool m_bZWrite
float m_fZBias
The amount of bias.
Additional Inherited Members
Public Types inherited from Actor
enum Effect {
no_effect, diffuse_blink, diffuse_shift, diffuse_ramp,
glow_blink, glow_shift, glow_ramp, rainbow,
wag, bounce, bob, pulse,
spin, vibrate
}
The list of the different effects.
enum EffectClock {
CLOCK_TIMER, CLOCK_TIMER_GLOBAL, CLOCK_BGM_TIME, CLOCK_BGM_BEAT,
CLOCK_BGM_TIME_NO_OFFSET, CLOCK_BGM_BEAT_NO_OFFSET, CLOCK_BGM_BEAT_PLAYER1, CLOCK_BGM_BEAT_PLAYER2,
CLOCK_LIGHT_1 = 1000, CLOCK_LIGHT_LAST = 1100, NUM_CLOCKS
}
Various values an Actor's effect can be tied to.
enum StretchType { fit_inside, cover }
How do we handle stretching the Actor?
Static Public Member Functions inherited from Screen
static void InitScreen (Screen *pScreen)
Static Public Member Functions inherited from Actor
static void SetBGMTime (float fTime, float fBeat, float fTimeNoOffset, float fBeatNoOffset)
static void SetPlayerBGMBeat (PlayerNumber pn, float fBeat, float fBeatNoOffset)
static void SetBGMLight (int iLightNumber, float fCabinetLights)
Public Attributes inherited from ScreenWithMenuElements
bool m_bShouldAllowLateJoin
Public Attributes inherited from Actor
HiddenPtr< LuaClass > m_pLuaInstance
Static Protected Member Functions inherited from Screen
static bool SortMessagesByDelayRemaining (const QueuedScreenMessage &m1, const QueuedScreenMessage &m2)
Static Protected Attributes inherited from Actor
static float g_fCurrentBGMTime = 0
static float g_fCurrentBGMBeat
static float g_fCurrentBGMTimeNoOffset = 0
static float g_fCurrentBGMBeatNoOffset = 0
static vector< float > g_vfCurrentBGMBeatPlayer
static vector< float > g_vfCurrentBGMBeatPlayerNoOffset
Constructor & Destructor Documentation
~ScreenSelectMusic()
ScreenSelectMusic::~ScreenSelectMusic () override
References IMAGECACHE, LOG, RageLog::Trace(), and ImageCache::Undemand().
Member Function Documentation
AfterMusicChange()
void ScreenSelectMusic::AfterMusicChange () protected
References BackgroundLoader::Abort(), AfterStepsOrTrailChange(), BackgroundLoader::CacheFile(), FAIL_M, FOREACH_HumanPlayer, FOREACH_PlayerNumber, FT_Sound, g_bBannerWaiting, g_bCDTitleWaiting, g_bSampleMusicWaiting, g_bWantFallbackCdTitle, g_StartedLoadingAt, GAMESTATE, Song::GetBannerPath(), Song::GetCDTitlePath(), MusicWheel::GetCurWheelItemData(), ActorUtil::GetFileType(), GameSoundManager::GetMusicPath(), GetMusicWheel(), SongUtil::GetPlayableSteps(), Song::GetPreviewMusicPath(), Song::GetPreviewStartSeconds(), MusicWheel::GetSelectedSection(), MusicWheel::GetSelectedSong(), MusicWheel::GetSelectedType(), SongManager::GetSongGroupBannerPath(), WheelBase::IsMoving(), MusicWheel::IsRouletting(), RageTextureManager::IsTextureRegistered(), FadingBanner::LoadCustom(), FadingBanner::LoadFromCachedBanner(), FadingBanner::LoadFromSortOrder(), FadingBanner::LoadMode(), FadingBanner::LoadRandom(), FadingBanner::LoadRoulette(), LOG, m_BackgroundLoader, m_Banner, PrefsManager::m_bShowBanners, Song::m_fMusicSampleLengthSeconds, m_fSampleLengthSeconds, m_fSampleStartSeconds, m_iSelection, ScreenWithMenuElements::m_MenuTimer, m_MusicWheel, MusicWheelItemData::m_pAction, GameState::m_pCurSong, GameState::m_pPreferredSong, m_pSampleMusicTimingData, m_sLoopMusicPath, GameCommand::m_sName, Song::m_SongTiming, GameState::m_SortOrder, m_sprCDTitleBack, m_sprCDTitleFront, m_sRandomMusicPath, m_sRouletteMusicPath, m_sSampleMusicToPlay, m_sSectionMusicPath, m_sSortMusicPath, m_vpSteps, PREFSMAN, LuaHelpers::ReportScriptErrorFmt(), SAMPLE_MUSIC_PREVIEW_MODE, SampleMusicPreviewMode_LastSong, SampleMusicPreviewMode_Normal, SampleMusicPreviewMode_ScreenMusic, SampleMusicPreviewMode_StartToPreview, BroadcastOnChangePtr< T >::Set(), FadingBanner::SetMovingFast(), Sprite::SongBannerTexture(), SONGMAN, SORT_GROUP, SortOrder_Invalid, SOUND, ssprintf(), MenuTimer::Stall(), GameSoundManager::StopMusic(), SwitchToPreferredDifficulty(), TEXTUREMAN, RageTimer::Touch(), RageLog::Trace(), Sprite::UnloadTexture(), WheelItemDataType_Custom, WheelItemDataType_Portal, WheelItemDataType_Random, WheelItemDataType_Roulette, WheelItemDataType_Section, WheelItemDataType_Song, and WheelItemDataType_Sort.
Referenced by BeginScreen(), DetectCodes(), HandleMessage(), HandleScreenMessage(), and Input().
AfterStepsOrTrailChange()
void ScreenSelectMusic::AfterStepsOrTrailChange (const vector< PlayerNumber > & vpns) protected
References ASSERT, MessageManager::Broadcast(), CLAMP(), FOREACH_CONST, GAMESTATE, ProfileManager::GetProfile(), HighScore::GetScore(), Profile::GetStepsHighScoreList(), HighScoreList::GetTopScore(), GameState::IsHumanPlayer(), m_iSelection, GameState::m_pCurSong, GameState::m_pCurSteps, m_SelectionState, m_textHighScore, m_vpSteps, MESSAGEMAN, NULL_SCORE_STRING, NUM_SCORE_DIGITS, PROFILEMAN, SelectionState_SelectingSong, SelectionState_SelectingSteps, BitmapText::SetText(), ssprintf(), and TWO_PART_CONFIRMS_ONLY.
Referenced by AfterMusicChange(), and ChangeSteps().
AllowLateJoin()
bool ScreenSelectMusic::AllowLateJoin () const inline override virtual
Determine if we allow extra players to join in on this screen.
Returns
false, for players should never be able to join while in progress.
Reimplemented from Screen.
BeginScreen()
void ScreenSelectMusic::BeginScreen () override virtual
This is called immediately before the screen is used.
Reimplemented from Screen.
References AfterMusicChange(), CommonMetrics::AUTO_SET_STYLE, ScreenWithMenuElements::BeginScreen(), MusicWheel::BeginScreen(), Profile::FavoritedCharts, FOREACH_ENUM, FOREACH_PlayerNumber, g_ScreenStartedLoadingAt, GAMEMAN, GAMESTATE, GameState::GetCurrentStyle(), RageTimer::GetDeltaTime(), GameManager::GetFirstCompatibleStyle(), GameState::GetNumSidesJoined(), ProfileManager::GetProfile(), GameManager::GetStepsTypesForGame(), Profile::goalmap, GameState::IsHumanPlayer(), GameState::isplaylistcourse, GameState::IsPlaylistCourse(), ThemeMetric< T >::Load(), LOG, m_bAllowOptionsMenu, m_bAllowOptionsMenuRepeat, m_bGoToOptions, m_bStepsChosen, m_iSelection, m_MusicWheel, m_OptionsList, GameState::m_pCurGame, GameState::m_PlayMode, m_SelectionState, Actor::m_sName, m_sprHighScoreFrame, Game::m_szName, m_textHighScore, m_timerIdleComment, SongManager::MakeSongGroupsFromPlaylists(), OPTIONS_MENU_AVAILABLE, PLAY_MODE_REGULAR, Actor::PlayCommand(), PLAYER_1, PLAYER_INVALID, SongManager::playlistcourse, PlayMode_Invalid, GameSoundManager::PlayOnceFromAnnouncer(), PROFILEMAN, OptionsList::Reset(), SCREENMAN, SelectionState_SelectingSong, BroadcastOnChange< T >::Set(), GameState::SetCompatibleStylesForPlayers(), GameState::SetCurrentStyle(), SongManager::SetFavoritedStatus(), SongManager::SetHasGoal(), ScreenManager::SetNewScreen(), Actor::SetVisible(), SONGMAN, SOUND, ssprintf(), RageTimer::Touch(), RageLog::Trace(), USE_OPTIONS_LIST, RageLog::Warn(), and ZERO.
can_open_options_list()
bool ScreenSelectMusic::can_open_options_list (PlayerNumber pn)
References m_OptionsList, NUM_PLAYERS, and USE_OPTIONS_LIST.
Referenced by LunaScreenSelectMusic::CanOpenOptionsList(), and LunaScreenSelectMusic::OpenOptionsList().
CanChangeSong()
bool ScreenSelectMusic::CanChangeSong () const inline protected
References m_SelectionState, and SelectionState_SelectingSong.
Referenced by UpdateSelectButton().
CanChangeSteps()
bool ScreenSelectMusic::CanChangeSteps () const inline protected
References m_SelectionState, SelectionState_SelectingSong, and SelectionState_SelectingSteps.
ChangeSteps()
void ScreenSelectMusic::ChangeSteps (PlayerNumber pn, int dir) protected
References AfterStepsOrTrailChange(), ASSERT, CommonMetrics::AUTO_SET_STYLE, MessageManager::Broadcast(), GameState::ChangePreferredDifficulty(), GameState::ChangePreferredDifficultyAndStepsType(), CLAMP(), GameState::DifficultiesLocked(), GameState::ForceOtherPlayersToCompatibleSteps(), FOREACH_HumanPlayer, GAMESTATE, Steps::GetDifficulty(), GameSoundManager::GetPlayerBalance(), GameState::IsHumanPlayer(), LOG, m_iSelection, GameState::m_pCurSong, m_soundDifficultyEasier, m_soundDifficultyHarder, Steps::m_StepsType, m_vpSteps, MESSAGEMAN, RageSound::PlayCopy(), Message::SetParam(), RageSound::SetProperty(), RageLog::Trace(), wrap(), and WRAP_CHANGE_STEPS.
Referenced by DetectCodes(), and Input().
CheckBackgroundRequests()
void ScreenSelectMusic::CheckBackgroundRequests (bool bForce) protected
References RageTimer::Ago(), ALIGN_MUSIC_BEATS, GameSoundManager::PlayMusicParams::bAlignBeat, GameSoundManager::PlayMusicParams::bApplyMusicRate, GameSoundManager::PlayMusicParams::bForceLoop, RageTextureManager::DisableOddDimensionWarning(), DLMAN, RageTextureManager::EnableOddDimensionWarning(), GameSoundManager::PlayMusicParams::fFadeInLengthSeconds, GameSoundManager::PlayMusicParams::fFadeOutLengthSeconds, BackgroundLoader::FinishedWithCachedFile(), GameSoundManager::PlayMusicParams::fLengthSeconds, GameSoundManager::PlayMusicParams::fStartSecond, g_bBannerWaiting, g_bCDTitleWaiting, g_bSampleMusicWaiting, g_bWantFallbackCdTitle, g_sBannerPath, g_ScreenStartedLoadingAt, g_StartedLoadingAt, GAMESTATE, ActorFrame::GetTweenTimeLeft(), ScreenWithMenuElements::HandleLuaMusicFile(), IsAFile(), BackgroundLoader::IsCacheFileFinished(), WheelBase::IsSettled(), RageTextureManager::IsTextureRegistered(), FadingBanner::Load(), Sprite::Load(), m_BackgroundLoader, m_Banner, m_fSampleLengthSeconds, m_fSampleStartSeconds, m_MusicWheel, GameState::m_pCurSteps, m_pSampleMusicTimingData, m_sFallbackCDTitlePath, m_sLoopMusicPath, m_sprCDTitleBack, m_sprCDTitleFront, m_sSampleMusicToPlay, PLAYER_1, GameSoundManager::PlayMusic(), GameSoundManager::PlayMusicParams::pTiming, SAMPLE_MUSIC_DELAY, SAMPLE_MUSIC_DELAY_INIT, SAMPLE_MUSIC_FADE_OUT_SECONDS, SAMPLE_MUSIC_FALLBACK_FADE_IN_SECONDS, SAMPLE_MUSIC_LOOPS, GameSoundManager::PlayMusicParams::sFile, Sprite::SongBannerTexture(), SOUND, TEXTUREMAN, and WheelBase::WheelIsLocked().
Referenced by SelectCurrent(), and Update().
DetectCodes()
bool ScreenSelectMusic::DetectCodes (const InputEventPlus & input) protected
References AfterMusicChange(), MessageManager::Broadcast(), CHANGE_GROUPS_WITH_GAME_BUTTONS, CHANGE_STEPS_WITH_GAME_BUTTONS, MusicWheel::ChangeSort(), ChangeSteps(), GameInput::controller, CodeDetector::DetectAndAdjustMusicOptions(), CodeDetector::EnteredCloseFolder(), CodeDetector::EnteredModeMenu(), CodeDetector::EnteredNextGroup(), CodeDetector::EnteredNextSort(), CodeDetector::EnteredNextSteps(), CodeDetector::EnteredPrevGroup(), CodeDetector::EnteredPrevSteps(), InputEventPlus::GameI, MusicWheel::GetSelectedSection(), MusicWheel::JumpToNextGroup(), MusicWheel::JumpToPrevGroup(), m_MusicWheel, m_soundLocked, m_soundOptionsChange, MESSAGEMAN, MODE_MENU_AVAILABLE, MusicWheel::NextSort(), RageSound::Play(), InputEventPlus::pn, MusicWheel::SelectSection(), MusicWheel::SetOpenSection(), Message::SetParam(), and SORT_MODE_MENU.
Referenced by Input().
DifferentialReload()
void ScreenSelectMusic::DifferentialReload ()
References SongManager::DifferentialReload(), m_MusicWheel, MusicWheel::ReloadSongList(), and SONGMAN.
Referenced by Input().
GenericTweenOff()
virtual bool ScreenSelectMusic::GenericTweenOff () const inline protected virtual
GenericTweenOn()
virtual bool ScreenSelectMusic::GenericTweenOn () const inline protected virtual
GetGoToOptions()
bool ScreenSelectMusic::GetGoToOptions () const inline
References m_bGoToOptions.
Referenced by LunaScreenSelectMusic::GetGoToOptions().
GetMusicWheel()
MusicWheel* ScreenSelectMusic::GetMusicWheel () inline
References m_MusicWheel.
Referenced by AfterMusicChange(), LunaScreenSelectMusic::GetMusicWheel(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
GetNextSelectionState()
SelectionState ScreenSelectMusic::GetNextSelectionState () const inline protected
References m_SelectionState, SelectionState_Finalized, SelectionState_SelectingSong, and SelectionState_SelectingSteps.
Referenced by SelectCurrent().
GetSelectionState()
int ScreenSelectMusic::GetSelectionState ()
References m_SelectionState.
Referenced by LunaScreenSelectMusic::GetSelectionState().
HandleMessage()
void ScreenSelectMusic::HandleMessage (const Message & msg) override virtual
Reimplemented from ActorFrame.
References AfterMusicChange(), ASSERT, FOREACH_ENUM, GAMESTATE, GameState::GetMasterPlayerNumber(), Message::GetParam(), ActorFrame::HandleMessage(), GameState::HaveProfileToLoad(), GameState::LoadProfiles(), Screen::m_bRunning, m_iSelection, m_MusicWheel, GameState::m_pCurSteps, m_vpSteps, Message_PlayerJoined, MusicWheel::PlayerJoined(), SCREENMAN, and ScreenManager::ZeroNextUpdate().
HandleScreenMessage()
void ScreenSelectMusic::HandleScreenMessage (ScreenMessage SM) override virtual
Reimplemented from Screen.
References SongManager::activeplaylist, AfterMusicChange(), ANSWER_YES, MessageManager::Broadcast(), MusicWheel::ChangeMusic(), Screen::ClearMessageQueue(), CODES, DLMAN, DO_ROULETTE_ON_MENU_TIMER, MusicWheel::FinishChangingSorts(), GAMESTATE, SongManager::GetPlaylists(), MusicWheel::GetSelectedSong(), ActorFrame::GetTweenTimeLeft(), ScreenWithMenuElements::HandleScreenMessage(), MusicWheel::IsRouletting(), m_bAllowOptionsMenu, m_bAllowOptionsMenuRepeat, m_bGoToOptions, GameState::m_bInNetGameplay, ScreenWithMenuElements::m_MenuTimer, m_MusicWheel, MenuStart(), MESSAGEMAN, Playlist::name, OnConfirmSongDeletion(), OPTIONS_MENU_AVAILABLE, Actor::PlayCommand(), Screen::PostScreenMessage(), CodeDetector::RefreshCacheItems(), ROULETTE_TIMER_SECONDS, ScreenPrompt::s_LastAnswer, ScreenTextEntry::s_sLastAnswer, MenuTimer::SetSeconds(), SM_BeginFadingOut, SM_GainFocus, SM_GoToNextScreen, SM_GoToPrevScreen, SM_LoseFocus, SM_MenuTimer, SONGMAN, SOUND, MenuTimer::Start(), and GameSoundManager::StopMusic().
Init()
void ScreenSelectMusic::Init () override virtual
This is called immediately after construction, to allow initializing after all derived classes exist.
Don't call it directly; use InitScreen instead.
Reimplemented from Screen.
References ActorFrame::AddChild(), ALIGN_MUSIC_BEATS, InputScheme::ButtonNameToIndex(), CHANGE_GROUPS_WITH_GAME_BUTTONS, CHANGE_STEPS_WITH_GAME_BUTTONS, CODES, COMMAND, ImageCache::Demand(), DO_ROULETTE_ON_MENU_TIMER, FOREACH_ENUM, FOREACH_PlayerNumber, g_ScreenStartedLoadingAt, GameManager::GameAndStringToStyle(), GAMEMAN, GAMESTATE, GameManager::GetDefaultGame(), InputMapper::GetInputScheme(), ThemeManager::GetMetric(), ThemeManager::GetPathF(), ThemeManager::GetPathG(), ThemeManager::GetPathS(), IDLE_COMMENT_SECONDS, IMAGECACHE, IMGCACHE_OFF, ScreenWithMenuElements::Init(), INPUTMAPPER, GameState::JoinPlayer(), OptionsList::Link(), RageTexturePreloader::Load(), MusicWheel::Load(), AutoActor::Load(), OptionsList::Load(), Sprite::Load(), ThemeMetric< T >::Load(), RageSound::Load(), LOAD_ALL_COMMANDS_AND_SET_XY, ActorUtil::LoadAllCommands(), BitmapText::LoadFromFont(), GamePreferences::m_AutoPlay, m_bAcceptSelectRelease, m_Banner, m_bSelectIsDown, RageSoundLoadParams::m_bSupportPan, m_GameButtonNextDifficulty, m_GameButtonNextGroup, m_GameButtonNextSong, m_GameButtonPreviousDifficulty, m_GameButtonPreviousGroup, m_GameButtonPreviousSong, PrefsManager::m_ImageCache, m_MusicWheel, m_OptionsList, PlayerState::m_PlayerController, GameState::m_PlayMode, GameState::m_pPlayerState, m_sFallbackCDTitlePath, m_sLoopMusicPath, Actor::m_sName, m_soundDifficultyEasier, m_soundDifficultyHarder, m_soundLocked, m_soundOptionsChange, m_soundStart, m_sprCDTitleBack, m_sprCDTitleFront, m_sprHighScoreFrame, m_sRandomMusicPath, m_sRouletteMusicPath, m_sSectionMusicPath, m_sSortMusicPath, PrefsManager::m_sTestInitialScreen, m_textHighScore, m_TexturePreload, SongManager::MakeSongGroupsFromPlaylists(), Message_PlayerJoined, MODE_MENU_AVAILABLE, MUSIC_WHEEL_TYPE, NULL_SCORE_STRING, OPTIONS_LIST_TIMEOUT, PC_HUMAN, PC_REPLAY, PLAY_MODE_REGULAR, PLAY_SOUND_ON_ENTERING_OPTIONS_MENU, PLAYER_1, PLAYER_2, PLAYER_INVALID, PlayerNumberToString(), PREFSMAN, ROULETTE_TIMER_SECONDS, SAMPLE_MUSIC_DELAY, SAMPLE_MUSIC_DELAY_INIT, SAMPLE_MUSIC_FADE_OUT_SECONDS, SAMPLE_MUSIC_FALLBACK_FADE_IN_SECONDS, SAMPLE_MUSIC_LOOPS, SAMPLE_MUSIC_PREVIEW_MODE, SELECT_MENU_AVAILABLE, SELECT_MENU_CHANGES_DIFFICULTY, SELECT_MENU_NAME, BroadcastOnChange< T >::Set(), GameState::SetCurrentStyle(), Actor::SetDrawOrder(), GameState::SetMasterPlayerNumber(), Actor::SetName(), Sprite::SongBannerTexture(), SONGMAN, ActorFrame::SortByDrawOrder(), ssprintf(), MessageSubscriber::SubscribeToMessage(), THEME, RageTimer::Touch(), TWO_PART_CONFIRMS_ONLY, TWO_PART_SELECTION, TWO_PART_TIMER_SECONDS, USE_OPTIONS_LIST, USE_PLAYER_SELECT_MENU, and WRAP_CHANGE_STEPS.
Input()
bool ScreenSelectMusic::Input (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References SongManager::activeplaylist, Profile::AddGoal(), ScreenManager::AddNewScreenToTop(), Profile::AddToFavorites(), Profile::AddToPermaMirror(), AfterMusicChange(), RageTimer::Ago(), Profile::allplaylists, MessageManager::Broadcast(), DeviceInput::button, CHANGE_GROUPS_WITH_GAME_BUTTONS, CHANGE_STEPS_WITH_GAME_BUTTONS, MusicWheel::ChangeMusic(), WheelBase::ChangeMusicUnlessLocked(), ChangeSteps(), Screen::ClearMessageQueue(), DetectCodes(), DeviceInput::device, DEVICE_KEYBOARD, DEVICE_MOUSE, InputEventPlus::DeviceI, RageInput::DeviceInputToChar(), DifferentialReload(), DLMAN, FAIL_M, Profile::FavoritedCharts, FOREACH_ENUM, FOREACH_HumanPlayer, g_CanOpenOptionsList, GAME_BUTTON_LEFT, GAME_BUTTON_MENUDOWN, GAME_BUTTON_MENUUP, GAME_BUTTON_RIGHT, GAME_BUTTON_SELECT, GAME_BUTTON_START, GameButtonToString(), InputEventPlus::GameI, GAMESTATE, Preference< T >::Get(), Song::GetAllSteps(), RageTimer::GetDeltaTime(), Song::GetDisplayMainTitle(), InputMapper::GetInputScheme(), SongManager::GetPlaylists(), ProfileManager::GetProfile(), MenuTimer::GetSeconds(), MusicWheel::GetSelectedSong(), Song::GetSongDir(), ActorFrame::GetTweenTimeLeft(), LocalizedString::GetValue(), ThemeMetric< T >::GetValue(), IET_FIRST_PRESS, IET_RELEASE, IET_REPEAT, OptionsList::Input(), Screen::Input(), INPUTFILTER, INPUTMAN, INPUTMAPPER, InputFilter::IsBeingPressed(), InputMapper::IsBeingPressed(), Song::IsFavorited(), GameState::IsHumanPlayer(), Song::IsPermaMirror(), MusicWheel::IsRouletting(), WheelBase::IsSettled(), ScreenWithMenuElements::IsTransitioning(), GameInput::IsValid(), MusicWheel::JumpToNextGroup(), MusicWheel::JumpToPrevGroup(), KEY_BACK, KEY_F9, KEY_LCTRL, KEY_LSHIFT, KEY_RCTRL, KEY_RSHIFT, m_bAcceptSelectRelease, m_bAllowOptionsMenu, m_bAllowOptionsMenuRepeat, PrefsManager::m_bAllowSongDeletion, m_bGoToOptions, m_bSelectIsDown, PrefsManager::m_bShowNativeLanguage, m_bStepsChosen, m_GameButtonNextDifficulty, m_GameButtonNextGroup, m_GameButtonNextSong, m_GameButtonPreviousDifficulty, m_GameButtonPreviousGroup, m_GameButtonPreviousSong, ScreenWithMenuElements::m_MenuTimer, m_MusicWheel, m_OptionsList, GameState::m_pCurSong, GameState::m_pCurSteps, m_pSongAwaitingDeletionConfirmation, m_SelectionState, Song::m_sMainTitle, m_soundLocked, m_soundStart, m_timerIdleComment, SongManager::MakePlaylistFromFavorites(), MakeUpper(), InputEventPlus::MenuI, MESSAGEMAN, MODE_MENU_AVAILABLE, MOUSE_LEFT, MOUSE_WHEELDOWN, WheelBase::Move(), MusicWheel::NextSort(), OptionsList::Open(), OPTIONS_LIST_TIMEOUT, OPTIONS_MENU_AVAILABLE, PERMANENTLY_DELETE, RageSound::Play(), PLAY_SOUND_ON_ENTERING_OPTIONS_MENU, Actor::PlayCommand(), PLAYER_1, PLAYER_INVALID, InputEventPlus::pn, Screen::PostScreenMessage(), PREFSMAN, PROFILEMAN, ScreenPrompt::Prompt(), PROMPT_YES_NO, WheelBase::RebuildWheelItems(), SongManager::ReconcileChartKeysForReloadedSong(), Song::ReloadFromSongDir(), Profile::RemoveFromFavorites(), Profile::RemoveFromPermaMirror(), InputMapper::ResetKeyRepeat(), ProfileManager::SaveProfile(), SCREENMAN, SELECT_MENU_AVAILABLE, SELECT_MENU_CHANGES_DIFFICULTY, SELECT_MENU_NAME, SelectionState_Finalized, SelectionState_SelectingSong, SelectionState_SelectingSteps, MusicWheel::SelectSection(), Preference< T >::Set(), Song::SetFavorited(), Song::SetHasGoal(), MusicWheel::SetOpenSection(), Message::SetParam(), Song::SetPermaMirror(), SM_BeginFadingOut, SONGMAN, ssprintf(), ScreenManager::SystemMessage(), ScreenTextEntry::TextEntry(), RageTimer::Touch(), TWO_PART_CONFIRMS_ONLY, InputEventPlus::type, UpdateSelectButton(), USE_OPTIONS_LIST, and USE_PLAYER_SELECT_MENU.
MenuBack()
bool ScreenSelectMusic::MenuBack (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References BackgroundLoader::Abort(), ScreenWithMenuElements::Cancel(), m_BackgroundLoader, and SM_GoToPrevScreen.
MenuStart()
bool ScreenSelectMusic::MenuStart (const InputEventPlus & input) override virtual
Reimplemented from Screen.
References GAME_BUTTON_SELECT, IET_FIRST_PRESS, INPUTMAPPER, InputMapper::IsBeingPressed(), Screen::m_fLockInputSecs, PLAYER_INVALID, InputEventPlus::pn, SelectCurrent(), and InputEventPlus::type.
Referenced by HandleScreenMessage().
OnConfirmSongDeletion()
void ScreenSelectMusic::OnConfirmSongDeletion ()
References RageFileManager::DeleteRecursive(), FILEMAN, Preference< T >::Get(), Song::GetSongDir(), LOG, PrefsManager::m_bAllowSongDeletion, m_MusicWheel, m_pSongAwaitingDeletionConfirmation, PREFSMAN, MusicWheel::ReloadSongList(), SONGMAN, RageLog::Trace(), SongManager::UnlistSong(), and RageLog::Warn().
Referenced by HandleScreenMessage().
OpenOptionsList()
void ScreenSelectMusic::OpenOptionsList (PlayerNumber pn)
References m_MusicWheel, m_OptionsList, WheelBase::Move(), OptionsList::Open(), and PLAYER_INVALID.
Referenced by LunaScreenSelectMusic::OpenOptionsList().
PlayReplay()
void ScreenSelectMusic::PlayReplay (HighScore * score)
PushSelf()
void ScreenSelectMusic::PushSelf (lua_State * L) override virtual
Reimplemented from Screen.
SelectCurrent()
bool ScreenSelectMusic::SelectCurrent (PlayerNumber pn)
References BackgroundLoader::Abort(), MessageManager::Broadcast(), CheckBackgroundRequests(), OptionsList::Close(), DLMAN, f, GameState::ForceSharedSidesMatch(), FOREACH_ENUM, FOREACH_HumanPlayer, g_bBannerWaiting, g_bCDTitleWaiting, g_bSampleMusicWaiting, GAMESTATE, Preference< T >::Get(), GetNextSelectionState(), MenuTimer::GetSeconds(), MusicWheel::GetSelectedSong(), ActorFrame::GetTweenTimeLeft(), HARD_COMMENT_METER, GameState::IsEventMode(), ProfileManager::IsSongNew(), LOG, PrefsManager::m_AllowHoldForOptions, m_BackgroundLoader, m_bAllowOptionsMenu, m_bStepsChosen, ScreenWithMenuElements::m_MenuTimer, m_MusicWheel, m_OptionsList, GameState::m_pCurSteps, m_SelectionState, m_soundStart, StatsManager::m_vPlayedStageStats, max(), MESSAGEMAN, OPTIONS_MENU_AVAILABLE, RageSound::Play(), Actor::PlayCommand(), PLAYER_INVALID, GameSoundManager::PlayOnceFromAnnouncer(), Screen::PostScreenMessage(), PREFSMAN, PROFILEMAN, SAMPLE_MUSIC_PREVIEW_MODE, SampleMusicPreviewMode_StartToPreview, MusicWheel::Select(), SelectionState_Finalized, SelectionState_SelectingSong, SelectionState_SelectingSteps, SelectionStateToString(), GameState::SetCompatibleStylesForPlayers(), Message::SetParam(), MenuTimer::SetSeconds(), SHOW_OPTIONS_MESSAGE_SECONDS, SM_BeginFadingOut, SM_None, SOUND, MenuTimer::Start(), ScreenWithMenuElements::StartTransitioningScreen(), STATSMAN, MenuTimer::Stop(), TWO_PART_CONFIRMS_ONLY, TWO_PART_SELECTION, TWO_PART_TIMER_SECONDS, UpdateSelectButton(), and RageLog::Warn().
Referenced by MenuStart(), LunaScreenSelectMusic::PlayReplay(), LunaScreenSelectMusic::SelectCurrent(), and LunaScreenSelectMusic::StartPlaylistAsCourse().
StartPlayingMusic()
void ScreenSelectMusic::StartPlayingMusic () inline override virtual
Reimplemented from ScreenWithMenuElements.
SwitchToPreferredDifficulty()
void ScreenSelectMusic::SwitchToPreferredDifficulty () protected
References CLAMP(), GameState::DifficultiesLocked(), Difficulty_Invalid, FOREACH_CONST, FOREACH_HumanPlayer, GAMESTATE, GameState::GetMasterPlayerNumber(), m_iSelection, GameState::m_pCurSteps, GameState::m_PreferredDifficulty, GameState::m_PreferredStepsType, m_vpSteps, NUM_Difficulty, and StepsType_Invalid.
Referenced by AfterMusicChange().
Update()
void ScreenSelectMusic::Update (float fDeltaTime) override virtual
Reimplemented from Screen.
References CheckBackgroundRequests(), RageTimer::GetDeltaTime(), IDLE_COMMENT_SECONDS, ScreenWithMenuElements::IsTransitioning(), Actor::m_sName, m_timerIdleComment, RageTimer::PeekDeltaTime(), GameSoundManager::PlayOnceFromAnnouncer(), SOUND, and ScreenWithMenuElements::Update().
UpdateSelectButton()
void ScreenSelectMusic::UpdateSelectButton (PlayerNumber pn, bool bBeingPressed) protected
References MessageManager::Broadcast(), CanChangeSong(), m_bSelectIsDown, MESSAGEMAN, SELECT_MENU_AVAILABLE, and Message::SetParam().
Referenced by Input(), and SelectCurrent().
Member Data Documentation
ALIGN_MUSIC_BEATS
ThemeMetric<bool> ScreenSelectMusic::ALIGN_MUSIC_BEATS protected
Referenced by CheckBackgroundRequests(), and Init().
CHANGE_GROUPS_WITH_GAME_BUTTONS
ThemeMetric<bool> ScreenSelectMusic::CHANGE_GROUPS_WITH_GAME_BUTTONS protected
Referenced by DetectCodes(), Init(), and Input().
CHANGE_STEPS_WITH_GAME_BUTTONS
ThemeMetric<bool> ScreenSelectMusic::CHANGE_STEPS_WITH_GAME_BUTTONS protected
Referenced by DetectCodes(), Init(), and Input().
CODES
ThemeMetric<RString> ScreenSelectMusic::CODES protected
Referenced by HandleScreenMessage(), and Init().
DO_ROULETTE_ON_MENU_TIMER
ThemeMetric<bool> ScreenSelectMusic::DO_ROULETTE_ON_MENU_TIMER protected
Referenced by HandleScreenMessage(), and Init().
IDLE_COMMENT_SECONDS
ThemeMetric<float> ScreenSelectMusic::IDLE_COMMENT_SECONDS protected
Referenced by Init(), and Update().
m_bAcceptSelectRelease
bool ScreenSelectMusic::m_bAcceptSelectRelease[NUM_PLAYERS] protected
Referenced by Init(), and Input().
m_BackgroundLoader
BackgroundLoader ScreenSelectMusic::m_BackgroundLoader protected
Referenced by AfterMusicChange(), CheckBackgroundRequests(), MenuBack(), and SelectCurrent().
m_bAllowOptionsMenu
bool ScreenSelectMusic::m_bAllowOptionsMenu protected
Referenced by BeginScreen(), HandleScreenMessage(), Input(), and SelectCurrent().
m_bAllowOptionsMenuRepeat
bool ScreenSelectMusic::m_bAllowOptionsMenuRepeat protected
Referenced by BeginScreen(), HandleScreenMessage(), and Input().
m_Banner
FadingBanner ScreenSelectMusic::m_Banner protected
Referenced by AfterMusicChange(), CheckBackgroundRequests(), and Init().
m_bGoToOptions
bool ScreenSelectMusic::m_bGoToOptions protected
Referenced by BeginScreen(), GetGoToOptions(), HandleScreenMessage(), and Input().
m_bSelectIsDown
bool ScreenSelectMusic::m_bSelectIsDown[NUM_PLAYERS] protected
Referenced by Init(), Input(), and UpdateSelectButton().
m_bStepsChosen
bool ScreenSelectMusic::m_bStepsChosen[NUM_PLAYERS] protected
Referenced by BeginScreen(), Input(), and SelectCurrent().
m_fSampleLengthSeconds
float ScreenSelectMusic::m_fSampleLengthSeconds protected
Referenced by AfterMusicChange(), and CheckBackgroundRequests().
m_fSampleStartSeconds
float ScreenSelectMusic::m_fSampleStartSeconds protected
Referenced by AfterMusicChange(), and CheckBackgroundRequests().
m_GameButtonNextDifficulty
GameButton ScreenSelectMusic::m_GameButtonNextDifficulty protected
Referenced by Init(), and Input().
m_GameButtonNextGroup
GameButton ScreenSelectMusic::m_GameButtonNextGroup protected
Referenced by Init(), and Input().
m_GameButtonNextSong
GameButton ScreenSelectMusic::m_GameButtonNextSong protected
Referenced by Init(), and Input().
m_GameButtonPreviousDifficulty
GameButton ScreenSelectMusic::m_GameButtonPreviousDifficulty protected
Referenced by Init(), and Input().
m_GameButtonPreviousGroup
GameButton ScreenSelectMusic::m_GameButtonPreviousGroup protected
Referenced by Init(), and Input().
m_GameButtonPreviousSong
GameButton ScreenSelectMusic::m_GameButtonPreviousSong protected
Referenced by Init(), and Input().
m_iSelection
int ScreenSelectMusic::m_iSelection[NUM_PLAYERS] protected
Referenced by AfterMusicChange(), AfterStepsOrTrailChange(), BeginScreen(), ChangeSteps(), HandleMessage(), and SwitchToPreferredDifficulty().
m_MusicWheel
MusicWheel ScreenSelectMusic::m_MusicWheel protected
Referenced by AfterMusicChange(), BeginScreen(), CheckBackgroundRequests(), DetectCodes(), DifferentialReload(), GetMusicWheel(), HandleMessage(), HandleScreenMessage(), Init(), Input(), OnConfirmSongDeletion(), OpenOptionsList(), and SelectCurrent().
m_OptionsList
OptionsList ScreenSelectMusic::m_OptionsList[NUM_PLAYERS] protected
Referenced by BeginScreen(), can_open_options_list(), Init(), Input(), OpenOptionsList(), and SelectCurrent().
m_pSampleMusicTimingData
TimingData* ScreenSelectMusic::m_pSampleMusicTimingData protected
Referenced by AfterMusicChange(), and CheckBackgroundRequests().
m_pSongAwaitingDeletionConfirmation
Song* ScreenSelectMusic::m_pSongAwaitingDeletionConfirmation protected
Referenced by Input(), and OnConfirmSongDeletion().
m_sCourseMusicPath
RString ScreenSelectMusic::m_sCourseMusicPath protected
m_SelectionState
SelectionState ScreenSelectMusic::m_SelectionState protected
Referenced by AfterStepsOrTrailChange(), BeginScreen(), CanChangeSong(), CanChangeSteps(), GetNextSelectionState(), GetSelectionState(), Input(), and SelectCurrent().
m_sFallbackCDTitlePath
RString ScreenSelectMusic::m_sFallbackCDTitlePath protected
Referenced by CheckBackgroundRequests(), and Init().
m_sLoopMusicPath
RString ScreenSelectMusic::m_sLoopMusicPath protected
Referenced by AfterMusicChange(), CheckBackgroundRequests(), and Init().
m_soundDifficultyEasier
RageSound ScreenSelectMusic::m_soundDifficultyEasier protected
Referenced by ChangeSteps(), and Init().
m_soundDifficultyHarder
RageSound ScreenSelectMusic::m_soundDifficultyHarder protected
Referenced by ChangeSteps(), and Init().
m_soundLocked
RageSound ScreenSelectMusic::m_soundLocked protected
Referenced by DetectCodes(), Init(), and Input().
m_soundOptionsChange
RageSound ScreenSelectMusic::m_soundOptionsChange protected
Referenced by DetectCodes(), and Init().
m_soundStart
RageSound ScreenSelectMusic::m_soundStart protected
Referenced by Init(), Input(), and SelectCurrent().
m_sprCDTitleBack
Sprite ScreenSelectMusic::m_sprCDTitleBack protected
Referenced by AfterMusicChange(), CheckBackgroundRequests(), and Init().
m_sprCDTitleFront
Sprite ScreenSelectMusic::m_sprCDTitleFront protected
Referenced by AfterMusicChange(), CheckBackgroundRequests(), and Init().
m_sprHighScoreFrame
AutoActor ScreenSelectMusic::m_sprHighScoreFrame[NUM_PLAYERS] protected
Referenced by BeginScreen(), and Init().
m_sRandomMusicPath
RString ScreenSelectMusic::m_sRandomMusicPath protected
Referenced by AfterMusicChange(), and Init().
m_sRouletteMusicPath
RString ScreenSelectMusic::m_sRouletteMusicPath protected
Referenced by AfterMusicChange(), and Init().
m_sSampleMusicToPlay
RString ScreenSelectMusic::m_sSampleMusicToPlay protected
Referenced by AfterMusicChange(), and CheckBackgroundRequests().
m_sSectionMusicPath
RString ScreenSelectMusic::m_sSectionMusicPath protected
Referenced by AfterMusicChange(), and Init().
m_sSortMusicPath
RString ScreenSelectMusic::m_sSortMusicPath protected
Referenced by AfterMusicChange(), and Init().
m_textHighScore
BitmapText ScreenSelectMusic::m_textHighScore[NUM_PLAYERS] protected
Referenced by AfterStepsOrTrailChange(), BeginScreen(), and Init().
m_TexturePreload
RageTexturePreloader ScreenSelectMusic::m_TexturePreload protected
Referenced by Init().
m_timerIdleComment
RageTimer ScreenSelectMusic::m_timerIdleComment protected
Referenced by BeginScreen(), Input(), and Update().
m_vpSteps
vector<Steps*> ScreenSelectMusic::m_vpSteps protected
Referenced by AfterMusicChange(), AfterStepsOrTrailChange(), ChangeSteps(), HandleMessage(), and SwitchToPreferredDifficulty().
MODE_MENU_AVAILABLE
ThemeMetric<bool> ScreenSelectMusic::MODE_MENU_AVAILABLE protected
Referenced by DetectCodes(), Init(), and Input().
MUSIC_WHEEL_TYPE
ThemeMetric<RString> ScreenSelectMusic::MUSIC_WHEEL_TYPE protected
Referenced by Init().
NULL_SCORE_STRING
ThemeMetric<RString> ScreenSelectMusic::NULL_SCORE_STRING protected
Referenced by AfterStepsOrTrailChange(), and Init().
OPTIONS_LIST_TIMEOUT
ThemeMetric<float> ScreenSelectMusic::OPTIONS_LIST_TIMEOUT protected
Referenced by Init(), and Input().
OPTIONS_MENU_AVAILABLE
ThemeMetric<bool> ScreenSelectMusic::OPTIONS_MENU_AVAILABLE protected
Referenced by BeginScreen(), HandleScreenMessage(), Input(), and SelectCurrent().
PLAY_SOUND_ON_ENTERING_OPTIONS_MENU
ThemeMetric<bool> ScreenSelectMusic::PLAY_SOUND_ON_ENTERING_OPTIONS_MENU protected
Referenced by Init(), and Input().
ROULETTE_TIMER_SECONDS
ThemeMetric<float> ScreenSelectMusic::ROULETTE_TIMER_SECONDS protected
Referenced by HandleScreenMessage(), and Init().
SAMPLE_MUSIC_DELAY
ThemeMetric<float> ScreenSelectMusic::SAMPLE_MUSIC_DELAY protected
Referenced by CheckBackgroundRequests(), and Init().
SAMPLE_MUSIC_DELAY_INIT
ThemeMetric<float> ScreenSelectMusic::SAMPLE_MUSIC_DELAY_INIT protected
Referenced by CheckBackgroundRequests(), and Init().
SAMPLE_MUSIC_FADE_OUT_SECONDS
ThemeMetric<float> ScreenSelectMusic::SAMPLE_MUSIC_FADE_OUT_SECONDS protected
Referenced by CheckBackgroundRequests(), and Init().
SAMPLE_MUSIC_FALLBACK_FADE_IN_SECONDS
ThemeMetric<float> ScreenSelectMusic::SAMPLE_MUSIC_FALLBACK_FADE_IN_SECONDS protected
Referenced by CheckBackgroundRequests(), and Init().
SAMPLE_MUSIC_LOOPS
ThemeMetric<bool> ScreenSelectMusic::SAMPLE_MUSIC_LOOPS protected
Referenced by CheckBackgroundRequests(), and Init().
SAMPLE_MUSIC_PREVIEW_MODE
ThemeMetric<SampleMusicPreviewMode> ScreenSelectMusic::SAMPLE_MUSIC_PREVIEW_MODE protected
Referenced by AfterMusicChange(), Init(), and SelectCurrent().
SELECT_MENU_AVAILABLE
ThemeMetric<bool> ScreenSelectMusic::SELECT_MENU_AVAILABLE protected
Referenced by Init(), Input(), and UpdateSelectButton().
SELECT_MENU_CHANGES_DIFFICULTY
ThemeMetric<bool> ScreenSelectMusic::SELECT_MENU_CHANGES_DIFFICULTY protected
Referenced by Init(), and Input().
SELECT_MENU_NAME
ThemeMetric<RString> ScreenSelectMusic::SELECT_MENU_NAME protected
Referenced by Init(), and Input().
TWO_PART_CONFIRMS_ONLY
ThemeMetric<bool> ScreenSelectMusic::TWO_PART_CONFIRMS_ONLY protected
Referenced by AfterStepsOrTrailChange(), Init(), Input(), and SelectCurrent().
TWO_PART_SELECTION
ThemeMetric<bool> ScreenSelectMusic::TWO_PART_SELECTION protected
Referenced by Init(), and SelectCurrent().
TWO_PART_TIMER_SECONDS
ThemeMetric<float> ScreenSelectMusic::TWO_PART_TIMER_SECONDS protected
Referenced by Init(), and SelectCurrent().
USE_OPTIONS_LIST
ThemeMetric<bool> ScreenSelectMusic::USE_OPTIONS_LIST protected
Referenced by BeginScreen(), can_open_options_list(), Init(), and Input().
USE_PLAYER_SELECT_MENU
ThemeMetric<bool> ScreenSelectMusic::USE_PLAYER_SELECT_MENU protected
Referenced by Init(), and Input().
WRAP_CHANGE_STEPS
ThemeMetric<bool> ScreenSelectMusic::WRAP_CHANGE_STEPS protected
Referenced by ChangeSteps(), and Init().
The documentation for this class was generated from the following files:
ScreenSelectMusic.h
ScreenSelectMusic.cpp