Etterna: RageFileObjTimeout Class Reference
RageFileObjTimeout Class Reference
Public Member Functions
RageFileObjTimeout (ThreadedFileWorker *pWorker, RageFileBasic *pFile, int iSize, int iMode)
~RageFileObjTimeout () override
int GetFileSize () const override
int GetFD () override
RageFileBasic * Copy () const override
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
RString GetDisplayPath () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Protected Member Functions
int SeekInternal (int iPos) override
int ReadInternal (void *pBuffer, size_t iBytes) override
int WriteInternal (const void *pBuffer, size_t iBytes) override
int FlushInternal () override
Protected Member Functions inherited from RageFileObj
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes
RageFileBasic * m_pFile
ThreadedFileWorker * m_pWorker
int m_iFileSize
int m_iMode
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileObjTimeout()
RageFileObjTimeout::RageFileObjTimeout (ThreadedFileWorker * pWorker, RageFileBasic * pFile, int iSize, int iMode) inline
References RageFileObj::EnableReadBuffering(), RageFileObj::EnableWriteBuffering(), m_iFileSize, m_iMode, m_pFile, m_pWorker, RageFile::READ, and RageFile::WRITE.
Referenced by Copy().
~RageFileObjTimeout()
RageFileObjTimeout::~RageFileObjTimeout () inline override
References ThreadedFileWorker::Close(), RageFileObj::Flush(), m_pFile, and m_pWorker.
Member Function Documentation
Copy()
RageFileBasic* RageFileObjTimeout::Copy () const inline override virtual
Reimplemented from RageFileObj.
References ThreadedFileWorker::Copy(), m_iFileSize, m_iMode, m_pFile, m_pWorker, and RageFileObjTimeout().
FlushInternal()
int RageFileObjTimeout::FlushInternal () inline override protected virtual
Reimplemented from RageFileObj.
References ThreadedFileWorker::Flush(), m_pFile, m_pWorker, and RageFileObj::SetError().
GetFD()
int RageFileObjTimeout::GetFD () inline override virtual
Reimplemented from RageFileObj.
References ThreadedFileWorker::GetFD(), m_pFile, m_pWorker, and RageFileObj::SetError().
GetFileSize()
int RageFileObjTimeout::GetFileSize () const inline override virtual
Implements RageFileObj.
References m_iFileSize.
ReadInternal()
int RageFileObjTimeout::ReadInternal (void * pBuffer, size_t iBytes) inline override protected virtual
Implements RageFileObj.
References m_pFile, m_pWorker, ThreadedFileWorker::Read(), and RageFileObj::SetError().
SeekInternal()
int RageFileObjTimeout::SeekInternal (int iPos) inline override protected virtual
Reimplemented from RageFileObj.
References m_pFile, m_pWorker, ThreadedFileWorker::Seek(), and RageFileObj::SetError().
WriteInternal()
int RageFileObjTimeout::WriteInternal (const void * pBuffer, size_t iBytes) inline override protected virtual
Implements RageFileObj.
References m_pFile, m_pWorker, RageFileObj::SetError(), and ThreadedFileWorker::Write().
Member Data Documentation
m_iFileSize
int RageFileObjTimeout::m_iFileSize protected
Referenced by Copy(), GetFileSize(), and RageFileObjTimeout().
m_iMode
int RageFileObjTimeout::m_iMode protected
Referenced by Copy(), and RageFileObjTimeout().
m_pFile
RageFileBasic* RageFileObjTimeout::m_pFile mutable protected
Referenced by Copy(), FlushInternal(), GetFD(), RageFileObjTimeout(), ReadInternal(), SeekInternal(), WriteInternal(), and ~RageFileObjTimeout().
m_pWorker
ThreadedFileWorker* RageFileObjTimeout::m_pWorker protected
Referenced by Copy(), FlushInternal(), GetFD(), RageFileObjTimeout(), ReadInternal(), SeekInternal(), WriteInternal(), and ~RageFileObjTimeout().
The documentation for this class was generated from the following file:
RageFileDriverTimeout.cpp