Etterna: RageFileDriver Class Reference
RageFileDriver Class Reference abstract
#include <RageFileDriver.h>
Public Types
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Member Functions
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual RageFileBasic * Open (const RString &sPath, int iMode, int &iError)=0
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void FlushDirCache (const RString &sPath)
virtual void CacheFile (const RString &)
virtual bool Move (const RString &, const RString &)
virtual bool Remove (const RString &)
virtual bool Remount (const RString &)
Public Attributes
FilenameDB * FDB
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ERROR_WRITING_NOT_SUPPORTED
Constructor & Destructor Documentation
RageFileDriver()
RageFileDriver::RageFileDriver (FilenameDB * pDB) inline
References FDB.
~RageFileDriver()
RageFileDriver::~RageFileDriver () virtual
References FDB.
Member Function Documentation
CacheFile()
virtual void RageFileDriver::CacheFile (const RString &) inline virtual
FlushDirCache()
void RageFileDriver::FlushDirCache (const RString & sPath) virtual
Reimplemented in RageFileDriverMountpoints, RageFileDriverMem, RageFileDriverZip, and RageFileDriverTimeout.
References FDB, and FilenameDB::FlushDirCache().
Referenced by RageFileDriverTimeout::FlushDirCache(), ThreadedFileWorker::HandleRequest(), and RageFileManager::Remount().
GetDirListing()
void RageFileDriver::GetDirListing (const RString & sPath, vector< RString > & asAddTo, bool bOnlyDirs, bool bReturnPathToo) virtual
References FDB, and FilenameDB::GetDirListing().
Referenced by DeleteRecursive(), RageFileManager::GetDirListing(), and GetDirListingRecursive().
GetFileHash()
int RageFileDriver::GetFileHash (const RString & sPath) virtual
References FDB, and FilenameDB::GetFileHash().
GetFileSizeInBytes()
int RageFileDriver::GetFileSizeInBytes (const RString & sFilePath) virtual
References FDB, and FilenameDB::GetFileSize().
GetFileType()
RageFileManager::FileType RageFileDriver::GetFileType (const RString & sPath) virtual
References FDB, and FilenameDB::GetFileType().
Referenced by GetDirListingRecursive(), GetPathValue(), RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), and RageFileDriverDirect::Remove().
GetPathValue()
int RageFileDriver::GetPathValue (const RString & sPath) virtual
References GetFileType(), split(), RageFileManager::TYPE_DIR, RageFileManager::TYPE_FILE, and RageFileManager::TYPE_NONE.
Referenced by RageFileManager::OpenForWriting().
Move()
virtual bool RageFileDriver::Move (const RString & , const RString &) inline virtual
Reimplemented in RageFileDriverDirectReadOnly, RageFileDriverTimeout, and RageFileDriverDirect.
Referenced by ThreadedFileWorker::HandleRequest().
Open()
virtual RageFileBasic* RageFileDriver::Open (const RString & sPath, int iMode, int & iError) pure virtual
Implemented in RageFileDriverMountpoints, RageFileDriverMem, RageFileDriverDirectReadOnly, RageFileDriverZip, RageFileDriverTimeout, and RageFileDriverDirect.
Referenced by ThreadedFileWorker::HandleRequest(), RageFileManager::OpenForReading(), and RageFileManager::OpenForWriting().
Remount()
virtual bool RageFileDriver::Remount (const RString &) inline virtual
Reimplemented in RageFileDriverDirect.
Referenced by RageFileManager::Remount().
Remove()
virtual bool RageFileDriver::Remove (const RString &) inline virtual
Reimplemented in RageFileDriverMem, RageFileDriverDirectReadOnly, RageFileDriverTimeout, and RageFileDriverDirect.
Referenced by ThreadedFileWorker::HandleRequest().
Member Data Documentation
FDB
FilenameDB* RageFileDriver::FDB
Referenced by FlushDirCache(), GetDirListing(), GetFileHash(), RageFileDriverZip::GetFileInfo(), GetFileSizeInBytes(), GetFileType(), ThreadedFileWorker::HandleRequest(), RageFileDriverMountpoints::LoadFromDrivers(), RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), RageFileDriverZip::Open(), RageFileDriverMem::Open(), RageFileDriverZip::ParseZipfile(), RageFileDriver(), RageFileDriverTimeout::RageFileDriverTimeout(), RageFileDriverDirect::Remount(), RageFileDriverDirect::Remove(), RageFileDriverMem::Remove(), and ~RageFileDriver().
The documentation for this class was generated from the following files:
RageFileDriver.h
RageFileDriver.cpp