Etterna: RageFileDriverDirectHelpers.h File Reference
RageFileDriverDirectHelpers.h File Reference
#include "RageUtil_FileDB.h"
Classes
class DirectFilenameDB
Macros
#define DoStat stat
#define DoMkdir mkdir
#define DoFindFirstFile FindFirstFile
#define DoRename rename
#define DoRemove remove
#define O_BINARY 0
Functions
RString DoPathReplace (const RString &sPath)
bool CreateDirectories (const RString &sPath)
Macro Definition Documentation
DoFindFirstFile
#define DoFindFirstFile FindFirstFile
Referenced by DirectFilenameDB::CacheFile(), and DirectFilenameDB::PopulateFileSet().
DoMkdir
#define DoMkdir mkdir
Referenced by CreateDirectories().
DoRemove
#define DoRemove remove
Referenced by RageFileDriverDirect::Remove(), and RageFileObjDirect::~RageFileObjDirect().
DoRename
#define DoRename rename
Referenced by RageFileDriverDirect::Move().
DoStat
#define DoStat stat
Referenced by DirectFilenameDB::CacheFile(), CreateDirectories(), and DirectFilenameDB::PopulateFileSet().
O_BINARY
#define O_BINARY 0
Referenced by MakeFileObjDirect().
Function Documentation
CreateDirectories()
bool CreateDirectories (const RString & sPath)
References DoMkdir, DoStat, StdString::CStdStr< CT >::Left(), split(), ssprintf(), and WARN.
Referenced by RageFileDriverDirect::Move(), RageFileDriverDirect::Open(), and RageFileDriverDirect::Remount().
DoPathReplace()
RString DoPathReplace (const RString & sPath)
Referenced by RageFileObjDirect::~RageFileObjDirect().