Etterna: Message Struct Reference
Message Struct Reference
#include <MessageManager.h>
Public Member Functions
Message (const RString &s)
Message (MessageID id)
Message (const RString &s, const LuaReference &params)
~Message ()
void SetName (const RString &sName)
RString GetName () const
bool IsBroadcast () const
void SetBroadcast (bool b)
void PushParamTable (lua_State *L)
const LuaReference & GetParamTable () const
void SetParamTable (const LuaReference &params)
void GetParamFromStack (lua_State *L, const RString &sName) const
void SetParamFromStack (lua_State *L, const RString &sName)
template<typename T >
bool GetParam (const RString &sName, T &val) const
template<typename T >
void SetParam (const RString &sName, const T &val)
template<typename T >
void SetParam (const RString &sName, const vector< T > &val)
bool operator== (const RString &s) const
bool operator== (MessageID id) const
Message (const Message &rhs)
Private Member Functions
Message & operator= (const Message &rhs)
Private Attributes
RString m_sName
LuaTable * m_pParams
bool m_bBroadcast
Constructor & Destructor Documentation
Message() [1/4]
Message::Message (const RString & s) explicit
References m_bBroadcast, m_pParams, and m_sName.
Message() [2/4]
Message::Message (MessageID id) explicit
References m_bBroadcast, m_pParams, m_sName, and MessageIDToString().
Message() [3/4]
Message::Message (const RString & s, const LuaReference & params)
References LuaManager::Get(), L, LUA, m_bBroadcast, m_pParams, m_sName, LuaReference::PushSelf(), LuaManager::Release(), and LuaReference::SetFromStack().
~Message()
Message::~Message ()
References m_pParams.
Message() [4/4]
Message::Message (const Message & rhs)
Member Function Documentation
GetName()
RString Message::GetName () const inline
References m_sName.
Referenced by MessageManager::Broadcast(), Foreground::HandleMessage(), ScreenSelect::HandleMessage(), HoldJudgment::HandleMessage(), StepsDisplayList::HandleMessage(), ModIconRow::HandleMessage(), GameStateMessageHandler::HandleMessage(), OptionRow::HandleMessage(), and Actor::PlayCommandNoRecurse().
GetParam()
template<typename T > bool Message::GetParam (const RString & sName, T & val) const inline
References LuaManager::Get(), GetParamFromStack(), L, LUA, LuaHelpers::Pop(), and LuaManager::Release().
Referenced by HoldJudgment::HandleMessage(), ScreenSelectMusic::HandleMessage(), and ScreenGameplay::HandleMessage().
GetParamFromStack()
void Message::GetParamFromStack (lua_State * L, const RString & sName) const
References LuaTable::Get(), and m_pParams.
Referenced by GetParam().
GetParamTable()
const LuaReference & Message::GetParamTable () const
References m_pParams.
Referenced by Actor::PlayCommandNoRecurse().
IsBroadcast()
bool Message::IsBroadcast () const inline
References m_bBroadcast.
Referenced by ActorFrame::HandleMessage().
operator=()
Message& Message::operator= (const Message & rhs) private
operator==() [1/2]
bool Message::operator== (const RString & s) const inline
References m_sName.
operator==() [2/2]
bool Message::operator== (MessageID id) const inline
References m_sName, and MessageIDToString().
PushParamTable()
void Message::PushParamTable (lua_State * L)
References m_pParams, and LuaReference::PushSelf().
SetBroadcast()
void Message::SetBroadcast (bool b) inline
References m_bBroadcast.
Referenced by MessageManager::Broadcast().
SetName()
void Message::SetName (const RString & sName) inline
References m_sName.
Referenced by InputQueueCodeSet::InputMessage().
SetParam() [1/2]
template<typename T > void Message::SetParam (const RString & sName, const T & val) inline
References LuaManager::Get(), L, LUA, LuaHelpers::Push(), LuaManager::Release(), and SetParamFromStack().
Referenced by LifeMeterBar::AfterLifeChanged(), LifeMeterBattery::BroadcastLifeChanged(), MusicWheel::BuildWheelItemDatas(), ScreenSelectMaster::ChangePage(), ScreenSelectMusic::ChangeSteps(), ScreenOptions::ChangeValueInRowAbsolute(), OptionsList::Close(), SMOProtocol::DealWithSMOnlinePack(), ScreenSelectMusic::DetectCodes(), GhostArrowRow::DidHoldNote(), GhostArrowRow::DidTapNote(), SongManager::DifferentialReload(), SongManager::DifferentialReloadDir(), Download::Failed(), ScoreKeeperNormal::HandleHoldScore(), ScreenSelectMaster::HandleScreenMessage(), ScoreKeeperNormal::HandleTapRowScore(), ScoreKeeperNormal::HandleTapScore(), ScoreDisplayNormal::Init(), NoteField::Init(), Player::Init(), ScreenContinue::Input(), ScreenSelectMusic::Input(), OptionsList::Input(), InputQueueCodeSet::InputMessage(), Download::Install(), GameState::JoinPlayer(), StepsDisplay::Load(), ScoreKeeperNormal::Load(), MusicWheelItem::LoadFromWheelItemData(), ScreenSelectMaster::MenuStart(), ScreenOptions::MoveRowAbsolute(), OptionsList::Open(), ScreenOptions::ProcessMenuStart(), MusicWheelItem::RefreshGrades(), DownloadManager::RequestChartLeaderBoard(), ScreenMapControllers::SanityCheckWrapper(), LuaHelpers::ScriptErrorMessage(), ScreenSelectMusic::SelectCurrent(), Player::SendComboMessages(), ScreenGameplay::SendCrossedMessages(), LifeMeterTime::SendLifeChangedMessage(), Player::SetCombo(), ScreenWithMenuElements::SetHelpText(), Player::SetHoldJudgment(), StepsDisplay::SetInternal(), Player::SetJudgment(), PlayerStageStats::SetLifeRecordAt(), Player::SetMineJudgment(), OptionRow::SetModIcon(), ReceptorArrow::SetNoteUpcoming(), OptionsList::Start(), ReceptorArrow::Step(), Player::Step(), OptionsList::SwitchToCurrentRow(), ScreenManager::SystemMessage(), ScreenManager::SystemMessageNoAnimate(), ScreenGameplay::ToggleReplayPause(), GameState::UnjoinPlayer(), ScreenInstallOverlay::Update(), GameSoundManager::Update(), ScreenGameplay::Update(), ETTProtocol::Update(), ScreenSelectMusic::UpdateSelectButton(), ScreenNetEvaluation::UpdateStats(), and ScreenSyncOverlay::UpdateText().
SetParam() [2/2]
template<typename T > void Message::SetParam (const RString & sName, const vector< T > & val) inline
References LuaHelpers::CreateTableFromArray(), LuaManager::Get(), L, LUA, LuaManager::Release(), and SetParamFromStack().
SetParamFromStack()
void Message::SetParamFromStack (lua_State * L, const RString & sName)
References m_pParams, and LuaTable::Set().
Referenced by Player::SetHoldJudgment(), Player::SetJudgment(), and SetParam().
SetParamTable()
void Message::SetParamTable (const LuaReference & params)
References LuaManager::Get(), L, LUA, m_pParams, LuaReference::PushSelf(), LuaManager::Release(), and LuaReference::SetFromStack().
Member Data Documentation
m_bBroadcast
bool Message::m_bBroadcast private
Referenced by IsBroadcast(), Message(), and SetBroadcast().
m_pParams
LuaTable* Message::m_pParams private
Referenced by GetParamFromStack(), GetParamTable(), Message(), PushParamTable(), SetParamFromStack(), SetParamTable(), and ~Message().
m_sName
RString Message::m_sName private
Referenced by GetName(), Message(), operator==(), and SetName().
The documentation for this struct was generated from the following files:
MessageManager.h
MessageManager.cpp