Etterna: BitmapText::BMT_TweenState Struct Reference
BitmapText::BMT_TweenState Struct Reference
#include <BitmapText.h>
Public Member Functions
BMT_TweenState ()
bool operator== (BMT_TweenState const &other) const
bool operator!= (BMT_TweenState const &other) const
void SetStrokeColor (RageColor const &c)
RageColor const & GetStrokeColor ()
Static Public Member Functions
static void MakeWeightedAverage (BMT_TweenState &out, BMT_TweenState const &from, BMT_TweenState const &to, float between)
Private Attributes
RageColor m_stroke_color
Constructor & Destructor Documentation
BMT_TweenState()
BitmapText::BMT_TweenState::BMT_TweenState () inline
Member Function Documentation
GetStrokeColor()
RageColor const& BitmapText::BMT_TweenState::GetStrokeColor () inline
References m_stroke_color.
Referenced by BitmapText::GetCurrStrokeColor(), and BitmapText::GetStrokeColor().
MakeWeightedAverage()
void BitmapText::BMT_TweenState::MakeWeightedAverage (BMT_TweenState & out, BMT_TweenState const & from, BMT_TweenState const & to, float between) static
References RageColor::a, RageColor::b, RageColor::g, lerp(), m_stroke_color, and RageColor::r.
Referenced by BitmapText::UpdatePercentThroughTween().
operator!=()
bool BitmapText::BMT_TweenState::operator!= (BMT_TweenState const & other) const inline
References operator==().
operator==()
bool BitmapText::BMT_TweenState::operator== (BMT_TweenState const & other) const
Referenced by operator!=().
SetStrokeColor()
void BitmapText::BMT_TweenState::SetStrokeColor (RageColor const & c) inline
References m_stroke_color.
Referenced by BitmapText::SetCurrStrokeColor(), and BitmapText::SetStrokeColor().
Member Data Documentation
m_stroke_color
RageColor BitmapText::BMT_TweenState::m_stroke_color private
Referenced by GetStrokeColor(), MakeWeightedAverage(), and SetStrokeColor().
The documentation for this struct was generated from the following files:
BitmapText.h
BitmapText.cpp