Etterna: InputHandler_DirectInputHelper.cpp File Reference
InputHandler_DirectInputHelper.cpp File Reference
#include "InputHandler_DirectInputHelper.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "archutils/Win32/DirectXHelpers.h"
#include "archutils/Win32/ErrorStrings.h"
#include "archutils/Win32/GraphicsWindow.h"
#include "global.h"
Functions
static int ConvertScancodeToKey (int scancode)
static BOOL CALLBACK DIJoystick_EnumDevObjectsProc (LPCDIDEVICEOBJECTINSTANCE dev, LPVOID data)
static BOOL CALLBACK DIMouse_EnumDevObjectsProc (LPCDIDEVICEOBJECTINSTANCE dev, LPVOID data)
Variables
LPDIRECTINPUT8 g_dinput = NULL
Function Documentation
ConvertScancodeToKey()
static int ConvertScancodeToKey (int scancode) static
References KEY_ACCENT, KEY_BACK, KEY_BACKSLASH, KEY_C0, KEY_C1, KEY_C2, KEY_C3, KEY_C4, KEY_C5, KEY_C6, KEY_C7, KEY_C8, KEY_C9, KEY_Ca, KEY_CAPSLOCK, KEY_Cb, KEY_Cc, KEY_Cd, KEY_Ce, KEY_Cf, KEY_Cg, KEY_Ch, KEY_Ci, KEY_Cj, KEY_Ck, KEY_Cl, KEY_Cm, KEY_Cn, KEY_Co, KEY_COMMA, KEY_Cp, KEY_Cq, KEY_Cr, KEY_Cs, KEY_Ct, KEY_Cu, KEY_Cv, KEY_Cw, KEY_Cx, KEY_Cy, KEY_Cz, KEY_DEL, KEY_DOWN, KEY_END, KEY_ENTER, KEY_EQUAL, KEY_ESC, KEY_F1, KEY_F10, KEY_F11, KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_HOME, KEY_HYPHEN, KEY_INSERT, KEY_KP_ASTERISK, KEY_KP_C0, KEY_KP_C1, KEY_KP_C2, KEY_KP_C3, KEY_KP_C4, KEY_KP_C5, KEY_KP_C6, KEY_KP_C7, KEY_KP_C8, KEY_KP_C9, KEY_KP_ENTER, KEY_KP_EQUAL, KEY_KP_HYPHEN, KEY_KP_PERIOD, KEY_KP_PLUS, KEY_KP_SLASH, KEY_LALT, KEY_LBRACKET, KEY_LCTRL, KEY_LEFT, KEY_LMETA, KEY_LSHIFT, KEY_MENU, KEY_NUMLOCK, KEY_PAUSE, KEY_PERIOD, KEY_PGDN, KEY_PGUP, KEY_PRTSC, KEY_RALT, KEY_RBRACKET, KEY_RCTRL, KEY_RIGHT, KEY_RMETA, KEY_RSHIFT, KEY_SCRLLOCK, KEY_SEMICOLON, KEY_SLASH, KEY_SPACE, KEY_SQUOTE, KEY_TAB, and KEY_UP.
Referenced by DIDevice::Open().
DIJoystick_EnumDevObjectsProc()
static BOOL CALLBACK DIJoystick_EnumDevObjectsProc (LPCDIDEVICEOBJECTINSTANCE dev, LPVOID data) static
References DIDevice::axes, input_t::AXIS, input_t::BUTTON, DIDevice::buttons, DIDevice::Device, input_t::HAT, DIDevice::hats, DIDevice::Inputs, input_t::num, input_t::ofs, and input_t::type.
Referenced by DIDevice::Open().
DIMouse_EnumDevObjectsProc()
static BOOL CALLBACK DIMouse_EnumDevObjectsProc (LPCDIDEVICEOBJECTINSTANCE dev, LPVOID data) static
References DIDevice::axes, input_t::AXIS, input_t::BUTTON, DIDevice::buttons, DIDevice::Inputs, input_t::num, input_t::ofs, and input_t::type.
Referenced by DIDevice::Open().
Variable Documentation
g_dinput
LPDIRECTINPUT8 g_dinput = NULL
Referenced by GetNumJoysticksSlow(), InputHandler_DInput::InputHandler_DInput(), DIDevice::Open(), and InputHandler_DInput::~InputHandler_DInput().