Etterna: ThemeMetric< T > Class Template Reference
ThemeMetric< T > Class Template Reference
The theme specific data.
#include <ThemeMetric.h>
Public Member Functions
ThemeMetric (const RString &sGroup="", const RString &sName="")
ThemeMetric (const ThemeMetric< T > &cpy)
~ThemeMetric () override
void Load (const RString &sGroup, const RString &sName)
Load the chosen metric from the .ini file.
void ChangeGroup (const RString &sGroup)
void Read () override
Actually read the metric and get its data.
void PushSelf (Lua *L)
void Clear () override
const RString & GetName () const
Retrieve the metric's name.
const RString & GetGroup () const
Retrieve the metric's group.
const T & GetValue () const
Retrieve the metric's value.
operator const T & () const
bool IsLoaded () const
bool operator== (const T &input) const
Public Member Functions inherited from IThemeMetric
virtual ~IThemeMetric ()=default
Protected Attributes
RString m_sGroup
the metric's group.
RString m_sName
the metric's name.
LuaReference m_Value
the metric's value.
T m_currentValue
bool m_bCallEachTime
Detailed Description
template<class T>
class ThemeMetric< T >
The theme specific data.
Each piece of data is to correspond to a type.
Constructor & Destructor Documentation
ThemeMetric() [1/2]
template<class T> ThemeMetric< T >::ThemeMetric (const RString & sGroup = "", const RString & sName = "") inline
ThemeMetric() [2/2]
template<class T> ThemeMetric< T >::ThemeMetric (const ThemeMetric< T > & cpy) inline
~ThemeMetric()
template<class T> ThemeMetric< T >::~ThemeMetric () inline override
Member Function Documentation
ChangeGroup()
template<class T> void ThemeMetric< T >::ChangeGroup (const RString & sGroup) inline
Clear()
template<class T> void ThemeMetric< T >::Clear () inline override virtual
Implements IThemeMetric.
GetGroup()
template<class T> const RString& ThemeMetric< T >::GetGroup () const inline
Retrieve the metric's group.
Returns
the metric's group.
GetName()
template<class T> const RString& ThemeMetric< T >::GetName () const inline
Retrieve the metric's name.
Returns
the metric's name.
GetValue()
template<class T> const T& ThemeMetric< T >::GetValue () const inline
Retrieve the metric's value.
Returns
the metric's value.
Referenced by ScreenOptions::ChangeValueInRowRelative(), GetCustomDifficulty(), ScreenSelectMaster::GetDefaultChoice(), ScreenOptions::GetExplanationText(), StepMania::GetInitialScreen(), PlayerOptions::GetMods(), PaneDisplay::GetPaneTextAndLevel(), StepMania::GetSelectMusicScreen(), ScreenHowToPlay::Init(), ScreenWithMenuElements::Init(), ScreenPackages::Init(), ScreenSelectMusic::Input(), ThemeMetric< TapNoteScore >::operator const TapNoteScore &(), ThemeMetric< AutoPtrCopyOnWrite >::operator==(), OptionRow::PositionUnderlines(), LifeMeterBattery::Refresh(), BPMDisplay::SetBPMRange(), StepsDisplay::SetInternal(), RollingNumbers::SetTargetNumber(), LyricDisplay::Update(), WheelBase::Update(), ScreenGameplay::Update(), and RollingNumbers::UpdateText().
IsLoaded()
template<class T> bool ThemeMetric< T >::IsLoaded () const inline
Load()
template<class T> void ThemeMetric< T >::Load (const RString & sGroup, const RString & sName) inline
Load the chosen metric from the .ini file.
Parameters
sGroup the group the metric is in.
sName the name of the metric.
Referenced by AutoScreenMessage(), ScreenSelectMusic::BeginScreen(), ScreenProfileLoad::Init(), ScreenSelect::Init(), ScreenSplash::Init(), ScreenContinue::Init(), ScreenAttract::Init(), ScreenWithMenuElements::Init(), ScreenStatsOverlay::Init(), ScreenPackages::Init(), BeginnerHelper::Init(), ScreenNetSelectMusic::Init(), ScreenRanking::Init(), ScreenSelectMaster::Init(), ScreenSelectMusic::Init(), ScreenOptions::Init(), ScreenEvaluation::Init(), Screen::Init(), Player::Init(), ScreenGameplay::Init(), LifeMeterBar::LifeMeterBar(), RollingNumbers::Load(), ModIcon::Load(), RoomInfoDisplay::Load(), SoundEffectControl::Load(), OptionListRow::Load(), ComboGraph::Load(), LifeMeterBattery::Load(), ModIconRow::Load(), BPMDisplay::Load(), MenuTimer::Load(), MusicWheel::Load(), StepsDisplay::Load(), OptionRowType::Load(), StreamDisplay::Load(), PaneDisplay::Load(), WheelBase::Load(), OptionsList::Load(), ScoreKeeperNormal::Load(), LocalizedStringImplThemeMetric::Load(), StepsDisplayList::LoadFromNode(), MusicWheelItem::MusicWheelItem(), SongManager::ResetGroupColors(), and SongManager::SongManager().
operator const T &()
template<class T> ThemeMetric< T >::operator const T & () const inline
operator==()
template<class T> bool ThemeMetric< T >::operator== (const T & input) const inline
PushSelf()
template<class T> void ThemeMetric< T >::PushSelf (Lua * L) inline
Referenced by ScoreKeeperNormal::CalcNextToastyAt(), MusicWheel::NextSort(), and LifeMeterBattery::OnSongEnded().
Read()
template<class T> void ThemeMetric< T >::Read () inline override virtual
Actually read the metric and get its data.
Implements IThemeMetric.
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::ChangeGroup(), ThemeMetric< AutoPtrCopyOnWrite >::Load(), ThemeMetricDifficultiesToShow::Read(), ThemeMetricStepsTypesToShow::Read(), and ScreenDimensions::ReloadScreenDimensions().
Member Data Documentation
m_bCallEachTime
template<class T> bool ThemeMetric< T >::m_bCallEachTime protected
m_currentValue
template<class T> T ThemeMetric< T >::m_currentValue mutable protected
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::GetValue().
m_sGroup
template<class T> RString ThemeMetric< T >::m_sGroup protected
the metric's group.
In metrics.ini, it is usually done as such: [GroupName]
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::GetGroup().
m_sName
template<class T> RString ThemeMetric< T >::m_sName protected
the metric's name.
Referenced by ThemeMetric< AutoPtrCopyOnWrite >::GetName(), and ThemeMetric< AutoPtrCopyOnWrite >::GetValue().
m_Value
template<class T> LuaReference ThemeMetric< T >::m_Value protected
the metric's value.
The documentation for this class was generated from the following file:
ThemeMetric.h