Etterna: SongCriteria Class Reference
SongCriteria Class Reference
The criteria for dealing with songs.
#include <SongUtil.h>
Public Types
enum Selectable { Selectable_Yes, Selectable_No, Selectable_DontCare }
enum Tutorial { Tutorial_Yes, Tutorial_No, Tutorial_DontCare }
Is this song used for tutorial purposes?
enum Locked { Locked_Locked, Locked_Unlocked, Locked_DontCare }
Is this song used for locking/unlocking purposes?
Public Member Functions
SongCriteria ()
Set up some initial song criteria.
bool Matches (const Song *p) const
Determine if the song matches the current criteria.
bool operator== (const SongCriteria &other) const
Determine if two sets of criteria are equivalent.
bool operator!= (const SongCriteria &other) const
Determine if two sets of criteria are not equivalent.
Public Attributes
RString m_sGroupName
What group name are we searching for for Songs?
bool m_bUseSongGenreAllowedList { false }
vector< RString > m_vsSongGenreAllowedList
enum SongCriteria::Selectable Selectable_DontCare
bool m_bUseSongAllowedList { false }
vector< Song * > m_vpSongAllowedList
int m_iMaxStagesForSong { -1 }
How many songs does this take max? Don't use this if it's -1.
enum SongCriteria::Tutorial Tutorial_DontCare
enum SongCriteria::Locked Locked_DontCare
Detailed Description
The criteria for dealing with songs.
Member Enumeration Documentation
Locked
enum SongCriteria::Locked
Is this song used for locking/unlocking purposes?
Enumerator
Locked_Locked
This song is a locked song.
Locked_Unlocked
This song is an unlocked song.
Locked_DontCare
This song can or cannot be locked or unlocked.
Selectable
enum SongCriteria::Selectable
Enumerator
Selectable_Yes
Selectable_No
Selectable_DontCare
Tutorial
enum SongCriteria::Tutorial
Is this song used for tutorial purposes?
Enumerator
Tutorial_Yes
This song is used for tutorial purposes.
Tutorial_No
This song is not used for tutorial purposes.
Tutorial_DontCare
This song can or cannot be used for tutorial purposes.
Constructor & Destructor Documentation
SongCriteria()
SongCriteria::SongCriteria () inline
Set up some initial song criteria.
Member Function Documentation
Matches()
bool SongCriteria::Matches (const Song * p) const
Determine if the song matches the current criteria.
Parameters
p the song to compare against the criteria.
Returns
true of the song matches the criteria, false otherwise.
References DEFAULT_FAIL, GAMESTATE, GameState::GetNumStagesMultiplierForSong(), Song::IsTutorial(), Locked_DontCare, Locked_Locked, Locked_Unlocked, m_bUseSongAllowedList, m_bUseSongGenreAllowedList, m_iMaxStagesForSong, Song::m_sGenre, m_sGroupName, Song::m_sGroupName, m_vpSongAllowedList, m_vsSongGenreAllowedList, Selectable_DontCare, Selectable_No, Selectable_Yes, Tutorial_DontCare, Tutorial_No, and Tutorial_Yes.
Referenced by SongUtil::FilterSongs(), StepsUtil::GetAllMatching(), and StepsUtil::HasMatching().
operator!=()
bool SongCriteria::operator!= (const SongCriteria & other) const inline
Determine if two sets of criteria are not equivalent.
Parameters
other the other criteria.
Returns
true if the two sets of criteria are not equal, false otherwise.
References operator==().
operator==()
bool SongCriteria::operator== (const SongCriteria & other) const inline
Determine if two sets of criteria are equivalent.
Parameters
other the other criteria.
Returns
true if the two sets of criteria are equal, false otherwise.
A quick way to match every part of the song criterium.
References m_bUseSongAllowedList, m_bUseSongGenreAllowedList, m_iMaxStagesForSong, and X.
Referenced by operator!=().
Member Data Documentation
Locked_DontCare
enum SongCriteria::Locked SongCriteria::Locked_DontCare
Referenced by Matches().
m_bUseSongAllowedList
bool SongCriteria::m_bUseSongAllowedList { false }
Referenced by Matches(), and operator==().
m_bUseSongGenreAllowedList
bool SongCriteria::m_bUseSongGenreAllowedList { false }
Referenced by Matches(), and operator==().
m_iMaxStagesForSong
int SongCriteria::m_iMaxStagesForSong { -1 }
How many songs does this take max? Don't use this if it's -1.
Referenced by Matches(), and operator==().
m_sGroupName
RString SongCriteria::m_sGroupName
What group name are we searching for for Songs?
If an empty string, don't bother using this for searching.
Referenced by StepsUtil::GetAllMatching(), StepsUtil::HasMatching(), and Matches().
m_vpSongAllowedList
vector<Song*> SongCriteria::m_vpSongAllowedList
Referenced by Matches().
m_vsSongGenreAllowedList
vector<RString> SongCriteria::m_vsSongGenreAllowedList
Referenced by Matches().
Selectable_DontCare
enum SongCriteria::Selectable SongCriteria::Selectable_DontCare
Referenced by Matches().
Tutorial_DontCare
enum SongCriteria::Tutorial SongCriteria::Tutorial_DontCare
Referenced by Matches().
The documentation for this class was generated from the following files:
SongUtil.h
SongUtil.cpp