Etterna: LunaActor Class Reference
LunaActor Class Reference
Allow Lua to have access to the Actor.
Public Member Functions
GETTER_SETTER_BOOL_METHOD (tween_uses_effect_delta)
LunaActor ()
Public Member Functions inherited from Luna< Actor >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int name (T *p, lua_State *L)
static int sleep (T *p, lua_State *L)
static int linear (T *p, lua_State *L)
static int accelerate (T *p, lua_State *L)
static int decelerate (T *p, lua_State *L)
static int spring (T *p, lua_State *L)
static int tween (T *p, lua_State *L)
static int stoptweening (T *p, lua_State *L)
static int finishtweening (T *p, lua_State *L)
static int hurrytweening (T *p, lua_State *L)
static int GetTweenTimeLeft (T *p, lua_State *L)
static int x (T *p, lua_State *L)
static int y (T *p, lua_State *L)
static int z (T *p, lua_State *L)
static int xy (T *p, lua_State *L)
static int addx (T *p, lua_State *L)
static int addy (T *p, lua_State *L)
static int addz (T *p, lua_State *L)
static int zoom (T *p, lua_State *L)
static int zoomx (T *p, lua_State *L)
static int zoomy (T *p, lua_State *L)
static int zoomz (T *p, lua_State *L)
static int zoomto (T *p, lua_State *L)
static int zoomtowidth (T *p, lua_State *L)
static int zoomtoheight (T *p, lua_State *L)
static int setsize (T *p, lua_State *L)
static int SetWidth (T *p, lua_State *L)
static int SetHeight (T *p, lua_State *L)
static int basealpha (T *p, lua_State *L)
static int basezoom (T *p, lua_State *L)
static int basezoomx (T *p, lua_State *L)
static int basezoomy (T *p, lua_State *L)
static int basezoomz (T *p, lua_State *L)
static int stretchto (T *p, lua_State *L)
static int cropleft (T *p, lua_State *L)
static int croptop (T *p, lua_State *L)
static int cropright (T *p, lua_State *L)
static int cropbottom (T *p, lua_State *L)
static int fadeleft (T *p, lua_State *L)
static int fadetop (T *p, lua_State *L)
static int faderight (T *p, lua_State *L)
static int fadebottom (T *p, lua_State *L)
static int diffuse (T *p, lua_State *L)
static int diffuseupperleft (T *p, lua_State *L)
static int diffuseupperright (T *p, lua_State *L)
static int diffuselowerleft (T *p, lua_State *L)
static int diffuselowerright (T *p, lua_State *L)
static int diffuseleftedge (T *p, lua_State *L)
static int diffuserightedge (T *p, lua_State *L)
static int diffusetopedge (T *p, lua_State *L)
static int diffusebottomedge (T *p, lua_State *L)
static int diffusealpha (T *p, lua_State *L)
static int diffusecolor (T *p, lua_State *L)
static int glow (T *p, lua_State *L)
static int aux (T *p, lua_State *L)
static int getaux (T *p, lua_State *L)
static int rotationx (T *p, lua_State *L)
static int rotationy (T *p, lua_State *L)
static int rotationz (T *p, lua_State *L)
static int addrotationx (T *p, lua_State *L)
static int addrotationy (T *p, lua_State *L)
static int addrotationz (T *p, lua_State *L)
static int getrotation (T *p, lua_State *L)
static int baserotationx (T *p, lua_State *L)
static int baserotationy (T *p, lua_State *L)
static int baserotationz (T *p, lua_State *L)
static int skewx (T *p, lua_State *L)
static int skewy (T *p, lua_State *L)
static int heading (T *p, lua_State *L)
static int pitch (T *p, lua_State *L)
static int roll (T *p, lua_State *L)
static int shadowlength (T *p, lua_State *L)
static int shadowlengthx (T *p, lua_State *L)
static int shadowlengthy (T *p, lua_State *L)
static int shadowcolor (T *p, lua_State *L)
static int horizalign (T *p, lua_State *L)
static int vertalign (T *p, lua_State *L)
static int halign (T *p, lua_State *L)
static int valign (T *p, lua_State *L)
static int diffuseblink (T *p, lua_State *L)
static int diffuseshift (T *p, lua_State *L)
static int diffuseramp (T *p, lua_State *L)
static int glowblink (T *p, lua_State *L)
static int glowshift (T *p, lua_State *L)
static int glowramp (T *p, lua_State *L)
static int rainbow (T *p, lua_State *L)
static int wag (T *p, lua_State *L)
static int bounce (T *p, lua_State *L)
static int bob (T *p, lua_State *L)
static int pulse (T *p, lua_State *L)
static int spin (T *p, lua_State *L)
static int vibrate (T *p, lua_State *L)
static int stopeffect (T *p, lua_State *L)
static int effectcolor1 (T *p, lua_State *L)
static int effectcolor2 (T *p, lua_State *L)
static int effectperiod (T *p, lua_State *L)
static int effecttiming (T *p, lua_State *L)
static int effect_hold_at_full (T *p, lua_State *L)
static int effectoffset (T *p, lua_State *L)
static int effectclock (T *p, lua_State *L)
static int effectmagnitude (T *p, lua_State *L)
static int geteffectmagnitude (T *p, lua_State *L)
static int scaletocover (T *p, lua_State *L)
static int scaletofit (T *p, lua_State *L)
static int animate (T *p, lua_State *L)
static int play (T *p, lua_State *L)
static int pause (T *p, lua_State *L)
static int setstate (T *p, lua_State *L)
static int GetNumStates (T *p, lua_State *L)
static int texturetranslate (T *p, lua_State *L)
static int texturewrapping (T *p, lua_State *L)
static int SetTextureFiltering (T *p, lua_State *L)
static int blend (T *p, lua_State *L)
static int zbuffer (T *p, lua_State *L)
static int ztest (T *p, lua_State *L)
static int ztestmode (T *p, lua_State *L)
static int zwrite (T *p, lua_State *L)
static int zbias (T *p, lua_State *L)
static int clearzbuffer (T *p, lua_State *L)
static int backfacecull (T *p, lua_State *L)
static int cullmode (T *p, lua_State *L)
static int visible (T *p, lua_State *L)
static int hibernate (T *p, lua_State *L)
static int draworder (T *p, lua_State *L)
static int playcommand (T *p, lua_State *L)
static int queuecommand (T *p, lua_State *L)
static int queuemessage (T *p, lua_State *L)
static int addcommand (T *p, lua_State *L)
static int GetCommand (T *p, lua_State *L)
static int RunCommandsRecursively (T *p, lua_State *L)
static int GetX (T *p, lua_State *L)
static int GetY (T *p, lua_State *L)
static int GetZ (T *p, lua_State *L)
static int GetDestX (T *p, lua_State *L)
static int GetDestY (T *p, lua_State *L)
static int GetDestZ (T *p, lua_State *L)
static int GetWidth (T *p, lua_State *L)
static int GetHeight (T *p, lua_State *L)
static int GetZoomedWidth (T *p, lua_State *L)
static int GetZoomedHeight (T *p, lua_State *L)
static int GetZoom (T *p, lua_State *L)
static int GetZoomX (T *p, lua_State *L)
static int GetZoomY (T *p, lua_State *L)
static int GetZoomZ (T *p, lua_State *L)
static int GetBaseZoomX (T *p, lua_State *L)
static int GetBaseZoomY (T *p, lua_State *L)
static int GetBaseZoomZ (T *p, lua_State *L)
static int GetRotationX (T *p, lua_State *L)
static int GetRotationY (T *p, lua_State *L)
static int GetRotationZ (T *p, lua_State *L)
static int GetSecsIntoEffect (T *p, lua_State *L)
static int GetEffectDelta (T *p, lua_State *L)
static int GetDiffuseAlpha (T *p, lua_State *L)
static int GetVisible (T *p, lua_State *L)
static int GetHAlign (T *p, lua_State *L)
static int GetVAlign (T *p, lua_State *L)
static int GetName (T *p, lua_State *L)
static int GetParent (T *p, lua_State *L)
static int GetFakeParent (T *p, lua_State *L)
static int SetFakeParent (T *p, lua_State *L)
static int AddWrapperState (T *p, lua_State *L)
static size_t get_state_index (T *p, lua_State *L, int stack_index)
static int RemoveWrapperState (T *p, lua_State *L)
static int GetNumWrapperStates (T *p, lua_State *L)
static int GetWrapperState (T *p, lua_State *L)
static int Draw (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Actor >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Actor >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Actor >
using T = Actor
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Actor >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Actor.
Constructor & Destructor Documentation
LunaActor()
LunaActor::LunaActor () inline
References ADD_GET_SET_METHODS, ADD_METHOD, Actor::AddWrapperState(), Actor::bob, Actor::bounce, Actor::Draw(), Actor::GetBaseZoomX(), Actor::GetBaseZoomY(), Actor::GetBaseZoomZ(), Actor::GetCommand(), Actor::GetDestX(), Actor::GetDestY(), Actor::GetDestZ(), Actor::GetDiffuse(), Actor::GetDiffuseAlpha(), Actor::GetEffectDelta(), Actor::GetFakeParent(), Actor::GetGlow(), Actor::GetName(), Actor::GetNumStates(), Actor::GetNumWrapperStates(), Actor::GetParent(), Actor::GetRotationX(), Actor::GetRotationY(), Actor::GetRotationZ(), Actor::GetSecsIntoEffect(), Actor::GetTweenTimeLeft(), Actor::GetVisible(), Actor::GetWrapperState(), Actor::GetX(), Actor::GetY(), Actor::GetZ(), Actor::GetZoom(), Actor::GetZoomedHeight(), Actor::GetZoomedWidth(), Actor::GetZoomX(), Actor::GetZoomY(), Actor::GetZoomZ(), Actor::pulse, Actor::rainbow, Actor::RemoveWrapperState(), roll, Actor::RunCommandsRecursively(), Actor::SetFakeParent(), Actor::SetHeight(), Actor::SetTextureFiltering(), Actor::SetWidth(), Actor::spin, Actor::vibrate, and Actor::wag.
Member Function Documentation
accelerate()
static int LunaActor::accelerate (T * p, lua_State * L) inline static
References Actor::BeginTweening(), COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and TWEEN_ACCELERATE.
addcommand()
static int LunaActor::addcommand (T * p, lua_State * L) inline static
References Actor::AddCommand(), COMMON_RETURN_SELF, SArg, and LuaReference::SetFromStack().
addrotationx()
static int LunaActor::addrotationx (T * p, lua_State * L) inline static
References Actor::AddRotationX(), COMMON_RETURN_SELF, and FArg.
addrotationy()
static int LunaActor::addrotationy (T * p, lua_State * L) inline static
References Actor::AddRotationY(), COMMON_RETURN_SELF, and FArg.
addrotationz()
static int LunaActor::addrotationz (T * p, lua_State * L) inline static
References Actor::AddRotationZ(), COMMON_RETURN_SELF, and FArg.
AddWrapperState()
static int LunaActor::AddWrapperState (T * p, lua_State * L) inline static
References Actor::AddWrapperState(), Actor::GetNumWrapperStates(), Actor::GetWrapperState(), and Actor::PushSelf().
addx()
static int LunaActor::addx (T * p, lua_State * L) inline static
References Actor::AddX(), COMMON_RETURN_SELF, and FArg.
addy()
static int LunaActor::addy (T * p, lua_State * L) inline static
References Actor::AddY(), COMMON_RETURN_SELF, and FArg.
addz()
static int LunaActor::addz (T * p, lua_State * L) inline static
References Actor::AddZ(), COMMON_RETURN_SELF, and FArg.
animate()
static int LunaActor::animate (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::EnableAnimation().
aux()
static int LunaActor::aux (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetAux().
backfacecull()
static int LunaActor::backfacecull (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, CULL_BACK, CULL_NONE, and Actor::SetCullMode().
basealpha()
static int LunaActor::basealpha (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseAlpha().
baserotationx()
static int LunaActor::baserotationx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseRotationX().
baserotationy()
static int LunaActor::baserotationy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseRotationY().
baserotationz()
static int LunaActor::baserotationz (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseRotationZ().
basezoom()
static int LunaActor::basezoom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseZoom().
basezoomx()
static int LunaActor::basezoomx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseZoomX().
basezoomy()
static int LunaActor::basezoomy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseZoomY().
basezoomz()
static int LunaActor::basezoomz (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetBaseZoomZ().
blend()
static int LunaActor::blend (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetBlendMode().
bob()
static int LunaActor::bob (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectBob().
bounce()
static int LunaActor::bounce (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectBounce().
clearzbuffer()
static int LunaActor::clearzbuffer (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::SetClearZBuffer().
cropbottom()
static int LunaActor::cropbottom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetCropBottom().
cropleft()
static int LunaActor::cropleft (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetCropLeft().
cropright()
static int LunaActor::cropright (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetCropRight().
croptop()
static int LunaActor::croptop (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetCropTop().
cullmode()
static int LunaActor::cullmode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetCullMode().
decelerate()
static int LunaActor::decelerate (T * p, lua_State * L) inline static
References Actor::BeginTweening(), COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and TWEEN_DECELERATE.
diffuse()
static int LunaActor::diffuse (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuse().
diffusealpha()
static int LunaActor::diffusealpha (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetDiffuseAlpha().
diffuseblink()
static int LunaActor::diffuseblink (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectDiffuseBlink().
diffusebottomedge()
static int LunaActor::diffusebottomedge (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseBottomEdge().
diffusecolor()
static int LunaActor::diffusecolor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseColor().
diffuseleftedge()
static int LunaActor::diffuseleftedge (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseLeftEdge().
diffuselowerleft()
static int LunaActor::diffuselowerleft (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseLowerLeft().
diffuselowerright()
static int LunaActor::diffuselowerright (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseLowerRight().
diffuseramp()
static int LunaActor::diffuseramp (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectDiffuseRamp().
diffuserightedge()
static int LunaActor::diffuserightedge (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseRightEdge().
diffuseshift()
static int LunaActor::diffuseshift (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectDiffuseShift().
diffusetopedge()
static int LunaActor::diffusetopedge (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseTopEdge().
diffuseupperleft()
static int LunaActor::diffuseupperleft (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseUpperLeft().
diffuseupperright()
static int LunaActor::diffuseupperright (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetDiffuseUpperRight().
Draw()
static int LunaActor::Draw (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Actor::Draw(), LUA, LuaManager::UnyieldLua(), and LuaManager::YieldLua().
draworder()
static int LunaActor::draworder (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and Actor::SetDrawOrder().
effect_hold_at_full()
static int LunaActor::effect_hold_at_full (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetEffectHoldAtFull().
effectclock()
static int LunaActor::effectclock (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and Actor::SetEffectClockString().
effectcolor1()
static int LunaActor::effectcolor1 (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetEffectColor1().
effectcolor2()
static int LunaActor::effectcolor2 (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetEffectColor2().
effectmagnitude()
static int LunaActor::effectmagnitude (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetEffectMagnitude().
effectoffset()
static int LunaActor::effectoffset (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetEffectOffset().
effectperiod()
static int LunaActor::effectperiod (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and Actor::SetEffectPeriod().
effecttiming()
static int LunaActor::effecttiming (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetEffectTiming().
fadebottom()
static int LunaActor::fadebottom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetFadeBottom().
fadeleft()
static int LunaActor::fadeleft (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetFadeLeft().
faderight()
static int LunaActor::faderight (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetFadeRight().
fadetop()
static int LunaActor::fadetop (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetFadeTop().
finishtweening()
static int LunaActor::finishtweening (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::FinishTweening().
get_state_index()
static size_t LunaActor::get_state_index (T * p, lua_State * L, int stack_index) inline static
References Actor::GetNumWrapperStates(), and IArg.
getaux()
static int LunaActor::getaux (T * p, lua_State * L) inline static
References Actor::GetAux().
GetBaseZoomX()
static int LunaActor::GetBaseZoomX (T * p, lua_State * L) inline static
References Actor::GetBaseZoomX().
GetBaseZoomY()
static int LunaActor::GetBaseZoomY (T * p, lua_State * L) inline static
References Actor::GetBaseZoomY().
GetBaseZoomZ()
static int LunaActor::GetBaseZoomZ (T * p, lua_State * L) inline static
References Actor::GetBaseZoomZ().
GetCommand()
static int LunaActor::GetCommand (T * p, lua_State * L) inline static
References Actor::GetCommand(), and SArg.
GetDestX()
static int LunaActor::GetDestX (T * p, lua_State * L) inline static
References Actor::GetDestX().
GetDestY()
static int LunaActor::GetDestY (T * p, lua_State * L) inline static
References Actor::GetDestY().
GetDestZ()
static int LunaActor::GetDestZ (T * p, lua_State * L) inline static
References Actor::GetDestZ().
GetDiffuseAlpha()
static int LunaActor::GetDiffuseAlpha (T * p, lua_State * L) inline static
GetEffectDelta()
static int LunaActor::GetEffectDelta (T * p, lua_State * L) inline static
References Actor::GetEffectDelta().
geteffectmagnitude()
static int LunaActor::geteffectmagnitude (T * p, lua_State * L) inline static
References Actor::GetEffectMagnitude().
GetFakeParent()
static int LunaActor::GetFakeParent (T * p, lua_State * L) inline static
References Actor::GetFakeParent(), and Actor::PushSelf().
GetHAlign()
static int LunaActor::GetHAlign (T * p, lua_State * L) inline static
References Actor::GetHorizAlign().
GetHeight()
static int LunaActor::GetHeight (T * p, lua_State * L) inline static
References Actor::GetUnzoomedHeight().
GetName()
static int LunaActor::GetName (T * p, lua_State * L) inline static
References Actor::GetName().
GetNumStates()
static int LunaActor::GetNumStates (T * p, lua_State * L) inline static
References Actor::GetNumStates(), and LuaHelpers::Push().
GetNumWrapperStates()
static int LunaActor::GetNumWrapperStates (T * p, lua_State * L) inline static
References Actor::GetNumWrapperStates().
GetParent()
static int LunaActor::GetParent (T * p, lua_State * L) inline static
References Actor::GetParent(), and Actor::PushSelf().
getrotation()
static int LunaActor::getrotation (T * p, lua_State * L) inline static
References Actor::GetRotationX(), Actor::GetRotationY(), and Actor::GetRotationZ().
GetRotationX()
static int LunaActor::GetRotationX (T * p, lua_State * L) inline static
References Actor::GetRotationX().
GetRotationY()
static int LunaActor::GetRotationY (T * p, lua_State * L) inline static
References Actor::GetRotationY().
GetRotationZ()
static int LunaActor::GetRotationZ (T * p, lua_State * L) inline static
References Actor::GetRotationZ().
GetSecsIntoEffect()
static int LunaActor::GetSecsIntoEffect (T * p, lua_State * L) inline static
References Actor::GetSecsIntoEffect().
GETTER_SETTER_BOOL_METHOD()
LunaActor::GETTER_SETTER_BOOL_METHOD (tween_uses_effect_delta)
GetTweenTimeLeft()
static int LunaActor::GetTweenTimeLeft (T * p, lua_State * L) inline static
References Actor::GetTweenTimeLeft().
GetVAlign()
static int LunaActor::GetVAlign (T * p, lua_State * L) inline static
References Actor::GetVertAlign().
GetVisible()
static int LunaActor::GetVisible (T * p, lua_State * L) inline static
References Actor::GetVisible().
GetWidth()
static int LunaActor::GetWidth (T * p, lua_State * L) inline static
References Actor::GetUnzoomedWidth().
GetWrapperState()
static int LunaActor::GetWrapperState (T * p, lua_State * L) inline static
References Actor::GetWrapperState(), and Actor::PushSelf().
GetX()
static int LunaActor::GetX (T * p, lua_State * L) inline static
References Actor::GetX().
GetY()
static int LunaActor::GetY (T * p, lua_State * L) inline static
References Actor::GetY().
GetZ()
static int LunaActor::GetZ (T * p, lua_State * L) inline static
References Actor::GetZ().
GetZoom()
static int LunaActor::GetZoom (T * p, lua_State * L) inline static
References Actor::GetZoom().
GetZoomedHeight()
static int LunaActor::GetZoomedHeight (T * p, lua_State * L) inline static
References Actor::GetZoomedHeight().
GetZoomedWidth()
static int LunaActor::GetZoomedWidth (T * p, lua_State * L) inline static
References Actor::GetZoomedWidth().
GetZoomX()
static int LunaActor::GetZoomX (T * p, lua_State * L) inline static
References Actor::GetZoomX().
GetZoomY()
static int LunaActor::GetZoomY (T * p, lua_State * L) inline static
References Actor::GetZoomY().
GetZoomZ()
static int LunaActor::GetZoomZ (T * p, lua_State * L) inline static
References Actor::GetZoomZ().
glow()
static int LunaActor::glow (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetGlow().
glowblink()
static int LunaActor::glowblink (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectGlowBlink().
glowramp()
static int LunaActor::glowramp (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectGlowRamp().
glowshift()
static int LunaActor::glowshift (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectGlowShift().
halign()
static int LunaActor::halign (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetHorizAlign().
heading()
static int LunaActor::heading (T * p, lua_State * L) inline static
References Actor::AddRotationH(), COMMON_RETURN_SELF, and FArg.
hibernate()
static int LunaActor::hibernate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetHibernate().
horizalign()
static int LunaActor::horizalign (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetHorizAlign().
hurrytweening()
static int LunaActor::hurrytweening (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, FArg, and Actor::HurryTweening().
linear()
static int LunaActor::linear (T * p, lua_State * L) inline static
References Actor::BeginTweening(), COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and TWEEN_LINEAR.
name()
static int LunaActor::name (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, SArg, and Actor::SetName().
pause()
static int LunaActor::pause (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::EnableAnimation().
pitch()
static int LunaActor::pitch (T * p, lua_State * L) inline static
References Actor::AddRotationP(), COMMON_RETURN_SELF, and FArg.
play()
static int LunaActor::play (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::EnableAnimation().
playcommand()
static int LunaActor::playcommand (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Actor::HandleMessage(), SArg, and LuaReference::SetFromStack().
pulse()
static int LunaActor::pulse (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectPulse().
queuecommand()
static int LunaActor::queuecommand (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Actor::QueueCommand(), and SArg.
queuemessage()
static int LunaActor::queuemessage (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Actor::QueueMessage(), and SArg.
rainbow()
static int LunaActor::rainbow (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectRainbow().
RemoveWrapperState()
static int LunaActor::RemoveWrapperState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::RemoveWrapperState().
roll()
static int LunaActor::roll (T * p, lua_State * L) inline static
References Actor::AddRotationR(), COMMON_RETURN_SELF, and FArg.
rotationx()
static int LunaActor::rotationx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetRotationX().
rotationy()
static int LunaActor::rotationy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetRotationY().
rotationz()
static int LunaActor::rotationz (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetRotationZ().
RunCommandsRecursively()
static int LunaActor::RunCommandsRecursively (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Actor::RunCommandsRecursively(), and LuaReference::SetFromStack().
scaletocover()
static int LunaActor::scaletocover (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::ScaleToCover().
scaletofit()
static int LunaActor::scaletofit (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::ScaleToFitInside().
SetFakeParent()
static int LunaActor::SetFakeParent (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Actor::SetFakeParent().
SetHeight()
static int LunaActor::SetHeight (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetHeight().
setsize()
static int LunaActor::setsize (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, Actor::SetHeight(), and Actor::SetWidth().
setstate()
static int LunaActor::setstate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and Actor::SetState().
SetTextureFiltering()
static int LunaActor::SetTextureFiltering (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, and Actor::SetTextureFiltering().
SetWidth()
static int LunaActor::SetWidth (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetWidth().
shadowcolor()
static int LunaActor::shadowcolor (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageColor::FromStackCompat(), and Actor::SetShadowColor().
shadowlength()
static int LunaActor::shadowlength (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetShadowLength().
shadowlengthx()
static int LunaActor::shadowlengthx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetShadowLengthX().
shadowlengthy()
static int LunaActor::shadowlengthy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetShadowLengthY().
skewx()
static int LunaActor::skewx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetSkewX().
skewy()
static int LunaActor::skewy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetSkewY().
sleep()
static int LunaActor::sleep (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and Actor::Sleep().
spin()
static int LunaActor::spin (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetEffectSpin().
spring()
static int LunaActor::spring (T * p, lua_State * L) inline static
References Actor::BeginTweening(), COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and TWEEN_SPRING.
stopeffect()
static int LunaActor::stopeffect (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::StopEffect().
stoptweening()
static int LunaActor::stoptweening (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::StopTweening().
stretchto()
static int LunaActor::stretchto (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::StretchTo().
texturetranslate()
static int LunaActor::texturetranslate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetTextureTranslate().
texturewrapping()
static int LunaActor::texturewrapping (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::SetTextureWrapping().
tween()
static int LunaActor::tween (T * p, lua_State * L) inline static
References Actor::BeginTweening(), COMMON_RETURN_SELF, ITween::CreateFromStack(), FArg, and LuaHelpers::ReportScriptErrorFmt().
valign()
static int LunaActor::valign (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetVertAlign().
vertalign()
static int LunaActor::vertalign (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetVertAlign().
vibrate()
static int LunaActor::vibrate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetEffectVibrate().
visible()
static int LunaActor::visible (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::SetVisible().
wag()
static int LunaActor::wag (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, f, and Actor::SetEffectWag().
x()
static int LunaActor::x (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetX().
xy()
static int LunaActor::xy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetXY().
y()
static int LunaActor::y (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetY().
z()
static int LunaActor::z (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZ().
zbias()
static int LunaActor::zbias (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZBias().
zbuffer()
static int LunaActor::zbuffer (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::SetUseZBuffer().
zoom()
static int LunaActor::zoom (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZoom().
zoomto()
static int LunaActor::zoomto (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::ZoomTo().
zoomtoheight()
static int LunaActor::zoomtoheight (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::ZoomToHeight().
zoomtowidth()
static int LunaActor::zoomtowidth (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::ZoomToWidth().
zoomx()
static int LunaActor::zoomx (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZoomX().
zoomy()
static int LunaActor::zoomy (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZoomY().
zoomz()
static int LunaActor::zoomz (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Actor::SetZoomZ().
ztest()
static int LunaActor::ztest (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, Actor::SetZTestMode(), ZTEST_OFF, and ZTEST_WRITE_ON_PASS.
ztestmode()
static int LunaActor::ztestmode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and Actor::SetZTestMode().
zwrite()
static int LunaActor::zwrite (T * p, lua_State * L) inline static
References BIArg, COMMON_RETURN_SELF, and Actor::SetZWrite().
The documentation for this class was generated from the following file:
Actor.cpp