Etterna: TickcountSegment Struct Reference
TickcountSegment Struct Reference
Identifies when a chart is to have a different tickcount value for hold notes.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
TickcountSegment (int iStartRow=ROW_INVALID, int iTicks=DEFAULT_TICK_COUNT)
TickcountSegment (const TickcountSegment &other)
int GetTicks () const
void SetTicks (int iTicks)
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const TickcountSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Static Public Attributes
static const unsigned DEFAULT_TICK_COUNT = 4
The default amount of ticks per beat.
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Private Attributes
int m_iTicksPerBeat
The amount of hold checkpoints counted per beat.
Detailed Description
Identifies when a chart is to have a different tickcount value for hold notes.
A tickcount segment is used to better replicate the checkpoint hold system used by various based video games. The number is used to represent how many ticks can be counted in one beat.
Constructor & Destructor Documentation
TickcountSegment() [1/2]
TickcountSegment::TickcountSegment (int iStartRow = ROW_INVALID, int iTicks = DEFAULT_TICK_COUNT) inline
Referenced by Copy().
TickcountSegment() [2/2]
TickcountSegment::TickcountSegment (const TickcountSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* TickcountSegment::Copy () const inline override virtual
Implements TimingSegment.
References TickcountSegment().
DebugPrint()
void TickcountSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), TimingSegment::GetRow(), GetTicks(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType TickcountSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetTicks()
int TickcountSegment::GetTicks () const inline
References m_iTicksPerBeat.
Referenced by DebugPrint(), NoteDataUtil::GetTotalHoldTicks(), GetValues(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetType()
TimingSegmentType TickcountSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_TICKCOUNT.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> TickcountSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetTicks().
IsNotable()
bool TickcountSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool TickcountSegment::operator== (const TickcountSegment & other) const inline
References COMPARE, and m_iTicksPerBeat.
Referenced by operator==().
operator==() [2/2]
bool TickcountSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetTicks()
void TickcountSegment::SetTicks (int iTicks) inline
References m_iTicksPerBeat.
ToString()
RString TickcountSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetTicks(), IntToString(), and ssprintf().
Member Data Documentation
DEFAULT_TICK_COUNT
const unsigned TickcountSegment::DEFAULT_TICK_COUNT = 4 static
The default amount of ticks per beat.
Referenced by ProcessTickcounts().
m_iTicksPerBeat
int TickcountSegment::m_iTicksPerBeat private
The amount of hold checkpoints counted per beat.
Referenced by GetTicks(), operator==(), and SetTicks().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp