Etterna: LowLevelWindow_X11 Class Reference
LowLevelWindow_X11 Class Reference
#include <LowLevelWindow_X11.h>
Public Member Functions
LowLevelWindow_X11 ()
~LowLevelWindow_X11 ()
void * GetProcAddress (const RString &s)
RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut)
void LogDebugInformation () const
bool IsSoftwareRenderer (RString &sError)
void SwapBuffers ()
const VideoModeParams * GetActualVideoModeParams () const
void GetDisplayResolutions (DisplayResolutions &out) const
bool SupportsRenderToTexture () const
RenderTarget * CreateRenderTarget ()
bool SupportsThreadedRendering ()
void BeginConcurrentRenderingMainThread ()
void EndConcurrentRenderingMainThread ()
void BeginConcurrentRendering ()
void EndConcurrentRendering ()
Public Member Functions inherited from LowLevelWindow
virtual ~LowLevelWindow ()=default
virtual void Update ()
Private Attributes
bool m_bWasWindowed
VideoModeParams CurrentParams
Additional Inherited Members
Static Public Member Functions inherited from LowLevelWindow
static LowLevelWindow * Create ()
Constructor & Destructor Documentation
LowLevelWindow_X11()
LowLevelWindow_X11::LowLevelWindow_X11 ()
References FAILED_CONNECTION_XSERVER, g_iOldSize, g_OldRotation, g_pScreenConfig, LocalizedString::GetValue(), RageLog::Info(), LOG, and RageException::Throw().
~LowLevelWindow_X11()
LowLevelWindow_X11::~LowLevelWindow_X11 ()
References g_AltWindow, g_iOldSize, g_OldRotation, g_pBackgroundContext, g_pContext, and g_pScreenConfig.
Member Function Documentation
BeginConcurrentRendering()
void LowLevelWindow_X11::BeginConcurrentRendering () virtual
Reimplemented from LowLevelWindow.
References ASSERT, and g_pBackgroundContext.
BeginConcurrentRenderingMainThread()
void LowLevelWindow_X11::BeginConcurrentRenderingMainThread () virtual
Reimplemented from LowLevelWindow.
References ASSERT, g_AltWindow, and g_pContext.
CreateRenderTarget()
RenderTarget * LowLevelWindow_X11::CreateRenderTarget () virtual
Reimplemented from LowLevelWindow.
EndConcurrentRendering()
void LowLevelWindow_X11::EndConcurrentRendering () virtual
Reimplemented from LowLevelWindow.
References ASSERT.
EndConcurrentRenderingMainThread()
void LowLevelWindow_X11::EndConcurrentRenderingMainThread () virtual
Reimplemented from LowLevelWindow.
References ASSERT, and g_pContext.
GetActualVideoModeParams()
const VideoModeParams* LowLevelWindow_X11::GetActualVideoModeParams () const inline virtual
Implements LowLevelWindow.
References CurrentParams.
GetDisplayResolutions()
void LowLevelWindow_X11::GetDisplayResolutions (DisplayResolutions & out) const virtual
Implements LowLevelWindow.
References ASSERT_M.
GetProcAddress()
void * LowLevelWindow_X11::GetProcAddress (const RString & s) virtual
Implements LowLevelWindow.
IsSoftwareRenderer()
bool LowLevelWindow_X11::IsSoftwareRenderer (RString & sError) virtual
Reimplemented from LowLevelWindow.
LogDebugInformation()
void LowLevelWindow_X11::LogDebugInformation () const virtual
Reimplemented from LowLevelWindow.
References RageLog::Info(), and LOG.
SupportsRenderToTexture()
bool LowLevelWindow_X11::SupportsRenderToTexture () const virtual
Reimplemented from LowLevelWindow.
References f.
SupportsThreadedRendering()
bool LowLevelWindow_X11::SupportsThreadedRendering () virtual
Reimplemented from LowLevelWindow.
References g_pBackgroundContext.
SwapBuffers()
void LowLevelWindow_X11::SwapBuffers () virtual
Implements LowLevelWindow.
TryVideoMode()
RString LowLevelWindow_X11::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) virtual
Implements LowLevelWindow.
References ASSERT, ASSERT_M, VideoModeParams::bpp, FAIL_M, g_AltWindow, g_iOldSize, g_OldRotation, g_pBackgroundContext, g_pContext, g_pScreenConfig, VideoModeParams::height, VideoModeParams::sWindowTitle, VideoModeParams::vsync, VideoModeParams::width, and VideoModeParams::windowed.
Member Data Documentation
CurrentParams
VideoModeParams LowLevelWindow_X11::CurrentParams private
Referenced by GetActualVideoModeParams().
m_bWasWindowed
bool LowLevelWindow_X11::m_bWasWindowed private
The documentation for this class was generated from the following files:
LowLevelWindow_X11.h
LowLevelWindow_X11.cpp