Etterna: CachedObjectHelpers Namespace Reference
CachedObjectHelpers Namespace Reference
Utilities for working with the CachedObjects.
Functions
void Lock ()
void Unlock ()
Detailed Description
Utilities for working with the CachedObjects.
Function Documentation
Lock()
void CachedObjectHelpers::Lock ()
References RageMutex::Lock(), and m_Mutex.
Referenced by CachedObjectPointer< Steps >::CachedObjectPointer(), CachedObject< Steps >::ClearCacheAll(), CachedObject< Steps >::ClearCacheNegative(), CachedObject< Steps >::ClearCacheSpecific(), CachedObjectPointer< Steps >::Get(), CachedObjectPointer< Steps >::Set(), and CachedObjectPointer< Steps >::Unset().
Unlock()
void CachedObjectHelpers::Unlock ()
References m_Mutex, and RageMutex::Unlock().
Referenced by CachedObjectPointer< Steps >::CachedObjectPointer(), CachedObject< Steps >::ClearCacheAll(), CachedObject< Steps >::ClearCacheNegative(), CachedObject< Steps >::ClearCacheSpecific(), CachedObjectPointer< Steps >::Get(), CachedObjectPointer< Steps >::Set(), and CachedObjectPointer< Steps >::Unset().