Etterna: LunaBanner Class Reference
LunaBanner Class Reference
Allow Lua to have access to the Banner.
Public Member Functions
LunaBanner ()
Public Member Functions inherited from Luna< Banner >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int scaletoclipped (T *p, lua_State *L)
static int ScaleToClipped (T *p, lua_State *L)
static int LoadFromSong (T *p, lua_State *L)
static int LoadFromCachedBanner (T *p, lua_State *L)
static int LoadIconFromCharacter (T *p, lua_State *L)
static int LoadCardFromCharacter (T *p, lua_State *L)
static int LoadFromSongGroup (T *p, lua_State *L)
static int LoadFromSortOrder (T *p, lua_State *L)
static int GetScrolling (T *p, lua_State *L)
static int SetScrolling (T *p, lua_State *L)
static int GetPercentScrolling (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< Banner >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< Banner >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< Banner >
using T = Banner
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< Banner >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the Banner.
Constructor & Destructor Documentation
LunaBanner()
LunaBanner::LunaBanner () inline
References ADD_METHOD, GetPercentScrolling(), GetScrolling(), LoadCardFromCharacter(), LoadFromCachedBanner(), LoadFromSong(), LoadFromSongGroup(), LoadFromSortOrder(), LoadIconFromCharacter(), scaletoclipped(), ScaleToClipped(), and SetScrolling().
Member Function Documentation
GetPercentScrolling()
static int LunaBanner::GetPercentScrolling (T * p, lua_State * L) inline static
References Banner::ScrollingPercent().
Referenced by LunaBanner().
GetScrolling()
static int LunaBanner::GetScrolling (T * p, lua_State * L) inline static
References Banner::GetScrolling().
Referenced by LunaBanner().
LoadCardFromCharacter()
static int LunaBanner::LoadCardFromCharacter (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Banner::LoadIconFromCharacter().
Referenced by LunaBanner().
LoadFromCachedBanner()
static int LunaBanner::LoadFromCachedBanner (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Banner::LoadFromCachedBanner(), and SArg.
Referenced by LunaBanner().
LoadFromSong()
static int LunaBanner::LoadFromSong (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Banner::LoadFromSong().
Referenced by LunaBanner().
LoadFromSongGroup()
static int LunaBanner::LoadFromSongGroup (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, Banner::LoadFromSongGroup(), and SArg.
Referenced by LunaBanner().
LoadFromSortOrder()
static int LunaBanner::LoadFromSortOrder (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, Banner::LoadFromSortOrder(), and SortOrder_Invalid.
Referenced by LunaBanner().
LoadIconFromCharacter()
static int LunaBanner::LoadIconFromCharacter (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, and Banner::LoadIconFromCharacter().
Referenced by LunaBanner().
scaletoclipped()
static int LunaBanner::scaletoclipped (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::ScaleToClipped().
Referenced by LunaBanner().
ScaleToClipped()
static int LunaBanner::ScaleToClipped (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and Sprite::ScaleToClipped().
Referenced by LunaBanner().
SetScrolling()
static int LunaBanner::SetScrolling (T * p, lua_State * L) inline static
References BArg, COMMON_RETURN_SELF, FArg, and Banner::SetScrolling().
Referenced by LunaBanner().
The documentation for this class was generated from the following file:
Banner.cpp