Etterna: LunaRageFileManager Class Reference
LunaRageFileManager Class Reference
Allow Lua to have access to the RageFileManager.
Public Member Functions
LunaRageFileManager ()
Public Member Functions inherited from Luna< RageFileManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int DoesFileExist (T *p, lua_State *L)
static int GetFileSizeBytes (T *p, lua_State *L)
static int GetHashForFile (T *p, lua_State *L)
static int GetDirListing (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< RageFileManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< RageFileManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< RageFileManager >
using T = RageFileManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< RageFileManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the RageFileManager.
Constructor & Destructor Documentation
LunaRageFileManager()
LunaRageFileManager::LunaRageFileManager () inline
References ADD_METHOD, DoesFileExist(), GetDirListing(), GetFileSizeBytes(), and GetHashForFile().
Member Function Documentation
DoesFileExist()
static int LunaRageFileManager::DoesFileExist (T * p, lua_State * L) inline static
References RageFileManager::DoesFileExist(), and SArg.
Referenced by LunaRageFileManager().
GetDirListing()
static int LunaRageFileManager::GetDirListing (T * p, lua_State * L) inline static
References BArg, LuaHelpers::CreateTableFromArray(), RageFileManager::GetDirListing(), and SArg.
Referenced by LunaRageFileManager().
GetFileSizeBytes()
static int LunaRageFileManager::GetFileSizeBytes (T * p, lua_State * L) inline static
References RageFileManager::GetFileSizeInBytes(), and SArg.
Referenced by LunaRageFileManager().
GetHashForFile()
static int LunaRageFileManager::GetHashForFile (T * p, lua_State * L) inline static
References RageFileManager::GetFileHash(), and SArg.
Referenced by LunaRageFileManager().
The documentation for this class was generated from the following file:
RageFileManager.cpp