Etterna: picosha2 Namespace Reference
picosha2 Namespace Reference
Namespaces
detail
impl
Classes
class hash256_one_by_one
Typedefs
typedef unsigned long word_t
typedef unsigned char byte_t
Functions
template<typename InIter >
void output_hex (InIter first, InIter last, std::ostream &os)
template<typename InIter >
void bytes_to_hex_string (InIter first, InIter last, std::string &hex_str)
template<typename InContainer >
void bytes_to_hex_string (const InContainer &bytes, std::string &hex_str)
template<typename InIter >
std::string bytes_to_hex_string (InIter first, InIter last)
template<typename InContainer >
std::string bytes_to_hex_string (const InContainer &bytes)
void get_hash_hex_string (const hash256_one_by_one &hasher, std::string &hex_str)
std::string get_hash_hex_string (const hash256_one_by_one &hasher)
template<typename InIter , typename OutIter >
void hash256 (InIter first, InIter last, OutIter first2, OutIter last2, int buffer_size=PICOSHA2_BUFFER_SIZE_FOR_INPUT_ITERATOR)
template<typename InIter , typename OutContainer >
void hash256 (InIter first, InIter last, OutContainer &dst)
template<typename InContainer , typename OutIter >
void hash256 (const InContainer &src, OutIter first, OutIter last)
template<typename InContainer , typename OutContainer >
void hash256 (const InContainer &src, OutContainer &dst)
template<typename InIter >
void hash256_hex_string (InIter first, InIter last, std::string &hex_str)
template<typename InIter >
std::string hash256_hex_string (InIter first, InIter last)
void hash256_hex_string (const std::string &src, std::string &hex_str)
template<typename InContainer >
void hash256_hex_string (const InContainer &src, std::string &hex_str)
template<typename InContainer >
std::string hash256_hex_string (const InContainer &src)
template<typename OutIter >
void hash256 (std::ifstream &f, OutIter first, OutIter last)
Variables
static const size_t k_digest_size = 32
Typedef Documentation
byte_t
typedef unsigned char picosha2::byte_t
word_t
typedef unsigned long picosha2::word_t
Function Documentation
bytes_to_hex_string() [1/4]
template<typename InIter > void picosha2::bytes_to_hex_string (InIter first, InIter last, std::string & hex_str)
References output_hex().
Referenced by bytes_to_hex_string(), and get_hash_hex_string().
bytes_to_hex_string() [2/4]
template<typename InContainer > void picosha2::bytes_to_hex_string (const InContainer & bytes, std::string & hex_str)
References bytes_to_hex_string().
bytes_to_hex_string() [3/4]
template<typename InIter > std::string picosha2::bytes_to_hex_string (InIter first, InIter last)
References bytes_to_hex_string().
bytes_to_hex_string() [4/4]
template<typename InContainer > std::string picosha2::bytes_to_hex_string (const InContainer & bytes)
References bytes_to_hex_string().
get_hash_hex_string() [1/2]
void picosha2::get_hash_hex_string (const hash256_one_by_one & hasher, std::string & hex_str) inline
References bytes_to_hex_string(), picosha2::hash256_one_by_one::get_hash_bytes(), and k_digest_size.
Referenced by get_hash_hex_string().
get_hash_hex_string() [2/2]
std::string picosha2::get_hash_hex_string (const hash256_one_by_one & hasher) inline
References get_hash_hex_string().
hash256() [1/5]
template<typename InIter , typename OutIter > void picosha2::hash256 (InIter first, InIter last, OutIter first2, OutIter last2, int buffer_size = PICOSHA2_BUFFER_SIZE_FOR_INPUT_ITERATOR)
References picosha2::impl::hash256_impl().
Referenced by hash256(), and hash256_hex_string().
hash256() [2/5]
template<typename InIter , typename OutContainer > void picosha2::hash256 (InIter first, InIter last, OutContainer & dst)
References hash256().
hash256() [3/5]
template<typename InContainer , typename OutIter > void picosha2::hash256 (const InContainer & src, OutIter first, OutIter last)
References hash256().
hash256() [4/5]
template<typename InContainer , typename OutContainer > void picosha2::hash256 (const InContainer & src, OutContainer & dst)
References hash256().
hash256() [5/5]
template<typename OutIter > void picosha2::hash256 (std::ifstream & f, OutIter first, OutIter last)
References hash256().
hash256_hex_string() [1/5]
template<typename InIter > void picosha2::hash256_hex_string (InIter first, InIter last, std::string & hex_str)
References hash256(), k_digest_size, and output_hex().
Referenced by HighScore::GenerateValidationKeys(), and hash256_hex_string().
hash256_hex_string() [2/5]
template<typename InIter > std::string picosha2::hash256_hex_string (InIter first, InIter last)
References hash256_hex_string().
hash256_hex_string() [3/5]
void picosha2::hash256_hex_string (const std::string & src, std::string & hex_str) inline
References hash256_hex_string().
hash256_hex_string() [4/5]
template<typename InContainer > void picosha2::hash256_hex_string (const InContainer & src, std::string & hex_str)
References hash256_hex_string().
hash256_hex_string() [5/5]
template<typename InContainer > std::string picosha2::hash256_hex_string (const InContainer & src)
References hash256_hex_string().
output_hex()
template<typename InIter > void picosha2::output_hex (InIter first, InIter last, std::ostream & os)
Referenced by bytes_to_hex_string(), and hash256_hex_string().
Variable Documentation
k_digest_size
const size_t picosha2::k_digest_size = 32 static
Referenced by get_hash_hex_string(), and hash256_hex_string().