Etterna: RageInputDevice.h File Reference
RageInputDevice.h File Reference
#include "global.h"
#include "EnumHelper.h"
#include <chrono>
Classes
struct InputDeviceInfo
struct DeviceInput
Macros
#define FOREACH_InputDevice(i) FOREACH_ENUM(InputDevice, i)
A special foreach loop for each input device.
Typedefs
typedef vector< DeviceInput > DeviceInputList
Enumerations
enum InputDevice {
DEVICE_KEYBOARD = 0, DEVICE_JOY1, DEVICE_JOY2, DEVICE_JOY3,
DEVICE_JOY4, DEVICE_JOY5, DEVICE_JOY6, DEVICE_JOY7,
DEVICE_JOY8, DEVICE_JOY9, DEVICE_JOY10, DEVICE_JOY11,
DEVICE_JOY12, DEVICE_JOY13, DEVICE_JOY14, DEVICE_JOY15,
DEVICE_JOY16, DEVICE_JOY17, DEVICE_JOY18, DEVICE_JOY19,
DEVICE_JOY20, DEVICE_JOY21, DEVICE_JOY22, DEVICE_JOY23,
DEVICE_JOY24, DEVICE_JOY25, DEVICE_JOY26, DEVICE_JOY27,
DEVICE_JOY28, DEVICE_JOY29, DEVICE_JOY30, DEVICE_JOY31,
DEVICE_JOY32, DEVICE_PUMP1, DEVICE_PUMP2, DEVICE_MIDI,
DEVICE_MOUSE, DEVICE_PIUIO, NUM_InputDevice, InputDevice_Invalid
}
enum InputDeviceState {
InputDeviceState_Connected, InputDeviceState_Unplugged, InputDeviceState_NeedsMultitap, InputDeviceState_NoInputHandler,
NUM_InputDeviceState, InputDeviceState_Invalid
}
enum DeviceButton {
KEY_SPACE = 32, KEY_EXCL = 33, KEY_QUOTE = 34, KEY_HASH = 35,
KEY_DOLLAR = 36, KEY_PERCENT = 37, KEY_AMPER = 38, KEY_SQUOTE = 39,
KEY_LPAREN = 40, KEY_RPAREN = 41, KEY_ASTERISK = 42, KEY_PLUS = 43,
KEY_COMMA = 44, KEY_HYPHEN = 45, KEY_PERIOD = 46, KEY_SLASH = 47,
KEY_C0 = 48, KEY_C1 = 49, KEY_C2 = 50, KEY_C3 = 51,
KEY_C4 = 52, KEY_C5 = 53, KEY_C6 = 54, KEY_C7 = 55,
KEY_C8 = 56, KEY_C9 = 57, KEY_COLON = 58, KEY_SEMICOLON = 59,
KEY_LANGLE = 60, KEY_EQUAL = 61, KEY_RANGLE = 62, KEY_QUESTION = 63,
KEY_AT = 64, KEY_CA = 65, KEY_CB = 66, KEY_CC = 67,
KEY_CD = 68, KEY_CE = 69, KEY_CF = 70, KEY_CG = 71,
KEY_CH = 72, KEY_CI = 73, KEY_CJ = 74, KEY_CK = 75,
KEY_CL = 76, KEY_CM = 77, KEY_CN = 78, KEY_CO = 79,
KEY_CP = 80, KEY_CQ = 81, KEY_CR = 82, KEY_CS = 83,
KEY_CT = 84, KEY_CU = 85, KEY_CV = 86, KEY_CW = 87,
KEY_CX = 88, KEY_CY = 89, KEY_CZ = 90, KEY_LBRACKET = 91,
KEY_BACKSLASH = 92, KEY_RBRACKET = 93, KEY_CARAT = 94, KEY_UNDERSCORE = 95,
KEY_ACCENT = 96, KEY_Ca = 97, KEY_Cb = 98, KEY_Cc = 99,
KEY_Cd = 100, KEY_Ce = 101, KEY_Cf = 102, KEY_Cg = 103,
KEY_Ch = 104, KEY_Ci = 105, KEY_Cj = 106, KEY_Ck = 107,
KEY_Cl = 108, KEY_Cm = 109, KEY_Cn = 110, KEY_Co = 111,
KEY_Cp = 112, KEY_Cq = 113, KEY_Cr = 114, KEY_Cs = 115,
KEY_Ct = 116, KEY_Cu = 117, KEY_Cv = 118, KEY_Cw = 119,
KEY_Cx = 120, KEY_Cy = 121, KEY_Cz = 122, KEY_LBRACE = 123,
KEY_PIPE = 124, KEY_RBRACE = 125, KEY_DEL = 127, KEY_BACK,
KEY_TAB, KEY_ENTER, KEY_PAUSE, KEY_ESC,
KEY_F1, KEY_F2, KEY_F3, KEY_F4,
KEY_F5, KEY_F6, KEY_F7, KEY_F8,
KEY_F9, KEY_F10, KEY_F11, KEY_F12,
KEY_F13, KEY_F14, KEY_F15, KEY_F16,
KEY_LCTRL, KEY_RCTRL, KEY_LSHIFT, KEY_RSHIFT,
KEY_LALT, KEY_RALT, KEY_LMETA, KEY_RMETA,
KEY_LSUPER, KEY_RSUPER, KEY_MENU, KEY_FN,
KEY_NUMLOCK, KEY_SCRLLOCK, KEY_CAPSLOCK, KEY_PRTSC,
KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT,
KEY_INSERT, KEY_HOME, KEY_END, KEY_PGUP,
KEY_PGDN, KEY_KP_C0, KEY_KP_C1, KEY_KP_C2,
KEY_KP_C3, KEY_KP_C4, KEY_KP_C5, KEY_KP_C6,
KEY_KP_C7, KEY_KP_C8, KEY_KP_C9, KEY_KP_SLASH,
KEY_KP_ASTERISK, KEY_KP_HYPHEN, KEY_KP_PLUS, KEY_KP_PERIOD,
KEY_KP_EQUAL, KEY_KP_ENTER, KEY_OTHER_0, KEY_LAST_OTHER = 511,
JOY_LEFT, JOY_RIGHT, JOY_UP, JOY_DOWN,
JOY_LEFT_2, JOY_RIGHT_2, JOY_UP_2, JOY_DOWN_2,
JOY_Z_UP, JOY_Z_DOWN, JOY_ROT_UP, JOY_ROT_DOWN,
JOY_ROT_LEFT, JOY_ROT_RIGHT, JOY_ROT_Z_UP, JOY_ROT_Z_DOWN,
JOY_HAT_LEFT, JOY_HAT_RIGHT, JOY_HAT_UP, JOY_HAT_DOWN,
JOY_AUX_1, JOY_AUX_2, JOY_AUX_3, JOY_AUX_4,
JOY_BUTTON_1, JOY_BUTTON_2, JOY_BUTTON_3, JOY_BUTTON_4,
JOY_BUTTON_5, JOY_BUTTON_6, JOY_BUTTON_7, JOY_BUTTON_8,
JOY_BUTTON_9, JOY_BUTTON_10, JOY_BUTTON_11, JOY_BUTTON_12,
JOY_BUTTON_13, JOY_BUTTON_14, JOY_BUTTON_15, JOY_BUTTON_16,
JOY_BUTTON_17, JOY_BUTTON_18, JOY_BUTTON_19, JOY_BUTTON_20,
JOY_BUTTON_21, JOY_BUTTON_22, JOY_BUTTON_23, JOY_BUTTON_24,
JOY_BUTTON_25, JOY_BUTTON_26, JOY_BUTTON_27, JOY_BUTTON_28,
JOY_BUTTON_29, JOY_BUTTON_30, JOY_BUTTON_31, JOY_BUTTON_32,
MIDI_FIRST = 600, MIDI_LAST = 699, MOUSE_LEFT = 700, MOUSE_RIGHT,
MOUSE_MIDDLE, MOUSE_X_LEFT, MOUSE_X_RIGHT, MOUSE_Y_UP,
MOUSE_Y_DOWN, MOUSE_WHEELUP, MOUSE_WHEELDOWN, NUM_DeviceButton,
DeviceButton_Invalid
}
Functions
const RString & InputDeviceToString (InputDevice i)
InputDevice StringToInputDevice (const RString &s)
bool IsJoystick (InputDevice id)
bool IsPump (InputDevice id)
bool IsMouse (InputDevice id)
bool operator== (InputDeviceInfo const &lhs, InputDeviceInfo const &rhs)
bool operator!= (InputDeviceInfo const &lhs, InputDeviceInfo const &rhs)
const RString & InputDeviceStateToString (InputDeviceState ids)
RString DeviceButtonToString (DeviceButton i)
DeviceButton StringToDeviceButton (const RString &s)
bool operator== (DeviceInput const &lhs, DeviceInput const &rhs)
bool operator!= (DeviceInput const &lhs, DeviceInput const &rhs)
bool operator< (DeviceInput const &lhs, DeviceInput const &rhs)
bool operator> (DeviceInput const &lhs, DeviceInput const &rhs)
bool operator<= (DeviceInput const &lhs, DeviceInput const &rhs)
bool operator>= (DeviceInput const &lhs, DeviceInput const &rhs)
Variables
const int NUM_JOYSTICKS = 32
const int NUM_PUMPS = 2
Macro Definition Documentation
FOREACH_InputDevice
#define FOREACH_InputDevice (i) FOREACH_ENUM(InputDevice, i)
A special foreach loop for each input device.
Referenced by InputFilter::Reset().
Typedef Documentation
DeviceInputList
typedef vector<DeviceInput> DeviceInputList
Enumeration Type Documentation
DeviceButton
enum DeviceButton
Enumerator
KEY_SPACE
KEY_EXCL
KEY_QUOTE
KEY_HASH
KEY_DOLLAR
KEY_PERCENT
KEY_AMPER
KEY_SQUOTE
KEY_LPAREN
KEY_RPAREN
KEY_ASTERISK
KEY_PLUS
KEY_COMMA
KEY_HYPHEN
KEY_PERIOD
KEY_SLASH
KEY_C0
KEY_C1
KEY_C2
KEY_C3
KEY_C4
KEY_C5
KEY_C6
KEY_C7
KEY_C8
KEY_C9
KEY_COLON
KEY_SEMICOLON
KEY_LANGLE
KEY_EQUAL
KEY_RANGLE
KEY_QUESTION
KEY_AT
KEY_CA
KEY_CB
KEY_CC
KEY_CD
KEY_CE
KEY_CF
KEY_CG
KEY_CH
KEY_CI
KEY_CJ
KEY_CK
KEY_CL
KEY_CM
KEY_CN
KEY_CO
KEY_CP
KEY_CQ
KEY_CR
KEY_CS
KEY_CT
KEY_CU
KEY_CV
KEY_CW
KEY_CX
KEY_CY
KEY_CZ
KEY_LBRACKET
KEY_BACKSLASH
KEY_RBRACKET
KEY_CARAT
KEY_UNDERSCORE
KEY_ACCENT
KEY_Ca
KEY_Cb
KEY_Cc
KEY_Cd
KEY_Ce
KEY_Cf
KEY_Cg
KEY_Ch
KEY_Ci
KEY_Cj
KEY_Ck
KEY_Cl
KEY_Cm
KEY_Cn
KEY_Co
KEY_Cp
KEY_Cq
KEY_Cr
KEY_Cs
KEY_Ct
KEY_Cu
KEY_Cv
KEY_Cw
KEY_Cx
KEY_Cy
KEY_Cz
KEY_LBRACE
KEY_PIPE
KEY_RBRACE
KEY_DEL
KEY_BACK
KEY_TAB
KEY_ENTER
KEY_PAUSE
KEY_ESC
KEY_F1
KEY_F2
KEY_F3
KEY_F4
KEY_F5
KEY_F6
KEY_F7
KEY_F8
KEY_F9
KEY_F10
KEY_F11
KEY_F12
KEY_F13
KEY_F14
KEY_F15
KEY_F16
KEY_LCTRL
KEY_RCTRL
KEY_LSHIFT
KEY_RSHIFT
KEY_LALT
KEY_RALT
KEY_LMETA
KEY_RMETA
KEY_LSUPER
KEY_RSUPER
KEY_MENU
KEY_FN
KEY_NUMLOCK
KEY_SCRLLOCK
KEY_CAPSLOCK
KEY_PRTSC
KEY_UP
KEY_DOWN
KEY_LEFT
KEY_RIGHT
KEY_INSERT
KEY_HOME
KEY_END
KEY_PGUP
KEY_PGDN
KEY_KP_C0
KEY_KP_C1
KEY_KP_C2
KEY_KP_C3
KEY_KP_C4
KEY_KP_C5
KEY_KP_C6
KEY_KP_C7
KEY_KP_C8
KEY_KP_C9
KEY_KP_SLASH
KEY_KP_ASTERISK
KEY_KP_HYPHEN
KEY_KP_PLUS
KEY_KP_PERIOD
KEY_KP_EQUAL
KEY_KP_ENTER
KEY_OTHER_0
KEY_LAST_OTHER
JOY_LEFT
JOY_RIGHT
JOY_UP
JOY_DOWN
JOY_LEFT_2
JOY_RIGHT_2
JOY_UP_2
JOY_DOWN_2
JOY_Z_UP
JOY_Z_DOWN
JOY_ROT_UP
JOY_ROT_DOWN
JOY_ROT_LEFT
JOY_ROT_RIGHT
JOY_ROT_Z_UP
JOY_ROT_Z_DOWN
JOY_HAT_LEFT
JOY_HAT_RIGHT
JOY_HAT_UP
JOY_HAT_DOWN
JOY_AUX_1
JOY_AUX_2
JOY_AUX_3
JOY_AUX_4
JOY_BUTTON_1
JOY_BUTTON_2
JOY_BUTTON_3
JOY_BUTTON_4
JOY_BUTTON_5
JOY_BUTTON_6
JOY_BUTTON_7
JOY_BUTTON_8
JOY_BUTTON_9
JOY_BUTTON_10
JOY_BUTTON_11
JOY_BUTTON_12
JOY_BUTTON_13
JOY_BUTTON_14
JOY_BUTTON_15
JOY_BUTTON_16
JOY_BUTTON_17
JOY_BUTTON_18
JOY_BUTTON_19
JOY_BUTTON_20
JOY_BUTTON_21
JOY_BUTTON_22
JOY_BUTTON_23
JOY_BUTTON_24
JOY_BUTTON_25
JOY_BUTTON_26
JOY_BUTTON_27
JOY_BUTTON_28
JOY_BUTTON_29
JOY_BUTTON_30
JOY_BUTTON_31
JOY_BUTTON_32
MIDI_FIRST
MIDI_LAST
MOUSE_LEFT
MOUSE_RIGHT
MOUSE_MIDDLE
MOUSE_X_LEFT
MOUSE_X_RIGHT
MOUSE_Y_UP
MOUSE_Y_DOWN
MOUSE_WHEELUP
MOUSE_WHEELDOWN
NUM_DeviceButton
DeviceButton_Invalid
InputDevice
enum InputDevice
Enumerator
DEVICE_KEYBOARD
DEVICE_JOY1
DEVICE_JOY2
DEVICE_JOY3
DEVICE_JOY4
DEVICE_JOY5
DEVICE_JOY6
DEVICE_JOY7
DEVICE_JOY8
DEVICE_JOY9
DEVICE_JOY10
DEVICE_JOY11
DEVICE_JOY12
DEVICE_JOY13
DEVICE_JOY14
DEVICE_JOY15
DEVICE_JOY16
DEVICE_JOY17
DEVICE_JOY18
DEVICE_JOY19
DEVICE_JOY20
DEVICE_JOY21
DEVICE_JOY22
DEVICE_JOY23
DEVICE_JOY24
DEVICE_JOY25
DEVICE_JOY26
DEVICE_JOY27
DEVICE_JOY28
DEVICE_JOY29
DEVICE_JOY30
DEVICE_JOY31
DEVICE_JOY32
DEVICE_PUMP1
DEVICE_PUMP2
DEVICE_MIDI
DEVICE_MOUSE
DEVICE_PIUIO
NUM_InputDevice
InputDevice_Invalid
InputDeviceState
enum InputDeviceState
Enumerator
InputDeviceState_Connected
InputDeviceState_Unplugged
InputDeviceState_NeedsMultitap
InputDeviceState_NoInputHandler
NUM_InputDeviceState
InputDeviceState_Invalid
Function Documentation
DeviceButtonToString()
RString DeviceButtonToString (DeviceButton i)
References g_mapNamesToString, InitNames(), JOY_BUTTON_1, JOY_BUTTON_32, KEY_LAST_OTHER, KEY_OTHER_0, MIDI_FIRST, MIDI_LAST, and ssprintf().
Referenced by InputHandler::GetDeviceSpecificInputString(), RageInput::GetLocalizedInputString(), InputHandler::GetLocalizedInputString(), and DeviceInput::ToString().
InputDeviceStateToString()
const RString& InputDeviceStateToString (InputDeviceState ids)
Referenced by ControllerStateDisplay::Update().
InputDeviceToString()
const RString& InputDeviceToString (InputDevice i)
Referenced by InputHandler::GetDeviceSpecificInputString(), RageInput::GetDisplayDevicesString(), and DeviceInput::ToString().
IsJoystick()
bool IsJoystick (InputDevice id) inline
References DEVICE_JOY1, and NUM_JOYSTICKS.
Referenced by InputMapper::CheckForChangedInputDevicesAndRemap(), DeviceInput::IsJoystick(), and MakeDevice().
IsMouse()
bool IsMouse (InputDevice id) inline
References DEVICE_MOUSE.
Referenced by DeviceInput::IsMouse().
IsPump()
bool IsPump (InputDevice id) inline
References DEVICE_PUMP1, and NUM_PUMPS.
Referenced by MakeDevice().
operator!=() [1/2]
bool operator!= (InputDeviceInfo const & lhs, InputDeviceInfo const & rhs) inline
References operator==().
operator!=() [2/2]
bool operator!= (DeviceInput const & lhs, DeviceInput const & rhs) inline
References operator==().
operator<()
bool operator< (DeviceInput const & lhs, DeviceInput const & rhs) inline
References DeviceInput::button, and DeviceInput::device.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (DeviceInput const & lhs, DeviceInput const & rhs) inline
References operator<().
operator==() [1/2]
bool operator== (InputDeviceInfo const & lhs, InputDeviceInfo const & rhs) inline
References InputDeviceInfo::id, and InputDeviceInfo::sDesc.
Referenced by operator!=().
operator==() [2/2]
bool operator== (DeviceInput const & lhs, DeviceInput const & rhs) inline
References DeviceInput::button, and DeviceInput::device.
operator>()
bool operator> (DeviceInput const & lhs, DeviceInput const & rhs) inline
References operator<().
operator>=()
bool operator>= (DeviceInput const & lhs, DeviceInput const & rhs) inline
References operator<().
StringToDeviceButton()
DeviceButton StringToDeviceButton (const RString & s)
References DeviceButton_Invalid, enum_add2(), g_mapStringToNames, InitNames(), JOY_BUTTON_1, KEY_OTHER_0, MIDI_FIRST, and MOUSE_LEFT.
Referenced by DeviceInput::FromString(), and LunaInputFilter::IsBeingPressed().
StringToInputDevice()
InputDevice StringToInputDevice (const RString & s)
Referenced by DeviceInput::FromString(), and LunaInputFilter::IsBeingPressed().
Variable Documentation
NUM_JOYSTICKS
const int NUM_JOYSTICKS = 32
Referenced by EnumDevicesCallback(), and IsJoystick().
NUM_PUMPS
const int NUM_PUMPS = 2
Referenced by InputHandler_Win32_Pump::GetDevicesAndDescriptions(), InputHandler_Win32_Pump::InputHandler_Win32_Pump(), InputHandler_Win32_Pump::InputThreadMain(), IsPump(), and InputHandler_Win32_Pump::Update().