Etterna: StatsManager Class Reference
StatsManager Class Reference
Managed non-persisted statistics.
#include <StatsManager.h>
Public Member Functions
StatsManager ()
~StatsManager ()
void Reset ()
void GetFinalEvalStageStats (StageStats &statsOut) const
void CalcAccumPlayedStageStats ()
StageStats & GetAccumPlayedStageStats ()
void UnjoinPlayer (PlayerNumber pn)
void GetStepsInUse (set< Steps *> &apInUseOut) const
void PushSelf (lua_State *L)
Static Public Member Functions
static void CommitStatsToProfiles (const StageStats *pSS)
Public Attributes
StageStats m_CurStageStats
The current Stage stats.
vector< StageStats > m_vPlayedStageStats
Private Attributes
StageStats m_AccumPlayedStageStats
Detailed Description
Managed non-persisted statistics.
Constructor & Destructor Documentation
StatsManager()
StatsManager::StatsManager ()
References LuaManager::Get(), L, LUA, PushSelf(), and LuaManager::Release().
~StatsManager()
StatsManager::~StatsManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
CalcAccumPlayedStageStats()
void StatsManager::CalcAccumPlayedStageStats ()
References AccumPlayedStageStats(), m_AccumPlayedStageStats, and m_vPlayedStageStats.
Referenced by Reset(), and ScreenGameplay::StageFinished().
CommitStatsToProfiles()
void StatsManager::CommitStatsToProfiles (const StageStats * pSS) static
References AddPlayerStatsToProfile(), ProfileManager::AddStepTotals(), FOREACH_HumanPlayer, GAMESTATE, ProfileManager::GetProfile(), LOG, GameState::m_bMultiplayer, StageStats::m_fGameplaySeconds, Profile::m_iNumTotalSongsPlayed, Profile::m_iTotalGameplaySeconds, StageStats::m_player, PlayerStageStats::m_radarActual, StageStats::m_vpPlayedSongs, PROFILEMAN, RadarCategory_Hands, RadarCategory_Holds, RadarCategory_Jumps, RadarCategory_Lifts, RadarCategory_Mines, RadarCategory_Rolls, RadarCategory_TapsAndHolds, and RageLog::Trace().
Referenced by GameState::CommitStageStats().
GetAccumPlayedStageStats()
StageStats& StatsManager::GetAccumPlayedStageStats () inline
References m_AccumPlayedStageStats.
Referenced by LunaStatsManager::GetAccumPlayedStageStats(), and ScoreDisplayAliveTime::UpdateNumber().
GetFinalEvalStageStats()
void StatsManager::GetFinalEvalStageStats (StageStats & statsOut) const
References AccumPlayedStageStats(), StageStats::Init(), and m_vPlayedStageStats.
Referenced by LunaStatsManager::GetBestFinalGrade(), LunaStatsManager::GetFinalEvalStageStats(), LunaStatsManager::GetFinalGrade(), GameState::GetRankingFeats(), and ScreenEvaluation::Init().
GetStepsInUse()
void StatsManager::GetStepsInUse (set< Steps *> & apInUseOut) const
References FOREACH_MultiPlayer, FOREACH_PlayerNumber, m_vPlayedStageStats, and PlayerStageStats::m_vpPossibleSteps.
Referenced by SongManager::FreeAllLoadedFromProfile().
PushSelf()
void StatsManager::PushSelf (lua_State * L)
Referenced by StatsManager().
Reset()
void StatsManager::Reset ()
References CalcAccumPlayedStageStats(), StageStats::Init(), m_AccumPlayedStageStats, m_CurStageStats, and m_vPlayedStageStats.
Referenced by GameState::Reset(), and LunaStatsManager::Reset().
UnjoinPlayer()
void StatsManager::UnjoinPlayer (PlayerNumber pn)
References FOREACH, FOREACH_MultiPlayer, FOREACH_PlayerNumber, PlayerStageStats::m_bJoined, StageStats::m_multiPlayer, StageStats::m_player, and m_vPlayedStageStats.
Referenced by GameState::UnjoinPlayer().
Member Data Documentation
m_AccumPlayedStageStats
StageStats StatsManager::m_AccumPlayedStageStats private
Referenced by CalcAccumPlayedStageStats(), GetAccumPlayedStageStats(), and Reset().
m_CurStageStats
StageStats StatsManager::m_CurStageStats
The current Stage stats.
This is not necessarily passed stage stats if this is an Extra Stage.
Referenced by GameState::BeginStage(), Player::ChangeLifeRecord(), Player::ChangeWifeRecord(), GameState::CommitStageStats(), DancingCharacters::DrawPrimitives(), GameState::FinishStage(), LunaStatsManager::GetBestGrade(), GameState::GetCourseSongIndex(), LunaStatsManager::GetCurStageStats(), LifeMeterTime::GetLifeSeconds(), PlayerInfo::GetPlayerStageStats(), GameState::GetStageResult(), LunaStatsManager::GetWorstGrade(), Player::HandleHoldCheckpoint(), ScreenGameplayLesson::HandleScreenMessage(), ScreenGameplay::HandleScreenMessage(), Player::HandleTapRowScore(), ScreenHowToPlay::Init(), ScreenEvaluation::Init(), Player::Init(), ScreenGameplay::Init(), BackgroundImpl::IsDangerAllVisible(), ScreenGameplay::LoadNextSong(), SMOProtocol::ReportScore(), Reset(), ScreenGameplayLesson::ResetAndRestartCurrentSong(), GameState::ResetStageStatistics(), ScreenGameplay::SetSongPosition(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::StageFinished(), ScreenGameplay::ToggleReplayPause(), ScoreDisplayOni::Update(), Player::Update(), ScreenGameplay::Update(), Player::UpdateHoldNotes(), and ScoreDisplayAliveTime::UpdateNumber().
m_vPlayedStageStats
vector<StageStats> StatsManager::m_vPlayedStageStats
Referenced by CalcAccumPlayedStageStats(), LunaStatsManager::GetBestFinalGrade(), GetFinalEvalStageStats(), LunaStatsManager::GetPlayedStageStats(), GameState::GetRankingFeats(), LunaStatsManager::GetStagesPlayed(), GetStepsInUse(), ScreenEvaluation::Init(), Reset(), ScreenSelectMusic::SelectCurrent(), LunaScreenSelectMusic::ShowEvalScreenForScore(), ScreenGameplay::StageFinished(), and UnjoinPlayer().
The documentation for this class was generated from the following files:
StatsManager.h
StatsManager.cpp