Etterna: SongUtil.cpp File Reference
SongUtil.cpp File Reference
#include "CommonMetrics.h"
#include "EnumHelper.h"
#include "Foreach.h"
#include "GameManager.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "LuaBinding.h"
#include "PrefsManager.h"
#include "Profile.h"
#include "ProfileManager.h"
#include "RageLog.h"
#include "Song.h"
#include "SongManager.h"
#include "Steps.h"
#include "StepsUtil.h"
#include "Style.h"
#include "ThemeMetric.h"
#include "XmlFile.h"
#include "global.h"
Functions
static RString RemoveInitialWhitespace (RString s)
Remove the initial whitespace characters.
static bool CompareSongPointersBySortValueAscending (const Song *pSong1, const Song *pSong2)
static bool CompareSongPointersBySortValueDescending (const Song *pSong1, const Song *pSong2)
static bool CompareSongPointersByTitle (const Song *pSong1, const Song *pSong2)
static bool CompareSongPointersByMSD (const Song *pSong1, const Song *pSong2, Skillset ss)
static bool CompareSongPointersByBPM (const Song *pSong1, const Song *pSong2)
static bool CompareSongPointersByLength (const Song *pSong1, const Song *pSong2)
void AppendOctal (int n, int digits, RString &out)
static bool CompDescending (const pair< Song *, int > &a, const pair< Song *, int > &b)
static bool CompAscending (const pair< Song *, int > &a, const pair< Song *, int > &b)
static int CompareSongPointersByGenre (const Song *pSong1, const Song *pSong2)
static int CompareSongPointersByGroupAndTitle (const Song *pSong1, const Song *pSong2)
static int CompareSongPointersByGroup (const Song *pSong1, const Song *pSong2)
std::function< int(const Song *pSong1, const Song *pSong2)> CompareSongPointersByGroupAndMSD (Skillset ss)
Variables
ThemeMetric< int > SORT_BPM_DIVISION ("MusicWheel", "SortBPMDivision")
ThemeMetric< bool > SHOW_SECTIONS_IN_BPM_SORT ("MusicWheel", "ShowSectionsInBPMSort")
static LocalizedString SORT_NOT_AVAILABLE ("Sort", "NotAvailable")
static LocalizedString SORT_OTHER ("Sort", "Other")
static map< const Song *, RString > g_mapSongSortVal
static LocalizedString YOU_MUST_SUPPLY_NAME ("SongUtil", "You must supply a name for your new edit.")
static LocalizedString CHART_NAME_CONFLICTS ("SongUtil", "The name you chose conflicts with " "another chart. Please use a " "different name.")
static LocalizedString EDIT_NAME_CONFLICTS ("SongUtil", "The name you chose conflicts with " "another edit. Please use a " "different name.")
static LocalizedString CHART_NAME_CANNOT_CONTAIN ("SongUtil", "The chart name cannot contain any of the following characters: %s")
static LocalizedString EDIT_NAME_CANNOT_CONTAIN ("SongUtil", "The edit name cannot contain any of the following characters: %s")
static LocalizedString AUTHOR_NAME_CANNOT_CONTAIN ("SongUtil", "The step author's name cannot contain any of the following characters: %s")
static LocalizedString PREVIEW_DOES_NOT_EXIST ("SongUtil", "The preview file '%s' does not exist.")
static LocalizedString MUSIC_DOES_NOT_EXIST ("SongUtil", "The music file '%s' does not exist.")
Function Documentation
AppendOctal()
void AppendOctal (int n, int digits, RString & out)
CompareSongPointersByBPM()
static bool CompareSongPointersByBPM (const Song * pSong1, const Song * pSong2) static
References CompareRStringsAsc(), Song::GetDisplayBpms(), DisplayBpms::GetMax(), and Song::GetSongFilePath().
Referenced by SongUtil::SortSongPointerArrayByBPM().
CompareSongPointersByGenre()
static int CompareSongPointersByGenre (const Song * pSong1, const Song * pSong2) static
References Song::m_sGenre.
Referenced by SongUtil::SortSongPointerArrayByGenre().
CompareSongPointersByGroup()
static int CompareSongPointersByGroup (const Song * pSong1, const Song * pSong2) static
References Song::m_sGroupName.
Referenced by CompareSongPointersByGroupAndMSD().
CompareSongPointersByGroupAndMSD()
std::function<int(const Song* pSong1, const Song* pSong2)> CompareSongPointersByGroupAndMSD (Skillset ss)
References CompareSongPointersByGroup(), and CompareSongPointersByMSD().
Referenced by SongUtil::SortSongPointerArrayByGroupAndMSD().
CompareSongPointersByGroupAndTitle()
static int CompareSongPointersByGroupAndTitle (const Song * pSong1, const Song * pSong2) static
References SongUtil::CompareSongPointersByGroup(), and CompareSongPointersByTitle().
Referenced by SongUtil::SortSongPointerArrayByGroupAndTitle().
CompareSongPointersByLength()
static bool CompareSongPointersByLength (const Song * pSong1, const Song * pSong2) static
References CompareRStringsAsc(), Song::GetSongFilePath(), and Song::m_fMusicLengthSeconds.
Referenced by SongUtil::SortSongPointerArrayByLength().
CompareSongPointersByMSD()
static bool CompareSongPointersByMSD (const Song * pSong1, const Song * pSong2, Skillset ss) static
References StdString::CStdStr< CT >::CompareNoCase(), GAMESTATE, ModsGroup< T >::Get(), Song::GetHighestOfSkillsetAllSteps(), Song::GetSongFilePath(), SongOptions::m_fMusicRate, GameState::m_SongOptions, and ModsLevel_Current.
Referenced by CompareSongPointersByGroupAndMSD().
CompareSongPointersBySortValueAscending()
static bool CompareSongPointersBySortValueAscending (const Song * pSong1, const Song * pSong2) static
References g_mapSongSortVal.
Referenced by SongUtil::SortSongPointerArrayByArtist(), SongUtil::SortSongPointerArrayByDisplayArtist(), SongUtil::SortSongPointerArrayByNumPlays(), SongUtil::SortSongPointerArrayBySectionName(), and SongUtil::SortSongPointerArrayByStepsTypeAndMeter().
CompareSongPointersBySortValueDescending()
static bool CompareSongPointersBySortValueDescending (const Song * pSong1, const Song * pSong2) static
References g_mapSongSortVal.
Referenced by SongUtil::SortSongPointerArrayByNumPlays().
CompareSongPointersByTitle()
static bool CompareSongPointersByTitle (const Song * pSong1, const Song * pSong2) static
References StdString::CStdStr< CT >::CompareNoCase(), Song::GetSongFilePath(), Song::GetTranslitMainTitle(), Song::GetTranslitSubTitle(), and SongUtil::MakeSortString().
Referenced by CompareSongPointersByGroupAndTitle(), and SongUtil::SortSongPointerArrayByTitle().
CompAscending()
static bool CompAscending (const pair< Song *, int > & a, const pair< Song *, int > & b) static
Referenced by SongUtil::SortSongPointerArrayByGrades().
CompDescending()
static bool CompDescending (const pair< Song *, int > & a, const pair< Song *, int > & b) static
Referenced by SongUtil::SortSongPointerArrayByGrades().
RemoveInitialWhitespace()
static RString RemoveInitialWhitespace (RString s) static
Remove the initial whitespace characters.
Parameters
s the string to left trim.
Returns
the trimmed string.
Referenced by SongUtil::DeleteDuplicateSteps().
Variable Documentation
AUTHOR_NAME_CANNOT_CONTAIN
LocalizedString AUTHOR_NAME_CANNOT_CONTAIN("SongUtil", "The step author's name cannot contain any of the following characters: %s") static
Referenced by SongUtil::ValidateCurrentStepsCredit().
CHART_NAME_CANNOT_CONTAIN
LocalizedString CHART_NAME_CANNOT_CONTAIN("SongUtil", "The chart name cannot contain any of the following characters: %s") static
Referenced by SongUtil::ValidateCurrentStepsChartName().
CHART_NAME_CONFLICTS
LocalizedString CHART_NAME_CONFLICTS("SongUtil", "The name you chose conflicts with " "another chart. Please use a " "different name.") static
Referenced by SongUtil::ValidateCurrentStepsChartName().
EDIT_NAME_CANNOT_CONTAIN
LocalizedString EDIT_NAME_CANNOT_CONTAIN("SongUtil", "The edit name cannot contain any of the following characters: %s") static
Referenced by SongUtil::ValidateCurrentEditStepsDescription().
EDIT_NAME_CONFLICTS
LocalizedString EDIT_NAME_CONFLICTS("SongUtil", "The name you chose conflicts with " "another edit. Please use a " "different name.") static
Referenced by SongUtil::ValidateCurrentEditStepsDescription().
g_mapSongSortVal
map<const Song*, RString> g_mapSongSortVal static
Referenced by CompareSongPointersBySortValueAscending(), CompareSongPointersBySortValueDescending(), SongUtil::SortSongPointerArrayByArtist(), SongUtil::SortSongPointerArrayByDisplayArtist(), SongUtil::SortSongPointerArrayByNumPlays(), SongUtil::SortSongPointerArrayBySectionName(), and SongUtil::SortSongPointerArrayByStepsTypeAndMeter().
MUSIC_DOES_NOT_EXIST
LocalizedString MUSIC_DOES_NOT_EXIST("SongUtil", "The music file '%s' does not exist.") static
Referenced by SongUtil::ValidateCurrentStepsMusic().
PREVIEW_DOES_NOT_EXIST
LocalizedString PREVIEW_DOES_NOT_EXIST("SongUtil", "The preview file '%s' does not exist.") static
Referenced by SongUtil::ValidateCurrentSongPreview().
SHOW_SECTIONS_IN_BPM_SORT
ThemeMetric<bool> SHOW_SECTIONS_IN_BPM_SORT("MusicWheel", "ShowSectionsInBPMSort")
Referenced by SongUtil::GetSectionNameFromSongAndSort().
SORT_BPM_DIVISION
ThemeMetric<int> SORT_BPM_DIVISION("MusicWheel", "SortBPMDivision")
Referenced by SongUtil::GetSectionNameFromSongAndSort().
SORT_NOT_AVAILABLE
LocalizedString SORT_NOT_AVAILABLE("Sort", "NotAvailable") static
Referenced by SongUtil::GetSectionNameFromSongAndSort().
SORT_OTHER
LocalizedString SORT_OTHER("Sort", "Other") static
Referenced by SongUtil::GetSectionNameFromSongAndSort(), and SongUtil::SortSongPointerArrayBySectionName().
YOU_MUST_SUPPLY_NAME
LocalizedString YOU_MUST_SUPPLY_NAME("SongUtil", "You must supply a name for your new edit.") static
Referenced by SongUtil::ValidateCurrentEditStepsDescription().