Etterna: RageSoundReader_Resample_Good Class Reference
RageSoundReader_Resample_Good Class Reference
This class changes the sampling rate of a sound.
#include <RageSoundReader_Resample_Good.h>
Public Member Functions
RageSoundReader_Resample_Good (RageSoundReader *pSource, int iSampleRate)
RageSoundReader_Resample_Good (const RageSoundReader_Resample_Good &cpy)
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
~RageSoundReader_Resample_Good () override
RageSoundReader_Resample_Good * Copy () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
void SetRate (float fRatio)
Change the rate of a sound without changing the sample rate.
float GetRate () const
Retrieve the exact rate.
int GetSampleRate () const override
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
unsigned GetNumChannels () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Member Functions
void Reset ()
void ReopenResampler ()
void GetFactors (int &iDownFactor, int &iUpFactor) const
Private Attributes
vector< RageSoundResampler_Polyphase * > m_apResamplers
int m_iSampleRate
float m_fRate
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Detailed Description
This class changes the sampling rate of a sound.
Constructor & Destructor Documentation
RageSoundReader_Resample_Good() [1/2]
RageSoundReader_Resample_Good::RageSoundReader_Resample_Good (RageSoundReader * pSource, int iSampleRate)
References m_fRate, m_iSampleRate, and ReopenResampler().
Referenced by Copy().
RageSoundReader_Resample_Good() [2/2]
RageSoundReader_Resample_Good::RageSoundReader_Resample_Good (const RageSoundReader_Resample_Good & cpy)
References m_apResamplers, m_fRate, and m_iSampleRate.
~RageSoundReader_Resample_Good()
RageSoundReader_Resample_Good::~RageSoundReader_Resample_Good () override
References m_apResamplers.
Member Function Documentation
Copy()
RageSoundReader_Resample_Good * RageSoundReader_Resample_Good::Copy () const override virtual
Implements RageSoundReader.
References RageSoundReader_Resample_Good().
GetFactors()
void RageSoundReader_Resample_Good::GetFactors (int & iDownFactor, int & iUpFactor) const private
References RageSoundReader::GetSampleRate(), m_fRate, m_iSampleRate, and RageSoundReader_Filter::m_pSource.
Referenced by Read(), ReopenResampler(), and SetRate().
GetNextSourceFrame()
int RageSoundReader_Resample_Good::GetNextSourceFrame () const override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader::GetNextSourceFrame(), RageSoundReader::GetSampleRate(), m_apResamplers, m_iSampleRate, and RageSoundReader_Filter::m_pSource.
GetRate()
float RageSoundReader_Resample_Good::GetRate () const
Retrieve the exact rate.
Returns
the exact rate.
References m_fRate.
Referenced by RageSoundReader_PitchChange::Read(), and Read().
GetSampleRate()
int RageSoundReader_Resample_Good::GetSampleRate () const inline override virtual
Reimplemented from RageSoundReader_Filter.
References m_iSampleRate.
GetStreamToSourceRatio()
float RageSoundReader_Resample_Good::GetStreamToSourceRatio () const override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader::GetStreamToSourceRatio(), m_fRate, and RageSoundReader_Filter::m_pSource.
Read()
int RageSoundReader_Resample_Good::Read (float * pBuf, int iFrames) override virtual
Reimplemented from RageSoundReader_Filter.
References ASSERT, f, GetFactors(), GetRate(), m_apResamplers, RageSoundReader_Filter::m_pSource, and RageSoundReader::Read().
ReopenResampler()
void RageSoundReader_Resample_Good::ReopenResampler () private
References GetFactors(), RageSoundReader::GetNumChannels(), m_apResamplers, m_fRate, and RageSoundReader_Filter::m_pSource.
Referenced by RageSoundReader_Resample_Good(), and SetRate().
Reset()
void RageSoundReader_Resample_Good::Reset () private
References RageSoundReader::GetNumChannels(), m_apResamplers, and RageSoundReader_Filter::m_pSource.
Referenced by SetPosition().
SetPosition()
int RageSoundReader_Resample_Good::SetPosition (int iFrame) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader::GetSampleRate(), m_iSampleRate, RageSoundReader_Filter::m_pSource, Reset(), SCALE, and RageSoundReader::SetPosition().
SetProperty()
bool RageSoundReader_Resample_Good::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Filter::m_pSource, RageSoundReader::SetProperty(), and SetRate().
SetRate()
void RageSoundReader_Resample_Good::SetRate (float fRatio)
Change the rate of a sound without changing the sample rate.
Parameters
fRatio the ratio for changing.
References ASSERT, GetFactors(), m_apResamplers, m_fRate, and ReopenResampler().
Referenced by RageSoundReader_PitchChange::Read(), and SetProperty().
Member Data Documentation
m_apResamplers
vector<RageSoundResampler_Polyphase*> RageSoundReader_Resample_Good::m_apResamplers private
Referenced by GetNextSourceFrame(), RageSoundReader_Resample_Good(), Read(), ReopenResampler(), Reset(), SetRate(), and ~RageSoundReader_Resample_Good().
m_fRate
float RageSoundReader_Resample_Good::m_fRate private
Referenced by GetFactors(), GetRate(), GetStreamToSourceRatio(), RageSoundReader_Resample_Good(), ReopenResampler(), and SetRate().
m_iSampleRate
int RageSoundReader_Resample_Good::m_iSampleRate private
Referenced by GetFactors(), GetNextSourceFrame(), GetSampleRate(), RageSoundReader_Resample_Good(), and SetPosition().
The documentation for this class was generated from the following files:
RageSoundReader_Resample_Good.h
RageSoundReader_Resample_Good.cpp