Etterna: InputMapper Class Reference
InputMapper Class Reference
Holds user-chosen input preferences and saves it between sessions.
#include <InputMapper.h>
Public Member Functions
InputMapper ()
~InputMapper ()
void SetInputScheme (const InputScheme *pInputScheme)
const InputScheme * GetInputScheme () const
void SetJoinControllers (PlayerNumber pn)
void ReadMappingsFromDisk ()
void SaveMappingsToDisk ()
void ResetMappingsToDefault ()
void CheckButtonAndAddToReason (GameButton menu, vector< RString > &full_reason, RString const &sub_reason)
void SanityCheckMappings (vector< RString > &reason)
void ClearAllMappings ()
void SetInputMap (const DeviceInput &DeviceI, const GameInput &GameI, int iSlotIndex)
void ClearFromInputMap (const DeviceInput &DeviceI)
bool ClearFromInputMap (const GameInput &GameI, int iSlotIndex)
void AddDefaultMappingsForCurrentGameIfUnmapped ()
void AutoMapJoysticksForCurrentGame ()
bool CheckForChangedInputDevicesAndRemap (RString &sMessageOut)
bool IsMapped (const DeviceInput &DeviceI) const
bool DeviceToGame (const DeviceInput &DeviceI, GameInput &GameI) const
bool GameToDevice (const GameInput &GameI, int iSlotNum, DeviceInput &DeviceI) const
GameButton GameButtonToMenuButton (GameButton gb) const
void MenuToGame (GameButton MenuI, PlayerNumber pn, vector< GameInput > &GameIout) const
PlayerNumber ControllerToPlayerNumber (GameController controller) const
float GetSecsHeld (const GameInput &GameI, MultiPlayer mp=MultiPlayer_Invalid) const
float GetSecsHeld (GameButton MenuI, PlayerNumber pn) const
bool IsBeingPressed (const GameInput &GameI, MultiPlayer mp=MultiPlayer_Invalid, const DeviceInputList *pButtonState=NULL) const
bool IsBeingPressed (GameButton MenuI, PlayerNumber pn) const
bool IsBeingPressed (const vector< GameInput > &GameI, MultiPlayer mp=MultiPlayer_Invalid, const DeviceInputList *pButtonState=NULL) const
void ResetKeyRepeat (const GameInput &GameI)
void ResetKeyRepeat (GameButton MenuI, PlayerNumber pn)
void RepeatStopKey (const GameInput &GameI)
void RepeatStopKey (GameButton MenuI, PlayerNumber pn)
float GetLevel (const GameInput &GameI) const
float GetLevel (GameButton MenuI, PlayerNumber pn) const
void Unmap (InputDevice device)
void ApplyMapping (const vector< AutoMappingEntry > &vMmaps, GameController gc, InputDevice id)
Static Public Member Functions
static InputDevice MultiPlayerToInputDevice (MultiPlayer mp)
static MultiPlayer InputDeviceToMultiPlayer (InputDevice id)
Protected Member Functions
void UpdateTempDItoGI ()
Protected Attributes
InputMappings m_mappings
const InputScheme * m_pInputScheme
Private Member Functions
InputMapper (const InputMapper &rhs)
InputMapper & operator= (const InputMapper &rhs)
Detailed Description
Holds user-chosen input preferences and saves it between sessions.
Constructor & Destructor Documentation
InputMapper() [1/2]
InputMapper::InputMapper ()
References m_pInputScheme, and PLAYER_INVALID.
~InputMapper()
InputMapper::~InputMapper ()
References SaveMappingsToDisk().
InputMapper() [2/2]
InputMapper::InputMapper (const InputMapper & rhs) private
Member Function Documentation
AddDefaultMappingsForCurrentGameIfUnmapped()
void InputMapper::AddDefaultMappingsForCurrentGameIfUnmapped ()
References ClearFromInputMap(), DEVICE_KEYBOARD, FOREACH, FOREACH_CONST, FOREACH_ENUM, GameController_1, GameController_2, IsMapped(), GameInput::IsValid(), InputScheme::m_pAutoMappings, m_pInputScheme, AutoMappings::m_vMaps, and SetInputMap().
Referenced by ScreenMapControllers::Input(), ReadMappingsFromDisk(), ResetMappingsToDefault(), and ScreenMapControllers::Update().
ApplyMapping()
void InputMapper::ApplyMapping (const vector< AutoMappingEntry > & vMmaps, GameController gc, InputDevice id)
References FOREACH_CONST, NUM_GameController, and SetInputMap().
Referenced by AutoMapJoysticksForCurrentGame().
AutoMapJoysticksForCurrentGame()
void InputMapper::AutoMapJoysticksForCurrentGame ()
References ApplyMapping(), ARRAYLEN, AUTOMAPPINGS_DIR, DeviceInput::button, Regex::Compare(), StdString::CStdStr< CT >::EqualsNoCase(), FOREACH_CONST, FOREACH_ENUM, GameController_1, RageInput::GetDevicesAndDescriptions(), GetDirListing(), RageLog::Info(), INPUTMAN, DeviceInput::IsValid(), LOG, InputMappings::m_GItoDI, m_pInputScheme, InputMappings::m_sDescription, InputMappings::m_sDeviceRegex, AutoMappings::m_sGame, InputScheme::m_szName, AutoMappings::m_vMaps, NUM_GAME_TO_DEVICE_SLOTS, NUM_GameController, InputMappings::ReadMappings(), and Unmap().
Referenced by CheckForChangedInputDevicesAndRemap().
CheckButtonAndAddToReason()
void InputMapper::CheckButtonAndAddToReason (GameButton menu, vector< RString > & full_reason, RString const & sub_reason)
References FOREACH, FOREACH_ENUM, FOREACH_GameButtonInScheme, GetInputScheme(), InputMappings::m_GItoDI, m_mappings, InputScheme::MenuButtonToGameInputs(), NUM_GAME_TO_DEVICE_SLOTS, and PLAYER_1.
Referenced by SanityCheckMappings().
CheckForChangedInputDevicesAndRemap()
bool InputMapper::CheckForChangedInputDevicesAndRemap (RString & sMessageOut)
References AutoMapJoysticksForCurrentGame(), AUTOMAPPING_ALL_JOYSTICKS, MessageManager::Broadcast(), CONNECTED, DISCONNECTED, g_bAutoMapOnJoyChange, g_sLastSeenInputDevices, GetConnectsDisconnects(), RageInput::GetDevicesAndDescriptions(), LocalizedString::GetValue(), RageLog::Info(), INPUTMAN, IsJoystick(), Rage::join(), LOG, Message_AutoJoyMappingApplied, MESSAGEMAN, PREFSMAN, SaveMappingsToDisk(), PrefsManager::SavePrefsToDisk(), and split().
Referenced by GameLoop::RunGameLoop(), and sm_main().
ClearAllMappings()
void InputMapper::ClearAllMappings ()
References InputMappings::Clear(), m_mappings, and UpdateTempDItoGI().
ClearFromInputMap() [1/2]
void InputMapper::ClearFromInputMap (const DeviceInput & DeviceI)
References InputMappings::ClearFromInputMap(), m_mappings, and UpdateTempDItoGI().
Referenced by AddDefaultMappingsForCurrentGameIfUnmapped(), and ScreenMapControllers::Input().
ClearFromInputMap() [2/2]
bool InputMapper::ClearFromInputMap (const GameInput & GameI, int iSlotIndex)
References InputMappings::ClearFromInputMap(), m_mappings, and UpdateTempDItoGI().
ControllerToPlayerNumber()
PlayerNumber InputMapper::ControllerToPlayerNumber (GameController controller) const
References GameController_Invalid, and PLAYER_INVALID.
Referenced by CodeDetector::ChangeScrollSpeed(), CodeDetector::DetectAndAdjustMusicOptions(), and HandleInputEvents().
DeviceToGame()
bool InputMapper::DeviceToGame (const DeviceInput & DeviceI, GameInput & GameI) const
References GameInput::controller, and GameController_Invalid.
Referenced by InputFilter::CheckButtonChange(), HandleInputEvents(), and InputList::Update().
GameButtonToMenuButton()
GameButton InputMapper::GameButtonToMenuButton (GameButton gb) const
References InputScheme::GameButtonToMenuButton(), and m_pInputScheme.
Referenced by HandleInputEvents().
GameToDevice()
bool InputMapper::GameToDevice (const GameInput & GameI, int iSlotNum, DeviceInput & DeviceI) const
References GameInput::button, GameInput::controller, DeviceInput::device, InputDevice_Invalid, InputMappings::m_GItoDI, and m_mappings.
Referenced by GetLevel(), GetSecsHeld(), IsBeingPressed(), ScreenMapControllers::Refresh(), RepeatStopKey(), and ResetKeyRepeat().
GetInputScheme()
const InputScheme * InputMapper::GetInputScheme () const
References m_pInputScheme.
Referenced by CheckButtonAndAddToReason(), Style::ColToButtonName(), ScreenMapControllers::Init(), ScreenSelectMusic::Init(), ScreenSelectMusic::Input(), InputQueueCode::Load(), Screen::PassInputToLua(), Style::StyleInputToGameInput(), and InputList::Update().
GetLevel() [1/2]
float InputMapper::GetLevel (const GameInput & GameI) const
References GameInput::button, GameButton_Invalid, GameToDevice(), InputFilter::GetLevel(), INPUTFILTER, max(), and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by GetLevel(), and SoundEffectControl::Update().
GetLevel() [2/2]
float InputMapper::GetLevel (GameButton MenuI, PlayerNumber pn) const
References GameButton_Invalid, GetLevel(), max(), and MenuToGame().
GetSecsHeld() [1/2]
float InputMapper::GetSecsHeld (const GameInput & GameI, MultiPlayer mp = MultiPlayer_Invalid) const
References GameInput::button, DeviceInput::device, GameButton_Invalid, GameToDevice(), InputFilter::GetSecsHeld(), INPUTFILTER, max(), MultiPlayer_Invalid, MultiPlayerToInputDevice(), and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by Player::CrossedRows(), and GetSecsHeld().
GetSecsHeld() [2/2]
float InputMapper::GetSecsHeld (GameButton MenuI, PlayerNumber pn) const
References GameButton_Invalid, GetSecsHeld(), max(), and MenuToGame().
InputDeviceToMultiPlayer()
MultiPlayer InputMapper::InputDeviceToMultiPlayer (InputDevice id) static
References DEVICE_JOY1, enum_add2(), InputDevice_Invalid, MultiPlayer_Invalid, and MultiPlayer_P1.
Referenced by HandleInputEvents().
IsBeingPressed() [1/3]
bool InputMapper::IsBeingPressed (const GameInput & GameI, MultiPlayer mp = MultiPlayer_Invalid, const DeviceInputList * pButtonState = NULL) const
References GameInput::button, DeviceInput::device, GameButton_Invalid, GameToDevice(), INPUTFILTER, InputFilter::IsBeingPressed(), MultiPlayer_Invalid, MultiPlayerToInputDevice(), and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by Player::CrossedRows(), InputQueueCode::EnteredCode(), ScreenSelectMusic::Input(), OptionsList::Input(), IsBeingPressed(), ScreenNetSelectMusic::LeftAndRightPressed(), ScreenSetTime::MenuStart(), ScreenSelectMusic::MenuStart(), ScreenOptions::MenuStart(), ScreenOptions::MenuUpDown(), Player::Update(), ControllerStateDisplay::Update(), and Player::UpdateHoldNotes().
IsBeingPressed() [2/3]
bool InputMapper::IsBeingPressed (GameButton MenuI, PlayerNumber pn) const
References GameButton_Invalid, IsBeingPressed(), and MenuToGame().
IsBeingPressed() [3/3]
bool InputMapper::IsBeingPressed (const vector< GameInput > & GameI, MultiPlayer mp = MultiPlayer_Invalid, const DeviceInputList * pButtonState = NULL) const
References IsBeingPressed().
IsMapped()
bool InputMapper::IsMapped (const DeviceInput & DeviceI) const
Referenced by AddDefaultMappingsForCurrentGameIfUnmapped().
MenuToGame()
void InputMapper::MenuToGame (GameButton MenuI, PlayerNumber pn, vector< GameInput > & GameIout) const
References m_pInputScheme, InputScheme::MenuButtonToGameInputs(), and PLAYER_INVALID.
Referenced by GetLevel(), GetSecsHeld(), IsBeingPressed(), RepeatStopKey(), and ResetKeyRepeat().
MultiPlayerToInputDevice()
InputDevice InputMapper::MultiPlayerToInputDevice (MultiPlayer mp) static
References DEVICE_JOY1, enum_add2(), InputDevice_Invalid, and MultiPlayer_Invalid.
Referenced by GetSecsHeld(), IsBeingPressed(), and ControllerStateDisplay::Update().
operator=()
InputMapper& InputMapper::operator= (const InputMapper & rhs) private
ReadMappingsFromDisk()
void InputMapper::ReadMappingsFromDisk ()
References AddDefaultMappingsForCurrentGameIfUnmapped(), SpecialFiles::KEYMAPS_PATH, m_mappings, m_pInputScheme, InputMappings::ReadMappings(), and UpdateTempDItoGI().
Referenced by StepMania::InitializeCurrentGame(), ScreenMapControllers::ReloadFromDisk(), and SetInputScheme().
RepeatStopKey() [1/2]
void InputMapper::RepeatStopKey (const GameInput & GameI)
References GameInput::button, GameButton_Invalid, GameToDevice(), INPUTFILTER, NUM_GAME_TO_DEVICE_SLOTS, and InputFilter::RepeatStopKey().
Referenced by HandleInputEvents(), and RepeatStopKey().
RepeatStopKey() [2/2]
void InputMapper::RepeatStopKey (GameButton MenuI, PlayerNumber pn)
References GameButton_Invalid, MenuToGame(), and RepeatStopKey().
ResetKeyRepeat() [1/2]
void InputMapper::ResetKeyRepeat (const GameInput & GameI)
References GameInput::button, GameButton_Invalid, GameToDevice(), INPUTFILTER, NUM_GAME_TO_DEVICE_SLOTS, and InputFilter::ResetKeyRepeat().
Referenced by ScreenSelectMusic::Input(), ScreenOptions::Input(), and ResetKeyRepeat().
ResetKeyRepeat() [2/2]
void InputMapper::ResetKeyRepeat (GameButton MenuI, PlayerNumber pn)
References GameButton_Invalid, MenuToGame(), and ResetKeyRepeat().
ResetMappingsToDefault()
void InputMapper::ResetMappingsToDefault ()
References AddDefaultMappingsForCurrentGameIfUnmapped(), InputMappings::Clear(), m_mappings, and UpdateTempDItoGI().
Referenced by ScreenMapControllers::ClearToDefault(), and DebugLineResetKeyMapping::DoAndLog().
SanityCheckMappings()
void InputMapper::SanityCheckMappings (vector< RString > & reason)
References CheckButtonAndAddToReason(), GAME_BUTTON_MENULEFT, GAME_BUTTON_MENURIGHT, GAME_BUTTON_OPERATOR, and GAME_BUTTON_START.
Referenced by ScreenMapControllers::SanityCheckWrapper().
SaveMappingsToDisk()
void InputMapper::SaveMappingsToDisk ()
References SpecialFiles::KEYMAPS_PATH, m_mappings, m_pInputScheme, and InputMappings::WriteMappings().
Referenced by CheckForChangedInputDevicesAndRemap(), DebugLineResetKeyMapping::DoAndLog(), ScreenMapControllers::SaveToDisk(), and ~InputMapper().
SetInputMap()
void InputMapper::SetInputMap (const DeviceInput & DeviceI, const GameInput & GameI, int iSlotIndex)
References m_mappings, InputMappings::SetInputMap(), and UpdateTempDItoGI().
Referenced by AddDefaultMappingsForCurrentGameIfUnmapped(), ApplyMapping(), and ScreenMapControllers::Update().
SetInputScheme()
void InputMapper::SetInputScheme (const InputScheme * pInputScheme)
References m_pInputScheme, and ReadMappingsFromDisk().
Referenced by StepMania::InitializeCurrentGame().
SetJoinControllers()
void InputMapper::SetJoinControllers (PlayerNumber pn)
Referenced by GameState::SetCurrentStyle().
Unmap()
void InputMapper::Unmap (InputDevice device)
References m_mappings, InputMappings::Unmap(), and UpdateTempDItoGI().
Referenced by AutoMapJoysticksForCurrentGame().
UpdateTempDItoGI()
void InputMapper::UpdateTempDItoGI () protected
References FOREACH_ENUM, DeviceInput::IsValid(), InputMappings::m_GItoDI, m_mappings, and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by ClearAllMappings(), ClearFromInputMap(), ReadMappingsFromDisk(), ResetMappingsToDefault(), SetInputMap(), and Unmap().
Member Data Documentation
m_mappings
InputMappings InputMapper::m_mappings protected
Referenced by CheckButtonAndAddToReason(), ClearAllMappings(), ClearFromInputMap(), GameToDevice(), ReadMappingsFromDisk(), ResetMappingsToDefault(), SaveMappingsToDisk(), SetInputMap(), Unmap(), and UpdateTempDItoGI().
m_pInputScheme
const InputScheme* InputMapper::m_pInputScheme protected
Referenced by AddDefaultMappingsForCurrentGameIfUnmapped(), AutoMapJoysticksForCurrentGame(), GameButtonToMenuButton(), GetInputScheme(), InputMapper(), MenuToGame(), ReadMappingsFromDisk(), SaveMappingsToDisk(), and SetInputScheme().
The documentation for this class was generated from the following files:
InputMapper.h
InputMapper.cpp