Etterna: RageSoundReader_MP3.h File Reference
RageSoundReader_MP3.h File Reference
#include "RageFile.h"
#include "RageSoundReader_FileReader.h"
Classes
class RageSoundReader_MP3
Typedefs
typedef unsigned long id3_length_t
Functions
signed long id3_tag_query (const unsigned char *data, id3_length_t length)
void fill_frame_index_cache (madlib_t *mad)
Typedef Documentation
id3_length_t
typedef unsigned long id3_length_t
Function Documentation
fill_frame_index_cache()
void fill_frame_index_cache (madlib_t * mad)
References get_this_frame_byte(), madlib_t::Timer, madlib_t::timer_accurate, and madlib_t::tocmap.
Referenced by RageSoundReader_MP3::do_mad_frame_decode().
id3_tag_query()
signed long id3_tag_query (const unsigned char * data, id3_length_t length)
References ID3_TAG_FLAG_FOOTERPRESENT, parse_header(), TAGTYPE_ID3V1, TAGTYPE_ID3V2, TAGTYPE_ID3V2_FOOTER, and TAGTYPE_NONE.
Referenced by RageSoundReader_MP3::do_mad_frame_decode().