Etterna: NotesWriterDWI.cpp File Reference
NotesWriterDWI.cpp File Reference
#include "global.h"
#include "NotesWriterDWI.h"
#include "NoteData.h"
#include "NoteDataUtil.h"
#include "NoteTypes.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "Song.h"
#include "Steps.h"
Functions
RString OptimizeDWIString (RString holds, RString taps)
Shrink the file contents as best as possible.
static char OptimizeDWIPair (char c1, char c2)
Optimize an individual pair of characters whenever possible.
static RString NotesToDWIString (const TapNote tnCols[6])
Turn the Notes into a DWI string without angle brackets whenever possible.
static RString NotesToDWIString (TapNote tnCol1, TapNote tnCol2, TapNote tnCol3, TapNote tnCol4, TapNote tnCol5, TapNote tnCol6)
Turn the Notes into a DWI string without angle brackets whenever possible.
static RString NotesToDWIString (TapNote tnCol1, TapNote tnCol2, TapNote tnCol3, TapNote tnCol4)
Turn the Notes into a DWI string without angle brackets whenever possible.
static void WriteDWINotesField (RageFile &f, const Steps &out, int start)
Write out the notes for a DWI file.
static bool WriteDWINotesTag (RageFile &f, const Steps &out)
Attempt to write a DWI's #NOTES tag.
Variables
static const int BEATS_PER_MEASURE = 4
The number of beats per measure for a DWI file.
Function Documentation
NotesToDWIString() [1/3]
static RString NotesToDWIString (const TapNote tnCols[6]) static
Turn the Notes into a DWI string without angle brackets whenever possible.
Parameters
tnCols the columns of TapNotes in question.
Returns
the DWI'ed string.
References OptimizeDWIString(), TapNoteType_Empty, TapNoteType_HoldHead, and TapNoteType_Mine.
Referenced by NotesToDWIString(), and WriteDWINotesField().
NotesToDWIString() [2/3]
static RString NotesToDWIString (TapNote tnCol1, TapNote tnCol2, TapNote tnCol3, TapNote tnCol4, TapNote tnCol5, TapNote tnCol6) static
Turn the Notes into a DWI string without angle brackets whenever possible.
Parameters
tnCol1 the first column.
tnCol2 the second column.
tnCol3 the third column.
tnCol4 the fourth column.
tnCol5 the fifth column.
tnCol6 the sisth column.
Returns
the DWI'ed string.
References NotesToDWIString().
NotesToDWIString() [3/3]
static RString NotesToDWIString (TapNote tnCol1, TapNote tnCol2, TapNote tnCol3, TapNote tnCol4) static
Turn the Notes into a DWI string without angle brackets whenever possible.
Parameters
tnCol1 the first column.
tnCol2 the second column.
tnCol3 the third column.
tnCol4 the fourth column.
Returns
the DWI'ed string.
References NotesToDWIString(), and TAP_EMPTY.
OptimizeDWIPair()
static char OptimizeDWIPair (char c1, char c2) static
Optimize an individual pair of characters whenever possible.
Parameters
c1 the first character.
c2 the second character.
Returns
the one singular character.
References ASSERT, and swap().
Referenced by OptimizeDWIString().
OptimizeDWIString()
RString OptimizeDWIString (RString holds, RString taps)
Shrink the file contents as best as possible.
Parameters
holds the holds in the file.
taps the taps in the file.
Returns
the optimized string.
References ASSERT, OptimizeDWIPair(), and ssprintf().
Referenced by NotesToDWIString().
WriteDWINotesField()
static void WriteDWINotesField (RageFile & f, const Steps & out, int start) static
Write out the notes for a DWI file.
Parameters
f the file to write out to.
out the Steps in question.
start the starting position.
References ASSERT_M, BEATS_PER_MEASURE, BeatToNoteRow(), FAIL_M, NoteData::GetLastBeat(), Steps::GetNoteData(), NoteDataUtil::GetSmallestNoteTypeForMeasure(), NoteData::GetTapNote(), NoteDataUtil::InsertHoldTails(), Steps::m_StepsType, NOTE_TYPE_12TH, NOTE_TYPE_16TH, NOTE_TYPE_192ND, NOTE_TYPE_24TH, NOTE_TYPE_32ND, NOTE_TYPE_48TH, NOTE_TYPE_4TH, NOTE_TYPE_64TH, NOTE_TYPE_8TH, NotesToDWIString(), NoteType_Invalid, RageFile::PutLine(), NoteData::SetTapNote(), ssprintf(), StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, TAP_EMPTY, and RageFile::Write().
Referenced by NotesWriterDWI::Write().
WriteDWINotesTag()
static bool WriteDWINotesTag (RageFile & f, const Steps & out) static
Attempt to write a DWI's #NOTES tag.
Parameters
f the file to write out to.
out the Steps in question.
Returns
its success or failure.
References Difficulty_Beginner, Difficulty_Challenge, Difficulty_Easy, Difficulty_Edit, Difficulty_Hard, Difficulty_Medium, FAIL_M, Steps::GetDifficulty(), Steps::GetMeter(), LOG, Steps::m_StepsType, RageFile::PutLine(), ssprintf(), StepsType_dance_couple, StepsType_dance_double, StepsType_dance_single, StepsType_dance_solo, RageLog::Trace(), and RageFile::Write().
Referenced by NotesWriterDWI::Write().
Variable Documentation
BEATS_PER_MEASURE
const int BEATS_PER_MEASURE = 4 static
The number of beats per measure for a DWI file.
Referenced by WriteDWINotesField().