Etterna: LockNoteSkin Class Reference
LockNoteSkin Class Reference
#include <NoteSkinManager.h>
Public Member Functions
LockNoteSkin (RString sNoteSkin, PlayerNumber pn)
~LockNoteSkin ()
Constructor & Destructor Documentation
LockNoteSkin()
LockNoteSkin::LockNoteSkin (RString sNoteSkin, PlayerNumber pn) inline
References ASSERT, NoteSkinManager::GetCurrentNoteSkin(), and NoteSkinManager::SetCurrentNoteSkin().
~LockNoteSkin()
LockNoteSkin::~LockNoteSkin () inline
References NoteSkinManager::SetCurrentNoteSkin().
The documentation for this class was generated from the following file:
NoteSkinManager.h