Etterna: LunaStatsManager Class Reference
LunaStatsManager Class Reference
Allow Lua to have access to the StatsManager.
Public Member Functions
LunaStatsManager ()
Public Member Functions inherited from Luna< StatsManager >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetCurStageStats (T *p, lua_State *L)
static int GetPlayedStageStats (T *p, lua_State *L)
static int Reset (T *p, lua_State *L)
static int GetAccumPlayedStageStats (T *p, lua_State *L)
static int GetFinalEvalStageStats (T *p, lua_State *L)
static int GetFinalGrade (T *p, lua_State *L)
static int GetStagesPlayed (T *p, lua_State *L)
static int GetBestGrade (T *p, lua_State *L)
static int GetWorstGrade (T *p, lua_State *L)
static int GetBestFinalGrade (T *t, lua_State *L)
Static Public Member Functions inherited from Luna< StatsManager >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< StatsManager >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< StatsManager >
using T = StatsManager
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< StatsManager >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the StatsManager.
Constructor & Destructor Documentation
LunaStatsManager()
LunaStatsManager::LunaStatsManager () inline
References ADD_METHOD, GetAccumPlayedStageStats(), GetBestFinalGrade(), GetBestGrade(), GetCurStageStats(), GetFinalEvalStageStats(), GetFinalGrade(), GetPlayedStageStats(), GetStagesPlayed(), GetWorstGrade(), and Reset().
Member Function Documentation
GetAccumPlayedStageStats()
static int LunaStatsManager::GetAccumPlayedStageStats (T * p, lua_State * L) inline static
References StatsManager::GetAccumPlayedStageStats(), and StageStats::PushSelf().
Referenced by LunaStatsManager().
GetBestFinalGrade()
static int LunaStatsManager::GetBestFinalGrade (T * t, lua_State * L) inline static
References FOREACH_CONST, FOREACH_HumanPlayer, StatsManager::GetFinalEvalStageStats(), PlayerStageStats::GetGrade(), Grade_Failed, StageStats::m_player, StatsManager::m_vPlayedStageStats, min(), and Enum::Push().
Referenced by LunaStatsManager().
GetBestGrade()
static int LunaStatsManager::GetBestGrade (T * p, lua_State * L) inline static
References FOREACH_EnabledPlayer, PlayerStageStats::GetGrade(), StatsManager::m_CurStageStats, StageStats::m_player, min(), and NUM_Grade.
Referenced by LunaStatsManager().
GetCurStageStats()
static int LunaStatsManager::GetCurStageStats (T * p, lua_State * L) inline static
References StatsManager::m_CurStageStats, and StageStats::PushSelf().
Referenced by LunaStatsManager().
GetFinalEvalStageStats()
static int LunaStatsManager::GetFinalEvalStageStats (T * p, lua_State * L) inline static
References StatsManager::GetFinalEvalStageStats(), and StageStats::PushSelf().
Referenced by LunaStatsManager().
GetFinalGrade()
static int LunaStatsManager::GetFinalGrade (T * p, lua_State * L) inline static
References GAMESTATE, StatsManager::GetFinalEvalStageStats(), PlayerStageStats::GetGrade(), Grade_NoData, GameState::IsHumanPlayer(), L, and StageStats::m_player.
Referenced by LunaStatsManager().
GetPlayedStageStats()
static int LunaStatsManager::GetPlayedStageStats (T * p, lua_State * L) inline static
References IArg, and StatsManager::m_vPlayedStageStats.
Referenced by LunaStatsManager().
GetStagesPlayed()
static int LunaStatsManager::GetStagesPlayed (T * p, lua_State * L) inline static
References StatsManager::m_vPlayedStageStats.
Referenced by LunaStatsManager().
GetWorstGrade()
static int LunaStatsManager::GetWorstGrade (T * p, lua_State * L) inline static
References FOREACH_EnabledPlayer, PlayerStageStats::GetGrade(), Grade_Tier01, StatsManager::m_CurStageStats, StageStats::m_player, and max().
Referenced by LunaStatsManager().
Reset()
static int LunaStatsManager::Reset (T * p, lua_State * L) inline static
References StatsManager::Reset().
Referenced by LunaStatsManager().
The documentation for this class was generated from the following file:
StatsManager.cpp