Etterna: PlayerOptions.cpp File Reference
PlayerOptions.cpp File Reference
#include "global.h"
#include "PlayerOptions.h"
#include "CommonMetrics.h"
#include "Foreach.h"
#include "GameState.h"
#include "NoteSkinManager.h"
#include "RageUtil.h"
#include "Song.h"
#include "Steps.h"
#include "Style.h"
#include <cfloat>
#include "LuaBinding.h"
#include "OptionsBinding.h"
Classes
class LunaPlayerOptions
Allow Lua to have access to PlayerOptions.
Macros
#define APPROACH(opt) fapproach(m_##opt, other.m_##opt, fDeltaSeconds* other.m_Speed##opt);
#define DO_COPY(x) x = other.x;
#define SET_FLOAT(opt)
#define COMPARE(x)
#define CPY(x) x = other.x;
#define CPY_SPEED(x)
#define SAVE(x) po_prefs.x = this->x;
#define CPY(x) this->x = defaults.x;
Functions
XToString (LifeType)
XToLocalizedString (LifeType)
LuaXType (LifeType)
XToString (DrainType)
XToLocalizedString (DrainType)
LuaXType (DrainType)
void NextFloat (float fValues[], int size)
void NextBool (bool bValues[], int size)
static void AddPart (vector< RString > &AddTo, float level, RString name)
Variables
static const char * LifeTypeNames []
static const char * DrainTypeNames []
ThemeMetric< float > RANDOM_SPEED_CHANCE ("PlayerOptions", "RandomSpeedChance")
ThemeMetric< float > RANDOM_REVERSE_CHANCE ("PlayerOptions", "RandomReverseChance")
ThemeMetric< float > RANDOM_DARK_CHANCE ("PlayerOptions", "RandomDarkChance")
ThemeMetric< float > RANDOM_ACCEL_CHANCE ("PlayerOptions", "RandomAccelChance")
ThemeMetric< float > RANDOM_EFFECT_CHANCE ("PlayerOptions", "RandomEffectChance")
ThemeMetric< float > RANDOM_HIDDEN_CHANCE ("PlayerOptions", "RandomHiddenChance")
ThemeMetric< float > RANDOM_SUDDEN_CHANCE ("PlayerOptions", "RandomSuddenChance")
static const float CMOD_DEFAULT = 200.0f
Macro Definition Documentation
APPROACH
#define APPROACH (opt) fapproach(m_##opt, other.m_##opt, fDeltaSeconds* other.m_Speed##opt);
Referenced by PlayerOptions::Approach().
COMPARE
#define COMPARE (x)
Value:
{                                                                          \
        if ((x) != other.x)                                                    \
            return false;                                                      \
    }
Referenced by PlayerOptions::operator==().
CPY [1/2]
#define CPY (x) x = other.x;
Referenced by PlayerOptions::operator=(), and PlayerOptions::ResetPrefs().
CPY [2/2]
#define CPY (x) this->x = defaults.x;
CPY_SPEED
#define CPY_SPEED (x)
Value:
m_##x = other.m_##x;                                                       \
    m_Speed##x = other.m_Speed##x;
Referenced by PlayerOptions::operator=().
DO_COPY
#define DO_COPY (x) x = other.x;
Referenced by PlayerOptions::Approach().
SAVE
#define SAVE (x) po_prefs.x = this->x;
Referenced by PlayerOptions::GetSavedPrefsString().
SET_FLOAT
#define SET_FLOAT (opt)
Value:
{                                                                          \
        m_##opt = level;                                                       \
        m_Speed##opt = speed;                                                  \
    }
Referenced by PlayerOptions::FromOneModString().
Function Documentation
AddPart()
static void AddPart (vector< RString > & AddTo, float level, RString name) static
References ssprintf().
Referenced by PlayerOptions::GetMods().
LuaXType() [1/2]
LuaXType (LifeType)
LuaXType() [2/2]
LuaXType (DrainType)
NextBool()
void NextBool (bool bValues[], int size)
Referenced by PlayerOptions::NextTransform(), and PlayerOptions::NextTurn().
NextFloat()
void NextFloat (float fValues[], int size)
Referenced by PlayerOptions::NextAccel(), PlayerOptions::NextAppearance(), PlayerOptions::NextEffect(), and PlayerOptions::NextScroll().
XToLocalizedString() [1/2]
XToLocalizedString (LifeType)
XToLocalizedString() [2/2]
XToLocalizedString (DrainType)
XToString() [1/2]
XToString (LifeType)
XToString() [2/2]
XToString (DrainType)
Variable Documentation
CMOD_DEFAULT
const float CMOD_DEFAULT = 200.0f static
Referenced by PlayerOptions::FromOneModString(), PlayerOptions::Init(), LunaPlayerOptions::MMod(), and LunaPlayerOptions::XMod().
DrainTypeNames
const char* DrainTypeNames[] static
Initial value:
= {
    "Normal",
    "NoRecover",
    "SuddenDeath",
}
LifeTypeNames
const char* LifeTypeNames[] static
Initial value:
= {
    "Bar",
    "Battery",
    "Time",
}
RANDOM_ACCEL_CHANCE
ThemeMetric<float> RANDOM_ACCEL_CHANCE("PlayerOptions", "RandomAccelChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_DARK_CHANCE
ThemeMetric<float> RANDOM_DARK_CHANCE("PlayerOptions", "RandomDarkChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_EFFECT_CHANCE
ThemeMetric<float> RANDOM_EFFECT_CHANCE("PlayerOptions", "RandomEffectChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_HIDDEN_CHANCE
ThemeMetric<float> RANDOM_HIDDEN_CHANCE("PlayerOptions", "RandomHiddenChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_REVERSE_CHANCE
ThemeMetric<float> RANDOM_REVERSE_CHANCE("PlayerOptions", "RandomReverseChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_SPEED_CHANCE
ThemeMetric<float> RANDOM_SPEED_CHANCE("PlayerOptions", "RandomSpeedChance")
Referenced by PlayerOptions::ChooseRandomModifiers().
RANDOM_SUDDEN_CHANCE
ThemeMetric<float> RANDOM_SUDDEN_CHANCE("PlayerOptions", "RandomSuddenChance")
Referenced by PlayerOptions::ChooseRandomModifiers().