Etterna: RageSoundReader_PostBuffering Class Reference
RageSoundReader_PostBuffering Class Reference
#include <RageSoundReader_PostBuffering.h>
Public Member Functions
RageSoundReader_PostBuffering (RageSoundReader *pSource)
RageSoundReader_PostBuffering * Copy () const override
int Read (float *pBuf, int iFrames) override
bool SetProperty (const RString &sProperty, float fValue) override
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Attributes
float m_fVolume
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Constructor & Destructor Documentation
RageSoundReader_PostBuffering()
RageSoundReader_PostBuffering::RageSoundReader_PostBuffering (RageSoundReader * pSource)
References m_fVolume.
Referenced by Copy().
Member Function Documentation
Copy()
RageSoundReader_PostBuffering* RageSoundReader_PostBuffering::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_PostBuffering().
Read()
int RageSoundReader_PostBuffering::Read (float * pBuf, int iFrames) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundUtil::Attenuate(), f, RageSoundReader_Filter::GetNumChannels(), m_fVolume, RageSoundReader_Filter::m_pSource, and RageSoundReader::Read().
SetProperty()
bool RageSoundReader_PostBuffering::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader_Filter.
References m_fVolume, and RageSoundReader_Filter::SetProperty().
Member Data Documentation
m_fVolume
float RageSoundReader_PostBuffering::m_fVolume private
Referenced by RageSoundReader_PostBuffering(), Read(), and SetProperty().
The documentation for this class was generated from the following files:
RageSoundReader_PostBuffering.h
RageSoundReader_PostBuffering.cpp