Etterna: LunaHighScore Class Reference
LunaHighScore Class Reference
Allow Lua to have access to the HighScore.
Public Member Functions
LunaHighScore ()
Public Member Functions inherited from Luna< HighScore >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetName (T *p, lua_State *L)
static int GetScore (T *p, lua_State *L)
static int GetPercentDP (T *p, lua_State *L)
static int GetWifeScore (T *p, lua_State *L)
static int GetWifePoints (T *p, lua_State *L)
static int GetMusicRate (T *p, lua_State *L)
static int GetJudgeScale (T *p, lua_State *L)
static int GetDate (T *p, lua_State *L)
static int GetSurvivalSeconds (T *p, lua_State *L)
static int IsFillInMarker (T *p, lua_State *L)
static int GetMaxCombo (T *p, lua_State *L)
static int GetModifiers (T *p, lua_State *L)
static int GetTapNoteScore (T *p, lua_State *L)
static int GetHoldNoteScore (T *p, lua_State *L)
static int RescoreToWifeJudge (T *p, lua_State *L)
static int RescoreToDPJudge (T *p, lua_State *L)
static int RescoreJudges (T *p, lua_State *L)
static int GetRadarValues (T *p, lua_State *L)
static int GetSkillsetSSR (T *p, lua_State *L)
static int ToggleEtternaValidation (T *p, lua_State *L)
static int GetOffsetVector (T *p, lua_State *L)
static int GetNoteRowVector (T *p, lua_State *L)
static int GetTrackVector (T *p, lua_State *L)
static int GetTapNoteTypeVector (T *p, lua_State *L)
static int GetJudgmentString (T *p, lua_State *L)
static int GetUserid (T *p, lua_State *L)
static int GetScoreid (T *p, lua_State *L)
static int GetAvatar (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< HighScore >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< HighScore >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< HighScore >
using T = HighScore
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< HighScore >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the HighScore.
Constructor & Destructor Documentation
LunaHighScore()
LunaHighScore::LunaHighScore () inline
References ADD_METHOD, GetAvatar(), GetDate(), GetHoldNoteScore(), GetJudgeScale(), GetJudgmentString(), GetMaxCombo(), GetModifiers(), GetMusicRate(), GetName(), GetNoteRowVector(), GetOffsetVector(), GetPercentDP(), GetRadarValues(), GetScore(), GetScoreid(), GetSkillsetSSR(), GetSurvivalSeconds(), GetTapNoteScore(), GetTapNoteTypeVector(), GetTrackVector(), GetUserid(), GetWifePoints(), GetWifeScore(), IsFillInMarker(), RescoreJudges(), and ToggleEtternaValidation().
Member Function Documentation
GetAvatar()
static int LunaHighScore::GetAvatar (T * p, lua_State * L) inline static
References HighScore::avatar.
Referenced by LunaHighScore().
GetDate()
static int LunaHighScore::GetDate (T * p, lua_State * L) inline static
References HighScore::GetDateTime(), and DateTime::GetString().
Referenced by LunaHighScore().
GetHoldNoteScore()
static int LunaHighScore::GetHoldNoteScore (T * p, lua_State * L) inline static
References HighScore::GetHoldNoteScore().
Referenced by LunaHighScore().
GetJudgeScale()
static int LunaHighScore::GetJudgeScale (T * p, lua_State * L) inline static
References HighScore::GetJudgeScale().
Referenced by LunaHighScore().
GetJudgmentString()
static int LunaHighScore::GetJudgmentString (T * p, lua_State * L) inline static
References HighScore::GetMaxCombo(), HighScore::GetTapNoteScore(), ssprintf(), TNS_Miss, TNS_W1, TNS_W2, TNS_W3, TNS_W4, and TNS_W5.
Referenced by LunaHighScore().
GetMaxCombo()
static int LunaHighScore::GetMaxCombo (T * p, lua_State * L) inline static
References HighScore::GetMaxCombo().
Referenced by LunaHighScore().
GetModifiers()
static int LunaHighScore::GetModifiers (T * p, lua_State * L) inline static
References HighScore::GetModifiers().
Referenced by LunaHighScore().
GetMusicRate()
static int LunaHighScore::GetMusicRate (T * p, lua_State * L) inline static
References HighScore::GetMusicRate().
Referenced by LunaHighScore().
GetName()
static int LunaHighScore::GetName (T * p, lua_State * L) inline static
References HighScore::GetName().
Referenced by LunaHighScore().
GetNoteRowVector()
static int LunaHighScore::GetNoteRowVector (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), HighScore::GetNoteRowVector(), HighScore::LoadReplayData(), and HighScore::UnloadReplayData().
Referenced by LunaHighScore().
GetOffsetVector()
static int LunaHighScore::GetOffsetVector (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), HighScore::GetOffsetVector(), HighScore::LoadReplayData(), and HighScore::UnloadReplayData().
Referenced by LunaHighScore().
GetPercentDP()
static int LunaHighScore::GetPercentDP (T * p, lua_State * L) inline static
References HighScore::GetPercentDP().
Referenced by LunaHighScore().
GetRadarValues()
static int LunaHighScore::GetRadarValues (T * p, lua_State * L) inline static
References HighScore::GetRadarValues(), and RadarValues::PushSelf().
Referenced by LunaHighScore().
GetScore()
static int LunaHighScore::GetScore (T * p, lua_State * L) inline static
References HighScore::GetScore().
Referenced by LunaHighScore().
GetScoreid()
static int LunaHighScore::GetScoreid (T * p, lua_State * L) inline static
References HighScore::scoreid.
Referenced by LunaHighScore().
GetSkillsetSSR()
static int LunaHighScore::GetSkillsetSSR (T * p, lua_State * L) inline static
References HighScore::GetSkillsetSSR().
Referenced by LunaHighScore().
GetSurvivalSeconds()
static int LunaHighScore::GetSurvivalSeconds (T * p, lua_State * L) inline static
References HighScore::GetSurvivalSeconds().
Referenced by LunaHighScore().
GetTapNoteScore()
static int LunaHighScore::GetTapNoteScore (T * p, lua_State * L) inline static
References HighScore::GetTapNoteScore().
Referenced by LunaHighScore().
GetTapNoteTypeVector()
static int LunaHighScore::GetTapNoteTypeVector (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), HighScore::GetTapNoteTypeVector(), HighScore::LoadReplayData(), and HighScore::UnloadReplayData().
Referenced by LunaHighScore().
GetTrackVector()
static int LunaHighScore::GetTrackVector (T * p, lua_State * L) inline static
References LuaHelpers::CreateTableFromArray(), HighScore::GetTrackVector(), HighScore::LoadReplayData(), and HighScore::UnloadReplayData().
Referenced by LunaHighScore().
GetUserid()
static int LunaHighScore::GetUserid (T * p, lua_State * L) inline static
References HighScore::userid.
Referenced by LunaHighScore().
GetWifePoints()
static int LunaHighScore::GetWifePoints (T * p, lua_State * L) inline static
References HighScore::GetWifePoints().
Referenced by LunaHighScore().
GetWifeScore()
static int LunaHighScore::GetWifeScore (T * p, lua_State * L) inline static
References HighScore::GetWifeScore().
Referenced by LunaHighScore().
IsFillInMarker()
static int LunaHighScore::IsFillInMarker (T * p, lua_State * L) inline static
References FOREACH_PlayerNumber, HighScore::GetName(), and RANKING_TO_FILL_IN_MARKER.
Referenced by LunaHighScore().
RescoreJudges()
static int LunaHighScore::RescoreJudges (T * p, lua_State * L) inline static
References HighScore::GetRescoreJudgeVector(), and IArg.
Referenced by LunaHighScore().
RescoreToDPJudge()
static int LunaHighScore::RescoreToDPJudge (T * p, lua_State * L) inline static
References IArg, and HighScore::RescoreToDPJudge().
RescoreToWifeJudge()
static int LunaHighScore::RescoreToWifeJudge (T * p, lua_State * L) inline static
References IArg, and HighScore::RescoreToWifeJudge().
ToggleEtternaValidation()
static int LunaHighScore::ToggleEtternaValidation (T * p, lua_State * L) inline static
References HighScore::GetEtternaValid(), and HighScore::SetEtternaValid().
Referenced by LunaHighScore().
The documentation for this class was generated from the following file:
HighScore.cpp