Etterna: OptionRowHandler.h File Reference
OptionRowHandler.h File Reference
#include "global.h"
#include "GameCommand.h"
#include "LuaReference.h"
#include "RageUtil.h"
#include <set>
Classes
struct OptionRowDefinition
Define the purpose of the OptionRow.
class OptionRowHandler
Shows PlayerOptions and SongOptions in icon form.
Namespaces
OptionRowHandlerUtil
Utilities for the OptionRowHandlers.
Macros
#define PUSH(c)
Enumerations
enum SelectType {
SELECT_ONE, SELECT_MULTIPLE, SELECT_NONE, NUM_SelectType,
SelectType_Invalid
}
How many options can be selected on this row?
enum LayoutType { LAYOUT_SHOW_ALL_IN_ROW, LAYOUT_SHOW_ONE_IN_ROW, NUM_LayoutType, LayoutType_Invalid }
How many items are shown on the row?
Functions
const RString & SelectTypeToString (SelectType pm)
SelectType StringToSelectType (const RString &s)
LuaDeclareType (SelectType)
const RString & LayoutTypeToString (LayoutType pm)
LayoutType StringToLayoutType (const RString &s)
LuaDeclareType (LayoutType)
OptionRowHandler * OptionRowHandlerUtil::Make (const Commands &cmds)
OptionRowHandler * OptionRowHandlerUtil::MakeNull ()
OptionRowHandler * OptionRowHandlerUtil::MakeSimple (const MenuRowDef &mrd)
void OptionRowHandlerUtil::SelectExactlyOne (int iSelection, vector< bool > &vbSelectedOut)
int OptionRowHandlerUtil::GetOneSelection (const vector< bool > &vbSelected)
void VerifySelected (SelectType st, vector< bool > &selected, const RString &sName)
Detailed Description
Author
Chris Danford (c) 2002-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
PUSH
#define PUSH (c)
Value:
if (c)                                                                     \
        m_vsChoices.push_back(c);
Referenced by OptionRowDefinition::OptionRowDefinition().
Enumeration Type Documentation
LayoutType
enum LayoutType
How many items are shown on the row?
Enumerator
LAYOUT_SHOW_ALL_IN_ROW
All of the options are shown at once.
LAYOUT_SHOW_ONE_IN_ROW
Only one option is shown at a time.
NUM_LayoutType
LayoutType_Invalid
SelectType
enum SelectType
How many options can be selected on this row?
Enumerator
SELECT_ONE
Only one option can be chosen on this row.
SELECT_MULTIPLE
Multiple options can be chosen on this row.
SELECT_NONE
No options can be chosen on this row.
NUM_SelectType
SelectType_Invalid
Function Documentation
LayoutTypeToString()
const RString& LayoutTypeToString (LayoutType pm)
LuaDeclareType() [1/2]
LuaDeclareType (SelectType)
LuaDeclareType() [2/2]
LuaDeclareType (LayoutType)
SelectTypeToString()
const RString& SelectTypeToString (SelectType pm)
StringToLayoutType()
LayoutType StringToLayoutType (const RString & s)
Referenced by OptionRowHandlerLua::LoadInternal(), OptionRowHandlerListSteps::Reload(), and OptionRowHandlerLua::SanityCheckTable().
StringToSelectType()
SelectType StringToSelectType (const RString & s)
Referenced by OptionRowHandlerLua::LoadInternal(), and OptionRowHandlerLua::SanityCheckTable().
VerifySelected()
void VerifySelected (SelectType st, vector< bool > & selected, const RString & sName) inline
References LuaHelpers::ReportScriptErrorFmt(), and SELECT_ONE.
Referenced by OptionRow::ExportOptions(), OptionRowHandlerList::ImportOption(), and OptionRow::ImportOptions().