Etterna: RageMovieTexture_Generic_Intermediate Class Reference
RageMovieTexture_Generic_Intermediate Class Reference
Public Member Functions
RageMovieTexture_Generic_Intermediate (const RageTextureID &ID, const int iWidth, const int iHeight, const int iImageWidth, const int iImageHeight, const int iTextureWidth, const int iTextureHeight, const RageSurfaceFormat &SurfaceFormat, const RagePixelFormat &pixfmt)
virtual ~RageMovieTexture_Generic_Intermediate ()
virtual void Invalidate ()
virtual void Reload ()
virtual unsigned GetTexHandle () const
bool IsAMovie () const
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Update (float)
virtual void SetPosition (float)
virtual void DecodeSeconds (float)
virtual void SetPlaybackRate (float)
virtual void SetLooping (bool)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Private Member Functions
void CreateTexture ()
Private Attributes
unsigned m_uTexHandle
RageSurfaceFormat m_SurfaceFormat
RagePixelFormat m_PixFmt
Additional Inherited Members
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
RageMovieTexture_Generic_Intermediate()
RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate (const RageTextureID & ID, const int iWidth, const int iHeight, const int iImageWidth, const int iImageHeight, const int iTextureWidth, const int iTextureHeight, const RageSurfaceFormat & SurfaceFormat, const RagePixelFormat & pixfmt) inline
References RageTexture::CreateFrameRects(), CreateTexture(), RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_PixFmt, and m_uTexHandle.
~RageMovieTexture_Generic_Intermediate()
virtual RageMovieTexture_Generic_Intermediate::~RageMovieTexture_Generic_Intermediate () inline virtual
References RageDisplay::DeleteTexture(), DISPLAY, and m_uTexHandle.
Member Function Documentation
CreateTexture()
void RageMovieTexture_Generic_Intermediate::CreateTexture () inline private
References RageSurfaceFormat::BitsPerPixel, CreateSurfaceFrom(), RageDisplay::CreateTexture(), DISPLAY, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, m_PixFmt, m_SurfaceFormat, m_uTexHandle, and RageSurfaceFormat::Mask.
Referenced by RageMovieTexture_Generic_Intermediate().
GetTexHandle()
virtual unsigned RageMovieTexture_Generic_Intermediate::GetTexHandle () const inline virtual
Implements RageTexture.
References m_uTexHandle.
Invalidate()
virtual void RageMovieTexture_Generic_Intermediate::Invalidate () inline virtual
Reimplemented from RageTexture.
References m_uTexHandle.
IsAMovie()
bool RageMovieTexture_Generic_Intermediate::IsAMovie () const inline virtual
Reimplemented from RageTexture.
Reload()
virtual void RageMovieTexture_Generic_Intermediate::Reload () inline virtual
Reimplemented from RageTexture.
Member Data Documentation
m_PixFmt
RagePixelFormat RageMovieTexture_Generic_Intermediate::m_PixFmt private
Referenced by CreateTexture(), and RageMovieTexture_Generic_Intermediate().
m_SurfaceFormat
RageSurfaceFormat RageMovieTexture_Generic_Intermediate::m_SurfaceFormat private
Referenced by CreateTexture().
m_uTexHandle
unsigned RageMovieTexture_Generic_Intermediate::m_uTexHandle private
Referenced by CreateTexture(), GetTexHandle(), Invalidate(), RageMovieTexture_Generic_Intermediate(), and ~RageMovieTexture_Generic_Intermediate().
The documentation for this class was generated from the following file:
MovieTexture_Generic.cpp