Etterna: DateTime Struct Reference
DateTime Struct Reference
A standard way of determining the date and the time.
#include <DateTime.h>
Public Member Functions
DateTime ()
Set up a default date and time.
void Init ()
Initialize the date and time.
bool operator< (const DateTime &other) const
Determine if this DateTime is less than some other time.
bool operator> (const DateTime &other) const
Determine if this DateTime is greater than some other time.
bool operator== (const DateTime &other) const
Determine if this DateTime is equal to some other time.
bool operator!= (const DateTime &other) const
Determine if this DateTime is not equal to some other time.
bool operator<= (const DateTime &other) const
Determine if this DateTime is less than or equal to some other time.
bool operator>= (const DateTime &other) const
Determine if this DateTime is greater than or equal to some other time.
void StripTime ()
Remove the time portion from the date.
RString GetString () const
Retrieve a string representation of the current date and time.
bool FromString (const RString &sDateTime)
Attempt to turn a string into a DateTime.
Static Public Member Functions
static DateTime GetNowDateTime ()
Retrieve the current date and time.
static DateTime GetNowDate ()
Retrieve the current date.
Public Attributes
int tm_sec
The number of seconds after the minute.
int tm_min
The number of minutes after the hour.
int tm_hour
The number of hours since midnight (or 0000 hours).
int tm_mday
The specified day of the current month.
int tm_mon
The number of months since January.
int tm_year
The number of years since the year 1900.
Detailed Description
A standard way of determining the date and the time.
Constructor & Destructor Documentation
DateTime()
DateTime::DateTime ()
Set up a default date and time.
References Init().
Member Function Documentation
FromString()
bool DateTime::FromString (const RString & sDateTime)
Attempt to turn a string into a DateTime.
Parameters
sDateTime the string to attempt to convert.
Returns
true if the conversion worked, or false otherwise.
References Init(), tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by XMLProfile::LoadEttGeneralDataFromNode(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), HighScoreList::LoadFromNode(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), DBProfile::LoadPlayerScores(), DBProfile::LoadScoreGoals(), and DownloadManager::RequestChartLeaderBoard().
GetNowDate()
DateTime DateTime::GetNowDate () static
Retrieve the current date.
Returns
the current date.
References GetNowDateTime(), and StripTime().
Referenced by Profile::IncrementCategoryPlayCount(), Profile::IncrementStepsPlayCount(), LuaInformation(), and Profile::SaveAllToDir().
GetNowDateTime()
DateTime DateTime::GetNowDateTime () static
Retrieve the current date and time.
Returns
the current date and time.
References COPY_M, tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by Profile::AddGoal(), FillInHighScore(), GetNowDate(), MakeRandomHighScore(), and StepMania::SaveScreenshot().
GetString()
RString DateTime::GetString () const
Retrieve a string representation of the current date and time.
This returns a common SQL/XML format: "YYYY-MM-DD HH:MM:SS".
Returns
the string representation of the date and time.
References ssprintf(), tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by DownloadManager::AddGoal(), HighScoreImpl::CreateEttNode(), HighScoreImpl::CreateNode(), HighScoreList::CreateNode(), FillInHighScore(), LunaHighScore::GetDate(), HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), DBProfile::LoadPlayerScores(), ETTProtocol::ReportHighScore(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), DBProfile::SavePlayerScores(), StepMania::SaveScreenshot(), SetCURLPOSTScore(), DownloadManager::UpdateGoal(), and LunaScoreGoal::WhenAchieved().
Init()
void DateTime::Init ()
Initialize the date and time.
References ZERO.
Referenced by DateTime(), FromString(), HighScoreImpl::HighScoreImpl(), Profile::InitGeneralData(), and Profile::Profile().
operator!=()
bool DateTime::operator!= (const DateTime & other) const inline
Determine if this DateTime is not equal to some other time.
Parameters
other the other DateTime to check.
Returns
true if this is not equal to the other time, or false otherwise.
References operator==().
operator<()
bool DateTime::operator< (const DateTime & other) const
Determine if this DateTime is less than some other time.
Parameters
other the other DateTime to check.
Returns
true if this is less than the other time, or false otherwise.
References COMPARE, tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by operator>=().
operator<=()
bool DateTime::operator<= (const DateTime & other) const inline
Determine if this DateTime is less than or equal to some other time.
Parameters
other the other DateTime to check.
Returns
true if this is less than or equal to the other time, or false otherwise.
References operator>().
operator==()
bool DateTime::operator== (const DateTime & other) const
Determine if this DateTime is equal to some other time.
Parameters
other the other DateTime to check.
Returns
true if this is equal to the other time, or false otherwise.
References COMPARE, tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by operator!=().
operator>()
bool DateTime::operator> (const DateTime & other) const
Determine if this DateTime is greater than some other time.
Parameters
other the other DateTime to check.
Returns
true if this is greater than the other time, or false otherwise.
References COMPARE, tm_hour, tm_mday, tm_min, tm_mon, tm_sec, and tm_year.
Referenced by operator<=().
operator>=()
bool DateTime::operator>= (const DateTime & other) const inline
Determine if this DateTime is greater than or equal to some other time.
Parameters
other the other DateTime to check.
Returns
true if this is greater than or equal to the other time, or false otherwise.
References operator<().
StripTime()
void DateTime::StripTime ()
Remove the time portion from the date.
References tm_hour, tm_min, and tm_sec.
Referenced by GetNowDate().
Member Data Documentation
tm_hour
int DateTime::tm_hour
The number of hours since midnight (or 0000 hours).
Valid values are [0, 23].
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), operator>(), and StripTime().
tm_mday
int DateTime::tm_mday
The specified day of the current month.
Valid values are [1, 31].
XXX: Is it possible to set an illegal date through here, such as day 30 of February? -Wolfman2000
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), and operator>().
tm_min
int DateTime::tm_min
The number of minutes after the hour.
Valid values are [0, 59].
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), operator>(), and StripTime().
tm_mon
int DateTime::tm_mon
The number of months since January.
Valid values are [0, 11].
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), and operator>().
tm_sec
int DateTime::tm_sec
The number of seconds after the minute.
Valid values are [0, 59].
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), operator>(), and StripTime().
tm_year
int DateTime::tm_year
The number of years since the year 1900.
Referenced by FromString(), GetNowDateTime(), GetString(), operator<(), operator==(), and operator>().
The documentation for this struct was generated from the following files:
DateTime.h
DateTime.cpp