Etterna: LunaActorMultiVertex Class Reference
LunaActorMultiVertex Class Reference
Allow Lua to have access to the ActorMultiVertex.
Public Member Functions
DEFINE_METHOD (GetUseAnimationState, _use_animation_state)
DEFINE_METHOD (GetAnimationLengthSeconds, GetAnimationLengthSeconds())
DEFINE_METHOD (GetDecodeMovie, _decode_movie)
LunaActorMultiVertex ()
Public Member Functions inherited from Luna< ActorMultiVertex >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int SetNumVertices (T *p, lua_State *L)
static int GetNumVertices (T *p, lua_State *L)
static void SetVertexFromStack (T *p, lua_State *L, size_t VertexIndex, int DataStackIndex)
static int SetVertex (T *p, lua_State *L)
static int SetVertices (T *p, lua_State *L)
static int SetEffectMode (T *p, lua_State *L)
static int SetTextureMode (T *p, lua_State *L)
static int SetLineWidth (T *p, lua_State *L)
static int SetDrawState (T *p, lua_State *L)
static int GetDestDrawMode (T *p, lua_State *L)
static int GetDestFirstToDraw (T *p, lua_State *L)
static int GetDestNumToDraw (T *p, lua_State *L)
static int GetCurrDrawMode (T *p, lua_State *L)
static int GetCurrFirstToDraw (T *p, lua_State *L)
static int GetCurrNumToDraw (T *p, lua_State *L)
static int LoadTexture (T *p, lua_State *L)
static int GetSpline (T *p, lua_State *L)
static int SetVertsFromSplines (T *p, lua_State *L)
static int SetUseAnimationState (T *p, lua_State *L)
static int GetNumStates (T *p, lua_State *L)
static void FillStateFromLua (lua_State *L, ActorMultiVertex::State &state, RageTexture *tex, int index)
static int AddState (T *p, lua_State *L)
static size_t ValidStateIndex (T *p, lua_State *L, int pos)
static int RemoveState (T *p, lua_State *L)
static int GetState (T *p, lua_State *L)
static int SetState (T *p, lua_State *L)
static int GetStateData (T *p, lua_State *L)
static int SetStateData (T *p, lua_State *L)
static int SetStateProperties (T *p, lua_State *L)
static int SetAllStateDelays (T *p, lua_State *L)
static int SetSecondsIntoAnimation (T *p, lua_State *L)
static int GetNumQuadStates (T *p, lua_State *L)
static size_t QuadStateIndex (T *p, lua_State *L, int pos)
static int AddQuadState (T *p, lua_State *L)
static int RemoveQuadState (T *p, lua_State *L)
static int GetQuadState (T *p, lua_State *L)
static int SetQuadState (T *p, lua_State *L)
static int ForceStateUpdate (T *p, lua_State *L)
static int SetDecodeMovie (T *p, lua_State *L)
static int SetTexture (T *p, lua_State *L)
static int GetTexture (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ActorMultiVertex >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ActorMultiVertex >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ActorMultiVertex >
using T = ActorMultiVertex
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ActorMultiVertex >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the ActorMultiVertex.
Constructor & Destructor Documentation
LunaActorMultiVertex()
LunaActorMultiVertex::LunaActorMultiVertex () inline
References ADD_METHOD, ActorMultiVertex::AddQuadState(), ActorMultiVertex::AddState(), ActorMultiVertex::GetCurrDrawMode(), ActorMultiVertex::GetCurrFirstToDraw(), ActorMultiVertex::GetCurrNumToDraw(), ActorMultiVertex::GetDestDrawMode(), ActorMultiVertex::GetDestFirstToDraw(), ActorMultiVertex::GetDestNumToDraw(), ActorMultiVertex::GetNumQuadStates(), ActorMultiVertex::GetNumStates(), ActorMultiVertex::GetNumVertices(), ActorMultiVertex::GetQuadState(), ActorMultiVertex::GetSpline(), ActorMultiVertex::GetState(), ActorMultiVertex::GetStateData(), ActorMultiVertex::GetTexture(), ActorMultiVertex::RemoveQuadState(), ActorMultiVertex::RemoveState(), ActorMultiVertex::SetAllStateDelays(), ActorMultiVertex::SetDrawState(), ActorMultiVertex::SetEffectMode(), ActorMultiVertex::SetLineWidth(), ActorMultiVertex::SetNumVertices(), ActorMultiVertex::SetQuadState(), ActorMultiVertex::SetSecondsIntoAnimation(), ActorMultiVertex::SetState(), ActorMultiVertex::SetStateData(), ActorMultiVertex::SetStateProperties(), ActorMultiVertex::SetTexture(), ActorMultiVertex::SetTextureMode(), and ActorMultiVertex::SetVertsFromSplines().
Member Function Documentation
AddQuadState()
static int LunaActorMultiVertex::AddQuadState (T * p, lua_State * L) inline static
References ActorMultiVertex::AddQuadState(), COMMON_RETURN_SELF, and IArg.
AddState()
static int LunaActorMultiVertex::AddState (T * p, lua_State * L) inline static
References ActorMultiVertex::AddState(), COMMON_RETURN_SELF, and ActorMultiVertex::GetTexture().
DEFINE_METHOD() [1/3]
LunaActorMultiVertex::DEFINE_METHOD (GetUseAnimationState , _use_animation_state)
DEFINE_METHOD() [2/3]
LunaActorMultiVertex::DEFINE_METHOD (GetAnimationLengthSeconds , GetAnimationLengthSeconds())
DEFINE_METHOD() [3/3]
LunaActorMultiVertex::DEFINE_METHOD (GetDecodeMovie , _decode_movie)
FillStateFromLua()
static void LunaActorMultiVertex::FillStateFromLua (lua_State * L, ActorMultiVertex::State & state, RageTexture * tex, int index) inline static
References StepMania::Rect< T >::bottom, DATA_ERROR, RageTexture::GetImageToTexCoordsRatioX(), RageTexture::GetImageToTexCoordsRatioY(), StepMania::Rect< T >::left, ActorMultiVertex::State::rect, StepMania::Rect< T >::right, SET_SIDE, and StepMania::Rect< T >::top.
ForceStateUpdate()
static int LunaActorMultiVertex::ForceStateUpdate (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorMultiVertex::UpdateAnimationState().
GetCurrDrawMode()
static int LunaActorMultiVertex::GetCurrDrawMode (T * p, lua_State * L) inline static
References ActorMultiVertex::GetCurrDrawMode(), and Enum::Push().
GetCurrFirstToDraw()
static int LunaActorMultiVertex::GetCurrFirstToDraw (T * p, lua_State * L) inline static
References ActorMultiVertex::GetCurrFirstToDraw().
GetCurrNumToDraw()
static int LunaActorMultiVertex::GetCurrNumToDraw (T * p, lua_State * L) inline static
References ActorMultiVertex::GetCurrNumToDraw().
GetDestDrawMode()
static int LunaActorMultiVertex::GetDestDrawMode (T * p, lua_State * L) inline static
References ActorMultiVertex::GetDestDrawMode(), and Enum::Push().
GetDestFirstToDraw()
static int LunaActorMultiVertex::GetDestFirstToDraw (T * p, lua_State * L) inline static
References ActorMultiVertex::GetDestFirstToDraw().
GetDestNumToDraw()
static int LunaActorMultiVertex::GetDestNumToDraw (T * p, lua_State * L) inline static
References ActorMultiVertex::GetDestNumToDraw().
GetNumQuadStates()
static int LunaActorMultiVertex::GetNumQuadStates (T * p, lua_State * L) inline static
References ActorMultiVertex::GetNumQuadStates().
GetNumStates()
static int LunaActorMultiVertex::GetNumStates (T * p, lua_State * L) inline static
References ActorMultiVertex::GetNumStates().
GetNumVertices()
static int LunaActorMultiVertex::GetNumVertices (T * p, lua_State * L) inline static
References ActorMultiVertex::GetNumVertices().
GetQuadState()
static int LunaActorMultiVertex::GetQuadState (T * p, lua_State * L) inline static
References ActorMultiVertex::GetQuadState().
GetSpline()
static int LunaActorMultiVertex::GetSpline (T * p, lua_State * L) inline static
References ActorMultiVertex::GetSpline(), IArg, ActorMultiVertex::num_vert_splines, and CubicSplineN::PushSelf().
GetState()
static int LunaActorMultiVertex::GetState (T * p, lua_State * L) inline static
References ActorMultiVertex::GetState().
GetStateData()
static int LunaActorMultiVertex::GetStateData (T * p, lua_State * L) inline static
References StepMania::Rect< T >::bottom, ActorMultiVertex::State::delay, RageTexture::GetImageToTexCoordsRatioX(), RageTexture::GetImageToTexCoordsRatioY(), ActorMultiVertex::GetStateData(), ActorMultiVertex::GetTexture(), StepMania::Rect< T >::left, ActorMultiVertex::State::rect, StepMania::Rect< T >::right, and StepMania::Rect< T >::top.
GetTexture()
static int LunaActorMultiVertex::GetTexture (T * p, lua_State * L) inline static
References ActorMultiVertex::GetTexture(), and RageTexture::PushSelf().
LoadTexture()
static int LunaActorMultiVertex::LoadTexture (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, RageTextureManager::DisableOddDimensionWarning(), RageTextureManager::EnableOddDimensionWarning(), RageTextureManager::GetDefaultTextureID(), ActorMultiVertex::LoadFromTexture(), SArg, TEXTUREMAN, and ActorMultiVertex::UnloadTexture().
QuadStateIndex()
static size_t LunaActorMultiVertex::QuadStateIndex (T * p, lua_State * L, int pos) inline static
References ActorMultiVertex::GetNumQuadStates(), and IArg.
RemoveQuadState()
static int LunaActorMultiVertex::RemoveQuadState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorMultiVertex::RemoveQuadState().
RemoveState()
static int LunaActorMultiVertex::RemoveState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorMultiVertex::RemoveState().
SetAllStateDelays()
static int LunaActorMultiVertex::SetAllStateDelays (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorMultiVertex::SetAllStateDelays().
SetDecodeMovie()
static int LunaActorMultiVertex::SetDecodeMovie (T * p, lua_State * L) inline static
References ActorMultiVertex::_decode_movie, BArg, and COMMON_RETURN_SELF.
SetDrawState()
static int LunaActorMultiVertex::SetDrawState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorMultiVertex::GetDestDrawMode(), ActorMultiVertex::GetDestFirstToDraw(), ActorMultiVertex::GetDestNumToDraw(), IArg, L, LuaHelpers::ReportScriptErrorFmt(), and ActorMultiVertex::SetDrawState().
SetEffectMode()
static int LunaActorMultiVertex::SetEffectMode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, and ActorMultiVertex::SetEffectMode().
SetLineWidth()
static int LunaActorMultiVertex::SetLineWidth (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, LuaHelpers::ReportScriptErrorFmt(), and ActorMultiVertex::SetLineWidth().
SetNumVertices()
static int LunaActorMultiVertex::SetNumVertices (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and ActorMultiVertex::SetNumVertices().
SetQuadState()
static int LunaActorMultiVertex::SetQuadState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and ActorMultiVertex::SetQuadState().
SetSecondsIntoAnimation()
static int LunaActorMultiVertex::SetSecondsIntoAnimation (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, FArg, and ActorMultiVertex::SetSecondsIntoAnimation().
SetState()
static int LunaActorMultiVertex::SetState (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorMultiVertex::SetState().
SetStateData()
static int LunaActorMultiVertex::SetStateData (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorMultiVertex::GetStateData(), and ActorMultiVertex::GetTexture().
SetStateProperties()
static int LunaActorMultiVertex::SetStateProperties (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, ActorMultiVertex::GetTexture(), and ActorMultiVertex::SetStateProperties().
SetTexture()
static int LunaActorMultiVertex::SetTexture (T * p, lua_State * L) inline static
References Luna< Type >::check(), COMMON_RETURN_SELF, RageTextureManager::CopyTexture(), ActorMultiVertex::SetTexture(), and TEXTUREMAN.
SetTextureMode()
static int LunaActorMultiVertex::SetTextureMode (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, L, and ActorMultiVertex::SetTextureMode().
SetUseAnimationState()
static int LunaActorMultiVertex::SetUseAnimationState (T * p, lua_State * L) inline static
References ActorMultiVertex::_use_animation_state, BArg, and COMMON_RETURN_SELF.
SetVertex()
static int LunaActorMultiVertex::SetVertex (T * p, lua_State * L) inline static
References ActorMultiVertex::AddVertices(), COMMON_RETURN_SELF, ActorMultiVertex::GetNumVertices(), IArg, and LuaHelpers::ReportScriptErrorFmt().
SetVertexFromStack()
static void LunaActorMultiVertex::SetVertexFromStack (T * p, lua_State * L, size_t VertexIndex, int DataStackIndex) inline static
References FArg, RageColor::FromStack(), LuaHelpers::ReportScriptErrorFmt(), ActorMultiVertex::SetVertexColor(), ActorMultiVertex::SetVertexCoords(), and ActorMultiVertex::SetVertexPos().
SetVertices()
static int LunaActorMultiVertex::SetVertices (T * p, lua_State * L) inline static
References ActorMultiVertex::AddVertices(), COMMON_RETURN_SELF, ActorMultiVertex::GetNumVertices(), IArg, and LuaHelpers::ReportScriptErrorFmt().
SetVertsFromSplines()
static int LunaActorMultiVertex::SetVertsFromSplines (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and ActorMultiVertex::SetVertsFromSplines().
ValidStateIndex()
static size_t LunaActorMultiVertex::ValidStateIndex (T * p, lua_State * L, int pos) inline static
References ActorMultiVertex::GetNumStates(), and IArg.
The documentation for this class was generated from the following file:
ActorMultiVertex.cpp