Etterna: CsvFile Class Reference
CsvFile Class Reference
#include <CsvFile.h>
Public Types
typedef vector< RString > StringVector
Public Member Functions
CsvFile ()
bool ReadFile (const RString &sPath)
bool ReadFile (RageFileBasic &sFile)
bool WriteFile (const RString &sPath) const
bool WriteFile (RageFileBasic &sFile) const
Public Attributes
vector< StringVector > m_vvs
Private Attributes
RString m_sPath
RString m_sError
Member Typedef Documentation
StringVector
typedef vector<RString> CsvFile::StringVector
Constructor & Destructor Documentation
CsvFile()
CsvFile::CsvFile () default
Member Function Documentation
ReadFile() [1/2]
bool CsvFile::ReadFile (const RString & sPath)
References CHECKPOINT_M, f, RageFile::GetError(), LOG, m_sError, m_sPath, RageFile::Open(), ssprintf(), and RageLog::Trace().
ReadFile() [2/2]
bool CsvFile::ReadFile (RageFileBasic & sFile)
References RageFileBasic::GetError(), RageFileBasic::GetLine(), StdString::CStdStr< CT >::Left(), m_sError, m_vvs, and Rage::utf8_remove_bom().
WriteFile() [1/2]
bool CsvFile::WriteFile (const RString & sPath) const
References f, RageFile::GetError(), LOG, m_sError, RageFile::Open(), RageLog::Trace(), and RageFile::WRITE.
WriteFile() [2/2]
bool CsvFile::WriteFile (RageFileBasic & sFile) const
References FOREACH_CONST, RageFileBasic::GetError(), m_sError, m_vvs, RageFileBasic::PutLine(), and StdString::CStdStr< CT >::Replace().
Member Data Documentation
m_sError
RString CsvFile::m_sError mutable private
Referenced by ReadFile(), and WriteFile().
m_sPath
RString CsvFile::m_sPath private
Referenced by ReadFile().
m_vvs
vector<StringVector> CsvFile::m_vvs
Referenced by ReadFile(), and WriteFile().
The documentation for this class was generated from the following files:
CsvFile.h
CsvFile.cpp