Etterna: LunaLifeMeter Class Reference
LunaLifeMeter Class Reference
Allow Lua to have access to the LifeMeter.
Public Member Functions
LunaLifeMeter ()
Public Member Functions inherited from Luna< LifeMeter >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetLife (T *p, lua_State *L)
static int IsInDanger (T *p, lua_State *L)
static int IsHot (T *p, lua_State *L)
static int IsFailing (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< LifeMeter >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< LifeMeter >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< LifeMeter >
using T = LifeMeter
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< LifeMeter >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the LifeMeter.
Constructor & Destructor Documentation
LunaLifeMeter()
LunaLifeMeter::LunaLifeMeter () inline
References ADD_METHOD, GetLife(), IsFailing(), IsHot(), and IsInDanger().
Member Function Documentation
GetLife()
static int LunaLifeMeter::GetLife (T * p, lua_State * L) inline static
References LifeMeter::GetLife(), and LuaHelpers::Push().
Referenced by LunaLifeMeter().
IsFailing()
static int LunaLifeMeter::IsFailing (T * p, lua_State * L) inline static
References LifeMeter::IsFailing(), and LuaHelpers::Push().
Referenced by LunaLifeMeter().
IsHot()
static int LunaLifeMeter::IsHot (T * p, lua_State * L) inline static
References LifeMeter::IsHot(), and LuaHelpers::Push().
Referenced by LunaLifeMeter().
IsInDanger()
static int LunaLifeMeter::IsInDanger (T * p, lua_State * L) inline static
References LifeMeter::IsInDanger(), and LuaHelpers::Push().
Referenced by LunaLifeMeter().
The documentation for this class was generated from the following file:
LifeMeter.cpp