Etterna: RageFileDriverMem Class Reference
RageFileDriverMem Class Reference
#include <RageFileDriverMemory.h>
Public Member Functions
RageFileDriverMem ()
~RageFileDriverMem () override
RageFileBasic * Open (const RString &sPath, int mode, int &err) override
void FlushDirCache (const RString &) override
bool Remove (const RString &sPath) override
Public Member Functions inherited from RageFileDriver
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void CacheFile (const RString &)
virtual bool Move (const RString &, const RString &)
virtual bool Remount (const RString &)
Private Attributes
RageMutex m_Mutex
vector< RageFileObjMemFile * > m_Files
Additional Inherited Members
Public Types inherited from RageFileDriver
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Attributes inherited from RageFileDriver
FilenameDB * FDB
Constructor & Destructor Documentation
RageFileDriverMem()
RageFileDriverMem::RageFileDriverMem ()
~RageFileDriverMem()
RageFileDriverMem::~RageFileDriverMem () override
References m_Files, and RageFileObjMemFile::ReleaseReference().
Member Function Documentation
FlushDirCache()
void RageFileDriverMem::FlushDirCache (const RString &) inline override virtual
Reimplemented from RageFileDriver.
Open()
RageFileBasic * RageFileDriverMem::Open (const RString & sPath, int mode, int & err) override virtual
Implements RageFileDriver.
References FilenameDB::AddFile(), RageFileObjMemFile::AddReference(), RageFileDriver::FDB, FilenameDB::GetFilePriv(), LockMut, m_Files, m_Mutex, Remove(), and RageFile::WRITE.
Remove()
bool RageFileDriverMem::Remove (const RString & sPath) override virtual
Reimplemented from RageFileDriver.
References ASSERT, FilenameDB::DelFile(), RageFileDriver::FDB, FilenameDB::GetFilePriv(), LockMut, m_Files, m_Mutex, and RageFileObjMemFile::ReleaseReference().
Referenced by Open().
Member Data Documentation
m_Files
vector<RageFileObjMemFile*> RageFileDriverMem::m_Files private
Referenced by Open(), Remove(), and ~RageFileDriverMem().
m_Mutex
RageMutex RageFileDriverMem::m_Mutex private
Referenced by Open(), and Remove().
The documentation for this class was generated from the following files:
RageFileDriverMemory.h
RageFileDriverMemory.cpp