Etterna: LuaBinding.cpp File Reference
LuaBinding.cpp File Reference
#include "global.h"
#include "LuaBinding.h"
#include "LuaReference.h"
#include "RageUtil.h"
#include "SubscriptionManager.h"
#include "RageUtil_AutoPtr.h"
Functions
REGISTER_WITH_LUA_FUNCTION (RegisterTypes)
static void GetGlobalTable (Lua *L)
void DefaultNilArgs (lua_State *L, int n)
float FArgGTEZero (lua_State *L, int index)
Variables
static SubscriptionManager< LuaBinding > m_Subscribers
Function Documentation
DefaultNilArgs()
void DefaultNilArgs (lua_State * L, int n)
FArgGTEZero()
float FArgGTEZero (lua_State * L, int index)
References FArg.
Referenced by LunaPlayerOptions::CMod(), LunaPlayerOptions::Distant(), LunaPlayerOptions::Hallway(), LunaPlayerOptions::Incoming(), LunaPlayerOptions::MMod(), LunaSongOptions::MusicRate(), LunaPlayerOptions::Overhead(), LunaPlayerOptions::Space(), and LunaPlayerOptions::XMod().
GetGlobalTable()
static void GetGlobalTable (Lua * L) static
References LuaReference::IsSet(), LuaReference::PushSelf(), and LuaReference::SetFromStack().
Referenced by LuaBinding::ApplyDerivedType(), LuaBinding::GetPointerFromStack(), and LuaClass::~LuaClass().
REGISTER_WITH_LUA_FUNCTION()
REGISTER_WITH_LUA_FUNCTION (RegisterTypes)
Variable Documentation
m_Subscribers
SubscriptionManager<LuaBinding> m_Subscribers static