Etterna: TimingData.h File Reference
TimingData.h File Reference
#include "global.h"
#include "NoteTypes.h"
#include "PrefsManager.h"
#include "TimingSegments.h"
#include <cfloat>
Classes
class TimingData
Holds data for translating beats<->seconds.
struct TimingData::GetBeatArgs
struct TimingData::GetBeatStarts
struct TimingData::lookup_item_t
Macros
#define COMPARE(x)
Compare a TimingData segment's properties with one another.
#define TimingSegmentToXWithName(Seg, SegName, SegType)
#define TimingSegmentToX(Seg, SegType) TimingSegmentToXWithName(Seg##Segment, Seg, SEGMENT_##SegType)
#define DefineSegmentWithName(Seg, SegName, SegType)
#define DefineSegment(Seg, SegType) DefineSegmentWithName(Seg##Segment, Seg, SEGMENT_##SegType)
Functions
template<class T >
T ToDerived (const TimingSegment *t, TimingSegmentType tst)
TimingSegmentToX (BPM, BPM)
TimingSegmentToX (Stop, STOP)
TimingSegmentToX (Delay, DELAY)
TimingSegmentToX (TimeSignature, TIME_SIG)
TimingSegmentToX (Warp, WARP)
TimingSegmentToX (Label, LABEL)
TimingSegmentToX (Tickcount, TICKCOUNT)
TimingSegmentToX (Combo, COMBO)
TimingSegmentToX (Speed, SPEED)
TimingSegmentToX (Scroll, SCROLL)
TimingSegmentToX (Fake, FAKE)
Detailed Description
Author
Chris Danford, Glenn Maynard (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
COMPARE
#define COMPARE (x)
Value:
if (this->x != other.x)                                                    \
        return false;
Compare a TimingData segment's properties with one another.
Referenced by TimingData::operator==().
DefineSegment
#define DefineSegment (Seg, SegType) DefineSegmentWithName(Seg##Segment, Seg, SEGMENT_##SegType)
DefineSegmentWithName
#define DefineSegmentWithName (Seg, SegName, SegType)
Value:
const Seg* Get##Seg##AtRow(int iNoteRow) const                             \
    {                                                                          \
        const TimingSegment* t = GetSegmentAtRow(iNoteRow, SegType);           \
        return To##SegName(t);                                                 \
    }                                                                          \
    Seg* Get##Seg##AtRow(int iNoteRow)                                         \
    {                                                                          \
        return const_cast<Seg*>(                                               \
          ((const TimingData*)this)->Get##Seg##AtRow(iNoteRow));               \
    }                                                                          \
    const Seg* Get##Seg##AtBeat(float fBeat) const                             \
    {                                                                          \
        return Get##Seg##AtRow(BeatToNoteRow(fBeat));                          \
    }                                                                          \
    Seg* Get##Seg##AtBeat(float fBeat)                                         \
    {                                                                          \
        return const_cast<Seg*>(                                               \
          ((const TimingData*)this)->Get##Seg##AtBeat(fBeat));                 \
    }                                                                          \
    void AddSegment(const Seg& seg) { AddSegment(&seg); }
TimingSegmentToX
#define TimingSegmentToX (Seg, SegType) TimingSegmentToXWithName(Seg##Segment, Seg, SEGMENT_##SegType)
TimingSegmentToXWithName
#define TimingSegmentToXWithName (Seg, SegName, SegType)
Value:
inline const Seg* To##SegName(const TimingSegment* t)                      \
    {                                                                          \
        ASSERT(t->GetType() == SegType);                                       \
        return static_cast<const Seg*>(t);                                     \
    }                                                                          \
    inline Seg* To##SegName(TimingSegment* t)                                  \
    {                                                                          \
        ASSERT(t->GetType() == SegType);                                       \
        return static_cast<Seg*>(t);                                           \
    }
Function Documentation
TimingSegmentToX() [1/11]
TimingSegmentToX (BPM , BPM)
TimingSegmentToX() [2/11]
TimingSegmentToX (Stop , STOP)
TimingSegmentToX() [3/11]
TimingSegmentToX (Delay , DELAY)
TimingSegmentToX() [4/11]
TimingSegmentToX (TimeSignature , TIME_SIG)
TimingSegmentToX() [5/11]
TimingSegmentToX (Warp , WARP)
TimingSegmentToX() [6/11]
TimingSegmentToX (Label , LABEL)
TimingSegmentToX() [7/11]
TimingSegmentToX (Tickcount , TICKCOUNT)
TimingSegmentToX() [8/11]
TimingSegmentToX (Combo , COMBO)
TimingSegmentToX() [9/11]
TimingSegmentToX (Speed , SPEED)
TimingSegmentToX() [10/11]
TimingSegmentToX (Scroll , SCROLL)
TimingSegmentToX() [11/11]
TimingSegmentToX (Fake , FAKE)
ToDerived()
template<class T > T ToDerived (const TimingSegment * t, TimingSegmentType tst) inline
References ASSERT_M, TimingSegment::GetType(), ssprintf(), T, and TimingSegmentTypeToString().