Etterna: LunaCubicSplineN Struct Reference
LunaCubicSplineN Struct Reference
Public Member Functions
LCSN_EVAL_SOMETHING (evaluate)
LCSN_EVAL_SOMETHING (evaluate_derivative)
LCSN_EVAL_SOMETHING (evaluate_second_derivative)
LCSN_EVAL_SOMETHING (evaluate_third_derivative)
SET_GET_LUA (loop)
SET_GET_LUA (polygonal)
SET_GET_LUA (dirty)
LunaCubicSplineN ()
Public Member Functions inherited from Luna< CubicSplineN >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static size_t dimension_index (T *p, lua_State *L, int s)
static size_t point_index (T *p, lua_State *L, int s)
static int solve (T *p, lua_State *L)
static void get_element_table_from_stack (T *p, lua_State *L, int s, size_t limit, vector< float > &ret)
static void set_point_from_stack (T *p, lua_State *L, size_t i, int s)
static int set_point (T *p, lua_State *L)
static void set_coefficients_from_stack (T *p, lua_State *L, size_t i, int s)
static int set_coefficients (T *p, lua_State *L)
static int get_coefficients (T *p, lua_State *L)
static int set_spatial_extent (T *p, lua_State *L)
static int get_spatial_extent (T *p, lua_State *L)
static int get_max_t (T *p, lua_State *L)
static int set_size (T *p, lua_State *L)
static int get_size (T *p, lua_State *L)
static int set_dimension (T *p, lua_State *L)
static int get_dimension (T *p, lua_State *L)
static int empty (T *p, lua_State *L)
static int destroy (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< CubicSplineN >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< CubicSplineN >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< CubicSplineN >
using T = CubicSplineN
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< CubicSplineN >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Constructor & Destructor Documentation
LunaCubicSplineN()
LunaCubicSplineN::LunaCubicSplineN () inline
References ADD_METHOD, destroy(), empty(), get_coefficients(), get_dimension(), get_max_t(), get_size(), get_spatial_extent(), set_coefficients(), set_dimension(), set_point(), set_size(), set_spatial_extent(), and solve().
Member Function Documentation
destroy()
static int LunaCubicSplineN::destroy (T * p, lua_State * L) inline static
References CubicSplineN::m_owned_by_actor, and SAFE_DELETE.
Referenced by LunaCubicSplineN().
dimension_index()
static size_t LunaCubicSplineN::dimension_index (T * p, lua_State * L, int s) inline static
References CubicSplineN::dimension(), and IArg.
Referenced by get_spatial_extent(), and set_spatial_extent().
empty()
static int LunaCubicSplineN::empty (T * p, lua_State * L) inline static
References CubicSplineN::empty().
Referenced by LunaCubicSplineN().
get_coefficients()
static int LunaCubicSplineN::get_coefficients (T * p, lua_State * L) inline static
References CubicSplineN::dimension(), CubicSplineN::get_coefficients(), and point_index().
Referenced by LunaCubicSplineN().
get_dimension()
static int LunaCubicSplineN::get_dimension (T * p, lua_State * L) inline static
References CubicSplineN::dimension().
Referenced by LunaCubicSplineN().
get_element_table_from_stack()
static void LunaCubicSplineN::get_element_table_from_stack (T * p, lua_State * L, int s, size_t limit, vector< float > & ret) inline static
References f, and FArg.
Referenced by set_coefficients_from_stack(), and set_point_from_stack().
get_max_t()
static int LunaCubicSplineN::get_max_t (T * p, lua_State * L) inline static
References CubicSplineN::get_max_t().
Referenced by LunaCubicSplineN().
get_size()
static int LunaCubicSplineN::get_size (T * p, lua_State * L) inline static
References CubicSplineN::size().
Referenced by LunaCubicSplineN().
get_spatial_extent()
static int LunaCubicSplineN::get_spatial_extent (T * p, lua_State * L) inline static
References dimension_index(), and CubicSplineN::get_spatial_extent().
Referenced by LunaCubicSplineN().
LCSN_EVAL_SOMETHING() [1/4]
LunaCubicSplineN::LCSN_EVAL_SOMETHING (evaluate)
LCSN_EVAL_SOMETHING() [2/4]
LunaCubicSplineN::LCSN_EVAL_SOMETHING (evaluate_derivative)
LCSN_EVAL_SOMETHING() [3/4]
LunaCubicSplineN::LCSN_EVAL_SOMETHING (evaluate_second_derivative)
LCSN_EVAL_SOMETHING() [4/4]
LunaCubicSplineN::LCSN_EVAL_SOMETHING (evaluate_third_derivative)
point_index()
static size_t LunaCubicSplineN::point_index (T * p, lua_State * L, int s) inline static
References IArg, and CubicSplineN::size().
Referenced by get_coefficients(), set_coefficients(), and set_point().
set_coefficients()
static int LunaCubicSplineN::set_coefficients (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, point_index(), and set_coefficients_from_stack().
Referenced by LunaCubicSplineN().
set_coefficients_from_stack()
static void LunaCubicSplineN::set_coefficients_from_stack (T * p, lua_State * L, size_t i, int s) inline static
References CubicSplineN::dimension(), get_element_table_from_stack(), and CubicSplineN::set_coefficients().
Referenced by set_coefficients().
set_dimension()
static int LunaCubicSplineN::set_dimension (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, CubicSplineN::m_owned_by_actor, and CubicSplineN::redimension().
Referenced by LunaCubicSplineN().
SET_GET_LUA() [1/3]
LunaCubicSplineN::SET_GET_LUA (loop)
SET_GET_LUA() [2/3]
LunaCubicSplineN::SET_GET_LUA (polygonal)
SET_GET_LUA() [3/3]
LunaCubicSplineN::SET_GET_LUA (dirty)
set_point()
static int LunaCubicSplineN::set_point (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, point_index(), and set_point_from_stack().
Referenced by LunaCubicSplineN().
set_point_from_stack()
static void LunaCubicSplineN::set_point_from_stack (T * p, lua_State * L, size_t i, int s) inline static
References CubicSplineN::dimension(), get_element_table_from_stack(), and CubicSplineN::set_point().
Referenced by set_point().
set_size()
static int LunaCubicSplineN::set_size (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, IArg, and CubicSplineN::resize().
Referenced by LunaCubicSplineN().
set_spatial_extent()
static int LunaCubicSplineN::set_spatial_extent (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, dimension_index(), FArg, and CubicSplineN::set_spatial_extent().
Referenced by LunaCubicSplineN().
solve()
static int LunaCubicSplineN::solve (T * p, lua_State * L) inline static
References COMMON_RETURN_SELF, and CubicSplineN::solve().
Referenced by LunaCubicSplineN().
The documentation for this struct was generated from the following file:
CubicSpline.cpp