Etterna: ScoresForChart Struct Reference
ScoresForChart Struct Reference
#include <ScoreManager.h>
Public Member Functions
ScoresForChart ()
HighScore * GetPBAt (float &rate)
HighScore * GetPBUpTo (float &rate)
vector< HighScore * > GetAllPBPtrs ()
HighScore * AddScore (HighScore &hs)
vector< float > GetPlayedRates ()
vector< int > GetPlayedRateKeys ()
vector< string > GetPlayedRateDisplayStrings ()
string RateKeyToDisplayString (float rate)
int RateToKey (float &rate)
float KeyToRate (int key)
void PushSelf (lua_State *L)
ScoresAtRate * GetScoresAtRate (const int &rate)
XNode * CreateNode (const string &ck) const
void LoadFromNode (const XNode *node, const string &ck, const string &profileID)
ScoresAtRate operator[] (const int rate)
void SetTopScores ()
Public Attributes
Grade bestGrade = Grade_Invalid
Chart ch
map< int, ScoresAtRate, greater< int > > ScoresByRate
Constructor & Destructor Documentation
ScoresForChart()
ScoresForChart::ScoresForChart ()
References bestGrade, Grade_Invalid, and ScoresByRate.
Member Function Documentation
AddScore()
HighScore * ScoresForChart::AddScore (HighScore & hs)
References bestGrade, HighScore::GetMusicRate(), HighScore::GetWifeGrade(), min(), RateToKey(), ScoresByRate, HighScore::SetTopScore(), and SetTopScores().
CreateNode()
XNode * ScoresForChart::CreateNode (const string & ck) const
References XNode::AppendChild(), ch, Chart::CreateNode(), FOREACHM_CONST, Chart::FromKey(), and ScoresByRate.
GetAllPBPtrs()
vector< HighScore * > ScoresForChart::GetAllPBPtrs ()
References FOREACHM, and ScoresByRate.
GetPBAt()
HighScore * ScoresForChart::GetPBAt (float & rate)
References RateToKey(), and ScoresByRate.
GetPBUpTo()
HighScore * ScoresForChart::GetPBUpTo (float & rate)
References FOREACHM, RateToKey(), and ScoresByRate.
GetPlayedRateDisplayStrings()
vector< string > ScoresForChart::GetPlayedRateDisplayStrings ()
References GetPlayedRates(), and RateKeyToDisplayString().
Referenced by LunaScoreManager::GetScoresByKey().
GetPlayedRateKeys()
vector< int > ScoresForChart::GetPlayedRateKeys ()
References FOREACHM, and ScoresByRate.
Referenced by LunaScoreManager::GetScoresByKey().
GetPlayedRates()
vector< float > ScoresForChart::GetPlayedRates ()
References FOREACHM, KeyToRate(), and ScoresByRate.
Referenced by GetPlayedRateDisplayStrings().
GetScoresAtRate()
ScoresAtRate * ScoresForChart::GetScoresAtRate (const int & rate)
References ScoresByRate.
Referenced by LunaScoreManager::GetScoresByKey().
KeyToRate()
float ScoresForChart::KeyToRate (int key) inline
References f.
Referenced by GetPlayedRates(), and LoadFromNode().
LoadFromNode()
void ScoresForChart::LoadFromNode (const XNode * node, const string & ck, const string & profileID)
References ASSERT, bestGrade, ch, FOREACH_CONST_Child, XNode::GetAttrValue(), XNode::GetName(), Chart::key, KeyToRate(), Chart::lastpack, Chart::lastsong, Chart::LoadFromNode(), min(), ScoresByRate, and StringToInt().
operator[]()
ScoresAtRate ScoresForChart::operator[] (const int rate) inline
References ScoresByRate.
PushSelf()
void ScoresForChart::PushSelf (lua_State * L)
RateKeyToDisplayString()
string ScoresForChart::RateKeyToDisplayString (float rate)
References ssprintf().
Referenced by GetPlayedRateDisplayStrings().
RateToKey()
int ScoresForChart::RateToKey (float & rate) inline
References f.
Referenced by AddScore(), GetPBAt(), and GetPBUpTo().
SetTopScores()
void ScoresForChart::SetTopScores ()
References FOREACHM, GetCalcVersion(), HighScore::GetSkillsetSSR(), Grade_Failed, ScoresByRate, and Skill_Overall.
Referenced by AddScore().
Member Data Documentation
bestGrade
Grade ScoresForChart::bestGrade = Grade_Invalid
Referenced by AddScore(), LoadFromNode(), and ScoresForChart().
ch
Chart ScoresForChart::ch
Referenced by CreateNode(), and LoadFromNode().
ScoresByRate
map<int, ScoresAtRate, greater<int> > ScoresForChart::ScoresByRate
Referenced by AddScore(), CreateNode(), GetAllPBPtrs(), GetPBAt(), GetPBUpTo(), GetPlayedRateKeys(), GetPlayedRates(), GetScoresAtRate(), LoadFromNode(), operator[](), ScoresForChart(), and SetTopScores().
The documentation for this struct was generated from the following files:
ScoreManager.h
ScoreManager.cpp