Etterna: LowLevelWindow_MacOSX.mm File Reference
LowLevelWindow_MacOSX.mm File Reference
#import "global.h"
#import "LowLevelWindow_MacOSX.h"
#import "DisplayResolutions.h"
#import "RageUtil.h"
#import "RageThreads.h"
#import "RageDisplay_OGL_Helpers.h"
#import "arch/ArchHooks/ArchHooks.h"
#import <Cocoa/Cocoa.h>
#import <OpenGL/OpenGL.h>
#import <OpenGL/gl.h>
#import <mach-o/dyld.h>
#include <IOKit/graphics/IOGraphicsLib.h>
Classes
class AutoreleasePool
class SMWindowDelegate
class RenderTarget_MacOSX
Macros
#define POOL AutoreleasePool SM_UNIQUE_NAME(pool)
#define X(x) p.x != m_CurrentParams.x
Enumerations
enum GLContextType { WINDOWED, FULL_SCREEN, PIXEL_BUFFER }
Functions
static NSOpenGLContext * CreateOGLContext (GLContextType type, int iColorSize, int iAlphaSize, int iDepthSize, NSOpenGLContext *share, bool &bShared)
static size_t GetDisplayBitsPerPixel (CGDirectDisplayID displayId)
static int GetIntValue (CFTypeRef r)
static bool GetBoolValue (CFTypeRef r)
Variables
static const unsigned int g_iStyleMask
static bool g_bResized
static int g_iWidth
static int g_iHeight
static RageMutex g_ResizeLock ("Window resize lock.")
Macro Definition Documentation
POOL
#define POOL AutoreleasePool SM_UNIQUE_NAME(pool)
Referenced by RenderTarget_MacOSX::Create(), LowLevelWindow_MacOSX::LowLevelWindow_MacOSX(), LowLevelWindow_MacOSX::TryVideoMode(), LowLevelWindow_MacOSX::~LowLevelWindow_MacOSX(), and RenderTarget_MacOSX::~RenderTarget_MacOSX().
X
#define X (x) p.x != m_CurrentParams.x
Referenced by LowLevelWindow_MacOSX::TryVideoMode().
Enumeration Type Documentation
GLContextType
enum GLContextType
Enumerator
WINDOWED
FULL_SCREEN
PIXEL_BUFFER
Function Documentation
CreateOGLContext()
static NSOpenGLContext* CreateOGLContext (GLContextType type, int iColorSize, int iAlphaSize, int iDepthSize, NSOpenGLContext * share, bool & bShared) static
References FULL_SCREEN, PIXEL_BUFFER, and WINDOWED.
Referenced by RenderTarget_MacOSX::Create(), and LowLevelWindow_MacOSX::TryVideoMode().
GetBoolValue()
static bool GetBoolValue (CFTypeRef r) static
Referenced by LowLevelWindow_MacOSX::GetDisplayResolutions().
GetDisplayBitsPerPixel()
static size_t GetDisplayBitsPerPixel (CGDirectDisplayID displayId) static
Referenced by LowLevelWindow_MacOSX::SetActualParamsFromMode().
GetIntValue()
static int GetIntValue (CFTypeRef r) static
Referenced by LowLevelWindow_MacOSX::GetDisplayResolutions().
Variable Documentation
g_bResized
bool g_bResized static
Referenced by LowLevelWindow_MacOSX::Update(), and SMWindowDelegate::windowDidResize:.
g_iHeight
int g_iHeight static
Referenced by LowLevelWindow_MacOSX::Update(), and SMWindowDelegate::windowDidResize:.
g_iStyleMask
const unsigned int g_iStyleMask static
Initial value:
= NSTitledWindowMask | NSClosableWindowMask |
                     NSMiniaturizableWindowMask | NSResizableWindowMask
g_iWidth
int g_iWidth static
Referenced by LowLevelWindow_MacOSX::Update(), and SMWindowDelegate::windowDidResize:.
g_ResizeLock
RageMutex g_ResizeLock("Window resize lock.") static
Referenced by LowLevelWindow_MacOSX::Update(), and SMWindowDelegate::windowDidResize:.