Etterna: RageSurface_Save_BMP.cpp File Reference
RageSurface_Save_BMP.cpp File Reference
#include "global.h"
#include "RageSurface_Save_BMP.h"
#include "RageFile.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageUtil.h"
Functions
static void WriteBytes (RageFile &f, RString &sError, const void *buf, int size)
static void write_le16 (RageFile &f, RString &sError, uint16_t val)
static void write_le32 (RageFile &f, RString &sError, uint32_t val)
Function Documentation
write_le16()
static void write_le16 (RageFile & f, RString & sError, uint16_t val) static
References Swap16LE(), and WriteBytes().
Referenced by RageSurfaceUtils::SaveBMP().
write_le32()
static void write_le32 (RageFile & f, RString & sError, uint32_t val) static
References Swap32LE(), and WriteBytes().
Referenced by RageSurfaceUtils::SaveBMP().
WriteBytes()
static void WriteBytes (RageFile & f, RString & sError, const void * buf, int size) static
References RageFile::GetError(), and RageFile::Write().
Referenced by RageSurfaceUtils::SaveBMP(), write_le16(), and write_le32().