Etterna: RageSoundReader_WAV Class Reference
RageSoundReader_WAV Class Reference
#include <RageSoundReader_WAV.h>
Classes
struct WavData
Public Member Functions
OpenResult Open (RageFileBasic *pFile) override
void Close ()
int GetLength () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
int GetNextSourceFrame () const override
RageSoundReader_WAV ()
~RageSoundReader_WAV () override
RageSoundReader_WAV (const RageSoundReader_WAV &)
RageSoundReader_WAV * Copy () const override
Public Member Functions inherited from RageSoundReader_FileReader
float GetStreamToSourceRatio () const override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual int GetLength_Fast () const
virtual ~RageSoundReader ()=default
virtual bool SetProperty (const RString &, float)
virtual RageSoundReader * GetSource ()
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Attributes
WavData m_WavData
WavReader * m_pImpl
Additional Inherited Members
Public Types inherited from RageSoundReader_FileReader
enum OpenResult { OPEN_OK, OPEN_UNKNOWN_FILE_FORMAT = 1, OPEN_FATAL_ERROR = 2 }
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Static Public Member Functions inherited from RageSoundReader_FileReader
static RageSoundReader_FileReader * OpenFile (const RString &filename, RString &error, bool *pPrebuffer=NULL)
Protected Member Functions inherited from RageSoundReader_FileReader
void SetError (const RString &sError) const
Protected Attributes inherited from RageSoundReader_FileReader
HiddenPtr< RageFileBasic > m_pFile
Constructor & Destructor Documentation
RageSoundReader_WAV() [1/2]
RageSoundReader_WAV::RageSoundReader_WAV ()
References m_pImpl.
Referenced by Copy().
~RageSoundReader_WAV()
RageSoundReader_WAV::~RageSoundReader_WAV () override
References m_pImpl.
RageSoundReader_WAV() [2/2]
RageSoundReader_WAV::RageSoundReader_WAV (const RageSoundReader_WAV &)
Member Function Documentation
Close()
void RageSoundReader_WAV::Close ()
Copy()
RageSoundReader_WAV * RageSoundReader_WAV::Copy () const override virtual
Implements RageSoundReader.
References RageFileBasic::Copy(), RageSoundReader_FileReader::m_pFile, RageSoundReader_WAV(), and RageFileBasic::Seek().
GetLength()
int RageSoundReader_WAV::GetLength () const override virtual
Implements RageSoundReader.
References ASSERT, WavReader::GetLength(), and m_pImpl.
GetNextSourceFrame()
int RageSoundReader_WAV::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References ASSERT, WavReader::GetNextSourceFrame(), and m_pImpl.
GetNumChannels()
unsigned RageSoundReader_WAV::GetNumChannels () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_WAV::WavData::m_iChannels, and m_WavData.
GetSampleRate()
int RageSoundReader_WAV::GetSampleRate () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_WAV::WavData::m_iSampleRate, and m_WavData.
Open()
RageSoundReader_FileReader::OpenResult RageSoundReader_WAV::Open (RageFileBasic * pFile) override virtual
Implements RageSoundReader_FileReader.
References FATAL_ERROR, RageFileBasic::GetDisplayPath(), WavReader::GetError(), RageFileBasic::GetFileSize(), WavReader::Init(), LOG, RageSoundReader_WAV::WavData::m_iBitsPerSample, RageSoundReader_WAV::WavData::m_iBlockAlign, RageSoundReader_WAV::WavData::m_iChannels, RageSoundReader_WAV::WavData::m_iDataChunkPos, RageSoundReader_WAV::WavData::m_iDataChunkSize, RageSoundReader_WAV::WavData::m_iExtraFmtBytes, RageSoundReader_WAV::WavData::m_iExtraFmtPos, RageSoundReader_WAV::WavData::m_iFormatTag, RageSoundReader_WAV::WavData::m_iSampleRate, RageSoundReader_FileReader::m_pFile, m_pImpl, m_WavData, RageSoundReader_FileReader::OPEN_FATAL_ERROR, RageSoundReader_FileReader::OPEN_OK, RageSoundReader_FileReader::OPEN_UNKNOWN_FILE_FORMAT, FileReading::read_16_le(), FileReading::read_32_le(), ReadString(), RageFileBasic::Seek(), RageSoundReader_FileReader::SetError(), ssprintf(), RageFileBasic::Tell(), and RageLog::Warn().
Read()
int RageSoundReader_WAV::Read (float * pBuf, int iFrames) override virtual
Implements RageSoundReader.
References ASSERT, m_pImpl, and WavReader::Read().
SetPosition()
int RageSoundReader_WAV::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References ASSERT, m_pImpl, and WavReader::SetPosition().
Member Data Documentation
m_pImpl
WavReader* RageSoundReader_WAV::m_pImpl private
Referenced by GetLength(), GetNextSourceFrame(), Open(), RageSoundReader_WAV(), Read(), SetPosition(), and ~RageSoundReader_WAV().
m_WavData
WavData RageSoundReader_WAV::m_WavData private
Referenced by GetNumChannels(), GetSampleRate(), and Open().
The documentation for this class was generated from the following files:
RageSoundReader_WAV.h
RageSoundReader_WAV.cpp