Etterna: RageMath.h File Reference
RageMath.h File Reference
#include "global.h"
Classes
class RageQuadratic
class RageBezier2D
Macros
#define PI (3.141592653589793f)
#define DegreeToRadian(degree) ((degree) * (PI / 180.0f))
#define RadianToDegree(radian) ((radian) * (180.0f / PI))
Functions
void RageVec3ClearBounds (struct RageVector3 &mins, RageVector3 &maxs)
void RageVec3AddToBounds (const struct RageVector3 &p, RageVector3 &mins, RageVector3 &maxs)
void RageVec2Normalize (struct RageVector2 *pOut, const struct RageVector2 *pV)
void RageVec3Normalize (struct RageVector3 *pOut, const struct RageVector3 *pV)
void VectorFloatNormalize (vector< float > &v)
void RageVec3Cross (struct RageVector3 *ret, struct RageVector3 const *a, struct RageVector3 const *b)
void RageVec3TransformCoord (struct RageVector3 *pOut, const struct RageVector3 *pV, const struct RageMatrix *pM)
void RageVec3TransformNormal (struct RageVector3 *pOut, const struct RageVector3 *pV, const struct RageMatrix *pM)
void RageVec4TransformCoord (struct RageVector4 *pOut, const struct RageVector4 *pV, const struct RageMatrix *pM)
void RageMatrixIdentity (struct RageMatrix *pOut)
void RageMatrixMultiply (struct RageMatrix *pOut, const struct RageMatrix *pA, const struct RageMatrix *pB)
void RageMatrixTranslation (struct RageMatrix *pOut, float x, float y, float z)
void RageMatrixScaling (struct RageMatrix *pOut, float x, float y, float z)
void RageMatrixSkewX (struct RageMatrix *pOut, float fAmount)
void RageMatrixSkewY (struct RageMatrix *pOut, float fAmount)
void RageMatrixTranslate (struct RageMatrix *pOut, float fTransX, float fTransY, float fTransZ)
void RageMatrixScale (struct RageMatrix *pOut, float fScaleX, float fScaleY, float fScaleZ)
void RageMatrixRotationX (struct RageMatrix *pOut, float fTheta)
void RageMatrixRotationY (struct RageMatrix *pOut, float fTheta)
void RageMatrixRotationZ (struct RageMatrix *pOut, float fTheta)
void RageMatrixRotationXYZ (struct RageMatrix *pOut, float rX, float rY, float rZ)
void RageAARotate (struct RageVector3 *inret, struct RageVector3 const *axis, float angle)
void RageQuatFromHPR (struct RageVector4 *pOut, struct RageVector3 hpr)
void RageQuatFromPRH (struct RageVector4 *pOut, struct RageVector3 prh)
void RageMatrixFromQuat (struct RageMatrix *pOut, const struct RageVector4 &q)
void RageQuatSlerp (struct RageVector4 *pOut, const struct RageVector4 &from, const RageVector4 &to, float t)
struct RageVector4 RageQuatFromH (float theta)
struct RageVector4 RageQuatFromP (float theta)
struct RageVector4 RageQuatFromR (float theta)
void RageQuatMultiply (struct RageVector4 *pOut, const struct RageVector4 &pA, const RageVector4 &pB)
struct RageMatrix RageLookAt (float eyex, float eyey, float eyez, float centerx, float centery, float centerz, float upx, float upy, float upz)
void RageMatrixAngles (struct RageMatrix *pOut, const struct RageVector3 &angles)
void RageMatrixTranspose (struct RageMatrix *pOut, const struct RageMatrix *pIn)
float RageFastSin (float x) CONST_FUNCTION
float RageFastCos (float x) CONST_FUNCTION
Macro Definition Documentation
DegreeToRadian
#define DegreeToRadian (degree) ((degree) * (PI / 180.0f))
PI
#define PI (3.141592653589793f)
Referenced by RageDisplay::DrawCircleInternal(), RageDisplay::GetPerspectiveMatrix(), ArrowEffects::GetRotationZ(), ArrowEffects::GetXPos(), RageDisplay::LoadMenuPerspective(), GraphLine::MakeCircle(), NoteColumnRenderer::NCR_TweenState::NCR_TweenState(), Actor::PreDraw(), RADAR_VALUE_ROTATION(), RageFastCos(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationXYZ(), RageMatrixRotationY(), RageMatrixRotationZ(), RageQuatFromH(), RageQuatFromHPR(), RageQuatFromP(), RageQuatFromPRH(), RageQuatFromR(), ArrowEffects::ReceptorGetRotationZ(), sine_initter::sine_initter(), TweenSpring::Tween(), and ArrowEffects::Update().
RadianToDegree
#define RadianToDegree (radian) ((radian) * (180.0f / PI))
Referenced by msAnimation::LoadMilkshapeAsciiBones().
Function Documentation
RageAARotate()
void RageAARotate (struct RageVector3 * inret, struct RageVector3 const * axis, float angle)
RageFastCos()
float RageFastCos (float x)
References f, PI, and RageFastSin().
Referenced by RageDisplay::DrawCircleInternal(), NoteField::DrawPrimitives(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ArrowEffects::GetXPos(), ArrowEffects::GetYOffset(), GraphLine::MakeCircle(), Actor::PreDraw(), RageAARotate(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationXYZ(), RageMatrixRotationY(), RageMatrixRotationZ(), RageQuatFromH(), RageQuatFromHPR(), RageQuatFromP(), RageQuatFromPRH(), RageQuatFromR(), TweenSpring::Tween(), and ArrowEffects::Update().
RageFastSin()
float RageFastSin (float x)
References lerp(), second, SET_SAMPLE, sine_index_mod, and sine_table_index_mult.
Referenced by ArrowGetPercentVisible(), RageDisplay::DrawCircleInternal(), GrooveRadar::GrooveRadarValueMap::DrawPrimitives(), ArrowEffects::GetXPos(), ArrowEffects::GetYOffset(), ArrowEffects::GetZPos(), GraphLine::MakeCircle(), Actor::PreDraw(), RageAARotate(), RageFastCos(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationXYZ(), RageMatrixRotationY(), RageMatrixRotationZ(), RageQuatFromH(), RageQuatFromHPR(), RageQuatFromP(), RageQuatFromPRH(), RageQuatFromR(), and RageQuatSlerp().
RageLookAt()
struct RageMatrix RageLookAt (float eyex, float eyey, float eyez, float centerx, float centery, float centerz, float upx, float upy, float upz)
References RageMatrixMultiply(), RageMatrixTranslation(), RageVec3Normalize(), and X.
Referenced by RageDisplay::LoadLookAt(), and RageDisplay::LoadMenuPerspective().
RageMatrixAngles()
void RageMatrixAngles (struct RageMatrix * pOut, const struct RageVector3 & angles)
RageMatrixFromQuat()
void RageMatrixFromQuat (struct RageMatrix * pOut, const struct RageVector4 & q)
RageMatrixIdentity()
void RageMatrixIdentity (struct RageMatrix * pOut)
Referenced by MatrixStack::LoadIdentity(), RageDisplay::RageDisplay(), RageMatrixAngles(), RageMatrixRotationX(), RageMatrixRotationY(), RageMatrixRotationZ(), RageMatrixScaling(), RageMatrixSkewX(), RageMatrixSkewY(), RageMatrixTranslation(), and Model::SetBones().
RageMatrixMultiply()
void RageMatrixMultiply (struct RageMatrix * pOut, const struct RageMatrix * pA, const struct RageMatrix * pB)
RageMatrixRotationX()
void RageMatrixRotationX (struct RageMatrix * pOut, float fTheta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by MatrixStack::RotateX(), and MatrixStack::RotateXLocal().
RageMatrixRotationXYZ()
void RageMatrixRotationXYZ (struct RageMatrix * pOut, float rX, float rY, float rZ)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::BeginDraw().
RageMatrixRotationY()
void RageMatrixRotationY (struct RageMatrix * pOut, float fTheta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by DancingCharacters::DrawPrimitives(), MatrixStack::RotateY(), and MatrixStack::RotateYLocal().
RageMatrixRotationZ()
void RageMatrixRotationZ (struct RageMatrix * pOut, float fTheta)
References RageMatrix::m, PI, RageFastCos(), RageFastSin(), and RageMatrixIdentity().
Referenced by MatrixStack::RotateZ(), and MatrixStack::RotateZLocal().
RageMatrixScale()
void RageMatrixScale (struct RageMatrix * pOut, float fScaleX, float fScaleY, float fScaleZ)
Referenced by Actor::BeginDraw(), RageDisplay_D3D::SendCurrentMatrices(), and RageDisplay_Legacy::SendCurrentMatrices().
RageMatrixScaling()
void RageMatrixScaling (struct RageMatrix * pOut, float x, float y, float z)
References RageMatrixIdentity().
Referenced by RageDisplay::GetCenteringMatrix(), RageDisplay_D3D::GetOrthoMatrix(), MatrixStack::Scale(), and MatrixStack::ScaleLocal().
RageMatrixSkewX()
void RageMatrixSkewX (struct RageMatrix * pOut, float fAmount)
References RageMatrix::m, and RageMatrixIdentity().
Referenced by MatrixStack::SkewX().
RageMatrixSkewY()
void RageMatrixSkewY (struct RageMatrix * pOut, float fAmount)
References RageMatrix::m, and RageMatrixIdentity().
Referenced by MatrixStack::SkewY().
RageMatrixTranslate()
void RageMatrixTranslate (struct RageMatrix * pOut, float fTransX, float fTransY, float fTransZ)
Referenced by Actor::BeginDraw().
RageMatrixTranslation()
void RageMatrixTranslation (struct RageMatrix * pOut, float x, float y, float z)
References RageMatrixIdentity().
Referenced by RageDisplay::GetCenteringMatrix(), RageDisplay_D3D::GetOrthoMatrix(), RageLookAt(), MatrixStack::Translate(), and MatrixStack::TranslateLocal().
RageMatrixTranspose()
void RageMatrixTranspose (struct RageMatrix * pOut, const struct RageMatrix * pIn)
RageQuatFromH()
struct RageVector4 RageQuatFromH (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationH().
RageQuatFromHPR()
void RageQuatFromHPR (struct RageVector4 * pOut, struct RageVector3 hpr)
References PI, RageFastCos(), RageFastSin(), RageVector4::w, RageVector3::x, RageVector4::x, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
Referenced by msAnimation::LoadMilkshapeAsciiBones().
RageQuatFromP()
struct RageVector4 RageQuatFromP (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationP().
RageQuatFromPRH()
void RageQuatFromPRH (struct RageVector4 * pOut, struct RageVector3 prh)
References PI, RageFastCos(), RageFastSin(), RageVector4::w, RageVector3::x, RageVector4::x, RageVector3::y, RageVector4::y, RageVector3::z, and RageVector4::z.
RageQuatFromR()
struct RageVector4 RageQuatFromR (float theta)
References PI, RageFastCos(), and RageFastSin().
Referenced by Actor::AddRotationR().
RageQuatMultiply()
void RageQuatMultiply (struct RageVector4 * pOut, const struct RageVector4 & pA, const RageVector4 & pB)
RageQuatSlerp()
void RageQuatSlerp (struct RageVector4 * pOut, const struct RageVector4 & from, const RageVector4 & to, float t)
RageVec2Normalize()
void RageVec2Normalize (struct RageVector2 * pOut, const struct RageVector2 * pV)
RageVec3AddToBounds()
void RageVec3AddToBounds (const struct RageVector3 & p, RageVector3 & mins, RageVector3 & maxs)
RageVec3ClearBounds()
void RageVec3ClearBounds (struct RageVector3 & mins, RageVector3 & maxs)
Referenced by RageModelGeometry::LoadMilkshapeAscii().
RageVec3Cross()
void RageVec3Cross (struct RageVector3 * ret, struct RageVector3 const * a, struct RageVector3 const * b)
RageVec3Normalize()
void RageVec3Normalize (struct RageVector3 * pOut, const struct RageVector3 * pV)
RageVec3TransformCoord()
void RageVec3TransformCoord (struct RageVector3 * pOut, const struct RageVector3 * pV, const struct RageMatrix * pM)
RageVec3TransformNormal()
void RageVec3TransformNormal (struct RageVector3 * pOut, const struct RageVector3 * pV, const struct RageMatrix * pM)
RageVec4TransformCoord()
void RageVec4TransformCoord (struct RageVector4 * pOut, const struct RageVector4 * pV, const struct RageMatrix * pM)
VectorFloatNormalize()
void VectorFloatNormalize (vector< float > & v)
References ASSERT_M, and scale().