Etterna: ITween Class Reference
ITween Class Reference abstract
The interface for simple interpolation.
#include <Tween.h>
Public Member Functions
virtual ~ITween ()=default
Create the initial interface.
virtual float Tween (float f) const =0
virtual ITween * Copy () const =0
Static Public Member Functions
static ITween * CreateFromType (TweenType iType)
static ITween * CreateFromStack (Lua *L, int iStackPos)
Detailed Description
The interface for simple interpolation.
Funny enough, this is a class.
Constructor & Destructor Documentation
~ITween()
virtual ITween::~ITween () virtual default
Create the initial interface.
Member Function Documentation
Copy()
virtual ITween* ITween::Copy () const pure virtual
Implemented in InterpolateBezier2D, InterpolateBezier1D, TweenSpring, TweenDecelerate, TweenAccelerate, and TweenLinear.
Referenced by Actor::TweenInfo::operator=().
CreateFromStack()
ITween * ITween::CreateFromStack (Lua * L, int iStackPos) static
References CreateFromType(), L, InterpolateBezier1D::m_Bezier, InterpolateBezier2D::m_Bezier, LuaHelpers::ReportScriptErrorFmt(), RageQuadratic::SetFromBezier(), RageBezier2D::SetFromBezier(), and TWEEN_BEZIER.
Referenced by LunaActor::tween().
CreateFromType()
ITween * ITween::CreateFromType (TweenType iType) static
References FAIL_M, ssprintf(), TWEEN_ACCELERATE, TWEEN_DECELERATE, TWEEN_LINEAR, and TWEEN_SPRING.
Referenced by Actor::BeginTweening(), and CreateFromStack().
Tween()
virtual float ITween::Tween (float f) const pure virtual
Implemented in InterpolateBezier2D, InterpolateBezier1D, TweenSpring, TweenDecelerate, TweenAccelerate, and TweenLinear.
Referenced by Actor::CalcPercentThroughTween().
The documentation for this class was generated from the following files:
Tween.h
Tween.cpp