Etterna: ScrollSegment Struct Reference
ScrollSegment Struct Reference
Identifies when the chart scroll changes.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
ScrollSegment (int iStartRow=ROW_INVALID, float fRatio=1.0f)
ScrollSegment (const ScrollSegment &other)
float GetRatio () const
void SetRatio (float fRatio)
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const ScrollSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
float m_fRatio
The percentage by which the chart's scroll rate is multiplied.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when the chart scroll changes.
ScrollSegments adjusts the scrolling speed of the note field. Unlike forced attacks, these cannot be turned off at a set time: reset it by setting the precentage back to 1.
These were inspired by the Pump It Up series.
Constructor & Destructor Documentation
ScrollSegment() [1/2]
ScrollSegment::ScrollSegment (int iStartRow = ROW_INVALID, float fRatio = 1.0f) inline
Referenced by Copy().
ScrollSegment() [2/2]
ScrollSegment::ScrollSegment (const ScrollSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* ScrollSegment::Copy () const inline override virtual
Implements TimingSegment.
References ScrollSegment().
DebugPrint()
void ScrollSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetRatio(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetEffectType()
SegmentEffectType ScrollSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetRatio()
float ScrollSegment::GetRatio () const inline
References m_fRatio.
Referenced by DebugPrint(), GenerateCacheDataStructure(), GetValues(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetType()
TimingSegmentType ScrollSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_SCROLL.
Referenced by DebugPrint(), and operator==().
GetValues()
vector<float> ScrollSegment::GetValues () const inline override virtual
Reimplemented from TimingSegment.
References GetRatio().
IsNotable()
bool ScrollSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool ScrollSegment::operator== (const ScrollSegment & other) const inline
References COMPARE_FLOAT, and m_fRatio.
Referenced by operator==().
operator==() [2/2]
bool ScrollSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetRatio()
void ScrollSegment::SetRatio (float fRatio) inline
References m_fRatio.
ToString()
RString ScrollSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetRatio(), IntToString(), and ssprintf().
Member Data Documentation
m_fRatio
float ScrollSegment::m_fRatio private
The percentage by which the chart's scroll rate is multiplied.
Referenced by GetRatio(), operator==(), and SetRatio().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp