Etterna: ScreenOptionsReviewWorkout.cpp File Reference
ScreenOptionsReviewWorkout.cpp File Reference
#include "global.h"
#include "GameManager.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "OptionRowHandler.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "Profile.h"
#include "ProfileManager.h"
#include "RageUtil.h"
#include "ScreenManager.h"
#include "ScreenMiniMenu.h"
#include "ScreenOptionsCourseOverview.h"
#include "ScreenPrompt.h"
#include "ScreenTextEntry.h"
#include "SongManager.h"
#include "SongUtil.h"
#include "Style.h"
Enumerations
enum ReviewWorkoutRow {
ReviewWorkoutRow_Play, ReviewWorkoutRow_Edit, ReviewWorkoutRow_Shuffle, ReviewWorkoutRow_Save,
NUM_ReviewWorkoutRow
}
Functions
REGISTER_SCREEN_CLASS (ScreenOptionsCourseOverview)
AutoScreenMessage (SM_BackFromEnterName) void ScreenOptionsCourseOverview
Variables
static const MenuRowDef g_MenuRows []
static LocalizedString ERROR_SAVING_WORKOUT ("ScreenOptionsCourseOverview", "Error saving workout.")
static LocalizedString WORKOUT_SAVED ("ScreenOptionsCourseOverview", "Workout saved successfully.")
static LocalizedString ENTER_WORKOUT_NAME ("ScreenOptionsCourseOverview", "Enter a name for the workout.")
Enumeration Type Documentation
ReviewWorkoutRow
enum ReviewWorkoutRow
Enumerator
ReviewWorkoutRow_Play
ReviewWorkoutRow_Edit
ReviewWorkoutRow_Shuffle
ReviewWorkoutRow_Save
NUM_ReviewWorkoutRow
Function Documentation
AutoScreenMessage()
AutoScreenMessage (SM_BackFromEnterName)
References ScreenOptionsCourseOverview::EDIT_SCREEN, ThemeManager::GetPathS(), ScreenOptions::Init(), ThemeMetric< T >::Load(), RageSound::Load(), PrefsManager::m_iArcadeOptionsNavigation, Actor::m_sName, ScreenOptionsCourseOverview::m_soundSave, ScreenOptions::NAV_THREE_KEY_MENU, ScreenOptionsCourseOverview::PLAY_SCREEN, PREFSMAN, ScreenOptions::SetNavigation(), and THEME.
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenOptionsCourseOverview)
Variable Documentation
ENTER_WORKOUT_NAME
LocalizedString ENTER_WORKOUT_NAME("ScreenOptionsCourseOverview", "Enter a name for the workout.") static
Referenced by ScreenOptionsCourseOverview::ProcessMenuStart().
ERROR_SAVING_WORKOUT
LocalizedString ERROR_SAVING_WORKOUT("ScreenOptionsCourseOverview", "Error saving workout.") static
Referenced by ScreenOptionsCourseOverview::ProcessMenuStart().
g_MenuRows
const MenuRowDef g_MenuRows[] static
Initial value:
= {
    MenuRowDef(-1, "Play", true, EditMode_Practice, true, false, 0, NULL),
    MenuRowDef(-1,
               "Edit Workout",
               true,
               EditMode_Practice,
               true,
               false,
               0,
               NULL),
    MenuRowDef(-1, "Shuffle", true, EditMode_Practice, true, false, 0, NULL),
    MenuRowDef(-1, "Save", true, EditMode_Practice, true, false, 0, NULL),
}
WORKOUT_SAVED
LocalizedString WORKOUT_SAVED("ScreenOptionsCourseOverview", "Workout saved successfully.") static
Referenced by ScreenOptionsCourseOverview::HandleScreenMessage(), and ScreenOptionsCourseOverview::ProcessMenuStart().