Etterna: ScreenTextEntry.cpp File Reference
ScreenTextEntry.cpp File Reference
#include "ScreenTextEntry.h"
#include "ActorUtil.h"
#include "FontCharAliases.h"
#include "InputEventPlus.h"
#include "InputFilter.h"
#include "LocalizedString.h"
#include "LuaBinding.h"
#include "Preference.h"
#include "RageInput.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "ScreenPrompt.h"
#include "ThemeManager.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "global.h"
Classes
class LunaScreenTextEntry
Allow Lua to have access to the ScreenTextEntry.
Macros
#define SET_FUNCTION_MEMBER(memname)
Functions
LUA Release (L)
static bool ValidateAppendFromLua (const RString &sAnswerBeforeChar, const RString &sAppend)
static RString FormatAnswerForDisplayFromLua (const RString &sAnswer, LuaReference func)
static RString FormatAnswerForDisplayFromLua (const RString &sAnswer)
REGISTER_SCREEN_CLASS (ScreenTextEntry)
REGISTER_SCREEN_CLASS (ScreenTextEntryVisual)
Variables
static const char * g_szKeys [NUM_KeyboardRow][KEYS_PER_ROW]
return append
static LocalizedString INVALID_FLOAT ("ScreenTextEntry", "\s\is an invalid floating point value.")
static LocalizedString INVALID_INT ("ScreenTextEntry", "\s\is an invalid integer value.")
static LocalizedString ANSWER_CARET ("ScreenTextEntry", "AnswerCaret")
static LocalizedString ANSWER_BLANK ("ScreenTextEntry", "AnswerBlank")
Macro Definition Documentation
SET_FUNCTION_MEMBER
#define SET_FUNCTION_MEMBER (memname)
Value:
lua_getfield(L, iTab, #memname);                                           \
    if (lua_isfunction(L, -1)) {                                               \
        (memname).SetFromStack(L);                                             \
    } else if (!lua_isnil(L, -1)) {                                            \
        LuaHelpers::ReportScriptError("ScreenTextEntry \"" #memname            \
                                      "\" is not a function.");                \
    }                                                                          \
    lua_settop(L, iTab);
Referenced by ScreenTextEntry::TextEntrySettings::FromStack().
Function Documentation
FormatAnswerForDisplayFromLua() [1/2]
static RString FormatAnswerForDisplayFromLua (const RString & sAnswer, LuaReference func) static
References LuaManager::Get(), LuaReference::IsNil(), LuaReference::IsSet(), LUA, LuaHelpers::Pop(), LuaReference::PushSelf(), LuaManager::Release(), LuaHelpers::ReportScriptError(), and LuaHelpers::RunScriptOnStack().
Referenced by FormatAnswerForDisplayFromLua(), ScreenTextEntry::LoadFromTextEntrySettings(), and ScreenTextEntry::UpdateAnswerText().
FormatAnswerForDisplayFromLua() [2/2]
static RString FormatAnswerForDisplayFromLua (const RString & sAnswer) static
References FormatAnswerForDisplayFromLua().
REGISTER_SCREEN_CLASS() [1/2]
REGISTER_SCREEN_CLASS (ScreenTextEntry)
REGISTER_SCREEN_CLASS() [2/2]
REGISTER_SCREEN_CLASS (ScreenTextEntryVisual)
Release()
LUA Release (L)
ValidateAppendFromLua()
static bool ValidateAppendFromLua (const RString & sAnswerBeforeChar, const RString & sAppend) static
Referenced by ScreenTextEntry::LoadFromTextEntrySettings(), and ScreenTextEntry::TryAppendToAnswer().
Variable Documentation
ANSWER_BLANK
LocalizedString ANSWER_BLANK("ScreenTextEntry", "AnswerBlank") static
Referenced by ScreenTextEntry::UpdateAnswerText().
ANSWER_CARET
LocalizedString ANSWER_CARET("ScreenTextEntry", "AnswerCaret") static
Referenced by ScreenTextEntry::UpdateAnswerText().
append
return append
Referenced by Rage::join(), StdString::CStdStr< CT >::operator+=(), write_memory_buffer(), HighScore::WriteInputData(), and HighScoreImpl::WriteReplayData().
g_szKeys
const char* g_szKeys[NUM_KeyboardRow][KEYS_PER_ROW] static
Referenced by ScreenTextEntryVisual::Init(), ScreenTextEntryVisual::MenuStart(), ScreenTextEntryVisual::MoveX(), and ScreenTextEntryVisual::MoveY().
INVALID_FLOAT
LocalizedString INVALID_FLOAT("ScreenTextEntry", "\%s\ is an invalid floating point value.") static
Referenced by ScreenTextEntry::FloatValidate().
INVALID_INT
LocalizedString INVALID_INT("ScreenTextEntry", "\%s\ is an invalid integer value.") static
Referenced by ScreenTextEntry::IntValidate().