Etterna: ScreenReloadSongsLoadingWindow Class Reference
ScreenReloadSongsLoadingWindow Class Reference
Public Member Functions
ScreenReloadSongsLoadingWindow (BitmapText &bt)
void SetText (const RString &str) override
void Paint ()
Public Member Functions inherited from LoadingWindow
virtual RString Init ()
virtual ~LoadingWindow ()=default
virtual void SetIcon (const RageSurface *pIcon)
virtual void SetSplash (const RageSurface *pSplash)
virtual void SetProgress (const int progress)
virtual void SetTotalWork (const int totalWork)
virtual void SetIndeterminate (bool indeterminate)
Private Attributes
RageTimer m_LastDraw
BitmapText & m_BitmapText
Additional Inherited Members
Static Public Member Functions inherited from LoadingWindow
static LoadingWindow * Create ()
Protected Attributes inherited from LoadingWindow
int m_progress
int m_totalWork
bool m_indeterminate
Constructor & Destructor Documentation
ScreenReloadSongsLoadingWindow()
ScreenReloadSongsLoadingWindow::ScreenReloadSongsLoadingWindow (BitmapText & bt) inline explicit
Member Function Documentation
Paint()
void ScreenReloadSongsLoadingWindow::Paint () inline
References ScreenManager::Draw(), DrawFrameRate, RageTimer::GetDeltaTime(), RageTimer::PeekDeltaTime(), and SCREENMAN.
Referenced by SetText().
SetText()
void ScreenReloadSongsLoadingWindow::SetText (const RString & str) inline override virtual
Implements LoadingWindow.
References Paint(), and BitmapText::SetText().
Member Data Documentation
m_BitmapText
BitmapText& ScreenReloadSongsLoadingWindow::m_BitmapText private
m_LastDraw
RageTimer ScreenReloadSongsLoadingWindow::m_LastDraw private
The documentation for this class was generated from the following file:
ScreenReloadSongs.cpp