Etterna: NoteColorSprite Struct Reference
NoteColorSprite Struct Reference
#include <NoteDisplay.h>
Public Member Functions
NoteColorSprite ()
~NoteColorSprite ()
void Load (const RString &sButton, const RString &sElement, PlayerNumber, GameController, RString)
Sprite * Get (RString)
Private Attributes
map< RString, NoteResource * > g_p
Constructor & Destructor Documentation
NoteColorSprite()
NoteColorSprite::NoteColorSprite ()
References g_p.
~NoteColorSprite()
NoteColorSprite::~NoteColorSprite ()
References DeleteNoteResource(), and g_p.
Member Function Documentation
Get()
Sprite * NoteColorSprite::Get (RString Color)
References g_p.
Load()
void NoteColorSprite::Load (const RString & sButton, const RString & sElement, PlayerNumber pn, GameController gc, RString Color)
References g_p, and MakeNoteResource().
Referenced by NoteDisplay::Load().
Member Data Documentation
g_p
map<RString, NoteResource*> NoteColorSprite::g_p private
Referenced by Get(), Load(), NoteColorSprite(), and ~NoteColorSprite().
The documentation for this struct was generated from the following files:
NoteDisplay.h
NoteDisplay.cpp