Etterna: bmsCommandTree Struct Reference
bmsCommandTree Struct Reference
Classes
struct bmsNodeS
Public Member Functions
bmsCommandTree ()
~bmsCommandTree ()=default
bmsNodeS * addConditionalChain ()
bmsNodeS * createIfNode (bmsNodeS *Chain, int value)
bmsNodeS * createElseIfNode (bmsNodeS *Chain, int value)
bmsNodeS * createElseNode (bmsNodeS *Chain)
void appendNodeElements (bmsNodeS *node, BMSHeaders &headersOut, vector< RString > &linesOut)
bool triggerBranches (bmsNodeS *node, BMSHeaders &headersOut, vector< RString > &linesOut)
bool evaluateNode (bmsNodeS *node, BMSHeaders &headersOut, vector< RString > &linesOut)
void evaluateBMSTree (BMSHeaders &headersOut, vector< RString > &linesOut)
void doStatement (RString statement, map< int, bool > &referencedTracks)
Public Attributes
bmsNodeS * currentNode
bmsNodeS root
vector< unsigned int > randomStack
int line
RString path
Constructor & Destructor Documentation
bmsCommandTree()
bmsCommandTree::bmsCommandTree () inline
References bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::conditionTriggerValue, bmsCommandTree::bmsNodeS::conditionType, bmsCommandTree::bmsNodeS::conditionValue, bmsCommandTree::bmsNodeS::CT_NULL, bmsCommandTree::bmsNodeS::parent, and root.
~bmsCommandTree()
bmsCommandTree::~bmsCommandTree () default
Member Function Documentation
addConditionalChain()
bmsNodeS* bmsCommandTree::addConditionalChain () inline
References bmsCommandTree::bmsNodeS::branches, bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::conditionValue, bmsCommandTree::bmsNodeS::CT_CONDITIONALCHAIN, and currentNode.
Referenced by doStatement().
appendNodeElements()
void bmsCommandTree::appendNodeElements (bmsNodeS * node, BMSHeaders & headersOut, vector< RString > & linesOut) inline
References bmsCommandTree::bmsNodeS::ChannelCommands, and bmsCommandTree::bmsNodeS::Commands.
Referenced by evaluateNode().
createElseIfNode()
bmsNodeS* bmsCommandTree::createElseIfNode (bmsNodeS * Chain, int value) inline
References bmsCommandTree::bmsNodeS::branches, bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::conditionValue, and bmsCommandTree::bmsNodeS::CT_ELSEIF.
Referenced by doStatement().
createElseNode()
bmsNodeS* bmsCommandTree::createElseNode (bmsNodeS * Chain) inline
References bmsCommandTree::bmsNodeS::branches, bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::conditionValue, and bmsCommandTree::bmsNodeS::CT_ELSE.
Referenced by doStatement().
createIfNode()
bmsNodeS* bmsCommandTree::createIfNode (bmsNodeS * Chain, int value) inline
References bmsCommandTree::bmsNodeS::branches, bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::conditionValue, and bmsCommandTree::bmsNodeS::CT_IF.
Referenced by doStatement().
doStatement()
void bmsCommandTree::doStatement (RString statement, map< int, bool > & referencedTracks) inline
References addConditionalChain(), bmsCommandTree::bmsNodeS::branchHeight, bmsCommandTree::bmsNodeS::ChannelCommands, bmsCommandTree::bmsNodeS::Commands, bmsCommandTree::bmsNodeS::conditionType, createElseIfNode(), createElseNode(), createIfNode(), bmsCommandTree::bmsNodeS::CT_CONDITIONALCHAIN, g_RandomNumberGenerator, LOG, StdString::CStdStr< CT >::MakeLower(), bmsCommandTree::bmsNodeS::parent, random_up_to(), StringToInt(), and RageLog::UserLog().
Referenced by BMSChart::Load().
evaluateBMSTree()
void bmsCommandTree::evaluateBMSTree (BMSHeaders & headersOut, vector< RString > & linesOut) inline
References evaluateNode().
Referenced by BMSChart::Load().
evaluateNode()
bool bmsCommandTree::evaluateNode (bmsNodeS * node, BMSHeaders & headersOut, vector< RString > & linesOut) inline
References appendNodeElements(), bmsCommandTree::bmsNodeS::conditionTriggerValue, bmsCommandTree::bmsNodeS::conditionType, bmsCommandTree::bmsNodeS::conditionValue, bmsCommandTree::bmsNodeS::CT_CONDITIONALCHAIN, bmsCommandTree::bmsNodeS::CT_ELSE, bmsCommandTree::bmsNodeS::CT_ELSEIF, bmsCommandTree::bmsNodeS::CT_IF, bmsCommandTree::bmsNodeS::CT_NULL, bmsCommandTree::bmsNodeS::parent, and triggerBranches().
Referenced by evaluateBMSTree(), and triggerBranches().
triggerBranches()
bool bmsCommandTree::triggerBranches (bmsNodeS * node, BMSHeaders & headersOut, vector< RString > & linesOut) inline
References bmsCommandTree::bmsNodeS::branches, evaluateNode(), and FOREACH.
Referenced by evaluateNode().
Member Data Documentation
currentNode
bmsNodeS* bmsCommandTree::currentNode
Referenced by addConditionalChain().
line
int bmsCommandTree::line
path
RString bmsCommandTree::path
Referenced by BMSChart::Load().
randomStack
vector<unsigned int> bmsCommandTree::randomStack
root
bmsNodeS bmsCommandTree::root
Referenced by bmsCommandTree().
The documentation for this struct was generated from the following file:
NotesLoaderBMS.cpp