Etterna: TimingData Class Reference
TimingData Class Reference
Holds data for translating beats<->seconds.
#include <TimingData.h>
Classes
struct GetBeatArgs
struct GetBeatStarts
struct lookup_item_t
Public Types
typedef vector< lookup_item_t > beat_start_lookup_t
Public Member Functions
TimingData (float fOffset=0)
Sets up initial timing data with a defined offset.
~TimingData ()
void Copy (const TimingData &other)
void Clear ()
bool IsSafeFullTiming ()
TimingData (const TimingData &cpy)
TimingData & operator= (const TimingData &cpy)
void PrepareLookup ()
void ReleaseLookup ()
void DumpOneTable (const beat_start_lookup_t &lookup, const RString &name)
void DumpLookupTables ()
int GetSegmentIndexAtRow (TimingSegmentType tst, int row) const
int GetSegmentIndexAtBeat (TimingSegmentType tst, float beat) const
float GetNextSegmentBeatAtRow (TimingSegmentType tst, int row) const
float GetNextSegmentBeatAtBeat (TimingSegmentType tst, float beat) const
float GetPreviousSegmentBeatAtRow (TimingSegmentType tst, int row) const
float GetPreviousSegmentBeatAtBeat (TimingSegmentType tst, float beat) const
bool empty () const
void CopyRange (int start_row, int end_row, TimingSegmentType copy_type, int dest_row, TimingData &dest) const
void ShiftRange (int start_row, int end_row, TimingSegmentType shift_type, int shift_amount)
void ClearRange (int start_row, int end_row, TimingSegmentType clear_type)
void GetActualBPM (float &fMinBPMOut, float &fMaxBPMOut, float highest=FLT_MAX) const
Gets the actual BPM of the song, while respecting a limit.
const TimingSegment * GetSegmentAtRow (int iNoteRow, TimingSegmentType tst) const
Retrieve the TimingSegment at the specified row.
TimingSegment * GetSegmentAtRow (int iNoteRow, TimingSegmentType tst)
const TimingSegment * GetSegmentAtBeat (float fBeat, TimingSegmentType tst) const
Retrieve the TimingSegment at the given beat.
TimingSegment * GetSegmentAtBeat (float fBeat, TimingSegmentType tst)
DefineSegment (BPM, BPM)
DefineSegment (Stop, STOP)
DefineSegment (Delay, DELAY)
DefineSegment (Warp, WARP)
DefineSegment (Label, LABEL)
DefineSegment (Tickcount, TICKCOUNT)
DefineSegment (Combo, COMBO)
DefineSegment (Speed, SPEED)
DefineSegment (Scroll, SCROLL)
DefineSegment (Fake, FAKE)
DefineSegment (TimeSignature, TIME_SIG)
float GetBPMAtRow (int iNoteRow) const
float GetBPMAtBeat (float fBeat) const
void SetBPMAtRow (int iNoteRow, float fBPM)
void SetBPMAtBeat (float fBeat, float fBPM)
float GetStopAtRow (int iNoteRow) const
float GetStopAtBeat (float fBeat) const
void SetStopAtRow (int iNoteRow, float fSeconds)
void SetStopAtBeat (float fBeat, float fSeconds)
float GetDelayAtRow (int iNoteRow) const
float GetDelayAtBeat (float fBeat) const
void SetDelayAtRow (int iNoteRow, float fSeconds)
void SetDelayAtBeat (float fBeat, float fSeconds)
void SetTimeSignatureAtRow (int iNoteRow, int iNum, int iDen)
void SetTimeSignatureAtBeat (float fBeat, int iNum, int iDen)
float GetWarpAtRow (int iNoteRow) const
float GetWarpAtBeat (float fBeat) const
void SetWarpAtRow (int iRow, float fLength)
void SetWarpAtBeat (float fBeat, float fLength)
int GetTickcountAtRow (int iNoteRow) const
int GetTickcountAtBeat (float fBeat) const
void SetTickcountAtRow (int iNoteRow, int iTicks)
void SetTickcountAtBeat (float fBeat, int iTicks)
int GetComboAtRow (int iNoteRow) const
int GetComboAtBeat (float fBeat) const
int GetMissComboAtRow (int iNoteRow) const
int GetMissComboAtBeat (float fBeat) const
const RString & GetLabelAtRow (int iNoteRow) const
const RString & GetLabelAtBeat (float fBeat) const
void SetLabelAtRow (int iNoteRow, const RString &sLabel)
void SetLabelAtBeat (float fBeat, const RString &sLabel)
bool DoesLabelExist (const RString &sLabel) const
float GetSpeedPercentAtRow (int iNoteRow) const
float GetSpeedPercentAtBeat (float fBeat) const
float GetSpeedWaitAtRow (int iNoteRow) const
float GetSpeedWaitAtBeat (float fBeat) const
SpeedSegment::BaseUnit GetSpeedModeAtRow (int iNoteRow) const
SpeedSegment::BaseUnit GetSpeedModeAtBeat (float fBeat)
void SetSpeedAtRow (int iNoteRow, float fPercent, float fWait, SpeedSegment::BaseUnit unit)
void SetSpeedAtBeat (float fBeat, float fPercent, float fWait, SpeedSegment::BaseUnit unit)
void SetSpeedPercentAtRow (int iNoteRow, float fPercent)
void SetSpeedWaitAtRow (int iNoteRow, float fWait)
void SetSpeedModeAtRow (int iNoteRow, SpeedSegment::BaseUnit unit)
void SetSpeedPercentAtBeat (float fBeat, float fPercent)
void SetSpeedWaitAtBeat (float fBeat, float fWait)
void SetSpeedModeAtBeat (float fBeat, SpeedSegment::BaseUnit unit)
float GetDisplayedSpeedPercent (float fBeat, float fMusicSeconds) const
float GetScrollAtRow (int iNoteRow) const
float GetScrollAtBeat (float fBeat)
void SetScrollAtRow (int iNoteRow, float fPercent)
void SetScrollAtBeat (float fBeat, float fPercent)
float GetFakeAtRow (int iRow) const
float GetFakeAtBeat (float fBeat) const
bool IsWarpAtRow (int iRow) const
bool IsWarpAtBeat (float fBeat) const
bool IsFakeAtRow (int iRow) const
bool IsFakeAtBeat (float fBeat) const
bool IsJudgableAtRow (int row) const
Determine if this notes on this row can be judged.
bool IsJudgableAtBeat (float beat) const
void MultiplyBPMInBeatRange (int iStartIndex, int iEndIndex, float fFactor)
void NoteRowToMeasureAndBeat (int iNoteRow, int &iMeasureIndexOut, int &iBeatIndexOut, int &iRowsRemainder) const
void GetBeatInternal (GetBeatStarts &start, GetBeatArgs &args, unsigned int max_segment) const
float GetElapsedTimeInternal (GetBeatStarts &start, float beat, unsigned int max_segment) const
void GetBeatAndBPSFromElapsedTime (GetBeatArgs &args) const
float GetBeatFromElapsedTime (float elapsed_time) const
float GetElapsedTimeFromBeat (float fBeat) const
void GetBeatAndBPSFromElapsedTimeNoOffset (GetBeatArgs &args) const
float GetBeatFromElapsedTimeNoOffset (float elapsed_time) const
float GetElapsedTimeFromBeatNoOffset (float fBeat) const
float GetDisplayedBeat (float fBeat) const
bool HasBpmChanges () const
bool HasStops () const
bool HasDelays () const
bool HasWarps () const
bool HasFakes () const
bool HasSpeedChanges () const
bool HasScrollChanges () const
bool operator== (const TimingData &other)
Compare two sets of timing data to see if they are equal.
bool operator!= (const TimingData &other)
Compare two sets of timing data to see if they are not equal.
void ScaleRegion (float fScale=1, int iStartRow=0, int iEndRow=MAX_NOTE_ROW, bool bAdjustBPM=false)
void InsertRows (int iStartRow, int iRowsToAdd)
void DeleteRows (int iStartRow, int iRowsToDelete)
void SortSegments (TimingSegmentType tst)
const vector< TimingSegment * > & GetTimingSegments (TimingSegmentType tst) const
vector< TimingSegment * > & GetTimingSegments (TimingSegmentType tst)
void TidyUpData (bool allowEmpty)
Tidy up the timing data, e.g. provide default BPMs, labels, tickcounts.
void PushSelf (lua_State *L)
vector< RString > ToVectorString (TimingSegmentType tst, int dec=6) const
const vector< float > & BuildAndGetEtaner (const vector< int > &nerv)
const vector< float > & BuildAndGetEtar (int lastrow)
void SetElapsedTimesAtAllRows (vector< float > &etar)
vector< float > GetElapsedTimesAtAllRows ()
void UnsetElapsedTimesAtAllRows ()
void UnsetEtaner ()
float WhereUAtBro (float beat) const
float WhereUAtBro (float beat)
float WhereUAtBroNoOffset (float beat) const
float WhereUAtBroNoOffset (float beat)
float WhereUAtBro (int row)
vector< float > ConvertReplayNoteRowsToTimestamps (vector< int > nrv, float rate)
void InvalidateSequentialAssmption ()
bool IsSequentialAssumptionValid ()
void NegStopAndBPMCheck ()
Public Attributes
beat_start_lookup_t m_beat_start_lookup
beat_start_lookup_t m_time_start_lookup
RString m_sFile
The file of the song/steps that use this TimingData.
float m_fBeat0OffsetInSeconds
The initial offset of a song.
vector< float > ElapsedTimesAtAllRows
vector< float > ElapsedTimesAtNonEmptyRows
bool ValidSequentialAssumption = true
Protected Member Functions
void AddSegment (const TimingSegment *seg)
Protected Attributes
vector< TimingSegment * > m_avpTimingSegments [NUM_TimingSegmentType]
Detailed Description
Holds data for translating beats<->seconds.
Member Typedef Documentation
beat_start_lookup_t
typedef vector<lookup_item_t> TimingData::beat_start_lookup_t
Constructor & Destructor Documentation
TimingData() [1/2]
TimingData::TimingData (float fOffset = 0)
Sets up initial timing data with a defined offset.
Parameters
fOffset the offset from the 0th beat.
~TimingData()
TimingData::~TimingData ()
References Clear().
TimingData() [2/2]
TimingData::TimingData (const TimingData & cpy) inline
References Copy().
Member Function Documentation
AddSegment()
void TimingData::AddSegment (const TimingSegment * seg) protected
References ASSERT, TimingSegment::Copy(), TimingSegment::DebugPrint(), EraseSegment(), TimingSegment::GetEffectType(), TimingSegment::GetRow(), GetSegmentIndexAtRow(), TimingSegment::GetType(), INVALID_INDEX, TimingSegment::IsNotable(), LOG, m_avpTimingSegments, SAFE_DELETE, SegmentEffectType_Indefinite, SegmentEffectType_Range, SegmentEffectType_Row, TimingSegment::SetRow(), TimingSegmentTypeToString(), and RageLog::Trace().
Referenced by AdjustSync::AutosyncTempo(), Copy(), CopyRange(), Deserialize(), HandleBunki(), DWILoader::LoadFromDir(), LoadFromKSFFile(), LoadGlobalData(), MusicPlaying::MusicPlaying(), SMALoader::ProcessBeatsPerMeasure(), SSCLoader::ProcessBPMs(), SMLoader::ProcessBPMsAndStops(), SSCLoader::ProcessCombos(), SMLoader::ProcessDelays(), SMLoader::ProcessFakes(), SSCLoader::ProcessLabels(), SMALoader::ProcessMultipliers(), SSCLoader::ProcessScrolls(), SMALoader::ProcessSpeeds(), SMLoader::ProcessSpeeds(), SSCLoader::ProcessStops(), SMLoader::ProcessTickcounts(), ProcessTickcounts(), SMLoader::ProcessTimeSignatures(), SSCLoader::ProcessWarps(), SetBPMAtRow(), SetDelayAtRow(), SetLabelAtRow(), SetScrollAtRow(), SetSpeedAtRow(), SetStopAtRow(), SetTickcountAtRow(), SetTimeSignatureAtRow(), OsuLoader::SetTimingData(), SetWarpAtBeat(), SetWarpAtRow(), and TidyUpData().
BuildAndGetEtaner()
const vector< float > & TimingData::BuildAndGetEtaner (const vector< int > & nerv)
References ElapsedTimesAtAllRows, ElapsedTimesAtNonEmptyRows, GetBPMAtRow(), GetElapsedTimeFromBeatNoOffset(), m_avpTimingSegments, m_fBeat0OffsetInSeconds, NoteRowToBeat(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, and SEGMENT_WARP.
Referenced by Steps::CalcEtternaMetadata(), DoInstalls(), Player::Load(), and ScoreManager::RecalculateSSRs().
BuildAndGetEtar()
const vector< float > & TimingData::BuildAndGetEtar (int lastrow)
References ElapsedTimesAtAllRows, GetBPMAtRow(), GetElapsedTimeFromBeatNoOffset(), LOG, m_avpTimingSegments, m_fBeat0OffsetInSeconds, NoteRowToBeat(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENT_WARP, RageLog::Trace(), and RageLog::Warn().
Referenced by Player::Load().
Clear()
void TimingData::Clear ()
References FOREACH_TimingSegmentType, m_avpTimingSegments, SAFE_DELETE, UnsetElapsedTimesAtAllRows(), and UnsetEtaner().
Referenced by Copy(), and ~TimingData().
ClearRange()
void TimingData::ClearRange (int start_row, int end_row, TimingSegmentType clear_type)
References EraseSegment(), FOREACH_TimingSegmentType, GetSegmentIndexAtRow(), GetTimingSegments(), INVALID_INDEX, and TimingSegmentType_Invalid.
ConvertReplayNoteRowsToTimestamps()
vector< float > TimingData::ConvertReplayNoteRowsToTimestamps (vector< int > nrv, float rate)
References WhereUAtBro().
Copy()
void TimingData::Copy (const TimingData & other)
References AddSegment(), Clear(), FOREACH_TimingSegmentType, m_avpTimingSegments, m_fBeat0OffsetInSeconds, and m_sFile.
Referenced by operator=(), and TimingData().
CopyRange()
void TimingData::CopyRange (int start_row, int end_row, TimingSegmentType copy_type, int dest_row, TimingData & dest) const
References AddSegment(), TimingSegment::Copy(), FOREACH_TimingSegmentType, GetTimingSegments(), TimingSegment::SetRow(), and TimingSegmentType_Invalid.
DefineSegment() [1/11]
TimingData::DefineSegment (BPM , BPM)
DefineSegment() [2/11]
TimingData::DefineSegment (Stop , STOP)
DefineSegment() [3/11]
TimingData::DefineSegment (Delay , DELAY)
DefineSegment() [4/11]
TimingData::DefineSegment (Warp , WARP)
DefineSegment() [5/11]
TimingData::DefineSegment (Label , LABEL)
DefineSegment() [6/11]
TimingData::DefineSegment (Tickcount , TICKCOUNT)
DefineSegment() [7/11]
TimingData::DefineSegment (Combo , COMBO)
DefineSegment() [8/11]
TimingData::DefineSegment (Speed , SPEED)
DefineSegment() [9/11]
TimingData::DefineSegment (Scroll , SCROLL)
DefineSegment() [10/11]
TimingData::DefineSegment (Fake , FAKE)
DefineSegment() [11/11]
TimingData::DefineSegment (TimeSignature , TIME_SIG)
DeleteRows()
void TimingData::DeleteRows (int iStartRow, int iRowsToDelete)
References FOREACH_TimingSegmentType, TimingSegment::GetEffectType(), TimingSegment::GetRow(), GetSegmentAtRow(), LOG, m_avpTimingSegments, SegmentEffectType_Indefinite, TimingSegment::SetRow(), and RageLog::Trace().
DoesLabelExist()
bool TimingData::DoesLabelExist (const RString & sLabel) const
References GetTimingSegments(), and SEGMENT_LABEL.
DumpLookupTables()
void TimingData::DumpLookupTables ()
References DumpOneTable(), LOG, m_beat_start_lookup, m_sFile, m_time_start_lookup, and RageLog::Trace().
DumpOneTable()
void TimingData::DumpOneTable (const beat_start_lookup_t & lookup, const RString & name)
References TimingData::GetBeatStarts::bpm, TimingData::GetBeatStarts::delay, TimingData::lookup_item_t::first, TimingData::GetBeatStarts::is_warping, TimingData::GetBeatStarts::last_row, TimingData::GetBeatStarts::last_time, LOG, m_avpTimingSegments, TimingData::lookup_item_t::second, SegInfoStr(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENT_WARP, ssprintf(), TimingData::GetBeatStarts::stop, RageLog::Trace(), TimingData::GetBeatStarts::warp, and TimingData::GetBeatStarts::warp_destination.
Referenced by DumpLookupTables().
empty()
bool TimingData::empty () const
References FOREACH_TimingSegmentType, and GetTimingSegments().
Referenced by GetETTNoteData(), GetSSCNoteData(), Steps::GetTimingData(), ScreenSyncOverlay::Input(), SongCacheIndex::InsertSteps(), IsSafeFullTiming(), Song::IsStepsUsingDifferentTiming(), and TidyUpData().
GetActualBPM()
void TimingData::GetActualBPM (float & fMinBPMOut, float & fMaxBPMOut, float highest = FLT_MAX) const
Gets the actual BPM of the song, while respecting a limit.
The high limit is due to the implementation of mMods.
Parameters
fMinBPMOut the minimium specified BPM.
fMaxBPMOut the maximum specified BPM.
highest the highest allowed max BPM.
References clamp, GetTimingSegments(), max(), min(), and SEGMENT_BPM.
Referenced by LunaTimingData::GetActualBPM(), Steps::GetDisplayBpms(), Song::GetDisplayBpms(), Player::Init(), and BPMDisplay::SetBpmFromSteps().
GetBeatAndBPSFromElapsedTime()
void TimingData::GetBeatAndBPSFromElapsedTime (GetBeatArgs & args) const
References TimingData::GetBeatArgs::elapsed_time, GAMESTATE, GetBeatAndBPSFromElapsedTimeNoOffset(), ModsGroup< T >::GetCurrent(), PrefsManager::m_fGlobalOffsetSeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, and PREFSMAN.
Referenced by GetBeatFromElapsedTime(), BackgroundImpl::Layer::UpdateCurBGChange(), SongPosition::UpdateSongPosition(), and Player::UpdateTapNotesMissedOlderThan().
GetBeatAndBPSFromElapsedTimeNoOffset()
void TimingData::GetBeatAndBPSFromElapsedTimeNoOffset (GetBeatArgs & args) const
References TimingData::GetBeatArgs::elapsed_time, FindEntryInLookup(), GetBeatInternal(), TimingData::GetBeatStarts::last_time, m_beat_start_lookup, and m_fBeat0OffsetInSeconds.
Referenced by GetBeatAndBPSFromElapsedTime(), and GetBeatFromElapsedTimeNoOffset().
GetBeatFromElapsedTime()
float TimingData::GetBeatFromElapsedTime (float elapsed_time) const inline
References TimingData::GetBeatArgs::beat, TimingData::GetBeatArgs::elapsed_time, and GetBeatAndBPSFromElapsedTime().
Referenced by LunaTimingData::GetBeatFromElapsedTime(), Song::GetFirstBeat(), Song::GetLastBeat(), Song::GetSpecifiedLastBeat(), ScreenSyncOverlay::Input(), ScreenGameplay::SendCrossedMessages(), Player::Step(), Song::TidyUpData(), Foreground::Update(), and Player::UpdateJudgedRows().
GetBeatFromElapsedTimeNoOffset()
float TimingData::GetBeatFromElapsedTimeNoOffset (float elapsed_time) const inline
References TimingData::GetBeatArgs::beat, TimingData::GetBeatArgs::elapsed_time, and GetBeatAndBPSFromElapsedTimeNoOffset().
Referenced by OsuLoader::MsToNoteRow(), GameplayAssist::PlayTicks(), StartMusic(), and SongPosition::UpdateSongPosition().
GetBeatInternal()
void TimingData::GetBeatInternal (GetBeatStarts & start, GetBeatArgs & args, unsigned int max_segment) const
References TimingData::GetBeatArgs::beat, TimingData::GetBeatStarts::bpm, TimingData::GetBeatArgs::bps_out, TimingData::GetBeatStarts::delay, TimingData::GetBeatArgs::delay_out, TimingData::GetBeatArgs::elapsed_time, FindEvent(), FOUND_BPM_CHANGE, FOUND_DELAY, FOUND_STOP, FOUND_STOP_DELAY, FOUND_WARP, FOUND_WARP_DESTINATION, TimingData::GetBeatArgs::freeze_out, TimingSegment::GetBeat(), GetBPMAtRow(), WarpSegment::GetLength(), StopSegment::GetPause(), DelaySegment::GetPause(), INC_INDEX, TimingData::GetBeatStarts::is_warping, TimingData::GetBeatStarts::last_row, TimingData::GetBeatStarts::last_time, m_avpTimingSegments, NOT_FOUND, NoteRowToBeat(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENT_WARP, TimingData::GetBeatStarts::stop, TimingData::GetBeatStarts::warp, TimingData::GetBeatArgs::warp_begin_out, TimingData::GetBeatArgs::warp_dest_out, and TimingData::GetBeatStarts::warp_destination.
Referenced by GetBeatAndBPSFromElapsedTimeNoOffset(), and PrepareLookup().
GetBPMAtBeat()
float TimingData::GetBPMAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetBPMAtRow().
Referenced by LunaTimingData::GetBPMAtBeat(), and LoadFromKSFFile().
GetBPMAtRow()
float TimingData::GetBPMAtRow (int iNoteRow) const inline
Referenced by BuildAndGetEtaner(), BuildAndGetEtar(), Steps::FillStringWithBPMs(), GetBeatInternal(), GetBPMAtBeat(), GetElapsedTimeInternal(), ScaleRegion(), and WriteGlobalTags().
GetComboAtBeat()
int TimingData::GetComboAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetComboAtRow().
GetComboAtRow()
int TimingData::GetComboAtRow (int iNoteRow) const inline
Referenced by GetComboAtBeat().
GetDelayAtBeat()
float TimingData::GetDelayAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetDelayAtRow().
Referenced by GetDisplayedSpeedPercent().
GetDelayAtRow()
float TimingData::GetDelayAtRow (int iNoteRow) const inline
Referenced by GetDelayAtBeat(), IsWarpAtRow(), and LoadFromKSFFile().
GetDisplayedBeat()
float TimingData::GetDisplayedBeat (float fBeat) const
References m_avpTimingSegments, and SEGMENT_SCROLL.
GetDisplayedSpeedPercent()
float TimingData::GetDisplayedSpeedPercent (float fBeat, float fMusicSeconds) const
References DEBUG_ASSERT, TimingSegment::GetBeat(), SpeedSegment::GetDelay(), GetDelayAtBeat(), SpeedSegment::GetRatio(), GetSegmentIndexAtBeat(), GetTimingSegments(), SpeedSegment::GetUnit(), LOG, SEGMENT_SPEED, RageLog::Trace(), SpeedSegment::UNIT_SECONDS, and WhereUAtBro().
Referenced by FindDisplayedBeats(), and ArrowEffects::GetYOffset().
GetElapsedTimeFromBeat()
float TimingData::GetElapsedTimeFromBeat (float fBeat) const
References GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeatNoOffset(), PrefsManager::m_fGlobalOffsetSeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, and PREFSMAN.
Referenced by MusicWheel::FilterBySkillsets(), ScreenSyncOverlay::Input(), and WhereUAtBro().
GetElapsedTimeFromBeatNoOffset()
float TimingData::GetElapsedTimeFromBeatNoOffset (float fBeat) const
References FindEntryInLookup(), GetElapsedTimeInternal(), TimingData::GetBeatStarts::last_time, m_fBeat0OffsetInSeconds, and m_time_start_lookup.
Referenced by BuildAndGetEtaner(), BuildAndGetEtar(), GetElapsedTimeFromBeat(), StartMusic(), and WhereUAtBroNoOffset().
GetElapsedTimeInternal()
float TimingData::GetElapsedTimeInternal (GetBeatStarts & start, float beat, unsigned int max_segment) const
References TimingData::GetBeatStarts::bpm, TimingData::GetBeatStarts::delay, FindEvent(), FOUND_BPM_CHANGE, FOUND_DELAY, FOUND_MARKER, FOUND_STOP, FOUND_STOP_DELAY, FOUND_WARP, FOUND_WARP_DESTINATION, TimingSegment::GetBeat(), GetBPMAtRow(), WarpSegment::GetLength(), INC_INDEX, TimingData::GetBeatStarts::is_warping, TimingData::GetBeatStarts::last_row, TimingData::GetBeatStarts::last_time, m_avpTimingSegments, NOT_FOUND, NoteRowToBeat(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, SEGMENT_WARP, TimingData::GetBeatStarts::stop, TimingData::GetBeatStarts::warp, and TimingData::GetBeatStarts::warp_destination.
Referenced by GetElapsedTimeFromBeatNoOffset().
GetElapsedTimesAtAllRows()
vector<float> TimingData::GetElapsedTimesAtAllRows () inline
References ElapsedTimesAtAllRows.
GetFakeAtBeat()
float TimingData::GetFakeAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetFakeAtRow().
GetFakeAtRow()
float TimingData::GetFakeAtRow (int iRow) const inline
Referenced by GetFakeAtBeat().
GetLabelAtBeat()
const RString& TimingData::GetLabelAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetLabelAtRow().
GetLabelAtRow()
const RString& TimingData::GetLabelAtRow (int iNoteRow) const inline
Referenced by GetLabelAtBeat().
GetMissComboAtBeat()
int TimingData::GetMissComboAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetMissComboAtRow().
GetMissComboAtRow()
int TimingData::GetMissComboAtRow (int iNoteRow) const inline
Referenced by GetMissComboAtBeat().
GetNextSegmentBeatAtBeat()
float TimingData::GetNextSegmentBeatAtBeat (TimingSegmentType tst, float beat) const inline
References BeatToNoteRow(), and GetNextSegmentBeatAtRow().
GetNextSegmentBeatAtRow()
float TimingData::GetNextSegmentBeatAtRow (TimingSegmentType tst, int row) const
References GetTimingSegments(), and NoteRowToBeat().
Referenced by GetNextSegmentBeatAtBeat().
GetPreviousSegmentBeatAtBeat()
float TimingData::GetPreviousSegmentBeatAtBeat (TimingSegmentType tst, float beat) const inline
References BeatToNoteRow(), and GetPreviousSegmentBeatAtRow().
GetPreviousSegmentBeatAtRow()
float TimingData::GetPreviousSegmentBeatAtRow (TimingSegmentType tst, int row) const
References GetTimingSegments(), and NoteRowToBeat().
Referenced by GetPreviousSegmentBeatAtBeat().
GetScrollAtBeat()
float TimingData::GetScrollAtBeat (float fBeat) inline
References BeatToNoteRow(), and GetScrollAtRow().
GetScrollAtRow()
float TimingData::GetScrollAtRow (int iNoteRow) const inline
Referenced by GetScrollAtBeat().
GetSegmentAtBeat() [1/2]
const TimingSegment* TimingData::GetSegmentAtBeat (float fBeat, TimingSegmentType tst) const inline
Retrieve the TimingSegment at the given beat.
Parameters
fBeat the beat that has a TimingSegment.
tst the TimingSegmentType requested.
Returns
the segment in question.
References BeatToNoteRow(), and GetSegmentAtRow().
Referenced by GetSegmentAtBeat().
GetSegmentAtBeat() [2/2]
TimingSegment* TimingData::GetSegmentAtBeat (float fBeat, TimingSegmentType tst) inline
References GetSegmentAtBeat().
GetSegmentAtRow() [1/2]
const TimingSegment * TimingData::GetSegmentAtRow (int iNoteRow, TimingSegmentType tst) const
Retrieve the TimingSegment at the specified row.
Parameters
iNoteRow the row that has a TimingSegment.
tst the TimingSegmentType requested.
Returns
the segment in question.
References FAIL_M, TimingSegment::GetEffectType(), TimingSegment::GetRow(), GetSegmentIndexAtRow(), GetTimingSegments(), and SegmentEffectType_Indefinite.
Referenced by DeleteRows(), GetSegmentAtBeat(), and GetSegmentAtRow().
GetSegmentAtRow() [2/2]
TimingSegment * TimingData::GetSegmentAtRow (int iNoteRow, TimingSegmentType tst)
References GetSegmentAtRow().
GetSegmentIndexAtBeat()
int TimingData::GetSegmentIndexAtBeat (TimingSegmentType tst, float beat) const inline
References BeatToNoteRow(), and GetSegmentIndexAtRow().
Referenced by GetDisplayedSpeedPercent().
GetSegmentIndexAtRow()
int TimingData::GetSegmentIndexAtRow (TimingSegmentType tst, int row) const
References GetTimingSegments(), INVALID_INDEX, max(), and min().
Referenced by AddSegment(), ClearRange(), GetSegmentAtRow(), GetSegmentIndexAtBeat(), IsFakeAtRow(), IsWarpAtRow(), and ShiftRange().
GetSpeedModeAtBeat()
SpeedSegment::BaseUnit TimingData::GetSpeedModeAtBeat (float fBeat) inline
References BeatToNoteRow(), and GetSpeedModeAtRow().
GetSpeedModeAtRow()
SpeedSegment::BaseUnit TimingData::GetSpeedModeAtRow (int iNoteRow) const inline
Referenced by GetSpeedModeAtBeat().
GetSpeedPercentAtBeat()
float TimingData::GetSpeedPercentAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetSpeedPercentAtRow().
GetSpeedPercentAtRow()
float TimingData::GetSpeedPercentAtRow (int iNoteRow) const inline
Referenced by GetSpeedPercentAtBeat().
GetSpeedWaitAtBeat()
float TimingData::GetSpeedWaitAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetSpeedWaitAtRow().
GetSpeedWaitAtRow()
float TimingData::GetSpeedWaitAtRow (int iNoteRow) const inline
Referenced by GetSpeedWaitAtBeat().
GetStopAtBeat()
float TimingData::GetStopAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetStopAtRow().
GetStopAtRow()
float TimingData::GetStopAtRow (int iNoteRow) const inline
Referenced by GetStopAtBeat(), IsWarpAtRow(), and LoadFromKSFFile().
GetTickcountAtBeat()
int TimingData::GetTickcountAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetTickcountAtRow().
GetTickcountAtRow()
int TimingData::GetTickcountAtRow (int iNoteRow) const inline
Referenced by Player::CrossedRows(), and GetTickcountAtBeat().
GetTimingSegments() [1/2]
const vector<TimingSegment*>& TimingData::GetTimingSegments (TimingSegmentType tst) const inline
Referenced by AdjustSync::AutosyncTempo(), ClearRange(), CopyRange(), DoesLabelExist(), NoteField::DrawPrimitives(), empty(), GenerateCacheDataStructure(), GetActualBPM(), LunaTimingData::GetBPMs(), GetDisplayedSpeedPercent(), GetNextSegmentBeatAtRow(), GetPreviousSegmentBeatAtRow(), GetSegmentAtRow(), GetSegmentIndexAtRow(), AdjustSync::GetSyncChangeTextSong(), NoteDataUtil::GetTotalHoldTicks(), HasBpmChanges(), HasDelays(), HasFakes(), HasScrollChanges(), HasSpeedChanges(), HasStops(), HasWarps(), SongCacheIndex::InsertStepsTimingData(), IsFakeAtRow(), IsWarpAtRow(), BackgroundImpl::LoadFromRandom(), NoteRowToMeasureAndBeat(), Serialize(), ShiftRange(), TimingSegmentSetToLuaTable(), ToVectorString(), NotesWriterDWI::Write(), and WriteGlobalTags().
GetTimingSegments() [2/2]
vector<TimingSegment*>& TimingData::GetTimingSegments (TimingSegmentType tst) inline
References m_avpTimingSegments.
GetWarpAtBeat()
float TimingData::GetWarpAtBeat (float fBeat) const inline
References BeatToNoteRow(), and GetWarpAtRow().
GetWarpAtRow()
float TimingData::GetWarpAtRow (int iNoteRow) const inline
Referenced by GetWarpAtBeat().
HasBpmChanges()
bool TimingData::HasBpmChanges () const inline
References GetTimingSegments(), and SEGMENT_BPM.
Referenced by LunaTimingData::HasBPMChanges(), Song::HasSignificantBpmChangesOrStops(), and Steps::HasSignificantTimingChanges().
HasDelays()
bool TimingData::HasDelays () const inline
References GetTimingSegments(), and SEGMENT_DELAY.
Referenced by LunaTimingData::HasDelays(), Song::HasSignificantBpmChangesOrStops(), and Steps::HasSignificantTimingChanges().
HasFakes()
bool TimingData::HasFakes () const inline
References GetTimingSegments(), and SEGMENT_FAKE.
Referenced by LunaTimingData::HasFakes().
HasScrollChanges()
bool TimingData::HasScrollChanges () const
References GetTimingSegments(), and SEGMENT_SCROLL.
Referenced by LunaTimingData::HasScrollChanges(), and Steps::HasSignificantTimingChanges().
HasSpeedChanges()
bool TimingData::HasSpeedChanges () const
References GetTimingSegments(), and SEGMENT_SPEED.
Referenced by Steps::HasSignificantTimingChanges(), and LunaTimingData::HasSpeedChanges().
HasStops()
bool TimingData::HasStops () const inline
References GetTimingSegments(), and SEGMENT_STOP.
Referenced by Song::HasSignificantBpmChangesOrStops(), Steps::HasSignificantTimingChanges(), and LunaTimingData::HasStops().
HasWarps()
bool TimingData::HasWarps () const inline
References GetTimingSegments(), and SEGMENT_WARP.
Referenced by Steps::CalcEtternaMetadata(), PlayerStageStats::CalcSSR(), LunaTimingData::HasNegativeBPMs(), Steps::HasSignificantTimingChanges(), LunaTimingData::HasWarps(), Steps::IsRecalcValid(), Player::Load(), NegStopAndBPMCheck(), ScoreManager::RecalculateSSRs(), and ETTProtocol::ReportHighScore().
InsertRows()
void TimingData::InsertRows (int iStartRow, int iRowsToAdd)
References ASSERT_M, FOREACH_TimingSegmentType, TimingSegment::GetRow(), m_avpTimingSegments, SEGMENT_BPM, and TimingSegment::SetRow().
InvalidateSequentialAssmption()
void TimingData::InvalidateSequentialAssmption () inline
Referenced by Foreground::LoadFromSong().
IsFakeAtBeat()
bool TimingData::IsFakeAtBeat (float fBeat) const inline
References BeatToNoteRow(), and IsFakeAtRow().
IsFakeAtRow()
bool TimingData::IsFakeAtRow (int iRow) const
References TimingSegment::GetBeat(), FakeSegment::GetLength(), GetSegmentIndexAtRow(), GetTimingSegments(), NoteRowToBeat(), and SEGMENT_FAKE.
Referenced by IsFakeAtBeat(), and IsJudgableAtRow().
IsJudgableAtBeat()
bool TimingData::IsJudgableAtBeat (float beat) const inline
References BeatToNoteRow(), and IsJudgableAtRow().
IsJudgableAtRow()
bool TimingData::IsJudgableAtRow (int row) const inline
Determine if this notes on this row can be judged.
Parameters
row the row to focus on.
Returns
true if the row can be judged, false otherwise.
References IsFakeAtRow(), and IsWarpAtRow().
Referenced by NoteDataUtil::CalculateRadarValues(), NoteDataWithScoring::GetActualRadarValues(), Player::GetClosestNonEmptyRowDirectional(), Player::GetClosestNoteDirectional(), NoteData::GetNumHoldNotes(), NoteData::GetNumHoldNotesTwoPlayer(), NoteData::GetNumRolls(), NoteData::GetNumRollsTwoPlayer(), NoteData::GetNumRowsWithSimultaneousPresses(), NoteData::GetNumRowsWithSimultaneousTaps(), NoteData::GetNumRowsWithTap(), NoteData::GetNumRowsWithTapOrHoldHead(), Player::HandleHoldCheckpoint(), NoteData::IsFake(), IsJudgableAtBeat(), NoteData::IsLift(), NoteData::IsMine(), NoteData::IsTap(), GameplayAssist::PlayTicks(), NoteDataUtil::RemoveFakes(), Player::Step(), Player::UpdateJudgedRows(), Player::UpdateTapNotesMissedOlderThan(), and NoteData::WifeTotalScoreCalc().
IsSafeFullTiming()
bool TimingData::IsSafeFullTiming ()
References empty(), m_avpTimingSegments, SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_TICKCOUNT, and SEGMENT_TIME_SIG.
IsSequentialAssumptionValid()
bool TimingData::IsSequentialAssumptionValid () inline
References ValidSequentialAssumption.
IsWarpAtBeat()
bool TimingData::IsWarpAtBeat (float fBeat) const inline
References BeatToNoteRow(), and IsWarpAtRow().
IsWarpAtRow()
bool TimingData::IsWarpAtRow (int iRow) const
References TimingSegment::GetBeat(), GetDelayAtRow(), WarpSegment::GetLength(), GetSegmentIndexAtRow(), GetStopAtRow(), GetTimingSegments(), NoteRowToBeat(), SEGMENT_DELAY, SEGMENT_STOP, and SEGMENT_WARP.
Referenced by IsJudgableAtRow(), and IsWarpAtBeat().
MultiplyBPMInBeatRange()
void TimingData::MultiplyBPMInBeatRange (int iStartIndex, int iEndIndex, float fFactor)
References BPMSegment::GetBPM(), BPMSegment::GetBPS(), TimingSegment::GetRow(), m_avpTimingSegments, SEGMENT_BPM, and BPMSegment::SetBPM().
NegStopAndBPMCheck()
void TimingData::NegStopAndBPMCheck () inline
References BPMSegment::GetBPM(), StopSegment::GetPause(), HasWarps(), LOG, m_avpTimingSegments, SEGMENT_BPM, SEGMENT_STOP, ValidSequentialAssumption, and RageLog::Warn().
Referenced by Player::Load().
NoteRowToMeasureAndBeat()
void TimingData::NoteRowToMeasureAndBeat (int iNoteRow, int & iMeasureIndexOut, int & iBeatIndexOut, int & iRowsRemainder) const
References FAIL_M, TimeSignatureSegment::GetNoteRowsPerMeasure(), TimingSegment::GetRow(), GetTimingSegments(), and SEGMENT_TIME_SIG.
Referenced by GameplayAssist::PlayTicks().
operator!=()
bool TimingData::operator!= (const TimingData & other) inline
Compare two sets of timing data to see if they are not equal.
Parameters
other the other TimingData.
Returns
the inequality or lack thereof of the two TimingData.
References operator==().
operator=()
TimingData& TimingData::operator= (const TimingData & cpy) inline
References Copy().
operator==()
bool TimingData::operator== (const TimingData & other) inline
Compare two sets of timing data to see if they are equal.
Parameters
other the other TimingData.
Returns
the equality or lack thereof of the two TimingData.
References COMPARE, FOREACH_ENUM, m_avpTimingSegments, and m_fBeat0OffsetInSeconds.
Referenced by operator!=().
PrepareLookup()
void TimingData::PrepareLookup ()
References TimingData::GetBeatArgs::elapsed_time, GetBeatInternal(), TimingData::GetBeatStarts::last_row, TimingData::GetBeatStarts::last_time, m_avpTimingSegments, m_beat_start_lookup, m_fBeat0OffsetInSeconds, m_time_start_lookup, NoteRowToBeat(), ReleaseLookup(), SEGMENT_BPM, SEGMENT_DELAY, SEGMENT_STOP, and SEGMENT_WARP.
PushSelf()
void TimingData::PushSelf (lua_State * L)
Referenced by LunaPlayer::GetPlayerTimingData(), LunaSteps::GetTimingData(), and LunaSong::GetTimingData().
ReleaseLookup()
void TimingData::ReleaseLookup ()
References CLEAR_LOOKUP, m_beat_start_lookup, and m_time_start_lookup.
Referenced by PrepareLookup().
ScaleRegion()
void TimingData::ScaleRegion (float fScale = 1, int iStartRow = 0, int iEndRow = MAX_NOTE_ROW, bool bAdjustBPM = false)
References ASSERT, FOREACH_TimingSegmentType, BPMSegment::GetBPM(), GetBPMAtRow(), TimingSegment::GetRow(), m_avpTimingSegments, NoteDataUtil::Scale(), SEGMENT_BPM, BPMSegment::SetBPM(), and SetBPMAtRow().
SetBPMAtBeat()
void TimingData::SetBPMAtBeat (float fBeat, float fBPM) inline
References BeatToNoteRow(), and SetBPMAtRow().
Referenced by LoadFromKSFFile().
SetBPMAtRow()
void TimingData::SetBPMAtRow (int iNoteRow, float fBPM) inline
References AddSegment().
Referenced by BMSChartReader::ReadNoteData(), ScaleRegion(), and SetBPMAtBeat().
SetDelayAtBeat()
void TimingData::SetDelayAtBeat (float fBeat, float fSeconds) inline
References BeatToNoteRow(), and SetDelayAtRow().
Referenced by LoadFromKSFFile().
SetDelayAtRow()
void TimingData::SetDelayAtRow (int iNoteRow, float fSeconds) inline
References AddSegment().
Referenced by SetDelayAtBeat().
SetElapsedTimesAtAllRows()
void TimingData::SetElapsedTimesAtAllRows (vector< float > & etar) inline
SetLabelAtBeat()
void TimingData::SetLabelAtBeat (float fBeat, const RString & sLabel) inline
References BeatToNoteRow(), and SetLabelAtRow().
SetLabelAtRow()
void TimingData::SetLabelAtRow (int iNoteRow, const RString & sLabel) inline
References AddSegment().
Referenced by SetLabelAtBeat().
SetScrollAtBeat()
void TimingData::SetScrollAtBeat (float fBeat, float fPercent) inline
References BeatToNoteRow(), and SetScrollAtRow().
SetScrollAtRow()
void TimingData::SetScrollAtRow (int iNoteRow, float fPercent) inline
References AddSegment().
Referenced by SetScrollAtBeat().
SetSpeedAtBeat()
void TimingData::SetSpeedAtBeat (float fBeat, float fPercent, float fWait, SpeedSegment::BaseUnit unit) inline
References BeatToNoteRow(), and SetSpeedAtRow().
SetSpeedAtRow()
void TimingData::SetSpeedAtRow (int iNoteRow, float fPercent, float fWait, SpeedSegment::BaseUnit unit) inline
References AddSegment().
Referenced by SetSpeedAtBeat(), SetSpeedModeAtRow(), SetSpeedPercentAtRow(), and SetSpeedWaitAtRow().
SetSpeedModeAtBeat()
void TimingData::SetSpeedModeAtBeat (float fBeat, SpeedSegment::BaseUnit unit) inline
References BeatToNoteRow(), and SetSpeedModeAtRow().
SetSpeedModeAtRow()
void TimingData::SetSpeedModeAtRow (int iNoteRow, SpeedSegment::BaseUnit unit) inline
References SpeedSegment::GetDelay(), SpeedSegment::GetRatio(), and SetSpeedAtRow().
Referenced by SetSpeedModeAtBeat().
SetSpeedPercentAtBeat()
void TimingData::SetSpeedPercentAtBeat (float fBeat, float fPercent) inline
References BeatToNoteRow(), and SetSpeedPercentAtRow().
SetSpeedPercentAtRow()
void TimingData::SetSpeedPercentAtRow (int iNoteRow, float fPercent) inline
References SpeedSegment::GetDelay(), SpeedSegment::GetUnit(), and SetSpeedAtRow().
Referenced by SetSpeedPercentAtBeat().
SetSpeedWaitAtBeat()
void TimingData::SetSpeedWaitAtBeat (float fBeat, float fWait) inline
References BeatToNoteRow(), and SetSpeedWaitAtRow().
SetSpeedWaitAtRow()
void TimingData::SetSpeedWaitAtRow (int iNoteRow, float fWait) inline
References SpeedSegment::GetRatio(), SpeedSegment::GetUnit(), and SetSpeedAtRow().
Referenced by SetSpeedWaitAtBeat().
SetStopAtBeat()
void TimingData::SetStopAtBeat (float fBeat, float fSeconds) inline
References BeatToNoteRow(), and SetStopAtRow().
SetStopAtRow()
void TimingData::SetStopAtRow (int iNoteRow, float fSeconds) inline
References AddSegment().
Referenced by BMSChartReader::ReadNoteData(), and SetStopAtBeat().
SetTickcountAtBeat()
void TimingData::SetTickcountAtBeat (float fBeat, int iTicks) inline
References BeatToNoteRow(), and SetTickcountAtRow().
Referenced by LoadFromKSFFile().
SetTickcountAtRow()
void TimingData::SetTickcountAtRow (int iNoteRow, int iTicks) inline
References AddSegment().
Referenced by SetTickcountAtBeat().
SetTimeSignatureAtBeat()
void TimingData::SetTimeSignatureAtBeat (float fBeat, int iNum, int iDen) inline
References BeatToNoteRow(), and SetTimeSignatureAtRow().
SetTimeSignatureAtRow()
void TimingData::SetTimeSignatureAtRow (int iNoteRow, int iNum, int iDen) inline
References AddSegment().
Referenced by BMSChartReader::ReadNoteData(), and SetTimeSignatureAtBeat().
SetWarpAtBeat()
void TimingData::SetWarpAtBeat (float fBeat, float fLength) inline
References AddSegment(), and BeatToNoteRow().
SetWarpAtRow()
void TimingData::SetWarpAtRow (int iRow, float fLength) inline
References AddSegment().
ShiftRange()
void TimingData::ShiftRange (int start_row, int end_row, TimingSegmentType shift_type, int shift_amount)
References ERASE_SEG, FOREACH_TimingSegmentType, GetSegmentIndexAtRow(), GetTimingSegments(), INVALID_INDEX, max(), min(), and TimingSegmentType_Invalid.
SortSegments()
void TimingData::SortSegments (TimingSegmentType tst)
References m_avpTimingSegments.
TidyUpData()
void TimingData::TidyUpData (bool allowEmpty)
Tidy up the timing data, e.g. provide default BPMs, labels, tickcounts.
Parameters
allowEmpty true if completely empty TimingData should be left alone, false if it should be changed
References AddSegment(), empty(), LOG, m_avpTimingSegments, m_sFile, SEGMENT_BPM, SEGMENT_COMBO, SEGMENT_LABEL, SEGMENT_SCROLL, SEGMENT_SPEED, SEGMENT_TICKCOUNT, SEGMENT_TIME_SIG, and RageLog::UserLog().
Referenced by ScreenHowToPlay::Init(), BMSChartReader::ReadNoteData(), and Song::TidyUpData().
ToVectorString()
vector< RString > TimingData::ToVectorString (TimingSegmentType tst, int dec = 6) const
References GetTimingSegments(), and StringConversion::ToString().
Referenced by SongCacheIndex::CacheSong(), and WriteTimingTags().
UnsetElapsedTimesAtAllRows()
void TimingData::UnsetElapsedTimesAtAllRows () inline
Referenced by Clear().
UnsetEtaner()
void TimingData::UnsetEtaner () inline
Referenced by Steps::CalcEtternaMetadata(), Clear(), DoInstalls(), and ScoreManager::RecalculateSSRs().
WhereUAtBro() [1/3]
float TimingData::WhereUAtBro (float beat) const
References AutosyncType_Off, BeatToNoteRow(), ElapsedTimesAtAllRows, GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeat(), SongOptions::m_AutosyncType, PrefsManager::m_fGlobalOffsetSeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, PREFSMAN, and ValidSequentialAssumption.
Referenced by ConvertReplayNoteRowsToTimestamps(), Player::GetClosestNonEmptyRow(), Player::GetClosestNote(), GetDisplayedSpeedPercent(), LunaTimingData::GetElapsedTimeFromBeat(), LunaTimingData::GetElapsedTimeFromNoteRow(), GameState::GetSongPercent(), ArrowEffects::GetYOffset(), Player::Step(), Song::TidyUpData(), Foreground::Update(), and BackgroundImpl::Layer::UpdateCurBGChange().
WhereUAtBro() [2/3]
float TimingData::WhereUAtBro (float beat)
References AutosyncType_Off, BeatToNoteRow(), ElapsedTimesAtAllRows, GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeat(), SongOptions::m_AutosyncType, PrefsManager::m_fGlobalOffsetSeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, PREFSMAN, and ValidSequentialAssumption.
WhereUAtBro() [3/3]
float TimingData::WhereUAtBro (int row)
References AutosyncType_Off, ElapsedTimesAtAllRows, GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeat(), SongOptions::m_AutosyncType, PrefsManager::m_fGlobalOffsetSeconds, SongOptions::m_fMusicRate, GameState::m_SongOptions, NoteRowToBeat(), PREFSMAN, and ValidSequentialAssumption.
WhereUAtBroNoOffset() [1/2]
float TimingData::WhereUAtBroNoOffset (float beat) const
References AutosyncType_Off, BeatToNoteRow(), ElapsedTimesAtAllRows, GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeatNoOffset(), SongOptions::m_AutosyncType, GameState::m_SongOptions, and ValidSequentialAssumption.
Referenced by GameplayAssist::PlayTicks(), and StartMusic().
WhereUAtBroNoOffset() [2/2]
float TimingData::WhereUAtBroNoOffset (float beat)
References AutosyncType_Off, BeatToNoteRow(), ElapsedTimesAtAllRows, GAMESTATE, ModsGroup< T >::GetCurrent(), GetElapsedTimeFromBeatNoOffset(), SongOptions::m_AutosyncType, GameState::m_SongOptions, and ValidSequentialAssumption.
Member Data Documentation
ElapsedTimesAtAllRows
vector<float> TimingData::ElapsedTimesAtAllRows
Referenced by BuildAndGetEtaner(), BuildAndGetEtar(), GetElapsedTimesAtAllRows(), WhereUAtBro(), and WhereUAtBroNoOffset().
ElapsedTimesAtNonEmptyRows
vector<float> TimingData::ElapsedTimesAtNonEmptyRows
Referenced by BuildAndGetEtaner().
m_avpTimingSegments
vector<TimingSegment*> TimingData::m_avpTimingSegments[NUM_TimingSegmentType] protected
Referenced by AddSegment(), BuildAndGetEtaner(), BuildAndGetEtar(), Clear(), Copy(), DeleteRows(), DumpOneTable(), GetBeatInternal(), GetDisplayedBeat(), GetElapsedTimeInternal(), GetTimingSegments(), InsertRows(), IsSafeFullTiming(), MultiplyBPMInBeatRange(), NegStopAndBPMCheck(), operator==(), PrepareLookup(), ScaleRegion(), SortSegments(), and TidyUpData().
m_beat_start_lookup
beat_start_lookup_t TimingData::m_beat_start_lookup
Referenced by DumpLookupTables(), GetBeatAndBPSFromElapsedTimeNoOffset(), PrepareLookup(), and ReleaseLookup().
m_fBeat0OffsetInSeconds
float TimingData::m_fBeat0OffsetInSeconds
The initial offset of a song.
Referenced by AdjustSync::AutosyncOffset(), AdjustSync::AutosyncTempo(), BuildAndGetEtaner(), BuildAndGetEtar(), SongCacheIndex::CacheSong(), Copy(), Deserialize(), GetBeatAndBPSFromElapsedTimeNoOffset(), GetElapsedTimeFromBeatNoOffset(), GetETTNoteData(), GetSSCNoteData(), AdjustSync::GetSyncChangeTextSong(), ScreenSyncOverlay::Input(), SongCacheIndex::InsertStepsTimingData(), DWILoader::LoadFromDir(), LoadFromKSFFile(), SMALoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), LoadGlobalData(), OsuLoader::LoadNoteDataFromParsedData(), OsuLoader::MsToNoteRow(), operator==(), PrepareLookup(), SMLoader::ProcessBPMsAndStops(), BMSChartReader::ReadHeaders(), BMSChartReader::ReadNoteData(), SetOffset(), SetStepsOffset(), SMSetOffset(), SongCacheIndex::SongFromStatement(), StartMusic(), NotesWriterDWI::Write(), WriteGlobalTags(), and NotesWriterJson::WriteSong().
m_sFile
RString TimingData::m_sFile
The file of the song/steps that use this TimingData.
This is for informational purposes only.
Referenced by Copy(), DumpLookupTables(), Song::LoadAutosaveFile(), SMALoader::LoadFromSimfile(), SMLoader::LoadFromSimfile(), SSCLoader::LoadFromSimfile(), SongCacheIndex::SongFromStatement(), and TidyUpData().
m_time_start_lookup
beat_start_lookup_t TimingData::m_time_start_lookup
Referenced by DumpLookupTables(), GetElapsedTimeFromBeatNoOffset(), PrepareLookup(), and ReleaseLookup().
ValidSequentialAssumption
bool TimingData::ValidSequentialAssumption = true
Referenced by IsSequentialAssumptionValid(), Player::Load(), NegStopAndBPMCheck(), WhereUAtBro(), and WhereUAtBroNoOffset().
The documentation for this class was generated from the following files:
TimingData.h
TimingData.cpp