Etterna: InputHandler Class Reference
InputHandler Class Reference abstract
A class designed to handle special input devices.
#include <InputHandler.h>
Public Member Functions
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual bool DevicesChanged ()
virtual void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)=0
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Public Member Functions
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes
static DriverList m_pDriverList
Protected Member Functions
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Private Attributes
std::chrono::time_point< std::chrono::steady_clock > m_LastUpdate
int m_iInputsSinceUpdate { 0 }
Detailed Description
A class designed to handle special input devices.
Constructor & Destructor Documentation
InputHandler()
InputHandler::InputHandler () inline
~InputHandler()
InputHandler::~InputHandler () override default
Member Function Documentation
ApplyKeyModifiers()
wchar_t InputHandler::ApplyKeyModifiers (wchar_t c) static
References INPUTFILTER, InputFilter::IsControlPressed(), InputFilter::IsShiftPressed(), L, and MakeUpper().
Referenced by DeviceButtonToChar(), and InputHandler_MacOSX_HID::DeviceButtonToChar().
ButtonPressed()
void InputHandler::ButtonPressed (DeviceInput di) protected
References InputFilter::ButtonPressed(), FAIL_M, INPUTFILTER, LOG, m_iInputsSinceUpdate, m_LastUpdate, DeviceInput::ts, and RageLog::Warn().
Referenced by InputHandler_SextetStream::Impl::ButtonPressed(), InputHandler_Win32_Pump::HandleInput(), InputHandler_Linux_PIUIO::InputThread(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), InputHandler_Win32_MIDI::SetDev(), InputHandler_Linux_tty::Update(), InputHandler_DInput::UpdateBuffered(), and InputHandler_DInput::UpdatePolled().
Create()
void InputHandler::Create (const RString & sDrivers, vector< InputHandler *> & apAdd) static
References DriverList::Create(), DEBUG_ASSERT, FOREACH_CONST, LocalizedString::GetValue(), INPUT_HANDLERS_EMPTY, LOG, split(), RageException::Throw(), and RageLog::Trace().
Referenced by RageInput::LoadDrivers().
DeviceButtonToChar()
wchar_t InputHandler::DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers) virtual
Reimplemented in InputHandler_MacOSX_HID, and InputHandler_DInput.
References ApplyKeyModifiers(), KEY_KP_ASTERISK, KEY_KP_C0, KEY_KP_C9, KEY_KP_EQUAL, KEY_KP_HYPHEN, KEY_KP_PERIOD, KEY_KP_PLUS, KEY_KP_SLASH, and L.
Referenced by InputHandler_DInput::DeviceButtonToChar(), InputHandler_MacOSX_HID::DeviceButtonToChar(), RageInput::DeviceInputToChar(), GetDeviceSpecificInputString(), and GetLocalizedInputString().
DevicesChanged()
virtual bool InputHandler::DevicesChanged () inline virtual
Reimplemented in InputHandler_MacOSX_HID, InputHandler_DInput, InputHandler_Linux_Joystick, and InputHandler_Linux_Event.
GetDevicesAndDescriptions()
virtual void InputHandler::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) pure virtual
Implemented in InputHandler_MacOSX_HID, InputHandler_Linux_Joystick, InputHandler_Linux_Event, InputHandler_Linux_tty, InputHandler_Win32_Pump, InputHandler_DInput, InputHandler_SextetStream, InputHandler_Win32_MIDI, InputHandler_Win32_Para, and InputHandler_Linux_PIUIO.
GetDeviceSpecificInputString()
RString InputHandler::GetDeviceSpecificInputString (const DeviceInput & di) virtual
Reimplemented in InputHandler_MacOSX_HID, and InputHandler_Win32_Pump.
References DeviceInput::button, Capitalize(), DeviceInput::device, DEVICE_KEYBOARD, DeviceButtonToChar(), DeviceButtonToString(), InputDevice_Invalid, InputDeviceToString(), L, and WStringToRString().
Referenced by InputHandler_Win32_Pump::GetDeviceSpecificInputString(), RageInput::GetDeviceSpecificInputString(), and InputHandler_MacOSX_HID::GetDeviceSpecificInputString().
GetInputDeviceState()
virtual InputDeviceState InputHandler::GetInputDeviceState (InputDevice) inline virtual
References InputDeviceState_Connected.
Referenced by RageInput::GetInputDeviceState().
GetLocalizedInputString()
RString InputHandler::GetLocalizedInputString (const DeviceInput & di) virtual
References ALT, BACKSLASH, DeviceInput::button, Capitalize(), CTRL, DEL, DeviceButtonToChar(), DeviceButtonToString(), DOWN, END, LocalizedString::GetValue(), HOME, INSERT, KEY_BACKSLASH, KEY_DEL, KEY_DOWN, KEY_END, KEY_HOME, KEY_INSERT, KEY_LALT, KEY_LCTRL, KEY_LSHIFT, KEY_PGDN, KEY_PGUP, KEY_RALT, KEY_RCTRL, KEY_RSHIFT, KEY_SPACE, KEY_UP, L, PGDN, PGUP, SHIFT, SPACE, UP, and WStringToRString().
Referenced by RageInput::GetLocalizedInputString().
Update()
virtual void InputHandler::Update () inline virtual
Reimplemented in InputHandler_DInput, InputHandler_X11, InputHandler_Linux_tty, and InputHandler_Win32_Pump.
UpdateTimer()
void InputHandler::UpdateTimer () protected
References m_iInputsSinceUpdate, and m_LastUpdate.
Referenced by InputHandler_Linux_PIUIO::InputThread(), InputHandler_Linux_Event::InputThread(), InputHandler_Linux_Joystick::InputThread(), InputHandler_Win32_Pump::InputThreadMain(), InputHandler_Win32_Pump::Update(), InputHandler_Linux_tty::Update(), InputHandler_X11::Update(), and InputHandler_DInput::Update().
WindowReset()
virtual void InputHandler::WindowReset () inline virtual
Reimplemented in InputHandler_DInput.
Member Data Documentation
m_iInputsSinceUpdate
int InputHandler::m_iInputsSinceUpdate { 0 } private
Referenced by ButtonPressed(), and UpdateTimer().
m_LastUpdate
std::chrono::time_point<std::chrono::steady_clock> InputHandler::m_LastUpdate private
Referenced by ButtonPressed(), and UpdateTimer().
m_pDriverList
DriverList InputHandler::m_pDriverList static
The documentation for this class was generated from the following files:
InputHandler.h
InputHandler.cpp