Etterna: BroadcastOnChangePtr< T > Class Template Reference
BroadcastOnChangePtr< T > Class Template Reference
#include <MessageManager.h>
Public Member Functions
BroadcastOnChangePtr (MessageID m)
T * Get () const
void Set (T *t)
void SetWithoutBroadcast (T *t)
operator T* () const
T * operator-> () const
Private Attributes
MessageID mSendWhenChanged
T * val
Constructor & Destructor Documentation
BroadcastOnChangePtr()
template<class T> BroadcastOnChangePtr< T >::BroadcastOnChangePtr (MessageID m) inline explicit
Member Function Documentation
Get()
template<class T> T* BroadcastOnChangePtr< T >::Get () const inline
Referenced by GameCommand::DescribesCurrentMode(), SongManager::GetExtraStageInfo(), AdjustSync::GetSyncChangeTextSong(), and BPMDisplay::SetFromGameState().
operator T*()
template<class T> BroadcastOnChangePtr< T >::operator T* () const inline
References BroadcastOnChangePtr< T >::val.
operator->()
template<class T> T* BroadcastOnChangePtr< T >::operator-> () const inline
Set()
template<class T> void BroadcastOnChangePtr< T >::Set (T * t) inline
Referenced by ScreenSelectMusic::AfterMusicChange(), GameCommand::ApplySelf(), ScreenOptionsCourseOverview::BeginScreen(), GameState::GameState(), SongManager::GetExtraStageInfo(), ScreenGameplaySyncMachine::HandleScreenMessage(), ScreenNetSelectMusic::HandleScreenMessage(), ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), ScreenEvaluation::Init(), OptionRowHandlerListSongsInCurrentSongGroup::LoadInternal(), ScreenGameplay::LoadNextSong(), GameState::Reset(), ScreenNetSelectMusic::SelectCurrent(), GameState::SetCurGame(), LunaGameState::SetCurrentSong(), GameState::SetCurrentStyle(), and ScreenNetSelectMusic::StartSelectedSong().
SetWithoutBroadcast()
template<class T> void BroadcastOnChangePtr< T >::SetWithoutBroadcast (T * t) inline
Member Data Documentation
mSendWhenChanged
template<class T> MessageID BroadcastOnChangePtr< T >::mSendWhenChanged private
val
template<class T> T* BroadcastOnChangePtr< T >::val private
Referenced by BroadcastOnChangePtr< const Style >::Get(), BroadcastOnChangePtr< T >::operator T*(), and BroadcastOnChangePtr< const Style >::operator->().
The documentation for this class was generated from the following file:
MessageManager.h