Etterna: LuaHelpers Namespace Reference
LuaHelpers Namespace Reference
Utilities for working with Lua.
Functions
template<>
bool FromStack (Lua *L, RString &object, int offset)
template<>
void Push< bool > (lua_State *L, bool const &object)
template<>
void Push< float > (lua_State *L, float const &object)
template<>
void Push< double > (lua_State *L, double const &object)
template<>
void Push< int > (lua_State *L, int const &object)
template<>
void Push< unsigned int > (lua_State *L, unsigned int const &object)
template<>
void Push< unsigned long > (lua_State *L, unsigned long const &object)
template<>
void Push< std::string > (lua_State *L, std::string const &object)
template<>
void Push< RString > (lua_State *L, RString const &object)
template<>
bool FromStack< bool > (Lua *L, bool &object, int offset)
template<>
bool FromStack< float > (Lua *L, float &object, int offset)
template<>
bool FromStack< double > (Lua *L, double &object, int offset)
template<>
bool FromStack< int > (Lua *L, int &object, int offset)
template<>
bool FromStack< unsigned int > (Lua *L, unsigned int &object, int offset)
template<>
bool FromStack< unsigned long > (Lua *L, unsigned long &object, int offset)
template<>
bool FromStack< std::string > (Lua *L, std::string &object, int offset)
template<>
bool FromStack< RString > (Lua *L, RString &object, int offset)
bool FromStack (Lua *L, char const *object, int offset)
bool LoadScript (Lua *L, const std::string &sScript, const std::string &sName, std::string &sError)
Dialog::Result ReportScriptError (std::string const &Error, std::string ErrorType="LUA_ERROR", bool UseAbort=false)
void ScriptErrorMessage (std::string const &Error)
template<typename... Args>
void ReportScriptErrorFmt (std::string const &msg, Args const &... args)
A convenience method to use when replacing uses of LOG->Warn.
bool RunScriptOnStack (Lua *L, std::string &Error, int Args=0, int ReturnValues=0, bool ReportError=false, bool blank_env=false)
bool RunScript (Lua *L, const std::string &Script, const std::string &Name, std::string &Error, int Args=0, int ReturnValues=0, bool ReportError=false, bool blank_env=false)
bool RunExpression (Lua *L, const std::string &sExpression, const std::string &sName="", bool blank_env=false)
bool RunScriptFile (const std::string &sFile, bool blank_env=false)
bool run_script_file_in_state (lua_State *L, std::string const &filename, int return_values, bool blank_env)
bool string_can_be_lua_identifier (lua_State *L, std::string const &str)
void push_lua_escaped_string (lua_State *L, std::string const &str)
void save_lua_table_to_file (lua_State *L, int table_index, std::string const &filename)
void CreateTableFromArrayB (Lua *L, const std::vector< bool > &aIn)
void CreateTableFromXNode (Lua *L, const XNode *pNode)
void DeepCopy (lua_State *L)
void ReadArrayFromTableB (Lua *L, std::vector< bool > &aOut)
void rec_print_table (lua_State *L, std::string const &name, std::string const &indent)
void ParseCommandList (lua_State *L, const std::string &sCommands, const std::string &sName, bool bLegacy)
XNode * GetLuaInformation ()
void PushValueFunc (lua_State *L, int iArgs)
template<class T >
void Push (lua_State *L, const T &Object)
template<class T >
bool FromStack (lua_State *L, T &Object, int iOffset)
template<class T >
bool Pop (lua_State *L, T &val)
template<class T >
void ReadArrayFromTable (std::vector< T > &aOut, lua_State *L)
template<class T >
void CreateTableFromArray (const std::vector< T > &aIn, lua_State *L)
int TypeError (Lua *L, int narg, std::string const &tname)
int AbsIndex (Lua *L, int i)
template<>
bool FromStack< LuaReference > (lua_State *L, LuaReference &Object, int iOffset)
template<>
bool FromStack< apActorCommands > (lua_State *L, apActorCommands &Object, int iOffset)
template<>
void Push< LuaReference > (lua_State *L, const LuaReference &Object)
template<class T >
void Push (lua_State *L, const BroadcastOnChange< T > &Object)
template<typename T >
void Push (lua_State *L, const Preference< T > &Object)
template<>
bool FromStack< RageColor > (lua_State *L, RageColor &Object, int iOffset)
template<>
void Push< RageColor > (lua_State *L, const RageColor &Object)
Variables
bool InReportScriptError = false
Detailed Description
Utilities for working with Lua.
Function Documentation
AbsIndex()
int LuaHelpers::AbsIndex (Lua * L, int i) inline
Referenced by CheckEnum(), and LuaBinding::GetPointerFromStack().
CreateTableFromArray()
template<class T > void LuaHelpers::CreateTableFromArray (const std::vector< T > & aIn, lua_State * L)
References Push().
Referenced by LunaTimingData::GetActualBPM(), LunaCharacterManager::GetAllCharacters(), LunaAnnouncerManager::GetAnnouncerNames(), LunaTimingData::GetBPMs(), LunaPlaylist::GetChartkeys(), LunaRageInput::GetDescriptions(), LunaRageFileManager::GetDirListing(), LunaSteps::GetDisplayBpms(), LunaSong::GetDisplayBpms(), LunaGameState::GetEnabledPlayers(), LunaProfile::GetGoalTable(), LunaGameState::GetHumanPlayers(), LunaHighScore::GetNoteRowVector(), LunaNoteSkinManager::GetNoteSkinNames(), LunaHighScore::GetOffsetVector(), LunaPacklist::GetPackTable(), LunaSteps::GetRelevantRadars(), LunaHighScore::GetTapNoteTypeVector(), LunaHelpDisplay::gettips(), LunaHighScore::GetTrackVector(), LunaDownloadManager::RequestChartLeaderBoard(), and Message::SetParam().
CreateTableFromArrayB()
void LuaHelpers::CreateTableFromArrayB (Lua * L, const std::vector< bool > & aIn)
Referenced by OptionRowHandlerLua::ExportOption(), and OptionRowHandlerLua::ImportOption().
CreateTableFromXNode()
void LuaHelpers::CreateTableFromXNode (Lua * L, const XNode * pNode)
Referenced by XMLProfile::LoadEttGeneralDataFromNode(), and XMLProfile::LoadGeneralDataFromNode().
DeepCopy()
void LuaHelpers::DeepCopy (lua_State * L)
References ASSERT_M.
Referenced by LuaReference::DeepCopy().
FromStack() [1/3]
template<> bool LuaHelpers::FromStack (Lua * L, RString & object, int offset)
Referenced by FromStack(), FromStack< apActorCommands >(), GetAndConvertMetric(), GetLuaInformation(), Pop(), ThemeMetric< AutoPtrCopyOnWrite >::Read(), LuaBinding::Register(), and LunaActorScroller::SetTransformFromFunction().
FromStack() [2/3]
bool LuaHelpers::FromStack (Lua * L, char const * object, int offset)
References FromStack().
FromStack() [3/3]
template<class T > bool LuaHelpers::FromStack (lua_State * L, T & Object, int iOffset)
FromStack< apActorCommands >()
template<> bool LuaHelpers::FromStack< apActorCommands > (lua_State * L, apActorCommands & Object, int iOffset)
References FromStack().
FromStack< bool >()
template<> bool LuaHelpers::FromStack< bool > (Lua * L, bool & object, int offset)
FromStack< double >()
template<> bool LuaHelpers::FromStack< double > (Lua * L, double & object, int offset)
FromStack< float >()
template<> bool LuaHelpers::FromStack< float > (Lua * L, float & object, int offset)
FromStack< int >()
template<> bool LuaHelpers::FromStack< int > (Lua * L, int & object, int offset)
FromStack< LuaReference >()
template<> bool LuaHelpers::FromStack< LuaReference > (lua_State * L, LuaReference & Object, int iOffset)
FromStack< RageColor >()
template<> bool LuaHelpers::FromStack< RageColor > (lua_State * L, RageColor & Object, int iOffset)
FromStack< RString >()
template<> bool LuaHelpers::FromStack< RString > (Lua * L, RString & object, int offset)
FromStack< std::string >()
template<> bool LuaHelpers::FromStack< std::string > (Lua * L, std::string & object, int offset)
FromStack< unsigned int >()
template<> bool LuaHelpers::FromStack< unsigned int > (Lua * L, unsigned int & object, int offset)
FromStack< unsigned long >()
template<> bool LuaHelpers::FromStack< unsigned long > (Lua * L, unsigned long & object, int offset)
GetLuaInformation()
XNode * LuaHelpers::GetLuaInformation ()
References XNode::AppendAttr(), XNode::AppendChild(), ASSERT, FOREACH_LUATABLE, FromStack(), LuaManager::Get(), Pop(), ReadArrayFromTable(), LuaManager::Release(), and ssprintf().
Referenced by LuaInformation().
LoadScript()
bool LuaHelpers::LoadScript (Lua * L, const std::string & sScript, const std::string & sName, std::string & sError)
References Pop().
Referenced by RunScript().
ParseCommandList()
void LuaHelpers::ParseCommandList (lua_State * L, const std::string & sCommands, const std::string & sName, bool bLegacy)
References RageColor::a, RageColor::b, RageColor::FromString(), RageColor::g, LOG, Rage::make_lower(), ParseCommands(), RageColor::r, Rage::replace(), RunScript(), Commands::v, and RageLog::Warn().
Referenced by ActorUtil::ParseActorCommands(), and ThemeManager::PushMetric().
Pop()
template<class T > bool LuaHelpers::Pop (lua_State * L, T & val)
References FromStack().
Referenced by CheckEnum(), FormatAnswerForDisplayFromLua(), GetLuaInformation(), GetLuaStack(), ThemeManager::GetMetricsGroupFallback(), Message::GetParam(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), XNodeLuaValue::GetValue(), ScreenWithMenuElements::HandleLuaMusicFile(), ScoreDisplayAliveTime::LoadFromNode(), PaneDisplay::LoadFromNode(), LoadScript(), LuaPanic(), ReadArrayFromTable(), PercentageDisplay::Refresh(), RunScriptOnStack(), MenuTimer::SetText(), XNodeStringValue::SetValueFromStack(), and TypeError().
Push() [1/3]
template<typename T > void LuaHelpers::Push (lua_State * L, const Preference< T > & Object)
References Preference< T >::Get(), and L.
Push() [2/3]
template<class T > void LuaHelpers::Push (lua_State * L, const T & Object)
Referenced by LunaGameState::ApplyGameCommand(), ScoreKeeperNormal::CalcNextToastyAt(), LunaGameState::CanSafelyEnterGameplay(), CheckEnum(), DynamicActorScroller::ConfigureActor(), LuaReference::Create(), CreateTableFromArray(), OptionRowHandlerLua::ExportOption(), LunaScreenSelectProfile::Finish(), LunaSong::GetBGChanges(), LunaWheelItemBase::GetColor(), LunaGameState::GetCurrentStyle(), LunaSteps::GetDisplayBPMType(), LunaRageDisplay::GetDisplayHeight(), LunaRageDisplay::GetDisplayWidth(), LunaGameManager::GetFirstStepsTypeForGame(), LunaGameState::GetGameSeed(), LunaLifeMeter::GetLife(), GetLuaStack(), LunaStyle::GetName(), LunaActor::GetNumStates(), LunaPlayerState::GetPlayerOptionsString(), LunaScreenSelectProfile::GetProfileIndex(), LunaScoreManager::GetScoresByKey(), LunaGameState::GetSongOptions(), LunaStageStats::GetStage(), LunaGameState::GetStageResult(), LunaGameState::GetStageSeed(), LunaScreenEvaluation::GetStageStats(), LunaWheelItemBase::GetText(), LunaDownloadManager::GetTopSkillsetScore(), LunaScreenProfileLoad::HaveProfileToLoad(), LunaScreenProfileSave::HaveProfileToSave(), OptionRowHandlerLua::ImportOption(), ScreenOptions::InitMenu(), LunaLifeMeter::IsFailing(), LunaLifeMeter::IsHot(), LunaLifeMeter::IsInDanger(), Profile::LoadCustomFunction(), LuaFunc_commify(), LuaThreadVariable::LuaThreadVariable(), LunaRoomWheel::MoveAndCheckType(), LunaMusicWheel::MoveAndCheckType(), OptionRowHandlerLua::NotifyOfSelection(), LifeMeterBattery::OnSongEnded(), Screen::PassInputToLua(), ActorFrame::PushChildrenTable(), LunaThemeManager::PushMetricNamesInGroup(), LuaThreadVariable::PushThreadTable(), XNodeStringValue::PushValue(), PercentageDisplay::Refresh(), LuaManager::SetGlobal(), Message::SetParam(), LunaScreenSelectProfile::SetProfileIndex(), LunaRageSound::SetProperty(), MenuTimer::SetText(), XNodeLuaValue::SetValue(), LuaExpressionTransform::TransformItemDirect(), and LuaThreadVariable::~LuaThreadVariable().
Push() [3/3]
template<class T > void LuaHelpers::Push (lua_State * L, const BroadcastOnChange< T > & Object)
References BroadcastOnChange< T >::Get(), and L.
Push< bool >()
template<> void LuaHelpers::Push< bool > (lua_State * L, bool const & object)
Push< double >()
template<> void LuaHelpers::Push< double > (lua_State * L, double const & object)
Push< float >()
template<> void LuaHelpers::Push< float > (lua_State * L, float const & object)
Push< int >()
template<> void LuaHelpers::Push< int > (lua_State * L, int const & object)
Push< LuaReference >()
template<> void LuaHelpers::Push< LuaReference > (lua_State * L, const LuaReference & Object)
Push< RageColor >()
template<> void LuaHelpers::Push< RageColor > (lua_State * L, const RageColor & Object)
Push< RString >()
template<> void LuaHelpers::Push< RString > (lua_State * L, RString const & object)
Push< std::string >()
template<> void LuaHelpers::Push< std::string > (lua_State * L, std::string const & object)
Push< unsigned int >()
template<> void LuaHelpers::Push< unsigned int > (lua_State * L, unsigned int const & object)
Push< unsigned long >()
template<> void LuaHelpers::Push< unsigned long > (lua_State * L, unsigned long const & object)
push_lua_escaped_string()
void LuaHelpers::push_lua_escaped_string (lua_State * L, std::string const & str)
Referenced by write_lua_table_to_file().
PushValueFunc()
void LuaHelpers::PushValueFunc (lua_State * L, int iArgs)
Referenced by LuaBinding::Register(), and Enum::SetMetatable().
ReadArrayFromTable()
template<class T > void LuaHelpers::ReadArrayFromTable (std::vector< T > & aOut, lua_State * L)
References Pop(), and T.
Referenced by LunaMusicWheel::FilterByStepKeys(), GetLuaInformation(), LunaGrooveRadar::SetFromValues(), LunaActorFrame::SetLightDirection(), and LunaHelpDisplay::settips().
ReadArrayFromTableB()
void LuaHelpers::ReadArrayFromTableB (Lua * L, std::vector< bool > & aOut)
Referenced by OptionRowHandlerLua::ImportOption().
rec_print_table()
void LuaHelpers::rec_print_table (lua_State * L, std::string const & name, std::string const & indent)
References LOG, and RageLog::Trace().
ReportScriptError()
Dialog::Result LuaHelpers::ReportScriptError (std::string const & Error, std::string ErrorType = "LUA_ERROR", bool UseAbort = false)
References InReportScriptError, LOG, ScriptErrorMessage(), and RageLog::Warn().
Referenced by Actor::AddCommand(), GameCommand::ApplySelf(), ScoreKeeperNormal::CalcNextToastyAt(), CheckEnum(), ActorFrameTexture::Create(), FormatAnswerForDisplayFromLua(), ScreenTextEntry::TextEntrySettings::FromStack(), NoteSkinManager::GetMetric(), ThemeManager::GetMetricRaw(), NoteSkinManager::GetPath(), NoteSkinManager::GetPathFromDirAndFile(), ThemeManager::GetPathInfoToRaw(), MusicWheel::GetPreferredSelectionForRandomOrPortal(), ThemeManager::GetString(), Screen::HandleScreenMessage(), ScreenSelect::Init(), ScreenSelectMaster::Init(), ScreenEvaluation::Init(), DifficultyIcon::Load(), ScreenManager::LoadDelayedScreen(), XmlFileUtil::LoadFromFileShowErrors(), StepsDisplayList::LoadFromNode(), PercentageDisplay::LoadFromNode(), PaneDisplay::LoadFromNode(), ActorUtil::LoadFromNode(), NoteSkinManager::LoadNoteSkinDataRecursive(), ActorUtil::LoadTableFromStackShowErrors(), NoteSkinManager::PushActorTemplate(), ThemeManager::PushMetric(), ThemeMetricDifficultiesToShow::Read(), Font::Reload(), ReportScriptErrorFmt(), ActorUtil::ResolvePath(), run_script_file_in_state(), RunScript(), RunScriptFile(), RunScriptOnStack(), SafeFArg(), LuaExpressionTransform::SetFromReference(), GradeDisplay::SetGrade(), Sprite::SetState(), RollingNumbers::SetTargetNumber(), NoteSkinManager::ValidateNoteSkinName(), and verify_arg_count().
ReportScriptErrorFmt()
template<typename... Args> void LuaHelpers::ReportScriptErrorFmt (std::string const & msg, Args const &... args)
A convenience method to use when replacing uses of LOG->Warn.
References ReportScriptError(), and ssprintf().
Referenced by LunaActor::accelerate(), ScreenSelectMusic::AfterMusicChange(), GameState::ApplyGameCommand(), GameState::BeginStage(), Actor::BeginTweening(), BackgroundImpl::Layer::CreateBackground(), ITween::CreateFromStack(), LunaActor::decelerate(), ActorFrame::DrawPrimitives(), LunaActor::effectperiod(), get_returned_column(), LunaStyle::GetColumnDrawOrder(), LunaStyle::GetColumnInfo(), GameState::GetEasiestStepsDifficulty(), SongManager::GetExtraStageInfo(), GameState::GetHardestStepsDifficulty(), ThemeManager::GetMetricRawRecursive(), ThemeManager::GetPath(), ThemeManager::GetPathInfoToAndFallback(), LunaPrefsManager::GetPreference(), ScreenWithMenuElements::HandleLuaMusicFile(), ScreenSMOnlineLogin::HandleScreenMessage(), ScreenOptions::HandleScreenMessage(), ScreenOptionsMaster::Init(), ScreenSelect::Init(), ScreenHowToPlay::Init(), ScreenSelectMaster::Init(), ScreenGameplay::Init(), PlayerAI::InitFromDisk(), LunaActor::linear(), ComboGraph::Load(), OptionsList::Load(), FontPage::Load(), Font::Load(), NoteSkinManager::LoadActor(), Profile::LoadEditableDataFromDir(), Font::LoadFontPageSettings(), XmlFileUtil::LoadFromFileShowErrors(), LyricsLoader::LoadFromLRCFile(), DynamicActorScroller::LoadFromNode(), HoldJudgment::LoadFromNode(), MeterDisplay::LoadFromNode(), BitmapText::LoadFromNode(), StepsDisplayList::LoadFromNode(), DifficultyIcon::LoadFromNode(), Sprite::LoadFromNode(), TitleTrans::LoadFromNode(), OptionRowHandlerList::LoadInternal(), XMLProfile::LoadStatsFromDir(), ScreenManager::MakeNewScreen(), ThemeMetricDifficultiesToShow::Read(), RemoveStepsTypes(), Actor::RunCommands(), OptionRowHandlerLua::SanityCheckTable(), save_lua_table_to_file(), XMLProfile::SaveEttXmlToDir(), XMLProfile::SaveStatsXmlToDir(), XmlFileUtil::SaveToFile(), Font::SetDefaultGlyph(), ActorMultiVertex::AMV_TweenState::SetDrawState(), LunaActorMultiVertex::SetDrawState(), LunaActorMultiVertex::SetLineWidth(), LunaPrefsManager::SetPreference(), LunaPrefsManager::SetPreferenceToDefault(), LunaActorMultiVertex::SetVertex(), LunaActorMultiVertex::SetVertexFromStack(), LunaActorMultiVertex::SetVertices(), LunaActor::sleep(), LunaActor::spring(), LunaActor::tween(), BackgroundImpl::Layer::UpdateCurBGChange(), ActorFrame::UpdateInternal(), and VerifySelected().
run_script_file_in_state()
bool LuaHelpers::run_script_file_in_state (lua_State * L, std::string const & filename, int return_values, bool blank_env)
References GetFileContents(), ReportScriptError(), RunScript(), and ssprintf().
RunExpression()
bool LuaHelpers::RunExpression (Lua * L, const std::string & sExpression, const std::string & sName = "", bool blank_env = false)
References RunScript(), and ssprintf().
Referenced by ThemeManager::GetMetricsGroupFallback(), ScreenSelect::Init(), ThemeManager::PushMetric(), and LuaReference::SetFromExpression().
RunScript()
bool LuaHelpers::RunScript (Lua * L, const std::string & Script, const std::string & Name, std::string & Error, int Args = 0, int ReturnValues = 0, bool ReportError = false, bool blank_env = false)
References LoadScript(), ReportScriptError(), and RunScriptOnStack().
Referenced by ScreenWithMenuElements::HandleLuaMusicFile(), NoteSkinManager::LoadNoteSkinDataRecursive(), ParseCommandList(), run_script_file_in_state(), RunExpression(), and RunScriptFile().
RunScriptFile()
bool LuaHelpers::RunScriptFile (const std::string & sFile, bool blank_env = false)
References LuaManager::Get(), GetFileContents(), LuaManager::Release(), ReportScriptError(), RunScript(), and ssprintf().
Referenced by ThemeManager::RunLuaScripts().
RunScriptOnStack()
bool LuaHelpers::RunScriptOnStack (Lua * L, std::string & Error, int Args = 0, int ReturnValues = 0, bool ReportError = false, bool blank_env = false)
References GetLuaStack(), infinite_loop_preventer(), Pop(), and ReportScriptError().
Referenced by GameCommand::ApplySelf(), ScoreKeeperNormal::CalcNextToastyAt(), DynamicActorScroller::ConfigureActor(), ActorFrame::DrawPrimitives(), OptionRowHandlerLua::ExportOption(), FormatAnswerForDisplayFromLua(), ThemeMetric< AutoPtrCopyOnWrite >::GetValue(), OptionRowHandlerLua::ImportOption(), ScreenSelectMaster::Init(), ScreenGameplay::Init(), Profile::LoadCustomFunction(), DynamicActorScroller::LoadFromNode(), ActorUtil::LoadTableFromStackShowErrors(), OptionRowHandlerLua::NotifyOfSelection(), LifeMeterBattery::OnSongEnded(), Screen::PassInputToLua(), PercentageDisplay::Refresh(), Actor::RunCommands(), RunScript(), OptionRowHandlerLua::SanityCheckTable(), OptionRowHandlerLua::SetEnabledForPlayers(), MenuTimer::SetText(), LuaExpressionTransform::TransformItemDirect(), and ActorFrame::UpdateInternal().
save_lua_table_to_file()
void LuaHelpers::save_lua_table_to_file (lua_State * L, int table_index, std::string const & filename)
References RageFile::Close(), RageFile::GetError(), RageFile::Open(), ReportScriptErrorFmt(), RageFile::WRITE, RageFile::Write(), and write_lua_table_to_file().
ScriptErrorMessage()
void LuaHelpers::ScriptErrorMessage (std::string const & Error)
References MessageManager::Broadcast(), MESSAGEMAN, and Message::SetParam().
Referenced by ThemeManager::GetPathInfo(), and ReportScriptError().
string_can_be_lua_identifier()
bool LuaHelpers::string_can_be_lua_identifier (lua_State * L, std::string const & str)
Referenced by write_lua_table_to_file().
TypeError()
int LuaHelpers::TypeError (Lua * L, int narg, std::string const & tname)
References Pop().
Referenced by Luna< GameSoundManager >::check().
Variable Documentation
InReportScriptError
bool LuaHelpers::InReportScriptError = false
Referenced by ReportScriptError().