Etterna: RageSoundUtil Namespace Reference
RageSoundUtil Namespace Reference
Simple utilities that operate on sound buffers.
Functions
void Attenuate (float *pBuf, int iSamples, float fVolume)
void Pan (float *pBuffer, int iFrames, float fPos)
void Fade (float *pBuffer, int iFrames, int iChannels, float fStartVolume, float fEndVolume)
void ConvertMonoToStereoInPlace (float *pBuffer, int iFrames)
void ConvertNativeInt16ToFloat (const int16_t *pFrom, float *pTo, int iSamples)
void ConvertFloatToNativeInt16 (const float *pFrom, int16_t *pTo, int iSamples)
Detailed Description
Simple utilities that operate on sound buffers.
Function Documentation
Attenuate()
void RageSoundUtil::Attenuate (float * pBuf, int iSamples, float fVolume)
Referenced by RageSoundReader_PostBuffering::Read().
ConvertFloatToNativeInt16()
void RageSoundUtil::ConvertFloatToNativeInt16 (const float * pFrom, int16_t * pTo, int iSamples)
References clamp, and f.
Referenced by RageSoundReader_Preload::Open().
ConvertMonoToStereoInPlace()
void RageSoundUtil::ConvertMonoToStereoInPlace (float * pBuffer, int iFrames)
Referenced by RageSound::GetDataToPlay(), and RageSoundReader_Pan::Read().
ConvertNativeInt16ToFloat()
void RageSoundUtil::ConvertNativeInt16ToFloat (const int16_t * pFrom, float * pTo, int iSamples)
Referenced by RageSoundReader_Preload::Read().
Fade()
void RageSoundUtil::Fade (float * pBuffer, int iFrames, int iChannels, float fStartVolume, float fEndVolume)
References clamp, f, and SCALE.
Referenced by RageSoundReader_Extend::Read().
Pan()
void RageSoundUtil::Pan (float * pBuffer, int iFrames, float fPos)
References f, SCALE, and swap().
Referenced by RageSoundReader_Pan::Read().