Etterna: RageBitmapTexture Class Reference
RageBitmapTexture Class Reference
#include <RageBitmapTexture.h>
Public Member Functions
RageBitmapTexture (const RageTextureID &name)
~RageBitmapTexture () override
void Invalidate () override
void Reload () override
unsigned GetTexHandle () const override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Update (float)
virtual void SetPosition (float)
virtual void DecodeSeconds (float)
virtual void SetPlaybackRate (float)
virtual bool IsAMovie () const
virtual void SetLooping (bool)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Private Member Functions
void Create ()
void Destroy ()
Private Attributes
unsigned m_uTexHandle
Additional Inherited Members
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Constructor & Destructor Documentation
RageBitmapTexture()
RageBitmapTexture::RageBitmapTexture (const RageTextureID & name)
References Create().
~RageBitmapTexture()
RageBitmapTexture::~RageBitmapTexture () override
References Destroy().
Member Function Documentation
Create()
void RageBitmapTexture::Create () private
References RageTextureID::AdditionalTextureHints, RageSurfaceUtils::ApplyHotPinkColorKey(), ASSERT, ASSERT_M, RageTextureID::bDither, RageTextureID::bHotPinkColorKey, RageSurfaceFormat::BitsPerPixel, RageTextureID::bMipMaps, RageDisplay::RagePixelFormatDesc::bpp, RageTextureID::bStretch, RageSurfaceUtils::ConvertSurface(), RageTexture::CreateFrameRects(), CreateSurface(), RageDisplay::CreateTexture(), DISPLAY, RageSurfaceUtils::ErrorDiffusionDither(), FAIL_M, RageTextureID::filename, RageSurfaceUtils::FindSurfaceTraits(), RageSurfaceUtils::FixHiddenAlpha(), RageSurface::fmt, RageTexture::GetFramesHigh(), RageTexture::GetFramesWide(), StepMania::GetHighResolutionTextures(), RageTexture::GetID(), RageDisplay::GetMaxTextureSize(), RageTextureManager::GetOddDimensionWarning(), RageDisplay::GetPixelFormatDesc(), GetResolutionFromFileName(), RageTextureManager::GetScreenSurface(), RageTextureManager::GetScreenTextureID(), RageTexture::GetSourceHeight(), RageTexture::GetSourceWidth(), RageSurface::h, RageTextureID::iAlphaBits, RageTextureID::iColorDepth, RageTextureID::iGrayscaleBits, RageTextureID::iMaxSize, RageSurfaceUtils::LoadFile(), LOG, RageSurfaceFormat::Loss, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_uTexHandle, RageSurfaceUtils::MakeDummySurface(), StdString::CStdStr< CT >::MakeLower(), RageSurfaceFormat::Mask, RageDisplay::RagePixelFormatDesc::masks, max(), min(), RageSurfaceUtils::PalettizeToGrayscale(), power_of_two(), RagePixelFormat_PAL, RagePixelFormat_RGB5A1, RagePixelFormat_RGBA4, RagePixelFormat_RGBA8, RagePixelFormatToString(), ssprintf(), RageDisplay::SupportsTextureFormat(), TEXTUREMAN, RageSurfaceUtils::TRAIT_BOOL_TRANSPARENCY, RageSurfaceUtils::TRAIT_NO_TRANSPARENCY, RageSurface::w, RageLog::Warn(), and RageSurfaceUtils::Zoom().
Referenced by RageBitmapTexture(), and Reload().
Destroy()
void RageBitmapTexture::Destroy () private
References RageDisplay::DeleteTexture(), DISPLAY, and m_uTexHandle.
Referenced by Reload(), and ~RageBitmapTexture().
GetTexHandle()
unsigned RageBitmapTexture::GetTexHandle () const inline override virtual
Implements RageTexture.
References m_uTexHandle.
Invalidate()
void RageBitmapTexture::Invalidate () inline override virtual
Reimplemented from RageTexture.
References m_uTexHandle.
Reload()
void RageBitmapTexture::Reload () override virtual
Reimplemented from RageTexture.
References Create(), and Destroy().
Member Data Documentation
m_uTexHandle
unsigned RageBitmapTexture::m_uTexHandle private
Referenced by Create(), Destroy(), GetTexHandle(), and Invalidate().
The documentation for this class was generated from the following files:
RageBitmapTexture.h
RageBitmapTexture.cpp