Etterna: DebugLineAutoplay Class Reference
DebugLineAutoplay Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
Type GetType () const override
bool IsEnabled () override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual RString GetPageName () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineAutoplay::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References ASSERT, DEVICE_KEYBOARD, IDebugLine::DoAndLog(), FOREACH_HumanPlayer, FOREACH_MultiPlayer, GAMESTATE, GameState::GetMasterPlayerNumber(), INPUTFILTER, InputFilter::IsBeingPressed(), KEY_LALT, KEY_LSHIFT, KEY_RALT, KEY_RSHIFT, GamePreferences::m_AutoPlay, PlayerState::m_PlayerController, GameState::m_pMultiPlayerState, GameState::m_pPlayerState, PC_AUTOPLAY, PC_CPU, PC_HUMAN, PC_REPLAY, PLAYER_INVALID, and ScreenSyncOverlay::SetShowAutoplay().
GetDisplayTitle()
RString DebugLineAutoplay::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References AUTO_PLAY, and LocalizedString::GetValue().
GetDisplayValue()
RString DebugLineAutoplay::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
References CPU, FAIL_M, LocalizedString::GetValue(), GamePreferences::m_AutoPlay, OFF, ON, PC_AUTOPLAY, PC_CPU, PC_HUMAN, PC_REPLAY, REPLAY, and ssprintf().
GetType()
Type DebugLineAutoplay::GetType () const inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::gameplay_only.
IsEnabled()
bool DebugLineAutoplay::IsEnabled () inline override private virtual
Implements IDebugLine.
References GamePreferences::m_AutoPlay, and PC_HUMAN.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp