Etterna: RageFileDriverMountpoints Class Reference
RageFileDriverMountpoints Class Reference
Public Member Functions
RageFileDriverMountpoints ()
RageFileBasic * Open (const RString &sPath, int iMode, int &iError)
void FlushDirCache (const RString &sPath)
void LoadFromDrivers (const vector< LoadedDriver *> &apDrivers)
Public Member Functions inherited from RageFileDriver
RageFileDriver (FilenameDB *pDB)
virtual ~RageFileDriver ()
virtual void GetDirListing (const RString &sPath, vector< RString > &asAddTo, bool bOnlyDirs, bool bReturnPathToo)
virtual RageFileManager::FileType GetFileType (const RString &sPath)
virtual int GetFileSizeInBytes (const RString &sFilePath)
virtual int GetFileHash (const RString &sPath)
virtual int GetPathValue (const RString &sPath)
virtual void CacheFile (const RString &)
virtual bool Move (const RString &, const RString &)
virtual bool Remove (const RString &)
virtual bool Remount (const RString &)
Additional Inherited Members
Public Types inherited from RageFileDriver
enum { ERROR_WRITING_NOT_SUPPORTED = -1 }
Public Attributes inherited from RageFileDriver
FilenameDB * FDB
Constructor & Destructor Documentation
RageFileDriverMountpoints()
RageFileDriverMountpoints::RageFileDriverMountpoints () inline
Member Function Documentation
FlushDirCache()
void RageFileDriverMountpoints::FlushDirCache (const RString & sPath) inline virtual
Reimplemented from RageFileDriver.
LoadFromDrivers()
void RageFileDriverMountpoints::LoadFromDrivers (const vector< LoadedDriver *> & apDrivers) inline
References FilenameDB::AddFile(), RageFileDriver::FDB, and FilenameDB::FlushDirCache().
Referenced by AddFilesystemDriver(), and RageFileManager::Unmount().
Open()
RageFileBasic* RageFileDriverMountpoints::Open (const RString & sPath, int iMode, int & iError) inline virtual
Implements RageFileDriver.
References RageFileDriver::ERROR_WRITING_NOT_SUPPORTED, and RageFile::WRITE.
The documentation for this class was generated from the following file:
RageFileManager.cpp