Etterna: RageSurfaceUtils_Palettize.cpp File Reference
RageSurfaceUtils_Palettize.cpp File Reference
#include "RageSurfaceUtils_Palettize.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageUtil.h"
#include "global.h"
Classes
struct acolorhist_item
struct acolorhist_list_item
struct acolorhash_hash
struct pixerror_t
struct box
Macros
#define PAM_GETR(p) ((p)[0])
#define PAM_GETG(p) ((p)[1])
#define PAM_GETB(p) ((p)[2])
#define PAM_GETA(p) ((p)[3])
#define PAM_ASSIGN(p, red, grn, blu, alf)
#define PAM_EQUAL(p, q)
#define PAM_DEPTH(p)
#define MAXCOLORS 32767
#define FS_SCALE 1024 /* Floyd-Steinberg scaling factor */
#define REP_AVERAGE_PIXELS
#define pam_hashapixel(p)
Typedefs
typedef uint8_t pixval
typedef uint8_t apixel[4]
typedef struct acolorhist_list_item * acolorhist_list
typedef struct box * box_vector
Functions
static acolorhist_item * mediancut (acolorhist_item *achv, int colors, int sum, int maxval, int newcolors)
static bool compare_index_0 (const acolorhist_item &ch1, const acolorhist_item &ch2)
static bool compare_index_1 (const acolorhist_item &ch1, const acolorhist_item &ch2)
static bool compare_index_2 (const acolorhist_item &ch1, const acolorhist_item &ch2)
static bool compare_index_3 (const acolorhist_item &ch1, const acolorhist_item &ch2)
static acolorhist_item * pam_computeacolorhist (const RageSurface *src, int maxacolors, int *acolorsP)
static void pam_addtoacolorhash (acolorhash_hash &acht, const uint8_t acolorP[4], int value)
static int pam_lookupacolor (const acolorhash_hash &acht, const uint8_t acolorP[4])
static void pam_freeacolorhist (acolorhist_item *achv)
static bool CompareBySumDescending (const box &b1, const box &b2)
static bool pam_computeacolorhash (const RageSurface *src, int maxacolors, int *acolorsP, acolorhash_hash &hash)
static acolorhist_item * pam_acolorhashtoacolorhist (const acolorhash_hash &acht, int maxacolors)
Variables
static const unsigned int HASH_SIZE = 20023u
Macro Definition Documentation
FS_SCALE
#define FS_SCALE 1024 /* Floyd-Steinberg scaling factor */
Referenced by RageSurfaceUtils::Palettize().
MAXCOLORS
#define MAXCOLORS 32767
Referenced by RageSurfaceUtils::Palettize().
PAM_ASSIGN
#define PAM_ASSIGN (p, red, grn, blu, alf)
Value:
do {                                                                       \
        (p)[0] = (red);                                                        \
        (p)[1] = (grn);                                                        \
        (p)[2] = (blu);                                                        \
        (p)[3] = (alf);                                                        \
    } while (0)
Referenced by mediancut(), and RageSurfaceUtils::Palettize().
PAM_DEPTH
#define PAM_DEPTH (p)
Value:
PAM_ASSIGN((p),                                                            \
               (uint8_t)table[PAM_GETR(p)],                                    \
               (uint8_t)table[PAM_GETG(p)],                                    \
               (uint8_t)table[PAM_GETB(p)],                                    \
               (uint8_t)table[PAM_GETA(p)])
Referenced by RageSurfaceUtils::Palettize().
PAM_EQUAL
#define PAM_EQUAL (p, q)
Value:
((p)[0] == (q)[0] && (p)[1] == (q)[1] && (p)[2] == (q)[2] &&               \
     (p)[3] == (q)[3])
Referenced by pam_computeacolorhash(), and pam_lookupacolor().
PAM_GETA
#define PAM_GETA (p) ((p)[3])
Referenced by mediancut(), and RageSurfaceUtils::Palettize().
PAM_GETB
#define PAM_GETB (p) ((p)[2])
Referenced by mediancut(), and RageSurfaceUtils::Palettize().
PAM_GETG
#define PAM_GETG (p) ((p)[1])
Referenced by mediancut(), and RageSurfaceUtils::Palettize().
PAM_GETR
#define PAM_GETR (p) ((p)[0])
Referenced by mediancut(), and RageSurfaceUtils::Palettize().
pam_hashapixel
#define pam_hashapixel (p)
Value:
(((unsigned)PAM_GETR(p) * 33023 + (unsigned)PAM_GETG(p) * 30013 +          \
      (unsigned)PAM_GETB(p) * 27011 + (unsigned)PAM_GETA(p) * 24007) %         \
     (unsigned)HASH_SIZE)
Referenced by pam_addtoacolorhash(), pam_computeacolorhash(), and pam_lookupacolor().
REP_AVERAGE_PIXELS
#define REP_AVERAGE_PIXELS
Typedef Documentation
acolorhist_list
typedef struct acolorhist_list_item* acolorhist_list
apixel
typedef uint8_t apixel[4]
box_vector
typedef struct box* box_vector
pixval
typedef uint8_t pixval
Function Documentation
compare_index_0()
static bool compare_index_0 (const acolorhist_item & ch1, const acolorhist_item & ch2) static
References acolorhist_item::acolor.
Referenced by mediancut().
compare_index_1()
static bool compare_index_1 (const acolorhist_item & ch1, const acolorhist_item & ch2) static
References acolorhist_item::acolor.
Referenced by mediancut().
compare_index_2()
static bool compare_index_2 (const acolorhist_item & ch1, const acolorhist_item & ch2) static
References acolorhist_item::acolor.
Referenced by mediancut().
compare_index_3()
static bool compare_index_3 (const acolorhist_item & ch1, const acolorhist_item & ch2) static
References acolorhist_item::acolor.
Referenced by mediancut().
CompareBySumDescending()
static bool CompareBySumDescending (const box & b1, const box & b2) static
References box::sum.
Referenced by mediancut().
mediancut()
static acolorhist_item * mediancut (acolorhist_item * achv, int colors, int sum, int maxval, int newcolors) static
References acolorhist_item::acolor, ASSERT, box::colors, compare_index_0(), compare_index_1(), compare_index_2(), compare_index_3(), CompareBySumDescending(), box::ind, max(), min(), PAM_ASSIGN, PAM_GETA, PAM_GETB, PAM_GETG, PAM_GETR, box::sum, and acolorhist_item::value.
Referenced by RageSurfaceUtils::Palettize().
pam_acolorhashtoacolorhist()
static acolorhist_item* pam_acolorhashtoacolorhist (const acolorhash_hash & acht, int maxacolors) static
References ASSERT, acolorhash_hash::hash, HASH_SIZE, and acolorhist_list_item::next.
Referenced by pam_computeacolorhist().
pam_addtoacolorhash()
static void pam_addtoacolorhash (acolorhash_hash & acht, const uint8_t acolorP[4], int value) static
References acolorhist_item::acolor, ASSERT, acolorhist_list_item::ch, acolorhash_hash::hash, acolorhist_list_item::next, pam_hashapixel, and acolorhist_item::value.
Referenced by RageSurfaceUtils::Palettize().
pam_computeacolorhash()
static bool pam_computeacolorhash (const RageSurface * src, int maxacolors, int * acolorsP, acolorhash_hash & hash) static
References acolorhist_item::acolor, ASSERT, RageSurfaceFormat::BytesPerPixel, acolorhist_list_item::ch, RageSurface::fmt, RageSurface::h, acolorhash_hash::hash, acolorhist_list_item::next, PAM_EQUAL, pam_hashapixel, RageSurface::pitch, RageSurface::pixels, acolorhist_item::value, and RageSurface::w.
Referenced by pam_computeacolorhist().
pam_computeacolorhist()
static acolorhist_item * pam_computeacolorhist (const RageSurface * src, int maxacolors, int * acolorsP) static
References pam_acolorhashtoacolorhist(), and pam_computeacolorhash().
Referenced by RageSurfaceUtils::Palettize().
pam_freeacolorhist()
static void pam_freeacolorhist (acolorhist_item * achv) static
Referenced by RageSurfaceUtils::Palettize().
pam_lookupacolor()
static int pam_lookupacolor (const acolorhash_hash & acht, const uint8_t acolorP[4]) static
References acolorhash_hash::hash, acolorhist_list_item::next, PAM_EQUAL, and pam_hashapixel.
Referenced by RageSurfaceUtils::Palettize().
Variable Documentation
HASH_SIZE
const unsigned int HASH_SIZE = 20023u static
Referenced by pam_acolorhashtoacolorhist(), and acolorhash_hash::~acolorhash_hash().