Etterna: ActorFrame.cpp File Reference
ActorFrame.cpp File Reference
#include "global.h"
#include "ActorFrame.h"
#include "ActorUtil.h"
#include "Foreach.h"
#include "LuaBinding.h"
#include "RageDisplay.h"
#include "RageUtil.h"
#include "ScreenDimensions.h"
#include "XmlFile.h"
#include "arch/Dialog/Dialog.h"
Classes
class LunaActorFrame
Allow Lua to have access to the ActorFrame.
Macros
#define CPY(x) this->x = cpy.x;
#define PropagateActorFrameCommand(cmd)
#define PropagateActorFrameCommand1Param(cmd, type)
Functions
REGISTER_ACTOR_CLASS_WITH_NAME (ActorFrameAutoDeleteChildren, ActorFrame)
static int IdenticalChildrenSingleApplier (lua_State *L)
static int IdenticalChildrenIndexLayer (lua_State *L)
static void CreateChildTable (lua_State *L, Actor *a)
static void AddToChildTable (lua_State *L, Actor *a)
PropagateActorFrameCommand (FinishTweening) PropagateActorFrameCommand1Param(SetZTestMode
ZTestMode PropagateActorFrameCommand1Param (SetZWrite, bool) PropagateActorFrameCommand1Param(HurryTweening
static bool CompareActorsByDrawOrder (const Actor *p1, const Actor *p2)
Macro Definition Documentation
CPY
#define CPY (x) this->x = cpy.x;
Referenced by ActorFrame::ActorFrame().
PropagateActorFrameCommand
#define PropagateActorFrameCommand (cmd)
Value:
void ActorFrame::cmd()                                                     \
    {                                                                          \
        Actor::cmd();                                                          \
                                                                               \
        /* set all sub-Actors */                                               \
        for (unsigned i = 0; i < m_SubActors.size(); i++)                      \
            m_SubActors[i]->cmd();                                             \
    }
PropagateActorFrameCommand1Param
#define PropagateActorFrameCommand1Param (cmd, type)
Value:
void ActorFrame::cmd(type f)                                               \
    {                                                                          \
        Actor::cmd(f);                                                         \
                                                                               \
        /* set all sub-Actors */                                               \
        for (unsigned i = 0; i < m_SubActors.size(); i++)                      \
            m_SubActors[i]->cmd(f);                                            \
    }
Function Documentation
AddToChildTable()
static void AddToChildTable (lua_State * L, Actor * a) static
References Actor::PushSelf().
Referenced by ActorFrame::PushChildrenTable(), and ActorFrame::PushChildTable().
CompareActorsByDrawOrder()
static bool CompareActorsByDrawOrder (const Actor * p1, const Actor * p2) static
References Actor::GetDrawOrder().
Referenced by ActorFrame::SortByDrawOrder().
CreateChildTable()
static void CreateChildTable (lua_State * L, Actor * a) static
References IdenticalChildrenIndexLayer(), and Actor::PushSelf().
Referenced by ActorFrame::PushChildrenTable(), and ActorFrame::PushChildTable().
IdenticalChildrenIndexLayer()
static int IdenticalChildrenIndexLayer (lua_State * L) static
References IdenticalChildrenSingleApplier().
Referenced by CreateChildTable().
IdenticalChildrenSingleApplier()
static int IdenticalChildrenSingleApplier (lua_State * L) static
Referenced by IdenticalChildrenIndexLayer().
PropagateActorFrameCommand()
PropagateActorFrameCommand (FinishTweening)
PropagateActorFrameCommand1Param()
ZTestMode PropagateActorFrameCommand1Param (SetZWrite , bool)
REGISTER_ACTOR_CLASS_WITH_NAME()
REGISTER_ACTOR_CLASS_WITH_NAME (ActorFrameAutoDeleteChildren , ActorFrame)