Etterna: pos_map_queue Class Reference
pos_map_queue Class Reference
#include <RageSoundPosMap.h>
Public Member Functions
pos_map_queue ()
~pos_map_queue ()
pos_map_queue (const pos_map_queue &cpy)
pos_map_queue & operator= (const pos_map_queue &rhs)
void Insert (int64_t iSourceFrame, int iFrames, int64_t iDestFrame, float fSourceToDestRatio=1.0f)
int64_t Search (int64_t iSourceFrame, bool *bApproximate) const
void Clear ()
bool IsEmpty () const
Private Attributes
pos_map_impl * m_pImpl
Constructor & Destructor Documentation
pos_map_queue() [1/2]
pos_map_queue::pos_map_queue ()
References m_pImpl.
~pos_map_queue()
pos_map_queue::~pos_map_queue ()
References m_pImpl.
pos_map_queue() [2/2]
pos_map_queue::pos_map_queue (const pos_map_queue & cpy)
References m_pImpl.
Member Function Documentation
Clear()
void pos_map_queue::Clear ()
References m_pImpl, and pos_map_impl::m_Queue.
Referenced by RageSound::SoundIsFinishedPlaying().
Insert()
void pos_map_queue::Insert (int64_t iSourceFrame, int iFrames, int64_t iDestFrame, float fSourceToDestRatio = 1.0f)
References pos_map_impl::Cleanup(), pos_map_t::m_fSourceToDestRatio, pos_map_t::m_iDestFrame, pos_map_t::m_iFrames, pos_map_t::m_iSourceFrame, m_pImpl, pos_map_impl::m_Queue, and pos_map_backlog_frames.
Referenced by RageSound::CommitPlayingPosition(), and RageSound::GetDataToPlay().
IsEmpty()
bool pos_map_queue::IsEmpty () const
References m_pImpl, and pos_map_impl::m_Queue.
Referenced by RageSound::GetPositionSeconds(), RageSound::GetSourceFrameFromHardwareFrame(), Search(), and RageSound::SoundIsFinishedPlaying().
operator=()
pos_map_queue & pos_map_queue::operator= (const pos_map_queue & rhs)
References m_pImpl.
Search()
int64_t pos_map_queue::Search (int64_t iSourceFrame, bool * bApproximate) const
References FOREACHL_CONST, RageTimer::GetDeltaTime(), I64F, IsEmpty(), LOG, pos_map_t::m_fSourceToDestRatio, pos_map_t::m_iDestFrame, pos_map_t::m_iFrames, pos_map_t::m_iSourceFrame, m_pImpl, pos_map_impl::m_Queue, RageTimer::PeekDeltaTime(), and RageLog::Trace().
Referenced by RageSound::GetSourceFrameFromHardwareFrame().
Member Data Documentation
m_pImpl
pos_map_impl* pos_map_queue::m_pImpl private
Referenced by Clear(), Insert(), IsEmpty(), operator=(), pos_map_queue(), Search(), and ~pos_map_queue().
The documentation for this class was generated from the following files:
RageSoundPosMap.h
RageSoundPosMap.cpp