Etterna: Luna< Type > Class Template Reference
Luna< Type > Class Template Reference
Allow the binding of Lua to various classes.
#include <LuaBinding.h>
Inherits LuaBinding.
Classes
struct RegType
Public Member Functions
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Static Public Attributes
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types
using T = Type
using binding_t = int(T *, lua_State *)
Protected Member Functions
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Private Member Functions
static int thunk (Lua *L)
static int tostring_T (lua_State *L)
Private Attributes
std::vector< RegType > m_aMethods
Additional Inherited Members
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
template<typename Type>
class Luna< Type >
Allow the binding of Lua to various classes.
Member Typedef Documentation
binding_t
template<typename Type> using Luna< Type >::binding_t = int(T*, lua_State*) protected
T
template<typename Type> using Luna< Type >::T = Type protected
Member Function Documentation
AddMethod()
template<typename Type> void Luna< Type >::AddMethod (std::string const & regName, int(*)(T *p, lua_State *L) pFunc) inline protected
check()
template<typename Type> static T* Luna< Type >::check (lua_State * L, int narg, bool bIsSelf = false) inline static
Referenced by LunaProfile::AddScreenshot(), LunaActorMultiTexture::AddTexture(), LunaSongManager::GetExtraStageInfo(), LunaGameManager::GetFirstStepsTypeForGame(), LunaProfile::GetHighScoreList(), LunaSongManager::GetSongFromSteps(), LunaProfile::GetSongNumTimesPlayed(), LunaProfile::HasPassedAnyStepsInSong(), LunaPlayerOptions::IsEasierForSongAndSteps(), LunaBanner::LoadCardFromCharacter(), LunaFadingBanner::LoadCardFromCharacter(), LunaBanner::LoadFromSong(), LunaFadingBanner::LoadFromSong(), LunaPercentageDisplay::LoadFromStats(), LunaBanner::LoadIconFromCharacter(), LunaFadingBanner::LoadIconFromCharacter(), LunaScreenSelectMusic::PlayReplay(), LunaMusicWheel::SelectSong(), LunaComboGraph::Set(), LunaGraphDisplay::Set(), LunaPlayer::SetActorWithComboPosition(), LunaPlayer::SetActorWithJudgmentPosition(), LunaGameState::SetCurrentSong(), LunaGameState::SetCurrentSteps(), LunaGameState::SetCurrentStyle(), LunaActor::SetFakeParent(), LunaGrooveRadar::SetFromRadarValues(), LunaTextBanner::SetFromSong(), LunaBPMDisplay::SetFromSong(), LunaDifficultyIcon::SetFromSteps(), LunaStepsDisplay::SetFromSteps(), LunaBPMDisplay::SetFromSteps(), LunaGameState::SetPreferredSong(), LunaActorMultiTexture::SetSizeFromTexture(), LunaActorProxy::SetTarget(), LunaActorMultiVertex::SetTexture(), LunaSprite::SetTexture(), LunaScreenSelectMusic::ShowEvalScreenForScore(), LunaSongManager::SongToPreferredSortSectionName(), Luna< GameSoundManager >::thunk(), Luna< GameSoundManager >::tostring_T(), and LunaSongManager::WasLoadedFromAdditionalSongs().
get()
template<typename Type> static T* Luna< Type >::get (lua_State * L, int narg) inline static
GetBaseClassName()
template<typename Type> const std::string& Luna< Type >::GetBaseClassName () const inline override virtual
Implements LuaBinding.
GetClassName()
template<typename Type> const std::string& Luna< Type >::GetClassName () const inline override virtual
Implements LuaBinding.
PushObject()
template<typename Type> static void Luna< Type >::PushObject (Lua * L, const std::string & sDerivedClassName, T * p) static
Register()
template<typename Type> void Luna< Type >::Register (Lua * L, int iMethods, int iMetatable) inline override protected virtual
Implements LuaBinding.
thunk()
template<typename Type> static int Luna< Type >::thunk (Lua * L) inline static private
Referenced by Luna< GameSoundManager >::Register().
tostring_T()
template<typename Type> static int Luna< Type >::tostring_T (lua_State * L) inline static private
Referenced by Luna< GameSoundManager >::Register().
Member Data Documentation
m_aMethods
template<typename Type> std::vector<RegType> Luna< Type >::m_aMethods private
Referenced by Luna< GameSoundManager >::AddMethod(), and Luna< GameSoundManager >::Register().
m_sBaseClassName
template<typename Type> std::string Luna< Type >::m_sBaseClassName static
Referenced by Luna< GameSoundManager >::GetBaseClassName().
m_sClassName
template<typename Type> std::string Luna< Type >::m_sClassName static
Referenced by Luna< GameSoundManager >::GetClassName().
The documentation for this class was generated from the following file:
LuaBinding.h