Etterna: InputHandler_MacOSX_HID.cpp File Reference
InputHandler_MacOSX_HID.cpp File Reference
#include "InputHandler_MacOSX_HID.h"
#include "Foreach.h"
#include "InputFilter.h"
#include "PrefsManager.h"
#include "RageLog.h"
#include "archutils/Darwin/DarwinThreadHelpers.h"
#include "archutils/Darwin/JoystickDevice.h"
#include "archutils/Darwin/KeyboardDevice.h"
#include "archutils/Darwin/MouseDevice.h"
#include "archutils/Darwin/PumpDevice.h"
#include "global.h"
#include <Carbon/Carbon.h>
#include <IOKit/IOMessage.h>
Macros
#define OTHER(n) (KEY_OTHER_0 + (n))
Functions
REGISTER_INPUT_HANDLER_CLASS2 (HID, MacOSX_HID)
static void RunLoopStarted (CFRunLoopObserverRef o, CFRunLoopActivity a, void *sem)
static CFDictionaryRef GetMatchingDictionary (int usagePage, int usage)
static HIDDevice * MakeDevice (InputDevice id)
static wchar_t KeyCodeToChar (CGKeyCode keyCode, unsigned int modifierFlags)
Macro Definition Documentation
OTHER
#define OTHER (n) (KEY_OTHER_0 + (n))
Referenced by InputHandler_MacOSX_HID::GetDeviceSpecificInputString().
Function Documentation
GetMatchingDictionary()
static CFDictionaryRef GetMatchingDictionary (int usagePage, int usage) static
References FAIL_M.
Referenced by InputHandler_MacOSX_HID::AddDevices().
KeyCodeToChar()
static wchar_t KeyCodeToChar (CGKeyCode keyCode, unsigned int modifierFlags) static
Referenced by InputHandler_MacOSX_HID::DeviceButtonToChar().
MakeDevice()
static HIDDevice* MakeDevice (InputDevice id) static
References DEVICE_KEYBOARD, DEVICE_MOUSE, IsJoystick(), and IsPump().
Referenced by InputHandler_MacOSX_HID::AddDevices().
REGISTER_INPUT_HANDLER_CLASS2()
REGISTER_INPUT_HANDLER_CLASS2 (HID , MacOSX_HID)
RunLoopStarted()
static void RunLoopStarted (CFRunLoopObserverRef o, CFRunLoopActivity a, void * sem) static
Referenced by InputHandler_MacOSX_HID::Run().