Etterna: RageDisplay_Legacy Class Reference
RageDisplay_Legacy Class Reference
#include <RageDisplay_OGL.h>
Public Member Functions
RageDisplay_Legacy ()
~RageDisplay_Legacy () override
RString Init (const VideoModeParams &p, bool bAllowUnacceleratedRenderer) override
RString GetApiDescription () const override
void GetDisplayResolutions (DisplayResolutions &out) const override
void ResolutionChanged () override
const RagePixelFormatDesc * GetPixelFormatDesc (RagePixelFormat pf) const override
bool SupportsThreadedRendering () override
void BeginConcurrentRenderingMainThread () override
void EndConcurrentRenderingMainThread () override
void BeginConcurrentRendering () override
void EndConcurrentRendering () override
bool BeginFrame () override
void EndFrame () override
const VideoModeParams * GetActualVideoModeParams () const override
void SetBlendMode (BlendMode mode) override
bool SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime=false) override
bool SupportsPerVertexMatrixScale () override
unsigned CreateTexture (RagePixelFormat pixfmt, RageSurface *img, bool bGenerateMipMaps) override
void UpdateTexture (unsigned iTexHandle, RageSurface *img, int xoffset, int yoffset, int width, int height) override
void DeleteTexture (unsigned iTexHandle) override
RageSurface * GetTexture (unsigned iTexture) override
RageTextureLock * CreateTextureLock () override
void ClearAllTextures () override
int GetNumTextureUnits () override
void SetTexture (TextureUnit tu, unsigned iTexture) override
void SetTextureMode (TextureUnit tu, TextureMode tm) override
void SetTextureWrapping (TextureUnit tu, bool b) override
int GetMaxTextureSize () const override
void SetTextureFiltering (TextureUnit tu, bool b) override
void SetEffectMode (EffectMode effect) override
bool IsEffectModeSupported (EffectMode effect) override
bool SupportsRenderToTexture () const
unsigned CreateRenderTarget (const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut) override
unsigned GetRenderTarget () override
void SetRenderTarget (unsigned iHandle, bool bPreserveTexture) override
bool IsZWriteEnabled () const override
bool IsZTestEnabled () const override
void SetZWrite (bool b) override
void SetZBias (float f) override
void SetZTestMode (ZTestMode mode) override
void ClearZBuffer () override
void SetCullMode (CullMode mode) override
void SetAlphaTest (bool b) override
void SetMaterial (const RageColor &emissive, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, float shininess) override
void SetLighting (bool b) override
void SetLightOff (int index) override
void SetLightDirectional (int index, const RageColor &ambient, const RageColor &diffuse, const RageColor &specular, const RageVector3 &dir) override
void SetSphereEnvironmentMapping (TextureUnit tu, bool b) override
void SetCelShaded (int stage) override
bool IsD3DInternal () override
RageCompiledGeometry * CreateCompiledGeometry () override
void DeleteCompiledGeometry (RageCompiledGeometry *p) override
void SetPolygonMode (PolygonMode pm) override
void SetLineWidth (float fWidth) override
RString GetTextureDiagnostics (unsigned id) const override
Public Member Functions inherited from RageDisplay
RageDisplay ()
virtual ~RageDisplay ()
void SetPresentTime (std::chrono::nanoseconds presentTime)
RString SetVideoMode (VideoModeParams p, bool &bNeedReloadTextures)
bool IsD3D ()
bool IsWindowed ()
bool SupportsRenderToTexture () const
void DrawQuads (const RageSpriteVertex v[], int iNumVerts)
void DrawQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawFan (const RageSpriteVertex v[], int iNumVerts)
void DrawStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawTriangles (const RageSpriteVertex v[], int iNumVerts)
void DrawCompiledGeometry (const RageCompiledGeometry *p, int iMeshIndex, const vector< msMesh > &vMeshes)
void DrawLineStrip (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void DrawSymmetricQuadStrip (const RageSpriteVertex v[], int iNumVerts)
void DrawCircle (const RageSpriteVertex &v, float radius)
void DrawQuad (const RageSpriteVertex v[])
bool SaveScreenshot (const RString &sPath, GraphicsFileFormat format)
bool IsPredictiveFrameLimit () const
int GetFPS () const
int GetVPF () const
int GetCumFPS () const
virtual void ResetStats ()
virtual void ProcessStatsOnFlip ()
virtual RString GetStats () const
void StatsAddVerts (int iNumVertsRendered)
void PushMatrix ()
void PopMatrix ()
void Translate (float x, float y, float z)
void TranslateWorld (float x, float y, float z)
void Scale (float x, float y, float z)
void RotateX (float deg)
void RotateY (float deg)
void RotateZ (float deg)
void SkewX (float fAmount)
void SkewY (float fAmount)
void MultMatrix (const RageMatrix &f)
void PostMultMatrix (const RageMatrix &f)
void PreMultMatrix (const RageMatrix &f)
void LoadIdentity ()
void TexturePushMatrix ()
void TexturePopMatrix ()
void TextureTranslate (float x, float y)
void TextureTranslate (const RageVector2 &v)
void CameraPushMatrix ()
void CameraPopMatrix ()
void LoadMenuPerspective (float fFOVDegrees, float fWidth, float fHeight, float fVanishPointX, float fVanishPointY)
void LoadLookAt (float fov, const RageVector3 &Eye, const RageVector3 &At, const RageVector3 &Up)
void CenteringPushMatrix ()
void CenteringPopMatrix ()
void ChangeCentering (int trans_x, int trans_y, int add_width, int add_height)
RageSurface * CreateSurfaceFromPixfmt (RagePixelFormat pixfmt, void *pixels, int width, int height, int pitch)
RagePixelFormat FindPixelFormat (int bpp, unsigned Rmask, unsigned Gmask, unsigned Bmask, unsigned Amask, bool realtime=false)
void PushSelf (lua_State *L)
Protected Member Functions
void DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override
void DrawCompiledGeometryInternal (const RageCompiledGeometry *p, int iMeshIndex) override
void DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth) override
void DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override
RString TryVideoMode (const VideoModeParams &p, bool &bNewDeviceOut) override
RageSurface * CreateScreenshot () override
RagePixelFormat GetImgPixelFormat (RageSurface *&img, bool &FreeImg, int width, int height, bool bPalettedTexture)
bool SupportsSurfaceFormat (RagePixelFormat pixfmt)
void SendCurrentMatrices ()
Protected Member Functions inherited from RageDisplay
virtual void DrawCircleInternal (const RageSpriteVertex &v, float radius)
void DrawPolyLine (const RageSpriteVertex &p1, const RageSpriteVertex &p2, float LineWidth)
void DrawPolyLines (const RageSpriteVertex v[], int iNumVerts, float LineWidth)
void SetDefaultRenderStates ()
RageMatrix GetPerspectiveMatrix (float fovy, float aspect, float zNear, float zFar)
virtual RageMatrix GetOrthoMatrix (float l, float r, float b, float t, float zn, float zf)
virtual RageMatrix GetFrustumMatrix (float l, float r, float b, float t, float zn, float zf)
RageMatrix GetCenteringMatrix (float fTranslateX, float fTranslateY, float fAddWidth, float fAddHeight)
void UpdateCentering ()
const RageMatrix * GetCentering () const
const RageMatrix * GetProjectionTop () const
const RageMatrix * GetViewTop () const
const RageMatrix * GetWorldTop () const
const RageMatrix * GetTextureTop () const
void FrameLimitBeforeVsync ()
void FrameLimitAfterVsync (int iFPS)
Additional Inherited Members
Public Types inherited from RageDisplay
enum GraphicsFileFormat { SAVE_LOSSLESS, SAVE_LOSSLESS_SENSIBLE, SAVE_LOSSY_LOW_QUAL, SAVE_LOSSY_HIGH_QUAL }
Constructor & Destructor Documentation
RageDisplay_Legacy()
RageDisplay_Legacy::RageDisplay_Legacy ()
References FixLittleEndian(), g_bTextureMatrixShader, RageDisplay_Legacy_Helpers::Init(), LOG, RageLog::MapLog(), and RageLog::Trace().
~RageDisplay_Legacy()
RageDisplay_Legacy::~RageDisplay_Legacy () override
References g_pWind.
Member Function Documentation
BeginConcurrentRendering()
void RageDisplay_Legacy::BeginConcurrentRendering () override virtual
Reimplemented from RageDisplay.
References LowLevelWindow::BeginConcurrentRendering(), and RageDisplay::BeginConcurrentRendering().
BeginConcurrentRenderingMainThread()
void RageDisplay_Legacy::BeginConcurrentRenderingMainThread () override virtual
Reimplemented from RageDisplay.
References LowLevelWindow::BeginConcurrentRenderingMainThread().
BeginFrame()
bool RageDisplay_Legacy::BeginFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::BeginFrame(), and LowLevelWindow::GetActualVideoModeParams().
ClearAllTextures()
void RageDisplay_Legacy::ClearAllTextures () override virtual
Implements RageDisplay.
References FOREACH_ENUM.
ClearZBuffer()
void RageDisplay_Legacy::ClearZBuffer () override virtual
Implements RageDisplay.
CreateCompiledGeometry()
RageCompiledGeometry * RageDisplay_Legacy::CreateCompiledGeometry () override virtual
Implements RageDisplay.
CreateRenderTarget()
unsigned RageDisplay_Legacy::CreateRenderTarget (const RenderTargetParam & param, int & iTextureWidthOut, int & iTextureHeightOut) override virtual
Reimplemented from RageDisplay.
References ASSERT, RenderTarget::Create(), LowLevelWindow::CreateRenderTarget(), g_mapRenderTargets, and RenderTarget::GetTexture().
CreateScreenshot()
RageSurface * RageDisplay_Legacy::CreateScreenshot () override protected virtual
Implements RageDisplay.
References RageDisplay::RagePixelFormatDesc::bpp, CreateSurface(), DebugAssertNoGLError, DebugFlushGLErrors, RageSurfaceUtils::FlipVertically(), LowLevelWindow::GetActualVideoModeParams(), RageDisplay::RagePixelFormatDesc::masks, RageSurface::pixels, and RagePixelFormat_RGBA8.
CreateTexture()
unsigned RageDisplay_Legacy::CreateTexture (RagePixelFormat pixfmt, RageSurface * img, bool bGenerateMipMaps) override virtual
Implements RageDisplay.
References RageSurfaceColor::a, ASSERT, RageSurfaceColor::b, RageSurfaceFormat::BytesPerPixel, RageSurfacePalette::colors, DebugAssertNoGLError, DebugFlushGLErrors, f, RageSurface::fmt, GLPixFmtInfo_t::format, RageSurfaceColor::g, g_GLPixFmtInfo, g_gluVersion, LowLevelWindow::GetActualVideoModeParams(), GL_TEXTURE_INDEX_SIZE_EXT, RageDisplay_Legacy_Helpers::GLToString(), RageSurface::h, GLPixFmtInfo_t::internalfmt, LOG, RageSurfacePalette::ncolors, NUM_RagePixelFormat, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, power_of_two(), RageSurfaceColor::r, RagePixelFormat_BGR8, RagePixelFormat_Invalid, RagePixelFormat_PAL, RagePixelFormat_RGB8, RagePixelFormat_RGBA8, SetPixelMapForSurface(), SetTextureUnit(), TextureUnit_1, RageException::Throw(), RageLog::Trace(), GLPixFmtInfo_t::type, and RageSurface::w.
CreateTextureLock()
RageTextureLock * RageDisplay_Legacy::CreateTextureLock () override virtual
Reimplemented from RageDisplay.
DeleteCompiledGeometry()
void RageDisplay_Legacy::DeleteCompiledGeometry (RageCompiledGeometry * p) override virtual
Implements RageDisplay.
DeleteTexture()
void RageDisplay_Legacy::DeleteTexture (unsigned iTexHandle) override virtual
Implements RageDisplay.
References DebugAssertNoGLError, DebugFlushGLErrors, and g_mapRenderTargets.
DrawCompiledGeometryInternal()
void RageDisplay_Legacy::DrawCompiledGeometryInternal (const RageCompiledGeometry * p, int iMeshIndex) override protected virtual
Implements RageDisplay.
References RageCompiledGeometry::Draw(), and TurnOffHardwareVBO().
DrawFanInternal()
void RageDisplay_Legacy::DrawFanInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References SetupVertices(), and TurnOffHardwareVBO().
DrawLineStripInternal()
void RageDisplay_Legacy::DrawLineStripInternal (const RageSpriteVertex v[], int iNumVerts, float LineWidth) override protected virtual
Reimplemented from RageDisplay.
References clamp, RageDisplay::DrawLineStripInternal(), g_line_range, g_point_range, LowLevelWindow::GetActualVideoModeParams(), RageMatrix::m, and SetupVertices().
DrawQuadsInternal()
void RageDisplay_Legacy::DrawQuadsInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References SetupVertices(), and TurnOffHardwareVBO().
DrawQuadStripInternal()
void RageDisplay_Legacy::DrawQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References SetupVertices(), and TurnOffHardwareVBO().
DrawStripInternal()
void RageDisplay_Legacy::DrawStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References SetupVertices(), and TurnOffHardwareVBO().
DrawSymmetricQuadStripInternal()
void RageDisplay_Legacy::DrawSymmetricQuadStripInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References max(), SetupVertices(), and TurnOffHardwareVBO().
DrawTrianglesInternal()
void RageDisplay_Legacy::DrawTrianglesInternal (const RageSpriteVertex v[], int iNumVerts) override protected virtual
Implements RageDisplay.
References SetupVertices(), and TurnOffHardwareVBO().
EndConcurrentRendering()
void RageDisplay_Legacy::EndConcurrentRendering () override virtual
Reimplemented from RageDisplay.
References LowLevelWindow::EndConcurrentRendering().
EndConcurrentRenderingMainThread()
void RageDisplay_Legacy::EndConcurrentRenderingMainThread () override virtual
Reimplemented from RageDisplay.
References LowLevelWindow::EndConcurrentRenderingMainThread().
EndFrame()
void RageDisplay_Legacy::EndFrame () override virtual
Reimplemented from RageDisplay.
References RageDisplay::EndFrame(), LowLevelWindow::SwapBuffers(), and LowLevelWindow::Update().
GetActualVideoModeParams()
const VideoModeParams * RageDisplay_Legacy::GetActualVideoModeParams () const override virtual
Implements RageDisplay.
References LowLevelWindow::GetActualVideoModeParams().
GetApiDescription()
RString RageDisplay_Legacy::GetApiDescription () const inline override virtual
Implements RageDisplay.
GetDisplayResolutions()
void RageDisplay_Legacy::GetDisplayResolutions (DisplayResolutions & out) const override virtual
Implements RageDisplay.
References LowLevelWindow::GetDisplayResolutions().
GetImgPixelFormat()
RagePixelFormat RageDisplay_Legacy::GetImgPixelFormat (RageSurface *& img, bool & FreeImg, int width, int height, bool bPalettedTexture) protected
References RageSurfaceFormat::Amask, ASSERT, RageSurfaceFormat::BitsPerPixel, RageSurfaceUtils::Blit(), RageSurfaceFormat::Bmask, RageDisplay::RagePixelFormatDesc::bpp, RageSurfaceFormat::BytesPerPixel, CreateSurface(), DISPLAY, RageSurface::fmt, g_bColorIndexTableWorks, RageDisplay::GetPixelFormatDesc(), RageSurfaceFormat::Gmask, RageSurface::h, RageDisplay::RagePixelFormatDesc::masks, RagePixelFormat_Invalid, RagePixelFormat_RGBA8, RageSurfaceFormat::Rmask, and RageSurface::w.
GetMaxTextureSize()
int RageDisplay_Legacy::GetMaxTextureSize () const override virtual
Implements RageDisplay.
GetNumTextureUnits()
int RageDisplay_Legacy::GetNumTextureUnits () override virtual
Implements RageDisplay.
References g_iMaxTextureUnits.
GetPixelFormatDesc()
const RageDisplay::RagePixelFormatDesc * RageDisplay_Legacy::GetPixelFormatDesc (RagePixelFormat pf) const override virtual
Implements RageDisplay.
References ASSERT, and NUM_RagePixelFormat.
GetRenderTarget()
unsigned RageDisplay_Legacy::GetRenderTarget () override virtual
Reimplemented from RageDisplay.
References g_mapRenderTargets.
GetTexture()
RageSurface * RageDisplay_Legacy::GetTexture (unsigned iTexture) override virtual
Reimplemented from RageDisplay.
References AssertNoGLError, RageDisplay::RagePixelFormatDesc::bpp, CreateSurface(), FlushGLErrors, g_GLPixFmtInfo, RageDisplay::RagePixelFormatDesc::masks, RageSurface::pixels, RagePixelFormat_RGB8, and RagePixelFormat_RGBA8.
GetTextureDiagnostics()
RString RageDisplay_Legacy::GetTextureDiagnostics (unsigned id) const override virtual
Reimplemented from RageDisplay.
Init()
RString RageDisplay_Legacy::Init (const VideoModeParams & p, bool bAllowUnacceleratedRenderer) override virtual
Implements RageDisplay.
References LowLevelWindow::Create(), g_iMaxTextureUnits, g_line_range, g_point_range, LocalizedString::GetValue(), GLDIRECT_IS_NOT_COMPATIBLE, RageLog::Info(), LowLevelWindow::IsSoftwareRenderer(), Rage::join(), LOG, LowLevelWindow::LogDebugInformation(), OBTAIN_AN_UPDATED_VIDEO_DRIVER, split(), ssprintf(), and RageLog::Warn().
IsD3DInternal()
bool RageDisplay_Legacy::IsD3DInternal () override virtual
Reimplemented from RageDisplay.
IsEffectModeSupported()
bool RageDisplay_Legacy::IsEffectModeSupported (EffectMode effect) override virtual
Reimplemented from RageDisplay.
References EffectMode_ColorBurn, EffectMode_ColorDodge, EffectMode_HardMix, EffectMode_Normal, EffectMode_Overlay, EffectMode_Screen, EffectMode_Unpremultiply, EffectMode_VividLight, EffectMode_YUYV422, g_bColorBurnShader, g_bColorDodgeShader, g_bUnpremultiplyShader, g_bVividLightShader, g_hHardMixShader, g_hOverlayShader, g_hScreenShader, and g_hYUYV422Shader.
IsZTestEnabled()
bool RageDisplay_Legacy::IsZTestEnabled () const override virtual
Implements RageDisplay.
IsZWriteEnabled()
bool RageDisplay_Legacy::IsZWriteEnabled () const override virtual
Implements RageDisplay.
ResolutionChanged()
void RageDisplay_Legacy::ResolutionChanged () override virtual
Reimplemented from RageDisplay.
References RageDisplay::ResolutionChanged().
SendCurrentMatrices()
void RageDisplay_Legacy::SendCurrentMatrices () protected
References g_bInvertY, RageMatrixMultiply(), and RageMatrixScale().
SetAlphaTest()
void RageDisplay_Legacy::SetAlphaTest (bool b) override virtual
Implements RageDisplay.
SetBlendMode()
void RageDisplay_Legacy::SetBlendMode (BlendMode mode) override virtual
Implements RageDisplay.
References BLEND_ADD, BLEND_ALPHA_KNOCK_OUT, BLEND_ALPHA_MASK, BLEND_ALPHA_MULTIPLY, BLEND_COPY_SRC, BLEND_INVERT_DEST, BLEND_MODULATE, BLEND_NO_EFFECT, BLEND_NORMAL, BLEND_SUBTRACT, BLEND_WEIGHTED_MULTIPLY, and DEFAULT_FAIL.
SetCelShaded()
void RageDisplay_Legacy::SetCelShaded (int stage) override virtual
Implements RageDisplay.
References g_gCelShader, and g_gShellShader.
SetCullMode()
void RageDisplay_Legacy::SetCullMode (CullMode mode) override virtual
Implements RageDisplay.
References CULL_BACK, CULL_FRONT, CULL_NONE, FAIL_M, and ssprintf().
SetEffectMode()
void RageDisplay_Legacy::SetEffectMode (EffectMode effect) override virtual
Reimplemented from RageDisplay.
References DebugAssertNoGLError, DebugFlushGLErrors, EffectMode_ColorBurn, EffectMode_ColorDodge, EffectMode_HardMix, EffectMode_Normal, EffectMode_Overlay, EffectMode_Screen, EffectMode_Unpremultiply, EffectMode_VividLight, EffectMode_YUYV422, g_bColorBurnShader, g_bColorDodgeShader, g_bUnpremultiplyShader, g_bVividLightShader, g_hHardMixShader, g_hOverlayShader, g_hScreenShader, and g_hYUYV422Shader.
SetLightDirectional()
void RageDisplay_Legacy::SetLightDirectional (int index, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, const RageVector3 & dir) override virtual
Implements RageDisplay.
References RageVector3::x, RageVector3::y, and RageVector3::z.
SetLighting()
void RageDisplay_Legacy::SetLighting (bool b) override virtual
Implements RageDisplay.
SetLightOff()
void RageDisplay_Legacy::SetLightOff (int index) override virtual
Implements RageDisplay.
SetLineWidth()
void RageDisplay_Legacy::SetLineWidth (float fWidth) override virtual
Reimplemented from RageDisplay.
SetMaterial()
void RageDisplay_Legacy::SetMaterial (const RageColor & emissive, const RageColor & ambient, const RageColor & diffuse, const RageColor & specular, float shininess) override virtual
Implements RageDisplay.
References RageColor::b, RageColor::g, and RageColor::r.
SetPolygonMode()
void RageDisplay_Legacy::SetPolygonMode (PolygonMode pm) override virtual
Reimplemented from RageDisplay.
References FAIL_M, POLYGON_FILL, POLYGON_LINE, and ssprintf().
SetRenderTarget()
void RageDisplay_Legacy::SetRenderTarget (unsigned iHandle, bool bPreserveTexture) override virtual
Reimplemented from RageDisplay.
References ASSERT, RageDisplay::CameraPopMatrix(), RageDisplay::CameraPushMatrix(), DISPLAY, RenderTarget::FinishRenderingTo(), g_bInvertY, g_mapRenderTargets, and LowLevelWindow::GetActualVideoModeParams().
SetSphereEnvironmentMapping()
void RageDisplay_Legacy::SetSphereEnvironmentMapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References SetTextureUnit().
SetTexture()
void RageDisplay_Legacy::SetTexture (TextureUnit tu, unsigned iTexture) override virtual
Implements RageDisplay.
References SetTextureUnit().
SetTextureFiltering()
void RageDisplay_Legacy::SetTextureFiltering (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References LowLevelWindow::GetActualVideoModeParams().
SetTextureMode()
void RageDisplay_Legacy::SetTextureMode (TextureUnit tu, TextureMode tm) override virtual
Implements RageDisplay.
References SetTextureUnit(), TextureMode_Add, TextureMode_Glow, and TextureMode_Modulate.
SetTextureWrapping()
void RageDisplay_Legacy::SetTextureWrapping (TextureUnit tu, bool b) override virtual
Implements RageDisplay.
References SetTextureUnit().
SetZBias()
void RageDisplay_Legacy::SetZBias (float f) override virtual
Implements RageDisplay.
References SCALE.
SetZTestMode()
void RageDisplay_Legacy::SetZTestMode (ZTestMode mode) override virtual
Implements RageDisplay.
References FAIL_M, ssprintf(), ZTEST_OFF, ZTEST_WRITE_ON_FAIL, and ZTEST_WRITE_ON_PASS.
SetZWrite()
void RageDisplay_Legacy::SetZWrite (bool b) override virtual
Implements RageDisplay.
SupportsPerVertexMatrixScale()
bool RageDisplay_Legacy::SupportsPerVertexMatrixScale () override virtual
Implements RageDisplay.
References g_bTextureMatrixShader.
SupportsRenderToTexture()
bool RageDisplay_Legacy::SupportsRenderToTexture () const
References LowLevelWindow::SupportsRenderToTexture().
SupportsSurfaceFormat()
bool RageDisplay_Legacy::SupportsSurfaceFormat (RagePixelFormat pixfmt) protected
References g_bReversePackedPixelsWorks, and g_GLPixFmtInfo.
SupportsTextureFormat()
bool RageDisplay_Legacy::SupportsTextureFormat (RagePixelFormat pixfmt, bool realtime = false) override virtual
Implements RageDisplay.
References g_GLPixFmtInfo.
SupportsThreadedRendering()
bool RageDisplay_Legacy::SupportsThreadedRendering () override virtual
Reimplemented from RageDisplay.
References LowLevelWindow::SupportsThreadedRendering().
TryVideoMode()
RString RageDisplay_Legacy::TryVideoMode (const VideoModeParams & p, bool & bNewDeviceOut) override protected virtual
Implements RageDisplay.
References FOREACHM, g_mapRenderTargets, InitShaders(), InvalidateObjects(), RageTextureManager::InvalidateTextures(), SetupExtensions(), TEXTUREMAN, LowLevelWindow::TryVideoMode(), and VideoModeParams::vsync.
UpdateTexture()
void RageDisplay_Legacy::UpdateTexture (unsigned iTexHandle, RageSurface * img, int xoffset, int yoffset, int width, int height) override virtual
Implements RageDisplay.
References RageSurfaceFormat::BytesPerPixel, RageSurface::fmt, GLPixFmtInfo_t::format, g_GLPixFmtInfo, RageSurfaceFormat::palette, RageSurface::pitch, RageSurface::pixels, SetPixelMapForSurface(), and GLPixFmtInfo_t::type.
The documentation for this class was generated from the following files:
RageDisplay_OGL.h
RageDisplay_OGL.cpp