Etterna: RageFileObjInflate Class Reference
RageFileObjInflate Class Reference
#include <RageFileDriverDeflate.h>
Public Member Functions
RageFileObjInflate (RageFileBasic *pFile, int iUncompressedSize)
RageFileObjInflate (const RageFileObjInflate &cpy)
~RageFileObjInflate () override
int ReadInternal (void *pBuffer, size_t iBytes) override
int WriteInternal (const void *, size_t) override
int SeekInternal (int iOffset) override
int GetFileSize () const override
int GetFD () override
RageFileObjInflate * Copy () const override
void DeleteFileWhenFinished ()
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
RString GetDisplayPath () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Private Types
enum { INBUFSIZE = 1024 * 4 }
Private Attributes
int m_iUncompressedSize
RageFileBasic * m_pFile
int m_iFilePos
bool m_bFileOwned
z_stream * m_pInflate
char decomp_buf [INBUFSIZE]
char * decomp_buf_ptr
int decomp_buf_avail
Additional Inherited Members
Protected Member Functions inherited from RageFileObj
virtual int FlushInternal ()
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes inherited from RageFileObj
RString m_sError
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
INBUFSIZE
Constructor & Destructor Documentation
RageFileObjInflate() [1/2]
RageFileObjInflate::RageFileObjInflate (RageFileBasic * pFile, int iUncompressedSize)
References decomp_buf, decomp_buf_avail, decomp_buf_ptr, m_bFileOwned, m_iFilePos, m_iUncompressedSize, m_pFile, m_pInflate, ssprintf(), RageException::Throw(), and WARN.
Referenced by Copy().
RageFileObjInflate() [2/2]
RageFileObjInflate::RageFileObjInflate (const RageFileObjInflate & cpy)
References RageFileBasic::Copy(), decomp_buf, decomp_buf_avail, decomp_buf_ptr, m_bFileOwned, m_iFilePos, m_iUncompressedSize, m_pFile, and m_pInflate.
~RageFileObjInflate()
RageFileObjInflate::~RageFileObjInflate () override
References m_bFileOwned, m_pFile, m_pInflate, ssprintf(), and WARN.
Member Function Documentation
Copy()
RageFileObjInflate * RageFileObjInflate::Copy () const override virtual
Reimplemented from RageFileObj.
References RageFileObjInflate().
DeleteFileWhenFinished()
void RageFileObjInflate::DeleteFileWhenFinished () inline
References m_bFileOwned.
Referenced by GunzipFile(), and RageFileDriverZip::Open().
GetFD()
int RageFileObjInflate::GetFD () inline override virtual
Reimplemented from RageFileObj.
References RageFileBasic::GetFD(), and m_pFile.
GetFileSize()
int RageFileObjInflate::GetFileSize () const inline override virtual
Implements RageFileObj.
References m_iUncompressedSize.
ReadInternal()
int RageFileObjInflate::ReadInternal (void * pBuffer, size_t iBytes) override virtual
Implements RageFileObj.
References ASSERT_M, decomp_buf, decomp_buf_avail, decomp_buf_ptr, RageFileBasic::GetError(), m_iFilePos, m_iUncompressedSize, m_pFile, m_pInflate, min(), RageFileBasic::Read(), RageFileObj::SetError(), ssprintf(), and WARN.
Referenced by SeekInternal().
SeekInternal()
int RageFileObjInflate::SeekInternal (int iOffset) override virtual
Reimplemented from RageFileObj.
References decomp_buf, decomp_buf_avail, decomp_buf_ptr, RageFileBasic::GetFileSize(), m_iFilePos, m_iUncompressedSize, m_pFile, m_pInflate, min(), ReadInternal(), and RageFileBasic::Seek().
WriteInternal()
int RageFileObjInflate::WriteInternal (const void * , size_t) inline override virtual
Implements RageFileObj.
References RageFileObj::SetError().
Member Data Documentation
decomp_buf
char RageFileObjInflate::decomp_buf[INBUFSIZE] private
Referenced by RageFileObjInflate(), ReadInternal(), and SeekInternal().
decomp_buf_avail
int RageFileObjInflate::decomp_buf_avail private
Referenced by RageFileObjInflate(), ReadInternal(), and SeekInternal().
decomp_buf_ptr
char * RageFileObjInflate::decomp_buf_ptr private
Referenced by RageFileObjInflate(), ReadInternal(), and SeekInternal().
m_bFileOwned
bool RageFileObjInflate::m_bFileOwned private
Referenced by DeleteFileWhenFinished(), RageFileObjInflate(), and ~RageFileObjInflate().
m_iFilePos
int RageFileObjInflate::m_iFilePos private
Referenced by RageFileObjInflate(), ReadInternal(), and SeekInternal().
m_iUncompressedSize
int RageFileObjInflate::m_iUncompressedSize private
Referenced by GetFileSize(), RageFileObjInflate(), ReadInternal(), and SeekInternal().
m_pFile
RageFileBasic* RageFileObjInflate::m_pFile private
Referenced by GetFD(), RageFileObjInflate(), ReadInternal(), SeekInternal(), and ~RageFileObjInflate().
m_pInflate
z_stream* RageFileObjInflate::m_pInflate private
Referenced by RageFileObjInflate(), ReadInternal(), SeekInternal(), and ~RageFileObjInflate().
The documentation for this class was generated from the following files:
RageFileDriverDeflate.h
RageFileDriverDeflate.cpp