Etterna: ScreenManagerUtil Namespace Reference
ScreenManagerUtil Namespace Reference
Utility functions for the ScreenManager.
Classes
struct LoadedScreen
Functions
void PushLoadedScreen (const LoadedScreen &ls)
bool ScreenIsPrepped (const RString &sScreenName)
bool GetPreppedScreen (const RString &sScreenName, LoadedScreen &ls)
void BeforeDeleteScreen ()
void AfterDeleteScreen ()
void GrabPreparedActors (vector< Actor *> &apOut)
void DeletePreparedScreens ()
Variables
Actor * g_pSharedBGA
RString m_sPreviousTopScreen
vector< LoadedScreen > g_ScreenStack
vector< Screen * > g_OverlayScreens
set< RString > g_setGroupedScreens
set< RString > g_setPersistantScreens
vector< LoadedScreen > g_vPreparedScreens
vector< Actor * > g_vPreparedBackgrounds
Detailed Description
Utility functions for the ScreenManager.
Function Documentation
AfterDeleteScreen()
void ScreenManagerUtil::AfterDeleteScreen ()
References SongManager::Cleanup(), RageTextureManager::DeleteCachedTextures(), SONGMAN, and TEXTUREMAN.
Referenced by DeletePreparedScreens(), ScreenManager::LoadDelayedScreen(), and ScreenManager::PopTopScreenInternal().
BeforeDeleteScreen()
void ScreenManagerUtil::BeforeDeleteScreen ()
References ScreenManager::ZeroNextUpdate().
Referenced by DeletePreparedScreens(), ScreenManager::LoadDelayedScreen(), and ScreenManager::PopTopScreenInternal().
DeletePreparedScreens()
void ScreenManagerUtil::DeletePreparedScreens ()
References AfterDeleteScreen(), BeforeDeleteScreen(), FOREACH, GrabPreparedActors(), and SAFE_DELETE.
Referenced by ScreenManager::LoadDelayedScreen(), ScreenManager::PopAllScreens(), and ScreenManager::~ScreenManager().
GetPreppedScreen()
bool ScreenManagerUtil::GetPreppedScreen (const RString & sScreenName, LoadedScreen & ls)
References FOREACH.
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), and ScreenManager::AddNewScreenToTop().
GrabPreparedActors()
void ScreenManagerUtil::GrabPreparedActors (vector< Actor *> & apOut)
References FOREACH.
Referenced by DeletePreparedScreens(), and ScreenManager::LoadDelayedScreen().
PushLoadedScreen()
void ScreenManagerUtil::PushLoadedScreen (const LoadedScreen & ls)
References Screen::BeginScreen(), Actor::GetName(), LOG, ScreenManagerUtil::LoadedScreen::m_pScreen, RageLog::MapLog(), ScreenManager::PostMessageToTopScreen(), ScreenManager::RefreshCreditsMessages(), SM_GainFocus, and RageLog::Trace().
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), and ScreenManager::AddNewScreenToTop().
ScreenIsPrepped()
bool ScreenManagerUtil::ScreenIsPrepped (const RString & sScreenName)
References FOREACH.
Referenced by LunaScreenManager::LunaScreenManager(), ScreenManager::PrepareScreen(), and LunaScreenManager::ScreenIsPrepped().
Variable Documentation
g_OverlayScreens
vector<Screen*> ScreenManagerUtil::g_OverlayScreens
Referenced by ScreenManager::Draw(), ScreenManager::Input(), ScreenManager::ReloadOverlayScreens(), ScreenManager::Update(), and ScreenManager::~ScreenManager().
g_pSharedBGA
Actor* ScreenManagerUtil::g_pSharedBGA
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), ScreenManager::Draw(), ScreenManager::PlaySharedBackgroundOffCommand(), ScreenManager::PrepareScreen(), ScreenManager::ScreenManager(), ScreenManager::ThemeChanged(), ScreenManager::Update(), and ScreenManager::~ScreenManager().
g_ScreenStack
vector<LoadedScreen> ScreenManagerUtil::g_ScreenStack
Referenced by ScreenManager::AddNewScreenToTop(), ScreenManager::AllowOperatorMenuButton(), ScreenManager::Draw(), ScreenManager::GetScreen(), ScreenManager::GetTopScreen(), ScreenManager::Input(), ScreenManager::IsStackedScreen(), ScreenManager::PopAllScreens(), ScreenManager::PopTopScreen(), ScreenManager::PopTopScreenInternal(), ScreenManager::Update(), and ScreenManager::~ScreenManager().
g_setGroupedScreens
set<RString> ScreenManagerUtil::g_setGroupedScreens
Referenced by ScreenManager::GroupScreen(), and ScreenManager::LoadDelayedScreen().
g_setPersistantScreens
set<RString> ScreenManagerUtil::g_setPersistantScreens
Referenced by ScreenManager::PersistantScreen(), and ScreenManager::PopTopScreenInternal().
g_vPreparedBackgrounds
vector<Actor*> ScreenManagerUtil::g_vPreparedBackgrounds
Referenced by ScreenManager::ActivatePreparedScreenAndBackground(), and ScreenManager::PrepareScreen().
g_vPreparedScreens
vector<LoadedScreen> ScreenManagerUtil::g_vPreparedScreens
Referenced by ScreenManager::PopTopScreenInternal(), and ScreenManager::PrepareScreen().
m_sPreviousTopScreen
RString ScreenManagerUtil::m_sPreviousTopScreen