Etterna: IPreference Class Reference
IPreference Class Reference abstract
#include <Preference.h>
Public Member Functions
IPreference (const RString &sName)
virtual ~IPreference ()
void ReadFrom (const XNode *pNode, bool bIsStatic)
void WriteTo (XNode *pNode) const
void ReadDefaultFrom (const XNode *pNode)
virtual void LoadDefault ()=0
virtual void SetDefaultFromString (const RString &s)=0
virtual RString ToString () const =0
virtual void FromString (const RString &s)=0
virtual void SetFromStack (lua_State *L)
virtual void PushValue (lua_State *L) const
const RString & GetName () const
RString GetName ()
void SetStatic (bool b)
Static Public Member Functions
static IPreference * GetPreferenceByName (const RString &sName)
static void LoadAllDefaults ()
static void ReadAllPrefsFromNode (const XNode *pNode, bool bIsStatic)
static void SavePrefsToNode (XNode *pNode)
static void ReadAllDefaultsFromNode (const XNode *pNode)
Private Attributes
RString m_sName
bool m_bIsStatic
Constructor & Destructor Documentation
IPreference()
IPreference::IPreference (const RString & sName)
References SubscriptionManager< T >::Subscribe().
~IPreference()
IPreference::~IPreference () virtual
References SubscriptionManager< T >::Unsubscribe().
Member Function Documentation
FromString()
virtual void IPreference::FromString (const RString & s) pure virtual
Implemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
Referenced by GameCommand::ApplySelf(), BGBrightnessOrStatic(), MoveMap(), MovePref(), MovePref< bool >(), ReadFrom(), and SetTimingDifficulty().
GetName() [1/2]
const RString& IPreference::GetName () const inline
References m_sName.
Referenced by Preference< ImageCacheMode >::Set().
GetName() [2/2]
RString IPreference::GetName () inline
References m_sName.
GetPreferenceByName()
IPreference * IPreference::GetPreferenceByName (const RString & sName) static
References FOREACHS, and SubscriptionManager< T >::m_pSubscribers.
Referenced by GameCommand::ApplySelf(), BGBrightnessOrStatic(), LunaPrefsManager::GetPreference(), Preference< ImageCacheMode >::GetPreferenceByName(), GameCommand::LoadOne(), MoveMap(), MovePref(), MovePref< bool >(), LunaPrefsManager::PreferenceExists(), LunaPrefsManager::SetPreference(), LunaPrefsManager::SetPreferenceToDefault(), and SetTimingDifficulty().
LoadAllDefaults()
void IPreference::LoadAllDefaults () static
References FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
Referenced by PrefsManager::Init(), PrefsManager::ReadPrefsFromDisk(), and PrefsManager::ResetToFactoryDefaults().
LoadDefault()
virtual void IPreference::LoadDefault () pure virtual
Implemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
Referenced by LunaPrefsManager::SetPreferenceToDefault().
PushValue()
void IPreference::PushValue (lua_State * L) const virtual
Reimplemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
References LOG, m_sName, and RageLog::Trace().
Referenced by LunaPrefsManager::GetPreference().
ReadAllDefaultsFromNode()
void IPreference::ReadAllDefaultsFromNode (const XNode * pNode) static
References FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
Referenced by PrefsManager::ReadDefaultsFromIni().
ReadAllPrefsFromNode()
void IPreference::ReadAllPrefsFromNode (const XNode * pNode, bool bIsStatic) static
References ASSERT, FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
Referenced by PrefsManager::ReadPrefsFromIni().
ReadDefaultFrom()
void IPreference::ReadDefaultFrom (const XNode * pNode)
References XNode::GetAttrValue(), m_sName, and SetDefaultFromString().
ReadFrom()
void IPreference::ReadFrom (const XNode * pNode, bool bIsStatic)
References FromString(), XNode::GetAttrValue(), m_bIsStatic, and m_sName.
SavePrefsToNode()
void IPreference::SavePrefsToNode (XNode * pNode) static
References FOREACHS_CONST, and SubscriptionManager< T >::m_pSubscribers.
Referenced by PrefsManager::SavePrefsToIni().
SetDefaultFromString()
virtual void IPreference::SetDefaultFromString (const RString & s) pure virtual
Implemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
Referenced by ReadDefaultFrom().
SetFromStack()
void IPreference::SetFromStack (lua_State * L) virtual
Reimplemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
References LOG, m_sName, and RageLog::Trace().
Referenced by LunaPrefsManager::SetPreference().
SetStatic()
void IPreference::SetStatic (bool b) inline
References m_bIsStatic.
ToString()
virtual RString IPreference::ToString () const pure virtual
Implemented in Preference< T >, Preference< HighResolutionTextures >, Preference< TapNoteScore >, Preference< float >, Preference< int >, Preference< StdString::CStdStr >, Preference< ShowDancingCharacters >, Preference< AllowW1 >, Preference< MusicWheelUsesSections >, Preference< bool >, Preference< AttractSoundFrequency >, Preference< BackgroundFitMode >, Preference< Maybe >, and Preference< ImageCacheMode >.
Referenced by BGBrightnessOrStatic(), MoveMap(), MovePref(), MovePref< bool >(), LunaPrefsManager::SetPreferenceToDefault(), and WriteTo().
WriteTo()
void IPreference::WriteTo (XNode * pNode) const
References XNode::AppendAttr(), m_bIsStatic, m_sName, and ToString().
Member Data Documentation
m_bIsStatic
bool IPreference::m_bIsStatic private
Referenced by ReadFrom(), SetStatic(), and WriteTo().
m_sName
RString IPreference::m_sName private
Referenced by GetName(), PushValue(), ReadDefaultFrom(), ReadFrom(), SetFromStack(), and WriteTo().
The documentation for this class was generated from the following files:
Preference.h
Preference.cpp