Etterna: RageMovieTextureDriver_FFMpeg Class Reference
RageMovieTextureDriver_FFMpeg Class Reference
#include <MovieTexture_FFMpeg.h>
Public Member Functions
virtual RageMovieTexture * Create (const RageTextureID &ID, RString &sError)
Public Member Functions inherited from RageMovieTextureDriver
~RageMovieTextureDriver () override=default
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Static Public Member Functions
static RageSurface * AVCodecCreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, int &iAVTexfmt, MovieDecoderPixelFormatYCbCr &fmtout)
Additional Inherited Members
Static Public Attributes inherited from RageMovieTextureDriver
static DriverList m_pDriverList
Member Function Documentation
AVCodecCreateCompatibleSurface()
RageSurface * RageMovieTextureDriver_FFMpeg::AVCodecCreateCompatibleSurface (int iTextureWidth, int iTextureHeight, bool bPreferHighColor, int & iAVTexfmt, MovieDecoderPixelFormatYCbCr & fmtout) static
References ASSERT, AVPixelFormats, AVPixelFormat_t::bpp, CreateSurface(), FindCompatibleAVFormat(), FixLilEndian(), LOG, AVPixelFormat_t::masks, AVPixelFormat_t::pf, PixelFormatYCbCr_YUYV422, RageLog::Trace(), and AVPixelFormat_t::YUV.
Referenced by MovieDecoder_FFMpeg::CreateCompatibleSurface().
Create()
RageMovieTexture * RageMovieTextureDriver_FFMpeg::Create (const RageTextureID & ID, RString & sError) virtual
Implements RageMovieTextureDriver.
References MovieTexture_Generic::Init(), and SAFE_DELETE.
The documentation for this class was generated from the following files:
MovieTexture_FFMpeg.h
MovieTexture_FFMpeg.cpp