Etterna: DebugLineConvertXML Class Reference
DebugLineConvertXML Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineConvertXML::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References convert_xmls_in_dir(), IDebugLine::DoAndLog(), GAMESTATE, Song::GetSongDir(), and GameState::m_pCurSong.
GetDisplayTitle()
RString DebugLineConvertXML::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References CONVERT_XML, and LocalizedString::GetValue().
GetDisplayValue()
RString DebugLineConvertXML::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPageName()
RString DebugLineConvertXML::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineConvertXML::IsEnabled () inline override private virtual
Implements IDebugLine.
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp