Etterna: LunaScreenNetSelectMusic Class Reference
LunaScreenNetSelectMusic Class Reference
Allow Lua to have access to the PlayerState.
Public Member Functions
LunaScreenNetSelectMusic ()
Public Member Functions inherited from Luna< ScreenNetSelectMusic >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetMusicWheel (T *p, lua_State *L)
static int SelectCurrent (T *p, lua_State *L)
static int GetSelectionState (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< ScreenNetSelectMusic >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< ScreenNetSelectMusic >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< ScreenNetSelectMusic >
using T = ScreenNetSelectMusic
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< ScreenNetSelectMusic >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the PlayerState.
Constructor & Destructor Documentation
LunaScreenNetSelectMusic()
LunaScreenNetSelectMusic::LunaScreenNetSelectMusic () inline
References ADD_METHOD, GetMusicWheel(), GetSelectionState(), and SelectCurrent().
Member Function Documentation
GetMusicWheel()
static int LunaScreenNetSelectMusic::GetMusicWheel (T * p, lua_State * L) inline static
References ScreenNetSelectMusic::GetMusicWheel(), and MusicWheel::PushSelf().
Referenced by LunaScreenNetSelectMusic().
GetSelectionState()
static int LunaScreenNetSelectMusic::GetSelectionState (T * p, lua_State * L) inline static
References NetworkSyncManager::m_iSelectMode, and NSMAN.
Referenced by LunaScreenNetSelectMusic().
SelectCurrent()
static int LunaScreenNetSelectMusic::SelectCurrent (T * p, lua_State * L) inline static
References ScreenNetSelectMusic::SelectCurrent().
Referenced by LunaScreenNetSelectMusic().
The documentation for this class was generated from the following file:
ScreenNetSelectMusic.cpp