Etterna: RageSoundDriver_WaveOut Class Reference
RageSoundDriver_WaveOut Class Reference
#include <RageSoundDriver_WaveOut.h>
Public Member Functions
RageSoundDriver_WaveOut ()
~RageSoundDriver_WaveOut ()
RString Init ()
int64_t GetPosition () const
float GetPlayLatency () const
int GetSampleRate () const
Public Member Functions inherited from RageSoundDriver
RageSoundDriver ()
~RageSoundDriver () override
void StartMixing (RageSoundBase *pSound)
void StopMixing (RageSoundBase *pSound)
bool PauseMixing (RageSoundBase *pSound, bool bStop)
int64_t GetHardwareFrame (RageTimer *pTimer) const
virtual void Update ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void MixerThread ()
bool GetData ()
void SetupDecodingThread ()
Static Private Member Functions
static int MixerThread_start (void *p)
Private Attributes
RageThread MixingThread
HWAVEOUT m_hWaveOut
HANDLE m_hSoundEvent
WAVEHDR m_aBuffers [8]
int m_iSampleRate
bool m_bShutdown
int m_iLastCursorPos
Additional Inherited Members
Static Public Member Functions inherited from RageSoundDriver
static RageSoundDriver * Create (const RString &sDrivers)
static RString GetDefaultSoundDriverList ()
Static Public Attributes inherited from RageSoundDriver
static DriverList m_pDriverList
Protected Member Functions inherited from RageSoundDriver
void StartDecodeThread ()
void SetDecodeBufferSize (int frames)
void Mix (int16_t *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void Mix (float *pBuf, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
void MixDeinterlaced (float **pBufs, int channels, int iFrames, int64_t iFrameNumber, int64_t iCurrentFrame)
Constructor & Destructor Documentation
RageSoundDriver_WaveOut()
RageSoundDriver_WaveOut::RageSoundDriver_WaveOut ()
References m_bShutdown, m_hSoundEvent, m_hWaveOut, and m_iLastCursorPos.
~RageSoundDriver_WaveOut()
RageSoundDriver_WaveOut::~RageSoundDriver_WaveOut ()
References RageThread::IsCreated(), LOG, m_aBuffers, m_bShutdown, m_hSoundEvent, m_hWaveOut, MixingThread, num_chunks, RageLog::Trace(), and RageThread::Wait().
Member Function Documentation
GetData()
bool RageSoundDriver_WaveOut::GetData () private
References chunksize_frames, FAIL_M, GetPosition(), m_aBuffers, m_hWaveOut, m_iLastCursorPos, RageSoundDriver::Mix(), num_chunks, and wo_ssprintf().
Referenced by MixerThread().
GetPlayLatency()
float RageSoundDriver_WaveOut::GetPlayLatency () const virtual
Reimplemented from RageSoundDriver.
References buffersize_frames, chunksize_frames, and m_iSampleRate.
GetPosition()
int64_t RageSoundDriver_WaveOut::GetPosition () const virtual
Implements RageSoundDriver.
References FAIL_M, m_hWaveOut, and wo_ssprintf().
Referenced by GetData().
GetSampleRate()
int RageSoundDriver_WaveOut::GetSampleRate () const inline virtual
Reimplemented from RageSoundDriver.
References m_iSampleRate.
Init()
RString RageSoundDriver_WaveOut::Init () virtual
Reimplemented from RageSoundDriver.
References buffersize_frames, channels, chunksize, RageThread::Create(), RageLog::Info(), LOG, m_aBuffers, m_hSoundEvent, m_hWaveOut, m_iSampleRate, PrefsManager::m_iSoundPreferredSampleRate, MixerThread_start(), MixingThread, num_chunks, PREFSMAN, RageSoundDriver::SetDecodeBufferSize(), RageThread::SetName(), RageSoundDriver::StartDecodeThread(), wo_ssprintf(), and ZERO.
MixerThread()
void RageSoundDriver_WaveOut::MixerThread () private
References GetData(), LOG, m_bShutdown, m_hSoundEvent, m_hWaveOut, and RageLog::Warn().
MixerThread_start()
int RageSoundDriver_WaveOut::MixerThread_start (void * p) static private
Referenced by Init().
SetupDecodingThread()
void RageSoundDriver_WaveOut::SetupDecodingThread () private virtual
Reimplemented from RageSoundDriver.
References LOG, and RageLog::Warn().
Member Data Documentation
m_aBuffers
WAVEHDR RageSoundDriver_WaveOut::m_aBuffers[8] private
Referenced by GetData(), Init(), and ~RageSoundDriver_WaveOut().
m_bShutdown
bool RageSoundDriver_WaveOut::m_bShutdown private
Referenced by MixerThread(), RageSoundDriver_WaveOut(), and ~RageSoundDriver_WaveOut().
m_hSoundEvent
HANDLE RageSoundDriver_WaveOut::m_hSoundEvent private
Referenced by Init(), MixerThread(), RageSoundDriver_WaveOut(), and ~RageSoundDriver_WaveOut().
m_hWaveOut
HWAVEOUT RageSoundDriver_WaveOut::m_hWaveOut private
Referenced by GetData(), GetPosition(), Init(), MixerThread(), RageSoundDriver_WaveOut(), and ~RageSoundDriver_WaveOut().
m_iLastCursorPos
int RageSoundDriver_WaveOut::m_iLastCursorPos private
Referenced by GetData(), and RageSoundDriver_WaveOut().
m_iSampleRate
int RageSoundDriver_WaveOut::m_iSampleRate private
Referenced by GetPlayLatency(), GetSampleRate(), and Init().
MixingThread
RageThread RageSoundDriver_WaveOut::MixingThread private
Referenced by Init(), and ~RageSoundDriver_WaveOut().
The documentation for this class was generated from the following files:
RageSoundDriver_WaveOut.h
RageSoundDriver_WaveOut.cpp