Etterna: LunaStageStats Class Reference
LunaStageStats Class Reference
Allow Lua to have access to the StageStats.
Public Member Functions
LunaStageStats ()
Public Member Functions inherited from Luna< StageStats >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int GetPlayerStageStats (T *p, lua_State *L)
static int GetMultiPlayerStageStats (T *p, lua_State *L)
static int GetPlayedSongs (T *p, lua_State *L)
static int GetPossibleSongs (T *p, lua_State *L)
static int GetGameplaySeconds (T *p, lua_State *L)
static int OnePassed (T *p, lua_State *L)
static int AllFailed (T *p, lua_State *L)
static int GetStage (T *p, lua_State *L)
static int PlayerHasHighScore (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< StageStats >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< StageStats >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< StageStats >
using T = StageStats
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< StageStats >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to the StageStats.
Constructor & Destructor Documentation
LunaStageStats()
LunaStageStats::LunaStageStats () inline
References ADD_METHOD, AllFailed(), GetGameplaySeconds(), GetMultiPlayerStageStats(), GetPlayedSongs(), GetPlayerStageStats(), GetPossibleSongs(), GetStage(), OnePassed(), and PlayerHasHighScore().
Member Function Documentation
AllFailed()
static int LunaStageStats::AllFailed (T * p, lua_State * L) inline static
References StageStats::AllFailed().
Referenced by LunaStageStats().
GetGameplaySeconds()
static int LunaStageStats::GetGameplaySeconds (T * p, lua_State * L) inline static
References StageStats::m_fGameplaySeconds.
Referenced by LunaStageStats().
GetMultiPlayerStageStats()
static int LunaStageStats::GetMultiPlayerStageStats (T * p, lua_State * L) inline static
References L, and StageStats::m_multiPlayer.
Referenced by LunaStageStats().
GetPlayedSongs()
static int LunaStageStats::GetPlayedSongs (T * p, lua_State * L) inline static
References StageStats::m_vpPlayedSongs.
Referenced by LunaStageStats().
GetPlayerStageStats()
static int LunaStageStats::GetPlayerStageStats (T * p, lua_State * L) inline static
References L, and StageStats::m_player.
Referenced by LunaStageStats().
GetPossibleSongs()
static int LunaStageStats::GetPossibleSongs (T * p, lua_State * L) inline static
References StageStats::m_vpPossibleSongs.
Referenced by LunaStageStats().
GetStage()
static int LunaStageStats::GetStage (T * p, lua_State * L) inline static
References StageStats::m_Stage, and LuaHelpers::Push().
Referenced by LunaStageStats().
OnePassed()
static int LunaStageStats::OnePassed (T * p, lua_State * L) inline static
References StageStats::OnePassed().
Referenced by LunaStageStats().
PlayerHasHighScore()
static int LunaStageStats::PlayerHasHighScore (T * p, lua_State * L) inline static
Referenced by LunaStageStats().
The documentation for this class was generated from the following file:
StageStats.cpp