Etterna: Preference< T > Class Template Reference
Preference< T > Class Template Reference
#include <Preference.h>
Public Member Functions
Preference (const RString &sName, const T &defaultValue, void(pfnValidate)(T &val)=NULL)
RString ToString () const override
void FromString (const RString &s) override
void SetFromStack (lua_State *L) override
void PushValue (lua_State *L) const override
void LoadDefault () override
void SetDefaultFromString (const RString &s) override
const T & Get () const
const T & GetDefault () const
operator const T () const
void Set (const T &other)
Public Member Functions inherited from IPreference
IPreference (const RString &sName)
virtual ~IPreference ()
void ReadFrom (const XNode *pNode, bool bIsStatic)
void WriteTo (XNode *pNode) const
void ReadDefaultFrom (const XNode *pNode)
const RString & GetName () const
RString GetName ()
void SetStatic (bool b)
Static Public Member Functions
static Preference< T > * GetPreferenceByName (const RString &sName)
Static Public Member Functions inherited from IPreference
static IPreference * GetPreferenceByName (const RString &sName)
static void LoadAllDefaults ()
static void ReadAllPrefsFromNode (const XNode *pNode, bool bIsStatic)
static void SavePrefsToNode (XNode *pNode)
static void ReadAllDefaultsFromNode (const XNode *pNode)
Private Attributes
T m_currentValue
T m_defaultValue
void(* m_pfnValidate)(T &val)
Constructor & Destructor Documentation
Preference()
template<class T> Preference< T >::Preference (const RString & sName, const T & defaultValue, void(pfnValidate)(T &val) = NULL) inline
Member Function Documentation
FromString()
template<class T> void Preference< T >::FromString (const RString & s) inline override virtual
Implements IPreference.
Get()
template<class T> const T& Preference< T >::Get () const inline
Referenced by ChangeAppPri(), ChangeVisualDelay(), ChangeVolume(), GameState::CountNotesSeparately(), RageDisplay::FrameLimitAfterVsync(), RageDisplay::FrameLimitBeforeVsync(), ScreenGameplay::Init(), SongManager::InitSongsFromDisk(), ScreenNetSelectMusic::Input(), ScreenSelectMusic::Input(), DebugLineStats::IsEnabled(), DebugLineVsync::IsEnabled(), DebugLineAllowMultitexture::IsEnabled(), DebugLineShowMasks::IsEnabled(), DebugLineMenuTimer::IsEnabled(), GameState::JoinInput(), ScreenNetSelectMusic::OnConfirmSongDeletion(), ScreenSelectMusic::OnConfirmSongDeletion(), RageSoundReader_Preload::Open(), Preference< TapNoteScore >::operator const TapNoteScore(), Player::PlayKeysound(), LuaHelpers::Push(), RageSoundReader_Preload::RageSoundReader_Preload(), Song::SaveToETTFile(), Song::SaveToSSCFile(), ScreenSelectMusic::SelectCurrent(), Actor::SetGlobalRenderStates(), RageSoundManager::SetMixVolume(), RageSoundReader_PitchChange::SetProperty(), sm_main(), FileTransfer::StartTransfer(), ScreenStatsOverlay::Update(), Player::UpdateHoldNotes(), ScreenStatsOverlay::UpdateSkips(), and SongPosition::UpdateSongPosition().
GetDefault()
template<class T> const T& Preference< T >::GetDefault () const inline
GetPreferenceByName()
template<class T> static Preference<T>* Preference< T >::GetPreferenceByName (const RString & sName) inline static
Referenced by ChangeVisualDelay(), ChangeVolume(), DebugLineShowMasks::GetPref(), DebugLineVolumeUp::GetPref(), DebugLineVolumeDown::GetPref(), DebugLineVisualDelayUp::GetPref(), DebugLineVisualDelayDown::GetPref(), Player::PlayKeysound(), and Player::UpdateHoldNotes().
LoadDefault()
template<class T> void Preference< T >::LoadDefault () inline override virtual
Implements IPreference.
Referenced by Preference< ImageCacheMode >::Preference().
operator const T()
template<class T> Preference< T >::operator const T () const inline
PushValue()
template<class T> void Preference< T >::PushValue (lua_State * L) const inline override virtual
Reimplemented from IPreference.
Set()
template<class T> void Preference< T >::Set (const T & other) inline
Referenced by AdjustForChangedSystemCapabilities(), AdjustSync::AutosyncOffset(), ChangeVisualDelay(), ChangeVolume(), CheckVideoDefaultSettings(), DisplayResolutionM(), DebugLineStats::DoAndLog(), DebugLineVsync::DoAndLog(), DebugLineAllowMultitexture::DoAndLog(), DebugLineShowMasks::DoAndLog(), DebugLineMuteActions::DoAndLog(), DebugLineToggleErrors::DoAndLog(), DebugLineMenuTimer::DoAndLog(), HandleInputEvents(), ScreenSyncOverlay::Input(), ScreenDebugOverlay::Input(), ScreenSelectMusic::Input(), ScreenNetworkOptions::MenuStart(), NetworkSyncManager::PostStartUp(), AdjustSync::RevertSyncChanges(), and StoreActualGraphicOptions().
SetDefaultFromString()
template<class T> void Preference< T >::SetDefaultFromString (const RString & s) inline override virtual
Implements IPreference.
SetFromStack()
template<class T> void Preference< T >::SetFromStack (lua_State * L) inline override virtual
Reimplemented from IPreference.
ToString()
template<class T> RString Preference< T >::ToString () const inline override virtual
Implements IPreference.
Member Data Documentation
m_currentValue
template<class T> T Preference< T >::m_currentValue private
Referenced by Preference< ImageCacheMode >::FromString(), Preference< ImageCacheMode >::Get(), Preference< ImageCacheMode >::LoadDefault(), Preference< ImageCacheMode >::PushValue(), Preference< ImageCacheMode >::Set(), Preference< ImageCacheMode >::SetFromStack(), and Preference< ImageCacheMode >::ToString().
m_defaultValue
template<class T> T Preference< T >::m_defaultValue private
Referenced by Preference< ImageCacheMode >::FromString(), Preference< ImageCacheMode >::GetDefault(), Preference< ImageCacheMode >::LoadDefault(), and Preference< ImageCacheMode >::SetDefaultFromString().
m_pfnValidate
template<class T> void(* Preference< T >::m_pfnValidate) (T &val) private
Referenced by Preference< ImageCacheMode >::FromString(), and Preference< ImageCacheMode >::SetFromStack().
The documentation for this class was generated from the following file:
Preference.h