Etterna: GameManager Class Reference
GameManager Class Reference
#include <GameManager.h>
Public Member Functions
GameManager ()
~GameManager ()
void GetStylesForGame (const Game *pGame, vector< const Style *> &aStylesAddTo, bool editor=false)
const Game * GetGameForStyle (const Style *pStyle)
void GetStepsTypesForGame (const Game *pGame, vector< StepsType > &aStepsTypeAddTo)
const Style * GetEditorStyleForStepsType (StepsType st)
void GetDemonstrationStylesForGame (const Game *pGame, vector< const Style *> &vpStylesOut)
const Style * GetHowToPlayStyleForGame (const Game *pGame)
void GetCompatibleStyles (const Game *pGame, int iNumPlayers, vector< const Style *> &vpStylesOut)
const Style * GetFirstCompatibleStyle (const Game *pGame, int iNumPlayers, StepsType st)
void GetEnabledGames (vector< const Game *> &aGamesOut)
const Game * GetDefaultGame ()
bool IsGameEnabled (const Game *pGame)
int GetIndexFromGame (const Game *pGame)
const Game * GetGameFromIndex (int index)
const StepsTypeInfo & GetStepsTypeInfo (StepsType st)
StepsType StringToStepsType (RString sStepsType)
const Game * StringToGame (const RString &sGame)
const Style * GameAndStringToStyle (const Game *pGame, const RString &sStyle)
RString StyleToLocalizedString (const Style *s)
void PushSelf (lua_State *L)
Public Attributes
bool m_bResetModifiers
float m_fPreviousRate
RString m_sModsToReset
Constructor & Destructor Documentation
GameManager()
GameManager::GameManager ()
References LuaManager::Get(), L, LUA, m_bResetModifiers, m_fPreviousRate, m_sModsToReset, PushSelf(), and LuaManager::Release().
~GameManager()
GameManager::~GameManager ()
References LUA, and LuaManager::UnsetGlobal().
Member Function Documentation
GameAndStringToStyle()
const Style * GameManager::GameAndStringToStyle (const Game * pGame, const RString & sStyle)
References StdString::CStdStr< CT >::CompareNoCase(), Game::m_apStyles, and Style::m_szName.
Referenced by ScreenSelectMusic::Init(), ScreenEvaluation::Init(), GameCommand::LoadOne(), SMOProtocol::ProcessInput(), LunaGameState::SetCurrentStyle(), and StyleID::ToStyle().
GetCompatibleStyles()
void GameManager::GetCompatibleStyles (const Game * pGame, int iNumPlayers, vector< const Style *> & vpStylesOut)
References DEFAULT_FAIL, FOREACH_ENUM, Game::m_apStyles, Style::m_bUsedForGameplay, Style::m_StyleType, StyleType_OnePlayerOneSide, StyleType_OnePlayerTwoSides, StyleType_TwoPlayersSharedSides, and StyleType_TwoPlayersTwoSides.
Referenced by GetFirstCompatibleStyle(), SongUtil::GetPlayableStepsTypes(), and MusicWheel::SetOpenSection().
GetDefaultGame()
const Game * GameManager::GetDefaultGame ()
References ARRAYLEN, IsGameEnabled(), and RageException::Throw().
Referenced by ScreenSelectMusic::Init(), ScreenEvaluation::Init(), and SwitchToLastPlayedGame().
GetDemonstrationStylesForGame()
void GameManager::GetDemonstrationStylesForGame (const Game * pGame, vector< const Style *> & vpStylesOut)
References ASSERT, Game::m_apStyles, and Style::m_bUsedForDemonstration.
GetEditorStyleForStepsType()
const Style * GameManager::GetEditorStyleForStepsType (StepsType st)
References ASSERT_M, Style::m_bUsedForEdit, Style::m_StepsType, and ssprintf().
GetEnabledGames()
void GameManager::GetEnabledGames (vector< const Game *> & aGamesOut)
References ARRAYLEN, and IsGameEnabled().
Referenced by GameChoices(), GameSel(), and LunaGameManager::GetEnabledGames().
GetFirstCompatibleStyle()
const Style * GameManager::GetFirstCompatibleStyle (const Game * pGame, int iNumPlayers, StepsType st)
References FOREACH_CONST, and GetCompatibleStyles().
Referenced by ScreenSelectMusic::BeginScreen(), GameState::ForceOtherPlayersToCompatibleSteps(), GameState::JoinPlayer(), GameState::SetCompatibleStyle(), and GameState::SetCompatibleStylesForPlayers().
GetGameForStyle()
const Game * GameManager::GetGameForStyle (const Style * pStyle)
References FAIL_M, and Style::m_szName.
Referenced by StyleID::FromStyle().
GetGameFromIndex()
const Game * GameManager::GetGameFromIndex (int index)
References ARRAYLEN, and ASSERT.
GetHowToPlayStyleForGame()
const Style * GameManager::GetHowToPlayStyleForGame (const Game * pGame)
References FAIL_M, Game::m_apStyles, Style::m_bUsedForHowToPlay, Game::m_szName, and ssprintf().
Referenced by ScreenGameplaySyncMachine::Init(), ScreenHowToPlay::Init(), and OptionRowHandlerListDifficulties::LoadInternal().
GetIndexFromGame()
int GameManager::GetIndexFromGame (const Game * pGame)
References ARRAYLEN, FAIL_M, Game::m_szName, and ssprintf().
GetStepsTypeInfo()
const StepsTypeInfo & GameManager::GetStepsTypeInfo (StepsType st)
References ARRAYLEN, ASSERT, ASSERT_M, NUM_StepsType, and ssprintf().
Referenced by BMSChartReader::CalculateStepsType(), GameState::CanSafelyEnterGameplay(), Steps::CopyFrom(), Steps::CreateBlank(), StepsID::CreateNode(), Steps::Decompress(), Steps::GetNoteData(), OptionRowHandlerStepsType::LoadInternal(), BMSChartReader::ReadNoteData(), XMLProfile::SaveCategoryScoresCreateNode(), XMLProfile::SaveEttGeneralDataCreateNode(), DBProfile::SaveGeneralData(), XMLProfile::SaveGeneralDataCreateNode(), Steps::SetNoteData(), ScreenRanking::SetPage(), LunaGameManager::StepsTypeToLocalizedString(), StepsTypeToString(), Steps::TidyUpData(), and StepsID::ToString().
GetStepsTypesForGame()
void GameManager::GetStepsTypesForGame (const Game * pGame, vector< StepsType > & aStepsTypeAddTo)
References ASSERT, Game::m_apStyles, Style::m_StepsType, and NUM_StepsType.
Referenced by ScreenSelectMusic::BeginScreen(), LunaGameManager::GetFirstStepsTypeForGame(), ThemeMetricStepsTypesToShow::Read(), and GameState::SetCompatibleStylesForPlayers().
GetStylesForGame()
void GameManager::GetStylesForGame (const Game * pGame, vector< const Style *> & aStylesAddTo, bool editor = false)
References Game::m_apStyles, Style::m_bUsedForEdit, and Style::m_bUsedForGameplay.
Referenced by OptionRowHandlerListStyles::LoadInternal().
IsGameEnabled()
bool GameManager::IsGameEnabled (const Game * pGame)
References NoteSkinManager::DoNoteSkinsExistForGame(), and NOTESKIN.
Referenced by GetDefaultGame(), GetEnabledGames(), LunaGameManager::IsGameEnabled(), and SwitchToLastPlayedGame().
PushSelf()
void GameManager::PushSelf (lua_State * L)
Referenced by GameManager().
StringToGame()
const Game * GameManager::StringToGame (const RString & sGame)
References ARRAYLEN, StdString::CStdStr< CT >::CompareNoCase(), and Game::m_szName.
Referenced by LunaGameManager::GetStylesForGame(), StepMania::InitializeCurrentGame(), LunaGameManager::IsGameEnabled(), SMOProtocol::ProcessInput(), LunaGameManager::SetGame(), SwitchToLastPlayedGame(), and StyleID::ToStyle().
StringToStepsType()
StepsType GameManager::StringToStepsType (RString sStepsType)
References StdString::CStdStr< CT >::MakeLower(), NUM_StepsType, and StepsType_Invalid.
Referenced by Deserialize(), XMLProfile::LoadCategoryScoresFromNode(), XMLProfile::LoadEttGeneralDataFromNode(), StepsID::LoadFromNode(), SMLoader::LoadFromTokens(), DBProfile::LoadGeneralData(), XMLProfile::LoadGeneralDataFromNode(), SMLoader::LoadNoteDataFromSimfile(), SSCLoader::LoadNoteDataFromSimfile(), RemoveStepsTypes(), SetStepsType(), and SongCacheIndex::SongFromStatement().
StyleToLocalizedString()
RString GameManager::StyleToLocalizedString (const Style * s)
References Capitalize(), ThemeManager::GetString(), ThemeManager::HasString(), Style::m_szName, and THEME.
Referenced by OptionRowHandlerListStyles::LoadInternal().
Member Data Documentation
m_bResetModifiers
bool GameManager::m_bResetModifiers
Referenced by GameManager(), ScreenEvaluation::HandleMenuStart(), ScreenGameplay::Input(), LunaScreenSelectMusic::PlayReplay(), LunaScreenSelectMusic::ShowEvalScreenForScore(), and ScreenGameplay::Update().
m_fPreviousRate
float GameManager::m_fPreviousRate
Referenced by GameManager(), ScreenEvaluation::HandleMenuStart(), ScreenGameplay::Input(), LunaScreenSelectMusic::PlayReplay(), LunaScreenSelectMusic::ShowEvalScreenForScore(), and ScreenGameplay::Update().
m_sModsToReset
RString GameManager::m_sModsToReset
Referenced by GameManager(), ScreenEvaluation::HandleMenuStart(), ScreenGameplay::Input(), LunaScreenSelectMusic::PlayReplay(), and ScreenGameplay::Update().
The documentation for this class was generated from the following files:
GameManager.h
GameManager.cpp