Etterna: EnumHelper.cpp File Reference
EnumHelper.cpp File Reference
#include "global.h"
#include "EnumHelper.h"
#include "LuaManager.h"
#include "RageUtil.h"
Functions
int CheckEnum (lua_State *L, LuaReference &table, int iPos, int iInvalid, const char *szType, bool bAllowInvalid, bool bAllowAnything)
const RString & EnumToString (int iVal, int iMax, const char **szNameArray, unique_ptr< RString > *pNameCache)
static void PushEnumMethodTable (lua_State *L)
Variables
static const luaL_Reg EnumLib []
Function Documentation
CheckEnum()
int CheckEnum (lua_State * L, LuaReference & table, int iPos, int iInvalid, const char * szType, bool bAllowInvalid, bool bAllowAnything)
References LuaHelpers::AbsIndex(), StdString::CStdStr< CT >::MakeLower(), LuaHelpers::Pop(), LuaHelpers::Push(), LuaReference::PushSelf(), LuaHelpers::ReportScriptError(), ssprintf(), and unlikely.
Referenced by Enum::Check().
EnumToString()
const RString& EnumToString (int iVal, int iMax, const char ** szNameArray, unique_ptr< RString > * pNameCache)
References FAIL_M, ssprintf(), and unlikely.
PushEnumMethodTable()
static void PushEnumMethodTable (lua_State * L) static
Referenced by Enum::SetMetatable().
Variable Documentation
EnumLib
const luaL_Reg EnumLib[] static
Initial value:
= { { "GetName", GetName },
                                    { "Reverse", Reverse },
                                    { NULL, NULL } }