Etterna: MovieTexture_Generic Class Reference
MovieTexture_Generic Class Reference
#include <MovieTexture_Generic.h>
Public Member Functions
MovieTexture_Generic (const RageTextureID &ID, MovieDecoder *pDecoder)
virtual ~MovieTexture_Generic ()
RString Init ()
void Invalidate ()
virtual void Reload ()
virtual void SetPosition (float fSeconds)
virtual void DecodeSeconds (float fSeconds)
virtual void SetPlaybackRate (float fRate)
void SetLooping (bool bLooping=true)
unsigned GetTexHandle () const
Public Member Functions inherited from RageMovieTexture
RageMovieTexture (const RageTextureID &ID)
~RageMovieTexture () override=default
void Update (float) override
bool IsAMovie () const override
Public Member Functions inherited from RageTexture
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Static Public Member Functions
static EffectMode GetEffectMode (MovieDecoderPixelFormatYCbCr fmt)
Static Public Member Functions inherited from RageMovieTexture
static RageMovieTexture * Create (const RageTextureID &ID)
static bool GetFourCC (const RString &fn, RString &handler, RString &type)
Static Public Member Functions inherited from RageTexture
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Private Types
enum { FRAME_NONE, FRAME_DECODED }
Private Member Functions
void UpdateFrame ()
void CreateTexture ()
void DestroyTexture ()
bool DecodeFrame ()
float CheckFrameTime ()
Private Attributes
MovieDecoder * m_pDecoder
float m_fRate
enum MovieTexture_Generic:: { ... } m_ImageWaiting
bool m_bLoop
bool m_bWantRewind
unsigned m_uTexHandle
RageTextureRenderTarget * m_pRenderTarget
RageTexture * m_pTextureIntermediate
Sprite * m_pSprite
RageSurface * m_pSurface
RageTextureLock * m_pTextureLock
float m_fClock
bool m_bFrameSkipMode
Additional Inherited Members
Public Attributes inherited from RageTexture
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions inherited from RageTexture
virtual void CreateFrameRects ()
Protected Attributes inherited from RageTexture
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FRAME_NONE
FRAME_DECODED
Constructor & Destructor Documentation
MovieTexture_Generic()
MovieTexture_Generic::MovieTexture_Generic (const RageTextureID & ID, MovieDecoder * pDecoder)
References RageTextureID::filename, FRAME_NONE, LOG, m_bFrameSkipMode, m_bLoop, m_bWantRewind, m_fClock, m_fRate, m_ImageWaiting, m_pDecoder, m_pRenderTarget, m_pSprite, m_pSurface, m_pTextureIntermediate, m_pTextureLock, m_uTexHandle, and RageLog::Trace().
~MovieTexture_Generic()
MovieTexture_Generic::~MovieTexture_Generic () virtual
References MovieDecoder::Close(), DestroyTexture(), m_pDecoder, and m_pSprite.
Member Function Documentation
CheckFrameTime()
float MovieTexture_Generic::CheckFrameTime () private
References f, RageTexture::GetID(), MovieDecoder::GetTimestamp(), LOG, m_bFrameSkipMode, m_fClock, m_fRate, m_pDecoder, and RageLog::Trace().
Referenced by DecodeSeconds().
CreateTexture()
void MovieTexture_Generic::CreateTexture () private
References align_left, align_top, ASSERT, RageSurfaceFormat::BitsPerPixel, CHECKPOINT_M, MovieDecoder::CreateCompatibleSurface(), RageDisplay::CreateTexture(), RageDisplay::CreateTextureLock(), DISPLAY, FAIL_M, RageTextureID::filename, RageDisplay::FindPixelFormat(), RageSurface::fmt, g_bMovieTextureDirectUpdates, GetEffectMode(), MovieDecoder::GetHeight(), RageTexture::GetID(), RageTextureManager::GetPrefs(), MovieDecoder::GetSourceAspectRatio(), MovieDecoder::GetWidth(), RageSurface::h, RenderTargetParam::iHeight, RenderTargetParam::iWidth, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, RageTextureManagerPrefs::m_iMovieColorDepth, RageTexture::m_iRefCount, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_pDecoder, m_pRenderTarget, m_pSprite, m_pSurface, m_pTextureIntermediate, m_pTextureLock, m_uTexHandle, RageSurfaceFormat::Mask, PixelFormatYCbCr_Invalid, RageSurface::pixels, power_of_two(), RagePixelFormat_Invalid, RagePixelFormat_RGB5, RagePixelFormat_RGB8, RagePixelFormat_RGBA4, RagePixelFormat_RGBA8, SAFE_DELETE, Sprite::SetEffectMode(), Actor::SetHorizAlign(), Sprite::SetTexture(), Actor::SetVertAlign(), ssprintf(), RageDisplay::SupportsTextureFormat(), TEXTUREMAN, Sprite::UnloadTexture(), and RageSurface::w.
Referenced by Init(), and UpdateFrame().
DecodeFrame()
bool MovieTexture_Generic::DecodeFrame () private
References MovieDecoder::DecodeFrame(), MovieDecoder::GetFrameDuration(), RageTexture::GetID(), MovieDecoder::GetTimestamp(), LOG, m_bFrameSkipMode, m_bLoop, m_bWantRewind, m_fClock, m_pDecoder, MovieDecoder::Rewind(), and RageLog::Trace().
Referenced by DecodeSeconds().
DecodeSeconds()
void MovieTexture_Generic::DecodeSeconds (float fSeconds) virtual
Reimplemented from RageTexture.
References CheckFrameTime(), DecodeFrame(), FRAME_DECODED, FRAME_NONE, LOG, m_fClock, m_fRate, m_ImageWaiting, RageLog::MapLog(), and UpdateFrame().
DestroyTexture()
void MovieTexture_Generic::DestroyTexture () private
References RageDisplay::DeleteTexture(), DISPLAY, m_pRenderTarget, m_pSurface, m_pTextureIntermediate, m_pTextureLock, and m_uTexHandle.
Referenced by ~MovieTexture_Generic().
GetEffectMode()
EffectMode MovieTexture_Generic::GetEffectMode (MovieDecoderPixelFormatYCbCr fmt) static
References ASSERT, EffectModes, and PixelFormatYCbCr_Invalid.
Referenced by CreateTexture(), and FindCompatibleAVFormat().
GetTexHandle()
unsigned MovieTexture_Generic::GetTexHandle () const virtual
Implements RageTexture.
References RageTextureRenderTarget::GetTexHandle(), m_pRenderTarget, and m_uTexHandle.
Referenced by UpdateFrame().
Init()
RString MovieTexture_Generic::Init ()
References CHECKPOINT_M, RageTexture::CreateFrameRects(), CreateTexture(), MovieDecoder::DecodeFrame(), FRAME_DECODED, RageTexture::GetID(), LOG, RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, m_ImageWaiting, RageTexture::m_iSourceHeight, RageTexture::m_iSourceWidth, RageTexture::m_iTextureHeight, RageTexture::m_iTextureWidth, m_pDecoder, MovieDecoder::Open(), ssprintf(), RageLog::Trace(), and UpdateFrame().
Referenced by RageMovieTextureDriver_FFMpeg::Create().
Invalidate()
void MovieTexture_Generic::Invalidate () virtual
Reimplemented from RageTexture.
References RageTexture::Invalidate(), m_pTextureIntermediate, and m_uTexHandle.
Reload()
void MovieTexture_Generic::Reload () virtual
Implements RageMovieTexture.
SetLooping()
void MovieTexture_Generic::SetLooping (bool bLooping = true) inline virtual
Reimplemented from RageMovieTexture.
References m_bLoop.
SetPlaybackRate()
virtual void MovieTexture_Generic::SetPlaybackRate (float fRate) inline virtual
Implements RageMovieTexture.
References m_fRate.
SetPosition()
void MovieTexture_Generic::SetPosition (float fSeconds) virtual
Implements RageMovieTexture.
References LOG, m_bWantRewind, RageLog::Trace(), and RageLog::Warn().
UpdateFrame()
void MovieTexture_Generic::UpdateFrame () private
References RageTextureRenderTarget::BeginRenderingTo(), CHECKPOINT_M, CreateTexture(), DISPLAY, Actor::Draw(), RageTextureRenderTarget::FinishRenderingTo(), MovieDecoder::GetFrame(), RageTexture::GetTexHandle(), GetTexHandle(), RageSurface::h, RageTextureLock::Lock(), RageTexture::m_iImageHeight, RageTexture::m_iImageWidth, m_pDecoder, m_pRenderTarget, m_pSprite, m_pSurface, m_pTextureIntermediate, m_pTextureLock, m_uTexHandle, RageTextureLock::Unlock(), RageDisplay::UpdateTexture(), and RageSurface::w.
Referenced by DecodeSeconds(), and Init().
Member Data Documentation
m_bFrameSkipMode
bool MovieTexture_Generic::m_bFrameSkipMode private
Referenced by CheckFrameTime(), DecodeFrame(), and MovieTexture_Generic().
m_bLoop
bool MovieTexture_Generic::m_bLoop private
Referenced by DecodeFrame(), MovieTexture_Generic(), and SetLooping().
m_bWantRewind
bool MovieTexture_Generic::m_bWantRewind private
Referenced by DecodeFrame(), MovieTexture_Generic(), and SetPosition().
m_fClock
float MovieTexture_Generic::m_fClock private
Referenced by CheckFrameTime(), DecodeFrame(), DecodeSeconds(), and MovieTexture_Generic().
m_fRate
float MovieTexture_Generic::m_fRate private
Referenced by CheckFrameTime(), DecodeSeconds(), MovieTexture_Generic(), and SetPlaybackRate().
m_ImageWaiting
enum { ... } MovieTexture_Generic::m_ImageWaiting
Referenced by DecodeSeconds(), Init(), and MovieTexture_Generic().
m_pDecoder
MovieDecoder* MovieTexture_Generic::m_pDecoder private
Referenced by CheckFrameTime(), CreateTexture(), DecodeFrame(), Init(), MovieTexture_Generic(), UpdateFrame(), and ~MovieTexture_Generic().
m_pRenderTarget
RageTextureRenderTarget* MovieTexture_Generic::m_pRenderTarget private
Referenced by CreateTexture(), DestroyTexture(), GetTexHandle(), MovieTexture_Generic(), and UpdateFrame().
m_pSprite
Sprite* MovieTexture_Generic::m_pSprite private
Referenced by CreateTexture(), MovieTexture_Generic(), UpdateFrame(), and ~MovieTexture_Generic().
m_pSurface
RageSurface* MovieTexture_Generic::m_pSurface private
Referenced by CreateTexture(), DestroyTexture(), MovieTexture_Generic(), and UpdateFrame().
m_pTextureIntermediate
RageTexture* MovieTexture_Generic::m_pTextureIntermediate private
Referenced by CreateTexture(), DestroyTexture(), Invalidate(), MovieTexture_Generic(), and UpdateFrame().
m_pTextureLock
RageTextureLock* MovieTexture_Generic::m_pTextureLock private
Referenced by CreateTexture(), DestroyTexture(), MovieTexture_Generic(), and UpdateFrame().
m_uTexHandle
unsigned MovieTexture_Generic::m_uTexHandle private
Referenced by CreateTexture(), DestroyTexture(), GetTexHandle(), Invalidate(), MovieTexture_Generic(), and UpdateFrame().
The documentation for this class was generated from the following files:
MovieTexture_Generic.h
MovieTexture_Generic.cpp