Etterna: RageSoundReader_Extend Class Reference
RageSoundReader_Extend Class Reference
#include <RageSoundReader_Extend.h>
Public Member Functions
RageSoundReader_Extend (RageSoundReader *pSource)
int SetPosition (int iFrame) override
int Read (float *pBuffer, int iFrames) override
int GetNextSourceFrame () const override
bool SetProperty (const RString &sProperty, float fValue) override
RageSoundReader_Extend * Copy () const override
~RageSoundReader_Extend () override=default
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int Read (float *pBuf, int iFrames) override
int GetSampleRate () const override
unsigned GetNumChannels () const override
bool SetProperty (const RString &sProperty, float fValue) override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Types
enum StopMode { M_LOOP, M_STOP, M_CONTINUE }
Private Member Functions
int GetEndFrame () const
int GetData (float *pBuffer, int iFrames)
Private Attributes
int m_iPositionFrames
StopMode m_StopMode
int m_iStartFrames
int m_iLengthFrames
int m_iFadeInFrames
int m_iFadeOutFrames
bool m_bIgnoreFadeInFrames
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Member Enumeration Documentation
StopMode
enum RageSoundReader_Extend::StopMode private
Enumerator
M_LOOP
M_STOP
M_CONTINUE
Constructor & Destructor Documentation
RageSoundReader_Extend()
RageSoundReader_Extend::RageSoundReader_Extend (RageSoundReader * pSource)
References ASSERT_M, RageSoundReader::GetNextSourceFrame(), m_bIgnoreFadeInFrames, m_iFadeInFrames, m_iFadeOutFrames, m_iLengthFrames, m_iPositionFrames, m_iStartFrames, M_STOP, and m_StopMode.
Referenced by Copy().
~RageSoundReader_Extend()
RageSoundReader_Extend::~RageSoundReader_Extend () override default
Member Function Documentation
Copy()
RageSoundReader_Extend* RageSoundReader_Extend::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_Extend().
GetData()
int RageSoundReader_Extend::GetData (float * pBuffer, int iFrames) private
References RageSoundReader::END_OF_FILE, GetEndFrame(), RageSoundReader::GetNextSourceFrame(), RageSoundReader_Filter::GetNumChannels(), m_iLengthFrames, m_iPositionFrames, RageSoundReader_Filter::m_pSource, max(), min(), and RageSoundReader_Filter::Read().
Referenced by Read().
GetEndFrame()
int RageSoundReader_Extend::GetEndFrame () const private
References m_iLengthFrames, and m_iStartFrames.
Referenced by GetData(), Read(), and SetPosition().
GetNextSourceFrame()
int RageSoundReader_Extend::GetNextSourceFrame () const override virtual
Implements RageSoundReader.
References m_iPositionFrames.
Read()
int RageSoundReader_Extend::Read (float * pBuffer, int iFrames) override virtual
Implements RageSoundReader.
References RageSoundReader::END_OF_FILE, f, RageSoundUtil::Fade(), GetData(), GetEndFrame(), RageSoundReader_Filter::GetNumChannels(), m_bIgnoreFadeInFrames, M_CONTINUE, m_iFadeInFrames, m_iFadeOutFrames, m_iLengthFrames, m_iPositionFrames, m_iStartFrames, M_LOOP, m_StopMode, min(), SCALE, SetPosition(), and RageSoundReader::STREAM_LOOPED.
SetPosition()
int RageSoundReader_Extend::SetPosition (int iFrame) override virtual
Implements RageSoundReader.
References GetEndFrame(), m_bIgnoreFadeInFrames, M_CONTINUE, m_iLengthFrames, m_iPositionFrames, RageSoundReader_Filter::m_pSource, m_StopMode, max(), and RageSoundReader::SetPosition().
Referenced by Read().
SetProperty()
bool RageSoundReader_Extend::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader.
References RageSoundReader_Filter::GetSampleRate(), M_CONTINUE, m_iFadeInFrames, m_iFadeOutFrames, m_iLengthFrames, m_iStartFrames, M_LOOP, M_STOP, and m_StopMode.
Member Data Documentation
m_bIgnoreFadeInFrames
bool RageSoundReader_Extend::m_bIgnoreFadeInFrames private
Referenced by RageSoundReader_Extend(), Read(), and SetPosition().
m_iFadeInFrames
int RageSoundReader_Extend::m_iFadeInFrames private
Referenced by RageSoundReader_Extend(), Read(), and SetProperty().
m_iFadeOutFrames
int RageSoundReader_Extend::m_iFadeOutFrames private
Referenced by RageSoundReader_Extend(), Read(), and SetProperty().
m_iLengthFrames
int RageSoundReader_Extend::m_iLengthFrames private
Referenced by GetData(), GetEndFrame(), RageSoundReader_Extend(), Read(), SetPosition(), and SetProperty().
m_iPositionFrames
int RageSoundReader_Extend::m_iPositionFrames private
Referenced by GetData(), GetNextSourceFrame(), RageSoundReader_Extend(), Read(), and SetPosition().
m_iStartFrames
int RageSoundReader_Extend::m_iStartFrames private
Referenced by GetEndFrame(), RageSoundReader_Extend(), Read(), and SetProperty().
m_StopMode
StopMode RageSoundReader_Extend::m_StopMode private
Referenced by RageSoundReader_Extend(), Read(), SetPosition(), and SetProperty().
The documentation for this class was generated from the following files:
RageSoundReader_Extend.h
RageSoundReader_Extend.cpp