Etterna: RageFileObjDeflate Class Reference
RageFileObjDeflate Class Reference
#include <RageFileDriverDeflate.h>
Public Member Functions
RageFileObjDeflate (RageFileBasic *pOutput)
~RageFileObjDeflate () override
int GetFileSize () const override
void DeleteFileWhenFinished ()
Public Member Functions inherited from RageFileObj
RageFileObj ()
RageFileObj (const RageFileObj &cpy)
~RageFileObj () override
RString GetError () const override
void ClearError () override
bool AtEOF () const override
int Seek (int iOffset) override
int Seek (int offset, int whence) override
int Tell () const override
int Read (void *pBuffer, size_t iBytes) override
int Read (RString &buffer, int bytes=-1) override
int Read (void *buffer, size_t bytes, int nmemb) override
int Write (const void *pBuffer, size_t iBytes) override
int Write (const RString &sString) override
int Write (const void *buffer, size_t bytes, int nmemb) override
int Flush () override
int GetLine (RString &out) override
int PutLine (const RString &str) override
void EnableCRC32 (bool on=true) override
bool GetCRC32 (uint32_t *iRet) override
int GetFD () override
RString GetDisplayPath () const override
RageFileBasic * Copy () const override
Public Member Functions inherited from RageFileBasic
virtual ~RageFileBasic ()=default
Protected Member Functions
int ReadInternal (void *, size_t) override
int WriteInternal (const void *pBuffer, size_t iBytes) override
int FlushInternal () override
Protected Member Functions inherited from RageFileObj
virtual int SeekInternal (int)
void EnableReadBuffering ()
void EnableWriteBuffering (int iBytes=1024 *64)
void SetError (const RString &sError)
Protected Attributes
RageFileBasic * m_pFile
z_stream * m_pDeflate
bool m_bFileOwned
Protected Attributes inherited from RageFileObj
RString m_sError
Constructor & Destructor Documentation
RageFileObjDeflate()
RageFileObjDeflate::RageFileObjDeflate (RageFileBasic * pOutput)
References m_bFileOwned, m_pDeflate, m_pFile, ssprintf(), RageException::Throw(), and WARN.
~RageFileObjDeflate()
RageFileObjDeflate::~RageFileObjDeflate () override
References FlushInternal(), m_bFileOwned, m_pDeflate, m_pFile, ssprintf(), and WARN.
Member Function Documentation
DeleteFileWhenFinished()
void RageFileObjDeflate::DeleteFileWhenFinished () inline
References m_bFileOwned.
FlushInternal()
int RageFileObjDeflate::FlushInternal () override protected virtual
Reimplemented from RageFileObj.
References FAIL_M, RageFileBasic::Flush(), RageFileBasic::GetError(), m_pDeflate, m_pFile, RageFileObj::SetError(), ssprintf(), and RageFileBasic::Write().
Referenced by ~RageFileObjDeflate().
GetFileSize()
int RageFileObjDeflate::GetFileSize () const inline override virtual
Implements RageFileObj.
References RageFileBasic::GetFileSize(), and m_pFile.
ReadInternal()
int RageFileObjDeflate::ReadInternal (void * , size_t) inline override protected virtual
Implements RageFileObj.
References RageFileObj::SetError().
WriteInternal()
int RageFileObjDeflate::WriteInternal (const void * pBuffer, size_t iBytes) override protected virtual
Implements RageFileObj.
References FAIL_M, RageFileBasic::GetError(), m_pDeflate, m_pFile, RageFileObj::SetError(), ssprintf(), and RageFileBasic::Write().
Member Data Documentation
m_bFileOwned
bool RageFileObjDeflate::m_bFileOwned protected
Referenced by DeleteFileWhenFinished(), RageFileObjDeflate(), and ~RageFileObjDeflate().
m_pDeflate
z_stream* RageFileObjDeflate::m_pDeflate protected
Referenced by FlushInternal(), RageFileObjDeflate(), WriteInternal(), and ~RageFileObjDeflate().
m_pFile
RageFileBasic* RageFileObjDeflate::m_pFile protected
Referenced by RageFileObjGzip::Finish(), FlushInternal(), GetFileSize(), RageFileObjDeflate(), RageFileObjGzip::Start(), WriteInternal(), and ~RageFileObjDeflate().
The documentation for this class was generated from the following files:
RageFileDriverDeflate.h
RageFileDriverDeflate.cpp