Etterna: OptionRowHandlerGameCommand Class Reference
OptionRowHandlerGameCommand Class Reference
Public Member Functions
OptionRowHandlerGameCommand ()
void Init () override
bool LoadInternal (const Commands &cmds) override
void ImportOption (OptionRow *pRow, const vector< PlayerNumber > &vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const override
int ExportOption (const vector< PlayerNumber > &vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const override
void GetIconTextAndGameCommand (int iFirstSelection, RString &sIconTextOut, GameCommand &gcOut) const override
RString GetScreen (int iChoice) const override
Public Member Functions inherited from OptionRowHandler
OptionRowHandler ()
virtual ~OptionRowHandler ()=default
bool Load (const Commands &cmds)
RString OptionTitle () const
RString GetThemedItemText (int iChoice) const
virtual ReloadChanged Reload ()
virtual int GetDefaultOption () const
virtual bool NotifyOfSelection (PlayerNumber pn, int choice)
virtual bool GoToFirstOnStart ()
Public Attributes
GameCommand m_gc
Public Attributes inherited from OptionRowHandler
OptionRowDefinition m_Def
vector< RString > m_vsReloadRowMessages
Additional Inherited Members
Public Types inherited from OptionRowHandler
enum ReloadChanged { RELOAD_CHANGED_NONE, RELOAD_CHANGED_ENABLED, RELOAD_CHANGED_ALL }
Constructor & Destructor Documentation
OptionRowHandlerGameCommand()
OptionRowHandlerGameCommand::OptionRowHandlerGameCommand () inline
References Init().
Member Function Documentation
ExportOption()
int OptionRowHandlerGameCommand::ExportOption (const vector< PlayerNumber > & vpns, const vector< bool > vbSelected[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::ApplyToAllPlayers(), PLAYER_1, and PLAYER_2.
GetIconTextAndGameCommand()
void OptionRowHandlerGameCommand::GetIconTextAndGameCommand (int iFirstSelection, RString & sIconTextOut, GameCommand & gcOut) const inline override virtual
Reimplemented from OptionRowHandler.
References m_gc.
GetScreen()
RString OptionRowHandlerGameCommand::GetScreen (int iChoice) const inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::m_sScreen.
ImportOption()
void OptionRowHandlerGameCommand::ImportOption (OptionRow * pRow, const vector< PlayerNumber > & vpns, vector< bool > vbSelectedOut[NUM_PLAYERS]) const inline override virtual
Reimplemented from OptionRowHandler.
Init()
void OptionRowHandlerGameCommand::Init () inline override virtual
Reimplemented from OptionRowHandler.
References GameCommand::ApplyCommitsScreens(), GameCommand::Init(), and OptionRowHandler::Init().
Referenced by OptionRowHandlerGameCommand().
LoadInternal()
bool OptionRowHandlerGameCommand::LoadInternal (const Commands & cmds) inline override virtual
Reimplemented from OptionRowHandler.
References LAYOUT_SHOW_ONE_IN_ROW, GameCommand::Load(), OptionRowDefinition::m_bOneChoiceForAllPlayers, OptionRowHandler::m_Def, OptionRowDefinition::m_layoutType, OptionRowDefinition::m_selectType, OptionRowDefinition::m_sName, GameCommand::m_sName, OptionRowDefinition::m_vsChoices, ROW_INVALID_IF, SELECT_NONE, and Commands::v.
Member Data Documentation
m_gc
GameCommand OptionRowHandlerGameCommand::m_gc
Referenced by GetIconTextAndGameCommand().
The documentation for this class was generated from the following file:
OptionRowHandler.cpp