Etterna: SplineSolutionCache Struct Reference
SplineSolutionCache Struct Reference
Classes
struct Entry
Public Member Functions
void solve_diagonals_straight (vector< float > &diagonals, vector< float > &multiples)
void solve_diagonals_looped (vector< float > &diagonals, vector< float > &multiples)
Private Member Functions
void prep_inner (size_t last, vector< float > &out)
bool find_in_cache (list< Entry > &cache, vector< float > &outd, vector< float > &outm)
void add_to_cache (list< Entry > &cache, vector< float > &outd, vector< float > &outm)
Private Attributes
list< Entry > straight_diagonals
list< Entry > looped_diagonals
Member Function Documentation
add_to_cache()
void SplineSolutionCache::add_to_cache (list< Entry > & cache, vector< float > & outd, vector< float > & outm) private
References solution_cache_limit.
Referenced by solve_diagonals_looped(), and solve_diagonals_straight().
find_in_cache()
bool SplineSolutionCache::find_in_cache (list< Entry > & cache, vector< float > & outd, vector< float > & outm) private
Referenced by solve_diagonals_looped(), and solve_diagonals_straight().
prep_inner()
void SplineSolutionCache::prep_inner (size_t last, vector< float > & out) private
Referenced by solve_diagonals_looped(), and solve_diagonals_straight().
solve_diagonals_looped()
void SplineSolutionCache::solve_diagonals_looped (vector< float > & diagonals, vector< float > & multiples)
References add_to_cache(), find_in_cache(), looped_diagonals, and prep_inner().
Referenced by CubicSpline::solve_looped().
solve_diagonals_straight()
void SplineSolutionCache::solve_diagonals_straight (vector< float > & diagonals, vector< float > & multiples)
References add_to_cache(), f, find_in_cache(), prep_inner(), and straight_diagonals.
Referenced by CubicSpline::solve_straight().
Member Data Documentation
looped_diagonals
list<Entry> SplineSolutionCache::looped_diagonals private
Referenced by solve_diagonals_looped().
straight_diagonals
list<Entry> SplineSolutionCache::straight_diagonals private
Referenced by solve_diagonals_straight().
The documentation for this struct was generated from the following file:
CubicSpline.cpp