Etterna: InputHandler_Linux_Joystick Class Reference
InputHandler_Linux_Joystick Class Reference
#include <InputHandler_Linux_Joystick.h>
Public Types
enum { NUM_JOYSTICKS = 4 }
Public Member Functions
InputHandler_Linux_Joystick ()
~InputHandler_Linux_Joystick ()
bool TryDevice (RString dev)
bool DevicesChanged ()
void GetDevicesAndDescriptions (vector< InputDeviceInfo > &vDevicesOut)
Public Member Functions inherited from InputHandler
InputHandler ()
~InputHandler () override=default
virtual void Update ()
virtual RString GetDeviceSpecificInputString (const DeviceInput &di)
virtual RString GetLocalizedInputString (const DeviceInput &di)
virtual wchar_t DeviceButtonToChar (DeviceButton button, bool bUseCurrentKeyModifiers)
virtual InputDeviceState GetInputDeviceState (InputDevice)
virtual void WindowReset ()
Public Member Functions inherited from RageDriver
virtual ~RageDriver ()=default
Private Member Functions
void StartThread ()
void StopThread ()
void InputThread ()
Static Private Member Functions
static int InputThread_Start (void *p)
Private Attributes
int fds [NUM_JOYSTICKS]
int m_iLastFd
RString m_sDescription [NUM_JOYSTICKS]
RageThread m_InputThread
bool m_bShutdown
bool m_bDevicesChanged
Additional Inherited Members
Static Public Member Functions inherited from InputHandler
static void Create (const RString &sDrivers, vector< InputHandler *> &apAdd)
static wchar_t ApplyKeyModifiers (wchar_t c)
Static Public Attributes inherited from InputHandler
static DriverList m_pDriverList
Protected Member Functions inherited from InputHandler
void ButtonPressed (DeviceInput di)
void UpdateTimer ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NUM_JOYSTICKS
Constructor & Destructor Documentation
InputHandler_Linux_Joystick()
InputHandler_Linux_Joystick::InputHandler_Linux_Joystick ()
References fds, LinuxInputManager::InitDriver(), LINUXINPUT, LOG, m_bDevicesChanged, m_iLastFd, NUM_JOYSTICKS, StartThread(), and RageLog::Trace().
~InputHandler_Linux_Joystick()
InputHandler_Linux_Joystick::~InputHandler_Linux_Joystick ()
References fds, RageThread::IsCreated(), m_InputThread, NUM_JOYSTICKS, and StopThread().
Member Function Documentation
DevicesChanged()
bool InputHandler_Linux_Joystick::DevicesChanged () inline virtual
Reimplemented from InputHandler.
References m_bDevicesChanged.
GetDevicesAndDescriptions()
void InputHandler_Linux_Joystick::GetDevicesAndDescriptions (vector< InputDeviceInfo > & vDevicesOut) virtual
Implements InputHandler.
References DEVICE_JOY1, fds, RageThread::IsCreated(), m_bDevicesChanged, m_InputThread, m_sDescription, NUM_JOYSTICKS, and StartThread().
InputThread()
void InputHandler_Linux_Joystick::InputThread () private
References InputHandler::ButtonPressed(), DEVICE_JOY1, enum_add2(), fds, JOY_BUTTON_1, JOY_LEFT, JOY_RIGHT, LOG, m_bShutdown, max(), NUM_JOYSTICKS, SCALE, InputHandler::UpdateTimer(), RageLog::Warn(), and wrap().
InputThread_Start()
int InputHandler_Linux_Joystick::InputThread_Start (void * p) static private
Referenced by StartThread().
StartThread()
void InputHandler_Linux_Joystick::StartThread () private
References RageThread::Create(), InputThread_Start(), m_bShutdown, m_InputThread, and RageThread::SetName().
Referenced by GetDevicesAndDescriptions(), InputHandler_Linux_Joystick(), and TryDevice().
StopThread()
void InputHandler_Linux_Joystick::StopThread () private
References LOG, m_bShutdown, m_InputThread, RageLog::Trace(), and RageThread::Wait().
Referenced by TryDevice(), and ~InputHandler_Linux_Joystick().
TryDevice()
bool InputHandler_Linux_Joystick::TryDevice (RString dev)
References fds, RageLog::Info(), RageThread::IsCreated(), LOG, m_bDevicesChanged, m_iLastFd, m_InputThread, m_sDescription, ssprintf(), StartThread(), StopThread(), RageLog::Warn(), and ZERO.
Referenced by LinuxInputManager::InitDriver().
Member Data Documentation
fds
int InputHandler_Linux_Joystick::fds[NUM_JOYSTICKS] private
Referenced by GetDevicesAndDescriptions(), InputHandler_Linux_Joystick(), InputThread(), TryDevice(), and ~InputHandler_Linux_Joystick().
m_bDevicesChanged
bool InputHandler_Linux_Joystick::m_bDevicesChanged private
Referenced by DevicesChanged(), GetDevicesAndDescriptions(), InputHandler_Linux_Joystick(), and TryDevice().
m_bShutdown
bool InputHandler_Linux_Joystick::m_bShutdown private
Referenced by InputThread(), StartThread(), and StopThread().
m_iLastFd
int InputHandler_Linux_Joystick::m_iLastFd private
Referenced by InputHandler_Linux_Joystick(), and TryDevice().
m_InputThread
RageThread InputHandler_Linux_Joystick::m_InputThread private
Referenced by GetDevicesAndDescriptions(), StartThread(), StopThread(), TryDevice(), and ~InputHandler_Linux_Joystick().
m_sDescription
RString InputHandler_Linux_Joystick::m_sDescription[NUM_JOYSTICKS] private
Referenced by GetDevicesAndDescriptions(), and TryDevice().
The documentation for this class was generated from the following files:
InputHandler_Linux_Joystick.h
InputHandler_Linux_Joystick.cpp