Etterna: InputMappings Class Reference
InputMappings Class Reference
#include <InputMapper.h>
Public Member Functions
void Clear ()
void Unmap (InputDevice id)
void WriteMappings (const InputScheme *pInputScheme, const RString &sFilePath)
void ReadMappings (const InputScheme *pInputScheme, const RString &sFilePath, bool bIsAutoMapping)
void SetInputMap (const DeviceInput &DeviceI, const GameInput &GameI, int iSlotIndex)
void ClearFromInputMap (const DeviceInput &DeviceI)
bool ClearFromInputMap (const GameInput &GameI, int iSlotIndex)
Public Attributes
RString m_sDeviceRegex
RString m_sDescription
DeviceInput m_GItoDI [NUM_GameController][NUM_GameButton][NUM_GAME_TO_DEVICE_SLOTS]
Member Function Documentation
Clear()
void InputMappings::Clear ()
References FOREACH_ENUM, m_GItoDI, and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by InputMapper::ClearAllMappings(), ReadMappings(), and InputMapper::ResetMappingsToDefault().
ClearFromInputMap() [1/2]
void InputMappings::ClearFromInputMap (const DeviceInput & DeviceI)
References FOREACH_ENUM, m_GItoDI, DeviceInput::MakeInvalid(), and NUM_GAME_TO_DEVICE_SLOTS.
Referenced by InputMapper::ClearFromInputMap(), and SetInputMap().
ClearFromInputMap() [2/2]
bool InputMappings::ClearFromInputMap (const GameInput & GameI, int iSlotIndex)
References GameInput::button, GameInput::controller, GameInput::IsValid(), DeviceInput::IsValid(), m_GItoDI, and DeviceInput::MakeInvalid().
ReadMappings()
void InputMappings::ReadMappings (const InputScheme * pInputScheme, const RString & sFilePath, bool bIsAutoMapping)
References Clear(), FOREACH_CONST_Attr, GameInput::FromString(), DeviceInput::FromString(), XNode::GetChild(), IniFile::GetError(), IniFile::GetValue(), GameInput::IsValid(), DeviceInput::IsValid(), SpecialFiles::KEYMAPS_PATH, LOG, m_sDescription, m_sDeviceRegex, InputScheme::m_szName, NUM_GAME_TO_DEVICE_SLOTS, IniFile::ReadFile(), SetInputMap(), split(), and RageLog::Trace().
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), and InputMapper::ReadMappingsFromDisk().
SetInputMap()
void InputMappings::SetInputMap (const DeviceInput & DeviceI, const GameInput & GameI, int iSlotIndex)
References ASSERT_M, GameInput::button, ClearFromInputMap(), GameInput::controller, m_GItoDI, NUM_GAME_TO_DEVICE_SLOTS, NUM_GameButton, NUM_GameController, and ssprintf().
Referenced by ReadMappings(), and InputMapper::SetInputMap().
Unmap()
void InputMappings::Unmap (InputDevice id)
References DeviceInput::device, FOREACH_ENUM, m_GItoDI, DeviceInput::MakeInvalid(), and NUM_USER_GAME_TO_DEVICE_SLOTS.
Referenced by InputMapper::Unmap().
WriteMappings()
void InputMappings::WriteMappings (const InputScheme * pInputScheme, const RString & sFilePath)
References XNode::AppendAttr(), XNode::AppendChild(), IniFile::DeleteKey(), FOREACH_ENUM, FOREACH_GameButtonInScheme, XNode::GetChild(), Rage::join(), m_GItoDI, InputScheme::m_szName, NUM_USER_GAME_TO_DEVICE_SLOTS, IniFile::ReadFile(), XNode::RemoveChild(), GameInput::ToString(), DeviceInput::ToString(), and IniFile::WriteFile().
Referenced by InputMapper::SaveMappingsToDisk().
Member Data Documentation
m_GItoDI
DeviceInput InputMappings::m_GItoDI[NUM_GameController][NUM_GameButton][NUM_GAME_TO_DEVICE_SLOTS]
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), InputMapper::CheckButtonAndAddToReason(), Clear(), ClearFromInputMap(), InputMapper::GameToDevice(), SetInputMap(), Unmap(), InputMapper::UpdateTempDItoGI(), and WriteMappings().
m_sDescription
RString InputMappings::m_sDescription
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), and ReadMappings().
m_sDeviceRegex
RString InputMappings::m_sDeviceRegex
Referenced by InputMapper::AutoMapJoysticksForCurrentGame(), and ReadMappings().
The documentation for this class was generated from the following files:
InputMapper.h
InputMapper.cpp