Etterna: StepMania.cpp File Reference
StepMania.cpp File Reference
#include "global.h"
#include "StepMania.h"
#include "ActorUtil.h"
#include "GameSoundManager.h"
#include "LocalizedString.h"
#include "MemoryCardManager.h"
#include "RageDisplay.h"
#include "RageInput.h"
#include "RageLog.h"
#include "RageMath.h"
#include "RageSoundManager.h"
#include "RageTextureManager.h"
#include "RageThreads.h"
#include "RageTimer.h"
#include "arch/ArchHooks/ArchHooks.h"
#include "arch/Dialog/Dialog.h"
#include "arch/LoadingWindow/LoadingWindow.h"
#include <ctime>
#include "ProductInfo.h"
#include "CodeDetector.h"
#include "CommandLineActions.h"
#include "CommonMetrics.h"
#include "Game.h"
#include "InputEventPlus.h"
#include "RageSurface.h"
#include "RageSurface_Load.h"
#include "Screen.h"
#include "ScreenDimensions.h"
#include "AnnouncerManager.h"
#include "CharacterManager.h"
#include "FilterManager.h"
#include "FontManager.h"
#include "GameManager.h"
#include "GameState.h"
#include "ImageCache.h"
#include "InputFilter.h"
#include "InputMapper.h"
#include "InputQueue.h"
#include "NoteSkinManager.h"
#include "SongCacheIndex.h"
#include "DownloadManager.h"
#include "CryptManager.h"
#include "GameLoop.h"
#include "MessageManager.h"
#include "ModelManager.h"
#include "NetworkSyncManager.h"
#include "RageFileManager.h"
#include "ScoreManager.h"
#include "SpecialFiles.h"
#include "StatsManager.h"
#include "ver.h"
#include "RageDisplay_OGL.h"
#include "RageDisplay_Null.h"
#include "LuaManager.h"
Classes
struct VideoCardDefaults
Macros
#define SUPPORT_OPENGL
Functions
void ShutdownGame ()
bool HandleGlobalInputs (const InputEventPlus &input)
void HandleInputEvents (float fDeltaTime)
static RString GetActualGraphicOptionsString ()
static void StoreActualGraphicOptions ()
static RageDisplay * CreateDisplay ()
static void update_centering ()
static void StartDisplay ()
static bool CheckVideoDefaultSettings ()
static void HandleException (const RString &sError)
static void AdjustForChangedSystemCapabilities ()
static RString GetVideoDriverName ()
static void SwitchToLastPlayedGame ()
static void MountTreeOfZips (const RString &dir)
static void WriteLogHeader ()
static void ApplyLogPreferences ()
int sm_main (int argc, char *argv[])
int LuaFunc_SaveScreenshot (lua_State *L)
void LuaFunc_Register_SaveScreenshot (lua_State *L)
REGISTER_WITH_LUA_FUNCTION (LuaFunc_Register_SaveScreenshot)
static int LuaFunc_update_centering (lua_State *L)
LUAFUNC_REGISTER_COMMON (update_centering)
Variables
static Preference< bool > g_bAllowMultipleInstances ("AllowMultipleInstances", false)
static LocalizedString COLOR ("Etterna", "color")
static LocalizedString TEXTURE ("Etterna", "texture")
static LocalizedString WINDOWED ("Etterna", "Windowed")
static LocalizedString FULLSCREEN ("Etterna", "Fullscreen")
static LocalizedString ANNOUNCER_ ("Etterna", "Announcer")
static LocalizedString VSYNC ("Etterna", "Vsync")
static LocalizedString NO_VSYNC ("Etterna", "NoVsync")
static LocalizedString SMOOTH_LINES ("Etterna", "SmoothLines")
static LocalizedString NO_SMOOTH_LINES ("Etterna", "NoSmoothLines")
ThemeMetric< RString > INITIAL_SCREEN ("Common", "InitialScreen")
ThemeMetric< RString > SELECT_MUSIC_SCREEN ("Common", "SelectMusicScreen")
struct VideoCardDefaults g_VideoCardDefaults []
static LocalizedString ERROR_INITIALIZING_CARD ("Etterna", "There was an error while initializing your video card.")
static LocalizedString ERROR_DONT_FILE_BUG ("Etterna", "Please do not file this error as a " "bug! Use the web page below to " "troubleshoot this problem.")
static LocalizedString ERROR_VIDEO_DRIVER ("Etterna", "Video Driver: %s")
static LocalizedString ERROR_NO_VIDEO_RENDERERS ("Etterna", "No video renderers attempted.")
static LocalizedString ERROR_INITIALIZING ("Etterna", "Initializing %s...")
static LocalizedString ERROR_UNKNOWN_VIDEO_RENDERER ("Etterna", "Unknown video renderer value: %s")
static LocalizedString COULDNT_OPEN_LOADING_WINDOW ("LoadingWindow", "Couldn't open any loading windows.")
static LocalizedString SERVICE_SWITCH_PRESSED ("Etterna", "Service switch pressed")
static LocalizedString RELOADED_METRICS ("ThemeManager", "Reloaded metrics")
static LocalizedString RELOADED_METRICS_AND_TEXTURES ("ThemeManager", "Reloaded metrics and textures")
static LocalizedString RELOADED_SCRIPTS ("ThemeManager", "Reloaded scripts")
static LocalizedString RELOADED_OVERLAY_SCREENS ("ThemeManager", "Reloaded overlay screens")
Macro Definition Documentation
SUPPORT_OPENGL
#define SUPPORT_OPENGL
Function Documentation
AdjustForChangedSystemCapabilities()
static void AdjustForChangedSystemCapabilities () static
References LOG, PrefsManager::m_bDelayedTextureDelete, PREFSMAN, PrefsManager::SavePrefsToDisk(), Preference< T >::Set(), and RageLog::Trace().
Referenced by sm_main().
ApplyLogPreferences()
static void ApplyLogPreferences () static
References LOG, Checkpoints::LogCheckpoints(), PrefsManager::m_bForceLogFlush, PrefsManager::m_bLogCheckpoints, PrefsManager::m_bLogToDisk, PrefsManager::m_bShowLogOutput, PREFSMAN, RageLog::SetFlushing(), RageLog::SetInfoToDisk(), RageLog::SetLogToDisk(), RageLog::SetShowLogOutput(), and RageLog::SetUserLogToDisk().
Referenced by sm_main().
CheckVideoDefaultSettings()
bool CheckVideoDefaultSettings () static
References ARRAYLEN, VideoCardDefaults::bSmoothLines, Regex::Compare(), FAIL_M, g_VideoCardDefaults, GetVideoDriverName(), VideoCardDefaults::iDisplayColor, VideoCardDefaults::iHeight, VideoCardDefaults::iMovieColor, RageLog::Info(), VideoCardDefaults::iTextureColor, VideoCardDefaults::iTextureSize, VideoCardDefaults::iWidth, LOG, PrefsManager::m_bSmoothLines, PrefsManager::m_fDisplayAspectRatio, PrefsManager::m_iDisplayColorDepth, PrefsManager::m_iDisplayHeight, PrefsManager::m_iDisplayWidth, PrefsManager::m_iMaxTextureResolution, PrefsManager::m_iMovieColorDepth, PrefsManager::m_iTextureColorDepth, PrefsManager::m_sLastSeenVideoDriver, PrefsManager::m_sVideoRenderers, PREFSMAN, VideoCardDefaults::sDriverRegex, Preference< T >::Set(), VideoCardDefaults::sVideoRenderers, RageLog::Trace(), and RageLog::Warn().
Referenced by CreateDisplay(), and StepMania::ResetPreferences().
CreateDisplay()
RageDisplay * CreateDisplay () static
References CheckVideoDefaultSettings(), StdString::CStdStr< CT >::CompareNoCase(), ERROR_DONT_FILE_BUG, ERROR_INITIALIZING, ERROR_INITIALIZING_CARD, ERROR_NO_VIDEO_RENDERERS, ERROR_UNKNOWN_VIDEO_RENDERER, ERROR_VIDEO_DRIVER, StepMania::GetPreferredVideoModeParams(), LocalizedString::GetValue(), GetVideoDriverName(), RageDisplay::Init(), PrefsManager::m_bAllowUnacceleratedRenderer, PrefsManager::m_sVideoRenderers, PREFSMAN, SAFE_DELETE, split(), ssprintf(), RageException::Throw(), and VIDEO_TROUBLESHOOTING_URL.
Referenced by StartDisplay().
GetActualGraphicOptionsString()
static RString GetActualGraphicOptionsString () static
References VideoModeParams::bpp, COLOR, DISPLAY, FULLSCREEN, RageDisplay::GetActualVideoModeParams(), RageDisplay::GetApiDescription(), LocalizedString::GetValue(), VideoModeParams::height, PrefsManager::m_bSmoothLines, PrefsManager::m_iTextureColorDepth, NO_SMOOTH_LINES, NO_VSYNC, PREFSMAN, VideoModeParams::rate, SMOOTH_LINES, ssprintf(), TEXTURE, VSYNC, VideoModeParams::vsync, VideoModeParams::width, WINDOWED, and VideoModeParams::windowed.
Referenced by StepMania::ApplyGraphicOptions(), and sm_main().
GetVideoDriverName()
static RString GetVideoDriverName () static
Referenced by CheckVideoDefaultSettings(), and CreateDisplay().
HandleException()
static void HandleException (const RString & sError) static
References g_bAutoRestart, HOOKS, ArchHooks::RestartProgram(), Shutdown(), and ShutdownGame().
Referenced by sm_main().
HandleGlobalInputs()
bool HandleGlobalInputs (const InputEventPlus & input)
References ScreenManager::AllowOperatorMenuButton(), MessageManager::Broadcast(), DEVICE_KEYBOARD, InputEventPlus::DeviceI, GAME_BUTTON_OPERATOR, GAMESTATE, RageTimer::GetDeltaTime(), IET_FIRST_PRESS, INPUTFILTER, InputEventPlus::InputList, InputFilter::IsBeingPressed(), KEY_Cq, KEY_ENTER, KEY_F12, KEY_F13, KEY_F2, KEY_F4, KEY_LALT, KEY_LCTRL, KEY_LMETA, KEY_LSHIFT, KEY_PAUSE, KEY_PRTSC, KEY_RALT, KEY_RCTRL, KEY_RMETA, KEY_RSHIFT, LOG, GameState::m_pCurGame, InputEventPlus::MenuI, MESSAGEMAN, NOTESKIN, CommonMetrics::OPERATOR_MENU_SCREEN, ScreenManager::PopAllScreens(), CodeDetector::RefreshCacheItems(), NoteSkinManager::RefreshNoteSkinData(), RageTextureManager::ReloadAll(), RELOADED_METRICS, RELOADED_METRICS_AND_TEXTURES, RELOADED_OVERLAY_SCREENS, RELOADED_SCRIPTS, ThemeManager::ReloadMetrics(), ScreenManager::ReloadOverlayScreens(), GameState::Reset(), StepMania::SaveScreenshot(), SCREENMAN, SERVICE_SWITCH_PRESSED, ScreenManager::SetNewScreen(), ArchHooks::SetToggleWindowed(), ArchHooks::SetUserQuit(), ScreenManager::SystemMessage(), TEXTUREMAN, THEME, RageLog::Trace(), InputEventPlus::type, and ThemeManager::UpdateLuaGlobals().
Referenced by HandleInputEvents().
HandleInputEvents()
void HandleInputEvents (float fDeltaTime)
References ArchHooks::AppHasFocus(), StepMania::ApplyGraphicOptions(), ASSERT, GameInput::button, CODE_BACK_IN_EVENT_MODE, GameInput::controller, InputMapper::ControllerToPlayerNumber(), DeviceInput::device, DEVICE_JOY1, InputEventPlus::DeviceI, InputMapper::DeviceToGame(), CodeDetector::EnteredCode(), FOREACH_ENUM, GAME_BUTTON_BACK, GameButton_Invalid, InputMapper::GameButtonToMenuButton(), InputEventPlus::GameI, GAMESTATE, ArchHooks::GetAndClearToggleWindowed(), InputFilter::GetInputEvents(), ScreenManager::GetTopScreen(), HandleGlobalInputs(), HOOKS, IET_FIRST_PRESS, ScreenManager::Input(), InputMapper::InputDeviceToMultiPlayer(), INPUTFILTER, InputEventPlus::InputList, INPUTMAPPER, INPUTQUEUE, GameState::IsEventMode(), Actor::IsFirstUpdate(), DeviceInput::IsJoystick(), GameInput::IsValid(), GameState::m_bMultiplayer, PrefsManager::m_bWindowed, InputEventPlus::MenuI, InputEventPlus::mp, MultiPlayer_Invalid, NUM_MultiPlayer, InputEventPlus::pn, PREFSMAN, InputQueue::RememberInput(), InputMapper::RepeatStopKey(), SCREENMAN, Preference< T >::Set(), swap(), InputEventPlus::type, and InputFilter::Update().
Referenced by GameLoop::RunGameLoop().
LUAFUNC_REGISTER_COMMON()
LUAFUNC_REGISTER_COMMON (update_centering)
LuaFunc_Register_SaveScreenshot()
void LuaFunc_Register_SaveScreenshot (lua_State * L)
References LuaFunc_SaveScreenshot().
LuaFunc_SaveScreenshot()
int LuaFunc_SaveScreenshot (lua_State * L)
References ProfileManager::GetProfileDir(), L, PlayerNumber_Invalid, PROFILEMAN, and StepMania::SaveScreenshot().
Referenced by LuaFunc_Register_SaveScreenshot().
LuaFunc_update_centering()
static int LuaFunc_update_centering (lua_State * L) static
References update_centering().
MountTreeOfZips()
static void MountTreeOfZips (const RString & dir) static
References FILEMAN, GetDirListing(), IsADirectory(), IsAFile(), LOG, RageFileManager::Mount(), and RageLog::Trace().
REGISTER_WITH_LUA_FUNCTION()
REGISTER_WITH_LUA_FUNCTION (LuaFunc_Register_SaveScreenshot)
ShutdownGame()
void ShutdownGame ()
References ANNOUNCER, CHARMAN, CRYPTMAN, DISPLAY, DLMAN, FILEMAN, FONT, GAMEMAN, GAMESTATE, HOOKS, IMAGECACHE, INPUTFILTER, INPUTMAN, INPUTMAPPER, INPUTQUEUE, LOG, LUA, MEMCARDMAN, MESSAGEMAN, MODELMAN, NOTESKIN, NSMAN, PREFSMAN, PROFILEMAN, SAFE_DELETE, SCREENMAN, RageSoundManager::Shutdown(), Shutdown(), SONGINDEX, SONGMAN, SOUND, SOUNDMAN, STATSMAN, TEXTUREMAN, and THEME.
Referenced by HandleException(), and sm_main().
sm_main()
int sm_main (int argc, char * argv[])
References AdjustForChangedSystemCapabilities(), ANNOUNCER, ApplyLogPreferences(), CHARMAN, InputMapper::CheckForChangedInputDevicesAndRemap(), ArchHooks::CheckForMultipleInstances(), COULDNT_OPEN_LOADING_WINDOW, ArchHooks::Create(), LoadingWindow::Create(), CRYPTMAN, NetworkSyncManager::DisplayStartupStatus(), DLMAN, DoesFileExist(), ArchHooks::DumpDebugInfo(), FAIL_M, FILEMAN, FILTERMAN, SongCacheIndex::FinishTransaction(), FONT, g_bAllowMultipleInstances, g_RandomNumberGenerator, GAMEMAN, GAMESTATE, CryptManager::GenerateGlobalKeys(), Preference< T >::Get(), GetActualGraphicOptionsString(), GetCommandlineArgument(), GameState::GetCurrentGame(), NetworkSyncManager::GetCurrentSMBuild(), StepMania::GetInitialScreen(), ThemeManager::GetPathG(), RageThread::GetSupportsTLS(), LocalizedString::GetValue(), ArchHooks::GoToURL(), CommandLineActions::Handle(), HandleException(), HOOKS, IMAGECACHE, RageLog::Info(), ArchHooks::Init(), Init(), ProfileManager::Init(), RageSoundManager::Init(), SongManager::InitAll(), ActorUtil::InitFileTypeLists(), StepMania::InitializeCurrentGame(), INPUTFILTER, INPUTMAN, INPUTMAPPER, INPUTQUEUE, RageSurfaceUtils::LoadFile(), LOG, LUA, GameState::m_bDopefish, PrefsManager::m_bSignProfileData, PrefsManager::m_iSoundWriteAhead, PrefsManager::m_sAdditionalFolders, PrefsManager::m_sAdditionalSongFolders, MEMCARDMAN, MESSAGEMAN, RageFileManager::Mount(), RageFileManager::MountInitialFilesystems(), RageFileManager::MountUserFilesystems(), NOTESKIN, NSMAN, PREFSMAN, SongManager::PreloadSongImages(), PRODUCT_ID, PROFILEMAN, PrefsManager::ReadPrefsFromDisk(), CodeDetector::RefreshCacheItems(), ArchHooks::RegisterWithLua(), StepMania::ResetGame(), GameLoop::RunGameLoop(), SAFE_DELETE, PrefsManager::SavePrefsToDisk(), SCOREMAN, SCREENMAN, seed_lua_prng(), RageException::SetCleanupHandler(), SetCommandlineArguments(), LoadingWindow::SetIcon(), RageSoundManager::SetMixVolume(), ScreenManager::SetNewScreen(), LoadingWindow::SetSplash(), ShutdownGame(), SM_DOWNLOAD_URL, SONGINDEX, SONGMAN, SOUND, SOUNDMAN, split(), StartDisplay(), SongCacheIndex::StartTransaction(), STATSMAN, StoreActualGraphicOptions(), SwitchToLastPlayedGame(), ScreenManager::SystemMessage(), THEME, ScreenManager::ThemeChanged(), RageException::Throw(), SongManager::UpdatePreferredSort(), ArchHooks::UserQuit(), version_num, and WriteLogHeader().
Referenced by main().
StartDisplay()
static void StartDisplay () static
References CreateDisplay(), DISPLAY, StepMania::GetHighResolutionTextures(), PrefsManager::m_bDelayedModelDelete, PrefsManager::m_bDelayedTextureDelete, PrefsManager::m_bForceMipMaps, PrefsManager::m_iMaxTextureResolution, PrefsManager::m_iMovieColorDepth, PrefsManager::m_iTextureColorDepth, MODELMAN, PREFSMAN, ModelManager::SetPrefs(), RageTextureManager::SetPrefs(), TEXTUREMAN, and update_centering().
Referenced by sm_main().
StoreActualGraphicOptions()
static void StoreActualGraphicOptions () static
References VideoModeParams::bpp, DISPLAY, RageDisplay::GetActualVideoModeParams(), VideoModeParams::height, PrefsManager::m_bVsync, PrefsManager::m_bWindowed, PrefsManager::m_iDisplayColorDepth, PrefsManager::m_iDisplayHeight, PrefsManager::m_iDisplayWidth, PrefsManager::m_iRefreshRate, PREFSMAN, VideoModeParams::rate, REFRESH_DEFAULT, Preference< T >::Set(), VideoModeParams::vsync, VideoModeParams::width, and VideoModeParams::windowed.
Referenced by StepMania::ApplyGraphicOptions(), and sm_main().
SwitchToLastPlayedGame()
static void SwitchToLastPlayedGame () static
References ASSERT, GAMEMAN, PrefsManager::GetCurrentGame(), GameManager::GetDefaultGame(), StepMania::InitializeCurrentGame(), GameManager::IsGameEnabled(), LOG, Game::m_szName, PREFSMAN, GameManager::StringToGame(), and RageLog::Warn().
Referenced by sm_main().
update_centering()
static void update_centering () static
References RageDisplay::ChangeCentering(), DISPLAY, PrefsManager::m_fCenterImageAddHeight, PrefsManager::m_fCenterImageAddWidth, PrefsManager::m_iCenterImageTranslateX, PrefsManager::m_iCenterImageTranslateY, and PREFSMAN.
Referenced by StepMania::ApplyGraphicOptions(), LuaFunc_update_centering(), and StartDisplay().
WriteLogHeader()
static void WriteLogHeader () static
References g_argc, g_argv, RageLog::Info(), LOG, PRODUCT_FAMILY, product_version, sm_version_git_hash, ssprintf(), RageLog::Trace(), version_date, and version_time.
Referenced by sm_main().
Variable Documentation
ANNOUNCER_
LocalizedString ANNOUNCER_("Etterna", "Announcer") static
COLOR
LocalizedString COLOR("Etterna", "color") static
Referenced by GetActualGraphicOptionsString().
COULDNT_OPEN_LOADING_WINDOW
LocalizedString COULDNT_OPEN_LOADING_WINDOW("LoadingWindow", "Couldn't open any loading windows.") static
Referenced by sm_main().
ERROR_DONT_FILE_BUG
LocalizedString ERROR_DONT_FILE_BUG("Etterna", "Please do not file this error as a " "bug! Use the web page below to " "troubleshoot this problem.") static
Referenced by CreateDisplay().
ERROR_INITIALIZING
LocalizedString ERROR_INITIALIZING("Etterna", "Initializing %s...") static
Referenced by CreateDisplay().
ERROR_INITIALIZING_CARD
LocalizedString ERROR_INITIALIZING_CARD("Etterna", "There was an error while initializing your video card.") static
Referenced by CreateDisplay().
ERROR_NO_VIDEO_RENDERERS
LocalizedString ERROR_NO_VIDEO_RENDERERS("Etterna", "No video renderers attempted.") static
Referenced by CreateDisplay().
ERROR_UNKNOWN_VIDEO_RENDERER
LocalizedString ERROR_UNKNOWN_VIDEO_RENDERER("Etterna", "Unknown video renderer value: %s") static
Referenced by CreateDisplay().
ERROR_VIDEO_DRIVER
LocalizedString ERROR_VIDEO_DRIVER("Etterna", "Video Driver: %s") static
Referenced by CreateDisplay().
FULLSCREEN
LocalizedString FULLSCREEN("Etterna", "Fullscreen") static
Referenced by GetActualGraphicOptionsString().
g_bAllowMultipleInstances
Preference<bool> g_bAllowMultipleInstances("AllowMultipleInstances", false) static
Referenced by sm_main().
g_VideoCardDefaults
struct VideoCardDefaults g_VideoCardDefaults[]
Referenced by CheckVideoDefaultSettings().
INITIAL_SCREEN
ThemeMetric<RString> INITIAL_SCREEN("Common", "InitialScreen")
Referenced by StepMania::GetInitialScreen().
NO_SMOOTH_LINES
LocalizedString NO_SMOOTH_LINES("Etterna", "NoSmoothLines") static
Referenced by GetActualGraphicOptionsString().
NO_VSYNC
LocalizedString NO_VSYNC("Etterna", "NoVsync") static
Referenced by GetActualGraphicOptionsString().
RELOADED_METRICS
LocalizedString RELOADED_METRICS("ThemeManager", "Reloaded metrics") static
Referenced by HandleGlobalInputs().
RELOADED_METRICS_AND_TEXTURES
LocalizedString RELOADED_METRICS_AND_TEXTURES("ThemeManager", "Reloaded metrics and textures") static
Referenced by HandleGlobalInputs().
RELOADED_OVERLAY_SCREENS
LocalizedString RELOADED_OVERLAY_SCREENS("ThemeManager", "Reloaded overlay screens") static
Referenced by HandleGlobalInputs().
RELOADED_SCRIPTS
LocalizedString RELOADED_SCRIPTS("ThemeManager", "Reloaded scripts") static
Referenced by HandleGlobalInputs().
SELECT_MUSIC_SCREEN
ThemeMetric<RString> SELECT_MUSIC_SCREEN("Common", "SelectMusicScreen")
Referenced by StepMania::GetSelectMusicScreen().
SERVICE_SWITCH_PRESSED
LocalizedString SERVICE_SWITCH_PRESSED("Etterna", "Service switch pressed") static
Referenced by HandleGlobalInputs().
SMOOTH_LINES
LocalizedString SMOOTH_LINES("Etterna", "SmoothLines") static
Referenced by GetActualGraphicOptionsString().
TEXTURE
LocalizedString TEXTURE("Etterna", "texture") static
Referenced by GetActualGraphicOptionsString().
VSYNC
LocalizedString VSYNC("Etterna", "Vsync") static
Referenced by GetActualGraphicOptionsString().
WINDOWED
LocalizedString WINDOWED("Etterna", "Windowed") static
Referenced by GetActualGraphicOptionsString().