Etterna: RageSoundReader_Pan Class Reference
RageSoundReader_Pan Class Reference
#include <RageSoundReader_Pan.h>
Public Member Functions
RageSoundReader_Pan (RageSoundReader *pSource)
RageSoundReader_Pan * Copy () const override
unsigned GetNumChannels () const override
int Read (float *pBuf, int iFrames) override
bool SetProperty (const RString &sProperty, float fValue) override
Public Member Functions inherited from RageSoundReader_Filter
RageSoundReader_Filter (RageSoundReader *pSource)
int GetLength () const override
int GetLength_Fast () const override
int SetPosition (int iFrame) override
int GetSampleRate () const override
int GetNextSourceFrame () const override
float GetStreamToSourceRatio () const override
RageSoundReader * GetSource () override
RString GetError () const override
Public Member Functions inherited from RageSoundReader
virtual ~RageSoundReader ()=default
int RetriedRead (float *pBuffer, int iFrames, int *iSourceFrame=NULL, float *fRate=NULL)
Private Attributes
float m_fPan
Additional Inherited Members
Public Types inherited from RageSoundReader
enum { RSRERROR = -1, END_OF_FILE = -2, WOULD_BLOCK = -3, STREAM_LOOPED = -4 }
Protected Attributes inherited from RageSoundReader_Filter
HiddenPtr< RageSoundReader > m_pSource
Constructor & Destructor Documentation
RageSoundReader_Pan()
RageSoundReader_Pan::RageSoundReader_Pan (RageSoundReader * pSource)
References m_fPan.
Referenced by Copy().
Member Function Documentation
Copy()
RageSoundReader_Pan* RageSoundReader_Pan::Copy () const inline override virtual
Implements RageSoundReader.
References RageSoundReader_Pan().
GetNumChannels()
unsigned RageSoundReader_Pan::GetNumChannels () const override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundReader_Filter::GetNumChannels(), and max().
Referenced by Read().
Read()
int RageSoundReader_Pan::Read (float * pBuf, int iFrames) override virtual
Reimplemented from RageSoundReader_Filter.
References RageSoundUtil::ConvertMonoToStereoInPlace(), RageSoundReader::GetNumChannels(), GetNumChannels(), m_fPan, RageSoundReader_Filter::m_pSource, RageSoundUtil::Pan(), and RageSoundReader::Read().
SetProperty()
bool RageSoundReader_Pan::SetProperty (const RString & sProperty, float fValue) override virtual
Reimplemented from RageSoundReader_Filter.
References m_fPan, and RageSoundReader_Filter::SetProperty().
Member Data Documentation
m_fPan
float RageSoundReader_Pan::m_fPan private
Referenced by RageSoundReader_Pan(), Read(), and SetProperty().
The documentation for this class was generated from the following files:
RageSoundReader_Pan.h
RageSoundReader_Pan.cpp