Etterna: Command Class Reference
Command Class Reference
#include <Command.h>
Classes
struct Arg
Public Member Functions
void Load (const RString &sCommand)
RString GetOriginalCommandString () const
RString GetName () const
void Clear ()
Arg GetArg (unsigned index) const
Command ()
Public Attributes
vector< RString > m_vsArgs
Constructor & Destructor Documentation
Command()
Command::Command () inline
Member Function Documentation
Clear()
void Command::Clear () inline
References m_vsArgs.
GetArg()
Command::Arg Command::GetArg (unsigned index) const
References m_vsArgs, and Command::Arg::s.
Referenced by OptionRowHandlerList::LoadInternal(), OptionRowHandlerSteps::LoadInternal(), OptionRowHandlerLua::LoadInternal(), OptionRowHandlerConfig::LoadInternal(), OptionRowHandlerStepsType::LoadInternal(), and OptionRowHandlerUtil::Make().
GetName()
RString Command::GetName () const
References m_vsArgs, and Trim().
Referenced by OptionRowHandlerList::LoadInternal(), and GameCommand::LoadOne().
GetOriginalCommandString()
RString Command::GetOriginalCommandString () const
References Rage::join(), and m_vsArgs.
Referenced by GameCommand::LoadOne().
Load()
void Command::Load (const RString & sCommand)
References m_vsArgs, and split().
Referenced by ParseCommands().
Member Data Documentation
m_vsArgs
vector<RString> Command::m_vsArgs
Referenced by Clear(), GetArg(), GetName(), GetOriginalCommandString(), Load(), OptionRowHandlerList::LoadInternal(), GameCommand::LoadOne(), and OptionRowHandlerUtil::Make().
The documentation for this class was generated from the following files:
Command.h
Command.cpp