Etterna: RageTextureManager Class Reference
RageTextureManager Class Reference
#include <RageTextureManager.h>
Public Member Functions
RageTextureManager ()
~RageTextureManager ()
void Update (float fDeltaTime)
RageTexture * LoadTexture (const RageTextureID &ID)
RageTexture * CopyTexture (RageTexture *pCopy)
bool IsTextureRegistered (RageTextureID ID) const
void RegisterTexture (RageTextureID ID, RageTexture *p)
void VolatileTexture (const RageTextureID &ID)
void UnloadTexture (RageTexture *t)
void ReloadAll ()
void RegisterTextureForUpdating (const RageTextureID &id, RageTexture *tex)
bool SetPrefs (RageTextureManagerPrefs prefs)
RageTextureManagerPrefs GetPrefs ()
RageTextureID::TexPolicy GetDefaultTexturePolicy () const
void SetDefaultTexturePolicy (const RageTextureID::TexPolicy &p)
void DeleteCachedTextures ()
void DoDelayedDelete ()
void InvalidateTextures ()
void AdjustTextureID (RageTextureID &ID) const
void DiagnosticOutput () const
void DisableOddDimensionWarning ()
void EnableOddDimensionWarning ()
bool GetOddDimensionWarning () const
RageTextureID GetDefaultTextureID ()
RageTextureID GetScreenTextureID ()
RageSurface * GetScreenSurface ()
Private Types
enum GCType { screen_changed, delayed_delete }
Private Member Functions
void DeleteTexture (RageTexture *t)
void GarbageCollect (GCType type)
RageTexture * LoadTextureInternal (RageTextureID ID)
Private Attributes
RageTextureManagerPrefs m_Prefs
int m_iNoWarnAboutOddDimensions { 0 }
RageTextureID::TexPolicy m_TexturePolicy { RageTextureID::TEX_DEFAULT }
Member Enumeration Documentation
GCType
enum RageTextureManager::GCType private
Enumerator
screen_changed
delayed_delete
Constructor & Destructor Documentation
RageTextureManager()
RageTextureManager::RageTextureManager ()
~RageTextureManager()
RageTextureManager::~RageTextureManager ()
References FOREACHM, LOG, RageTexture::m_iRefCount, SAFE_DELETE, and RageLog::Trace().
Member Function Documentation
AdjustTextureID()
void RageTextureManager::AdjustTextureID (RageTextureID & ID) const
References RageTextureID::bMipMaps, RageTextureID::iColorDepth, RageTextureID::iMaxSize, RageTextureManagerPrefs::m_bMipMaps, RageTextureManagerPrefs::m_iMaxTextureResolution, RageTextureManagerPrefs::m_iTextureColorDepth, m_Prefs, and min().
Referenced by IsTextureRegistered(), LoadTextureInternal(), and RegisterTexture().
CopyTexture()
RageTexture * RageTextureManager::CopyTexture (RageTexture * pCopy)
References RageTexture::m_iRefCount.
Referenced by ActorMultiTexture::ActorMultiTexture(), ActorMultiVertex::ActorMultiVertex(), ActorMultiTexture::AddTexture(), RageTexturePreloader::operator=(), LunaActorMultiVertex::SetTexture(), LunaSprite::SetTexture(), and Sprite::Sprite().
DeleteCachedTextures()
void RageTextureManager::DeleteCachedTextures () inline
References GarbageCollect(), and screen_changed.
Referenced by ScreenManagerUtil::AfterDeleteScreen().
DeleteTexture()
void RageTextureManager::DeleteTexture (RageTexture * t) private
References ASSERT, FAIL_M, FOREACHM, RageTexture::m_iRefCount, and SAFE_DELETE.
Referenced by GarbageCollect(), and UnloadTexture().
DiagnosticOutput()
void RageTextureManager::DiagnosticOutput () const
References Basename(), DISPLAY, RageTextureID::filename, FOREACHM_CONST, RageTexture::GetTexHandle(), RageDisplay::GetTextureDiagnostics(), RageTexture::GetTextureHeight(), RageTexture::GetTextureWidth(), LOG, RageTexture::m_iRefCount, ssprintf(), and RageLog::Trace().
DisableOddDimensionWarning()
void RageTextureManager::DisableOddDimensionWarning () inline
References m_iNoWarnAboutOddDimensions.
Referenced by ScreenSelectMusic::CheckBackgroundRequests(), Banner::Load(), LunaSprite::LoadBackground(), LunaSprite::LoadBanner(), BackgroundImpl::LoadFromSong(), LunaActorMultiVertex::LoadTexture(), and ReloadAll().
DoDelayedDelete()
void RageTextureManager::DoDelayedDelete () inline
References delayed_delete, and GarbageCollect().
Referenced by ReloadAll(), StepMania::ResetGame(), and Update().
EnableOddDimensionWarning()
void RageTextureManager::EnableOddDimensionWarning () inline
References m_iNoWarnAboutOddDimensions.
Referenced by ScreenSelectMusic::CheckBackgroundRequests(), Banner::Load(), LunaSprite::LoadBackground(), LunaSprite::LoadBanner(), BackgroundImpl::LoadFromSong(), LunaActorMultiVertex::LoadTexture(), and ReloadAll().
GarbageCollect()
void RageTextureManager::GarbageCollect (GCType type) private
References delayed_delete, DeleteTexture(), FAIL_M, RageTexture::GetPolicy(), LOG, RageTextureManagerPrefs::m_bDelayedDelete, RageTexture::m_iRefCount, m_Prefs, screen_changed, ssprintf(), RageTextureID::TEX_DEFAULT, RageTextureID::TEX_VOLATILE, and RageLog::Trace().
Referenced by DeleteCachedTextures(), and DoDelayedDelete().
GetDefaultTextureID()
RageTextureID RageTextureManager::GetDefaultTextureID ()
Referenced by ActorMultiVertex::ActorMultiVertex(), FontPage::Load(), LunaActorMultiVertex::LoadTexture(), Sprite::NewBlankSprite(), and Quad::Quad().
GetDefaultTexturePolicy()
RageTextureID::TexPolicy RageTextureManager::GetDefaultTexturePolicy () const inline
References m_TexturePolicy.
Referenced by RageTextureID::Init(), Foreground::LoadFromSong(), and BackgroundImpl::LoadFromSong().
GetOddDimensionWarning()
bool RageTextureManager::GetOddDimensionWarning () const inline
References m_iNoWarnAboutOddDimensions.
Referenced by RageBitmapTexture::Create().
GetPrefs()
RageTextureManagerPrefs RageTextureManager::GetPrefs () inline
References m_Prefs.
Referenced by MovieTexture_DShow::CreateTexture(), and MovieTexture_Generic::CreateTexture().
GetScreenSurface()
RageSurface * RageTextureManager::GetScreenSurface ()
References RageDisplay::CreateScreenshot(), and DISPLAY.
Referenced by RageBitmapTexture::Create().
GetScreenTextureID()
RageTextureID RageTextureManager::GetScreenTextureID ()
Referenced by RageBitmapTexture::Create().
InvalidateTextures()
void RageTextureManager::InvalidateTextures ()
References FOREACHM, and RageTexture::Invalidate().
Referenced by RageDisplay_GLES2::TryVideoMode(), and RageDisplay_Legacy::TryVideoMode().
IsTextureRegistered()
bool RageTextureManager::IsTextureRegistered (RageTextureID ID) const
References AdjustTextureID().
Referenced by ScreenSelectMusic::AfterMusicChange(), ScreenSelectMusic::CheckBackgroundRequests(), ActorFrameTexture::Create(), ImageCache::LoadCachedImage(), Sprite::LoadFromCached(), Banner::LoadFromCachedBanner(), FadingBanner::LoadFromCachedBanner(), Sprite::LoadFromNode(), ActorMultiVertex::LoadFromNode(), and Song::ReloadFromSongDir().
LoadTexture()
RageTexture * RageTextureManager::LoadTexture (const RageTextureID & ID)
References LoadTextureInternal(), RageTexture::m_bWasUsed, RageTexture::m_lastRefTime, and RageTimer::Touch().
Referenced by ActorMultiVertex::ActorMultiVertex(), GraphBody::GraphBody(), RageTexturePreloader::Load(), AnimatedTexture::Load(), FontPage::Load(), ActorMultiVertex::LoadFromTexture(), Sprite::LoadFromTexture(), and Song::ReloadFromSongDir().
LoadTextureInternal()
RageTexture * RageTextureManager::LoadTextureInternal (RageTextureID ID) private
References AdjustTextureID(), CHECKPOINT_M, RageMovieTexture::Create(), RageTextureID::filename, FT_Movie, ActorUtil::GetFileType(), RageTexture::m_iRefCount, and ssprintf().
Referenced by LoadTexture(), and VolatileTexture().
RegisterTexture()
void RageTextureManager::RegisterTexture (RageTextureID ID, RageTexture * p)
References AdjustTextureID(), RageTextureID::filename, and RageException::Throw().
Referenced by ActorFrameTexture::Create(), and ImageCache::LoadCachedImage().
RegisterTextureForUpdating()
void RageTextureManager::RegisterTextureForUpdating (const RageTextureID & id, RageTexture * tex)
ReloadAll()
void RageTextureManager::ReloadAll ()
References DisableOddDimensionWarning(), DoDelayedDelete(), EnableOddDimensionWarning(), and FOREACHM.
Referenced by StepMania::ApplyGraphicOptions(), DebugLineReloadTheme::DoAndLog(), and HandleGlobalInputs().
SetDefaultTexturePolicy()
void RageTextureManager::SetDefaultTexturePolicy (const RageTextureID::TexPolicy & p) inline
References m_TexturePolicy.
Referenced by Foreground::LoadFromSong(), and BackgroundImpl::LoadFromSong().
SetPrefs()
bool RageTextureManager::SetPrefs (RageTextureManagerPrefs prefs)
References ASSERT, RageTextureManagerPrefs::m_iMovieColorDepth, RageTextureManagerPrefs::m_iTextureColorDepth, and m_Prefs.
Referenced by StepMania::ApplyGraphicOptions(), and StartDisplay().
UnloadTexture()
void RageTextureManager::UnloadTexture (RageTexture * t)
References ASSERT_M, DeleteTexture(), RageTextureID::filename, RageTexture::GetID(), RageTexture::GetPolicy(), RageTexture::IsAMovie(), RageTextureManagerPrefs::m_bDelayedDelete, RageTexture::m_bWasUsed, RageTexture::m_iRefCount, RageTexture::m_lastRefTime, m_Prefs, RageTimer::PeekDeltaTime(), ssprintf(), RageTextureID::TEX_DEFAULT, and RageTextureID::TEX_VOLATILE.
Referenced by ActorMultiTexture::ClearTextures(), ImageCache::LoadCachedImage(), AnimatedTexture::Unload(), RageTexturePreloader::UnloadAll(), Sprite::UnloadTexture(), ActorMultiVertex::UnloadTexture(), VolatileTexture(), ActorFrameTexture::~ActorFrameTexture(), FontPage::~FontPage(), and GraphBody::~GraphBody().
Update()
void RageTextureManager::Update (float fDeltaTime)
References DoDelayedDelete(), FOREACHM, gameplay, Screen::GetScreenType(), ScreenManager::GetTopScreen(), RageTimer::PeekDeltaTime(), SCREENMAN, RageTimer::Touch(), and RageTexture::Update().
Referenced by GameLoop::RunGameLoop().
VolatileTexture()
void RageTextureManager::VolatileTexture (const RageTextureID & ID)
References RageTexture::GetPolicy(), LoadTextureInternal(), min(), RageTextureID::TEX_VOLATILE, and UnloadTexture().
Referenced by Banner::Load().
Member Data Documentation
m_iNoWarnAboutOddDimensions
int RageTextureManager::m_iNoWarnAboutOddDimensions { 0 } private
Referenced by DisableOddDimensionWarning(), EnableOddDimensionWarning(), and GetOddDimensionWarning().
m_Prefs
RageTextureManagerPrefs RageTextureManager::m_Prefs private
Referenced by AdjustTextureID(), GarbageCollect(), GetPrefs(), SetPrefs(), and UnloadTexture().
m_TexturePolicy
RageTextureID::TexPolicy RageTextureManager::m_TexturePolicy { RageTextureID::TEX_DEFAULT } private
Referenced by GetDefaultTexturePolicy(), and SetDefaultTexturePolicy().
The documentation for this class was generated from the following files:
RageTextureManager.h
RageTextureManager.cpp