Etterna: ScreenGameplay.cpp File Reference
ScreenGameplay.cpp File Reference
#include "global.h"
#include "ScreenGameplay.h"
#include "ActorUtil.h"
#include "AdjustSync.h"
#include "ArrowEffects.h"
#include "Background.h"
#include "CommonMetrics.h"
#include "DancingCharacters.h"
#include "DownloadManager.h"
#include "Foreach.h"
#include "Foreground.h"
#include "Game.h"
#include "GameConstantsAndTypes.h"
#include "GameManager.h"
#include "GamePreferences.h"
#include "GameSoundManager.h"
#include "GameState.h"
#include "LifeMeter.h"
#include "LifeMeterBar.h"
#include "LuaBinding.h"
#include "LuaManager.h"
#include "LyricsLoader.h"
#include "NetworkSyncManager.h"
#include "NoteDataUtil.h"
#include "NoteDataWithScoring.h"
#include "Player.h"
#include "PlayerAI.h"
#include "PlayerState.h"
#include "PrefsManager.h"
#include "Profile.h"
#include "ProfileManager.h"
#include "RageLog.h"
#include "RageSoundReader.h"
#include "RageTimer.h"
#include "ScoreDisplayOni.h"
#include "ScoreDisplayPercentage.h"
#include "ScoreKeeperNormal.h"
#include "ScreenDimensions.h"
#include "ScreenManager.h"
#include "ScreenSaveSync.h"
#include "Song.h"
#include "SongManager.h"
#include "SongUtil.h"
#include "StatsManager.h"
#include "Steps.h"
#include "StepsDisplay.h"
#include "Style.h"
#include "ThemeManager.h"
#include "ThemeMetric.h"
#include "XmlFile.h"
#include "XmlFileUtil.h"
Classes
class LunaScreenGameplay
Allow Lua to have access to the ScreenGameplay.
class LunaPlayerInfo
Allow Lua to have access to the PlayerInfo.
Macros
#define SHOW_LIFE_METER_FOR_DISABLED_PLAYERS THEME->GetMetricB(m_sName, "ShowLifeMeterForDisabledPlayers")
#define SHOW_SCORE_IN_RAVE THEME->GetMetricB(m_sName, "ShowScoreInRave")
#define SONG_POSITION_METER_WIDTH THEME->GetMetricF(m_sName, "SongPositionMeterWidth")
#define CENTER_PLAYER_BLOCK
Functions
AutoScreenMessage (SM_PlayGo)
AutoScreenMessage (SM_LoadNextSong)
AutoScreenMessage (SM_StartLoadingNextSong)
AutoScreenMessage (SM_DoPrevScreen)
AutoScreenMessage (SM_DoNextScreen)
AutoScreenMessage (SM_StartHereWeGo)
AutoScreenMessage (SM_StopHereWeGo)
AutoScreenMessage (SM_BattleTrickLevel1)
AutoScreenMessage (SM_BattleTrickLevel2)
AutoScreenMessage (SM_BattleTrickLevel3)
vector< PlayerInfo >::iterator GetNextEnabledPlayerInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > &v)
vector< PlayerInfo >::iterator GetNextEnabledPlayerInfoNotDummy (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > &v)
vector< PlayerInfo >::iterator GetNextEnabledPlayerNumberInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > &v)
vector< PlayerInfo >::iterator GetNextPlayerNumberInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > &v)
vector< PlayerInfo >::iterator GetNextVisiblePlayerInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > &v)
Variables
static ThemeMetric< float > INITIAL_BACKGROUND_BRIGHTNESS ("ScreenGameplay", "InitialBackgroundBrightness")
static ThemeMetric< float > SECONDS_BETWEEN_COMMENTS ("ScreenGameplay", "SecondsBetweenComments")
static ThemeMetric< RString > SCORE_KEEPER_CLASS ("ScreenGameplay", "ScoreKeeperClass")
static ThemeMetric< bool > FORCE_IMMEDIATE_FAIL_FOR_BATTERY ("ScreenGameplay", "ForceImmediateFailForBattery")
static Preference< bool > g_bCenter1Player ("Center1Player", true)
static Preference< bool > g_bShowLyrics ("ShowLyrics", false)
static Preference< float > g_fNetStartOffset ("NetworkStartOffset", -3.0)
static Preference< bool > g_bEasterEggs ("EasterEggs", true)
Macro Definition Documentation
CENTER_PLAYER_BLOCK
#define CENTER_PLAYER_BLOCK
Value:
{                                                                          \
        edge = 0.0f;                                                           \
        screen_space = SCREEN_WIDTH;                                           \
        left_marge = margins[PLAYER_1][0];                                     \
        right_marge = margins[PLAYER_2][1];                                    \
        field_space = screen_space - left_marge - right_marge;                 \
    }
Referenced by ScreenGameplay::Init().
SHOW_LIFE_METER_FOR_DISABLED_PLAYERS
#define SHOW_LIFE_METER_FOR_DISABLED_PLAYERS THEME->GetMetricB(m_sName, "ShowLifeMeterForDisabledPlayers")
Referenced by ScreenGameplay::Init().
SHOW_SCORE_IN_RAVE
#define SHOW_SCORE_IN_RAVE THEME->GetMetricB(m_sName, "ShowScoreInRave")
Referenced by ScreenGameplay::Init().
SONG_POSITION_METER_WIDTH
#define SONG_POSITION_METER_WIDTH THEME->GetMetricF(m_sName, "SongPositionMeterWidth")
Function Documentation
AutoScreenMessage() [1/10]
AutoScreenMessage (SM_PlayGo)
AutoScreenMessage() [2/10]
AutoScreenMessage (SM_LoadNextSong)
AutoScreenMessage() [3/10]
AutoScreenMessage (SM_StartLoadingNextSong)
AutoScreenMessage() [4/10]
AutoScreenMessage (SM_DoPrevScreen)
AutoScreenMessage() [5/10]
AutoScreenMessage (SM_DoNextScreen)
AutoScreenMessage() [6/10]
AutoScreenMessage (SM_StartHereWeGo)
AutoScreenMessage() [7/10]
AutoScreenMessage (SM_StopHereWeGo)
AutoScreenMessage() [8/10]
AutoScreenMessage (SM_BattleTrickLevel1)
AutoScreenMessage() [9/10]
AutoScreenMessage (SM_BattleTrickLevel2)
AutoScreenMessage() [10/10]
AutoScreenMessage (SM_BattleTrickLevel3)
GetNextEnabledPlayerInfo()
vector<PlayerInfo>::iterator GetNextEnabledPlayerInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > & v)
GetNextEnabledPlayerInfoNotDummy()
vector<PlayerInfo>::iterator GetNextEnabledPlayerInfoNotDummy (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > & v)
GetNextEnabledPlayerNumberInfo()
vector<PlayerInfo>::iterator GetNextEnabledPlayerNumberInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > & v)
References MultiPlayer_Invalid.
GetNextPlayerNumberInfo()
vector<PlayerInfo>::iterator GetNextPlayerNumberInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > & v)
References PLAYER_INVALID.
GetNextVisiblePlayerInfo()
vector<PlayerInfo>::iterator GetNextVisiblePlayerInfo (vector< PlayerInfo >::iterator iter, vector< PlayerInfo > & v)
Variable Documentation
FORCE_IMMEDIATE_FAIL_FOR_BATTERY
ThemeMetric<bool> FORCE_IMMEDIATE_FAIL_FOR_BATTERY("ScreenGameplay", "ForceImmediateFailForBattery") static
Referenced by ScreenGameplay::LoadNextSong().
g_bCenter1Player
Preference<bool> g_bCenter1Player("Center1Player", true) static
Referenced by ScreenGameplay::Center1Player().
g_bEasterEggs
Preference<bool> g_bEasterEggs("EasterEggs", true) static
Referenced by ScreenGameplay::HandleScreenMessage().
g_bShowLyrics
Preference<bool> g_bShowLyrics("ShowLyrics", false) static
Referenced by ScreenGameplay::Init().
g_fNetStartOffset
Preference<float> g_fNetStartOffset("NetworkStartOffset", -3.0) static
Referenced by ScreenGameplay::BeginScreen().
INITIAL_BACKGROUND_BRIGHTNESS
ThemeMetric<float> INITIAL_BACKGROUND_BRIGHTNESS("ScreenGameplay", "InitialBackgroundBrightness") static
Referenced by ScreenGameplay::LoadNextSong().
SCORE_KEEPER_CLASS
ThemeMetric<RString> SCORE_KEEPER_CLASS("ScreenGameplay", "ScoreKeeperClass") static
Referenced by PlayerInfo::Load().
SECONDS_BETWEEN_COMMENTS
ThemeMetric<float> SECONDS_BETWEEN_COMMENTS("ScreenGameplay", "SecondsBetweenComments") static
Referenced by ScreenGameplay::Update().