Etterna: RageCompiledGeometry Class Reference
RageCompiledGeometry Class Reference abstract
#include <RageDisplay.h>
Classes
struct MeshInfo
Public Member Functions
virtual ~RageCompiledGeometry ()
void Set (const vector< msMesh > &vMeshes, bool bNeedsNormals)
virtual void Allocate (const vector< msMesh > &vMeshes)=0
virtual void Change (const vector< msMesh > &vMeshes)=0
virtual void Draw (int iMeshIndex) const =0
Protected Member Functions
size_t GetTotalVertices () const
size_t GetTotalTriangles () const
Protected Attributes
vector< MeshInfo > m_vMeshInfo
bool m_bNeedsNormals
bool m_bAnyNeedsTextureMatrixScale
Constructor & Destructor Documentation
~RageCompiledGeometry()
RageCompiledGeometry::~RageCompiledGeometry () virtual
References m_bNeedsNormals.
Member Function Documentation
Allocate()
virtual void RageCompiledGeometry::Allocate (const vector< msMesh > & vMeshes) pure virtual
Implemented in RageCompiledGeometryHWOGL, RageCompiledGeometrySWOGL, RageCompiledGeometrySWD3D, RageCompiledGeometryGLES2, and RageCompiledGeometryNull.
Referenced by Set().
Change()
virtual void RageCompiledGeometry::Change (const vector< msMesh > & vMeshes) pure virtual
Implemented in RageCompiledGeometryHWOGL, RageCompiledGeometrySWOGL, RageCompiledGeometrySWD3D, RageCompiledGeometryGLES2, and RageCompiledGeometryNull.
Referenced by Set(), and Model::UpdateTempGeometry().
Draw()
virtual void RageCompiledGeometry::Draw (int iMeshIndex) const pure virtual
Implemented in RageCompiledGeometryHWOGL, RageCompiledGeometrySWOGL, RageCompiledGeometrySWD3D, RageCompiledGeometryGLES2, and RageCompiledGeometryNull.
Referenced by RageDisplay_D3D::DrawCompiledGeometryInternal(), and RageDisplay_Legacy::DrawCompiledGeometryInternal().
GetTotalTriangles()
size_t RageCompiledGeometry::GetTotalTriangles () const inline protected
References m_vMeshInfo.
Referenced by RageCompiledGeometrySWD3D::Allocate().
GetTotalVertices()
size_t RageCompiledGeometry::GetTotalVertices () const inline protected
References m_vMeshInfo.
Referenced by RageCompiledGeometrySWD3D::Allocate().
Set()
void RageCompiledGeometry::Set (const vector< msMesh > & vMeshes, bool bNeedsNormals)
References Allocate(), Change(), RageCompiledGeometry::MeshInfo::iTriangleCount, RageCompiledGeometry::MeshInfo::iTriangleStart, RageCompiledGeometry::MeshInfo::iVertexCount, RageCompiledGeometry::MeshInfo::iVertexStart, m_bAnyNeedsTextureMatrixScale, m_bNeedsNormals, RageCompiledGeometry::MeshInfo::m_bNeedsTextureMatrixScale, m_vMeshInfo, msMesh::Triangles, and msMesh::Vertices.
Referenced by RageModelGeometry::LoadMilkshapeAscii(), and Model::LoadPieces().
Member Data Documentation
m_bAnyNeedsTextureMatrixScale
bool RageCompiledGeometry::m_bAnyNeedsTextureMatrixScale protected
Referenced by Set().
m_bNeedsNormals
bool RageCompiledGeometry::m_bNeedsNormals protected
Referenced by Set(), and ~RageCompiledGeometry().
m_vMeshInfo
vector<MeshInfo> RageCompiledGeometry::m_vMeshInfo protected
Referenced by RageCompiledGeometrySWD3D::Change(), RageCompiledGeometrySWD3D::Draw(), GetTotalTriangles(), GetTotalVertices(), and Set().
The documentation for this class was generated from the following files:
RageDisplay.h
RageDisplay.cpp