Etterna: ScreenPackages.cpp File Reference
ScreenPackages.cpp File Reference
#include "global.h"
#include "GameConstantsAndTypes.h"
#include "GameState.h"
#include "LocalizedString.h"
#include "RageDisplay.h"
#include "RageFile.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "ScreenManager.h"
#include "ScreenPackages.h"
#include "ScreenTextEntry.h"
#include "ThemeManager.h"
#include <cstdlib>
Functions
AutoScreenMessage (SM_BackFromURL)
REGISTER_SCREEN_CLASS (ScreenPackages)
static size_t FindEndOfHeaders (const RString &buf)
Variables
static LocalizedString VISIT_URL ("ScreenPackages", "VisitURL")
static LocalizedString DOWNLOAD_PROGRESS ("ScreenPackages", "DL @ %d KB/s")
static LocalizedString ENTER_URL ("ScreenPackages", "Enter URL")
static LocalizedString DOWNLOAD_CANCELLED ("ScreenPackages", "Download cancelled.")
static LocalizedString DOWNLOAD_FAILED ("ScreenPackages", "Failed.")
static LocalizedString INVALID_URL ("ScreenPackages", "Invalid URL.")
static LocalizedString FILE_ALREADY_EXISTS ("ScreenPackages", "File Already Exists")
static LocalizedString FAILED_TO_CONNECT ("ScreenPackages", "Failed to connect.")
static LocalizedString HEADER_SENT ("ScreenPackages", "Header Sent.")
static LocalizedString WAITING_FOR_HEADER ("ScreenPackages", "Waiting for header.")
Function Documentation
AutoScreenMessage()
AutoScreenMessage (SM_BackFromURL)
FindEndOfHeaders()
static size_t FindEndOfHeaders (const RString & buf) static
References LOG, and RageLog::Trace().
Referenced by ScreenPackages::HTTPUpdate().
REGISTER_SCREEN_CLASS()
REGISTER_SCREEN_CLASS (ScreenPackages)
Variable Documentation
DOWNLOAD_CANCELLED
LocalizedString DOWNLOAD_CANCELLED("ScreenPackages", "Download cancelled.") static
Referenced by ScreenPackages::MenuBack().
DOWNLOAD_FAILED
LocalizedString DOWNLOAD_FAILED("ScreenPackages", "Failed.") static
Referenced by ScreenPackages::CancelDownload().
DOWNLOAD_PROGRESS
LocalizedString DOWNLOAD_PROGRESS("ScreenPackages", "DL @ %d KB/s") static
Referenced by ScreenPackages::Update().
ENTER_URL
LocalizedString ENTER_URL("ScreenPackages", "Enter URL") static
Referenced by ScreenPackages::MenuStart().
FAILED_TO_CONNECT
LocalizedString FAILED_TO_CONNECT("ScreenPackages", "Failed to connect.") static
Referenced by ScreenPackages::EnterURL().
FILE_ALREADY_EXISTS
LocalizedString FILE_ALREADY_EXISTS("ScreenPackages", "File Already Exists") static
Referenced by ScreenPackages::EnterURL().
HEADER_SENT
LocalizedString HEADER_SENT("ScreenPackages", "Header Sent.") static
Referenced by ScreenPackages::EnterURL().
INVALID_URL
LocalizedString INVALID_URL("ScreenPackages", "Invalid URL.") static
Referenced by ScreenPackages::EnterURL().
VISIT_URL
LocalizedString VISIT_URL("ScreenPackages", "VisitURL") static
Referenced by ScreenPackages::HTMLParse(), and ScreenPackages::Init().
WAITING_FOR_HEADER
LocalizedString WAITING_FOR_HEADER("ScreenPackages", "Waiting for header.") static
Referenced by ScreenPackages::HTTPUpdate().