Etterna: Grade.h File Reference
Grade.h File Reference
#include "global.h"
#include "EnumHelper.h"
#include "ThemeMetric.h"
Macros
#define Grade_NoData Grade_Invalid
Have an alternative for if there is no data for grading.
#define NUM_POSSIBLE_GRADES (NUM_GRADE_TIERS_USED + 1)
#define FOREACH_PossibleGrade(g) for (Grade g = (Grade)(0); g != Grade_Invalid; g = GetNextPossibleGrade(g))
Loop through each possible Grade.
Enumerations
enum Grade {
Grade_Tier01, Grade_Tier02, Grade_Tier03, Grade_Tier04,
Grade_Tier05, Grade_Tier06, Grade_Tier07, Grade_Tier08,
Grade_Tier09, Grade_Tier10, Grade_Tier11, Grade_Tier12,
Grade_Tier13, Grade_Tier14, Grade_Tier15, Grade_Tier16,
Grade_Tier17, Grade_Tier18, Grade_Tier19, Grade_Tier20,
Grade_Failed, NUM_Grade, Grade_Invalid
}
The list of grading tiers available.
Functions
static RString GradeToString (Grade g)
Convert the grade supplied to a string representation.
RString GradeToOldString (Grade g)
Convert to the old version styled grade strings.
RString GradeToLocalizedString (Grade g)
Grade StringToGrade (const RString &s)
Convert the given RString into a proper Grade.
LuaDeclareType (Grade)
Grade GetNextPossibleGrade (Grade g)
Step through the enumerator one at a time to get the next Grade.
Variables
ThemeMetric< int > NUM_GRADE_TIERS_USED
The current number of grade tiers being used.
Detailed Description
Author
Chris Danford (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
FOREACH_PossibleGrade
#define FOREACH_PossibleGrade (g) for (Grade g = (Grade)(0); g != Grade_Invalid; g = GetNextPossibleGrade(g))
Loop through each possible Grade.
Referenced by GradeDisplay::Load(), and GradeDisplay::SetGrade().
Grade_NoData
#define Grade_NoData Grade_Invalid
Have an alternative for if there is no data for grading.
Referenced by HighScoreList::CreateNode(), LunaStatsManager::GetFinalGrade(), GameState::GetRankingFeats(), SongUtil::GetSectionNameFromSongAndSort(), GradeToOldString(), GradeToString(), ScreenNetEvaluation::HandleScreenMessage(), Profile::HasPassedSteps(), HighScoreImpl::HighScoreImpl(), ScreenEvaluation::Init(), HighScoreList::Init(), StringToGrade(), and ScreenNetEvaluation::UpdateStats().
NUM_POSSIBLE_GRADES
#define NUM_POSSIBLE_GRADES (NUM_GRADE_TIERS_USED + 1)
Referenced by GradeDisplay::Load().
Enumeration Type Documentation
Grade
enum Grade
The list of grading tiers available.
TODO: Look into a more flexible system without a fixed number of grades. -Wolfman2000
Enumerator
Grade_Tier01
Usually an AAAA
Grade_Tier02
Usually an AAA
Grade_Tier03
Usually an AA
Grade_Tier04
Usually an A
Grade_Tier05
Usually a B
Grade_Tier06
Usually a C
Grade_Tier07
Usually a D
Grade_Tier08
Grade_Tier09
Grade_Tier10
Grade_Tier11
Grade_Tier12
Grade_Tier13
Grade_Tier14
Grade_Tier15
Grade_Tier16
Grade_Tier17
Grade_Tier18
Grade_Tier19
Grade_Tier20
Grade_Failed
Usually an E
NUM_Grade
Grade_Invalid
Function Documentation
GetNextPossibleGrade()
Grade GetNextPossibleGrade (Grade g)
Step through the enumerator one at a time to get the next Grade.
Parameters
g the current Grade.
Returns
the next Grade.
References Grade_Failed, Grade_Invalid, and NUM_GRADE_TIERS_USED.
GradeToLocalizedString()
RString GradeToLocalizedString (Grade g)
References ThemeManager::GetString(), GradeToString(), ThemeManager::HasString(), and THEME.
Referenced by SongUtil::GetSectionNameFromSongAndSort(), and SMOProtocol::ProcessInput().
GradeToOldString()
RString GradeToOldString (Grade g)
Convert to the old version styled grade strings.
This is mainly for backward compatibility purposes, but the announcer also uses it. Think "AAA", "B", etc. This is only referenced in ScreenEvaluation at the moment.
Parameters
g the current Grade.
Returns
the old styled grade string.
References Grade_Failed, Grade_NoData, Grade_Tier01, Grade_Tier02, Grade_Tier03, Grade_Tier04, Grade_Tier05, Grade_Tier06, and Grade_Tier07.
Referenced by ScreenEvaluation::Init().
GradeToString()
static RString GradeToString (Grade g) inline static
Convert the grade supplied to a string representation.
This is in the header so the test sets don't require Grade.cpp (through PrefsManager), since that pulls in ThemeManager.
Parameters
g the grade to convert.
Returns
the string reprsentation.
References ASSERT_M, Grade_Failed, Grade_NoData, NUM_Grade, and ssprintf().
Referenced by HighScoreImpl::CreateEttNode(), ScoresAtRate::CreateNode(), HighScoreImpl::CreateNode(), HighScoreList::CreateNode(), HighScore::GenerateValidationKeys(), GradeToLocalizedString(), GradeDisplay::Load(), XMLProfile::LoadGeneralDataFromNode(), XMLProfile::SaveGeneralDataCreateNode(), DBProfile::SavePlayerScores(), SetCURLPOSTScore(), and GradeDisplay::SetGrade().
LuaDeclareType()
LuaDeclareType (Grade)
StringToGrade()
Grade StringToGrade (const RString & s)
Convert the given RString into a proper Grade.
Parameters
s the string to convert.
Returns
the expected Grade.
References Grade_Failed, Grade_NoData, LOG, StdString::CStdStr< CT >::MakeUpper(), NUM_Grade, and RageLog::Warn().
Referenced by HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), and HighScoreList::LoadFromNode().
Variable Documentation
NUM_GRADE_TIERS_USED
ThemeMetric<int> NUM_GRADE_TIERS_USED
The current number of grade tiers being used.
Referenced by GetNextPossibleGrade().