Etterna: Grade.cpp File Reference
Grade.cpp File Reference
#include "global.h"
#include "Grade.h"
#include "EnumHelper.h"
#include "LuaManager.h"
#include "RageLog.h"
#include "RageUtil.h"
#include "ThemeManager.h"
Functions
LuaXType (Grade)
Grade GetNextPossibleGrade (Grade g)
Step through the enumerator one at a time to get the next Grade.
RString GradeToLocalizedString (Grade g)
RString GradeToOldString (Grade g)
Convert to the old version styled grade strings.
Grade StringToGrade (const RString &sGrade)
Convert the given RString into a proper Grade.
Variables
ThemeMetric< int > NUM_GRADE_TIERS_USED ("PlayerStageStats", "NumGradeTiersUsed")
The current number of grade tiers being used.
Function Documentation
GetNextPossibleGrade()
Grade GetNextPossibleGrade (Grade g)
Step through the enumerator one at a time to get the next Grade.
Parameters
g the current Grade.
Returns
the next Grade.
References Grade_Failed, Grade_Invalid, and NUM_GRADE_TIERS_USED.
GradeToLocalizedString()
RString GradeToLocalizedString (Grade g)
References ThemeManager::GetString(), GradeToString(), ThemeManager::HasString(), and THEME.
Referenced by SongUtil::GetSectionNameFromSongAndSort(), and SMOProtocol::ProcessInput().
GradeToOldString()
RString GradeToOldString (Grade g)
Convert to the old version styled grade strings.
This is mainly for backward compatibility purposes, but the announcer also uses it. Think "AAA", "B", etc. This is only referenced in ScreenEvaluation at the moment.
Parameters
g the current Grade.
Returns
the old styled grade string.
References Grade_Failed, Grade_NoData, Grade_Tier01, Grade_Tier02, Grade_Tier03, Grade_Tier04, Grade_Tier05, Grade_Tier06, and Grade_Tier07.
Referenced by ScreenEvaluation::Init().
LuaXType()
LuaXType (Grade)
StringToGrade()
Grade StringToGrade (const RString & s)
Convert the given RString into a proper Grade.
Parameters
s the string to convert.
Returns
the expected Grade.
References Grade_Failed, Grade_NoData, LOG, StdString::CStdStr< CT >::MakeUpper(), NUM_Grade, and RageLog::Warn().
Referenced by HighScoreImpl::LoadFromEttNode(), HighScoreImpl::LoadFromNode(), and HighScoreList::LoadFromNode().
Variable Documentation
NUM_GRADE_TIERS_USED
ThemeMetric<int> NUM_GRADE_TIERS_USED("PlayerStageStats", "NumGradeTiersUsed")
The current number of grade tiers being used.
Referenced by GetNextPossibleGrade().