Etterna: LunaPlayerOptions Class Reference
LunaPlayerOptions Class Reference
Allow Lua to have access to PlayerOptions.
Public Member Functions
ENUM_INTERFACE (LifeSetting, LifeType, LifeType)
ENUM_INTERFACE (DrainSetting, DrainType, DrainType)
INT_INTERFACE (BatteryLives, BatteryLives)
FLOAT_INTERFACE (TimeSpacing, TimeSpacing, true)
FLOAT_INTERFACE (MaxScrollBPM, MaxScrollBPM, true)
FLOAT_INTERFACE (ScrollSpeed, ScrollSpeed, true)
FLOAT_INTERFACE (ScrollBPM, ScrollBPM, true)
FLOAT_INTERFACE (Boost, Accels[PlayerOptions::ACCEL_BOOST], true)
FLOAT_INTERFACE (Brake, Accels[PlayerOptions::ACCEL_BRAKE], true)
FLOAT_INTERFACE (Wave, Accels[PlayerOptions::ACCEL_WAVE], true)
FLOAT_INTERFACE (Expand, Accels[PlayerOptions::ACCEL_EXPAND], true)
FLOAT_INTERFACE (Boomerang, Accels[PlayerOptions::ACCEL_BOOMERANG], true)
FLOAT_INTERFACE (Drunk, Effects[PlayerOptions::EFFECT_DRUNK], true)
FLOAT_INTERFACE (Dizzy, Effects[PlayerOptions::EFFECT_DIZZY], true)
FLOAT_INTERFACE (Confusion, Effects[PlayerOptions::EFFECT_CONFUSION], true)
FLOAT_INTERFACE (Mini, Effects[PlayerOptions::EFFECT_MINI], true)
FLOAT_INTERFACE (Tiny, Effects[PlayerOptions::EFFECT_TINY], true)
FLOAT_INTERFACE (Flip, Effects[PlayerOptions::EFFECT_FLIP], true)
FLOAT_INTERFACE (Invert, Effects[PlayerOptions::EFFECT_INVERT], true)
FLOAT_INTERFACE (Tornado, Effects[PlayerOptions::EFFECT_TORNADO], true)
FLOAT_INTERFACE (Tipsy, Effects[PlayerOptions::EFFECT_TIPSY], true)
FLOAT_INTERFACE (Bumpy, Effects[PlayerOptions::EFFECT_BUMPY], true)
FLOAT_INTERFACE (Beat, Effects[PlayerOptions::EFFECT_BEAT], true)
FLOAT_INTERFACE (Xmode, Effects[PlayerOptions::EFFECT_XMODE], true)
FLOAT_INTERFACE (Twirl, Effects[PlayerOptions::EFFECT_TWIRL], true)
FLOAT_INTERFACE (Roll, Effects[PlayerOptions::EFFECT_ROLL], true)
FLOAT_INTERFACE (Hidden, Appearances[PlayerOptions::APPEARANCE_HIDDEN], true)
FLOAT_INTERFACE (HiddenOffset, Appearances[PlayerOptions::APPEARANCE_HIDDEN_OFFSET], true)
FLOAT_INTERFACE (Sudden, Appearances[PlayerOptions::APPEARANCE_SUDDEN], true)
FLOAT_INTERFACE (SuddenOffset, Appearances[PlayerOptions::APPEARANCE_SUDDEN_OFFSET], true)
FLOAT_INTERFACE (Stealth, Appearances[PlayerOptions::APPEARANCE_STEALTH], true)
FLOAT_INTERFACE (Blink, Appearances[PlayerOptions::APPEARANCE_BLINK], true)
FLOAT_INTERFACE (RandomVanish, Appearances[PlayerOptions::APPEARANCE_RANDOMVANISH], true)
FLOAT_INTERFACE (Reverse, Scrolls[PlayerOptions::SCROLL_REVERSE], true)
FLOAT_INTERFACE (Split, Scrolls[PlayerOptions::SCROLL_SPLIT], true)
FLOAT_INTERFACE (Alternate, Scrolls[PlayerOptions::SCROLL_ALTERNATE], true)
FLOAT_INTERFACE (Cross, Scrolls[PlayerOptions::SCROLL_CROSS], true)
FLOAT_INTERFACE (Centered, Scrolls[PlayerOptions::SCROLL_CENTERED], true)
FLOAT_INTERFACE (Dark, Dark, true)
FLOAT_INTERFACE (Blind, Blind, true)
FLOAT_INTERFACE (Cover, Cover, true)
FLOAT_INTERFACE (RandAttack, RandAttack, true)
FLOAT_INTERFACE (NoAttack, NoAttack, true)
FLOAT_INTERFACE (PlayerAutoPlay, PlayerAutoPlay, true)
FLOAT_INTERFACE (Skew, Skew, true)
FLOAT_INTERFACE (Tilt, PerspectiveTilt, true)
FLOAT_INTERFACE (Passmark, Passmark, true)
FLOAT_INTERFACE (RandomSpeed, RandomSpeed, true)
BOOL_INTERFACE (TurnNone, Turns[PlayerOptions::TURN_NONE])
BOOL_INTERFACE (Mirror, Turns[PlayerOptions::TURN_MIRROR])
BOOL_INTERFACE (Backwards, Turns[PlayerOptions::TURN_BACKWARDS])
BOOL_INTERFACE (Left, Turns[PlayerOptions::TURN_LEFT])
BOOL_INTERFACE (Right, Turns[PlayerOptions::TURN_RIGHT])
BOOL_INTERFACE (Shuffle, Turns[PlayerOptions::TURN_SHUFFLE])
BOOL_INTERFACE (SoftShuffle, Turns[PlayerOptions::TURN_SOFT_SHUFFLE])
BOOL_INTERFACE (SuperShuffle, Turns[PlayerOptions::TURN_SUPER_SHUFFLE])
BOOL_INTERFACE (NoHolds, Transforms[PlayerOptions::TRANSFORM_NOHOLDS])
BOOL_INTERFACE (NoRolls, Transforms[PlayerOptions::TRANSFORM_NOROLLS])
BOOL_INTERFACE (NoMines, Transforms[PlayerOptions::TRANSFORM_NOMINES])
BOOL_INTERFACE (Little, Transforms[PlayerOptions::TRANSFORM_LITTLE])
BOOL_INTERFACE (Wide, Transforms[PlayerOptions::TRANSFORM_WIDE])
BOOL_INTERFACE (Big, Transforms[PlayerOptions::TRANSFORM_BIG])
BOOL_INTERFACE (Quick, Transforms[PlayerOptions::TRANSFORM_QUICK])
BOOL_INTERFACE (BMRize, Transforms[PlayerOptions::TRANSFORM_BMRIZE])
BOOL_INTERFACE (Skippy, Transforms[PlayerOptions::TRANSFORM_SKIPPY])
BOOL_INTERFACE (Mines, Transforms[PlayerOptions::TRANSFORM_MINES])
BOOL_INTERFACE (AttackMines, Transforms[PlayerOptions::TRANSFORM_ATTACKMINES])
BOOL_INTERFACE (Echo, Transforms[PlayerOptions::TRANSFORM_ECHO])
BOOL_INTERFACE (Stomp, Transforms[PlayerOptions::TRANSFORM_STOMP])
BOOL_INTERFACE (JackJS, Transforms[PlayerOptions::TRANSFORM_JACKJS])
BOOL_INTERFACE (AnchorJS, Transforms[PlayerOptions::TRANSFORM_ANCHORJS])
BOOL_INTERFACE (IcyWorld, Transforms[PlayerOptions::TRANSFORM_ICYWORLD])
BOOL_INTERFACE (Planted, Transforms[PlayerOptions::TRANSFORM_PLANTED])
BOOL_INTERFACE (Floored, Transforms[PlayerOptions::TRANSFORM_FLOORED])
BOOL_INTERFACE (Twister, Transforms[PlayerOptions::TRANSFORM_TWISTER])
BOOL_INTERFACE (HoldRolls, Transforms[PlayerOptions::TRANSFORM_HOLDROLLS])
BOOL_INTERFACE (NoJumps, Transforms[PlayerOptions::TRANSFORM_NOJUMPS])
BOOL_INTERFACE (NoHands, Transforms[PlayerOptions::TRANSFORM_NOHANDS])
BOOL_INTERFACE (NoLifts, Transforms[PlayerOptions::TRANSFORM_NOLIFTS])
BOOL_INTERFACE (NoFakes, Transforms[PlayerOptions::TRANSFORM_NOFAKES])
BOOL_INTERFACE (NoQuads, Transforms[PlayerOptions::TRANSFORM_NOQUADS])
BOOL_INTERFACE (NoStretch, Transforms[PlayerOptions::TRANSFORM_NOSTRETCH])
BOOL_INTERFACE (MuteOnError, MuteOnError)
ENUM_INTERFACE (FailSetting, FailType, FailType)
ENUM_INTERFACE (MinTNSToHideNotes, MinTNSToHideNotes, TapNoteScore)
DEFINE_METHOD (UsingReverse, m_fScrolls[PlayerOptions::SCROLL_REVERSE]==1.0f)
LunaPlayerOptions ()
Public Member Functions inherited from Luna< PlayerOptions >
const std::string & GetClassName () const override
const std::string & GetBaseClassName () const override
Public Member Functions inherited from LuaBinding
LuaBinding ()
virtual ~LuaBinding ()
void Register (lua_State *L)
bool IsDerivedClass () const
Static Public Member Functions
static int IsEasierForSongAndSteps (T *p, lua_State *L)
static int NoteSkin (T *p, lua_State *L)
static void SetSpeedModApproaches (T *p, float speed)
static int CMod (T *p, lua_State *L)
static int XMod (T *p, lua_State *L)
static int MMod (T *p, lua_State *L)
static void SetPerspectiveApproach (T *p, lua_State *L, float speed)
static int Overhead (T *p, lua_State *L)
static int Incoming (T *p, lua_State *L)
static int Space (T *p, lua_State *L)
static int Hallway (T *p, lua_State *L)
static int Distant (T *p, lua_State *L)
static int GetReversePercentForColumn (T *p, lua_State *L)
static int GetStepAttacks (T *p, lua_State *L)
Static Public Member Functions inherited from Luna< PlayerOptions >
static T * check (lua_State *L, int narg, bool bIsSelf=false)
static T * get (lua_State *L, int narg)
static void PushObject (Lua *L, const std::string &sDerivedClassName, T *p)
Static Public Member Functions inherited from LuaBinding
static void RegisterTypes (lua_State *L)
static void ApplyDerivedType (Lua *L, const std::string &sClassname, void *pSelf)
static bool CheckLuaObjectType (lua_State *L, int narg, std::string const &szType)
Additional Inherited Members
Static Public Attributes inherited from Luna< PlayerOptions >
static std::string m_sClassName
static std::string m_sBaseClassName
Protected Types inherited from Luna< PlayerOptions >
using T = PlayerOptions
using binding_t = int(T *, lua_State *)
Protected Member Functions inherited from Luna< PlayerOptions >
void Register (Lua *L, int iMethods, int iMetatable) override
void AddMethod (std::string const &regName, int(*pFunc)(T *p, lua_State *L))
Static Protected Member Functions inherited from LuaBinding
static void CreateMethodsTable (lua_State *L, const std::string &szName)
static void * GetPointerFromStack (Lua *L, const std::string &sType, int iArg)
static bool Equal (lua_State *L)
static int PushEqual (lua_State *L)
Detailed Description
Allow Lua to have access to PlayerOptions.
Constructor & Destructor Documentation
LunaPlayerOptions()
LunaPlayerOptions::LunaPlayerOptions () inline
References ADD_METHOD, NoteDataUtil::AnchorJS(), NoteDataUtil::Backwards(), NoteDataUtil::Big(), NoteDataUtil::BMRize(), CMod(), Distant(), NoteDataUtil::Echo(), NoteDataUtil::Floored(), GetReversePercentForColumn(), GetStepAttacks(), Hallway(), NoteDataUtil::IcyWorld(), Incoming(), IsEasierForSongAndSteps(), NoteDataUtil::JackJS(), NoteDataUtil::Little(), MMod(), NoteSkin(), Overhead(), NoteDataUtil::Planted(), NoteDataUtil::Quick(), NoteDataUtil::Skippy(), Space(), NoteDataUtil::Stomp(), NoteDataUtil::Twister(), NoteDataUtil::Wide(), and XMod().
Member Function Documentation
BOOL_INTERFACE() [1/35]
LunaPlayerOptions::BOOL_INTERFACE (TurnNone , Turns [PlayerOptions::TURN_NONE])
BOOL_INTERFACE() [2/35]
LunaPlayerOptions::BOOL_INTERFACE (Mirror , Turns [PlayerOptions::TURN_MIRROR])
BOOL_INTERFACE() [3/35]
LunaPlayerOptions::BOOL_INTERFACE (Backwards , Turns [PlayerOptions::TURN_BACKWARDS])
BOOL_INTERFACE() [4/35]
LunaPlayerOptions::BOOL_INTERFACE (Left , Turns [PlayerOptions::TURN_LEFT])
BOOL_INTERFACE() [5/35]
LunaPlayerOptions::BOOL_INTERFACE (Right , Turns [PlayerOptions::TURN_RIGHT])
BOOL_INTERFACE() [6/35]
LunaPlayerOptions::BOOL_INTERFACE (Shuffle , Turns [PlayerOptions::TURN_SHUFFLE])
BOOL_INTERFACE() [7/35]
LunaPlayerOptions::BOOL_INTERFACE (SoftShuffle , Turns [PlayerOptions::TURN_SOFT_SHUFFLE])
BOOL_INTERFACE() [8/35]
LunaPlayerOptions::BOOL_INTERFACE (SuperShuffle , Turns [PlayerOptions::TURN_SUPER_SHUFFLE])
BOOL_INTERFACE() [9/35]
LunaPlayerOptions::BOOL_INTERFACE (NoHolds , Transforms [PlayerOptions::TRANSFORM_NOHOLDS])
BOOL_INTERFACE() [10/35]
LunaPlayerOptions::BOOL_INTERFACE (NoRolls , Transforms [PlayerOptions::TRANSFORM_NOROLLS])
BOOL_INTERFACE() [11/35]
LunaPlayerOptions::BOOL_INTERFACE (NoMines , Transforms [PlayerOptions::TRANSFORM_NOMINES])
BOOL_INTERFACE() [12/35]
LunaPlayerOptions::BOOL_INTERFACE (Little , Transforms [PlayerOptions::TRANSFORM_LITTLE])
BOOL_INTERFACE() [13/35]
LunaPlayerOptions::BOOL_INTERFACE (Wide , Transforms [PlayerOptions::TRANSFORM_WIDE])
BOOL_INTERFACE() [14/35]
LunaPlayerOptions::BOOL_INTERFACE (Big , Transforms [PlayerOptions::TRANSFORM_BIG])
BOOL_INTERFACE() [15/35]
LunaPlayerOptions::BOOL_INTERFACE (Quick , Transforms [PlayerOptions::TRANSFORM_QUICK])
BOOL_INTERFACE() [16/35]
LunaPlayerOptions::BOOL_INTERFACE (BMRize , Transforms [PlayerOptions::TRANSFORM_BMRIZE])
BOOL_INTERFACE() [17/35]
LunaPlayerOptions::BOOL_INTERFACE (Skippy , Transforms [PlayerOptions::TRANSFORM_SKIPPY])
BOOL_INTERFACE() [18/35]
LunaPlayerOptions::BOOL_INTERFACE (Mines , Transforms [PlayerOptions::TRANSFORM_MINES])
BOOL_INTERFACE() [19/35]
LunaPlayerOptions::BOOL_INTERFACE (AttackMines , Transforms [PlayerOptions::TRANSFORM_ATTACKMINES])
BOOL_INTERFACE() [20/35]
LunaPlayerOptions::BOOL_INTERFACE (Echo , Transforms [PlayerOptions::TRANSFORM_ECHO])
BOOL_INTERFACE() [21/35]
LunaPlayerOptions::BOOL_INTERFACE (Stomp , Transforms [PlayerOptions::TRANSFORM_STOMP])
BOOL_INTERFACE() [22/35]
LunaPlayerOptions::BOOL_INTERFACE (JackJS , Transforms [PlayerOptions::TRANSFORM_JACKJS])
BOOL_INTERFACE() [23/35]
LunaPlayerOptions::BOOL_INTERFACE (AnchorJS , Transforms [PlayerOptions::TRANSFORM_ANCHORJS])
BOOL_INTERFACE() [24/35]
LunaPlayerOptions::BOOL_INTERFACE (IcyWorld , Transforms [PlayerOptions::TRANSFORM_ICYWORLD])
BOOL_INTERFACE() [25/35]
LunaPlayerOptions::BOOL_INTERFACE (Planted , Transforms [PlayerOptions::TRANSFORM_PLANTED])
BOOL_INTERFACE() [26/35]
LunaPlayerOptions::BOOL_INTERFACE (Floored , Transforms [PlayerOptions::TRANSFORM_FLOORED])
BOOL_INTERFACE() [27/35]
LunaPlayerOptions::BOOL_INTERFACE (Twister , Transforms [PlayerOptions::TRANSFORM_TWISTER])
BOOL_INTERFACE() [28/35]
LunaPlayerOptions::BOOL_INTERFACE (HoldRolls , Transforms [PlayerOptions::TRANSFORM_HOLDROLLS])
BOOL_INTERFACE() [29/35]
LunaPlayerOptions::BOOL_INTERFACE (NoJumps , Transforms [PlayerOptions::TRANSFORM_NOJUMPS])
BOOL_INTERFACE() [30/35]
LunaPlayerOptions::BOOL_INTERFACE (NoHands , Transforms [PlayerOptions::TRANSFORM_NOHANDS])
BOOL_INTERFACE() [31/35]
LunaPlayerOptions::BOOL_INTERFACE (NoLifts , Transforms [PlayerOptions::TRANSFORM_NOLIFTS])
BOOL_INTERFACE() [32/35]
LunaPlayerOptions::BOOL_INTERFACE (NoFakes , Transforms [PlayerOptions::TRANSFORM_NOFAKES])
BOOL_INTERFACE() [33/35]
LunaPlayerOptions::BOOL_INTERFACE (NoQuads , Transforms [PlayerOptions::TRANSFORM_NOQUADS])
BOOL_INTERFACE() [34/35]
LunaPlayerOptions::BOOL_INTERFACE (NoStretch , Transforms [PlayerOptions::TRANSFORM_NOSTRETCH])
BOOL_INTERFACE() [35/35]
LunaPlayerOptions::BOOL_INTERFACE (MuteOnError , MuteOnError)
CMod()
static int LunaPlayerOptions::CMod (T * p, lua_State * L) inline static
References f, FArg, FArgGTEZero(), PlayerOptions::m_fMaxScrollBPM, PlayerOptions::m_fScrollBPM, PlayerOptions::m_fScrollSpeed, PlayerOptions::m_fTimeSpacing, PlayerOptions::m_SpeedfScrollBPM, OPTIONAL_RETURN_SELF, and SetSpeedModApproaches().
Referenced by LunaPlayerOptions().
DEFINE_METHOD()
LunaPlayerOptions::DEFINE_METHOD (UsingReverse , m_fScrolls [PlayerOptions::SCROLL_REVERSE] = =1.0f)
Distant()
static int LunaPlayerOptions::Distant (T * p, lua_State * L) inline static
References FArg, FArgGTEZero(), PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, PlayerOptions::m_SpeedfPerspectiveTilt, OPTIONAL_RETURN_SELF, and SetPerspectiveApproach().
Referenced by LunaPlayerOptions().
ENUM_INTERFACE() [1/4]
LunaPlayerOptions::ENUM_INTERFACE (LifeSetting , LifeType , LifeType)
ENUM_INTERFACE() [2/4]
LunaPlayerOptions::ENUM_INTERFACE (DrainSetting , DrainType , DrainType)
ENUM_INTERFACE() [3/4]
LunaPlayerOptions::ENUM_INTERFACE (FailSetting , FailType , FailType)
ENUM_INTERFACE() [4/4]
LunaPlayerOptions::ENUM_INTERFACE (MinTNSToHideNotes , MinTNSToHideNotes , TapNoteScore)
FLOAT_INTERFACE() [1/45]
LunaPlayerOptions::FLOAT_INTERFACE (TimeSpacing , TimeSpacing , true)
FLOAT_INTERFACE() [2/45]
LunaPlayerOptions::FLOAT_INTERFACE (MaxScrollBPM , MaxScrollBPM , true)
FLOAT_INTERFACE() [3/45]
LunaPlayerOptions::FLOAT_INTERFACE (ScrollSpeed , ScrollSpeed , true)
FLOAT_INTERFACE() [4/45]
LunaPlayerOptions::FLOAT_INTERFACE (ScrollBPM , ScrollBPM , true)
FLOAT_INTERFACE() [5/45]
LunaPlayerOptions::FLOAT_INTERFACE (Boost , Accels [PlayerOptions::ACCEL_BOOST], true)
FLOAT_INTERFACE() [6/45]
LunaPlayerOptions::FLOAT_INTERFACE (Brake , Accels [PlayerOptions::ACCEL_BRAKE], true)
FLOAT_INTERFACE() [7/45]
LunaPlayerOptions::FLOAT_INTERFACE (Wave , Accels [PlayerOptions::ACCEL_WAVE], true)
FLOAT_INTERFACE() [8/45]
LunaPlayerOptions::FLOAT_INTERFACE (Expand , Accels [PlayerOptions::ACCEL_EXPAND], true)
FLOAT_INTERFACE() [9/45]
LunaPlayerOptions::FLOAT_INTERFACE (Boomerang , Accels [PlayerOptions::ACCEL_BOOMERANG], true)
FLOAT_INTERFACE() [10/45]
LunaPlayerOptions::FLOAT_INTERFACE (Drunk , Effects [PlayerOptions::EFFECT_DRUNK], true)
FLOAT_INTERFACE() [11/45]
LunaPlayerOptions::FLOAT_INTERFACE (Dizzy , Effects [PlayerOptions::EFFECT_DIZZY], true)
FLOAT_INTERFACE() [12/45]
LunaPlayerOptions::FLOAT_INTERFACE (Confusion , Effects [PlayerOptions::EFFECT_CONFUSION], true)
FLOAT_INTERFACE() [13/45]
LunaPlayerOptions::FLOAT_INTERFACE (Mini , Effects [PlayerOptions::EFFECT_MINI], true)
FLOAT_INTERFACE() [14/45]
LunaPlayerOptions::FLOAT_INTERFACE (Tiny , Effects [PlayerOptions::EFFECT_TINY], true)
FLOAT_INTERFACE() [15/45]
LunaPlayerOptions::FLOAT_INTERFACE (Flip , Effects [PlayerOptions::EFFECT_FLIP], true)
FLOAT_INTERFACE() [16/45]
LunaPlayerOptions::FLOAT_INTERFACE (Invert , Effects [PlayerOptions::EFFECT_INVERT], true)
FLOAT_INTERFACE() [17/45]
LunaPlayerOptions::FLOAT_INTERFACE (Tornado , Effects [PlayerOptions::EFFECT_TORNADO], true)
FLOAT_INTERFACE() [18/45]
LunaPlayerOptions::FLOAT_INTERFACE (Tipsy , Effects [PlayerOptions::EFFECT_TIPSY], true)
FLOAT_INTERFACE() [19/45]
LunaPlayerOptions::FLOAT_INTERFACE (Bumpy , Effects [PlayerOptions::EFFECT_BUMPY], true)
FLOAT_INTERFACE() [20/45]
LunaPlayerOptions::FLOAT_INTERFACE (Beat , Effects [PlayerOptions::EFFECT_BEAT], true)
FLOAT_INTERFACE() [21/45]
LunaPlayerOptions::FLOAT_INTERFACE (Xmode , Effects [PlayerOptions::EFFECT_XMODE], true)
FLOAT_INTERFACE() [22/45]
LunaPlayerOptions::FLOAT_INTERFACE (Twirl , Effects [PlayerOptions::EFFECT_TWIRL], true)
FLOAT_INTERFACE() [23/45]
LunaPlayerOptions::FLOAT_INTERFACE (Roll , Effects [PlayerOptions::EFFECT_ROLL], true)
FLOAT_INTERFACE() [24/45]
LunaPlayerOptions::FLOAT_INTERFACE (Hidden , Appearances [PlayerOptions::APPEARANCE_HIDDEN], true)
FLOAT_INTERFACE() [25/45]
LunaPlayerOptions::FLOAT_INTERFACE (HiddenOffset , Appearances [PlayerOptions::APPEARANCE_HIDDEN_OFFSET], true)
FLOAT_INTERFACE() [26/45]
LunaPlayerOptions::FLOAT_INTERFACE (Sudden , Appearances [PlayerOptions::APPEARANCE_SUDDEN], true)
FLOAT_INTERFACE() [27/45]
LunaPlayerOptions::FLOAT_INTERFACE (SuddenOffset , Appearances [PlayerOptions::APPEARANCE_SUDDEN_OFFSET], true)
FLOAT_INTERFACE() [28/45]
LunaPlayerOptions::FLOAT_INTERFACE (Stealth , Appearances [PlayerOptions::APPEARANCE_STEALTH], true)
FLOAT_INTERFACE() [29/45]
LunaPlayerOptions::FLOAT_INTERFACE (Blink , Appearances [PlayerOptions::APPEARANCE_BLINK], true)
FLOAT_INTERFACE() [30/45]
LunaPlayerOptions::FLOAT_INTERFACE (RandomVanish , Appearances [PlayerOptions::APPEARANCE_RANDOMVANISH], true)
FLOAT_INTERFACE() [31/45]
LunaPlayerOptions::FLOAT_INTERFACE (Reverse , Scrolls [PlayerOptions::SCROLL_REVERSE], true)
FLOAT_INTERFACE() [32/45]
LunaPlayerOptions::FLOAT_INTERFACE (Split , Scrolls [PlayerOptions::SCROLL_SPLIT], true)
FLOAT_INTERFACE() [33/45]
LunaPlayerOptions::FLOAT_INTERFACE (Alternate , Scrolls [PlayerOptions::SCROLL_ALTERNATE], true)
FLOAT_INTERFACE() [34/45]
LunaPlayerOptions::FLOAT_INTERFACE (Cross , Scrolls [PlayerOptions::SCROLL_CROSS], true)
FLOAT_INTERFACE() [35/45]
LunaPlayerOptions::FLOAT_INTERFACE (Centered , Scrolls [PlayerOptions::SCROLL_CENTERED], true)
FLOAT_INTERFACE() [36/45]
LunaPlayerOptions::FLOAT_INTERFACE (Dark , Dark , true)
FLOAT_INTERFACE() [37/45]
LunaPlayerOptions::FLOAT_INTERFACE (Blind , Blind , true)
FLOAT_INTERFACE() [38/45]
LunaPlayerOptions::FLOAT_INTERFACE (Cover , Cover , true)
FLOAT_INTERFACE() [39/45]
LunaPlayerOptions::FLOAT_INTERFACE (RandAttack , RandAttack , true)
FLOAT_INTERFACE() [40/45]
LunaPlayerOptions::FLOAT_INTERFACE (NoAttack , NoAttack , true)
FLOAT_INTERFACE() [41/45]
LunaPlayerOptions::FLOAT_INTERFACE (PlayerAutoPlay , PlayerAutoPlay , true)
FLOAT_INTERFACE() [42/45]
LunaPlayerOptions::FLOAT_INTERFACE (Skew , Skew , true)
FLOAT_INTERFACE() [43/45]
LunaPlayerOptions::FLOAT_INTERFACE (Tilt , PerspectiveTilt , true)
FLOAT_INTERFACE() [44/45]
LunaPlayerOptions::FLOAT_INTERFACE (Passmark , Passmark , true)
FLOAT_INTERFACE() [45/45]
LunaPlayerOptions::FLOAT_INTERFACE (RandomSpeed , RandomSpeed , true)
GetReversePercentForColumn()
static int LunaPlayerOptions::GetReversePercentForColumn (T * p, lua_State * L) inline static
References GAMESTATE, GameState::GetCurrentStyle(), PlayerOptions::GetReversePercentForColumn(), IArg, Style::m_iColsPerPlayer, and PlayerOptions::m_pn.
Referenced by LunaPlayerOptions().
GetStepAttacks()
static int LunaPlayerOptions::GetStepAttacks (T * p, lua_State * L) inline static
References PlayerOptions::m_fNoAttack, and PlayerOptions::m_fRandAttack.
Referenced by LunaPlayerOptions().
Hallway()
static int LunaPlayerOptions::Hallway (T * p, lua_State * L) inline static
References FArg, FArgGTEZero(), PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, PlayerOptions::m_SpeedfPerspectiveTilt, OPTIONAL_RETURN_SELF, and SetPerspectiveApproach().
Referenced by LunaPlayerOptions().
Incoming()
static int LunaPlayerOptions::Incoming (T * p, lua_State * L) inline static
References FArg, FArgGTEZero(), PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, PlayerOptions::m_SpeedfSkew, OPTIONAL_RETURN_SELF, and SetPerspectiveApproach().
Referenced by LunaPlayerOptions().
INT_INTERFACE()
LunaPlayerOptions::INT_INTERFACE (BatteryLives , BatteryLives)
IsEasierForSongAndSteps()
static int LunaPlayerOptions::IsEasierForSongAndSteps (T * p, lua_State * L) inline static
References Luna< Type >::check(), PlayerOptions::IsEasierForSongAndSteps(), and L.
Referenced by LunaPlayerOptions().
MMod()
static int LunaPlayerOptions::MMod (T * p, lua_State * L) inline static
References CMOD_DEFAULT, f, FArg, FArgGTEZero(), PlayerOptions::m_fMaxScrollBPM, PlayerOptions::m_fScrollBPM, PlayerOptions::m_fScrollSpeed, PlayerOptions::m_fTimeSpacing, PlayerOptions::m_SpeedfMaxScrollBPM, OPTIONAL_RETURN_SELF, and SetSpeedModApproaches().
Referenced by LunaPlayerOptions().
NoteSkin()
static int LunaPlayerOptions::NoteSkin (T * p, lua_State * L) inline static
References CommonMetrics::DEFAULT_NOTESKIN_NAME, NoteSkinManager::DoesNoteSkinExist(), PlayerOptions::m_sNoteSkin, NOTESKIN, OPTIONAL_RETURN_SELF, and SArg.
Referenced by LunaPlayerOptions().
Overhead()
static int LunaPlayerOptions::Overhead (T * p, lua_State * L) inline static
References FArgGTEZero(), PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, OPTIONAL_RETURN_SELF, and SetPerspectiveApproach().
Referenced by LunaPlayerOptions().
SetPerspectiveApproach()
static void LunaPlayerOptions::SetPerspectiveApproach (T * p, lua_State * L, float speed) inline static
References PlayerOptions::m_SpeedfPerspectiveTilt, and PlayerOptions::m_SpeedfSkew.
Referenced by Distant(), Hallway(), Incoming(), Overhead(), and Space().
SetSpeedModApproaches()
static void LunaPlayerOptions::SetSpeedModApproaches (T * p, float speed) inline static
References PlayerOptions::m_SpeedfMaxScrollBPM, PlayerOptions::m_SpeedfScrollBPM, PlayerOptions::m_SpeedfScrollSpeed, and PlayerOptions::m_SpeedfTimeSpacing.
Referenced by CMod(), MMod(), and XMod().
Space()
static int LunaPlayerOptions::Space (T * p, lua_State * L) inline static
References FArg, FArgGTEZero(), PlayerOptions::m_fPerspectiveTilt, PlayerOptions::m_fSkew, PlayerOptions::m_SpeedfSkew, OPTIONAL_RETURN_SELF, and SetPerspectiveApproach().
Referenced by LunaPlayerOptions().
XMod()
static int LunaPlayerOptions::XMod (T * p, lua_State * L) inline static
References CMOD_DEFAULT, FArg, FArgGTEZero(), PlayerOptions::m_fMaxScrollBPM, PlayerOptions::m_fScrollBPM, PlayerOptions::m_fScrollSpeed, PlayerOptions::m_fTimeSpacing, PlayerOptions::m_SpeedfScrollSpeed, OPTIONAL_RETURN_SELF, and SetSpeedModApproaches().
Referenced by LunaPlayerOptions().
The documentation for this class was generated from the following file:
PlayerOptions.cpp