Etterna: OptionRow.cpp File Reference
OptionRow.cpp File Reference
#include "global.h"
#include "OptionRow.h"
#include "ActorUtil.h"
#include "CommonMetrics.h"
#include "Foreach.h"
#include "GameState.h"
#include "OptionRowHandler.h"
#include "RageUtil.h"
#include "Song.h"
#include "Style.h"
#include "LuaBinding.h"
Classes
class LunaOptionRow
Macros
#define ERASE_ONE_BOOL_AT_FRONT_IF_NEEDED(vbSelected)
#define INSERT_ONE_BOOL_AT_FRONT_IF_NEEDED(vbSelected)
Functions
RString ITEMS_LONG_ROW_X_NAME (size_t p)
RString MOD_ICON_X_NAME (size_t p)
Variables
const RString NEXT_ROW_NAME = "NextRow"
const RString EXIT_NAME = "Exit"
Macro Definition Documentation
ERASE_ONE_BOOL_AT_FRONT_IF_NEEDED
#define ERASE_ONE_BOOL_AT_FRONT_IF_NEEDED (vbSelected)
Value:
if (GetFirstItemGoesDown())                                                \
        (vbSelected).erase((vbSelected).begin());
Referenced by OptionRow::ExportOptions(), and OptionRow::ImportOptions().
INSERT_ONE_BOOL_AT_FRONT_IF_NEEDED
#define INSERT_ONE_BOOL_AT_FRONT_IF_NEEDED (vbSelected)
Value:
if (GetFirstItemGoesDown())                                                \
        (vbSelected).insert((vbSelected).begin(), false);
Referenced by OptionRow::ExportOptions(), and OptionRow::ImportOptions().
Function Documentation
ITEMS_LONG_ROW_X_NAME()
RString ITEMS_LONG_ROW_X_NAME (size_t p)
References ssprintf().
Referenced by OptionRowType::Load().
MOD_ICON_X_NAME()
RString MOD_ICON_X_NAME (size_t p)
References ssprintf().
Referenced by OptionRowType::Load().
Variable Documentation
EXIT_NAME
const RString EXIT_NAME = "Exit"
Referenced by OptionRow::LoadExit().
NEXT_ROW_NAME
const RString NEXT_ROW_NAME = "NextRow"
Referenced by OptionRow::ChoicesChanged().