Etterna: LinuxInputManager.cpp File Reference
LinuxInputManager.cpp File Reference
#include "LinuxInputManager.h"
#include "InputHandler_Linux_Event.h"
#include "InputHandler_Linux_Joystick.h"
#include "Foreach.h"
#include "RageInput.h"
#include "RageLog.h"
#include <string>
#include <errno.h>
Functions
RString getDevice (RString inputDir, RString type)
Variables
LinuxInputManager * LINUXINPUT
Function Documentation
getDevice()
RString getDevice (RString inputDir, RString type)
References LOG, and RageLog::Warn().
Referenced by LinuxInputManager::InitDriver(), and LinuxInputManager::LinuxInputManager().
Variable Documentation
LINUXINPUT
LinuxInputManager* LINUXINPUT
Initial value:
=
  NULL
Referenced by InputHandler_Linux_Event::InputHandler_Linux_Event(), and InputHandler_Linux_Joystick::InputHandler_Linux_Joystick().