Etterna: GameInput.h File Reference
GameInput.h File Reference
#include "EnumHelper.h"
Classes
struct GameInput
An input event specific to an InputScheme defined by a logical controller and button.
Macros
#define FOREACH_GameButton_Custom(gb)
A special way to loop through each game button.
#define GAME_BUTTON_NEXT GAME_BUTTON_CUSTOM_01
#define DANCE_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
Set up the left arrow for dance mode.
#define DANCE_BUTTON_RIGHT GAME_BUTTON_CUSTOM_02
Set up the right arrow for dance mode.
#define DANCE_BUTTON_UP GAME_BUTTON_CUSTOM_03
Set up the up arrow for dance mode.
#define DANCE_BUTTON_DOWN GAME_BUTTON_CUSTOM_04
Set up the down arrow for dance mode.
#define DANCE_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_05
Set up the upleft arrow for dance mode (solo).
#define DANCE_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_06
Set up the upright arrow for dance mode (solo).
#define NUM_DANCE_BUTTONS GAME_BUTTON_CUSTOM_07
#define PUMP_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_01
Set up the upleft arrow for pump mode.
#define PUMP_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_02
Set up the upright arrow for pump mode.
#define PUMP_BUTTON_CENTER GAME_BUTTON_CUSTOM_03
Set up the center arrow for pump mode.
#define PUMP_BUTTON_DOWNLEFT GAME_BUTTON_CUSTOM_04
Set up the downleft arrow for pump mode.
#define PUMP_BUTTON_DOWNRIGHT GAME_BUTTON_CUSTOM_05
Set up the downright arrow for pump mode.
#define NUM_PUMP_BUTTONS GAME_BUTTON_CUSTOM_06
#define KB7_BUTTON_KEY1 GAME_BUTTON_CUSTOM_01
#define KB7_BUTTON_KEY2 GAME_BUTTON_CUSTOM_02
#define KB7_BUTTON_KEY3 GAME_BUTTON_CUSTOM_03
#define KB7_BUTTON_KEY4 GAME_BUTTON_CUSTOM_04
#define KB7_BUTTON_KEY5 GAME_BUTTON_CUSTOM_05
#define KB7_BUTTON_KEY6 GAME_BUTTON_CUSTOM_06
#define KB7_BUTTON_KEY7 GAME_BUTTON_CUSTOM_07
#define NUM_KB7_BUTTONS GAME_BUTTON_CUSTOM_08
#define EZ2_BUTTON_FOOTUPLEFT GAME_BUTTON_CUSTOM_01
#define EZ2_BUTTON_FOOTUPRIGHT GAME_BUTTON_CUSTOM_02
#define EZ2_BUTTON_FOOTDOWN GAME_BUTTON_CUSTOM_03
#define EZ2_BUTTON_HANDUPLEFT GAME_BUTTON_CUSTOM_04
#define EZ2_BUTTON_HANDUPRIGHT GAME_BUTTON_CUSTOM_05
#define EZ2_BUTTON_HANDLRLEFT GAME_BUTTON_CUSTOM_06
#define EZ2_BUTTON_HANDLRRIGHT GAME_BUTTON_CUSTOM_07
#define NUM_EZ2_BUTTONS GAME_BUTTON_CUSTOM_08
#define PARA_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
#define PARA_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_02
#define PARA_BUTTON_UP GAME_BUTTON_CUSTOM_03
#define PARA_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_04
#define PARA_BUTTON_RIGHT GAME_BUTTON_CUSTOM_05
#define NUM_PARA_BUTTONS GAME_BUTTON_CUSTOM_06
#define DS3DDX_BUTTON_HANDLEFT GAME_BUTTON_CUSTOM_01
#define DS3DDX_BUTTON_FOOTDOWNLEFT GAME_BUTTON_CUSTOM_02
#define DS3DDX_BUTTON_FOOTUPLEFT GAME_BUTTON_CUSTOM_03
#define DS3DDX_BUTTON_HANDUP GAME_BUTTON_CUSTOM_04
#define DS3DDX_BUTTON_HANDDOWN GAME_BUTTON_CUSTOM_05
#define DS3DDX_BUTTON_FOOTUPRIGHT GAME_BUTTON_CUSTOM_06
#define DS3DDX_BUTTON_FOOTDOWNRIGHT GAME_BUTTON_CUSTOM_07
#define DS3DDX_BUTTON_HANDRIGHT GAME_BUTTON_CUSTOM_08
#define NUM_DS3DDX_BUTTONS GAME_BUTTON_CUSTOM_09
#define BEAT_BUTTON_KEY1 GAME_BUTTON_CUSTOM_01
#define BEAT_BUTTON_KEY2 GAME_BUTTON_CUSTOM_02
#define BEAT_BUTTON_KEY3 GAME_BUTTON_CUSTOM_03
#define BEAT_BUTTON_KEY4 GAME_BUTTON_CUSTOM_04
#define BEAT_BUTTON_KEY5 GAME_BUTTON_CUSTOM_05
#define BEAT_BUTTON_KEY6 GAME_BUTTON_CUSTOM_06
#define BEAT_BUTTON_KEY7 GAME_BUTTON_CUSTOM_07
#define BEAT_BUTTON_SCRATCHUP GAME_BUTTON_CUSTOM_08
#define BEAT_BUTTON_SCRATCHDOWN GAME_BUTTON_CUSTOM_09
#define NUM_BEAT_BUTTONS GAME_BUTTON_CUSTOM_10
#define MANIAX_BUTTON_HANDUPLEFT GAME_BUTTON_CUSTOM_01
#define MANIAX_BUTTON_HANDUPRIGHT GAME_BUTTON_CUSTOM_02
#define MANIAX_BUTTON_HANDLRLEFT GAME_BUTTON_CUSTOM_03
#define MANIAX_BUTTON_HANDLRRIGHT GAME_BUTTON_CUSTOM_04
#define NUM_MANIAX_BUTTONS GAME_BUTTON_CUSTOM_05
#define TECHNO_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
#define TECHNO_BUTTON_RIGHT GAME_BUTTON_CUSTOM_02
#define TECHNO_BUTTON_UP GAME_BUTTON_CUSTOM_03
#define TECHNO_BUTTON_DOWN GAME_BUTTON_CUSTOM_04
#define TECHNO_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_05
#define TECHNO_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_06
#define TECHNO_BUTTON_CENTER GAME_BUTTON_CUSTOM_07
#define TECHNO_BUTTON_DOWNLEFT GAME_BUTTON_CUSTOM_08
#define TECHNO_BUTTON_DOWNRIGHT GAME_BUTTON_CUSTOM_09
#define NUM_TECHNO_BUTTONS GAME_BUTTON_CUSTOM_10
#define POPN_BUTTON_LEFT_WHITE GAME_BUTTON_CUSTOM_01
#define POPN_BUTTON_LEFT_YELLOW GAME_BUTTON_CUSTOM_02
#define POPN_BUTTON_LEFT_GREEN GAME_BUTTON_CUSTOM_03
#define POPN_BUTTON_LEFT_BLUE GAME_BUTTON_CUSTOM_04
#define POPN_BUTTON_RED GAME_BUTTON_CUSTOM_05
#define POPN_BUTTON_RIGHT_BLUE GAME_BUTTON_CUSTOM_06
#define POPN_BUTTON_RIGHT_GREEN GAME_BUTTON_CUSTOM_07
#define POPN_BUTTON_RIGHT_YELLOW GAME_BUTTON_CUSTOM_08
#define POPN_BUTTON_RIGHT_WHITE GAME_BUTTON_CUSTOM_09
#define NUM_POPN_BUTTONS GAME_BUTTON_CUSTOM_10
#define LIGHTS_BUTTON_MARQUEE_UP_LEFT GAME_BUTTON_CUSTOM_01
#define LIGHTS_BUTTON_MARQUEE_UP_RIGHT GAME_BUTTON_CUSTOM_02
#define LIGHTS_BUTTON_MARQUEE_LR_LEFT GAME_BUTTON_CUSTOM_03
#define LIGHTS_BUTTON_MARQUEE_LR_RIGHT GAME_BUTTON_CUSTOM_04
#define LIGHTS_BUTTON_BUTTONS_LEFT GAME_BUTTON_CUSTOM_05
#define LIGHTS_BUTTON_BUTTONS_RIGHT GAME_BUTTON_CUSTOM_06
#define LIGHTS_BUTTON_BASS_LEFT GAME_BUTTON_CUSTOM_07
#define LIGHTS_BUTTON_BASS_RIGHT GAME_BUTTON_CUSTOM_08
#define NUM_LIGHTS_BUTTONS GAME_BUTTON_CUSTOM_09
#define GAME_BUTTON_LEFT GAME_BUTTON_MENULEFT
#define GAME_BUTTON_RIGHT GAME_BUTTON_MENURIGHT
#define GAME_BUTTON_UP GAME_BUTTON_MENUUP
#define GAME_BUTTON_DOWN GAME_BUTTON_MENUDOWN
#define GAME_BUTTON_START GAME_BUTTON_START
#define GAME_BUTTON_BACK GAME_BUTTON_BACK
#define GAME_BUTTON_RESTART GAME_BUTTON_RESTART
Enumerations
enum GameController { GameController_1 = 0, GameController_2, NUM_GameController, GameController_Invalid }
the list of controllers in use.
enum GameButton {
GAME_BUTTON_MENULEFT, GAME_BUTTON_MENURIGHT, GAME_BUTTON_MENUUP, GAME_BUTTON_MENUDOWN,
GAME_BUTTON_START, GAME_BUTTON_SELECT, GAME_BUTTON_BACK, GAME_BUTTON_COIN,
GAME_BUTTON_OPERATOR, GAME_BUTTON_EFFECT_UP, GAME_BUTTON_EFFECT_DOWN, GAME_BUTTON_RESTART,
GAME_BUTTON_CUSTOM_01, GAME_BUTTON_CUSTOM_02, GAME_BUTTON_CUSTOM_03, GAME_BUTTON_CUSTOM_04,
GAME_BUTTON_CUSTOM_05, GAME_BUTTON_CUSTOM_06, GAME_BUTTON_CUSTOM_07, GAME_BUTTON_CUSTOM_08,
GAME_BUTTON_CUSTOM_09, GAME_BUTTON_CUSTOM_10, GAME_BUTTON_CUSTOM_11, GAME_BUTTON_CUSTOM_12,
GAME_BUTTON_CUSTOM_13, GAME_BUTTON_CUSTOM_14, GAME_BUTTON_CUSTOM_15, GAME_BUTTON_CUSTOM_16,
GAME_BUTTON_CUSTOM_17, GAME_BUTTON_CUSTOM_18, GAME_BUTTON_CUSTOM_19, NUM_GameButton,
GameButton_Invalid
}
the list of buttons StepMania recognizes.
Functions
const RString & GameControllerToString (GameController mp)
LuaDeclareType (GameController)
RString GameButtonToString (const InputScheme *pInputs, GameButton i)
RString GameButtonToLocalizedString (const InputScheme *pInputs, GameButton i)
GameButton StringToGameButton (const InputScheme *pInputs, const RString &s)
Detailed Description
Author
Chris Danford (c) 2001-2004
LICENSE
All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Macro Definition Documentation
BEAT_BUTTON_KEY1
#define BEAT_BUTTON_KEY1 GAME_BUTTON_CUSTOM_01
BEAT_BUTTON_KEY2
#define BEAT_BUTTON_KEY2 GAME_BUTTON_CUSTOM_02
BEAT_BUTTON_KEY3
#define BEAT_BUTTON_KEY3 GAME_BUTTON_CUSTOM_03
BEAT_BUTTON_KEY4
#define BEAT_BUTTON_KEY4 GAME_BUTTON_CUSTOM_04
BEAT_BUTTON_KEY5
#define BEAT_BUTTON_KEY5 GAME_BUTTON_CUSTOM_05
BEAT_BUTTON_KEY6
#define BEAT_BUTTON_KEY6 GAME_BUTTON_CUSTOM_06
BEAT_BUTTON_KEY7
#define BEAT_BUTTON_KEY7 GAME_BUTTON_CUSTOM_07
BEAT_BUTTON_SCRATCHDOWN
#define BEAT_BUTTON_SCRATCHDOWN GAME_BUTTON_CUSTOM_09
BEAT_BUTTON_SCRATCHUP
#define BEAT_BUTTON_SCRATCHUP GAME_BUTTON_CUSTOM_08
DANCE_BUTTON_DOWN
#define DANCE_BUTTON_DOWN GAME_BUTTON_CUSTOM_04
Set up the down arrow for dance mode.
DANCE_BUTTON_LEFT
#define DANCE_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
Set up the left arrow for dance mode.
DANCE_BUTTON_RIGHT
#define DANCE_BUTTON_RIGHT GAME_BUTTON_CUSTOM_02
Set up the right arrow for dance mode.
DANCE_BUTTON_UP
#define DANCE_BUTTON_UP GAME_BUTTON_CUSTOM_03
Set up the up arrow for dance mode.
DANCE_BUTTON_UPLEFT
#define DANCE_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_05
Set up the upleft arrow for dance mode (solo).
DANCE_BUTTON_UPRIGHT
#define DANCE_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_06
Set up the upright arrow for dance mode (solo).
DS3DDX_BUTTON_FOOTDOWNLEFT
#define DS3DDX_BUTTON_FOOTDOWNLEFT GAME_BUTTON_CUSTOM_02
DS3DDX_BUTTON_FOOTDOWNRIGHT
#define DS3DDX_BUTTON_FOOTDOWNRIGHT GAME_BUTTON_CUSTOM_07
DS3DDX_BUTTON_FOOTUPLEFT
#define DS3DDX_BUTTON_FOOTUPLEFT GAME_BUTTON_CUSTOM_03
DS3DDX_BUTTON_FOOTUPRIGHT
#define DS3DDX_BUTTON_FOOTUPRIGHT GAME_BUTTON_CUSTOM_06
DS3DDX_BUTTON_HANDDOWN
#define DS3DDX_BUTTON_HANDDOWN GAME_BUTTON_CUSTOM_05
DS3DDX_BUTTON_HANDLEFT
#define DS3DDX_BUTTON_HANDLEFT GAME_BUTTON_CUSTOM_01
DS3DDX_BUTTON_HANDRIGHT
#define DS3DDX_BUTTON_HANDRIGHT GAME_BUTTON_CUSTOM_08
DS3DDX_BUTTON_HANDUP
#define DS3DDX_BUTTON_HANDUP GAME_BUTTON_CUSTOM_04
EZ2_BUTTON_FOOTDOWN
#define EZ2_BUTTON_FOOTDOWN GAME_BUTTON_CUSTOM_03
EZ2_BUTTON_FOOTUPLEFT
#define EZ2_BUTTON_FOOTUPLEFT GAME_BUTTON_CUSTOM_01
EZ2_BUTTON_FOOTUPRIGHT
#define EZ2_BUTTON_FOOTUPRIGHT GAME_BUTTON_CUSTOM_02
EZ2_BUTTON_HANDLRLEFT
#define EZ2_BUTTON_HANDLRLEFT GAME_BUTTON_CUSTOM_06
EZ2_BUTTON_HANDLRRIGHT
#define EZ2_BUTTON_HANDLRRIGHT GAME_BUTTON_CUSTOM_07
EZ2_BUTTON_HANDUPLEFT
#define EZ2_BUTTON_HANDUPLEFT GAME_BUTTON_CUSTOM_04
EZ2_BUTTON_HANDUPRIGHT
#define EZ2_BUTTON_HANDUPRIGHT GAME_BUTTON_CUSTOM_05
FOREACH_GameButton_Custom
#define FOREACH_GameButton_Custom (gb)
Value:
for (GameButton gb = GAME_BUTTON_CUSTOM_01; gb < NUM_GameButton;           \
         enum_add(gb, +1))
A special way to loop through each game button.
GAME_BUTTON_BACK
#define GAME_BUTTON_BACK GAME_BUTTON_BACK
GAME_BUTTON_DOWN
#define GAME_BUTTON_DOWN GAME_BUTTON_MENUDOWN
Referenced by ScreenContinue::Input().
GAME_BUTTON_LEFT
#define GAME_BUTTON_LEFT GAME_BUTTON_MENULEFT
Referenced by ScreenAttract::AttractInput(), ScreenContinue::Input(), ScreenNetRoom::Input(), ScreenSelectMusic::Input(), ScreenOptions::Input(), OptionsList::Input(), ScreenNetSelectMusic::LeftAndRightPressed(), ScreenSetTime::MenuStart(), and ScreenOptions::MenuStart().
GAME_BUTTON_NEXT
#define GAME_BUTTON_NEXT GAME_BUTTON_CUSTOM_01
Referenced by InputScheme::GameButtonToMenuButton(), Style::GameInputToColumn(), InputScheme::GetGameButtonInfo(), Game::GetPerButtonInfo(), InputScheme::MenuButtonToGameButtons(), and Style::StyleInputToGameInput().
GAME_BUTTON_RESTART
#define GAME_BUTTON_RESTART GAME_BUTTON_RESTART
GAME_BUTTON_RIGHT
#define GAME_BUTTON_RIGHT GAME_BUTTON_MENURIGHT
Referenced by ScreenAttract::AttractInput(), ScreenContinue::Input(), ScreenNetRoom::Input(), ScreenSelectMusic::Input(), ScreenOptions::Input(), OptionsList::Input(), ScreenNetSelectMusic::LeftAndRightPressed(), ScreenSetTime::MenuStart(), and ScreenOptions::MenuStart().
GAME_BUTTON_START
#define GAME_BUTTON_START GAME_BUTTON_START
GAME_BUTTON_UP
#define GAME_BUTTON_UP GAME_BUTTON_MENUUP
Referenced by ScreenContinue::Input().
KB7_BUTTON_KEY1
#define KB7_BUTTON_KEY1 GAME_BUTTON_CUSTOM_01
KB7_BUTTON_KEY2
#define KB7_BUTTON_KEY2 GAME_BUTTON_CUSTOM_02
KB7_BUTTON_KEY3
#define KB7_BUTTON_KEY3 GAME_BUTTON_CUSTOM_03
KB7_BUTTON_KEY4
#define KB7_BUTTON_KEY4 GAME_BUTTON_CUSTOM_04
KB7_BUTTON_KEY5
#define KB7_BUTTON_KEY5 GAME_BUTTON_CUSTOM_05
KB7_BUTTON_KEY6
#define KB7_BUTTON_KEY6 GAME_BUTTON_CUSTOM_06
KB7_BUTTON_KEY7
#define KB7_BUTTON_KEY7 GAME_BUTTON_CUSTOM_07
LIGHTS_BUTTON_BASS_LEFT
#define LIGHTS_BUTTON_BASS_LEFT GAME_BUTTON_CUSTOM_07
LIGHTS_BUTTON_BASS_RIGHT
#define LIGHTS_BUTTON_BASS_RIGHT GAME_BUTTON_CUSTOM_08
LIGHTS_BUTTON_BUTTONS_LEFT
#define LIGHTS_BUTTON_BUTTONS_LEFT GAME_BUTTON_CUSTOM_05
LIGHTS_BUTTON_BUTTONS_RIGHT
#define LIGHTS_BUTTON_BUTTONS_RIGHT GAME_BUTTON_CUSTOM_06
LIGHTS_BUTTON_MARQUEE_LR_LEFT
#define LIGHTS_BUTTON_MARQUEE_LR_LEFT GAME_BUTTON_CUSTOM_03
LIGHTS_BUTTON_MARQUEE_LR_RIGHT
#define LIGHTS_BUTTON_MARQUEE_LR_RIGHT GAME_BUTTON_CUSTOM_04
LIGHTS_BUTTON_MARQUEE_UP_LEFT
#define LIGHTS_BUTTON_MARQUEE_UP_LEFT GAME_BUTTON_CUSTOM_01
LIGHTS_BUTTON_MARQUEE_UP_RIGHT
#define LIGHTS_BUTTON_MARQUEE_UP_RIGHT GAME_BUTTON_CUSTOM_02
MANIAX_BUTTON_HANDLRLEFT
#define MANIAX_BUTTON_HANDLRLEFT GAME_BUTTON_CUSTOM_03
MANIAX_BUTTON_HANDLRRIGHT
#define MANIAX_BUTTON_HANDLRRIGHT GAME_BUTTON_CUSTOM_04
MANIAX_BUTTON_HANDUPLEFT
#define MANIAX_BUTTON_HANDUPLEFT GAME_BUTTON_CUSTOM_01
MANIAX_BUTTON_HANDUPRIGHT
#define MANIAX_BUTTON_HANDUPRIGHT GAME_BUTTON_CUSTOM_02
NUM_BEAT_BUTTONS
#define NUM_BEAT_BUTTONS GAME_BUTTON_CUSTOM_10
NUM_DANCE_BUTTONS
#define NUM_DANCE_BUTTONS GAME_BUTTON_CUSTOM_07
NUM_DS3DDX_BUTTONS
#define NUM_DS3DDX_BUTTONS GAME_BUTTON_CUSTOM_09
NUM_EZ2_BUTTONS
#define NUM_EZ2_BUTTONS GAME_BUTTON_CUSTOM_08
NUM_KB7_BUTTONS
#define NUM_KB7_BUTTONS GAME_BUTTON_CUSTOM_08
NUM_LIGHTS_BUTTONS
#define NUM_LIGHTS_BUTTONS GAME_BUTTON_CUSTOM_09
NUM_MANIAX_BUTTONS
#define NUM_MANIAX_BUTTONS GAME_BUTTON_CUSTOM_05
NUM_PARA_BUTTONS
#define NUM_PARA_BUTTONS GAME_BUTTON_CUSTOM_06
NUM_POPN_BUTTONS
#define NUM_POPN_BUTTONS GAME_BUTTON_CUSTOM_10
NUM_PUMP_BUTTONS
#define NUM_PUMP_BUTTONS GAME_BUTTON_CUSTOM_06
NUM_TECHNO_BUTTONS
#define NUM_TECHNO_BUTTONS GAME_BUTTON_CUSTOM_10
PARA_BUTTON_LEFT
#define PARA_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
PARA_BUTTON_RIGHT
#define PARA_BUTTON_RIGHT GAME_BUTTON_CUSTOM_05
PARA_BUTTON_UP
#define PARA_BUTTON_UP GAME_BUTTON_CUSTOM_03
PARA_BUTTON_UPLEFT
#define PARA_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_02
PARA_BUTTON_UPRIGHT
#define PARA_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_04
POPN_BUTTON_LEFT_BLUE
#define POPN_BUTTON_LEFT_BLUE GAME_BUTTON_CUSTOM_04
POPN_BUTTON_LEFT_GREEN
#define POPN_BUTTON_LEFT_GREEN GAME_BUTTON_CUSTOM_03
POPN_BUTTON_LEFT_WHITE
#define POPN_BUTTON_LEFT_WHITE GAME_BUTTON_CUSTOM_01
POPN_BUTTON_LEFT_YELLOW
#define POPN_BUTTON_LEFT_YELLOW GAME_BUTTON_CUSTOM_02
POPN_BUTTON_RED
#define POPN_BUTTON_RED GAME_BUTTON_CUSTOM_05
POPN_BUTTON_RIGHT_BLUE
#define POPN_BUTTON_RIGHT_BLUE GAME_BUTTON_CUSTOM_06
POPN_BUTTON_RIGHT_GREEN
#define POPN_BUTTON_RIGHT_GREEN GAME_BUTTON_CUSTOM_07
POPN_BUTTON_RIGHT_WHITE
#define POPN_BUTTON_RIGHT_WHITE GAME_BUTTON_CUSTOM_09
POPN_BUTTON_RIGHT_YELLOW
#define POPN_BUTTON_RIGHT_YELLOW GAME_BUTTON_CUSTOM_08
PUMP_BUTTON_CENTER
#define PUMP_BUTTON_CENTER GAME_BUTTON_CUSTOM_03
Set up the center arrow for pump mode.
PUMP_BUTTON_DOWNLEFT
#define PUMP_BUTTON_DOWNLEFT GAME_BUTTON_CUSTOM_04
Set up the downleft arrow for pump mode.
PUMP_BUTTON_DOWNRIGHT
#define PUMP_BUTTON_DOWNRIGHT GAME_BUTTON_CUSTOM_05
Set up the downright arrow for pump mode.
PUMP_BUTTON_UPLEFT
#define PUMP_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_01
Set up the upleft arrow for pump mode.
PUMP_BUTTON_UPRIGHT
#define PUMP_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_02
Set up the upright arrow for pump mode.
TECHNO_BUTTON_CENTER
#define TECHNO_BUTTON_CENTER GAME_BUTTON_CUSTOM_07
TECHNO_BUTTON_DOWN
#define TECHNO_BUTTON_DOWN GAME_BUTTON_CUSTOM_04
TECHNO_BUTTON_DOWNLEFT
#define TECHNO_BUTTON_DOWNLEFT GAME_BUTTON_CUSTOM_08
TECHNO_BUTTON_DOWNRIGHT
#define TECHNO_BUTTON_DOWNRIGHT GAME_BUTTON_CUSTOM_09
TECHNO_BUTTON_LEFT
#define TECHNO_BUTTON_LEFT GAME_BUTTON_CUSTOM_01
TECHNO_BUTTON_RIGHT
#define TECHNO_BUTTON_RIGHT GAME_BUTTON_CUSTOM_02
TECHNO_BUTTON_UP
#define TECHNO_BUTTON_UP GAME_BUTTON_CUSTOM_03
TECHNO_BUTTON_UPLEFT
#define TECHNO_BUTTON_UPLEFT GAME_BUTTON_CUSTOM_05
TECHNO_BUTTON_UPRIGHT
#define TECHNO_BUTTON_UPRIGHT GAME_BUTTON_CUSTOM_06
Enumeration Type Documentation
GameButton
enum GameButton
the list of buttons StepMania recognizes.
Enumerator
GAME_BUTTON_MENULEFT
Navigate the menus to the left.
GAME_BUTTON_MENURIGHT
Navigate the menus to the right.
GAME_BUTTON_MENUUP
Navigate the menus to the top.
GAME_BUTTON_MENUDOWN
Navigate the menus to the bottom.
GAME_BUTTON_START
GAME_BUTTON_SELECT
GAME_BUTTON_BACK
GAME_BUTTON_COIN
Insert a coin to play.
GAME_BUTTON_OPERATOR
Access the operator menu.
GAME_BUTTON_EFFECT_UP
GAME_BUTTON_EFFECT_DOWN
GAME_BUTTON_RESTART
GAME_BUTTON_CUSTOM_01
GAME_BUTTON_CUSTOM_02
GAME_BUTTON_CUSTOM_03
GAME_BUTTON_CUSTOM_04
GAME_BUTTON_CUSTOM_05
GAME_BUTTON_CUSTOM_06
GAME_BUTTON_CUSTOM_07
GAME_BUTTON_CUSTOM_08
GAME_BUTTON_CUSTOM_09
GAME_BUTTON_CUSTOM_10
GAME_BUTTON_CUSTOM_11
GAME_BUTTON_CUSTOM_12
GAME_BUTTON_CUSTOM_13
GAME_BUTTON_CUSTOM_14
GAME_BUTTON_CUSTOM_15
GAME_BUTTON_CUSTOM_16
GAME_BUTTON_CUSTOM_17
GAME_BUTTON_CUSTOM_18
GAME_BUTTON_CUSTOM_19
NUM_GameButton
GameButton_Invalid
GameController
enum GameController
the list of controllers in use.
Enumerator
GameController_1
The left controller
GameController_2
The right controller
NUM_GameController
The number of controllers allowed.
GameController_Invalid
Function Documentation
GameButtonToLocalizedString()
RString GameButtonToLocalizedString (const InputScheme * pInputs, GameButton i)
References GameButtonToString(), ThemeManager::GetString(), and THEME.
Referenced by ScreenMapControllers::Init(), and InputList::Update().
GameButtonToString()
RString GameButtonToString (const InputScheme * pInputs, GameButton i)
References InputScheme::GetGameButtonName().
Referenced by GameButtonToLocalizedString(), ScreenSelectMusic::Input(), Screen::PassInputToLua(), StringToGameButton(), and GameInput::ToString().
GameControllerToString()
const RString& GameControllerToString (GameController mp)
Referenced by GameInput::ToString().
LuaDeclareType()
LuaDeclareType (GameController)
StringToGameButton()
GameButton StringToGameButton (const InputScheme * pInputs, const RString & s)
References FOREACH_GameButtonInScheme, GameButton_Invalid, and GameButtonToString().
Referenced by GameInput::FromString(), and ScreenMapControllers::Init().