Etterna: DebugLineWriteProfiles Class Reference
DebugLineWriteProfiles Class Reference
Private Member Functions
RString GetDisplayTitle () override
RString GetDisplayValue () override
bool IsEnabled () override
RString GetPageName () const override
void DoAndLog (RString &sMessageOut) override
Additional Inherited Members
Public Types inherited from IDebugLine
enum Type { all_screens, gameplay_only }
Public Member Functions inherited from IDebugLine
IDebugLine ()
virtual ~IDebugLine ()=default
virtual Type GetType () const
virtual bool ForceOffAfterUse () const
Public Attributes inherited from IDebugLine
DeviceInput m_Button
Member Function Documentation
DoAndLog()
void DebugLineWriteProfiles::DoAndLog (RString & sMessageOut) inline override private virtual
Reimplemented from IDebugLine.
References IDebugLine::DoAndLog(), g_ProfileSlot, GAMESTATE, GameState::SaveCurrentSettingsToProfile(), and GameState::SavePlayerProfile().
GetDisplayTitle()
RString DebugLineWriteProfiles::GetDisplayTitle () inline override private virtual
Implements IDebugLine.
References LocalizedString::GetValue(), and WRITE_PROFILES.
GetDisplayValue()
RString DebugLineWriteProfiles::GetDisplayValue () inline override private virtual
Reimplemented from IDebugLine.
GetPageName()
RString DebugLineWriteProfiles::GetPageName () const inline override private virtual
Reimplemented from IDebugLine.
IsEnabled()
bool DebugLineWriteProfiles::IsEnabled () inline override private virtual
Implements IDebugLine.
References IsSelectProfilePersistent().
The documentation for this class was generated from the following file:
ScreenDebugOverlay.cpp