Etterna: RageTexture Class Reference
RageTexture Class Reference abstract
#include <RageTexture.h>
Public Member Functions
RageTexture (const RageTextureID &file)
virtual ~RageTexture ()=0
virtual void Update (float)
virtual void Reload ()
virtual void Invalidate ()
virtual unsigned GetTexHandle () const =0
virtual void SetPosition (float)
virtual void DecodeSeconds (float)
virtual void SetPlaybackRate (float)
virtual bool IsAMovie () const
virtual void SetLooping (bool)
int GetSourceWidth () const
int GetSourceHeight () const
int GetTextureWidth () const
int GetTextureHeight () const
int GetImageWidth () const
int GetImageHeight () const
int GetFramesWide () const
int GetFramesHigh () const
int GetSourceFrameWidth () const
int GetSourceFrameHeight () const
int GetTextureFrameWidth () const
int GetTextureFrameHeight () const
int GetImageFrameWidth () const
int GetImageFrameHeight () const
float GetSourceToImageCoordsRatioX () const
float GetImageToTexCoordsRatioX () const
float GetSourceToTexCoordsRatioX () const
float GetSourceToImageCoordsRatioY () const
float GetImageToTexCoordsRatioY () const
float GetSourceToTexCoordsRatioY () const
const RectF * GetTextureCoordRect (int frameNo) const
int GetNumFrames () const
const RageTextureID::TexPolicy & GetPolicy () const
RageTextureID::TexPolicy & GetPolicy ()
const RageTextureID & GetID () const
virtual void PushSelf (lua_State *L)
Static Public Member Functions
static void GetFrameDimensionsFromFileName (const RString &sPath, int *puFramesWide, int *puFramesHigh, int source_width=0, int source_height=0)
Public Attributes
int m_iRefCount
bool m_bWasUsed
RageTimer m_lastRefTime
Protected Member Functions
virtual void CreateFrameRects ()
Protected Attributes
int m_iSourceWidth
int m_iSourceHeight
int m_iTextureWidth
int m_iTextureHeight
int m_iImageWidth
int m_iImageHeight
int m_iFramesWide
int m_iFramesHigh
vector< RectF > m_TextureCoordRects
Private Attributes
RageTextureID m_ID
Constructor & Destructor Documentation
RageTexture()
RageTexture::RageTexture (const RageTextureID & file)
~RageTexture()
RageTexture::~RageTexture () pure virtual default
Member Function Documentation
CreateFrameRects()
void RageTexture::CreateFrameRects () protected virtual
References GetFrameDimensionsFromFileName(), GetID(), m_iFramesHigh, m_iFramesWide, m_iImageHeight, m_iImageWidth, m_iSourceHeight, m_iSourceWidth, m_iTextureHeight, m_iTextureWidth, and m_TextureCoordRects.
Referenced by RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), ImageTexture::Create(), MovieTexture_DShow::Init(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), and RageTexture_Default::RageTexture_Default().
DecodeSeconds()
virtual void RageTexture::DecodeSeconds (float) inline virtual
Reimplemented in MovieTexture_Generic.
Referenced by Sprite::Update(), and ActorMultiVertex::Update().
GetFrameDimensionsFromFileName()
void RageTexture::GetFrameDimensionsFromFileName (const RString & sPath, int * puFramesWide, int * puFramesHigh, int source_width = 0, int source_height = 0) static
References Regex::Compare(), and StringToInt().
Referenced by CreateFrameRects(), and Font::LoadFontPageSettings().
GetFramesHigh()
int RageTexture::GetFramesHigh () const inline
References m_iFramesHigh.
Referenced by RageBitmapTexture::Create(), GetImageFrameHeight(), GetSourceFrameHeight(), and GetTextureFrameHeight().
GetFramesWide()
int RageTexture::GetFramesWide () const inline
References m_iFramesWide.
Referenced by RageBitmapTexture::Create(), GetImageFrameWidth(), GetSourceFrameWidth(), and GetTextureFrameWidth().
GetID()
const RageTextureID& RageTexture::GetID () const inline
References m_ID.
Referenced by ActorMultiTexture::AddTexture(), MovieTexture_Generic::CheckFrameTime(), RageBitmapTexture::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_Generic::CreateTexture(), MovieTexture_Generic::DecodeFrame(), Sprite::GetTexturePath(), MovieTexture_Generic::Init(), ActorMultiVertex::LoadFromTexture(), Sprite::LoadFromTexture(), MovieTexture_Null::MovieTexture_Null(), Sprite::SetState(), and RageTextureManager::UnloadTexture().
GetImageFrameHeight()
int RageTexture::GetImageFrameHeight () const inline
References GetFramesHigh(), and GetImageHeight().
GetImageFrameWidth()
int RageTexture::GetImageFrameWidth () const inline
References GetFramesWide(), and GetImageWidth().
GetImageHeight()
int RageTexture::GetImageHeight () const inline
References m_iImageHeight.
Referenced by GetImageFrameHeight(), GetSourceToImageCoordsRatioY(), Sprite::SetCustomImageCoords(), and Sprite::SetCustomImageRect().
GetImageToTexCoordsRatioX()
float RageTexture::GetImageToTexCoordsRatioX () const inline
References GetTextureWidth().
Referenced by LunaActorMultiVertex::FillStateFromLua(), GetSourceToTexCoordsRatioX(), and LunaActorMultiVertex::GetStateData().
GetImageToTexCoordsRatioY()
float RageTexture::GetImageToTexCoordsRatioY () const inline
References GetTextureHeight().
Referenced by LunaActorMultiVertex::FillStateFromLua(), GetSourceToTexCoordsRatioY(), and LunaActorMultiVertex::GetStateData().
GetImageWidth()
int RageTexture::GetImageWidth () const inline
References m_iImageWidth.
Referenced by GetImageFrameWidth(), GetSourceToImageCoordsRatioX(), Sprite::SetCustomImageCoords(), and Sprite::SetCustomImageRect().
GetNumFrames()
int RageTexture::GetNumFrames () const inline
References m_iFramesHigh, and m_iFramesWide.
Referenced by LunaRageTexture::GetNumFrames(), GetTextureCoordRect(), FontPage::Load(), Font::Load(), Sprite::LoadFromNode(), Sprite::LoadStatesFromTexture(), LunaSprite::SetStateProperties(), and FontPage::SetTextureCoords().
GetPolicy() [1/2]
const RageTextureID::TexPolicy& RageTexture::GetPolicy () const inline
References m_ID.
Referenced by RageTextureManager::GarbageCollect(), RageTextureManager::UnloadTexture(), and RageTextureManager::VolatileTexture().
GetPolicy() [2/2]
RageTextureID::TexPolicy& RageTexture::GetPolicy () inline
References m_ID.
GetSourceFrameHeight()
int RageTexture::GetSourceFrameHeight () const inline
References GetFramesHigh(), and GetSourceHeight().
Referenced by FontPage::Load(), Sprite::SetTexture(), and FontPage::SetTextureCoords().
GetSourceFrameWidth()
int RageTexture::GetSourceFrameWidth () const inline
References GetFramesWide(), and GetSourceWidth().
Referenced by FontPage::Load(), FontPage::SetExtraPixels(), Sprite::SetTexture(), and FontPage::SetTextureCoords().
GetSourceHeight()
int RageTexture::GetSourceHeight () const inline
References m_iSourceHeight.
Referenced by RageBitmapTexture::Create(), GetSourceFrameHeight(), GetSourceToImageCoordsRatioY(), and ActorMultiTexture::SetSizeFromTexture().
GetSourceToImageCoordsRatioX()
float RageTexture::GetSourceToImageCoordsRatioX () const inline
References GetImageWidth(), and GetSourceWidth().
Referenced by GetSourceToTexCoordsRatioX().
GetSourceToImageCoordsRatioY()
float RageTexture::GetSourceToImageCoordsRatioY () const inline
References GetImageHeight(), and GetSourceHeight().
Referenced by GetSourceToTexCoordsRatioY().
GetSourceToTexCoordsRatioX()
float RageTexture::GetSourceToTexCoordsRatioX () const inline
References GetImageToTexCoordsRatioX(), and GetSourceToImageCoordsRatioX().
Referenced by Sprite::LoadFromNode(), FontPage::SetExtraPixels(), and FontPage::SetTextureCoords().
GetSourceToTexCoordsRatioY()
float RageTexture::GetSourceToTexCoordsRatioY () const inline
References GetImageToTexCoordsRatioY(), and GetSourceToImageCoordsRatioY().
Referenced by Sprite::LoadFromNode().
GetSourceWidth()
int RageTexture::GetSourceWidth () const inline
References m_iSourceWidth.
Referenced by RageBitmapTexture::Create(), GetSourceFrameWidth(), GetSourceToImageCoordsRatioX(), and ActorMultiTexture::SetSizeFromTexture().
GetTexHandle()
virtual unsigned RageTexture::GetTexHandle () const pure virtual
Implemented in ImageTexture, RageMovieTexture_Generic_Intermediate, RageTexture_Default, MovieTexture_Generic, MovieTexture_DShow, RageTextureRenderTarget, RageBitmapTexture, and MovieTexture_Null.
Referenced by RageTextureManager::DiagnosticOutput(), NoteDisplay::DrawHoldPart(), Model::DrawPrimitives(), ActorMultiVertex::DrawPrimitives(), GraphBody::DrawPrimitives(), Sprite::DrawTexture(), and MovieTexture_Generic::UpdateFrame().
GetTextureCoordRect()
const RectF * RageTexture::GetTextureCoordRect (int frameNo) const
References GetNumFrames(), and m_TextureCoordRects.
Referenced by LunaRageTexture::GetTextureCoordRect(), Sprite::LoadFromNode(), Sprite::LoadStatesFromTexture(), LunaSprite::SetStateProperties(), FontPage::SetTextureCoords(), and GraphDisplay::UpdateVerts().
GetTextureFrameHeight()
int RageTexture::GetTextureFrameHeight () const inline
References GetFramesHigh(), and GetTextureHeight().
GetTextureFrameWidth()
int RageTexture::GetTextureFrameWidth () const inline
References GetFramesWide(), and GetTextureWidth().
GetTextureHeight()
int RageTexture::GetTextureHeight () const inline
References m_iTextureHeight.
Referenced by Sprite::AddImageCoords(), RageTextureManager::DiagnosticOutput(), GetImageToTexCoordsRatioY(), GetTextureFrameHeight(), Sprite::SetCustomImageCoords(), Sprite::SetCustomImageRect(), and Sprite::SetTexture().
GetTextureWidth()
int RageTexture::GetTextureWidth () const inline
References m_iTextureWidth.
Referenced by Sprite::AddImageCoords(), RageTextureManager::DiagnosticOutput(), GetImageToTexCoordsRatioX(), GetTextureFrameWidth(), Sprite::SetCustomImageCoords(), Sprite::SetCustomImageRect(), and Sprite::SetTexture().
Invalidate()
virtual void RageTexture::Invalidate () inline virtual
Reimplemented in ImageTexture, RageMovieTexture_Generic_Intermediate, MovieTexture_Generic, MovieTexture_DShow, RageTextureRenderTarget, RageBitmapTexture, and MovieTexture_Null.
Referenced by MovieTexture_Generic::Invalidate(), and RageTextureManager::InvalidateTextures().
IsAMovie()
virtual bool RageTexture::IsAMovie () const inline virtual
Reimplemented in RageMovieTexture_Generic_Intermediate, and RageMovieTexture.
Referenced by FadingBanner::Load(), and RageTextureManager::UnloadTexture().
PushSelf()
virtual void RageTexture::PushSelf (lua_State * L) virtual
Reimplemented in RageTextureRenderTarget.
Referenced by LunaActorFrameTexture::GetTexture(), LunaActorMultiVertex::GetTexture(), and LunaSprite::GetTexture().
Reload()
virtual void RageTexture::Reload () inline virtual
Reimplemented in ImageTexture, RageMovieTexture_Generic_Intermediate, MovieTexture_Generic, MovieTexture_DShow, RageMovieTexture, RageTextureRenderTarget, MovieTexture_Null, and RageBitmapTexture.
Referenced by LunaRageTexture::Reload(), and Song::ReloadFromSongDir().
SetLooping()
virtual void RageTexture::SetLooping (bool) inline virtual
Reimplemented in MovieTexture_Generic, MovieTexture_DShow, RageMovieTexture, and MovieTexture_Null.
Referenced by LunaRageTexture::loop().
SetPlaybackRate()
virtual void RageTexture::SetPlaybackRate (float) inline virtual
Reimplemented in MovieTexture_Generic, MovieTexture_DShow, RageMovieTexture, and MovieTexture_Null.
Referenced by LunaRageTexture::rate().
SetPosition()
virtual void RageTexture::SetPosition (float) inline virtual
Reimplemented in MovieTexture_Generic, MovieTexture_DShow, RageMovieTexture, and MovieTexture_Null.
Referenced by LunaRageTexture::position(), Sprite::SetSecondsIntoAnimation(), and ActorMultiVertex::SetSecondsIntoAnimation().
Update()
virtual void RageTexture::Update (float) inline virtual
Reimplemented in MovieTexture_DShow, RageMovieTexture, and MovieTexture_Null.
Referenced by RageTextureManager::Update().
Member Data Documentation
m_bWasUsed
bool RageTexture::m_bWasUsed
Referenced by ActorFrameTexture::Create(), RageTextureManager::LoadTexture(), and RageTextureManager::UnloadTexture().
m_ID
RageTextureID RageTexture::m_ID private
Referenced by GetID(), and GetPolicy().
m_iFramesHigh
int RageTexture::m_iFramesHigh protected
Referenced by RageTextureRenderTarget::Create(), CreateFrameRects(), GetFramesHigh(), GetNumFrames(), and MovieTexture_Null::MovieTexture_Null().
m_iFramesWide
int RageTexture::m_iFramesWide protected
Referenced by RageTextureRenderTarget::Create(), CreateFrameRects(), GetFramesWide(), GetNumFrames(), and MovieTexture_Null::MovieTexture_Null().
m_iImageHeight
int RageTexture::m_iImageHeight protected
Referenced by RageTextureRenderTarget::BeginRenderingTo(), MovieTexture_DShow::CheckFrame(), RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_Generic::CreateTexture(), RageMovieTexture_Generic_Intermediate::CreateTexture(), GetImageHeight(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), RageTexture_Default::RageTexture_Default(), and MovieTexture_Generic::UpdateFrame().
m_iImageWidth
int RageTexture::m_iImageWidth protected
Referenced by RageTextureRenderTarget::BeginRenderingTo(), MovieTexture_DShow::CheckFrame(), RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_Generic::CreateTexture(), RageMovieTexture_Generic_Intermediate::CreateTexture(), GetImageWidth(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), RageTexture_Default::RageTexture_Default(), and MovieTexture_Generic::UpdateFrame().
m_iRefCount
int RageTexture::m_iRefCount
Referenced by RageTextureManager::CopyTexture(), MovieTexture_Generic::CreateTexture(), RageTextureManager::DeleteTexture(), RageTextureManager::DiagnosticOutput(), RageTextureManager::GarbageCollect(), RageTextureManager::LoadTextureInternal(), RageTextureManager::UnloadTexture(), and RageTextureManager::~RageTextureManager().
m_iSourceHeight
int RageTexture::m_iSourceHeight protected
Referenced by MovieTexture_DShow::CheckFrame(), RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_Generic::CreateTexture(), GetSourceHeight(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), and RageTexture_Default::RageTexture_Default().
m_iSourceWidth
int RageTexture::m_iSourceWidth protected
Referenced by MovieTexture_DShow::CheckFrame(), RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_Generic::CreateTexture(), GetSourceWidth(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), and RageTexture_Default::RageTexture_Default().
m_iTextureHeight
int RageTexture::m_iTextureHeight protected
Referenced by RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_DShow::CreateTexture(), MovieTexture_Generic::CreateTexture(), GetTextureHeight(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), and RageTexture_Default::RageTexture_Default().
m_iTextureWidth
int RageTexture::m_iTextureWidth protected
Referenced by RageBitmapTexture::Create(), RageTextureRenderTarget::Create(), MovieTexture_DShow::Create(), ImageTexture::Create(), CreateFrameRects(), MovieTexture_DShow::CreateTexture(), MovieTexture_Generic::CreateTexture(), GetTextureWidth(), MovieTexture_Generic::Init(), MovieTexture_Null::MovieTexture_Null(), RageMovieTexture_Generic_Intermediate::RageMovieTexture_Generic_Intermediate(), and RageTexture_Default::RageTexture_Default().
m_lastRefTime
RageTimer RageTexture::m_lastRefTime
Referenced by RageTextureManager::LoadTexture(), RageTextureManager::UnloadTexture(), and FontPage::~FontPage().
m_TextureCoordRects
vector<RectF> RageTexture::m_TextureCoordRects protected
Referenced by CreateFrameRects(), GetTextureCoordRect(), and MovieTexture_DShow::Init().
The documentation for this class was generated from the following files:
RageTexture.h
RageTexture.cpp