Etterna: ComboSegment Struct Reference
ComboSegment Struct Reference
Identifies when a chart is to have a different combo multiplier value.
#include <TimingSegments.h>
Public Member Functions
TimingSegmentType GetType () const override
SegmentEffectType GetEffectType () const override
bool IsNotable () const override
void DebugPrint () const override
TimingSegment * Copy () const override
ComboSegment (int iStartRow=ROW_INVALID, int iCombo=1, int iMissCombo=1)
ComboSegment (const ComboSegment &other)
int GetCombo () const
int GetMissCombo () const
void SetCombo (int iCombo)
void SetMissCombo (int iCombo)
RString ToString (int dec) const override
vector< float > GetValues () const override
bool operator== (const ComboSegment &other) const
bool operator== (const TimingSegment &other) const override
Public Member Functions inherited from TimingSegment
TimingSegment (int iRow=ROW_INVALID)
TimingSegment (float fBeat)
TimingSegment (const TimingSegment &other)
virtual ~TimingSegment ()=default
virtual void Scale (int start, int length, int newLength)
Scales itself.
int GetRow () const
void SetRow (int iRow)
float GetBeat () const
void SetBeat (float fBeat)
bool operator< (const TimingSegment &other) const
virtual bool operator!= (const TimingSegment &other) const
Private Attributes
int m_iCombo
The amount the combo increases at this point.
int m_iMissCombo
The amount of miss combos given at this point.
Additional Inherited Members
Static Public Attributes inherited from TimingSegment
static const double EPSILON = 1e-6
Detailed Description
Identifies when a chart is to have a different combo multiplier value.
Admitedly, this would primarily be used for mission mode style charts. However, it can have its place during normal gameplay.
Constructor & Destructor Documentation
ComboSegment() [1/2]
ComboSegment::ComboSegment (int iStartRow = ROW_INVALID, int iCombo = 1, int iMissCombo = 1) inline
Referenced by Copy().
ComboSegment() [2/2]
ComboSegment::ComboSegment (const ComboSegment & other) inline
Member Function Documentation
Copy()
TimingSegment* ComboSegment::Copy () const inline override virtual
Implements TimingSegment.
References ComboSegment().
DebugPrint()
void ComboSegment::DebugPrint () const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetCombo(), GetMissCombo(), TimingSegment::GetRow(), GetType(), LOG, TimingSegmentTypeToString(), and RageLog::Trace().
GetCombo()
int ComboSegment::GetCombo () const inline
References m_iCombo.
Referenced by DebugPrint(), GetValues(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetEffectType()
SegmentEffectType ComboSegment::GetEffectType () const inline override virtual
Reimplemented from TimingSegment.
References SegmentEffectType_Indefinite.
GetMissCombo()
int ComboSegment::GetMissCombo () const inline
References m_iMissCombo.
Referenced by DebugPrint(), GetValues(), ScoreKeeperNormal::HandleTapNoteScoreInternal(), SongCacheIndex::InsertStepsTimingData(), and ToString().
GetType()
TimingSegmentType ComboSegment::GetType () const inline override virtual
Reimplemented from TimingSegment.
References SEGMENT_COMBO.
Referenced by DebugPrint(), and operator==().
GetValues()
vector< float > ComboSegment::GetValues () const override virtual
Reimplemented from TimingSegment.
References GetCombo(), and GetMissCombo().
IsNotable()
bool ComboSegment::IsNotable () const inline override virtual
Implements TimingSegment.
operator==() [1/2]
bool ComboSegment::operator== (const ComboSegment & other) const inline
References COMPARE, m_iCombo, and m_iMissCombo.
Referenced by operator==().
operator==() [2/2]
bool ComboSegment::operator== (const TimingSegment & other) const inline override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetType(), GetType(), and operator==().
SetCombo()
void ComboSegment::SetCombo (int iCombo) inline
References m_iCombo.
SetMissCombo()
void ComboSegment::SetMissCombo (int iCombo) inline
References m_iMissCombo.
ToString()
RString ComboSegment::ToString (int dec) const override virtual
Reimplemented from TimingSegment.
References TimingSegment::GetBeat(), GetCombo(), GetMissCombo(), IntToString(), and ssprintf().
Member Data Documentation
m_iCombo
int ComboSegment::m_iCombo private
The amount the combo increases at this point.
Referenced by GetCombo(), operator==(), and SetCombo().
m_iMissCombo
int ComboSegment::m_iMissCombo private
The amount of miss combos given at this point.
Referenced by GetMissCombo(), operator==(), and SetMissCombo().
The documentation for this struct was generated from the following files:
TimingSegments.h
TimingSegments.cpp