Etterna: HighScoreList Struct Reference
HighScoreList Struct Reference
The list of high scores.
#include <HighScore.h>
Public Member Functions
HighScoreList ()
Set up the HighScore List with default values.
void Init ()
int GetNumTimesPlayed () const
DateTime GetLastPlayed () const
const HighScore & GetTopScore () const
void AddHighScore (HighScore hs, int &iIndexOut, bool bIsMachine)
void IncrementPlayCount (DateTime dtLastPlayed)
void RemoveAllButOneOfEachName ()
void MergeFromOtherHSL (HighScoreList &other, bool is_machine)
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
void PushSelf (lua_State *L)
Public Attributes
vector< HighScore > vHighScores
Grade HighGrade { Grade_NoData }
Private Attributes
int iNumTimesPlayed { 0 }
DateTime dtLastPlayed
Detailed Description
The list of high scores.
Constructor & Destructor Documentation
HighScoreList()
HighScoreList::HighScoreList () inline
Set up the HighScore List with default values.
This used to call Init(), but it's better to be explicit here.
Member Function Documentation
AddHighScore()
void HighScoreList::AddHighScore (HighScore hs, int & iIndexOut, bool bIsMachine)
References HighScore::GetWifeGrade(), HighGrade, min(), and vHighScores.
Referenced by Profile::AddCategoryHighScore(), and Profile::AddStepsHighScore().
CreateNode()
XNode * HighScoreList::CreateNode () const
References XNode::AppendChild(), HighScore::CreateNode(), dtLastPlayed, DateTime::GetString(), Grade_NoData, GradeToString(), HighGrade, iNumTimesPlayed, and vHighScores.
Referenced by XMLProfile::SaveCategoryScoresCreateNode(), and XMLProfile::SaveSongScoresCreateNode().
GetLastPlayed()
DateTime HighScoreList::GetLastPlayed () const inline
References ASSERT, dtLastPlayed, and iNumTimesPlayed.
Referenced by Profile::GetSongLastPlayedDateTime().
GetNumTimesPlayed()
int HighScoreList::GetNumTimesPlayed () const inline
References iNumTimesPlayed.
Referenced by Profile::GetCategoryNumTimesPlayed(), Profile::GetSongLastPlayedDateTime(), Profile::GetSongNumTimesPlayed(), Profile::GetStepsNumTimesPlayed(), XMLProfile::SaveCategoryScoresCreateNode(), and XMLProfile::SaveSongScoresCreateNode().
GetTopScore()
const HighScore & HighScoreList::GetTopScore () const
References vHighScores.
Referenced by ScreenSelectMusic::AfterStepsOrTrailChange(), Profile::GetGrades(), PaneDisplay::GetPaneTextAndLevel(), Profile::GetSongsActual(), and Profile::HasPassedSteps().
IncrementPlayCount()
void HighScoreList::IncrementPlayCount (DateTime dtLastPlayed)
References dtLastPlayed, and iNumTimesPlayed.
Referenced by Profile::IncrementCategoryPlayCount(), and Profile::IncrementStepsPlayCount().
Init()
void HighScoreList::Init ()
References Grade_NoData, HighGrade, iNumTimesPlayed, and vHighScores.
Referenced by Profile::InitCategoryScores(), LoadFromNode(), and Profile::Profile().
LoadFromNode()
void HighScoreList::LoadFromNode (const XNode * pNode)
References ASSERT, dtLastPlayed, FOREACH_CONST_Child, DateTime::FromString(), XNode::GetName(), HighGrade, Init(), iNumTimesPlayed, min(), StringToGrade(), and vHighScores.
Referenced by XMLProfile::LoadCategoryScoresFromNode(), and XMLProfile::LoadSongScoresFromNode().
MergeFromOtherHSL()
void HighScoreList::MergeFromOtherHSL (HighScoreList & other, bool is_machine)
References dtLastPlayed, HighGrade, iNumTimesPlayed, and vHighScores.
PushSelf()
void HighScoreList::PushSelf (lua_State * L)
Referenced by LunaProfile::GetCategoryHighScoreList(), and LunaProfile::GetHighScoreList().
RemoveAllButOneOfEachName()
void HighScoreList::RemoveAllButOneOfEachName ()
References FOREACH, and vHighScores.
Member Data Documentation
dtLastPlayed
DateTime HighScoreList::dtLastPlayed private
Referenced by CreateNode(), GetLastPlayed(), IncrementPlayCount(), LoadFromNode(), and MergeFromOtherHSL().
HighGrade
Grade HighScoreList::HighGrade { Grade_NoData }
Referenced by AddHighScore(), CreateNode(), Init(), LoadFromNode(), and MergeFromOtherHSL().
iNumTimesPlayed
int HighScoreList::iNumTimesPlayed { 0 } private
Referenced by CreateNode(), GetLastPlayed(), GetNumTimesPlayed(), IncrementPlayCount(), Init(), LoadFromNode(), and MergeFromOtherHSL().
vHighScores
vector<HighScore> HighScoreList::vHighScores
Referenced by AddHighScore(), CreateNode(), LunaHighScoreList::GetHighestScoreOfName(), LunaHighScoreList::GetHighScores(), PaneDisplay::GetPaneTextAndLevel(), GameState::GetRankingFeats(), LunaHighScoreList::GetRankOfName(), GetTopScore(), Profile::GetTotalStepsWithTopGrade(), Init(), LoadFromNode(), MergeFromOtherHSL(), and RemoveAllButOneOfEachName().
The documentation for this struct was generated from the following files:
HighScore.h
HighScore.cpp