Etterna: StyleID Class Reference
StyleID Class Reference
#include <StyleUtil.h>
Public Member Functions
StyleID ()
void Unset ()
void FromStyle (const Style *p)
const Style * ToStyle () const
bool operator< (const StyleID &rhs) const
XNode * CreateNode () const
void LoadFromNode (const XNode *pNode)
bool IsValid () const
Static Public Member Functions
static void FlushCache (Song *pStaleSong)
Private Attributes
RString sGame
RString sStyle
Constructor & Destructor Documentation
StyleID()
StyleID::StyleID () inline
Member Function Documentation
CreateNode()
XNode * StyleID::CreateNode () const
References XNode::AppendAttr(), sGame, and sStyle.
Referenced by XMLProfile::SaveGeneralDataCreateNode().
FlushCache()
static void StyleID::FlushCache (Song * pStaleSong) static
FromStyle()
void StyleID::FromStyle (const Style * p)
References GAMEMAN, GameManager::GetGameForStyle(), Game::m_szName, Style::m_szName, sGame, and sStyle.
Referenced by Unset().
IsValid()
bool StyleID::IsValid () const
References sGame, and sStyle.
Referenced by XMLProfile::LoadGeneralDataFromNode().
LoadFromNode()
void StyleID::LoadFromNode (const XNode * pNode)
References ASSERT, XNode::GetAttrValue(), XNode::GetName(), sGame, sStyle, and Unset().
Referenced by XMLProfile::LoadGeneralDataFromNode().
operator<()
bool StyleID::operator< (const StyleID & rhs) const
References COMP, sGame, and sStyle.
ToStyle()
const Style * StyleID::ToStyle () const
References GameManager::GameAndStringToStyle(), GAMEMAN, sGame, sStyle, and GameManager::StringToGame().
Unset()
void StyleID::Unset () inline
References FromStyle().
Referenced by LoadFromNode().
Member Data Documentation
sGame
RString StyleID::sGame private
Referenced by CreateNode(), FromStyle(), IsValid(), LoadFromNode(), operator<(), and ToStyle().
sStyle
RString StyleID::sStyle private
Referenced by CreateNode(), FromStyle(), IsValid(), LoadFromNode(), operator<(), and ToStyle().
The documentation for this class was generated from the following files:
StyleUtil.h
StyleUtil.cpp