Etterna: CommandLineActions.cpp File Reference
CommandLineActions.cpp File Reference
#include "global.h"
#include "CommandLineActions.h"
#include "DateTime.h"
#include "FileDownload.h"
#include "Foreach.h"
#include "IniFile.h"
#include "LuaManager.h"
#include "ProductInfo.h"
#include "RageFile.h"
#include "RageFileManager.h"
#include "RageUtil.h"
#include "ScreenInstallOverlay.h"
#include "SpecialFiles.h"
#include "XmlFile.h"
#include "XmlFileUtil.h"
#include "arch/Dialog/Dialog.h"
#include "arch/LoadingWindow/LoadingWindow.h"
#include "ver.h"
Functions
static void Nsis ()
static void LuaInformation ()
static void Version ()
Print out version information.
Variables
const RString INSTALLER_LANGUAGES_DIR = "Themes/_Installer/Languages/"
The directory where languages should be installed.
Function Documentation
LuaInformation()
static void LuaInformation () static
References XNode::AppendAttr(), XNode::AppendChild(), LuaHelpers::GetLuaInformation(), DateTime::GetNowDate(), PRODUCT_FAMILY, product_version, and XmlFileUtil::SaveToFile().
Referenced by CommandLineActions::Handle().
Nsis()
static void Nsis () static
References FOREACH_CONST, FOREACH_CONST_Attr, FOREACH_CONST_Child, GetDirListing(), GetLanguageInfo(), StdString::CStdStr< CT >::MakeUpper(), RageFile::Open(), RageFile::PutLine(), IniFile::ReadFile(), StdString::CStdStr< CT >::Replace(), splitpath(), ssprintf(), LanguageInfo::szEnglishName, RageException::Throw(), and RageFile::WRITE.
Referenced by CommandLineActions::Handle().
Version()
static void Version () static
Print out version information.
HACK: This function is primarily needed for Windows users. Mac OS X and Linux print out version information on the command line regardless of any preferences (tested by shakesoda on Mac). -aj
References PRODUCT_FAMILY, product_version, sm_version_git_hash, ssprintf(), version_date, and version_time.
Referenced by CommandLineActions::Handle().
Variable Documentation
INSTALLER_LANGUAGES_DIR
const RString INSTALLER_LANGUAGES_DIR = "Themes/_Installer/Languages/"
The directory where languages should be installed.